### ISSUE TITLE
Clear formatting back color is incorrect.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1002]
**Describe the bug**

When clearing formatting the backcolor is incorrect.

**To Reproduce**
1. Go to http://localhost:4000/components/editor/test-clear-formatting.html
2. hit clear formatting
3. look at the background color button, its showing the backcolor of slate01 but there is really no background color, should be that the backcolor is "clear".

**Expected behavior**
should be that the backcolor is "clear" like the initial state

**Additional context**
Needs https://github.com/infor-design/enterprise/pull/992

**Comment by tmcconechy** [comment]
Added to the sprint as Deepak has addressed this.

**Comment by janahintal** [comment]
QA Failed. 
Tested in: https://4150-beta0-enterprise.demo.design.infor.com/components/editor/test-clear-formatting.html

Steps:
1. Goto https://4150-beta0-enterprise.demo.design.infor.com/components/editor/test-clear-formatting.html
2. Add Background color on the 2nd paragraph 
3. Add Block quote on the 2nd paragraph 
4. Clear format

**Comment by janahintal** [comment]
QA Failed. 
Issue still existing. 

Steps:
1. Goto > http://4150-rc0-enterprise.demo.design.infor.com/components/editor/test-clear-formatting.html
2. Block quote 2nd paragraph 
3. Add BG text color to the 2nd paragraph 
4. Clear format

<img width="1410" alt="screen shot 2019-02-04 at 5 37 04 pm" src="https://user-images.githubusercontent.com/45757016/52200353-8523b180-28a3-11e9-981b-e2df334cb15b.png">

**Comment by tmcconechy** [comment]
@janahintal we tested those steps in chrome and IE and were not able to reproduce any further issues.
Can you try again or provide any further info? Also try clearing browser cache.

**Comment by clepore** [comment]
We can double test this again in `rc.1` to see if it can be replicated.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
