### ISSUE TITLE
Duplicate Trigger Name 'dragstart' and 'dragend'

### ISSUE THREAD

**Issue by Milan1983** [infor-design/enterprise#1003]
**Describe the bug**
For a same  trigger name,  firing different data.

'dragend'
1. Drag and drop same item on tree
2. Fire 'dragend' trigger
3. The result it is position

**Expected behavior**
I am expecting sortable objects

**Additional context**
Reason to happen this behaviour,it is  because have a same trigger name in finish function.

'dragstart'
1. Drag and drop same item on tree
2. Fire 'dragstart' trigger
3.The  result it is position

**Expected behavior**
I am expecting sortable object

**Additional context**
Reason to happen this behaviour,it is  because have a same trigger name in handleEvents function.

[Tree_Sortable (4).html.zip](https://github.com/infor-design/enterprise/files/2479697/Tree_Sortable.4.html.zip)

**Comment by tmcconechy** [comment]
On which page can i reproduce these steps?

**Comment by Milan1983** [comment]
Happen's same thing with 'dragend'

**Comment by davidcarlsonberg** [comment]
@tmcconechy Should I start work on this as an assignee?

**Comment by tmcconechy** [comment]
Sure, i didnt see a PR from @Milan1983 .

**Comment by Milan1983** [comment]
- On  .on('dragstart.tree', function (e, pos, thisClone) {
     need to rename trigger to sortstart

- On   .on('dragend.tree', function (e, pos) {

   need to rename trigger to sortstop

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Tested it using URL: http://master-enterprise.demo.design.infor.com/components/tree/example-sortable.html. Moving this ticket to the "Done" bucket.
