### ISSUE TITLE
Typo in environment.js causes no pages to load in IE 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1004]
**Describe the bug**

The new code in environment.js is giving errors on IE 11

**To Reproduce**
1. Go to http://localhost:4000/components/editor/test-modal.html on IE 11
2. Check dev tools console

**Expected behavior**
The page to load without errors

**Screenshots**

**Platform**
- IE 11 / Edge

**Additional context**
https://github.com/infor-design/enterprise/issues/726#issuecomment-429721218

**Comment by brianjuan** [comment]
Passed QA testing. Pages are loading successfully in IE
