### ISSUE TITLE
Datagrid reset to default does not work on second attempt

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1009]
**Describe the bug**
When you arrange the columns and then use the use the reset to default button it only works on the first attempt.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/example-reorder.html'
2. reorder the datagrid buttons
3. Click on 'the reset to default button under the more button for the datagrid'
4. repeat steps 2 and 3.

**Expected behavior**
The order of the columns is not returned to the default.

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome

**Additional context**
When the resetColumns function is run the originalColumns value is then used and a reference is establisted between columns and originalColumns. 

A copy can be made an then used in the when using updateColumns. this.columnsFromString(JSON.stringify(this.originalColumns))

```
  /**
  * Reset Columns to defaults (used on restore menu item)
  */
  resetColumns() {
    if (this.canUseLocalStorage()) {
      localStorage.removeItem(this.uniqueId('columns'));
    }

    if (this.originalColumns) {
      const columnGroups = this.settings.columnGroups && this.originalColGroups ?
        this.originalColGroups : null;
      this.updateColumns(this.columnsFromString(JSON.stringify(this.originalColumns)), columnGroups);
    }

    this.clearFilter();
  },
```

**Comment by marknolaninfor** [comment]
Are you able to give me permission, so that I can create a branch instead of the requirement to update my forked version?

**Comment by tmcconechy** [comment]
We cant, the reason being it costs money on our github licenses, so reserving it just for people directly on our team. You should be able to work on the fork. Here are some links on updating the fork

https://help.github.com/articles/syncing-a-fork/

https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser

Anything i missed @clepore  ?

**Comment by clepore** [comment]
That's pretty much it. Because the github costs come out of the H&L budget, we only pay for our team, but we made it open source so everyone can contribute to circumnavigate that barrier.
