### ISSUE TITLE
Dropdown with Icons: Searching in IE causes the icons to disappear and replaced with "undefined"

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1011]
**Describe the bug**
Dropdown with Icons: Searching in IE causes the icons to disappear and replaced with "undefined".

**To Reproduce**
1. Go to http://localhost:4000/components/dropdown/example-icons.html in **Windows IE**
2. Type "icon" in the dropdown field
3. Notice that the icons will disappear and replaced by "undefined"

**Expected behavior**
Icons should not disappear when searching with the dropdown field

**Screenshots**
<img width="1113" alt="screen shot 2018-10-16 at 6 50 03 pm" src="https://user-images.githubusercontent.com/39508864/47011464-991c9980-d174-11e8-9bb4-c2849b02f13b.png">

**Platform**
 - Windows IE

**Additional context**
No additional context.

**Comment by brianjuan** [comment]
http://localhost:4000/components/dropdown/example-icons.html
http://4120-beta0-enterprise.demo.design.infor.com/components/dropdown/example-icons.html

Issue still happens in IE when you clear the dropdown searchfield.

<img width="858" alt="screen shot 2018-10-23 at 12 25 15 pm" src="https://user-images.githubusercontent.com/39508864/47335634-c01c2380-d6be-11e8-8a70-b7b72aafffb4.png">

**Comment by tmcconechy** [comment]
@tjamesallen15 Can you please check this again?

**Comment by tjamesallen15** [comment]
I'm checking on this. Brian told me yesterday about this issue. He showed me what's wrong step by step. @tmcconechy

**Comment by brianjuan** [comment]
http://4120-rc1-enterprise.demo.design.infor.com/components/dropdown/example-icons.html
Passed QA testing on Windows IE.
