### ISSUE TITLE
StepProcess: Main container clipped by header for certain screen size

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#1012]
**Describe the bug**
The main content area height is wrong when screen size is at 1024 x 768. (_seems to break around 1200 x ..._) The top of the main content is under the header area at this point.

**To Reproduce**
1. Go to http://localhost:4000/patterns/stepprocess.html

**Expected behavior**
Content should not be clipped or go under the header

**Screenshots**
![step-process-height](https://user-images.githubusercontent.com/1056684/47021557-49f94900-d121-11e8-81ec-486d5f18e64c.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by EdwardCoyle** [comment]
I tested this back a few versions back in IE, Windows Chrome, iOS Safari, etc, and wasn't seeing the issue described:

- https://master-enterprise.demo.design.infor.com/patterns/stepprocess
- https://4150-enterprise.demo.design.infor.com/patterns/stepprocess
- https://4140-enterprise.demo.design.infor.com/patterns/stepprocess
- https://4130-enterprise.demo.design.infor.com/patterns/stepprocess

I think we may have inadvertently fixed this in another issue and not realized it... though I can't seem to pinpoint where?  Maybe something in the Stepprocess ".custom-toolbar", the sticky header code, or the form fields themselves?

@krishollenbeck can you recheck this and confirm that it's working/not working?

**Comment by krishollenbeck** [comment]
@EdwardCoyle Yeah I don't think this is an issue anymore.
