### ISSUE TITLE
Stepprocess: Radio button z-index issue

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#1014]
**Describe the bug**
Radio buttons show up on top of the header with large amounts of content.

**To Reproduce**
1. Edit stepprocess-markup.html,  (add a radio button and enough content to force overflow)
2. Go to http://localhost:4000/patterns/stepprocess-markup.html
3. Scroll until radio buttons are at the top. Notice the radio buttons are on top of the header.

**Expected behavior**
The radio buttons should stay behind the header when scrolling.

**Screenshots**
![radio-button-zindex](https://user-images.githubusercontent.com/1056684/47022586-73b36f80-d123-11e8-9b0a-10acb644d2e4.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by EdwardCoyle** [comment]
Just noting that the fix for this issue also fixes #1568

**Comment by janahintal** [comment]
QA Passed. Moving to done.
Verified in: https://4170-beta0-enterprise.demo.design.infor.com/patterns/stepprocess in all browsers and OS
