### ISSUE TITLE
DataGrid - dirtyRows doesn't include rows whose status is in error 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#1019]
The function dirtyRows doesn't account for row's whose status is in 'error'.  Only including row's whose status is 'dirty'.

**Expected behavior**
Expect that row's whose status is 'error' would also be included.  This is how it works in inforControlsCombined.js.

Current code snippet of dirtyRows function:
```
    /**
    * Return all of the currently dirty rows by row index.
    * @returns {array} An array of dirty rows.
    */
    dirtyRows: function dirtyRows() {
      var rows = [];
      var data = this.settings.dataset;

      for (var i = 0; i < data.length; i++) {
        if (data[i].rowStatus && data[i].rowStatus.icon === 'dirty') {
          rows.push(data[i]);
        }
      }
      return rows;
    }
```

Code snippet of getDirtyRows from inforControlsCombined.js:
```
    function getDirtyRows(commitEdits) {
      //Commit any pending edits...
      var commitEdits = commitEdits || false,
        allRows = getData(commitEdits).getItems(),
        dirty = [], i;

      for (i = 0; i < allRows.length; i++) {
        if (allRows[i].indicator === "dirty" || allRows[i].indicator === "error") {
          dirty.push(allRows[i]);
        }
      }
      return dirty;
    }
```

**Comment by deep7102** [comment]
Hi @claudenbach looks like this issue now should be fixed since added
https://github.com/infor-design/enterprise/pull/1173

Retest/confirm if all good at your end, this issue can be close.

**Comment by brianjuan** [comment]
https://4170-beta0-enterprise.demo.design.infor.com/components/datagrid/test-dirty-indication.html
Passed QA testing on all browsers, moving to Done.
