### ISSUE TITLE
Datagrid - need a mechanism to cancel a rowActivated event

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#1021]
Need a mechanism to cancel a rowActivated event.  Perhaps before a rowActivated event occurs, fire a before event where a return of false means the event should be ignored?  Or make the rowActivated event cancellable?

Landmark business case:
Have a parent list that drives a child list.  The user adds a record to the child list. The user then changes the active row on the parent list (which then changes the child list).  Before performing the rowActivated event, need to query the user as to whether the child list changes should be saved.

**Comment by tmcconechy** [comment]
The pattern we have been using is an onBeforeActived which you can return false to.
As any async support needed?

**Comment by janahintal** [comment]
Hi, datagrid is not loading when in IE11 Windows 10. Will re-open the ticket. 
Please see Image below. Thank you. 
<img width="1318" alt="Screen Shot 2019-03-21 at 5 53 12 PM" src="https://user-images.githubusercontent.com/45757016/54744575-4d2dbf00-4c02-11e9-8ca6-3b52e99e1d02.png">

**Comment by tmcconechy** [comment]
@deep7102 Can you take a look? I guess just change the example to Jquery promises instead.

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thank you!
Tested in : http://4170-rc0-enterprise.demo.design.infor.com/components/datagrid/test-before-row-activated.html in all Browser and Devices.

**Comment by janahintal** [comment]
QA Passed. Now working in all Browser, Devices and OS. Thank you!
Tested in: http://4170-rc0-enterprise.demo.design.infor.com/components/datagrid/test-before-row-activated.html
