### ISSUE TITLE
Hierarchy Text Cut Off

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1024]
**Describe the bug**
After recent changes on #999 the text in a mobile or narrow view is cut off.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/hierarchy/example-index.html
2. Resize the browser (chrome) as small as possible
3. All the items are now cut off.

**Expected behavior**
I think we need a solution that still shows as much text as before (or more at least). But also still works on the paging example http://master-enterprise.demo.design.infor.com/components/hierarchy/example-paging.html

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by ericangeles** [comment]
So is it okay to have a horizontal scroll bar in the mobile view?

**Comment by tmcconechy** [comment]
Its not ideal, as explained on the call, lets try to adjust the widths of the example-index and make a special case with the back button. We could even try to move the back button above the first node instead of on the side.

**Comment by brianjuan** [comment]
http://localhost:4000/components/hierarchy/example-index.html
http://localhost:4000/components/hierarchy/example-paging.html
Passed QA testing on all browsers, text are not cut off in responsive view. Also tested on mobile.
