### ISSUE TITLE
Popupmenu breaks when shared between multiple controls.

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise#1025]
**Describe the bug**

Use of a `popupmenu` component with several different html elements as context menus does not work as expected if the element hosting the `popupmenu` is removed from the DOM (which is often the case with angular components).

This issue is not just an angular issue, but can also be replicated in raw enterprise widgets.

**To Reproduce**
The following markup creates two inputs, each sharing the same popup menu. Deleting the first input prevents the context menu from appearing for the remaining input.

```html
    <button id="popdown-destroy" class="btn" type="button">
      <span>Destroy</span>
    </button>

    <div class="field" id="field1">
      <label for="input-menu">Label</label>
      <input type="text" value="Right Click Me" id="input-menu"/>
    </div>

    <div class="field" id="field2">
      <label for="input-menu2">Label2</label>
      <input type="text" value="Right Click Me" id="input-menu2"/>
    </div>

    <ul id="action-popupmenu" class="popupmenu">
      <li><a href="#">Cut</a></li>
      <li><a href="#">Copy</a></li>
      <li><a href="#">Paste</a></li>
    </ul>
```

```javascript
    // Share the popupmenu with the two context menus.
    const contextMenu = $('#input-menu');
    contextMenu.popupmenu({trigger:'rightClick', menu: "action-popupmenu", attachToBody: true})
    const contextMenuApi = contextMenu.data('popupmenu');

    const contextMenu2 = $('#input-menu2')
    contextMenu2.popupmenu({trigger:'rightClick', menu: "action-popupmenu", attachToBody: true});
    const contextMenuApi2 = contextMenu2.data('popupmenu');

    const popupMenu = $('#action-popupmenu');
    popupMenu.popupmenu({ attachToBody: true });
    const popupMenuApi = popupMenu.data('popupmenu');

    // This emulates an *ngIf on the first field, where it's presence is toggled.
    $('#popdown-destroy').click(() => {
      // turn off events
      contextMenu.off();

      // destroy the api
      contextMenuApi.destroy();

      // Remove the context.
      contextMenu.parent().remove();
    });
```

**Expected behavior**

I would expect the `popupmenu` to continue to work.

**Screenshots**

N/A

**Platform**

**Additional context**

**Comment by bthharper** [comment]
[example-popupmenu-issue.zip](https://github.com/infor-design/enterprise/files/2487756/example-popupmenu-issue.zip)

**Comment by EdwardCoyle** [comment]
I'm not sure exactly what we should do here... I'm not sure about the idea of sharing the same piece of markup between two or more component instances that can be independently destroyed.

@tmcconechy what do you think about duplicating the menu markup and assigning it a custom ID?

Another option could be to explore allowing Popupmenu definitions to data based.  Popupmenus already have the `toData()` method for generating a JSON structure that represents the menu, so it wouldn't be a stretch to allow that same structure to create one.

**Comment by janahintal** [comment]
QA Passed. 
Tested in : https://4150-beta0-enterprise.demo.design.infor.com/components/popupmenu/test-multiple-context-menu-destroy.html across all OS, browser and devices.
