### ISSUE TITLE
Add some content for a few docs pages.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1034]
**Is your feature request related to a problem? Please describe.**

Take some docs feedback and add a few improvements

- [x] Show locale example , formatting the date
- [x] Breadcrumb - show where to place this on the page (examples from patterns)
- [x] Modal - explain how to cancel closing the modal
- [x] https://design.infor.com/code/ids-enterprise/latest/utils has 404 should we remove?
- [x] input - Add info on masking i.e. explicit link to masking
- [x] popupmenu - better example how to use it, for example how do you attach a handler to a selection.
- [x] form - ensure links to samples work

**Comment by CindyMercadoReyes** [comment]
Tested multiple links provided from @tmcconechy and opened 3 GitHub ticket. Moving this ticket to the Done bucket.
