### ISSUE TITLE
removeSelected is not deleting all selected rows

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#1036]
**Describe the bug**
When using the removeSelected when all the rows on the grid are selected, rows are left in the array.

**To Reproduce**
1. Grid has 11 rows. (it does it with more too but it seems to break exactly after 10)
2. click checkbox select all
3. Click on Delete (this will call removeSelected method on the grid)

**Expected behavior**
All selected rows on the Grid should be deleted

**Screenshots*
![image](https://user-images.githubusercontent.com/17933529/47168160-2c1d1700-d2ce-11e8-8396-161885a45686.png)
*

**Platform**
Windows 7, Chrome

**Additional context**
Grid setup
html
 <div soho-datagrid (rowReordered)="onRowReordered($event)" (selected)="onSelected()">

Component
this.sohoDataGridComponent.gridOptions = {
      columns: this.columns,
      dataset: this.dataset,
      selectable: 'multiple',
      idProperty: 'id',
      editable: true,
      rowReorder: true,
      clickToSelect: false
    };

Columns:
 initializeColumns() {
    if (this.permission === DeskPermissionTypes.FULL_ACCESS) {
      this.columns.push({
        id: 'rowReorder',
        sortable: false,
        resizable: false,
        formatter: Soho.Formatters.RowReorder,
        align: 'center'
      });

      this.columns.push({
        id: 'selectionCheckbox',
        sortable: false,
        resizable: false,
        formatter: Soho.Formatters.SelectionCheckbox,
        align: 'center'
      });
    }

    this.columns.push({
      id: 'position',
      sortable: false,
      name: this.translations.position,
      field: 'position',
      formatter: Soho.Formatters.Readonly
    });

    const localeCodeCol: SohoDataGridColumn = {
      id: 'code',
      sortable: false,
      name: this.translations.localeCode,
      field: 'code'
    };

  }

Data
{"version":1,
"positions":[{"code":"en_US"},
{"code":"cs_CZ"},
{"code":"es_MX"},
{"code":"ko_KR"},
{"code":"fr_CA"},
{"code":"en_GB"},
{"code":"bo-CN"},
{"code":"cu-RU"},
{"code":"da-DK"},
{"code":"de-AT"},
{"code":"dz-BT"}
]}

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-reorder-multiselect
http://master-enterprise.demo.design.infor.com/components/datagrid/test-reorder-multiselect
Passed QA testing on all browsers, moving to Done.
