### ISSUE TITLE
TrackDirty: indictor not on the checkboxes component when scrolling

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1052]
**Describe the bug**
Checkboxes component disappears on responsive view

**To Reproduce**
1. Go to url: http://4120-beta0-enterprise.demo.design.infor.com/
2. Scroll down to Checkboxes and click on the dirty tracker checkbox
3. Make the page responsive
4. All the checkboxes are no longer appearing. However you can still see the dirty tracker ticker on the UI

**Expected behavior**
The checkboxes component should appear when the page is on responsive view

**Screenshots**
![checkboxes responsive view 2](https://user-images.githubusercontent.com/39101346/47316553-64e22680-d615-11e8-84f7-9bc74b48b17d.png)

**Platform**
 - MAC Chrome

**Additional context**
None

**Comment by tmcconechy** [comment]
They are in the page, its just scrolling. I think the solution here is to make the dirty tracker not absolutely positioned in the page..

**Comment by EdwardCoyle** [comment]
This isn't quite as simple as it looks.  I'm not totally familiar with the dirty tracking code, but the dirty trackers on these checkboxes aren't wrapped inside of a common element along with the checkboxes, making their placement a bit tricky for situations where the page repaints columns/containers/etc.

Specifically for Checkboxes/Radios, we may be looking at attaching the absolute positioning routine in the [TrackDirty component](https://github.com/infor-design/enterprise/blob/master/src/components/trackdirty/trackdirty.js#L70) to the (global resize handler)[https://github.com/infor-design/enterprise/blob/master/src/utils/environment.js#L248]

@tmcconechy @deep7102, what do you guys think?

**Comment by tmcconechy** [comment]
Can we take another approach by perhaps adding a "is-dirty" class to either the label or input that adds a pseudo element that styles the tick instead of a seperate element?

**Comment by EdwardCoyle** [comment]
Not sure that we can... the pseudo-elements are reserved for the checkbox in the case of the label wrapping the input

**Comment by tmcconechy** [comment]
Had another look at this issue and i cant seem to reproduce it on http://4180-enterprise.demo.design.infor.com/ or http://4190-rc1-enterprise.demo.design.infor.com/ 

So placing as fixed in 4.20 for further re-verification

**Comment by brianjuan** [comment]
Yeah, it seems like fixed on the latest version, tested in http://localhost:4000/ on all browsers, will retest once beta is deployed.
