### ISSUE TITLE
Sink Page: Slider tooltip appears in modal component on responsive view

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1053]
**Describe the bug**
Slider tooltip appears in modal component on responsive view

**To Reproduce**
1. Go to URL: http://4120-beta0-enterprise.demo.design.infor.com/
2. On responsive view scroll down to the slider and move the slider
3. Click on "Show Modal"  button
4. The numeric tooltip still appears in the modal. When you change the UI back to non responsive the number moves to a different location on the modal. Please see screen shot attached. 

**Expected behavior**
The slider tooltip should not appear in the modal componenet

**Screenshots**
![slider error 2](https://user-images.githubusercontent.com/39101346/47317232-0c138d80-d617-11e8-8770-c221fac845e3.png)
![slider error](https://user-images.githubusercontent.com/39101346/47317233-0cac2400-d617-11e8-95e8-7ef12221eecb.png)

**Platform**
- MAC Chrome

**Additional context**
None

**Comment by tmcconechy** [comment]
One solution is to hide id="tooltip" in the modal code when opening.

**Comment by ericangeles** [comment]
No worries

**Comment by tmcconechy** [comment]
Added to the sprint board so this can be tests. This was pulled out of up for grabs while we switch sprints.

**Comment by janahintal** [comment]
QA Passed. Moving to Done
Tested in https://4140-beta0-enterprise.demo.design.infor.com/
