### ISSUE TITLE
Style of read-only Text Input field has changed in Light Theme

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#1055]
**Describe the bug**
Between version 4.8 and 4.9, the text colour used within read-only text fields has changed, but only in the Light Theme. To compare...

**To Reproduce**
https://design.infor.com/code/ids-enterprise/4.8.0/demo/input/example-index?font=source-sans
https://design.infor.com/code/ids-enterprise/4.9.0/demo/input/example-index?font=source-sans

I can see nothing in the release notes that implies this is deliberate and the new style essentially makes the read-only text look disabled, and definitely much more difficult to read. We use this style extensively in our Infor ERP applications, and the new style has effectively made the fields unusable in the default theme, and is therefore preventing us upgrading to the latest release of SoHo Xi to take other fixes we need.

**Expected behavior**
Can we have a fix, or, if this style change is deliberate, then can we have a alternate read-only class to go back to the original styling?

**Screenshots**
n/a

**Platform**
Reproduced using MS Windows 8.1, with Chrome, FireFox and IE11 (latest versions of all browsers).

**Comment by tmcconechy** [comment]
Yes, your right it used to be https://design.infor.com/code/ids-enterprise/4.7.0/demo/input/example-index?font=source-sans i think due to token changes? @jmacaluso711 @clepore ?

**Comment by clepore** [comment]
@tmcconechy Yeah it was an unexpected changed. I did a manual fix and the tokens will resonate this in their next release. 

@sanx72 This will go out when we release v4.12.0 in a week or so 👍

**Comment by brianjuan** [comment]
http://4120-rc2-enterprise.demo.design.infor.com/components/input/example-index
Passed QA testing on all browsers, read-only is now back to its original styling.
