### ISSUE TITLE
Tabs: On mobile, alignment issue on X button of dismissible tab with dropdown  

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1056]
**Describe the bug**
Tabs: On mobile, alignment issue on X button of dismissible tab with dropdown .

**To Reproduce**
1. Go to http://localhost:4000/components/tabs/test-dismissibles-with-dropdowns.html on Android or iOS devices
2. Click the arrow down on the right-most part of tab
3. Notice that the X button is out of position in "Plastic (Dismissible & Dropdown)" tab

**Expected behavior**
X button in the dismissible tab with dropdown should be in the right position.

**Screenshots**
<img width="500" alt="screen shot 2018-10-23 at 6 53 24 pm" src="https://user-images.githubusercontent.com/39508864/47355974-671bb200-d6f5-11e8-8a90-81f2b131c472.png">

**Platform**
 - Android and iOS devices

**Additional context**
No additional context.

**Comment by tjamesallen15** [comment]
Hi @tmcconechy,

Should it be like this?
![screen shot 2018-11-20 at 1 54 31 pm](https://user-images.githubusercontent.com/34049950/48754246-f3f16580-eccb-11e8-9777-2a1e44986d59.png)


Thanks!

**Comment by tmcconechy** [comment]
Yes, that looks good, maybe pad the x a bit more on each side.

**Comment by tmcconechy** [comment]
This can now go in master when its ready..

**Comment by brianjuan** [comment]
Passed QA testing on all mobile browsers.
