### ISSUE TITLE
Contextual Toolbar: buttons are sometimes hidden from view

### ISSUE THREAD

**Issue by mmmild** [infor-design/enterprise#1058]
**Describe the bug**
When resizing a Contextual Toolbar (CT) with multiple buttons, the buttons sometimes disappear due to width containment (see recording).

**To Reproduce**
1. Open sample "datagrid-mixed-selection" and add some more buttons to the buttonset of the CT
2. Select an item in the datagrid and resize the width of the browser window 
3. Problem: rightmost items get pushed below the visible area

**Expected behavior**
All buttons are visible regardless of width. 

**Screenshots**
![ct-buttons](https://user-images.githubusercontent.com/43241773/47360524-ff06a500-d6cf-11e8-9861-a0d0c872e656.gif)
In the recording, I modified the "datagrid-mixed-selection" sample in ng-enterprise.
- IDS Version: IDS Components (+ NG) 4.12.0-dev 

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 70.0.3538.67 (Official Build) (64-bit)]

**Additional context**
Moved to the NG project: infor-design/enterprise-ng#283

**Comment by tmcconechy** [comment]
Perhaps similar to https://github.com/infor-design/enterprise-ng/issues/225

**Comment by mmmild** [comment]
Hmm, no searchfield here and this is only a visual issue

**Comment by EdwardCoyle** [comment]
Depends on #1120, maybe @tmcconechy ?

**Comment by deep7102** [comment]
Moved to the NG project: infor-design/enterprise-ng#283
