### ISSUE TITLE
Upgrade to use ids-identity@2.0.0

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1062]
**Is your feature request related to a problem? Please describe.**
The tokens have been refactored and changed to a `v2.0.0`.

**Describe the solution you'd like**
- Update to use the new token naming scheme.
- Also the colors are now freely available from `ids-identity` so consider switching off of the Enterprise color palette vars.

**Describe alternatives you've considered**
n/a

**Additional context**
Some of the original tokens were removed, so this is a reminder to restore those to their previous Enterprise config vars.

**Comment by brianjuan** [comment]
@clepore I noticed that the current color scheme for the Dark theme differs from the previous versions. Is this part of the enhancement?
E.g, bar chart
http://localhost:4000/components/list
<img width="865" alt="screen shot 2018-11-14 at 6 32 35 pm" src="https://user-images.githubusercontent.com/39508864/48477335-4948f500-e83c-11e8-979f-af63d965bc29.png">

previous versions:
http://4120-enterprise.demo.design.infor.com/components/bar/example-index.html
<img width="864" alt="screen shot 2018-11-14 at 6 33 21 pm" src="https://user-images.githubusercontent.com/39508864/48477356-59f96b00-e83c-11e8-887e-aebf2b53c0a5.png">

**Comment by tmcconechy** [comment]
Im not sure if you mean the bar or the checkmarks in the list?

- checked and the bar is both rgb(29, 95, 138) (#1d5f8a), so assuming you dont mean that.
- the checkmark change is a separate issue, it should be as previous, so its more viewable. I think this could be from this change. So good catch, we should address this as a failed issue.

**Comment by clepore** [comment]
This is a bug in the design-system repo, but we'll fix it for 4.13, see https://github.com/infor-design/design-system/issues/235

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the "Done" bucket.
