### ISSUE TITLE
Scatter: Example Series 02 Color Code Not Appearing In the Tooltip

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1066]
**Describe the bug**
 Scatter Chart Example Series 02 Color Code Not Appearing In the Tooltip

**To Reproduce**
1. Go to URL: http://4120-beta0-enterprise.demo.design.infor.com/#
2. Scroll down to Scatter Chart Example
4. Click inside the chart to view the tooltip 
5. The light green Series 02 is not appearing in the tooltip. Only the blue series 01 is appearing in the tooltip.

**Expected behavior**
Both Series 01 and Series 02 should appear in the tooltip

**Screenshots**
![scatter plot chart series 02](https://user-images.githubusercontent.com/39101346/47374709-982bc080-d6bc-11e8-8eaf-a721a5ddef89.png)

**Platform**
- All Browsers

**Additional context**
None

**Comment by tmcconechy** [comment]
It should at lease have the right color, preferably also change the shape.
Check related components: area, line
