### ISSUE TITLE
Field Filter Component:  Lookup doesn't display 3 button Eclipse button on responsive view

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1068]
**Describe the bug**
Field Filter Component:  Lookup doesn't display 3 button Eclipse button on responsive view

**To Reproduce**
1. Go to url: http://4120-beta0-enterprise.demo.design.infor.com/components/field-filter/example-index.html
2. Make the page responsive
3. Click on the Lookup icon
4. The product lookup list window pops up. However, the 3 button Eclipse button is not being displayed. 
5. Please see screen shot attached. 

**Expected behavior**
The 3 button Eclipse button should be visible on responsive view

**Screenshots**
![lookup 3 button eclipse not appearing](https://user-images.githubusercontent.com/39101346/47376487-b5fb2480-d6c0-11e8-9790-88fa02be0b5d.png)

**Platform**
- MAC chrome
**Additional context**
None

**Comment by tmcconechy** [comment]
Note that it only doesnt work if the page starts out responsive. If you resize while the dialog is open, it does not occur. This means we can check to rerun the sizing logic on load.

**Comment by janahintal** [comment]
QA Passed. 
Tested in: https://4150-beta0-enterprise.demo.design.infor.com/components/field-filter/example-index.html across all browsers
