### ISSUE TITLE
Form Component: Dropdown list box has alignment issues on mobile

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1069]
**Describe the bug**

**To Reproduce**
1. On iOS iPhone X
2. Go to url: http://4120-beta0-enterprise.demo.design.infor.com/components/form/example-inputs.html
3. Scroll down to States drop down list box and open the list box. the list box opens on a different area of the form and the user is able to scrolls up and down the page with the list box still being opened
4. Please see screen shot attached. 

**Expected behavior**
The list box should only up in one location

**Screenshots**
![bs_realios_mobile_iphone xs-12 0](https://user-images.githubusercontent.com/39101346/47380992-c2857a00-d6cc-11e8-97f6-1ad3b24913f4.jpg)
**Platform**
 - Device: iOS iPhone X 

**Additional context**
None

**Comment by ericangeles** [comment]
Pretty sure that the dropdown list shouldn't close on mobile if scrolling is existing right, @tmcconechy? Tapping outside of the list would be the only way to close it.

Hi @CindyMercadoReyes , could you give me more details about the bug? Thank you.

**Comment by tmcconechy** [comment]
There is two places you can scroll in this example.

1) When the list is open, scroll within the list (this doesnt appear to work for me)
2) Scrolling on the form, for example when the list is open press above on the form the form , hold and scroll. (touch scroll) This should close the list and is not working.

Hope that helps!
