### ISSUE TITLE
Menu Button Component: Blue check maker appears in the dropdown list and the full list is not displayed

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1071]
**Describe the bug**
Menu Button Component: Blue check maker appears in the dropdown list and the full list is not displayed 

**To Reproduce**
1. On IOS iPhone X
2. Go to url: http://4120-beta0-enterprise.demo.design.infor.com/components/menubutton/test-focus-click.html
2. Click on the "Add Item" dropdown list and turn the phone to horizontal view
3. a blue check marker appears on top of the text and the full list is not displayed. 
4. Please see screen shot attached. 

**Expected behavior**
- A blue check marker should not be visible in the dropdown list
- The full list under "Enable Autocomplete" should appear

**Screenshots**
![bs_realios_mobile_iphone x-11 0 2](https://user-images.githubusercontent.com/39101346/47383336-805f3700-d6d2-11e8-8b8b-5e1c437c1d7a.jpg)

**Platform**
 - Device: iOS  iPhone X

**Additional context**
None

**Comment by tmcconechy** [comment]
This is just an example issue, it can be fixed by adding the class ` is-selectable` to the ul in the example html.
