### ISSUE TITLE
Hierarchy actions menus sub menu is sometimes clipped

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#1073]
**Describe the bug**
Sub menus of an action menu are clipped when the action button is on a card nested down a couple levels.

**To Reproduce**
1. Apply code from PR
2. Go to http://localhost:4000/components/hierarchy/example-context-menu-with-details.html
3. Click on "Katie Olland" card action menu button.
4. Hover over options. Notice the sub menu is not displayed and forces a horizontal overflow.

**Expected behavior**
The sub menu should display. There should not be a horizontal overflow.

**Screenshots**
![sub-menu-clipped](https://user-images.githubusercontent.com/1056684/47385077-ada9e600-d6ce-11e8-82e5-59c713c88ff6.png)

**Platform**
 - Windows 10
 - Chrome

**Comment by tmcconechy** [comment]
Maybe related to https://github.com/infor-design/enterprise/pull/1048 or at least that portion of the code. Feel free to assign to yourself if you plan on looking at it
