### ISSUE TITLE
textarea data object is destroyed in 'updated' trigger

### ISSUE THREAD

**Issue by tobywicksinfor** [infor-design/enterprise#1077]
**Describe the bug**
After `$("textarea").trigger('updated'')` is called `$("textarea").data('textarea')` returns `undefined`.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/textarea/example-index?font=source-sans&nofrills=true
2. `$("#description-max").data('textarea')` correctly returns 
`Textarea {settings: {…}, element: jQuery.fn.init(1), isChrome: true, isSafari: false, counter: jQuery.fn.init(1), …}`
3. `$("#description-max").trigger('updated')`
4. `$("#description-max").data('textarea')` incorrectly returns `undefined`

**Expected behavior**
`$("#description-max").data('textarea')` does not return `undefined` after `.trigger('updated')` has been called on the control.

**Platform**
 - Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
Possibly relevant code: https://github.com/infor-design/enterprise/blob/568b7b1203597e211aaff93c73b625d8d317503d/src/components/textarea/textarea.js#L278

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done folder.
