### ISSUE TITLE
Lookup Page Indicators Hidden when Grid Width gets smaller

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#1079]
**Describe the bug**
Hi, noticed an inconsistent behavior for the lookup control. When the grid size is smaller, some of the grid page indicators are being hidden. The indicators are hidden inconsistently. Please see steps/screenshots below for further explanation.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/lookup/example-paging.html'
2. Don't open the lookup yet. In the console of the browser, enter this:

`$('#paging').data('lookup').settings.options.columns.pop(5);
$('#paging').data('lookup').settings.options.columns.pop(3);
$('#paging').data('lookup').settings.options.columns.pop(2);`

This removes some of the columns of the lookup.

3. Now open the lookup.
4. The "Records per Page" and "Page Number" indicators are hidden.
![image](https://user-images.githubusercontent.com/41028784/47408289-53258e00-d791-11e8-8fb0-4c9505b423ae.png)

5. Click on the Next Page. The "Records per Page" is shown. The "Page Number" indicators are still hidden.
![image](https://user-images.githubusercontent.com/41028784/47408318-70f2f300-d791-11e8-8f60-e570b8d82cb5.png)

6. Now click on the previous page. The "Page Number" indicators are shown but the "Records per Page" are hidden.
![image](https://user-images.githubusercontent.com/41028784/47408368-b1eb0780-d791-11e8-8b53-69a0e4c8febb.png)

Not sure if this expected, but the hidden indicators varies from page to page. Hope we can clarify if this is an issue or not. Thanks.

**Platform**
- Google Chrome

**Comment by tmcconechy** [comment]
This is actually by design. The columns drive the width of the modal and by default they size to the content. So this is the size of the form.

You could influence it by making the widths of the columns bigger so that there is enough room for the other components on the dialog.

We may or may not want to change anything here.

**Comment by marknolaninfor** [comment]
Hi @tmcconechy,

Is there a way that the modal has a minimum width applied, when it is displayed on larger devices, tablets, and desktops. I have created a pull request with an example.

**Comment by tmcconechy** [comment]
Hi @marknolaninfor , I think we should probably do it by adding a width setting to the lookup.js which gets applied. That way its not a fixed value of 400px....

**Comment by marknolaninfor** [comment]
Hi @tmcconechy, There is now a minWidth setting applied and the example now has two versions of the small lookup to see the difference when it is applied.
