### ISSUE TITLE
Error on lookup if dataset is an empty array

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1080]
**Describe the bug**
This issue happens in angular because the array for dataset is set to null. So its breaking those using angular lookups. A recent regression.

**To Reproduce**
1. Change lookup/example-paging-serverside.html to add options.dataset = []
2. Click to open lookup
3. Select a row and click apply
4. See error in console

Second problem is that the way that angular is updating the dataset is incorrect. To make this possible we should add a updateDataset method to lookup that will:

a) set the settings.options.dataset to whats passed in
b) if the modal is open and the grid.updateDataset is available call that with the update
c) make a test/sample

**Expected behavior**
No error

**Comment by brianjuan** [comment]
http://4120-rc2-enterprise.demo.design.infor.com/components/lookup/test-update-dataset.html
http://4120-rc2-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html
Passed QA testing on all browsers.

**Comment by sowmyabaisani** [comment]
I am getting error for soho-lookup , source function is calling two times .
![image](https://github.com/infor-design/enterprise/assets/130368580/2f083e6f-8818-46f1-bfcf-fecdd0693905)
<input
              soho-lookup
              soho-busyindicator
              data-init="false"
              [activated]="isBusy"
              [(ngModel)]="custGL"
              [columns]="glcols"
              [options]="{
               paging: true,
               pagesize: 10,
               pagesizes: [5, 10, 15, 20, 25],
             }"
              [source]="source.bind(context)"
              [toolbar]="{
                results: true,
                dateFilter: false,
                keywordFilter: true,
                advancedFilter: true,
                actions: true,
                views: true,
                rowHeight: false,
                collapsibleFilter: false,
                fullWidth: true
              }"
              field="SMCD"
              name="SMCD"
              aria-required="true"
              data-validate="required"
            />
this is my HTML code.
GroupLevelGridColumns: SohoDataGridColumn[] = [
    {
      field: 'SMCD',
      id: 'GRP_ID',
      name: 'Group level',
      filterType: 'text',
      width: 'auto',
    },

    {
      field: 'TX40',
      id: 'Description',
      name: 'Description',
      width: 'auto',
    },
    {
      field: 'SDEP',
      id: 'Description',
      name: 'Description',
      width: 'auto',
    },
  ];
  setLookup() {
    this.glcols = [];

    this.GroupLevelGridColumns.forEach((column) => {
      this.glcols.push(column);
    });
  }
  
  source(
    req: SohoDataGridSourceRequest,
    response: SohoDataGridResponseFunction
  ) {
    const filter =
      req.filterExpr && req.filterExpr[0] && req.filterExpr[0].value;
    this.tabnotesService
      .LstSalesPersontq(filter, req.activePage, req.pagesize)
      .then((result) => {
        req.total = result.total;
        response(result.data, req);
      });
  }
this is .ts code related to HTML 
Please help me out to solve this.

Thank you

**Comment by tmcconechy** [comment]
@sowmyabaisani not sure how to run this? Would you be able to try to put it in stackblitz? https://stackblitz.com/edit/ids-quick-start-1641

Note in general the source function may be called in different scenarios (paging vs filtering vs saving settings / initial load ect)
