### ISSUE TITLE
IE11 no tooltip on hover of rowstatus of new row

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#1081]
**Describe the bug**
Adding rowstatus and adding a new row with rowstatus and hovering on tooltip does not reveal tooltip.

**To Reproduce**
- Run app
- Go to IE11 on Windows and browse up app
- Click Add Row Status
- Click Add Row under "..."
- Notice hover of rowstatus does not reveal tooltip text

**Expected behavior**
Expect the tooltip to reveal on hover.

**Platform**
Windows 8.1, IE11

**Additional context**
https://github.com/infor-design/enterprise/issues/227#issuecomment-432145902

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done bucket.
