### ISSUE TITLE
Datepicker - Clicking today should insert current time or time to midnight.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1087]
**Describe the bug**
Clicking today should insert current time or time to midnight.

**To Reproduce**
Steps:
1. Open the date picker on the "Date-Time Picker in Locale (Time to Current)"
2. Select 1:00 AM on the time picker
3. Click "Today" button
4. See Issue happen, values on the time picker (1:00 AM) will be applied, not the current time.

**Expected behavior**
When clicking today we should insert the current time , ignoring whats selected in the fields for the action of the today button (respecting the useCurrentTime setting)

**Comment by hohnzy** [comment]
This is still not working. When you dont use useCurrentTime, the time remains the same but PM is switched to AM after clicking 'Today' button. I would expect setting the time to midnight or unchanged.

https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat?font=source-sans

**Comment by tmcconechy** [comment]
Im not 100% clear on what you mean - it seems to work as expected (and all previous versions).

1. https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat?font=source-sans
2. open the picker on "Date-Time Picker in Locale (Time to Midnight)"
3. press today
4. time is inserted as 1/22/2019 12:00 AM (Midnight)

**Comment by hohnzy** [comment]
1. https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat?font=source-sans
2. open the picker on "Date-Time Picker in Locale (Time to Midnight)"
3. select any time "PM" and any date
4. open again and press today
5. time is inserted as it was but PM is switched to AM
