### ISSUE TITLE
Provide a configuration option to hide drop-down arrow icon on a menu-button

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise#1088]
**Describe the bug**

Using a `menu-button` for the "User" control on the masthead but don't want to see the drop-down arrow next to the User icon

Setting the `showArrow` to false did not have the desired affect.

**To Reproduce**

Add a menu button with the showArrow option set to false, and then display the page.

**Expected behavior**

The icon should be displayed without the arrow.

**Screenshots**

**Platform**
**Additional context**

I discussed this with @tmcconechy , and agreed that showArrow is the correct way to achieve this, however this does not currently work..

A corresponding change has been made in the enterprise-ng control to support showArrow.

**Comment by tmcconechy** [comment]
I later found out showArrow is for the arrow on the popup dialog. We need a new option for not showing / adding the arrow icon to the button

**Comment by CindyMercadoReyes** [comment]
This failed QA testing. On high contrast them you can barely see the text or the buttons. Please see screen shot attached. 
![menu button high contrast](https://user-images.githubusercontent.com/39101346/48788711-61e06180-ecb9-11e8-978a-6103d254ff71.png)

**Comment by tmcconechy** [comment]
@clepore @jmacaluso711 maybe something is wrong with the tokens here? http://master-enterprise.demo.design.infor.com/components/menubutton/example-index.html

**Comment by tmcconechy** [comment]
This also effects all the icons buttons http://localhost:4000/components/icons/example-index.html if you change to high contrast mode

**Comment by clepore** [comment]
Hmm, okay. I'll investigate.

**Comment by tmcconechy** [comment]
This is mainly a seperate issue so i created https://github.com/infor-design/enterprise/issues/1249

**Comment by brianjuan** [comment]
https://4130-beta0-enterprise.demo.design.infor.com/components/menubutton/test-no-arrow-icon.html
Passed QA testing on all browsers, example menu button doesn't have arrow icon. Moving to Done.
