### ISSUE TITLE
Detect an option in `SohoConfig` for preventing automatic start of the RenderLoop

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1095]
Related to infor-design/enterprise-ng#214

**Is your feature request related to a problem? Please describe.**
A recent Angular issue requires us to allow more fine-grain control of the RenderLoop's lifecycle, so that it can be run outside of Zone.js's control.

**Describe the solution you'd like**
- Add a setting to the optional `SohoConfig` object: `SohoConfig.renderLoop.noAutoStart` 
- allow the new setting to disable `renderLoop.start()` [see here](https://github.com/infor-design/enterprise/blob/master/src/utils/renderloop.js#L407) if it's present.

**Describe alternatives you've considered**
Not sure how else to disable.  Since [IDS is an IIFE bundle](https://github.com/infor-design/enterprise-ng/issues/214#issuecomment-431953822), as long as the line is present in the bundle it will automatically run, and will be a performance bottleneck for Angular.  Allowing Angular to call it directly is the only way to solve.

**Additional context**

**Comment by clepore** [comment]
🔗 Related to https://github.com/infor-design/enterprise-ng/issues/214
