### ISSUE TITLE
Menu Button Component: Blue Check Marker is misaligned on all dropdown list box

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1096]
**Describe the bug**

**To Reproduce**
1. Go to URL: http://4120-beta0-enterprise.demo.design.infor.com/components/menubutton/test-on-toolbar.html
2. Click on any drop down list box
3. Everywhere that "Enable Autocomplete" appears the blue check mark ticker overlaps onto the letter "E"
4. Please see screen shot attached.

**Expected behavior**
The blue check mark ticker should not appear in the drop down list box

**Screenshots**
<img width="893" alt="menubutton error" src="https://user-images.githubusercontent.com/39101346/47515312-85e28b80-d850-11e8-879f-b98c4911f0e2.png">

**Platform**
 - MAC Chrome 

**Additional context**
None

**Comment by tmcconechy** [comment]
This is just an example issue, it can be fixed by adding the class is-selectable to the ul in the example html.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done folder.
