### ISSUE TITLE
Searchfield Component: The letter "H" is cut off

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1101]
**Describe the bug**
Searchfield Component: The letter "H" is cut off

**To Reproduce**
1. Go to URL: http://4120-beta0-enterprise.demo.design.infor.com/components/searchfield/example-categories-and-go-button.html#
2. Please see screens shot attached. 

**Expected behavior**
All the letters should be visible

**Screenshots**
<img width="1239" alt="searchfield letter gets cut off" src="https://user-images.githubusercontent.com/39101346/47527968-f1892080-d871-11e8-8736-47c2b4af70ea.png">

**Platform**
 - Mac Chrome,
**Additional context**
None

**Comment by tmcconechy** [comment]
is that the right screen shot? I dont see any H

**Comment by tmcconechy** [comment]
Probably just a small issue with the example

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the "Done" bucket.
