### ISSUE TITLE
Searchfield Category Component: Alignment issues and keyboard overlaps the page on landscape view

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1102]
**Describe the bug**
Searchfield Category Component: Alignment issues and keyboard overlaps the page on landscape view

**To Reproduce**
1. Go to URL: http://4120-beta0-enterprise.demo.design.infor.com/components/searchfield/example-categories-full.html#
2. On portrait view the field box is misaligned  
3. On landscape view the user is unable to click on the drop down list box because the keyboard overlaps onto the UI of the page
4. Please see screens shot attached. 

Also the same issue on http://4120-beta0-enterprise.demo.design.infor.com/components/autocomplete/test-longpage-modal.html as it uses autocomplete.

**Expected behavior**
- The list box and the searchfield box should be aligned 
- The keyboard should not overlap the search drop down list box or the searc field box.

**Screenshots**
![bs_realios_mobile_iphone x-11 0 3](https://user-images.githubusercontent.com/39101346/47524301-4162ea00-d868-11e8-84f9-7a1b0a602e61.jpg)

**Platform**
 - iOS iPhone X

**Additional context**
None

**Comment by tmcconechy** [comment]
For this issue, just test and fix the alignment of the boxes. No need to change the behavior.

**Comment by tjamesallen15** [comment]
Hi @tmcconechy  and @clepore ,

May I ask how can I run localhost on browserstack for IPhone X? The emulator itself can't access or find the localhost.

Thanks!

**Comment by tmcconechy** [comment]
Try to install the browser stack chrome plugin and then launch the VM from the icon on the toolbar.
https://chrome.google.com/webstore/detail/browserstack/nkihdmlheodkdfojglpcjjmioefjahjb?hl=en
This way local host works (thumbs)

**Comment by tjamesallen15** [comment]
Thank you @ericangeles  and @tmcconechy

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
