### ISSUE TITLE
Searchfield Example Context Search Style Component: Background color different from PC and Mobile

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1104]
**Describe the bug**
Searchfield Example Context Search Style Component: Background color different from PC and Mobile

**To Reproduce**
1. Go to url: http://4120-beta0-enterprise.demo.design.infor.com/components/searchfield/example-context-search-style.html
2. On Mac Chrome Click into the "Context Search" box and type in "Hello World" 
3. On iOS iPhone X Click into the "Context Search" box and type in "Hello World" 
4. The background color theme is different for both. Please see screen shots attached. 

**Expected behavior**
The background color theme should be consistent

**Screenshots**
<img width="916" alt="searchfield theming" src="https://user-images.githubusercontent.com/39101346/47525284-d961d300-d86a-11e8-823a-9ff71dc68a1f.png">
![bs_realios_mobile_iphone x-11 0 4](https://user-images.githubusercontent.com/39101346/47525291-dd8df080-d86a-11e8-9aba-d76b8aee1479.jpg)

**Platform**
 - iOS iPhone X
- Mac Chrome

**Additional context**
None

**Comment by brianjuan** [comment]
http://localhost:4000/components/searchfield/example-context-search-style.html
http://master-enterprise.demo.design.infor.com/components/searchfield/example-context-search-style.html
Passed QA testing, background colors are now the same for Mac and iOS.

**Comment by tmcconechy** [comment]
Yep should have been closed
