### ISSUE TITLE
Searchfield Header Compact Component: Text not appearing in the searchfield box and alignment issues

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1106]
**Describe the bug**
Search field Header Compact Component: Text not appearing in the search field box and alignment issues
**To Reproduce**
1. Go to url: http://4120-beta0-enterprise.demo.design.infor.com/components/searchfield/example-header-compact.html
2. Click on on the drop down and select " Product References"
3. Type " Hello World" in the searcfied box
4. The list box and searchfield box are not aligned
5. The text "Hello World" text is not visible
6. Please see screen shot attached. 

**Expected behavior**
The list box and searchfield box should both be aligned
The text " Hello World" should be visible

**Screenshots**
![bs_realios_mobile_iphone x-11 0 5](https://user-images.githubusercontent.com/39101346/47527298-3d3aca80-d870-11e8-945a-9010595c8084.jpg)

**Platform**
  - iOS iPhone X
**Additional context**
None

**Comment by brianjuan** [comment]
http://localhost:4000/components/searchfield/example-header-compact.html
http://master-enterprise.demo.design.infor.com/components/searchfield/example-header-compact.html
Passed QA testing on mobile, moving to Done.
