### ISSUE TITLE
Searchfield Categories Component: Unable to deselect items that are already selected

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1107]
**Describe the bug**
Searchfield Categories Component: Unable to deselect items that are already selected
**To Reproduce**
1. Go to url: http://4120-beta0-enterprise.demo.design.infor.com/components/searchfield/test-categories.html#
2. Click on list box for Context Search + Full-Word Category
3. Select "People, Baby"
4. Now deselect "People, Baby" 
5. The user is unable to deselect "People or Baby"
6. Please see screen shot attached. 

**Expected behavior**
The user should be able to select and deselect the check mark boxes

**Screenshots**
<img width="1304" alt="search field test categories_2" src="https://user-images.githubusercontent.com/39101346/47528248-ae7b7d00-d872-11e8-9547-1af6dfbb8649.png">

**Platform**
 - Mac Chrome,

**Additional context**
None

**Comment by tmcconechy** [comment]
Seems to work on http://4120-beta0-enterprise.demo.design.infor.com/components/searchfield/example-categories-full.html so this is just a problem on the example. Should update the example page

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done bucket.

**Comment by tmcconechy** [comment]
This issue should have been closed
