### ISSUE TITLE
Signin Component: Forgot Password is redirecting to the components page instead of the "Forgot Password" page

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1108]
**Describe the bug**
Signin Component: Forgot Password is redirecting to the components page instead of the "Forgot Password" page

**To Reproduce**
1. Go to url: http://4120-beta0-enterprise.demo.design.infor.com/components/signin/test-dropdown.html
2. Click on "forgot Password" 
3. It brings the user to the Sign in components page

**Expected behavior**
Should bring the user to the "Forgot Password" UI page

**Screenshots**
None

**Platform**
All Browsers  

**Additional context**
None

**Comment by brianjuan** [comment]
http://4120-rc2-enterprise.demo.design.infor.com/components/signin/test-dropdown.html
Passed QA testing on all browsers, Forgot Password is now redirecting to the right page.
