### ISSUE TITLE
Editor throws exception: Cannot read property 'parentElement' of undefined when text is changed

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#1114]
**Describe the bug**
When the editor is configured to use the track dirty functionality and the editor.updated() method has been executed, changes to the editor text will throw an exception: Uncaught TypeError: Cannot read property 'parentElement'.

**To Reproduce**
1. Change /components/editor/example-dirty-tracking.html to run the editor.updated() method
2. Run /components/editor/example-dirty-tracking.html
3. Make a change to the text in the editor
4. See error in console 
5. Dirty indicator is not set on editor and a change.dirty event is not fired

**Expected behavior**
Expect the dirty indicator to be placed on the editor and a change.dirty event to be fired

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/47587388-51da9980-d928-11e8-9366-2e1120667704.png)

**Additional context**
This is an issue for the soho-editor.component in ids-enterprise-ng as the updated() method is called by  ngAfterViewChecked(). 
The issue stems from the teardown() in editor.js as the textarea property is not initialized to null.
Also attached is an updated \editor\example-dirty-tracking.html that duplicates the issue.

[example-dirty-tracking.zip](https://github.com/infor-design/enterprise/files/2520546/example-dirty-tracking.zip)

**Comment by tmcconechy** [comment]
Any impression if this is a regression just  on 4.12 or not?
