### ISSUE TITLE
Autocomplete Modal Component: On Mobile device the keyboard overlaps the autocomplete list box

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1118]
**Describe the bug**
Autocomplete Modal Component: On Mobile device the keyboard overlaps the autocomplete list box

**To Reproduce**
1. Go to url: http://4120-beta0-enterprise.demo.design.infor.com/components/autocomplete/test-longpage-modal.html
2. Scroll down to "Add Context"
3. Click on the "Add Context" button
4. Click inside the "States" field box and type in "New Jersey"
4. On Portrait view the keyboard overlaps the list box

**Expected behavior**
The keyboard should not overlap the Autocomplete list box

**Screenshots**
![bs_realios_mobile_iphone x-11 0 7](https://user-images.githubusercontent.com/39101346/47661446-6fe60b00-db6f-11e8-8b00-8fda63f1b575.jpg)

**Platform**
 - Device: iPhone X
**Additional context**
None

**Comment by tmcconechy** [comment]
Going to combine this with https://github.com/infor-design/enterprise/issues/1102
