### ISSUE TITLE
Dropdown:  Listbox does not close on scroll on mobile

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1119]
**Describe the bug**
Contextual Action Panel Searchfield Component: List box opens on different areas of the UI

**To Reproduce**
1. Go to url:http://4120-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/test-searchfield-flex.html
2. Click on "Company Name" or any drop down list box
3. When the user scrolls or tries to click on different section of the page the list box doesn't close
4. Please see screen shot attached. 

**Expected behavior**
The drop down list box should close once the user clicks on another drop down list box. 

**Screenshots**
![bs_realios_mobile_iphone x-11 0 8](https://user-images.githubusercontent.com/39101346/47663181-d1f43f80-db72-11e8-85b1-80f3a47024d0.jpg)

**Platform**
 - Device: iPhone X
**Additional context**
None

**Comment by tmcconechy** [comment]
This might not be worth fixing maybe:
- remove the example and add a test
- remove the content from the modal.

**Comment by tmcconechy** [comment]
The problem is that the keyboard will cause the scrolling and close the list.
So there is really no way to fix this without breaking more stuff.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
