### ISSUE TITLE
Toolbar: Replace legacy Toolbar with Flex Toolbar in larger components

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1120]
Depends on #269 

**Is your feature request related to a problem? Please describe.**
We built the Flex Toolbar as a more CSS-driven replacement component for the original Toolbar, which utilizes some JS-based resizing techniques and overflow calculations that don't work well, and that we'd like to replace.  The Flex Toolbar is almost 1:1 feature compatible with the original.  Once that compatibility is complete, we should move to replace the usage of the current toolbar by larger components in IDS with the Flex Toolbar

**Describe the solution you'd like**
The Flex Toolbar should be the default toolbar style in the following components:
- [x] Header/Subheader
- [x] Masthead
- [ ] Contextual Action Panel (somewhat implemented)
- [ ] Card/Listview Headers
- [ ] Datagrid (standard and contextual toolbars)
- [x] Editor (standalone-style, rendered by the JS component)
- [x] Listbuilder (standalone-style toolbar, also present in toolbar folder samples)
- [ ] Listview (button row, contextual toolbar)
- [ ] Lookup (basically same as Datagrid)

Additional changes include:
- [ ] Update all example/test pages involving a Toolbar to prefer the Flex Toolbar
- [ ] We should also add full documentation on the Flex Toolbar (`readme.md`, code examples) as part of this issue.

**Describe alternatives you've considered**
We may also want to provide short-term settings for continued use of the original Toolbar in these components, with a deprecation plan.  The usage of Flex Toolbar should be the default.

**Comment by EdwardCoyle** [comment]
Noting that while working through the changes in the Header component, I noticed some hard-coded things from back in the early days of SohoXI that I made a note of fixing in #1954

**Comment by brianjuan** [comment]
Passed QA testing on all browsers, moving to Done.

**Comment by tmcconechy** [comment]
Descoping this for now due to refactor WC project. We'll do it there.
