### ISSUE TITLE
Lookup Component: Keyboard overlap when entering a product number in the search field box 

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1121]
**Describe the bug**
Lookup Component: Keyboard overlap when entering a product number in the search field box 

**To Reproduce**
1. Go to url: http://4120-beta0-enterprise.demo.design.infor.com/components/lookup/example-index.html
2. Open the Lookup 
3. Click inside the search field box and type in 2142201 and click the return button on your phone
4. The product is not appearing because the keyboard overlaps the Lookup table

**Expected behavior**
Once the user clicks on the "return" button on their device the table should be visible with the correct product ID

**Screenshots**
![img_0678](https://user-images.githubusercontent.com/39101346/47669300-ff47ea00-db80-11e8-89fe-da9033b5f258.PNG)

**Platform**
 - Device: iPhone X
**Additional context**
None

**Comment by tmcconechy** [comment]
This is a valid scenario because the field is still in focus. So the keyboard is there.
It cant just close on enter. But if they want they can press the done button to close the kyboard.
