### ISSUE TITLE
DataGrid: method updateCellNode is not always working

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#1122]
Code within the method updateCellNode does not handle the situation were the col.field contains more than three parts.  For example, we have a col.field whose value is "dataView.fields.ReceivedQuantity.value".  When col.field is split on the '.', an array with four parts is created.  The code presently only handles a col.field that contains two or three parts.

Provided a code snippet of a suggestion to handle two or more parts.

Currently coded:
`
    updateCellNode: function updateCellNode(row, cell, value, fromApiCall, isInline) {
.... (removed large part of existing code)

      coercedVal = xssUtils.unescapeHTML(coercedVal);

      if (col.field && coercedVal !== oldVal) {
        if (col.field.indexOf('.') > -1) {

          var parts = col.field.split('.');
          if (parts.length === 2) {
            rowData[parts[0]][parts[1]] = coercedVal;
          }

          if (parts.length === 3) {
            rowData[parts[0]][parts[1]][parts[2]] = coercedVal;
          }
        } else {
          rowData[col.field] = coercedVal;
        }
      }
`

Suggestion for the code:
`
    updateCellNode: function updateCellNode(row, cell, value, fromApiCall, isInline) {
.... (removed large part of existing code)

      coercedVal = xssUtils.unescapeHTML(coercedVal);

      if (col.field && coercedVal !== oldVal) {
        if (col.field.indexOf('.') > -1) {
          var rowDataObj = rowData;
          var nbrParts = col.field.split('.').length;
          col.field.split('.').forEach(function (part, index) {
            if (index === nbrParts - 1) {
              rowDataObj[part] = coercedVal;
            } else {
              rowDataObj = rowDataObj[part];
            }
          });
        } else {
          rowData[col.field] = coercedVal;
        }
      }

`

**Comment by brianjuan** [comment]
https://4140-beta0-enterprise.demo.design.infor.com/components/datagrid/example-editable
Passed QA testing on all browsers.
