### ISSUE TITLE
The cell alignment Issues in SoHo datagrid (Table)

### ISSUE THREAD

**Issue by rishni** [infor-design/enterprise#1124]
**Describe the bug**
The Cell alignment not proper way in SoHo data grid(Table)

**Expected behavior**
The table cell alignment must show the proper way.

**Screenshots**
![1new](https://user-images.githubusercontent.com/44457011/47712607-27f1e180-dc5e-11e8-951b-70d9b1a2d800.jpg)

**Platform**
  - Browser Chrome, Firefox, IE 
 - Browser Version Chrome Version:69.0.3497.58 (Official Build) (64-bit)]

**Additional context**
This issues occurred when filters used in the data grid(Table)

**Comment by tmcconechy** [comment]
Do you mean the actions column? Also can you attach the column options you are using for that column. 

I think this can be reproduced here http://master-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-toolbar-filter.html on centered aligned columns, but i cant be sure without the code for the columns.

**Comment by rishni** [comment]
I mean all the column and is there any solution to avoiding this alignment issue in Table with the filter?

**Comment by tmcconechy** [comment]
We will only fix this issue with http://master-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-toolbar-filter.html where some columns with alignment do not align when using a filter.

We cannot reproduce what you have highlighted, so must be a problem on your end. Feel free to add an example so we might be able to reproduce that part, or we'll just only fix what we see on our examples.

**Comment by rishni** [comment]
This our code and please check it.
**this is the table  options**

const gridOptions: SohoDataGridOptions = {
  columns: this.testCaseService.getColumns('list'),
  selectable: 'single',
  paging: true,
  pagesize: pageSize,
  pagesizes: [25, 50, 75, 100],
  emptyMessage: emptyDataGridMessage,
  disableClientSort: true,
  indeterminate: false,
  rowHeight: 'short', // short, medium or normal
  source: (req: SohoDataGridSourceRequest, response: any) => {
    this.busyIndicator.open();
    this.testCaseService.getData(req, filterOptionMap).subscribe((result: any) => {
      this.changeDetectorRef.detectChanges();
      this.busyIndicator.close(true);
      req.total = result.total;
      response(result.data, req);
    });
  },
} as SohoDataGridOptions;

**this is the table  columns**

private _COLUMNS: SohoDataGridColumn[] = [
  {
    id: 'key', name: 'Test Case ID', field: 'key', sortable: false, width: '100px',
    formatter: (row, cell, value, column, item) => {
      return TestCaseService.keyFormatter(item);
    }
  },
  {id: 'name', name: 'Test Case Name', field: 'name', sortable: false, width: '150px'},
  {id: 'type', name: 'Type', field: 'type', sortable: false, width: '150px', hidden: false, filterType: 'text'},
  {
    id: 'priority', name: 'Priority', field: 'priority', sortable: false, width: '150px',
    formatter: (row, cell, value, column, item) => {
      return TestCaseService.priorityFormatter(item);
    }
  },
  {id: 'automated', name: 'Automated', field: 'automated', sortable: false, width: '150px'},
  {id: 'dependancies', name: 'Dependancies', field: 'dependancies', sortable: false, width: '150px'},
  {
    id: 'status', name: 'Status', field: 'status', sortable: false, width: '150px', filterType: 'text',
    formatter: (row, cell, value, column, item) => {
      return TestCaseService.statusFormatter(item);
    }
  },
  {id: 'reporter', name: 'Reporter', field: 'reporter', sortable: false, width: '150px', filterType: 'text'},
  {id: 'assignee', name: 'Assignee', field: 'assignee', sortable: false, width: '150px', filterType: 'text'},
  {
    id: 'domainUrl',
    name: 'domainUrl',
    field: 'domainUrl',
    sortable: false,
    hidden: true,
    width: '150px',
    filterType: 'text'
  }
];

**Comment by tmcconechy** [comment]
Ok, i see you have your own formatters such as `TestCaseService.xxxFormater`. I think the problem is in that code, you probably arent structuring the html correctly so it will be padded. Since your wrote that we dont support it. But this is one example: https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.formatters.js#L10

Also did you try to check the css in your app as to what is changing the padding? As you can see in our examples it doesnt do this, so just a simple css compare of whats going on should tell you.

We will fix the header alignment issue as that is a bug.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-fixed-header-toolbar-filter.html
http://master-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-toolbar-filter.html
Actual Price column is getting out of alignment when you change the row height to Short or Medium.
Steps:
1. Click the ... Menu on the top-right of the datagrid
2. Select Short or Medium row height, Actual Price alignment will change
<img width="1089" alt="screen shot 2018-11-16 at 2 35 30 pm" src="https://user-images.githubusercontent.com/39508864/48602170-2f7aef80-e9ad-11e8-85cf-774f85488ebb.png">

**Comment by tmcconechy** [comment]
@deep7102 - Can you test and fix the row heights - good catch @brianjuan

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done folder.
