### ISSUE TITLE
Autocomplete Component: Cursor appearing in the wrong location within the drop down list box

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1129]
**Describe the bug**
Autocomplete Component: Cursor appearing in the wrong location within the drop down list box

**To Reproduce**
1. Go to url: http://4120-rc1-enterprise.demo.design.infor.com/
2. Scroll down to Autocomplete "States" field box
3. Click inside the states field box and type in "New" 
4. The following states will appear: New Hampshire, New Jersey, New Mexico, New York, and the text stating " All Results For "New"
5. The error here is that the cursor is appearing in the wrong location of the list box. Please see screens shot attached. 

**Expected behavior**
The cursor should appear in the state field box not in the middle of the word "All Results For "new"

**Screenshots**
![autocomplete states cursor error](https://user-images.githubusercontent.com/39101346/47738510-a5f7bd80-dc49-11e8-8e37-6e5754f16d10.png)

**Platform**
 - Windows 10 IE 11

**Additional context**
None

**Comment by tmcconechy** [comment]
I tried this on the page mentioned, but Im not sure how you did this.
I think that maybe the cursor is in the field below, if so that may be correct. But the list should close.

**Comment by tmcconechy** [comment]
Was unable to reproduce this one. So marking fixed.
