### ISSUE TITLE
Example Links in the Docs Should go to a new Browser Window

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1132]
**Describe the bug**
Example Links in the Docs recently added should go to a new Browser Window like the other examples.

**To Reproduce**
1. Go to url: https://staging.design.infor.com/code/ids-enterprise/4.12.0-rc.0/emptymessage (this issue happens an all pages where static links have been added on PR #1034 
2. Example Links in the Docs Should go to a new Browser Window
3. Please see screen shot attached. 

**Expected behavior**
Example Links in the Docs Should go to a new Browser Window

**Screenshots**
![screen shot 2018-10-30 at 4 08 36 pm](https://user-images.githubusercontent.com/814283/47747250-52439f00-dc5e-11e8-998b-b63b4ab0d6bc.png)

**Platform**
 - Mac Chrome

**Additional context**
None

**Comment by brianjuan** [comment]
https://staging.design.infor.com/code/ids-enterprise/latest
Passed QA testing, all links to example pages are opening in new tab.
