### ISSUE TITLE
Update demo app templates with correct URLs for patterns, layouts, and examples

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#1133]
**Is your feature request related to a problem? Please describe.**
To enable linking to patterns, layouts, and examples, within the design system website (as requested in infor-design/website#688) we need to update the linking of a few things:

- list links need to be relative to current path
- stylesheets on patterns, layouts, and examples need to be an absolute path of the build server URL

This also addresses https://github.com/infor-design/website/issues/680

**Comment by tmcconechy** [comment]
We might want to keep in mind https://github.com/infor-design/enterprise/issues/1132 as i noticed that the links i added with static urls like `https://design.infor.com/code/ids-enterprise/latest/demo/emptymessage/example-widgets?font=source-sans` are not opening in new pages like the others. This may address that?

**Comment by nickwynja** [comment]
This fix won't address that problem. The "Demo" links at the top of each page have `target="_blank"` in the template. If you want to have a link open in a new tab from the markdown file, you would need to use a standard HTML link with the `target` attribute rather than a markdown link. For example:

```
<a href="https://design.infor.com/code/ids-enterprise/latest/demo/emptymessage/example-widgets?font=source-sans" target="_blank">See empty message example</a>
```
rather than:
```
(See empty message example)[https://design.infor.com/code/ids-enterprise/latest/demo/emptymessage/example-widgets?font=source-sans]
```
