### ISSUE TITLE
Colorpicker: An extra color is added when using clearable=false

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#1135]
**Description**
An extra color, Azure01, is always added to the options when clearable is set to false.

**To Reproduce**
Use colorpicker with clearable option set to false. An extra color, Azure01, will be added to the list (see link).
https://github.com/infor-design/enterprise/blob/7f1f2f98d96119f465b4906f695d11dba4b3b17d/src/components/colorpicker/colorpicker.js#L542

This becomes an issue if using the colors option, to provide a different set of colors than the default. We do not want Azure01 to be added if providing our own color options.

**Expected behavior**
Azure01 shall only be added if standard set of colors is used. Perhaps set a property here, ex. this.hasCustomColors?
https://github.com/infor-design/enterprise/blob/7f1f2f98d96119f465b4906f695d11dba4b3b17d/src/components/colorpicker/colorpicker.js#L132

And use that to determine whether to add Azure01 or not when clearable is false.

**Platform**
Any platform or browser @ IDS 4.11.0

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the "Done" bucket.
