### ISSUE TITLE
Datagrid: Provide styles for a table

### ISSUE THREAD

**Issue by PilotBob** [infor-design/enterprise#1137]
**Is your feature request related to a problem? Please describe.**
It is fairly common in our application that use a table element, rendered server side, for tabular data However there seems to be no easy way to style a table to look like the datatable component.

**Describe the solution you'd like**
Add style or styles to apply to a table in order to duplicate the look of the datatable component.

**Describe alternatives you've considered**
Doing our own styling using the styles the datatable uses. However, it was more complicated than I thought it would be.

**Comment by tmcconechy** [comment]
We'll have to workthough if we can use the existing markup or need a set of classes specific to tables. Do you need any functionality to work such as Sort, Alternating Line Color, Filters, Row Size ect?

**Comment by PilotBob** [comment]
We use mainly for static data as well as our own jQuery based line item grid for invoice lines, billing lines, etc. So, mostly just the visual parts. Header color, font, alternating line colors option, row size class, padding, border settings, etc. I also looked at the IDS stylesheet, they don't have any way to style a table either.  

I envision just being able to add class="table row-size-compact alternate-colors" to the table tag or something as simple as that if possible. If we have to add a class to th or td or tr we can do that. But I assume the CSS would target those specifically by default.

Having some responsive classes giving the ability to hide column(s) on a smaller width screen would be a bonus.  I would expect horizontal scrolling to kick in automatically if the screen gets to narrow, but I would aways just expect full height. If we want vertical scrolling we can add it to a scrollable div ourself.

**Comment by tmcconechy** [comment]
ok, FYI we had an example where it took a table as source and "converted it" to a dataset so the grid would fully work. http://master-enterprise.demo.design.infor.com//components/datagrid/example-table-markup.html / Its different that just adding css but could be a solution if we fixed that.

**Comment by tmcconechy** [comment]
This work has been done in the new web component version. You can now use basic table styles - standalone when that version is released.
