### ISSUE TITLE
Contextual Action Panel: Clicking an item in an accordion closes the contextual action panel 

### ISSUE THREAD

**Issue by petterbr** [infor-design/enterprise#1138]
If you have an accordion in a CAP, the whenever a node in the accordion is clicked (either to reveal its children, or to select the item), the CAP will close. It seems this was fixed for _modals_ in 652afc68cbd887cb5e82e52464d7d43029b6c195, but not for contextual action panels. 
 
The following line in accordion.js, which was added at that commit
```
    $('body').children().not('.application-menu, .modal-page-container').closeChildren();
```
...should maybe be extended to...
```
    $('body').children().not('.application-menu, .modal-page-container, .contextual-action-panel, .contextual-action-panel-trigger').closeChildren();
```
A workaround exists; by adding the modal-page-container class to the .contextual-action-panel and .contextual-action-panel-trigger elements, which will cause them to hit the .not() method

**Comment by tjamesallen15** [comment]
Hi @tmcconechy,

May I get some clarifications about this ticket? :)

Thanks!

**Comment by tmcconechy** [comment]
Sure, You can also maybe talk to Eric, he did this ticket https://github.com/infor-design/enterprise/pull/796 and its the exact same thing but we did not do it for contextual action panel we only did it for modal.

So what you will want to do is make an example on contextual action panel thats similar with an accordion and test that it doesnt close according to those steps. 

Hope this helps!

**Comment by tjamesallen15** [comment]
Thanks, @tmcconechy !

**Comment by brianjuan** [comment]
http://localhost:4000/components/contextualactionpanel/test-contextual-accordion.html
http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-contextual-accordion.html
Passed QA testing on all browsers.
