### ISSUE TITLE
Contextual Action Panel: Only able to open once if contents defined in settings

### ISSUE THREAD

**Issue by petterbr** [infor-design/enterprise#1139]
**Describe the bug**
If the contents of the panel are passed to the .contextualactionpanel function (as opposed to being defined in the body markup), the CAP will open the first time, but after closing it, it will not re-appear. 

**To Reproduce**
Go to https://design.infor.com/code/ids-enterprise/latest/demo/contextualactionpanel/example-trigger?font=source-sans
Open the CAP. Close it. Try to open it again. 

**Expected behavior**
It works fine in the (internal) demo site for 4.3.4:
http://usalvlhlpool1.infor.com/4.3.4/components/contextualactionpanel/example-trigger
It also works fine when you refer to an element in the DOM to define the contents.

**Comment by brianjuan** [comment]
https://4140-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-trigger
Passed QA testing on all browsers, Contextual Action Panel can now be reopened successfully.
Also tested on:
- https://4140-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html
- https://4140-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-trigger.html
- https://4140-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/test-workspaces-buttons.html
