### ISSUE TITLE
Modal: Added Resizable and Draggable options

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1140]
**Is your feature request related to a problem? Please describe.**

There has been several requests to resize the bottom corner of a modal and an editor. Once https://github.com/infor-design/design-system/issues/105 is approved for design we can add this.

**Describe the solution you'd like**

- Add resizable: true option to editor and modal. Show a grip and allow the size to be resized.
Need a way to save (local storage).
- Add a draggable: true option to modal so you can move it within the page and see the behind content. May have to not show or dim the overlay

**Additional context**
https://github.com/infor-design/design-system/issues/105 - Design Ticket

**Comment by theakatz** [comment]
Re infor-design/design-system#105 closing this ticket

**Comment by adinenno** [comment]
After you make these changes, do you then pass it off for Landmark to adapt. This is a very good idea.

**Comment by tmcconechy** [comment]
@inforandy - cc

**Comment by tmcconechy** [comment]
@pwpatton - can you refresh my memory on reasonable use cases that require this?

**Comment by pwpatton** [comment]
I think this can be ice boxed for now. We can revisit if users bring up any issues.

**Comment by tmcconechy** [comment]
Ok, Closing this for now as we didnt really want this interaction as it complicates modals more than it needs to and encourages them to be used in more complex cases than they should be.
