### ISSUE TITLE
Error icon on tab not dismissed

### ISSUE THREAD

**Issue by boehmd1** [infor-design/enterprise#1144]
**Describe the bug**

Tab Error icon is NOT dismissed when the content no longer has an error.

**To Reproduce**
On a List in a Tab Panel
1.  Type an invalid date in the editable date cell
2.  Try to open the invalid value in the dateCellEditor
3  The tab displays an Error Icon
4.  In the table cell field, type a valid date or an empty value

**Expected behavior**
Error icon to go away.

**Screenshots**
![capture](https://user-images.githubusercontent.com/39602923/47877711-8946bb80-ddea-11e8-836b-eb96fbe6a8a6.PNG)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcastro** [comment]
Hi, I'm having trouble recreating a test page for this. Any chance I could have a sample HTML page for this?

**Comment by tmcconechy** [comment]
@boehmd1 I also cannot reproduce this - have a look at this example i made which you can drop in to app/views/components/tabs-vertical/test-datagrid.html

[test-datagrid.html.zip](https://github.com/infor-design/enterprise/files/2653901/test-datagrid.html.zip)

Have a look and see if you can add anything to reproduce. One strange this is your showing a dirty indicator there on your screen shot but we changed that all around

**Comment by tmcconechy** [comment]
Taking this out of the sprint as we cannot reproduce this. If you have further info just let us know and i'll reopen.
