### ISSUE TITLE
Extra text (Expand / Collapse) added with tree datagrid

### ISSUE THREAD

**Issue by deep7102** [infor-design/enterprise#1145]
**Describe the bug**
When using editable and treegrid option with datagrid, some extra text (Expand / Collapse) added to the target node soon try to edit parent node cell.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/test-tree-editable.html
2. Click on any parent node's cell text with (+/-) icon to get in edit mode.
3. Click anywhere else on the page or "Enter" key to get out from edit mode without make any changes.
4. See in that cell's content some extra text (Expand / Collapse) added.

**Expected behavior**
It should not add anything extra.

**Comment by tmcconechy** [comment]
@deep7102 Did you add a fix for this or is it for future?

**Comment by tmcconechy** [comment]
Added this to the sprint because deepak addressed this.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-tree-editable.html
Passed QA testing on all browsers, will do further testing once 4.15.0 build is ready.
