### ISSUE TITLE
High Contrast theme has application menu items that are hard to read.

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1146]
**Describe the bug**

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html'
2. Set the theme to High Contrast
3. Expand the My Account menu option

**Expected behavior**
The Sign out link is close to unread, and the placeholder for Search this menu is hard to read.

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/47884953-b47ce980-de82-11e8-8658-2fc2a596bfc0.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the "Done" folder.

**Comment by clepore** [comment]
While this fixes a specific instance for the high contrast theme, it changes the link color everywhere to something that is not compliant (see part of https://github.com/infor-design/enterprise/issues/1249). We need to be careful about changing global variable/token values like that.
