### ISSUE TITLE
TextArea autogrow max height setting

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1147]
**Describe the bug**
The textarea can continue to grow to a size that may be too large to manage, eg a lot of scrolling.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/textarea/example-autogrow.html'
2. Enter a large amount of text in to the autogrow textarea.

**Expected behavior**
That there was a way to limit the autogrow height to a manageable size.

**Screenshots**
The example screenshot shows a datagrid, that show the log for the active row .
![image](https://user-images.githubusercontent.com/39749678/47890923-fcab0480-dea0-11e8-8ac8-fd412f861310.png)

**Additional context**
I have looked at adding an additional setting to the textarea, autoGrowMaxHeight, that will only apply the max height if defined on the control. This will then limit the height and display the scrollbars if the content is larger than required.

**Comment by brianjuan** [comment]
http://localhost:4000/components/textarea/example-autogrow.html
http://master-enterprise.demo.design.infor.com/components/textarea/example-autogrow.html
Passed QA testing on all browsers, autoGrow and max height are working as expected.
