### ISSUE TITLE
Validation addError defaulting inline incorrectly and icon issue

### ISSUE THREAD

**Issue by PilotBob** [infor-design/enterprise#1150]
**Describe the bug**
When calling addError({ message: "Error message"}) on a field two issues are occurring.
1. It is defaulting to legacy message, ie inline is defaulting to false
2. inline: false is displaying the icon in the incorrect location and not being removed when calling removeError() on the field.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/input/example-placeholder?font=source-sans
2. Open dev tools console
3. type $("#text").addError({message: "test" })
4. You will see the icon display in the wrong position to the very right of the page.
5. type $("#text").removeError()
6. You will see the error class is removed, however, the incorrectly positioned icon is not removed.

**Expected behavior**
when calling addError() and not passing a value for inline, inline should default to true, the new display method rather than the legacy display. 
when using inline: false, the icon should be positioned inside the text field, and should be removed when removeError() is called.

**Additional context**
if I pass inline: true, it displays as expected and removeError works as expected removing the style and message.

**Comment by brianjuan** [comment]
http://4120-rc2-enterprise.demo.design.infor.com/components/input/example-placeholder.htm
http://4120-rc2-enterprise.demo.design.infor.com/components/validation/test-legacy-tooltip.html
Passed QA testing, addError() and removeError() are now working as expected.
