### ISSUE TITLE
Listview in Mixed Mode is Drilling in

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1152]
**Describe the bug**
When using a listview in mixed selection mode. Clicking the checkbox will drill in.

**To Reproduce**
1. Go to http://localhost:4000/patterns/list-detail-mixed-selection.html (new example with mixed mode)
2. Resize to less that 790px
3. Click the checkbox
4. Will expand

**Expected behavior**
Should not drill when clicking.

**Additional context**

**Comment by tmcconechy** [comment]
For some reason - didnt get closed on merge

**Comment by clepore** [comment]
Duplicate of #1143

**Comment by brianjuan** [comment]
http://4120-rc2-enterprise.demo.design.infor.com/patterns/list-detail-mixed-selection.html
Passed QA testing, fix is working on all browsers.
