### ISSUE TITLE
Multi-Select: Scroll bar not working correctly using the arrow up or arrow down key

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1158]
**Describe the bug**
Multi-Select Dropdown Component: Scroll bad not working correctly using the arrow up or arrow down key

**To Reproduce**
1. Go to url: http://4120-rc1-enterprise.demo.design.infor.com/
2. Scroll down to Multi-Select Dropdown and select a couple of states
3. Deselect a state by using your keyboard and use the arrow up or arrow down key.  
4. The issue that is occurring is that the arrow up or arrow down key is not insync with how it's moving the scroll bar. In addition, states are skip when using the arrow up or arrow down key

**Expected behavior**
The arrow up and arrow down key should be in sync with with the scroll bar 

**Screenshots**
<img width="1205" alt="multiselect scroll bar" src="https://user-images.githubusercontent.com/39101346/48009476-cd3b0880-e0e9-11e8-9d10-8b46758a690a.png">

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [MAC]
 - Browser Name [Chrome]

**Additional context**
None

**Comment by tmcconechy** [comment]
Trying on http://4120-rc1-enterprise.demo.design.infor.com/components/multiselect/example-index.html im not certain that i can reproduce any issue.

**Comment by tmcconechy** [comment]
Descoping this older issue for now
