### ISSUE TITLE
Indeterminate paging - Previous page button fails to message source fn when initially loading last page [v4.12.x]

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#1162]
**Describe the bug**
indeterminate paging - previous page button fails to message source function when initially loading last paging

**To Reproduce**
1. In the `example-paging-indeterminate-landmark.html` in getDataPage change 'initial' req.type case to fall through to the 'last' req.type case. 
```
       switch (request.type) {
          case 'first':   beginIndex = 0; break;
          case 'initial':   // <--- *NOTE*: Move 'initial' req.type to appear here and fall through to the last  req.type case.
          case 'last':    beginIndex = getData().length - request.pagesize; break;
          case 'next':    beginIndex = beginIndex + request.pagesize; break;
          case 'prev':    beginIndex = beginIndex - request.pagesize; break;

          case 'sorted':   console.log('sorted stub called - implement me'); break;
          case 'filtered': console.log('filtered stub called - implement me'); break;
        }
```

2. Go to http://localhost:4000/components/datagrid/example-paging-indeterminate-landmark.html
2. Click on previous page button
3. Notice no data changes and first and prev paging buttons become disabled.

**Expected behavior**
Previous button should message the source(reqType === 'previous') callback function.

**Screenshots**
![prevpage](https://user-images.githubusercontent.com/4737815/48028001-f2427200-e10f-11e8-8b13-2c75db7ecab5.gif)

**Platform**
 - PC
 - Windows 10
 - chrome

**Additional context**

**Comment by pwpatton** [comment]
Note, this all works fine unless you initially load the datagrid with the last page of records.

**Comment by tmcconechy** [comment]
Landmark requested this be patched back to 4.12.x

**Comment by clepore** [comment]
✅ Confirming to patch into `4.12.x`

**Comment by tmcconechy** [comment]
This was patched and can be closed
