### ISSUE TITLE
validateForm may not return a resolved state from all of the deferred processes 

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1174]
**Describe the bug**
The logic for the validate function skips over the resolution of the deferred event if the validation type has been included in the results. This works for a validation type that errors on the form as a reject has been passed and the process of validating the form will fail.

When it is a validation type that does not error the form like an alert or warning then it will not complete the processing of the deferreds if the first rule alert fails, and then there is a second alert rule on the control that passes the rule. The second rule the rusult is true, so the first section of code is skipped, and then the second section is skipped because the validation type is already included within the results object.

There needs to be an additional else if condition that will capture any validation type that do not error the form and resolve the deferred event.
```
 else if (!validationType.errorsForm ) {
          dfrd.resolve();  
        }
```
**To Reproduce**
Currently unable to replicate on an example but /components/validation/example-validation-form.html can be altered to demonstrate the error

**Expected behavior**
If there are no form error that the validateForm will return the results as true, even if there is a warning message.

**Additional context**
```
if (!result) {
          if (!self.isPlaceholderSupport && value === placeholder && rule.message !== Locale.translate('Required')) {
            return;
          }

          self.addMessage(field, rule, isInline, showResultTooltip);
          results.push(rule.type);

          if (validationType.errorsForm) {
            dfrd.reject();
          } else {
            **dfrd.resolve();**
          }
        } else if ($.grep(results, function (res) {
          return res === validationType.type;
        }).length === 0) {
          dfrd.resolve();

          if (rule.positive) {
            // FIX: In Contextual Action Panel control not sure why but need to add error,
            // otherwise "icon-confirm" get misaligned,
            // so for this fix adding and then removing error here
            self.addMessage(field, rule, isInline, showResultTooltip);
            self.removeMessage(field, rule, true);
            dfrd.resolve();
            self.addPositive(field);
          }
        }
```

**Comment by tmcconechy** [comment]
What alterations are needed to the validation/example-validation-form age to reproduce?

**Comment by marknolaninfor** [comment]
To replicate this on /components/validation/example-validation-form.html

**1. Add a second alert validation rule**

        $.fn.validation.rules.customWarningRule = {
          check: function (value) {
           
            return false;
          },
          message: 'Custom Warning 1',
          type: 'alert'
        };
        
        $.fn.validation.rules.customWarningRule2 = {
          check: function (value) {

            return true;
          },
          message: 'Custom Warning 2',
          type: 'alert'
        };

**2. Set the input to have two warning messages.**

<div class="field">
        <label for="credit-code">Code</label>
        <input type="text" id="credit-code" class="input-sm" name="credit-code" data-validate="customWarningRule customWarningRule2" data-mask="###" data-mask-mode="number"/>
      </div>

**3. Add some Javascript to run validateForm, for example when an input changes to validate all the rules.**

        $('input').on('change', function() {
          $('#test-form').data('validate').validateForm(function (result) { 
          console.log('validateForm retult', result);
          });
        });

**4. Test the form by entering all of the required values that will error the form.**

When validateForm should return a true value there is nothing returned.
