### ISSUE TITLE
Button focus on DOM elements that no longer exist causes console error

### ISSUE THREAD

**Issue by mmmild** [infor-design/enterprise#1177]
**Describe the bug**
Clicking a button that is subsequently removed from the DOM causes error in the console, due to attempting to set focus.

**To Reproduce**
1. Go to any environment that has Homepages 12.0.27 (or later), where the user has the role "Homepages-ADMINISTRATOR"
2. Click on the application menu (...) -> "Advanced" -> "Administration"
3. From the admin view, click on the "Switch to Homepages" button
4. See error in console

**Expected behavior**
No focus is (forcibly) attempted to be set on elements that no longer exists in the DOM.

**Screenshots**
![focus_error](https://user-images.githubusercontent.com/43241773/48137354-25b50600-e2a2-11e8-8d63-c5fd24aa662c.gif)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 70.0.3538.77 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
We should be able to just add a safety check on setActiveButton in toolbar.js.

**Comment by tmcconechy** [comment]
@mmmild we probably need to test this on the app. I may be wrong. Can you email me and Deepak Details on how to get in and check?

**Comment by mmmild** [comment]
Sure, just sent a separate email.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done bucket.
