### ISSUE TITLE
DatePicker: Ability to set first day of week in date picker configuration

### ISSUE THREAD

**Issue by brianmwchui** [infor-design/enterprise#1179]
**Is your feature request related to a problem? Please describe.**

We need to control the first day on the datepicker configuration.

**Describe the solution you'd like**

Add a firstDayofWeek option to datepicker that overrides whats used in locale.

**Describe alternatives you've considered**

It may be possible to change the locale
```
Locale.currentLocale.data.calendars[0].firstDayofWeek = 1 // starts on monday
$('my-datepicker').datepicker();
```

**Additional context**

See also https://jira.infor.com/browse/UXD-961

**Further Background**

What WFM needs, however, is a customer configurable start day of the week. WFM supports time-and-attendance and scheduling for many customers worldwide. While locale plays a role into the start day of week, what our customers need is a way to configure the date pickers to align with their payroll weeks. For example, we have customers who have 2-week pay cycles that start on a Friday. They currently configure their start day of week to be Friday. 
Just a little background: in WFM's old datepicker field UI, if no start day of week is configured on the specific date field, then it aligns with the system's overall configuration (via a registry parameter). If a start day of week is configured on a specific date field, then such configuration "overrides" the system-level configuration.

**Comment by janahintal** [comment]
http://localhost:4000/components/datepicker/test-set-first-day-of-week.html
Moving to QA Failed
Incorrect Date displayed. 
<img width="330" alt="screen shot 2018-12-13 at 1 14 08 pm" src="https://user-images.githubusercontent.com/45757016/49917272-7f2fd680-fed9-11e8-8917-5c60a0f74088.png">

**Comment by tmcconechy** [comment]
@janahintal Can you elaborate on whats incorrect here? It does seem to be correct to me its Dec 13th and the calendar starts on Monday to the left?

**Comment by janahintal** [comment]
Hi @tmcconechy , Yes, the calendar does start on Monday and that is correct. But when you check the dates in the Calendar and its corresponding Day you will notice that there is some discrepancy. In my screenshot above, I'm expecting that In December 2018 Calendar, December 13 should be on Thursday and not Friday (please see screenshot below). 

_Regular December 2018 Calendar:_
![image](https://user-images.githubusercontent.com/45757016/49980745-b2cd3800-ff8f-11e8-8646-6c366e54311e.png)

**Comment by tmcconechy** [comment]
@ericangeles Can you check into this, let me know if you need help. What im seeing is with this setting @janahintal is correct the calendar is not updated correctly. But if we use the locale setting it does seem to work for example http://localhost:4000/components/datepicker/example-index.html?locale=sv-SE so i think the setting is maybe not doing something properly that that example does.

Thanks

**Comment by ericangeles** [comment]
Sure. Will look into it.

**Comment by ericangeles** [comment]
Tried to test this example http://localhost:4000/components/datepicker/example-index.html?locale=sv-SE but it seems that it's the same with the example that I created.

**Comment by tmcconechy** [comment]
Seems like to pushed a PR, i guess you found it after?

**Comment by ericangeles** [comment]
Yup. Found out the issue then.

**Comment by CindyMercadoReyes** [comment]
QA BDD Test Script Attached:
[story_github#1179.docx](https://github.com/infor-design/enterprise/files/2691047/story_github.1179.docx)

**Comment by janahintal** [comment]
QA Passed. Moving to Done. 
Tested in: https://github.com/infor-design/enterprise/issues/1179

**Comment by brianmwchui** [comment]
Thanks for completing the fix.  Is there an ETA to make this feature available in the angular version of date picker control?

**Comment by tmcconechy** [comment]
You can follow that here: https://github.com/infor-design/enterprise-ng/issues/304 
Can also try to do a pull request if you want - but we didnt put a date on 5.1.0 of NG yet
