### ISSUE TITLE
Splitter collapse button not localized, text not changing

### ISSUE THREAD

**Issue by darinw** [infor-design/enterprise#1180]
**Describe the bug**
on the soho splitter component, the title text does not change on close, it also does not localize the text.

**To Reproduce**
1. Go to https://github.com/infor-design/enterprise/blob/6a02596a30ddcadf5cb59343bed5bc62a44bc160/src/components/splitter/splitter.js#L98

**Expected behavior**
the text should either be removed, or when closed change to "expand" it also needs to be localized
it would also be nice if it was a soho-tooltip

**Comment by tmcconechy** [comment]
@darinw Any objections to no tooltip? i dont see the need for it showing everytime as the icon shows the direction?

**Comment by brianjuan** [comment]
https://4140-beta0-enterprise.demo.design.infor.com/components/splitter/test-collapse-button.html
Passed QA testing on all browsers.
