### ISSUE TITLE
Field Filter doesn't allow filter value to be set programmatically

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#1181]
**Is your feature request related to a problem? Please describe.**
There currently isn't a way to set the value of the field filter programmatically, which means I can't reset a filter field value from a search field or with a button click.

**Describe the solution you'd like**
A programmatic way to get the field filter drop down value.

**Comment by janahintal** [comment]
QA Passed. Moving to Done. 
Verified in: http://localhost:4000/components/field-filter/example-filtertype.html
