### ISSUE TITLE
Tree structure expand/collapse all does not work for "dirty" tree

### ISSUE THREAD

**Issue by deep7102** [infor-design/enterprise#1183]
**Describe the bug**
If user expands/collapse one node in Soho Tree, expand all/collapse all stops working

**To Reproduce**
Run enterprise-ng project

Go to Tree - Content
Click on Public Folders
Click on Expand All/Collapse All
See Tree does not expand/collapse and actually hides the node children

**Expected behavior**
Expand all/Collapse all would work even though user would manually expand/collapse node

**Screenshots**

**Platform**
- OS Version: Windows 10
- Browser Name Chrome

**Additional context**
Moved from the NG project: infor-design/enterprise-ng#250

**Comment by brianjuan** [comment]
http://localhost:4000/components/tree/test-expand-collapse-all.html
http://master-enterprise.demo.design.infor.com/components/tree/test-expand-collapse-all.html

**Comment by brianjuan** [comment]
http://localhost:4000/components/tree/test-expand-collapse-all.html
http://master-enterprise.demo.design.infor.com/components/tree/test-expand-collapse-all.html
Passed QA testing on all browsers, expand/collapse all is working as expected.
