### ISSUE TITLE
Datagrid Dropdown Editor - when have a source option the display value is being cleared  

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#1185]
Have a datagrid column with a dropdown editor that makes use of the source editorOptions.  When the dropdown is opened the relevant option item is not selected.  If the user clicks off the dropdown without selecting a value, the cell's value is changed to an empty string.

To Reproduce:
See the attached example that demonstrates the issue.

**Comment by claudenbach** [comment]
Changed the file extension to txt in order to attach.
[test-dropdown-editor-source.html.txt](https://github.com/infor-design/enterprise/files/2559146/test-dropdown-editor-source.html.txt)

**Comment by tmcconechy** [comment]
Do you get an error by any chance?

**Comment by claudenbach** [comment]
There is no error in the browser's debugger.

**Comment by ericangeles** [comment]
I tested it and I found interesting output. Instead of an empty string, it reverts back the date of descending order instead of the ascending one. It seems that when you click the value (e.g. date,) the functionality of the sorting didn't destroy, and it lays on the input field.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-editor-dropdown-source.html
Passed QA testing on all browsers.
