### ISSUE TITLE
The datagrid tooltips stop displaying after a lookup is opened

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1186]
**Describe the bug**
The datagrid tooltips stop displaying after a lookup is opened.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html'
2. Clear the first rows Product Id to display an error, and hover to display tooltip.
3. Open the lookup for the second Product Id and then close it
4. See error, as the tooltips do not display, and you can create new errors by clearing other Product Id's and the tooltips do not display.

**Expected behavior**
Error tooltips are displayed

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the "Done" folder.
