### ISSUE TITLE
Datagrid Editable Component: Calendar for Order Date as alignment issues

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1191]
**Describe the bug**
Datagrid Editable Component: Calendar for Order Date as alignment issues

**To Reproduce**
1. Go to url: http://master-enterprise.demo.design.infor.com/components/datagrid/example-editable
2. Click 3/15/2016 from the "Order Date" column
3. The calendar icon is appearing to close to the date
4. Please see screen shot attached. 

**Expected behavior**
Spacing is needed between the date and the calendar icon

**Screenshots**
<img width="1297" alt="datagrid calendar alignment issue" src="https://user-images.githubusercontent.com/39101346/48220955-b81adf80-e35e-11e8-95fc-989e9aaa1bce.png">

**Platform**
 - OS Version: [iOS 8]

**Additional context**
None

**Comment by tmcconechy** [comment]
This is an example issue only. We can just make the column wider. Also you can resize the column.
Almost a non-issue, but we can clean this up later.

**Comment by tmcconechy** [comment]
Should fix this with #1168 since the column is not defaulting to a good size
