### ISSUE TITLE
Datagrid: Readonly fields are hard to read in the high contrast theme

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1193]
**Describe the bug**
Read-only fields are harder to read in the high contrast theme

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html'
2. Change the theme to high-contrast

**Expected behavior**
A user has  asked if it is possible to lighten the read only fields.

**Screenshots**
Comment from a user regarding the read-only field. "The background colour in grids is really dark where the value is non-maintainable once saved.  The colour is fine when it's just individual fields like the Application Number but really doesn't look good in a 'block' like the grid."
![image](https://user-images.githubusercontent.com/39749678/48243394-1ebbfe00-e430-11e8-823b-a29412277a3a.png)

When the form is in the light theme the read-only datagrid field, is a lighter shade compared to the field that is also read-only.
![image](https://user-images.githubusercontent.com/39749678/48319011-062e2c80-e658-11e8-8190-f3056653ea11.png)

**Comment by kayiuho** [comment]
I noticed that there's a difference between the screenshot and the EP demo. In the screenshot, read-only state BG is implemented with #999999. In the EP demo, `.datagrid td.is-readonly` (in High Contrast) is #BDBDBD. 

<img width="1250" alt="screen shot 2018-11-20 at 12 27 05 pm" src="https://user-images.githubusercontent.com/34747859/48791935-f9957e00-ecc0-11e8-83cb-a3f80919674d.png">

**Comment by marknolaninfor** [comment]
I can confirm that with the current version the BG color is #BDBDBD. No action required as it has been corrected.
![image](https://user-images.githubusercontent.com/39749678/48808114-ad554700-ed6f-11e8-9e12-8178ecf89ebd.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
