### ISSUE TITLE
Swaplist items lost on drag and drop

### ISSUE THREAD

**Issue by hernebrink** [infor-design/enterprise#1195]
**Describe the bug**
When moving swaplist items by drag and drop, in an fast manner items are "lost" in the ui.

**To Reproduce**
1. Go to [latest swaplist example](https://design.infor.com/code/ids-enterprise/latest/demo/swaplist/example-selected.html?font=source-sans)
2. Select multiple items in one of the lists and drag them over in a fast manner to the next one. 
3. Items will disappear from the ui

**Expected behavior**
To have the selected items moved and visible

**Screenshots**
The .gif illustrates the difference in dragging and dropping slow vs fast
![swaplist-issue](https://user-images.githubusercontent.com/4176143/48263438-650c5f80-e426-11e8-88f2-591f29e5cb7e.gif)

**Platform**
 - OS Version: [Windows 10]
 - Browser Name [chrome]
 - Browser Version [70.0.3538.77 (Official Build) (64-bit)]

**Comment by tmcconechy** [comment]
I can reproduce this if you
- select all in first list and drag over
- select first five in other list
- does seem to be related to drag and drop speed

**Comment by CindyMercadoReyes** [comment]
Hi @tmcconechy This is working correctly on across all browsers. However, on iPhone X you are only able to swap list once. It doesn't allow you to swaplist again.

**Comment by tmcconechy** [comment]
On let’s take a look @tmcsstro

**Comment by tmcconechy** [comment]
For the last part i made a new issue https://github.com/infor-design/enterprise/issues/1423 so we can fix that later (next sprint)

**Comment by tmcastro** [comment]
Thanks, Tim. That last part is a bit tricky

**Comment by brianjuan** [comment]
Will now move this to Done, I didn't encounter any issue other than #1423
