### ISSUE TITLE
Datepicker - Issues with range picker, resetting the old values.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1197]
**Describe the bug**
There are some issues with date picker when using range picker.

**To Reproduce**
Bug One
1. Go to http://localhost:4000/components/datepicker/example-range.html
2. Click on the picker and select a range
3. Go back in the field
4. Clear the values
5. Open again 
6. Error: The picker should not be showing the old value

Bug Two
1. Go to http://localhost:4000/components/datepicker/example-range.html
2. Click on the picker and select a range
3. Go back in the field
4. Type a value in the field
5. Should not have to hit space in between in the mask
5. Open again 
6. Error: The picker should not be showing the old value

**Expected behavior**
Should reflect the value in the field. 

CC Lothar Blum

**Comment by tmcconechy** [comment]
Part is related to https://github.com/infor-design/enterprise/issues/415

**Comment by tmcconechy** [comment]
Noting that issue on is fixed but issue 2 is open as a duplicate #415

**Comment by tmcconechy** [comment]
Yes it should, im trying again and not seeing any problem with those. It does not seem to be reverting to the old value. Can you test on http://4130-beta0-enterprise.demo.design.infor.com/components/datepicker/example-range.html instead of localhost to be sure your on the right code?

**Comment by brianjuan** [comment]
Hi @tmcconechy , I also tried http://4130-beta0-enterprise.demo.design.infor.com/components/datepicker/example-range.html and I can still encounter the bug on "Range - Disable Not included" and "Range - Disable included". And also on "Range - Initial value by Settings"
![datepicker_oldval3](https://user-images.githubusercontent.com/39508864/49057661-8305fc80-f23b-11e8-84a7-c4790a974a88.gif)

**Comment by tmcconechy** [comment]
OK i see on the clear. Can we make a new ticket for this last part then.

**Comment by brianjuan** [comment]
Created new ticket #1306

**Comment by brianjuan** [comment]
https://4130-rc0-enterprise.demo.design.infor.com/components/datepicker/example-range.html
Bug 1 and Bug 2 are now fixed, tested on all browsers. Moving to this Done.
