### ISSUE TITLE
Dropdown control: Cannot open dropdown when destroy() method is called for another dropdown

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#1202]
**Describe the bug**
When the destroy() method for a dropdown control is executed from another dropdown control, the is-open class is not removed from the executing dropdown and the executing dropdown can no longer be opened.

This functionality is required as the soho-dropdown.component in ids-enterprise-ng will execute the destroy() method when the component is removed from a template. In Landmark, there is functionality to dynamically show or remove controls based on some criteria. In this instance, a dropdown is set to be visible when a certain value is selected from another dropdown; otherwise, a text component is set to be visible.

Would like this change to be in 4.13.

**To Reproduce**
1. Using the attached dropdown/example-destroy.html 
2. Arizona is setup to destroy the Numeric dropdown
3. Click on the States dropdown and select Arizona
4. The Numeric dropdown should be removed
5. Click on the States dropdown
6. The States dropdown does not open

**Expected behavior**
Expect the dropdown to open

**Screenshots**
![dropdown-destroy-issue](https://user-images.githubusercontent.com/20212079/48369830-3f2cc800-e67d-11e8-9133-7c08f01d36e0.gif)

**Additional context**
[example-destroy.zip](https://github.com/infor-design/enterprise/files/2573295/example-destroy.zip)

**Comment by fitzorama** [comment]
I think your folks are better situated to make the change. I came up with something, but believe it to be more of a work around.

**Comment by brianjuan** [comment]
http://localhost:4000/components/dropdown/example-destroy.html
http://master-enterprise.demo.design.infor.com/components/dropdown/example-destroy.html
File not found when accessing the URL

**Comment by tmcconechy** [comment]
Try:

http://localhost:4000/components/dropdown/test-destroy.html
http://master-enterprise.demo.design.infor.com/components/dropdown/test-destroy.html

My fault, as i asked @davidcarlsonberg to rename these as these are more tests than front facing examples. Also there is a unit test for this.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done folder.
