### ISSUE TITLE
Dialogs are closed on hash change

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#1207]
**Describe the bug**
When `window.location.hash` is changed, any open dialogs (CAP, About etc.) are closed.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/contextualactionpanel/example-index
2. Click the "Contextual Action Panel" button
3. In the browser console, type `window.location.hash = "something"`
4. The CAP is closed, and it cannot be re-opened by clicking the button.

**Expected behavior**
The text `#something` is appended to the page URL, and nothing more.

**Screenshots**
![dialog_onhashchange](https://user-images.githubusercontent.com/4991954/48414549-5d60f980-e74b-11e8-89bc-d1ae82771dad.gif)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 70.0.3538.77 (Official Build) (64-bit)

**Additional context**
We encounter this problem when using the `enterprise-ng` library, but it can be reproduced without them so I figured it was best to report it to this project. I'm not entirely sure if this behavior is a feature or a bug. If it is a feature, is there any way to disable it?

**Comment by tmcconechy** [comment]
We found that it was added because of https://jira.infor.com/browse/SOHO-5975 , so its intended to close when back button is hit. We think either a setting or removing this code and making the app manage this is most appropriate.

**Comment by EdwardCoyle** [comment]
To clarify, I think we just want to remove all the code that closes the CAP on the `popstate` event.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
