### ISSUE TITLE
Timepicker/Dropdown - Shows un-needed tooltip

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1214]
**Describe the bug**

**To Reproduce**
1. Go to http://localhost:4000/components/timepicker/example-index.html or http://master-enterprise.demo.design.infor.com/components/timepicker/example-index.html
2. hover over the AM/PM picker -> here a tooltip shows this isnt really needed so should just hide this in dropdown.js
3. Press OK
4. See that the tooltip stays around. (Should be ok if 2 was just fixed)

**Expected behavior**
No tooltip is needed since you can see all the text.

**Platform**
- all

**Additional context**
Maybe caused by #38 and needs an adjustment
This example should still work after: http://localhost:4000/components/dropdown/test-multiselect-with-tooltip

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
