### ISSUE TITLE
Error in the console when opening a context menu that is generated dynamically.

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#1216]
**Describe the bug**
Currently, a right click context menu on a datagrid has a trigger of 'immediate' when the popupmenu is initialized. This causes and error to be displayed in the javascript console when the popupmenu doesn't exist in the dom yet. 

**To Reproduce**
1. Go to test-contextmenu.html in your system and delete the 'grid-actions-menu' div.
2. Navigate to the test-contextmenu page
3. Right click on a row in the table
4. See error in the console

**Expected behavior**
The popupmenu's init method shouldn't attempt to open a menu that doesn't exist yet.

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/48506170-7383be00-e80e-11e8-9f97-2518eeba39b0.png)

**Platform**
 - All

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-contextmenu-dynamic.html
http://master-enterprise.demo.design.infor.com/components/datagrid/test-contextmenu-dynamic.html
Passed QA testing on all browsers, no error showed in console.
