### ISSUE TITLE
Remaining Calendar Features (Part Two)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1221]
This ticket lists all features done with calendar in Nov sprint.

**Added Nov/Oct Sprint**
- [x] upcoming events view
- [x] when no icon, the event should be left aligned
- [x] when selecting a day from the month switcher datepicker it doesn't go to that direct day..
- [x]  Right to left cleanup/retest
- [x] refactor showTodaysMonth to selectDay
- [x] comment back in the xit tests
- [x] keyboarding around on the calendar days
- [x] veracode scan

The rest carries on on #841 which may be further broken out.

**Comment by CindyMercadoReyes** [comment]
Hi @tmcconechy For Windows 10 IE 11 the color legends are not displayed on the calendar. Please see screen shot attached. 
![win 10 ie11 calendar index page](https://user-images.githubusercontent.com/39101346/48791861-c521c200-ecc0-11e8-8626-b9db349a435a.png)

**Comment by brianjuan** [comment]
https://4130-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html
Passed QA testing on all browsers including the bug fix for IE and Dark theme, moving to Done.
