### ISSUE TITLE
Regression on search field sizes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1228]
**Describe the bug**
Search field/categories seems off now.

**To Reproduce**
1. Go to http://localhost:4000/components/searchfield/example-categories-full.html
2. Compare to http://4120-enterprise.demo.design.infor.com/components/searchfield/example-categories-full.html

**Expected behavior**
Should work like before.

**Additional context**
Not sure what caused this.

**Comment by EdwardCoyle** [comment]
Tracked this down to the changes from #1176.  Nothing major, I'm going to push a fix as part of the Toolbar Searchfield improvements for #269

**Comment by EdwardCoyle** [comment]
Closing this, since this was fixed as part of #1148
