### ISSUE TITLE
Enter key opens dropdown list, when it should only be used to select items within an open list

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#1239]
According to the documentation, the following key behaviours apply to drop-down lists...

![image](https://user-images.githubusercontent.com/44396995/48700603-4f482880-ebe4-11e8-887b-d10ccc27ad19.png)

...so pressing space or down arrow is documented as opening the list dropdown (so is alt+down arrow but doesn't work in FireFox/Google), but pressing the Enter key also opens the list, and this causes a big problem for us as out applications use enter as input/advance, so if the user has focus on a drop-down they cannot advance to the next screen without moving to a non-list field.

Previously, in 4.4 version, I was able to override this behaviour by putting an addtional key-down event on the "pseudoElem", but now it seems that there is another key event firing before this so the list is already open.

Ideally, the drop-down should conform to the documented behaviour, but if that is not possible, I need to be able to intercept the very first key-down event and block it before the "list open" event is fired (FYI - tried using the onKeyDown option and that only appears to be called when the list is already open) , so any recommended example of doing that would be useful.

**Comment by tmcconechy** [comment]
I think your right, enter should only work when the list is open or you cant submit the form. We should be following these guidelines https://www.w3.org/TR/wai-aria-practices-1.1/#combobox and as noted in the docs. i also tested the onKeyDown and it is in fact only working when open.

Changes
- Make onKeyDown work when closed
- fix alt+down arrow
- make enter not block and not open the list
- test other keys.

**Comment by tmcconechy** [comment]
@ericangeles make sure to test https://github.com/infor-design/enterprise/issues/1262 as well but i think thats a dup, just give it a test and we should be good on that too.

**Comment by brianjuan** [comment]
http://localhost:4000/components/dropdown/test-allow-custom-keystroke.html
Moving to failed QA. Enter key doesn't work when the list is open.

**Comment by tmcconechy** [comment]
@ericangeles - For that case you could just update the example so the enter key works if the list is open. Fx.. 

```
if ('#dropdown-list').is(':visible')) {
   return;
}
```

**Comment by janahintal** [comment]
QA Passed. Moving to Done.
Tested in https://4140-beta0-enterprise.demo.design.infor.com/components/dropdown/test-allow-custom-keystroke.html

**Comment by CindyMercadoReyes** [comment]
QA BDD Test Script:
[story_github#1239.docx](https://github.com/infor-design/enterprise/files/2691043/story_github.1239.docx)
