### ISSUE TITLE
Jenkins PR master builds only cancel other master builds

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1240]
**Is your feature request related to a problem? Please describe.**
See if there is anyway to only have `master` builds in jenkins cancel out other master builds, instead of release builds like "beta", "rc", and "final".

**Describe the solution you'd like**
Update script

**Describe alternatives you've considered**
Not worrying about it.

**Additional context**
n/a

**Comment by tmcconechy** [comment]
Descoping for now in favor of "Not worrying about it."
