### ISSUE TITLE
More Actions Buttons: Tooltip doesn't disappear

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1242]
**Describe the bug**
Toolbar -flex Component: Tooltip doesn't disappears on RTL

**To Reproduce**
1. Go to url: http://master-enterprise.demo.design.infor.com/components/toolbar-flex/example-eyebrow.htmll?locale=ar-SA
2. Click on the 3 dot icon 
3. The tooltip appears on top of "Pre-defined item #1 and when I use the arrow key up or down the tooltip doesn't go away. Which doesn't allow me to view the first option from the dropdown list box
4. Please see screen shot attached. 

**Expected behavior**
The tooltip should disappear after a couple of seconds. 

**Screenshots**
<img width="1347" alt="toolbar flex tooltip" src="https://user-images.githubusercontent.com/39101346/48732841-c98da280-ec0e-11e8-8b4c-93db4f304356.png">

**Platform**
 - OS Version: [iOS 8]
 - Browser Name [Chrome]

**Additional context**
None

**Comment by EdwardCoyle** [comment]
Just noting here:  This was originally reported as only happening on RTL, but I was able to reproduce it under normal circumstances as well:

http://master-enterprise.demo.design.infor.com/components/toolbar-flex/example-eyebrow.html

**Comment by EdwardCoyle** [comment]
Also changed it to "More Actions" buttons.  This is actually happening on the Header Toolbars as well, which are not (currently) Flex Toolbars.  Something to do with the auto-add of the tooltip on More Actions buttons in general

**Comment by EdwardCoyle** [comment]
@brianjuan I see the tooltip still being displayed over top of the More Menu on some occasions... I think I've got a fix for that.

However, I tested on IE11 and did not see a situation where the menu doesn't open:

![nov 26 2018 10_59 am](https://user-images.githubusercontent.com/3249601/49025943-b7f64e80-f16a-11e8-8da3-e456694bfd23.gif)

**Comment by tmcconechy** [comment]
@EdwardCoyle We may have fixed some IE errors on 4.13 branch, im thinking.

**Comment by tmcconechy** [comment]
Closed via #1245 and #1282

**Comment by brianjuan** [comment]
https://4130-rc0-enterprise.demo.design.infor.com/components/toolbar-flex/example-eyebrow.htmll?locale=ar-SA
Passed QA testing on all browsers, including the bug found on IE. Moving to Done.
