### ISSUE TITLE
Datagrid - Display text for a button is not fully rendered

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#1246]
**Describe the bug**
Have a datagrid column that contains a button through the use of the `Formatters.Button`. When a `grid.hideColumn()` is performed, the display text on the button is not fully rendered. The button column is the last column in the grid.

**To Reproduce**
1. See screenshot below

**Expected behavior**
The button should be fully rendered.

**Version**
- ids-enterprise: 4.x.0

**Screenshots**
Landmark example:
![image](https://user-images.githubusercontent.com/39804038/48790842-dd401400-ecb5-11e8-8d5d-36ad2e50dfa3.png)

**Platform**
 - Desktop browsers

**Additional context**
n/a

**Comment by claudenbach** [comment]
Changed the file
[test-button-not-fully-rendered.html.txt](https://github.com/infor-design/enterprise/files/2600821/test-button-not-fully-rendered.html.txt)
 extension to txt in order to attach file.

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/48790842-dd401400-ecb5-11e8-8d5d-36ad2e50dfa3.png)

This is an example from Landmark.

**Comment by tmcconechy** [comment]
Maybe similar to https://github.com/infor-design/enterprise/issues/1168

**Comment by clepore** [comment]
@claudenbach Thanks for your submission, but please update the description to follow the `bug request` or `feature request` template. Thanks!

**Comment by claudenbach** [comment]
@clepore Not sure what you're looking for.  The issue is typed as a bug.  I've also previously attached an example that illustrates the issue.

**Comment by clepore** [comment]
I'll ping you on teams so we can chat 👍

**Comment by clepore** [comment]
🏁 Possibly related to and fixed with work from #1456

**Comment by brianjuan** [comment]
http://4160-beta0-enterprise.demo.design.infor.com/components/datagrid/test-button-not-fully-rendered.html
Passed QA testing on all browsers.
