### ISSUE TITLE
Menu button Component: ticker has alignment issues

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1247]
**Describe the bug**
Menu button Component: ticker has alignment issues

**To Reproduce**
1. Go to http://4130-beta0-enterprise.demo.design.infor.com/components/menubutton/test-default.html
2. Click on "Add item" drop down list box
3. The ticker is not aligned correctly
4. Please see screen shot attached. 

**Expected behavior**
The alignment has to be corrected

**Screenshots**
![bs_win10_firefox_63 0](https://user-images.githubusercontent.com/39101346/48795704-aa087f80-eccb-11e8-9bd8-cbdcec417cc0.jpg)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [ Win 10]
 - Browser Name [IE 11, FF]

**Additional context**
None

**Comment by tmcconechy** [comment]
This is just an example issue.
