### ISSUE TITLE
disableClientSort/disableClientFilter visual for the filter bar and sort indicator are lost after each loading of data.

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#1248]
**Describe the bug**
When loading data with datagrid.loadData any filter field and sort visual state is lost when disableClientFilter and disableClientSort are used, respectively.

Suggest not resetting the visual state when these settings are being used. The justification for that would be that the implementing code should manage all those when these settings are used.

**To Reproduce**
1. Change this in components/datagrid/example-filter.html 
```
* Make sure one column has a sortable: true
      columns.push({ id: 'productName', name: 'Product Name', field: 'productName', sortable: true, formatter: Formatters.Hyperlink, filterType: 'text', click: function(e, args){ console.log(e, args);}});

* use disableClientfilter and sort settings and loadData when filtered adn sorted events are fired. 

      // Init and get the api for the grid
      var datagrid = $('#datagrid').datagrid({
        columns: columns,
        dataset: data,
        filterable: true,
        selectable: 'single',
        disableClientFilter: true,
        disableClientSort: true,
        editable: true,
        emptyMessage: {title: Locale.translate('NoData'), info: Locale.translate('NoDataFilter'), icon: 'icon-empty-no-data'},
        toolbar: {title: 'Filterable Datagrid', filterRow: true, results: true, dateFilter: false ,keywordFilter: false, actions: true, views: false, rowHeight: true, collapsibleFilter: false}
      }).on('filtered', function (e, args) {
        console.log('filtered', args);
        datagrid.loadData(data);
      }).on('sorted', function (e, args) {
        console.log('sorted', args);
        datagrid.loadData(data);
      }).data('datagrid');
```
2. Open the sample 
3. Click on sort column and note the sort indicator doesn't seem to get set. 
4. Enter in a filter value and type enter. notice the value is cleared

**Expected behavior**
When using the disableClientFilter and disableClientSort calling loadData should leave the visual state of these as is and not clear them.

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version 70.0.3538.102 (Official Build) (64-bit)

**Additional context**

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-disable-client-filter-and-sort.html
Passed QA testing on localhost and master, will do a retest once 4.15.0 build is provided.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
