### ISSUE TITLE
Contrast / Token Issues with High Contrast and Dark Theme

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1249]
**Describe the bug**
Found a couple bugs in high contrast theme and dark theme.

1. Menu buttons and icon buttons are too dim
    http://localhost:4000/components/icons/example-index.html
    http://localhost:4000/components/menubutton/example-index.html
    - change to high contrast

1. Links are too light 
    http://localhost:4000/components/hyperlinks/example-index.html
    http://localhost:4000/components/button/example-index.html
    - change to high contrast

1. disabled checkboxes seem too light
    http://localhost:4000/components/checkboxes/example-index.html
    http://localhost:4000/components/radios/example-index.html
    - change to dark theme
    - same with radios and inputs?

**Screenshots**

**Additional context**
Start out on #1088 but this is a separate issue

**Comment by clepore** [comment]
- [ ] 1. Menu buttons and icon buttons are too dim
- [ ] 2. Links are too light
- [ ] 3. disabled checkboxes seem too light

**Comment by brianjuan** [comment]
Pages above passed QA testing on all browsers, color issues on different themes are now fixed. Moving to Done.
