### ISSUE TITLE
The "initialized" event is not called if a non-standard locale is used

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#1267]
The "initialized" event is not called if a non-standard locale is used.

Our application allows the customer to define and configure their own locales. In the pre-SoHo Xi versions of the controls (3.x), if the customer defined a locale that the controls did not recognise/support, it defaulted to en-US so at least the program continued to work.

In SoHo Xi, if an invalid locale is passed to the initialize() method, it seems to prevent the "initialized" event from firing, which, in our application, is where all the page load and configuration functionality is located, so, to the end user, the application appears to freeze.

Here is a simple example...

```
		var initialLocale = 'xx-XX';
		//var initialLocale = 'en-UK';

		$('body').initialize({
			locale : initialLocale
		}).on('initialized', function() {
			alert("Initialized fired");
		});

```

Add this script to any standard SoHo Xi page template and the alert box will not be fired. Comment the "xx-XX" locale variable and uncomment the "en-UK" one and it works as expected. 

Looking in the sohoxi.js, it looks like it should be dropping down to the "en-US" locale as a default, but in the init function, if the "Locale.set(locale)" fails, it will not call the self.initAll() method, which then calls the "initialized" event.

**Comment by tmcconechy** [comment]
The problem with the way this works is that the event is attached after the call and fired during the call. So you would need to do it like this.

```
var initialLocale = 'en-UK';

$('body').on('initialized', function() {
  alert("Initialized fired");
}).initialize({
  locale : initialLocale
});
```

or like this

```
var initialLocale = 'en-UK';

$('body').on('initialized', function() {
  alert("Initialized fired");
});

// later
$('body').initialize({
  locale : initialLocale
});
```

**Comment by tmcconechy** [comment]
On further testing a workaround is to do it like this, because in the case of a not found locale it doesnt call a promise and delay the event, so need to establish it first. Not sure if there is a better solution...

```
<script>
  // Initialize all IDS Enterprise Controls and set the locale
  var initialLocale = 'xx-XX';

  $('body').on('initialized', function() {
    alert("Initialized fired");
  }).initialize({locale: initialLocale});
</script>
```

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done folder.
