### ISSUE TITLE
Date Picker Range: Selected dates with month/year picker are not selected when date picker was opened again

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1268]
**Describe the bug**
Date Picker Range: Selected dates with month/year picker are not selected when date picker was opened again.

**To Reproduce**
1. Go to http://localhost:4000/components/datepicker/example-range.html
2. Open the date picker on "Range - Month Year Picker"
3. Select November 2019 on the dropdowns
4. Select November 1, 2019 - November 8, 2019
5. Close the Date Picker, then open again
6. Select November 2019 on the dropdown, notice that November 1 to November 8 are not selected, only the November 8

**Expected behavior**
Selected range of dates using month/year picker should still be selected when the date picker was opened again.

**Version**

- v4.10.0 - v.4.13.0

**Screenshots**
<img width="535" alt="screen shot 2018-11-23 at 6 55 13 pm" src="https://user-images.githubusercontent.com/39508864/48940158-9ff7b280-ef51-11e8-95ed-1311082eee78.png">

**Platform**
 - All browsers, OS and devices.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Closing this issue as it is no longer valid as the picker is built in.
