### ISSUE TITLE
Datagrid applyfilter does not work with related datafields

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1269]
**Describe the bug**
The logic to set the rowValue within apply filter is not correct and will not failback to the fieldValue function when it need to evaluate any related data.

The test is only if rowData exists, and not that also rowData[columnDef.field] does not return an undefined value. Our example has the columnDef.field set as 'csysmpt.descr'
```
let rowValue = rowData ? rowData[columnDef.field] :
          self.fieldValue(rowData, columnDef.field);
```
Correct check will then fail to the function, as rowData['csysmpt.descr'] will return undefined.
```
let rowValue = rowData && rowData[columnDef.field] !== undefined ? rowData[columnDef.field] :
          self.fieldValue(rowData, columnDef.field)
```
**To Reproduce**

**Expected behavior**
The rowValue is set correctly so that the datagrid can be filtered.

**Version**
v4.14

**Screenshots**
Example of rowData to filter the csysmpt.descr field
![image](https://user-images.githubusercontent.com/39749678/48985254-832bcc80-f155-11e8-9e0c-b63b693269f3.png)

**Comment by tmcconechy** [comment]
Moved to Dec sprint for QA as this was added by external team. (Thanks Mark)

**Comment by janahintal** [comment]
QA Passed. Moving to Done. 
Tested in: https://4140-beta0-enterprise.demo.design.infor.com/components/datagrid/test-filter-editable.html [All browsers, devices and OS]
