### ISSUE TITLE
Tree: Previously selected nodes are being selected again after child nodes are loaded

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1270]
**Describe the bug**
Tree: Previously selected nodes are being selected again after child nodes are loaded via AJAX.

Affected Pages:
http://4130-beta0-enterprise.demo.design.infor.com/components/tree/example-ajax.html
http://4130-beta0-enterprise.demo.design.infor.com/components/tree/example-context-menu.html
http://4130-beta0-enterprise.demo.design.infor.com/components/tree/example-destroy.html

**To Reproduce**
1. Go to the URLs above
2. Click "Node One" to select
3. Click "Node Two" to load its child nodes, notice that "Node One" will be selected/highlighted together with the "Node Two"
4. Now click "Node 2.1" to select
5. Click "Node 2.2" to load its child nodes, notice that "Node One", "Node Two", "Node 2.1" and "Node 2.2" will be selected/highlighted

**Expected behavior**
Previously selected nodes should not be selected again after child nodes are loaded via AJAX

**Version**
v4.10.0 - v4.13.0

**Screenshots**
<img width="797" alt="screen shot 2018-11-26 at 6 03 13 pm" src="https://user-images.githubusercontent.com/39508864/49007234-f6f5c580-f1a5-11e8-835d-372ca0ad104f.png">

**Platform**
 - All devices, OS and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Not a regression it was doing this back to 4.11.

**Comment by brianjuan** [comment]
http://localhost:4000/components/tree/example-ajax.html
http://localhost:4000/components/tree/example-context-menu.html
http://localhost:4000/components/tree/example-destroy.html
Passed QA testing in localhost and master, will test again once 4.15.0 build is provided.
