### ISSUE TITLE
Color picker: Tooltip is showing on top-left of the page after picking a color

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1273]
**Describe the bug**
Color picker: Tooltip is showing on top-left of the page after picking a color.

**To Reproduce**
1. Go to http://4130-beta0-enterprise.demo.design.infor.com/components/colorpicker/example-index.html
2. Open color picker
3. Select a color, the tooltip will display on the top-left of the page
4. Sometimes it doesn't trigger, just continue to select other colors to trigger the bug

**Expected behavior**
Color tooltip should not display on other places

**Version**
v4.13.0

**Screenshots**
![colorpicker_tooltip](https://user-images.githubusercontent.com/39508864/49008662-586b6380-f1a9-11e8-9dc0-187668dd9dd3.gif)

**Platform**
 - All OS and browsers except mobile

**Additional context**
Intermittent issue

**Comment by tmcconechy** [comment]
Closed via #1297

**Comment by brianjuan** [comment]
https://4130-rc0-enterprise.demo.design.infor.com/components/colorpicker/example-index.html
Passed QA testing on all browsers, moving to Done.
