### ISSUE TITLE
DatePicker control no longer auto-closes on lose-focus once the time has been changed

### ISSUE THREAD

**Issue by pjm16** [infor-design/enterprise#1278]
**Describe the bug**
We're using the DatePicker for Date + Time selection. For time selection the control remains open after a change is made. In Soho 4.6.0 the control would close when focus was lost.

Since ids-enterprise 4.10.0, the control remains open once the time has been changed. It can only be closed by clicking the date again. The control remains open throughout all other screen operations.

**To Reproduce**
1. Go to datepicker
2. Change the time
3. Click away from the control
4. The control remains open

(repeat but without changing the time - the control auto-closes correctly)

**Expected behavior**
We need the control to auto-close. 

**Version**
- ids-enterprise-ng 4.10.0 and 4.13.0

**Screenshots**
screenshot added just to illustrate

**Platform**
- latest Chrome browser on Windows PC

**Additional context**

The control is configured in HTML with Angular bindings as below. Any date format and disable options can be used.

<div class="field">
            <input soho-datepicker name="dateTo" [dateFormat]="displayFormat" showTime="true" mode="standard" [placeholder]="true" [disable]="disableOptions"
                formControlName="dateTo" />
        </div>

![datepicker](https://user-images.githubusercontent.com/29760363/49027388-18d35600-f16e-11e8-88fb-49338b902b8e.png)

**Comment by tmcconechy** [comment]
Closed via #1283

**Comment by brianjuan** [comment]
https://4130-rc0-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html
Passed QA testing on all browsers, date picker now closes properly. Moving to Done.
