### ISSUE TITLE
Toolbar Flex Component: Menu button cut off on responsive view

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1279]
**Describe the bug**
Toolbar Flex Component: Menu button cut off on responsive view

**To Reproduce**
1. Go to url: http://4130-beta0-enterprise.demo.design.infor.com/components/toolbar-flex/example-favor-buttonset.html
2. Make the page responsive
3. The Menu button is cut off. Please see screen shot attached.

**Expected behavior**
The page needs to be responsive

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

<img width="486" alt="toolbar flex 2" src="https://user-images.githubusercontent.com/39101346/49029716-48d12800-f173-11e8-9d42-bd7266bb88d4.png">

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [iOS 8]
 - Browser Name [Chrome]

**Additional context**
None

**Comment by tmcconechy** [comment]
Closing as wont fix. There isnt really any solution for this that is viable.
