### ISSUE TITLE
Circle Pager Tabs Component: Similar Products tab is not displayed correctly on responsive view

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1284]
**Describe the bug**
Circle Pager Tabs Component: Similar Products tab is not displayed correctly on responsive view

**To Reproduce**
1. Go to url: http://4130-beta0-enterprise.demo.design.infor.com/components/circlepager/example-tabs.html
2. Make the page responsive
3. Click the down arrow key and select "Similar Products
4. The circle images are not being displayed properly. Please see screen shot attached. 

**Expected behavior**
The images should not overlap each other. 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="400" alt="circle 1" src="https://user-images.githubusercontent.com/39101346/49043167-4a611700-f198-11e8-8058-e0a184ba3bf9.png">

**Platform**
 - OS Version: [iOS 8]
 - Browser Name [Chrome]

**Additional context**
None

**Comment by janahintal** [comment]
QA Failed. Issue still exist. 
Tested in : http://master-enterprise.demo.design.infor.com/components/circlepager/example-tabs.html & http://localhost:4000/components/circlepager/example-tabs.html

**Failing on all PC Browsers**. Working well in Mobile devices os and browsers. 

**Steps to replicate:** 
1. Open PC Browser
2. Goto : http://master-enterprise.demo.design.infor.com/components/circlepager/example-tabs.html & http://localhost:4000/components/circlepager/example-tabs.html
3. Click on > Technical Specifications Tabs
4. Minimize the screen 
5. Using the arrow key drop down button, click on > Similar Products 

<img width="392" alt="screen shot 2019-01-17 at 1 02 03 pm" src="https://user-images.githubusercontent.com/45757016/51296827-b6ede900-1a58-11e9-840b-ff3f8783d65c.png">

**Comment by tmcconechy** [comment]
@tjamesallen15 can you please take a quick look?

**Comment by tmcconechy** [comment]
Ok Sounds good. For your information i just followed the steps exactly as above and i was able to see the issue as well.

<img width="536" alt="screen shot 2019-01-22 at 9 50 41 am" src="https://user-images.githubusercontent.com/814283/51543273-31d54c00-1e2b-11e9-880c-0e61b1ceda73.png">

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to Done.
