### ISSUE TITLE
RTL: Donut Chart Title Component as alignment issues

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1293]
**Describe the bug**
Donut Chart Title Component: RTL alignment issue

**To Reproduce**
1. Go to URL: http://4130-beta0-enterprise.demo.design.infor.com/components/donut/example-values.html
2. The line for 40 and 30 are overlapping on Win 10 Edge 17
3. Please see screen shot attached.

**Expected behavior**
The should be no over lapping

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![bs_win10_edge_17 0 1](https://user-images.githubusercontent.com/39101346/49098813-c6616a80-f23d-11e8-8020-296664f4d3a8.jpg)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [Windows 10 ]
 - Browser Name [Edge 17]

**Additional context**
None

**Comment by tmcconechy** [comment]
Can no longer reproduce this issue. Closing
