### ISSUE TITLE
RTL: Donut Values Component numeric values not appearing correctly

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1295]
**Describe the bug**
Donut Values Component: RTL numeric values not appearing correctly

**To Reproduce**
1. Go to url: http://4130-beta0-enterprise.demo.design.infor.com/components/donut/example-values.html?locale=ar-SA
2. The number on the chart are not aligned. 
3. Please see the screen shot attached. 

**Expected behavior**
The numeric values should be aligned within the chart

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

![bs_win10_edge_17 0 3](https://user-images.githubusercontent.com/39101346/49105321-48f22600-f24e-11e8-8954-793360a703c4.jpg)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [Windows 10]
 - Browser Name [Edge 17]

**Additional context**
None

**Comment by tmcconechy** [comment]
Should be fixed along with https://github.com/infor-design/enterprise/issues/1293

**Comment by tmcconechy** [comment]
Can no longer reproduce this issue on 4.26
