### ISSUE TITLE
Datagrid Dropdown Editor - dropdown window is to small 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#1298]
Have a datgrid column that uses the Editors.DropDown. Open the dropdown, the rendered dropdown window is to small.

To reproduce:
See the attached example that demonstrates the issue.

**Comment by claudenbach** [comment]
Changed the file extension to txt in order to attach file.
[test-dropdown-window-size.html.txt](https://github.com/infor-design/enterprise/files/2621922/test-dropdown-window-size.html.txt)

**Comment by tmcconechy** [comment]
FYI you can zip the things you want to attach as well.

**Comment by claudenbach** [comment]
![enterprise-1298](https://user-images.githubusercontent.com/39804038/49113032-0afaff00-f25a-11e8-8e9c-25ab3aa58bf4.gif)

**Comment by claudenbach** [comment]
[Git1298.zip](https://github.com/infor-design/enterprise/files/2622079/Git1298.zip)

**Comment by marknolaninfor** [comment]
#909 needs to also be tested with the fix.

http://localhost:4000/components/datagrid/example-editable.html

**Comment by tmcconechy** [comment]
Added this issue to the sprint for QA as it was solved by an external team (Thanks Mark)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. However, another issue was found while testing this ticket. 
GitHub ticket: https://github.com/infor-design/enterprise/issues/1396
