### ISSUE TITLE
Dropdown - no-search doesnt work with capital letters

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1301]
**Describe the bug**
When using no-search option with dropdown it is not possible to type ahead to select things when using CAPS.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/dropdown/example-no-search.html
2. Type 'S'

**Expected behavior**
Expect it to work with caps same as it does on  http://master-enterprise.demo.design.infor.com/components/dropdown/example-index

**Version**
- ids-enterprise: [e.g. v4.11.0 up to v4.13.0]

**Additional context**
Was partially fixed on #363

**Comment by awbuboltz** [comment]
Hey Tim, do you have an ETA on this?

**Comment by tmcconechy** [comment]
We have it in for next sprint so End of Jan.. Or sooner

**Comment by awbuboltz** [comment]
Great, thanks!

**Comment by janahintal** [comment]
QA Failed.

**Comment by janahintal** [comment]
QA Failed. 
Tested in:  http://localhost:4000/components/dropdown/example-no-search.html

Failing on all Windows _OS 10_ Browsers, Android 8 and iOS. 
Issue fixed and working well on all MAC OS _(tested in Mojave)_ browsers 

Steps:
1. Open Windows or Mobile (Android or iOS) Browser 
2. Type 'S'
3. No event has been fired

**Comment by tmcconechy** [comment]
@ericangeles - As we discussed please check this out. Not seeing anything in the errors.
Maybe the way the keys are retrieved from the events?

**Comment by janahintal** [comment]
QA Passed. 
Tested in: **https://4150-beta0-enterprise.demo.design.infor.com/components/dropdown/example-no-search.html** across all browsers & OS
