### ISSUE TITLE
DataGrid: Clear dirty indicator on cells

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#1303]
Have a datagrid that sets the showDirty option to true.  Make changes to cells in a row so that the cell dirty indicator is shown.  There is no way to clear the dirty cell indicator for a specific row.  

Landmark business case:
- User makes changes to cells in several rows of the datagrid
- User performs a save action
- Rows that were successfully saved, want to remove the dirty cell indicator
- Row that were not successfully saved, want to show a row status with a tooltip explaining the reason for the failure.  This is working via the grid.rowStatus(row, status, tooltip)

Perhaps just enhance rowStatus to clear the dirty cell indicators when the status is an empty string?

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/test-dirty-indication.html
Passed QA testing on localhost and master, will do testing again once 4.15.0 build is provided.
