### ISSUE TITLE
Tabs: Date field inside panel doesn't have date picker

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1304]
**Describe the bug**
Tabs: Date field inside panel doesn't have date picker.

**To Reproduce**
1. Go to http://4130-beta0-enterprise.demo.design.infor.com/components/tabs/test-datepicker-in-panel.html
2. Click on "Notes" tab
3. See bug, Date Field does not have date picker

**Expected behavior**
Date Field inside tab panel should have date picker

**Version**
v4.13.0

**Screenshots**
<img width="977" alt="screen shot 2018-11-29 at 6 38 05 pm" src="https://user-images.githubusercontent.com/39508864/49216499-36225180-f406-11e8-961f-538d633ae8c8.png">

**Platform**
 - All Devices, OS and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
I retested this on the 4.13 branch it it seems ok - i think another PR fixed this

**Comment by brianjuan** [comment]
https://4130-rc0-enterprise.demo.design.infor.com/components/tabs/test-datepicker-in-panel.html
Passed QA testing on all browsers, moving to Done.
