### ISSUE TITLE
Toast: Toast messages are not closing automatically

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1305]
**Describe the bug**
Toast: Toast messages are not closing automatically.

Affected pages:
http://4130-beta0-enterprise.demo.design.infor.com/components/toast/example-index.html
http://4130-beta0-enterprise.demo.design.infor.com/components/toast/example-positions.html
http://4130-beta0-enterprise.demo.design.infor.com/components/toast/test-allow-links.html

**To Reproduce**
1. Go to URLs above
2. Click buttons to show toast message
3. See bug, toasts will not close automatically

**Expected behavior**
Toast messages should close automatically

**Version**
v4.13.0

**Platform**
 - All Devices, OS and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Closed via PR #1305

**Comment by brianjuan** [comment]
https://4130-rc0-enterprise.demo.design.infor.com/components/toast/example-index.html
https://4130-rc0-enterprise.demo.design.infor.com/components/toast/example-positions.html
https://4130-rc0-enterprise.demo.design.infor.com/components/toast/test-allow-links.html
Passed QA testing on all browsers, moving to Done.
