### ISSUE TITLE
Hierarchy Context Menu With Detail Component: Submenu don't open on responsive view

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1309]
**Describe the bug**
Hierarchy Context Menu With Detail Component: Submenu don't open on responsive view

**To Reproduce**
1. Go to url: http://4130-beta0-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html
2. Make the page responsive
3. Click on the 3 dot button
4. The menu box doesn't open.  Please see screen shot attached. 

**Expected behavior**
The menu box should open on responsive view. 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="422" alt="hierarchy responsive view error" src="https://user-images.githubusercontent.com/39101346/49235039-27687a00-f3c7-11e8-994f-c064a5aebad4.png">

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [iOS 8]
 - Browser Name [Chrome]

**Additional context**
None

**Comment by tmcconechy** [comment]
cc @krishollenbeck - not sure if you want to fix this or not?

**Comment by krishollenbeck** [comment]
@tmcconechy Sure I can look at sometime. I will keep it on my radar

**Comment by tmcconechy** [comment]
Descoping this issue for now
