### ISSUE TITLE
Hierarchy Context Menu Detail Component: RTL has alignment issues on Win 10

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1310]
**Describe the bug**
Hierarchy Context Menu Detail Component: RTL has alignment issues on Win 10

**To Reproduce**
1. Go to url: http://4130-beta0-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html?locale=ar-SA
2. Scroll down to were you see the top level hierarchy for "Jonathan Cargill Director FT"
4. His name and title are appearing outside the box. Please see screen shot attached. 

**Expected behavior**
The name and title should appear inside the box

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![hierarchy rtl error](https://user-images.githubusercontent.com/39101346/49235687-a316f680-f3c8-11e8-9c68-ae16666b9301.png)

**Platform**

 - OS Version: [Win 10]
 - Browser Name [IE 11]

**Additional context**
None

**Comment by tmcconechy** [comment]
cc @krishollenbeck in case you want to fix this.

**Comment by krishollenbeck** [comment]
@tmcconechy Was RTL implemented in Hierarchy? I don't recall doing work for that.

**Comment by tmcconechy** [comment]
I might have then

**Comment by tmcastro** [comment]
Hi @deep7102,

Do you have a fix for this already? I checked this issue this morning and I found a fix for this. Can you check if I did it right? Thanks

**Comment by janahintal** [comment]
QA Passed.
Tested in: http://localhost:4000/components/hierarchy/example-context-menu-with-details.html?locale=ar-SA for all browser, os and devices
