### ISSUE TITLE
Expandable Area Component: Drop down arrow cut off on responsive view

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1311]
**Describe the bug**
Expandable Area Component: Drop down arrow cut off on responsive view

**To Reproduce**
1. Go to url: http://4130-beta0-enterprise.demo.design.infor.com/components/expandablearea/example-index.html
2. Make the UI responsive
3. Click "Shoe More" for each expandable area
4. More Customer Details box is cut off
5. Other dropdown list box is cut off and the arrow is not displayed. 
6. Please see screen shot attached. 

**Expected behavior**
The right corner edge of both boxes should not be cut off. In addition, the drop down arrow key should be visible.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="335" alt="expandable area error" src="https://user-images.githubusercontent.com/39101346/49110972-e05e7580-f25c-11e8-8128-fd2ee3b54ed7.png">

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [OS 8]
 - Browser Name [Chrome]

**Additional context**
Noe

**Comment by tmcconechy** [comment]
This is probably just another example issue
