### ISSUE TITLE
Hierarchy Many Children Component: Open position alignment issue on responsive view

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1312]
**Describe the bug**
Hierarchy Many Children Component: Open position alignment issue on responsive view

**To Reproduce**
1. Go to url: http://4130-beta0-enterprise.demo.design.infor.com/components/hierarchy/example-many-children.html
2. Scroll down to the bottom of the page
4. The blank circle for open position is not correct. Please see screen shot attached 

**Expected behavior**
The open position icon needs to be formatted correctly for responsive view.

**Version**
- mac firefox
- ids-enterprise: [e.g. v4.9.0 or v4.10.0 and up to 4.16.0]

**Screenshots**
<img width="335" alt="hierarchy responsive view open position error" src="https://user-images.githubusercontent.com/39101346/49237191-b4153700-f3cb-11e8-8f1b-b4cf56fb5858.png">

**Platform**
 - OS Version: [iOS 8]
 - Browser Name [FireFox]

**Additional context**
None

**Comment by tmcconechy** [comment]
cc @krishollenbeck in case you want to fix this.

**Comment by krishollenbeck** [comment]
@tmcconechy I will keep it on my radar. Might be awhile before I can look into this.

**Comment by tmcconechy** [comment]
This page is no longer present so descoping this issue
