### ISSUE TITLE
double click on open accordion will close it but set the icon to open

### ISSUE THREAD

**Issue by darinw** [infor-design/enterprise#1314]
**Describe the bug**
When you double click an open accordion-header the it will close on the first click, but will not reopen on the second. the arrow will change to open on the second click. On the third click the arrow will flip back with the content remaining closed. with the fourth click it will be back to normal

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/accordion
2. Click on accordion-header
3. Once open double click accordion-header

**Expected behavior**
either open back up or not allow the second click from going through

**Version**
current release 4.12.1

**Comment by janahintal** [comment]
QA Passed. Moving to Done.
Tested in: http://localhost:4000/components/accordion/example-index.html for all browser, OS and devices.
