### ISSUE TITLE
Lookup Editable Component: Look is left blank if you click on the hyperlink

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1315]
**Describe the bug**
Lookup Editable Component: Look is left blank if you click on the hyperlink

**To Reproduce**
1. Go to url: http://4130-beta0-enterprise.demo.design.infor.com/components/lookup/example-editable.html#
2. Open the lookup
3. Check off product number "2142201" 
4. Click on the hyperlink within that product "Compressor" 
5. The pop closes and the product number "2142201" doesn't appear in the lookup
6. Click on the lookup icon again
7. Product ID "2142201" is still selected, click on the "Apply" button
8. Again the product id doesn't appear in the lookup field box. 

**Expected behavior**
The product id should appear in the lookup window.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1265" alt="lookup editable error" src="https://user-images.githubusercontent.com/39101346/49246642-6dcbd200-f3e3-11e8-8cc1-4594d94ee469.png">

**Platform**
  - OS Version: [iOS 8]
 - Browser Name [Chrome]

**Additional context**
None

**Comment by tmcconechy** [comment]
We tested this again for 4.15 and did not find the issue anymore. Two cases seem to work ok.

http://master-enterprise.demo.design.infor.com/components/lookup/example-multiselect.html
- clicking the link here toggles selection

http://master-enterprise.demo.design.infor.com/components/lookup/example-editable.html
- clicking the link here goes in edit mode.

Furthermore the link is probable incorrect to use here as you have multiple things going on (selection vs navigation in the popup). As part of #1136 will clean this up and remove some examples and links.
