### ISSUE TITLE
Tree Control - Node styling

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#1321]
**Is your feature request related to a problem? Please describe.**
We are using tree control in Infor GRC for rule building section. We are currently facing on issue. We are showing Role Name and Role Description as a tree node which is get render has one string. 
We need provision to add two different strings so we can style them with different colors.

**Describe the solution you'd like**
Provide solution  where we can add different colors for node text.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

![screen shot 2018-12-03 at 9 17 59 am](https://user-images.githubusercontent.com/814283/49379120-673ba400-f6dc-11e8-9501-d0297918c5cb.png)

**Comment by dhumalkishor** [comment]
I am unable to attach document so please refer below link for more details.
https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1542955639752?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1542955639752&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Angular%20Components&createdTime=1542955639752

**Comment by tmcconechy** [comment]
To attach a document zip it first and then drag it into the comments or press upload. 

https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by tmcconechy** [comment]
Attached the screen shot to make this all in one place. By colors do you just mean the bold?

**Comment by dhumalkishor** [comment]
[Tree Control.zip](https://github.com/infor-design/enterprise/files/2678902/Tree.Control.zip)

**Comment by tmcconechy** [comment]
I think this was completed?
