### ISSUE TITLE
Custom Builds: Can't include component files containing extra periods in the filename

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1322]
**Describe the bug**
Some component filenames are causing the custom builder to not be able to execute.  This is due to a bad `export` statement being written whenever a filename contains an extra `.`.  For example, I witnessed a build fail when attempting to include `toolbar-flex.item.js`.

**To Reproduce**
Attempt to run a custom build with the following:
```sh
npm run build:custom -- --components=autocomplete,toolbar-flex
```
The console will inform you of the error, but won't go into much detail.  After the temp files have been generated by the above command, try running the following:
```sh
rollup -c --components=autocomplete,toolbar-flex
```
This will generate a more elaborate output with a reference to the bad export statement.

**Screenshots**
![screen shot 2018-11-30 at 2 07 51 pm](https://user-images.githubusercontent.com/3249601/49309469-5e16c100-f4a9-11e8-98b0-4c1c27130477.png)

**Expected behavior**
The build should complete without issue, including all components listed.

**Version**
- v4.9.0+ (any version that implements the IDS Custom Builder)

**Platform**
 - All

**Additional context**
Related to filename changes that might be necessary per #833

**Comment by tmcconechy** [comment]
See comments on https://teams.microsoft.com/l/message/19:6d4c9079385840c0bc61e55bcdd16a33@thread.skype/1563563661210?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1563563661210&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Problems&createdTime=1563563661210

**Comment by jake-harrington** [comment]
We're currently experiencing this trying to use 4.19.x. I'm running into the same error doing:
`npm run build -- --disable-css --components=button,toolbar`
This is necessary for us to be able to update from 4.11.x and we use custom builds like this exclusively.

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to the Done folder. There is no way for QA to test this ticket.
