### ISSUE TITLE
Pathway Critical Items for Calendar Feature

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#1324]
**Is your feature request related to a problem? Please describe.**

Hi below is the order of the critical items Pathway needs for the Calendar feature. (The first three are the most critical)

Most Critical
- [x] adding events - on add button (with API)
- [x] adding events - on add button (with modal)
- [x] editing events - on clicking (with modal)
- [x] showing more than one event in a day in the details

Secondarily Critical
- [ ] drag times to extend / reduce them across days, Drag events to other days
- [x] adding events - on double click
- [ ] week view

**Comment by tmcconechy** [comment]
Note that this is is an extension of #1289 giving priorities on those items. I'll see if its possibly that  we can pick this up sooner but putting for Jan sprint for now.

**Comment by tmcconechy** [comment]
I was able to finish all the above except drag drop and weekview (so mainly able to add/remove events and some tune ups). The remaining two items are back up on https://github.com/infor-design/enterprise/issues/1289 and ranked. Should be able to finish that one up next time (but not necessarily next sprint as we have some other things planned).

**Comment by brianjuan** [comment]
Hi, is this also expected to work on mobile for now? Adding events via double click doesn't work on iOS, and also showing details of more than one event in a day doesn't work on both Android and iOS.

**Comment by brianjuan** [comment]
Thanks @tmcconechy , will now move this to Done since it passed QA testing on all Desktop browsers.
