### ISSUE TITLE
Need a new icon to reinforce the need to do search 

### ISSUE THREAD

**Issue by nbcp** [infor-design/enterprise#1325]
**Is your feature request related to a problem? Please describe.**
Need an icon to help reinforce that the user needs to take a "search" action rather that showing you have an empty search result.

**Describe the solution you'd like**
The new icon would look like this:
![image](https://user-images.githubusercontent.com/11013464/49353474-df17c780-f6f8-11e8-8870-2274c1a41754.png)

**Here is the svg in a zip file:**
[icon-no-search-data.zip](https://github.com/infor-design/enterprise/files/2638082/icon-no-search-data.zip)

**Comment by lipetzan** [comment]
Need Landmark milestone on this one @tmcconechy  - Thanks.

**Comment by tmcconechy** [comment]
Actually this is in the wrong spot. This should go on https://jira.infor.com/browse/UXD as Manilla is making the icons now. CC me on the issue and I'll add it to IDS once its complete.

**Comment by tmcconechy** [comment]
I misunderstood that this was a designed icon already. So need to add to the code

**Comment by tmcconechy** [comment]
@nbcp or @lipetzan - Where did you get this icon from? It doesnt seem to be exported like the other icons so i cant seem to render it. 

Expect an 18 x 18 view box and trimmed down to minimal paths.
https://raw.githubusercontent.com/infor-design/enterprise/4.5.x/images/additional-icons/add-employee.svg

Can you get however made this to try another way to export?

**Comment by tmcconechy** [comment]
Actually looking at the Jira is this an icon or empty message?

http://master-enterprise.demo.design.infor.com/components/icons/example-index.html
or
http://master-enterprise.demo.design.infor.com/components/emptymessage/example-index.html

Maybe thats why its an empty icon right?

**Comment by nbcp** [comment]
@tmcconechy yes this is for empty message. 
@jamie-norman can you get this svg exported in how tim expects it? thanks

**Comment by jamie-norman** [comment]
@tmcconechy Let me know if this works okay:
[iconEmptyErrorLoading.svg.zip](https://github.com/infor-design/enterprise/files/2663432/iconEmptyErrorLoading.svg.zip)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
