### ISSUE TITLE
Display theme tabs for embedded demos

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#1327]
**Is your feature request related to a problem? Please describe.**
People want to visually see dark and contrast examples of the embedded demos on Enterprise components.

**Describe the solution you'd like**
Use tabs to provide options to switch between different themes of that same demo.

https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs/example-index?font=source-sans

**Describe alternatives you've considered**
Maybe a dropdown instead? But I think tabs would be better.

**Comment by tmcconechy** [comment]
This was done.
