### ISSUE TITLE
Error Clicking Clear formatting in NG

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1328]
**Describe the bug**

Using the clear format button with nothing selected in angular gives an error. This is a Enterprise error but only seen in NG. Maybe just need a null check.

**To Reproduce**
1. Go to http://localhost:4200/editor
2. Click on clear formatting with nothing selected.

**Additional context**
Need to add it to the example in src/app/editor/editor.demo.ts around line 50.

```
  'separator', 'anchor',
  'separator', 'clearFormatting',
  'separator', 'source'
],
```

**Comment by brianjuan** [comment]
Can this be tested in Enterprise?

**Comment by brianjuan** [comment]
Can we test this in Enterprise?

**Comment by tmcconechy** [comment]
No sorry, can’t be tested in EP

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by tmcconechy** [comment]
This issue should have been closed
