### ISSUE TITLE
Dropdown: Deprecate legacy render processes in favor of its templating system

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1329]
**Is your feature request related to a problem? Please describe.**
After #377 is implemented and battle-tested, we should replace the current Dropdown component's internal process for rendering content in favor of the newer render steps based on templates.  This would allow for some general customizations of Dropdown content.

**Describe the solution you'd like**
- [ ] Create a default, standard template for both:
  - In-page Element
  - List Element
- [ ] Set these as defaults for the `componentTemplate` and `listTemplate` settings, which will disable the old rendering methods.
- [ ] Comments/warnings/whatever in the console when using the old method and explicitly changing the settings to `undefined/null`

**Additional context**
#377 Precedes this issue and must be completed beforehand

**Comment by tmcconechy** [comment]
Closing this for now - we will use html templates in WC version
