### ISSUE TITLE
multiselect grid ignores links and buttons in custom formatter

### ISSUE THREAD

**Issue by mlick27** [infor-design/enterprise#1331]
**Describe the bug**
I have a multiselect datagrid. In the first column with an ID, I need to provide a link and a button in the same cell, as well as other information, but for the purpose here, that's not important.  Whenever a user clicks on the link or the button, the row is getting selected rather than the action associated with the link or button.  It's as if the table row is a layer over everything and it's recognizing the table row being clicked, but not the link or button.

**To Reproduce**
1. Go to [](http://usalvwaldevd16:4000/components/datagrid/MLexample-multiselect.html)
2. Click on any link or button in the Product ID column.  An alert box should pop up saying which was clicked.  Instead, the row is selected.

**Expected behavior**
An alert should popup and the row should NOT be selected.

**Version**

4.12.1 and 4.13.0-dev

**Comment by tmcconechy** [comment]
Usually we just use two different cells, one for the link or button and the next cell for the ID. The problem is the keyboard only works cell by cell - with screen reader ect.

But you should be able to achieve this with a Custom Formatter. Here is an example: https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-custom-formatter.html

Also check out the options `selectable: false` and `clickToSelect: false,` and possibly `cellNavigation: false,`.

I think that might give you what you need.

**Comment by mlick27** [comment]
I'm using a custom formatter to put the link and button in the same cell.  There's other information and icons that's also included in that formatter, that for the sake of the example I've removed.  I'm not able to split the link and the button into separate columns.  The business has decided they like this design.  I lost that fight months ago.  

`      columns.push({ id: 'productId', name: 'Product Id', field: 'productId', width: 150,
            formatter: function (row, cell, value, columnDef, dataContext) {

                    var cell = '<div style="display:table">';
                    cell += '<div class="table-row"><a href="javascript: LinkClick(' + value + ')" class="hyperlink" >' + value + '</a>';
                    cell += '<button type="button" class="btn-icon row-btn" tabindex="-1" onClick="ButtonClick(' + value + ')"><svg class="icon" focusable="false" aria-hidden="true" role="presentation"><use xlink:href="#icon-edit"></use></svg><span></span></button></div>';
                    return cell;
	            }
            })
`
Neither LinkClick or ButtonClick are firing.  I tried doing all combinations of selectable, clickToSelect, and cellNavigation to no help.  Any other suggestions?

**Comment by mlick27** [comment]
Doesn't seem to do anything when added to my column with the custom formatter.  It just ignores it.  My link and my button do two different actions in the same column.  This all works fine in 4.3.2.

`      columns.push({ id: 'productId', name: 'Product Id', field: 'productId', width: 150,
			click: function (e, args) {
				console.log(args);      // NEVER FIRES
			},
            formatter: function (row, cell, value, columnDef, dataContext) {

                    var cell = '<div style="display:table">';
                    cell += '<div class="table-row"><a href="" onclick="console.log(' + value + ')" class="hyperlink" >' + value + '</a>';
                    cell += '<button type="button" class="btn-icon row-btn" tabindex="-1" onclick="console.log(' + value + ')"><svg class="icon" focusable="false" aria-hidden="true" role="presentation"><use xlink:href="#icon-edit"></use></svg><span></span></button></div>';
                    return cell;
	            }
            })
`

**Comment by tmcconechy** [comment]
As a workaround for this..

a) you can turn off the links internal code with `$('#readonly-datagrid table').off('click')` and the link will work
b) For the button you can do it with a seperate event
```
$('#readonly-datagrid table button').on('click.namepsace', function () {alert()})
```

I think whats happening is the internal code is stripping the onclick for security (xss).
Also for the link we added code so links would NOT redirect to handle cases for angular. I think you wold have to just turn off that event in order for this case to work

**Comment by mlick27** [comment]
Well, that was a help.  Not entirely perfect, but it lead me in the right direction.  There were a bunch of steps I had to do to make it work.

You can see the demo of the problem here: http://usalvwaldevd16:4000/components/datagrid/MLexample-multiselect.html

And a demo and explanation of my solution here:
http://usalvwaldevd16:4000/components/datagrid/MLexample-multiselect-fixed.html

I'd like your feedback on if what I did seems decent or not.

**Comment by tmcconechy** [comment]
Maybe its my connection (but i think its ok). Or maybe something needs to be on thats not, but im not able to connect to your solution.

I think we could make some settings or example around these cases in the future, but you do have a workaround so thats good.

**Comment by mlick27** [comment]
That machine tends to reboot over the weekend, and I have to start the web server manually.  It's up now.

**Comment by tmcconechy** [comment]
This that looks how i would expect. Nice job on it. Recognize it was a workaround but we added that code for a reason.

You do have an issue that you can never bet to the button with the keyboard. But if your happy with this so am I.

Also you could add a bit more space between them so the focus state on the button doesnt show so close to the link.

Also might be some risk that something we change would stop this from working... But i think thats just the way it would have to be for this case.

**Comment by tmcconechy** [comment]
Going to close this as the support was resolved.
