### ISSUE TITLE
Column Layouts - do not really "belong" anywhere nor are referenced by IDS

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1332]
**Is your feature request related to a problem? Please describe.**
The "column" layout examples kind of live in no man's land with no real reference or documentation relating to IDS.

**Describe the solution you'd like**
Even though they are styles, they should probably be extracted to their own component or pattern.

**Describe alternatives you've considered**
Leaving them as-is.

**Additional context**
It could be nice to have it documented as well (hence my suggestion to make it a component) similar to the [IDS CSS responsive grid](https://design.infor.com/code/ids-css/latest/grid).

**Comment by tmcconechy** [comment]
I think this is what you are saying but what about just making a component called "layouts" and putting all these in there http://localhost:4000/layouts/list with a MD file.

We also have all these:
http://localhost:4000/examples/list
and
http://localhost:4000/patterns/list

I think examples can go under the related component(s).
patterns can maybe each be their own component?

At least that was a thought a while back that never got finished. These three things are somewhat hidden.

**Comment by clepore** [comment]
The only bad thing about one component called layouts is if we wrote an MD and talked about all of them, that'd be a very long page.

**Comment by tmcconechy** [comment]
Yeah, might have to break it out more. But was thinking that the scroll and n column examples are pretty similar and can be easily explained in a few sentences + some links to each one.

**Comment by clepore** [comment]
Yep, that's why I figured we'd break the column patterns out into their own separate component with their own documentation.

**Comment by tmcconechy** [comment]
Maybe

   Header Only -> goes in header
   Header Scroll -> goes in header
   Header Sticky -> goes in header
   Masonry -> goes in homepages
   Masthead Header Scroll -> goes in masthead
   Object Summary -> goes in forms
   Scrolling Canvas -> goes in new component ?scrolling layouts?
   Scrolling Contained Three Column -> goes in new component ?scrolling layouts?
   Scrolling Contained Two Column -> goes in new component ?scrolling layouts?
   Scrolling Contained -> goes in new component ?scrolling layouts?
   Scrolling Flex -> goes in new component ?scrolling layouts?
   Scrolling Longpage Sticky -> goes in new component ?scrolling layouts?
   Scrolling Longpage -> goes in new component ?scrolling layouts?
   Scrolling Single Column -> goes in new component ?scrolling layouts?
   Scrolling Three Column -> goes in new component ?scrolling layouts?
   Scrolling Two Column Left -> goes in new component ?scrolling layouts?
   Scrolling Two Column-> goes in new component ?scrolling layouts? 
   Three Column Fixed Both -> goes in new component ?3 column layouts?
   Three Column Fixed Left -> goes in new component ?3 column layouts?
   Three Column Fixed Right -> goes in new component ?3 column layouts?
   Three Column Fluid -> goes in new component ?3 column layouts?
   Two Column Fixed Left -> goes in new component ?2 column layouts?
   Two Column Fixed Lg -> goes in new component ?2 column layouts?
   Two Column Fixed Md -> goes in new component ?2 column layouts?
   Two Column Fixed Mm -> goes in new component ?2 column layouts?
   Two Column Fixed Percent -> goes in new component ?2 column layouts?
   Two Column Fixed Sm -> goes in new component ?2 column layouts?
   Two Column Fixed Xl -> goes in new component ?2 column layouts?
   Two Column Fixed -> goes in new component ?2 column layouts?
   Two Column Fluid Left -> goes in new component ?2 column layouts?
   Two Column Fluid -> goes in new component ?2 column layouts?
   Two Column Swaplist No Template -> goes in new component ?2 column layouts?

Totally an idea....Just spitballing.

**Comment by tmcconechy** [comment]
Descoping this issue for now
