### ISSUE TITLE
Input: Dirty Tracking does not trigger on Microsoft Edge and IE

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1335]
**Describe the bug**
Input: Dirty Tracking does not trigger on Microsoft Edge and IE.

**To Reproduce**
1. Open Edge and IE
2. Go to https://4130-rc0-enterprise.demo.design.infor.com/components/input/example-index.html
3. Type anything on Dirty Tracking field
4. See bug: Yellow dirty tracking indicator won't be displayed

**Expected behavior**
Dirty Tracking should display on Edge and IE

**Version**
v4.13.0-rc0

**Screenshots**
<img width="1021" alt="screen shot 2018-12-04 at 6 52 43 pm" src="https://user-images.githubusercontent.com/39508864/49437275-14eea600-f7f6-11e8-91dd-f840bcdf6d6e.png">

**Platform**
 - Microsfot Edge and IE

**Additional context**
No additional context.

**Comment by CindyMercadoReyes** [comment]
The issue is still occurring on Win 10 IE 11 and Edge 17. When I enter text in the dirty tracker and tab to the next field box the dirty tracker doesn't appear.

**Comment by tmcconechy** [comment]
The fix was pushed to master by mistake will be added back to 4.13-rc2 in the pending PR or you can verify on master as well.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
