### ISSUE TITLE
Multiselect: Color issue on Microsoft Edge

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1336]
**Describe the bug**
Multiselect: Color issue on Microsoft Edge.

**To Reproduce**
1. Open Microsoft Edge
2. Go to https://4130-rc0-enterprise.demo.design.infor.com/components/multiselect/example-index.html
3. Open the "States (Max 10)" dropdown
4. Notice that the checkbox is not visible when not hovered, and it has wrong color when hovered

**Expected behavior**
Checkbox color in Multiselect dropdowns should appear correctly.

**Version**
v4.13.0-rc0

**Screenshots**
<img width="784" alt="screen shot 2018-12-04 at 6 59 35 pm" src="https://user-images.githubusercontent.com/39508864/49437731-47e56980-f7f7-11e8-9157-c9bfce42531e.png">

**Platform**
 - Microsoft Edge

**Additional context**
Try also on different themes.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
