### ISSUE TITLE
Datepicker: Datepicker with range doesn't display on selected range when opened again. 

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1337]
**Describe the bug**
Datepicker: Datepicker with range doesn't display on selected range when opened again. .

**To Reproduce**
1. Go to https://4130-rc0-enterprise.demo.design.infor.com/components/datepicker/example-range.html
2. Open the "Range - No initial value" date picker
3. Select January 9, 2019 - January 12, 2019
4. Notice that the date picker will show the current month, not January 2019. You need to manually go to the selected range of dates.

**Expected behavior**
Date picker with Range should display on selected dates when opened again.

**Version**
v4.10.0 - v4.13.0

**Screenshots**
![range_notonselected](https://user-images.githubusercontent.com/39508864/49438404-3a30e380-f7f9-11e8-89d5-6cd2eaf0a0cd.gif)

**Platform**
 - All Devices, OS and Browsers

**Additional context**
Also encountered on all other Range date picker fields.

**Comment by brianjuan** [comment]
http://4130-rc1-enterprise.demo.design.infor.com/components/datepicker/example-range.html
Passed QA testing on all browsers, moving to Done.

**Comment by tmcconechy** [comment]
This issue was fixed on https://github.com/infor-design/enterprise/pull/2583 and confirmed in 4.13 just for good measure moving it to QA to retest based on the changes to the month/year picker. Please have a retest of this

**Comment by brianjuan** [comment]
https://4200-rc0-enterprise.demo.design.infor.com/components/datepicker/example-range.html
Still QA passed on all browsers. When the date picker field is opened again, it will display the selected range, not the current month.
