### ISSUE TITLE
Fileupload Advanced - Getting error when unbinding() and init() throws error

### ISSUE THREAD

**Issue by asui4tong** [infor-design/enterprise#1340]
**Describe the bug**

OP is seeing an error when chaining  like
```fileuploadadvanced.unbind().init()```

**To Reproduce**

When we use code like this: 
```
$('#divFileUpload').fileuploadadvanced( { send: sendFileToServer });
```
We got errors from sohoxi.js at function call  "fileuploadadvanced.updated()", in which there is this line of code:
```
**return this.unbind().init();**
```

**Expected behavior**
The `fileuploadadvanced.unbind()` function should have "**return this**" so it can be chained without an error.

**Version**
v4.12.1

**Screenshots**
n/a

**Platform**
all

**Additional context**
n/a

**Comment by tmcconechy** [comment]
Thanks, if you have the time, feel free to push a PR. Otherwise adding to next available sprint.

**Comment by clepore** [comment]
@asui4tong Thanks for your submission 👍

I updated your issue description to follow our template. It would be helpful if you follow all of the steps in the bug template or our `feature request` template for future submissions.

**Comment by tmcconechy** [comment]
Seems like to solve we just need a return this.

Here: https://github.com/infor-design/enterprise/blob/master/src/components/fileupload-advanced/fileupload-advanced.js#L572
And Here: https://github.com/infor-design/enterprise/blob/master/src/components/fileupload-advanced/fileupload-advanced.js#L72

**Comment by asui4tong** [comment]
Thank you! I will bookmark this one to serve as a template for future submissions.

**Comment by clepore** [comment]
When you click to create a new issue, it should ask you which template you want to use:

<img width="1022" alt="screen shot 2018-12-04 at 4 12 41 pm" src="https://user-images.githubusercontent.com/742319/49473234-7ce5c200-f7df-11e8-93c0-809e10518f9e.png">

Then you can follow the text we already have pre-filled in the description:

<img width="784" alt="screen shot 2018-12-04 at 4 13 57 pm" src="https://user-images.githubusercontent.com/742319/49473286-9f77db00-f7df-11e8-8a0e-52680b716527.png">

**Comment by asui4tong** [comment]
Hi Thea, what is the reason you assign this to me? It is a bug to be addressed. If you assign to me I am afraid no one will pick it up.

**Comment by tmcconechy** [comment]
I thought you were going to do a PR for this as you attempted it. If not no problem someone can pick it up.

**Comment by clepore** [comment]
@tmcconechy FYI - I'm going to backlog this issue for future planning due to lack of activity.

**Comment by tmcconechy** [comment]
Added this fix in finally. Just did it here https://github.com/infor-design/enterprise/pull/3561/files#diff-015738a5cd4ba96bc08c363e6d59161fR73
