### ISSUE TITLE
npm run build is not working on windows

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1348]
**Describe the bug**
After recent build changes on master we cannot build on windows for IDS.

**To Reproduce**
1. Open a windows VM
2. Make sure it has python + node 10
3. clone this project
4. npm install
5. npm run build

**Expected behavior**
No error

**Additional context**
Error seen is...

```
E:\infor\enterprise>npm run build

> ids-enterprise@4.14.0-dev build E:\infor\enterprise
> node ./scripts/build


=========   IDS Enterprise Builder   =========

⚠  No component arguments were provided.  A full component bundle will be created.

Running build processes...

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npx ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by EdwardCoyle** [comment]
Error log looks like:

![screen shot 2018-12-05 at 11 58 16 am](https://user-images.githubusercontent.com/3249601/49529916-15824d80-f885-11e8-8aa5-61bdd2ba01e2.png)

Most likely something to do with the args being passed to the child processes... bad syntax maybe?
