### ISSUE TITLE
Unable to paste into a bulleted list and pasting lists from word show smart characters

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1351]
**Describe the bug**
There are some issues pasting a simple bullet list from word.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index
2. At the bottom make a bullet list and add two bullets
3. Open the attached word document (in the zip)

4. Copy the bullet points
5. Pasts

**Expected behavior**
Smart dots should not be shown
If possible the list should continue , if not a second list can appear and it can be tweaked

**Version**
Any

**Screenshots**
See this video in the zip for more info if needed.
[Archive.zip](https://github.com/infor-design/enterprise/files/2650524/Archive.zip)

**Comment by janahintal** [comment]
QA Passed. Moving to Done
Tested in: http://localhost:4000/components/editor/example-index.html
