### ISSUE TITLE
Input:  the content cannot be selected on IE or Edge browser

### ISSUE THREAD

**Issue by zyhalj** [infor-design/enterprise#1354]
**Describe the bug**
On IE or Edge browser, the content of Input component cannot be selected. Chrome is OK。

**To Reproduce**
If Input component has tooltips, it will be set a class “logpress-target” and its attribute “-ms-user-select” is none. This class disable the selection on Input component. 

Once remove the tooltip, it can work.

**Expected behavior**
Tooltip is required to us, so please remove logpress-target class for Input component on IE and Edge.

**Version**

- ids-enterprise: v4.9.0 ~ v4.12.1

**Screenshots**
![capture](https://user-images.githubusercontent.com/13767418/49624385-2d380e00-fa0c-11e8-98dc-274012a83cd3.PNG)

**Platform**
 - Device (if applicable) PC or laptop.
 - OS Version: Windows 10
 - Browser Name IE11 and Edge
 - Browser Version  IE11 version11.1446.15063.0; Microsoft Edge 40.15063.674.0

**Additional context**
Tim has confirmed this bug:
Ok cool think we isolated it. We added some code so tooltips work on long press. They maybe don’t need to add this case on windows. So log a bug and I think we can correct this.

**Comment by tmcconechy** [comment]
This is done (forgot the smart tag). https://github.com/infor-design/enterprise/pull/1401

**Comment by janahintal** [comment]
QA Passed. Moving to Done.
Tested in : http://localhost:4000/components/input/test-tooltips.html & http://localhost:4000/components/tooltip/example-index.html for IE and Edge browser
