### ISSUE TITLE
Datagrid: selecting an item from a dropdown is generating a javascript error

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#1360]
The selectListItem function generates a javascript error when the user selects an item from the dropdown list.  The column containing the dropdown needs to have the editorOptions of showSelectAll of true and closeOnSelect of true.

Within selectListItem, when this.settings.closeOnSelect is true, the function this.closeList is called. CloseList will set this.list = null.  Later within selectListItem, have an if statement that when  this.settings.showSelectAll is true, it references this.list.find('.dropdown-select-all-list-item'), but this.list has been set to null.

Current code snippet:
selectListItem: function selectListItem(target) {
      var ddOption = target.closest('li');

... (large chuck of code not shown)

      if (this.settings.closeOnSelect) {
        this.closeList('select');
      }

      if (this.isMobile()) {
        return true; //eslint-disable-line
      }

      this.activate(!this.settings.closeOnSelect);

      // Check/uncheck select all depending on no. of selected items
      if (this.settings.showSelectAll) {
        var opts = this.element.find('option');
        var selectedOpts = opts.filter(':selected');

        if (opts.length > selectedOpts.length) {
          this.list.find('.dropdown-select-all-list-item').removeClass('is-selected');
        } else {
          this.list.find('.dropdown-select-all-list-item').addClass('is-selected');
        }
      }

      return true; //eslint-disable-line

Suggested code snippet:
selectListItem: function selectListItem(target) {
      var ddOption = target.closest('li');

... (large chuck of code not shown)

      if (this.settings.closeOnSelect) {
        this.closeList('select');
      }

      if (this.isMobile()) {
        return true; //eslint-disable-line
      }

      this.activate(!this.settings.closeOnSelect);

      // Check/uncheck select all depending on no. of selected items
      if (this.settings.showSelectAll && !this.settings.closeOnSelect) {
        var opts = this.element.find('option');
        var selectedOpts = opts.filter(':selected');

        if (opts.length > selectedOpts.length) {
          this.list.find('.dropdown-select-all-list-item').removeClass('is-selected');
        } else {
          this.list.find('.dropdown-select-all-list-item').addClass('is-selected');
        }
      }

      return true; //eslint-disable-line
    },

The javascript error is causing serious issues in Landmark.

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/49668868-15b94f00-fa25-11e8-85df-c535e5de4179.png)

**Comment by claudenbach** [comment]
![git-1360](https://user-images.githubusercontent.com/39804038/49668990-76e12280-fa25-11e8-9a5e-a00cee5c5091.gif)

**Comment by tmcconechy** [comment]
Do we have a way to reproduce this on the sample projects(s). 

Is it showSelectAll on datagrid or dropdown ?

Seems like dropdown from the code snippet you suggested but based on `showSelectAll= true` and `closeOnSelect = true` i think we want a multiselect editor / formatter but there doesn't seem to be one at the moment. From the screen shots I'm not certain if u are expecting a multiselect editor or not so maybe showSelectAll= true just shouldnt be set here?

Not certain yet how to approach this one yet.

**Comment by claudenbach** [comment]
Setting the showSelectAll on a datagrid column containing a dropdown.  The column's filterType is 'multiselect'.

I can try to produce a sample that illustrates the issue.

**Comment by tmcconechy** [comment]
OK, I see - your using the select all for the header filter. I think because the editor is a regular dropdown with no select all its throwing this error. Workaround would of course be to not use showSelectAll.

Did this work at any point?

**Comment by claudenbach** [comment]
I'm not sure.  Maria added the use of the showSelectAll with her work on the header filter.

**Comment by brianjuan** [comment]
https://4140-beta0-enterprise.demo.design.infor.com/components/datagrid/test-filter-selectall.html
https://4140-beta0-enterprise.demo.design.infor.com/components/dropdown/example-index.html
Passed QA testing on all browsers.

**Comment by tmcconechy** [comment]
Failing due to the fact that a fix was reverted here - the last item in the dropdown is now hidden. 
http://localhost:4000/components/datagrid/example-editable.html

**Comment by brianjuan** [comment]
Moving this to Done, issue on http://localhost:4000/components/datagrid/example-editable.html is now fixed on all browsers.
