### ISSUE TITLE
Tree- Additions to component from Approva

### ISSUE THREAD

**Issue by mdevale** [infor-design/enterprise#1364]
**Is your feature request related to a problem? Please describe.**
Problems in tree control:
1. Not able to insert dropdown with dynamic options in the tree node.
2. There is no provision to insert new node in between the nodes.
3. Hide check box for specific node. Currently tree control showing checkbox for all node. 
4. We need empty icon for some node. Currently tree control showing default document icon for leaf node.
5. Node gets selected on expand and collapse node.

**Additional context**
Please check below JT also 
https://jira.infor.com/browse/UXD-4

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done folder
