### ISSUE TITLE
Tabs Control: Support for re-ordering of tabs

### ISSUE THREAD

**Issue by rvaja-infor** [infor-design/enterprise#1366]
We are currently writing a designer based web application to replace its desktop equivalent, and the application requires tabs to be re-ordered. At the moment re-ordering is done via a dialog box, which we have considered to go with, but believe it would be much nicer to do this by dragging and dropping.

What we would like to see is for the Tabs control to have a feature built in that would allow the re-ordering of tabs suing drag and drop. This feature would only be turned on by the use of a flag, which would be defaulted to 'false'.

**Comment by tmcconechy** [comment]
Is this for normal, module or vertical tabs? Assume module as that would make the most sense.

**Comment by rvaja-infor** [comment]
This is form normal, but think it would be nice across all of them

**Comment by tmcconechy** [comment]
Or maybe just normal + module. I know module was also requested

**Comment by tmcconechy** [comment]
consolidating  this with a second request for this https://github.com/infor-design/enterprise/issues/4520
