### ISSUE TITLE
Data grid docs contain duplicate `.html` extension

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#1373]
**Describe the bug**
The `slug`s in `datagrid/readme.md` contains `.html` extensions when it shouldn't. This causes duplicate `.html.html` links to render on the website. This causes broken links to the Github pages.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/datagrid
2. Click on one of the Github icon links in "More Examples"

**Expected behavior**
We're generally defining `slug` without an extension and then append it when necessary. This should be consistent across all doc readmes.

**Version**
- ids-enterprise: 4.13.0

**Screenshots**
![image](https://user-images.githubusercontent.com/1012017/49806290-59fa6700-fd25-11e8-970e-4db784c7b1df.png)

**Comment by tmcconechy** [comment]
Fixed and deployed
