### ISSUE TITLE
Documentation deploy sometimes fails to generate API data

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#1377]
**Describe the bug**
When attempting to deploy the docs for `4.13.0`, I tried several times to deploy the docs. They never had errors but most times failed to generate the `api` object so none of the JSDocs data was available on the website.

**To Reproduce**
1. Run 1. `npm run documentation -- --dry-run --test-mode --site=prod`
2. In some cases (maybe this only happens on my machine?) the API docs aren't generated so the `api` property in the `docs/ids-website/dist/docs/component.json` is empty 
    - i.e.`docs/ids-website/dist/docs/button.json`

**Expected behavior**
Should work every time.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
