### ISSUE TITLE
Contextual Action Panel: Toolbar Layout Issues

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1378]
**Describe the bug**
Some CAP examples/tests using the standard Toolbar component aren't rendering the toolbars correctly, causing a problem where buttons overlap:

![screen shot 2018-12-11 at 4 37 00 pm](https://user-images.githubusercontent.com/3249601/49831919-30f8c700-fd63-11e8-804f-927de8da677e.png)

**To Reproduce**
1. Go to http://localhost:4000/components/contextualactionpanel/test-full-content.html
2. Click on 'Show Contextual Action Panel" to open the CAP
3. See the Toolbar's buttons are overlapping on the right:

![screen shot 2018-12-11 at 4 38 08 pm](https://user-images.githubusercontent.com/3249601/49831920-30f8c700-fd63-11e8-8c8f-dd57cb68b645.png)

**Expected behavior**
The Toolbar should display all its elements properly.

**Version**
- 4.13.x

**Platform**
 - n/a

**Comment by tmcconechy** [comment]
Also somewhat related i tried to update includes/header to use the flex toolbar but i could not get that to work. The icons would become dark and the text was not aligned.

**Comment by tmcconechy** [comment]
This issue was fixed along the way and can no longer be reproduced on 4.26
