### ISSUE TITLE
Modal: rework Contextual Action Panel integration

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1379]
**Is your feature request related to a problem? Please describe.**
The integration between Modals, Contextual Action Panels, and related components need some refactoring.  In their current states, it's cumbersome to do maintenance on these components.  Since their original forms have been built, the use cases for all of the components have been fleshed out and better described, and the foundational code we wrote to support them has had many things added, without a solid core being defined.

**Key Components** 
- [modal.js](https://github.com/infor-design/enterprise/blob/4.13.x/src/components/modal/modal.js)
- [modal.jquery.js](https://github.com/infor-design/enterprise/blob/4.13.x/src/components/modal/modal.jquery.js)
- [contextualactionpanel.js](https://github.com/infor-design/enterprise/blob/4.13.x/src/components/contextualactionpanel/contextualactionpanel.js)
- [contextualactionpanel.jquery.js](https://github.com/infor-design/enterprise/blob/4.13.x/src/components/contextualactionpanel/contextualactionpanel.jquery.js)

**Describe the solution you'd like**
Some goals are:
- [ ] Reduce spaghetti lifecycle/build logic
- [ ] Remove all settings logic from the jQuery portion of the Modal component, and into its prototype, making the jQuery component wrapper simple like the majority of other components.
- [ ] Make the Modal a better foundational component that can be used as a platform for others:
  - The "Modal" part should only do the following:
    - Become a streamlined, empty component only comprised of the empty window and its overlay by default.
    - Become agnostic of its content, and have no content by default.  It should be possible to load any content inside.
    - Be the main source of lifecycle events (build, events, teardown/destroy)
    - Provide a way to return the results of an internal form via a callback once its closed
   - About/Contextual Action Panel/Message Components
     - Be reworked to use the new platform for loading their own content/form elements
     - Contextual Action Panel should no longer be responsible for lifecycle events in any way, delegating those responsibilities to the Modal.
 - [ ] Modal Buttonset should become its own separate component.

**Describe alternatives you've considered**
We should thoroughly discuss alternatives to this, because it's potentially a large breaking change.  It also has the potential to make the Modal much more useful, reduce code, and improve maintenance times on all involved components.

**Comment by tmcconechy** [comment]
Descoping this for now - but this should be considered on the new project (but will probably just naturally be fixed)
