### ISSUE TITLE
Spinbox: Fix field sizes on mobile

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1384]
Originally reported by @tmcconechy [in this comment](https://github.com/infor-design/enterprise/pull/1362#issuecomment-446269944).  When placing two Spinbox fields side-by-side in a mobile layout, they should not be wider than a single input field.  

**Describe the solution you'd like**
The CSS for the Spinbox and standard input field should be modified to match well on a mobile layout. 

As of `v4.13.x`, This is what http://master-enterprise.demo.design.infor.com/components/form/test-spinbox-compound-field.html currently looks like on iOS:

<img width="256" alt="screen shot 2018-12-12 at 11 40 17 am" src="https://user-images.githubusercontent.com/3249601/49884376-b8e1de00-fe02-11e8-9320-c3217c8f8f63.png">

**Comment by tmcconechy** [comment]
Just a note but i think its the input sizes not the spinbox sizes? They line up so there is 20px on each size but the input is smaller.

**Comment by EdwardCoyle** [comment]
Specced this issue out a bit further [in this comment](https://github.com/infor-design/enterprise/pull/3044#issuecomment-547458890)

**Comment by jbrcna** [comment]
QA **FAILED**

Verified in http://4240-beta0-enterprise.demo.design.infor.com/components/spinbox/example-sizes.html

![image](https://user-images.githubusercontent.com/56722184/70689699-e69c8400-1cef-11ea-8b10-76de40ae7219.png)

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. 
Verified in http://4240-rc0-enterprise.demo.design.infor.com/components/spinbox/example-sizes.html?theme=uplift&variant=light across all platform.
