### ISSUE TITLE
Datagrid Editable Component: Tab key for Action column triggers the search field box to open and close

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1394]
**Describe the bug**
Datagrid Editable Component: Tab key for Action column triggers the search field box to open and close

**To Reproduce**
1. Go to url: https://4140-beta0-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. On FF 63 or FF 64 open the page - desktop size not mobile
3. Click on shipped and open the drop down
4. Arrow down twice - arrow up twice
5. Hit tab
6. When the user clicks on the tab key the search field box opens and closes quickly

**Expected behavior**
When the tab key is selected to close the dropdown list box this should not trigger the search field box to open and close quickly

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
None

**Platform**
 - OS Version: [ iOS 8]
 - Browser Name [FF 63 FF 64]

**Additional context**
None

**Comment by tmcconechy** [comment]
Noting that i saw this on BS on FF 63 but not on 64. So i think its probably not worth fixing.

**Comment by tmcconechy** [comment]
Closing this as doesnt seem like i can do anything with it
