### ISSUE TITLE
Datagrid Editable Component: Blank Tooltip appearing when you hover over the checkbox header

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1395]
**Describe the bug**
Datagrid Editable Component: Blank Tooltip appearing when you hover over the checkbox header

**To Reproduce**
1. Load page refresh
Go to url: https://4140-beta0-enterprise.demo.design.infor.com/components/datagrid/example-editable.html#
2.blank out one activity cell so an error occurs
3. now hover the rowid header column
4. now hover the checkbox header column
5. A blank tooltip appear

**Expected behavior**
No tooltip should appear

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
None

**Platform**
 - OS Version: [iOS 8]
 - Browser Name [e.g. Chrome,FF]

**Additional context**
None

**Comment by brianjuan** [comment]
https://4140-rc0-enterprise.demo.design.infor.com/components/datagrid/example-editable
Passed QA testing on all browsers. moving to Done.
