### ISSUE TITLE
Datagrid dropdown window resize component: Tooltip appearing on mobile

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1396]
**Describe the bug**
Datagrid dropdown window resize component: Tooltip appearing on mobile

**To Reproduce**
1. On mobile go to url: https://4140-beta0-enterprise.demo.design.infor.com/components/datagrid/test-dropdown-window-size.html
2. Click on the "Cheap" dropdown list box
3. A tooltip appears with the textt "Cheap"

This ticket is related to ticket: https://github.com/infor-design/enterprise/issues/1298
**Expected behavior**
A tooltip should not appear

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![bs_realdroid_mobile_samsung galaxy s9 plus-8 0-1440x2960 1](https://user-images.githubusercontent.com/39101346/49964093-a7263680-fee7-11e8-94e6-68257a16045f.jpg)
![bs_realios_mobile_iphone x-11 0](https://user-images.githubusercontent.com/39101346/49964095-a7263680-fee7-11e8-87c6-9d47c64018fb.jpg)

**Platform**
 - Device (if applicable) [e.g. iPhone X]

**Additional context**
None

**Comment by janahintal** [comment]
QA Passed. Moving to Done. 
Tested in: http://4140-rc0-enterprise.demo.design.infor.com/components/datagrid/test-dropdown-window-size.html
