### ISSUE TITLE
Datagrid with paging: Applying filter on multiple columns does not work

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1405]
**Describe the bug**
Datagrid with paging: Applying filter on multiple columns does not work

**To Reproduce**
1. Go to : https://4140-beta0-enterprise.demo.design.infor.com/components/datagrid/example-paging.html
2. Add filter on Product Name > Contains '50'
3. Add filter on different column > Quantity > equals '26'
4. Filter doesn't work

**Expected behavior**
Will be able to filter all Product Name that Contains '50' and has Quantity equals '26'

**Version**

- ids-enterprise: [v4.7.0 or v4.14.0]

**Screenshots**
<img width="1665" alt="screen shot 2018-12-17 at 5 13 57 pm" src="https://user-images.githubusercontent.com/45757016/50077455-6b5cdb00-021f-11e9-95c5-39bc85932b49.png">

**Platform**
All devices, OS and Browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Calling this minor as this is just a demo app / example issue since our backend test server doesn't handle this. Would have to update compressors.js to work, but this isnt crucial.

https://4140-beta0-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side.html  will work.

**Comment by tmcconechy** [comment]
Descoping this demo app issue for now. Not worth fixing.
