### ISSUE TITLE
Swaplist search 'Shift + M' doesn't allow uppercase M to be typed on search bar

### ISSUE THREAD

**Issue by kcinco** [infor-design/enterprise#1408]
**Describe the bug**
When attempting to type an uppercase M via "Shift + M" in the Swaplist search field the letter wouldn't appear on the field. This seems to be only isolated to the letter M, all other letters when made uppercase this way gets typed in.

Exists in this sample: https://design.infor.com/code/ids-enterprise/latest/demo/components/swaplist/example-search?font=source-sans

**To Reproduce**
1. Go to a search enabled Swaplist
2. type "Shift + M"
3. uppercase M not typed in 

**Expected behavior**
An uppercase M should appear.

**Comment by tmcconechy** [comment]
This is not showing on https://design.infor.com/code/ids-enterprise/latest/demo/components/searchfield/example-index.html (just a note). Seems like just swaplist.

**Comment by tmcconechy** [comment]
For who fixes this. Seems like the issue is around here https://github.com/infor-design/enterprise/blob/master/src/components/swaplist/swaplist.js#L917 Shift+M is the shortcut key for selecting with keyboard. But this should be ignored if the search input is focused.

**Comment by janahintal** [comment]
QA passed.
Tested in : https://4150-beta0-enterprise.demo.design.infor.com/components/swaplist/example-search?font=source-sans
for all OS and browsers
