### ISSUE TITLE
Datagrid column width error when filtering after resize

### ISSUE THREAD

**Issue by chrisfried** [infor-design/enterprise#1411]
**Describe the bug**
Resizing a column then immediately applying a column level filter results in a formatting error

**To Reproduce**
1. Go to https://4140-beta0-enterprise.demo.design.infor.com/components/datagrid/test-tree-filter.html
3. Increase the size of the Task column.
3. Click on the Task column filter
4. Type 'hmm'
5. Press Enter.

**Expected behavior**
Column formatting should remain resized.

**Version**
- ids-enterprise: 4.14.0-beta.0

**Screenshots**
![resizefilter](https://user-images.githubusercontent.com/422381/50098881-0cc13e00-01da-11e9-91cf-6ce254a14442.png)

**Platform**
 - Windows 10
 - Chrome
 - Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Not seeing this one on my end. Does it matter how big the screen is?

**Comment by chrisfried** [comment]
... Reproduced three times in a row before hitting submit. Now I can't reproduce.

**Comment by tmcconechy** [comment]
Hmm wondering if there is another step like sizing a different column.

**Comment by chrisfried** [comment]
Now it's reproducing approximately every other refresh.

**Comment by chrisfried** [comment]
And then ten in a row where I can't reproduce.

**Comment by tmcconechy** [comment]
Havent quite seen it yet.

**Comment by clepore** [comment]
Revised steps:
1. Click to drag the first column larger, but while doing that, have the mouse go down over the cells.
2. Once it's large, let go.
3. Sort by a column.

See this zipped mov file:
[columns-misalign.mov.zip](https://github.com/infor-design/enterprise/files/2818519/columns-misalign.mov.zip)

**Comment by tmcconechy** [comment]
Fixed this while working on the resize for #464 will push with it.
