### ISSUE TITLE
Datagrid: Toolbar keywordFilter does not work with tree grid

### ISSUE THREAD

**Issue by chrisfried** [infor-design/enterprise#1412]
**Describe the bug**
Column filters were adjusted to display matching child elements in the tree grid, but the toolbar filter was not. (Maybe this is actually a feature request for toolbar filter rather than a bug?)

**To Reproduce**
1. I added `keywordFilter: true` to the toolbar settings in test-tree-filter to reproduce.
2. Type 'hmm' in the column filter
3. Refresh and type 'hmm' in the toolbar filter
4. Compare

**Expected behavior**
The rows that appear in the column filter should all appear in the toolbar filter

**Version**

- ids-enterprise: 4.14.0-dev

**Screenshots**
Column filter:
![columnfilter](https://user-images.githubusercontent.com/422381/50099727-0a5fe380-01dc-11e9-84fe-cc2a06cebe55.png)

Toolbar filter:
![toolbarfilter](https://user-images.githubusercontent.com/422381/50099731-0c29a700-01dc-11e9-95fe-94002c9db6db.png)

**Platform**
 - Surface Book
 - Windows 10
 - Chrome
 - Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Yeah i think we didnt ever implement the datagrid + tree + keyword filter.

**Comment by tmcconechy** [comment]
This is pretty old @chrisfried is this still useful to you or should we close?

**Comment by AnaLauraMartinez** [comment]
We still have this requirement.

**Comment by tmcconechy** [comment]
Descoping this issue for now. Simply no time for it but for 5.x we can reconsider.
