### ISSUE TITLE
Rich Text Editor: Disabled state shouldn't interfere with RTE internal content styling

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#1413]
**Describe the bug**
When the editor control is set to disabled, a border is displayed and the height of the control is maintained regardless of content.

**To Reproduce**
1. Extract and run the attached test-editor-states.html

**Expected behavior**
Would like to see no border and the control vertically size to the content.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]
v4.13.0

**Screenshots**

Currently:
![image](https://user-images.githubusercontent.com/20212079/50101358-223d6480-01e8-11e9-9e11-8b1aeb714442.png)

Expectation:
![image](https://user-images.githubusercontent.com/20212079/50101579-9b3cbc00-01e8-11e9-942d-7f58d39b9305.png)

[test-editor-states.zip](https://github.com/infor-design/enterprise/files/2686997/test-editor-states.zip)

**Platform**

**Additional context**
An additional setting to indicate to not set the border and vertically size the content would be acceptable so as to maintain backward compatibility.

**Comment by tmcconechy** [comment]
I moved the item in the milestone down? Assuming its not top priority. But the way we treat this is to have the readonly and disabled styling as the same as fields. Do we need a new readonly mode that has no borders and back color? (Html Readonly view)

**Comment by fitzorama** [comment]
You're correct, the content should not appear disabled.

For Landmark, a 'display as text' displays the value as text without any control and a 'display only' displays the value with the control set to readOnly. So perhaps a new state for the editor is needed.

**Comment by lipetzan** [comment]
https://us-api.asm.skype.com/v1/objects/0-cus-d7-48c65bcea646c09df6cf0c5a70f2316d/views/imgo

**Comment by lipetzan** [comment]
![2019-01-14_143913](https://user-images.githubusercontent.com/42155063/51139695-3174f980-180a-11e9-8b9f-a73c0846b87f.png)

We've got some forms that will look pretty bad without this enhancement.

**Comment by clepore** [comment]
We're going to keep the disabled and readonly states matching the input styles. Please use custom CSS/JS to target this fix.

**Comment by lipetzan** [comment]
So the SoHo Xi design is to have a border around Rich Text fields at all times, in all states, value entered or not?  Is that how to interpret this closure?  And if so, we wouldn't want to override the design I'm thinking.  

It also seems that in disabled and readonly statues that the font style is changed to a lighter gray, from the standard editable black.  This could be an issue in a Rich Text as users might infer that they'd changed the color and style.

**Comment by fitzorama** [comment]
An example of what @lipetzan has indicated about the color change when the control is in either the readOnly or displayOnly state. Content that is default color formatted displays as a disabled grey.

![image](https://user-images.githubusercontent.com/20212079/52012205-97ff4600-249f-11e9-83c6-50a67b37ce47.png)

**Comment by clepore** [comment]
Okay, yeah removing the border is a design aesthetic thing, so that would be something we wouldn't change (why we closed the ticket).

However, seeing your other concerns, it seems the request is to be able to lock the RTE into "preview mode" so that it renders everything as it should, versus changing the "disabled state" styles for Enterprise?

**Comment by tmcconechy** [comment]
The problem with that @nickwynja is that the editor does have some built in styling and ways of rendering stuff that may not work in a div without replicating it or adding some different classes on top. For example the block quote, links and font ect.

**Comment by clepore** [comment]
I was thinking about that. The solution might not be to "lock" the RTE in preview mode (as this is probably hackable anyway), but to extract those `.editor` styles into a generic class altogether, that can go on the editor element AND any other element, like a `div` or `p` for static rendering of the context w/o having a "disabled" editor.

**Comment by tmcconechy** [comment]
Possibly - but also content editable does some rendering on its own. So might have to see how close that looks. It does a lot of inline styles and stuff. I.E. Sounds like might be lot more work.

**Comment by nickwynja** [comment]
That may "work" but then you're setting yourself up for unexpected changes when you want to change the styles for something strictly in the editor. Then you have `<div class="editor">`s hanging around in the wild which aren't what you want to target and no real way to fix it.

**Comment by tmcconechy** [comment]
For clarity the ask is to make a new preview mode - the mode should:

- be invoked by option `preview: true`
- add an api option to toggle the preview mode fx `preview()` and `editable()` or `readonly()
- the style of the mode should show the html exactly like its in the editor 
- nothing should show disabled or readonly style
- no borders or toolbar
- inherit background
- should not be able to type in

**Comment by janahintal** [comment]
QA Passed. Will move to Done
Validated in: http://localhost:4000/components/editor/example-preview.html across all Browsers.

**Comment by CindyMercadoReyes** [comment]
On Win 7 IE 11 the color palette doesn't open. Please see screen shot attached. 
![bs_win7_ie_11 0](https://user-images.githubusercontent.com/39101346/53346008-22429a80-38e4-11e9-82cf-a32e25cb0e3d.jpg)

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks!
Color palette is now working in Win 7 IE 11. 

Tested in : https://4160-rc0-enterprise.demo.design.infor.com/components/editor/example-preview.html
