### ISSUE TITLE
About Component display IDS Version in device specs area with apps version

### ISSUE THREAD

**Issue by danders1717** [infor-design/enterprise#1414]
**Describe the bug**
If include the device specs, the version being passed in is displaying for the IDS Version as well in the About component. Should display the IDS Version instead.

**To Reproduce**

1. edit app/views/components/about/example-index.html to 
```
    //Show About Screen
    $('body').about({
      appName: 'IDS Enterprise',
      productName: 'Controls',
      version: 'Example Application Version No. XX',
      content: '<p>Fashionable components for fashionable applications.</p>'
    });
```
2. open http://localhost:4000/components/about/example-index.html
3. should show bothe the app version on the top and the current ids version on the bottom

If include the device specs, the version being passed in is displaying for the IDS Version as well in the About component.  Should display the IDS Version instead.
**Expected behavior**
Should be able to show both a custom app version AND the Ids version.

**Version**
- 4.14-rc0

**Platform**
- Any

**Additional context**
Mentioned on MS Teams.

Overlooked on https://github.com/infor-design/enterprise/pull/913

**Comment by brianjuan** [comment]
http://localhost:4000/components/about/example-index.html
Passed QA testing on localhost and master, will do a retest once 4.15.0 build is provided.
