### ISSUE TITLE
Datagrid: There is a white background when editing a cell in High Contrast theme

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1421]
**Describe the bug**
Datagrid: There is a white background when editing a cell in High Contrast theme.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-editable.html
2. Change the theme to High Contrast 
3. Type "test edit" in the Activity column of the first row
4. Notice that there is an inappropriate white background while editing

**Expected behavior**
Inappropriate background color should not be displayed when editing a cell in datagrid.

**Version**
- ids-enterprise: v4.6.0 - v.4.14.0

**Screenshots**
<img width="839" alt="screen shot 2018-12-18 at 7 21 18 pm" src="https://user-images.githubusercontent.com/39508864/50150872-42f5df00-02fa-11e9-8204-a4ce1f27cfc9.png">

**Platform**
 - All OS, devices and browsers

**Additional context**
No additional context.

**Comment by janahintal** [comment]
QA Passed. 
Tested in https://4150-beta0-enterprise.demo.design.infor.com/components/datagrid/example-editable.html across all browser, OS and devices.
