### ISSUE TITLE
Datagrid Tree - Make Filtered child rows a setting

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1422]
**Describe the bug**
As a continuation on #1281 

**To Reproduce**
Behavior number 2 still happens when you apply filter that match the parent node. Expand/collapse button is displayed but doesn't do anything.
Steps:

- Go to https://4140-beta0-enterprise.demo.design.infor.com/components/datagrid/test-tree-filter.html
- Apply Contains filter on Task column with the word "HMM"
- Try to Expand/Collapse the first row, nothing happens.

**Expected behavior**
Make this behavior a setting.

Add this as api settings allowChildExpandOnMatch: boolean

allowChildExpandOnMatch === true

- if only parent got match then add children nodes too
- if one or more child node got match then add parent node and all the children nodes
allowChildExpandOnMatch === false

- if only parent got match then (disable|hide|anything-else) +/- button and no add children nodes
- if one or more child node got match then add parent node and only matching children nodes (as it doing now)

**Additional context**
#1281

**Comment by tmcconechy** [comment]
Added to the sprint as Deepak is done with all the issues (except https://github.com/infor-design/enterprise-ng/issues/206 which may not be possible) and he was working on fixing this.

**Comment by janahintal** [comment]
QA Passed. 
Tested in: http://localhost:4000/components/datagrid/test-tree-filter-child-on-match.html
