### ISSUE TITLE
Swaplist - Cannot drag more than once on IOS

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1423]
**Describe the bug**
As a continuation of #1195 making a new issue

**To Reproduce**
1. ON ios x
2. Go to latest swaplist example
3. Select multiple items in one of the lists and drag them over in a fast manner to the next one.
Items will disappear from the ui
4. Try again (this doesnt work)

**Expected behavior**
Should be able to drag more than once on IOS

**Version**
- v4.14.x

**Platform**
 - IOS

**Additional context**
#1195

**Comment by brianjuan** [comment]
I also encountered this on Android and other iOS phones.

**Comment by tmcconechy** [comment]
@deep7102 Do you have any suggestions for @tmcastro tmcastro here?

**Comment by tmcastro** [comment]
Hey guys, the issue I have here is that the click event is being triggered by the placeholder which has already been removed from the dom. Also, when I try to click on a dragged item and hold on to it for a few secs, it becomes ok again. I'm having trouble finding the code that made it ok again.

**Comment by tmcastro** [comment]
Hi Chris, we were asked to reassign all remain IDS tickets to you while we work on other projects. Thanks

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.  Moving this ticket to Done column.
