### ISSUE TITLE
Multiselect Dropdown: Layout issue on arrow down icon when dropdown values are longer than the dropdown width

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1426]
**Describe the bug**
Multiselect Dropdown: Layout issue on arrow down icon when dropdown values are longer than the dropdown width.

**To Reproduce**
1. Go to http://4140-rc0-enterprise.demo.design.infor.com/components/multiselect/example-index.html on any browsers except Chrome
2. Open the "States (Max 10)" dropdown
3. Select/check 10 items
4. See layout issue on arrow down icon

**Expected behavior**
Layout should appear correctly, showing ellipsis text like in chrome

**Version**
- ids-enterprise: v4.14.0-rc0

**Screenshots**
<img width="724" alt="screen shot 2018-12-19 at 3 24 27 pm" src="https://user-images.githubusercontent.com/39508864/50205318-b18e7780-03a2-11e9-8069-130f184e0ac8.png">

**Platform**
 - Mac Safari, Mac FF, Windows IE, Windows Edge, Windows FF, All iOS browsers, Android FF

**Additional context**
No additional context.

**Comment by clepore** [comment]
It works on 4.13.0, so regression for sure:
<img width="338" alt="screen shot 2019-01-03 at 10 44 11 am" src="https://user-images.githubusercontent.com/742319/50646632-9136ef00-0f44-11e9-9a2b-05c224e27883.png">

**Comment by deep7102** [comment]
This issue is now fixed with another issue.
https://master-enterprise.demo.design.infor.com/components/multiselect/example-index.html

**Comment by brianjuan** [comment]
Verified fixed on http://master-enterprise.demo.design.infor.com/components/multiselect/example-index.html, will retest once beta build for 4.19.0 is deployed. Moving to Done.
