### ISSUE TITLE
Application Menu: List-Item style accordion headers are not displayed correctly

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1429]
**Describe the bug**
Application Menu: Sub menu is not showing in Android devices 

**To Reproduce**
1. Go to : http://4140-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html OR http://4140-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-menubutton.html
2. Click on 'My Roles'
3. Click on  sub menu '+ Role # 1'
4. See error : sub menu are not showing unless clicked.

**Expected behavior**
sub menu should appear

**Version**

- ids-enterprise: [v4.13.0 or v4.14.0]

**Screenshots**
<img width="544" alt="screen shot 2018-12-20 at 3 57 20 pm" src="https://user-images.githubusercontent.com/45757016/50273202-f551b180-0474-11e9-9bde-317fcf33f2c9.png">

**Platform**
- Android Devices : All browsers e.g Chrome or Firefox

**Additional context**
No additional context

**Comment by tmcconechy** [comment]
@EdwardCoyle can you test out if this is maybe a regression we should handle for 4.14?

**Comment by tmcconechy** [comment]
Can still reproduce on 4.25 - maybe we should look at this one.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you! :) 
![image](https://user-images.githubusercontent.com/45757016/79979341-f5801800-84d3-11ea-9d71-b3c31d884256.png)
