### ISSUE TITLE
Tree: Unable to drag nodes on sortable tree using mobile browsers

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1437]
**Describe the bug**
Tree: Unable to drag nodes on sortable tree using mobile browsers

**To Reproduce**
1. Go to http://localhost:4000/components/tree/example-sortable.html on Android and iOS devices
2. Try to drag nodes to other nodes

**Expected behavior**
On mobile, nodes should be draggable when tree is configured as sortable

**Version**
- ids-enterprise: v4.7.0 - v.4.14.0-rc0

**Screenshots**
No screenshots applicable.

**Platform**
 - All mobile browsers

**Additional context**
On iOS devices, parent nodes cannot also be expanded/collapsed

**Comment by tmcconechy** [comment]
This may not ever be possible to sort nodes on a mobile device. We can consider but likely going to be a limitation.

**Comment by tmcconechy** [comment]
Descoping this issue for now
