### ISSUE TITLE
Datagrid: Comment column is not responsive on smaller/mobile screen

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1438]
**Describe the bug**
Datagrid: Comment column is not responsive on smaller/mobile screen.

**To Reproduce**
1. Go to https://4140-rc0-enterprise.demo.design.infor.com/components/datagrid/example-comments.html
2. Resize the browser to smaller size or open the URL in iPhone X and Galaxy S9
3. See issue: Comment column is not responsive, making the content unreadable

**Expected behavior**
Comment column should be responsive on smaller/mobile screen

**Version**
- ids-enterprise: v4.7.0 - v4.14.0-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/50341177-d62c5000-0558-11e9-9295-5522e2b3d951.png)

**Platform**
 - All Mobile browsers
 - All Desktop browsers (adjust to smaller screen) 

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This might be fixable when adding https://github.com/infor-design/enterprise/issues/459 as of now this page is not responsive because the last column is a text field with percent width by configuration.

**Comment by brianjuan** [comment]
The issue is also encountered on http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/example-expandable-cells.html#
And on iPhone XR, iPhone XS and iPhone XS Max, Datagrid contents disappear when you expand the expandable cells.

**Comment by tmcconechy** [comment]
Descoping this issue for now
