### ISSUE TITLE
Tabs: Add New Button is misplaced after init and destroy

### ISSUE THREAD

**Issue by shilpa-domakonda** [infor-design/enterprise#1439]
**Describe the bug**
The add tab button is not deleted even after destroying the object. The duplicate + is shown when we initialize the object again. Please check below for reference.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs/example-add-tab-button.html'
2. Open the google dev console for this example page and execute the below steps as shown in the attached screenshot(Google Dev Console) which are:
```
var settings = $('#add-capable-tabs').settings;
$('#add-capable-tabs').data('tabs').destroy();
$('#add-capable-tabs').tabs(settings);
```
3. You will observe a new '+' is added to the tab panel in the UI example page.
4. See the attached screenshot(New + Button Added)

**Screen Shots**
<img width="887" alt="new button added" src="https://user-images.githubusercontent.com/46045638/50341431-a4929500-0516-11e9-9d46-bb64e2343567.PNG">
<img width="955" alt="google dev console" src="https://user-images.githubusercontent.com/46045638/50341440-b2481a80-0516-11e9-8e42-237698036407.PNG">

**Expected behavior**
There should not be the duplicate + button as shown in the screenshot.

**Version**

-Observed in 4.11.0 and the latest versions

**Screenshots**

**Platform**
 - Device - laptop or desktop
 - OS Version: [e.g. Windows 10]
 - Browser Name [chrome, safari, stock browser, any]
 - Browser Version [any]

**Additional context**

**Comment by jbrcna** [comment]
**QA Passed**
v4.29.0-beta0
https://4290-beta0-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html
