### ISSUE TITLE
Dropdown with Icons: Cannot select second item that has similar label but different icon 

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1441]
**Describe the bug**
Dropdown with Icons: Cannot select second item that has similar label but different icon.

**To Reproduce**
1. Go to http://4140-rc0-enterprise.demo.design.infor.com/components/dropdown/example-icons.html
2. Open the dropdown
3. Click the second "Icon with over color" item
4. See issue: the first "Icon with over color" item will be the value of the dropdown, where it should be the second one.
5. Open the dropdown, you can see that both "Icon with over color" items are highlighted

**Expected behavior**
Dropdown item with the same label but different icon can be selected.

**Version**
- ids-enterprise: v4.10.0 - v4.14.0-rc0

**Screenshots**
No screenshots available

**Platform**
 - All devices, OS and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This is probably just an example issue where the data is the same on the two items.

**Comment by tmcconechy** [comment]
This appears to have been fixed along the way. Closing
