### ISSUE TITLE
Menu Button: Sort button not working on responsive view 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1442]
**Describe the bug**
Menu Button: Sort button not working on responsive view 

**To Reproduce**
1. Go to http://4140-rc0-enterprise.demo.design.infor.com/components/menubutton/test-splitbutton.html OR http://4140-rc0-enterprise.demo.design.infor.com/components/menubutton/test-splitbutton-sort.html
2. Minimize the Screen
3. Click Sort Descending in responsive view / in Mobile

**Expected behavior**
Sort button should be working

**Version**

- ids-enterprise: [v4.14.0]

**Screenshots**
<img width="397" alt="screen shot 2018-12-26 at 8 32 49 pm" src="https://user-images.githubusercontent.com/45757016/50446078-de67ff00-094d-11e9-83ba-a75aeee190cf.png">

**Platform**
All browser, os and devices. 

**Additional context**
No any additional context.

**Comment by tmcconechy** [comment]
This is probably another example issue where the example cannot be made to work responsively. Can take a look or remove this page as part of #1136

**Comment by tmcconechy** [comment]
Since split buttons are not officially supported and considered confusing UX. As part of 1136 considering this a test page. That does not support mobile.
