### ISSUE TITLE
Busy Indicator: Overlapping Icon in lookup field

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1444]
**Describe the bug**
Busy Indicator: Overlapping Icon in lookup field

**To Reproduce**
1. Go to http://4140-rc0-enterprise.demo.design.infor.com/components/busyindicator/test-ajax-calls.html
2. Click on Lookup field
3. Navigate field
4. Notice that the Busy indicator is overlapping the lookup icon field.

**Expected behavior**
Lookup icon should be hidden while busy indicator is running / Busy Indicator and lookup icon should not overlap each other. 

**Version**

- ids-enterprise: [v4.14.0]

**Screenshots**
<img width="768" alt="screen shot 2018-12-26 at 4 50 44 pm" src="https://user-images.githubusercontent.com/45757016/50446382-ae216000-094f-11e9-9761-11ec6a336579.png">

**Platform**
All Browsers, OS and Devices.

**Additional context**
No any additional context.

**Comment by tmcconechy** [comment]
Can take a look or remove this page as part of #1136 as its a test test page, but we can try to hide the underlying icon so both do not show up at the same time.

**Comment by tmcconechy** [comment]
Descoping this issue for now
