### ISSUE TITLE
Time Picker: AM/PM tooltip is displaying on Android browsers

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1446]
**Describe the bug**
Time Picker: AM/PM tooltip is displaying on Android browsers.

**To Reproduce**
1. Go to http://4140-rc0-enterprise.demo.design.infor.com/components/timepicker/example-index.html on any Android browsers
2. Open the time picker
3. Click the AM/PM drodpdown
4. See issue: tooltip will appear

**Expected behavior**
There should not be any tooltip on the AM/PM dropdown

**Version**
- ids-enterprise: v4.14.0-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/50480319-30745780-0a16-11e9-996f-e355ecc5d907.png)

**Platform**
 - Android browsers

**Additional context**
No additional context.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
