### ISSUE TITLE
Multi-select select all: tooltip overlapping field values

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1447]
**Describe the bug**
Multi-select select all: tooltip overlapping field values

**To Reproduce**
1. Go to http://4140-rc0-enterprise.demo.design.infor.com/components/multiselect/test-select-all.html
2. Click Select All
3. Deselect one value one value
4. Click the field again

**Expected behavior**
Tooltip should not overlap the field values

**Version**

- ids-enterprise: [v4.14.0]

**Screenshots**
<img width="648" alt="screen shot 2018-12-27 at 7 32 35 pm" src="https://user-images.githubusercontent.com/45757016/50481276-931c2200-0a1b-11e9-944f-ec9586005da3.png">

**Platform**
Android Devices Version 8

**Additional context**
No Additional context

**Comment by tmcconechy** [comment]
Im going to close this issue as i do not think there is any way to fix this. Also not entirely sure there is a major issue here so very trivial.
