### ISSUE TITLE
Icon search not responding

### ISSUE THREAD

**Issue by corettas** [infor-design/enterprise#1449]
**Describe the bug**
When a search term is entered, there are no responses in the search.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/icons/example-index?font=source-sans'.
2. Click on the magnifying glass.
3. Enter a search term.
4. The search does not complete.

**Expected behavior**
The search should produce icons based on the search term entered.

**Version**

- ids-enterprise: N/A

**Screenshots**

**Platform**
 - Device MacBook Pro
 - OS Version: 10.13
 - Browser Name: Chrome
 - Browser Version: 71.0.3578.98

**Additional context**

**Comment by clepore** [comment]
Unfortunately the header search is only there as decoration for most of the demos and examples. It seems like it should provide search results in the page, but it is not connected to do so.

As a resolve, we have an initiative remove that header and make it a simple header to avoid misleading site visitors with false functionality.

**Comment by tmcconechy** [comment]
We could just remove the icon for now. Also maybe replace it with an Info icon with that dropdown with example info.

**Comment by theakatz** [comment]
We are going to remove the magnifying glass icon.

**Comment by tmcconechy** [comment]
Yep who grabs this just remove this from the template.

**Comment by tmcconechy** [comment]
Turns out I already did this on master when i did 

To test
- any page like http://master-enterprise.demo.design.infor.com/components/validation/example-index.html will no longer have a search
- http://master-enterprise.demo.design.infor.com/components/validation/example-multiple-errors.html has the new popup demo.

**Comment by janahintal** [comment]
Hi @tmcconechy, I see now that the Search icon in * http://master-enterprise.demo.design.infor.com/components/validation/example-index.html are no longer visible however, in * http://master-enterprise.demo.design.infor.com/components/validation/example-multiple-errors.html there is still lookup icon/search icon in the 1st field. May I know if this s expected?

**Comment by tmcconechy** [comment]
@janahintal Yes this is as expected. The one page http://master-enterprise.demo.design.infor.com/components/validation/example-multiple-errors.html has a new concept that we may add to the pages going forward. Its in there for review. It shows the steps of the page and info about the page in that dialog.

In the future we will refine this dialog a bit and add it to more pages. So assume either the info icon or no search on all pages.

**Comment by clepore** [comment]
@janahintal The search icon in the header was never functional for the demo pages anyway. It was just there as a visual leftover from a previous layout.

**Comment by tmcconechy** [comment]
Right thats we we removed it but http://master-enterprise.demo.design.infor.com/components/validation/example-multiple-errors.html shows an Info icon not a search - and its functional. So we might use that on pages going forward (either info icon or no search that doesnt function)

**Comment by janahintal** [comment]
Noted in that. Thanks @clepore & @tmcconechy. Will 
Move the ticket to Done Now. 
Tested in all devices and Browsers. Thanks!
