### ISSUE TITLE
RTL: Modal Checkbox in causes modal to disappear when clicked

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#1450]
Hi,

If you add a checkbox component to a modal, and you're using an RTL locale (Arabic/Hebrew), the modal will disappear after clicking the checkbox (hitting ESC on the keyboard will bring it back).
This behavior is seen on Chrome 71 and Firefox. However, on IE 11 it works well.

Please see an example:
https://jsfiddle.net/sebulbajoe/1q3th0sy/2/

**To Reproduce**
1. Add a checkbox to a modal
2. Change the locale in $('body').initialize to ar-EG or he-IL
3. Show the modal, and click the checkbox

**Version**
- ids-enterprise: v4.13.0 - v4.15.0-dev

**Platform**
 - OS Version: Windows 7
 - Browser Name: Chrome  - Version 71.0.3578.98 (Official Build) (64-bit)
 - Browser Name: Firefox Developer Edition - Version 65.0b6 (64-bit)

Thanks,
Jonathan

**Comment by tmcconechy** [comment]
Also able to reproduce by simply adding..

```
  		<div class="field">
  			<input type="checkbox" class="checkbox" id="checkbox1">
  			<label for="checkbox1" class="checkbox-label">Unchecked</label>
  		</div>
```
To example-index in the modal folder and running as example-index.html?locale=ar-SA

**Comment by SofiK** [comment]
We also have this issue in Homepages in a Contextual Action Panel in Chrome (not IE), Reproducible in the following example: http://localhost:4000/components/contextualactionpanel/test-searchfield.html?locale=ar-SA

**Comment by tmcconechy** [comment]
Makes sense - as CAP uses the modal.

**Comment by SofiK** [comment]
I think this issue has been fixed!

**Comment by tmcconechy** [comment]
Thanks will let QA test it out if its in doubt a bit

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Closing out this ticket.
