### ISSUE TITLE
Tab activated events are fired on closing a tab with X button

### ISSUE THREAD

**Issue by duncsully** [infor-design/enterprise#1452]
**Describe the bug**
It appears that any time a tab is closed via clicking the X, the activated events (before and after included) fire before the delete, and the event target is the tab set container, so I don't really have anyway of knowing that this activation event came from a deletion. 

**To Reproduce**
1. Navigate to http://master-enterprise.demo.design.infor.com/components/tabs/example-dismissible-tabs.html
2. Open debugger
3. In console, enter: $('#tabs-dismissible').on('activated close', console.log)
4. Close any tab via clicking X
5. Notice that an activated event fires before the close event (in addition to the activated event that happens after the close to select a new tab), this happens regardless if tab was already selected before removal

**Expected behavior**
A. The first set of activated events don't fire at all.
B. If not that, then I'd like some reliable way to know to selectively ignore it in my activated handlers. 

**Version**
Appears to be happening in 4.11 and the latest 4.15 dev (likely everything in between)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
If closing a tab - activate should not fire for that tab.

**Comment by tmcconechy** [comment]
Descoping this issue for now. Its not totally incorrect since when you click the tab it activates first as your clicking it as well as the close button

**Comment by tmcconechy** [comment]
yeah i suppose i agree - i was looking at the functionality of it not the events. we can add it back to the backlog

**Comment by aaronpikkarainen** [comment]
Suggested Fix:

**tabs.js** - lines 798-802
`
// let right click and close icon click pass through
if (e.which !== 3 && !$(e.target).hasClass('close')) {
  return self.handleTabClick(e, $(this));
}
return false;
`

Note: I have not fully tested this fix, but it seems good based on my limited testing.

**Comment by jbrcna** [comment]
QA Passed .v4.63.0-dev
https://main-enterprise.demo.design.infor.com/components/tabs/example-dismissible-tabs.html
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/56722184/165885573-1b3f0009-e85f-4c32-8576-6a0a6f63dbf2.png">
