### ISSUE TITLE
Accordian: Name text isn't wrapping correctly when using long static text 

### ISSUE THREAD

**Issue by drinkaj** [infor-design/enterprise#1454]
**Describe the bug**
Landmark uses the "accordion-content accordion-static-panel" layout for the account and menu navigation, but if you have a really long name or are logging in as a proxy for another manager the text wraps into the picture.

**To Reproduce**
1. Using Chrome. Go to the following url http://usalvlhlpool1.infor.com/4.6.0-rc/components/applicationmenu/example-menubutton
2. Right click on name area and inspect the element. Add additional text to make the name longer. 

**Expected behavior**
Text should not display over the picture icon. Should get similar behavior as http://usalvlhlpool1.infor.com/4.6.0-rc/components/applicationmenu/test-long-content-string.html

**Screenshots**
![textwrap](https://user-images.githubusercontent.com/6230418/43094985-0f1695de-8e7a-11e8-8234-7d73fbd7d117.png)
![hcmexample](https://user-images.githubusercontent.com/6230418/43094990-126b579c-8e7a-11e8-8367-910507f7c8e0.png)

**Platform**
 - OS Version: Windows 7
 - Browser Name: chrome
 - Browser Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by lipetzan** [comment]
I wonder if https://github.com/infor-design/enterprise/issues/457 isn't a duplicate.

**Comment by janahintal** [comment]
QA Passed. 
Tested in: https://4150-beta0-enterprise.demo.design.infor.com/components/applicationmenu/example-menubutton across all browser, OS and devices
