### ISSUE TITLE
Datagrid: Smaller page sizes can not seem to scroll horizontally

### ISSUE THREAD

**Issue by deep7102** [infor-design/enterprise#1456]
**Describe the bug**
At smaller page sizes can not seem to scroll horizontally to view the last column with datagrid.

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/example-index.html'
2. Open page with full screen width
3. Resize the page so you can hide last column only
4. Try to scroll to reach that hidden last column
5. No scrolling happen

**Expected behavior**
Should let it scroll to see all the columns.

**Comment by tmcconechy** [comment]
Should finish this after #464 so i'll grab this one.

**Comment by tmcconechy** [comment]
Could also address https://github.com/infor-design/enterprise/issues/1191 at the same time.

**Comment by brianjuan** [comment]
http://4160-beta0-enterprise.demo.design.infor.com/components/datagrid/example-index.html
Passed QA testing on all browsers.
