### ISSUE TITLE
Splitter: Character sometimes renders incorrectly

### ISSUE THREAD

**Issue by duncsully** [infor-design/enterprise#1458]
**Describe the bug**
Very occasionally the character used for the splitter drag handle renders incorrectly.

**To Reproduce**
Cannot consistently reproduce, happens intermittently, perhaps latency dependent? 

**Expected behavior**
Ideally, this character should be replaced with an SVG icon that wouldn't be susceptible to character encoding problems or other text-related oddities. 

**Version**
Has happened in all versions

**Screenshots**
![image](https://user-images.githubusercontent.com/10189958/50651082-ee806f80-0f47-11e9-9ab0-b0794272827a.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 71.0.3578.98 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Was previously once reported in https://jira.infor.com/browse/SOHO-7408

**Comment by janahintal** [comment]
This issue is now resolved. Will move to Done.
