### ISSUE TITLE
Pager: Need to have page size chooser available at narrower widths

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#1459]
**Is your feature request related to a problem? Please describe.**
Need to be able to have standalone pager.js display the page size chooser in narrow widths

**Describe the solution you'd like**
Remove 'Records Per Page' test at narrow widths and just display the dropdown. 

**Describe alternatives you've considered**
Some sort of smaller text that is still meaningful.

**Additional context**
![50295215-31692000-043d-11e9-8754-e0fd1de2797c](https://user-images.githubusercontent.com/4737815/50654843-c3038200-0f53-11e9-9773-c34ae19d30f0.png)

**Comment by janahintal** [comment]
Pager Doesn't show in iOS Devices. Will move this ticket to Failed for now. Thank you. 

Steps to Replicate:
1. Using iOS Device, Open 'https://4170-beta0-enterprise.demo.design.infor.com/patterns/list-detail-paging-pagesize-selector.html'
2. Notice that the Page doesn't show the Pager at the bottom. 

Tested using: Iphone XS - Safari


<img width="915" alt="Screen Shot 2019-03-21 at 4 02 49 PM" src="https://user-images.githubusercontent.com/45757016/54739373-d1784600-4bf2-11e9-87ef-377fd5711163.png">

**Comment by tmcconechy** [comment]
@EdwardCoyle From what i see the device is too small so the picker is still not shown by rule. And i think thats ok. Also if you have a short page like this in landscape mode you might just have to scroll down to see things and thats also fine to me.

If you agree this is a non issue, lets just move this back for further testing and ignore this issue?

**Comment by EdwardCoyle** [comment]
@tmcconechy @janahintal I was able to reproduce in the simulator.

Taking a closer look at it, there are multiple issues with the mobile view I'm seeing:
- [ ] The issue described above, which isn't really a practical setup to use for this pattern, but we should still see about potentially providing the pager bar in some way on that view.
- [ ] When the device is landscape oriented, the page selector is still not available.
- [ ] When you open the page in a desktop browser, and shrink the viewport to see the responsive mode, the page size selector is not there, and it appears the first/last buttons are becoming disabled for no specific reason.

I didn't see any of this before, so I've got some changes to make

**Comment by EdwardCoyle** [comment]
Noting that I'm going to PR the fixes for this shortly, but I made a "band-aid" fix for the landscape-oriented pager bar display that I don't really like, and I've raised #1831 for Evolution to clean it up, along with other layout-related stuff.

**Comment by janahintal** [comment]
Thanks @EdwardCoyle. I've already tested in iOS and the pager is now showing. 
Also tested across all browser, and OS. 
QA Passed. Will move to Done.
