### ISSUE TITLE
Events: Standardize all component API event names

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1461]
**Is your feature request related to a problem? Please describe.**

Different components have similar event names that mean the same thing, or seem like they mean the same thing, for example:

- `expandablearea/expand` vs `hierarchy/expanded`
-  `dropdown/listopened` vs `autocomplete/listopen` vs `modal/open`
- `deselected` vs `unselected`

**Describe the solution you'd like**
- All similar event names should be the same and camelCased, such as `beforeOpen` or `afterExpand`.
- Clean up event documentation
    - Datagrid has two `@event contextmenu` events documented..."contextmenu" doesn't seem like a valid event name either, so we should probably rename any super vague events to be more meaningful
- Remove any `settings.callback()` in favor of the event they are associated with. If needed, add `before{Event}` to replace the settings callback property.
- Event functional testing

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tmcconechy** [comment]
Related thought we also started to make both an event AND a call back.. Fx

selected - event
onSelected - method/setting

I was thinking that we could either...
a) just use one (prefer the onSelected method as it conflicts yet and is better in NG)
b) make sure there is both as we standardize the events

**Comment by clepore** [comment]
I'm hesitant to prefix with `on` because it's vague in whether hit happens before or after the event occurs, but the general premise is a good thought.

**Comment by tmcconechy** [comment]
on is pretty common i think its ok. onBeforeSelected runs before onAfterSelected runs at the end onSelected runs during. Thats pretty much what we been doing.

**Comment by clepore** [comment]
Okay, that would probably be fine to have callbacks as `settings.onSelect` where the callback would run after the `select` event occurs (since its a "callback"...hence runs after the initial code). I'll add an item in the initial description to make sure methods have matching events.

**Comment by tmcconechy** [comment]
Decided to go with standard events as this is what web components are doing. Then use the past tense.

beforeselected, beforedimissed, dismissed, beforedismissed

As this is breaking in some case will be documented part by part during the refacter web component projetc. No need a think for an open issue
