### ISSUE TITLE
WC: Datasource: Create a datasource component with API hooks to standardize data

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1463]
**Is your feature request related to a problem? Please describe.**
We have been coming across the need for data formatting and standardization.

**Describe the solution you'd like**
Create a new component that handles and distributes data in standardized ways for all components  to use.

**Describe alternatives you've considered**

**Additional context**
- [Kendo UI Data source](https://docs.telerik.com/kendo-ui/framework/datasource/overview)
- Prereq to issue https://github.com/infor-design/enterprise/issues/941

**Comment by clepore** [comment]
Lets try to remove most of the data logic out of the components and dumb the data down to be mostly just rendering.

For February, lets get some notes and comments on this issue, and maybe a branch to set it up for actual implementation.

**Comment by tmcconechy** [comment]
This work has been done in the new web component version. You can now use basic table styles - standalone when that version is released.
