### ISSUE TITLE
Remove anything @deprecated

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1476]
**Describe the Task**

- [x] add a deprecated note for Step Process
- [ ] add a deprecated note for Field Options
- [ ] add a deprecated note for Composite Form
- [x] add a deprecated note for Popdown
- [ ] search all code for deprecated and remove. Currently 47 hits in 28 files.
- [x] Deprecate `confirm` in favor of `success` (#963)
- [ ] Remove popdown as its covered by popup / tooltip (#2468)
- [ ] Remove svg patterns (they never worked right and don't work now)
- [ ] Field Options?

 And then document all this carefully in the change log.

**Comment by davidcarlsonberg** [comment]
@tmcconechy I didn't include a `@deprecated` tag for the below ticket but thought I should bring it up here as it should be deprecated at some point:
https://github.com/infor-design/enterprise/issues/963

**Comment by tmcconechy** [comment]
Setting to 1 for the first part which is just adding a note that the components WILL be deprecated later

**Comment by tmcconechy** [comment]
@pwpatton I just wanted to be 100% sure. Plan is to mark these as deprecated:
Step Process
Field Options
Composite Form
Popdown

As you said you dont use some of these. See any issue there? Will mark it now and remove in 3-4 months but will check first.

**Comment by tmcconechy** [comment]
descoping this for now - will be done during eventual refactor
