### ISSUE TITLE
Popupmenu: Rework to separate concerns

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1477]
**Is your feature request related to a problem? Please describe.**
There are multiple different "systems" all mixed into the Popupmenu that could be more cleanly separated for easier maintenance and API access.  This would be a similar initiative to Flex Toolbar and how it's structured.

**Describe the solution you'd like**
Separate the Popupmenu into multiple sub-component types:
- [ ] *Popup Container* - a generic "window" or "wrapper" that can be attached to a parent element, like a trigger button.  There would be settings that control the placement (via the current Place behavior), and APIs for setting content and a generic method for returning a value via event/callback that was generated by work done internally on the popup (fx: returning the state of the entire Popupmenu's list once the list is closed and focus is returned to the trigger).  This could be created in a way that would eventually let us use the same pattern on trigger buttons for opening modals or other styles of contained workflow.
- [ ] *Generic List* - a generic "list" type that can wrap HTMLElements such as `<ol>` or `<li>` that simply provide all the basic APIs for a "list" type (fx: find selected items, find disabled items, provide totals, etc).
- [ ] *Generic List Item* - Similar to Flex Toolbar Item, which represents a single item in the list and its current state.  It would be possible to use APIs and properties directly on this type to affect the state (fx: disabled, selected, hidden).

Other minor improvements to the way menu systems work:
- [ ] Re-work the Popupmenu to be more data-driven, and use data as the source of truth instead of HTML markup (some headway's already been made on the component to help this along, we need to finish it -- see the [`toData()` method on Popupmenu](https://github.com/infor-design/enterprise/blob/4.14.x/src/components/popupmenu/popupmenu.js#L419-L429) which already works with Flex Toolbar in this manner).
- [ ] There should be no separate concept of a "sub-menu". Using the data, it should be possible to open recursive instances of a popupmenu to use as a submenu against a parent popupmenu item (read: get rid of things like [`showSubmenu`](https://github.com/infor-design/enterprise/blob/4.14.x/src/components/popupmenu/popupmenu.js#L1778) in favor of just temporarily opening another menu instance.

**Comment by tmcconechy** [comment]
Replaced by #4256
