### ISSUE TITLE
Fully remove all deprecated `data-` attribute-based settings that are not `data-options`

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1478]
**Is your feature request related to a problem? Please describe.**
At the beginning of Soho 4.x, many of the components accepted both a JS-based way of building settings, as well as HTML-markup based `data-*` attributes that would be converted and preferred over the originally-set JS settings.

Over time we began to standardize on two methods of changing component settings:
- JS via the component constructor (fx: `$('#my-dropdown').dropdown({ source: 'http://site.com' });`)
- HTML-based using JSON-style syntax, like the following:
```html
<select id="my-dropdown" class="dropdown" data-options="{ source: 'http://site.com' }"></select>
```
This system works better for our users.  However, some of the legacy settings remain, and there are many little pieces of setup code throughout the components that converts these legacy attributes to actual settings.  In a new major release, we should push to remove these legacy patterns in favor of the standard ones.

**Describe the solution you'd like**
- [ ] Search and document all deprecated HTML-based settings
- [ ] Remove them all
- [ ] Remove all related tests
- [ ] Ensure all component configurations are still possible

**Comment by tmcconechy** [comment]
Closing this for now. In the web component version these will all be gone.
