### ISSUE TITLE
Datagrid: Improve "Run Filter" settings

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#1479]
On the Datagrid toolbar, when filtering is enabled, there is a "more" menu that has a "Run Filter" option, but, as far as I can tell using the settings we use, the filter is applied as soon as the user changes a value in the filter field within the header.

e.g. see the standard example...

https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-filter?font=source-sans

Is there a way to remove the Run Filter option but leave the other menu options to Save and Clear the Filter (I can't see any documentation for settings.toolbar in https://design.infor.com/code/ids-enterprise/latest/datagrid and also the example for settings.toolbar seems to have been put under settings.selectChildren by mistake)?

**Comment by tmcconechy** [comment]
Run filter does run the filter but the "problem" is that the default for filtering is when you edit the field it runs. Some folks that run backend calls wanted ability to disable this so if you use 'filterWhenTyping = false' option its more useful.

Unfortunately you cannot individually remove that with the setting. https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L5308 as its all under the filterRow option. We should make more toolbar options though.

The other thing you can do is make a custom toolbar removing the item https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-custom-toolbar.html (and insert the items as shown in the code link for the filter).

Moved the settings out in the docs. Thanks!

**Comment by sanx72** [comment]
Thanks for the feedback. from what you've described about the filterWhenTyping option, which I presume is the default, if that is set to 'true' is there any point in showing the "Run Filter" menu option? If there is, then a new settings.toolbar option to be able to hide the Run Filter option would be preferable, as I don't really want to go down the custom toolbar route, as that would mean that we would need to keep checking for any changes to the HTML markup of the standard toolbar at each release to make sure we don't lose out on any changes or new function that is added in that area.

**Comment by tmcconechy** [comment]
Making a pr where i added an example at app/views/components/datagrid/test-filter-toolbar-filter-row.html that shows the toolbar with only the clear and showFilter row options. Made it such you can do this in the option.

```
toolbar: {... filterRow: { showFilter: true, clearFilter: true } ... }
```

All options `filterRow: { showFilter: true, clearFilter: true, runFilter }` but if `filterWhenTyping` is true runFilter is ignored.

**Comment by jbrcna** [comment]
This issue is now resolved. tested in master v4.26-dev
moving this ticket to Done
