### ISSUE TITLE
When using minWidth option the sort will misalign columns

### ISSUE THREAD

**Issue by darinw** [infor-design/enterprise#1481]
**Describe the bug**
When using minWidth, changing the column width before reordering will cause the columns to misalign

**To Reproduce**
1. Go to https://codepen.io/anon/pen/REqWqz
2. Resize the "Product Name" column
3. Click "Product Name" Header (sort)
4. See Misaligned  columns

**Expected behavior**
Should Remain aligned

**Version**
- latest-enterprise --- 4.14.0

**Comment by tmcconechy** [comment]
@darinw Which example page did this start from?

**Comment by brianjuan** [comment]
http://4160-beta0-enterprise.demo.design.infor.com/components/datagrid/example-index
Passed QA testing on all browsers
