### ISSUE TITLE
Lookup in datagrid filter not giving click info about datagrid

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#1486]
**Describe the bug**
When using the click function setting on a lookup in a datagrid, a reference to the datagrid object isn't returned. 

**To Reproduce**
1. Put the attached test-filter-lookup-click-function.html in your code base and navigate to it.
2. Click the trigger icon for the lookup in filter row for Product Id
3. An alert with "No click arguments returned" will popup

**Expected behavior**
An alert with "Grid Information Found" should popup

**Version**
- ids-enterprise: 4.15-dev

**Platform**
 -All

[test-filter-lookup-click-function.zip](https://github.com/infor-design/enterprise/files/2756703/test-filter-lookup-click-function.zip)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done folder.
