### ISSUE TITLE
Editor: Actions menu cannot be opened after clear formatting

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#1494]
**Describe the bug**
I found this issue in Homepages Notes widget and was able to reproduce it in IDS when shrinking the view so that the background color button is moved to the ... menu in the toolbar (Can be reproduced with larger view too). 
The issue is that after selecting "Clear formatting" in the ... menu a white arrow is shown (Se image) and the ... menu can no longer be opened. 
**Note**: It seems to happen when a paragraph (enter) is included in the selected text. (See second screenshot)

**To Reproduce**
1. Got to http://localhost:4000/components/editor/test-clear-formatting.html#
2. Shrink the window until the background color button ends up in the ... menu
3. Select some text, make sure to select parts of two paragraphs (see second image)
4. Click ... > Clear formatting
=> Arrow is shown in view (see first image)
5. Click ...
=>Menu is not opened 

**Expected behavior**
The small white arrow should not be shown and it should be possible to open the menu again.

**Version**
4.14.0

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/51234154-3d78cc80-196c-11e9-9d90-3e164b7ebcd3.png)
![image](https://user-images.githubusercontent.com/8664975/51234709-d9570800-196d-11e9-8ead-c05ed078e127.png)

**Platform**
Windows 10
IE11 / Chrome
 11.253.17763.0/Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
As seen in the second screenshot very little text is enough for reproducing the bug as long as it's part of 2 different paragraphs. Also This issue can be reproduced with only one item in the ... menu.

**Comment by tmcconechy** [comment]
This can no longer be reproduced on https://master-enterprise.demo.design.infor.com/components/editor/example-index.html

this was actually fixed when we added the new heading picker. The menus have been changed to all not have arrows now. And the issue as written does not occur
