### ISSUE TITLE
Trackdirty: UI issue with a track dirty dropdown in a compound-field

### ISSUE THREAD

**Issue by AleksandraKlyszcz** [infor-design/enterprise#1497]
We're using dropdown inside compound-field class and when the dirty-icon is displayed it overlaps the dropdown component. It is higher then without compound-field.

The dom structure is:
`<div class="compound-field">`
`<div class="field">`
`<label class="label">Label text</label>`
`<select soho-dropdown soho-trackdirty ...>`
`<option...></option>`
`</select>`
` </div>`
`</div>`

**Screenshots**
![soho-bug](https://user-images.githubusercontent.com/8652479/51248830-aaeb2400-1991-11e9-83c5-9be24a1c38ae.jpg)

**Comment by clepore** [comment]
No response, closing.

**Comment by AleksandraKlyszcz** [comment]
Sorry for not sufficient description. I'll try once again:

**Describe the bug**
We're using dropdown inside compound-field class and when the dirty-icon is displayed it overlaps the dropdown component. It is higher then without compound-field. It also happens on input field.

**To Reproduce**
Steps to reproduce the behavior:
1. Use 
```
<div class="compound-field">
<div class="field">
<label class="label">Label text</label>
<select soho-dropdown soho-trackdirty ...>
<option...></option>
</select>
</div>
</div>
```
2. Change data in dropdown
3. Dirty icon is too high

**Version**

- ids-enterprise-ng: 5.0.0

**Screenshots**
![51248830-aaeb2400-1991-11e9-83c5-9be24a1c38ae](https://user-images.githubusercontent.com/8652479/53738091-8807c700-3e8e-11e9-8159-371d58b253fa.jpg)

**Platform**
 - Device: DELL Latitude
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 72.0.3626.119 (Official Build) (64-bit)

**Additional context**
Add any other context about the problem here.

**Comment by tmcconechy** [comment]
Seems like the issue is ok here: http://latest-enterprise.demo.design.infor.com/components/trackdirty/example-index.html this is 4.15 which will be in 5.10.0 NG . In the screen shot looks like more is bumping the icon down and around. Maybe some css in that example is effecting the layout?

**Comment by tmcconechy** [comment]
Also https://github.com/infor-design/enterprise/issues/1052 could be similar.

**Comment by AleksandraKlyszcz** [comment]
Another screenshot with field inside compound field:
![image](https://user-images.githubusercontent.com/8652479/53740785-40386e00-3e95-11e9-912d-5358cc9cd9c8.png)
