### ISSUE TITLE
Searchfield: long labels do not show correctly

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#1500]
**Describe the bug**
When you pass string to the label long enough that horizontal scrollbar will appear, there is an issue with the line dividing the results and 'all results'

**To Reproduce**
1. In the searchfield demo component, change the label to something extra long
2. Open the demo in browser and go to searchfield
3. Type in a string which will match the long string in code
4. Observe after scrolling to the right in result popdown

**Expected behavior**
The dividing line should have full width of the popdown

**Version**
- ids-enterprise-ng: 4.11.0, 5.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/11279863/50145464-f25a9380-02b1-11e9-9505-c046ea5c1436.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 71.0.3578.98 (Official Build) (64-bit)

**Comment by janahintal** [comment]
QA failed.

**Comment by brianjuan** [comment]
http://4150-rc0-enterprise.demo.design.infor.com/components/searchfield/test-long-options.html
Passed QA testing on all browsers.
