### ISSUE TITLE
Popupmenu: Can not longer do "immediate" popupmenus twice.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1507]
**Describe the bug**

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/tree/example-context-menu.html
2. Right Click on first (or any) node
2. Right Click again on first (or any) node

**Expected behavior**
Should be able to right click more than once. The code is using immediate trigger method so its a bigger issue than just this page.

**Version**
- Failed on v4.14.0

**Platform**
- Any

**Additional context**
Back tracked this code change as the cause https://github.com/infor-design/enterprise/pull/1217

**Comment by janahintal** [comment]
QA Passed. Moving to Done
Tested in: https://4150-beta0-enterprise.demo.design.infor.com/components/tree/example-context-menu.html
