### ISSUE TITLE
RTL: Text end up behind icon in Searchfield

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#1514]
**Describe the bug**
When running in RTL, The text in search field ends up behind the search icon.

**To Reproduce**
1. Go to http://localhost:4000/?colors=800000&locale=ar-SA
2. Scroll down to Search field
=> Issue here already for label
3. Start writing in the search field
4. Notice that the text ends up behind the icon

**Expected behavior**
There should be space between the search icon and the text so that the text is readable.

**Version**
- ids-enterprise: 4.14.0

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/51522320-634d1800-1e29-11e9-94d9-4fa493cffe53.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name IE11
 - Browser Version 11.253.17763.0

**Additional context**

**Comment by tmcconechy** [comment]
Complete with https://github.com/infor-design/enterprise/issues/1515

**Comment by tmcconechy** [comment]
Retesting this issue we noticed this is fixed. To verify:
- go to http://localhost:4000/components/searchfield/example-index.html?locale=ar-SA
- type in the field
- text is no longer overlapping the icon

**Comment by tmcconechy** [comment]
Possibly fixed by @EdwardCoyle on https://github.com/infor-design/enterprise/issues/1515

**Comment by janahintal** [comment]
Hi @tmcconechy  tested this ticket in http://master-enterprise.demo.design.infor.com/components/searchfield/example-index.html?locale=ar-SA and noticed that in Chrome & Safari, the cursor  or focus stays in the left side.  Should this be the right behavior? I only experince it  in Chrome and Safari browser?
![image](https://user-images.githubusercontent.com/45757016/60966871-d69d0480-a34b-11e9-9ce2-ee2bf4e74f7c.png)

**Comment by tmcconechy** [comment]
I think this is probably just the way the browser handles rlt text. Ie it’s like having the cursor at the “end” of the text. I’d ignore this as it’s out of our control
