### ISSUE TITLE
RTL: Horizontal scroll in About in chrome

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#1516]
**Describe the bug**
A minor minor issue in About dialog in Chrome when running RTL is that a horizontal scroll is visible.

**To Reproduce**
1. Go to http://localhost:4000/?colors=800000&locale=ar-SA in chrome
2. Notice the horizontal scroll.

**Expected behavior**
no horizontal scroll should be needed.

**Version**
- ids-enterprise:4.14.0

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/51527880-c17ff800-1e35-11e9-8aab-32d6e8efde16.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Additional context**

**Comment by SofiK** [comment]
No longer an issue in v 4.22.1 (and probably som earlier versions) see: https://design.infor.com/code/ids-enterprise/latest/demo/components/about/example-index.html?locale=ar-SA

**Comment by tmcconechy** [comment]
Thanks @SofiK was thinking of making next sprint one where we fix some RTL issues. So if you see any others you cannot reproduce just feel free to close them off. Thats very helpful.

https://github.com/infor-design/enterprise/labels/focus%3A%20rtl
