### ISSUE TITLE
RTL: Toolbar gets wrong position when application menu is used

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#1518]
**Describe the bug**
When you run in RTL (ar-SA as locale) the application is moved to the right, but the space left for the application menu is still on the left, so the menu hides parts of the toolbar in IE11. Reproducible in enterprise-ng. 

**To Reproduce**
1. For the angular project Change locale to ar-SA in app.component.ts
2. Go to http://localhost:4200/
3. Issue occurs here, Empty space to the left and menu button is placed below the Application menu

**Expected behavior**
The full toolbar should be visible with no extra space to the left

**Version**
- ids-enterpris**e-ng**: 5.0

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/51541579-78419f80-1e59-11e9-9cb6-4c35b495c68a.png)

![image](https://user-images.githubusercontent.com/8664975/51541853-25b4b300-1e5a-11e9-94cd-231be5c0f8ee.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: IE11
 - Browser Version: 11.253.17763.0

**Additional context**
Changing right to "auto" instead of "initial" in html[dir='rtl'] .application-menu + .page-container {
Might be one way to solve it.

**Comment by ericangeles** [comment]
@tmcconechy, checked in NG and non NG and it seems fixed already. Will now move this ticket.

**Comment by tmcconechy** [comment]
Seems that this issue has already been fixed or we can no longer reproduce it. Can you retest this on the latest @SofiK ?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
