### ISSUE TITLE
Button: Alert icon is all white now

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1524]
**Describe the bug**
The alert icon on buttons is all white. 

**To Reproduce**
1. Go to http://localhost:4000/components/button/example-index.html 
2. Note that the icon is all white on the one button. I think this is a regression I caused on calendar changes to the alert icon. But a bit minor as I don’t think this is that widely used.

**Expected behavior**
Should be same as last version and alert should be visible

**Version**
- 4.15 Dev

**Screenshots**

**Additional context**
I did this - i can fix.

**Comment by brianjuan** [comment]
http://4150-beta0-enterprise.demo.design.infor.com/components/validation/example-multiple-errors.html
http://4150-beta0-enterprise.demo.design.infor.com/components/button/example-index.html
http://4150-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html
Passed QA testing on all browsers, moving to Done.
