### ISSUE TITLE
Hierarchy, Back button wraps in mobile views.

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#1528]
**Describe the bug**
Back button wraps on mobile devices

**To Reproduce**
1. http://localhost:4000/components/hierarchy/example-paging
2. Reduce screen to phone size via chrome emulator. Or use mobile device
3. Expand a leaf to display back button.
4. Back button wraps.

**Expected behavior**
Back button should not wrap. Leafs should not get clipped by viewport.

**Version**

- ids-enterprise:  v4.15.0-dev

**Screenshots**
![back-button-wrapping](https://user-images.githubusercontent.com/1056684/51612545-49720a80-1ee7-11e9-9042-931891b52019.png)

**Platform**
 - Desktop (windows), iPhone (5, 6, 6, 8, X), android (galaxy s5 - s9, pixel, pixel2)
 - Windows 10
 - Chrome, Firefox, IE
 - Latest Chrome and Firefox. IE11 and Edge

**Comment by tmcconechy** [comment]
Spotted this issue was not in the project. Added so it could be QA'd further

**Comment by janahintal** [comment]
QA passed.
Tested in: https://4150-beta0-enterprise.demo.design.infor.com/components/hierarchy/example-paging for all devices, OS and browser
