### ISSUE TITLE
Datagrid filter's datepicker doesn't honor editorOptions

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#1532]
**Describe the bug**
The datepicker filter when set to 'in range' filter type doesn't obey passed in editorOptions. For example, passing in 'showMonthYearPicker: true' has the month and year show up as drop downs in the date picker. When you change to 'in range' filter type, the month and year just show up as plain text.

**To Reproduce**
1. Pull in the attached [example-filter.zip](https://github.com/infor-design/enterprise/files/2788817/example-filter.zip) and put it in your datagrid/example-filter directory.
2. Navgiate to /components/datagrid/example-filter
3. Open the datepicker for Order Date, without changing the filter type.
4. The month and year should be dropdowns.
5. Close the datepicker and change it's filter type to 'in range'. Then reopen the datepicker
4. See that the month and years aren't dropdowns

**Expected behavior**
Month and Year should still be dropdowns, so the use can easily set a large date range.

**Version**

- ids-enterprise: v4.15.0-dev

**Screenshots**
On load:
![image](https://user-images.githubusercontent.com/22107636/51630879-d8474d00-1f10-11e9-9eca-14ab7662f9a9.png)

After change to 'in range':
![image](https://user-images.githubusercontent.com/22107636/51630904-e4cba580-1f10-11e9-8ec6-d7a628121128.png)

**Platform**
 - All

**Comment by janahintal** [comment]
QAPassed. Moving To Done. 
Tested in: http://localhost:4000/components/datagrid/example-filter.html in all Browser, OS and Devices
