### ISSUE TITLE
Datepicker: Range date picker and month/year picker doesn't clear selection when changing month or year

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#1537]
**Describe the bug**
The range option of a datapicker in a datagrid filter isn't clearing the original selected range when changing to a new month/year.

**To Reproduce**
1. Go to components/datagrid/example-filter
2. Select range in the filter for Order Date
3. Open the picker and select a range on the current month
4. Close it and insert the range
5. Reopen the date picker
6. Select another month or year.

Now the range is the same but for the different month/year. 

**Expected behavior**
It should probably reset the range the selected range if you choose a new month. However, there is a use case that after selecting a starting date the user should be able to change the month/year and choose an end date.

**Version**

- ids-enterprise: v4.15.0-dev

**Platform**
 - All

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/example-filter.html
Passed QA testing on all browsers, moving to Done.
