### ISSUE TITLE
Accessibility: add information to docs about our role in achieving standards compliance

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1540]
**Is your feature request related to a problem? Please describe.**
We need to set a clear expectation in the role IDS plays in helping an application achieve a certification in accessibility standards compliance, such as Section 508 or WCAG 2.0 AAA.

**Describe the solution you'd like**
We need to draw a fine line between us providing a library that is "ready" for these certifications, while not over-reaching and doing things that an application team would be responsible for, such as making content accessible.

A rough list of items we would be responsible for may include:
- we add `aria` attributes automatically where appropriate
- we provide a compliant series of color schemes
- we provide audio-backups for written text where possible

A list of things an app team would be responsible for:
- Providing accessible language and content to be used within our patterns and components
- Appropriate usage of the components in a way that ensures all of our accessibility measures are correctly working

**Comment by tmcconechy** [comment]
Probably should add this when adding #1722
