### ISSUE TITLE
Guidelines for styling custom error pages

### ISSUE THREAD

**Issue by rvaja-infor** [infor-design/enterprise#1546]
Currently there is no clear guidelines for styling custom error pages e.g. a HTTP 500 or HTTP 400 page where you wish to provide your own custom message. Other examples of custom page maybe a redirect to deny access to a web application.

Would be nice to have some guidelines or sample template on how to style these custom pages. It would be also great if default custom error pages that cover some of the HTTP error status codes were available that could be used to override the defaults provided by a web server.

**Comment by tmcconechy** [comment]
Hi @rvaja-infor can you re-raise this issue in the design system as this is for eventual dev. We will need design to look at it first. When you do that please follow the issue template

https://github.com/infor-design/design-system/issues/new

I'll follow this over there.
