### ISSUE TITLE
HomePages: Widget tiles display off the sides of screen on iPhone 5 and iPhone 6.

### ISSUE THREAD

**Issue by drinkaj** [infor-design/enterprise#1547]
**Describe the bug**
Widget tiles display off the sides of screen on iPhone 5 and iPhone 6.

**To Reproduce**
1. Using Chrome Go to http://usalvlhlpool1.infor.com/4.5.0/components/homepage/example-scenario-a.html
2. Hit F12 and toggle device toolbar and set to iPhone 5/SE
3. Note the widget containers are off the screen
4. Note the Chrome device emulator for iPhone 6/7/8 does show the sides of the widget container, but using an actual iPhone 6 device you get the same experience as the iPhone 5/SE emulator.

**Expected behavior**
Should be able to see the whole widget container. 

**Version**
Soho XI Controls v4.5.0

**Screenshots**

![widgettiles](https://user-images.githubusercontent.com/6230418/51750569-0bf0b700-2078-11e9-91cf-1fe6fe4b6956.png)

**Platform**
 - Device : iPhone 6

**Comment by tmcconechy** [comment]
Technically we say we only support R-1 versions. But this device is popular so i think we can investigate a fix. If you see something feel free to PR, i made the issue up for grabs for anyone to take.

**Comment by tmcconechy** [comment]
Since we dont technically support R-1 i will close this. The widgets are fixed size for the layouts (320px) and this just wont work on a device that old without major changes.
