### ISSUE TITLE
Local demo app: Example page links use local drive path on Windows10

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#1549]
**Describe the bug**
The example page links are being built with the local drive path instead of the web server address. For example, using http://server:4000/components/dropdown, the links to the various examples and tests all point to `C:\....`.

**To Reproduce**
1. Steps to reproduce the behavior:
1. Use Windows 10
1. `cd {basefolder}`
1. git clone <path> .
1. `npm install`
1. `npm run start`
1. go to <http://server:4000/components>
1. click a component 
1. click an example
1. Click fails due to 'Not allowed to load local resource `file:///C:/.....html`'

**Expected behavior**
The link should work; either a fully-qualified path or relative path.

**Version**

- ids-enterprise: 4.15.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/51772559-e385ae80-20b1-11e9-983f-e482d9a5430b.png)

**Platform**
 - OS Version: Windows 10, possibly Windows 7
 - Browser Name: Chrome, IE, Firefox

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
