### ISSUE TITLE
Locale: Add support to set language and locale independently

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#1552]
**Background**
A customer requirement is the ability to separate locale formatting from language. Ming.le provides these values as separate parameters, and we need the IDS components to support the same. The language and locale need to be set on a high level, when initializing the IDS Locale object, and not as options when initializing specific components. 

Example: Use English translations for all IDS components, but Swedish formatting (dates, numbers, etc.)

**Problem description**
There is currently no way to set language and locale to different values when initializing the IDS Locale object, all formatting is done based on the set language. 

**Proposed solution**
Make it possible to set language and locale independently of each other. No code change should be required for Homepages widgets / content that consume the actual IDS components, only for the IDS Locale initialization.

**Comment by tmcconechy** [comment]
I just increased the priority based on lots of people asking for it. As this may be a broader problem for ION Desk in Angular, IoT, HomePages and other new Angular applications.

**Comment by Fruko** [comment]
Note that along with language and locale, also timezones are meant to be supported. So it would be nice if Soho could also accept timezone in date/time formatters

**Comment by tmcconechy** [comment]
@Fruko Thats a separate issue: https://github.com/infor-design/enterprise/issues/592 can you list what you need over there?

**Comment by clepore** [comment]
Let's see if we can try to do this without any breaking changes before we punt on it.

**Comment by tmcconechy** [comment]
Will see if its possible when digging in this sprint and aim for no breaking change.

**Comment by brianjuan** [comment]
-https://4170-beta0-enterprise.demo.design.infor.com/components/locale/test-set-language.html?locale=ar-SA
-https://4170-beta0-enterprise.demo.design.infor.com/components/locale/test-add-custom-locale.html?locale=ar-SA
-https://4170-beta0-enterprise.demo.design.infor.com/components/locale/test-extend-messages.html
Passed QA testing on all browsers, moving to Done.

**Comment by ahnpnl** [comment]
hi, i have checked #1552 but i don't see updating of example app regarding to the usage. Is the usage documented somewhere ?

**Comment by clepore** [comment]
@ahnpnl To see updated examples in the demo app of using two different languages at once, the updated links are listed in the pull request (linked above as "merged") or https://github.com/infor-design/enterprise/pull/1767.

**Comment by tmcconechy** [comment]
Here is one other example of the usage for this:

https://github.com/infor-design/enterprise/blob/master/app/views/components/locale/test-set-language.html#L18
