### ISSUE TITLE
Radar: Legend crops off radar chart Is smaller display like when placed in card or mobile

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#1553]
If the radar chart displays it appears media tags try to handle sizing as the area gets smaller but it appears the labels are not of the solution as at times they are cut off. You can see it in the radar examples by making the screen slowly smaller and watch the repaint.

This can be reproduced in the standard enterprise examples
/components/radar/test-axis-formatter.html

![radar](https://user-images.githubusercontent.com/19823048/51846991-5b392080-22e0-11e9-83c0-ec918d5fb11f.png)

**Comment by tmcconechy** [comment]
This is probably going to be very difficult to solve. Regardless of the labels.
At a bit lower of a break point legend will go to the bottom. Maybe we can introduce the 3 label sizes that other charts have.

**Comment by krahs1** [comment]
Sure that would be fine. I think that would work.

**Comment by tmcconechy** [comment]
@lipetzan - i added this to the Milestone and dragged it down. Please feel free to place it.

**Comment by brianjuan** [comment]
Hi, even after applying 3 label sizes, labels are still getting cut-off on smaller screen sizes. Try resizing to Galaxy S5 viewport, and you'll notice that shorthand labels are cut-off.
![image](https://user-images.githubusercontent.com/39508864/54674625-cad8c880-4b37-11e9-9d48-262efeb93197.png)

**Comment by tmcconechy** [comment]
@deep7102 Maybe just reduce the size of the radar chart so it can fit 2 or 3 chars on the sides and then adjust the example to show that many.

**Comment by janahintal** [comment]
Hello, tested and issue fixed in smaller screen mobile devices, however, the issue still exist in Firefox Win10 Browser. 
Tested in: https://4170-rc0-enterprise.demo.design.infor.com/components/radar/test-long-text.html

<img width="331" alt="Screen Shot 2019-03-26 at 7 42 57 PM" src="https://user-images.githubusercontent.com/45757016/54994974-9c0f9600-5000-11e9-868b-456cb58933df.png">

**Comment by CindyMercadoReyes** [comment]
this issue is now resolved.
