### ISSUE TITLE
Dropdown error icon not removed when using .removeError()

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#1556]
**Describe the bug**
After adding an error message (non-inline) to a dropdown using addError(), then calling removeError(), the error icon is not removed.

**To Reproduce**
1. On any sample page with a dropdown, use $('select.dropdown').removeError().addError({ message: 'Dropdown error.', inline: false });
2. Call $('select.dropdown').removeError();

**Expected behavior**
Dropdown error message and icon are removed.

**Version**
- ids-enterprise: master

**Screenshots**
![image](https://user-images.githubusercontent.com/2107139/51853876-fc2ed800-22ee-11e9-877c-1705dbad8df7.png)

**Additional Info**
This has caused a customer incident, links to LSF-40959.

**Comment by tmcconechy** [comment]
Do you know if this regressed from one version to another?

**Comment by awbuboltz** [comment]
It worked in our July release, but that's about all I know. We were pre-4.11 at that time, but we didn't update until around September. So I'm not really positive where it broke.

**Comment by tmcconechy** [comment]
Ok, I also tried to see if this regressed but noticed i cannot reproduce. Go to any of these pages:

https://master-enterprise.demo.design.infor.com/components/validation/test-legacy-tooltip.html
https://4140-enterprise.demo.design.infor.com/components/validation/test-legacy-tooltip.html
https://4130-enterprise.demo.design.infor.com/components/validation/test-legacy-tooltip.html
https://4120-enterprise.demo.design.infor.com/components/validation/test-legacy-tooltip.html
https://4110-enterprise.demo.design.infor.com/components/validation/test-legacy-tooltip.html

- open console
- paste `$('select.dropdown').removeError().addError({ message: 'Dropdown error.', inline: false });`
- then `$('select.dropdown').removeError();`

Then it does seem to work ok in all those versions?

**Comment by awbuboltz** [comment]
It looks like it's reproducible here: https://master-enterprise.demo.design.infor.com/components/validation/example-multiple-errors.html

The difference between those two pages appears to be data-error-type="tooltip" on the select.

**Comment by awbuboltz** [comment]
I looks like this was broken with revision 58d0c6a.

I think that line 1018 of validator.js should be reading `field.attr(`data-${rule.type}-type`),` not `loc.attr(`data-${rule.type}-type`)`, since that data attribute gets applied to the generated field, not the original element.

**Comment by jake-harrington** [comment]
@tmcconechy Can this be prioritized? We have a couple customers reporting this issue.

**Comment by awbuboltz** [comment]
Looks good Tim, thanks!
