### ISSUE TITLE
Donut: Chart Legend is not same as what is displayed in the Chart when in High Contrast

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1561]
**Describe the bug**

**To Reproduce**
1. Go to https://4150-beta0-enterprise.demo.design.infor.com/components/donut/example-values.html
2. Switch to 'High Contrast' 
3. Click 'Open' in legend
4. Notice that the Color is different from the chart

**Expected behavior**
Legend color should be same with what is in the Chart

**Version**
v4.15.0

**Screenshots**
<img width="1050" alt="screen shot 2019-01-30 at 11 48 55 am" src="https://user-images.githubusercontent.com/45757016/51960022-1654eb80-2492-11e9-92de-5f336cce758b.png">
<img width="1043" alt="screen shot 2019-01-30 at 11 49 13 am" src="https://user-images.githubusercontent.com/45757016/51960025-17861880-2492-11e9-8048-08bce0b3a311.png">

**Platform**
All Browser, OS and Devices

**Additional context**
No additional Context

**Comment by jmacaluso711** [comment]
Hi @janahintal I can't reproduce this. Has it been resolved?

**Comment by tmcconechy** [comment]
Looks like it has i cant reproduce on https://4150-enterprise.demo.design.infor.com/components/donut/example-values.html
or https://master-enterprise.demo.design.infor.com/components/donut/example-values.html

**Comment by tmcconechy** [comment]
move to re QA

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
