### ISSUE TITLE
Donut Legend size is not responsive 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1562]
**Describe the bug**
Donut Legend size is not responsive 

**To Reproduce**
1. Go to https://4150-beta0-enterprise.demo.design.infor.com/components/donut/example-legend.html
2. Put a long label in the Legend
3. Notice that the Legend minimized and is not consistent

**Expected behavior**
Legend size should be consistent

**Version**
4.15.0

**Screenshots**
<img width="381" alt="screen shot 2019-01-30 at 2 38 40 pm" src="https://user-images.githubusercontent.com/45757016/51962935-c4659300-249c-11e9-9515-958096395d52.png">

**Platform**
 All browsers, OS and devices
Tested in Chrome.

**Comment by tmcconechy** [comment]
Descoping this for now
