### ISSUE TITLE
Modal: Modal with full content doesn't open after closing it twice

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1563]
**Describe the bug**
Modal with full content doesn't open after closing it twice.

**To Reproduce**
1. Go to https://4150-beta0-enterprise.demo.design.infor.com/components/modal/example-full-content.html
2. Click the "Show Modal" button
3. Close the Modal
4. Open the Modal again, then close
5. See issue: Screen will be grayed out and cannot interact with the page again

**Expected behavior**
Modal can be opened again multiple times

**Version**
- ids-enterprise: v4.14.0 - v4.15.0-beta0

**Screenshots**
After closing the modal twice
<img width="1261" alt="screen shot 2019-01-30 at 6 44 20 pm" src="https://user-images.githubusercontent.com/39508864/51976219-18816f00-24bf-11e9-8842-3517def58bbc.png">

**Platform**
 - All Devices, OS and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This broke on 4.14 as it is working on https://4130-beta0-enterprise.demo.design.infor.com/components/modal/example-full-content.html

**Comment by brianjuan** [comment]
http://4150-rc0-enterprise.demo.design.infor.com/components/modal/example-full-content.html
Passed QA testing on all browsers.
