### ISSUE TITLE
Example Code for "Track Dirty" in a modal

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#1567]
Do you have an example of using the "track dirty" functionality of a text input field when shown inside a modal popup? I'm trying to get this to work, having added the icon to the page and also adding the 'data-trackdirty="true"' to the input fields, but the icon is not showing when the field is changed and I tab out in the same way that it does when used on the main form. We are using version 4.14 of the controls. I was looking for an example to use to check if I needed any extra classes or method calls but I cannot seem to find one.

**Comment by tmcconechy** [comment]
If you use the initializer it should pick up `data-trackdirty="true"` https://github.com/infor-design/enterprise/blob/master/src/behaviors/initialize/initialize.js#L219

But if you dont use that you would just need to call `.trackdirty()` on the input in question. For example

```
$('input').trackdirty();
```

Dont have any examples of it on a modal but should be same as a form. http://latest-enterprise.demo.design.infor.com/components/trackdirty/example-index.html

**Comment by sanx72** [comment]
Thanks Tim, the content of the modal is dynamic, and as the rest of the layout was OK, I'd assumed that the modal control was automatically calling the initialise method on the content, that's the missing piece I needed to get it working.
