### ISSUE TITLE
Selected radio button within an accordion is not rendered

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#1568]
**Description**
When using radio buttons within an accordion, the selected radio button is not rendered. 

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/accordion/example-index?font=source-sans
2. Expand "Sort By"

The selected value, "Price: Low – High", is not rendered correctly. If highlighting where the text should be, radio button appears.

**Expected behavior**
Selected radio is rendered

**Version**
ids-enterprise: 4.14

**Comment by tmcconechy** [comment]
I noticed this before too. Its wierd if you click the radios then it renders again.

**Comment by EdwardCoyle** [comment]
We discovered that the changes I've made for fixing #1014 also seem to fix this issue, so we're picking it up for the March sprint and closing it off along with that.  Will be PR-ing the fix shortly

**Comment by janahintal** [comment]
QA Passed. Moving to Done. 
Verified in: https://4170-beta0-enterprise.demo.design.infor.com/components/accordion/example-index.html across all Devices, OS and Browsers
