### ISSUE TITLE
Notification: Notification cannot be dismissed in Firefox

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1573]
**Describe the bug**
Notification: Notification cannot be dismissed in Firefox

**To Reproduce**
1. Go to https://4150-beta0-enterprise.demo.design.infor.com/components/notification/example-index.html using Firefox browser
2. Click on 'X' button of the notifications
3. See issue: Notifications were not dismissed

**Expected behavior**
Notification should be dismissed when X button is clicked

**Version**
- ids-enterprise: v4.11.0 to v4.15.0-beta0

**Screenshots**
No screenshots applicable

**Platform**
 - Mac Firefox, Windows Firefox, Android Firefox

**Additional context**
No additional context.

**Comment by brianjuan** [comment]
Hi, issue still exists on http://localhost:4000/components/notification/example-index.html and http://master-enterprise.demo.design.infor.com/components/notification/example-index.html using Firefox

**Comment by tmcconechy** [comment]
I think this wasnt actually merged yet https://github.com/infor-design/enterprise/pull/1869 will move it back to inprogress then move it back to ready when its really done

**Comment by tmcconechy** [comment]
Apparently this is not fixed yet so reopening.

**Comment by brianjuan** [comment]
http://4180-beta0-enterprise.demo.design.infor.com/components/notification/example-index.html
Passed QA testing on Firefox browsers, moving to Done.
