### ISSUE TITLE
Datagrid colorpicker not selected icon is cut off and there is white background in the cell when in high contrast

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1574]
**Describe the bug**
Datagrid colorpicker not selected icon is cut off and there is white background in the cell when in high contrast

**To Reproduce**
1. Go to https://4150-beta0-enterprise.demo.design.infor.com/components/datagrid/test-editable-colorpicker.html
2. switch to high contrast
3. In the color picker column, edit one cell
4. Select NONE in the color options
5. Notice that the photo or icon is cut off and there is white background in the cell

**Expected behavior**
Cell color should be the same in the background and the NONE icon should not be cut off

**Version**
4.15.0

**Screenshots**
<img width="859" alt="screen shot 2019-01-31 at 12 41 51 pm" src="https://user-images.githubusercontent.com/45757016/52031240-89279a80-2556-11e9-9844-7dc4d4dac332.png">

should be something like below
<img width="856" alt="screen shot 2019-01-31 at 12 45 16 pm" src="https://user-images.githubusercontent.com/45757016/52031257-95abf300-2556-11e9-93a1-71eff2f0d632.png">

**Platform**
All OS, Browsers and devices 

**Additional context**
No additional context

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
