### ISSUE TITLE
Datagrid dropdown : cell has is a unnecessary tooltip when trying to search in the field

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1575]
**Describe the bug**
Datagrid dropdown : cell has is a unnecessary tooltip when trying to search in the field

**To Reproduce**
1. Go to https://4150-beta0-enterprise.demo.design.infor.com/components/datagrid/test-editable-dropdown-objects.html
2. In the Units column, select one cell then input 'm'
3. Notice that the cell expand and there is unnecessary tooltip displayed

**Expected behavior**
Unnecessary tooltip should not appear

**Version**
v4.15.0

**Screenshots**
<img width="1276" alt="screen shot 2019-01-31 at 1 13 13 pm" src="https://user-images.githubusercontent.com/45757016/52032010-13bdc900-255a-11e9-87e1-10f641519c66.png">

**Platform**
All browser, OS and devices. 
Tested in Chrome MacOS

**Additional context**
No additional context

**Comment by tmcconechy** [comment]
Maybe just need to add `autocomplete="off"` to the generated input.

**Comment by janahintal** [comment]
QA Passed. Will Move to Done. Thanks
Tested in: http://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-dropdown-objects.html across all browser, OS and devices
