### ISSUE TITLE
Popover: Layout issues in Windows IE when theme is changed

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1577]
**Describe the bug**
Popover: Layout issues in Windows IE when the theme is changed.

**To Reproduce**
1. Open Windows IE
2. Go to
     https://4150-beta0-enterprise.demo.design.infor.com/components/popover/example-index.html
     https://4150-beta0-enterprise.demo.design.infor.com/components/popover/example-extra-css-class.html
     https://4150-beta0-enterprise.demo.design.infor.com/components/popover/example-alternate-positions.html
3. Open the Popover, then close
4. Change the theme to either Dark or High Contrast
5. Open the Popover again
6. See issue: There will be layout issues inside the Popover

**Expected behavior**
Popover layout and content should be displayed correctly in Windows Internet Explorer

**Version**
- ids-enterprise: v4.14.0 to v4.15.0-beta0

**Screenshots**
https://4150-beta0-enterprise.demo.design.infor.com/components/popover/example-index.html
<img width="733" alt="screen shot 2019-01-31 at 4 31 05 pm" src="https://user-images.githubusercontent.com/39508864/52041527-a3bd3c00-2575-11e9-83c8-227aaf683d28.png">

https://4150-beta0-enterprise.demo.design.infor.com/components/popover/example-extra-css-class.html
<img width="857" alt="screen shot 2019-01-31 at 4 31 48 pm" src="https://user-images.githubusercontent.com/39508864/52041559-bf284700-2575-11e9-823a-d56a58f26b7b.png">

https://4150-beta0-enterprise.demo.design.infor.com/components/popover/example-alternate-positions.html
<img width="838" alt="screen shot 2019-01-31 at 4 33 46 pm" src="https://user-images.githubusercontent.com/39508864/52041656-06aed300-2576-11e9-89f5-8c2ccd78941b.png">

**Platform**
 - Windows Internet Explorer

**Additional context**
No additional context

**Comment by tmcconechy** [comment]
Should fix this along with #1576

**Comment by tmcconechy** [comment]
Descoping this issue for now
