### ISSUE TITLE
File Upload Send Select File link button highlight still visible after upload in Windows 10 IE 11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1578]
**Describe the bug**
File Upload Send Select File link button highlight still visible after upload in Windows 10 IE 11

**To Reproduce**
1. Go to https://4150-beta0-enterprise.demo.design.infor.com/components/fileupload-advanced/example-send.html
2. Click on 'Select Files' link button
3. Upload a File

**Expected behavior**
Square box or highlight should not appear anymore after file upload

**Version**
4.15.0

**Screenshots**
<img width="1085" alt="screen shot 2019-01-31 at 5 03 01 pm" src="https://user-images.githubusercontent.com/45757016/52043289-47a8e680-257a-11e9-850e-51b435e3bcb2.png">

**Platform**
Windows 10 
Browser: IE 11

**Additional context**
No additional context

**Comment by tmcconechy** [comment]
This is almost not an issue as this is the focus state on the link. But this can be improved by adding `hide-focus` behavior to the link.

**Comment by tmcconechy** [comment]
Descoping this issue for now
