### ISSUE TITLE
Modal validation for the email field not showing up

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1579]
**Describe the bug**
Modal validation for the email field not showing up

**To Reproduce**
1. Go to https://4150-beta0-enterprise.demo.design.infor.com/components/modal/example-validation.html
2. Click on 'Add Context'
3. Hover thru each tab and wait for the required field validation to show
4. Notice that the email field didn't show any 'Required' validation 

* Note: Required validation will only when you do 'Tab' for each field without populating 

**Expected behavior**
Required Validation should appear 

**Version**
v.4.15.0

**Screenshots**
<img width="851" alt="screen shot 2019-01-31 at 6 37 12 pm" src="https://user-images.githubusercontent.com/45757016/52048838-4a5e0880-2587-11e9-8f58-b0e396a76f4d.png">

![modal email validation](https://user-images.githubusercontent.com/45757016/52049755-86926880-2589-11e9-912f-1c08bd35808a.gif)

**Platform**
All Browser, OS and Devices.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This is just an example issues (Can fix maybe when continuing on #1136).
This validation on the field is set to `keydown` only. Can just remove that so it behaviors correctly.

**Comment by tmcconechy** [comment]
Similar to https://github.com/infor-design/enterprise/issues/1701

**Comment by tmcconechy** [comment]
Seems this was fixed along the way
