### ISSUE TITLE
Context Menu breaks touch interaction in iOS

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#1580]
**Describe the bug**
When an area has a `soho-context-menu`, nothing in that area is scrollable or clickable in iOS (webview, chrome & safari)

**To Reproduce**
https://github.com/anhallbe/ids-repro/blob/context-menu/src/app/app.component.html
Given a site with the code above:
1. Try to scroll in the widget
2. Try to click an item

Nothing happens, unless the context menu is opened (long-click then scroll).

**Expected behavior**
Can scroll and click.

**Version**
- ids-enterprise-ng: 4 & 5

**Platform**
 - Device: iPhone & iPad
 - Browser Name: Safari, Chrome, WebView

**Additional context**
Works fine on Android, Windows and MacOS. Safari & Chrome.
Related: https://jira.infor.com/browse/LIME-4269

**Comment by tmcconechy** [comment]
@anhallbe this is older - sorry.

But tested this and it seems ok now. Probably because at some point we changed this line

https://github.com/infor-design/enterprise/blame/b5224799f5ad74cefea34c6950f3a89a3f1f8efc/src/components/popupmenu/popupmenu.js#L944

**Comment by tmcconechy** [comment]
note to QA: to test long press is opening the context menu you must use a real device or xcode simulator (browserstack does not allow this)

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/contextmenu/example-page-rightclick.html?
![Large GIF (1192x712)](https://user-images.githubusercontent.com/56722184/93593188-3712e180-f9e6-11ea-809f-954674b9eb96.gif)
