### ISSUE TITLE
Block Grid: Can't see block grid outline on high contrast

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1581]
**Describe the bug**
Block Grid: Can't see block grid outline on high contrast

**To Reproduce**
1. Go to url: http://4150-beta0-enterprise.demo.design.infor.com/components/blockgrid/example-index.html
2. Click on the more icon on the top right hand corner of the page
3. Select "High Contrast"
4. Block Grid: Can't see block grid outline on high contrast. Please see screen shot attached. 

**Expected behavior**
On high contrast the outline of the block grid should be visible.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="937" alt="block grid" src="https://user-images.githubusercontent.com/39101346/52077497-225aaf00-255f-11e9-8fd4-680cc6babfa4.png">

**Platform**
- Browser Name [All browsers]

**Additional context**
None

**Comment by tmcconechy** [comment]
I think change the request so it shows a different color box that shows on all 3 themes.
Or find some other placeholders or use the ones in app/www/images (stones maybe)
