### ISSUE TITLE
Color Picker: when you type in the word "None" for custom label the color gray appears

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1582]
**Describe the bug**
Color Picker: when you type in the word "None" for custom label the color gray appears

**To Reproduce**
1. Go to url: http://4150-beta0-enterprise.demo.design.infor.com/components/colorpicker/example-custom-labels.html
2. Click inside the Color Picker (custom label)
3. Select a color from the color picker palette 
4. Click inside the field box and remove the text
5. Type in the word "none" and click on the enter key
6. the color gray appears. Please see screen shot attached. 

Note: `None` works `none` does not.

**Expected behavior**
when the user types in the word "none" the None color should appear the white box with the red line. 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="525" alt="color picker none color code" src="https://user-images.githubusercontent.com/39101346/52082827-d06c5600-256b-11e9-97b6-eb021330ebdf.png">

**Platform**
 - Browser Name [Mac FF]

None

**Comment by tmcconechy** [comment]
I'm not seeing the same thing here. Im seeing the white with the X when i follow the steps (chrome and mac). Are the steps accurate - doesnt seem like it would matter if you focus the field in step 2.

**Comment by tmcconechy** [comment]
Descoping this for now.
