### ISSUE TITLE
Datagrid: Equals filter on multi-select filters like a contains filter

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1586]
**Describe the bug**
For a multi-select filter the values are placed within an array, but similar values like "Assemble" and "Assemble Paint". If you select "Assemble Paint" then also the "Assemble" rows will display

This requires that the example-filter.html file is altered so that there is an "Assemble" activity available and that at least one row is set to "Assemble"
**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/example-filter.html'
2. Click on 'Activity filter ' and set it to "Assemble Paint"

**Expected behavior**
Only "Assemble Paint" is display when selected as the filter

multi-select values are using the indexOf instead of comparing the values.

**Additional context**
          case 'equals':

            // This case is multiselect
            if (conditions[i].value instanceof Array) {
              isMatch = false;

              for (let k = 0; k < conditions[i].value.length; k++) {
                const match = conditions[i].value[k].toLowerCase().indexOf(rowValue) >= 0 && (rowValue.toString() !== '' || conditions[i].value[k] === '');
                if (match) {
                  isMatch = true;
                }
              }
            } else {
              isMatch = (rowValue === conditionValue && rowValue !== '');
            }

            break;

**Comment by tmcconechy** [comment]
Added to the sprint for QA round - thanks for the contribution @marknolaninfor

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/example-filter.html
Passed QA testing on all browsers, moving to Done.
