### ISSUE TITLE
Text area: Cannot resize resizable text area in Windows Edge, IE and iOS

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1587]
**Describe the bug**
Text area: Cannot resize resizable text area in Windows Edge, IE and iOS.

**To Reproduce**
1. Open Windows Edge, IE and iPhone browsers
2. Go to https://4150-beta0-enterprise.demo.design.infor.com/components/textarea/example-index.html
3. Enter long texts in Notes (resizable)
4. Try adjusting the size by dragging the bottom-right corner of the text area
5. See issue: Text area won't resize

**Expected behavior**
Resizable text area should be able to resize on all browsers

**Version**
- ids-enterprise: v.4.7.0 to v.4.15.0-beta0

**Screenshots**
No screenshot.

**Platform**
 - Windows Edge
 - Windows Internet Explorer
 - iPhone browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Textareas are standard Html elements and IE and IOS simply dont support resize. There is nothing we can do about this. So closing.
