### ISSUE TITLE
Datagrid: "New Row Indicator" Cannot be switched off

### ISSUE THREAD

**Issue by pjm16** [infor-design/enterprise#1589]
**Describe the bug**
The SOHO datagrid shows a "!" dirty indicator when using the datagrid.addRow() method.

In the dataGrid.gridOptions there's a flag that can be set "showDirty: false" but this isnt being used, the code continues to show the dirty indicator

**To Reproduce**
I've tried using the flag in various parts of the SOHO app & it's not being respected. For example in the "datagrid-breadcrumb.demo", try adding:

```
ngAfterContentInit() {
    // pjm
    this.dataGrid.gridOptions.showDirty =false;
  }
```

**Expected behavior**
The dirty indicator should not be shown when the "showDirty: false" flag is set in the grid options

**Version**
- ids-enterprise-ng: v4.10.0

**Screenshots**
none

**Platform**
 Windows, Chrome

**Additional context**
none

**Comment by tmcconechy** [comment]
Added this issue to the sprint because it was picked up and fixed by @ericangeles

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/example-editable.html
Passed QA testing, moving to Done.
