### ISSUE TITLE
Dropdown: Does not honor tabindex property

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#1591]
**Describe the bug**
The dropdown control does not honor the tabindex property. When the dropdown is configured to use readonly='true' and tabindex='-1', the control can be navigated to by tabbing.

**To Reproduce**
1. Use the dropdown/example-readonly.html and modify the select element to include tabindex="-1"
2. Put focus into the First Random Input field
3. Click on the Tab key to navigate to next field
4. Focus moves to the Dropdown field

**Expected behavior**
Expect when clicking on the Tab key, that the Dropdown field is skipped due to the presence of the tabindex="-1" property and focus is moved to the field following the Dropdown field.

**Version**

- ids-enterprise: v4.15.0-dev

**Screenshots**
![dropdown-tabindex](https://user-images.githubusercontent.com/20212079/52147823-7f249b00-262d-11e9-9c9f-8e7480204231.gif)

**Platform**

**Additional context**
Modified dropdown/example-readonly.html is attached.
[example-readonly.zip](https://github.com/infor-design/enterprise/files/2823223/example-readonly.zip)

**Comment by tmcconechy** [comment]
What’s the end goal? I think that read only field should be tabbable but disabled fields would not be. So maybe you just want to disable?

**Comment by fitzorama** [comment]
For Landmark, any field that is readonly is not focusable. Read only fields are not mutable and I'm not sure what benefit there is for tabbing to them. It certainly makes a difference for heads-down data entry.

**Comment by tmcconechy** [comment]
Ok seems like a valid choice but the one reason I know they should be tabbale is screen readers. The screen reader may need to tab in to read what’s in the field out.

One note on it: 
https://tink.uk/screen-reader-support-for-disabled-read-only-form-fields/

But I get it could be useful for data entry

**Comment by fitzorama** [comment]
Good point about 508.

**Comment by brianjuan** [comment]
https://4170-beta0-enterprise.demo.design.infor.com/components/dropdown/example-readonly.html
Passed QA testing on all browsers, moving to Done.
