### ISSUE TITLE
Input: Add styles for browser autocomplete

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1593]
**Describe the bug**
When using the browser auto fill feature it sets colors on the fields that looks a little off putting. Its possible to style this so maybe we should.

**To Reproduce**
1. Go to url: http://4150-rc0-enterprise.demo.design.infor.com/components/input/example-index.html
2. Type in your name or something that you might have already as auto fill in the browser.
3. See view the screen shot attached. Its using browser default auto fill styles.

**Expected behavior**
Autocomplete on dark contrast could do with some adjustments. Please reference screen shot attached.  

**Version**
- ids-enterprise: [noticed when testing v4.15.0]

**Screenshots**
![screen shot 2019-02-04 at 11 18 55 am](https://user-images.githubusercontent.com/39101346/52221345-f6953d00-286e-11e9-87e0-cc10fab271fa.png)

**Platform**
- All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
We could style these per theme https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/ by using `-webkit-autofill`. Check with design on how this might look? Maybe a light azure highlight.

**Comment by tmcconechy** [comment]
Descoping this for now.
