### ISSUE TITLE
Locale: Allow Mixed locales on the same page (LTR Dropdown on RTL page)

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#1594]
Hi,

(Bases on Enterprise 4.14)
Hope that I'm writing in the correct place :)

We have an RTL page (he-IL locale), with some dropdowns components.
However, we need to have the dropdowns in LTR direction (en-US).
If I initialize the body to `he-IL`, and then initialize the dropdown to `en-US`, the whole page switches to `en-US`.
Please see example: [https://jsfiddle.net/sebulbajoe/8zj6gdmx/](url)
The page loads with he-IL, and after 5 seconds it switches the dropdown component to en-US.

I couldn't find a DOM element that I can change the direction to ltr **only** for the dropdown.

I was able to change it only once, using the JQuery command `$(".dropdown-list").css("direction","ltr")`, but I need that the dropdown list will be triggered for it to work.

Is there a work around for this issue?

Thanks,
Jonathan

**Comment by tmcconechy** [comment]
I dont think this is going to work the way it is presently constructed. I think the only workaround would be to put the LTR component in an iframe or something. Either that or reverse the RTL css for it in your custom css.

**Comment by tmcconechy** [comment]
Descoping this issue for now - too difficult. But we might be able to do it when we move to web components.
