### ISSUE TITLE
Datagrid filter dropdown overflows page when column is at the edge of the page and a value is long

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#1604]
**Describe the bug**
When the column is next to the edge of the browser, the filter dropdown's popup can overflow the page.  when there is a long value in it. This means that the scrollbar doesn't appear and some values could be cut off.

**To Reproduce**
1. Copy the attached
[example-filter.zip](https://github.com/infor-design/enterprise/files/2837803/example-filter.zip)
 to components/datagrid and navigate to it.
3. Open the dropdown filter for the status column.
4. See that the popup is overflowed off the page.

**Expected behavior**
The popup doesn't get overflowed off the page.

**Version**

- ids-enterprise: 4.16.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/52365706-aef8e780-2a0d-11e9-8270-1aaf75f05f9e.png)

**Platform**
 - All

**Additional context**
Happening in mobile and desktop

**Comment by janahintal** [comment]
Hi, I will re-open the issue. Dropdown filter still overflow after minimizing the screen. 

Please see screenshots below. 
Thank you. 

<img width="923" alt="Screen Shot 2019-03-21 at 5 07 25 PM" src="https://user-images.githubusercontent.com/45757016/54742608-de019c00-4bfc-11e9-901c-5c3c582ea2b9.png">
<img width="772" alt="Screen Shot 2019-03-21 at 5 08 12 PM" src="https://user-images.githubusercontent.com/45757016/54742610-dfcb5f80-4bfc-11e9-8ef6-956d22bee658.png">

**Comment by tmcconechy** [comment]
@janahintal Im not sure what you mean here? Everything in the screen shots looks ok (not sure why the error is on top the dropdown but i dont see that). Its OK for the dropdown to change position as long as it doesnt become invisible off the right of the page and its not doing that.

**Comment by tmcconechy** [comment]
Moving back to retest, we dont see anything wrong with the functionality.

**Comment by brianjuan** [comment]
Thanks for clarification @tmcconechy, the issue is now fixed, dropdown is not being cut-off in the edge. Moving to Done.
