### ISSUE TITLE
LookUp does not allow to change the selected Value

### ISSUE THREAD

**Issue by cshirole** [infor-design/enterprise#1607]
**Describe the bug**
When I select a value on single select lookup and try to change it the popup opens and closes immediately. 

**To Reproduce**
1. Go to Confugure Page
2. Click on Lookup and select a value
3. Click the save button
4. Reopen the configure page and try to change the lookup value.

**Expected behavior**
The lookup should remain open until I select another value/change lookup value.

**Comment by tmcconechy** [comment]
Whats the "configure page". Do you mean this example: https://latest-enterprise.demo.design.infor.com/components/lookup/example-index.html 

We dont have a save button on it

Maybe you have to modify our example in order to reproduce something?

**Comment by cshirole** [comment]
[LookUp Issue.zip](https://github.com/infor-design/enterprise/files/2841589/LookUp.Issue.zip)
 
[infor.AuditingandMonitoring.AuditTransactionCountBySeverity.zip](https://github.com/infor-design/enterprise/files/2841605/infor.AuditingandMonitoring.AuditTransactionCountBySeverity.zip)

Save button is on the configure Page. I have attached a recording and the widget zip file for your reference. Please let me know if I still need to give you an example.

**Comment by tmcconechy** [comment]
Yeah im going to need a sample. Try and take the lookup example and edit it so it resembles your case.
I dont have a way to run home pages to reproduce issues so we need it broken down into a reduced test case. For example a Js Fiddle or sample page we can drop into our project and run.

You can fork this project and try and edit the lookup examples so your case is shown.
https://github.com/infor-design/enterprise

**Comment by gushanson** [comment]
I suggest closing this issue and reference this: https://github.com/infor-design/enterprise-ng/issues/351

**Comment by cshirole** [comment]
[lookup.zip](https://github.com/infor-design/enterprise/files/2845109/lookup.zip)

HI @tmcconechy Please take a look at this example, You just need to unzip the files in ./src/app/lookup

**Comment by tmcconechy** [comment]
Closing this in favor of https://github.com/infor-design/enterprise-ng/issues/351
