### ISSUE TITLE
Datagrid: Add option to disable rows from selection depending on item property

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#1614]
**Is your feature request related to a problem? Please describe.**
Would like to be able to disable rows from being selected.

```
{
	id: "selectionCheckbox",
	sortable: false,
	resizable: false,
	formatter: Soho.Formatters.SelectionCheckbox,
	align: "center"
}
```

**Describe the solution you'd like**
* Use a function to determine if a row is disabled (true or false on metadata)
* dim the entire row with some opacity
* block selection / activation with both the row.

**Describe alternatives you've considered**
- using the isReadonly column function is disabled for selection checkboxes

**Additional context**
- similar to https://github.com/infor-design/enterprise/issues/1590

**Comment by tmcconechy** [comment]
You can conditionally make a cell readonly with the isReadonly function. But im not 100% certain if this will work on selection checkbox because depending on your mode you may still be able to click the row to select it. https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-readonly-links.html#L42-L50

We would have to format this issue as an enhancement i think to disable rows from selection.

**Comment by guoliang** [comment]
was isReadonly setting property introduced in a later version? I don't seems to get it to work on 4.9.1

**Comment by guoliang** [comment]
Does not work with the checkbox. I found this [issue](https://github.com/infor-design/enterprise/issues/1590). It sounds what I am looking for

**Comment by tmcconechy** [comment]
I can see it is disabled for selection checkbox:
https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L3174

Soo, I think it wont work on that column as you can also select the row. So we probably need a disabled rows feature. Can you reformat the ticket with the Feature request template? https://github.com/infor-design/enterprise/issues/new?template=feature_request.md

**Comment by tmcconechy** [comment]
Yeah sort of like #1590 but i think this was descoped at one point. The idea we had for the feature was "disabled rows".

- Use a function to determine if a row is disabled (true or false on metadata)
- dim the entire row
- block selection / activation.

That ticket is just about the button format, but similar.

**Comment by tmcconechy** [comment]
@ericangeles This is what i suggest as a starting point

1. add a disabled() function on the column that you can assign a function to like the isReadonly one
1. in the example add some phoney logic to disable a few rows
1. add a class is-disabled from the row
2. dim the row with disabled opacity and the checkbox too
3. if you try to select a row and its is-disabled return out.

**Comment by tmcconechy** [comment]
@ericangeles Should we put this back in the backlog or are you still working on it?

**Comment by guoliang** [comment]
Hi, I tried out the feature and it works, but I want it still to allow rows to be selected if I do it in the code.
That is, if I use `Datagrid.selectRows(...)` then it still allow row to be selected. I'm unsure whether it is better to skip this [line](https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L6788) or add another parameter to `selectRows` call it forceSelect.

**Comment by tmcconechy** [comment]
OK But if the row is visually disabled I'm not sure why you would select it. I think for this the only way is add a forceSelect fourth parameter. I think that should be fine.

Probably add a new issue for that or quick PR on this.

**Comment by guoliang** [comment]
I have a wizard where I use a datagrid which has selectable properties.
User can select additional properties before continue on in the wizard.

Some properties are mandatory therefore I want them to be selected by default, and should not be unselectable therefore those rows needs to be disabled.

I can make the change.

**Comment by guoliang** [comment]
Turns out to be quite a few more changes required perhaps.

I added the optional parameter `forceSelect`, and it works. However `selectAllRows()` also calls on `selectRow()`. Further on `selectAllRows` is called when clicking on the select all icon 
![image](https://user-images.githubusercontent.com/542598/64426517-01d37400-d0af-11e9-89ab-4803d52539ec.png)

I could fix the first issue by passing `forceSelect` to `selectAllRows`. But for the second issue there is a problem. I would require a new settings property I guess. But seeing that there's already quite a number of settings properties, and it does not make sense with `forceSelect` settings property perhaps.

**Comment by tmcconechy** [comment]
As this is possibly a not normal use case maybe you can do this another way without changing a lot of things if anything. Two ideas:

1) since isRowDisabled can be a function https://github.com/infor-design/enterprise/pull/1945/files?file-filters%5B%5D=.js&file-filters%5B%5D=.png#diff-7a47cbfa760f2056d4f9b91cf583d3fcR3410 just turn the function to return true and then call select row, then set it back.
2) I think if you put `_selected = true` in the row data it will also visually select the row?

**Comment by guoliang** [comment]
That was sufficient solution, I need to this small fix in though. Since disabled/selected rows are still deselectable.
