### ISSUE TITLE
Listview: missing beforeselected event

### ISSUE THREAD

**Issue by mirekrewak** [infor-design/enterprise#1619]
**Is your feature request related to a problem? Please describe.**
There is no event beforeselected in Listview component.

**Describe the solution you'd like**
I'd like this event to be emitted before item selection to add additional code that could prevent selection e.g. modify validation errors before moving to the other item, save data before selection etc. I need it in single selection mode.

**Describe alternatives you've considered**
I checked emitted events on Listview: click and selected events and selected event is emitted before click so cannot stop selection.
There are activated and beforeactivated events emitted but they are not emitted in single selection mode.

**Comment by tmcconechy** [comment]
Do you have to decide on selection asynchronously or synchronously.

**Comment by mirekrewak** [comment]
I need an asynchronous way. It is the requested use case:
1. When selecting a next listview item, show confirmation "Data modified. Do you want to save?"  
2. Save the data if confirmed.
3. When save completes, select desired (next) listview item.
I checked other components and now I see that maybe instead of emitting beforeselected event better would be having beforeselect parameter to assign a promise or function that could handle additional logic before selecting an item (also veto a selection change) - it seems that it is done that way in Tree component.

**Comment by tmcconechy** [comment]
Descoping some older issues we wont be able to get to. But its possible this might work in 5.0 and we can revisit this when thats done.
