### ISSUE TITLE
Datagrid not showing tooltip if browser resolution change to less than 75%.

### ISSUE THREAD

**Issue by vamsibandarupalli** [infor-design/enterprise#1625]
**Describe the bug**
when we change the resolution of screen to less than 75%(in chrome) we are unable to see tooltip for datagrid text. (In IE11 when resolution is less than 120%).

**Expected behavior**
Tooltip should be displayed if text is not fit inside the dataGrid cell(Irrespective of users browser resolution).

**Version**

- ids-enterprise: v4.10.0

**Screenshots**

**Platform**

Windows 10 
chrome
 - Browser Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
This may also be fixed on the latest version with the revamp of datagrid tooltips. Can you reproduce this on this page? https://latest-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html 

That is version 4.15. I suggest testing the latest version. And if still an issue please add or point to an example where we can reproduce this. Im not 100% sure I'm testing what your saying on https://latest-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html or if there are other factors we need to see.

**Comment by vamsibandarupalli** [comment]
This got resolved by upgrading to soho 5. But one issue we got is that we are not able to selected whole text in cell. i.e when selected like below image we are only getting "Assemble Paint Ass" we need to copy whole text if user selects from start to end.

![image](https://user-images.githubusercontent.com/18053782/53863311-e14b3400-400f-11e9-830e-aff326176256.png)

**Comment by tmcconechy** [comment]
@vamsibandarupalli Im not sure about this. It seems to work when i try it. Can you make a new issue with an example and steps to reproduce and browsers and all that. 

We did have one issue where the longpress was causing issues (this would be on mobile devices or safari), this has been fixed and should be in 5.1.0 when released.

**Comment by tmcconechy** [comment]
Going to mark this issue as closed as we could never reproduce it but feel free to raise a new one about the selecting if you have a concrete way to reproduce.
