### ISSUE TITLE
Not able to select text inside datagrid cell if added "enableTooltips: true" to the SohoDataGridOptions.

### ISSUE THREAD

**Issue by vamsibandarupalli** [infor-design/enterprise#1626]
**Describe the bug**
When added "enableTooltips: true" to the SohoDataGridOptions, Not able to select and copy text inside the datagrid cell.

**Expected behavior**
Should be able to select and copy text even if we added enableTooltips to datagridoptions.

**Version**

- ids-enterprise: v4.10.0

**Platform**
 - OS Version: Windows 10 
 - Browser Name chrome
 - Browser Version  Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I tested this on https://latest-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html (which is 4.15). And i seem to be able to select the text just fine in the last column thats showing the tooltips.

We recently did a revamp of tooltips in datagrid. https://github.com/infor-design/enterprise/issues/447 
This was done end of Sept (so thats v 4.11 or later but suggest 4.15 or 4.16 when released in a few weeks)

Your version is a bit old - so i think this seems fixed.
