### ISSUE TITLE
application menu dismissOnClickMobile false doesn't work on mobile

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise#1627]
**Describe the bug**
Try to set dismissOnClickMobile to false but application menu still closes when clicking outside the menu on small screens/mobile screens

**To Reproduce**
1. Start example app inside `enterprise-ng` repo
2. Go to `app.component.html` and modify `[dismissOnClickMobile]` to be `[dismissOnClickMobile]="false"`
3. Open chrome dev tool and use device simulator and choose a phone, e.g iPhone 8
4. Click on hamburger icon to open menu and then click outside the menu. Observe that menu closes.

**Expected behavior**
`dismissOnClickMobile` false value shouldn't close the menu when clicking outside the menu. Or is it a misleading regarding to this option

**Version**
- ids-enterprise-ng: 5.0.0

**Screenshots**
**N.A.**

**Platform**
 - Device: **N.A.**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version Version: 72.0.3626.96 (Official Build) (64-bit)

**Additional context**
There should be at least some documentations about this option.

**Comment by tmcconechy** [comment]
Descoping this issue for now
