### ISSUE TITLE
Hierarchy redesign. New "stacked" design implementation

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#1629]
**Describe the solution you'd like**
- Creating a stacked hierarchy view that is similar in functionality and flow to ms teams.
- Add deprecation notifications and notes for future deprecation of older hierarchy layouts.

New control will support existing features and continue to support older versions of hierarchy layout until a future TBD date.

Should still provide and support the following functionality:

1. Responsive behavior
2. A visual indicator for paging throw nodes (expand/collapse)
3. Menu button to display more details and a context menu

**Additional context**
![hierarchy-stacked](https://user-images.githubusercontent.com/1056684/52739784-42df2c00-2f97-11e9-8815-51710cc7cf53.png)

**Comment by tmcconechy** [comment]
Moving this into the sprint for QA

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
