### ISSUE TITLE
E2e Visual Tests: Create custom docker container for less setup

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1631]
**Is your feature request related to a problem? Please describe.**
Right now we have to pull the generic travis ci docker container and set it up per install. It'd be nice to have our own custom container ready to go.

**Describe the solution you'd like**
Use the existing docker container to create a custom container with all of the setup already included, including adding volume-linking to a users's local `enterprise/test/baseline` and `enterprise/test/.tmp` folders.

**Describe alternatives you've considered**
Leaving it alone.

**Additional context**
If anyone wants to take a stab at docker stuff, feel free to play around!

**Comment by tmcconechy** [comment]
Me and Dave had also discussed doing this but didn't get around to it. 

1. Should include the downloads for nvm, node, chrome ect as per https://github.com/infor-design/enterprise/blob/master/docs/TESTING.md#setting-up-the-docker-environment
1. Post it up to docker https://hub.docker.com/
1. Update instructions
1. cloned repo perhaps on /

But how does the "volumn-linking" work? I didn't do that on mine.

**Comment by clepore** [comment]
More info here: https://stackoverflow.com/questions/50022550/get-screenshot-of-failed-tests-from-travis-ci

**Comment by tmcconechy** [comment]
Also here https://blog.travis-ci.com/2012-12-18-travis-artifacts

**Comment by clepore** [comment]
I created this issue for just the artifacts task: https://github.com/infor-design/enterprise/issues/1953

**Comment by tmcconechy** [comment]
We did this.... https://hub.docker.com/r/infords/travis/tags
