### ISSUE TITLE
Step Process Control folder should not be selectable

### ISSUE THREAD

**Issue by boehmd1** [infor-design/enterprise#1633]
**Describe the bug**
Stepprocess expanding or collapsing a folder show the step as being select, this leaves a disconnect with the end user on what step is slected and what is showing in the step panel frame.

**To Reproduce**
1. Go to http://localhost:4000/patterns/stepprocess-markup.html#profile
2. Expand/collapse folder

**Expected behavior**
The folder should not be selected

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to QA Failed. On Windows 10 IE 11  when the user clicks on the 3 dotted button on the top left hand side of the page; the designer application list is gone and there's no way to view the list unless you click on the Previous or Next button. Please see screen shot attached.
![bs_win7_ie_11 0 1](https://user-images.githubusercontent.com/39101346/53350425-0bed0c80-38ed-11e9-92b8-58ad331ba545.jpg)

**Comment by tmcconechy** [comment]
Also check out https://github.com/infor-design/enterprise/issues/1662 @boehmd1 if you can when fixing this.

**Comment by boehmd1** [comment]
This bug seems unrelated to this fix.

**Comment by tmcconechy** [comment]
No its not but it will pretty up the step process a bit if you're in there anyways.

**Comment by boehmd1** [comment]
Sorry Tim. I meant the bug reported by CindyMercadoReyes, the IE 11 issue

**Comment by tmcconechy** [comment]
Yeah it could have already been there. Does Landmark care if this pattern works on IE 11?

**Comment by boehmd1** [comment]
Yes, I can try to take a look at this too.  Would like it to be a different ticket, keep it separate form the Header Selection issue.

**Comment by tmcconechy** [comment]
OK i was thinking it might not be that important on IE tho? Because they dont run it mobile size on IE. Thinking we should make a new ticket too and prioritize.

@CindyMercadoReyes Can you make the IE issue a new ticket and close this as its unrelated.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
