### ISSUE TITLE
Notification : Cant change themes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1639]
**Describe the bug**
You cannot test notifications with the theme switcher. This may be a demo app issue, it looks like the notifications should go into the body section container instead ( this may also need a notification.js update ).

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/notification/example-index.html
2. Click on the '....'  button
3. Notice it doesnt work.

**Expected behavior**
Should be able to change theme.

**Version**
4.15

**Additional context**
See #1636 also.

**Comment by tmcconechy** [comment]
Same as https://github.com/infor-design/enterprise/issues/1573

**Comment by EdwardCoyle** [comment]
I'm going to mark this one fixed alongside #1893.  The problem with the sample is the Notifications are getting put in the wrong spot, and there is an element overlapping the header, causing the button not to be clickable.

**Comment by brianjuan** [comment]
Hi, issue still exists on http://master-enterprise.demo.design.infor.com/components/notification/example-index.html and http://localhost:4000/components/notification/example-index.html

**Comment by brianjuan** [comment]
https://4171-rc1-enterprise.demo.design.infor.com/components/notification/example-index.html
Passed QA testing on all browsers.
