### ISSUE TITLE
selectRow and unselectRow can alter a checkbox that is not the selectionCheckbox

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1641]
**Describe the bug**
The method to find the selectionCheckbox can result in a cellnode that is not the selection checkbox from being selected and then altered.

If there is no selectionCheckbox columns then, self.columnIdxById('selectionCheckbox') will return -1, but the cellNode method will return the last column node for the row. If this is a checkbox then the checkbox will change.

self.cellNode(elem, self.columnIdxById('selectionCheckbox'));

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/example-singleselect.html'
2. Click on any row to select the row

**Expected behavior**
Only the selectionCheckbox should change and not any other checkbox on the grid

**Version**
4.16.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/52921602-c9fe1c80-3368-11e9-99aa-d4561153a030.png)

**Comment by tmcconechy** [comment]
Adding to sprint to QA as this was added by an external contributor.

**Comment by brianjuan** [comment]
http://4160-beta0-enterprise.demo.design.infor.com/components/datagrid/example-singleselect.html
Passed QA testing on all browsers.
