### ISSUE TITLE
Datagrid Multi-line field not expanding while entering text

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#1643]
**Describe the bug**
For multiline fields in Datagrids, as user is entering lines of text, the cell is not expanding thus, some lines of text are being cropped. Although, the cell will expand once user focuses out of the cell.

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/test-long-text.html'
2. Enter some lines of text in the multiline "Activity" column
3. As user is typing several lines, the cell is not expanding cropping out the first lines of text. The cell will expand after user focuses out of the cell.

As User is still typing:
![image](https://user-images.githubusercontent.com/41028784/52980802-ea84b000-3416-11e9-8726-5ecfb9dc98e3.png)

After focusing out:
![image](https://user-images.githubusercontent.com/41028784/52980847-1d2ea880-3417-11e9-84b3-cf78ea691d36.png)

**Version**
Version: 4.16.0-dev

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome

**Comment by tmcconechy** [comment]
What editor did you use? Probably this wont be easily fixable. I think it's acceptable if the cell expands when its done typing. And scrolls while editing initially.

**Comment by NathanLouisBarcial** [comment]
Hi @tmcconechy the editors used is Editors.Textarea

Yes, the scroll while editing might be okay, but one issue we're encountering with this is once we focus out of the cell and try to edit again a cell with multiple lines, the height of the row is still retained and the scroll bar is cropped:

![image](https://user-images.githubusercontent.com/41028784/53056504-64d03580-34e6-11e9-8d1a-de954a68d2d1.png)

**Comment by tmcconechy** [comment]
Gotcha - yeah this seems like something we should address.

**Comment by NathanLouisBarcial** [comment]
Alright, thanks Tim.

**Comment by tmcconechy** [comment]
Think this is now completed
