### ISSUE TITLE
CSS: Use ids-identity header tokens

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1646]
**Is your feature request related to a problem? Please describe.**
Header specific tokens are not yet used in Enterprise.

**Describe the solution you'd like**
Replace the current private header variables in Enterprise SASS with their token equivalents:
- https://github.com/infor-design/design-system/issues/283

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tmcconechy** [comment]
Descopint this issue as it is ongoing work anyways
