### ISSUE TITLE
SpinBox is cropped inside Expandable Area when viewed in Mobile or Smaller Screen

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#1647]
**Describe the bug**
SpinBox is cropped inside Expandable Area when viewed in Mobile or Smaller Screen. This is just minor issue on our end but is raised to us when our app is viewed on mobile.

**To Reproduce**
1. Go to 'http://localhost:4000/components/expandablearea/test-switches.html'
2. Add another div to the html, and set the first div to ten columns only.

`<div class="two columns">

    <div class="expandable-area">

      <div class="expandable-header">
        <span class="title">SpinBox</span>
      </div>

      <div class="expandable-pane">

        <div class="row">
          <div class="twelve columns">

			<div class="field">
				<label for="regular-spinbox">Spinbox (min: 0, max: 10)</label>
				<input id="regular-spinbox" name="regular-spinbox" type="text" class="spinbox" data-options="{min: 0, max: 10}"/>
			</div>

          </div>
        </div>

      </div>
    </div>

  </div>`

3. The output layout should be like this:
![image](https://user-images.githubusercontent.com/41028784/53057971-479e6580-34ec-11e9-8011-3cd889b718e2.png)

4. Now, when this is viewed in mobile:

![image](https://user-images.githubusercontent.com/41028784/53057984-571dae80-34ec-11e9-9c84-e00c73b98d23.png)

5. As you can see, the Spinbox is cropped and the "+" button is shown on another line.
6. Not a Major Issue for us, but for app's aesthetics.

**Platform**
 - Mobile: iPad Mini or smaller screen devices.

**Comment by tmcconechy** [comment]
I think the "workaround" is to place it into a bigger size column. At this size its going to be practically unusable even if the layout issue is fixed.

**Comment by NathanLouisBarcial** [comment]
Yeah, adding columns did fix the issue, and I see your point that it will be practically unusable if layout is adjusted more. Will just inform our testers here if ever we encounter this again. This solved our issue. Thanks for the response!
