### ISSUE TITLE
About Dialog - Minor issue with Operating system showing 10 twice

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#1650]
**Describe the bug**
In the About dialog Windows 10 Operative system shows as "Windows 10 10" it should probably show Windows 10 or perhaps "Windows 10, 10.0.17763" if the build number should also be shown.

**To Reproduce**
1. On a Windows 10 computer, go to https://design.infor.com/code/ids-enterprise/latest/about
2. Click on 'Show About screen'
3. Scroll down to 'Operating system'

**Expected behavior**
Operating system should probably show "Windows 10" or perhaps "Windows 10, 10.0.17763" if the build number should also be shown.

**Version**

- ids-enterprise: 4.15.0 (and 4.14.0)

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/53147223-2d758d80-35a7-11e9-9453-93c3807dd972.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 72.0.3626.109 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
We should check environment.js as well as the mapping in about.js

**Comment by tmcconechy** [comment]
Lets fix this with https://github.com/infor-design/enterprise/issues/3073

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the done column.
