### ISSUE TITLE
Tag Input component 

### ISSUE THREAD

**Issue by rishni** [infor-design/enterprise#1651]
**Is your feature request related to a problem? Please describe.**
Our project needed component can enter multiple email address in the input box.  

**Describe the solution you'd like**
The expect enhancement is Tag Input component for entering multiple entries. 

**Additional context**
We currently used this component from another library for our requirement. It's https://www.npmjs.com/package/ngx-chips

![image](https://user-images.githubusercontent.com/44457011/53150013-780dfe80-35d5-11e9-8658-d7390b324363.png)

**Comment by tmcconechy** [comment]
Our multiselect component behaves different than this. We chose a different design thats a more compact field. We can consider this for some day in the future but needs design work. We did come up with this patter for search which you can use:

https://latest-enterprise.demo.design.infor.com/examples/landmark/search-form.html
- you have to do the work on it but idea is when you search you just add more tags.

**Comment by EdwardCoyle** [comment]
@rishni If you're still in need of an IDS component for working with Tags for selection, we've recently implemented the Tag workflow into our Multiselect, as of #3116 

I'm going to close this issue for now, but feel free to open another if the new system is lacking any functionality you need.
