### ISSUE TITLE
Lookup single select not working with async server-side

### ISSUE THREAD

**Issue by deep7102** [infor-design/enterprise#1654]
**Describe the bug**
1. Using a single select Lookup with source attribute, when a value is selected it doesn't get unselected when another value is selected. This is a visual bug, not functional.

2. Using a single select Lookup with source attribute, when a value is pre-selected, the selection dialog will automatically close when opened and the value can therefore not be changed.

**To Reproduce**
http://localhost:4000/components/lookup/
Case 1:
1. Create test page use setting to be single select and server-side with source method
2. Open lookup modal and make selection
3. It should close model and enter value to lookup input
4. Open again and select different product
5. It should close model and update value to lookup input
6. Open again and see both rows selected now (should be only one)

Case 2:
1. Now change test page to set the value attribute to be pre-selected
2. Open lookup modal
3. It open and close by it self (should be kept open till selection made)

**Expected behavior**
1. Only the active value is selected
2. The dialog remains opened, allowing for the user to select a new value.

**Additional context**
Moved from the NG project:
[infor-design/enterprise-ng#351](https://github.com/infor-design/enterprise-ng/issues/351)
[infor-design/enterprise-ng#352](https://github.com/infor-design/enterprise-ng/issues/352)

**Comment by tmcconechy** [comment]
This issue actually was fixed in time for 4.16 so moving it to that project, see test notes on https://github.com/infor-design/enterprise/pull/1655

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
