### ISSUE TITLE
Build process: Build a developer notification module/utility

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1658]
**Is your feature request related to a problem? Please describe.**
We need a way to notify developers that things are being deprecated or going away.

**Describe the solution you'd like**
1. I would like a common helper utility that we can tie into in the future to get "deprecations." Right now it can simply take some sort of object, or array of objects, and do a `console.warn()`. See [here](https://css-tricks.com/approaches-to-deprecating-code-in-javascript/) for an example of their "Obsolete" function helper.
1. Use the proper [JSDoc @deprecated](http://usejsdoc.org/tags-deprecated.html) syntax
1. Add a "Deprecation" and maybe "Pending Deprecation" sections to the changelog to list what was deprecated in that release
1. Create a `docs/` document about how deprecate a feature/method...etc

**Describe alternatives you've considered**
n/a

**Additional context**
Informational links:
- https://css-tricks.com/approaches-to-deprecating-code-in-javascript/
- https://www.npmjs.com/search?q=deprecations

**Comment by EdwardCoyle** [comment]
Should probably use #1747's deprecation of the `font` setting in personalize.js as a potential jumping off point for this one.

**Comment by EdwardCoyle** [comment]
@clepore @nickwynja @tmcconechy @deep7102 @davidcarlsonberg 

Some questions I had that I'm putting up for debate surrounding this issue:
1. Do we want to show browser-level warnings when deprecated code is used?  Or should we only be showing this in the build tooling?
1. When should we fully remove deprecated code?  Next major version?  2 (or more) major versions out?
1. Do we want to have some kind of open policy for the reasoning behind making deprecations?  I see a note about adding documentation for how to deprecate, but should we have something more consumer-facing about why?

**Comment by tmcconechy** [comment]
1. I would vote for noting it in the code and change log and on npm install. No console logs.
2. I was thinking 3 months (releases) would be adequate (2 would be fine too).
3. I think we should have a statement on what types of things we deprecate. Good idea

**Comment by EdwardCoyle** [comment]
Just noting that if we do decide that browser-based notifications aren't important, we can potentially tackle the console notifications pre-build with ESLint:  https://github.com/gajus/eslint-plugin-jsdoc

I saw another interesting method of build-time deprecation with Sass via a mixin:  https://www.npmjs.com/package/sass-deprecate

**Comment by davidcarlsonberg** [comment]
1. I like the idea of putting `console.warn()`'s at the browser level; similar to how Chrome warns developers of deprecations or upcoming changes or current experiments.
2. Releases makes sense to me.
3. I don't know if I'd say that a "why" justification is necessary but I do think implementing some kind of deprecation documentation would create a useful historical rationale.

**Comment by clepore** [comment]
1. Browser level warnings
    > Yes
2. Fully deprecated code timeline
    > I like 3 months, but we'll probably have to make it 6, because very few companies are actually consistently updating month-to-month
3. How/why we deprecate?
    > It is pretty obvious, but i think a small explanation in the JSDoc comments is good.

I really think the 5 steps of that [article](https://css-tricks.com/approaches-to-deprecating-code-in-javascript/#article-header-id-2) nails it (along w/ the helper module).

**Note:** For design-system, I already implemented a build time `post-install` script to log messages based on a json file of deprecations in https://github.com/infor-design/design-system/pull/319 if you wanted to see how I did that for ideas.

**Comment by nickwynja** [comment]
>     1. Do we want to show browser-level warnings when deprecated code is used?  Or should we only be showing this in the build tooling?

The important reason for having `console.warn()` is for teams who are using the library directly through `npm install` and don't build from source.

>     2. When should we fully remove deprecated code?  Next major version?  2 (or more) major versions out?  For example, we had tentatively decided to remove some deprecations in #1476 in a future 5.0 release.

I think there might be a moving scale when it comes to time for deprecation. Smaller changes with smaller impacts (if someone fails to migrate from the deprecation) might happen more quickly but major impacts might take more than one major version.

>     3. Do we want to have some kind of open policy for the reasoning behind making deprecations?  I see a note about adding documentation for how to deprecate, but should we have something more consumer-facing about why?

I think it could be worth mentioning our general approach. It might be enough to add to ` 	DEVELOPER.md`.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
