### ISSUE TITLE
StepProcess in 'linearProgression' mode not working as expected in a Responsive mode (Mobile)

### ISSUE THREAD

**Issue by boehmd1** [infor-design/enterprise#1660]
**Describe the bug**
StepProcess in 'linearProgression' mode not working as expected in a Responsive mode (Mobile).
'Save and Close' and 'Next' only available when viewing the step content.  If you view the step list, there is no way to view the next step or to save and close the step control.

**To Reproduce**
Use the StepProccess.demo.html
1. change it use the linearProgression true

**Expected behavior**
1. Able to move to the next step when viewing the list of steps
2. Able to save and close when viewing the list of steps.

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by deep7102** [comment]
Hi @boehmd1 I cannot reproduce this issue. Please test again at your end to see if you still have this issue.
http://localhost:4200/ids-enterprise-ng-demo/step-process
I added `linearProgression = true` to `stepprocess.demo.html`

**Comment by boehmd1** [comment]
This was fixed in the enterprise-ng

**Comment by janahintal** [comment]
Hi @tmcconechy, may we know how and where can we test this issue on our end? Thanks.

**Comment by tmcconechy** [comment]
There wasn’t any test made available for this fix

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. There is no way to QA test this ticket.
