### ISSUE TITLE
Step Process Component: Focus is cut off on the 3 dot button

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1662]
**Describe the bug**
Step Process Component: Focus is cut off on the 3 dot button

**To Reproduce**
1. Go to url: http://4160-beta0-enterprise.demo.design.infor.com/patterns/stepprocess-markup.html#profile
2. Click on 3 dot button on the top left hand side of the UI
3. The focus is cut off each time you click on the button
4. See screens shot attached. 
5. Also the icons are extra large on the tree/accordion

**Expected behavior**
The focus state should cover the whole button

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="838" alt="step process conponent" src="https://user-images.githubusercontent.com/39101346/53349451-1c9c8300-38eb-11e9-801c-69a738369093.png">

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [iOS 8]
 - Browser Name [Chrome]

**Additional context**
None

**Comment by janahintal** [comment]
QA Failed. The Three Dot button in the upper right corner for Previous and Next is not showing when minimized or in mobile view. Please see below. 

Tested in: https://4160-rc0-enterprise.demo.design.infor.com/patterns/stepprocess.html

<img width="398" alt="screen shot 2019-03-05 at 4 06 28 pm" src="https://user-images.githubusercontent.com/45757016/53790297-9c68c400-3f61-11e9-9ef3-a78d14c7c202.png">

**Comment by tmcconechy** [comment]
@janahintal - Im not 100% sure what you mean. I think you mean the next and previous button UNDER the ... button is hidden on mobile. If thats the case this is the design as these may not fit this is the same in all previous versions: https://4140-enterprise.demo.design.infor.com/patterns/stepprocess.html

On mobile you can use the next button on the button or use the menu on the left to open the steps and navigate so i think its correct. Also asking @pwpatton and @boehmd1 for input.

**Comment by tmcconechy** [comment]
I suggest a new issue for anything else on this issue.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
