### ISSUE TITLE
Demo App: Create uplift mini-app to test and showcase uplift theme

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#1665]
**Is your feature request related to a problem? Please describe.**
To be able to better explore, test, and demo our uplift work, we should create a set of the most used pattern examples linked into a "mini-app". This way, when we're designing and developing the uplift in EP, we're using contextual examples of how the components look and work together in their primary use cases.

**Describe the solution you'd like**

Wiring together the following patterns and components:

* [Homepage](https://latest-enterprise.demo.design.infor.com/components/homepage/example-filled.html)
* [List Detail page](https://latest-enterprise.demo.design.infor.com/patterns/list-detail-no-split-header-toolbar.html)
* Maybe some nested tabs in the item
* Form fields in a responsive column layout
* A data grid somewhere
* Something that opens up a contextual action panel

**Describe alternatives you've considered**
n/a

**Comment by tmcconechy** [comment]
So a new page / set of linked pages off here https://latest-enterprise.demo.design.infor.com/examples/list ? Maybe?

**Comment by tmcconechy** [comment]
Descoping this now but examples will be a key part of the refactor project
