### ISSUE TITLE
SearchField: "api details" listed many times in subnav on "searchfield" page

### ISSUE THREAD

**Issue by swetteinfor** [infor-design/enterprise#1668]
![screen shot 2019-02-25 at 2 45 00 pm](https://user-images.githubusercontent.com/20357266/53364200-4b772100-390c-11e9-89bd-c5bb3bfd7f70.png)

See screenshot. or check it out on the https://design.infor.com/code/ids-enterprise/latest/searchfield page. 

desired behavior is for api details to only take one slot in the sub-nav.

**Comment by brianjuan** [comment]
Hi @tmcconechy , can we only see it fixed when 4.24.0 version is deployed in https://design.infor.com/code/ids-enterprise/latest/searchfield ? Thanks.

**Comment by tmcconechy** [comment]
Yes only when released for that page. Suggest just moving to done for now.

**Comment by brianjuan** [comment]
Thanks Tim! I'll take note of this ticket so I can verify once 4.24 is deployed.

**Comment by brianjuan** [comment]
I've retested this ticket and verified QA passed.
Tested in https://design.infor.com/code/ids-enterprise/latest/searchfield#searchfield
