### ISSUE TITLE
Dropdown not working after changing the Theme

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1670]
**Describe the bug**
Dropdown not working after changing the Theme

**To Reproduce**
1. Open Browser e.g Chrome
2. Go to 
http://4160-beta0-enterprise.demo.design.infor.com/components/dropdown/example-index.html or
http://4160-beta0-enterprise.demo.design.infor.com/components/dropdown/example-groups.html
3. Minimize the Screen 
4. Click the dropdown field and check if working
5. Change the Theme to 'Emerald' & 'High Contrast'
6. If the dropdown worked >> Change the Theme again 'Turquoise' & 'High Contrast'
7. Click the Dropdown field
8. Notice that the field is not working

**Expected behavior**
Dropdown field should still be clickable 

**Version**
- ids-enterprise: [v4.16.0]

**Screenshots**
<img width="470" alt="screen shot 2019-02-26 at 1 22 57 pm" src="https://user-images.githubusercontent.com/45757016/53389334-d702b780-39c9-11e9-93ff-64878cf0932f.png">

**Platform**
- All Browsers and OS

**Additional context**
No Additional Context

**Comment by tmcconechy** [comment]
While this issue was in past 4.14 i think this is an important issue as it means that you cant open dropdowns , then use a menu button.

**Comment by janahintal** [comment]
QA Passed. Tested in https://4160-rc0-enterprise.demo.design.infor.com/components/dropdown/example-index.html & https://4160-rc0-enterprise.demo.design.infor.com/components/dropdown/example-groups.html for all browsers and devices
