### ISSUE TITLE
Datagrid: Blank area on the right side of the grid appears after resizing a column

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1671]
**Describe the bug**
A blank area appears on the right side of the grid after resizing a column to smaller size.

**To Reproduce**
1. Go to http://4160-beta0-enterprise.demo.design.infor.com/components/datagrid/example-index.html
2. Drag the right border of Order Date column to left to resize to smaller size
3. See issue: A blank area appears next to the Phone column

**Expected behavior**
There should be no blank area in the datagrid when you resize a column

**Version**
- ids-enterprise: v4.6.0 - v4.16.0-beta0

**Screenshots**
![datagrid_blankarea](https://user-images.githubusercontent.com/39508864/53396766-3cfa3980-39e0-11e9-85e0-dfa02f2df1ec.gif)

**Platform**
 - All Devices, OS and Browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This is actually working as designed currently. Once you resize the column you go from automatic to static column size, and if the columns dont fit they wont stretch.

But leaving it open as this is a common question, i think we could also stretch the last column while resizing and that might be a better experience.

**Comment by tmcconechy** [comment]
All these 3 are closely related
https://github.com/infor-design/enterprise/issues/2130
https://github.com/infor-design/enterprise/issues/1671
https://github.com/infor-design/enterprise/issues/605

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
