### ISSUE TITLE
Line Graph: Does not display X-axis labels when its populated with only one value

### ISSUE THREAD

**Issue by cshirole** [infor-design/enterprise#1674]
Please check the attached image.

Steps to Reproduce the Issue:
1) Unzip line.demo.ts into ./src/app/line
2) Check the line graph

Expected Behavior:
Line Graph should display X-axis Labels.

**Comment by cshirole** [comment]
Hi Tim,
Just following up on this issue.

Thanks,
Chetan

**Comment by tmcconechy** [comment]
It's in the queue but not sure when someone will have a chance for it. It is up for grabs so if you wanted to contribute a fix feel free. Also vote up the issue by giving it a 👍

**Comment by jmacaluso711** [comment]
@tmcconechy Looks like there is some math being done in the build function that is cutting off the last entry.

`const entries = d3.max(dataset.map(function (d) { return d.data.length; })) - 1;`

https://github.com/infor-design/enterprise/blob/4faebd21ca120e73628c9ad5c892ca9b186939f9/src/components/line/line.js#L275

I think we can just check if there is only one entry and not subtract 1.

```
    let entries;
    if (d3.max(dataset.map(function (d) { return d.data.length; })) <= 1) {
      entries = d3.max(dataset.map(function (d) { return d.data.length; }))
    } else {
      entries = d3.max(dataset.map(function (d) { return d.data.length; })) - 1;
    }
```

**Comment by tmcconechy** [comment]
@jmacaluso711 That sounds good. I hadnt looked at this, but figured there was some mislogic in there.

I think the idea was that the line on the axis on the left should not show. Maybe it was for that but im not sure 100%. But if you give it a test and this works and the line is still hidden, then seems like a good fix and we can review.
 
![Screen Shot 2019-03-26 at 2 14 48 PM](https://user-images.githubusercontent.com/814283/55022718-951d5f00-4fd1-11e9-88eb-d3f5c137ffec.png)

And if you want to push it that would be great.
