### ISSUE TITLE
Listview: searching without "clearable" set causes no searching to occur

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1675]
**Describe the bug**
It's currently not possible to filter on a results set in a Searchable Listview if the Searchfield being used is not configured as "clearable".  This is because the `contents-checked` event that is listened to [inside the Listview](https://github.com/infor-design/enterprise/blob/4.16.x/src/components/listview/listview.js#L1403) to trigger filtering is dispatched by the [`clearable()` behavior](https://github.com/infor-design/enterprise/blob/4.16.x/src/utils/utils.js#L420)

**To Reproduce**
- Open http://master-enterprise.demo.design.infor.com/patterns/list-detail-search.html
- Find the Searchfield in the top left
- Type "task"
- Notice there is no "X" button on the searchfield.  Also notice that the results don't filter.

Adding a `clearable: true` setting to the Searchfield in that example causes it to suddenly start filtering.

**Expected behavior**
Compare to http://master-enterprise.demo.design.infor.com/components/listview/example-search.html, which is also a Listview and has `clearable: true` set on the Searchfield

**Version**
- Found as early as [v4.7.x](https://github.com/infor-design/enterprise/blob/4.7.x/src/components/listview/listview.js#L1236)
- Still present in v4.16.x

**Screenshots**
![screen shot 2019-02-26 at 10 28 02 am](https://user-images.githubusercontent.com/3249601/53424455-402a0100-39b1-11e9-8ff5-78bb3501257e.png)

**Platform**
- n/a

**Comment by EdwardCoyle** [comment]
Whoever picks this up should also go through all the List/Detail patterns in http://localhost:4000/patterns/list to double check and make sure the Search is working properly.  In some cases, they are not.

**Comment by tmcconechy** [comment]
Descoping this for now
