### ISSUE TITLE
Hierarchy stacked layout needs ability to support multi root data structure.

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#1677]
**Is your feature request related to a problem? Please describe.**
Need a way to render multiple roots. For example.

```
{
  "ancestorPath": null,
  "centeredNode": null
  "children":  [{..childrenUrl}, {..childrenUrl}, {...childrenUrl}]
}
```

**Describe the solution you'd like**
Cards will display as one level if there are multiple roots on the initial data load (see attached screenshot).

**Additional context**
![multi-root](https://user-images.githubusercontent.com/1056684/53431682-9d748100-39b6-11e9-9adf-cd45234309a6.png)

**Comment by CindyMercadoReyes** [comment]
Adding URL for testing purposes. https://4170-beta0-enterprise.demo.design.infor.com/components/hierarchy/test-multi-root.html
