### ISSUE TITLE
Alerts Component: Dirty tracker color is cut off on high/dark contrast

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1679]
**Describe the bug**
Alerts Component: Dirty tracker color is cut off on high/dark contrast

**To Reproduce**
1. Go to url: http://4160-beta0-enterprise.demo.design.infor.com/components/alerts/example-index.html
2. Click on High Contrast
3. The Dirty tracker color is cut off
4. Please see screen shot attached

**Expected behavior**
The dirty tracker color should appear correctly

**Version**
n/a

**Screenshots**
![bs_win10_ie_11 0 2](https://user-images.githubusercontent.com/39101346/53433792-1974c600-39c3-11e9-8894-f7de125d726b.jpg)

**Platform**
 - OS Version: [Windows 10]
 - Browser Name [IE 11]

**Additional context**
None

**Comment by tmcconechy** [comment]
@clepore @nickwynja - This is minor, but a regression. Should it go in design QA to get fixed? Looks like its generating an inline fill into the icon.

**Comment by nickwynja** [comment]
@tmcconechy Maybe we fix this and #1677 in a `4.16.1` patch release?

**Comment by tmcconechy** [comment]
This is actually working fine on the fields
http://4160-beta0-enterprise.demo.design.infor.com/components/input/test-dirty.html
http://4150-enterprise.demo.design.infor.com/components/input/test-dirty.html

ect...

So i dont really think this needs fixing. If anything maybe just remove it from the alerts page as its wierd on there.
