### ISSUE TITLE
Application Menu Component: Search and 3 button ellipsis button skips when the page loads

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1680]
**Describe the bug**
Application Menu Component: Search and 3 button ellipsis button skips when the page loads

**To Reproduce**
1. Go to url: http://4160-beta0-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html
2. When the page is loaded for the first time the Search and 3 button ellipsis button skips on IE 11

**Expected behavior**
Page should not skip once it's loaded

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - OS Version: [Windows 10 ]
 - Browser Name [IE 11]

**Additional context**
None

**Comment by tmcconechy** [comment]
I think the browser is just loading slow and the toolbar is drawing in and placing. I dont think there is anything we can do about this. Its probably better on a faster machine.

**Comment by tmcconechy** [comment]
Descoping this issue for now see https://github.com/infor-design/enterprise/issues/3026
