### ISSUE TITLE
Lookup Component: Pagination Issue and also extra scroll bar not needed

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1681]
**Describe the bug**
Lookup Component: Pagination Issue and also extra scroll bar not needed

**To Reproduce**
Issue 1: 
1. Go to url: http://4160-beta0-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html
1. Open the Lookup
1. Select all 
1. click ok
1. Open the lookup again
1. Click on the “Last Page” button
1. Select 215219
1. Click on “First Page”
1. All products Id’s are selected
1. All product id's should not be selected

Issue 2: Extra scroll bar not needed
1. Go to url: http://4160-beta0-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html
1. Open the Lookup
2. Select all on the look up and click enter key
3. An extra scroll bar is appearing
4. Screen shot attached,

**Expected behavior**
Issue 1: 
All product id's should not be selected
Issue 2: 
An extra scroll bar is appearing when it's not needed
**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

<img width="910" alt="lookup pagination issue" src="https://user-images.githubusercontent.com/39101346/53437964-be47d100-39cc-11e9-8c6c-acafeaa1ad09.png">

**Platform**
 - OS Version: [ iOS 8]
 - Browser Name [FF]

**Additional context**
None

**Comment by tmcconechy** [comment]
Not sure why this one was failed so moving it back to retest.

**Comment by brianjuan** [comment]
http://4160-rc1-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html
Issue 1 and 2 Passed QA testing on all browsers, moving to Done.
