### ISSUE TITLE
Calendar: Disable the new event modal when no template is defined

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1684]
**Describe the bug**
There is no way to disable the new event modal.

**To Reproduce**
1. Go to '/components/calendar/test-ajax-events.html'
2. Double Click on a date

**Expected behavior**
No modal should be defined as there is no template for the controls to allow the user to add the event.
This should either only show when a template exists, or have a way to disable to modal, eg a read-only calendar.

**Version**
master

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/53455798-ae3afa80-3a7b-11e9-8da8-17c696f2d3db.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome
 - Browser Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Adding to the sprint - but moving to done because there is nothing to QA.
