### ISSUE TITLE
Popup Menu: Disabled submenu can be opened and selected

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1687]
**Describe the bug**
Popup Menu: Disabled submenu can be opened and selected

**To Reproduce**
1. Go to https://4160-beta0-enterprise.demo.design.infor.com/components/popupmenu/example-disabled-submenus.html
2. Open Cats Menu
3. Hover on the disabled "Short-hair" submenu
4. See issue: Short-hair will be opened
5. You can also select submenus of Short-hair even though they are disabled.

**Expected behavior**
Disabled submenus should not be hovered, clicked or opened.

**Version**
- ids-enterprise: v4.15.0 - v4.16.0-beta0

**Screenshots**
<img width="830" alt="screen shot 2019-02-27 at 8 47 27 pm" src="https://user-images.githubusercontent.com/39508864/53491261-ee789800-3ad0-11e9-9c89-b8467216ba4e.png">

**Platform**
 - All Devices, OS and browsers including mobile

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This is actually correct - and the same as previous versions. Its not actually selecting the items. Its just closing the menu. You can see by the cursor that its disabled and the select event is not firing.

**Comment by brianjuan** [comment]
Hi @tmcconechy sorry to revisit this ticket, but I just noticed today upon doing a round of regression, on the previous versions (4.14.0 and lower), when you hover on the disabled Short-hair menu, its submenu doesn't open. And based on what I understand regarding "disabled" menus, it is correct that it should not be opened when hovered or clicked.

**Comment by tmcconechy** [comment]
Ok, Yes i think your right i'd agree and lean towards them not opening since they arent actionable. I noted this on a new issue https://github.com/infor-design/enterprise/issues/1863 with the version this behavior changed
