### ISSUE TITLE
Datagrid serverside filtering regression

### ISSUE THREAD

**Issue by Mincol** [infor-design/enterprise#1688]
**Describe the bug**
While server side filtering is configured, changing multi select and single select combo box filters did not called server for new Datagrid content

**To Reproduce**
1. Go to http://localhost/demo/components/datagrid/example-paging
2. Click on multi select filter (currently not in place, I intend to enrich example as part of pull request)
3. The data was not filtered and no call to server was made

**Expected behavior**
The function Datagrid.settings.source should be called, which will issue ajax call and grid is refreshed with new data.
The filter is still visible.

**Version**
On master since Dec 17, 2018
Version  4.14.0 (?) till current latest 4.15.0

**Additional context**
Regression caused by https://github.com/infor-design/enterprise/pull/1416.
Change prevents calling Datagrid.settings.source function, but intended change was just to prevent calling: 
```
 /**
         * Fires after a filter action ocurs
         * @event filtered
         * @memberof Datagrid
         * @property {object} event The jquery event object
         * @property {object} args Object with the arguments
         * @property {number} args.op The filter operation, this can be 'apply', 'clear'
         * @property {object} args.conditions An object with all the condition data.
         * @property {string} args.trigger Info on what was the triggering action. May be render, select or key
         */
        this.element.trigger('filtered', {op: 'apply', conditions: conditions, trigger: trigger});
```
Why it worked for test fields I do not understand. Maybe fix should be in different place? Or refactoring is needed?

**Comment by tmcconechy** [comment]
Added to the sprint for later QA.

**Comment by brianjuan** [comment]
https://4170-beta0-enterprise.demo.design.infor.com/components/datagrid/test-disable-client-filter-and-sort.html
Passed QA testing on all browsers following steps in #1745 , moving to Done.
