### ISSUE TITLE
SohoTreeComponent - Children property is undefined when tree is multi select.

### ISSUE THREAD

**Issue by mdevale** [infor-design/enterprise#1690]
**Describe the bug**
When getting tree dataset, children property of tree node who has children's before assigning dataset to tree is undefined when tree is multi select.

**To Reproduce**
1. Do the changes as described in additional context
2. Run the project
3. Browse tree-source page in tree control
4. See console output

**Expected behavior**
If tree node has children then children property of that node should not be undefined.

**Version**
- ids-enterprise-ng: v5.0.0 
- ids-enterprise: v4.15.0

**Screenshots**
![image](https://user-images.githubusercontent.com/40569892/53416045-a2f2bb00-39f8-11e9-8b72-995492f2f6d3.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name - chrome
 - Browser Version - Version 72.0.3626.109 (Official Build) (64-bit)

**Additional context**
1. Put below code in tree-source.demo.ts to make tree multi select.  
    `treeOptions: SohoTreeOptions = {    
    hideCheckboxes: true,
    selectable: 'multiple'
  };`

   `ngOnInit() {
    this.tree.options = this.treeOptions;
  }`  

2. Define ngAfterViewInit in tree-source.demo.ts as below
   ` ngAfterViewInit() {        
    const data = this.demoData.getRootTreeNodes();
    console.log('Assigned Dataset: ' + JSON.stringify(data));    
    this.tree.dataset = data;
    console.log('Dataset from tree: '); 
    console.log(this.tree.dataset);    
  }`

3. Change ROOT_NODE in tree-data.demo.ts as below
    `private ROOT_NODE: SohoTreeNode = {
    'id': 'Root ' + this.id++,
    'open': true,
    'text': 'Node 1',
    'children': [
        {
          'id': 'Node 1' + '/1',
          'text': 'Leaf ' + this.id++
        },
        {
          'id': 'Node 1' + '/2',
          'text': 'Node ' + this.id++,
          'children': []
        }
      ]
    };`

**Comment by mdevale** [comment]
Found one more scenario. If tree is not multi select, on expanding node it's children property get's undefined. Please find attached screenshot. Steps to reproduce:

1. Browse tree-children page from my fork "mdevale/enterprise-ng"
2. Expand node "Node 2.2" by clicking on folder icon
3. Click on "Log Dataset" button.
4. See console. Node 2.2 has children but Node 2.2 doesn't have children property in tree dataset.

Before expanding node Node 2.2
![image](https://user-images.githubusercontent.com/40569892/53542687-9cbe2500-3b45-11e9-9a58-95725ba5ba69.png)

After expanding node Node 2.2
![image](https://user-images.githubusercontent.com/40569892/53542862-6634da00-3b46-11e9-87a1-0c7c2c194d5f.png)

**Comment by tmcconechy** [comment]
@deep7102 wonder if your recent fix fixes this. Can you test this and let me know?

**Comment by jbrcna** [comment]
**QA Passed**
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/tree/test-children-data.html
![image](https://user-images.githubusercontent.com/56722184/81691409-583f5080-948f-11ea-860d-35926d0f1913.png)

https://master-enterprise.demo.design.infor.com/components/tree/test-children-data-select-multiple.html
![image](https://user-images.githubusercontent.com/56722184/81691865-1ebb1500-9490-11ea-913d-1f589df30a04.png)

**Comment by hemantg05** [comment]
I had another issue with regular tree component while using **ids-enterprise-ng v7.1.0**(ids-enterprise v4.28.0). When a node is selected, its children disappear from `tree.dataset`. This issue seems to be resolved with this bug fix.

**My issue:**
1. Select a node which has children.
2. Inspect the tree.dataset

**Expected Behaviour:** The selected node should have children in the tree.dataset.
**Actual Behaviour:** The selected node's children disappear in `tree.dataset` after the node was selected.

![tree-dataset-children-disappear-after-selecting-a-node](https://user-images.githubusercontent.com/1594815/82458804-702e5a00-9ab7-11ea-8273-ec55855cdd15.gif)

QA may add a test for this scenario to verify in their testing. 

cc @karinthulin
