### ISSUE TITLE
Listbuilder item text is treated as HTML

### ISSUE THREAD

**Issue by jake-harrington** [infor-design/enterprise#1692]
**Describe the bug**
Adding something in a listbuilder using HTML as the text, the item is treated as HTML still.

**To Reproduce**
1. Go to http://localhost:4000/components/listbuilder/test-add-new-item.html
2. Open JS console in dev tool
2. Click +
3. Type <script>alert('hi')</script>
4. Observe security errors in the console because it's trying to execute the title as a script

**Expected behavior**
The text should be rendered as it was input with nothing being treated as HTML. It should be shown as '<script>alert('hi')</script>' the whole time without anything executing.

**Version**
Tested 4.17 and the 4.11 we're using.

**Screenshots**
![image](https://user-images.githubusercontent.com/39064853/53501980-c35f5b80-3a72-11e9-906f-6b4133584989.png)

**Additional context**
We're seeing this in the version we use too (4.11), though we have a different way to add that will pass an updated dataset to listbuilder.updateDataset(ds) and it's rendering initially correctly there, but is treated as HTML and fires alerts whenever you try to drag the item to reorder.

**Comment by brianjuan** [comment]
http://localhost:4000/components/listbuilder/test-add-new-item.html
http://master-enterprise.demo.design.infor.com/components/listbuilder/test-add-new-item.html
Passed QA testing on all browsers. Will test again once beta is deployed.
