### ISSUE TITLE
Release Process Updates/Enhancements

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1693]
**Is your feature request related to a problem? Please describe.**
Fully script the build process and update documentation.

**Describe the solution you'd like**
Make any necessary updates to the release process as a script to make seamless.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by clepore** [comment]
We are also waiting on DevOps to give accounts and tokens.

**Comment by tmcconechy** [comment]
Also checkout #1864
