### ISSUE TITLE
Stepprocess :  Previous/next step selects a disabled step

### ISSUE THREAD

**Issue by boehmd1** [infor-design/enterprise#1697]
**Describe the bug**
The step process next and previous actions select a disabled step when it encounters two disabled steps in a row or if the first  step in a folder is disabled. 

**To Reproduce**
Modify the existing samples to have two disabled steps in a row.  Using the next button will skip the next step which is disabled and automatically selects the next step, it does NOT check if that step is also disabled.  

Modify the existing samples to have the first step in a folder disabled, using the next button that step is selected.

**Expected behavior**
Disabled steps should be skipped (not selected) when using the next or previous buttons

**Comment by tmcconechy** [comment]
For who grabs this you may want to fix this pattern up with these related issues:
https://github.com/infor-design/enterprise/issues/1697
https://github.com/infor-design/enterprise/issues/1662
https://github.com/infor-design/enterprise/issues/413

**Comment by boehmd1** [comment]
@tmcconechy hope i did everything correctly :)

**Comment by brianjuan** [comment]
Hi @tmcconechy , where can we do QA testing for this?

**Comment by tmcconechy** [comment]
You cannot test out this issue, as it was not completed with a working sample. It was verified by an app developer.

**Comment by brianjuan** [comment]
Thanks @tmcconechy, will now move this to Done.
