### ISSUE TITLE
Modal Validation submit button is still clickable even with wrong email 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1701]
**Describe the bug**
Modal Validation submit button is still clickable even with wrong email 

**To Reproduce**
1. Go to http://4160-beta0-enterprise.demo.design.infor.com/components/modal/example-validation.html
2. Click each field until the validation appear
3. Populate Type and Description
4. Populate email with 'A' value
5. Notice that the submit button is Enabled

**Expected behavior**
Submit button should be Disabled. 

**Version**
[v4.16.0]

**Screenshots**
![feb-28-2019 19-24-35](https://user-images.githubusercontent.com/45757016/53563297-9acc8400-3b8e-11e9-943b-14180483dc22.gif)

**Platform**
- All browsers & devices

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Relates to #1579

**Comment by tmcconechy** [comment]
Descoping this for now.
