### ISSUE TITLE
Swaplist: cannot drag item after searching

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1703]
**Describe the bug**
Swaplist: cannot drag item after searching

**To Reproduce**
1. Go to https://4160-beta0-enterprise.demo.design.infor.com/components/swaplist/example-search.html
2. Drag "Option AA" from 'Available' to 'Selected'
3. Type "BB" in the search field of 'Available'
4. Try to Drag "Option BB"
5. See issue: Option BB cannot be dragged
6. Clear the search field of 'Available'
7. Try to drag any item from 'Available', See issue: now you can't drag any item
8. Also notice that "Option AA" is now in the 'Available' again

**Expected behavior**
Items in the swaplist should be draggable even after searching

**Version**
- ids-enterprise: v4.16.0-beta0

**Screenshots**
No applicable screenshot

**Platform**
 - All devices, OS and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This does work in https://4150-enterprise.demo.design.infor.com/components/swaplist/example-search.html - so considering a regression.

**Comment by brianjuan** [comment]
https://4160-rc1-enterprise.demo.design.infor.com/components/swaplist/example-search.html
Passed QA testing on all browsers, moving to Done.
