### ISSUE TITLE
Tabs-module with searchfield: x icon is outside the searchfield

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1704]
**Describe the bug**
Tabs-module with searchfield: x icon is outside the searchfield.

**To Reproduce**
Affected pages:
- https://4160-beta0-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html
- https://4160-beta0-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html
- https://4160-beta0-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button.html

1. Go to URLs above
2. Type "test" in the search field
3. See issue: x icon is displayed outside the searh field

**Expected behavior**
x iocn should be inside the search field

**Version**
- ids-enterprise: v4.13.0 - v4.16.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/53575456-88f9d980-3bac-11e9-9831-8aae4cf79636.png)

**Platform**
 - All devices, OS and browsers.

**Additional context**
Search field also doesn't look good on mobile.

**Comment by tmcconechy** [comment]
This hasnt worked in a while i checked back quite a few versions. But this looks bad and should be an easy fix so raising the priority so it gets picked up soon.

**Comment by janahintal** [comment]
QA Passed. 
Tested in: 
http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
http://localhost:4000/components/tabs-module/example-category-searchfield.html
http://localhost:4000/components/tabs-module/example-category-searchfield-go-button.html
Across all OS and Browser. Thanks!
