### ISSUE TITLE
Calendar Component: Company Holiday view not correct on high contrast

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1706]
**Describe the bug**
Calendar Component: Company Holiday view not correct on high contrast

**To Reproduce**
1. Go to url: http://4160-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Create a "Company Holiday" event
3. Change the contrast to "High Contrast"
4. Company Holiday event doesn't appear correctly on high contrast. Please see screen shot attached. 

**Expected behavior**
Company Holiday should appear correctly on high contrast

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1359" alt="calendar high contrast issue" src="https://user-images.githubusercontent.com/39101346/53586978-4d80f000-3b57-11e9-911b-94fbcbf51134.png">

**Platform**
 - OS Version: [iOS 8]
 - Browser Name [FF]

**Additional context**
None

**Comment by tmcconechy** [comment]
This color is configurable. So this really doesnt matter. If they want to use it in that high contrast mode they can pick a better color. Should maybe update the example colors sometime.

**Comment by tmcconechy** [comment]
This issue can no longer be reproduced. Must have been fixed along the way.
