### ISSUE TITLE
Calendar Component: Changing some event spans is causing missing dates on the dialogs

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1708]
**Describe the bug**
Calendar Component: Orang exclamation point Out of Office event not working correctly

**To Reproduce**
1. Go to url:http://4160-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html#
2. Click on the "Out of Office"  event on Feb 13th and open the event
3. Change the Event name to another name and change the date to 2/13-2/28 and close the event
4. Open that same event on the date 2-26
5. When you open the even the From and To field are blank. Please see the screen shot attached. 

**Expected behavior**
The dates should appear on the From and To field boxes

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1359" alt="calendar events issue 2" src="https://user-images.githubusercontent.com/39101346/53592586-9be8bb80-3b64-11e9-9f5d-02403d5d8b9e.png">

**Platform**
 - OS Version: [iOS MAC]
 - Browser Name [FF]

**Additional context**
None

**Comment by marknolaninfor** [comment]
This may be solved by #1742 as if the popup had validation then the dates could be set as required fields and also validate the date input.
