### ISSUE TITLE
Toolbar Flex - selected events not working for menu buttons

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#1709]
**Describe the bug**
Selected Events aren't working for a menu button in a flex toolbar

**To Reproduce**
1. Go to '/components/toolbar-flex/example-more-actions-ajax'
2. Click on Menu Button, and then select Menu Button Option 1
3. No toast message confirmation is seen

**Expected behavior**
Should see a toast message confirming the selected event bubbled up and the correct option is identified.

**Version**

- ids-enterprise: v4.16.0-beta.0

**Screenshots**
![nomenubuttonevents](https://user-images.githubusercontent.com/22107636/53594521-a5702480-3b60-11e9-9486-fe1f5e864348.gif)

**Platform**
 - All

**Comment by janahintal** [comment]
QA Passed. Working fine on all OS, Browser and Devices. Will move to Done. Thanks. 
Tested in: https://4170-beta0-enterprise.demo.design.infor.com/components/toolbar-flex/example-more-actions-ajax
