### ISSUE TITLE
Checkboxes Component: Dirty tracker not appearing correctly on high contrast

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1710]
**Describe the bug**
Calendar Component: Show Event selection not working

**To Reproduce**
1. Go to url:http://4160-beta0-enterprise.demo.design.infor.com/components/checkboxes/example-horizontal.html
2. Change the color contrast to high contrast
3. The dirty tracker is not appearing correctly
4. Please see screen shot attached

**Expected behavior**
The dirty tracker should be yellow not dark gray

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![bs_win10_edge_18 0 2](https://user-images.githubusercontent.com/39101346/53594898-e3be1180-3b69-11e9-8a04-bbbba26cb1ff.jpg)
![bs_realios_mobile_iphone xs-12 0](https://user-images.githubusercontent.com/39101346/53594899-e3be1180-3b69-11e9-9ba6-a0470f42a071.jpg)

**Platform**
 - All Browsers and Devices 

**Additional context**
None

**Comment by tmcconechy** [comment]
This is actually correct as it changes to a darker color on high contrast mode.
