### ISSUE TITLE
Circle Component: On responsive view the down arrow key is not working 

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1712]
**Describe the bug**
Circle Component: On responsive view the down arrow key is not working 

**To Reproduce**
1. Go to url: http://4160-beta0-enterprise.demo.design.infor.com/components/circlepager/example-index.html
2. Make the page responsive
3. A scroll bar will appear on the right hand side of the page
4. Use the down arrow key to scroll down. The page starts to flicker when you press on the down arrow key

**Expected behavior**
The user should be able to press on the down arrow key and view all the circle images with out any issues

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
None

**Platform**
 - OS Version: [ iOS MAC]
 - Browser Name [FF]

**Additional context**
None

**Comment by tmcconechy** [comment]
Descoping this for now.
