### ISSUE TITLE
Datagrid: stretch column not working in Edge browser

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1716]
**Describe the bug**
The stretch column does not work correctly and within the Edge browser a space can be seen.

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/test-columns-stretch-column.html'

**Expected behavior**
The grid columns should fill the datagrid.

**Version**
- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/53704925-a6f76080-3e70-11e9-94a7-794086265271.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Windows 10
 - Browser Name Edge
 - Browser Version 40.15063.674.0

**Additional context**

**Comment by janahintal** [comment]
Hi, Issue still exist Mobile Devices. Will re-open the ticket. Thank you.

To Replicate:
1. Open https://4170-beta0-enterprise.demo.design.infor.com/components/datagrid/test-columns-stretch-column.html in Portrait Angle on Android or iOS Mobile Devices. 
2. Flip / Rotate the screen to Landscape 

Please see Images below. 
<img width="917" alt="Screen Shot 2019-03-21 at 6 07 05 PM" src="https://user-images.githubusercontent.com/45757016/54745461-87985b80-4c04-11e9-9db9-be331e39a211.png">
<img width="965" alt="Screen Shot 2019-03-21 at 6 08 29 PM" src="https://user-images.githubusercontent.com/45757016/54745469-8bc47900-4c04-11e9-81cf-f0370c12d02b.png">

**Comment by janahintal** [comment]
QA Passed. Moving to Done. Thanks!
Tested in: https://4170-beta0-enterprise.demo.design.infor.com/components/datagrid/test-columns-stretch-column.html across all browser, OS & devices.
