### ISSUE TITLE
Datagrid date filter does not filter 'null' values on 'is not empty'

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#1718]
**Describe the bug**
When filtering 'is not empty' dates on datagrid, "null" values are still being shown. Whereas empty string values are being filtered out.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-editable.html'
2. On Row 6, remove the 'Order Date' value
![image](https://user-images.githubusercontent.com/41028784/53710769-c47cf800-3e79-11e9-8634-df0083044348.png)
3. Row 6 should have an empty string value ("") and Row 7 has a null value.
![image](https://user-images.githubusercontent.com/41028784/53710819-027a1c00-3e7a-11e9-8ed3-83a896b472f0.png)
4. Filter our the Order Date using the "Is Not Empty" option.
![image](https://user-images.githubusercontent.com/41028784/53710831-102fa180-3e7a-11e9-9fcb-f59682337230.png)

**Expected behavior**
Both Row 6 and Row 7 should not be shown anymore since they are "empty" and we are filtering out values that are "not empty".

**Actual Behavior**
Row 7 is still shown.
![image](https://user-images.githubusercontent.com/41028784/53710856-37866e80-3e7a-11e9-8b2f-36ac55369afc.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome

**Comment by tmcconechy** [comment]
Putting in the sprint as it was picked up

**Comment by janahintal** [comment]
QA Passed. Moving to Done. 
Verified in: https://4170-beta0-enterprise.demo.design.infor.com/components/datagrid/example-filter.html across all Devices, OS and Browsers.
