### ISSUE TITLE
Accessibility: Issues on Skip Link and App Menu

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1721]
**Describe the bugs**
A listing of minor bugs we might need to break out the bigger ones later.

- [x] ~~App Menu - > Suggest to use a UL and LI instead of a series of divs for the tree~~ Wont do, not a problem
- [x] ~~App Menu - > The has tag in the href is pronounced on older browsers, use a title~~ Wont do dont really know details.
- [x] ~~App Menu - > The divs incorrectly have `role="presentation"` (this is actually accordion `<div class="accordion-header hide-focus is-selected" role="presentation"> </div>`)~~ - On folow up this is correct.
- [x] App Menu - > if open then the skip link does not have a high enough z-index
- [x] ~~Dropdown- > Seems to not have labels~~ - Could not reproduce, maybe a Landmark only issue
- [x] ~~Lookup- > The modal has incorrect alertdialog role.~~ this is not true as on http://localhost:4000/components/lookup/example-index.html the role is dialog, so must be something on the landmark lookups
- [x] ~~Listview- > The ul also has `role="presentation"`  ~~ will be done on #403

**Version**
4.16.x

**Additional context**
Landmark Accessibility Call with External Contractors.

**Comment by janahintal** [comment]
Hi @clepore, after clicking 'Skip to Main Content' link, the URL is changed to **'components/applicationmenu/example-open-on-large.html#maincontent'** is this what you mean in _'when you hit the skip link it should now be on top'_ and is expected? Thanks!

**Comment by clepore** [comment]
Umm I'm not really sure. @tmcconechy can probably elaborate when he's back in the office next week 👍

**Comment by tmcconechy** [comment]
On top means visually (the zindex). Previously the app menu had a higher zindex so the skip link is hidden behind and you couldn’t even see it since the menu was over it. So if you see the link visually on the page it’s working. Clicking it will focus the hash link in the page which is on the header (what your seeing on the link).

**Comment by janahintal** [comment]
Thanks @tmcconechy. I can see the link button now in all browsers. I will now move the ticket to Done. Thanks!
