### ISSUE TITLE
Splitter Component does not allow buttons on left split

### ISSUE THREAD

**Issue by darinw** [infor-design/enterprise#1730]
**Describe the bug**
When using`isSplitterRight=false` and  `collapseButton=true` the buttons will not appear.

**To Reproduce**
1. Go to https://github.com/infor-design/enterprise/blob/977e799fb7e0feb6a5edcb23e12d7df5a7758863/src/components/splitter/splitter.js#L98
2. See code only run inside `isSplitterRightSide`

**Expected behavior**
collapse buttons should be allowed in right and left split

**Version**
- ids-enterprise: v4.15.0

**Comment by janahintal** [comment]
The issue still exist. Please see image below. The arrow should point left.
https://master-enterprise.demo.design.infor.com/components/splitter/test-collapse-button-right.html
https://master-enterprise.demo.design.infor.com/components/splitter/test-collapse-button.html

notice that when I slit until the end, the arrow still point to right.
![image](https://user-images.githubusercontent.com/45757016/90000514-d85d9800-dcc2-11ea-8a3b-5d0e5ae038c3.png)

**Comment by tmcconechy** [comment]
Yes i see that issue. Good catch.

On https://master-enterprise.demo.design.infor.com/components/splitter/test-collapse-button.html when you manually resize it all the way to the left at the last minute it flips "out". But https://master-enterprise.demo.design.infor.com/components/splitter/test-collapse-button-right.html doesnt do that.

**Comment by tmcconechy** [comment]
cc @jmacaluso711

**Comment by janahintal** [comment]
Issue still exist on initial load of https://master-enterprise.demo.design.infor.com/components/splitter/test-collapse-button-right.html when in responsive view. 

Steps:
1. Minimize the windows and go to https://master-enterprise.demo.design.infor.com/components/splitter/test-collapse-button-right.html
2. See error
![image](https://user-images.githubusercontent.com/45757016/91811596-54b01f00-ec62-11ea-970a-3fd2afc0b255.png)

**Comment by tmcconechy** [comment]
Im not clear on this steps. This also seems minor. Lets make a new issue and we can look at it at a later date
