### ISSUE TITLE
Application Menu: Truncating of Text / Long Language Text Handling

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#1736]
**Describe the bug**
Truncated texts on application menu do not show tooltips.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels-icons.html
2. Click on Level 1 Outbound Links and traverse through the application menu tree
3. Hover on 'Level 6 Outbound Link...'
4. There is no tooltip showing the full text.

**Expected behavior**
Tooltip should be present on a hover when text is truncated.

**Version**
- ids-enterprise: v4.17.0

**Screenshots**

**Platform**
 - Device: desktop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 72.0.3626.119 

**Additional context**
Related to https://github.com/infor-design/enterprise/issues/457

**Comment by tmcconechy** [comment]
@davidcarlsonberg - Perhaps see if you can address this based on the last PR, when you have a chance.

**Comment by davidcarlsonberg** [comment]
This looks to be a scrollbar appearance issue.

**Comment by janahintal** [comment]
QA Passed. Moving to Done. 
Verified in: https://4170-beta0-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels-icons.html across all OS, Browsers, and Devices. Thanks!
