### ISSUE TITLE
Listview: Updated() passing "undefined" for setting no longer refreshes the component

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#1738]
**Describe the bug**
The listview.js `updated()` function was changed to only refresh the list view when setting were not undefined. This breaks EP/NG content projection where we project new elements into the `div.listview` element. It manifests itself as not displaying checkboxes for mixed and multiple selection modes.

See the change here that caused the issue.
https://github.com/infor-design/enterprise/commit/211804d13fa0ed7d2fb43bf4ab9fde846da020b9#r32531426

**Expected behavior**
Expect `update()` with undefined args to call the `refresh()` function of listview.

**Version**
4.16.0-beta.0 and 4.16.0-rc.0

**Comment by tmcconechy** [comment]
I saw this comment but wasnt 100% clear on how to reproduce this. What do you think @pwpatton ?

**Comment by pwpatton** [comment]
To duplicate the issue in EP I think we’d need a test sample to do these  steps 

- initialize a list view w/o a template and instead initialize from html with settings.selection set to ‘mixed’
- once displayed change the list items in the dom and call updated() w/o any args. 
Before the regression they updated() function would call the refresh() function and it would add the checkboxes to the items. 
After the regression the refresh isn’t called and the checkboxes don’t get rendered. 

This essentially mimics what we do in

**Comment by pwpatton** [comment]
a work around to this issue could be to call the updated function with an empty object: ‘listview.updated({})’. 

That would cause the refresh function to be called that adds the checkboxes.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
