### ISSUE TITLE
Calendar: modal is still displayed after changing months

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1741]
**Describe the bug**
The modal is still displayed after the month is changed.

**To Reproduce**
1. Go to 'http://localhost:4000/components/calendar/example-index.html'
2. Click on any event to display the modal
3. Change the displayed month

**Expected behavior**
I believe that the modal should close when a new month is rendered, eg. add removeModal to the event.

**Version**
v4.17.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/53850918-c75c2200-400c-11e9-9469-dd91fc0e1ee0.png)

**Comment by tmcconechy** [comment]
Would need to hide the popover on changeMonth, could just add a call to close for any open popovers there.
