### ISSUE TITLE
Calendar: Missing field validation

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1742]
**Describe the bug**
The validator will not run any rule when there is any item visible on the page with the class "calendar-popup" and the Calendar modal has this class. This then means you can not set any validation like a field is required within this modal.

This requires an alteration to the page to add the required validation to a field eg subject

**To Reproduce**
1. Go to '/components/calendar/example-index.html'
2. Clear the value from the subject
3. The required message should show

**Expected behavior**
This modal should allow for validation rules to be added.

**Version**
v4.17.0

**Comment by tmcconechy** [comment]
Actually this is using the popover which does not have validation built in. http://latest-enterprise.demo.design.infor.com/components/popover/example-index.html

What i would suggest is just manually invoking the validation component on your button clicks, as this would be fairly repetitive to add to the popover.

**Comment by marknolaninfor** [comment]
@tmcconechy 

The field attempts to validate, but there is a condition that stops the check from being processed. The change allows the validation to happen and then makes the calendar popup to work like a modal with the primary button. This is only for the calendar in the same way that the validation was excluded.

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to QA failed. The Cancel and Submit are not appearing correctly. Please see screen shot attached. This was tested using URL: http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html

![Calendar Submit and Cancel button](https://user-images.githubusercontent.com/39101346/60457269-9336ed80-9c09-11e9-8ad2-f6ccd9a0255c.png)

**Comment by tmcconechy** [comment]
Can you add any more info @CindyMercadoReyes ? I tested this quickly on http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html in mac chrome and did not see any issue. i did this
- dbl click a day so the calendar popups up
- type a value like 3/33 in and tab out of the date field

**Comment by tmcconechy** [comment]
@CindyMercadoReyes lets raise a new bug for this issue.

**Comment by janahintal** [comment]
Hi, @tmcconechy I was able to replicate the issue. Raised #2479 for it. Moreover, Ive tested this issue and it seemed Passed through all Browser, OS and devices. Thanks

**Comment by tmcconechy** [comment]
Ok thanks i still cant reproduce that issue but lets take it on the new issue. moving this to done now.
