### ISSUE TITLE
Tabs: Style-only Header Tabs are incorrectly making AJAX calls to their specified URLs

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1746]
Discovered [here](https://github.com/infor-design/enterprise/pull/1728#issuecomment-470171684)

**Describe the bug**
On the Tabs component, there's a case where Header Tabs can be used as "style-only", where the tabs that are displayed will be outbound hyperlinks instead of rendering a tab panel.  This case is for "website"-styled apps that are not single-page.

There's also a case in Tabs where defining a full URL can create an AJAX request for getting Tab content.  At some point, it appears these two cases were mixed, and is now causing an issue on these tests.

**To Reproduce**
Navigate to either of these tests:
- http://master-enterprise.demo.design.infor.com/patterns/navigation-tabs-outbound-page1.html
- http://master-enterprise.demo.design.infor.com/patterns/navigation-tabs-outbound-page2.html

Notice that there is a second header rendered inside a tab panel.  If you examine the HTML for either of these tests, there is a tab panel already defined with content that should be displayed instead of the header.

**Expected behavior**
The correct tab panel should be showing on these test pages.

**Version**
v4.15.x

**Screenshots**

![screen shot 2019-03-06 at 11 33 16 am](https://user-images.githubusercontent.com/3249601/53897216-ac38e480-4003-11e9-9000-d4d1cda8507b.png)

**Platform**
- n/a

**Comment by tmcconechy** [comment]
This seems to have been completed.
