### ISSUE TITLE
Demo App: Remove "font" query parameter functionality

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1747]
**Is your feature request related to a problem? Please describe.**
Since we are slowly creating the uplift theme, we do not need `?font=` url query parameter for the demo app.

**Describe the solution you'd like**
Remove the`?font=source-sans` capability from the demo app.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by EdwardCoyle** [comment]
Is the idea here that the font style will come through the tokens, per theme?

**Comment by tmcconechy** [comment]
I think so. I think we can just remove the url param, but also the personalize functions to set theme.

**Comment by EdwardCoyle** [comment]
@clepore @nickwynja

Are we ok with removing the query param from the app?  One concern we had was the fact that design.infor.com shows all the current samples using the new font, so we would technically be breaking the website (even though the font would just default to the standard).

For example, the embedded design here:  https://design.infor.com/code/ids-enterprise/latest/grid

**Comment by tmcconechy** [comment]
Things we could remove:
1. Do we want to say that this font is part of the theme now?
1. Change the site to not show that font for this theme when embedded
1. Change the site to not send a url param for this theme when embedded
1. Remove the option on personalize.js to change the font for a theme.
1. Remove the URL Param?

Sound like the goal?

**Comment by nickwynja** [comment]
We never really adequately rolled out the new font in the default "soho" theme, so I'm OK removing the font query param from the app and standing behind the new font for the uplift theme. We can also remove the query param from the embeds on the website.

I'm not sure we should touch `personalize()` though. If there's a chance that someone is depending on it there, we'd be breaking things for them.

**Comment by tmcconechy** [comment]
Sounds like the best idea. Maybe we can deprecate the setting in personalize.js. It mostly works but we’ve discovered a couple line height issues that we probably don’t want to continue to support going forward for old themes. Not sure that many would be using that in prod.

**Comment by EdwardCoyle** [comment]
I think I may also try to pick up #1658 in this sprint, in which case I will punt on the deprecation of the font setting in personalize.js and maybe try to work that into the larger deprecation notice framework.

**Comment by nickwynja** [comment]
I've removed the font query param from the website.
