### ISSUE TITLE
Column click broke when a the data grid has hidden columns

### ISSUE THREAD

**Issue by boehmd1** [infor-design/enterprise#1749]
**Describe the bug**
Column click broke when a the data grid has hidden columns.  

The regression was promoted with this PRD - https://github.com/infor-design/enterprise/pull/1635

handleEvents() {
..

      // Handle Cell Click Event
      const elem = $(this).closest('td');
      const cell = elem.attr('aria-colindex') - 1;
	  //const cell = elem.parent().children(':visible').index(elem);
	  // now when self.columnSettings(cell, true) looks for the column, the index
	  // will be wrong if there are any hidden columns before this column
      const col = self.columnSettings(cell, true);

      if (col.click && typeof col.click === 'function' && target.is('button, input[checkbox], a') || target.parent().is('button')) {   //eslint-disable-line
        const rowElem = $(this).closest('tr');
        let rowIdx = self.actualRowIndex(rowElem);

**To Reproduce**
1. Have a hidden column before a column with a click handler

**Expected behavior**
colum.n.click function is called.

**Comment by boehmd1** [comment]
@tmcconechy  this is a regression, not sure on how to mark the bug a regression.

**Comment by tmcconechy** [comment]
Also seems like if you have two of them its not working. Trying http://localhost:4000/components/datagrid/test-icon-buttons.html#

vs

http://latest-enterprise.demo.design.infor.com/components/datagrid/test-icon-buttons.html#

Both button should show a console.log

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
