### ISSUE TITLE
Lookup Datagrid Date and DateTime Values are not being filtered on some of the filter types.

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#1754]
**Describe the bug**
Opening a lookup which has filters allowed, when trying to filter Date and DateTime Values using 

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/lookup/test-paging-server-side-and-autocomplete.html'
2. Open the lookup.
![image](https://user-images.githubusercontent.com/41028784/53922259-8ddbf300-40ae-11e9-9b58-3f9be617724d.png)

3. Filter the 'Order Date' column by greater than or equal to (>=) 1/1/2015
![image](https://user-images.githubusercontent.com/41028784/53922275-9af8e200-40ae-11e9-9712-c34204554574.png)

4. There should still be multiple records shown on the grid. But as seen below, no records were found
![image](https://user-images.githubusercontent.com/41028784/53922337-dbf0f680-40ae-11e9-9dc1-cc776941184c.png)

Same issue occurs with the other filters. Only the "equals" filter looks to be working correctly.

**Platform**
 - Windows 10
 - Google Chrome

**Comment by tmcconechy** [comment]
I think this issue might just be on the data on that example (for example maybe the data is string).
As it works ok here http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html

**Comment by tmcconechy** [comment]
@NathanLouisBarcial Can you please confirm what the source data you have in your case is? Is it a date object in the dataset? Or something else?

**Comment by NathanLouisBarcial** [comment]
Hi @tmcconechy, in our case, it's in a date string format in the dataset: 
![image](https://user-images.githubusercontent.com/41028784/56267681-14f69f00-6122-11e9-9ee6-8a0e5a9d437d.png)

Just like in 'http://master-enterprise.demo.design.infor.com/components/lookup/test-paging-server-side-and-autocomplete.html'

![image](https://user-images.githubusercontent.com/41028784/56267708-2d66b980-6122-11e9-80d0-aafa48b9f2df.png)

**Comment by EdwardCoyle** [comment]
After looking at this one, seems like the example isn't "working" because we don't actually ship a completely functioning example of server-side filtering with date/time on Datagrids (and by proxy, Lookups).  The example @tmcconechy provided displays client-side filtering, which is fully supported by us and seems to be working.

I'm not sure we want to tackle this one yet, only because we're starting to get into the implementation of app-level data handling, which is out of scope for a UI/UX kit.

**Comment by tmcconechy** [comment]
Suggest we close this issue as this cannot work and does'nt really need to work for the server side examples. The teams would implement this on their servers. This can only work client side in the demo app.
