### ISSUE TITLE
Datagrid Cell Value Removed When Tabbed Out, User unable to input value again

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#1755]
**Describe the bug**
When a cell in a datagrid is focused and user tabs out of the cell, the value is removed and user is unable to edit again. 

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html'
2. Focus on a cell in the "Activity" Column.
![image](https://user-images.githubusercontent.com/41028784/53924286-80c30200-40b6-11e9-91b2-b262d0a88fc2.png)

3. **Tab Out** of the cell.
![image](https://user-images.githubusercontent.com/41028784/53924290-89b3d380-40b6-11e9-80e8-82c62256f7ed.png)

4. The value in the cell is removed and if user tries to enter a value again, user is unable to do so. Tried doing the same steps to the other columns, and same happens. Although, in the Order Date and Action columns, this issue doesn't occur.

**Platform**
 - Windows 10
 - Chrome

**Comment by tmcconechy** [comment]
This issue appears to be ok in the 4.16 release http://4160-rc1-enterprise.demo.design.infor.com/components/datagrid/example-editable.html this will get merged on to master on release so closing the issue as fixed in 4.16

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
