### ISSUE TITLE
Calendar: Create Week View

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1757]
**Is your feature request related to a problem? Please describe.**

We need to implement the week view in the calendar. See the [Design for Calendar UI Week View](https://github.com/infor-design/enterprise/files/2941621/SoHo.Calendar.UI-Week.View_111218.pdf)

**Describe the solution you'd like**

Implement similar to monthview as a new component and then integrate into the calendar component

**Describe alternatives you've considered**
N/A

**Additional context**
#1289

**Comment by marknolaninfor** [comment]
Hi @tmcconechy,

It is not clear on the design if there is a way to highlight a work day.
![image](https://user-images.githubusercontent.com/39749678/53995037-c4d00880-4183-11e9-88aa-396ad022f3b4.png)

**Comment by tmcconechy** [comment]
We probably could just use x2 or x3 in the color pallette on the selection state

**Comment by jamie-norman** [comment]
@tmcconechy Yeah, I think that makes sense; typical highlight color. Click on the day "cell" to select the whole day > change state to highlight color.

**Comment by tmcconechy** [comment]
Moved this to next sprint due to high urgency issues and holidays ect. If we have enough time can still do try to do it earlier

**Comment by tmcconechy** [comment]
Working on primarily remaining calendar issues next sprint (after labour day)

**Comment by tmcconechy** [comment]
This is almost working but is not stable enough for code cut off. Will be first thing in 4.23.

**Comment by janahintal** [comment]
Hi @tmcconechy , I was able to navigate the Week view however, after changing the theme form Subtle to Vibrant some components misaligned. 

![image](https://user-images.githubusercontent.com/45757016/68670988-3ff68380-0589-11ea-9033-af7732138cc7.png)

**Comment by tmcconechy** [comment]
This was a known issue i mentioned in the testing. You need to reload the page or that field wont resize. But im going to fix this i decided. This is also already mentioned here https://github.com/infor-design/enterprise/issues/2862#issuecomment-552599097 so this is duplicate so moving to done.
