### ISSUE TITLE
Popupmenu: Icons are now much larger

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1758]
**Describe the bug**
After icon changes the icons when on popupmenus are very large.

**To Reproduce**
1. Go to http://4160-rc1-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
1. Click on any filter menu
1. Compare to http://4150-enterprise.demo.design.infor.com/components/datagrid/example-filter.html

**Version**
- ids-enterprise: v4.16.rc

**Screenshots**
![screen shot 2019-03-07 at 9 06 34 am](https://user-images.githubusercontent.com/814283/53964775-f1215180-40bd-11e9-9610-dd582005c5b8.png)

**Platform**
- Any

**Additional context**
- Ms teams chat

**Comment by tmcconechy** [comment]
Interestingly http://master-enterprise.demo.design.infor.com/components/popupmenu/example-icons.html is not effected.

**Comment by nickwynja** [comment]
Will fix in infor-design/design-system#329 and release in `2.3.0`.

**Comment by nickwynja** [comment]
This is how it looks in the `2.3.0` build:

![image](https://user-images.githubusercontent.com/1012017/53980215-ca731300-40dd-11e9-8522-f314e8516b6b.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
