### ISSUE TITLE
Uplift: Support backwards compatible refreshed icon set

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#1759]
**Is your feature request related to a problem? Please describe.**
As of `ids-identity@2.3.0`, we'll be introducing an alpha build of a new icon style. We need to support the ingestion of these icons at build time and support usage of these icons in the uplift theme.

**Describe the solution you'd like**
* When switching to the `uplift-alpha` theme, the application renders the new refreshed icon set.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by clepore** [comment]
To Do's:
- [ ] Change the build icons pipeline to build out all available icons for all themes.
- [ ] Build a theme switcher (or adapt) capability in the demo app to remove/inject each icon set, pending the requested theme. The default should be the Soho theme.

**Comment by parsakhan** [comment]
closed by #1795
