### ISSUE TITLE
Datagrid colspan is not skipping hidden columns 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#1764]
Describe the bug
For a datagrid containing a column with a colspan function, the returned colspan value is the number of visible columns that need to be spanned.  Issue occurs when a column is already hidden via hideColumn()  the 'is-hidden' class is not being added to the correct number of visible columns.  Leads to a column alignment issue. 

To Reproduce
1. Have a column with a colspan function
2. Have a hidden column within the colspan value
3. See alignment issue

Expected behavior
Columns are correctly aligned because 'is-hidden' class is added to visible columns.

Suggested Fix
Within the rowHtml function
...
if (skipColumns > 0 **&& !_col.hidden**) {
  skipColumns -= 1;
  cssClass += ' is-hidden';
} 

**Screenshots**
Without the fix screenshot:
![image](https://user-images.githubusercontent.com/39804038/53989834-82a7b800-40ec-11e9-801c-7c9f3ba5762f.png)

With the fix screenshot:
![image](https://user-images.githubusercontent.com/39804038/53990031-efbb4d80-40ec-11e9-845d-5d6fa6d84d77.png)

**Comment by janahintal** [comment]
QA Passed. Moving to Done. 
Tested in: http://4170-beta0-enterprise.demo.design.infor.com/components/datagrid/example-colspan.html in all browser and devices. 

<img width="1157" alt="Screen Shot 2019-03-20 at 5 35 40 PM" src="https://user-images.githubusercontent.com/45757016/54674067-9c0e2280-4b36-11e9-995b-cedcb169946f.png">
