### ISSUE TITLE
Summary Form: Improve data readability by updating type hierarchy

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#1765]
**Is your feature request related to a problem? Please describe.**
With information dense screens, the `summary-form` can lose readability since there is only a small difference between label and content typography

- [ ] Design input by @kayiuho 
- [ ] Dev implementation

See: https://design.infor.com/code/ids-enterprise/latest/demo/components/expandablearea/example-index

**Describe the solution you'd like**
* Increasing font size for data points and/or using font weight to differentiate labels, data, and headings
* Needs to be updated in default theme but also supported in `uplift`

**Describe alternatives you've considered**
n/a

**Additional context**
![image006](https://user-images.githubusercontent.com/1012017/54031945-2e4d1880-417e-11e9-8da4-ea6a9007f530.jpg)

![picture1](https://user-images.githubusercontent.com/1012017/54032110-ac112400-417e-11e9-8202-d24e6ab1c98a.png)

**Comment by tmcconechy** [comment]
Do we know yet what font sizes to use for a design?

**Comment by nickwynja** [comment]
@tmcconechy Not yet. We have to figure out which tokens to use and how they relate to https://github.com/infor-design/enterprise/pull/1751.

**Comment by nickwynja** [comment]
Copying @aaronpikkarainen on this issue since I know it's a customer concern in CSD as well.

**Comment by nickwynja** [comment]
For example:

```
.summary-form .label {
  font-size: $theme-size-font-xs;
  font-weight: $theme-number-font-weight-bold;
}

.summary-form .data {
  font-weight: $theme-number-font-weight-bold;
  line-height: $theme-number-font-line-height-md;
}
```

**Comment by nickwynja** [comment]
After looking at this again, we probably shouldn't do the `.summary-form .label` in grey. "Grey on grey" is consistently complained about.

**Comment by clepore** [comment]
@nickwynja should we link this to a (new) issue in design-system to address this?

**Comment by kayiuho** [comment]
Got some usability testing done on the text styling of Summary Form. If anyone is interested in the process and method I went through, I've documented everything in Dropbox Paper here: https://paper.dropbox.com/doc/Usability-Testing-Summary-Forms--AdIuWmZocyHB~FkZQybzOktGAQ-6Y1V0jBnsBWhBt0l7xJrg (H&L internal link only and not open for public viewing)

Based on the data and feedback I gathered, I'm proposing the below changes (for EP):
![EP 4 19](https://user-images.githubusercontent.com/34747859/57792376-da762700-770c-11e9-84e7-a7a510af0a00.png)

In terms of changing the text colors here on Summary Form, my reservation is that we would break the global styling once we start playing around with different colors of labels and base texts (unless we are fine with having Summary Form texts to render differently than the rest of the components. More thought on that??

**Comment by jmacaluso711** [comment]
There is a draft PR open for this if anyone want to look at it live

**Comment by CindyMercadoReyes** [comment]
This is now resolved. QA tested and verified.
