### ISSUE TITLE
Datagrid: Active page (savedUserSettings) in client-side paginated datagrid is stored but rows are not displayed when reloading the webpage

### ISSUE THREAD

**Issue by csachetti** [infor-design/enterprise#1766]
**Describe the bug**
Stored active page doesn't display its corresponding rows when reloading the webpage.

**To Reproduce**
1. Open this JsFiddle isolated test https://jsfiddle.net/y7c8bpqe/
2. Move to a page different than page 1
3. Refresh the browser

**Current behavior**
Active page is stored and selected, but its corresponding rows are not displayed.

**Expected behavior**
Stored active page displays its corresponding rows when reloading the webpage.

**Version**
- ids-enterprise: 4.15.0

**Platform**
 - OS Version: Xubuntu 16.04 LTS
 - Browser Name: Chrome
 - Browser Version: 64.0.3282.186 (Official Build) (64-bit)

**Additional context**
This doesn't work for client-side paginated datagrids. However it does work for server-side paginated datagrids.

**Comment by tmcconechy** [comment]
Have a feeling this is due to some recent pager changes.

**Comment by tmcconechy** [comment]
@janahintal I assume this was just dragged by mistake back? Moving to done. If incorrect just let us know.
