### ISSUE TITLE
Composite Tabs - Show Less overflows in IE11 when browser shrunk 

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#1768]
**Describe the bug**
The Show Less button on a composite form overflows in to the tab panel when the browser window is shrunk.

**To Reproduce**
1. Copy the attached [example-composite-form.zip](https://github.com/infor-design/enterprise/files/2946549/example-composite-form.zip) to componets/tabs
2. Navigate to /components/tabs/example-composite-form.html in IE11
3. Shrink the window.

**Expected behavior**
The Show More button should be in the context form, and not overflowed in to the tabs container

**Version**

- ids-enterprise: v4.17.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/54040371-cc46e000-418a-11e9-8edd-36a68dc0efcc.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: IE 11
 - Browser Version 11.1540.10586.0

**Comment by janahintal** [comment]
QA Failed. Issue still exist in Win 10 IE11. 
Please see below image. 
<img width="796" alt="Screen Shot 2019-03-20 at 4 06 27 PM" src="https://user-images.githubusercontent.com/45757016/54668616-40d63300-4b2a-11e9-812e-07bf4cb12fd6.png">

**Comment by janahintal** [comment]
QA Passed. Moving to Done. Thanks. 
Tested in: https://4170-rc0-enterprise.demo.design.infor.com/components/tabs/example-composite-form.html across all browser, OS and devices.
