### ISSUE TITLE
Firefox non-inline field errors shrink dropdowns

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#1770]
**Describe the bug**
When adding a non-inline error icon/tooltip to a dropdown in Firefox, the field shrinks and overlapping occurs.

**To Reproduce**
See this code:
https://gist.github.com/awbuboltz/3386b57f9a9d85e134db61460ae39e58

**Expected behavior**
Other browsers leave the size as-is and just shows the error icon and tooltip.

**Version**

- ids-enterprise: master

**Screenshots**
I have a size 35px dropdown here, it shrinks and overlaps to the point of not being able to see it.
![image](https://user-images.githubusercontent.com/2107139/54052238-80effa00-41a9-11e9-9236-b72136b80acf.png)

**Platform**
 - Browser Name: Firefox

**Additional context**
https://gist.github.com/awbuboltz/3386b57f9a9d85e134db61460ae39e58

**Comment by tmcconechy** [comment]
Adding to the sprint to QA as this was submitted as a fix

**Comment by brianjuan** [comment]
https://4170-beta0-enterprise.demo.design.infor.com/components/dropdown/test-firefox-error-positioning.html
Passed QA on both Mac and Windows Firefox, moving to Done.
