### ISSUE TITLE
Datagrid: Row status disappears when changing a page or a row is added

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1771]
**Describe the bug**
Datagrid: Row status disappears when changing a page or a row is added

**To Reproduce**
1. Go to http://4160-rc2-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Click "Add Row Status" button, row status will show
3. Click "Next Page" button
4. See issue: Row status will disappear
5. Go back to previous page, row status are also disappeared
6. Reload the page
7. Click "Add Row Status" button again, row status will show
8. Click ... menu then click "+ Add"
9. See issue: Row status will disappear

**Expected behavior**
Row status should not disappear when a page is changed or a row is added.

**Version**
v4.16.0-beta0 - v4.16.0-rc2

**Screenshots**
No screenshots applicable.

**Platform**
 - All Devices, OS and browsers.

**Additional context**
No additional context.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
