### ISSUE TITLE
Datagrid Editable: Gray selection background stays in previous rows

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1772]
**Describe the bug**
Datagrid Editable: Gray selection background stays in previous rows when selecting in a dropdown.

**To Reproduce**
1. Go to http://4160-rc2-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. On the Action column of the first row, select any value in the dropdown
3. On the second row, select any value in the dropdown, repeat in every row
4. See issue: Gray selection will stay on the previous rows. On the video below, it stays in Row 1, 3 and 4

**Expected behavior**
Gray background should not stay when selection is removed.

**Version**
v4.16.0-beta0 - v4.16.0-rc2

**Screenshots**
![dg_graybg](https://user-images.githubusercontent.com/39508864/54114057-87d67100-4424-11e9-871e-8a7846228f6b.gif)

**Platform**
 - All browsers except Edge and IE

**Additional context**
No additional context.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
