### ISSUE TITLE
Performance solution needed for tree grids with large datasets

### ISSUE THREAD

**Issue by chrisfried** [infor-design/enterprise#1780]
**Describe the bug**

- If a flat data grid has a large data set, performance is improved greatly by limiting the number of rows drawn at one time through paging. 
- Paging only accounts for top level rows when used with a tree grid
- If a dataset has large collections of child nodes, this can result in the tree grid drawing attempting to draw thousands of rows despite page length being set to a reasonable number.
- This tends to crash the browser tab.

**To Reproduce**
You can see a sample of how tree grid and paging interact here: https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-tree-paging

**Expected behavior**
I'm not saying child nodes should _always_ be spread across multiple pages, but a setting that change the paging behavior from "the next **n** top level rows + all of their children" to "just the next **n** rows, whatever their depth" would be nice.

I'm open to other solutions, that's just what first came to mind. It's not entirely ideal. Say there's a row at the top of the current page with a depth of 4. Needing to page backwards, perhaps several times, to understand the context of that row would not be a great experience. But it would be better than the page not loading.

**Version**

- ids-enterprise: 4.15.0

**Screenshots**
![image](https://user-images.githubusercontent.com/422381/54220025-b5b3c800-44ad-11e9-9f3d-f1d365b1c7ff.png)

**Platform**
 - OS Version: Win 10
 - Browser Name: Chrome
 - Browser Version: Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Comments and thoughts from the MS teams chat on this:

- Maybe there can be a way to improve the performance a bit but it still might have a slow down, especially in IE. 
- Maybe need to make paging respect the total number of rows and not the top level? 
- Or introduce some feature like "Load More" when you hit a threshold

What kind of times are you know getting?
- Tested browsers?
- What else on the page?
- What is the shape of the data and volume?
- How many columns?

**Comment by chrisfried** [comment]
> What kind of times are you know getting?

If the browser doesn't just hang, load times are over a minute.

> Tested browsers?

I've only tested Chrome.

> What else on the page?

Several smaller components, nothing that makes a dent in that load time.

> What is the shape of the data and volume?

- a single top level node
  - with a couple
  - child nodes
    - but
    - hundreds
      - to thousands 
      - of rows
        - beyond
        - that
          - upwards
            - of seven
              - levels deep

> How many columns?

10-ish

**Comment by chrisfried** [comment]
Our current workaround:

- We start with the tree collapsed.
- While a row is collapsed, we store the items that _should_ be in the row's `children` property in a `hiddenChildren` property so the datagrid doesn't process them.
- When an item is expanded, we restore the `children` property and refresh the datagrid.
- When an item is collapsed, we move the children back to `hiddenChildren`.

This gives us a datagrid that works, though there's a small "load" time when a row is expanded.

If a user decides to expand _every_ row in the tree at once, the refresh will still grind to a halt. Our users should never _need_ to expand every row at once, but that doesn't mean they won't do it anyway.

**Comment by chrisfried** [comment]
The major limitation of this workaround is that the datagrid filters aren't run against collapsed rows.

**Comment by tmcconechy** [comment]
There is an option `allowChildExpandOnMatch` that will control if filters run on hidden rows. I think thats the one, and it will work as you expect when set to true.

**Comment by chrisfried** [comment]
The trick is that we're "hiding" the collapsed children _from_ the datagrid. If the datagrid knows about them, it chugs through the thousand of them and crashes the browser. I very much doubt that option will find them.

**Comment by tmcconechy** [comment]
Working on this as part of #4340 - so will just use that issue instead
