### ISSUE TITLE
Demoapp: Directory list hyperlinks are sometimes incorrect

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1783]
**Describe the bug**
On certain directly listing URLs, the hyperlinks rendered on the page will not correctly link to test/example pages.

**To Reproduce**
1. Go to http://localhost:4000/components/listview (no slash at the end) and  http://localhost:4000/components/listbuilder
1. Click any hyperlink
1. The browser will attempt to navigate to a page inside the "components" folder instead of the "listview" folder.

**Expected behavior**
All the links on this page should be correct.  It should work the same as if you see the listing on http://localhost:4000/components/listview/list

**Version**
Found in v4.16.x

**Screenshots**
n/a

**Platform**
n/a

**Comment by jbrcna** [comment]
**QA Passed**
The issue is now resolved. moving this ticket to Done. Thanks
v4.28.0-dev
https://master-enterprise.demo.design.infor.com/components/listview
https://master-enterprise.demo.design.infor.com/components/listbuilder
