### ISSUE TITLE
Widget: empty datagrid cuts off columns when in a widget

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#1785]
**Describe the bug**
An empty datagrid's columns overflow and are cut off in when in a widget.

**To Reproduce**
1. Copy [test-empty-datagrid.zip](https://github.com/infor-design/enterprise/files/2962825/test-empty-datagrid.zip) into the codebase under app/views/components/homepage
2. Navigate to /components/homepage/test-empty-datagrid
3. See error

**Expected behavior**
Would be able to scroll and see all columns for the empty datagrid

**Version**

- ids-enterprise: v4.17.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/54300803-a30fc080-458b-11e9-8351-281b7282bba0.png)

**Platform**
 - All

**Comment by tmcconechy** [comment]
The solution here is to use the empty message like this example http://latest-enterprise.demo.design.infor.com/components/datagrid/example-empty-message.html

It does work there. I'll check that example out maybe something is interfering when its in a card

**Comment by Sovia** [comment]
When I access that link with a shrunk window (using Chrome), I see price getting cut off without a scroll:
![image](https://user-images.githubusercontent.com/22107636/54301822-aefc8200-458d-11e9-87a9-f11fe0dccc44.png)

**Comment by Sovia** [comment]
I've now seen this on a normal datagrid (not in a widget), with the horizontal scroll bar not appearing when the empty message is being shown. It's in the example at components/datagrid/test-fifty-columns.html

You can see this by commenting out the [dataset ](https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-fifty-columns.html#L65)value, and accessing the page:
![image](https://user-images.githubusercontent.com/22107636/59628481-58f82700-9106-11e9-9ebf-ddbab102238d.png)

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-empty-card.html
http://master-enterprise.demo.design.infor.com/components/datagrid/test-empty-card.html
Passed QA on all browsers including mobile.
