### ISSUE TITLE
Source Sans Font Shows Caps and Digits in different sizes.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1789]
**Describe the bug**
If you have text in caps next to numbers. The source-sans font is showing
https://github.com/adobe-fonts/source-sans-pro/issues/123  - This is fixed in 2.040 - how do we get a new version of the font? 

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-index?theme=uplift&variant=light
2. Most prominent on windows chrome
3. Edit text to something like BuT123oN

**Screenshots**
![image002](https://user-images.githubusercontent.com/814283/54360461-4835a200-463b-11e9-8071-e5946ae4aa55.png)

**Platform**
 - Chrome

**Additional context**
Effects only uplift theme because we made recent decision to not use this theme in the older themes

**Comment by tmcconechy** [comment]
cc @nickwynja @clepore

**Comment by nickwynja** [comment]
We can update the fonts within the `design-system` repo but currently the demo app is accessing the fonts from the Google Fonts API. So a couple options:

1. Update the app serve the font files from `ids-identity` and use `@font-face` to import the fonts
2. Wait until Google updates the fonts to the latest version

**Comment by tmcconechy** [comment]
I think we could do 1 easily enough also this is more "secure" from a veracode standpoint.

**Comment by tmcconechy** [comment]
Removed the datagrid tag. I showed the datagrid in the example but the problem is the font in general.

**Comment by tmcconechy** [comment]
Happy to say this issue is fixed. The font thats now on `<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600&amp;display=swap" rel="stylesheet">` appears to be ok.

The heights of the uppercase and numbers now match:
![Screen Shot 2020-04-29 at 11 43 26 AM](https://user-images.githubusercontent.com/814283/80616327-c820f600-8a0e-11ea-8572-c6750058aae6.png)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://4280-beta1-enterprise.demo.design.infor.com/components/datagrid/example-index?theme=uplift&variant=light

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
