### ISSUE TITLE
DataGrid: method selectedRows is incorrect following addRow

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#1794]
Describe the bug
The datagrid method selectedRows() is returning incorrect information when a row has been added to a grid via the addRow(). 

To Reproduce
1. Using the attached example-selected-rows.html 
2. Select several rows
3. Click on 'Show Selected Rows'  -> note the results in console log 
4. Click on 'Add' (maybe in the overflow menu
5. Click on 'Show Selected Rows' -> note the results in the console log
6. Continue to select / unselect rows in the datagrid, each time checking the selected row by clicking on the 'Show Selected Rows' and noting the results in the console log
7.  At some point the selectedRows will not be correct

**Expected behavior**
selectedRows returns the rows selected

**Comment by claudenbach** [comment]
[Enterprise-1794.zip](https://github.com/infor-design/enterprise/files/2968209/Enterprise-1794.zip)

**Comment by janahintal** [comment]
QA Passed.  Will move to Done. 
Tested in: http://master-enterprise.demo.design.infor.com/components/datagrid/test-selected-rows-addnew.html Across all Browser, OS and devices. Thanks!
