### ISSUE TITLE
Datagrid: Columns misaligned after sorting

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#1797]
**Describe the bug**
When user adjust the column width on Datagrid & performs operation sorting or searching or no. of records per page value change then grid gets distorted.

**To Reproduce**

1. Load the example and go to the example page new example is http://localhost:4000/components/datagrid/test-column-widths-sort.html
2. Resize first column
2. Sort first column
3. See error

**Expected behavior**

**Version**
This issue is observed in 4.15.0 angular version. 
![2](https://user-images.githubusercontent.com/42198413/54411354-18f36380-4715-11e9-874a-25864cea79b5.jpg)

**Screenshots**

**Platform**

 - Browser Name [e.g. chrome, safari, stock browser] Chrome
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)] Version 72.0.3626.121 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Can you adjust the template so we can reproduce this issue? Looks like you just left all the default template in without adding any info on how to reproduce. 

Also a screen shot isnt going to be enough, we will need a sample that we can drop in so we can reproduce the issue as there are too many variables as to what could be happening. You could make this by cloning the project and trying to take an example from app/views/components/datagrid and modifying it to resemble your case. Probably going to need what your using for settings and columns.

We also did fix some column alignment issues in 4.16 so you could try that version

**Comment by dhumalkishor** [comment]
Please refer attached files for setting and columns.
[IGRC_Grid_Example.zip](https://github.com/infor-design/enterprise/files/2977871/IGRC_Grid_Example.zip)

**Comment by dhumalkishor** [comment]
We tried with 4.16 library but still issue is exit.

**Comment by tmcconechy** [comment]
Can you reproduce this on any of our examples? http://master-enterprise.demo.design.infor.com/components/datagrid/list

Im not sure that i could get this example to run? Perhaps try to make one you can drop into either this project or the enterprise-ng project? The thing i'd be interested in is what is `width: AUTO_STYLE` ?

**Comment by dhumalkishor** [comment]
Ignore earlier example.
I have reproduced this issue in enterprise-ng project. Please add below files in latest enterprise-ng. 
[datagrid-width.zip](https://github.com/infor-design/enterprise/files/2982990/datagrid-width.zip)

**Comment by tmcconechy** [comment]
I tried this on the 4.18 (beta and could not reproduce). Im pushing an example to both the EP and NG project so we can test it further there and see if anything is missing. But you could also test 4.18

I thought it was due to the percent width columns mixed with fixed width ones but they seem to be working.

**Comment by janahintal** [comment]
Hi @tmcconechy upon testing in: 
http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html
http://master-enterprise.demo.design.infor.com/components/datagrid/test-column-resize-issue.html
http://master-enterprise.demo.design.infor.com/components/datagrid/test-columns-mixed.html

Upon resizing the column, the last column also moved left.
<img width="1612" alt="Screen Shot 2019-05-08 at 12 33 38 PM" src="https://user-images.githubusercontent.com/45757016/57350137-6decac80-718f-11e9-8e3b-fe990e91c214.png">
<img width="1606" alt="Screen Shot 2019-05-08 at 12 33 56 PM" src="https://user-images.githubusercontent.com/45757016/57350139-6f1dd980-718f-11e9-8169-3f1b456db5e1.png">
<img width="1603" alt="Screen Shot 2019-05-08 at 12 34 11 PM" src="https://user-images.githubusercontent.com/45757016/57350142-70e79d00-718f-11e9-8c59-403b8df2036c.png">

**Comment by tmcconechy** [comment]
This is currently normal behavior because you are moving into fixed width mode so there may be a gap on the last column. Let’s make a separate issue for that as it’s been complained about a lot. Maybe we can change it to something different

**Comment by tmcconechy** [comment]
moving back to QA column and i added an issue for what you noted as its unrelated https://github.com/infor-design/enterprise/issues/2130

**Comment by janahintal** [comment]
Hi @tmcconechy thanks for the response. No issues so far than the above. Will move this ticket to Done since another issue has been filed. Thanks!
