### ISSUE TITLE
Demo app: Color hexes don't match up with changing themes

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1801]
**Describe the bug**
The hexes are hard-coded so when changing themes, the hexes don't change.

**To Reproduce**
1. Go to:
    - <https://master-enterprise.demo.design.infor.com/components/colors/example-index.html>
    - <https://master-enterprise.demo.design.infor.com/components/colors/example-index.html?theme=uplift-alpha>
- Notice that the colors do not match the hexes when using the uplift theme.

**Expected behavior**

**Version**
- latest

**Screenshots**
The background colors change, but the listed "hex" text does not:
<img width="481" alt="Screen Shot 2019-03-15 at 2 12 37 PM" src="https://user-images.githubusercontent.com/742319/54452832-6c24e080-472c-11e9-905a-8497c57573d5.png">

**Platform**
- All

**Additional context**

**Comment by brianjuan** [comment]
http://localhost:4000/components/colors/example-index.html?theme=uplift 
http://master-enterprise.demo.design.infor.com/components/colors/example-index.html?theme=uplift
Passed QA testing on all browsers. Will test again once beta is deployed.
