### ISSUE TITLE
Having a scrollable datagrid with the columns staying on top.

### ISSUE THREAD

**Issue by rvilleno** [infor-design/enterprise#1807]
**Is your feature request related to a problem? Please describe.**
When scrolling down a datagrid with several records, the columns on top are not locked.

**Describe the solution you'd like**
To have an option in the soho-datagrid to lock the header column when scrolling down so that the column header does not disappear from view when scrolling to the bottom of the grid.

**Describe alternatives you've considered**

**Additional context**
![358EA4E9-9BC6-4BAF-9A17-8E62CC5C019D](https://user-images.githubusercontent.com/10869544/54507891-69212e80-497e-11e9-9ea4-f2e84166faa3.GIF)

**Comment by tmcconechy** [comment]
This is already possible check out any of the examples with "fixed header" in the description http://latest-enterprise.demo.design.infor.com/components/datagrid for example http://latest-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html

Basically to achieve this you just need to constraint the height of the datagrid and it will "just work". If needed you can use some of the same classes as the example: https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-fixed-header.html#L2
