### ISSUE TITLE
RTL: Searchfiled with categoryMultiselect: true misaligned

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#1811]
**Describe the bug**
Using Locale.set('ar-SA') on searchfields with multiselect doesn't have the proper RTL styling.

**To Reproduce**
1. Add Locale.set('ar-SA') on http://localhost:4000/components/searchfield/example-categories-full?locale=ar-SA
2. Click on 'Category-Driven Multi-Selectable Searchfield'
3. See error

**Expected behavior**
No overlapping checkboxes.

**Version**

- ids-enterprise: master

**Screenshots**
![image](https://user-images.githubusercontent.com/2107139/54553514-57d92180-4980-11e9-8c3e-bcfbce8c81c4.png)

**Comment by SofiK** [comment]
Now there is only a missing margin to the text left to do in this ticket (text is above the checkbox, but the checkbox is correctly placed: https://design.infor.com/code/ids-enterprise/latest/demo/components/searchfield/example-categories-full?locale=ar-SA#)

**Comment by brianjuan** [comment]
Passed QA in all browsers. Moving to Done, will retest once beta is deployed.
Tested in http://master-enterprise.demo.design.infor.com/components/searchfield/example-categories-full.html?locale=ar-SA
![image](https://user-images.githubusercontent.com/39508864/72065458-37b48d80-3319-11ea-963a-ade658dea488.png)

**Comment by brianjuan** [comment]
Passed QA in beta as well, tested in http://4250-beta0-enterprise.demo.design.infor.com/components/searchfield/example-categories-full.html?locale=ar-SA.
