### ISSUE TITLE
RTL: lookups in a field-short container misaligned

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#1812]
**Describe the bug**
RTL lookups with a small width in field-shorts don't look right.

**To Reproduce**
Create a 54px; size 2 lookup in a field-short and run it in RTL.

**Expected behavior**
Should look the same as LTR but flipped. It appears that the padding just isn't updated on the input.

**Version**

- ids-enterprise: master

**Screenshots**
Width 54px with two character value
![image](https://user-images.githubusercontent.com/2107139/54556502-fa949e80-4986-11e9-9736-43b882fdccb6.png)

Width 54px RTL with two character value
![image](https://user-images.githubusercontent.com/2107139/54556461-e650a180-4986-11e9-8ddf-a47097097d87.png)

**Additional context**
Here's the code I used for the field.
`<div class="field-short">`
      `<label for="lookup" class="label">Lookup Field-short RTL</label>`
      `<input id="lookup" class="lookup" type="text" value="DA" style="width: 54px;"/>`
`</div>`

**Comment by tmcconechy** [comment]
Test this in uplift as well.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/93211429-cffdee80-f793-11ea-8254-c5f846c47490.png)
