### ISSUE TITLE
RTL: Splitter doesn't work

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#1813]
**Describe the bug**
Splitter drags the wrong direction in RTL.

**To Reproduce**
1. Go to http://localhost:4000/components/splitter/example-index.html?locale=ar-SA
2. Flip to ar-SA

**Expected behavior**
Splitter should drag the proper direction.

**Version**

- ids-enterprise: master

**Comment by jbrcna** [comment]
**QA Failed**
v4.29.0-beta0
https://4290-beta0-enterprise.demo.design.infor.com/components/splitter/example-index.html?locale=ar-SA
![image](https://user-images.githubusercontent.com/56722184/82890860-6efda100-9f7f-11ea-972e-30fdcc85bedf.png)

https://4290-beta0-enterprise.demo.design.infor.com/components/splitter/test-iframes.html
![image](https://user-images.githubusercontent.com/56722184/82890825-60af8500-9f7f-11ea-83ea-87558aee2454.png)

Expected result:
![image](https://user-images.githubusercontent.com/56722184/82890894-7d4bbd00-9f7f-11ea-96de-6e65524b667d.png)

**Comment by jbrcna** [comment]
also in `Firefox`
![image](https://user-images.githubusercontent.com/56722184/82891352-2abed080-9f80-11ea-806a-fb2bef80f155.png)

**Comment by tmcconechy** [comment]
@jbrcna Im not seeing any of these issues. I think the issue is it remembers the position it loaded in before. So maybe try to resize the splitter back to another position and then reload the page. Or try a new icognito tab or clear browser cache.

Moving back to QA so you can try some more.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by jbrcna** [comment]
Thank you @tmcconechy you're absolutely right. I used incognito for the screenshot below.
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/56722184/83006669-2a3c3d80-a045-11ea-9681-997923da1ccf.png">

**Comment by awbuboltz** [comment]
Hey @tmcconechy , I'm seeing this being reversed again when trying to drag, is that correct behavior? Seems strange.

**Comment by tmcconechy** [comment]
I guess it does seem strange? Im not sure if its wrong or not tho either. Do you remember it working this way @deep7102 and @jbrcna ?

**Comment by jbrcna** [comment]
Hi @tmcconechy the behavior was change to a normal dragging behavior in v4.29. Upon investigation, I can see that the dragging behavior is inverted starting from v4.34

**Comment by deep7102** [comment]
Yes @tmcconechy it looks something changed, it was working fine before.

**Comment by tmcconechy** [comment]
My guess is it is this commit. Can you guys take a look @deep7102 @jmacaluso711 ?

**Comment by deep7102** [comment]
Sure @tmcconechy, I take a look to it.

**Comment by jbrcna** [comment]
The issue is now resolved.
v4.37.0-rc0
https://4370-rc0-enterprise.demo.design.infor.com/components/splitter/example-index.html?locale=ar-SA
