### ISSUE TITLE
Cropped Header for Builder Panel When Text is Long

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#1814]
**Describe the bug**
In the Builder Panel Header, when the text is very long, it is being cropped. This becomes an issue for us when app is viewed on mobile because space becomes limited and fewer characters can be shown. 

Minor issue on our end, mostly occurs on mobile devices. Can this be done like the headers of other pages wherein an ellipses will be shown when the text is too long?

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/patterns/builder-wizard.html'
2. Change the Builder Panel title to a longer text. Make the browser smaller or when viewed in Mobile. The title is cropped.
![image](https://user-images.githubusercontent.com/41028784/54579118-ffb42500-4a3c-11e9-8823-d3bff1118ea2.png)

**Expected behavior**
Can this be shown like in the Header of Pages wherein an ellipses is shown.

![image](https://user-images.githubusercontent.com/41028784/54578119-81a24f00-4a39-11e9-94fb-5ce3d6d860bd.png)

**Comment by tmcconechy** [comment]
Added to the sprint as this issue was submitted by @marknolaninfor . Thanks!

**Comment by janahintal** [comment]
Hi @tmcconechy, upon testing in http://localhost:4000/patterns/builder-subtitle-test.html using Windows 10 IE11, the sub-header is still cropped and doesn't have ellipsis. Please see screenshot below. 

<img width="915" alt="Screen Shot 2019-04-01 at 6 14 41 PM" src="https://user-images.githubusercontent.com/45757016/55320738-71af5400-54aa-11e9-9fb0-735f00769ed9.png">

**Comment by tmcconechy** [comment]
@marknolaninfor What do you think about @janahintal 's comments? Is this something we can fix?

**Comment by clepore** [comment]
Just as an FYI, the cutoff date for `4.18.0` is next Friday (4/19).

**Comment by marknolaninfor** [comment]
@tmcconechy 

I believe that it is an issue with the </br> and how IE is applying the css.
'https://stackoverflow.com/questions/36071024/multiline-ellipsis-with-br-tags-only-adds-ellipsis-to-first-line-in-ie11-edge'

It can be solved by changing the panel-subhead from a span after the </br> to a simple div and apply the style directly to the div. This change would then be a breaking change for anyone using the 'panel-subhead' as they would have defined it as a span and not a div.

![image](https://user-images.githubusercontent.com/39749678/55852133-db121f80-5b9a-11e9-8b07-2b57c225f565.png)

**Comment by tmcconechy** [comment]
Ok, I think we can make that change to the sample as long as both work. They want the ellipsis to show they then have to make that change.

 I also wonder if you keep it a div and just change the css display property so it’s an in-line element like a span if that also works and if that’s any better?

**Comment by janahintal** [comment]
Hi @marknolaninfor, upon checking in http://localhost:4000/patterns/builder-subtitle-test.html using Win10 IE11, the sub-header is still cropped doesn't have any ellipsis in responsive view. Please see screen captured below. Thank you. 

<img width="785" alt="Screen Shot 2019-04-15 at 6 09 30 PM" src="https://user-images.githubusercontent.com/45757016/56124701-c9b98080-5fa9-11e9-9cb3-4baf87e19d46.png">

**Comment by tmcconechy** [comment]
Waiting for https://github.com/infor-design/enterprise/pull/1939 to be merged. Seemed i moved this over too early

**Comment by janahintal** [comment]
QA Passed. Moving to Done. Thanks!
Tested in: http://master-enterprise.demo.design.infor.com/patterns/builder-subtitle-test.html
