### ISSUE TITLE
Hierarchy not loading on IE 11 Windows 10

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1815]
**Describe the bug**
Hierarchy not loading on IE 11 Windows 10

**To Reproduce**
1. Open Windows 10 IE 11 Browser
2. Goto https://4162-rc0-enterprise.demo.design.infor.com/components/hierarchy/example-index.html
*Notice that the Hierarchy components didn't load on the page. 

**Expected behavior**
Hierarchy Tree should appear in the Page

**Version**
v4.16.0

**Screenshots**
<img width="1981" alt="Screen Shot 2019-03-19 at 1 20 52 PM" src="https://user-images.githubusercontent.com/45757016/54596690-22136600-4a70-11e9-8e6b-7e518c9e9251.png">

**Platform**
- Windows 10 IE 11

**Additional context**
No additional context.

**Comment by CindyMercadoReyes** [comment]
Hi @tmcconechy The image is not appearing for William Moore and Sarah Lee is not appearing on Win 10 IE 11. Please see screen shot attached. 
![Hierarchy_Image not appearing](https://user-images.githubusercontent.com/39101346/54619697-68020700-4a3b-11e9-9ade-930e656b66a2.png)

**Comment by tmcconechy** [comment]
@CindyMercadoReyes Fixed the image thing on #1819
