### ISSUE TITLE
Lookup: Add an example of filtering the value when opening the dialog

### ISSUE THREAD

**Issue by cbeck54** [infor-design/enterprise#1817]
**Is your feature request related to a problem? Please describe.**
The Lookup component, as being used by the App Builder team, presents a blank field with a magnifying glass icon to the user—per SoHo standards, I'm told. As a user, my expectation was that, if I typed something into that field, the component would automatically use that as the Search term. However, it does not work that way. I think it should, because that would be more in line with current practices as I've experienced them and more consistent, I think, with user expectations. 

**Describe the solution you'd like**
The Lookup component, I believe, would work better if the user could type a search term into the Lookup field and the component would automatically accept that and use it as the desired search term, before even opening the dialog.

**Comment by tmcconechy** [comment]
Maybe this is something we could consider but there are a few options.

1) Use the beforeshow event or source callback to grab the value and use that as a parameter to your data query fx: http://master-enterprise.demo.design.infor.com/components/lookup/test-beforeshow.html

2) You can add auto complete on top http://master-enterprise.demo.design.infor.com/components/lookup/test-autocomplete-and-lookup.html

**Comment by tmcconechy** [comment]
Are you thinking of putting it on the search field and searching that way? Issue with that is that is optional

**Comment by cbeck54** [comment]
I'm not a software developer, I am an information developer; so, I'm not sure what #1 is telling me. 
While #2 sounds like a nice option, that is not what I'm talking about. 
I think your second comment covers it. What I'm proposing is that we take whatever the user types into the text field for the Lookup component and use that as the search term, without requiring the user to type it again into the Search field in the dialog box. 
Are you saying there that it is OK to do what I'm proposing as an option for that type of component?

**Comment by tmcconechy** [comment]
Yes i think thats perfectly fine and people (developers) did do that already. Basically what i am saying for 1. The develop has an api where they can grab the value as the dialog opens and then load data based on that value to present.

We could make a better example for that, but i think it would be doable already with some work by the developer.

**Comment by cbeck54** [comment]
Very good. Thanks for the prompt replies!!

**Comment by tmcconechy** [comment]
Descoping this for now
