### ISSUE TITLE
Hierarchy Component: Sub item feature is not working correctly

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1819]
**Describe the bug**
Hierarchy Component: Sub item feature is not working correctly

**To Reproduce**
1. Go to URL: http://4162-rc2-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html
2. On Window 10 IE 11 make the webpage responsive
3. Click on "Kaylee Edwards" and click on the 3 dots button
4. Scroll down to "Options" then click on Sub item
5. Two issues are occurring:  1st issue: The "Message from webpage" popup window is appearing outside the the webpage
2nd issue: The curly brackets are not containing the URL inside of it. Please see screen shots attached. 

**Expected behavior**
The popup menu should appear within the webpage. In addition, the url should appear with in the curly brackets. 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![Hierarchy 1_Popup message apperas outside the box 1](https://user-images.githubusercontent.com/39101346/54617996-aa761480-4a38-11e9-99af-e2a470fd27e1.png)
![Hierarchy 2_Popup message apperas outside the box 1](https://user-images.githubusercontent.com/39101346/54617997-aa761480-4a38-11e9-9868-d64e8091976a.png)
![IMG_5281](https://user-images.githubusercontent.com/39101346/54622872-cd0c2b80-4a40-11e9-871e-0a1385cff2ce.JPG)

Additionally 
- http://localhost:4000/components/hierarchy/example-index.html -> has no scroll bar on the bottom
- some images do not load on IE -> found these to be two large corrupt so fixed them.

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [Windows 10]
 - Browser Name [IE 11]

**Additional context**
None

**Comment by janahintal** [comment]
No pop-up menu appeared after clicking 'Sub-menu' option. Re-tested in Win10 IE 11. Please advice if this is expected in the fix. @tmcconechy 

Also, upon using iOS devices, the sub-menu option is cut off please see image below. 
Tested in iOS 12 iPhone XS
<img width="446" alt="Screen Shot 2019-04-03 at 2 40 51 PM" src="https://user-images.githubusercontent.com/45757016/55458092-93314c80-561e-11e9-86f1-322a184b72dd.png">


Tested in: http://master-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html & http://master-enterprise.demo.design.infor.com/components/hierarchy/example-index.html across all browsers and OS and devices.

**Comment by tmcconechy** [comment]
I dont think we can fix this problem on IOS. I suggest making a new issue and we can set it to trivial.
This menu is an edge case anyways.

**Comment by janahintal** [comment]
### 

> Seems like this is a general issue unrelated to this fix, so i made #1928
> 
> Moving this back to QA the rest, or you can move to done if the rest seems ok?

Noted on that @tmcconechy. Thanks. No issues aside from #1928. Will now move this to Done. Thank you!
