### ISSUE TITLE
Blockgrid:  Use non-deprecated `select` method internally

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1820]
**Describe the bug**
In some previous refactoring work (Described in #922), the `renderBlock()` and `selectBlock()` methods in Blockgrid were deprecated in favor of the shorter names `render()` and `select()`.  However, the API is still using the original method names internally for its event handlers.

When #1809 is merged and deprecation warnings begin appearing in `master`, anyone using Blockgrid will frequently see these messages.

**To Reproduce**
1. Go to http://localhost:4000/components/blockgrid/example-paging.html
2. Open a dev tools console
3. Click to select/deselect any block
4. See console warnings.

**Expected behavior**

**Version**
- ids-enterprise: master at `v4.17.x`

**Screenshots**

![Screen Shot 2019-03-19 at 1 01 47 PM](https://user-images.githubusercontent.com/3249601/54626257-31ca8480-4a47-11e9-9b4a-ca0ff57458be.png)

**Platform**
n/a

**Additional context**
n/a

**Comment by tmcconechy** [comment]
I actually fixed this, not knowing there was an issue for it. Was trying to reduce the warnings in the tests at the time.
