### ISSUE TITLE
Docs page for Initialize 404s

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#1827]
**Describe the bug**
The docs page for [initialize](https://design.infor.com/code/ids-enterprise/latest/initialize) 404s. We should either generate the docs or remove the item from the `sitemap.yaml`.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/initialize

**Expected behavior**
The page doesn't 404 or it's not included in the sidebar navigation.

**Additional context**
It seems like this docs file isn't being generated because we currently only grab files from `${rootPath}/src/components` and `${rootPath}/docs` but `initialize.md` is in `${rootPath}/src/behaviors`.

**Comment by tmcconechy** [comment]
@nickwynja we werent sure 100% what to do in EP for this? Can you explain? Was just looking across this reviewing @EdwardCoyle 404 PR (seems unrelated but saw this one)

**Comment by nickwynja** [comment]
@tmcconechy Take a look at [`scripts/deploy-documentation.js`](https://github.com/infor-design/enterprise/blob/master/scripts/deploy-documentation.js). In `documentJsToHtml()`, only `${paths.components}/${componentName}/${componentName}.js` are being generated yet `initialize` lives in `/src/behaviors/` not `${paths.components}`.

**Comment by tmcconechy** [comment]
I think this is done because the PR is closed.
