### ISSUE TITLE
Modal removes busy indicator overlay

### ISSUE THREAD

**Issue by tobywicksinfor** [infor-design/enterprise#1828]
**Describe the bug**
If a **Modal** is displayed while a **Busy Indicator** is being shown when the modal closes it removes the busy indicator's `.overlay`.

**To Reproduce**
1. Create a new `BusyIndicator` control. 
2. After the element has been displayed.
3. Show a new `Modal` control.
4. Close the new `Modal` control.

**Expected behavior**
The busy indicator overlay that disallow the user modifying the page should not be removed. 

**References**
The relevant code is: `$('.overlay').remove();` at https://github.com/infor-design/enterprise/blob/b81105dc1f2c6a2edcdbcf92966502d931a235a2/src/components/modal/modal.js#L899

**Version**
 v4.17.0-beta.0

**Screenshots**
With overlay:
![BusyIndicator_WithOverlay](https://user-images.githubusercontent.com/40477207/54727310-0078c280-4bc7-11e9-8d80-a20cbc980b0c.PNG)

After modal has been closed - no overlay: 
![BusyIndicator_NoOverlay](https://user-images.githubusercontent.com/40477207/54727312-02db1c80-4bc7-11e9-8cf7-6cdd696600c6.PNG)

**Platform**
 - OS Version: Windows 10
 - Browser Name Chrome

**Additional context**

**Comment by tmcconechy** [comment]
We probably need to change modal to either track the overlays its using or scope the modal overlays with an extra class and remove just them. (Something like that)

**Comment by tmcconechy** [comment]
Has this possibly been fixed? Can you retest on the latest dev build? Or 4.27 when it comes out?

**Comment by tmcconechy** [comment]
Could not reproduce:

See
https://master-enterprise.demo.design.infor.com/components/busyindicator/test-inside-modal.html
and
https://master-enterprise.demo.design.infor.com/components/busyindicator/test-after-close-modal.html

**Comment by tobywicksinfor** [comment]
@tmcconechy This issue is still occurring in v4.26.2:

![Uploading Busy Indicator and Dialog Clears overlay v4.26.2.gif…]()

**Comment by tmcconechy** [comment]
Can you reproduce it somehow on master? We made some fixed in 4.27-beta0 which you can test but overall im just not 100% sure how to reproduce it in our examples, so might need some help there.

**Comment by tobywicksinfor** [comment]
Hey Tim, on master branch it seems to be not working for the **busyindicator/test-after-close-modal.html.** test page:

git HEAD: 
commit f9dd291caab113ae6752e77e274c89ec8ee34854 
Author: Tim McConechy <tim.mcconechy@infor.com>
Date:   Mon Mar 30 09:57:26 2020 -0400

On a side note, I had a few issues with getting the page to load without errors. Seems like an issue with xlink:href for the SVG icons. I commented that out so that the page could at least load without errors. I assume that is something that is currently a work in progress.

Anyway, here is a clip of the issue:

![busyindicator test-after-close-modal](https://user-images.githubusercontent.com/40477207/77975624-1b395780-7342-11ea-9714-42c485c2e26c.gif)

**Comment by tmcconechy** [comment]
@tobywicksinfor maybe we need an entirely new issue with updated steps and expectations? I'm not seeing the steps above in the video and it seems to work correctly to me.

1) go to https://master-enterprise.demo.design.infor.com/components/busyindicator/test-after-close-modal.html
2) click start to show the busy indicator
3) show the message dialog
4) busy indicator still running in the background - you didnt stop it.
5) close the message dialog
6) busy indicator still running in the background - you didnt stop it.
7) stop it (if you want)

That's just how i see the behavior - and im not certain its necessarily wrong there?

Concerning the error with SVG xhref. Is we did change it from xlink:href to href. So maybe you didnt get the updated svg files to go along with it? If its just the demo app try cleaning things out and freshly building.

```
cd folder_where_it_is
rm -rf node_modules
npm i
npm run build
npm run start
```

**Comment by tobywicksinfor** [comment]
My apologies @tmcconechy it seems to working after running the above steps. So looks like it has been fixed. I think the issue was there because I ran `npm quickstart` rather than `npm run build` and `npm run start`.

**Comment by tmcconechy** [comment]
Great! Sounds good.
