### ISSUE TITLE
Datagrid Validation tooltip does not wrap words correctly across multiple lines

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#1829]
**Describe the bug**
If a validation rule has a long message than the words may not wrap correctly. This required a change to the validation message for the rule.

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/test-editable-validation.html'
2. set the Product Id to "1" to display the validation message
3. See error

**Expected behavior**
The word wrap will not break mid word.

**Version**
master

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/54733114-b7853600-4be7-11e9-8539-9dff027e57c9.png)

**Platform**

 - OS Version: Windows 10
 - Browser Name chrome

**Comment by tmcconechy** [comment]
@marknolaninfor Do we need to make a modification to this example to see the issue? Im seeing this:
![Screen Shot 2019-03-21 at 8 27 27 AM](https://user-images.githubusercontent.com/814283/54752095-3b70fb00-4bb3-11e9-9e59-084f853972bb.png)

**Comment by marknolaninfor** [comment]
The issue did require a change to a validation rule on the example so that the message was long enough to cause the wrapping issue. I have added the example with the fix.

**Comment by tmcconechy** [comment]
Moved to the board for QA purposes. Thanks again @marknolaninfor

**Comment by janahintal** [comment]
QA Passed. 
Tested in: http://localhost:4000/components/datagrid/test-editable-validation.html across all browsers & OS
<img width="376" alt="Screen Shot 2019-04-01 at 3 33 12 PM" src="https://user-images.githubusercontent.com/45757016/55318993-8ee22380-54a6-11e9-99a2-21e9fb537b36.png">
