### ISSUE TITLE
Layouts: Improve code surrounding heights in List/Detail and other two column layouts

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1831]
**Describe the bug**
The CSS selectors in [`_layouts.scss`](https://github.com/infor-design/enterprise/blob/master/src/layouts/_layouts.scss#L426-L698) surrounding the two column layout and the heights of various inner components could use some simplification.  At the time many of these were written, our browser support included some that did not support Flexbox.  Our lowest-supported browser is now IE11, so we should work to improve these layouts by:

- [ ] Make CSS selectors less specific wherever possible.
- [ ] Replace all specific, calculated heights on sidebar sub-components with Flexbox layouts.
- [ ] Test on all two column layout-based screens
  - List/Detail Pattern
  - Builder
  - Vertical Tabs
  - Stepprocess
- [ ] Update e2e test baseline images for any shifting

![Screen Shot 2019-03-21 at 12 17 48 PM](https://user-images.githubusercontent.com/3249601/54767546-bcd88580-4bd3-11e9-81f2-7c5dfaf7096e.png)

**Comment by tmcconechy** [comment]
Descoping this for now
