### ISSUE TITLE
Datagrid: disabled checkbox appears actionable

### ISSUE THREAD

**Issue by slsheridan** [infor-design/enterprise#1841]
**Describe the bug**
In a datagrid cell that is a checkbox, and the checkbox cell is disabled, the cell is gray but the checkbox itself is blue. 

**Expected behavior**
When the checkbox is not editable and it is checked, the checkbox should be gray.

**Version**
4.12

**Screenshots**
![image](https://user-images.githubusercontent.com/48289278/54829340-91fe3800-4c8c-11e9-92cc-48b7166ead76.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 73.0.3683.86 (Official Build) (64-bit)

**Additional context**
Column settings:
editor = Soho.Editors.Checkbox
formatter = Soho.Formatters.Checkbox
isEditable = false

**Comment by tmcconechy** [comment]
Solution would be to use the disabled checkbox style when the row is disabled with the column isEditable option

**Comment by janahintal** [comment]
QA Passed. Will Moved to Done. 
Tested in: http://master-enterprise.demo.design.infor.com/components/popupmenu/example-selectable-multiple.html across all browser, OS and devices.
