### ISSUE TITLE
Removing last tab from tabs component cause exception

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#1848]
**Describe the bug**
Tabs component require at least one tab to exist. If you remove the last one exception is thrown

**To Reproduce**
Remove last tab

**Expected behavior**
No exception thrown
**Version**
4.16.1

**Additional context**
It was no problem in 4.9.0

**Comment by tmcconechy** [comment]
Descoping this for now, cant seem to reproduce this. Also in most of the examples we decided to make sure one tab always stays. https://master-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html
