### ISSUE TITLE
Datepicker overlapping focus on previous and next arrow keys

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1854]
**Describe the bug**
Datepicker overlapping focus on previous and next arrow keys. Also the alignment is off in Win10 IE 11. 

**To Reproduce**
1. Go to http://4170-rc0-enterprise.demo.design.infor.com/components/datepicker/example-month-year-format.html
2. Click tab until it focuses on 'Left Arrow key' in the calendar or just click the 'Left arrow key' to focus. 

**Expected behavior**
Focus should not overlap other fields

**Version**
v4.17.0

**Screenshots**
<img width="922" alt="Screen Shot 2019-03-27 at 2 30 58 PM" src="https://user-images.githubusercontent.com/45757016/55055354-acc21980-509d-11e9-8dd2-f1db77e6a71e.png">

Win10 IE 11:
<img width="796" alt="Screen Shot 2019-03-27 at 2 51 02 PM" src="https://user-images.githubusercontent.com/45757016/55056026-e72cb600-509f-11e9-9b3e-26a5aa119f8d.png">

**Platform**
- All browser, os and devices 
- Windows 10 IE 11

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Tested this back to 4.14 i do not think this ever had quite enough space but this was exacerbated, when we changed the icons in 4.15

**Comment by tmcconechy** [comment]
Since the entire dialog changed on #1854 this screen no longer exists in the form on this issue. So closing. Nothing to test here so moving to done
