### ISSUE TITLE
Datepicker calendar is cut off when in mobile landscape mode

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1855]
**Describe the bug**
Datepicker calendar is cut off when in mobile landscape mode

**To Reproduce**

1. Using mobile device , flip to landscape mode then open a browser
1. Go to 'http://4170-rc0-enterprise.demo.design.infor.com/components/datepicker/example-sizes.html' or any date picker example page. 
2. Click the Calendar icon to open the Datepicker 

**Expected behavior**
Datepicker calendar should not be cut off even in Landscape mode

**Version**
v4.17.0

**Screenshots**
<img width="946" alt="Screen Shot 2019-03-27 at 3 49 41 PM" src="https://user-images.githubusercontent.com/45757016/55061867-c10f1200-50af-11e9-8fbb-300161f738b5.png">

**Platform**
 - Mobile Devices, iOS & Android

**Additional context**
No Additional context.

**Comment by tmcconechy** [comment]
This is somewhat correct as when on that size device there is really no room so its just flowing to what fits. But i think it would look better if either the buttons on the bottom dont stretch or it opens towards the right side in this size device

**Comment by tmcconechy** [comment]
Duplicates #925
