### ISSUE TITLE
Expandable Area font size are getting bigger in iOS devices after switching from Portrait angle to Landscape

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1856]
**Describe the bug**
Expandable Area font size are getting bigger in iOS devices after switching from Portrait angle to Landscape

**To Reproduce**
1. Using iOS device open a Browser in Portrait mode

2. Open http://4170-rc0-enterprise.demo.design.infor.com/components/expandablearea/example-index.html

3. Flip the phone to Landscape mode. 

**Expected behavior**
Font Size should be consistent and smaller. 

**Version**
v4.17.0

**Screenshots**
<img width="1073" alt="Screen Shot 2019-03-27 at 7 14 13 PM" src="https://user-images.githubusercontent.com/45757016/55071803-8f547600-50c4-11e9-8fbc-2aa3d3a869c3.png">

**Platform**
- iOS devices

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Seems like the devices is zooming in or something. Im not sure why, but it's probably worth investigating at some point. If we see any other issues like this let's not raise anymore about the same thing. This probably isn't our code, but i agree let's take a look at this when we can.

**Comment by tmcconechy** [comment]
Noticed this testing and applied a fix with https://github.com/infor-design/enterprise/pull/4014

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
