### ISSUE TITLE
Notifications: No background color in Internet Explorer

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1857]
**Describe the bug**
Notification: No background color in Windows Internet Explorer.

**To Reproduce**
1. Open Internet Explorer, go to https://4170-rc0-enterprise.demo.design.infor.com/components/notification/example-index.html#
2. See issue: No background color on the Notifications

**Expected behavior**
There should be a background color in Notifications

**Version**
- ids-enterprise: v4.11.0 - v4.17.0-rc0

**Screenshots**
<img width="671" alt="Screen Shot 2019-03-27 at 6 06 00 PM" src="https://user-images.githubusercontent.com/39508864/55067629-02f18580-50bb-11e9-8210-a829bd848452.png">

**Platform**
 - Windows Internet Explorer

**Additional context**
No Additional Context.

**Comment by tmcconechy** [comment]
This relates to https://github.com/infor-design/design-system/issues/294 once we change this colors on a new issue when thats decided we should also test and fix this.

**Comment by kayiuho** [comment]
Just curious - do we know why the current colors (`background-color: rgba(213, 246, 192, 0.4)` for example) aren't showing on IE? Is it because of the opacity? If that's the case, going "solid" in the proposed solution would fix this bug.

**Comment by tmcconechy** [comment]
@kayiuho I think its just because we use css `RGBA` there which is not supported on IE. We should convert these to HEX or use the HEX OR RGB with an actually css opacity. So, coding error.

**Comment by tmcconechy** [comment]
We still need to make the changes here

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks!
Tested in: http://master-enterprise.demo.design.infor.com/components/notification/example-index.html#

**Comment by brianjuan** [comment]
Moving to Failed QA, issues still exists on http://4180-beta0-enterprise.demo.design.infor.com/components/notification/example-index.html#

**Comment by clepore** [comment]
So the real issue is that the classes are not being set on the notification elements:

<img width="595" alt="Screen Shot 2019-04-22 at 11 58 24 AM" src="https://user-images.githubusercontent.com/742319/56509843-0b8c7e80-64f6-11e9-9297-d8eafb3e6bfd.png">

**Comment by brianjuan** [comment]
http://4180-rc0-enterprise.demo.design.infor.com/components/notification/example-index.html
Passed QA testing on Windows IE, moving to Done.
