### ISSUE TITLE
Positive/Negative Chart: Cannot select charts after initial selection

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1860]
**Describe the bug**
Positive/Negative Chart: Cannot select charts after initial selection

**To Reproduce**
1. Go to https://4170-rc0-enterprise.demo.design.infor.com/components/positive-negative/example-index.html
2. Click on any bar, the charts will be like disabled
3. Try to select other bar or try to select by clicking a legend
4. See issue: Chart won't be selected

**Expected behavior**
Charts can be selected

**Version**
- ids-enterprise: v4.7.0 - v4.17.0-rc0

**Screenshots**
![positive-negative](https://user-images.githubusercontent.com/39508864/55069281-a001ed80-50be-11e9-8f10-e7e0531eb5f1.gif)

**Platform**
 - All Devices, OS and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Tested back to 4.14, i do not think this ever worked correctly.

**Comment by tmcconechy** [comment]
descoping this for now
