### ISSUE TITLE
Field Filter fields are cut off when in smaller mobile screen and also when minimizing in IE 11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1861]
**Describe the bug**
Field Filter fields are cut off when in smaller mobile screen and also when minimizing in IE 11

**To Reproduce**
1. Goto http://4170-rc0-enterprise.demo.design.infor.com/components/field-filter/example-index.html in win10 IE11
2. Minimize the Screen 
3. OR Using iPhone SE, goto http://4170-rc0-enterprise.demo.design.infor.com/components/field-filter/example-index.html

**Expected behavior**
Fields should not get cut off

**Version**
version 4.17.0

**Screenshots**
<img width="351" alt="Screen Shot 2019-03-27 at 7 39 52 PM" src="https://user-images.githubusercontent.com/45757016/55073608-13a8f800-50c9-11e9-9287-88cae5d6b062.png">

Win10 IE11
<img width="449" alt="Screen Shot 2019-03-27 at 7 47 35 PM" src="https://user-images.githubusercontent.com/45757016/55073645-33d8b700-50c9-11e9-926b-1b0044da76d3.png">

**Platform**
- Small screen devices
- Windows 10 IE 11

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
As this is a Landmark component, putting as a Landmark issues for fixing.

**Comment by CindyMercadoReyes** [comment]
This issue passed QA and is now resolved.
