### ISSUE TITLE
Field options spin box focuses outside of the field

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1862]
**Describe the bug**
Field options spin box focuses outside of the field

**To Reproduce**
1. Go to http://4170-rc0-enterprise.demo.design.infor.com/components/field-options/example-index.html
2. Play with spinbox field

**Expected behavior**
It should not have extra focus or another focus outside the spinbox field

**Version**
v4.17.0

**Screenshots**
<img width="904" alt="Screen Shot 2019-03-27 at 8 10 52 PM" src="https://user-images.githubusercontent.com/45757016/55075669-8a94bf80-50ce-11e9-9f94-ba3a0a63a0e7.png">

**Platform**
All browsers, devices and OS

**Additional context**
No additional context

**Comment by tmcconechy** [comment]
As this is a Landmark component, putting as a Landmark issues for fixing.

**Comment by tmcconechy** [comment]
Might be out of scope? But i think it looks a little odd the way the box shadow is placed on focus.

![Screen Shot 2019-05-15 at 3 01 37 PM](https://user-images.githubusercontent.com/814283/57801739-6d6d8c00-7722-11e9-87e3-4c03108f144a.png)
![Screen Shot 2019-05-15 at 3 01 42 PM](https://user-images.githubusercontent.com/814283/57801742-6fcfe600-7722-11e9-938c-8cec08c060a9.png)

Is it possible to adjust that?

**Comment by brianjuan** [comment]
Moving to failed QA, there is still an alignment issue on Clearable input.
<img width="359" alt="Screen Shot 2019-05-21 at 6 35 32 PM" src="https://user-images.githubusercontent.com/39508864/58089474-6bf70480-7bf7-11e9-9227-dce60f1b964e.png">

**Comment by janahintal** [comment]
QA Passed. 
Verified in: http://4190-beta0-enterprise.demo.design.infor.com/components/field-options/example-index.html across all browser and OS. Thanks
