### ISSUE TITLE
PopupMenu: Disabled Submenus Open

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1863]
**Describe the bug**
The disabled submenus are opening where on previous versions they did not.

**To Reproduce**
1. Go to https://4140-enterprise.demo.design.infor.com/components/popupmenu/example-disabled-submenus.html
2. Click on the button to open the popup menu
3. Hover the disabled submenu
4. See that it doesn't open 
5. Compare to https://4150-enterprise.demo.design.infor.com/components/popupmenu/example-disabled-submenus.html

**Expected behavior**
A disabled submenu should not open (because its disabled 😃 )

**Version**
- ids-enterprise v4.15.0 this behavior changed

**Platform**
 - Any

**Additional context**
Noted on QA issue https://github.com/infor-design/enterprise/issues/1687#issuecomment-477088658

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks!
Tested in: http://master-enterprise.demo.design.infor.com/components/popupmenu/example-disabled-submenus.html
