### ISSUE TITLE
Releases: Automate the deploy to the AWS CDN in release it

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1864]
**Is your feature request related to a problem? Please describe.**

On each release we have to manually run this command
https://github.com/infor-design/enterprise/blob/master/package.json#L59

In order to get the sohoxi files up in the AWS CDN (link https://cdn.hookandloop.infor.com/sohoxi/4.15.0/js/sohoxi.min.js)

Secondly the https://www.unpkg.com/ids-enterprise@4.16.2/dist/js/ CDN does not have a minimized js. Should see if that can be fixed too or decide one or the other formally.

I have the AWS keys for who takes this

**Describe the solution you'd like**
Update (releaseit?)so that it runs the command to deploy during the release cycle.

**Describe alternatives you've considered**
Do it manually and forget everytime.

**Comment by clepore** [comment]
Have we confirmed that anyone still uses this?

**Comment by tmcconechy** [comment]
Yes, because it came up the other day, they asked why the new version wasnt there.
