### ISSUE TITLE
Notification: Change background colors for better saturation

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1865]
**Is your feature request related to a problem? Please describe.**

Implement the proposed design changes on https://github.com/infor-design/design-system/issues/294. Which is simple to change the background colors to Amber01, Azure01, Emerald01 and Ruby01.

Note Ruby01 will be changed in a token in IDS Identity first.

Should also fix https://github.com/infor-design/enterprise/issues?utf8=%E2%9C%93&q=notification++is%3Aopen+ at the same time. As all issues are related

**Describe the solution you'd like**
Change the 4 colors on http://latest-enterprise.demo.design.infor.com/components/notification/example-index.html to use the tokens Amber01, Azure01, Emerald01 and Ruby01.

**Additional context**
https://github.com/infor-design/design-system/issues/294

**Comment by tmcconechy** [comment]
We still need to make the changes here to use the tokes on the EP side

**Comment by brianjuan** [comment]
http://4180-beta0-enterprise.demo.design.infor.com/components/notification/example-index.html
Passed QA testing on all browsers, background colors are now updated. Moving to Done.
