### ISSUE TITLE
Personalize: API to retrieve available themes and their personalization colors.

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#1866]
**Is your feature request related to a problem? Please describe.**
Api with the ability to 
- get the available themes. 
- get the relevant colors name and their hex values for a given theme. 

**Describe the solution you'd like**
```
interface Theme {
  id: string;        // internal id of the theme
  name: string;  // display value
}

interface ThemeColors {
  id: string;  // internal id of theme personalization color
  name: string;  // display value of color for UI
  color: string;  // hex value of the color to set on the personization api
}

interface ThemeApi {
  getThemeNames(): Theme[];
  getPersonalizationColors(theme: Theme | id: string): ThemeColors[];
}
```
**Describe alternatives you've considered**
An alternative could be just to have the names listed out as design token in the ids-identity system. But translation would be an issue there.

**Additional context**
Right now we have the names hard coded into the UI. 
![image](https://user-images.githubusercontent.com/4737815/55083954-62777300-5072-11e9-8380-038387d7047e.png)

We also don't have the names of the personalization color for the uplift theme.
![image](https://user-images.githubusercontent.com/4737815/55084058-8d61c700-5072-11e9-850b-fc9fd2ef1c3e.png)

**Comment by tmcconechy** [comment]
Do this with https://github.com/infor-design/enterprise/issues/1847

**Comment by nickwynja** [comment]
This is complete now, right?
