### ISSUE TITLE
ContextualActionPanel wont open again after closing the panel

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1870]
**Describe the bug**
Contextual Action Panel wont open again after closing the panel

**To Reproduce**
1. Go to http://4170-rc1-enterprise.demo.design.infor.com/components/contextualactionpanel/example-centered.html
2. Open the Panel
3. Click 'x' to close the panel

*Notice that the Panel did not open again'

**Expected behavior**
Should open again when clicked even after closing it.

**Version**
v4.17.0

**Platform**
- All Browser, OS and devices

**Additional context**
No additional context

**Comment by tmcconechy** [comment]
Maybe as part of #1136 just remove this example.

**Comment by tmcconechy** [comment]
This issue was fixed along the way as i can no longer reproduce it on http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/example-centered.html
