### ISSUE TITLE
Composite form: Not showing the hide summary button on iOS devices

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1871]
**Describe the bug**
Composite form not responsive in iOS devices when in landscape mode. Dot show the 'Hide Summary' button and cannot be scrolled down. 

**To Reproduce**
1.  Using iOS device in Landscape mode Open a Browser
2. Go to http://4170-rc1-enterprise.demo.design.infor.com/components/compositeform/example-index.html

**Expected behavior**
'Hide Summary' button should be visible or the screen should at least be scrolled down to see and click on the button. 

**Version**
v4.17.0

**Screenshots**
<img width="787" alt="Screen Shot 2019-03-28 at 7 00 12 PM" src="https://user-images.githubusercontent.com/45757016/55152879-394b0580-518c-11e9-826e-e77ccbfac603.png">

**Platform**
 - iOS mobile devices

**Additional context**

**Comment by tmcconechy** [comment]
We will deprecate this pattern so closing this issue see https://github.com/infor-design/enterprise/issues/1944
