### ISSUE TITLE
Circle pager: Pager buttons not showing on IOS

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1872]
**Describe the bug**
Circle pager not responsive in iOS devices

**To Reproduce**
1. Using iOS device in portrait angle
2. Open http://4170-rc1-enterprise.demo.design.infor.com/components/circlepager/example-index.html

Notice that the pager didn't appear and the 'Prev' & 'Next' button is not working

**Expected behavior**
Pager should appear and the Prev and Next button should work. 
**Version**
v4.17.0

**Screenshots**
<img width="399" alt="Screen Shot 2019-03-28 at 7 33 50 PM" src="https://user-images.githubusercontent.com/45757016/55154934-022b2300-5191-11e9-9939-a4da84725821.png">

**Platform**
- iOS Mobile devices 

Tested in iPhone X max - Safari

**Additional context**
No additional context.

**Comment by EdwardCoyle** [comment]
Hi @janahintal, can you recheck this one, and provide some more details on iOS/Safari versions?  I tested in a few os/browser combinations on iOS devices in the simulator, and wasn't able to reproduce.

![Mar-28-2019-9_25-AM](https://user-images.githubusercontent.com/3249601/55161401-d5005580-513b-11e9-88ef-36b3335c5826.gif)

**Comment by tmcconechy** [comment]
I did see it on browserstack IOS X - Iphone

**Comment by janahintal** [comment]
Hi, @EdwardCoyle yes I still able to replicate it in version 4.18 the circle pager didn't appear even in Android devices as well but I was able yo scroll down and see the remaining item.

**Comment by ericangeles** [comment]
Hi @tmcconechy and @janahintal , I believe i fixed this issue before. https://github.com/infor-design/enterprise/issues/2589 

Testing it, and I wasn't able to reproduce the issue.  I guess we can now close this ticket.

**Comment by tmcconechy** [comment]
I also can no longer reproduce must have been fixed along the way.

**Comment by janahintal** [comment]
QA Passed. Will Move to Done. 
Verified in http://master-enterprise.demo.design.infor.com/components/circlepager/example-index.html across all platform
