### ISSUE TITLE
Datagrid Filter: lookup filtertype has incorrect filter conditions

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#1873]
**Describe the bug**
Currently by default, a filterType of 'lookup' only has 'Equals, Does Not Equal, Is Empty, Is Not Empty'. If you specify a filterConditions of ['equals', 'contains'], only Equals will be in the drop down.
Since a lookup could be for an integer field or an alpha field, would have the default for lookup fields to have the same as text and numeric (Contains, Does Not Contain, Equals, Does Not Equal, Is Empty, Is Not Empty, Ends With, Does Not End With, Starts With Does Not Start With, Less Than, Less Than Or Equals, Greater Than and Greater Than Or Equals). Then the filterConditions could be used by the implementer to narrow down the list depending if the lookup is numeric or alpha.

**To Reproduce**
1. Copy
[test-filter-lookup-click-function.zip](https://github.com/infor-design/enterprise/files/3018447/test-filter-lookup-click-function.zip) into /components/datagrid/ in your codebase.
2. Go to './components/datagrid/test-filter-lookup-click-function.html'
2. Click on the filter conditions dropdown for Product Id
4. Only "Equals" is seen in the dropdown.

**Expected behavior**
Equals and Contains should be seen in the dropdown.

**Version**

- ids-enterprise: v4.17.0-rc.0

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/55166544-52789580-513d-11e9-921f-cb281f48c282.png)

**Platform**
All

**Additional context**
I believe an if for filterType === lookup needs to be added around here: https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L1697

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-filter-lookup-options.html
http://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-lookup-options.html
Passed QA testing on all browsers. Will test again once beta is deployed.
