### ISSUE TITLE
Toast: Add configuration to move the toast and have it stay in that postion

### ISSUE THREAD

**Issue by lipetzan** [infor-design/enterprise#1876]
**Is your feature request related to a problem? Please describe.**

Recruiter's at Riverside using Landmark/GHR's ATS software are complaining that the confirmation message is "in the way".   This is due to placement and timing I'm guessing.

Placement: confirmation is typically placed right over the toolbar (top right).  Makes sense, it's were most eyes go as well.  The problem is that it does block what actions I might want to take next.  This happens to power-users who hammer on data and records all day.

Timing: the message isn't snappy one would say.  I know there is an "x" to dismiss it, but that means extra clicks and things to deal with.  The feedback is that doing the "x" is just in the way.

Potential ideas might be to add personalization settings on placement and timing.  E.g. I'm a fast reader, I know the system, i'd cut the message time by 50%.   Or, I'd like confirmations on the bottom left.  Like the browser did/does.

**Describe the solution you'd like**

- [ ] Add the ability to drag the toast to any place on the page you want
- [ ] Once it is dragged save the position in local storage
- [ ] Next toast for the user will go in the same place -> or under the last one if stacked

**Comment by tmcconechy** [comment]
@lipetzan we can already put it in any of the four positions http://master-enterprise.demo.design.infor.com/components/toast/test-positions.html can you do that in LPL? Or how would we let the user decide? Maybe have to drag it to another corner and it stays there?

**Comment by lipetzan** [comment]
We have a Settings menu for Theme and Personalization we could use?  Did you ever intend for the optionality to be this end-user driven?

**Comment by lipetzan** [comment]
I don't hate drag and sticky either.

**Comment by tmcconechy** [comment]
No we did not think of the position being user driven. If it has to be maybe you can move and it stays but we dont have a settings dialog of the time or anything

**Comment by jamie-norman** [comment]
I like the flexibility of allowing the user to move the dialog. I think it's enough to just implicitly remember the position and maintain until user moves it again.

**Comment by tmcconechy** [comment]
Ok, Also if you press down on the mouse on the toast then it will delay the time it takes before it shuts and if you want it gone you click the x. So maybe the drag/save position is enough?

**Comment by jamie-norman** [comment]
I think that could be enough. I know we've also talked about shortening its display time. Not sure if that is necessary.

**Comment by tmcconechy** [comment]
Ok, Display time is a setting. If you want to expose it on a user settings and then pass it to the component that would work too.

**Comment by jamie-norman** [comment]
configure ALL THE THINGS

**Comment by clepore** [comment]
So we can:
- Add the ability to drag/drop the toast
- Create API endpoints:
    - set the toast coordinates
    - get the final coordinates after drag/drop

We can't actually store/persist from a library perspective, but we can provide the api endpoints to set and access from the consuming app.

**Comment by lipetzan** [comment]
@clepore can you give an ETA on this?

**Comment by clepore** [comment]
@lipetzan I believe it was reprioritized out of May in favor of other things (like datagrid). We can add it to the June sprint for `v4.20`.

**Comment by adinenno** [comment]
Do we have an ETA on when Riverside can expect this? Has the Hook & Loop team finished their part and passed off to Landmark? What is the Landmark ETA?

**Comment by tmcconechy** [comment]
We just started on it and moved it into progress. Should be maybe in by end of the week in a nightly build for testing. Final version is at end of this month. Not sure what the landmark ETA would be based on that, you would have to check over there. But they are probably waiting on this as a first step.

**Comment by janahintal** [comment]
HI @tmcconechy . Having issues with toast in Responsive view after changing the position of it. Thanks.
![image](https://user-images.githubusercontent.com/45757016/61513316-4cc9f700-aa2f-11e9-9da4-55ff58e598a6.png)

**Comment by tmcconechy** [comment]
@deep7102 I think @janahintal has a point. If you do this:

- open the browser wider(ish)
- open the toast
- drag it to the far right
- resize the browser to narrow
- now any clicks you cannot see the toast

You think its possible to reset the position so the toast is in view when it loads while off the page? If not we can punt this as it is working as expected as you did drag it there.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/toast/example-draggable.html 
Passed on all Mac and Windows browsers, as well as when you resize the browser to narrow. 

But is this feature also applicable to Mobile? Because the toast is not draggable on Android Chrome. But is working fine in iOS Safari, Chrome and Android Firefox.

**Comment by tmcconechy** [comment]
This behavior is not ideal for use on a mobile device. We can revise it later if Android Chrome is needed in the future by some team.
