### ISSUE TITLE
Datagrid: Columns Title Misaligned on Short Row Size

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1880]
**Describe the bug**
The header test and sort icons are misaligned, sometimes hitting the filters. This issue is important enough to make a 4.17.1 patch (and a 5.2.1 ng with it).

**To Reproduce**
1. Go to https://4162-enterprise.demo.design.infor.com/components/datagrid/example-filter
3. Select short row height
4. Notice the text is slightly cut off. This looks extremely bad in Landmark app

**Expected behavior**
Text, filters and sort icons should all be nicely aligned on all 3 row heights.

**Version**
- ids-enterprise: [4.16.0 or 4.17]

**Platform**
 - Any

**Additional context**
- Make an example with left, right, center aligns. With filter or no filter and various column types. Also make some with the headerAlign setting. 
- Make 3 visual regression tests on the three heights after fixing
- This probably occurred when we fixed this example adding an alignment option https://4162-enterprise.demo.design.infor.com/components/datagrid/test-align-header-text.html

**Comment by CindyMercadoReyes** [comment]
Hi @tmcconechy @clepore , This issue is now resolved. However, a new issue was introuduce. Please see GitHub ticket: https://github.com/infor-design/enterprise/issues/1890  Thanks, Cindy
