### ISSUE TITLE
Notification: Add widget version

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1881]
**Is your feature request related to a problem? Please describe.**

Design has provided a version of the notification thats shorter for on a widget.

**Describe the solution you'd like**
- if the `parent` setting is a `widget` or `card` then the new size of the notification should be adopted
- make an example showing it working on a card/widget

**Describe alternatives you've considered**
Leave it on the page header only and dont change size

**Additional context**
Designs:
[20190329-IONErrorBannersHandoffDoc-JV.pdf.zip](https://github.com/infor-design/enterprise/files/3022682/20190329-IONErrorBannersHandoffDoc-JV.pdf.zip)

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/notification/example-widget.html
Passed QA testing on all browsers, will retest on beta build once deployed.

**Comment by CindyMercadoReyes** [comment]
Including BBD for this enhancement. 
[story_github#1881.docx](https://github.com/infor-design/enterprise/files/3334974/story_github.1881.docx)
