### ISSUE TITLE
Mac Safari: Item in Dropdown list cannot be selected by one click after special condition

### ISSUE THREAD

**Issue by tomjohn9** [infor-design/enterprise#1882]
**Describe the bug**
Item in Dropdown list cannot be selected by one click after unchecking "Select All" in Safari browser. User has to click twice on item to mark item as selected

**To Reproduce**
1. Go to http://latest-enterprise.demo.design.infor.com/components/multiselect/test-select-all.html (or have soho dropdown with attribute "multiselect" and [showSelectAll]=true with couple of items)
2. Click on dropdown and check "Select All" option (so all items will be marked as selected)
3. Click somewhere else to make dropdown close its list
4. Click again on dropdown and uncheck "Select All" option (so all items will be marked as NOT selected)
5. Click on any item in dropdown list

**Expected behavior**
Item is selected when user click on item in dropdown list

**Current behavior**
Item is NOT selected when user click on item in dropdown list. User has to click again on item to mark is as selected

**Version**
- ids-enterprise: 4.17.0

**Platform**
 - OS Version: MacOs
 - Browser: safari

**Comment by janahintal** [comment]
QA Passed. Will Move to Done. Thanks!
Tested in: http://localhost:4000/components/multiselect/test-select-all.html & http://master-enterprise.demo.design.infor.com/components/multiselect/test-select-all.html
