### ISSUE TITLE
Marketo Tokens break example pages

### ISSUE THREAD

**Issue by swetteinfor** [infor-design/enterprise#1884]
**Describe the bug**
Corporate communcations added Marketo query parameters to our links in the corporate wide H&L newsletter and they are breaking.

**To Reproduce**
1. Go to these two links:
    - https://master-enterprise.demo.design.infor.com/components/form/example-forms.html?theme=uplift&mkt_tok=eyJpIjoiWldNMk4yVmhZVFkwTTJaaiIsInQiOiI0d3ZVandQV2Q0cmx0Q0xXRGwrQmo4K3hGczMwM1k2NUhLOVl4bTlsUkVmcFRqNjdVeHhnNkc5dHlpcDBIS1BleWNaRmg0alpHcmJvVU9tQW9IcTdPK3lIUENtc0ZcL2NZdng1RWRCQ2xaNjVqYkhhczhNUTljeHhEeXhXMUo5TG0ifQ%3D%3D
    - https://master-enterprise.demo.design.infor.com/components/form-compact/example-list-detail.html?theme=uplift&mkt_tok=eyJpIjoiWkdVMU1EaGxNR1kyWXpKaCIsInQiOiJJNENkMUxjcVZmSmFHTlNBYzhOYUdqSzlvUFBZVDRBK01YVzNzQ0JKYk5JT0dsbHp0R0xGeDZyNE1GYlZoamlJdENNVVA4c0VFWVBNcmRtbTZncnptS0dnenRvNUhqMWxldlJBNlVmU08yV2ZNTm00QzZnZFwvNk5GZjdvbkcxWjgifQ%3D%3D

**Expected behavior**
These links should resolve no matter what the query params are. Here are the base links:
- https://master-enterprise.demo.design.infor.com/components/form/example-forms.html
- https://master-enterprise.demo.design.infor.com/components/form-compact/example-list-detail.html

**Version**
- ids-enterprise: all

**Screenshots**
n/a

**Platform**
- all

**Additional context**
@nickwynja I noticed you sent out links to `master` and this makes me wary.

**Comment by tmcconechy** [comment]
Running the link local http://localhost:4000/components/form/example-forms.html?theme=uplift&mkt_tok=eyJpIjoiWldNMk4yVmhZVFkwTTJaaiIsInQiOiI0d3ZVandQV2Q0cmx0Q0xXRGwrQmo4K3hGczMwM1k2NUhLOVl4bTlsUkVmcFRqNjdVeHhnNkc5dHlpcDBIS1BleWNaRmg0alpHcmJvVU9tQW9IcTdPK3lIUENtc0ZcL2NZdng1RWRCQ2xaNjVqYkhhczhNUTljeHhEeXhXMUo5TG0ifQ%3D%3D

No errors, seems like the links are too long so it hangs the demo app? If we can push a fix to master and let it deploy

**Comment by clepore** [comment]
What actually breaks it is the `%3d%3d` at the end, not the query params themselves.
