### ISSUE TITLE
Demo App: Hierarchy example images aren't being served on IDS iframes and latest demo

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1888]
**Describe the bug**
We are seeing broken images in the EP demo app only when on `latest`.

**To Reproduce**

*IDS Website*
1. Go to these links and see the images not loading:
    - https://design.infor.com/code/ids-enterprise/latest/hierarchy
    - https://design.infor.com/code/ids-enterprise/4.17.0/hierarchy
    - https://design.infor.com/code/ids-enterprise/4.16.2/hierarchy

Demo App:
1. Go to [latest...hierarchy/example-index](https://design.infor.com/code/ids-enterprise/latest/demo/components/hierarchy/example-index)
    - See the images are not being served
2. But go to `master` and `4.17.0` and see they are served there:
    - [master...hierarchy/example-index.html](https://master-enterprise.demo.design.infor.com/components/hierarchy/example-index.html)
    - [4170...hierarchy/example-index.html](https://4170-enterprise.demo.design.infor.com/components/hierarchy/example-index.html)

**Expected behavior**
The images should be served on all the things and places.

**Screenshots**
<img width="745" alt="Screen Shot 2019-03-28 at 5 43 19 PM" src="https://user-images.githubusercontent.com/742319/55194790-018a9080-5181-11e9-99d3-5c17120e6063.png">

**Platform**
 - All

**Additional context**
n/a

**Comment by clepore** [comment]
In the demo app, images need to be:
```<img src = "{{basepath}}images/signin-logo.png" alt="Name"/>```
with the basepath prefixed.

In all of the hierarchy examples, the image `src` is getting written out inside of a template, so global `basepath` doesn’t exist...
```{{={{{ }}}=}}
<script type="text/html" id="hierarchyChartTemplate">
  <div class="leaf {{colorClass}}" id="{{id}}">

    {{#Picture}}
      <img src="{{basepath}}{{Picture}}" class="image" alt="Image of {{Name}} '{{basepath}}'"/>
    {{/Picture}}
    {{^Picture}}
...```

Essentially the demo app examples are templates, and this is a template literal in a template.

@EdwardCoyle 's idea was to use express middleware to formulate the data and add the correct `basepath`. This is probably the cleanest solution for now.

**Comment by EdwardCoyle** [comment]
To follow up, I'm thinking we turn [this JSON-based data](https://github.com/infor-design/enterprise/blob/master/app/data/orgstructure.json) into a `.js` file that looks something like [this data route](https://github.com/infor-design/enterprise/blob/master/app/data/states.js), and probably use Express's `originalUrl()` or something similar to append the correct basepath to the image data.

**Comment by janahintal** [comment]
QA Passed. Image loading properly in all OS and Browsers. Thanks
Tested in https://1888-demoapp-image-paths-enterprise.demo.design.infor.com/components/hierarchy/example-index & http://master-enterprise.demo.design.infor.com/components/hierarchy/example-index
