### ISSUE TITLE
Icons Page is not loading the embedded sample

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1889]
**Describe the bug**
Happened across this problem:

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/icons
2. Have a look at the frame with the example and you will see nothing, just blank page.

**Expected behavior**
You see https://design.infor.com/code/ids-enterprise/latest/demo/components/icons/example-index?layout=embedded

**Platform**
Any

**Additional context**
Looks like the embedded layout option doesnt work with the icons (due to the switching?)

https://design.infor.com/code/ids-enterprise/latest/demo/components/icons/example-index?layout=embedded

**Comment by clepore** [comment]
It seems that the query param is not allowing the url to hit the custom icons route in the routing.
