### ISSUE TITLE
Filterable Datagrid: Can't resize the "Status" column more than once

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1890]
**Describe the bug**
Filterable Datagrid: Can't resize the "Status" column more than once.

**To Reproduce**
1. Go to:
    - http://4171-rc0-enterprise.demo.design.infor.com//components/datagrid/example-filter
    - http://4170-enterprise.demo.design.infor.com//components/datagrid/example-filter
    - http://4162-enterprise.demo.design.infor.com//components/datagrid/example-filter
2. Click on Status column and resize it to look smaller
3. Again go to the Status column and try to resize it again.
4. You are unable to resize the "Status" more than once. You have to refresh the page in order to resize it 

**Expected behavior**
The user should be able to resize the "Status" column more than once.  

**Version**

- ids-enterprise: `4.16.2`, `4.17.0`

**Screenshots**
![Filterable Datagrid Status Colunm](https://user-images.githubusercontent.com/39101346/55350410-09507a80-548a-11e9-913a-d2f48e705d43.png)
**Platform**
 - All Browser 

**Additional context**
None

**Comment by clepore** [comment]
It seems to be an issue with sizing/adjusting the 2nd to the last column, and not specifically to the `status` column itself.

**Comment by tmcconechy** [comment]
This is the original behavior and did not break on any changes this release. When you size the last column it will break out from stretching mode to manual size mode (every column has a fixed pixel size and none stretch). I think there is already any issue for this. But it was a choice I made at the time. We could in the future change this so that when sizing the last column it stays stretched and adjusts adjacent columns or the other side of the stretch column. Don’t think this should delay 4.17

**Comment by tmcconechy** [comment]
Actually scratch part of my comment. I’m talking about the behavior of resizing it so it doesn’t stretch anymore. But you should be able to resize it back and resize more than once. So the more than one part is a bug. We should see if this regresses in 4.16 or 4.15 and possibly something @deep7102 can help with. Maybe the resize grip is moved out of position. Maybe we add for next version?

**Comment by clepore** [comment]
So it actually is able to be resized more than once. It looks like what happens is...
1. The 2nd to last column column is `130px` wide
1. You mousedown on the resize element
1. On the slightest drag move, the column snaps to `83px` (despite where the mouse is or moved to)
1. From there you can resize the column smaller than `83px`, but not larger than `83px`
    - Also there is now a gap between the datagrid and it's container that is the difference between the original width of `130px` minus the "snapped width" of `83px`

**Comment by brianjuan** [comment]
Issue still exists on http://localhost:4000/components/datagrid/example-filter and http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter

**Comment by clepore** [comment]
@brianjuan This is correct as we haven't released and merged [4.17.1] back into master. That will be resolved in the next day or so 👍
