### ISSUE TITLE
RTL: Datagrid Column fixed header misaligned on load

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#1892]
Hi,

Starting from 4.16, when using Datagrid with fixed headers in RTL, the column header is offset by a few pixels. After scrolling or doing some "action" on the datagrid, the header is aligned (until data reload).
On version 4.15.0 it was OK.

Please see:
[https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-fixed-header?locale=he-IL](url)

The same page but with version 4.15.0:
[https://design.infor.com/code/ids-enterprise/4.15.0/demo/components/datagrid/example-fixed-header?locale=he-IL](url)

I saw the same behavior on Chrome, IE11 and Firefox.

Thanks,
Jonathan

**Comment by clepore** [comment]
We appreciate your submission and we'll look into it! For next time though, we request that you follow the one of the templates (`bug request` or `feature request`) found after clicking the "New Issue" button on the repo's Issues page.

**Comment by clepore** [comment]
One of the actions I noticed is that if you change the result size using the the dropdown in the bottom right corner of that page, in `4.17.0 (latest)` a weird gutter appears to the left, but the columns never mis-aligned. I did not notice the gutter on `4.16.2`.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. However, tickets https://github.com/infor-design/enterprise/issues/1942  and https://github.com/infor-design/enterprise/issues/1957 are still open.
