### ISSUE TITLE
Notifications: Demo not properly loading on docs site

### ISSUE THREAD

**Issue by swetteinfor** [infor-design/enterprise#1893]
**Describe the bug**
Notification Banner demo not properly loading on the docs site.

**To Reproduce**
1. Visit <https://design.infor.com/code/ids-enterprise/latest/notification>
1. Notice an empty iframe where the example should load.

**Expected behavior**
The embed example should load as it does when viewing the example directly: https://design.infor.com/code/ids-enterprise/latest/demo/components/notification/example-index

**Version**
- ids-enterprise: 4.15.0, 4.16.2, 4.17.0

**Platform**
 - Browser Name: All

**Comment by clepore** [comment]
The issues deals with the `?layout=embedded` causing a console error:

<img width="712" alt="Screen Shot 2019-04-02 at 11 30 07 AM" src="https://user-images.githubusercontent.com/742319/55415857-cd75ed80-553b-11e9-8bbb-0cf11fa882c2.png">

<https://design.infor.com/code/ids-enterprise/4.15.0/demo/components/notification/example-index?layout=embedded>

**Comment by EdwardCoyle** [comment]
Not sure why this didn't close, but we fixed this in #1896

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
