### ISSUE TITLE
Datagrid: Server-side paging issue when loading gird for the first time

### ISSUE THREAD

**Issue by sumit4singh** [infor-design/enterprise#1899]
**Describe the bug**
when we are trying to load dataGrid with server side pagination for the first time we are just getting pagination as 1 of 1 even though we have more than one page.
when we change the page size from size selector it shows up the exact .no of pages available.

```
source: (req, response) =>{
      req.pagesize = 10;
      req.activePage = 1;
      req.total = 50;
      response(this.swaggercollectionJsonString.swaggerCollection.swagger, req);
}
```

**Expected behavior**
for the first time loading also it should show exact .no of pages.

**Version**
"ids-enterprise-ng": "5.0.0"

**Screenshots**
![image](https://user-images.githubusercontent.com/36255774/55483385-16b16480-5644-11e9-97e2-4aa65bb6459b.png)

soho application for first time loading
![image](https://user-images.githubusercontent.com/36255774/55483639-9c351480-5644-11e9-912b-4ce57fdcbfd0.png)

when changing records per page
![image](https://user-images.githubusercontent.com/36255774/55483675-b5d65c00-5644-11e9-95da-b37a491d6d8c.png)

**Platform**
 - OS Version: [ Windows 10 ]
 - Browser Name [chrome, safari, stock browser]

**Comment by tmcconechy** [comment]
@sumit4singh im not sure we can reproduce this or not. Is this an angular only issue or an Enterprise core issue. It would help speed up this issue if you could drop in an example we can run to reproduce as you dont seem to show how you set up the page sizes initially.

**Comment by sumit4singh** [comment]
source: (req, response) =>{
      req.pagesize = this.swaggercollectionJsonString.paging.pageSize;
      response(this.swaggercollectionJsonString.swaggerCollection.swagger, req);
      }
its not shown in website. but if we run ng-enterprise-master project locally then its shown there.

**Comment by sumit4singh** [comment]
thanks Tim for looking into it. its now resolved when i update my SOHO to latest version

**Comment by tmcconechy** [comment]
Excellent thanks for following up with that 👍
