### ISSUE TITLE
Datagrid - DateTime format type

### ISSUE THREAD

**Issue by brafajloski** [infor-design/enterprise#1903]
**Is your feature request related to a problem? Please describe.**
`Infor Data Lake` requires datagrids where a date column contains a datetime format type.
Currently datetime in a grid is not sortable and filterable as the other data types are, nor there is a proper UI control to select the time for a date.

**Describe the solution you'd like**

- DateTime to be supported as a type for column.
- Filter for datetime.
- DateTime picker for the column containing DataTime values
- Sortable by the DateTime.

**Describe alternatives you've considered**

- Store the value as datetime.
- Allow filtering/sorting only on the date. 

**Additional context**
N/A

**Comment by tmcconechy** [comment]
We do already have this feature. Check out the example:
http://latest-enterprise.demo.design.infor.com/components/datagrid/test-editable-datetime.html

Source: https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-editable-datetime.html

This is done using options on the Date filter type https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-editable-datetime.html#L46

So you can pass in anything the datepicker supports in terms of options and the picker and field will use that. `filterType: 'date', editorOptions: {showTime: true, dateFormat: Locale.calendar().dateFormat.datetime}`
