### ISSUE TITLE
Datagrid - Row numbering

### ISSUE THREAD

**Issue by brafajloski** [infor-design/enterprise#1904]
**Is your feature request related to a problem? Please describe.**
`Infor Data Lake` will allow executing queries over the data stored and will show the results in a data grid. The results datagrid is required to have row numbering.

**Describe the solution you'd like**
- Sequential row number for each displayed row.
- Numbering is fixed, non-sortable
- Filtering -I am not sure if it makes complete sense. I can think of a use case 'filter and show rows numbered 25-50,'

**Describe alternatives you've considered**
We tried adding a row with numbering. However the numbering gets reordered when you apply sorting on one of the other columns.

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Is this still needed? i think it's a good idea .. But just checking its still needed after the late reply.

**Comment by brafajloski** [comment]
Yes. It's not a huge gap in our solution, but if you build it we'll use it 👍

**Comment by tmcconechy** [comment]
@brafajloski just wondering a bit about the "fixed - non sortable" requirement. Is this what you mean https://drive.google.com/file/d/1vb3REWR8cewrSWMUSgeGfmyWub3gnrFw/view

**Comment by brafajloski** [comment]
@tmcconechy ,exactly what I had in mind, thanks. It is just row numbering column. 
In our app (Compass Query Editor) we do not allow sorting/filtering the data grid, so I cannot directly relate my answer to a specific use case. Maybe others would have a different expectations, but i agree with your proposal. 

Sort: Order of row numbers should remain 1-n after sorting a column.
Filter: Maybe the row number should disappear when filtering a column. (e.g. Excel).

**Comment by jbrcna** [comment]
**QA Failed**
v4.32.0-dev
will retest once beta is deployed
https://master-enterprise.demo.design.infor.com/components/datagrid/example-row-numbers
when you run a filter then sort that filtered results, the read-only column showing the row number is also sorted
![image](https://user-images.githubusercontent.com/56722184/90126020-8e91b200-dd95-11ea-9691-2803e52787d7.png)

_Assumption_
If I understand it correctly, ` row number` should stay `the same`
![Large GIF (1230x668)](https://user-images.githubusercontent.com/56722184/90125360-82592500-dd94-11ea-819e-0dba028116c7.gif)

**Comment by brafajloski** [comment]
Yes I think so too, the row numbers should not change when sorting with applied filters. Thanks for the example, looks awesome.

**Comment by jbrcna** [comment]
The issue is now resolved. Thank you 😊 
moving this ticket to Done
![Large GIF (1230x668)](https://user-images.githubusercontent.com/56722184/90248141-ae46da00-de6a-11ea-9a08-4a117477c047.gif)

**Comment by CindyMercadoReyes** [comment]
BDD included
[story_github#1904.pdf](https://github.com/infor-design/enterprise/files/5074834/story_github.1904.pdf)
