### ISSUE TITLE
Datagrid: Add events to allow multiselect only when modifier key is pressed

### ISSUE THREAD

**Issue by hernebrink** [infor-design/enterprise#1906]
**Is your feature request related to a problem? Please describe.**
In M3, we need to be able to do a multiple select, but only when the user is pressing the Ctrl/Command (mac) key at the same time. This is a behavior that thousands of M3 users are accustomed to. The M3 H5 client is currently being rewritten using ids-enterprise-ng components and this feature enhancement for the datagrid is very much needed. 

**Describe the solution you'd like**
Option 1:
The optimal solution would be to have a property e.g. modifierKey (available for `multiple` selection datagrids) which would take a supported (by you guys) value e.g. ctrl or alt. Lets say the value ctrl is given, the datagrid control would check If ctrlKey or metaKey (mac) is available on the triggered event and its current value. If the value of the mappings for the modifyer key is true, then go ahead and add the row to the list of selected rows, otherwise unselect all rows and add only the current row to the list of selected rows. If this modifyerKey property is not present on the datagrid options object, continue with default behavior (as today). 

Option 2:
A different solution could perhaps be to add `beforeRowActivated` (or similar event before a row is actually activated or selected) for `multiple` selection datagrids too (currently only available for mixed selection datagrids?). You would have to pass the original event (not only the `row` and `item` which is the case for the `mixed` selection datagrids today), so that the developers can check if `event.ctrlKey` or `event.metaKey` exists and if anyone is true. 

**Describe alternatives you've considered**
An alternative solution I've tried is to create an angular directive to be added to the same div as the `soho-datagrid` one which has a HostListener for click event. I can then inject the datagrid in the directive and unselect all rows if the modifyer key of my choice is not true. This works to some extent, but not when the rows are selected using keys (tabbing and selecting with enter for example). Also some events are not triggerd by users, so it is not a good solution for that reason too.

**Comment by tmcconechy** [comment]
So selecting rows is "blocked" unless they hold ctrl key down? Im not certain i follow how that works to the end user? Can you explain that a bit more?

What we do support is:

http://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
- click one row
- hold shift down
- select another row a few down

**Comment by jonathanamiran** [comment]
This feature also been asked by our M3 customers:
We need to select a row by clicking on the row while Ctrl key being pressed - but with clickToSelect setting set to **false**. We don't want to select the line by clicking it, only when Ctrl is clicked.

If we change selectable setting to 'mixed' instead of 'multiselect' then **rowactivated** event  is fired when clicking on a row, however, although the event has e.ctrlKey property, its value is undefined (I'm not sure if it's a Bug or not). So currently I couldn't find a solution to Ctrl+Click to select.

Thanks

**Comment by tmcconechy** [comment]
Ok so it’s really only possible to select if you click when Carl is down. And anywhere on the row or only the checkbox? And is it multi or single select? I’m thinking

- add selectable : manual option that only allows the select and deselect apis to be called
- use the click event of the grid
- check for ctrl key in the event and call toggleSelected or selectRow ect

You could try with selectable: false or mixed ect now on the.

Or your ideas seem ok as well. Such as a beforeselect or afterselect that you can veto and ensure the key is in the event data to check

**Comment by jonathanamiran** [comment]
I'm talking on catching the Ctrl+Click event while clicking anywhere on a row.

I just found a little workaround, it seems that **window.event.ctrlKey** has the correct value when firing the  'rowactivated' event (in selectable:'mixed'). And I have a little function that selects/deselects the row depends on the current selected value.

**Comment by tmcconechy** [comment]
Ok, The mixed selection is a bit different so your only blocking the activation not selection. (Not sure if your aware of that). I think the easiest solution is maybe add a vetoable beforerowselection that has the event data, and that you can return false to not select. Then we just using multi-select mode and you can return false.

**Comment by hernebrink** [comment]
> Ok so it’s really only possible to select if you click when Carl is down. And anywhere on the row or only the checkbox? And is it multi or single select?
> 

1. The checkboxes will always be hidden (in the case of M3).
2. One should be able to select a row by clicking on it
3. One should be able to select a different row when clicking on that row
4. One should be able to add multiselect by pressing Ctrl and clicking a different row
5. One should now be able to add multiple additional rows by pressing Ctrl and Shift and clicking for example tree rows below the last row you clicked,
6. One should loose all selected rows but the rows from the last clicked row to the current clicked row if one only press Shift + Click now
7. All rows should be unselected if you were to select a different row now without pressing Ctrl. Only the current clicked row now should be selected. 

I have made a short recording of this from the current M3 H5 version we have (forgot to include/show point 6 from my list though).
![Multiselectbehavior](https://user-images.githubusercontent.com/4176143/55890468-06086d80-5bb3-11e9-9471-a4fec7a63472.gif)

**Comment by tmcconechy** [comment]
The way you do it is completely different than the keyboard shortcuts we agreed on to do this.
I think perhaps what i can do is add:

- ctrlclick event -> in this event you get that a row was clicked along with the currently pressed keys, then you can call what you want.
- a beforeRowSelect -> that you can simply veto.

Unless you already have a solution for this?

**Comment by hernebrink** [comment]
Hi Tim, 

This is not "my" way but M3's, since before the product hit the cloud servers. I just wanted to make that clear so you don't think this is my preferred way or idea. Also am I not aware of what has been agreed on when it comes to shortcuts for the controls, I just know what the M3 users are used to what they would expect if they were to transition from the old "fat" JAVA client to the CE one. 

Exposing an onBeforeRowSelect (with the event object passed - so that one can manually stopPropagation, check if meta keys were pressed etc) could potentially suffice, would it wouldn't hurt if you can ad the ctrlclick event too.

Thank you!

**Comment by tmcconechy** [comment]
Sure understood. I really just meant I considered if the m3 way would work with our way (shift click for multiple or each click toggles). And i don’t think it can so we’ll need some events so you can implement something custom to achieve it.

**Comment by CindyMercadoReyes** [comment]
Hi @tmcconechy When testing this enhancement on URL: http://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html  when I follow these steps below. It select all the rows on MAC Chrome. 
- click one row
- hold shift down
- select another row a few down

Steps to reproduce the issue:
- Click on the row for product ID 2142201
- Hold the shift down key
- Select the row for product IS 2642206
- All the rows get selected.

**Comment by tmcconechy** [comment]
@CindyMercadoReyes Thats not a bug if you hold shift you can select multiple rows it works like this.
- click one row like 2342203
- hold shift and click another row like 2642205

But m3 wants to do it a different way but this is our default way or multiselect so is totally correct

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
