### ISSUE TITLE
Locale: en-US locale has incorrect groupsize

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#1907]
**Describe the bug**
The locale for en-US has an incorrect groupsize of [3, 0]. It should be [3, 3]. I believe this happened due to a typo between issue #441 where it referenced es-US and the pr #1779 where it referenced en-US.

**To Reproduce**
1. Using the browser console
    ```
    var num = "123456789012.123456"
    Soho.Locale.formatNumber(num, { style: "decimal", round: false, minimumFractionDigits: 6, 
    maximumFractionDigits: 6})
    returns "123456789,012.123456"
    ```

**Expected behavior**
- `123,456,789,012.123456`

**Version**

- ids-enterprise: v4.17.0-rc.0+

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/55555370-bdc8e700-56aa-11e9-8eaf-7b14a86602ae.png)

**Comment by tmcconechy** [comment]
I rechecked this and the group size and on the original issue is both [3, 0] so i think this was correct an unneeded. Are you totally sure this is wrong @fitzorama 

See Globalize original source of this info
https://github.com/globalizejs/globalize/blob/v0.1.1/lib/cultures/globalize.cultures.js#L2515
and as noted on the original issue
https://github.com/infor-design/enterprise/issues/441#issue-342055154
