### ISSUE TITLE
SohoTreeComponent: Tree is not loaded when children property of any one of the node is null

### ISSUE THREAD

**Issue by mdevale** [infor-design/enterprise#1908]
**Describe the bug**
Tree is not loaded when children property of any one of the node is null.

**To Reproduce**
1. Make change in `tree/example-ajax.html` as mentioned in additional context section
2. Run this project
3. Browse this page <http://localhost:4000/components/tree/example-ajax.html>
4. Tree is not loaded and you will see below error in console
    - `Uncaught TypeError: Cannot read property 'length' of null`

**Expected behavior**
It should load tree without any error.

**Version**
- ids-enterprise: 4.15.0+

**Screenshots**
![image](https://user-images.githubusercontent.com/40569892/55563270-3c596f00-5713-11e9-95f8-48346b24c166.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 73.0.3683.86 (Official Build) (64-bit)

**Additional context**
1. Change data source "sampleDataNoID" as below
```js
sampleDataNoID = [{
    "text": "Node One",
    "extra": "test 1"
  }, {
    "text": "Node Two",
    "open": false,
    "children": null,
    "extra": "test 2"
  }];
```
2. In above data source "Node Two" contains children property null that's causing issue.

**Comment by clepore** [comment]
Other things we should for this solution:
- [ ] Add code documentation for the Tree's `settings.dataset` object and what properties/types it should contain
- [ ] Review the code and add code documentation for any other missing settings for Tree

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by CindyMercadoReyes** [comment]
Including the BDD for this enhancement. 
[story_github#1908.docx](https://github.com/infor-design/enterprise/files/3334979/story_github.1908.docx)
