### ISSUE TITLE
Column Chart:  Include existing tooltip content in the tooltip callback setting

### ISSUE THREAD

**Issue by deep7102** [infor-design/enterprise#1909]
**Is your feature request related to a problem? Please describe.**
Need to add data to custom tooltip callback with column chart.

**Describe the solution you'd like**
Currently it can not really modify existing contents, but we can overwrite.
Need to modify the custom tooltip callback with current data
```
$('#column-bar-example').chart({
      type: 'column',
      dataset: dataset,
      tooltip: function (req, res) {}
    });
```

**Comment by CindyMercadoReyes** [comment]
Including the BDD for this enhancement. 
[story_github#1909.docx](https://github.com/infor-design/enterprise/files/3334987/story_github.1909.docx)
