### ISSUE TITLE
RTL: Datepicker wrong direction of Next/Prev buttons

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#1910]
**Describe the bug**
When using Datepicker in RTL, the Next/Prev buttons that change the months are directing to the wrong month when clicked. 
The layout on the screen is OK, but when a user wants to go to the next month, he clicks on the **left** button, and for the previous month he clicks on the **right** button. But he gets the exact opposite response. 

**To Reproduce**
1. Go to [Hebrew datepicker](https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-index?locale=he-IL)
2. Click on 'Calendar Icon'
3. The month now is April (אפריל)
3. Click on the Left button 
4. It goes to March (מרץ ) instead of May (מאי)

(I don't know if there is an English RTL locale for easier testing)

**Expected behavior**
In RTL - Left arrow =Next and Right arrow=Prev
In LTR - Left arrow =Prev and Right arrow=Next

**Version**

- ids-enterprise: ALL

**Screenshots**

**Platform**
 - OS Version: Windows 7
 - Browser Name Chrome
 - Browser Version 73.0.3683.86 (Official Build) (64-bit)

**Additional context**
Thanks!

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
