### ISSUE TITLE
Busy Indicator: Getting javascript error

### ISSUE THREAD

**Issue by deep7102** [infor-design/enterprise#1918]
**Describe the bug**
When Busy Indicator use on body it generating javascript error.

**To Reproduce**
1. Create example with Busy Indicator on body `<body class="busy" data-options="{ 'displayDelay': 300 }">`
2. Trigger start after load `$('body').trigger('start.busyindicator');`
3. See console it is generating javascript error

**Expected behavior**
There should not be any error.

**Comment by janahintal** [comment]
QA. Passed. Will Move to Done. 
Tested in: http://master-enterprise.demo.design.infor.com/components/busyindicator/test-busyindicator-on-body.html Thanks!
