### ISSUE TITLE
Datagrid: Allow dragging cell value outside

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#1920]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
Allow the ability of dragging cell value from Datagrid into an outside input element.
Preferably show the value of the dragged content near the mouse point while dragging.

**Describe alternatives you've considered**
Currently I can only select the cell text with the mouse and then drag it outside.

**Additional context**
This feature was available in M3 Workplace IBrix c:table element (including showing the value being dragged)

Thanks,
Jonathan

**Comment by tmcconechy** [comment]
We have a similar example of this .. See:
http://latest-enterprise.demo.design.infor.com/components/drag/test-grid-to-grid.html
Source: https://github.com/infor-design/enterprise/blob/master/app/views/components/drag/test-grid-to-grid.html

Basically this is using the included "drag" API see also :
http://latest-enterprise.demo.design.infor.com/components/drag/example-index.html -> see "Free" drag

I'm not certain this is a generic enough feature so might be something you just build out any further so suggest using the drag API. But wont close this yet.

**Comment by tmcconechy** [comment]
Did that example help you get what you needed to do? If not can reopen.
