### ISSUE TITLE
Validation - isAlert is no longer supported - regression

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#1922]
**Describe the bug**
re: SOHO-7224: 4.0 Validation Alert - ability to not set border, font, control icon color

This functionality was added in February 2018 and has subsequently been lost at some point. Please refer to the jira ticket above for the requirements. When the isAlert property is set to true, the border color, control text color, control icon color is displaying the color for the alert rather than displaying the default font color. 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/validation/test-message-types.html
2. Click on the Add Inline Message button
3. The text and date fields display an error icon with the message 'Message type is error'; the control border, control text, and control icon is red
4. Click on the Remove Message button
5. The error is removed
6. Click on the Is Alert checkbox
7. Click on the Add Inline Message button
8. The text and date fields display an error icon with the message 'Message is alert; type is error'
9. This is the error > the control border, control text, and control icon is red

**Expected behavior**
When Is Alert is checked, the control border, control text, and control icon should not have the color of the alert; it should maintain the default font color. This should be true for all of the validation types: error, alert, success, info, and icon.

**Version**

- ids-enterprise: v4.17.1

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/55734447-34d0e900-59e5-11e9-9f3c-5d0148a76bfa.png)

**Platform**

**Additional context**

**Comment by tmcconechy** [comment]
@fitzorama I tried to find this ever working. I vaguely remember this but dont see any evidence of it ever working all the way back to:

http://470-enterprise.demo.design.infor.com/components/validation/test-message-types.html

Do you have a screen shot how it once looked? Having a hard time picturing how isAlert should look

**Comment by janahintal** [comment]
QA Passed. Will Move to Done. Thanks!
Tested in: http://4180-beta0-enterprise.demo.design.infor.com/components/validation/test-message-types.html in all Browsers, OS and Devices.

**Comment by clepore** [comment]
I am reopening this so we remember to change it the code around to handle what we discussed in slack:
> We should still receive the `isAlert` option, but instead of doing overrides, simply have the code internally switch to use the `icon` type (which has 0 styles on it) and then pass in the icon from the originally requested alert type.

**Comment by clepore** [comment]
After an offline discussion, this is working as it should be.
