### ISSUE TITLE
Datagrid: Render issue with single column within modal dialog

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#1923]
Describe the bug
When a single column datagrid is within a modal dialog, the datagrid has render issues. The rows of the datagrid don't extend across. making it appear that the grid is not complete.

1. Using the attached example-modal-datagrid-single-column.html
2. Click on the 'Add Context' button to open a datagrid within a modal dialog
3. Notice that the Id column doesn't expand across making the rendering of the datagrid look incomplete

Expected behavior
Last column of the datagrid expands across the space

In Landmark we're also seeing that the column header doesn't span across the space allocated to the datagrid.

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/55738636-1bcc3600-59ed-11e9-8e62-a2cbe9260dc8.png)

**Comment by claudenbach** [comment]
This is what we see in Landmark.  Where the column header also doesn't stretch across the datagrid, but I couldn't come up with an example that replicates this exactly.

![image](https://user-images.githubusercontent.com/39804038/55738820-7feefa00-59ed-11e9-9bc1-4ce33c96430a.png)

**Comment by tmcconechy** [comment]
@claudenbach Im having a weird issue with the zip. It just unzips to a .cpgz every-time and i can never get into the files.

**Comment by claudenbach** [comment]
Is this one better?

[Git-1923.zip](https://github.com/infor-design/enterprise/files/3055690/Git-1923.zip)

**Comment by tmcconechy** [comment]
Yep thanks!

**Comment by tmcconechy** [comment]
Note: Fixed this on datagrid-master branch for review see https://github.com/infor-design/enterprise/pull/2137#issue-277524780 for further testing details.

The class i chose was `datagrid-default-modal-width`

**Comment by claudenbach** [comment]
Any idea when this change will be rolled up and available in an ids-enterprise-ng version?

**Comment by tmcconechy** [comment]
Probably by the end of the month when we release. We've been asked to isolate all datagrid changes on a special branch. This means they wont be available like normal soon as they are merged.

Once this does get back in master it just needs you to make an NG version with that nightly build in it and start using the class.

**Comment by tmcconechy** [comment]
This is ready to QA on the datagrid-master branch

**Comment by janahintal** [comment]
Hi @tmcconechy, upon checking in http://master-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-single-column.html 
the grid still didnt stretched after resizing the window. 
<img width="1144" alt="Screen Shot 2019-05-20 at 2 32 13 PM" src="https://user-images.githubusercontent.com/45757016/58002084-ef3d2b00-7b0f-11e9-87b9-84e500b5faee.png">

**Comment by tmcconechy** [comment]
Resizing and having to change is not supported yet but i did add a setting for it on 1818 so you can try that there. For now just dont resize the page...It wont have any effect in this scenario as that wasnt a use case i considered here.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
