### ISSUE TITLE
RTL: Datagrid column resize direction is reversed

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise#1924]
**Describe the bug**
In RTL datagrid the columns are resizing in the opposite direction that you drag the resize-handle.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-fixed-header.html?locale=he-IL#
2. Drag column resize-handle to the right and the column will resize to the left.

**Expected behavior**
The direction you drag and the column resizing should be going in the same direction.

**Comment by tmcconechy** [comment]
This was missing a project so i added it, this was added into 4.18

**Comment by janahintal** [comment]
Hi @tmcconechy, tested this ticket in the latest build. http://4180-rc3-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html?locale=he-IL# 

Issue still exist. Please see image below. Thanks
<img width="1419" alt="Screen Shot 2019-05-03 at 2 25 51 PM" src="https://user-images.githubusercontent.com/45757016/57122362-7cae1a80-6daf-11e9-91ba-a7a758e2ec68.png">

**Comment by tmcconechy** [comment]
Did this issue maybe go in 4.19 I wasn’t sure but thought it was in 4.18 by the date @jmacaluso711

**Comment by clepore** [comment]
@tmcconechy This went to master before we cut the `4.18.x` branch, so it should be in there. I'm going to go ahead and reopen this and move it to the DG milestone so you can address it with all the DG stuff for the `4.19` May sprint.

**Comment by SofiK** [comment]
The wrong separator is also dragged when dragging.

![The_wrong_column_is_resized_ids](https://user-images.githubusercontent.com/8664975/69011373-07302300-096a-11ea-81cd-b9ace1b3e94c.gif)

**Comment by tmcconechy** [comment]
Works better with recent fixes by needs more work for next sprint

**Comment by janahintal** [comment]
QA Passed. This issue is now resolved. Verified in https://4260-beta0-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html?theme=uplift&variant=light&locale=he-IL across all platform. Thank you.
