### ISSUE TITLE
Veracode scan for 4.18

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1927]
**Is your feature request related to a problem? Please describe.**

Veracode scans expired end of December. Should submit a scan on the latest (4.1.8 master) or near the end of 4.18 and mitigate or fix any issues it finds.

**Comment by tmcconechy** [comment]
Scans in progress

**Comment by janahintal** [comment]
Hi @tmcconechy, upon testing in http://localhost:4000/components/pager/example-standalone.html I notices that the "Reset Tooltips" button doesn't have a toast or log. May I know if this expected? Thank you!

**Comment by tmcconechy** [comment]
Yes that’s expected as there is no event there. I only changed the console log to a toast for events that fire. The reset tooltips just changes the tooltips on the pager buttons but doesn’t have any events to show

**Comment by janahintal** [comment]
> Yes that’s expected as there is no event there. I only changed the console log to a toast for events that fire. The reset tooltips just changes the tooltips on the pager buttons but doesn’t have any events to show

Thanks @tmcconechy. I already tested it and it seems fine. Will move the ticket to Done. Thank you! :)
