### ISSUE TITLE
Popupmenu: Submenus not showing on IOS

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1928]
**Describe the bug**
Submenus wont appear on IOS and are cut off. I do believe this once works.

**To Reproduce**
1. Go to http://latest-enterprise.demo.design.infor.com/components/popupmenu/test-ajax-submenu.html
2. Click on menu to open
3. Click on submenu

**Expected behavior**
Submenu should show.

**Version**
- ids-enterprise: [v4.18.0 / v4.17.0]

**Screenshots**
![Screen Shot 2019-04-08 at 1 23 02 PM](https://user-images.githubusercontent.com/814283/55743879-740d3300-5a01-11e9-8720-808ddb75ff4c.png)

**Platform**
 - Device [iPhone x]
 - OS Version: [iOS]
 - Browser Name [safari]

**Additional context**
Found on https://github.com/infor-design/enterprise/issues/1819

**Comment by tmcconechy** [comment]
Note:  there is a `-webkit-overflow-scrolling: auto css` class that may fix this.

**Comment by Sovia** [comment]
The submenu's ul is also missing the has-submenu class, which means that a third level menu will be cut off like above.

**Comment by tmcconechy** [comment]
Note to test the menu on https://github.com/infor-design/enterprise/issues/2362

**Comment by janahintal** [comment]
QA Passed. Will move to  Done. 
Tested in: https://master-enterprise.demo.design.infor.com/components/popupmenu/example-submenus.html & https://master-enterprise.demo.design.infor.com/components/popupmenu/test-scrolling
