### ISSUE TITLE
Tabs: Calling disableTab() steals focus to next available enabled tab 

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#1934]
**Describe the bug**
We have some hotkey logic that can call disableTab(), on keydown. When disabling, the focus jumps to the tab header of the next active tab. User can no longer type after this and has to manually set focus back to the field.

**To Reproduce**
This file should go in app/views/components/tabs.

1. Place this file in app/views/components/tabs [example-enable-disable-individual-tabs-with-keydown.zip](https://github.com/infor-design/enterprise/files/3060042/example-enable-disable-individual-tabs-with-keydown.zip)
1. Go to http://localhost:4000/components/tabs/example-enable-disable-individual-tabs-with-keydown.html
1. Click on 'Disable "Form Elements" tab on keydown'
1. Press a key, like down arrow
1. Focus will jump to 'Another' tab

**Expected behavior**
Tab should disable, but focus should stay in the field, as happens when enabling a tab.

**Version**

- ids-enterprise: master

**Additional context**
Sample file attached

**Comment by tmcconechy** [comment]
One potential fix i can see is to make sure activateAdjacentTab does not focus a tab when it changes the tab on disable. I dont see any reason it needs to. So fix might be

- add option to `select(tab, noFocus)` to not focus the tab after selecting it
- in activateAdjacentTab() call the option for the selects calls there 
- add an e2e test for this case
- test keyboard / selecting of tabs / disabling of tabs examples

**Comment by awbuboltz** [comment]
I pulled @deep7102's fix into our branch and it looks good, same solution I came up with.

**Comment by janahintal** [comment]
Hi @tmcconechy, upon checking in http://localhost:4000/components/tabs/example-enable-disable-individual-tabs-with-keydown.html, the "Enable "Form Elements" tab on keydown" field didn't disable as expected in #1938 after I click the arrow down key. The focus switch to Enable "Form Elements" tab on keydown field as I click Tab after the Arrow down key.

**Comment by tmcconechy** [comment]
Let's try to verify this on http://master-enterprise.demo.design.infor.com/components/tabs/example-enable-disable-individual-tabs-with-keydown.html instead. This has been merged and accepted by the original asker.

http://master-enterprise.demo.design.infor.com/components/tabs/example-enable-disable-individual-tabs-with-keydown.html
- in the "Disable "Form Elements" tab on keydown" - hit down arrow and the first tab will become disabled and the cursor should stay in the field
- in the "Enable "Form Elements" tab on keydown" tab on keydown" - hit down arrow and the first tab will become disabled and the cursor should stay in the field

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by awbuboltz** [comment]
Just a note, that second bullet point should say ..will become **enabled** and the cursor..
