### ISSUE TITLE
Application menu: support full-width role switcher

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#1935]
**Is your feature request related to a problem? Please describe.**
To support complex menus in products like HCM, we need to introduce a more robust role switcher in the application menu.

**Describe the solution you'd like**
Support an menu which areas over the application menu which can be populated by a dynamic and nested list.

**Describe alternatives you've considered**
We could support the more standard popover that exists in examples now but the experience isn't fine tuned and causes some discomfort on a phone layout.

**Additional context**
![Picture1](https://user-images.githubusercontent.com/1012017/55820819-037e1900-5aca-11e9-9b6c-f84c2174b2cd.png)

**Comment by tmcconechy** [comment]
Have to think about how we do this one? Maybe an option to popupmenu / menubutton?
Or do we just do all popupmenus like this on a phone?

**Comment by nickwynja** [comment]
@tmcconechy I think possibly just an app menu feature. I can't really see this behavior happening anywhere else.

**Comment by CindyMercadoReyes** [comment]
Attaching the BDD test case to this new enhancement.
[story_github#1935_draft.docx](https://github.com/infor-design/enterprise/files/3085063/story_github.1935_draft.docx)

**Comment by janahintal** [comment]
QA Passed. Will Move to Done. 
Tested in: 
http://localhost:4000/components/applicationmenu/example-personalized.html?colors=0563C2
http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html?colors=7025B6
http://localhost:4000/components/applicationmenu/example-personalized-roles.html?colors=0563C2
http://localhost:4000/components/applicationmenu/example-personalized.html?colors=7025B6&theme=uplift
http://localhost:4000/components/counts/example-not-actionable.html
http://localhost:4000/components/personalize/example-classes.html?color=0563C2
http://localhost:4000/components/personalize/example-classes.html

**Comment by tmcconechy** [comment]
@janahintal I think we should raise a new issue for this and not fail this one. As the issue is with the module tabs

http://localhost:4000/components/tabs-header/example-index.html

But i cannot reproduce it, when you raise a new issue can you add the browsers and the scroll bar mac setting your using? (I tried chrome mac with all settings and could not see the issue).

**Comment by tmcconechy** [comment]
Maybe the extra scroll bar is just on High Sierra Mac - if so it may be an OS bug we cant do anything about so maybe no need for a new issue.
