### ISSUE TITLE
Editor: Has errors and icon problems in Uplift

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1937]
**Describe the bug**
Some issues noticed on the editor in uplift theme.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html?theme=uplift
2. Select text
3. Click on the text color icon -> gives an error "Cannot read property 'border' of undefined"
4. Also note the icon alignment

**Expected behavior**
No error and better alignment. WIthout wrecking other themes.

**Version**
- ids-enterprise: [e.g. v4.18.0]

**Comment by kayiuho** [comment]
There's custom css built into the component that was meant to be used with the soho icon set. Not sure if there's another way to go around it without changing the codes and causing things to break? 

![icon_uplift_editor](https://user-images.githubusercontent.com/34747859/56911680-7cdeab00-6a7b-11e9-92f1-23e3ced6e052.png)

**Comment by tmcconechy** [comment]
I think i manually pushed some of these icons around because the original ones where all out of alignment and looked really strange all next to each other. If we can make the icons for B, I, U, S all line up nice in the sketch we can remove these css hacks.

**Comment by tmcconechy** [comment]
Closing in favor of https://github.com/infor-design/design-system/issues/441 which we will do next sprint
