### ISSUE TITLE
Datagrid: Using console.log in field data breaks datagrid layout

### ISSUE THREAD

**Issue by albinbergvall** [infor-design/enterprise#1941]
**Describe the bug**
If you use _console.log_ as a field in a row in a datagrid, the grid will break. This leads to unusual behavior, such as some entries not showing, cells disappearing and the content of cells not showing. I looked through the code for the HTML sanitation, and found that _console.log_ is sanitized when it's used, but found that the regex might be incorrect for detecting it, as it seems that is sanitizing too much. Note that _<script></script>_ is sanitized correctly, which also happens in the same sanitation method. 

**To Reproduce**
1. Edit a datagrid sample to contain _console.log_ in one of the fields.

**Expected behavior**
_console.log_ is either escaped or sanitized.

**Actual result**
See screenshot

**Version**

- ids-enterprise: 4.17

**Screenshots**
![image](https://user-images.githubusercontent.com/30404138/55879480-08f96300-5b9f-11e9-9803-717e6c13ecf1.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 73.0.3683.86 (Official Build) (64-bit)

**Additional context**
Where sanitation is performed: https://github.com/infor-design/enterprise/blob/26d314b58d3444b9fe985792f43867faf7c65737/src/utils/xss.js#L62

**Comment by tmcconechy** [comment]
Raising this as he as we like to treat XSS issues as higher priority.

**Comment by albinbergvall** [comment]
I checked the regex pattern on line 63. It appears that it's not closing correctly and matching everything after _console.log_.'(' & ')' needs to be escaped in the regex pattern as it's interpreted as a capture group in regex syntax.

**Comment by tmcconechy** [comment]
Ok, Your welcome to make a pull request if you do have a test https://github.com/infor-design/enterprise/blob/master/docs/CONTRIBUTING.md#pull-requests

**Comment by albinbergvall** [comment]
Well, honestly I'm not sure why console.log() needs to be sanitized? It has to be inside a script section to be executed anyway, right?  And sure, if you want to sanitize them go ahead, but shouldn't console.warn()/console.error() be sanitized as well for consistency?

**Comment by tmcconechy** [comment]
I'm guessing it doesnt need to be sanitized its just basically a test string. But i'm thinking either because the way it is sanitized its causing the markup to break in the cells. I think there is a case for a technique to hack thats being "fixed for" https://github.com/infor-design/enterprise/blob/master/test/components/utils/xss.func-spec.js#L33 the case of this is causing the markup to break when its run over the console.log text string.

**Comment by janahintal** [comment]
QA Passed. Will Move to Done
Tested in: http://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
