### ISSUE TITLE
Contextual Action Panel: Close button sits on top of overflow button

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#1943]
**Describe the bug**
In a contextual action panel, the close button is positioned on top of toolbar overflow button. 

**To Reproduce**

In any contextual action panel sample, 
(1) set showCloseButton to true 
(2) add four buttons so an overflow button is displayed in the toolbar
(3) Bring up the contextual action panel

**Expected behavior**
The close button is on the top right. And the toolbar overflow button is to its left.

**Version**
ids-enterprise: 4.17.1

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version:  Windows 10 
 - Browser Name Chrome
 - Browser Version 73.0.3683.86 (Official Build) (64-bit)]

**Comment by aaralikar** [comment]
![image](https://user-images.githubusercontent.com/22720894/55904975-a56b3780-5b96-11e9-8450-ccbcc7b7e10c.png)

**Comment by tmcconechy** [comment]
Can you update the issue and use the bug reporting template please: https://github.com/infor-design/enterprise/issues/new?template=bug_report.md

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-full-content.html
http://master-enterprise.demo.design.infor.com/components/modal/example-close-btn.html
Passed QA testing on all browsers, will retest once beta is deployed.
