### ISSUE TITLE
Composite Form and Step Process and Field Options: Deprecate and Remove

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#1944]
**Describe the bug**
The composite form component is no longer used by Landmark and we can deprecate it. I doubt that its used by many other teams. (But if you see this please coment Teams 😄)

Landmark is also working to get rid of Step Process and do that on their own too. So same with that one.

**To Do**

- [ ] List Composite Form component in the deprecated list so it has a change log and console log entry when it runs
- [ ] Landmark now rolls their own field options. We should see if we can deprecate? May possibly be used but i doubt it.
- [ ] Step Process component in the deprecated list so it has a change log and console log entry when it runs
- [ ] Wait the allocated time and drop all the code(s)

**Comment by pwpatton** [comment]
compositeform stuff ok to remove for landmark. 

Landmark is still using the stepprocess however. The goal is to manage that ourselves going forward but we have not started any of that work.

**Comment by tmcconechy** [comment]
We'll just leave these out of the Web component refactor. So wont actively remove these at this time.
