### ISSUE TITLE
Tooltip: Generic tooltip for any ellipsis text

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#1952]
**Is your feature request related to a problem? Please describe.**

One of our design feature in homepages widget (for XM) is to have a tooltip that only works on truncated texts. 

**Describe the solution you'd like**

It would be better if there's a setting on the tooltip instead of creating function in every components.
- Test this out on listview if the text is cut off
- Test it also on places like hierarchy https://github.com/infor-design/enterprise/issues/2008
- End develop would have to add this on texts they want to show with tooltips, it wont be possible to have it automatically working everywhere.

**Describe alternatives you've considered**

Implement the tooltip plugin and create a function.

**Additional context**

It would be better if we create this feature for both JavaScript and Angular Wrapper. We're implementing the widgets using Angular.

**Comment by tmcconechy** [comment]
Will build this out in new component but this doesnt need special issue
