### ISSUE TITLE
Header: Replace hard-coded subcomponents with settings-based subcomponents

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#1954]
**Describe the bug**
The IDS Header component's javascript part currently has some code paths that generate hard-coded navigation patterns when triggering certain methods:
- [`buildPopupMenu()`](https://github.com/infor-design/enterprise/blob/master/src/components/header/header.js#L290-L295) - Title Popupmenu (in place of the H1)
- [`buildBreadcrumb()`](https://github.com/infor-design/enterprise/blob/master/src/components/header/header.js#L181-L186) - Breadcrumbs
- [`buildTabs()`](https://github.com/infor-design/enterprise/blob/master/src/components/header/header.js#L227-L232) - Header Tabs
- [`buildWizard()`](https://github.com/infor-design/enterprise/blob/master/src/components/header/header.js#L258-L263) - Wizard

This was done during early SohoXI development to demonstrate various header configurations in an interactive test.  While it's possible to manually set all of these sub-components up with HTML markup, the hardcoded methods remain.  We should consider doing one of the following:

- Move the hardcoded portions directly into the test
- Flesh out the methods to no longer be hardcoded, and accept a setting for subcomponent options to be passed in via JS.

**To Reproduce**
See the test at https://master-enterprise.demo.design.infor.com/patterns/nav-patterns-test

**Version**
- ids-enterprise: v4.0.0+

**Screenshots**

![Screen Shot 2019-04-12 at 12 42 45 PM](https://user-images.githubusercontent.com/3249601/56052908-9f08c700-5d20-11e9-9c8a-7acad5626127.png)
![Screen Shot 2019-04-12 at 12 42 55 PM](https://user-images.githubusercontent.com/3249601/56052909-9fa15d80-5d20-11e9-94c3-43af2928cbe0.png)
![Screen Shot 2019-04-12 at 12 43 05 PM](https://user-images.githubusercontent.com/3249601/56052910-9fa15d80-5d20-11e9-8af1-665439f06108.png)

**Platform**
- n/a

**Additional context**
- n/a

**Comment by tmcconechy** [comment]
descoping this for now
