### ISSUE TITLE
Compact Form: Implement additional features

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#1955]
**Is your feature request related to a problem? Please describe.**
The compact form implementation is currently just the foundation. Let's add some more feature support in.

**Describe the solution you'd like**
Support for:
- [ ] checkbox
- [ ] radios
- [x] date picker
- [x] time picker
- [x] file browser
- [x] lookup
- [ ] drop down

**Additional context**
We'll need to work through designs first

**Comment by tmcconechy** [comment]
What about all form fields for example lookup?

**Comment by nickwynja** [comment]
@tmcconechy Yes, lookup should be another. I these field+icon examples, those aren't coded as a different component, are they? Just using a different icon and event?

**Comment by tmcconechy** [comment]
No they are all different components.

**Comment by EdwardCoyle** [comment]
@nickwynja is there a design system ticket for the designs that need to be reviewed?

**Comment by EdwardCoyle** [comment]
@nickwynja I set up [1955-compact-form-complex-fields](https://github.com/infor-design/enterprise/tree/1955-compact-form-complex-fields) for the work on this issue.

**Comment by kayiuho** [comment]
I created a Dropbox Paper where the in-progress designs are posted: https://paper.dropbox.com/doc/Compact-Form--AdQOsMg9ysFNqD9ePAL2y7agAQ-R8idPCwaQcbGBbIZVX3Md (internal H&L link)
Let me know if anyone has any design or implementation thoughts.

**Comment by EdwardCoyle** [comment]
I raised #2193 to punt Checkbox, Radios, and Dropdowns for a future PR.  Will add that issue up for `v4.20.x`

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to QA failed due to the page not having any alignment issues on Field 18 for FF on MAC.  Please see the screen shot attached. 
![IDS compact component](https://user-images.githubusercontent.com/39101346/58264885-a45c2700-7d4c-11e9-88d0-b4015c4b11a7.png)

**Comment by clepore** [comment]
@CindyMercadoReyes Not sure what you mean by "QA failed due to the page not having any alignment issues on Field 18".
