### ISSUE TITLE
Datagrid Component: RTL column alignment issue on mobile 

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1957]
**Describe the bug**
Data Grid Component: RTL column alignment issue on mobile 

**To Reproduce**
1. Go to url: http://master-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html?locale=he-IL#
2. Change the row count to 25 per page
3. Scroll up and down 
4. See error. The columns are not aligned with the rows. Please see screen shot attached. 

**Expected behavior**
Columns and rows should be aligned. 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![bs_realdroid_Mobile_Samsung Galaxy S9-8 0-1440x2960](https://user-images.githubusercontent.com/39101346/56143028-c2748180-5f6d-11e9-9dba-f1b28e03a559.jpg)

**Platform**
 - Device (if applicable) [Samsung Galaxy S9]
 - Browser Name [Chrome]

**Additional context**
None

**Comment by tmcconechy** [comment]
Look at this with https://github.com/infor-design/enterprise/issues/1818 maybe

**Comment by janahintal** [comment]
Hi @tmcconechy , noticed that when in iOS, after I flipped the screen to landscape. The columns misaligned. Please see image below. Tested in http://master-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html?locale=he-IL#

<img width="1178" alt="Screen Shot 2019-05-08 at 6 26 23 PM" src="https://user-images.githubusercontent.com/45757016/57370366-9510a180-71c2-11e9-976c-07bd6730ecbe.png">

**Comment by tmcconechy** [comment]
Ok let’s make a separate issue for that as it’s a new case about flipping

**Comment by janahintal** [comment]
Hi, @tmcconechy logged #2138 for this. Thanks!

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
