### ISSUE TITLE
Datagrid: Popoupmenu in selection toolbar is opened behind datagrid in Safari

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#1960]
**Describe the bug**
When using a datagrid with the toolbar that is displayed only on selection the popupmenus in that toolbar are opened behind the datagrid in Safari.

I've edited the http://localhost:4000/components/datagrid/example-mixed-selection.html code t oinclude a more button. But I'm not allowed to add the .html file.. so Here you get it as a .txt instead 
[example-mixed-selection.txt](https://github.com/infor-design/enterprise/files/3083736/example-mixed-selection.txt)

**To Reproduce**

In Mac **(Safari)**:
1. Copy the code from the attached .txt to the example-mixed-selection.html
2. Open it as http://localhost:4000/components/datagrid/example-mixed-selection.html 
3. Select a line in the first grid
4. Click the ... popupmenu
5.  See the error, The popupmenu is displayed behind the datagrid.

**Expected behavior**
The popupmenu is displayed on top of the datagrid (so that it is visible)

**Version**
Found in IDS 4.14 but reproduced in 4.17.

**Screenshots**
<img width="1433" alt="Screen Shot 2019-04-16 at 10 02 24 AM" src="https://user-images.githubusercontent.com/8664975/56193528-201dd200-6031-11e9-95c4-dbfda06af5da.png">

**Platform**
 - OS Version: macOS Mojave Version 10.14.4
 - Browser Name: Safari
 - Browser Version: Version 12.1 (14607.1.40.1.4)

**Additional context**
-

**Comment by tmcconechy** [comment]
FYI you can attach HTML - you just have to put it in a zip file.

**Comment by tmcconechy** [comment]
Perhaps this issue is similar to https://github.com/infor-design/enterprise/issues/1928

**Comment by janahintal** [comment]
HI @tmcconechy, tested the ticket in the below link. The popup menu issue is now fixed in Safari. However, the 'Row height' functionality is not working. 
Tested in: http://master-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection-popupmenu.html

**Comment by tmcconechy** [comment]
OK, Thats unrelated to the fix. Also you raised that one here: https://github.com/infor-design/enterprise/issues/1989 its just a problem in the example not being wired up so not serious. I will fix it there.

**Comment by janahintal** [comment]
Thanks, @tmcconechy. Already verified this thru http://master-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection-popupmenu.html. 

Will move to Done.
