### ISSUE TITLE
Accessibility: Interacting with checkbox several times, "aria-checked" attribute is incorrect

### ISSUE THREAD

**Issue by Moorhed** [infor-design/enterprise#1961]
**Describe the bug**
When clicking several times on checkbox in header (see attached screenShot) attribute "aria-checked" remains in true value despite the checkbox is check or un-checked. On the first three clicks, attribute is changing value correctly.
HTML of the header is attached.
![CheckBox](https://user-images.githubusercontent.com/36002693/56200357-ece23f80-603e-11e9-80a3-90facfec5023.jpg)

**To Reproduce**
Steps to reproduce the behaviour:
1. Inspect the code of HTML
2. Click 4 times the checkbox
3. Notice how the "aria-checked" attribute is changing the  value
Happening in FF and CHrome (did not try other browsers)

**Expected behaviour**
"aria-checked" has always correct value

Here is part of the code:
<div class="datagrid-checkbox-wrapper  l-center-text">
	<span class="datagrid-header-text"/>
	
	<span aria-checked="false" class="datagrid-checkbox" aria-label="Selection" role="checkbox"/>
</div>

**Version**
4.10.0

**Platform**
FF and Chrome
[HeaderCode.zip](https://github.com/infor-design/enterprise/files/3084290/HeaderCode.zip)

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect
Passed QA testing on all browsers, will retest once beta is deployed.
