### ISSUE TITLE
Personalization: Need ability for landmark context form to have personalization background color

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#1963]
**Is your feature request related to a problem? Please describe.**
Need landmark context form to have personalization color for composite forms. 

**Describe the solution you'd like**
Would like to add .is-personlizable class to format some elements in it that arent yet supported.

**Additional context**
Note: not using the .compositeform jquery component or ep markup for this.

![image](https://user-images.githubusercontent.com/4737815/56220938-ee0b7080-602e-11e9-84bd-9ecd3f77db7f.png)

**Comment by tmcconechy** [comment]
Can you attach the markup for those sections so we can build out an example?

**Comment by pwpatton** [comment]
<div class="page-container no-scroll" xmlns:margin-top="http://www.w3.org/1999/xhtml">
  <header class="header is-personalizable">
    <div class="toolbar">
      <div class="title">
        <h1>Level Two Detail View</h1>
      </div>

      <div class="buttonset">
      </div>

      {{> includes/header-actionbutton}}
    </div>
  </header>

  <section id="maincontent" class="scrollable" role="main">
    <section style="margin-top:30px;">
      <div class="content">
        <div class="row">
          <div class="one-fifth column one-half-mobile">
            <label>Item</label>
            <p class="name-xl">2000 LGE Incorporated</p>
          </div>
          <div class="one-fifth column one-half-mobile">
            <label>Purchase Order Date</label>
            <p class="name-xl">7/14/2006</p>
          </div>
          <div class="one-fifth column one-half-mobile">
            <label>Vendor</label>
            <p class="name-xl">116</p>
          </div>
          <div class="one-fifth column one-half-mobile">
            <label>Purchase Order</label>
            <p class="name-xl">1096</p>
          </div>
          <div class="one-fifth column one-half-mobile">
            <label>Delivery Order</label>
            <p class="name-xl">7/14/2006</p>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="tab-container">
        <div class="tab-list-container scrollable-y">
          <ul class="tab-list">
            <li class="tab is-selected"><a id="detail" href="#composite-form-detail">Detail</a></li>
            <li class="tab"><a id="options" href="#composite-form-options">Options</a></li>
            <li class="tab"><a id="quantity_detail" href="#composite-form-quantity-detail">Quantity Detail</a></li>
            <li class="tab"><a id="user-fields" href="#composite-form-user-fields">User Fields</a></li>
            <li class="tab"><a id="messages" href="#composite-form-messages">Messages</a></li>
            <li class="tab"><a id="add-on-changes" href="#composite-form-addon-changes">Add-On Changes</a></li>
            <li class="tab"><a id="sources" href="#composite-form-sources">Sources</a></li>
          </ul>
        </div>
      </div>
      <div class="tab-panel-container scrollable-y">
        <div id="composite-form-detail" class="tab-panel" role="tabpanel">
          <div class="row form-responsive">
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-item">Item</label>
                <input id="composite-form-detail-item" class="lookup"/>
              </div>
            </div>
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-quantity">Quantity</label>
                <input id="composite-form-detail-quantity" class="lookup"/>
              </div>
            </div>
          </div>

          <div class="row form-responsive">
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-entered-by-uom">Entered Buy UOM</label>
                <input id="composite-form-detail-entered-by-uom" class="lookup"/>
              </div>
            </div>
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-item-type">Item Type</label>
                <input id="composite-form-detail-item-type" class="lookup"/>
              </div>
            </div>
          </div>

          <div class="row form-responsive">
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-description">Description</label>
                <input id="composite-form-detail-description" class="lookup"/>
              </div>
            </div>
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-service-code">Service Code</label>
                <input id="composite-form-detail-service-code" class="lookup"/>
              </div>
            </div>
          </div>

          <div class="row form-responsive">
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-unit-cost">Item</label>
                <input id="composite-form-detail-unit-cost" class="lookup"/>
              </div>
            </div>
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-late-delivery-date">Late Delivery Date</label>
                <input id="composite-form-detail-late-delivery-date" class="lookup"/>
              </div>
            </div>
          </div>

          <div class="row form-responsive top-padding">
            <div class="six columns">
              &nbsp;
            </div>
          </div>

          <div class="row form-responsive">
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-vendor-item">Vendor Item</label>
                <input id="composite-form-detail-vendor-item" class="lookup"/>
              </div>
            </div>
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-contract-line">Contract Line</label>
                <input id="composite-form-detail-contract-line" class="lookup"/>
              </div>
            </div>
          </div>

          <div class="row form-responsive">
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-distribution-code">Distribution Code</label>
                <input id="composite-form-detail-distribution-code" class="lookup"/>
              </div>
            </div>
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-contract">Contract</label>
                <input id="composite-form-detail-contract" class="lookup"/>
              </div>
            </div>
          </div>

          <div class="row form-responsive">
            <div class="six columns">
              <div class="field">
                <label for="composite-form-detail-early-delivery-date">Early Delivery Date</label>
                <input id="composite-form-detail-early-delivery-date" class="lookup"/>
              </div>
            </div>
          </div>
        </div>
        <div id="composite-form-options" class="tab-panel" role="tabpanel">
          <div class="row">
            <div class="twelve columns">
              <h3>Options</h3>
            </div>
          </div>
        </div>
        <div id="composite-form-quantity-detail" class="tab-panel" role="tabpanel">
          <div class="row">
            <div class="twelve columns">
              <h3>Quantity Detail</h3>
            </div>
          </div>
        </div>
        <div id="composite-form-user-fields" class="tab-panel" role="tabpanel">
          <div class="row">
            <div class="twelve columns">
              <h3>User Fields</h3>
            </div>
          </div>
        </div>
        <div id="composite-form-messages" class="tab-panel" role="tabpanel">
          <div class="row">
            <div class="twelve columns">
              <h3>Messages</h3>
            </div>
          </div>
        </div>
        <div id="composite-form-addon-changes" class="tab-panel" role="tabpanel">
          <div class="row">
            <div class="twelve columns">
              <h3>Add-On Changes</h3>
            </div>
          </div>
        </div>
        <div id="composite-form-sources" class="tab-panel" role="tabpanel">
          <div class="row">
            <div class="twelve columns">
              <h3>Sources</h3>
            </div>
          </div>
        </div>
      </div>
    </section>
  </section>

</div>

**Comment by pwpatton** [comment]
[example-compform.html.txt](https://github.com/infor-design/enterprise/files/3090303/example-compform.html.txt)

**Comment by pwpatton** [comment]
[example-compform2.html.txt](https://github.com/infor-design/enterprise/files/3090431/example-compform2.html.txt)

Example Issues: same issues as above example and this:
- image isn't aligning with fields correctly maybe

**Comment by CindyMercadoReyes** [comment]
This ticket failed QA. Conducted testing using the url's below and the colors are not appearing correctly on the page.  Please see screens shot attached. 
URLs:
http://localhost:4000/components/personalize/example-form2.html
http://localhost:4000/components/personalize/example-form.html

![bs_win10_Edge_18 0(1)](https://user-images.githubusercontent.com/39101346/58029299-46c8a000-7aea-11e9-83d0-3a551fcdea5e.jpg)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
