### ISSUE TITLE
ApplicationMenu: Menu items should have a possibility to not enable blue background when clicking on it

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise#1968]
**Is your feature request related to a problem? Please describe.**
When creating an application menu using `accordion-header` css class, it is not possible to disable blue background when clicking on the menu item. The use case is clicking on the menu item, it triggers opening a modal dialog and BA doesn't want the selected menu item to have blue background.

**Describe the solution you'd like**
A way to disable blue background when the menu item is selected

**Describe alternatives you've considered**
I have to create my own css class which copies styling from `accordion-header` to achieve this.

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
We could add a class like `is-not-selectable` that will not show the styles. But also i think its fine if you add the classes on the app to do this until we can get to this.

**Comment by tmcconechy** [comment]
We decided to descope this as it's not the normal planned behavior of the app menu. But you can override it on your end if you need to.
