### ISSUE TITLE
Datagrid - toggle filter row breaks the UI

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#1969]
**Describe the bug**
When we use the datagrid toggle filter row feature, it breaks the UI - column titles are not visible

**To Reproduce**
1. run demo app
2. open DataGrid - Toolbar and Breadcrumb page
3. hit Toggle Filter Row button twice

**Expected behavior**
Column names should be visible

**Version**
- ids-enterprise-ng: 5.2.1

**Screenshots**
![image](https://user-images.githubusercontent.com/11279863/56281482-03ef6300-610d-11e9-80cd-63d04901e5d9.png)

**Platform**
- OS Version: Windows 10
- Browser Name: Chrome
- Browser Version: Version 73.0.3683.103 (Official Build) (64-bit)

**Additional context**

**Comment by clepore** [comment]
It seems as if the sort actions (up/down carets) are somehow appearing after the filter toggle out of place. See this screenshot & screen capture:

- <img width="164" alt="Screen Shot 2019-04-17 at 10 20 40 AM" src="https://user-images.githubusercontent.com/742319/56295787-48720300-60fb-11e9-9ac4-160031f25644.png">

- [datagrid-toggle-filter-row-alignment.mov.zip](https://github.com/infor-design/enterprise/files/3090084/datagrid-toggle-filter-row-alignment.mov.zip)

**Comment by janahintal** [comment]
Hi @clepore, I have tried testing http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-filter.html in different browsers and OS. Seems fine but when I test it in Windows10 IE11 and Edge, the header label is aligned Center and when hovered, it will switch position to top left which is different to other browser. 

May I know if this is expected in Windows Edge and IE11 browsers?
Please see image below.  

Edge: 
<img width="1001" alt="Screen Shot 2019-04-22 at 3 23 07 PM" src="https://user-images.githubusercontent.com/45757016/56489072-143f7d80-6513-11e9-8fd3-e7391f185315.png">
 
IE11:
<img width="986" alt="Screen Shot 2019-04-22 at 3 18 12 PM" src="https://user-images.githubusercontent.com/45757016/56489078-1acdf500-6513-11e9-923a-680680bcb26f.png">

**Comment by clepore** [comment]
@janahintal this is not expected functionality. We will fix.

**Comment by janahintal** [comment]
QA Passed. Moving to Done. Thanks
Verified in: http://4180-rc0-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-filter.html
