### ISSUE TITLE
Theme: Add uplift theme dark variant

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1972]
**Is your feature request related to a problem? Please describe.**
Start showcasing the uplift theme dark variant in beta.

**Describe the solution you'd like**
Add the dark variant as an option beside the uplift light variant by using the existing EP soho theme dark variant as the basis and layer the uplift over top of it.

**Describe alternatives you've considered**
n/a

**Additional context**
Depends on 
- https://github.com/infor-design/design-system/issues/299
- https://github.com/infor-design/design-system/issues/374
- `ids-identity@2.6.0` release.

**Comment by tmcconechy** [comment]
You read my mind. This would now partially depend on: https://github.com/infor-design/enterprise/pull/1971
- Find a way to list the tokens or add to that theme list in there in theme.js
- Change the page-switcher to use that `Soho.theme.list` list to avoid the hard coding there or add to those elements.
- Add the SASS needed ect
