### ISSUE TITLE
Application menu: need to initialize expandable area within application menu and add support to close expandable area

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#1978]
**Describe the bug**
When there is a role switcher in the application menu header, the expandable area for the switcher needs to be initialized within application menu.
Need a new function for closing the expandable area when an accordion within the expandable area is selected.

**To Reproduce**
1. Go to application menu 
2. Click on the role switcher
3. Expandable area is not shown

**Expected behavior**
Expandable area should be shown when a role switcher is clicked.

**Version**
 v4.18.0

**Platform**
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version Version 73.0.3683.103 (Official Build) (64-bit)

**Additional context**

**Comment by CindyMercadoReyes** [comment]
http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html

Steps
- click on Employee >
- click on an item
- will now close when you click

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
