### ISSUE TITLE
Functional Tests: Tab tests randomly failing

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#1979]
**Describe the bug**
Functional tab tests are now starting to randomly fail.

**To Reproduce**
1. See the screenshot

**Expected behavior**
Tabs tests should pass

**Version**

- ids-enterprise: 4.18.0-dev+

**Screenshots**
<img width="650" alt="Screen Shot 2019-04-22 at 9 42 05 AM" src="https://user-images.githubusercontent.com/742319/56503374-34efdf00-64e3-11e9-8154-d595bfce705c.png">

**Platform**
 n/a

**Additional context**

**Comment by brianjuan** [comment]
Moving to Done since there is no QA testing needed for this.
