### ISSUE TITLE
Datagrid: Tooltip pointing in the wrong row

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1983]
**Describe the bug**
Datagrid: Tooltip pointing in the wrong row.

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html
2. Hover in 1st row activity column 
* notice that the pointer is not in the focused row

**Expected behavior**
Tooltip must be pointing in the 1st row activity column 

**Version**

- ids-enterprise: [v4.X.0] (seems to be all modern versions - @clepore )

**Screenshots**
<img width="1091" alt="Screen Shot 2019-04-23 at 3 31 43 PM" src="https://user-images.githubusercontent.com/45757016/56564389-77e3ac80-65e0-11e9-8f85-10f2cc381485.png">

**Platform**
All Browsers and OS
Tested in 
Windows 10: Chrome

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
Descoping this issue for now
