### ISSUE TITLE
Datagrid Row Reorder: Bottom Scroll bar is not hiding after reordering to the bottom

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1984]
**Describe the bug**
Datagrid Row Reorder: Bottom Scroll bar is not hiding after reordering to the bottom

**To Reproduce**
1. Open Chrome browser and Go to http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/example-row-reorder.html
2. Adjust the row height to Short
3. Take the 1st row and move at the bottom row
* Notice that the bottom scrollbar became visible with no way to be hidden

**Expected behavior**
No scrollbar should appear / scroll bar should get hidden

**Version**

- ids-enterprise: [v4.18.0]

**Screenshots**
<img width="1436" alt="Screen Shot 2019-04-23 at 4 58 04 PM" src="https://user-images.githubusercontent.com/45757016/56568152-0a884980-65e9-11e9-9e27-522dc569d3bb.png">

**Platform**
Os: Mac, Windows 10
Browser: Chrome

**Additional context**
No any other context about the problem here.

**Comment by clepore** [comment]
@janahintal I am actually unable to reproduce this. What is your OS X scroll bar setting, maybe that is affecting it?

🍎 > System Preferences > General:
<img width="415" alt="Screen Shot 2019-04-23 at 4 24 30 PM" src="https://user-images.githubusercontent.com/742319/56613302-5a184680-65e4-11e9-8198-7f8140380f12.png">

**Comment by janahintal** [comment]
Hi @clepore , I was able to replicate it in Mac High Sierra OS but can't reproduce it in Mojave. Thanks!

**Comment by tmcconechy** [comment]
I think we should close this then, as its probably an OS problem and there wont be much we can do about it.
