### ISSUE TITLE
Datagrid Paging: after removing 1 Row in 1000 data, the page became 1 of 1 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1985]
**Describe the bug**
Datagrid Paging: after removing 1 Row in 1000 data, the page became 1 of 1 

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/example-paging.html
2. Select row '0'
3. Remove Row
* notice that the row has been removed but the pager became 1 of 1 instead of 1 of 100.

**Expected behavior**
Row should be removed and the pager should display 1 of 100

**Version**
v4.16.0+

**Screenshots**
<img width="1272" alt="Screen Shot 2019-04-23 at 5 57 40 PM" src="https://user-images.githubusercontent.com/45757016/56572260-53dc9700-65f1-11e9-99fb-db673a7a610a.png">

**Platform**
All OS, Browser and Devices. 

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
Issues goes back quite a few versions, just noting.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
