### ISSUE TITLE
Datagrid: Paging inconsistent in Windows browsers Edge, Safari, IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1986]
**Describe the bug**
Datagrid Paging inconsistent in Windows browsers Edge, Safari, IE11

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/example-paging.html
2. Filter 75 records per page
3. Scroll down 
4. Click Next Page button 
5. Click Last Page button
6. Click Previous Page button
* notice that the page position changed / scrolled up

**Expected behavior**
Previous page should have same behavior as with Next Page button

**Version**
v4.18.0

**Platform**
Windows 10 
Edge, Safari and IE11 browsers

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
Issues goes back a few versions. Probably just the link getting followed for some reason

**Comment by tmcconechy** [comment]
Descoping this issue for now because of https://github.com/infor-design/enterprise/issues/3756
