### ISSUE TITLE
Datagrid: paging error after clicking previous button from last page

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1987]
**Describe the bug**
Datagrid paging indeterminate no data available error after clicking Previous button 

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html
2. Filter 75 records per page
3. Click Last page button
4. Click Previous page button
*No data available error is displayed

**Expected behavior**
Expecting records to be displayed 

**Version**
v4.16.0+

**Screenshots**
<img width="1608" alt="Screen Shot 2019-04-23 at 6 24 52 PM" src="https://user-images.githubusercontent.com/45757016/56574153-21349d80-65f5-11e9-8330-db15402a697e.png">

**Platform**
All Browsers, OS and Devices

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
Probably just a demo app bug, been thinking of removing this example in favor of the indeterminate-landmark example which works and is more realistic about how its used in indeterminate mode.

**Comment by tmcconechy** [comment]
Descoping this for now.
