### ISSUE TITLE
Datagrid Mixed Selection Row height filter is not working

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#1989]
**Describe the bug**
Datagrid Mixed Selection Row height filter is not working

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection.html
2. Click '52295' in My Assets Table
3. Click '...' button in Detail Table
4. Filter Row height to 'Short'
5. Click '...' button in My Assets table
6. Filter Row Height to 'Short'

**Expected behavior**
My Assets table row height should change to 'Short'

**Version**
v4.18.0

**Screenshots**
<img width="1206" alt="Screen Shot 2019-04-23 at 7 02 34 PM" src="https://user-images.githubusercontent.com/45757016/56577711-3a8e1780-65fe-11e9-8c17-457156aef65e.png">

**Platform**
All Browser, OS and Devices. 

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
The top grid has a custom toolbar so its just not wired in right.

**Comment by tmcconechy** [comment]
Could no longer reproduce this issue. Moving to QA to verify in case i missed something.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.
