### ISSUE TITLE
Contextual Action Panel Component: Can only open the contextual action panel one time.

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1993]
**Describe the bug**
Contextual Action Panel Component: Can only open the contextual action panel one time.

**To Reproduce**
1. Go to url: http://4180-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-centered.html
2. Click on the "Open Contextual Action Panel" button
3. Click the "X" button to close the panel
4. Click on the "Open Contextual Action Panel" button again
5. The user is unable to open the panel. The only way to open the panel is by refreshing the page.

**Expected behavior**
The user should be able to "Open Contextual Action Panel" button multiple times

**Version**

- ids-enterprise: 4.18.0-beta.0

**Screenshots**
none

**Platform**
 - OS Version: [iOS 8]
 - Browser Name [e.g. FF]
 - Browser Version [ 66.0.2 (Official Build) (64-bit)]

**Additional context**
None

**Comment by janahintal** [comment]
QA Passed. Tested in all browser and OS. Will move to Done. 
Verified in: http://4180-rc0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-centered.html
