### ISSUE TITLE
Color picker Sizes Component: Responsive alignment issue for Large color picker 

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1995]
**Describe the bug**
Color picker Sizes Component: Responsive alignment issue for Large color picker 

**To Reproduce**
1. Go to url: http://4180-beta0-enterprise.demo.design.infor.com/components/colorpicker/example-sizes.html
2. Make the page responsive
3. Scroll down to "Large" 
4. The frame is cut off. Please see screen shot attached

**Expected behavior**
The frame should not be cut off

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![ColorPicker ALignment Issue](https://user-images.githubusercontent.com/39101346/56607525-b83e2d00-65d6-11e9-91e9-5023e49f1605.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g.iOS 8]
 - Browser Name [FF]
 - Browser Version [66.02 (Official Build) (64-bit)]

**Additional context**
None

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/colorpicker/example-sizes.html
Passed QA testing on all browsers, will retest once beta is deployed.

**Comment by brianjuan** [comment]
http://4190-beta2-enterprise.demo.design.infor.com/components/colorpicker/example-sizes.html
On Chrome, when height is set to lower size (scrollbar is visible), the Large colorpicker is having layout issues.
<img width="506" alt="Screen Shot 2019-06-10 at 1 56 17 PM" src="https://user-images.githubusercontent.com/39508864/59175290-977e6680-8b87-11e9-8cbb-3e841108469b.png">

**Comment by tmcconechy** [comment]
@davidcarlsonberg Did you want to take a quick look?

**Comment by brianjuan** [comment]
http://localhost:4000/components/form/example-inputs.html
http://localhost:4000/components/colorpicker/example-sizes.html
Passed QA testing on all browsers, will retest once beta is deployed.
