### ISSUE TITLE
Autocomplete Component: Enter key doesn't work for making a selection

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#1996]
**Describe the bug**
Autocomplete Component: Enter key doesn't work for making a selection

**To Reproduce**
1. Go to url: http://4180-beta0-enterprise.demo.design.infor.com/components/autocomplete/example-keyword.html
2. Tab into the "States" field box
3. Type in "New" a list with the states containing "New" will appear in the dropdown
4. Arrow key down and highlight "New York"
5. Click on the "Enter" key on your keyboard to make "New York" your selection
6. When I click on the "Enter" key it doesn't select New York. The dropdown stays opened and doesn't make the selection

**Expected behavior**
When the user clicks on the "Enter" key the dropdown should close and "New York" should be populated in the "States" field box

**Version**

- ids-enterprise: [v4.18]

**Screenshots**
No screenshot

**Platform**
 - OS Version: [ iOS 8]
 - Browser Name: [FireFox]
 - Browser Version [ 66.0.2 (Official Build) (64-bit)]

**Additional context**
None

**Comment by janahintal** [comment]
QA Passed. Tested in all Browsers and OS. Will move to Done. Thanks!
Verified in: http://4180-rc0-enterprise.demo.design.infor.com/components/autocomplete/example-keyword.html
