### ISSUE TITLE
Functional Tests: ListBuilder tests randomly failing

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise#1997]
**Describe the bug**
Functional ListBuilder tests are randomly failing

**To Reproduce**
1. See screenshot

**Expected behavior**
ListBuilder tests should pass

**Version**

- ids-enterprise: 4.18.0-dev+

**Screenshots**
![Screen Shot 2019-04-23 at 4 02 47 PM](https://user-images.githubusercontent.com/1084735/56612222-c5ace480-65e1-11e9-9be0-cdb24b691723.png)

**Platform**
 - n/a

**Additional context**

**Comment by tmcconechy** [comment]
I think for a fix we want to make sure in beforeEach that there is a new array object. i had a similar issue in datagrid https://github.com/infor-design/enterprise/blob/master/test/components/datagrid/datagrid-api.func-spec.js#L46

Some of the functions might be adding to the dataset and effecting the tests when run in random order.
