### ISSUE TITLE
Datagrid: Button is cut off when row is expanded on short row height

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#1999]
**Describe the bug**
Datagrid: Button is cut off when a row is expanded on short row height

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row-one-only.html
2. Change the row height to Short
3. Click the + icon of the first row to expand
4. See issue: New Order button on the last column is cut off

**Expected behavior**
The button should not be cut off when a row is expanded

**Version**
- ids-enterprise: v4.17.0 - v4.18.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/56638758-8ba31780-66a1-11e9-9c86-951a32fbf374.png)

**Platform**
 - All Devices, OS, and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Issue goes back to 4.15 at least http://4150-enterprise.demo.design.infor.com/components/datagrid/test-expandable-row-one-only.html

**Comment by tmcconechy** [comment]
Note: This is fixed on datagrid-master for texting see https://github.com/infor-design/enterprise/pull/2151#issue-278732527 for details.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row-one-only.html
Passed QA testing on all browsers, will retest once beta is deployed.
