### ISSUE TITLE
Splitter position saving in localstorage

### ISSUE THREAD

**Issue by mythilinishtala** [infor-design/enterprise#2000]
**Describe the bug**
Splitter: In spite of setting the save property to false in the soho-splitter, the positions of splitter are still  saved in local storage.

**Expected behavior**
The splitter positions should not be saved if the 'save' property is set to false.
Version

**Version**
- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Platform**
- ids-enterprise-ng :  5.0.0

**Additional context**
See MS Teams

**Comment by tmcconechy** [comment]
@mythilinishtala How are you setting it to false in the code? As this option is working as expected see: http://latest-enterprise.demo.design.infor.com/components/splitter/example-splitter-right.html

Often in Angular people set this wrong. I also tested NG and it is working on this example as expected https://github.com/infor-design/enterprise-ng/blob/master/src/app/splitter/splitter-vertical.demo.html#L17

```
    <soho-splitter [isSplitterRight]="true" [collapseButton]="false" [save]="false">
      <div class="panel-header"></div>
    </soho-splitter>
```
