### ISSUE TITLE
Datagrid: Incorrect column data on exported csv/excel files

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2001]
**Describe the bug**
Datagrid: Incorrect column data on exported csv/excel files

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html
2. Click "Export To Csv" button and "Export To Excel" buttons
3. Open the downloaded .csv and .xls files
4. See issue: The values are incorrect on the Product Name, Quantity, Price and Status columns of the downloaded files.

**Expected behavior**
The column values on the exported files should match the values on the Datagrid

**Version**
- ids-enterprise: v4.17.0 - v4.18.0-beta0

**Screenshots**
.csv file
<img width="903" alt="Screen Shot 2019-04-24 at 4 18 29 PM" src="https://user-images.githubusercontent.com/39508864/56643735-c2325f80-66ac-11e9-8774-1a075be08a5f.png">

.xls file
<img width="760" alt="Screen Shot 2019-04-24 at 4 19 08 PM" src="https://user-images.githubusercontent.com/39508864/56643748-c8c0d700-66ac-11e9-965b-79f486a680ea.png">

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by davidcarlsonberg** [comment]
Looks to me like this may not be a bug as those columns not translated to the CSV have `data-exportable="false"`.

**Comment by brianjuan** [comment]
http://4180-rc0-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html
Passed QA testing, moving to Done.
