### ISSUE TITLE
Multiselect: Previous selection is still selected even after unselecting "Select All"

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2003]
**Describe the bug**
Multiselect: Previous selection is still selected even after unselecting "Select All".

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/multiselect/test-select-all.html
2. Open the States dropdown
3. Select Alabama then close the dropdown, Alabama will be displayed on the dropdown
4. Open the States dropdown again, click "Select All" then close the dropdown
5. All States will be displayed on the dropdown
6. Open the States dropdown again, then uncheck "Select All", close the dropdown
7. See issue: Alabama is still displayed on the dropdown

**Expected behavior**
Previous selection should not be displayed when "Select All" is unchecked

**Version**
- ids-enterprise: v4.18.0-beta0

**Screenshots**
![multiselect](https://user-images.githubusercontent.com/39508864/56646367-007e4d80-66b2-11e9-8dca-f344c903ef39.gif)

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This seems to have broke on 4.18 probably due to https://github.com/infor-design/enterprise/pull/1936 can you have a look when you get a chance @deep7102

**Comment by brianjuan** [comment]
http://4180-rc0-enterprise.demo.design.infor.com/components/multiselect/test-select-all.html
Passed QA testing on all browsers, moving to Done.
