### ISSUE TITLE
Datagrid: '+' button in grouping header focus is cut off in grouping filter

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2005]
**Describe the bug**
Datagrid '+' button in grouping header focus is cut off in grouping filter

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouping-filter.html
2. Change the Row Height to Short or Medium
3. Click '+' button in group header
*  Notice that the circular focus is cut off

**Expected behavior**

**Version**
v.4.18.0

**Screenshots**
<img width="1301" alt="Screen Shot 2019-04-24 at 6 52 55 PM" src="https://user-images.githubusercontent.com/45757016/56655067-552ac400-66c4-11e9-97c8-5a26168f5718.png">

**Platform**
All browser, OS and devices

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
Note: This is fixed on datagrid-master for texting see https://github.com/infor-design/enterprise/pull/2151#issue-278732527 for details.

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks
Tested in: http://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-filter
