### ISSUE TITLE
Hierarchy tooltip not working 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2008]
**Describe the bug**
Hierarchy tooltip not working 

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/hierarchy/example-index.html
2. Under 'Mary Butler' tree. hover to Katie Olland's Role

**Expected behavior**
Tooltip should show

**Version**
v4.18.0

**Screenshots**
n/a

**Platform**
All OS, Browser & Devices. 

**Additional context**
No  any other context about the problem here.

**Comment by tmcconechy** [comment]
Im going to close this and consolidate this with https://github.com/infor-design/enterprise/issues/1952 we need to make a generic tooltip option that works on any ellipsis text that can be used. As of now its not supporting a tooltip on the hierarchy. Its not a feature of it that it shows a tooltip on the hierarchy but when we add this feature we could do it there too.
