### ISSUE TITLE
Tree Multiselect: Selecting issues on Windows Internet Explorer

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2011]
**Describe the bug**
Tree Multiselect: Selecting issues on Windows Internet Explorer.

**To Reproduce**
1. Open Windows Internet Explorer
2. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/tree/example-select-multiple.html
3. Click the "Leadership" folder multiple times
4. See issue: Child nodes of "Leadership" won't get selected or deselected.
5. Click the folder icon of "Icons" folder or any folder
6. See issue: Folder will not expand or collapse

**Expected behavior**
Child nodes should be selected or deselected when the parent node is clicked. 

**Version**
- ids-enterprise: v4.10.0 - v4.18.0-beta0

**Screenshots**
![tree_multi](https://user-images.githubusercontent.com/39508864/56719150-bd37e380-6772-11e9-94b1-f96edee4c710.gif)

**Platform**
 - OS: Windows
 - Browser: Internet Explorer 11

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Can you reclarify the steps @brianjuan ? Im not clear on this one. As you can click either the checkboxes or the folder and they do different things. For example the folder opens and the checkbox selects so the steps are a bit confusing.

Either way I'm not seeing anything wrong (Just tested Chrome Mac though).

**Comment by brianjuan** [comment]
@tmcconechy this issue only happens on Windows IE. When you click the checkbox of a parent node like the Leadership, it's child nodes are not getting selected. 

And when you try to open a folder like the Icons, it is not being expanded.

**Comment by tmcconechy** [comment]
I see yes there is an error : "SCRIPT5007: Unable to get property 'contains' of undefined or null reference" and its been for several versions past

**Comment by tmcconechy** [comment]
Descoping this issue for now
