### ISSUE TITLE
App Menu personalized background color is black on initial load

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2012]
**Describe the bug**
App Menu background color is black on initial load

**To Reproduce**
1. Go to 
http://4180-beta0-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html
http://4180-beta0-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized.html
http://4180-beta0-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html
2. Change the Personalization color to 'Amber'
3. Switch back to Azure

**Expected behavior**
Default background color should be 'Azure' 

**Version**
v4.18.0

**Screenshots**
<img width="1706" alt="Screen Shot 2019-04-25 at 5 06 58 PM" src="https://user-images.githubusercontent.com/45757016/56724143-fe34f580-677c-11e9-9555-91508caf3502.png">

**Platform**
All Browser, OS and Devices

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
This is the old color of the app menu, so for backwards compatibility it will remain black. But you can opt in to changing the color if you want for example with http://localhost:4000/components/applicationmenu/example-personalized.html?colors=2578A9

So this is not really an iissue.
