### ISSUE TITLE
Dropdown with Colors and Icons: Issues with selections

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2013]
**Describe the bug**
Dropdown with Colors and Icons: Issues with selections.

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/dropdown/example-icons.html
2. Open the "Dropdown with Colors"
3. Select "Turquoise"
4. See issue: "Amethyst" will be selected instead of "Turquoise".
5. Open the "Dropdown with Colors" again, notice that options from "Amethyst" to "Graphite" are highlighted.
5. This issue also applies when you select "Emerald", "Ruby", "Slate" or "Graphite" options, and also when you select by typing in the dropdown.
6. Open the "Dropdown with Icons"
7. Select "Icon with over color"
8. Open the "Dropdown with Icons" again, see issue: both "Icon with over color" options are highlighted

**Expected behavior**
Selections in the dropdown with icons and colors should be correct

**Version**
- ids-enterprise: v4.18.0-beta0

**Screenshots**
![dd_icons](https://user-images.githubusercontent.com/39508864/56725138-e0689000-677e-11e9-8497-7b9777c726d0.gif)

**Platform**
 - All devices, OS, and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
We should just replace this example with the one on http://4180-beta0-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html as that was done after and works and looks better.

**Comment by tmcconechy** [comment]
Closing as there is a pending PR on 4.18.x branch

**Comment by brianjuan** [comment]
Moving to Failed QA due to two reasons:

First, On Windows IE, Dropdown with Colors is not closing when you select a color, and the selected color is not applied to the Header's color.

Second, the issue on Step 7 to 9 is still happening, which is when you select "Icon with over color" on the Dropdown with Icons, then you open the dropdown again, the two "Icon with over color" are highlighted.

**Comment by brianjuan** [comment]
http://4180-rc2-enterprise.demo.design.infor.com/components/dropdown/example-icons.html
Passed QA testing on all browsers, moving to Done.
