### ISSUE TITLE
Dropdown with Placeholder: Selected value is just being appended to the placeholder

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2014]
**Describe the bug**
Dropdown with Placeholder: Selected value is just being appended to the placeholder instead of replacing it.

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/dropdown/example-placeholder.html
2. Open the dropdown
3. Select "California"
4. See issue: Dropdown value is "Select a StateCalifornia"
5. Also occurs on multiselect http://4180-beta0-enterprise.demo.design.infor.com/components/multiselect/example-placeholder.html  (should be using same code path)

**Expected behavior**
The selected value should replace the placeholder

**Version**
- ids-enterprise: v4.18.0-beta0

**Screenshots**
<img width="566" alt="Screen Shot 2019-04-25 at 5 49 51 PM" src="https://user-images.githubusercontent.com/39508864/56727140-a6998880-6782-11e9-86e3-d8dd959a8235.png">

**Platform**
 - All devices, OS, and browsers.

**Additional context**

**Comment by tmcconechy** [comment]
This worked in 4.17 (previous version).

**Comment by brianjuan** [comment]
http://4180-rc0-enterprise.demo.design.infor.com/components/multiselect/example-placeholder.html
http://4180-rc0-enterprise.demo.design.infor.com/components/dropdown/example-placeholder.html
Passed QA testing on all browsers, moving to Done.
