### ISSUE TITLE
Dropdown: Tooltip is not displaying

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2016]
**Describe the bug**
Dropdown: Tooltip is not displaying

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/dropdown/example-tooltips.html
2. Mouse hover on the dropdown
3. See issue: Tooltip is not displaying

**Expected behavior**
The tooltip should be displayed when mouse hovered on the dropdown with long values

**Version**
- ids-enterprise: v4.18.0-beta0

**Screenshots**
No applicable screenshots.

**Platform**
 - All devices, OS, and browsers

**Additional context**
The issue also exists in http://4180-beta0-enterprise.demo.design.infor.com/components/dropdown/test-multiselect-with-tooltip.html

**Comment by janahintal** [comment]
Also in http://4180-beta0-enterprise.demo.design.infor.com/components/multiselect/example-index.html

**Comment by tmcconechy** [comment]
This seems to have regressed in 4.18, we will have to investigate the change that caused this to not work. Maybe #1882 or #404

**Comment by brianjuan** [comment]
http://4180-rc0-enterprise.demo.design.infor.com/components/dropdown/example-tooltips.html
http://4180-rc0-enterprise.demo.design.infor.com/components/dropdown/test-multiselect-with-tooltip.html
http://4180-rc0-enterprise.demo.design.infor.com/components/multiselect/example-index.html
Passed QA testing on all browsers, moving to Done.
