### ISSUE TITLE
Dropdown: X icon is misaligned on Mobile devices

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2018]
**Describe the bug**
Dropdown: X icon is misaligned on Mobile devices.

**To Reproduce**
1. Open browsers in Android and iOS devices
2. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/dropdown/example-index.html
3. Open the dropdown
4. See issue: X icon is misaligned

**Expected behavior**
X icon should be properly aligned

**Version**
- ids-enterprise: v4.18.0-beta0

**Screenshots**
<img width="428" alt="Screen Shot 2019-04-25 at 6 29 45 PM" src="https://user-images.githubusercontent.com/39508864/56729557-270eb800-6788-11e9-8ab7-c5d1e133e3fe.png">

**Platform**
 - Android browsers
 - iOS browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This last worked in 4.15 and is similar to https://github.com/infor-design/enterprise/issues/2021 so those will probably be fixed together. A bit ugly so making it high.

**Comment by brianjuan** [comment]
Hi, the bug fix is working on iOS Safari, iOS Chrome, and Android Firefox. 
But still failing on Android Chrome, will move to Failed QA for now.

http://4180-rc2-enterprise.demo.design.infor.com/components/dropdown/example-index.html
<img width="458" alt="Screen Shot 2019-05-02 at 3 37 04 PM" src="https://user-images.githubusercontent.com/39508864/57061629-2ded7b80-6cf0-11e9-81ab-106704b44a54.png">

http://4180-rc2-enterprise.demo.design.infor.com/components/multiselect/example-index.html
<img width="443" alt="Screen Shot 2019-05-02 at 3 40 15 PM" src="https://user-images.githubusercontent.com/39508864/57061773-bcfa9380-6cf0-11e9-8c92-f33550671802.png">

**Comment by brianjuan** [comment]
http://4180-rc3-enterprise.demo.design.infor.com/components/dropdown/example-index.html
http://4180-rc3-enterprise.demo.design.infor.com/components/multiselect/example-index.html
Bug fix is now working on Android Chrome as well, moving to Done.
