### ISSUE TITLE
Swaplist: Disabled swap button is not visually disabled 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2019]
**Describe the bug**
Swaplist disabled swap button isa not disabled 

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/swaplist/example-disable-dragging.html
2. In the 3rd table, try to swap values and click the swap button in the header
3. Notice that the button displayed as enabled but is disabled.

**Expected behavior**
Swap button should be disabled 

**Version**
v4.18.0

**Screenshots**
<img width="1315" alt="Screen Shot 2019-04-25 at 6 46 49 PM" src="https://user-images.githubusercontent.com/45757016/56730616-fa0fd480-678a-11e9-87ee-76bdc5d7a25b.png">

**Platform**
All browser, OS and devices

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
This seems to have regressed in 4.18 any thoughts @deep7102 as to why? I dont see any issues on swaplist recently

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks!
Verified in: http://4170-enterprise.demo.design.infor.com/components/swaplist/example-disable-dragging.html
