### ISSUE TITLE
Datepicker: Alignment issues on Windows IE

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2020]
**Describe the bug**
Datepicker: Alignment issues on Windows IE.

**To Reproduce**
1. Open Windows Internet Explorer
2. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/datepicker/example-month-year-format.html
and http://4180-beta0-enterprise.demo.design.infor.com/components/datepicker/example-month-year-picker.html
3. Open the date picker
4. See alignment issues

**Expected behavior**
Date picker alignment should be correct

**Version**
- ids-enterprise: v4.11.0 - v4.18.0-beta0

**Screenshots**
http://4180-beta0-enterprise.demo.design.infor.com/components/datepicker/example-month-year-format.html
<img width="712" alt="Screen Shot 2019-04-25 at 7 10 46 PM" src="https://user-images.githubusercontent.com/39508864/56731892-342ea580-678e-11e9-88ac-058c67905665.png">

http://4180-beta0-enterprise.demo.design.infor.com/components/datepicker/example-month-year-picker.html
<img width="525" alt="Screen Shot 2019-04-25 at 7 13 55 PM" src="https://user-images.githubusercontent.com/39508864/56731960-6c35e880-678e-11e9-8735-411b634c8887.png">

**Platform**
 - Windows IE 11

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Checked back to 4.10 and this hasnt worked in quite a while on IE11.
Also not sure how much we care about IE11 anymore as the new Chrome Edge browser is coming soon. (We support R-1) But as of now we do still support IE11.

**Comment by tmcconechy** [comment]
This is no longer an issue as this design has been replaced with something new so the screen shots are no longer valid.
