### ISSUE TITLE
Locale: incorrect time patterns

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#2022]
According to locale definitions here https://github.com/moment/moment/tree/develop/locale
And I have also checked in C#, time pattern for e.g. sl-SI it should be using ':' and not '.'

Raising a question whether there's more mismatch in the locale definitions.

At least these have wrong time pattern
da-DK
pl-PL
pt-BR
sl-SI

**Comment by tmcconechy** [comment]
Our source for this is the CLDR I'm seeing the version i had has some differences on the latest https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/sl/ca-gregorian.json#L323

So will update based on that as a source.

**Comment by guoliang** [comment]
How does that play with csharps CultureInfo?
E.g. I see that in CultureInfo nb-NO short date pattern looks like following "dd.MM.yyyy"
But in CLDR it looks like following "dd.MM.y"
https://github.com/unicode-cldr/cldr-dates-full/blob/1af902b749bef761f07281f80241250053b4313d/main/nb/ca-gregorian.json#L314

**Comment by tmcconechy** [comment]
They say MS uses CLDR http://cldr.unicode.org/#TOC-Who-uses-CLDR- but we did one exception with CLDR and made all years four digit pattern. (Usually) But seems the nb-NO case isnt how i expect https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/nb-NO.js#L18 so i would update that one.

**Comment by guoliang** [comment]
Further question on nb-NO definition, https://github.com/unicode-cldr/cldr-dates-full/blob/1af902b749bef761f07281f80241250053b4313d/main/nb/ca-gregorian.json#L324
`nb-NO` has a `short-alt-variant`, which `sl-SI` does not have. Are you taking that into consideration?

I noticed that on the computer I use, it would recognize the first pattern which is `HH:mm` but not `HH.mm`. So my guess when you update locales, you should priorities `short`  pattern and not the `short-alt-variant`

**Comment by tmcconechy** [comment]
Yeah i would agree that we would take the short pattern from these when i go through it all again.

**Comment by tmcconechy** [comment]
@guoliang i synced this up have a look at https://github.com/infor-design/enterprise/pull/2114

da-DK  -> not changed https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/da/ca-gregorian.json#L320
pl-PL -> changed some 
pt-BR -> changed some 
sl-SI -> changed 

Others corrected.

**Comment by CindyMercadoReyes** [comment]
Keep this ticket in Ready for QA and retest it during Smoke testing.  A minor issue was found on Android mobile. When you open the dropdown list box to set the time the list box appears on the left hand corner of the UI. Please see screen shot attached. 
![bs_realdroid_Mobile_Samsung Galaxy S9-8 0-1440x2960(1)](https://user-images.githubusercontent.com/39101346/57637191-c3063500-7578-11e9-9c75-96957fafc1ba.jpg)

**Comment by tmcconechy** [comment]
That issue you noted is unrelated and is fact a separate issue: https://github.com/infor-design/enterprise/issues/2021 i think this info should go on that ticket instead

**Comment by CindyMercadoReyes** [comment]
Hi, @brianjuan The only way to test this ticket is by conducting regression on 
the datepicker and time picker and then try a few locales to change like can spot check on http://localhost:4000/components/datepicker/example-timeformat.html?locale=bg-BG

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=bg-BG
http://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=sl-SI
http://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=pt-BR
http://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=pl-PL
http://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=da-DK
Passed on all browsers except on Windows IE since the date and time picker is not displayed.

**Comment by tmcconechy** [comment]
As discussed i have a fix in for the IE issues https://github.com/infor-design/enterprise/pull/2186

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
