### ISSUE TITLE
Color picker label is cut off in Extra Small sized input

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2023]
**Describe the bug**
Color picker label is cut off in Extra Small sized input

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/colorpicker/example-sizes.html

**Expected behavior**
Label should not be cut off in Extra Small field with long text value 

**Version**
v.4.18.0

**Screenshots**
<img width="913" alt="Screen Shot 2019-04-25 at 7 38 39 PM" src="https://user-images.githubusercontent.com/45757016/56733310-53c7cd00-6792-11e9-84aa-dca728b866e9.png">

**Platform**
All browser, OS and Devices

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
This probably should go to ellipsis so will keep open for now. But if the text doesnt fit in the dropdown size there is really nothing else that you can do except for pick a bigger size

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. However another minor issue was found. GitHub# https://github.com/infor-design/enterprise/issues/2134
