### ISSUE TITLE
Slider tooltip not being removed after switching to responsive view 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2033]
**Describe the bug**
Slider tooltip not being removed after switching to responsive view 

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/slider/example-index.html
2. Slide to '12'
3. Minimize or maximize the window
 

**Expected behavior**
Tooltip should not get stucked in same place be removed. 

**Version**
v4.13.0 - v4.18.0

**Screenshots**
<img width="656" alt="Screen Shot 2019-04-26 at 1 37 04 PM" src="https://user-images.githubusercontent.com/45757016/56785576-6db3ef00-6828-11e9-8b2c-b1cd7a6ba668.png">

**Platform**
All OS Browsers.

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
Closing as there is a pending PR on 4.18.x branch

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks!
Verified in: http://4180-rc0-enterprise.demo.design.infor.com/components/slider/example-index.html
