### ISSUE TITLE
Tabs: Tab indicator is out of position when hiding a tab

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2034]
**Describe the bug**
Tabs: When on the last tab, the tab indicator gets out of position when hiding a tab.

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/tabs/example-hidden-tabs.html
2. Click "Show Hidden Tabs" button
3. Go to Tab 6
4. Click "Hide Tabs 2 and 5" button
5. See issue: Blue tab indicator gets out of position

**Expected behavior**
Tab indicator position should also be updated when hiding a tab

**Version**
- ids-enterprise:  v4.6.0 - v4.18.0-beta0

**Screenshots**
<img width="981" alt="Screen Shot 2019-04-26 at 3 43 50 PM" src="https://user-images.githubusercontent.com/39508864/56791657-2e8e9980-683a-11e9-8012-835207270def.png">

**Platform**
 - All devices, OS, and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Not a regression, also did not work in 4.15 http://4150-enterprise.demo.design.infor.com/components/tabs/example-hidden-tabs.html

**Comment by tmcconechy** [comment]
Descoping this for now.
