### ISSUE TITLE
Editor:  Default text color or text color 'none' is not working

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2035]
**Describe the bug**
Editor default text color or text color 'none' not working

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/editor/example-index.html
2. Change a text color to 'Orange' 
3. Change again to Text color - 'None' or the default color

**Expected behavior**
Text color should change back to default 

**Version**
beta0 v4.18.0

**Platform**
All browser, OS and devices. 

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
It does work if you change the text to black. But i agree this should work to reset it.
Also would be nice if in the popup the number of rows in the color popup was equal.

**Comment by janahintal** [comment]
QA Passed. This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/editor/example-index.html?theme=uplift&variant=light across all platform.
