### ISSUE TITLE
Popdown misaligned in responsive view 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2036]
**Describe the bug**
Popdown misaligned in responsive view 

**To Reproduce**
1. Go to http://4180-beta0-enterprise.demo.design.infor.com/components/popdown/example-index.html
2. Click My Cart button
3. Minimize the screen to view in responsive view 

**Expected behavior**
Popdown arrow should be aligned 

**Version**
v4.18.0

**Screenshots**
<img width="849" alt="Screen Shot 2019-04-26 at 4 52 19 PM" src="https://user-images.githubusercontent.com/45757016/56797062-6f8cab00-6846-11e9-8c68-c6b83a211ec9.png">

**Platform**
All OS and Browsers. 

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
Somewhat tricky issue as the popdown is a fixed size. Not sure if this is worth fixing so marking minor.

**Comment by tmcconechy** [comment]
Popdown is deprecated since 4.20 in favor of Popover and will be removed in the future. So will not fix any issues with it at this time.
