### ISSUE TITLE
Application Menu: Hamburger No Longer Opens the App Menu

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2040]
**Describe the bug**
Since toolbar changes in 4.18 the app menu wont open in a few examples. This is an NG and EP issue

**To Reproduce**
1. Go to http://localhost:4000/examples/landmark/requisitions-screen.html
2. Click on hamburger
3. Nothing happens

Note: The demo app was just wrong so fixing.

1. Go to http://localhost:4200/
2. Click on hamburger
3. Nothing happens

This needs a fix in EP, so fixing

**Version**

- ids-enterprise v4.18.0

**Additional context**
Started out in MS teams message

**Comment by tmcconechy** [comment]
Closing as there is a pending PR on 4.18.x branch

**Comment by brianjuan** [comment]
http://4180-rc0-enterprise.demo.design.infor.com/examples/landmark/requisitions-screen.html
Passed QA testing on all browsers, moving to Done.
