### ISSUE TITLE
Dropdown: add option for automatic width

### ISSUE THREAD

**Issue by Macke105** [infor-design/enterprise#2051]
**Is your feature request related to a problem? Please describe.**
Dropdowns by default will let the open drowdown grow to the size of its largest data inside it, not respecting the dropdown or parent width. Currently there is a option for settings.maxWidth, but that doesn't really work with dynamic widths..

**Describe the solution you'd like**
An option for dropdown to keep open dropdown width the same as closed dropdown wdith.
And this option should be set to true by default. Setting it to false would allow the dropdown content to grow to its largest data,

**Describe alternatives you've considered**
There are no obvious alternatives.

**Additional context**
open dropdown expands over other inputs.
![dropdown](https://user-images.githubusercontent.com/1390994/56946673-1022e980-6b2b-11e9-9db3-4d4411fb7a25.png)

**Comment by tmcconechy** [comment]
Seems like a good idea to add.

**Comment by tmcconechy** [comment]
Descoping this for now due to performance reasons. But you can set a width and maxWidth to something manual now with that setting. So if you want to explore using that please do
