### ISSUE TITLE
Dropdown: Tooltip with previous selection is displaying on Mobile

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2052]
**Describe the bug**
Dropdown: Tooltip with previous selection is displaying on Mobile.

**To Reproduce**
1. Open browsers in Android and iOS
2. Go to http://4180-rc0-enterprise.demo.design.infor.com/components/multiselect/example-index.html
and http://4180-rc0-enterprise.demo.design.infor.com/components/dropdown/example-index.html
3. Select item in the dropdown
4. Close the dropdown, then open again
5. See issue: Tooltip will show displaying the selection

**Expected behavior**
A tooltip should not display in mobile when not necessary

**Version**
- ids-enterprise: v4.18.0-rc0

**Screenshots**
http://4180-rc0-enterprise.demo.design.infor.com/components/dropdown/example-index.html
<img width="451" alt="Screen Shot 2019-04-30 at 8 10 43 PM" src="https://user-images.githubusercontent.com/39508864/56960639-15605280-6b84-11e9-8507-3991592c88c8.png">

http://4180-rc0-enterprise.demo.design.infor.com/components/multiselect/example-index.html
<img width="465" alt="Screen Shot 2019-04-30 at 8 08 56 PM" src="https://user-images.githubusercontent.com/39508864/56960653-20b37e00-6b84-11e9-887d-bd5b6e41e076.png">

**Platform**
 - Android browsers
 - iOS browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Can possibly fix with https://github.com/infor-design/enterprise/issues/2018

**Comment by brianjuan** [comment]
Not sure if this is because of the fix, but the tooltip on multiselect doesn't disappear even if you interact with another dropdown.

http://4180-rc2-enterprise.demo.design.infor.com/components/multiselect/example-index.html
Android Chrome
<img width="448" alt="Screen Shot 2019-05-02 at 5 00 07 PM" src="https://user-images.githubusercontent.com/39508864/57065687-cee23380-6cfc-11e9-8269-e3d41345c02d.png">

iOS Safari
<img width="450" alt="Screen Shot 2019-05-02 at 5 01 16 PM" src="https://user-images.githubusercontent.com/39508864/57065701-dacdf580-6cfc-11e9-8762-46bd7d76e2dd.png">

**Comment by brianjuan** [comment]
http://4180-rc3-enterprise.demo.design.infor.com/components/dropdown/example-index.html
http://4180-rc3-enterprise.demo.design.infor.com/components/multiselect/example-index.html
Passed QA testing on mobile browsers, moving to Done.
