### ISSUE TITLE
Datagrid: Scrolling does not hide filter dropdowns

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2056]
**Describe the bug**

When scrolling horizontally, the filter dropdowns, if open will not close.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-filter.html
2. Resize the page so you can scroll horizontally
3. Open the activity dropdown in the filter
4. Scroll horizontally again and see error

**Expected behavior**
Dropdowns in header should close on scrolling (both horizontal and vertical)

**Version**
- ids-enterprise: 4.18.0

**Additional context**
Observed in a teams chat

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html. Will retest once beta is deployed.
