### ISSUE TITLE
Personalization: Chart colors aren't updating when switching to the uplift theme

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2058]
**Describe the bug**
When switching to the uplift theme colors in charts are not switching to the uplift color palette colors.

**To Reproduce**
1. Go to http://localhost:4000/components/bar/example-colors.html
2. Note soho colors (which is correct here).
3. Go to http://localhost:4000/components/bar/example-colors.html?theme=uplift
4. Notice colors of chart haven't changed.

**Expected behavior**
Colors for charts should use the themes color palette when switching to uplift.

**Version**
4.19-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/4737815/56976856-829ac600-6b39-11e9-980a-4a42a9c0ab9c.png)

**Platform**
 - PC
 - Window 10
 - Chrome
 - Version 74.0.3729.108 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I think this is a bad example because it has hard coded colors to show you can set the colors.
I thought i tested this and it was working, but trying on http://localhost:4000/components/bar-grouped/example-index.html?theme=uplift it doesnt seem to at the moment.

**Comment by pwpatton** [comment]
It doesn't seem to work on any of our charts. I'll double check them all

**Comment by tmcconechy** [comment]
Its definitely not right, I'll fix.

**Comment by nickwynja** [comment]
Aren't the chart colors a separate palette?

**Comment by tmcconechy** [comment]
No they use the same colors in the pallete and do change across themes (i thought when i did the first PR but this is not working)

**Comment by janahintal** [comment]
Hi @tmcconechy upon testing, I noticed that color in the chart is different from what is displayed in the legend in uplift theme for all charts that has a legend. 
![image](https://user-images.githubusercontent.com/45757016/60083620-a4df4780-9768-11e9-8240-e478e2f2495e.png)

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. 
tested in: https://master-enterprise.demo.design.infor.com/components/bar-stacked/example-index.html?theme=uplift&variant=contrast 
https://master-enterprise.demo.design.infor.com/components/bar-stacked/example-index.html?theme=uplift
