### ISSUE TITLE
Application Menu: Role switcher is not working when the role title is too long

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#2060]
**Describe the bug**
Application role switcher button is not expanding/collapsing the switcher panel area when the role title is too long

**To Reproduce**
1. Changed the application-menu-switcher-trigger button title to a long text.
2. Go to 'http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html'

**Expected behavior**
Trigger button to expand and collapse switcher panel area.

**Version**

- ids-enterprise: 4.18

**Screenshots**
![image](https://user-images.githubusercontent.com/39130590/56977907-ea521080-6b3b-11e9-950a-4b5e5696e70a.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-personalized-role-switcher-long-title.html
Passed QA testing on all browsers, will retest once beta is deployed.
