### ISSUE TITLE
Personalization: When scrolling app menu with new color scheme bottom is left the wrong color

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2062]
**Describe the bug**
application-menu element is not set to the theme personalization color

**To Reproduce**
1. Create full scroll example
2. Scroll down to see non colored part

**Version**

- ids-enterprise: 4.19 dev

**Screenshots**
![image](https://user-images.githubusercontent.com/4737815/56985976-38bcda80-6b4f-11e9-963c-28430a5dc6b1.png)

**Platform**
 - Windows
 - 10
 - chrome
 - Version 74.0.3729.108 (Official Build) (64-bit)

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks!

Verified in http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?colors=206B62 & http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html?colors=80000
in all OS, Browsers and Devices.
