### ISSUE TITLE
Personalization: Add default to personalization picker, and change turquoise color

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2063]
**Describe the bug**
- Need a default color in the personalization color picker.
- For uplift theme change turquoise color to turquoise09

**To Reproduce**
For the default color
1. go to: http://master-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html
2. Select the light theme and pick amber personalization
3. Switch to dark theme and notice the amber color stays.

**Expected behavior**
Need an option for a default color for the theme for dark and high-contrast

**Version**

- ids-enterprise: 4.19 dev

**Screenshots**
![image](https://user-images.githubusercontent.com/4737815/56986234-db755900-6b4f-11e9-9148-4c8c39ba2771.png)

**Platform**
- Windows
- 10
- chrome
- Version 74.0.3729.108 (Official Build) (64-bit)

**Comment by pwpatton** [comment]
This might not be an issue with the EP sample I'm not sure. But it is an issue for our app forsure.

**Comment by janahintal** [comment]
Hi @tmcconechy , upon testing in http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html#

In Safari Mojave OS, the app menu color is wrong when switched to different color. Notice that there is a black row in the app menu. 
<img width="1476" alt="Screen Shot 2019-05-08 at 1 28 57 PM" src="https://user-images.githubusercontent.com/45757016/57351823-dccd0400-7195-11e9-9c8c-2670f197daac.png">
