### ISSUE TITLE
Update to Protractor 6.0.0

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2065]
**Is your feature request related to a problem? Please describe.**

Should try to update to protractor 6.0.0 once stable. Its having a few issues at the moment like:
angular/webdriver-manager#376 (comment)
angular/protractor#5225

**Describe the solution you'd like**

- [ ] Update to a 6.X current version of protractor
- [ ] Adjust for any breaking changes https://github.com/angular/protractor/blob/master/CHANGELOG.md#breaking-changes
- [ ] Test `npm run e2e:ci:debug` without the need for a fixed chrome version https://github.com/infor-design/enterprise/pull/2064/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R58 and remove

**Describe alternatives you've considered**
NA

**Additional context**
https://github.com/infor-design/enterprise/pull/2064/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R58

**Comment by cnishina** [comment]
I would hold off on Protractor 6. As a first step, I would try to update your tests to get everything on async / await. An example of this is something like:

https://github.com/angular/protractor/blob/master/spec/basic/locators_spec.js#L6-L17

To get async / await working in  your Protractor config in version 5, you will have to add `SELENIUM_PROMISE_MANAGER: false`. See https://github.com/angular/protractor/blob/master/spec/basicConf.js#L6. Basically this will turn off the control flow.

**Comment by tmcconechy** [comment]
Thanks @cnishina i think our tests might be ok already, but i cant get it to run yet, because of this: https://github.com/infor-design/enterprise/pull/2064#issuecomment-488093436

We already use those concepts...
Awaits (in most places i think) : https://github.com/infor-design/enterprise/tree/master/test/components
And SELENIUM_PROMISE_MANAGER :  https://github.com/infor-design/enterprise/blob/master/test/protractor.ci.conf.js#L14

Probably we'll wait a bit and try this out again soon.

**Comment by cnishina** [comment]
Oh neat. I didn't review your code but I'm glad you are doing it. I would hold off using Protractor 6. Also using webdriver-manager 12.1.4 will install two versions of webdriver-manager and that might not work since the files are downloaded locally. I'll have a 6.0.1-beta.1 version out soon and I'll ping you when I'm done with the release.

**Comment by tmcconechy** [comment]
Closing this for now. Seems like 6.0.0 is still not ready.
