### ISSUE TITLE
ApplicationMenu: Allow a search field on application menu that has custom logic

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#2066]
**Describe the bug**
Need to show search field when application menu filterable setting is false. Currently, the search field will be hidden. 

**To Reproduce**
1. Go to http://localhost:4000/components/applicationmenu/example-filterable.html

**Expected behavior**
Need the search field on application menu to show up even when 'filterable' setting is 'false' to insert custom search logic vs. the header search controlled by the application menu.

**Version**

- ids-enterprise: 4.18

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 73.0.3683.103 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Im not totally clear on this issue. Why can we not just set `filterable: true` if that works and you want filtering. I don't think it makes sense to filter when the setting is turned off, otherwise whats the point of having a setting? @pwpatton ?

**Comment by pwpatton** [comment]
@tmcconechy It was the option we were using to interrupt the default searching and run a back end search and present results in our own panel.

**Comment by pwpatton** [comment]
Perhaps another option name would be better like `disableClientSideFilter` or something like we do in  datagrid.

**Comment by tmcconechy** [comment]
OK so you mean you want to just put a search field in there but its not going to control the app menu? Your just searching something else?

**Comment by pwpatton** [comment]
yes

**Comment by brianjuan** [comment]
Passed on other browsers but on Windows IE, the toast is not showing up 
http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-filterable-custom.html

**Comment by tmcconechy** [comment]
The example just is using the change event on the search and that only fires in IE when you leave the field so you have to click out. Basically this example is just doing "nothing" which was the point of it so i cant add any special code to make that work. The end developer would do what they want here. So im going to skip that point is its really not important.

**Comment by brianjuan** [comment]
Noted on that @tmcconechy , verified working on IE. Moving to Done and will retest on beta.
