### ISSUE TITLE
RTL:  Wrong position of Hour and Minute dropdowns in timepicker

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#2068]
**Describe the bug**
In Timepicker component when using RTL, the position of Hour dropdown is aligned to right and Minutes to the left - so it looks like mm:HH format.

**To Reproduce**
1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/timepicker/test-24-hour?locale=he-IL](https://design.infor.com/code/ids-enterprise/latest/demo/components/timepicker/test-24-hour?locale=he-IL)
2. Click on Clock icon
3. See error

**Expected behavior**
In RTL like LTR, the format is hh:mm (or HH:mm), but always hours first.

**Version**
- ids-enterprise: v4.17.1

**Screenshots**

**Platform**
 - OS Version: Windows 7 
 - Browser Name Chrome

**Additional context**
Thanks!

**Comment by tmcconechy** [comment]
Also the dropdown is opening in the wrong position and there is an extra border near the button.
