### ISSUE TITLE
Datagrid: Filtering Makes Two Ajax Calls

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2069]
**Describe the bug**

When doing a filter on datagrid with server side data the ajax call (source function) is executed twice. This can be a big problem if the calls are intensive.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/test-filter-paging-server-side.html
2. Set a debug point in the source function on the example source.
3. Filter on id contains 20 or any filter
4. This runs twice.

**Expected behavior**
Should only run once.

**Version**
- ids-enterprise: [e.g. v4.18.0]

**Additional context**
Found by automative team.

**Comment by brianjuan** [comment]
http://4180-rc3-enterprise.demo.design.infor.com/components/datagrid/test-filter-paging-server-side.html
Passed QA testing across all browsers, moving to Done.
