### ISSUE TITLE
Datagrid: Arrows misaligned and minor issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2073]
**Describe the bug**
While testing found and fixed a few things i spotted.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/test-filter-disabled.html
2. Notice that the dropdown borders are a darker disabled color
3. Go to http://localhost:4000/components/datagrid/test-fixed-header-short-row-filter.html
4. Try and drag the headers to sort
5. Look at the arrows on the top and bottom of the header -> they don't align right

This happened when making alignment changes this version

**Expected behavior**
Arrows align and text is correct color.

**Version**
- ids-enterprise: [e.g. v4.1.8.0]

**Screenshots**
Not possible for the drag issue.

**Comment by janahintal** [comment]
Hi @tmcconechy, tested both links in rc3 build. Noticed that the dropdown borders are still inconsistent in iOS devices. Please see image below. Thank you!

<img width="1122" alt="Screen Shot 2019-05-03 at 3 58 34 PM" src="https://user-images.githubusercontent.com/45757016/57129765-0539b480-6dca-11e9-952f-d861cb8b17f4.png">

**Comment by tmcconechy** [comment]
Let’s just move this in the backlog again and fix next time. It shouldn’t hold up a release I think.
