### ISSUE TITLE
Support custom scroll bar in specific contexts

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#2074]
**Is your feature request related to a problem? Please describe.**
There are certain contexts like widget cards and data grids where overflow of content is standard and expected. In Windows browsers, there are often chunky scroll bars which both steal real estate and make the application style look very clunky.

**Describe the solution you'd like**
Global override of scroll bar styling is still not consistently supported across browsers. Doing a global style override scares me. I'd like to propose targeting custom scroll bar styles to some specific contexts like grid and widget overflow to start testing out the waters of custom scrollbars. This does introduce inconsistency across the styles scroll bar in different places within the application but the pay off might be worth it. This could also be specific to the Uplift theme, and not tough the existing styles in Soho.

**Describe alternatives you've considered**
Staying very far away from this.

**Additional context**
![Screen Shot 2019-05-01 at 3 02 11 PM](https://user-images.githubusercontent.com/1012017/57036380-1e9ffc80-6c22-11e9-98f2-40ca086fa13e.png)

![Screen Shot 2019-05-01 at 2 52 06 PM](https://user-images.githubusercontent.com/1012017/57036334-0334f180-6c22-11e9-9464-9e1450388977.png)

**Comment by tmcconechy** [comment]
This was a bug when we changed colors. We had some custom scrollbars in place. So fixing them that means that we did implement scrollbars for this case and this issue is no longer needed.

https://github.com/infor-design/enterprise/issues/3413
