### ISSUE TITLE
Toolbar: A toolbar with a searchfield in a list details div text is same color as searchfield

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2075]
**Describe the bug**
The text color matches the searchfield's color, so you can't read it. This is happening for a searchfield in a toolbar in a list details area. Also, the clear button is over the magnifiying glass button when there is a value in the searchfield, but it's collapsed.

**To Reproduce**
1. Copy [list-detail.zip](https://github.com/infor-design/enterprise/files/3135802/list-detail.zip) into your codebase, and navigate to it.
1. (TJM) On branch http://localhost:4000/patterns/list-detail.html i put it
2. Click into the toolbar search field (the magnifying glass icon) and start typing
3. See error

**Expected behavior**
Need to be able to see what is being typed.

**Version**
v4.19.0-dev

**Screenshots**
![SearchFieldTextIssue](https://user-images.githubusercontent.com/22107636/57038566-d8499e00-6c1f-11e9-881e-66225e182ea1.gif)

**Platform**
 - All

**Comment by tmcconechy** [comment]
Additionally.
- the placeholder text is the same color as the text
- when search is collapsed and you hover an x appears when it shouldnt

**Comment by tmcconechy** [comment]
Wondering if this worked before or is a new combination? Just wondering if we broke something

**Comment by Sovia** [comment]
I feel like it was working in the landmark case before. I'm just not sure when. It looks like a rule in [_list-detail.scss](https://github.com/infor-design/enterprise/blob/master/src/patterns/list-detail/_list-detail.scss#L137) is what is setting the current color to transparent.

**Comment by clepore** [comment]
Very very interesting. So something was probably done to "unmask" this and it's very odd that at one point we set the `color: transparent`. Honestly I think we can remove that whole selector in our codebase, but we'll investigate.

**Comment by EdwardCoyle** [comment]
Was able to remove [this whole snippet](https://github.com/infor-design/enterprise/blame/master/src/patterns/list-detail/_list-detail.scss#L132-L153), and it seems like that was the culprit

**Comment by janahintal** [comment]
The text color is now different as the search field however, The text color is the same with placeholder & when search is collapsed and you hover an x appears when it shouldn't.
Verified in: http://4180-rc2-enterprise.demo.design.infor.com/patterns/list-detail.html

**Comment by janahintal** [comment]
Hi @tmcconechy, Already tested in all OS browsers and noticed that the placeholder is not showing in Windows10 IE11 browser. 
Will move to QA failed. Thank you.

**Comment by clepore** [comment]
@EdwardCoyle since we have this working in most browsers, let's split @janahintal 's latest finding as a separate issue (for `4.19` sprint) so we can release `4.18.0`.

**Comment by EdwardCoyle** [comment]
Raised #2093 for that one
