### ISSUE TITLE
Datagrid: Chart hover displays empty tooltip

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#2079]
**Describe the bug**
On hover of a chart in a datagrid cell at this URL: /components/datagrid/test-targeted-achievement.html, an empty tooltip is displayed.

"It should not display empty tooltip (see middle columns `With Alert Colors, To a Target`)"
  - _Originally posted by @deep7102 in https://github.com/infor-design/enterprise/pull/2049#issuecomment-488306457_

**To Reproduce**
- Visit /components/datagrid/test-targeted-achievement.html
- Hover over a chart without text
  - Notice there is an empty tooltip displayed

**Expected behavior**
No tooltip should appear.

**Version**
4.19.0

**Screenshots**
<img width="778" alt="empty-tooltip" src="https://user-images.githubusercontent.com/7952168/57070569-e510d500-6ca5-11e9-920a-49659857b459.png">

**Platform**
Mac OS 10.14.4
Chrome Version 73.0.3683.103 (Official Build) (64-bit)

**Additional context**
It was suggested in the PR where this bug was found that an audible span might resolve the issue:
https://github.com/infor-design/enterprise/pull/2049#issuecomment-488370551

**Comment by tmcconechy** [comment]
I think it would be better than not showing a tooltip, to show the value. I think adding in an audible span with the value it might pick it up in the tooltip.

**Comment by tmcconechy** [comment]
This issue can no longer be reproduced. I know i fixed this at some stage but cant find the duplicate issue. Testing http://master-enterprise.demo.design.infor.com/components/datagrid/test-targeted-achievement you will see hovering will now show a value and not an empty tooltip.
