### ISSUE TITLE
Pager: Selected item gets deselected when changing a page

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2080]
**Describe the bug**
Pager: Selected item gets deselected when changing a page.

**To Reproduce**
1. Go to http://4180-rc2-enterprise.demo.design.infor.com/components/pager/example-index.html
2. Select "Item Three"
3. Go to Page 2
4. Go back to Page 1
5. See issue: "Item Three" is now deselected

**Expected behavior**
Selected item should stay selected even after changing pages

**Version**
- ids-enterprise: v4.17.0 - v4.18.0-rc2

**Screenshots**
No screenshot applicable.

**Platform**
 - All devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This did work in 4.15 before the changes to the pager. It's not necessarily expected behavior i think, but since it did work someone might notice this so keeping it open. Can increase priority if any teams actually require this.

**Comment by brianjuan** [comment]
Will take note of this. Thanks @tmcconechy!

**Comment by tmcconechy** [comment]
Descoping this for now
