### ISSUE TITLE
Datagrid: Export doesn't work on Windows IE

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2081]
**Describe the bug**
Datagrid: Export doesn't work on Windows IE.

**To Reproduce**
1. Open Windows Internet Explorer 11
2. Go to http://4180-rc2-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html
3. Click "Export To Csv" and "Export To Excel"
4. See issue: Files are not being downloaded

**Expected behavior**
Datagrid exporting should work on Windows IE

**Version**
- ids-enterprise: v4.17.0 - v4.18.0-rc2

**Screenshots**
No applicable screenshots.

**Platform**
 - OS: Windows 10 or lower
 - Browser: Internet Explorer 11

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This broke in 4.17 but im going to push a fix.

**Comment by brianjuan** [comment]
http://4180-rc3-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html
Passed QA testing, moving to Done.
