### ISSUE TITLE
Dropdown: Character appears when arrows left and right are pressed.

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2082]
**Describe the bug**
Dropdown: Character appears when arrows left and right are pressed.

**To Reproduce**
1. Go to http://4180-rc2-enterprise.demo.design.infor.com/components/dropdown/example-index.html
2. Tab to dropdown
3. Press Right Arrow key
4. See issue: ' will appear on the dropdown
5. Tab to dropdown again
6. Press Left Arrow key
7. See issue: % will appear on the dropdown

**Expected behavior**
Characters should not appear when arrows left and right are pressed.

**Version**
- ids-enterprise: v4.9.0 or v4.18.0-rc2

**Screenshots**
No applicable screenshots.

**Platform**
 - OS: Windows and Mac
 - Browsers: Chrome, Safari, Firefox, Edge, and IE

**Additional context**
The issue also applies to multiselect dropdowns.

**Comment by brianjuan** [comment]
On Safari and IE, a dot appears when delete key is pressed.

**Comment by tmcconechy** [comment]
Descoping for now
