### ISSUE TITLE
Kitchen-sink: Profile menu doesn't open on stacked Hierarchy

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2084]
**Describe the bug**
Kitchen-sink: Profile menu doesn't open on stacked Hierarchy.

**To Reproduce**
1. Go to http://4180-rc2-enterprise.demo.design.infor.com/
2. Scroll down to the Hierarchy (Stacked ) section
3. Click the ... menu of John Randolph and Barb Wire
4. See issue: Menu doesn't open
5. Additionally, legends are positioned way to the left of the page

**Expected behavior**
Profile menu should open on stacked hierarchy

**Version**
- ids-enterprise: v4.18.0

**Screenshots**
No applicable screenshot.

**Platform**
 - All devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by brianjuan** [comment]
Will take note of this, thanks.

**Comment by tmcconechy** [comment]
Descoping this issue for now
