### ISSUE TITLE
Datagrid: dirtyRow doesn't include rows and cells whose status changed via rowStatus

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2091]
Describe the bug
In Landmark, the values of a datagrid maybe updated externally.  For example, a cell contains a button that when clicks opens a model dialog.  The user updates field values and those values are to be reflected in the row.  Fields may or may not have a visible cell to show the updated value. 

1. Using the attached example-change-cell-externally.html
2. Click on the 'Change Cell' toolbar button
3. Notice in the displayed alert that the dirty row count doesn't reflect the row that is 'in-progress'

Expected behavior
Expect that rows and cells whose status has been set to 'in-progress' or 'error' via the  rowStatus method should be included.  Similar to how it worked in 3.5 in inforControlsCombined.js via getDirtyRows.

Additionally need a method to setDirtyCell to visually show that a cell has been updated externally via updateRow method.

**Comment by claudenbach** [comment]
[Git-2091.zip](https://github.com/infor-design/enterprise/files/3139707/Git-2091.zip)

**Comment by tmcconechy** [comment]
Note: Fixed this on datagrid-master branch for review see https://github.com/infor-design/enterprise/pull/2145 (comment) for further testing details.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/test-dirty-change-cell-externally.html
http://master-enterprise.demo.design.infor.com/components/datagrid/test-dirty-indication.html
Programmatically changed dirty indicator is removed when you change the datagrid page.
Also, the datagrids are not loaded in Windows IE.

**Comment by janahintal** [comment]
QA Passed. Dirty Indicator is not removed after changing data grid page, also the grid is now loading in windows IE11. Thanks. 
Verified in: http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/test-dirty-change-cell-externally.html
http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/test-dirty-indication.html
