### ISSUE TITLE
Homepages: Text Color is too dark on the hero

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2097]
**Describe the bug**
Noticed the text color isnt changing correctly on home page her widgets: http://master-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html
2. Examine the text in the hero area.

**Expected behavior**
Text is legible and changes based on the personalization colors. Can possible use the new text color classes http://master-enterprise.demo.design.infor.com/components/personalize/example-classes.html

**Version**
- ids-enterprise: v4.18.0

**Comment by janahintal** [comment]
Hi @tmcconechy, some colors are still not readable in High Contrast mode. Also the legend is different from what is displayed in the chart. 
http://master-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html?colors=#56932e
http://master-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html?colors=#db7726

<img width="1417" alt="Screen Shot 2019-06-24 at 7 04 51 PM" src="https://user-images.githubusercontent.com/45757016/60014584-e95cdb80-96b3-11e9-865f-57474ece7151.png">

**Comment by tmcconechy** [comment]
@janahintal @deep7102 Im not sure that we can ensure this works on every single color some of the lightest colors will not be workable. But this is a user preference so they can just pick a different color.

But i think that the tooltip is an issue worth fixing as it seems to show the wrong colors.

**Comment by tmcconechy** [comment]
@deep7102 To fix this you can update the scripts to use the theme colors like this with `var palette = Soho.theme.themeColors().palette;`. You may need to play with the colors and see what looks good across most the themes and colors.

```
<script>
  var palette = Soho.theme.themeColors().palette;
  var donutData = [{
    data: [
      {name: 'Positive', value: 20, color: 'good'},
      {name: 'Negative', value: 25, color: 'error'},
      { name: 'Neutral', value: 10, color: 'neutral'}
    ],
    centerLabel: 'Reviews'
  }];

  var barData = [{
        data: [
          {name: 'Jan', value: 12, color: 'alertYellow'},
          {name: 'Feb', value: 11, color: 'good'},
          {name: 'Mar', value: -5, color: 'error'},
          {name: 'Apr', value: 10, color: palette.azure['30'].value},
          {name: 'May', value: 14, color: palette.ruby['30'].value}
        ],
        name: 'Team A'
      }, {
        data: [
          {name: 'Jan', value: 22, color: 'alertYellow'},
          {name: 'Feb', value: 24, color: 'good'},
          {name: 'Mar', value: 12, color: 'error'},
          {name: 'Apr', value: 20, color: palette.azure['30'].value},
          {name: 'May', value: 21, color: palette.ruby['30'].value}
        ],
        name: 'Team B'
      }, {
        data: [
          {name: 'Jan', value: 32, color: 'alertYellow'},
          {name: 'Feb', value: 31, color: 'good'},
          {name: 'Mar', value: 34, color: 'error'},
          {name: 'Apr', value: 30, color: palette.azure['30'].value},
          {name: 'May', value: 33, color: palette.ruby['30'].value}
        ],
        name: 'Team C'
      }];

  var areaData = [{
    data: [
      {name: 'Jan', value: 12}, {name: 'Feb', value: 11}, {name: 'Mar', value: 14},
      {name: 'Apr', value: 10}, {name: 'May', value: 14}, {name: 'Jun', value: 8}],
    name: 'Metals', color: '#ede3fc'
  }, {
    data: [
      {name: 'Jan', value: 22}, {name: 'Feb', value: 21}, {name: 'Mar', value: 24},
      {name: 'Apr', value: 20}, {name: 'May', value: 24}, {name: 'Jun', value: 28}],
    name: 'Stone', color: 'alertYellow'
  }, {
    data: [
      {name: 'Jan', value: 32}, {name: 'Feb', value: 31}, {name: 'Mar', value: 34},
      {name: 'Apr', value: 30}, {name: 'May', value: 34}, {name: 'Jun', value: 38}],
    name: 'Wood', color: 'error'
  }];

  $('#donut-alert1').chart({type: 'donut', dataset: donutData});
  $('#bar-grouped-example').chart({type: 'bar-grouped', dataset: barData, showLegend: false});
  $('#area-example').chart({type: 'area',
        dataset: areaData});


  // Wait for initialize
  $('body').on('initialized', function() {
    var homepageApi = $('.homepage').data('homepage');
    var circlepagerApi = $('.circlepager').data('circlepager');

    // Set view type
    var setView = function(numberOfColumns) {
      if (numberOfColumns > 2) {
        circlepagerApi.showExpandedView();
      } else {
        circlepagerApi.showCollapsedView();
      }
    };

    // Bind resize
    homepageApi.element.on('resize', function(e, numberOfColumns) {
      setView(numberOfColumns);
    });


    // Init
    setView(homepageApi.settings.columns);
  });
</script>
```

**Comment by janahintal** [comment]
Hi @tmcconechy, upon checking in http://master-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html?theme=soho&variant=dark&colors=50535a when I hover again in the bar, the tooltip doesnt show up.

**Comment by janahintal** [comment]
QA Passed.  Moving to Done. 
Thanks. 
Tested in: http://master-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html?theme=uplift&variant=contrast&colors=56932e across all OS, browser and devices.
