### ISSUE TITLE
RTL: Fileupload in Modal doesn't look good in RTL

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#2098]
**Describe the bug**
When using a fileupload in a modal the folder icon appears under the name instead of to the left in the field and x icon is missing after you have selected a file. This is reproducible in the latest IDS.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/modal/test-fileupload.html?locale=ar-SA 
2. Click on "Show Modal"
3. Click the Folder icon
4. Select a File and click Open
5. See Error

**Expected behavior**
Folder should be to the left as in example: https://design.infor.com/code/ids-enterprise/latest/demo/components/fileupload/example-index.html?locale=ar-SA

**Version**
4.17

**Screenshots**
Actual Result: 
![image](https://user-images.githubusercontent.com/8664975/57230826-80dd7080-7019-11e9-8c39-5ae4d60d7f4d.png)

Expected result (from not in Modal):
![image](https://user-images.githubusercontent.com/8664975/57230857-9488d700-7019-11e9-8043-bebc4755ef10.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 74.0.3729.108 (Official Build) (64-bit)

**Additional context**
-

**Comment by janahintal** [comment]
QA Passed. Will move to Done
Verified in: http://4190-beta0-enterprise.demo.design.infor.com/components/modal/test-fileupload.html?locale=ar-SA across all browser, OS and devices.
