### ISSUE TITLE
Notification: Improve animation

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2099]
**Describe the bug**
Not apparent in the demo app for EP but noticeable the way its done in NG. The animation could be improved since the icon is `position: absolute`

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/notification
2. Click on the button to show repeatedly
3. Notice the icon lags positioning in the animation

**Expected behavior**
Icon should move with the notification. Either make it animate on its own along with it or make it not positioned absolute and still position correctly

**Version**
- ids-enterprise 4.18.0

**Comment by jbrcna** [comment]
**QA Passed**
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/notification/example-index.html
