### ISSUE TITLE
FieldOptions: Border misaligned

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2107]
**Describe the bug**
The border is a pixel off.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/field-options/example-index.html
2. Click in the first field
3. See error

**Expected behavior**
Expect the options border to be up a piXel

**Version**
- ids-enterprise:  v4.18.x

**Platform**
 - Browser Name [chrome]

**Additional context**
Seems to work to add `top: -1px` but all browsers should be tested for the best solution

**Comment by clepore** [comment]
Similar to #1862

**Comment by CindyMercadoReyes** [comment]
This ticket failed QA. Everything is now aligned for the spin box. However, when I click on the "+" or "-" it increase the number by two instead of increasing the number by one each time I click on the add or minus button.  This is occurring on Win 10 Edge 18.  @deep7102 @tmcconechy

**Comment by tmcconechy** [comment]
i only see this sometimes. I also noticed @deep7102 that the spinbox's ... menu next to the field has an invisible icon on IE11

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. Thanks
Spinner and border is now working as expected. 
Tested in:
http://4190-beta0-enterprise.demo.design.infor.com/components/field-options/example-index.html
http://4190-beta0-enterprise.demo.design.infor.com/components/spinbox/example-index.html
