### ISSUE TITLE
Random saved.shift is not a function error

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2109]
**Describe the bug**
Seeing a rogue error in some situations.  Steps are not clear but was seeing it very consistently on this branch https://github.com/infor-design/enterprise/pull/2108

Error: `saved.shift is not a function`
Documented here https://github.com/jquery/jquery/issues/4350

**To Reproduce (sometimes)**

1. Go to http://localhost:4000/components/applicationmenu/example-personalized-role-switcher.html# (with the hash)
3. Try and pick colors

**Expected behavior**
No error

**Version**
- ids-enterprise: [v4.18.0]

**Platform**
 - Browser Name [e.g. chrome]

**Comment by brianjuan** [comment]
Hi @tmcconechy, I am trying to replicate the issue, but I cannot see any error on both http://4180-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html# and http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html#

Maybe it's intermittent?

**Comment by tmcconechy** [comment]
Yes it is. It was only possible to see it a few times debugging. I wouldn’t worry about it and trust it’s fixed since it’s well noted on the joinery package link

**Comment by brianjuan** [comment]
Thanks Tim! Will now move this to Done and will retest once beta is deployed.
