### ISSUE TITLE
[builder pattern] purpose of the hamburger icon on larger devices.

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2115]
**Is your feature request related to a problem? Please describe.**
The following example layout shows a hamburger icon, when page is not on an extra small device, as then it changes to the back button icon and it is then clear on what it is used for.
http://master-enterprise.demo.design.infor.com/patterns/builder-subtitle-test.html

**Describe the solution you'd like**
Should the example hide the icon on larger devices?
eg. by adding the following classes 
visible-sm hidden-md hidden-lg hidden-xl

**Additional context**
Example of this were the left hamburger loads the application menu.
![image](https://user-images.githubusercontent.com/39749678/57349325-d2603980-7198-11e9-90ae-d83171d50e94.png)
We have used the styles locally, so the icon with no function is not displayed to larger devices.
![image](https://user-images.githubusercontent.com/39749678/57349422-31be4980-7199-11e9-90ef-25feb71619ea.png)

**Comment by tmcconechy** [comment]
@EdwardCoyle I saw this too in some examples I was working on. This might be a good one to pick up when you have capability

**Comment by brianjuan** [comment]
Passed QA, tested all builder pages in http://localhost:4000/patterns/list across all browsers. Will retest once beta is deployed.
