### ISSUE TITLE
Applicationmenu: infor logo overlap on a larger menu

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2116]
**Describe the bug**
If there is a menu longer that the screen the Infor icon will be placed within the menu instead of the bottom.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html'
2. Make the screen small so that there is an overflow
3. Scroll up and down
5. Or just go to https://design.infor.com/code/ids-enterprise/latest/demo/components/applicationmenu/test-filterable-many-items.html

**Expected behavior**
The icon should be placed at the bottom of the menu even if the menu is long or short.

**Version**
v4.18.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/57349772-7bf3fa80-719a-11e9-8f08-d794bd2b8646.png)

**Comment by marknolaninfor** [comment]
@tmcconechy 
We have corrected our menu by using the footer 

  <div class="application-menu-footer">
    <div class="branding">
      <svg class="icon" viewBox="0 0 34 34" focusable="false" aria-hidden="true" role="presentation">
        <use xlink:href="#icon-logo"></use>
      </svg>
    </div>
  </div>

![image](https://user-images.githubusercontent.com/39749678/57589110-44040300-755e-11e9-9a34-f05d31e14cde.png)

**Comment by clepore** [comment]
Workaround approved 👍

**Comment by tmcconechy** [comment]
I think we should reopen this as the example noted on https://teams.microsoft.com/l/message/19:6d4c9079385840c0bc61e55bcdd16a33@thread.skype/1557850861892?groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35

Is more obvious then I first expected here

**Comment by tmcconechy** [comment]
Cc @EdwardCoyle I’m wondering what broke this maybe an accordion change? Maybe we can track this down tomorrow.

To reproduce see https://design.infor.com/code/ids-enterprise/latest/demo/components/applicationmenu/test-filterable-many-items.html

And just scroll around...

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
