### ISSUE TITLE
Datagrid: Pagination Label moves to its Left when "Records per page" is changed 

### ISSUE THREAD

**Issue by jeffuycoque** [infor-design/enterprise#2117]
**Describe the bug**
Pagination Label for the Datagrid control moves to the left when the "records per page" is changed to double digits (Example: from 5 pages to 10 pages).

**To Reproduce**

1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html

2. Reduce the number of records to 5. The example has 7 records so we should delete 2 rows.

3. Change the "records per page" from 5 pages to 75 pages.

4. The pagination label will move to its left.

Please see attached zip file for the video of the steps to reproduce.
[Datagrid_Pagination Label.zip](https://github.com/infor-design/enterprise/files/3155714/Datagrid_Pagination.Label.zip)

**Platform**

OS Version: Windows 10
Browser Name: Google Chrome

**Comment by tmcconechy** [comment]
Cant seem to see this anymore. So descoping this for now

**Comment by sharmainerivera** [comment]
Hi, Tim. This issue can still be replicated on version 4.31.0-dev. The pagination below the datagrid still moves to the left when Records per Page was changed. Please see screen capture below. 
![9e744449-2d39-481a-8f54-bb2b51027853](https://user-images.githubusercontent.com/61222084/88379408-78678600-cdd5-11ea-96b1-ea0905d55e5f.gif)

**Comment by tmcconechy** [comment]
Ok i was looking at the wrong text. This might be fixable but the reason its doing it is all the same elements are on the pager and the text (75 vs 2) is longer so it bumps it over.

Would have to make the right text position: absolute.

This seems super minor
