### ISSUE TITLE
Required asterisks no longer appearing

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#2118]
**Description**
A recent change to the required asterisk strategy has caused all our asterisks to disappear. They used to be an ::after pseudo element to the label.required element (CSS solution), but are now inserted by DOM selector when sohoxi.js script is loaded (one-time DOM manipulation solution).
The new solution will not work for _any_ dynamic HTML that is rendered after the sohoxi initialization (which for us is the complete Angular application)

This is the change introduced in v4.18.0:
https://github.com/infor-design/enterprise/pull/1877/files#diff-ce2b1986d94d1af0464dc730fd2bbe29L100

**Expected behavior**
CSS solution for required asterisk kept in place,

**Version**
- ids-enterprise: v4.18.0

**Comment by EdwardCoyle** [comment]
@tmcconechy Simply adding back the `::after` actually causes an issue in the new, accessibility-friendly markup:

![Screen Shot 2019-05-08 at 10 51 21 AM](https://user-images.githubusercontent.com/3249601/57385668-dbdda780-7180-11e9-8f26-7c5df8d57bb9.png)

To counteract this, when using the accessibility-friendly markup, we need an additional CSS class on the element containing the text (either the `<label>` directly, or the `.label-text` element).  I was thinking we'd just call it `.accessible`, or something like that?

**Comment by EdwardCoyle** [comment]
@tmcconechy Simply adding back the `::after` actually causes an issue in the new, accessibility-friendly markup:

![Screen Shot 2019-05-08 at 10 51 21 AM](https://user-images.githubusercontent.com/3249601/57385668-dbdda780-7180-11e9-8f26-7c5df8d57bb9.png)

To counteract this, when using the accessibility-friendly markup, we need an additional CSS class on the element containing the text (either the `<label>` directly, or the `.label-text` element).  I was thinking we'd just call it `.accessible`, or something like that?

**Comment by tmcconechy** [comment]
Maybe `required-accessible`? Kind of a bummer.

**Comment by EdwardCoyle** [comment]
Not sure why this didn't close, closing now.
