### ISSUE TITLE
Datagrid: Lookup filter long text overflows trigger icon

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2122]
**Describe the bug**
If there is a lookup filtertype in a datagrid, if the value is long it overflows into the lookup trigger icon.

**To Reproduce**
1. Copy [test-filter-lookup-click-function.zip](https://github.com/infor-design/enterprise/files/3158627/test-filter-lookup-click-function.zip)
 into your codebase in /app/views/components/datagrid and navigate to it
2. Click on the lookup filter trigger for Product Name
3. Choose 'I Love Compressors'

**Expected behavior**
The text shouldn't overflow the icon.

**Version**
- v.4.19.0-dev and earlier

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/57395290-56142900-718d-11e9-8e49-74a46996e80d.png)

**Platform**
All

**Comment by janahintal** [comment]
Failed QA. Ellipsis is not showing in WIn10 IE11
Tested in: https://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-lookup-click-function across all browsers. Thanks

**Comment by tmcconechy** [comment]
@janahintal this cannot be fixed as there is a bug in IE 11 https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15550368/

Please verify otherwise without this fix and then move to done if all else is done.

**Comment by janahintal** [comment]
Will move this to Done. Working in all browser except IE11 for some limitations.
