### ISSUE TITLE
Datagrid: Content shifts in editable date cell

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#2126]
**Describe the bug**
Content shifts in an editable date cell when opening the datepicker.

**To Reproduce**
- Visit localhost:4000/components/datagrid/test-editable-datetime.html?locale=he-IL
- Click in an editable date cell
  - Notice the content shifts to the right when editing
  - Content shifts back to the left after closing the datepicker

**Expected behavior**
Content should not shift.

**Version**
4.19.0-dev

**Screenshots**
<img width="213" alt="before" src="https://user-images.githubusercontent.com/7952168/57406802-ae5c2280-71af-11e9-806b-d6c1489f63a5.png">
<img width="210" alt="after" src="https://user-images.githubusercontent.com/7952168/57406803-ae5c2280-71af-11e9-98cd-dccc3dfedcec.png">

**Platform**
Mac OS 10.14.4
Chrome Version 74.0.3729.131 (Official Build) (64-bit)

**Other info**
First reported here: https://github.com/infor-design/enterprise/pull/2105#issuecomment-490538470

**Comment by tmcconechy** [comment]
This should no longer be an issue
