### ISSUE TITLE
Datagrid: Filter operator popdown is not updated when the filter via a script

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2129]
**Describe the bug**
If the filter is applied via the api, over a user clicking to change the operator then it is no longer correct in the popdown as only the filter icon is updated.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
2. in the in stock color filter on only selected items
2. run the following in the console
`$('#datagrid').data('datagrid').applyFilter([{columnId: "inStock", operator: "selected", value: ""}], '')`
3. Then click on the filter for the "In Stock" field

**Expected behavior**
The icon and popdown are in sync and the filter is cleared.

**Version**
v4.18.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/57425819-f9337400-725b-11e9-9dd3-71fbe1fe0a03.png)
After the script runs
![image](https://user-images.githubusercontent.com/39749678/57425890-41529680-725c-11e9-898c-d00da097f771.png)
opening the operator for the filter, not that it changes the filter without actually selecting a value.

**Platform**
 - OS Version:  Windows 10
 - Browser Name chrome

**Comment by tmcconechy** [comment]
Also noticed that calling `$('#datagrid').data('datagrid').filterConditions()` when filtered shows the value as empty. I think we need a way to represent that type of filter as selected, not selected or all that applies in both functions.

**Comment by marknolaninfor** [comment]
@tmcconechy, I believe that the value is correct as you can look at other filters that allow a value to be entered like 'text' they seperate the operator and value. The 'checkbox' filter just does not have a value field.

**Comment by marknolaninfor** [comment]
@tmcconechy 
Could you also look at being able to re render the header and maintaining the applied filter?

Currently if you run the following it will render as if there is no filters operations
$('#datagrid').data('datagrid').renderHeader()

If you look at the filter expression then it is still set
$('#datagrid').data('datagrid').filterExpr

**Comment by tmcconechy** [comment]
@marknolaninfor Ok, some of this logic is in the saveUserSettings logic. But some folks did mention having some issues with this so it should be worth it to restore the filter conditions if renderHeader is called with a filter on
