### ISSUE TITLE
Datagrid: Need a way to keep the last column stretched

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2130]
**Describe the bug**
A lot of folks complain about the last column in the grid, so should find a solution.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html
2. Note that the last column is filled to the end
3. Resize any column and make it smaller
4. See that the last column is now not filling

**Expected behavior**
While this is ok because you now have fixed size columns, it would be good if the stretch column would still stay stretched.

**Version**
- ids-enterprise: [v4.18.0]

**Additional context**
Noted on https://github.com/infor-design/enterprise/issues/1797
Relates to https://github.com/infor-design/enterprise/issues/1818

**Comment by tmcconechy** [comment]
All these 3 are closely related
https://github.com/infor-design/enterprise/issues/2130
https://github.com/infor-design/enterprise/issues/1671
https://github.com/infor-design/enterprise/issues/605

**Comment by jbrcna** [comment]
QA **FAILED**
the columns with an option similar to "fit" function work fine. However, In `Safari` Browser after you use the sort in Datagrid, the columns become frozen. you can't resize anymore

Verified in http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/example-index.html

**Comment by tmcconechy** [comment]
This is already mentioned on https://github.com/infor-design/enterprise/issues/1818#issuecomment-564950660 so working on it there on just one issue. Moving this to done.
