### ISSUE TITLE
Datagrid: Errors in TreeGrid when using server side paging

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2132]
**Describe the bug**
If using treegrid + serverside paging the grid will error on any page but page one.

**To Reproduce**
1. Add the attached example
2. Go to http://localhost:4000/components/datagrid/test-tree-paging-serverside
3. Go to page two
4. Click to expand any tree row
5. See error

**Expected behavior**
No error..

**Version**
- ids-enterprise: [v4.18.1]

**Platform**
Any

**Additional context**
https://github.com/infor-design/enterprise-ng/issues/386

**Comment by tmcconechy** [comment]
Example test-tree-paging-serverside.html

```
<div class="full-height full-width">
  <div id="datagrid" >
  </div>
</div>

<script>
  $('body').one('initialized', function () {

      var grid,
        columns = [];

      //Define Columns for the Grid.
      columns.push({ id: 'taskName', hideable: false, name: 'Task', field: 'taskName', expanded: 'expanded', formatter: Formatters.Tree});
      columns.push({ id: 'id', name: 'Id', field: 'id'});
      columns.push({ id: 'page', name: 'Page', field: 'page'});
      columns.push({ id: 'desc', name: 'Description', field: 'desc'});
      columns.push({ id: 'comments', name: 'Comments', field: 'comments',  formatter: Formatters.Hyperlink});
      columns.push({ id: 'time', name: 'Time', field: 'time'});

      //Get some data via ajax
      var url = '{{basepath}}api/tree-tasks';

      $('#datagrid').datagrid({
        columns: columns,
        paging: true,
        dataset: [],
        treeGrid: true,
        toolbar: {title: 'Tasks (Hierarchical)', results: true, personalize: true, actions: true, rowHeight: true},
        source: function(req, response) {
          $.getJSON(url, function(data) {
            req.total = 100;
            for (var i = 0; i < data.length; i++) {
              data[i].page = req.activePage;
            }
            response(data, req);
          });
        }
      });
  });
</script>
```

**Comment by crlang44** [comment]
+1
I see this is part of the Focus: Datagrid but is there an estimated time for it to be fixed?

**Comment by tmcconechy** [comment]
I'm working on Datagrid focus issues next few sprints pretty much exclusively. I'll work on this one next sprint since its an error baring any unforseen issues.

**Comment by janahintal** [comment]
QA Passed. Will move to Done. 
Tested in: https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-lazy-loading.html 
https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-dropdown-objects.html across all browser, OS and devices
