### ISSUE TITLE
ColorPicker: Text is not visible on IE on readonly pickers

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2134]
**Describe the bug**
Color Picker Component: Extra Small Field box doesn't insert color name once you select a color

**To Reproduce**
1. Go to URL: http://master-enterprise.demo.design.infor.com/components/colorpicker/example-sizes.html
2. Click on click in the extra small
3. Open the color picker
4. select a color
5. The color picker closes
6. The extra small field box doesn’t display the name of the color only a cursor
7. The error occurs when the user has to click outside of the Extra small field box for the name of the color to appear in the field box

**Expected behavior**
Once the user clicks on a color the color should appear in the Extra Small field box once the color picker closes 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
None

**Platform**
 - OS Version: Windows
 - Browser Name IE 11

**Additional context**
None

**Comment by tmcconechy** [comment]
Im not seeing this one Chrome. Did you say it was an IE issue?

**Comment by tmcconechy** [comment]
There is a rule `.colorpicker-container.is-readonly.is-not-editable input[readonly]:focus` set to transparent.

**Comment by CindyMercadoReyes** [comment]
Sorry @tmcconechy  that is correct it's happening on IE 11.

**Comment by tmcconechy** [comment]
Yep i see it, updated the issue a bit. Seems like all readonly color pickers

**Comment by janahintal** [comment]
QA Passed. 
Tested in: http://master-enterprise.demo.design.infor.com/components/colorpicker/example-sizes.html across all browser, OS and devices
