### ISSUE TITLE
Datagrid cloumns misaligned after flipping the screen to Landscape in iOS device

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2138]
**Describe the bug**
Datagrid cloumns misaligned after flipping the screen to Landscape in iOS device

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html?locale=he-IL# in portrait mode
2. Wait for the grid to load then flip the screen to Landscape

**Expected behavior**
Grid columns should be aligned

**Version**
ids-enterprise: [v4.18.0] beta0 

**Screenshots**
<img width="1178" alt="Screen Shot 2019-05-08 at 6 26 23 PM" src="https://user-images.githubusercontent.com/45757016/57370366-9510a180-71c2-11e9-976c-07bd6730ecbe.png">

**Platform**
OS: iOS 12
Device: iPhone X

**Comment by tmcconechy** [comment]
This should no longer be an issue.
