### ISSUE TITLE
Datagrid: Pop-up menu in datagrid fires multiple events

### ISSUE THREAD

**Issue by macalat** [infor-design/enterprise#2140]
**Describe the bug**
When a popup menu is used in a datagrid, the event listener is not being remove after the previous click. Clicking on the same menu will attach another event listener and will cause to fire multiple events. 

**To Reproduce in NG**
1. Run the sample code 'Datagrid - Service' from enterprise-ng-master project
2. In the '_Actions_' column, select the first icon to show the popup
3. Select '_Action One_'. Console log will show the selected menu.
4. Select '_Action One_' again on the the same row.
5. Console will log twice.

**To Reproduce in EP**
1. go to http://localhost:4000/components/datagrid/test-all-formatters.html
2. scroll over to the actions (...) columns
3. open console
4.click .. and select one item and see one event
5. do it again and see two events (doubles every time)

**Expected behavior**
Clicking a menu on the popup should only trigger the event once every single time.

**Version**
- ids-enterprise-ng: v5.3.0

**Screenshots**
![soho_datagrid_popup_multiple_events](https://user-images.githubusercontent.com/4149858/57530233-5a953900-7369-11e9-8059-3223056e066b.gif)

[link](https://gfycat.com/leadingwindinggazelle) if gif does not work

**Platform**
 - OS Version: [Windows 10]
 - Browser Name [chrome]
 - Browser Version [74.0.3729.131 (Official Build) (64-bit)]

**Comment by tmcconechy** [comment]
Relates to #2133

**Comment by CindyMercadoReyes** [comment]
There's really no way to conduct QA testing on this issue since there's no data grid component that has a toast. Per my conversation with Tim this was tested internally as it's an NG issue.
