### ISSUE TITLE
Datagrid: Editor in single column editable grid appears to disappear when editing

### ISSUE THREAD

**Issue by rvaja-infor** [infor-design/enterprise#2143]
**Describe the bug**
The Editor in single column editable grid appears to disappear when editing.

**To Reproduce**
To reproduce, please run the attached sample page.

**Expected behavior**
The editor should be visible at all times, and not appear as though it has disappeared.

**Version**
v4.14.0 but noticed that the CSS styling in question has not changed for sometime in older and newer version

**Screenshots**
Before Editing:
![image](https://user-images.githubusercontent.com/45232365/57628753-6f084a00-7592-11e9-8f09-d88d9532cfc9.png)
Editing:
![image](https://user-images.githubusercontent.com/45232365/57628780-7a5b7580-7592-11e9-849f-8d3dcbdf09a9.png)

**Platform**
 - Desktop PC
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 74.0.3729.131 (Official Build) (64-bit)

**Additional context**
Issue is related to the 'absolute' position CSS style being applied to '.datagrid td.is-editing .datagrid-cell-wrapper'. Changing the CSS position to 'relative' resolves the issue and does not seem to effect multi-column editable grids from what I can see, but extra testing would be required to verify.
[SingleColumnEditableGridIssue.zip](https://github.com/infor-design/enterprise/files/3173298/SingleColumnEditableGridIssue.zip)

**Comment by tmcconechy** [comment]
Descoping some older issues we wont be able to get to. But its possible this might work in 5.0 and we can revisit this when thats done.
