### ISSUE TITLE
Type: Languages are no Longer changing Font

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2144]
**Describe the bug**

Before #1767 was done the languages would change the font to something more suitable for the languages alphabet. This is handled by this rule https://github.com/infor-design/enterprise/blob/master/src/components/typography/_typography.scss#L12 controls this.

Now because only the language is there not the full locale this isn't working. We may need to add back the full locale in the html property.

Additionally Koch suggests Gothic would be better than Batang for ko_KO

**To Reproduce**
1. Go to and page like http://master-enterprise.demo.design.infor.com/components/radios/example-index.html?locale=ko-KR
2. Inspect the html tag's font-family property. Should be `Batang` but it's not anymore.

**Expected behavior**
Shows correct based on locale.

**Version**
- ids-enterprise: [e.g. v4.18.0]

**Additional context**
Comment:

“Korean Font” in Infor is a problem. Used font in Infor is absolutely not suitable for this kind of Portal system. That font’s only used in Newspaper or traditional government document. 

Current font looks like “(바탕)Batang” style. But it should be changed to “Gothic” or something like this.

**Comment by tmcconechy** [comment]
These links explain it pretty well:

https://en.wikipedia.org/wiki/List_of_typefaces_included_with_macOS
https://en.wikipedia.org/wiki/List_of_typefaces_included_with_Microsoft_Windows

I think maybe we want Malgun Gothic / Apple Gothic ?

**Comment by lipetzan** [comment]
Feedback from Korean native speakers "for Korean Malgun Gothic is the preferred font"

**Comment by lipetzan** [comment]
Required by https://jira.lawson.com/browse/LMCLIENT-24901

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
