### ISSUE TITLE
DatePicker: how do I use openCalendar() method?

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#2148]
Hi,

I need to be able to trigger the calendar modal in runtime (without the need for the user to click on the calendar icon).
I have a button that I want the calendar to be shown when clicked.

In jQuery UI for example the method is this: ` $('#mypicker').datepicker('show');`

(using version 4.18.0)

Thanks,
Jonathan

**Comment by tmcconechy** [comment]
Hi Jonathan,

That would look like this... `$('#mypicker').data('datepicker').openCalendar()`
You have to get at the API on the data attribute.

**Comment by jonathanamiran** [comment]
you're the best! it works :)
