### ISSUE TITLE
Calendar: Need an example of a calendar without the left and right sides (just a month and events)

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2149]
**Describe the bug**
Need calendar to sho only calendar + events and optional legend. At the moment there are a couple small issues preventing this. Such as an error if you exclude the events on the right side and some missing css. Causing a gap

**Expected behavior**

- [x] need an example with just the calendar + events
- [x]  should full 100% height and width to parent size
- [x]  Add an the optional legend 
- [x]  need example with custom modal for event entry, this can be just showing an event click event and a toast. 
- [x]  ability to suppress mix and match between 1 or all of these: monthview, weekview, and dayviewday - option `showViewChanger: false`

**Version**
- Seen in ids-enterprise: [v4.19. dev]

**Additional context**
Teams Chat

**Comment by pwpatton** [comment]
Example of potenetial time off entry screen
![image](https://user-images.githubusercontent.com/4737815/57651457-d4f4d180-7592-11e9-99ea-882741c2f1f4.png)

**Comment by pwpatton** [comment]
Another example from financials

![image](https://user-images.githubusercontent.com/4737815/57713017-48501f00-7637-11e9-8816-3ebf21363f8d.png)

**Comment by janahintal** [comment]
QA Passed. No issues found so far for all browser and OS. 
Tested in: 
http://master-enterprise.demo.design.infor.com/components/calendar/example-only-calendar-legend.html#
http://master-enterprise.demo.design.infor.com/components/calendar/example-only-calendar.html

**Comment by CindyMercadoReyes** [comment]
Including the BDD for this enhancement. 
[story_github#2149.docx](https://github.com/infor-design/enterprise/files/3334990/story_github.2149.docx)
