### ISSUE TITLE
Datagrid: Button does not dim when disabled

### ISSUE THREAD

**Issue by jeffuycoque** [infor-design/enterprise#2150]
**Describe the bug**
Datagrid buttons (Ex. Remove, Up, Down) disabled via scripting does not dim. The onclick event is disabled but on the UI it still looks clickable unlike on version 4.17 wherein the buttons would look disabled.

**To Reproduce**

1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html

2. Select 1 record

3. Open Dev Tool/ Click F12

4. Input $('#remove-btn').disable() then click enter

**Actual Behavior**
4.19 version

![image](https://user-images.githubusercontent.com/49975141/57665198-8ba59000-762d-11e9-8a68-05b76fbcbaaa.png)

4.19 version on hover
![image](https://user-images.githubusercontent.com/49975141/57665240-b7c11100-762d-11e9-9558-e5ef32062d33.png)

**Expected Behavior**
4.17 version

![image](https://user-images.githubusercontent.com/49975141/57665267-c8718700-762d-11e9-9b68-cc1ce5aefb5c.png)

This issue affects most of our forms that has enable/disable logic. Although the buttons are no longer clickable, the look on the UI is misleading.

**Platform**
OS Version: Windows 10
Browser Name: Google Chrome

**Comment by janahintal** [comment]
QA Passed. Button was disabled after testing $('#remove-btn').disable(); in console. Will move to Done. Thanks!
Tested in: http://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
<img width="1112" alt="Screen Shot 2019-05-17 at 1 40 04 PM" src="https://user-images.githubusercontent.com/45757016/57906092-5ad28e80-78ab-11e9-8c82-b75f94873afc.png">
