### ISSUE TITLE
Targeted Achievement Chart: Add Icon support 

### ISSUE THREAD

**Issue by MadhaviDasika** [infor-design/enterprise#2152]
**Requirement**
Our application widgets has UI design to show icon on chart, especially of type targeted achievement. We achieved it by adding icon tags to chart dataset (to "text" attribute).
Earlier version till v4.14 allowed to add icon tags to chart dataset input. Considering XSS injection errors these tags are now ignored, and icons no more show up.

![image](https://user-images.githubusercontent.com/24714335/57673654-5a7f8c80-763a-11e9-8661-4b27b569a557.png)
![image](https://user-images.githubusercontent.com/24714335/57673665-68351200-763a-11e9-8e17-77746c134e7f.png)
![image](https://user-images.githubusercontent.com/24714335/57673675-75520100-763a-11e9-9bdf-461c514e162e.png)
![image](https://user-images.githubusercontent.com/24714335/57673766-c3ff9b00-763a-11e9-85c0-1bc879fd0daf.png)

**Solution**
Request to consider our test case designs and add support to Chart component allowing icons and styling of text that show on chart. 
FYI-Currently we added css to show underline to one of  the charts.

**Comment by tmcconechy** [comment]
As a note this worked prior to use stripping the tags. So we should make sure we have an example that shows putting icons in the text titles. Not sure i support the underline text until we have further info on what that means.

**Comment by MadhaviDasika** [comment]
@tmcconechy , as per our requirement, Underline as you said is to indicate a link and when user clicks on the link it navigates to the application. Since click action on chart applies to the whole chart component , for now we modified the css such that on chart, the cursor is made default and when user hovers on the underlined text it becomes pointer. However, click on anywhere still navigates to the application.

**Comment by tmcconechy** [comment]
Ok Got it, i think we can allow proper hyperlinks in there. Thats better than just using fake text with underlines.

**Comment by janahintal** [comment]
QA Passed. Will move to Done
Verified in: http://4190-beta0-enterprise.demo.design.infor.com/components/targeted-achievement/example-links-icons.html across all browser, OS and devices
