### ISSUE TITLE
Timepicker: The swedish translation for Set time should be changed to "Sätt tid"

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#2153]
**Describe the bug**
Currently the "Set Time" in the time picker is translated to "Klockslag" in Swedish, which is a bit confusing. "Sätt tid" would be a better translation. Another possibility would be to just use "OK" instead of "Set time" I think.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/timepicker/example-index.html?locale=sv-se 
2. Click on the clock
3. See that The button states "Klockslag" Should be "Sätt tid"   (Or OK)

**Expected behavior**
It should say "Sätt tid" (Or OK if OK is used instead of "Set time").

**Version**
- ids-enterprise: v4.18.1

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/57715229-86206800-7676-11e9-88e8-9a448d5120dc.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name  chrome

**Comment by tmcconechy** [comment]
Sure, if you want to update this you can do a PR changing the file: https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/sv-SE.js#L58

We'll just have to watch that the translation team doesn't accidentally add back in a wrong translation.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by SofiK** [comment]
Thank you! :)

**Comment by tmcconechy** [comment]
@SofiK the translation team gave me a new file where the translation here is 'Ange tid' is that fine or is Sätt tid' still better?

**Comment by SofiK** [comment]
"Ange tid" is great! 👍
