### ISSUE TITLE
RTL: Header, unable to hide Application Menu in IE11 

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#2154]
**Describe the bug**
In IE11 with RTL, hamburger icon is missing after clicking it
It seems that the Application Menu is overlapping the icon.
In Chrome it works well.

**To Reproduce**
1. Open IE11
2. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/header/example-index?locale=he-IL](https://design.infor.com/code/ids-enterprise/latest/demo/components/header/example-index?locale=he-IL)
3. Click on the hamburger icon
4. See behavior

**Expected behavior**
Should work the same as Chrome

**Version**

- ids-enterprise: 4.18.0

**Screenshots**

**Platform**
 - OS Version: Windows 7
 - Browser Name: Internet Explorer
 - Browser Version: 11.0.9600.19326

**Additional context**
Thanks!

**Comment by tmcconechy** [comment]
Even tho we have plans to drop IE 11 support https://github.com/infor-design/enterprise/issues/3756

This should probably be fixed

**Comment by tmcconechy** [comment]
Going to descope this as we limit IE 11 support

**Comment by janahintal** [comment]
The issue still exists. Please see screenshot below. The header shrink as I opened the hamburger menu. 

![image](https://user-images.githubusercontent.com/45757016/87124391-4aede900-c2bb-11ea-998b-92f98d99ee3b.png)

**Comment by tmcconechy** [comment]
Hmm ok i rethink this now. We should fix this. Its pretty obvious

**Comment by janahintal** [comment]
This is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/header/example-index?theme=soho&variant=light&colors=0066D4&locale=he-IL 
![image](https://user-images.githubusercontent.com/45757016/88532577-700e8580-d037-11ea-9881-1433f8627aac.png)
