### ISSUE TITLE
Datagrid: Datetime filtering does not return the correct format pattern within filterConditions.

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2159]
**Describe the bug**
If a datagrid field shows both the date and time then the filterConditions only returns the date format portion, as the just uses the dateFormat setting. But it should be using the pattern that has been calculated for the datepicker control from all of its settings.

**To Reproduce**
An example needs to be provided as all the examples are date only 

**Expected behavior**
The correct format is used, so that the dates can be parsed and matched correctly for the filtering process.

**Version**
4.19

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/57747432-b3bbee80-7714-11e9-97bf-2860c8a0d45c.png)

![image](https://user-images.githubusercontent.com/39749678/57747395-9ab33d80-7714-11e9-931b-f007ebf2908c.png)

**Comment by marknolaninfor** [comment]
The pattern of the filter condition was then "d/MM/yyyy" and would not work when the condition and rowValue was calculated. 

The pattern on the datepicker should be used as this is used as the display pattern and will work for all of the settings instead of attempting to duplicate the conditions.

**Comment by janahintal** [comment]
QA Passed. Will Move to Done. Thanks

Tested in: http://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-datetime-client-side.html
