### ISSUE TITLE
Accordion: arrow down/up is not aligned center on Safari

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise#2161]
**Describe the bug**
Arrow down/up on accordion pane when using `SohoAccordionComponent` isn't aligned center on iOS like normal desktop.

**To Reproduce**
1. Go to `accordion.demo.html` in example app with iPhone 6/7/8 simulation.
2. Observe that the arrow down/up is not aligned center like desktop

**Expected behavior**
Arrow down/up should align center, similar to desktop

**Version**
- ids-enterprise-ng: master branch

**Screenshots**
This is iOS simulation
![image](https://user-images.githubusercontent.com/27772165/57766956-98e37d00-7708-11e9-899a-142843bfecdf.png)

This is desktop
![image](https://user-images.githubusercontent.com/27772165/57767077-d0522980-7708-11e9-9dd7-00ad4d9a8e1f.png)

**Platform**
 - Device: simulation iPhone 6,7,8
 - OS Version: **N.A.**
 - Browser Name: Chrome
 - Browser Version: Version 74.0.3729.157 (Official Build) (64-bit)

**Additional context**
I observed that iOS has a completely different css compare to desktop version. Are there any specific reasons for that ?

**Comment by tmcconechy** [comment]
This is still an issue. We probably should fix this by now
