### ISSUE TITLE
Demo App: Kitchen Sink errors from reinitializing personalization many times

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#2167]
**Describe the bug**
When loading the kitchen sink page, personalization is initialized many times, eventually causing: `Uncaught TypeError: Cannot read property 'fadeOut' of undefined` on `personalize.js:357`.

**To Reproduce**
1. Go to http://localhost:4000/

**Expected behavior**
No errors, improved performance from not re-init'ing many times.

**Version**
Exposed by improvements in #2103

**Screenshots**
![image](https://user-images.githubusercontent.com/1012017/57812202-59ce1f80-773a-11e9-9293-239188d480d6.png)

**Comment by EdwardCoyle** [comment]
@nickwynja I checked this against http://master-enterprise.demo.design.infor.com/ and it doesn't seem it's a problem there.  This might be specific to the changes on that PR/branch

**Comment by tmcconechy** [comment]
Same but i we could add the corrections i mentioned on https://hookandloop.slack.com/archives/G7PBY3X9S/p1557857424351200 just so it doesnt fire for every line in the listview.
