### ISSUE TITLE
is-personalizable not working for generated chart and alerts.

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2171]
**Describe the bug**
soho-chart and soho-alert elements are built in EP js code. So I don't' have an opportunity to place a personalize-chart or personalize-text class on their internal element.

**To Reproduce**
1. update personalize/example-form2.html with changes from attached file
2. run it and see chart and alert clash with the background

**Expected behavior**
Would like a class that can be added to the upper div. For example: 
personalize-alert and personalize-chart maybe.

**Version**
- ids-enterprise: v4.19.0

**Screenshots**
![image](https://user-images.githubusercontent.com/4737815/57865864-f8eb2980-77c3-11e9-9d69-c792bb44653d.png)

**Platform**
 - PC
 - window 10
 - Safari
 - Version 74.0.3729.131

**Additional context**
Updated Example:
[example-form2.html.txt](https://github.com/infor-design/enterprise/files/3187765/example-form2.html.txt)

**Comment by janahintal** [comment]
Hi @tmcconechy 
Tested in: 
http://4190-beta0-enterprise.demo.design.infor.com/components/targeted-achievement/list
http://4190-beta0-enterprise.demo.design.infor.com/components/targeted-achievement/list
http://4190-beta0-enterprise.demo.design.infor.com/components/completion-chart/list

Noticed that some labels are still not visible when in Dark mode. Please see below link. 
http://4190-beta0-enterprise.demo.design.infor.com/components/completion-chart/example-colors.html
http://4190-beta0-enterprise.demo.design.infor.com/components/completion-chart/example-colors.html
<img width="1221" alt="Screen Shot 2019-05-22 at 1 01 31 PM" src="https://user-images.githubusercontent.com/45757016/58148639-1cb1e200-7c92-11e9-9f44-80cda6deafe8.png">
<img width="1217" alt="Screen Shot 2019-05-22 at 1 02 07 PM" src="https://user-images.githubusercontent.com/45757016/58148641-1e7ba580-7c92-11e9-9005-0845ad9b5653.png">

**Comment by janahintal** [comment]
Hi @tmcconechy. 
Tested this ticket and still, some labels with #880e0e color is still not readable in Dark Mode. 
http://4190-beta1-enterprise.demo.design.infor.com/components/completion-chart/example-colors.html?theme=uplift
http://4190-beta1-enterprise.demo.design.infor.com/components/completion-chart/example-variations.html?theme=uplift

**Comment by tmcconechy** [comment]
@janahintal Can you test this again? The links you mentioned are not dark mode but i retested these pages and saw two small issues. Fixing

http://4190-beta1-enterprise.demo.design.infor.com/components/completion-chart/example-colors.html?theme=soho&variant=dark
http://4190-beta1-enterprise.demo.design.infor.com/components/completion-chart/example-index.html?theme=soho&variant=dark
http://4190-beta1-enterprise.demo.design.infor.com/components/completion-chart/example-variations.html?theme=soho&variant=dark

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. Thanks!
Tested in: 
http://4190-beta2-enterprise.demo.design.infor.com/components/completion-chart/example-colors.html?theme=soho&variant=dark
http://4190-beta2-enterprise.demo.design.infor.com/components/completion-chart/example-index.html?theme=soho&variant=dark
http://4190-beta2-enterprise.demo.design.infor.com/components/completion-chart/example-variations.html?theme=soho&variant=dark
Across all browser, OS and devices.
