### ISSUE TITLE
Datagrid: Overlapping Datagrid Icons

### ISSUE THREAD

**Issue by jeffuycoque** [infor-design/enterprise#2174]
**Describe the bug**
Values that are more than 10 characters causes an overlap between the Datagrid Text and the Datagrid  Icons.

**To Reproduce**

Example 1: Datagrid Text Overlaps Datagrid Lookup Icon
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html

2. Manually type in more than 10 characters on the Datagrid Lookup Field
or Set a value via dev tool:
$('#datagrid').data('datagrid').settings.dataset[0].productId = 11111111111;
$('#datagrid').data('datagrid').renderRows();

3. Hover mouse on the Datagrid Lookup Field

![image](https://user-images.githubusercontent.com/49975141/57906033-219a1e80-78ab-11e9-99fb-7f5924996d4b.png)

Example 2: Datagrid Text Overlaps Datagrid Alert/Info/Error Icons
1. Go to http://localhost:4000/components/datagrid/test-editable-lookup.html

2. Setup a custom rule in test-editable-lookup.html:
		  $.fn.validation.rules.customRule = {
			check: function (value, field, grid) {
			  return false;
			},
			message: 'Incorrect Input',
			type: 'error'
		  };

3. Set the custom rule on the validate property of the datagrid fields
        columns.push({ id: 'productName', name: 'Product Name', sortable: false, field: 'productName', formatter: Formatters.Hyperlink, validate: 'customRule', editor: Editors.Input});
        columns.push({ id: 'productId', name: 'Product Id', field: 'productId', formatter: Formatters.Lookup, editor: Editors.Lookup, validate: 'required customRule', editorOptions: lookupOptions, width: 120 });

4. Manually type in more than 10 characters on the Datagrid Lookup Field
or Set a value via dev tool:
$('#datagrid').data('datagrid').settings.dataset[0].productId = 11111111111;
$('#datagrid').data('datagrid').renderRows();

5. Focus out on the field to trigger the validation

![image](https://user-images.githubusercontent.com/49975141/57907242-66c04f80-78af-11e9-840b-730e7696d954.png)

This is not reproducible on form load since there seems to be an auto adjustment of the width based on the initial values, however once we update it using a value with a longer text then the overlap will occur.

Our expected behavior would be that once the value changes, the cell width would adjust based on its updated value.

**Note**: This behavior does not affect the main functionality of our web form. 

**Platform**

OS Version: Windows 10
Browser Name: Google Chrome

**Comment by marknolaninfor** [comment]
This effectively is asking for a cell to expand bases on a change. I have added a pull request for this but you may want to only turn this on via a parameter as I am not sure that all will want this behaviour.

**Comment by tobywicksinfor** [comment]
This issue is still occurring in the latest build:

```
 *  IDS Enterprise Components - v4.24.0-dev
 *  Date: 2019-11-20T03:32:12.024Z
 *  Revision: 2a59ee56e22a706215acbd53a207de6b52fce116
```

in:

```
Google Chrome | 78.0.3904.97 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | 021b9028c246d820be17a10e5b393ee90f41375e-refs/branch-heads/3904@{#859}
OS | Windows 10 OS Version 1809 (Build 17763.557)
```

![Datagrid lookup cell overlaps text](https://user-images.githubusercontent.com/40477207/69208256-cec75980-0ba2-11ea-8341-b08d38603d5e.PNG)

@tmcconechy Should I create a new issue?

**Comment by tmcconechy** [comment]
Yes let’s make a new issue. A lot of history here and that should clean things up to the present state. Not seeing any other open issues about this either
