### ISSUE TITLE
Datagrid: Datagrid Info/Alert Icon overlaps with Datagrid Lookup Icon

### ISSUE THREAD

**Issue by jeffuycoque** [infor-design/enterprise#2175]
**Describe the bug**
Datagrid Info/Alert Icon overlaps with Datagrid Lookup Icon when validation rule is triggered.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/test-editable-lookup.html

2. Setup a custom rule in test-editable-lookup.html:
```
$.fn.validation.rules.customRule = {
check: function (value, field, grid) {
return false;
},
message: 'Incorrect Input',
type: 'info'
};
```
3. Set the custom rule on the validate property of the datagrid fields
```
columns.push({ id: 'productName', name: 'Product Name', sortable: false, field: 'productName', formatter: Formatters.Hyperlink, validate: 'customRule', editor: Editors.Input});
columns.push({ id: 'productId', name: 'Product Id', field: 'productId', formatter: Formatters.Lookup, editor: Editors.Lookup, validate: 'required customRule', editorOptions: lookupOptions, width: 120 });
```
4. Manually type in more than 10 characters on the Datagrid Lookup Field
or Set a value via dev tool:
```
$('#datagrid').data('datagrid').settings.dataset[0].productId = 11111111111;
$('#datagrid').data('datagrid').renderRows();
```
5. Focus out on the field to trigger the validation then hove on the Datagrid Lookup Field

![image](https://user-images.githubusercontent.com/49975141/57908193-0a126400-78b2-11e9-8c93-fdd75ec6ec22.png)

On this scenario, the user would no longer be able to see the Lookup Icon.

This is also reproducible when using alert icon.

![image](https://user-images.githubusercontent.com/49975141/58442208-819a8b80-811b-11e9-9a0f-8027fa8febad.png)

The expected behavior would be the same with the current behavior for error icon in which the error icon would move to the left once the lookup icon is shown.

![image](https://user-images.githubusercontent.com/49975141/58442328-d25eb400-811c-11e9-9b51-880e6633e58a.png)

**Platform**

OS Version: Windows 10
Browser Name: Google Chrome

**Comment by tmcconechy** [comment]
Relates to https://github.com/infor-design/enterprise/issues/2174

**Comment by marknolaninfor** [comment]
The following will correctly move the other icons 
![image](https://user-images.githubusercontent.com/39749678/58451155-75c9bc00-8151-11e9-800b-86287ffd7253.png)

There still would be the possible issue if the cell has move than one validation type error as the icons are stacked.
