### ISSUE TITLE
Datagrid: Counts in the Title not updated

### ISSUE THREAD

**Issue by deep7102** [infor-design/enterprise#2177]
**Describe the bug**
Datagrid title not updating after filter or add/remove rows.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-paging.html
2. On page load it say `(all 1000)`
3. In column “Product Id” type 214224 title will change to`(1 of 1000)`
4. Clear the filter to render back all rows
5. See the title now `(1000 of 1000)`

**Expected behavior**
Title should updated with right values.

**Version**
- ids-enterprise: v4.18.x

**Screenshots**
![2019-05-19t11-07a](https://user-images.githubusercontent.com/38439203/57937450-fbb54f80-7893-11e9-9c0b-2c2e67b79117.gif)

**Platform**
All browsers, devices and OS

**Additional context**
No additional context.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
