### ISSUE TITLE
SOHO-8120: Dismissable tag icon misaligned in RTL

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#218]
The x-icon of dismissable tags are misaligned when running RTL.

*Reproduce*
- Go to http://localhost:4200/tags with dir="RTL"

*ids-enterprise*
The x-icon is placed too far to the right.
!ids-enterprise_tag.PNG|thumbnail!
*ids-enterprise-ng*
The x-icon is placed too far to the right.
The x-icon is placed to far down.
!ids-enterprise-ng_tags.PNG|thumbnail!

**Comment by tmcconechy** [comment]
Closed as per https://jira.infor.com/browse/SOHO-8120
