### ISSUE TITLE
Accordion: Need a way to right align some text

### ISSUE THREAD

**Issue by MadhaviDasika** [infor-design/enterprise#2180]
**Problem**
Component: Accordion
There was a fix to accordion component which added a new style **"display: inline-block"** to accordion>a>span. Its available from **v4.17**. There is a GA widget that has accordion component which shows text aligned to right on accordion header. This new style has impacted the right aligned text on header.
![image](https://user-images.githubusercontent.com/24714335/57673134-8c8fef00-7638-11e9-8084-29e9abb6e110.png)

**Solution**
Most of our application widgets UI will have text showing to right on accordion header (as shown in the screenshot).
Accordion would be better if the style is changed to accommodate our use case design.

![AccordionHeader](https://user-images.githubusercontent.com/24714335/57672861-73d30980-7637-11e9-970f-466619528c17.JPG)

**Comment by clepore** [comment]
We appreciate your submission! Unfortunately, we are unable to make any progress on the issue until the description is in the structure of one of the templates (`bug request` or `feature request`) found after clicking the "New Issue" button on the repo's Issues page [here](https://github.com/infor-design/enterprise/issues/new/choose).

**Comment by tmcconechy** [comment]
Some background we found on a quick webex this broke because of https://github.com/infor-design/enterprise-ng/blob/master/projects/ids-enterprise-ng/src/lib/accordion/soho-accordion-header.component.html#L2

And the fact we have this rule 
```
.accordion-header > a > span {
  display: inline-block;
}
```

I suggested we make a "feature" for this so it wont break again. `listview-right-text` class and an example with a test.

**Comment by tmcconechy** [comment]
Issue seems clear enough will add to the backlog. But please use the issue template when making issues. Also be nice if you did update this to use the issue/bug template please.

**Comment by harishinfor** [comment]
Hi,
we have an enhancement where an icon should be displayed to right of the description as shown in below:
![image](https://user-images.githubusercontent.com/25452976/80336909-24044700-8876-11ea-9cc2-7f3afa32fb0f.png)

**Comment by tmcconechy** [comment]
The new 5.0 accordion will allow contents in its template (available sometime next year). So descoping this issue for now
