### ISSUE TITLE
Date Picker: No date picker on Windows Internet Explorer

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2183]
**Describe the bug**
Date Picker: No date picker on Windows Internet Explorer

**To Reproduce**
1. Open Internet Explorer on Windows
2. Go to http://master-enterprise.demo.design.infor.com/components/datepicker/example-index
3. See issue: there is no date picker 
4. Type in the date field
5. See issue: Date format will not be applied

**Expected behavior**
Date picker should work correctly on Windows Internet Explorer

**Version**
- ids-enterprise: [e.g. v4.19.0-dev]

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/58019416-0c85ef80-7b38-11e9-95f1-0eec13b82e25.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Internet Explorer 11

**Additional context**
Also happens on time picker http://master-enterprise.demo.design.infor.com/components/timepicker/example-index.html

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
