### ISSUE TITLE
File Upload: On Windows IE, pressing backspace on file upload is causing the browser to go to previous page

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2184]
**Describe the bug**
File Upload: On Windows IE, pressing backspace on file upload is causing the browser to go to previous page

**To Reproduce**
1. Open Windows Internet Explorer or Edge
2. Go to http://master-enterprise.demo.design.infor.com/components/fileupload/example-index
3. Select a file on the file upload
4. While on the file upload, press backspace
5. See issue, file upload will be cleared but will also cause the browser to go to the previous page

**Expected behavior**
File upload field should be cleared and stay in the page when backspace is pressed.

**Version**
- ids-enterprise: [e.g. v4.7.0 - current version]

**Screenshots**
No applicable screenshot.

**Platform**
 - OS Version: Windows 10
 - Browser Name: Internet Explorer and Edge

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Note that delete will clear the dropdown. But there are some key handlers for Mac (backspace vs delete) that should probably be made to work ok on windows

**Comment by brianjuan** [comment]
http://4190-beta1-enterprise.demo.design.infor.com/components/fileupload/example-index
Passed QA testing.
