### ISSUE TITLE
Time Picker Component: Values from the dropdown list box is not getting inserted in the field-box 

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2191]
**Describe the bug**
Time Picker Component: Values from the dropdown list box is not getting inserted in the field-box 

**To Reproduce**
1. Go to url: http://master-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=sv-se
2. On Android Galaxy S9 click on the hours dropdown list box and select "02"
3. Click on the OK/"Satt tid" button 
4. rotate the device to landscape view
5. Perform steps 2 and 3 again. 
6. The time picker hours field box is not getting update with the time 

**Expected behavior**
The time picker list box should work on portrait and landscape view

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Device (if applicable) [Samsung Galaxy S9]
 - Browser Name [chrome]

**Additional context**
None

**Comment by tmcconechy** [comment]
As discussed @deep7102 see if you can fix this as well https://github.com/infor-design/enterprise/issues/2021 as closely related

**Comment by tmcconechy** [comment]
Descoping this for now
