### ISSUE TITLE
Compact Form: Implement Checkbox/Radios/Dropdown

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#2193]
**Is your feature request related to a problem? Please describe.**
This issue has the same goals as #1955, focusing on the implementation of:
- [x] Checkbox
- [x] Radios
- [ ] Dropdown/Multiselect
- [ ] Different visual states (error, warn, success, info, neutral) for input fields

**Additional Context**
Per @kayiuho's [comment on that issue](https://github.com/infor-design/enterprise/issues/1955#issuecomment-493488958), there is a [Dropbox Paper document](https://paper.dropbox.com/doc/Compact-Form--AdfI1qwaQD8ovJjtd44TMg9EAg-R8idPCwaQcbGBbIZVX3Md) containing designs that is currently in progress.

----

Branch: https://github.com/infor-design/enterprise/compare/2193-form-compact

**Comment by EdwardCoyle** [comment]
Branch has been started here: https://github.com/infor-design/enterprise/compare/2193-form-compact

**Comment by EdwardCoyle** [comment]
#2466 merged the changes for font size, spacing, and the additions of checks/radios.  Outstanding on this issue are the Dropdown/Multiselect, the visual states, and the dirty indicator.

**Comment by tmcconechy** [comment]
Should this stay open?

**Comment by tmcconechy** [comment]
@EdwardCoyle 
Should we close this and move to QA? Or keep it open for the remaining outstanding items? Maybe a new issue for those?

**Comment by EdwardCoyle** [comment]
Might as well keep it open for now.

**Comment by janahintal** [comment]
Hi. Tested this in http://master-enterprise.demo.design.infor.com/components/form-compact/example-index.html?locale=ar-EG & http://master-enterprise.demo.design.infor.com/components/form-compact/example-index.html no issued found so far for radio buttons and checkboxes. Will move to Done.

**Comment by tmcconechy** [comment]
I think we will shelf this until further notice. Most is done and compact form isn't what it was
