### ISSUE TITLE
Locale: Add support for Spanish Latin America (es_419)

### ISSUE THREAD

**Issue by starmount-mjcampo** [infor-design/enterprise#2204]
In order to support a wider number of countries without incurring translation costs for each country, we need to be able to support a common form of Spanish for Latin America.  Chrome and IE/Edge support Spanish for Latin America.  This language will suffice in a large number of countries in the Americas.  Applications can then be certified within the countries with incurring minimal translation costs.  From a locale perspective, es_MX (Mexico) should suffice.

**Is your feature request related to a problem?** 
Different browsers support a different group of countries in Latin America.  Each country may have its own language/locale designater.  We do not want to have to support the many different resource bundles (translations) for each country when a generic will do.

The following locale specific changes will need to be accommodated. (There may be more but these are the ones that are known.)
- Dates - DD/MM/YYYY format - 25/12/2019 is December 25, 
- Amounts - ###,###,###.## - commas for separators and period for decimal place.

**Describe alternatives you've considered**
We are updating the application such that if a language/locale is set from the browser is Spanish in a locale that is not already supported, we want to be able to use the generic locale of Latin America.  (We already support es_ES for Spain.)

**Comment by starmount-mjcampo** [comment]
If the browser language is set to es_419, IDS does not display many of the components (data grids for one)).

**Comment by tmcconechy** [comment]
Did you mean to close this? es_419 will not work (would be es-419 if when we do add it but at the moment it doesnt exist so wont work)

**Comment by starmount-mjcampo** [comment]
Didn't mean to close it.  Just didn't hit the correct key.

**Comment by tmcconechy** [comment]
Relates to #2216

**Comment by janahintal** [comment]
QA Passed. Will Move to Done. 
Tested in below links across all bowser, OS and Devices.
http://4190-beta1-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=es-419
http://4190-beta1-enterprise.demo.design.infor.com/components/locale
