### ISSUE TITLE
Hierarchy partially loads when their are multiple instances on the same page.

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#2205]
**Describe the bug**
Hierarchy partially loads when their are multiple instances on the same page. For example a tab panel with a different hierarchy chart in each panel.

**To Reproduce**
1. Get **_test.multi-root.html_** example from PR
2. Go to http://localhost:4000/components/hierarchy/test-multiple-charts.html
3. Click on tab two.
4. Notice the whole chart does not load

**Expected behavior**
The chart should fully load in both tabs.

**Version**
4.16.x

**Screenshots**
**Tab One**
![hierarchy-in-tabs](https://user-images.githubusercontent.com/1056684/58119194-0c353500-7bc8-11e9-9769-c62f4dc170ad.png)

**Tab Two**
![hierarchy-in-tabs-partial-load](https://user-images.githubusercontent.com/1056684/58119207-135c4300-7bc8-11e9-9b1f-4903e18e6767.png)

**Platform**
 - Windows, Chrome  74.0.3729.157

**Additional context**

**Comment by janahintal** [comment]
Hi @tmcconechy the tree did not load on Windows 10 IE11 http://4190-beta0-enterprise.demo.design.infor.com/components/hierarchy/test-multiple-charts.html. Will move to Failed QA. Thanks

**Comment by janahintal** [comment]
QA Passed. Will Move to Done
Tested in
http://4190-beta1-enterprise.demo.design.infor.com/components/hierarchy/test-multiple-charts.html across all browser, OS and devices
