### ISSUE TITLE
Icons: Theme Uplift icon alignment is off

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#2211]
**Describe the bug**
General icon alignment inside of buttons for Uplift theme is off.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/?theme=uplift
2. Review all items with icons
    - [x] buttons
    - [x] spinbox
    - [x] process indicator
    - [x] badges
    - [x] timeline
    - [x] dropdown
    - [x] checkboxes
    - [x] icons on Targeted Achievement chart (#2220)

**Expected behavior**
The alignment should look pretty.

**Version**
- ids-enterprise: 4.19.0-dev+ (uplift theme)

**Screenshots**
<img width="181" alt="Screen Shot 2019-05-21 at 6 01 32 PM" src="https://user-images.githubusercontent.com/742319/58133705-7ebb0a80-7bf2-11e9-85a4-440963d85e91.png">

**Platform**
- all

**Additional context**
Related to #2072

**Comment by tmcconechy** [comment]
Would also add to test in IE11, Edge and Safari on both normal and uplift. I saw an minor icon alignment issue on spinbox on soho theme in edge / ie11

**Comment by CindyMercadoReyes** [comment]
This ticket is now resolved.  All the minor issue that I found are being tracked in GitHub ticket number: https://github.com/infor-design/enterprise/issues/2289
