### ISSUE TITLE
Datagrid: Theme Uplift header alignment issues

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#2212]
**Describe the bug**
There are still many alignment issues involving the datagrid header and its short/med/tall w/ filter row combinations.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-filter.html?theme=uplift
2. Click on the `...` menu
3. Change the combinations of row height and toggle filter row

**Expected behavior**
Everything should be aligned.

**Version**
- ids-enterprise: 4.19.0-dev+ (uplift theme)

**Screenshots**
- Too many to list

**Platform**
 - all

**Additional context**
related to #2072 and PR https://github.com/infor-design/enterprise/pull/2202

**Comment by janahintal** [comment]
Hi @tmcconechy, noticed that the filters are still not aligned in uplift filter. 
http://4190-beta1-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift
<img width="1427" alt="Screen Shot 2019-06-04 at 7 08 52 PM" src="https://user-images.githubusercontent.com/45757016/58874920-b353b980-86fc-11e9-922b-80500433db0e.png">

**Comment by janahintal** [comment]
QA Failed. Issue still exist. Filters in header still dont align. 
http://4190-beta2-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift
<img width="1311" alt="Screen Shot 2019-06-06 at 1 19 21 PM" src="https://user-images.githubusercontent.com/45757016/59008751-d8ac0900-885d-11e9-9ce9-243f78384568.png">

**Comment by brianjuan** [comment]
http://4190-rc0-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift
Alignment issues are now fixed, QA passed on all browsers.
