### ISSUE TITLE
Datagrid: Incorrect value on Selection Counter after Adding new row

### ISSUE THREAD

**Issue by jeffuycoque** [infor-design/enterprise#2214]
**Describe the bug**
If the datagrid select all rows checkbox is ticked before adding a new row, the selected count is not being updated even if the new row is automatically selected.

**To Reproduce**
1. Navigate to http://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Change the records per page to 75 to show all records.
3. Click Select All checkbox
![image](https://user-images.githubusercontent.com/49975141/58149423-7bc52600-7c95-11e9-9c76-797f0797588e.png)
4. Click Add row button
![image](https://user-images.githubusercontent.com/49975141/58149448-91d2e680-7c95-11e9-8a91-5da1f869a8f2.png)

**Expected behavior**
The selection counter should also count the newly added row.

**Platform**
OS Version: Windows 10
Browser Name: Google Chrome

**Comment by tmcconechy** [comment]
I would say that it should'nt mark the newly added row as selected in the first place.

**Comment by jeffuycoque** [comment]
Hi Tim, we agree that it makes much more sense if the newly added row is not automatically selected.

**Comment by jeffuycoque** [comment]
Just to clarify, this behavior does not affect the main functionality of our web form. We filed this to track that the misleading count is also occurring in IDS.

**Comment by tmcconechy** [comment]
Got it, I think we should fix it the way i said by ensuring the newly added row isnt selected.

**Comment by marknolaninfor** [comment]
Following the steps this is not reproducable. It must have been corrected via another ticket.

![image](https://user-images.githubusercontent.com/39749678/64740011-10001500-d533-11e9-800a-3a8e0cde35d2.png)
