### ISSUE TITLE
Locale: If using en-XX locales all new translations will be undefined

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2216]
**Describe the bug**
If you set the locale to en-GB since the new strings arent copied over all new strings will be [undefined].

**To Reproduce**
1. Go to http://localhost:4000/components/personalize/example-color-theme-api.html?locale=en-GB
2. Notice the dropdowns
3. But any non en-XX locale will default back to en-US correctly. http://localhost:4000/components/personalize/example-color-theme-api.html?locale=de-DE

**Version**
- ids-enterprise: [v4.19.0]

**Additional context**
Easy to fix by copying the strings over to all en locales.

**Comment by janahintal** [comment]
QA Failed. Drop down list dont display in Windows 10 IE 11 browser. 

http://4190-beta1-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html?locale=de-DE
http://4190-beta1-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html?locale=en-GB

<img width="1359" alt="Screen Shot 2019-06-03 at 9 07 05 PM" src="https://user-images.githubusercontent.com/45757016/58804164-c8b8dd00-8643-11e9-8e78-5c807a5016fa.png">
<img width="1358" alt="Screen Shot 2019-06-03 at 9 07 26 PM" src="https://user-images.githubusercontent.com/45757016/58804165-c8b8dd00-8643-11e9-8929-179c8b576974.png">

**Comment by janahintal** [comment]
QA Failed. http://4190-beta2-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html?locale=en-GB still don't work in IE

**Comment by janahintal** [comment]
QA failed. Dropdown is not loading in all Browser and OS http://4190-rc0-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html?locale=en-GB
![image](https://user-images.githubusercontent.com/45757016/59256108-d4208f80-8c65-11e9-9dd8-38549a868f6d.png)

**Comment by brianjuan** [comment]
http://4190-rc1-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html?locale=en-GB
http://4190-rc1-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html?locale=de-DE
Now passed QA testing on all desktop and mobile browsers.
