### ISSUE TITLE
SOHO-8037: [All Browsers] Contextual Action Panel Control: Unable to close the modal

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#222]
1. [All Browsers] Contextual Action Panel Control: Unable to close the modal

2. For URLS: 
http://470-beta-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html

and 

http://470-beta-enterprise.demo.design.infor.com/components/contextualactionpanel/example-trigger.html

3. Steps to reproduce:
- Click Open Contextual Action Panel Button
- Click outside the modal

**Comment by brianjuan** [comment]
This bug fix is working as expected across all browsers and passed QA testing.
