### ISSUE TITLE
Targeted Achievement Chart: Icon Alignments (Uplift)

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#2220]
**Describe the bug**
Some of the alignment between the icons and label text on the Targeted Achievement charts is not quite right.  It's especially off on Uplift color scheme variants.

**To Reproduce**
See that the alignment of the icons compared to the label text on http://localhost:4000/components/targeted-achievement/example-links-icons.html:

![Screen Shot 2019-05-22 at 4 54 13 PM](https://user-images.githubusercontent.com/3249601/58208704-44657200-7cb3-11e9-8981-bfd831743698.png)

... as well as http://localhost:4000/components/targeted-achievement/example-links-icons.html?theme=uplift&variant=dark:

![Screen Shot 2019-05-22 at 4 55 15 PM](https://user-images.githubusercontent.com/3249601/58208705-44657200-7cb3-11e9-9771-0929e199f0fc.png)

**Expected behavior**
The icon alignment should be centered along with the label text.

**Version**
- `v4.19.x`

**Additional context**
Discovered when reviewing #2217

**Comment by tmcconechy** [comment]
Will. Add to my PR I just changed that icon so it would flow on either side of the text

**Comment by tmcconechy** [comment]
Fixed in PR https://github.com/infor-design/enterprise/pull/2217

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
