### ISSUE TITLE
Datagrid all Totals are displayed in initial load even when the group is not collapsed

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2221]
**Describe the bug**
Datagrid all Totals are displayed in initial load even when the group is not collapsed

**To Reproduce**
1. Go to http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouping-totals.html

Notice that groups that is not collapsed are displaying Total

**Expected behavior**
Should only display total if the group is collapsed. 

**Version**
v4.7.0 or v4.18.0

**Screenshots**
<img width="1360" alt="Screen Shot 2019-05-23 at 4 27 12 PM" src="https://user-images.githubusercontent.com/45757016/58238844-932a0f00-7d7a-11e9-84fa-4f663775be4e.png">

**Platform**
All Browser, OS and devices 

**Additional context**
No any other Additional context about the problem here.

**Comment by tmcconechy** [comment]
Issue goes back as far as i can see. I will address this in the datagrid focus tasks as low priority.
I can see that this happens only if the rows are initially closed.

**Comment by brianjuan** [comment]
Also happens when you sort a column.

**Comment by janahintal** [comment]
QA Passed. Thanks. 
Tested in: http://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-totals.html across all browser, OS and devices.
