### ISSUE TITLE
Datagrid: Unable to select a record in after clicking next page

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2222]
**Describe the bug**
Datagrid: Unable to select a record in after clicking next page

**To Reproduce**
1. Go to http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouping-paging.html
2. Click next Page twice (Double click)
3. Should be redirected to Page 3
4. Select 214230

**Expected behavior**
The record must be selected

**Version**
v4.17.0 - v4.19.0

**Screenshots**
N/A

**Platform**
All Browser, OS and devices.

**Additional context**
No any other Additional context about the problem here.

**Comment by tmcconechy** [comment]
@janahintal Im not 100% clear on this. For step 2 you just mean click twice so you get to page three? But even if i do that i do not see any issues.

http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouping-paging.html
- click next twice to page three
- click checkbox for "214230" row
- row is selected just fine?
