### ISSUE TITLE
Datagrid: Can't switch or move columns in Group column groups

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2223]
**Describe the bug**

**To Reproduce**
1. Go to http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html
2. Move 'Product Name' Column at the end <Next to 'Action Item'>
3. Move 'Product Id' Column at the end <Next to 'Product Name'>
4. Try to Move 'Product Name' again in 'Column Group One'

Noticed that the Column Group One header is moved to left with no way to move a column into it again. 

**Expected behavior**
Column Group One should not get cut off and can still move header/column in it. 

**Version**
v4.12.0 - v4.19.0

**Screenshots**
<img width="1361" alt="Screen Shot 2019-05-23 at 6 03 15 PM" src="https://user-images.githubusercontent.com/45757016/58245489-7cd68000-7d87-11e9-8d9e-c6ba1831e64d.png">

**Platform**
All Browser, OS and devices

**Additional context**
No any other Additional context about the problem here.

**Comment by tmcconechy** [comment]
Issue goes back as far as i can see. I will try address this in the datagrid focus tasks, im not sure that there is a good solution for this. Perhaps we would have to limit that the items can only be dragged within the group. Would that work @claudenbach what do you think?

**Comment by tmcconechy** [comment]
Fixed this issue along with #3552 . The way i fixed it was to "pick" one column in each group that cannot be dragged. You need to have one column that always stays in the group or the group will disappear.

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html?theme=uplift&variant=light  across all platform.
