### ISSUE TITLE
Datagrid: Group header appears too large in iOS devices

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2224]
**Describe the bug**
Datagrid: Group header appears too large in iOS devices

**To Reproduce**

1. Using iOS device, Open browser Safari or Google
2. Go to http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouping.html

**Expected behavior**
Header

**Version**
v4.14.0 or v4.19.0

**Screenshots**
Group header text should not appear too large in Devices

**Platform**
iOS 12
iPhone X Max

**Additional context**
No any other Additional context about the problem here.

**Comment by tmcconechy** [comment]
Issue goes back as far as i can see. Will address this in the datagrid focus tasks.

**Comment by tmcconechy** [comment]
Fixed this while testing another issue.

**Comment by janahintal** [comment]
This issue is now resolved. The header is now in normal size in iOS. Thank you. 
Tested in http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouping.html
