### ISSUE TITLE
Datagrid on Modal: Select All column header not working properly

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2225]
**Describe the bug**
Datagrid on Modal: Select All column header not working properly.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com//components/datagrid/example-modal-datagrid.html
2. Click Open Modal button
3. Click the checkbox column header
4. See issue: Not all rows will be selected, only the first row.

**Expected behavior**
All rows should be selected when checkbox column header is checked.

**Version**
- ids-enterprise: v4.17.0 - v4.19.0-beta0

**Screenshots**
<img width="1654" alt="Screen Shot 2019-05-23 at 7 09 22 PM" src="https://user-images.githubusercontent.com/39508864/58248309-5b2cc700-7d8e-11e9-9b4d-0a1a6c22416a.png">

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Issue goes back forever, the example is just incorrect as it has a checkbox column but the selectable: 'multiple' is not set (its set to single select). A simple demo app fix will fix this.

**Comment by brianjuan** [comment]
http://4190-beta1-enterprise.demo.design.infor.com/components/datagrid/example-modal-datagrid.html
Passed QA, tested on all browsers.
