### ISSUE TITLE
Datagrid: Checkbox column header is not updating automatically after removing rows

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2226]
**Describe the bug**
Datagrid with Multiselect: Checkbox column header is not updating automatically after removing rows.

**To Reproduce**
1. Go to 'http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
2. Select 1st, 2nd, and 3rd rows
3. Click Remove button
4. See issue: checkbox column header does not get updated, should be unselected after removing rows.

**Expected behavior**
Checkbox column header should be unselected after removing rows

**Version**
- ids-enterprise: v4.19.0-beta0

**Screenshots**
<img width="1590" alt="Screen Shot 2019-05-23 at 7 19 45 PM" src="https://user-images.githubusercontent.com/39508864/58248992-43564280-7d90-11e9-8b62-da00eda9c99d.png">

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Issue did work in 4.18

**Comment by brianjuan** [comment]
http://4190-beta1-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
Passed QA, tested on all browsers.
