### ISSUE TITLE
Datagrid Paging Client Side: Sorting arrow disappears when changing page

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2228]
**Describe the bug**
Datagrid Paging Client Side: Sorting arrow disappears when changing grid page.

**To Reproduce**
1. Go to http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side.html
2. Click Id column header to sort
3. Click the Next Page button, then Click Previous Page
4. See issue: Sorting arrow icon on Id column header disappears

**Expected behavior**
Sorting arrow icon should stay even after changing grid page.

**Version**
- ids-enterprise: v4.19.0-beta0

**Screenshots**
<img width="1284" alt="Screen Shot 2019-05-23 at 7 40 01 PM" src="https://user-images.githubusercontent.com/39508864/58249957-caa4b580-7d92-11e9-9fbc-9133ed3aae5f.png">

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by janahintal** [comment]
QA Passed. Will Move to Done. 
Tested in: http://4190-beta1-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side.html & http://4190-beta1-enterprise.demo.design.infor.com/components/datagrid/test-paging-select-indeterminate-single.html across all browser & OS.
