### ISSUE TITLE
Datagrid: ellipsis not displaying in expandable row headers

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2229]
**Describe the bug**
Datagrid: ellipsis not displaying in expandable row headers

**To Reproduce**
1. Go to http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row.html
2. Play with row header
3. Play with the last row and expand the row notice that all the row is resizing

**Expected behavior**
- Header text should not be cut off 
- Should not expand all rows when expanding the last column

**Version**
v4.17.0 or v4.19.0

**Screenshots**
<img width="1236" alt="Screen Shot 2019-05-23 at 7 44 45 PM" src="https://user-images.githubusercontent.com/45757016/58250287-a4cbe080-7d93-11e9-9cad-13dce80cf0fb.png">

**Platform**
All browser, OS and Devices

**Additional context**
No any other Additional context about the problem here.

**Comment by tmcconechy** [comment]
In order to have this behavior you need to add `textOverflow: 'ellipsis'` to the column. This example has a mix of this. So just note that not every column is going to overflow to ellipsis unless this is set as its optional.
