### ISSUE TITLE
Datagrid Paging Indeterminate: Checkbox Column Header not working after changing a page

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2230]
**Describe the bug**
Datagrid Paging Indeterminate: Checkbox Column Header not working properly after changing a page.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html#
2. Select the Checkbox column header
3. Click Next Page button, then Click Previous Page button
4. See issue: Try to select and unselect Checkbox column header, now is not working properly.

**Expected behavior**
Checkbox column header should still work properly after changing a page.

**Version**
- ids-enterprise: v4.17.0 - v4.19.0-beta0

**Screenshots**
![paginginde1](https://user-images.githubusercontent.com/39508864/58250658-874b4680-7d94-11e9-9e43-85d2329fc8e1.gif)

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Issue goes back as far as i can see. I will address this in the datagrid focus tasks.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
