### ISSUE TITLE
Datagrid: Filter options dropdown doesn't work if filterConditions takes out the default option

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2234]
**Describe the bug**
If you specify filterConditions on a column that don't include the hard coded default, the filter options dropdown doesn't open and an error is seen in the browser console.

**To Reproduce**
1. Copy [test-filter-lookup-click-function.zip](https://github.com/infor-design/enterprise/files/3212906/test-filter-lookup-click-function.zip) into your codebase. Then navigate to /components/datagrid/test-filter-lookup-click-function.html
2. Click on the filter options next to the lookup for Product Id
3. No dropdown opens, and the error is seen in the browser console.

**Expected behavior**
We have a usecase where a lookup field could be either numeric or alpha. For the numeric case, we don't want to have a 'contains' option available in the filter options. But since it is the default in the code [here](https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L1798) we run into this issue. It would be nice to be able to say what we want as the default.

**Version**

- ids-enterprise: v4.19.0-dev

**Screenshots**
![NumericLookupFilterOptionsProblem](https://user-images.githubusercontent.com/22107636/58264660-d452fc80-7d43-11e9-901b-4cb7db6f657d.gif)

![image](https://user-images.githubusercontent.com/22107636/58264719-f187cb00-7d43-11e9-80ec-2a3f762505df.png)

**Platform**
 - All

**Comment by lipetzan** [comment]
Can we get this into 4.19 beta for the June release

**Comment by marknolaninfor** [comment]
@clepore 
The lookup filtertype is hard coded to have a default value of contains, but an array of filterConditions can be set that does not contain this value. It would be assumed that the first filterContidion would be the default.

For filterButtonHtml every place that is calling renderButton would need to be altered so that the first filterCondition is passed. Then also when the icon is set it should use the first filterCondition.

    if (col.filterType === 'lookup') {
      btnMarkup = renderButton(filterConditions.length ? filterConditions[0] : 'contains')
....
      btnMarkup = btnMarkup.replace('{{icon}}', filterConditions.length ? filterConditions[0] : 'contains');
    }

**Comment by clepore** [comment]
Thanks! @deep7102 is working on it as we speak.

**Comment by janahintal** [comment]
QA Passed. Will move to Done
Verified in: http://4190-beta1-enterprise.demo.design.infor.com/components/datagrid/test-filter-lookup-click-function.html across all browser, OS and devices.
