### ISSUE TITLE
Dropdown: Ellipsis not displayed for long selected items when ids-enterprise-ng is present

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#2236]
**Describe the bug**
The dropdown control does not display ellipsis for long selected items when the control is used via ids-enterprise-ng. This occurs only with the Firefox browser.

**To Reproduce**
1. Implement the dropdown.demo.html and .ts in the attached zip into ids-enterprise-ng or
manually change the states field in dropdown.demo.html to have a long display label for the Delaware option and change the model.single property in dropdown.demo.ts to be 'DE'
2. Run ids-enterprise-ng
3. Click on D > Dropdown - Single-Select
4. The first dropdown, States, should display the issue

**Expected behavior**
Expect the long selected item to be truncated and ellipsis to be displayed

**Version**

- ids-enterprise: v4.19.0-beta.0

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/58267607-95c04080-7d49-11e9-942f-f55e86f8e104.png)

**Platform**
 - Browser Name: Firefox only

**Additional context**
[ids-enterprise-ng.dropdown.demo.zip](https://github.com/infor-design/enterprise/files/3213103/ids-enterprise-ng.dropdown.demo.zip)

**Comment by tmcconechy** [comment]
This is working fine on http://master-enterprise.demo.design.infor.com/components/multiselect/test-select-all.html in FF

I think for one thing that the way the multiselect is done in EP is wrong, it doesnt actually use the multiselect component it just uses settings on the dropdown.

Maybe that can be changed? Given that this is an NG only issue i think we should move this back over there to that project?

**Comment by fitzorama** [comment]
The example is for dropdown only, although I did see that it occurs for dropdown using multi-select.

What I saw during debugging was if sohoxi dropdown updated() called overflowed, then the initial value displayed with the ellipsis.

**Comment by fitzorama** [comment]
I guess I could have used a different long value rather than using Delaware repeatedly.

**Comment by tmcconechy** [comment]
Ok that would be like http://master-enterprise.demo.design.infor.com/components/dropdown/example-tooltips.html then. Maybe its not triggering the code that sets up the tooltip/ellipsis the way its updating?

**Comment by fitzorama** [comment]
The issue can really be seen without any modifications in the dropdown.multiselect.demo in ids-enterprise-ng using Firefox. I believe the issue resolution is in ids-enterprise.

**Comment by fitzorama** [comment]
Here is an ids-enterprise example using the dropdown test-long-text.html with a small modification.

![image](https://user-images.githubusercontent.com/20212079/58275753-6f0b0580-7d5b-11e9-94e8-6c12086e0c44.png)

To duplicate:
1. Replace the test-long-text.html in the ids-enterprise app > views > components > dropdown directory
2. In Firefox, create a new tab (Ctrl-T)
3. Paste http://localhost:4000/components/dropdown/test-long-text.html into the command line
4. Hit Enter
5. The dropdown should display long text without ellipsis

Using F5 to refresh will display the ellipsis, so you will always need to create a new tab to duplicate.

[ids-enterprise-dropdown.test-long-text.zip](https://github.com/infor-design/enterprise/files/3213574/ids-enterprise-dropdown.test-long-text.zip)

**Comment by CindyMercadoReyes** [comment]
This issue passed QA testing. However, another issue was found while testing this ticket.  GitHub ticket: https://github.com/infor-design/enterprise/issues/2465 was created.  Thanks, Cindy
