### ISSUE TITLE
SOHO-7919: [Android Galaxy 8] Filterable Datagrid Control: Alignment Issue with Filter dropdown list box

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#224]
1. http://usalvlhlpool1.infor.com/4.6.0-rc/components/datagrid/example-filter

2. [Android Galaxy 8] Filterable Datagrid Control: Alignment Issue with Filter dropdown list box 

3. Please see screen shot attached

**Comment by tmcconechy** [comment]
Closing along with https://jira.infor.com/browse/SOHO-7919
