### ISSUE TITLE
Application Menu Personalized Role Component: Keyboard Is reversed on lower toolbar

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2240]
**Describe the bug**
Application Menu Personalized Role Component: Keyboard Is reversed on lower toolbar

*edit*: See the comment below on how to address this 💬 

**To Reproduce**
1. Go to URL: http://4190-beta0-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html
2. click on "Find a Coworker"
3.  tab down to the settings
4. arrow left and right
5. Nothing happens with you select the left and and right arrow key. The user should be able to right arrow key to the "Proxy a user" field box

**Expected behavior**
The left and right arrow key should allow the user to highlight the "Proxy a user" and "About this App" 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1202" alt="Application Menu Error" src="https://user-images.githubusercontent.com/39101346/58275693-b1d0db80-7d63-11e9-8c21-8ed5e7d04a12.png">

**Platform**
 - OS Version: [ iOS 8]
 - Browser Name [Chrome]
**Additional context**

**Comment by tmcconechy** [comment]
Im seeing arrow left and right work but they are inversed. The bottom toolbar left and right go one way and the top toolbar they go the other way.

**Comment by clepore** [comment]
We are punting on this issue for now.

**Comment by clepore** [comment]
The solution for this is to add the visual paradigm to the flex toolbar component so that the toolbar can have a "left side" and "right side" grouping.

![image](https://user-images.githubusercontent.com/742319/58280008-bd290480-7d6d-11e9-9d0e-5bdb30d97f83.png)

Per the image above:

```html
<flextoolbar>
    <div class="toolbar-section-left"> <!-- GREEN: This is a left anchored grouping -->
        <button>Settings <i>icon</i></button>
        ...
    </div>
    <div class="toolbar-section-right"> <!-- ORANGE: This is a right anchored grouping -->
        <button><i>icon</i></button>
        <button><i>icon</i></button>
        <button><i>icon</i></button>
        ...
    </div>
</flextoolbar>
```

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html
Passed QA on all Mac and Windows browsers, will retest once beta is deployed.
