### ISSUE TITLE
Datagrid not responsive in Mobile view Portrait mode

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2244]
**Describe the bug**
Datagrid not responsive in Mobile view Portrait mode

**To Reproduce**
1. Open Mobile browser in Portrait view
2. Go to http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/example-comments.html

**Expected behavior**
Should be responsive and be able to scroll horizontally. 

**Version**
v4.7.0 - v4.19.0

**Screenshots**
<img width="369" alt="Screen Shot 2019-05-24 at 10 57 59 AM" src="https://user-images.githubusercontent.com/45757016/58300152-16e40a00-7e14-11e9-8bbd-1d0bd1253cde.png">
<img width="380" alt="Screen Shot 2019-05-24 at 10 58 59 AM" src="https://user-images.githubusercontent.com/45757016/58300157-18adcd80-7e14-11e9-9ffc-2714c1329d13.png">

**Platform**
Windows10 IE 11 responsive view
iOS and Android devices

**Additional context**
No any other Additional context about the problem here.

**Comment by tmcconechy** [comment]
Duplicates #1438
