### ISSUE TITLE
Datagrid is breaking after expanding a cell in mobile

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2246]
**Describe the bug**
Datagrid is breaking after expanding a cell in mobile

**To Reproduce**
1. Open a browser in Mobile Android / iOS
2. Goto http://4190-beta0-enterprise.demo.design.infor.com/components/datagrid/example-expandable-cells.html
3. Expand a cell

Android Portrait mode: Unable to scroll
iOS: Datagrid records did not show up

**Expected behavior**
Datagrid should not break also, should be able to scroll in mobile and in IE 11 responsive view after expanding a cell. 

**Version**
v4.19.0

**Screenshots**
<img width="448" alt="Screen Shot 2019-05-24 at 1 34 38 PM" src="https://user-images.githubusercontent.com/45757016/58305060-52d59a00-7e29-11e9-92a5-edfb9ce71621.png">
<img width="474" alt="Screen Shot 2019-05-24 at 1 35 32 PM" src="https://user-images.githubusercontent.com/45757016/58305062-549f5d80-7e29-11e9-9297-686297dc9f71.png">

**Platform**
- Windows 10 IE 11 responsive view
- Android & iOS devices

**Additional context**
No any other Additional context about the problem here.

**Comment by tmcconechy** [comment]
Descoping this issue for now
