### ISSUE TITLE
Multiselect font size changed after selecting max record in iOS

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2247]
**Describe the bug**
Multiselect font size is getting bigger after selecting max record in iOS

**To Reproduce**
1. Open iOS device
2. Goto http://4190-beta0-enterprise.demo.design.infor.com/components/multiselect/example-index.html
3. Select max record for both State and Town field

Noticed that the font size changed

**Expected behavior**
Font size should not be changed

**Version**
4.19.0

**Screenshots**
<img width="389" alt="Screen Shot 2019-05-24 at 3 29 09 PM" src="https://user-images.githubusercontent.com/45757016/58310662-be276800-7e39-11e9-8f1b-4a804ecc04b1.png">

**Platform**
iOS 12 - iPhone X max

**Additional context**
No any other Additional  context about the problem here.

**Comment by tmcconechy** [comment]
Im not seeing this issue on Browser stack on an IOS X Max. Are you maybe zoomed or anything else?
In the steps for step 2 you mean just open it and select 10 items and close?

**Comment by tmcconechy** [comment]
Was not able to reproduce this.
