### ISSUE TITLE
Dropdown with tooltips: Alignment issue on Mobile

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2248]
**Describe the bug**
Dropdown with tooltips: Alignment issue on Mobile.

**To Reproduce**
1. Open browser in Android and iOS
2. Go to http://4190-beta0-enterprise.demo.design.infor.com/components/dropdown/example-tooltips.html
3. Open the dropdown
4. See issue: dropdown is out of position

**Expected behavior**
Dropdown with tooltip should be in right position on Mobile browsers.

**Version**
- ids-enterprise: v4.17.0 - v4.19.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/58324980-0c992e80-7e5b-11e9-9c0d-8b1061138342.png)

**Platform**
 - Device: Mobile
 - OS: Android and iOS
 - Browsers: All mobile browsers.

**Additional context**
This maybe an example page issue.

**Comment by tmcconechy** [comment]
Not finding any issues but i think @EdwardCoyle should take a look at the place changes and approve.

**Comment by brianjuan** [comment]
http://4190-beta1-enterprise.demo.design.infor.com/components/dropdown/example-tooltips.html
Passed QA on all mobile browsers.
