### ISSUE TITLE
SOHO-7918: [Win 7 FF 59] Filterable Data Grid Control: Activity and Status field box alignment issue

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#225]
1. http://usalvlhlpool1.infor.com/4.6.0-rc/components/datagrid/example-filter

2. [Win 7 FF 59] Filterable Data Grid Control: Activity and Status field box alignment issue

3. Please see screen shot attached

**Comment by tmcconechy** [comment]
This was fixed along with https://jira.infor.com/browse/SOHO-7444
