### ISSUE TITLE
App menu: Uplift design needs to cascade through the nesting

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#2255]
**Describe the bug**
Alignment issue with app menu and tree in accordion panel

**To Reproduce**
A new example will need to be created

**Version**
- ids-enterprise: v4.19.0-beta.0

**Screenshots**

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1012017/58344999-418a8e80-7e25-11e9-93fd-a1d04985aca8.png)

**Comment by brianjuan** [comment]
http://4190-beta1-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=uplift&colors=7025B6
Passed QA testing on all browsers.
