### ISSUE TITLE
Editor: H3 and H4 overwrites other styling in Edge but not in Chrome

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#2256]
**Describe the bug**
Minor, but currently the Editor works a little differently in Edge (+ IE11) compared to Chrome. In Edge when you have styled some text and then choose to style it with H3 or H4 all other styling are lost, but in Chrome when you have styled some text and then choose H3 or H4 the other styles are still applied.

**To Reproduce**
In Edge and Chrome:
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index
2. Add A new line and and some test text
3. Select the text
4. Make it Bold, Italic, Underlines, Strike through and color it
5. Click H3 (or H4)
6. See the result

**Expected behavior**
I'm not fully sure what is the expected behaviour (If edge or Chrome does it right). In word it seems all "before styling" is lost when applying a Heading style so perhaps that is the expected behavior? But Edge (and IE11) and chrome should handle it equally.

**Version**
- ids-enterprise: v 4.18.1

**Screenshots**
-

**Platform**
 - OS Version: Win 10
 - Browser Name: Chrome & Edge
 - Browser Version: Version 74.0.3729.157 (Official Build) (64-bit) &
Microsoft Edge 44.17763.1.0, Microsoft EdgeHTML 18.17763

**Additional context**
-

**Comment by tmcconechy** [comment]
It may be not so easy to address this as its a content editable so the browsers may vary this depending on implementation. Somewhat related https://github.com/infor-design/enterprise/issues/391

**Comment by tralarn** [comment]
What is the status for this issue?

**Comment by tmcconechy** [comment]
Status: No time for this yet.

I suggest we fix this by first striping the style and then applying the Headers (so chrome behaves like IE 11 does). But this seems like a minor edge case.

That should be simple enough since we have the ability to clear style first before applying the header.

Putting this in the next spring bucket for now.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
