### ISSUE TITLE
Personalize: Personalization overlay doesn't go away when managing own style sheets

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2258]
**Describe the bug**
The way landmark is doing their own themes the overlay can remain after recent changes.

**To Reproduce**
1. Go to http://usspnppatton.infor.com:8080/hcm/EmployeeSelfService/home?csk.cli=true&csk.showusingxi=true&csk.HROrganization=7004
emp02/lawson
2. Click refresh a number of times and you'll see the entire browser screen just looking gray.
3. If you look at the elements you'll see personalize-overlay is still there, delete it and the app displays.

**Expected behavior**
ctrl-shift-refresh causes it to work, but just browser refresh a couple times causes it to fail it doesnt seem like we need to insert the style sheet and overlay again if its already there.

**Version**
- ids-enterprise: [v4.19.0]

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/814283/58482659-c4b12a80-812c-11e9-9f5e-0b7ef2bb3060.png)

**Additional context**
Also seeing issues with:
- the color picker setting the wrong classes
- the class in the head being wrong.

**Comment by tmcconechy** [comment]
Branch `personalize-runner` needs a bit more work.

**Comment by brianjuan** [comment]
http://4190-beta1-enterprise.demo.design.infor.com/components/personalize/example-form.html?theme=uplift&variant=dark
http://4190-beta1-enterprise.demo.design.infor.com/components/colorpicker/example-index.html
Passed QA, tested on all browsers.
