### ISSUE TITLE
Personalize: Uplift personalize-text styles overriden by important

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#2259]
**Describe the bug**
Using `.personalize-text` class should override existing text styles. This issue is caused by a poor definition in the uplift stylesheet.

**To Reproduce**
1. Go to http://4190-beta0-enterprise.demo.design.infor.com/components/personalize/example-form2.html?theme=uplift&colors=7025B6

**Expected behavior**
Anything with `.personalize-text` should always take the personalize color

**Version**

- ids-enterprise: v4.19.0-beta.0

**Screenshots**

![image004](https://user-images.githubusercontent.com/1012017/58489414-41e29c80-8139-11e9-8968-8a7ed62bf407.jpg)

**Comment by brianjuan** [comment]
http://4190-beta1-enterprise.demo.design.infor.com/components/personalize/example-form2.html?theme=uplift&colors=7025B6
Passed QA on all browsers.
