### ISSUE TITLE
Colorpicker is not shown correctly in smaller viewport

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#2266]
**Describe the bug**
If I try to use a colorpicker in a window that is not so high or slim the colors are rearranged even though the dialog could be larger so that it could look as usual.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/colorpicker
2. Make the browser a little slimmer, so the frame is a little bit smaller. (For example 7742 pixels)
3. Click the Colorpicker

Steps to reproduce 2:
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/colorpicker/example-index
2. Make the browser really short
3. click the color picker
4. See the error

**Expected behavior**
1. Since the view aren't really that small, it should be possible to show the color picker as large as it usually is and show the colors as usual.
2. Here there is alot of room horizontally and it seems strange that it drags one color down to the next line when it's the height and not the width that is the problem.

**Version**
- ids-enterprise: v 4.18.1

**Screenshots**
1. 
![image](https://user-images.githubusercontent.com/8664975/58556424-5055b480-821c-11e9-8c19-1d205c9c25fb.png)

2. 
![image](https://user-images.githubusercontent.com/8664975/58556522-83984380-821c-11e9-9ade-4831331c537a.png)

**Platform**
 - OS Version: windows 10
 - Browser Name: Chrome
 - Browser Version: Version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**
-

**Comment by tralarn** [comment]
What is the status for this issue?

**Comment by tmcconechy** [comment]
Status: Seems minor. But perhaps we can address the position and color behavior for better mobile support. Not sure what a solution would look like but we can discuss with who ever picks this up.

Putting in the next to next sprint bucket for now.

**Comment by SofiK** [comment]
In this case I think the strange thing is that it's not wide enough since it has room to be so.

**Comment by tmcconechy** [comment]
You do have some size options you could use https://design.infor.com/code/ids-enterprise/latest/demo/components/colorpicker/example-sizes.html

**Comment by SofiK** [comment]
oh yes, I realize I wrote my comment a bit unclear. I meant the dialog that is opened when I click it, could become wider to add room for the scrollbar :)

**Comment by ericangeles** [comment]
@tmcconechy looking at it, seems fixed already.

**Comment by SofiK** [comment]
Yes it's possible to reproduce by making the window as short as possible so
that a vertical scroll appear.

For example here in design.infor.com
[image: image.png]

Den tors 16 apr. 2020 kl 17:07 skrev Tim McConechy <notifications@github.com

**Comment by jbrcna** [comment]
**QA Passed**
moving this ticket to Done
v4.28.0-dev
