### ISSUE TITLE
Editor: Shouldn't anchor url field be required?

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#2268]
**Describe the bug**
Minor! When inserting an anchor in the Editor it is possible to leave the url field empty. Shouldn't it be a required field?

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index
2. Go to a new line
3. Click Insert anchor
4. Empty the url field
5. Click Insert
=> http:// is added to the editor

**Expected behavior**
I think it should not be possible to click Insert when the URL field is empty.

**Version**

- ids-enterprise: 4.18.1

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/58566836-9701d980-8231-11e9-9969-b149bfec18bd.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**
-

**Comment by tmcconechy** [comment]
We can probably set the modal to work like http://latest-enterprise.demo.design.infor.com/components/modal/example-validation.html

**Comment by tralarn** [comment]
What is the status for this issue?

**Comment by tmcconechy** [comment]
Status: Did not have time yet, but added to the next to next sprint bucket.

**Comment by tmcconechy** [comment]
Added fix for this in the current fix im doing in here... will push soon

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
