### ISSUE TITLE
Datagrid: Improve calculateTextWidth for various editor types

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2270]
**Describe the bug**
calculateTextWidth can under estimate the required width for the following editors
* Lookup
* Date
* Time
* Dropdown
* Spinbox 
* Colorpicker

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/test-calculateTextWidth.html'
* Check the trigger icons for the Lookup, Date, Time
* The Dropdown does not display the the full label for the field
* The spinbox and color picker are not sized correctly

**Expected behavior**
The function is improved to allow for these editors to automatically calculate the minimum width required to display.

**Version**
4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/58600223-e6441a80-82c2-11e9-9c5b-ceeff13c31fd.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome

**Additional context**
The formatters could actually skip the dataset and calculate the actual max width
* Date (Pass a date to the Formatter double digit days and month, eg last day of this year)
* Time (Pass a date to the Formatter, eg last second of today)
* Dropdown (Find the longest option label and pass that value)
* Spinbox (Find the largest and smallest for negatives and pass that to the formatter)
* Colorpicker 

This should then calculate faster, at least for larger datasets.

**Comment by marknolaninfor** [comment]
The header needs to calculate the width with its font, as the first lookup column would have used the header as it contains more characters, but its render width would actually be less that required for the lookup.

Requiring some feedback 
* if the date and time fields when editable should calculate with on the values in the dataset vs max possible width value.
* Any improvements to the padding to align the trigger icons (lookup, date, timepicker)
* When the grid is filterable any improvements to the calculation, as this is still the original code.

There is also a potential issue when changing a setting that affects the header, as updated only renders the rows, and if the pager state is still set to inital then the output is different compared to paging and then using updated.

![image](https://user-images.githubusercontent.com/39749678/58684524-b9256400-83b7-11e9-9d0b-8e9ece79fcc5.png)

We don't use updated so it does not affect us, but other may be writing code to overcome this.

**Comment by janahintal** [comment]
QA Passed. Will move to done. 
Tested in: http://master-enterprise.demo.design.infor.com/components/datagrid/test-calculate-text-width.html across browsers.
