### ISSUE TITLE
Popover: Button overflows container

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#2271]
**Describe the bug**
The button inside the popover overflows it's container at small screen sizes.

**To Reproduce**
- Run demo app
- Visit http://localhost:4000/components/popover/example-alternate-positions.html or http://localhost:4000/components/popover/example-index.html 
- Reduce screen size to mobile
- Click either button
  - notice the "Apply" button overflows it's container

**Expected behavior**
I expect the popover to be contained to the dimensions of the device and for the button to not overflow it's container.

**Version**
v4.20.0

**Screenshots**
<img width="333" alt="bug" src="https://user-images.githubusercontent.com/7952168/58623769-b84bdf80-829c-11e9-8e7e-cf82a2930e5d.png">

**Platform**
 - iPhone 5/SE (simulated in Dev Tools on Chrome Desktop)
 - MacOS 10.14.5
 - Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Additional Context**
First reported here: https://github.com/infor-design/enterprise/pull/2267#issuecomment-497118814

**Comment by tmcconechy** [comment]
Similar to https://github.com/infor-design/enterprise/issues/1576

**Comment by brianjuan** [comment]
https://master-enterprise.demo.design.infor.com/components/popover/example-alternate-positions.html
https://master-enterprise.demo.design.infor.com/components/popover/example-index.html
Passed QA testing, button now remains inside the popover, with the entire popover displaying correctly on iOS and Android. Will retest once beta is deployed.
