### ISSUE TITLE
Tabs - Unable to apply personalization to only the tab-list

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2277]
**Describe the bug**
I want to personalize just a tab-list and not the tab panels. 

**To Reproduce**
1. Download updated example-form2.html attached to this issue.
2. Open that screen and see white info-message below tabs.

**Expected behavior**
Right now is-personalizable is required on a parent div personize-header. If that could be updated for tabs to allow the same element for these classes that would seem a decent solution.
For Example:
```
      <div class="tab-container header-tabs is-personalizable personalize-header">
        <div class="tab-list-container scrollable-y"><ul class="tab-list"></ul></div>
      </div>
      <div class="tab-panel-container scrollable-y">
        ...
      </div>
```

**Version**
- ids-enterprise: 4.19.x

**Screenshots**
Notice in the tab panel 
![image](https://user-images.githubusercontent.com/4737815/58645084-3d002300-82c8-11e9-978b-5b9272999186.png)

**Platform**
 - OS Version: winodws 10
 - Browser Name: chrome
 - Browser Version: Version 74.0.3729.169 (Official Build) (64-bit)

**Update Example Attached**
[example-form2.html.txt](https://github.com/infor-design/enterprise/files/3237723/example-form2.html.txt)

**Comment by tmcconechy** [comment]
CC @pwpatton

**Comment by janahintal** [comment]
Hi @tmcconechy , unable to test in iOS and Android devices. The page http://4190-beta1-enterprise.demo.design.infor.com/components/personalize/example-form3.html won't scroll down. Thus, we could not verify the alert text at the bottom. Thanks.

**Comment by janahintal** [comment]
QA Failed. From header did not changed after changing theme to Dark or High Contrast. 
**In IE11 Windows 10**
Steps:
1. Change Personalization to Emerald
2. Change Theme to Dark
<img width="1456" alt="Screen Shot 2019-06-06 at 1 52 31 PM" src="https://user-images.githubusercontent.com/45757016/59010073-9e913600-8862-11e9-9143-5d2aaa463211.png">

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. 
Tested in: http://4190-rc0-enterprise.demo.design.infor.com/components/personalize/example-form3.html
http://localhost:4000/components/personalize/example-classes.html?theme=uplift
http://localhost:4000/components/personalize/example-form.html?theme=uplift
http://localhost:4000/components/personalize/example-form2.html?theme=uplift
http://localhost:4000/components/personalize/example-form3.html?theme=uplift
http://localhost:4000/components/components/personalize/example-form4.html?theme=uplift
http://localhost:4000/components/components/personalize/example-form4.html?theme=uplift
Across all OS, browser & devices
