### ISSUE TITLE
Question: can we use the command 'require' in NODE JS?

### ISSUE THREAD

**Issue by thun88** [infor-design/enterprise#2286]
Hi Infor Design Staff
This is Wen-Long from Italy (CDM Tecnoconsulting, INFOR Partner)
I have a question about **Infor Design**:

1.  Can we use the command '**require**' inside the NODE JS CODE? 
2.  And then use the webpack for use the package?

We have also tested the NPM RUNKIT online, but it seems there are some errors and doesn't run.
https://npm.runkit.com/ids-enterprise

Thank you in advance
Best
Wen-Long

**Comment by clepore** [comment]
Hi @thun88 ,

In general, Enterprise is currently designed to be included as a `<script>` tag in a website/app by way of download or source from our cdn.  It is not setup to run with `require()` in a NodeJS environment, but it is something we are considering in the distant future.

Cheers!

**Comment by tmcconechy** [comment]
Closing as answered. It wouldnt be possible to run IDS in node as its a front end browser component library. We also use Rollup not Webpack for our bundling. Webpack may be possible but we chose the later so havent done much work making Webpack work and we dont have any specific plans to change that right now.
