### ISSUE TITLE
Modal: Keyboard focus can be set outside of modal content?

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#2287]
I'm not entirely sure this if this is a bug. More of a question.

**Description**
When opening a modal / contextual action panel, it's possible to focus elements outside of the modal content area. However, this only seems to be possible if the app / page is within an iframe. Is this some kind of known limitation?

**To Reproduce**
* Open https://design.infor.com/code/ids-enterprise/latest/modal
* Click Show Modal button
* Mouse click outside of the modal on the overlay
* Tab a few times
Result: The Show Modal button can be focused

However, it's not possible here (non-iframed)
https://design.infor.com/code/ids-enterprise/latest/demo/components/modal/example-index

Since our app is iframed, it becomes an issue with all modals. Content outside can reached by tabbing and actions can be performed that shouldn't be possible with the modal opened.

Just wondering if you have any idea about this, or if something can be done to solve this for iframed content as well?

**Comment by tmcconechy** [comment]
It might be possible if you do something like add an overlay when the modal is open over the non iframe area? If its on the same domain perhaps the modal code can extend the overlay over the iframe but its going to be messy i think. 

This is one of the normal types of issues you see with iFrames in general. But if this prevalent might be something worth exploring in the future.

**Comment by volante007** [comment]
The whole content is in an iframe, and the modal overlay covers the content as designed (and is part of the iframed domain too). So to clarify, in the reproduce steps, I'm referring to the complete example app (not everything around it outside of iframe):  

![image](https://user-images.githubusercontent.com/1101770/58716362-242b6680-83c9-11e9-9e98-e3c6d81caf65.png)

The elements that can be focused outside of the modal are all part of the same iframed content. But perhaps the "modal rules" (aria-modal="true", role="dialog") doesn't really work under these circumstances.

**Comment by tmcconechy** [comment]
OK then that would be a bug but im not seeing it in chrome. both tab and shift tab keep me in the modal on https://design.infor.com/code/ids-enterprise/latest/modal but i think someone did mention this before so would be nice to track this down.

**Comment by volante007** [comment]
Yes if you tab / shift tab when modal is opened, focus will stay in the modal. But if you click anywhere outside of the modal (on the overlay), and tab a few more times, focus will end up on the Show Modal button after a while (at least for me in Chrome)

**Comment by tmcconechy** [comment]
OK i see , yeah i think we make this into a bug

**Comment by tralarn** [comment]
What is the status for this issue?

**Comment by tmcconechy** [comment]
Status: Did not have time yet, but added to the upcoming sprint.

**Comment by EdwardCoyle** [comment]
@volante007 - PR #3633 fixes part of this issue, but the other part isn't something we can really address due to the nature of `<iframe>` and sandboxing.  I was able to replicate your issue in the new test present on that PR, and fixed the portion where clicking the overlay, followed by pressing tab, would not correctly focus within the modal.  However, if you click outside of the iframe region and attempt to use the Tab key, focus may still not occur on the correct elements.

**Comment by EdwardCoyle** [comment]
Digging a little deeper on this, there are related focus traps that were present before my changes that I'm going to address as part of this.  For example: https://master-enterprise.demo.design.infor.com/components/modal/test-popover.html

- Open the Modal
- Open the Popover
- Focus the hyperlink/button/etc inside the Popover and use the keyboard to tab around.  Focus will eventually go back to the Modal, but can never escape the modal to go back to the open Popover.

Stuff like that is present in any "popover"-style component that can be placed in the Modal (think Dropdown, Popupmenu, etc).  Going to fix them all as part of this issue.

**Comment by janahintal** [comment]
This is now working as expected. Will now move to Done. Thanks!
