### ISSUE TITLE
Field Filter: Dropdown filter triggers native select over IDS style

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#2288]
**Describe the bug**
The dropdown select reverts to a native version when the In Range filter is chosen. This only happens on dropdown.

**To Reproduce**
1. Visit http://localhost:4000/components/field-filter/example-index.html
2. Click open the filter on the last Dropdown
3. Select "In Range"
4. Notice the Dropdown defaults back to a native dropdown

**Expected behavior**
I would expect it to maintain the styling as with other filter choices.

**Version**
v4.19

**Screenshots**
![dropdown-filter](https://user-images.githubusercontent.com/7952168/58722299-182dad80-83a5-11e9-94f4-7dc7c9b3ceef.gif)

**Platform**
All

**Comment by tmcconechy** [comment]
Broken since 4.10 noted but seems bad.
