### ISSUE TITLE
SOHO-7351: Datagrid row reorder breaks in IE11

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#229]
The row-reorder functionality of the datagrid breaks after moving a few items around. Only happens in IE11.

Reproduce:
- Go to http://usalvlhlpool1.infor.com/4.4.0-rc/components/datagrid/example-row-reorder.html
- Move items around 2-4 times.
_issue occurs here_

Expected: It's possible to reorder rows.
Actual: It's not possible to reorder rows.

![datagrid-sort-bug](https://user-images.githubusercontent.com/7952168/47090041-0ae5f900-d1f0-11e8-9245-b77324d210d7.gif)

**Comment by davidcarlsonberg** [comment]
Tested thoroughly in IE11 on Windows 8.1 using VirtualBox and can't reproduce.

**Comment by tmcconechy** [comment]
Ok, Perfect!

**Comment by brianjuan** [comment]
Can't also reproduce on IE11 using BrowserStack, will now move this to Done.
