### ISSUE TITLE
Datagrid: Performance of Table Export methods are significantly slower since 4.4.0 version

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#2291]
**Describe the bug**
We recently upgraded from SoHo Xi 4.4.0 to 4.14.0 and shipped this to our customers. They have reported back that the "Export to Excel" of table data "hangs". On investigation, we found that the problem was with large data sets (approx 1000 or more records) and that the processing of these records seems to take much longer in SoHo Xi 4.14.0 than in SoHo Xi 4.4.0, which, to the user, appears like the screen is hung as the CPU use is maxed out. This performance issues is still occurring in the latest 4.18.1 version. This issue has been raised on Infor Xtreme and support are involved.

For example, in the old code, an export of 2000 records takes 9 seconds in Chrome, but in the latest code it takes 137 seconds. Customers are using much larger data sets than this.

I will attach an example HTML file that contains calls to the exportToExcel and exportToCSV methods in the latest SoHo Xi version, along with a call to the old 4.4.0 code for comparison. The table is built using a loop to duplicate 2000 records, then use the buttons on the top of the page to export using the different methods. Time taken is written to alert box on completion and to the console, if open.

**To Reproduce**
1. Use the attached example
2. Click on Export
3. Compare speed to 4.4.0

**Expected behavior**
Should be near as fast as 4.4.0 if possible

**Version**
- ids-enterprise: [e.g. v4.14.0]

**Platform**
 - Browser Name [chrome] but others tested / same issue

**Additional context**
It looks to me that by changing to arrays, instead of strings, it has caused this performance issue.

**Comment by sanx72** [comment]
[testPage.zip](https://github.com/infor-design/enterprise/files/3246785/testPage.zip)

**Comment by tmcconechy** [comment]
We'll take a look, i knew it would be a bit slower we had to change this to work differently because of the frozen columns feature. With that there is several tables that need to be combined.

**Comment by janahintal** [comment]
Hi @tmcconechy. I have tested this in https://master-enterprise.demo.design.infor.com/components/datagrid/test-export-performance.html across all browser. Noticed that in IE11, it takes me 5 seconds to download the file without showing a spinner or loading state. Would like to ask if this is acceptable in your end.

**Comment by tmcconechy** [comment]
Yes IE is always much slower so there is nothing we can do about that.

**Comment by janahintal** [comment]
> Yes IE is always much slower so there is nothing we can do about that.

Thanks Tim, already tested this. Will move  this to Done.
