### ISSUE TITLE
Tabs: Having some issues with tab fadeout boundary colors and default color

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2298]
**Describe the bug**
Having some issues with tabs and personalize-header (landmark context form) defaulting the color.

**To Reproduce**
1. Go to http://localhost:4000/components/personalize/example-form3.html
1. Reduce the menu so the tabs overflow 
1. Pick a color in the menu
1. Notice the tab left and right have a wrong color

Also
1. Go to http://localhost:4000/components/personalize/example-form3.html
2. Type `Soho.personalization.setColorsToDefault()` in the console.

**Expected behavior**
Setting the color should work in the tabs example. And setColorsToDefault should add the azure colored header classes
for uplift or soho respectedly. We would set our style sheet and then call either `setColor('800000')` `setColorstoDefault()`.
So use setColor to set a color and setColorstoDefault to default back to azure with a dark app menu in the light theme for example.

**Version**
- ids-enterprise: [v4.19.0]

**Screenshots**
uplift with default color both left and right fade out pseudo elements look correct
![image](https://user-images.githubusercontent.com/4737815/58833781-73ff6d00-8617-11e9-81d8-db34e7abf3fb.png)

Change to a different color (other than azure) and the left and right fade out pseudo elements look incorrect. Left seems to change to azure and right seems to keep the default.
![image](https://user-images.githubusercontent.com/4737815/58833872-a4dfa200-8617-11e9-8818-e90750ac508d.png)

The theme doesn't seem to matter (soho or uplift), just the color. Here's soho light with emerald color chosen.
![image](https://user-images.githubusercontent.com/4737815/58834021-ea03d400-8617-11e9-8e00-efb696f430ec.png)

**Additional context**
http://localhost:4000/components/personalize/example-form.html
http://localhost:4000/components/personalize/example-form2.html work ok

**Comment by tmcconechy** [comment]
Been working on isolating this problem with Phillip. Should be fairly straightforward to solve.

**Comment by clepore** [comment]
Also noting we need to fix some other quirks by migrating the new themed header styles, into the default css so those styles also exist w/o personalization being active.

**Comment by janahintal** [comment]
QA Failed for all uplift theme in IE 11 browser. Please se below screen shot. 
Change the personalization to Emerald, then the mode to Dark Mode. 
http://4190-beta2-enterprise.demo.design.infor.com/components/personalize/example-form3.html
http://4190-beta2-enterprise.demo.design.infor.com/components/personalize/example-form3.html
http://4190-beta2-enterprise.demo.design.infor.com/components/personalize/example-form3.html


<img width="612" alt="Screen Shot 2019-06-06 at 4 49 52 PM" src="https://user-images.githubusercontent.com/45757016/59019884-69dda880-887b-11e9-82da-937661f9ce94.png">

**Comment by brianjuan** [comment]
Passed QA testing, issues found on IE are now also fixed.
