### ISSUE TITLE
Datagrid: Search on Personalize Columns not working

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise#2299]
**Describe the bug**

The search box on the in-built personalize columns dialog is not longer filtering the list of columns present in the associated dialog.  It is highlighting the matching letters.

**To Reproduce**

Clone the master repo of enterprise.

```sh
npm i
npm run start
```

Then navigate to `http://localhost:4000/components/datagrid/test-save-settings.html`. 

Open the DataGrid option menu, and select Personalize.

Enter text into the search field.

**Expected behavior**

When entering text I would expect the list of reduce as appropriate.

**Version**

v4.19 (beta.0 and 1)

**Screenshots**

![image](https://user-images.githubusercontent.com/8340092/58881998-3fe98200-86d3-11e9-9222-5971e68c7299.png)

**Platform**
 - Windows and Mac
- Chrome and IE11

**Additional context**

**Comment by janahintal** [comment]
QA Passed. Will Move to Done.
Tested in: https://master-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html?theme=soho&variant=contrast across all browser, OS and devices.
