### ISSUE TITLE
Datagrid: Does Not Equal filter is incorrect

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#2301]
**Describe the bug**
When filtering the Quantity column on Does Not Equal and including a number that exists, the filtering is inaccurate and does not show those cells/rows that Do Not Equal the provided value.

**To Reproduce**
1. Visit http://localhost:4000/components/datagrid/test-save-settings-serverside.html
2. Filter the Quantity column on Does Not Equal and type a number that exists in a cell in that column.
3. Notice the column is not filtered against that number and filter option.

**Expected behavior**
I expect Quantity to correctly filter the column contents on "Does Not Equal"

**Version**
4.19

**Screenshots**
![doesnotequal](https://user-images.githubusercontent.com/7952168/58884063-a360b900-86ad-11e9-9421-8f2e6c978dd9.png)

**Platform**
 - MacBook Pro
   - MacOS 10.14.5
 - Chrome
   - Version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**
First reported here: https://github.com/infor-design/enterprise/pull/2293#pullrequestreview-245445316

**Comment by marknolaninfor** [comment]
@davidcarlsonberg @tmcconechy 
The server dataset is empty for the request

/api/compressors?pageNum=1&pageSize=10&sortId=quantity&sortAsc=true&filterValue=1&filterOp=does-not-equal&filterColumn=quantity

Looking at the code for app\data\compressor.js this api is only coded to work for equals and contains.

**Comment by tmcconechy** [comment]
Yes, Since our data is static i on purpose just made it work on a few of the columns. We could improve this test API but i didn't find it critical at the time. That is the right spot for the fix 👍

**Comment by janahintal** [comment]
Hi @tmcconechy, noticed that there are decimal values in QTY column. However, I could not filter a decimal value. I'm done testing in https://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings-serverside.html just haven't tried to filter those that are with decimal values. Should this be in another ticket?

**Comment by tmcconechy** [comment]
I think thats two minor of an issue to raise so i just fixed in it this PR https://github.com/infor-design/enterprise/pull/2401 its just a configuration in the datagrid example
