### ISSUE TITLE
Multi-select issue for datagrid with expandable row

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#2302]
**Description**
For a datagrid with expandable row, shift + click to select multiple rows is not working as expected. If trying to select first two rows, three get selected. If trying to select first four rows, seven get selected. 

The expandable row markup is also a ``<tr>`` element, so it seems that the selection takes these into account as well.

GIF demonstrating the issue
![multiselect](https://user-images.githubusercontent.com/1101770/58799780-7dcca480-8606-11e9-8a77-401144fd34c7.gif)

**To Reproduce**
1. Change gridOptions in app/datagrid/datagrid-mixed-selection.demo.ts to use
```
selectable: "multiple",
expandableRow: true
```
2. Run sample
3. Check / select first row
4. While holding SHIFT key, select third row

**Expected behavior**
Rows 1-3 get selected

**Actual behavior**
Rows 1-5 get selected

**Version**
- ids-enterprise-ng: v5.3.0

**Comment by tralarn** [comment]
What is the status for this issue?

**Comment by tmcconechy** [comment]
Status: No time yet for this but will add to next sprint.

**Comment by jbrcna** [comment]
QA PASSED. verified in master. Will retest once beta is deployed
v4.27.0-dev
