### ISSUE TITLE
DataGrid: Lookup with a mask doesn't display value in IE11

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2305]
Describe the bug
A column with a lookup and mask options, does not display the returned lookup value into the cell when using IE11.  Works fine with Chrome.

To Reproduce

1. Using the attached test-lookup-with-mask.html
2. Click on 'Add Row (top)' 
3. Click on the Product Id cell for the new row
4. Click on the lookup icon to open the lookup selection window
5. Select one of the rows (note the Product Id value)
6. Product Id selected is not displayed in the cell

Expected behavior
Product Id value is displayed in the cell as it does with Chrome.

**Comment by claudenbach** [comment]
[Git-2305.zip](https://github.com/infor-design/enterprise/files/3253258/Git-2305.zip)

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-lookup-with-mask
http://master-enterprise.demo.design.infor.com/components/datagrid/test-lookup-with-mask

Passed QA testing, moving to Done. Will retest once beta is deployed.
![image](https://user-images.githubusercontent.com/39508864/63335624-4c938300-c370-11e9-95e0-09f50a3028d7.png)
