### ISSUE TITLE
SOHO-5888: Multiple display issues when datagrid inside tabs and other containers

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#231]
When a datagrid is inside of certain containers (2-column layout, tabs, expandable areas, etc.), there are the following display issues:

1. Multiselect checkbox is not vertically aligned in middle
2. Drag handle bars don't display at all or display too large
3. Dropdown filter arrow icon is positioned very low

See attached screen shots. I will submit an example too. Please test dark theme too.

I believe the issue is caused by the *font-size: 0* or other font-size css rules on these containers.

**Comment by tmcconechy** [comment]
This was closed on https://github.com/infor-design/enterprise/pull/275

**Test Steps**:
http://localhost:4000/components/datagrid/test-in-containers.html
- Open the above page, Check the vertical and horizontal alignment of the checkbox. It should be centered
- Dropdown icon should be vertically centered on the right side.
- Handle icon should be properly display
