### ISSUE TITLE
DataGrid: Row and cell indicators overlap cell value

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2312]
Describe the bug
The row status indicator and the cell dirty indicator overlaps the value in the cell.  Making the cell value difficult to read.

To Reproduce

1. Using the attached test-overlaps-row-cell-indicators.html
2. Click on the 'Add Row (top)'
3. Click on the Product Id cell for the new row
4. Click on the lookup icon to open the lookup selection window
5. Select one of the rows

Notice that the row indicator and cell indicator overlaps the value in the cell.  
![Screen Shot 2019-06-04 at 2 58 03 PM](https://user-images.githubusercontent.com/814283/58906093-2cd9b080-86d9-11e9-8368-b73e51222c78.png)

Expected behavior
Cell value should be fully visible.

**Comment by claudenbach** [comment]
[Git-2312.zip](https://github.com/infor-design/enterprise/files/3254078/Git-2312.zip)

**Comment by claudenbach** [comment]
Manually changing the width of the column does not fix the issue.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-overlaps-row-cell-indicators.html#
http://master-enterprise.demo.design.infor.com/components/datagrid/test-overlaps-row-cell-indicators.html
Passed QA on all browsers.
![image](https://user-images.githubusercontent.com/39508864/63249637-77aca280-c29c-11e9-9b05-3d7064def1c9.png)
