### ISSUE TITLE
Datagrid: Request a mechanism to constrain a column width

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2313]
Describe the feature:
In Landmark, the column widths are not set.  We want the columns width to adjust to the data being loaded into the grid. However if the datagrid contains a rich text column, there is no way to constrain the column width.  So if the rich text column contains a large amount of data the column width becomes huge.  

Here's our issue....  
A list contains a column with a cardview and a column with a text area.  They want the text area column to wrap, showing only the number of lines of data as the cardview.   So if the cardview is two lines, they want the text area to wrap to the two lines.  If more text exists than can be displayed in two lines, then an ellipsis is shown with a tooltip showing the complete value.  Today, the text area column expands to display the entire value making the column width HUGE when it contains a large amount of data.  I tried setting column.width = 200, but if this column is the last column it doesn't stretch to fill the remaining space.  And column.maxWidth is not available.

**Describe the solution you'd like**
Provide something like column.maxWidth where we can suggest the largest width size of a column.

**Describe alternatives you've considered**
Tried using column.width, but if this column is the last visible column in the list it doesn't stretch to fill the remaining space.

Additional requirement:
Need to support showing up to x number of characters in a cell, the full value would be shown via a tooltip.

Landmark LPL for this is:
show up to x characters

Additional requirement:
Need to support showing up to x number of lines of data in a cell, the full value would be shown via a tooltip.

Landmark LPL for this is:
use text area of 3 lines

**Comment by claudenbach** [comment]
![Git-2313](https://user-images.githubusercontent.com/39804038/58910424-1896b300-86db-11e9-8ef6-9da562b6cc65.gif)

**Comment by marknolaninfor** [comment]
max and min values should both be available, so that a column width can be force to fall within an acceptable range. 

"I tried setting column.width = 200, but if this column is the last column it doesn't stretch to fill the remaining space."

@claudenbach 
You could set the stretchColumn to another columnId other than 'last' and allow that column to stretch and fill the remaining space. This may allow you to overcome some of the issues until this ticket has been completed.

**Comment by janahintal** [comment]
Hi @EdwardCoyle , noticed that when trying to erase the value of the description, the height changes and when trying to highlight text that I will delete, it is not being deleted. Please see below image
![image](https://user-images.githubusercontent.com/45757016/60085989-e245d400-976c-11e9-98f0-ec1d391ae5c3.png)
![image](https://user-images.githubusercontent.com/45757016/60086047-fb4e8500-976c-11e9-9ab8-71323e2424b2.png)

**Comment by tmcconechy** [comment]
@janahintal This is the correct behavior the comments fields can be configured to grow or change in size. So i dont consider this a bug. Please review excluding that issue

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks
Tested in: https://master-enterprise.demo.design.infor.com/components/datagrid/test-columns-min-max-widths.html across all browser and OS.
