### ISSUE TITLE
Datagrid: Restore Columns should restore columns hidden in the dialog

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2315]
**Describe the bug**
Restore columns should also restore columns hidden in the personalize dialog.

**To Reproduce**
1. Go to http://4180-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html
3. Open Personalize Columns
4. Hide all but two columns
5. Reload Page
6. IN the .. menu select reset to default

**Expected behavior**
Should go back to however the original columns based to the grid are.

**Version**
- ids-enterprise: [v4.76.12 to v4.19.0 at least]

**Comment by janahintal** [comment]
QA Passed. Will move to done. Thanks
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html across all browser, OS and devices
