### ISSUE TITLE
Uplift: Fallout from last minute design changes

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#2318]
**Describe the bug**
Testing each component A-Z and reporting some issues. Listed in short form. We will divide these up.

**To Reproduce**
Continued list from https://github.com/infor-design/enterprise/issues/2318:

- [x] [Cards Example](http://localhost:4000/components/cards/example-group-action.html?theme=uplift) - the secondary toolbar needs work
- [x] [Colorpicker Example](http://localhost:4000/components/colorpicker/example-index.html?theme=uplift) - arrow is missing the border 
- [x] [Contextmenu Example](http://localhost:4000/components/contextmenu/example-index.html?theme=uplift) - icons not centered in the menu
- [x] [Header Example](http://localhost:4000/components/header/test-header-gauntlet.html?theme=uplift) -Misalignment on text and checkbox, text is a bit too low.
- [x] [Editor Example](http://localhost:4000/components/components/editor/example-index.html?theme=uplift&variant=dark) - In Edge the H3 and H4 icons are cut off
- [x] [Favorite Example](http://localhost:4000/components/favorites/example-index.html?theme=uplift) - Focus state is out of alignment
- [x] [Fileupload Example](http://localhost:4000/components/fileupload-advanced/example-index.html?theme=uplift) - Upload a file and look at the X icon , its misaligned
- [x] [Masthead](http://localhost:4000/components/masthead/example-index.html?theme=uplift) - Title text is a little close
- [x] [Message](http://localhost:4000/components/message/example-index.html
) - Click success button on IE edge and a tiny scroll bar is visible
- [x] [Multiselect](http://localhost:4000/components/multiselect/example-placeholder.html?theme=uplift) - The placeholder is the same color
- [x] [Paging Example](http://localhost:4000/components/blockgrid/example-paging.html?theme=uplift)- pager buttons not aligned in chrome and a little low
- [x] [Popdown](http://localhost:4000/components/popdown/example-index.html?theme=uplift) - the icon is not aligned with the text. Also when opening the top of the popdown shows an extra bordered edge on the top.
- [x] [Popover](http://localhost:4000/components/popover/example-alternate-positions.html?theme=uplift) - button appears outside the popup
- [x] [Radar](http://localhost:4000/components/radar/example-index.html?theme=uplift) - Text is smaller and very hard to read
- [x] [Searchfield](http://localhost:4000/components/searchfield/example-no-all-results-link.html?theme=uplift) - Is the x big?
- [x] [Slider](http://localhost:4000/components/slider/example-index.html?theme=uplift) - The bar is a little too dark
- [x] [Swaplist](http://localhost:4000/components/swaplist/example-index.html?theme=uplift) - Drag handle is very large
- [x] [Masthead](http://localhost:4000/components/masthead/example-index.html?theme=uplift) - make uplift masthead 313236 for back color (slate 08) and make the title 1.4rem (14px)
- [ ] [Tree](http://localhost:4000/components/tree/example-index.html?theme=uplift) - the icons for just a generic node i dont think are right liike like radios

**Version**

- ids-enterprise: v4.19.0

**Screenshots**
n/a

**Platform**
- all

**Additional context**
n/a

**Comment by EdwardCoyle** [comment]
Just noting stuff here that isn't changed in the branch:
- _Searchfield:_ no modifications to the size of the "X", but I did change the placement on Uplift to center it a bit more.
- _Tree:_ the node icon isn't actually different in the code.  The actual tree node icon from the tokens is different.

**Comment by brianjuan** [comment]
Hi, there are still some alignment issues found.
On http://4200-beta1-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html?theme=uplift, icon is a little too high.
![image](https://user-images.githubusercontent.com/39508864/62044061-976c2000-b234-11e9-9128-9fa99dbf6bb7.png)

On http://4200-beta1-enterprise.demo.design.infor.com/components/cards/example-group-action.html?theme=uplift&variant=light&colors=0563C2, checkboxes are too low.
![image](https://user-images.githubusercontent.com/39508864/62044087-a783ff80-b234-11e9-936a-11676e9ab982.png)

**Comment by brianjuan** [comment]
https://4200-rc0-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html?theme=uplift&variant=light&colors=0563C2
https://4200-rc0-enterprise.demo.design.infor.com/components/cards/example-group-action.html?theme=uplift&variant=light&colors=0563C2
Passed QA on all browsers.
