### ISSUE TITLE
SOHO-8162: Toast Functional and E2E Tests

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#232]
Add some tests for Toast

See existing tests for example textarea, dropdown, treemap, menubutton for reference. Also see docs/TESTING.MD for commands. Ask for help on sohoxi-dev if needed.

Functional Tests
- Test events that get triggered
- Test events that are listened to
- Test all API methods, most importantly the public ones first and the rest for coverage. (fx enable/disable)
- Test lifecycle methods (init, teardown, destroy, invoke)
- Test setting and that some states are applied

E2e Tests
- Load each test page in the components/<name>/list and test the main ideas of the page, if unsure of the main idea ask on the channel.
- Keyboard

Toast Specific Test Considerations 
- positions
- changing text
- api
- new links setting

Other Tests
- Accessibility tests https://github.com/dequelabs/axe-core
- Security Tests
- Specific Test Cases from Cindy
- Protractor Image Comparison Tests

**Comment by tjamesallen15** [comment]
For Testing run the following..
npm run functional:ci
npm run e2e:ci

**Comment by tmcconechy** [comment]
Should have been closed on https://github.com/infor-design/enterprise/pull/336

**Comment by CindyMercadoReyes** [comment]
This was reviewed by QA and the scripts cover all necessary aspects needed for Toast.
