### ISSUE TITLE
Datagrid before select veto: unable to select row in IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2321]
**Describe the bug**
Datagrid before select veto: unable to select row in IE11

**To Reproduce**
1. Open windows IE 11
2. Goto http://4190-beta2-enterprise.demo.design.infor.com/components/datagrid/example-beforeselect-veto.html
3. Hold ctrl then select a row

**Expected behavior**
Row should be selected

**Version**
v4.19.0

**Screenshots**
N/a

**Platform**
Windows 10
IE 11

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Fixing as almost a failed QA. If the team requesting this feature needs IE11 support this could be an issue

**Comment by janahintal** [comment]
QA Passed. Will Moved to Done
Tested in: http://4190-rc0-enterprise.demo.design.infor.com/components/datagrid/example-beforeselect-veto.html accross all OS, browser and devices.
