### ISSUE TITLE
Datagrid Paging: Select All Checkbox Untoggles after sorting

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2322]
**Describe the bug**
Datagrid Paging: Select All rows broke after sorting

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging.html
2. Click the Checkbox column header
3. Click the Id column header to sort
4. See issue: notice that the checkbox column header will be unchecked
5. Click the checkbox of first row
6. Now check the checkbox column header again
7. See issue: Checkbox column header is now unchecked

**Expected behavior**
Checkbox column should retain its state after sorting

**Version**
- ids-enterprise: v4.15.0 to v4.19.0-beta2

**Screenshots**
![dgpaging](https://user-images.githubusercontent.com/39508864/59027489-b7faa800-888b-11e9-8f6e-0683c7d3c7e2.gif)

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by marknolaninfor** [comment]
Server side data issue, as a client dataset is in sync.
http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side.html

Not sure how the server dataset is designed to keep the selected rows in sync.

**Comment by tmcconechy** [comment]
I made a feature/setting for this http://master-enterprise.demo.design.infor.com/components/datagrid/test-paging-multiselect-select-across-page.html and it does work on that example, just a note.

I think maybe here if we call `syncSelectedUI` after the sort it may fix it
