### ISSUE TITLE
Search field Component: User can select "All Results For" in search field box

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2329]
**Describe the bug**
Search field Component: User can select "All Results For" in search field box

**To Reproduce**
1. Go to url: http://4190-beta2-enterprise.demo.design.infor.com/components/autocomplete/example-searchfield.html
2. Type in “ca”
“California” and “All Results For “ca” appears in the list box
3. If I select ” All Results For “ca” it populates the search field box
4. ” All Results For “ca” should not  populates the search field box

**Expected behavior**
” All Results For “ca” should not  populates the search field box

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1028" alt="Searchfield component" src="https://user-images.githubusercontent.com/39101346/59048935-e7da8900-8854-11e9-802b-6c1decd6d9f6.png">

**Platform**
 - OS Version: [ iOS 10]
 - Browser Name [Chrome]

**Additional context**
None

**Comment by tmcconechy** [comment]
This issue was fixed for "No Results" as per https://github.com/infor-design/enterprise/issues/329 but not for the "All Results" apparently.

**Comment by brianjuan** [comment]
Hi, for "All Results", there's a conversation in the pull request to keep it selectable, https://github.com/infor-design/enterprise/pull/1010

**Comment by tmcconechy** [comment]
Ok, Thanks @brianjuan good find. So based on us agreeing that previously i'll close this out
