### ISSUE TITLE
Datagrid: Header text alignment issue

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2332]
Describe the bug
When the filter row is toggled on, the header text alignment is incorrect for a column that is not filterable.

To Reproduce
1. Using the attached test-header-text-alignment.html
2. Click on toolbar more button '....'
3. Toggle on the Show Filter Row menu item

Expected behavior
Header text for the Comment column should be aligned at the top.

Really just tweaked the existing test-align-header-text.html to show the issue.

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/59058971-5d4d5600-8863-11e9-87b3-effc4baa1571.png)

**Comment by claudenbach** [comment]
[Git-2332.zip](https://github.com/infor-design/enterprise/files/3263071/Git-2332.zip)

**Comment by janahintal** [comment]
QA Passed.  Will move to Done. 
Verified in: 
https://master-enterprise.demo.design.infor.com/components/datagrid/test-align-header-text
https://master-enterprise.demo.design.infor.com/components/datagrid/test-align-header-text-toggle
