### ISSUE TITLE
Datagrid filters in header is not aligned

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2337]
**Describe the bug**
Datagrid filters in header is not aligned

**To Reproduce**
1. Go to http://4190-beta2-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
2. Notice the filters in the header is not aligned

**Expected behavior**
Header filters should be aligned

**Version**
v4.19.0

**Screenshots**
<img width="1435" alt="Screen Shot 2019-06-07 at 1 29 29 PM" src="https://user-images.githubusercontent.com/45757016/59087878-855ab900-8938-11e9-95e2-0fbd0a3835fe.png">

**Platform**
All OS, Browsers and devices

**Additional context**
No additional context

**Comment by tmcconechy** [comment]
Will fix this along with https://github.com/infor-design/enterprise/pull/2328 which is same/similar. Will fix the Qty text and instock column

**Comment by tmcconechy** [comment]
We had a fix in a PR for this already https://github.com/infor-design/enterprise/pull/2328#issuecomment-499609588

**Comment by janahintal** [comment]
QA Passed. Thanks! 
Will now move to Done. 
Tested in: http://4190-rc0-enterprise.demo.design.infor.com/components/datagrid/example-filter.html across all browser, OS and devices
