### ISSUE TITLE
Datagrid grouped column not being reset after clicking Reset to Dafault

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2338]
**Describe the bug**
Datagrid grouped column not being reset after clicking Reset to Dafault

**To Reproduce**
1. Go to http://4190-beta2-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html
2. Move all columns in 'Column Grouped Four' to 'Column Group One'
3. Reset to Default

**Expected behavior**
Grid should reset to default

**Version**
v4.19.0

**Screenshots**
<img width="1181" alt="Screen Shot 2019-06-07 at 4 44 58 PM" src="https://user-images.githubusercontent.com/45757016/59092721-d1abf600-8944-11e9-8434-f0ec555cafbd.png">

**Platform**
All browser, OS and devices 

**Additional context**
No any additional context

**Comment by tmcconechy** [comment]
This seemed to work in 4.18.2 and i think i know why around the reset/JSON error changes i made

**Comment by tmcconechy** [comment]
@janahintal We cant seem to reproduce this one.
