### ISSUE TITLE
SOHO-8160: Block Grid Functional and E2E Tests

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#234]
Add some tests for Block Grid

See existing tests for example textarea, dropdown, treemap, menubutton for reference. Also see docs/TESTING.MD for commands. Ask for help on sohoxi-dev if needed.

Functional Tests
- Test events that get triggered
- Test events that are listened to
- Test all API methods, most importantly the public ones first and the rest for coverage. (fx enable/disable)
- Test lifecycle methods (init, teardown, destroy, invoke)
- Test setting and that some states are applied

E2e Tests
- Load each test page in the components/<name>/list and test the main ideas of the page, if unsure of the main idea ask on the channel.
- Keyboard

Block Grid Specific Test Considerations 
- mixed selection
- multiselect
- paging
- single select
- updated

Other Tests
- Accessibility tests https://github.com/dequelabs/axe-core
- Security Tests
- Specific Test Cases from Cindy
- Protractor Image Comparison Tests

**Comment by brianjuan** [comment]
I encountered a bug on example-paging and test-update pages.
I created a separate ticket for it, please see #488

**Comment by CindyMercadoReyes** [comment]
GitHub ticket #496 was created. This ticket was created for additional E2E Block Grid test scripts that are needed.

https://github.com/infor-design/enterprise/issues/496

**Comment by tmcconechy** [comment]
This issue should have been auto closed.
