### ISSUE TITLE
Colorpicker: Different colorpicker sizes are all the same in Mobile view

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2344]
**Describe the bug**
Colorpicker: Different colorpicker sizes are all the same in Mobile view or smaller browsers sizes.

**To Reproduce**
1. Open browsers in Android or iOS, or resize your desktop browser (except Chrome) in mobile viewport sizes
2. Go to http://4190-beta2-enterprise.demo.design.infor.com/components/colorpicker/example-sizes.html
3. See issue: All colorpickers are in the same sizes.

**Expected behavior**
Different colorpicker sizes should stay on their corresponding sizes on smaller screen size.

**Version**
- ids-enterprise: v4.19.0-beta0 to v4.19.0-beta2

**Screenshots**
<img width="422" alt="Screen Shot 2019-06-10 at 2 21 35 PM" src="https://user-images.githubusercontent.com/39508864/59176249-145f0f80-8b8b-11e9-93ad-7033f4b3639f.png">

**Platform**
 - All mobile browsers
 - All desktop browsers **except Google Chrome**

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
We did this on purpose. The fields will now be the same size on mobile. So this is correct
