### ISSUE TITLE
Tabs: Wrong focus after hiding a tab

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2346]
**Describe the bug**
Tabs: Wrong focus after hiding a tab

**To Reproduce**
1. Go to http://4190-beta2-enterprise.demo.design.infor.com/components/tabs/example-hidden-tabs.html
2. Click show hidden tabs button
3. Click the last tab, "Tab # 6"
4. Click Hide Tabs 2 and 5

**Expected behavior**
Tab focus should be in Tab#6

**Version**
 v4.19.0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/59183944-aa9d3080-8b9f-11e9-805d-f8ee4651dcdd.png)

**Platform**
All device, OS and browsers. 

**Additional context**
No any additional context

**Comment by EdwardCoyle** [comment]
Something wrong with the [calculation being done here](https://github.com/infor-design/enterprise/blob/4.19.x/src/components/tabs/tabs.js#L3552).  Noticing that the `positionFocusState` method is also called quite a bit in the Tabs code now -- wondering if it's being called multiple times with a bad index value in the event that focus is on the last tab.

**Comment by janahintal** [comment]
Failed QA. Issue still exist. Please see below. 
![image](https://user-images.githubusercontent.com/45757016/61209113-73381b80-a72b-11e9-802c-f59a336adfbb.png)
Tested in: http://master-enterprise.demo.design.infor.com/components/tabs/example-hidden-tabs.html

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
