### ISSUE TITLE
Tabs: Tabs drop down button for responsive view is still active after disabling all tab

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2347]
**Describe the bug**
Tabs drop down button for responsive view is still active after disabling all tab

**To Reproduce**
1. Open a browser and minimize he screen to responsive view
2. Go to http://4190-beta2-enterprise.demo.design.infor.com/components/tabs/example-enable-disable.html#programmatic-tabs-error-icon
3. Click Disable Entire Tab Control button
Notice the 'Arrow down' button is still viewed as Active

**Expected behavior**
Arrow down button should display Disabled 

**Version**
v4.19.0

**Screenshots**

![image](https://user-images.githubusercontent.com/45757016/59184414-aa516500-8ba0-11e9-872d-0cb50d369d7a.png)

**Platform**
All OS, Browser & Devices

**Additional context**
No any additional context

**Comment by EdwardCoyle** [comment]
Also noticing on that same sample page that the Slider component inside the "Form Elements" tab still has focusable ticks.  This ticket's scope could really be to double-check that the [disable()](https://github.com/infor-design/enterprise/blob/4.19.x/src/components/tabs/tabs.js#L3713) and [enable](https://github.com/infor-design/enterprise/blob/4.19.x/src/components/tabs/tabs.js#L3787) processes are correctly covering the whole component.

**Comment by tmcconechy** [comment]
I was actually thinking that this might not even be an issue. Because the tabs are disabled. I dont see why leaving the overflow would be problematic so you can view the disabled tabs in it?

**Comment by EdwardCoyle** [comment]
I'd have to recheck against an older build, but I think we originally disabled the whole thing.

**Comment by janahintal** [comment]
QA Passed. Tested in https://master-enterprise.demo.design.infor.com/components/tabs/example-enable-disable.html#programmatic-tabs-disabled across all browser, OS and devices.
