### ISSUE TITLE
Contextmenu in Data Field Options: Focus doesn't disappear

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2348]
**Describe the bug**
 Contextmenu in Data Field Options: Focus doesn't disappear when interacting with another field.

**To Reproduce**
1. Go to http://4190-beta2-enterprise.demo.design.infor.com/components/contextmenu/example-field-options.html
2. Open the Data Field in Input SM
3. Open the Data Field in Input LG
4. See issue: focus on Input SM doesn't disappear

**Expected behavior**
Focus should disappear on the previous field

**Version**
- ids-enterprise: v4.10.0 to v4.19.0-beta2

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/59189661-43867880-8bad-11e9-95e4-c84b09b29235.png)

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Can you have a look @deep7102 this probably happened due to recent changes this version

**Comment by brianjuan** [comment]
http://localhost:4000/components/contextmenu/example-field-options.html
Passed QA testing on all browsers, will retest once beta is deployed.
