### ISSUE TITLE
Tabs Module: New added tab is getting the content of different tab

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2350]
**Describe the bug**
Tabs Module: New added tab is getting the content of different tab

**To Reproduce**
1. Go to http://4190-beta2-enterprise.demo.design.infor.com/components/tabs-module/example-index.html#tab-2
2. Uncheck fill with garage and Populate Tab name and content
3. Click create new tab button
4. Check fill with garbage button
5.  Tick Create new tab button

**Expected behavior**
New tab should not have the content of different Tab

**Version**
 v4.19.0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/59193945-f52ba680-8bb9-11e9-880c-821591c2cffa.png)

**Platform**
All browser, OS and devices

**Additional context**
No any additional context

**Comment by tmcconechy** [comment]
I think this demo app issue is too minor to worry about. You would have to clear the text from the dialog and then click garbage. I guess clicking garbage should reset that field.

**Comment by tmcconechy** [comment]
@EdwardCoyle If you think we should fix feel free to reopen.

**Comment by EdwardCoyle** [comment]
It's definitely just a demoapp bug.  If we rework these tests in the future, it's something we can fix at that time.
