### ISSUE TITLE
Datagrid: Aligned right sort indicators overlap the column header text

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2351]
Describe the bug
With a column header alignment of right and enableTooltips setting of true, the sort indicators overlaps the column header text.

To Reproduce

1. Using the attached example-overlapping-sort-indicator.html
2. Mouse over the 'Order Date' column header
3. Notice that the sort indicators overlaps the column header text

Expected behavior
Column header text and sort indicators should not overlap

![image](https://user-images.githubusercontent.com/39804038/59203163-a3583180-8b63-11e9-8c5f-bf54cc290807.png)

**Comment by claudenbach** [comment]
[Git-2351.zip](https://github.com/infor-design/enterprise/files/3272485/Git-2351.zip)

**Comment by marknolaninfor** [comment]
Can you test with #2342 as that should correct the issue

**Comment by janahintal** [comment]
Failed QA. 
Filter are overlapping. Also for, http://master-enterprise.demo.design.infor.com/components/datagrid/test-overlapping-sort-indicator?theme=soho&variant=contrast&colors=133c59 & https://master-enterprise.demo.design.infor.com/components/datagrid/test-align-header-text-toggle the ellipsis is not showing upon resizing the column. 
![image](https://user-images.githubusercontent.com/45757016/60961439-bd418b80-a33e-11e9-9def-200f3fc0b248.png)

**Comment by tmcconechy** [comment]
The order date column doesn’t look right, so will fix that but the ellipsis on the header is a setting not enabled on this example. This example uses the default setting of just cutting off the column. Usually the example mentions “ellipsis” in the url name so that one way to know.

**Comment by tmcconechy** [comment]
Ready to retest: Fixed the order date problem now so ready to retest. Did not fix the textEllipsis as this is not an issue as the setting is not set on the mentioned example.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/test-ellipsis-sort-indicator and http://master-enterprise.demo.design.infor.com/components/datagrid/test-overlapping-sort-indicator Passed QA on all browsers.

But this page http://master-enterprise.demo.design.infor.com/components/datagrid/test-align-header-text-toggle on Safari, there's an alignment issue when you resize the Order Date column then you click the filter icon.
![image](https://user-images.githubusercontent.com/39508864/61533997-f83f6f80-aa60-11e9-8df4-a093ae9dcdd9.png)

**Comment by tmcconechy** [comment]
@brianjuan I'm going to ignore that last safari issue for now as it is risky to fix for the impact. IM actually not even seeing it on http://master-enterprise.demo.design.infor.com/components/datagrid/test-align-header-text-toggle on Mac safari.

If you want to raise a new issue for that case lets make a new issue.
