### ISSUE TITLE
RTL: using the arrows in colorpicker goes the wrong way

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#2352]
**Describe the bug**
I'm not sure that this is a problem, cause i'm not sure how the keyboards works for those using RTL. But it might be so I'll report it for now, maybe someone else knows?
The issue is that when I the colorpicker and try to select a color using the keyboard arrows it moves in the opposite direction (right when I click left arrow and left when I click the right)

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/colorpicker/example-index?locale=ar-SA
2. Click on the colorpicker to open it
3. Move around in the colorpicker using the left and right arrow

**Expected behavior**
I think that the selection should move in the direction of the arrow even in RTL

**Version**

- ids-enterprise: 4.18.1

**Screenshots**
-

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**
As I mentioned I am not sure if key codes are switched or something for RTL keyboards? but probably not so I think this is a bug. If not then please close this ticket :)

**Comment by tmcconechy** [comment]
@jonathanamiran is a hebrew native speaker. What do you think of this question, which way should the arrows move in LTR keyboards when testing? Is it correct for you as is? We did code it to be like this as its what we thought

Also noting that the layout part is on https://github.com/infor-design/enterprise/issues/1513 it isnt looking so great in RTL indeed

**Comment by jonathanamiran** [comment]
Hi, there aren't "LTR keyboards", arrows on Hebrew keyboards act the same way as regular Qwerty keyboard. 
If I change the keyboard language to Hebrew, the keyCode for **right** **arrow** is 39 and **left** **arrow** is 37 (which is the same an English if I'm not mistaken).

For this case I can see that when clicking on the right keyboard arrow it goes to the left and vice versa.

Cheers,
Jonathan

**Comment by tmcconechy** [comment]
OK, thanks. So its incorrect at the moment , your saying?

**Comment by janahintal** [comment]
Failed QA. Focus still not aligned in http://master-enterprise.demo.design.infor.com/components/colorpicker/example-index.html?locale=ar-EG

![image](https://user-images.githubusercontent.com/45757016/60968180-0ef21200-a34f-11e9-93ba-a7fe1d890ab1.png)

**Comment by davidcarlsonberg** [comment]
@janahintal Thanks for finding this! Unfortunately it is out of scope for this issue, which concerns using the left and right arrows in the colorpicker menu in `right-to-left` mode. Please raise another issue for the alignment.
