### ISSUE TITLE
Pager: Need to attach the page size selector to body.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2355]
**Describe the bug**
Because we have a position: sticky menu the pager dropdown menu is not sizing correctly when its open in our app. The existing option attachPageToBody fixes this but the pager doesnt have a way to set it.

**To Reproduce**
You cant you have to use our app.

**Expected behavior**
Add a way to feed the option into the pager popupmenu.

**Comment by brianjuan** [comment]
I did regression on this page, http://4190-rc1-enterprise.demo.design.infor.com/components/pager/example-standalone.html , and everything works fine. I am just confused about the steps in PR #2354 , Page size dropdown is in the same position in the dom whether I check or uncheck the "Attach Page Size Menu To Body" checkbox

**Comment by tmcconechy** [comment]
Yeah it will still visually be in the same position. It’s very subtle it’s just the position in the html structure. This is important in some specific cases depending on html structure of your page. It’s kind of a developer / api level thing that doesn’t lead well to visual testing.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done folder.
