### ISSUE TITLE
Pager: Improve settings handling on Page Size Selector

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#2356]
**Is your feature request related to a problem? Please describe.**
A feature was added in #2354 that passes an `attachPageSizeMenuToBody` setting to the Pager's page size button.  To follow our other components' normal pattern of passing a whole options object instead of just individual settings, we should add a `pageSizeMenuSettings` object that represents the full set of Popupmenu options.

**Describe the solution you'd like**
Change [this bit in the Popupmenu code to](https://github.com/infor-design/enterprise/pull/2354/files/59560f6cd12a8431acfcdfa542643c25cc0223f8#diff-5ec3aeece02e6ca8b60f7f7080ef5362R99):
```js
pageSizeMenuSettings: {
   attachToBody: false
}
```

... as well as [this bit](https://github.com/infor-design/enterprise/pull/2354/files#diff-5ec3aeece02e6ca8b60f7f7080ef5362L1019) to:
```js
const popupOpts  = utils.extend({}, {
  placementOpts: {
    parent: pageSizeButton,
    parentXAlignment: (Locale.isRTL() ? 'left' : 'right'),
    strategies: ['flip']
  }
}, this.settings.pageSizeMenuOpts);
```

We should also include a deprecation warning for this whenever someone tries to use `attachPageSizeMenuToBody`, and provide backwards compatibility when attempting to use it.  We also need a corresponding change on the NG side to accommodate the fleshed out settings.

**Additional context**
Per the comments in the original pull, we had to accommodate an easy change on the NG side in order to meet some deadlines, which is why we didn't do it this way to begin with.

Probably want to test against https://latest-enterprise.demo.design.infor.com/components/pager/example-standalone.html

----

@pwpatton

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
