### ISSUE TITLE
Datagrid / Treegrid: isEditable function may or may not send the correct row data

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#2357]
**Describe the bug**
The treegrid uses a callback function called isEditable to determine if a particular cell is editable. The parameters to the callback function includes row data. The row data may or may not be available since settings.dataset is 'collapsed' data.  When the tree nodes are expanded, the cell editable does not have the row data to make that determination.

**To Reproduce**
1. Use the demo page test-tree-editable.html.
2. Say for description column definition, set isEditable function:
```
columns.push({ id: 'desc', name: 'Description', field: 'desc', editor: Editors.Input, isEditable: cellIsEditable });
...
...
cellIsEditable = function(row, cell, value, columnDef, rowData, dataGrid) {
    return rowData != undefined;
};
```
**Expected behavior**
After expanding one of the tree node,  description cell of the last row has rowData passed in cellIsEditable function.

**Version**
ids-enterprise:  v4.19.0-beta.2

**Platform**
 - OS Version: Windows 10
 - Browser Name: chrome version 75

**Comment by tmcconechy** [comment]
Im not very clear on this issue can you explain it further? 
1. Where is  EditableTreeGrid.html mentioned?
2. I tried to edit test-tree-editable.html to the below code. And when i run the page it runs the function as expected. I am watching the console and seeing the rowData looking as i might expect.

Updated test-tree-editable.html
```html
<div class="row">
  <div class="twelve columns">
    <div id="datagrid">
    </div>
  </div>
</div>

<script>
  $('body').one('initialized', function () {
    var columns = [];
    var someData = [
      {
        id: 215,
        escalated: 0,
        taskName: 'Follow up action with Residental Housing',
        desc: 'Contact sales representative with the updated purchase order.',
        comments: 2,
        time: '22:10 PM',
        children: [
          {
            id: 216,
            escalated: 0,
            taskName: 'Follow up action with Universal HMM Logistics',
            desc: 'Contact sales representative.',
            comments: 2,
            time: '22:10 PM'
          },
          {
            id: 217,
            escalated: 0,
            expanded: true,
            taskName: 'Follow up action with Acme Shipping',
            desc: 'Contact sales representative.',
            comments: 2,
            time: '22:10 PM',
            children: [
              {
                id: 218,
                escalated: 0,
                taskName: 'Follow up action with Residental Shipping Logistics ',
                desc: 'Contact sales representative.',
                comments: 2,
                time: '7:04 AM'
              }
            ]
          }
        ]
    }];

    var isCellEditable = function(row, cell, value, columnDef, rowData, dataGrid) {
      console.log(rowData);
      return rowData != undefined;
    };

    //Define Columns for the Grid.
    columns.push({ id: 'taskName', name: 'Task', field: 'taskName', expanded: 'expanded', formatter: Formatters.Tree, editor: Editors.Input });
    columns.push({ id: 'id', name: 'Id', field: 'id' });
    columns.push({ id: 'portable', name: 'Portable', field: 'portable', align: 'center', formatter: Formatters.Checkbox, editor: Editors.Checkbox});
    columns.push({ id: 'comments', name: 'Comments', field: 'comments',  formatter: Formatters.Hyperlink, editor: Editors.Input, width: 60, isEditable: isCellEditable});
    columns.push({ id: 'desc', name: 'Description', field: 'desc', editor: Editors.Input });

    //Get some data via ajax
    var url = '{{basepath}}api/tree-tasks';

    $.getJSON(url, function(data) {

      $('#datagrid').datagrid({
        columns: columns,
        dataset: data,
        treeGrid: true,
        editable: true,
        toolbar: {title: 'Tasks (Hierarchical)', results: true, personalize: true}
      });

    });

  });
</script>
```

**Comment by aaralikar** [comment]
Sorry, I saved it as EdtableTreeGrid.html and gave you the wrong name. It is test-tree-editable.html

**Comment by aaralikar** [comment]
![image](https://user-images.githubusercontent.com/22720894/59281263-98b59f00-8c2c-11e9-9ef2-f0c6c68db043.png)

**Comment by aaralikar** [comment]
In the above screenshot, I clicked on row 1, cell 4. But I get the row data corresponding to row 6.

**Comment by aaralikar** [comment]
![image](https://user-images.githubusercontent.com/22720894/59281490-fd70f980-8c2c-11e9-9487-34e94ee94f71.png)

**Comment by aaralikar** [comment]
In the above screenshot, I clicked on row 21, cell 4 and the rowdata is undefined.

**Comment by tmcconechy** [comment]
On thing that confuses me is that function never fires on click. It only fires as i see on page load

**Comment by aaralikar** [comment]
[test-tree-editable.txt](https://github.com/infor-design/enterprise/files/3277936/test-tree-editable.txt)

**Comment by aaralikar** [comment]
Renamed demo file to .txt instead of .html

I am able to reproduce the issue with click of each row.

**Comment by tmcconechy** [comment]
Issue is merged and ready to retest

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to Failed QA. On Win 10 IE11 the data grid is not appearing.

Win 10 IE 11
URL: http://master-enterprise.demo.design.infor.com/components/datagrid/test-post-renderer-tree.html
The data grid doesn't load. Please see screen shot attached.
![bs_win10_IE_11 0 (6)](https://user-images.githubusercontent.com/39101346/60528362-4d8a2b80-9cc2-11e9-90a6-c91e2576c07e.jpg)

**Comment by tmcconechy** [comment]
@CindyMercadoReyes can you retest? Im seeing it load fine now on WIn 10 IE11

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. @tmcconechy
