### ISSUE TITLE
Datepicker: Invalid error and unavailable date validation errors are confusing when they appearing at the same time

### ISSUE THREAD

**Issue by junxyan** [infor-design/enterprise#2359]
Soho datepicker invalid error and unavailable date error appearing at the same time

1. Go to http://master-enterprise.demo.design.infor.com/components/datepicker/test-invalid-dates.html
2. Click on any unavailable date
3. See unavailable date error message appearing
4. Manually update the date using keyboard to invalid date say three digits year,
5. See Invalid date error message appearing along with unavailable date error message

Expected behavior:
should only see Invalid date error message in this case, not two error messages together

Version
- ids-enterprise: 5.3 and lower

Screenshots
![image](https://user-images.githubusercontent.com/51687210/59239571-403ecb80-8c45-11e9-908d-0425f6bcb791.png)

From MRM PO:
Yeah, I think this issue needs to be addressed. Because if you think about it a datepicker with weekends are set to unavailabledates, as users are allowed to type dates, instead choosing, when a date is invalid to be entered, it cannot have the same error as Weekend date right. Ideally we should just have one validation at any given time..I cannot really think of scenario from our use case where both validation errors can be true
If SOHO team can improve this experience that will be great..!!

**Comment by tmcconechy** [comment]
In order to fix this i think the developer should update the "unavailable date" validation message to return true if the date is invalid. This seems a bit counterintuitive so may need to rethink this.

**Comment by tmcconechy** [comment]
Descoping this for now
