### ISSUE TITLE
SOHO-8128: Datagrid - unable to capture the 'tab' key onKeydown

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#236]
In Landmark, the list component is listening for the tab key onKeyDown.  When the user hits the tab key on the last cell of a newly added row, the row is saved and another row is added to the datagrid.  This is intended to support users that want to quickly add data rows to the datagrid.

The tab key event from onKeydown was not getting to our keydown handler because within soho's datagrid.js it is capturing the tab event and indicating that the event was handled and performs preventDefault() and stopPropagation().

Including some code snippets from datagrid.js....
{code}
    // Handle rest of the keyboard
    self.table.on('keydown.datagrid', 'td', function (e) {
      const key = e.which || e.keyCode || e.charCode || 0;
      let handled = false;

......

      // Tab, Left and Right arrow keys.
      if ([9, 37, 39].indexOf(key) !== -1) {
        if (key === 9 && !self.settings.actionableMode) {
          return;
        }

        if (key !== 9 && e.altKey) {
          // [Alt + Left/Right arrow] to move to the first or last cell on the current row.
          cell = ((key === 37 && !isRTL) || (key === 39 && isRTL)) ? 0 : lastCell;
          self.setActiveCell(row, cell);
        } else if (!self.quickEditMode || (key === 9)) {
          if ((!isRTL && (key === 37 || key === 9 && e.shiftKey)) || // eslint-disable-line
              (isRTL && (key === 39 || key === 9))) { // eslint-disable-line
            cell = getNextVisibleCell(cell, lastCell, true);
          } else {
            cell = getNextVisibleCell(cell, lastCell);
          }

          if (cell instanceof jQuery) {
            self.setActiveCell(cell);
          } else {
            self.setActiveCell(row, cell);
          }
          self.quickEditMode = false;
          handled = true;
        }
      }

.....

      if (handled) {
        e.preventDefault();
        e.stopPropagation();
        return false; // eslint-disable-line
      }
{code}

**Comment by tmcconechy** [comment]
This issue should have been closed with https://github.com/infor-design/enterprise/pull/262
