### ISSUE TITLE
Hierarchy: Contextmenu details are added every time you open it

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2361]
**Describe the bug**
Hierarchy: Contextmenu details are added every time you open it.

**To Reproduce**
1. Go to http://4190-rc0-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html
2. Click the ... button in Kaylee Edwards to open context menu
3. Close the context menu, then open again
4. See issue: There are new Delete and Move items
5. Try reopening the context menu several times

**Expected behavior**
There should be no items added in the context menu every time you open it.

**Version**
- ids-enterprise: v4.10.0 to v4.19.0-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/59263784-54e68800-8c74-11e9-9995-63872f1fb2b8.png)

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Descoping this for now
