### ISSUE TITLE
Datagrid: Cannot scroll horizontally when no data is shown

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2363]
**Describe the bug**

**To Reproduce**
1. Go to http://4190-rc0-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
2. Resize the page to smaller size
3. Type "testfilter" in the Product Name filter field
4. No Data Available message will be shown
5. Try to scroll horizontally, see issue: datagrid will not scroll

**Expected behavior**
Datagrid should be scrolled horizontally when No Data 

**Version**
- ids-enterprise: v4.17.0 to v4.19.0-rc0

**Screenshots**
No applicable screenshot.

**Platform**
 - All Devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
![Screen Shot 2019-06-11 at 8 39 13 AM](https://user-images.githubusercontent.com/814283/59272630-69029900-8c24-11e9-9379-127bcc2efab1.png)

Im not 100% able to reproduce this issue, I'm seeing the scroll bar.

**Comment by tmcconechy** [comment]
This is possibly similar to https://github.com/infor-design/enterprise/issues/1041 but having a problem reproducing all of what is there.

**Comment by brianjuan** [comment]
@tmcconechy For Mac, the scrollbar setting did the trick, I can now scroll horizontally. It's also working fine for Windows. But for Android and iOS, the issue can be encountered, maybe you can take a look if you can reproduce it. Thanks.

**Comment by marknolaninfor** [comment]
A user has reported this to us and the additional information was that they had the browser zoom set to 90% within chrome and the scrollbar was not visible, but when it was 100% it was visible. Hope this helps to replicate the issue.

**Comment by pwpatton** [comment]
https://jira.lawson.com/browse/LMCLIENT-26157
here's a related issue reported to us by the landmark cloud suite financials team.

**Comment by brianjuan** [comment]
http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
QA Passed on other browsers except Safari and Windows IE.
In Safari, you cannot scroll through the column headers.
![image](https://user-images.githubusercontent.com/39508864/70699103-93ccc780-1d03-11ea-9690-07cc37624586.png)

In Windows IE, empty message is not displayed
![image](https://user-images.githubusercontent.com/39508864/70699246-cb3b7400-1d03-11ea-9971-773c393f642d.png)

**Comment by tmcconechy** [comment]
Hmm, yeah. Taking a look at this.

**Comment by tmcconechy** [comment]
Closing as PR will solve

**Comment by brianjuan** [comment]
http://4240-rc0-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
Passed QA on all browsers, moving to Done.
