### ISSUE TITLE
Input / Context Menu:  Right Click Me text error in within the autocomplete label

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2364]
**Describe the bug**
Input / Context Menu:  Right Click Me text error in within the autocomplete label

**To Reproduce**
1. Go to url: http://4190-rc0-enterprise.demo.design.infor.com/ 
2. Scroll down to Context Menu on Input Fields
3. Click inside the Label field box
4. Click on the delete key to remove characters from " Right Click Me"
5. See error on MAC Chrome when the user begins to remove characters from the filed box "Right Click Me appears under the field box. Please see screen shot attached. 

**Expected behavior**
Autocomplete should not appear under the Label and Label2 field box 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.19.0]

**Screenshots**
![Screen Shot 2019-06-11 at 9 53 17 AM](https://user-images.githubusercontent.com/39101346/59278501-162ede80-8c30-11e9-9b40-5d7a70c35a18.png)

**Platform**
 - OS Version: [iOS 8]
 - Browser Name [Chrome]
 - Browser Version [Version 74.0.3729.169 (64-bit) ]

**Additional context**
None

**Comment by tmcconechy** [comment]
Seems like the audible label is adding a value. We should probably remove that or change it from adding. Also we can add `autocomplete: true`

```
<input type="text" data-options="{trigger:'rightClick'}" data-popupmenu="action-popupmenu" value="Right Click Me" id="input-menu" aria-haspopup="true" aria-controls="action-popupmenu" class="">
```

**Comment by tmcconechy** [comment]
Relates to https://github.com/infor-design/enterprise/issues/2366

**Comment by tmcconechy** [comment]
Also we found the popup on a search field is inserted in the DOM it should also have `autocomplete="off"`
