### ISSUE TITLE
Demoapp: Add Uplift/RTL Font Support

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#2365]
**Is your feature request related to a problem? Please describe.**
The Demoapp needs to conditionally serve font families for certain locales when displaying the Uplift theme.

- Fonts should be served locally from the app, or pulled in from Google Fonts
- Font files served locally should be copied in from the `ids-identity` package
- Link tags that include the font should conditionally be used only if a corresponding locale requires the font.
- Don't bundle the fonts in the actual IDS build.  We are leaving the inclusion of the extra locale fonts up to the app developers to use if they are actually needed.

**Additional context**
Discussion on Locale-specific Uplift fonts can be seen on infor-design/design-system#385

**Comment by EdwardCoyle** [comment]
Just putting this on hold til we decide all final font choices on infor-design/design-system#385.

**Comment by brianjuan** [comment]
All pages in the PR are working as expected except this page https://4200-beta1-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?theme=uplift&locale=ar-SA, texts are not loaded and I'm getting an error in all browsers except IE11.

**Comment by tmcconechy** [comment]
@brianjuan as this issue is locale related i made a seperate issue https://github.com/infor-design/enterprise/issues/2540 will fix it there as i think i see the issue
