### ISSUE TITLE
Lookup: Listbox and Browser Autocomplete list appearing at the same time

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2366]
**Describe the bug**

**To Reproduce**
1. Go to url: http://4190-rc0-enterprise.demo.design.infor.com/components/lookup/example-index.html
2. Make the page responsive
3. Place your cursor inside the "Product" field box and press down arrow key
3. The dropdown list box will appear then quickly disappear and the Products list  pop up window appears 
4. The Product list popup window should not appear when the user has place their cursor in the Products field box

**Expected behavior**
The Product list popup window should not appear when the user has place their cursor in the Products field box

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.19.0]

**Screenshots**
None

**Platform**

 - OS Version: [iOS 8]
 - Browser Name [Chrome]
 - Browser Version [ 74, (64-bit)]

**Additional context**
None

**Comment by tmcconechy** [comment]
This issue is not totally obvious but whats happening is the browser autocomplete is showing up and interfering. To fix this just make sure that lookup.js adds `autocomplete = "off"` to the input field and it should fix. 

Might want to figure out how to make the autocomplete appear first and reproduce.

**Comment by tmcconechy** [comment]
Also #2364 can be fixed along with this. We worked out that adding :

```
autocomplete = "false"
autocomplete ="some-nonsense"
```

Will probably fix see:

https://teams.microsoft.com/l/message/19:6d4c9079385840c0bc61e55bcdd16a33@thread.skype/1560268550992?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1560268550992&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Problems&createdTime=1560268550992

**Comment by tmcconechy** [comment]
Should also add autocomplete to the autocomplete popup on searchfield.

**Comment by davidcarlsonberg** [comment]
I cannot find a way to reproduce this. Maybe a video would help?

**Comment by CindyMercadoReyes** [comment]
Move this ticket to QA failed on iOS device the user can't view the product list.  Please see screen shot attached. 
![bs_realios_Mobile_iPhone XS-12 0(1)](https://user-images.githubusercontent.com/39101346/61316430-f65e7d80-a7ce-11e9-8638-3d888cb684c1.jpg)

**Comment by tmcconechy** [comment]
@CindyMercadoReyes That problem should be addressed by:
https://github.com/infor-design/enterprise/issues/2433

And is unrelated. So lets descope that one for now as its not related to the list autocomplete popup.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/lookup/example-index.html
http://localhost:4000/components/lookup/example-index.html
Passed QA testing on all browsers, will retest once beta is deployed.
