### ISSUE TITLE
About Component: Incorrect Version Appearing

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2367]
**Describe the bug**

**To Reproduce**
1. Go to url:http://4190-rc0-enterprise.demo.design.infor.com/components/about/example-index.html
2. Click on "Show About Screen
3. Scroll down to the bottom of the page
4. The version is incorrect. It's showing Beta when it should be RC

**Expected behavior**
Correct version should appear

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.190]

**Screenshots**
![About Page](https://user-images.githubusercontent.com/39101346/59294876-746bb980-8c50-11e9-82b2-350b79822b93.png)

**Platform**

 - OS Version:  iOS 8]
 - Browser Name [chrome]
 - Browser Version [e.g. 74 (64-bit)]

**Additional context**
None

**Comment by tmcconechy** [comment]
Lets see what happens on the next deploy.

**Comment by clepore** [comment]
This was due to a fluke in the release version bump is all.

**Comment by tmcconechy** [comment]
Confirmed: https://4190-rc1-enterprise.demo.design.infor.com/components/about/example-index.html is ok now 👍
