### ISSUE TITLE
SOHO-8121: 4.0 Validation getting multiple events firing for one occurrance

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#237]
Seeing multiple validation events firing for one occurrence. 

For example, using a date field and changing the value to 12, seeing the following events being fired:
{code}
'valid'
'error'
'valid'
'error'
{code} 

To duplicate, use the example-index.html that is either attached or located in the validation directory.
- Highlight the date value and replace with 12
- Tab out of the field
- On the console observe the multiple events that were logged.

Also attached is a screenshot/gif demonstrating the issue.

**Comment by tmcconechy** [comment]
Fixed as per PR https://github.com/infor-design/enterprise/pull/291
Once merged can be tested on 

http://master-enterprise.demo.design.infor.com/components/validation/test-events
- both error and valid events should fire only once.

**Comment by brianjuan** [comment]
Bug fix is working as expected across all browsers and passed the QA testing.
See screenshot below.
![image](https://user-images.githubusercontent.com/39508864/42862284-d8d0c5cc-8a2c-11e8-9ecf-3601ddc866c2.png)
