### ISSUE TITLE
Validation: Placeholder showing when typing in the field box

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2370]
**Describe the bug**
Validations Component: Dirty Tracker Issue when typing in the field box

**To Reproduce**
1. Go to url: http://4190-rc0-enterprise.demo.design.infor.com/
2. Scroll down to  "Text Input Fields" 
3. Click inside the "Dirty Tracker" field box and start typing "Hello" 
4. If you look at the screen shot attached, you notice that the Grayed out word " Dirty Tracker" is still visible while the user is entering text in the field box. Please see screen shot attached.  

**Expected behavior**
The field box should be blank when entering text.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.19.0]

**Screenshots**
![IMG_4919](https://user-images.githubusercontent.com/39101346/59299830-a33b5d00-8c5b-11e9-9780-2589d3f66322.PNG)

**Platform**
 - Device (if applicable) [iPhone XS 12]

**Additional context**
None

**Comment by tmcconechy** [comment]
Im not seeing this, does anyone else see it? Looks like something with a spell checker.

**Comment by tmcconechy** [comment]
Was unable to reproduce
