### ISSUE TITLE
PopupMenu: SubMenu still have the is-open class after selection/close

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2371]
**Describe the bug**
When a submenu is opened and an item is selected then the submenu still has the is-open class. This causes an issue if an accordion is also used as the accordion's check for open menus $('.popupmenu.is-open') will return that the submenu is open, and then run additional code that fails.

**To Reproduce**
1. Go to 'http://localhost:4000/components/accordion/test-with-contextmenu.html'
2. Click on the more button on the page and set the color
3. Click on the Personal accordion item to expand
4. See error in the console and the item does not expand.

**Expected behavior**
If the parent menu is closed then the submenu is also closed and the is-open css style should be removed.

**Version**
master

![image](https://user-images.githubusercontent.com/39749678/59402590-369c9b80-8dde-11e9-9def-c328e2d5e03c.png)

**Comment by tmcconechy** [comment]
This should also address a little part of this issue https://github.com/infor-design/enterprise/issues/1928#issuecomment-500583896

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks
Tested in http://master-enterprise.demo.design.infor.com/components/accordion/test-with-contextmenu.html across all Browsers.
