### ISSUE TITLE
SOHO-8119: Context menu not hidden when clicking on accordion menu

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#238]
Repro:

1. Setup an accordion menu bar with two menu groups.
2. Setup a context menu to display when clicking on a menu item.
3. Right-click on the menu item (the context-menu is correctly displayed)
4. Click on another menu group in the menu bar (the context menu remains visible).
5. Click somewhere else in the document (the context menu is correctly hidden).

!ContextMenuOnHeader.PNG|thumbnail!

**Comment by brianjuan** [comment]
This issue is working as expected across all browsers and passed QA testing.
