### ISSUE TITLE
Swaplist: Search Does Not Remove Second Character Highlight/Bold

### ISSUE THREAD

**Issue by kenneth-acejo** [infor-design/enterprise#2382]
**Describe the bug**
When removing letters from the search word:
Option -> Optio -> Opti -> Opt -> Op -> O

The highlight/bold for characters for matching items are removed except for the second character.

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/swaplist-search
2. Type 'Option' on any search field 
3. Press backspace until 'p' is removed (characters removed in sequence are n, o, i, t and p)
4. Observe the matching items. 'Op' are in bold

**Expected behavior**
Only 'O' should be highlighted or in bold.

**Version**
- ids-enterprise-ng: [e.g. v5.4.0]
- ids-enterprise: since the feature was introduced

**Screenshots**
![Capture](https://user-images.githubusercontent.com/17284784/59483220-f2250480-8e9e-11e9-9637-0b121066e56c.PNG)

**Comment by tmcconechy** [comment]
I rested this on https://master-enterprise.demo.design.infor.com/components/swaplist/example-search.html (4.34) and it appears this is no longer an issue on the latest version
