### ISSUE TITLE
SOHO-8097: Tabs Functional and E2E Tests

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#239]
Add some tests for Tabs and Tab Variations

See existing tests for example dropdown, timepicker, treemap, ect menubutton for reference. Also see docs/TESTING.MD for commands.

Ask for help on hl-dev-ids if needed.

Function Tests
- Test events that get triggered (activated, beforeactivated ect)
- Test events that are listened to
- Test all API methods, most importantly the public ones first and the rest for coverage. (fx enable/disable)
- Test lifecycle methods (init, teardown, destroy, invoke)
- Test setting and that some states are applied

E2E
- Load each test page in the components/<name>/list and test the main ideas of the page, if unsure of the main idea ask on the channel.
- Keyboard

Tabs Specific Test Considerations 
- Regular Tabs
- Header Tabs (two variations)
- Validation - Editing a field on the page shows icon on the tab
- Add Tab Button
- Tab Counts
- Closable Tabs
- Dropdwn Tabs
- Enable/Disable Tabs
- Hide/Show Tabs
- Urls on tabs as links
- Ajax tab content
- Special LSF bordered tabs
- Nested Tabs
- Not able to dismiss some tabs
- Seperators
- Module Tabs - Add
- Module Tabs - Menu Button
- Module Tabs - Category Search
- Empty Module Tabs
- Multi (Side by Side) Tabs - With Mast Head
- Vertical Tabs - scrolling
- Vertical Tabs - responsive

Other Tests
- Accessibility tests https://github.com/dequelabs/axe-core
- Security Tests (XSS) - 
- Specific Test Cases from Cindy ?
- Protractor Image Comparison Tests (Css Regressions)

**Comment by CindyMercadoReyes** [comment]
This was reviewed by QA and the scripts cover all necessary aspects needed for Tabs.
