### ISSUE TITLE
Datagrid: Incorrect sorting on numeric columns

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#2390]
**Description of problem:**
On the example page http://localhost:4000/components/datagrid/test-calculate-text-width.html, when changing the sort on the "capacity" column, the numbers become incorrectly sorted (e.g., putting 10 and 100 just before 1,000):

<img width="123" alt="capacity-sort" src="https://user-images.githubusercontent.com/7952168/59619458-8938c900-90f8-11e9-9890-e6097a41ffe2.png">

_Originally posted by @davidcarlsonberg in https://github.com/infor-design/enterprise/pull/2342#issuecomment-502748330_

**Expected Behavior:**
This column should sort numerically.

**Version**
Discovered testing `master` at 4.20.x

**Comment by tmcconechy** [comment]
I wasn't 100% seeing this. 
1. load the page
2. sort back and forth on id or capacity (same issue) -> is is sort of wrong because it should sort the backend across all pages
3. page one forward and pack -> now i see the issue and the sorting is really wrong

**Comment by tmcconechy** [comment]
Also found that this worked in http://4150-enterprise.demo.design.infor.com/components/datagrid/example-paging.html but the sorting is wrong. I fixed the sorting so far but i see we have an issue that sort is not calling source on paging.

So this is both a regression from the paging changes made and a demo app bug.

**Comment by janahintal** [comment]
QA Passed. 
Will move to done. Tested in http://master-enterprise.demo.design.infor.com/components/datagrid/test-calculate-text-width.html
