### ISSUE TITLE
Stepprocess: Not showing the next step

### ISSUE THREAD

**Issue by boehmd1** [infor-design/enterprise#2391]
**Describe the bug**
When on the last step of a step process wizard and the next button calls the beforeSelectStep promise which enables more steps to become valid.  The newly enables step is NOT rendered.

**To Reproduce**
1. Go to http://localhost:4000/patterns/stepprocess-markup1.html
2. Click on Next

**Expected behavior**
The next valid step (step 2) should be rendered.

**Version**
- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Comment by boehmd1** [comment]
@tmcconechy  i have a fix for this issue.

**Comment by brianjuan** [comment]
http://localhost:4000/patterns/stepprocess-markup1.html
Passed on all browsers, will retest once beta is deployed.
