### ISSUE TITLE
Datagrid: cell error background colour has changed so that the tooltip is not visible

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2397]
**Describe the bug**
The background colour used be 10% opaque for a datagrid cell with an error.

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/test-editable-validation'
2. Remove a value from the order date
3. Hover over the cell to find the tooltip

**Expected behavior**
The cell indicates that there is an error and the tooltip is visible, so additional information can be seen regarding the error.

**Version**
v4.20.0-dev (master)

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/59733037-a81b9480-928b-11e9-97e0-1fb63c08a8ea.png)

**Comment by tmcconechy** [comment]
This issue was caused by changes on https://github.com/infor-design/enterprise/pull/2353

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-editable-validation
Error icon and tooltip can now be seen. Tested on all browsers, will retest once beta is deployed.
