### ISSUE TITLE
Datagrid: Contextmenu behavior change from 4.18 to 4.19

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#2398]
**Describe the bug**
Hi, we use contextmenu on DataGrid. When testing 4.19.2 (before upgrade from 4.18) I've noticed that the first right click on the datagrid row shows a small narrow popup on the bottom of the datagrid, after right clicking again the issue resolves (comes back again when we reload the site)

**To Reproduce**
1. Go to [https://jsfiddle.net/sebulbajoe/nm05o4d2/1](https://jsfiddle.net/sebulbajoe/nm05o4d2/1)
2. Right click on one of the rows
3. see the bottom popup.
4. right click again - see the correct context menu

**Expected behavior**
Go to the same code on [https://jsfiddle.net/sebulbajoe/nm05o4d2](https://jsfiddle.net/sebulbajoe/nm05o4d2) but this time connected to 4.18.0. Context menu pops correctly on the first try

**Version**

- ids-enterprise: v4.19.2

**Screenshots**
![datagrid-contextmenu](https://user-images.githubusercontent.com/34129313/59745933-7e0fa580-927e-11e9-9904-40979ce834f8.PNG)

**Platform**

 - Browser Name Chrome
 - Browser Version  74.0.3729.169 (Official Build) (64-bit)

**Additional context**

**Comment by CindyMercadoReyes** [comment]
I tested this issue across browsers and this ticket is now resolved.
