### ISSUE TITLE
Datagrid/Modal: Focus Trap Issue

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#2399]
**Describe the bug**
There is a focus trap issue involving Datagrid components inside of Modals. Inside an active Modal, once keyboard focus is on an element inside of the Datagrid, it is no longer possible to navigate outside of the Datagrid's rows/columns. 

This doesn't appear to affect Lookup components.  Specifically, it affects a full-fledged Datagrid used inside of a Modal.

**Steps to reproduce**
- Open http://localhost:4000/components/modal/test-toolbar.html
- Click "Open Modal"
- Press `Tab` key once to move focus to the grid
- Press `Shift + Tab` to try and move focus back to the button.  See that it doesn't move focus out of the grid.
- The same occurs when tabbing all the way through all grid cells.  It's not possible to then press `Tab` to get out of the grid and into the Pager bar, or beyond.

**Version**
Found while testing v4.19.x, may have been present before since the example page was new.

**Additional Context**
Originally found while testing [#2381](https://github.com/infor-design/enterprise/pull/2381#issuecomment-502838269)

**Comment by jbrcna** [comment]
QA PASSED. will retest this ticket once beta is deployed
v4.27.0.-dev
