### ISSUE TITLE
SOHO-8090: Soho Grid Copy and Paste performance issue on large clipboard data

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#240]
Have tried copying 500 rows on data from excel to Soho Data Grid and browses goes not responding/crashing.

This request is related to : SOHO-1750

To reproduce:

1. Go to components/datagrid/example-editable.html
1. Copy the rows of cell in the attached excel file. [500Rows.xlsx](https://github.com/infor-design/enterprise/files/2201507/500Rows.xlsx)
1. Paste it on the 'Activity' column in the grid in the link above.

**Comment by brianjuan** [comment]
This enhancement is working as expected across all browsers and passed QA testing.
Browsers are not crashing/freezing when pasting 500 records.
