### ISSUE TITLE
Unable to get property 'previousElementSibling' after selecting from dropdown in datagrid cell

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2403]
**Describe the bug**
selecting a value from a datagrid editor cell dropdown (that is lazily loaded might be required) and notice the error:
Unable to get property 'previousElementSibling' of undefined.
This causes the app to essentially stop working.

**To Reproduce**
NOTE: Please let me know if you need to dup so I can start the server
1. go to http://usspnppatton.infor.com:8080/hcm/Benefits/form/BenefitPlan%287004,FIDELITY%20401K%29.BenefitPlanForm?action=Update&csk.cli=true&csk.showusingxi=true
2. so once you get there, click the deductions tab
3. click the create button above the deductions list (this allows the first row to hgave data typed in).
4. then click on the first rows Type cell and select a value form the dropdonw

**Version**

- 4.19.0

**Screenshots**
![error](https://user-images.githubusercontent.com/4737815/59793509-5fb8a280-929c-11e9-9cfc-e3f7aab085f7.gif)

**Platform**
 - Windows 10
 - IE 11

**Comment by tmcconechy** [comment]
Investigating pushing the other fix for testing now.

**Comment by fitzorama** [comment]
![image](https://user-images.githubusercontent.com/20212079/59793825-246aa380-929d-11e9-905b-705ddfc56182.png)

**Comment by pwpatton** [comment]
I can also take pull a branch to verify it's fixed in landmark

**Comment by tmcconechy** [comment]
See the branch and PR if you want to test it please https://github.com/infor-design/enterprise/pull/2405 (i know phillip tried and verified it looked good)

**Comment by tmcconechy** [comment]
For this issue just retest the tooltip component a bit. The issue is only on Landmark so we dont have a way to test. But this issue was confirmed as fixed by @pwpatton

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
