### ISSUE TITLE
Datagrid: placeholder on additional Formatters.

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2408]
**Describe the bug**
A placeholder property can be placed on a datagrid column, but it is only visible when the Placeholder formatter is in use. We have a requirement to display a placeholder on a field that has a Lookup Editor, so it also requires that the Formatter is set to Lookup to trigger the control. 

Other Formatters that may require a placeholder:
* Decimal
* DropDown

**To Reproduce**
'http://localhost:4000/components/datagrid/example-placeholder.html' needs to be updated to provide an example.

**Expected behavior**
A placeholder can be added to a column without the requirement to use the Placeholder formatter.

**Version**
 v4.20.0 (master)

**Screenshots**

**Comment by tmcconechy** [comment]
Issue should be ready to test

**Comment by CindyMercadoReyes** [comment]
This issue passed QA and is now resolved.
