### ISSUE TITLE
SOHO-8056: [All Browsers] Editor Dirty Tracker Control: Dirty Tracker Alignment Issue

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#241]
1. http://470-beta-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html

2. [All Browsers] Editor Dirty Tracker Control: Dirty Tracker Alignment Issue

3. Steps to reproduce:
1. html view
2. edit text (yellow thing in wrong place)
3. go back to visual
4. go back to html

**Comment by brianjuan** [comment]
Performed testing of this in all browsers.
Bug fix is working as expected and passed the QA testing.
