### ISSUE TITLE
Datepicker: Validations stop working after body re-initialize

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#2410]
**Describe the bug**
When running `$('body').initialize();` after body already been initialized, the Datapicker validations stop working.

We need to have a two initialization steps, because we have a user login modal dialog that is initialized with en-US, when the user logs in, the system gets the user's locale (English/French/Chinese/Hebrew/etc...) and then re-initialize the page with that locale.

**To Reproduce**
1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-validation](https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-validation)
2. Type 123 in the first datepicker
3. See validation error.
4. Clear the datepicker, so validation is also cleared
5. execute `$('body').initialize();`  in console
6. repeat step 2
7. validation error doesn't appear

**Expected behavior**

**Version**

- ids-enterprise: 4.19.2

**Screenshots**

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/34129313/59852343-4cc6d080-9377-11e9-9a95-3782a70943df.gif)

**Platform**
 - OS Version: Windows 7/10
 - Browser Name Chrome/Firefox

**Additional context**
Thanks.

**Comment by jbrcna** [comment]
Test PASSED
Verified in http://master-enterprise.demo.design.infor.com/components/datepicker/test-validation-body-reinitialize.html

ALL Browser and Devices
