### ISSUE TITLE
Datagrid: Multiselect filter with source doesn't setFilterConditions correctly

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2414]
**Describe the bug**
When attempting to setFilterConditions on load of a page (to simulate navigating back to a filtered list), the conditions aren't applied to a multiselect with source.

I believe this is happening since there are no options to [find](https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L2361), so nothing is selected.

**To Reproduce**
1. Unzip [test-editor-dropdown-source-prior-filter.zip](https://github.com/infor-design/enterprise/files/3311524/test-editor-dropdown-source-prior-filter.zip) to app/views/components/datagrid
2. Navigate to /components/datagrid/test-editor-dropdown-source-prior-filter
3. See that the filter for the Action column isn't populated.

**Expected behavior**
The Action column should be set to "Place On-Hold, Request Review"

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Platform**
 - v4.20.0-dev

**Comment by tmcconechy** [comment]
When fixed please include @Sovia and @pwpatton  on the PR for review in their app

**Comment by janahintal** [comment]
Failed QA. Te grid is not loading in IE11. 
https://4200-beta1-enterprise.demo.design.infor.com/components/datagrid/test-editor-dropdown-source-prior-filter.html
![image](https://user-images.githubusercontent.com/45757016/62032036-47cd2a80-b21b-11e9-949e-838c8185f90e.png)

**Comment by brianjuan** [comment]
https://4200-rc0-enterprise.demo.design.infor.com/components/datagrid/test-editor-dropdown-source-prior-filter.html
Passed QA testing on all browsers. Datagrid is now displaying in IE.
