### ISSUE TITLE
Focus Tooltip Component: Issue with Dark and High Contrast

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2415]
**Describe the bug**
Focus Tooltip Component: Issue with Dark and High Contrast

**To Reproduce**
1. Go to url: https://4193-rc0-enterprise.demo.design.infor.com/components/tooltip/example-trigger-focus.html
2. Click on "Show Focus Tooltip" the tooltip will appear
3. Change the them to Dark or High Contrast
4. When the user clicks on Show Focus Tooltip on Dark or High Contrast the tooltip appears and disappears really fast

**Expected behavior**
The tooltip should be visible on Dark or High Contrast. 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.19.rc0]

**Screenshots**
![Tooltip Dark and High Contrast](https://user-images.githubusercontent.com/39101346/59870137-eafc6b80-9362-11e9-98ef-56ab59c0d7ae.png)

**Platform**
 - All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
In this example you need to tab into the button and then the tooltip will show. But this is working on https://4182-enterprise.demo.design.infor.com/components/tooltip/example-trigger-focus.html because click will also focus. Going to investigate if the fix i made caused this.
