### ISSUE TITLE
Calendar: Some Missing Functionality

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2419]
**Describe the bug**
- [x] 1. onMonthRendered callback in calendar settings needs to tell us what month is rendered
- [x] 2. Need CalendarEvent selection event when an event in the calendar date is clicked.
- [x] 3. Setting the events and event types through the calendar.updated(settings) doesn't seem to render calendar events once the calendar is already created.
- [x] 4. Attempting to use the legend accordion in soho-calendar demo gets stack size exceeded.

**To Reproduce**
- for 1 & 2 See calendar examples in 
- for 3 see enterprise-ng `calendar` branch and run http://localhost:4200/ids-enterprise-ng-demo/calendar-updated 
- for 4 bring up http://localhost:4200/ids-enterprise-ng-demo/calendar-monthview-legend and notice in the console the stack size limit error. Seems to be due to the calendar being created, then in init/build $.fn.initialize() is called which attempts to recreate the calendar, which causes the initialize(), ad-infinitum.

**Version**
- ids-enterprise: 4.20

**Screenshots**

**Platform**
 - windows 10, latest chrome.

**Additional context**

**Comment by janahintal** [comment]
Failed QA. Please see below. 

http://master-enterprise.demo.design.infor.com/components/calendar/test-specific-month.html# - Doesn't show the toast

http://master-enterprise.demo.design.infor.com/components/calendar/test-updated.html - When you click at the date at the bottom of the calendar. There's no way to scroll again to the calendar header.
![image](https://user-images.githubusercontent.com/45757016/60962839-d26be980-a341-11e9-9809-c1071ad6b596.png)

**Comment by tmcconechy** [comment]
@janahintal 

1) http://master-enterprise.demo.design.infor.com/components/calendar/test-specific-month.html# - Doesn't show the toast
This is not an issue not all examples need to show toasts.

2) http://master-enterprise.demo.design.infor.com/components/calendar/test-updated.html - When you click at the date at the bottom of the calendar. There's no way to scroll again to the calendar header.
- Lets make a new issue for this. We have to change the scrolling on the calendar for example
- Go to http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
- make page sorter
- no way to scroll to the items.
This is a larger change so should have a new issue.

**Comment by janahintal** [comment]
Hi @tmcconechy , thanks for the response. Created ticket #2489 for the new issue.
For #1, I think the PR #2457 includes this scenario below thats why I expected a toast. I can disregard it though if it is not needed here. 

#2419 - Part 2
is covered by functional test
but can go to http://localhost:4000/components/calendar/test-specific-month.html
click any event in the month - should see a click event toast
dblclick any event in the month - should see a dbl click event toast (and 2 click events toast)

**Comment by tmcconechy** [comment]
Ok no problem. I only added the toasts to see some events on http://localhost:4000/components/calendar/example-only-calendar.html and http://localhost:4000/components/calendar/example-only-calendar-legend.html as mentioned on the PR, didnt add them anywhere else.
