### ISSUE TITLE
SOHO-8027: Datagrid Functional Tests

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#242]
**Is your feature request related to a problem? Please describe.**
Datagrid needs tests.

**Describe the solution you'd like**

Write functional Tests
- Test events that get triggered
- Test events that are listened to
- Test all API methods, most importantly the public ones first and the rest for coverage. (fx enable/disable)
- Test lifecycle methods (init, teardown, destroy, invoke)
- Test setting and that some states are applied

**Describe alternatives you've considered**
n/a

**Additional context**
See existing tests for example dropdown, treemap, menubutton, timepicker, spinbox for reference. Also see docs/TESTING.MD for commands

**Comment by brianjuan** [comment]
Performed regression on Datagrid component, and also run functional:ci test, passed QA testing.
