### ISSUE TITLE
Editor: Tab breaks out of editor when doing indents

### ISSUE THREAD

**Issue by jblock012** [infor-design/enterprise#2421]
**Describe the bug**
When creating a list and indenting one of the items, the editor loses focus forcing the user to click inside it before they can continue typing.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index 
2. Click on the numbered list icon in the toolbar
3. Click inside the editor
4. Type some text for the first item in the list
5. Hit enter, then tab
6. When starting to type the next item, you will notice that the text editor is no longer in focus and no new text is visible.  
7. Repeat these steps with the bulleted list selection

**Expected behavior**
I should be able to indent a line item in my list and continue typing without needing to put focus back inside the editor.

**Version**

- ids-enterprise:  v4.19.2 

**Screenshots**

**Platform**
 - Device (if applicable) : Laptop
 - OS Version: Windows 10 
 - Browser Name: Chrome
 - Browser Version 75.0.3770.90 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
While triaging this issue i found a solution easily. Pushing a PR

**Comment by janahintal** [comment]
Failed QA.  Issue still exist in 
Windows 10 and macOS Mojave -  FireFox

Also, the pointing of the cursor/focus is inconsistent. In chrome, when I hit the Number list icon, the focus is moving at the start of the list, while in other browsers e.g Safari, IE and Edge the focus is still in the end of the list.

**Comment by tmcconechy** [comment]
It appears there is a browser bug as the code is running but its just not doing the indent and outdent. I cant fix this until this bug is fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1522797 

So punting on that part for now. Lets just consider that this only works in chrome for now
