### ISSUE TITLE
Homepage: Dynamically added widget isn't positioned correctly

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2425]
**Describe the bug**
When a new widget is added to a home page dynamically, it doesn't get positioned correctly. 

**To Reproduce**
1. Copy [example-add-widget.html](https://github.com/infor-design/enterprise/files/3315494/example-add-widget.zip) to /app/views/components/homepage
2. Navigate to /components/homepage/example-add-widget.html
3. Click the "Show Business Insight" button

**Expected behavior**
The widget should be added and positioned correctly. I believe that a method may need to be added quick will do the positioning. Currently, if you resize the window the layout corrects it's self, so I would like that method to be exposed in enterprise and enterprise-ng.

**Version**
- v4.20.0-dev

**Screenshots**
![IncorrectlyPositionedWidget](https://user-images.githubusercontent.com/22107636/59941039-e6e35300-9421-11e9-8534-1f75a66765c6.gif)

**Platform**
 - All

**Additional context**

**Comment by brianjuan** [comment]
http://localhost:4000/components/homepage/example-add-widget.html
http://master-enterprise.demo.design.infor.com/components/homepage/example-add-widget.html
Passed QA testing on all browsers.
![image](https://user-images.githubusercontent.com/39508864/63251330-125ab080-c2a0-11e9-8846-a69c5a900590.png)
