### ISSUE TITLE
Datagrid: column widths no longer responsive to the data

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2428]
**Describe the bug**
The datagrid used to automatically fit the data within the columns.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/test-paging-select-indeterminate-single.html'
2. Note the width and padding on the Product Name field 
3. Page to the end
4. There now is less padding on the right of the field and the value is close to the edge, if there was another value then the complete value would not be viewable.

**Expected behavior**
The data is displayed in the column and viewable

**Version**
4.20

**Screenshots**

**Additional context**
#2404 removed the lines that would recalculate the column widths based on the current data.
![image](https://user-images.githubusercontent.com/39749678/59994284-6aa37680-9692-11e9-810b-12464bc89865.png)

We have forms that will lazy load data into the datagrid using the loadData function 

![image](https://user-images.githubusercontent.com/39749678/59994599-97a45900-9693-11e9-9915-c4c08f33eaeb.png)
The widths are not recalculated when the data is loaded.
![image](https://user-images.githubusercontent.com/39749678/59994652-d0443280-9693-11e9-9664-7146296b14ee.png)

**Comment by tmcconechy** [comment]
@marknolaninfor the issue i was trying to fix was on
http://localhost:4000/components/datagrid/test-editor-dropdown-source
- if you select a value in the header
- the code reinitializes the datagrid columns and the dropdown is out of position.

Thinking maybe i can try to do that part just on page change?

**Comment by marknolaninfor** [comment]
Not corrected if sorted or filtered. 

The multiselect, date, time filters need to skip the resize and apply it on the close of the control if you do not want it to resize when the control is open.

**Comment by janahintal** [comment]
Failed QA. Sorting for https://master-enterprise.demo.design.infor.com/components/datagrid/test-paging-select-indeterminate-single.html is still incorrect
![image](https://user-images.githubusercontent.com/45757016/60428206-eec5a300-9c2a-11e9-87a0-891ad8aa8b99.png)

**Comment by marknolaninfor** [comment]
@janahintal the sorting is alpha numeric for that field, and the test data just happens to have a number in the field. This would be the expected alpha numeric sorting within a system. 

The fix is not to do with sorting, but the column widths. The width would recalculate for the new page data and pad the column correctly.

**Comment by tmcconechy** [comment]
Agree with @marknolaninfor . The sort has been like that since creation of the example as the column is not numeric. See http://4162-enterprise.demo.design.infor.com/components/datagrid/test-paging-select-indeterminate-single.html moving back to retest , feel free to move to none if no other issues
