### ISSUE TITLE
Searchfield on List/Detail Pattern: Fix expansion to properly fill sidebar Header

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#2431]
**Is your feature request related to a problem? Please describe.**
On any List/Detail pattern that contains a Searchfield on the List side's Header area, expanding the Searchfield doesn't currently fill the space well.  It ends up being too small.  See the top-left area of the screenshot below:

![Screen Shot 2019-06-24 at 12 32 06 PM](https://user-images.githubusercontent.com/3249601/60036016-3ae97400-967c-11e9-91bc-ca912b3f50db.png)

**Describe the solution you'd like**
We should fix the calculation that sets the Searchfield's width to stretch a bit better into the available Header space.

**Describe alternatives you've considered**
We could also create a special case for this pattern configuration that always causes the "fullWidth" Searchfield from the mobile view to appear, minus the collapse button.

**Additional Context**
Originally described by @tmcconechy while testing [#2407](https://github.com/infor-design/enterprise/pull/2407#pullrequestreview-252295326)

**Comment by tmcconechy** [comment]
Descoping this for now
