### ISSUE TITLE
Lookup: Support option for showing lookup in Contextual Action Panel

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#2432]
**Is your feature request related to a problem? Please describe.**
Through extensive use of the lookup component, there are many situations where the modal that's opened has complex data grids within. This often goes against our [modal guidelines](https://design.infor.com/guidelines/patterns/modals).

**Describe the solution you'd like**
Introduce an option to the lookup that allows triggering the lookup to open in a Contextual Action Panel instead of a modal. This will also allow better flexibility to shape the contextual action panel appropriately in mobile layouts to make better use of the space.

**Describe alternatives you've considered**
Leaving the lookup to trigger in a modal will only cause future issues, so we should avoid keeping it as is.

**Additional context**
![image](https://user-images.githubusercontent.com/1012017/60048910-2a94c180-969b-11e9-886a-74133da8d99e.png)
![image](https://user-images.githubusercontent.com/1012017/60048979-5152f800-969b-11e9-8cfb-58dbe0aaec75.png)

**Comment by tmcconechy** [comment]
Would this default view be turned from default into a CAP?

**Comment by nickwynja** [comment]
Probably not. I think changing the standard behavior of the component would be considered "breaking" it, unfortunately. We can teach teams to use the new option instead.

**Comment by tmcconechy** [comment]
Right, Ok. But point is that the dialog as it stands now would be considered too complex and "should" be a CAP?

**Comment by tmcconechy** [comment]
Descoping this for now.
