### ISSUE TITLE
Contextual Action Panel and Modal: Take up full width+height on mobile breakpoint

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#2433]
**Is your feature request related to a problem? Please describe.**
On mobile breakpoints, the contextual action panel has a constrained size, which cramps the content and introduces issues with zoom and scroll.

**Describe the solution you'd like**
- [x] At a mobile breakpoint, the contextual action panel should take the full height and width of the viewport so it behaves like a "sheet".
- [x] Overall, modals should contain less padding around the edges.
- [x] Contextual Action Panels should be setup to allow horizontal scrolling, if applicable. 

This also requires converting some components to using the contextual action panel instead of the simple modal. (See #2432)

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/1012017/60051505-24a1df00-96a1-11e9-8af9-7edbe2abfac9.png)

**Comment by tmcconechy** [comment]
Just to clarify we want to permanently make this one full page on mobile? http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html

![Screen Shot 2019-06-25 at 10 52 27 AM](https://user-images.githubusercontent.com/814283/60108862-5c5b6600-9737-11e9-87ad-befc8390cec3.png)

**Comment by nickwynja** [comment]
Correct. We'd remove the height and width constraints and it would cover the screen (like a whole-page takeover).

**Comment by tmcconechy** [comment]
In addition we should make the modals have less padding and scroll horizontally as per the referenced issue and https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1562057289558?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1562057289558&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Angular%20Components&createdTime=1562057289558

**Comment by EdwardCoyle** [comment]
Added Tim's bulletpoints to the original issue:

> This also requires converting some components to using the contextual action panel instead of the simple modal. (See #2432)

The work on this ticket can be done independently of #2432.  I think it's a good idea to move certain components away from the standard modal and into the CAP if they are too complex, but I'm not sure we have any "components" that need that work done at the moment... although I'm sure we could find some sample pages where that would be the case.

**Comment by VINAYREDDY59** [comment]
>, In addition, we should make the modals have less padding and scroll horizontally as per the referenced issue and https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1562057289558?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1562057289558&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Angular%20Components&createdTime=1562057289558

Hi,
Could you please update me the status of this issue?

**Comment by tmcconechy** [comment]
This is being worked on in the current sprint for version 4.22 version released on or before Oct 14th.

**Comment by janahintal** [comment]
QA Passed. Will move to Done.
Verified in http://master-enterprise.demo.design.infor.com/components/modal/example-fullsize-responsive.html
http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-fullsize-always.html
http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-horizontal-scrolling.html
