### ISSUE TITLE
App Menu: Scroll issues on mobile

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#2434]
**Describe the bug**
Open app menu on mobile breakpoints accept dragging/scrolling within body which causes jumping.

**To Reproduce**
1. On a small touch device or simulator, go to http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html
2. Open the application menu
3. Scroll down on the application container section 

**Expected behavior**
The App menu in this state is essentially a modal so it should block input to the container behind it.

**Version**
- ids-enterprise: all versions

**Screenshots**

![Jun-24-2019 17-16-00](https://user-images.githubusercontent.com/1012017/60052702-f2de4780-96a3-11e9-98dc-64fe9e13ac48.gif)

![Jun-24-2019 17-25-27](https://user-images.githubusercontent.com/1012017/60053194-3f765280-96a5-11e9-8346-5643c9cece57.gif)

**Comment by tmcconechy** [comment]
I can reproduce this.

Do we want a "focus: mobile tag? I think for this one just stop propagation on the scroll touch events on the app menu itself.

**Comment by nickwynja** [comment]
There's also the potential that (like in the second gif) that the menu is long enough or expands to be long enough that it needs to scroll as well.

**Comment by janahintal** [comment]
Hi @tmcconechy  this issue still exists **http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html** when you hover outside the appmenu, the body still scroll.

**Comment by tmcconechy** [comment]
Yeah im seeing it bounce but this page doesnt actually have any scrolling?

**Comment by jmacaluso711** [comment]
We're gonna hold on this as any fix here would be a hack. The current behavior is default for mobile browsers.

**Comment by jbrcna** [comment]
Hi, I just stumbled across this and it seems like the issue is now resolved in v4.36.0-dev
I've tried using a real device and in BS. iPhone 12 Safari. please see below clip for reference.
https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html
![Large GIF (388x664)](https://user-images.githubusercontent.com/56722184/102589402-ed9f7300-4149-11eb-9ea0-970c3e8df176.gif)

https://user-images.githubusercontent.com/56722184/102589265-b8932080-4149-11eb-8b7e-10ffd17c4c79.mp4
Browserstack: _iPhone 12 Safari_

**Comment by tmcconechy** [comment]
hi @jbrcna I think this is ok. If you try any app at all on IOS they do this bounce effect when you try and scroll up from the bottom so there is really nothing wrong / or anything we can do.

**Comment by jbrcna** [comment]
Thanks for clarifying @tmcconechy. I noticed the bounce effect in iOS. upon checking it again when you zoom in to the body then open app menu you can still scroll.
