### ISSUE TITLE
Datagrid: removeRow should also remove the row from nonVisibleCellErrors

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2436]
**Describe the bug**
The nonVisibleCellErrors contains the row information for the error, so when the row is removed it should automatically remove the information.

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/test-editable-paging-validation.html'
2. Select a row and also remove the Product Name
3. Page to the next page, so that the nonVisibleCellErrors created and visible
4. Run the following in the console 
$('#datagrid').data('datagrid').removeSelected();

**Expected behavior**
Better to automatically remove all the row data in the removeRow function.

**Version**
4.20

**Additional context**
It is also possible to remove all the rows, so the standard revalidation of row(s) will not work as non exist.

**Comment by janahintal** [comment]
QA Passed. Tested in https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-paging-validation.html across all browser, OS and devices.
