### ISSUE TITLE
SOHO-7993: Broken links on design.infor.com

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#244]
Links to examples are broken as follows:

Alerts ->
More Badge Examples
(/) working now 

Dropdown ->
States example

Inputs -> 
Textarea example

Pager ->
Paging the ListView Component
Paging the Datagrid Component

Searchfield ->
Header Searchfield (compact)
Header Searchfield (Large)

Slider Component =>
setValue() API Demo

Switch component ->
Alternate alighment example

Tabs => 
Update count example

Text Input =>
Test Area example

Tooltip component =>
Demo of setContent() api method

  Utilities

All that have examples give a 404 result when clicking the link.

   Charts 
All chart example links return a 404 page

   Unclassified ->

Hierarchy =>
Lazy Loading Example

List Filter =>
Multiselect Filter Types link

Radio Button =>
Horizontal Example (goes to example-index, not correct example)

**Comment by tmcconechy** [comment]
Fixed in PR https://github.com/infor-design/enterprise/pull/217

**Comment by tmcconechy** [comment]
@clepore Are these fixes actually deployed to https://design.infor.com/code/ids-enterprise/latest ?
I only see a 4.8.0 so i suspect the issue @brianjuan is seeing may be that these are not yet up there to test...

**Comment by CindyMercadoReyes** [comment]
This issue is now QA verified.
