### ISSUE TITLE
DataGrid: Issues with beforeCommitCellEdit

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2442]
**Describe the bug**
The `beforecommitcelledit` event has issues and doesn't really meet Landmark needs.  Would like a function/callback that is defined on a column that would be called before the cell leaves edit mode.  The function/callback mechanism would be similar to what is already in place for the column functions of `colspan` or `tooltip`.  The function would simply return a boolean reflecting whether to stay in edit mode.  The function would be synchronous like `colspan` and `tooltip`.

Looking for something similar to what was provided in 3.5 with the function `stayInEditMode`, which was called from `makeActiveCellNormal()` and `commitCurrentEdit()`.

Problem trying to solve:
When a code block cell is the active cell in the datagrid, if the user clicks on a label of an input element within the code block, want to stay in edit mode and make this input element the active element within the cell.  But the click event is being handled by this code in datagrid.js

```js
this.element.off('click.datagrid').on('click.datagrid', 'tbody td', function (e) { 
    .....
}
```

So even if I capture the click event on the label and attempt to  stop event propagation it doesn't work. 

Would need the target of the event to determine if the user has clicked on an element within the active code block cell or has clicked somewhere outside of the cell.  Clicking outside of the cell would have similar behavior that exists for any type of cell.

**Steps to reproduce the behavior:**
1. Using the existing test-editable-before-commitcelledit.html
2. Click on Price cell for row 0
3. Change the value
4. Attempt to leave the cell
5. When prompted at the dialog click on 'No'
6. Click to other cells, click back to the changed price cell
7. Never prompted again via the dialog, appears that the cell is always in edit mode

**Comment by tmcconechy** [comment]
Will put for 4.21 for now but i do have capacity to pick up a few more datagrid ones in 4.20 so probably can fix this one sooner.

**Comment by tmcconechy** [comment]
@claudenbach have you seen any 3.5 examples that show this working. I understand the rest but was looking for one to test and didnt see any. FYI i was going to back out the current beforecommitcelledit code as it isn't needed and we made it for you.

**Comment by claudenbach** [comment]
I don't have an example from 3.5 other than exercising our Landmark code.

Good idea to back out the current beforecommitcelledit code so don't have to support something we're not using.

**Comment by claudenbach** [comment]
Tim, you should put the work for this issue on hold.  We had a meeting this morning about code block in a list and we going to try an alternative solution.  If the alternative works, this particular work will not be necessary.

**Comment by tmcconechy** [comment]
Ok im basically done the event part. I was trying to see about just making the click in the editor not commit cell edit. I'll push what i've done and hold on the other part.

**Comment by claudenbach** [comment]
Sounds good.
