### ISSUE TITLE
Datagrid: Filter type text have to press enter twice to filter

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2444]
**Describe the bug**
A datagrid with a set up of disableClientFilter: true and filterWhenTyping: false, will have the user have to hit enter twice.

**To Reproduce**
1. Unzip [test-editor-dropdown-source.zip](https://github.com/infor-design/enterprise/files/3331443/test-editor-dropdown-source.zip) to app/views/components/datagrid
2. Navigate to /components/datagrid/test-editor-dropdown-source
3. Enter some string into the filter for the Product Name Column
4. Hit Enter once, see that nothing happens
5. Hit Enter again, see that the table empties.

This seems to be related to the restoreFilterClientSide variable being incorrectly used at line [2199](https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L2199) in datagrid.js

**Expected behavior**
Would only need to hit the enter button once.

**Version**

- ids-enterprise: v4.19.3

**Platform**
 - All

**Comment by lipetzan** [comment]
Is there a work-around on this for us?  This is a regression going out.

**Comment by lipetzan** [comment]
Any way to fix this in 4.19.4?  Users will have to hit enter twice when filtering datagrids

**Comment by tmcconechy** [comment]
I'll look at this next.

**Comment by tmcconechy** [comment]
I dont seem to be able to reproduce this @Sovia ? I tried dropping this in to both master and 4.19x branches. When i type enter in the text field after typing i do see the filtered event fire in the console and the grid clear out. So it seems to run right away. Is the example or steps missing something?

**Comment by Sovia** [comment]
@tmcconechy Sorry, on that example the first time works. Every other time you try and change it, it takes two enter presses

So:
1. Put in 'Com' and press enter. The filter runs
2. Clear out 'Com' and press enter. The filter fails to clear
3. Press enter again. The filter clears

**Comment by tmcconechy** [comment]
Ok working towards a patch for 4.19.4

**Comment by tmcconechy** [comment]
Fix is now deployed to 4.19.4-rc0 in npm and on https://4194-rc0-enterprise.demo.design.infor.com/components/datagrid for QA

**Comment by tmcconechy** [comment]
Found two browser issues i will PR

1. This wont load in edge https://4194-rc0-enterprise.demo.design.infor.com/components/datagrid/test-timezone-formats?layout=nofrills&locale=nl-NL
2. This page wont load in IE https://4194-rc0-enterprise.demo.design.infor.com/components/datagrid/test-editor-dropdown-source

**Comment by lipetzan** [comment]
This fixed passed our Landmark testing.
