### ISSUE TITLE
Need a different selection model for datagrid, listview, boxgrid, etc..

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2445]
**Is your feature request related to a problem? Please describe.**
The `mixed` selection mode is not being well received and we want to change a number of things about it. 

**Describe the solution you'd like**
- would like to see single selection when clicking on a list item. i.e. when an item is clicked then other selections should be cleared and the new item selected.
- If the user clicks a checkbox it should add multiple select
- if the user does ctrl-click on an item it should add it to the multiple selection
- if the user does a shift-click it should select all items from the last selected to the new selection.

**Comment by tmcconechy** [comment]
Probably need another selection setting other than mixed some folks may be using that one. Not sure what we would call it

**Comment by pwpatton** [comment]
standard?

**Comment by tmcconechy** [comment]
"both" ? as its single and multiselect?

**Comment by tmcconechy** [comment]
Also one other team had very custom select requirements so we made them this http://master-enterprise.demo.design.infor.com/components/datagrid/example-beforeselect-veto.html basically they veto the select and then do it all themselves. The event has the key info in it.

**Comment by pwpatton** [comment]
I do have a workaround for all but ctrl-click and shift-click. That might drop this one down a notch or 2 in priority.

Basically, when I get an activateRow message I set that row to selected. If there are any other rows selected I remove their selection.

**Comment by pwpatton** [comment]
Here is an animated gif of the kludge we have right now. 

![selection](https://user-images.githubusercontent.com/4737815/60210239-09121200-9822-11e9-8663-13d7f85b84f7.gif)

**Comment by pwpatton** [comment]
I think our kludge (technique?) might be good besides missing the shift-click.

**Comment by pwpatton** [comment]
I was able to get what I need working using mixed selection mode. Closing for now
