### ISSUE TITLE
Bar: Unable to use the {{value}} expression in the tooltip

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2447]
**Describe the bug**
Other chart types allow for the tooltip to be defined as a function, or contain special fields to construct the tooltip. The Bar chart type is missing this and a good comparison is the column chart.

**To Reproduce**
To create

**Expected behavior**
All chart types are able to define the tooltip in the same ways making it easier to change between some chart types.

**Version**
4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/60222086-35c63800-98bb-11e9-91ed-1d196c9f9e28.png)

**Additional context**
http://localhost:4000/components/bar/test-custom-tooltips.html will be update to have the same tooltip as http://localhost:4000/components/column/example-index.html

**Comment by janahintal** [comment]
QA Passed. Tested in https://master-enterprise.demo.design.infor.com/components/bar/test-custom-tooltips.html across all OS, browser and devices.
