### ISSUE TITLE
SOHO-7978: Right click (long press) for context menus on mobile

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#245]
Need a way to open context menus on mobile devices. On lists / datagrid and inputs.

**Comment by EdwardCoyle** [comment]
@tmcconechy think this behavior should be limited to touch events only?  Or should the "long press" also translate to held-down mouse buttons?

**Comment by tmcconechy** [comment]
@EdwardCoyle would say touch device only. We don't need it because on a desktop you would hover. So its swapping non existant hover functionality for touch longpress.

**Comment by EdwardCoyle** [comment]
That's actually a whole other issue then... we should probably have a way for field options to be permanently accessible in a touch environment

**Comment by EdwardCoyle** [comment]
Noting that work on #400 can go ahead now that #504 is merged

**Comment by EdwardCoyle** [comment]
Awaiting the merge of #573 to put together an example of the context menu being replaced by a Field Options button

**Comment by EdwardCoyle** [comment]
Ready for Q/A.  _To test:_ 

- open http://localhost:4000/components/contextmenu/example-field-options.html on a mobile device (iOS Safari/Android Chrome)
- all examples should show a working context menu attached to each field options button

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/contextmenu/example-field-options.html

Contextmenu is cropped and not scrollable in iOS devices, contextmenu will close if you attempt to scroll it.
Another issue is the focus of the previously selected field is not disappearing.
<img width="528" alt="screen shot 2018-08-16 at 4 22 43 pm" src="https://user-images.githubusercontent.com/39508864/44197701-fba3ea00-a171-11e8-8f9e-c625c2deaecf.png">

**Comment by EdwardCoyle** [comment]
@brianjuan, after some digging, the scrolling in the Popupmenu on iOS may require a larger fix than we have time for.  I've raised #645 for that one.  As far as the scrolling goes, please disregard that for this issue.

I've got a PR coming that fixes the active state issues.

**Comment by EdwardCoyle** [comment]
@brianjuan, #646 should have fixed the active state issues.  Please retest against the latest cut of `master`.  #645 contains all the popupmenu scrolling items, and has been spun off as a separate issue.

**Comment by brianjuan** [comment]
@EdwardCoyle Thanks for the update, I've tested the active state issue and now passed QA testing, will move this to Done.
