### ISSUE TITLE
Popupmenu: Updating a more menu with a submenu causes a browser console error

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2458]
**Describe the bug**
Landmark is having an error when updating a toolbar with a disabled submenu in the toolbar's overflow menu.

 I can't seem to replicate this in the ep, but after talking with @EdwardCoyle there seems to be something going wrong when the controls are rebuilding the submenu incorrectly.

For right now, a check at [popupmenu.js 601](https://github.com/infor-design/enterprise/blob/master/src/components/popupmenu/popupmenu.js#L601) to make sure submenu is defined.

**Expected behavior**
No Error in the console, and the more menu popup opening.

**Version**

- ids-enterprise: v4.19.4

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/60456217-47327b80-9bfe-11e9-93e5-e02d463a09e2.png)

**Platform**
 - All

**Comment by EdwardCoyle** [comment]
Haven't quite been able to replicate this on the EP side yet, but I briefly tested on @Sovia's local env and was seeing it.  I suspect it's some combination of: 

- AJAX-generated menu (rebuilds differently)
- Menu contains a submenu (not necessarily a disabled one)
- Submenu has previously been wrapped with a `div.wrapper` element.

I think whatever is causing the menu to be rebuilt has identified a hole in the `markupItems()` [process for correctly laying out submenus](https://github.com/infor-design/enterprise/blob/master/src/components/popupmenu/popupmenu.js#L594-L616).  Most likely, this is fixable by changing around some type-checking.

**Comment by janahintal** [comment]
QA Passed. 
Tested in http://master-enterprise.demo.design.infor.com/components/popupmenu/test-malformed-popupmenu.html across all browser, OS and devices. Thanks
