### ISSUE TITLE
SOHO-7964: Escaped modal title showing escaped characters

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#246]
When escaping the title of a modal, to prevent XSS, the title will be shown with the escaped characters, not the not the corresponding alphabetical characters.

*Reproduce*
- Start the local server in the Componenets repo and go to http://localhost:4200/modal-dialog
- Enter the following in the Dialog title input: 
```
&lt;script&gt;alert(&quot;menuXSS&quot;)&lt;/script&gt;
```
_the issue occurs here_

*Expected*: Title shown as <script>alert("menuXSS")</script>
*Actual*: Title shown as
```
&lt;script&gt;alert(&quot;menuXSS&quot;)&lt;/script&gt;
```

**Comment by tmcconechy** [comment]
This seemed to work ok now on 4.9 or coming 4.10 (i added a test page  - components/modal/test-escaped-title.html) to show this working in 4.1.0

Closing as working but test page wont show up until 4.10 or on master

**Comment by brianjuan** [comment]
http://4100-beta0-enterprise.demo.design.infor.com/components/modal/test-escaped-title.html
Passed QA testing

**Comment by anhallbe** [comment]
Was this fixed? We're seeing this in ids-enterprise@4.20.0.

Related: https://jira.infor.com/browse/LIME-3565

**Comment by tmcconechy** [comment]
I think we were thinking that you input `<script>alert("menuXSS")</script>` in the dialog. I guess the xss blocking utils are treating the & wrong. Will have to have another look

**Comment by tmcconechy** [comment]
FYI The test we have is for `message` so this was fixed for message but not modal. Working on it now.

**Comment by brianjuan** [comment]
Passed QA in all browsers.
http://master-enterprise.demo.design.infor.com/components/message/test-escaped-title.html
![image](https://user-images.githubusercontent.com/39508864/65426718-5b73c680-de43-11e9-80c6-7de9118ccfc0.png)

http://master-enterprise.demo.design.infor.com/components/modal/test-escaped-title.html
![image](https://user-images.githubusercontent.com/39508864/65426759-6f1f2d00-de43-11e9-8778-aae3aa4e61e0.png)
