### ISSUE TITLE
Dropdown Long Text Component: Tooltip appears on mobile when the page is loaded

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2465]
**Describe the bug**
Dropdown Long Text Component: Tooltip appears on mobile when the page is loaded

**To Reproduce**

1. On  iOS or Android mobile device 
2. Go to url: http://master-enterprise.demo.design.infor.com/components/dropdown/test-long-text.html
3. The tooltip appears once the page is loaded. It doesn't go away unless I click on it.  If I make another selection from the dropdown list box; again the tooltip appears and doesn't lose focus unless I click on it.
4. Please see screen shot attached. 

**Expected behavior**
The tooltip should lose focus without the user having to click on it

**Version**

- ids-enterprise: [v4.20]

**Screenshots**
![dropdown  long text](https://user-images.githubusercontent.com/39101346/60542399-d8c6e980-9ce1-11e9-81d4-964fe078b5d7.png)

**Platform**
 - Device [Latest iPhone 6 and Samsung Galaxy]

**Additional context**
None

**Comment by tmcconechy** [comment]
I think the question is why the tooltip is showing on the page initially. Im not certain why that would be. I would think it should show on long press.

**Comment by tmcconechy** [comment]
descoping this for now
