### ISSUE TITLE
Popdown: Deprecate in favor of Popover

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#2468]
**Is your feature request related to a problem? Please describe.**
The Popdown component present in the Builder Pattern (and used sporadically in some of our examples) was originally created to quickly allow for the usage of a Listview component inside of a "popover" styled element triggered from buttons.

In recent IDS versions, the Popover component has gained feature parity with the Popdown. For example, it now supports external templates with subcomponents. Popover is more full featured, and it's confusing to maintain two components that are virtually similar, so we should deprecate the Popdown in favor of Popover, since it's used less, and Popover's API handles more.

**Describe the solution you'd like**
- [ ] Make a functioning example of the Popover component containing a Listview (and other components)
- [ ] Ensure 100% feature parity on Popover component compared to Popdown component. 
- [ ] Add functional/e2e tests if necessary
- [ ] Replace the Builder Pattern examples’ usage of Popdown in favor of Popover.
- [ ] Add deprecation warnings whenever `$.fn.popdown()` is used.

**Additional context**
Originally reported on [SOHO-6531](https://jira.infor.com/browse/SOHO-6531)

**Comment by tmcconechy** [comment]
@pwpatton I just wanted to be 100% sure. Plan is to mark these as deprecated:
Step Process
Field Options
Composite Form
Popdown

As you said you dont use some of these. See any issue there? Will mark it now and remove in 3-4 months but will check first.

**Comment by tmcconechy** [comment]
Im thinking maybe we dont do this as the behavior is not on par and its used heavily in the ng project. So maybe remove the warning ? What you think @EdwardCoyle ?

**Comment by tmcconechy** [comment]
We should do this and also fix
- all popdown, popover, popxxx, tooltip bugs at the same time in one sprint task

**Comment by tmcconechy** [comment]
Closing this for now as we work on #4255
