### ISSUE TITLE
Popupmenu: Not working properly when the datagrid's parent container also contains a popupmenu

### ISSUE THREAD

**Issue by sheilamaejornadal** [infor-design/enterprise#2469]
**Describe the bug**
When you right click on the datagrid, the soho-popupmenu of the parent container shows before the context menu of the datagrid.

**To Reproduce**
1. Go to https://github.com/infor-design/enterprise-ng.git to get sample project
2. Open datagrid-dynamic.demo.html and datagrid-dynamic.demo.ts
3. Copy and paste the contents from the attached files on both html and ts file
4. Run the project
5. Go to the datagrid dynamic demo
6. Open the developer tool
7. Put a breakpoint to the onContextMenu() method of the datagrid-dynamic.demo.ts
8. Right click on the datagrid
9. Click F8
10. See gif for detailed steps

**Expected behavior**
When you right click on the datagrid, the soho-popupmenu of the parent container should not be shown before the context menu of the datagrid.

**Version**
- ids-enterprise: 5.5.0

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 75.0.3770.100 (Official Build) (64-bit)

**Additional context**
For any clarifications, you may contact me at sheilamae.jornadal@infor.com
[datagrid-context-menu-issue.zip](https://github.com/infor-design/enterprise/files/3362567/datagrid-context-menu-issue.zip)

**Comment by tmcconechy** [comment]
I can see why it would be problematic for multiple reasons to put a right click on an element and on its direct parent. Whats the real use case as from the example this doesn't seem very useful? Could you just remove the top level menu?

Something like a page level right click menu AND a context menu on the grid? Going to look to make an Enterprise example of this based on actual feedback on the real use case.

**Comment by sheilamaejornadal** [comment]
We can't just remove the top level menu because the panel (which is the direct parent of the datagrid) is configurable by right clicking on it. On the other hand, we also need to have the context menu on the datagrid to perform another operation on each row.

**Comment by tmcconechy** [comment]
OK i'll see what we can do about this for a future fix.

**Comment by tmcconechy** [comment]
Descoping some issues for now we wont have time for
