### ISSUE TITLE
SOHO-7946: I like Links with my Toast in the morning

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#247]
Allow hyperlinks in the toast message.

You can see my use case in http://jira.lawson.com/secure/attachment/942586/screenshot-1.png - see http://jira.lawson.com/browse/LMCLIENT-19493.

We had another use-case where if a record is created from a list we could present a link to that newly created record. Much like Jira does when you create a new Jira issue.

See SOHO-7818 for more context and XSS concerns

**Comment by tjamesallen15** [comment]
https://jira.infor.com/browse/SOHO-7946 Resolved.

**Comment by tmcconechy** [comment]
James, We still need this done. I only closed the Jira as this is the correct issue to be using now as we are now using just the github issues. The Jira ones will be closed off but we still need to do all the github ones.

**Comment by tjamesallen15** [comment]
For Testing..
Check localhost:4000/components/toast/test-allow-links.html
See if the toast from the button has a link added.

**Comment by brianjuan** [comment]
Enhancement is working as expected across all browsers and passed QA testing.
![image](https://user-images.githubusercontent.com/39508864/42870276-61ff2272-8a45-11e8-9ac0-eb03c378488d.png)
