### ISSUE TITLE
Calling datagrid loadData causes an unexpected unSelectAllRows() to be called.

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2470]
**Describe the bug**
In landmark we manage the initial selection state of a list when calling loadData. We also call loadData through the angular component which doesn't give us the option of passing in pagerOptions (which isn't really needed for us since we aren't using the paging functionality in datagrid).

**To Reproduce**
1. make a datagrid sample be mixed selection mode. 
2. listen for selected row event from datagrid and set a break point in there
3. Call loadData for the first time. 
4. Notice that selected event is fired during a load data due to 
```
 if (this.settings.source) {
    this._selectedRows = [];
  } else if (pagerInfo.type === 'initial' || !pagerInfo.type) {
    this.unSelectAllRows();
  }
```
https://github.com/infor-design/enterprise/blob/28f3a61b26626a78f1090a9bcbffce160d85ff0a/src/components/datagrid/datagrid.js#L791

**Expected behavior**
No selection event should be called from loadData when pagerInfo is undefined.

**Version**
4.19

**Platform**
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
What if we simply add a check there for "if any rows are selected". I think that should cover the cases?

**Comment by pwpatton** [comment]
that would work for me!

**Comment by pwpatton** [comment]
any way we could patch 4.19 with this one?

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/example-mixed-selection.html
Passed QA on all browsers, will retest once beta is deployed.
