### ISSUE TITLE
Charts: Need ability to disallow selection on a chart

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2471]
**Describe the bug**
Need the ability to disallow default/initial selection (this.setInitialSelected()) for charts (pie.js, column.js, line.js, and radar.js). 

**To Reproduce**
1. Go to a pie.js chart for example
2. Notice pie.setInitialSelected is always called from pie,build().

**Expected behavior**
Need a way to disable disallow default/initial selection but still keep selection. 
Suggest a new option `initialSelection = 'off' | 'on"?` added to all charts.

**Comment by tmcconechy** [comment]
Made this a 5 its easy but needs to be applied to a bunch of charts

**Comment by pwpatton** [comment]
yea, and it's not selection that's the issue but the initially selected event that's causing the issue.

**Comment by tmcconechy** [comment]
As discussed try and check if you have selected: true set in the data for the chart. If you turn that off it should not initially set anything as selected. See if this works.

**Comment by pwpatton** [comment]
Issue was in my code when setting the selected in the data.
