### ISSUE TITLE
Icon: Empty State Widgets disappeared when using the uplift theme

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2474]
**Describe the bug**
Three of the empty state widget icons disappear when using the uplift theme.

**To Reproduce**
1. Go to the Icon page in the ng-demo app
2. Change the theme to uplift
3. Scroll down to the Icons - Empty State Widgets section

**Expected behavior**
Should be able to see all the icon

**Version**
- ids-enterprise-ng: v5.2.1

**Screenshots**
Uplift theme:
![image](https://user-images.githubusercontent.com/22107636/57080805-f1525d80-6cb8-11e9-81c7-c93c19f439ea.png)

Light theme:
![image](https://user-images.githubusercontent.com/22107636/57080862-1515a380-6cb9-11e9-9b58-1c9884e8af87.png)

**Platform**
 - All

**Comment by tmcconechy** [comment]
This can also be reproduced by simply going to uplift theme on the icons:
http://localhost:4000/components/icons/example-empty-widgets.html?theme=uplift&variant=light&colors=0563C2

**Comment by tmcconechy** [comment]
It appears that some of these icons are missing fill: "fillColor". Perhaps this change is in the ids-design repo/tokens

**Comment by janahintal** [comment]
QA Passed. Tested in all Browser, OS and devices Thanks. 
Verified in http://master-enterprise.demo.design.infor.com/components/icons/example-empty-widgets.html?theme=uplift&variant=dark&colors=0563C2
