### ISSUE TITLE
Difference in colour Azure and Default

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2476]
**Describe the bug**
The colour Azure and Default display differently as the default colour does not calculate the text colour. Should they be different? 

**To Reproduce**
1. Go to 'http://localhost:4000/components/list' any form
2. Default is loaded by default 
3. Click on the more button and select Azure
4. Click on the more button and select Default

**Expected behavior**
The header colour looks the same, so the user may ask is my default azure and if so why is it different

**Version**
Master

**Screenshots**
Default
![image](https://user-images.githubusercontent.com/39749678/60935737-0deac180-a30a-11e9-9f78-c98cfee14875.png)
Azure
![image](https://user-images.githubusercontent.com/39749678/60935757-1fcc6480-a30a-11e9-94ae-642bbdd05622.png)

**Additional context**
We allow for a site to specify the default colour, eg one for Production and another for Testing, so we initialise the colour with a value and not the empty default. It is hard to explain to testers and end users that are comparing with the ids site the azure is not initially loaded, but a "default" version of azure.

**Comment by tmcconechy** [comment]
This has recently regressed the text used to be whit.

- go to https://master-enterprise.demo.design.infor.com/components/form/example-inputs.html?theme=soho&variant=light&colors=56932e
- pick any color in the ... menu like amber azure or amythest 

Probably from https://github.com/infor-design/enterprise/pull/2456

@deep7102 maybe we have to make that a setting or for home page only

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/
Passed QA testing on all browsers, Azure and Default colors are now correct. Also tested with different Themes and Variants. Will retest once beta is deployed.
