### ISSUE TITLE
SOHO-7909: Lookup control - Select all checkbox when filtering

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#248]
Steps to reproduce:

1. Open the modal
1. Use the search control (e.g. use a criteria that return 2-3 records)
1. Click on “Select All” check box

Expected behaviour: it should return only the selected ones (i.e. 2 - 3 records)
Actual behaviour: it is returning all items from list without considering the filter

I have tested it with 4.5 version *angular components*

**Comment by tmcconechy** [comment]
This issue wasn't closed on link. Details can be found on https://github.com/infor-design/enterprise/pull/280

**Test Info**:
http://localhost:4000/components/lookup/example-multiselect
- Open above link
- Click on lookup field to open modal
- Type "205" and press Enter key in search field
- It should filter with two results (Product Id - 2542205 and 2642205)
- Click on checkbox in header to select all (both rows)
- Click modal button "Apply"
- It should close the lookup modal
- In lookup field should add those selected items (Product Id - 2542205 and 2642205)

**Comment by brianjuan** [comment]
This bug fix is working as expected across all browsers and passed QA testing.
