### ISSUE TITLE
Pager: destroying page size menu leaves artifacts causing a memory leak

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#2482]
**Describe the bug**
When the page size menu on the Pager is destroyed, some DOM elements remain which for some applications using Angular can eventually cause issues with memory usage.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/pager/example-standalone.html
2. Click on Show Page Size Selector checkbox to display the page size menu
3. Click on Attach Page Size Menu to Body checkbox
4. In the browser debugger under the Elements tab, you should see a div element with the class name of 'popupmenu-wrapper bottom'
5. Expand the div element to display the child ul and div elements
6. Uncheck the Attach Page Size Menu to Body checkbox
7. The child ul and div elements remain

**Expected behavior**
Expect the child ul and div elements to be removed with their parent element.

**Version**

- ids-enterprise: v4.20.0-dev

**Screenshots**
![pager-standalone-destroy-issue](https://user-images.githubusercontent.com/20212079/61071112-e06b4a00-a3d5-11e9-8d93-affc25026b9a.gif)

**Platform**
 
**Additional context**
Since the page control uses the popupmenu control internally, this may be more of an issue with the popupmenu. 

This is a Landmark issue that is causing a severe memory leak.

**Comment by EdwardCoyle** [comment]
I discovered this same issue while working on #2356.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Attaching a screen shot of the .popupmenu-wrapper element directly inside the <body> tag is no longer there.
<img width="1314" alt="Standalone component" src="https://user-images.githubusercontent.com/39101346/61241151-f6984380-a710-11e9-890b-c883fcad6730.png">
