### ISSUE TITLE
Functional Tests: Use `cleanup()` method throughout to prevent leftover artifacts

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#2484]
**Is your feature request related to a problem? Please describe.**
Many of the functional tests in our test suite have a problem where some elements that are generated in each sandbox aren't properly cleaned up and removed when the test completes.  Since the test suite doesn't run functional tests in any specific order (by design), this can occasionally cause random test failures.  

For example: if an ID attribute is accidentally duplicated, or a menu isn't closed when it's expected to be closed.  

Another example: Some of the tests will target the "first" element of a certain type, but if there are duplicates, sometimes the wrong one will get targeted for use by a test, and the result may not match what's expected.

You can see duplicates in a test suite locally by doing the following:
- Pull `master` and run the demoapp
- In a code editor, open `test/components/colorpicker/colorpicker-aria.func-spec.js`
- change the `describe()` statement to an `fdescribe()` statement.
- in a terminal, run the test suite with `npm run functional:local`
- in a browser, open the debugger's URL: http://localhost:9876/debug.html
- allow the test suite to complete.  Where there should be a completely blank screen, you will see something like the below screenshot:

![Screen Shot 2019-07-12 at 10 22 23 AM](https://user-images.githubusercontent.com/3249601/61135083-f557e400-a48e-11e9-9f7b-45228741f49f.png)

**Describe the solution you'd like**
We implemented a [helper method](https://github.com/infor-design/enterprise/blob/master/test/helpers/func-utils.js#L6) that takes an array of CSS selectors that will be targeted for removal.  We need to revisit each test suite file and use this method along with component `destroy()` methods to ensure all component instances are removed before the next test suite runs.

Using this method, we should target all specific elements, `.svg-icons` and `.row` elements in a test sandbox to clean them up and remove them after each test is run. Additionally, we should be destroying each component instance that's tested where it makes sense.

**Comment by tmcconechy** [comment]
descoping this for now
