### ISSUE TITLE
Calendar: Unable to scroll for smaller screens

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2489]
**Describe the bug**
Calendar: Unable to scroll for smaller screens

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html 
http://master-enterprise.demo.design.infor.com/components/calendar/test-specific-month.html#
2. lick at the date at the bottom of the calendar. There's no way to scroll again to the calendar header.

**Expected behavior**
Be able to scroll for smaller screen size 

**Version**
Beta 4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/60962839-d26be980-a341-11e9-9809-c1071ad6b596.png)

**Platform**
All OS & Browsers. 

**Additional context**
NA

**Comment by davidcarlsonberg** [comment]
Looks like the `is-fullsize` class on `.calendar-monthview .monthview` is preventing scroll of overflow.
![is-fullsize](https://user-images.githubusercontent.com/7952168/62058388-5d2c5f80-b1ef-11e9-9b3b-21cda9cee91e.png)

**Comment by tmcconechy** [comment]
Yeah i think that was pat of the reason i punted this originally. I think we need some parent wrapper to scroll as the calendar itself is 100%.

**Comment by janahintal** [comment]
QA Passed. 
Re-tested in https://4200-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html#  https://4200-rc0-enterprise.demo.design.infor.com/components/calendar/test-specific-month.html# across all browser, os and devices. Thanks!
