### ISSUE TITLE
SOHO-7839: [All Browsers] Data Grid Editable Control: Price Column giving "Nan" error

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#249]
1. http://usalvlhlpool1.infor.com/4.6.0-rc/components/datagrid/example-editable.html

2. [All Browsers] Data Grid Editable Control: Price Column giving "Nan" error

3. Steps to reproduce:
- Click on any cell in the Price column
- Remove the text from the field box
- Click out of the cell. You will get "Required" icon 
- Click back into the same cell and start type anything and click out of the cell
- The "NaN" error appears in the field box. Please see screen shot attached. 

****** Also the page record is not working correctly****

**Comment by tmcconechy** [comment]
Fixed in https://jira.infor.com/browse/SOHO-7839
And PR https://github.com/infor-design/enterprise/pull/208
