### ISSUE TITLE
Export: Separator in exportToCsv method is not working as expected

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#2490]
**Describe the bug**
Specifying a separator in exportToCsv method changes just the first line of file, data are always separated by comma ','.

**To Reproduce**
1. Go to /src/utils/excel.js
2. check line 357 for hardcoded comma - csv.push(rowContent.join('","'));

**Expected behavior**
Output file data should be separated by chosen character.

**Version**
Latest

**Comment by tmcconechy** [comment]
As discussed the fix could be to:
1. Make the seperator option either accept "sep=;" as before which just adds a first line to the document as now
2. Also make the seperator option either accept ";" or "," which will add the sep line and change the document seperator
3. Need a way to do either of the two options (change document seperator and first line) things or both or none with the API

**Comment by hohnzy** [comment]
I think the method should accept separator as a string (usually one char like , ; | etc) and a boolean if we want that sep=<separator> included as 1st line.

**Comment by tmcconechy** [comment]
I agree but we probably want to try to keep the API backwards compatible which could get messy. Maybe since this was introduced for one team we could see if they would buy in to a change they can adjust for.

**Comment by hohnzy** [comment]
Anything new about this one? In my opinion when its implemented like right now just for one team it should be changed to my proposal. Otherwise its useful only for them in that case...

**Comment by tmcconechy** [comment]
I'll put it in next sprint. I did not think was a big issue. Many teams use this feature. We just added the separator per spec and I consider this an additional issue. But we'll fix it.

**Comment by janahintal** [comment]
QA passed. Will Move to Done. 
Verified in http://master-enterprise.demo.design.infor.com/components/datagrid/test-export-custom-separator.html
