### ISSUE TITLE
Lookup: Destroy test case not working and causes memory leak

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#2494]
**Describe the bug**
Calling the destroy api on a lookup control doesn't release the control from memory. These memory leaks can build up over time in a SPA and cause the browser window to slow down and crash.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/test-destroy
2. Open the Memory tab in Chrome Developer Tools
3. Click on the 'Destroy' button
4. Click the 'Collect garbage' button to make sure the browser has collected garbage
5. Click the 'Take snapshot' button to see the memory heap.
6. Filter the results in the snapshot to 'lookup' and you will see that the instance of the Lookup control is still in memory.

**Expected behavior**
After calling the destroy api on a lookup control it should no longer exist in memory. The destroy method needs to properly cleanup/remove things so that garbage collection will remove the control from memory.

**Version**
- ids-enterprise: v4.19.4

**Screenshots**
![image](https://user-images.githubusercontent.com/14128010/61306807-31ef4c80-a7bb-11e9-9786-602da225831f.png)

**Platform**
 - Device: Dell Laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 75.0.3770.142 (Official Build) (64-bit)

**Comment by brianjuan** [comment]
http://localhost:4000/components/lookup/test-destroy.html#
http://master-enterprise.demo.design.infor.com/components/lookup/test-destroy.html
Passed QA testing on Mac and Windows Chrome, and IE 11.
![image](https://user-images.githubusercontent.com/39508864/63250168-8fd0f180-c29d-11e9-9350-57433aa216e4.png)
