### ISSUE TITLE
Lookup Component: Scroll bar not visible on the Product list pop up window

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2495]
**Describe the bug**
Lookup Component: Scroll bar not visible on the Product list pop up window

**To Reproduce**
1. Go to url: http://master-enterprise.demo.design.infor.com/components/lookup/example-index.html or http://master-enterprise.demo.design.infor.com/components/lookup/example-custom-buttons.html
2. On Win 10 IE 11 make the page responsive
3. Click inside the Product field box and click the down arrow key. The Product List window will appear
4. The scroll bar to go up or down the list is not visible on responsive view

**Expected behavior**
The scroll bar should be visible for the user to be able to scroll up or down the Product list grid.  Please see multiple screen shots attached. 

**Version**

- ids-enterprise: [v4.19]

**Screenshots**
![Lookup Scroll Bar Second Issue](https://user-images.githubusercontent.com/39101346/61316938-f612b200-a7cf-11e9-92b9-dc0b92c2f4d1.png)
![Lookup Scroll Bar Issue](https://user-images.githubusercontent.com/39101346/61316939-f612b200-a7cf-11e9-9be4-13564eee2373.png)
![bs_realios_Mobile_iPhone XS-12 0(1)](https://user-images.githubusercontent.com/39101346/61316964-02970a80-a7d0-11e9-90fb-52e1ec8f2085.jpg)

**Platform**
 - Device (if applicable) [iPhone XS ]
 - OS Version: [Windows 10]
 - Browser Name [IE 11]

**Additional context**
None

**Comment by tmcconechy** [comment]
- This issue only happens on IE (which we will gradually descope)
- It also only happens if you open the list while wide and then make it smaller to responsive when open
- Happened in every version back to 4.4

**Comment by tmcconechy** [comment]
Descoping this issue for now see https://github.com/infor-design/enterprise/issues/3026
