### ISSUE TITLE
Toolbar: Destroy test case not working and causes memory leak

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#2496]
**Describe the bug**
Calling the destroy api on a Toolbar control doesn't release the control from memory. These memory leaks can build up over time in a SPA and cause the browser window to slow down and crash.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/toolbar/test-destroy
2. Open the Memory tab in Chrome Developer Tools
3. Click on the 'Destroy' button
4. Click the 'Collect garbage' button to make sure the browser has collected garbage
5. Click the 'Take snapshot' button to see the memory heap.
6. Filter the results in the snapshot to 'toolbar' and you will see that the instance of the Toolbar control that was supposed to be destroyed is still in memory. (Note: The 2nd instance of Toolbar in memory is from the page header.)

**Expected behavior**
After calling the destroy api on a control it should no longer exist in memory. The destroy method needs to properly cleanup/remove things so that garbage collection will remove the control from memory.

**Version**
- ids-enterprise: v4.19.4

**Screenshots**
![image](https://user-images.githubusercontent.com/14128010/61318055-307d4e80-a7d2-11e9-9a8c-d1788d9f8aaf.png)

**Platform**
 - Device: Dell Laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 75.0.3770.142 (Official Build) (64-bit)

**Comment by brianjuan** [comment]
Toolbars are still found in Memory after Destroy and collecting garbage in https://4200-rc0-enterprise.demo.design.infor.com/components/toolbar/test-destroy?layout=nofrills.
But working as expected in http://master-enterprise.demo.design.infor.com/components/toolbar/test-destroy?layout=nofrills

![image](https://user-images.githubusercontent.com/39508864/62437761-38983080-b777-11e9-9cd6-d46660e8a108.png)

**Comment by EdwardCoyle** [comment]
Not totally sure why it's still like that in the RC branch... from what I can tell the fix was merged here:  https://github.com/infor-design/enterprise/commit/4d1697a29d9d5632a6df27734c47391227b76287

**Comment by tmcconechy** [comment]
Ok lets move it back to rest in rc and they can retest on rc1?

**Comment by brianjuan** [comment]
http://4200-rc1-enterprise.demo.design.infor.com/components/toolbar/test-destroy?layout=nofrills
QA Passed, tested in Mac and Windows Chrome.
![image](https://user-images.githubusercontent.com/39508864/62678596-836ab000-b9e4-11e9-9483-91c7c12a50f1.png)
