### ISSUE TITLE
Modal: Destroy test case not working and causes memory leak

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#2497]
**Describe the bug**
Calling the destroy api on a Modal control doesn't release the control from memory. These memory leaks can build up over time in a SPA and cause the browser window to slow down and crash.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/modal/test-destroy-on-close.html
2. Open the Memory tab in Chrome Developer Tools
3. Click on the button to open the modal, then click Cancel to close the modal (which calls destroy)
4. Click the 'Collect garbage' button to make sure the browser has collected garbage
5. Click the 'Take snapshot' button to see the memory heap.
6. Filter the results in the snapshot to 'modal' and you will see that the instance of the Modal control that was supposed to be destroyed is still in memory.

**Expected behavior**
After calling the destroy api on a control it should no longer exist in memory. The destroy method needs to properly cleanup/remove things so that garbage collection will remove the control from memory.

**Version**
- ids-enterprise: v4.19.4

**Screenshots**
![image](https://user-images.githubusercontent.com/14128010/61319894-44c34a80-a7d6-11e9-8f88-68fb8ffcaab1.png)

**Platform**
 - Device: Dell Laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 75.0.3770.142 (Official Build) (64-bit)

**Comment by janahintal** [comment]
QA Passed. Working as expected. 
Tested in http://master-enterprise.demo.design.infor.com/components/modal/test-destroy-on-close.html & http://master-enterprise.demo.design.infor.com/components/lookup/test-destroy.html
