### ISSUE TITLE
Pager API Updates - To Support Listview having number of records dropdown

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#250]
**Is your feature request related to a problem? Please describe.**
Cardview lists should have the dropdown for number of records shown in the footer along with the paging controls. in order to do this in angular/landmark pager.js needs some refactors.

**Describe the solution you'd like**

- Would like settings to indicate which controls should be used in the pager
```
next
prev
first
last
page input
page size selector
pager list buttons
```
- Trigger events when paging actions happen

- Use only events to other components instead of directly linking componentAPI setting 

- All updates and control state would take place by a function in pager. (enableFirstButton, enableLastButton for example).

- Existing functionality not broken in any way.

**Strawman**
```
<soho-pager  
   [hasPageSizeChooser]=true
 
   [hasFirstButton]="'true'"
   [enableFirstButton]="enableFirstButton"
   ...
 
  (firstButtonClicked)="onFirstButtonClicked()"
  (pageSizeChanged)="onPageSizeChanged()"
```

**Additional context**
Issue combined with https://github.com/infor-design/enterprise/issues/438
Formerly SOHO-7823 and SOHO-6841

**Comment by brianjuan** [comment]
Found some issues on the existing pager example pages. Both of these issues are not in previous version 4.11.0.

Issue 1: http://localhost:4000/components/pager/example-datagrid.html
Page number is now allowing user to type a number beyond the last page, you can even click on the next page button.
![pagerdatagrid](https://user-images.githubusercontent.com/39508864/47420483-1f5a6080-d7b1-11e8-9517-efac4cfe9b76.gif)

Issue 2: http://localhost:4000/components/pager/example-listview.html
Issue on the vertical scroll bar, it's scrolling beyond the limit
![pagerlistview](https://user-images.githubusercontent.com/39508864/47420933-203fc200-d7b2-11e8-99dd-7a7f1f2c4975.gif)

This one I'm not sure if is a valid issue.
http://localhost:4000/components/pager/example-standalone.html
Page size selector is not showing on mobile.

**Comment by tmcconechy** [comment]
Pushed a fix for 1 and 2 for the next build.
3) (page size selector is not showing on mobile) is by design because there is not enough room for it.

**Comment by brianjuan** [comment]
http://4120-rc2-enterprise.demo.design.infor.com/components/pager/example-datagrid.html
http://4120-rc2-enterprise.demo.design.infor.com/components/pager/example-listview.html
http://4120-rc2-enterprise.demo.design.infor.com/components/pager/example-standalone.html
Passed QA testing on all browsers.
