### ISSUE TITLE
DateTime: There is no proper format for dateTime included with seconds like "M/d/yyyy h:mm:ss a" and Invalid/ wrong error message

### ISSUE THREAD

**Issue by VINAYREDDY59** [infor-design/enterprise#2500]
**Describe the bug**
We have a requirement of dateTime picker which gives us "M/d/yyyy h:mm:ss a" format.
In this case i don't see any format like i have mentioned above in "Soho.Locale.currentLocale.data.calendars[0].dateFormat"
And also if we type in only date or remove time from dateTime it is giving an error alert like 
"Invalid Date". The thing we are modifying the dateTime so, It should show "Invalid DateTime".
could you please resolve it for us.

**Reproducing Steps for Error Message**
1. Goto dateTime picker.
2. Select date and Time.
3. Then try to edit it by removing the time.
4. Then you can see the error message "Invalid Date".

**Expected behavior**
There should be a format for "M/d/yyyy h:mm:ss a" also.
The Error message should be corrected.

**Comment by tmcconechy** [comment]
@VINAYREDDY59 This can be done similarly to the example https://github.com/infor-design/enterprise/blob/master/app/views/components/datepicker/test-12hr-time.html you can either pass the options in to the data-options if you are using the global `initialize` like this:

```html
    <div class="field">
      <label for="datetime-field-time" class="label">12 hr time no padding (h:mm a)</label>
      <input id="datetime-field-time"  class="datepicker datetime" name="datetime-field" type="text" data-options="{'dateFormat': 'M/d/yyyy', 'showTime': 'true', 'timeFormat': 'h:mm:ss a'}" value=""/>
    </div>
```

Or you can pass the options in like this to the plugin:

```js
$("#datepicker-id").datepicker({
  dateFormat': 'M/d/yyyy', 
  showTime: true,
  timeFormat': 'h:mm:ss a'
});
```

See also the docs https://design.infor.com/code/ids-enterprise/latest/datepicker
