### ISSUE TITLE
Grouped Column Chart:  Does not display graph as expected for 1 data point

### ISSUE THREAD

**Issue by cshirole** [infor-design/enterprise#2505]
**Describe the bug**
Grouped Column  Chart does not display as expected when there is only one data point.

**To Reproduce**
1. Set up your enterprise project 'https://github.com/infor-design/enterprise'
2. Go To https://github.com/infor-design/enterprise/blob/master/app/views/components/column-grouped/example-index.html
3. Set dataset to following
  ```
   var dataset = [{
        data: [{
            name: 'Jan',
            value: 12
        }, {
            name: 'Feb',
            value: 11
        }, {
            name: 'Mar',
            value: 14
        }, {
            name: 'Apr',
            value: 10
        }, {
            name: 'May',
            value: 14
        }, {
            name: 'Jun',
            value: 8
        }],
        name: 'Component A'
      }]
  ```

**Expected behavior**
Column's should be grouped and not separated from each other.

**Version**
- ids-enterprise: 4.19.0

**Screenshots**
![1Record](https://user-images.githubusercontent.com/42473822/61453827-cb199100-a97c-11e9-9a0b-ba38bae0b07b.JPG)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome, IE

**Comment by cshirole** [comment]
Hi @tmcconechy ,
I have updated the Description as per the template. Please let me know if there is anything else that is required.

Thanks.

**Comment by tmcconechy** [comment]
Descoping some issues for now we wont have time for
