### ISSUE TITLE
Column Chart: yAxis option does not work for bar graph when only one data item

### ISSUE THREAD

**Issue by cshirole** [infor-design/enterprise#2506]
**Describe the bug**
The `yAxis` option does not work for bar graph when only one data item

**To Reproduce**
1. Set up your enterprise project 'https://github.com/infor-design/enterprise'
2. Go To "https://github.com/infor-design/enterprise/blob/master/app/views/components/column/test-axis-y-format-integer.html"
3. Scroll down to 
```
         yAxis: {
               ticks: {
               number: 5, // Tip: round max data value
               format: 'd'
            }
```
4. Change `number: 5`  to `number: 1`
5. Notice the y-axis values.

**Expected behavior**
Only 0 and 1 should be displayed on Y-axis. 

**Version**
- ids-enterprise: 4.19.0

**Screenshots**
![Bargraph](https://user-images.githubusercontent.com/42473822/61451948-40cf2e00-a978-11e9-98b9-5de1c3704470.JPG)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Windows 10
 - Browser Name: Chrome, IE

**Additional context**
For line graph this works as expected.

**Comment by cshirole** [comment]
Hi @tmcconechy ,
I have updated the Description as per the template. Please let me know if there is anything else that you need.

Thanks.

**Comment by tmcconechy** [comment]
Complete with https://github.com/infor-design/enterprise/issues/2505

**Comment by tmcconechy** [comment]
Descoping some issues for now we wont have time for
