### ISSUE TITLE
Lookup: Unable to remove previously selected value in a single select lookup dialog

### ISSUE THREAD

**Issue by cshirole** [infor-design/enterprise#2507]
**Describe the bug**
When using a single select lookup it is not possible to remove/clear value by opening the dialog.

**To Reproduce**
1. Go to 'Go to http://master-enterprise.demo.design.infor.com/components/lookup/example-index.html'
2. Click on 'icon to open the lookup'
3. Select one  'value'
![SL1](https://user-images.githubusercontent.com/42473822/61452830-52193a00-a97a-11e9-93ce-96fd35041819.PNG)
4. Click on the icon to open the lookup again and try deselecting and clearing the value. You cant as there is no way to clear it.
![SL2](https://user-images.githubusercontent.com/42473822/61452880-71b06280-a97a-11e9-868c-71252ff07890.PNG)

**Expected behavior**
User should be allowed to clear previously selected value

**Version**

- ids-enterprise: 4.20.0

**Screenshots**

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome, IE

**Comment by cshirole** [comment]
Hi @tmcconechy ,
I have updated the Description as per the template. Please let me know if there is anything else that you need.

Thanks.

**Comment by dhumalkishor** [comment]
Hi Tim, any updates on this? When it will be get fixed?

**Comment by tmcconechy** [comment]
I can put it in the same sprint as https://github.com/infor-design/enterprise/issues/740

**Comment by ericangeles** [comment]
Picking up as this is related to #740 that am currently fixing.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Tested this ticket using URL: https://master-enterprise.demo.design.infor.com/components/lookup/example-clearable.html
