### ISSUE TITLE
Tooltip: Title doesn't display when the tooltip title value starts with `#`.

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise#2512]
**Describe the bug**
Tooltip title doesn't display when the tooltip title value starts with `#`.

**To Reproduce**
Example code
```
<button id="tooltip-btn" class="btn-secondary" type="button" title="#388383 - Emerald">
      Normal Tooltip
    </button>
```

**Expected behavior**
Tooltip title should display with title value starts with `#`

**Version**

- ids-enterprise: 4.19.4

**Screenshots**
**N.A.**

**Platform**
 - Device (if applicable) **N.A.**
 - OS Version: Windows 10, MacOS Mojave
 - Browser Name: Chrome
 - Browser Version: Version 75.0.3770.142 (Official Build) (64-bit)

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
This is caused be https://github.com/infor-design/enterprise/blob/master/src/components/tooltip/tooltip.js#L386 i think this code should be changed to not return false if the element isnt found. We need to review history on that code.

As a workaround make sure the # is not first for example `title="Emerald - #388383"`

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/tooltip/test-tooltip-starts-with-pound-sign.html
![image](https://user-images.githubusercontent.com/56722184/87288478-faca8d00-c52d-11ea-81ec-a50ba8fd9176.png)
