### ISSUE TITLE
Calendar: Add more event callbacks, overflow and a day view

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#2518]
**Describe the bug**
Missing functionalities in calendar component.

**To Reproduce**
Go to http://master-enterprise.demo.design.infor.com/components/calendar/test-specific-month.html

**Expected behavior**

- [x] Day view (Moved to https://github.com/infor-design/enterprise/issues/2780)
- [ ] Hover event
- [x] Show overflow events  (beyond the visible ones) - we will use day view for this or by having events on the right side http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
- [ ] Right click event callback 

**Version**

- ids-enterprise: v4.19

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 75.0.3770.142 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
@vonnyw can you explain some of these things and what you would do in them

- Day view - we do not have a design yet for a day view
- Hover event -> just a callback?
- Show overflow events (beyond the visible ones) -> not sure what you are referring to
- Right click event callback -> we do have a menu in this example so not 100% sure what more would be needed?

**Comment by vonnyw** [comment]
@tmcconechy Any update on calendar?

**Comment by tmcconechy** [comment]
Not yet. We still need a day view design for one thing. Can you answer some of my questions in the previous comment.

We might have to split this up into a couple issues but some of it we can try to do next sprint

**Comment by tmcconechy** [comment]
For hover event callback can you just use the tooltip plugin ?

**Comment by vonnyw** [comment]
I see, no design on day view just yet.....I have answered the questions on your previous comment. I can try using tooltip plugin for hover event callback.

**Comment by tmcconechy** [comment]
Oh I see you answered in it. Ok I will work up some examples on everything but the day view and ask around for that.

**Comment by vonnyw** [comment]
@tmcconechy I am currently working on item #2 and #4 on this ticket. (hover and right click callback) and will be submitting PR when they are fully tested. Day view remains to be an important item (this will be the view we switch to when there is an overflow on each day in month view).

**Comment by tmcconechy** [comment]
Ok great. Thanks I will review. Still now design on day view, so I’ll make a separate issue for that and try and see what I can do to get that going.

**Comment by tmcconechy** [comment]
@vonnyw moved Day view to its own issue, since we do not have a design yet will have to do it as soon as we do.

**Comment by janahintal** [comment]
QA Passed. Will move to Done
Verified in
http://master-enterprise.demo.design.infor.com/components/calendar/test-ajax-events.html#

![image](https://user-images.githubusercontent.com/45757016/66111775-22ceac80-e5fc-11e9-8ccf-e9a935cfdea8.png)
