### ISSUE TITLE
SOHO-7747: Ability to display additional information next to a field.

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#252]
In our current app we display the "description" of the "code" that the user selects in a text box to the right of the text box. 

For example, the users enters a vendor's code, and we display the vendor name to the right of the field. Or, the user selects a customer id and we display the customer name to the right of the field. 

Before they enter a customer id:

!2018-04-03_1326.png|thumbnail!

After they enter a customer id:

!2018-04-03_1327.png|thumbnail!

You can also see this works if the user enters data or picks from the picklist.
https://www.screencast.com/t/UFxM2Hplc

We request guidance and maybe modifications to include this ability in the SOHO forms. We are currently using form-responsive row divs wrapping fields per SOHO guidelines.

**Comment by tmcconechy** [comment]
Issue was not auto closed so closing. (Next time can add Closes #number to the PR)

Steps to test:

http://localhost:4000/components/form/test-flex.html
http://localhost:4000/components/form/test-flex.html?locale=ar-SA

both lookup field and label should be displayed properly side by side
Lookup/input field can accept user inputs and should not be moved or scrolled.
Long labeled descriptions should have scrollbar to view hidden texts

**Comment by brianjuan** [comment]
Working as expected across all browsers and passed QA testing.
