### ISSUE TITLE
Application menu: dismissClickOnMobile setting should be used when collapsing role switcher

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#2520]
**Describe the bug**
closeSwitcherPanel in applicationmenu.js should take into account the 'dismissOnClickMobile' setting and closes the application menu accordingly.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html
2. Open Developer Tools - Toggle Device toolbar to iPhone
3. Click on Role Switcher dropdown, select an item

**Expected behavior**
Application menu should be dismissed on mobile.

**Version**

- ids-enterprise: 4.19.0

**Platform**
 - Device iPhone 6

**Additional context**

**Comment by brianjuan** [comment]
http://4200-beta1-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html QA Passed on iOS and Android. App Menu is now closing when an item is selected in Role Switcher. Moving to Done.
