### ISSUE TITLE
Blockgrid/Pager: Disabled first/last page buttons

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#2522]
**Describe the bug**
We need to examine the Pager when combined with a Blockgrid, and figure out why the first/last page buttons are disabled no matter what page the user is looking at. 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/blockgrid/example-paging.html?theme=uplift
2. Observe that the "Last Page" button appears disabled and cannot be used to goto Page 2
3. Click on Page 2
4. Observe that the "First Page" button appears disabled and cannot be used to goto Page 1

**Expected behavior**
It should be possible for these buttons to be enabled and usable in the correct context.

**Version**
Discovered while testing v4.20.x, been present since at least 4.16.x

**Screenshots**
![Screen Shot 2019-07-24 at 10 54 31 AM](https://user-images.githubusercontent.com/3249601/61804175-74d7a280-ae01-11e9-8313-e63db090b33d.png)

**Platform**
- n/a

**Additional context**
 Discovered while testing [#2516](https://github.com/infor-design/enterprise/pull/2516#pullrequestreview-266033903)

**Comment by tmcconechy** [comment]
Can no longer reproduce this issue. Adding it to QA though in case i missed something

**Comment by janahintal** [comment]
Hi @tmcconechy noticed that the Go to Last & Fist page is not included anymore in https://master-enterprise.demo.design.infor.com/components/blockgrid/example-paging.html?theme=uplift&variant=light may I know if this is expected?

![image](https://user-images.githubusercontent.com/45757016/96575759-c4a66180-1303-11eb-9181-cecf94806800.png)

**Comment by tmcconechy** [comment]
Yes thats expected. There are different types of pagers this one is only a List with numbers so you navigate with the numbers to go first to last.

**Comment by janahintal** [comment]
Thanks Tim, will now move this to Done.
