### ISSUE TITLE
Filter Field: Operators not specific to Data Type

### ISSUE THREAD

**Issue by LotharBlum** [infor-design/enterprise#2525]
**Describe the bug**
The field filter components are not specific to the data types and are reacting buggy on interactions. See attached PDF for some of the issues discovered. 

**To Reproduce**
IDS Enterprise, Component field filter
https://design.infor.com/code/ids-enterprise/latest/field-filter

**Expected behavior**
Described in PDF
[Bugs in Filter Field Component.pdf](https://github.com/infor-design/enterprise/files/3430438/Bugs.in.Filter.Field.Component.pdf)

**Version**
- ids-enterprise: v4.19.4

**Screenshots**

**Platform**
 - Device (if applicable) MacBook
 - OS Version: latest MacOS
 - Browser Name FF
 - Browser Version 68.0 (64-bit)]

**Additional context**
Add formating hints in fields for user to indicate which format for keyboard input he should use.

**Comment by tmcconechy** [comment]
The two things your suggesting are possible.

1) You can configure each field to have exactly what you want already https://github.com/infor-design/enterprise/blob/master/app/views/components/field-filter/example-index.html#L87
3) You can add a placeholder option if desired in the markup. Although we do'nt normally suggest over using formatting hints as it can add to cognitive load.

Although these are possible, perhaps we should update the demo example to show more correct values as you suggested. So keeping this open for future demo app updates.

**Comment by tmcconechy** [comment]
descoping this for now
