### ISSUE TITLE
Datagrid Filter: disableClientFilter and load data causing an infinite loop when updating columns

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2526]
**Describe the bug**
Calling updateColumns on a datagrid will emit a filtered event when disableClientFilter is true for options. The filtered event is from the [restoreFilter ](https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L763)flag being set to true, which causes the [filtered event to be emitted](https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L1271).

Does a rerender of the header need to emit the filter event if it's disableClientSideFilter?

**To Reproduce**
1. Copy [test-filter-load-data-update-columns.zip](https://github.com/infor-design/enterprise/files/3432387/test-filter-load-data-update-columns.zip) into app/views/components/datagrid
2. Navigate to '/components/datagrid/test-filter-load-data-update-columns'
3. Attempt to set a filter on the Action column
4. See error - Page is unresponsive, and if you open the browser debugger, an infinite loop of filtered events are being printed in the console.

**Expected behavior**
An updateColumn call should not cause a filtered event to occur when disableClientSideFilter is set to true.

**Version**

- ids-enterprise: v4.20.0-dev

**Platform**
 - All

**Comment by lipetzan** [comment]
We've worked around this issue for now on our side, but would like to move back to standard impl when this is fixed.

**Comment by tmcconechy** [comment]
So this doesnt need to go in 4.20? Can wait for 4.21?

**Comment by Sovia** [comment]
The filtered event will be emitted whenever a updateColumn call is made. So the case of a server sort, which calls updateColumns will have filter event being emitted as well.

Updated the example so you can see that when sorting the Product Name column:
[test-filter-load-data-update-columns.zip](https://github.com/infor-design/enterprise/files/3432671/test-filter-load-data-update-columns.zip)

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-load-data-update-columns.html
Multiples events when selecting a filter is now fixed, but I found an issue related to filter.
Deselected item is still selected when the dropdown filter is opened again.
Steps:
1. Open Action filter, then select Place On-Hold, then close dropdown
2. Open Action filter again, deselect Place On-Hold then select Request Review, close dropdown
2. Open Action filter again, see issue: Place On-Hold is still selected.

Also, datagrid is not loading in Windows IE 11.

**Comment by tmcconechy** [comment]
This example is not configured for filter to work. Im only concerned about the events here so moving this to done.

**Comment by brianjuan** [comment]
Noted on that @tmcconechy. How about in IE? The datagrid is not loading, so we're not able to test this in IE.

**Comment by tmcconechy** [comment]
Oh hmm ok i will check that out. I missed that. But its not super important for this example.

**Comment by brianjuan** [comment]
Sure @tmcconechy no rush. Thanks!

**Comment by brianjuan** [comment]
I'm not sure if the fixes are already merged? I am still seeing the issues in http://localhost:4000/components/datagrid/test-filter-load-data-update-columns.html and http://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-load-data-update-columns.html. There is also a message in the PR "Merging is blocked".

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-load-data-update-columns.html
Issues are now fixed. Passed QA on all browsers including IE.
