### ISSUE TITLE
Completion Chart: Vertical text alignment is off in uplift theme

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2529]
We use completion charts for our field that are to be displayed as a progress increment. Notice the text in the chart is down at the bottom and also not very visible against the very dark background.

![imgpsh_mobile_save](https://user-images.githubusercontent.com/4737815/61890477-2263b800-aecd-11e9-8037-f9de1a3087a7.jpg)

**Comment by tmcconechy** [comment]
@pwpatton can you edit the issue to use the bug template https://raw.githubusercontent.com/infor-design/enterprise/master/.github/ISSUE_TEMPLATE/bug_report.md

im not sure about this one as we do not have any text on the bar here http://master-enterprise.demo.design.infor.com/components/completion-chart/example-index.html

**Comment by tmcconechy** [comment]
Closing until further information can be provided as we could not reproduce.
