### ISSUE TITLE
Uplift Theme: The fonts on title too big and on page body too small

### ISSUE THREAD

**Issue by wuy00** [infor-design/enterprise#2532]
https://jira.lawson.com/browse/LMCLIENT-26399

See attached screenshot. 

1. employee > Opportunities > job list > open a job to job description page.
2. Textarea rich text title fonts too big

![richTextArea](https://user-images.githubusercontent.com/1207532/61910946-aaf94d00-aefb-11e9-9d21-a9d6ad2cec3c.png)

![jobPage](https://user-images.githubusercontent.com/1207532/61910948-aaf94d00-aefb-11e9-9062-ef3267dab0f8.png)

**Comment by tmcconechy** [comment]
@wuy00 Can you please follow the issue template https://raw.githubusercontent.com/infor-design/enterprise/master/.github/ISSUE_TEMPLATE/bug_report.md just edit your issue and fill in the information as specified when creating issues. Also for issues in the REPO please refer to the example pages I think i can reproduce this here on this page http://master-enterprise.demo.design.infor.com/components/editor/example-preview.html?theme=uplift&variant=light&colors=0563C2 but not 100% sure?

**Comment by wuy00** [comment]
@tmcconechy Thanks Tim, I guess I close this ticket now, I will let my team developer to evaluate the issue first.
