### ISSUE TITLE
Datagrid: Add method to set the columns in the Reset to Default after Grid is initialized

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#2533]
**Is your feature request related to a problem? Please describe.**
The columns that are used in reset to default are only set on `init` off the datagrid. We define our columns based on data fetched and pass them to the grid later.

Since columns are set based on the  initial data provided. This means some columns will be hidden or displayed based on that incomplete data.

**Describe the solution you'd like**
Add method where the default columns can be set after the Grid initialization.

**Describe alternatives you've considered**
We are removing the Reset to default for the moment since there is no work around.

**Additional context**

**Comment by tmcconechy** [comment]
How do you set the columns based on data exactly? Do you call setColumns later?

**Comment by AnaLauraMartinez** [comment]
We have a method after setColumns that reviews if for example any of the data has description, if it doesn't we then make the column hidden, the default is displayed. Then we use the updateColumns method.

**Comment by tmcconechy** [comment]
Descoping some older issues we wont be able to get to. But its possible this might work in 5.0 and we can revisit this when thats done.
