### ISSUE TITLE
Dropdown: Not displaying tooltip when update() is called

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#2534]
**Describe the bug**
re: #2236 
The dropdown tooltip for selected items with long text does not display when using ids-enterprise-ng with ids-enterprise. This occurs with Angular because the dropdown option elements are not processed until after the sohoxi dropdown has been initialized, even when the option elements are statically placed in the DOM.

The previous example, dropdown/test-long-text.html, has been modified to replicate the issue seen in ids-enterprise-ng. 

**To Reproduce**
1. Replace the test-long-text.html in the ids-enterprise app > views > components > dropdown directory
2. In the browser, navigate to http://localhost:4000/components/dropdown/test-long-text.html
3. Click the Update button
4. Hover over the States and States Readonly fields; there is not a tooltip displayed
5. Additionally for Firefox and IE 11, the ellipsis does not display for the long text which is likely related

**Expected behavior**
The tooltip should display for the selected item long text

**Version**

- ids-enterprise: v4.20.0-dev

**Screenshots**
gif of ids-enterprise showing the tooltip not displaying after update() is called
![dropdown-tooltip-not-displaying](https://user-images.githubusercontent.com/20212079/61972788-0d0f8c00-afa8-11e9-9781-37743c191009.gif)

gif of ids-enterprise-ng debugging dropdown showing the options elements are not available at dropdown initialization, but later when soho-dropdown.update() is performed
![soho-dropdown-not-displaying-tooltip](https://user-images.githubusercontent.com/20212079/61972972-84ddb680-afa8-11e9-9a16-36779a346125.gif)

**Platform**
 - Browser Name: Chrome, Firefox, IE 11

**Additional context**
[test-long-text.zip](https://github.com/infor-design/enterprise/files/3436934/test-long-text.zip)

Believe if toggleTooltip() was called from the dropdown update() method, it might resolve the issue.

**Comment by fitzorama** [comment]
![image](https://user-images.githubusercontent.com/20212079/61973398-91164380-afa9-11e9-90f0-ca67a98f131c.png)

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/dropdown/test-updating-long-text.htm
http://localhost:4000/components/dropdown/test-updating-long-text.html
Passed QA testing on all browsers.
