### ISSUE TITLE
Contextual Action Panel / Tabs: Overflow menu not displayed on workspace CAP

### ISSUE THREAD

**Issue by tmcastro** [infor-design/enterprise#2537]
**Describe the bug**
Tabs in workspace doesn't display spillover when viewed in mobile

**To Reproduce**
1. Switch to mobile view on Google Chrome
2. Open a workspace with Tab component that has 4-5 tabs
3. Spillover isn't showing up but tab headers are able to scroll

**Expected behavior**
Spillover should be displayed

**Platform**
 - Google Chrome - Mobile View

**Comment by tmcastro** [comment]
![image](https://user-images.githubusercontent.com/39041951/62047918-2fbad280-b23e-11e9-9f85-59d0fafd7f62.png)

**Comment by tmcconechy** [comment]
Can you upload a reduced test case/sample so we can try this out? One thing you can try is to set a specific width on the Contextual Action Panel. This may help it to work

**Comment by tmcastro** [comment]
[example-workspaces.html.zip](https://github.com/infor-design/enterprise/files/3445268/example-workspaces.html.zip)

Hi @tmcconechy, 

Here's a sample of test page for this issue.

> One thing you can try is to set a specific width on the Contextual Action Panel. This may help it to work

Do you mean a fixed width for the contextual action panel?

**Comment by tmcconechy** [comment]
Thanks I can see the issue in your example. What i meant was add a width like `  <div class="contextual-action-panel" style="display:none; width: 400px">` but this did not work. If i do that to your example and open it i do not see the tab overflow. But i do if i slightly resize the page. So i think the logic is not firing  to make the tabs resize at the right time. If you want to look into this issue and do a PR feel free or i'll backlog it and we can fix later.

**Comment by tmcastro** [comment]
I think we can backlog it for now. And I/someone can pick it up some other time. Thanks!

**Comment by tmcconechy** [comment]
Descoping for now
