### ISSUE TITLE
Uplift: Some header colors have black foreground color

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2539]
**Describe the bug**
Uplift: Some header colors (Turquoise, Slate, and Graphite) have black foreground color.

**To Reproduce**
1. Go to http://4200-beta1-enterprise.demo.design.infor.com/components/list?theme=uplift
2. Select Turquoise, Slate or Graphite in ... menu
3. See issue: Header foreground color is black

**Expected behavior**
Foreground color should be white.

**Version**
- ids-enterprise: v4.20.0-beta1

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/62048992-ce483300-b240-11e9-9c45-972e989bd0f8.png)

**Platform**
 - All OS and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
@deep7102 Can you fix it for the other 3 colors too. I think they all should be white.

**Comment by brianjuan** [comment]
https://4200-rc0-enterprise.demo.design.infor.com/components/list?theme=uplift
Passed QA testing on all browsers.
![image](https://user-images.githubusercontent.com/39508864/62467286-f5b17980-b7c5-11e9-97cd-4a285b211483.png)
