### ISSUE TITLE
Locale: Strings giving an error for locales using the strings of a "parent" locale

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2540]
**Describe the bug**
Originally noted on https://github.com/infor-design/enterprise/issues/2365 when you use a locale on this example you can see errors. This only happens on locales that share strings with another locale like es-US (es-ES) and ar-SA (ar-EG)

**To Reproduce**
1. Go to https://4200-beta1-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?theme=uplift&locale=es-US2. Click on '....'
3. Do hard refresh to load not from cache
4. See console

**Expected behavior**
Either we map this internally better or update the sample page

**Version**
- ids-enterprise: [e.g. v4.20.0]

**Platform**
 - Chrome
- Deployed

**Additional context**
Notes on

**Comment by brianjuan** [comment]
https://4200-rc0-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?locale=ar-SA
https://4200-rc0-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?locale=es-ES
https://4200-rc0-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?locale=es-US
Passed QA on all browsers. Pages are loading properly and no errors in console.
