### ISSUE TITLE
Uplift Dark and High Contrast Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2541]
**Describe the bug**
This is a list of noted bugs in uplift dark and uplift high contrast. Will do further testing as well.

**Uplift Dark Issues**
- [ ] The selected color for modals is very hard to read [open the Popup on Datepicker to see]( http://localhost:4000/components/datepicker/example-index.html?theme=uplift&variant=dark&colors=0053B1)
- [ ] Pager font color is not readable (https://github.com/infor-design/enterprise/issues/2588)
- [ ] The submenu header color should perhaps be a azure color.  Compare http://localhost:4000/patterns/builder-wizard.html?theme=uplift&variant=dark&colors=0563C2 and http://localhost:4000/patterns/builder-wizard.html?theme=uplift&variant=dark
- [ ] The editor buttons look strange:  http://localhost:4000/components/editor/example-index.html?theme=uplift&variant=dark

**High Contrast Dark Issues**
- [ ] The disabled buttons do not have a larger noticeable difference - http://localhost:4000/components/datepicker/example-index.html?theme=uplift&variant=contrast&colors=003066 - open the popup and then click the menu button. This is also noticeable on http://localhost:4000/components/button/example-index.html?theme=uplift&variant=contrast&colors=003066 should bring it down one or 2 colors
- [ ] On http://localhost:4000/components/input/example-index.html?theme=uplift&variant=contrast&colors=003066 the readonly field is too bold. And the inputs should have a white background. The spinner does on the ends only.

**Comment by EdwardCoyle** [comment]
Do you all think this works for the disabled button colors on Uplift Contrast?

![Screen Shot 2019-08-28 at 5 16 12 PM](https://user-images.githubusercontent.com/3249601/63893272-ba1a6180-c9b7-11e9-8f71-9094f95e175a.png)

@tmcconechy FYI, this and the Input field color change back to white are going to need another token release 😞

**Comment by tmcconechy** [comment]
I think this looks pretty good. 
Sure just make a new token PR and release is now easy that we know how.

**Comment by brianjuan** [comment]
Found some uplift issues while testing.
**List view** http://4210-beta1-enterprise.demo.design.infor.com/components/listview/example-index.html?theme=uplift
In **IE**, there are alignment issues in header
![image](https://user-images.githubusercontent.com/39508864/64246717-e9911700-cf3f-11e9-9b70-736db3d36f0a.png)

**Cards** http://4210-beta1-enterprise.demo.design.infor.com/components/cards/example-group-action.html?theme=uplift
In **Safari**, there are alignment issues, but it get's fixed when you changed the to either Dark or High Contrast
![image](https://user-images.githubusercontent.com/39508864/64246958-6b814000-cf40-11e9-9093-d256cfb84338.png)

**Editor** http://4210-beta1-enterprise.demo.design.infor.com/components/editor/example-index.html?theme=uplift&variant=dark
Some elements are cut-off
**All browsers**
![image](https://user-images.githubusercontent.com/39508864/64247252-07ab4700-cf41-11e9-8efc-d266f811dc0d.png)

![image](https://user-images.githubusercontent.com/39508864/64247347-404b2080-cf41-11e9-839e-61cfa5e4c7af.png)

**Edge**
![image](https://user-images.githubusercontent.com/39508864/64247614-cc5d4800-cf41-11e9-8c4e-ace7b9089941.png)

**Comment by kevinwhitedesign** [comment]
Nice catches @brianjuan

**Comment by brianjuan** [comment]
http://4210-beta3-enterprise.demo.design.infor.com/components/listview/example-index.html?theme=uplift
http://4210-beta3-enterprise.demo.design.infor.com/components/cards/example-group-action.html?theme=uplift
http://4210-beta3-enterprise.demo.design.infor.com/components/input/example-index.html?theme=uplift
http://4210-beta3-enterprise.demo.design.infor.com/components/checkboxes/example-index.html?theme=uplift
http://4210-beta3-enterprise.demo.design.infor.com/components/radios/example-index.html?theme=uplift
http://4210-beta3-enterprise.demo.design.infor.com/components/editor/example-index.html?theme=uplift&variant=dark
http://4210-beta3-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels-icons.html?theme=uplift
Passed QA, tested in all browsers.
