### ISSUE TITLE
Overflow not set on modals in uplift.

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2547]
**Describe the bug**
When bringing up a modal if the window is to short for the content a scroller does NOT appear and the context spill out of bounds of the modal.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/modal/test-full-content-buttons.html?theme=uplift&variant=light&colors=0563C2
2. Click on "Show Modal" button
3. Make the browser shorter than the dialog
4. Notice not scroller and fields seem to spill out of the modal.

**Expected behavior**
An overflow for the modal content area should scroll the modal content.

**Version**

- ids-enterprise: 4.20.0-dev.20190725 and 4.20.0-dev.20190724

**Screenshots**
![image](https://user-images.githubusercontent.com/4737815/62071118-73431b80-b201-11e9-967d-1870d693860d.png)

**Additional context**
We believe this change caused the issue
https://github.com/infor-design/enterprise/commit/1b2cbe8eacd5e673dca7f7136191aabbaa842342

**Comment by EdwardCoyle** [comment]
FYI, this fixed this issue in Uplift Modals:

>  Message - Click success button on IE edge and a tiny scroll bar is visible

I'm guessing we care more about the ability to scroll, moreso than the existence of the scrollbar?  If so, I can reverse the change.

**Comment by pwpatton** [comment]
Any way to do the 'inherit' just for these message modals? For our form modals (and your guys' form modals) no scrolling happens.

**Comment by tmcconechy** [comment]
Perhaps for the message fix we just needed to remove some padding or something for? As really the message didnt need a scrollbar bar all for it.

**Comment by brianjuan** [comment]
https://4200-rc0-enterprise.demo.design.infor.com/components/modal/test-full-content-buttons.html?theme=uplift&variant=light&colors=0563C2
Passed QA testing on all browsers.
![image](https://user-images.githubusercontent.com/39508864/62441110-81ef7c80-b785-11e9-917a-32a2cf1871f9.png)
