### ISSUE TITLE
Icons: Need a flag icon that isn't red but just the regular icon color

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2548]
**Describe the bug**
We would like to use the flag icon however it is hard coded to red. Would like a red version and a normal icon version

**To Reproduce**
1. Go to http://localhost:4000/components/icons/example-index.html
1. Scroll down to '#icon-flag' and inspect

**Expected behavior**
Would like the flag to be whatever color by a css class and be normal icon color otherwise.

**Version**
- ids-enterprise: [e.g. v4.19.0]

**Platform**
 - Any (Chrome)

**Additional context**
https://github.com/infor-design/design-system/issues/391

**Comment by tmcconechy** [comment]
We need to remove the inline red color on the icon. This may be an ids-identity change.
Then show the normal flag and one with the (red) color(s) added by a css class.

**Comment by tmcconechy** [comment]
@nickwynja What would we have to do to get rid of the inline fill on the ids-identity side?
Also https://github.com/infor-design/enterprise/issues/2474 is somewhat related.

**Comment by davidcarlsonberg** [comment]
Why was this moved to Failed?

**Comment by EdwardCoyle** [comment]
@davidcarlsonberg @janahintal I just moved it back, since there didn't appear to be any work done on this yet

**Comment by tmcconechy** [comment]
Not sure what happened but this should be simple just make the flag icon get its color from a css class instead of the inline fill property.

**Comment by tmcconechy** [comment]
Sometime sirens can get dragged wrong I assume that’s what happened

**Comment by kentonquatman** [comment]
I just got tapped to look at this issue. Would it be possible to use "currentColor" as the value for the fill attribute on our icons? This should allow us to set and override icon colors using CSS.

**Comment by tmcconechy** [comment]
Your saying just make it the same color as all other icons (default none).

I think that could work - which was my original idea. But it might end up being a minor breaking change as you would need to now add a class to make it red. But i think thats explainable.

**Comment by kentonquatman** [comment]
Yea, exactly.

You raise a good point about breaking changes. We might want to consider adding specific classes to all of our icons going forward so that they can be targeted for styling. Future proofing for situations like this one. It could be something like `class="icon icon--flag"` instead of just `class="icon"`

**Comment by tmcconechy** [comment]
We do have classes for colors like `ruby07` or `error` we can use. Should add the right styles between it. They are not new. I think just do it that way as its unlikely this icon is highly used we can note the change in the release notes.

**Comment by kentonquatman** [comment]
Perfecto.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/icons/example-index.html
http://master-enterprise.demo.design.infor.com/components/alerts/example-index.html
http://master-enterprise.demo.design.infor.com/components/icons/example-empty-widgets.html?theme=uplift
Passed QA on all browsers, tested all themes and variants as well.
