### ISSUE TITLE
Application Menu Component: Accessibilty Issue with tab and arrow down key for "Search this menu"

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2550]
**Describe the bug**
Application Menu Component: Accessibilty Issue with tab and arrow down key fro "Search this menu"

**To Reproduce**
1. Go to url: https://4200-beta1-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html
2. Tab into the "Search this menu" field box. 
3. Type the following "Hist"
4. History will appear 
5. Try to tab or arrow key into "History" and you are unable to do so. You an only select "History" by using your mouse

**Expected behavior**
The user should be able to tab or arrow down key into History with the use of a mouse

**Version**

- ids-enterprise: [v4.20.0]

**Screenshots**
none

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [MAC FF and Chrome]
 - Browser Name [e.g. FF, chrome,]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
None

**Comment by CindyMercadoReyes** [comment]
Also happening here as well: https://4200-beta1-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html

**Comment by tmcconechy** [comment]
Seeing this back to 4.16 at least. Also when i tab from the search to the x it clears the search.

**Comment by tmcconechy** [comment]
Descoping some issues for now we wont have time for
