### ISSUE TITLE
Application menu: toolbar buttonset in footer area overlaps menu content

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#2552]
**Describe the bug**
IE 11 issue only - When the application menu content height is such that it shows a scrollbar, the application menu toolbar area appears in the middle of the application menu content until users clicks elsewhere.

**To Reproduce**
See screenshot: (a role switcher demo will be added to ep-ng project to duplicate this issue).

**Expected behavior**
Application menu toolbar should not overlaps content area.

**Version**

- ids-enterprise: v4.19.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39130590/62075960-1b5de200-b20c-11e9-9984-d45a8891843d.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: IE 11
 - Browser Version: 11.885.17134.0

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-personalized-role-switcher-long-title.html
Passed QA in all browsers including IE.
![image](https://user-images.githubusercontent.com/39508864/65508279-6d686e80-df02-11e9-96ea-c3ee2335ad32.png)
