### ISSUE TITLE
Datagrid: Inconsistency in the disabled rows when columns are sorted

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2554]
**Describe the bug**
Datagrid: Inconsistency in the disabled rows when columns are sorted. 

**To Reproduce**
1. Go to http://4200-beta1-enterprise.demo.design.infor.com/components/datagrid/example-disabled-rows.html
2. Notice that rows with Row ID 2, 3 and 4 are disabled
3. Click the Row ID column to sort in descending order
4. See issue: Rows with Row ID 5, 4 and 2 are disabled and Row ID 3 is now enabled
5. This also happens in all sortable columns 

**Expected behavior**
Rows that are previously disabled should stay disabled even after sorting is applied.

**Version**
- ids-enterprise: v4.19.0 to v4.20.0-beta1

**Screenshots**
No screenshots applicable

**Platform**
 - All devices, OS, and browsers.

**Additional context**
I also noticed that the color of disabled rows is different compared here http://4200-beta1-enterprise.demo.design.infor.com/components/datagrid/example-editable.html. Please clarify. Thanks.

**Comment by tmcconechy** [comment]
Something is not correct here but has been this way since this feature is added. Changed the function to:
```
      isRowDisabled: function (rowIdx, item) {
        return item.activity === 'Assemble Paint';
      }
```

Also when fixing this i will change the style to font color not opacity on the rows. Doing this as part of the datagrid fixes.

**Comment by jbrcna** [comment]
**QA Passed**
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-disabled-rows.html
