### ISSUE TITLE
Datagrid:  Frozen Columns cannot be scrolled vertically in mobile

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2555]
**Describe the bug**
Datagrid Frozen Columns: Unable to scroll vertically in mobile.

**To Reproduce**
1. Open browsers in iOS and Android
2. Go to http://4200-beta1-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html
3. Try to scroll vertically
4. See issue: datagrid won't allow you to scroll

**Expected behavior**
Frozen columns should be scrollable horizontally on mobile browsers.

**Version**
- ids-enterprise: v4.17.0 to v4.20.0-beta1

**Screenshots**
No applicable screenshots.

**Platform**
 - iOS browsers
 - Android browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Calling this a demo app bug. It seems like we need to change the example so that the mobile view renders differently with a different (non frozen view). We can do this with a media query. As it is now this pattern is not mobile friendly and thats fine.

**Comment by tmcconechy** [comment]
This should be ok now with the very latest changes.
