### ISSUE TITLE
Datagrid pager took so long to load in windows 10 IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2560]
**Describe the bug**
Datagrid pager took so long to load in windows 10 IE11

**To Reproduce**
1. Go to any of these (and all grids that includes pager)
https://4200-beta1-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection-popupmenu.html
https://4200-beta1-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html
https://4200-beta1-enterprise.demo.design.infor.com/components/datagrid/example-paging.html 
2. Click next page

**Expected behavior**
Should not take too long to redirect in the next page

**Version**
Beta 4.20

**Screenshots**
NA

**Platform**
Windows 10 IE 11

**Additional context**
NA

**Comment by tmcconechy** [comment]
Calling this a regression and something we should fix. What im seeing is on IE11 clicking the next button isnt really working even. Its not slow, nothing is actually happening compared to 4.19. I think perhaps the link is out of place so clicking the button is not hitting the link.

**Comment by brianjuan** [comment]
Also in http://4200-beta1-enterprise.demo.design.infor.com/components/datagrid/example-paging.html

**Comment by brianjuan** [comment]
Also in http://4200-beta1-enterprise.demo.design.infor.com/components/datagrid/example-grouping-paging.html

**Comment by tmcconechy** [comment]
Thanks @brianjuan its going to be the pager on EVERYWHERE. But we have a fix in now for the RC

**Comment by brianjuan** [comment]
https://4200-rc0-enterprise.demo.design.infor.com/components/pager/example-index.html
https://4200-rc0-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection-popupmenu.html
https://4200-rc0-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html
https://4200-rc0-enterprise.demo.design.infor.com/components/datagrid/example-grouping-paging.html
https://4200-rc0-enterprise.demo.design.infor.com/components/datagrid/example-paging.html
Passed QA on IE. I also tested other browsers, and pagers are still working as expected.
