### ISSUE TITLE
Calendar: Add Schedule view

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#2563]
**Describe the bug**
The Schedule view for the calendar is listed on the drop down, but it is currently unavaliable.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html'

**Version**
- ids-enterprise: [v4.21.0]

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/62181171-93a1e000-b391-11e9-85f7-20f39fafdb5d.png)

**Additional Information**
The model for this is google schedule view.

![Screen Shot 2021-07-30 at 9 16 13 AM](https://user-images.githubusercontent.com/814283/127658458-de5fbe48-c63a-4477-8937-74c82d8d61c6.png)

**Comment by tmcconechy** [comment]
We have tickets for day and week view however we only currently have designs for Week view of the 3 missing views.

**Comment by kevinwhitedesign** [comment]
@katieinfor needs a ticket, they need a schedule view I think we have a design for it

**Comment by katieinfor** [comment]
Jira ticket: https://jira.infor.com/browse/UXD-2939
