### ISSUE TITLE
Datagrid Grouping: Misalignment on Totals after personalizing columns

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2564]
**Describe the bug**
Datagrid Grouping: Misalignment on Totals after personalizing columns.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-totals.html
2. Open ... menu then select Personalize Columns
3. Hide the "Customer Id" column
4. See issue: Totals will now be at the leftmost of the row
5. Hide the "Location" column
6. See issue: "Total" labels will be hidden
7. Hide the "First Name" column
8. See issue: Both total and the amounts will be hidden
9. Try hiding other columns as well, different behaviors are encountered whenever a column is hidden

**Expected behavior**
Alignment of total labels should be correct even after hiding columns.

**Version**
- ids-enterprise: v4.6.0 to v4.20.0-beta1

**Screenshots**
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/39508864/62193156-c3f57880-b3a9-11e9-8f2d-61f76714406a.png)

**Platform**
 - All devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-totals.html?theme=uplift&variant=light
