### ISSUE TITLE
Datagrid: Filter value is cleared after reordering a column to another group

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2565]
**Describe the bug**
Datagrid: Filter value is cleared after reordering a column to another group.

**To Reproduce**
1. Go to http://4200-beta1-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html
2. Type "Air" in the filter field of Product Name column, datagrid will be filtered
3. Drag the Product Name column to "Column Group Three"
4. See issue: "Air" will be cleared in the Product Name column while the datagrid remains filtered.

**Expected behavior**
Filter value should not be cleared after a column is reordered.

**Version**
- ids-enterprise: v4.20.0-beta1

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/62198042-81389e00-b3b3-11e9-9430-53df9d4c0dc3.png)

**Platform**
 - All devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This issue has existed since the creation of this feature.

**Comment by brianjuan** [comment]
Yup @tmcconechy, the only version it is not happening is in 4.19.0

**Comment by brianjuan** [comment]
Passed in all browsers except in Windows 10 IE 11. The fix cannot be tested in IE since the columns are now not draggable. Tested in http://master-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html.

**Comment by brianjuan** [comment]
QA passed in Windows 10 IE as well, tested in https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html.
![image](https://user-images.githubusercontent.com/39508864/74511166-558c9800-4f40-11ea-9f55-1dcfa278ee98.png)
