### ISSUE TITLE
Lookup filter does not refresh properly 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2566]
**Describe the bug**
Lookup filter does not refresh properly 

**To Reproduce**
1. Go to https://4200-beta1-enterprise.demo.design.infor.com/components/lookup/example-filter-row.html
2. Filter product name contains "I L"
3. Click Cancel 
4. Notice that the filter refreshed but the list didn't

**Expected behavior**
List and Filter should render properly / consistently 

**Version**
beta 4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/62203630-1fc9fc80-b3be-11e9-95a2-78eb79753108.png)

**Platform**
All Browser, OS and devices. 

**Additional context**
NA

**Comment by tmcconechy** [comment]
@janahintal and @CindyMercadoReyes do not understand this issue. The steps are clear but im not seeing anything wrong here. Can you elaborate further? If i click cancel it closes as expected im not seeing anything related to refreshing...

**Comment by CindyMercadoReyes** [comment]
Adding additional steps to this issue below: 
Steps to reproduce the behavior:

1-  Go to https://4200-beta1-enterprise.demo.design.infor.com/components/lookup/example-filter-row.html
2- Filter product name contains "I L"
3- Click Cancel
4-Notice that the filter refreshed but the list didn't
5- The lookup closes
6- Reopen the look up
7-"I Love Compressor" is still appearing  when the full list of products should be appearing not "I Love Compressor"

**Comment by janahintal** [comment]
QA PASSED. Will move to done. 
Tested in https://4200-rc0-enterprise.demo.design.infor.com/components/lookup/example-filter-row.html across all browser, OS and devices. Thanks
