### ISSUE TITLE
Lookup multi select is not working properly 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2568]
**Describe the bug**
Lookup multi select is not working properly 

**To Reproduce**
1. Go to https://4200-beta1-enterprise.demo.design.infor.com/components/lookup/example-multiselect.html
2. Select the 1st row 2142201
3. Click Cancel
4. Open the lookup again
5. Select 2nd row 2241202
6. click 'Apply' 

Notice that the field is populated but only by the 2nd row 2241202

**Expected behavior**
Should select both 1st and 2nd row. 

**Version**
Beta 4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/62205318-c6fc6300-b3c1-11e9-9788-b80211629747.png)

**Platform**
All OS, Browser and devices. 

**Additional context**
NA

**Comment by tmcconechy** [comment]
Similar to https://github.com/infor-design/enterprise/issues/2566

**Comment by janahintal** [comment]
QA Passed. Will Move to Done 
Retested in https://4200-rc0-enterprise.demo.design.infor.com/components/lookup/example-multiselect.html
