### ISSUE TITLE
Datepicker: selection issues in range

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2569]
**Describe the bug**
Datepicker: selection issues in range.

**To Reproduce**
1. Go to http://4200-beta1-enterprise.demo.design.infor.com/components/datepicker/example-range.html
2. Open the date picker in "Range - No Initial value"
3. Select July 30, 2019 to August 3, 2019
4. Open the date picker again
5. Click the left arrow to go to July 2019 view
6. See issue: there are issues in selection
7. Also, try to go to other months beyond August 2019, selections are also applied.
8. Issues are also encountered in all fields with range in the page

**Expected behavior**
Selections should be correct after selecting a range in should not be applied to other months.

**Version**
- ids-enterprise: v4.20.0-beta1

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/62205551-44c06e80-b3c2-11e9-86b1-c6bd543b0e4a.png)

**Platform**
  - All devices, OS, and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
@deep7102 can you help me clean up these?

**Comment by brianjuan** [comment]
https://4200-rc0-enterprise.demo.design.infor.com/components/datepicker/example-range.html
Passed QA on all browsers.

**Comment by jbrcna** [comment]
Issue still persist in v4.24 beta0. 
Dates that are declared as **holidays** are the ones affected
Verified in http://4240-beta0-enterprise.demo.design.infor.com/components/datepicker/example-range.html
![image](https://user-images.githubusercontent.com/56722184/71070709-527e6100-21b6-11ea-9f6b-1985b5980ba1.png)

Issue is also present in v4.23

**Comment by tmcconechy** [comment]
Ok, this is an older issue. Lets skip this for now as we have several of bugs on Datepicker Range to fix so once we finally can get to those we can retest the functionality in full.

**Comment by jbrcna** [comment]
Noted on that @tmcconechy . Cheers!
