### ISSUE TITLE
SOHO-7019: XSS in Editor (Homepages Notes widget)

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#257]
When using the Notes widget in Homepages (which uses the Editor SoHo component), you can insert script tags in hyperlinks:
!xss_notes.gif|thumbnail!

This is pretty dangerous, since it makes it trivial to perform an XSS attack on any platform where users can share the contents of the Editor (assuming no escaping is done when serializing/transmitting the data).

I guess this affects any product that uses the Editor, and is not specific to Homepages widgets.

*Stpes to reproduce*
- Go to http://usalvlhlpool1.infor.com/4.4.0-rc/components/editor/example-clickable-links
- Click the insert anchor button.
- Add a link with URL: "><script>alert()</script>
- Click Insert
- Click the HTML button
_issue occurs here_

Expected: No alert
Actual: Alert appears due to injected script being executed.

**Comment by brianjuan** [comment]
Passed Smoke testing on http://4100-beta0-enterprise.demo.design.infor.com/kitchen-sink
