### ISSUE TITLE
Base Tag Date Picker Component: Today feature on the date picker not updating correctly with the correct time

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2575]
**Describe the bug**
Base Tag Date Picker Component: Today feature on the date picker not updating correctly with the correct time

**To Reproduce**
1. Go to url: http://4200-beta1-enterprise.demo.design.infor.com/components/base-tag/datepicker-datepicker-time.html
2. Open the date picker and select a future date
3. Tab down to the time section in the date picker and change the hour, minutes 
4. Click on the "Enter" key on your keyboard
5. Open the date picker again
6. Tab down to "Today" 
7. The date was changed to today's date. However, the time stayed the same.  It didn't update to correct time for the users location.

**Expected behavior**
When the user clicks on "Today" in the date picker. The Date Field with Time field box should appear with today's date and correct timeframe of the users location. 

**Version**

- ids-enterprise: [v4.20]

**Screenshots**
![Date picker with time](https://user-images.githubusercontent.com/39101346/62247952-f193ef00-b3b4-11e9-9644-1ed11547de74.png)

**Platform**
- All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
I think this is debatable. As you might want to today with a different time. But perhaps we make it set the time to now and then if they reopen they can change it again

**Comment by tmcconechy** [comment]
Descoping this issue for now
