### ISSUE TITLE
Tabs: 404 Error on outbound links

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2576]
**Describe the bug**
Tabs outbound links error 404

**To Reproduce**
1. Go to  https://4200-beta1-enterprise.demo.design.infor.com/components/tabs-vertical/example-outbound-links-page1.html and 
https://4200-beta1-enterprise.demo.design.infor.com/components/tabs-vertical/example-outbound-links-page2.html
2. Click the next available tab 'Page 1' or 'Page 2' in the respective link
Notice that there is an  error after clicking 

**Expected behavior**
Should have no error upon clicking next tab

**Version**
Regression Beta 4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/62269972-b02a3080-b402-11e9-918d-7390b3edba25.png)

**Platform**
All Browser, OS and devices. 

**Additional context**
NA

**Comment by tmcconechy** [comment]
Suggest we make these urls go to http://infor.com but this is not a big issue as its just a faulty link the feature is working.

**Comment by tmcconechy** [comment]
This might be worth looking at as i was trying for a quick fix and could'nt workout how this is supposed to work. Its not pulling in the page on the external link. Just want to make sure some functionality isnt broken here.

**Comment by EdwardCoyle** [comment]
This sample is supposed to demonstrate how a Tab component could represent a link to an outbound page instead of opening a new pane.  Those URLs on the links are pointing to `outbound-link-page1` or 2, but they should be pointing to `example-outbound-link-page1` or 2.

Should just be a matter of changing out the URL in the examples

**Comment by tmcconechy** [comment]
OK when i did that they loaded each other inside each other (double tabs on the page) and when i changed the contents nothing loaded so that seemed weird to me.

**Comment by EdwardCoyle** [comment]
Definitely shouldn't be doing double tabs...  The pages should both fully reload when the links are clicked.

**Comment by tmcconechy** [comment]
Yeah its wierd because the pages reference themself. Couldnt work it out. Maybe just make the links google.com and bing.com?

**Comment by EdwardCoyle** [comment]
well the point is that the links can be styled like vertical tabs, and act as outbound links to other pages... it's supposed to be used like a multi-page application.  It was a feature request at one point.

I think there might be something off with the layout that we never noticed after moving things around in the demoapp.  I can take a look at this eventually and see.

**Comment by janahintal** [comment]
QA Passed, Will move to Done.  Thanks
Verified in http://master-enterprise.demo.design.infor.com/components/tabs-vertical/example-outbound-links-page1
http://master-enterprise.demo.design.infor.com/components/tabs-vertical/example-outbound-links-page2
