### ISSUE TITLE
Editor: Dirty tracking does not display

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2577]
**Describe the bug**
Editor: Dirty tracking does not display.

**To Reproduce**
1. Go to http://4200-beta1-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html
2. Type "test" in the editor or change any formatting
3. See issue: Dirty tracking indicator won't display

**Expected behavior**
Dirty tracking indicator should display when editor is changed.

**Version**
- ids-enterprise: v4.20.0-beta1

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/62273636-93c4dd00-b470-11e9-8f43-00255e753c83.png)

**Platform**
 - All devices, OS, and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
I know this did used to work but not 100% sure when as the servers are down so marking as 4.20 issue for now.

**Comment by brianjuan** [comment]
https://4200-rc0-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html?theme=soho&variant=contrast&colors=133c59
Dirty tracker is now displaying. But in Uplift, the dirty tracker is barely noticeable.
![image](https://user-images.githubusercontent.com/39508864/62465087-b03e7d80-b7c0-11e9-9f7a-1c818d07a937.png)

**Comment by brianjuan** [comment]
http://4200-rc1-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html
Passed QA across all browsers.
![image](https://user-images.githubusercontent.com/39508864/62677900-6e8d1d00-b9e2-11e9-94b1-fe0a014c33b6.png)
