### ISSUE TITLE
Tabs module add tab button is misaligned in uplift theme

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2579]
**Describe the bug**
Tabs module add tab button is misaligned in uplift theme

**To Reproduce**
1. Go to https://4200-beta1-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html?theme=uplift&variant=light&colors=0563C2
* notice that the Add tab button is misaligned as well as the search button 
**Expected behavior**

**Version**
Beta 4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/62287321-a109a980-b427-11e9-8a02-d2790d607c2d.png)

**Platform**
All Browser OS and devices

**Additional context**
NA

**Comment by tmcconechy** [comment]
This is fixed now please retest on RC

**Comment by janahintal** [comment]
QA PASSED. Tested in https://4200-rc0-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html?theme=uplift&variant=light&colors=0563C2 across all OS Browsers & devices. Thanks.
