### ISSUE TITLE
Datagrid: noSearch dropdown editor in datagrid throws an error in IE11 when selecting using a keyboard letter

### ISSUE THREAD

**Issue by jake-harrington** [infor-design/enterprise#2582]
**Describe the bug**
When selecting something in a dropdown editor by typing the first letter, with the dropdown open, will throw an error in dropdown's `position` method.
![image](https://user-images.githubusercontent.com/39064853/62311446-77fe0e80-b451-11e9-9f5b-9d5975198325.png)

**To Reproduce**
1. Go to example provided with IE11 dev tools open
2. Click the price in the second column
3. Press right arrow to get to units
4. Press space twice to open the editor 
5. Press 'm' on the keyboard
6. No errors should be thrown in the console.

**Version**
4.11, also happens in 4.21.0-dev

**Platform**
 - IE11

**Additional context**
This happens during `updateList` which calls `position` which by the looks of it, only matters if the list is open, right? `position` is called two lines before an `if (this.isOpen())` check, maybe it'd make sense to put that in there? Calling `position` also happens when setting the value programmatically, and the code in the screenshot earlier forces a reflow which causes significant performance problems on pages with a lot of dropdowns because it forces a reflow for every dropdown even though nothing visually is changing.

[test-editable-dropdown-objects.zip](https://github.com/infor-design/enterprise/files/3457790/test-editable-dropdown-objects.zip)

**Comment by tmcconechy** [comment]
Cant seem to reproduce this issue anymore. This may have been fixed along the way
