### ISSUE TITLE
Lookup: Unnecessary scrollbar

### ISSUE THREAD

**Issue by rowelineeveresurreccion** [infor-design/enterprise#2586]
**Describe the bug**
Upon opening a lookup an additional scrollbar is displayed. It happens on a laptop screen only. 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/lookup/example-filter-row.html 
1. Resize the page if needed so scrollbars show.
1. Click on 'Products' Lookup
1. See an additional scrollbar
![image](https://user-images.githubusercontent.com/50350478/62336893-8e6b9f00-b511-11e9-8f89-08ed5ab85ea4.png)

**Version**
Master

**Comment by brianjuan** [comment]
https://4200-rc0-enterprise.demo.design.infor.com/components/lookup/example-filter-row.html#
Passed QA on all browsers.
![image](https://user-images.githubusercontent.com/39508864/62436650-e2c18980-b772-11e9-97f6-16f11b19e7cd.png)
