### ISSUE TITLE
Pager font color is not readable when in uplift theme dark mode

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2588]
**Describe the bug**
Pager font color is not readable when in uplift theme dark mode

**To Reproduce**
1. Go to https://4200-beta1-enterprise.demo.design.infor.com/components/pager/example-listview.html?theme=uplift&variant=dark
Notice that the pager font color is not that readable. 

**Expected behavior**
Pager text should be readable

**Version**
Beta 4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/62373916-601bad00-b56d-11e9-9d1b-ae75c18ce529.png)

**Platform**
All Browser, OS and devices

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
@janahintal if you do see any uplift or dark mode issues in uplift please add them to these list with a brief note. https://github.com/infor-design/enterprise/issues/2541 we are trying to test out this theme and fix in bulk next version

**Comment by davidcarlsonberg** [comment]
@kentonquatman Hi!
Looks like we need a better color for $theme-color-brand-primary for the following components:
datepicker (https://4200-beta1-enterprise.demo.design.infor.com/components/datepicker/example-index.html?theme=uplift&variant=dark)
pager (https://4200-beta1-enterprise.demo.design.infor.com/components/pager/example-listview.html?theme=uplift&variant=dark)
Is it possible for you to prescribe one for uplift dark?
See here for more info: https://github.com/infor-design/enterprise/pull/2630

**Comment by janahintal** [comment]
QA Passed. Will now move to done. Thanks
Verified in http://4210-beta1-enterprise.demo.design.infor.com/components/pager/example-listview.html?theme=uplift&variant=dark 
http://4210-beta1-enterprise.demo.design.infor.com/components/pager/example-listview.html?theme=uplift&variant=contrast
