### ISSUE TITLE
Pager in datagrid goes disabled after removing multiple row

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2590]
**Describe the bug**
Pager in datagrid goes disabled after removing multiple row also noticed that the pager is not that readable in uplift theme 

**To Reproduce**
1. Go to https://4200-beta1-enterprise.demo.design.infor.com/components/pager/example-datagrid.html?theme=uplift&variant=light&colors=0563C2 
1. Select row 0 
1. Click next page
1. Select row 10 
1. Click Remove button 
1 Try to click next page again 
1. Notice that it became disabled

**Expected behavior**
Pager should work 

**Version**
Beta 4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/62375833-c7d3f700-b571-11e9-9543-f2ed85872d48.png)

**Platform**
All Browser, OS and devices 

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
This worked in 4.19 so i think we should check it out

**Comment by janahintal** [comment]
QA PASSED. 
Tested in https://4200-rc0-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side?theme=uplift&variant=light&colors=0563C2 https://4200-rc0-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?theme=uplift&variant=light&colors=0563C2 across all OS browsers & devices. Thanks!
