### ISSUE TITLE
Datagrid: Mask doesn't work on new rows

### ISSUE THREAD

**Issue by meechtsm-infor** [infor-design/enterprise#2592]
**Describe the bug**
When entering new decimal values on a new row in a datagrid, the mask settings do not work when separator is not a dot.
For example in Spanish locale, with a mask set to "####.000", entering the value 1234,5678 results in the cell value being set to 12.345.678,000.

**To Reproduce**
Steps to reproduce the behaviour:
The issue can be reproduced in the datagrid test html test-addrow-tabbing.html
http://master-enterprise.demo.design.infor.com/components/datagrid/test-addrow-tabbing?locale=es-ES

- Ensure that the page is using a locale that uses a comma as a decimal separator e.g. es-ES
- Add a new row to the grid
- In a decimal column cell enter a value with a decimal e.g. 1.234,5670

**Expected behaviour**
When the cell value is changed the value is expected to be 1.234,5670 but appears as 12.345.670,000.

**Screenshot**
![chrome-2019-08-02-006](https://user-images.githubusercontent.com/53617793/62379971-05b82780-b540-11e9-8ba8-2b2c24404e61.png)

**Version**
- ids-enterprise: v4.19.x

**Platform**
 - OS Version: Windows 10
 - Chrome
 - Browser Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by meechtsm-infor** [comment]
The issue appears to be caused by a string instead of a number being passed to the Decimal formatter . This only happens with values on new rows because on existing rows the new value is parsed based on the type of the existing value in the dataset, the resulting number is then passed to the formatter.

A work around, assuming that the dataset value type is a number, is to add a function to the column config to serialise the new value to a number.

The bug seems to be with the Locale.formatNumber code, when formatting a string as a number,  it replaces the localised decimal separator before parsing the string. Locale.parseNumber assumes that string is localised.

**Comment by tmcconechy** [comment]
@meechtsm-infor Can you point me to the code your referring to in regards to your last comment? Thanks

**Comment by meechtsm-infor** [comment]
@tmcconechy This is the code fragment, from the formatNumber function in locale.js, that appears to be causing the issue.
`
if (typeof number === 'string') {
      if (decimal !== '.') {
        number = number.replace(decimal, '.');
      }
      number = Locale.parseNumber(number);
    }
`

**Comment by tmcconechy** [comment]
I tested this issue and found that this was fixed. The code mentioned had been changed on another fix. And using the steps i can no longer reproduce.

Steps:
- go to http://localhost:4000/components/datagrid/test-addrow-tabbing?locale=es-ES
- press new (top or bottom)
- type: 1.234,5670
- tab or enter
- note that the value is changed to 1.234,567 which is correct because the max decimals is 3 in this example)

**Comment by jbrcna** [comment]
**QA PASSED**
The issue no longer exist
verified in
https://master-enterprise.demo.design.infor.com/components/datagrid/test-addrow-tabbing?locale=es-ES
and 
https://4270-beta0-enterprise.demo.design.infor.com/components/datagrid/test-addrow-tabbing?locale=es-ES

![image](https://user-images.githubusercontent.com/56722184/77718625-60961600-701e-11ea-9122-f98350d27a85.png)
