### ISSUE TITLE
Datepicker: range selection issues with footer button

### ISSUE THREAD

**Issue by deep7102** [infor-design/enterprise#2595]
**Describe the bug**
Range selection not working if footer buttons use to select.

**To Reproduce**
Go to https://4200-rc0-enterprise.demo.design.infor.com/components/datepicker/example-range.html

Issue: 1
1. Open picker `Range - No Initial value`
2. Today's date should be highlighted with blue background
3. Click on footer button `Select`
4. See its not doing anything, should be select this highlighted date

Issue: 2
1. Refresh the page
2. Open picker `Range - No Initial value`
3. Click on any date and it will select the date
4. Click on footer button `Select` to select the 2nd date
5. See its not doing anything, should be select this highlighted date
6. In this case 1st and 2nd date should be same

Issue: 3
1. Refresh the page
2. Open picker `Range - No Initial value`
3. Click on footer button `Today` and it will select the today's date
4. Click on footer button `Select` to select the 2nd date
5. See its not doing anything, should be select this highlighted date
6. In this case 1st and 2nd date should be same as today's date

Issue: 4
1. Refresh the page
2. Open picker `Range - No Initial value`
3. Click on footer button `Today` and it will select the today's date
4. Click on any other date to select the 2nd date
5. See its replaced the 1st selected date with this clicked one
6. It should select this new clicked date as 2nd date and close the picker (if the selected 2nd date smaller then 1st date, it will replace the dates. so always 1st date smaller then 2nd date)
7. If you clicked on same selected date, in this case 1st, 2nd date should be same as today's date and close the picker

Issue: 5
1. Refresh the page
2. Open developer tools
3. Use Keyboard to focus on field `Range - No Initial value`
4. While picker still closed
5. Press key: `t` to enter today's date
6. See console it got js error

**Expected behavior**
Selection should be working with footer buttons.

**Version**
- ids-enterprise: [v4.20.0-rc0]

**Screenshots**
none

**Platform**
All devices, OS, and browsers

**Additional context**
No additional context.

**Comment by janahintal** [comment]
QA Passed. Tested in https://4200-rc1-enterprise.demo.design.infor.com/components/datepicker/example-range.html across all OS, Browser and devices.
