### ISSUE TITLE
Application Menu, Pixel 2 Emulator can't scroll to sign out

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#2596]
**Describe the bug**
Can't scroll to sign out when emulating pixel 2 via chrome debugger tools. I am not sure if this is a legitimate issue on the Pixel 2 as I do not have a Pixel 2 device to test this more thoroughly. 

**To Reproduce**
1. Go to http://localhost:4000/components/applicationmenu/example-personalized-roles.html
2. Press F12 to open Chrome Debug Tools
3. Toggle Device Toolbar
4. Open Application Menu
5. Attempt to scroll to the bottom to sign out

**Expected behavior**
Should be able to scroll to bottom to sign out.

**Version**
4.21.0-dev

**Screenshots**
![pixel2-emulator-cant-scroll-to-sign-out](https://user-images.githubusercontent.com/1056684/62397991-04d1c680-b53d-11e9-92c8-d867590671fe.png)

**Platform**
 - Windows 10
 - Chrome  75.0.3770.142

**Comment by tmcconechy** [comment]
@krishollenbeck I have had issues like this with the chrome desktop simulator, some things with it do not work the same. I tested this on an actual pixel 3 device and it is possible to scroll. Here i have shown it scrolled down to the login/settings.

![Screen Shot 2019-08-05 at 8 52 01 AM](https://user-images.githubusercontent.com/814283/62466075-6e7ceb00-b75e-11e9-8006-09fd9ac788bf.png)

**Comment by krishollenbeck** [comment]
@tmcconechy Okay thanks for looking into it. Unfortunately I don't currently have a way to test some of the mobile devices. I had a feeling it might have just been the emulator being misleading.

**Comment by tmcconechy** [comment]
No problem @krishollenbeck I use browserstack.com for device testing. I heard maybe your team might be getting some licenses too. But you might also want to try some of these https://www.androidauthority.com/best-android-emulators-for-pc-655308/ i have used Genymotion as well and it works rather well. I have not tried the rest and im on Mac not PC so take that for what its worth...
