### ISSUE TITLE
Date Picker with Range: "loc" appears in IE and Windows Edge

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2597]
**Describe the bug**
Date Picker with Range: "loc" appears in IE and Windows Edge when out of focus.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datepicker/example-range.html in IE and Edge
2. Open date picker in Range - No initial value
3. Select August 5 - 7, 2019
4. Click outside the date picker field
5. See issue: loc will be displayed in Range - No initial value
6. Also happening on the other range date picker fields

**Expected behavior**
loc should not appear in date picker field

**Version**
- ids-enterprise: v4.17.0 to v4.20.0-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/62461328-145c4400-b7b7-11e9-8400-f50e439f57db.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: IE, Edge

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
@brianjuan Im not able to reproduce this issue. Are the steps correct? The problem with them as i see it is when i do `3. Select August 5 - 7, 2019` the dialog closes. So the rest of the steps are invalid at that point.

**Comment by brianjuan** [comment]
http://4200-rc1-enterprise.demo.design.infor.com/components/datepicker/example-range.html
QA Passed in Windows Edge and IE.
![image](https://user-images.githubusercontent.com/39508864/62695763-8af08000-ba09-11e9-80fe-6c299ca3aa4d.png)
