### ISSUE TITLE
Date Picker: Month name is too close to the corner on Windows Edge

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2598]
**Describe the bug**
Date Picker: Month name is too close to the corner on Windows Edge.

**To Reproduce**
1. Go to https://4200-rc0-enterprise.demo.design.infor.com/components/datepicker/example-index.html on Windows Edge
2. Open the date picker field
3. See issue: Month name is too close to edge

**Expected behavior**
Month name should have correct alignment

**Version**
- ids-enterprise:  v4.20.0-beta1 to v4.20.0-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/62461694-0eb32e00-b7b8-11e9-9a17-e130aabcb426.png)

**Platform**
  - OS Version: Windows 10
 - Browser Name: Edge

**Additional context**
No additional context.

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Issue fixed. 
Tested in 
https://4200-rc1-enterprise.demo.design.infor.com/components/datepicker/test-no-month-year-picker.html
https://4200-rc1-enterprise.demo.design.infor.com/components/datepicker/example-index
Across all OS, Browser and Devices.
