### ISSUE TITLE
Date Picker with Range: Time does not applied when Select button was clicked

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2599]
**Describe the bug**
Date Picker with Range: Time does not applied when Select button was clicked.

**To Reproduce**
1. Go to https://4200-rc0-enterprise.demo.design.infor.com/components/datepicker/example-range.html
2. Open date picker on Range - with Time
3. Select August 5 - 7, 2019
4. Open the date picker again
5. Select 7:40 PM in the time dropdowns, then Click Select button
6. See issue: date picker will close but 7:40 PM will not be displayed in the field

**Expected behavior**
Selected time should be applied in the field when Select button was clicked in the date picker.

**Version**
- ids-enterprise: v4.20.0-rc0

**Screenshots**
No applicable screenshots.

**Platform**
 All devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This issue is related to https://github.com/infor-design/enterprise/issues/2595 so @deep7102 will fix along with that fix.

**Comment by brianjuan** [comment]
http://4200-rc1-enterprise.demo.design.infor.com/components/datepicker/example-range.html
Passed QA testing in all browsers.
