### ISSUE TITLE
Image: Some images not loading on design.infor.com

### ISSUE THREAD

**Issue by jblock012** [infor-design/enterprise#2601]
**Describe the bug**
The images for the "Images" and "Hierarchy" components are not loading properly.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/images/example-photos 
AND
https://design.infor.com/code/ids-enterprise/latest/demo/components/hierarchy/example-lazy-load 
2. See that the image links are broken

**Version**
ids-enterprise: Latest (4.19.4)

**Platform**
Device (if applicable) : Laptop
OS Version: Windows 10
Browser Name: Chrome and IE
Browser Version: Chrome - 75.0.3770.142 (Official Build) (64-bit) / IE - 11.165.17763.0

**Additional context**
The Data Catalog team is looking to use this for a future enhancement.

**Comment by tmcconechy** [comment]
@nickwynja @clepore @jmacaluso711 
Any ideas about where this would be fixed or if the image links can be changed to something that works. I assume the issue is just the proxy on https://design.infor.com/code/ids-enterprise/latest/demo as this is working on http://latest-enterprise.demo.design.infor.com/components/images/example-photos.html

@jblock012 This doesnt effect the functionality of the component as you can see it works everywhere but this link. There is just a problem on that particular link due to proxying. So feel free to use as you want

**Comment by nickwynja** [comment]
Seems like it's a relative path thing. The image is trying to load from `/images/10.jpg` which resolves to `https://design.infor.com/images/10.jpg`.

**Comment by tmcconechy** [comment]
I thought that too at first but it on the other sites its http://latest-enterprise.demo.design.infor.com/images/10.jpg

So that would be this? But it is not working..
https://design.infor.com/code/ids-enterprise/latest/images/10.jpg or all various combinations i tried do not seem to load

**Comment by nickwynja** [comment]
Seems like the current proxy code doesn't accept the `images` path:

https://github.com/infor-design/website/blob/master/src/config/nginx/snippets/demo-proxy.conf

**Comment by clepore** [comment]
So we should probably use the fully qualified URL for this.

**Comment by tmcconechy** [comment]
@clepore i think the relative url might work but nginx is not serving it? I think thats the first step

**Comment by clepore** [comment]
We should probably use something like the current html examples do:
```
<img alt="Placeholder Image" src="{{basepath}}images/natural.png">
```

**Comment by janahintal** [comment]
This issue is now resolved. Thanks. 
Verified in 
https://master-enterprise.demo.design.infor.com/components/blockgrid
https://master-enterprise.demo.design.infor.com/components/hierarchy
https://master-enterprise.demo.design.infor.com/components/applicationmenu
