### ISSUE TITLE
Modal: Keyboard can scroll items out of view on mobile apps

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2602]
**Describe the bug**
When running a modal on mobile and they keyboard pops up either the field is out of view or the modal will resize to smaller size taking into account space for the keyboard and making the modal smaller. This will partially be addressed by #2433 

**To Reproduce**
1. Open an ios or android simulator
1. Go to http://localhost:4000/components/modal/example-index.html
1. Open the modal
2. click into the text area

**Expected behavior**
Usability should not be too severely impacted by keyboards getting in the way. To fix this possibly do not resize the modal (and it will be bigger due to #2433. Ensure the focused element is in view.

**Version**
- ids-enterprise: [e.g. v4.20.0]

**Screenshots**
![Screen Shot 2019-08-05 at 1 24 01 PM](https://user-images.githubusercontent.com/814283/62482862-528c4000-b784-11e9-9322-984b8d661f84.png)

**Platform**
 - Device: Iphone X (or android pixel3)

**Additional context**
Seen in the infor go demo video GoWidgets4.mp

**Comment by EdwardCoyle** [comment]
> Seen in the infor go demo video GoWidgets4.mp

@tmcconechy where can I find this?

**Comment by brianjuan** [comment]
Passed QA testing on iOS browsers.
http://master-enterprise.demo.design.infor.com/components/modal/test-mobile-scrolling.html
![image](https://user-images.githubusercontent.com/39508864/67003649-04df6c80-f111-11e9-9564-cc9d2590fe9b.png)

http://master-enterprise.demo.design.infor.com/components/modal/example-index.html
![image](https://user-images.githubusercontent.com/39508864/67003716-23ddfe80-f111-11e9-85a9-0a93415bbd20.png)
