### ISSUE TITLE
Wizard: Show labels on mobile

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2604]
**Describe the bug**
When on mobile (be design) only the current labels are shown. We need to think of some solutions to help usability.

**To Reproduce**
1. Go to http://latest-enterprise.demo.design.infor.com/components/wizard/example-index.html
2. Resize to mobile size or use a mobile device
4. See that you cannot see what the next and previous steps are

**Expected behavior**
Consider some options to show the label such as:
- show the label up to ellipsis text
- long press the item or ellipsis text to show in a tooltip
- add ability to show abbreviated / shorter versions of the wizard text

**Version**
- ids-enterprise: [v4.20.0]

**Screenshots**
![Screen Shot 2019-08-05 at 1 33 07 PM](https://user-images.githubusercontent.com/814283/62483409-93d11f80-b785-11e9-8600-bed84d4cb2c6.png)

**Platform**
 - Device: desktop mobile size or IOS or android

**Additional context**
This was noted in GoWidgets4.mp

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. I tested this on iPhone XS and Android. Moving this ticket to the Done bucket.
