### ISSUE TITLE
Contextual Action Panel: Extra space on mobile when there is longer text.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2605]
**Describe the bug**
Using the CAP (workspaces example). If the text is longer there will be an overflow causing a white space on the right.

**To Reproduce**
1. Go to http://localhost:4000/components/contextualactionpanel/example-workspaces.html
2. Edit the title in the DOM so it says something longer like "Promote Pearl Reynolds Promote Pearl Reynolds"
3. Resize to mobile or use a mobile device

**Expected behavior**
No white gap and better text overflow

**Version**
- ids-enterprise: [e.g. v4.20.0]

**Screenshots**
![Screen Shot 2019-08-05 at 1 48 47 PM](https://user-images.githubusercontent.com/814283/62484234-c5e38100-b787-11e9-8494-2eea0dc29e80.png)

**Platform**
 - Device  [Desktop Responsize or IOS or Android newer devices]

**Additional context**
Infor Go Video/Slide show.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Closing out this ticket.
