### ISSUE TITLE
Themes: Rename themes/variants and set a default theme to uplift

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2606]
**Is your feature request related to a problem? Please describe.**
We are still deciding on names for the "themes" and would like to change the naming and make the new theme the default. See See https://jira.infor.com/browse/HLO-231 for final decisions

Latest Idea we mostly like:
Themes -> Called names (so for example new and classic)
Variants -> Called Modes

**Describe the solution you'd like**
References should be changed to the new thing for:
```
Subtle - Light -> Classic - Light
Subtle - Dark -> Classic - Dark
Subtle - Contrast -> Classic - High Contrast 
Vibrant - Light -> New - Light
Vibrant - Dark -> New - Dark
Vibrant - Contrast -> New - High Contrast 
```

**Steps**

- [ ] Remove the older, older copies of the theme files the last file rename since deprecated a while
- [ ] Make the css files generated as the new names (and keep the previous ones?)
- [ ] Make the js files generated as the new names (and keep the previous ones?)
- [ ] Make the demo app switcher show the new text
- [ ] Make the newest UX the default in the demo app
- [ ] Update and resend the translations for update (done?)
- [ ] Update any examples and code mentioning the the names and code mentioning old names
- [ ] Switcher API should accept the older names and map them
- [ ] Update any docs mentioning the the names
- [ ] Update the change log with appropriate notes

**Comment by tmcconechy** [comment]
Logged this issue for now but there may be further branding changes so we should wait a bit for the names to settle.

**Comment by tmcconechy** [comment]
@inforandy please add this to the queue

**Comment by inforandy** [comment]
got it here, thanks @tmcconechy https://jira.infor.com/browse/HLPE-452

**Comment by tmcconechy** [comment]
See https://jira.infor.com/browse/HLO-231 for final decisions.

**Comment by jbrcna** [comment]
working as expected. verified in v4.38.0-dev 
https://master-enterprise.demo.design.infor.com/components/datagrid/example-index

**Comment by CindyMercadoReyes** [comment]
Adding the BDD to this ticket. 
[BDDStory_github2606[1].docx](https://github.com/infor-design/enterprise/files/6051580/BDDStory_github2606.1.docx)
