### ISSUE TITLE
SOHO-2182: 4.0 Calendar Control

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#261]
**Landmark Requirements:**
- Allow display of calendar items to span dates and times.
- Allow a legend with a checkbox control to display/hide matching items
-  Allow click events on open areas and on calendar items: double click, right click (to open and show right click menu)
- Date navigator to go to the next/prev week, month, day.
If drag and drop is allowed:
- Need a way to tell calendar whether item is draggable or not.
- Need an event on drop with "done" and "cancel" responses.
need to be able to cancel the drop from completing after drop event.
- Need an onSelection event
- Keyboard handling to notify by an event for show, add, update, delete (high priority)
- Keyboard navigation
- Right to left compliant
- Other calendar support: Hijri, other?

**Optiva Requirements**
- Shared calendars
-  Support for defining working days and working hours for groups of employees
    i.e. Monday through Friday. 7AM to 3PM
- Support for adding site level holidays
- UTC support
- We need support for importing and exporting calendar event data using a standard format
- The standard iCalendar (.ICS) format is supported by Outlook and Google Calendar for import from outlook.

**Pathway Requirements**
For ePathway, the following requirements are critical:
 
- View which days of the month are fully booked (i.e. all available times booked)
- View which times in a day are booked
- Ability to configure blocks/intervals of time (e.g. 15 minute blocks, 2 hour blocks etc.)
- Ability to configure starting (availability) date and final (availability) date. For example, a facility is available from the 1st of next month up until the end of the calendar year.
- Nice to have: If booking a facility (e.g. tennis courts), Google Maps integration to display/view the facility and other nearby facilities

Need By Landmark and Optiva and Pathway.

**Other Calendar Examples:**
http://fullcalendar.io/ - note this works but doesnt not have accessibility and H&L designs so cannot be used at present in current state.

https://calendar.google.com/calendar/render?hl=cy&tab=gc&pli=1#main_7

https://github.com/nhnent/tui.calendar/blob/master/README.md

**Design**
[SoHo Calendar-UI-v1_050418_JN.pdf](https://github.com/infor-design/enterprise/files/2176670/SoHo.Calendar-UI-v1_050418_JN.pdf)

**Comment by brianjuan** [comment]
http://4100-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html?locale=en-US
http://4100-beta0-enterprise.demo.design.infor.com/components/monthview/example-index.html#
Passed QA testing
