### ISSUE TITLE
Fieldset overlapping text when in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2610]
**Describe the bug**
Fieldset overlapping text when in responsive view

**To Reproduce**
1. Go to http://4200-rc0-enterprise.demo.design.infor.com/components/fieldset/example-index.html?theme=uplift&variant=light&colors=0563C2
2. Minimize the screen
3. Scroll down, in the Available Credit and see the label below are overlapping 

**Expected behavior**
Text should not overlap each other

**Version**
4.20 - 4.17

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/62525217-96a54080-b869-11e9-887e-40a53487629a.png)

**Platform**
All Browser, OS and devices

**Additional context**
No any other context about the problem here.

**Comment by tmcconechy** [comment]
I think that the chart is not being initialized as it is on http://localhost:4000/components/completion-chart/example-index.html

**Comment by ericangeles** [comment]
@tmcconechy , what is your suggestion here?

**Comment by janahintal** [comment]
QA Passed. Will move to Done. 
Verified in http://master-enterprise.demo.design.infor.com/components/fieldset/example-index.html?theme=uplift&variant=light&colors=0563C2 Thanks.
