### ISSUE TITLE
Date Picker: Selected day is also highlighted when viewing other months

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2611]
**Describe the bug**
Date Picker: Selected day is also highlighted when viewing other months.

**To Reproduce**
1. Go to http://4200-rc0-enterprise.demo.design.infor.com/components/datepicker/example-index.html
2. Open date picker
3. Select August 9
4. Open date picker again then click arrows to view other months
5. See issue: "9" is also selected in other months

**Expected behavior**
Selected day should not be highlighted when viewing other months.

**Version**
- ids-enterprise: v4.20.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/62527734-4e3c5180-b86e-11e9-887c-0e3bd900e074.png)

**Platform**
 - All devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
We did this one purpose so that there is a day that can be focused with the keyboard. When changing month it goes to the next month and keeps the currently selected day.

**Comment by brianjuan** [comment]
Thanks for the clarification @tmcconechy.
