### ISSUE TITLE
Searchfield Uplift: Text is too low in IE

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2612]
**Describe the bug**
Searchfield Uplift: Text is too low in IE.

**To Reproduce**
1. Go to http://4200-rc0-enterprise.demo.design.infor.com/components/searchfield/example-index.html in IE
2. Click ... Menu, then select Uplift under Theme
3. In the searchfield, type A then choose American Samoa
4. See issue: text is too low

**Expected behavior**
Alignment of text in searchfield should be vertically centered.

**Version**
- ids-enterprise: v4.20.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/62528349-46c97800-b86f-11e9-9c50-848b97bccc01.png)

**Platform**
 - OS: Windows 10
 - Browser: IE 11

**Additional context**
No additional context.

**Comment by janahintal** [comment]
QA Failed. 
Issue still exist in https://4200-rc1-enterprise.demo.design.infor.com/components/input/test-comparison-of-fields.html?theme=uplift#

Windows 10 IE 11 
![image](https://user-images.githubusercontent.com/45757016/62697729-ee7cac80-ba0d-11e9-8af7-a51862715d67.png)

**Comment by brianjuan** [comment]
Passed QA testing, also tested on all browsers.
https://4200-rc2-enterprise.demo.design.infor.com/components/searchfield/example-index.html
![image](https://user-images.githubusercontent.com/39508864/62855507-0b262680-bd25-11e9-8acf-666bd39ac266.png)

https://4200-rc2-enterprise.demo.design.infor.com/components/input/test-comparison-of-fields.html
![image](https://user-images.githubusercontent.com/39508864/62855562-2d1fa900-bd25-11e9-8862-621e3862dc52.png)
