### ISSUE TITLE
Input with Contextmenu: Cannot type in iOS browsers

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2613]
**Describe the bug**
Input with Contextmenu: Cannot type in iOS browsers.

**To Reproduce**
1. Open browsers on iOS devices
2. Go to http://master-enterprise.demo.design.infor.com/components/input/example-contextmenu.html
3. Try to type anything in the input field
4. See issue: unable to type

**Expected behavior**
Should be able to type in input field with contextmenu using iOS

**Version**
- ids-enterprise: v4.14.0 to v4.20.0

**Screenshots**
No applicable screenshots.

**Platform**
 - OS Version: iOS
 - Browser Name: Safari, Chrome

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This is acting strangely I can type in it but not with the keyboard and I cannot select text.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/input/example-contextmenu.html
Passed QA testing in iOS (iPhone and iPad) browsers, will retest once beta is deployed.
![image](https://user-images.githubusercontent.com/39508864/66903364-edcb4c80-f034-11e9-99e7-fe6a3a46f90b.png)
