### ISSUE TITLE
Margin issue in uplift menu

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#2616]
**Describe the bug**
Uplift theme - Noticed sub menus don't have the left margin as in soho light theme.

**To Reproduce**
1. Go to 'http://localhost:4200/ids-enterprise-ng-demo/application-menu-roleswitcher'

**Expected behavior**
Submenus to be indented in uplift theme.

**Version**

- ids-enterprise: v4.20.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39130590/62559537-cbe96880-b840-11e9-9954-3e7e545715f5.png)
![image](https://user-images.githubusercontent.com/39130590/62559687-03f0ab80-b841-11e9-8c33-6008095a21fe.png)

**Platform**
 - OS Version: Windows 10

**Comment by tmcconechy** [comment]
I would suspect the mark up. Did you try to compare this to http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels-icons.html?theme=uplift&variant=light&colors=0563C2 im seeing the indents on the "level one out bound links examples" so suspecting incorrect markup in the example?

**Comment by vonnyw** [comment]
This example has an extra div with accordion-content class on it. We don't use that, just using accordion-header and accordion-pane. They work as expected in soho-light but not in soho-uplift.

**Comment by tmcconechy** [comment]
Ok that might be the workaround for this (adding the extra markup to indent the content). But i can see if it works in one and not the other something may be missing

**Comment by davidcarlsonberg** [comment]
Visiting the above URL, can't seem to reproduce the issue.

**Comment by tmcconechy** [comment]
Same it doesnt look like the demo has the example with those submenus? Do you have code for this @vonnyw ?

**Comment by vonnyw** [comment]
Yes, I had to add a few more submenus to the demo to illustrate the issue. I have the code for it, should I attach it here?

**Comment by tmcconechy** [comment]
Yes thats the key thing missing to reproduce this. Just note what you need to change/add to see it

**Comment by vonnyw** [comment]
Please copy and paste the attached html into application-menu-roleswitcher.demo.html under any of a submenu's accordion-header element.
[git#2616.txt](https://github.com/infor-design/enterprise/files/3482810/git.2616.txt)

**Comment by brianjuan** [comment]
Will move to Done since it is working and cannot be replicated in IDS enterprise.
