### ISSUE TITLE
File Upload Advance: Label need to display what type of files can be uploaded

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2620]
**Describe the bug**
File Upload Advance: Label need to display what type of files can be uploaded

**To Reproduce**
1. Go to URL: https://4200-rc0-enterprise.demo.design.infor.com/components/fileupload-advanced/example-allowed-types.html
2. Click on "Select Files" from the Drag and Drop file upload 
3. The open window explorer will appear
4. The issue hers is that, when the open window explorer pops up it the user only sees png|jpg|gif files.  So it confuses the user. We need a label on the UI stating you can only upload " jpg|png|gif" files 

**Expected behavior**
Need label on the UI stating the user can only upload " jpg|png|gif" files 

**Version**

- ids-enterprise: [ v4.20.0]

**Screenshots**
![Advance File Upload](https://user-images.githubusercontent.com/39101346/62575722-63fb4800-b869-11e9-8219-44142be363d2.png)

**Platform**
 - All Browser 

**Additional context**
None

**Comment by tmcconechy** [comment]
Suggest a label is added after the “upload files” text on the initial drop box.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Closing out this JIRA ticket.
