### ISSUE TITLE
Lookup Popup: Applying selection not on <Enter> Key

### ISSUE THREAD

**Issue by LotharBlum** [infor-design/enterprise#2622]
**Describe the bug**
Application of selected list item in Lookup Popup is not executed by *Enter*Key but *Space* Key. This is not expected behavior.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/example-index
2. Click on Lookup Icon in the field. Your will get the Select Popup
3. Select an item in the list using keyboard. You will need to do this with tab and arrow keys. Focus is on the selected item.
4. Once focused, I as a user using a keyboard would press *Enter* to apply the selection. This is THE button for applying something or executing something on desktop devices.
5. However, system does not execute on *enter* but on *space*. How would I know this as a user?

**Expected behavior**
Apply selection on *Enter*Key.

**Version**

- ids-enterprise: 4.19.4

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47633092/62612615-036f1800-b908-11e9-8791-3867b8f0ec56.png)

**Platform**
 - Notebook
 - both WIN and Mac
 - FF [68]

**Additional context**
Behavior should be compliant with ARIA guidelines. But maybe it is already and that is part of the problem.

**Comment by tmcconechy** [comment]
Currently you can use space to select. I would agree that we could make enter key select especially if we add the apply button then the enter would action on that primary dialog button.

**Comment by tmcconechy** [comment]
Descoping this for now as space is valid. Will consider this for future refactor of lookups
