### ISSUE TITLE
Lookup: Make single select also have an apply button

### ISSUE THREAD

**Issue by LotharBlum** [infor-design/enterprise#2623]
**Is your feature request related to a problem? Please describe.**
Currently the lookup popup aka. "lookup modal" is behaving in a way, that the selection of an item in the single select list is combined with the application of that selection. This results in taking over the selected item into the lookup field and the closing of the popup.

![grafik](https://user-images.githubusercontent.com/47633092/62615381-6d3df080-b90d-11e9-8811-05380a3d83e8.png)

I understand that combining two interactions together is motivated by reducing required clicks from the user. However, two things:
- it feels wrong to me as there is no robustness to errors. Anything clicked in the list is taken over, the popup closes and the user has no chance to check if what he has selected is really what he wants. Only the reduced information in the lookup field will be displayed. If the user wants to check that the selected item is correct, he need to open the lookup popup again.
- in dEPM we have single select lists with 100-1000 items, an integrated paging component and search bar. This results in a more complex screen with way more data. My thoughts are, that there is more cognitive load and invested time of the user to finding the right selection anyway than what your example in the IDS library is showing. An additional click for applying the selection would not change the effort within complex settings that much. 
- In dEPM we also have multi-select popups which require to separate selecting items from applying them. Thus, addional aspect of consistent interaction within very similar types of lookup popups need to be taken into account.

Example:
![grafik](https://user-images.githubusercontent.com/47633092/62616181-2ea93580-b90f-11e9-95d1-f9de31cf313a.png)

**Describe the solution you'd like**
Separate interaction for selecting list item and applying (including the closing of the popup) by adding an OK / Apply Button to the modal button in the popup.

**Describe alternatives you've considered**
Might require to discuss the topic 

**Additional context**
Might affect this ticket about Key commands: https://github.com/infor-design/enterprise/issues/2622

**Comment by tmcconechy** [comment]
I think it could make sense to make the apply button on single select lookup the same as the multiselect lookup. If we do this i would make it an option `clickToSelect` so that the current behavior if enjoyed by the current users is not taken away. 

Related to #2622

**Comment by tmcconechy** [comment]
Closing this for now. Single select now has a apply button https://master-enterprise.demo.design.infor.com/components/lookup/example-index.html

We did this for another issue
