### ISSUE TITLE
Toast: Control not destroyed when removed from screen which causes memory leak

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#2634]
**Describe the bug**
The toast control is not destroyed from memory after it is removed from the screen, which causes memory leaks. It should automatically call its "destroy" api, similar to how the Modal control automatically destroys itself when it is closed (see logic in Modal's "close" function which calls "destroy"). These memory leaks can build up over time in a SPA and cause the browser window to slow down and crash.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/toast/example-index.html
2. Open the Memory tab in Chrome Developer Tools
3. Click the 'Collect garbage' button to remove any clutter
4. Click the 'Take snapshot' button to get a comparison point of the memory heap.
5. Click the "Show Toast Message" button
6. Wait for the toast message to be removed
7. Click the 'Collect garbage' button again
8. Click the 'Take snapshot' button to get another memory heap.
9. While looking at "Snapshot 2" change the dropdown which says "All objects" to "Objects allocated between Snapshot 1 and Snapshot 2" (this will help you see what is hanging around in memory due to the toast message being shown and removed)
10. Look at the results in the list to see what the toast message left hanging around in memory. For example there is an instance of "Toast" and some Detached HTML elements (see items in screenshot below)

**Expected behavior**
The Toast control should be automatically destroyed after it is removed from the screen, similar to the Modal control (https://design.infor.com/code/ids-enterprise/latest/demo/components/modal/test-destroy-on-close.html). After the destroy api on a control is called it should no longer exist in memory.

**Version**
- ids-enterprise: v4.19.4

**Screenshots**
![image](https://user-images.githubusercontent.com/14128010/62730200-7e5e2e80-b9ed-11e9-87c7-1b6a57d70a77.png)

**Platform**
 - Device: Dell Laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 75.0.3770.142 (Official Build) (64-bit)

**Comment by brianjuan** [comment]
http://localhost:4000/components/toast/example-index.html
http://master-enterprise.demo.design.infor.com/components/toast/example-index.html
Passed QA testing in Mac and Windows Chrome, as well as IE11.
![image](https://user-images.githubusercontent.com/39508864/63244388-d4559080-c28f-11e9-8785-9c4183733c6d.png)
