### ISSUE TITLE
getCulturePath does not handle if sohoxi.js filename has a hash part

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#2637]
**Describe the bug**
getCulturePath does not handle if sohoxi.js filename has a hash part

**To Reproduce**
1. Add a hash part to filename e.g. sohoxi.hashedpart123.js
2. Change locale to e.g. en-NZ

**Expected behavior**
Language en-NZ loaded in Soho.Locale.cultures

**Version**
- ids-enterprise: 4.18.1

**Comment by guoliang** [comment]
I created a PR https://github.com/infor-design/enterprise/pull/2638

**Comment by tmcconechy** [comment]
OK, please assign yourself to issues you plan to address. (We cant assign some users only those attached to the project). Thanks for fixing this!

**Comment by guoliang** [comment]
I don't think I can assign myself to this issue either. At least I cannot see that option

**Comment by tmcconechy** [comment]
Ok strange? I wasnt sure about that either. Oh well.
