### ISSUE TITLE
SOHO-8165: Tree Functional and E2E Tests

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#264]
### Original ticket: [SOHO-8165](https://jira.infor.com/browse/SOHO-8165)

Add some tests for Tree

See existing tests for example textarea, dropdown, treemap, menubutton for reference. Also see docs/TESTING.MD for commands. Ask for help on sohoxi-dev if needed.

Functional Tests
- Test events that get triggered
- Test events that are listened to
- Test all API methods, most importantly the public ones first and the rest for coverage. (fx enable/disable)
- Test lifecycle methods (init, teardown, destroy, invoke)
- Test setting and that some states are applied

E2e Tests
- Load each test page in the components/<name>/list and test the main ideas of the page, if unsure of the main idea ask on the channel.
- Keyboard

Tree Grid Specific Test Considerations 
see all of http://localhost:4000/components/tree/list examples and tests

Other Tests
- Accessibility tests https://github.com/dequelabs/axe-core
- Security Tests (TBD)
- Specific Test Cases from Cindy (TBD)
- Protractor Image Comparison Tests  (TBD)

**Comment by CindyMercadoReyes** [comment]
QA verified. Moving this ticket to the Done folder.
