### ISSUE TITLE
Locale: Allow default locale loading to be disabled

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise#2640]
**Describe the bug**

Angular application provide their own mechanisms for loading and initialising localisations, often using the APP_INITIALIZER approach.  However, the Locale object in the EP controls automatically loads the en_US.js script from the default location before Angular has had a chance to initialise their location or augment the translations.

**To Reproduce**

You can see this by running enterprise-ep demo applications from the angular-8 branch.  this often (but not always) displays an error loading en_US.js as `Soho.Locale.culturesPath` has not yet been set.

**Expected behavior**

Being able to disable the "automatic" loading of the default locale from the route of the application would remove the error, and allow the standard angular locale initialiser to complete.

**Version**

angular enterprise-ng 5.5-beta

**Screenshots**

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Need this for NG 8... So will try and address this somehow.

**Comment by bthharper** [comment]
Could we turn off the initialisation like this:

```html
<script>
   window['SohoConfig'] = { renderLoop: { noAutoStart: true }, Locale: { initialization: false} };
</script>
```

**Comment by tmcconechy** [comment]
I could do that but i think this code is not needed so checking that first

**Comment by bthharper** [comment]
Even better! :-)

**Comment by janahintal** [comment]
QA passed. Working well in all Browser, OS and devices. 
Verified in: http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=de-DE
