### ISSUE TITLE
Slide demo is failing with javascript error

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2647]
**Describe the bug**
Slider demo is failing when using 'very-poor' color.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/slider/example-colors-and-ticks.html
2. Open your devtools and see console error and notice the slider component does not actually work.

**Expected behavior**
No error and slider w/'very-poor' tick should work. 

**Version**
4.21

**Screenshots**
![image](https://user-images.githubusercontent.com/4737815/62892676-7a445080-bd0e-11e9-9c9f-c5c15878a68e.png)

**Comment by tmcconechy** [comment]
Appears this broke during theme adjustments in 4.19

**Comment by janahintal** [comment]
QA Passed. Working well in all OS, Browser and devices. 
Verified in: 
 http://master-enterprise.demo.design.infor.com/components/slider/example-vertical.html?theme=uplift&variant=dark&colors=56932e & http://master-enterprise.demo.design.infor.com/components/slider/example-colors-and-ticks.html?theme=uplift&variant=light&colors=56932e
