### ISSUE TITLE
Datepicker: Cursor is showing in calendar in IE

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2649]
**Describe the bug**
Datepicker cursor is showing in calendar in IE

**To Reproduce**
1. Go to http://4200-rc3-enterprise.demo.design.infor.com/?theme=uplift&variant=light&colors=0563C2
2. Goto datepicker and select January 2018 in date & month picker
3. Notice that the cursor is still blinking in the calendar

**Expected behavior**

**Version**
4.20

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/62931937-d0d68b00-bdf1-11e9-8831-c62e0b979db8.png)

**Platform**
Windows 10 IE 11

**Additional context**
NA

**Comment by tmcconechy** [comment]
This is very minor, probably not even worth addressing. But will keep open for now

**Comment by tmcconechy** [comment]
Seems like this can only be reproduced on an actual windows PC (not browser stack). This may be too minor to fix once we deprecate IE 11.

**Comment by tmcconechy** [comment]
Decided this issue is not worth fixing so closing.
