### ISSUE TITLE
SOHO-7983: Chart issues  in angular controls

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#265]
### Original ticket: [SOHO-7983](https://jira.infor.com/browse/SOHO-7983)

- 🚫~missing animation on radar (wont do)~
- ✅  emptyMessage input missing on Pie chart
- 🚫  ~tooltip input missing on column (wont do)~
- ✅  getSelected missing on all chart components
- ✅  setSelected input missing on all chart components

I Believe we could set this by passing an index but we also passed an object with a reference of some kind and a value. You would find the element with the reference attribute and value that matched and select it. In our case we pass a ref vaule in each of our data nodes to tie it back to the dataset that we used to create the data we pass into the chart.   

```java
      if (this._chartOptions.type.indexOf('grouped') >= 0 || this._chartOptions.type === 'column') {
        selectOptions = {groupName: 'ref', groupValue: ref};
      } else {
        selectOptions = {fieldName: 'ref', fieldValue: ref};
      }

      this.chart.setSelected(selectOptions);
```

- ✅  Legend needs to be able to scroll and overlays chart in some cases
![screenshot-1](https://user-images.githubusercontent.com/742319/41861169-82e87b3e-786e-11e8-9ff6-6a9e7c3c4cff.png)

**Comment by brianjuan** [comment]
Bug fix is working as expected across all browsers and passed the QA testing.
See screenshot below.
![image](https://user-images.githubusercontent.com/39508864/42862133-35f5d9a0-8a2c-11e8-92a7-5bd062ab8a25.png)
