### ISSUE TITLE
Dropdown: List not closed on scroll within modal

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#2650]
**Describe the bug**
If using a dropdown within a scrollable area in a modal (that is not the modal body), its list will not close when scrolling that area. Instead, it sticks in place.

**To Reproduce**
I don't have any good example, but it should be noticeable in any modal that has a scroll section with a dropdown other than the modal body.

**Reason in dropdown code**
```
var modalScroll = $('.modal.is-visible .modal-body-wrapper');
// Below line is fine, it finds the closest scrollable panel properly
var parentScroll = self.element.closest('.scrollable').length ? self.element.closest('.scrollable') : $(document);
parentScroll = self.element.closest('.scrollable-y').length ? self.element.closest('.scrollable-y') : parentScroll;
// But below line sets it to the modal body anyway, even though it's not the closest parent nor scrollable
parentScroll = modalScroll.length ? modalScroll : parentScroll;
// scrollDocument is never invoked as a result (in which dropdown list is closed)
parentScroll.on('scroll.dropdown', scrollDocument);
```
It seems to me that scrollable & scrollable-y should be prioritized instead, and then fall back to modal body if there aren't any? Or perhaps attach scroll event on both parent + modal body.

Let me know if you need any additional context.

**Expected behavior**
Dropdown list closes if its nearest scrollable parent is scrolling

**Version**
- ids-enterprise: v4.19.4

**Comment by tralarn** [comment]
What is the status for this issue?

**Comment by tmcconechy** [comment]
Status: No time yet for this. But added it to the upcoming sprint.

**Comment by EdwardCoyle** [comment]
@volante007 apologies for the delay on getting to this issue.  I'm exploring it now and just wanted to clarify:

> I don't have any good example, but it should be noticeable in any modal that has a scroll section with a dropdown other than the modal body.

Are you saying that you have a scrollable element within a `.modal-body` element?  Or are you saying that you have a scrollable section with no `.modal-body` element?  Or both/either?

**Comment by volante007** [comment]
Hi @EdwardCoyle , sorry for the late reply!

We have a .modal-body etc. (all standard modal wrappers). Inside, in our "own content", we have a scrollable sidebar as well.

**Comment by janahintal** [comment]
The issue is now resolved. The dropdown closes when the modal is scrolled. Thank you. 

Verified in: 
https://master-enterprise.demo.design.infor.com/components/dropdown/test-in-modal-content.html?theme=uplift&variant=light

Only found some minor issue below. I will just file a new ticket for it. 
![image](https://user-images.githubusercontent.com/45757016/77039019-0e3a7100-69f0-11ea-9a7b-ece2b55fbe9f.png)
