### ISSUE TITLE
Multiselect: Sending back selected: true in the JSON is not selecting the value

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2656]
**Describe the bug**
Expecting that if the ajax data contains `select: true` it will mark these items as selected in the list.

**To Reproduce**
1. Go to multiselect/example-ajax
2. Edit the select to have one selected inline (angle to this issue)
```
      <select id="ajax-test" name="ajax-test" class="dropdown" data-init="false">
        <option selected value="FL">Florida</option>
      </select>
```
3. Edit `app/data/states.js`  to have a couple (or all selected: true
4. Open the list
5. Only FL is selected. 

**Expected behavior**
The current logic is to look in the field for whats selected but it selected is passed in the Ajax expect that to take precedence.

**Version**
- ids-enterprise: [e.g. v4.20.0]

**Platform**
 - All (Chrome)

**Additional context**
- From a MS teams convo
- this code is where the update to fix this would be https://github.com/infor-design/enterprise/blob/master/src/components/dropdown/dropdown.js#L2658

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
