### ISSUE TITLE
Datagrid: Actions column formatter removes arrows from all elements in DOM

### ISSUE THREAD

**Issue by albinbergvall** [infor-design/enterprise#2657]
**Describe the bug**
The _actions_ formatter for data grid columns has the unwanted side effect of removing the arrows from all tooltips in the application after the actions popupmenu menu has been closed. The formatter uses the soho-popupmenu component to render the popupmenu, and in the teardown of the popupmenu component all elements inside the wrapper of the popupmenu is removed. This is to remove the arrow which is rendered when the popupmenu is opened. In the teardown the popupmenu is also unwrapped which removes the wrapper of the component. The bug appears due to destroy being called twice for the popupmenu, once internally inside the component and once inside the datagrid. Since the component has already been unwrapped, the parent is now the body tag inside of the DOM. This causes _ALL_ elements with the arrow class to be removed. Since the tooltip component has a div element with the arrow class, this will no longer function. 

**To Reproduce**
Reproduced using enterprise-ng v.5.5.1
1. Open 'DataGrid - Service' demo 
2. Click the '...' button in the actions column
3. Close the dropdown
4. Open 'Tooltips' demo
5. Hover one of the tooltip triggers
6. The tooltip is shown but no arrow is present. A refresh is required to show the arrow once more. 

**Expected behavior**
The tooltip is shown with an arrow.

**Version**

- Reproduced in ids-enterprise: v.4.21.0-dev

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/30404138/63082222-eeb50480-bf45-11e9-9a9d-25caa25fea9d.png)
After:
![image](https://user-images.githubusercontent.com/30404138/63082269-0a200f80-bf46-11e9-8ad6-c3d3ea04db51.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
Destroy call internally in the popupmenu: 
https://github.com/infor-design/enterprise/blob/1ece66d0707e5702ec318e58b99e2526e67a6d5e/src/components/popupmenu/popupmenu.js#L2148

Destroy call inside datagrid: 
https://github.com/infor-design/enterprise/blob/1ece66d0707e5702ec318e58b99e2526e67a6d5e/src/components/datagrid/datagrid.js#L5886

Popupmenu teardown:
https://github.com/infor-design/enterprise/blob/c7dc302b5ec2c475edab750bf236b95ba4da668f/src/components/popupmenu/popupmenu.js#L2186

**Comment by tmcconechy** [comment]
This does not seem to happen in http://localhost:4000/components/datagrid/test-all-formatters.html so something related to the NG lifecycle as well.

**Comment by volante007** [comment]
That example probably works since the cell also has a tooltip. In datagrid control, popupmenu.destroy() isn't called if the element has a tooltip. 

```
if (el.data('popupmenu') && !el.data('tooltip')) {
   el.data('popupmenu').destroy();
}
```

https://github.com/infor-design/enterprise/blob/1ece66d0707e5702ec318e58b99e2526e67a6d5e/src/components/datagrid/datagrid.js#L5885

Without tooltip, destroy() would be called twice.

**Comment by tmcconechy** [comment]
Yeah can test this example with no tooltip and see then...

**Comment by tmcconechy** [comment]
Descoping this one as too complex to solve for the moment.
