### ISSUE TITLE
Locale: Formatter is broken for Slovak language for full date format

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise#2658]
**Describe the bug**
When Soho.Locale.formatDate is used with Locale set to sk-SK, it returns broken string format for dateFromat: full

**To Reproduce**
1. Go to sample app
2. Set Locale & Language to sk-SK
3. in console try to format date
```
var dateToFormat = new Date();    
var fullDate = Soho.Locale.formatDate(dateToFormat, { pattern: Soho.Locale.currentLocale.data.calendars[ 0 ].dateFormat.full });
```
4. See error result "štvrtok 15. **PM**ugusta 2019"" 

**Expected behavior**
date should be "štvrtok 15. augusta 2019"

**Version**
Soho.version in console shows -> 4.19.4

**Comment by tmcconechy** [comment]
I found on 4.25/4.26-dev that this was now working. Must have been fixed, added a new test https://github.com/infor-design/enterprise/pull/3373/files#diff-aa0a79b8248cb1237ef6589d2049198fR1290
