### ISSUE TITLE
SOHO-7686: Data Entered In Typeahead Not Available In The Dropdown Control

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#266]
### Original ticket: [SOHO-7686](https://jira.infor.com/browse/SOHO-7686)

hi, I think we have an error in the Dropdown typeahead binding & I'm seeing the same thing in the 4.4.0 build.

The control I'm looking at is the Angular "Dropdown-Single Select" with "States - From Source".

What I'm looking for is a subscription to the typeahead data. Each time the user presses a key then my app needs to respond & do something extra. The way to do this is through the "source" property which the Angular control uses - [source]="source".

However, the source method (in dropdown.demo.ts) is getting called only once with a searchTerm of "".  It doesnt get called again after subsequent user keypresses.

Could you please have a look. Maybe this is expected behavior - if so could we please have a "searchTerm" Output event added to the API so we can subscribe that way? Thanks

![screenshot-1-1](https://user-images.githubusercontent.com/742319/41861308-dcc3a386-786e-11e8-8aaa-3c6668f78ea6.png)

**Comment by EdwardCoyle** [comment]
@clepore this is basically the NG part of #267... does it make sense to open an issue for this in NG and close this one?

**Comment by tmcconechy** [comment]
or just leave #267 if it covers it and add a note there linking back

**Comment by EdwardCoyle** [comment]
Closing this one.  The related enterprise work has been done in #267, and I just raised infor-design/enterprise-ng#136 to track the work specifically in that repo.
