### ISSUE TITLE
Minify culture js files before shipping to npm

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise#2660]
**Is your feature request related to a problem? Please describe.**
No problems related.

**Describe the solution you'd like**
- [x] minify the culture files in the `dist/` folder (@tmcconechy do you forsee any issues with this?)
- [ ] find a way to test the compressed culture files
- [x] replace UglifyES with Terser
- [x] re-test the build

At the moment, `ids-enterprise` is shipped to npm with `sohoxi.min.js`. However all js files in `dist/js/cultures` are not minified. These files should be minified as well, like `sohoxi.min.js`.

and also perhaps, minifying process should switch to use `terser` instead of `UglifyJS`

**Describe alternatives you've considered**
**N.A.**

**Additional context**
**N.A.**

**Comment by EdwardCoyle** [comment]
@ahnpnl thank you for pointing this out.  We didn't know that [UglifyES isn't maintained anymore](https://github.com/mishoo/UglifyJS2/issues/3156#issuecomment-392943058)!

[Terser](https://github.com/terser-js/terser) seems to be a maintained fork of UglifyES so makes sense we'd switch to that.

**Comment by EdwardCoyle** [comment]
Todos here:
- [ ] minify the culture files in the `dist/` folder (@tmcconechy do you forsee any issues with this?)
- [ ] find a way to test the culture files
- [ ] replace UglifyES with Terser
- [ ] re-test the build

**Comment by tmcconechy** [comment]
That should be fine. But I think we will need a setting so that the code knows which file pattern to fetch (for debugging)?

Terser seems good, maybe it will even speed up builds a bit.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done bucket.
