### ISSUE TITLE
Toolbar Flex Component: Menu button's popup menu lost when attachToBody used

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2664]
**Describe the bug**
The popupmenu associated with a menu button is getting lost when using attachToBody: true. When tracking thru the code, on init the menu is being moved up to the <body> tag (which is correct), but after the page is rendered, I don't see the menu anywhere in the dom.

I think the menu is getting moved, and then destroyed. Maybe something from the memory leak fix a couple weeks ago?

Also, we need to use the attachToBody:true option, since without it iOS broswers put the popupmenu content underneath the contents below a toolbar. Only when viewing it on a physical device.

**To Reproduce**
I currently can only reproduce this on a landmark system. I can share my system with the person who works on it.

**Expected behavior**
Menu button should open correctly.

**Version**

- ids-enterprise: 4.21.0-dev

**Screenshots**
This is seen in the browser console after the page is rendered:
![image](https://user-images.githubusercontent.com/22107636/63294128-3366d580-c28f-11e9-80dd-621b852d55d6.png)

**Platform**
 - All

**Comment by lipetzan** [comment]
We can't move forward with the flex toolbar changes we are all ready for without this fix

**Comment by EdwardCoyle** [comment]
Troubleshooting with @Sovia seemed to show a Popupmenu Component API somehow getting setup without a menu present against a menu button:

![Screen Shot 2019-08-19 at 3 31 16 PM](https://user-images.githubusercontent.com/3249601/63299215-3cfa3880-c2a3-11e9-9b9c-36e3f2d6a4e4.png)

Will need to test it further.  Because we can't currently replicate this in EP only, I'm wondering if the lifecycle changes to fix the memory leaks may need to be accounted for in NG as well?

**Comment by EdwardCoyle** [comment]
@lipetzan @Sovia will we need to patch this into an existing release, or will you guys be testing this against `4.21.0-dev`?

**Comment by tmcconechy** [comment]
Suggest we do this in 4.21 (as you did).

**Comment by Sovia** [comment]
@EdwardCoyle we're on 4.21.0-dev. We get whatever ep build is in ep-ng.

**Comment by EdwardCoyle** [comment]
I've pushed [a branch](https://github.com/infor-design/enterprise/compare/2664-flextoolbar-menubutton?expand=1#diff-ef9fe0a0c3937dc05ef6b0e959b8ae75) with an EP-centered test.  The key components are:

- Flex toolbar with a menu button
- Menu button has `attachToBody: true`
- Menu button also has an AJAX call for population
- There are triggers for reloading both the Popupmenu and the entire Flex Toolbar

I'm not able to reproduce this on the EP side only.  Most likely it's coming from NG or some kind of race condition in Landmark.  I'll continue testing against @Sovia's environment.

**Comment by Sovia** [comment]
@EdwardCoyle and I have now replicated this in EP. It's seems to be related to removeOnDestroy being set on the popupmenu, which in conjunction with updated getting called on the flex toolbar is deleting the menu reference.

**Comment by EdwardCoyle** [comment]
Including in this issue:
- [ ] tests surrounding the `removeOnDestroy` setting (there are currently none)

**Comment by janahintal** [comment]
http://4210-beta1-enterprise.demo.design.infor.com/components/popupmenu/test-flex-toolbar.html has error. 
 
Steps:
1. Click Destroy Menu button 
2. Click Trigger updated() on Menu Button Only

![image](https://user-images.githubusercontent.com/45757016/64225541-65726b80-cf0e-11e9-82c1-041e1e47db7c.png)

**Comment by brianjuan** [comment]
http://4210-beta2-enterprise.demo.design.infor.com/components/popupmenu/test-flex-toolbar.html
Passed QA in all browsers, there's also no error in the console.
