### ISSUE TITLE
DataGrid: when 'isFiltered' column is used datagrid shows no data as it gets filtered out

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#2668]
**Describe the bug**
When 'isFiltered' column is used datagrid shows no data

**To Reproduce**
1. Go to demo app
2. In datagrid-paging-data.ts in PAGING_COLUMNS change definition of any column id property to 'isFiltered'.
3. Change also the property name in PAGING_DATA
4. Run app and check the error on web (for example in fixed header datagrid)

**Expected behavior**
isFiltered could be used.

**Version**
- ids-enterprise-ng: 5.3.0

**Additional context**
When there is no column id isFiltered, but search field is used to filter data, then property isFiltered with boolean values is exported by using exportToCsv.

**Comment by hohnzy** [comment]
Our columns are dynamic, they come from different sources.
Actually I think this design is really unhappy. _isFiltered is not a solution. I would say we must be sure that the data wont collide and that the export to csv also wont be affected.

**Comment by tmcconechy** [comment]
Yeah i do agree but thats the way it was done. But should be improved. As i said this is a bigger refactor.

**Comment by hohnzy** [comment]
Workaround: copy the data for grid into new property used as dataset. Do prefix id names with unique string and use original data for exporting into csv.

**Comment by Rottosson** [comment]
We experienced a problem with data that had been filtered in one grid became filtered in a different one because of the flag being brought along.
Can't you wrap the data and add the flagg isFiltered to the wrapped object?

**Comment by tmcconechy** [comment]
We could put the filtered rows in another array maybe but this is a substantial change.

**Comment by hohnzy** [comment]
Cant you just do something like `dataSet.filter((row) => {...})` for what to show?

**Comment by tmcconechy** [comment]
Things like editing would then not work as this would create a new array so the editing would go into the other array. I think the easiest solution is for us to use something other than `isFiltered` that's more unique like `_datagridFilter`. We have a lot of features in the datagrid that are connected.

**Comment by tmcconechy** [comment]
I looked at this a bit and i think maybe i can just do away with the need for isFiltered entirely. I'll take a deeper look next sprint.

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to QA failed due to alignment issue on the uplift theme in the data grid: http://localhost:4000/components/datagrid/example-filter.html?theme=uplift&variant=light
 Please see screen shot below. 

![Alignment issue for Activity](https://user-images.githubusercontent.com/39101346/73972054-1d58da00-48ee-11ea-9c86-c70d845ddf26.png)

**Comment by tmcconechy** [comment]
@CindyMercadoReyes i dont think that failed QA belongs here. Lets just make a new issue. Also i couldnt reproduce it . So maybe new steps are needed or you are zooming?

http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift&variant=light

![Screen Shot 2020-02-06 at 2 43 15 PM](https://user-images.githubusercontent.com/814283/73972565-0a92d500-48ef-11ea-89bd-de709ec31984.png)

Anyways moving to done, awaiting a new issue with more details
