### ISSUE TITLE
Homepage: chart is not resized on widget resize

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#2669]
**Describe the bug**
Homepage: chart is not resized on widget resize.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/homepage/example-filled
2. Resize the page, so the widget size changes automatically.
3. Observe, that chart is not resized.
4. When you resize now (the way that the widget doesnt change size) the chart gets resized. Maybe some other event is taking time (animation?) so the calculation of chart width is faster?

**Expected behavior**
Chart should resize on first hit.

**Version**
- ids-enterprise: 4.20.0

**Screenshots**
![image](https://user-images.githubusercontent.com/11279863/63354040-02a4a000-c364-11e9-8138-8a42405753aa.png)

**Comment by hohnzy** [comment]
Hi, how does it look with this one?

**Comment by tmcconechy** [comment]
We havent had time (backlog about 500 items). I can put it in next sprint if its important.

**Comment by brianjuan** [comment]
Passed QA in master in all browsers. Tested in https://master-enterprise.demo.design.infor.com/components/homepage/example-filled using all variants and themes as well. Will retest once beta is deployed.
