### ISSUE TITLE
SOHO-7494: Multiselect using ajax missing expected search term behavior

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#267]
### Original ticket via @pilotbob: [SOHO-7494](https://jira.infor.com/browse/SOHO-7494)

When implementing the Multilist using ajax there seemed to be no support for a search term. 

You can observe the following when accessing the sample at http://usalvlhlpool1.infor.com/4.3.4/components/multiselect/example-ajax

There appears to be no passing of a typed in search value to the source function or endpoint. Example text implies it will be passed as "term", or the second parameter passed to the source callback function. 

The page implies that a search term is sent with the ajax request but I’m not seeing that.
 
When I tab into the control the first letter I type causes it to drop down, make the ajax request without a term. 
 
Also, once I select one item, I can’t see a way to type in a second item.
 
I am expecting to be able to type in a “new” item and have it make an ajax request to get matching items that they can select from. Is that not possible?
 
I can only make it work by returning the full dataset and then it does searching client side. It also makes the ajax call every time I open the control. I’ve found I can specify the endpoint in data-source as well it calls it every time I open the dropdown.

Unable to type in a second value once an initial value has been typed.

Expected behavior... 

The ability to type into the text box and on change a call is made to the calldback function or to the endpoint (specified in data-source) passing the typed in value. It also would be nice to specify how many letters must be typed before a call to the remote endpoint is made, but that can of course be done in the callback function. 

The ability to type in an additional item. While I was able to type in the first item I was only able to enter multiple items using the mouse and selecting items in the drop down. (not specific to AJAX usage)

The ability to delete a single item, similar to how you can do that in the Jira multiselect. See the affects versions multiselect above. (not specific to AJAX usage)

**Comment by brianjuan** [comment]
Bug fix is working as expected and passed QA testing.

Environment: http://490-beta0-sohoxi.demo.design.infor.com/components/multiselect/test-reload-typeahead.html
![image](https://user-images.githubusercontent.com/39508864/42930354-57863256-8b6f-11e8-8b52-1387448cfe09.png)
