### ISSUE TITLE
Homepage: chart height is not calculated properly when other elements are used in widget

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#2670]
**Describe the bug**
Homepage: chart height is not calculated properly when other elements are used in widget

**To Reproduce**
1. Add some banner (div) to the widget with chart https://design.infor.com/code/ids-enterprise/latest/demo/components/homepage/example-filled
2. Observe that the height of the chart is still 288px like there is nothing else.

**Expected behavior**
The chart should fit into smaller height.

**Version**
- ids-enterprise: 4.20.0

**Screenshots**
![image](https://user-images.githubusercontent.com/11279863/63355385-52846680-c366-11e9-886e-4fcb7666528c.png)
![image](https://user-images.githubusercontent.com/11279863/63355487-7cd62400-c366-11e9-8e5d-370f745602ed.png)

**Comment by hohnzy** [comment]
The same issue also in bar chart.

**Comment by hohnzy** [comment]
If I wrap inside another div with height set, the chart is sized properly. But I would say this wrapper should be already in a library when its needed for correct behavior.

**Comment by tmcconechy** [comment]
The fix here (for whoever gets this) is to set the height of the content container when there is a toolbar differently. Then test with a chart and make an example

**Comment by janahintal** [comment]
Hi, noticed that the https://master-enterprise.demo.design.infor.com/components/line/test-fit-height.html?theme=soho&variant=light still has a scroll bar in the widget. Other example pages are now working as expected. Thank you. 


![image](https://user-images.githubusercontent.com/45757016/82312841-2e8ba980-99fa-11ea-8242-2a7a20be0864.png)

**Comment by tmcconechy** [comment]
@deep7102 we had this conversation on the issue PR. Maybe we can just change the data on this one to shorter legend items so it fits and do 2 lines only if needed. The scrollbar on its own isnt wrong.

**Comment by janahintal** [comment]
Failed QA in uplift theme. There is still a scroll bar in Uplift theme. 

https://master-enterprise.demo.design.infor.com/components/line/example-axis-ticks.html?theme=uplift&variant=light&colors=0066D4

![image](https://user-images.githubusercontent.com/45757016/82659651-9b51ae80-9c5b-11ea-8646-20157d0a7e1c.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
