### ISSUE TITLE
Homepage: chart y axis description is not visible when widget width is 1 unit

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#2674]
**Describe the bug**
Chart y axis description is not visible when widget width is 1 unit (360px). See screenshots. Something wrong in transform: translate(), like 62 for x translate seems more accurate.

**To Reproduce**
1. Enter longer strings for y axis values in https://design.infor.com/code/ids-enterprise/latest/demo/components/homepage/example-filled

**Expected behavior**
Should be aligned properly and y axis labels should be visible

**Version**
4.20.0

**Screenshots**
![image](https://user-images.githubusercontent.com/11279863/63420038-30dabc00-c406-11e9-8d03-bd989d9c623d.png)
![image](https://user-images.githubusercontent.com/11279863/63419965-0983ef00-c406-11e9-8c51-d571b8a7f732.png)

**Comment by hohnzy** [comment]
Also when the widget is wider its a bit off, but at least visible:
![image](https://user-images.githubusercontent.com/11279863/63420459-00dfe880-c407-11e9-91d4-bd7f3aec619b.png)

**Comment by tmcconechy** [comment]
For this case you will have to set the number of ticks https://github.com/infor-design/enterprise/blob/master/app/views/components/line/test-axis-y-formate-integer.html#L47 or the tick format https://github.com/infor-design/enterprise/blob/master/app/views/components/line/test-axis-y-formate-shortened.html#L39

https://github.com/infor-design/enterprise/blob/master/app/views/components/line/test-axis-ticks-date-range.html#L146

If it doesnt fit - it wont fit automatically. You can just set the number of ticks to less so less values show or use shorter labels.

**Comment by tmcconechy** [comment]
Might eventually just close this issue as wont fix but i think we can adjust the height of the widget a bit better. Your other choice is to use a 2 width chart section for this chart

**Comment by hohnzy** [comment]
I think this is just bug with wrong translate value on the first <g> under <svg> element...
Can't show less values as it is top 10 chart, also can't use shorter labels in this use case.

![PYkV0280XE](https://user-images.githubusercontent.com/11279863/72836319-9e786600-3c8c-11ea-9467-03afc2d83770.gif)

**Comment by tmcconechy** [comment]
Do you see something you can prepare a Pull Request for?

**Comment by hohnzy** [comment]
Not really... :( i dont understand how the constant 6 was computed. That means that the average character is 6 pixels wide?
https://github.com/infor-design/enterprise/blob/e76e0c17490022c8cf7ebabdca81127bb7a1db3c/src/components/bar/bar.js#L240
Looks like this line is always triggered when the component is used by angular SohoBarComponent as it does not have longText defined in SohoBarOptions interface in soho-bar.d.ts :(

Also I dont understand where is innerWidth set, so the small, medium, large viewport can be set?
https://github.com/infor-design/enterprise/blob/e76e0c17490022c8cf7ebabdca81127bb7a1db3c/src/components/bar/bar.js#L141

**Comment by tmcconechy** [comment]
Ok this may be a little easier than I thought tho. @deep7102 can you answer those questions? I think the six was maybe approx size of a character? But we can schedule for next sprint and review further

**Comment by deep7102** [comment]
Yes, its
- `6` is approximate character size.
- `innerWidth` is global window variable set by browser it is most of the time written as `window.innerWidth`.

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. Thanks
Verified in https://master-enterprise.demo.design.infor.com/components/homepage/test-linechart-x-axis.html

**Comment by hohnzy** [comment]
just read the description :( how can this pass through QA?

**Comment by tmcconechy** [comment]
The super long Y axis wasnt entirely clear to me - sorry. Try and make a new issue for that case and i'll escalate it. Again not sure there is a fix. Also your welcome to test the PR when you see it being added to the issue

**Comment by tmcconechy** [comment]
I'll make a new issue and cc you on it since we missed that part. Coming soon

**Comment by hohnzy** [comment]
I dont think new issue is needed. This just shouldn't be closed. Its described clearly and the title is **y axis**
you can see in https://github.com/infor-design/enterprise/issues/2674#issuecomment-576842631 picture where the bug is.

**Comment by tmcconechy** [comment]
I need a new issue to make sure its clearer. I will make it then. If you read the first part of the issue that comment wasnt mentioned at all (very clearly anyways). So thats probably why this got missed. That was buried in there. Also i want to discuss how we might fix it as im not sure how. So for those reasons will make a new issue

**Comment by hohnzy** [comment]
you can reproduce in ng demo, file bar.demo.ts change the barData
```
 public barData = [{
    data: [{
      name: 'Category AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
      value: 373,
      url: 'test'
      }, {
        name: 'Category B',
        value: 372
      }, {
        name: 'Category C',
        value: 236.35
    }],
    name: ''
  }];
```
and observe here http://localhost:4200/ids-enterprise-ng-demo/bar

**Comment by tmcconechy** [comment]
And another thing - the original issue is a line chart this is a bar chart no.? Anyways here is the new issue. https://github.com/infor-design/enterprise/issues/3702 Can we discuss the details of that over there - especially worth discussing what a good fix for that would be.

Again: I feel like the original issue was unclear about this point. But sorry for missing that point.
New Issue i tried to make the point abundantly clear. Now we need to discuss over there what a reasonable fix would be. I made a suggestion there and CC you.
