### ISSUE TITLE
Datagrid issue - hidePagerOnOnePage & filter change not working correctly

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise#2676]
**Describe the bug**
We're seeing this in our angular app but I'm confident that it's an enterprise issue. Applies to a datagrid that has paging and filtering enabled and is using hidePagerOnOnePage = true. If you enter a value into the filter that results in less than one page of results, the pager control disappears which is what you would expect. The issue is, when you subsequently clear out the filter value, causing more than one page of rows to be the result, the pager does not re-appear. 

**To Reproduce**
1. Setup a paging and filtering enabled datagrid and option hidePagerOnOnePage=true.
2. Display the grid, initially with more than one page of rows.
3. Note the paging control appears at the bottom of the grid, 'Page 1 of XX'.
4. Enter a column filter value that results in < one page or rows.
5. Note that the paging control disappears - this is expected.
6. Clear out the filter value entered in step 4.
7. Note the paging control does not re-appear.

**Expected behavior**
The paging control should appear/disappear based on the current rows displayed count.

**Version**
IDS-NG 5.5.1
IDS-Enterprise 4.16.2

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 76.0.3809.100

**Comment by tmcconechy** [comment]
Yes, this can be reproduced in EP by
- modify 
- so that there is one filter column and and change some settings:
```
columns.push({ id: 'id', name: 'Id', filterType: 'text', field: 'id', formatter: Formatters.Text});
...
filterable: true,
hidePagerOnOnePage: true,
```
- follow the steps above

**Comment by jbrcna** [comment]
**QA PASSED**
Verified in http://master-enterprise.demo.design.infor.com/components/datagrid/test-hide-pager-if-one-page-filter.html across all browsers and devices. moving this to Done
