### ISSUE TITLE
Editor: Bullet / numbered list item can't be turned into H3/H4

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#2679]
**Describe the bug**
This is a minor issue. A bullet / numbered list item can't be turned into H3/H4. The style does look like it gets applied, since the buttons get active, but it remains a list item. Only seems to be an issue in Chrome & Safari.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index
2. Type something
3. Turn text into bullet / number list
4. Turn into H3/H4
**Result**: Not turned into H3/H4

**Expected behavior**
Turned into H3/H4

**Version**
- ids-enterprise: 4.20.0

**Platform**
 - Browser: Chrome / Safari

**Comment by tmcconechy** [comment]
Probably have to remove the button/number markup first and then turn it into a H3. Would make for a wierd H3 text. Probably not the straight forward

**Comment by volante007** [comment]
Yeah, in IE11/Edge, it transforms into h3/h4. But as you say, works fine if removing list styling first :)

**Comment by tmcconechy** [comment]
Actually made thats an answer - if bullet or number list, call removeMarkup (like the button does) then apply H3, H4

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
