### ISSUE TITLE
Tabs: Closing a tab causes a memory leak

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#2686]
**Describe the bug**
The tabs control has memory leaks when a tab is removed by clicking its X button. Details are below. These memory leaks can build up over time in a SPA and cause the browser window to slow down and crash.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html
2. Open the Memory tab in Chrome Developer Tools
3. Click the 'Collect garbage' button to remove any clutter
4. Click the 'Take snapshot' button to get a comparison point of the memory heap
5. Click the '+' button to add a new tab
6. Click the 'X' button for that tab to close it
7. Click the 'Collect garbage' button again
8. Click the 'Take snapshot' button to get another memory heap.
9. While looking at "Snapshot 2" change the dropdown which says "All objects" to "Objects allocated between Snapshot 1 and Snapshot 2" (this will help you see what is hanging around in memory due to the new tab being added and removed)
10. Look at the results in the list to see what the tab left hanging around in memory. For example there is a Detached HTMLDivElement and HTMLAnchorElement (see items in screenshot below)

**Expected behavior**
The closed tab should not leave its DOM elements in memory. The below line of code in tabs.js is the culprit.

`
if (hasTargetPanel) {
  this.panels = this.panels.not(targetPanel);
}
this.anchors = this.anchors.not(targetAnchor);
`

This article describes how using variables and jQuery filters can cause big memory leaks due to the "prevObject" reference in jQuery objects - https://blog.yonatan.dev/jquery-prevobject-memory-leak/ - They recommend creating new references using the $() wrapper like this...

`
if (hasTargetPanel) {
  this.panels = $(this.panels.not(targetPanel));
}
this.anchors = $(this.anchors.not(targetAnchor));
`

**Version**
- ids-enterprise: v4.20.0

**Screenshots**
![image](https://user-images.githubusercontent.com/14128010/63592386-7bcc0f00-c57f-11e9-9473-9668cbf2363b.png)

**Platform**
 - Device: Dell Laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 76.0.3809.100 (Official Build) (64-bit)

**Comment by janahintal** [comment]
QA Passed. 
Verified in http://4210-beta1-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html thanks!
