### ISSUE TITLE
Complete Searchfield integration with Flex Toolbar

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#269]
**Is your feature request related to a problem? Please describe.**

Flex Toolbar has basic support for barebones Searchfields, but it's support isn't currently 1-to-1 with the regular Toolbar.  We should complete the basic Searchfield handling of the Toolbar, and make sure that all alternates/contexts for the regular Toolbar in other components will work properly if a Flex Toolbar is used in its place.

**Describe the solution you'd like**

We'd need to add the following support to Flex Toolbar:

- [x] Responsive view for Searchfields inside the Flex Toolbar (making the `.toolbar-section.searchfield` expand and hide everything else on mobile views)
- [x] Smooth out the display of Collapsible Searchfields:
  - [x] on mobile views, hide Searchfields that are "collapsibleOnMobile" or "collapsible" behind a button if they aren't active.
  - [x] automatically expand the `.toolbar-section.buttonset` on desktop/larger views if the searchfield has focus.

Additionally, will fix some codepaths in these components that are specific to the regular toolbar, so that they can also support the alternate markup in the Flex Toolbar (f.x., `.toolbar-section` is an element that won't do anything in a regular Toolbar, but is integral to the function of Flex Toolbar.  We could use the class to define sections in both)

**Comment by EdwardCoyle** [comment]
Scoped the part of this issue dealing with integration into larger components to #1120.  Going to pick the remaining part of this one up for the November sprint

**Comment by EdwardCoyle** [comment]
Possibly looking at adding a piece of functionality to the Searchfield itself to make the responsive experience better:

- [ ] Create a responsive-only (collapse) button for the Flex Toolbar Searchfield
  - Only shows up on Responsive view (but exists all the time)
  - CSS hides it by default, prevents tabIndex by default.  In responsive view, it's focusable.
  - Clicking/Keying "Enter" on this button collapses the Searchfield and selects the next element on the toolbar.

**Comment by EdwardCoyle** [comment]
Some of the above requires some async code to deal with focus traps... looking at adopting a promise polyfill in #1172 so we can actually use promises instead of jQuery deferreds for this

**Comment by CindyMercadoReyes** [comment]
Hi @EdwardCoyle I'm moving this ticket to the Failed QA folder due to the toast not appearing for Win 10 IE 11 for URL: http://4130-beta0-enterprise.demo.design.infor.com/components/toolbar-flex/example-index.html#
When I click on toolbar title the toast doesn't appear. It also doesn't appear when I click on the trash can icon.  Please see screen shot attached.  

![bs_win10_ie_11 0 3](https://user-images.githubusercontent.com/39101346/48783173-bf6eb100-ecad-11e8-8756-64ddabe65d08.jpg)

**Comment by tmcconechy** [comment]
Maybe we dont need toasts in the example.

**Comment by tmcconechy** [comment]
Closed via #1252 and other PRs on this issue

**Comment by brianjuan** [comment]
https://4130-rc0-enterprise.demo.design.infor.com/components/toolbar-flex/example-index
Passed QA testing on all browsers, moving to Done.
