### ISSUE TITLE
Tabs: If info icon is used rather than error icon , it is misaligned

### ISSUE THREAD

**Issue by jeffuycoque** [infor-design/enterprise#2695]
**Describe the bug**
On our application, if there is a field that has an info message, the tab would have an info icon right next to it. However the info icon is misaligned when it is rendered 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/tabs/test-modal-error.html
2. Click Add Context
3. Trigger Validation By inputting a blank value on Last Name Field
4. Right Click Error Icon on the Tab and Click Inspect
![image](https://user-images.githubusercontent.com/49975141/63737964-c10f7a00-c8ba-11e9-8d72-7fb99bdfb83d.png)
5. Change icon-error to icon-info
icon-error:
![image](https://user-images.githubusercontent.com/49975141/63737995-e2706600-c8ba-11e9-87f7-ce62b7fe25bc.png)

icon-info
![image](https://user-images.githubusercontent.com/49975141/63738046-121f6e00-c8bb-11e9-8d3e-5d3d9b207b60.png)

**Expected behavior:**
Info Icon would be aligned

**Actual behavior:**
![image](https://user-images.githubusercontent.com/49975141/63738017-fcaa4400-c8ba-11e9-8b52-186529e85250.png)

It seems that the info and error icons have different sizes, the error icon seems to be a little smaller which may be the reason why the issue is not reproducible when tab has an error.

Platform
OS Version: Windows 10
Browser Name: Google Chrome

**Comment by jeffuycoque** [comment]
@tmcconechy this is also reproducible using alert icon
![image](https://user-images.githubusercontent.com/49975141/64302145-94431d00-cfb4-11e9-898a-28e56e09e6d2.png)

![image](https://user-images.githubusercontent.com/49975141/64302173-ad4bce00-cfb4-11e9-920c-bd2e4b03185e.png)

**Comment by jbrcna** [comment]
**QA Passed**
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/tabs/test-modal-error.html

![image](https://user-images.githubusercontent.com/56722184/81406314-e9e74f00-916b-11ea-9fb5-d4af44065f2a.png)
