### ISSUE TITLE
Locale: Leading 0 Removed from SSS in dates

### ISSUE THREAD

**Issue by kenneth-acejo** [infor-design/enterprise#2696]
**Describe the bug**
Using the following on setting SohoDataGridColumn[]
dateFormat: 'yyyy-MM-ddTHH:mm:ss.SSS'
formatter: Soho.Formatters.Date

The millis seems to remove a leading zero when the value is less than 100.
Example: 
* 2015-01-01T06:00:00.123Z
  * actual 2015-01-01T14:00:00.123
  * expected 2015-01-01T14:00:00.123 -> correct

* 2015-01-02T06:00:00.120Z
  * actual 2015-01-02T14:00:00.120
  * expected 2015-01-02T14:00:00.120 -> correct

* 2015-01-03T06:00:00.012Z
  * actual 2015-01-03T14:00:00.12
  * expected 2015-01-01T14:00:00.012

* 2015-01-04T06:00:00.100Z
  * actual 2015-01-04T14:00:00.100
  * expected 2015-01-01T14:00:00.100 -> correct

* 2015-01-05T06:00:00.010Z
  * actual 2015-01-05T14:00:00.10
  * expected 2015-01-01T14:00:00.010

* 2015-01-06T06:00:00.001Z
  * actual 2015-01-06T14:00:00.1
  * expected 2015-01-01T14:00:00.001

**Version**
- ids-enterprise-ng: 5.4.0

![sohocodebug](https://user-images.githubusercontent.com/17284784/63770907-c3002a00-c908-11e9-999a-b3accbd2dd6c.PNG)
![sohopagebug](https://user-images.githubusercontent.com/17284784/63770912-c693b100-c908-11e9-9392-469753dbb9b5.PNG)

**Additional context**
I edited the demo enterprise-ng / datagrid / datagrid-paging-data.ts

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
