### ISSUE TITLE
Charts: Inconsistent context menu events in charts

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#2699]
**Describe the bug**

 Bar and Pie/Donut throw a contextmenu event with 3 params including ui and data. We need all the charts to throw the same event so we can grab the index of the element that caused the event to be throw. Using the index we can have the context menu to show for the chart element clicked on.

```
column:  self.element, d3.select(this).nodes()[0], d
pie: self.element, d3.select(this).select('path').nodes()[0], d
bar: (dont see any event at all)
line: (dont see any event at all)
line: (dont see any event at all)
bubble: (dont see any event at all)
radar: (dont see any event at all)
scatter: (dont see any event at all)
```

**To Reproduce**
1. We need to construct an example of a right click menu on all chart elements that uses contextmenu and surfaces a menu

**Expected behavior**
All Chart need to throw a consistent event when a chart element is clicked on for a context menu. 

**Version**
- ids-enterprise: [e.g. v4.21.x]

**Platform**
 - N/A

**Comment by brianjuan** [comment]
Tested all the pages in the PR, context menu events are firing in console and there are no errors. 

However, on the pages below, there are errors in the console when a legend is clicked. Not sure if these errors are related to context menu implementation.
http://master-enterprise.demo.design.infor.com/components/column-grouped/example-contextmenu.html
http://master-enterprise.demo.design.infor.com/components/column-stacked/example-contextmenu.html
http://master-enterprise.demo.design.infor.com/components/donut/example-contextmenu.html
http://master-enterprise.demo.design.infor.com/components/line/example-contextmenu.html
http://master-enterprise.demo.design.infor.com/components/pie/example-contextmenu.html
http://master-enterprise.demo.design.infor.com/components/radar/example-contextmenu.html
![chart-error](https://user-images.githubusercontent.com/39508864/65870091-0d644300-e3ae-11e9-86e8-0ea4a42a76f1.jpg)

**Comment by brianjuan** [comment]
Passed QA in all browsers, moving to Done.
