### ISSUE TITLE
Unselectable item with badge in the Dropdown

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#270]
**Describe the bug**
Unselectable item with badge in the Dropdown.

**To Reproduce**
1. Go to url: http://480-beta0-sohoxi.demo.design.infor.com/components/dropdown/test-badges.html
2. Click the Dropdown to open
3. Try to select the last item with badge but doesn't have text'
4. See screen shot
<img width="1279" alt="dropdown badges" src="https://user-images.githubusercontent.com/39101346/41868542-59ae9c92-7884-11e8-9656-9f936b16eeaa.png">
<img width="1279" alt="dropdown badges" src="https://user-images.githubusercontent.com/39101346/41868548-5d5e6be2-7884-11e8-86a4-42e32adf8479.png">

**Expected behavior**
badge should appear.

**Screenshots**

**Platform**
 -
 - All Browsers 
 
**Additional context**

**Comment by brianjuan** [comment]
Bug fix is working as expected across all browsers and passed QA testing.

Environment: http://490-beta0-sohoxi.demo.design.infor.com/components/dropdown/test-badges.html
<img width="612" alt="screen shot 2018-07-19 at 4 52 44 pm" src="https://user-images.githubusercontent.com/39508864/42932258-684bd7b2-8b74-11e8-861e-8335164c922d.png">

**Comment by tmcconechy** [comment]
This issue should have been closed.
