### ISSUE TITLE
DataGrid: Cells supporting multi-line (word wrap) values vertically align single row data incorrectly

### ISSUE THREAD

**Issue by pvasys** [infor-design/enterprise#2703]
**Describe the bug**
Using the following example for multi-line support:
https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-comments

The column supporting multi-line data uses a span with the class "datagrid-multiline-text".  While multi-line values look good, if there is single-row data, it appears to be misaligned relative to other cells on the row without the datagrid-multiline-text span.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-comments
2. Look at the lines with a single line.

**Version**
- ids-enterprise: [e.g. v4.20.1]

**Screenshots**

![datagrid_multiline_single_line_vertical_alignment](https://user-images.githubusercontent.com/7040513/63870992-0d28f000-c989-11e9-8a17-665493806148.png)

**Platform**
 - Chrome (mac or windows) or any

**Additional context**
This may belong in the css project - I don't know the source of the issue.

**Comment by janahintal** [comment]
This issue is now resolved. Tested in Master will retest when beta is released. Thank you.
![image](https://user-images.githubusercontent.com/45757016/81401371-c1f2ee00-9161-11ea-8aa4-029c4e2a964a.png)
