### ISSUE TITLE
Datepicker: Add a setting for hiding the "Today" button

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#2704]
**Is your feature request related to a problem? Please describe.**
Per @kevinwhitedesign's comment on #2541:

![63724189-30d32580-c825-11e9-8858-98d000f5d710](https://user-images.githubusercontent.com/3249601/63889420-fb5a4380-c9ae-11e9-9fff-dad97c6db409.png)

> This 'today' button doesn't seem to be all that useful in this 'set as of date' context. In general, it's one too many actions. If it's auto selecting today's date, then the less common experience would be that someone chooses another and then comes back and selects today's date. This popover is not taking a stand and it's providing all the possible actions. Which, may be more confusing + inefficient for normal usage than for the edge case. Terminology should be cancel and then apply, I'll have Julie Briggs, our ux copy writer shed some light here.

**Describe the solution you'd like**
This button has been present in the Datepicker for some time, so we can't outright remove it.  
- [x] Provide a setting for hiding the "Today" button (maybe called `todayButton`), defaulted to `false`.
- [x] Add functional tests for the new setting.
- [x] Document new setting.
- [x] Do we want to deprecate the old way?  If so, need deprecation warnings.

**Comment by tmcconechy** [comment]
Another way to do this is to put the today button as a link on the top toolbar, similar to:

![Screen Shot 2019-09-03 at 9 19 12 AM](https://user-images.githubusercontent.com/814283/64176677-ee64a680-ce2b-11e9-9916-725d81c3fe57.png)

Thinking i like this the best.

**Comment by brianjuan** [comment]
Functionality of "Today" is working as expected. I just found some minor layout issues in **IE**.
http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html
![image](https://user-images.githubusercontent.com/39508864/65864844-23213a80-e3a5-11e9-998a-ff5d17be8c30.png)

http://master-enterprise.demo.design.infor.com/components/monthview/example-index.html
![image](https://user-images.githubusercontent.com/39508864/65864970-4946da80-e3a5-11e9-93bb-042f2afd849e.png)

**Comment by tmcconechy** [comment]
This is essentially the same problem as https://github.com/infor-design/enterprise/issues/2713 working on a fix for those two issues

**Comment by tmcconechy** [comment]
This is mentioned on https://github.com/infor-design/enterprise/issues/2862 so just moving to done.
