### ISSUE TITLE
Calendar: Create a 'Select All' checkbox on the legend

### ISSUE THREAD

**Issue by rowelineeveresurreccion** [infor-design/enterprise#2706]
**Is your feature request related to a problem? Please describe.**

We have a lot of legend items, so would suggest a select all/deselect all on the legend of teh calender.

http://master-enterprise.demo.design.infor.com/components/calendar/example-only-calendar-legend.html

**Describe the solution you'd like**
Please add a select all/deselect all action to the legend.

**Describe alternatives you've considered**
Not having a select all/deselect all.

**Additional context**

To enhance user experience on web since the options under Legend (in this case, the list of Resources) are maintainable, meaning the list could have one or more items (in the sample screen shot, there are a total of 20 items, but the list could go more than 20). 

Selecting and deselecting of resource items will be used quite often on calendar control, especially if a user just wants to view a single resource Item's booking schedule.  With this enhancement, the user will save time from doing redundant action of selecting and deselecting items one by one and just click a single checkbox to deselect or select all items.

**Comment by tmcconechy** [comment]
Descoping this issue as we havent had time for it. However for the 5.0 calendar will make the legend area an open slot where you can put what you like in it
