### ISSUE TITLE
Datagrid inline filter date icon disappear when the row height is set to "Medium"

### ISSUE THREAD

**Issue by shane-infor** [infor-design/enterprise#2709]
**Description**
We noticed that the datagrid inline filter date icon is not showing up after we upgraded to 5.5.2. 
http://latest-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
Please set the "Row Height" option to "Medium".

**Expected behavior**
Date icon show appear regardless of the row height.

**Version**
- ids-enterprise-ng 5.5.2

**Screenshots**
Working:
![image](https://user-images.githubusercontent.com/54695843/63989726-c5d76680-cb24-11e9-8be0-f7a4be666e82.png)

Not working:
![image](https://user-images.githubusercontent.com/54695843/63989736-cf60ce80-cb24-11e9-955c-a0d690aefc6d.png)

**Comment by janahintal** [comment]
QA Failed. Filter in http://4210-beta1-enterprise.demo.design.infor.com/components/datagrid/test-editable-time has error
http://4210-beta1-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
http://4210-beta1-enterprise.demo.design.infor.com/components/datagrid/test-filter-short-rowheight
http://4210-beta1-enterprise.demo.design.infor.com/components/datagrid/test-filter-medium-rowheight


1. Click the time filter 
2. List of filter will show up
3.  Select any Filter and Click again the filter button


Please see error below

![image](https://user-images.githubusercontent.com/45757016/64222637-6d78de00-cf03-11e9-8d7c-ed78b9647c75.png)

**Comment by brianjuan** [comment]
http://4210-beta2-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
http://4210-beta2-enterprise.demo.design.infor.com/components/datagrid/test-editable-time
http://4210-beta2-enterprise.demo.design.infor.com/components/datagrid/test-filter-short-rowheight
http://4210-beta2-enterprise.demo.design.infor.com/components/datagrid/test-filter-medium-rowheight
These pages passed QA in Soho theme, datepicker icon is not disappearing regardless of selected row height. And filter is not causing the datagrid to break.

But in uplift theme, datepicker icon is disappearing in Medium row height
http://4210-beta2-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift
![image](https://user-images.githubusercontent.com/39508864/64694794-28d5df80-d4cd-11e9-9f72-b51cbffb5179.png)

**Comment by janahintal** [comment]
QA Failed. http://4210-beta3-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift&variant=dark&colors=0053B1 
Hi @tmcastro, the calendar icon is now visible in row height medium. However, in normal height, the timepicker field is too close to the grid both in uplift and soho theme. Please see image below. 


![image](https://user-images.githubusercontent.com/45757016/64751215-13ed6080-d54e-11e9-93a6-8dddb9784e21.png)

**Comment by janahintal** [comment]
QA Passed. Datepicker is now visible in the grid for both Soho and Uplift theme in Medium row height. Thanks.
