### ISSUE TITLE
RTL: Datagrid expandable row icon is misplaced

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#2710]
**Describe the bug**
When using a datagrid with an expandable row, the + icon is placed to far to the left. I've noticed that it has a left: -10 in the ".datagrid-expand-btn" class that is still there in RTL mode. In the samples this isn't so easy to spot, but in Homepages we have a column with only a + icon button centered in the middle of the column. And then it is very easy to spot the issue.

**To Reproduce**
1. Go to http://latest-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row.html?locale=ar-sa
2. Open a new browser window and look in http://latest-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row.html 
3. Note the different margins to the border next to the + icon

**Expected behavior**
The icon should be placed with the same distance to the outer border in both RTL and LTR

**Version**
4.20.1

**Screenshots**
RTL:
![image](https://user-images.githubusercontent.com/8664975/64028143-64be8b80-cb42-11e9-9f8f-afd0a7c5cfa7.png)

LTR:
![image](https://user-images.githubusercontent.com/8664975/64028194-7d2ea600-cb42-11e9-96b6-81f67b1292a3.png)

**Platform**
 - OS Version:  Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 76.0.3809.132 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
![Screen Shot 2020-02-07 at 3 35 19 PM](https://user-images.githubusercontent.com/814283/74063899-78a6cd00-49bf-11ea-8ad9-5debd0a150f4.png)

Testing this on 4.26 it appears it was fixed along the way. Adding to QA to verify.

**Comment by janahintal** [comment]
QA Passed. 
Verified in http://master-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row.html?theme=uplift&variant=light&locale=ar-sa
http://master-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row.html across all platform
