### ISSUE TITLE
Datepicker: Not enough space for translations of buttons and incorrect translation in Swedish

### ISSUE THREAD

**Issue by karinpb** [infor-design/enterprise#2713]
**Describe the bug**
There is very little room for translations in the date picker dialog.
Also in Swedish the "Select" is translated as "Markera", although not visible enough as the text has overflow indication and no extra tooltip. The meaning of the translation would be "mark" in English. In Swedish a more suitable translation for this scenario is "Välj". The term select might be translated to Markera, but it does not make sense in this context. The date is already marked in the dialog so OK would have been better. Or an extra language constant for selectAsOK?

Ok is easier to translate than Select.

**To Reproduce**

**Expected behavior**
Change the Swedish translation for this dialog to "Välj".
Add more margins to the dialog so that there is more room for the text on the buttons.

**Version**
v4.20.1

**Screenshots**

![image](https://user-images.githubusercontent.com/7961438/64170148-bd966880-ce4f-11e9-9d73-dfa61fd79d47.png)

**Comment by tmcconechy** [comment]
This relates to https://github.com/infor-design/enterprise/issues/2704
We are thinking of removing the today button, which will help this case. Or removing it by default with a setting. You can also hit T to go to today.

**Comment by janahintal** [comment]
QA Failed. in http://master-enterprise.demo.design.infor.com/components/monthview/example-index.html?theme=uplift&variant=light&colors=0563C2

Fields are not aligned in the calendar header 
Screenshot in IE
![image](https://user-images.githubusercontent.com/45757016/65590566-9568d800-dfbd-11e9-956e-c548d031f873.png)

**Comment by janahintal** [comment]
The today function is working as expected but there seems to be a problem in focusing in Today button in **IE 11**in http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=sv-SE 

![image](https://user-images.githubusercontent.com/45757016/66111337-3a596580-e5fb-11e9-9ee4-e872cddeb002.png)

**Comment by tmcconechy** [comment]
This is mentioned on https://github.com/infor-design/enterprise/issues/2862 so just moving to done.
