### ISSUE TITLE
Datagrid list : Margin is misaligned when in Uplift theme, row height short

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2717]
**Describe the bug**
Datagrid list : Margin is misaligned when in Uplift theme, row height short

**To Reproduce**
1. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/datagrid/example-list.html?theme=uplift&variant=light&colors=0563C2 
2. Set row height to Small
3. Hover to any row.

**Expected behavior**
Row margin should be aligned 

**Version**
Beta Regression 4.21

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/64237363-c742cd80-cf2e-11e9-9d5d-358fade021c0.png)

**Platform**
All browser, OS and devices. 

**Additional context**
None so far

**Comment by tmcconechy** [comment]
For 4.21.x please @deep7102 :)

**Comment by janahintal** [comment]
QA Passed. 
Tested in http://4210-beta3-enterprise.demo.design.infor.com/components/datagrid/example-list.html?theme=soho&variant=light&colors=0563C2 across all browser, OS and devices.
