### ISSUE TITLE
Datagrid: Select all text box is not aligned center both in uplift theme and soho

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2718]
**Describe the bug**
Datagrid: Select all text box is not aligned center 

**To Reproduce**
1. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection-popupmenu.html
2. click Select all in the first grid
3. Change the row height to small

**Expected behavior**
Select all checkbox should be aligned center

**Version**
Beta Regression 4.21

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/64238711-80a2a280-cf31-11e9-9d41-693cf5fc33c3.png)

**Platform**
All OS, Browser and devices

**Additional context**
N/A

**Comment by janahintal** [comment]
QA Passed. 
Verified in http://4210-beta3-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection?theme=uplift&variant=light&colors=0563C2
http://4210-beta3-enterprise.demo.design.infor.com/components//datagrid/example-modal-datagrid.html?theme=uplift&variant=light&colors=0563C2 across all browser, OS and devices. Thanks!

**Comment by brianjuan** [comment]
http://4210-beta3-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection
Still failing in IE.

**Comment by tmcconechy** [comment]
This was fixed in rc build and I didn’t post that yet. Cindy said today we will.

**Comment by brianjuan** [comment]
http://4210-rc0-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection
Passed QA in all browsers including IE.
![image](https://user-images.githubusercontent.com/39508864/64933545-52e62380-d878-11e9-96a5-21933e30e972.png)
