### ISSUE TITLE
Datagrid: select all checkbox in modal grid is misaligned

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2719]
**Describe the bug**
Datagrid: select all checkbox in modal grid is misaligned

**To Reproduce**
1. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/datagrid/example-modal-datagrid.html
http://4210-beta1-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html even all the grid examples that has multiselect
2. Click on 'Open Modal' button

**Expected behavior**
Checkbox fields should be aligned center

**Version**
Regression Beta 4.21

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/64247361-493bf200-cf41-11e9-9244-8590afc17955.png)

**Platform**
All OS, Browser and Devices.

**Additional context**
N/a

**Comment by janahintal** [comment]
Hi, issue still exist in Win 10 IE 11 browser. 
![image](https://user-images.githubusercontent.com/45757016/64760559-9b49cc80-d56c-11e9-9ae4-b7f2a9f0d2f9.png)

**Comment by brianjuan** [comment]
http://4210-beta3-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
http://4210-beta3-enterprise.demo.design.infor.com/components/datagrid/example-modal-datagrid.html
Still failing in IE.

**Comment by tmcconechy** [comment]
This was fixed in rc build and I didn’t post that yet. Cindy said today we will.

**Comment by brianjuan** [comment]
http://4210-rc0-enterprise.demo.design.infor.com/components/datagrid/example-modal-datagrid.html
http://4210-rc0-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
Passed QA in all browsers including IE
![image](https://user-images.githubusercontent.com/39508864/64932504-19aab500-d872-11e9-9f48-bc25d95c9d59.png)
