### ISSUE TITLE
Broken border line on the bottom-right edge of the list

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#272]
**Describe the bug**
Broken border line on the bottom-right edge of the list

**To Reproduce**
1. Go to url: http://480-beta0-sohoxi.demo.design.infor.com/components/listview/example-header-totals.html#
2. Open the page on Chrome
3. Notice the broken border line on the bottom-right edge of the list 

**Expected behavior**
The border should not be cut off. Please see screen shot attached.

**Screenshots**
<img width="1169" alt="listview broken border" src="https://user-images.githubusercontent.com/39101346/41871731-c0c841ae-788d-11e8-8a82-eaa03e8e45f9.png">

**Platform**

 - OS Version: Windows 10  Chrome 67

**Additional context**

**Comment by tmcconechy** [comment]
I noticed its missing a td in the tr in the markdown. Just needs adjusting
