### ISSUE TITLE
Listview: No items on the list

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#273]
**Describe the bug**
No items on the list

**To Reproduce**
1. Go to 'http://480-beta0-sohoxi.demo.design.infor.com/components/listview/test-first-selected.html'
2. Open the page
3. List doesn't have items

**Expected behavior**
The list should have data in it

**Screenshots**
<img width="1294" alt="list view" src="https://user-images.githubusercontent.com/39101346/41872305-73fe9b0a-788f-11e8-9089-0d301a42f2c9.png">

**Platform**

 - All Browsers

**Additional context**

**Comment by brianjuan** [comment]
Bug fix is working as expected across all browsers and passed the QA testing.
See screenshot below.
![image](https://user-images.githubusercontent.com/39508864/42861193-082b810e-8a28-11e8-9aa1-002c372ff4db.png)
