### ISSUE TITLE
Datagrid: Font color makes text difficult to read with TargetedAchievement formatter

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2730]
Describe the bug
Getting push back that the text is difficult to read with the font color being used and that the font color itself is inconsistent when using the TargetedAchievement formatter.

To Reproduce

1. Using the attached test-targeted-achievement.html
2. Note the font color of the progress bar text for the Tomac row
3. Note the font color of the progress bar text for the Turner Bikes row
4. Change to the Uplift theme and note
5. Change to the Variant of Light, Dark, High Contrast

Expected behavior
Font color of the text on the progress bar should be consistent and easy to read.

Testing with the various themes:
Vibrant - Light => font is black, if value > 75 font changes to white
Subtle - Light => font is black; if value > 75 font changed to white
Subtle - Dark => font is always white
Subtle - Contrast => font is always white

Comparing to forms, the font color change occurs when the value is > 55. So the list and form as inconsistent.

**Comment by claudenbach** [comment]
`  TargetedAchievement(row, cell, value, col) {
    const perc = (100 * value);
    let text = `${perc}%`;
    const ranges = formatters.ClassRange(row, cell, perc, col);
    const target = col.target;
    let isWhite = perc > 60;

    if (col.text) {
      text = col.text;
      text = text.replace('{{value}}', value);
      text = text.replace('<% value %>', value);
      text = text.replace('<%value%>', value);

      text = text.replace('{{percent}}', perc);
      text = text.replace('<% percent %>', perc);
      text = text.replace('<%percent%>', perc);

      col.showPercentText = true;
      isWhite = perc > 75;
    }

    const barClass = (col.ranges && ranges.classes ? ranges.classes : 'primary');
    return `<div class="total bar chart-completion-target chart-targeted-achievement">
              <div class="target remaining bar" style="width: ${(target || 0)}%;"></div>
              <div class="completed bar ${barClass}" style="width: ${perc}%;"></div>
              ${(col.showPercentText ? `<div class="chart-targeted-text l-center" ${(isWhite ? 'style="color: white"' : '')}>${text}</div>
            </div>` : `<div class="audible">${perc}%</div>`)}`;
  }`

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/64291816-a37f8780-cf2e-11e9-80f4-4ffc8d02cd46.png)

**Comment by claudenbach** [comment]
[Git-2730.zip](https://github.com/infor-design/enterprise/files/3576519/Git-2730.zip)

**Comment by tmcconechy** [comment]
The problem is it cant be both consistent and easy to read over the background. So we have to pick one color white or black and always show that for all of them, from what your saying. Depending on if the use a lighter color it may not look great.

This color may not always work depending on the color of the background. One option is to make it all white?

![Screen Shot 2019-09-04 at 5 10 46 PM](https://user-images.githubusercontent.com/814283/64291791-fa895a80-cf36-11e9-9fad-7b2cad49a373.png)

**Comment by claudenbach** [comment]
https://jira.lawson.com/browse/LMCLIENT-26002

**Comment by tmcconechy** [comment]
@claudenbach I cant find the example for:
`Comparing to forms, the font color change occurs when the value is > 55. So the list and form as inconsistent.
`

Do you know what component that is? Or do you have a screen shot? Cant find the form versoin

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/test-targeted-achievement.html
Passed QA in all browsers. Tested in all Themes and Variants.
![image](https://user-images.githubusercontent.com/39508864/65505670-4f980b00-defc-11e9-98e9-7d957c4ca129.png)
