### ISSUE TITLE
Popdown: Not closing when you click outside the popdown using IE

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2734]
**Describe the bug**
Popdown: Not closing when you click outside the popdown using IE.

**To Reproduce**
1. Open IE browser
2. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/popdown/example-index.html
3. Click My Cart to open the popdown
4. Click outside
5. See issue: popdown will not close

**Expected behavior**
Popdown should close when you click outside.

**Version**
- ids-enterprise: v4.20.0-v4.21.0-beta1

**Screenshots**
No applicable screenshots.

**Platform**
 - OS Version: Windows 10
 - Browser Name: IE 11

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Popdown is deprecated since 4.20 in favor of Popover and will be removed in the future. So will not fix any issues with it at this time.

**Comment by brianjuan** [comment]
This is noted @tmcconechy , thanks!
