### ISSUE TITLE
Charts: ability to disable selections

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#2736]
**Is your feature request related to a problem? Please describe.**
We would like to be able to disable selections of bars in charts, because there is no functionality on this and it leads users to think it should do something

**Describe the solution you'd like**
A parameter on the chart component (like 'isSelectable') which takes boolean value. It can be true by default

**Describe alternatives you've considered**
Another possibility is to add this parameter to each value (similar to color). But that is not needed in our use case.

**Comment by tmcconechy** [comment]
Some others we use `selectable: 'single' or false` this may work as a consistent option with others

**Comment by CindyMercadoReyes** [comment]
BDD added for this ticket attached. 
[story_github2736.docx](https://github.com/infor-design/enterprise/files/7171184/story_github2736.docx)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
