### ISSUE TITLE
Application Menu: Improve hierarchy in uplift (New Design)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2739]
**Describe the bug**

We have had reports of the hierarchy in uplift mode of the app menu. in soho it works as each section has a background color change. But in uplift design wants to adjust the spacing instead of a background.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels-icons.html?theme=uplift&variant=light&colors=0563C2
2. Expand the second item to see more heir achy items
4. See attached examples:
https://www.dropbox.com/s/n416uamxdphx3av/Screenshot%202019-09-04%2015.29.29.png?dl=0
https://www.dropbox.com/s/xxodwkhhxir14cq/Screenshot%202019-09-04%2015.30.09.png?dl=0

**Expected behavior**
A clearer hierarchy so you dont get lost in the menu

**Design Comments**

After a brief look it seems that implementation may be a bit off on both sides of the spectrum here, and that this problem was starting to get solved in the design but not communicated well. I’ll try to resolve here.

It seems that largely: alignment, vertical & horizontal spacing may be off in both LMK & IDS examples. The biggest problem in that is the vertical spacing and the lack of alignment in LVL 1 menu items.

New Design: 
https://inforus.invisionapp.com/share/QZTSFWVAFS2

Approx. Adjustment Log: https://github.com/infor-design/design-system/issues/409#issuecomment-528457527

- [x] Even distribution of HCM nav icons at the top.
- [x] Search bar hint text should more clearly tell the user what they can do. If this was a full HCM search then the text ‘search’ would work. However, since it’s nav items and sub pages it doesn’t seem appropriate or helpful. Push it further: an additional idea here is to have the user click in and then immediately get suggestions on what to search for, or things they’ve searched for in the past. For the interim, “Look up menu items” feels very appropriate to me.
- [x] Comfy-er search bar in general. Is consistent with selection / hover states for menu items as well. (40px H, 288 W, 6px Radius)
- [x] Some additional space between header & menu items. Visual separation. (40px vert)
- [x] Clear difference in padding on the left for menus with icons and without.
- [ ] For this menu example, active menu items take on the selected UI theme (instead of the azure). This is basically for theme consistency so that if this was the slate theme or the azure theme, we’d be using values from those families.
- [ ] LVL1 Selected menu item is
Text: bold, #fff @ 100% opacity
Bg: #fff @ 15% opacity
- [ ] LVL1 Hover menu item is
Text: Reg, #fff @ 100%
Bg: #fff @ 5%
- [ ] Vertical spacing between selected & hover states is 4px
- [ ] LVL1 Selected expanded menu item
Text: Bold, #fff @ 100%
Bg: #000 @ 20% Opacity
Chevron: #fff @ 100%
- [ ] Use Uplift-style chevron icons
- [ ] Use Uplift-style add / minus icons
- [ ] Expanded LVL1 sections have additional vertical spacing at bottom (56px)
- [ ] LVL2-6 Normal state menu item
Text: Regular, 14px, #fff @ 50% opacity
Icon: #fff @ 50% opacity
- [ ] LVL2-6 Selected / Hover menu item
Text: Reg, 14px #fff @ 100%
Bg: #fff @ 15%
- [ ] Explore using the provided alternative background colors to help visuals, although text indentation, lvl 1 expansion and text styling should solve for this issue sufficiently.

**Effected Version**
- ids-enterprise: [e.g. v4.21.0]

**Dev To Do**
- [ ] Build a new example page like the design showing HCM menu with actual hierarchy
- [ ] Use inspect in https://inforus.invisionapp.com/d/main#/console/18409050/382534032/inspect  to see any css details for the new design
- [ ] Code the uplift theme so that the menu looks as the new designs now.
- [ ] See if anything needs to be updated with indent in soho theme (the background we will leave as is so more just minor padding issues and any size issues)

**Comment by EdwardCoyle** [comment]
@tmcconechy just checking, but this is ready to be worked on right?

**Comment by tmcconechy** [comment]
Yep good to go. Was hoping you would pick this up 👍

**Comment by kevinwhitedesign** [comment]
Sorry for the delay, yeah Slate only though!

**Comment by brianjuan** [comment]
All pages in the PR are QA passed in all desktop browsers. However, there is just minor alignment issue in **Android Chrome**
http://4220-beta0-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels?theme=uplift
![image](https://user-images.githubusercontent.com/39508864/66296395-0b573280-e920-11e9-99a2-8d0524ace01f.png)

**Comment by EdwardCoyle** [comment]
@brianjuan any particular device specifications?  OS Version, Chrome Version, device type?  I did test in the latest Chrome on a Samsung Galaxy S5 and wasn't seeing this result.

**Comment by tmcconechy** [comment]
@EdwardCoyle I do see this on Browser stack on 10, 9.0, 8, 7 Samsung Galaxy

![Screen Shot 2019-10-07 at 9 16 09 AM](https://user-images.githubusercontent.com/814283/66315137-2b1c3580-e8e3-11e9-9a3f-f3633556585d.png)

Was fine on a few more i tried like a Galaxy 6,7 and pixel 3, pixel 3 xl, Nexus 7 were ok. So just newer galaxy devices?

**Comment by brianjuan** [comment]
http://4220-rc0-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels?theme=uplift&variant=contrast
Passed QA testing on all browsers.
