### ISSUE TITLE
No records are displayed on last page

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#274]
**Describe the bug**
No records are displayed on last page

**To Reproduce**
1. Go to url: http://480-beta0-sohoxi.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html
1. Click the Last Page Button
2. No records are displayed in the datagrid
4. It doesn't matter what you set the the "Record per page" you never see anything on the last page. 

**Expected behavior**
Depending on what you set the "Record per page' data should appear on the last page

**Screenshots**

**Platform**
 
 - All Browsers 

**Additional context**

**Comment by tmcconechy** [comment]
Can no longer reproduce this on http://4110-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html
