### ISSUE TITLE
Tabs: Focus is misaligned after switching to uplift theme from soho or vise versa

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2743]
**Describe the bug**
Tabs focus is misaligned after switching to uplift theme from soho or vise versa

**To Reproduce**
1. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/tabs/example-index.html?theme=soho&variant=light&colors=2578a9
2. Click the last tab, 'Notes'
3. Switch to uplift or vise versa
**Expected behavior**
Focus should be aligned 

**Version**
Beta 4.21

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/64401313-f417f180-d0a2-11e9-88c7-8b6d8cfa43e0.png)

**Platform**
All OS, Browser and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Somehow would need to trigger a resize when changing theme.

**Comment by janahintal** [comment]
QA Failed. Issue still existing.

Go to http://master-enterprise.demo.design.infor.com/components/tabs/example-index.html?
Click the last tab, 'Notes'
Switch to Vibrant theme or vise versa
Expected behavior
Focus should be aligned
 
![image](https://user-images.githubusercontent.com/45757016/65590820-00b2aa00-dfbe-11e9-8980-20c0db149c26.png)

**Comment by tmcconechy** [comment]
@janahintal I tried those steps and it seems fine (this was actually the whole fix). Maybe try clearing browser cache.

- go to http://master-enterprise.demo.design.infor.com/components/tabs/example-index.html
- click notes 
- select theme -> vibrant
- page resizes and shows correct (Chrome Mac)

**Comment by janahintal** [comment]
Hi @tmcconechy , I am still encountering this issue even after clearing cache. 

go to http://master-enterprise.demo.design.infor.com/components/tabs/example-index.html
**click notes**
select theme -> **vibrant**

After changing the theme to Vibrant, the focus is getting misaligned in Notes tab.
