### ISSUE TITLE
Tabs: Searchfield 'x' button and text is overlapping each other and the dropdown filter is cut off

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2745]
**Describe the bug**
Tabs searchfield 'x' button and text is overlapping each other and the dropdown filter is cut off

**To Reproduce**
1. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button.html
2.  In the text field populate with a long text 
3. In the dropdown filter, select Movies
Notice that the 'x' button overlaps with the text and the filter is cut off. 

**Expected behavior**
Button should not overlap the text and the dropdown filer should not be cut off 

**Version**
Beta 4.21

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/64416950-b7f88700-d0ca-11e9-9308-12be7f6475b9.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Seems like this worked better in http://4190-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button.html

**Comment by janahintal** [comment]
QA Failed for Mobile iOS and Android devices. 

Android
![image](https://user-images.githubusercontent.com/45757016/65575609-d0114700-dfa2-11e9-977b-5570a8af6430.png)

iOS
![image](https://user-images.githubusercontent.com/45757016/65575655-f0d99c80-dfa2-11e9-91aa-6b01b208fd07.png)

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thank
Verified in http://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button.html Across all platform
