### ISSUE TITLE
Tabs: Tab with App Menu does not have 'x' close button after refreshing the page in uplift theme 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2746]
**Describe the bug**
Tabs with App Menu does not have 'x' close button after refreshing the page in uplift theme

**To Reproduce**
1. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/tabs-module/example-app-menu-button.html
http://4210-beta1-enterprise.demo.design.infor.com/components/tabs-module/example-add-tab-button.html
2. Switch to uplift theme
3. Refresh the page 
- notice that the close button for each tab is missing
4. Switch to Soho theme 
 - notice that the Tab and Header color is not similar. 

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/64418359-70272f00-d0cd-11e9-9e50-103547acef99.png)

![image](https://user-images.githubusercontent.com/45757016/64418402-8634ef80-d0cd-11e9-9afa-ffd418bbb8b7.png)

**Platform**
All OS, Browser and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
1. We should make the icons change somehow when changing theme in the demo app
2. In uplift the icon is not aligned here. Should fix next version.

**Comment by tmcconechy** [comment]
Found the x is missing will fix these as thats a regression.

**Comment by brianjuan** [comment]
http://4210-beta2-enterprise.demo.design.infor.com/components/tabs-module/example-app-menu-button.html
http://4210-beta2-enterprise.demo.design.infor.com/components/tabs-module/example-add-tab-button.html
QA Passed in all browsers.
