### ISSUE TITLE
Tabs: Add tooltip for overflowed text

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2747]
**Describe the bug**
Tabs tooltip is not working in Multi Tab

**To Reproduce**
1. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/tabs-multi/example-index.html
2. Minimize the screen
3. Hover to the first tab with long label

**Expected behavior**
Tooltip should appear

**Version**
Beta 4.21

**Screenshots**
n/a

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
I cant see that this was ever a feature of the tabs. But it isnt a bad idea as we do this elsewhere. So leaving it as a enhancement for now in the backlog.

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks
Verified in http://master-enterprise.demo.design.infor.com/components/tabs-multi/example-index.html
