### ISSUE TITLE
Uplift: Layout issues on some components

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2748]
**Describe the bug**
The Uplift theme contains layout issues on some components:

- [x] **Pager** - In high contrast, the color of the "disabled" pager button is the same as the enabled
- [x] **Date Picker** - In IE, arrow icon is misaligned (being fixed in #2713 / #2704)
- [x] **Dropdown** - The Search Icon in filtering mode is cut off. 
- [x] **Dropdown** - In Dark theme, there's an extra white shadow at the bottom

**To Reproduce**
1. Go to the URLs in the screenshots below

**Expected behavior**
Layout on components below should be correct.

**Version**
- ids-enterprise: v4.20.0 - v4.21.0-beta1

**Screenshots**
**Pager** - http://4210-beta1-enterprise.demo.design.infor.com/components/pager/example-index.html?theme=uplift
High Contrast
![image](https://user-images.githubusercontent.com/39508864/64423510-4aa02280-d0d9-11e9-8033-7cd0284afba1.png)

**Date Picker** - http://4210-beta1-enterprise.demo.design.infor.com/components/datepicker/example-index.html?theme=uplift
**IE**
![image](https://user-images.githubusercontent.com/39508864/64423591-7f13de80-d0d9-11e9-811d-e83f18e62bc1.png)

**Dropdown** - http://4210-beta1-enterprise.demo.design.infor.com/components/dropdown/example-index.html?theme=uplift
![image](https://user-images.githubusercontent.com/39508864/64423912-34df2d00-d0da-11e9-94b9-8ad2a9438760.png)

Dark theme
![image](https://user-images.githubusercontent.com/39508864/64424261-2cd3bd00-d0db-11e9-8f8c-5a1ecb370e05.png)

**Platform**
 - All devices, OS, and browsers

**Additional context**
N/A.

**Comment by tmcconechy** [comment]
@EdwardCoyle FYI for the date picker point im working on that area as well on #2713 / #2704 so just in case we bump into each other there.

**Comment by EdwardCoyle** [comment]
I believe the [issue with the Search Icon on Dropdown](http://master-enterprise.demo.design.infor.com/components/dropdown/example-index.html?theme=uplift) is fixed on `master`:

![Screen Shot 2019-09-13 at 10 43 24 AM](https://user-images.githubusercontent.com/3249601/64871610-912ed900-d613-11e9-83bd-9f58fc3871d5.png)

**Comment by brianjuan** [comment]
All of the issues above are now fixed in master in all browsers, except in Windows Edge, month name is now too close to the edge.
http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html?theme=uplift
![image](https://user-images.githubusercontent.com/39508864/65589700-0a3b1280-dfbc-11e9-9193-b684b3bd3c5f.png)

**Comment by brianjuan** [comment]
Passed QA in all browsers, moving to Done.
