### ISSUE TITLE
Editor: Input Event is not detected in IE

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2755]
**Describe the bug**
Editor: Input Event is not detected in IE.

**To Reproduce**
1. Open IE browser
2. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/editor/example-with-events.html
3. Type "Test Event" in the editor
4. See issue: Input event is not being detected

**Expected behavior**
Input event should fire when there's an input in the editor

**Version**
- ids-enterprise: v4.14.0 to v4.21.0-beta

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/64519531-e2468080-d326-11e9-9bbe-c893a2803b4a.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: IE 11

**Additional context**
N/A.

**Comment by tmcconechy** [comment]
IE does not work right with respect to the input event. While this issue is logged i dont think its worth spending time on at this time
