### ISSUE TITLE
File Upload: X button is not visible in Uplift

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2757]
**Describe the bug**
File Upload: X button is not visible in Uplift.

**To Reproduce**
1. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/fileupload/example-index.html?theme=uplift and http://4210-beta1-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html?theme=uplift
2. Upload a file
3. See issue: X button is not visible but clickable

**Expected behavior**
X button should be visible in uplift

**Version**

- ids-enterprise: v4.20.0 - v4.21.0-beta

**Screenshots**
http://4210-beta1-enterprise.demo.design.infor.com/components/fileupload/example-index.html?theme=uplift
![image](https://user-images.githubusercontent.com/39508864/64524235-b203df80-d330-11e9-9495-5709bd504573.png)

http://4210-beta1-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html?theme=uplift
![image](https://user-images.githubusercontent.com/39508864/64524323-d8297f80-d330-11e9-88cd-7e90a2d45258.png)

**Platform**
 - All devices, OS, and browsers.

**Additional context**
N/A.

**Comment by tmcconechy** [comment]
Found the x is missing will fix these as thats a regression.

**Comment by brianjuan** [comment]
Passed QA in all browsers.
http://4210-beta2-enterprise.demo.design.infor.com/components/fileupload/example-index.html?theme=uplift
![image](https://user-images.githubusercontent.com/39508864/64695367-874f8d80-d4ce-11e9-9799-91ebe452b566.png)

http://4210-beta2-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html
![image](https://user-images.githubusercontent.com/39508864/64695273-51aaa480-d4ce-11e9-9829-6d5186ab32fc.png)
