### ISSUE TITLE
Datagrid Context Menu Component: Right clicking breaks the datagrid

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2758]
**Describe the bug**
Datagrid Context Menu Component: Right clicking breaks the datagrid

**To Reproduce**
1. Go to url: http://4210-beta1-enterprise.demo.design.infor.com/components/datagrid/test-contextmenu
2. Right Click on  Order Date
3. Action One to three list will appear
4. Click on Action Two. the whole data grid disappears. Please see screen shot attached.  

**Expected behavior**
Datagrid should not be affected when the user right clicks on the data grid.

**Version**

- ids-enterprise: [e.g. v4.21]

**Screenshots**
![datagrid comtextmenu error](https://user-images.githubusercontent.com/39101346/64535344-1d27c480-d2e5-11e9-83cc-f3177d7df7cd.png)

**Platform**
 - All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
This issue was fixed with the same fix as https://github.com/infor-design/enterprise/pull/2728

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
