### ISSUE TITLE
Datagrid: Setting paging off does not remove the pager

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#2759]
**Describe the bug**
Disable paging does not remove the paging toolbar.
Regression?

**To Reproduce**
1. Go to [this example](https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-paging-client-side)

2. Open dev tools
3. Run this in console
```
var settings = $('#datagrid').data('datagrid').settings
settings.paging = false;
$('#datagrid').data('datagrid').updated(settings)
```

**Expected behavior**
Paging toolbar should be removed

**Version**
- ids-enterprise: v4.20.1

**Comment by tmcconechy** [comment]
Im not sure if this ever worked as it is a bit of an unusually case to remove the pager on the fly. We dont have any tests in place for this to work covered. But we can add some.

**Comment by guoliang** [comment]
It is a use case so it would be nice to have this issue prioritized :)

**Comment by johnbarcena** [comment]
tested on  http://localhost:4000/components/datagrid/test-update-settings.html
ALL Browser and Devices
Test PASSED
![image](https://user-images.githubusercontent.com/52902639/66904195-40593880-f036-11e9-818b-720c05d9c66e.png)
