### ISSUE TITLE
Tabs Control: Clicking (x) opens the Dropdown Tab Menu instead of dismissing

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#276]
**Describe the bug**
Clicking (x) opens the Dropdown Tab Menu instead of dismissing

**To Reproduce**
1. Go to url: http://480-beta0-sohoxi.demo.design.infor.com/components/tabs/test-dismissibles-with-dropdowns.html
1. Click (x) in the Dropdown Tab Menu (Plastic (Dismissible & Dropdown))
2. Dropdown will open instead of dismissing

**Expected behavior**
The "Plastic (Dismissible &Dropdown) should be removed from the page

**Screenshots**
<img width="1277" alt="dismissibles with dropdown" src="https://user-images.githubusercontent.com/39101346/41933805-e3ae3492-7952-11e8-914e-e3a87858343b.png">

**Platform**
 - All Browsers

**Additional context**
None

**Comment by brianjuan** [comment]
http://localhost:4000/components/tabs/test-dismissibles-with-dropdowns.html
http://4120-beta0-enterprise.demo.design.infor.com/components/tabs/test-dismissibles-with-dropdowns.html
Passed QA testing, dismissible tab is now closing when X button was clicked.
