### ISSUE TITLE
Calendar: Should not be able to select dates before the for date in the to date

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#2762]
**Describe the bug**
Calendar Component: Old dates on new event should be grayed out

**To Reproduce**
1. Go to url: http://4210-beta1-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=soho&variant=light&colors=2578a9
2. Double click on any calendar day and the "New Event" window will appear
3. Open the  "To" calendar and select a past date 9/6/2019
4. See error is that for the "To" old dates should be grayed out or have logic starting that you can have an old date for the "To" field box.

**Expected behavior**
Old dates should be grayed out

**Version**

- ids-enterprise: [e.g. v4.21]

**Screenshots**
<img width="978" alt="Calendar Issue" src="https://user-images.githubusercontent.com/39101346/64557570-ce435480-d30f-11e9-9383-ae15685d0136.png">

**Platform**
 - All Browsers

**Additional context**
None

**Comment by tmcconechy** [comment]
We could either
1. Change to a range picker http://master-enterprise.demo.design.infor.com/components/datepicker/example-range.html
1. Use validation on the inputs
1. Use validation and disabled dates feature

**Comment by tmcconechy** [comment]
Descoping some issues for now we wont have time for
