### ISSUE TITLE
Fieldset: Submit button in a fieldset is throwing error

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2763]
**Describe the bug**
Fieldset: Submit button in a fieldset is throwing an error.

**To Reproduce**
1. Go to http://4210-beta1-enterprise.demo.design.infor.com/components/fieldset/example-fields.html
2. Type "test" in all of the input fields
3. Click Submit button
4. See issue: Error will be displayed

**Expected behavior**
There should be no error when Submit button is clicked

**Version**
- ids-enterprise: v4.14.0 - v4.21.0-beta

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/64587587-74579300-d3d2-11e9-97d7-bfa4b9161ed9.png)

**Platform**
 - All devices, OS, and browsers.

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Descoping this for now.
