### ISSUE TITLE
Calendar: Adds 1 day when 'All Day' is checked

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2768]
**Describe the bug**

**To Reproduce**
1. Open Safari
1. Set time zone to Manilla / Phillpines
1. Set the time to 10PM 
1. Go to https://4210-beta1-enterprise.demo.design.infor.com/components/calendar/example-index.html?
3. Create an event ( Start date sept 10 end date sept 13 )
1. Verify that  'All Day' is checked
1. Click Submit
1. Verify End Dates (says the 14th not 13th)

**Expected behavior**
![image](https://user-images.githubusercontent.com/52902639/64611487-28254680-d404-11e9-8d41-41b6def23c91.png)

**Version**
- ids-enterprise: [4.21 beta1]

**Actual**
![image](https://user-images.githubusercontent.com/52902639/64610742-7e918580-d402-11e9-84eb-4f3b21b72a3a.png)

**Platform**
 - Browser Name: safari

**Additional context**

**Comment by tmcconechy** [comment]
Can you clarify and improve the steps? It looks like your selecting multiple days in the modal and that everything is actually correct. When i try it i select 09/10/2019 - 09/13/2019 and it seems like its working correctly and im not getting the same results.

**Comment by johnbarcena** [comment]
**Input Data :**
September 10 to September 13
**Browser:**
Safari
**OS:**
macOS Mojave 10.14.6

**Steps**
1. Open Safari
2. Go to https://4210-beta1-enterprise.demo.design.infor.com/components/calendar/example-index.html
3. Click '+' icon and select Add Event (Modal)
4. Select date From 9/10/2019 To 9/13/2019
5. Leave 'All Day' checked
6. Click Submit
7. Verify End Dates, Notice that End Date in accordion-content on the right side is September 14

![image](https://user-images.githubusercontent.com/52902639/64616064-560f8880-d40e-11e9-8961-86d0e7095dfe.png)

**Comment by tmcconechy** [comment]
<img width="515" alt="Screen Shot 2019-09-10 at 9 15 30 AM" src="https://user-images.githubusercontent.com/814283/64616979-8ffb7300-d3ab-11e9-9f6c-01b817022d6f.png">

Im not seeing the same thing. Whats your timezone? And time you tried this? Wonder if its a timezone issue?

**Comment by johnbarcena** [comment]
this is my local machine's timezone
![image](https://user-images.githubusercontent.com/52902639/64617153-8c4e0780-d410-11e9-8c84-1f7f3b61098f.png)

**Comment by johnbarcena** [comment]
Safari Version
![image](https://user-images.githubusercontent.com/52902639/64617327-da630b00-d410-11e9-8e13-de7feaa7e59b.png)

**Comment by tmcconechy** [comment]
Still cant reproduce this setting the time zone to manilla on my end. We will shelf this issue for now.

**Comment by johnbarcena** [comment]
**Input Date is Sept11 to Sept16**
I tried using **Houston, TX - United States timezone** and it seems like moving the Start Date 1 step backward. refer to screenshot below
![image](https://user-images.githubusercontent.com/52902639/64670001-2d32d600-d496-11e9-9e1b-2899ae7ba041.png)

but when All Day is unchecked the End Date Moves 1 step backward
![image](https://user-images.githubusercontent.com/52902639/64670188-bf3ade80-d496-11e9-87a0-f172dff95878.png)

I believe you're right about the timezone as a factor

**Comment by tmcconechy** [comment]
Descoping this issue for now
