### ISSUE TITLE
Lookup: Required message is not removed after selecting a value from the dialog

### ISSUE THREAD

**Issue by mgdfgodoy** [infor-design/enterprise#2769]
**Describe the bug**
On a required lookup field, "Required" message does not disappear after selecting a value from the dialog, even on focus out of the field.  However, if value is manually typed in the input field, the "Required" message disappears.

**To Reproduce**
1. Go to http://latest-enterprise.demo.design.infor.com/components/lookup/example-index.html
2. Select value from the dialog
3. Delete value from field, then remove focus from the lookup field, then select another from the dialog
    Notice "Required" message is removed immediately, even without removing focus.
4.  Repeat steps above, but this time do not remove focus from the field.  Just delete value, then select another value from the dialog
     Notice "Required message is retained below, even if you remove focus from the field

**Expected behavior**
After selecting value from lookup, "Required" message should disappear without having to focus out of the field

**Version**
- ids-enterprise-ng: 4.20.1

**Gif**
![lookup_test](https://user-images.githubusercontent.com/55127155/64592520-c8687480-d3de-11e9-9143-9e77ff9ee6d0.gif)

**Comment by tmcconechy** [comment]
Descoping some issues for now we wont have time for
