### ISSUE TITLE
Hidden Tabs Control: Tab contents are still displayed when the tab becomes hidden

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#277]
**Describe the bug**
Tab contents are stiil shown when Tab was rehidden

**To Reproduce**
1. Go to url: http://480-beta0-sohoxi.demo.design.infor.com/components/tabs/example-hidden-tabs.html
2. Click Show Hidden Tabs button
3. Go to Tab # 5, contents of Tab # 5 will be shown
4. Click Hide Tabs 2 and 5 button while still on Tab # 5
5. Notice that the contents of Tab # 5 is still shown

**Expected behavior**
Tab number 5 should not be appearing

**Screenshots**
 - All Browsers 

**Additional context**
None

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/tabs/example-hidden-tabs.html
Passed QA testing, working as expected across all browsers.
