### ISSUE TITLE
Datagrid: Column with an alert and text overflow does not render text always

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#2773]
**Describe the bug**
In a Datagrid, say, a column has an alert formatter and text overflow set. If the text description of this column is longer than column width, ellipsis is not displayed. Instead the text  is totally hidden.

**To Reproduce**
1. Go to Datagrid, test ellipsis sample (datagrid/test-ellipsis.html)
2. Scroll to the right to status column.
3. Adjust the column width and see the description text hides when the width is reduced.

**Expected behavior**
Expect ellipsis to be rendered instead.

**Version**

- ids-enterprise: v4.21.0-beta.1

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Windows 10 
 - Browser Name Chrome
 - Browser Version 76.0.3809.132

**Additional context**

**Comment by aaralikar** [comment]
![AlertAndEllipsis](https://user-images.githubusercontent.com/22720894/64634060-0acf8880-d3c2-11e9-9863-465a74d5fb78.gif)

**Comment by tmcconechy** [comment]
OK, Im pretty sure it didnt work on every column type. Will have to figure this out for alert columns.

**Comment by aaralikar** [comment]
Added 'textOverflow: ellipsis' to the status column in datagrid\test-ellipsis.html

      columns.push({ id: 'status', name: 'Status', field: 'status', formatter: Formatters.Alert, filterType: 'select', textOverflow: 'ellipsis', editorOptions: {clearable: true}, options: statuses, ranges: [{'value':'Confirmed', 'classes': 'success', text: 'Confirmed'}, {'value':'Error', 'classes': 'error', text: 'Error'}]});

**Comment by pwpatton** [comment]
Per @lipetzan : Issue is that some data will show up as missing and give users wrong impression of data.

**Comment by pwpatton** [comment]
If just the ellipsis didn't show then we'd be fine but it causes the data to completely dissappear when text is longer that column width.

**Comment by tmcconechy** [comment]
But from the issue all it is missing ... at the end. How does that mean missing data?

**Comment by pwpatton** [comment]
@aaralikar  can you post a recording of what you're seeing?

**Comment by pwpatton** [comment]
I would totally agree if the data line just didn't go completely missing. 
Look at this example
https://usspvwlmclient1.infor.com/hcm/EmployeeSelfService/list/UserNotification.ActorUserNotification?csk.ng=true&csk.developer=true
admin1/lawson
Narrow the first column with the alert in it.

**Comment by tmcconechy** [comment]
Ok i see, i guess because of that type it does'nt cut off. I'll take a look but we really need to complete 4.21 on time.

**Comment by pwpatton** [comment]
Agreed but we will get creamed on this one.

**Comment by janahintal** [comment]
QA Passed. Tested in 
http://4210-beta3-enterprise.demo.design.infor.com/components/datagrid/test-alerts.html?theme=uplift&variant=contrast&colors=003066
http://4210-beta3-enterprise.demo.design.infor.com/components/datagrid/test-ellipsis?theme=soho&variant=light&colors=2578a9
http://4210-beta3-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?theme=uplift&variant=light&colors=0563C2
For all browser, OS and devices. Thanks
