### ISSUE TITLE
Calendar: Created events from certain dates is not displayed in 'Upcoming' 

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2775]
**Describe the bug**
 Created events from certain dates are not displayed in upcoming 
Chrome: from Sept 27 onwards
Safari: from Sept 26 onwards

**To Reproduce**
1. Go to https://4210-beta1-enterprise.demo.design.infor.com/components/calendar/example-index.html?
2. Create an event on each date from day 24 to day 30
3. Verify Upcoming Events on the left panel

**Expected behavior**
Created events with dates => today() should be displayed in the Upcoming event panel

**Version**
- ids-enterprise: 4.21 beta1

**Screenshots**
Chrome
![image](https://user-images.githubusercontent.com/52902639/64674389-5443d480-d4a3-11e9-9ddb-a562c159f917.png)

Safari
![image](https://user-images.githubusercontent.com/52902639/64674470-7ccbce80-d4a3-11e9-81f7-02e9f11cf94e.png)

**Platform**
 - Browser Name Chrome & Safari

**Additional context**

**Comment by tmcconechy** [comment]
This is ok. The setting is set to show only 14 days ahead. This is combined with the timezone issue in safari you mentioned so its a little different. We probably wont fix that issue, so i will leave that open for, but we definitely will not fix this issue as this is by setting.
