### ISSUE TITLE
Calendar: Event is not displayed as upcoming when the start date is today()

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2776]
**Describe the bug**
Using Chrome browser, Event is not displayed as upcoming when the start date is today() 

**To Reproduce**
1. Set your local Machine's timezone to Manila, Philippines
2. Go to https://4210-beta1-enterprise.demo.design.infor.com/components/calendar/example-index.html
3. Go to or Click today
4. Create an event
5. Verify Upcoming event

**Expected behavior**
Created events with dates => today() should be displayed in the Upcoming event panel

**Version**
- ids-enterprise: 4.21 beta1

**Screenshots**
![image](https://user-images.githubusercontent.com/52902639/64681825-fc14ce80-d4b2-11e9-89ba-cddec4f9efee.png)

**Platform**
 - Browser Name : chrome

**Additional context**
Timezone should be Manila, Philippines

**Comment by tmcconechy** [comment]
Im not able to reproduce this issue. 
1) Open https://4210-beta1-enterprise.demo.design.infor.com/components/calendar/example-index.html#
2) click today
3) click + Then add event API
4) the event immediately shows up in both the upcming and on the calendar

**Comment by johnbarcena** [comment]
I think this has something to do with the local machine's timezone. when I retested it earlier this morning (Manila, PH time)  I was able to see the event on upcoming, but when I tested it again 12noon (Manila, PH time)  I don't see the event on upcoming.
I will edit the steps and put an additional step for setting the timezone.

**Comment by tmcconechy** [comment]
@ericangeles can you see if you can reproduce this issue? I was unable to be changing the time zone but since you are there maybe you can give this a test?

**Comment by ericangeles** [comment]
@tmcconechy will look into it.

**Comment by ericangeles** [comment]
Yeah, the issue also occurs on my end.

**Comment by tmcconechy** [comment]
Ok see if you can find a solution?

**Comment by ericangeles** [comment]
> Ok see if you can find a solution?

For sure.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
