### ISSUE TITLE
Calendar: Incorrect date/time format in duration

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2777]
**Describe the bug**
Incorrect date/time format in duration when 'All Day' is unchecked

**To Reproduce**
1. Go to https://4210-beta1-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Create an event from September 15 to 21
3. Uncheck 'All Day'
4. Verify Duration in the right side panel

**Expected behavior**
Should display a correct date/time format

**Version**
- ids-enterprise: 4.21 beta1

**Screenshots**
![image](https://user-images.githubusercontent.com/52902639/64682297-d3410900-d4b3-11e9-854b-847d9a983711.png)

**Platform**
 - All

**Additional context**

**Comment by johnbarcena** [comment]
tested on 4.22 rc0 and it seems fine. see screenshot
However, hours are not computed accordingly i.e (you use 7 hrs or less). Lastly, when all day is unchecked and duration of event is 1 day only, there's no duration displayed.
![image](https://user-images.githubusercontent.com/52902639/66644438-850a5b80-ec53-11e9-9861-aab7e3f909e7.png)

**Comment by tmcconechy** [comment]
This may be a time zone issue similar to https://github.com/infor-design/enterprise/issues/2768

**Comment by jbrcna** [comment]
This issue still **exists** in 4.250 beta 0 
https://4250-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html#
Observations are as follows:
1. If you uncheck `All Day` within a single day it will display a **CORRECT** duration of date and time
![image](https://user-images.githubusercontent.com/56722184/72601883-3efb1d00-3951-11ea-8dab-5a98333fb196.png)

2. But if you uncheck  `All Day` and select multiple days it will display an **INCORRECT** duration of time. Noticed that only a single day is counted as 12hrs. 24hrs x 2 + 12 = 60
![image](https://user-images.githubusercontent.com/56722184/72602818-d7de6800-3952-11ea-8fd3-c8c7883478b0.png)

3. Lastly, When you set 23-hour duration it will display an **INCORRECT** duration of time. It's 47 hours if you make it 2 days. The same issue noted above in no.2
![image](https://user-images.githubusercontent.com/56722184/72603426-fa24b580-3953-11ea-8fb5-3a42385c66f1.png)

![image](https://user-images.githubusercontent.com/56722184/72603140-6ce16100-3953-11ea-9192-4f891f60b49f.png)

**Comment by tmcconechy** [comment]
This bug is not fixed yet not sure when we will have time

**Comment by jbrcna** [comment]
Noted on that @tmcconechy . I just put some observations because of the UI change for reference.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
