### ISSUE TITLE
Calendar: Overlapping text in calendar-upcoming-events accordion-content

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2778]
**Describe the bug**
Overlapping text in calendar-upcoming-events accordion-content

**To Reproduce**
1. Go to https://4210-beta1-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Create event with name "New Random Event12345"
3. Verify that theme is SOHO
4. Verify the name of the newly created event in the Upcoming panel 
5. Create event with name "New Random Event1"
6. Verify that theme is Uplift
7. Verify the name of the newly created event in the Upcoming panel 

**Expected behavior**
Text should not overlap

**Version**
- ids-enterprise: 4.21 beta1

**Screenshots**
SOHO
![image](https://user-images.githubusercontent.com/52902639/64684107-13ee5180-d4b7-11e9-817e-f8be8900c7ee.png)

Uplift
![image](https://user-images.githubusercontent.com/52902639/64684197-3da77880-d4b7-11e9-9040-ad0b0a41c328.png)

**Platform**
 - All

**Additional context**
Soho: 20-21 character
Uplift : 16-17 character

**Comment by janahintal** [comment]
Issue still exist in IE 11. 

![image](https://user-images.githubusercontent.com/45757016/66105094-0f681500-e5ed-11e9-9c0a-dba10c934b8a.png)

**Comment by tmcconechy** [comment]
@janahintal im not able to reproduce exactly that issue but i see another one. Please make a new issue with further steps and also note that the text is too big on the same issue on the right side on that new issue.

We will treat whats left as a new issue.

See
![Screen Shot 2019-10-03 at 10 57 00 AM](https://user-images.githubusercontent.com/814283/66138444-9f499700-e5cc-11e9-9a75-aeb8ef9a1531.png)

![Screen Shot 2019-10-03 at 10 56 56 AM](https://user-images.githubusercontent.com/814283/66138449-a1135a80-e5cc-11e9-89e2-da2c5a6b855f.png)
