### ISSUE TITLE
Calendar: Text becomes underlined when High Contrast variant is used.

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2779]
**Describe the bug**
The text becomes underlined when High Contrast variant is used.

**To Reproduce**
1. Go to https://4210-beta1-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=soho&variant=contrast
2. Create an event
3. Verify that variant is 'High Contrast'
4. Mouse Hover on the name of the created event in the right panel
5. Verify the name of the created event in the right panel

**Expected behavior**
Text should not be underlined
![image](https://user-images.githubusercontent.com/52902639/64685899-52394000-d4ba-11e9-9877-7cdbfc603389.png)

**Version**
- ids-enterprise: 4.21 beta1

**Screenshots**
![image](https://user-images.githubusercontent.com/52902639/64685794-2453fb80-d4ba-11e9-8f1a-5befc411f14b.png)

**Platform**
 - All

**Additional context**
accordion-header

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
