### ISSUE TITLE
Calendar: Create Day View 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2780]
**Is your feature request related to a problem? Please describe.**

We need to implement the day view in the calendar. We need a new design for this. (May be similar to google calendar day view)

**Describe the solution you'd like**

Implement dayview similar to monthview as a new component and then integrate into the calendar component.

**Describe alternatives you've considered**
N/A

**Additional context**
See also https://github.com/infor-design/enterprise/issues/2518

**Comment by tmcconechy** [comment]
cc @vonnyw

**Comment by janahintal** [comment]
Hello @tmcconechy, as per testing in Day and Week view for longer events, I was unable to scroll down and view for longer events. Please refer below image 

1. Goto http://4230-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html#
2. Modify the Personal 3 event and make it until 11:00 PM
3. Try to scroll down

![image](https://user-images.githubusercontent.com/45757016/68669786-5ea74b00-0586-11ea-9cf7-f05e79f4b4a2.png)


![image](https://user-images.githubusercontent.com/45757016/68669713-27389e80-0586-11ea-8d43-2a6629c34041.png)

![image](https://user-images.githubusercontent.com/45757016/68669743-3b7c9b80-0586-11ea-92b7-08cbd8f021cc.png)


Tested in 
http://4230-beta0-enterprise.demo.design.infor.com/components/week-view/example-one-day.html?theme=uplift&variant=light&colors=0563C2#
http://4230-beta0-enterprise.demo.design.infor.com/components/week-view/example-two-day.html?theme=uplift&variant=light&colors=0563C2#
http://4230-beta0-enterprise.demo.design.infor.com/components/week-view/example-two-weeks.html?theme=uplift&variant=light&colors=0563C2
http://4230-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html

**Comment by tmcconechy** [comment]
Moving to done as made https://github.com/infor-design/enterprise/issues/3095 as not fixing as it is working as i designed it to. The event will just cut off. Commented on that issue.

Any further issues on day view lets just make a new issue.
