### ISSUE TITLE
Treemap: not drawn correctly when 1 value is dominating

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#2794]
**Describe the bug**
The chart is not drawn correctly when 1 value is dominating

**To Reproduce**
1. create more values for treemap chart
2. make one value something like 99% of the total
3. observe chart

**Expected behavior**
Chart should be drawn properly as full rectangle

**Screenshots**
![image](https://user-images.githubusercontent.com/11279863/64949538-b45ac200-d879-11e9-846d-05df097da266.png)

**Comment by hohnzy** [comment]
You can see the data in the legend
`{
  "size": 2.6345027174E11,
  "count": 428345,
  "data": [
    {
      "name": "Bod",
      "value": 621020385
    },
    {
      "name": "JSON",
      "value": 621524675
    },
    {
      "name": "AnyData",
      "value": 262171903987
    },
    {
      "name": "DSV",
      "value": 35822693
    }
  ]
}`
The strip is okey, but I think it should be perfect rectangle. Here you can see it is not on the right side. On left side its perfectly alligned.
![image](https://user-images.githubusercontent.com/11279863/65025961-e92d4e80-d937-11e9-9b7f-3780e3e58170.png)

**Comment by deep7102** [comment]
Hi @hohnzy can not reproduce the issue as given data. It render all blank.

```
<div class="row">
  <div class="twelve columns">
      <div class="widget">
        <div class="widget-header">
          <h2 class="widget-title">Tree Map Example</h2>
        </div>
        <div class="widget-content">
          <div id="treemap-chart-example" class="chart-container">
          </div>
        </div>
      </div>
  </div>
</div>

<script id="test-script">
$('body').on('initialized', function () {
  var treeMapData = {
    size: 2.6345027174E11,
    count: 428345,
    data: [
      {
        name: "Bod",
        value: 621020385
      },
      {
        name: "JSON",
        value: 621524675
      },
      {
        name: "AnyData",
        value: 262171903987
      },
      {
        name: "DSV",
        value: 35822693
      }
    ]
  };

  $('#treemap-chart-example').treemap({ dataset: treeMapData });

});
</script>
```

**Comment by tmcconechy** [comment]
I got it running like this....

```
<script>
$('body').on('initialized', function () {
  var data = {
   "name": "Total Objects",
   "children": [
      {
       "name": "type1",
       "children": [
        {"name": "Bod", "value": 621020385}
       ]
      },
      {
       "name": "type2",
       "children": [
        {"name": "JSON", "value": 621524675}
       ]
      },
      {
       "name": "type3",
       "children": [
        {"name": "AnyData", "value": 262171903987}
       ]
      },
      {
       "name": "type4",
       "children": [
        {"name": "DSV", "value": 35822693}
       ]
      }
     ]
  };

  $('#treemap-chart-example').treemap({dataset: data});
});
</script>
```

But that rendered something totally different.

**Comment by tmcconechy** [comment]
any updates @hohnzy we still cant reproduce this.

**Comment by hohnzy** [comment]
I would like to see what it rendered then. because this dataset is rendering the exact screen ive already sent.
the code is this:
```
<div soho-treemap
             *ngIf="selectedChartType === overviewChartType.TREEMAP && !isLoading"
             [dataset]="chartsSettings.treemapData"
             [colors]="chartsSettings.colors"
             [redrawOnResize]="true"
             [showLabel]="false"
             [showTitle]="true"></div>
```

and the dataset has this model (and used the sent values):
```
interface TreemapDataModel {
  name: string,
  children: TreemapData[]
}

interface TreemapData {
  name: string,
  children: OverviewDataItem[]
}

export interface OverviewDataItem {
  name: string,
  value: number
}
```

**Comment by tmcconechy** [comment]
ok, what we tried is to take the original data and massage it into this example....

```html
<div class="row">
  <div class="twelve columns">
      <div class="widget">
        <div class="widget-header">
          <h2 class="widget-title">Tree Map Example</h2>
        </div>
        <div class="widget-content">
          <div id="treemap-chart-example" class="chart-container">
          </div>
        </div>
      </div>
  </div>
</div>

<script>
$('body').on('initialized', function () {
  var data = {
   "name": "Total Objects",
   "children": [
      {
       "name": "type1",
       "children": [
        {"name": "Bod", "value": 621020385}
       ]
      },
      {
       "name": "type2",
       "children": [
        {"name": "JSON", "value": 621524675}
       ]
      },
      {
       "name": "type3",
       "children": [
        {"name": "AnyData", "value": 262171903987}
       ]
      },
      {
       "name": "type4",
       "children": [
        {"name": "DSV", "value": 35822693}
       ]
      }
     ]
  };

  $('#treemap-chart-example').treemap({dataset: data});
});
</script>
```

It renders this:

![Screen Shot 2020-09-03 at 9 57 04 AM](https://user-images.githubusercontent.com/814283/92124490-d8d1e600-edcb-11ea-9416-7bffb3cd7ad7.png)

Maybe you can put that example with a modal in a runable NG example file and paste it in or work on a https://stackblitz.com/

**Comment by hohnzy** [comment]
In ng demo app I've put the data into treemap.demo.ts:
```
public treemapData = {
      name: 'Storage Utilization (78 GB)',
      children: [
      {
        name: 'by type',
        children: [
        {
          name: 'type1',
          children: [
            {name: 'JSON', value: 262171903987}
          ]
        }, {
          name: 'type2',
          children: [
            {name: 'PDF', value: 621524675}
          ]
        }, {
          name: 'type3',
          children: [
            {name: 'BOD', value: 621020385}
          ]
        }, {
          name: 'type4',
          children: [
            {name: 'TXT', value: 35822693}
          ]
        }]
      }]
    };
```

resulting in (much more visible with custom colors we are using):
![image](https://user-images.githubusercontent.com/11279863/96131079-09dc2500-0ef9-11eb-8326-249b78db9cc8.png)
![image](https://user-images.githubusercontent.com/11279863/96131193-2bd5a780-0ef9-11eb-9659-e0beb0f7a313.png)

**Comment by hohnzy** [comment]
Playing a bit with the dataset and this is much more obvious
```
public treemapData = {
      name: 'Storage Utilization (78 GB)',
      children: [
      {
        name: 'by type',
        children: [
        {
          name: 'type1',
          children: [
            {name: 'JSON', value: 262171903987}
          ]
        }, {
          name: 'type2',
          children: [
            {name: 'PDF', value: 2621524675}
          ]
        }, {
          name: 'type3',
          children: [
            {name: 'BOD', value: 621020385}
          ]
        }, {
          name: 'type4',
          children: [
            {name: 'TXT', value: 29822693}
          ]
        }]
      }]
    };
```
also the labels are ugly, would be nice to have tooltips over areas
![image](https://user-images.githubusercontent.com/11279863/96132347-99ce9e80-0efa-11eb-88fd-8bc9e8aee632.png)

**Comment by tmcconechy** [comment]
Ok, Thanks i see the issue now with that data. By "ugly" you just mean the way its cut off right? Not so sure what we could do about that but i agree about the tooltips. I think we should add tooltips to the cells. For example

```
{
          name: 'type1',
          children: [
            {name: 'JSON', value: 262171903987}
          ],
          tooltip: 'test'
        }
```

**Comment by hohnzy** [comment]
Yes, would be great to be able to add tooltips this way!

**Comment by janahintal** [comment]
Noticed that the Label is cut off on other column. Had to confirm if this is also expected for the fix? 
https://master-enterprise.demo.design.infor.com/components/treemap/example-tooltips.html
![image](https://user-images.githubusercontent.com/45757016/97005182-adb87700-1570-11eb-963f-c18f4cde1f7c.png)

**Comment by tmcconechy** [comment]
Yes thats correct, the boxes wont fit because the slices are too small. So thats the data representation of how big it is. I added the tooltip so you can see the data that way.

**Comment by janahintal** [comment]
Thanks for the clarification, Tim. Will now move this to Done :)
