### ISSUE TITLE
Datagrid: Grouping - when adding a row to a group the group moves

### ISSUE THREAD

**Issue by slsheridan** [infor-design/enterprise#2801]
**Describe the bug**
In a datagrid that is groupable, when you add a row to a group, that group moves up to the top (however in my application, it always moves to the second group in the list).  

**To Reproduce**
1. Import this file (without .txt extension) into enterprise\app\views\components\datagrid folder and run the example.  This is a modified version of example-group-editable.html

[example-grouping-editable_groupmoves.html.txt](https://github.com/infor-design/enterprise/files/3618094/example-grouping-editable_groupmoves.html.txt)

2. Select a row in a group other than the first group.
3. Click the add button (+).
4. A new row is added to the group and that group is moved up to the top of the list of groups.

**Expected behavior**
When the new row is added, the group order should not change as I have populated the datagrid with the rows in the order I need to have them.  

**Version**

- ids-enterprise: v4.22.0

**Screenshots**
Before adding row:
![image](https://user-images.githubusercontent.com/48289278/64992045-14b12a00-d8a1-11e9-9a9c-e064f372b52e.png)

After adding row:
![MovedGroups](https://user-images.githubusercontent.com/48289278/64992802-a79e9400-d8a2-11e9-9071-e20be8e214a6.png)

**Platform**
  - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version 76.0.3809.132 (Official Build) (64-bit)

**Additional context**
**In my application, I have a refresh button that retrieves the data from the backend and sets the datagrid.data property to the returned result however the grid does not refresh as it used to prior to adding grouping.  I have tried to mimic that in the example.**

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to QA Failed. When the user clicks on page 2 and then any of the following:

    Top (in group)
    Bottom (in group)
    At Selected
    When I click on any of the three options on the second page nothing happens in the data grid.

**Comment by janahintal** [comment]
Failed upon testing for this scenario: 

1. Select 'Customer ID 1' in Hardware customer group
2. Goto the last Page 
3. Click 'Customer Id 4' in Hardware Prospect group 
4. Add a row (Top in Group)

Expected :
Both groups with selected Ids should have new rows. 

Actual Result :
Only Hardware Prospect group has the new row

**Comment by tmcconechy** [comment]
it is currently just adding them to the first selected group for demo purposes, but maybe this makes sense if we have time for the example.

**Comment by tmcconechy** [comment]
For now as we dont have much time, decided to skip your last point. It will only do it in this example on the first selected one. Its just an example so doesnt need to support multiple selections and we dont have time for that now
