### ISSUE TITLE
Lookup:The count doesnt update when filtering

### ISSUE THREAD

**Issue by nilamthakur** [infor-design/enterprise#2806]
Async data Lookup control count doesn't update for filtering. Its just showing total count we pass in.

**Describe the bug**
Async data Lookup control having issue at the time of search, record count results not get refresh.

**To Reproduce**
1. Set up your enterprise project ' https://github.com/infor-design/enterprise-ng.git’
2. Check  lookup-validation.demo example, In that “Products (Async Results)” lookup (please refer the screen ). 
3. Open the lookup, It will show the result as '7'. (please see the screenshot)
4. If we search for any value, it will show result for that but not updating count value for filter.

**Expected behavior**
The count should update for filtering.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

![image](https://user-images.githubusercontent.com/43470457/65154841-d99e2a80-da49-11e9-857a-e44776c3e7e5.png)
![image](https://user-images.githubusercontent.com/43470457/65154862-e3c02900-da49-11e9-91e8-b3939a4adc7d.png)

**Platform**
  - OS Version: Windows 10
 - Browser Name: Chrome, IE

**Additional context**

**Comment by ericangeles** [comment]
@tmcconechy, this ticket might also related https://github.com/infor-design/enterprise-ng/issues/758 ?

**Comment by janahintal** [comment]
This issue is now Resolved. Thank you. :) 
Verified in : https://master-enterprise.demo.design.infor.com/components/lookup/test-paging-server-side-keyword-search.html
![image](https://user-images.githubusercontent.com/45757016/85658484-e2f9a900-b6e5-11ea-8bc8-bcce4ccd0503.png)

**Comment by dhumalkishor** [comment]
Record count not get updated when there is no records found in search.
This issue is observed in 4.31.1 library.  You can reproduce this in below example of enterprise-ng.
http://localhost:4200/ids-enterprise-ng-demo/lookup

**Comment by dhumalkishor** [comment]
![L1](https://user-images.githubusercontent.com/42198413/91450705-37620600-e89a-11ea-9b7d-314aab4b83be.jpg)

**Comment by tmcconechy** [comment]
Ok i think this needs a new issue i think i can see it on https://master-enterprise.demo.design.infor.com/components/lookup/test-paging-server-side-keyword-search.html although its similar looks like when you type something that doesnt exist it isnt correct.

So make a new bug with steps to that page. Thanks
