### ISSUE TITLE
Deprecated code needs to be fixed in IDS

### ISSUE THREAD

**Issue by SasiPalanati** [infor-design/enterprise#2808]
We found these console errors in Saleshub.
IDS Enterprise: "toggleList()" is deprecated. Please use "toggle()" instead.
IDS Enterprise: "()" is deprecated. Please use "()" instead.

Component: toggleList

**Comment by SasiPalanati** [comment]
IDS version:v4.17.1

**Comment by tmcconechy** [comment]
This issue has been fixed if its just this. Try 4.21 and it should be gone.
Adding this to QA so they can note to look on the console for any deprecation errors they spot on the pages they test. This issue was in dropdown i believe so one place to focus tests

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done bucket.
