### ISSUE TITLE
Popupmenu: Destroy event is bubbling up to other controls since not using triggerHandler

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#2809]
**Describe the bug**
In the destroy function for the Popupmenu it is triggering a 'destroy' event on the menu element which is causing the event to bubble up to parent elements and cause bad problems in our app. I believe Soho's normal way is to use "triggerHandler" instead of "trigger" so that the event does not bubble up.

![image](https://user-images.githubusercontent.com/14128010/65246394-7ac5c900-dabc-11e9-986a-f29ef44367db.png)

**To Reproduce**
I found this bug in the CSD application where we had a colorpicker in a CAP modal. After using the colorpicker its popupmenu would close (be destroyed) and cause a destroy event to be triggered on the CAP modal. You may be able to reproduce the bug at this example if you add a listener on the modal for the 'destroy' event -> http://master-enterprise.demo.design.infor.com/components/colorpicker/test-modal.html

**Expected behavior**
Soho code should use "triggerHandler" instead of "trigger" to prevent event bubbling.

**Version**
v4.22.0

**Platform**
- Device: Dell Laptop
- OS Version: Windows 10
- Browser Name: Chrome
- Browser Version: 76.0.3809.132 (Official Build) (64-bit)

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/colorpicker/test-modal.html
Passed QA testing on all browsers, will retest once beta is deployed.
