### ISSUE TITLE
Toolbar Flex: When title wrapped in a span, width set to 250px

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2810]
**Describe the bug**
There is a CSS rule in [_toolbar-flex.scss](https://github.com/infor-design/enterprise/blob/master/src/components/toolbar-flex/_toolbar-flex.scss#L66) that sets the width of a title in a span to 250px. This is causing a title to be truncated when there is enough space for it.

**To Reproduce**
1. Copy [test-header-like-title-in-span.zip](https://github.com/infor-design/enterprise/files/3632119/test-header-like-title-in-span.zip) into \app\views\components\toolbar-flex.
2. Navigate to /components/toolbar-flex/test-header-like-title-in-span.html
3. See error

**Expected behavior**
Title is truncated when there is plenty of space for it

**Version**

- ids-enterprise: 4.22.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/65259125-ca5ec180-dac9-11e9-8347-28f01802f42d.png)

**Platform**
 - All

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/toolbar-flex/test-header-like-title-in-span.html
Passed QA testing in all browsers.
![image](https://user-images.githubusercontent.com/39508864/66111172-eea6bc00-e5fa-11e9-8e45-8e3910434c38.png)
