### ISSUE TITLE
Application: Menu tooltip shows white text on white background on default theme color.

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#2811]
**Describe the bug**
Application menu tooltip shows white text on white background with on default theme color.

**To Reproduce**
1. Go to http://4210-rc0-enterprise.demo.design.infor.com/components/applicationmenu/test-personalized-role-switcher-long-title.html
2. Toggle the role switcher on the right top corner of application menu.
3. Hover over the title with "..." 
4. Also seeing on https://4200-enterprise.demo.design.infor.com/components/applicationmenu/test-personalized-role-switcher-long-title.html that the ... is not there.
4. See tooltip box in white background and white text - unreadable

**Expected behavior**
Tooltip on default color should show a different background color than white so text is readable.

**Version**

- ids-enterprise: v4.19.0-dev.20190424

**Screenshots**
![image](https://user-images.githubusercontent.com/39130590/65259476-5670e900-daca-11e9-80c9-8407dcf59dab.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-personalized-role-switcher-long-title.html
Passed QA testing on all browsers.
![image](https://user-images.githubusercontent.com/39508864/65502137-ccbf8200-def4-11e9-8d29-5ab669c79316.png)
