### ISSUE TITLE
Personalize: Duplicate theme classes added to HTML element when setting theme

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise#2817]
**Describe the bug**

Manually setting the default theme, by appending the class to the HTML element, causes multiple class entries in the HTML element for different themes.  

**To Reproduce**

This can be seen in the angular demo application adding:

```html
<html lang="en" class="theme-uplift-light" >
```
Running the application causes three classes to be present:

```html
<html lang="en-US" class="theme-uplift-light is-chrome theme-soho-light theme-uplift-dark" data-sohoxi-version="4.21.0-dev" data-ids-enterprise-ng-version="6.1.0-dev.20190916"><link type="text/css" id="dark-mode" rel="stylesheet" href=""><style type="text/css" id="dark-mode-custom-style"></style><head>
```

**Expected behavior**

Only one theme should be present, that is the one loaded.

**Version**

6.1.0 of NG and 4.21 of EP.

**Screenshots**

**Platform**
**Additional context**

**Comment by bthharper** [comment]
I would not be setting the theme this way normally, however the ticket is to follow up on a thread on MS Teams where a developer wanted to set the default theme without using the theme api.

**Comment by tmcconechy** [comment]
Also note to self.
- test setting theme by style sheet in the head in NG and EP
- fix the duplicate classes issue here as can bee seen in the demo app by adding a theme class to head.html

**Comment by tmcconechy** [comment]
Descoping this as its irrelevance in 5.0 code as all themes are self contained
