### ISSUE TITLE
Input: time validation failed because he-IL time format changed

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#2818]
**Describe the bug**
Since version 4.19, `timeFormat `value in **he-IL** locale changed from 'HH:mm' to 'H:mm', however, the `is24Hour `variable is checked against 'HH' and therefore the validation for 24 hours format fails.
I also noticed that cultures **es-ES** and **es-MX** changed as well from 'HH:mm' to 'H:mm', but **es-AR** (in 4.21) is 'HH:mm'

I don't really know what is the difference between the patterns js wise.
The he-IL, I believe, should be as Europe (France, Italy, etc), thus 'HH:mm'.

**To Reproduce**
Add input, for example:
`<input type="text" " class="input-mm new-mask" value=""
 placeholder="hh:mm"
 data-options='{ "process": "date", "patternOptions": { "format":"HH:mm" } }'
data-validate="time" 
/>`
Change locales, and try to type 13:00
(this exact input validated correctly before v4.19 - users started complaining after version upgrade that they cannot enter times larger than 12)

**Expected behavior**
Time validation should work when typing 24 hours time.

**Version**
Since v4.19.0

**Screenshots**
![he-il-timeFormat](https://user-images.githubusercontent.com/34129313/65384253-c4b2e700-dd28-11e9-97da-5a83d947937f.PNG)

**Platform**
 - OS Version: Windows 7+
 - Browser Name: Chrome
 - Browser Version: Latest

**Additional context**
Thanks!

**Comment by tmcconechy** [comment]
FYI HH means pad with a leading zero fx 6:00 would be 06:00
I think this changed when i synced up with the CLDR http://cldr.unicode.org/

**Comment by janahintal** [comment]
QA Passed. Will move to Done. 
Verified http://master-enterprise.demo.design.infor.com/components/mask/example-index.html across all platform
