### ISSUE TITLE
SwapList: Items sent to 'beforeswap' event after search do not match selected item

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#2819]
**Describe the bug**

The items object passed to the SwapList 'beforeswap' event do not match what is selected when the search feature is used.

This means that any validation/processing code we have written in the 'beforeswap' fails as the wrong item list is sent. The documentation for 'beforeswap' states that the 2nd parameter will contain 'List of selected items data'. It look like it is using data from the *full* list rather than the filtered list to pass data to 'beforeswap'.

**To Reproduce**
1. Take the standard "Swaplist with Filter/Search" example page: https://design.infor.com/code/ids-enterprise/latest/demo/components/swaplist/example-search
1. Edit the source so that it has a 'beforeswap' event; e.g. after initialising the swaplist, add...

```
$('#example-swaplist-1').on('beforeswap', function(e, obj) {
      		  window.console.log('Selected Items: ' + JSON.stringify(obj));
          });
```
1. Open this new test page in a browser, I used Chrome on Windows 8.1
1. Open Developer Tools in your browser and view the Console
1. In the left-side search/filter box, enter DD
1. Filter is applied to show only "Option DD" on the left
1. Select/highlight 'Option DD' then click the move right icon
1. In the display, the correct option is moved to the right 
1.In the console, look at the output. Instead of "Option DD" inthe object text it says...

```
Selected Items: {"items":[{"id":1,"value":"opt-1","text":"Option AA","node":{"0":{},"length":1},"isFiltered":false}],"from":{"container":{"length":0,"prevObject":{"0":{},"length":1}},"class":""}}`
```

This happens for other filtered items.

**Additional context**

This is a show-stopper for us. We need to upgrade IDS to get a fix for a previously logged Excel Export problem, which is a customer-raised issue, but we cannot upgrade if it breaks existing functionality in other areas.

**Comment by tmcconechy** [comment]
For further information: What version did this work in that you had previously?

**Comment by tmcconechy** [comment]
We'll take a look. Added to the current sprint

**Comment by sanx72** [comment]
Our GA release, where the swaplist function was OK, is using IDS 4.14

**Comment by janahintal** [comment]
QA  Passed. Will move to done. 

Verified  in: http://master-enterprise.demo.design.infor.com/components/swaplist/test-beforeswap-with-search.html
![image](https://user-images.githubusercontent.com/45757016/65660265-c0583800-e060-11e9-8e26-386c819a7161.png)
