### ISSUE TITLE
Accordion: focus styling remains when clicking headers (in safari)

### ISSUE THREAD

**Issue by gushanson** [infor-design/enterprise#282]
**Describe the bug**
The blue focus styling remains on a clicked header even after another header has been clicked.

**To Reproduce**
- Go to url: http://master-enterprise.demo.design.infor.com/components/accordion/example-index.html
- Click Warehouse Location header
- Click Sort By header
- Click brand name header

**Expected behavior**
The Warehouse Location is not styled as focused.

**Actual behavior**
The Warehouse Location is styled as focused.

**Additional context**
Version 4.7.0
**Safari only**

**Comment by tmcconechy** [comment]
This is actually correct we have two types.

Panel-style
http://master-enterprise.demo.design.infor.com/components/accordion/example-accordion-panels.html
- used for navigation/selection

In-page / Traditional
http://master-enterprise.demo.design.infor.com/components/accordion/example-index.html
- just has expandable sections and content inside.
- focus the headers to activate 

So this example is correct.

**Comment by gushanson** [comment]
![selected](https://user-images.githubusercontent.com/4129417/42166912-be0372de-7e0c-11e8-90cb-2b7cac222c97.png)
What I'm seeing is the scenario in the image. I sthis really by design?

**Comment by tmcconechy** [comment]
That is an older link. How did you get that? By clicking each one at a time as im not seeing that here o the latest link (Pre 4.8.0)

http://master-enterprise.demo.design.infor.com/components/accordion/example-index.html

**Comment by tmcconechy** [comment]
OK, Nevermind i do see that on safari. I'll reopen.

**Comment by ericangeles** [comment]
I also noticed that the button arrow is also focused in safari(v.11.1.2) when toggling. But in the other browsers looks fine.

<img width="712" alt="screen shot 2018-08-30 at 10 25 55 am" src="https://user-images.githubusercontent.com/8839327/44825907-46783400-ac3f-11e8-9242-b8241208c1ee.png">

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/accordion/example-index.html
Passed QA testing. Bug fix is working as expected on Safari.
