### ISSUE TITLE
Search Field: Search value is not displayed

### ISSUE THREAD

**Issue by VINAYREDDY59** [infor-design/enterprise#2820]
**Describe the bug**
Search value is not displayed in search field while we click out side the search field.

**To Reproduce**
1. Go to soho toolbar flex with search included in it.
1. Click on search icon.
1. Type the search term
1. Now click out side.
1. observe that the search term is not visible anymore.
1. Now again click on search icon and see the search term exists there.

**Expected behavior**
The search term should be visible even if we out focus/click outside.

**Screenshots**
Search the text
![image](https://user-images.githubusercontent.com/31958563/65417968-ec817800-de18-11e9-888b-a9a6edf64cfa.png)

We applied an effect to highlight the search. The search term highlights but the search term is not visible in the search field.
![image](https://user-images.githubusercontent.com/31958563/65417986-fa36fd80-de18-11e9-9cd6-4950b10d9255.png)

**Additional context**
It works for Inbox which uses the same shared component.
![image](https://user-images.githubusercontent.com/31958563/65418151-716c9180-de19-11e9-8809-cc730b82c1ee.png)

I have noticed that the issue is about responsiveness. When i switch Inbox application to mobile view the issue exists.
![image](https://user-images.githubusercontent.com/31958563/65418241-9f51d600-de19-11e9-86d1-f50a997efe52.png)

**Comment by tmcconechy** [comment]
@VINAYREDDY59 Where is the example "Go to soho toolbar flex with search included in it." located?

**Comment by VINAYREDDY59** [comment]
Hi @tmcconechy ,
Please look at this component in mobile view.
http://master-enterprise.demo.design.infor.com/components/toolbar-flex/example-searchfield-collapsible.html
![image](https://user-images.githubusercontent.com/31958563/65429964-b0f4a700-de34-11e9-8f25-245a65bfcbf6.png).

**Comment by tmcconechy** [comment]
When on mobile size the search field will auto collapse. It has to do this or the buttons cannot be interacted with. 

This is the default behavior.

What you could do is make the search field non collapsible by a setting but then you wont be able to have any buttons.

**Comment by EdwardCoyle** [comment]
@VINAYREDDY59 For both of your use cases, I'd suggest:
- Make the Searchfield non-collapsible (pass it a setting of `collapsible: false`)
- Set a static width on the Searchfield to shorten it just enough that your buttons stay visible.  It appears that both the inbox list view and the card example are fixed-width containers, which this setup will work well in.

**Comment by tmcconechy** [comment]
Another suggestion is to use the search feature integrated with the list view. http://master-enterprise.demo.design.infor.com/components/listview/example-search.html so basically have a toolbar with no search and the listview search underneath so both are visible.
