### ISSUE TITLE
Vertical Tabs: When in .is-in-responsive-mode and .is-personalizable then don't apply the .alternate class

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2824]
**Is your feature request related to a problem? Please describe.**
At the moment `.alternate` is being applied in tabs.js when tabs are vertical whether responsive or not. This causes the `.is-personalisable` background theme color to be overridden by the `.alternate` class. 

**Describe the solution you'd like**
Vertical tabs should participate in `.is-personalisable` (and use the theme background color) when in responsive mode (`.is-in-responsive-mode`). 

For an example of the mark that could be used see

http://master-enterprise.demo.design.infor.com/components/tabs-vertical/example-responsive.html

Add `is-personalizable` to the tab-container. 
      <div id="tabs-vertical" class="vertical tab-container no-scroll `is-personalizable`" data-options='{ "verticalResponsive": true }'>

The result should look like it does now when tabs are vertical
![image](https://user-images.githubusercontent.com/4737815/65456315-a58e8500-de0e-11e9-8432-33476200da48.png)

 but like the screenshot here when they are responsive 

![image](https://user-images.githubusercontent.com/4737815/65456231-7c6df480-de0e-11e9-8428-fc2a07c5ee18.png)

**Comment by tmcconechy** [comment]
We should try and do this early on or in 4.22 if time becomes available.

**Comment by davidcarlsonberg** [comment]
@tmcconechy Is this a bug or a feature request?

**Comment by tmcconechy** [comment]
A bit of both - but mainly a feature i guess as we had done this for other situations / components but not this particular combination.

**Comment by janahintal** [comment]
QA Passed. Will move to Done
Verified in http://master-enterprise.demo.design.infor.com/components/tabs-vertical/example-responsive.html?theme=uplift&variant=light&colors=0563C2
