### ISSUE TITLE
Contextual Action Panel: Bubble up beforeclose event.

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#2826]
**Describe the bug**
When cancel button is clicked and contextual action panel is closed, 'beforeclose' event is not fired. The dialog has vetoable events, but the contextual panel does not. 

**To Reproduce**
1. Open any sample for contextual action panel.
2. Click escape to dismiss the panel.

**Expected behavior**
beforeclose event is not bubbled up. If the form has  pending changes, a confirmation message is usually displayed before discarding the changes. If the user clicks the cancel button, the cancel button click handler is used to display the confirmation message. But when the user clicks the escape button, beforeclose event handler is where the form dirty check can be performed.

**Version**

- ids-enterprise: v4.22.0-dev

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-beforeclose.html
Passed QA testing in all browsers, will retest once beta is deployed.
