### ISSUE TITLE
Datagrid: The minWidth doesn't work with the stretchColumn

### ISSUE THREAD

**Issue by MickalWang** [infor-design/enterprise#2828]
**Describe the bug**
I set the specific column as stretch column in the dataGrid since users will use 'Personalize Columns' function. I set the minWidth for this stretch column  and fixed width for other columns so I think if the user adds more and more columns in the dataGrid, the horizontal scroll bar could display to show the selected columns. However, before the horizontal scroll bar appear, the width of the stretch column become smaller and smaller until it disappear in the dataGrid. After the stretch column disappear completely,  horizontal scroll bar appear.

**To Reproduce**
1. Set a specific column as stretchColumn for the dataGrid.
2. Set the minWidth for the stretch Column and fixed width for other columns in the dataGrid. 
3. Set Part of columns as hidden so that these columns don't be displayed when the dataGrid is loaded.
4. Use Personalize Columns to add more and more columns to the dataGrid.
5. The width of stretch Column become smaller until it disappear in the dataGrid.

**Expected behavior**
The width of stretch Column become smaller when the user adds columns by using Personalize Columns. But the width of stretch Column will not smaller than the minWidth. Horizontal scroll bar will appear once the dataGrid can't display the selected columns completely.

**Version**
- ids-enterprise: v4.21.0

**Screenshots**
![Error1](https://user-images.githubusercontent.com/33276468/65490650-223d6400-dee0-11e9-8112-8cb0f2c7f962.png)
![Error2](https://user-images.githubusercontent.com/33276468/65490667-279aae80-dee0-11e9-83c6-07f7fdea0d31.png)

**Platform**
 - OS Version: Windows 10 Enterprise
 - Browser Name : chrome
 - Browser Version : 76.0.3809.132 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Descoping some older issues
