### ISSUE TITLE
Toolbar button click does not dismiss application menu on mobile.

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#2831]
**Describe the bug**
Toolbar button click does not dismiss application menu on mobile.

**To Reproduce**

Go to http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html
Open Developer Tools - Toggle Device toolbar to iPhone
Click on the toolbar button, it should dismiss the menu.

**Expected behavior**
Clicking toolbar button on application menu on mobile should dismiss the menu.

**Version**

- ids-enterprise: v4.19.0-dev.20190424

**Screenshots**
![GIT#2831](https://user-images.githubusercontent.com/39130590/77338807-dafe2780-6cf8-11ea-8646-3e9267fb217e.gif)

**Platform**
 - Device: iPhone 6/7/8

**Comment by tmcconechy** [comment]
I'm not 100% convinced it should always close when clicking the toolbar buttons? Perhaps it's better you do this if needed in your code you use to handle the buttons?

**Comment by tmcconechy** [comment]
Ok, yeah that makes sense i think if dismissOnClickMobile is true then these also can close.

**Comment by EdwardCoyle** [comment]
This ended up being related to Popupmenu trigger buttons, not specifically Toolbar-related.  I've put the change there and it seems to work nicely.

**Comment by janahintal** [comment]
QA Passed. Working as expected. Will move to Done. Thanks. 
Verified in http://4220-beta0-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher across all platform.

**Comment by vonnyw** [comment]
This issue still persists, it is not the same as #2890. Please see attached recording.

**Comment by tmcconechy** [comment]
Can you make an new issue then? If its "not the same". I think that makes more sense. Video missing.

**Comment by vonnyw** [comment]
This issue is #2831, but was linked and closed by #2890 although they are not the same issues. Video has been added.

**Comment by tmcconechy** [comment]
Where is the video?

**Comment by vonnyw** [comment]
The .gif recording was added to the Screenshots part of this issue description.

**Comment by tmcconechy** [comment]
OK is that a different video? I just looked at it again and before it showed clicking the toolbar button on the outside of the dialog.

**Comment by vonnyw** [comment]
Hmm, not sure which video you are referring to. I included both issues on the .gif to illustrate they are 2 different issues. Toolbar button on content area vs. toolbar button on application menu header.

**Comment by tmcconechy** [comment]
Ok i feel like the video was switched on me. But ok i see the issue as shown.

**Comment by jbrcna** [comment]
**QA Passed**
The issue is now resolved in v4.29.0-dev. this is working as expected in `Developer Tools - Toggle Device toolbar` and `Browserstack Mobile devices`
https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html?
