### ISSUE TITLE
Datepicker: mask is lost after updated is called

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2832]
**Describe the bug**
The mask on a date picker is lost after updated is called on the component.

The teardown method is causing this.element.data('mask') to return "" instead of undefined, so the mask doesn't get re-inited [here](https://github.com/infor-design/enterprise/blob/master/src/components/datepicker/datepicker.js#L418).

**To Reproduce**
1. Copy test-mask-after-update
[test-mask-after-update.zip](https://github.com/infor-design/enterprise/files/3648059/test-mask-after-update.zip) into app/views/components/datepicker.
2. Navigate to '/components/datepicker/test-mask-after-update.html'
3. Enter some numbers manually into the field, see that slashes are automatically put in and the date is formated
4. Clear out the field, and click the updated button
5. Enter some numbers manually into the field, see that no slashes are added and no formatting occurs.

**Expected behavior**
The mask should still work after updated is called on the datepicker component.

**Version**

- ids-enterprise: v4.22.0-dev and earlier

**Screenshots**
![DatepickerMaskIssue](https://user-images.githubusercontent.com/22107636/65527779-daefad00-deb8-11e9-9f5d-1b30b87c3b9e.gif)

**Platform**
 - All

**Comment by tmcconechy** [comment]
The problem is here https://github.com/infor-design/enterprise/blob/master/src/components/datepicker/datepicker.js#L418 as after the component is detroyed the mask variable is set to empty string not undefined and will never reinvoke the mask.

The fix should be to move this line https://github.com/infor-design/enterprise/blob/master/src/components/datepicker/datepicker.js#L1639

Down a bit to after https://github.com/infor-design/enterprise/blob/master/src/components/datepicker/datepicker.js#L1654

And set it to undefined not empty string. Seems like even the mask is not getting destroyed.

**Comment by pwpatton** [comment]
@lipetzan I know this is in our upcoming release to customers.  Which I believe uses EP 4.21. Do we need a patch for this or can it wait until next CU?

**Comment by tmcconechy** [comment]
Just let me know asap i can do either a 4.21 patch or just add it in 4.22 which freezes EOM

**Comment by lipetzan** [comment]
Please add some unit tests for form field masks.  Adding a tag for that.

**Comment by tmcconechy** [comment]
There are tests for mask but not the case of doing a destroy and then reinvoking. Adding a test on the PR... Incomming

**Comment by tmcconechy** [comment]
We added a tag "for customer". We didnt want to increase the number of tags as we have a system. 
What are these new two tags for?

**Comment by tmcconechy** [comment]
Removing these new tags as they dont make sense to us. But let me know what the purpose as and we can try to fit it into our system

**Comment by pwpatton** [comment]
`There are tests for mask but not the case of doing a destroy and then reinvoking. Adding a test on the PR... Incomming`

@tmcconechy We probably need test for all components updated() functions that destroy and then reinvoke.

**Comment by tmcconechy** [comment]
That would be a separate issue. Feel free to raise.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datepicker/test-mask-after-update.html
Passed QA testing in all browsers. Also retested http://master-enterprise.demo.design.infor.com/components/datepicker/example-validation.html.
