### ISSUE TITLE
Contextual Action Panel: Close button

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#2834]
**Describe the bug**
A close button is added to the contextual action panel when showCloseButton is set. But the close button is added to the modal header and not the button set of the toolbar as in the demo used to test for issue #1943.
The close button actually wraps around and appears below the header. Also, the text 'Close' is partially visible.

**To Reproduce**
In any contextual action panel sample,
(1) set showCloseButton to true
(2) add four buttons so an overflow button is displayed in the toolbar
(3) Bring up the contextual action panel

**Expected behavior**
The close button is on the top right corner of the contextual action panel. It is just an icon button with no text.

**Version**

- ids-enterprise:  v4.22.0-dev

**Screenshots**

**Platform**
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version Version 77.0.3865.90

**Additional context**

**Comment by aaralikar** [comment]
![image](https://user-images.githubusercontent.com/22720894/65548137-83653780-dee0-11e9-9a89-c7bfcfc11b96.png)

**Comment by Sovia** [comment]
When @aaralikar and I were looking at this, we noticed that 'Close' was hard coded, instead of translated.

**Comment by EdwardCoyle** [comment]
@Sovia @aaralikar just making a note here that PR #2984 should address this.  I had read the history on this a bit and noticed this comment in the original ticket #1943:

> **Expected behavior**
> The close button is on the top right. And the toolbar overflow button is to its left.

Just noting that the fact that the close button is not sitting to the right of the more button is due to the limitations of how the original standard Toolbar was built.  We addressed this alignment issue with Flex Toolbar, which is fully implemented in the Contextual Action Panels, and allows separate toolbar section(s) to the right of the more menu.  If you need to display the close button outside the overflow menu, I recommend switching to Flex Toolbar.  PR #2984 has a couple tests demonstrating how it can be implemented.

**Comment by jbrcna** [comment]
Test FAILED

Chrome, Safari, EDGE, Firefox

1. test-close-button-flex : responsive view 320x 568, 375 x 667
2. test-close-button-flex-from-settings  : responsive view 320x 568, 375 x 667


see screenshot below for reference
<img width="504" alt="image" src="https://user-images.githubusercontent.com/56722184/67384588-05ba4780-f5c4-11e9-90c5-ee532094aed7.png">


Other Context:
**IE11 works perfectly fine**

Also, 

Modals should also be tested for accuracy:
**modal/example-close-btn**: the tooltip for close button/icon kind of like stays for almost to 1sec after clicking the ‘X’ icon

**Comment by jbrcna** [comment]
Here's a screenshot for **IE11**
<img width="457" alt="image" src="https://user-images.githubusercontent.com/56722184/67385752-431fd480-f5c6-11e9-90de-721569ff57aa.png">

**Comment by tmcconechy** [comment]
@jbrcna Can you clarify the problem and steps to reproduce? The screen shots seem ok except maybe the misplaced scrollbar? Also the tooltip not closing is a non issue. So im not sure what the fail is here 100%

**Comment by tmcconechy** [comment]
OK im thinking we definitely punt on this then?

**Comment by EdwardCoyle** [comment]
It's a quick fix I could make during the beta.  We can toss it into Q/A fixes for 4.23.0-beta/rc/etc

**Comment by jbrcna** [comment]
@tmcconechy the second screenshot (which is IE11) works fine and that should be the expected result. whereas in the first screenshot, the 'X' icon is not appearing thus, you cannot close the contextual action panel.

**Steps to replicate:**
1. Open Chrome browser
2. Navigate to http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-close-button-flex?theme=uplift
and/or
http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-close-button-flex-from-settings?theme=uplift
3. Click Contextual Action Panel
4. Resize Browser window to  320x 568
5. Notice that you cannot click the 'X' icon
6. See screenshot below for reference

**iPhone XS**
<img width="366" alt="image" src="https://user-images.githubusercontent.com/56722184/67448338-4314e880-f649-11e9-8f2b-a7b76b719c7c.png">

**Safari**
<img width="512" alt="image" src="https://user-images.githubusercontent.com/56722184/67448513-c46c7b00-f649-11e9-92df-a7a09d8591b3.png">

**Comment by tmcconechy** [comment]
An updated fix has been merged to master

**Comment by jbrcna** [comment]
Test PASSED

Verified in http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-close-button-flex?theme=uplift
and/or
http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-close-button-flex-from-settings?theme=uplift
