### ISSUE TITLE
Datagrid: misalligned headers and rows

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#2835]
**Describe the bug**
The vertical lines dividing columns are misalligned in header row and result rows when vertical scroll appears

**To Reproduce**
1. I've reproduced in ng demo app
2. Go to Datagrid - Fixed header
3. Select 10 or 5 records per page
4. Be sure that all rows are visible so there is no vertical scrollbar in grid
5. Now change the window size, so the vertical scrollbar appears.
6. Observe, that you can go a bit further to the right now (width of scrollbar)

**Expected behavior**
All lines should be aligned correctly

**Version**

- ids-enterprise: 4.22.0
- ids-enterprise-ng: 6.1.0
- windows only?

**Screenshots**
![image](https://user-images.githubusercontent.com/11279863/65604088-1ec0e000-dfa7-11e9-903c-f3d76d2dca9f.png)

**Comment by tmcconechy** [comment]
Related to #1818 (possibly) and #2825

**Comment by brianjuan** [comment]
http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-filter.html
Passed QA on all browsers. Moving to Done.
![image](https://user-images.githubusercontent.com/39508864/70709874-ebc1f900-1d18-11ea-8d03-ab5cfdbd6b13.png)
