### ISSUE TITLE
Contextual Action Panel Control: Contextual Action Panel will not show up after you closed and reopen it

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#284]
**Describe the bug**
Contextual Action Panel will not show up after you closed and reopen it

**To Reproduce**
1. Go to url: http://480-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-markup.html
2. Click "Open Contextual Action Panel" button
3. Press Escape key to close the modal
4. Click "Open Contextual Action Panel" button again
5. Contextual Action Panel will not show up

**Expected behavior**
Contextual Action Panel should show up

**Screenshots**
None

**Platform**
 
 - All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
@EdwardCoyle this might be very similar to #283

**Comment by EdwardCoyle** [comment]
@tmcconechy  Not really the same thing at all... Some of the CAP examples have been this way for some time and we haven't really sorted out why.  Should keep this one open.

**Comment by tmcconechy** [comment]
OK i thought your pr did that...

**Comment by EdwardCoyle** [comment]
Nope, #222 was the original issue -- deals with adding close buttons.

This one is different because I think there are scenarios where a CAP is supposed to not re-open, because it's supposed to be destroyed.  It's not clear in the tests which ones are supposed to do that.

**Comment by tmcconechy** [comment]
Yes, i remember this - i think in the situations where you provide the markup entirely. I believe i looked at this before but never came to a conclusion. Maybe an option of "removeMarkup on destroy" could be added.

**Comment by tmcconechy** [comment]
Closing this as a dup of 
https://github.com/infor-design/enterprise/issues/506
