### ISSUE TITLE
Datagrid: Request a mechanism to conditionally show browser's context menu

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2842]
Describe the feature:
When the user opens the contextmenu for a cell in the datagrid containing a hyperlink, Landmark wants to display the browser's default menu.  The user wants access to items found in the browser's default context menu like 'Copy link address' or 'Open link in a new tab'.

We could achieve this in 3.5, because handleContextMenu(e) within inforControlsCombined.js was not performing a preventDefault().

In 4.0, both the handler for the contextmenu event (.on('contextmenu.datagrid')) and triggerRowEvent are performing a preventDefault().

Describe the solution you'd like
Provide a column callback function or something were we can conditionally show the browser's default menu.

Describe alternatives you've considered
Unable to provide a solution within Landmark since sohoxi.js is performing the preventDefault().
 
**Additional context**
Attached gif files of how it works in 3.5 and 4.0.
Attached an example to help illustrate.

https://jira.lawson.com/browse/LMCLIENT-25259

**Comment by claudenbach** [comment]
[Git-2842.zip](https://github.com/infor-design/enterprise/files/3654856/Git-2842.zip)
![ContextMenu4 0](https://user-images.githubusercontent.com/39804038/65641128-95fb7180-dfb1-11e9-8260-ff16d505ca2b.gif)
![ContextMenu3 5](https://user-images.githubusercontent.com/39804038/65641133-98f66200-dfb1-11e9-8e5c-8c862b69ac4b.gif)

**Comment by tmcconechy** [comment]
Not sure i understand the use case. Is it to allow the browser menu on one cell and a custom menu on another at the same time?

**Comment by claudenbach** [comment]
Want the ability to show the default browser menu for a cell containing a link for the context menu.  Otherwise the custom context menu is shown.  

Look at the 3.5 gif file for an example.

**Comment by janahintal** [comment]
QA Failed. 

Custom context menu is not working in iOS mobile. 
1. Open iOS device and Go to http://master-enterprise.demo.design.infor.com/components/datagrid/test-contextmenu-on-specific-columns.html?theme=uplift&variant=light&colors=0563C2
2. Select and hold any record in Activities 


![image](https://user-images.githubusercontent.com/45757016/68292085-1ab7d000-00c6-11ea-9419-b5473ffcb118.png)

**Comment by tmcconechy** [comment]
@janahintal - going to ignore this point as this will not work the way you expect here on mobile. This is actually what the mobile menu will look like. So i think this is working as best it can for now.
