### ISSUE TITLE
Locale: getCulturesPath fails to set the correct URL for the locale if the path contains "sohoxi"

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#2844]
In our web application, we copy and deploy the IDS code to a sub-folder called "sohoxi". The URLs that load SoHo Xi controls are like this...

```
https://server.infor.com/systemi/static/sohoxi/js/jquery-3.4.1.js
https://server.infor.com/systemi/static/sohoxi/js/d3.v4.js
https://server.infor.com/systemi/static/sohoxi/js/promise-polyfill.js
https://server.infor.com/systemi/static/sohoxi/js/sohoxi.js
https://server.infor.com/systemi/static/sohoxi/js/sohoxi-migrate-4.4.0.js
```

In all versions prior to 4.0.21, this was fine.

In version 4.0.21, the locale no longer loads. This is due to the change to getCulturesPath to "check" the URL using a regular expression and set the culturesPath variable. This regex does not take into account that a sub-folder in the URL path may be called, or have the words "sohoxi" in it.

```
const partialPathRegexp = /sohoxi(.min){0,1}(.{0,1}[a-z0-9]*).js/;
```

This matches against the folder multiple times, not the file...

![image](https://user-images.githubusercontent.com/44396995/65683059-3f933f00-e054-11e9-8d4a-6e077c5555bd.png)

What I think you may have intended to use was this regular expression, to match the .js extension...

```
const partialPathRegexp = /sohoxi(.min){0,1}(.{0,1}[a-z0-9]*)\.js/;
```

![image](https://user-images.githubusercontent.com/44396995/65683163-7e28f980-e054-11e9-990d-e08c6ce08e9b.png)

This happens in all browsers.

**Comment by tmcconechy** [comment]
This is due to the changes on https://github.com/infor-design/enterprise/issues/2637

@sanx72 So your saying just change https://github.com/infor-design/enterprise/blame/c5c2e2ed52c0fbd49792e9f9ec1cb0ca57ddd7c9/src/components/locale/locale.js#L121 to `const partialPathRegexp = /sohoxi(.min){0,1}(.{0,1}[a-z0-9]*)\.js/;` should fix?

@guoliang - what do you think about the proposed change?

**Comment by sanx72** [comment]
If the intention was to match for a file path ending in ".js" then the Regex is erroneous as "." in Regex is a special character that matches against any character (https://www.regular-expressions.info/dot.html), which is why you need to escape it. 

If it is genuinely meant to be a RegEx "dot" to match any character, then I'm not sure what it was for and you'd need the original developer to explain.

**Comment by tmcconechy** [comment]
It was intended to fix has paths on https://github.com/infor-design/enterprise/issues/2637 and was a contribution by @guoliang , so waiting for comments.

**Comment by guoliang** [comment]
Oh yes, that's looks to be missing part from my side. The dot should be escaped of course.
You want me to make a PR for that?

**Comment by tmcconechy** [comment]
That would be great @guoliang 👍

**Comment by tmcconechy** [comment]
This can be tested on npm nightly 4.22.0-dev.20191002
