### ISSUE TITLE
Datagrid: List Style header and cells seem to be 1px off

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#2849]
**Describe the bug**
Header and cells not aligning perfectly

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-list.html?theme=uplift
2. inspect dom and notice border around cells adding extra pixel of padding

**Expected behavior**
cell and header text should perfectly align left (as possible) 

**Version**
4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/4737815/65718246-cb16cb00-e068-11e9-89f3-34a838ca9f87.png)

**Comment by pwpatton** [comment]
![image](https://user-images.githubusercontent.com/4737815/65718556-64de7800-e069-11e9-8e27-9d9bc7bd23d7.png)

Seems to be a problem with standard datagrid style as well.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/example-list.html
http://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html
Header and cells are now aligned in Normal row height, but I noticed that in Short and Medium row heights, alignment is still 1px off. 

Short row height
![image](https://user-images.githubusercontent.com/39508864/66910728-b2834a80-f041-11e9-8214-cd10e413a52f.png)

**Comment by tmcconechy** [comment]
@ericangeles think you can update this for all row sizes?

**Comment by ericangeles** [comment]
Yep! Will do the fix for this.

**Comment by brianjuan** [comment]
https://master-enterprise.demo.design.infor.com/components/datagrid/example-list.html
https://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html
Passed QA on all browsers.
![image](https://user-images.githubusercontent.com/39508864/67835766-c771da80-fb25-11e9-9be5-074cf6fbd49e.png)
