### ISSUE TITLE
Contextual Action Panel Control High Contrast And Buttons Not Working Issues

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#285]
**Describe the bug**
Gray spaces at the bottom of the contextual action panel when on High Contrast theme and Cancel and Submit buttons not working

**To Reproduce**
1. Go to url: 480-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-workspaces.html
2. Switch to High Contrast theme under the (…) Menu
3. Click Show Contextual Action Panel button
4. Notice the gray spaces at the bottom of the contextual action panel
5. In addition, the "Cancel" and "Submit" button is not working. The user needs to click on the escape key to get out of the pop up window

**Expected behavior**
High contrast should appear correctly
The Cancel and Submit button should close the pop up window

**Screenshots**
<img width="1144" alt="contextual panel high contrast" src="https://user-images.githubusercontent.com/39101346/41991668-3fc75d28-7a14-11e8-82cf-e30ce592104d.png">

**Platform**

 - All Browsers 

**Additional context**
None

**Comment by CindyMercadoReyes** [comment]
On WIn 10 IE 11, using URL: http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/example-workspaces.html
The "Show Contextual Action Panel" does not pop up. The screen just turns a dark gray. Please see screen shot attached. 

![bs_win10_ie_11 0 1](https://user-images.githubusercontent.com/39101346/48374325-870a1a00-e692-11e8-8f65-783e922f22e8.jpg)

**Comment by tmcconechy** [comment]
Seeing an error in the console: `Object doesnt support property or method `from`` maybe this is why?

**Comment by ericangeles** [comment]
Agreed. I am seeing this error too in browserstack IE.

**Comment by EdwardCoyle** [comment]
#1244 and #1252 should have this one totally fixed

**Comment by tmcconechy** [comment]
I moved this to retest on the RC build as it does seem to be fixed on that branch but the fix does not seem to be in 4.13. beta 0 yet.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
