### ISSUE TITLE
Accordion: Header stays selected in Safari

### ISSUE THREAD

**Issue by shane-infor** [infor-design/enterprise#2851]
**Describe the bug**
Accordion header stays selected even if the user click on other panel in Safari only.

**To Reproduce**
1. Go to http://latest-enterprise.demo.design.infor.com/components/accordion/example-accordion-panels.html in Safari 12.
2. Click on the Accordion panel header.
3. Click on another Accordion panel header from the same Accordion.

**Expected behavior**
When the user click on panel, rest of the panel should loose the focus.

**Version**
- ids-enterprise-ng: 6 (latest)

**Screenshots**
![image](https://user-images.githubusercontent.com/54695843/65735659-86983780-e11b-11e9-80ad-7aef01073a97.png)

**Platform**
 - Device: Mac
 - OS Version: Latest
 - Browser Name: Safari
 - Browser Version: 12.1

**Additional context**
It seems that when a user click on the panel, it is not removing the is-focus from other panels.

**Comment by EdwardCoyle** [comment]
@shane-infor I moved this issue to the regular Enterprise repo, since this is reproducible in EP.

@tmcconechy I'm going to fix this one in my current batch of Accordion/App Menu stuff for `v4.22.x`

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks 
Tested in http://4220-beta0-enterprise.demo.design.infor.com/components/accordion/example-accordion-panels.html
