### ISSUE TITLE
Datagrid: Alert Formatter has blank tooltip when using just alert formatter

### ISSUE THREAD

**Issue by petr-hlavnicka** [infor-design/enterprise#2852]
![1_1_code_text_property_missing](https://user-images.githubusercontent.com/49194823/65755350-3ddc8080-e113-11e9-9196-51f4dc8538f8.png)
![1_2_key_displayed_when_text_property_missing](https://user-images.githubusercontent.com/49194823/65755351-3ddc8080-e113-11e9-9933-24885071072c.png)
![2_1_code_text_property_whitespace](https://user-images.githubusercontent.com/49194823/65755352-3ddc8080-e113-11e9-8731-68735f8a557f.png)
![2_2_empty_tooptip_displayed_when_text_property_whitespace](https://user-images.githubusercontent.com/49194823/65755353-3ddc8080-e113-11e9-8906-dcf3ad1ca769.png)

**Describe the bug**
It seems that the possibility of include only icons with no text in the datagrid when using formatter: Soho.Formatters.Alert is not supported:

- if we do not include property text or this property is empty, key is displayed - see screenshots 1_1 and 1_2

- as a workaround we set text property to whitespace - the problem with this approach is the empty tooltip - see screenshots 2_1 and 2_2 - this is the bug reported by QA.

**To Reproduce**

**Expected behavior**

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by petr-hlavnicka** [comment]
[datagrid-standard-formatter_demo_updated.txt](https://github.com/infor-design/enterprise/files/3676560/datagrid-standard-formatter_demo_updated.txt)
![Black_tooltip](https://user-images.githubusercontent.com/49194823/65967461-e6674900-e461-11e9-8d1a-b4063375b2c9.png)
Hi @tmcconechy, I attched the updated datagrid-standard-formatter.demo.ts code, which reproduces the bug/behaviour. The changes are on lines 48-51 and 73.

**Comment by janahintal** [comment]
QA Passed. Thank you.
Will retest in beta once released.
