### ISSUE TITLE
Contextual Action Panel Control: Layout Issue - Close button inside contextual action panel is cut out

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#286]
**Describe the bug**
Layout Issue - Close button inside contextual action panel is cut out

**To Reproduce**
1. Go to http://localhost:4000/components/contextualactionpanel/test-full-content.html
2. Click "Show Contextual Action Panel" button
3. Notice the Close button is cut out

**Expected behavior**
The Close button should be visible 

**Screenshots**
<img width="1027" alt="cap layout issues" src="https://user-images.githubusercontent.com/39101346/41991827-d3acde50-7a14-11e8-9c4a-9c934eb80251.png">

**Platform**

 - All Browsers
 

**Additional context**
None

**Comment by EdwardCoyle** [comment]
I actually fixed this in #283, but that's currently against `master`.

**Comment by tmcconechy** [comment]
Cool, I think thats fine this was for this sprint and its only an issue on the examples not needed for this version.

Noting as Fixed on https://github.com/infor-design/enterprise/pull/283
