### ISSUE TITLE
Monthview: Date and "Today" labels are misaligned in IE

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2862]
**Describe the bug**
Monthview: Date and "Today" labels are misaligned in Windows IE.

**To Reproduce**
1. Open **Windows IE**
2. Go to http://master-enterprise.demo.design.infor.com/components/monthview/example-index.html
3. See issue: Date and "Today" labels are misaligned

**Expected behavior**
Date and "Today" labels should be properly aligned.

**Version**
- ids-enterprise: v4.14.0 to v4.21.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/65951217-3221ee80-e472-11e9-8331-78f7ddaaee62.png)

**Platform**
 - OS: Windows 10
 - Browser: IE 11

**Additional context**
N/A

**Comment by tmcconechy** [comment]
@ericangeles Im working on this already.

**Comment by tmcconechy** [comment]
This will be fixed along with https://github.com/infor-design/enterprise/issues/2713#issuecomment-534946823 and https://github.com/infor-design/enterprise/issues/2704#issuecomment-536474994

**Comment by ericangeles** [comment]
Alright, will just remove the branch that I created. Thanks, @tmcconechy 👍

**Comment by tmcconechy** [comment]
This fix depends on #1757 as i made the calendar toolbar a separate component. So will be fixd when thats done

**Comment by tmcconechy** [comment]
Since this depends on #1757 which isnt done yet this will be first thing in 4.23. 4.22 will have a minor layout issue on IE which isnt as much in use anymore.

**Comment by CindyMercadoReyes** [comment]
This issue is still occurring. Please see screens shot attached. 
![bs_win7_IE_11 0](https://user-images.githubusercontent.com/39101346/67296651-c3efab00-f4b6-11e9-824c-a3b42e70a941.jpg)

**Comment by tmcconechy** [comment]
Still working on this one. It’s not pushed just yet

**Comment by CindyMercadoReyes** [comment]
There are still alignment issues on uplift theme.  Please see screen shot attached. 
<img width="871" alt="Alignment issues on uplift theme" src="https://user-images.githubusercontent.com/39101346/68618212-dac26580-0496-11ea-9b00-6724b886e260.png">

**Comment by tmcconechy** [comment]
I was working on this but it was raised as a seperate issue https://github.com/infor-design/enterprise/issues/3111

So will close this and move to done and work on the fix on the other / more clear ticket.
