### ISSUE TITLE
Datepicker: Arrow keys are not working to select month and year in IE

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2863]
**Describe the bug**
Datepicker: Arrow keys are not working to select month and year in **Windows IE**.

**To Reproduce**
1. Open **Windows IE**
2. Go to http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html
3. Open date picker
4. Open month and year dropdown
5. Tab to list of months, try to use arrow down and up keys, they won't work
6. Tab to list of years, try to use arrow down and up keys as well, they won't work

**Expected behavior**
Arrow Down and Up keys should work when selecting month and year in IE.

**Version**
- ids-enterprise: v4.20.0 to v4.21.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/65951741-41556c00-e473-11e9-9bec-8d83a473b187.png)

**Platform**
 - OS: Windows 10
 - Browser: IE 11

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Descoping some IE 11 issues for now.
