### ISSUE TITLE
DataGrid: Missing horizontal scrollbar when filter is applied

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#2864]
**Describe the bug**
When the datagrid is wider and horizontal scrollbar is present and you apply the filter, the scrollbar disappears. Issue when you filtered out columns hidden right

**To Reproduce**
1. update fixed header demo page, so the filtering is enabled (delete `disableClientFilter: true`)
2. Open app, make window smaller so the horizontal scrollbar appears
3. scroll to the right and filter out something so `No Data Available` appears
4. See that the scrollbar is lost and you are moved to left, so you cant easily navigate to clear/modify the filter field

**Expected behavior**
Scrollbar should stay there so the user is able to navigate there via mouse.
Or keep the header on the same place so the used filter field is on the screen.

**Version**
- ids-enterprise-ng: 6.0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/11279863/65960935-d5b0d600-e455-11e9-94f8-3b611082bb5e.png)

**Additional context**
Still possible to reach the field by tab key, but when you delete the filter the grid is not alligned (unless you do some horizotnal scrolling)
![image](https://user-images.githubusercontent.com/11279863/65961028-04c74780-e456-11e9-8a2a-b85ded392142.png)

**Comment by tmcconechy** [comment]
Relates to https://github.com/infor-design/enterprise/issues/1041 and https://github.com/infor-design/enterprise/issues/2363

This will probably be all fixed by what im doing on #1818 to change the scrolling mechanism to `position:sticky`

**Comment by janahintal** [comment]
QA Passed. This issue is now resolved. Thank you. 
Tested in http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-filter.html?theme=soho&variant=light across all platform.
