### ISSUE TITLE
DataGrid: Filtering dates does not filter datetime correctly

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#2865]
**Describe the bug**
When the filter is accepting only days and cells are in datetime format, then the filter does not work properly

**To Reproduce**
1. set column like this in ng demo app    
`columns.push({ id: 'orderDate', name: 'Order Date 2', field: 'orderDate', formatter: Formatters.Date, editor: Editors.Date, filterType: 'date', width: 200, editorOptions: {secondInterval: 1, minuteInterval: 1, showTime: false, dateFormat: 'M/d/yyyy'}, dateFormat: 'M/d/yyyy HH:mm:ss'});`
2. Observe that when you select date in filter, cells with same date but different times than 00:00:00 are not shown

**Expected behavior**
When you have for example 1/1/2019 15:00:00 and 1/1/2019 16:00:00 then by using the filter (defined like described above) with the date 1/1/2019 should show both results. Now it shows none of them.

**Version**
- ids-enterprise-ng: 6.0.0

**Screenshots**
in ids-enterprise: 
![image](https://user-images.githubusercontent.com/11279863/65954931-50262980-e447-11e9-8998-5c4d281356cd.png)

in ids-enterprise-ng:
![image](https://user-images.githubusercontent.com/11279863/65954989-6cc26180-e447-11e9-9f7f-71f153c47ec0.png)

**Additional context**
Works in ids-enterprise

**Comment by tmcconechy** [comment]
As a note i thought i was able to make this work by changing the editorOptions here on this example. https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-editable-datetime.html#L43

- may want to extend filterEditorOptions to date time and provide a test and retest for this and test the NG example as noted.

**Comment by tmcconechy** [comment]
I found that this can be done by providing a sourceFormat option that represents the "full showing" date format so it knows exactly how to compare the time date string to the shorter date string with no time. An example of this is:

```
columns.push({ id: 'ibatdatim', name: 'Date / Time (Filter Date)', field: 'ibatdatim', sortfield: 'ibatdatim', filterType: 'date', sortable: false, hidden: false,  dateFormat: Calendars.dateFormat['short'] + ' ' + Calendars.dateFormat['timestamp'], sourceFormat: Calendars.dateFormat['short'] + ' ' + Calendars.dateFormat['timestamp'], editorOptions: { showTime: true, dateFormat: Calendars.dateFormat['short'] + ' ' + Calendars.dateFormat['timestamp']}, editorOptions: {showTime: false, placeholder: true, dateFormat: Calendars.dateFormat['short']}, formatter: Soho.Formatters.Date });
```

Adding this to app/views/components/datagrid/test-filter-datetime-client-side.html

**Comment by jbrcna** [comment]
This issue is now resolved. tested in master v4.26-dev
moving this ticket to Done
