### ISSUE TITLE
DataGrid: no data shown in column containing dot in id

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#2866]
**Describe the bug**
No data are shown in a column containing dot in id. For example `employee.id`

**To Reproduce**
1. Change the id in any column, so it contains dot
2. Change the dataset to match column.
3. Run app and check

**Expected behavior**
Dot should be allowed.

**Version**
- ids-enterprise-ng: 6.0.0

**Comment by tmcconechy** [comment]
When you modified your data did you just make the id have a dot in the text or did you actually change the data to the object syntax. As when you insert a dot the datagrid is assuming object syntax like this example:

https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-nested-objects.html#L19-L24

http://latest-enterprise.demo.design.infor.com/components/datagrid/test-nested-objects.html

i.e If you use dots objects are expected in the data. So not sure if this is a bug. If anything we could make an enhancement setting to "not use object syntax" but this seems maybe like an odd case. So up to you if you think this warrants a setting. As this is working as we spec'd

**Comment by hohnzy** [comment]
Aha, our columns are dynamic. Its result from SQL so the user can do something like `SELECT column1 as 'column.1' from sqltable` - this is kinda ok as we can say users to not use dot, but some columns are directly defined as 'column.1'.

**Comment by tmcconechy** [comment]
OK i think a setting to not treat it like an object is something we could do but i will make it minor for now if your good with it now that you know how it works and why.

**Comment by hohnzy** [comment]
Sure. I can workaround by modifying the data before sending to grid. But that feature would be nice in future.

**Comment by tmcconechy** [comment]
We will get this working in the new web component but archiving this for now
