### ISSUE TITLE
Datagrid: Problem using rowTemplate/expandableRows and frozenColumns with both right and left side frozen.

### ISSUE THREAD

**Issue by SasiPalanati** [infor-design/enterprise#2867]
**Describe the bug**
When using rowTemplate/expandableRows and frozenColumns with both right and left side frozen. The right side is not rendered properly

**To Reproduce**
1. Take the example code for the example http://latest-enterprise.demo.design.infor.com/components/datagrid/test-expandable-row-frozen-columns.html
1. In the code change the frozen columns as 
`frozenColumns: { left: ['productId'], right:['quantity10'] },`
1. Compile and click on expand button and see the right frozen section, the expanded area is missing
1. See Error in the sohoxi.js file

**Expected behavior**
Right table should have a expanded row. so that three sections are aligned and no error.

1. Also as a Second Example Use the same example above, remove rowTemplate setting, add `expandableRow: true` and `onExpandRow: this.expandRowCallback`, and keep both left and right frozen columns. In this case also, the right table expander row is missing.

**Expected result:**
Right table also should have expanded row. Missing the condition in the sohoxi.js file 46797. Need to add the condition.

**Version**
Soho version 4.21

**Screenshots**

**Platform**
Both chrome and IE

**Comment by tmcconechy** [comment]
Suggested Workaround: Do not freeze the right side if using expandable rows.

**Comment by tmcconechy** [comment]
Easier way to reproduce:

1. go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-expandable-row-frozen-columns.html
1. In the above link please click on one of the expander buttons – say row 1(the row expands including the left pane) and then go to another row – say 4, and click on the expander button there. 
1. The ‘left pane’ expanded area of row 1 has not collapsed

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in https://master-enterprise.demo.design.infor.com/components/datagrid/test-expandable-row-frozen-columns.html and https://master-enterprise.demo.design.infor.com/components/datagrid/test-expandable-row-frozen-columns-bothsides.html.
