### ISSUE TITLE
Search-field Control: No event fired in the console

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#287]
**Describe the bug**
No event fired in the console

**To Reproduce**
1. Go to http://480-beta0-sohoxi.demo.design.infor.com/components/searchfield/test-selected-event.html
2. Open developer tools, go to console
3. Select "Baby" from the dropdown
4. Type 'a' in the search field
5. Nothing happens in the console

**Expected behavior**
An event should fire off in dev console

**Screenshots**
None

**Platform**

 - All Browsers 

**Additional context**
None

**Comment by EdwardCoyle** [comment]
Fixed in #290

**Comment by CindyMercadoReyes** [comment]
This Issue is now resolved. An event was fired in the dev console. Closing out this ticket.
