### ISSUE TITLE
Contextual Action Panel: Locale reverts back to the default after opening a contextual action panel

### ISSUE THREAD

**Issue by prkarlsson** [infor-design/enterprise#2873]
**Describe the bug**
When opening a contextual action panel the locale reverts back to the default (en-US). We would like this to be fixed as soon as possible to be able to support separate language and locale in the Homepages application.

Depending on the settings for the current user our application may use different language and locale which are both different from the default. This works as expected, numbers and dates are formatted according to the current locale etc. After opening any contextual action panel the locale reverts back to en-US and after that all numbers and dates are formatted in en-US instead of the expected locale.

When the contextual action panel is opened the Initialize function is invoked (see behaviors\initialize\initialize.js). The settings parameter is empty so it defaults to the en-US locale set in INITIALIZE_DEFAULTS.

**To Reproduce**
1. Test with an application configured to use non-default language and locale
2. Open a contextual action panel
3. The current locale reverts to en-US

**Expected behavior**
The current locale should remain after opening a contexual action panel.

**Version**
4.21.0

**Platform**
 - Affects all platforms

**Comment by tmcconechy** [comment]
About to push a fix but found that setting `initializeContent: false` on the CAP settings would be a workaround.

**Comment by SofiK** [comment]
Note that this also affect RTL. So in this sample, https://design.infor.com/code/ids-enterprise/latest/demo/components/contextualactionpanel/example-index.html?locale=ar-sa 
The RTL becomes LTR (in the entire window) directly when opening the dialog.

**Comment by tmcconechy** [comment]
Thanks I confirmed on the fix branch that this is indeed fixed by the fix https://github.com/infor-design/enterprise/pull/2877

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-locale.html
http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-locale.html?locale=de-DE
http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html?locale=ar-sa
Passed QA in all browsers, moving to Done.
