### ISSUE TITLE
Datagrid: Actions menu can only be opened once

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#2876]
**Describe the bug**
If opening an actions menu in a datagrid (Actions formatter on column), and then refresh the dataset, the menu can no longer be opened for any row item. This is a high priority issue for us.
![action-menu](https://user-images.githubusercontent.com/1101770/66034514-a8256480-e509-11e9-9b7f-7c636c0c2881.gif)

It was originally reported & fixed in March 2018:
https://jira.infor.com/browse/SOHO-7634

**To Reproduce**
The SOHO ticket above has a link to a test page you created, but I'm unable to find out where to access it now (or if it exists anymore)?
http://usalvlhlpool1.infor.com/4.5.0-rc/components/datagrid/test-actions-reload.html

**Expected behavior**
After refreshing dataset (either by changing dataset completely or if using updateRow() etc.), the Actions menu can still be opened.

**Version**
- ids-enterprise: 4.21.0

**Additonal context**
See https://jira.infor.com/browse/SOHO-7634
Working on 4.20.1

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thank! :) 
Verified in http://4220-beta0-enterprise.demo.design.infor.com/components/datagrid/test-actions-reload.html across all platform
