### ISSUE TITLE
Popdown filter is not showing in iOS devices 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2883]
**Describe the bug**
Popdown filter is not showing in iOS devices 
**To Reproduce**
1. Open Browser in iOS device 
2.  Go to  http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=soho&variant=light&colors=2578a9
3. Click '...' button 

**Expected behavior**
Will show a popdown filter

**Version**
Beta 4.22 regression

**Screenshots**
Popdown filter is not showing in iOS devices 

**Platform**
iOS Devices

**Additional context**
NA

**Comment by tmcconechy** [comment]
Duplicate of #2800
