### ISSUE TITLE
Question: Do DataGrid filters support multiple matches?

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#2884]
In a DataGrid, I can see there are various column filter options and also the option of using a fixed "multiselect" filter, which is fine for known values, but not for dynamic data. So, is there a way to specify, in a column filter, multiple values?

For example, I have a table that has a column containing Cities of the world, and I want to filter the table to show "Chicago" and "Boston", ideally by typing "Chicago,Boston" into the column filter field, is there a way to do that with the DataGrid, and if so, is there an example page I need to look at?

I did try using a comma, space and using "or" and "and" in the filter but these didn't appear to work. is there a "user guide" for how the column filtering works that we could incoporate in our own product guide?

**Comment by tmcconechy** [comment]
We only support this via the multiselect filter type

http://latest-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
- see column "activity"
- source is https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-filter.html#L58 it used the multiselect filter and you have to populate the list how you want

We did have a filterType: 'contents' but in writing this i noticed it does not work as expected so i will raise an issue for that. Idea was it would pick up your contents from every cell and make a multiselect dynamically.

**Comment by tmcconechy** [comment]
Raised https://github.com/infor-design/enterprise/issues/2887 for the unexpectedly missing filter type

**Comment by sanx72** [comment]
Thanks Tim. I did look at multiselect filter but having to provide data that the datagrid already had seemed wrong but I must have missed the 'contents' example, even if it doesn't work as expected.

I don't see 'multisect' or 'contents' in the Data grid documentation: https://design.infor.com/code/ids-enterprise/latest/datagrid so perhaps you also need to add that so people don't need to look through source to find the available function?

**Comment by tmcconechy** [comment]
Agreed. The contents filter was what i hoped to show but will make it work again and provide an example for it on https://github.com/infor-design/enterprise/issues/2887 i also noted on there to ensure the docs list all the filter types and explain them.
