### ISSUE TITLE
Datagrid: No empty states in custom filter conditions

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2886]
**Describe the bug**
Datagrid: No empty states in custom filter conditions

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html?theme=soho&variant=light&colors=2578a9 
2. In the Product Name select '=' filter and type 'Com'

**Expected behavior**
Empty state with icon should appear for both SOHO and Vibrant theme

**Version**
Beta 4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66114487-7f809600-e601-11e9-9a11-a6283fb295e5.png)

**Platform**
All OS, Browsers and Devices

**Additional context**
NA

**Comment by tmcconechy** [comment]
I cant 100% reproduce this issue.

1. In soho theme when i filter on = CROM i DO see the icon http://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html
BUT
1. In Uplift theme i do not see this icon. It may be missing that exact icon http://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html?theme=uplift&variant=light&colors=2578a9

Is that correct @janahintal @CindyMercadoReyes ? Or is a step missing?

**Comment by janahintal** [comment]
QA passed. Will move to Done. Thanks :)
Verified here http://4220-beta0-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html?theme=uplift&variant=light&colors=2578a9
