### ISSUE TITLE
Datagrid: Contents Filtertype is not working

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2887]
**Describe the bug**
We used to have support for `filterType: 'contents'` but while reviewing #2884 i found there is no example and it doesnt work.

**To Reproduce**
1.Edit app/views/components/datagrid/example-filter.html
2. Add column `columns.push({ id: 'activity', name: 'Activity (Contents Filter)', field: 'activity', filterType: 'contents'});`
3. Run components/datagrid/example-filter.html and check the filter on the new column. Its empty 😞 

**Expected behavior**
This type should pick up and generate a multiselect filter for each value found in the datagrid.
Also provide a test and separate example page and ensure the filterType settings are in the datagrid docs.

**Version**
- ids-enterprise: [e.g. v4.22.0-beta]

**Platform**
 - Any (Chrome)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift&variant=light
