### ISSUE TITLE
Datagrid List: Add "tall" row height for casual lists

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2893]
**Is your feature request related to a problem? Please describe.**

@kevinwhitedesign has suggested a design for smaller "casual" lists with a wider row height.
The suggestion os to add a fourth row height to the datagrid. Use case would be less columns and a smaller list with "isList" style in the datagrid. But would work in all cases just in case

**Additional context**
Mockup:

![Screen Shot 2019-10-03 at 12 58 18 PM](https://user-images.githubusercontent.com/814283/66147767-7e3d7200-e5dd-11e9-83a2-deedafc7c95d.png)

**Comment by kevinwhitedesign** [comment]
<img width="240" alt="Screenshot 2019-10-03 12 50 41" src="https://user-images.githubusercontent.com/6478704/66148054-19364c00-e5de-11e9-97ce-8adedbce51c9.png">

**Comment by kevinwhitedesign** [comment]
@jamienorman @pwpatton @lipetzan

**Comment by jamie-norman** [comment]
@kevinwhitedesign Related LMCLIENT JT: https://jira.lawson.com/browse/LMCLIENT-27799

**Comment by kevinwhitedesign** [comment]
@tmcconechy do you mean larger lists? with higher row height?

**Comment by tmcconechy** [comment]
Yep by larger i mean higher row height

**Comment by tmcconechy** [comment]
@kevinwhitedesign this is the current list view http://master-enterprise.demo.design.infor.com/components/datagrid/example-list.html?theme=uplift&variant=light&colors=0563C2

in regards to this should we just add a row height, or also change colors of all the elements like the header and test?

**Comment by tmcconechy** [comment]
@kevinwhitedesign @jamie-norman do you guys think we need this still (based on things need to be more compact now)

**Comment by jamie-norman** [comment]
@tmcconechy Fair to call it a lower priority. Maybe axe it for now and see if we get any feedback around a need for this feature?

**Comment by tmcconechy** [comment]
Descoping this for now
