### ISSUE TITLE
Locale: Add new translations

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2896]
**Is your feature request related to a problem? Please describe.**
Add the new translations we got back from the translation team.

**Comment by brianjuan** [comment]
Passed QA in all browsers. Moving to Done.
http://4220-beta0-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html
http://4220-beta0-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?locale=fi-FI
