### ISSUE TITLE
Enterprise css breaks Monaco Editor

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise#2898]
**Describe the bug**
Using Enteprise css together with Monaco editor causes Monaco editor to not render popups properly due to css conflicts

**To Reproduce**
1. Clone project from this [repo](https://github.com/Fruko/ids-enterprise-ng-monaco)
2. Run it with `cd app && yarn install && ng server`
3. Type import in the file
3. See that with light theme css included in the index.html the popups do not render properly
4. Looks like `.tree a` is conflicting
5. Use trick `setTimeout(() => {debugger;}, 3000)` to start a debugger up when its open.

**Expected behavior**
Enterprise css to be encapsulated so that it wouldn't break other libraries

**Comment by tmcconechy** [comment]
This is a good use case to support https://github.com/infor-design/enterprise/issues/1199

**Comment by tmcconechy** [comment]
@Fruko 

Not sure if you solved this or not but i was testing out https://github.com/vanillawc/wc-monaco-editor and if you embed your monaco editor with that it moves the css into the shadow DOM so it seems like with this it wont conflict.

We are still resistent to make the breaking change yet. Thinking if that doesnt work to do something so tree specifically works. Then in a future version we will have `ids-tree` and done with a web component.

**Comment by Fruko** [comment]
@tmcconechy  thank you for this! Actually because of these issues we de-scoped the adoption of Monaco. I will try wc-monaco-editor

**Comment by tmcconechy** [comment]
Please give it a shot if it works great, if not i can find a non breaking way to fix the tree so it doesnt conflict.

**Comment by Fruko** [comment]
@tmcconechy we tried with wc monaco editor and unfortunately the styles are broken anyway

![image](https://user-images.githubusercontent.com/10186522/83897189-8c87f300-a755-11ea-9980-713bf4f8193f.png)

I think manually fixing the style conflicts is our only option to make it work for now

**Comment by tmcconechy** [comment]
Ok, i thought i saw the issue with the typeahead popupmenu was definately working. Any idea what classes are conflicting here? 

Should we just test with wc monaco editor then?

**Comment by Fruko** [comment]
it seems that quick fix could be removing the font-size: 0
![image](https://user-images.githubusercontent.com/10186522/83900003-a9262a00-a759-11ea-8137-34d088c64647.png)

but there can be a number of these cases. 
facing the issue as it is, I would say our team will try to use angular wrapper for monaco
https://github.com/atularen/ngx-monaco-editor

and override the styles to make it work

**Comment by tmcconechy** [comment]
OK yes thats probably easier. It would be tough to remove that font-size right now. What i'll do is do it on the bit of the rework we are starting then. (no reset ect)

**Comment by tmcconechy** [comment]
Descoping this for now. But in 5.0 we have encapsulation so it will work in 5.0. For now have to use your current workarounds
