### ISSUE TITLE
Context menu sizing and positioning in some situations is incorrect.

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#2899]
**Describe the bug**
The size of the browser window can effect the sizing and positioning of the context window. Sometime even a small change in the browser window size can make the context window come up an huge differences in size. Left positioning seems to be right but the top positioning is not always correct either.  This issue for us is seen in the right click full page.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/contextmenu/example-page-rightclick.html
2. Size browser height smaller 
3. Right click to show context menu
4. Keep repeating step 2-3 and each time making the window small to see issue. In the case if the example the menu height is not to tall and so it requires a smaller window to replicate. If you have a taller context menu the behavior cn be seen on full size browser windows.

**Expected behavior**
For the context menu to size and position properly taking screen size and menu dimensions and use those to properly size the menu

**Version**
 IDS Enterprise Components - v4.22.0-dev

**Screenshots**

![Screenshot 2019-10-04 13 03 29](https://user-images.githubusercontent.com/19823048/66229934-9cbc6f80-e6a8-11e9-98e7-e7a15d0bde42.png)
**This is clicking near the bottom of the screen with the menu fitting**

![Screenshot 2019-10-04 13 03 41](https://user-images.githubusercontent.com/19823048/66229952-aa71f500-e6a8-11e9-913f-7bcabd72cb9c.png)
**Made the window smaller. This is clicking near the bottom but the menu comes up on the top and to short**

![Screenshot 2019-10-04 13 04 02](https://user-images.githubusercontent.com/19823048/66229957-ae057c00-e6a8-11e9-9d3b-7ba2061f7f0e.png)
**Made the windows smaller. this is clicking near the bottom and now the menu is so small it seems unusable and nowhere near the click area.**

![Screenshot 2019-10-04 13 04 10](https://user-images.githubusercontent.com/19823048/66229961-b1006c80-e6a8-11e9-9a2d-5d40bb3a716f.png)

**Made it even smaller but now the menu sizes to large with no way to get to the lower menu items.**

**### Again this issue does not just happen in smaller window sizes. It can happen in  full window browsers when the menu has a lot of items in it.**

**Platform**
Chrome - Version 77.0.3865.90 (Official Build) (64-bit)

**Additional context**

**Comment by pwpatton** [comment]
@krahs1  are we using `attachToBody` on this?

**Comment by tmcconechy** [comment]
I think I saw this on field options in certain positions and that was not attachToBody.
So I guess that doesn’t matter. Seems like a position logic issue

**Comment by janahintal** [comment]
Issue still exist. Please see below:

http://master-enterprise.demo.design.infor.com/components/contextmenu/example-page-rightclick.html

![image](https://user-images.githubusercontent.com/45757016/67460298-3609f080-f66d-11e9-915f-1abfa638cb27.png)

![image](https://user-images.githubusercontent.com/45757016/67460313-41f5b280-f66d-11e9-9c94-438136dd1f09.png)

**Comment by tmcconechy** [comment]
Im not seeing this appear exactly like that anymore. Did you try to clear cache @janahintal 
Do you see it @EdwardCoyle ?

**Comment by pwpatton** [comment]
@EdwardCoyle would always "attaching to body" fix some of these? thinking this is happening due to container heights that the menu is displaying in?!

**Comment by EdwardCoyle** [comment]
@pwpatton No, `attachToBody` has nothing to do with this issue.  This issue is in the placement calculation.  Setting `attachToBody: true` will pull the placed element out of containment, but it would still be affected if the space available is too small.

That being said, @tmcconechy I think something is wrong with the current deployment on `master-enterprise`.  I can see what @janahintal reported on [the `master-enterprise` test page](http://master-enterprise.demo.design.infor.com/components/contextmenu/example-page-rightclick.html), but if you pull the latest master branch and run locally, it's working as expected.

**Comment by EdwardCoyle** [comment]
I think a build just replaced `master-enterprise` right after I typed out the response above.  `sohoxi.js` now has this build info:

![Screen Shot 2019-10-24 at 10 48 56 AM](https://user-images.githubusercontent.com/3249601/67497472-04ccf880-f64c-11e9-9ad0-7395138805fc.png)

I didn't get a screen capture of the original one, but the date before said "2019-10-22".  I think the test happened on an old build.  @janahintal would you be able to retest?

**Comment by tmcconechy** [comment]
Yep looks like the last merge did update it. Lets QA again now that is updated.

**Comment by janahintal** [comment]
Hi @tmcconechy ,  I have tried testing it again today and it's now working as expected. Thank you. I will now move this to Done.
