### ISSUE TITLE
Application menu header always inserts the +/- button when it's a subitem.

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#2900]
**Describe the bug**
Application menu header always inserts the +/- button when it's a subitem.

**To Reproduce**
Would like to have the arrow up/down button even if the subitems are inside another element tag, in our case they are inside an angular template component.

**Expected behavior**
http://master-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm?theme=uplift

**Version**

- ids-enterprise: v4.22.0-dev

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by EdwardCoyle** [comment]
Not necessarily a bug.  This has been the design of the accordion headers for some time.  We'd need to provide a setting that would use the chevron instead of the +/- expanders in sub-headers, which is currently not possible.

**Comment by tmcconechy** [comment]
Setting sounds good. I thought maybe it was a problem due to angular nesting.

**Comment by EdwardCoyle** [comment]
@vonnyw are you expecting the chevron icons to appear in subheaders with the same placement that they have in top-level headers?  FX: text on the left, expander on the right?

For example, current top level headers do this:

![Screen Shot 2019-10-09 at 1 02 21 PM](https://user-images.githubusercontent.com/3249601/66503393-29926f00-ea95-11e9-9df3-ca92958828c9.png)

... and subheaders do this:

![Screen Shot 2019-10-09 at 1 02 30 PM](https://user-images.githubusercontent.com/3249601/66503403-3020e680-ea95-11e9-969c-47131ed9dc5b.png)

Would you expect the subheader chevron icons to be on the right, the same as the headers?  Or should the current placement remain?

**Comment by vonnyw** [comment]
@EdwardCoyle We are expecting the current placement to remain.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/accordion/test-all-chevrons.html
http://master-enterprise.demo.design.infor.com/components/accordion/test-all-plus-minus.html
http://master-enterprise.demo.design.infor.com/components/accordion/test-display-chevron-setting.html
Passed QA on all browsers, will retest once beta is deployed.
