### ISSUE TITLE
Checkbox: New global uplift rule causes alignment issues

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#2907]
**Describe the bug**

A recent change https://github.com/infor-design/enterprise/pull/2872/files#diff-4e8ca57486af317304770962b8ed1fc9R68 introduced an issue on our checkboxes.

**To Reproduce**
1. Go to http://localhost:4000/components/form/test-compound-checkboxes-alignment.html and see alignment issues
1. Go to http://localhost:4000/components/calendar/example-index.html?theme=uplift&variant=light&colors=0563C2
2. In the + menu select add event (modal)
3. Remove the rule https://github.com/infor-design/enterprise/pull/2872/files#diff-4e8ca57486af317304770962b8ed1fc9R68 since its not adquetly scoped.
4. Rest test this form and find a new alignment fix - does seem ok.

**Expected behavior**

**Version**
- ids-enterprise: [v4.22.0 beta]

**Platform**
 - Any (Chrome)

**Additional context**
The bigger problem for Landmark is we use a form layout on our checkboxes and this rule was scoped to all checkboxes. Will provide a form test example to follow. While Tim reworks the fix.

**Comment by janahintal** [comment]
Unable to test http://4220-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=uplift in iOS devices as the popup menu is cut off upon clicking '+'

**Comment by tmcconechy** [comment]
This is reported on https://github.com/infor-design/enterprise/issues/2962 so moving to done.
