### ISSUE TITLE
Datagrid: getModifiedRows() has duplicate entries for the same row 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2908]
Describe the bug
The method getModifiedRows() may contain more than one entry for the same row.  Expect that a single entry would exist for a modified row.

1. Go to 'http://localhost:4000/components/datagrid/test-dirty-change-cell-externally.html
2. Click on 'Change Cell' button on the toolbar
3. Open the browser's debugger and examine the array returned from getModifiedRows()

Expected behavior
A modified row would appear in the returned array once

Version
v4.23.0-dev

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/66341004-fbcdee80-e90b-11e9-87ed-337656cac46b.png)

**Comment by claudenbach** [comment]
Currently have the following code in Landmark as a workaround for the possible duplicate entries.  Prefer that the removal of dups would not reside in the users of the the method.

```
 public getDirtyRows(commitEdits: boolean = undefined): Array<LMDataView> {
    // return this.sohoDataGridComponent.dirtyRows();
    let modifiedRows = this.sohoDataGridComponent.getModifiedRows() as Array<SohoDataGridModifiedRow>;

    // remove duplicate rows from the array since presently getModifiedRows may contain dups
    let dirtyRows = modifiedRows.filter((obj, pos, arr) => {
      return arr.map(mapObj =>
          mapObj['row']).indexOf(obj['row']) === pos;
    });

    return Object.keys(dirtyRows).map((key) => {
      let modifiedRow: SohoDataGridModifiedRow = dirtyRows[key];
      return modifiedRow.data;
    });
  }
```

**Comment by janahintal** [comment]
QA Passed. This issue is now resolved. Thanks! Verified in http://master-enterprise.demo.design.infor.com/components/datagrid/test-dirty-change-cell-externally.html?theme=uplift&variant=light&colors=0563C2
