### ISSUE TITLE
Datagrid: Inconsistent filter results across pages in indeterminate paging

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2911]
**Describe the bug**
Datagrid: Inconsistent filter results across pages in indeterminate paging.

**To Reproduce**
1. Go to http://4220-beta0-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html
2. Type 1 on the filter field of Actual ID column, datagrid will be filtered
3. Go to next pages
4. See issue: datagrid rows on other pages does not match the applied filter on Actual ID column

**Expected behavior**
Datagrid should be filtered on all pages

**Version**
- ids-enterprise: v4.19.0 to v4.22.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/66388724-52fdbd00-e9f9-11e9-818a-1237b740915d.png)

**Platform**
 - All devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
I just changed the example locally to not show paging on this example as this example cannot do paging as the data is static/example data only. So turned the paging row off to avoid confusion.

**Comment by brianjuan** [comment]
Taking note of that @tmcconechy, thank you.
