### ISSUE TITLE
Dropdown: Icons are misaligned in the list in IE 11 Windows 10

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2912]
**Describe the bug**
Dropdown icons are misaligned in the list in IE 11 Windows 10

**To Reproduce**
1. Open IE and Go to http://4220-beta0-enterprise.demo.design.infor.com/components/dropdown/example-icons.html?theme=uplift&variant=light&colors=5c5c5c

**Expected behavior**
List details and icons should align properly

**Version**
Beta 4.22
**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66388966-d4554f80-e9f9-11e9-8214-28dc70b87817.png)

**Platform**
Windows 10 IE 11

**Additional context**
N/a

**Comment by johnbarcena** [comment]
test PASSED

**Comment by johnbarcena** [comment]
![image](https://user-images.githubusercontent.com/52902639/67003100-d9a84d80-f10f-11e9-80f0-ee6352c4bdca.png)
