### ISSUE TITLE
About: Language is shown as locale

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#2913]
**Describe the bug**
When opening the about dialog the locale is always shown as the browser language, not the locale that is used from the URL. I'm not sure it seems the language depends on the locale in the URL so maybe we have different usage of locale? 

**To Reproduce**

1. Set the browser language to Swedish (or any other language that is not English)
2. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/about/example-index.html?locale=en-US
3. Click on 'Show about screen'
4. Scroll down to 'locale'
5. Note that the locale is shown as 'sv' (the browser language)

**Expected behavior**
I think the locale should be displayed as 'en-US' which is the locale instead of the browser language.
Or perhaps the label should be language? (But then how do we override the language to the actual language instead of the browser language?)

**Version**

- ids-enterprise: v 4.21.0

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/66402389-0c05cc80-e9e5-11e9-9257-fd7a84e217c9.png)

![image](https://user-images.githubusercontent.com/8664975/66402343-fabcc000-e9e4-11e9-88cc-0bcfb6548372.png)

**Platform**
 - OS Version: Win 10
 - Browser Name: Chrome
 - Browser Version: Version 77.0.3865.90 (Official Build) (64-bit)

**Additional context**
We also have an issue in Homepages when we override browser language with both locale and language the browser language is still shown in locale. But perhaps we are doing something wrong here? How can we override the browser locale if the expected locale should be sv in this case?

**Comment by tmcconechy** [comment]
Is it the same if i do this ? https://design.infor.com/code/ids-enterprise/latest/demo/components/about/example-index.html?locale=sv-SE

Perhaps this should show 
a) browser language
b) Locale.currentLanguage.name
c) Locale.currentLocale.name

**Comment by SofiK** [comment]
If I have English as browser language and visits https://design.infor.com/code/ids-enterprise/latest/demo/components/about/example-index.html?locale=sv-SE 
locale is shown as en-US

**Comment by tmcconechy** [comment]
Right ok i forgot its showing the browser locale. I think i would expand it to show the three things i mentioned above.

**Comment by SofiK** [comment]
Yes, I think all of them are interesting :)

**Comment by jbrcna** [comment]
QA **Failed**
Verified in https://master-enterprise.demo.design.infor.com/components/about/example-index.html?locale=en-US

![image](https://user-images.githubusercontent.com/56722184/71660344-b2affe00-2d85-11ea-8896-cc964dc66662.png)

**Notes:**
It works fine in ALL Browsers **Except** in IE11. nothing seems to be working in IE11 with the current version 4.25.0-dev

**Comment by tmcconechy** [comment]
Fixed on https://github.com/infor-design/enterprise/issues/3289 - ready to retest IE 11

**Comment by CindyMercadoReyes** [comment]
Retested this ticket on IE and its now working as expected. Moving this ticket to the Done column.
