### ISSUE TITLE
DataGrid: Using Editors.Dropdown doesn't display value in IE11 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2919]
Describe the bug
A column that uses the Editors.Dropdown, does not display the selected value into the cell when using IE11.  Works fine with Chrome  

To Reproduce

1. Open an IE11 browser
2. Go to http://localhost:4000/components/datagrid/test-toggle-editable.html
3. Click on 'Edit' from the toolbar
4. Click on an Action cell and select a value from the dropdown 
5. After selection, the cell is blank, selected value is not displayed

Expected behavior
Selected value from the dropdown is displayed in the cell.  

Version
v4.23.0-dev

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

Additional context
Maybe related to https://github.com/infor-design/enterprise/issues/2305

**Comment by claudenbach** [comment]
![Git-2919](https://user-images.githubusercontent.com/39804038/66425113-8712b700-e9d4-11e9-8b7f-6c2af4fcbc23.gif)

**Comment by janahintal** [comment]
QA Passed. This issue is now resolved. Tested in http://4230-rc2-enterprise.demo.design.infor.com/components/datagrid/example-editable.html across all platform. Thank you!
