### ISSUE TITLE
Uplift Menu UI updates

### ISSUE THREAD

**Issue by kevinwhitedesign** [infor-design/enterprise#2920]
A continuation of the conversation happening here:
https://github.com/infor-design/enterprise/pull/2861#issuecomment-538058493
https://github.com/infor-design/enterprise/pull/2861#issuecomment-538061769
https://github.com/infor-design/enterprise/pull/2861#issuecomment-538112804

**Comment by tmcconechy** [comment]
Closing this in favor of https://github.com/infor-design/enterprise/issues/2925
