### ISSUE TITLE
Tabs '...' Popdown option id cut off in iOS Devices

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2927]
**Describe the bug**
Tabs '...' Popdown option id cut off in iOS Devices

**To Reproduce**
1. Open iOS device browser
2. Go to http://4220-beta0-enterprise.demo.design.infor.com/components/tabs/example-index.html
3. Click '...' button

**Expected behavior**
Pop down option should not be cut off

**Version**
Beta 4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66451245-23e55b00-ea8e-11e9-89e2-e7f8ecf64f45.png)

**Platform**
iOS Devices

**Additional context**
n/a

**Comment by tmcconechy** [comment]
Duplicate of #2800

**Comment by janahintal** [comment]
QA Passed. Popdown is now showing in toolbars. Thanks. 
Verified in http://master-enterprise.demo.design.infor.com/components/toolbar/example-inside-form-tag.html?theme=soho&variant=dark&colors=2578a9
