### ISSUE TITLE
Tabs: fix scaffolding around `afteractivated` event / renderloop

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#293]
**Describe the bug**

The `afteractivated` event fired by Tabs components doesn't always get fired properly.  The reason for this is it's being triggered at the end of a `transitionend` event.  While this event should be triggered the end of the fade-out animation of the `.tab-panel` element, in some cases such as the window losing focus, the event isn't triggered.

**To Reproduce**
This behavior is sporadic.  Steps to reproduce the behavior:
1. Go to http://localhost:4000/components/tabs/example-activated-event.html
2. Open this test in a code editor and change the event listener's condition from `activated.test` to `afteractivated.test`
3. In a browser, change the active tab with the keyboard and mouse
4. Occasionally, the `afteractivated` event will not fire.

**Expected behavior**

The `afteractivated` event should always be reliably triggered, even if the window loses/regains focus.

**Possible Solutions**

- Replace the [event listener for `transitionend`](https://github.com/infor-design/enterprise/blob/master/src/components/tabs/tabs.js#L1897) with a new RenderLoop Item (driven by `requestAnimationFrame`) that will more reliably trigger the event

**Screenshots**
n/a

**Platform**
n/a

**Additional context**

- A skipped test for this was added by @d-g-h here:  https://github.com/infor-design/enterprise/pull/271#pullrequestreview-132907278

**Comment by brianjuan** [comment]
http://localhost:4000/components/tabs/example-activated-event.html
http://master-enterprise.demo.design.infor.com/components/tabs/example-activated-event.html
Passed QA testing on all browsers.
