### ISSUE TITLE
Datagrid Singleselect: Can select multiple rows after sorting a column

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2930]
**Describe the bug**
Datagrid Singleselect: Can select multiple rows after sorting a column.

**To Reproduce**
1. Go to http://4220-beta0-enterprise.demo.design.infor.com/components/datagrid/example-singleselect.html
2. Click the row with Product ID = 2142201, row will be selected
3. Click Product Name column header to sort
4. Click the row with Product ID = 2445204
5. See issue: both rows will be selected

**Expected behavior**
Can only select single row even after sorting a column.

**Version**
- ids-enterprise: v4.21.0 to v4.22.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/66456824-45037700-eaa1-11e9-8238-b595d14d7df3.png)

**Platform**
 - All devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by deep7102** [comment]
Fixed by other issue #2961 with PR #3009

**Comment by tmcconechy** [comment]
Thanks @deep7102 i also retested it and it now seems ok on http://master-enterprise.demo.design.infor.com/components/datagrid/example-singleselect.html 👍

**Comment by jbrcna** [comment]
TEST PASSED

Verified in 
http://master-enterprise.demo.design.infor.com/components/datagrid/example-singleselect.html

All Browser and Device
