### ISSUE TITLE
Circle pager: not available on IE11 and Firefox69

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2933]
**Describe the bug**
Circle pager is broken when browser is resized to smallest

**To Reproduce**
1. Go to 'http://4220-beta0-enterprise.demo.design.infor.com/components/pager/example-circlepager.html'
2. Resize browser to smallest possible
3. Verify pagination

**Expected behavior**
Circle pager should be available

**Version**
4.22 Beta

**Screenshots**
![image](https://user-images.githubusercontent.com/52902639/66463707-383a4f80-eab0-11e9-8f05-5feb4ffc78a1.png)

**Platform**
 IE11 and Firefox69

**Additional context**
related to #2589

**Comment by tmcconechy** [comment]
See this working ok in FF 68 but not IE 11. This is minor since we are limiting IE11 fixes.

**Comment by tmcconechy** [comment]
Descoping this issue now see #3756
