### ISSUE TITLE
Editor: Insert Image does not work on other browsers 

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2937]
**Describe the bug**
Editor: Insert Image does not work on other browsers .

**To Reproduce**
1. Open Windows Edge, IE, Chrome, Mac Safari, Firefox, and mobile browsers
2. Go to http://4220-beta0-enterprise.demo.design.infor.com/components/editor/example-index.html
3. Click Insert Image icon in the Editor's toolbar
4. Click the "Insert" button in the modal
5. See issue: Image is not displayed

**Expected behavior**
Inserted image should be displayed in the Editor across all browsers.

**Version**
- ids-enterprise: v4.15.0 to v4.22.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/66476458-3e3c2a80-eac8-11e9-9b7b-0c67ca8baac1.png)

**Platform**
 - Mac: Safari and Firefox
 - Windows: Edge, IE, and Chrome
 - Android and iOS browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
The problem is just the path is giving an error (Cross Site). Suggest we change the path to something in the demo app. Like http://localhost:4000/images/placeholder-80x80.png using the relative path.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/editor/example-index.html
Verified QA Passed across all browsers. Will retest once beta is deployed.
![image](https://user-images.githubusercontent.com/39508864/69530167-8b0e8e80-0fac-11ea-88c4-a28024ff74ac.png)
