### ISSUE TITLE
Editor: Flex toolbar does not work in responsive view or mobile

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#2938]
**Describe the bug**
Editor: Flex toolbar does not work in responsive view or mobile.

**To Reproduce**
1. Go to http://4220-beta0-enterprise.demo.design.infor.com/components/editor/example-flex-toolbar.html
2. Resize the browser to responsive view (e.g 486x617) or open in mobile browsers
3. Highlight the first paragraph in the Editor
4. Open ... menu in the Editor toolbar
5. Select "Block Quote"
6. See issue: nothing happens, block quote won't be applied
7. Try all tools inside ... menu, all of them doesn't work

**Expected behavior**
Flex toolbar in Editor should work even in responsive view or mobile.

**Version**
- ids-enterprise: v4.18.0 to v4.22.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/66477044-b0f9d580-eac9-11e9-9b76-9430a32448fb.png)

**Platform**
 - All mobile browsers and desktop browsers in responsive view

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
@EdwardCoyle - Do you think this might be a general issue with any flex toolbar? Its not new but just want to be sure this isnt more serious than i think it is. Since the menu items arent working in the overflow.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/editor/example-flex-toolbar.html
Passed QA in all desktop and mobile browsers, toolbar is now working. Will retest once beta build is deployed.
