### ISSUE TITLE
Tabs Module: Missing ellipsis for long text in search field when in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2940]
**Describe the bug**
Tabs Module: Missing ellipsis for long text in search field when in responsive view

**To Reproduce**
1. Go to http://4220-beta0-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html
2.  Minimize the Browser 
3. Type a long text in the search field

**Expected behavior**
Field should have ellipsis and should not be cut off upon having a long text in the field

**Version**
Beta 4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66476631-b1de3780-eac8-11e9-9e9c-d3d3e4ec528f.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
The x is also missing.

**Comment by ericangeles** [comment]
@janahintal @tmcconechy, I couldn't see the bug and it seems working. The ellipsis state works when you out focus on the searchfield, while the x button shows when you click/focus the on it. Thoughts?

**Comment by ericangeles** [comment]
Seems working when you load the web app on `767px` below. I think it lack of resize event? Your thoughts, @tmcconechy ?

**Comment by tmcconechy** [comment]
I think we should be able to handle with css somehow? if i 
- type something big in the search
- make browser smaller
- at some point the code will step ellipsisizing

It does look like the width on the search field needs to be changed on resize? Where is this handled @EdwardCoyle ? Toolbar?

**Comment by janahintal** [comment]
Hi @tmcconechy, the issue is now resolved in Windows Browsers. However, when I maximize the screen in MacOS, either Safari or Chrome browser, the search field disappears. Is this expected? 

![image](https://user-images.githubusercontent.com/45757016/70718453-35b3da80-1d2b-11ea-83d1-af599ccb7a08.png)

**Comment by EdwardCoyle** [comment]
@janahintal not sure how you're getting that result.  I'm not seeing the same in either browser on Mac OS X:

![Screen Shot 2019-12-12 at 9 32 23 AM](https://user-images.githubusercontent.com/3249601/70720767-6d3a6c80-1cc2-11ea-9ed8-62e6cbc051a0.png)

Is it possible that on your browserstack instance, the window is larger than your viewport?

**Comment by tmcconechy** [comment]
Same with @EdwardCoyle - tried some combinations of resize and maximize and minimize. Not getting that result either. So its probably not a problem worth pursuing.

**Comment by janahintal** [comment]
Thanks guys, its now working on our end. Will move this to done.
