### ISSUE TITLE
Grid: Create an 8pt Grid system with newer css tech (WC)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#2941]
**Is your feature request related to a problem? Please describe.**

Design would also like to design around an 8pt grid cc @kevinwhitedesign - did some work in the enterprise-wc component with a ids-layout-grid. This component does even spacing. We can extend this by adding more settings to the web components to do other layouts.

Sync with design what they want and add new options to ids-layout-grid to do this along with examples, docs and tests. Feel free to do any relevant research along the way, nothing is set in stone but do think that it should be a web component.

**Describe the solution you'd like**

- [ ] Use css grid or flex box as needed
- [ ] Make a new `8pt-grid` system https://builttoadapt.io/intro-to-the-8-point-grid-system-d2573cde8632 with either flex or css grid (lean css grid)
- [ ] Show an example with all input fields in test a few components
- [ ] Add new settings to ids-layout-grid (do we like the name)

**Other notes**

See https://www.carbondesignsystem.com/guidelines/2x-grid/basics/ for another good example of a 8pt grid and good documentation.

**Comment by EdwardCoyle** [comment]
I think we pretty much have to keep the current grid system for now.  It's built into everything, including the majority of the samples in our demoapp.

**Comment by tmcconechy** [comment]
Yes most likely but thinking of this as a future option, especially if newer designs are focused on a 8pt system.

**Comment by tmcconechy** [comment]
Lets make a jira for this.... @inforandy the question is to make sure design is totally on board with this then we can add it in Dev.

**Comment by tmcconechy** [comment]
Calling this done for now.
