### ISSUE TITLE
Tab: Tab is cut off in iOS Multi Tab

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2946]
**Describe the bug**

**To Reproduce**
1. Open iOS Device Browser
2. Flip the screen to Landscape 
3. Go to http://4220-beta0-enterprise.demo.design.infor.com/components/tabs-multi/example-index.html

**Expected behavior**
Multi Tab should not be cut off in iOS devices

**Version**
Beta 4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66539790-febf1e00-eb5b-11e9-97b4-c946058bed48.png)

**Platform**
iOS Devices - iPhone XS iOS 12

**Additional context**
N/a

**Comment by tmcconechy** [comment]
I dont think this is very important to fix, or that it even can be. Its just that in this example there is not enough room so its cutting off the tab. This example has two tabs side by side so its not going to work perfect on a phone and thats not the design.

This is also similar to https://github.com/infor-design/enterprise/issues/971
