### ISSUE TITLE
Lookup: Unable to scroll in iOS device

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2949]
**Describe the bug**
Lookup: Unable to scroll in iOS device

**To Reproduce**
1. Open iOS Mobile and flip the phone to Landscape mode
2. Go to http://4220-beta0-enterprise.demo.design.infor.com/components/lookup/example-paging.html
3. Open the lookup filter
4. Try to scroll to see other records

**Expected behavior**
Should be able to scroll down

**Version**
Beta 4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66558974-1fe93400-eb87-11e9-9c6e-424d16556b0c.png)

**Platform**
iOS Mobile - iPhone XS iOS12

**Additional context**
N/A

**Comment by tmcconechy** [comment]
De scoping this for now
