### ISSUE TITLE
Lookup Control: Checking Select All after searching a keyword selects all the original list not all the filtered list 

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#295]
**Describe the bug**
Checking Select All after searching a keyword selects all the original list not all the filtered list 

**To Reproduce**
1. Go to http://480-beta0-sohoxi.demo.design.infor.com/components/lookup/example-editable.html
2. Open the Lookup field
3. Type "compressors" in the Search field then hit Enter, row with "I Love Compressors" and "Air Compressors" product name should show up
4. Check the check box header to select all 
5. Click Apply button
6. Expected values in Lookup field should be the "I Love Compressors" and "Air Compressors" only not all the items in the original list

**Expected behavior**
Expected values in Lookup field should be the "I Love Compressors" and "Air Compressors" only not all the items in the original list

**Screenshots**
None

**Platform**

 - All Browsers

**Additional context**
None

**Comment by ericangeles** [comment]
Tested it thoroughly to all browsers and seems to work perfectly.

**Comment by ericangeles** [comment]
@tmcconechy hello. If it's working on your end we can close this one.

**Comment by tmcconechy** [comment]
Yes, agreed. This may have been fixed last sprint on some lookup stuff i worked on.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done bucket.
