### ISSUE TITLE
Datagrid: getModifiedRows() are not correct when tabbing across row cells

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2958]
Describe the bug
Tabbing across the cells of a new row, without making a change, are showing up in the results from calling the method getModifiedRows().

To Reproduce
1. Using the attached test-new-row-dirty-indicators.html
2. Click on 'Add Row' toolbar button
3. Click on 'Get Modified Rows' toolbar button
4. Examine the console to get the results returned from getModifiedRows() - are correct at this point
5. Tab across the cells of the new row without making any cell changes
6. Click on 'Get Modified Rows' toolbar button
7. Examine the console to get the results returned from getModifiedRows()

Expected behavior
Method getModifiedRows should only include rows that have been modified.

Version
v4.23.0-dev

Additional context
Related to https://github.com/infor-design/enterprise/issues/2091

**Comment by claudenbach** [comment]
Additionally, is it possible to just return an array of dataViews?  Like dirtyRows().  In Landmark, I'm now forced to iterate the returned Array<SohoDataGridModifiedRow> to get the modified rows.

```
  public getDirtyRows(commitEdits: boolean = undefined): Array<LMDataView> {
    // return this.sohoDataGridComponent.dirtyRows();
    let modifiedRows = this.sohoDataGridComponent.getModifiedRows() as Array<SohoDataGridModifiedRow>;
    if (modifiedRows.length === 0) {
      return [];
    }

    // remove duplicate rows from the array since presently getModifiedRows may contain dups
    let dirtyRows = modifiedRows.filter((obj, pos, arr) => {
      return arr.map(mapObj =>
          mapObj['row']).indexOf(obj['row']) === pos;
    });

    return Object.keys(dirtyRows).map((key) => {
      let modifiedRow: SohoDataGridModifiedRow = dirtyRows[key];
      return modifiedRow.data;
    });
  }
```

**Comment by claudenbach** [comment]
[Git-2958.zip](https://github.com/infor-design/enterprise/files/3713655/Git-2958.zip)

**Comment by janahintal** [comment]
QA Passed. This issue is now verified and working in http://master-enterprise.demo.design.infor.com/components/datagrid/test-new-row-dirty-indicators.html
