### ISSUE TITLE
Locale: parseNumber does not parse correctly when locale has group of space

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#2959]
**Describe the bug**
When a locale has a group (thousands separator) defined as a space, Soho.Locale.parseNumber() does not parse the value correctly.

[test-number-with-group-of-space.zip](https://github.com/infor-design/enterprise/files/3714283/test-number-with-group-of-space.zip)

**To Reproduce**
1. Unzip the test-number-with-group-of-space.zip to ep > app > views > components > mask
2. Run http://localhost:4000/components/mask/test-number-with-group-of-space.html?locale=fr-FR
3. Enter a value in the Number Field, enough digits to have a group separator and tab out
4. The Parsed Number result field will only display the first digits

**Expected behavior**
The number should parse correctly

**Version**

- ids-enterprise: v4.22.0-beta.0

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/66600207-a5aab680-eb6a-11e9-80cc-e8296b16267d.png)

![parse-date-group-of-space](https://user-images.githubusercontent.com/20212079/66600296-d5f25500-eb6a-11e9-890d-c4ac8623cf56.gif)

**Platform**
 - All

**Additional context**
It appears that the regular expression removing spaces does not work correctly.

**Comment by fitzorama** [comment]
Probably should be high priority as any customer using the Landmark Web with a locale that has a group of space would not be able to save their decimal values correctly as parseNumber() is used to transform the value from the locale to Landmark format.

**Comment by tmcconechy** [comment]
I’ll take a look along with #2878 and see if they can be squashed together

**Comment by fitzorama** [comment]
Use fr-FR as it does.
I think you want something like > .replace(new RegExp('\\' + group, 'g'), '')

**Comment by fitzorama** [comment]
Looks like quite a few do, 18 by my count.

**Comment by johnbarcena** [comment]
Test FAILED
please see the screenshot for reference.

Browser: **EDGE**
**locale=ar-SA**
**Expected Result**
- Number Field should display 1٬234٬567٫12
- Parsed Number result field should display 1234567.12
![image](https://user-images.githubusercontent.com/52902639/67000494-82ec4500-f10a-11e9-9ff8-fb41763c34b8.png)

Browser: **SAFARI**
**locale=ar-SA**
**Expected Result**
- Number Field should display 1٬234٬567٫12
- Parsed Number result field should display 1234567.12
![image](https://user-images.githubusercontent.com/52902639/67000676-d8285680-f10a-11e9-85ba-0cb7a1725a5c.png)

Browser: **IE11**
**locale=ar-SA**
**Expected Result**
- Number Field should display 1٬234٬567٫12
- Parsed Number result field should display 1234567.12
![image](https://user-images.githubusercontent.com/52902639/67001416-402b6c80-f10c-11e9-8fc9-7e3c30e030ed.png)


**locale=en-US**
**Expected Result**
- Number Field should display 1,234,567.12
- Parsed Number result field should display 1234567.12
![image](https://user-images.githubusercontent.com/52902639/67001240-d4490400-f10b-11e9-9331-952cdb8807d3.png)


**locale=es-ES**
**Expected Result**
- Number Field should display 1.234.567,12
- Parsed Number result field should display 1234567.12
![image](https://user-images.githubusercontent.com/52902639/67001554-9e584f80-f10c-11e9-8a9d-77eac7068db0.png)


**locale=fr-FR**
**Expected Result**
- The Number Field should display 1 234 567,12
- Parsed Number result field should display 1234567.12
![image](https://user-images.githubusercontent.com/52902639/67001769-07d85e00-f10d-11e9-888e-c75f8734a965.png)


Browser: **Firefox**
**locale=ar-SA**
**Expected Result**
- Number Field should display 1٬234٬567٫12
- Parsed Number result field should display 1234567.12
![image](https://user-images.githubusercontent.com/52902639/67001940-64d41400-f10d-11e9-9d32-394deb8d7000.png)

**Comment by johnbarcena** [comment]
btw, ANDROID and iOS work perfectly fine in all four locales.

**Comment by tmcconechy** [comment]
New fixes have been added for the noted cases.

**Comment by jbrcna** [comment]
Test Failed . Issue still persist **except** on the ff browsers and locales
-IE11 en-US 
-IE11 es-ES 
-IE11 fr-FR 

Verified in http://master-enterprise.demo.design.infor.com/components/mask/test-number-parsing.html?

**Comment by tmcconechy** [comment]
@jbrcna Can you please be more explicit about what is NOT working. I find it confusing that you say that the issue is still there except some browsers?

I
- went to http://master-enterprise.demo.design.infor.com/components/mask/test-number-parsing.html
- in IE 11
- type 123456789.12
- results as expected

I think all the main cases are fixed here so probably just consider this done. Unless im missing some tests where it isnt working?

**Comment by tmcconechy** [comment]
Ok it was effecting a few other PR's then. I will just move this to done as is. Im seeing it working ok

**Comment by jbrcna** [comment]
Hello @tmcconechy, to answer your question, based on the noted cases above on my first comment
Test Passed on the ff cases below
-IE11 en-US
http://master-enterprise.demo.design.infor.com/components/mask/test-number-parsing.html?locale=en-US
-IE11 es-ES
http://master-enterprise.demo.design.infor.com/components/mask/test-number-parsing.html?locale=es-ES
-IE11 fr-FR
http://master-enterprise.demo.design.infor.com/components/mask/test-number-parsing.html?locale=fr-FR

Test Failed on the ff cases below

1.  EDGE
http://master-enterprise.demo.design.infor.com/components/mask/test-number-parsing.html?locale=ar-SA
2. SAFARI
http://master-enterprise.demo.design.infor.com/components/mask/test-number-parsing.html?locale=ar-SA
3. IE11 
http://master-enterprise.demo.design.infor.com/components/mask/test-number-parsing.html?locale=ar-SA
4. Firefox
http://master-enterprise.demo.design.infor.com/components/mask/test-number-parsing.html?locale=ar-SA

enter 1234567.12 and tab out
If unable to enter the period, try pasting 1234567٫12
Number Field should display 1٬234٬567٫12
Parsed Number result field should display 1234567.12

**Comment by jbrcna** [comment]
see screenshot for reference
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/56722184/67540762-36f85c00-f719-11e9-8ad7-c1624ebed3df.png">


<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56722184/67540794-5beccf00-f719-11e9-9c48-0379417a0c8d.png">

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/56722184/67540886-a706e200-f719-11e9-9bbf-7ca857b8bb99.png">

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/56722184/67540922-bd14a280-f719-11e9-85e7-e6c2c3071f62.png">

**Comment by tmcconechy** [comment]
Ah yeah thats because in Arabic the period is a different character. You would need an arabic keyboard to type it. So i think this is fine to ignore for now.

**Comment by jbrcna** [comment]
Thanks @tmcconechy . 
I agree , I way over thought that :)
