### ISSUE TITLE
Datagrid: cell dirty indicators are on the wrong cells after performing removeRow

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#2960]
Describe the bug
The cell dirty indicators will be on the wrong cells after performing a removeRow().

To Reproduce
1. Using the attached test-dirty-indication-after-remove-row.html
2. Dirty the cells of row 1 (has Row Id 1)
3. Click on 'Delete Row 1' toolbar button
4. Dirty cell indicators from Row Id 1 are now on Row Id 2
5. Click on 'Show Modified' toolbar button
6. Contains data from the removed row?

Expected behavior
Dirty cell indicators are still correct after a removeRow

Version
v4.23.0-dev

**Screenshots**

**Comment by claudenbach** [comment]
In datagrid.js, the api for removeRow is defined as 
removeRow(row, noSync, noTrigger).

However in soho-datagrid.component.d.ts, the api for removeRow is defined as 
removeRow(data: any): void;

What does the noSync argument mean?

**Comment by claudenbach** [comment]
[Git-2960.zip](https://github.com/infor-design/enterprise/files/3714531/Git-2960.zip)

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/test-dirty-indication-after-remove-row
Verified Passed QA on all browsers, will retest once beta is deployed.
