### ISSUE TITLE
TreeGrid: Selects incorrect child row

### ISSUE THREAD

**Issue by carerer2** [infor-design/enterprise#2961]
**Describe the bug**
The Datagrid have an issue in selection scop for the secondary tree node which has children and same level item

**To Reproduce**
1. Create a treegrid and make it multiple select
2. set the data as below, make the id5 is the sendonary tree node and only have 2 children id6 and id7. Also, create the same level item id8 with id5:
```
this._data = [{
        id: 1, escalated: 0, depth: 1, expanded: true, taskName: 'Follow up action with Residental Housing', desc: 'Contact sales representative with the updated purchase order.', comments: 2, time: '22:10 PM', children: [
          { id: 2, escalated: 0, depth: 2, taskName: 'Follow up action with Universal HMM Logistics', desc: 'Contact sales representative.', comments: 2, time: '22:10 PM' },
          {
            id: 3, escalated: 0, depth: 2, expanded: true, taskName: 'Follow up action with Residental Shipping Logistics ', desc: 'Contact sales representative.', comments: 2, time: '7:04 AM', children: [
              { id: 4, escalated: 0, depth: 3, taskName: 'Follow up action with Universal Shipping Logistics Customers', desc: 'Contact sales representative.', comments: 2, time: '14:10 PM' },
              {
                id: 5, escalated: 0, depth: 3, expanded: true, taskName: 'Follow up action with Acme Universal Logistics Customers', desc: 'Contact sales representative.', comments: 2, time: '7:04 AM', children: [
                  { id: 6, escalated: 0, depth: 4, taskName: 'More Contact', desc: 'Contact sales representative.', comments: 2, time: '14:10 PM' },
                  { id: 7, escalated: 0, depth: 4, taskName: 'More Follow up', desc: 'Contact sales representative.', comments: 2, time: '7:04 AM' },
                ]
              },
              { id: 8, escalated: 0, depth: 3, taskName: 'Follow up action with Residental Housing', desc: 'Contact sales representative with the updated purchase order.', comments: 2, time: '18:10 PM' }
            ]
          }
        ]
      }];
    }
```
	
3. select the item id5

**Expected behavior**
The id5, id6 and id7 should be selected and id8 should be unselected

**Version**
- ids-enterprise: [^5.5.2]

**Screenshots**
![image](https://user-images.githubusercontent.com/48427258/66618716-d17e7880-ec0c-11e9-9294-c1d9c9d08b61.png)

**Comment by tmcconechy** [comment]
@deep7102 do you think when you get a chance you can test the data on https://github.com/infor-design/enterprise/pull/2990 and see if this actually fixes that as well?

**Comment by carerer2** [comment]
One more case: If change the id5's expand = false. I expect the id5's tree icon should be "+" and the children id6, id7 should be hidden. But the existing behavior is even the id5's tree icon is "+", the id6 and id7 still can display.

**Comment by janahintal** [comment]
Will Move to QA Failed. 

Steps: 
1. Goto http://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-select-multiple.html
2. Click '+' in Id 5
3. Select Id 6
4. Close the tree and click '-' in Id 5
5. Reopen Id 5 and click '+' then select Id 7

Expected : 
Id 5  should be 'Checked' and not be Partial

**Comment by tmcconechy** [comment]
@janahintal im not able to reproduce this. Can you clarify step 4? After i open it again it is partial as expected.

![Screen Shot 2019-10-23 at 7 32 05 AM](https://user-images.githubusercontent.com/814283/67388738-3a4be600-f567-11e9-97e8-d1be4f1ad90a.png)

**Comment by deep7102** [comment]
@janahintal in order to `Id 5 should be 'Checked' and not be Partial`, all three rows with id `5, 6 and 7` must be selected, but in your steps only selecting `6 and 7` and did not selecting `id 5` so in that case `Id 5 should be Partial` as expected.
