### ISSUE TITLE
Calendar : Add Event modal popup modal fields are cut off after minimizing the screen 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2962]
**Describe the bug**
Calendar : Add Event modal popup modal fields are cut off and overlapping the modal after minimizing the screen 

**To Reproduce**
1. Go to http://4220-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=uplift&variant=light&colors=0563C2
2. Click '+' and Add Event Modal button
3. Minimize the screen 
5. Maximize the screen again

**Expected behavior**
Fields should not be cut off or overlap the modal 

**Version**
Beta 4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66622791-a8b1af80-ec1b-11e9-94af-6623169ead14.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
I also saw this and have a fix on my branch for #1757

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. However, I found other issues and opened GitHub Ticket: 3089.

**Comment by CindyMercadoReyes** [comment]
A BDD was created for this ticket.  Please see attached below.
[story_Calendar.docx](https://github.com/infor-design/enterprise/files/3836515/story_Calendar.docx)
