### ISSUE TITLE
Message : unexpected scrollbar appears even if its not needed. 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2964]
**Describe the bug**
Message : unexpected scroll appears even if its not needed. 

**To Reproduce**
1. Go to http://4220-rc0-enterprise.demo.design.infor.com/?theme=uplift&variant=dark&colors=0053B1# and minimize the view to responsive 
2. Go to Message components 
3. Click Success Example button 

**Expected behavior**
Modal should not have a scrollbar

**Version**
RC 4.22 Regression

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66627954-e28cb100-ec2f-11e9-8c0c-c2af58c1202a.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
On review of this issue Im closing #2964 as wont fix as you will need to scroll if the text is much bigger. So it is actually working correctly its just that the text is just too much to fit with shorter break points.

So really it's working ok.

**Comment by tmcconechy** [comment]
I was still able to reproduce this..

- load Windows Chrome (78)
- go to http://localhost:4000/components/message/example-index.html
- click the success example button (notice the scroll bar)

**Comment by CindyMercadoReyes** [comment]
This is still appearing for Win 10 Edge 18. Please see screen shot attached. 
![bs_win10_Edge_18 0](https://user-images.githubusercontent.com/39101346/69166734-b8959c80-0ac1-11ea-9d6e-e610794f05a0.jpg)

**Comment by janahintal** [comment]
This issue is now resolved and now working in http://master-enterprise.demo.design.infor.com/
![image](https://user-images.githubusercontent.com/45757016/69526124-73cba300-0fa4-11ea-8e26-cc00d2f2ceb7.png)
