### ISSUE TITLE
Calendar:Label for Company Holiday Legend is not displayed using Vibrant/Uplift with Dark Variant

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2965]
**Describe the bug**
Company Holiday Legend Label is not readable using Vibrant Theme and Dark Variant

**To Reproduce**
1. Go to 'http://4210-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=uplift&variant=dark&colors=0053B1' 
and/or
http://4220-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=uplift&variant=dark&colors=0053B1

2. Change Theme to Vibrant
3. Change Variant to Dark

**Expected behavior**
Company Holiday Legend Label should be displayed
![image](https://user-images.githubusercontent.com/52902639/66641122-afa4e600-ec4c-11e9-81f1-dac383008ce5.png)

**Version**
4.21 
http://4210-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=uplift&variant=dark&colors=0053B1

4.22 RC
http://4220-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=uplift&variant=dark&colors=0053B1

**Screenshots**
![image](https://user-images.githubusercontent.com/52902639/66639503-846cc780-ec49-11e9-9be9-69373151c826.png)

**Platform**
ALL

**Additional context**
Note: **'+'** button is missing in **4.20 enterprise** but that screenshot should be the expected behavior for Company Holiday Legend. 

Also, it is much darker with the current version 4.22-rc0

**Comment by jbrcna** [comment]
Test Passed

Verified in
http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=uplift&variant=dark&colors=0053B1

All Browser and Devices
