### ISSUE TITLE
Calendar: Unable to create new Event using Double Click() on iOS Mobile

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2967]
**Describe the bug**
User cannot create an Event using Double Click with iOS Devices

**To Reproduce**
1. Go to 'http://4220-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html?'
2. Double Click on any day then Verify New Event tool tip

**Expected behavior**
User should be able to create an Event using Double Click
New Event tooltip should be displayed when user Double Click on any day/date
![image](https://user-images.githubusercontent.com/52902639/66644133-c3ebe180-ec52-11e9-90c1-112124809f67.png)

**Version**
4.22 rc0

**Screenshots**

**Platform**
iOS Mobile

**Additional context**

**Comment by tmcconechy** [comment]
Is it even possible to double click on mobile? Double tap maybe?

**Comment by johnbarcena** [comment]
Yes, the correct term is double tap. It works fine on android. Maybe because I tested it on Browserstack that's why I thought of it as click instead of tap 😅.

**Comment by tmcconechy** [comment]
Gotcha , this wasn’t implemented but it’s a fine idea

**Comment by tmcconechy** [comment]
De scoping this for now
