### ISSUE TITLE
Contextual Action Panel: resizes a little when user input large amount of text on EDGE and IE11

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#2968]
**Describe the bug**
when you input a large amount of text in the comment box panel resizes a little

**To Reproduce**
1. Go to 'http://4220-rc0-enterprise.demo.design.infor.com'
2. Paste this text to comment box 
"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
3. Click checkbox (freight)
4. Notice that panel will resize a little

**Expected behavior**
Panel should not resize

**Version**
4.22 rc0

**Screenshots**

**Platform**
EDGE and IE11

**Additional context**

**Comment by EdwardCoyle** [comment]
I was able to reproduce.  This is possibly related to modal changes from #2433

**Comment by janahintal** [comment]
Issue still exists after resizing the window. 

Steps:

1. Minimize / Resize the window
![image](https://user-images.githubusercontent.com/45757016/67835412-d86e1c00-fb24-11e9-9052-aa1167d6b5de.png)

2. Maximize the window view
![image](https://user-images.githubusercontent.com/45757016/67835336-a8267d80-fb24-11e9-8300-54ad8cfeb11d.png) 

3. Click the checkbox
![image](https://user-images.githubusercontent.com/45757016/67835445-ee7bdc80-fb24-11e9-9122-8fea0e793f4b.png)

**Comment by tmcconechy** [comment]
@janahintal for the remaining issues can you make a new issue please. IE is almost unsupported now so this is minor we will maybe fix this at a future date if we can.
