### ISSUE TITLE
Lookup Control: No Dirty Tracking Indicator on the Dirty Tracking Lookup field

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#297]
**Describe the bug**
No Dirty Tracking Indicator on the Dirty Tracking Lookup field

**To Reproduce**
1. Go to http://480-beta0-sohoxi.demo.design.infor.com/components/lookup/test-states.html
2. Open the Dirty Tracking lookup field
3. Select Different Compressor
4. Dirty Tracking Indicator will not be displayed

**Expected behavior**
The yellow dirty tracker should appear

**Screenshots**
<img width="1158" alt="lookup dirty tracker" src="https://user-images.githubusercontent.com/39101346/42053614-faa2b086-7adf-11e8-965a-9a29e6171fed.png">

**Platform**

 - All Browser Name

**Additional context**
None

**Comment by tmcconechy** [comment]
Seems like this has not worked in a few versions. We probably should have at least a working functional and visual test of this. So make this work and add a test.
