### ISSUE TITLE
Charts: Unable to select a legend in iOS devices

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#2973]
**Describe the bug**
Charts: Unable to select a legend in iOS devices

**To Reproduce**
1. Open an iOS device and open a browser
2. Goto http://4220-rc0-enterprise.demo.design.infor.com
3. Go to charts section
4. In Pie chart, select the yellow legend 
5. Select the Green legend

_Issue also exist in all chart that has legend._

**Expected behavior**
Should be able to select the legend and focus on the selected legend

**Version**
rc 4.22

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/66741649-90a29000-eea8-11e9-8383-4d4e6a24cb9e.png)

**Platform**
iOS Mobile Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping for now
