### ISSUE TITLE
Modal: Allow opacity of the overlay to be controlled by setting

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#2975]
In our Infor ERP application, popups may be displayed over the main page to show additional prompts for input (and prevent input on the main page), but some data on the main screen may be relevant, so the user still wants to be able to read it.

We have a customer who has some users that use a "privacy filter", which is a piece of film placed over the monitor that prevents people looking in from the side to read the screen and to protect sensitive information. This naturally darkens the screen a little bit too, so in combination with the modal overlay's dark opacity, it makes the background very difficult to read regardless of the theme used. They have logged an ERS in Infor Xtreme to alter this "darkness" of the popup overlay on a per-user basis.

For us to be able to offer this to the customer, what we would like is to give the user control of the opacity of the modal/message dialog overlay via a new "opacity" setting. At the moment this looks like it is set as .7 in the standard IDS code and none of the API settings appear to address the ability to change this opacity value...

https://design.infor.com/code/ids-enterprise/latest/modal#modal
https://design.infor.com/code/ids-enterprise/latest/message#message

Ideally a new "opacity" setting on modal/message APIs would support a range off values, say 10% through to 90%, which we can then offer to the user as a preference setting in our application, which we can then pass into the modal/message IDS API on creation.

**Comment by tmcconechy** [comment]
You could also override it with a css class/override. But we also have some possible requirements like dragging the modals which may mean a need for less opacity as well.

**Comment by sanx72** [comment]
As much as possible, we try to avoid having bespoke changes to IDS as over the life-span of our product using UX3, then SoHo, then SoHo Xi and now IDS controls, we've hit too many problems where a new version breaks a bespoke change. As a small team, we don't always have time to keep re-implementing changes, which is why we prefer them to go into standard product.

**Comment by janahintal** [comment]
This issue is now resolved. Thanks! Verified in http://master-enterprise.demo.design.infor.com/components/modal/test-overlay-opacity.html?theme=uplift&variant=light&colors=0563C2 & http://master-enterprise.demo.design.infor.com/components/message/test-overlay-opacity?theme=uplift&variant=light&colors=0563C2
