### ISSUE TITLE
toast does not support buttons and therefore does not replace inforSlideInMessage

### ISSUE THREAD

**Issue by ronperkinsuk** [infor-design/enterprise#2976]
We were using inforSlideInMessage which supported buttons but now this has been replaced with toast I don't see anyway to have buttons shown now. It only support text links!

Is there any other component that we could use similar to the old inforSideInMessage which supports buttons?

**Comment by tmcconechy** [comment]
A closer replacement is the notification component http://latest-enterprise.demo.design.infor.com/components/notification/example-index.html

It also only supports a link and a close button.

If you have the need for buttons a modal or message component would be the right thing.
