### ISSUE TITLE
Editor: Pasting into HTML mode does not always strip attributes

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#2987]
**Describe the bug**
When pasting html into the editor using HTML mode, the style attribute is not always stripped which can lead to usage of unsupported font families. 

**To Reproduce**
1. Go to http://localhost:4000/components/editor/test-html-view.html
2. Highlight all of the text in the editor and click Delete to remove it
3. Paste the following into the editor 
`<p><span style="font-family: serif">TEST</span></p>`
4. Click on the VISUAL button to switch modes
5. TEST displays using a serif font which is not supported by the editor

**Expected behavior**
TEST should display using the supported font of the editor.
Pasting html into the editor should work the same regardless of mode.

**Version**

- ids-enterprise: v4.23.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/66920076-327cc680-efe8-11e9-904c-7f3908d16f79.png)
![image](https://user-images.githubusercontent.com/20212079/66920087-39a3d480-efe8-11e9-8fa6-4cc109c9ae31.png)

**Platform**
 - All

**Additional context**
I found when using HTML mode, pasting the text above without a paragraph tag or other container tag like a div, the style attribute was removed.

**Comment by jbrcna** [comment]
**QA PASSED**
Verified in http://master-enterprise.demo.design.infor.com/components/editor/test-html-view.html across all browser and devices. moving this ticket to Done column.
