### ISSUE TITLE
Flex Toolbar: Non-ajax submenus disappearing and check marks overlaying text

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#2989]
**Describe the bug**
Checkmarks are overlaying text when there are no icon buttons in a flex toolbar. Since no icons are detected in [toPopupMenu()](https://github.com/infor-design/enterprise/blob/master/src/components/toolbar-flex/toolbar-flex.js#L495), hasIcons is false on the flex toolbar's settings and the .has-icons class isn't set on the ul.

Also, when writing a test for this, I discovered that a non-ajax submenu isn't opening correctly.

**To Reproduce**
1. Copy [test-checked-submenu-no-icons.zip](https://github.com/infor-design/enterprise/files/3735295/test-checked-submenu-no-icons.zip) into your codebase.
2. Navigate to '/components/toolbar-flex/test-checked-submenu-no-icons.html'
3. Click on the more menu in the toolbar.
4. See the checkmark is overlaying the first item's text
5. Hover over 'More Three'
6. See both more menus disappear.

**Expected behavior**
There should be enough space for the checkmark, and the submenu should open correctly.

**Version**
- ids-enterprise: v4.23.0-dev

**Screenshots**
![CheckMarkAndSubmenuError](https://user-images.githubusercontent.com/22107636/66937281-cceb0300-f004-11e9-86fe-2c2924e2bb58.gif)

**Platform**
 - All

**Comment by tmcconechy** [comment]
The selectable examples http://master-enterprise.demo.design.infor.com/components/popupmenu/example-selectable.html seems ok.

You may just need class is-selectable https://github.com/infor-design/enterprise/blob/master/app/views/components/popupmenu/example-selectable.html#L10

But i do not have sumenus in the example to test.

**Comment by Sovia** [comment]
I think it's toolbar specific, rather that generic popupmenu.

**Comment by Sovia** [comment]
Do we need to pass in a setting or something for if the more menu is getting constructed via a ajax callback?

**Comment by EdwardCoyle** [comment]
Switched this to a `[5]` because the lifecycle issue is a bit more complicated than we originally thought.  It requires building a handful of tests, as well as potentially change the way the menu renders.

**Comment by janahintal** [comment]
Hi, Verified this issue as this was also set to Done by Automation. Thanks
This issue is now resolved. http://master-enterprise.demo.design.infor.com/components/toolbar-flex/test-more-actions-selectable.html?theme=uplift&variant=dark&colors=0053B1
http://master-enterprise.demo.design.infor.com/components/popupmenu/example-partially-selectable?theme=soho&variant=dark&colors=808080#

**Comment by tmcconechy** [comment]
@janahintal i fixed the automation and moved back the wrongly moved issues.
