### ISSUE TITLE
Modal Control: Submit button is not enabling

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#299]
**Describe the bug**
Submit button is not enabling

**To Reproduce**
1. Go to http://480-beta0-sohoxi.demo.design.infor.com/components/modal/test-validation2.html
2. Tab through the input field then type "test"
3. Click the input field
4. Select an item in the Type dropdown
5. Type "test name" in the Name text box
6. Type "test description" in the Description text area
7. Type "test editor" in the Editor field
8. Submit button will not enable
**Expected behavior**
The "Submit" button should be enabled

**Screenshots**
![bs_win10_edge_17 0](https://user-images.githubusercontent.com/39101346/42054184-b6da5ffa-7ae1-11e8-82fb-c77d8285c287.jpg)

**Platform**

 - All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
This did work in 4.7.0 - we should test after the validation changes are merged in though so i think this can stay on master.

But marginally should be patched...

**Comment by CindyMercadoReyes** [comment]
Thisi issue is now resolved. Tested this ticket using updated url: http://480-rc0-sohoxi.demo.design.infor.com/components/modal/test-validation-editor.html. Closing out this ticket.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Closing out this ticket.
