### ISSUE TITLE
Datagrid: Export to Excel causes Excel to display file extension warning

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#2995]
**Describe the bug**
Hi, when using exportToExcel method in Datagrid and opening the exported file, Excel is displaying a message: 
_The file format and extension of 'xxxxx.xls' don't match_

**To Reproduce**
1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-export-from-button](https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-export-from-button)
2. Click on 'Export to Excel' button
3. Open exported file
4. See message

**Expected behavior**
When exporting CSV we don't get that message (but there are Unicode issues in CSV)

**Version**

- ids-enterprise: v4.22.0 (but also seen in earlier versions)

**Screenshots**
![excel-export](https://user-images.githubusercontent.com/34129313/66998712-68e83d80-f0dd-11e9-8553-c846c8a02d49.png)

**Platform**
 - OS Version: [e.g. Windows 7 and 10
 - Excel 2013 / 2019

**Additional context**
Thanks

**Comment by tmcconechy** [comment]
There does not seem to be any solution for this. We did try this in the past.
BTW: Nothing no https://stackoverflow.com/questions/28403642/how-to-fix-file-format-and-extension-dont-match seems to work.

**Comment by tmcconechy** [comment]
Will leave it open for a while in case someone has a new suggestion. But for many years we have tried to fix this unsuccessfully. We cant get around the browser warnings.

**Comment by jonathanamiran** [comment]
Thanks.
Before opening this issue I've checked if Excel export works "properly" in DataTables
[https://datatables.net/extensions/buttons/examples/initialisation/export.html](https://datatables.net/extensions/buttons/examples/initialisation/export.html)
and it does - although they export in xlsx format.

**Comment by tmcconechy** [comment]
I'm getting the same error in data tables as we get.

![Screen Shot 2019-10-17 at 9 47 19 AM](https://user-images.githubusercontent.com/814283/67014630-2a458980-f0c3-11e9-8102-7432cdc969a4.png)

**Comment by tmcconechy** [comment]
Hmm i see. I guess we would have to change the entire export procedure to use the binary xlsx format.... Might be doable.

**Comment by tmcconechy** [comment]
Can look at what https://tableexport.v5.travismclarke.com/#install-manually-using-less-than-script-greater-than-tags is doing (note to self)

**Comment by tmcconechy** [comment]
Closing this as a duplicate instead of in favor of https://github.com/infor-design/enterprise/issues/4709
