### ISSUE TITLE
Mask: Change event is not fired in Safari if decimal value is not entered

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#3002]
**Describe the bug**
When a field is defined with a mask with a decimal and the value entered does not contain the decimal, Safari does not fire a change event.

**To Reproduce**
1. In Safari, go to http://master-enterprise.demo.design.infor.com/components/mask/test-number-parsing.html
2. Enter `12345` into the Number Field and tab out
3. Error > The Parsed Number result field does not display the value
4. Clear the Number Field and enter `54321.12` and tab out
5. The Parsed Number result field displays `54321.12`

**Expected behavior**
Expect the change event to fire

**Version**

- ids-enterprise: 4.23.0-dev

**Screenshots**

**Platform**
 - Device (if applicable): Apple
 - OS Version: 10.14 and IOS 13
 - Browser Name Safari
 - Browser Version 10.14 > Safari v12.1.1 (146072.6.1.1)  and IOS 13

**Additional context**

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
