### ISSUE TITLE
Datagrid: Empty Message in uplift theme has a shadow in the icon

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3003]
**Describe the bug**
Datagrid: Empty Message in uplift theme has a shadow 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging.html?theme=uplift&variant=dark&colors=0053B1
2. In Id column, type "/"

**Expected behavior**
Empty state should be displayed

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/67191084-9efe2800-f423-11e9-9ffd-588366d242fc.png)

**Platform**
All, Browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This is the style of the new empty message in uplift. Its showing a shadow element to draw interest to the icon and is 100% correct according to design.

http://master-enterprise.demo.design.infor.com/components/emptymessage/example-index.html?theme=uplift&variant=light&colors=0563C2
