### ISSUE TITLE
Datagrid: example-export-from-button - missing columns

### ISSUE THREAD

**Issue by johnbarcena** [infor-design/enterprise#3004]
**Describe the bug**
**example-export-from-button**
The columns 'Quantity' and 'Status' are not shown after you remove them and then Drag and Drop another column to where the column 'Quantity' is located ( column[3] ).

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html'
2. Click on '...' then select 'Personalized Columns'
3. Tick 'Quantity' and 'Status'
4. Drag and Drop 'Action Item' (could be any column/item) to column(3) where 'Quantity' column is located
5. Click on '...' then select 'Personalized Columns'
6. Tick 'Quantity' and 'Status'
7. Notice that 'Quantity' and 'Status' are missing or not shown.
8. Drag and Drop 'Action Item' to another column
9. Notice that 'Quantity' and 'Status' are shown.

see error at step 7

**Expected behavior**
The column(s) should show up in particular order that the user has/have set
The column values on the Datagrid should match the values on the exported files

**Version**
4.23

**Screenshots**
![datagrid-example-exportfrombutton](https://user-images.githubusercontent.com/52902639/67191440-2fd50380-f424-11e9-8bfa-f384d7da63b6.gif)

Here's a video just in case:
[Video MP4 (1516x736).mp4.zip](https://github.com/infor-design/enterprise/files/3749897/Video.MP4.1516x736.mp4.zip)

**Platform**
ALL

**Additional context**
-the last column (Extra) is not affected, i.e if you remove the column Extra then drag and drop an item to where column 'Extra' is located then add the column 'Extra' again, it will show up

![datagrid-example-exportfrombutton-Extra](https://user-images.githubusercontent.com/52902639/67193851-99efa780-f428-11e9-8237-465836c78b26.gif)

[Video MP4 (1516x736).mp4.zip](https://github.com/infor-design/enterprise/files/3749963/Video.MP4.1516x736.mp4.zip)

**Comment by jbrcna** [comment]
Test **PASSED**
Verified in http://master-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html across All Browsers.

the issue is now resolved added columns are now displayed.
