### ISSUE TITLE
Datagrid: Time filter doesn't get applied after clicking "Set Time" button

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3005]
**Describe the bug**
Datagrid: Time filter doesn't get applied after clicking "Set Time" button.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
2. In the "Time" column header, open the time picker
3. Select 1:30 AM then click "Set Time" button
4. See issue: Datagrid will not be filtered based on the selected filter in the Time column

**Expected behavior**
Datagrid should be filtered based on the selected time filter upon clicking "Set Time" button.

**Version**
- ids-enterprise: v4.21.0 to v4.22.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/67198540-c3f99780-f431-11e9-905d-7bf8642648e6.png)

**Platform**
 - All devices, OS, and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This is almost a bug, but has always worked this way. I agree it might be nice if it did filter on clicking apply but as of now it will filter when pressing enter like the other text input fields.

Will keep this open for consideration as it does make some sense.

**Comment by tmcconechy** [comment]
Descoping this for now
