### ISSUE TITLE
Datagrid: The focus border is shown on the second last clicked menu

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3006]
**Describe the bug**
We've found a minor issue with the focus border around the Actions (...) menus in datagrids that when you click a ... menu the border focus styling remains on the previously clicked menu.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-contextmenu.html
2. Scroll to the Actions column
3. Click the third ... menu
4. Click the last ... menu
(... 5. Click another ... menu)

**Expected behavior**
When the last ... menu is clicked that one should get the focus border (or atleast the previous one should not have it)

**Version**

- ids-enterprise: v 4.21.3

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/67202003-e7a7e800-f407-11e9-9d2a-d0af1c6c78e2.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 77.0.3865.120 (Official Build) (64-bit)

**Additional context**
-

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
