### ISSUE TITLE
Datepicker: setting date format with comma character clears the value after losing focus

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#3008]
**Describe the bug**
When we set the date format to a value comming from Locale containing comma (for example en-US medium date format 'MMM d, yyyy') then after selecting any date, the field gets cleared.

**To Reproduce**
1. Set dateFormat of date picker with 'MMM d, yyyy'
2. open it in browser and select any date
3. click somewhere else to get rid off focus on picker

**Expected behavior**
Any date and time formats from locales should be valid in date pickers and also grid filters

**Version**
- ids-enterprise: 4.21.0

**Screenshots**
![pdhTo2aF0Q](https://user-images.githubusercontent.com/11279863/67214294-ce129a80-f41f-11e9-8853-173120207614.gif)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to Done column.
