### ISSUE TITLE
Header: Tooltip Text is unreadable when using SoHo Dark Theme

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#3011]
The Tooltip Text for items on the Header of a page, when SoHo Dark Theme is enabled, is unreadble with most colours as it uses black text. All the other themes use white text. This was not an issue in previous releases (e.g 4.14). Other themes use white text so are readable.

To reproduce...

Use your own example page...

https://design.infor.com/code/ids-enterprise/latest/demo/components/header/example-disabled-buttons

Using the "More" menu, select Theme = SoHo, then Variant = Dark, then any Colour except default, Azure or Slate show best. Note: using "Default" shows a white tooltip with black text which is of course readable.

Tried FireFox and Chrome on Windows 8.1 PC

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/header/example-disabled-buttons?theme=soho&variant=dark&colors=941e1e
Passed QA in all browsers. Also tested using all Colors and Variants in both Soho and Uplift.
![image](https://user-images.githubusercontent.com/39508864/67914193-56383300-fbca-11e9-972f-6690f111f233.png)
