### ISSUE TITLE
Datagrid: example-grouping-filter - Excluded group is shown 

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3012]
**Describe the bug**
Given that the user has applied a filter 
After the user ordered the list (ascending/descending) it shows the excluded group

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-filter.html'
2. Input Filter and Apply ( Contains is used in the screenshot below )
3. Noticed that the datagird has been filtered accordingly
4. Click Datagrid header to order the list (ascending/descending)
5.  Excluded/Filtered groups are shown

**Expected behavior**
Excluded group should be hidden

**Version**
4.23x

**Screenshots**
![image](https://user-images.githubusercontent.com/52902639/67269160-c10dae00-f4e8-11e9-9896-c791fc1bb9c9.png)

**Platform**
ALL

**Additional context**

_**Below Filters are not affected**_
1. Does Not Contain
2. Does Not Equal
3. Does Not End With

**Comment by jbrcna** [comment]
Issue still persist 
Verified in 4.23 rc2
http://4230-rc2-enterprise.demo.design.infor.com/components/datagrid/example-grouping-filter.html
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/56722184/69304867-2c1fe100-0c5d-11ea-85ab-b8e530ea18f6.png">

**Comment by tmcconechy** [comment]
This is for next version 4.24 but you can test it on master link if you like

**Comment by jbrcna** [comment]
Test **PASSED**
Works perfectly fine across all browser
Verified in http://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-filter.html
