### ISSUE TITLE
Datagrid: Multi select is resetting after using the pager

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3013]
**Describe the bug**
Datagrid: Multi select is resetting after using the pager

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side.html
2. Select IDs 0 & 1
3. Change to 25 Records per Page

**Expected behavior**
Records should still be selected after using the pager

**Version**
Beta 4.23

**Screenshots**
N/a

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This has never worked this way. But it probably could/should.

**Comment by tmcconechy** [comment]
Descoping this for now
