### ISSUE TITLE
Modal Dialog: Modal Buttons are wrapped down in Android devices

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#3014]
**Describe the bug**
If the modal buttonset has more than 2 buttons, the buttons are wrapped down in Android phones such as Galaxy S7 / S8 / S9 or HTC

**To Reproduce**
1. Go to components/modal/test-validation-editor.html sample under enterprise
2. Add another button to the modal button set.
        ` <div class="modal-buttonset">
            <button type="button" class="btn-modal" >Cancel</button>
            <button type="button" class="btn-modal" >Confirm</button>
            <button type="button" id="submit" class="btn-modal-primary" >Submit</button>
          </div> `
3. Bring up the sample in chrome with device set to samsung galaxy s7.

**Expected behavior**
 The third button should be within the bounds of the modal-buttonset.

**Version**

- ids-enterprise: v4.23.0-dev

**Platform**
 - Device Samsung Galaxy S6 / S7 / S8 / S9
 - OS Version: Android

**Comment by aaralikar** [comment]
![image](https://user-images.githubusercontent.com/22720894/67305844-a2dd8900-f4bb-11e9-8029-905fd3c68baa.png)

**Comment by aaralikar** [comment]
Same behavior can be reproduced in enterprise-ng demo too. Add another button to enterprise-ng\src\app\modal-dialog\modal-dialog.demo.ts

`
  openSimple() {
    const dialogRef = this.modalService
      .modal<ExampleModalDialogComponent>(ExampleModalDialogComponent, this.placeholder)
      .buttons([
        {
          id: 'cancel-button',
          text: Soho.Locale.translate('Cancel'),
          click: (e, modal) => { modal.isCancelled = true; dialogRef.close('CANCEL'); }
        },
        {
          id: 'confirm-button',
          text: Soho.Locale.translate('Confirm'),
          click: (e, modal) => { dialogRef.close('CONFIRM'); }
        },
        {
          text: 'Submit', click: (e, modal) => {
            dialogRef.close('SUBMIT');
          }, isDefault: true
        }])
      .title(this.title)
      .isAlert(this.isAlert)
      .apply((dialogComponent) => { dialogComponent.model.header = 'Header Text Update!!'; })
      .open();
....
}

`
Angular demo uses the decorateButtons function in addButtons method in modal.js

**Comment by lipetzan** [comment]
This is critical.  Landmark workflow is broken on mobile without a fix asap.

**Comment by tmcconechy** [comment]
Patch critical or next version critical?

**Comment by tmcconechy** [comment]
I fixed this issue on the attached PR. It should be easy to make a workaround in older versions. I just updated the css to remove the padding. And adjusted the button height.

https://github.com/infor-design/enterprise/pull/3016/files#diff-d662c14c5dcd7e4b41028bf60b9bc77bL423

Something like adding the following where it will take effect:

```
.modal-buttonset {
  padding: 0 !Important;
}
.modal-buttonset button {
  height: 49px;
  line-height: 49px;
}
```

**Comment by janahintal** [comment]
Hi @tmcconechy, upon testing this in iOS, I was **unable to click any button again** after clicking **any 2** buttons in http://master-enterprise.demo.design.infor.com/components/modal/test-inline-buttons.html

1. Open iOS device 
2. Goto http://master-enterprise.demo.design.infor.com/components/modal/test-inline-buttons.html
3. Click Three buttons - button
4. Click Five buttons - button 
5. Click Four buttons - button (will not be able to click any button in this scenario)

**Comment by tmcconechy** [comment]
@janahintal i simplified this test to avoid any more issues being raised on it

**Comment by janahintal** [comment]
Thanks Tim, I will now move this to Done as it is now working as expected.
