### ISSUE TITLE
Kitchen Sink Updates

### ISSUE THREAD

**Issue by kentonquatman** [infor-design/enterprise#3017]
**Describe the solution you'd like**
Please add the following components to the [kitchen sink page](http://localhost:4000) so that we have a more comprehensive set to test with:

- [Header Tabs](https://design.infor.com/code/ids-enterprise/latest/tabs-header)
- [Application Menu](https://design.infor.com/code/ids-enterprise/latest/applicationmenu)
- [Notification Banners](https://design.infor.com/code/ids-enterprise/latest/notification) (Can be confined within a card)
- One of these things where there is a white section between the header and the main body (Sorry, I don't know what it's called in IDS. Banner?)

![Screen Shot 2019-10-22 at 8 10 37 PM](https://user-images.githubusercontent.com/847306/67345199-2d4bda00-f508-11e9-8d8b-9153bfac429e.png)

**Describe alternatives you've considered**
We are planning to build out a new sketch library with all of the vibrant components in each variant, but that project will take a while and would delay the GA release of vibrant. To keep things moving, we just want to compile what we have and tweak components as needed.

**Comment by kentonquatman** [comment]
@jmacaluso711 Adding these four items might be all we need to test the vibrant theme variants. Let me know if you think of any other components that should be included.

**Comment by tmcconechy** [comment]
Some of these things we would have to think about how they can easily be included on the kitchen sink page. The reason is 3/4 of these are full page patterns that use the whole page and the kitchen sink page scrolls.

What about something like a series of links on a page or maybe we can restructure the kitchen sink on some other way? Or perhaps iframes? or rework them to constrain them to a partial page container.

**Comment by EdwardCoyle** [comment]
On the documentation site, we used to have a "Table of Contents" page that was different than the kitchen sink page.  Maybe we could:

- Build up a curated "table of contents" page that replaces http://localhost:4000, including the requested samples behind quick links.
- Retain the kitchen sink page at http://localhost:4000/kitchen-sink, add that to the curated list

**Comment by tmcconechy** [comment]
There is http://latest-enterprise.demo.design.infor.com/components/list but i get that it can be slow to click into each and every one. We also should consolidate the examples and patterns into components so there is one list. But thats just something i think of from time to time.

**Comment by EdwardCoyle** [comment]
> We also should consolidate the examples and patterns into components so there is one list.

We could make a single table of contents somewhere and do this programatically.  I think the ask from @kentonquatman is specifically to create a quick-access list of tests they need for checking colors/font size/other design assets.  We pretty much have every sample you could want at this point but there's too many to quickly navigate for that purpose.

**Comment by kentonquatman** [comment]
Did we ultimately decide that we're unable to implement those four components on the kitchen-sink page?

**Comment by tmcconechy** [comment]
We’ll take a stab at it and see. Have it in next sprint which starts next week so will take a deeper look

**Comment by tmcconechy** [comment]
Thinking i can make this work with having each section in "cards". Might look a little nicer that way as well and reduce some mixed up text hierarchy.

**Comment by tmcconechy** [comment]
@kentonquatman any updates on designs for this one? Just checking and following up it is not urgent.

**Comment by tmcconechy** [comment]
@inforandy FYI moving this to next sprint - but when we get the designs i'll do it right away as soon as we do.

**Comment by inforandy** [comment]
Sounds good, thank you

**Comment by tmcconechy** [comment]
@inforandy - Have we get even any WIP versions of this?

**Comment by tmcconechy** [comment]
De scoping this one for now
