### ISSUE TITLE
Tabs: Tooltip is showing in a disabled form 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3018]
**Describe the bug**
Tabs: Tooltip is showing in a disabled form 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/tabs/example-enable-disable.html?theme=uplift&variant=light&colors=0563C2#programmatic-tabs-form-elements
2. Click 'Disable Entire Tab Column' button
3.  Under 'Modified Tooltipped', hover and click the selector

**Expected behavior**
No tooltip should be displayed

**Version**
Beta 4 .23

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/67389188-add40e80-f5cc-11e9-85a2-547559b6a012.png)

**Platform**
All OS, Browser and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Lets think about this one. Maybe just end up closing as its very very minor.
It is almost working fine because that is the way the value for the slider is shown in the tooltip. Although i can see the argument for this as the tab is supposed to be disabled entirely.

**Comment by tmcconechy** [comment]
Descoping this issue for now.
