### ISSUE TITLE
Locale: Cannot parse datetime string using the Finish locale (fi-FI)

### ISSUE THREAD

**Issue by prkarlsson** [infor-design/enterprise#3019]
The function Soho.Locale.parseDate returns undefined when trying to parse a datetime string on the Finish locale (fi-FI) using the datetime format "d.M.y H.mm" defined in the IDS culture file fi-FI.js. The datetime format is retrieved from Soho.Locale.calendar().dateFormat.datetime.

The parseDate function works when testing with a four digit year in the format ("d.M.yyyy H.mm") but it does not work with the datetime in the culture file that has a single character for year. I don't know if this is an issue in the parseDate implementation or if the configuration of the datetime format is wrong in the Finish culture file.

The function works as expected for other locales that we have tested with but we have not tested with all locales.

**To Reproduce**
1. Call the parseDate function using a valid Finish datetime string.

Non working examples:
Soho.Locale.parseDate("18.10.2019 7.15", Soho.Locale.calendar().dateFormat.datetime, true)
Soho.Locale.parseDate("18.10.2019 7.15", "d.M.y H.mm", true)

Working example (note that the short date format is defined to use four digit year "d.M.yyyy"):
Soho.Locale.parseDate("18.10.2019 7.15", "d.M.yyyy H.mm", true)
Soho.Locale.parseDate("18.10.2019", Soho.Locale.calendar().dateFormat.short, true)

**Expected behavior**
A Date object is returned from the parseDate function when called with a valid datetime string and datetime format.

**Actual behavior**
The value undefined is returned.

**Version**
4.21.3

**Comment by tmcconechy** [comment]
@prkarlsson Im wondering what you think about format `d.M.y` we had only 2 and for digit dates working. https://en.wikipedia.org/wiki/Date_format_by_country says they use d.M.yyyy so is d.M.d a real ask? or is d.M.yyyy fine?

If d.M.y is used how should it display?

1/2/2019 -> 1.2.9?
1/2/2019 -> 1.2.2019? (just map it anyways to 4 digit)

**Comment by tmcconechy** [comment]
I think i just answered my question https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/fi-FI.js#L16-L24

I think we just need to update these to all d.M.yyyy as its a mistake. And we support d.M.yyyy

But feel free to confirm.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to Done column.
