### ISSUE TITLE
Progress: Bar cannot be reset to 0

### ISSUE THREAD

**Issue by jayblack-infor** [infor-design/enterprise#3020]
**Describe the bug**
Once a value has been set for the progress bar it cannot be reset to 0.

**To Reproduce**
1.   Set an initial value or increment value to greater than 0.
2.   Set value to 0.

**Expected behavior**
Progress bar updated to 0

**Version**
- ids-enterprise-ng: [4.13]

**Screenshots**
Unable to get screen shots to display here

**Platform**
 - OS Version: [Windows 10]
 - Browser Name [chrome]
 - Browser Version [n/a]

**Additional context**
This is the angular codeI created to do an isolated test.
 
Initial load set @ 25
 
 
 
Click “Decrease” which decrements by 25.
 
 
@Component({
       template: `
       <div>
        <div>
            <label id="pr-label1">Percent complete</label>
             <soho-progress [progressValue]="val"></soho-progress>
            <button soho-button (click)="increase()">Increase</button>
            <button soho-button (click)="decrease()">Decrease</button>
        </div>
       </div>`
})
export class ProgressBarComponent implements AfterViewInit, IWidgetComponent {
       @Input()
       widgetContext: IWidgetContext;
       @Input()
       widgetInstance: IWidgetInstance;
 
    public val = 0;
 
       ngAfterViewInit() {
 
              // Initial update of the message text and color
              this.increase();
    }
 
    public increase() {
        this.val += 25;
    }
 
    public decrease() {
        this.val -= 25;
    }
}

**Comment by tmcconechy** [comment]
This issue has an easy fix. Just need to remove this if https://github.com/infor-design/enterprise/blob/master/src/components/progress/progress.js#L79 or make it work better with zero vs undefined/null.
