### ISSUE TITLE
DataGrid: Row collapses on edit for grid with one editable column

### ISSUE THREAD

**Issue by tobywicksinfor** [infor-design/enterprise#3023]
**Describe the bug**
When the user sets focus on the cell it enters edit mode and the row is collapsed (height = 1px) and the user cannot see and therefore edit field. This only applies to data grids with one one editable text column. If there are other columns displayed this issue does not occur.

**To Reproduce**
1. Change the datagrid/example-editable.html page to only show one editable column (**Product Name** for example)
2. Load http://localhost:4000/components/datagrid/example-editable.html
3. Click on a cell.
4. The cell's text is unexpectedly hidden.

**Expected behavior**
The row is not collapsed and the user can see the editable field and edit the cell's content. 

**Additional Information**
If there is another column displayed in the grid this is not a problem, because the row height is then calculated based on the adjacent cell's height.

**Version**
 *  IDS Enterprise Components - v4.21.2
 *  Date: 2019-10-08T19:36:27.902Z
 *  Revision: ccd8c0ea41c98fe57a0d744e0e33fb7002ab67d5

**Screenshots**
![Datagrid row hides](https://user-images.githubusercontent.com/40477207/67439408-a9940980-f63d-11e9-914c-27da3111b442.gif)
![Datagrid row height when collapsed](https://user-images.githubusercontent.com/40477207/67439552-10b1be00-f63e-11e9-853c-7bfa3437f128.PNG)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - Windows 10
 - Google Chrome | 77.0.3865.120 (Official Build) (64-bit) (cohort: Stable)

**Comment by tobywicksinfor** [comment]
Applied the following workaround:

```
.datagrid td.is-editing { height: 49px }
.datagrid.short-rowheight td.is-editing { height: 29px }
.datagrid.medium-rowheight td.is-editing { height: 40px }
```

**Comment by tmcconechy** [comment]
We probably need to add a height like your workaround. But it needs to be variable based on a variable row height and the row height options (normal, short ect). Perhaps it can be added as the editor is opened.

**Comment by janahintal** [comment]
This issue is now resolved. Will now move to Done. Thanks! 
Tested in http://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-single-column.html?theme=uplift&variant=dark across all browser and OS
