### ISSUE TITLE
Tabs: Focus is cut off after adding a Tab

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3024]
**Describe the bug**
Tabs: Focus is cut off after adding a Tab

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html
2. Add a Tab with a Tab Name "TEST SUPER LONG TAB NAME 1", Tab Index 0
3. Click '+'

**Expected behavior**
Focus should not be cut off

**Version**
Beta 4.23

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/67471293-bdf9f580-f681-11e9-9ae2-2dd76b2b775c.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping this for now
