### ISSUE TITLE
Toast: Dragging a should stay in the same place across the application

### ISSUE THREAD

**Issue by drinkaj** [infor-design/enterprise#3025]
**Describe the bug**
Added the ability to drag and save the position when a Toast message is displayed. This appears to be saved to local storage by URL so if you open a record and make a change and drag the Toast message to the center of the screen. Then open a different record and make a change the Toast message appears in the upper right again. 

If the Toast message is moved would like it to stay across the application. 

**To Reproduce**
1. Go to datagrid list and open a record. 
2. Make a change and when the Toast message appears drag it to the center of the screen.
3. Go to the datagrid list again and open a different record.
4. Make a change and note the Toast message appears in the upper right again. 
5. If you go back to the first record that was changed and make another change the Toast message will appear where it was moved too. 

**Expected behavior**
If you move a Toast message it should stay in the same place across the application. If the browser cache is reset then the Toast message resets back to the upper right corner. 

**Version**

- ids-enterprise: 4.23.0

**Screenshots**

**Platform**
 - Browser Name - chrome
 - Browser Version - 77.0.3865.120 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@deep7102 when you pick this up. I think we need to just change uniqueID so it does not use a URL. So that its the same saved location across the app/every test page

**Comment by tmcconechy** [comment]
@deep7102 please check out https://github.com/infor-design/enterprise/pull/3086#issuecomment-558527142 can that be fixed?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by CindyMercadoReyes** [comment]
I spoke to @tmcconechy , in regards to the issue for when you move/drag the 1st Toast to another position before it gets completed,  it won’t save the latest position of the toast. However, the 2nd Toast seems to work perfectly fine.

Tim stated the customer is totally ok with how this example works. 

This issue is QA Passed.   Thanks Cindy
