### ISSUE TITLE
Datagrid: Performance optimization

### ISSUE THREAD

**Issue by GeTeBr-Infor** [infor-design/enterprise#3026]
**Is your feature request related to a problem? Please describe.**

Datagrid is slow when handling large amounts of data. I've attached some examples which are showing the problem.  Loading 10000 rows into the grid costs  around 15 seconds returning the set grouped is the same time. But rendering the group collapsed is a faster around 3 seconds, but that is not the experience I have when using the Angular component. Please note that I've completely disabled the numberformatters.

I've noticed several things. First when I use the default formatting of the grid which is locale.js from the enterprise library. It is slower comparing to use my own formatter. It looks like locale.js' formatNumber is to generic to be fast. This wouldn't be an issue but with a large dataset this is a lot of extra code to be executed.

What I've seen is that when the grid is rebuild the renderrows is called two times. The first time to determine the sizes of the columns and the second time to show the actual data. 
My first test with grouping wasn't accurate because the formatNumber slowed down the drawing.

In the attached zip there are 7 examples:

- test-large-dataset-performance-grouping.html just grouping a large set in productgroup. takes 13 seconds of just drawing. but collapsed it is faster
- test-large-dataset-performance-grouping_on_demand.html same as the first but grouping after button click. takes long when expanded. not expanded is faster
- test-large-dataset-performance-grouping_on_demandvirtualization.html same as second but using virtualization. This causes strange behavior. I hope there is a way to fix this easy.
 -test-large-dataset-performance-nopaging.html plain grid without paging without formatting. drawing is 15 seconds
- test-large-dataset-performance-nopagingwithformatters.html plain grid without paging with formatting. drawing takes really long. my chrome performance tab crashes most of the times. 1000 records in 9.98 seconds
- test-large-dataset-performance-Virtualized.html grid with virtualization. Really fast 10000 records shown in 0.253 seconds
- test-large-dataset-performance-Virtualizedwithformatters.html grid with virtualization and with rowformatting is slow 1000 records in 4.3 seconds. 10000 in 43 seconds.
	
These examples are plain JQuery. I have the idea that the angular wrapper degrades the performance.

**Describe the solution you'd like**
I would like the have grouping enabled on the datagrid since it doesn't handle large ammounts of data really fast. 

**Describe alternatives you've considered**
Alternative is to use grouping, but we want to use the datagrid to create some sort of overview for the client.

**Additional context**
Attached you'll find my examples in a zip file. 
[testwithlargedatasets.zip](https://github.com/infor-design/enterprise/files/3767697/testwithlargedatasets.zip)

**Comment by tmcconechy** [comment]
Looked at this a bit. The changes i made do change it up in speed to load on average of 2-4 seconds per example. Seems like its taking approx 1 second per 1000 records. Once you get over 2-3000 rows the scrolling is a bit laggy.

The formatters are important and do a lot of processing as they have to change the display data so its very tricky to change these.

I think the answer is to use paging or to fix the virtualization so its not as clunky. Since the work i did reduces rendering time this can move forward in a later version. I included a slightly cleaned up set of the tests in this version but moving the majority of this task to a future TBD sprint.

Also included a new example http://localhost:4000/components/datagrid/test-rendering-performance.html which performs fairly well (but its only 100x100).

**Comment by tmcconechy** [comment]
Related to https://github.com/infor-design/enterprise/issues/460 (if not a duplicate)

**Comment by tmcconechy** [comment]
Have a plan for this now but its going to have to be be done on a future major version

**Comment by tmcconechy** [comment]
Closing this in favor of https://github.com/infor-design/enterprise/issues/4340
