### ISSUE TITLE
Tabs vertical header is not changing to Subtle in iOS device

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3029]
**Describe the bug**
Tabs vertical header is not changing to Subtle in iOS device

**To Reproduce**
1. Open iOS device and goto http://master-enterprise.demo.design.infor.com/components/tabs-vertical/example-responsive.html?theme=soho&variant=light&colors=2578a9
2. Change the Theme to Vibrant
3. Change the Theme again back to Subtle 

**Expected behavior**
Entire body should be changed to Subtle theme

**Version**
Beta 4.23

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/67563649-b1de6880-f753-11e9-8bb1-f83deeb59c59.png)

**Platform**
iOS Devices 
Tested in Iphone XR iOS 13

**Additional context**
N/a

**Comment by tmcconechy** [comment]
It is somewhat correct in fact as this is the selected state. And as of now the selected state does not change color.

It probably could. @kentonquatman @kevinwhitedesign what do you think about changing azure accented elements to the color in the header?

**Comment by EdwardCoyle** [comment]
I reviewed this one and it seems like the color change is no longer a problem on `master`.  Sending over to Q/A for a test.

**Comment by tmcconechy** [comment]
I also see the header isnt changing color when changing to vibrant

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Will now move to Done.
