### ISSUE TITLE
Update Sketch Kit

### ISSUE THREAD

**Issue by kmahsmith** [infor-design/enterprise#303]
Right now the components in the sketch file don't have a filled background, so when a user layers them over a gray background, the input or card takes the background color.

Update components (inputs, card, button, radio) to have white background colors.

**Comment by tmcconechy** [comment]
Is this ask about changing the enterprise components to have a white background?

Notes:
- previously was only white on highcontrast - just noting.
- cards are already having a white background
- what should happen in dark contrast?
- dont think buttons would be effected so would be just all input elements, dropdowns, checkboxes, radios.

**Comment by kmahsmith** [comment]
Yes, the sketch kit is just one part of this. We would also have to update enterprise components too. Will open up another ticket, but these are definitely things we should consider when making any changes.

**Comment by tmcconechy** [comment]
Ok, if this is for updating the Sketch kit is it in the right project?
