### ISSUE TITLE
Popover - Popover button is overlapping in responsive view in Vibrant / Uplift Theme

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3030]
**Describe the bug**
Popover - Popover button is overlapping in responsive view in Vibrant / Uplift Theme

**To Reproduce**
1. Open iOS device browser and go to 
http://master-enterprise.demo.design.infor.com/components/popover/example-index.html
2. Change the Theme to Vibrant
3. Click 'Click to show popover' button

**Expected behavior**
Popover should display in responsive view

**Version**
Beta 4.23

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/67565185-6201a080-f757-11e9-8550-7fa02df53977.png)

![image](https://user-images.githubusercontent.com/45757016/67565367-d8060780-f757-11e9-8cec-5cb84c716085.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Im going to descope this issue as too minor to worry about so we can free time for more important issues.
