### ISSUE TITLE
Editor: example-dirty-tracking - tracker is displayed even if there is no change

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3031]
**Describe the bug**

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html?'
2. Click on the comment section
3. Press 'Tab' 5 times

**Expected behavior**
Dirty tracing should be triggered by changes of the content

**Version**
master 4.23

**Screenshots**
<img width="1658" alt="image" src="https://user-images.githubusercontent.com/56722184/67566333-1997b200-f75a-11e9-8b1f-066ffd998e78.png">

**Platform**
ALL

**Additional context**

**Comment by tmcconechy** [comment]
Cannot seem to reproduce this issue anymore. Tabbing should actually just tab out of the editor not change it and it seems to be doing that.
