### ISSUE TITLE
Editor: example-flex-toolbar tooltip is not displayed

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3033]
**Describe the bug**
upon opening the menu tooltip is not shown

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/editor/example-flex-toolbar.html?theme=uplift&variant=light&colors=0563C2'
2. Resize browser window to 320 x 568 or at least '...' is shown
3. Click '....'

**Expected behavior**
tooltip should be displayed

**Version**
master 4.23

**Screenshots**
<img width="609" alt="image" src="https://user-images.githubusercontent.com/56722184/67567279-3503bc80-f75c-11e9-9587-c9eb4b5c18ba.png">

**Platform**
SAFARI

**Additional context**

**Comment by tmcconechy** [comment]
Also when fixing.

a) seeing an extra scroll bar in safari on the toolbar
b) the actions button is out of alignment.

**Comment by EdwardCoyle** [comment]
@tmcconechy I'm going to move this to Q/A for 4.23.x.  I think we fixed this issue with the changes in #2977, and I'm no longer seeing this in Safari when we test against the current beta.

**Comment by jbrcna** [comment]
**QA Failed**
The menu/tooltip is now displayed. However, there is a scroll bar in the header of the editor. Also, the items on the menu are not working. (i.e. click on View Source, nothing happens)
when you maximize the browser or select the editor options that are not in the menu, it's working
(e.g. from 320 x 568 resize the width of the browser to remove 'Block Quote' on the menu then click 'Block Quote' from  the header of the editor)
![image](https://user-images.githubusercontent.com/56722184/68920314-cd1b2180-07af-11ea-85f5-207cbb71aaa1.png)

Verified in Safari Browser
http://master-enterprise.demo.design.infor.com/components/editor/example-flex-toolbar.html?theme=uplift&variant=light&colors=0563C2

http://4230-rc0-enterprise.demo.design.infor.com/components/editor/example-flex-toolbar.html?theme=uplift&variant=light&colors=0563C2

**Comment by tmcconechy** [comment]
cc @EdwardCoyle maybe just fix it in your editor PR if its not already and close?

**Comment by EdwardCoyle** [comment]
Yeah I'll add it to #3122

**Comment by tmcconechy** [comment]
Ok moving to done, we expect this fix for the last point on #3122 @jbrcna

**Comment by jbrcna** [comment]
The issue is now **resolved**
1. overflowed items are now triggering editor actions as expected.
2. no more extra scroll bar
Verified in http://master-enterprise.demo.design.infor.com/components/editor/example-flex-toolbar.html
across all browser and devices
