### ISSUE TITLE
Locale: jse when using extendMessages() for nb-NO

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#3035]
**Describe the bug**
A jse is output when calling Soho.Locale.extendMessages() for locale nb-NO.

[test-extend-messages.zip](https://github.com/infor-design/enterprise/files/3772555/test-extend-messages.zip)

**To Reproduce**
1. Unzip the attached test-extend-messages.zip to app > views > components > locale 
2. Go to http://localhost:4000/components/locale/test-extend-messages.html?locale=nb-NO
3. Page remains blank
4. Browser console displays the jse > 'Uncaught: TypeError: Cannot read property 'name' of undefined

**Expected behavior**
Expect to be able to extend the messages for the locale.

**Version**

- ids-enterprise: v4.23.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/67580460-00681480-f70c-11e9-8c26-198f332f1d27.png)

**Platform**
 - All

**Additional context**

**Comment by tmcconechy** [comment]
if workaround is needed just change the Locale. defaultLocales array element as per:

https://github.com/infor-design/enterprise/pull/3036/files#diff-3792f94525dff5169376546b60ecacb7L63

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/locale/test-extend-messages.html?locale=nb-NO
http://master-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?locale=nb-NO
Passed QA in all browsers, moving to Done.
![image](https://user-images.githubusercontent.com/39508864/67667485-e434d380-f9a8-11e9-8d6f-6fe099a2603a.png)
