### ISSUE TITLE
Header: Placeholder text is the wrong color

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3040]
**Describe the bug**

QA Bug from design that needs design input. The header color for the placeholder text is the wrong color.

**To Reproduce**
1. Go to http://latest-enterprise.demo.design.infor.com/components/header/example-searchfield-expanded.html?colors=800000
1. In the DOM add `placeholder: "search"` to the search field
1. See error

**Expected behavior**
The placeholder value for css shouldnt be abaeb7. It should possibly be white at 0.7 but the problem with opacity on text is it is less legible so may want to use that value as an actual hex.

This example also cannot be run in Vibrant (uplift theme). So also need to fix that to test how this will look there.

Also need to test changing colors on the header for this bug so might need the theme switcher and color switcher to work on these header examples.

**Version**
- ids-enterprise: [v4.22]

**Screenshots**

![Screen Shot 2019-10-28 at 1 34 11 PM](https://user-images.githubusercontent.com/814283/67702600-63fe7600-f988-11e9-97c5-b96ccb32efca.png)

**Platform**
 - Any / Chrome

**Additional context**
cc @kevinwhitedesign

**Comment by kevinwhitedesign** [comment]
![hint-text-example](https://user-images.githubusercontent.com/6478704/67717195-9ff30480-f9a3-11e9-9cc0-6ecd5a85d66e.png)

-(top row) white opacity looks like works well here
-(mid row) using slate(5) seems visually conflicting
-big question?, do we introduce opacity for color backgrounds? @kentonquatman @tmcconechy @benfenton (in the bottom row it seems silly to scale this by adding a new hint text value per each theme)
-does this component need an uplift redesign @kentonquatman ?

**Comment by tmcconechy** [comment]
I think that possibly white with opacity is the only case we should be using opacity in the design system. So i agree rgba(255, 255,255, .4) looks the best to me here.

**Comment by brianjuan** [comment]
http://4240-beta0-enterprise.demo.design.infor.com/components/header/example-searchfield-expanded.html
Placeholder color is correct on all browsers except Mac Safari and iOS browsers.

Safari, Theme: Subtle, Variant: Light
![image](https://user-images.githubusercontent.com/39508864/70782812-d2758700-1dc2-11ea-99d8-60c1ca0cad0b.png)

Safari, Theme: Vibrant, Variant: High Contrast
![image](https://user-images.githubusercontent.com/39508864/70782850-e91bde00-1dc2-11ea-8f12-93917354f948.png)

**Comment by tmcconechy** [comment]
Closing as PR will solve

**Comment by janahintal** [comment]
Issue is now resolved. Will now move to Done. 
Verified in 
http://4240-rc0-enterprise.demo.design.infor.com/components/header/example-searchfield-expanded.html?theme=soho&variant=dark 
http://4240-rc0-enterprise.demo.design.infor.com/components/input/example-index.html?theme=uplift&variant=contrast
http://4240-rc0-enterprise.demo.design.infor.com/components/colorpicker/test-states.html?theme=uplift&variant=contrast
http://4240-rc0-enterprise.demo.design.infor.com/components//fileupload/example-index.html?theme=soho&variant=light
http://4240-rc0-enterprise.demo.design.infor.com/components/listview/test-search-disabled.html?theme=uplift&variant=contrast
http://4240-rc0-enterprise.demo.design.infor.com/components/personalize/example-index.html?theme=uplift&variant=contrast&colors=9279a6
http://4240-rc0-enterprise.demo.design.infor.com/components/spinbox/example-disabled.html
