### ISSUE TITLE
Remove usage of `-webkit-text-fill-color` in favor of a CSS reset

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#3041]
**Describe the bug**
We utilize `-webkit-text-fill-color;` in a lot of places alongside the standard text color definition. We shouldn't be using this so prevalently because:

- MDN states that [it's non-standard technology](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-fill-color)
- Some browsers accidentally accept it over top of other valid color definitions, causing unexpected results (see the personalization bug with tooltips in #3011 as an example).

**Solution**
We currently have 30+ spots in IDS styles that use this property.  We should:
- [x] Remove it from all places where it's used.
- [x] Fix any broken visual regressions
- [x] Make some "reset" style rules specifically for any place where Chrome would be using this property to override standard text colors (for example, anchor tags, and `::selected` pseudo styles should probably have a rule that `unset`s this property).

**Version**
Tested as of v4.23.x-dev

**Screenshots**
![Screen Shot 2019-10-28 at 2 45 57 PM](https://user-images.githubusercontent.com/3249601/67708283-446c4b00-f992-11e9-9dd6-2e440f97f696.png)

**Platform**
- n/a

**Comment by jbrcna** [comment]
QA **FAILED**
please find details below. moving this ticket to _Failed_ column

- [ ] Input fields, specifically readonly/disabled. Also check the placeholder:
http://master-enterprise.demo.design.infor.com/components/input/example-index.html?theme=uplift&variant=contrast
![image](https://user-images.githubusercontent.com/56722184/69715028-824fc100-1142-11ea-9706-ed28c281c65e.png)

- [ ] Colorpicker:
http://master-enterprise.demo.design.infor.com/components/colorpicker/test-states.html?theme=uplift&variant=contrast
![image](https://user-images.githubusercontent.com/56722184/69715569-7ca6ab00-1143-11ea-9957-58d82cb90c8b.png)
http://master-enterprise.demo.design.infor.com/components/colorpicker/test-states.html
![image](https://user-images.githubusercontent.com/56722184/69715810-db6c2480-1143-11ea-8254-1b2bf6065113.png)

- [ ] File Uploader:
http://master-enterprise.demo.design.infor.com/components/fileupload/example-index.html?theme=soho&variant=light
![image](https://user-images.githubusercontent.com/56722184/69716506-19b61380-1145-11ea-85fb-19a4496afb1a.png)
http://master-enterprise.demo.design.infor.com/components/fileupload/example-index.html?theme=uplift&variant=contrast
![image](https://user-images.githubusercontent.com/56722184/69716589-49651b80-1145-11ea-88e6-c9d49c19e5f3.png)

- [ ] Listview (disabled):
http://master-enterprise.demo.design.infor.com/components/listview/test-search-disabled.html?theme=uplift&variant=contrast
![image](https://user-images.githubusercontent.com/56722184/69716888-fcce1000-1145-11ea-8859-5911588dfb83.png)

- [ ] Personalized (Vibrant)
http://master-enterprise.demo.design.infor.com/components/personalize/example-index.html?theme=uplift&variant=contrast&colors=9279a6
![image](https://user-images.githubusercontent.com/56722184/69717522-2fc4d380-1147-11ea-814f-830c1857416e.png)


- [ ] Spinbox Buttons (disabled and readonly):
http://master-enterprise.demo.design.infor.com/components/spinbox/example-disabled.html
![image](https://user-images.githubusercontent.com/56722184/69714381-4405d200-1141-11ea-9abd-4f73cb211fc5.png)

**Comment by jbrcna** [comment]
#3199 - **PASSED**
Test PASSED on the following components below, verified across all browsers and devices. All themes and variants are tested as well.
-Standard Inputs
-Colorpicker (Soho)
-Colorpicker (Vibrant):
-File Uploader (Soho):
-File Uploader (Vibrant):
-Listview Searchfield
-Personalized Searchfield
-Spinbox

However, I also tested several components that I think was affected by this issue. below are the components who have failed. so, for now, this ticket will be move to Failed. If i need to file a separate issue for those components. please let me know

- [ ] Datepicker - legend (subtle/dark)
https://master-enterprise.demo.design.infor.com/components/datepicker/example-legend.html?theme=soho&variant=dark
![image](https://user-images.githubusercontent.com/56722184/70523378-e2505980-1b7d-11ea-93e8-1b3b1770aa1a.png)

- [ ] Popover -extra css (dark theme)
https://master-enterprise.demo.design.infor.com/components/popover/example-extra-css-class.html?theme=uplift&variant=dark
![image](https://user-images.githubusercontent.com/56722184/70523134-59d1b900-1b7d-11ea-9578-c67eb872128a.png)

**Comment by tmcconechy** [comment]
@jbrcna i would suggest a new issue for these two things 
I do not think related

**Comment by jbrcna** [comment]
@tmcconechy  alright I will create new tickets for those issues and thanks for your suggestion
