### ISSUE TITLE
Pager: Select all is not working as expected 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3043]
**Describe the bug**
Pager: Select all is not working as expected 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/pager/example-datagrid.html?theme=uplift&variant=light&colors=0563C2
2. Click Select all 
3. Click Next Page button

**Expected behavior**
All records should be selected

**Version**
Beta 4.23

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/67762528-9be8e480-fa80-11e9-9034-594034fbe30a.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Because this is server side paging the pages are not saved moving from page to page. However the select all checkbox should be reset when changing page.

**Comment by tmcconechy** [comment]
Fixed this while testing another issue.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
