### ISSUE TITLE
Datepicker - Time options not working correctly if passed in updated

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#305]
**Describe the bug**
When calling update to reset the settings things are not working right when changing some of the time related settings.

**To Reproduce**
1. Copy this attachment to app/views/components/datepicker

[test-updated.html.zip](https://github.com/infor-design/enterprise/files/2371082/test-updated.html.zip)

2. Run http://localhost:4000/components/datepicker/test-updated.html
3. Click update
4. Selecting a date and set time in the picker.
5. Click to select a different time / date.

At this point an error occurs and the time portion is not updated.
The problem only occurs if using updated. So workaround is to destroy and recreate (this is commented out in the example).

**Expected behavior**
Expect the time options to work the same on updated as they do on init.

**Platform**
tested on chrome

**Additional context**
Problem submitted by Milan Premgi - Email

**Comment by EdwardCoyle** [comment]
I would think this just requires swapping out the contents of the input field as part of the `updated()` method.  Whatever process sets the contents of the input field when a date is chosen from the picker should also happen in `updated()`.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datepicker/test-updated.html
Passed QA testing across all browsers
