### ISSUE TITLE
Locale: Make fromGregorian and toGregorian shared functions with no maxDate

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3051]
**Is your feature request related to a problem? Please describe.**

This issue is to fix one part of https://github.com/infor-design/enterprise/issues/2878 we think should be seperate. The `fromGregorian` and `togregorian` functions in ar-SA and ar-EG should be usable in any locale so they should be moved. Also we should update the functions so that the maxDate is not 2029 anymore.

**Describe the solution you'd like**
1. move fromGregorian and toGregorian from  https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/ar-EG.js and https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/ar-SA.js to locale.js instead so there is just one place and can be used in any locale.
1. name them  `Locale.umalquraToGregorian` and `Locale.gegorianToUmalqura` (same signitures)
2. Change any code needed that uses to point to the new shared place
3. make sure it doesnt max out on the dates - https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/ar-EG.js#L210-L211 to test this go to any page in ar-SA or ar-EG http://localhost:4000/components/locale/test-groupsize.html?locale=ar-SA and type in the console
```
Locale.currentLocale.data.calendars[0].conversions.fromGregorian(new Date(2021, 10, 10))
// ok
Locale.currentLocale.data.calendars[0].conversions.fromGregorian(new Date(2040, 10, 10))
// not ok (undefined)
```
4. test the steps on https://github.com/infor-design/enterprise/issues/2956#issue-505289936 and confim after

**Additional context**
The original functions came from https://github.com/globalizejs/globalize (version 0.x) so maybe there is a new version here or elsewhere or the current function can be updated.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
