### ISSUE TITLE
Icons: Restore transparent icons

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3052]
**Describe the bug**
We made an icon change to remove the solid icons. We probably have to revert this change.
This was also reported by teams as they had been using this icons on some solid colored backgrounds.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/button/example-index.html
1. Observe the primary button icon
1. test #icon-info-field specifically this should be out lined
1. test http://localhost:4000/components/alerts/example-index.html

**Expected behavior**
We need the linear icons + solid with white background + transparent versions of all the alert icons. Try to avoid name change as much as possible just restore the solid ones which have a white background and the ones with a transparent version.

If necessary just add new transparent versions?

**Version**
- ids-enterprise: [4.21]

**Additional context**
CC @kevinwhitedesign 

Ms teams thread

**Comment by tmcconechy** [comment]
Summary of changes we should have:

- an outline version
- one with a white background over the inner shape
- one with a transparent background over the inner shape
- in both themes with same names
- icon-info-field was outlined
- icon-info (default ones) are transparent in middle
- icon-info-solid (or can do new name if we want here) was white in the middle.
- need to do for all alert icons which should be:
```
icon-alert
icon-success
icon-error
icon-pending
icon-info
icon-in-progress
icon-info-field
```

**Comment by kentonquatman** [comment]
@tmcconechy I'll make those updates right now.

**Comment by tmcconechy** [comment]
Thanks. I'm not sure if my comments are accurate 100% as i noticed there is `icon-info-linear`
So i think we can

- restore `icon-info` ones back to transparent
- keep `icon-info-linear` as the linear version
- add a new `icon-solid-background` (name). Old was `icon-info-solid` but these havent been used that much

**Comment by kentonquatman** [comment]
Does 'icon-confirm' need to have '-linear' and '-solid-background' versions created?

**Comment by tmcconechy** [comment]
I would say now. This is primarily about alert icons. http://master-enterprise.demo.design.infor.com/components/alerts/example-index.html
The icon-confirm is a "toolbar" icon. For alerts we use `icon-success` already.

**Comment by CindyMercadoReyes** [comment]
I will go back to retesting this ticket once Tim makes the updates to "Buttons" font color. @tmcconechy

**Comment by tmcconechy** [comment]
All good now!

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
