### ISSUE TITLE
Formatter.Expander function prevents template by escaping value

### ISSUE THREAD

**Issue by karinpb** [infor-design/enterprise#3054]
**Describe the bug**
After updating to ids-enterprise-ng@6.1.0 with ids-enterprise@4.22.0 the value sent in to

Formatters.Expander(row, cell, value, col, item, api) is escaped which means that the Custom Formatter I did for a column no longer works after updating IDS. 
 
I use this formatter function in the Data Grid, it's not a Tree it's an expandable row.
```
const errorFormatter = (row, cell, value, col, item: IPage, api) => {
         if ((item as IPage).err) {
            value = `<svg class="icon datagrid-alert-icon icon-alert lm-admin-page-warn-icon" focusable="false" aria-hidden="true" role="presentation"><use xlink:href="#icon-alert"></use></svg>
                     <span class="lm-margin-sm-l lm-text-alert">${value}</span>
                  </svg>`;
         }
         return Formatters.Expander(row, cell, value, col, item, api);
      };
```

**To Reproduce**
1. Create a data grid
2. Add a custom formatter function
3. Within that function create a template and pass that to Formatters.Expander function.

-> Issue occurs here as Formatters.Expander function seems to have started to escape the value.
Changing that behaviour would require a new approach to content that is in fact a template.

**Expected behavior**
I expect that templates are supported in this scenario and any escaping would have to be done by me in this scenario. Or the function need to support a templateValue for values that should not be escaped and where the internal parts have already been escaped.

**Version**
ids-enterprise-ng@6.1.0 with ids-enterprise@4.22.0 

**Screenshots**
Before upgrade:
![image](https://user-images.githubusercontent.com/7961438/67844603-5834c000-fafe-11e9-95f8-9a6d65217949.png)

After upgrade of IDS:
![image](https://user-images.githubusercontent.com/7961438/67844643-697dcc80-fafe-11e9-9b4b-667b6e996ccb.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome

**Additional context**

**Comment by tmcconechy** [comment]
I don't seem to be able to reproduce this issue. I made both an NG and EP example and am unable to reproduce. Pushing two PR's you can checkout.

**Comment by karinpb** [comment]
This was in fact caused by an issue on our side by two independent changes and I failed to check the correct branch and only compared with my branch.
