### ISSUE TITLE
Application Menu: Font color gets changed when search result has accordion

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3056]
**Describe the bug**
In Filterable Application Menu, font color gets changed when search result has accordion

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html
2. In the search field inside Application menu, type "role"
3. See issue: "My Roles", "Role 1", and "Role 2" font color were changed to gray

**Expected behavior**
Font color should not change when searching.

**Version**
- ids-enterprise: v4.13.0 to v4.23.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/67859378-70382e00-fb56-11e9-87d3-ba434624a51e.png)

**Platform**
 - All devices, OS and browsers.

**Additional context**
N/A.

**Comment by tmcconechy** [comment]
Going to close this as too minor/non issue. The color change is that its showing that those nodes are parent nodes. Nothing important to fix here.
