### ISSUE TITLE
Locale: Missing culture property firstDayofWeek 

### ISSUE THREAD

**Issue by pukhrajbal** [infor-design/enterprise#3060]
90% of culture files are missing firstDayofWeek assignment.

Below is example of where it is provided.
https://github.com/infor-design/enterprise/blob/ded35cb4f7ce13a0d66c2c0f86a764253abc3a1a/src/components/locale/cultures/en-GB.js#L42

Is this something which should be covered 100% across all culture files provided by soho?

**Comment by tmcconechy** [comment]
It defaults to zero otherwise. But if it’s needed as part of the data I can understand?

**Comment by crayzd92** [comment]
Infor CRM CE noticed this one as the Mongoose calendar correctly shifts the first day of the week based on the culture (we have an internal Jira for this if needed):

![image](https://user-images.githubusercontent.com/17650211/67900775-77dddf80-fb22-11e9-8335-5965bf7ca7f9.png)

**Comment by tmcconechy** [comment]
Is there a mismatch on some of the locales maybe? Which language is that?

**Comment by crayzd92** [comment]
That is Thai (Thailand): th-TH, the other note there is that they are one of the few that uses a non-Gregorian calendar as well.

**Comment by tmcconechy** [comment]
I’ll check the first day locales data again against cldr (data source) and see about first day.
We do not currently support Thai calendar only Gregorian and umalqura. Could be added if there is a need for it but that’s a bigger task. If needed let’s make a separate ticket with justification for it mentioned.

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. 
Verified in http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html. Thank you.
