### ISSUE TITLE
Application Menu: Role switcher layout gets broken when you resize from small to large screen size

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3061]
**Describe the bug**
Application Menu: Role switcher layout gets broken when you resize from small to large screen size.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html
2. Resize the browser to short height
3. Open the Application Menu, then click the Employee menu to open the role switcher, make sure the scrollbar is visible in the switcher
4. Maximize the browser
5. See issue: role switcher is now broken

**Expected behavior**
Role switcher layout should still appear correctly after changing browser size.

**Version**
- ids-enterprise: v4.19.0 to v4.23.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/67936172-41799080-fc06-11e9-8a2b-deabb63a8591.png)

**Platform**
 - All desktop browsers.

**Additional context**
N/A.

**Comment by tmcconechy** [comment]
The height is calculated when it opens. Maybe can resize on page resize or close the list.
But minor

**Comment by tmcconechy** [comment]
Descoping this for now
