### ISSUE TITLE
Datagrid: Time filter overlapping the triggering icon

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3062]
**Describe the bug**
A time filter is overlapping the triggering icon.

**To Reproduce**
1. Go to '/components/datagrid/example-filter.html'
2. Scroll over on the table to the Time column
3. In the time column, enter a time of 12:45 AM

**Expected behavior**
Similar to lookup filter, the value should ellipses instead of overlapping the icon.

**Version**

- ids-enterprise: v4.23.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/67976158-f2befd00-fbeb-11e9-9a1b-73ab078b3387.png)

**Platform**
 - All

**Comment by jbrcna** [comment]
QA **Failed**
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html

**Notes:**
It works fine in ALL Browsers **Except**  in IE11. nothing seems to be working in IE11 with the current version 4.25.0-dev

**Comment by tmcconechy** [comment]
Fixed on https://github.com/infor-design/enterprise/issues/3289 - ready to retest IE 11

**Comment by CindyMercadoReyes** [comment]
I retested this issue and this issue is now resolved.

**Comment by jbrcna** [comment]
just a few observation. @tmcconechy @CindyMercadoReyes 

Is the scroll bar intended?
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/56722184/71708213-8a2e0f80-2e2a-11ea-92a6-202711852b00.png">

In Firefox (`Vibrant`) the icon is not centered 
<img width="190" alt="image" src="https://user-images.githubusercontent.com/56722184/71708247-ccefe780-2e2a-11ea-87c3-9aa488aa138f.png">

**Comment by tmcconechy** [comment]
Yes the scrollbar is intended. Otherwise there will be a strange gap  / empty space there because of the other scroll bar on the other side.

Will fix the firefox issue tho.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
