### ISSUE TITLE
CAP Component: When user clicks close button the tooltip is still appearing

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3063]
**Describe the bug**
CAP Component: When user clicks close button the tooltip is still appearing

**To Reproduce**
1. Go to url: http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-close-button-flex-from-settings.html
2. Click on "CAP
3. CAP window opens. Click on the "X" button
4. See error is that the CAP closes yet the "Close" tool tip is still appearing on the main UI. Please see screen shot attached. 

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![CAP Error](https://user-images.githubusercontent.com/39101346/67976862-4f6ee780-fbed-11e9-9f2d-0dbe4127bbaa.png)

**Platform**
 - OS Version: MAC]
 - Browser Name [FF]

**Additional context**
None

**Comment by tmcconechy** [comment]
Can no longer reproduce this. i think it was fixed. Adding to QA list

**Comment by jbrcna** [comment]
The issue is now resolved. Thank you.
https://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-close-button-flex-from-settings.html
https://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-close-button-flex-from-settings.html
