### ISSUE TITLE
RTL: datagrid filter icon is shown behind text

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3067]
**Describe the bug**
The checkbox are behind the text in the Datagrid filters so that it's not so easy to see it.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-filter.html?locale=ar-SA
2. Click on 'Product name' filter button
3. See error [A] is selected but the selection is behind the text

**Expected behavior**
The checkbox should be to the right of the [A]

**Version**

- ids-enterprise: v.4.22.1

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/68125869-d801c680-ff12-11e9-8e33-5908df23eb87.png)

**Platform**

 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 78.0.3904.70 (Official Build) (64-bit)

**Additional context**
-

**Comment by tmcconechy** [comment]
This issue fixed along with a different issue in 4.26. See https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-filter.html?locale=ar-SA (its working now 🎉 )
