### ISSUE TITLE
RTL: Datepicker placement issues

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3068]
**Describe the bug**
The Clear and Apply buttons has switched placement and Today link are misplaced behind the text in the datepicker.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-index.html?locale=ar-SA
2. Click on the first calendar icon
3. See error 1: "Today" is placed behind the text
4. See error 2: Default "Apply" button should probably be placed to the left (similar to the Modal buttons Save and cancel in https://design.infor.com/code/ids-enterprise/latest/demo/components/modal/example-index.html?locale=ar-SA)

**Expected behavior**
The Today text should not be behind the text
The Apply and Clear buttons should switch places so Apply is to the left.

**Version**
- ids-enterprise: v.4.22.1

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/68126604-73476b80-ff14-11e9-817f-72b173fb2267.png)

**Platform**

 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 78.0.3904.70 (Official Build) (64-bit)

**Additional context**
-

**Comment by tmcconechy** [comment]
Same point on https://github.com/infor-design/enterprise/issues/2910

**Comment by tmcconechy** [comment]
This issue was fixed while fixing something else by @deep7102 see http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=ar-SA

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=ar-SA
The Today link now does not overlap the dropdown text, however, the Apply button is still on the right.
![image](https://user-images.githubusercontent.com/39508864/68292145-3327ea80-00c6-11ea-8b87-5d6034a1a6ba.png)

And in Windows IE, the Today link is too close to the > button.
Soho
![image](https://user-images.githubusercontent.com/39508864/68292215-5bafe480-00c6-11ea-9a19-d4eeb59b5ec0.png)

Uplift
![image](https://user-images.githubusercontent.com/39508864/68292256-71250e80-00c6-11ea-8d54-5440983ea25d.png)

**Comment by tmcconechy** [comment]
Working on this as part of #1757 so will flip the buttons.

**Comment by brianjuan** [comment]
http://4230-beta0-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=ar-SA
Passed QA in all browsers, moving to Done.
![image](https://user-images.githubusercontent.com/39508864/68655034-3f022980-056a-11ea-837d-6f517cb6da34.png)
