### ISSUE TITLE
Clear Searchfield when new data is loaded

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise#307]
**Is your feature request related to a problem? Please describe.**
I have a datagrid where I can dynamically change dataset and if I have something in the search field the result will be 0 when I load a new dataset. (Even if I have a hit on that search string).

**Describe the solution you'd like**
I would support having the datagrid just clear it when you call updateDataset.

**Describe alternatives you've considered**
A clear-method on the toolbar API.

**Comment by brianjuan** [comment]
Enhancement is working as expected and passed QA testing.
Environment: http://490-beta0-sohoxi.demo.design.infor.com/components/datagrid/test-clear-searchfield-on-update-dataset.html
