### ISSUE TITLE
ApplicationMenu: '+' icons on application menu displays as '|' when screen is zoomed out and on IE11.

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#3070]
**Describe the bug**
'+' icon changed to '|' in application menu.

**To Reproduce**
1. Go to 'http://localhost:4000/components/applicationmenu/test-six-levels.html?theme=uplift&variant=light&colors=0563C2'
2. Expand Level 1 and a few of its children
3. Ctrl -
4. See a few of the '+' icons turned to '|'

This also happens sporadically on IE11.

**Expected behavior**

**Version**

- ids-enterprise: v4.23.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/39130590/68161109-c02e4080-ff1a-11e9-82dd-0d531bae0b71.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome and IE11
 - Browser Version: Version 77.0.3865.120 (Official Build) (64-bit) and 11.1069.171340.0

**Comment by tmcconechy** [comment]
@vonnyw Can you retest this on 4.24 against the new add menu changes and see if its still an issue?

https://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html?theme=uplift&variant=light&colors=0563C2

Having some issues reproducing this and think it may be fixed.

**Comment by vonnyw** [comment]
@tmcconechy This is no longer an issue in master as of today.

**Comment by vonnyw** [comment]
This issue seems to resurface sporadically, please see attachment. ![image](https://user-images.githubusercontent.com/39130590/77334395-b737e300-6cf2-11ea-944d-cdb5b7fd44bd.png)

**Comment by tmcconechy** [comment]
Any idea how to reproduce? Are we still supporting IE 11? I read today it was out of the supported browser list but unsure if thats official.

**Comment by vonnyw** [comment]
@lipetzan  Can you please comment on IE11 support? 

Reproduce on https://master-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html?theme=uplift&variant=light&colors=0563C2 - click Level 1 - click Level 2 (no children with icons), notices the Level 2 with content link icon changed to "|".

No error was observed.

**Comment by tmcconechy** [comment]
![Screen Shot 2020-03-23 at 12 26 16 PM](https://user-images.githubusercontent.com/814283/77338990-827f5800-6d01-11ea-86a1-b128ba31d57e.png)

Not seeing that on windows 8.1 nor indows 10 with IE 11.  Any chance that the browser is zoomed?

**Comment by vonnyw** [comment]
Yes, sorry, forgot to add, this only happens on certain resolutions. I zoomed out by doing Ctrl - twice and was able to reproduce.

**Comment by tmcconechy** [comment]
Ok that might not be able to be fixed (cross pixel effect). But will keep this in the backlog for now.
Did you fix something like this once with some trick @ericangeles  ?

**Comment by ericangeles** [comment]
> Ok that might not be able to be fixed (cross pixel effect). But will keep this in the backlog for now.
> Did you fix something like this once with some trick @ericangeles ?

I haven't but I can take a look at it @tmcconechy.

**Comment by tmcconechy** [comment]
OK, sure. Lets prioritise the calendar thing your working on tho. Can get to this next sprint.

**Comment by jbrcna** [comment]
The issue is now resolved. Thank you. will retest once beta is deployed
v4.28.0-dev
verified in https://master-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html?theme=uplift&variant=light
