### ISSUE TITLE
Autocomplete: Selected event not fired when partially overflowing its parent

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#3072]
**Describe the bug**
If an autocomplete input element is partially overflowing its parent, the selected event will not fire when selecting an item from the list. Gif below demonstrates the issue:
![auto](https://user-images.githubusercontent.com/1101770/68218646-f89a5100-ffe4-11e9-9b87-0a272f1baa66.gif)

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/autocomplete/example-templates
2. Open dev tools
3. Enlarge dev tools so that the autocomplete demo view is very small and scroll appears
4. Adjust scroll position so that the autocomplete is not fully visible
5. Search for "q" and select the option
Result: Nothing happens

The scenario above is not very likely, but it will occur anytime the autocomplete parent has vertical scroll and the autocomplete is not 100% within the view.

**Expected behavior**
The selected event is fired with the selected item.

**Version**
- ids-enterprise: 4.22.1

**Comment by janahintal** [comment]
QA Passed. Will now move do Done. Thanks!
Tested in http://master-enterprise.demo.design.infor.com/components/autocomplete/example-templates.html?theme=uplift&variant=light

**Comment by volante007** [comment]
We still see this issue. Can be reproduced in above QA page

**Comment by tmcconechy** [comment]
@volante007 im not seeing it. everytime i try it i se the toast message indicating that the selected event fires. 

Tried on: http://master-enterprise.demo.design.infor.com/components/autocomplete/example-templates.html
And: https://design.infor.com/code/ids-enterprise/latest/demo/components/autocomplete/example-templates

Video: https://drive.google.com/file/d/1Uv_6hU85o7uzIIpKIbREN2zu9s5LMoju/view

**Comment by volante007** [comment]
Hi Tim,

The issue isn't seen in your video since the autocomplete input is not partially hidden. Please see GIF & description in original post. If even only 1 pixel is hidden due to overflow, issue will occur.

**Comment by EdwardCoyle** [comment]
I tried this on https://4274-enterprise.demo.design.infor.com/components/autocomplete/example-templates.html (which is running 4.27.4) and I wasn't able to reproduce any errors - seemed ok to me:

![IDS-Enterprise-_2_ (1)](https://user-images.githubusercontent.com/3249601/80717599-1a255280-8ac7-11ea-9914-3d4794c956ad.gif)

My screen recording tool got in the way a bit on this GIF but I was seeing the same results without it present.

**Comment by EdwardCoyle** [comment]
However... confirmed that doing the same on https://master-enterprise.demo.design.infor.com/components/autocomplete/example-templates.html reproduces the bug:

![IDS-Enterprise-_3_](https://user-images.githubusercontent.com/3249601/80717946-82743400-8ac7-11ea-8078-29c2c8236249.gif)

**Comment by volante007** [comment]
@EdwardCoyle Hm, right, seems to work fine on 4.27.4 on that link, but not on master. Very strange, we see this in Homepages with 4.27.4. Our cases are all in modals though, not sure if that can differ somehow?

**Comment by tmcconechy** [comment]
Yeah i see it now on master which is most important to fix it... If i open the chrome tools and cover the autocomplete bottom border.

**Comment by volante007** [comment]
Added a GIF to previous post for one of our scenarios.

"Also only the first time"
I think that's only because when you select, it will actually auto. scroll into view fully. So for it to appear again, need to make it "hidden" again.

**Comment by volante007** [comment]
As part of the fix, it would be great if a test page could be added with an autocomplete used in a modal as well! Similar to (or just add an autocomplete to):
https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/test-in-modal-content.html

**Comment by jbrcna** [comment]
This issue is now resolved. moving this ticket to Done. please see screenshot for reference
v4.28.0-rc0

https://4280-rc0-enterprise.demo.design.infor.com/components/autocomplete/example-templates.html
![image](https://user-images.githubusercontent.com/56722184/80961698-0fa7e780-8e3e-11ea-9404-e9d6cb25e476.png)

**Comment by jbrcna** [comment]
just some observation with the other test page.
https://4280-rc0-enterprise.demo.design.infor.com/components/autocomplete/test-in-modal-content.html

**Expected behavior:**
Scrolling inside of this Modal component should cause the Autocomplete list to close, if the list is open when attempting to scroll.

**Actual Result:**
In `test-content (scrollable-y section)`
after you scroll,  Autocomplete list does not close
![image](https://user-images.githubusercontent.com/56722184/80962291-5f3ae300-8e3f-11ea-8124-c056372980cb.png)
_screenshot from Safari browser_

**Comment by tmcconechy** [comment]
The point about it not closing is worth an issue i think. @jbrcna
