### ISSUE TITLE
About: Microsoft Chromium Edge not being detected

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3073]
**Describe the bug**

**To Reproduce**
1. Go to url: http://master-enterprise.demo.design.infor.com/components/about/example-index.html
2. Click on "Show About Screen"
3. Scroll down to Operating System information
4. See error is that the Microsoft Chromium Edge not being detected. Please see screen shot attached

**Expected behavior**
Microsoft Chromium Edge not being detected should be detected

**Version**

- ids-enterprise: [e.g. v4.21]

**Screenshots**
![About Screen](https://user-images.githubusercontent.com/39101346/68236782-d0eebd00-ffd3-11e9-9875-ad88c77487f3.png)

**Platform**

 - OS Version: [e.g. Windows 10]
 - Browser Name [Microsoft Chromium Edge]

**Additional context**
None

**Comment by tmcconechy** [comment]
https://stackoverflow.com/questions/56360225/how-to-detect-microsoft-chromium-edge-chredge-edgium-in-javascript

Should print out something like "Microsoft Chromium Edge - version"

**Comment by tmcconechy** [comment]
Also please fix the duplicate 10 in "Windows 10 10"

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
