### ISSUE TITLE
Calendar: Adding an Event is not working as expected / inconsistent in Safari 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3079]
**Describe the bug**
Calendar: Adding an Event is not working as expected in Safari 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=soho&variant=light&colors=206b62#
2. Click Today 
3. In the Calendar, click November 19
4. Click '+' button and Click Add Event Modal - Make sure the Date in From and To datepicker is both November 19 and the All day is checked. 
5. Click Submit

**Expected behavior**
The event should only be on November 19. 

**Version**
Beta 4.23

**Screenshots**

![image](https://user-images.githubusercontent.com/45757016/68377887-210d8100-0186-11ea-83f9-957bfb09849a.png)

![image](https://user-images.githubusercontent.com/45757016/68377951-3d112280-0186-11ea-98f9-0d042371d517.png)

**Platform**
Mac Safari, iOS Safari 

**Additional context**
N/a

**Comment by gushanson** [comment]
There is an issue with setting the time as well (Safari only). I can't create a good reproduction since I don't have access to a Mac atm. But here are the simple steps from out tester:
1. Open a date selector with time.
2. Change the hour
3. Verify that the time is changed
Actual: The wrong hour is set.
Expected: Hour to be what was selected in step 2.

**Comment by tmcconechy** [comment]
I was able to reproduce the listed issue but not sure about the extra steps @gushanson ? Can you clarify these a bit.

**Comment by tmcconechy** [comment]
We also did have some related issues i cannot reproduce that seem to only happen on mac's when in manilla. Perhaps somehow timezone related? https://github.com/infor-design/enterprise/issues/2776

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/calendar/example-index.html across all browsers
