### ISSUE TITLE
Monthview: Displayed month/year is blank when Today was clicked after clearing

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3080]
**Describe the bug**
Monthview: Displayed month/year is blank when Today was clicked after clearing.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/monthview/example-index.html
2. Open the datepicker then click Clear button
3. Click the "Today" button in monthview
4. See issue: Date today will be selected in monthview but the month/year in datepicker is still empty

**Expected behavior**
Current month/year should be displayed in the datepicker.

**Version**
- ids-enterprise: v4.20.0 to v4.23.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/68380023-0210ee00-018a-11ea-889b-0d875d44222d.png)

**Platform**
 - All OS and browsers.

**Additional context**
N/A

**Comment by brianjuan** [comment]
I also wonder if "Clear" functionality is appropriate here since it's monthview and there should always be selected month, either the default month today or the user selected.

**Comment by tmcconechy** [comment]
After changes i made recently im pushing this seems to have resolved itself. So including in my PR.

**Comment by CindyMercadoReyes** [comment]
This issue is still occurring on https://4230-beta0-enterprise.demo.design.infor.com/components/monthview/example-index.html?theme=soho&variant=dark&colors=2578a9 for Win 10 IE 11 and Edge 18. Please see screen shot attached. 

![bs_win10_IE_11 0](https://user-images.githubusercontent.com/39101346/68620571-be74f780-049b-11ea-840d-077123549227.jpg)

**Comment by tmcconechy** [comment]
@CindyMercadoReyes im not able to reproduce this? can you elaborate the steps?
https://github.com/infor-design/enterprise/issues/3080#issuecomment-552611913

i actually find these two steps confusing
1. Open the datepicker then click Clear button
1. Click the "Today" button in monthview

I guess you mean reopen for the today button? Either way i'm not seeing the issue anymore

**Comment by brianjuan** [comment]
Issue is fixed in all browsers including IE in http://4230-beta0-enterprise.demo.design.infor.com/components/monthview/example-index.html, I also noticed that the button is now Cancel instead of Clear. Moving to done.
![image](https://user-images.githubusercontent.com/39508864/68761020-21a68b80-064e-11ea-90c8-d518eff5a996.png)
