### ISSUE TITLE
Locale: Invalid format for date in zh-cn

### ISSUE THREAD

**Issue by pukhrajbal** [infor-design/enterprise#3081]
Date picker for November 7, 2019 shows as below

![image](https://user-images.githubusercontent.com/1594975/68414792-16cf9080-014e-11ea-8324-492051e6a87b.png)

Translators have pointed out that the year month format is wrong. It has 11 and also 十一月 (which means November)

MCRM-10268

**Comment by tmcconechy** [comment]
So what should this be? `2019年11` ? Does this seem correct?

**Comment by brianjuan** [comment]
Passed QA, tested in http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=zh-CN. Will retest in IE and once 4.25.0-beta is deployed.

**Comment by brianjuan** [comment]
Passed in beta as well in all browsers, tested in http://4250-beta0-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=zh-CN.
