### ISSUE TITLE
Accordion: Focus is cut off when clicked after the Sort By drop down

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3082]
**Describe the bug**
Accordion: Focus is cut off when clicked after the Sort By drop down

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/accordion/example-index.html?theme=uplift&variant=light&colors=0563C2
2. Click Sort By accordion 
3. Click Brand Name
4. Notice that the focus is cut off
5. Click Warehouse Location
6. Notice that the focus is full

**Expected behavior**
Accordion focus should be consistent

**Version**
Beta 4.23

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/68461697-c9cee580-0245-11ea-8cf0-8d1ff151eacb.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Also noticed that the > caret is not centered within the accordion.

**Comment by janahintal** [comment]
QA Passed. Issue is now resolved. Thank you.
