### ISSUE TITLE
Modal: Field validation does not trigger on fullsize

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3083]
**Describe the bug**
Modal: Field validation does not trigger on fullsize.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/modal/example-fullsize-always.html and http://master-enterprise.demo.design.infor.com/components/modal/example-fullsize-responsive.html
2. Open Modal
3. Tab out from Name and Page Title fields while leaving them blank
4. See issue: Validation will not be triggered

**Expected behavior**
Field validation should trigger on fullsize modal.

**Version**
- ids-enterprise: v4.22.0 to v4.23.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/68471597-7e263700-0259-11ea-988e-6d0a1fc2b019.png)

**Platform**
 - All OS and browsers.

**Additional context**
N/A

**Comment by tmcconechy** [comment]
There is no validation involved in this example. I just removed the required indicator so it doesnt look like there is and included it in my next PR. So this is fixed
