### ISSUE TITLE
Calendar: Multiple issues

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3089]
**Describe the bug**

**To Reproduce**
1. Go to url: http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=uplift&variant=light&colors=0563C2
2. Click on the "+"  and click on "Add Event (Modal) 
3. Multiple issues are found in the " Request Time Off" popup UI
4. First issue is on the  "From and To" field box. The date and calendar icon overlap each other
5. Second issue: When I click on the "time picker" the set time picker pops up. however if I scroll down and don't close the the set time picker and click on the Submit button. The Request Time Off pop up closes, however the set time picker still appears.  
6. Please see screen shot for both issues. 

***Found an additional issue on the BETA new Edge. The upcoming events are not appearing correctly. Please see screen shot attached. ***

**Expected behavior**
Please see steps above and also the screen shots included in this ticket. 

**Version**

- ids-enterprise: [e.g. v4.22.0 ]

**Screenshots**
<img width="1033" alt="Calendar Time Picker" src="https://user-images.githubusercontent.com/39101346/68614406-d3975980-048e-11ea-9af8-9afffd9ca854.png">
<img width="1033" alt="Calendar alignment issue" src="https://user-images.githubusercontent.com/39101346/68614407-d3975980-048e-11ea-8098-be7430ee7279.png">
![New Edge Calendar Issue](https://user-images.githubusercontent.com/39101346/68617655-b1550a00-0495-11ea-839d-2f9df734dd3a.png)

**Platform**
 - OS Version: [iOS 8]
 - Browser Name [FF]

**Additional context**
None

**Comment by tmcconechy** [comment]
Im not clear on the steps on the timepicker popup issue?
The icon issue also depends on the screen size it appears. I think we need to make the dialog fixed size but its minor as it shouldnt happen everywhere.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to Done bucket.
