### ISSUE TITLE
Dropdown Control: Updatable Dropdown is updating its values when changing Theme

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#309]
**Describe the bug**
Updatable Dropdown is updating its values when changing Theme.

**To Reproduce**
1. Go to http://480-rc0-sohoxi.demo.design.infor.com/components/dropdown/example-updating.html
2. Open the dropdown, take note the values "Option One", "Option Two", "Option Three"
3. Change the theme to Dark under the (…) menu
4. Dropdown will update its values to "Option One" and "Option Two"

**Expected behavior**
Dropdown values should not be updated when changing to any Theme.

**Screenshots**
No screenshot applicable.

**Platform**
 - Mac, Windows
- All browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This is super minor - just an example issue. I can see we just need to add an id on the button and isolate the click to that. As of now its reseting when any button on the whole page is pressed.
