### ISSUE TITLE
Calendar: Add Event API Errors

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3090]
**Describe the bug**
Latest fixes broke addEvent in a couple of ways.

**To Reproduce**
1. Go to http://localhost:4000/components/calendar/example-index.html
2. in the console run
```
$('.calendar').data('calendar').addEvent({
      id: '6',
      subject: 'Discretionary Time Off',
      shortSubject: 'DTO',
      comments: 'Personal time',
      location: 'Canada Office',
      status: 'Approved',
      starts: '2018-08-24T10:00:00.999',
      ends: '2018-08-24T14:00:00.999',
      type: 'dto',
      isAllDay: false
    })
```
3. See error
4. now reload this page and run 
```
$('.calendar').data('calendar').addEvent({
      id: '1',
      subject: 'Test Event One',
      status: 'pending',
      starts: '2019-12-02T15:00:00.000',
      ends: '2019-12-02T16:00:00.000',
      type: 'dto',
      isAllDay: 'false'
    })
```
5. this works but adds the date on todays date instead

**Expected behavior**
No errors/problems

**Version**

- ids-enterprise: [e.g. v4.23.0-b]

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving it to the Done bucket.
