### ISSUE TITLE
Datepicker: Selected date gets cleared after changing month or year in Umalqura and Calendar

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3093]
**Describe the bug**
Datepicker: Selected date gets cleared after changing month or year in Umalqura and Calendar.

**To Reproduce**
1. Go to http://4230-beta0-enterprise.demo.design.infor.com/components/datepicker/example-umalqura.html and http://4230-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Open date picker
3. Open month and year dropdown, then select any year or month
4. Click Apply button, see issue: selected date is cleared
5. Click Apply button inside date picker, see issue: NaN will be displayed in the field

**Expected behavior**
Selected date should be retained after changing month or year and NaN won't be displayed after Applying the date.

**Version**
- ids-enterprise: v4.23.0-beta0

**Screenshots**
Umalqura:
![image](https://user-images.githubusercontent.com/39508864/68665640-5d255500-057d-11ea-94d9-f153bb07c2c3.png)

Calendar:
![image](https://user-images.githubusercontent.com/39508864/68667719-a8d9fd80-0581-11ea-9c73-3b5b2fe6cb36.png)

**Platform**
 - All OS and browsers.

**Additional context**
N/A.

**Comment by tmcconechy** [comment]
This did work in 4.22 so should probably fix this.

**Comment by brianjuan** [comment]
Passed QA in http://4230-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html. 

However, in http://4230-rc0-enterprise.demo.design.infor.com/components/datepicker/example-umalqura.html, "1" is always selected in the date picker. So every time you choose a date other than "1" and you open the date picker again, both the chosen date and "1" are selected. And after changing the month or year, "1" is selected instead of the chosen date.
![image](https://user-images.githubusercontent.com/39508864/68931922-84259600-07cc-11ea-8ccd-a5cc0b81156d.png)

**Comment by tmcconechy** [comment]
cc @deep7102

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done bucket.
