### ISSUE TITLE
Calendar: Adding new event via double click is not working

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3094]
**Describe the bug**
Calendar: Adding new event via double clicking inside a date is not working.

**To Reproduce**
1. Go to http://4230-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Double click inside November 19, 2019
3. New Event modal will open, type anything in the Subject and Comments then click Submit button
4. See issue: event won't be added
5. Try to double click again inside any date. See issue: New Event modal will no longer open

**Expected behavior**
New event should be successfully added by double clicking inside a date.

**Version**
- ids-enterprise: v4.23.0-beta0

**Screenshots**
No screenshots applicable.

**Platform**
 - All OS and browsers.

**Additional context**
N/A.

**Comment by EdwardCoyle** [comment]
Seems like this is throwing a JS error when you click/press enter to submit the new event:
![Screen Shot 2019-11-12 at 9 29 59 AM](https://user-images.githubusercontent.com/3249601/68680161-2d4f6080-052f-11ea-9ff8-bf0cd0a9d1c8.png)

**Comment by janahintal** [comment]
QA Passed. Issue is resolved. I'm now able to add events via double click. 

Tested in http://4230-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html
