### ISSUE TITLE
Calendar: Day view non all day events are not displaying as expected in Day view 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3095]
**Describe the bug**
Calendar: Day view non all day events are not displaying as expected in Day view 

**To Reproduce**
1. Go to http://4230-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html#
2. Click on November 14 and click +
3. Select Add event Modal
4. Create a NON all day event from 3pm-11pm
![image](https://user-images.githubusercontent.com/45757016/68670714-826b9080-0588-11ea-834d-fe28d0f6eef9.png)
4. Submit 
5. Switch to Day view 

**Expected behavior**
In the day view calendar, the time from 3-11pm should be blocked. 

**Version**
Beta 4.23

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/68670816-c3fc3b80-0588-11ea-94c1-70d28336321e.png)

**Platform**
All Browser OS, And devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This is not a bug, the week view is configurable to a certain number of hours. If your event exceed this like in this case it's just cut off on the bottom. This is also why i show the times on the event.

This works the same in other calendars (google ect)
