### ISSUE TITLE
Homepage: A triple width widget moves above two single width out of DOM order

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3101]
**Describe the bug**
DOM order isn't maintained for triple width widgets. When a triple width widget is third in the DOM, under two single widths, it moves above the singles when there is enough horizontal space for it.

**To Reproduce**
1. Copy [example-scenario-p.zip](https://github.com/infor-design/enterprise/files/3838133/example-scenario-p.zip) into /app/views/components/homepage
2. Navigate to /components/homepage/example-scenario-p.html
3.  Ensure the browser is large enough for a triple width widget.

**Expected behavior**
DOM order should be maintained when possible.

**Version**

- ids-enterprise: v4.24.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/68708901-3d306a00-055a-11ea-9bd2-ed50adb59c29.png)

**Platform**
 - All

**Comment by tmcconechy** [comment]
@Sovia we have one case with 3 up that works http://localhost:4000/components/homepage/example-scenario-m.html

Are you just thinking this should go:
1.single-width, 2. single-width
3. tripple-width
4. tripple-width
5. tripple-width

?

**Comment by brianjuan** [comment]
Passed QA in all browsers, widgets are in correct order. Moving to Done and will retest once beta is deployed.
Tested in http://master-enterprise.demo.design.infor.com/components/homepage/example-scenario-p.html.

**Comment by brianjuan** [comment]
Passed QA in beta as well, tested in http://4250-beta0-enterprise.demo.design.infor.com/components/homepage/example-scenario-p.html.
