### ISSUE TITLE
Checkboxes: Non-editable checkboxes should still be focusable

### ISSUE THREAD

**Issue by sheilamaejornadal** [infor-design/enterprise#3104]
**Is your feature request related to a problem? Please describe.**
We have a requirement that all non-editable fields should be focusable, that includes checkboxes. The problem is when we disabled the checkboxes, they became non-focusable.

**Describe the solution you'd like**
It would be fixed if the checkboxes also have readonly attribute, same with the textbox and dropdown.

**Describe alternatives you've considered**
It might also be fixed if we are able to set the tab index of the checkbox or its label.

**Comment by tmcconechy** [comment]
The reason we do not have this is that readonly is not a valid property of an html select (its more used as an invisible submit checkbox). So this will not work in many browsers.

There are potential workarounds like using pointer-events and stopping the click. https://stackoverflow.com/questions/12267242/how-can-i-make-a-checkbox-readonly-not-disabled

Why do you need it to be readonly? I think that we would need to make checkbox a JS component for this and therefore would need solid justification for going around whats valid HTML

**Comment by tmcconechy** [comment]
Closing this issue as invalid. Disabled objects can usually not be focusable.
