### ISSUE TITLE
Dropdown: Truncated text not showing ellipses and tooltip

### ISSUE THREAD

**Issue by meechtsm-infor** [infor-design/enterprise#3106]
**Describe the bug**
If the dropdown is populated and a value set before it is displayed, in a Modal for example, when the dropdown is displayed, truncated label text does not show ellipses and a popup tooltip is not shown on hover.

**To Reproduce**
1. Using the Modal example, edit the html so that the dropdown has an option that containers text that will overflow the field.
2. Mark the edited option to be selected.
3. When the page is displayed, open the Modal panel.

**Expected behavior**
The dropdown should contain truncated text with ellipses and a popup tooltip should be shown on hover.

**Version**
- ids-enterprise: v4.19.x

**Screenshots**
![dropdown-truncated-issue](https://user-images.githubusercontent.com/53617793/68747122-cfd01800-05f1-11ea-91e5-9b75b790c82c.png)

**Platform**
- OS Version: Windows 10
- Chrome
- Browser Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by ericangeles** [comment]
@tmcconechy truncated text and tooltip is working now. The only issue is that the tooltip gets cut off.

<img width="328" alt="Screen Shot 2020-05-08 at 7 50 43 PM" src="https://user-images.githubusercontent.com/8839327/81403093-3ed39700-9165-11ea-9531-fc9d084c50be.png">

**Comment by jbrcna** [comment]
**QA Passed** this issue is now resolved. Moving this ticket to Done. Thank you
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/dropdown/test-truncated-text-on-modal.html
![image](https://user-images.githubusercontent.com/56722184/82210532-da24f300-9941-11ea-9a29-5272a7c9d021.png)
