### ISSUE TITLE
Calendar: Upcoming events are not displayed in Upcoming section upon page load

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3108]
**Describe the bug**
Calendar: Upcoming events are not displayed in Upcoming section upon page load. Only newly added events are being displayed.

**To Reproduce**
1. Go to http://4230-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html#
2. See issue: "Personal" event on November 30 is not displayed in Upcoming section

**Expected behavior**
Upcoming events should be displayed in Upcoming section upon page load.

**Version**
- ids-enterprise: v4.23.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/68759589-f1a9b900-064a-11ea-8a8f-48ed6a363197.png)

**Platform**
 - All OS and browsers.

**Additional context**
Only newly added events are being displayed in Upcoming section.

**Comment by tmcconechy** [comment]
This is actually correct. The upcoming events will only show 14 days ahead and that day is out of range. This can be configured in the component settings but the example is set to the default of 14 days. So once the date is in range it will show.

So closing as wont fix/correct behavior.

**Comment by brianjuan** [comment]
Thanks for the clarification @tmcconechy .
