### ISSUE TITLE
Colorpicker hides color names for certain languages

### ISSUE THREAD

**Issue by gushanson** [infor-design/enterprise#311]
**Describe the bug**
The colorpicker is only optimized for en-US. When using for example fi-FI the text is cropped.
I suggest that the colorpicker should get enough width to display its longest color name (if it fits within the container).

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/colorpicker/example-show-label.html?locale=fi-FI
2. Click on the colorpicker menu
3. Click a the first green color.

**Expected behavior**
The color name "Smaragdinvihreä10" is visible.

**Screenshots**
Only "Smaragdinvi" is visible.

**Platform**
 - Windows 10
- Chrome, IE11, Edge

**Additional context**

**Comment by tmcconechy** [comment]
Whoever takes this. We should make the colorpicker take these sizes:

http://localhost:4000/components/input/example-sizes.html

Particularily input-mm and input-md -> if those classes are tagged in should go to that size.
Possibly consider an auto size (input-auto)

**Comment by ericangeles** [comment]
I also noticed that there is a span container (with a class of ```.colorpicker-container```) in the input field that sets the width to just ```150px``` only. Maybe we change it to min-width instead of width.
