### ISSUE TITLE
Monthview: I'm able to type in the datepicker field

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3110]
**Describe the bug**
Monthview: I'm able to type in the datepicker field.

**To Reproduce**
1. Go to http://4230-beta0-enterprise.demo.design.infor.com/components/monthview/example-index.html and http://4230-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html#
2. Try to type in the datepicker field

**Expected behavior**
Should not be able to type in datepicker field in monthview

**Version**
- ids-enterprise: v4.23.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/68761182-819d3200-064e-11ea-8117-ca6b3c7baaf7.png)

**Platform**
 - All OS and browsers

**Additional context**
This also happens in Calendar.

**Comment by tmcconechy** [comment]
Working on this with https://github.com/infor-design/enterprise/issues/3111?email_source=notifications&email_token=AAGGZS2SO2DZ22VSVT3YUUTQTPVAPA5CNFSM4JM2L2NKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HY7X2GA

**Comment by brianjuan** [comment]
http://4230-rc0-enterprise.demo.design.infor.com/components/monthview/example-index.html
QA Passed, tested in all browsers. Moving to Done bucket.
