### ISSUE TITLE
Editor: Memory Leak on destroy/invoke

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#3112]
**Describe the bug**
When destroyed, the Editor component is leaving behind artifacts in memory that are not being cleaned up properly.  This has the potential to cause memory leaks in SPA environments.

**To Reproduce**
1. Open a dev tools instance
2. Navigate to http://4220-enterprise.demo.design.infor.com/components/editor/test-destroy.html
3. Using the dev tools "Memory" tab, take a heap snapshot.  When the snapshot completes, use the class filter to search for "Editor".  There should only be one instance.
4. On the test page, use the "Destroy" and "Invoke" buttons to destroy/invoke the component multiple times.
5. Using the dev tools "Memory" tab, take another heap snapshot.  When the snapshot completes, use the class filter to search for "Editor".  Notice there are now multiple instances of the Editor hanging around in memory:

![Screen Shot 2019-11-13 at 10 04 01 AM](https://user-images.githubusercontent.com/3249601/68775887-2c850000-05fd-11ea-9c05-c76f96988a71.png)

**Expected behavior**
The Editor component should be properly cleaned up and leave no fragments behind when using the `destroy()` method.

**Version**
ids-enterprise: v4.22.x (maybe earlier)

**Platform**
 - n/a

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to Done column.
