### ISSUE TITLE
Allow a new style for linkable tags

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#3113]
**Is your feature request related to a problem? Please describe.**
Need to update clickable/linkable tag style.

**Describe the solution you'd like**
In discussions with @tmcconechy and @kevinwhitedesign we came up with this new look for a linkable tag.
Current Design
http://master-enterprise.demo.design.infor.com/components/tag/example-index.html

New Design
![image](https://user-images.githubusercontent.com/4737815/68778372-b54d6d00-05f8-11ea-89d0-aeb9cbbfe91b.png)

- Add right > caret/arrow style to indicate that it's clickable
- Allow the color of arrow to be white or dark to be set by the implementor (through a class would be perfect).
- should work with `error`, `good`, `alert` default styles (with white/light foreground text).

**Comment by brianjuan** [comment]
QA Passed on all browsers except IE, there's a layout issue on the caret when using Uplift theme.
Open the URL below in Windows 10 IE 11.
http://master-enterprise.demo.design.infor.com/components/tag/example-linkable.html?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/39508864/71710741-bcdf0480-2e38-11ea-92fd-24f07ea90013.png)

**Comment by CindyMercadoReyes** [comment]
Adding the BDD to this ticket. Thank you @brianjuan 
[BDD_github#3113.docx](https://github.com/infor-design/enterprise/files/4026500/BDD_github.3113.docx)

**Comment by CindyMercadoReyes** [comment]
Retested this ticket. This issue is now resolved. Moving this ticket to Done column.

**Comment by brianjuan** [comment]
Arrows are not centered again in beta using IE 11.
http://4250-beta0-enterprise.demo.design.infor.com/components/tag/example-linkable.html?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/39508864/72610957-c5b8f580-3963-11ea-8005-a3bcd52ae97b.png)

**Comment by tmcconechy** [comment]
@EdwardCoyle can you pick this one up as well? Minor QA issue

**Comment by EdwardCoyle** [comment]
@tmcconechy it's actually resolved as part of #3346

**Comment by brianjuan** [comment]
Passed QA in IE and retested in all browsers, tested in https://4250-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html?theme=soho&variant=light
![image](https://user-images.githubusercontent.com/39508864/72964705-8cfe9d80-3df5-11ea-9767-a10f0dc4565a.png)
