### ISSUE TITLE
Weekview: In Two Day example, the view changes to One Day after selecting a date

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3118]
**Describe the bug**
Weekview: In Two Day example, the view changes to One Day after selecting a date in the datepicker.

**To Reproduce**
1. Go to http://4230-beta0-enterprise.demo.design.infor.com/components/week-view/example-two-day.html
2. Open the date picker
3. Select October 16, 2019 or any dates
4. See issue: the view will update to one day

**Expected behavior**
Week view should still display 2 days after selecting a date.

**Version**
- ids-enterprise: v4.23.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/68840202-3130dd80-06fd-11ea-89c1-104b95d4cfda.png)

**Platform**
 - All OS and browsers

**Additional context**
N/A

**Comment by janahintal** [comment]
QA Passed. Issue is now resolved and working as expected. Will move to Done. Thanks!
