### ISSUE TITLE
Weekview: Recurring icon is hard to see in Dark Variant

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3120]
**Describe the bug**
Weekview: Recurring icon is hard to see in Dark Variant

**To Reproduce**
1. Go to http://4230-beta0-enterprise.demo.design.infor.com/components/week-view/example-index.html?theme=soho&variant=dark&colors=2578a9
2. Go to October 2019 week view
3. See issue: recurring icon is hard to see

**Expected behavior**
Recurring icon should be readable.

**Version**
- ids-enterprise: v4.23.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/68854823-d6f14600-0717-11ea-9eed-9e3b6eec3e2b.png)

**Platform**
 - All OS and browsers

**Additional context**
Also encountered in Calendar and Monthview that have events

**Comment by janahintal** [comment]
QA Passed. This issue is now resolved. Will move to Done. Thanks!

![image](https://user-images.githubusercontent.com/45757016/68922859-c5f81180-07b7-11ea-8a44-96999e544975.png)
