### ISSUE TITLE
RTL: trivial issue in modals with space beside last button

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3124]
**Describe the bug**
There is a minor/trivial issue in Modals, where the last button does not end where the modal ends but there is a little space next to the last button that looks like a separator to another button. (see screenshot). This happens in all modals.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/modal/example-index.html?locale=ar-SA
2. Click on 'Show Modal'
3. See issue.

**Expected behavior**
There should be no space next to the button.

**Version**

- ids-enterprise: 4.22.1

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/68929032-b531a680-078b-11ea-8259-1047b6fb8e13.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 78.0.3904.97 (Official Build) (64-bit)

**Additional context**
-

**Comment by tmcconechy** [comment]
It appears this issue has been fixed while working on other modal css issues. Closing for now and adding for verification to QA

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
