### ISSUE TITLE
Calendar: Date picker is not updating after selecting a date inside the calendar

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3126]
**Describe the bug**
Calendar: Date picker is not updating after selecting a date inside the calendar.

**To Reproduce**
1. Go to http://4230-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Click > icon to go to December 2019
3. Select December 20 in the calendar
4. Open the date picker
5. See issue: Date picker is not updated and still in November 2019

**Expected behavior**
Date picker should update whenever a date is selected in the calendar.

**Version**
- ids-enterprise: v4.23.0-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/68932769-3d38a000-07ce-11ea-878a-34b4d0280635.png)

**Platform**
 - All OS and browsers.

**Additional context**
Issue also exist in month and week view components.

**Comment by brianjuan** [comment]
http://4230-rc1-enterprise.demo.design.infor.com/components/calendar/example-index.html
Issue still persists when you switch to Week or Day view.


> * Click > icon to go to December 2019
> * Select December 20 in the calendar
> * Open the date picker
> * Switch to week or day view from the dropdown
> * Open the date picker, see issue

![image](https://user-images.githubusercontent.com/39508864/69226349-f5918a00-0bba-11ea-835f-a077de6df84d.png)

**Comment by janahintal** [comment]
This issue is now resolved. Verified in https://4230-rc2-enterprise.demo.design.infor.com/components/calendar/example-index.html? across all browsers, OS and devices.
