### ISSUE TITLE
Application Menu: example-filterable issues

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3131]
**Describe the bug**
- [x] 'My Role' menu is hard to read (Vibrant Theme, Dark & High Contrast Variant)

- [ ] Filter using the text of the Menu e.g. “My Account’ does not show its menu items 

- [ ] When the focus is on “My Account” menu / “My Account’ is selected then user used a filter, “My Account” menu is still shown 

**To Reproduce**

**Issue 1**
Using Chrome
1. Go to 'http://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html'. 
2. Type in "**Role**" then filter
3. Switch to Vibrant Theme with Dark variant
5. Switch to High Contrast variant
6. See Error

**Issue 2**
1. Go to 'http://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html'. 
2. Type '**My Account**' to filter
3. Click accordion
4. See Error (Menu items are not shown)
5. Clear Filters
6. Type "**My Role**" to filter
7. Click accordion
8. See Error (Menu items are not shown)

**Issue 3**
1. Go to 'http://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html'. 
2. Click 'My Account'
3. Accordion shows menu items for 'My Account'
4. Type "Homepages" to filter
5. See Error, 'My Account' is still shown

**Expected behavior**
-  **Issue 1** 'My Role' menu should be readable

-  **Issue 2** Menu items should be displayed

-  **Issue 3** should only display what is filtered

**Version**
4.23 rc0

**Screenshots**
**Issue 1**
![image](https://user-images.githubusercontent.com/56722184/69047882-2943a700-0a37-11ea-9e72-c4ce4835f5e7.png)

**Issue 2**
![image](https://user-images.githubusercontent.com/56722184/69048396-55135c80-0a38-11ea-8d02-9b0df8d3c0a6.png)

**Issue 3**
![image](https://user-images.githubusercontent.com/56722184/69048714-1f22a800-0a39-11ea-8935-072b8207227a.png)

**Comment by EdwardCoyle** [comment]
Just noting that we fixed **Issue 1** as part of https://github.com/infor-design/enterprise/pull/3401 in [v4.25.0](https://github.com/infor-design/enterprise/releases/tag/4.25.0)

**Comment by EdwardCoyle** [comment]
Getting to the end of this issue and after reviewing the cases, I wanted to address *Issue 2* because I'm not sure the expectation is right:
> 1. Go to 'http://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html'.
> 1. Type 'My Account' to filter
> 1. Click accordion
> 1. See Error (Menu items are not shown)
> 1. Clear Filters
> 1. Type "My Role" to filter
> 1. Click accordion
> 1. See Error (Menu items are not shown)

If you are filtering on "My Account", you're saying "I only want to see results containing the term 'my account'".  This would mean that any of the children of that accordion header (which are the content area with the avatar, notifications, administrator, user settings, and help) do not match the filter, so they are purposefully hidden from the user until the filter is cleared, even if the expand/collapse icon is clicked.  This is definitely not a bug because we don't want results displayed that don't match what the user is looking for in the list.

I've been able to fix everything else listed and will PR very shortly

**Comment by tmcconechy** [comment]
Yeah i'd agree @EdwardCoyle that point seems ok to me. really nothing to expand/collapse in that case so lets just leave /ignore that point for now.

**Comment by jbrcna** [comment]
The issues mentioned above were now resolved.  IDS v4.26.0-dev
verified in https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html
tagging this ticket as Passed but with few Observations

**Issue1** - _Check visibility of parent headers that don't match the filter, but contain children that do:_
* You cannot toggle expand/collapse accordion after the search filter is used

**Issue2** _Check that accordion headers that match the filter are displayed, but their children that don't match the header are not:_
* Both arrows flip when you click either one of them.
![Large GIF (1176x532)](https://user-images.githubusercontent.com/56722184/74021677-ead6dc00-49d6-11ea-8549-ad168e8b45e2.gif)
