### ISSUE TITLE
Application Menu: button overlaps using vibrant theme

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3133]
**Describe the bug**
when using vibrant theme, menu button overlaps if the button has long text

**To Reproduce**
1. Go to 'http://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-menubutton.html?theme=uplift&variant=light&colors=0563C2'
2. Click on menu button
3. Select "_Employee Transition Programs_"

**Expected behavior**
menu button should not overlap/overflow

**Version**
4.23 rc0 

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/69049353-a45a8c80-0a3a-11ea-99d2-d296296880a9.png)

**Platform**
 ALL

**Additional context**

**Comment by tmcconechy** [comment]
Also the pane in the app menu is the wrong color. This is not a new issue so adding to a future sprint.

**Comment by jbrcna** [comment]
Thanks for clarifying @tmcconechy, will take note of this

**Comment by jbrcna** [comment]
**version:** 4.25.0-dev
this is now okay with full screen or maximize view but when you resize the browser to smaller sizes the issue persists. ( i.e. 320 x 568 )

**Comment by tmcconechy** [comment]
We did not have time to address this yet. Moving to next sprint.
