### ISSUE TITLE
Applicaton Menu: scroll bar is shown even if it is not needed

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3134]
**Describe the bug**
when using vibrant theme a scroll bar is shown even if it is not needed

**To Reproduce**
1. Go to 'http://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-open-on-large.html?theme=uplift&variant=light&colors=0563C2'
2. See error

**Expected behavior**
scroll bar should not be shown

**Version**
4.23 rc0 

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/69049820-b557cd80-0a3b-11ea-8935-91b17ca8bfaf.png)

**Platform**
ALL

**Additional context**

**Comment by tmcconechy** [comment]
Adding to 4.2.5as we want to fix uplift issues, however this is not a new issue.
Seems to be caused by the margin css on the pane.

**Comment by CindyMercadoReyes** [comment]
This issue is still opened. the Scroll bar appears for Win 10 IE 11. Please see screen shot attached. 
![bs_win10_IE_11 0(1)](https://user-images.githubusercontent.com/39101346/70087587-908a5b00-15e2-11ea-81c4-9070f32ae495.jpg)

**Comment by tmcconechy** [comment]
This fix isnt there. Yet maybe do to build issues. Lets test again later

**Comment by jbrcna** [comment]
QA **PASSED**
Verifiedn in https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-open-on-large.html?theme=uplift&variant=dark&colors=0563C2

**Observation:**
In IE11 the scroll bar is still shown after resizing the browser. However, when you close the panel and open it again the scroll bar will disappear.
![image](https://user-images.githubusercontent.com/56722184/70232979-932eb100-1798-11ea-9157-dec0cdfea519.png)
