### ISSUE TITLE
Search Field Cancel button 'x' is overlapping the text in the text field

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3135]
**Describe the bug**
Search Field Cancel button is overlapping the text in the text field

**To Reproduce**
1. Go to http://4230-rc0-enterprise.demo.design.infor.com/?theme=uplift&variant=dark&colors=0053B1
2. Goto Search Field Component
4. Type a long test in the Search field

**Expected behavior**
Cancel 'x' button should not overlap any of the text

**Version**
ids-enterprise-4.23-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/69050078-3a42e700-0a3c-11ea-80f7-5c88cab3c7f7.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Adding this todo to smooth out the uplift theme. This issue has existed as far back as i can see.

**Comment by ericangeles** [comment]
This bug exist to all themes upon checking the searchfield component.

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. Thanks! 
Tested in 
http://master-enterprise.demo.design.infor.com/components/searchfield/example-index.html
http://master-enterprise.demo.design.infor.com/components/searchfield/test-application-server-data-label.html
