### ISSUE TITLE
Application Menu: Line under the Tab label is misaligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3136]
**Describe the bug**
when switching themes, the  Line under the Tab label is misaligned.

**To Reproduce**
1. Go to 'http://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html'
or
http://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html
or
http://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized.html

2. Click on 'My Password' Tab
3. Switch themes between Subtle and Vibrant
4. Notice that the line under the TAB's label is misaligned

**Expected behavior**
The line under the 'Tab' label should be aligned

**Version**
4.23 rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/69050387-f00e3580-0a3c-11ea-8881-4cfa2ced3a6c.png)

**Platform**
ALL

**Additional context**
Example pages affected
- [Example Personalized Role Switcher](http://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html)
- [Example Personalized Roles](http://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html)
- [Example Personalized](http://4230-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized.html)

**Comment by tmcconechy** [comment]
I cannot seem to reproduce this issue following the steps. I'm seeing the tab resize correctly still hen changing the theme.

**Comment by jbrcna** [comment]
Please see GIF below for reference.

![Large GIF (1080x316)](https://user-images.githubusercontent.com/56722184/69111728-651f5080-0ab9-11ea-8a0a-2b26ff0a2ef4.gif)

**Comment by tmcconechy** [comment]
Does the browser matter? Im not seeing this in chrome.

**Comment by jbrcna** [comment]
The issue exist across all browsers. My chrome version is 
Version 78.0.3904.97 (Official Build) (64-bit)
I update my chrome browser to Version 78.0.3904.108 (Official Build) (64-bit) but still the issue persist
<img width="1666" alt="image" src="https://user-images.githubusercontent.com/56722184/69202992-2acbb700-0b7e-11ea-9b90-c65931eebe86.png">


<img width="1665" alt="image" src="https://user-images.githubusercontent.com/56722184/69203061-58186500-0b7e-11ea-95bb-7e9b7966e587.png">


<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56722184/69203124-80a05f00-0b7e-11ea-970a-0d503d937ce8.png">


<img width="1673" alt="image" src="https://user-images.githubusercontent.com/56722184/69203233-c3623700-0b7e-11ea-8968-3d3ba8eb486a.png">

**Comment by jbrcna** [comment]
The issue is also present in sink page 4.23 rc1

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/56722184/69228579-c54bea80-0bbe-11ea-9cff-32c4a9fff822.png">

**Comment by tmcconechy** [comment]
This is really strange, i am totally not seeing this and also on chrome. You dont have any errors in the console do you? @EdwardCoyle @deep7102 can you reproduce?

I did add code in the theme switcher to handle this. So when i do change them i see the indicator slide over after a second when changing theme and then it looks fine. See it resizing on all tabs examples like http://4230-rc0-enterprise.demo.design.infor.com/components/tabs/example-index.html?theme=uplift&variant=light&colors=0563C2

**Comment by EdwardCoyle** [comment]
I tested in a few local browsers, and IE11 on Browserstack.  I'm not seeing this issue at all.

@jbrcna for reference, this is what it should be doing (and what we're seeing):

![Untitled_-Nov-20-2019-9_40-AM](https://user-images.githubusercontent.com/3249601/69248341-200f2300-0b7a-11ea-9193-a7a89e26e0fc.gif)

I can't understand what would be causing this in every browser you're looking at, unless maybe we had a bad build deploy?

**Comment by tmcconechy** [comment]
Maybe clear cache? Or something with a Slow connection? Thing is that it fires the resize after the style sheet is loading so wondering if some timing issue. But havent seen this NOT working on my end

**Comment by deep7102** [comment]
Same, can not reproduce this on my end.

**Comment by jbrcna** [comment]
Thank you for your responses. are you using windows pc? not sure if this is a factor but I'm using macOS Mojave Version 10.14.6 (18G1012)

**Comment by brianjuan** [comment]
I can also replicate the issue in all of my browsers (Mac Chrome, Safari, Firefox) and Windows browsers using browserstack. I also noticed that the misalignment gets corrected after resizing the browsers. Please see GIF below. It's strange that you can't replicate it.

http://4230-rc2-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html
Mac Google Chrome:
![tab-misaligned](https://user-images.githubusercontent.com/39508864/69328205-c9910a00-0c89-11ea-8aaa-7b98fc05782d.gif)

**Comment by tmcconechy** [comment]
Wierd, i did see it once only on Windows 10 - Firefox 7.0
Tried a bunch of combinations but i do have one idea. I'm pushing a fix.

Has to be a timing issue.

**Comment by jbrcna** [comment]
Test **PASSED**
Verified in http://master-enterprise.demo.design.infor.com/components/tabs/example-index.html?theme=uplift&variant=light&colors=2578a9
across ALL browsers

I just noticed that when you resize the browser to 320x568 then click `Notes `and from subtle switch to vibrant theme the `Notes tab` is kinda hidden ( just a little ) though you can just swipe to left to see it fully  so im not sure if this is a bug.
![Large GIF (1096x446)](https://user-images.githubusercontent.com/56722184/69416091-cd3b9400-0d50-11ea-891d-cded8cb08ba7.gif)

**Comment by tmcconechy** [comment]
@jbrcna the behavior your noting with the overflow is by design. If the tabs all dont fit they overflow like this. Since the vibrant theme has a bigger font the tabs are not the same size so they may not all fit at low breakpoints.

**Comment by jbrcna** [comment]
Thanks @tmcconechy for clarifying. taking note of this.
