### ISSUE TITLE
Locale: cultureInHead assumes all script tags have a src attribute

### ISSUE THREAD

**Issue by ca0v** [infor-design/enterprise#3138]
**Describe the bug**
When the document contains a script tag (in any location) without a src, the cultureInHead method fails with a null reference exception.

**To Reproduce**
include a link to cultures/en-US.js, which calls `Soho.Locale.addCulture('en-US', ...)`
Now call `Locale.set("en-US")`
This will call cultureInHead, which will fail if any script tags are missing a src attribute.

Here is the current source code which shows that every script tag is examined and the first tag it encounters without a src attribute will create a reference exception:

```
  cultureInHead() {
    const scripts = document.getElementsByTagName('script');
    const partialPath = 'cultures';

    for (let i = 0; i < scripts.length; i++) {
      const src = scripts[i].src;

      if (src.indexOf(partialPath) > -1) {
        return true;
      }
    }

    return false;
  },
```

The proposed fix would exit the method as soon as the first match was found and would guard against src being a non-string (`src && src.indexOf`).

**Comment by tmcconechy** [comment]
Ok i get it now. Thats strange since our demo app has a few of these. If you wanted to do a PR feel free.

**Comment by ca0v** [comment]
I tried reproducing by created <script type="text/javascript"> and could never produce a tag with a null @src (it was always an empty string).  Live-reload is somehow able to create the following script tag that does have a null src attribute value:

```
<script type="text/javascript">
	//   &lt;-- For SVG support
	if ('WebSocket' in window) {
		(function() {
			function refreshCSS() {
				var sheets = [].slice.call(document.getElementsByTagName("link"));
				var head = document.getElementsByTagName("head")[0];
				for (var i = 0; i &lt; sheets.length; ++i) {
					var elem = sheets[i];
					head.removeChild(elem);
					var rel = elem.rel;
					if (elem.href &amp;&amp; typeof rel != "string" || rel.length == 0 || rel.toLowerCase() == "stylesheet") {
						var url = elem.href.replace(/(&amp;|\?)_cacheOverride=\d+/, '');
						elem.href = url + (url.indexOf('?') &gt;= 0 ? '&amp;' : '?') + '_cacheOverride=' + (new Date().valueOf());
					}
					head.appendChild(elem);
				}
			}
			var protocol = window.location.protocol === 'http:' ? 'ws://' : 'wss://';
			var address = protocol + window.location.host + window.location.pathname + '/ws';
			var socket = new WebSocket(address);
			socket.onmessage = function(msg) {
				if (msg.data == 'reload') window.location.reload();
				else if (msg.data == 'refreshcss') refreshCSS();
			};
			console.log('Live reload enabled.');
		})();
	}
	// 
</script>
```

I have to assume live-reload is explicitly nulling the "src" attribute.

Conclusion: although `cultureInHead` does not need to iterate over every <script> tag it should work as-is under normal circumstances.  Closing.
