### ISSUE TITLE
EmptyMessage: Clicking anywhere fires the button click

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3139]
**Describe the bug**
The empty message button.click option will fire no matter where you click in the empty message. This should be only on the button.

**To Reproduce**
1. Make an empty message example with 
```
settings.button = {
    id: 'test',
    text: 'Retry',
    click: () => {
      alert('Do the thing');
    }
  }
```
2. Click any place on the empty message
3. See alert in the wrong time

**Expected behavior**
Should only fire this click event on the button click.

**Version**

- ids-enterprise: [e.g. v4.23.0]

**Platform**
 - ANY

**Additional context**
https://github.com/infor-design/enterprise/blob/master/src/components/emptymessage/emptymessage.js#L81.

Scope that to the button.

See https://github.com/infor-design/enterprise-ng/pull/666

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/emptymessage/test-button-click.html
Working as expected on all browsers except in Windows IE11, the widget is not loaded and there are errors in the console.
![image](https://user-images.githubusercontent.com/39508864/69616477-a394ac80-1071-11ea-83be-8a62a30bd426.png)

**Comment by tmcconechy** [comment]
QA issue on IE 11 is now resolved.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/emptymessage/test-button-click.html
Passed QA in all browsers, moving to Done. Will retest once beta is deployed.
