### ISSUE TITLE
Drag and drop images to Xi Rich Text Editor control

### ISSUE THREAD

**Issue by snambiinfor** [infor-design/enterprise#314]
**Is your feature request related to a problem? Please describe.**
We wanted to request for an enhancement to the existing Xi rich text editor control. We need to drag and drop images onto an Xi Rich Text editor. Currently, when we do that, it is just opening the image we drag.

**Comment by tmcconechy** [comment]
Looked briefly and there does not seem to be any easy way to do this as you would need to manage where the image is saved and since we use content editable its limited what we can do for this.

So descoping this for now.
