### ISSUE TITLE
Pie/Donut: Line labels cut off when something other than value is used

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#3143]
**Describe the bug**
Pie/Donut labels cut off when something other than value is used. The svg node clips the chart as it has a wide of 75%.

**To Reproduce**

- Change the default 'value' that displays on labels to 'label'
- Change the size of the chart until the labels are clipped by the svg node
Expected behavior

Perhaps use an ellipsis on labels at some point. The biggest issue is the labels on the left side of the chart are clipped from the start of the label (ex: instead of 'Apple' you might see 'ple'

**Version**
-- 4.24.0-dev

Screenshots

Pass the options to the pie chart to display with labels as a text value:
![Screenshot 2019-11-19 07 12 18](https://user-images.githubusercontent.com/19823048/69153039-29798c00-0aa3-11ea-90d6-127b2eb1054a.png)

When the screen is wide enough:
![Screenshot 2019-11-19 07 05 10](https://user-images.githubusercontent.com/19823048/69152862-d0115d00-0aa2-11ea-992d-8bfd5b269fce.png)

Here you can see the clipping on left and right side. So part of the text is not displayed:
![Screenshot 2019-11-19 07 05 22](https://user-images.githubusercontent.com/19823048/69152845-c982e580-0aa2-11ea-9409-90778a32f843.png)

This shows the svg node highlighted:
![Screenshot 2019-11-19 07 05 40](https://user-images.githubusercontent.com/19823048/69152832-c4be3180-0aa2-11ea-8c17-b882080c72a1.png)

This shows the graphics node where the chart is painted:
![Screenshot 2019-11-19 07 05 49](https://user-images.githubusercontent.com/19823048/69152823-c0921400-0aa2-11ea-8e76-6cb690207f78.png)

**Platform**
- Chrome/Any

**Comment by tmcconechy** [comment]
Some thoughts on a fix for this.

- Adjust the svg size from 75% to 100% when hideLegend option is used to get more space.
- But dont make the pie too big
- Decrease the line length
- Move the text to top of the line
- Change algorithm to find longest label to a max and adjust the line size accordingly (lines may have different sizes)

**Comment by krahs1** [comment]
This is required for LMCLIENT-28355
https://jira.lawson.com/browse/LMCLIENT-28355

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column
