### ISSUE TITLE
RTL: Dropdown badges overlapping text

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#3150]
**Describe the bug**
Hi, when using dropdown with badges in RTL mode, the badges are overlapping the text.

**To Reproduce**
1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/test-badges.html?locale=he-IL](https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/test-badges.html?locale=he-IL)
2. Click on Dropdown
3. See the result

**Expected behavior**
Should behave the same as dropdown with Icons

**Version**

- ids-enterprise: v4.22.1

**Screenshots**
Dropdown with Badges RTL:
![badge-rtl](https://user-images.githubusercontent.com/34129313/69220138-fc011100-0b7c-11ea-950f-06ad0fc4cf60.PNG)
Dropdown with Badges LTR:
![barge-ltr](https://user-images.githubusercontent.com/34129313/69220139-fc99a780-0b7c-11ea-95ba-8b3116d9285a.PNG)
Dropdown with Icons RTL for comparison:
![icons-rtl](https://user-images.githubusercontent.com/34129313/69220141-fc99a780-0b7c-11ea-98b5-4df3321a185a.PNG)

**Platform**
 - OS Version: Windows 7
 - Browser Name: Chrome
 - Browser Version  78.0.3904.97 (Official Build) (64-bit)

**Additional context**
Thanks

**Comment by tmcconechy** [comment]
While triaging i found this was an easy fix so fixed it.

**Comment by janahintal** [comment]
This issue is now resolved. Will move to Done. Thanks! Verified in http://master-enterprise.demo.design.infor.com/components/dropdown/test-badges.html?locale=he-IL 
![image](https://user-images.githubusercontent.com/45757016/69625719-2faed000-1082-11ea-8ac1-cb2da60f77f0.png)
