### ISSUE TITLE
Calendar: "undefined Days" in Upcoming when multiple days event is created while All Day is unchecked

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3152]
**Describe the bug**
Calendar: "undefined Days" in Upcoming when multiple days event is created while All Day is unchecked.

**To Reproduce**
1. Go to http://4230-rc1-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Double click on November 24, 2019, New Event modal will open
3. Type "Test" in Subject and Comments fields
4. Uncheck All Day checkbox
5. Select Dates: From 11/24/2019 to 11/25/2019
6. Select Time: From 12:00 AM to 12:00 PM
7. Click Submit button
8. See issue: "undefined Days" will be displayed in Upcoming section

**Expected behavior**
Correct number of days should be displayed in Upcoming section

**Version**
- ids-enterprise: v4.23.0-rc1

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/69228450-8d44a780-0bbe-11ea-85dc-1f54a2c53840.png)

**Platform**
 - All OS and browsers.

**Additional context**
N/A

**Comment by tmcconechy** [comment]
This is similar to https://github.com/infor-design/enterprise/issues/3153 in that its sort of wierd what your doing. I think will push this to a future date and keep as minor.

**Comment by tmcconechy** [comment]
Fixed in attached PR.

**Comment by brianjuan** [comment]
Passed QA in all browsers. Moving to Done.
Tested in http://4230-rc2-enterprise.demo.design.infor.com/components/calendar/example-index.html
![image](https://user-images.githubusercontent.com/39508864/69314733-d6086900-0c6f-11ea-8ad6-6592eea281ed.png)
