### ISSUE TITLE
Calendar: Created multiple days events are always displayed as All Day

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3153]
**Describe the bug**
Calendar: Created multiple days events are always displayed as All Day.

**To Reproduce**
1. Go to http://4230-rc1-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Double click November 13, 2019, New Event modal will open
3. Type "Test" in Subject and Comments fields
4. Uncheck All Day checkbox
5. Select Dates: From 11/13/2019 to 11/15/2019
6. Select Time: From 8:00 AM to 10:00 AM
7. Click Submit button
8. Click on the created "Test" event
9. See issue: All Day is checked, and time is 12:00AM to 12:00PM instead of 8:00AM to 10:00AM

**Expected behavior**
All Day should be unchecked and appropriate time set by the user should be displayed.

**Version**
- ids-enterprise: v4.23.0-rc1

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/69230160-b9155c80-0bc1-11ea-8c12-05d7497452ef.png)

**Platform**
 - All OS and browsers.

**Additional context**
N/A

**Comment by brianjuan** [comment]
Referencing #3107

**Comment by tmcconechy** [comment]
Just as a note i think it's kind of strange to make events span days that have a start and end time on different days. But we can see if anyone needs this functionality in the future and fix it later as needed.

**Comment by tmcconechy** [comment]
Also test https://github.com/infor-design/enterprise/issues/3107#issuecomment-555867667

**Comment by brianjuan** [comment]
Passed QA in all browsers. Moving to Done.
Tested in http://4230-rc2-enterprise.demo.design.infor.com/components/calendar/example-index.html
![image](https://user-images.githubusercontent.com/39508864/69314487-3e0a7f80-0c6f-11ea-92c6-866a3d8c0690.png)
