### ISSUE TITLE
Pie chart: Building a pie chart with initial selection set fails

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#3157]
**Describe the bug**
Building a Pie chart with an initial slice to be selected set fails with a javascript error.
ng:///AppModule/PieDemoComponent.ngfactory.js:15 ERROR TypeError: Cannot read property 'call' of undefined
    at SVGPathElement.<anonymous> (sohoxi.js:27993)
    at Selection.selection_each [as each] (d3.js:1185)
    at Pie.setInitialSelected (sohoxi.js:27985)
    at Pie.build (sohoxi.js:27664)
    at Pie.init (sohoxi.js:27532)
    at new Pie (sohoxi.js:27510)
    at jQuery.fn.init.$.fn.chart (sohoxi.js:29119)
    at soho-pie.component.ts:194

**To Reproduce**
1. Go to enterprise-ng demo.
2. Click on 'P' and choose Pie chart.
3. Note the error in the console.

**Expected behavior**
Javascript error be fixed so pie chart can be interacted with. 

**Version**

IDS Enterprise Components - v4.23.0-rc.0

**Screenshots**

**Platform**
  - Browser Name: Chrome
 - Browser Version 78.0.3904.97 (Official Build) (64-bit)

**Additional context**
In enterprise-ng demo project, pie-demo.ts, add 'selected: true' to one of the data point to reproduce the issue.
```
 public pieData = [{
    data: [{
      name: 'Item A',
      value: 10.1,
      id: 'ca',
      tooltip: 'Item A <b>{{percent}}</b>',
      selected: true
    },
....
....
    ]
  }];

```

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
