### ISSUE TITLE
Sparkline Chart: Javascript Error when swapping themes

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#3159]
**Describe the bug**
The Sparkline Chart is throwing a Javascript error when it's present during a theme change.

**To Reproduce**
1. Go to http://4220-enterprise.demo.design.infor.com/components/sparkline/example-index.html
2. Click the page's More Actions menu.  Choose the Vibrant Theme
3. Open a dev tools console
4. See that there's an error thrown.

**Expected behavior**
It should be possible to re-render the chart without errors.

**Version**
- Tested on v4.22.0
- Also present on `v4.24.0-dev`

**Screenshots**
![Screen Shot 2019-11-20 at 3 44 14 PM](https://user-images.githubusercontent.com/3249601/69276659-df7ccd00-0bac-11ea-9f10-8299f6cb94e4.png)
![Screen Shot 2019-11-20 at 3 44 40 PM](https://user-images.githubusercontent.com/3249601/69276660-df7ccd00-0bac-11ea-8fbf-c0a8a9b3578d.png)

**Platform**
 - n/a

**Additional context**
Source of the error seems to be [missing args in `updated()`](https://github.com/infor-design/enterprise/blob/master/src/components/sparkline/sparkline.js#L364).

**Comment by tmcconechy** [comment]
@EdwardCoyle I noticed this too. It seems its been there a while. I found it testing this pr and added a fix https://github.com/infor-design/enterprise/pull/3146/files#diff-4b00ead3faee3399412507df31a001f6L364

Looks like that didnt work...

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/sparkline/example-index.html
Verified QA Passed in all browsers, will retest once beta is deployed.
