### ISSUE TITLE
Sink Page: All charts are not responsive on sink page

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#316]
**Describe the bug**
Sink Page: All charts are not responsive on sink page

**To Reproduce**
1. Go to url: http://480-rc0-sohoxi.demo.design.infor.com/kitchen-sink#
2. All the charts and graphs on the sink page are not responsive

**Expected behavior**
All the charts and graphs on the sink page are not responsive. The charts should be responsive on the sink page. Please see screen shot attached. 

**Screenshots**
![pie chart sink page](https://user-images.githubusercontent.com/39101346/42182244-933dd054-7e0b-11e8-9e6b-295095432240.png)

**Platform**
All Browser Name

**Additional context**
None

**Comment by brianjuan** [comment]
Bug fix is working as expected across all browsers and passed QA testing.
![image](https://user-images.githubusercontent.com/39508864/42870640-5dc7e454-8a46-11e8-8f1b-a689be6b1b4c.png)
