### ISSUE TITLE
DataGrid/Locale: Decimal Formatter corrupts data where comma is used instead of decimal point

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#3165]
Using a dataset that contains decimal values where a comma is used as the decimal point (e.g. 123,45), with the page initialised as nl-NL locale, the PC setup as Dutch (with comma set in Windows Locale Number Format), applying the Decimal formatter to the data grid corrupts the data; e.g.

![Decimal Formatter Error](https://user-images.githubusercontent.com/44396995/69336927-8e75e300-0c57-11ea-8e78-c1a1e12b5fdf.png)

Code snippet to reproduce (insert into any standard page using latest IDS version)...

```
<div class="page-container top-padding scrollable" role="main"><div class="row"><div class="columns twelve"><div id="datagrid"></div></div></div></div>`
<script>

        $("body").one('initialized', function () {
      
          var dataset = [];
          var columns = [];
          
          dataset.push({id: 1, col1: '100,00', col2: '100,00'});
          dataset.push({id: 2, col1: '836,45', col2: '836,45'});
          dataset.push({id: 3, col1: '1200,12', col2: '1200,12'});
          dataset.push({id: 4, col1: '10,99', col2: '10,99'});
          dataset.push({id: 5, col1: '130300,00', col2: '130300,00'});
          
		  columns.push({ id: "id", name: "ID", field: "id", formatter: Formatters.Text, focusable: false, align: "left", filterType: "text" });
		  columns.push({ id: "col1", name: "Text Formatter", field: "col1", formatter: Formatters.Text, focusable: false, align: "right", filterType: "integer" });
		  columns.push({ id: "col2", name: "Decimal Formatter", field: "col2", formatter: Formatters.Decimal, focusable: false, align: "right", filterType: "decimal" });

		  var grid = $('#datagrid').datagrid({
		    	columns: 	columns,
		    	pagesize: 	10,
		    	rowHeight: 	'short',
		    	isList: 	true,
		    	filterable: true,
		    	saveUserSettings: { sortOrder: true, filter: true, columns: true },
		    	toolbar:  { title: "Test", results: true, filter: true, actions: true, filterRow: true, 
		    				personalize: true, resetLayout: true},
		    	dataset: 	dataset
		  });			  
        });

    // Initialize all IDS Enterprise Controls and set the locale
    var initialLocale = 'nl-NL';
    $('body').initialize({locale: initialLocale});

</script>
 ```

Other european locales, such as Spanish (es-ES) and Italian (it-IT), suffer the same problem, though French (fr-FR) appears to be OK. The difference is that the French use a "space" as the group separator, but Dutch, Spanish etc. use a stop. This may be the root cause of the problem.

FYI - this has been logged as a customer issue on Infor Xtreme.

**Comment by sanx72** [comment]
FYI - this is using the latest IDS version from "latest-enterprise.demo.design.infor.com" and does not appear to be browser specific.

**Comment by sanx72** [comment]
FYI, in the sohoxi.js, Locale.formatNumber method, if I comment out the decimal replacement it fixes the problem for Dutch... 

`      if (typeof number === 'string') {
//        if (decimal !== '.') {
//          number = number.replace(decimal, '.');
//        }
        number = Locale.parseNumber(number);
      }`

...though as there is no comment as to why the replacement is needed at this point, it might cause a problem in other locales.

**Comment by tmcconechy** [comment]
Had a look at this and what you're doing isn't really supported at the moment. The number formatter is expecting a number. So i would expect your data as:

```
    dataset.push({id: 1, col1: 100.00, col2: 100.00});
```

Either that or use a string formatter if the data is already in the right format? If this is a hard requirement we could probably do something. Maybe a setting where you specify what the sourceFormat of the number is so we can first convert this to a real number and then format it.

I'm thinking initially we need to know what the format is your using in the string or it could be a space, , . or anything... Although it might work if the number is a string with normal decimals as that works with toString by default.

**Comment by sanx72** [comment]
The reason for using the Decimal formatter is that, in our real program, the data from this table is gathered from application screens, presented in the grid for export to Excel, and I recall we had problems with the Excel import if the data was not using a numeric column type (these may have been resolved since).

The formatNumber code called by the Decimal formatter is already checking the value to see if it is a string, so surely that means string data is supported, and converting it to a number (see my prevous comment) using the parseNumber method, which appears to be locale aware. The problem is that the code changes the decimal seperator in the string first. If the code didn't do this, it works for locales where a stop is not used as the decimal seperator.

**Comment by tmcconechy** [comment]
Ok i think you answered my question partly. We can assume if its a string then we should use the current local to try and parse it. That should work in this case. Will do that.

But I'm not sure about your comment about the excel import? Can you refresh me on that? i know we have the ability to paste http://master-enterprise.demo.design.infor.com/components/datagrid/test-copy-paste-from-excel.html from excel in. But not sure what your doing on that bit, and if it is fixed or not.

Main thing was i wanted to make sure you needed this and it wasnt a mistake that the data was in string. But i can see hardening it by making strings parse in the current locale so will do that .

**Comment by sanx72** [comment]
What I meant is we put our tabular data, extracted from our ERP screens, into a datagrid (read-only), then call the grid's Export To Excel function to create the CSV. In the past, as we've been using IDS since before it was called IDS, I think we had an issue where the numeric data in the CSV file did not import/display properly in Excel unless we used the Decimal formatter on that column. Also, in our system, many of the ERP screens do not have a group seperator applied to decimal values. Using the Decimal formatter adds the correct one(s) in for the current locale. Sorry for the confusion, I was just trying to explain why we use the Decimal formatter and not a string one.

**Comment by tmcconechy** [comment]
Right, Ok yeah the excel export function exports whats displayed on the screen so it uses the formatters to format it as per the page.

I'll fix the formatting issue for strings to use the locale as suggested.

**Comment by tmcconechy** [comment]
@sanx72 ended up using your fix. Its correct since parseNumber did already work with the current locale as a string. So it wasnt needed. Tidy up and added test on the link PR which you can review.
