### ISSUE TITLE
The checked attribute in renderEventTypes is incorrect, as checked='false' is still checked.

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#3170]
**Describe the bug**
The checked attribute should be implemented like the disabled attribute, so that an item can be either checked or unchecked.

 checked="${eventType.checked ? 'true' : 'false'}" ${eventType.disabled ? 'disabled="true"' : ''
to
 ${eventType.checked ? 'checked="true"' : ''}" ${eventType.disabled ? 'disabled="true"' : ''

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html'
2. Open the console to use the calendarAPI
// Uncheck the first event type 
$('.calendar').data('calendar').settings.eventTypes[0].checked = false
// Render the eventTypes based on the current settings
$('.calendar').data('calendar').renderEventTypes()

**Expected behavior**
checked = false, should not show a checked event type when rendered.

**Version**
master

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/69387481-d8250300-0d15-11ea-83fb-6c9956c5b116.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
Passed QA on all browsers. Moving to Done, will retest once beta is deployed.
![image](https://user-images.githubusercontent.com/39508864/72339502-5348db00-3701-11ea-82dc-b3434f34e903.png)

**Comment by brianjuan** [comment]
QA Passed in beta as well. Tested in http://4250-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html.
