### ISSUE TITLE
Application Menu: Issue Showing/Hiding Application menu

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#3171]
Since version  v4.18.0, the code to add trigger for handling application menu opening has been removed and moved into function for creating title button if it does not exist. Would expect the trigger to be added if the title button exists as well.
We believe this to be a bug as it does not work for applications that supply the button and do not use the global initialise button.

**Describe the bug**
Clicking on the Hamburger icon does not show the application menu (or hide it if menu already displayed).

**To Reproduce**
1. Test with an application that  supplies the button.
2. Click on Hamburger icon to show/hide the menu
3. Application menu does not show/hide.

**Expected behavior**
Expected the Applicartion menu to show/hide.

**Version**
v4.18.0 onwards

**Comment by tmcconechy** [comment]
@nbeare-infor Thanks for the submission. But the steps are not possible to follow, can you upload some runnable code so we can debug the issue?

Some people use a link like https://jsbin.com to host the reproduction.

Maybe looking at the example will help

1) add the app menu in the right place in the page structure: https://github.com/infor-design/enterprise/blob/master/app/views/components/applicationmenu/example-index.html#L6
2) https://github.com/infor-design/enterprise/blob/master/app/views/includes/header.html#L5

I do not think this is a bug on our end as the examples all work fine
http://master-enterprise.demo.design.infor.com/components/applicationmenu

Also i attached a small example you can run and see it working. This component can be confusing as the setup is in multiple places so i made this standalone example so you can see how it fits together in one place.

[Archive.zip](https://github.com/infor-design/enterprise/files/3880020/Archive.zip)

Hope This helps

**Comment by nbeare-infor** [comment]
@tmcconechy thanks for your prompt response.

We use GWT and UIBinding, so without you having the appropriate framework, it is not possible/easy to give you a simple standalone example.

In your example 
http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html 
the call to global initialize adds the trigger  to the button as well as setting the locale.

We do call the same initialize call to set the locale, but we have to add our controls ourselves (inc the application menu button) at a later stage,  so the global initialize does not find the button to add the trigger.

Because this was working in our application in versions of SOHO  up to v4.18.0, we see this as a regression.

**Comment by tmcconechy** [comment]
Still im not able to reproduce this issue. I checked the code and i don't see anything wrong. I made a new example and test case using the global initialize function.

As you can see it works in this example as well. Maybe you can use this to help see how you can fix it on your end? Or use it to construct a way to reproduce.

[Archive.zip](https://github.com/infor-design/enterprise/files/3887223/Archive.zip)

But since it does work in both cases for me. Im pretty sure you can make it work on your end with out a code change on our end.

**Comment by tmcconechy** [comment]
I was unable to reproduce this issue.
