### ISSUE TITLE
Datagrid: Misaligned columns

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3174]
**Description**
datagrid columns misaligned after you personalized the column(s) 
(i.e. remove a column, move a column, resize a column, and add a column then sort)

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html
2. Click on toolbar button `...` then click on `Personalize Columns`
3. In personalized modal window uncheck Quantity
4. Click on Close to close the modal window
5. Drag and Drop the column `Extra` (could be any column) to anywhere you want (e.g. beside the column `Order Date`
6. Resize the column `Extra`
7. Click again on toolbar button `...` then click on` Personalize Columns`
8.  In personalized modal window check Quantity
9. Click on Close to close the modal window
10. Sort the column `Extra`
11. See error

**Expected behavior**
columns should be aligned to its table header

**Version**
master-enterprise

**Screenshots**
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/56722184/69532921-c8c1e600-0fb1-11ea-9146-43ac7d4c372f.png">

[Video MP4.zip](https://github.com/infor-design/enterprise/files/3886110/Video.MP4.zip)

**Platform**
ALL browsers

**Additional context**
in Safari browser, just by moving the column `Extra` then resize it . makes the column misaligned

**Comment by tmcconechy** [comment]
Closing this as it will be fixed by #2825 
Also see #1818
