### ISSUE TITLE
Datagrid: Personalized column modal window was not centered on IE11

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3175]
**Describe the bug**
modal window of 'Personalize Column' was not centered

**To Reproduce**
1. Open IE 11 and Navigate to http://master-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html
2. Click on toolbar button `....`
3. Click on `Personalize Columns`

**Expected behavior**
modal window should be centered

**Version**
master-enterprise

**Screenshots**
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/56722184/69534044-00ca2880-0fb4-11ea-9588-a4dca1a63e99.png">

**Platform**
IE11

**Additional context**
On first load not all toolbar options were shown (maybe this is just a timing issue)
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/56722184/69534268-628a9280-0fb4-11ea-8783-f24ddc572244.png">

**Comment by tmcconechy** [comment]
Think this should be fixed on the PR im working on. So will move it in for now

**Comment by jbrcna** [comment]
QA Failed
the modal is not properly aligned within the Datagrid in IE11

Verified in http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html?
![image](https://user-images.githubusercontent.com/56722184/70687316-c5d13000-1ce9-11ea-8e8a-01a888400786.png)

**Comment by tmcconechy** [comment]
Closing as PR will solve

**Comment by jbrcna** [comment]
QA **Passed**
will move this ticket  to Done
Verified in http://4240-rc0-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html
