### ISSUE TITLE
Calendar-Need to pass calendar tooltip settings down to weekview component.

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#3179]
**Describe the bug**
Need to pass calendar tooltip settings down to weekview component.

**To Reproduce**
1. Go to 'https://4230-rc0-enterprise.demo.design.infor.com/components/calendar/test-ajax-events.html'
2. Hover over an event in month view and noticed the tooltip text is showing.
3. Switch view to Week
4. Hover over an event and noticed the tooltip text for the same event is not showing.

**Expected behavior**
Event and icon tooltip on monthview should also be shown on weekview and dayview events/icons.

**Version**

- ids-enterprise: v4.23.

**Screenshots**

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 78.0.3904.108 (Official Build) (64-bit)

**Comment by jbrcna** [comment]
QA **Passed**
Verified in https://master-enterprise.demo.design.infor.com/components/calendar/test-ajax-events.html

**Observation:**
Not All Events have tooltip (e.g. Discretionary Time Off)

![Large GIF (1286x590)](https://user-images.githubusercontent.com/56722184/70230610-ab500180-1793-11ea-98f6-24b0e3cca418.gif)
