### ISSUE TITLE
Calendar: Link on monthview should switch to day view when clicked to display all the events on that day.

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#3181]
**Describe the bug**

**To Reproduce**
1. Go to 'https://4230-rc0-enterprise.demo.design.infor.com/components/calendar/test-ajax-events.html'
2. Go to 'August 2018'
3. On August 22nd 2018, there are 5 events, noticed there is '+3 more' link
4. Click the link
5. Nothing happens

**Expected behavior**
Link should have a click event which brings up the day view to show all the events on that day.

**Version**

- ids-enterprise: v4.23

**Screenshots**
![image](https://user-images.githubusercontent.com/39130590/69575861-bedbbb00-0f90-11ea-9a8d-f6f8cbb4e13d.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in https://master-enterprise.demo.design.infor.com/components/calendar/test-ajax-events.html. Will retest once beta is deployed.
![image](https://user-images.githubusercontent.com/39508864/73836473-4fb0fb80-484a-11ea-88c4-9e36d2e17c21.png)

**Comment by CindyMercadoReyes** [comment]
Attaching the BBD to this new enhancement. 
[BDD_github#3181.docx](https://github.com/infor-design/enterprise/files/4165535/BDD_github.3181.docx)
