### ISSUE TITLE
Datagrid: Font color issue in 

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3182]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Issue incorrectly created...
