### ISSUE TITLE
Dropdown: The tooltip for long option names gets cut in modal

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#3185]
**Describe the bug**
When a dropdown has a long option name that gets truncated when selected, a tooltip is used when hovering it. In a modal, this tooltip gets cut (partly hidden beneath modal header). See attached GIF below:

![dropdown-tooltip](https://user-images.githubusercontent.com/1101770/69635701-4be84800-1055-11ea-93a3-defa00416324.gif)

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/test-on-modal.html
2. In DOM inspector, modify one of the select &lt;option&gt;s to have a long label / text
3. Select the long option in the dropdown
4. Hover the selected option

**Expected behavior**
A tooltip appears that shows the full text. Probably below the dropdown as opposed to above due to limited space?

**Actual behavior**
A tooltip is shown, but cut.

**Version**
- ids-enterprise: 4.23.0

**Additonal context**
Perhaps this is a general issue for tooltips when used in the top of any modal content, not dropdown specific.

**Comment by tmcconechy** [comment]
In this case the tooltip needs to be appended to the body or something. Since the parent modal has overflow for scrolling its being cut off. Either that or for the top field we could make the tooltip open down.

**Comment by ericangeles** [comment]
@tmcconechy this one is related to the ticket that I PR. #3106

**Comment by jbrcna** [comment]
**QA Passed** this issue is now resolved. Moving this ticket to Done. Thank you
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/dropdown/test-truncated-text-on-modal.html
![image](https://user-images.githubusercontent.com/56722184/82210531-d8f3c600-9941-11ea-8c69-5fa8234d60c2.png)
