### ISSUE TITLE
Dropdown: mobile search / filter doesn't work

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#3192]
**Describe the bug**
Hi, I don't know if it's by design, but when using dropdown in mobile mode, the search/filter functionality doesn't work 

**To Reproduce**
1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/example-index](https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/example-index)
2. Enter "device mode" (dev tools  and ctrl+shift+M to toggle device mode)
3. Select iPad, make sure device type set to "Mobile"
4. **Reload screen**
5. Try to type text inside the dropdown component
6. Notice that you cannot type, and there is no search icon

**Expected behavior**
Allow typing/filtering in dropdown when in mobile mode

**Version**

- ids-enterprise: v4.23.0 (but also in previous versions)

**Screenshots**
![chrome-dropdown-ipad](https://user-images.githubusercontent.com/34129313/69708790-e5bafe00-1104-11ea-8f4c-3fd734753b3d.PNG)

**Platform**
 - Device: Android / PC
 - Browser Name: Chrome / Firefox
 - Browser Version: latest

**Additional context**
thanks

**Comment by tmcconechy** [comment]
This was the correct behavior. We wanted mobile device to have a simpler feel more like a normal HTML select some of the functionality was too complex to make work on mobile device and we didn't think it would be required.

What do you suggest @jonathanamiran ? Do you have negative feedback on it changing like this in behavior

**Comment by tmcconechy** [comment]
Closing this as it was the behavior we decided on. To simplify the mobile experience
