### ISSUE TITLE
Datagrid: Focus is cut off after resizing the window from responsive view to full view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3193]
**Describe the bug**
Datagrid: Focus is cut off after resizing the window from responsive view to full view

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-single-column.html?theme=uplift&variant=dark
2.  Minimize the screen to responsive view
3.  Click and focus on "Some Compressor" product name 
 - Notice that the focus is full an not cut off
4. Maximize the window to full view (While the focus on responsive view is still active)

**Expected behavior**
Focus should be responsive 

**Version**
Beta 4.24 

**Screenshots**
1. Responsive view 
![image](https://user-images.githubusercontent.com/45757016/69714078-b75b1400-1140-11ea-9fc7-a060913f536b.png)

2. Full view after maximizing the window
![image](https://user-images.githubusercontent.com/45757016/69714092-c215a900-1140-11ea-9c54-91f568314220.png)

**Platform**
All Browser & OS

**Additional context**
NA

**Comment by tmcconechy** [comment]
This will also be fixed by work on #2825 so will close this out with a test, soon

**Comment by janahintal** [comment]
QA Passed. Issue is now resolved. Thank you. 
Tested in http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/test-editable-single-column.html?theme=uplift&variant=dark across all OS and Browser
