### ISSUE TITLE
Tree: Issue with tree not rendering nodes since v4.19.0

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#3194]
**Describe the bug**

A fix made in version v4.19.0 has caused us a fundamental issue with trees in that they no longer render the data. The offending line of code is in function getNodeHtml. The ‘fix’ which caused us the issue is the change
from
`var isChildren = typeof data.children !== 'undefined';`
to
`var isChildren = data.children && data.children.constructor === Array;`

This `(data.children.constructor === Array)` is now incorrectly returning false. On doing some research, found this page:

https://stackoverflow.com/questions/4775722/how-to-check-if-an-object-is-an-array

It suggests the best check is to use 
`Array.isArray(arr)`
 
Furthermore, it goes on to say that if the constructor gets overwritten via prototype [for example by frameworks such as GWT], arr.constructor === Array will return false, whereas Array.isArray(arr) will still return true;

So a better fix for the above [and one that works for us], would be:-
`var isChildren = data.children && Array.isArray(data.children);`

I have tested it.

**Expected behavior**
Tree to render all nodes.

**Version**
v4.19.0 onwards

**Comment by tmcconechy** [comment]
Can someone test and make this change. Adding to the sprint as its small but has an impact for the requesting team.

**Comment by nbeare-infor** [comment]
Thanks Tim.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by CindyMercadoReyes** [comment]
Hi @tmcconechy, there’s an error in console in Chrome, Firefox and EDGE browser. please see screen shot attached.
<img width="833" alt="Console error " src="https://user-images.githubusercontent.com/39101346/71008684-06002c00-20b7-11ea-9907-893a83ca1695.png">

**Comment by tmcconechy** [comment]
@CindyMercadoReyes I think when you click a link on the node it will give this message. Its Information only (blue not red) . So nothing wrong or nothing we can change or fix.

**Comment by CindyMercadoReyes** [comment]
Per my chat with Tim, the error in the console is a normal error. This issue passed QA on the second round of testing.
