### ISSUE TITLE
Datagrid: Intermittent misaligned column widths (indeterminate mode)

### ISSUE THREAD

**Issue by tobywicksinfor** [infor-design/enterprise#3195]
Depending on the length of the header and/or length of the cell content in the data grid the column widths will not always align. Seems to only be relevant when running in paging indeterminate mode.

**To Reproduce**
1. Change the **getColumns()** and **getData()** functions in components/datagrid/example-paging-indeterminate.html:
```
    function getColumns() {
      if (!PAGING_COLUMNS) {
        PAGING_COLUMNS = [
          { id: 'f1', name: 'This is a really long header name. This is a long name.', sortable: false, field: 'productName' },
          { id: 'f2', name: 'Header Two', sortable: false, field: 'activity' },
          { id: 'f3', name: 'Header Three', sortable: false, field: 'activity' }
        ];
      }

      return PAGING_COLUMNS;
    }

    function getData() {
      if (!PAGING_DATA) {
        PAGING_DATA = [
          { productName: 'This is the content for a cell that has a long header', activity: 'Assemble Paint' },
        ];
      }

      return PAGING_DATA;
    }
```
1. Go to 'http://localhost:4000/components/datagrid/example-paging-indeterminate.html'
2. Resize the width of the page to approximately 670px
3. Refresh the screen
4. The columns are misaligned.

**Expected behavior**
The columns are not misaligned with the cell content.

**Version**
 *  IDS Enterprise Components - v4.24.0-dev
 *  Date: 2019-11-28T00:18:47.689Z
 *  Revision: 9247bac99495e3ac455e93c67e2f87815d78264f

**Screenshots**
![Datagrid column misalignment](https://user-images.githubusercontent.com/40477207/69768243-ba511580-11cf-11ea-94b3-8685f2838d2b.gif)

**Platform**
 * Google Chrome | 78.0.3904.108 (Official Build) (64-bit) (cohort: Stable)
 * Revision | 4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}
 * OS | Windows 10 OS Version 1809 (Build 17763.864)

**Comment by tmcconechy** [comment]
Working on a general fix for this https://github.com/infor-design/enterprise/issues/2825 which should be done this sprint.

We have a few issues already like this like https://github.com/infor-design/enterprise/issues/2835 and https://github.com/infor-design/enterprise/issues/1818 which should all be solved when thats done. So calling this duplicate for now. Please watch those and test when done.
