### ISSUE TITLE
Input: Text doesn't appear if used with the Builder Actions class and the Soho Dark theme

### ISSUE THREAD

**Issue by spikeeedge** [infor-design/enterprise#3199]
**Describe the bug**
The textbox value doesn't appear if used with the "builder-actions" class and the Soho Dark theme.

**To Reproduce**
1. Go to [http://localhost:4000/examples/saleshub/edit-profile.html?theme=soho&variant=dark](http://localhost:4000/examples/saleshub/edit-profile.html?theme=soho&variant=dark)
2. Enter value in Company Address/Phone Number/Website textboxes.
3. Notice the entered text is not shown in the textbox.

**Expected behavior**
The text entered should be shown clearly.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
Replicate the issue on fly
![Soho Dark Theme issue with Builder Action - Live Demo](https://user-images.githubusercontent.com/11339925/69931167-21dfcb80-1516-11ea-9834-812a5271bf07.gif)

[http://localhost:4000/examples/saleshub/edit-profile.html?theme=soho&variant=dark](http://localhost:4000/examples/saleshub/edit-profile.html?theme=soho&variant=dark)
![Soho Dark Theme issue with Builder Action](https://user-images.githubusercontent.com/11339925/69931169-22786200-1516-11ea-895e-204fa3d0638e.gif)

**Platform** 
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version: Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Looks like maybe this was due to recent changes. I think we should fix this one.

**Comment by EdwardCoyle** [comment]
Not due to recent changes... seems like the background color on the Dark theme here was never correct.  The text color is clashing because the background should be darker, not white.

**Comment by jbrcna** [comment]
QA **PASSED**

Verified in
http://4240-beta0-enterprise.demo.design.infor.com/examples/saleshub/edit-profile.html?theme=soho&variant=dark
