### ISSUE TITLE
Modal Control: Pressing Enter key on Checkbox closes the modal

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#320]
**Describe the bug**
Pressing Enter key on Checkbox closes the modal

**To Reproduce**
1. Go to http://480-rc0-sohoxi.demo.design.infor.com/components/modal/test-checkboxes-cut.html
2. Click the Add Context button to open modal
3. Tab through the Checkbox field
4. Press Enter key, modal will close

**Expected behavior**
The enter should not close the lodal
**Screenshots**
None
**Platform**
All Browsers 

**Additional context**
None

**Comment by brianjuan** [comment]
http://localhost:4000/components/modal/test-checkboxes-cut.html
http://master-enterprise.demo.design.infor.com/components/modal/test-checkboxes-cut.html
Passed QA testing across all browsers
