### ISSUE TITLE
Tabs: Focus is overlapping another tab after adding new Tab

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3200]
**Describe the bug**
Tabs: Focus is overlapping another tab after adding new Tab

**To Reproduce**
1. Go to  http://master-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html?theme=uplift&variant=light
2.  Fill up the Form 
 Tab Name = Test
 Tab Content = Test
 Tab Index = Leave blank 
 Dismissible = Unchecked 

3. Use the addTabButtonCallback property on the Tabs Control API to supply a callback for the Add Tab Button
4. Click '+' add tab button 

**Expected behavior**
The New tab must be displayed in the 1st index and the focus should not overlap

**Version**
4.24 Beta

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/70021923-4ba7f980-15cd-11ea-980c-2c93399a1c76.png)

**Platform**
All Platform 
Tested in Win10 Chrome 78

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Probably a demo app issue but worth looking into in the near future.

**Comment by tmcconechy** [comment]
Descoping this for now
