### ISSUE TITLE
Datepicker: Today is changing PM/AM value

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3202]
**Describe the bug**
Hi! 
We want a way to allow the user to set the time they want and then select todays date by clicking Today if that is wanted. This works fine for some time periods (especially in he morning) but not for 12:00 - 12:59 **AM** when it changes to 12:XX PM And for 1:00-11:59 **PM** which changes to XX:XX **AM**. 

**If the user click the current date, then it works fine. It is just when clicking Today that this issue occur.**

**Note** that we do not want it to choose current time as in this issue https://github.com/infor-design/enterprise/issues/2575. 

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/test-12hr-time.html
2. Click on the datepicker
3. Change the time to "11:55 AM"
4. Click Today
5. Note that the time remains 11:55 (which is what we want)
6. Click on the datepicker icon again 
7. Change the time to "12:10 AM"
8. Click Today
=> Time changes to 12:10 **PM**
9. Click on the datepicker
10. Change the time to "6:55 PM"
11. Click Today
=> Time changes to "6:55 **AM**"

**Expected behavior**
I think this could be handled differently depending on the value of useCurrentTime option,  If useCurrentTime is false I do not think current time should be used while clicking Today (If useCurrentTime is true then Today should change to current time). 

When "useCurrentTime" setting is false, the Time should not change at all when clicking Today (just as when you click todays date). So the "12:XX AM" should stay "12:XX **AM**" after clicking Today and PM should stay PM for all afternoon values.

**Version**

- ids-enterprise: v. 4.23.0

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/70044282-5e690100-15c2-11ea-9014-0c484492f741.png)

![image](https://user-images.githubusercontent.com/8664975/70044298-6759d280-15c2-11ea-9226-0830e25a8d46.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version:Version 78.0.3904.108 (Official Build) (64-bit)

**Additional context**
Currently the sample in the steps to reproduce does not have the "useCurrentTime" option set, but I think it should have been false by design according to spec? I've also tried to add the "useCurrentTime" option and set it to false. But still have issues with AM/PM changes.

**Comment by SofiK** [comment]
Or should this be a enhancement request to add a new option to allow not to automatically change AM/PM? (time values are not changed only AM/PM)

**Comment by tmcconechy** [comment]
I suppose i would call this a bug. We had an issue similar to this. I don't think it should randomly change it from AM to PM.

As of now today clicking will either insert the current time or midnight. Need a third option to set to the selected time. Which i think is part of the problem.

**Comment by janahintal** [comment]
QA Passed. Thankyou. Issue is now resolved. 
Tested in https://master-enterprise.demo.design.infor.com/components/datepicker/test-12hr-time.html?theme=uplift&variant=dark across all platfrom.
