### ISSUE TITLE
Hyperlinks in DataGrid still causes redirection, even when href is '#'

### ISSUE THREAD

**Issue by rvaja-infor** [infor-design/enterprise#3207]
**Describe the bug**
Redirects in grids still occur when clicking a hyperlink in a grid cell, even though they should be prevented if the href is '#'.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-dynamic-links.html
2. Click on a hyperlink within the Grid
3. URL in address bar changes to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-dynamic-links.html#

**Expected behavior**
The URL in address bar should not change

**Version**
Found in v4.19.4. and also observed in 4.23.0

**Screenshots**
N/A

**Platform**
 - Device: Desktop PC
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version:  78.0.3904.108 (Official Build) (64-bit)

**Additional context**
Attempting to use this in a dialog to navigate a folder structure. Because it redirects, clicking on any link causes the dialog to be dismissed and go to the redirected URL.

**Comment by tmcconechy** [comment]
I have a fix on my branch with #2825

**Comment by brianjuan** [comment]
http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/test-dynamic-links.html
Passed QA in all browsers, moving to Done.
