### ISSUE TITLE
Locale: Getting wrong data in the locale

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3208]
**Describe the bug**
We are seeing the wrong locale being used in some cases. For example en-GB is using en0US settings. Possible timing issue

**To Reproduce**
1. Go to https://jsfiddle.net/ekonfdc1/
2. Should be using dd/MM/yyyy for en-GB
3. But it is not (note it may work initially but if you reload the page you will see the wrong locale)
4. Also not that en-US and en-GB scripts are appended more than one time.

**Expected behavior**
Should use en-GB if specified.

**Version**
- ids-enterprise: [e.g. v4.24.0 ]

**Platform**
 - Chrome

**Additional context**
Guessing either #2368 or #2238 were the ones which caused the issue.

**Comment by brianjuan** [comment]
http://4240-beta0-enterprise.demo.design.infor.com/components/locale/test-format-date
Passed QA on all browsers, moving to Done.

**Comment by janahintal** [comment]
QA Passed. Issue is now resolved. Thank you. 
Tested in http://4240-beta0-enterprise.demo.design.infor.com/components/locale/test-format-date
