### ISSUE TITLE
Modal Control: Pressing Enter key on File upload field closes the Modal

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#321]
**Describe the bug**
Pressing Enter key on File upload field closes the Modal

**To Reproduce**
1. Go to http://480-rc0-sohoxi.demo.design.infor.com/components/modal/test-fileupload.html
2. Click Show Modal button
3. Tab through the Fileupload field
4. Press Enter key, modal will close

**Expected behavior**
Modal should not close

**Screenshots**
None

**Platform**
All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
FIxed via https://github.com/infor-design/enterprise/pull/472#issuecomment-416529060

**Comment by brianjuan** [comment]
http://4100-beta1-enterprise.demo.design.infor.com/components/modal/test-fileupload.html
Passed QA testing
