### ISSUE TITLE
Datagrid Grouping on multiple columns

### ISSUE THREAD

**Issue by GeTeBr-Infor** [infor-design/enterprise#3213]
**Is your feature request related to a problem? Please describe.**
The grouping functionality of the Datagrid should be extended. Currently when grouped on multiple columns the columns are concatenated on the row group line. 
Also it should be possbile to aggregate on multiple columns. Aggregation should be possible as sum,min,max,count and avg.
The Grouped columns should be in their own columns in the grid. 

**Describe the solution you'd like**
I want to be able to group the datagrid on multiple columns and have each grouped column shown in it's own place. when resizing the columns the group headers should also resize.

**Describe alternatives you've considered**
I've tried to implement a custom group row formatter, but I wasn't able to implement a tabel in the row. So when resizing the columns the group headers didn't resize. 

**Additional context**

**Comment by tmcconechy** [comment]
We may have to merge some changes in that im working on. I've made some substantial changes will review.

**Comment by tmcconechy** [comment]
I think this issue has been fixed (has a PR)
