### ISSUE TITLE
Datagrid: Filter window should close when user scrolls.

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#3216]
**Describe the bug**

**To Reproduce**
1. Go to  http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html 
2. Click on Product Name filter
3. Scroll to the right. 

Second scenario 
1. Go to  http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html 
2. Click on More ( ... on top right of the Grid)
3. Scroll to the right. 

**Expected behavior**
The filter window should disappear just as if the user clicks on a row does. This is also the case with the More (top ...) window.

**Version**
- ids-enterprise-ng:  4.24

**Screenshots**

![image](https://user-images.githubusercontent.com/17933529/70331390-5fda3980-180d-11ea-8785-b12119e2932d.png)

![image](https://user-images.githubusercontent.com/17933529/70331369-5355e100-180d-11ea-94c0-f23bf49757b7.png)

**Platform**
Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by janahintal** [comment]
This issue is now resolved. Thanks.
Verified in http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift&variant=light across all platform
