### ISSUE TITLE
Locale: unable to enter all digits for a decimal number when locale is fr-FR

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#3217]
**Describe the bug**
Unable to enter all digits for a decimal number when the locale is set to fr-FR.

**To Reproduce**
1. Go to http://latest-enterprise.demo.design.infor.com/components/mask/test-number-mask-gauntlet.html?locale=fr-FR
2. For the Number: 1 000,00 field (column 1, second row), try to enter 1234,
3. The error is when the decimal separator is entered, the value becomes 123,
4. The expectation is the value is 1 234,
5. For the Millions: 1 000 000,00 field (column 1, fourth row), try to enter 1234567,
6. The error is the last digit of 7 cannot be entered, the value becomes 123 456
7. The expectation is the value is 1 234 567,
8. For the Billions: 1 000 000 000,00 field (column 1, sixth row), try to enter 1234567890,
9. The error is the last digit that can be entered is 8, the value becomes 12 345 678
10. The expectation is the value is 1 234 567 890,

**Expected behavior**
Expectations are stated above.

**Version**

- ids-enterprise: 4.23.0

**Screenshots**
![locale-number-mask-fr-FR-issue](https://user-images.githubusercontent.com/20212079/70346624-58725a80-1824-11ea-938e-7efe89558734.gif)

**Platform**
 - All

**Additional context**
For the fr-FR locale, also seeing NaN in the placeholder and labels for the Quintillion fields.

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks. 
Tested in http://master-enterprise.demo.design.infor.com/components/mask/test-number-mask-gauntlet.html?locale=fr-FR across all browsers.
