### ISSUE TITLE
Popdown: Tab order broken when tabbing into the popdown and back out of it

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3218]
**Describe the bug**
We have an implementation where we have a form that we want to display inside a popdown. We want to be able to tab into the popdown, tab thru the fields, and on the blur for the last field, close the popdown and focus into the next field from the base form.

I think this may have something to do with the control reparenting the popdown contents div to the body?

**To Reproduce**
1. Copy [test-tab-example.zip](https://github.com/infor-design/enterprise/files/3933562/test-tab-example.zip) into /components/popdown
2. Navigate to /components/popdown/test-tab-example.html
3. Click or tab into the first Date field
4. Press tab (the popdown opens, and the first field is focused)
5. Press tab (the second field in the popdown is focused)
6. Press tab (the popdown is dismissed, but the next field on the base form (Another Field) isn't focused)

**Expected behavior**
Another Field should get focused when the popdown is dismissed.

**Version**
- ids-enterprise: 4.24.0-dev

**Screenshots**
![PopdownTabbingIssue](https://user-images.githubusercontent.com/22107636/70348004-5c53ac00-1827-11ea-9e1c-890072f009fe.gif)

**Platform**
 - All

**Comment by lipetzan** [comment]
Raising priority for full-time users requiring and relying on keyboard nav.

**Comment by tmcconechy** [comment]
This was addressed in 4.25
