### ISSUE TITLE
Calendar not all events are render in day or week view (event time)

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#3222]
**Describe the bug**

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html'
2. Click on the 'Chiropractor' Event on the 2nd of December
3. Change the start time to 3:20
4. Change the view to 'Week'
5. The event is not visible for the day.

**Expected behavior**
All times are rendered to the Day and Week views.

**Version**
master

**Platform**
 - OS Version: Windows 10
 - Browser Name . chrome

**Comment by janahintal** [comment]
Failed upon testing in http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html

![image](https://user-images.githubusercontent.com/45757016/74330178-2bb26480-4dcc-11ea-8990-1ed27fe58b7e.png)

![image](https://user-images.githubusercontent.com/45757016/74330249-48e73300-4dcc-11ea-8493-4f4a24982105.png)



Expected Duration is 3 Days please refer to the above photo.

**Comment by tmcconechy** [comment]
Yes, i see that as well. @deep7102 ?

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/calendar/example-index Across all browsers
