### ISSUE TITLE
Datepicker: Layout issue in IE11

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3226]
**Describe the bug**
the date picker's calendar in IE11 has a different design

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html
2. Click on first date picker
3. See error

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/70522616-6e618180-1b7c-11ea-911b-fe4db8fc8f5b.png)

**Version**
4.24-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/70521375-16c21680-1b7a-11ea-9ea5-dcb1d5aa2051.png)

**Platform**
IE 11

**Additional context**

**Comment by jbrcna** [comment]
QA **FAILED**
Browser: IE11
The design seems fine, however, the functionality of the calendar in datepicker is not working except for the ‘today’  function. 

Verified in http://4240-beta0-enterprise.demo.design.infor.com/components/datepicker/example-index.html

**Comment by tmcconechy** [comment]
Closing as PR will solve

**Comment by jbrcna** [comment]
QA **Passed**
the issues were now resolved
Verified in http://4240-rc0-enterprise.demo.design.infor.com/components/datepicker/example-index.html
