### ISSUE TITLE
Charts: Add a double click to all chart elements on all chart types

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#3229]
**Is your feature request related to a problem? Please describe.**
Our current product allows for a double click on the chart pieces to open the record link to the chart element. It is a way of drilling into the data that builds that chart. This also follows with the functionality of double clicking on a list to open the record

**Describe the solution you'd like**
Emit a double click event when clicking any chart piece on any chart.

**Describe alternatives you've considered**
We already support a right mouse click (context menu) to open record but customers are familiar with the double click as a quick way to access the data.

**Additional context**
NA

**Comment by krahs1** [comment]
This is required for LMCLIENT-25710
https://jira.lawson.com/browse/LMCLIENT-25710

and LMCLIENT-23865
https://jira.lawson.com/browse/LMCLIENT-23865

**Comment by krahs1** [comment]
Also tickets https://jira.lawson.com/browse/LMCLIENT-31885 and https://jira.lawson.com/browse/LMCLIENT-33371

**Comment by tmcconechy** [comment]
What do you guys do for mobile with double click?

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in 
http://localhost:4000/components/bullet/test-double-click.html
http://localhost:4000/components/column/test-double-click.html
http://localhost:4000/components/column-grouped/test-double-click.html
http://localhost:4000/components/column-stacked/test-double-click.html
http://localhost:4000/components/column-stacked/test-double-click-singular.html
http://localhost:4000/components/positive-negative/test-double-click.html
http://localhost:4000/components/area/test-double-click.html
http://localhost:4000/components/bubble/test-double-click.html
http://localhost:4000/components/line/test-double-click.html
http://localhost:4000/components/scatterplot/test-double-click.html
http://localhost:4000/components/donut/test-double-click.html
http://localhost:4000/components/pie/test-double-click.html
http://localhost:4000/components/radar/test-double-click.html

**Comment by CindyMercadoReyes** [comment]
Attached please find the BDD for this enhancement ticket. 
[story_github3229.docx](https://github.com/infor-design/enterprise/files/6212455/story_github3229.docx)
