### ISSUE TITLE
Pie Chart Control: Selected slice is being deselected when resizing a page 

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#323]
**Describe the bug**
Selected slice in the pie chart is being deselected when resizing a page.

**To Reproduce**
1. Go to http://480-rc0-sohoxi.demo.design.infor.com/components/pie/example-index.html
2. Click the Green slice to select it
3. Resize the page
4. Green slice will be deselected

**Expected behavior**
Selected slice must not be deselected even a user resizes a page.

**Screenshots**
No applicable screenshot.

**Platform**
 - MAC and Windows
 - All browsers

**Additional context**
No additional context.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
