### ISSUE TITLE
Datagrid group header text appears too large in iOS device, and the sort arrow is not visible for some columns

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3234]
**Describe the bug**
Datagrid group header text appears too large in iOS device, and the sort arrow is not visible for some columns.

**To Reproduce**
1. Open iOS device
2. Go to http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouping.html

**Expected behavior**
Header and text should be responsive in mobile iOS view, and the sort icon should not be cut off

**Version**
IDS enterprise beta0 4.24

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/70689799-2f543d00-1cf0-11ea-823c-c7cc226b9c76.png)

**Platform**
iOS Mobile devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
It seems to work ok if you resize the page, just does this when you rotate. Calling this minor for picking up at a future date or if customers find it annoying.

**Comment by tmcconechy** [comment]
I think i fixed this one.
