### ISSUE TITLE
Datagrid: Missing Empty Message Icon for empty state in Windows IE

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3240]
**Describe the bug**
Datagrid: Missing Empty Message Icon for empty state in Windows IE

**To Reproduce**
1. Open IE browser
2. Go to http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-filter.html?theme=soho&variant=light
3. Filter until Empty Message is shown or records is empty 

**Expected behavior**
For empty state, the Empty Message icon should appear in the grid for both Theme. 

**Version**
Beta 4.24 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/70772329-1eb6cc00-1daf-11ea-8ba7-a777cd5dbac7.png)

**Platform**
Windows 10 IE 11 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Closing as PR will solve

**Comment by janahintal** [comment]
Issue is now resolved. Thank you! 
Re-tested in http://4240-rc0-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-filter.html?theme=uplift&variant=light
