### ISSUE TITLE
Datepicker: numbers with legend on upcoming month were hard to read

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3241]
**Describe the bug**
use `Subtle` theme and `Dark` variant

**To Reproduce**
1. Go to 'https://master-enterprise.demo.design.infor.com/components/datepicker/example-legend.html?theme=soho&variant=dark
2. See error

**Expected behavior**
the calendar inside the datepicker should be easily readable

**Version**
4.23

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/70796549-897efc00-1ddd-11ea-9e3b-853f2d3702b2.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Descoping this for now
