### ISSUE TITLE
Locale: Separate the language parts of the date format further

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3244]
**Describe the bug**
While its possible now to use Locale.setLanguage('se') to set the language to english some parts like the day names and week names are not separated full. 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/monthview/test-specific-locale-lang.html
2. Notice that the lang is de but the format is da-DK
3. The days are in Danish but should be in english.

**Expected behavior**
We need the language based parts of the locale to be moved into the language strings. And try and keep the API backwards compatible if possible

**Version**
- ids-enterprise: [e.g. v4.24]

**Platform**
 - Any

**Additional context**
https://teams.microsoft.com/l/message/19:6d4c9079385840c0bc61e55bcdd16a33@thread.skype/1576226227220?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1576226227220&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Problems&createdTime=1576226227220

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in 
https://master-enterprise.demo.design.infor.com/components/calendar/test-specific-lang.html
https://master-enterprise.demo.design.infor.com/components/monthview/test-specific-lang.html
https://master-enterprise.demo.design.infor.com/components/datepicker/test-two-locales-same-page.html
https://master-enterprise.demo.design.infor.com/datepicker/test-specific-lang.html
