### ISSUE TITLE
Locale: Add fr-CA translations

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3245]
**Describe the bug**
I found out that the fr-CA language translation file is very different than fr_FR, i thought they were the same.

**Expected behavior**
Need to add strings to fr-CA and make fr-CA use them and not use shared strings in fr-FR

**Version**
- ids-enterprise: [e.g. v4.24]

**Additional context**
From email (translation team)

**Comment by brianjuan** [comment]
Passed QA, tested in http://master-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?locale=fr-CA. Will retest in IE and once 4.25.0-beta is deployed.

**Comment by brianjuan** [comment]
Passed QA in beta as well, tested in http://4250-beta0-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?locale=fr-CA
