### ISSUE TITLE
Datagrid: On Fixed Header Example, column's edge moves faster than the pointer when resizing

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3251]
**Describe the bug**
Datagrid: On Fixed Header Example, column's edge moves faster than the mouse pointer when resizing

**To Reproduce**
1. Go to http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html
2. Maximize the browser
3. Drag the right edge of Product Name column to the left
4. See issue: Notice that the line moves faster to the left than the mouse pointer
5. Now try to drag to the right, see issue: the line also moves faster to the right

**Additionally**
These pages exhibit some strange resize behavior:

- http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/test-column-resize-issue.html
- http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/test-columns-mixed.html
- http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/test-columns-percent.html
- test tree http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/example-tree

**Expected behavior**
Column's edge/line should be at the same position with the mouse pointer when resizing.

- [x] resize works on percent
- [x] resize works on tree
- [x] resize works on width and min width
- [x] resize cursor stays "close" to the mouse position
- [x] resize affects only adjacent column like now

**Version**
- ids-enterprise: v4.24.0-beta0

**Screenshots**
![datagrid-linemovesfaster](https://user-images.githubusercontent.com/39508864/70882251-fd055100-2009-11ea-9c4f-f6d391c41c4a.gif)

**Platform**
 - All Mac and Windows browsers

**Additional context**
N/A.

**Comment by brianjuan** [comment]
Also happens in:
http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/test-columns-class.html and
http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/test-columns-colors.html

**Comment by tmcconechy** [comment]
@deep7102 wondering if you have any ideas. I looked at this as well as it was mentioned on the PR but could not figure out why. This would be nice to fix but is not required as its a problem only on some layouts.

**Comment by tmcconechy** [comment]
An observattion was noted on #3308 
```
The error is in the master branch, http://master-enterprise.demo.design.infor.com/components/datagrid/test-columns-stretch-column.html, as 'dragend.datagrid', and 'drag.datagrid' events are trying to set a style on the next column, but there is not one on the last column

        const nextCol = DOM.getNextSibling(self.currentHeader, ':not(.is-hidden)'); 
        const nextColGroup = DOM.getNextSibling(currentCol, ':not(.is-hidden)'); (undefined)
        const nextColWidth = parseInt(nextColGroup.style.width, 10); (Therefor errors as it does not exist)

There are also odd behaviour on http://master-enterprise.demo.design.infor.com/components/datagrid/test-columns-percent.html, as it uses the percentage as the pixel width and then restyles based on the change in drag.

```

**Comment by tmcconechy** [comment]
Also test tree grid.

**Comment by brianjuan** [comment]
I am experiencing a strange movement when resizing the Product ID column in https://4260-beta0-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html, please see video below. 
![vertical-tabs](https://user-images.githubusercontent.com/39508864/75333421-1441a400-58c1-11ea-87d4-9eb1840308db.gif)

But QA passed on other links in this ticket.

**Comment by brianjuan** [comment]
Passed QA in all browsers, issue above is now fixed. Tested in https://4260-rc0-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html. Moving to Done.
![datagridresize1st](https://user-images.githubusercontent.com/39508864/75764087-4c8d2a80-5d78-11ea-97d9-412e2939110a.gif)
