### ISSUE TITLE
Dropdown clearable 'x' is not working in Mobile and Browser

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3252]
**Describe the bug**
Dropdown clearable 'x' is not working in Mobile and Browser

**To Reproduce**

Scenario 1
1. Open mobile device 
2. Go to  http://4240-beta0-enterprise.demo.design.infor.com/components/dropdown/example-clearable.html?theme=uplift&variant=light
3. Open the dropdown Clearable field 
4. Click the 'x' button
- Notice that the field is not being cleared

Scenario 2
1. Open browser
2. Go to  http://4240-beta0-enterprise.demo.design.infor.com/components/dropdown/example-clearable.html?theme=uplift&variant=light
3. Open the dropdown Clearable field 
4. Notice that the 'x' button is not appearing 

**Expected behavior**
Scenario 1 - The field should be cleared 
Scenario 2 - The 'x' button should appear 

**Version**
IDS Beta0 4.42
**Screenshots**
Screnario 1
![image](https://user-images.githubusercontent.com/45757016/70890523-3e086000-2020-11ea-8025-97402846d3da.png)

Scenario 2
![image](https://user-images.githubusercontent.com/45757016/70890480-229d5500-2020-11ea-8f9b-347e835f86f9.png)

**Platform**
Browsers and Mobile devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
We changed the mobile behavior so its more like a mobile select on mobile devices. So there is no X possible. It simply has a simpler behavior. 

Closing for now as wont fix
