### ISSUE TITLE
Editor: Heading buttons are not working in Customize Buttons example page

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3253]
**Describe the bug**
Editor: Heading buttons are not working in Customize Buttons example page.

**To Reproduce**
1. Go to http://4240-beta0-enterprise.demo.design.infor.com/components/editor/example-customize-buttons.html
2. Highlight first paragraph in Editor
3. Click H3 or H4 buttons
4. See issue: heading won't be applied to first paragraph

**Expected behavior**
Heading buttons should still work or should be updated to the new font picker.

**Version**
- ids-enterprise: v4.24.0-beta0

**Screenshots**
N/A

**Platform**
 - All platforms, OS and devices

**Additional context**
N/A

**Comment by tmcconechy** [comment]
@EdwardCoyle - did we decide to just remove the buttons? If so maybe a quick update to this example or decide if it can actually be removed? Just for cleanup

**Comment by EdwardCoyle** [comment]
@tmcconechy Yeah not sure why the buttons are still here.  The Fontpicker is supposed to completely replace them.  I'll take a look.

**Comment by tmcconechy** [comment]
Found a fix.. Pushing it.

**Comment by brianjuan** [comment]
http://4240-rc0-enterprise.demo.design.infor.com/components/editor/example-customize-buttons.html
Passed QA in all browsers, moving to Done.
