### ISSUE TITLE
Editor: pastes the text after using undo 

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3260]
**Describe the bug**
In Chrome and Safari browser, when using undo functionality (i.e. ctrl z) Editor pastes the text

**To Reproduce**
1. Go to http://4240-beta0-enterprise.demo.design.infor.com/components/editor/example-index?theme=uplift&variant=light
2. Type in a text in Editor
3. Select the text then change the header
4. Click` View Source`
5. Click  `View Visual`
6. Press `Ctrl + z` or `command + z `in mac

**Expected behavior**
it should not paste the text but rather undo the changes

**Version**
4.24 beta 0 

**Screenshots**
![Large GIF (1274x506)](https://user-images.githubusercontent.com/56722184/70960098-08638580-20b9-11ea-9ff6-c1e8ea9e1a12.gif)

**Platform**
Chrome & Safari

**Additional context**
you should select the text otherwise you won't see the issue.

**Comment by tmcconechy** [comment]
We dont really support undo functionality. We could maybe consider adding it in the future (if we have time).
This is almost a non - bug but will keep it as minor for now and possibly close later.

**Comment by tmcconechy** [comment]
Can  not longer reproduce this issue since changing the buttons around.
