### ISSUE TITLE
Editor: strikethrough icon is not highlighted when used

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3261]
**Describe the bug**
Strikethrough icon is not highlighted when used

**To Reproduce**
1. Go to http://4240-beta0-enterprise.demo.design.infor.com/components/editor/example-index?theme=uplift&variant=light
2. Type in any text or select a word in editor
3. Format the font of the text by clicking strikethrough icon

**Expected behavior**
when the icon is used it should be highlighted

**Version**
4.24 beta 0 

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/70979242-47f79500-20ec-11ea-878a-7060ac1b6539.png)

**Platform**
EDGE, IE 11, Firefox

**Additional context**

**Comment by tmcconechy** [comment]
Test this on 4.26 and this is no longer an issue. The styling has changed and the icon is highlighting now. Something must have changed to fix this.

**Comment by jbrcna** [comment]
The issue persists in IE 11
IDS v4.27.0-dev
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/56722184/76195463-4dfc9e00-6223-11ea-8965-ed2fd8423671.png">

IDS v4.26.0-beta0
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/56722184/76200042-e4cd5880-622b-11ea-8cbd-cc083a314d4d.png">

**Comment by tmcconechy** [comment]
Sorry i should explain this differently. Decided not to fix this issue as its working in chrome and minor.
IE 11 is not going to be supported too much longer so its not worth doing anything at all with this.

**Comment by jbrcna** [comment]
Will take note of this. We'll deprioritize testing in IE11.
