### ISSUE TITLE
Weekview/Calendar: Day size is inconsistent

### ISSUE THREAD

**Issue by jamie-norman** [infor-design/enterprise#3262]
**Describe the bug**
Based on testing and implementing weekview, we came up with a couple bugs and suggestions.

- [ ] The weekview days are uneven because of the size of the text.
- [ ] Possibly have more contrast between the date and the day name, spacing, color, etc. Same with Day View — could consider stacking with very different sizes. There should be enough vertical space
- [ ] Consistency with the day names on the Month View. It's nice to have it fully spelled out as it is in Day/Week View. Month should follow suit. Consider abbreviating if needed for responsive views

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=uplift&variant=light
2. Click On weekview,
3. Notice the widths of the weekdays aren't even, as expected. Wednesday in particular is wide, Friday is really skinny ect.

**Expected behavior**

**Version**
- ids-enterprise: [4.24.x]

**Platform**
- All

**Additional context**
Started as an ms teams chat

**Comment by tmcconechy** [comment]
What if we just made them all abbreviated 3 width days? If we dont do that would have to make them fixed size which may introduce scrolling.

Or we could try and find the widest and set size to that.

What do you suggest for "Possibly have more contrast between the date and the day name, spacing, color, etc. Same with Day View — could consider stacking with very different sizes. There should be enough vertical space" ?

**Comment by jamie-norman** [comment]
![image](https://user-images.githubusercontent.com/44705854/71034791-cd287d00-20df-11ea-9b44-a944be6a990b.png)
I do like the way G Cal styles date/day

**Comment by jamie-norman** [comment]
Not suggesting copying directly, but just illustrating the contrast

**Comment by tmcconechy** [comment]
OK i used your design.... I do like this as well.

**Comment by janahintal** [comment]
QA Passed. This issue is now resolved.
Verified in  https://master-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=soho&variant=light&?locale=af-ZA across all platform thank you.

![image](https://user-images.githubusercontent.com/45757016/77143974-a8b5b580-6abf-11ea-9ec5-7b8e085f8af4.png)
