### ISSUE TITLE
Datagrid: Header display issue with column groups

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3265]
Describe the bug
The column group header does not display correctly when the list is made read-only via the isList grid option.  Using various combinations of themes and variants.

To Reproduce

1. Using the attached example-grouped-headers.html
2. Click on More (....) button
3. Select Theme of 'Vibrant'
4. Select Variant of 'Light'
5. Notice that the grouped column headers do not display correctly

Expected behavior
Grouped column headers display correctly.

Version
v4.25.0-dev

Screenshots

**Comment by claudenbach** [comment]
[Git-3265.zip](https://github.com/infor-design/enterprise/files/3975841/Git-3265.zip)

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/71041921-f0f3bf00-20ef-11ea-9aba-fa17a329d218.png)

**Comment by tmcconechy** [comment]
@claudenbach any indication this is a new issue starting in 4.25-dev? Or just something you found and not sure?

**Comment by claudenbach** [comment]
I'm not sure when the issue started.  Just noticed it when a jira ticket came in.

**Comment by tmcconechy** [comment]
Ok, thanks will treat it as regression for now.

**Comment by tmcconechy** [comment]
Fixed this but found it was never working so not a regression. Was too risky to change at RC time so added to 4.25.

**Comment by janahintal** [comment]
QA Passed. This issue is now resolved. Thank you. 
Tested in http://master-enterprise.demo.design.infor.com/components/datagrid/example-list-grouped-headers.html?theme=soho&variant=contrast across all platform.
