### ISSUE TITLE
Contextual Action Panel: Responsive view issue in IE

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3267]
**Describe the bug**
in IE 11 the header was not properly aligned and in EDGE browser you cannot scroll in responsive view

**To Reproduce**
1. Go to http://4240-beta0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-workspaces.html
2. Click on `Show Contextual Action Panel` button
3. Do resize Browser to smaller screen size Until Panel becomes full screen

**Expected behavior**
header should be fixed and in front of text

**Version**
4.24 beta 0 

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/71062788-55715580-21a6-11ea-80ef-fcf72b8be647.png)

**Platform**
IE 11

**Additional context**
In EDGE browser, you cannot scroll through the panel in responsive view

**Comment by tmcconechy** [comment]
Making this a minor layout issue because it was in previous versions and IE may be finished for support soon.

**Comment by tmcconechy** [comment]
Descoping this issue now see #3756
