### ISSUE TITLE
Datepicker: Double click does not enforce Range - Min (N) Days

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3268]
**Describe the bug**
user is able to input a single day on datepicker with range Min 5 days

**To Reproduce**
1. Go to http://4240-beta0-enterprise.demo.design.infor.com/components/datepicker/example-range.html
2. Click on `datepicker` with _Range - Min (5) Days_
3. Select a date and double click it 

**Expected behavior**
should only accept minimum required value

**Version**
4.24 beta 0

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/71069238-4218b700-21b3-11ea-94cf-d8c5e2a88428.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Not that if you single click the date and then press apply it is working as expected. Just need to extend this to double click somehow.... Minor

**Comment by jbrcna** [comment]
QA FAILED - The calendar functionality works fine however when I used the textbox and typed in the dates I was able to input a range of fewer than 5 days. see screenshot
v4.26.0-rc0
https://4260-rc0-enterprise.demo.design.infor.com/components/datepicker/example-range.html
![image](https://user-images.githubusercontent.com/56722184/75760511-5c097500-5d72-11ea-97bc-1119e28d10e8.png)

**Comment by tmcconechy** [comment]
@deep7102 if you fix this you can just fix on master as it's not critical enough to make a new build for.
