### ISSUE TITLE
Datagrid Treegrid: Expand row does not display children nodes

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#3274]
**Describe the bug**
In a treegrid, expand row does not display the children nodes under specific conditions. Say you clicked on '+' to expand and execute a http call to fetch the children nodes, the promise that fires the 'expandrow' event in toggleChildren is resolved prematurely and the flags are toggled before the data retrieval is complete. In this case, the new children nodes are not displayed under the parent row.

**To Reproduce**
Update enterprise-ng demo project and use the attached files, datagrid-treegrid-service.demo.ts and datagrid-treegrid.demo.ts
1. Go to enterprise-ng demo for datagrid-treegrid.
2. Collapse child 1 (row identifier 2)
3. Collapse child 2 (row identifier 5)
4. Expand child2 (row identifier 5). 
5. The children of row id 5 will flash by, but not display.

**Expected behavior**
The children nodes are retrieved and displayed for a parent.

**Version**

- ids-enterprise: v4.25.0-dev

**Platform**
  - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by aaralikar** [comment]
![TreegridExpand2](https://user-images.githubusercontent.com/22720894/71124701-0b3ea300-21ab-11ea-9ece-5a95a51b0249.gif)

**Comment by aaralikar** [comment]
[datagrid-treegrid.demo.txt](https://github.com/infor-design/enterprise/files/3980612/datagrid-treegrid.demo.txt)
[datagrid-treegrid-service.demo.txt](https://github.com/infor-design/enterprise/files/3980613/datagrid-treegrid-service.demo.txt)

Changed the .ts extension to .txt to upload.

**Comment by aaralikar** [comment]
In datagrid-treegrid-service.demo.txt, simplified the dataset to include minimum nodes to reproduce the issue.

```
  public getData(): any[] {
    if (!this._data) {
      /* tslint:disable */
      this._data = [
        {id: 1, escalated: 0, depth: 1, expanded: true, taskName: 'Follow up action with Residental Shipping Logistics ', desc: 'Contact sales representative.', comments: 2, time: '7:04 AM', children: [
            {id: 2, escalated: 0, depth: 2, expanded: true, taskName: 'Follow up action with Universal Shipping Logistics Customers', desc: 'Contact sales representative.', comments: 2, time: '14:10 PM', children: [
                {id: 3, escalated: 0, depth: 3, taskName: 'More Contact', desc: 'Contact sales representative.', comments: 2, time: '14:10 PM'},
                {id: 4, escalated: 0, depth: 3, taskName: 'More Follow up', desc: 'Contact sales representative.', comments: 2, time: '7:04 AM'},
              ]},
            {id: 5, escalated: 0, depth: 2, expanded: true, taskName: 'Follow up action with Acme Universal Logistics Customers', desc: 'Contact sales representative.', comments: 2, time: '7:04 AM', children: [
                {id: 6, escalated: 0, depth: 3, taskName: 'More Contact', desc: 'Contact sales representative.', comments: 2, time: '14:10 PM'},
                {id: 7, escalated: 0, depth: 3, taskName: 'More Follow up', desc: 'Contact sales representative.', comments: 2, time: '7:04 AM'},
              ]
            },
          ]
        }
      ];
```

**Comment by aaralikar** [comment]
In datagrid-treegrid.demo.ts, added a setTimeout to mimic http call and change in the dataset.
```
 onExpandRow(e: SohoDataGridToggleRowEvent) {
    const descr = e.rowData.taskName;
    const event = { event: 'expandrow', descr: descr, date: new Date() };
    console.log(event);
    this.events.push({ name: 'expandrow', descr: descr, date: new Date() });
    setTimeout(() => {
      const data: Array<any> = this.dataGrid.dataset;
      this.dataGrid.dataset = [].concat(data);
    });
  }
```

**Comment by jbrcna** [comment]
The issue is now resolved. verified in v4.27.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-lazy-loading-api.html
The children nodes are retrieved and displayed for a parent with some delay
