### ISSUE TITLE
Datagrid select all checkbox is not working as expected after changing records per page

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3275]
**Describe the bug**
Datagrid select all checkbox is not working as expected after changing records per page

**To Reproduce**
1. Go to http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html?theme=uplift&variant=light
2. Click Select all checkbox
3. Change the Record per page to 10 Records per page
4. Notice that the select all checkbox got unchecked 
5. Bring back to 5 Records per page
6. Notice that the select all checkbox is still unchecked 

**Expected behavior**
After selecting select all records. all records should be selected even on the next page. 

**Version**
Beta 4.24

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/71152709-1f010c80-2272-11ea-91b5-2196240eb96c.png)

**Platform**
All platform

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Dulplicate of #3269
