### ISSUE TITLE
Multiselect: placeholder text color is too dark

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3276]
**Describe the bug**
Multiselect placeholder with `Vibrant` theme and `High Contrast` variant is too dark almost to like a normal text 

**To Reproduce**
1. Go to http://4240-beta0-enterprise.demo.design.infor.com/components/multiselect/example-placeholder.html?theme=soho&variant=contrast
2. See error
3. Notice that the placeholder is too dark for high contrast with vibrant theme

**Expected behavior**
a placeholder should not look like a normal text. see screenshot
![image](https://user-images.githubusercontent.com/56722184/71161401-3ba64000-2284-11ea-861b-b2fd3e812f04.png)

**Version**
4.24 beta 0

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/71161266-07328400-2284-11ea-93b3-22a38cedb9e6.png)

**Platform**
All browser and devices

**Additional context**

**Comment by tmcconechy** [comment]
It is dimmer but going to bring it down one color.
![Screen Shot 2019-12-19 at 9 05 14 AM](https://user-images.githubusercontent.com/814283/71179704-b2b8e580-223e-11ea-8b09-f2b0bcc1f80d.png)

**Comment by jbrcna** [comment]
The issue still persists. will move to Failed column
![image](https://user-images.githubusercontent.com/56722184/72497064-8062ce00-3866-11ea-9a3a-27bb026b53a1.png)

**Comment by tmcconechy** [comment]
Can you elaborate? And Retest?

Not sure what your seeing there maybe wrong url? @jbrcna when i go to https://4250-beta0-enterprise.demo.design.infor.com//components/multiselect/example-placeholder.html?theme=soho&variant=contrast i see this:

![Screen Shot 2020-01-17 at 7 47 20 AM](https://user-images.githubusercontent.com/814283/72613485-a0919c00-38fd-11ea-9553-b161926a965a.png)

**Comment by jbrcna** [comment]
Switch to `Vibrant` then choose `High` contrast

<img width="830" alt="image" src="https://user-images.githubusercontent.com/56722184/72720596-4cb0dc80-3bb5-11ea-942d-9bb6bfea3959.png">
screenshot in `Safari` browser

**Comment by jbrcna** [comment]
also, notice that the placeholder is not centered. will move this ticket to Failed column

**Comment by EdwardCoyle** [comment]
@tmcconechy maybe wait for #3346 to merge before rechecking this.

**Comment by tmcconechy** [comment]
@EdwardCoyle i still see this one with the steps of changing theme as @jbrcna noted

**Comment by jbrcna** [comment]
yeah my bad. Although `Vibrant` theme and `High Contrast` variant were indicated in '_Describe a bug_', the Link provided in _'Steps to reproduce'_ was incorrect. it should be `theme=uplift` and not `theme=soho`

**Comment by tmcconechy** [comment]
Issue appears to be fixed as far as i can tell. If any further issues please raise a new bug

**Comment by jbrcna** [comment]
The issues mentioned above were now resolved. Moving this ticket to Done column
Verified in https://4250-rc0-enterprise.demo.design.infor.com//components/multiselect/example-placeholder.html?theme=uplift&variant=contrast
<img width="563" alt="image" src="https://user-images.githubusercontent.com/56722184/72960199-dd6efe80-3de7-11ea-9792-3278b8effdbe.png">
