### ISSUE TITLE
Lookup: Layout issue in min width

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3277]
**Describe the bug**
Lookup: Layout issue in min width.

**To Reproduce**
1. Go to http://4240-beta0-enterprise.demo.design.infor.com/components/lookup/example-minwidth.html
2. Open lookup in Paging Small field
3. See issue: list only fills half of the modal
4. Click Cancel button
5. Open lookup in Paging Small(minWidth=640) field
6. See issue: list only fills half of the modal

**Expected behavior**
List should have correct width 

**Version**
- ids-enterprise: v4.24.0-beta0

**Screenshots**
Paging Small lookup
![image](https://user-images.githubusercontent.com/39508864/71164154-6d6dd580-2289-11ea-8c82-5131388279e3.png)

Paging Small(minWidth=640) lookup
![image](https://user-images.githubusercontent.com/39508864/71164205-86768680-2289-11ea-865d-1e3c88691ce8.png)

**Platform**
 - All OS, devices and browsers.

**Additional context**
N/A

**Comment by brianjuan** [comment]
List width is now filling the modal, but I just found a minor issue on smaller browser size, the list is cropped.
http://4240-rc0-enterprise.demo.design.infor.com/components/lookup/example-minwidth.html
![image](https://user-images.githubusercontent.com/39508864/71249110-7036fc00-2357-11ea-9374-4937ee3b92f5.png)

**Comment by tmcconechy** [comment]
It was like this before. The grid will not resize in this context. Not worth fixing or spending time on so moving to done.
