### ISSUE TITLE
[Mobile] Searchfield Control: Excess border appears around the search field when focused

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#328]
**Describe the bug**
Excess border around the search field is appearing when search field is on focus.
"x" icon also appears on the rightmost part of the excess border.

**To Reproduce**
1. Open Chrome on Galaxy S9 or iPhone X using browserstack 
1. Go to http://480-rc0-sohoxi.demo.design.infor.com/components/searchfield/example-index.html
2. Click on the Search field
3. Notice the excess border on the rightmost part of the field
4. Type "test" on the search field, "x" icon will appear at the excess border
5. Remove the focus on the search field, notice the "x" icon will stay outside the search field

**Expected behavior**
No excess border should appear on the search field and "x" icon should appear inside the search field.

**Screenshots**
<img width="494" alt="screen shot 2018-07-09 at 4 04 42 pm" src="https://user-images.githubusercontent.com/39508864/42438189-daede7b4-8391-11e8-85c9-b5fed75ceb0e.png">

**Platform**
 - Samsung Galaxy S9+ and S8, iPhone X, iPhone 8
 - Browsers: Chrome, Safari, Firefox

**Additional context**
No additional context.

**Comment by tmcastro** [comment]
![soho-318](https://user-images.githubusercontent.com/39041951/46335034-cd626700-c658-11e8-8317-8c1a23a1ee28.png)

Seems to be working fine now. This must've been fixed on another ticket.

**Comment by tmcconechy** [comment]
OK, Its very possibly it was just fixed then. Closing...
