### ISSUE TITLE
Init toolbar() removes previously initialized tooltips

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#3283]
**Describe the bug**
I have few button elements inside a toolbar element. These buttons I have tooltips on them.
So If I do `button.tooltip(...)` for each elements, then these buttons have tooltip on them.

If I now do toolbarElement.toolbar(). Then the previous tooltips are all gone.

I cannot reproduce this on the latest version. So I'm wondering if it was bug which has been fixed?
If so in which version was it fixed and with which commits? 

**To Reproduce**
Read descriptions

**Version**
4.20.2

**Comment by tmcconechy** [comment]
I'm really not sure. I don't recall any fix to this. But must be one of these commits: https://github.com/infor-design/enterprise/commits/master/src/components/tooltip/tooltip.js

So it works on 4.23.0 ...?

**Comment by tmcconechy** [comment]
Support question answered (sort of). Any more questions on this let me know.
