### ISSUE TITLE
App Menu / Accordion: clearing a filter doesn't always expand child elements

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#3285]
**Describe the bug**
A handful of issues have uncovered that the filtering in Application Menu Accordions isn't working well:

- https://github.com/infor-design/enterprise/issues/2925#issuecomment-567896112
- https://github.com/infor-design/enterprise/issues/2925#issuecomment-567898701

The major problem is that `expand/collapse` isn't fully adding/removing rules that correctly handle the submenus, respectively.

**To Reproduce**
1. Go to http://4240-rc0-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm.html?theme=uplift&variant=light
2. Use the search box to filter for a sub item, such as "3rd Level Menu Item"
3. Notice that the matching accordion headers will show the top-level item that contains the correct filter result, but not the child that should actually be the result.

**Expected behavior**
When filtering happens, expand/collapse needs to happen at the correct times to display the filtered results.

**Version**
Discovered in v4.24.0-beta0

**Screenshots**
![](https://user-images.githubusercontent.com/56722184/71241226-124de880-2346-11ea-8bfc-01da968b94ed.png)

**Platform**
- n/a

**Comment by tmcconechy** [comment]
@jbrcna after recent fixes i do not think i can reproduce any of this. Can you retest this and if further issues lets make an new issue for them.

**Comment by jbrcna** [comment]
@tmcconechy I could still be able to replicate the issue. please see screenshot
https://4250-beta0-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm.html?theme=uplift&variant=light
browser: Firefox
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/56722184/72864755-218ed000-3d10-11ea-97a9-fe2450d2044c.png">

**Comment by tmcconechy** [comment]
@jbrcna you want be able to test this until the 425-rc is deployed.
