### ISSUE TITLE
Editor: Increase paragraph top padding and adjust header styles

### ISSUE THREAD

**Issue by kentonquatman** [infor-design/enterprise#3288]
## Describe the bug
Paragraph spacing seems to disappear when multiple styles are introduced
1. Go to http://localhost:4000/components/editor/example-index.html
2. Add a couple headings on the page
3. Add a paragraph below the heading
4. The paragraph spacing seems to disappear

## Expected behavior
All text should have some spacing between block level elements.

## Screenshots

Only using paragraph styles
![Screen Shot 2019-12-23 at 11 22 34 AM](https://user-images.githubusercontent.com/847306/71369426-c1720600-2578-11ea-94aa-852e2c287ad1.png)

Adding heading styles
![Screen Shot 2019-12-23 at 11 23 06 AM](https://user-images.githubusercontent.com/847306/71369460-d9e22080-2578-11ea-8ec0-61dd19a7c4db.png)

Paragraph spacing disappears below heading
![Screen Shot 2019-12-23 at 11 25 01 AM](https://user-images.githubusercontent.com/847306/71369476-e1a1c500-2578-11ea-8d8b-70f6007f7562.png)

## Platform
 - Macbook Pro
 - macOS 10.14.6 (Mojave)
 - Chrome v79.0.3945.88

## Additional context
I also think that "Heading 1" and "Heading 2" are too close in size. We should either make Heading 1 larger or Heading 2 smaller.

**Comment by tmcconechy** [comment]
@kentonquatman What do you suggest for font size and padding for heading 1-6? (In both themes).

I do agree that the header styles need adjusting as i saw that, but did not notice the padding issue (agree with that as well)

**Comment by kentonquatman** [comment]
@tmcconechy Do we know that we need to support six heading sizes in the rich text editor? The typographic scale in IDS only has four sizes at the moment ([Dropbox file](https://www.dropbox.com/work/Design%20System/Typography?preview=IDS_Typography_20191001.html)).

The previous version editor only had two size options, so I mocked up a version using 28px and 20px for headings one and two ([View on Figma](https://www.figma.com/file/8ekRxSWEbFxDzmvzraB1LH/Rich-Text-Editor?node-id=0%3A1)).

If we want to have more heading options, we could just use the four from IDS (32, 28, 24, 20).

I set the margins equal to the line-height so that we could maintain the vertical rhythm as best we can. So for the 28px heading, it should have a line height of 36px and margins of 36px.

_**Note:** the mock-up includes an update to the editor toolbar. I'll bring that up in a separate issue, we'll just use this to look at type sizes and spacing._

**Comment by tmcconechy** [comment]
Yes, it does support six but i dont think that many people would use all of them. My idea i had discussed with @EdwardCoyle was to just use a subset of the sizes you made in the "new font sizes". The suggested dropbox link looks better as than we worked up on http://master-enterprise.demo.design.infor.com/components/editor/example-complex-fontpicker.html?theme=uplift&variant=light

As i feel the upper headings are too big.  If we use  (32, 28, 24, 20) can we get two more size in there someplace? Maybe a 30 ? 26 or 16?

**Comment by kentonquatman** [comment]
I don't want to introduce any one-off sizes, but we could use 16px for both headings five and six. One could be semibold and the other could be italic (I know that's how Google Docs handles it).

Are these sizes configurable in the component? I'd rather keep the options simple, only including sizes 1-3 by default, and allow product teams to turn on sizes 4-6 if they have a use case for them.

**Comment by tmcconechy** [comment]
Ok that works (using 16px in semi bold and italic). Yes, it is configurable which sizes you want to show in the dropdown (but the actually css values we use are not). Default is h1 and h2.

**Comment by jbrcna** [comment]
**Test Passed**
v4.27.0-dev
moving this ticket to Done column
https://master-enterprise.demo.design.infor.com/components/components/editor/example-dirty-tracking.html
