### ISSUE TITLE
Console error in Windows IE

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3289]
**Describe the bug**
All of the pages have console error in Windows IE.

**To Reproduce**
1. Open IE browser then open console
2. Go to http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html or http://master-enterprise.demo.design.infor.com/
3. There is a "_Object doesn't support property or method 'includes'_" console error
4. Some example pages like in Datagrid and Locale components are not even loading the content

**Expected behavior**
There should be no console error in Windows IE

**Version**
- ids-enterprise: 4.25.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/71510348-90bc0480-28c9-11ea-8830-6e03340df1df.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: IE 11

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Up for grabs, until im back. I think i added an includes that should be refactored to something IE 11 safe.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
