### ISSUE TITLE
Searchfield: User can select "No Results" and "All Results" placeholders

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#329]
**Describe the bug**
User can select "No Results" and "All Results" placeholders.

**To Reproduce**
1. Open Chrome/Safari on Galaxy S9 or iPhone X using browserstack
2. Go to http://480-rc0-sohoxi.demo.design.infor.com/components/searchfield/example-clearable.html
3. Type "test" in the search field
4. Click "No Results", "No Results" will be selected and will be the value of the search field
5. Clear the value of the search field then type "al"
6. Click "All Results For "al", "All Results For "al" will be selected and will be the value of the search field

**Expected behavior**
"No Results" and "All Results" placeholders should not be selectable

**Screenshots**
No screenshot applicable

**Platform**
 - Samsung Galaxy S9+ and S8, iPhone X, iPhone 8
 - Browsers: Chrome, Safari, Firefox

**Additional context**
No additional context.

**Comment by brianjuan** [comment]
http://localhost:4000/components/searchfield/example-clearable.html
I can still select "No Results" using keyboard.
1. Type "test" in the searchfield
2. Press Arrow Down then press Enter, "No Results" message will be selected.

**Comment by tmcastro** [comment]
Alright, will work on this. Thanks!

**Comment by brianjuan** [comment]
http://localhost:4000/components/searchfield/example-clearable.html
Passed QA testing, fix is not yet reflected on https://4130-beta0-enterprise.demo.design.infor.com/components/searchfield/example-clearable.html though, but I will still move this to Done.

**Comment by brianjuan** [comment]
@tmcconechy The fix for Arrow Down/Up issue is not yet reflected on https://4130-rc0-enterprise.demo.design.infor.com/components/searchfield/example-clearable.html

**Comment by tmcconechy** [comment]
@brianjuan this fix was merged in master by mistake. https://master-enterprise.demo.design.infor.com/components/searchfield/example-clearable.html i guess thats fine as this is minor so you can verify it there. But it didnt get in 4.13 (for 4.14)
