### ISSUE TITLE
Datepicker: tooltip is not properly aligned in mobile view and/or responsive view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3294]
**Describe the bug**
The tooltip of datepicker is not properly aligned

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datepicker/example-sizes.html
2. Resize the browser to 320 x 568 or open in mobile
3. Click the calendar icon of `Extra Small` and `Small` datepickers

**Expected behavior**
tooltip should be properly aligned

**Version**
4.25.0-dev

**Screenshots**
![Large GIF (522x682)](https://user-images.githubusercontent.com/56722184/71806602-2878da00-30a4-11ea-918e-740795e9c0df.gif)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
The layout of the dialog cannot always fit in every scenario so for some cases it may move such that the arrow is not in alignment in favor of the dialog being visible.

Will not fix this issue at this time.

**Comment by jbrcna** [comment]
will take note of this
