### ISSUE TITLE
Locale: Incorrect font style in Chinese

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3295]
**Describe the bug**
Locale: Incorrect font style in Chinese.

**To Reproduce**
1. Open Mac Safari or Windows Chrome
2. Go to http://master-enterprise.demo.design.infor.com/?locale=zh-CN 
3. Notice that all font styles are incorrect
4. Happens on all pages using locale=zh-CN

**Expected behavior**
Font style should be correct.

**Version**
- ids-enterprise: v4.19.0 to v4.25.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/71811206-13557880-30af-11ea-9c52-61fb7c849289.png)

**Platform**
 - OS: Mac and Windows
 - Browser Name: Mac Safari, All Windows browsers

**Additional context**
N/A

**Comment by tmcconechy** [comment]
This is not a bug, by design we change the fonts for some languages. As normally the character set will be different and the default English font doesnt show well (this is for most asian languages)

**Comment by brianjuan** [comment]
Thanks for the clarification @tmcconechy .
