### ISSUE TITLE
Search Field: Add setting to customize how large a collapsed search field can be

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3296]
**Is your feature request related to a problem? Please describe.**
Currently, a collapsed search field on a flex toolbar has a max size of 100px. This is to make a collapsed search field take up the same amount of space as a text button.

**Describe the solution you'd like**
 We would like a setting to configure this, so implementers can determine a reasonable size for their application.

**Additional context**
![image](https://user-images.githubusercontent.com/22107636/71832969-9fe14600-3071-11ea-898f-47050208a01e.png)

**Comment by Sovia** [comment]
This was discovered with the fix for #2944 , and it would be nice if this new setting could get exposed in the ng controls as well.

**Comment by EdwardCoyle** [comment]
@Sovia I raised infor-design/enterprise-ng#719 for the NG work on this issue

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in http://master-enterprise.demo.design.infor.com/components/searchfield/test-configure-close-size.html. Will retest once beta is deployed.
