### ISSUE TITLE
Datagrid - Summary Row is hidden on initial render

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#330]
**Describe the bug**
The Datagrid Summary Row is hidden on the initial load of the control.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/test-summary-row-pager.html
2. The Datagrid should have a Summary Row upon load.
3. Click on the Next Page.
4. The Summary Row will now be rendered.

**Expected behavior**
Summary Row should be rendered upon initial load of the Datagrid.

**Screenshots**
Initial Load:
![image](https://user-images.githubusercontent.com/41028784/42482377-58b6971a-8426-11e8-8961-36472ca11679.png)
Click on Next Page:
![image](https://user-images.githubusercontent.com/41028784/42482394-65bd3a90-8426-11e8-9b91-cf48541e65e4.png)

**Platform**
 - Windows 10
 - Browser: Google Chrome

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/test-summary-row-pager.html
http://localhost:4000/components/datagrid/test-summary-row-pager.html
Passed QA testing on all browsers, Summary row is now being loaded on initial render.
