### ISSUE TITLE
Datagrid: Missing stretchcolumn when re-rendering

### ISSUE THREAD

**Issue by rowelineeveresurreccion** [infor-design/enterprise#3301]
**Describe the bug**
We found some columns are not showing/displaying in the View/UI in the latest IDS version.  In our app.

**Investigation**

Columns should be between these 2 column, but it is not appearing. 

![image](https://user-images.githubusercontent.com/50350478/71876082-d4d6c100-3175-11ea-9444-b0252f24bb5d.png)

- Verify Hidden set to ‘False’

![image](https://user-images.githubusercontent.com/50350478/71876127-f8017080-3175-11ea-9f7a-9cb68be490a6.png)

- Verify column name lapv1490_schedules has values, the plannum has value on it. 
![image](https://user-images.githubusercontent.com/50350478/71876147-0780b980-3176-11ea-8913-d69a9e19ea11.png)

**Steps to reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/test-horizontal-scroll.html
2. Type the following in the console
```
var datagrid = $('#datagrid').data('datagrid')
datagrid.settings.stretchColumn = "productName"
datagrid.render()
```
3. Notice productName is invisible.

**Expected behavior**
Available columns should be displayed in the UI.

**Platform**
- Chrome Version 79.0.3945.88 (Official Build) (64-bit)
-data-sohoxi-version="4.25.0-dev"

**Comment by tmcconechy** [comment]
A similar issue should be fixed in 4.25-dev already. There was an issue with hidden columns in that the columns might be set to width zero. I'm not 100% sure why you should still have an issue.

But there is no way to reproduce and test this issue given the steps. Can you upload a runnable example we can drop into the demo app and see the issue?

**Comment by rowelineeveresurreccion** [comment]
Hi @tmcconechy will verify it again and give you the details. Once done will get back to you. Thank you.

**Comment by rowelineeveresurreccion** [comment]
Hi @tmcconechy please see details below: 

Upon further investigation we found that issue is that the column “plannum” was caused by the generated width is “max-width:99%” as suppose to the “numeric px” width. We checked on the Soho.js and found this line which the column “plannum”’s condition fits. 

For some reason the column “plannum” is included in the Settings.stretchColumn as shown on the soho.js script here:

![plannum](https://user-images.githubusercontent.com/50350478/72129162-33de4500-33c5-11ea-9404-8bf5bbec7c1d.png)




We tried to replicate on http://master-enterprise.demo.design.infor.com/components/datagrid/test-horizontal-scroll.html

Code used on the image: 
var datagrid = $('#datagrid').data('datagrid')
datagrid.settings.stretchColumn = "productName"
datagrid.render()

![missing column](https://user-images.githubusercontent.com/50350478/72128795-f3ca9280-33c3-11ea-9f4a-bb2f70c12f87.gif)

**Comment by tmcconechy** [comment]
Ok got it. Updating the steps to make it more clear.

**Comment by tmcconechy** [comment]
Its possible that this PR may fix it https://github.com/infor-design/enterprise/issues/3308 but will retest after this is added.

**Comment by tmcconechy** [comment]
I tested this PR and it does in fact fix this issue
