### ISSUE TITLE
Tabs: No toast displayed in Mobile or Responsive view after URL change

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3303]
**Describe the bug**
Tabs: No toast displayed in Mobile or Responsive view after URL change

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/tabs/example-url-hash-change.html?theme=uplift&variant=light#tab-number-four
2. Minimize the screen to responsive / mobile view 
3. Click dropdown and select a Tab

**Expected behavior**
A toasts will appear after changing URL 

**Version**
4.31 BETA IDS ENTERPRISE 

**Screenshots**
N/A

**Platform**
All browser, os and mobile devices. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Im not going to worry about this. It seems the demo app is only doing the url-has change when clicking a tab not on the dropdown menu. This is as expected and its a specific case. The toast is just there arbitrarily. So not really anything worth spending time on here or anything wrong.

Only clicking the tab will show the toast and thats just fine.
