### ISSUE TITLE
Datagrid: Stretch column can have a width smaller than expected due to width set at 99%

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#3308]
**Describe the bug**
The stretch column can become unusable on smaller devices, or if there are a large number of columns.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/test-columns-stretch-column.html'
2. Reduce the width of the browser, until you can no longer see the complete column

**Expected behavior**
The stretch column will only expand to fill the remaining space in the datagrid, but then also maintain its minimal width, so that the column is usable. The minimal width should be applied using the calculated width for the column.

**Version**
Master

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/72107704-cd840300-3381-11ea-9a6c-d2c479b9a32b.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome

**Comment by janahintal** [comment]
Failed in Windows 10 IE11, the datagrid is not loading in IE11 for http://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html?theme=soho&variant=dark

**Comment by tmcconechy** [comment]
@janahintal this was fixed in the 4.25 branch. I synced everything up and all the datagrid pages are now loading again in IE 11

**Comment by marknolaninfor** [comment]
@tmcconechy,

I can not see this in 4.25, as you should see this.stretchColumnDiff in the datagrid.js file. Can this be put into 4.25.x?

**Comment by tmcconechy** [comment]
@marknolaninfor i fixed the js error in in 4.25.1 this wasn’t directly this issue it was found by qa while testing this out. So we should be good n 4.25.1 or master?

**Comment by janahintal** [comment]
This issue is now resolved in http://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html?theme=soho&variant=dark. Thanks guys.

**Comment by marknolaninfor** [comment]
If you run the latest version 4.25.x 

1. https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-columns-stretch-column.html
2. Reduce the width of the browser, until you can no longer see the complete column

The same behaviour is found.

The master version 4.26.x works fine.

**Comment by tmcconechy** [comment]
The fix i believe ended in master 42.6 after all because of the timing of the merges ect.
