### ISSUE TITLE
Datagrid: Error converting circular structure to JSON

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3309]
Describe the bug
If you include a lookup filter and decide to use saveUserSettings. The grid will error when restoring or resetting columns.

To Reproduce
1. Go to http://localhost:4000/components/datagrid/test-save-settings.html#
2. Resize a column
3. Reload Page
4. Click on Reset to Default in the .. menu
See error in the debugger

Expected behavior
No errors

Version
4.25.0-dev

Additional context
Related to https://github.com/infor-design/enterprise/issues/2279

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/72109686-ff528680-32fb-11ea-8e21-4a7090b31622.png)

**Comment by claudenbach** [comment]
![Git-3309](https://user-images.githubusercontent.com/39804038/72110224-468d4700-32fd-11ea-81d6-b0e1fedbbe46.gif)

**Comment by tmcconechy** [comment]
I had this problem in the past on some of the lookup filter examples - its due to the JSON structure attached. I'll look for a fix.

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. 
Thanks. 
Tested in http://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html?theme=uplift&variant=light across all browsers.
