### ISSUE TITLE
[Mobile] Modal: Pressing Enter Key on the input field closes the modal  

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#331]
**Describe the bug**
Pressing Enter Key on the input field closes the modal.

**To Reproduce**
1. Open Chrome/Safari on Galaxy S9 or iPhone X using browserstack
2. Go to http://480-rc0-sohoxi.demo.design.infor.com/components/modal/example-index.html
3. Type "test" in the input field
4. Press Enter Key or Click Return/Go Key, Modal will close

**Expected behavior**
Modal should not close when Enter key is press in the input field.

**Screenshots**
No applicable screenshot.

**Platform**
 - Samsung Galaxy S9+ and S8, iPhone X, iPhone 8
 - Browsers: Chrome, Safari, Firefox

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Im not sure about this one, what do you think @EdwardCoyle ? I think the enter key was supposed to close the dialog and work like pressing the apply.

**Comment by EdwardCoyle** [comment]
<img width="776" alt="screen shot 2018-08-03 at 9 22 37 am" src="https://user-images.githubusercontent.com/3249601/43645073-d62fb83a-96fe-11e8-8837-c04dbe8f1d05.png">

I think it's exactly that, but the `enter` keypress is bubbling up to the modal and not being cancelled by the input field... not sure if it should be.  If the submit or cancel buttons aren't focused, should we be closing the modal on an enter key?

**Comment by tmcconechy** [comment]
Yes, i think so, the idea is that you are "submitting" the form / modal. We do have some fields like textarea, editor where we ignore that.

But i guess they can always tab to the buttons. We could see if we get many comments about it

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/modal/example-index.html
Passed QA testing, bug fix is working across all browsers.
