### ISSUE TITLE
Datagrid: Column containing a dropdown unable to select a blank item

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3313]
Describe the bug
A column has a dropdown whose item options contain a blank item.  When selecting the blank item, the cell reverts to the existing value. 

To Reproduce
1. Using the attached example-editable.html
2. Click on an Action cell  
3. From the dropdown options, select the blank (or first) item
4. Notice that the value is not changed, maintains the original value

Expected behavior
Select a blank item (in order to clear the selection)

Version
v4.25.0-dev

**Comment by claudenbach** [comment]
[Git-3313.zip](https://github.com/infor-design/enterprise/files/4046800/Git-3313.zip)

**Comment by claudenbach** [comment]
Also noticed if a dropdown options is {(label: ' ', value: '')}, this option doesn't appear when the dropdown list is opened.

**Comment by claudenbach** [comment]
Similar behavior in Chrome and IE11.

**Comment by marknolaninfor** [comment]
The change in  #3137 caused this issue.

{code}
      if (!val && this.input.find('option[selected]').length > 0) {
        val = this.input.find('option[selected]').attr('value');
      }
{code}

when val is any of the falsy values, https://developer.mozilla.org/en-US/docs/Glossary/Falsy , the dropdown input will return an incorrect value. The fix should be reversed as it breaks more than it fixes. 

I was not able to replicate the original issue in IE 11, so I could not find an alternative.

**Comment by tmcconechy** [comment]
Moved this fix up to 4.25

**Comment by janahintal** [comment]
Failed upon testing in Windows 10 IE 11. The datagrid itself did not load. Please see image below. 
![image](https://user-images.githubusercontent.com/45757016/73354200-1586ad80-42d0-11ea-8510-45a0f29ca51a.png)

**Comment by janahintal** [comment]
Verified in http://4251-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html?theme=soho&variant=dark
