### ISSUE TITLE
Tabs - Unwanted lines appear under the Tabs in Vibrant Theme, Dark Variant

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3317]
**Describe the bug**
Tabs - Unwanted lines appear under the Tabs in Vibrant Theme Dark Variant

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/tabs-module/example-add-tab-button.html?theme=uplift&variant=light#module-tabs-controls
2.In the new tab Builder, Create several New Tabs until the Dropdown the Dropdown Tab Filter appear
3. Switch Tab 
4. Notice the line below the Tab

**Expected behavior**

**Version**
beta 4.31 ids enterprise

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/72244287-e8c46c00-3628-11ea-8882-b6b5328d80e6.png)

**Platform**
All Browser OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Though not 100% a duplicate im going to consolidate this issue with https://github.com/infor-design/enterprise/issues/3312 as this all needs to be fixed together.
