### ISSUE TITLE
Validation: removeError() no longer removing error class if no error-message set on field

### ISSUE THREAD

**Issue by danders1717** [infor-design/enterprise#3318]
**Describe the bug**
The deprecated removeError function that was replaced with removeMessage is no longer removing the error class if the field in error does not have an error-message attached to it such as Required.

**To Reproduce**
1. Add a field on the with the "error" class so shows in red.
2. From console run $("#fieldname").removeMessage() or $("#fieldname").removeError()
3. Error class is no longer removed from the field like it did with old removeError function

**Expected behavior**
expect calling removeError() or removeMessage() to always remove the error class regardless of if it has "error-message" class set for it.

**Version**
4.22.0 or 4.24.0

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
