### ISSUE TITLE
Calendar-weekview: Date selection does not persist when switching from month view to week view to day view

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#3319]
**Describe the bug**
Calendar weekview seems to reset the month view date selection to the first day of the week.

**To Reproduce**
1. Go to http://localhost:4000/components/calendar/test-ajax-events.html
2. Click on a date other than today's date, such as: August 15th, 2018.
3. Click on view changer and switch to week view, then click on view changer and switch to day view.
4. Noticed the day showing on day view is Sunday, August 12th 2018.

**Expected behavior**
Day view should show August 15th, 2018 persisted from the day selection on month view.

**Version**

- ids-enterprise: v4.25.0-dev

**Screenshots**
![Day selection issue](https://user-images.githubusercontent.com/39130590/72276290-345d2280-35f5-11ea-9159-a6e1d8d63cca.gif)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 79.0.3945.117 (Official Build) (64-bit)

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in https://master-enterprise.demo.design.infor.com/components/calendar/test-ajax-events.html. Will retest once beta is deployed.
