### ISSUE TITLE
Validation is Attaching Submit Handlers unnessarily

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#332]
**Describe the bug**
The validation code is adding an event handler that blocks form submission.

**To Reproduce**
1. Go to https://ustawvqa1.infor.com/efinancials
2. Select batches from the menu
3. Click add
4. Fill in required values and submit

**Expected behavior**
Form should submit.

**Platform**
 - Chrome
 - App specific.

**Additional context**
Its getting into `if (this.element.is('form')) {` unnecessarily in validate.js
Secondarily we should add a line to not validate on `disabled input elements`.

This started in 4.8.0 and was made aware of on a chat with @pilotbob

**Comment by brianjuan** [comment]
This bug passed QA testing.
