### ISSUE TITLE
Radar Chart: Labels cut off In some screen sizes/shape

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#3320]
**Describe the bug**
Radar Chart labels cut off when chart area is at certain size/shapes. The examples of radar chart in components are done in a widget and in that case it seems to be fine.  

**To Reproduce**
1. grab this file [gapchart.zip](https://github.com/infor-design/enterprise/files/4055403/gapchart.zip)
2. Unzip and bring up example chart
3. Resize the screen in width and/or height and see that the top and bottom are at time clipped and other times the sides are  clipped. In some sized sceens it works properly

**Expected behavior**
For the chart to be able to fit in its area without clipping labels

**Version**

v4.25.0-dev

**Screenshots**
![Screenshot 2020-01-13 13 48 59](https://user-images.githubusercontent.com/19823048/72286972-d982f580-360b-11ea-9c61-8ff84b576027.png)
![Screenshot 2020-01-13 13 49 52](https://user-images.githubusercontent.com/19823048/72286976-dbe54f80-360b-11ea-9d3a-437f99d3e6c9.png)

**Platform**
Version 79.0.3945.117 (Official Build) (64-bit)

**Additional context**

**Comment by pwpatton** [comment]
Required by LMCLIENT-28963

https://jira.lawson.com/browse/LMCLIENT-28963
Competency and Skill Analysis Chart Image Is Too Big - Results in Cut Off Text

**Comment by pwpatton** [comment]
@tmcconechy  what version of ids will this make it into?

**Comment by tmcconechy** [comment]
4.26

**Comment by janahintal** [comment]
QA Passed. Thanks!
Verified in http://master-enterprise.demo.design.infor.com/components/radar/test-labels.html?theme=uplift&variant=light across all platform.

**Comment by CindyMercadoReyes** [comment]
Tested this ticket across browsers and devices and the issue is now resolved.  Moving this ticket to the Done column.
