### ISSUE TITLE
Datagrid: handle headerless tables

### ISSUE THREAD

**Issue by mbarb-infor** [infor-design/enterprise#3324]
System i Workspace Anywhere (SiWA) uses Infor Design System Datagrid to provide table handling.  Tables in SiWA can be defined with the number of column heading rows set to zero.  However, this does not appear to be handled by Datagrid, so an empty header row is always inserted.

The request is therefore to provide support for a header-less table.

**Comment by tmcconechy** [comment]
@mbarb-infor when making issues please use the issue template so we have all the needed information.
https://github.com/infor-design/enterprise/issues/new/choose

You can just edit this issue using the markdown of the templates and fill in the fields.
https://github.com/infor-design/enterprise/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

Im not 100% clear on what a headerless table means? Does it mean data in the settings.dataset but settings.columns = [] (an empty array?)

If so i recently made that work in 4.25. This will now produce this:

![Screen Shot 2020-01-14 at 9 34 12 AM](https://user-images.githubusercontent.com/814283/72352865-0c32f980-36b1-11ea-94ef-d554610f092b.png)

**Comment by mbarb-infor** [comment]
Hi Tim,

Apologies for not using the template.  As I normally use the Infor Enhancement Request System, I have not seen github before today, so I'm feeling my way.

I am not part of the team that develops the System i Workspace Anywhere (SiWA) product.  I simply use SiWA to design screens for end-user developments.

One of the SiWA features is to be able to design a table with the number of column heading rows set to zero.  Here is an example of where this was done:

![image](https://user-images.githubusercontent.com/59873525/72356448-32708d80-36e1-11ea-9ac3-21f5e001b158.png)

(I am seeing a file reference above, rather than the image itself, so I assume that is a quirk of github and that you can see it.)

Because there are four records per screen row, the column heading "ASN Numbers" needs to span all four columns, which SiWA does not handle.  This heading that you see is therefore specified externally from the table and the table is defined to have zero header rows.  As you can see, this results in an extra empty row being re-inserted back into the table which shouldn't be there.

Richard Sankey, the development lead on SiWA, told me that SiWA now uses Datagrid for table handling, and he didn't think that Datagrid could handle tables with no header, and that I should raise this Enhancement Request.

I suspect the answer to your question is option 2, but I think I am going to have to refer this issue to Richard as the technical side of how SiWA uses Datagrid is outside my knowledge.

Regards, Martin.

**Comment by tmcconechy** [comment]
Ok, Thanks. I think i get it. So you want to hide the black header row? I think i would suggest for this case you just add a css class and hide the header area.

Usually a table needs a header so you can tell what the column means and this goes against accessibility and usability guidelines so may not be something we want to encourage. Although in this case you have sort of a header that says ASN numbers. We did do an example something like this with group by. Perhaps it helps.

http://master-enterprise.demo.design.infor.com/components/datagrid/test-grouping-list.html

**Comment by tmcconechy** [comment]
Going to descope this for now. As this is fairly custom and goes against usability guidelines.
If you want to do this you can just hide the header in your css.
