### ISSUE TITLE
Forms: Implement optional smaller field sizes (Phase 2)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3329]
**Is your feature request related to a problem? Please describe.**
This issue continues on https://github.com/infor-design/enterprise/issues/3249

**Describe the solution you'd like**

**P1 and P2**
- [x]  P1 field filters (continue)
- [x]  P1 fieldset/expandable area http://master-enterprise.demo.design.infor.com/components/fieldset/example-index.html
- [x] P2 data labels on summary fields 

**Later**
- [x] P2  field Options
- [x]  switch
- [x]  editor
- [x]  rating
- [x]  slider
- [x] counts 
- [x] context forms
- [x] summary forms
- [x] Reduce bottom padding on context forms (Screen Shot 2 on https://github.com/infor-design/enterprise/issues/3249)
- [x] Reduce bottom padding between data labels on summary fields  (Screen Shot 3 on https://github.com/infor-design/enterprise/issues/3249)

**Describe alternatives you've considered**
N/A

**Additional context**
Everything on https://github.com/infor-design/enterprise/issues/3249

**Comment by kentonquatman** [comment]
I'll add specs for these elements to our Figma file.

**Comment by brianjuan** [comment]
Found some layout/alignment issues.

http://master-enterprise.demo.design.infor.com/components/field-options/example-index.html?theme=soho&variant=light
**All Browsers:**
![image](https://user-images.githubusercontent.com/39508864/74011832-bad20d80-49c3-11ea-89bd-6a97e4343320.png)
![image](https://user-images.githubusercontent.com/39508864/74012106-6f6c2f00-49c4-11ea-9d53-f1d0f9dcd783.png)

**Mac Safari:**
![image](https://user-images.githubusercontent.com/39508864/74018322-aa745f80-49d0-11ea-8336-2a9697bc97f6.png)

**Mac and Windows Firefox, Windows IE, Windows Edge:**
Field options are misaligned across all the fields in the entire page
![image](https://user-images.githubusercontent.com/39508864/74018592-29699800-49d1-11ea-828f-2c32699cf680.png)

Uplift
![image](https://user-images.githubusercontent.com/39508864/74019081-fb388800-49d1-11ea-8da8-38fe9df56829.png)

![image](https://user-images.githubusercontent.com/39508864/74019019-db08c900-49d1-11ea-91a9-676077a8c7c5.png)

**Comment by tmcconechy** [comment]
Made a PR to fix the failed issues. Any further issues please raise them on a new ticket for later please

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
