### ISSUE TITLE
Additional E2E Tests For Colorpicker

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#333]
**Is your feature request related to a problem? Please describe.**
The E2E Tests For Colorpicker needs additional test included for the example index page and the test modal page.

**Describe the solution you'd like**
For the Colorpicker example index page a script needs to be created capturing each field with "Tab" and"Enter" key being used to navigate through the page. We have to ensure that the page is accessible using your keyboard. 

For the Colorpicker Test Modal page, I attached a MS Word document stating all the verification points that should be covered. Steps 16 to steps 20 are related to modal. 

URL's: 
http://master-enterprise.demo.design.infor.com/components/colorpicker/example-index.html
http://master-enterprise.demo.design.infor.com/components/colorpicker/test-modal.html

**Describe alternatives you've considered**
Attached is the MS Word Colorpicker test cases

**Additional context**
[Color Picker Test Case.docx](https://github.com/infor-design/enterprise/files/2181027/Color.Picker.Test.Case.docx)

Color Picker Test Case

- [x] Verify user can clear color selection
- [x] Should not be able to enter text in the read only color picker field box
- [x] Verify color picker label appears correctly in the “Show Label” field box
- [x] Verify color label appear
- [x] Non-Editable color picker: Should not be able to edit the field using your keyboard
- [x] Verify user can restore to default color (None)
- [x] Verify user can only pick a color from the pre-configured color palette
- [x] Verify user can tab in, and arrow for each color
- [x] Verify user can click Enter key to save the color
- [x] Verify user can manually enter the color key number
- [x] Verify the “None” color picker option appears with box and red line across it
- [x] Dirty tracker color picker: The dirty tracker should appear when a color is chosen
- [x] Validation color picker: ensure the word requires appears with a red icon if the validation field box is not populated
- [x] Verify for Upper/Lower Case color picker field box the user is only allowed to enter “Upper case” for the upper-case field box and “Lower case” for the lower-case field box
- [x] ~~Verify the colors in the color picker looks correct on all three themes~~, pass a color theme in order to test manually

**Modal**

- [x] Verify that once in the color picker modal the user can click the cancel, and send the escape key to close the modal
- [x] Verify Modal opens, and user is able to update “Both” color pickers in the modal and either click cancel or save to close the modal
- [x] Verify that the user can tab and enter key within the modal
- [x] Verify that the user can click down arrow key and select a color from the color picker
- [x] Verify that you can use your keyboard to enter a color in the color picker field box

**Comment by tmcconechy** [comment]
Seems like all these tests are done and merged now.
