### ISSUE TITLE
Personalize: Cannot scroll through forms in responsive or mobile view

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3330]
**Describe the bug**
Personalize: Cannot scroll through the forms in responsive or mobile view.

**To Reproduce**
1. Resize the browser screen to smaller height size or open a browsers in Android/iOS
2. Go to http://master-enterprise.demo.design.infor.com/components/personalize/example-form.html
3. See issue: You cannot scroll down through the forms

**Expected behavior**
Should be able to scroll down through the forms in responsive or mobile view.

**Version**
- ids-enterprise: v4.19.0 to v4.25.0-dev

**Screenshots**
Unable to scroll
![forms-scroll](https://user-images.githubusercontent.com/39508864/72429254-7db29b00-37ca-11ea-9e3e-0610c673fea4.gif)

**Platform**
 - All devices, OS, and browsers.

**Additional context**
N/A

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
