### ISSUE TITLE
Toolbar Flex: Overflow menu hidden behind page content on infor GO

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3331]
**Describe the bug**
The overflow menu for a flex toolbar is falling behind the content in a iOS Infor Go environment. I think the setting of attachToBody isn't getting set, because the control doesn't detect it's on a iOS/macOS device when in the app.

**Expected behavior**
Overflow menu should display correctly

**Version**

- ids-enterprise: v4.24.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/72441426-48795f00-3770-11ea-9bdf-d2e62b3f7f87.png)

**Platform**
 - InforOS on iOS devices, I believe

**Additional context**
I think we may need to by default set the attachToBody:true by default, unless the browser type is chrome/safari/edge. @EdwardCoyle would that cause a performance issue?

**Comment by tmcconechy** [comment]
- remove the if for safari
- change the setting default to true

**Comment by EdwardCoyle** [comment]
Yep agreed, we can switch it to default.

**Comment by jbrcna** [comment]
The issue is now resolved. moving this ticket to Done column
