### ISSUE TITLE
Datagrid: Provide validation output to list current errors

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise#3332]
**Is your feature request related to a problem? Please describe.**
We use Datagrid validation to show errors in the datagrid, however in our use case we only allow certain actions if the model of the datagrid is valid. Currently there is no way to tell whether all columns are valid or not and therefore we need to validate whole model again

**Describe the solution you'd like**
We would like Datagrid to have output with validation errors listed if any. This could be an array of invalid cells e.g.
```
[{
col: 0,
row: 1,
validation: 'required',
message: '<required message shown in the Datagrid>'
}]
```

**Describe alternatives you've considered**
Currently we are validating whole dataset which leads to duplicate validation

**Comment by tmcconechy** [comment]
Is this still needed or do you have a workaround?

**Comment by tmcconechy** [comment]
Descoping for now
