### ISSUE TITLE
Editor: Produces inconsistent line spacing

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3335]
**Describe the bug**

When Enter is used to add a new line after a heading like an h3 element, Chrome by default will insert a DIV element instead of a P (paragraph) element by default. This should be overridden using document.execCommand('defaultParagraphSeparator', false, 'p') to ensure that most of our paragraphs will come in as P (paragraph) elements instead, which will produce more consistent and proper line spacing.  Related internal ticket https://jira.lawson.com/browse/LMCLIENT-28890

**To Reproduce**
Open the attached HTML file and press the F12 key to play with alternative behaviors and see the HTML produced. 

[LMCLIENT-28890.zip](https://github.com/infor-design/enterprise/files/4068549/LMCLIENT-28890.zip)

**Expected behavior**
See attached

**Version**
- ids-enterprise: [e.g. v4.25]

**Platform**
 - windows / mac
 - Browser Name [chrome]

**Additional context**
See links below for further reference.
- https://www.fxsitecompat.dev/en-CA/docs/2018/rich-text-editor-s-newline-behaviour-has-been-changed-now-generates-div-instead-of-br/
- https://stackoverflow.com/questions/2735672/how-to-change-behavior-of-contenteditable-blocks-after-on-enter-pressed-in-vario
- https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content#Differences_in_markup_generation

**Comment by lipetzan** [comment]
How risky and large is this one @tmcconechy ?   I'm being pushed hard for this in 4.25.

**Comment by tmcconechy** [comment]
Let me take a look. We may have to delay 4.25 release a bit if thats the case. I dont think its "risky" or will take too long tho.

**Comment by tmcconechy** [comment]
@pwpatton @lipetzan - this is now in 4.25 next build (beta 2 or rc) - in the next day or two it will be ready along with an dev and rc/beta build. Do you have someone that can test this once you pull it in?

**Comment by pwpatton** [comment]
@tmcconechy We have Kris working on this right now with an npm link. We have work to do on our side where we've overridden things. But this is his P1 for our next code cutoff.

**Comment by tmcconechy** [comment]
OK, we applied the fix. So please test it out on your end.

**Comment by pwpatton** [comment]
@tmcconechy @lipetzan I actually thought this was a different ticket. @lipetzan do we have someone to look at this right now?

**Comment by tmcconechy** [comment]
Just as a note this fix is in 4.25.x branch need to make a 4.25 beta with this shortly which will help.

**Comment by lipetzan** [comment]
@tmcconechy  we'll pick this up and get a build out to an app dev for testing once this is ready.

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in https://4250-rc0-enterprise.demo.design.infor.com/components/editor/example-index.html using the steps in PR.
