### ISSUE TITLE
Datagrid: Getting errors filtering on a date column when using the in-range operator

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3337]
Describe the bug
Getting JSE when using the date picker on a date column and the operator is in-range.

To Reproduce
1. Using http://localhost:4000/components/datagrid/example-filter.html
2. add the datagrid option of filterWhenTyping: false  
3. Enter a date into the filter criteria field for Order Date (leaving the operator set to Equals)
4. Hit the enter key (because of step #2)
5. Change the operator to in-range for Order Date
6. Open the date picker for Order Date

Expected behavior
Date picker works properly, doesn't throw JSE

Version
v4.25.0-dev

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/72570346-4273a300-3882-11ea-87fc-88c3df188ddb.png)

**Comment by claudenbach** [comment]
![Git-3337](https://user-images.githubusercontent.com/39804038/72570497-b8780a00-3882-11ea-9d5a-362dc175da67.gif)

**Comment by claudenbach** [comment]
Perhaps simply clear the date value from the filter field when the in-range operator is selected and two date values are not present?

**Comment by brianjuan** [comment]
Passed QA in master in https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html in all browsers. Will retest in RC once deployed.
![image](https://user-images.githubusercontent.com/39508864/75675561-56eced00-5cc2-11ea-95e9-40a476f0a3e5.png)

**Comment by brianjuan** [comment]
Passed QA in RC in all browsers as well. Tested in https://4260-rc0-enterprise.demo.design.infor.com/components/datagrid/example-filter.html. Moving to Done.
![image](https://user-images.githubusercontent.com/39508864/75764383-c1f8fb00-5d78-11ea-85e9-d5b721d89a4b.png)
