### ISSUE TITLE
Datagrid: unable to see the whole sort filter when in Subtle theme, Dark Variant 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3340]
**Describe the bug**
Datagrid: unable to see the whole sort filter when in Subtle theme, Dark Variant 

**To Reproduce**
1. Go to http://4250-beta0-enterprise.demo.design.infor.com/components/datagrid/example-comments.html?theme=soho&variant=dark
2. Make sure you're in Subtle Theme, Dark Variant 
3. Hover/play in different columns 

**Expected behavior**
The sort filter should always be visible 

**Version**
IDS Beta 4.250

**Screenshots**
http://4250-beta0-enterprise.demo.design.infor.com/components/datagrid/example-comments.html?theme=soho&variant=dark
![image](https://user-images.githubusercontent.com/45757016/72601322-22121a00-3950-11ea-8547-43b5ba0e13d3.png)

**Platform**
All Browser, OS and Devices. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This was fixed already
