### ISSUE TITLE
Datagrid: Tooltip is not being removed after scrolling in Mobile Device 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3349]
**Describe the bug**
Datagrid: Tooltip is not being removed after scrolling in Mobile Device 

**To Reproduce**
1. Open iOS device browser and goto http://4250-beta0-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html 
2. Hover in the Activity of Product Id 2142201 
3. Play and Scroll left and right 

**Expected behavior**
Tooltip should disappear 

**Version**
IDS Beta 4.250

**Screenshots**
![55C50CD7-0A68-4571-AB6A-9E8C576798DB](https://user-images.githubusercontent.com/45757016/72734676-2b5fe880-3bd5-11ea-8630-20555acc692e.png)

**Platform**
Mobile Devices. Both Android and iOS

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Descoping this issue for now
