### ISSUE TITLE
Rich Text Editor Enhancements - For Candidate Space

### ISSUE THREAD

**Issue by lauracarlsoninfor** [infor-design/enterprise#335]
**Describe the bug**
Customers need the ability to format job descriptions. The current functionality doesn't keep text size, format the same; doesn't allow users to copy/paste from word or notepad without changing the formatting, (currently doesn't allow copy/paste from notepad at all) the formatting functions within the system don't stay with the text when the job is posted on candidate space. Customers are also asking for the ability to add videos and images to the job descriptions on candidate space. 

Examples and requirements can be found here: https://inforonline-my.sharepoint.com/:o:/r/personal/laura_carlson_infor_com/Documents/TA%20Team/PRD/Job%20Description%20Formatting?d=wa9669f5cc0084020a3dbe8f6c2451408&csf=1&e=VfCp2A

**To Reproduce**
https://inforonline-my.sharepoint.com/:o:/r/personal/laura_carlson_infor_com/Documents/TA%20Team/PRD/Job%20Description%20Formatting?d=wa9669f5cc0084020a3dbe8f6c2451408&csf=1&e=VfCp2A
[Job Description Example 2.docx](https://github.com/infor-design/enterprise/files/2181650/Job.Description.Example.2.docx)
[Job Description Example.docx](https://github.com/infor-design/enterprise/files/2181651/Job.Description.Example.docx)
[Job Description Formatting.pdf](https://github.com/infor-design/enterprise/files/2181652/Job.Description.Formatting.pdf)
[Job Description Formatting2.pdf](https://github.com/infor-design/enterprise/files/2181653/Job.Description.Formatting2.pdf)

**Expected behavior**
User should be able to copy/paste from Word and have the formatting pull through.  The description on the description page, the preview page, and candidate space should all match. 

**Screenshots**
https://inforonline-my.sharepoint.com/:o:/r/personal/laura_carlson_infor_com/Documents/TA%20Team/PRD/Job%20Description%20Formatting?d=wa9669f5cc0084020a3dbe8f6c2451408&csf=1&e=VfCp2A

**Platform**
Browser: Google Chrome Version 67.0.3396.99; Internet Explorer 11 Version 11.2312.14393.0 
Word: 2016 
Notepad Windows 10, Version 1607 (OS Build 14393.2312) 
OS: Windows 10 Enterprise; Version 1607 

Infor HR has also encountered this issue. I am not sure what browsers, doc versions, or OS versions they are on. 

**Additional context**
 LMCLIENT-20727

**Comment by tmcconechy** [comment]
Could you maybe attach the sharepoint docs in a zip? I don't seem to have access and probably no one else does also not sure if the link works as it has an emoji in it?

**Comment by lauracarlsoninfor** [comment]
Hi Tim,

I attached them all to the fit hub thing as pdf’s. Did that not work?

Thank you,
Laura Carlson
________________________________

**Comment by tmcconechy** [comment]
Hi!

I see this files attached..
Job Description Example 2.docx
Job Description Example.docx
Job Description Formatting.pdf
Job Description Formatting2.pdf

But there is also 3 sharepoint links i cannot get into (looks like 3 the same link).
https://inforonline-my.sharepoint.com/⭕️/r/personal/laura_carlson_infor_com/Documents/TA%20Team/PRD/Job%20Description%20Formatting?d=wa9669f5cc0084020a3dbe8f6c2451408&csf=1&e=VfCp2A

If there is nothing else there we need i think we are good then to review this issue in more detail.

**Comment by tmcconechy** [comment]
Update pasting of text is now possible as per https://github.com/infor-design/enterprise/issues/548 which has been fixed. This should allow you to paste plain text correctly. Can always paste in plain unformatted text and add the formatting.

**Comment by clepore** [comment]
Closing this issue as it was mostly to facilitate the discussion around the current rich text editor. Please create individual issues and feature requests using our template for specific items that need addressed.
