### ISSUE TITLE
Datagrid: Focus in Calendar field is not aligned 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3350]
**Describe the bug**
Datagrid: Focus in Calendar field is not aligned 

**To Reproduce**
1. Go to http://4250-beta0-enterprise.demo.design.infor.com/components/datagrid/example-placeholder.html
2.Click and Focus in Order Date column in Row ID 1.

**Expected behavior**
Notice that the focus or the blinker is not aligned. 

**Version**
Beta 4.250 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/72735369-a8d82880-3bd6-11ea-8404-3500f727a7c7.png)

**Platform**
All Browser, OS and Devices 

**Additional context**
N/a

**Comment by janahintal** [comment]
Hi @tmcconechy, the cursor is now aligned however the highlight or focus has been cut off in Uplift theme. Please see below.

![image](https://user-images.githubusercontent.com/45757016/72989822-fb5d5300-3e29-11ea-9c61-51d569184bb9.png)

**Comment by tmcconechy** [comment]
OK lets fix this for the final @deep7102 ?

**Comment by janahintal** [comment]
QA Passed.  This issue is now resolved. Thank you. 

Re-tested in http://4250-rc1-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html?theme=soho&variant=contrast
