### ISSUE TITLE
Checkbox Component: Dark Contrast color on text and checkbox not correct

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3355]
**Describe the bug**
Checkbox Component: Dark Contrast color on text and checkbox not correct

**To Reproduce**
1. Go to URL: http://4250-beta0-enterprise.demo.design.infor.com/components/checkboxes/example-legend-colors.html?theme=soho&variant=dark
2. Click on "More" and select "Dark Contrast
3. See error" Company Holiday text and checkbox color is not correct. Please see screen shot attached. 

**Expected behavior**
The color for "Company Holiday" on Dark Contrast has to be corrected

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1300" alt="Checkbox dark contrast" src="https://user-images.githubusercontent.com/39101346/72820693-53833200-3c3d-11ea-8a40-26e612b51997.png">

**Platform**
 - All Browser Name [Chrome]

**Additional context**
None

**Comment by tmcconechy** [comment]
This was noted on #3007 so fixing there. Although the contrast isnt a bit better. But its not 100% vibrant and this is ok because it is disabled.

<img width="226" alt="Screen Shot 2020-01-21 at 11 04 08 AM" src="https://user-images.githubusercontent.com/814283/72820922-c2f92180-3c3d-11ea-8f9f-51d33a5453d1.png">

**Comment by tmcconechy** [comment]
This was fixed on the latest PR on #3007 so ready to test in the next build

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in http://4250-rc0-enterprise.demo.design.infor.com/components/checkboxes/example-legend-colors.html?theme=soho&variant=dark. Moving to Done.
