### ISSUE TITLE
Modal: modal-wrapper flex direction change?

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#3360]
Hi,

I couldn't find a template for a "support" ticket, but this would count as one. 

We found an issue with auto resize of our CAPs when upgrading IDS to v4.24.0. Their width used to auto-shrink when resizing the browser window. We're setting max-width and "default" width of our CAP, which is the direct child to the automatically added `.modal-wrapper` element as below.

```
<div class="modal-wrapper">
   <div class="contextual-action-panel modal is-visible"...>  <!-- we're setting width and max-width on this one in our code

```
This used to work as below when window width decreased:
![modal-wrapper-flexdirection-row](https://user-images.githubusercontent.com/1101770/72886395-09b44d80-3d0a-11ea-99f7-9774a2e8ceff.gif)
The main CAP element is fully visible

After IDS update, it behaves like this:
![modal-wrapper-flexdirection-column](https://user-images.githubusercontent.com/1101770/72886421-1638a600-3d0a-11ea-9b56-a8474706ba13.gif)
The main CAP element gets hidden on sides

This is caused by the addition of `flex-direction: column` to the `.modal-wrapper` class:
https://github.com/infor-design/enterprise/commit/9ae34881367d5962f210ab81a3396b67687dfdfd#diff-d662c14c5dcd7e4b41028bf60b9bc77b

Now the only child of `.modal-wrapper` will auto shrink its height rather than its width.

The change was made as part of a datagrid fix, not a modal fix. What is the reason for the flex-direction change? Can we "safely" revert it on our end, to make the `.modal-wrapper` use flex-direction row as before, or will that lead to some other issue?

Our CAP is very custom and complex, so this change might not affect smaller, more regular CAPs & modals, but it would be helpful to know the reason to the change. Thank you!

**Comment by tmcconechy** [comment]
While testing some of the examples with datagrid on modals there was layout issues (no defaulting width content blocked off similar to your example / video actually).  May have been:
http://localhost:4000/components/lookup/test-modal-lookup.html and since the datagrid uses `  display: flex;` this seemed like a good fix since it was just on the parent wrappers in the modal.

All our cap examples seem ok but they are simple. So i would say its safe to override this (safest within your contents area if that works?). But will monitor for this in case anyone else has issues.

**Comment by volante007** [comment]
Ah ok, thank you! The only way we can override this is to change IDS css for .modal-wrapper. Can't do it within the contents area unfortunately since that's a few levels down in the DOM hierarchy of the CAP.

**Comment by tmcconechy** [comment]
OK, Maybe if you can workup an example we could add some sort of class you can use on the content to reset it?

**Comment by volante007** [comment]
I think I got it working now without overriding the default IDS style. As mentioned, we've been setting max-width + width on the .modal-wrapper child. If removing width and making sure the inner elements scale properly it works like before.

So I think the combination of our special use case and that we can work around it means we can close this one :)
