### ISSUE TITLE
ListView: Bullet icon has same color with the background color when hovered in Subtle theme High Contrast and Dark Variant. 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3361]
**Describe the bug**
List View: Bullet icon has same color with the background color when hovered in Subtle theme High Contrast and Dark Variant. 

**To Reproduce**
1. Go to http://4250-beta0-enterprise.demo.design.infor.com/components/listview/example-paging-clientside.html?theme=soho&variant=contrast
2. Make sure you're in Subtle Theme Dark or High Contrast Variant 
3. Hover in 'Middle School Parking Lot' 

**Expected behavior**
Bullet icon should at least have different contrast over the background-color

**Version**
IDS Beta 4.250

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/72894332-047cf000-3d56-11ea-90d6-18779530a596.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping this for now
