### ISSUE TITLE
Locale: formatDate() does not work for es-419

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#3363]
**Describe the bug**
Using `Soho.Locale.formatDate` to format a date string coming from datepicker does not work in es-419 Locale. It returns undefined.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-index?locale=es-419 
(or any demo site with es-419 as locale)
2. Open Dev console
3. Paste and call `Soho.Locale.formatDate("22 ene. 2020 00:00", Soho.Locale.calendar().dateFormat.datetime, true);` 
4. undefined is returned

**Expected behavior**
Formatted date string is returned. 

**Version**
- ids-enterprise: v4.24.0

**Additional context**
The example string, "22 ene. 2020 00:00", corresponds to how a datepicker (with time) value looks when es-419 is used

**Comment by tmcconechy** [comment]
Wierd. I would also expect `Locale.parseDate('22 ene. 2020 00:00', { date: 'datetime'})` to work but it is not. This is working:

```
Locale.formatDate(new Date(), {date: 'datetime'})
// "22 ene. 2020 08:55"
// But the invere is not
Locale.parseDate('22 ene. 2020 08:55', { date: 'datetime'})
// undefined
```
