### ISSUE TITLE
Locale: Japanese Characters Not Showing Up in the App Menu

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3364]
**Describe the bug**
When using Japanese and possibly other languages the characters seem to flow to the next line when on deeper app menu levels.

**To Reproduce**
1. Take the below code and replace the contents of app/views/components/applicationmenu/test-six-levels.html
2. Go to http://localhost:4000/components/applicationmenu/test-six-levels.html?locale=ja-JP
2. Expand Level 1 outbound links.

**Expected behavior**
Visible Japanese

**Version**
- ids-enterprise: [e.g. v4.25]

**Screenshots**
![Screen Shot 2020-01-22 at 9 11 23 AM](https://user-images.githubusercontent.com/814283/72901161-3a3ebc00-3cf7-11ea-9448-b2059c59e753.png)

**Platform**
 -  chrome

**Other Info**
Code: 
[test-six-levels.html.zip](https://github.com/infor-design/enterprise/files/4097704/test-six-levels.html.zip)

Seems to me like its the width of the text in this font. Maybe we can adjust this rule (width)
```
.accordion-pane .accordion-header.list-item a {
  padding-left: 1px;
  vertical-align: middle;
  width: calc(100% - 41px);
}
```

**Comment by EdwardCoyle** [comment]
Added the fix for this to the other 4.25.x Application Menu Q/A patch:  https://github.com/infor-design/enterprise/pull/3359

**Comment by brianjuan** [comment]
Japanses character are now showing up, but in Mac browsers and Android Chrome, the indentations are bit misaligned.
Mac Chrome
https://4250-rc0-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html?locale=ja-JP
![image](https://user-images.githubusercontent.com/39508864/72976698-0904df80-3e0e-11ea-9cee-18f581edcb72.png)

![image](https://user-images.githubusercontent.com/39508864/72976849-53865c00-3e0e-11ea-812b-d5cd3e1d9089.png)

In IE, it happens in Uplift theme
https://4250-rc0-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html?locale=ja-JP
![image](https://user-images.githubusercontent.com/39508864/72977086-b546c600-3e0e-11ea-96d6-451bc7e4b8d0.png)

**Comment by EdwardCoyle** [comment]
@brianjuan not sure what happened during your testing, but it appears that in both of your screenshots the Japanese `Noto Sans JP` font that's supposed to be used here was not loaded properly.  I re-tested the `rc` URL and it seems that it's loading and the alignment is better:

![Screen Shot 2020-01-23 at 9 35 57 AM](https://user-images.githubusercontent.com/3249601/72994883-f5ce2180-3dc5-11ea-950c-7b7ca2fd7899.png)
<img width="780" alt="Screen Shot 2020-01-23 at 9 48 50 AM" src="https://user-images.githubusercontent.com/3249601/72994884-f5ce2180-3dc5-11ea-9d5d-95947c5109f0.png">

**Comment by tmcconechy** [comment]
It also looks pretty good to me.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to Done column.

**Comment by brianjuan** [comment]
Since it only happens in my machine, I agree to move this to Done. Thank you guys.
