### ISSUE TITLE
Datagrid: Cell value not escaped when referencing object.property in field property of column

### ISSUE THREAD

**Issue by albinbergvall** [infor-design/enterprise#3366]
**Describe the bug**
When using wrapper objects in a dataset, and referencing a property of that wrapper in the columns of the datagrid, the values of those fields won't be escaped. 

**To Reproduce**
1. Edit any datagrid sample
1.1 Wrap the data object in a new object:
```
data.push({
      wrapper: { ... }
});
```
1.2 Inject HTML elements/scripts into a property of the wrapper:
```
data.push({
      wrapper: { 
            productName: '<h1>Some product</h1>',
            ... 
      }
});
```
1.3 Reference the wrapper property in a column field:
```
columns.push({ 
      id: 'productName', 
      name: 'Product Name', 
      field: 'wrapper.productName'
});
```
2. Open the sample
3. Inspect a cell in the column
4. The HTML element/script is injected

**Expected behavior**
The value of _wrapper.property_ is escaped and displayed in the cell.

**Version**

- ids-enterprise: v.4.25.0

**Screenshots**
![image](https://user-images.githubusercontent.com/30404138/72906918-46486f00-3d33-11ea-91c1-a87b6a5e017d.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 79.0.3945.130 (Official Build) (64-bit)

**Comment by davidcarlsonberg** [comment]
Using this for the view:
[example-alternate-row-shading.html.zip](https://github.com/infor-design/enterprise/files/8287023/example-alternate-row-shading.html.zip)

**Comment by tmcconechy** [comment]
cc @albinbergvall anything you can add?

**Comment by tmcconechy** [comment]
Descoping this for now
