### ISSUE TITLE
Datagrid: Render issues with frozen columns and column groups

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3367]
Describe the bug
Datagrid render issues when the grid has both frozen columns and column groups.

To Reproduce

1. Using the attached example-frozen-columns-with-group-headers.html
2. Notice the rendering issues

Expected behavior
Group header is displayed and rows are properly aligned

Version
v4.25.0-dev

Screenshots
![image](https://user-images.githubusercontent.com/39804038/72913159-5562f900-3d02-11ea-8cbd-ed99544e184f.png)

**Comment by claudenbach** [comment]
[Git-3367.zip](https://github.com/infor-design/enterprise/files/4098452/Git-3367.zip)

**Comment by claudenbach** [comment]
Example from Landmark 3.5

![image](https://user-images.githubusercontent.com/39804038/72913510-dc17d600-3d02-11ea-84e6-01fe5dab6527.png)

**Comment by claudenbach** [comment]
Example from Landmark 4.0

![image](https://user-images.githubusercontent.com/39804038/72913634-0d90a180-3d03-11ea-836d-d5118fe5a13d.png)

**Comment by tmcconechy** [comment]
Yeah looks like its not adding the second heading there. Wondering if as a workaround you can make it work by adding the spans? Will check this out as soon as we can.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
