### ISSUE TITLE
App Menu / Accordion: placeholder is a bit darker

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3369]
**Describe the bug**
The color of the placeholder is too dark

**To Reproduce**
1. Go to https://4250-rc0-enterprise.demo.design.infor.com/components/applicationmenu/test-hcm.html?theme=uplift&variant=contrast
2. Ensure that the Theme is `Vibrant` and Variant is `High Contrast`
3. See error, the placeholder is almost like a normal text

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/72958689-e27d7f00-3de2-11ea-85ac-a45903de127d.png)

**Version**
v4.250-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/72958735-08a31f00-3de3-11ea-8fda-d2e84e06251a.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
This was fixed in 4.25 adding to QA this version

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
