### ISSUE TITLE
Multiselect: X icon is not vertically centered inside the tags in Windows Edge, IE and Firefox

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3370]
**Describe the bug**
Multiselect: X icon is not vertically centered inside the tags in Windows Edge, IE and Firefox using Uplift.

**To Reproduce**
1. Open Edge, IE or Firefox browsers
2. Go to https://4250-rc0-enterprise.demo.design.infor.com/components/multiselect/example-index.html?theme=uplift&variant=light
3. In Edge and IE, notice that the X icon is not centered. In Firefox, notice that the label is not centered.

**Expected behavior**
X icon and label should be vertically centered.

**Version**
- ids-enterprise: v4.25.0-rc0

**Screenshots**
Windows Edge
![image](https://user-images.githubusercontent.com/39508864/72982611-69018300-3e1a-11ea-87d9-6eca1050ff4a.png)

Windows IE
![image](https://user-images.githubusercontent.com/39508864/72982726-b847b380-3e1a-11ea-8b1e-d458983c1dbd.png)

Windows Firefox
![image](https://user-images.githubusercontent.com/39508864/72982810-e3ca9e00-3e1a-11ea-9838-bea25313e337.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Edge, IE 11, Firefox

**Additional context**
N/A

**Comment by tmcconechy** [comment]
@EdwardCoyle - want to fix for 4.25 or 4.26? Might as well 4.25 i guess

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in https://4250-rc1-enterprise.demo.design.infor.com/components/multiselect/example-index.html?theme=uplift&variant=light.

Windows 10 Edge
![image](https://user-images.githubusercontent.com/39508864/73157193-4bcefc00-411b-11ea-87a1-3d31b6d731eb.png)

Windows 10 IE
![image](https://user-images.githubusercontent.com/39508864/73157327-99e3ff80-411b-11ea-8ecb-96e8676b1c45.png)

Windows 10 Firefox
![image](https://user-images.githubusercontent.com/39508864/73157483-11b22a00-411c-11ea-9be5-786bbee77152.png)
