### ISSUE TITLE
Splitter: Collapse Button not removed when destroyed

### ISSUE THREAD

**Issue by rvaja-infor** [infor-design/enterprise#3371]
![Splitter-CollapseButton](https://user-images.githubusercontent.com/45232365/72984940-bbbc4a00-3ddc-11ea-8d1f-484cd783e6b2.png)

**Describe the bug**
We have a GWT based application that wraps the IDS controls. When navigating away from a page the '#destroy' function is called on the control. When going back to the page the controls constructor is called in this issue 'splitter'.

Found that when going back and re-constructing the 'splitter' after destroying it, an second collapse button appears. This second button prevents the splitter from collapsing, and also means that the we get stale click handlers being left behind which may cause memory leaks.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/splitter/test-collapse-button.html'
2. Open Developer Console
3. In the console enter the below commands to replicate
`$('#splitter')`
`$('#splitter').data('splitter')`
`$('#splitter').data('splitter').destroy()`
`$('#splitter').splitter({'collapseButton': true})`
4. See double collapse button. Also observe that collapse no longer works

**Expected behavior**
The collapse button to be removed on destroy, and click handler to be removed to avoid memory leaks. Even if collapse button shown twice, collapse should still work.

**Version**
ids-enterprise: v4.24.0

**Screenshots**
Screenshot attached showing double collapse button

**Platform**
 - Device: Desktop PC
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version: 79.0.3945.117 (Official Build) (64-bit)

**Additional context**

**Comment by rvaja-infor** [comment]
Potential resolution:
`var collapseButton = this.element.find('#splitter-collapse-btn').remove()`
`if (collapseButton) {`
`    collapseButton.off('click');`
`    collapseButton.remove();`
`}`

**Comment by brianjuan** [comment]
QA Passed on all browsers, tested in http://master-enterprise.demo.design.infor.com/components/splitter/test-collapse-button.html?theme=uplift&variant=light. Will retest once beta is deployed.
