### ISSUE TITLE
Column: Cannot change color for all bars at once

### ISSUE THREAD

**Issue by charlesdasilvacosta** [infor-design/enterprise#3375]
**Describe the bug**
I want to create a chart column with a specific color but the column keep his default color (blue).

**To Reproduce**
Create a SohoColumnComponent  with type='column' and a color field in the data.

**Screenshots**

![aa](https://user-images.githubusercontent.com/22666121/72986023-8ec16480-3de7-11ea-8ef9-ffea3542633d.PNG)

**Comment by tmcconechy** [comment]
Decoping this issue for now...
