### ISSUE TITLE
Modal: Keeps on scrolling up after closing in IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3381]
**Describe the bug**
Modal keeps on scrolling up after closing in IE

**To Reproduce**
1. Open IE and Go to http://4250-rc0-enterprise.demo.design.infor.com/?theme=uplift&variant=light
2. Goto Modal and click Show Modal button 
3. Close the Modal
Notice that after closing, the page has been forced to scroll up

**Expected behavior**
The page should be still and won't scroll after closing a modal

**Version**
IDS RC0 4.250

**Screenshots**
N/a

**Platform**
Windows 10 IE 11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Will keep this for now, but starting to descope IE11 issues soon.

**Comment by tmcconechy** [comment]
Descoping this issue now see https://github.com/infor-design/enterprise/issues/3756
