### ISSUE TITLE
Datagrid: Short Row Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3385]
**Describe the bug**
Found more issues in short row with the editors, when using no formatter (or a custom formatter) and textOverflow: 'ellipsis'. Made an example for this issue i'll commit.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/test-landmark (new example)
2. Click on any cell
3. See error

**Expected behavior**
No layout issues.

**Version**
- ids-enterprise: [e.g. v4.25]

**Screenshots**
<img width="291" alt="Screen Shot 2020-01-24 at 5 27 02 PM" src="https://user-images.githubusercontent.com/814283/73108633-ceaf4700-3ece-11ea-8c62-f830e83e4c0f.png">

**Platform**
 - Chrome / Any

**Additional context**
Happened to to input height changes. This happens in a combo of tests we do not have which is no formatter (or a custom formatter) and textOverflow: 'ellipsis'

**Comment by tmcconechy** [comment]
Fixing for 4.25

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in https://4250-rc2-enterprise.demo.design.infor.com/components/datagrid/test-landmark

**Comment by brianjuan** [comment]
Verified QA passed in IE as well, http://4251-enterprise.demo.design.infor.com/components/datagrid/test-landmark.html.
![image](https://user-images.githubusercontent.com/39508864/73523234-5c49e400-4445-11ea-9fe7-8931994bb67a.png)
