### ISSUE TITLE
Datagrid: Lookup field text is misaligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3386]
**Describe the bug**
when you resize the column then open the lookup modal and close it the text in `lookup field `(product id)  becomes misaligned

**To Reproduce**
1. Go to https://4250-rc1-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html?
2. Resize the column `Product Id`
3. Open Lookup, the lookup modal shows up
4. Close the modal
5. See error

**Expected behavior**
the test should not be misaligned

**Version**
v4.250-rc1

**Screenshots**
![Large GIF (1332x534)](https://user-images.githubusercontent.com/56722184/73160353-b421db80-4123-11ea-89a0-4cf7afddb92e.gif)

**Platform**
All

**Comment by tmcconechy** [comment]
Fixed this in RC 2 by making a minWidth on the resize, also added the ellipsis option. But note that this isnt the default so it wont ALWAYS work this way.

**Comment by jbrcna** [comment]
The issue is now resolved. tagging this ticket as PASSED and DONE
Verified in https://4250-rc2-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html
