### ISSUE TITLE
Datagrid: issue with sort indicator

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#3391]
**Describe the bug**
when sort indicator is set programmatically (via some local storage state) then the initial click of sort column calls onSorted but doesn't send the correct `sortAsc` value.

**To Reproduce**
I'm only able to dup in NG. I didn't have time to set up an EP sample that is complex as the NG sample. I don't think this is an NG issue though.

NOTE: May required stand alone pager. 
      [disableClientSort]="true"
      [disableClientFilter]="true"
      [paging]="false"

1. go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-standalone-pager
2. Verify that ProductName column sort indicator is sorted ascending
3. click the ProductName column to sort it descending.
Notice it does not sort it descending. You have to click it a 2nd time to get it to sort descending.

**Expected behavior**
Clicking it once should cause it to sort descending.

**Version**
4.25 of EP
6.4 of NG

Steps to dup require https://github.com/infor-design/enterprise-ng/pull/718 be merged

**Comment by tmcconechy** [comment]
Fixed this issue on commit https://github.com/infor-design/enterprise/commit/6054528edca0fffa10f8090db8ec2aa85daddd3f  (accidentaly push to master).

This issue is covered by a new unit test in EP so to needed to do functional QA.
