### ISSUE TITLE
Datagrid Component: Uplift Dark and High Contrast Multiple Issues

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3392]
**Describe the bug**
Datagrid Component: Uplift Dark and High Contrast Multiple Issues

**To Reproduce**
1. Go to url: http://master-enterprise.demo.design.infor.com/components/datagrid/example-index?theme=uplift&variant=dark
2. Click on uplift theme and then also click on Dark contrast
3. Please see my screen shot for the multiple issues that need to be correct on Dark contrast

**Expected behavior**
The colors and text on the data grid need to updated. Spoke to Tim and Tim will work with the Design team. 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1252" alt="Datagrid Dark Contrast Multiple Issues" src="https://user-images.githubusercontent.com/39101346/73207701-2938e500-4113-11ea-99d9-fdef0e41732b.png">

**Platform**
 - All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
@ericangeles 
Forgot I actually fixed this already in 4.25. Just try and test it some more and i think we can just move to done

**Comment by ericangeles** [comment]
@tmcconechy it seems hovering the icons does not make it darker. That's the only issue that am seeing now.

**Comment by ericangeles** [comment]
@tmcconechy am not certain about the issue that I saw. Should we add hover effect the sort up and down icons? It seems that clicking the desc icon isn't functioning the descending order but it always in ascending. If we add the hovering effect, it should follow the icon that you hover and click.

**Comment by tmcconechy** [comment]
Its looking ok for me i think? If i go to:

http://master-enterprise.demo.design.infor.com/components/datagrid/example-index?theme=uplift&variant=dark

Are you just suggesting that we make the hover color on the header dark instead of light? If so that could look better. Feel free to give it a try and we can review

**Comment by ericangeles** [comment]
> Its looking ok for me i think? If i go to:
> 
> http://master-enterprise.demo.design.infor.com/components/datagrid/example-index?theme=uplift&variant=dark
> 
> Are you just suggesting that we make the hover color on the header dark instead of light? If so that could look better. Feel free to give it a try and we can review

So in that case, this will be reflectes to for all the themes and contrast?

**Comment by tmcconechy** [comment]
Ok, maybe im confused about what your saying? Can you describe the issue you see? It seems not bad in all themes with what i did to me.

**Comment by ericangeles** [comment]
My understanding on the hover is that, currently, when you hover the sort icon only, there's no hover effect or changes in the color of the icon. Something that will be a bit darker. Hovering on the header will display the icons, but when you try to hover the icon specifically, there's no hover effect or color changes.

I will probably create a PR and let's see if that works. And might also add the dark header instead of light that you suggested.

**Comment by tmcconechy** [comment]
Ok I see, giving the actual icon doesn’t have any effect (and never has) its only giving the whole header that toggles the search direction when pressed. Pressing the icon alone doesn’t do anything different so now state really needed there.

But we could try a better dark color(s)

**Comment by ericangeles** [comment]
Yeah, that's also my concern, a potential bug. That's what I meant on the ascending / descending stuff.

**Comment by tmcconechy** [comment]
Ok give it a try, as I see it it’s working fine but maybe the colors can be improved a bit

**Comment by tmcconechy** [comment]
Moved this over to confirm by QA, it was fixed previously.

**Comment by CindyMercadoReyes** [comment]
Tested this issue across browser and devices and the issue is now resolved. Moving this ticket to the Done column.
