### ISSUE TITLE
Datagrid: Alignment issues in Uplift

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3398]
**Describe the bug**
Datagrid: Alignment issues in Uplift.

**To Reproduce**
**Issue 1:**
1. Go to https://4250-rc1-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar.html?theme=uplift&variant=light
2. Type "paint" in the searchfield, then click outside the searchfield
3. See issue: text in searchfield is too low

**Issue 2:**
1. Go to https://4250-rc1-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html?theme=uplift&variant=light
2. Check the first, second and third rows
3. See issue: Partial and check are not vertically centered

**Expected behavior**
Text in searchfiled, partial and check should be properly aligned.

**Version**
- ids-enterprise: v4.25.0-rc1

**Screenshots**
Issue 1:
![image](https://user-images.githubusercontent.com/39508864/73263186-f6721800-420a-11ea-9995-f6b7d421961e.png)

Issue 2:
![image](https://user-images.githubusercontent.com/39508864/73263329-4b159300-420b-11ea-9ffc-ebbcb2db0174.png)

**Platform**
 - All Devices, OS, and Browsers

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Already fixed point 2. Will just fix point 1 as well.

**Comment by tmcconechy** [comment]
Adding a fix for this in 4.25 to retest

**Comment by EdwardCoyle** [comment]
@tmcconechy was there a PR associated with the fixes for this issue?  If there was doesn't seem it was linked.  Trying to understand how this was fixed and how it might affect #3296

**Comment by tmcconechy** [comment]
The fix for that specific part was this one padding change https://github.com/infor-design/enterprise/pull/3393/files#diff-5965810d2a8ecf5b1bc503baadb64cecL37

**Comment by EdwardCoyle** [comment]
OK thanks.  I don't think these changes affect #3296

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in: 
 - https://4250-rc2-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar.html?theme=uplift&variant=light 
 - https://4250-rc2-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html?theme=uplift&variant=light
