### ISSUE TITLE
Application Menu: Uplift App Menu has not enough contrast

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3400]
**Describe the bug**
We made changes to app menu for https://github.com/infor-design/enterprise/issues/2925 but when color changes are made this caused much lower contrast than previously https://github.com/infor-design/enterprise/issues/3007

**To Reproduce**
1. Go to http://localhost:4000/components/applicationmenu/example-personalized-roles.html?theme=uplift&variant=light
2. Compare to http://localhost:4000/components/applicationmenu/example-personalized-roles.html?theme=soho
3. See that the contents of the submenus in particular are too dim

**Expected behavior**
Lets grab the LM markup from the link below in their test bed and make a test page. Then adjust up the colors. I suggest #B7B7BA

**Version**
- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![Screen Shot 2020-01-28 at 1 07 09 PM](https://user-images.githubusercontent.com/814283/73291919-23083e80-41cf-11ea-822f-077c1fe73fd6.png)

**Platform**
 - Chrome / Try Windows and Mac

**Additional context**
https://usspvwlmclient1.infor.com/uitest/PatternTest/list/PlatformComponent?csk.includelpl=true&csk.developer=true - has the older version maybe we can grab the markup and make a new test.

**Comment by EdwardCoyle** [comment]
paging @vonnyw

**Comment by janahintal** [comment]
This issue is now resolved. Will now move to Done. Thanks!
Retested in http://4240-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=uplift&variant=light over http://4250-rc2-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=uplift&variant=light
