### ISSUE TITLE
Popupmenu: List separators disappear when browser zoom level is changed

### ISSUE THREAD

**Issue by victorclisbyinfor** [infor-design/enterprise#3407]
**Describe the bug**
When you have a popupmenu that has multiple list separators, some will vanish when you reduce the browser zoom level e.g. 70-80%.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/popupmenu/test-multiple.html
2. Right click on one of the Input controls to display the Popupmenu. Note that there are 3 list separators (which is expected).
3. Change the browser zoom to 70% or 80%. Right click on one of the Input controls again and note that you now may only see 1 or 2 list separators.
4. Continue opening and closing the Popupmenu and you will notice the list separators will show inconsistently (sometimes it will show 1, sometimes 2 and sometimes 3)

**Expected behavior**
Always show however many list separators that have been defined irrespective of the browser zoom level.

**Version**

- IDS Enterprise Components - v4.25.0-dev

**Screenshots**
Browser zoom @ 100%:
![image](https://user-images.githubusercontent.com/60455089/73417388-ce4bfb80-4367-11ea-8ac0-e1fb77ac2983.png)

Browser zoom @ 80%:
![image](https://user-images.githubusercontent.com/60455089/73417451-0d7a4c80-4368-11ea-8bf4-d4d276a678c5.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 79.0.3945.130

**Additional context**
I am unable to reproduce this in Edge so i think it's an issue with how Chrome handles sub pixel rendering. I've played around with the CSS and one potential solution that i have found is:

Current code:
![image](https://user-images.githubusercontent.com/60455089/73418094-461b2580-436a-11ea-914d-b62ac53f7828.png)

Proposed code:
![image](https://user-images.githubusercontent.com/60455089/73418103-4c110680-436a-11ea-9464-43584b55ea2a.png)

It seems that when you use the 'thin' property (which is equivalent to 1px anyway) instead of defining a specific pixel height, Chrome doesn't attempt to scale it when the browser zoom level changes. As a result, the separators remain visible all the time no matter what the browser zoom is set to.

**Comment by tmcconechy** [comment]
Thanks @victorclisbyinfor this is a great bug report. We will test your solution out to add it.

**Comment by deep7102** [comment]
Thanks! @victorclisbyinfor this is great.

**Comment by jbrcna** [comment]
The issue is now resolved. moving this ticket to Done
Tested in v4.26-dev
https://master-enterprise.demo.design.infor.com/components/popupmenu/test-multiple.html
