### ISSUE TITLE
Tag: Icon's misaligned with text in subtle theme

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3410]
**Describe the bug**
Icons in a tag are misaligned with the text for subtle theme

**To Reproduce**
1. Go to /components/tag/example-index.html
2. Ensure the page is on a subtle theme
3. See error

**Expected behavior**
Icons should align correctly

**Version**

- ids-enterprise: 4.26.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/73460831-bdd35b00-433e-11ea-97b3-e7a83976e389.png)

**Platform**
 - All

**Comment by tmcconechy** [comment]
It doesn't  seem to look like that for me.  Are you zooming or anything different?

![Screen Shot 2020-01-30 at 10 02 54 AM](https://user-images.githubusercontent.com/814283/73461204-c4b29b80-4347-11ea-9f8b-069998b7d851.png)

**Comment by EdwardCoyle** [comment]
Going to make a PR for this shortly.  Seems to be a slight difference in line height that's only present on Windows.

**Comment by jbrcna** [comment]
The issue still persists. **QA FAILED**
Verified in 
http://4251-enterprise.demo.design.infor.com/components/multiselect/example-tags
Browser: Windows Chrome
![image](https://user-images.githubusercontent.com/56722184/73524614-7638f600-4448-11ea-89c1-a4cf4afecf70.png)

Browser: Android Chrome
![image](https://user-images.githubusercontent.com/56722184/73525630-8eaa1000-444a-11ea-840d-c3f3bb5723aa.png)

**Comment by EdwardCoyle** [comment]
@jbrcna I'm not seeing the first issue... is the browser in that screenshot definitely Windows Chrome?   This is what I see on Browserstack on the latest Windows Chrome:

![Screen Shot 2020-01-31 at 9 37 53 AM](https://user-images.githubusercontent.com/3249601/73547763-9bf4d980-440d-11ea-88e6-e13dd86f0b7e.png)

I did see the Android issue.  I'm thinking we will call this "done" for 4.25.x and make the minor fixes in 4.26, what do you think @tmcconechy?

**Comment by tmcconechy** [comment]
Yes agreed. Lets make a new issue for whats left

**Comment by jbrcna** [comment]
@EdwardCoyle The 1st screenshot above is on Firefox but chrome have the same issue ( typo error :D ) . Testing is done using Browserstack. below are the complete list of the browsers that have the same issue
<img width="709" alt="image" src="https://user-images.githubusercontent.com/56722184/73626950-bc2ecd80-4685-11ea-9d04-1c907166d07c.png">

<img width="896" alt="image" src="https://user-images.githubusercontent.com/56722184/73627059-221b5500-4686-11ea-98ec-44c4248105b0.png">

<img width="977" alt="image" src="https://user-images.githubusercontent.com/56722184/73627118-57c03e00-4686-11ea-8b77-4b58c8d4904f.png">

<img width="357" alt="image" src="https://user-images.githubusercontent.com/56722184/73627358-56dbdc00-4687-11ea-8227-085cc2645c12.png">

<img width="363" alt="image" src="https://user-images.githubusercontent.com/56722184/73627393-812d9980-4687-11ea-88ee-af60c812d0c7.png">
