### ISSUE TITLE
General: Issues with custom scroll bar colors

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3413]
**Describe the bug**
The color changes done on #3007 caused the custom scrollbars on windows to go awry and look strange. 

**To Reproduce**
1. Open windows 10 - chrome
2. Go to http://localhost:4000/components/datagrid/example-frozen-columns.html?
3. Look at the scroll bars

**Expected behavior**
Scrollbars should look decent in windows - chrome

**Version**
- ids-enterprise: [e.g. v4.26]

**Screenshots**
![Screen Shot 2020-01-30 at 11 12 46 AM](https://user-images.githubusercontent.com/814283/73477239-def97300-4361-11ea-939a-1047f67c4f74.png)

**Platform**
 - Chrome / Windows

**Comment by brianjuan** [comment]
Hi @tmcconechy, I just want to clarify which one is correct?
In Windows Chrome and Windows Chrome Edge, the scroll bar looks like this:
![image](https://user-images.githubusercontent.com/39508864/73522459-65d24c80-4443-11ea-93d4-cae0a7fc1451.png)

And in Windows IE, Edge and Firefox, the scroll bar looks like this:
![image](https://user-images.githubusercontent.com/39508864/73522566-a9c55180-4443-11ea-9f40-7ac8888c6cac.png)

I'm doing page reload as per the instruction in PR.

Tested in:
http://4251-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html?theme=uplift&variant=light
and http://master-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html?theme=uplift&variant=light

**Comment by tmcconechy** [comment]
They are both correct. Chrome is the only browser that can customize the scrollbar. So it only works there. However, we may decide in the future to shelf this change for consistency. But for now its correct.
