### ISSUE TITLE
Datagrid: Render issues with frozen columns and column.colspan function

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3416]
Describe the bug
Datagrid render issues when the grid has both frozen columns and column.colspan custom function defined. This pattern is abundantly used in Landmark.

To Reproduce
1. Using the attached example-frozen-columns-with-colspan.html
2. Notice the rendering issues with the rows
3. Within the example-frozen-columns-with-colspan.html comment out the frozenColumns grid option
4. Notice how the rows and columns data is aligned

Expected behavior
Colspan should work with or without frozen columns

Version
v4.26.0-dev

Screenshots
Datagrid using colspan function without frozen columns

![image](https://user-images.githubusercontent.com/39804038/73493958-60a8cb00-4379-11ea-8e30-4038eca960ee.png)

Same example but adding Select Checkbox and Product Type as frozen columns

![image](https://user-images.githubusercontent.com/39804038/73494061-8209b700-4379-11ea-96cd-7b237e2d7cc5.png)

**Comment by claudenbach** [comment]
[Git-3416.zip](https://github.com/infor-design/enterprise/files/4136451/Git-3416.zip)

**Comment by claudenbach** [comment]
Landmark example with colspan and frozen column (first two columns are frozen)

![image](https://user-images.githubusercontent.com/39804038/73495694-a74bf480-437c-11ea-936d-cd8f7baf6608.png)

**Comment by claudenbach** [comment]
Same example with colspan but without frozen columns

![image](https://user-images.githubusercontent.com/39804038/73495792-de220a80-437c-11ea-97d4-ed3ae94e80a9.png)

**Comment by tmcconechy** [comment]
Need to hold on this until https://github.com/infor-design/enterprise/pull/3646 is merged and tested. (shouldnt be too long)

**Comment by jbrcna** [comment]
**QA FAILED**
v4.27.0-beta0
Safari
https://4270-beta0-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-with-colspan.html
![image](https://user-images.githubusercontent.com/56722184/77717411-62aaa580-701b-11ea-820e-5cf2f9afefc2.png)

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. Thank you. 

![image](https://user-images.githubusercontent.com/45757016/78344542-1d641600-75cf-11ea-80ba-f1d05715b4eb.png)
