### ISSUE TITLE
The textarea formatter is not the expected height when the row height is set to 'Short' or 'Medium''

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#3417]
**Describe the bug**
The textarea formatter is not the expected height when the row hieght is not set to 'Normal', eg. Short or Medium

**To Reproduce**
1. Go to 'http://localhost:4000/components/datagrid/test-editable-long-text.html'
2. Set the row height to 'Short'
3. Edit the Product Id in the second row 

**Expected behavior**
Single lined textara formatters should be the correct size that matches the row height. This works as expected when the row height is set to normal. 

**Version**
v4.26.x

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/73501527-1a557980-4416-11ea-83df-c6e6bc35e97b.png)

**Platform**
 - OS Version: Windows 10 
 - Browser Name: chrome

**Additional context**
There are other issues with the textarea editor, but they should be done as part of #1643

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.
Verified in http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift&variant=light

**Comment by janahintal** [comment]
The issue still exists upon checking. Thanks. 
![image](https://user-images.githubusercontent.com/45757016/74016080-cbd34c80-49cc-11ea-86e9-28fe9fac6d60.png)

**Comment by tmcconechy** [comment]
@janahintal you have a point here  but I'm not sure what we want to do about it. What do you think @marknolaninfor . Maybe center the editors?

![Screen Shot 2020-02-07 at 12 53 27 PM](https://user-images.githubusercontent.com/814283/74052943-d976db00-49a8-11ea-84c9-260c1e08d5fb.png)

**Comment by tmcconechy** [comment]
Going to descope the position of the editors for the time being.

**Comment by marknolaninfor** [comment]
The original displayed value was shown in the center, so should the editor also show in the center. The user would tap/click on the center to edit. So the question then is would they expect the field/control to then move to the top or the row or stay in the same place?

I would think that it should stay where the formatter displayed the value. Also agree that it should be descoped from this change.
