### ISSUE TITLE
Busy Indicator (ng): Overlay doesn't show when BI is triggered after modal close

### ISSUE THREAD

**Issue by shane-infor** [infor-design/enterprise#3424]
**Describe the bug**
If you have a busy indicator on a page and also a modal, opening busy indicator after modal close actually closing the busy indicator overlay.

**To Reproduce**
1. Create a BI in a page.
2. Create a button that opens a modal.
3. Create a function is trigger the BI in the page after modal close.
4. Open the modal.
5. Close the modal which will open the BI.
6. You can see the BI opens without overlay.

**Expected behavior**
BI should open with overlay.

**Version**
Soho ng 6.4.0

**Screenshots**
![2020-02-03_10-35-34](https://user-images.githubusercontent.com/54695843/73617286-1c674480-4671-11ea-8c2f-c3c5828051dd.gif)

**Platform**
Windows 10 Firefox

**Comment by tmcconechy** [comment]
Did you have an example you made with all this created in it?

**Comment by shane-infor** [comment]
Hi Tim, 

I managed to create a sample app from the quick-start project and I have attached herewith.
The issue here is that if we call `modal.close();` after triggering the `this.openBusyIndicator();`, the BI is opening without the overlay. The workaround is close modal first but closing modal should not close BI overlay though.

Cheers,
Shane

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to Done column.
