### ISSUE TITLE
Swaplist: Left and Right arrow buttons are displaced in Firefox 

### ISSUE THREAD

**Issue by kalvinfive** [infor-design/enterprise#3425]
**Describe the bug**
When viewing the swaplist in Firefox the left and right arrow buttons are not aligned with the swaplist titles

**To Reproduce**
1. Open Firefox browser
2. Go to swaplist [sample page](https://design.infor.com/code/ids-enterprise/latest/demo/components/swaplist/example-index)
3. Swaplist arrow buttons are not aligned

**Expected behavior**
The arrow buttons should be aligned with the swaplist titles

**Version**
IDS Enterprise Components - v4.25.1

**Screenshots**
![image](https://user-images.githubusercontent.com/12707364/73620161-88df4500-466b-11ea-9a83-2d302338ca62.png)

**Platform**
Windows 10 Firefox

**Comment by CindyMercadoReyes** [comment]
This issue was tested across browsers and devices. This issue is now resolved. 
However, a new issue was logged.
GitHub ticket: https://github.com/infor-design/enterprise/issues/3452
