### ISSUE TITLE
Dropdown - SelectValue() api method is not working as expected

### ISSUE THREAD

**Issue by spikeeedge** [infor-design/enterprise#3432]
**Bug**
SelectValue() method of Dropdown api is not working as expected. 
The method call doesn't change the value on screen.

**To Reproduce**
* Make sure to run 4.26.0-dev 
1. Go to 'http://localhost:4000/components/dropdown/example-setvalue.html'
2. Click on 'Update' button
3. Notice the dropdown is not showing the updated value.
4. As soon as you click on dropdown(without making any selection) will change the text and set it to correct value supplied in SelectValue() method.

**Expected behavior**
Dropdown should select and show the correct value supplied in SelectValue() method of api.

**Version**

- 4.26.0-dev

**Screenshots**
See the video below -

![Soho - Dropdown selection issue](https://user-images.githubusercontent.com/11339925/73699587-1dad7580-4734-11ea-9c24-ebc3ee447c74.gif)

**Platform** 
 - OS Version: Windows 10
 - Browser Name: Opera
 - Browser Version: 66.0.3515.44 (Windows 10 64-bit)

**Additional context**
The feature was working as expected before. Possibly broken with the changeset f6128a31cc4f35b642a84aeb44ddb01d73e31a26

**Comment by tmcconechy** [comment]
Also seems like this test page http://latest-enterprise.demo.design.infor.com/components/dropdown/test-change-value.html test is not working.

**Comment by janahintal** [comment]
The issue is now resolved. Thank you. 
Verified in http://master-enterprise.demo.design.infor.com/components/dropdown/example-setvalue?theme=uplift&variant=light
