### ISSUE TITLE
Colorpicker: Dirty Tracking in uplift theme is not aligned  when changing theme

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3433]
**Describe the bug**
Colorpicker  Dirty Tracking in uplift theme is not aligned 

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/colorpicker/test-states?theme=uplift&variant=contrast
2. Switch to Uplift theme 

**Expected behavior**
The dirty tracker icon should be aligned

**Version**
DEV 4.251

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/73724827-28353280-4767-11ea-992b-c705de76f670.png)

**Platform**
All platform Mobile, web and OS. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
We would need to dynamically move the dirty indicator or do it with out JS so it works with themes.

**Comment by tmcconechy** [comment]
Can no longer reproduce this issue.
