### ISSUE TITLE
Datagrid: Some columns disappear in datagrid with filter after resizing the browser

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3434]
**Describe the bug**
Datagrid: Some columns disappear in datagrid with filter after resizing the browser and after changing Themes, Variants or Colors.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
2. Resize to smaller browser size
3. See issue: Last column "Price" disappears
4. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html
5. Resize to smaller browser size
6. See issue: Last column "Product Name" disappears

Another case likely the same issue
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging.html?theme=soho&variant=light
1. FIlter Price = 0.99
1. Change theme to Vibrant

**Expected behavior**
Columns should not disappear after resizing the browser or after changing Themes, Variants or Colors.

**Version**
- ids-enterprise: v4.26.0-dev

**Screenshots**
http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
![image](https://user-images.githubusercontent.com/39508864/73737187-1c546b00-477d-11ea-80ba-a1358ab3c066.png)

http://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html
![image](https://user-images.githubusercontent.com/39508864/73737366-735a4000-477d-11ea-906c-63be1fa93fd0.png)

**Platform**
 - All Devices, OS and browsers.

**Additional context**
Issue also happens when changing Themes, Variants or Colors.

**Comment by tmcconechy** [comment]
Probably a demo app issue and nothing major but do want to investigate

**Comment by tmcconechy** [comment]
Concerned about this so taking a look next

**Comment by tmcconechy** [comment]
Letting anyone grab this just in case i dont get to it right away.

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html and https://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html. Will retest in beta once deployed.
