### ISSUE TITLE
General: Combine isInViewport to a shared utils

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3436]
**Is your feature request related to a problem? Please describe.**

Found two occurances of isInViewport. Also some folk would like this util to use. So extract it into a util and refactor the code

**Describe the solution you'd like**

- [ ]  Take isInViewport out of popupmenu
- [ ]  Take isInViewport out of datagrid
- [ ]  Put it in utils

**Describe alternatives you've considered**
Leave it

**Additional context**
Ms Teams Chat

**Comment by jbrcna** [comment]
**QA Passed** with some observation

https://master-enterprise.demo.design.infor.com/components/dropdown/test-on-modal.html
Safari:
![image](https://user-images.githubusercontent.com/56722184/79762368-4289b000-8355-11ea-84ab-eecb54ea1915.png)

![image](https://user-images.githubusercontent.com/56722184/79762699-ac09be80-8355-11ea-87aa-eb690844b749.png)

**Comment by tmcconechy** [comment]
Thanks @jbrcna lets ignore that for now

**Comment by jbrcna** [comment]
Copy that @tmcconechy . Cheers!
