### ISSUE TITLE
Lookup Functional and E2E Tests

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#344]
Add some tests for Lookup

See existing tests for example textarea, dropdown, treemap, menubutton for reference. Also see docs/TESTING.MD for commands. Ask for help on sohoxi-dev if needed.

Functional Tests
- Test events that get triggered
- Test events that are listened to
- Test all API methods, most importantly the public ones first and the rest for coverage. (fx enable/disable)
- Test lifecycle methods (init, teardown, destroy, invoke)
- Test setting and that some states are applied

E2e Tests
- Load each test page in the components/<name>/list and test the main ideas of the page, if unsure of the main idea ask on the channel.
- Keyboard

Lookup Specific Test Considerations 
- custom buttons on the lookup
- changing toolbar
- editing in the field
- editing in the lookup
- rendering a filter row
- single vs multiselect
- autoWidth option
- events (fx before open)
- block opening
- custom click function
- matching
- changing delimiter
- auto apply
- states
- validation on the buttons
- on a cap
- on a modal
- server side paging vs client side paging
- setting selected values

Other Tests
- Accessibility tests https://github.com/dequelabs/axe-core
- Security Tests XSS
- Other Specific Test Cases from Cindy
- Protractor Image Comparison Tests

**Comment by CindyMercadoReyes** [comment]
QA verified. Moving this ticket to QA Done.
