### ISSUE TITLE
Bullet: Add axis formatting like other charts

### ISSUE THREAD

**Issue by MadhaviDasika** [infor-design/enterprise#3447]
**Is your feature request related to a problem? Please describe.**
At present bullet chart on a high numbered intervals where there is huge gap between data set ranges shows scale with messy numbers.

**Describe the solution you'd like**
We need formatting the bullet chart scale as its done for column chart.

**Describe alternatives you've considered**
Could try and pre-process the data or limit data points

**Additional context**
Bullet:
![image](https://user-images.githubusercontent.com/24714335/73924628-ce617380-48f2-11ea-8ede-179fe23dc5ea.png)

Column:
![image](https://user-images.githubusercontent.com/24714335/73924665-de795300-48f2-11ea-9af3-322a1760c7da.png)

**Comment by tmcconechy** [comment]
@MadhaviDasika could you attach the data and settings you  are passing to the bullet chart in your example so we can reproduce this?

**Comment by MadhaviDasika** [comment]
Sample data set
chartDataset = [{
                                                data: [
                                                            {
                                                                        title: "Feb 17, 2020",
                                                                        ranges: [1000000, 0, 1000000],
                                                                        measures: [0],
                                                                        markers: [0]
                                                            }
                                                ],
                                                barColors: ["#D8D8D8", "#368AC0", "#69B5DD"],
                                                lineColors: ["#00000000", "#00000000", "#00000000"],
                                                markerColors: ["#000000"]
                                    }]; 

![image](https://user-images.githubusercontent.com/24714335/74237746-44524a00-4cfa-11ea-8b79-2076071b9d51.png)

**Comment by janahintal** [comment]
Hi @tmcconechy 
I was able to test in https://master-enterprise.demo.design.infor.com/components/bullet/example-format.html and it seems working fine. However, I was not able to test it in https://4270-beta0-enterprise.demo.design.infor.com/components/bullet/test-formate-axis.html as stated in PR because the page is not yet deployed it beta.

**Comment by tmcconechy** [comment]
The link is typed wrong @janahintal please look at https://4270-beta0-enterprise.demo.design.infor.com/components/bullet/example-format.html (instead of test-formate-axis.html)

**Comment by janahintal** [comment]
Thanks, Tim. Will now move the ticket to Done.
