### ISSUE TITLE
Tooltip not appearing on the toolbar's more button when the more button is created programmatically.

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#345]
**Describe the bug**
The 'More' tooltip isn't showing up on for the more actions button on a toolbar when the button is created programmatically. This is because the button isn't initialized before the button invoking loop.

**To Reproduce**
1. Go to [toolbar/example-index.html](http://480-sohoxi.demo.design.infor.com/components/toolbar/example-index.html)
2. Hover over the  '...' button in the blue header. You should see the more tooltip appear.
3. Hover over the  '...' button in the regular toolbar in the contents area. 
4. No tooltip appears

**Expected behavior**
The more tooltip should appear for any more actions button on a toolbar, no matter if it's created programmatically or in the html.

**Screenshots**
Working in header:
![image](https://user-images.githubusercontent.com/22107636/42650176-54291e14-85d1-11e8-80cd-db4b504561f5.png)
since the `<div class="more">` exists:
![image](https://user-images.githubusercontent.com/22107636/42650221-6f2dbab2-85d1-11e8-84c6-f5ab84f922a8.png)

Not working in regular toolbar:
![image](https://user-images.githubusercontent.com/22107636/42650243-807dedb4-85d1-11e8-95c2-a7136fa53a4b.png)
since the `<div class="more">` doesn't exist:
![image](https://user-images.githubusercontent.com/22107636/42650274-93eb9e64-85d1-11e8-8e6c-342faf0f76e7.png)

**Platform**
 - All

**Comment by brianjuan** [comment]
Performed testing of this on all browsers.
Bug fix is working as expected, see screenshot below.
![image](https://user-images.githubusercontent.com/39508864/42859131-3f66ba6a-8a20-11e8-9e94-738ad61ce3fa.png)
