### ISSUE TITLE
Swaplist: Overlapping view on uplift theme on dark contrast

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3452]
**Describe the bug**

**To Reproduce**
1. Go to url: http://localhost:4000/components/swaplist/example-index.html?theme=uplift&variant=dark
2. The UI is on uplift theme with dark contrast. 
3. The Available and Selected columns look like they are overlapping each other.  This only looks this was on uplift/dark contrast. Please screen shot attached. 
Found this issue when testing GitHub ticket: https://github.com/infor-design/enterprise/issues/3425
4. The UI should not look like it's overlapping each other on dark contrast. 

**Expected behavior**
The UI should not look like it's overlapping each other on dark contrast. 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![swtichbox overlap on dark contrast](https://user-images.githubusercontent.com/39101346/73975240-eb4a7680-48f3-11ea-91a7-326b60deefdb.png)

**Platform**
 - All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
I think we should try removing inside border radius's so these join. Or at least have the outside only have the box shadow

**Comment by janahintal** [comment]
QA Passed. The issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/swaplist/example-index.html?theme=soho&variant=contrast across all platforms, theme and variants.
