### ISSUE TITLE
AppMenu - Both arrows flip when you click either one of them when search filter is used

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3454]
**Describe the bug**
accordion headers that match the filter flip simultaneously.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html
2. Type 'My' into the input. Notice that "My Account" and "My Roles" are shown. Neither of the headers' children are displayed and they should remain hidden if clicked since they don't match the filter.
3. Click on the arrow of the accordion

**Expected behavior**
the arrows should only flip when you click them. 

**Version**
v4.26.0-dev

**Screenshots**
![Large GIF (1176x532)](https://user-images.githubusercontent.com/56722184/74022106-cdeed880-49d7-11ea-95a5-6cba07cc10c0.gif)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Going to just close this as not worth fixing. It is doing the right thing, its just that there is no active children shown when you expand. So nothing in correct here...
