### ISSUE TITLE
Locale: Unable to set language to "nb"

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#3455]
**Describe the bug**
When using the API `Soho.Locale.setLanguage()` and passing "nb", a maximum call stack size exceeded error is encountered and the language does not get changed to Norwegian (Bokmål). 

`jquery-3.4.1.js:757 Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at Function.Sizzle [as find] (jquery-3.4.1.js:757)
    at jQuery.fn.init.find (jquery-3.4.1.js:2896)
    at new jQuery.fn.init (jquery-3.4.1.js:3006)
    at jQuery (jquery-3.4.1.js:152)
    at Object.updateLanguageTag (locale.js:96)
    at Object.setCurrentLocale (locale.js:471)
    at Object.set (locale.js:375)
    at locale.js:435
    at fire (jquery-3.4.1.js:3291)`

It seems that "nb" is not accepted, even though there's a locale "nb-NO". Passing any random, non-supported string will result in the same error.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/about/example-index
2. Open Developer console
3. Perform `Soho.Locale.setLanguage("nb")` 
4. See error in console. Language does not change.

**Version**
- ids-enterprise: v4.25.0

**Comment by tmcconechy** [comment]
WIll fix with #3244 next

**Comment by jbrcna** [comment]
The issue is now resolved. tagging this ticket as Passed and Done
https://master-enterprise.demo.design.infor.com/components/about/example-index
v4.26.0-dev
![image](https://user-images.githubusercontent.com/56722184/74523738-a8724980-4f58-11ea-9fc0-e4d60020bf9e.png)
