### ISSUE TITLE
Fileupload: Modal dialog can disappear when tabbing 

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#3458]
**Describe the bug**
When a file upload control is used on modal dialog and there are sufficient (many) fields, tabbing through the file upload control will cause the modal dialog to disappear or cause it to partially display.

The test below has been modified to have additional fields on the modal.
[test-fileupload.zip](https://github.com/infor-design/enterprise/files/4171976/test-fileupload.zip)

**To Reproduce**
1. Unzip the above file and replace \app\views\components\modal\test-fileupload.html 
2. Go to http://localhost:4000/components/modal/test-fileupload.html
3. Click on the Show Modal button
4. The modal should display and focus should be in the first field
5. Using the tab key, tab through all the fields; the file upload field is the last field
6. Modal dialog disappears when tabbing out of the file upload field
7. Shift-tab will cause the modal to reappear, although it is not placed correctly on the screen

**Expected behavior**
Expect the first button of the dialogs buttons to receive focus next.

**Version**

- ids-enterprise: 4.25.1

**Screenshots**
![file-upload-tab-index-issue](https://user-images.githubusercontent.com/20212079/74048256-80527b80-4997-11ea-8651-e1ad8600902e.gif)

**Platform**
 - all

**Additional context**

**Comment by fitzorama** [comment]
@tmcconechy We will need a patch for 4.25.1.

**Comment by tmcconechy** [comment]
@fitzorama created a 4.25.2 with this fix and a corresponding 6.4.2 release of NG. Both now in npm

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in http://master-enterprise.demo.design.infor.com/components/modal/test-fileupload-scroll.html. Will retest once beta is deployed.
