### ISSUE TITLE
Datepicker: disable a year within the min/max date range

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#3462]
**Is your feature request related to a problem? Please describe.**
The datepicker enables a min and max date to be defined, plus additional days, of week, and/or dates to be added, so they are not selectable. 

We have a case where the year 2018 and 2020 are allowed, but not 2019. The current control requires that the min and max are defined to allow 2018 and 2020, but then every day for 2019 has to be added as a disabled date.
```
disable: {
    dates: [],
    minDate: '',
    maxDate: '',
    dayOfWeek: [],
    isEnable: false,
    restrictMonths: false
  },
```

**Describe the solution you'd like**
Could year(s) be disabed by adding a years array?

**Describe alternatives you've considered**
Adding every single date for a year to disable it seams like way too many dates.

**Additional context**
Our system requires that a user defines what years the calendar is avaliable, and not what years are disabled. An enable list may work better with our solution.

**Comment by tmcconechy** [comment]
Seems like a year array would make sense for this use case. Cant think of anything else  without a lot of days. Or what about a custom function?

**Comment by marknolaninfor** [comment]
A custom function may work best, as we could write our own logic that matchs the current functionality. This will then allow us to only enable the years that the customer has define instead of enabling an range and then removing the non-active years.

The custom function privides the most flexability.

**Comment by jbrcna** [comment]
The issue is now resolved. Will retest once Beta is deployed. Thank you
verified in master v4.28.0-dev

**Comment by CindyMercadoReyes** [comment]
Including BDD
[story_github#3462.docx](https://github.com/infor-design/enterprise/files/4516502/story_github.3462.docx)
