### ISSUE TITLE
Locale: Correct Russian date and month names

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3464]
**Describe the bug**
Testers have noted that some corrections are needed in ru-RU

**To Reproduce**
1. Go to http://localhost:4000/components/datepicker/example-index.html?locale=ru-RU
2. Open the calendar and look at the months
3. See error

**Expected behavior**
Months are now `  wide: ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря']`
But they should be `names: ["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь",""],
				`

Also the day names should be in caps.

**Version**
- ids-enterprise: [e.g. v4.25.2]

**Comment by janahintal** [comment]
QA Passed. Verified in https://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=ru-RU 
![image](https://user-images.githubusercontent.com/45757016/74531822-ac0dcc80-4f68-11ea-86e7-ce080919c51a.png)
