### ISSUE TITLE
Editor: underline or strike through formats not being removed correctly

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3467]
**Describe the bug**
When you have used both Strike through and underline only one of them is removed after unselecting them.

**To Reproduce**

1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index.html'
2. Select the second paragraph
3. Click the 'bold', 'Italic', 'Underline' and 'strike through' buttons => The section now has all those stylings
4. Click the end of that paragraph to unselect the text
5. Click Enter => Another paragraph is added with all those styling
6. Click the 'bold', 'Italic', 'Underline' and 'strike through' buttons again
Expected result?: All format buttons are now displayed as not used 
Actual result: All buttons are still blue (Perhaps this is a known limitation?) 
7. Start writing
Expected result: No format is applied
Actual result: One of the formats underline or strike through are still applied (strike through if I unselected it before underline otherwise underline)

**Expected behavior**
All formats (Including both underline and strike-through) should be removed if all have been un-selected.

**Version**

- ids-enterprise: v. 4.23 (but also reproducible in 4.25.2)

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/74227468-ce7cbd00-4cbe-11ea-94ce-716663ac90fe.png)

**Platform**
 - OS Version: Win 10
 - Browser Name: Chrome
 - Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
-

**Comment by tmcconechy** [comment]
This is possibly hard to fix. Lets see. Also not so sure people will use that full combination.

**Comment by SofiK** [comment]
For us I think it would be ok to close this one as a known issue.

**Comment by tmcconechy** [comment]
OK, lets descope for now. Too complicated
