### ISSUE TITLE
Datepicker/Timepicker: When using Norweigan as locale both : and . is used as time separator

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3468]
**Describe the bug**
I think it should be consistent and use ":" as separator in both the input field and in the dialog, currently the separator is ":" in the input field and "." in the dialog

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/timepicker/example-index.html?locale=nb-NO' or 'https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=nb-NO'
2. Click on the date/time picker
3. Notice that there is a "." as separator for the time in the dialog
4. Select a time and click apply
5. Notice that the time is still shown with a "." 
6. Unfocus the field
7. Notice that there is a ":" as separator for the time

**Expected behavior**
I'm not certain if it should be a "." or a ":", I think both are used in Norway. But I think it should be the same in all places.

**Version**

- ids-enterprise: 4.23.0 but also reproducible in 4.25.2

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/74248262-98076800-4ce7-11ea-8dcf-3bbfc257f97d.png)

**Platform**
 - OS Version: Win 10
 - Browser Name: Chrome
 - Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
-

**Comment by tmcconechy** [comment]
I think this should be a dot in both cases looking around https://www.babbel.com/en/magazine/how-to-write-the-date-in-norwegian http://www.unicode.org/cldr/charts/28/verify/dates/nb.html

Will fix this with some locale changes im making now

**Comment by SofiK** [comment]
Windows seems to be using : though
![image](https://user-images.githubusercontent.com/8664975/74248796-6fcc3900-4ce8-11ea-8a06-8854126ba511.png)

**Comment by tmcconechy** [comment]
Ok, good call. I actually did mean the date format. But the time format should be : 
Lets go with windows being correct 👍

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=nb-NO. Will retest once beta is deployed.
![image](https://user-images.githubusercontent.com/39508864/74516356-36473800-4f4b-11ea-909b-8e9dca23e957.png)
