### ISSUE TITLE
Datepicker: Korean doesn't work in datepicker

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3470]
**Describe the bug**
When I select a time in the datepicker (Or click Today) and then unfocus the field the field becomes invalid.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=ko-KR'
2. Click on the calendar icon in the second field
3. Click Today
4. Click outside the field (not in another field, for some reason it doesn't validate then)
5. Notice that it becomes invalid.

**Expected behavior**
The field should keep the format (or have the correct format which I do not know) and it should not be invalid

**Version**

- ids-enterprise: 4.23 but reproducible in 4.25.2

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/74251772-ec611680-4cec-11ea-8f7f-65125a95be28.png)

**Platform**
 - OS Version: Win 10
 - Browser Name: Chrome
 - Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
-

**Comment by janahintal** [comment]
QA Passed. Korean is now working and verified in https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?theme=uplift&variant=contrast&locale=ko-KR across all platform. Thank you.
