### ISSUE TITLE
Textarea: Not honoring rows attribute

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#3471]
**Describe the bug**
The rows attribute on a textarea is not being honored.

The test below has been modified to have an example for the rows attribute.
[example-index.zip](https://github.com/infor-design/enterprise/files/4186535/example-index.zip)

**To Reproduce**
1. Unzip the above file and replace \app\views\components\textarea\example-index.html
2. Go to http://localhost:4000/components/textarea/example-index.html
3. The textarea with the label Notes (7 rows) displays the same height as all of the other textareas when it should be taller

**Expected behavior**
The textarea should honor the rows attribute

**Version**

- ids-enterprise: 4.25.2

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/74252430-4e9d2580-4cb3-11ea-97b8-f6569286dbd8.png)

**Platform**
 - All

**Comment by fitzorama** [comment]
@tmcconechy we would like a patch for 4.25.2 please.

**Comment by tmcconechy** [comment]
We didnt really claim to support this. But adding an example and test for it. For previous versions to work you just need to add one CSS rule...

```
textarea[rows] {
  height: auto;
}
```

Perhaps not worth a full patch unless we have other fixes? Can you work with adding that for now? Will PR this soon.

**Comment by jbrcna** [comment]
The issue is now resolved. 
v4.26.0-dev
https://master-enterprise.demo.design.infor.com/components/textarea/example-autogrow.html
![image](https://user-images.githubusercontent.com/56722184/74525150-6b5b8680-4f5b-11ea-913d-479b81d53515.png)
