### ISSUE TITLE
Datepicker: Chinese cannot be used in datepicker with time

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3473]
**Describe the bug**
When I select a time in the datepicker (Or click Today) and then unfocus the field the field becomes invalid.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=zh-CN' or 'https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=zh-TW'
2. Click on the calendar icon in the second field
3. Click Today
4. Click outside the field (not in another field, for some reason it doesn't validate then)
5. Notice that it becomes invalid.

**Expected behavior**
The field should keep the format (or have the correct format which I do not know) and it should not be invalid

**Version**

- ids-enterprise: 4.23 but reproducible in 4.25.2

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/74255706-8d060500-4cf2-11ea-9f3e-7c981409efd1.png)

**Platform**
 - OS Version: Win 10
 - Browser Name: Chrome
 - Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
This issue can be related to https://github.com/infor-design/enterprise/issues/3470
All these 3 language codes (ko-KR, zh-Ch and zh-TW) gets the same error.

**Comment by jbrcna** [comment]
**QA PASSED with observation**
The issue is now resolved. v4.27.0-dev
verified in https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=zh-TW
In `Safari` Browser the font in menu looks different.
![image](https://user-images.githubusercontent.com/56722184/76412653-edaa5f80-63ce-11ea-9aeb-5a58da9ce02f.png)

**Comment by tmcconechy** [comment]
This is correct @jbrcna for your info. Some fonts like chinese need to be in a special font to show all the characters so we make that adjustment.
