### ISSUE TITLE
Datepicker: AM/PM doesn't work correctly for locale hi-IN

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3474]
**Describe the bug**
When I try to switch between AM and PM in Hindi it changes back to a value dependent on the time. 

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=hi-IN'
2. Click on the calendar icon for the second datepicker that will use the time 12:00
3. For the am/pm dropdown select the first option
4. Click The apply button
5. Notice that the time is still shown correctly with the correct am/pm option
6. Click outside of the field
7. Notice that the am/pm value changes (Expected result: The value is not changed)
8.  Click on the calendar icon for the third datepicker that will use the current time
9. For the am/pm dropdown select the second option
10. Click the apply button
11. Notice that the time is still shown correctly with the correct am/pm option
12. Click outside of the field
13. Notice that the am/pm value changes (This could perhaps depend on if it is currently am or pm time? I'm in pm for my time zone when testing?) (Expected result: The value is not changed)

**Expected behavior**
The am/pm value should not change in step 7 and 13

**Version**

- ids-enterprise: Found in v 4.25.2

**Screenshots**
![Testing datepicker hi-IN](https://user-images.githubusercontent.com/8664975/74259406-21bf3180-4cf8-11ea-9103-198a47b45472.gif)

**Platform**
 - OS Version: Win 10
 - Browser Name: Chrome
 - Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)

**Additional context**
-

**Comment by jbrcna** [comment]
**QA PASSED**
The issue is now resolved. v4.27.0-dev
verified in https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=hi-IN
