### ISSUE TITLE
EmptyMessage: Text needs to be more subtle

### ISSUE THREAD

**Issue by jamie-norman** [infor-design/enterprise#3476]
**Is your feature request related to a problem? Please describe.**
In general, the empty state messaging beneath the icons is too heavy, being displayed in 2.2rem source sans semibold. What we're seeing is that empty states often call too much attention to themselves and pull the eye away from more meaningful or priority information

**Describe the solution you'd like**
Consider either lightening the text color, maybe .7 opacity and/or make the font weight regular with similar lightening or decrease in opacity

![image](https://user-images.githubusercontent.com/44705854/74276184-df3b2c00-4cda-11ea-9160-944450378283.png)

**Comment by tmcconechy** [comment]
cc @kentonquatman @kevinwhitedesign

**Comment by jamie-norman** [comment]
Could be simple as adding the Source Sans Ultra Light or Light to the stack...
![image](https://user-images.githubusercontent.com/44705854/74276578-989a0180-4cdb-11ea-878f-07d1f4d62946.png)

**Comment by tmcconechy** [comment]
Maybe a color change or font-weight change? Adding another download for the font seems like it would cut some performance. If we can avoid downloading a new font-set would like to do that.

**Comment by jamie-norman** [comment]
Fair. Somewhere between 40-60% opacity could work. 
![image](https://user-images.githubusercontent.com/44705854/74277076-810f4880-4cdc-11ea-80f5-446996443282.png)

**Comment by kentonquatman** [comment]
![Screen Shot 2020-02-11 at 3 52 05 PM](https://user-images.githubusercontent.com/847306/74278115-ad2fc700-4ce6-11ea-9631-b775729245cd.png)

I took a look at this using the card example on the IDS website and noticed that the card titles and empty messages are using type sizes from the outdated type scale. This will be a good opportunity to fix a few items at once.

- Card title: reduce to 20 (2.0rem)
- Empty message: reduce to 16 (1.6rem), change to Slate-06 (#606066)

**Comment by kentonquatman** [comment]
@jamie-norman Let me know if that proposed would work for your use case or if it still to heavy on the page.

**Comment by jamie-norman** [comment]
@kentonquatman Yes, I think that could be an option. We don't seem to use the secondary text in most case.

**Comment by jamie-norman** [comment]
@tmcconechy Still planning on this one for April? At least one solution consultant noted that an empty state appeared to him like an error. I suspect some of that has to do with their visual weight, so hoping the proposed solution will find a better balance between an alert and something more informational. It will also be a change cycle for folks that are used to the old empty states, which were just text in the list footer.

**Comment by tmcconechy** [comment]
I put this in the end of the april (next sprint). But we can move it. What is the proposed solution though? I think that needs clarification...

**Comment by jamie-norman** [comment]
I don't think we need to rush or re-prioritize. But I agree, we need some clarity. @kevinwhitedesign do we want to make a design decision?

**Comment by kevinwhitedesign** [comment]
@jamie-norman Yeah I see this issue pretty clearly. This 'empty state' component was started with the intention that there would be titles, descriptions and actions. So just having the title throws off the visual weight here, we probably should have designed this with one-line from the beginning. I'll get to an example tomorrow.

**Comment by kevinwhitedesign** [comment]
It looks like we're really emphasizing 'No Data Available' across the board here, while landmark probably has a slew of these instances. I wonder if it would be of interest to swap the title for body text here to achieve a more subtle description of what's going on? Thoughts @tmcconechy @jamie-norman ?
![icon-typelockup](https://user-images.githubusercontent.com/6478704/78164411-b7815e00-7417-11ea-9166-792c562909de.png)

**Comment by tmcconechy** [comment]
Works for me. Can you show the suggestion with the optional additional informational text? Also is the icon the same size or should we reduce that (feel like its pretty big = emphasis)

**Comment by jamie-norman** [comment]
Not sure I follow, Kev. Are you suggesting in your example above that "Data Lake" becomes "No data Available?"
Also agree with Tim that reducing the size of the empty state icon seems reasonable too.

**Comment by kevinwhitedesign** [comment]
One caveat was I had an icon size that was larger than Tim's production code. I had 150, he had 100. Now that that's cleared up:

I went down to 80px. This feels appropriate to me. 

@jamie-norman data lake was just a silly filler text for the card title. 
![empty-state-typography](https://user-images.githubusercontent.com/6478704/78173664-0c2bd580-7426-11ea-9d24-e04d1c27f3a7.png)

**Comment by tmcconechy** [comment]
Looks much better to me.

**Comment by jamie-norman** [comment]
@kevinwhitedesign Gotcha. I like those options—definitely in line with what I was thinking. The outlines of the icon itself could even be lighter.

**Comment by kevinwhitedesign** [comment]
Yep, something was wrong with my svgs actually. Fixed.

![empty-state-typography-2](https://user-images.githubusercontent.com/6478704/78182162-a5adb400-7433-11ea-87be-81ee88ee1b43.png)

**Comment by jbrcna** [comment]
QA Passed.
v4.28.0-dev
