### ISSUE TITLE
ESC key should dismiss the role switcher in Landmark Applications

### ISSUE THREAD

**Issue by jamie-norman** [infor-design/enterprise#3477]
Would be great if the escape key dismissed the role switcher dropdown in LMK. Low level ask here, but seems to be expected behavior.

![image](https://user-images.githubusercontent.com/44705854/74276345-29bca880-4cdb-11ea-8529-3029b5277708.png)

**Comment by jamie-norman** [comment]
also, our titles should fit better than that. Likely a separate issue...

**Comment by janahintal** [comment]
This issue is now working well in MacOS and Windows (Chrome, Edge FF) browsers but **Failing in Windows 10 IE11 browser.**

**Comment by tmcconechy** [comment]
Lets skip this IE 11 issue for now since we are slowly descoping IE 11 and this is minor. Moving to done
