### ISSUE TITLE
Optimize Travis Builds

### ISSUE THREAD

**Issue by d-g-h** [infor-design/enterprise#348]
**Describe the bug**
Travis can run tests in parallel. Use  `- matrix` in the .travis config to run functional, and e2e tests
Travis should fail immediately if `npm run build` fails, and exit with a non-zero exit code

**Expected behavior**
- [x] We expect results from tests to run faster (reduce ~5 minutes)
- [x] We expect tests not to run if the `npm run build` fails
- [x] Deploy once after e2e tests pass

**Comment by tmcconechy** [comment]
As discussed reopening to test adding `npm ci` as well.

**Comment by tmcconechy** [comment]
We will use `npm install` and skip the package lock.
