### ISSUE TITLE
Datagrid: Firstrender and getStretchColumnIdx 

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#3481]
**Describe the bug**
On the first render of the datagrid, firstRender(), the rows are rendered first and then the header. This can cause an issue within afterRender, as it may attempt to apply a width to the stretch column, but apply it to the last column.

getStretchColumnIdx is looking for the header that does not exist, so returns -1, the last column as the result.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/test-columns-stretch-column.html', with the browser maximised.
2. Take note of how wide the last column is set
3. reduce the size of the browser window
4. Refresh the page.

This actually set the last column with to the calculated width of the stretchColumn

**Expected behavior**

**Version**
master

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome

**Additional context**
Should it be using this.bodyColGroup.find('col') instead of looking at the header?

**Comment by tmcconechy** [comment]
Dont seem to be seeing this issue. After i resize the browser and reload i see this:

<img width="781" alt="Screen Shot 2020-02-12 at 9 46 44 AM" src="https://user-images.githubusercontent.com/814283/74345778-99cf3b00-4d7c-11ea-8b61-3e109fa3b1e6.png">

Which seems ok?

**Comment by marknolaninfor** [comment]
It has to be small enough to caus an overflow

![image](https://user-images.githubusercontent.com/39749678/74387154-b2585780-4e47-11ea-9da2-64f699d8f425.png)

**Comment by tmcconechy** [comment]
Ok, it looked like it was more random in this case.

**Comment by marknolaninfor** [comment]
It is actually to do with #3308 , as that fix applied the calculated width to the scretch column, when the total width of the column, would be greater than the of the container. I assumed that the getStretchColumnIdx would be correct.

If the data in the stretch column was longer than the issue would be more dramatic.

It would be hard to create a unit test, unless you can set the width of the browser in the test, or create a second datagrid on this form with additional column, so that it alway causes the overflow, and then scroll to the end column to compare.

**Comment by marknolaninfor** [comment]
I found some other things that affect the widths. The totalWidth is a running total when columnWidth calls calculateColumnWidth. It is called in two spots renderRows and a resize onchage event where it does not reset the totalWidths, and just appends the widths again, so it can double, tripple, etc. 

I think it is only for a combination, of filtering, paging, and clientside data. 

The renderRows in the loaded event, and one instance,  does not reset the totalWitdhs, so the render event will then double the values

this.totalWidths[container] += col.hidden ? 0 : colWidth;

On the last column it calculates the overflow

diff = this.elemWidth - this.totalWidths[container];

In the final section of calculateColumnWidth it could set the last or stretch column width, and the left and right container widths for fixed columns.

**Comment by tmcconechy** [comment]
Would you want to recommend a change with a PR on master. I'm not totally following the proposed change without code to review?
