### ISSUE TITLE
Forms Compact: Choose File field is not aligned 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3483]
**Describe the bug**
Forms Compact: Choose File field is not aligned properly 

**To Reproduce**
1. Go tohttp://master-enterprise.demo.design.infor.com/components/form-compact/example-index.html?theme=uplift&variant=light
2. Scroll down and notice that the last field is not aligned with each other 

**Expected behavior**
Choose field should be aligned 

**Version**
All Browsers

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/74318681-ab363880-4db8-11ea-8a94-fe75e9239548.png)

**Platform**
Windows and macOS

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This regressed. If time we might as well fix it.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the "Done" column.
