### ISSUE TITLE
Datagrid: Reset to default is not working 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3487]
**Describe the bug**
Datagrid: Reset to default is not working 

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar.html?theme=uplift&variant=light
2. Click ...
3. Select Personalize Columns
4. Uncheck Product ID
5. Close 
6. Click Reset to Default 

**Expected behavior**
Default Columns and Product ID should show. 

**Version**
IDS Dev 4.251

**Screenshots**
N/a

**Platform**
All Platform 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This did work ok in 4.24 but seems to have regressed in 4.25. We better fix this

**Comment by janahintal** [comment]
The issue is still existing in https://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar.html?theme=uplift&variant=light 

- Click on ... button in grid toolbar
- Select Personalize Columns
- Uncheck Product ID
- Click on modal button Close
- See column Product ID should be hidden
- Click again on ... button in grid toolbar
- Select Reset to Default
- See column Product ID should show again
-

**Comment by tmcconechy** [comment]
@janahintal please test again, there was a deploy issue and the fix was not on master yet.

**Comment by janahintal** [comment]
QA Passed. Thank you. 

Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar.htm across all platforms.
