### ISSUE TITLE
Datagrid sort filter position or placement  is not consistent 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3488]
**Describe the bug**
Datagrid sort filter position or placement  is not consistent 

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift&variant=dark
2. Hover to all columns and notice that almost all sort filter is after the Title but not with QTY column. 

**Expected behavior**
Sort filter position should be consistent 

**Version**
4.251 Dev 

**Screenshots**
https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift&variant=dark

**Platform**
All Browser, OS, and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
The Qty column is right aligned (this is a column configuration). So thats why its on the left.
So this is working correctly
