### ISSUE TITLE
Datagrid checked row is getting unchecked after switching pages

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3489]
**Describe the bug**
Datagrid checked row is getting unchecked after switching pages

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-paging.html?theme=uplift&variant=light
2. Switch to  5 Groups per Page button
3. Click Last Page button
4. Select last row 215219 
5. Click First Page button then Click Last Page button again 

**Expected behavior**
215219 should remain checked 

**Version**
Dev IDS 4.251

**Screenshots**
N/a

**Platform**
All platform

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This example is using serverside paging without the saveRowsAcross pages option. So the selected rows are reset when changing page with this configuration. And its thus working correct
