### ISSUE TITLE
ContextMenu: Would like the ability to display Keyboard Shortcuts

### ISSUE THREAD

**Issue by drinkaj** [infor-design/enterprise#3490]
Landmark has a feature enhancement to add Keyboard Shortcuts to allow application users quicker ways to navigate through record, save records. etc..

On Context Menus where some of the actions that can be performed like Save, Next Record, Previous Record. Would like the ability to display the keyboard shortcuts to the far right of the menu. See screen shot for an example. 

![contextMenu](https://user-images.githubusercontent.com/6230418/74443356-a44f0a80-4e38-11ea-8c40-4fd71dec0576.png)

**Comment by tmcconechy** [comment]
We talked about doing an API where you would plugin the hotkeys and it would either do the mapping or not https://github.com/infor-design/enterprise/issues/643

But i think this is a bit easier. In just providing a UI facility to put the hot keys in the menu manually.

**Comment by tmcconechy** [comment]
This seem ok to you @kentonquatman or would you suggest some different treatment?

**Comment by kentonquatman** [comment]
This works. It seems to be the standard treatment for this pattern.
My only comment would be: can we use keyboard icons instead of spelling things out whenever possible? I know there isn't a universal icon for `ctrl`, but `cmd` and `shift` could be kept short.

⌘⇧→ or instead of Cmd + Shift + Right

**Comment by jbrcna** [comment]
The issue is now resolved. shortcut keys were displayed in contextmenu
v4.28.0-dev
https://master-enterprise.demo.design.infor.com/components/popupmenu/example-shortcut-text.html

**Comment by jbrcna** [comment]
just some observation in IE 11
![image](https://user-images.githubusercontent.com/56722184/79318465-9baea980-7f39-11ea-9788-b5fa5497231b.png)

**Comment by tmcconechy** [comment]
That might be worth a fix @jmacaluso711 ?

**Comment by CindyMercadoReyes** [comment]
Including BDD. 
[BDDStory_github#3490.docx](https://github.com/infor-design/enterprise/files/4516506/BDDStory_github.3490.docx)

**Comment by jbrcna** [comment]
The issue is now resolved. Thank you.
v4.28.0-dev
https://master-enterprise.demo.design.infor.com/components/popupmenu/example-shortcut-text.html
_screenshot from IE11_
![image](https://user-images.githubusercontent.com/56722184/80212261-bdaad900-8669-11ea-97f0-69a8da74eb7b.png)
