### ISSUE TITLE
Datagrid: Render issue with right aligned column and ellipsis in FireFox

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3491]
Describe the bug
Datagrid render issue when a grid column has a right alignment and the textOverflow of 'ellipsis'.  The cell value is rendered with the ellipsis, but expanding the width of the column does not show the data.  Issue only with Firefox.  Works fine in Chrome and IE11.

To Reproduce
1. Using the attached example-overflow-ellipsis.html
2. Render in Firefox browser
3. Notice that the Product Id cell values are all showing the ellipsis
4. Expanding the column width does not show the cell values
5. Compare with Chrome and IE 11

Expected behavior
Cell value should be displayed, ellipsis shown only when cell width requires.

Version
v4.26.0-dev

Screenshots
Rendering in Firefox:

![image](https://user-images.githubusercontent.com/39804038/74456058-e2a1f500-4e4b-11ea-8874-252f48c93f59.png)

Rendering in Chrome:

![image](https://user-images.githubusercontent.com/39804038/74456156-fe0d0000-4e4b-11ea-8e48-76b1ad73b0f9.png)

**Comment by claudenbach** [comment]
[Git-3491.zip](https://github.com/infor-design/enterprise/files/4199515/Git-3491.zip)

**Comment by jbrcna** [comment]
The issue is now resolved. Will retest once Beta is deployed. Thank you
verified in master v4.28.0-dev
