### ISSUE TITLE
Attempting to use full-width pattern and the grid layout

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#3495]
**Describe the bug**
We are looking at using the full-width class to utilise more of the screen space for pages with a lot of data or fields, but found a some css within the expandable area that is setting the padding even when the column was not in an expandable area. Looking at the history the specificity does not seem correct.

Last line of the _expandablearea.scss
```
.full-width .column:first-child,
.full-width .columns:first-child {
  // fixes an issue on search-forms
  padding-left: 20px !important;
}
```
It is padding the first column within a row. The example has multiple columns within a row, the column widths are set to half, and then are more than two in a row. The data is lazy loaded, so the each column may be hidden due to the data, eg no data returned for the part.

![image](https://user-images.githubusercontent.com/39749678/74612842-2d2bb600-5159-11ea-8c11-50acc2b02612.png)

**Additional context**
It was put in for the following example.
https://master-enterprise.demo.design.infor.com/examples/landmark/search-form

**Comment by tmcconechy** [comment]
Not totally clear on this , do you suggets suggest we remove padding from  https://master-enterprise.demo.design.infor.com/examples/landmark/search-form ? If so i think that would be fine as it would line up the left side.

**Comment by marknolaninfor** [comment]
The standard expandable area, with rows and columns does not apply any padding to the columns

https://master-enterprise.demo.design.infor.com/components/expandablearea/test-errors-padding.html

So should the other test page when using full-width also?

Example with the style disabled

![image](https://user-images.githubusercontent.com/39749678/75121189-bacf4e80-56e1-11ea-8335-47273e2ccd83.png)

I think it should all be the same, so that an expandable area does not apply the padding.

If it has to then the style needs to be moved in the file, so it only affects column in expandable areas. eg inside .expandable-area {

**Comment by tmcconechy** [comment]
I think what would be fine is to remove this inner padding. And then it will be flush by default. Then add a class like `side-padding` that can optionally pad inside? Feel free to propose a PR.

**Comment by brianjuan** [comment]
Passed QA in master in all browsers. Tested in https://master-enterprise.demo.design.infor.com/components/expandablearea/test-full-width.html. Will retest once beta is deployed.
