### ISSUE TITLE
Lookup Pager: select all checkbox is not working as expected

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3497]
**Describe the bug**
Lookup Pager: select all checkbox is not working as expected

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html
2. Open lookup field 
3. Click Last page
4. Click select all checkbox 
5. Go back to First Page

**Expected behavior**
The select all checkbox should be in Partial 

**Version**
IDS Dev 2451 beta 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/74653409-06a26500-51c3-11ea-83c5-c89f52672562.png)

**Platform**
All Platform

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping this for now
