### ISSUE TITLE
Validation: Wrong color of error message in Uplift Dark Variant

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3498]
**Describe the bug**
Validation: Wrong color of error message in Uplift Dark Variant.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/validation/example-index.html?theme=uplift&variant=dark
2. Clear the value of Email Address field
3. See issue: Error message "Required" is white instead of red

**Expected behavior**
Validation error message should be color red in Uplift Dark Variant.

**Version**
- ids-enterprise: v4.26.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/74720447-cac5d900-5270-11ea-8878-14d7d3424f31.png)

**Platform**
 - All Devices, OS and browsers.

**Additional context**
N/A.

**Comment by tmcconechy** [comment]
@brianjuan design asked us to change validation color to white for better contrast. So this is now correct

**Comment by brianjuan** [comment]
I see, thanks for the clarification @tmcconechy . This is noted.
