### ISSUE TITLE
Popover: Overlapping fields in Popover when in Uplift theme

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3499]
**Describe the bug**
Popover: Overlapping fields in Popover when in Uplift theme

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/popover/example-index.html?theme=uplift&variant=light
2. Open Popover button

**Expected behavior**
Popover should display properly 

**Version**
4.250 - 4.251 IDS 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/74739594-235a9d80-5294-11ea-90a9-2268a9fb1d2c.png)

**Platform**
All Platform

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This is being raised so often i just put a fix in.
