### ISSUE TITLE
Datagrid: Resizing columns does not reduce total grid size.

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise#3500]
**Is your feature request related to a problem? Please describe.**

Resizing the columns on a data grid is difficult if the data grids columns are too wide, Reset to Default does to make the columns fit,  

**Describe the solution you'd like**

Introduce a "Resize to Fit" action.

**Describe alternatives you've considered**

Reset to Default works as required.

**Additional context**

**Comment by tmcconechy** [comment]
May be similar to #3251

**Comment by tmcconechy** [comment]
@bthharper could you explain this a bit more?

**Comment by bthharper** [comment]
Executing "Reset to Default" calculates the columns widths bases on their contents, this can result in a horizontal scrollbar if the total required width exceeds the available width. 

Once in this situation, resizing the columns back to something that fits is difficult due to the way the column resizing works.

I suggest providing a "Resize to Fit" option, which distributes the columns evenly based on their relative width or via the 'stretchColumn'.

**Comment by tmcconechy** [comment]
Did you try the new resize options?  On https://master-enterprise.demo.design.infor.com/components/datagrid/example-reorder.html you can now resize the columns singular by default and even the last column. If you hold shift while resizing it will work in conjunction with the adjacent column.

I cant seem to reproduce reset to default making the size different. Try so here https://master-enterprise.demo.design.infor.com/components/datagrid/example-reorder.html

**Comment by tmcconechy** [comment]
Cant seem to reproduce this so closing for now
