### ISSUE TITLE
Datagrid: Unable to filter using the in-range operator

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3503]
Describe the bug
Unable to enter date ranges when using the in-range operator.  User is unable to type in two dates into the input box, the input box allows only a single date to be entered.  User is unable to enter date ranges when using the date picker.

To Reproduce
1. Using http://localhost:4000/components/datagrid/example-filter.html
2. Add the datagrid option of filterWhenTyping: false
3. Change the operator to in-range for the Order Date filter cell
4. Attempt to directly type in a date range (for example 01/01/2015 - 06/05/2015)
5. Notice that you're only able to enter the first date (01/01/2015), unable to directly type in a date range
6. Clear the date value
7. Attempt to pick the date range via the date picker
8. Notice that you can only pick a single date

Expected behavior
When using in-range operator, should be able to enter a date range

Version
v4.26.0-dev

Browser:
Testing using Chrome

Additional context
Related to https://github.com/infor-design/enterprise/issues/3337

**Comment by claudenbach** [comment]
![Git-3503](https://user-images.githubusercontent.com/39804038/74754819-d47f1a80-5237-11ea-8f81-d1ff5cc839be.gif)

**Comment by pwpatton** [comment]
just found this error exists in 4.25 for our june release. We'll need a patch for that and angular

**Comment by tmcconechy** [comment]
Are we sure that the range filter ever worked at all? Thinking it did not

**Comment by Sovia** [comment]
It used to, definitely. Dunno when it could have broken.

**Comment by Sovia** [comment]
whoops, pressed the wrong button.

**Comment by tmcconechy** [comment]
That’s fine. Once this is merged (was thinking to fox some related bugs but that can be separate). We can patch this one back

**Comment by brianjuan** [comment]
Passed QA in master, https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html in all browsers. Will retest once RC is deployed.
![image](https://user-images.githubusercontent.com/39508864/75674934-1476e080-5cc1-11ea-965a-2b71d0d4613d.png)

**Comment by brianjuan** [comment]
Passed QA in RC as well in all browsers. Tested in https://4260-rc0-enterprise.demo.design.infor.com/components/datagrid/example-filter.html. Moving to Done.
![image](https://user-images.githubusercontent.com/39508864/75748841-5eaca000-5d5b-11ea-9bfc-92cf78f5479f.png)
