### ISSUE TITLE
Calendar: buttons in popover are not visible

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3506]
**Describe the bug**
`Cancel` and `Submit` button are not visible. you need to resize the browser height or use tab(click comment box then press tab) to see the buttons

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Double Click on any date on last week of the month to open Add Event Modal

**Expected behavior**
Cancel and Submit button should be visible or at least have a scroll bar to view hidden objects

**Version**
4.26.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/74808667-52b9ea80-5326-11ea-9fac-f5b5785635f5.png)

**Platform**
All browser & Android Mobile

**Additional context**
iOS Mobile and/or responsive view works fine

**Comment by tmcconechy** [comment]
Not too worried about this issue, might close when the responsive view is done and coded (its not).
This is just that there is not enough room on the browser and you can easily resize to see everything.

**Comment by jbrcna** [comment]
the issue is also present in full screen.

**Comment by jbrcna** [comment]
This issue is now resolved. v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/56722184/85394944-f4c23b80-b581-11ea-8a36-79d0850fb3aa.png">
