### ISSUE TITLE
Checkbox: dirty tracker misaligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3507]
**Describe the bug**
dirty tracker in checkbox is misaligned

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/checkboxes/example-horizontal.html
2. Click on `Option3`
3. See error

**Expected behavior**
the dirty tracker should be inside the checkbox

**Version**
4.25 & 4.26.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/74820044-4b9dd700-533c-11ea-82bc-fb3b42dc51da.png)

**Platform**
All

**Additional context**

**Comment by jbrcna** [comment]
QA FAILED
v.4.26.0-dev
**`Firefox`**
![image](https://user-images.githubusercontent.com/56722184/75006852-31840600-54ae-11ea-8837-45c7286a2662.png)
**`iOS`**
![image](https://user-images.githubusercontent.com/56722184/75007475-3ea1f480-54b0-11ea-9642-a26b03afee89.png)
**`Android`**
![image](https://user-images.githubusercontent.com/56722184/75007456-2cc05180-54b0-11ea-84b4-ced65e5b6590.png)

**Comment by tmcconechy** [comment]
Added an additional fix. But it looked ok to me in Android 9.0, Pixel 3.0. But not totally worried about it

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to Done column.
