### ISSUE TITLE
Colorpicker: example-sizes dropdown issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3508]
**Describe the bug**
down arrow in dropdown is not centered. In iOS mobile, the last two drop down has no down arrow

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/colorpicker/example-sizes.html?theme=uplift&variant=light
2. Ensure that theme is `Vibrant`
3. Notice that the down arrow is not centered

**Expected behavior**
arrow should be in center

**Version**
4.26.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/74822319-ea780280-533f-11ea-8f23-7bec80d149ec.png)

**Platform**
All

**Additional context**
in iOS mobile, the medium size and large size dropdown has no arrow
![image](https://user-images.githubusercontent.com/56722184/74822534-39259c80-5340-11ea-9332-b31586f92421.png)

**Comment by tmcconechy** [comment]
@jbrcna what do you mean centered? It appears centered vertically to me. Do you mean too close to the right edge?

**Comment by jbrcna** [comment]
@tmcconechy yep you're right. it was too close. the screenshot below is the expected result.
<img width="586" alt="image" src="https://user-images.githubusercontent.com/56722184/74898703-9d467000-53d5-11ea-8c72-bc9039e5c366.png">

**Comment by jbrcna** [comment]
**Test Failed** - the dropdown arrows were now properly aligned, however, the mobile/responsive view issue still persist. 
verified in 
https://master-enterprise.demo.design.infor.com/components/colorpicker/example-sizes.html?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/56722184/75857195-b832ce80-5e30-11ea-9744-04c35b30afe9.png)
![image](https://user-images.githubusercontent.com/56722184/75857272-e1535f00-5e30-11ea-99f2-374de7ad44bf.png)

**Comment by tmcconechy** [comment]
Going to skip this final issue for now. Moving to done. Its somewhat correct these fields are fixed size not responsive. No one really asked for this, but if they do we can resume.
