### ISSUE TITLE
Process Indicator: Icons are not centered inside the circle

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3509]
**Describe the bug**
Process Indicator: Icons are not centered inside the circle.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/processindicator/example-index.html
2. See issue: Notice that the icons are not centered
3. Also try all Themes and Variants
4. Also try all browsers in Mac and Windows, each browsers have different cases

**Expected behavior**
Icons in Process Indicator should be centered

**Version**
- ids-enterprise: v4.25.0 to v4.26.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/39508864/74831122-8e1cdf00-534f-11ea-8f32-5da3b8ec1eda.png)

**Platform**
 - All devices, OS and browsers.

**Additional context**
N/A.

**Comment by janahintal** [comment]
Hi, the issue still exists. Some icons are still not centered. Please refer below. Thank you. 
https://master-enterprise.demo.design.infor.com/components/processindicator/example-index.html?

Uplift Theme:
![image](https://user-images.githubusercontent.com/45757016/76283407-7a70f280-62d5-11ea-849c-da9324fecb9f.png)

SOHO Theme:
![image](https://user-images.githubusercontent.com/45757016/76283539-d0de3100-62d5-11ea-862f-23833f79f4d6.png)

**Comment by ericangeles** [comment]
@janahintal would you mind to give more information about this? (Browser, size of the browser, is it on mobile, etc) Thanks

**Comment by janahintal** [comment]
Hi @ericangeles, I have tested this in Windows 10 Chrome Browser. 
Vibrant Theme - 
https://master-enterprise.demo.design.infor.com/components/processindicator/example-index.html?theme=uplift&variant=light

![image](https://user-images.githubusercontent.com/45757016/76841700-1e2d4600-6874-11ea-9a11-8606598cb8e5.png)

![image](https://user-images.githubusercontent.com/45757016/76841737-29807180-6874-11ea-90ee-4ebeb0baff2b.png)


SOHO Theme - https://master-enterprise.demo.design.infor.com/components/processindicator/example-index.html?theme=soho&variant=light
![image](https://user-images.githubusercontent.com/45757016/76841818-46b54000-6874-11ea-913d-1f4c5c29f8fa.png)
![image](https://user-images.githubusercontent.com/45757016/76841862-559bf280-6874-11ea-8530-1f70ee842d73.png)


Also in MacOS both SOHO and Uplift Theme
https://master-enterprise.demo.design.infor.com/components/processindicator/example-index.html?

![Uploading image.png…]()

**Comment by tmcconechy** [comment]
This issue is minor - so lets let any minor nudges go as we cannot fix this issue forever. Just not worth it

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
