### ISSUE TITLE
Radar: Alignment issues

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3510]
**Describe the bug**
Radar: Alignment issues.

**To Reproduce**
1. Open browsers in Android/iOS or resize desktop browsers to smaller
2. Go to https://master-enterprise.demo.design.infor.com/components/radar/example-index.html
3. See issue: Legends are too close to the bottom
4. Go to https://master-enterprise.demo.design.infor.com/components/radar/example-hcm.html?theme=uplift&variant=light in desktop browsers
5. See issue: Equipment Management is cropped

**Expected behavior**
There should be no alignment issues in Radar component

**Version**
- ids-enterprise: v4.26.0-dev

**Screenshots**
https://master-enterprise.demo.design.infor.com/components/radar/example-index.html
![image](https://user-images.githubusercontent.com/39508864/74831361-113e3500-5350-11ea-93a6-6970bce9e2e5.png)

https://master-enterprise.demo.design.infor.com/components/radar/example-hcm.html?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/39508864/74831439-35017b00-5350-11ea-900a-6fb069ce48a7.png)

**Platform**
 - All devices, OS, and browsers

**Additional context**
N/A.

**Comment by tmcconechy** [comment]
@deep7102 fixed this on a PR. Should be ready to test on master

**Comment by janahintal** [comment]
The issue is now resolved in Mobile but still exist in web browsers. Please see the image below. Thank you. 

https://master-enterprise.demo.design.infor.com/components/radar/example-hcm.html?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/45757016/79096642-51d68f80-7d90-11ea-8a25-e0e64b6c56a5.png)

**Comment by tmcconechy** [comment]
Can you rested this. Looks like it has a new fix now.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
