### ISSUE TITLE
FileUploadAdvanced: Add 'maxFiles` option to limit number of uploads

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise#3512]
**Is your feature request related to a problem? Please describe.**

It is not possible to constrain the number of files uploaded using the advanced file upload component.

**Describe the solution you'd like**

Provide an Input on `soho-advanced-fileupload` to constrain the maximum number of files than can be uploaded in the component.

**Describe alternatives you've considered**

Using vetoing events, but these do not exist either.

**Additional context**

**Comment by bthharper** [comment]
@tmcconechy - do we need a ticket for ng or will this be done as part of the tidy up?

**Comment by tmcconechy** [comment]
I usually run through them all before release but if you want to add it quick go ahead.

**Comment by jbrcna** [comment]
**QA Passed**
v4.28.0-dev
https://master-enterprise.demo.design.infor.com/components/fileupload-advanced/test-max-files.html
![image](https://user-images.githubusercontent.com/56722184/80212498-2a25d800-866a-11ea-92e5-91a5bb1b96bb.png)
