### ISSUE TITLE
Field Filter: Switching to In Range causes error

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3515]
**Describe the bug**
Switching to In Range filter type with a value in the field, then attempting to select a new in range value causes an error

**To Reproduce**
1. Go to /components/field-filter/example-datepicker.html
2.  Select a date in the date picker
3. Change the filter field to In Range
4. See the error : Not allowed to select a range, an error in the console log is seen

**Expected behavior**
Should be able to switch to a new filter field type with a value, and the date picker mode should updated appropriately.

**Version**

- ids-enterprise: v4.26.0-dev

**Screenshots**
![FieldFilterDatePickerError](https://user-images.githubusercontent.com/22107636/74872118-34ea8680-5322-11ea-8527-56d98de79ac6.gif)

![image](https://user-images.githubusercontent.com/22107636/74872008-0cfb2300-5322-11ea-9723-971965870d14.png)

**Platform**
 - All

**Comment by tmcconechy** [comment]
Range was never 100% working in some cases.. (like filter field and datagrid filter) Will have to fix this.

**Comment by brianjuan** [comment]
Passed QA in master, https://master-enterprise.demo.design.infor.com/components/field-filter/example-datepicker.html in all browsers. Will retest once RC is deployed.
![image](https://user-images.githubusercontent.com/39508864/75675365-fe1d5480-5cc1-11ea-836a-b68117bf9165.png)

**Comment by brianjuan** [comment]
Passed QA in RC in all browsers as well. Tested in https://4260-rc0-enterprise.demo.design.infor.com/components/field-filter/example-datepicker.html. Moving to Done.
![image](https://user-images.githubusercontent.com/39508864/75757383-3463de00-5d6d-11ea-909c-e842d5525e75.png)
