### ISSUE TITLE
Datagrid: Expanded row is misaligned from the frozen column

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3516]
**Describe the bug**
Datagrid: Expanded row is misaligned from the frozen column.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-expandable-row-frozen-columns.html or https://master-enterprise.demo.design.infor.com/components/datagrid/test-expandable-row-frozen-columns-bothsides.html
2. Click the ... menu at the top-right of the datagrid, then select Small or Medium row height
3. Expand the first row by clicking +
4. See issue: Expanded row is misaligned
5. Also try in Uplift, https://master-enterprise.demo.design.infor.com/components/datagrid/test-expandable-row-frozen-columns.html?theme=uplift&variant=light

**Expected behavior**
Expanded row should not be misaligned from the frozen column.

**Version**
- ids-enterprise: v4.26.0-dev

**Screenshots**
Soho, Small row height
![image](https://user-images.githubusercontent.com/39508864/74932927-e91d0780-541d-11ea-8d97-171ec6665d77.png)

Uplift, Normal row height
![image](https://user-images.githubusercontent.com/39508864/74932964-fcc86e00-541d-11ea-97ca-6352b4b1f909.png)

**Platform**
 - All devices, OS and browsers.

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Follow up issue on that feature you made @deep7102

**Comment by tmcconechy** [comment]
Closing this for now but we have one coming fix about changing the row height while its open.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to Done column.
