### ISSUE TITLE
Add ESC key functionality to dismiss a toast, like a modal

### ISSUE THREAD

**Issue by jamie-norman** [infor-design/enterprise#3521]
**Is your feature request related to a problem? Please describe.**
Would be nice to dismiss a toast message via hot key instead of having to grab the mouse and close or wait for timer to close it

**Describe the solution you'd like**
allow press of ESC key to dismiss

**Additional context**
If multiple toast messages are displayed, the ESC key would dismiss in order of newest to oldest or top to bottom layer

**Comment by tmcconechy** [comment]
We should look at notification banners. Too.

**Comment by EdwardCoyle** [comment]
cc'ing @inforandy

**Comment by jbrcna** [comment]
**QA Passed**
This is now working as expected.The toasts can now be quickly dismissed (based on the user's keyboard response settings).
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/toast/example-index.html
https://master-enterprise.demo.design.infor.com/components/toast/test-modal.html

**Comment by adinenno** [comment]
Do you know of a Landmark ticket for this so I can track it to let customers know what CU this will be in. Customers will love this.

**Comment by EdwardCoyle** [comment]
@adinenno I'm not aware of any open Landmark issues related to this... maybe @jamie-norman or @pwpatton could speak to that?

**Comment by CindyMercadoReyes** [comment]
BDD attached. Thanks Cindy
[story_github#3521.docx](https://github.com/infor-design/enterprise/files/4622356/story_github.3521.docx)
