### ISSUE TITLE
ContextMenu: field options menu icon button is misaligned Uplift

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3523]
**Describe the bug**
the icon beside the large textbox was not in proper alignment

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/contextmenu/example-field-options.html?theme=uplift&variant=light
2. Notice that the `:` icon beside the large textbox is not in proper alignment
3. See error

**Expected behavior**
the icon should be beside the textbox

**Version**
4.26.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/75009293-4b751700-54b5-11ea-9d6b-f3e8ebf4cf0d.png)

**Platform**
All

**Additional context**

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to QA failed. This issue still occurs on MAC FF
<img width="955" alt="Input Error Component" src="https://user-images.githubusercontent.com/39101346/75184890-2382ef00-5713-11ea-9082-e2365bbb6a16.png">

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column

**Comment by tmcconechy** [comment]
@CindyMercadoReyes i tried to reproduce but it seems ok. Can you test again.

- open this page in FF mac https://4260-beta0-enterprise.demo.design.infor.com/components/contextmenu/example-field-options.html?theme=uplift&variant=light
- hover each field (seems ok and free of issues)

**Comment by jbrcna** [comment]
QA PASSED
v4.26.0-beta0
verified in https://4260-beta0-enterprise.demo.design.infor.com/components/contextmenu/example-field-options.html?theme=uplift&variant=light
