### ISSUE TITLE
Masthead: Appears broken in uplift mode

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3526]
**Describe the bug**
Trying the masthead out and it looks odd in uplift.

**To Reproduce**
1. Go to 'https://master-enterprise.demo.design.infor.com/components/masthead/example-index.html?theme=uplift&variant=dark
2. The menu is all blue. i think it should not be. But if it is the colors should not look bad
3. Go to https://master-enterprise.demo.design.infor.com/components/masthead/example-index.html?theme=uplift&variant=contrast
4. See that all the buttons are gone compared to https://master-enterprise.demo.design.infor.com/components/masthead/example-index.html

**Expected behavior**
Buttons are visible and colors look ok in the dark modes.

**Version**
- ids-enterprise: [e.g. v4.26.0]

**Additional context**
Seen in Ng demo app

**Comment by brianjuan** [comment]
Passed QA in master in all browsers. Tested in the links below. Will retest once beta is deployed.

- https://master-enterprise.demo.design.infor.com/components/masthead/example-index.html?theme=uplift&variant=dark
- https://master-enterprise.demo.design.infor.com/components/masthead/example-index.html?theme=uplift&variant=light
- https://master-enterprise.demo.design.infor.com/components/masthead/example-index.html?theme=uplift&variant=contrast
- https://master-enterprise.demo.design.infor.com/components/masthead/example-index.html?theme=soho&variant=dark
- https://master-enterprise.demo.design.infor.com/components/masthead/example-index.html?theme=soho&variant=light
- https://master-enterprise.demo.design.infor.com/components/masthead/example-index.html?theme=soho&variant=contrast
