### ISSUE TITLE
Homepage: Allow widgets to be resized and rearranged.

### ISSUE THREAD

**Issue by crlang44** [infor-design/enterprise#3531]
**Is your feature request related to a problem? Please describe.**
Widgets don't have the ability to be resized or rearranged by the user.

**Describe the solution you'd like**
Widgets should be able to be resized and rearranged by the user.

**Describe alternatives you've considered**

**Additional context**

Ming.le Homepages which has this ability:
![image](https://user-images.githubusercontent.com/4143306/75175593-7d6dbf80-56e7-11ea-9636-06013a9f332e.png)

**Comment by janahintal** [comment]
Alright, Will just create a new ticket. Thanks. Will now move this to Done.

**Comment by jbrcna** [comment]
**Test Failed**
It works fine in All Browsers **EXCEPT** `IE11`
v4.27.0-dev
verified in https://master-enterprise.demo.design.infor.com/components/homepage/example-editable.html?
![image](https://user-images.githubusercontent.com/56722184/77154137-15d44580-6ad6-11ea-8d67-4b91de3284b2.png)

**Comment by jbrcna** [comment]
**QA PASSED**
it is now working on IE 11
v4.27.0-dev
https://master-enterprise.demo.design.infor.com/components/homepage/example-editable.html
