### ISSUE TITLE
Modal: What is the recommended way of chaining modal message dialogs?

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#3534]
We are using IDS 4.24 and Chrome (though same behviour in other browsers).

Can you provide the recomended code, or point me to an example, to display modal message dialogs in a chain, one after another? 

The example scenario is a modal dialog that has a button that, when clicked, destroys itself and then triggers the opening of a subsequent 2nd modal dialog (with different content and id).

What I am finding in practice is that when the 2nd modal is opened, and it displays as normal, then a a second later, its overlay is removed, so I presume the 1st modal is clearing the overlay on a timer. I presume this is because I need to invoke the 2nd modal in a different way but I don't see any obvious examples on the modal doc page. Could someone provide an example?

**Comment by tmcconechy** [comment]
It should roughly just "work". Here is an example in the modal examples https://master-enterprise.demo.design.infor.com/components/modal/test-nested.html

We dont have an example of message component nested. But i would image that it would work too the same.

Source: https://github.com/infor-design/enterprise/blob/master/app/views/components/modal/test-nested.html 
This one is done just using the trigger buttons setting in markup. Where each button opens a modal.

**Comment by sanx72** [comment]
@tmcconechy - in your example, the modals are the same size (sorry, I forgot to say that, in my application the 1st modal is larger than the 2nd) and stacked (hence the extra dark overlay on the 2nd dialog). 

I would like to be able to open modal 1, with a normal 70% opacity overlay, then close modal 1 on a button selection (via one of the modal form buttons, not an extra button in the modal body content) and then open modal 2, which will then also display with a 70% opacity overlay.

Attached is a Webex recording of the current behaviour...

[Chained Modal Example.zip](https://github.com/infor-design/enterprise/files/4250503/Chained.Modal.Example.zip)

**Comment by tmcconechy** [comment]
I cant see your video. Not sure how to open wrf files. I downloaded Webex Player but it gave me problems so i had to remove it. Maybe another format?

But based on the description i made a quick example https://github.com/infor-design/enterprise/blob/master/app/views/components/modal/test-one-after-the-other.html
- open one modal
- hit a button and it will close
- then hit another.

It looked OK without the timeout. But i added a brief timeout so the overlay doesnt look as "flashy". Not sure if this helps but maybe you can use this to model your issue your seeing. Or help solve.

**Comment by sanx72** [comment]
Thanks for the example. The video was recorded with WebEx Recorder/Player as that is the only thing Infor IT gives us to capture video (the step recorder in Windows doesn't properly show the problem).

I've previously used modal.destroy() in the button events as this removes the modal and the content (which is dynamically created on each call to open the 1st modal dialog). If I use modal.close() I then have to remember to manually delete the old content or it appears back in the document body.

My concern with using timeouts is that based on experience, what works on my PC/browser combination then gives different results on faster/slower PCs or browsers.

Just a thought, instead of doing a modal.close() is there a method on the modal object I could call passing the new modal content and buttons that would essentially redraw/resize the same instance of the modal dialog?

**Comment by tmcconechy** [comment]
We use this chrome plugin https://www.screencastify.com/ works pretty good.
Try it without the timeout. It wasn't bad at all to me like that but i felt it looked better with the timeout.

> instead of doing a modal.close() is there a method on the modal object I could call passing the new modal content and buttons that would essentially redraw/resize the same instance of the modal dialog?

No there isnt but what if you just had two areas on the modal and you hide and showed them? There is a method that will resize it as well..

```
      $('body').on(`resize.${this.namespace}`, () => {
        this.sizeInner();
      });
```

So you could  trigger resize `$('body').trigger('resize');`

**Comment by tmcconechy** [comment]
Think this was answered so closing.
