### ISSUE TITLE
SpinBox: Readonly state does not get removed full by enable

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#3536]
If the readonly method of a SpinBox is used, the input field is not updated to match the state of the plus/minus buttons. 

Is there a different method to call so that the both the spinbox plus/minus buttons and input field can be toggled between enabled and read-only states?

E.g. Initial state...

![image](https://user-images.githubusercontent.com/44396995/75260758-fd785000-57e1-11ea-8399-9655e0078e00.png)

Click check box to toggle the states of the boxes...

![image](https://user-images.githubusercontent.com/44396995/75260795-0bc66c00-57e2-11ea-83de-f96605562a5e.png)

Click check box again...

![image](https://user-images.githubusercontent.com/44396995/75260817-14b73d80-57e2-11ea-80b7-dc03919159fd.png)

Example Code

```html
<div class="row">
        <div class="twelve columns">
        	<div class="field">
				<label for="spin1">Initially read-only</label>
				<input class="spinbox" id="spin1" type="text" value="1" readonly="readonly"/>
        	</div>
        	<div class="field">
				<label for="spin2">Initially enabled</label>
				<input class="spinbox" id="spin2" type="text" value="1"/>
        	</div>
        </div>
      </div>
	<div class="row">
        <div class="twelve columns">
        	<div class="field">
      			<input type="checkbox" class="checkbox" id="chkToggle"/>
				<label for="chkToggle" class="checkbox-label">Toggle Read-only state of spinboxes</label>
        	</div>
        </div>
      </div>
```

```javascript
$('#chkToggle').change(function() {
				if ($(this).prop("checked")) {
					$('#spin1').data("spinbox").enable();
					$('#spin2').data("spinbox").readonly();
				} else {
					$('#spin1').data("spinbox").readonly();
					$('#spin2').data("spinbox").enable();
				}
			});
```

**Comment by tmcconechy** [comment]
This is a bug. Its not removing the readonly prop. Made a quick fix on the PR https://github.com/infor-design/enterprise/pull/3537/files#diff-0cb1774867e736cb897a054fbeaa6bcfR625

As a workaround you can just remove it `$('#spin2').data("spinbox").enable()..prop('readonly', false)`

**Comment by sanx72** [comment]
When I try the workaround in IDS 4.24, I get an exception...

`			$('#chkAuto').change(function() {
				if ($(this).prop("checked")) {
					$('#spnMajor').data("spinbox").readonly().prop('readonly', true);
					$('#spnMinor').data("spinbox").readonly().prop('readonly', true);
				} else {
					$('#spnMajor').data("spinbox").enable().prop('readonly', false);
					$('#spnMinor').data("spinbox").enable().prop('readonly', false);						
				}
			})`

`VM946:833 Uncaught TypeError: Cannot read property 'prop' of undefined
    at HTMLInputElement.<anonymous> (<anonymous>:833:47)
    at HTMLInputElement.dispatch (jquery-3.4.1.js:5237)
    at HTMLInputElement.elemData.handle (jquery-3.4.1.js:5044)`

I'm guessing the readonly/enable methods don't support chaining so I'll try re-organising the prop() calls.

**Comment by tmcconechy** [comment]
Sorry @sanx72 i just hand coded that. More like:

```
var elem = $('#spnMajor'):
elem.data("spinbox").enable();
elem.prop('readonly', false);
```

**Comment by janahintal** [comment]
QA Passed. Re-tested in https://master-enterprise.demo.design.infor.com/components/spinbox/example-readonly.html?theme=uplift&variant=light and the spinbox is now working as expected. Thank you.
