### ISSUE TITLE
Refactor old sass vars with corresponding ids-identity sass vars

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#354]
**Is your feature request related to a problem? Please describe.**
Currently we have a temporary implementation of ids-identity tokens where we map them to their existing sass variable counter part, for example in [_config.scss#165](https://github.com/infor-design/enterprise/blob/master/src/core/_config.scss#L160):

```sass
// existing sass var : ids-identity token
$primary-btn-bg-color: $button-primary-bg-color;
```

**Describe the solution you'd like**
The goal is to replace the older variables with their corresponding token sass variable. This will help cleanup `_config.scss` and remove confusion from having variables tied to one another with similar names.

To continue with the above example:

1. Remove [_config.scss#L160](https://github.com/infor-design/enterprise/blob/master/src/core/_config.scss#L160)
1. Find all instances of the original variable `$primary-btn-bg-color`
1. Replace those instances with the ids-identity token variable `$button-primary-bg-color`.
1. Repeat for each "mapping" pair to clean up redundancy

*Note that it might be easier to break this ticket into a few pull requests for smaller, easier peer reviews.*

**Additional context**
See https://github.com/infor-design/design-system/issues/158 for ids-identity and token related information.

**Comment by brianjuan** [comment]
Hi, can you provide us the page for QA testing and also the necessary steps. Thanks!

**Comment by clepore** [comment]
This is going to be a hard one to test. Since we mostly got rid of duplicate style variables, the testing method would be to make sure the site styles didn’t change. The easiest way to do this would be to test everything you normally would and keep an eye out for any differences (mostly colors) that look out of place.
