### ISSUE TITLE
Tabs: Overlapping Tab focus 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3546]
**Describe the bug**
Tabs: Overlapping Tab focus 

**To Reproduce**
1. Go to https://4260-beta0-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html
2. Close Tab 2 and Tab 3
3. Populate Tab Name and Tab Content 
4. Switch to Vibrant 
5. Click '+' add tab button

**Expected behavior**

**Version**
4260-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/75348838-7fe63a00-58de-11ea-8bd8-849d9f320001.png)

**Platform**
All Browser & OS

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping this issue for now. Its really not that important to change theme in this example page.
