### ISSUE TITLE
FileUploadAdvanced: Need an event for the delete of an attachment

### ISSUE THREAD

**Issue by jayblack-infor** [infor-design/enterprise#3548]
**Describe the bug**
Need an event added to SohoFileUploadAdvancedComponent when the x is clicked to remove an attachment.

**To Reproduce**
1. Select an attachment(s).
2. There is an x on the left if attachment is in progress.    There is an x on the right if complete.
3. When the x is clicked need an event that is available.
4. Expose this in Angular too

**Version**
4.13

**Comment by jbrcna** [comment]
**QA Passed**
v4.28.0-dev
moving this ticket to Done. Thank you
