### ISSUE TITLE
Lookup: Empty Message keeps appearing in the modal after clicking the lookup button

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3551]
**Describe the bug**
Lookup: Empty Message keeps appearing in the modal after clicking the lookup button

**To Reproduce**
1. Go to https://4260-beta0-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html?theme=uplift&variant=light
2. Open the Lookup 

**Expected behavior**
It should not have the empty message inside the modal

**Version**
4.260 IDS Beta

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/75440723-40c7ef80-5997-11ea-80f4-42552e89bc38.png)

**Platform**
All Platform

**Additional context**
N/a

**Comment by tmcconechy** [comment]
@janahintal cant seem to reproduce this. Do not see any empty message.

**Comment by tmcconechy** [comment]
Descoping this for now
