### ISSUE TITLE
Data Grid RTL: Actual Price header has alignment issue with up and down arrow key

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3552]
**Describe the bug**
Data Grid RTL: Actual Price header has alignment issue with up and down arrow key

**To Reproduce**
1. Go to URL: http://localhost:4000/components/datagrid/example-fixed-header.html?locale=he-IL#
2. Hover over "Actual Price"
3. See error here is that, the up and down arrow are overlapping the three dot. Please see screen shot attached. 

**Expected behavior**
There should be no overlapping.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="288" alt="Screen Shot 2020-02-27 at 9 33 34 AM" src="https://user-images.githubusercontent.com/39101346/75457208-40553780-594a-11ea-8c26-802cba2ad7b8.png">

**Platform**
 - OS Version: [ iOS 8]
 - Browser Name [FF]

**Additional context**
None

**Comment by jbrcna** [comment]
The issue is now resolved. verified in v4.27.0-dev
Moving this ticket to Done column
