### ISSUE TITLE
Calendar: Tooltip not aligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3553]
**Describe the bug**
The tooltip is not aligned

**To Reproduce**
1. Go to https://4260-beta0-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Create an event ( any date )
3. Click the newly created event
4. See error, notice that the tooltip does not point directly to the source

**Expected behavior**
should be aligned

**Version**
4.26.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/75464312-fc057e00-59c1-11ea-9c95-d17928cf1cde.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Going to descope this for now. Too hard to fix and not that valuable to fix. But will fix https://github.com/infor-design/enterprise/issues/3506 which is similar.
