### ISSUE TITLE
Multi-Select: Add option to provide "All" Header Strings

### ISSUE THREAD

**Issue by crayzd92** [infor-design/enterprise#3554]
From the Infor CRM CE Team as reported to us through our translation team in Jira MCRM-9049.

**Describe the bug**
"All Cuisine Preference" in Cuisine Preference dropdown is a combined string. Combining strings leads to I18n issues. "Cuisine Preference" is a CRM string; "All" does not come from CRM.

We are using the IDS Drop-Down component for a multi-select list in CRM CE inside of Mongoose.

**To Reproduce**
1. Go to super secret internal Infor ADE Server link (I will email to code owners)
2. Open Infor CRM CE in Ming.le
3. Click on Contacts > Extended Details > Cuisine Preference:
4. Open the drop-down and see the concatenated header strings.

sohoxi.js lines 36318 & 36329 are where this concatenation is happening

![image](https://user-images.githubusercontent.com/17650211/75468272-303d5800-594a-11ea-8517-0021032eea99.png)

**Expected behavior**
Translation best practices are to use format strings when strings need to be concatenated because some languages say things in a different order than we do in English.

**Version**
4.22.0

**Screenshots**

![image](https://user-images.githubusercontent.com/17650211/75468407-6f6ba900-594a-11ea-82e2-ed2ef4c79451.png)

![image](https://user-images.githubusercontent.com/17650211/75468493-890cf080-594a-11ea-8ab1-cf4a4160ef36.png)

In German (psuedo-translated)

![image](https://user-images.githubusercontent.com/17650211/75468545-9cb85700-594a-11ea-9a9f-4fe3e6d97c2f.png)

**Platform**
 - Device: Desktop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 80.0.3987.122 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
I thought there was an option for this but there seems to not be. So i think what we can do is add an option to the component. `allTextString` and `selectedTextString`  that you can set to what you like. Then it will  be possible to override the default concatination.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/multiselect/test-header-strings.html?theme=uplift&variant=light
