### ISSUE TITLE
Datagrid: Lookup editor removes '|" pipe character when returning value

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3556]
Describe the bug
A datagrid cell is using the editor Lookup.  When the lookup editor returns the value, it removes all characters following and including the '|' pipe character.  Landmark has legit values that contains the '|' pipe character.  

To Reproduce
1. Using the attached test-editor-lookup-with-pipe.html 
2. Click on a Product Name cell
3. Click on the lookup icon
4. Select the item with the Product Name of 'Pipe| Character' (its the last one)
5. Leave the cell being edited
6. Notice that the value place into the cell is just 'Pipe' and not 'Pipe| Character' 

Expected behavior
Full value is displayed, no truncation when the value contains '|' pipe character.  

Version
v4.27.0-dev

Browser:
Testing using Chrome

**Comment by tmcconechy** [comment]
Its probably these lines https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.editors.js#L775 I think it should instead be using the delimiter setting. And checking if multiselect. i think this was done for the mutiselect lookup.

**Comment by claudenbach** [comment]
Here is the code with the issue...

    this.val = function (v) {
      let fieldValue = this.input.val();
      if (fieldValue && fieldValue.indexOf('|') > -1) {
        fieldValue = fieldValue.substr(0, fieldValue.indexOf('|'));
      }
      return v ? this.input.val(v) : fieldValue;
    };

**Comment by claudenbach** [comment]
[Git-3556.zip](https://github.com/infor-design/enterprise/files/4263964/Git-3556.zip)

**Comment by jbrcna** [comment]
**Test Passed** 
v4.27.0-dev
tagging this ticket as Passed with Observation
verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup-with-pipe.html
- The sort functionality was not present in “Product Name” column of Datagrid
