### ISSUE TITLE
Datagrid: Unable to resize back the last column after resizing it to smaller width

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#3557]
**Describe the bug**
Datagrid: Unable to resize back the last column after resizing it to smaller width.

**To Reproduce**
1. Go to https://4260-beta0-enterprise.demo.design.infor.com/components/datagrid/example-index.html
2. Resize the last column "Phone" to smaller width size
3. Try to resize back the last column "Phone" to larger, issue will happen: unable to resize back. See video below for more visual steps.

**Expected behavior**
Should be able to resize back the last column after resizing it to smaller width.

**Version**
- ids-enterprise: v4.26.0-beta0

**Screenshots**
![datagrid-resize](https://user-images.githubusercontent.com/39508864/75543807-9cf54700-5a5d-11ea-9855-152c30443c53.gif)

**Platform**
 - All devices, OS, and browsers.

**Additional context**
N/A

**Comment by tmcconechy** [comment]
This might be worth fixing. Thinking we maybe make the last column not resizable?

**Comment by tmcconechy** [comment]
Added an additional fix.

**Comment by brianjuan** [comment]
Passed QA in all browsers, tested in https://4260-rc0-enterprise.demo.design.infor.com/components/datagrid/example-index.html. Moving to Done.
![resizedatagrid](https://user-images.githubusercontent.com/39508864/75762364-81e44900-5d75-11ea-9fa9-254c147499b4.gif)
