### ISSUE TITLE
Datagrid: Records are being not selected after going to the Last Page

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3558]
**Describe the bug**

**To Reproduce**
1. Go to https://4260-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouping-paging.html?theme=uplift&variant=light
2. Select All Records 
3. Click Last Page
4. Click 1st Page

**Expected behavior**
Records should all be selected

**Version**
4.260 IDS Beta

**Screenshots**
N/a

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This is another case where it is working correctly as you change pages. What i'll do is remove the checkbox on the header from this example so we dont get further bugs added around this and to avoide any confusion.

**Comment by tmcconechy** [comment]
Decided not to do this as it failed some expected tests. So just keep in mind that on this example select all will only work on the current page. But if you dont know, dont worry raise the issue and i'll close it if thats the case.
