### ISSUE TITLE
Colorpicker: Some issues with selection in iOS

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3559]
**Describe the bug**
There are 2 things we thought of when using the color picker in phones, first if you miss the color and click between the colors in iOS the color picker is closed without selecting any value. This does not seem to happen in Android where it seems to be easier to touch the color.

Second issue actually happens in Android as well, is there a way to stop the color picker from opening the keyboard after selecting the color. I do not think that it's necessary to leave the cursor in the color picker after selecting the color. It is quite annoying on the phone/tablet when the keyboard shows up when I do not intend to use it and after a color has been selected it is not probable that I want to write in the color picker field.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/colorpicker/example-index.html' in an Ipad/Iphone
2. Click on the color picker
3. Click right next to a color
4. Notice that the color picker is closed without selecting any value (or keeping the old one), also notice in this case the keyboard is not opened, which would be nice in step 6
5. Click the color picker again
6. Select a color
7. Notice that the cursor is within the color picker and the Keyboard is opened

**Expected behavior**
In step 4 I think either the closest color should be selected or the color picker should not close when you missed the colors.
//Removed  - In step 7 the color picker input should be updated as before but the keyboard should not pop up so I suppose the focus needs to behave differently.

**Version**

- ids-enterprise: v 4.24

**Screenshots**

![image](https://user-images.githubusercontent.com/8664975/75555070-d321cf00-5a3b-11ea-91ef-1de6a6371779.png)

**Platform**
 - Device: Ipad, (Samsung Galaxy S7 (Second issue)
 - OS Version:  IpadOS 13.3.1 / Android 8.0.0
 - Browser Name: Chrome
 - Browser Version: 79.0.3945.73 / 79.0.3945.136

**Additional context**
-

**Comment by tmcconechy** [comment]
Im not 100% sure we can do anything about this. The keyboard is there in case you want to type.
Possibly we can see if it can be hidden "automatically" when you select? Not sure if thats possible or not.

Otherwise you could just use the https://master-enterprise.demo.design.infor.com/components/colorpicker/test-states.html "Normal (Non-Editable)" colorpicker for this use case?

**Comment by SofiK** [comment]
That's a good idea to use the non-editable variant. I think I will bring that back to the team. Thank you!

**Comment by SofiK** [comment]
Hi @tmcconechy  do you think you will do something regarding the first part of the issue where it closes when you click in between colors? My suggestion is that either the colorpicker should not close if you miss or the color that currently has focus/is closest should be applied.

**Comment by tmcconechy** [comment]
I'd think that can probably be addressed. I dont think the keyboard is though. But maybe we can see if we can make an incorrect click not close it?

**Comment by SofiK** [comment]
Great, Thanks! 
Please ignore the keyboard issue, that part seems to be working better now :)

**Comment by jbrcna** [comment]
**QA Passed**
will retest once beta is deployed.
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/colorpicker/example-index.html

**Comment by jbrcna** [comment]
Test passed. verified in v4.33.0-beta1
https://4330-beta1-enterprise.demo.design.infor.com/components/colorpicker/example-index.html
