### ISSUE TITLE
Pie/Donut: Placing Legend on Bottom is not working in Homepage Cards

### ISSUE THREAD

**Issue by DivyaParepally** [infor-design/enterprise#3560]
**Is your feature request related to a problem? Please describe.**
In Homepage Widgets when [legendPlacement] ="'bottom'" is used for pie-chart, legend is not displaying.

**Additional context**
https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1582275854189?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1582275854189&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Angular%20Components&createdTime=1582275854189

**Describe the solution you'd like**
Legend should be displayed on the bottom of Pie-Chart.

**Version**
- ids-enterprise-ng: 6.1.0

**Comment by tmcconechy** [comment]
I thought this might work in a double-height widget. But it doesnt seem to be. Will take a look in the future. This also isnt putting the widget on the bottom..

```
<div class="row">
  <div class="one-third column">
      <div class="widget double-height">
        <div class="widget-header">
          <h2 class="widget-title">Pie Chart</h2>
        </div>
        <div class="widget-content">
          <div id="pie-chart-example" class="chart-container">
          </div>
        </div>
      </div>
  </div>
</div>
```

In theory we can try to reduce the size of the pie and squish it in but if  alot of legend items it might scroll.

Another possible workaround is make your widget scrollable.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-single-widget.html?theme=uplift&variant=dark
