### ISSUE TITLE
Datepicker Chinese translation has incorrect format for the year heading

### ISSUE THREAD

**Issue by crayzd92** [infor-design/enterprise#3568]
**Describe the bug**
This was raised up by the CRM CE translation team in MCRM-10268. The year heading on the calendar view of the Datepicker control is formatted incorrectly for Chinese.

![image](https://user-images.githubusercontent.com/17650211/75716425-247cc900-5c9d-11ea-896e-2565fa034716.png)

Using September 2019 as an example:

2019年9 九月 is wrong. It has 9 and also 九月 (which means September). It should be either **2019年 九月** or **2019/9**

Secondly, once you select a date like September 2, 2019 it is returned the control and reformatted as 2019/9/2 (correct), but then if you open the Datepicker again the value is immediately changed to 2/0/1992 and highlighted in red.

![image](https://user-images.githubusercontent.com/17650211/75716325-f8614800-5c9c-11ea-9abf-351574aa8f9c.png)

**To Reproduce**
Use the Datepicker control when your language is set to zh-CN

**Expected behavior**
The year header in the calendar view should be either **2019年 九月** or **2019/9**

**Version**
- ids-enterprise: 4.22.0

**Screenshots**
See above

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
This possibly is a duplicate of:

https://github.com/infor-design/enterprise/issues/3473 - for the error message part?
Cant reproduce it on the latest here:

https://master-enterprise.demo.design.infor.com/components/datepicker/example-index?locale=zh-CN

For the formatting in the header we recently changed this as you can see in the example, but we use a slightly different format. (Was also told to do it this way by the translation team)

<img width="147" alt="Screen Shot 2020-03-03 at 9 48 00 AM" src="https://user-images.githubusercontent.com/814283/75787016-1af27000-5d34-11ea-8f09-d12ba1cd97fb.png">

Please test this out on the example and let me know if you still see any issues.

**Comment by crayzd92** [comment]
Thanks @tmcconechy , we are going to be updating to the latest in the next week-ish, We will have our translation team take another look once that happens.
