### ISSUE TITLE
Datepicker: Mobile/Responsive View Layout Issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3569]
**Describe the bug**
calendar pop up have some layout issue

**To Reproduce**
1. Go to https://4260-rc0-enterprise.demo.design.infor.com/components/datepicker/example-range.html
2. For Mobile, Click on the textbox then click the calendar icon
3. See error
4. For Browsers, Resize the browser window to a smaller size then click the calendar icon
5. See error

**Expected behavior**
calendar pop up should be responsive

**Version**
v4.26.0-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/75770311-a8f54780-5d82-11ea-80cd-50cbd94a35be.png)
![image](https://user-images.githubusercontent.com/56722184/75771457-fe325880-5d84-11ea-93a2-5729424bdfca.png)

**Platform**
Mobile/Responsive view

**Additional context**

**Comment by tmcconechy** [comment]
@jbrcna im not seeing this. here is a screen shot of iphone (browser) stack and responsive view in chrome:

<img width="308" alt="Screen Shot 2020-03-03 at 9 32 23 AM" src="https://user-images.githubusercontent.com/814283/75785616-0614dd00-5d32-11ea-9bae-264324f1b1db.png">
<img width="384" alt="Screen Shot 2020-03-03 at 9 32 27 AM" src="https://user-images.githubusercontent.com/814283/75785618-06ad7380-5d32-11ea-81a5-d8d74f852b93.png">

**Comment by jbrcna** [comment]
https://4260-rc0-enterprise.demo.design.infor.com/components/datepicker/example-range.html
1. For Mobile, Click on the `textbox` then click the `calendar icon` of `Range - Min (5) Days` alternatively, scroll down then choose any date picker from below. datepickers from above are not affected
![Large GIF (508x630)](https://user-images.githubusercontent.com/56722184/75855791-fd093600-5e2d-11ea-80b0-ffb82c9bfb17.gif)

2. Resize your browser to 371 x 606 or until you can only see 4 date pickers then click on the calendar icon
![Large GIF (618x472)](https://user-images.githubusercontent.com/56722184/75853158-7c940680-5e28-11ea-8d31-b9e42553f5c6.gif)

**Comment by jbrcna** [comment]
QA FAILED
Test was done in v4.26.1 and in master v4.27.0-dev.

![image](https://user-images.githubusercontent.com/56722184/76620700-ba9bd380-6568-11ea-9678-c2c5482badba.png)

![image](https://user-images.githubusercontent.com/56722184/76620811-00589c00-6569-11ea-8205-647349bbf7b8.png)

**master-enterprise v4.27.0-dev**
There's an issue in `Vibrant` Theme
`Vibrant Theme`
![image](https://user-images.githubusercontent.com/56722184/76622255-1ae04480-656c-11ea-97b0-9dca574dc3a9.png)

`Vibrant Theme`
![image](https://user-images.githubusercontent.com/56722184/76621216-d784d680-6569-11ea-9e1e-deed5533e569.png)
If you weren't able to reproduce, just keep on changing the dates. try using `Clear` and `Apply` buttons
`Vibrant Theme`
![image](https://user-images.githubusercontent.com/56722184/76621376-321e3280-656a-11ea-9471-80505c12747a.png)

(Trivial) - Also, Notice that the calendar container doesn't look like popover it looks more like a box or modal

**Comment by tmcconechy** [comment]
Can you take a look at these additional cases when you have a chance @ericangeles ?

**Comment by ericangeles** [comment]
@tmcconechy sure do.

**Comment by ericangeles** [comment]
@jbrcna would you mind to give more details on this? Thanks

**Comment by jbrcna** [comment]
I did the same steps as mentioned above and in the PR. The issue persists in vibrant theme. 

For Mobile, Click on the textbox then click the calendar icon of Range - Min (5) Days alternatively, scroll down then choose any date picker from below. datepickers from above are not affected.
Use vibrant theme and do same steps. Also, use the clear and apply buttons then repeat the first steps. 

 For browser, Resize your browser to 371 x 606 or until you can only see 4 date pickers then click on the calendar icon. Repeat the same steps as above.

If it still not reproducible, just let me know your availability to discuss. Ill ping you  😊

**Comment by jbrcna** [comment]
Browser: Chrome EDGE
![Large GIF (656x494)](https://user-images.githubusercontent.com/56722184/76734081-1fd80a80-679d-11ea-82af-884878b3d50f.gif)

Browserstack: iPhone 11 Pro
![Large GIF (490x696)](https://user-images.githubusercontent.com/56722184/76735253-7b0afc80-679f-11ea-9ce0-c8b34f63a088.gif)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
