### ISSUE TITLE
Datagrid "In Range" filter not working on manual input

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#357]
**Describe the bug**
This is related to JIRA ticket [SOHO-8146](https://jira.infor.com/browse/SOHO-8146) filed on June 19.
Gently following up this one.

For DateTime Columns, using the "In Range" filter should display the dates that fall on the range specified. The issue is when user manually inputs the range in the filter box, the correct results are not displayed. However, when user selects the range from the date picker, the correct results are displayed.

**To Reproduce**
1. Go to http://480-sohoxi.demo.design.infor.com/components/datagrid/test-editable-datetime.html
2. Manually filter the "Order Date" column using "In Range", manually type in the values (e.g. 3/15/2016 - 3/16/2016)

**Expected behavior**
The order dates falling in the range of 3/15/2016 - 3/16/2016 should be filtered.

**Screenshots**
![image](https://user-images.githubusercontent.com/41028784/42741459-faf23314-88e4-11e8-8cc5-9cb6789949f0.png)

Manually inputting the range of 3/15/2016 - 3/16/2016:
![image](https://user-images.githubusercontent.com/41028784/42741469-22748086-88e5-11e8-9895-f5a29640037c.png)

If user selects the range in the date picker, the filter is applied:
![image](https://user-images.githubusercontent.com/41028784/42741481-41ab1afa-88e5-11e8-87b7-547f825b788b.png)

**Comment by tmcconechy** [comment]
We need to modify this example http://localhost:4000/components/datagrid/test-editable-datetime.html to see the issue right? Im not seeing any ranges to test here on that page

**Comment by tmcconechy** [comment]
Closing this issue for now due to not having a way to test it and due to age of the issue.
