### ISSUE TITLE
Lookup Single Select Component: Required error alert still appears able user selects a product 

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3570]
**Describe the bug**
Lookup Single Select Component: Required error alert still appears able user selects a product 

**To Reproduce**
1. Go to url: https://master-enterprise.demo.design.infor.com/components/lookup/example-index.html
2. Click inside the "Products" field box and then tab out of it
3. Tab back into the "Products" field and click on button to view all Products
4. In the Keyword field box type in "Another Compressor", click the enter key and then select "Another Compressor" from the list box.
5. In the "Products" field box the number "2445204" Then tab of of the field box 
4. See error here is that when the user tabs out of the "Products" field box is still showing the "Required". Please see screen shot attached. 

**Expected behavior**
When there is a Product number is in the product field box the "Required" icon should be gone

**Version**

- ids-enterprise: [v4.26.]

**Screenshots**
![Lookup_SingleSelect_Error](https://user-images.githubusercontent.com/39101346/75787422-b2f05980-5d34-11ea-9f0e-682d055ff5da.png)

**Platform**
 - All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
We couldnt reproduce it more than once
