### ISSUE TITLE
Checkbox Component: Required icon are different on uplift, dark contrast them

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3575]
**Describe the bug**
Checkbox Component: Required icon are different on uplift, dark contrast them

**To Reproduce**
1. Go to url: https://4260-rc0-enterprise.demo.design.infor.com/components/checkboxes/example-index.html?theme=uplift&variant=dark
2. Click on select and deselect the "Required" so an error shows
3. Change theme to vibrant
3. Click on select and deselect the "Required (No Indicator)" so an error shows

**Expected behavior**
The error alert icons should look the same. Please see screen shot attached. 

**Version**

- ids-enterprise: [v4.26.0]

**Screenshots**
<img width="241" alt="Screen Shot 2020-03-03 at 3 55 30 PM" src="https://user-images.githubusercontent.com/814283/75818730-6c682280-5d67-11ea-8848-11a22d0c227f.png">

**Platform**
 - Chrome/mac (any)

**Additional context**
Looks like one error has `#icon-error-alert` and the other has `#icon-error`, the code should add the same one. (`icon-error-alert` i think).

**Comment by tmcconechy** [comment]
@CindyMercadoReyes i tried to take a look but they seem the same to me?

<img width="216" alt="Screen Shot 2020-03-03 at 3 45 13 PM" src="https://user-images.githubusercontent.com/814283/75817944-0a5aed80-5d66-11ea-9cf1-57465bfa3758.png">

Also the image is missing, so that might help to re-add.

**Comment by jbrcna** [comment]
**QA Passed**
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/checkboxes/example-index.html?theme=soho&variant=dark

![image](https://user-images.githubusercontent.com/56722184/81407971-f3be8180-916e-11ea-84bc-b169b43afeef.png)
