### ISSUE TITLE
Editor: Rich text editor UI updates

### ISSUE THREAD

**Issue by kentonquatman** [infor-design/enterprise#3577]
The rich text editor (RTE) field should be revised as part of the UI uplift initiative.
The update should address the following issues:

- Improved transitions between HTML and WYSIWYG (visual) editors. The current transition has been disorienting for some users. (https://github.com/infor-design/design-system/issues/440)
- Simplified UI. The current version has outlines around everything and boxes inside boxes.
- Clean up toolbar icons. Some icons have been scaled or squeezed.
- Make separations more distinct in the toolbar.

**Comment by jbrcna** [comment]
**Test Passed**
moving this ticket to Done column
v4.27.0-dev
https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
