### ISSUE TITLE
Editor: Starting typing on empty editor does not add p tags

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3578]
**Describe the bug**
The editor is not adding `<p>` tags in some cases and this may cause formatting issues.

**To Reproduce**
Part One:
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
2. Select and delete all text in the visual view
3. Type or past something like " ecologies paradigms wireless share life-hacks create innovative harness. Evolve solutions rich-clientAPIs synergies harness relationships virtual vertical facilitate end-to-end, wireless, evolve synergistic synergies."
4. switch to html view. the text here should be incased in a P tag

Part Two:
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
2. Select and delete all text in the HTML view
3. Type or paste something like " ecologies paradigms wireless share life-hacks create innovative harness. Evolve solutions rich-clientAPIs synergies harness relationships virtual vertical facilitate end-to-end, wireless, evolve synergistic synergies."
4. switch to html view. the text here should be incased in a P tag

Part Three:
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
2. In the code remove all content
3. Focus the editor and type or paste something like " ecologies paradigms wireless share life-hacks create innovative harness. Evolve solutions rich-clientAPIs synergies harness relationships virtual vertical facilitate end-to-end, wireless, evolve synergistic synergies."
4. switch to html view. the text here should be incased in a P tag

Part Four:
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
2. Select and delete all text in the visual view
4. Switch to html view. Should be nothing here..

**Expected behavior**
- Should always have a p tag on enter. 
- Also if the text is not in a p tag ensure it has the same line spacing.
- Delete all should not leave blank tags and empty tags

**Version**
- ids-enterprise: [e.g. v4.2.6]

**Platform**
 - Chrome
 -  Test on both windows and mac

**Comment by tmcconechy** [comment]
Fix was added to 4.26 and 4.27 as noted on the PR steps

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
