### ISSUE TITLE
Hierarchy, Deprecating paging option and mobileView option.

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#3579]
**Describe the bug**
The following options need to be removed from Hierarchy control.
- paging
- mobileView

`layout` should be used instead. For example

```
var options = {
   templateId: 'hierarchyChartTemplate',
    legendKey: 'EmploymentType',
    legend: [],
    dataset: [],
    paging: true,            <!-- deprecated
    mobileView: true,     <!-- deprecated
    layout: 'paging'        <!-- use this instead  'stacked' | 'horizontal' | 'paging' | 'mobile-only'
}
```

**Expected behavior**
Paging should still work without issue after removing these options. (User will have to update options). This will be a breaking change for anyone currently using **paging** or **mobileView** http://localhost:4000/components/hierarchy/test-paging.html

**Version**
4.27.0

**Comment by janahintal** [comment]
QA Passed. Thank you. Verified in https://master-enterprise.demo.design.infor.com/components/hierarchy/test-paging.html?theme=uplift&variant=light across all browser, OS and devices.
