### ISSUE TITLE
X close icon for closing modals

### ISSUE THREAD

**Issue by nbcp** [infor-design/enterprise#358]
Instead of just adding a cancel button, offer an x icon to the top right corner of the modal since this is also a widely accepted standard for modals. Proposed close button is similar with toasts, see image below:
![image](https://user-images.githubusercontent.com/11013464/42744126-8e154098-88fc-11e8-9892-df3d888b1a53.png)

**Comment by brianjuan** [comment]
Working as expected across all browsers and passed QA testing.
![image](https://user-images.githubusercontent.com/39508864/42871333-1d4afe6e-8a48-11e8-9604-e71135421741.png)
