### ISSUE TITLE
Modal - Validation Message Placement is off in some components

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#3587]
Originally discovered here: https://github.com/infor-design/enterprise/pull/3582#pullrequestreview-370379804

**Describe the bug**
 The Validation Error Message that displays beneath some components isn't always in a uniform, correct spot.

**To Reproduce**
- [ ] http://localhost:4000/components/modal/test-multiple-validation.html - In the first modal, the spacing between the first field and its error message, compared to the second one, is much wider.
- [ ] http://localhost:4000/components/modal/test-required-fields.html - has a layout issue on it when you tab out of the field (not new)
- [ ] http://localhost:4000/components/modal/test-validation-editor.html - tab out of the editor and the required is very far away (not new)
- [ ] Check all modal form examples:  http://localhost:4000/components/modal/ - There may be others

**Expected behavior**
The error message that displays underneath each field should be uniform in spacing/padding/margin among all fields.

**Version**
v4.25.x

**Screenshots**
![Screen Shot 2020-03-06 at 4 26 08 PM](https://user-images.githubusercontent.com/3249601/76123785-5fe20500-5fc7-11ea-86f3-1778998e716e.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
