### ISSUE TITLE
Modal - Close Tooltips attached to Toolbar Buttons when closing the Modal

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#3588]
Originally discovered here: https://github.com/infor-design/enterprise/pull/3582#pullrequestreview-370379804

**Describe the bug**
When clicking the close button to close a Modal, sometimes an attached Tooltip stays open for much longer than the modal does.

**To Reproduce**
1. Go to 'http://localhost:4000/components/modal/example-close-btn.html
2. Click on "Show Modal"
3. Hover the (X) Button and wait for the "Close" tooltip to appear
4. Click the Close button
5. Watch carefully.  When the modal disappears, the Tooltip will remain in the empty page space for up to a few seconds before it also disappears.

**Expected behavior**
The Tooltip should disappear right away.

**Version**
- v4.25.x

**Screenshots**
![Screen Shot 2020-03-06 at 4 32 22 PM](https://user-images.githubusercontent.com/3249601/76124159-147c2680-5fc8-11ea-8357-1ac8652d5c27.png)

**Comment by tmcconechy** [comment]
See this one other buttons like in calendar and places (slider maybe). It is a bit annoying. Lets fix it sometime in the next few sprints

**Comment by jbrcna** [comment]
**QA PASSED**
v4.27.0-dev
https://master-enterprise.demo.design.infor.com/components/modal/example-close-btn.html
test across all browsers
