### ISSUE TITLE
Editor: Toggling source view on a modal gives wrong width.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3594]
**Describe the bug**

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/test-modal.html
2. Click on the button
3. In the .. of the editor select source view
4. See error (width changes)

**Expected behavior**
Width stays the same as before

**Version**
- ids-enterprise: [v4.26]

**Platform**
 - Chrome

**Comment by jbrcna** [comment]
**Test Failed** 
the Width does not stay the same as before when `Uplift` theme is used. the width changes a little bit.
v4.27.0-dev
https://master-enterprise.demo.design.infor.com/components/editor/test-modal.html?theme=uplift&variant=light

**Comment by jbrcna** [comment]
The issue is now resolved. moving this ticket to Done column
