### ISSUE TITLE
Hierarchy: menu selection lost after expanding hierarchy chart

### ISSUE THREAD

**Issue by bemariepedragosa** [infor-design/enterprise#3597]
**Describe the bug**
Menu selection is lost after expanding the hierarchy org chart

**To Reproduce**
1. Go to https://codepen.io/bemuuchan/pen/abOEQzg
2. Expand the hierarchy chart

**Expected behavior**
Menu is still selected

**Proposed solution:**
File > enterprise/src/components/hierarchy/hierarchy.js

selectLeaf function
   >> add .leaf class on selector
         $('.leaf.is-selected').removeClass('is-selected');

handleEvents function >> mouseup
   >> add .leaf class on selector
         $('.leaf.is-selected').removeClass('is-selected');

**Version**

- ids-enterprise: 4.25.2

**Platform**
- Chrome

**Comment by tmcconechy** [comment]
cc @krishollenbeck ? what do you think?

**Comment by bemariepedragosa** [comment]
Hi @tmcconechy and @krishollenbeck ,
Any updates on this issue? Thank you!

**Comment by tmcconechy** [comment]
No one has had time for this yet on our end. But if you have an idea you could try a pull request. To clarify do you mean that the tab is loosing the selected (blue) indicator when you click the hierarchy to expand?

**Comment by bemariepedragosa** [comment]
Yes @tmcconechy. You can test it here https://codepen.io/bemuuchan/pen/abOEQzg.
I have a proposed solution above and @krishollenbeck agreed to it based on his response above. 

**Proposed solution:**
**File > enterprise/src/components/hierarchy/hierarchy.js**

selectLeaf function

add .leaf class on selector
$('.leaf.is-selected').removeClass('is-selected');

**handleEvents function >> mouseup**

add .leaf class on selector
$('.leaf.is-selected').removeClass('is-selected');

Thank you!

**Comment by tmcconechy** [comment]
cc @krishollenbeck what do you think about this one?

**Comment by krishollenbeck** [comment]
@tmcconechy  The codepen example doesn't seem to work anymore. I could make on in ids-enterprise project though. If I recall the issue was that tab component and hierarchy both have the same class names for selected state. Seems like an easy fix. I can create a PR for it if you would like me to do that.

**Comment by tmcconechy** [comment]
Sure thanks that would be great

**Comment by jbrcna** [comment]
**QA Passed**
v4.30.0-beta0
https://4300-beta0-enterprise.demo.design.infor.com/components/hierarchy/test-vertical-tabs.html
![image](https://user-images.githubusercontent.com/56722184/86123965-f30df000-bb0c-11ea-8f24-91320b40c6a9.png)
