### ISSUE TITLE
Editor: Toggling source view to HTML and making edits does not display dirty indicator

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#3598]
**Describe the bug**
Toggling the rich text editor to HTML mode and making changes does not display the dirty indicator. Works correctly when in Visual mode.

**To Reproduce**
Steps to reproduce the behavior to test HTML mode:
1. Go to 'https://master-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html'
2. Click on 'HTML'
3. Make changes
4. Dirty indicator does not display

Steps to reproduce the behavior to test Visual mode:
1. Go to 'https://master-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html'
2. Make changes
3. Dirty indicator displays correctly

**Expected behavior**
If the component is defined with validation, then both modes should display the dirty indicator.

**Version**

- ids-enterprise: v4.26

**Screenshots**

**Platform**
 - All

**Additional context**

**Comment by tmcconechy** [comment]
Working on other editor issues so will pick this up too. Good find, i missed that

**Comment by jbrcna** [comment]
**Test Passed** with observation
v4.27.0-dev
Dirty Indicator still displays even with no changes made. [set focus then lose focus]
Steps to replicate
1. click on Editor to set focus.
2. Tab out on Editor to lose focus. 
3. Notice that dirty Indicator is displayed.
verified in https://master-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html?

**Comment by tmcconechy** [comment]
Noted @jbrcna - not too worried about that. it seems to be working much better now

**Comment by jbrcna** [comment]
Thanks @tmcconechy . I agree, It's perfectly working fine now
