### ISSUE TITLE
Pie: Percent type rounds values. Need to be able to set decimal value

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#3599]
**Describe the bug**
The pie chart can have a show of 'percent'

 `   lines: {`
`         show: 'percent', // value, label or percent or custom function`
`	}`

The values are rounded for the integer value and this can give incorrect information. Need to be able to ask for a decimal value by setting the number of decimals

`   lines: { `
`	show: 'percent', // value, label or percent or custom function`
`	formatter: '.2%'`
`	}`

or

`   lines: {`
 `     show: 'percent', // value, label or percent or custom function`
`      decimalPlaces: '2'`
`    }`

**To Reproduce**
1. Go to /components/pie/test-101-percent.html'
2. Change the data so you have 6 equally sized pieces (value = 1)
3. set lines: { show: 'percent'  }
4. Load the chart

**Expected behavior**
That each piece would be 16.67%

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

IDS Enterprise Components - v4.25.3

**Screenshots**

![In Percent Pie Chart - all status has 1 record but percentage is confusing](https://user-images.githubusercontent.com/19823048/76353038-0f77e980-62de-11ea-8ad4-4b0e8bf7c813.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

Windows 10
Chrome Version 80.0.3987.132 (Official Build) (64-bit) 

**Additional context**
NEEDED for LMCLIENT-29756
4.0 All - Incorrect Percent Value being displayed in Enrollment Event’s Percent Pie Chart

**Comment by janahintal** [comment]
This issue is failing in Android Devices. 
Values are not showing even after hovering in the chart. 
![image](https://user-images.githubusercontent.com/45757016/81676657-bf0a3d00-9482-11ea-9268-99b5af48bcf6.png)

**Comment by EdwardCoyle** [comment]
Tested this on a Samsung Galaxy s10e.  There's no way to "hover" on a mobile device, but when long-pressing the chart slices, I can see the visibility of the tooltip with content isn't always there.  Maybe we need to re-assess this?

![Screenshot_20200512-095111_Chrome](https://user-images.githubusercontent.com/3249601/81700812-2f8b6c80-9437-11ea-9f36-3d7184e7bf3b.jpg)

**Comment by tmcconechy** [comment]
Yes i think this is a seperate issue. Maybe clicking the pie chart item also shows the tooltip so you can tap it to show?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
