### ISSUE TITLE
Tags: Recently Broke

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3604]
**Describe the bug**
Tags layout has gone awry

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tag/example-dismissible-and-clickable.html
1. See error

**Expected behavior**
As it was before ...

**Version**

- 4.27.x (current master)

**Screenshots**
![Screen Shot 2020-03-12 at 9 57 49 AM](https://user-images.githubusercontent.com/3249601/76536847-46234080-6453-11ea-8c48-ad0aec1b641c.png)

**Platform**
 - Chrome

**Additional context**
Found during testing. Im on a branch thats about two days old and it doesnt seem to happen for me.

**Comment by janahintal** [comment]
Hi, @tmcconechy noticed that the dismiss button in multi-select doesn't work in Mobile devices. Please advise if this is expected. Thank you. 

![image](https://user-images.githubusercontent.com/45757016/77033233-a2510c00-69e1-11ea-9ef7-58c2427a5530.png)

**Comment by tmcconechy** [comment]
Yeah im not 100% sure but it is not related to this layout fix. The problem is we made mobile behave different. I guess just make an issue and we will decide later.

**Comment by janahintal** [comment]
Thanks @tmcconechy. I will now move the ticket to Done and create a new ticket.
