### ISSUE TITLE
Modal:  When dialog contains a datagrid place focus on first row

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3607]
Issue:
Modal dialog currently has the option of autoFocus, to indicate whether focus should be placed on the first input element.  When the dialog contains a datagrid would like the focus to be placed on the first row when records exist. 

Solution:
Need a mechanism to have focus placed on the first row when the modal dialog contains a datagrid and not the first input element. For landmark, this pattern is used extensively for the lookup select dialog. Currently focus is getting placed on the first toolbar button, which is not appropriate.

Alternatives Considered:
Since we're in Angular, attempteded to use the elementRef.nativeElement to get to the first row in the datagrid and the to set focus to it, but this did not work. 

Testing using the existing example-modal-datagrid.html ensuring that the autoFocus option is set to true.

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/76542280-c4331780-6452-11ea-9c82-8fa62359e285.png)

**Comment by EdwardCoyle** [comment]
@claudenbach would you be able to re-test this issue against our latest `master` branch?  We made some more general improvements to the focusing system of Modals in #3717 and #3793 that seems to have fixed this issue.

In the interim I will make a PR to add a `close` button to the sample page you identified to make sure focus sits inside the Datagrid when the Modal opens.

**Comment by tmcconechy** [comment]
Also @Sovia was asking me about this. Giving me the impression should made this work by using

- autoFocus false
- setActiveCell

So maybe this is good now as is? Adding focus to specific grid is maybe to general and something you can achive in the API

**Comment by EdwardCoyle** [comment]
I actually didn't make any more Modal changes in #3800, just modified the sample to add a button to the Modal header.  It seems the focus detection that was already present in the Modal/Datagrid is now working as expected.

**Comment by jbrcna** [comment]
**QA Passed**
v4.28.0-dev
moving this ticket to Done. thank you
