### ISSUE TITLE
Datagrid: Request ability to change size of datagrid with no data available

### ISSUE THREAD

**Issue by rowelineeveresurreccion** [infor-design/enterprise#3609]
**Is your feature request related to a problem? Please describe.**
When there are 2 or more datagrids that are being used in one page that has no available data to show, it takes up unnecessary spaces. 

![image](https://user-images.githubusercontent.com/50350478/76580040-67deff00-6509-11ea-82f0-1a223c07ba3e.png)

**Describe the solution you'd like**
Kindly change the datagrid size to smaller size when there are no available data to show.
Having a datagrid like below even if it can’t have the message “no data exist”s and is just blank is nicer and easier for display purposes.

**Describe alternatives you've considered**
Hiding the datagrid without no available data to show has been considered but it will be confused by the user that the page has no ability to show a certain data they are looking for.

From This:

![image](https://user-images.githubusercontent.com/50350478/76580081-9c52bb00-6509-11ea-91cc-8842da4b619b.png)

To this:

With either blank second line or if it can be done – the words “No Data Available”. Users can then double click the box to be taken to the relevant form to insert records etc.

![image](https://user-images.githubusercontent.com/50350478/76580113-ba202000-6509-11ea-966c-4bdde3fa35fa.png)

**Additional context**
When datagrids are heavily used on a page, it takes up more space especially when several datagrids don’t show any available data.
The enhancement is to be able to show grids where no data currently exists to a smaller version that obviously will allow expansion when more records are added.

**Comment by tmcconechy** [comment]
I dont really understand the screen shot of what you want to achieve.

It should only take up the space that you give the datagrid and there is a  min-height: 300px; otherwise. So thats currently the smallest size.

But it could make sense to allow some more options to be set like a emptyMessage height and width. Could you please upload a reduced test case we can work with as I'm not sure i fully understand the use case.

**Comment by sharmainerivera** [comment]
Hi, Tim.
Here’s how the datagrids are heavily used on our summary forms:

![image](https://user-images.githubusercontent.com/61222084/76714883-91479700-6764-11ea-8e5e-24e5a8adf0bb.png)

To save spaces on the form and also avoid unnecessary scrolling, we would like to change the datagrids without data to something like this:

![image](https://user-images.githubusercontent.com/61222084/76714917-be944500-6764-11ea-9eb6-a7a3d7b28205.png)

Let us know if you have other concerns. Thanks!

**Comment by tmcconechy** [comment]
Ok, Sounds good I was confused that the text looked like a record in the original screen shot.

**Comment by janahintal** [comment]
Hi Guys, noticed the following error upon testing the changes in 
https://master-enterprise.demo.design.infor.com/components/datagrid/test-empty-message-small.html?theme=uplift&variant=light&colors=0066D4

Also the empty message font size remains the same even after changing the grid to extra small
![image](https://user-images.githubusercontent.com/45757016/88782996-d672df80-d1c0-11ea-9ca7-d9d8d8bf21e0.png)

**Comment by tmcconechy** [comment]
Will fix this... Same as https://github.com/infor-design/enterprise/issues/4154#issuecomment-665596889

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://4310-rc0-enterprise.demo.design.infor.com/components/datagrid/test-empty-message-small.html?theme=uplift&variant=dark&colors=0066D4

![image](https://user-images.githubusercontent.com/45757016/89375758-efc7de80-d720-11ea-91c6-72a95ccbb706.png)
