### ISSUE TITLE
Icon: Refactor xlink:href to href

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3611]
**Is your feature request related to a problem? Please describe.**

As per https://css-tricks.com/on-xlinkhref-being-deprecated-in-svg href is correct and xlink:href is actually deprectaed. Found this fixes angular to work with ivy.

**Describe the solution you'd like**
Since the NG project will use `<use href="{{iconName}}"></use>` we should do the same in our demo app.

**Describe alternatives you've considered**
Not doing it and being inconsistent

**Additional context**
Tested that it does work in IE 11

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done column.
