### ISSUE TITLE
Modal : Close / Cancel button is not working

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3615]
**Describe the bug**
Modal : Close / Cancel button is not working

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/modal/example-cancel-close.html
2. Click on Cancel or Save button to close the modal

**Expected behavior**
Modal should close

**Version**
IDS beta 4.270-dev

**Screenshots**

**Platform**
All platform Mobile & Desktop. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
@EdwardCoyle  Can you take a look. Probably due to the buttons PR. I remember this failed when testing that PR at the time.

For example https://4220-enterprise.demo.design.infor.com/components/modal/example-cancel-close.html works ok

**Comment by janahintal** [comment]
QA Passed. The issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/modal/example-cancel-close.html?theme=uplift&variant=light
