### ISSUE TITLE
Modal: Not opening after closing it in iOS device

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3616]
**Describe the bug**
Modal is not opening after closing it in iOS device.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/modal/example-close-btn.html
2. Open the Show Modal button 
3. Close the button or Click Cancel
4. Click “Show Modal” button 

**Expected behavior**
Modal will open again

**Version**
IDS Beta 4.270dev

**Screenshots**
N/a

**Platform**
IOS Mobile Devices 
Tested in Iphone 11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Maybe this one too?

**Comment by EdwardCoyle** [comment]
@janahintal I retested this against the latest master on an iPhone 11 simulator, and wasn't seeing this as an issue.  However, I did smooth out this sample and some others, which I'll be PRing shortly.

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/modal/example-close-btn.html
