### ISSUE TITLE
Tooltip: Using Popover with a tooltip on the same object (button) causes conflicts

### ISSUE THREAD

**Issue by edgarinfor** [infor-design/enterprise#3621]
**Describe the bug**
When replacing the deprecated **soho-popdown** with a **soho-tooltip [popover]="true"**, the opening element's "**title**" attribute becomes the header of the **popover** and it no longer shows on hovering that element as a _tool-tip_.

This means that an element cannot have a tool-tip independent from its popover; which could be done before.

![soho_popdown_vs_popover](https://user-images.githubusercontent.com/39097500/76876098-d0024d80-6847-11ea-96ef-60e1cd273fc1.png)

**To Reproduce**
This can be reproduced in the demo by simply trying to use a **soho-tooltip** as a popover, for example:
```html
<button soho-button="icon" title="This is the button title..." soho-tooltip [popover]="true" ...>
```

**Expected behavior**
For popovers, you may want to have a different "tool-tip" for the opening button explaining what it does ("hint") and display a different popover header or **no header at all**.

We can reproduce the desired results if we do something like this:
```html
<button soho-button="icon" [attr.title]="'This is the button title...'" title="xxx" soho-tooltip [popover]="true" ...>
```
![soho_tooltip_popover](https://user-images.githubusercontent.com/39097500/76877980-8830f580-684a-11ea-9f27-1e98670a9fcd.png)

However, this might be _hacky_, and it doesn't allow you to have a soho formatted tooltip (in case you want it).

**Version**
- ids-enterprise-ng: 7.0.0-dev.20200219

**Platform**
 - OS Version: Windows 
 - Browser Name: Chrome
 - Browser Version: Latest

**Comment by tmcconechy** [comment]
Actually this is a little confusing. What do we want to do exactly? Have a popup (either popover or popdown) and a tooltip on the same button?

For one thing they both cant work on hover. Seems like it might be a lot of work to sort out popdown vs popover.

**Comment by edgarinfor** [comment]
Yes, we need to have both a tool-tip and a popup on the same button: when you hover it, we want to show you a hint telling you what the button is for (typical tool-tip use-case); and, when you click on it, we want to show you the popover (typical popdown scenario).

A popover could replace the tooltip if it opens on "hover" but, on "click" they are not mutually exclusive and that's where the conflict happens.

**Comment by tmcconechy** [comment]
yeah exactly, it is sort of a known issue. but we can probably figure out something. will possibly be breaking and/or a big change

**Comment by tmcconechy** [comment]
Descoping this issue for now but we rebuilt the popop and tooltip so they wont conflict. This will be working in 5.0 web components when thats eventually released
