### ISSUE TITLE
Field Filter drop down filter is misaligned 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3625]
**Describe the bug**
Field Filter drop-down  filter is misaligned 

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/field-filter/example-short.html?theme=uplift&variant=contrast
2. Minimize the screen 
3. Open the Time PIcker
4. Click the Dropdown filter for AM/PM

**Expected behavior**
Dropdown records should be aligned 

**Version**
IDS Beta 4270

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/76937318-8bea7800-692f-11ea-954e-939c65d65012.png)

**Platform**
All Browser & OS

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This should be fixed by https://github.com/infor-design/enterprise/pull/3596 when its done.
