### ISSUE TITLE
Field Set label it cut off when in responsive view 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3626]
**Describe the bug**
FieldSet label it cut off when in responsive view 

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/fieldset/example-50-50.html?theme=soho&variant=light
2. Minimize the screen to responsive view 
3. Scroll down to bottom
4. Notice that you cannot see the field as the label is cut off

**Expected behavior**
Field label should not be cut off

**Version**
IDS Beta 4.270

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/76940415-2ef1c080-6935-11ea-9b35-0fe2b0408c9e.png)

**Platform**
All desktop browsers, OS and browser. 

**Additional context**
n/a

**Comment by tmcconechy** [comment]
Going to call this too minor to worry about.
