### ISSUE TITLE
Fieldset: Fields are overlapping when in not in compact mode 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3627]
**Describe the bug**
Fieldset fields are overlapping when in not in compact mode 

**To Reproduce**
1. Open Mobile Browser or Minimize the PC Browser 
2. Go to https://master-enterprise.demo.design.infor.com/components/fieldset/example-short.html?theme=soho&variant=contrast
3.  Notice that the fields are overlapping

**Expected behavior**
Fields/text should not overlap 

**Version**
IDS Beta 4.270

**Screenshots**
Both in Soho and Uplift theme 

![image](https://user-images.githubusercontent.com/45757016/76941895-c6581300-6937-11ea-9632-f1076178bb7c.png)

**Platform**
Mobile Devices / Web responsive view 
All Platform

**Additional context**
N/a

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
