### ISSUE TITLE
Datagrid: Empty table even if keyword search has results

### ISSUE THREAD

**Issue by raymondfrancisco** [infor-design/enterprise#3629]
Table is empty when you move to other page then search using the keyword filter. 
If "Enter" key is pressed twice the expected result will be displayed.

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-paging-client-side
2. Click Next Page
3. Type "Compressor 0" in the keyword input box

**Expected behavior**
The "Compressor 0 " record should be displayed.

**Version**
- ids-enterprise: 4.26.1

**Screenshots**
![1st](https://user-images.githubusercontent.com/8829002/76942319-83e30600-6938-11ea-9bcd-a58fde40411d.png)
![2nd](https://user-images.githubusercontent.com/8829002/76942349-92312200-6938-11ea-9c6b-71de5b8885c3.png)

**Platform**
 - OS Version: Windows 10 
 - Browser Name: chrome
 - Browser Version: 80.0.3987.132 (Official Build) (64-bit)

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side.html?theme=uplift&variant=light will retest once beta is released.
