### ISSUE TITLE
Datagrid: Needs Tag formatter that will handle clickable tabs

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#3631]
**Describe the bug**
New clickable tags do not have an implementation in the TagFormatter

**To Reproduce**
1. make a datagrid with a tag column
2. see > right caret icon is not formatted to be smaller and caret color is wrong.

**Expected behavior**
to behave like other linkable tags
https://master-enterprise.demo.design.infor.com/components/tag/example-linkable.html

**Version**
4.26

**Platform**
 - Windows 10
 - Browser Name Chrome

**Additional context**

**Comment by tmcconechy** [comment]
One example with `Formatters.Tag` http://localhost:4000/components/datagrid/test-alerts.html` (of 9 that show it).

**Comment by jbrcna** [comment]
**QA Passed** with observation. 
@tmcconechy let me know if I need to file a separate issue.
v4.28.0-dev
verified in 
https://master-enterprise.demo.design.infor.com/components/datagrid/test-alerts.html

**Observation:**
IE11
![image](https://user-images.githubusercontent.com/56722184/79323788-3f4f8800-7f41-11ea-9733-3bc8da3adf9c.png)

FIrefox
![image](https://user-images.githubusercontent.com/56722184/79323818-4a0a1d00-7f41-11ea-96cd-b1959fdfcc84.png)

**Comment by tmcconechy** [comment]
Lets skip that. Not worth the effort as we we soon not support IE 11
