### ISSUE TITLE
Lookup: No title header when opened inside a datagrid

### ISSUE THREAD

**Issue by sharmainerivera** [infor-design/enterprise#3635]
**Describe the bug**
When a lookup is opened inside a datagrid, it doesn't have a title header.

**To Reproduce**
1. Open a lookup inside a datagrid by clicking the magnifying glass 
(reference: https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html)

**Expected behavior**
There should be a title header for a datagrid lookup just the same as a standalone lookup has. 
(reference: https://master-enterprise.demo.design.infor.com/components/lookup/example-clientside-paging-with-filtering.html)

**Version**
- ids-enterprise: v4.27.0-dev

**Screenshots**
Standalone lookup opened has title header:
![image](https://user-images.githubusercontent.com/61222084/77015911-2d65de00-69b1-11ea-875a-7025e6295c19.png)

Datagrid lookup opened has no title header:
![image](https://user-images.githubusercontent.com/61222084/77015731-97ca4e80-69b0-11ea-96fc-ffdc74ca188f.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 80.0.3987.132 (Official Build) (64-bit)

**Additional Context**
Having title header for datagrid lookup will help the user in identifying the current lookup he/she is looking into especially if there are multiple lookups inside a datagrid that are editable.

**Comment by tmcconechy** [comment]
- Fix the layout issue (title should be centered)
- Make the dialog pick up the editorOptions lookup title setting or default it to the column name if not provided.

**Comment by janahintal** [comment]
Thi issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html?theme=soho&variant=dark across all platform. 
![image](https://user-images.githubusercontent.com/45757016/79118774-5b2c2000-7dc1-11ea-96fe-4f92a81cad0f.png)
