### ISSUE TITLE
Hierarchy: Separators aren't supported in actions menu

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3636]
**Describe the bug**
A separator isn't supported in the actions menu on a hierarchy leaf.

**To Reproduce**
1. In app/data/orgstructure-original.json, the [actions array](https://github.com/infor-design/enterprise/blob/master/app/data/orgstructure-original.json#L31), add a actions that is {"value": "", "url": "#", "data": {"id":"separator","label":"","type":"separator"}}. Save and launch the server
2. Navigate to /components/hierarchy/example-context-menu-with-details.html
3. Click on the ... button on the Kaylee Edwards leaf

**Expected behavior**
A menu separator should appear, instead of a blank line. Like any other popupmenu

**Version**

- ids-enterprise: v4.27.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/77084546-1af99d80-69cd-11ea-9bff-bdccd6c264ea.png)

**Platform**
 - All

**Additional context**
I believe the [getActionMenuItems in hierarchy.js](https://github.com/infor-design/enterprise/blob/master/src/components/hierarchy/hierarchy.js#L367) needs to be updated to check the a.data.type === 'separator', and just add a `<li class="separator">` in that case (having the a in the li causes it to display as an entire blank line)

**Comment by janahintal** [comment]
QA Passed. This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html?theme=uplift&variant=light across all platform 
![image](https://user-images.githubusercontent.com/45757016/79118415-76e2f680-7dc0-11ea-9737-cf4aa47ac1c2.png)
