### ISSUE TITLE
TextArea: Text not visible in safari

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3638]
**Describe the bug**

**To Reproduce**
1. Use Safari Mac (latest)
1. Go to https://master-enterprise.demo.design.infor.com/components/textarea/example-index.html
1. See that the text is invisible in the disabled input

**Expected behavior**
Text should be visible

**Version**
- ids-enterprise: [e.g. v4.26.1]

**Platform**
  - OS Version: [iOS or mac]
 - Browser Name [safari]

**Additional context**
Ms Teams

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. Thanks. 
Verified in https://master-enterprise.demo.design.infor.com/components/textarea/example-index.html
![image](https://user-images.githubusercontent.com/45757016/77410601-13cff680-6df6-11ea-8512-cc479a942deb.png)
