### ISSUE TITLE
Autocomplete: Stealing focus from other controls on pop down

### ISSUE THREAD

**Issue by 100Jason** [infor-design/enterprise#3639]
**Describe the bug**
When doing an autocomplete with ajax (or URL) for source, if the user is a fast typist and tabs off the field before the autocomplete results come back, autocomplete steals the focus back to do the popdown. 

**To Reproduce**
1. Add another field after the states on the example ajax demo https://design.infor.com/code/ids-enterprise/latest/demo/components/autocomplete/example-ajax
2. In the autocomplete field, type in Utah really quick and press tab
3. The next field gets the focus and then loses it back to the original one when it pops down. On slightly slower connections, this is very noticeable. I've been doing data entry into the next field when it suddenly stole focus back.

**Expected behavior**
If the Ajax call returns and the linked field does not have focus anymore, it should not proceed with the popup.

**Version**
v4.26.1

**Platform**
Chrome current version

**Comment by janahintal** [comment]
This issue is now resolved. 
Verified in https://master-enterprise.demo.design.infor.com/components/autocomplete/test-focus?theme=uplift&variant=light thank you.
