### ISSUE TITLE
Datagrid: Row item is undefined when grid cell click event fired via Enter key

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#3645]
**Describe the bug**
The row "item" parameter is undefined when a grid cell click event is fired via the Enter key. When using a mouse click, then item is populated properly.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-form-buttons.html
2. Click on the "Action" button in one of the grid cells of the last column
3. See in the console that the "item" arg is populated
4. Now with that same grid cell in focus hit the Enter key
5. See in the console that the "item" arg is undefined

**Expected behavior**
The "item" arg should be populated properly in both cases.

**Version**
v4.26.2

**Suggested Fix**
There is a very simple fix for this issue. In datagrid.js line 8056 should use **rowNode** instead of **node** like this...

`const item = self.settings.dataset[self.dataRowIndex(rowNode)];`

**Platform**
 - Device: Dell laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 80.0.3987.149 (Official Build) (64-bit)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
