### ISSUE TITLE
Dropdown: Unaligned Dropdown when using Compound Field

### ISSUE THREAD

**Issue by Mark-Pearson1** [infor-design/enterprise#3647]
**Describe the bug**
Using Compound Field with Dropdown and a different component, the Dropdown sits below the other component by around 5px.

**To Reproduce**
1. Go to Directory List 
2. Click on Forms then Example Forms (https://master-enterprise.demo.design.infor.com/components/form/example-forms.html)
3. Scroll down to Dropdown and Button in Compound Field
![image](https://user-images.githubusercontent.com/62523135/77261973-53a5b980-6ce2-11ea-878b-6a5cd3084728.png)

**Expected behavior**
The dropdown is aligned with the component its compound with.

**Version**
4.27.0-dev

**Screenshots**
I've tested with several components to see what its unaligned with.
![image](https://user-images.githubusercontent.com/62523135/77262062-20175f00-6ce3-11ea-9cab-0da9bddc9029.png)
![image](https://user-images.githubusercontent.com/62523135/77262065-286f9a00-6ce3-11ea-82c4-a15805f253c2.png)
![image](https://user-images.githubusercontent.com/62523135/77262069-32919880-6ce3-11ea-952a-9cdda1ea4702.png)
![image](https://user-images.githubusercontent.com/62523135/77262092-4b9a4980-6ce3-11ea-8bee-27b9a90ef9a4.png)
![image](https://user-images.githubusercontent.com/62523135/77262094-56ed7500-6ce3-11ea-9e43-9754f10dfd3e.png)
![image](https://user-images.githubusercontent.com/62523135/77262110-708ebc80-6ce3-11ea-83ea-46c55547a1fb.png)
![image](https://user-images.githubusercontent.com/62523135/77262114-7a182480-6ce3-11ea-85d2-77fcd92af45c.png)
Switch appears to be completely unaligned.
![image](https://user-images.githubusercontent.com/62523135/77262124-92883f00-6ce3-11ea-897a-e4f6c47d65d3.png)
![image](https://user-images.githubusercontent.com/62523135/77262128-9a47e380-6ce3-11ea-9b24-14f97fde02fe.png)

**Platform**
 - OS Version: Windows 10 
 - Browser Name: Chrome
 - Browser Version: Version 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
I tested a fix to this on _dropdown.scss by adding a margin-bottom: 5px and it appears to fix a majority of the tested components (Switch is still going to be an issue).
![image](https://user-images.githubusercontent.com/62523135/77262863-85b91a80-6ce6-11ea-966d-575a2b2d1f87.png)

![image](https://user-images.githubusercontent.com/62523135/77262961-b600b900-6ce6-11ea-8fe2-629ca0ffc6ed.png)
This is what it became, I hope my suggested fix is of help.

**Comment by tmcconechy** [comment]
Thanks. Your fix seems reasonable. Do you want to do a pull request? Also do you need all the fields in question? If not we can probably skip switch for now.

**Comment by Mark-Pearson1** [comment]
Yeah I'll do a pull request and the only thing I don't need is the switch. Thanks!

**Comment by jbrcna** [comment]
**QA Failed**
v4.27.0-dev
https://master-enterprise.demo.design.infor.com/components/form/example-forms.html
https://master-enterprise.demo.design.infor.com/components/dropdown/test-compound-fields.html
![image](https://user-images.githubusercontent.com/56722184/77514454-df217500-6eb1-11ea-8833-0a0aa5a81024.png)

**Comment by tmcconechy** [comment]
I'm not seeing this on my end... IE 11 - Windows 10:

![Screen Shot 2020-03-25 at 9 22 30 AM](https://user-images.githubusercontent.com/814283/77540845-33a8fe00-6e7a-11ea-8a79-9bbbda4c23c9.png)

**Comment by tmcconechy** [comment]
Going to descope this for the time being
