### ISSUE TITLE
Datagrid: Move icon is misaligned in IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3648]
**Describe the bug**
Datagrid: Switch icon is misaligned in IE11

**To Reproduce**
1. Open IE11 and Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-list-grouped-headers.html
2. Hover and click the Quantity column in 2nd row of Column Group Two
3. Notice that the move column icon is in the 1st column 

**Expected behavior**
Switch filter should be in the 2nd row behind Quantity Column 

**Version**
IDS Beta 4.270

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/77301723-216c7a00-6d2b-11ea-8288-2c7e7045c850.png)

**Platform**
Windows 10 IE11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Going to try to fix this.. As it is a recent change. But since its IE 11 maybe we can push it

**Comment by janahintal** [comment]
QA Passed. This issue is now resolved. Will now move to Done. Thanks.
