### ISSUE TITLE
Datagrid: Gridlines are missing when vibrant/dark is used

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3649]
**Describe the bug**
gridlines are not visible/present when you collapse a row group in `Vibrant` Theme `Dark` Variant

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-totals.html?theme=uplift&variant=dark
2. Ensure that you're using `Vibrant` Theme and `Dark` Variant
3. Collapse a row group
4. See error, Notice that grid lines are not present

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/77311341-deb29e00-6d3a-11ea-98c6-58cbb0be1690.png)

**Version**
v.4.27.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/77311079-6f3cae80-6d3a-11ea-9d9e-253130911dd8.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Yes, the dark themes should also have some border

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
