### ISSUE TITLE
DataGrid: For skipColumns need to hide the column

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#365]
**Describe the bug**
For a datagrid with a colspan function, for each skipped column need to hide the column.  Previously the column was skipped so a <td> element was not created.  This caused column alignment issues if a hideColumn() was performed. 

**To Reproduce**
See screenshots.

**Expected behavior**
The alignment of the datagrid columns is correct

**Screenshots**
Working screenshot:
![image](https://user-images.githubusercontent.com/39804038/42776327-3f8e2b38-88fc-11e8-807d-0c8b983b3f42.png)

Without the fix screenshot:
![image](https://user-images.githubusercontent.com/39804038/42776396-73f23e96-88fc-11e8-954d-be9ad8d5dd1e.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
This was resolved on PR https://github.com/infor-design/enterprise/pull/366
