### ISSUE TITLE
Modal: Field focus could not be de-focused in IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3655]
**Describe the bug**
Modal: Field focus could not be de-focused in IE11

**To Reproduce**
1. Open IE11 browser and Go to https://master-enterprise.demo.design.infor.com/components/modal/test-iframe.html
2. Mouse click outside of the modal on the overlay to defocus the 1st field 

**Expected behavior**
No fields should be focused 

**Version**
IDS Beta 4.270

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/77387677-094b3800-6dc9-11ea-81d4-6ac40f6f1518.png)

**Platform**
Windows10 IE11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping this issue for now because of https://github.com/infor-design/enterprise/issues/3756
