### ISSUE TITLE
Editor: dirty indicator not being reset when changes are in HTML mode

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#3662]
**Describe the bug**
The dirty indicator on an editor does not reset when changes were made in HTML mode.

[example-dirty-tracking.zip](https://github.com/infor-design/enterprise/files/4381706/example-dirty-tracking.zip)

**To Reproduce**
1. Unzip the attached file to \app\views\components\editor
2. Go to '/components/editor/example-dirty-tracking.html'
3. Remove some text and click on the Reset Dirty button
4. Dirty indicator should be removed
5. Click on HTML to change modes
6. Enter or change some text and click on the Reset Dirty button
7. Dirty indicator does not get removed

**Expected behavior**
Dirty indicator should be removed.

**Version**

- ids-enterprise: 4.26

**Screenshots**
![editor-dirty](https://user-images.githubusercontent.com/20212079/77553418-c8aff500-6e82-11ea-8c15-bd13b116651e.gif)

**Platform**
 - All

**Additional context**

**Comment by jbrcna** [comment]
**QA FAILED**
v4.27.0-beta0
https://4270-beta0-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html
https://4270-beta0-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking-reset.html

In `Uplift`, when you switch from `Visual` to `HTML` and back to `Visual` Reset Button does not apply and Notice that when you go back to `HTML` again the Reset Button is working.
![Large GIF (1292x548)](https://user-images.githubusercontent.com/56722184/77716478-4279e700-7019-11ea-9e59-baaa002d7962.gif)

**Comment by tmcconechy** [comment]
@jbrcna the last point was noticed aleady and we raised it as a seperate issue https://github.com/infor-design/enterprise/issues/3670 so lets manage it from there. Fix is coming in RC

Will move this point to done

**Comment by jbrcna** [comment]
Noted @tmcconechy
