### ISSUE TITLE
Datagrid / Treegrid: Row data is not available in column serializer

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#3663]
**Describe the bug**
In a treegrid, if a column has a serializer set, the row data is sometimes undefined and not available to be used in serializer function.

**To Reproduce**
1. Use the demo page test-tree-editable.html.
2. Update description column definition to include a serializer
`
 
         var serializer = function(value, oldVal, col, row, cell, rowData) {
            return (rowData != undefined )? rowData.desc.toUpperCase() : "";
          }

          // Define Columns for the Grid.
          columns.push({ id: 'desc', name: 'Description', field: 'desc', editor: Editors.Input, isEditable: cellIsEditable, serialize: serializer  });

`
3. Bring up the demo and expand the last row.
4. Notice that the description column is blanked out.

**Expected behavior**
coerceValue should pass the tree row data just like isCellEditable

**Version**

- ids-enterprise: v4.27.0-dev

**Platform**
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version 80.0

**Comment by tmcconechy** [comment]
@deep7102 can you check this one out next? wondering if that last tree fix would help here? maybe not?

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-serializer.html?theme=uplift&variant=light
