### ISSUE TITLE
Widget Count: Needs uplift fixes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3666]
**Describe the bug**
Update the widget counts to encorporate new designs https://www.figma.com/file/UTwbDbeB1Xv34Uz6js36L4/ids-widget-counts?node-id=0%3A1 

Modify this for uplift and soho theme.

**To Reproduce**
1. Go to 'https://master-enterprise.demo.design.infor.com/components/counts/example-widget-count.html
2. Compare to https://master-enterprise.demo.design.infor.com/components/counts/example-widget-count.html?theme=uplift&variant=light
3. Compare to https://www.figma.com/file/UTwbDbeB1Xv34Uz6js36L4/ids-widget-counts?node-id=0%3A1
4. Add new aspects of the design

**Expected behavior**
Looks like new designs

**Version**
- ids-enterprise: [e.g. v4.27]

**Screenshots**
![78367228-5b693600-75df-11ea-9e91-9502088d8e06](https://user-images.githubusercontent.com/814283/78562305-1f082680-77e7-11ea-88ed-b15bd1dcc857.jpg)

**Platform**
- Any

**Comment by tmcconechy** [comment]
cc @kevinwhitedesign what do you think?

**Comment by kevinwhitedesign** [comment]
Yeah these changes generally make sense to me. Any more background on this? Specifics?

This is what I'm seeing btw:
https://www.dropbox.com/s/yjggvyenuvu01ws/Screenshot%202020-03-31%2018.24.37.png?dl=0

**Comment by tmcconechy** [comment]
Ok sounds good. Im not sure about the background. I mean in general this is just a "dashboard" of counts of certain types. The new design was something manilla provided to a team and we noticed a mismatch.

The only problem with it is that the text especially the yellow is not visible. Maybe we can come up with something with:
- the color
- an alert icon
- text that is readable with no contrast issues

**Comment by kevinwhitedesign** [comment]
Oh gotcha, thanks for that background. I remember doing a few of these in the subtle-era. 

Maybe this would work. What did you mean by alert icon?
https://www.figma.com/file/UTwbDbeB1Xv34Uz6js36L4/ids-widget-counts?node-id=0%3A1

**Comment by tmcconechy** [comment]
Yeah thats a nice treatment. Idea being just show the icon "somewhere" in case the use is color blind and cant determine the states by color alone. That could definitely work.

**Comment by dhumalkishor** [comment]
Need to provision to add label "Violation count by Role" or "Violation count by User" in widget.

**Comment by tmcconechy** [comment]
@dhumalkishor can u explain this further? I'm not sure where you wont those labels? We have a space under each count for a label. Wont that work?

**Comment by dhumalkishor** [comment]
At the bottom of the widget so user can understand this count is for which violating object.

**Comment by tmcconechy** [comment]
You mean like the title in the widget? That seems like a good place. Might need a sketch for what your suggestion to get it right

**Comment by dhumalkishor** [comment]
![Widget](https://user-images.githubusercontent.com/42198413/78367228-5b693600-75df-11ea-9e91-9502088d8e06.jpg)

**Comment by tmcconechy** [comment]
Gotcha - do you need to change it? Like maybe a dropdown?  Like on top here https://master-enterprise.demo.design.infor.com/components/cards/example-action-menu-button.html

**Comment by kevinwhitedesign** [comment]
It's a filtered view of multiple user violations? And filtered by user?

**Comment by dhumalkishor** [comment]
![Filters](https://user-images.githubusercontent.com/42198413/78558951-248a5e80-7831-11ea-9e97-1cefa141a12f.jpg)
These are the filters we are using for this widget.

**Comment by tmcconechy** [comment]
OK, So its just an extra sub label. The label being the widget title. Clarifying above.

**Comment by tmcconechy** [comment]
Cc @inforandy - for "widget stuff"

**Comment by kevinwhitedesign** [comment]
@dhumalkishor 👋 would you mind giving us a view into the background information of this usecase?

**Comment by dhumalkishor** [comment]
Hi Kevin,
We are using this widget to show violations count. There are two violating objects in our system, One is Role and second one is User. Looking at this widget user is  not able to find this count is for which object.  Currently to see object user need to go configurations every-time.

**Comment by kevinwhitedesign** [comment]
Oh awesome thanks for that @dhumalkishor what's the difference between user & role violation objects? What's the goal of a user looking at this widget? Will they look at 'high' and say to themselves, wow that's a lot I have to look into this?

**Comment by dhumalkishor** [comment]
Infor GRC is internal auditing tool for auditors. Auditor create rules by using our product and do analysis of that rules. Analysis generate violations based on rules. those violations could be for user or for role. All this violations are threat to business.

**Comment by ericangeles** [comment]
Hello @tmcconechy @kevinwhitedesign, do we have the final design for this ticket? So we can move now to the development stage. Thanks!

**Comment by tmcconechy** [comment]
The design was here https://www.figma.com/file/UTwbDbeB1Xv34Uz6js36L4/ids-widget-counts?node-id=0%3A1 but @kevinwhitedesign can let us know if it need anything more?

**Comment by ericangeles** [comment]
So there will be no text below of the widget count?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by kevinwhitedesign** [comment]
@ericangeles I suggested in the designs that this message could be indicated via the title or on hover. Sry for the delay!

**Comment by tmcconechy** [comment]
@kevinwhitedesign have a look https://master-enterprise.demo.design.infor.com/components/counts/example-widget-count.html we implemented. I think we did what you had specified 👍
