### ISSUE TITLE
Editor: Yet More Dirty Bugs

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3670]
**Describe the bug**
Found another case of dirty not resetting on the editor.

**To Reproduce**
1. go to http://localhost:4000/components/editor/test-dirty-tracking-reset.html
1. change some text
1. dirty indicator will show
1. click the button and dirty indicator will reset
1. switch to HTML view
1. change some text
1. dirty indicator will show
1. click the button and dirty indicator will reset
1. switch to Visual mode
1. change some text
1. dirty indicator will show
1. click the button and dirty indicator is not resetting

**Expected behavior**
Will reset on the last step

**Version**
- ids-enterprise: [e.g. v4.27.0]

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by jbrcna** [comment]
In IE 11 Reset Dirty button is not working.

**Comment by jbrcna** [comment]
**QA Passed** with observation
The reset button is now working in IE11. However, when you switch to `HTML view` the dirty indicator is not working. 
v42.7.0-rc1
https://4270-rc1-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking-reset.html

a separate issue was created
https://github.com/infor-design/enterprise/issues/3720
