### ISSUE TITLE
Editor Component: dirty indicator not working correctly when user changes color on the text

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3672]
**Describe the bug**
Editor Component: dirty indicator not working correctly when user changes color on the text

**To Reproduce**
1. url: https://master-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html

2. After: morph. I enter the text Cindy Test
3. I then change the color of the font from black to red
4. I then backspace and erase Cindy Test and the dirty tracker is still appearing. Please see screen shots attached
**Expected behavior**
The dirty tracker should not appear once I remove all the text

**Version**

- ids-enterprise: [v4.27]

**Screenshots**
<img width="1199" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/39101346/77698089-6b04d100-6f86-11ea-94aa-570fa3446d55.png">
<img width="1199" alt="Screen shot 2" src="https://user-images.githubusercontent.com/39101346/77698096-6dffc180-6f86-11ea-9b3e-d870be491d18.png">
<img width="1199" alt="Screen shot 1" src="https://user-images.githubusercontent.com/39101346/77698102-6f30ee80-6f86-11ea-8b30-34894dcc9862.png">

**Platform**
 - All Browser Name 

**Additional context**
None

**Comment by tmcconechy** [comment]
If i change the color of the text and then reset it, the dirty indicator does not reset. It could but thats minor.

If i remove all the text entirely that was just added I do see the indicator getting removed tho. Did you make sure to even remove the extra space and backspace right up to the dot?

**Comment by tmcconechy** [comment]
Descoping this for now
