### ISSUE TITLE
Datagrid: Change Theme & Variant is not working 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3676]
**Describe the bug**
Datagrid: Change Theme & Variant is not working 

**To Reproduce**
1. Go to https://4270-beta0-enterprise.demo.design.infor.com/components/datagrid/example-list-grouped-headers.html?
2. Change Theme to Uplift & Variant to Dark

**Expected behavior**
Theme and Variant will be changed 

**Version**
Beta 4.270 

**Screenshots**
N/a

**Platform**
All Browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Cannot reproduce this?

1. go to the link https://4270-beta0-enterprise.demo.design.infor.com/components/datagrid/example-list-grouped-headers.html in chrome mac
1. select uplift (sublte) - which is already the them
1. select dark - changes as expected
2. results in https://4270-beta0-enterprise.demo.design.infor.com/components/datagrid/example-list-grouped-headers.html?theme=soho&variant=dark as expected

**Comment by tmcconechy** [comment]
Descoping this for now
