### ISSUE TITLE
Datagrid: Borders are  too close with the checkbox in responsive mode

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3677]
**Describe the bug**
Datagrid: Borders are  too close with the checkbox in responsive mode

**To Reproduce**
1. Go to https://4270-beta0-enterprise.demo.design.infor.com/components/datagrid/example-modal-datagrid.html
2. Open the Modal
3. Minimize the screen 

**Expected behavior**
Border/grids should be consistent 

**Version**
4.270 beta 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/77902022-21ccbe00-72b3-11ea-9e36-253b13f29252.png)

**Platform**
 All Browser, OS and devices

**Additional context**
N/a

**Comment by CindyMercadoReyes** [comment]
This ticket failed. The alignment is still off for Win 10 IE 11 on Uplift theme. Please see screen shot attached. 

![bs_win10_IE_11 0(10)](https://user-images.githubusercontent.com/39101346/78294207-f4248680-74f7-11ea-8232-e554cd0fdb31.jpg)

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. Thank you. 
Verified  in https://4270-rc1-enterprise.demo.design.infor.com/components/datagrid/example-modal-datagrid.html?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/45757016/78661274-09871f80-7901-11ea-92ba-fb725cc26470.png)
