### ISSUE TITLE
Datagrid: Search filter is not  working in Datagrid with pager

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3678]
**Describe the bug**
Datagrid: Search filter is not  working in Datagrid with pager

**To Reproduce**
1. Go to https://4270-beta0-enterprise.demo.design.infor.com/components/datagrid/example-paging.html
2. In Product Id - Search '9'

**Expected behavior**
Search for '9' in product Id should e working

**Version**
IDS Beta 4.270

**Screenshots**
n/a

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
