### ISSUE TITLE
Modal: Max Call Stack Error on Lookup in a modal

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3682]
**Describe the bug**
LM is having an issue on modals where the console will show a max call stack exceeded error and stop on modals.

**To Reproduce**
Steps to reproduce the behavior (vague as i cannot reproduce yet)
1. Make a modal with a lookup that in turn has a modal on it.
2. Open the modal and click the lookup
3. See error

**Expected behavior**
No Error

**Version**
- ids-enterprise: [e.g. v4.27]

**Screenshots**
![Screen Shot 2020-03-30 at 2 53 29 PM](https://user-images.githubusercontent.com/814283/77950272-3f3f5f00-7296-11ea-8971-3d6d45b5bdb8.png)

**Platform**
- Windows

**Additional context**
Ed has a fix on a workin branch

**Comment by EdwardCoyle** [comment]
Going to fix as part of the changes on infor-design/enterprise-ng#705, since there's quite a bit of nested modal and focus-related changes.

**Comment by tmcconechy** [comment]
And just port the focus changes back? Or PR the whole thing on 4.27?  Up to you what you think is best to get a fix for this in 4.27

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. We did regression testing on  MODALS today.
