### ISSUE TITLE
Locale: Af-Za Locale is missing translations

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3685]
**Describe the bug**
The file from the translation team was missing some translations for africaans.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?locale=af-ZA
2. Click on the filter rows dropdowns
3. See error: Should not be english here.

**Version**
- ids-enterprise: [v4.27]

**Additional context**
Ms Teams

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
