### ISSUE TITLE
Field Filter: label is displayed incorrectly when initially hidden

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3687]
**Describe the bug**
Labels are being incorrectly seen in the collapsed filter field. This is only happening when the fields are initially hidden (using the hidden class) and then displayed.

**To Reproduce**
1. Copy [test-initially-hidden.zip](https://github.com/infor-design/enterprise/files/4410571/test-initially-hidden.zip) into /app/views/components/field-filter
2. Navigate to "/components/field-filter/test-initially-hidden.html"
3. Click the Toggle Fields button

**Expected behavior**
A collapsed filter field should only show the icon, and no label.

**Version**

- ids-enterprise: 4.28-dev

**Screenshots**
![FieldFilterCollapsedDisplayIssue](https://user-images.githubusercontent.com/22107636/78056545-f3022680-734a-11ea-91c2-696eeb807b69.gif)

**Platform**
 - All

**Comment by Sovia** [comment]
I may have messed up your label, sorry @tmcconechy

**Comment by janahintal** [comment]
Hi @tmcconechy , the issue is now fixed in Soho theme but when in Uplift theme, the last fields became unaligned. Please see screenshot below. 

![image](https://user-images.githubusercontent.com/45757016/78341616-93b24980-75ca-11ea-8c54-c972644bc90b.png)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://4270-rc1-enterprise.demo.design.infor.com/components/field-filter/test-initially-hidden.html?theme=uplift&variant=contrast
![image](https://user-images.githubusercontent.com/45757016/78661593-9fbb4580-7901-11ea-84a5-8331ae8606f1.png)
