### ISSUE TITLE
Editor: Need ability to indicate number of rows for display

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#3688]
**Is your feature request related to a problem? Please describe.**
The editor component needs settings to control the height for Visual mode and HTML mode, similar to the textarea property of rows. This would allow applications to set and control the height without using css.

**Describe the solution you'd like**
There would be two settings: one for Visual mode and one for HTML mode, so each mode can be controlled separately. The settings are optional and if not passed, the values currently used for height are the default.

**Describe alternatives you've considered**

**Additional context**
The settings would also need to be added to ids-enterprise-ng.

**Comment by jbrcna** [comment]
**QA Failed** with observation
In `HTML view` Switching `Themes` with high contrast makes the text disappear
v4.27.0-rc0
https://4270-rc0-enterprise.demo.design.infor.com/components/editor/test-rows.html?theme=soho&variant=contrast
Browser: Safari
![image](https://user-images.githubusercontent.com/56722184/78337981-84c89880-75c4-11ea-9c94-b418164abfad.png)

Observation
![image](https://user-images.githubusercontent.com/56722184/78336422-e50a0b00-75c1-11ea-8276-e45e3b82c55b.png)

**Comment by tmcconechy** [comment]
@jbrcna can you test this again and add better steps? I wasnt able to reproduce that failure (but early in development i saw it). So i think im missing some steps.

But moving to test column, just move it back with new steps if found. I did try safari

**Comment by jbrcna** [comment]
Steps
1. Go to https://4270-rc0-enterprise.demo.design.infor.com/components/editor/test-rows.html?theme=soho&variant=contrast
2. Switch to `HTML` View
3. Switch Themes
4. See error
![Large GIF (1142x508)](https://user-images.githubusercontent.com/56722184/78537803-9b6c2b00-7822-11ea-819d-3abbf8468054.gif)

**Comment by jbrcna** [comment]
**QA PASSED**
moving this ticket to Done
v4.27.0-rc1
https://4270-rc1-enterprise.demo.design.infor.com/components/editor/test-rows.html?theme=soho&variant=contrast

Thank you @tmcconechy for acknowledging the issue
