### ISSUE TITLE
Datagrid: Sort button is cut off in expandable rows in Subtle Theme Light Variant 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3692]
**Describe the bug**
Datagrid: Sort button is cut off in expandable rows in Subtle Theme Light Variant 

**To Reproduce**
1. Go to https://4270-beta0-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row-one-only.html?theme=soho&variant=light
also in https://4270-beta0-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html?theme=soho&variant=dark
2. Select the 1st column in the 1st row of Location 
3. Click Sort Filter in Location 

**Expected behavior**
Sort icon/button should appear complete 

**Version**
Beta 4.270

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/78123062-325e6f00-7440-11ea-8e70-6d6e75573312.png)

**Platform**
All browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Agreed - I noticed this before too.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
