### ISSUE TITLE
BusyIndicator: Displaced in responsive view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3693]
**Describe the bug**
the busy indicator is not in the center of the UI but rather in the center screen

**To Reproduce**
1. Go to https://4260-rc0-enterprise.demo.design.infor.com/components/busyindicator/example-transparent-overlay.html
2. Make the browser in responsive view (`461px` x `694px)` or any size but smaller height and longer width
3. Click the `Submit` button

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/78136179-c5ee6a80-7455-11ea-8818-f01af765853d.png)

**Version**
v4.27.0-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/78136193-cab31e80-7455-11ea-9097-5cb389fa93e5.png)

**Platform**
All

**Additional context**
Mobile is working fine

**Comment by tmcconechy** [comment]
This is correct behavior when the page goes responsive the busy indicator will become centered in the parent element still which is then the whole page. The fields are fixes size though.

Nothing to fix here.
