### ISSUE TITLE
Calendar: Unable to scroll in the popup form when in Soho theme 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3696]
**Describe the bug**
Calendar: Unable to scroll in the popup form when in Soho theme 

**To Reproduce**
1. Go to https://4270-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=soho&variant=light
2. Double click any date to show the popup form 
3. Try to Cancel and scroll down. Notice it's not working. 

**Expected behavior**
Scroll should be working

**Version**
IDS 4.270 RC0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/78210598-3d1b1180-74dd-11ea-960a-bf28160b251b.png)

**Platform**
All Browser, OS and Devices. 

**Additional context**
N/a

**Comment by janahintal** [comment]
The issue is now fixed in MacOS & iOS but still exist in Windows Browser for both Soho and uplift theme. 

![image](https://user-images.githubusercontent.com/45757016/78659996-e8bdca80-78fe-11ea-8700-1096b043e8ec.png)

**Comment by tmcconechy** [comment]
Going to skip this part for IE 11 for now. As it can be fixed by making the browser bigger.
