### ISSUE TITLE
Calendar: Day & Week view is not changing after modifying the date picker to change in different date

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3698]
**Describe the bug**
Calendar: Day view is not changing after modifying the date picker to change in different date

**To Reproduce**
1. Go to https://4270-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html?theme=soho&variant=light
2. Switch to Day View 
3. Click Today 
4. Open the date picker and select April 7 
5. Open the date picker and Select to April 16 
6. Open the date picker yo Select April 9 

Issue still exist in week view

**Expected behavior**
Should be changed to the selected day/date also for selected week view

**Version**
IDS RC0 4.270

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/78232442-d9a5d980-7506-11ea-895b-20ecad9cdc93.png)

**Platform**
All Browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This is going to be the same as https://github.com/infor-design/enterprise/issues/3701

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://4270-rc1-enterprise.demo.design.infor.com/components/calendar/example-index.html?
