### ISSUE TITLE
ContextualActionPanel: Color Issues

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3700]
**Describe the bug**
the label in the button is unreadable when you do a mouse hover using high contrast

**To Reproduce**
1. Go to https://4270-rc0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-jquery.html?theme=uplift&variant=contrast
and
https://4270-rc0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html?theme=soho&variant=contrast
2. Ensure that you're using` High Contrast`
3. Hover over the button

**Expected behavior**
the label should be readable in all themes and variants

**Version**
4.27.0-rc0

**Screenshots**
snapshot from safari browser
![image](https://user-images.githubusercontent.com/56722184/78244169-a9b30200-7517-11ea-8d1f-d8eba4e3fb3e.png)

**Platform**
all

**Additional context**
also please see `Soho / Dark`
https://4270-rc0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-jquery.html?theme=soho&variant=dark
and 
https://4270-rc0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html?theme=soho&variant=dark

![image](https://user-images.githubusercontent.com/56722184/78244713-c3087e00-7518-11ea-8277-0bf47af3edcd.png)

**Comment by tmcconechy** [comment]
Easy one . Will fix it quick

**Comment by jbrcna** [comment]
**QA Passed**
The issue is now resolved. moving ticket to Done. All links mentioned above were working as expected
v4.27.0-rc1
