### ISSUE TITLE
Bar/Line: If using long y axis labels the chart will render poorly

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3702]
**Describe the bug**
When y axis labels are very long. The text is cut off. Should come up with a solution. This was a point that was mentioned on https://github.com/infor-design/enterprise/issues/2674 but missed when fixing that issue.

Also in some cases in the bar chart if the data valueis longer (say 800000) the axis will move too far to the left side.

**To Reproduce**
1. Go to http://localhost:4000/components/bar/example-index.html
2. Edit the chart data in this example to the code below

**Example One Bar Chart**
```
<script id="test-script">
$('body').on('initialized', function () {

 var dataset = [{
      data: [{
          name: 'Category AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
          value: 373,
          url: 'test',
          tooltip: 'Tooltip by Data <br> Component A <br> Information'
      }, {
          name: 'Category B',
          value: 372
      }, {
          name: 'Category C',
          value: 236.35
      }],
      name: ''  //Can be optionally passed in makes less sense with one: Group 1
    }];

  $('#bar-example').chart({type: 'bar', dataset: dataset, animate: false});

});
</script>
```

**Example Two Line Chart**
```
lineData = [{
  data: [
    {name: 'Jan | 2018', value: 12000000000000, depth: 4},
    {name: 'Jan | 2018', value: 11},
    {name: 'Jan | 2018', value: 14},
    {name: 'Jan | 2018', value: 10},
    {name: 'Jan | 2018', value: 14},
    {name: 'Jan | 2018', value: 8}
  ],
  name: 'Component A',
  id: '1'
}, {
  data: [
    {name: 'Jan', value: 22},
...
```

**Expected behavior**
Case One (line):
We need to discuss what an appropriate fix would be. ideas:
- Show the first N characters that will fit and truncate to ellipsis at a max. Show tooltip for ellipsis text
- Implement 3 size labels (long, short, abbreviated) - like we have in other charts

Case Two (Bar):
- check the code so that the `g` tag doesnt shift over

**Version**
- ids-enterprise: [e.g. v4.27]

**Screenshots**
![Screen Shot 2020-04-02 at 9 57 20 AM](https://user-images.githubusercontent.com/814283/78257815-5f566480-74c8-11ea-9299-10e84f3db1f8.png)

**Alternatives/Workarounds**
- Just use a shorter label in the code when sending it in that will fit.

**Platform**
 - Any

**Additional context**
Originally mentioned on https://github.com/infor-design/enterprise/issues/2674
cc @hohnzy

**Comment by hohnzy** [comment]
It actually affects probably all charts, not just bar one. I can see in line chart. Just give any huge number to any value, like 12000000000000 in the example bellow.

I would prefer correct width of the g element, because the labels in bar chart are object references and we want to let the user to select and copy paste (not possible with tooltip)

![image](https://user-images.githubusercontent.com/11279863/78260967-e7576100-74fe-11ea-9dd2-d87deca8c9c7.png)

**Comment by tmcconechy** [comment]
@hohnzy Thats a line chart now? So thats a slightly different issue? Can we see the data for that one looks like you changed it up for the ng example.

We can increase the scope to line and bar charts here but i think kind of too similar problems with different answers.

Anyways, I can see that in this case the g axis is just a touch off so we can try and move it there.

But for the line chart case if you put unlimited size text there is the ellipsis ok? Or we can make it have several lengths of labels you can pass like this example... https://master-enterprise.demo.design.infor.com/components/radar/test-labels.html (see how the labels change down to smaller abbreviations you provide)?

**Comment by hohnzy** [comment]
I can clearly see that you are not reading the comments. Not in the first issue, not even now.

**Comment by EdwardCoyle** [comment]
@hohnzy there's really no need for comments like that.  This is a public forum representing our company. Let's keep commentary to the issue at hand, please.

Per @tmcconechy's response:
> Anyways, I can see that in this case the g axis is just a touch off so we can try and move it there.

Seems like we've identified moving/sizing the axis correctly as the primary way to fix the problem.  The other part of his response:
> Show the first N characters that will fit and truncate to ellipsis at a max. Show tooltip for ellipsis text

The addition of a tooltip treatment is consistent with truncated text that we provide throughout IDS.  For example, [shrink this page](https://master-enterprise.demo.design.infor.com/components/toolbar/test-gtn-long-title.html) and hover the Toolbar's title -- you'll see a tooltip appear with the full text.  Per your concerns, please note that it's possible to copy/paste the full contents of the text there, even the items behind the ellipsis.

If there's anything we've missed in the assessment, please feel free to add.

**Comment by tmcconechy** [comment]
Thats a good point on copying text @EdwardCoyle - i forgot about that trick i learned not so long ago. If you have text in the browser that has ... ellipsis in it you can triple click to copy it all even when its cut off with ...

**Comment by hohnzy** [comment]
Tripple click trick is neat. that could work. I would still prefer the correct position and dimensions of the g element. Also for not to have whitespace on the right, while the left side is almost at the edge.

**Comment by jbrcna** [comment]
**QA Passed**
moving this ticket to Done. thank you
v4.28.0-dev
