### ISSUE TITLE
Lookup: Add tooltip to overflowed text

### ISSUE THREAD

**Issue by darinw** [infor-design/enterprise#3703]
When the Lookup field is overflowing the width of the input and eclipses it should have a tooltip to display the whole value

**Describe alternatives you've considered**
Current solution is to add a tooltip with the value. The downside is that it could be built in and does not react to the overflow

This is similar to the multi select which has the exact desired behavior.
https://design.infor.com/code/ids-enterprise/latest/multiselect

Seems to be a subtask to https://github.com/infor-design/enterprise/issues/1952

**Comment by ericangeles** [comment]
@tmcconechy looks like working as expected now?

<img width="439" alt="issue" src="https://user-images.githubusercontent.com/8839327/81520237-4fa72700-9376-11ea-861f-58ecf56dc23d.png">

**Comment by tmcconechy** [comment]
Yes i think we noted that this might be working. If thats the case just close it to test in 4.29 @ericangeles Thanks!

**Comment by jbrcna** [comment]
**QA Passed**
a tooltip is present now
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/lookup/test-with-tooltip.html
