### ISSUE TITLE
DataGrid: 'hideOnOnePage' should keep the page size selector for non-empty state

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise#3706]
**Description**
Soho DataGrid: When user selects number of records per page higher than total items in datagrid, the page selector disappears.

Grid Options:
hidePagerOnOnePage = true

**Steps to reproduce the behavior:**
 Select number of "records per page" higher than total items in datagrid with "hidePagerOnOnePage = true"

**Expected behavior**
"page size selector" should persist for non empty state. (It should disappear for empty state and it is already working as expected)

**Version**
enterprise-ng: 6.4.2

**Comment by tmcconechy** [comment]
Is this still needed or do you have a workaround?

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.62.0-dev.
https://main-enterprise.demo.design.infor.com/components/datagrid/test-count-in-select-all-current-page-setting.html
<img width="1545" alt="image" src="https://user-images.githubusercontent.com/56722184/160055218-92929206-8ed7-4bd6-8382-ae547bbf5e7a.png">
