### ISSUE TITLE
Swaplist: Swap buttons are all the same in Dark Variant and doesn't show enabled and disabled buttons

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3709]
**Describe the bug**
Swaplist: Swap buttons are all the same in Dark Variant and doesn't show enabled and disabled buttons

**To Reproduce**
1. Go to https://4270-rc0-enterprise.demo.design.infor.com/components/swaplist/example-disable-dragging.html?theme=soho&variant=dark
2. Notice that the disabled swap buttons on the top appear the same in dark mode (dont appear disabled)
3. Test all 6 theme/modes

**Expected behavior**
Buttons should appear enabled if enabled and disabled if disabled. 
e.g. 
![image](https://user-images.githubusercontent.com/45757016/78547211-4c79c200-7831-11ea-8dc1-f075b374558a.png)

**Version**
IDS Rc0 4.270

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/78546819-a6c65300-7830-11ea-8eea-7a1ae9bc5fbc.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Hi, @janahintal can you improve the steps? I'm not seeing any issue / or not understanding.

a) The link is dark mode but the screen shot show high contrast mode
b) hovering the items in all modes seems ok.
c) screen shot isnt showing any issues / and is cut off?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
