### ISSUE TITLE
Datagrid- Nested Grid : focus still on the parent rows

### ISSUE THREAD

**Issue by ShyamaMenon** [infor-design/enterprise#371]
**Description**
When you select a link / row within the nested grid, the focus is still on the parent link/row. As a result, the click event within the nested grid doesn’t work as expected. 

**To Reproduce**
1. http://master-enterprise.demo.design.infor.com/components/datagrid/example-nested-grids.html
2. Expand any row
3. click directly on the link i the subgrid

Result: The parent link will focus, and the event info on the column click event should be retested.

**Expected behavior**
Each row within the nested datagrid should trigger the corresponding 'click' event .

**Platform**
 - Browsers used: chrome, safari
 - SOHO version: 4.8.0

**Comment by tmcconechy** [comment]
Can you clarify how you are attaching the click? (Is it the column click function/option? or the datagrid click event?)

**Comment by brianjuan** [comment]
http://4100-beta0-enterprise.demo.design.infor.com/components/datagrid/example-nested-grids.html
Passed QA testing
