### ISSUE TITLE
Swaplist: Selected records become disabled after trying to switch in different swaplist table

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3710]
**Describe the bug**
Swaplist: Selected records become disabled after trying to switch in different swaplist table

**To Reproduce**
1. Go to https://4270-rc0-enterprise.demo.design.infor.com/components/swaplist/example-index.html?theme=soho&variant=contrast
2. Try swapping the Option D or Option K in Selected Table to the upper Selected Table

**Expected behavior**
Records should not display as disabled. 

**Version**
IDS rc0 4.270

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/78548434-64524580-7833-11ea-9378-a94c0551e3f2.png)

**Platform**
All browser, OS and devices

**Additional context**
/N/a

**Comment by tmcconechy** [comment]
hi @janahintal 
- its not an issue that you cannot drag from the lower and upper table. the example shows two different swap lists one with two and one with tree. you cannot move them between the two instances.
- was not able to see the disabled drag items. can you elaborate on getting that? maybe its an issue but not sure yet. But you cant dro from down instance up

**Comment by tmcconechy** [comment]
Descoping this for now
