### ISSUE TITLE
Pie: When there is a concentration of pie chart pieces near the top or bottom of the chart the labels overlap

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#3712]
**Describe the bug**
If the data shows a number of smaller pie chart pieces on the top or bottom of the chart the labels of the chart overlap and they cant be seen easily. 

**To Reproduce**
1. Display a pie chart with a lot of pie pieces near the top or bottom of the chart
2. Notice the overlapping of labels

**Expected behavior**
In some way the labels would still be able to be seen.

**Version**

IDS Enterprise Components - v4.28.0-dev

**Screenshots**
<img width="960" alt="PercentChart" src="https://user-images.githubusercontent.com/19823048/78566394-c5066180-77e4-11ea-9b72-66171121c4e4.png">

**Platform**
Version 80.0.3987.149 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
This is a known issue that has no fix. But i will leave this in the backlog in case we revist the chart design.

For this reason we added options to hide the labels. As they are going to intersect in one way depending on data no matter what happens. Or a very complicated solution is needed.

Suggest showing the legend instead of lines as that has a more static size.

**Comment by krahs1** [comment]
> Add any other context about the problem here.
Needed for LMCLIENT-30094

**Comment by lipetzan** [comment]
Other more severe examples at https://jira.lawson.com/browse/LMCLIENT-30094

**Comment by tmcconechy** [comment]
That might be a case where the legend version is more useful https://master-enterprise.demo.design.infor.com/components/pie/test-hide-lines.html

**Comment by tmcconechy** [comment]
cc @inforandy lets look for a design solution for this issue

**Comment by tmcconechy** [comment]
We dont have any viable solution for this. However we will be making a new chart that should work better in this situation as outlined here. https://github.com/infor-design/enterprise/issues/4587

With a lot of smaller slices this chart may be better to use for this situation. Also suggest using only a legend and no lines.

Descoping for now
