### ISSUE TITLE
Datagrid: Load data is not properly clearing selected rows

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3718]
Describe the bug
When calling loadData() to load the next set of records into the datagrid, the method unSelectAllRows() is not correctly clearing the selected rows.  Occurs when the  new dataset is smaller than the existing dataset.   

1. Using the attached test-loaddata-selected-rows.html
2. Select all records by clicking on the checkbox on the grid header
3. Click on the 'Selected Rows' button - notice the count
4. Click on 'Load Next Records' button
5. Notice that no records are visually selected
6. Click on 'Selected Rows' button - notice the count

Expected behavior
When loading a new dataset into the grid, unselected rows is cleared

Version
v4.28.0-dev

**Comment by claudenbach** [comment]
[Git-3718.zip](https://github.com/infor-design/enterprise/files/4441361/Git-3718.zip)

**Comment by claudenbach** [comment]
Did this fix make it into 6.6.2?  

When testing with 6.6.2, I'm still seeing the issue.  I expected that when I load data into the datagrid, the selected rows are unselected.

**Comment by tmcconechy** [comment]
No this fix didnt make it. Was done later in 4.28 (master) ~ future 6.7 and was not patched back.

**Comment by claudenbach** [comment]
Okay.

**Comment by claudenbach** [comment]
Can we get this fix patched into 6.6?

**Comment by tmcconechy** [comment]
Ok, But can we wait a few days maybe? Lets plan offline with @pwpatton maybe.

I dont want to keep patching every day (that would be two in one day)? Also would help in those cases to maybe add a note in advance. But if critical we can patch.

**Comment by claudenbach** [comment]
Yes, its critical and needs a patch.  I'm fine with waiting but would still need it this week.

**Comment by tmcconechy** [comment]
Ok lets plan on a patch release Thursday in case there is more so i dont keep patching each issue one by one.

**Comment by janahintal** [comment]
This issue is now resolved. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-loaddata-clear-selected-rows across all platforms. Thank you.
