### ISSUE TITLE
Enterprise 4.x Stability Analysis for Rick

### ISSUE THREAD

**Issue by theakatz** [infor-design/enterprise#372]
ToDo: Enterprise 4.x Stability Analysis--from Nick's FY19 planning  https://paper.dropbox.com/doc/Q1FY19-Planning-1PTJWJo1YscVx8aVOOop9

Current tracking: https://datastudio.google.com/u/0/reporting/1dIymCiqN-JzZz2AazBAubtNIuyXvMJ2l/page/B4gR

Notes:
- Probably should get some solid data around who actually uses the controls
- Since we are planning on updating/creating new soho controls

**Comment by swetteinfor** [comment]
I updated the dashboard to be cleaner and added todos in there - see it at https://datastudio.google.com/open/1dIymCiqN-JzZz2AazBAubtNIuyXvMJ2l 

1. We should make a ticket to help me pull the data from the github api. Thea, ask someone to decide who that would be. Then we can put time on the calendar to kick off that task. This is the only real blocker for me. 

2. hopefully we have cleaner statuses then before in github. (see image)
![screen shot 2018-08-22 at 3 10 33 pm](https://user-images.githubusercontent.com/20357266/44485084-89be1b80-a61d-11e8-8891-a0446e01bb1c.png)

**Comment by swetteinfor** [comment]
@jmacaluso711 , lets set up some time to work on the github piece!

**Comment by clepore** [comment]
@swetteinfor And @jmacaluso711 - How is the progress of this?

**Comment by swetteinfor** [comment]
Same as before, we shouldn't move forward until we can get the data into datastudio automatically (no upload process), otherwise the dashboard will become outdated very often

**Comment by theakatz** [comment]
@jmacaluso711 are you able to do that or do we need a backend guy to help?

**Comment by jmacaluso711** [comment]
Should be all on the front end, i think

**Comment by jmacaluso711** [comment]
this is done easily through the datastudio interface... I'll walk @swetteinfor through the process
