### ISSUE TITLE
Editor: Dirty indicator is not shown when using HTML view IE11

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3720]
**Describe the bug**
The dirty indicator is not displayed in `HTML` view

**To Reproduce**
1. Open IE 11  
2. Go to https://4270-rc1-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking-reset.html
3. Add/Remove some text
4. Dirty indicator should be displayed
5. Click on the Reset Dirty button
6. Dirty indicator should be removed
7. Click on HTML to change modes
8. Enter or change some text 
9. Dirty indicator is not shown

**Expected behavior**
when a user makes changes the dirty indicator should be displayed. Both in `HTML` and `VISUAL` view

**Version**
v4.27.0-rc1

**Screenshots**

**Platform**
IE11

**Additional context**

**Comment by jbrcna** [comment]
the issue is now resolved. moving this ticket to Done
verified in v4.27.1 & v4.28.0-dev

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
