### ISSUE TITLE
Tree: UpdateNode - Does not update underlying dataset

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3724]
**Describe the bug**
Calling tree updateNode with a new set of children updates the UI but fails to sync the underlying dataset. This means other functions like findById will not subsequently work.

**To Reproduce**
1. Add this attached code to app/views/components/tree/test-update-node-with-children.html
2. Load page
3. Check the console
4. The first findById works but the second fails

**Related issue**
1. go to https://master-enterprise.demo.design.infor.com/components/tree/example-sortable.html
2. try and drag an item "about us" above home
3. error: `Uncaught TypeError: Cannot read property 'parentNode' of undefined`

**New Code**

```
<div class="row top-padding">
  <div class="twelve columns">

    <ul id="tree" class="tree" role="tree" aria-label="Asset Types" data-init="false">
      <li>
          <a href="#" id="home">Home</a>
      </li>
      <li><a href="#" id="about">About Us</a></li>
      <li class="is-open">
        <a href="#" id="public">Public Folders</a>
        <ul class="is-open root">
          <li class="is-open">
              <a href="#" id="leadership">New Leadership</a>
              <ul class="is-open">
                <li><a href="#" id="new1">New Item 1</a></li>
                <li><a href="#" id="new2">New Item 2</a></li>
              </ul>
          </li>
        </ul>
      </li>
    </ul>

  </div>
</div>

<script>
  var tree = $('#tree').tree().data('tree');
  console.log(tree.findById('leadership'));

  // Update only text for folder level node
  tree.updateNode({id: 'leadership', text: 'Just Updated', children: [{ id: 'line-mgr', text: 'Line Manager', children: [{ id: 'bloc_mgr', text: 'Block Manager' }]}]});
  console.log(tree.findById('line-mgr'));
</script>
```

**Expected behavior**
Should work. Please add a functional test case for this.

**Version**
- ids-enterprise: [e.g. v4.27.x]

**Platform**
 - Chrome (or any)

**Additional context**
Infor PIM - cc @hemantg05

**Comment by hemantg05** [comment]
Thanks!

**Comment by hemantg05** [comment]
Even the tree.removeNode() API doesn't work because of this issue.

**Comment by tmcconechy** [comment]
@deep7102 could you take a look at this one next? Or if you want to take a break from charts?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
