### ISSUE TITLE
Toolbar Component: Can barely read the The word "Keyword" for search on Up lift Theme Dark Contrast

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3727]
**Describe the bug**
Toolbar Component: Can barely read the The word "Keyword" for search on Uplift Theme Dark Contrast

**To Reproduce**
1. Go to https://4270-rc1-enterprise.demo.design.infor.com/components/toolbar/example-index.html?theme=uplift&variant=dark
2. Click on the "Search" field box to expand
4. See error here is you can barely see the word "Keyword" on Uplift dark contrast (the placeholder text)

**Expected behavior**
The word "Keyword" needs to be brighter

**Version**

- ids-enterprise: [ v4.27]

**Screenshots**
![bs_win10_Edge_80 0(1)](https://user-images.githubusercontent.com/39101346/78718000-7abdd700-78ef-11ea-96ab-510de6cc463e.jpg)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 ]
 - Browser Name [Edge]

**Additional context**
None

**Comment by janahintal** [comment]
The issue still exist in Windows 10 IE 11. Thanks. 

https://master-enterprise.demo.design.infor.com/components/toolbar/example-index.html?theme=uplift&variant=contrast![image](https://user-images.githubusercontent.com/45757016/79449623-27960380-8016-11ea-97f4-6e3bfa79cc93.png)

**Comment by ericangeles** [comment]
@tmcconechy upon checking the placeholder in IE11, when an input field has focus, it returns to its normal style of the input field and placeholder will disappear. This is a known issue on IE10+ and it seems to work Edge version.

**Comment by tmcconechy** [comment]
I agree. We really cant fix this. Also IE 11 less important now. So moving to done
