### ISSUE TITLE
Popover: '...' menu is misplaced in index example page in Windows 10 IE 11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3728]
**Describe the bug**
Popover: '...' menu is misplaced in popover index example page in Win10 IE11

**To Reproduce**
1. Open IE browser and Go to https://4270-rc1-enterprise.demo.design.infor.com/components/popover/example-index.html
2. Notice the the '...' menu id misplaced

**Expected behavior**
'...' menu options should appear in the topmost right of the page.

**Version**
IDS RC1 4270

**Screenshots**
[image](https://user-images.githubusercontent.com/45757016/78774197-ede64c80-79c6-11ea-8ba6-f54644813201.png)

**Platform**
Windows 10 IE 11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Tried to test this on IE 11 - Windows 10 and did not experience this issue. It looks like maybe an error occurred and the page stopped. But it did not do it for me.

Are you able to add any more info? Or try clearing caches and doing a hard reload? Im not seeing this.

**Comment by tmcconechy** [comment]
Descoping this for now
