### ISSUE TITLE
SOHO-8173: Datagrid - when using paging, selectRows() is not correct

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#373]
After the user performs a next page request, neither of the methods selectRows or selectRow is working properly when a row number is passed.

For example:
    sohoDataGridComponent.selectRows(1);
or
    sohoDataGridComponent.selectRow(1);

Using selectRows, providing it an index, generates a javascript error (row.index is not a function) on the following statement within selectRows... 
    this.selectRow(row.index(), true, true);

Using selectRow, it doesn't find the correct rowNode because within the called method actualRowNode it performs a jquery find using the aria-rowindex, which reflects the pagesize + row index.

**Comment by brianjuan** [comment]
Followed the steps on PR #638 for the different scenarios.
Passed QA testing.
