### ISSUE TITLE
Tree: Add an option to expand on icon click only

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3730]
**Is your feature request related to a problem? Please describe.**
Currently if you click the text of the tree item it expands and then selects the item. It would be good in some cases to select and expand distinctly. Note some systems use either approach for example in Atom editor clicking a folder or the text will select + expand. But in outlook clicking a folder will only expand.

**Describe the solution you'd like**
- add an option - expandOnIconClick
- when this is true only clicking the icon part will expand, clicking the text will only select
- leads itself better on http://localhost:4000/components/tree/example-plus-minus-folders.html example
- make a new example and a test

**Describe alternatives you've considered**
Dealing with not having it.

**Additional context**
Infor PIM

**Comment by tmcconechy** [comment]
Similar and to be done with https://github.com/infor-design/enterprise/issues/3847

**Comment by janahintal** [comment]
QA Passed. Verified in https://master-enterprise.demo.design.infor.com/components/tree/test-expand-target.html?theme=uplift&variant=light&colors=0066D4 
Thanks! :)

**Comment by hemantg05** [comment]
Nice!
