### ISSUE TITLE
Icons: Update lock icon

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3732]
**Describe the bug**
Making this issue for tracking... We pushed a new update to the design system repo for new lock icons as the uplift ones did not really look like locks.

https://www.dropbox.com/s/5i01ur94mggopcw/SoHo%20Lock%3AUnlock%2004092020.sketch?dl=0
https://www.dropbox.com/s/64gcwkrthp0yb3s/Infor_lock_unlock.sketch?dl=0

**To Complete**

1. Make a design system release (we should have other changes this sprint so when that happens)
2. Make a change log entry
3. PR
4. test icons page in both themes

**Comment by jbrcna** [comment]
**QA Passed**. will retest once beta is deployed. Thank you
v4.28.0-dev
Verified in
https://master-enterprise.demo.design.infor.com/components/icons/example-index.html?theme=soho&variant=dark
![image](https://user-images.githubusercontent.com/56722184/79324962-f6003800-7f42-11ea-9c55-190d955bb8ea.png)

https://master-enterprise.demo.design.infor.com/components/icons/example-index.html?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/56722184/79325199-5b542900-7f43-11ea-829d-df4e1ed89a00.png)
