### ISSUE TITLE
SOHO-8151: [All Browsers] Data Grid Grouped Header Control: "Column Group Two" group header is disappearing when Product Name column is dragged

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#374]
1. http://master-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html

2. [All Browsers] Data Grid Grouped Header Control: "Column Group Two" group header is disappearing when Product Name column is dragged

3.Steps to reproduce: 
1. Drag Product Name column inside "Column Group Two"
2. Notice that the "Column Group Two" group header will disappear

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html
Passed QA testing, working across all browsers.
