### ISSUE TITLE
Calendar: Increase font size of events and details panel for better readability

### ISSUE THREAD

**Issue by sharmainerivera** [infor-design/enterprise#3742]
**Is your feature request related to a problem or use case? Please describe.**
The font sizes of the calendar events and panel are too small to be read by the user:
https://master-enterprise.demo.design.infor.com/components/calendar/test-specific-locale.html
![image](https://user-images.githubusercontent.com/61222084/79183053-f7e2d200-7e42-11ea-8318-cffbd6f1ef9c.png)

**Describe the solution you'd like**
The font sizes on the calendar events and details should be large enough to be readable.

**Describe alternatives you've considered**
Alternatively, there should be a setting of choice for the user to set his/her preferred font size if possible.

**Comment by tmcconechy** [comment]
One option for immediate use is to use the new uplift theme (which will actually soon by the recommended default).

It is a bit bigger https://master-enterprise.demo.design.infor.com/components/calendar/test-specific-locale.html?theme=uplift&variant=light

**Comment by sharmainerivera** [comment]
Hi, Tim. Yes. Adding more settings for user's preference is much better.

**Comment by tmcconechy** [comment]
Descoping this as we havent had bandwidth. But suggest adopting the "new" theme where the text is 16px.
Should solve it https://master-enterprise.demo.design.infor.com/components/calendar/test-specific-locale.html?theme=uplift&variant=light
