### ISSUE TITLE
Slider: Add a setting for tooltip positioning (top/bottom)

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#3746]
**Is your feature request related to a problem? Please describe.**
When using mouse control on the slider, the tooltip placement is under the cursor

**Describe the solution you'd like**
Option to select if we want tooltip on above or below the slider

**Comment by tmcconechy** [comment]
I agree with option, think actually top is better as a default as the hand cursor doesnt get in the way that way.

**Comment by jbrcna** [comment]
**QA Passed**
v4.29.0-dev (Master)
https://master-enterprise.demo.design.infor.com/components/slider/example-tooltip-position.html

![image](https://user-images.githubusercontent.com/56722184/81563636-19df5e00-93c9-11ea-8d4d-f062c72a8079.png)
