### ISSUE TITLE
Slider: Showing the tooltip from load

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#3747]
**Is your feature request related to a problem or use case? Please describe.**
The user is not able to see current value, when the component is loaded. Now the tooltip is seen only after focusing into the component.
![image](https://user-images.githubusercontent.com/11279863/79244484-3db98d80-7e77-11ea-91d1-5556a6c5df8e.png)

**Describe the solution you'd like**
When persistTooltip is set to true, the tooltip should appear immediately after load of the component. Like this:
![image](https://user-images.githubusercontent.com/11279863/79244637-6b063b80-7e77-11ea-98e8-e0c6a1aca6f3.png)

**Comment by tmcconechy** [comment]
This has been discussed. Have to bring up the old conversation i forget at the moment. @EdwardCoyle ?

**Comment by tmcconechy** [comment]
@katieinfor this is an older issue but it requires design feed back. Is the best way to show the value to show it in the tooltip? Maybe there are other options?

**Comment by katieinfor** [comment]
Jira Ticket: https://jira.infor.com/browse/UXD-2909

**Comment by tmcconechy** [comment]
As per https://jira.infor.com/browse/UXD-2909 we should go ahead with this.

a) setting to show the tooltip on page load (basically always shows?)
b) an example with an input next to it showing the value

**Comment by tmcconechy** [comment]
Final designs on https://www.figma.com/file/gHmapzCfCqqPRv5RnFfGcE/Q3-Accessibility-Tests?node-id=44%3A1364

Ready for Dev

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.59.0-dev.
verified in https://main-enterprise.demo.design.infor.com/components/slider/example-tooltip-onload-and-textbox.html

**Comment by CindyMercadoReyes** [comment]
BDD attached.
[BDDStory_github3747.docx](https://github.com/infor-design/enterprise/files/7737716/BDDStory_github3747.docx)
