### ISSUE TITLE
Datagrid: Row Reorder doesn't work when paging is used

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#3749]
**Is your feature request related to a problem or use case? Please describe.**

In a datagrid with paging, make the rowReorder = true and add the row-reorder column. On the first page the start and end index are correct. However in the second page, these numbers restart from 0 again. Each page reflects the rows visible no the dataset row index. When the row is dragged, the datagrid moves back to page 1 and the row is not moved.

I would like to have the true values of start and end index and the row to move within the page. This could be considered a bug but marking it as a feature as this combination didnt work before and is communicated as a known limitation.

![image](https://user-images.githubusercontent.com/17933529/79269617-c1b94880-7e6a-11ea-8e4b-c3c58c3849b3.png)

**Describe the solution you'd like**
If possible it would ne nice to have a way to drag between pages. But primarily because the index are wrong it can be used on multi page so having the indexes correctly will help the most.

**Describe alternatives you've considered**

We are disabling this feature for now because we can't get a workaround to work.

**Additional context**
Ms Teams..
Team: Data Catalog

**Comment by jbrcna** [comment]
**QA Passed** 
Reorder and/with paging is working as expected. reordering with paging as well as the number of records per page can now work together.
The rows stay as you had changed the order even with the number of records per page is used.
v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-row-reorder-paging.html
