### ISSUE TITLE
Datagrid: Aggregator is missing some aggregate functions

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3752]
**Describe the bug**
When trying the max aggregator its reporting errors or undefined.
Ideally Would like: Sum, Min, Max, Avg, Count (non-blank/non-null) supported

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-grouping-totals.html
2. In the example change sum to 'max'
3. Run again
4. See error -> seeing undefined not a max
5. Also test for null / undefined/ bad type of data in the data as errors are seen in the running app
6. Show an example of extending with a custom aggregator

**Expected behavior**
No errors and while in there try and add the rest of the missing functions.

**Version**
- ids-enterprise: [e.g. v4.28-dev]

**Platform**
 - Infor Application/Team Name: App Builder (Home Pages?)
 - Device:  mac
 - Browser Name: chrome

**Additional context**
Ms Teams

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://4280-beta1-enterprise.demo.design.infor.com/components/datagrid/example-index?theme=uplift&variant=light

**Comment by jbrcna** [comment]
**QA Passed** with observation
moving this ticket to Done.
v4.28.0-beta1

_Observation_
the sort function of the last column  is not working in
https://4280-beta1-enterprise.demo.design.infor.com/components/datagrid/test-grouping-aggregators-list
