### ISSUE TITLE
Datagrid: Apply compact mode

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#3755]
**Describe the solution you'd like**

When in compact mode have datagrid respond by
- use smaller font of compact mode that is used for form fields
- narrow margins and maybe datagrid line height

**Solution**
- [x]  Add a fourth row size -> and change names call them xs , small (short), med, large (normal)
- [x]  Make the section titles on form and toolbar same size (18px) as now its different
http://localhost:4000/components/form/example-compact-mode.html?theme=uplift&variant=light&colors=0066D4
http://localhost:4000/components/datagrid/example-index.html?theme=uplift&variant=light&colors=0066D4
- [x] do not change toolbar size (designer descision) 
- [x]  xs gets 14px font and 4px padding (same font size as the compact form field )
- [ ]  test filter row ect and other features
- [ ]  respond to form class

**Comment by tmcconechy** [comment]
Holding on to this for ongoing chat (Friday). Then may work on this next

**Comment by jbrcna** [comment]
**QA Failed**
The header checkbox is not fully centered.
v4.30.0-beta0
https://4300-beta0-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
![image](https://user-images.githubusercontent.com/56722184/86120186-6ceeab00-bb06-11ea-8b8e-1d65c0f38acf.png)

https://4300-beta0-enterprise.demo.design.infor.com/components/datagrid/example-beforeselect-veto.html?theme=uplift&variant=light&colors=0066D4
`Both Themes were affected`
![image](https://user-images.githubusercontent.com/56722184/86120291-9e677680-bb06-11ea-8039-0f94d004a596.png)

https://4300-beta0-enterprise.demo.design.infor.com/components/datagrid/example-disabled-rows.html?theme=uplift&variant=light&colors=0066D4
`Both Themes were affected`
![image](https://user-images.githubusercontent.com/56722184/86121003-d7541b00-bb07-11ea-88d0-e3df9a64df08.png)

https://4300-beta0-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?theme=uplift&variant=light&colors=0066D4
`Both Themes were affected`
![image](https://user-images.githubusercontent.com/56722184/86121237-46317400-bb08-11ea-9022-8b52c141ea44.png)

https://4300-beta0-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html?theme=uplift&variant=light&colors=0066D4
`Both Themes were affected`
![image](https://user-images.githubusercontent.com/56722184/86124308-834c3500-bb0d-11ea-98f5-a38eac6920e6.png)

**Comment by jbrcna** [comment]
**QA Passed**
The issues mentioned above were now resolved. Thank you.
v4.30.0-rc0
https://4300-rc0-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
![image](https://user-images.githubusercontent.com/56722184/86466744-c7864200-bd66-11ea-9990-05efdc1af5b7.png)
![image](https://user-images.githubusercontent.com/56722184/86467084-5b580e00-bd67-11ea-9760-5de0b0241827.png)

https://4300-rc0-enterprise.demo.design.infor.com/components/datagrid/example-beforeselect-veto.html?theme=uplift&variant=light&colors=0066D4
![image](https://user-images.githubusercontent.com/56722184/86466801-e4227a00-bd66-11ea-8431-c904369d57ba.png)
