### ISSUE TITLE
Hierarchy: Context menu fails to size correctly when dynamically loading actions.

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#3760]
**Describe the bug**
Context menu fails to size correctly when dynamically loading actions. Using the new stacked layout with context menu button on a card.

**To Reproduce**
1. Get new example from PR
2. Go to http://localhost:4000/components/hierarchy/example-stacked-ajax-popupmenu.html
3. Click on action menu button to get actions. (see attached gif)
4. Notice on the initial click the menu fails to size properly and is missing the scroll bar. Clicking a second time will force it to size properly.

**Expected behavior**

**Version**
v4.27.3

**Screenshots**
![scroll-issue-on-popupmenu-with-dynamic-call](https://user-images.githubusercontent.com/1056684/79504116-eabb1400-7ff7-11ea-88f8-a0fd3e0f53db.gif)

**Platform**
 - eng-landmark
 - Windows 10
 - Chrome
 - Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by janahintal** [comment]
Issue still exist in https://master-enterprise.demo.design.infor.com/components/hierarchy/example-stacked-ajax-popupmenu.html
for windows 10 browsers. 

Win10 Chrome Browser - Notice that the arrow is not aligned after the second click. 
![image](https://user-images.githubusercontent.com/45757016/79856064-6bb24b00-83fe-11ea-8ffb-2a0ff21eb3af.png)

Win10 IE11 browser - Page is not loading
![image](https://user-images.githubusercontent.com/45757016/79856471-fabf6300-83fe-11ea-8ae8-4b5008a77d73.png)

**Comment by krishollenbeck** [comment]
@tmcconechy I have a fix for the IE11 issue. Should I reopen this? Or create a new ticket? @janahintal , For the chrome issue. Do you still have to click twice to get the menu to size properly?

**Comment by krishollenbeck** [comment]
@tmcconechy, What do you think about that arrow? In my opinion I think it should be removed. I don't think it will ever look proper on menus with big menus. I tried to move the details outside of the popupmenu and inside the wrapper. But the popupmenu control doesn't seem to size correctly when I do that. I am guessing it probably doesn't account for stuff being outside of the `<ul>` when setting the height on the `<ul>`

**Comment by tmcconechy** [comment]
@krishollenbeck yes as discussed on line the arrow can be minor issue. If we want to improve it or leave it. Arrow should be pointing at the center dit and bout 5px below.

We can use css or the afterplace callback in popupmenu to adjust depending what works the best

**Comment by janahintal** [comment]
Issue still exist in https://master-enterprise.demo.design.infor.com/components/hierarchy/example-stacked-ajax-popupmenu.html
for windows 10 IE and Chrome browsers.

**Comment by tmcconechy** [comment]
Sorry the issue is not merged. Lets try when it is.

**Comment by janahintal** [comment]
Hi @tmcconechy, thank you this issue is now resolved in Windows 10 IE browsers as well as in MacOS Browsers but now failing in Windows 10 chrome browser. 

https://master-enterprise.demo.design.infor.com/components/hierarchy/example-stacked-ajax-popupmenu.html

Upon first click/open. 
![image](https://user-images.githubusercontent.com/45757016/80203700-27bb8200-865a-11ea-8cf5-945eb123637c.png)

Upon second click/open - Notice that the position changed, 
![image](https://user-images.githubusercontent.com/45757016/80203747-3e61d900-865a-11ea-9b27-62238a12ae9d.png)

**Comment by tmcconechy** [comment]
It does shift a bit the second time but i would call this minor. What do you think @krishollenbeck ?

**Comment by tmcconechy** [comment]
I think the last point is too minor. I cant seem to consistently reproduce it so lets skip this for now.
Moving to done.

**Comment by krishollenbeck** [comment]
@tmcconechy, I see this has been taken care of. Sorry for late response. I haven't been getting github notifications. Going to check my settings.

**Comment by tmcconechy** [comment]
i decided to punt on the fact it shifts a tiny bit. Didn't seem that important to me.
