### ISSUE TITLE
Datagrid: Overlapping icons and text

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3765]
**Describe the bug**
Datagrid: Overlapping icons and text

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html?theme=uplift&variant=light
2. Open the lookup field in Product Id column
3. Select '11111111111'
4. Hover again in lookup filter to see the icon and ellipsis overlapping

**Expected behavior**
Icons and Text should not overlap 

**Version**
IDS 4.28x Dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/79571244-75ca0600-80ed-11ea-83fa-2d67341db4ac.png)

**Platform**
All Browser and OS. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Going to descope this issue. There isnt really a fix. If you pick text bigger than the column, then the solution is to either change the text or resize the column to make it bigger.

Dont think there is any coding solution that can make this work. Also the text 11111111 was added to actually show these cases. So think this is not worth it. 

Thanks!
