### ISSUE TITLE
Application Menu: menu button down arrow is not centered in Uplift

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3766]
**Describe the bug**
down arrow is not centered in `Vibrant` theme

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-menubutton.html?theme=uplift&variant=light
2. See error
3. Notice that the down arrow is not centered in menu button

**Expected behavior**
should be centered in menu button

**Version**
v4.28.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/79571094-300d3d80-80ed-11ea-9eaf-82a667c1e627.png)

**Platform**
Safari

**Additional context**

**Comment by ericangeles** [comment]
@tmcconechy looks fixed already.

**Comment by ericangeles** [comment]
It seems that this still occurs on Safari. @jbrcna approached me about this and verified.

**Comment by jbrcna** [comment]
**QA Passed**
The issue is now resolved. Test across all browsers and devices and both themes. Thank you!
v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-menubutton.html?theme=uplift&variant=light&colors=0066D4
