### ISSUE TITLE
Multiselect: `showTags` and `showSelectAll` settings render selected elements incorrectly

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#3767]
**Describe the bug**
When a Multiselect Component is configured with the settings `showTags` and `showSelectAll` both true, and the "Select All" checkbox is used, the Multiselect incorrectly renders both the text and tag versions of the selected items within the list.

**To Reproduce**
- In the EP codebase, open the file `app/views/components/multiselect/test-select-all.html` and modify the part that invokes the Multiselect be:
```js
  $('#states-multi').multiselect({
    source: '{{basepath}}api/states?term=',
    showSelectAll: true,
    showTags: true,
    showEmptyGroupHeaders: false
  });
```
1. Run the demoapp and open http://localhost:4000/components/multiselect/test-select-all.html
2. Open the Multiselect
3. Click the "Select All" checkbox
4. See that all items are correctly selected, but the in-page element receives both the text and tagged versions of the results.

**Expected behavior**
When configured to show tags, the Multiselect's pseudo-element should only render tags.  When configured to show text only, it should only show text.

**Version**
Discovered in v4.28.x, reported in [MS Teams](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1587101184766?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1587101184766&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=General&createdTime=1587101184766)

**Screenshots**
![Screen Shot 2020-04-17 at 9 45 47 AM](https://user-images.githubusercontent.com/3249601/79576374-2bb33700-8091-11ea-98e6-3bc2e9c2ac50.png)

**Platform**
 - n/a

**Comment by byannalam** [comment]
Found another issue with the multiselect field yesterday. Mentioned it in Microsoft Teams, but was advised to add it as a note to this issue:

![3767-1](https://user-images.githubusercontent.com/4402939/79918433-ba4bfd80-846f-11ea-9bb3-1f611d6e3abc.png)
![3767-2](https://user-images.githubusercontent.com/4402939/79918443-be781b00-846f-11ea-97cc-ebe3df556279.png)

My steps to reproduce:

- Select all items via the "Select All" options
- Deselect all items
- Take note of how the box enclosing the multiselect appears to shrink to a super small height (screenshot 1).
- Close the dropdown part of the multiselect and note how the height reverts to its usual self (similar to screenshot 2).

**Comment by janahintal** [comment]
This issue is now resolved. 
![image](https://user-images.githubusercontent.com/45757016/85011881-c238cd00-b194-11ea-84b5-35302c732fd0.png)
