### ISSUE TITLE
Buttons: Moving to 100% on mobile after a recent fix

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3769]
**Describe the bug**
A rule added 24 days ago is not specific enough. Its forcing all buttons in a page container to go to 100%. This is causing buttons to flow off the page on mobile.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/button/example-index.html
2. in chrome tools debug this with the mobile tool as a pixel 2
3. See error

**Expected behavior**
This should not happen. This is caused by this rule https://github.com/infor-design/enterprise/pull/3641/files#diff-3d5f7c545f1d12e63ab9f6c95f5e04d5R771

This should be removed or made more specific for the original fixed bug so retest https://github.com/infor-design/enterprise/pull/3641

**Version**
- ids-enterprise: [e.g. v4.27]

**Screenshots**
<img width="538" alt="Screen Shot 2020-04-17 at 3 33 31 PM" src="https://user-images.githubusercontent.com/814283/79607229-e6a6f900-80c0-11ea-9479-5c260ad01096.png">

**Platform**
 - Mobile or chrome mobile

**Comment by tmcconechy** [comment]
This may need a patch but just fix on master ASAP and then i can port it back.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
