### ISSUE TITLE
General: Add default export so IDS-enterprise can be bundled

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#3771]
**Is your feature request related to a problem or use case? Please describe.**
Currently using IDS-enterprise require you to include the assets in `<script>` tags.
And it will be available globally afterwards. There's no way to include it via ES6 import/syntax. Therefore you cannot use bundler such as Webpack to include IDS-enterprise

**Describe the solution you'd like**
Add default export, visible exports so components/functionalities from IDS-enterprise can be imported instead. 

**Describe alternatives you've considered**
In my modified `sohoxi.js` I just added a default export, and it was enough for Webpack to recognize and bundle IDS-enterprise.

**Comment by guoliang** [comment]
In my custom fix I added the following line in the built `sohoxi.js`.

![image](https://user-images.githubusercontent.com/542598/79781191-63dea200-833d-11ea-8efe-985227cb103e.png)

**Comment by guoliang** [comment]
Btw, lodash which we also are using has a version of it which they have built the library as ES modules
https://www.npmjs.com/package/lodash-es

So perhaps we could have a version of IDS which is built as ES modules, thus you can keep it backward compatible with the users which include IDS in `<script>` tags?

**Comment by EdwardCoyle** [comment]
@guoliang agreed there, that's what I had been thinking when we first talked about this.  I think we need to continue shipping a standard bundle that can be included in a script tag, and the ES6-module based bundle would be separate.

Thanks for doing the digging on this!

**Comment by EdwardCoyle** [comment]
Noting that as part of this issue, I'm going to upgrade Rollup from `2.10.x` to `2.12.0`

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
