### ISSUE TITLE
Lookup: keywordFilter and filterable both set to true cause an error

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#3772]
**Describe the bug**
In lookup when `filterable `is set to `true` and `toolbar.keywordFilter` is also set to `true`, after selecting an item, we get an error in the console and it is not possible to open modal dialogs  anymore.

**To Reproduce**
1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/example-filter-row.html](https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/example-filter-row.html)
2. Change toolbar setting of  `keywordFilter` to `true`
3. Click on the lookup button.
4. Select an item- click  Apply button 
5. See the error in console.log.
6. Try to click again on the lookup button, nothing happens.

You can see my JSFiddle example [https://jsfiddle.net/sebulbajoe/pn9j5r0b/9/show](https://jsfiddle.net/sebulbajoe/pn9j5r0b/9/show)

**Expected behavior**
To have lookup with both keyword filter and row filter and to be able to continue use modals.

**Version**

- ids-enterprise: v4.27.3

**Screenshots**

**Platform**

 - Browser Name: Chrome
 - Browser Version:75.0.3770.100 (Official Build) (64-bit)

**Additional context**
On version 4.19.3 we didn't experience this bug.

Thanks,
Jonathan

**Comment by tmcconechy** [comment]
Not sure we have a test for both filter and keyword search. Seems like they do the same thing.
But if they worked before they probably should still work. Trying to add this to this sprint but we are wrapping up so maybe have to move it to the next sprint.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/lookup/example-filter-lookup.html?theme=uplift&variant=light across all platforms.
