### ISSUE TITLE
Calendar: ‘allowOnePane’ parameter is not working properly

### ISSUE THREAD

**Issue by rowelineeveresurreccion** [infor-design/enterprise#3773]
**Describe the bug**
The ‘allowOnePane’ parameter is not working properly. Please details below:

**To Reproduce**
1.	Go to https://latest-enterprise.demo.design.infor.com/components/calendar/example-index.html
2.	Move the cursor to the Right-side panel region.
 
![image](https://user-images.githubusercontent.com/50350478/79710771-88fcf180-82f8-11ea-9711-30fb60a38f51.png)

3.	Right Click > Inspect. Then, change the ‘allowOnePane’ to ‘true’.
 
![image](https://user-images.githubusercontent.com/50350478/79710785-9a45fe00-82f8-11ea-99d2-55d571a83e4d.png)

4.	Set it to ‘true’.
 
![image](https://user-images.githubusercontent.com/50350478/79710820-b6499f80-82f8-11ea-8100-185c7a411a22.png)

5.	Go back to the page and click on ‘+’ and Add Event (api). Do this twice or more.
6.	Click on the 2nd and/or 3rd event items. The contents of the 2nd event items and beyond do not expand.
 
![image](https://user-images.githubusercontent.com/50350478/79710900-f3ae2d00-82f8-11ea-9ce1-31807bff30cc.png)

**Expected behavior**
-	The event items should be able to display and expand the event details one pane at a time without any issues. (This is based on the description of what ‘allowOnePane’ should do).

**Version**

- ids-enterprise: 4.28.0-dev 
but can also replicate in our Application with ids version: 4.27.1

**Platform**
 - Infor Application/Team Name: Pathway
- Browser Name: Chrome
 - Browser Version: Version 81.0.4044.113 (Official Build) (64-bit)

**Additional context**

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/calendar/test-allow-single-pane.html?theme=uplift&variant=light&colors=0066D4
