### ISSUE TITLE
Lookup: Checkbox column is not center-aligned with the header

### ISSUE THREAD

**Issue by sharmainerivera** [infor-design/enterprise#3774]
**Describe the bug**
Checkbox column for lookup is not aligned at the center making it look misaligned to the header.

**To Reproduce**
1. http://localhost:4000/components/lookup/example-clientside-paging-with-filtering.html
2. Remove other columns except for the Product Name.
3. Add this column:
columns.push({ id: 'active', name: 'Active', field: 'active', sortable: false, filterType: 'checkbox', align: 'center', formatter: Formatters.Checkbox });

![image](https://user-images.githubusercontent.com/61222084/79732323-1acf2380-8326-11ea-89df-1423cdb9709c.png)

**Expected behavior**
The checkboxes below the header should be centered as well to match the alignment to the header

**Version**
- ids-enterprise: 4.27.1

**Platform**
 - Infor Application/Team Name: Infor Pathway
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by ericangeles** [comment]
@tmcconechy looking at this and it seems the alignment issue is resolve. However, checking it on a smaller viewport, the datagrid gets cut off. Looks like it should overflow on a mobile view.

<img width="465" alt="Datagrid cutt off on mobile view" src="https://user-images.githubusercontent.com/8839327/95150573-0808b800-07bb-11eb-9a26-3dcdac2cbe3e.png">

**Comment by tmcconechy** [comment]
@ericangeles in that case you can still swipe / scroll. There isn't a lot we can do about that problem other then reconstruct the grid dimensions (column widths) so thats a user setting.

If we cant reproduce the checkbox alignment anymore then lets close and move to QA to test.

**Comment by tmcconechy** [comment]
@ericangeles can you just PR the change so we can QA the checkbox column (i.e. add the checkbox column so we can verify the issue is fixed)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/95975004-3ab05180-0e48-11eb-8886-2fc0d2eee417.png)
