### ISSUE TITLE
Datagrid: Dropdown filter gets misaligned after showing the remove panel

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3775]
**Describe the bug**
Datagrid: Dropdown filter gets misaligned after showing the remove panel

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-disabled-rows.html?theme=uplift&variant=light
2. In Row ID 1 -  Action Column, hover and click the dropdown filter
3. Notice that after the remove panel show up, the dropdown filter become misaligned 

**Expected behavior**
The dropdown filter should be aligned. 

**Version**
IDS 4.28x - Dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/79753257-32b79f00-8348-11ea-8069-5aad752451e8.png)

**Platform**
All Browse, OS, and Devices. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Interesting bug. I think maybe make the selection checkbox the only way to select vs when you edit the row. (Demo app setting)

**Comment by tmcconechy** [comment]
Descoping this one for now
