### ISSUE TITLE
Badges: Clock icon not perfectly centered in High Contrast

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3776]
**Describe the bug**
The clock icon is not centered when using `High Contrast`

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/badges/example-index.html?theme=soho&variant=contrast 
or
https://master-enterprise.demo.design.infor.com/components/badges/example-index.html?theme=uplift&variant=contrast
3. See error, ensure that the variant is `High Contrast``
4. Notice that the clock icon is not centered

**Expected behavior**
Icon should be centered

**Version**
v4.28.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/79752807-71008e80-8347-11ea-8c3b-abd9d08986f3.png)

**Platform**
All

**Additional context**
Both `Subtle` and `Uplift` is affected

**Comment by tmcconechy** [comment]
Descoping this for now
