### ISSUE TITLE
Multiselect: Error when settings.showSelectAll is true and there are no other selection values

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#3777]
**Describe the bug**
JS error in multi select dropdown when settings.showSelectAll is true and there are no other selection values

**To Reproduce**
1. Go to https://usspvwlmclient1.infor.com/uitest/PatternTest/list/Product.StateFieldsListOnSearchForm
contact me for un/pw
2. Click on "Alpha Price" dropdown
3. Notice only "Select All" is displayed. Click That

**Expected behavior**
We lazily load these values from database table and hence the list can come back empty. I think just removing this when no other values are available to select from is reasonable.

**Version**
4.27

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/4737815/79768346-4800df00-82f0-11ea-94b3-3119508a9134.png)

undefined value in sohoxi.js
![image](https://user-images.githubusercontent.com/4737815/79768403-5bac4580-82f0-11ea-9347-4a00248a5cfc.png)

**Platform**
 - Landmark
 - Window 10
 - Chrome
 - Latest

**Additional context**

**Comment by EdwardCoyle** [comment]
Wondering if this is the same as #3767, although I don't remember seeing a JS error there when testing

**Comment by tmcconechy** [comment]
Seems a bit different but probably can be fixed together.

**Comment by jbrcna** [comment]
**QA Passed**
v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/multiselect/test-select-all-no-opts.html
