### ISSUE TITLE
Datagrid: Filter conditions Leaves Two selected if you just reorder.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3779]
**Describe the bug**
If you rearrange the items in filterConditions and leave the default IN you get two selected in the list visually.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-custom-filter-conditions.html
2. Edit that page so one column has `filterConditions: ['equals', 'does-not-equal', 'contains', 'does-not-contain', 'is-empty', 'is-not-empty', 'end-with', 'does-not-end-with', 'start-with', 'does-not-start-with']`
3. open filter list (not that it is showing equals correctly but)
4. See error - two are selected

**Expected behavior**
Only equals is selected

**Version**
- ids-enterprise: [e.g. v4.27.0]

**Screenshots**
![Screen Shot 2020-04-20 at 2 19 07 PM](https://user-images.githubusercontent.com/814283/79792040-4220f300-831c-11ea-963f-3fe23c5dfdcc.png)

**Platform**
 - Any

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html across all platforms.
