### ISSUE TITLE
SOHO-8122: Datagrid CSV export - issue with column separator & different locales

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#378]
When exporting a datagrid to CSV format the file always uses a comma (",") for the field separator. In many locales the comma is the accepted default for the column separator character for .CSV files. For example, Excel will ,by default, directly open the file without issue on an en-US locale machine. But if a user 's machine is configured for a Swedish locale, for example, the default separator character is a semicolon (";"); a default open of the same file in Excel treats each row as a single field thus the data is corrupted. There are workarounds for this but a solution that works 'by default' for every user regardless of locale is preferred.

Here are a 3 proposed solutions:

1. Excel will accept a separator identification as the first line of an imported CSV file,  "sep=,". Solution would be to add that as a first line to every CSV export file. The downside of this is that a non-Excel app may have an issue with this but we're ok with it. There exists functionality in our application where we do CSV exports with our own code and this is what we do.
2. Allow for an optional parameter to be sent to the exportToCsv method that tells the datagrid code what character to use as the separator.
3. A combination of 1 & 2 - an optional parameter for the exportToCsv method that instructs the datagrid code to add the "sep=," as the first line in the exported file. This probably makes the most sense and won't break existing implementations.

The "sep=," appears in older versions of datagrid.js code, was specific for IE9.  

Open to other ideas of course.

Our application is used extensively to query data, sometimes lots of it, and the export function is used quite a bit so having this functionality work by default is important.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/example-export-from-button.html
http://4120-beta0-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html
Passed QA testing.
