### ISSUE TITLE
General: Error building datagrid

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3784]
**Describe the bug**
Including datagrid in a custom build is giving an error.

**To Reproduce**
1. Pull master
2. run `npm run build -- --components=button,busyindicator,datagrid`
3. or `npm run build -- --components=datagrid`
4. See 2 errors `Error: no mixin named required-indicator
    at Object.module.exports.renderSync (/Users/tmcconechy/Dev/master4/node_modules/node-sass/lib/index.js:441:16)` and `Error: 'DatagridEditors' is not exported by src/components/datagrid/datagrid.editors.js, imported by temp/components.js`

**Expected behavior**
Should build with datagrid. We can rename exports if needed.

**Version**

- ids-enterprise: [e.g. v4.2.7]

**Platform**
 - Mac and windows

**Additional context**
Infor S3

**Comment by EdwardCoyle** [comment]
Noting that I wanted to build a test suite for verifying custom builds as part of this issue, but for now I've kicked that off to #3796

**Comment by janahintal** [comment]
QA Passed. Tested and working well on all platforms.
Verified in https://4280-beta1-enterprise.demo.design.infor.com/components/datagrid/example-index.html?theme=uplift&variant=light&layout=nofrills
