### ISSUE TITLE
Popupmenu: "attachToBody" cause memory leak when used in a Modal / CAP

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#3785]
**Describe the bug**
The default value for `attachToBody` for popupmenu was changed from false to true. With this, we've seen some memory leaks when popupmenus are used in Modals / CAPs. If destroying the modal when closed, some popupmenus remain in DOM and increase +1 each time the modal is re-opened.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/contextualactionpanel/test-destroy.html
2. Repeat "Show me potato salad" -> "Destroy CAP" -> "Invoke CAP" a few times

**Expected behavior**
When CAP is destroyed, all popupmenus within should be destroyed & removed from DOM

**Actual behavior**
No. of popupmenus increase +1 on body each time CAP is re-invoked and opened. In this example, it seems it's the toolbar more menu that doesn't get destroyed.

**Version**
- ids-enterprise: v4.27.3

**Additional context**
In older versions, when`attachToBody` was false by default, any menus within a CAP / modal got destroyed since the whole modal is removed from DOM.
4.24.0
https://design.infor.com/code/ids-enterprise/latest/demo/components/contextualactionpanel/test-destroy.html

Perhaps there are other scenarios where a popupmenu fails to destroy, but for now this is the one we've seen.

**Comment by tmcconechy** [comment]
I fixed this while fixing https://github.com/infor-design/enterprise-ng/issues/801

**Comment by jbrcna** [comment]
**QA Passed**
moving this ticket to Done. thank you
v4.28.0-dev
