### ISSUE TITLE
Icons: Fix demo app pages

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3790]
**Describe the bug**
We noticed two problems when linking out from design.infor.com.

**To Reproduce**

- [x] Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/icons/example-index and click on theme switcher and change to uplift. Notice the icon contents dont change
- [x] Also the pages https://design.infor.com/code/ids-enterprise/latest/demo/components/icons have some duplication and should be removed (some are needed some not)
- [x] Change tyopgraphy page to new hierarchy

**Expected behavior**
Switching icons should work. And example pages should be cleaned up.

**Version**
- ids-enterprise: [e.g. v4.27.0]

**Platform**
 - mac/chrome

**Additional context**
See also related issue https://github.com/infor-design/website/issues/868

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
