### ISSUE TITLE
Datagrid / Treegrid: Siblings Selection mode, clicking on already selected rows toggles selection

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#3791]
**Describe the bug**
Siblings selection mode is used in cubes in landmark to select all records in the same level. Row click on already selected rows toggles the selection. 

**To Reproduce**
1. Go to enterprise-ng-demo > Datagrid > Datagrid-TreeGridCube demo.
2. The 4 root level nodes are already selected and the corresponding chart is displayed to the right.
3. Now click on the first selected row. 
4. It unselects all the rows.

**Expected behavior**
The selection is not toggled and the four rows remain selected.

**Version**

- ids-enterprise: v4.27.3

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 81.0

**Comment by tmcconechy** [comment]
Im a bit fuzzy on these steps. Can you reproduce it here https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-select-siblings.html ?

Is it that you dont want to be able to unselect at all?

**Comment by tmcconechy** [comment]
Just marking for clarification...

**Comment by aaralikar** [comment]
@tmcconechy I am able to reproduce the behavior using test-tree-select-sibligs.html in enterprise demo too. 
The check box does not make sense in cubes. The interaction is used to refresh the chart on the right. When the selection is lost, the chart does not carry any meaning. Clicking anywhere on already selected set of nodes should not toggle selection.

**Comment by aaralikar** [comment]
![SiblingSelectionTest](https://user-images.githubusercontent.com/22720894/80114442-349c8080-8549-11ea-8178-419f8247eb55.gif)

**Comment by tmcconechy** [comment]
Ok, so you basically dont want to be able to unselect a set of selected nodes. So only select another one?

**Comment by jbrcna** [comment]
**QA Passed**
this is now working as expected
v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-select-siblings.html
