### ISSUE TITLE
Create Test Suite for Custom Builds

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#3796]
**Is your feature request related to a problem or use case? Please describe.**
It should be possible for us to prove that our Custom Builds work properly by way of providing a test suite for them.

**Describe the solution you'd like**
While needing some more research, a tentative plan could be to verify the contents of the `sohoxi.js` and `sohoxi.css` files by way of a functional test suite.  We'd need to build a harness that:
- Runs the custom builder in various pre-determined configs (fx: `--components=datagrid` to test that JUST building datagrid can allow it to stand by itself)
- Run a functional test suite (Jasmine/Mocha)
- Open each compiled library and check for the correct imports/exports
- Open the files that get added to `dist/log` by the custom builder and check that the files that have been globbed/targeted are correct.

**Describe alternatives you've considered**
I'm open to other ideas, not sure what else we could do to verify builds.

**Comment by tmcconechy** [comment]
Descoping this for now as we are building out a different system
