### ISSUE TITLE
Datepicker cannot be used with Arabic locale

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3804]
**Describe the bug**

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=ar-SA
2. Click on the first datepicker
3.  Click Apply
4. See error, shows NAN and console error parseDate.getHours is not a function.

**Expected behavior**
The datepicker should display a date in RTL after choosing a date. It should also be possible to reopen the datepicker after that date is displayed to select a new date and time.

**Version**

- ids-enterprise: 4.27.4

**Screenshots**

![image](https://user-images.githubusercontent.com/8664975/80346538-32009a80-886b-11ea-8502-1067a9f8d1a9.png)
![image](https://user-images.githubusercontent.com/8664975/80346562-39c03f00-886b-11ea-801e-75b11b41da4d.png)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 81.0.4044.122 (Official Build) (64-bit)

**Additional context**
-

**Comment by tmcconechy** [comment]
Thought this could have been fixed by https://github.com/infor-design/enterprise/pull/3798 recently but still seeing it:

https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=ar-SA

Will check if that site is up to date or there is some bug still.

**Comment by jbrcna** [comment]
**QA Passed**
moving this ticket to Done. Thank you
v4.28.0-beta1

verified in
https://4280-beta1-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?theme=uplift&variant=light&locale=ar-SA
and
https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?theme=uplift&variant=light&locale=ar-SA
