### ISSUE TITLE
ApplicationMenu: Button not working in NG

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3805]
**Describe the bug**
Due to changes on extend the app menu button is not working in NG. The problem is empty arrays are not getting extended properly in the settings.

**To Reproduce**
1. Go to the ng project on master
2. Click on the hamburger menu
3. See error (its not working)

**Expected behavior**
This works and extend works.

**Version**
- ids-enterprise: [e.g. v4.27]

**Platform**
 - Chrome

**Additional context**
Originated in Ms Teams

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
