### ISSUE TITLE
Textarea: "Characters Remaining" text is not localized for af-ZA language

### ISSUE THREAD

**Issue by hgodse** [infor-design/enterprise#3807]
**Describe the bug**
  soho-textarea "Characters Remaining" text is not localized for af-ZA language

**To Reproduce**
1. Go to 'https://master-enterprise.demo.design.infor.com/components/textarea/example-index.html?locale=af-ZA'
2. type something in textarea
3. notice that "Characters Remaining"  text is not in language af-ZA

**Expected behavior**
 "Characters Remaining"  text is should be in language af-ZA

**Version**

v4.20.0 to 4.27

**Screenshots**
<img width="960" alt="screenshot" src="https://user-images.githubusercontent.com/64417907/80379570-e5917b00-88bb-11ea-83a4-f991887ef56d.png">

**Platform**
 -OS Version: Windows 10
-Browser Name: Chrome
-Browser Version: 80.0.3987.163 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Translated text is there. This might work in 4.29 but will test and add unit tests now for 4.30 and confirm

**Comment by tmcconechy** [comment]
@hgodse FYI this is working in 4.29 but i added the tests in 4.30 so either should work for you. https://github.com/infor-design/enterprise/pull/3966

**Comment by janahintal** [comment]
This issue is now resolved. Thank you! 
Verified in https://master-enterprise.demo.design.infor.com/components/textarea/example-index.html?theme=uplift&variant=light&colors=0066D4&locale=af-ZA
![image](https://user-images.githubusercontent.com/45757016/84121635-011aa480-aa6a-11ea-8602-23960d981b7b.png)
