### ISSUE TITLE
ContextActionPanel: Manual trigger won't open

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3809]
**Describe the bug**
CAP won't open in example-trigger EP.

**To Reproduce**
1. Go to 'https://master-enterprise.demo.design.infor.com/components/contextualactionpanel/example-trigger.html
2. Click on the button to open `CAP`
3. See error
4. Notice that the `CAP` won't be displayed

**Expected behavior**
CAP should be displayed upon clicking the button

**Version**
v4.28.0-dev

**Screenshots**

**Platform**
All

**Additional context**

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
