### ISSUE TITLE
SOHO-8105: Enhance 'Personalize Columns' - taller and drag/drop to change order

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#381]
A datagrid with lots of columns is a key part of IIH, central to a customer's workflow and to how we demonstrate the product's value.

As part of that, we often change the column order. That's, er, less than ideal, for our typical case: drag an off-screen column (scrolled off to the right) so it's on-screen for everyday use.

It would be much more efficient if we could drag fields up/down from within the Personalize Columns dialog -- especially if that were made as tall as the window that it comes from.

(And, probably for a separate ticket: saving/loading multiple named sets would be useful too!)

**Comment by tmcconechy** [comment]
De scoping this issue for now.
