### ISSUE TITLE
SearchField: No clear() function to clear the search field

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise#3810]
There is no clear() function to clear the search field. Setting input value to empty string leaves a width and a placeholder.

**Describe the bug**
There is no clear() function to clear the search field. Setting input value to empty string leaves a width and a placeholder.

**Expected behaviour**
Search Field should have explicit clear() function

**Additional context**
Infor PIM @karinthulin

**Comment by tmcconechy** [comment]
This seems to be a gap. We need to check all the settings and make a clear function. For at least one case it should

```
$('#regular-toolbar-searchfield').val('').attr('placeholder','').parent().removeClass('has-text')
```
- remove the placeholder nad parent class and value to collapse it
- function should be callable with any option and in NG (which gives an error now)

**Comment by jbrcna** [comment]
**QA Passed**
`x` button is shown after user input and clears the field when used.
v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/searchfield/example-clear-api.html
