### ISSUE TITLE
Modal: Validation for Email field is not working in Mobile devices on both Android and iOS

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3816]
**Describe the bug**
Modal: Validation for Email field is not working in Mobile devices on both Android and iOS

**To Reproduce**
1. Open Mobile browser e.g Android Chrome / iOS Safari then Go to https://master-enterprise.demo.design.infor.com/components/modal/example-validation.html?theme=uplift&variant=light
2. Click 'Add Context'
3. Click All 3 fields but do not select or type any to show the validation
4, Click 'Cancel' 
5. Open the Modal again. 

Notice that the Email field did not show validation.

**Expected behavior**

**Version**
IDS 4.28x - Master 

**Screenshots**
Android 
![image](https://user-images.githubusercontent.com/45757016/80475924-3f597a00-897c-11ea-8683-1b70465e0ed9.png)

iOS
![image](https://user-images.githubusercontent.com/45757016/80475954-4da79600-897c-11ea-975b-cd05f0430743.png)

**Platform**
Android & iOS latest OS.

**Additional context**
N/a

**Comment by tmcconechy** [comment]
I can confirm the issue. It is a bit wierd, not sure why the blur does not fire in this situation. Marking as minor

**Comment by tmcconechy** [comment]
Descoping for now
