### ISSUE TITLE
Datepicker: Range-Disable Selected value indicator issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3818]
**Describe the bug**
when you select dates from the last week of the last month to the first week of the first month (i.e. Dec 31 to Jan 4) then press back or the `<` icon the selected value and indicator have issues
please see attached screenshot and gif file

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datepicker/example-range.html
2. MoveTo `Range - Disable included` 
3. Select dates from 12/31/2017 to 12/4/2017
4. Press forward `>` icon
5. See that the date highlight is not matching the selected date

**Expected behavior**
Highlight should only indicate the exact selected value 

**Version**
ids-enterprise: v4.28.0-dev

**Screenshots**
Notice that the date is not correct when using `forward`  button
<img width="361" alt="Screen Shot 2020-04-28 at 8 53 09 AM" src="https://user-images.githubusercontent.com/814283/80489358-b3206600-892d-11ea-8eca-be6febe93a07.png">

**Platform**
All Browsers

**Comment by tmcconechy** [comment]
Simplified these steps above. Marking this as minor.

**Comment by tmcconechy** [comment]
Descoping this for now
