### ISSUE TITLE
General: Error building modal

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#3822]
**Describe the bug**
Including modal in a custom build is giving an error.

**To Reproduce**

1. Pull master
2. run `npm run build -- --components=modal`
3. See error: `[!] Error: 'ModalManager' is not exported by src\components\modal\modal.manager.js, imported by temp\components.js`

**Expected behavior**
Should be able to generate a build that includes a modal

**Version**

- ids-enterprise: master

**Platform**
 - Windows

**Additional context**
Lawson product

**Comment by awbuboltz** [comment]
Hey @EdwardCoyle, datagrid is working now, but I didn't get too much further before hitting the modal issue.

**Comment by EdwardCoyle** [comment]
Thanks @awbuboltz, a recent addition to the core was incorrectly being picked up by the custom builder here.

**Comment by jbrcna** [comment]
**QA Passed**
moving this ticket to Done. Thank you
v4.28.0-beta1

verified in
https://4280-beta1-enterprise.demo.design.infor.com/components/modal/example-index.html?layout=nofrills
