### ISSUE TITLE
Modal/Checkbox: Extra spacing & scroll-bar when checkbox is in modal

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#3824]
**Describe the bug**
A modal with only a checkbox (and possibly other components, like listview?) will overflow, which will cause a scrollbar to appear for no reason.

**To Reproduce**
1. Go to https://anhallbe.github.io/ids-repro/checkbox-modal
2. Click on 'Open Modal'
3. Notice the scrollbar right next to the checkbox

**Expected behavior**
There should be no overflow or scrollbars in the modal.

**Version**
- ids-enterprise-ng: 7.0.2

**Screenshots**
![modal-shenanigans](https://user-images.githubusercontent.com/4991954/80521128-c4e42680-898a-11ea-98e7-e3efe3e28d95.gif)

**Platform**
 - OS Version: Windows & MacOS
 - Browser Name: chrome, safari

**Additional context**
Original issue, with other possibly related scenarios: https://jira.infor.com/browse/LIME-6065

Repro source code: https://github.com/anhallbe/ids-repro/blob/master/src/app/checkbox-modal/checkbox-modal.component.ts

**Comment by tmcconechy** [comment]
Fix seems to be...
```
.switch input:empty {
  /* margin-left: -9999px; */
}
.switch input {
  position: absolute;
  top: 0;
  height: 20px;
  left: 0;
}
```

**Comment by jbrcna** [comment]
**QA Passed**
moving this ticket to Done.
v4.28.0-beta1
