### ISSUE TITLE
Splitter: Collapse Button Example Is Broken

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3825]
**Describe the bug**
The collapse button example broke in 4.27 should fix before spotted as its used.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/splitter/test-collapse-button.html
2. See compared to https://4262-enterprise.demo.design.infor.com/components/splitter/test-collapse-button.html

**Expected behavior**
Want it back like 4.62 with the button in the right place. Also add a regresion test (visual)?

**Version**
- ids-enterprise: [e.g. v4.27 and 4.28]

**Platform**
 - Chrome

**Comment by jbrcna** [comment]
**QA Passed**
moving this ticket to Done. Thank you
v4.28.0-beta1

verified in
https://4280-beta1-enterprise.demo.design.infor.com/components/splitter/test-collapse-button.html
and
https://master-enterprise.demo.design.infor.com/components/splitter/test-collapse-button.html

![image](https://user-images.githubusercontent.com/56722184/80596657-4b673980-8a59-11ea-93bb-e5cd41899b68.png)
