### ISSUE TITLE
Accordion: Unable to dynamically add accordion items

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#3826]
**Describe the bug**
Adding a new accordion header/panel then calling .updated($headers) no longer works. This has worked since 4.x came out, but I think it broke with commit 312ec60995e2fe1e2ecc42b15e3a12e1ac8e50ba in February.

**To Reproduce**
1. Add this file to the app/views/components/accordion directory: https://gist.github.com/awbuboltz/fc642f679f10c27df861fd2086d4bc99
2. Click the "Add new favorite" button
3. See the console error

**Expected behavior**
The newly added favorite menu item should be properly initialized as a menu item, including key handling and CSS.

**Version**

- ids-enterprise: 4.28

**Platform**
 - Infor Application/Team Name: Lawson
 - OS Version:. Windows 10
 - Browser Name: Chrome

**Additional context**
When passing new headers to .updated(), eventually teardown() gets called. Teardown now does a delete on this.headers, this.anchors, this.panes, and this.contentAreas. Right after teardown(), init() is called, which tries to access those variables.. which were just deleted.

**Comment by tmcconechy** [comment]
Do to the timing of this issue we can try to fix it next sprint - this one is in the books.

**Comment by marknolaninfor** [comment]
@EdwardCoyle 

I had the same issue today and found that update can except headers, corrently as the teardown is incorrect.

Only if globalEventTeardown is true it sould delete the delete list of controls, as this update is to append headers.

![image](https://user-images.githubusercontent.com/39749678/80566973-4b544300-8a33-11ea-8e36-d9c6a7de3f01.png)

**Comment by EdwardCoyle** [comment]
@awbuboltz @marknolaninfor thanks for the test case and suggestions!  I'm looking into this now to see if we can get it in for 4.28, considering the regression.  Seems pretty straightforward.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://4280-rc0-enterprise.demo.design.infor.com/components/accordion/test-add-dynamically.html?layout=nofrills

**Comment by janahintal** [comment]
QA Passed in https://master-enterprise.demo.design.infor.com/components/accordion/test-add-dynamically.html?layout=nofrills. Will retest when 4290 beta is released. Thank you.
