### ISSUE TITLE
Datagrid: Tree multiselect selects tree item on folder click and is-partial with ajax

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#383]
There are two issues here.

!. When using a multiselect tree clicking on the folder icon to expand/collapse the folder is toggling the selected status of the folder item's checkbox. This can be observed on the multiple select example: 

https://design.infor.com/code/ids-enterprise/latest/demo/tree/example-select-multiple?font=source-sans

Expected, the checked state of the items to not change when opening / closing folder nodes.

2. When using ajax dynamic loading there is no way to specify a partialy selected folder. In addition, when calling tree() on the element to initialize the component any is-partial classes are removed from the folders. These classes were added by the server side render.

Here is the use case. We have a form that allows the users to edit application permissions. Our permissions are in a hierarchy. We currently have about 2200 permissions, so I would like to dynamically load the child nodes. In this case I need to be able to set the is-selected class/property of the children when they are loaded from ajax. 

Beyond level 1 the tree should be able to correctly calculate the is-partial, as long as I can load children with is-partial... the tree should display the parent as partial if any children loaded are flagged as is-partial.

See also: SOHO-8085

**Comment by tmcconechy** [comment]
Descoping this issue for now as it hasn't gotten any traction in several years.
