### ISSUE TITLE
Datepicker: Value has incorrect datetime format with es-419 locale

### ISSUE THREAD

**Issue by albinbergvall** [infor-design/enterprise#3830]
**Describe the bug**
When using es-419 locale, datepicker doesn't use the datetime formatting of that locale. Instead it uses the datetime formatting of es-ES. This causes issues with parsing the value from the datepicker as it doesn't have the correct format needed for Locale.parseDate().

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat.html?locale=es-419
2. Select a value in one of the locale datepickers.
3. Open the browser console.
4. Type 'Locale.calendar().dateFormat.datetime'
4.1. Compare console output to datepicker datetime formatting
5. Type 'Locale.parseDate("<_DatePicker value_>", {date: "datetime"})'
5.1. Returns undefined

**Expected behavior**
4.1. 'Locale.calendar().dateFormat.datetime' and datepicker should have same datetime formatting
5.1 'Locale.parseDate("<_DatePicker value_>", {date: "datetime"})' should return a date object, not undefined

**Version**

- ids-enterprise: v4.27.4

**Screenshots**
![image](https://user-images.githubusercontent.com/30404138/80592713-2d311780-8a20-11ea-8dd9-6f072ebf2a22.png)

**Platform**
 - Infor Application/Team Name: Infor Ming.le Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 81.0.4044.122 (Official Build) (64-bit)

**Additional context**
We previously had another issue with es-419 which has since been fixed. Not sure if that has anything to do with this issue. https://github.com/infor-design/enterprise/issues/3363

**Comment by tmcconechy** [comment]
Yes this is simple, the locale is just using the medium format by error. As a workaround you can do it with a pattern..

```
Locale.parseDate("29/4/2020 08:40", {pattern: Locale.calendar().dateFormat.datetime})
```

**Comment by jbrcna** [comment]
QA Passed
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=es-419
![image](https://user-images.githubusercontent.com/56722184/81695735-96d80980-9495-11ea-9bb8-4ac52ad19c95.png)
