### ISSUE TITLE
Accordion: hidden headers are not excluded from keyboard navigation

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#3835]
**Describe the bug**
The internal hash Accordion uses for determining which headers/expanders can be focused by the keyboard is not currently working right, and it's allowing sub-headers hidden by a collapsed parent header to become focused.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/accordion/example-accordion-panels
2. Click inside the page body just above the gray Accordion Panel.
3. Begin slowly pressing the tab key.  After focus leaves the expander button on the first header labeled "Personal", notice that it "disappears" for several key presses until it re-appears on the second header labeled "Position".
4. Keep pressing the tab key until focus leaves the expander button on the third header labeled "Notes". Now press the "Enter" key.  Notice that the sub-header under Notes labeled "Education" becomes expanded.

**Expected behavior**
It should not be possible to interact with accordion headers, expanders, or any components within the content panels if they are currently beneath a collapsed accordion header.

**Version**
Discovered in 4.27.x, likely has been there awhile.

**Screenshots**
![IDS-Enterprise-_1_](https://user-images.githubusercontent.com/3249601/80624898-5a7ac700-8a1a-11ea-858b-b555ac080bf2.gif)

**Platform**
 - n/a

**Additional context**
Discovered while testing #3834

**Comment by tmcconechy** [comment]
I noticed this while looking at https://github.com/infor-design/enterprise/issues/2327#issuecomment-613667429 and made a note. I think whoever fixes these can address both (2327 has changed to really become this issue)

**Comment by EdwardCoyle** [comment]
I didn't see that issue before, this one's basically a duplicate of it I think.  Important to note that it's present in all accordions though, not just App Menu.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.
Verified in https://master-enterprise.demo.design.infor.com/components/accordion/example-accordion-panels.html?theme=soho&variant=light&colors=2578a9 & 
https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=uplift&variant=light&colors=0066D4
