### ISSUE TITLE
ContextMenu: Field Options Zoom issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3844]
**Describe the bug**
When using zoom 80%  the `:` icon is misaligned

**To Reproduce**
1. Go to https://4280-beta1-enterprise.demo.design.infor.com/components/contextmenu/example-field-options.html
2. Zoon out twice or until you reach 80%
3. See error

**Expected behavior**
the `:` icon should be in proper alignment regardless of the zoom preference

**Version**
- ids-enterprise: v4.28.0-beta1

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/80708628-94cd8c80-8b1e-11ea-9656-464f96942b1b.png)

**Platform**
Safari

**Additional context**
similar to https://github.com/infor-design/enterprise/issues/3523?

**Comment by tmcconechy** [comment]
Wondering if there is any solution to this. But field options is going to be deprecated so will shelf this for now.

**Comment by tmcconechy** [comment]
Descoping this for now
