### ISSUE TITLE
Multiselect: Select All checkbox should only select visible (filtered) items

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#3845]
**Is your feature request related to a problem or use case? Please describe.**
selectAll option in dropdown component should select only what is currently in the list when filter is applied

**Describe the solution you'd like**
An option for selectAll to select everything or filtered list.

**Describe alternatives you've considered**
adding new parameter 'selectFiltered'

**Additional context**
![CZONaYdpUt](https://user-images.githubusercontent.com/11279863/80709819-43a5a480-8aee-11ea-967e-f75fec7e14e8.gif)

**Comment by EdwardCoyle** [comment]
@tmcconechy is this a different feature you think?  Should we make this configurable and leave the current behavior as the other option?

**Comment by tmcconechy** [comment]
I feel like this should be the correct behavior but open to debate. So thinking make an option selectAllFilterOnly or whatever and set it to true by default

**Comment by thomas-blackwell** [comment]
Any progress on this issue?

**Comment by EdwardCoyle** [comment]
@thomas-blackwell we have this issue scheduled for our June sprint, starting June 1

**Comment by jbrcna** [comment]
**QA Passed**
v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/multiselect/test-select-all-tags.html

**Comment by jbrcna** [comment]
just some observation in `Uplift Theme`
![image](https://user-images.githubusercontent.com/56722184/85014458-e3032180-b198-11ea-959b-89d04e469ac7.png)

**Comment by EdwardCoyle** [comment]
@jbrcna I'm addressing that one in #4056, should be fixed after we merge that

**Comment by AsafMeirBarziv** [comment]
Can this fix be applied on datagrid too?

**Comment by tmcconechy** [comment]
OK, that would be a separate issue... But i don't get it so maybe need some steps, closest I can think of is:

https://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
- apply a filter
- select all
- revert the filter
- only what was filtered is selected

This issue relates to lookup and no further work will be done on it here.

**Comment by tmcconechy** [comment]
Yes, if you have an issue - this is closed nothing further is being done here.
