### ISSUE TITLE
ApplicationMenu: Personalized-Role-Switcher no ellipsis

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3846]
**Describe the bug**
No ellipsis in large text

**To Reproduce**
1. Go to https://4280-beta1-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html
2. Switch Role, Select` Example Role Thats Really Really Long So Long that it flows into an ellipsis just really long, maybe too long?`
3. Close the role switcher
3. See error
4. Notice that there is not enough room for the long text.

**Version**
ids-enterprise: v4.28.0-beta1

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/80712657-d95c2680-8b24-11ea-9d8a-66597cab16f8.png)

**Platform**
All browsers

**Additional context**

**Comment by tmcconechy** [comment]
This is the correct behavior now. I think that the text is just misleading made a quick update to it.

**Comment by tmcconechy** [comment]
Descoping this issue for now
