### ISSUE TITLE
ListFilter: Fix Case-Sensitive filtering

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#385]
Original JIRA Issue: https://jira.infor.com/browse/SOHO-8083
----

There's a code path in the ListFilter component that is supposed to support case-sensitive filtering.  Currently, this codepath isn't working, and anything filtered while this setting is `true` will not filter acknowledging case.

**Possible fix:**
Use regex to better test text string contents: https://stackoverflow.com/a/8993788/4024149

**Comment by tmcconechy** [comment]
Also when this is done, fix the test:

`xit('can implement case-sensitive filtering', () => {`

**Comment by brianjuan** [comment]
https://4140-beta0-enterprise.demo.design.infor.com/components/autocomplete/example-case-sensitive.html
Passed QA testing on all browsers.
