### ISSUE TITLE
Datagrid: Extraneous horizontal scroll bar appears then disappears.

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise#3851]
**Describe the bug**
Under certain circumstances a **second**, 'ghost' scroll bar will briefly appear under a datagrid when the application menu is collapsed then expanded.

**To Reproduce**
I couldn't find an existing enterprise demo component that shows the behavior, but the NG demo has one. Steps to reproduce the behavior:
1. Using IDS-NG demo...
2. Select the "Data Grid - Save User Settings" demo component.
3. Change the data grid "Records per Page" setting to "10".
4. Click the "hamburger" icon to collapse the Application Menu.
5. Note everything appears correctly.
6. While watching the bottom of the data grid, again click the hamburger icon to expand the Application Menu.
7. Note the horizontal scroll bar briefly appears then disappears under the data grid.

**Expected behavior**
In step #7, the extraneous scroll bar should not appear.

**Version**
IDS Enterprise 4.27.3
IDS NG 7.0.2

**Screenshots**

**Platform**
 - Infor Application/Team Name: M3/GLT
 - Device: PC
 - Browser Name: Chrome
 - Browser Version: 81.0.4044.129

**Additional context**
IMPORTANT: In our application, when there are data grids that already have a horizontal scroll bar, you still briefly see the **second** scroll bar. This is not an issue just for grids that do not have a horizontal scroll bar (as in the demo).

**Comment by tmcconechy** [comment]
Not 100% sure if this is an app menu issue or a datagrid issue. Leaning towards it being an app menu one. The issue seems to be the `page-container scrollable` element is getting a scroll bar while it animates.

Possibly removing scrollable in cases you dont need to scroll the page at all could work. I tested adding `overflow-x: hidden` to `page-container scrollable`  and it fixes it but thats not a fully viable solution for all cases. Perhaps the animation needs to toggle this when it runs?

**Comment by tmcconechy** [comment]
Also looking at this im wondering if a new pattern like https://master-enterprise.demo.design.infor.com/components/page-patterns/example-search-form.html might be interesting to explore.

**Comment by dmcodrum** [comment]
Sure. I'll take a look at it and get back to you. Thanks Tim.

**Comment by tmcconechy** [comment]
Sorry that comment was for another issue - nothing to do with this.

**Comment by dmcodrum** [comment]
Ha! No worries.

**Comment by tmcconechy** [comment]
Decoping this issue for now...As im not sure what we can do about it at this time
