### ISSUE TITLE
TreeGrid: With a frozen column a column's display value may not be visible

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3852]
Describe the bug
A tree grid with a frozen column when expanding the tree a column's value may not be visible since the frozen column can't be scrolled.

1. Go to 'test-tree-frozen-columns.html'
2. Click on the expand icon until the column's value isn't fully visible

In Landmark, a user may add additional rows to a tree branch and eventually the display value will become unreadable.

Version
v4.29.0-dev

Screenshot
![image](https://user-images.githubusercontent.com/39804038/80845306-6a3b0c80-8bce-11ea-92a4-e24900f1e35a.png)

**Comment by tmcconechy** [comment]
We probably need to find a way to scroll on the frozen section. Will investigate

**Comment by jbrcna** [comment]
**QA Failed**
v4.32.0-dev
unable to scroll using Mac/Safari
https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-frozen-columns.html
![image](https://user-images.githubusercontent.com/56722184/91044659-38035e00-e648-11ea-9577-50f83316da30.png)

**Comment by tmcconechy** [comment]
Looks like safari needs a width. Will have to think about this one. Fortunately that browser is only very slightly used.

**Comment by tmcconechy** [comment]
This is fixed now @jbrcna - this is fixed - instead i made the frozen columns scrollable.

**Comment by jbrcna** [comment]
Thank you @tmcconechy!
Upon retest, the issue still persists. All browsers are now affected. Moving this ticket to Failed for now.
v4.32.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-frozen-columns.html
![image](https://user-images.githubusercontent.com/56722184/91555826-4f05c100-e964-11ea-8d6c-8cb7ff113e35.png)
_Screenshot from Edge Browser_

**Comment by tmcconechy** [comment]
@jbrcna i changed the fix around so this is working correctly i think your just testing it wrong.

1) no longer can you scroll the left side
2) in edge has a slight issue on the bottom - ignoring this for now
3) instead resize the column, so rather than scrolling which wasnt working now you have to resize the frozen column to see more of it.

**Comment by jbrcna** [comment]
Thank you for clarifying the issue @tmcconechy. will mark this ticket as passed and moving this ticket to Done.
verified in v4.32.0-beta0
 https://4320-beta0-enterprise.demo.design.infor.com/components/datagrid/test-tree-frozen-columns.html
