### ISSUE TITLE
Datagrid: Tooltip arrow is not pointed in the correct text in Uplift Theme

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3854]
**Describe the bug**
Datagrid: Tooltip arrow is not pointed in the correct text in the Uplift theme

**To Reproduce**
1. Go to https://4280-rc0-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html?theme=soho&variant=light
2. Sort the Activity Column 
3. Hover in the 2nd row of Activity column 

**Expected behavior**
The tooltip should show pointed in the correct grid. 

**Version**
IDS4.280-RC0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/80935944-95f20880-8e01-11ea-8672-2b49f0a30a47.png)

**Platform**
All browsers, OS, and devices. 

**Additional context**
n/a

**Comment by tmcconechy** [comment]
This is similar to https://github.com/infor-design/enterprise/issues/1983 but i think now we should fix this in the future.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/84625238-73313480-af15-11ea-8722-88f17068665d.png)
