### ISSUE TITLE
Datagrid: Badge icon changes after using the search filter

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3855]
**Describe the bug**
Datagrid: Badge icon changes after using the search filter

**To Reproduce**
1. Go to https://4280-rc0-enterprise.demo.design.infor.com/components/datagrid/example-singleselect.html
2. Open the search filter and type 'error'

Notice that some of the badge icons became a text. 

**Expected behavior**
The badge icon should not change. 

**Version**
IDS 4.280 - RC0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/80936550-38ab8680-8e04-11ea-8132-fec120c06962.png)

**Platform**
All Browsers, OS and devices. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This is the same (but a different column) as https://github.com/infor-design/enterprise/issues/3731 and should probably be fixed with it.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.
