### ISSUE TITLE
Datagrid: Filter in pager is not working properly.

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3856]
**Describe the bug**
Datagrid: Filter in pager is not working properly.

**To Reproduce**
1. Go to https://4280-rc0-enterprise.demo.design.infor.com/components/datagrid/example-paging.html?theme=uplift&variant=light
2. Use the filter in Id to '=' 3
3. Select the Id 3 column, notice that the select all function is triggered 
4. Now clear the filter to show all the records. 
5. Notice that Id '0' become selected and not Id '3'

**Expected behavior**
Id '3' should be selected. 

**Version**
IDS 4.280 - RC0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/80939521-87125280-8e0f-11ea-8aa6-3dc37c5efe3b.png)

**Platform**
All browsers, OS, and devices. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
We should probably take a look at this next sprint. I do think there are some similar issues. Like changing page size. Ect

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
