### ISSUE TITLE
Datagrid: stretchColumn resizes the width of the columns upon re-rendering

### ISSUE THREAD

**Issue by sharmainerivera** [infor-design/enterprise#3857]
**Describe the bug**
When there's a set stretchColumn in the datagrid, re-rendering the datagrid resizes the the columns.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-columns-stretch-column.html.
2. Open the browser console (F12 or Ctrl + Shift + I).
3. Re-render the datagrid using the console:
`$('#datagrid').data('datagrid').renderRows() `
4. The widths re-render unnecessarily.

**Expected behavior**
The widths should be the same as it was initially loaded. 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
**stretchColumn on load:**
![image](https://user-images.githubusercontent.com/61222084/80939991-f472b300-8e10-11ea-9e37-48fa0e1ca0cd.png)

**After firing renderRows:**
![image](https://user-images.githubusercontent.com/61222084/80939907-b07fae00-8e10-11ea-998a-253b73992f28.png)

**Here's a GIF of the replication for proper visualization:**
![renderrows](https://user-images.githubusercontent.com/61222084/80940225-b0cc7900-8e11-11ea-824d-c7f7793d4d00.gif)

**Platform**
 - Infor Application/Team Name: Infor Pathway
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Browser Version: Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by marknolaninfor** [comment]
@sharmainerivera 

If you are using renderRows and a stretchColumn column, you should be calling clearCache before like what the ids control does, within the loadData method.

Depending on what you are doing there are other public methods that will call the rendering of the field, row, or dataset. These then could call renderRows with the correct sets, eg the public updateDataset method if you are updating or rerendering a sorted dataset. This then handles the logic and you don't have to call clearCache.

**Comment by marknolaninfor** [comment]
Closing this for the Pathway team as the coding use was not correct and should not have been used.
