### ISSUE TITLE
Datagrid: Selected records become unselected after changing the number of records per page

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3858]
**Describe the bug**
Datagrid: Selected records become unselected after changing the number of records per page

**To Reproduce**
1. Go to https://4280-rc0-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html
2. Select all records 
3. Change the Records per Page to 10

**Expected behavior**
Selected Records 0-4 should be selected. 

**Version**
IDS 4.280 - rc0

**Screenshots**
N/a

**Platform**
All browsers, OS and devices. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This example is doing server side paging. So this is not a bug the row selection will be reset in this scenario.
