### ISSUE TITLE
Datagrid: Move icon is not aligned in uplift theme

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3859]
**Describe the bug**
Datagrid: Move icon is not aligned in uplift theme

**To Reproduce**
1. Go to https://4280-rc0-enterprise.demo.design.infor.com/components/datagrid/example-list-grouped-headers.html?theme=uplift&variant=light
2.  Hover to Product Id column title
3. Notice that the move icon is not aligned properly

**Expected behavior**
Move icon should align properly. 

**Version**
IDS 4.280 - rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/80953793-c9975780-8e2e-11ea-97ab-4adbcefefcb3.png)

**Platform**
All browser, OS and devices. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Minor issue. Also not the hover state on the move icon is incorrect it should be darker not all white.

**Comment by tmcconechy** [comment]
decoping this for right now
