### ISSUE TITLE
SOHO-8080: Datepicker: Value disappears on focus out with yyyyMMdd format

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#386]
The datepicker removes the selected value and displays only the placeholder when the focus on the field is removed if you use yyyyMMdd as date format.

Steps to recreate:
1. Create a datepicker with yyyyMMdd format
2. Click on the calendar icon button of the datepicker
3. Select a date
4. Click anywhere outside the datepicker to remove the focus

ISSUE: the selected value disappeared and only the placeholder is displayed

SohoXi Version: 4.6.0

**Comment by tmcconechy** [comment]
We decided to close this issue. We only support locales with a separator and all of the locales have a  that we support contain a separator. So the code was written such that it relies on a separator.

This would be too much work to support for one edge case. So to fix this on your end just use a separator like . or / or - in the locale. https://www.iso.org/iso-8601-date-and-time-format.html is a recommended format
