### ISSUE TITLE
Multiselect: Enhance standard setting to work like tag

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3864]
**Describe the bug**
The search field in the multiselect (with tags) is within the dropdown, while in the standard multiselect you type directly into the form. We'd like a setting so the search field is in the drop down (and have the setting exposed in ng)

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/multiselect/example-index.html
2. Click on the States drop down under Multiselect (Standard). Compare with the dropdown when the States field under Multiselect (with Tags).

**Expected behavior**
Searchfield is within the dropdown like multiselect (with Tags) dropdown

**Version**

- ids-enterprise: v4.29.0-dev

**Screenshots**

**Platform**
 - All

**Additional context**
![image](https://user-images.githubusercontent.com/22107636/81010718-4f5dd780-8e1c-11ea-96ce-9b983db02301.png)

![image](https://user-images.githubusercontent.com/22107636/81010734-57b61280-8e1c-11ea-8564-a8e3a2a8063b.png)

This is a follow up issue from the design meeting April 27th, 2020.

**Comment by jbrcna** [comment]
**QA Passed**
v4.29.0-dev(Master)
https://master-enterprise.demo.design.infor.com/components/multiselect/example-search-under-selected.html
![image](https://user-images.githubusercontent.com/56722184/81562544-9bce8780-93c7-11ea-8031-e9d9b9fcd727.png)

**Comment by CindyMercadoReyes** [comment]
BDD attached. Thanks, Cindy
[story_github#3864.docx](https://github.com/infor-design/enterprise/files/4622362/story_github.3864.docx)
