### ISSUE TITLE
Messages Component: Icons getting cut off on Uplift Theme

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3867]
**Describe the bug**
Messages Component: Icons getting cut off on Uplift Theme

**To Reproduce**
1. Go to url: https://4280-rc0-enterprise.demo.design.infor.com/  
2. Scroll down to Messages
3. Click on Error Example and also on Success Example
4. See error for both messages on uplift theme the icons on the top left hand corner are getting cut off.  Please see screen shot attached. 

**Expected behavior**
Icons should not get cut off. 

**Version**

- ids-enterprise: [ v4.280]

**Screenshots**
<img width="1175" alt="icons error issue 2" src="https://user-images.githubusercontent.com/39101346/81026223-59490000-8e47-11ea-8240-30ecd4a925b1.png">
<img width="1175" alt="icons issue 1" src="https://user-images.githubusercontent.com/39101346/81026228-5cdc8700-8e47-11ea-8c94-2166239a3270.png">
<img width="1175" alt="icons issue 1" src="https://user-images.githubusercontent.com/39101346/81026239-649c2b80-8e47-11ea-9ced-23e69f0155d0.png">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - OS Version: [iOS 8]
 - Browser Name: [Chrome]

**Additional context**
None

**Comment by janahintal** [comment]
Issue still exists in https://master-enterprise.demo.design.infor.com/components/message/example-index.html?theme=uplift&variant=light

![image](https://user-images.githubusercontent.com/45757016/81161272-e7df8d80-8fbd-11ea-8206-4532bbca6b8f.png)

**Comment by EdwardCoyle** [comment]
@janahintal This is another one that's fixed in https://4280-enterprise.demo.design.infor.com/components/message/example-index?theme=uplift&variant=light (hasn't made it over from `master` yet)

**Comment by tmcconechy** [comment]
@janahintal @EdwardCoyle Was a bug in the deploy its updated now on https://master-enterprise.demo.design.infor.com/components/message/example-index.html?theme=uplift&variant=light too

**Comment by janahintal** [comment]
This issue is now resolved. Thank you :)
