### ISSUE TITLE
Switches Component: Sink page on IE 11 on uplift theme checkmark overlapping Switch component

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3868]
**Describe the bug**
Switches Component: Sink page on IE 11 on uplift theme checkmark overlapping Switch component

**To Reproduce**
1. Go to url: https://4280-rc0-enterprise.demo.design.infor.com/?theme=uplift&variant=light#
3. Scroll down to Switches
4. See error Checkmark boxes appearing on the Switch component. Please see screen shot attached. 

**Expected behavior**
there should not be any overlap on the sink page for any component

**Version**

- ids-enterprise: [e.g. v4.28.0]

**Screenshots**
![bs_win10_IE_11 0(11)](https://user-images.githubusercontent.com/39101346/81027460-d5dddd80-8e4b-11ea-8026-4a8602063d11.jpg)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 ]
 - Browser Name: [IE 11]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
None

**Comment by janahintal** [comment]
The issue still exists. Will move to Failed. 

Steps:
1. Open in IE11 browser - https://master-enterprise.demo.design.infor.com/components/switch/example-index.html?theme=uplift&variant=light
2. Test in both uplift & Soho theme

![image](https://user-images.githubusercontent.com/45757016/81159248-5bcc6680-8fbb-11ea-8502-d51901b37dc6.png)

![image](https://user-images.githubusercontent.com/45757016/81159279-638c0b00-8fbb-11ea-82ec-3251abea8b06.png)

**Comment by EdwardCoyle** [comment]
@janahintal this one is also fixed on https://4280-enterprise.demo.design.infor.com/components/switch/example-index?theme=uplift&variant=light (hasn't made it into `master` just yet)

**Comment by tmcconechy** [comment]
There was a bug in the deploy, it shoudl work on https://master-enterprise.demo.design.infor.com/components/switch/example-index.html?theme=uplift&variant=light now too

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. :)
