### ISSUE TITLE
SOHO-8079: Datagrid expand is not working when search is enabled

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#387]
Describe the bug
Data grid Expander issue: When search is running and click on expander not open the expand area.

1. Go to http://usalvlhlpool1.infor.com/4.5.0/components/datagrid/example-expandable-row.html
2. Click on First expander, expander works fine. No issue
.3. click on Search Icon in the Toolbar.
4. Search for "Another"
5. search result will show in the data grid.
6. click on any expander icon, not able to see the expander area.
Expected behavior
Expander area should be visible.*Screenshots*Please find the attached screen shot

Platform:
I have tested in chrome and IE. both have same issue.

**Comment by tmcconechy** [comment]
This issue can no longer be reproduced on the latest http://latest-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row.html , so seems like it was fixed along the way.
