### ISSUE TITLE
Calendar: Request for a Tree List Type Legend Display

### ISSUE THREAD

**Issue by rowelineeveresurreccion** [infor-design/enterprise#3870]
**Is your feature request related to a problem or use case? Please describe.**
The Legend display list is only at one level. However, in the use case of Pathway, the items in the Legend have sub-items that form levels like in Tree lists (as seen below).

**Describe the solution you'd like**
The Legend display would be suitable for Pathway if there is a way to make lists support Tree Lists.

**Describe alternatives you've considered**
n/a

**Additional context**
-	Infor Pathway uses the Calendar in booking Facilities. Hence, the Facilities are listed as the Legend’s items. These facilities have sub-facilities as well as seen below.
o	Additionally, if a higher level item in the Facilities is checked all of its sub-facilities will get checked as well.

Sample:
![image](https://user-images.githubusercontent.com/50350478/81042512-de352780-8ee2-11ea-973b-34ccf36d6d6f.png)

IDS Calendar Legend:
https://master-enterprise.demo.design.infor.com/components/calendar/example-only-calendar-legend.html

![image](https://user-images.githubusercontent.com/50350478/81042769-6adfe580-8ee3-11ea-8ac3-3426e5bf3e0f.png)

**Comment by tmcconechy** [comment]
I might add you could possibly try and implement this as it does seem a bit "custom". It may be possible to change out whats in https://github.com/infor-design/enterprise/blob/master/app/views/components/calendar/example-index.html#L3 in the template with a tree multiselect https://master-enterprise.demo.design.infor.com/components/tree/example-select-multiple.html but im not sure if this will work.

Just worth mentioning.

**Comment by maeroseb** [comment]
Hi Tim,

I tried to check whether it's possible to implement your suggestion but I think it's not possible. Upon checking, the rendering of the Calendar Legend is in the sohoxi.js renderEventTypes function where it assigns the event types markup to the inner html of the event type container.

![Render Event Types](https://user-images.githubusercontent.com/64888576/81146117-400c9480-8faa-11ea-9471-7096b933b6ab.png)

I checked whether I can pass the legend template as a setting for the Calendar but I didn't find a parameter for this.

![Calendar Settings](https://user-images.githubusercontent.com/64888576/81146228-74805080-8faa-11ea-974e-43b7dd0b6020.png)

And about changing what's in the template (class calendar-event-types which is being referenced in the renderEventTypes). Like we can try to use li and ul tags but I don't think it's possible to do the checking whether an event type has sub-event types (if this is the case a ul with li tag must be created, otherwise we'll use li tag only)
![Template](https://user-images.githubusercontent.com/64888576/81151490-9e8a4080-8fb3-11ea-8077-8a5832f888e2.png)

Thank you.

**Comment by tmcconechy** [comment]
OK, Yes that was just a guess. I sort of forgot what we did in there. I can see now this wouldn't be possible without making a setting or a modification of some kind. We will have to think this through in a future sprint.

**Comment by maeroseb** [comment]
Hi Tim,

This is a sample structure of the event type. Hope this helps.
![Event Type](https://user-images.githubusercontent.com/64888576/81247851-9aaafc80-904d-11ea-9774-25a4f0c56a81.png)

**Comment by tmcconechy** [comment]
OK, i dont fully understand that but thats probably ok. Want i meant is we have the event types in the legend like this https://github.com/infor-design/enterprise/blob/master/app/data/event-types.json

I guess we would just add a children to this JSON with children and that would be our tree then you would have to massge the data into our format. I think that would work

**Comment by maeroseb** [comment]
That's actually a sample data (I was advised not to fully disclose the data structure) in our event type that is used for our legend. Sorry for not providing what you really needed. But yes, I agree, we'll just work on the format you'll be providing. Thanks.

**Comment by marknolaninfor** [comment]
@maeroseb 

You would actually change the data entity to match the calendar structure like what is done for the id of the event, eg mapping of the tpk  to the id, so you would do the same for the parent to the logical name that will be used within the control. It is very easy to alter the data structure over making the control more complex.

**Comment by tmcconechy** [comment]
Just thinking, is it just one parent and n children? Or do we have to assume multiple (3-12 levels?) of checkboxes. Because if it’s just one parent and stuff under then that might simplify this feature greatly.

**Comment by maeroseb** [comment]
Hi @marknolaninfor thank you for telling me about that and will take note about it the next time.

Hi @tmcconechy, yes, it's just one parent and n children. Thank you.

**Comment by maeroseb** [comment]
Hi @tmcconechy, yes just one parent and n children.

![image](https://user-images.githubusercontent.com/64888576/84615964-ff832d80-aefc-11ea-97c9-18bb5523e475.png)

**Comment by kevinwhitedesign** [comment]
@katieinfor needs a ticket

**Comment by katieinfor** [comment]
Jira Ticket: https://jira.infor.com/browse/UXD-2940

**Comment by timothyholton** [comment]
Hi.  I am reviewing some older tickets.  This one is still required by Pathway users, but it was closed for some reason.  Is it possible to re-open this one so it can be actioned at some point?  Thanks.

**Comment by timothyholton** [comment]
Please also note that the "children" of each "parent" in the event types need to be collapsible too.

**Comment by tmcconechy** [comment]
Closed by stale bot. We can look when we have bandwidth

**Comment by timothyholton** [comment]
Hi @talkaboutdesign.  Currently in our context (of showing parent item and their child items) we only need one color.
Please note that both parent items and their child items can have events on the calendar, so the parent items are not just "categories" or "groupings" but can have their own events too.  Thanks.

**Comment by ericangeles** [comment]
Do we have a final design for this ticket @hey-yall  @talkaboutdesign?

**Comment by tmcconechy** [comment]
yes @ericangeles its on the Jira in the last comment see https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=346-11564&mode=design&t=vMDkzjQUuuWLIRI6-0

will need preferences/markup to keep the current way as an option

**Comment by ericangeles** [comment]
Great. Let’s get this done.

**Comment by hey-yall** [comment]
Design assets are here: https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=346-11564&mode=design&t=bLwOgSaJJvNm5Jfd-4 

Tracked under Jira ticket https://jira.infor.com/browse/IDS-92
