### ISSUE TITLE
Tabs: Search bar is not visible when in responsive view 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3871]
**Describe the bug**
Tabs: The search bar is not visible when in responsive view 

**To Reproduce**
1. Go to https://4280-rc0-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html
2. Minimize the screen and notice the search bar changed its color with the same color as the header. 

**Expected behavior**
The search bar should not change its color when in responsive view. 

**Version**
IDS 4.280 - RC0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/81060156-75f73d80-8f04-11ea-8ad5-f4b2cfaea341.png)

**Platform**
All browser, OS and devices. 

**Additional context**
N/a

**Comment by EdwardCoyle** [comment]
Probably need to check the `.non-collapsible.is-open` CSS classes to make sure background color is not being overridden.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html
![image](https://user-images.githubusercontent.com/45757016/81919240-2acae200-960a-11ea-9f1d-01c6a6298f60.png)
