### ISSUE TITLE
Tabs: Tooltip is not showing after adding a long tab name

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3872]
**Describe the bug**
Tabs: Tooltip is not showing after adding a long tab name

**To Reproduce**
1. Go to https://4280-rc0-enterprise.demo.design.infor.com/components/tabs-module/example-add-tab-button.html
2. In the New Tab Builder, add a long Tab Name and Create a new Tab. 
3. Hover in the newly created Tab

**Expected behavior**
Tooltip should appear after hovering in the long Tab Name

**Version**
IDS 4.280-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/81063269-18fe8600-8f0a-11ea-8173-12dded2f1e7f.png)

**Platform**
All Browser, OS and devices. 

**Additional context**
N/a

**Comment by EdwardCoyle** [comment]
Tested this back to 4.18.x and it hasn't worked in quite some time, but [there's a code path present](https://github.com/infor-design/enterprise/blob/master/src/components/tabs/tabs.js#L287-L294) that should allow this to work.

**Comment by EdwardCoyle** [comment]
@janahintal I realized while testing this that you're not seeing the ellipsis here because it's an "opt-in" feature, and this particular sample didn't enable the setting.  I've made a PR to enable the setting, and once approved, we'll send it back for review.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you! :)
