### ISSUE TITLE
Hierarchy: Popup menu doesn't open after clicking '...' more button in the tree

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3873]
**Describe the bug**
Hierarchy: Popup menu doesn't open after clicking '...' more button in the tree

**To Reproduce**
1. Go to https://4280-rc0-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html?theme=uplift&variant=light
2. In 'Kaylee Edwards' click '...' more button to show details or to open the popup menu

**Expected behavior**
Details should show up / popup menu should appear

**Version**
IDS 4.280-RC0

**Screenshots**
N/A

**Platform**
All browser, OS and devices.

**Additional context**
N/a

**Comment by EdwardCoyle** [comment]
@krishollenbeck is this working on your end?  I can reproduce in Enterprise but not sure where it's broken yet.

**Comment by EdwardCoyle** [comment]
Seems like [recent additions](https://github.com/infor-design/enterprise/pull/3761/files#diff-aea1a627e9a642001358bb80d2b775b4R333) to manually open the Popupmenu from the Hierarchy component are conflicting with Popupmenu's built in [context menu handler](https://github.com/infor-design/enterprise/blob/master/src/components/popupmenu/popupmenu.js#L919-L923).  Setting break points in both these points will demonstrate the menu opening, then immediately closing.

**Comment by janahintal** [comment]
The issue still exists. Will move to Failed. 

1. goto https://master-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html?theme=uplift&variant=light
2. In 'Kaylee Edwards' click '...' more button to show details or to open the popup menu

**Comment by EdwardCoyle** [comment]
@janahintal it seems that the last items from `4.28.x` haven't been merged to `master` yet.  https://4280-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html?theme=uplift&variant=light shows the issue fixed.

**Comment by tmcconechy** [comment]
@janahintal @EdwardCoyle Was a bug in the deploy its updated now on https://master-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html?theme=uplift&variant=light  too

**Comment by janahintal** [comment]
Hi guys. Thank you. Its now working in Master and 4280-enterprise. 

![image](https://user-images.githubusercontent.com/45757016/81283051-9ce17b00-908e-11ea-8ae3-55641c869211.png)

![image](https://user-images.githubusercontent.com/45757016/81283011-918e4f80-908e-11ea-869c-106b2cfb8370.png)
