### ISSUE TITLE
Datagrid: modal dialog containing a datagrid issue with horizontal scrollbar

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3879]
Describe the bug
When opening a modal dialog containing a datagrid, if the browser's window is resized smaller a horizontal scrollbar appears on the modal body.  Want the horizontal scrollbar to appear on the datagrid itself.

To Reproduce
1. Go to 'test-modal-datagrid-two-columns.html'
2. Open the browser's debugger (in this example align debugger on the right)
3. Narrow the browser window until the horizontal scrollbar appear on the modal dialog

Expected behavior
Horizontal scrollbar appears on the datagrid itself.

Version
4.29.0-dev

Additional context**
if width:100% is added to the div element with a class of modal-body the scrollbar appears on the datagrid vs the modal-body.

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/81086052-9ea81480-8ebd-11ea-8303-0755d8853cb5.png)

**Comment by claudenbach** [comment]
![Git-3879](https://user-images.githubusercontent.com/39804038/81086552-445b8380-8ebe-11ea-93dd-19a79e1f99e5.gif)

**Comment by EdwardCoyle** [comment]
@claudenbach you mentioned this:
> if width:100% is added to the div element with a class of modal-body the scrollbar appears on the datagrid vs the modal-body.

I believe that is our recommended way of handling scrolling issues within the Modal... Any thoughts @tmcconechy?

**Comment by tmcconechy** [comment]
Yes it is. These data grid on modal issues are challenging because there is no widths set on the table. We have a way to do that with a default class now. Which might work but i think here the real ask was to be able to scroll in the grid itself not the modal body.

I know we discussed that somewhere @claudenbach ? Is this the issue around having a setting to scroll the grid not the modal? Or was that another issue im not finding?

**Comment by claudenbach** [comment]
Yes, this is the issue to scroll the datagrid.  We discussed last week with Phillip in Teams.

**Comment by claudenbach** [comment]
On that default class issue, when adding the class of 'datagrid-default-modal-width' using .cssClass on sohoModalDialogService, the class gets added to the div element with class of 'modal' but its not working.  Snippet of our code....

```
      this.dialog = this.sohoModalDialogService
      .modal(LMListLookupDialogComponent, this.modalPlaceholder)
      .buttons(buttons)
      .title(title)
      .autoFocus(false)
      .cssClass('datagrid-default-modal-width')
      .open()
      .apply((lookupDialog: LMListLookupDialogComponent) => {
        lookupDialog.listUrlInfo = listUrlInfo;
        lookupDialog.listSpec = listSpec;
        lookupDialog.selectRequestData = {
          viewType: 'list',
          viewName: this.listSpec.busListSpec.name,
          dataView: dataView
        };
```

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/81096571-3876be00-8ecc-11ea-935a-b47e65054e5e.png)

**Comment by tmcconechy** [comment]
Yeah look slike its adding the class but maybe not the width? Its in the right place tho.

Try debugging
```
      if (!this.elemWidth && this.element.closest('.datagrid-default-modal-width').length > 0) { // handle on invisible modal
        this.elemWidth = this.settings.paging ? 466 : 300; // Default a size for when on modals
        this.element.css('width', this.elemWidth);
        this.element.css('min-width', 0);
        this.isInModal = true;
```

And in the spector it should get added as an inline css width...
![Screen Shot 2020-05-05 at 1 38 33 PM](https://user-images.githubusercontent.com/814283/81097374-cd31e980-8ed5-11ea-946f-736d0795933a.png)

Maybe we just give up and add a fixed with to modals on dialogs. Just not sure what i'll break. I think a lot.

**Comment by claudenbach** [comment]
When we get into the method calculateColumnWidth, this.elemWidth has already been set by the columnWidth() method so the code that you mentioned in never hit.

**Comment by claudenbach** [comment]
![WidthSetting](https://user-images.githubusercontent.com/39804038/81114438-a54b8180-8ee7-11ea-9469-dc82beb1e8eb.gif)

**Comment by janahintal** [comment]
This issue is now Resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-two-columns.html
