### ISSUE TITLE
SOHO-8077: [All Browsers] Lookup Control: Gray shading appearing on the custom modal page

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#388]
1. http://470-rc1-sohoxi.demo.design.infor.com/components/lookup/test-custom-modal.html

2. [All Browsers] Lookup Control: Gray shading appearing on the custom modal page

3. Please see screen shot attached

**Comment by tmcconechy** [comment]
This issue can no longer be seen on http://latest-enterprise.demo.design.infor.com/components/lookup/test-custom-modal.html so seems like it was fixed along the way
