### ISSUE TITLE
Hierarchy: Can't use keyboard navigation to open More Actions menu

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#3881]
**Describe the bug**
The Hierarchy component is currently not displaying any content if keyboard navigation is used to access a leaf's "More Actions" menu before it's clicked.

**To Reproduce**
1. Go to http://localhost:4000/components/hierarchy/example-context-menu-with-details.html?theme=uplift&variant=light
2. Use the keyboard to focus the leaf with "Kaylee Edwards".  Use tab/shift+tab.
3. Press the Enter key to open the Popupmenu.  See that it's empty.
4. Click the Popupmenu trigger.  It should re-open and become populated.

**Expected behavior**
- [ ] To work within the rendering process of the Popupmenu, we shouldn't be adding items to the menu on the fly at different points in its lifecycle.  We need to change the Hierarchy component to string together all the markup at once, and return it via `settings.beforeOpen()`.  This will allow the menu to be built at the right times, get all events/interactions assigned, etc.
- [ ] We need to rework this event handler into a testable function that can also be triggered with a keyboard action.

**Version**
[v4.29.x]

**Screenshots**
![Screen Shot 2020-05-05 at 3 06 19 PM](https://user-images.githubusercontent.com/3249601/81105508-0bcda100-8ee2-11ea-8488-a96b9dde4aa3.png)

**Platform**
 - n/a

**Comment by EdwardCoyle** [comment]
@krishollenbeck I'm putting this on the backburner for now.  I tried down the path of working the [`updateActions`](https://github.com/infor-design/enterprise/blob/master/src/components/hierarchy/hierarchy.js#L319) system and the [`mouseup` event](https://github.com/infor-design/enterprise/blob/master/src/components/hierarchy/hierarchy.js#L201) into something that plays nice with Popupmenu's `beforeOpen`, but I'm not fully understanding all the "actions" going on here.  We'll move this to a future sprint and hopefully can spec this out further.

**Comment by tmcconechy** [comment]
Descoping this for now
