### ISSUE TITLE
Accordion: The top border on the selected accordion header is missing

### ISSUE THREAD

**Issue by krishna-sadhu** [infor-design/enterprise#3885]
**Describe the bug**
Hi, I'm trying out an Accordion in the widget. The top border on the selected accordion header is missing. This is happening when the accordion panel above it is expanded

**To Reproduce**
- go to https://master-enterprise.demo.design.infor.com/components/accordion/example-index.html
- expand brand name
- focus material
- see the top border is missing
- try same in uplift

**Expected behavior**
A full border is expected when the accordion header is selected and focused

**Version**
- ids-enterprise: 4.22.0 to 4.28

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 81.0.4044.122

**Comment by EdwardCoyle** [comment]
[Relevant MS Teams Chat](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1588679129616?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1588679129616&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=General&createdTime=1588679129616)

We need to see what the focus states are doing on top-level accordion headers

**Comment by tmcconechy** [comment]
A workaround and ultimate fix is to manually add/modify this rule...

```
.accordion-pane.is-expanded + .accordion-header.is-focused {
    border-top-color: #368ac0;
}
```

For uplift the fix would be different..

**Comment by jbrcna** [comment]
**QA Passed**
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/accordion/example-index.html
![image](https://user-images.githubusercontent.com/56722184/82327562-2b4fe800-9a11-11ea-9961-f93b5c64ddbe.png)

**Comment by jbrcna** [comment]
Hi, I found the issue exists while testing v4.34.0-dev. I test the prev versions and been present at least 4.32.x
![image](https://user-images.githubusercontent.com/56722184/96717989-f12cad00-13d9-11eb-9197-b5a939dc74ca.png)

**Comment by tmcconechy** [comment]
Lets test this again if the issue is back?
