### ISSUE TITLE
Popover:  Details disappear after resizing & closing the popover in Windows 10 IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3886]
**Describe the bug**
Popover:  Details disappear after resizing the window & closing the popover in Windows 10 IE11

**To Reproduce**
1. Go to IE11  https://4280-rc0-enterprise.demo.design.infor.com/components/popover/example-index.html?theme=uplift&variant=dark
2. Click the button to show the popover
3. Minimize the window 
Notice that the details disappear 

**Expected behavior**
Popover details should not disappear after closing & resizing the window

**Version**
IDS 4.280-RC0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/81157937-1196b580-8fba-11ea-87c8-118806feb72c.png)

**Platform**
Windows 10 IE 11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Given https://github.com/infor-design/enterprise/issues/3756 we can likely descope this. Sometime...

**Comment by tmcconechy** [comment]
Descoping this for now
