### ISSUE TITLE
SOHO-8075: Datagrid - tabbing into editable cells not working

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#389]
Landmark requires the ability for power uses to quickly add rows to a datagrid.  

With editable cells in the datagrid, the tab key (to move to cell to the right) or tab + shift key (to move to the cell to the left) does not move across the cells of a row.  When tabbing into an editable cell, the cell should be in edit mode.

Tried adding the grid options of actionableMode: true and cellNavigation: true, but these don't affect the desired behavior.

This worked in 3.5 with the grid option of allowTabs: true. But allowTabs doesn't seem to available in 4.0.  

I've attached an updated version of example-editable.html to illustrate. Also attached a gif file to demonstrate how it was working in 3.5 to show what's needed in 4.0.

**Comment by brianjuan** [comment]
Moving to Failed QA. When the user tab into the Order Date column and accidentally typed an invalid date, for example: 2/29/2018 then hit Tab again, the focus will go on the Pagination control not to the next column.

You can also notice that there still a focus on the Order Date column even you click on the other cells.

**Comment by tmcconechy** [comment]
Im seeing an error "Uncaught TypeError: Cannot read property 'getDate' of undefined" in the console. This might be why... @deep7102

**Comment by tmcconechy** [comment]
As noted
- type 11/ in the date cell gives an error
- tab into dropdown column and it opens (should need to do down arrow to open)
- tab out of dropdown stays open (related to previous)
- datepicker when in error has an uneeded box shadow
