### ISSUE TITLE
Calendar: Color Settings for the Weekend, Public Holiday and Other dates 

### ISSUE THREAD

**Issue by fritzm-ux** [infor-design/enterprise#3893]
**Is your feature request related to a problem or use case? Please describe.**
Calendar does not currently have a support to change the colors for the Weekend, Public Holiday, and Other events. Infor Pathway makes use of specific colors for the calendar.

**Describe the solution you'd like**
Calendar would work better if it allowed choosing of changing colors for the Weekend, Public Holiday, and Other events based on the user's selection or settings

**Describe alternatives you've considered**
N/A

**Additional context**

- Infor Pathway has a page settings for Calendar Colors like below:
![image](https://user-images.githubusercontent.com/64887117/81250258-15c2e180-9053-11ea-9659-82d2518a848e.png)
- It would be helpful if the Calendar can be accept user-defined values for the color settings of specific day types

**Comment by tmcconechy** [comment]
@fritzm-ux do you mean this calendar ? https://latest-enterprise.demo.design.infor.com/components/calendar/example-index.html sometimes people refer to the datepicker as a calendar.

If so yes we only allow these colors at the moment https://github.com/infor-design/enterprise/blob/master/app/data/event-types.json#L3

https://latest-enterprise.demo.design.infor.com/components/colors/example-index.html this is really because of the branding. You want some specific hex values or can you just make those dropdowns all the 8 colors we have? If specific is needed you could probably do it by adding some css classes but we could maybe look into making it possible if thats what is needed.

**Comment by fritzm-ux** [comment]
Apologies for the confusion. But, yes, that is the Calendar I am referring to - not the datepicker.

Our QAs really see fit that the users are allowed to use any hex colors they have for personalization. The old version of our system allows that so now that we're using IDS they'd like to have the same. We'll just wait for this if ever this gets implemented. But, I'll take note of your suggestion as well.

Thanks for this.

**Comment by tmcconechy** [comment]
You can disable weekends https://master-enterprise.demo.design.infor.com/components/monthview/test-disable-weekends.html but that means they cant be used. If thats the use case it is possible.


We can allow custom hex values. I think maybe customers could have their own colors but ideally we stick to our theme colors by default unless needed.

**Comment by marknolaninfor** [comment]
@tmcconechy 

I will explain this, Fritz would be asking for the calendar control, to have the same functionality as the datepicker where a legend can be applied, eg Weekends, and other date types defined in the legend. 

If it was applied at the calendar level, and then applied down to the view, either month, or week/day, then it would make more logical. 

Also the example of disabled dates would be better if it was at the calendar level, and not the view level.

**Comment by tmcconechy** [comment]
Makes sense in that context, thanks @marknolaninfor

**Comment by tmcconechy** [comment]
cc @inforandy

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-beta1
https://4310-beta1-enterprise.demo.design.infor.com/components/lookup/test-paging-server-side-keyword-search.html
![image](https://user-images.githubusercontent.com/56722184/88903302-0df78f80-d286-11ea-85bb-c81eab05112d.png)
