### ISSUE TITLE
RTL: Datagrid list mode extra vertical line

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#3895]
**Describe the bug**
When using Datagrid in list mode and RTL, there is an extra vertical line before the last column (reading from right to left).
I believe that it's because the CSS elements:
`html[dir='rtl'] .datagrid-container .datagrid-wrapper:not(.left) td:last-child {
  border-right-color: #5c5c5c; }`
and
`html[dir='rtl'] .datagrid th:last-child {
  border-right: 1px solid #5c5c5c; }`

(In the LTR mode they are empty)

**To Reproduce**
1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-list.html?locale=he-IL](https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-list.html?locale=he-IL)
2. See the vertical line between **Customer Since** and **Contact Name**
3. (because there is a frozen column in this example the vertical line is not the last line)
4. See screenshot without the frozen column, it's clearer.

**Expected behavior**
The behave the same as LTR.

**Version**

- ids-enterprise: v4.28.0

**Screenshots**
(For this screenshot I removed the Frozen Column)
![extra vertical](https://user-images.githubusercontent.com/34129313/81296590-ca242e00-907a-11ea-92c0-6b7b0ed4425f.JPG)

**Platform**
 - Browser Name: Chrome

**Additional context**
Thanks!

**Comment by tmcconechy** [comment]
This is due to the frozen columns. Was meant to have a divider there but its showing on both sides.

**Comment by jonathanamiran** [comment]
But it also visible without using frozen columns.
This is an example with the frozen column removed:
[https://jsfiddle.net/sebulbajoe/ayb5gqw3/10/](https://jsfiddle.net/sebulbajoe/ayb5gqw3/10/)

**Comment by tmcconechy** [comment]
Oh, ok i thought it was the frozen columns thing. Anyways should be easily fixable
