### ISSUE TITLE
Datagrid: display issue with modal dialog containing a datagrid and search form

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#3897]
Describe the bug
A datagrid doesn't expand to fill the table width when the visibility of a search form within the modal dialog is toggled to show and hide.

To Reproduce
1. Using the attached test-modal-datagrid-search-form.html ([Git-3897.zip](https://github.com/infor-design/enterprise/files/4596205/Git-3897.zip))
2. Click the filter icon on the toolbar 
3. Width of the modal dialog grows - the grid table doesn't expand
4. Click the filter icon on the toolbar

Version
v4.29.0-dev

Screenshots

![image](https://user-images.githubusercontent.com/39804038/81352701-cac5c000-908c-11ea-8095-15cc0f234797.png)

![image](https://user-images.githubusercontent.com/39804038/81352721-d2856480-908c-11ea-9ac8-2b2c8a090ff8.png)

**Comment by claudenbach** [comment]
[Git-3897.zip](https://github.com/infor-design/enterprise/files/4596205/Git-3897.zip)

**Comment by claudenbach** [comment]
This is how it looks in Landmark...

![image](https://user-images.githubusercontent.com/39804038/81353070-c0f08c80-908d-11ea-84c8-fa274400b474.png)

![image](https://user-images.githubusercontent.com/39804038/81353095-cfd73f00-908d-11ea-98f9-9d3489a1cc74.png)

**Comment by tmcconechy** [comment]
Have to test `-webkit-fill-available` out thats a neat idea i hadn't considered.

**Comment by jamie-norman** [comment]
Looks like the IDS team is moving this into the current sprint. We continue to hear more noise and bugs written against this (in HCM and in Landmark), so I appreciate the focus on this issue.

**Comment by claudenbach** [comment]
Seeing noise on the rendering of a lookup select list in a modal dialog were the last column doesn't stretch to fill the space.  A separate issue is when the modal dialog containing a lookup select has a search form.

**Comment by jbrcna** [comment]
**QA Passed** with observation
v4.30.0-dev
Tested in all major browsers (Chrome, Firefox, Safari, Edge etc)
https://master-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-search-form.html
![image](https://user-images.githubusercontent.com/56722184/85718549-33dac300-b721-11ea-94e9-05bdd48ca76e.png)

**Observation**
In `Firefox`, the modal looks big
![image](https://user-images.githubusercontent.com/56722184/85721233-c1b7ad80-b723-11ea-9b7a-f3deea902ae7.png)
