### ISSUE TITLE
About: When the about dialog is closed using ESC key it cannot be reopened

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#3898]
**Describe the bug**
About dialog cannot be reopened after it has been closed using the ESC key.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/about/example-index.html
2. Click on Show About Screen
3. Press ESC key
4. Click on Show About Screen
5. See error - Nothing happens

**Expected behavior**
About dialog should be opened again when pressing the "Show About screen" button after the ESC key has been used to close it.

**Version**

- ids-enterprise: 4.28.0

**Screenshots**
-

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 81.0.4044.129 (Official Build) (64-bit)

**Additional context**
-

**Comment by tmcconechy** [comment]
I think that this broke recently as @EdwardCoyle was working on ESC key recently for modals and toasts. I think we should fix this sooner than later so adding to 4.29 if we can get to it ...

See it worked last in 4.27 https://4270-enterprise.demo.design.infor.com/components/about/example-index.html

**Comment by jbrcna** [comment]
**QA Passed**
this is now working in v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/about/example-index.html
