### ISSUE TITLE
SOHO-8073: [IE11, Chrome] Editor - Styling can be applied on white-space characters

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#390]
Users should not be able to apply some of the font styling on white-space characters. i.e. the user pressed space or tab and selected that white space and applied Underline or Strikethrough on it.
It is expected that whitespace cannot have font styling applied on it. Other formatting could be acceptable, such as indentation.

![styling on whitespace](https://user-images.githubusercontent.com/814283/50917415-71ec0600-140b-11e9-9b66-d7b9b282117a.png)

**Comment by davidcarlsonberg** [comment]
@clepoer To clarify, if user highlights ONLY whitespace, styling should not apply? But if user highlights a block of text that has characters AND whitespace, styling should apply?

**Comment by deep7102** [comment]
I agree with @davidcarlsonberg and @EdwardCoyle

**Comment by davidcarlsonberg** [comment]
Closing after discussion because "it seems logical and expected" as currently implemented.
