### ISSUE TITLE
SOHO-8072: [IE11, Chrome] - Editor controls can be all triggered at same time

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#391]
**More Important Bug**
- Type a line line “this is a header”
-  select and make it H4
-  select and make it H3 (both H4 and H3 show it cant be both)

Markup is showing it as just an H3, so H4 shouldnt show.

**Additional info**
When using the SoHo Editor the user is able to trigger all controls at the same time on one selection.

1. The problem only persists when a word (or characters) is selected and the controls are pressed one after another.
    ![all controls triggered](https://user-images.githubusercontent.com/742319/54776934-86a50100-4be7-11e9-8f54-95f0a36326e4.png)
1. If the user clicks away on a different word, the currently applied styling is properly shown in the controls toolbar.
    ![word selected - no problem](https://user-images.githubusercontent.com/742319/54776946-8b69b500-4be7-11e9-8335-0d8fd8b34e27.png)

Essentially, it would be ideal if the user has selected `H2` and decided to change it to `H3`, `H2` would get unselected. This applies to other controls that have no logical way of being applied together on one selection, i.e., can't have indent left and indent right at same time.

**Comment by KnuthK** [comment]
Any progress? @deep7102 this issue really makes our product ugly to use.

**Comment by tmcconechy** [comment]
@KnuthK I think this was in a sprint but was pulled. It is no longer in progress. I'll put back inline for a near sprint. I think this doesnt seem very important because the only way it happens is if someone decides to press every button, which i dont think is a common case.

Unless there is a different similar use case your seeing a problem worth mentioned?

**Comment by tmcconechy** [comment]
Updated the simpler bug to clarify to which i think you are probably having the more important problem.

**Comment by tmcconechy** [comment]
We will fix that More Important Bug section and leave the Additional info part alone. If the user chooses to use that many features on it we cant really control that.

**Comment by janahintal** [comment]
QA Passed. Will move to Done. Thanks. 
Verified in: http://master-enterprise.demo.design.infor.com/components/editor/example-index.html
