### ISSUE TITLE
Tree: Option to add new child node on top or bottom

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise#3915]
**Is your feature request related to a problem or use case? Please describe.**
Tree component addNode feature will when adding child nodes automatically put the new child node at the bottom of the list of children. (See attached screenshot)

If I configure single nodes to be added on top this will force me to have a different behavior for single nodes vs child nodes. 

**Describe the solution you'd like**
Tree component would allow for a better UX if child nodes can be configured to add on top or bottom. 
I would like to be able to supply the same option as when adding a single node:
```
// Example of current way to add single node
tree.addNode(newSingleNode, "top")

// Example of current way to add child node
newChildNode.parent = parentId;
tree.addNode(newChildNode);

// Proposed improvement, adding child node with top/bottom option
newChildNode.parent = parentId;
tree.addNode(newChildNode, "top");
```

**Describe alternatives you've considered**
Alternatively setting the top/bottom string on the newChildNode object but that would not align with how this option currently works for single nodes.

**Additional context**
Current behavior, new child node is automatically added at the bottom:
![image](https://user-images.githubusercontent.com/9215760/81734032-334cdc80-9493-11ea-9342-f748613b0f6d.png)

**Comment by karinthulin** [comment]
@tmcconechy can this issue be prioritized? We need the resolution to be able to address an issue in PIM.

**Comment by tmcconechy** [comment]
OK, I put it in the next sprint. We should be able to get to it then.

**Comment by karinthulin** [comment]
Thanks!

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/tree/test-add-node.html
![image](https://user-images.githubusercontent.com/45757016/87295954-96f99180-c538-11ea-97f6-3b896601134e.png)
