### ISSUE TITLE
Datepicker: Disable function is different to other controls

### ISSUE THREAD

**Issue by victorclisbyinfor** [infor-design/enterprise#3917]
**Describe the bug**
When you call the disable function on a Datepicker, the input element and the label become greyed out. When you call the disable function on a Dropdown, Input, Textarea (and probably other controls), only the input element becomes greyed out (not the label).

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/textarea/example-short.html
2. In the console, run: $('#description-max').disable()
3. Note that just the textarea box appears greyed out. The label is unchanged
4. Go to https://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html
5. In the console, run: $('#date-field-normal').disable()
6. Note that both the label and the input element appear greyed out

**Expected behavior**
I would expect the behaviour to be consistent. Whether this means tweaking the disable function for the Datepicker control so that it doesn't disable the label or tweaking the disable function of all the other controls so that it does disable the label.

**Version**

- IDS Enterprise Components - v4.27.1

**Screenshots**
When a Textarea is disabled, the label remains unchanged:
![image](https://user-images.githubusercontent.com/60455089/81898478-ddde1000-95f7-11ea-8dc9-c5d377eb8644.png)

When a Datepicker is disabled, the label is greyed out:
![image](https://user-images.githubusercontent.com/60455089/81898520-edf5ef80-95f7-11ea-9713-b18b7960ed2c.png)

**Platform**
- OS Version: Windows 10
- Browser Name: Chrome
- Browser Version: 81.0.4044.138

**Additional context**
One of our customers has raised that when an empty Input or Textarea is disabled it is difficult to visually identify that it is disabled as the change in styling is very subtle compared to when it is enabled. For example:

Enabled:
![image](https://user-images.githubusercontent.com/60455089/81899172-601b0400-95f9-11ea-8068-bb62e6b711b4.png)

Disabled:
![image](https://user-images.githubusercontent.com/60455089/81899220-788b1e80-95f9-11ea-9a37-82ce8467324b.png)

This scenario could be improved by having the label greyed out when the control is disabled (like the Datepickers current functionality) as this would help indicate to the user that the control is disabled. As briefly mentioned above in the Expected behaviour, this would mean refactoring the disable function for these two controls and all the other controls so that all controls are consistent. I'm not sure if this minor problem justifies making all those changes, so the easier solution to achieve consistency would be to tweak the disable function on the Datepicker so that it doesn't disable the label.

**Comment by tmcconechy** [comment]
I think the idea is that the label is also disabled. This will help the scenario mentioned about the text area being hard to distinguish. So for who picks this up, suggest making the disable, readonly function also dim/enable the label.

**Comment by EdwardCoyle** [comment]
Is there a difference between the visual state of a readonly label and a disabled label?

**Comment by tmcconechy** [comment]
No @EdwardCoyle the label was only disabled on disabled inputs

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/form/example-disabled-field.html
