### ISSUE TITLE
ProcessIndicator: Visual Enhancements Needed

### ISSUE THREAD

**Issue by jamie-norman** [infor-design/enterprise#3918]
**Is your feature request related to a problem or use case? Please describe.**
A clear and concise description of what the problem is. [e.g. {Component Name} has a problem when {...}]
Use Case: Requisition Process flows, other approval processes.
Users need a visual way to see where an object is in its approval lifecycle—where has it been; where is it currently; how many steps to go
Users need to see detail information for steps in order to inquire/follow-up with the approver

**Describe the solution you'd like**
A clear and concise description of what you want to happen. [e.g. {Component Name} would work better if {...}]
Using elements of the timeline and process indicator controls to show approval process horizontally

- 100% width, including responsive behavior
- Ability to show statuses via the indicator point (fills, colors, icons, etc)
- Labels on process indicator points
- Datagrid formater version with tooltips (for details of the field)
- Listview version
- Form version

**Describe alternatives you've considered**
Have looked at prev. mentioned existing controls

[LMCLIENT-28994](https://jira.lawson.com/browse/LMCLIENT-28994)
[Wireframe Design](https://github.com/infor-design/enterprise/files/4629075/Process.Indicator.WIP-050720.pdf)

**Comment by tmcconechy** [comment]
@inforandy Should we loop in Aaron or make a design issue to get the team to take a look at this? From what i see we can make the changes but probably want to loop the team in to improve our process

**Comment by inforandy** [comment]
@tmcconechy yup, will flag to them and get it on their radar. 

and thanks @jamie-norman , this is good one

**Comment by tmcconechy** [comment]
Design has not been done so will move this to next sprint for now

**Comment by tmcconechy** [comment]
Linking Jira issue for design https://jira.infor.com/browse/HLPE-386

**Comment by tmcconechy** [comment]
@inforandy - This just needs design approval. Do we have a status?

Also noting some of the changes we probably need to make technically:

- change the wizard
- make steps readonly / unclickable
- ensure can have an ID on the steps
- add setting to move labels to the top
- add a container under for content
- add an example
- maybe also something with responsive behavior

**Comment by jamie-norman** [comment]
Do we still need design blessing on this? I think sales has escalated the need for this feature in Landmark, so we're going to need to keep this moving for Landmark to use when they're able. Thanks peeps!

**Comment by pwpatton** [comment]
![image](https://user-images.githubusercontent.com/4737815/99676823-98831b00-2a3e-11eb-8510-96a2b9d619f0.png)

![image](https://user-images.githubusercontent.com/4737815/99676653-670a4f80-2a3e-11eb-8e34-0105e6621b52.png)

![image](https://user-images.githubusercontent.com/4737815/99676766-87d2a500-2a3e-11eb-987f-d260161e2024.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Tested this issue using the following URL's attached below.

<img width="745" alt="URLS FOR GITHUT TICKET" src="https://user-images.githubusercontent.com/39101346/100925290-cf7e1580-34af-11eb-972f-28459915cc42.png">
