### ISSUE TITLE
SOHO-8060: [Win 10 Chrome 66] Editor Color Background Control:Unable to change background color of words that were previously changed

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#392]
1. http://470-beta-enterprise.demo.design.infor.com/components/editor/example-with-backcolor.html

2. [Win 10 Chrome 66] Editor Color Background Control:Unable to change background color of words that were previously changed

3. Steps to reproduce:
- Highlight the word "Cross-platform" then change it's color to green
- Highlight the phrase "Cross-platform, evolve" then change it's color to blue
- only the word "evolve changes to blue not  "Cross-platform, evolve" which is what i highlighted.

**Comment by brianjuan** [comment]
http://localhost:4000/components/editor/example-with-backcolor.html
Fix is working for this bug, but I encountered one regression issue that I think related to the implemented fix. When you changed the background of a word, then you select part of it together with other words and change their background, the background color of the unselected characters will be gone.
![editor_bgcolor](https://user-images.githubusercontent.com/39508864/48196911-edd7bc80-e38e-11e8-84ad-e773a1daccbb.gif)

**Comment by tmcconechy** [comment]
@ericangeles Can you see if you can find a solution?

**Comment by ericangeles** [comment]
@tmcconechy for sure! :)

**Comment by clepore** [comment]
Moving this back to "in progress" since we didn't do a QA branch/deploy yet 👍

**Comment by clepore** [comment]
@ericangeles just a reminder to PR this into branch `3.14.x` when you're ready 👍

**Comment by tmcconechy** [comment]
For the last comment this is very tricky as the selection is attached to the words. I dont think we will be able to fix that. I also dont think that it would be common to set the back ground color on two attached text sequences. So lets leave this as a known issue and conclude this issue.
