### ISSUE TITLE
Calendar: Allow background color override at Event level

### ISSUE THREAD

**Issue by fritzm-ux** [infor-design/enterprise#3923]
**Is your feature request related to a problem or use case? Please describe.**
Calendar control does not currently allow the changing of the background-colors at event level.

**Describe the solution you'd like**
Calendar control would be better if the background-colors of the events can be changed individually at the event-level.

**Describe alternatives you've considered**
N/A

**Additional context**
The override of background-color at event-level will be helpful for Infor Pathway's use case of indicating the status of events. See the sample screenshot below: _(Note: The IDS Control example is used for simplicity.)_
![image](https://user-images.githubusercontent.com/64887117/82028331-a4c79d80-96d4-11ea-8973-0aa77d6e0264.png)

The ones highlighted in Yellow are both of Event Type - _Team Event_. However, the other one is in _Red_ because of its status being **"Cancelled"**.

***
- This will be for cases that the Booking Events in our project will different statuses like "Cancelled", "Tentative", "Unavailable", "Conflicting", Confirmed", "Awaiting Response", and so on. The changing of colors will be at the individual **event-level** and **NOT** the _event-type level_. 

- Our Support QAs and customers will be **expecting colors** to indicate these statuses as previous versions of our project use colors as well for the Calendar and booking statuses.

- Furthermore, it only possible, allow the _acceptance of custom colors (custom hex, etc.)_ as well for this becuse the Support QAs and customers expect color customization.

**Comment by tmcconechy** [comment]
Yeah right now it only accepts the color names like `amethyst`, `emerald` ect. We could make it accept a color like `error`, `success`, `alert` and/or an hex. Then it would show more colors. That way you can change the color to one of those in eventTypes and then change it back. But the color alone should not be used to convey meaning so we did it a different way in the current design.

So, we do have "Success/Error" alerts in the design. But they are shown as icons with colors so maybe that's acceptable. Just put the icon name into the data like `  "icon": "icon-success-alert",`. For accessibility i suggest maybe you simply use that.

To see this...
1. go to https://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. go to Feb 2019
3. Observe:

![Screen Shot 2020-05-15 at 9 44 43 AM](https://user-images.githubusercontent.com/814283/82057124-e6365980-9690-11ea-9c5d-b85ad5bb3d67.png)

**Comment by fritzm-ux** [comment]
Hello Tim, I actually presented this alternative to the to our QAs, however they did not want the icons. So, the icon alternative will not be enough for them.

They would really be expecting colors instead - so the acceptance of hex colors would be helpful at the event level. We might just have to wait for this enhancement then and I'll tell our QAs as well.

Thank you.

**Comment by marknolaninfor** [comment]
Wouldn't it be better to use the control in the way it was designed and intended, or changing the event types. Otherwise I would find it very confussing.

There is no easy way to see that the event on the 4th is a Team event, unles you lable each event with its type, this then defeats the whole inital design of using color to show the event type.

**Comment by tmcconechy** [comment]
Yeah @marknolaninfor i think thats why the deisgn just tacks on a icon for status states. Actually i added two field icon and status. So at the moment you get

- event color
- icon for status
- text for status

One shouldnt use just a color to show a status as per https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html

But that being said i dont mind allowing hex colors other than our defined ones. But i think you will want the icon and text we already have in addition to the event color for accessibility. And i think you will have to do some work like change the event types in the menu and dynamically change the colors as the states change or something. So it would be a bit of workarounds on your end. But can allow a hex color and our alert colors.

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-beta1
https://4310-beta1-enterprise.demo.design.infor.com/components/lookup/test-paging-server-side-keyword-search.html
![image](https://user-images.githubusercontent.com/56722184/88903307-0fc15300-d286-11ea-8673-92d1b83432cb.png)
