### ISSUE TITLE
Popupmenu: Not working with headers and multiselect

### ISSUE THREAD

**Issue by DivyaParepally** [infor-design/enterprise#3926]
**Describe the bug**
When using the multiselect popup with headings and separators the checkboxes show on the wrong items.

**To Reproduce**
1. Edit popupmenu/example-selectable-multiple.html or make a new example with seperators and headings like
```
      <ul class="popupmenu is-multiselectable">
        <li><a href="#">Menu Option #1</a></li>
        <li class="is-checked"><a href="#">Sub Option #2</a></li>
        <li><a href="#">Menu Option #3</a></li>
        <li><a href="#">Menu Option #4</a></li>
        <li><a href="#">Menu Option #5</a></li>
        <li class="separator single-selectable-section"></li>
        <li class="heading">Single-Selectable Section</li>
        <li><a href="#">Menu Option #6</a></li>
        <li><a href="#">Menu Option #7</a></li>
        <li class="is-checked is-disabled"><a href="#">Menu Option #8</a></li>
        <li class="is-disabled"><a href="#">Menu Option #9</a></li>
        <li><a href="#">Menu Option #10</a></li>
      </ul>
```
2. Open the page popupmenu/example-selectable-multiple.html
4. See the issue

**Expected behavior**
Should work with separators and headings.

**Version**
- ids-enterprise: [4.28]

**Screenshots**
![Screen Shot 2020-05-15 at 11 10 33 AM](https://user-images.githubusercontent.com/814283/82065936-ba20d580-969c-11ea-92b2-7f6c51aefcbf.png)

**Platform**
 - Chrome Mac or PC is fine

**Additional context**
Mentioned in MS Teams

**Comment by tmcconechy** [comment]
@DivyaParepally I am adding better clear steps for this but in the future please fill out the issue template when making the issue https://github.com/infor-design/enterprise/issues/new/choose

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/87296524-7a118e00-c539-11ea-93e4-7b37597bad80.png)
