### ISSUE TITLE
Tree: Support for expand and collapse single node without triggering onSelected

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise#3927]
**Is your feature request related to a problem or use case? Please describe.**
I have a case when adding child nodes where in order to show the new node and give proper visual feedback to the user I want to only open the parent node and show the newly added child. To do this I have tried tree.toggleNode(parentNode), however that will trigger the onSelected event on the parent. Multiple components and cases are in different ways already connected to the onSelected event and will break the UX we are trying to achieve if fired at this time.

**Describe the solution you'd like**
I would like tree component to support "expand single Node" and "collapse single Node" that only affects the UI without triggering onSelected. With those options one would also not need to track the current state as needed with toggleNode.

From what i can tell expandAll and collapseAll functions are not triggering onSelected, so same behavior but for single node.

**Describe alternatives you've considered**
Alternatively the toggleNode could be decoupled from select functionality completely so I can call toggleNode and then call select related functionality separately in only the cases it's needed.

**Additional context**
Application: Infor PIM

**Comment by tmcconechy** [comment]
Since you are the one handling these methods. Could you do something with a flag?

```
const noTrigger = true;
const handler = onSelected(even data) {
  if (noTrigger) {
     return;
  }
}

tree.toggleNode();
noTrigger = false;
```

This seems a little specific here. Maybe a test page would help understand the need?

**Comment by Carlfjord** [comment]
Yea the onSelected trigger part of this is very specific, we did consider that flag but due to our case and the nature of the components involved something like that would believe it or not become quite complex and ugly. I'm not sure I even can explain or recreate it accurately in a test page 🤣 

So I suppose the hope here is that the part of allowing for single node expand/collapse to avoid the need for tracking states is reason enough to implement this. In that case we can ride on that wave and have a short cut to avoid adding some hacky code in our specific case. Otherwise it will probably make more sense to rework this UX scenario to avoid our issue completely.

**Comment by tmcconechy** [comment]
OK, i think it always makes sense to factor out the parts more. Maybe toggle is doing too much..
So decouping seems fine, we can do that.

But in case you need an urgent fix you might consider coming up with an other solution.

**Comment by karinthulin** [comment]
Can this issue be prioritized @tmcconechy ? We would need this for the entity type creation scenarios for PIM.

**Comment by tmcconechy** [comment]
Ok, added it to next sprint.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by hemantg05** [comment]
@deep7102, the support for expandNode() and collapseNode() API was missed as part of implementation of this enhancement request. So, after discussion with @tmcconechy, I created a separate enhancement request. https://github.com/infor-design/enterprise/issues/4707

cc @karinthulin, @Carlfjord
