### ISSUE TITLE
Tree: Removing all child nodes should change parent node icon

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise#3928]
**Describe the bug**
On tree component the folder icon will persist even if all child nodes are removed.

**To Reproduce**
I reproduced it by editing one of the examples in the public example library, perhaps there is a better way...
1. Go to https://master-enterprise.demo.design.infor.com/components/tree/test-update-node-with-children.html
2. Use dev tools to set a breakpoint in the function called when clicking "removeNode()" button.
3. Select one of the leaf nodes
4. Click "removeNode()" button
5. at the active breakpoint, in dev tools console call tree.removeNode({id: "new1"}); to also remove the second leaf node in the folder.
6. Notice icon is still folder but without children

**Expected behavior**
If the child node array is empty the node should be considered a leaf node and be updated to no longer display a folder icon.

**Version**
- ids-enterprise: v4.29.0-dev
(also see it locally on v4.28.0)

**Screenshots**
v4.29.0-dev
![image](https://user-images.githubusercontent.com/9215760/82071317-3c79bb80-96d6-11ea-92f6-08306f7cc85e.png)
v4.28.0
![image](https://user-images.githubusercontent.com/9215760/82072447-148b5780-96d8-11ea-8b81-c3bde6346674.png)

**Platform**
Infor Application/Team Name: Infor PIM
OS Version: Windows 10
Browser Name: chrome
Browser Version: Version 81.0.4044.129 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
I cant seem to follow these steps. Seems like you wnat to call removeNode again while in the debugger stopped at remove node?

The example disabled remove node but i assume you are saying remove "New Item 1" and then "New Item 2" and you expect the folder to change? If so... I dont think this is a bug as its valid to have empty folders.

I probably am not understanding

**Comment by Carlfjord** [comment]
Yes that is correct, removing all items in the folder. 
Hmm.. you are right of course, it does makes sense to support empty folders. 

But the reason I reacted to this behavior is because we have a node that looks like this:
![image](https://user-images.githubusercontent.com/9215760/82082881-14e01e80-96e9-11ea-8701-452f70cdac8c.png)
Then we add a child node to it:
![image](https://user-images.githubusercontent.com/9215760/82083092-70121100-96e9-11ea-9efe-4a5e98f50402.png)
Then we remove the child node: 
![image](https://user-images.githubusercontent.com/9215760/82083163-8a4bef00-96e9-11ea-9d92-3c74423af272.png)

So with this flow it seemed strange that it does not revert to it's original state. Perhaps allowing empty folders could be optional somehow

**Comment by tmcconechy** [comment]
Ok so i tested this and this seems to work, give it a try.

```
      tree.updateNode({
        id: 'leadership',
        text: 'Leadership',
        icon: 'icon-tree-node',
        children: []
      });
```

So basically set the children to empty and then also pass in the default icon as a name. I think this makes sense. If that works for you we can probably close this.

Updated app/views/components/tree/test-update-node-with-children.html
<details>
<summary>Updated app/views/components/tree/test-update-node-with-children.html</summary>

whatever

</details>

**Comment by tmcconechy** [comment]
I think my comment should help you my example is now live https://master-enterprise.demo.design.infor.com/components/tree/test-update-node-with-children

So closing
