### ISSUE TITLE
Mask: de-DE.js culture currency issue

### ISSUE THREAD

**Issue by nbcp** [infor-design/enterprise#3933]
**Describe the bug**
Cannot input numbers in currency field when using german locale. Something prevents it and only shows dots

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/input/example-index?theme=uplift&variant=light&locale=de-DE
2. Scroll down to 'Currency Field' and try to input some number
3. See dots and no numbers

**Expected behavior**
Should be able to input some numbers

**Version**

- ids-enterprise: v4.28.0

**Screenshots**

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
Issue does not happen to other common locale like en-US, en-GB, etc.

**Comment by tmcconechy** [comment]
Has happened for a while. Seems like currency masks on any language with decimal and group reversed from English. Lets see if we can fit this in next sprint

**Comment by jbrcna** [comment]
**QA Passed**
v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/input/example-index?theme=uplift&variant=light&locale=de-DE
https://master-enterprise.demo.design.infor.com/components/mask/test-number-mask-gauntlet?locale=de-DE
![image](https://user-images.githubusercontent.com/56722184/85997965-cab6c080-ba3c-11ea-8c1d-7f07876a80ce.png)

![image](https://user-images.githubusercontent.com/56722184/85998569-8d9efe00-ba3d-11ea-9f44-cbc6a8ebdc22.png)
