### ISSUE TITLE
Tabs: Focus is not aligned on Tabs with icon

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#3935]
**Describe the bug**
Tabs: Focus is not aligned on Tabs with icon

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tabs/example-enable-disable-individual-tabs-with-keydown.html
2. In the Last tab, click tab show the  icon next to the tab name
3. Click tab until it focuses on the Last tab.

**Expected behavior**

**Version**
IDS 4.290 - master

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/82204307-3cc4c180-9937-11ea-92eb-95d6e517fa5e.png)

**Platform**
All browser, OS and device

**Additional context**
N/a

**Comment by EdwardCoyle** [comment]
This keeps on getting shifted somehow... definitely a regression from [v4.28.0](https://4280-enterprise.demo.design.infor.com/components/tabs/example-enable-disable-individual-tabs-with-keydown.html).  I'll pick this one up next.

<img width="623" alt="Screen Shot 2020-05-18 at 9 46 58 AM" src="https://user-images.githubusercontent.com/3249601/82220427-9c49af80-98ec-11ea-86f5-6d309611e138.png">

**Comment by tmcconechy** [comment]
We have a lot of couple similar issues around this:
https://github.com/infor-design/enterprise/issues/2929
https://github.com/infor-design/enterprise/issues/3024

I thought there might be a duplicate but those are a bit different

**Comment by janahintal** [comment]
The issue still exist in https://4290-beta0-enterprise.demo.design.infor.com/components/tabs/example-enable-disable-individual-tabs-with-keydown.html?theme=uplift&variant=light&colors=0066D4 borders are too close from the icon.
![image](https://user-images.githubusercontent.com/45757016/82894826-cd2d8280-9f85-11ea-927f-ccbaf3dcea0a.png)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/83404242-debad280-a43c-11ea-9ada-15d083d89553.png)
