### ISSUE TITLE
Tree: Error expanding on IE11

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3936]
**Describe the bug**
The tree component is erroring on expand in IE 11.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tree/example-select-multiple.html
2. Click on any folder to expand
3. See error

**Expected behavior**
No error.

**Version**
- ids-enterprise: [e.g. v4.29-dev]

**Platform**
 - IE 11

**Additional context**
Email recieved.

**Comment by janahintal** [comment]
Hi @tmcconechy , the selection & collapsing is now working as expected. However, the  File icon changed to Circle icon upon switching to Uplift & Its not disabled. 

https://master-enterprise.demo.design.infor.com/components/tree/example-select-multiple.html?theme=uplift&variant=light&colors=0066D4

![image](https://user-images.githubusercontent.com/45757016/82665317-26d03d00-9c66-11ea-9d1c-fa0fff8be5eb.png)

**Comment by tmcconechy** [comment]
This is the design of the icon . But I agree it does seem weird. Closing this and made a request to change that over here https://github.com/infor-design/enterprise/issues/3613#issuecomment-632680623

**Comment by tmcconechy** [comment]
But i do see another more important issue in uplift with colors now. Im fixing.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by kevinwhitedesign** [comment]
https://jira.infor.com/browse/HLPE-414 For this issue I think we should just swap the circle with the regular document icon.. I think it's called "Standard" on your end

**Comment by tmcconechy** [comment]
Sure that would work. I need it changed in the sketch file if you dont mind tho?

**Comment by kevinwhitedesign** [comment]
@tmcconechy is it possible to map to the standard doc icon for this?

**Comment by tmcconechy** [comment]
No, the icon has a specific name it needs to use the icon by name that was there
