### ISSUE TITLE
Datagrid: cellNavigation setting is not working

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3937]
**Describe the bug**
Testing another issue i found that `cellNavigation` is no longer working

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-singleselect.html
2. Click any row to select it
3. Use left arrow and right arrow
4. Notice the cells are focused.

**Expected behavior**
Cells should not be navigable with this setting on.

**Version**
- ids-enterprise: [e.g. v4.29.0]

**Screenshots**
When using it in lookup it has a wierd effect deselecting the rows.

![Screen Shot 2020-05-18 at 10 42 09 AM](https://user-images.githubusercontent.com/814283/82226234-3eb96100-98f4-11ea-8e21-d3c22da91a33.png)

**Platform**
 - Chrome

**Additional context**
This was working in previous versions https://4190-enterprise.demo.design.infor.com/components/datagrid/example-singleselect.html

**Comment by janahintal** [comment]
QA Failed. Unable to test in IE as the grid didn't load. 
https://master-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection.html
![image](https://user-images.githubusercontent.com/45757016/84134215-d5ec8100-aa7a-11ea-95be-72de6b08d3a6.png)
