### ISSUE TITLE
SOHO-8024: feat(soho-datagrid): An event which is triggered on any changes in soho data grid

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#394]
*Summary*
- An event emitter which is triggered by any changes in data grid (cell value changes, row add, row delete etc.). 
- It would be nice also that the event has some details about which action triggers the changes.

*Motivation*
The use case I have is I’m integrating an Angular application into ION Desk application. There is a navigating-away mechanism that it will check whether the user makes some changes and hasn’t saved those yet. Then a popup will appear to block the user from navigating away the page.
 
Normally if inside the page there is a form, I can react to the dirty status of the form. However now I encounter a case that the page is using data grid so I don’t have a generic event to react to the changes the user makes on data grid. So I have to create a function in TypeScript file which will be used by 3 events: cellChange, rowAdd and rowRemove. 
 
It would be nice if there is only one extra event (maybe name dataGridDataChange) which combines all those above events. It’s more convenient.

**Comment by tmcconechy** [comment]
Decided to descope this. We feel that each of the 3 events are different. And all you need to do is watch all three and call the same function on the typescript side. So not worth a change
