### ISSUE TITLE
Datagrid: Add a new function to refresh a single column

### ISSUE THREAD

**Issue by rvaja-infor** [infor-design/enterprise#3941]
**Is your feature request related to a problem or use case? Please describe.**
Infor SunSystems has a front-end UI driven by the business logic. This means it is quite chatty, and changes in a grid may cause multiple events to come from the server to enable/disable columns. These events are pushed and may arrive in batches, and processed. Currently we update the whole column model for the entire grid, which in turn re-renders the whole grid. This can be quite expensive in an application which is quite chatty with its server.

**Describe the solution you'd like**
It would be great if a function was available that allowed a single column to be refreshed instead of re-rendering the whole grid.
`refreshColumn(columnNumber)`

**Describe alternatives you've considered**
Currently we update the whole column model for the entire grid, which in turn re-renders the whole grid. This can be quite expensive in n application which is quite chatty with its server.

**Additional context**
Application worked on is Infor SunSystems.

**Comment by tmcconechy** [comment]
As discussed possibly add `refreshColumns` and `refreshCell` (similar to `updateCell` but no value).

Rework things to avoid redudency and keep it DRY

**Comment by janahintal** [comment]
QA Passed. Working as expected in https://main-enterprise.demo.design.infor.com/components/datagrid/test-update-column.html?theme=new&mode=dark&colors=0066D4. Thank you!
