### ISSUE TITLE
SOHO-8018: [All Browsers] Data Grid Group Headers Control: When moving columns the group header name disappear

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#395]
1. http://localhost:4000/components/datagrid/example-grouped-headers.html

2. [All Browsers] Data Grid Group Headers Control: When moving columns the group header name disappear 

3. Steps to reproduce:
- Select any column from "Column Group One" and move it to "Column Group Two" 
- Once the move is done the title header "Column Group Two" disappears
- Please see screen shot attached.

**Comment by tmcconechy** [comment]
Closing this as a dup of https://github.com/infor-design/enterprise/issues/374
