### ISSUE TITLE
Lookup: Validation rule isn't working as expected with non editable (select only) lookups

### ISSUE THREAD

**Issue by gauravugale** [infor-design/enterprise#3950]
**Describe the bug**
When set [editable]="false" to lookup control, Following issues occurred. 
- Required  (validation) message remained on page after selecting details.
- After required validation event gets fired, control not highlighted in red color only shows        "Required” message.

**To Reproduce**
- Do the changes as described in additional context
- Run the project
- Browse lookup page
-  - Required  (validation) message remained on page after selecting details.
    - After required validation event gets fired, control not highlighted in red color only shows        
    "Required” message.

**Expected behavior**
- Validation message invisible on page after selecting details.
- validation event gets fired, control will highlighted in red color and shows        
    "Required” message

**To Reproduce (much simpler version**
- change http://localhost:4000/components/lookup/example-editable-strict so that required validation is shown
- try and tab out -> no validation works when editable: false

**Version**
- ids-enterprise-ng: 5.0.0

**Screenshots**
![1](https://user-images.githubusercontent.com/50131562/56944273-6b130b80-6b40-11e9-8a26-a9b340669186.JPG)
![2](https://user-images.githubusercontent.com/50131562/56944286-723a1980-6b40-11e9-87bf-f6f4a94b8612.JPG)

**Platform**
- OS Version: Windows 10
- Browser Name: chrome, IE, safari
- Browser Version: Version 72.0.3626.109 (Official Build) (64-bit)

**Additional context**
- Put below code in lookup.demo.html file
```
<form [formGroup]="frmGrp">
				<button soho-button id="save" (click)="save()" title="save">save</button>
				<input soho-lookup multiselect 
					name="ookup"
					id="lookup" 
					class="lookup" 	     
					[columns]="lookupColumns" 
					[(ngModel)]="selectedIds"
					[toolbar]="{results: false, keywordFilter: false, showFilterRow: true, filterRow: true, rowHeight: false }" 
					[dataset]="data_product"
					field="Name" 
					type="text" 
					[editable]="false" 
					formControlName="selectedIds" 
					data-validate="required"
				asobject>
			</form>`
```
- Put below code in lookup.demo.ts file

```
  import { Component, ViewChildren, QueryList } from '@angular/core';			  
import { FormGroup, Validators, FormBuilder } from '@angular/forms';
import { SohoInputValidateDirective } from 'dist/ids-enterprise-ng/';

@Component({
  selector: 'app-lookup-demo',
  templateUrl: './lookup.demo.html',
})
export class LookupDemoComponent {
frmGrp: FormGroup;		
selectedIds: any;	  
@ViewChildren(SohoInputValidateDirective)  validateDirectives:  QueryList<SohoInputValidateDirective>;
					 
constructor( 
	private formBuilder:  FormBuilder
) 	{
		this.CreateFormGroup();
	}

  
  CreateFormGroup()  {
    this.frmGrp= this.formBuilder.group({      
      selectedIds: [this.selectedIds, [Validators.required]]
    });
  }

 save() {
  if  (!this.frmGrp.valid) {
      this.validateDirectives.forEach((item)  =>  {
        item.validate(event);
      });
      return;
    }
 }
}
```

**Comment by tmcconechy** [comment]
Pushed this fix to master on error (keep doing this). For QA use the following steps

1. go to http://localhost:4000/components/lookup/example-editable-strict.html
2. tab out of the field without entering a value -> error should show
3. select a value with the lookup -> value should go away

**Comment by jbrcna** [comment]
**QA Passed** with observation
this is now working as expected. The error validation can now be triggered and removed when populated
v4.29.0-dev
https://master-enterprise.demo.design.infor.com/components/lookup/example-editable-strict.html

_Observation_
selected value displays `Product Name`instead of `Product Id`. the value selected is `2142201` and it indeed displays the correct value in the textbox after selection. However, when you reopen the lookup it will show two different value selected with the same `Product Name`
![image](https://user-images.githubusercontent.com/56722184/82654157-e1564480-9c52-11ea-8d56-796e18711679.png)
