### ISSUE TITLE
Buttonset: Make the api accessible on CAP same as Modal and add Docs

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3951]
**Is your feature request related to a problem or use case? Please describe.**
We are unsure if the new buttonset API is wired for CAP so it probably will need to be added to CAP and a test added.

**Describe the solution you'd like**
- Show an example of CAP and a way you can disabled buttons from logic within the CAP dialog.
- Should show this in angular and EP.
- Add docs to show the buttonSet API in general
- Add docs to show the buttonSet API on Modal (maybe explain how to disable a button as its common)
- Add docs to show the buttonSet API on CAP (maybe explain how to disable a button as its common)

**Describe alternatives you've considered**
N/A - Leaving it go and see if you can hit the underlying modal somehow.

**Additional context**
https://github.com/infor-design/enterprise-ng/pull/821

**Comment by jbrcna** [comment]
**QA Passed**
v.4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-disable-button.html
![image](https://user-images.githubusercontent.com/56722184/88519558-e48bf900-d024-11ea-9160-2aa7644300ff.png)
