### ISSUE TITLE
Drag and drop list in a table/grid

### ISSUE THREAD

**Issue by aleste37** [infor-design/enterprise#3953]
**Describe the Issue**
I implemented an M3 H5 SDK v1/odin/AngularJS  a few years ago that uses https://www.npmjs.com/package/ng-draggable  .  I used it to have a grid, where a cell with a stock value can be dragged vertically across rows of warehouses. It will not allow dragging the cell horizontally to other columns of different (shoe) stock size.

Is there an IDS framework that does something similar in a ui-grid/data-grid?  
I found https://design.infor.com/code/ids-enterprise/latest/drag, but this seems to be for non-grid cases.

**Comment by tmcconechy** [comment]
Yes the [drag](https://design.infor.com/code/ids-enterprise/latest/drag) component is our internal drag and drop logic for IDS. You can try to use it for your case but im not 100% sure i understand what you want to do.

It does work on grid and is used in several places that might be related:

- [Column Reorder](https://latest-enterprise.demo.design.infor.com/components/datagrid/example-reorder.html)
- [Row Reorder](https://latest-enterprise.demo.design.infor.com/components/datagrid/example-row-reorder.html
)
-[List Builder](https://latest-enterprise.demo.design.infor.com/components/listbuilder/example-index.html)
- [Swap List](https://latest-enterprise.demo.design.infor.com/components/swaplist/example-index.html)

**Comment by tmcconechy** [comment]
Closing this issue as an answered question

**Comment by aleste37** [comment]
Thanks! The Row is the closest. If that can be restricted to just dragging a particular cell, rather than a whole row -- it'll match what we need.
