### ISSUE TITLE
SOHO-8014: [All Browsers] Data Grid Paging Server Side Control: Filters not working correctly

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#396]
1. http://localhost:4000/components/datagrid/example-paging.html

2. [All Browsers] Data Grid Paging Sever Side Control: Filters not working correctly

3. Steps to reproduce: 
- For Product Name enter  the number "0" and click on the enter key
- the return value is "No Data Available" When it should return "Compressor 0"

**Comment by janahintal** [comment]
QA Passed. Moving to Done. 
Tested in: https://4140-beta0-enterprise.demo.design.infor.com/components/datagrid/example-paging.html

Found a related issue and created a separate ticket for it: 
https://github.com/infor-design/enterprise/issues/1405

**Comment by Mincol** [comment]
I believe this is still issue.

1.  https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L666 this sets restoreFilterClientSide = true;
2. https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L1971 prevents from calling resetPager https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L1985 which in turn will not call https://github.com/infor-design/enterprise/blob/master/src/components/pager/pager.js#L1007

So server side filtering work only every other modification of filters.

**Comment by tmcconechy** [comment]
Following these steps it seems to work on this issue

https://master-enterprise.demo.design.infor.com/components/datagrid/example-paging.html
- filter on producet name : 0
- now showing correct results.

Im not sure about those lines your talking about. Perhaps try to make a new issue with steps on the latest code on master.
