### ISSUE TITLE
Date Format with no separator not supported in masking

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise#3963]
**Describe the bug**
I want to use format yyyyMMdd in input-masking but I can not write anything in the textbox with this format.

**To Reproduce**
1. Have a textbox
2. Add a mask such as yyyyMMdd
3. Try to write anything in the textbox

**Expected behavior**
The input should follow the mask

**Version**
4.27.4

**Platform**
 - Infor App Builder

**Comment by jbrcna** [comment]
**QA Passed** with observation
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/mask/test-dates-no-separators.html
![image](https://user-images.githubusercontent.com/56722184/88148046-9f388780-cc30-11ea-911e-9cf75e9bc39b.png)
Validations seems fine
![image](https://user-images.githubusercontent.com/56722184/88148070-a65f9580-cc30-11ea-9e40-c1b540a42038.png)

_**Observation**_
populate the fields then open the picker
Device: Android (Samsung Galaxy s20)
![image](https://user-images.githubusercontent.com/56722184/88149787-20911980-cc33-11ea-9d5f-f04bdb183c77.png)
