### ISSUE TITLE
Toolbar Flex: Some icons on flex toolbar not appearing on iOS12

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#3964]
**Describe the bug**
Some icons are missing on flex toolbars in iOS12 devices.

**To Reproduce**
1. Open browserstack and start a session with a iOS12 device (i.e. iPhone XS)
2. Navigate to https://master-enterprise.demo.design.infor.com/components/toolbar-flex/example-index.html
3. See error

**Expected behavior**
All icons should be seen

**Version**

- ids-enterprise: v4.30.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/22107636/82934016-75285900-9f50-11ea-90d8-15fed6cca6c9.png)

**Platform**
 - OS Version: iOS12
 - Happening on both safari and chrome. May be happening on inforGo as well.

**Comment by tmcconechy** [comment]
IOS Has a bug. This will work only in IOS 12.1 and up. So if on IOS 12 make sure to use IOS 12.1
BTW you cant test that in browser stack as they only give you the base version

**Comment by Sovia** [comment]
This is being seen in landmark, which is on dev 4.28 . So may need a patch back.

**Comment by tmcconechy** [comment]
I do not think there is any fix for this. Other than to update the device to 12.1 or later. Which seems reasonable. If we pull this out then IVY NG 9 will not work.

**Comment by tmcconechy** [comment]
Closing this as it cant really be fixed
