### ISSUE TITLE
SOHO-7997: Support Newer Chinese Locales

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#397]
Chinese locales are now known as zh-Hans and zh-Hant

zh-Hant -> maps to zh-TW
zh-Hans -> maps to zh-CN

Just need to copy the existing files and change the locales and add tests.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html?locale=zh-Hans
http://master-enterprise.demo.design.infor.com/components/about/example-index.html?locale=zh-Hant
Passed QA testing, tested on About and Datagrid components on all browsers.
