### ISSUE TITLE
LookUp: Filter Row resizes when you run filter with the filters hidden

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3971]
**Describe the bug**

**To Reproduce**
1. Go to https://4290-beta0-enterprise.demo.design.infor.com/components/lookup/example-filter-row.html
2. Click on `...` then select `Show Filter Row` to hide filters
3.  Click on `...` then select Run Filter
4. Notice that the modal resizes
5. Show filters again to see the error in fields

**Expected behavior**
should not resize

**Version**
- ids-enterprise: [v4.29.0-beta0]

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/83009508-72f5f580-a049-11ea-9630-c09f8f004b57.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Not really sure what to do here. Maybe run filter should be disabled if its closed. Minor issue anyways

**Comment by tmcconechy** [comment]
Descoping for now
