### ISSUE TITLE
Translation - GENERIC ISSUE: Wrong language capitalization in GRC "Application Instance / Data Sources (XX Results)" windows.

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#3974]
Translation - GENERIC ISSUE: Wrong language capitalization in GRC "Application Instance / Data Sources (XX Results)" windows.

The translated GRC versions are incorrect. I guess glued strings are used.

For example in English, R is in upper case i.e. (1 Result) but in most languages, the first letter should be in lower case e.g. (1 résultat)

**Comment by cpinatel7** [comment]
Screenshot (Defect.png) attached

**Comment by cpinatel7** [comment]
![Defect](https://user-images.githubusercontent.com/66057969/83119355-e6dae100-a0cf-11ea-8fba-5f7cd9ace8cb.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.  I used url: https://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html to conduct testing on this ticket.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
