### ISSUE TITLE
Translation - Missing 'Filter' translation for German (Soho filter used in GRC)

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#3975]
Translation - Missing 'Filter' translation for German (Soho filter used in GRC)

Screenshot attached
![Filter](https://user-images.githubusercontent.com/66057969/83119075-8ba8ee80-a0cf-11ea-9f6d-6cd337b97361.png)

**Comment by tmcconechy** [comment]
I checked this and the german translation is presently Filter google translate agrees but what do we think it should be:

https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/de-DE.js#L180

1. What should it be?
2. Can you change it in the translation system too?

**Comment by cpinatel7** [comment]
It should be Filtern.

Screenshot attached: Filtern_In_GRC.png
![Filtern_In_GRC](https://user-images.githubusercontent.com/66057969/83274604-4b7c6580-a1ce-11ea-8679-b52f8379f89d.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Use url: https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?locale=de-DE for testing.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
