### ISSUE TITLE
Datagrid: Keyword search is not working with server side paging

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise#3977]
**Describe the bug**
You can't have a source  (server side paging) and keyword search at the same time.
If you do and enable search-bar the results are not highlighted probably due to this line https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L6703

**To Reproduce**
1. Add a source to a datagrid (server side paging)
2. Enable keyword search
3. Add a toolbar with a search field
4. search for something in the search field 

Or modify https://master-enterprise.demo.design.infor.com/components/datagrid/example-keyword-search to show server side paging

**Expected behavior**
The result string should be highlighted in the grid when using keyword search and server side paging

**Version**
4.27.4

**Platform**
 - Infor App Builder

**Comment by kels0** [comment]
Do you have **team: App Builder** or **team: Mongoose**? App Builder is not part of Homepages anymore.

**Comment by tmcconechy** [comment]
@kels0 - no problem - i made a new label and im changing your issues.

**Comment by jbrcna** [comment]
**QA Passed**
though, The result string was not highlighted in the grid
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-keyword-search-serverside.html
![image](https://user-images.githubusercontent.com/56722184/87772424-4e9de480-c854-11ea-81df-52541ced761f.png)

**Comment by tmcconechy** [comment]
This isnt entirely fixed but started a new issue on https://github.com/infor-design/enterprise/issues/4488 to remove some noise.
