### ISSUE TITLE
Icons: Fix update-preview and tree-node icons in uplift mode

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#3978]
**Is your feature request related to a problem or use case? Please describe.**
Created a new issue off https://github.com/infor-design/enterprise/issues/3613 as there are two (maybe more) icons that need to be fixed still.

1. icon-tree-node

I found an case where the icon has lost meaning. This is in the tree. We used to have a "#icon-tree-node" icon that looked like a base level of a UI tree. Now its just a circle that looks like a radio button that you can select. This is confusing.

Compare:
https://master-enterprise.demo.design.infor.com/components/tree/example-select-multiple.html?theme=uplift&variant=light&colors=0066D4

With
https://master-enterprise.demo.design.infor.com/components/tree/example-select-multiple.html

2. update-preview
This icon no longer looks like a print preview and perhaps we need to make aprint preview

**Describe alternatives you've considered**
NA

**Additional context**
https://github.com/infor-design/enterprise/issues/3613

**Comment by tmcconechy** [comment]
cc @inforandy

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://4300-beta0-enterprise.demo.design.infor.com/components/icons/example-index.html?theme=uplift&variant=light&colors=0066D4 & https://4300-beta0-enterprise.demo.design.infor.com/components/tree/example-select-multiple.html?theme=uplift&variant=light&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/86118558-8e9a6300-bb03-11ea-93cf-b74e37b208f9.png)
