### ISSUE TITLE
SOHO-7995: Add a beforeOpen on autocomplete

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#398]
I got a use case scenario like this:

_I would like to get the AutoComplete functionality ONLY if I start my search with “{“._
_If I use anything but that I want the input field to behave just like a normal input field._

If I had a way before the popup opens to determine if this is a right string or not would be the best case, such as a *beforeOpen.*

Case is used in App Builder.

**Comment by brianjuan** [comment]
http://localhost:4000/components/autocomplete/test-beforeopen-event.html
http://master-enterprise.demo.design.infor.com/components/autocomplete/test-beforeopen-event.html
Passed QA testing on all browsers, moving to Done.
