### ISSUE TITLE
Datagrid: Double entry of alphanumeric/printable characters required with Dropdown lists and Date Controls

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#3980]
Users have to press alphanumeric/printable keys twice to get the dropdown or date control to take notice. Using your sample grid:-

https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-editable.html

If arrow right until Action cell is highlighted
Pressing ‘s’ does not list ‘Shipped’ and ‘Processing’ options until you press it a second time.

If you mouse click on the same cell, the dropdown list opens up automatically, so then pressing an ‘s’ will immediately filter matches.
Similarly with the date control, if you arrow to it, you need to press t twice for the control to put in today's date. It would be nice if those controls would recognise printable characters as such, not only placing the control in edit mode, but then applying the character also. 
 
Text controls already work like this, so as soon as you move to them with arrow keys anything you type will immediately get put in the textbox.

**Comment by AlexMarchant-Infor** [comment]
Hi @tmcconechy - any chance or a process to follow to promote this to a nearer or existing release (even better) of IDS?  We have a project specifically to improve grid usability that needs to go to customers and this is one of the key issues/frustrations that has been reported externally on multiple times.  
Thanks,
Alex

**Comment by tmcconechy** [comment]
Hi @AlexMarchant-Infor i did put this in the next sprint which is probably the fastest we can get to this. But can try to move this up if we can manage this sprint.

**Comment by AlexMarchant-Infor** [comment]
Yeah, cheers.  I saw 2.31 and knew we just upgraded to 2.28 so it felt a long way off.  Appreciate we've only just raised it.  Taken a while to narrow it down.

**Comment by tmcconechy** [comment]
yeah 4.29 is in RC, 4.30 is already in progress so actually 4.31 is next

**Comment by AlexMarchant-Infor** [comment]
OK. - thanks,.We are targetting our July release around resolving this issue (and a few others) to improve our grids.

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
