### ISSUE TITLE
Mask is not working in IE11

### ISSUE THREAD

**Issue by byannalam** [infor-design/enterprise#3983]
**Describe the bug**
_Currently observed in IE11 only._
When I go to enter a number in the 'Millions: 1,000,000' field of the 'test mask gauntlet' page, two problems can be clearly observed:

- the comma-separated format is not being applied as the user types
- the input is not being restricted to 7 digits as it is currently doing in Google Chrome. I was able to enter my attempted value of 12345678900000000 in it entirety.

**To Reproduce**
1. In IE11, navigate to : https://design.infor.com/code/ids-enterprise/latest/demo/components/mask/test-number-mask-gauntlet?theme=uplift&variant=light
2. In the 'Millions: 1,000,000' field enter '1234567'. Note that there is no comma-separation happening as soon as you enter the 4 of that number.
3. Enter 890. It currently allows you to do this.

**Expected behavior**
It is expected the the behaviour of the Mask will be identical across all browsers.

**Version**

- sohoxi: 4.28.1

**Screenshots**
The issue in IE11
![image](https://user-images.githubusercontent.com/4402939/83208906-47365500-a19a-11ea-917f-aad5aaf1d62b.png)

The same field in Google Chrome, behaving perfectly:
![image](https://user-images.githubusercontent.com/4402939/83209135-e4918900-a19a-11ea-94c2-9f2910db622d.png)

Current SoHo version:
![image](https://user-images.githubusercontent.com/4402939/83209544-fcb5d800-a19b-11ea-9bc4-ad8a267b5670.png)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - OS Version: Windows 10 Enterprise
 - Browser Name: Internet Explorer
 - Browser Version: Internet Explorer 11

**Additional context**
Cross-checked issue against Google Chrome Version 83.0.4103.61.

**Comment by tmcconechy** [comment]
This is not working in IE 11 as there is a fallback (graceful degradation). IE 11 does not support Intl.formatNumber.formatParts and this seems to be giving an error.

Will keep this open for now but due to dropping IE 11 support in October this possibly won't get fixed. See https://github.com/infor-design/enterprise/issues/3756

**Comment by tmcconechy** [comment]
Descoping this issue due to dropping IE 11 support.
