### ISSUE TITLE
Popupmenu: shortcut text misaligned in responsive view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3984]
**Describe the bug**
The shortcut text was misaligned in responsive view

**To Reproduce**
1. Go to https://4290-beta0-enterprise.demo.design.infor.com/components/popupmenu/example-shortcut-text.html?theme=soho&variant=light&colors=2578a9
2. Switch to responsive view or at least make your browser smaller until a scroll bar is present in the popup menu
3. Click the second button `Icon Menu with shortcut text`

**Expected behavior**
shortcut text should be properly aligned

**Version**
- ids-enterprise: [v4.29.0-beta0]

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/83245029-c8114300-a1d2-11ea-99bf-f2a65b012f77.png)

**Platform**
Safari

**Additional context**

**Comment by jbrcna** [comment]
**QA Failed**
will retest once the beta is available. thanks
v4.32.0-dev
https://master-enterprise.demo.design.infor.com/components/popupmenu/example-shortcut-text.html
`Chrome Vibrant`
![image](https://user-images.githubusercontent.com/56722184/90010636-bff57980-dcd2-11ea-84c7-ac5275cdcb07.png)

`Mac/Safari `
Failed in both Themes 
![image](https://user-images.githubusercontent.com/56722184/90010727-f206db80-dcd2-11ea-9de0-0b90c519095d.png)

**Comment by tmcconechy** [comment]
cc @jmacaluso711

**Comment by jbrcna** [comment]
**QA Failed**
v4.32.0-dev
https://master-enterprise.demo.design.infor.com/components/popupmenu/example-shortcut-text.html?theme=uplift&variant=light&colors=0066D4
`iPhone 5/SE Chrome`
![image](https://user-images.githubusercontent.com/56722184/91557799-bb35f400-e967-11ea-9f30-47d7049a4c37.png)

`Mac/Safari `
![image](https://user-images.githubusercontent.com/56722184/91558539-246a3700-e969-11ea-8b0d-23239e348f0a.png)

`iPhone 5/SE Mac/Safari`
![image](https://user-images.githubusercontent.com/56722184/91847310-fd737400-ec8c-11ea-9124-3b23ff51bd99.png)

**Comment by tmcconechy** [comment]
Descoping this further - we dont really support iphones that old. If it works in R -1 this is good enough but that being said it looks ok.

![Screen Shot 2020-09-01 at 9 40 46 AM](https://user-images.githubusercontent.com/814283/91858477-3f71cb00-ec37-11ea-8f95-6dc4271ee396.png)

We have spend enough time on this minor issue so moving to done - have no more bandwidth for this issue
