### ISSUE TITLE
Switch Component: Switch component showing check mark boxes for Win 10 IE 11

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#3992]
**Describe the bug**
Switch Component: Switch component showing check mark boxes for Win 10 IE 11

**To Reproduce**
1. Go to url: https://4280-rc0-enterprise.demo.design.infor.com/
2. Scroll down to Swtich section of the sink page
4. See error here is that you see check mark boxes each time you select a switch or turn swtich on or off. Please see screen shot attached. 

**Expected behavior**
Check mark boxes should not be appearing for the Swtich component.

**Version**

- ids-enterprise: [v4.28.0]

**Screenshots**
<img width="1323" alt="Switch Error on Sink Page" src="https://user-images.githubusercontent.com/39101346/83444973-3267f480-a41a-11ea-9631-b5bedf0b2154.png">

**Platform**
 - OS Version: [e.g. Windows 10 ]
 - Browser Name: [e.g. IE 11

**Additional context**
None

**Comment by tmcconechy** [comment]
We fixed this issue in 4.29 already https://master-enterprise.demo.design.infor.com/components/switch/example-index.html still working on the new URl for 4.29
