### ISSUE TITLE
Compact layout improvements on datagrid

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#3995]
**Is your feature request related to a problem or use case? Please describe.**
Compact layout on datagrid needs better column sizing so more columns are visible without scrolling horizontally. Another improvement area is to allow for font size options, naturally reducing the font size will result in allowing more content to be visible.

**Describe the solution you'd like**
Better margin for columns and font size setting.

**Describe alternatives you've considered**
No alternatives

**Additional context**
Infor Landmark

**Comment by tmcconechy** [comment]
This has already been raised here https://github.com/infor-design/enterprise/issues/3755
