### ISSUE TITLE
Datepicker: Button color issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#3997]
**Describe the bug**

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datepicker/example-custom-format.html
2. Click on to any date picker
3. See error

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/83510227-3de11b80-a4ff-11ea-9eb5-4b97acf25ef8.png)

**Version**
- ids-enterprise: [v4.29.0-rc0] 

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/83509742-80562880-a4fe-11ea-9a56-42e83eec05f0.png)

**Platform**
Chrome
Firefox
Edge

**Additional context**
Both themes were affected

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
