### ISSUE TITLE
SOHO-7979: Support tooltips for text/icons on mobile with no associated actions

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#400]
Need a way to show tooltips on ellipsis text or icons that have more info displayed in a tooltip. These would not be be buttons they would be alerts. So we can use a tab action.\

Also some tooltips may be needed on non-standard icons. Would work as
- long press to open? or tap?
- tooltip you can tap to do the action
- tooltip you can tap link to cancel?

**Comment by theakatz** [comment]
depends on #245

**Comment by EdwardCoyle** [comment]
Adding screenshots from the original JIRA ticket for context:

![soho-7979-screenshot-02](https://user-images.githubusercontent.com/3249601/43606240-c71c3cce-9668-11e8-8419-5029349b5647.png)  ![soho-7979-screenshot-01](https://user-images.githubusercontent.com/3249601/43606245-c8dc2de4-9668-11e8-8d7c-b12ec5a91d9c.png)

**Comment by EdwardCoyle** [comment]
> These would not be be buttons they would be alerts. So we can use a tab action.

@krishollenbeck, can you elaborate a bit?

**Comment by EdwardCoyle** [comment]
Pushed some work on this to https://github.com/infor-design/enterprise/tree/400-tooltips-on-icons

**Comment by krishollenbeck** [comment]
@EdwardCoyle Yes for alerts and context menus

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. This ticket was testing using BDD QA story attached.
[story_github#400.docx](https://github.com/infor-design/enterprise/files/2279302/story_github.400.docx)
