### ISSUE TITLE
Datepicker: +/- hotkeys used to increment/decrement date no longer supported/works in 4.X (Used to work in 3.X)

### ISSUE THREAD

**Issue by kaeleding** [infor-design/enterprise#4001]
**Describe the bug**
Pressing +/- hotkeys on the Date Field in 3.X used to increment/decrement the date. Now it no longer works in 4.X. Seems like from the documentation and source code that its left out (not sure if intentionally or not though)

**To Reproduce**
1. Go to a Date Field
2. Click on the calendar icon to open the calendar
3. Click on any desired date (or press T)
4. Press +/-
5. Nothing happens

**Expected behavior**
Date value should increment/decrement by one day.

**Version**
- ids-enterprise: [v4.28.0]

**Screenshots**
Pressing +/- hotkey here should increment/decrement the date:
![chrome_2020-06-03_11-09-39](https://user-images.githubusercontent.com/18295372/83591532-bc36cf80-a58a-11ea-9eb9-0347240f8767.png)

No mention of +/- hotkey functionality in the Datepicker documentation:
![chrome_2020-06-03_09-44-22](https://user-images.githubusercontent.com/18295372/83591557-c9ec5500-a58a-11ea-9ca7-e395160527f4.png)

**Platform**
- Infor Application/Team Name: [Lawson Ming.le]
- All browsers

**Additional context**
3.X Datepicker source code had support for +/- hotkey

**Comment by tmcconechy** [comment]
We can add + and - safely i think. We were following a set of accessible standards not necessarily exactly what was in 3.0 but see no reason why we cant include these as well.

**Comment by kaeleding** [comment]
@tmcconechy thanks! Will it be safe to assume it'll be out by the next release? Or is it different for enhancements?

**Comment by tmcconechy** [comment]
We didnt schedule this. But if you find it "urgent" we can slot it in maybe for 2 releases from now?

**Comment by kaeleding** [comment]
Sure, that sounds perfect. Thanks!

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html
![Large GIF (800x584)](https://user-images.githubusercontent.com/56722184/87289811-b50ec400-c52f-11ea-9894-aca79037503a.gif)
