### ISSUE TITLE
Datagrid: validateRow foes not work on the first row

### ISSUE THREAD

**Issue by kenneth-acejo** [infor-design/enterprise#4002]
Does not display error when you programmatically call validateRow on first row (row index: 0).

<img width="538" alt="Capture" src="https://user-images.githubusercontent.com/17284784/83603836-b13e6800-a5a7-11ea-928f-971660d9ceeb.PNG">

**Comment by tmcconechy** [comment]
@kenneth-acejo when filling out issues please follow the template https://github.com/infor-design/enterprise/issues/new/choose in the future. Even tho this is simple. I will provide a quick fix.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
