### ISSUE TITLE
Toolbar Flex:  Add better documentation

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#4004]
**Is your feature request related to a problem or use case? Please describe.**
There aren't a lot of specific instructions on how to build out and configure Flex Toolbars.  These are more CSS-driven and need a bit more setup than the standard Toolbar.   

**Describe the solution you'd like**
Add the following:
- The various CSS classes that can be used to set size/alignments on `.toolbar-section` areas.
- Some recipes for building out specific toolbar types (links to examples)

**Additional context**
Relevant [MS Teams Chat](https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1591109148175?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1590969547214&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Angular%20Components&createdTime=1591109148175) where I commented on some things that really need documentation.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
