### ISSUE TITLE
Context Menu of input field is not working in windows 10 IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4007]
**Describe the bug**
Context Menu of input field is not working in windows 10 IE11

**To Reproduce**
1. Open IE 11 and Go to https://4290-rc1-enterprise.demo.design.infor.com/
2. Scroll down to Context Menu on input fields
3. Right click on the fields 

**Expected behavior**
A context menu should show 

**Version**
4.290-rc1

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/83747456-3b172f80-a693-11ea-91eb-947076b5404c.png)

**Platform**
Windows 10 IE 11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
@janahintal i cant seem to reproduce this. i tried https://4290-rc1-enterprise.demo.design.infor.com/components/contextmenu/example-index.html in the IE 11 browser as well and it opens up fine.

Can you try again clearing caches? Or if you get it will you check the console for any errors?

**Comment by tmcconechy** [comment]
Descoping this issue due to dropping IE 11 support.
