### ISSUE TITLE
Popover is not working properly when opened in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4008]
**Describe the bug**
Popover is not working properly when opened in responsive view

**To Reproduce**
1. Open the browser and switch to responsive view
2. Now to https://4290-rc1-enterprise.demo.design.infor.com/?colors=50535a
3. Scroll down to popover example then click to button to open

**Expected behavior**
Pop over details should still show in responsive view

**Version**
4290-rc1

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/83758984-77ec2200-a6a5-11ea-9497-43076c1afe9e.png)

**Platform**
All browser, OS and devices.

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Think im going to just descope this.
- IE 11 is out of scope for serious issues
- Responsive doesnt really matter in IE 11
- The pop is useful and its only one example
