### ISSUE TITLE
Datagrid: Default column width renders too wide

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#4016]
**Describe the bug**
One pushback we are getting in landmark for 4.x is that there is too much horizontal scrolling for datagrids compared to the 3.5. 

**To Reproduce**
- See me for how URL/login and credentials.

**Expected behavior**
Want to columns to be greedy about reclaiming white space.

**Version**
7.1.1 of ng/ 2.28 of ep
**Screenshots**
In this case many columns seem to take more space than is needed. Some have their filter fields taking up more width than their cell.
![image](https://user-images.githubusercontent.com/4737815/83910781-c4307400-a730-11ea-97cc-bc48f692cc44.png)
In 3.5 this was much less of an issue because in landmark we set the size to fit on the columns and had a much smaller font.
![image](https://user-images.githubusercontent.com/4737815/83910875-e7f3ba00-a730-11ea-9bd6-6bcbeaeedc8d.png)
A more aggressive reclaim of white space could be of at least marginal improvement. 
![image](https://user-images.githubusercontent.com/4737815/83911186-78ca9580-a731-11ea-85f4-f084cd0bbc69.png)

**Platform**

 - PC
 - Window10
 - Latest Chrome

**Additional context**

**Comment by tmcconechy** [comment]
@pwpatton can you maybe give me the JSON data, grid settings and column settings for this grid example? I think i could make an example out of that.

**Comment by tmcconechy** [comment]
So i studied 3.5 the difference is that it doesn't fill the grid area. It just sizes the columns to the data and stops. Do we want that? Leaving a space on the left?

This could be an option, we just add an empty column at the end. But with less columns it wont evenly spread.

<img width="1255" alt="Screen Shot 2020-06-17 at 2 50 08 PM" src="https://user-images.githubusercontent.com/814283/84937606-0b602280-b0aa-11ea-9bbf-577c1c6868ac.png">

Do we want an option for spaceColumn? Or just a shorter defaulting of column sizes and still stretching it if need be?

**Comment by tmcconechy** [comment]
Also #3755 will record quite a bit of space by just changing the font size and margin

**Comment by pwpatton** [comment]
Can we fit as best as possible with little white space when the the container is narrow but spread them out if the container is large enough?

**Comment by tmcconechy** [comment]
The problem is really only when there is less columns and space than the datagrid width. At that point it goes and stretches the columns out across overriding whatever you set for widths so at that point the columns get big enough to stretch, stretching each one a bit beyond what it would be at the narrow size.

So i can just set the initial "narrow" size but once the grid is much wider than all the defaults the begin to stretch across. Then the only way is to make an extra blank stretching column

I.E. We are partially stuck by the table / browser it has a specific algorithm we cant override. https://www.w3.org/TR/CSS21/visudet.html#propdef-max-width things like maxwidth wont work, it just gets stretched.

Ok, what i will do is look for some tweaks on the size. Making it the size of number of characters in the filter container. Should reclaim some. Then can also add the spacer column and you can try it out

**Comment by pwpatton** [comment]
I think we could deal with a spacer column if it looked more like the other cells. And by spacer I mean one at the end that isn't one of the data columns. When it cuts off like before customer really didn't like it.

**Comment by tmcconechy** [comment]
yeah would just be black space on the header and then the row would continue . i'll work up some options on this.

**Comment by tmcconechy** [comment]
@pwpatton just so im comparing apples to apples. Can you send me the JSON data for that "books" page. Would need both the columns and dataset data.

Thanks!

**Comment by lipetzan** [comment]
Woah, this was pushed out to 31?  Can we talk?

**Comment by tmcconechy** [comment]
Yes, we can talk. It was too much work/plus other things added. Had to push

**Comment by tmcconechy** [comment]
@pwpatton 
Also Still looking to get this data (columns and data for this example) ...to accurately test and start this. Or at least either the columns or dataset?

**Comment by tmcconechy** [comment]
Found too problems so will adjust this.

1) if on short row height its sizing as if the padding was "normal"
2) its giving too much space for the filter row

**Comment by tmcconechy** [comment]
![Screen Shot 2020-07-10 at 4 49 41 PM](https://user-images.githubusercontent.com/814283/87201819-5f3ae180-c2cd-11ea-8346-e3fbd9c33d81.png)

BTW dont need the data per se anymore i made an example

**Comment by janahintal** [comment]
The default width still renders wide for some columns that do not have long data although there has been a size reduction. 

![image](https://user-images.githubusercontent.com/45757016/89154304-368acc80-d599-11ea-8d90-cff2b30b7a55.png)
![image](https://user-images.githubusercontent.com/45757016/89154317-3c80ad80-d599-11ea-9046-3e6b820b8ff4.png)

**Comment by tmcconechy** [comment]
This is correct @janahintal (or at least what i was trying to do).

https://4310-beta1-enterprise.demo.design.infor.com/components/datagrid/example-books.html -> this page has a small amount of reduction and sizes including the header

https://4310-beta1-enterprise.demo.design.infor.com/components/datagrid/example-columnsizing.html -> is the same xample with data size only truncating the header

**Comment by pwpatton** [comment]
@tmcconechy is't the idea that we still need a min size for the filter bar so that filter fields don't get truncated out of view. I think one thing that could improve that as well is to only show the down arrow and not the icon in the data case.

**Comment by tmcconechy** [comment]
I tried to just keep it consistent to one character for the filter. After all it was emphasizing the data. So that should be close. Also its pretty hard to makeout the header text unless its 5-6 characters

**Comment by claudenbach** [comment]
Let me know when a package is ready with this change.

**Comment by pwpatton** [comment]
@tmcconechy  @claudenbach isn't this already in 7.5.0-beta.2?

**Comment by tmcconechy** [comment]
No i didnt make a beta 2 yet as i was waiting for testing to procede further. (Cant make a build for every issue).
But its ready now so there will be a 7.5.0-rc shortly today

**Comment by tmcconechy** [comment]
Ok made a mistake but its ready. There is a 7.5.0-rc1 which has 4.31.0-rc.0

**Comment by janahintal** [comment]
Thank you guys for the confirmation. Working fine on my end & will now move this to done. 
Retested it in https://4310-beta1-enterprise.demo.design.infor.com/components/datagrid/example-columnsizing.html & https://4310-rc0-enterprise.demo.design.infor.com/components/datagrid/example-books.html

![image](https://user-images.githubusercontent.com/45757016/89386267-6a99f500-d733-11ea-8f89-d4ecf2a108f3.png)
![image](https://user-images.githubusercontent.com/45757016/89386287-71286c80-d733-11ea-9ed7-b594c0cb02bf.png)
