### ISSUE TITLE
Datagrid: Add favor data setting over the column header in a datagrid when sizing column

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#4017]
One pushback we are getting in landmark for 4.x is that there is too much horizontal scrolling for datagrids compared to the 3.5.

**Describe the solution you'd like**
A new setting to allow for cell data to be favored over the column headers when computing width.

**Describe alternatives you've considered**
A full auto fit all column where datagrid would never horizontally scroll; like in 3.5.

**Additional context**
With a few changes this could reclaim a lot of space and keep us from horizontally scrolling as much as we have to now. 
- change filter icon to be something much narrower perhaps just a down arrow
- have a minimum size for filter fields to they at least fit in the column header: sizes would be different based on the component. 
- Keep data always in view but allow the header text to have an ellipsis.

Notice in the before and after of the datagrid it's much small and it still shows all data. This is ofcource a stress test and when the browser is this wide it wouldn't need to have all the columns so narrow but I wanted to illustrate the difference that could be made up by doing the things listed above. 

![image](https://user-images.githubusercontent.com/4737815/83920696-61e06f00-a742-11ea-9a28-ec269bc1c920.png)

**Comment by tmcconechy** [comment]
This might be similar to https://master-enterprise.demo.design.infor.com/components/datagrid/test-columns-equal.html except that it will use the data instead.

Hope this one is possible.

**Comment by vonnyw** [comment]
@tmcconechy Could this possibly be included in 4.30?

**Comment by tmcconechy** [comment]
I not sure if we will have time enough for this. But i am working on related ones so will see.

**Comment by tmcconechy** [comment]
I think https://github.com/infor-design/enterprise/issues/4016 and this are identical issues. In order to fix this try to add a few settings something like:

1. columSizing: 'all | data | header | filterRow` -> the current is all. meaning we currently size to title or data
1. spacerColumn: false -> if set we decide to not stretch the rows the last column will be a spacer like in 3.5, this also makes the grid less responsive than it is now however. So will be default false.

**Comment by janahintal** [comment]
Working fine on my end. 
Verified in https://4310-beta1-enterprise.demo.design.infor.com/components/datagrid/example-columnsizing?theme=uplift&variant=light&colors=0066D4 & https://4310-beta1-enterprise.demo.design.infor.com/components/datagrid/example-books.html
![image](https://user-images.githubusercontent.com/45757016/88919223-4eaed300-d29d-11ea-96e0-63806be3df6d.png)
& without the feature 
![image](https://user-images.githubusercontent.com/45757016/88919454-b1a06a00-d29d-11ea-8301-8467bddc2aee.png)
