### ISSUE TITLE
SOHO-7947: Add the ability to add locales to the defaultLocale function in sohoxi.js

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#402]
**Use Case 1**

Landmark uses some specific languages called Manglish and Maribic to test translations.
Landmark passes in "mx-LW" and "mx-LW-RTL" to Soho.Locale.

These are not included in the variables of allLocales or defaults$$1 so they always return blank.
Would like the ability to pass in some additional locales to be appended to these varaibles. 

Something like.
```
defaultLocale: function defaultLocale(locale, addLocales, addDefaults) {
}
```

**Use Case 2**

Show an example of adding custom strings to an existing locale.

```
Soho.Locale.currentLocale.data.messages = extend(true, {},
Soho.Locale.currentLocale.data.messages, newMessages);
```

**Comment by bthharper** [comment]
Need this feature too, we used it extensively with SoHo 3.x.

**Comment by CindyMercadoReyes** [comment]
Tested this ticket using URL: https://4170-beta0-enterprise.demo.design.infor.com/components/locale/test-set-language.html?locale=de-DE. This issue is now resolved.
