### ISSUE TITLE
Datagrid: Backspace issue with Dropdown lists on Grids

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#4020]
See a "口" display in the cell when pressing the "Backspace" key having selected an entry form a dropdown list on a grid

1. Open Example grid https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-editable.html
2. Press S key twice, then press Enter key, to select the Shipped option.
3. Press Backspace key twice
Result: "口" (square character) displayed in the cell

**Expected behavior**
No "口" (square character) displayed in the cell

**Version**
latest (4.28.2) *Screenshots**
![image](https://user-images.githubusercontent.com/49482971/84041818-31940d00-a99c-11ea-90fc-e5992dcf128e.png)

**Platform**
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Chrome
 - 81.0.4044.138 (64 bit)

**Comment by tmcconechy** [comment]
Might need windows for this? As i tested on mac and it doesnt occur

**Comment by jmacaluso711** [comment]
I'm noticing on Mac you can't backspace at all in this scenario. So, wondering if the fix is to just disable backspace in windows to make it consistent.

**Comment by tmcconechy** [comment]
I think we might need to do both keys. Can try on windows and check in a normal input but I think both backspace and delete key on windows clear one character in an input and then dropdown should do the same.

So:

On Mac delete key or function + delete (backspace) would clear one char 
On pc delete or backspace would clear one char

**Comment by jbrcna** [comment]
**QA Passed**
had to press fn + delete twice to clear the value in the cell 
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
![image](https://user-images.githubusercontent.com/56722184/88261726-6adcce00-ccf9-11ea-8cbf-e7739078a427.png)
