### ISSUE TITLE
Tree: updateNode() - when "children" property is null/undefined/not present, default leaf node icon (icon-tree-node) should be shown

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise#4026]
When all children nodes are removed from a tree node and children property of node is null or is removed altogether

**Actual Behaviour:** The tree node still shows folder icon. As all children are deleted, it should be shown as a leaf node.
**Expected Behaviour:** As the node no longer has any children & "children" property is null/undefined/not present, it should be shown as a leaf node with leaf node default icon.

```
<div class="row top-padding">
  <div class="twelve columns">
    <button type="button" id="btn-remove-update-node" class="btn-secondary">Remove all children & update</button>
  </div>
</div>

<div class="row top-padding">
  <div class="twelve columns">
    <ul id="tree" class="tree" role="tree" aria-label="Asset Types" data-init="false">
      <li><a href="#" id="home">Home</a></li>
      <li><a href="#" id="about">About Us</a></li>
      <li class="is-open">
        <a href="#" id="public">Public Folders</a>
        <ul class="is-open root">
          <li class="is-open">
              <a href="#" id="leadership">Leadership</a>
              <ul class="is-open">
                <li><a href="#" id="new1">New Item 1</a></li>
                <li><a href="#" id="new2">New Item 2</a></li>
              </ul>
          </li>
          <li class="is-open">
            <a href="#" id="hr">HR</a>
        </li>
        </ul>
      </li>
    </ul>

  </div>
</div>

<script>
  var tree = $('#tree').tree().data('tree');

  // Remove node
  $('#btn-remove-update-node').on('click', function () {
    var toRemoveId = tree.findById('line-mgr') ? 'line-mgr' : 'new2';
    tree.removeNode({id: toRemoveId});
    tree.removeNode({id: 'new1'});
    const node = tree.findById('leadership');
    node.children = null //or delete node.children;
    tree.updateNode(node);
    $(this).disable(); // let it trigger onetime only
    console.log('Node Removed');
  });

</script>

```
**To Reproduce**
Steps to reproduce the behaviour:
1. Run the above code in enterprise repo
2. Click on 'Remove all children & update' button

![image](https://user-images.githubusercontent.com/1594815/84203830-62fafe80-aaaa-11ea-8d9b-4e6f94fbda7e.png)

**Version**
ids-enterprise: v4.29.0

**Additional context**
Infor PIM
cc @karinthulin

**Comment by deep7102** [comment]
Hi @hemantg05 for `updateNode(nodeData)` will update only the passing key/value. If there is any `undefined/not present` it will not do anything in this case property `children`. So after merge the PR(https://github.com/infor-design/enterprise/pull/4123) in order do update and remove children key/value can pass `null` or `[] -an empty array`. It will remove children key/value and should show as a leaf node.

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/tree/test-remove-all-children-and-update.html?theme=uplift&variant=light&colors=0066D4 & https://master-enterprise.demo.design.infor.com/components/tree/test-add-node.html?theme=uplift&variant=light&colors=0066D4
