### ISSUE TITLE
Datagrid: Inconsistent results with datagrid filtering on treegrid column

### ISSUE THREAD

**Issue by waltersh790824** [infor-design/enterprise#4031]
**Describe the bug**
While trying to filter data on a column using the Treegrid formatter, the results displayed are inconsistent.  Most of the time, the right results are displayed, but there are certain strings that are supposed to match something but don't get displayed.  The parent row of matching rows will be shown, but when expanded, no rows are shown.

**To Reproduce**
https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-filter.html 
- search for more in first column, and it showing only the parent nodes

https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-filter-child-on-match.html
- search for more in first column,
- here it changing the level of it the found results
 

**Expected behavior**
I expect all matching rows to be visible

**Version**
- ids-enterprise-ng: 6.6.4

**Screenshots**
![image](https://user-images.githubusercontent.com/25912716/84313127-165c0580-ab34-11ea-8909-122c5e8f1f3f.png)

![image](https://user-images.githubusercontent.com/25912716/84313083-080de980-ab34-11ea-8d51-7d8040399761.png)

**Platform**
Latest chrome

**Comment by janahintal** [comment]
The issue still exist in https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-filter.html

Steps: 
1. In the first column filter '=' More Contact
2. This row should be filtered
![image](https://user-images.githubusercontent.com/45757016/88276944-75579180-cd12-11ea-8a7c-d9130a6c943a.png)

**Comment by tmcconechy** [comment]
I tried the steps you mentioned @janahintal and its working as expected. Maybe try and hard refresh your browser?

<img width="334" alt="Screen Shot 2020-07-23 at 9 29 27 AM" src="https://user-images.githubusercontent.com/814283/88291974-030d8f80-ccc7-11ea-8d81-ec0b74d5d354.png">

What about you @deep7102 ? See this new issue?

**Comment by deep7102** [comment]
Yes! same here my end, working as expected.

http://localhost:4000/components/datagrid/test-tree-filter.html
- Apply "equal" filter on `Task` column with the word `More Contact`
- It should have parent and all child nodes, if not expanded use expand/collapse button
- There should be 8 rows as: 7, 10, 12, 13, 15, 18, 20, 21

**Comment by janahintal** [comment]
Hi Guys, 
Tried refreshing my browser already.  Now working as expected. Thank you :) 
![image](https://user-images.githubusercontent.com/45757016/88381029-2f650100-cdd8-11ea-84af-c47e5305cda2.png)
