### ISSUE TITLE
Datagrid: Make the select column consistent size

### ISSUE THREAD

**Issue by jamie-norman** [infor-design/enterprise#4032]
**Is your feature request related to a problem or use case? Please describe.**
When datagrid allows select/multi-select, the column size seems to be trying to factor into the column sizing. However, this column doesn't need to change widths as it will always contain the same size content. It can be very inconsistent when in a multi-list situation. 

**Describe the solution you'd like**
Create a standard, fixed column size for the select column

**Describe alternatives you've considered**
-
**Additional context**
![image](https://user-images.githubusercontent.com/44705854/84384769-17347c00-abb4-11ea-9782-67ab29c98722.png)

**Comment by tmcconechy** [comment]
I think i see the bug here:

https://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
- go in .. and in personalize columns
- toggle down the number of columns
- each time notice the checkbox column is changing size

This is because the grid is rebalancing to fit size. Maybe this can be avoided. Can take a look

**Comment by jamie-norman** [comment]
Can you still have good column resizing while not factoring in the checkbox column, so it would always have a fixed size?

**Comment by tmcconechy** [comment]
I think so. Must be a way. Actually thought this was working.

**Comment by jmacaluso711** [comment]
@tmcconechy seems like #4016  solution may fix this as well

**Comment by tmcconechy** [comment]
Interesting workaround i found which might even be a potential solution. Is to set one column (the one you want to stretch out) to `width: 100%`. This should work in any version

It seems the only two options are to either stretch one column out or leave a spacer area where the gap would be. Can make an example with both options

**Comment by jbrcna** [comment]
**QA Failed**
In `IE11` and `Firefox` using `Vibrant` Theme and Row Height `Extra Small`, when you hide/show `Product Name` column the grid resizes a little bit.
v4.31.0-beta1
https://4310-beta1-enterprise.demo.design.infor.com/components/datagrid/example-spacer-column.html?theme=uplift&variant=light&colors=0066D4
![Large GIF (1318x388)](https://user-images.githubusercontent.com/56722184/88898987-13ea7200-d280-11ea-857a-2f14d0a3e689.gif)

**Comment by tmcconechy** [comment]
Im going to call that too minor to worry about. There is a bit of flex in the rows so it can change size slightly

**Comment by tmcconechy** [comment]
Update i think i did fix this last item in a different context... So can retry it on next beta or rc build
