### ISSUE TITLE
Chinese locale abbreviated month name

### ISSUE THREAD

**Issue by pukhrajbal** [infor-design/enterprise#4034]
All chinese locales show number for abbreviated month names. Could this be same as "wide" values?
e.g.
https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/zh-CN.js#L38

cc https://jira.infor.com/browse/MCRM-12560

**Comment by tmcconechy** [comment]
This is the data i got from the CLDR. But if its problematic and a chinese speaker says. We can change it. But not sure if much point in having them the same?

**Comment by tmcconechy** [comment]
Data in the CLDR https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/zh-Hans/ca-gregorian.json#L30 but again we can override it if thats prefered

**Comment by pukhrajbal** [comment]
Yes I think it would be better. Abbreviated section can be used instead of narrow - refer https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/zh-Hans/ca-gregorian.json#L16

**Comment by jbrcna** [comment]
**QA Passed**
v4.30.0-dev
