### ISSUE TITLE
Datepicker: Errors when loading the calendar in fr-CA, pt-BR

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4035]
**Describe the bug**
The datepicker appears to be giving errors on some locales such as fr-CA, pt-BR

**To Reproduce**
1. Go to https://4270-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=fr-CA
2. Click on calendar
3. See error on screen and in the console.

**Expected behavior**
No errors - loads ok

**Version**

- ids-enterprise: [4.25 and Up]

**Platform**
 - Mac/Chrome or any

**Additional context**
Teams Chat

**Comment by jbrcna** [comment]
**QA Passed**
v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=pt-BR
https://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=fr-CA
https://master-enterprise.demo.design.infor.com/components/datepicker/test-with-time-cs-CZ.html
https://master-enterprise.demo.design.infor.com/components/datepicker/test-specific-lang.html
https://master-enterprise.demo.design.infor.com/components/datepicker/test-two-locales-same-page.html
![image](https://user-images.githubusercontent.com/56722184/84759946-fa57d880-aff9-11ea-9eb0-8e61a8d2510e.png)
