### ISSUE TITLE
Calendar: Custom Tooltips for eventTypes

### ISSUE THREAD

**Issue by sharmainerivera** [infor-design/enterprise#4039]
**Is your feature request related to a problem or use case? Please describe.**
We would like to show the resource details of an event type on the calendar. This will give the user an overview when to use the event type properly and if it aligns on their needs.

**Describe the solution you'd like**
There should be customizable tooltips dedicated on each event types on the calendar.

**Describe alternatives you've considered**
One workaround is using the generic IDS tooltips but we might encounter problems using the tooltips with the structure of the calendar.

**Additional context**
Project screenshot:
![image](https://user-images.githubusercontent.com/61222084/84628106-a6c28d80-af1a-11ea-89ae-3dec2117bfe6.png)

IDS Requested Outcome:
![image](https://user-images.githubusercontent.com/61222084/84629033-43395f80-af1c-11ea-975f-154dc84f6636.png)

**Comment by tmcconechy** [comment]
I think you should be safe just implementing either a tooltip https://master-enterprise.demo.design.infor.com/components/tooltip/example-index.html?theme=uplift&variant=light&colors=0066D4 or https://master-enterprise.demo.design.infor.com/components/popover/example-index.html?theme=uplift&variant=light&colors=0066D4

Just add the tooltip on the checkboxes after they render. But we could try and support the title

**Comment by tmcconechy** [comment]
Suggest just using the normal tooltip plugin here. It should support a custom tooltip on the checkbox.

https://master-enterprise.demo.design.infor.com/components/tooltip/list
