### ISSUE TITLE
Locale: Unlocalised 'Locale' Thai label in Ming.le > User Settings > Localization Settings

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4041]
Unlocalised 'Locale' Thai label in Ming.le > User Settings > Localization Settings

![locale](https://user-images.githubusercontent.com/66057969/84654752-05ced500-af10-11ea-95e0-018cde7bd6ec.png)

**Comment by tmcconechy** [comment]
Is there a place to raise issues for the translation team? This was not given to me https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/th-TH.js#L239

**Comment by cpinatel7** [comment]
Henry is responsible for Ming.le translations

**Comment by tmcconechy** [comment]
Right but does he have a Jira or something. He's not going to get this information here.

**Comment by cpinatel7** [comment]
I guess he should have a github account

**Comment by tmcconechy** [comment]
Added this and set it to `สถานที่เกิดเหตุ` for now. Made a test so i can uncover it when henry does the actual next round of translations if its not added.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.

**Comment by cpinatel7** [comment]
Retested in 2 different tenants (Infor OS ™ 2021-03). Locale is still unlocalised. Thanks

**Comment by tmcconechy** [comment]
We have the string in our set of strings https://github.com/infor-design/enterprise/blob/master/src/components/locale/cultures/th-TH.js#L253 but this screen is in mingle and not a component so im not sure where they need to change this.

Would raise this issue with the Infor OS / Mingle team

**Comment by cpinatel7** [comment]
Thanks. New JT: TSDEVSUP-26206
