### ISSUE TITLE
Application:  Focused Item Menu Styling Issue

### ISSUE THREAD

**Issue by bthharper** [infor-design/enterprise#4042]
**Describe the bug**

After upgrading to EP 4.29.x (via ep-ng 7.2.x) the styling of the focused menu item in the application menu is wrong.  I have only noticed in the Vibrant / Dark theme.

**To Reproduce**

1. Open a browser.
2. Navigate to [here](https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html?theme=uplift&variant=dark).
3. Open the Application Menu
4. Move the focus to one of the menu items.

**Expected behavior**

The highlight is incorrect, the top border is dark blue.  I am unclear what the exact colour should be.

**Version**

EP version 4.29.3

**Screenshots**

![image](https://user-images.githubusercontent.com/8340092/84663022-842d7600-af14-11ea-9791-2a4fce72d162.png)

**Comment by bthharper** [comment]
Actually, clicking on the link above produces:

![image](https://user-images.githubusercontent.com/8340092/84663758-7debc980-af15-11ea-9885-8e22d8c60405.png)

So the difference is the background of the application menu.

**Comment by tmcconechy** [comment]
I think just the default state (no color) needs to be fixed. You can also use the coloring to "fix" it. But thats optional.

**Comment by bthharper** [comment]
Click on:

* [link](https://master-enterprise.demo.design.infor.com/components/applicationmenu/list?theme=uplift&variant=dark&colors=0066D4)
* Select Example Index
* Select the Vibrant Theme 
* Select the Dark Variant
* Open the application menu
* Focus (select) an item

**Comment by bthharper** [comment]
@tmcconechy the application menu background does not change to blue when swapping themes, however in some circumstances it does.  Is there an issue here?

**Comment by tmcconechy** [comment]
@bthharper what do you mean there? Just in the demo app? The thing is we append the color on the URL so now its "saved". Is that what you mean? (watch the URL color param)

**Comment by bthharper** [comment]
@tmcconechy I think the the updated steps (above) then hopefully you will see the issue.

**Comment by bthharper** [comment]
I think the difference I am seeing is that "sometimes" the background of the application menu is blue (in the demo page) and sometimes black (it is always black in my application).  

When it is black, the focus colours are wrong.

**Comment by tmcconechy** [comment]
Yes i see the issue when its black as in https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html?theme=uplift&variant=dark (no color added so will take a look 👍 )

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
