### ISSUE TITLE
Incorrect Language List in Ming.le (User Settings > Localization Settings > Language)

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4043]
Incorrect Language List in Ming.le (User Settings > Localization Settings > Language)

1) Chinese (S) should be Chinese (Simplified)
2) Chinese (T) should be Chinese (Traditional)
3) Spanish (Spain) is not correct. Please refer to Wiki_Translation.png or https://wiki.infor.com/confluence/display/translation/Internationalization+standards. I understand that you need to map the language name / description to a culture code (e.g. es-ES) but most Infor products are translated into Spanish (International) and not Spanish (Spain). Spanish (International) or Spanish would be better
4) Arabic (Saudi Arabia) is not correct. Similar to 3). Most Infor products are available into a neutral Arabic version. Arabic (MSA) (where MSA = Modern Standard Arabic) or just Arabic would be better

Can you please discuss these points with Henry. Thank you

![Language](https://user-images.githubusercontent.com/66057969/84672723-2d7e6700-af29-11ea-9dda-7086d495d208.png)
![Wiki_Translation](https://user-images.githubusercontent.com/66057969/84672725-2e16fd80-af29-11ea-9ae7-b5429dcf7ba5.png)

**Comment by tmcconechy** [comment]
This seems 100% like a mingle Issue. I think this should be raised with the Mingle team. None of this is coming from anything we have. We just refer to these https://github.com/infor-design/enterprise/tree/master/src/components/locale/cultures

**Comment by cpinatel7** [comment]
Do they use github or an Infor Jira project? Thanks

**Comment by cpinatel7** [comment]
What's the Infor Jira project for Ming.le? Thanks

**Comment by tmcconechy** [comment]
I think thats here for mingle https://jira.infor.com/projects/TSDEVSUP 
Will close this then as i cant address it on my end
