### ISSUE TITLE
Locale: Incorrect fr-CA translation for 'Set Time'

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4045]
According to an external contractor / tester, “Set Time” should be translated “Fixer l’heure”.

Same issue in fr-FR

**To be reviewed by Dev / Translation Team**

![SetTime](https://user-images.githubusercontent.com/66057969/84755559-0de74d00-afc2-11ea-8496-a9532660ab13.png)

**Comment by tmcconechy** [comment]
If your going to be creating many more issues can you please

1. Use the template for issues https://github.com/infor-design/enterprise/issues/new/choose
2. Consider batching the issues with bullet points.

With this issue this comes from the translation team. So we again need a system for notifying them to change their translations. I can override them but they might just come back wrong.

So maybe this should go in the Translations teams issue tracker.

**Comment by tmcconechy** [comment]
Changed this as a placeholder to `Fixer l'heure` in fr-CA and fr-FR and added a test in case its not fixed by the translation team when we get it back.

**Comment by hwondergem** [comment]
OK, I updated the translations for fr-FR and fr-CA in the translation project. Should be correct going forward.
   SetTime: { id: 'SetTime', value: 'Fixer l'heure', comment: 'button the sets time in a field - please review' },

**Comment by tmcconechy** [comment]
Thanks @hwondergem i did flag a few translations in the file this time. Not sure if that helps.

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=fr-CA
![image](https://user-images.githubusercontent.com/56722184/87403295-45600e00-c5ef-11ea-8768-097cf2c6cd2d.png)
