### ISSUE TITLE
Datepicker: Incorrect translations in el, hu, lt, lv, no, ro, ru, sk, zh-TW and zh-CN

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4046]
**Describe the bug**
There are bugs or Incorrect calendar / calendar translations in el-GR, hu, lt, lv, no, ro, ru, sk, zh-TW and zh-CN

**To Reproduce**
1. Go to http://localhost:4000/components/datepicker/example-index.html?locale=el-GR (or any locale above)
2. Open picker
3. Test as per spread sheet attached

**List of fixes**

- [x] REJECTED: Undefined text in no-NO locale. Cannot be reproduced see https://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=no-NO
- [x] FIXED EARLIER: Genitive case not nomative case months in ru-RU locale -> was already fixed https://github.com/infor-design/enterprise/issues/3464
- [x] FIXED: Date format wrong in lv-LV http://localhost:4000/components/datepicker/example-index.html?locale=lv-V
- [x] FIXED: http://localhost:4000/components/datepicker/example-index.html?locale=lt-lT -> has wrong format
- [x] FIXED: http://localhost:4000/components/datepicker/example-index.html?locale=ro-RO -> has confusing month initials
- [x] FIXED: http://localhost:4000/components/datepicker/example-index.html?locale=sk-SK -> has incorrect grammer
- [x] FIXED: Genitive case not nomative case months in el-GR locale
- [x] FIXED: Wrong date format in zh-TW locale -> could not be reproduced in http://localhost:4000/components/datepicker/example-index.html?locale=zh-TW  (probably fixed)
- [x] FIXED: Wrong date format in zh-CN locale -> could not be reproduced in http://localhost:4000/components/datepicker/example-index.html?locale=zh-CN (probably fixed)
- [x] FIXED: wrong format on http://localhost:4000/components/datepicker/example-index.html?locale=hu-HU missing space
 
**Expected behavior**
No bugs/ correct translations

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Platform**
 - Any

**Additional context**
Please refer to: Calendar.xlsx attachment:
[Calendar.xlsx](https://github.com/infor-design/enterprise/files/4785669/Calendar.xlsx)

**Comment by tmcconechy** [comment]
I'll see if any of this can be reproduced on our end. I think some of it will be.

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=lv-V
![image](https://user-images.githubusercontent.com/56722184/87402908-c5d23f00-c5ee-11ea-853e-1e4779894c43.png)
