### ISSUE TITLE
Dropdown: Filtering with "Phrase Starts with" not correct after backspace

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#4047]
Phrase Starts With search in Dropdown lists not correct after backspace

Steps to reproduce the behavior:-
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/test-filter-types.html
2. Click in PhraseStartsWith Filter textbox and type a
3. Dropdown list shows Alabama, Alaska ...
4. type another a (so aa now in textbox)
5. Nothing in list
6. Backspace once leaving single a in textbox
7. List remains empty

**Expected behavior**
Expect list to show Alabama, Alaska ...

**Version**
latest (4.29.2)

**Comment by janahintal** [comment]
QA Passed. Thank you.
Verified in https://master-enterprise.demo.design.infor.com/components/dropdown/test-filter-types.html?theme=uplift&variant=light&colors=0066D4
