### ISSUE TITLE
Locale: Unlocalised labels and incorrect translations in Text / Visual Editor

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4049]
**Describe the bug**
There are Unlocalised labels and incorrect translations in Text / Visual Editor. Below are several examples. I think all languages should be reviewed (e.g. Block quote - often translated as Quotation / Sales Quotation)

**To Reproduce**
1. Go to http://localhost:4000/components/editor/example-index.html?locale=de-DE
2. Change the locale to one of the following..

**Greek - el-GR**
- [x] Block quote - incorrect
- [x] View Source - incorrect
- [x] Url - missing
- [x] Css Class  - missing

**Lithuanian - lt-LT**
- [x] Klasė in In Ccc Klasė should start with lowercase letter

**Chinese Simplified - zh-CN**
- [x] Strike through - incorrect
- [x] Insert Anchor - incorrect

**Portuguese (pt-PT)**
- [x] Toggle Heading 3 missing
- [x] Toggle Heading 4 missing
- [x] Toggle Bold Text missing
- [x] Toggle Italic Text missing
- [x] Toggle Underline Text missing

**slovanian (sl-SI)**
- [x] Block quote missing
- [x] Insert anchor missing

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.29]

**Platform**
 - Mac/Chrome or any

**Screen Shots**
![Editor](https://user-images.githubusercontent.com/66057969/84794267-57518f80-aff6-11ea-8832-4b022947acc5.png)

**Comment by tmcconechy** [comment]
What version is this for?

**Comment by cpinatel7** [comment]
I don't know. The Infor Learning Management Dev manager doesn't want to tell me. For sure they haven't upgraded for a while and they don't want to... However, the latest translations are still incorrect. For example, the translation for Block quote was fixed a few days ago in fr-FR (email sent to Henry). There are too many issues in this area therefore I decided to create a defect for tracking purposes. Thanks

**Comment by tmcconechy** [comment]
OK i will have a deeper look at this. Definitely seeing some issues on editor

**Comment by cpinatel7** [comment]
Thanks. This defect also belongs to Henry. Linguists need to verify that their translations are correct in context e.g. Block quote is not a sales quotation

**Comment by tmcconechy** [comment]
Yes but also there are some bugs here. For example the Visual / Html button is a hard coded icon you cannot translate and also i think some strings are not established. I will start there so these get in for what we need for next sprint

**Comment by tmcconechy** [comment]
Fixed several of these and flagged them for the translation team. Some could not be reproduced

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/editor/example-index.html?locale=el-GR
![image](https://user-images.githubusercontent.com/56722184/87404325-945a7300-c5f0-11ea-8d41-8eb578236e4d.png)
![image](https://user-images.githubusercontent.com/56722184/87404338-98869080-c5f0-11ea-92b7-921525a84f92.png)
