### ISSUE TITLE
SOHO-7933: updateRow() causes a row of tree datagrid displayed with wrong indent

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#405]
if a row contains tree sub-rows, updateRow() causes the row got one more indent space.
If a row is the last row of sub-rows, updateRow() cause the row got one less indent pace.
details see attached screenshot.

**Comment by theakatz** [comment]
@jmacaluso711 there is some extra context here: https://jira.infor.com/browse/SOHO-7933

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-tree-update-row.html
Passed QA testing on all browsers, will do further testing once 4.15.0 build is ready.
