### ISSUE TITLE
Editor: Missing tooltips

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4050]
**Describe the bug**

**To Reproduce**
1. Go to http://localhost:4000/components/editor/example-index.html
2. Hover on 'B'
3. See issue, there is no tooltip 

**Version**
- ids-enterprise: [v4.19 to now]

**Platform**
 - Mac/Chrome

**Additional context**
See also https://github.com/infor-design/enterprise/issues/4049

**Comment by jbrcna** [comment]
**QA Passed** with Observation
v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
![image](https://user-images.githubusercontent.com/56722184/85999233-63017500-ba3e-11ea-8523-3decef32803b.png)

**Observation**
The label in `Strikethrough` doesn't have the word **"Toggle"**
![image](https://user-images.githubusercontent.com/56722184/85999904-68ab8a80-ba3f-11ea-9e7a-eb6db211086d.png)
