### ISSUE TITLE
Multiselect: Scroll bar is misplaced after switching Theme

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4055]
**Describe the bug**
Multiselect: Scroll bar is misplaced after switching Theme

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/multiselect/test-select-all-tags.html
2. Open the Drop Down and Select All
3. Close the Dropdown
4. Change Theme to Vibrant

**Expected behavior**
The Scroll bar should not be misplaced

**Version**
4.30.0 - dev (master)

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/85012782-20b27b00-b196-11ea-8968-acb6af0bc0f8.png)

**Platform**
 All Bowser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Sort of a failed QA ish thing if maybe you want to look? @EdwardCoyle

**Comment by janahintal** [comment]
This issue is ow resolved. Thank you! 
Verified in https://master-enterprise.demo.design.infor.com/components/multiselect/test-select-all-tags.html?theme=uplift&variant=light&colors=0066D4
