### ISSUE TITLE
Datagrid: the fieldValue method is not always performing xssUtils.escapeHTML() 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4058]
Describe the bug
The logic of fieldValue() does not handle the case when the field argument has a value of 'fields.comments.value'.  The method returns when the field contains '.' before  performing xssUtils.escapeHTML(value).

To Reproduce
1. Using the attached test-editable-editor-singleline-rowheight.html
2. Render the datagrid
3. Notice that the Singleline cell is not showing the rich text value
4. Setting breakpoint in fieldValue() of datagrid.js, see that it doesn't handle a field whose value consists of something like 'fields.comments.value'.

Expected behavior
Rich text cell value is displayed.

Version
4.30.0-dev

**Comment by claudenbach** [comment]
Suggested code change:

```
  fieldValue(obj, field) {
    if (!field || !obj) {
      return '';
    }

    let rawValue;
    if (field.indexOf('.') > -1) {
      rawValue =  field.split('.').reduce((o, x) => (o ? o[x] : ''), obj);
    } else {
      rawValue = obj[field];
    }

    // const rawValue = obj[field];
    let value = (rawValue || rawValue === 0 || rawValue === false ? rawValue : '');

    value = xssUtils.escapeHTML(value);
    return value;
  },
```

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/85078436-125e6200-b18a-11ea-807d-5587f7c2fd4f.png)

**Comment by claudenbach** [comment]
[Git-4058.zip](https://github.com/infor-design/enterprise/files/4801521/Git-4058.zip)

**Comment by claudenbach** [comment]
Rendering with the suggested code changes....

![image](https://user-images.githubusercontent.com/39804038/85078736-b47e4a00-b18a-11ea-8860-2e16a1a88c0e.png)

**Comment by claudenbach** [comment]
Requesting this for Enterprise 4.30.x. (June 2020).

**Comment by jbrcna** [comment]
**QA Passed**
v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-editor-singleline-rowheight
https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-editor-singleline
https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
https://master-enterprise.demo.design.infor.com/components/tooltip/example-index.html
