### ISSUE TITLE
Datagrid: `Soho.Editors.Lookup` editor doesn't support mask

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#406]
Original Issue: [SOHO-7928](https://jira.infor.com/browse/SOHO-7928)
----

Datagrid columns using the `Soho.Editors.Lookup` do not support Mask.  For example, we would like to restrict the input to 10 numeric characters.  This is currently not supported.

So the following does not work (even when adding `maskMode` and `maxLength`)

```
SohoDataGridColumn)
    columns.push({
      id: 'lookup-click',
      name: 'Lookup Click',
      field: 'productId',
      editor: Soho.Editors.Lookup,
      editorOptions: {editable: true, click: LMLookupClickFunction},
      maskMode: 'number',
      mask: '##########',
      maxLength: 10
    });
```

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-editable-lookup-mask
Passed QA testing on localhost and master, will conduct further testing once 4.15.0 build is ready.
