### ISSUE TITLE
Datagrid: Select all function is not working as expected after clicking next page

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4060]
**Describe the bug**
Datagrid: Select all function is not working as expected after clicking next page

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html?theme=uplift&variant=light&colors=0066D4
2. Click Select All
3. Click Next Page

*Notice that all rows became unselected.* 

**Expected behavior**
All rows should be selected.

**Version**
4.30.0 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/85121846-253f6800-b258-11ea-8335-a8a94aabf241.png)

**Platform**
All browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This example is working as expected. Sometimes the selections are reset when changing page and sometimes they arent. Its a little hard to know but it is configurable and this page is configured to reset when changing page
