### ISSUE TITLE
Tabs: Remove tabset inner

### ISSUE THREAD

**Issue by Milan1983** [infor-design/enterprise#4061]
https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs/test-nested-horizontal-tabs.html

**Describe the bug**
selecting tab 1,so the tab 2 is hidden. Then when tried to remove tab 4 was selected previously, shows error.

**To Reproduce**
1. Select tab 2
2. Select tab  4
3. Select tab  1
4. remove tab  4 with `$('#nested-tabs-container').data('tabs').remove('tab4')` in the console
5. See error

**Expected behavior**
Expect no error

**Version**
- ids-enterprise: v4.29.3 

**Platform**
 - Infor Application/Team Name: Sunsystem
 - OS Version:  Windows 10 
 - Browser Name: Chrome
 - Browser Version: Version 83.0.4103.97 (Official Build) (64-bit)]

**Comment by tmcconechy** [comment]
@Milan1983 how do i remove a tab in this example? not sure i follow this.

**Comment by Milan1983** [comment]
@tmcconechy $('#nested-tabs-container').data('tabs').remove('tab4')

**Comment by tmcconechy** [comment]
Im not longer seeing an error with these steps on https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs/test-nested-horizontal-tabs.html

So closing this and passing it to QA to verify

**Comment by janahintal** [comment]
QA Passed. 
![image](https://user-images.githubusercontent.com/45757016/110311029-30ccfc00-803e-11eb-812c-867557a2946d.png)
![Uploading image.png…]()
