### ISSUE TITLE
Datagrid: Checkboxes in expandable areas can no longer be edited

### ISSUE THREAD

**Issue by hlu1805** [infor-design/enterprise#4062]
**Describe the bug**
In an expandable row. the checkbox is not clickable. This worked in previous versions.

**To Reproduce**
Steps to reproduce the behavior in IDS
1. go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-expandable-row-checkboxes.html
2. expand a cell
3. try to click a checkbox (doesnt work :) 

Steps to reproduce the behavior in our APP
1. Go to 'http://usalvwsce7.pmm.com/s1143-sceadmin'
2. In service panel, click on + sign to expand row
3. click on checkbox. It does not response.

**Version**
4.28.0
4.29.0

**Comment by tmcconechy** [comment]
@hlu1805 i made a patch 4.28.4 https://www.npmjs.com/package/ids-enterprise that includes a fix for this issue. You can get this out of npm or download from the releases https://github.com/infor-design/enterprise/releases

**Comment by jbrcna** [comment]
**QA Passed**
v4.30.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-expandable-row-checkboxes.html
![image](https://user-images.githubusercontent.com/56722184/85722176-9ed9c900-b724-11ea-9cf9-99fc331e09ca.png)
