### ISSUE TITLE
Datagrid: Popdown menu is not closing after focusing in the filter

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4063]
**Describe the bug**
Datagrid: Pop down menu is not closing after focusing in the filter

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html
2. Click on '...' button above the grid 
3. Hover & Click any filter input (the buttons in filter row work)

**Expected behavior**
Pop down menu should be closed

**Version**
4.30.0 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/85268076-9f662b80-b4a8-11ea-803b-9c397ffe14cd.png)

**Platform**
All Browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping for now
