### ISSUE TITLE
Datagrid: Select all is not working as expected after removing a cloumn

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4064]
**Describe the bug**
Datagrid: Select all is not working as expected after removing a cloumn

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouping-paging.html?theme=uplift&variant=light&colors=0066D4
2. Click 'Select All'
3. Click '...' and remove Product Id column 

**Expected behavior**
Select all should not be unselected

**Version**
4.30.0 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/85278262-494cb480-b4b7-11ea-8cc4-3ea10eebaeee.png)

**Platform**
All Browser, OS and devices

**Additional context**
n/a

**Comment by tmcconechy** [comment]
Descoping this for now
