### ISSUE TITLE
Accordion: Soho Dark Border Issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4066]
**Describe the bug**
the bottom border is missing

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/accordion/example-disabled.html?theme=soho&variant=dark&colors=0066D4
2. See Error
3. Notice that the bottom border is missing

**Expected behavior**
should have a full border

**Version**
- ids-enterprise: [v4.30.0-dev]

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/85278156-215d5100-b4b7-11ea-9ff3-0356921cb6eb.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
This is partly because this is disabled. If anything can bump up the border one on both ends and see how it looks

**Comment by tmcconechy** [comment]
This is fixed now see https://master-enterprise.demo.design.infor.com/components/accordion/example-disabled.html?theme=soho&variant=dark&colors=0066D4

**Comment by jbrcna** [comment]
verified in v4.32.0-dev. Thank you!
https://master-enterprise.demo.design.infor.com/components/accordion/example-disabled.html?theme=soho&variant=dark&colors=0066D4
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/56722184/89520558-9c34be00-d810-11ea-8120-749ece76cfcf.png">
