### ISSUE TITLE
Datagrid: Keyword Search not working when used with group headers

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#4068]
**Describe the bug**
Toolbar searchfield is not working when used with group headers in data grid

**To Reproduce**
1. Create data grid with group headers
2. implement toolbar with searchfield
3. observe serachfield has no effect on data grid

**Expected behavior**
Should work the same like without group headers

**Version**
- ids-enterprise-ng: 7.1.4

**Comment by jbrcna** [comment]
**QA Passed**
v.4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html
