### ISSUE TITLE
SOHO-7917: Datagrid - Editable field within a column with row-height = 'auto'

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#407]
The datagrid row is 'auto' since some of the columns will be wider as shown in the attachment. Due to this, when the 'Quantity' (which is an editable column) is selected for editing, it 'jumps' to the top margin of the row.. and once the cell loses focus, it comes back  to its correct place.

For  sample test case and screen shots see back on https://jira.infor.com/browse/SOHO-7917

**Comment by tmcconechy** [comment]
Can no longer reproduce this issue so descoping

**Comment by clepore** [comment]
Sounds good 👍 

(I totally forgot that all the tickets I transferred from Jira, are going to come to me 🍻)
