### ISSUE TITLE
Editor: Keyboard shift selection removes selection if you are not fast

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#4070]
**Describe the bug**
When you use hold shift and click the left arrow keys the text should be selected. this works if you are fast, but if you wait for a half second then it instead starts deselecting the end of the selection instead.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index.html'
2. Click the end of the last line in the editor
3. Hold the shift key
4. Press the left arrow key fast a few times => Selection is increased
5. Wait one second
6. Press the left arrow key again => Selection is decreased from the end

**Expected behavior**
I believe that the selection should continue to be increased in step 6, not decreased.

**Version**

- ids-enterprise: 4.28.0

**Screenshots**
Here is a gif where I hold Shift and press the left arrow key with different speed. Note I never release shift!
![NotesSelction](https://user-images.githubusercontent.com/8664975/85387318-f7527000-b544-11ea-9cbc-a07f0a5bde6f.gif)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 83.0.4103.106 (Official Build) (64-bit)

**Additional context**
-

**Comment by tmcconechy** [comment]
Having a tough time reproducing what your showing in the screen shot. As far as i can see we dont do anything with the cursor here so not sure if we can fix this. Or do we @deep7102 ? Any thoughts?

**Comment by deep7102** [comment]
I can reproduce on win10 chrome v83.0.4103.116, It looks bug somepoint in our selection logic.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
