### ISSUE TITLE
'Spanish (Mexico)' is not localised in Thai. Ming.le > User Settings > Localization Settings > Locale

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4071]
'Spanish (Mexico)' is not localised in Thai. Ming.le > User Settings > Localization Settings > Locale

![Mexican](https://user-images.githubusercontent.com/66057969/85394293-a3e51f80-b54e-11ea-80ff-e89ee9b10d60.png)

**Comment by tmcconechy** [comment]
Please raise this one with the Mingle. Team. We dont own this translation as far as i can see. So this bug will have to live over there
