### ISSUE TITLE
Thai translation for 'Duplicate Widget': I (external contractor) would suggest using 'ทำสำเนาวิดเจ็ต' to better fit the context

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4072]
Thai translation for 'Duplicate Widget': I (external contractor) would suggest using 'ทำสำเนาวิดเจ็ต' to better fit the context

![Duplicate](https://user-images.githubusercontent.com/66057969/85395915-27a00b80-b551-11ea-8045-15cc698c4299.png)

**Comment by tmcconechy** [comment]
We do not own this translation. Please raise this with the application team? Is this homepages maybe?
