### ISSUE TITLE
Popover: Details is not loading in IE

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4073]
**Describe the bug**
Popover: Details is not loading in IE

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/popover/example-alternate-positions.html?theme=soho&variant=light&colors=2578a9
2. Minimize the screen 
3. Open the popover 
4. Maximize the screen 
5. Open the popover

**Expected behavior**
Popover details should load properly

**Version**
4.30.0 - dev 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/85396689-bd08c300-b584-11ea-8962-a2fa32268f1a.png)

**Platform**
All browser, OS and Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Strange one - Does not seem to be any errors

**Comment by tmcconechy** [comment]
Descoping this for now
