### ISSUE TITLE
Calendar: Able to set invalid time

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4074]
**Describe the bug**
user is able to input invalid time in `From` and `To` dates

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Create an event to open the `Add Event Modal`
3. In `From` date set time to 5:00 PM
4. In `To` date set time to 12:00 PM
5. See Error

**Expected behavior**
should not be able to set invalid time

**Version**
- ids-enterprise: [v4.30.0-dev]

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/85399845-10314480-b58a-11ea-930c-248aad0fecc2.png)

**Platform**
All browsers

**Additional context**
When you set an invalid date, it doesn't show the event details and it is labels negative. Also, it is labeled as Jul 14 - Aug 13 in `Upcoming` event.
![image](https://user-images.githubusercontent.com/56722184/85399983-4c64a500-b58a-11ea-8eb2-922a1817b142.png)
`From:` July 14
`To:` July 13

**Comment by tmcconechy** [comment]
This is the same issue as https://github.com/infor-design/enterprise/issues/2762 we need on that to add a way to not select dates and times with the from time before the to date
