### ISSUE TITLE
Datepicker/Mask: Editing dates results in odd modifications

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#4079]
**Describe the bug**
Editing a date causes a shift of all numbers into the left most value ignoring the date separator and makes editing dates confusing to the end user.

**To Reproduce**
1. Go to 'https://master-enterprise.demo.design.infor.com/components/mask/test-date-with-validation.html'
2. Enter 1/1/2020 into the Date Input field and tab out
3. Return to the Date Input field and place the insertion point to the right of the month; intention is to change 1/1/2020 to 1/2/2020
4. Use the backspace key to remove the month and then enter a 2
5. Value becomes 12/20/20

**Expected behavior**
Expected the date mask to honor the position of the date separators and expected the value to be 1/2/2020.

**Version**

- ids-enterprise: 4.28.1

**Screenshots**
![datepicker-editting](https://user-images.githubusercontent.com/20212079/85443096-81570480-b556-11ea-947d-6a21049a1eca.gif)

**Additional context**
Landmark JIRA ticket for this: https://jira.lawson.com/browse/LMCLIENT-25021

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-beta1
https://4330-beta1-enterprise.demo.design.infor.com/components/mask/test-date-with-validation.html
https://4330-beta1-enterprise.demo.design.infor.com/components/mask/example-index.html
