### ISSUE TITLE
Excel export: The excel exported from DataGrid with group have no data.

### ISSUE THREAD

**Issue by Roking** [infor-design/enterprise#4081]
**Describe the bug**
We have upgraded ids-enterprise to 4.28.0 and tried to export excel from datagrid with group, but the generated excel had no data, just a header. But if no group, the excel will have data.  Both are normal with data when using infor/sohoxi 4.5.0

**To Reproduce**
1. Access the example: [https://usspvwhvgmdemo:20493/ids-enterprise-ng-demo/](url)
2. Click on "D→DataGrid - Groups" on the left menu, and the page shows a table with group and data.
3. Click on the link "Export to Excel".
4. Open the exported excel, you can see it only includes group info and other data is missing. Please refer to the screenshots.

**Expected behavior**
The exported excel should include all data in the DataGrid.

**Version**

- ids-enterprise: [v4.28.0 or v4.29.0]

**Screenshots**
The DataGrid page:
![image](https://user-images.githubusercontent.com/4515605/85521778-58f30700-b637-11ea-8fcd-14eec8ce70ba.png)

The exported excel:
![image](https://user-images.githubusercontent.com/4515605/85521825-69a37d00-b637-11ea-9e65-c3fccbcc5428.png)

**Platform**
All

**Additional context**
DataGrid-groupable demo code:
[datagrid-groupable.demo.zip](https://github.com/infor-design/enterprise/files/4824610/datagrid-groupable.demo.zip)

**Comment by tmcconechy** [comment]
I've attached a more simple EP example that replicates the issue i will also push this. app/views/components/datagrid/test-grouping-export.html

```

<div class="row bottom-padding">
  <div class="twelve columns">
    <div class="toolbar" role="toolbar">
      <div class="title">
        Compressors
        <span class="datagrid-result-count">(10 Results)</span>
      </div>
      <div class="buttonset">
        <button type="button" class="btn" id="export-to-csv">
          <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
            <use href="#icon-export-spreadsheet"></use>
          </svg>
          <span>Export To Csv</span>
        </button>
        <button type="button" class="btn" id="export-to-excel">
          <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
            <use href="#icon-export-spreadsheet"></use>
          </svg>
          <span>Export To Excel</span>
        </button>
      </div>

      <div class="more">
        <button type="button" class="btn-actions">
          <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
            <use href="#icon-more"></use>
          </svg>
          <span class="audible">More Actions</span>
        </button>
        <ul class="popupmenu">
          <li><a data-option="personalize-columns" href="#">Personalize Columns</a></li>
          <li><a data-option="reset-layout" href="#">Reset to Default</a></li>
          <li class="separator"></li>
          <li class="heading">Row Height</li>
          <li class="is-selectable"><a data-option="row-short" href="#">Short</a></li>
          <li class="is-selectable"><a data-option="row-medium" href="#">Medium</a></li>
          <li class="is-selectable is-checked"><a data-option="row-normal" href="#">Normal</a></li>
        </ul>
      </div>
    </div>
    <div id="datagrid">
    </div>
  </div>
</div>


<script>
  $('body').one('initialized', function () {
    var grid,
      columns = [],
      data = [];

    //Define Columns for the Grid.
    columns.push({ id: 'drilldown', name: '', field: '', resizable: false, formatter: Formatters.Drilldown, click: function(e, args) {
      console.log('Drilldown ', args[0]);
    }, align: 'center', sortable: false});
    columns.push({ id: 'id', name: 'Customer Id', field: 'id'});
    columns.push({ id: 'type', name: 'Type', field: 'type'});
    columns.push({ id: 'location', name: 'Location', field: 'location', formatter: Formatters.Hyperlink});
    columns.push({ id: 'firstname', name: 'First Name', field: 'firstname'});
    columns.push({ id: 'lastname', name: 'Last Name', field: 'lastname'});
    columns.push({ id: 'phone', name: 'Phone', field: 'phone'});
    columns.push({ id: 'purchases', name: 'Purchases', field: 'purchases'});

    //Get some data via ajax
    var url = '{{basepath}}api/accounts';

    $.getJSON(url, function(res) {
      grid = $('#datagrid').datagrid({
        columns: columns,
        dataset: res,
        groupable: {
          fields: ['type'],
          expanded: true
        },
        toolbar: {title: 'Accounts', results: true, personalize: true, actions: true, rowHeight: true, keywordFilter: false}
      });
    });
    $('#export-to-csv').on('click', function () {
      grid.data('datagrid').exportToCsv('myExport');
    });
    $('#export-to-excel').on('click', function () {
      grid.data('datagrid').exportToExcel('myExport');
    });
  });
</script>

```

**Comment by janahintal** [comment]
QA Passed. Thank you. :) 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-grouping-export.html
![image](https://user-images.githubusercontent.com/45757016/87778537-f10e9580-c85d-11ea-9a1d-88adae417af6.png)

**Comment by GauravJags** [comment]
Hi,

My project is created using Odin CLI version 2.2.1
I am not sure about the steps that needs to be performed so that i can use the latest changes done in the above fix.

Thanks,

Regards,

**Comment by tmcconechy** [comment]
You might have to ask the Odin developers. We don't maintain that repo. Does it have a git or oxford repo?

My guess which would be normal is update ids-enterprise in the `package.json` to the latest version
