### ISSUE TITLE
Calendar:  Overlapping events misalignment issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4082]
**Describe the bug**
If events span across days and their start and finish intersect, then the event listed in `+1 More` will display broken across the days that have no other events created.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Create an event on June 23 with a 1-day duration
3. It seemed to work just fine.
4. Create another event on June 23 with a 1-day duration
5.  It seemed to work just fine.
6. Create another event on June 23 with a 3-day duration
7.  It seemed to work just fine.
8. Create another event on June 23 with a 4-day duration
9. See error
10. It breaks apart the line for the 4th event

**Expected behavior**
as each date spans the next it will stay in the same position within the container

**Version**
Master
- ids-enterprise: [v4.30.0-dev]

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/85550362-7766fb80-b653-11ea-92a0-3cb0e6b1dbd2.png)

**Platform**
All browsers

**Additional context**
This issue is related to https://github.com/infor-design/enterprise/issues/1725

Also please see the below issue. Let me know if I should file a separate issue for this
![Large GIF (1180x562)](https://user-images.githubusercontent.com/56722184/85549900-03c4ee80-b653-11ea-9a42-e62edfba7031.gif)

**Comment by tmcconechy** [comment]
Descoping this for now
