### ISSUE TITLE
SOHO-7806: Modal dialog beforeShow callback function when a component is hosted

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#409]
**Original Issue:** https://jira.infor.com/browse/SOHO-7806

A component is dynamically created and hosted in a modal dialog after data is retrieved. In the response function of beforeShow callback, passing false does not open the dialog. Passing empty string, empties the dialog content. Looking for an ability to show the dialog when no content is passed in.

---

Important context from @pwpatton:

> The issue is that an angular component used with ours modals gets build when angular sees the markup for the component. So what happens today is the modal shows small, the angular element is recognized and the angular component is constructed. This causes the modal to resize between when it first came up and when it's content settled.
> 
> Then idea of the beforeShow is that we can hide the modal, instantiate the angular component and render it (hidden) before calling the beforeShow() callback. When that callback is called then the modal should animate to it's settled size and position.

**Comment by tmcconechy** [comment]
All needs to be done is make `response(true);` still open the modal.
