### ISSUE TITLE
Breadcrumb: Truncate "hidden" items, display important items

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#4091]
**Is your feature request related to a problem or use case? Please describe.**
A design enhancement to the IDS Breadcrumb has been requested with the following requirements:

>  The breadcrumb UI pattern is widely used and effectively gives the user an overview of where she is in a given navigation path. It also provides a simple way to navigate to previous states or pages. Today there are css classes in IDS that can be used to create breadcrumbs, but there is no component with clear examples and the current breadcrumb implementation is lacking two important features.
> - Correct truncation.
> - Possibility to see truncated parts of the breadcrumb path
> ...
> - Breadcrumbs should be truncated when they don't fit on the screen and the lowest level breadcrumb should always be visible. Today it's the first thing that disappears.
> - It should be possible to view and click parts of the breadcrumbs that has been truncated, so the user can navigate to that state. One example of this is the file system navigation bar on most computer operating systems.

After working through trying to implement these requirements into the current design, I've discovered the following pitfalls that need some design guidance:

- Our current breadcrumb design had only anticipated a handful of breadcrumb items being present at once, and never implemented "truncation" in the way this request is expecting.  Currently the line of breadcrumbs will wrap to a second line if it gets long enough.
- If we squish down the size of the breadcrumbs to a single line, and allow for expanding the size of "important" ones, we need to make design decisions on things like:
    - how many breadcrumbs should ever be visually present at once on a single line?
    - do we ever "throw away" any breadcrumbs on the line?
    - does clicking a breadcrumb automatically expand it?
    - should we have the standard "show truncated text in a tooltip" design pattern for breadcrumb items?  

**Additional context**
Originally listed as a requirement in infor-design/enterprise-ng#700, per @gushanson's request

**Examples**
<img width="306" alt="Screen Shot 2020-07-07 at 4 41 24 PM" src="https://user-images.githubusercontent.com/814283/86845125-083bcf00-c077-11ea-962f-fdb10b0e8a71.png">
<img width="1368" alt="Screen Shot 2020-07-07 at 4 41 15 PM" src="https://user-images.githubusercontent.com/814283/86845126-08d46580-c077-11ea-84d3-793dcbb06898.png">

**Comment by EdwardCoyle** [comment]
The work on the JS breadcrumb component has landed in `master`: https://master-enterprise.demo.design.infor.com/components/breadcrumb/example-add-remove.html can demonstrate the current scenario of what happens with too many breadcrumbs.

@inforandy is this something we could have design take a look at?

**Comment by tmcconechy** [comment]
Way way way back i talked with a designer and we decided to just make it flow like that to the next line. Dont think we need to get really fancy with it. But doesnt hurt to have a look

**Comment by EdwardCoyle** [comment]
Agreed, doesn't need to be fancy.  They specifically asked for truncation as a feature though, just wanted to make sure it gets some input.

**Comment by pwpatton** [comment]
@tmcconechy @EdwardCoyle so is this a way not to have wrapping overflow then?

**Comment by tmcconechy** [comment]
Yes, but TBD with design. Thats the use case exactly.

**Comment by pwpatton** [comment]
we also have desire to place this breadcrumbs control in a different area. 
- above the header bar (probably the best idea)
- within the headers eyebrow area (may not be feasible if we are placing the toolbar in header as well).

![image](https://user-images.githubusercontent.com/4737815/86945114-43d5a800-c10e-11ea-9967-3006582acb90.png)

**Comment by EdwardCoyle** [comment]
@tmcconechy @inforandy any idea if Design has had a chance to address this?

**Comment by tmcconechy** [comment]
Pretty sure not. Lets move this out for now.

**Comment by tmcconechy** [comment]
cc @inforandy

**Comment by janahintal** [comment]
Hi @tmcconechy, here's my observation upon testing. Would like to know if it is expected. Thank you. 

1.  '...' navigation button to select a Breadcrumb is not working
Link: https://master-enterprise.demo.design.infor.com/components/breadcrumb/example-navigation-breadcrumbs.html#
*Expected: When I select Pattern Test, It would show the breadcrumb selected. 
![image](https://user-images.githubusercontent.com/45757016/91839922-728d7c00-ec82-11ea-8501-3c2b5b2bd6e9.png)

**Comment by tmcconechy** [comment]
Yes @janahintal that is expected. As the order does not change of the bread crumb items in this example. It is always the same order unless the developer changes pages for real where it would change. Its a link that does nothing at this time. So that behavior is expected

**Comment by EdwardCoyle** [comment]
@janahintal Much of the breadcrumb behavior has been intentionally left to the app developers, since there isn't a very clear "spec" on what the selected action will be.

**Comment by janahintal** [comment]
Noted on this. Thank you for the confirmation. Will now move the ticket to Done. 👍
