### ISSUE TITLE
LookUp: Unnecessary scroll bar

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4094]
**Describe the bug**
There is an unnecessary scroll bar when you change the number of records per page

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/lookup/example-paging.html?
2. Click on `5 Records per page` then switch to `10 Records per page`
3. See error
4. Notice that there is a horizontal scroll bar present even though there is enough space.

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/85855653-2a1c9280-b7e9-11ea-87ec-a10e51c4b4bf.png)

**Version**
- ids-enterprise: [v4.30.0-dev]

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/85855674-356fbe00-b7e9-11ea-8af0-38e3428d1178.png)

**Platform**
`Mac Safari`

**Additional context**
https://master-enterprise.demo.design.infor.com/components/lookup/example-clientside-paging-with-filtering.html

**Comment by tmcconechy** [comment]
Descoping this for now
