### ISSUE TITLE
Tooltip: Add setting to show tooltip only when content is too long

### ISSUE THREAD

**Issue by edgarinfor** [infor-design/enterprise#4096]
**Is your feature request related to a problem? Please describe.**
Our applications use tooltips to show the full text on labels that are too long to display in place and have to be truncated (overflow: hidden) with an ellipsis.

On several occasions, BAs have requested that the tooltips should **NOT** appear if the text is not truncated (no ellipsis) to avoid unnecessary distractions when the users are working on the application since some of our screens are very data dense and complex.

**Describe the solution you'd like**
We would like a new setting on the Tooltip directive (e.g., **overflowOnly**) to enable an additional check so the tooltip only shows if the content element width overflows.

Please note that, too keep things simple, this solution should assume that proper CSS styling has been applied on the page so, the directive doesn't have to deal with unpredictable formatting.

**Describe alternatives you've considered**
There are several approaches to this (which we have tried) but, they all appear to be too "hacky" since they have to be done outside the Tooltip directive and then try to update the tooltip content dynamically.

We have done some research and, it appears that using the following logic allows to easily check if the content is "overflowing":
`this.elementRef.nativeElement.offsetWidth < this.elementRef.nativeElement.scrollWidth`

(You may find this on several Google results as well as this appear to be a common requested feature)

**Additional context**
We created a custom **AutoTooltipDirective** that essentially initializes the **SohoTooltipDirective** and does that calculation, we have attached it for reference.
[auto-tooltip.directive.txt](https://github.com/infor-design/enterprise-ng/files/4837820/auto-tooltip.directive.txt)

This is an example of the idea (notice that this is not a SoHo grid, it is a standard table styled like a grid):
![smart_tooltip_1](https://user-images.githubusercontent.com/39097500/85874741-1cdbb580-b7a1-11ea-93e0-5641e51acf08.png)

![smart_tooltip_2](https://user-images.githubusercontent.com/39097500/85874743-1cdbb580-b7a1-11ea-937d-f3e772d839f4.png)

**Comment by tmcconechy** [comment]
We might want to add this in the future tooltip refactor. But we already have this feature built in to the datagrid itself. See example https://master-enterprise.demo.design.infor.com/components/datagrid/test-ellipsis-header-align.html

`textOverflow": "ellipsis"` -> on the column
`enableTooltips: true,` -> to show tooltips when it is

**Comment by edgarinfor** [comment]
Hi, Tim, thanks for the info! :) 
As you said, we can definitely work around it for now since we also need the feature in other places **outside** datagrids.
I'll keep a reference to this because, it would be really helpful to have it as a general feature.

**Comment by tmcconechy** [comment]
Yeah we worked it into places instead as of now. But i think given a look back we probably should have done it as a general feature

**Comment by tmcconechy** [comment]
The new web component can now do this https://github.com/infor-design/enterprise-wc/blob/main/app/ids-tooltip/test-sandbox.html#L87

**Comment by edgarinfor** [comment]
@tmcconechy, are you deprecating and eventually dropping support for the Angular wrappers already?

If not, I don't think that solving issues in the web-components package should be a reason to ignore the other packages because that alone doesn't help us.

We won't be able to switch to the WC for a long time and, if the Angular wrappers are coming to an EOL soon, we should be considering a significant development effort on our end.

**Comment by tmcconechy** [comment]
I do understand that. We aren't deprecating and dropping support for the wrappers. And we will fix issues.
It's just that this issue is fixed in the new component and its very difficult to add to the old component. If it was easy we would do it in both. For example its sort of a case by case issue thing if it requires a significant / breaking change we do it in the new ones.

Also you could probably use the ids-tooltip side by side with the old components maybe sooner than you think

**Comment by tmcconechy** [comment]
Actually looking again. This is actually fixed / working. Sorry i missed that. Check out this example:

https://main-enterprise.demo.design.infor.com/components/datagrid/test-ellipsis.html
- then resize the columns until an ellipsis is shown.

![Screen Shot 2021-05-13 at 11 50 03 AM](https://user-images.githubusercontent.com/814283/118151214-634df900-b3e1-11eb-92a2-a074ffede4e2.png)

So this does work on the grid just not "any" element which does work in the new stuff. To do it on the grid you just need to add `textOverflow: 'ellipsis'` to the column definition and `enableTooltips: true,` to the datagrid settings.

**Comment by edgarinfor** [comment]
Yes, it is fixed on the **SoHo DataGrid** as you mentioned _long time ago_ but, we need this in other places **outside datagrids** probably even more. Actually, the screenshots that you see in the description aren't from a SoHo DataGrid but from a custom "table" that's been styled to look like it (for consistency) so, the fix doesn't work here neither.

I also understand your point but, unfortunately, I think that the approach that you are taking **favors one package over the other** and that doesn't really help us. If the Angular wrappers are still maintained, I don't think that it's fair to tell us to use (or wait for) something else and close this ticket as the issue that affects us isn't really solved.

I know that the WC are the future but, until then, it's very uncertain for us the amount of time, effort and limitations that switching to them or using them side by side with Angular could generate.

We are actively developing in Angular now so, we need an "official" statement explaining the direction that should be taken in general for existing issues (like this one) and new ones because we need to have clear expectations that we can present to our management as well.

**Comment by tmcconechy** [comment]
If this is badly needed you can let us know and we could try and add it in both. But the idea i had was you can slowly start using them side by side. Here is an example in this showing how you could use the new feature. You would just need to import the new IdsText component and use that to get overflow working with tooltip.

https://github.com/infor-design/enterprise-wc-examples/tree/master/angular-ids-wc
https://github.com/infor-design/enterprise-wc-examples/blob/master/angular-ids-wc/package.json#L14
https://github.com/infor-design/enterprise-wc-examples/blob/master/angular-ids-wc/src/app/app.component.html#L44
https://github.com/infor-design/enterprise-wc-examples/blob/master/angular-ids-wc/src/app/app.component.ts#L3

We are basically trying to find the right balance between the time between the new and old stuff. But we do need feedback like you need it badly and want it on the current NG examples so if you want to re-open this we can do that and take a look.
I wasn't sure on priority here.

But hoping we can try working some new things side by side...

**Comment by edgarinfor** [comment]
Well, my comments apply to pretty much any ticket that has been opened by the **WFM team**...

We are really pushing for development to consume the IDS library _as-is_ and avoid hacks or workarounds so, normally, when a ticket is opened for you it means that there's a business requirement and a development need for it. We understand that you have a lot on your plate and that's why for some things we don't push as _high priority_ but, when the tickets are being "closed" without a solution it triggers a concern.

In this particular case, the solution that you present with the WC is interesting. I wonder though, if you could use that "**ids-text**" as a "directive" as well? It seems that it works for **text blocks** but, for "title" attributes, the SoHo Tooltip works differently. Is that use case covered as well?

**Comment by tmcconechy** [comment]
I'm ok with "doing this twice" if required but my thinking was it was working and soon usable side by side. But we do have a lot of upcoming features to your team where we will be doing that so maybe this is a chance to look at side by side approaches here.

With the web component basically its a text custom element with overflow and tooltip (when its overflowed only) added. You can only use it in this way, but perhaps a directive would later be added. Also i decided to use tooltip not title because this way we don't have to worry about the browser tooltip interfering. So it is a "different" solution than the old one as this way we leverage web components and custom elements and have less "wrappers" to get out of sync and maintain. 

```
<ids-text overflow="ellipsis" tooltip="true">Some long text that is overflowing and long</ids-text>
```

There are some other tooltip usages but i was just showing the overflow text one.

1. In this case you have full control over the tooltip markup and linnk with a target https://github.com/infor-design/enterprise-wc/blob/main/app/ids-tooltip/example.html#L6-L7
2. In this case its a button with a tooltip property https://github.com/infor-design/enterprise-wc/blob/main/app/ids-tooltip/test-sandbox.html#L75 thinking you can just bind this property to your text so dont need really need directive to do anything with a ids-button
