### ISSUE TITLE
SOHO-7788: Selection icons in inverse popupmenu are too low contrast in high contrast theme

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#410]
The blue selection icons -- particularily single-select -- of an inverse popupmenu e.g. in the masthead are barely legible when using high contrast theme.

See https://jira.infor.com/browse/SOHO-7788 for screen shots and more info.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/masthead/test-different-button-types
Passed QA testing
