### ISSUE TITLE
Homepage: Allow optional Five column layout

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#4101]
**Is your feature request related to a problem or use case? Please describe.**
On a high-resolution screen, a four column Homepage layout leaves a lot of screen estate unused. 

**Describe the solution you'd like**
Allow a Homepage to span five columns, to make use of the available width. If there isn't enough space, automatically shrink to a four column layout (same as today where it changes to three etc.) 

**Additional context**
Below is a screenshot of how a five column Homepage would look:
![Homepage (5 columns)](https://user-images.githubusercontent.com/1101770/86000111-5fa1c580-ba0d-11ea-9110-d3f856213321.png)

Application: Ming.le Homepages

**Comment by tmcconechy** [comment]
Can you look at this one @deep7102  maybe next?

**Comment by janahintal** [comment]
QA Passed on my end. 
Verified in https://4320-beta0-enterprise.demo.design.infor.com/components/homepage/example-five-column.html

100% 
![image](https://user-images.githubusercontent.com/45757016/91973912-94086980-ed4f-11ea-81f3-1d81c9396bbf.png)

67%
![image](https://user-images.githubusercontent.com/45757016/91973883-89e66b00-ed4f-11ea-8755-d2a34d273387.png)
