### ISSUE TITLE
Sign In Component – Line height to tight

### ISSUE THREAD

**Issue by jamie-norman** [infor-design/enterprise#4111]
**Describe the bug**
Line height for the "application name" is too tight
**To Reproduce**
Visit
- https://design.infor.com/code/ids-enterprise/latest/signin
- https://design.infor.com/code/ids-enterprise/latest/demo/components/signin/example-index?theme=uplift&variant=light
Notice that the leading on "Application Name" is very tight, causing overlap 

**Expected behavior**
Adequate/auto spacing between lines of text

**Additional context**
Various Infor security teams using template, so would rather not have multiple teams writing overrides 

![image](https://user-images.githubusercontent.com/44705854/86390571-eb119580-bc5d-11ea-9e9d-fa4970bc17e7.png)

**Comment by janahintal** [comment]
This issue is now resolved. 
Thanks! 
![image](https://user-images.githubusercontent.com/45757016/87296137-e3dd6800-c538-11ea-989d-da19d3da7eb2.png)
