### ISSUE TITLE
CAP: Need to click close twice if dropdown is shown

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#4112]
**Describe the bug**
I am not certain if this is a bug or by design. The issue is that when a dropdown is open i need to click the Close button twice to close a contextual action panel. 

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html 
2. Click on the Ship Tems dropdown
3. Click Close in the CAP => Closes the dropdown, but not the contextual action panel
4. Click Close in the CAP again => Contextual action panel is closed

**Expected behavior**
I am not certain, but I think the first click on the Close button should close both the dropdown and the Contextual action panel.

**Version**

- ids-enterprise: 4.28.0

**Screenshots**
![CloseCapIssue](https://user-images.githubusercontent.com/8664975/86392857-6b56eb80-bc9c-11ea-8656-6b7dfe9df7b8.gif)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**
For us this issue appears in the header of a contextual action panel where a filter menu is opened. We also have another opposite issue with the same filter menu button where the menu isn't closed when we click one of the other buttons in the contextual action panel but it closes when all other buttons are pressed.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you 👍
