### ISSUE TITLE
Tooltip: is not working in windows 10 IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4117]
**Describe the bug**
Tooltip: is not working in windows 10 IE11

**To Reproduce**
1. Go to https://4300-rc0-enterprise.demo.design.infor.com/components/tooltip/example-index.html
2. Click te button to show the tooltip

**Expected behavior**
Tooltip should show up

**Version**
4.30.0 rc0

**Screenshots**
N/a

**Platform**
Windows 10 
IE11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
I fixed https://github.com/infor-design/enterprise/issues/4116 and https://github.com/infor-design/enterprise/issues/4116 but could not 100% reproduce this. I assume the issue was on page https://4300-rc0-enterprise.demo.design.infor.com

Also in this example you hover not click the button

**Comment by janahintal** [comment]
This issue is now resolved. Thank you :)
Verified in https://4300-rc1-enterprise.demo.design.infor.com/
![image](https://user-images.githubusercontent.com/45757016/86733460-cbb2a800-c063-11ea-9193-6b48fa1ba577.png)
