### ISSUE TITLE
Popover: View More button loses focus when you open the Popover more that one

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#4119]
**Describe the bug**
Popover Component: View More button loses focus when you open the Popover more that one

**To Reproduce**
1. Go to url: https://4300-rc0-enterprise.demo.design.infor.com/components/popover/example-index.html
2. Click on "Click To Show Popover" then Click on "View More" button then click on the "X" button
3. Click again on "Click To Show Popover" then Click on "View More" button
4. See error is the "View More" button no longer has focus when the user clicks on it

**Expected behavior**
There should be focus on the "View More" button each time the user opens the Popover.

**Version**

- ids-enterprise: [v4.30.0]

**Screenshots**
<img width="1303" alt="Popover View More Button Issue" src="https://user-images.githubusercontent.com/39101346/86606020-713b1e00-bf75-11ea-9ddb-3b101638d06a.png">

**Platform**
 - OS Version: [e.g. Windows 10 or iOS 8]
 - All Browser 

**Additional context**
None

**Comment by tmcconechy** [comment]
Descoping this for now
