### ISSUE TITLE
SOHO-7730: Tree datagrid issue with row activation

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#412]
With a mixed selectable grid option, there is an intermittent issue that exists were occasionally clicking on a row does not also make the row visually active (does not add the class 'is-rowactivated' to the tr element).

Click on the rows of the tree grid and eventually the issue occurs.  This is a problem for landmark in that we have a dependent child grid that is updated when the row click occurs on the parent grid.  There is a visual disconnect in that the active row of the parent grid will now not match what is being displayed in the dependent child grid. 

Seeing this in the angular-components.  

I've attached the following:
datagrid-treegrid.demo.html
datagrid-treegrid.demo.ts

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-tree-row-activated.html
http://4120-beta0-enterprise.demo.design.infor.com/components/datagrid/test-tree-row-activated.html

There is an intermittent scenario where the selected rows are not visually selected.
Try selecting downwards from ID 1 to ID 10, then select upwards. See video below.
![treedatagrid](https://user-images.githubusercontent.com/39508864/47354934-a399de80-d6f2-11e8-897b-167fc9167b0d.gif)

**Comment by tmcconechy** [comment]
@deep7102 Can you adjust for this case?
