### ISSUE TITLE
Modal: close-btn moves a little when hover

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4124]
**Describe the bug**
when you hover over the `x` button it moves a little

**To Reproduce**
1. Go to https://4300-rc1-enterprise.demo.design.infor.com/components/modal/example-close-btn.html?theme=uplift&variant=light&colors=0066D4
2. Click on `Show Modal `button
3. Hover over the `x` button on the right
4. See error, Notice that the `x` button moves a little

**Expected behavior**

**Version**
- ids-enterprise: [v4.30.0-rc0 & v4.30.0-rc1]

**Screenshots**
![Large GIF (746x628)](https://user-images.githubusercontent.com/56722184/86923930-52997a80-c161-11ea-8bcc-bb589c73d4ef.gif)

**Platform**
All

**Additional context**
If in case it does not replicate on the first try, close the modal and repeat the steps above. Sometimes it won't move on the first try (hover)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
