### ISSUE TITLE
SOHO-7701: Stepprocess: Next and Previous buttons should be showing on the left when viewing a Step Control / Step Process in Right To Left.

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#413]
When viewing a Step Control / Step Process pattern in Right to Left the Next and Previous buttons should be showing on the Left side of the screen. See screen shots. 

http://localhost:4000/patterns/stepprocess.html?locale=ar-SA

This was SOHO-7701

**Comment by brianjuan** [comment]
http://localhost:4000/patterns/stepprocess.html?locale=ar-SA
http://master-enterprise.demo.design.infor.com/patterns/stepprocess.html?locale=ar-SA
Passed QA testing on all browsers. Will test again once beta is deployed.
