### ISSUE TITLE
Datepicker: Arabic/Gregorian failing after initial selection

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise#4130]
**Describe the bug**
There is an issue regarding the Datepicker with arabic/gregorian scenario. When a user selects a date, the date picker is not showing after the initial date selection.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datepicker/test-ar-sa-gregorian.html
2. Select a date
3. Try to re-open the Datepicker
4. Datepicker does not open and there is an error in the console. See Screenshot below

**Expected behavior**
User should be able to continue to use the Datepicker after the initial selection.

**Version**

- ids-enterprise: [v4.30.0]

**Screenshots**
![Screen Shot 2020-07-09 at 9 06 21 AM](https://user-images.githubusercontent.com/1084735/87043711-7beaf280-c1c3-11ea-9a39-020162f7321e.png)

**Platform**
 - All

**Additional context**
n/a

**Comment by jbrcna** [comment]
**QA Passed** with observation
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/datepicker/test-ar-sa-gregorian.html
![image](https://user-images.githubusercontent.com/56722184/87769186-d8977e80-c84f-11ea-9318-dae21ca8790a.png)

**_Observation_**
Device: Android
![image](https://user-images.githubusercontent.com/56722184/87771269-b6533000-c852-11ea-8f06-5b2f99a7f9f9.png)
1. Open Picker
2. Select a Date
3. Press escape
4. Open picker again and select another date
