### ISSUE TITLE
Modal: Lots warnings in console due to use of css width: fill-available

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#4133]
**Describe the bug**
In landmark we pull in the soho/ep css into our own scss theming files. When running ngserve it causes a check on these scss files that complains about the use of `fill-available` in the imported soho/ep css. 

The recommendation is to change `fill-available` to `stretch`

```
WARNING in ./src/assets/themes/light-theme.css (./node_modules/css-loader/dist/cjs.js??ref--12-1!./node_modules/postcss-loader/src??embedded!./src/assets/themes/light-theme.css)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning
(25079:3) Replace fill-available to stretch, because spec had been changed
```
Github discussion on this issue
https://github.com/postcss/autoprefixer/issues/1035

CanIUse of stretch
https://caniuse.com/#feat=mdn-css_properties_width_stretch

**To Reproduce**

**Expected behavior**

**Version**
EPNG 7.4 / EP 4.30

**Platform**
 - Landmark
 - Latest chrome
 - windows 10

**Additional context**

**Comment by tmcconechy** [comment]
Tested this with phillip its due to width: fill-available not being a real thing and using a https://webpack.js.org/loaders/postcss-loader/ with https://github.com/postcss/autoprefixer

Fix is this:

```
.modal table {
  width: 300px;
  width: -moz-available;
  width: -webkit-fill-available;
  width: stretch; }
.modal .paginated table {
  width: 466px;
  width: -moz-available;
  width: -webkit-fill-available;
  width: stretch; }
```

But should retest the original issue. I will fix this and PR with tests.

**Comment by pwpatton** [comment]
Need patched in 4.30

**Comment by tmcconechy** [comment]
We can patch this but lets wait until absolutely needed or one more issue to patch. If this gets too annoying in the next couple of days just let me know.

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-search-form.html
https://master-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-two-columns.html
https://master-enterprise.demo.design.infor.com/components/datagrid/example-modal-datagrid.html
https://master-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-single-column.html
https://master-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-tooltips.html
