### ISSUE TITLE
Icon: 'remove-user' icon was removed. Could we add it back in this version

### ISSUE THREAD

**Issue by James063** [infor-design/enterprise#4137]
'remove-user' icon was removed. Could we add it back in this version

**Comment by tmcconechy** [comment]
I looked in 3.6 and 4.0 and no history of any remove-user. What does the functionality do? Sounds like deleting a user. If so i would use a delete icon as this is more historically well known to users.

**Comment by tmcconechy** [comment]
Closing as we cannot find any history of this icon. But if you do want to request a new icon let me know the details of this icon
