### ISSUE TITLE
Multiselect: Display as tag with compact layout css looks bad

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#4139]
**Describe the bug**
A multiselect field with show as tags enabled looks terrible in compact layout

**To Reproduce**
1. Copy [example-compact-layout.zip](https://github.com/infor-design/enterprise/files/4904828/example-compact-layout.zip) into /app/views/components/multiselect
2. Navigate to '/components/multiselect/example-index.html'
3. The multiselect with tags is ugly
4. Change to vibrant theme from subtle theme, css is still ugly

**Expected behavior**
The fields should look good. Consistent spacing and no extra scroll bars.

**Version**

- ids-enterprise: v4.31.0-dev

**Screenshots**
Vibrant:
![image](https://user-images.githubusercontent.com/22107636/87187908-8dabc300-c2b3-11ea-808e-ac1cb14e6bfb.png)

Subtle: 
![image](https://user-images.githubusercontent.com/22107636/87187939-98665800-c2b3-11ea-9d22-ed07e80477b1.png)

**Platform**
 - All

**Additional context**
Landmark would like this for it's Oct release.

**Comment by jbrcna** [comment]
**QA Failed**
The down arrow is displaced when compact mode is used
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/multiselect/example-compact.html
![image](https://user-images.githubusercontent.com/56722184/88024959-279e2600-cb66-11ea-80b8-03ed69ba9d30.png)

**iOS**
![image](https://user-images.githubusercontent.com/56722184/88026389-62a15900-cb68-11ea-9e96-0b6b32f6a436.png)

**Android**
![image](https://user-images.githubusercontent.com/56722184/88026508-8bc1e980-cb68-11ea-992e-8d33e6930eba.png)

**Comment by jmacaluso711** [comment]
@jbrcna Can you tell me which browsers and versions you were on for these?

**Comment by tmcconechy** [comment]
At least one screen shot looks like zoom might be activated ? Can you check that too @jbrcna ?

**Comment by jbrcna** [comment]
Hi @jmacaluso711 , @tmcconechy , The first screenshot was on `Safari`, Second one was on` iOS (iPhone 11 Pro - Safari)`, Third one was on` Android (Samsung Galaxy s20 - Firefox)` and Last one was on `Android Firefox` but  I didn't use zoom it was just cropped. 
the test was conducted on master v4.31.0-dev. The issue can also be replicated on any browsers. Thank you.

**Comment by janahintal** [comment]
This Issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/multiselect/example-compact.html?theme=soho&variant=contrast&colors=003876 

![image](https://user-images.githubusercontent.com/45757016/88528077-bad8cf00-d030-11ea-80d1-b1936a13a7e5.png)
