### ISSUE TITLE
Datagrid: Last row does not have a border 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4140]
**Describe the bug**
If the number of rows is less than what fits in the grid area the last row is missing a border.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-filter.html
2. Filter on '214220'
3. See error that the last row has no border

**Expected behavior**
Should have a border.

**Version**
- ids-enterprise: [e.g. v4.30]

**Screenshots**
![Screen Shot 2020-07-13 at 9 51 22 AM](https://user-images.githubusercontent.com/814283/87312351-6e4caa00-c4ee-11ea-88f6-7e293dd18bca.png)

**Platform**
 - Chrome

**Additional context**
TJM: I removed this i missed this case and was trying to remove the double border on the bottom. I need to check this again for this case.

**Comment by tmcconechy** [comment]
Pushed this to 4.30.x so fix is coming around soon.

**Comment by tmcconechy** [comment]
Steps to test:
http://localhost:4000/components/datagrid/test-fixed-header-filter.html

- filter on 214220
- should see a bottom border on the one row

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-fixed-header-filter.html
![image](https://user-images.githubusercontent.com/56722184/87909946-c14cd100-ca9b-11ea-8bf9-3338fe04d455.png)
