### ISSUE TITLE
Personalization: There is no event trigger for setColorsToDefault()

### ISSUE THREAD

**Issue by zzhblh** [infor-design/enterprise#4144]
**Describe the bug**
When you call the setcolors() function, it will fire the trigger handler 'colorschanged'. But there is no trigger for setColorsToDefault() function.

**To Reproduce**
1. Choose a color for personalization.
2. Fire the trigger handler 'colorschanged'.
3. Set to default color.
4. Have no trigger.

**Expected behavior**
Fire the trigger handler 'colorschanged' when call the setColorsToDefault() function.

**Version**

- ids-enterprise: [v4.26.2]

**Screenshots**
None.

**Platform**
 - OS Version: [Windows 10]
 - All Browser

**Additional context**
None.

**Comment by jmacaluso711** [comment]
@tmcconechy @Gboog This seems to have been addressed as it looks to be working correctly in master

https://master-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html

![Screen Shot 2020-08-10 at 2 37 49 PM](https://user-images.githubusercontent.com/1084735/89818081-3483b900-db17-11ea-8fa3-6428d3e95150.png)

**Comment by tmcconechy** [comment]
Yeah your right. Looks like i fixed it on this PR https://github.com/infor-design/enterprise/pull/3573
Closing then as dup
