### ISSUE TITLE
Accordion: Tree view display as black point when theme is Vibrant

### ISSUE THREAD

**Issue by zzhblh** [infor-design/enterprise#4145]
**Describe the bug**
Tree view display as black point when theme is Vibrant.

**To Reproduce**
1. Change theme to Vibrant
2. Tree view display as black point

**Expected behavior**
Node name should list. The display is correct when theme is Subtle. See the screenshots.
Changing the font size of _.accordion-pane .accordion-header.list-item::before {...}_  from 1.6rem to 1.2rem in theme-uplift-*.css can solve this problem

**Version**

- ids-enterprise: [v4.26.2]

**Screenshots**
Display as black point when theme is Vibrant:
![image](https://user-images.githubusercontent.com/8154831/87378921-92c58680-c5c1-11ea-899e-9b556c16849d.png)

Display is correct when theme is Subtle:
![image](https://user-images.githubusercontent.com/8154831/87379020-d6b88b80-c5c1-11ea-86a3-098035e2f179.png)

**Platform**
 - OS Version: [Windows 10]
 - All Browser

**Additional context**
None.

**Comment by tmcconechy** [comment]
I know there was a seperate bug here that was fixed. But i cant find it @EdwardCoyle ? @ericangeles 
Just wanted to link it.

But this was fixed so please try the latest?

**Comment by EdwardCoyle** [comment]
I see this one was closed.  I can't find the original issue either, but I double checked some samples and I believe that we fixed this in App Menu, but not Accordion.  Navigate a few levels deep on either accordion in https://master-enterprise.demo.design.infor.com/components/accordion/test-six-levels-deep.html?theme=uplift&variant=light&colors=0066D4

![Screen Shot 2020-07-14 at 4 25 07 PM](https://user-images.githubusercontent.com/3249601/87472882-a89d7080-c5ee-11ea-9b23-403a00398287.png)

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/accordion/test-six-levels-deep.html?theme=uplift&variant=dark&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/91161885-f03f0e00-e6fd-11ea-9bbe-34d1ffeb813c.png)
