### ISSUE TITLE
ColorPicker: Custom Label Loosing Value in some situations

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4146]
Hi, I just want to report the behavior of color picker,  https://master-enterprise.demo.design.infor.com/components/colorpicker/example-custom-labels.html

**To Reproduce**
Step 1: Select custom color
Step 2: Select custom label
Step 3: Open custom label dropdown field but don't select anything
Step 4: Open custom color dropdown field select any color. 
           Expected: selection will changed
           Actual: Selection is set to none

**Expected behavior**
Expected: selection will changed on custom label dropdown

**Version**

- ids-enterprise: [data-sohoxi-version="4.31.0-dev"]

**Screenshots**
![color picker custom label odd behavior](https://user-images.githubusercontent.com/50192038/87384622-cf4baf00-c5ce-11ea-9438-06cea2a84a41.gif)

**Platform**
 - OS Version: [Windows 10]
 - Browser Name: [Chrome]
 - Browser Version: [Version 83.0.4103.116 (Official Build) (64-bit)]

**Comment by jbrcna** [comment]
**QA Passed**
v4.35.0-dev
https://master-enterprise.demo.design.infor.com/components/colorpicker/example-custom-labels.html
