### ISSUE TITLE
Icons: Not working on Safari and Chrome (IOS 12.x)

### ISSUE THREAD

**Issue by raymondfrancisco** [infor-design/enterprise#4147]
**Describe the bug**
Icons are not visible when running under IOS 12.x for both Safari and Chrome browser.
Tested in version 4.27.4 and the latest both are not working.
The older version(4.20.1) works fine.

**To Reproduce**
- Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/icons/example-index?theme=uplift&variant=light

**Expected behavior**
 - Icons should be visible

**Version**
- ids-enterprise: 4.27.4

**Screenshots**
- Latest version
![latest](https://user-images.githubusercontent.com/8829002/87404863-45f9a400-c5f1-11ea-8bdf-ecdcd1db33f5.png)

- Older Version
![4 20 1](https://user-images.githubusercontent.com/8829002/87404878-4b56ee80-c5f1-11ea-9bde-b67a4c0dbd2c.png)

**Platform**
 - Infor Application/Team Name: Saleshub
 - Device: IPad
 - OS Version: IOS 12
 - Browser Name: chrome, safari

**Comment by tmcconechy** [comment]
This is a known issue. IOS 12 has problems with the way icons are being used however if you update to IOS 12.2 or newer it will work. They patched this fix.

We have no solutions for IOS 12 that work see https://github.com/infor-design/enterprise/issues/3637 for more details.
