### ISSUE TITLE
Autocomplete: Control throws JavaScript exception in IE11

### ISSUE THREAD

**Issue by rvaja-infor** [infor-design/enterprise#4148]
**Describe the bug**

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/autocomplete/example-index' in IE11
2. Enter 'a' into the input field
3. Open IE11 developer tools, and observe in the console the error message
`Object doesn't support property or method 'forEach'`
`autocomplete.js (438,7)`

**Expected behavior**
No exception is thrown in the console

**Version**
Latest 4.30.0 at time of raising

**Platform**
 - Browser Version: IE11

**Comment by tmcconechy** [comment]
Even tho we are dropping IE 11 this should be fixed until then.. https://github.com/infor-design/enterprise/issues/3756

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
