### ISSUE TITLE
Datagrid: Timepicker editor switches between AM and PM when set to 12:00

### ISSUE THREAD

**Issue by rgreinke** [infor-design/enterprise#4149]
**Describe the bug**
When entering a time of either 12:00 AM or 12:00 PM into a cell with a formatter of Formatters.Time and editor of Editors.Time, the cell redisplays the time, switching the AM or PM.  Underneath, the data is correct but the cell is showing the wrong time.  For example, look at the Filterable Datagrid example in the steps.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-filter?theme=uplift&variant=light
1. Try to enter a time in the time column of either 12 AM or 12 PM
1. See error -> Note that the cell flips the AM to PM and vice versa.

**Expected behavior**
Keeps the AM or PM entered.

**Version**
- ids-enterprise: [e.g. v4.30]

**Additional context**
Ms Teams

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift&variant=light&colors=0066D4
