### ISSUE TITLE
SOHO-7614: Mask is not working with Range Datepicker

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#415]
http://localhost:4000/components/field-filter/example-datepicker

- Click and choose “In-Range” option from field-filter dropdown
- Soon you type 3/15/2018, the caret is not placing end of the string
- Unable to type anymore until, move the caret manually to end of the string (ie. using cmd + right arrow key)

Relates to #357

**Comment by tmcconechy** [comment]
Closing this in favor of https://github.com/infor-design/enterprise/issues/3503

**Comment by tmcconechy** [comment]
Duplicate of #3503
