### ISSUE TITLE
Datagrid: Datepicker not visible in columns unless row height is 'short'

### ISSUE THREAD

**Issue by StaciGreen** [infor-design/enterprise#4151]
**Describe the bug**
After upgrading to 7.4.0 datepicker icon is not visible in columns.

**To Reproduce**

1. In ids-enterprise-ng-demo Go to 'DataGrid - Test Settings'
2. Click on 'Options ...' 
3. Uncheck Row Height Short
4. Date picker icon is no longer visible.
5. Go back to options and check Row height Short. Datepicker is now visible again.
 

**Expected behavior**
If column is setup for date filtering. the Date picker icon should be visible no matter row height setting.

**Version**
- ids-enterprise-ng: 7.4.0

**Screenshots**
Row Height short active:
![image](https://user-images.githubusercontent.com/50175666/87433745-aff55780-c5b7-11ea-90fd-3a336054c404.png)
Row Height short not active:
![image](https://user-images.githubusercontent.com/50175666/87434070-05c9ff80-c5b8-11ea-89b8-21465229cedd.png)

**Platform**
 - Device (if applicable) Windows Laptop
 - OS Version:  Windows 10
 - Browser Name  Chrome
 - Browser Version Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Pushed this to 4.30.x so fix is coming around soon.

**Comment by tmcconechy** [comment]
Steps to test:
http://localhost:4000/components/datagrid/example-filter.html?theme=uplift&variant=light&colors=0066D4
- try this on all 2 themes and 4 row heights
- the datepicker (and other pickers in the filter row) should be aligned

**Comment by StaciGreen** [comment]
Is there an estimate when the patch will be released?

**Comment by tmcconechy** [comment]
Hoping for today later on. Worst case Monday

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=uplift&variant=light&colors=0066D4
![image](https://user-images.githubusercontent.com/56722184/87911364-11c52e00-ca9e-11ea-8b3d-e752e4371150.png)
