### ISSUE TITLE
Datepicker: Inconsistent CSS in read only mode

### ISSUE THREAD

**Issue by StaciGreen** [infor-design/enterprise#4152]
**Describe the bug**
The datepicker icon is greyed out in readonly mode when not showing time, but is black when showing time.

**To Reproduce**
1. Edit datepicker.demo.html
2. Add the following input at bottom (copy of standard date with timepicker, setting readonly="true"
```
<div class="four columns">
    <div class="field">
      <label for="datetime" class="label">Standard Date with Timepicker (Current Time) Readonly</label>
      <input soho-datepicker id="datetime" name="datetime" readonly="true" dateFormat="MM/dd/yyyy" timeFormat="HH:mm:ss" showTime="true" useCurrentTime="true" mode="standard" placeholder="MM/dd/yyyy HH:mm:ss" [(ngModel)]="model.datetime" (change)="onChange($event)" class="input-mm"/>
    </div>
  </div>
```
3. Run demo app, and goto Date Picker demo
4. See difference between read only inputs with & without show time

**Expected behavior**
The css for the date picker icon should be consistent read-only = true, regardless of showTime.

**Version**
- ids-enterprise-ng: 7.4.0

**Screenshots**
![image](https://user-images.githubusercontent.com/50175666/87468103-f8783980-c5e6-11ea-9a3e-d0f09484c969.png)

**Platform**
 - Device (if applicable) Windows PC
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
This issue is the same as https://github.com/infor-design/enterprise/issues/3176 however it seems timepicker was missed. Its still a different color on 

https://master-enterprise.demo.design.infor.com/components/timepicker/test-states.html
vs
https://master-enterprise.demo.design.infor.com/components/datepicker/example-index

As described...

**Comment by jbrcna** [comment]
**QA Passed**
will retest once beta is deployed
v4.32.0-dev
https://master-enterprise.demo.design.infor.com/components/form/example-readonly-inputs.html
![image](https://user-images.githubusercontent.com/56722184/90127169-55f2d800-dd97-11ea-8eb4-ed320f2e2b29.png)

**Comment by jbrcna** [comment]
Retest Done. Test Passed
v4.32.0-beta0
https://4320-beta0-enterprise.demo.design.infor.com/components/form/example-readonly-inputs.html
