### ISSUE TITLE
Datagrid: Spacing Inconsistencies

### ISSUE THREAD

**Issue by kevinwhitedesign** [infor-design/enterprise#4154]
**Describe the bug**
I was looking at this https://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html?theme=uplift&variant=light&colors=0066D4

Discovered that cell padding was 21px on large size. We should move this onto the 8pt grid and use 24px for this padding.
<img width="1311" alt="Screenshot 2020-07-15 12 07 40" src="https://user-images.githubusercontent.com/6478704/87568545-d1c40c80-c693-11ea-878b-9a62da746f46.png">

I also found that medium was using 16px cell padding, and in places where text was right aligned - 21px padding.
<img width="1289" alt="Screenshot 2020-07-15 12 07 49" src="https://user-images.githubusercontent.com/6478704/87568674-06d05f00-c694-11ea-8df7-eb86e2e8a0df.png">

The small datagrid was using 11px, should we switch to 16px to be on the 8pt grid? (I guess 8px padding is another option here)
<img width="1428" alt="Screenshot 2020-07-15 15 15 28" src="https://user-images.githubusercontent.com/6478704/87586121-0fce2a00-c6ae-11ea-8205-401b45be4098.png">

The extra small datagrid was using 10px cell padding, but probably could be using 8px for the same reasons.
<img width="1283" alt="Screenshot 2020-07-15 16 32 24" src="https://user-images.githubusercontent.com/6478704/87593082-dea72700-c6b8-11ea-91e9-53124f98e008.png">

My designs on the left:
https://www.figma.com/file/4CtBGz8dwvSa6JsBcdtVZQ/Data-Grid?node-id=29%3A2

**Comment by tmcconechy** [comment]
I wouldn't increase the padding of anything. But we can change it to 4s... Maybe 4, 8, 16, 20 ?
Are you talking about header and cells? Or just header (we should make it the same think)

**Comment by kevinwhitedesign** [comment]
@tmcconechy Yeah I was hesitant to increase as well, as we know about existing issues with products, content, horizontal scrolling etc. I think for the large grid 24px does make sense, and only a 3px increase. For small, maybe we shouldn't go up to 16, but go down to 8. For extra small, I think 4px is not enough space, lets go 8 which is smaller than we currently have.

Yeah talking about column header & cell here. Should be the same otherwise reading might be harder if things are misaligned. 

Maybe you can shed more light on the filter example? Space between icon & field?

**Comment by tmcconechy** [comment]
I think its not a very good use of space on the larger grid... So take the filter: Do we align it at 24 pixels then we have to make the columns bigger to fit anything inside the inputs.

![Screen Shot 2020-07-16 at 9 54 27 AM](https://user-images.githubusercontent.com/814283/87679668-756ff400-c74a-11ea-890d-d0fa1f67fbc1.png)

![Screen Shot 2020-07-16 at 9 52 54 AM](https://user-images.githubusercontent.com/814283/87679732-87519700-c74a-11ea-91eb-26d25f082552.png)

So two questions:
- do we align the filter stuff with the text or let it "overhang" the whole column
- give that we almost always get push back on too much space being should we consider reducing the padding now im thinking 20 wasnt a multiple of 4 so could be 16, 12, 8, 4 (think that makes sense)

I think the 24px padding rule (almost 48px per column) might make the larger grid unusable for a lot of columns.

**Comment by tmcconechy** [comment]
Oh, Also there are two other elements in the header a drag icon and a sort icon.

![Screen Shot 2020-07-16 at 10 03 36 AM](https://user-images.githubusercontent.com/814283/87680626-a866b780-c74b-11ea-93d2-de61262d6140.png)

Maybe some rule like:
- the drag icon is half way between the text and edge? Problem is it wont fit
- the sort icon is 4px or 8px from the end of the text?

**Comment by kevinwhitedesign** [comment]
I think we should lean on 8 as much as possible. I hear the spacious concerns. I think 4px can be the tiniest increment as exception. I would recommend 16, 16(medium is already 16), 8, 8(this is even smaller than current). 16 LRG,16 MED, 8 SML, 8 XSML.

Maybe with the above reco the filter stuff is less of an issue. I think we should keep cell/column cell padding left & right equal. If we have to break that though, do it on the 8pt system if possible. So lrg grid with 16px padding, if there needs to be more space for the filter field, have that extend to be 8px from the right. Although maybe we won't have to do that now.

For the icon before text, can we use 8pt? Like this? 
<img width="725" alt="Screenshot 2020-07-16 15 08 58" src="https://user-images.githubusercontent.com/6478704/87712209-58e9b100-c776-11ea-80a4-3262365b12f9.png">

**Comment by tmcconechy** [comment]
Ok thanks @kevinwhitedesign going to run with this and let you know if any further questions. I think this guidance should all work now.

**Comment by janahintal** [comment]
Hi Guys, noticed the following error upon testing the changes in 
https://master-enterprise.demo.design.infor.com/components/datagrid/test-empty-message-small.html?theme=uplift&variant=light&colors=0066D4

![image](https://user-images.githubusercontent.com/45757016/88782996-d672df80-d1c0-11ea-9ca7-d9d8d8bf21e0.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
