### ISSUE TITLE
Datagrid: Select all checkbox focus seems off in Mobile view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4158]
**Describe the bug**
Datagrid: Select all checkbox focus seems off in Mobile view

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Click on Select All Checkbox
3. See error

**Expected behavior**
There focus should look fine in select all checkbox when selected

**Version**
4.31.0 master 

**Screenshots**
![32D0E6BC-5A7C-4E16-B709-FFE7F47E898F](https://user-images.githubusercontent.com/45757016/87667803-8e55c500-c79d-11ea-9141-267335a589db.png)

**Platform**
Across all platforms. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
@janahintal what do you mean by mobile view? Im not 100% sure what this screen shot is? Device? Browser Stack?

**Comment by tmcconechy** [comment]
Any updates @janahintal ?

**Comment by tmcconechy** [comment]
Descoping this for now
