### ISSUE TITLE
Datepicker: setValue() should accept a string and to- and fromGregorian working inversely

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#4160]
**Describe the bug**
When calling setValue() with a value string formatted as MMdd in umalqura, the value is not set. Additionally when using toGregorian and fromGregorian with the same locale, ie en-US, the value being formatted is in umalqura.

[test-set-value.zip](https://github.com/infor-design/enterprise/files/4933323/test-set-value.zip)

**To Reproduce**
1. Unzip the above and place into \app\views\components\datepicker directory
2. Go to 'http://localhost:4000/components/datepicker/test-set-value.html'
3. Error - the beginning database values of 2020 were converted to umalqura dates
4. Open new browser tab and go to "http://localhost:4000/components/datepicker/test-set-value.html?locale=ar-SA'
5. Error - the beginning database values were not converted; browser console has error of 'Uncaught TypeError: Cannot read property '2' of null'

**Expected behavior**

**Version**

- ids-enterprise: [4.30]

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/87706706-9134c380-c765-11ea-874c-dbf57fc0689d.png)
![image](https://user-images.githubusercontent.com/20212079/87706820-c214f880-c765-11ea-879b-e1ce6522c110.png)

**Platform**
 - All

**Additional context**
This test is an example of how Landmark transforms dates, from data to display and display to data

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/locale/test-set-value.html
https://master-enterprise.demo.design.infor.com/components/locale/test-set-value.html?locale=ar-SA
https://master-enterprise.demo.design.infor.com/components/locale/test-set-value.html?locale=ar-SA
![image](https://user-images.githubusercontent.com/45757016/87933230-72b12e00-cabf-11ea-9e6e-ebfeb913dd9e.png)
