### ISSUE TITLE
Tabs: Unnecessary scroll bar in Tab's dropdown filter in Windows IE 11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4166]
**Describe the bug**
Tabs: Unnecessary scroll bar in Tab's dropdown filter in Windows IE 11

**To Reproduce**
1. In IE browser,  Go to https://master-enterprise.demo.design.infor.com/components/tabs/example-enable-disable-individual-tabs-with-keydown.html?theme=uplift&variant=dark&colors=0066D4
2. Switch to a responsive view and minimize the screen 
3. In the Tabs, click the dropdown button 'v'

**Expected behavior**
There should not be any unnecessary scroll bar in the dropdown

**Version**
IDS 3.310 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/88036982-e19d8e00-cb76-11ea-8896-5aa138a49e19.png)

**Platform**
Windows 10 
IE 11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
May close this as minor and IE 11

**Comment by tmcconechy** [comment]
Descoping this for now
