### ISSUE TITLE
Tabs: Focus size is inconsistent or doubled when in responsive view in IE 11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4167]
**Describe the bug**
Tabs: Focus size is doubled when in responsive view in IE 11

**To Reproduce**
1. Open IE and Go to https://master-enterprise.demo.design.infor.com/components/tabs/example-index.html?theme=uplift&variant=dark&colors=0066D4
2. Minimize the screen 
3. Notice that the focus size become thicker

**Expected behavior**
Focus size should be consistent 

**Version**
4.31.0 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/88037888-0fcf9d80-cb78-11ea-814b-d62d0cae2436.png)

**Platform**
Windows 10 
IE 11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
May close this as minor and IE 11

**Comment by tmcconechy** [comment]
Descoping this for now
