### ISSUE TITLE
Searchfield: Clear function is not clearing

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4173]
**Describe the bug**
The clear function in search field is misnamed as its actually making the search field clearable. Not clearing it

**To Reproduce**
1. Go to http://localhost:4000/components/searchfield/example-index.html
2. Ru the page
3. See that the cleared function is not called as expected

**Expected behavior**
Also the functional test sometimes fails

**Version**
- ids-enterprise: [e.g. v4.31]

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-dev
https://master-enterprise.demo.design.infor.com/components/searchfield/example-clear-api.html
![image](https://user-images.githubusercontent.com/56722184/88519142-3c763000-d024-11ea-8301-0a6ba695731a.png)
