### ISSUE TITLE
Datagrid: Unnecessary vertical scrollbar visible when using row height of extra small

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4176]
Describe the bug
When using the datagrid option for a row height of 'extra-small', the rendered datagrid shows a vertical (overflow-y) scrollbar.  Switching to a row height of small, no vertical scrollbar is shown.

What's interesting about this issue, I only see this issue when the browser window is on my laptop, when moving the browser window to a second monitor the visible (but useless) vertical scrollbar is not present?  The resolution on the laptop is 1920 x 1080.

1. Go to http://localhost:4000/components/datagrid/example-compact-mode.html
2. Notice the vertical scrollbar (on the right hand side of the datagrid)
3. Using the scroll arrows does nothing
4. Now switch to a row height of Small via the More button
5. Notice that the vertical scrollbar is not present

Expected behavior
Vertical scrollbar would not be displayed when not necessary when using a row height of extra-small.

Version
v4.31.0-dev

![image](https://user-images.githubusercontent.com/39804038/88211184-f4699e80-cc1a-11ea-9124-42baf2b0d93b.png)

**Comment by tmcconechy** [comment]
Dont seem to see this on Mac or on PC (browser stack). Do you maybe have some browser zoom enabled on the monitor you see it on (guess?)

**Comment by claudenbach** [comment]
I'm seeing the issue with a browser zoom of 100%.

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/88212172-6ee6ee00-cc1c-11ea-82d6-fe3b02908f9d.png)

**Comment by tmcconechy** [comment]
Hmm what about on https://master-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html (this is a bit different i added back the double border on the bottom for several reasons).... See it there?

**Comment by claudenbach** [comment]
Yes, but I see the vertical scrollbar in both extra-small and small.

![image](https://user-images.githubusercontent.com/39804038/88212434-ddc44700-cc1c-11ea-85bb-0ee20a1b1241.png)

**Comment by claudenbach** [comment]
Interesting on vertical scrollbar when switching to the large row height, all other row heights show the scrollbar.

**Comment by tmcconechy** [comment]
Not seeing it here.. WIll get more folks to try it out. Can you identify what css is causing it?

**Comment by claudenbach** [comment]
![Scrollbar](https://user-images.githubusercontent.com/39804038/88214591-0994fc00-cc20-11ea-9a95-bcc02c3a0e0e.gif)

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/88214682-2e896f00-cc20-11ea-9298-428ec1584ebd.png)

**Comment by tmcconechy** [comment]
Interesting. Still unable to see it. But we cant remove that property or the grid will never scroll when it needs to. I think it would be an incorrect height someplace.

**Comment by tmcconechy** [comment]
Tried a windows VM and still not seeing it
![Screen Shot 2020-07-23 at 10 35 49 AM](https://user-images.githubusercontent.com/814283/88299418-533d1f80-ccd0-11ea-9adb-9e8ed511e323.png)

Anyone else? @EdwardCoyle @deep7102 ?

**Comment by deep7102** [comment]
I saw this when tested on my VM, win10 chrome v.84 but see only on master and its looking fine now in 4.31 after recent fixes.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/38439203/88305288-4ec83500-ccd7-11ea-92a0-4f6bcce113b2.png">

**Comment by tmcconechy** [comment]
I'll put this in the pile for QA for 4.31 so we can recheck. But it appears we have fixed it there.

**Comment by jbrcna** [comment]
**QA Passed**
I'm using Macbook and test it with   1680 x 1050 and 1920 x 1080. seems to work fine in both.
v4.31.0-dev 
https://master-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
![image](https://user-images.githubusercontent.com/56722184/88754643-cabbf480-d191-11ea-8ddd-2e59fc8c620a.png)
