### ISSUE TITLE
Tabs: Can't switch color theme in Tabs category searchfield

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4178]
**Describe the bug**
Tabs: Can't switch color theme in Tabs category search field

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html
2. Try to switch theme. Notice that the theme wont  change
3. Click Color menu. Notice that the sub menu did not open

**Expected behavior**
Sub menu should open

**Version**
4.310 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/88279728-23653a80-cd17-11ea-9b4b-3e8253dda059.png)

**Platform**
All platform Browser, OS and mobile devices

**Additional context**
n/a

**Comment by tmcconechy** [comment]
descoping this one for now
