### ISSUE TITLE
Tabs: Unable to create tabs with special characters

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4179]
**Describe the bug**
Tabs: Unable to create tabs with special characters

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tabs-module/example-legacy-style.html?theme=uplift&variant=dark&colors=56932e 
2. Create 1st tab
 Name: test
 Description: Test
3. Create 2nd tab
 Name: +++| test123 
 Description: !@#$%asd456
4. See error: unable to create tab

**Expected behavior**
Tab should be created

**Version**
4.310 dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/88281061-966fb080-cd19-11ea-8e0b-ba19182a7a75.png)

**Platform**
All platform OS, browser & devices

**Additional context**
n/a

**Comment by tmcconechy** [comment]
Seems minor as i the name is not realistic. But there seems to be an error happening we should fix.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified https://master-enterprise.demo.design.infor.com/components/tabs-module/example-legacy-style.html?theme=uplift&variant=dark&colors=56932e
![image](https://user-images.githubusercontent.com/45757016/91838167-a31fe680-ec7f-11ea-83c0-ddf6cc752bfa.png)
