### ISSUE TITLE
Search Field UI: background Issue

### ISSUE THREAD

**Issue by kevinwhitedesign** [infor-design/enterprise#4181]
Was interacting with this component
https://master-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-alternate-style-with-categories.html?theme=uplift&variant=light&colors=0066D4

I noticed that it's background wasn't really clear. I have a recommended shadow that we've been using in uplift:

```
/* Rectangle 538 */

width: 274px;
height: 32px;
left: 957px;
top: 1px;

background: #FFFFFF;
/* shadow */
box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.1);
```

It should end up looking something like this:
<img width="766" alt="Screen Shot 2020-07-23 at 10 21 24 AM" src="https://user-images.githubusercontent.com/6478704/88297736-4ae3e500-ccce-11ea-9798-17465ef658ca.png">

**Comment by tmcconechy** [comment]
Yeah that example is looking a bit off now.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
