### ISSUE TITLE
Editor: Text dropdown filter is not updating after changing to any Text Size

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4186]
**Describe the bug**
Editor: Text dropdown filter is not updating after changing to any Text Size

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-short.html?theme=uplift&variant=light&colors=0066D4
2. Highlight the 1st paragraph and choose Header 1 in Text dropdown filter
3. Text size should change as well as the value in the dropdown filter

**Expected behavior**
The value should change in the dropdown filter to Header 1 together with the text size 

**Version**
4.31.0 dev 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/88382424-fe3a0000-cdda-11ea-8eca-d7c1b1b321cf.png)

**Platform**
All browser OS and devices 

**Additional context**
n/a

**Comment by tmcconechy** [comment]
Descoping this issue for now
