### ISSUE TITLE
Editor: Font size changes to Normal after changing text alignment 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4188]
**Describe the bug**
Editor: Font size changes to Normal after changing text alignment 

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-complex-fontpicker.html?theme=uplift&variant=light&colors=0066D4
2. Select all text and change the font  to Header 5
3. Now Change the alignment to Right

**Expected behavior**
Font size Header 5 should be retained 

**Version**
4.31.0 dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/88384789-a782f500-cddf-11ea-958f-6f5794fb8cce.png)

**Platform**
All browser, OS and devices

**Additional context**
n/a

**Comment by tmcconechy** [comment]
The H5 isnt widely used so will descope this. Its sort of just doing what the browser decided to do in this situation so we dont really have any control over it
