### ISSUE TITLE
Locale: Create Translation Test Page

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4189]
**Is your feature request related to a problem or use case? Please describe.**
The translation team is requesting a test page in the sample app that shows the translations in context for testing.

**Describe the solution you'd like**

- [ ] Create a (list detail) with common elements in them that are translated (datagrid, calendar, datepicker)
- [ ] Create a sample form with translated data (making new strings with generic stuff like "Example Data", "Example Label"
- [ ] Test this with different locales and include as many strings as we can find coming through the strings for where they live in context

**Describe alternatives you've considered**
https://master-enterprise.demo.design.infor.com/components/datagrid/example-paging?locale=fr-FR has some but need most strings represent

**Additional context**
Email from Henry...

**Comment by tmcconechy** [comment]
I made an in-context translation page

https://master-enterprise.demo.design.infor.com/components/locale/test-translations.html&locale=es-ES for testing a bit better append the locale at the end you want to test (some new strings missing still).

**Comment by jbrcna** [comment]
QA Passed. Thank You!
https://4320-beta0-enterprise.demo.design.infor.com/components/locale/test-translations.html
https://4320-beta0-enterprise.demo.design.infor.com/components/locale/test-translations.html?locale=es-ES
![image](https://user-images.githubusercontent.com/56722184/92380939-892d4a80-f13c-11ea-94f8-44077141f734.png)
