### ISSUE TITLE
Datagrid: Selected rows multiplies upon reinvoke of .data('datagrid').selectAllRows

### ISSUE THREAD

**Issue by chamilledyan** [infor-design/enterprise#4195]
**Describe the bug**
Selected rows are multiplied upon reinvoke of .data('datagrid').selectAllRows
Issue is only encountered on datagrid with filterable set to true

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/4.30.0/demo/components/datagrid/test-filter-paging-client-side.html
2. On console developer tools, invoke $('#datagrid').data('datagrid').selectAllRows() - all rows will be selected
3. Check selected rows, invoke $('#datagrid').data('datagrid').selectedRows() - selected rows will be logged with all of dataset
4.  Repeat steps 2-3. Invoke $('#datagrid').data('datagrid').selectAllRows() again and check selected rows invoke $('#datagrid').data('datagrid').selectedRows() 
5. Selected rows will be logged with additional data. (repeating steps 2-3 will add more data)

**Expected behavior**
Selected rows will not be multiplied

**Version**
- ids-enterprise: 4.30.0 

**Screenshots**
![image](https://user-images.githubusercontent.com/68043861/88533476-f4add380-d038-11ea-8de4-f2f77cd21ee3.png)

**Platform**
 - Infor Application/Team Name: MSCM
 - OS Version: Windows 10
 - Browser Name: Microsoft Edge
 - Browser Version: Version 84.0.522.40 (Official build) (64-bit)

**Comment by tmcconechy** [comment]
This can be fixed by calling `unSelectAllRows` first. Also that can serve as a workaround.

**Comment by chamilledyan** [comment]
Hi @tmcconechy,
Applied workaround. Selected row count is hiding on second invoke but this is minimal issue than incorrect selected records.
![Datagrid items](https://user-images.githubusercontent.com/68043861/88764242-2b096100-d1a7-11ea-821e-8984103ea3d1.gif)

Thank you!

**Comment by tmcconechy** [comment]
Ok, yeah thats a good point. I think we need an internal fix to prevent this. We will work on it

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/90099340-cdf7d880-dd6c-11ea-85aa-db601a75a62e.png)
