### ISSUE TITLE
Datagrid: Nested rows cannot be clicked anymore

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4197]
**Describe the bug**
Nested datagrid rows cant be clicked anymore.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-nested-grids.html
2. Click on any row to expand
3. Click the delete button in the nested grid
4. See console -> no longer a message, also the rows appear not focusable.

**Expected behavior**
Should be able to click rows like before

**Version**
- ids-enterprise: [e.g. v4.30]

**Screenshots**

**Additional context**
Caused by https://github.com/infor-design/enterprise/issues/406
CC @afarn

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. :) 
![image](https://user-images.githubusercontent.com/45757016/88791831-f1e3e780-d1cc-11ea-9740-65e61d29e367.png)

**Comment by afarn** [comment]
I confirm that it works perfectly. Thank you.
