### ISSUE TITLE
Datagrid: Additional allowChildExpandOnMatch type search behavior

### ISSUE THREAD

**Issue by hgodse** [infor-design/enterprise#4209]
**Problem we faced**
When we set allowChildExpandOnMatch=true and find some element its showing all siblings of filtered element
also siblings of parent of filter elements.

**Solution we would like**
we would like solution like when we search element it searches like '**allowChildExpandOnMatch =false**'  with child expansion feature of  '**allowChildExpandOnMatch =true**'

**Explanation**
we expecting search result same as shown is  screenshot with '**allowChildExpandOnMatch =false**' with addition we expecting to able to expand searched node. In this example "Follow up action with Acme Canada"

We tried '**allowChildExpandOnMatch =true**' but it showing so many unnecessary nodes please find screenshot below
![Screenshot (11)](https://user-images.githubusercontent.com/64417907/88802423-af201080-d1c8-11ea-969d-5b8a8e4c6302.png)

![Screenshot (10)](https://user-images.githubusercontent.com/64417907/88801853-e80bb580-d1c7-11ea-9a9b-a879bddeeece.png)

**Comment by tmcconechy** [comment]
So how would you like it to behave exactly when you search like those examples? It seems like you just showed a screen shot of it on and of it off? Maybe you can list what you think it should show? If this new feature was added....

**Comment by hgodse** [comment]
please refer 2nd screenshot where search is minimized ,we would like to same result with adition to child of searched nodes

**Comment by tmcconechy** [comment]
Thats what confused me. The second search is already possible and is what happens if you just turn the option off.

https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-filter-child-on-match.html
- turn off the switch
- search on "Follow up action with Acme Canada"

So i dont yet see anything you cant presently do.

**Comment by hgodse** [comment]
but in second search we cannot select any children of  "Follow up action with Acme Canada".

**Comment by tmcconechy** [comment]
Ok, i see what you mean now. Wondering if maybe the best fix is to make allowChildExpandOnMatch only show matching nodes and parents and children... I think this can be simplified somehow but is tricky to do.

**Comment by hgodse** [comment]
ok

**Comment by hgodse** [comment]
Thanks for your support in advance

**Comment by dhumalkishor** [comment]
Hi Tim,

Any updated on this issue? 

Regards,
Kishor

**Comment by tmcconechy** [comment]
No we have not had time for this. But if your team does you could try and work on a pull request for review?

**Comment by dhumalkishor** [comment]
Hi Tim, 
Can you please look into this issue?

Regards,
Kishor

**Comment by tmcconechy** [comment]
Ok, will take a brief look at this in march. Since its a enhancement im going to timebox the issue as we have a lot of priorities.
Which means hopefully we find a quick solution. if not we might have to wait on this feature.

Meanwhile see what you can do as a workaround.

**Comment by janahintal** [comment]
QA Passed. 
![image](https://user-images.githubusercontent.com/45757016/113707403-700c6c80-9712-11eb-9f0a-c4afff1006f0.png)
![image](https://user-images.githubusercontent.com/45757016/113707417-7569b700-9712-11eb-963a-725ac3b6ed60.png)
![image](https://user-images.githubusercontent.com/45757016/113707437-7d295b80-9712-11eb-93e4-449d8e4f5c29.png)
