### ISSUE TITLE
Datagrid Tree view fails to display rows sometimes when updating dynamically.

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#4213]
**Describe the bug**
Datagrid fails to show rows sometimes when updating dataset for tree via updateDataset() function. I created a new branch with demo illustrating the issue. This is a pretty close comparison as to how we update data in our application, using the updateDataset() function.

**To Reproduce**
1. Get code from example branch "**_datagrid-tree-updateDataset-issue_**"
2. Go to "http://localhost:4000/components/datagrid/test-tree-update-data.html"
3. Expand all rows.
4. Last row fails to show data. 

**Expected behavior**
All data should display

When expecting the DOM you can see that the rows are there. But they both have `is-hidden` class on them. After digging around for a while. It appears as though this code is the culprit: (**_datagrid.js_**)

```
rowHtml() {
...
if (parentNode && parentNode.node.expanded !== undefined && !parentNode.node.expanded) {
     isHidden = true; 
} else {
    isHidden = rowData._isFilteredOut;
}
...
```

**Potential fix:**
I think maybe this can be fixed by also checking if parentNode has children. For example.. (_this seems to fix the issue in my example_)
```
if (parentNode && parentNode.node.children && parentNode.node.expanded !== undefined && !parentNode.node.expanded) {
     isHidden = true; 
} else {
    isHidden = rowData._isFilteredOut;
}
```

`isHidden` appears to get set to true when a row with no children exists. Which then appears to cause the flag to continue to be true late on.

**Version**
4.32.0-dev

**Screenshots**

**_Example broken:_**
![tree-not-expanding](https://user-images.githubusercontent.com/1056684/88872237-5a3bc480-d1df-11ea-8734-b4e4e1cce576.gif)

**_Example with potential fix:_**
![tree-expanding-with-fix](https://user-images.githubusercontent.com/1056684/88872243-5d36b500-d1df-11ea-8e67-0e99f8ff67c0.gif)

**Platform**
 - Windows 10
- Chrome

**Additional context**

**Comment by tmcconechy** [comment]
Hi @deep7102 can you take a look at this bug for 4.31 and see what you think?

**Comment by jbrcna** [comment]
**QA Passed**
v4.31.0-rc0
https://4310-rc0-enterprise.demo.design.infor.com/components/datagrid/test-tree-update-data.html
![image](https://user-images.githubusercontent.com/56722184/89395524-06c9f900-d740-11ea-805c-ca88893843b0.png)
