### ISSUE TITLE
SOHO-7434: Adjust CSS for disabled search field inside list-view

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#422]
h4. Having structure: 

```
  <soho-listview [dataset]="userList" [searchable]="true" [selectable]="single">
      <input soho-searchfield [formControl]="searchUserFormControl" [clearable]="true">
      <li  soho-listview-item class="user-item" *ngFor="let user of usersList; let i = index">
        <p soho-listview-header>{{user.displayName}}</p>
        <p soho-listview-subheader>{{user.loginName}}</p>
      </li>
  </soho-listview>
```

h4. Use case:
Users are loaded dynamically based on user input, so initially the list is empty. There are scenarios in our app when we want to have the input field disabled, so user is not able to search for other users.

h4. Styling Issues:
When input field has attribute disabled: 

h5. Expected result: 
- icon is grayed out
- on mouse over event -  styling of the border is untouched

h5. Actual result:
- icon is not grayed out
- on mouse over event - styling of the border is changed ( see pictures attached )

**Comment by ericangeles** [comment]
Not sure where to reproduce / replicate the issue.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/listview/test-search-disabled.html
Passed QA testing
