### ISSUE TITLE
CAP: Workspaces label spacing off in mobile/responsive view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4224]
**Describe the bug**
The Comment label spacing is off

**To Reproduce**
1. Open mobile browser / or go to responsive view
2. Go to https://4310-beta1-enterprise.demo.design.infor.com/components/contextualactionpanel/example-workspaces.html?theme=soho&variant=light&colors=2578a9
3. Open CAP by clicking the ` Show Contextual Action Panel `button

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/89183250-84b7c400-d5c9-11ea-8fe0-c807fc70f0a3.png)

**Version**
- ids-enterprise: [v4.29.0 - v4.31.0-beta1]

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/89183050-3efafb80-d5c9-11ea-8adf-6150c82102d0.png)

**Platform**
Mobile Device
iOS / Android

**Additional context**

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by jbrcna** [comment]
**QA Failed**
The padding in `Comment` is now resolved, However, it seems like the header got affected. please see screenshot.
v4.31.0-rc0
screenshot on `Browserstack:` iPhone 11 Pro
https://4310-rc0-enterprise.demo.design.infor.com/components/contextualactionpanel/example-workspaces.html?theme=soho&variant=light&colors=2578a9
![image](https://user-images.githubusercontent.com/56722184/89301941-cc5b5000-d69c-11ea-8082-3455c2d0ea8a.png)

Also, In default view, some inputs and labels were displaced. There's an unnecessary scroll bar present
screenshot on `Browser:` Mac/Edge
![image](https://user-images.githubusercontent.com/56722184/89302530-8783e900-d69d-11ea-8264-6b6f7a703e20.png)

**Comment by tmcconechy** [comment]
Added an additional fix for this that will be in the next RC/Final

**Comment by jbrcna** [comment]
Issue resolved. Thank you!
v4.31.0-rc1
https://4310-rc1-enterprise.demo.design.infor.com/components/contextualactionpanel/example-workspaces.html
![image](https://user-images.githubusercontent.com/56722184/89774193-006cc000-db38-11ea-8e6a-6f23b92e0ab5.png)
![image](https://user-images.githubusercontent.com/56722184/89774195-02368380-db38-11ea-9534-cf0261ca4980.png)
