### ISSUE TITLE
ToolbarFlexSearchfield: Styling issues when added to toolbar

### ISSUE THREAD

**Issue by James063** [infor-design/enterprise#4226]
1. Toolbarsearchfield has no Text property definition. 
2. we can't get control value in change event augment.
3. Toolbarsearchfield has one line in the button of control in the toolbar.

**Comment by jbrcna** [comment]
**QA Passed**
v4.32.0-dev
https://master-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
![image](https://user-images.githubusercontent.com/56722184/90249627-61b0ce00-de6d-11ea-96d6-880f2b1c9087.png)
