### ISSUE TITLE
DatePicker: Unable to use range with ar-SA locale

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#4227]
**Describe the bug**
When using the ar-SA locale with a date picker configured to use range, the range selection does not work; can get a browser console error of date.getTime is not a function

**To Reproduce**
1. Go to http://localhost:4000/components/datepicker/example-range.html and http://localhost:4000/components/datepicker/example-range.html?locale=ar-SA in separate tabs
2. First, not all the date fields pre-populated in en-US are not populated in ar-SA; no browser console errors
3. In ar-SA, using the Range - Select Forward field, open the datepicker and select a range
4. Error here as the UI is not indicating a range being selected; if clicking on a date, a browser console error is displayed

**Expected behavior**
- Pre-populated values should be displayed
- UI should indicate a range is being created (grey trail)
- Selecting a single date should begin a trail

**Version**

- ids-enterprise: [ v4.31.0-beta.1 ]

**Screenshots**
![image](https://user-images.githubusercontent.com/20212079/89324545-13215980-d64d-11ea-94c0-d9638c5dae02.png)

**Platform**
 - All

**Additional context**

**Comment by janahintal** [comment]
**Failing in Windows 10 IE 11 :** 
 _All range fields are not working in Windows 10 IE11._ 

- Range min(5) days is not working. Unable to select another date after choosing one

![image](https://user-images.githubusercontent.com/45757016/90094083-9c2c4500-dd5f-11ea-99f7-94611c834697.png)

- Range with time is overlapping in responsive view 

![image](https://user-images.githubusercontent.com/45757016/90094083-9c2c4500-dd5f-11ea-99f7-94611c834697.png)

**Comment by tmcconechy** [comment]
Putting in a fix for it not working at all in IE11. However will leave the overlap issue for now. It's not really fixable and only happens at certain sizes.

**Comment by janahintal** [comment]
Hi @tmcconechy , I often get this error in IE. But managed to test the fields. They're now working as expected but somehow slow on IE that I have to refresh the page more often. 
![image](https://user-images.githubusercontent.com/45757016/90222837-71b1b900-de3f-11ea-9915-27aa7e0f8a66.png)

**Comment by tmcconechy** [comment]
Im not really sure what this is. But we are descoping IE 11 so leaving this for now unless its found by a customer.
I'd dont see it
