### ISSUE TITLE
Datagrid: Unnecessary scroll bar in a grid with no data

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4228]
**Describe the bug**
Datagrid: Unnecessary scroll bar in a grid with no data

**To Reproduce**
1. Go to https://4310-rc0-enterprise.demo.design.infor.com/components/datagrid/test-empty-message-small.html?theme=uplift&variant=dark&colors=0066D4
2. Minimize the screen and change the row height to extra small
3. Change the theme to Subtle 

**Expected behavior**
There should be no unnecessary scroll bar in the grid

**Version**
4.31.0 IDS Rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/89375711-c9a23e80-d720-11ea-9e54-00426040819e.png)

**Platform**
All browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Dont think this is possible to fix. But will leave open for now and try later.

**Comment by janahintal** [comment]
The issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/95190707-4f666700-0802-11eb-997c-1f5df10de811.png)
![image](https://user-images.githubusercontent.com/45757016/95190999-b6841b80-0802-11eb-9ebc-454a9b876ba5.png)
