### ISSUE TITLE
Text Area: Read only fields has input cursor in Windows 10 IE 11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4232]
**Describe the bug**
Text Area: Read only fields has input cursor in Windows 10 IE 11

**To Reproduce**
1. Go to https://4310-rc0-enterprise.demo.design.infor.com/
2. Go to Text Area section
3. In the Notes (readonly) field, hover and click inside the text field 
4. See the input cursor is initiated

**Expected behavior**
There should not be input cursor in read only fields. 

**Version**
4.31.0 IDS RC0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/89494189-3c2a2180-d7e8-11ea-990f-4d1d6f90f101.png)

**Platform**
Windows 10 IE 11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This is the normal browser behavior for readonly fields. So nothing worth changing here. The cursor is there so you can select the readonly text. In some browser they do hide it. Also given its IE 11 really not worth addressing
