### ISSUE TITLE
Sink Page: Charts sinks when switching views mobile to default

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4233]
**Describe the bug**
Resizing from default > mobile > default view makes the charts displaced. (i.e. default view resize to mobile view then go back to default view)

**To Reproduce**
1. Go to https://4310-rc0-enterprise.demo.design.infor.com/
2. Find Charts
3. Switch to mobile view
4. Scrollto() Charts
5. Switch to default view
6. Scrollto() Charts
7. Notice that the charts shrunk

**Expected behavior**
should look normal

**Version**
- ids-enterprise: [e.g. v4.29.0 - v4.31.0-rc0]

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/89527686-541b9880-d81c-11ea-869e-29d3853e4b44.png)

**Platform**
Safari or any

**Additional context**

**Comment by tmcconechy** [comment]
Can't seem to reproduce this issue. Can you elaborate on the steps?

**Comment by jbrcna** [comment]
Hi @tmcconechy , kindly toggle the device toolbar.
![Large GIF (1200x714)](https://user-images.githubusercontent.com/56722184/89548872-2e9d8780-d83a-11ea-94d6-88e637337fde.gif)

**Comment by tmcconechy** [comment]
Ok i can see this on https://master-enterprise.demo.design.infor.com/components/pie/example-index.html on galaxy s5 specifically.

I think this is not too important because it specific

**Comment by tmcconechy** [comment]
descoping this for now

**Comment by jbrcna** [comment]
Hi @tmcconechy, I think this issue has been fixed by this https://github.com/infor-design/enterprise/pull/4928. just need to resize the browser gradually or slowly. Thank you.
