### ISSUE TITLE
Datagrid: Render issue with frozen columns and alerts when using row height of extra-small

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4237]
Describe the bug
Datagrid render issues when the row height is 'extra-small' and the list has frozen columns and cells with alerts.

1. Using the attached test-frozen-columns-with-alert.html
2. Click on the More button and change the row height to extra small
3. Notice that the rows are no longer vertically aligned

Expected behavior
Rendering of the datagrid should work with frozen columns

Version
4.32.0-dev

Screenshots
![image](https://user-images.githubusercontent.com/39804038/89573310-09842700-d7f0-11ea-951e-f3eac08065fd.png)

This will require a patch for 4.31.

**Comment by claudenbach** [comment]
[Git-4237.zip](https://github.com/infor-design/enterprise/files/5037577/Git-4237.zip)

**Comment by tmcconechy** [comment]
4.31 is not released. I think i fixed something similar i saw here. Will have look.

**Comment by tmcconechy** [comment]
You mean the hight of the two sides of the rows is not the same? Riight?

**Comment by claudenbach** [comment]
Correct.

**Comment by claudenbach** [comment]
Also have a rendering issue with frozen columns and tags when the row height is extra-small.

![image](https://user-images.githubusercontent.com/39804038/89589106-9805a200-d80a-11ea-9c2a-f653d7f79af0.png)

**Comment by claudenbach** [comment]
Please let me know when this is built into a package.

**Comment by tmcconechy** [comment]
@claudenbach this is built in NG 7.5.0-rc.2 have a go....

**Comment by claudenbach** [comment]
Will do.  Thank you!
