### ISSUE TITLE
SOHO-7396: Row templates expanded when searching in Datagrid

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#424]
Variation of SHUB-6744  - All rows expanded in datagrid when keywordFilter blanked.

In this case the row template is expanded for matching rows when a match is found in the template. The example used mentioned in SHUB-6744 cannot be used to illustrate the issue as it uses empty templates.

Using this example to illustrate the issue:
http://usalvlhlpool1.infor.com/4.3.4/components/datagrid/example-expandable-row.html

!row_expanded_template_text.png|thumbnail!

Notice that a search for 'Lo' finds a row and expands the template as it matches 'Lorem'.

Empty templates can be used as a workaround for this issue.

**Comment by brianjuan** [comment]
http://4100-beta0-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row.html
http://4100-beta0-enterprise.demo.design.infor.com/components/datagrid/test-expand-row-on-search.html
Passed QA testing
