### ISSUE TITLE
Trigger Field - Add new web component wrapper for trigger fields (WC) 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4244]
**Is your feature request related to a problem or use case? Please describe.**

Following the example of the tag component. This ask is to make a `trigger-field` component. A trigger field is considered an input field with an icon(s) next to it. This will be used to build out shared code between datepicker, dropdown, multiselect, timepicker, spinbox ect...

**Describe the solution you'd like**

- [ ] Create trigger-field web component
- [ ] Use flex to align the input and icon(s) within the parent container (responsive grid)
- [ ] Uses a ids-icon component for the trigger icon
- [ ] Add a click function callback for down arrow and/or click
- [ ] Add a new option `tabbable` to allow the trigger field to be in the tab order or not (default on)
- [ ] Add 100% test coverage

**Describe alternatives you've considered**
Building into each one. But this was a bad idea last time.

**Additional context**
https://github.com/infor-design/enterprise/issues/579 was the old issue but its not entirely valid anymore.

**Comment by tmcconechy** [comment]
Done for now? Or do you have more to add?

**Comment by jmacaluso711** [comment]
Done for now
