### ISSUE TITLE
Datagrid: Column showColumn when column is hidden causes grouped columns to misrender

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4247]
**Describe the bug**
When calling showColumn when the column is already visible and you have groupedHeaders the columns become misaligned.

**To Reproduce**
1. An example was pushed to 4.31.x called "test-frozen-columns-with-grouped-headers-hidden-columns.html"
1. Go to http://localhost:4000/components/datagrid/test-frozen-columns-with-grouped-headers-hidden-columns.html
1. Run and see error
1. Comment out
```
    }).data('datagrid');
    api.showColumn('CompanyValue7_7');
    api.showColumn('OnHold6_6');
```
1. Run and see it works.

**Expected behavior**
When calling showColumn the columnGroups in settings seem to be getting adjusted as if the column was hidden. But they dont need to be touched since the column is already visible.

**Version**
- ids-enterprise: [e.g. v4.31.x]

**Screenshots**
![Screen Shot 2020-08-10 at 3 31 34 PM](https://user-images.githubusercontent.com/814283/89823246-28035e80-db1f-11ea-92b6-93919ef51834.png)

**Platform**
 - Chrome/Any

**Additional context**
cc @claudenbach - debugging session

**Comment by claudenbach** [comment]
Please test that is also works with the hideColumn scenario, since that is more typical.  Renders correctly when frozen columns do not exist.

Rendering of an example list in Landmark, where the last two columns are hidden. The group header is still being shown.

![image](https://user-images.githubusercontent.com/39804038/89825014-947b5f00-db19-11ea-94a4-9fe9b4e53cbd.png)

**Comment by tmcconechy** [comment]
yeah will add a few more/hide/show tests

**Comment by janahintal** [comment]
Hi guys, 
Noticed this issue upon testing. Uneven row grid in Buttons column. 
![image](https://user-images.githubusercontent.com/45757016/90134835-5cd41780-dda4-11ea-8025-59f44fab1ec9.png)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you :)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you!
![image](https://user-images.githubusercontent.com/45757016/94549964-947c1d80-0285-11eb-99bb-8eeae0160d83.png)
