### ISSUE TITLE
Text Input: Error State is inconsistent 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4248]
**Describe the bug**
Text Input: Error state is inconsistent 

**To Reproduce**
1. Go to https://4300-enterprise.demo.design.infor.com/components/input/example-index.html?theme=uplift&variant=dark&colors=0066D4  
2. Go to Input section and tab to all required field to show notification 
3. Switch to Dark mode
4. Notice the focus disappeared after switching to dark mode

**Expected behavior**
Focus should be consistent in all theme and variant

**Version**
4310 IDS RC1

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/89879046-eba23200-dbf4-11ea-9d02-880df1bc184d.png)

after switching to Dark variant / mode
![image](https://user-images.githubusercontent.com/45757016/89878964-d62d0800-dbf4-11ea-8e10-484245472838.png)

**Platform**
All browser OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Yes looks like the error state is missing the colored border in dark - uplift. Should check this in all 6 themes

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.
Verified in https://master-enterprise.demo.design.infor.com/components/input/example-index.html?theme=soho&variant=light&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/90384891-db86c880-e0b4-11ea-8ec0-e1c5fa2bd762.png)
