### ISSUE TITLE
Step Process: .sidebar .tree was updated in _tree.scss, but .step-process-container .tree was not updated in _stepprocess.scss

### ISSUE THREAD

**Issue by drinkaj** [infor-design/enterprise#4249]
.sidebar .tree was updated in _tree.scss from using margins to padding, but the  .step-process-container .tree was not updated in _stepprocess.scss to override the padding.

![step_control](https://user-images.githubusercontent.com/6230418/89931573-f7c8c800-dbd1-11ea-8041-31f692b1e0b4.png)
![css](https://user-images.githubusercontent.com/6230418/89931574-f7c8c800-dbd1-11ea-81c6-6a366889f178.png)

**Comment by tmcconechy** [comment]
Will have to restore the deprecated example and get it all working again to test. Suggest working around in custom css meanwhile.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/page-patterns/test-stepprocess.html?theme=uplift&variant=light&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/93335630-53cdde80-f859-11ea-86eb-32edc13cf45a.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
