### ISSUE TITLE
Tree: Context menu is missing focus state/ menu not focusing correct node

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4252]
**Describe the bug**
#3794 was not fixed 100% correctly so made a new item to fix it up. Assigning to @deep7102 to fix further.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tree/example-context-menu.html
1. click node two to expand
1.  try tab to node one (issue one: should show blue focus and that's currently missing)
1.  right click node 2.1 and hit escape or click a menu item (should focus node 2.1)
1. click another node after closing the menu (should focus node with no focus state shown)

Second Test
1. Go to https://master-enterprise.demo.design.infor.com/components/tree/example-context-menu.html
1. click node two to expand
1. try tab to node one (issue one: should show blue focus and that's currently missing)
1. right click node 2.1 and while open click another node
1. clicked node should be focused with no focus state shown and there should be no focus on the previous item

**Expected behavior**
1. Should always have a focus state on focus
1. right clicking an item should set focus to it (when the menu is complete)

**Version**
- ids-enterprise: [e.g. v4.31]

**Platform**
 -  Chrome/Mac or any

**Additional context**
Clarifies #3794 further

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/tree/example-context-menu.html
