### ISSUE TITLE
WebComponents: Research and add Vue JS Example

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4255]
**Is your feature request related to a problem or use case? Please describe.**
The goal of this task is to research using a new webcomponent (the new tags component as an example) in vue.js and see whats needed to make it work. 

Think about vue.js  features that might want to be used with the component and try them. Ideally we dont need special wrappers or too much. Research "using web components in vue.js "

**Describe the solution you'd like**
- see https://github.com/infor-design/enterprise-wc-examples
- starting with a simple stackblitz project https://stackblitz.com/edit/vue
- add tags (manually like in the angular example for now)
- make it render and test features like:
  - Provide binding to the model for values
  - Catching and handling events emitted
  - Setting and changing settings (color setting for example)
  - Templating like loops or text values
  - Research common framework features (forms ect)
- when you get something working will we push to https://github.com/infor-design/enterprise-wc-examples/tree/master/vue-ids-wc and eventually host in stackblitz

Feel free to discuss with the team...

**Additional context**
- is mostly working https://github.com/infor-design/enterprise-wc-examples/tree/master/angular-ids-wc as a comparison

**Comment by tmcconechy** [comment]
@ericangeles i saw there was a recent major update https://v3.vuejs.org/ maybe you can update the examples to 3.0?

**Comment by ericangeles** [comment]
Sure do.
