### ISSUE TITLE
Popup - Add new web component for popup

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4256]
**Describe the solution you'd like**
This task is to make a new `popup` component that will live in the enterprise-wc project repo. This will replace popdown, popover, popup (all the pops :| ). And be the basis for tooltip, modal, CAP, popdown, popover ect.

This will also self contain the place logic. I think the place logic can be simplified a bit to our cases. This being (non exhaustive)

- arrow or not pointing at an object
- center in page or not
- opens down or side of
- size of contents (no padding - to be done by the caller)
- if size is too big - check opposite side and if more room use that. if not enough room on both sides fit to page and scroll 

**Rough Task Outline**
- [x] Make an `<ids-popup>` component
- [x] Make an example page with a few scenarios
- [ ] Other features like "contain focus" "click outside" and dig around existing components more for additional settings
- [x] Add tests
- [x] additional "seeing what others are doing" https://www.google.com/search?q=web+component+popup+component&rlz=1C5CHFA_enUS860US860&oq=web+component+popup+component&aqs=chrome..69i57j69i64l2.4784j0j4&sourceid=chrome&ie=UTF-8

**Additional context**
See also https://github.com/infor-design/enterprise/issues/2468

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
