### ISSUE TITLE
Step process: Sidebar and the content of step process are not scrollable

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#4258]
**Describe the bug**
Both the sidebar and the step content are not scrollable.

**To Reproduce**
1. Go to ids-enterprise-ng demo
2. Expand S in the main toolbar.
3. Choose 'Step Process-Basic'.
4. Adjust the browser height to recreate the problem.

**Expected behavior**
Both the sidebar and content area should be scrollable.
Noticed that .main and .sidebar height set to 'auto' under .two-column in _layouts.scss is causing the issue.

**Version**
- ids-enterprise: v4.31.0-rc.1

**Platform**
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 84.0.4147.105 (Official Build) (64-bit)

**Additional context**
Added some content to the first panel in stepprocess.demo.html in enterprise-ng demo project to test. Attaching file.

**Comment by aaralikar** [comment]
stepprocess.demo.html
[stepprocess.demo-html.txt](https://github.com/infor-design/enterprise/files/5065502/stepprocess.demo-html.txt)

**Comment by vonnyw** [comment]
@tmcconechy This is causing our form not to show all the fields, can we have the fix in 4.31?

**Comment by tmcconechy** [comment]
My understanding was you have a css fix for this you have added. Technically this pattern is deprecated

**Comment by vonnyw** [comment]
Never mind, yes, we do have a css workaround. Thanks

**Comment by janahintal** [comment]
Hi @tmcconechy, does this ticket has a PR for testing? Thank you. :)

**Comment by tmcconechy** [comment]
@janahintal yes it does. I linked it incorrectly. Its linked now https://github.com/infor-design/enterprise/pull/4338 👍

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. :)
