### ISSUE TITLE
Validation: Issues upon resetForm execution.

### ISSUE THREAD

**Issue by kmadamba** [infor-design/enterprise#4259]
**Describe the bug**
After execution of the resetForm, the dropdown field still contains errormessage array and is valid is false resulting to error label of the control not being displayed.

**To Reproduce**
1.	Go to 'https://master-enterprise.demo.design.infor.com/components/validation/example-validation-form.html'
2.	Select a state from the States dropdown
3.	Remove the selected state from the States dropdown, then click anywhere in the form to trigger the validation
4.	In the console run $('body').resetForm();
5.	Select the States dropdown, then click on another field to trigger the validation

**Expected behavior**
That the reset form will remove all of the validation icons and data, so that any validation can be rerun correctly.

**Screenshots**
Fields state right after the resetForm has been executed
![image](https://user-images.githubusercontent.com/66233290/90086425-fb348e80-dd4c-11ea-8d1c-df64abb3284b.png)

The field after the validation happens after the reset.
![image](https://user-images.githubusercontent.com/66233290/90086493-1acbb700-dd4d-11ea-9133-37a877e60712.png)

**Version**
- IDS SOHO v4.30.1

**Platform**
•	OS Version: Windows 10
•	Browser: Chrome Version 84.0.4147.105

**Comment by tmcconechy** [comment]
Yes i see this issue....You need to select the blank item and then click out in the steps involving dropdowns.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
