### ISSUE TITLE
SOHO-7388: .beforeActivate and .activated event is fired for every tab when closing tab

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#426]
**Describe the bug**
Every time a tab is closed (opened) events .beforeActivate and .activated are fired for **every** opened tab. Expected behavior is to fire this event for specific tab that is deactivated and the one that is activated.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/tabs/example-activated-event.html
2. Edit the example to make it more clear (by putting the events in the console
2. Click a different tab

**Expected behavior**
Expect one event for deactivate for the tab that is deactivated and one for the tab that is activated.

**Platform**
All

**Additional context**
See SOHO-7388

NOTE: I am not seeing this issue on http://master-enterprise.demo.design.infor.com/components/tabs/example-activated-event.html

**Comment by tjamesallen15** [comment]
Hi @clepore and @tmcconechy 

I messaged both you regarding about this.

Thanks!

**Comment by tmcconechy** [comment]
I was not able to reproduce this issue on http://master-enterprise.demo.design.infor.com/components/tabs/example-activated-event.html it seems to fire once per tab.

Suggest adding a toast to the beforeactivated on the example /tabs/example-activated-event.html and then adding a test. Then we can probably close.

**Comment by tjamesallen15** [comment]
I already pushed a PR for this ticket. Added additional e2e spec test for verification.

**Comment by brianjuan** [comment]
http://4110-beta0-enterprise.demo.design.infor.com/components/tabs/example-activated-event.html
Passed QA testing across all browsers.
