### ISSUE TITLE
Datagrid: Dynamic Tooltip only Shows when column size is shorter

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4260]
**Describe the bug**

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-custom-tooltip-dynamic.html
2. Hover Exception -> tooltip shows
3. Make Exception wider
4.  Hover Exception -> see error tooltip does show

**Expected behavior**
When using the dynamic tooltip function as this example does. The tooltip should always show.
I think that its getting mixed up with the ellipsis tooltip setting which only shows when the column is too small https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-ellipsis.html

**Version**
- ids-enterprise: [v4.31]

**Platform**
 - Any/Chrome

**Additional context**
Email

**Comment by janahintal** [comment]
QA Passed. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-custom-tooltip-dynamic.html?theme=uplift&variant=light&colors=0066D4 

![image](https://user-images.githubusercontent.com/45757016/91038720-d1794280-e63d-11ea-850e-b75411a2e1e8.png)
