### ISSUE TITLE
Datagrid: Render issue with tabbing into cell with Editors.Dropdown

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4261]
Describe the bug
When tabbing into a cell that is an updateable dropdown, the rendering is incorrect.  The dropdown works correctly if the user clicks on the dropdown arrow icon.  

1. Using the attached example-editable-dropdown.html
2. Tab into the cell of the Action column
3. See the render issue, the dropdown containing the options is not displayed

Expected behavior
Dropdown options should be displayed.

Version
v4.32

Additional context
This is a high priority issue for Landmark and will require a patch to 7.5.0.

**Comment by claudenbach** [comment]
[Git-4261.zip](https://github.com/infor-design/enterprise/files/5070137/Git-4261.zip)

**Comment by tmcconechy** [comment]
this can also be reproduced on http://localhost:4000/components/datagrid/example-editable.html

- go to http://localhost:4000/components/datagrid/example-editable.html
- click a cell like quantity
- hit f2
- tab until you hit the action column

Was probably caused by https://github.com/infor-design/enterprise/issues/3980

**Comment by tmcconechy** [comment]
Fixed this issue https://github.com/infor-design/enterprise/pull/4263 for review. 

Will patch the next version 4.31.1 -> On EOD Monday

**Comment by janahintal** [comment]
Hi @tmcconechy, noticed that when I try make the field editable, no text cursor is displayed. It just look like it's focused but not editable. 

https://4330-beta1-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?theme=uplift&variant=light&colors=0066D4

Steps:
1. click in the grid and arrow to the Action field hit enter -> this will enter edit mode but wont open
2. now type a and it should filter
3. reset
4. click in the grid and hit F2 to toggle "tabs mode"
5. tab to the Action field -> this will enter edit mode but wont open
6. now type a and it should filter

![image](https://user-images.githubusercontent.com/45757016/94547382-c68b8080-0281-11eb-8e9f-29ae87949d77.png)

**Comment by tmcconechy** [comment]
@janahintal thats correct - in f2 it goes into edit mode but it doesnt open right away unless you press down arrow. Vs enter + down arrow when not in edit mode.

But i see an issue (minor) with the white background. Would you take a look @deep7102 try this...
- put mouse over line one
- arrow right to order date and then on to action
- notice white background around.

Lets fix that part?

<img width="784" alt="Screen Shot 2020-09-29 at 9 34 30 AM" src="https://user-images.githubusercontent.com/814283/94565280-01b49200-0237-11eb-8ebc-178b5b477ac9.png">

**Comment by tmcconechy** [comment]
Moving my comment to https://github.com/infor-design/enterprise/issues/4264 as thats where it was created
