### ISSUE TITLE
Datagrid: Overlap issue with lookup icon and cell value when using a row height of extra-small

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4264]
Describe the bug
The value for a cell with a lookup editor, overlaps the lookup icon when using a row height of extra-small.  Not an issue when the row height is small.  Not an issue for an editable date column.

1. Using the attached test-lookup-cell-overlap.html
2. Select a row height of extra-small from the more menu
3. Make the width of the Product Name column smaller
4. Click on a cell within the Product Name column
5. See the overlap

Expected behavior
Lookup icon does not overlap the cell value.  Expect same behavior as a date column.

Version
v4.32.0

Additional context
This is a priority issue for Landmark and will require a patch to 7.5.0.

**Comment by claudenbach** [comment]
[Git-4264.zip](https://github.com/infor-design/enterprise/files/5070677/Git-4264.zip)

**Comment by claudenbach** [comment]
On further testing it does look like an editable date column also has the issue were the icon overlaps the data.

**Comment by claudenbach** [comment]
This is easier to dup if the columnSizing option is set to 'data'.

![image](https://user-images.githubusercontent.com/39804038/90171662-6ee39500-dd67-11ea-8d5c-d8124c0c41ad.png)

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/90171746-90dd1780-dd67-11ea-84b4-d76643d2b9f3.png)

**Comment by tmcconechy** [comment]
Did you attach the wrong file? I'm trying to look at this. Before i saw this isnt a new issue.
You just mean if the column is too short the icon is on top?

![Screen Shot 2020-08-13 at 2 26 49 PM](https://user-images.githubusercontent.com/814283/90172483-13b6a000-dd71-11ea-8294-51c989221baf.png) (this is 4.6.2)

I'm not sure there is a better solution. I think we tried adding ellipsis or cutting it off but it's a bit tricky.

**Comment by tmcconechy** [comment]
Would those steps also be correct?

- go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
- resize order date so the text doesnt fit
- hover the cell
- notice the icon is on the text

If so i think this is an enhancement (sort of) since we always had it like this. The solution would be to either change to ellipsis on hover or cut it off with padding if not possible. This could be a bit of a css rework.

Since not a new issue will put it in current sprint for now

**Comment by claudenbach** [comment]
Yes, I'm seeing the issue in that scenario as well.  

My case is, set focus into an order date cell so the date icon is visible.  Now make the column width's narrower by using the grabbers.  In this case the icon doesn't flow over the cell data.

![image](https://user-images.githubusercontent.com/39804038/90181719-87a77700-dd76-11ea-8884-aed97c9534cf.png)

**Comment by tmcconechy** [comment]
Yes i guess its handled in that case. So should we do the same thing on hover and just lop it off?

**Comment by claudenbach** [comment]
Yes, that is what I was thinking.  If you do the same thing with a lookup select cell when using row height of short it does the same thing.

![image](https://user-images.githubusercontent.com/39804038/90182571-c853c000-dd77-11ea-83fa-d67eab8746e3.png)

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-lookup-cell-overlap.html
![image](https://user-images.githubusercontent.com/56722184/93989911-0d2e3600-fdbd-11ea-9219-96258f0b406e.png)

**Comment by tmcconechy** [comment]
@deep7102 - we saw an minor issue with this we should probably address in 4.33.x with the white background. Would you take a look?

Try this...
- put mouse over line one
- arrow right to order date and then on to action
- notice white background around.

Lets fix ? Thanks

<img width="784" alt="Screen Shot 2020-09-29 at 9 34 30 AM" src="https://user-images.githubusercontent.com/814283/94565280-01b49200-0237-11eb-8ebc-178b5b477ac9.png">

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by jbrcna** [comment]
**QA Passed**
tried both themes and all variants. thank you.
v4.33.0-rc0
https://4330-rc0-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
![image](https://user-images.githubusercontent.com/56722184/94907197-5a538b80-04d2-11eb-8287-0534a9ae1e67.png)

**Comment by jbrcna** [comment]
Hi, @tmcconechy I was testing Datagrid editable and I came across an issue related to [this](https://github.com/infor-design/enterprise/issues/4264#issuecomment-700710758) (white background around the icon) when you add new rows.
**Steps to replicate**
![image](https://user-images.githubusercontent.com/56722184/107034699-08a96d80-67f2-11eb-9637-903801f6ed76.png)


![image](https://user-images.githubusercontent.com/56722184/107034590-e0ba0a00-67f1-11eb-82f9-6987314dc0e2.png)

**Comment by tmcconechy** [comment]
Thanks @jbrcna just a small css issue. I put it in with a fix for https://github.com/infor-design/enterprise/issues/4815 i was working on

**Comment by jbrcna** [comment]
Thanks @tmcconechy . upon testing it again in master v4.38.0-dev this is now fixed and  working as expected. 
[PR](https://github.com/infor-design/enterprise/pull/4816#issue-568457555)
<img width="822" alt="image" src="https://user-images.githubusercontent.com/56722184/107480434-8f29ca80-6bb7-11eb-9e10-de93529a4dca.png">
