### ISSUE TITLE
Datagrid: Client Side Paging doesn't have an option to configure select all (all pages vs the current page)

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#4265]
**Is your feature request related to a problem or use case? Please describe.**
We want the user to only select the page where they are at when clicking on Select All. This is a client side grid.

**Describe the solution you'd like**
We would like to see in the grid options an attribute that we can indicate if the select all should select all rows or just the page.

**Describe alternatives you've considered**
We don't have an alternative at the moment other than disable the select all feature

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
