### ISSUE TITLE
Datagrid: Editors.Lookup icon is rendered to high in uplift theme with row height of small or extra-small

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4266]
Describe the bug
The icon-search-list icon used by the Editors.Lookup is rendered to high, the margin-top is off when using the uplift theme and a row height of small or extra-small. 

1. Using test-lookup-cell-overlap.html
2. Switch to the uplift theme
3. Switch to a row height of extra-small
4. Set focus into a Product Id cell

Expected behavior
The icon is displayed in the middle of the cell

Version
v4.32

Additional context
Landmark will need a patch to 7.5.0.

Screenshots
![image](https://user-images.githubusercontent.com/39804038/90189245-6f3d5980-dd82-11ea-8a36-2abfd957e234.png)

**Comment by claudenbach** [comment]
In Landmark, with rowHeight: extra-small, columnSizing: data...

![image](https://user-images.githubusercontent.com/39804038/90189396-bcb9c680-dd82-11ea-9763-68bab0c386f5.png)

**Comment by claudenbach** [comment]
In Landmark, with rowHeight: small, columnSizing:data...

![image](https://user-images.githubusercontent.com/39804038/90189549-02768f00-dd83-11ea-898c-57f6206d68a4.png)

**Comment by jbrcna** [comment]
**QA Failed**
v4.32.0-dev
It looks fine in `Small` and `Extra-Small `but fails in `Medium` row height (Mobile View). Will retest once beta is deployed
https://master-enterprise.demo.design.infor.com/components/datagrid/test-lookup-cell-overlap.html
![image](https://user-images.githubusercontent.com/56722184/91043927-0b027b80-e647-11ea-987f-5681d8fb49a4.png)



https://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect
**Observation:**
Browser:Safari
![image](https://user-images.githubusercontent.com/56722184/91042545-7eef5480-e644-11ea-95b3-33c554c9991a.png)
https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup.html
https://master-enterprise.demo.design.infor.com/components/datagrid/example-editable

**Comment by tmcconechy** [comment]
Lets retest this once merged. For the Failed QA points

1) I made a fix to something else but couldn't reproduce this. Might need device info and more steps. Please raise a new issue if you still see something.
2) What's the observation exactly? I'm not sure what your highlighting.

**Comment by jbrcna** [comment]
Hi @tmcconechy  for the observation in `Safari` browser, there is a square shape object like in the header checkbox when you click (check) the header checkbox. 
Steps:
1. Navigate to https://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect
2. Tick the header checkbox, focus should also be on the header checkbox.
3. Notice the focus of the header checkbox is off. 

<img width="105" alt="image" src="https://user-images.githubusercontent.com/56722184/91297416-de7a6b00-e7d0-11ea-9288-0571f8d3d1c0.png">

it should display something like as below.
<img width="102" alt="image" src="https://user-images.githubusercontent.com/56722184/91297707-56e12c00-e7d1-11ea-8adc-e4344833a3c1.png">

**Comment by tmcconechy** [comment]
ok hmm im not seeing it - but now that i understand - will keep an eye out for it

**Comment by jbrcna** [comment]
**QA Failed**
v4.32.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-lookup-cell-overlap.html?theme=uplift&variant=light&colors=0066D4
using `Medium` row height
![image](https://user-images.githubusercontent.com/56722184/91844024-4de8d280-ec89-11ea-8c97-ad390f8fa7cd.png)

![image](https://user-images.githubusercontent.com/56722184/91557599-55496c80-e967-11ea-86b6-0e612af7d7db.png)

*****-------------------------------------------------------------------------------------------------------------

**Additional Fix:**

- go to http://localhost:4000/components/datagrid/test-ellipsis-editor-dropdown
- keep in short mode and try the dropdowns (centered one will NOT center when editing)
- try to change to uplift
- tab into the dropdown field to edit
- resize the dropdown columns to ellipsis and retry

Result: `(centered one will NOT center when editing)` looks fine. However, the search icon is displaced. It seems that the icon position is fixed.
![image](https://user-images.githubusercontent.com/56722184/91845093-2b57b900-ec8b-11ea-836b-272e4ccca7e1.png)
_screenshot Browser Safari_

**Comment by jbrcna** [comment]
**QA Issue 1 - Passed**

- go to https://4320-beta0-enterprise.demo.design.infor.com/components/datagrid/test-ellipsis-editor-dropdown
- click in cell "left align dd" to open the dropdown
- type a (search icon should now be aligned OK)

**QA Issue 2 - Passed**

- go to https://4320-beta0-enterprise.demo.design.infor.com/components/datagrid/test-lookup-cell-overlap.html?theme=uplift
- switch to medium row height
- click in product id cell
- editor should align nicely

Just a minor observation

QA Issue 1  - The search icon is displaced with `row height` `medium` and `small`
