### ISSUE TITLE
Export Separate Component Bundles

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#427]
**Original Issue:** https://jira.infor.com/browse/SOHO-7366

It should be possible to build out IDS Enterprise for different needs.  In many cases, the implementing App developer will not want to include every component we ship.  IDS should have several standard, logical groups of components we can recommend for various purposes.

Some (tentative) ways to split up the components could be:

- prereqs bundle - `ids-core.js`
- forms bundle (inputs / form functions) - `ids-forms.js`
- charts/visualization bundle (including d3) - `ids-charts.js`
- tree/hierarchy - `ids-hierarchy.js`
- list  / datagrid - `ids-lists.js`
- patterns - `ids-patterns.js`
- calendar - `ids-calendar.js`
- editor - `ids-editor.js`

All of the above bundles would include any dependency needed to fully display the components - meaning

- CSS
- Javascript
- SVG images (if applicable)
- HTML templates (if applicable)

**Comment by tmcconechy** [comment]
Think this is done now?
