### ISSUE TITLE
Datagrid Tree: Filter is not working showing data when the user types the date fast

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#4270]
When the user has a filter with a date, typing it causes problems and nothing is showed.
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-filter.html
2. Click on Order Date filter
3. Enter a date (DO NOT type fast or copy/paste a date or select from date picker) and press enter

**Expected behavior**
Row 8 should be displayed since it has that date. However no Data is displayed.

**Version**
IDS 7.5.0

**Platform**
 - Browser Name: chrome
![image](https://user-images.githubusercontent.com/17933529/90443182-cb1d2080-e0a9-11ea-9610-813d330d5e47.png)
![image](https://user-images.githubusercontent.com/17933529/90443229-e5ef9500-e0a9-11ea-8042-97d1e2291128.png)

**Comment by tmcconechy** [comment]
@AnaLauraMartinez - possible workaround is to set `filterWhenTyping: false`

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-filter.html
![Large GIF (1302x586)](https://user-images.githubusercontent.com/56722184/93460636-1bd8a100-f916-11ea-9d44-c82334507541.gif)
