### ISSUE TITLE
Tabs: Focus gets misaligned after switching themes in IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4272]
**Describe the bug**
Tabs: Focus gets misaligned after switching themes in IE11

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tabs/example-url-hash-change.html
2. Go to the last tab 'Tab Number Five' 
3. Switch to Uplift Theme

**Expected behavior**
Focus should not be misaligned

**Version**
4.320 dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/90491380-6ed20380-e172-11ea-8cfb-abeb8f8294a0.png)

**Platform**
Windows 10 IE 11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
We will probably end up closing this as minor and IE 11

**Comment by tmcconechy** [comment]
Descoping for now
