### ISSUE TITLE
Toast: Add support for Automated Testing Ids

### ISSUE THREAD

**Issue by PaulEvansInfor** [infor-design/enterprise#4275]
**Is your feature request related to a problem or use case? Please describe.**
We have a requirement to support Automated testing frameworks in Infor products.  This means any parts of a control that perform an interaction should easily be located within the document (via a unique statically named id element or surrogate attribute i.e. "data-auto-uid") the automated test framework can then easily fire a click event to interact with that component and not have to perform complex lookups/searches in order to find the element and trigger the event.

**Describe the solution you'd like**
This issue applies to Toast messages:
We should be able to provide a unique id for the Toast so Automated Testing frameworks can easily pick up when it has been displayed.  This may be used in the process of verifying an action such as successfully save/deletion of a record.

**Describe alternatives you've considered**
An alternative approach is to use an element within the DOM/page container to set/update state.  This would have to be applied per application and may differ depending on the technique used.

**Comment by tmcconechy** [comment]
Idea Is to add a setting that takes a string or function. Using the function you can use the count of number of active toasts (may not be unique). 

```
attributes: { name: 'id', value: 'my-unique-id' }
attributes: { name: 'data-automation-id', value: 'my-unique-id' }
attributes: { name: 'id', value: function(info) { return `my-unique-id-${infor.count}` }
attributes: { name: 'data-automation-id', value: function(info) { return `my-unique-id-${infor.count}` }
```

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/toast/example-index.html
![image](https://user-images.githubusercontent.com/56722184/93447866-82a18e80-f905-11ea-9455-dc0b7ce8e15d.png)

**Comment by CindyMercadoReyes** [comment]
Attaching BDD for this new enhancement. 
[BDDStory_github4275.docx](https://github.com/infor-design/enterprise/files/5239632/BDDStory_github4275.docx)
