### ISSUE TITLE
Datagrid: Add support for Automated Testing Ids

### ISSUE THREAD

**Issue by PaulEvansInfor** [infor-design/enterprise#4276]
**Is your feature request related to a problem or use case? Please describe.**
We have a requirement to support Automated testing frameworks in Infor products.  This means any parts of a control that perform an interaction should easily be located within the document (via a unique statically named id element or surrogate attribute i.e. "data-auto-uid") the automated test framework can then easily fire a click event to interact with that component and not have to perform complex lookups/searches in order to find the element and trigger the event.

**Describe the solution you'd like**
We need to easily be able to locate any part of the grid that triggers and action or accepts text.  Mainly this would apply to the filter bar, also drill down buttons and expand/collapse buttons.  We ideally would have a id assigned that identifies each control by column in the case of filters or by grid row in the case of drill down/expand buttons.

**Describe alternatives you've considered**
At present there are no clear alternatives.  It is awkward to locate certain items within the grid without using complex DOM lookups/XPaths.  Such code would vulnerable to future changes within the grid API.

**Comment by tmcconechy** [comment]
This one is a bit trickier...Have to figure out how to get all the parts that might need ideas and provide a function. We should pass types in perhaps like `filter-input`, `column`, `row`, `expander` ect..

```
attributes: { name: 'id', value: function(info) { return `my-unique-id-${infor.cell}-${infor.row}-${infor.type}` }
attributes: { name: 'data-automation-id', value: function(info) { return `my-unique-id-${infor.cell}-${infor.row}-${infor.type}` }
```

**Comment by tmcconechy** [comment]
This has been completed
