### ISSUE TITLE
Message: Add support for Automated Testing Ids

### ISSUE THREAD

**Issue by PaulEvansInfor** [infor-design/enterprise#4277]
**Is your feature request related to a problem or use case? Please describe.**
We have a requirement to support Automated testing frameworks in Infor products.  This means any parts of a control that perform an interaction should easily be located within the document (via a unique statically named id element or surrogate attribute i.e. "data-auto-uid") the automated test framework can then easily fire a click event to interact with that component and not have to perform complex lookups/searches in order to find the element and trigger the event.

**Describe the solution you'd like**
The Message class has no way of passing an id to assign to the resultant dialog.  The Modal class that is used by Message does support this feature but at present there is no way of passing an id through.

**Describe alternatives you've considered**
An alternative would be to use Modal directly, but the Message class is handy for simple situations.  An automated test framework may use this dialog to confirm state, such as a warning that certain fields are required in order to submit a form.

**Comment by tmcconechy** [comment]
Idea Is to add a setting that takes a string or function. Using the function you can use the count of number of active messages (may not be unique). 

```
attributes: { name: 'id', value: 'my-unique-id' }
attributes: { name: 'data-automation-id', value: 'my-unique-id' }
attributes: { name: 'id', value: function(info) { return `my-unique-id-${infor.count}` }
attributes: { name: 'data-automation-id', value: function(info) { return `my-unique-id-${infor.count}` }
```

**Comment by tmcconechy** [comment]
Similar to toast #4275

**Comment by jbrcna** [comment]
**QA Passed**
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/message/example-index.html
![image](https://user-images.githubusercontent.com/56722184/95982125-51f43c80-0e52-11eb-949e-9a25378374ad.png)
![image](https://user-images.githubusercontent.com/56722184/95982507-c4fdb300-0e52-11eb-95a7-1002a871f63d.png)

https://master-enterprise.demo.design.infor.com/components/modal/example-close-btn.html
![image](https://user-images.githubusercontent.com/56722184/95983245-e1e6b600-0e53-11eb-8875-273a08922dcd.png)
