### ISSUE TITLE
DropDown/Multi-select: Add support for Automated testing Id's

### ISSUE THREAD

**Issue by PaulEvansInfor** [infor-design/enterprise#4278]
**Is your feature request related to a problem or use case? Please describe.**
We have a requirement to support Automated testing frameworks in Infor products.  This means any parts of a control that perform an interaction should easily be located within the document (via a unique statically named id element or surrogate attribute i.e. "data-auto-uid") the automated test framework can then easily fire a click event to interact with that component and not have to perform complex lookups/searches in order to find the element and trigger the event.

**Describe the solution you'd like**
The drop down/multi-select should ideally take user defined ids/attributes (i.e. data-auto-uid and apply to the input/open/close button and elements selectable in the drop down list.  Ideally we should be able to set unique static ids so a dropdown control can easily be found and interacted with on the page.  Also we should be able to set static ids on the elements within the list so they can easily be selected by automated test tools.

**Describe alternatives you've considered**
The drop down list does assign an id attribute to list options based on the index (i.e. id="list-option-1")  This could be used by automated test frameworks to interact with the list.  The main issue here is that those ids don't have anything that describes the data, so if the ids change or the order in which data appears in the list changes then the automated tests may break.

**Comment by tmcconechy** [comment]
For this case i think that the id should be part of the data: `{ id: 'x', value: 'xx', label: 'xxx'}` this is now going on the select but not the popup list so need to somehow solve that.

**Comment by tmcconechy** [comment]
This has been completed
