### ISSUE TITLE
SOHO-7356: Documentation Improvements

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#428]
- [x] update application menu docs to explain: that you need to use the application-menu-trigger on the button. I assume that’s what the jQuery extension binds to
- [x] layouts - mention you need to  wrap the content in a page-container class
- [x] personalization - mention the use of  is-personalizable
- [x] layouts mention - scrollable, inverse, page-container, do are how they are used to layout a page, in addition to the grid.
- [x] form layouts for various use cases, like single record edit, master detail edit, multi-record edit, etc guidance. Like is the label above or to the left of the edit field? How do you indicate a required field? What should the field width be, should it fill the grid column, or are their specific sizes, or should the width match the max data contents width?  
- [x]  also, a question on the grid. Is it fixed or fluid? Is there a choice? In bootstrap for example it’s just one class either container or container-fluid.
A: With zero configuration, it’s fluid.  Whoever implements could build a fixed container for it
- [x] autocomplete, is there a documentation on the expected shape of the returned object?  
A: In this format with 
{value: "AL", label: "Alabama", id: ‘AL’}
- [x]  http://usalvlhlpool1.infor.com/4.3.4/layouts and http://usalvlhlpool1.infor.com/4.3.4/patterns make this in a list with more descriptions and tips and notes

**Comment by PilotBob** [comment]
Additional items to add: @tmcconechy 

Please add documentation for any additional layout classes that are available. Two I am aware of that aren't documented are

no-indent
top-padding

If there are any others, like was to set gutters on/off, pull or pus columns, etc... please also include. Currently, the only way to discover these classes is to spelunk the sample and css source or perhaps ask in teams.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
