### ISSUE TITLE
Colorpicker: Focus is not on the selected color when reopening the colorpicker on iPad

### ISSUE THREAD

**Issue by eeriksson429** [infor-design/enterprise#4280]
**Describe the bug**
When reopening the colorpicker, the previously selected color is not selected. This is only encountered when testing on iPad. Works on desktop. 

**To Reproduce**
1. Go to 'https://master-enterprise.demo.design.infor.com/components/colorpicker/example-index.html' on an iPad.
2. Open the colorpicker.
3. Select a color (e.g. Ruby08)
4. Reopen the colorpicker.

**Expected behavior**
The checkmark and blue focus border is displayed around Ruby08.

**Actual result**
The checkmark is displayed on Ruby08, but the blue focus border is shown around Slate10.

**Version**
- ids-enterprise: v4.30.1

**Platform**
- Infor Application/Team Name: Infor Homepages
- Device: iPad Mini 4
- OS Version: 13.3.1
- Browser Name: Safari & Chrome

**Comment by tmcconechy** [comment]
I tried this against https://master-enterprise.demo.design.infor.com/components/colorpicker/example-index.html on iPad Mini 2019 (13) and an iPad 12.9 2018 and could not reproduce it.

Anything else you can add? The one thing i do see is there is a blue focus state on the first field but the check is on the correct item? Is that the "bug"?

**Comment by eeriksson429** [comment]
Yeah, I double-checked with the QA who found it, and she said that the blue border is in the first field but the checkmark is on the right color square. 

I'll update the ticket info.

**Comment by tmcconechy** [comment]
I agree i suppose the focus should be on the check element as well (normally the focus is on the first element so thats why its doing it). But there seems to be some inconsistency that its just showing on Iphone. So will take a look but mark this as minor as there is no harm.

**Comment by eeriksson429** [comment]
Sounds good, thanks Tim!

**Comment by tmcconechy** [comment]
Descoping this bug for now
