### ISSUE TITLE
Popover:  Using an element id as content reference is no longer working

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#4281]
**Describe the bug**
Using an element id as content reference for a popover no longer works. 

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/popover/test-inline-data-options.html
2. Click on 'Open Popover'
Result: Popover content is the id string itself, not the content of the element with that id.

Doesn't work:
`content: "#some-id-to-popover-contents"`
Works:
`content: $("#some-id-to-popover-contents")`

**Expected behavior**
The popover should contain the content of the element with the id that was provided as content reference. 

**Version**
- ids-enterprise: 4.31.0

**Additional context**
It's working on 4.30.0:
https://design.infor.com/code/ids-enterprise/4.30.0/demo/components/popover/test-inline-data-options.html

The issue is caused by this change:
https://github.com/infor-design/enterprise/pull/4107/files#diff-0732597cd96cb9d201490dfa8fe61b4bR432
The id used as content reference will not match the id of the element that triggers the tooltip, since they're different elements. The change was done to solve an issue with the title, but changes the content logic.

**Comment by janahintal** [comment]
QA Failed in IE11

Steps:
1. go to https://master-enterprise.demo.design.infor.com/components/popover/test-inline-data-options.html and open POpover
2. Switch to vibrant mode then open the popover again
3. See error
![image](https://user-images.githubusercontent.com/45757016/91163732-9be95d80-e700-11ea-8a60-095dac506dbb.png)

**Comment by tmcconechy** [comment]
Since this issue is minor and IE 11 only will descope this final point
