### ISSUE TITLE
Modal: there are some overlapping fields in the modal when in IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4284]
**To Reproduce**
1. Open IE11 browser and Go to https://master-enterprise.demo.design.infor.com/components/modal/example-before-open.html?theme=uplift&variant=light&colors=0066D4
2. Click Add Context 
3. See Error

**Expected behavior**

**Version**
4.320 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/90747721-dff4f080-e303-11ea-9c83-73030896b046.png)

**Platform**
Windows 10 IE 11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Since this issue is minor and we are no longer supporting IE 11 in Oct will close this for now.
