### ISSUE TITLE
Tooltip: is not working on elements  

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4285]
**Describe the bug**
Tooltip: is not working on elements  

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tooltip/example-tooltips-on-elements.html
2. Hover in the 'tooltip here' button

**Expected behavior**
A tooltip should show

**Version**
4.320 dev ids

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/90766884-d9c03d80-e31e-11ea-8f6f-c58183916362.png)

**Platform**
All browser, OS and devices

**Additional context**
n/a

**Comment by tmcconechy** [comment]
@janahintal this example is actually working correctly. In order to show the tooltip hover over the "First and Last Name" element and then it will show on the button.

Its showing tooltips on input elements and the ability to redirect the placement of the tooltip to something else (the button)
