### ISSUE TITLE
Tabs Header: Misalignment on Uplift mode

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4289]
**Describe the bug**
Saw two issues in tab header uplift mode. One is that the icon is tiny and the page layouts funny.

**To Reproduce**
1. Go to https://latest-enterprise.demo.design.infor.com/components/tabs-header/example-add-tab-button.html?theme=uplift
2. Resize the page to like 707[x
3. See how the + icon is tiny
4. And the page form layout is pushed down

**Expected behavior**
Make a bigger (18px) but still fill the button in focus state correctly and fix layout issue

**Version**
- ids-enterprise: [e.g. v4.31]

**Screenshots**
![Screen Shot 2020-08-20 at 3 51 03 PM](https://user-images.githubusercontent.com/814283/90818740-f8add800-e2fc-11ea-9988-931f4237b35f.png)

**Platform**
 - Chrome or any

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
