### ISSUE TITLE
Does the IDS SpinBox support decimal values and increments?

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#4290]
Current IDS version: 4.26.2

I'm uplifting a legacy Infor UI program from VB.Net to a web application using IDS and one of the dialogs has a SpinBox control that displays a decimal value and increments in steps of 0.1. VB.Net supports decimal values in their SpinBox control.

I don't see any obvious examples in the documentation of decimal values in the IDS spinbox control. Is it possible?

**Comment by sanx72** [comment]
Thanks for checking. I'll go with the masked numeric for now as its only one input field in the whole product that requires a decimal value. 

FYI - in the VB.NET Spinbox you can set either integer or decimal initial values, set the number of decimal places for the value, and also set a integer or decimal increment value.

**Comment by tmcconechy** [comment]
OK yes thats makes sense then, if you set the interval that way. If we need this in the future lets make an enhancement issue.
