### ISSUE TITLE
Searchfield doesn't allow some special characters

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#4291]
**Describe the bug**
When I add some characters to the items in the http://localhost:4000/components/searchfield/test-long-options.html sample I cannot search for them in the searchfield. I have noticed that the following characters cannot be searched:  ( ) [ ? ' + *

**To Reproduce**
1. Locally edit the Items in the components/searchfield/test-long-options.html sample and add the characters ( ) [ ? ' + *
2. Run the sample
3. search for (
=> No results
4. Continue searching for the other special characters one by one

Note that the ] special character is allowed but not the [

**Expected behavior**
I think all or a majority of the special characters ( ) [ ? ' + * should be searchable in the searchfield. At least the following 3 special characters should be allowed  ( ) [ 

**Version**

- ids-enterprise: 4.31.0

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/90897657-c9af6900-e3c5-11ea-8d67-023d3a254897.png)

![image](https://user-images.githubusercontent.com/8664975/90897703-d92eb200-e3c5-11ea-8cdd-7ac3f829926e.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 84.0.4147.135 (Official Build) (64-bit)

**Additional context**

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/searchfield/test-special-characters
![image](https://user-images.githubusercontent.com/56722184/93206882-b2795680-f78c-11ea-966d-57e8aee841f6.png)
