### ISSUE TITLE
SohoTranslate returning incorrect value for 'ExportToExcel'

### ISSUE THREAD

**Issue by jbaumgartner401** [infor-design/enterprise#4292]
**Describe the bug**
sohoTranslate is returning "Export to Excell" instead of "Export to Excel". 

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-test-settings from the enterprise-ng sample app.
2. Click on More button above the data grid.
3. See error

**Expected behavior**
Text should be "Export to Excel" with a single L.

**Version**
v4.32.0-dev.20200807

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://user-images.githubusercontent.com/70033614/90924117-d8455280-e3bc-11ea-82cf-ba5a24d19b9b.png)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
Code:

````
                <li soho-popupmenu-item>
                    <a soho-popupmenu-label href="#" data-option="export-to-excel">{{'ExportToExcel' | sohoTranslate}}l</a>
                </li>
````

**Comment by tmcconechy** [comment]
Fixed this https://github.com/infor-design/enterprise-ng/commit/285709a30f7bace2aa18adfae893fd37770bbfdc
