### ISSUE TITLE
DataGrid: Treegrid with paging filter is not working

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#4293]
**Datagrid is a TreeGrid with Paging**

When a treegrid has paging and the user uses the filter, anything that it is not in the first page is not displayed.

**To Reproduce**
1. go to the example attached below (html and service components)
2. Make sure there are only 5 rows displayed.
3. Enter in the Position filter > 30

**Expected behavior**
rows with values 37, 38 and 40 to be displayed

Problems:
The data in the page 2 is not filtered hence no rows are showed. If you increase the # of rows per page, the filter will indeed show those records.

**Version**
IDS 7.5

![image](https://user-images.githubusercontent.com/17933529/90925317-0461d300-e3bf-11ea-9974-caf9e5a82f51.png)
![image](https://user-images.githubusercontent.com/17933529/90925337-0e83d180-e3bf-11ea-9554-1b2874b25c3a.png)
![image](https://user-images.githubusercontent.com/17933529/90925376-1e9bb100-e3bf-11ea-9771-8cded3509744.png)

[datagrid-treegrid-service.demo.zip](https://github.com/infor-design/enterprise/files/5110769/datagrid-treegrid-service.demo.zip)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.
Verified in https://4320-beta0-enterprise.demo.design.infor.com/components/datagrid/test-tree-filter-paging.html?theme=uplift&variant=light&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/91974979-40971b00-ed51-11ea-92b8-7be3c6788dfc.png)
