### ISSUE TITLE
FileUploadAdvanced: Set status completed on send method not working.

### ISSUE THREAD

**Issue by deep7102** [infor-design/enterprise#4294]
**Describe the bug**
When use api setting `send` method with FileUploadAdvanced. The passed method `status.setCompleted()` not firing  event `fileremoved`.

**To Reproduce**
1. Go to http://localhost:4000/components/fileupload-advanced/example-send.html
2. Remove passing data argument when run [status.setCompleted()](https://github.com/infor-design/enterprise/blob/06294a3ada7797f1a8d58b60f6e1c56aad99c3ce/app/views/components/fileupload-advanced/example-send.html#L45)
3. Save and run
4. Upload any file and after completed
5. Press `Remove File (X)` button

**Expected behavior**
Should fire event `fileremoved` after click on Remove File (X)` button.

**Version**

- ids-enterprise: v4.31

**Platform**
 - All

**Additional context**
See MS Teams comments [here](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1597415735243?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1597415735243&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=General&createdTime=1597415735243)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Conducted regression testing on the file upload component.
