### ISSUE TITLE
Editor: Missing toolbar button in small browser

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#4296]
**Describe the bug**
When the browser window is small one item in the toolbar is not listed (which one depends on the width of the window). For example if the window is wide enough to show the left and center align buttons but not the right align. The right align button will not be in toolbar or menu.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
2. Make the window small enough so the center align button is visible, but not the right align. 
3. Click the ... menu
4. Issue: Note that the right align option is not visible.
5. Close the menu again
6. Make the browser just a little wider so that the next separator is visible, but not the quote
7. Click the menu again
8. Note that the "quote button" is not avialable

**Expected behavior**
All icons should be available (in either the toolbar or the menu). So in step 4 the Right align option should be in the menu and in step 8 the Quote button should be avaialble inte the menu.

**Version**

- ids-enterprise: 4.31.1

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/91044202-2ce30a80-e615-11ea-9fad-5bbf86b98ec4.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 84.0.4147.135 (Official Build) (64-bit)

**Additional context**
-

**Comment by EdwardCoyle** [comment]
Seems to be related to all Flex Toolbars, but apparently very easy to spot on a formatter toolbar

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/editor/example-index.html?colors=0066D4
Verified in https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
![image](https://user-images.githubusercontent.com/45757016/93334825-1ddc2a80-f858-11ea-97d1-660fe192fdab.png)

**Comment by SofiK** [comment]
Hi! 
What is that undefined in the mobile image? Is it text color?

**Comment by tmcconechy** [comment]
Good question @SofiK - i cant figure out what this is doing. It should say text color tho. @EdwardCoyle was looking for an easy fix but i dont understand whats wrong here.

**Comment by SofiK** [comment]
Can it be related to the separator?

Den tor 17 sep. 2020 16:04Tim McConechy <notifications@github.com> skrev:

**Comment by tmcconechy** [comment]
@EdwardCoyle is more familiar with how that menu is generated. i was thinking a locale string was missing but i couldnt find one

**Comment by EdwardCoyle** [comment]
Seems to be the Colorpicker getting picked up by the overflow menu.  The Flex Toolbar might be getting this incorrectly or not knowing to throw it out.  This is a new bug I think.

<img width="1394" alt="Screen Shot 2020-09-18 at 11 02 37 AM" src="https://user-images.githubusercontent.com/3249601/93613278-a5cc4c80-f99e-11ea-912f-a8a6e622999a.png">

**Comment by tmcconechy** [comment]
ok, can you raise an issue for this @SofiK ? Thanks!

**Comment by SofiK** [comment]
Sure, will do it on Monday :)

Den fre 18 sep. 2020 17:05Tim McConechy <notifications@github.com> skrev:
