### ISSUE TITLE
SOHO-7307: Listview Performance issue when showing 4000 items

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#430]
Ticket is intended to improve performance of list view and combines SOHO-8172

1. Using SOHO Listview to display 4000 items in the list 
causes slowness in rending the list, searching items, item selection/deselection and lag in scrolling.

2. Also, when transferring items in one listview to another, the scrollbar gets cut. 
Similar thing happens when deselecting multiple items at once. (see attached image)- This should be fixed on 4.8.0

3. When paging the entire list renders then the first page is re-rendered would be more efficient to simply render the first page initially once.

See attached sample application for case 1.

**Comment by tjamesallen15** [comment]
Hi @tmcconechy and @clepore,

Do we have a sample page with 4000 items that can be use for debugging and testing?

Thanks!

**Comment by tmcconechy** [comment]
No but i made one for you. You can save this into the listview folder (as perhaps test-performance.html)

```

<div class="row">
  <div class="twelve columns">
      <h2 class="fieldset-title">ListView  - 4000 Items</h2>
  </div>
</div>

<div class="row">
  <div class="one-third column">
    <div class="card" >
      <div class="card-header">
        <h2 class="card-title">Tasks</h2>
      </div>

      <div class="card-content">
        <div class="listview" id="task-listview" data-init="false"></div>
      </div>
    </div>

  </div>
</div>

{{={{{ }}}=}}
<script id="task-tmpl" type="text/html">
  <ul>
    {{#dataset}}
      <li>
        <p class="listview-heading">Task #{{task}}</p>
        <p class="listview-subheading">{{desc}} </p>
        <p class="listview-micro">Due: {{due}}</p>
      </li>
    {{/dataset}}
  </ul>
</script>

<script>
  $('body').on('initialized', function() {
    var data = [];
    data.push({task: 'Task One', desc: 'Description of the task', due: '2018-08-10'});

    for (var i = 0; i < 4000; i++) {
      data.push({task: 'Task ' + i, desc: 'Description of for task ' + i, due: '2018-08-10'});
    }

    this.listview = $('#task-listview').listview({
      dataset: data,
      template: $('#task-tmpl').html(),
      selectable: false
    });
  });
</script>
```

Idea is to see if we can optimize the rendering some more.

**Comment by tmcconechy** [comment]
Working on 2 more fixes to add
- a setting for highlight
- checking paging works optimally for this example

**Comment by brianjuan** [comment]
http://localhost:4000/components/listview/test-listview-performance.html
In Mac Chrome, there is just slight delay like 2-3secs when searching on the listview. Try searching for #3333

**Comment by tmcconechy** [comment]
I dont think we can make it any faster this spring. This is a significant improvement from what it was.

**Comment by brianjuan** [comment]
This is noted @tmcconechy , thanks. Will now move this to Done.
