### ISSUE TITLE
ListBuilder: Usability improvements and API improvements

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#4301]
We are using IDS v4.26.2 but issues occur in the standard example in the latest release...

https://design.infor.com/code/ids-enterprise/latest/demo/components/listbuilder/example-index?theme=soho&variant=light&colors=2578a9

We would like the folloiwing improvements to the ListBuilder control to aid usabillity...

1) When no ListBuilder item is selected, the edit and delete options should be automatically disabled (and go up/down options). Also, provide "unselected" or "selection changed" event when the selection is cleared.

2) Double-click on an list item should fire the edit function for that item (and/or provide a "double-click" event passing the appropriate argument containing the selected list item's data so we can program our own double click behaviour)

**Comment by tmcconechy** [comment]
Closing this for now but will be working better in the new future web component - archiving for now
