### ISSUE TITLE
Tree: Would like to be able to append an alert image

### ISSUE THREAD

**Issue by krishnakotaInfor** [infor-design/enterprise#4305]
**Is your feature request related to a problem or use case? Please describe.**
As part of Widgets development in our application, we are using SoHoTree to binding some data.
we are able to bind the data to all the tree nodes successfully along with icon before the node.
We need to append/add an image icon to a node element with tooltip as per the below screen. But we are unable to implement it with existing SoHoTree framework.

Could you please suggest any work around.

**Describe the solution you'd like**
Would like a way to implement the attached design.

**Describe alternatives you've considered**
Appending the icon in with the text of the tree node

**Additional context**
![image](https://user-images.githubusercontent.com/55240054/91314555-4ed6bb80-e7d4-11ea-97a0-6b67c446c140.png)

**Comment by tmcconechy** [comment]
In terms of a workaround im not seeing much..

1) If you do it like this with markup https://github.com/infor-design/enterprise/blob/master/app/views/components/tree/example-index.html#L8 just add the icon inline (and then add some css to move it a bit)

```
<span class="tree-text">Leadership <svg class="icon icon-info" focusable="false" aria-hidden="true" role="presentation">
     <use href="#icon-info-alert"></use>
  </svg>
</span>
```
This maybe means you can "manually" append the icons later after loading the tree. Probably not easy

2) However if adding as JSON its encoding the html. So can see the bug here:

```
api.addNode({text: 'New Item 1.2 <svg class="icon icon-info" focusable="false" aria-hidden="true" role="presentation"><use href="#icon-info-alert"></use></svg>', parent: 'new1', disabled: true});
```

**Comment by krishnakotaInfor** [comment]
It is dynamic tree on conditional and the inline html is not working.
We are using the below codeto form a new tree.

                   this.ProductTree.push({
                        id: "RoadmapFileId",
                        text: "SubProcessors", //Here info icon should be appended
                        icon: "icon-plusminus-folder-open",
                        href: "#",
                        children: []
                    })

**Comment by tmcconechy** [comment]
Yes i understand - its not allowing contents there at the moment

**Comment by jbrcna** [comment]
**QA Passed**
works in both themes
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/tree/example-plus-minus-folders.html
![image](https://user-images.githubusercontent.com/56722184/93203336-d89bf800-f786-11ea-8395-1b066d58b041.png)

**Comment by CindyMercadoReyes** [comment]
Attaching the BDD to this new enhancement. 
[BDDStory_github4305.docx](https://github.com/infor-design/enterprise/files/5225221/BDDStory_github4305.docx)
