### ISSUE TITLE
Accordion: Request for having line separators

### ISSUE THREAD

**Issue by sharmainerivera** [infor-design/enterprise#4308]
**Is your feature request related to a problem or use case? Please describe.**
Items on expander under the likes of "favorites" or "bookmarks" can come from different categories and can be hard to categorize when they are altogether on one expander.

![image](https://user-images.githubusercontent.com/61222084/91416791-75ebc680-e882-11ea-98ea-6c6e89a76bee.png)

**Describe the solution you'd like**
For grouping the items, a line separator will be helpful to categorize them that looks like this:

![image](https://user-images.githubusercontent.com/61222084/91417129-e4c91f80-e882-11ea-8c25-5c3a66a56362.png)

**Additional context**
Application working on: Infor Pathway

**Comment by tmcconechy** [comment]
This should be an OK idea. But as a workaround is it possible to organize them with top level folders or sub folders. This was the intention as it gives meaning for the categories.

**Comment by sharmainerivera** [comment]
Hi, Tim. Thanks for the inputs. Since this is under "bookmarks"/"favorites", it will be convenient for the user to just click on their favorite navigation from that accordion without having to close/open a folder (of categories).

**Comment by tmcconechy** [comment]
Ok, Im not sure that this fits our design. But will leave it in the backlog for future consideration.

**Comment by tmcconechy** [comment]
Descoping this for now. I suggest you use the accordion headers as the separators or levels for the elements for an example see:

https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html
