### ISSUE TITLE
Editor: Selected format is not immediately displayed in the dropdown in the Editor toolbar

### ISSUE THREAD

**Issue by eeriksson429** [infor-design/enterprise#4309]
**Describe the bug**
The selected format (Normal, Heading 1, Heading 2) is not immediately displayed in the dropdown in the Editor toolbar. The correct dropdown value is only displayed after clicking elsewhere and moving focus from the dropdown field. 

**To Reproduce**
1. Go to 'https://master-enterprise.demo.design.infor.com/components/editor/example-index.html'
2. Select any text. 
3. Click the "Normal text" dropdown.
4. Select "Heading 1". 

**Expected behavior**
The text is formatted. The dropdown now shows "Heading 1". 

**Actual result**
The text is formatted, but the dropdown still shows "Normal text". 

**Version**
- ids-enterprise: v4.31.1 and v4.32.0-dev

**Platform**
 - Infor Application/Team Name: Infor Homepages
 - OS Version: macOS Catalina
 - Browser Name: Chrome
 - Browser Version: 84.0.4147.135 (Official Build) (64-bit)

**Comment by EdwardCoyle** [comment]
Discovered that this specifically happens when only selecting a portion of the text.  If you triple-click an entire paragraph, for example, the FontPicker text is updated immediately.  There is most likely something related to selection causing the visual update not to occur.

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
