### ISSUE TITLE
SOHO-7230: The position of custom select menu options and zoom out/in

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#431]
When the user zoom in or out and the select menu with options is visible then the position top/left has not been recalculated and the menu disappearing.

*Steps to reproduce*

1. Open custom select menu with options.
2. Zoom in / out.
3. Observe the behaviour. Attached [See select_zoom.mov in jira](https://jira.infor.com/browse/SOHO-7230) to present the behaviour.

![select_zoom](https://user-images.githubusercontent.com/3249601/60602321-9523bc80-9d81-11e9-8cc4-d59dbb26478b.gif)

*Expected*

The select menu with options stays sticked to the top/left position of the original select element while zooming in/out.

**Comment by EdwardCoyle** [comment]
This one came from JIRA before we migrated, and it seems to be missing some context... including that example video.

Any idea what "custom select menu" is?  Popupmenu?  Dropdown?  Any idea how to reproduce?

**Comment by clepore** [comment]
@EdwardCoyle I updated the description with a link to the original jira ticket.

**Comment by tmcconechy** [comment]
Im pretty sure i remember this one and it was
1. go to http://master-enterprise.demo.design.infor.com/components/dropdown/example-index.html
2. open the list
3. zoom the browser page
4. at this point the dropdown is not over the list

BUT now im seeing that the list closes which kinda solves it.

**Comment by clepore** [comment]
When scaling a browser, the browser has to repaint and some positioning becomes out of whack due to the nature of the process.  Currently our dropdown will briefly become askew and then close, to which the user can then re-open it in all its grandeur, scaled properly.
