### ISSUE TITLE
Datagrid: Column reorder focus when clicked, looks off

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4311]
**Describe the bug**
Datagrid: Column reorder focus when clicked is off

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-reorder.html
2. Hover and click the Vertical '...' in Product Name Column title
3. Hold and see the focus seems off or cut off

**Expected behavior**
Focus should not look like its cut off

**Version**
4.32.0 dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/91440893-e35b1f80-e8a1-11ea-8d08-0a69a201c9e7.png)

![image](https://user-images.githubusercontent.com/45757016/91441242-6f6d4700-e8a2-11ea-9999-36247936720a.png)

**Platform**
All browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This is correct. When you start dragging we make a clone of the header that can be dragged. And it has a fixed size that can be different than the column, to make it be easier to drag and not HUGE.

So closing as we wont change this at this time
