### ISSUE TITLE
Dropdown: Add ComboBox UI feature for manual text entry

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#4314]
The Infor System i Workspace team would like to re-open our design request that was originally logged as JIRA SOHO-4315 to create a "Combo" drop-down control, similar to the one supplied by VB.NET, that allows the user to enter a value or select from a list (where the list may contain descriptive values rather than the actual value). This allows a single field to be used by both novice and experienced application users.

This log was being progressed then was sudddenly closed without consultation with our team so we wish to re-open this request. See the JIRA SOHO-4315 for more detailed history and internal discussion.

**Comment by tmcconechy** [comment]
Transfered this issue to dev from design queue. Don't think this needs design but it possess technical issues. But Maybe we can add it on a future version.

**Comment by tmcconechy** [comment]
Descoping some older issues we wont be able to get to. But its possible this might work in 5.0 and we can revisit this when thats done.
