### ISSUE TITLE
Lookup: Add option to use full screen in small browsers

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#4319]
**Is your feature request related to a problem or use case? Please describe.**
A regular modal has the option to be used in full screen mode in smaller browsers. We would like to have this option for Lookups as well. Currently when using a lookup component and seeing it on a mobile screen the Lookup content is often to wide to show it in portrait mode and in landscape mode no content can be seen. If the Lookup was shown in full screen mode I believe it would be easier to use on a phone or other device with a small screen or lower resolution.  

**Describe the solution you'd like**
I think the Lookup component would work better for small screens if an option to view it in full screen was added similar to or equal to the Modal options with the fullsize='responsive' option and the breakpoint setting. I think it's very good if it has the same responsive behaviour as in the Modal.

**Describe alternatives you've considered**
Tim also suggested using a Custom Modal in the Lookup, but I believe it would be easier to use with a Lookup option than with a custom modal, specially if there are more than one Lookup to update.

**Additional context**
This is not urgent from our side, but there are some application teams that use Lookups in their widgets in Homepages and I believe this option would be good to improve the user experience on phones and small tablets.

And what application do you work on? Homepages

**Comment by tmcconechy** [comment]
I think we just need to add a modalSettings option to lookup and pass this to the underlying modal.
Plus maybe an example of it full screen.

**Comment by jbrcna** [comment]
QA Passed.
https://main-enterprise.demo.design.infor.com/components/lookup/example-index.html
<img width="863" alt="image" src="https://user-images.githubusercontent.com/56722184/210480073-92dfb000-92bd-40b6-9475-20c7e0bb864e.png">

**Comment by CindyMercadoReyes** [comment]
Adding BBD to this ticket. 
[BDDStory_github4319.docx](https://github.com/infor-design/enterprise/files/10345562/BDDStory_github4319.docx)
