### ISSUE TITLE
SOHO-7209: Datagrid: ResetColumns doesn't reset back to initial state

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#432]
Hello,

I found an issue running our Selenium tests, where I tried to "Selenium click" on Reset to Default button of Datagrid.
It causes resetting Datagrid not to original/default state (as written by programmer), but to "same state as before click".

I went thru Datagrid's code and I have several points which can cause it.
In function    

```
// Reset Columns from the Menu Option
    resetColumns: function () {
      if (this.canUseLocalStorage()) {
        localStorage.removeItem(this.uniqueId('columns'));
        localStorage[this.uniqueId('columns')] = '';
      }

      if (this.originalColumns) {
        this.updateColumns(this.originalColumns);
        this.originalColumns = this.columnsFromString(JSON.stringify(this.settings.columns));
      }
    },
```
It seems that inside updateColumns
```
    //given a new column set update the rows and reload
    updateColumns: function(columns, columnGroups) {
      this.settings.columns = columns;
```
you assign 
this.setting.columns = this.originalColumns;
and after function updateColumns()
you assign it back : 
```
this.originalColumns = this.columnsFromString(JSON.stringify(this.settings.columns));
```
It is not logical and simply speaking this "mess" causes problems in our test code,
because of messy work with those value values resetColumns() doesnt work well with our Selenium tests, and with Selenium tests it causes resetting to "same state", not default state of Datagrid which was set by programmer.

In my opinion it is not good idea to assign anything to this.setting.columns, because it seems to me that it was meant to contain initial/default settings of datagrid cols set by programmer (which should be immutable), 
not actual effective column values which is set by user interacting with datagrid (resizing, drag&drop, show/hide cols).
I found more of this assignment inside Datagrid's code.

Then you should not need this.originalColumns property I hope.
I am suggesting to use something like "effectiveSetting" or "effectiveColumns" which can be changed dynamicaly during work but dont mess it with initial settings of datagrid.

I hope you can help us with this.

**Comment by tjamesallen15** [comment]
Can you give me the page where we can replicate the issue? Also image capture might help! Thanks!

**Comment by tmcconechy** [comment]
Decided to descope this issue as its too big of a change. For my testing what im doing is this....

https://github.com/infor-design/enterprise/blob/master/test/components/datagrid/datagrid-api.func-spec.js#L6

https://github.com/infor-design/enterprise/blob/master/test/components/datagrid/datagrid-api.func-spec.js#L39

Unfortunately its too woven in that the array attached is mutating.
