### ISSUE TITLE
Tree: "sortable" object on API not available when re-ordering tree items 

### ISSUE THREAD

**Issue by sharmainerivera** [infor-design/enterprise#4323]
**Describe the bug**
"Sortable" object from Tree's API is no longer available upon re-ordering the tree items.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tree/example-sortable.html.
2. Drag "History" to be the first one among the items under "Leadership".
3. On the console, check the Tree API: $('#addnode-tree').data('tree')

**Expected behavior**
The object Sortable is no longer showing on the Tree API:
![image](https://user-images.githubusercontent.com/61222084/91839287-61903b00-ec81-11ea-9f8f-e4ece488867d.png)

Checked on 4.29 version, the Sortable object is there:
https://4290-enterprise.demo.design.infor.com/components/tree/example-sortable.html

![image](https://user-images.githubusercontent.com/61222084/91839403-94d2ca00-ec81-11ea-8311-30b839189840.png)

**Version**
- ids-enterprise: 4.32.0-dev / 4.30.1

**Platform**
 - Infor Application/Team Name: Infor Pathway
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 84.0.4147.135 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
The sortable object is just a variable reference and not an external published API. I cant see what it would be very useful for anything and i don't think we can easily add it back. I guess it showed the last dragged tree item. But what you should use is the `sortstart` and `sortend` events if you want the drag info. It should be published there?

Can you try that? Dont think we want an indeterminate non/public object for that - events should work if you need dragged info?

**Comment by sharmainerivera** [comment]
Hi, Tim. We can now close this bug. We'll be using the available sort objects as you suggested. Thank you!
