### ISSUE TITLE
Flex toolbar: Title element has scroll

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#4325]
**Describe the bug**
The flex toolbar title element has scroll. Title element is only 20px high, but its inner h2 is 23px

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/toolbar-flex/example-index?theme=uplift&variant=light

**Version**
- ids-enterprise: 4.31.2

**Screenshots**
![image](https://user-images.githubusercontent.com/1101770/91842928-30017a80-ec55-11ea-979d-9b4c70936e93.png)

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://4320-beta0-enterprise.demo.design.infor.com/components/toolbar-flex/example-index?theme=uplift&variant=light&colors=0066D4 across all browsers, OS and devices.
