### ISSUE TITLE
RTL Tabs: Tab default focus is off and error icon misplaced

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#4326]
**Describe the bug**
When in RTL mode the default focus for a tab in a modal is shifted to the left. 
When an invalid icon is also shown it is misplaced.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs/test-modal-error.html?locale=ar-SA
2. Click on 'Add Context'
3. Notice that the default focus is placed to the left of the tab title.
4. Write a space in the Last name field
5. Notice that the error icon is misplaced

**Expected behavior**
The tab focus shoud be below the title.

I believe the text should be right aligned to give space for the icon to the left in RTL mode, it is left aligned when visible in LTR mode. It  seems to be a padding that is the same way in both LTR and RTL that should be switched in RTL to make room for the icon on the left side of the text.
I also noticed that removing the margin-right: 11px on the icon in LTR mode makes the icon appear in a better position in the LTR case (it might be needed as a left margin in RTL mode though).

**Version**

- ids-enterprise: 4.31.2

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/91842085-aa30ff80-ec53-11ea-957c-e9f4fe3f72bf.png)
![image](https://user-images.githubusercontent.com/8664975/91842485-6f7b9700-ec54-11ea-8bd8-c87af0082fa1.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**
The error icon seems to be more misplaced in LTR mode, see;
![image](https://user-images.githubusercontent.com/8664975/91842162-d0ef3600-ec53-11ea-88bf-9c713757eed0.png)

When removing margin-right: 11px this will instead (which looks much better) be:
![image](https://user-images.githubusercontent.com/8664975/91843316-e2394200-ec55-11ea-9bb3-75d2f46dcdb7.png)

**Comment by tmcconechy** [comment]
This also relates to https://github.com/infor-design/enterprise/issues/4332

**Comment by ericangeles** [comment]
Picking up this too, @tmcconechy

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/93211611-118e9980-f794-11ea-8c74-dff15f7adfe6.png)
![image](https://user-images.githubusercontent.com/45757016/93212042-a1ccde80-f794-11ea-8b67-b190609fea09.png)
