### ISSUE TITLE
SOHO-7177: 4.0 Mask - changing percent value with delete or backspace key loses the percent sign

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#433]
When changing a percent value using the delete or backspace keys, the percent sign disappears.

Using test-new-mask-prefix-suffix.html which uses suffix or example-fields-with-symbols.html which uses showSymbol to duplicate the issue.
- Enter a percent value in the Percentage Suffix field or Percentage Input field depending on the test being used
- Using either the backspace or delete key, remove part of the value
- You should see the percent sign disappear
- Leaving the field does not format the value with the percent sign

**Comment by tmcconechy** [comment]
Closed via last pr.
