### ISSUE TITLE
Tabs: RTL Tabs do not display focus/activated state correctly

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#4332]
**Describe the bug**
In RTL mode, it appears any horizontal Tabs list (in-page or Header) no longer:
- correctly positions the focus state in any case
- correctly positions the "activated" state (animated bar) in cases where tabs are overflowed

**To Reproduce**
- Go to http://localhost:4000/components/tabs/example-index.html?theme=uplift&variant=light&colors=0066D4&locale=ar-EG
- Focus the tab list, and use the arrow keys to navigate the tabs.  Notice the focus state isn't located on the focused Tab's boundaries.
- Shrink the width of the page so the Tabs on the right spill into overflow.
- Click or press enter to activate any Tab.  Notice the animated bar doesn't properly line up to the newly activated tab.

Also saw this on Header tabs: http://localhost:4000/components/tabs-header/example-add-tab-button.html?theme=uplift&variant=light&locale=ar-EG

**Expected behavior**
The focus state should be placed correctly around the currently-focused tab, and the animated bar should line up with the text of the currently-active tab.

**Version**
Tested back to https://4120-enterprise.demo.design.infor.com/components/tabs/example-index.html?&locale=ar-EG

**Screenshots**
![Screen Shot 2020-09-01 at 2 25 57 PM](https://user-images.githubusercontent.com/3249601/91891503-267d1000-ec5f-11ea-9c94-3fbb5ce328d1.png)

**Additional context**
Possibly related to the scrolling of the Tab List when overflow is present, and/or location of the Add Tab (+) button?

**Comment by janahintal** [comment]
Issue still exists. To reproduce, try playing with tab keys to see focus when in responsive view. 
https://master-enterprise.demo.design.infor.com/components/tabs/example-index.html?theme=uplift&variant=light&colors=0066D4&locale=ar-EG
![image](https://user-images.githubusercontent.com/45757016/94008283-54c0bc00-fdd5-11ea-9612-e6a6f2fd9187.png)
![image](https://user-images.githubusercontent.com/45757016/94008363-7752d500-fdd5-11ea-82f3-e13fb7151911.png)

**Comment by tmcconechy** [comment]
@ericangeles could you take a look please?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by janahintal** [comment]
This issue is now resolved. Will now move to Done. :)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/96446357-e6401400-1243-11eb-9f68-a877ac112506.png)
