### ISSUE TITLE
Locale: Incorrect M/d/yyyy HH... entries in it-IT.js. Should be dd/MM/yyyy HH...

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4333]
Incorrect M/d/yyyy HH... entries in it-IT.js. Should be dd/MM/yyyy HH...

Screenshot attached (end result: incorrect date format in GRC)

![it-IT](https://user-images.githubusercontent.com/66057969/91953014-5b41a380-ed01-11ea-870e-886c6882d95e.png)

**Comment by tmcconechy** [comment]
This is a duplicate of https://github.com/infor-design/enterprise/issues/4297 and has been fixed in 4.32
