### ISSUE TITLE
Editor: Is Forcing focus changes 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4335]
**Describe the bug**

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
2. Tab to the B button
3. Hit Enter
4. See error - the focus is put into the editor

**Expected behavior**
If possible when keying onto these buttons the focus should not switch into the editor. When contents are selected we have to be careful it still selects. I do have a question on that case if its ok to change state on click/selection?

**Version**
- ids-enterprise: [e.g. v4.32]

**Platform**
- Chrome / Mac (Any)

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-31969

**Comment by janahintal** [comment]
QA Passed. 
**Observation**: When I tab to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
the focus is only going thru Normal Text field in the toolbar and not on the remaining buttons/fields. 
![image](https://user-images.githubusercontent.com/45757016/96094051-70fcd800-0eff-11eb-852e-f053bbe30033.png)
