### ISSUE TITLE
Locale: Wrong tooltip translation for the 'Show More' ellipsis icon

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4337]
Swedish: Wrong tooltip translation for the 'Show More' ellipsis icon.  This text says “show less” (Visa mindre) when it says "Show More' In the English version

Issue reported in GRC

Screenshot attached
![ShowMore](https://user-images.githubusercontent.com/66057969/92013218-c0bb8180-ed4d-11ea-8990-43fb1a13ed3b.png)

Swedish translations are managed by Henry W.

**Comment by tmcconechy** [comment]
Are we sure Henry knows how to get to issues here?

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by tmcconechy** [comment]
waiting for new translations

**Comment by hwondergem** [comment]
Updates/correction currently in progress. Expected mid-October.

**Comment by hwondergem** [comment]
Actually, our linguist already corrected this earlier. 
Can we check the latest translations on this page? 
https://4320-beta0-enterprise.demo.design.infor.com/components/locale/test-translations.html?locale=sv-SE
If not, where?

**Comment by tmcconechy** [comment]
Seems like its correct...Your right.

1) Go to https://4320-beta0-enterprise.demo.design.infor.com/components/locale/test-translations.html?locale=sv-SE
2) Type ShowMore in the filter for ID in the grid - Says "Visa Mer". That seems ok right (I speak danish and its definitely not saying Show less now)

I think GRC must still be on an older version. Closing for now but confirm, please
