### ISSUE TITLE
SOHO-7138: 4.0 Mask does not format percentage values according to Locale

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#434]
When an input field is using a Mask pattern for suffix of percent sign, the value does not get properly formatted according to the Locale.

Most locales are either '#,##0 %' or '#,##0%; tr-TR has '%#,##0'; ar-EG has a different symbol.

We do have the ability to set the appropriate percent sign on the Mask options, but the Mask does not properly format the value according to Locale.

Wondering if percentFormat should be part of the Mask options?

Landmark does not use currency format, but believe a similar issue exists for it.

See the attached screenshots and use the attached test-new-mask-prefix-suffix.html that has changes for suffix.

To duplicate, using the attached test
- Enter a value in the Percentage Suffix input field
- Enter the same value, without a suffix, in the Input Value field
- Compare the Percentage Suffix value with the Transformed Locale Suffix value which was created with the Input Value field and Locale.formatNumber using percent options.

Expectations are the values match.

**Comment by tmcconechy** [comment]
This was already possible so i added a test and a example on the PR. You can do this by just setting the pattern to the currencyFormat of the current locale.

See: https://github.com/infor-design/enterprise/pull/2816/files#diff-15406fd1708b6d7320c768958d49318aR18

**Comment by brianjuan** [comment]
Hi @tmcconechy, does the percentage sign is only added when the typed numbers are in 3 digits and not in 1 and 2 digits (i.e 5% and 10%)?

**Comment by tmcconechy** [comment]
Hmm i think you have a point. I will take another look.

**Comment by brianjuan** [comment]
Thanks @tmcconechy.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/mask/test-percent-locale
http://master-enterprise.demo.design.infor.com/components/mask/test-percent-locale?locale=ar-SA
http://master-enterprise.demo.design.infor.com/components/mask/test-percent-locale?locale=tr-TR
Passed QA in all browsers.
