### ISSUE TITLE
Datagrid: Export to CSV with special characters (é, à, ü, ...)

### ISSUE THREAD

**Issue by afarn** [infor-design/enterprise#4347]
Export to CSV with special characters (é, à, ü, û, ...) does not generate them correctly.

<img width="723" alt="datagrid" src="https://user-images.githubusercontent.com/40360119/92486565-89851e80-f1ec-11ea-8ef1-3efc4c62b1bf.png">

![Excel_file](https://user-images.githubusercontent.com/40360119/92486770-c7824280-f1ec-11ea-9903-bc31251e9a12.png)

**Comment by EdwardCoyle** [comment]
Reported on [MS Teams](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1599569430908?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1599569430908&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=General&createdTime=1599569430908)

**Comment by sanx72** [comment]
FYI - also had this issue reported from one of our French customers. We found that the Unicode BOM was missing from the CSV file. If we edited the CSV file in Notepad, then saved as Unicode (not UTF-8) then opened the file again in Excel, characters were displayed OK.

**Comment by tmcconechy** [comment]
I do have a question if this is actually fixed since the example page at https://master-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html shows some of these characters and the export appears to work?

**Comment by sanx72** [comment]
@tmcconechy yes it is the CSV one that doesn't work, which I believe is the default Export option on the data grid (in this example they are manually added export button options). The exportToExcel API method appears to work, but puts the XML wrapper around the data that then throws warnings in Excel when opened so, for our application, this is not acceptable.

**Comment by tmcconechy** [comment]
Yeah cant seem to get around the warning unless we include a complete excel parser. Will look at the CSV issue soon

**Comment by sanx72** [comment]
@tmcconechy Just looked at the solution for this, and the code appears to be setting a Unicode BOM but then encoding the save file as charset=UTF-8. You might want to review this again as in our own CSV save, we had to convert the CSV data (which will be in a UTF-16 string) to a byte array with a BOM (FF FE) and then put that into the Blob to save as charset=UTF-16. This was the only way we could get Excel to recognise non-ANSI characters.

**Comment by tmcconechy** [comment]
@sanx72 how does that translate to a change in the code? Do you have a recomendation?

**Comment by deep7102** [comment]
@sanx72 I tested with excel on mac and windows using different browsers and looks fine those all the chars on test-page below, do you having some other set of chars you see issue. Please tell info browser, operating system or excel version etc
http://localhost:4000/components/datagrid/example-export-from-button.html

**Comment by sanx72** [comment]
Have you tried this export with **sep=;** (i.e. for French or other countries where comma is used in numerics for decimal). That was where I hit a problem anyway, with anything other than **sep=,** Excel import failed with UTF-8 BOM, but OK with UTF-16 BOM.

`sep=;
"Product Id";"Product Name";"Quantity";"Price";"Status";"Extra";"Filtered"
"2142201";"Compressor";"1";"500,00";"OK";"ç ñ ÄËÏÖÜ äëïöü";"true"
"2241202";"Different Compressor";"2";"210,99";"";"àèìòù";"true"
"2342203";"Compressor";"1";"120,99";"";"áéíóú";""
"2445204";"Another Compressor";"3";"2.345,00";"OK";"ية (مصر";"true"
"2542205";"I Love Compressors";"4";"210,99";"OK";"'=HYPERLINK(""http://www.google.com"";""Please Click For More Info"")'";""
"2642205";"Air Compressors";"41";"120,99";"OK";"";""
"2642206";"Some Compressor";"41";"123,99";"OK";"";"true"`

![image](https://user-images.githubusercontent.com/44396995/95722563-03854900-0c6c-11eb-81a9-d0339fb3b185.png)

**Comment by afarn** [comment]
I tried with the sep=";" but it doesn't work.

**Comment by afarn** [comment]
For the separator ";" it works with this condition in excel.js **(line 368)** :
if (separator.firstLine && separator.char ! == ',' **&& separator.char ! == ';'**) {
       csv.unshift ([`sep = $ {separator.char}`]);
  }

**proposition :**
For Angular, I propose to change the declaration of the exportToCsv function (but it is not mandatory) as follows:
exportToCsv(fileName: string, customDs: Object[], separator: string **| {}**)

and for example we can call this function like: 
exportToCsv(‘toto’, undefined, **{  firstLine: false, char: ' ;' }**) ;

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. :) 
![image](https://user-images.githubusercontent.com/45757016/97152706-4129bc00-17ac-11eb-846a-a77c97f2c992.png)
