### ISSUE TITLE
SOHO-6990: Pagination - "updateColumns" to set a header group causes paging bar to have incorrectly disabled state

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#435]
> Calling `updateColumns(getColumns(), getColumnGroups());` to set a header group causes paging bar to have incorrectly disabled state

When using paging: indeterminate with the source callback function setting grouped headers after fails to set the paging buttons correctly.

See attached sample where all paging buttons should be disabled.

Setting the columns before the data is set and it will work ok but we need to update the column groups with new header text values when the data comes back.

**Comment by tmcconechy** [comment]
We were able to fix the issue by update the way the example is done. No code changes needed.
See: http://master-enterprise.demo.design.infor.com/components/datagrid/test-group-headers-update-columns-landmark.html

Source: https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-group-headers-update-columns-landmark.html

**Comment by CindyMercadoReyes** [comment]
Hi @deep7102 The datagrid doesn't appear at all on Win 10 IE11. Please see the screen shot attached. 
![bs_win7_ie_11 0](https://user-images.githubusercontent.com/39101346/48574890-63d3aa80-e8de-11e8-9181-65cde0396a91.jpg)

**Comment by tmcconechy** [comment]
Im guessing the promises https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-group-headers-update-columns-landmark.html#L99 maybe you can include @EdwardCoyle polyfil, but i havent seen that been done in an example.

**Comment by brianjuan** [comment]
https://4130-beta0-enterprise.demo.design.infor.com/components/datagrid/test-group-headers-update-columns-landmark.html
Passed QA testing on all browsers.
