### ISSUE TITLE
Dropdown: "noSearch" dropdown not working with NVDA screen reader

### ISSUE THREAD

**Issue by chaseerickson** [infor-design/enterprise#4350]
**Describe the bug**
With NVDA screen reader enabled, pressing the up/down arrow keys within an expanded "noSearch" dropdown appears to focus other elements, not the dropdown content. All other dropdowns function as expected with NVDA enabled, and the "noSearch" dropdown functions as expected when NVDA is disabled.

**To Reproduce**
1. With NVDA on, focus on a "noSearch" dropdown (example: http://localhost:4000/components/dropdown/example-no-search-lsf.html)
2. Press 'enter' to expand the dropdown.
3. Press the 'down' arrow key to cycle through the contents.
4. Observe that other elements are cycled, not the dropdown contents.

[nvda.docx](https://github.com/infor-design/enterprise/files/5190466/nvda.docx)

**Expected behavior**
Pressing the up/down arrow keys within an expanded dropdown should cycle through the contents of the dropdown,

**Version**
Master

**Screenshots**
Video attached (inside docx file)

**Platform**
 - Infor Application/Team Name: LSF
 - Device: Laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 85.0.4183.83 (Official Build) (32-bit)

**Additional context**

**Comment by tmcconechy** [comment]
1. That video isn't working. Perhaps try a different format and zip and attach.
1. NVDA isnt one of the primary screen readers we test. What happens in Chrome Vox / Jaws? If i recall NVDA might have a setting to use arrow keys but it sounds like NVDA is taking over the arrow key maybe? If this is the case i wonder what we could do?

**Comment by chaseerickson** [comment]
It seemed like an NVDA key override issue initially, but the problem only occurs when using "noSearch" dropdowns; all other dropdowns function properly with arrow keys using NVDA. When using Vox and Jaws, similar issues occur, and only with "noSearch" dropdowns (the dropdown contents highlight using arrow keys but are not read by the screen reader). Attached is a new zipped folder with recordings of NVDA, Vox, and Jaws using the "noSearch" dropdowns. 
[screen_readers.zip](https://github.com/infor-design/enterprise/files/5197907/screen_readers.zip)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
