### ISSUE TITLE
Datagrid: Decimal data type returns "NaN" value on invalid input

### ISSUE THREAD

**Issue by sharmainerivera** [infor-design/enterprise#4351]
**Describe the bug**
A NaN value is returned when inputting an invalid value on columns with a decimal data type.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html.
2. Click on any cell under the Price column.
3. Remove the data if there's any. You will get a "Required" icon.
4. Click back on the cell with error and type in a hyphen (-) or any invalid input. The cell returned a "NaN.000" value.

**Version**
- ids-enterprise: 4.33.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/61222084/92570903-08458e80-f2b5-11ea-9154-e816508a8eb8.png)

**Platform**
 - Infor Application/Team Name: Infor Pathway
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 85.0.4183.102 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I think that you can maybe fix this by adding a mask.

```
      columns.push({ id: 'price',  name: 'Price (negative)', field: 'price', align: 'right', formatter: Formatters.Decimal, editor: Editors.Input, filterType: 'integer', editor: Editors.Input, maskOptions: {allowNegative: true}});
```

See mask component then you pass these into the maskOptions https://master-enterprise.demo.design.infor.com/components/mask/test-number-mask-gauntlet.html

**Comment by sharmainerivera** [comment]
Hi, Tim. Yes. Thanks for that.
