### ISSUE TITLE
Datepicker: date highlights issue in mobile view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4352]
**Describe the bug**
The selected date highlight is a bit off

**To Reproduce**
1. Go to https://4290-enterprise.demo.design.infor.com/components/datepicker/example-range.html
2. Click on datepicker and select date range
in this case `Range - select forward ` (Sep 7 - Sep 11)
3. See error

**Expected behavior**
it should look something like this
![image](https://user-images.githubusercontent.com/56722184/92593852-66359e80-f2d4-11ea-8660-f7c3b6662be1.png)

**Version**
- ids-enterprise: [v4.32.0-beta0]

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/92593900-81081300-f2d4-11ea-9573-7dc36f2259ce.png)

**Platform**
Major browsers (Safari, EDGE Chrome)

**Additional context**

**Comment by tmcconechy** [comment]
@jbrcna that link is a bit old. i tried https://master-enterprise.demo.design.infor.com/components/datepicker/example-range.html in mac chrome and it looks fine. But from the screen shot it looks like your using some sort of device simulator? Do we need to know anything else (browsers or steps). To reproduce this issue?

**Comment by jbrcna** [comment]
Thank you for clarifying @tmcconechy , I pasted the wrong link. Here's the updated link with screenshots
https://4320-beta0-enterprise.demo.design.infor.com/components/datepicker/example-range.html?theme=soho&variant=light&colors=0066D4
<img width="349" alt="image" src="https://user-images.githubusercontent.com/56722184/92668885-987de500-f342-11ea-9b52-496e108d89ae.png">

v4.29.0 works just fine
https://4290-enterprise.demo.design.infor.com/components/datepicker/example-range.html?theme=soho&variant=light&colors=2578a9
<img width="352" alt="image" src="https://user-images.githubusercontent.com/56722184/92668964-d2e78200-f342-11ea-9c92-1c8f5751e474.png">


Also in master
<img width="353" alt="image" src="https://user-images.githubusercontent.com/56722184/92669070-16da8700-f343-11ea-9366-d6558112dd78.png">

The screenshots were taken in Mac/Safari using the device toolbar (dev tools). The issue can also be replicated using a real device

**Comment by tmcconechy** [comment]
Yes i can reproduce this:

1. open any range picker and select a range
1. open chrome dev tools - iphone 6/7/8 plus and see the gapping issue

**Comment by jbrcna** [comment]
The issue is now resolved. Thank you!
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/datepicker/example-range.html
![image](https://user-images.githubusercontent.com/56722184/95195336-f51cd480-0808-11eb-8a84-ceb54320c7fd.png)
