### ISSUE TITLE
Datagrid: Search filter is not working as expected 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4353]
**Describe the bug**
Datagrid: Search filter is not working as expected 

**To Reproduce**
1. Go to https://4320-beta0-enterprise.demo.design.infor.com/components/datagrid/example-drilldown.html
2. In the search filter, type '201'

**Expected behavior**
Only the product ID 2142201 should be listed

**Version**
IDS 4320 -beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/92597359-dd216600-f2d9-11ea-99e5-d2865ea65534.png)
![image](https://user-images.githubusercontent.com/45757016/92597371-e3174700-f2d9-11ea-959d-5d02acca3798.png)

**Platform**
All browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This is probably just an issue with the server side "fake" api not doing the correct filtering.

**Comment by tmcconechy** [comment]
Descoping this for now
