### ISSUE TITLE
Multiselect Lookup: Missing "MaxSelected" for restriction on records selection.

### ISSUE THREAD

**Issue by jpatil2** [infor-design/enterprise#4354]
**Is your feature request related to a problem? Please describe.**
User not able to restrict the selection of records for multiselect lookup component.

**Describe the solution you'd like**
Like **"MaxSelected"** property present in dropdown for selection restriction, need to add same with the multiselect lookup component. Or an example showing a way to do this.

**Comment by tmcconechy** [comment]
Probably this would be a datagrid setting.

**Comment by tmcconechy** [comment]
As of 4.53.4 you can use the `afterpaging` event on the lookup. In there you could count the number of selected and then deselect the last one.

Our code would just do the same thing and this is not a common request. So with the event you can do it now so closing.
