### ISSUE TITLE
Datagrid: Truncation with an align right alert when using a row height of extra-small

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4355]
Describe the bug
An alert column with right alignment, the display value is truncated when using a row height of extra-small.  Making the column wider does make the value fully visible.

1. Using the attached test-alerts-right-align.html
2. Select a row height of extra-small from the more menu
3. Notice that the full text value of Alert w Text column is not visible
4. Make the column width wider and the full value is still not displayable

Expected behavior
Making the column wider should be able to view the full text of a right aligned value.

Version
4.33.0-dev

**Comment by claudenbach** [comment]
[Git-4355.zip](https://github.com/infor-design/enterprise/files/5197692/Git-4355.zip)

**Comment by claudenbach** [comment]
Landmark example...

![image](https://user-images.githubusercontent.com/39804038/92646550-38d4fa80-f2ac-11ea-82a5-bfb8b186cf55.png)

**Comment by claudenbach** [comment]
Need a higher priority on this, since Koch KBS has pointed out this issue.

**Comment by tmcconechy** [comment]
We might not have time this sprint but can try....

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-alerts-right-align.html
![image](https://user-images.githubusercontent.com/56722184/93991009-621e7c00-fdbe-11ea-9031-6284f881866d.png)

**Comment by claudenbach** [comment]
Possible for Landmark to have a patch for this in 7.5.3?

**Comment by tmcconechy** [comment]
I don't think that this is a good "bug" to patch. As it introduced a couple issues so for, now there is at least 2 bugs i know of. It should go through the version QA i think which is in progress. Then at that point we can assess but it might be slightly risky for visual regressions

**Comment by pwpatton** [comment]
@tmcconechy what's the eta on a 4.33 release?

**Comment by tmcconechy** [comment]
Between Friday - Tuesday next week (latest)

**Comment by tmcconechy** [comment]
Patched in 4.31.x and 4.32.x
