### ISSUE TITLE
An exception will be thrown when removing the subtab

### ISSUE THREAD

**Issue by zzhblh** [infor-design/enterprise#4356]
**Describe the bug**
An exception will be thrown when removing the subtab.

**To Reproduce**
1. Go to  https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs/test-nested-horizontal-tabs.html
2. Click Tab#2, then click Tab#4, and then click Tab#1.
3. Enter “$('#nested-tabs-container').data('tabs').remove('tab4')”  in the browser console. which calls the remove method in sohoxi.js.
![image](https://user-images.githubusercontent.com/8154831/92692061-3212ba00-f376-11ea-96d3-c6412d5c139e.png)

4. See the error:  Uncaught TypeError: Cannot read property 'length' of undefined.  
![image](https://user-images.githubusercontent.com/8154831/92693330-10b2cd80-f378-11ea-86eb-ef437f3397ea.png)

This error seems to be related to the selector. When I try to remove the ':hidden' of var notATab , there will be no error.
```javascript
//var notATab = '.application-menu-trigger, .separator, .is-disabled, :hidden';
 var notATab = '.application-menu-trigger, .separator, .is-disabled';
....
if (prevLi.is(notATab)) {
  prevLi = this.tablist.children('li').not(notATab)[0];
  count -= 1;
}
```
**Expected behavior**
No error when remove the subtab.

**Version**

- ids-enterprise: [v4.26.2]

**Screenshots**
![image](https://user-images.githubusercontent.com/8154831/92692061-3212ba00-f376-11ea-96d3-c6412d5c139e.png)
![image](https://user-images.githubusercontent.com/8154831/92693330-10b2cd80-f378-11ea-86eb-ef437f3397ea.png)

**Platform**
 - OS Version: [Windows 10]
 - All Browser

**Additional context**
None

**Comment by jbrcna** [comment]
**QA Passed**
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/tabs/test-nested-horizontal-tabs.html
![image](https://user-images.githubusercontent.com/56722184/93208215-d3db4200-f78e-11ea-80ab-2024e771e4b4.png)
