### ISSUE TITLE
Datepicker: specific id results in error in dev tool console

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise#4357]
**Describe the bug**
With a bit unusual string value for input id, error is thrown in the dev tool console

**To Reproduce**

- Open example app in `enterprise-ng`, go to `datepicker.demo.html`

- Change to
```
<input soho-datepicker [attr.id]="field1" name="statechange" dateFormat="MM/dd/yyyy" mode="standard" placeholder="MM/dd/yyyy" [(ngModel)]="model.standard" (change)="onChange($event)"/>
```

- Go to https://github.com/infor-design/enterprise-ng/blob/master/src/app/datepicker/datepicker.demo.ts and add a new public property
```
field1 = 'Date001 (Should Not be "23.02.2017")';
```

- Start server

- Open the app with Chrome, turn on Chrome dev tools. Navigate to date picker example

- Observe the error in the console

**Expected behavior**
Should not throw any errors in the console

**Version**

- ids-enterprise: **4.31.2**. Tested with **4.32.0** also observes the issue.

**Screenshots**
Screenshot of error in dev tool
![image](https://user-images.githubusercontent.com/27772165/92707212-6629b300-f355-11ea-9219-157fd43a1ed6.png)

**Platform**
 - Infor Application/Team Name: ION
 - Device: (if applicable) **N.A.**
 - OS Version: MacOS
 - Browser Name: Chrome
 - Browser Version: Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
If using date picker in a loop, this error can result in UI glitch that not everything is displayed.

**Comment by EdwardCoyle** [comment]
@ahnpnl not totally following this... the string in question `Date001 (Should Not be "23.02.2017")` has some quotes in it, which might prematurely the string while being processed.  This isn't really something our component is handling, more like at the Angular or even standard DOM level.  You should probably either escape or remove the quotes from the string.

**Comment by ahnpnl** [comment]
I agree from Angular side, should do something. But on the other hands, the codes of tooltip should avoid throwing the current error. Currently, that behavior of throwing error cause UI glitch in my application. The codes should handle properly the user input.

**Comment by ahnpnl** [comment]
Moreover, if writing unit tests for that piece of codes, the test would fail for that particular case, which then impacts code quality as well as CI CD pipeline.

**Comment by EdwardCoyle** [comment]
@ahnpnl can you explain the use case for allowing user input to define the `id` attributes of input fields and `for` attributes of labels directly?

**Comment by ahnpnl** [comment]
The data I used for this issue is from a dynamic data which is sent from backend. The data has a string unique property so I use that as id for the input field. I can also use a different string for the `id` or processing the string to follow w3c standard before using it in HTML.

**Comment by tmcconechy** [comment]
I somewhat agree that we shouldn't error. I guess we can encode your ID but this is developer input not user input so you could just change the ID on the end where you feed that in and that might be a bit easier?

**Comment by ahnpnl** [comment]
yes I already did that. On your side there should be a fix to handle too. If we have both sides handle, it will be the best.

**Comment by tmcconechy** [comment]
Going to descope this. We made a fix for id's with `:` but this particular case is an extremely edge case
