### ISSUE TITLE
SOHO-6956: 4.0 Mask does not format decimal correctly with locale

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#436]
There are two issues when using the mask input with a locale and initial values.

The pattern passed is "#.###.###.###.##,00" and the value is "12345678,99".

1) the legacy mask does not format the value correctly; it displays just the first two digits, i.e., 12

2) the new mask does not format the value according to the groups in the pattern being passed; it displays the value with groups of three while the pattern specified the first group of two and then three. 

To duplicate, execute the attached test-new-mask-currencies.html.

Two new fields have been added: decimal 'locale' new and decimal 'locale' legacy.

**Comment by tmcconechy** [comment]
Relates to https://github.com/infor-design/enterprise/issues/441

**Comment by tmcconechy** [comment]
Duplicate of #1800
