### ISSUE TITLE
Calendar: Enable setting a default time on the Day and Week view

### ISSUE THREAD

**Issue by sharmainerivera** [infor-design/enterprise#4364]
**Is your feature request related to a problem or use case? Please describe.**
Having the time always set to 12 AM, the user needs to scroll to find the time they need for booking via the Calendar control in Day and Week view.

**Describe the solution you'd like**
Add a setting to set the default/first time value that can be seen on the Week and Day (eg. 8 AM).

**Describe alternatives you've considered**
Alternatively, the user will just have to scroll through the chart until they get to their desired time

**Additional context**
Desired outcome:
![image](https://user-images.githubusercontent.com/61222084/92827440-6fbe2400-f404-11ea-89ef-0bf59da73f1f.png)

And what application do you work on? Infor Pathway

**Comment by EdwardCoyle** [comment]
Hi @sharmainerivera, I believe this is already possible by way of setting the `weekViewSettings` property on the Calendar's settings object, [as seen here](https://github.com/infor-design/enterprise/blob/55633e16f50c82cb8106fd25508f92ed1b415271/app/views/components/calendar/test-weekview-settings.html#L52-L58).  You can see it in action on [this test page](https://master-enterprise.demo.design.infor.com/components/calendar/test-weekview-settings) if you switch to the Day or Week view -- the start hour is 6:00 AM and the end hour is 8:00 PM.

Please let us know if that works for you.

**Comment by sharmainerivera** [comment]
Hi, @EdwardCoyle. Thanks for the suggestion! We can now close this ticket.
