### ISSUE TITLE
Calendar: Field to set default end and start hours within the calendar control's day and week views

### ISSUE THREAD

**Issue by sharmainerivera** [infor-design/enterprise#4367]
**Is your feature request related to a problem or use case? Please describe.**
Scrolling through the time table finding for the correct time range to plot the user's entry sometimes slow the user to find the correct values.

**Describe the solution you'd like**
As a suggestion, there would be controls to set the default start and end hours within the calendar control in the Day and Week views. This will also allow users to see the configurations in real-time. Something like below:

![image](https://user-images.githubusercontent.com/61222084/93061587-59cf8e00-f6a6-11ea-92bf-ef7cd4d6ddfe.png)

**Describe alternatives you've considered**
weekViewSettings is currently used to set the default time but will be the same for every user.

**Additional context**
Application: Infor Pathway

**Comment by tmcconechy** [comment]
Can you maybe just add these inputs / information to a settings page or dialog? I'm not sure that they are really that useful being on the form like this.

**Comment by sharmainerivera** [comment]
Hi, Tim. I have relayed this information to the customer requesting this. Thanks for verifying. I'll now close this ticket.
