### ISSUE TITLE
Toolbar Menu button items: Add support for Automated testing

### ISSUE THREAD

**Issue by PaulEvansInfor** [infor-design/enterprise#4370]
**Is your feature request related to a problem or use case? Please describe.**
We have a requirement to support Automated testing frameworks in Infor products. This means any parts of a control that perform an interaction should easily be located within the document (via a unique statically named id element or surrogate attribute i.e. "data-auto-uid") the automated test framework can then easily fire a click event to interact with that component and not have to perform complex lookups/searches in order to find the element and trigger the event.

**Describe the solution you'd like**
This issue applies to drop down menus on Toolbars:
When we create a toolbar that has a Menu button (with items that drop down on click) if we assign an attribute such as "data-auto-uid" to each menu item then the attribute is copied to the "live" version of the down menu, but also remains in the original.  If we look in the method "addItemLinksRecursively" we can see a copy of the original menu is created.  In the case of the id property this is moved to the new copy and removed from the old.  In order to support automated testing we need a method of setting the data-auto-uid attribute on the live copy of the menu.  At present if we set the attribute on the original copy of the menu we end up with duplicates of the data-auto-uid attribute which makes it difficult for automated test frameworks to execute a click event on the correct menu item.

**Describe alternatives you've considered**
We could wait until the menu/toolbar is initialised and then apply the data-auto-uid attribute to each menu item, but then the attribute would be applied to the original copy of the menu button and not the new "live" copy that is created by the framework.  We could also use the id element instead, but it would be nice to support data-auto-uid (or other attribute) so automated test frameworks can use a consistent approach to finding page elements.

**Comment by EdwardCoyle** [comment]
@PaulEvansInfor as part of our overall work on adding better support for these automation ids, I've raised #4558 that lets you set a top-level automation ID on the Toolbar element, and passes it to all relevant child elements with unique suffixes.  Using this API will fix the issues you're seeing with the ids being duplicated manually.

**Comment by jbrcna** [comment]
**QA Passed**
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/toolbar/example-index.html
![image](https://user-images.githubusercontent.com/56722184/97986900-62765200-1e15-11eb-9605-5be62effa425.png)
