### ISSUE TITLE
Listview: Remove restriction of "Disable Item Deselection" option for ListView single row selection

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#4376]
The ListView "Disable Item Deselection" option is ineffective when 'selectable' option is set to single.

**To Reproduce**
1. Create a ListView with multiple rows, Have ListViewOptions set so that "Disable Item Deselection" is set to true and "selectable" is set to single
2. Bring up the list view and select a row
3. Click the selected row again and it deselects

**Expected behavior**
Clicking the selected row again should have no effect.

**Version**
v4.31.2

**Platform**
 - Sunsystems v7
 - OS Version: Windows 10
 - Browser Name:  chrome
 - Browser Version: 85.0.4183.102

**Comment by tmcconechy** [comment]
Perhaps we should make a setting: allowDeselect and add it to both datagrid and listview and leave the activation settings alone...

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
