### ISSUE TITLE
SOHO-6841: pager.js needs refactor to remove it's references directly into listview and datagrid.

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#438]
Would like to see a pager where the api is more component-ized. This will aid in making an angular wrapper. 

- All updates and control state would take place only through a pager.settings property or a function in pager. (updatePagingInfo for example).
- Use only events to other components instead of the componentAPI in there now.

- Would like settings to indicate which controls should be used in the pager (instead of using type: 'list' || 'table'). So (firstButton, prevButton, nextButton, lastButton, pageNumInput, pageNumLinks, recsPerPageControl)

- Perhaps type could be relegated to being only used internally in soho controls when the componentAPI is used?!

- Also need pager to not get wrapped inside pager.js so that angular can use the component appropriately (so the pager bar can manually be added in a directive)

```
createPagerBar: function () {
  // .not('soho-pager') so that angular2 component can be used naturally
  this.pagerBar = this.element.prev('.pager-toolbar').not('[soho-pager]');
  if (this.pagerBar.length === 0) {
    if (this.element.is('[soho-pager]')) {
      this.pagerBar = this.element;
    } else {
      this.pagerBar = $('<ul class="pager-toolbar"></ul>');
    }
``
I had to do this to get multiple pager bars to display in an angular sample.

- Test examples on an block list and a standard ul component.

- Add the angular wrapper examples that shows inputs possible strawman

```
<ul soho-pager
    [components]="{first: true, last: true, prev: true, next: true, recsPerPage: true}"
    [pageSize]="pageSize"
    [pageSizes]="pageSizes"
    [pagerInfo]="pagerInfo"
    [firstPage]="hasPreviousPage"
    [lastPage]="hasNextPage"

    (firstSelected)="onFirstSelected($event)"
    (previousSelected="onPreviousSelected($event)"
    (nextSelected)="onNextSelected($event)"
    (lastSelected)="onLastSelected($event)"
    (recsPerPageChanged)="onRecsPerPageChanged($event)"
></ul>
```

**Comment by tmcconechy** [comment]
Merged this issue with https://github.com/infor-design/enterprise/issues/250 since its all the same...
