### ISSUE TITLE
Datagrid: Leading Spaces are removed on Editing Cells

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4380]
**Describe the bug**
Leading spaces are removed on edited cells

**To Reproduce**
https://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html

![leading spaces are removed on editable cells](https://user-images.githubusercontent.com/50192038/93457583-c00c1900-f911-11ea-9039-5ed34996bbcd.gif)

**Expected behavior**
One of our use case is that leading spaces on editable cells should be ratined

**Version**
- ids-enterprise-ng 7.2.4

**Platform**
 - Infor Application/Team Name: User Productivity Team
 - Device: N/A
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Browser Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**
Tagging @lucacolumbu

**Comment by jbrcna** [comment]
**QA Passed**
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
![image](https://user-images.githubusercontent.com/56722184/95981267-f5dce880-0e50-11eb-897c-210bb638b2d6.png)
