### ISSUE TITLE
Pager: Errors when attempting to change rows per page using arrow keys

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#4383]
This can be seen in the editable grid example here:-
https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-editable.html
Expand the Pager control, then select a different Records/age setting using the arrow keys.
<img width="736" alt="exampleEditableGrid" src="https://user-images.githubusercontent.com/49482971/93500911-a1575380-f90c-11ea-9176-f7dd81678236.png">

Examine the console log in DevTools (if using Chrome) and look at the console log. There will be errors:-
<img width="335" alt="UncaughtTypeError" src="https://user-images.githubusercontent.com/49482971/93500922-a6b49e00-f90c-11ea-9905-5f295364ec6e.png">

This does not seem to adversely affect your example, but it causes our application to crash. 
I have got around it for now by checking if the link has a truthy value prior to attempting to remove the attribute and if not returning.

**Comment by jbrcna** [comment]
The issue is now resolved.
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
