### ISSUE TITLE
Locale: Additional dateFormats that include milliseconds.

### ISSUE THREAD

**Issue by StaciGreen** [infor-design/enterprise#4384]
**Is your feature request related to a problem? Please describe.**
We display log results in a grid that include date/times. The difference in the times can be down to the milliseconds. Currently using a single named format we can only display down to the minute. Creating a custom formatter we can manually concat the short with timestamp to get localized down to the second, but we really could use one with millisecond as well. 

**Describe the solution you'd like**
We would like several new dateFormats added to the standard cultures, timestamp with milliseconds, datetime with seconds, datetime with seconds & milliseconds, timezone with seconds, timezone with seconds & milliseconds.

**Describe alternatives you've considered**
If we could at a minimum get the timestamp with milliseconds we can continue concatenating short & timezone short name manually.

**Additional context**
![image](https://user-images.githubusercontent.com/50175666/93511672-27fe3780-f8f1-11ea-9ca2-08d7c888f1f9.png)

**Comment by tmcconechy** [comment]
We dont have any built in formats that contain millis. Do you need one? Or can you just use a custom format.. As you can parse them.

```
 Locale.formatDate(startDate, { pattern: 'yyyy-MM-dd HH:mm:ss.SSS' })
```

**Comment by StaciGreen** [comment]
We want to automatically support localization, so specifying a format would not do that.  We don't want to force a specific separator or 24hr.
Currently we are doing this:  
public DataGridDateTimeWithSecondsAndTZ(
    row: number,
    cell: any,
    value: any,
    column: SohoDataGridColumn,
    item: Object,
    api: SohoDataGridStatic
  ): any {
    const newDate = Soho.Locale.formatDate(value, { date: 'short' });
    const newTime = Soho.Locale.formatDate(value, { date: 'timestamp' });
    const newdtz = Soho.Locale.getTimeZone(new Date(value));
    const newValue = newDate + ' ' + newTime + ' ' + newdtz;
    return Soho.Formatters.Text(row, cell, newValue, column, item, api);
  }

![image](https://user-images.githubusercontent.com/50175666/93513286-a0fe8e80-f8f3-11ea-81f6-2131fba222a4.png)

**Comment by tmcconechy** [comment]
Yeah we probably should add a timestampMillis in each local and /or a datetimeMills ? For each locale then. Makes sense i think

**Comment by StaciGreen** [comment]
Either would work for us, though datetimeMillis probably would be more useful based on most of our data.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
