### ISSUE TITLE
Autocomplete: Shows intermediate results when slow

### ISSUE THREAD

**Issue by tobywicksinfor** [infor-design/enterprise#4387]
**Describe the bug**
When searching via the Autocomplete component and using the AJAX data source, multiple search attempts can be made and the intermediate search results are displayed rather than only showing the results for the last search.

**To Reproduce**

1. Set browser network speed to slow (Chrome > Dev Tools > Network > 'Slow 3G')
2. Navigate to components/autocomplete/example-ajax.html
3. Enter 'A' into the input field (wait until the AJAX request is sent)
4. Delete and enter a 'C' into the input field

Because of the network latency the list of states matching 'A' will be displayed even though they do not match the current 'C' search criteria.

**Expected behavior**
Only the results for the last search is displayed - not the intermediate results.

**Version**
 *  IDS Enterprise Components - v4.30.0-dev
 *  Date: 2020-09-18T03:04:07.350Z
 *  Revision: a29cf67315e7d4492673e8570acdb8b3d025a68a

**Screenshots**
![example-ajax](https://user-images.githubusercontent.com/40477207/93552423-9acde800-f9af-11ea-8423-19bedc7791a1.gif)

**Platform**
 - Infor Application/Team Name: Pathway
 - Google Chrome | 85.0.4183.102 (Official Build) (64-bit) (cohort: Stable)
 - Windows 10 OS Version 1809 (Build 17763.1457)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
