### ISSUE TITLE
DatePicker: Selecting a date far in the past is slow

### ISSUE THREAD

**Issue by tobywicksinfor** [infor-design/enterprise#4388]
When selecting a date using the DatePicker, the user can select the month and year from within the popup. In order to select a date far in the past the user has to scroll through the year list by pressing either the up or down arrow at the top and bottom of the list. Because the selection only changes by one year at a time, navigating to a year far in the past is slow.

**Suggested solution**
It would be ideal if clicking the up or down arrow would jump ahead by larger amount (perhaps 10 years) so that the user can scroll through the list much faster.

**Additional context**
Infor Application: Pathway

![Month Date Selection](https://user-images.githubusercontent.com/40477207/93561379-36b51f00-f9c3-11ea-97d2-f58a52491f0e.PNG)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
