### ISSUE TITLE
Sidebar: Setting/function for hiding/showing the sidebar

### ISSUE THREAD

**Issue by sharmainerivera** [infor-design/enterprise#4394]
**Is your feature request related to a problem or use case? Please describe.**
When hiding the sidebar using the addition of _invisible_ or _hidden_ class or using hide() leaves unnecessary whitespaces, and the components/containers that was left do not adjust to the space it should occupy once sidebar is hidden.

https://master-enterprise.demo.design.infor.com/components/builder/example-builder-subtitle-test.html

**Describe the solution you'd like**
Just like the applicationmenu, there should be a setting or function we can use to hide/show the sidebar as how it is being used on the sample site above. And upon showing/hiding, the components should also be able to adjust on the spaces the sidebar has left.

**Describe alternatives you've considered**
A workaround done was to use the classes to make it hidden or use hide(). As for the whitespaces left by the sidebar, the columns were manually changed to make it full.

**Additional context**
![image](https://user-images.githubusercontent.com/61222084/93752120-c4497680-fc30-11ea-8798-008d83dcdd3d.png)

Hide it using hide() function (a whitespace on the right can be seen)
![image](https://user-images.githubusercontent.com/61222084/93752223-eb07ad00-fc30-11ea-87ed-824bd3971748.png)

And what application do you work on? Infor Pathway

**Comment by tmcconechy** [comment]
We didnt design this pattern for hide/show of the side bar. However, if you close the listview you probably just need to set this rule to correct the widths

```
.builder .main {
    width: calc(100% - 250px); // to 100%
}
```

That being said we could add a button and a slide animation as an official feature.
