### ISSUE TITLE
Tabs: Focus when in responsive view seems off in IE11

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4395]
**Describe the bug**
Tabs: Focus when in responsive view seems off

**To Reproduce**
1. Open IE11 and Go to https://master-enterprise.demo.design.infor.com/components/tabs/example-enable-disable-individual-tabs.html?theme=uplift&variant=light&colors=0066D4
2. Minimize the screen
3. Click Dismissible tab and see error

**Expected behavior**
Focus should look fine and no back focus under the tab in IE 11

**Version**
4.32.0 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/93748922-9b72b280-fc2b-11ea-8867-5d22db1ad6c8.png)

**Platform**
Windows 10 IE 11

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Starting in Oct we dont even need to test IE 11 anymore. This issue also does not seem important enough - we are only addressing P1-P2 in IE11 the rest of the month. So i will just go ahead and close.
