### ISSUE TITLE
Dropdown/Datagrid: Open list in datagrid fails to close when next page is clicked

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#4396]
Open downdown list in datagrid fails to close when next page clicked. It should be closed. This would then look better and also be consistent with the Date Dialog which, when open, does close correctly when next page clicked. 

Steps to reproduce the behavior:-
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-editable.html 
2. Expand a dropdown in the Action Column
3. Click Next page
4. Dropdown remains open

**Expected behavior**
Dropdown should close when clicking Next Page 

**Version**
v4.31.2

**Screenshots**
<img width="779" alt="DDLOpen" src="https://user-images.githubusercontent.com/49482971/93759848-e1675080-fc02-11ea-9ef3-e7cd73a60bb5.png">
<img width="797" alt="DDLStaysOpen" src="https://user-images.githubusercontent.com/49482971/93759932-078cf080-fc03-11ea-9619-0f8645dd0aa4.png">
<img width="835" alt="DateDialogOpen" src="https://user-images.githubusercontent.com/49482971/93759741-b5e46600-fc02-11ea-9733-778dfd5241d2.png">
<img width="769" alt="DateDialogClosed" src="https://user-images.githubusercontent.com/49482971/93759958-11165880-fc03-11ea-9736-8e1227371ab0.png">

**Platform**
 - IDS
 - OS Version: Windows 10. iOS 8 untested
 - Browser Name: chrome, others untested
 - Browser Version: 85.0.4183.102

**Comment by jbrcna** [comment]
**QA Failed**
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
![Large GIF (1378x468)](https://user-images.githubusercontent.com/56722184/95071305-05b34900-073c-11eb-80c7-b6b5c13622ba.gif)

**Comment by tmcconechy** [comment]
@jbrcna can you test again. I think the fix wasnt deployed correctly

**Comment by jbrcna** [comment]
This issue is now resolved. Thanks @tmcconechy 
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
