### ISSUE TITLE
Editor: Text color name is undefined in overflow menu

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#4398]
**Describe the bug**
When the editor is so small so that the Text color action is available in the ... overflow menu it's label is "undefined"

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
2. make the browser window so small so that the text color button does not fit the toolbar (hint: use device toolbar mode in dev tools)
3. click the ... menu

**Expected behavior**
The text color action should have "text color"

**Version**

- ids-enterprise: v 4.32.0

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/93785041-edb4d300-fc2d-11ea-9055-e6ba19629735.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
Found in https://github.com/infor-design/enterprise/issues/4296

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/95166499-95123800-07e0-11eb-8f59-cc8518c42a3b.png)
