### ISSUE TITLE
SOHO-6820: Locale/Mask: Support `groupSize` for thousands separator

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#440]
Original issue:  http://jira.infor.com/browse/SOHO-6820

----

The Mask object needs to support the groupSize property which indicates how the thousands separator is formatted into the value.

While the default value is [ 3 ], there are two known locales supported by Sohoxi that have different values: hi-IN has a groupSize of [ 3, 2 ] and es-US has a groupSize of [ 3, 0 ].

The Mask object and Locale object need to be in sync when formatting numbers; please reference SOHO-6819 for the Locale object.

**Comment by tmcconechy** [comment]
Requires https://github.com/infor-design/enterprise/issues/441 first before the mask part can be done. We might need to defer this to later.

**Comment by tmcconechy** [comment]
I tested this after implementing #441 and now after having that merged
- check on on this page http://localhost:4000/components/mask/test-number-mask-gauntlet.html?locale=hi-IN
- Way Longer Number (1,00,00,00,000) is showing correct
- But typing in the field doesnt work it only shows the group after 3 still
- test on nl-NL (3,3), en-US (3,0) and hi-ID (3, 2) and this covers the 3 different cases across all locales

**Comment by tmcconechy** [comment]
Moving this issue forward a sprint as it was not picked up. But this is ready to work on. Maybe a good one for @EdwardCoyle when you get a chance.

**Comment by EdwardCoyle** [comment]
Just marking "reopened" because the Mask part's not done yet.  Picking up that part of this issue.

**Comment by EdwardCoyle** [comment]
Need to switch gears temporarily, so here are some notes....

Steps for the mask part that I will be implementing:
- [ ] Pass the locale string to the Mask Input component
- [ ] Mask Input component passes the locale string to the Mask API
- [ ] API uses the locale to pass the correct strings/formats/etc to the Number Mask (should probably just make it pass to all mask functions for future proofing)
- [ ] Modify `addThousandsSeparator()` in `masks.js` to get a correctly formatted string for the locale (was trying to use `Locale.toLocaleString()` for this, but it may not work).

**Comment by brianjuan** [comment]
http://localhost:4000/components/mask/test-number-mask-gauntlet.html
http://localhost:4000/components/mask/test-number-mask-gauntlet.html?locale=nl-NL
http://localhost:4000/components/mask/test-number-mask-gauntlet.html?locale=hi-IN
http://localhost:4000/components/mask/test-number-mask-gauntlet.html?locale=ar-EG
Passed QA testing on all browsers, moving to Done.
