### ISSUE TITLE
290 Security Vulnerabilities need to be Mitigated reported by AppScan

### ISSUE THREAD

**Issue by rperk-infor** [infor-design/enterprise#4401]
We are unable to get our product through Infor ISO review because AppScan is reporting that you have 290 in-scope vulnerability findings. The Infor ISO team want these to be mitigated.

SohoXi version is v4.14.0

[Sohoxi Javascript - Web scan - 9-15-20 353PM_20200918_0424.xlsx](https://github.com/infor-design/enterprise/files/5260545/Sohoxi.Javascript.-.Web.scan.-.9-15-20.353PM_20200918_0424.xlsx)

**Comment by tmcconechy** [comment]
@rperk-infor - probably shouldn't post the scan results so i removed it. I started a new scan on 4.32 but as of 4.31 we are in compliance and all flaws are mitigated. For 4.14 i can say thats probably less compliant.

Closing this issue. Please ping me on Ms teams for discussion on this topic. Also in the future please use the issue template https://github.com/infor-design/enterprise/issues/new/choose
