### ISSUE TITLE
Tree: Some icons color are not that visible when in Subtle High Contrast

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4402]
**Describe the bug**
Tree: Some icons color are not that visible when in Subtle High Contrast

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tree/example-badges.html?theme=soho&variant=contrast&colors=0066D4
2. Notice the '4' icon in pin color is not that visible in the current theme and variant

**Expected behavior**
All icons should look fine and visible on all themes and variant

**Version**
4.32.0 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/93871269-f3c7b400-fd00-11ea-85ff-69b521ccad71.png)

**Platform**
All browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping for now
