### ISSUE TITLE
Favorites: Rename to toggle button

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4405]
**Describe the change**

We decided favorites is not a component it should be on the toggle buttons page and classified there.

- 'Favorites' should have to be renamed to 'Toggle' and folded under the Button list in the Enterprise component list.
- 'Favorites' page removed from here https://design.infor.com/code/ids-enterprise/latest/favorites and shown as a toggle a button example
- Anywhere in code where it's called "Favorites" may have to be updated.

**Expected behavior**
Nothing just renaming/categorizing

**Version**
- ids-enterprise: [ v4.32]

**Platform**
 - All/Chrome

**Additional context**
https://jira.infor.com/browse/HLPE-299

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![Uploading image.png…]()
