### ISSUE TITLE
SOHO-6819: 4.0 Locale needs to support groupSize for thousands separator

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#441]
The Locale object needs to support the groupSize property which indicates where the thousands separator is placed.

The 3.5 controls were using Globalize which had the groupSize property and when formatting a number would properly format the thousand separator. Two cultures in 3.5 had a groupSize other than [ 3 ] defined: hi-IN with [ 3, 2 ] and es-US with [ 3, 0 ].

As noted below, the examples from 4.0 are not being formatted properly while the 3.5 examples are formatted properly.

Examples from 4.0:
```
Locale.currentLocale
{name: "hi-in", data: {…}}data: __proto__: Objectname: "hi-in"__proto__: Object

Locale.formatNumber(123456789.12, {style: 'decimal', round: false, minimumFractionDigits: 2, maximumFractionDigits: 2})
"123,456,789.12"
```

```
Locale.currentLocale
{name: "es-us", data: {…}}

Locale.formatNumber(123456789.12, {style: 'decimal', round: false, minimumFractionDigits: 2, maximumFractionDigits: 2})
"123,456,789.12"
```

Examples from 3.5:
```
Globalize.culture("hi-IN")
{name: "hi-IN", englishName: "Hindi (India)", nativeName: "????? (????)", isRTL: false, language: "hi", …}

Globalize.culture().numberFormat.groupSizes
(2) [3, 2]

Globalize.format(123456789.12, "n2")
"12,34,56,789.12"
```
```
Globalize.culture("es-US")
{name: "es-US", englishName: "Spanish (United States)", nativeName: "Español (Estados Unidos)", isRTL: false, language: "es", …}

Globalize.culture().numberFormat.groupSizes
(2) [3, 0]

Globalize.format(123456789.12, "n2")
"123456,789.12"
```

**Comment by CindyMercadoReyes** [comment]
Adding URL to test with: Test this page manually using the three different group sizes
http://localhost:4000/components/locale/test-groupsize.html?locale=hi-IN (3, 2)
http://localhost:4000/components/locale/test-groupsize.html?locale=nl-NL (3, 3)
http://localhost:4000/components/locale/test-groupsize.html?locale=en-US (3, 0)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
