### ISSUE TITLE
Editor: Loosing p and br tags

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4411]
**Describe the bug**
The editor seems to be removing empty p and br tags when switching views

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
2. Click at the end of the first paragraph and hit enter
3. Switch to the visual view
4. Switch back

See that the formating changed, on inspection the br is being removed. Also if you add "loose/empty" p and br tags they seem to be getting removed on changing views

**Expected behavior**
Keep empty tags

**Version**
- ids-enterprise: [v4.32.0]

**Platform**
 - Chrome/Any

**Additional context**
P1 - Customer issue

**Comment by tmcconechy** [comment]
cc @pwpatton @lipetzan

**Comment by jbrcna** [comment]
**QA Passed**
will retest once beta is deployed.
v4.33.0-dev
https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
![Large GIF (1318x498)](https://user-images.githubusercontent.com/56722184/94431339-ba42ed00-01c7-11eb-9e2f-e094f8c5f303.gif)

**Comment by jbrcna** [comment]
Test passed. verified in v4.33.0-beta1
https://4330-beta1-enterprise.demo.design.infor.com/components/editor/example-index.html
