### ISSUE TITLE
Datagrid: select all function is not working as expected after using pager

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4414]
**Describe the bug**
Datagrid: select all function is not working as expected after using pager

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html?theme=uplift&variant=light&colors=0066D4
2. Click select all to check all the checkboxes
3. Click next page
4. Go back to previous page
5. See error. The selected box become unselected

**Expected behavior**
Values selected should remain selected

**Version**
4.320 - dev

**Screenshots**
https://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html?theme=uplift&variant=light&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/94134940-50f46e80-fe95-11ea-96e9-bcd5adb83ecf.png)

**Platform**
All browser, OS and devices.

**Additional context**
n/a

**Comment by tmcconechy** [comment]
This particular example is set to reset the selections when changing page. Which is an option, so nothing is wrong here.
