### ISSUE TITLE
Move Calendar page from "Charts" section to "Components" section

### ISSUE THREAD

**Issue by kevinwhitedesign** [infor-design/enterprise#4415]
Was surfing this link https://design.infor.com/code/ids-enterprise/latest/calendar 

I was surprised that the calendar was under the "Charts" nav item. Albeit complex, this should be considered a component. 

I recommend we move that page under the "Component" parent on the site. Also, anywhere in code that it's categorized this way should be updated.

**Comment by tmcconechy** [comment]
Agreed @kevinwhitedesign - went and moved it here on this commit https://github.com/infor-design/enterprise/commit/a18ff3ae17bdf2dc07e9c34cd81c9dd022e20128 it will take effect next time we deploy
