### ISSUE TITLE
SOHO-6808: [MAC Chrome] Dropdown List Control: Scroll bar not appearing on responsive view

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#442]
1. http://localhost:4000/components/dropdown/test-long-text
2. On MAC Chrome, when the page is responsive it doesn't provide a scroll bar. Please see screen shot attached.

**Comment by tmcconechy** [comment]
I no longer seem to be able to reproduce this issue so closing.

![Screen Shot 2019-07-16 at 10 28 24 AM](https://user-images.githubusercontent.com/814283/61302832-73c8c480-a7b4-11e9-8f38-9480ce570cf2.png)
