### ISSUE TITLE
List Detail: Sidebar height broken in responsive mode

### ISSUE THREAD

**Issue by nbcp** [infor-design/enterprise#4426]
**Describe the bug**
A `_layouts.scss` change from v4.31 has broken the height for the list detail sidebar in responsive view. The changes were:
![image](https://user-images.githubusercontent.com/11013464/94527721-00508d00-026a-11eb-843d-4df36c24dca0.png)
Ref: https://github.com/infor-design/enterprise/compare/4.30.0-beta.0...4.31.0-rc.0

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/page-patterns/example-list-detail-search-paging.html?theme=uplift&variant=light
2. Shrink window down to responsive view
3. Notice the paging bar

**Expected behavior**

**Version**

- ids-enterprise: v4.31

**Screenshots**
If the list is short, paging bar shows too high:
![image](https://user-images.githubusercontent.com/11013464/94527223-3ccfb900-0269-11eb-9fa2-4c95bfccbfe7.png)

If the list is long, paging bar is too low and you can't scroll to it:
![image](https://user-images.githubusercontent.com/11013464/94527316-5cff7800-0269-11eb-9f9e-8d54b2052aae.png)

**Platform**
 - Infor Application/Team Name: Any
 - Device: Any
 - OS Version: Any
 - Browser Name: Any
 - Browser Version: Any

**Additional context**

**Comment by tmcconechy** [comment]
This has been this way a while for example https://4280-enterprise.demo.design.infor.com/patterns/list-detail-search.html it did work. I had noticed this but hadnt pushed a fix so thanks for doing it. Will review the PR.

**Comment by jbrcna** [comment]
**QA Passed**
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/page-patterns/example-list-detail-search-paging.html?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/56722184/95069775-c08e1780-0739-11eb-8888-783f48747fba.png)
