### ISSUE TITLE
ContextualActionPanel: Dropdown search function is not working after clicking Capslock 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4428]
**Describe the bug**
ContextualActionPanel: Dropdown search function is not working after clicking Capslock 

**To Reproduce**
1. Go to https://4330-beta1-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html?theme=uplift&variant=light&colors=0066D4
2. Open the Contextual Action Panel button
3. Tab to Purchase Form field 
4. Click CapsLock
4. Type 35
See error. Should be able to filter 35 data in dropdown

**Expected behavior**
See error. Should be able to filter 35 data in dropdown

**Version**
4.330 beta1

**Screenshots**

![image](https://user-images.githubusercontent.com/45757016/94531532-452af280-026f-11eb-87f0-b987e071b25e.png)

**Platform**
All browser and OS. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Is this just an IE 11 bug @janahintal ? I tried chrome and that seems ok.

**Comment by tmcconechy** [comment]
Descoping this for now
