### ISSUE TITLE
Responsive Form: Layout multi line labels better

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#443]
**Describe the bug**
When labels go over 2 lines because of screen width the input boxes underneath no longer align up and makes the screen look messy.

**To Reproduce**
1. Run the attached example markup
2. See error

**Expected behavior**
Somehow layout the labels and fields even.

**Version**
- ids-enterprise [e.g. v4.9.0 and up]

**Screenshots**
![2017-09-12 15_35_24-System i Workspace - Administration (WS2016RP) - Internet Explorer](https://user-images.githubusercontent.com/814283/68792490-6d8b0d80-0619-11ea-8a43-36cb68eb1e30.png)

**Platform**
 - Chrome

**Additional context**
Formerly https://jira.infor.com/browse/SOHO-6799 see attached files

[Archive.zip](https://github.com/infor-design/enterprise/files/3842817/Archive.zip)

**Comment by tmcconechy** [comment]
Have a fix for this ready...

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in http://master-enterprise.demo.design.infor.com/components/form/example-align-field-bottoms.html
