### ISSUE TITLE
Line: Achieve Localization and upper(topmost) interval on Y-axis scale:

### ISSUE THREAD

**Issue by harishinfor** [infor-design/enterprise#4437]
**Describe the issue:**
If the chart dataset has higher values, for example, the below charts has values 1.6M(1,672,009.47) and 2050 respectively but the corresponding Y axis intervals just rendered till 1.5M and 2.0k respectively as shown below.
![image](https://user-images.githubusercontent.com/25452976/93309595-557bb000-f821-11ea-8f93-60c05e825fa0.png)
Soho sample - https://latest-enterprise.demo.design.infor.com/components/line/test-axis-y-format-shortened.html

If we use only yAxis: {ticks: {number: 10}}. We can achieve upper most interval but
1)	Localization of intervals cannot be achieved.
2)	This is increasing the number of intervals because of this, chart would shrink as shown below.
![image](https://user-images.githubusercontent.com/25452976/93309666-6b897080-f821-11ea-83a6-1e530cfb1648.png)
If we use custom formatter for localization of intervals then yaxis ticks cannot be used.
This would again take us to the initial problem.

**Expected Behavior:**
Allow to coexist ticks and custom formatter.

**Comment by tmcconechy** [comment]
@harishinfor i made localization work in the charts this means

- you dont need a hack to localize it will just do the numbers now
- by doing this the ticks and settings also work
- however, if using K format. keep in mind the numbers will get the group formatter BUT the K is not necessarily making sense in all languages. So perhaps just use the numbers?

**Comment by janahintal** [comment]
Hi @tmcconechy, I think the changes were not deployed yet. 
https://master-enterprise.demo.design.infor.com/components/line/example-localize.html?locale=de-DE & https://master-enterprise.demo.design.infor.com/components/line/example-localize.html
![image](https://user-images.githubusercontent.com/45757016/95078320-875ca400-0747-11eb-955f-a5f9b3948aec.png)
![image](https://user-images.githubusercontent.com/45757016/95078361-9a6f7400-0747-11eb-95c6-3d953875c726.png)

**Comment by tmcconechy** [comment]
@janahintal - your right it wasnt deployed correctly. Please retest

**Comment by janahintal** [comment]
Failing in IE. Please see screenshots below

Windows Chrome: 
![image](https://user-images.githubusercontent.com/45757016/95187622-f3014880-07fd-11eb-9662-20f5f1fcb60a.png)
![image](https://user-images.githubusercontent.com/45757016/95187645-f98fc000-07fd-11eb-8e8e-e26c524b96d3.png)

IE 11:
Notice that both https://master-enterprise.demo.design.infor.com/components/line/example-localize.html?theme=uplift&variant=light&colors=0066D4&locale=de-DE & https://master-enterprise.demo.design.infor.com/components/line/example-localize.html?theme=uplift&variant=light&colors=0066D4 is both in decimal form.

![image](https://user-images.githubusercontent.com/45757016/95187873-4378a600-07fe-11eb-8088-e98974d0c3b4.png)
![image](https://user-images.githubusercontent.com/45757016/95187975-66a35580-07fe-11eb-8764-511ddba8034b.png)

**Comment by janahintal** [comment]
Failing in IE. Please see screenshots below

Windows Chrome: 
![image](https://user-images.githubusercontent.com/45757016/95187622-f3014880-07fd-11eb-9662-20f5f1fcb60a.png)
![image](https://user-images.githubusercontent.com/45757016/95187645-f98fc000-07fd-11eb-8e8e-e26c524b96d3.png)

IE 11:
Notice that both https://master-enterprise.demo.design.infor.com/components/line/example-localize.html?theme=uplift&variant=light&colors=0066D4&locale=de-DE & https://master-enterprise.demo.design.infor.com/components/line/example-localize.html?theme=uplift&variant=light&colors=0066D4 is both in decimal form.

![image](https://user-images.githubusercontent.com/45757016/95187873-4378a600-07fe-11eb-8088-e98974d0c3b4.png)
![image](https://user-images.githubusercontent.com/45757016/95187975-66a35580-07fe-11eb-8764-511ddba8034b.png)

**Comment by tmcconechy** [comment]
We no longer need to support IE11 so leaving this point alone
