### ISSUE TITLE
Datagrid: Number Range Follow up fixes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4438]
**Describe the bug**
Tested the number as range feature with landmark and ran into some blockers.

**To Reproduce**
**Issue One**: No way to know what to do...
1. Go to http://localhost:4000/components/datagrid/test-filter-numbers
2. Change the qty column to in range
3. Try and type "12" in the filter field -> this doesnt work. But the user doesnt know to type a ()

Possible Solutions Ranked in order of favoribility

1. Trigger Field
- make it a trigger field
- make a small popup with two number fields (like datepicker)
- when closing apply the range
2. Add placeholder text
3. Make it two fields (dialog prefered for short fields)

**Issue Two**: 
1. Go to http://localhost:4000/components/datagrid/test-filter-numbers
2. Change the qty column to in range
3. Try to type in the cell below "100" -> you cant as your forced to use the filter range here. should not filter here

**Issue three**
1. Need a form version on http://localhost:4000/components/field-filter/example-index.html
1. so same thing we do, specify a number field, then in range will show the new popup for number range

**Expected behavior**

**Version**
- ids-enterprise: [e.g. v4.34]

**Comment by pwpatton** [comment]
@tmcconechy what is the reason for the parens being required?

**Comment by tmcconechy** [comment]
For example if you need negatives `(-10) - (20)`

**Comment by pwpatton** [comment]
ah, too bad we don't use : between ranges

**Comment by nbcp** [comment]
Hi @tmcconechy, can we please disable this range operator in integer, decimal, percent fields for now? We can't use the parentheses syntax because those filter fields are formatted and we don't allow non-numeric to be entered. This also creates confusion for users since it is also not intuitive to use parentheses and dashes to be able to use this filter. Perhaps maybe having 2 fields is easier to use?

Plus right now in landmark, we only use range for date and time fields. Not sure if we'll support numeric range in the future.
fyi @pwpatton

**Comment by tmcconechy** [comment]
OK, adding this to June sprint. But you can maybe disable it with this setting https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/example-custom-filter-conditions.html#L29 (filterConditions)

For who takes this lets just remove range option entirely from the list.

**Comment by nbcp** [comment]
yup that's what I did for now.

**Comment by tmcconechy** [comment]
cool, since it has a workaround will take this out sprints for now

**Comment by pwpatton** [comment]
Perhaps we could allow custom separator for ranges? I'd like to set it to a colon `:` to separate the range values is what we want: `10 : 20`, -30 : 30

I think we'd also like to have the : for the data range separator as well.
`10/21/2020 : 11/21/2020`

@tmcconechy what do you think?

**Comment by tmcconechy** [comment]
Seems just a s confusing to me as the brackets. I like the idea best of "not doing ranges with numbers".

**Comment by pwpatton** [comment]
I'm not sure we can avoid it. Customers are asking for this functionality.
I agree with @nbcp that a trigger field for it would be helpful

**Comment by tmcconechy** [comment]
Could you put two columns on with the same data? I guess thats wierd...

**Comment by jamie-norman** [comment]
My $.02 is that regardless of what we use—parens or colon—my suggestion is that we either create a mask or show the format as placeholder text >>
![Uploading image.png…]()

**Comment by tmcconechy** [comment]
@EdwardCoyle whats the easiest way to make mask do this any of this?

**Comment by EdwardCoyle** [comment]
I think it shouldn't be too difficult to switch from `(value) - (value)` to `value:value`, but I can see conflicts arising if you include a time field that uses the colon as a separator between hours/minutes... (There is a range timepicker field IIRC) - for example, doing this might not work well:

```
11:00 pm : 12:00 am
```

The problems that arise from using the Mask for these things usually comes down to the complexity of the formatting -- if you need to use something as a separator between fields, you should also avoid using it in the format of each field itself.  This is why we chose the parenthesis for this feature.  It's also what makes localizing these fields difficult.

I'd say we can try and re-write the range masks to use a `:` as a separator between the two fields, but hesitant to say it's an "easy" fix, it's probably not.

**Comment by tmcconechy** [comment]
Similar to #5618

**Comment by tmcconechy** [comment]
Descoping old issues
