### ISSUE TITLE
SOHO-6791: Datagrid Custom Sort on Specific Columns

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#444]
Use Case: We have a bit mapping specifying a specific job type. So we break down the number in base 2 and construct a string from the result. 1 => 'I', 2=>'B', 4=>'M' and so on and bigger numbers will be a concatenation of the different type. For example:
number 8 => 'A', 4 => 'M' and 1039 => 'I, B, M, A, T'. Sorting this now will give sort order 'M', 'A', 'I, B, M, A, T' but should be 'A', 'M',  'I, B, M, A, T' that is string sorted.

Options:

- Change the default sort to sort on the formatter value and not the data value
- Extend to allow a custom sort function for specific columns, not at the grid level. So specific columns can have a modified sort function.

(or Both)

**Comment by tmcconechy** [comment]
Closing this as its a bit too specific. If really badly needed just let us know.
