### ISSUE TITLE
Icon: Not consistent for different themes

### ISSUE THREAD

**Issue by jddimaano** [infor-design/enterprise#4440]
**Describe the bug**
Process icon not consistent for uplift theme and default theme. Issue seems to be on the uplift theme.

**To Reproduce**
1. Go to Settings.
2. Click on dropdown for Theme. Choose Uplift/Vibrant.
3. Go to My Notifications
4. 'Mark All Read' and 'Mark All Read In Background' shows share icon.

**Expected behavior**
'Mark All Read' and 'Mark All Read In Background' should display process icon just like the icon displayed when theme is not uplift,

**Version**
- ids-enterprise-ng: 7.5.3

**Screenshots**
Screen recording attached: 
[process-icon.zip](https://github.com/infor-design/enterprise-ng/files/5305786/process-icon.zip)

See attached screenshot:
![vibrant_theme](https://user-images.githubusercontent.com/72140687/94692362-08d9be00-0365-11eb-96f1-f00ca815b669.jpg)
![subtle_theme](https://user-images.githubusercontent.com/72140687/94692370-0c6d4500-0365-11eb-811a-4f9d1535e091.jpg)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Browser Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
None

**Comment by jddimaano** [comment]
> Im unable to play this video in this format - as cisco no longer works on mac for me due to no more licenses? Do you have a screenshot of what you mean, instead? What does inconsistent mean?

Added screenshots. Thank you!

**Comment by tmcconechy** [comment]
So basically you mean that you dont like the change in icon between themes? Which exact icon is this? Note in general when changing themes all the icons are entirely different but should still map to same functionality? 

Maybe just flip it the same way?

**Comment by tmcconechy** [comment]
cc @inforandy

**Comment by tmcconechy** [comment]
We will review these icons further.

**Comment by tmcconechy** [comment]
Closing this issue due to lack of response for clarification
