### ISSUE TITLE
Tree: Component Enhancements

### ISSUE THREAD

**Issue by kentonquatman** [infor-design/enterprise#4442]
Infor PIM has requested an enhancement to the tree component on IDS:
https://design.infor.com/code/ids-enterprise/latest/tree

| Inline naming when creating a new node | Inline command buttons for each node |
|---|---|
|<img width="1131" alt="image002" src="https://user-images.githubusercontent.com/847306/73669129-f3e14980-4674-11ea-8828-7acb103f7ba4.png">|<img width="1124" alt="image003" src="https://user-images.githubusercontent.com/847306/73669158-00fe3880-4675-11ea-8fae-3d61be475a28.png">|
 
**Latest Designs:**
https://www.figma.com/file/44Wt91O8Dk20lSJsX1tndu/(IDS-110)-Tree-component-enhancements

**Comment by kevinwhitedesign** [comment]
Is this to rename a tree item?

**Comment by kevinwhitedesign** [comment]
@katieinfor needs a ticket

**Comment by tmcconechy** [comment]
Yes, But for all CRUD operations in a tree. 

- update
- delete
- move
- add

**Comment by dhumalkishor** [comment]
Hi Tim,

Any timeline for this issue to get fix?

Regards,
Kishor

**Comment by katieinfor** [comment]
@kevinwhitedesign sorry for the delay! the Jira ticket is: https://jira.infor.com/browse/UXD-2605

**Comment by dhumalkishor** [comment]
Hi Tim,

Can you please update when we can expect fix for this JT.

Regards,
Kishor

**Comment by tmcconechy** [comment]
Will bring this up for discussion next sprint planning. This might additional require design work.

**Comment by kevinwhitedesign** [comment]
@tmcconechy @dhumalkishor design started reviewing / working on this again.

**Comment by inforandy** [comment]
let's make sure we check this one for the June Enterprise grooming @tmcconechy; can we scope for delivery by the enterprise team or will it require additional support from you or someone else.

**Comment by tmcconechy** [comment]
When we add this it will be done on https://github.com/infor-design/enterprise-wc/issues/837 so please watch this issue
