### ISSUE TITLE
Icons: Add Enable Current and Disable Current.

### ISSUE THREAD

**Issue by vamsibandarupalli** [infor-design/enterprise#4443]
Hello,

We have the requirement to add "Enable Current" and "Disable Current" icons in datagrid. Can this icons be added to the infor design system so that we can also make use of it?

Icons:
- Enable Current.
- Disable Current.

![image](https://user-images.githubusercontent.com/18053782/73151116-d3067a80-40ef-11ea-8cbf-b933a0d375fe.png)

**Comment by tmcconechy** [comment]
cc @inforandy

**Comment by kevinwhitedesign** [comment]
@katieinfor this needs a JIRA ticket and to loop in Rogel

**Comment by kevinwhitedesign** [comment]
@vamsibandarupalli vamsibandarupalli hey! What's the usecase like for these? They don't look recognizable

**Comment by vamsibandarupalli** [comment]
In our application we are using some images like this 
![image](https://user-images.githubusercontent.com/18053782/114694730-79ac5a80-9d38-11eb-93c7-3ec71108884e.png)

We have the icon for last one and we are using it to call as reIndex, but for these two we calling them as disable selected and enable selected for reIndex.

**Comment by tmcconechy** [comment]
Descoping this for now.
