### ISSUE TITLE
Search Field: Selecting records from arrow key is not working

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4446]
**Describe the bug**
Search Field: Selecting records from arrow key is not working

**To Reproduce**
1. Go to https://4330-rc0-enterprise.demo.design.infor.com/components/searchfield/example-index.html
2. Go to Search Field section
3. Type 'ala'
- Alabama & Alaska should be listed
4. Using arrow key select Alaska
- Should be successfully selected
5. Now, hover and click again in the fields and delete 'backspace' until 'Ala' is listed again
- Alabama and Alaska is now listed again
6. Select Alabama using arrow key functions. 

**Expected behavior**
Alabama should be successfully selected

**Version**
4.330 rc0 - IDS

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/94774956-75020380-03f1-11eb-80ea-e711cea30c90.png)

**Platform**
All browser, OS and devices 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
https://4330-rc0-enterprise.demo.design.infor.com/components/searchfield/example-index.html -> does not work but https://4320-enterprise.demo.design.infor.com/components/searchfield/example-index.html seems to.

**Comment by jbrcna** [comment]
This issue is now resolved
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/searchfield/example-index.html
