### ISSUE TITLE
Calendar: Legend's color not working when using "Add Event (Modal)"

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4447]
**Describe the bug**
Event Color does not match the legend  when the event is created thru `"Add Event (Modal)"`

**To Reproduce**
1. Go to https://4330-rc0-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Click on `+` in the top right corner
3. Select `Add Event (Modal)`
4. Choose `Admin` or any non-default type (try all 4)
5. Hit Enter/Submit
6. See Error

**Expected behavior**
 event color should match the legend as selected

**Version**
v4.33.0-rc0

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/94808210-5a488280-0423-11eb-9e77-da6de4798af1.png)

**Platform**
All major browsers

**Additional context**
`Add Event (API) is fine`
related to https://github.com/infor-design/enterprise/issues/4439

**Comment by tmcconechy** [comment]
Hmm this is exactly what i fixed. Checking it out

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by jbrcna** [comment]
This issue is now resolved
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
