### ISSUE TITLE
SOHO-6732: When paging = false would like triggerSource to still execute

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#445]
Need ability to set gridOptions.pager = false and still have triggerSource on 'initial', 'filtered', 'sorted', 'refresh' work.

Right now triggerSource expects a pager to be used. In the case of the 4 types listed ('initial', 'filtered', 'sorted', 'refresh") a pager shouldn't be required as they are initiated from things other than a pager.

**Comment by tmcconechy** [comment]
once lm-list-grid is refactored landmark will just be using inputs and handlers for this stuff. So we won't use the gridOptions.source callback anymore, so this wont be needed.
