### ISSUE TITLE
Modal: fullsize responsive issue on Android phones in Landscape mode.

### ISSUE THREAD

**Issue by drinkaj** [infor-design/enterprise#4451]
See an issue on Androids using fullsize 'responsive' on modals when viewing in Landscape mode. 

Used the following URL
https://master-enterprise.demo.design.infor.com/components/modal/example-fullsize-responsive.html

Using browser stack in my example. 
In portrait mode the modal expands to the screen edges. 
In landscape mode the modal doesn't expand to the screen edges. 

See screen shots. 

**Platform**
 - Device:  Samsung Galaxy S10

![landmarkExample](https://user-images.githubusercontent.com/6230418/94846716-35361e80-03e7-11eb-9767-94893db0ef22.png)
![landscape](https://user-images.githubusercontent.com/6230418/94846732-3a936900-03e7-11eb-8c89-3fb907949478.jpg)
![portrait](https://user-images.githubusercontent.com/6230418/94846739-3d8e5980-03e7-11eb-8ad6-20e61a804270.jpg)
![landmarkIphoneExample](https://user-images.githubusercontent.com/6230418/94847900-ceb20000-03e8-11eb-9423-a86c9af5a816.png)

**Comment by janahintal** [comment]
Working on Mobile devices but not on iPad

Mobile & Samsung Tablet:
![image](https://user-images.githubusercontent.com/45757016/110894245-7c2f2500-8332-11eb-9780-2fec014d6d64.png)
![image](https://user-images.githubusercontent.com/45757016/110894937-c369e580-8333-11eb-94c1-b48157cd1c58.png)


iPad Pro 12.9 2020 Chrome
![image](https://user-images.githubusercontent.com/45757016/110894549-05def280-8333-11eb-9bc7-d93866a69b77.png)

**Comment by tmcconechy** [comment]
this was made for iphone configuration. the ipad has too much space so its not really setup for that.
I'll just move it to done

**Comment by ericangeles** [comment]
@tmcconechy that's correct. Basically, the iPad Pro's screen resolution is about `2048 x 2732 px` and has a viewport size of `1024 x 1366 px` which is considering as a medium desktop.

**Comment by tmcconechy** [comment]
Yes thats what i thought. So i think this should be considered done

**Comment by janahintal** [comment]
Thanks for this. :D Will now move this ticket to Done.
