### ISSUE TITLE
Listview: Readonly / Non-selectable listview should not have hover / selected styling

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#4452]
**Describe the bug**
A listview with `selectable: false` still gets focus / hover styles. 

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/listview/example-index?theme=uplift&variant=light&colors=0066D4
2. Hover the items
3. Select an item

![list](https://user-images.githubusercontent.com/1101770/95077301-8f9aec00-0713-11eb-99f8-73fa1f4c3810.gif)

**Expected behavior**
I think a readonly / non-selectable list should just be a list of items, no special hover / selected styling. The items are just info.
There are of course scenarios where a non-selectable listview _should_ have some kind of hover style, e.g. list of links / clickable (but not selectable) items, but I think a "plain" list should be the default, especially since these styles are difficult to override by the consumer. Alternatively an option that makes the list "plain", to avoid having to override focus / hover / active etc for info-only lists.

**Version**
- ids-enterprise: v4.32.0

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/96577045-a5103880-1305-11eb-9572-15d34d95f784.png)
