### ISSUE TITLE
Column: The x-axis labels of a column chart do always center correctly. 

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#4460]
**Describe the bug**
Depending on the chart size and data the column charts at time have mis-aligned x axis labels

**To Reproduce**
1. Use the chart examples chart /components/column/test-custom-tooltips.html
2. replace the data for the chart with the data listed below
3. Load the chart
4. Depend on window/screen size you might need to change size to see the issue.

**Expected behavior**
Label to be displayed the same way on each column. It appears they should be centered but that is not always the case

**Version**

Soho XI Controls v4.3.0

**Screenshots**

**Platform**
Version 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
Data :

dataset = [{
        "data": [{
            "name": "Count",
            "value": 14,
            "ref": 0
        }],
        "name": "Draft"
    },
    {
        "data": [{
            "name": "Count",
            "value": 9,
            "ref": 1
        }],
        "name": "Started"
    },
    {
        "data": [{
            "name": "Count",
            "value": 4,
            "ref": 2
        }],
        "name": "Submitted"
    },
    {
        "data": [{
            "name": "Count",
            "value": 14,
            "ref": 3
        }],
        "name": "Submit Pending"
    },
    {
        "data": [{
            "name": "Count",
            "value": 11,
            "ref": 4
        }],
        "name": "Finalized"
    },
    {
        "data": [{
            "name": "Count",
            "value": 3,
            "ref": 5
        }],
        "name": "Inactive"
    }
]

**Comment by krahs1** [comment]
![Screenshot 2020-10-05 09 41 56](https://user-images.githubusercontent.com/19823048/95101889-50ab6d00-06f8-11eb-81bb-3aa9e7d208ee.png)

**Comment by jmacaluso711** [comment]
@krahs1 It appears the main issue here is that the format of the data is incorrect. It should look like this:

```
var dataset = [{
    "data": [
      {
        "name": "Draft",
        "value": 14,
        "ref": 0
      },
      {
        "name": "Started",
        "value": 9,
        "ref": 1
      },
      {
        "name": "Submitted",
        "value": 4,
        "ref": 2
      },
      {
        "name": "Submit Pending",
        "value": 14,
        "ref": 3
      },
      {
        "name": "Finalized",
        "value": 11,
        "ref": 4
      },
      {
        "name": "Inactive",
        "value": 3,
        "ref": 5
      }
    ]
  }];
```

![Screen Shot 2020-11-05 at 2 46 44 PM](https://user-images.githubusercontent.com/1084735/98289129-c021b000-1f75-11eb-9fc1-90b5c0b569cc.png)

**Comment by tmcconechy** [comment]
Good find @jmacaluso711 this seems like the data like as if it was grouped columns https://master-enterprise.demo.design.infor.com/components/column-grouped but instead a whole bunch of groups so thats pushing it off.

Good fix

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.
