### ISSUE TITLE
AppMenu: Redundant info in expand/collapse button

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4462]
**Describe the bug**
There is redundant info in expand/collapse button and the structure can be improved

**To Reproduce**
1. Go to http://localhost:4000/components/applicationmenu/example-personalized-roles.html
2. Click on Level 2 with the plus/minus and inspect

**Expected behavior**
1. We dont need aria-expanded and the offscreen label. 
1. Ensure that both "+" and "My Development" are coded as a single element instead of "+" being a button and "My Development" being a link.

**Version**
- ids-enterprise: [4.33.0]

**Platform**
 - Chrome/Any

**See also**
https://jira.lawson.com/browse/LMCLIENT-32527

**Comment by jbrcna** [comment]
**QA Passed**
v4.35.0-dev
https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html
