### ISSUE TITLE
About: Format for IDS version is not correct in RTL

### ISSUE THREAD

**Issue by jcotaco** [infor-design/enterprise#4465]
**Describe the bug**
When displaying the IDS version in RTL (i.e. Arabic/Hebrew) in the About dialog, the actual version gets interchanged with the "IDS" label.

**To Reproduce** 
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/about/example-index.html?locale=ar-SA.
2. Click on "Show About Screen" button.
3. Scroll down the "About" screen and look for IDS version.
4. The IDS version is displayed as: **IDS : 4.33.0 إصدار** wherein IDS and 4.33.0 were interchanged.

**Expected behavior**
The version should be displayed as follows: **4.33.0: IDS إصدار**

**Version**
- ids-enterprise: v4.33.0

**Platform**
 - Infor Application/Team Name: Homepages
 - Device: PC 
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 85.0.4183.121 (Official Build) (64-bit)

**Additional context**
NA

**Comment by tmcconechy** [comment]
Are you sure it should not be

```
4.33.0: إصدار IDS 
```

i.e inverse of
```
Ids Version: 4.33
```

**Comment by jcotaco** [comment]
I'm sure that it should not be 4.33.0: إصدار IDS . Reading 4.33.0: IDS إصدار from right to left will give the inverse "version IDS".

**Comment by tmcconechy** [comment]
Hmm well if you flip ": إصدار IDS" inverse that seems to say IDS Version to me? None the less the : part of it is wrong.
And perhaps "IDS" should also be translated....

**Comment by jcotaco** [comment]
I have consulted this issue with someone who reads and writes RTL orientation and yes, I can assure you that the suggested format indeed is the expected output. I have also consulted with her about the "IDS" being translated and she said that it's ok. It can be retained as is too. Both will work just fine.

**Comment by tmcconechy** [comment]
OK thanks for confirming then. 👍

**Comment by jcotaco** [comment]
You're welcome :)

**Comment by janahintal** [comment]
This issue is now resolved. Thank you 
![image](https://user-images.githubusercontent.com/45757016/96991702-6c699c80-155b-11eb-87ef-e733d5be1026.png)
