### ISSUE TITLE
Datagrid: Unable to resize column smoothly a

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4466]
**Describe the bug**
Datagrid: Unable to resize column smoothly a

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-colspan.html
2. Try to minimize the Product ID column
3. See error. The column couldn't be resizes smoothly 

**Expected behavior**

**Version**
3.34 IDS Dev

**Screenshots**
N/a

**Platform**
All Major Browsers. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping for now
