### ISSUE TITLE
Datepicker: Broken in mobile view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4467]
**Describe the bug**
Datepicker is broken in mobile view 
Browserstack: Samsung GalaxyS9, Samsung GalaxyS10, Samsung GalaxyS20, Samsung GalaxyS20 Ultra

**To Reproduce**
1. Open a browser in Browserstack, Select `Galaxy S20`
When using Chrome dev tools, use `Galaxy S5`
2. Click/open the datepicker
3. See error

**Expected behavior**
v4.33.0
![image](https://user-images.githubusercontent.com/56722184/95327472-accbe800-08d6-11eb-80f1-98a781624712.png)

**Version**
- ids-enterprise: [v4.34.0-dev]

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/95327530-c4a36c00-08d6-11eb-883d-6fa4dd82a78a.png)

**Platform**
 Mobile / Mobile View

**Additional context**
Notice that there were spaces in between lines & borders
_Use safari device toolbar (iPhone 8 Plus)_
![image](https://user-images.githubusercontent.com/56722184/95325676-1f879400-08d4-11eb-8e06-8824fe2f5e41.png)

**Comment by tmcconechy** [comment]
This seems to be working better now but some views that are smaller dont work great. We dont necessarily support all of them so leaving this for now.

**Comment by jbrcna** [comment]
I'll take note of that. Thank you @tmcconechy.

**Comment by tmcconechy** [comment]
Descoping for now
