### ISSUE TITLE
Button: Ability to remove the dropdown button on a menu button

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#4470]
**Describe the bug**
Add an ability to not add a dropdown button to a menu button. In some cases it is enough to just display the icon and when clicked display the menu. If you are able to add something in a couple different ways a + icon is displayed and would make sense without the drop down arrow next to it. when clicked the menu would display the option. It would help clean up a smaller mobile screen and appears to be a second icon confusing the more then helping them understand they have more than one way to add. 

**To Reproduce**
1. Display a icon only menu button

**Expected behavior**
To not display the the dropdown button by using a flag or some other way to decide when to not display the dropdown

**Version**

Soho XI Controls v4.3.0

**Screenshots**

![Screenshot 2020-10-08 13 57 39](https://user-images.githubusercontent.com/19823048/95501758-69bd5380-096e-11eb-894c-e59cee476fb0.png)

**Platform**

**Additional context**
This is a bigger problem on a smaller phone with a larger title but it also is a little confusing because it looks like 2 icons instead of a drop down icon only menu

**Comment by krahs1** [comment]
It is needed for this ticket from HCM Mobile ticket  -  https://jira.lawson.com/browse/LMCLIENT-29390

**Comment by ericangeles** [comment]
@tmcconechy Does the hideMenuArrow option fix this issue?

**Comment by tmcconechy** [comment]
Could call @ericangeles i missed that. you are right that option does remove the arrow.  So closing this issue.
@krahs1 here is an example that works

```
      <button type="button" id="test" class="btn-menu" data-options="{ 'hideMenuArrow': true, 'attributes': [ { 'name': 'data-automation-id', 'value': 'menu-button' } ] }">
        <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
          <use href="#icon-delete"></use>
        </svg>
        <span class="audible">Add Item</span>
      </button>
      <ul class="popupmenu is-selectable has-icons">
        <li><a href="#">Create a form</a></li>
        <li class="separator"></li>
        <li><a href="#">Spelling...</a></li>
        <li><a href="#" disabled aria-disabled="true">Solver...</a></li>
        <li class="separator"></li>
        <li class="is-checked"><a href="#">Enable Autocomplete</a></li>
        <li><a href="#">Notification Rules</a></li>
        <li><a href="#">Protect Sheet Rules</a></li>
      </ul>
```
