### ISSUE TITLE
Datagrid: Unable to download file in iOS devices

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4472]
**Describe the bug**
Datagrid: Unable to download file in iOS devices

**To Reproduce**
1. In iPhone or iOS device, go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html
2. Click export button

**Expected behavior**
Data should be downloaded successfully 

**Version**
4.34 - dev 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/95568703-24c11c00-0a57-11eb-9622-f5d77eeb5dfe.png)

**Platform**
iOS mobile devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Marking this as minor as not sure on mobile what should happen? Maybe you need excel installed on the device?

**Comment by tmcconechy** [comment]
Descoping for now
