### ISSUE TITLE
Button: Add Option to remove default "more" tooltip

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#4473]
**Is your feature request related to a problem? Please describe.**

When adding an action button there's no option to remove the default tooltip. Which has the default text "More"

**Describe the solution you'd like**
Allow a title to be set to "" or some other tooltip when using btn-actions

**Additional context**
Check gif for the issue
![default-tooltip](https://user-images.githubusercontent.com/542598/95509420-c80d2500-09b4-11eb-8a1a-52998b99109c.gif)

**Comment by tmcconechy** [comment]
The problem is there is no test here https://github.com/infor-design/enterprise/blob/master/src/components/button/button.js#L387 if the title is overriden.

**Comment by jbrcna** [comment]
**QA Passed**
v4.35.0-dev
https://master-enterprise.demo.design.infor.com/components/button/test-remove-more-tooltip.html
![image](https://user-images.githubusercontent.com/56722184/98802593-7d1c7c80-244e-11eb-8e3b-016153f9f854.png)
