### ISSUE TITLE
Dropdown: Icon rendering issue at the time of filtering

### ISSUE THREAD

**Issue by sumanthvemula** [infor-design/enterprise#4474]
**Describe the bug**
Icon for the last option in the dropdown is changing while filtering the items in the search field.

**To Reproduce**
1. Create a Soho Dropdown with few options with icons.
2. Click on the dropdown and remove the text in the search field.
3. Observe the icon for the last option which is being replaced.

Or

https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/example-icons?theme=uplift&variant=light

1. Go to the above mentioned URL.
2. click on the dropdown and remove the text in the search field.
3. Observe the icon for the last option is being replaced.

**Expected behavior**
The icon for the last option should not change while at filtering.

**Version**
- ids-enterprise-ng: v7.4.0 and above

**Screenshots**
<img width="721" alt="SohoDropdownIssue1" src="https://user-images.githubusercontent.com/20971223/95544934-27515080-0a1a-11eb-99c3-5929c20cc03f.PNG">
<img width="660" alt="SohoDropdownIssue2" src="https://user-images.githubusercontent.com/20971223/95544942-2d473180-0a1a-11eb-9583-de1c70426cc7.PNG">

**Platform**
 - OS Version: Windows 10
 - Browser Name: chrome

**Comment by jbrcna** [comment]
**QA Passed**
v4.35.0-dev
https://master-enterprise.demo.design.infor.com/components/dropdown/example-icons
![image](https://user-images.githubusercontent.com/56722184/99626870-232f3e80-2a6e-11eb-9c86-aa52d2f03de1.png)
