### ISSUE TITLE
DataGrid: updateRow() is not updating the dataset and only updating visual cells 

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise#4476]
```
const updatedRow ={
      name: 'Attr1',
      type: 'Type1',
      description: 'Desc1',
      count: this.count
    };
```

**Describe the bug**
Above updateRow call is not updating this.datagrid.settings.dataset[0]. So when retrieving data from datagrid row via click on a row, we don't get updated data.

**Expected behaviour**
updateRow() should also update the dataset so that we get correct data from datagrid when retrieving it.

**Additional context**
cc @karinthulin

**Comment by hemantg05** [comment]
@tmcconechy, please feel to update the bug description if it is not clear enough.

**Comment by tmcconechy** [comment]
The problem is that the updateRow does not apply the incoming row to the dataset itself.

**Comment by tmcconechy** [comment]
@hemantg05 went to look at this and made a test and noticed it is working...At least on the latest version. 

1. go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-index
2. type this in the console...

```
$('#datagrid').data('datagrid').settings.dataset[1].productIdx
$('#datagrid').data('datagrid').settings.dataset[1].productName
$('#datagrid').data('datagrid').updateRow(1, { productId: 'test', productName: 'test' })
$('#datagrid').data('datagrid').settings.dataset[1].productIdx
$('#datagrid').data('datagrid').settings.dataset[1].productName
```

Any thoughts?

**Comment by hemantg05** [comment]
@tmcconechy, I think this is about non-existing column.

$('#datagrid').data('datagrid').updateRow(1, { nonExistingColumn: '123', productName: 'test' })

Expected:
$('#datagrid').data('datagrid').settings.dataset[1].nonExistingColumn should return '123'
Current:
$('#datagrid').data('datagrid').settings.dataset[1].nonExistingColumn returns undefined

**Comment by tmcconechy** [comment]
Thanks that is what i was missing

**Comment by jbrcna** [comment]
The issue is now resolved.
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-index
