### ISSUE TITLE
Editor: Back Color is not working

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4477]
**Describe the bug**
when selecting a text and set a back color, the color does not take effect

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-with-backcolor.html
2. Highlight/Select any text
3. Choose a back color

**Expected behavior**
Back Color should apply upon selection

**Version**
- ids-enterprise: [v4.34.0-dev]

**Screenshots**
![Large GIF (1378x468)](https://user-images.githubusercontent.com/56722184/95738517-f42dec00-0cbb-11eb-9436-75640c173642.gif)

**Platform**
All major browser

**Additional context**

**Comment by tmcconechy** [comment]
Descoping this one for now
