### ISSUE TITLE
Datagrid: No Data after clicking the Pager

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4482]
**Describe the bug**
Datagrid: No Data after clicking the Pager

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html
2. Set to 75 records per page
3. Click LAST PAGE
4. Click PREVIOUS PAGE
See error

**Expected behavior**
Data Should be displayed

**Version**
4.34 dev ids

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/95852901-20626f00-0d87-11eb-95e9-8ee147a5cbd8.png)

**Platform**
All Major Browsers

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This maybe just an example issue. So will mark this low.
