### ISSUE TITLE
Dropdown: Behavior when its open (combination of filterMode='wordStartsWith' and noSearch='true')

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4483]
**Is your feature request related to a problem or use case? Please describe.**
Use Case:
With noSearch='true' and filterMode='wordStartsWith' as properties
- When dropdown is open, option matching the first letters typed will only be highlighted/pre-selected; dropdown will not close yet
- Close dropdown on enter

**Describe the solution you'd like**
Soho dropdown support for the use case to enable:
(Dropdown is open)
- When user types first characters of an option, the option will be highlighted/pre-selected; dropdown will not close yet

**Describe alternatives you've considered**
No alternatives yet since type ahead will not pass the use case

**Additional context**
Please see below for sample behavior 
(note) I'm typing the first characters of options 
![expected_dropdown_behavior](https://user-images.githubusercontent.com/50192038/95854090-0aee4480-0d89-11eb-80d6-3074275e98c9.gif)

And what application do you work on? M3 User Productivity

tagging @lucacolumbu

**Comment by tmcconechy** [comment]
I agree with this. The idea was it should be like https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select which does stay open.

**Comment by janahintal** [comment]
QA Passed.
https://master-enterprise.demo.design.infor.com/components/dropdown/example-no-search-stay-open.html?theme=uplift&variant=light&colors=0066D4 
![image](https://user-images.githubusercontent.com/45757016/100202183-eff02200-2f3b-11eb-9a71-c6571e1e12e7.png)
