### ISSUE TITLE
Drag: Not dragging over navigation menu; Contain drag element within view port

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4484]
**Describe the bug**
The drag utility is not dragged over the navigation menu.
Additional request, is there a way to contain the drag element within the view port.
Currently when dragging element downward, this will just extend the body size from the ids-enteprise-ng sample (https://github.com/infor-design/enterprise-ng.git).
I tried containment='body' and 'window' too but same result

**To Reproduce**
recreate from enterprise-ng samples https://github.com/infor-design/enterprise-ng.git:
![image](https://user-images.githubusercontent.com/50192038/95855202-9c11eb00-0d8a-11eb-8dc9-c485c74150fc.png)
1. Open navigation menu
2. Go to Drag Menu
(Navigation menu should remain open)
- Drag the draggable element up to left most, dragging over to navigation menu not permitted
- Drag the draggable element downward, the element is not contained but the body is extended (see scroll bar generated)
- Drag the draggable element to the right, the element is not contained but the body is extended (see scroll bar generated)

**Expected behavior**
1. Draggable element can be dragged over the navigation menu
2. Draggable element can be 

**Version**
- ids-enterprise-ng 7.7.0-dev.20200909

**Screenshots**
![drag_behavior](https://user-images.githubusercontent.com/50192038/95856435-97e6cd00-0d8c-11eb-9ce0-fb1b4276ddae.gif)

**Platform**
 - Infor Application/Team Name: User Productivity Team
 - Device: N/A
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Browser Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**
Tagging @lucacolumbu

**Comment by tmcconechy** [comment]
Hi @marclouisgenedeguzman did you guys find a solution for this?

**Comment by marclouisgenedeguzman** [comment]
> Hi @marclouisgenedeguzman did you guys find a solution for this?

Hi Tim, yup we just changed the level of our div with the app menu. We can close this ticket. Thanks.
