### ISSUE TITLE
Datagrid: Settings to disable text selection on enter edit mode of editable cells in datagrid

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4485]
**Is your feature request related to a problem or use case? Please describe.**
Use Case: text selection should be disabled on enter edit mode in editable cells
On enter edit mode of editable cells in datagrid, default behavior is all text will be selected
- is there a property/setting to turn off text selection on enter edit mode

**Describe the solution you'd like**
Have a setting to disable text selection on enter edit mode of edit cell. 
The setting will be a flag if text selection will be executed or not

**Describe alternatives you've considered**
No alternatives yet

**Additional context**
And what application do you work on? M3 User Productivity Team

Tagging @lucacolumbu

**Comment by tmcconechy** [comment]
No, there is no current setting for this. The text is all selected to make it easier to type over and change the value. It could be a setting but it adds a level of inconsistency across applications. (BTW your the first team to request it)

So wondering why you would use that? Is there a specific use case?

Workaround -> use the arrow keys after going in the cell.

**Comment by tmcconechy** [comment]
@marclouisgenedeguzman question for you? Would you enable this by column or for all columns in your grid? I think by column could make sense and this would be easy.

**Comment by marclouisgenedeguzman** [comment]
@tmcconechy, it would be ok to set this for all columns. But let me get back to you as one of our developers is trying to come up with some work around

**Comment by jbrcna** [comment]
**QA Passed**
v4.35.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-select-on-edit.html
https://master-enterprise.demo.design.infor.com/components/datagrid/test-cell-edit-callback.html
