### ISSUE TITLE
Tree: Newly added childNode losing reference to parent when using addNode with parent option

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise#4486]
**Describe the bug**
Adding a new node to the tree using the "parent" option will successfully add the new node to the tree. But when accessing the new node by for example findById or looking up the tree dataset, the parent property will be blank (`parent: ""`).

**To Reproduce**
Steps to reproduce the behavior: (Also shown in attached screenshot)
1. Go to https://master-enterprise.demo.design.infor.com/components/tree/test-add-node-with-parent-option.html
2. Use devtools to pause on addNode call in script
3. Add node: `this.tree.addNode({id: 'newTestNode', text: 'New Test Node', parent: 'leadership'});`
4. Look up node: `this.tree.findById('newTestNode');`
5. Notice how newTestNode property called parent is empty. (`parent: ""`)

**Expected behavior**
Parent property should be set during node creation to contain the parent id so that it can be used if needed to identify the parent.

_I can easily work around this by adding a custom property to hold the parent id reference for now. However it would be nice to skip that so that i don't have multiple properties meant for holding the parent reference._

**Version**
- ids-enterprise: 4.34.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/9215760/95863527-973a4080-0d64-11eb-880e-73404b319134.png)

**Platform**
 - Infor Application/Team Name: Infor PIM
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: 85.0.4183.102 (Official Build) (64-bit)

**Comment by janahintal** [comment]
QA Passed. 
Verified in https://master-enterprise.demo.design.infor.com/components/tree/test-add-node-with-parent-option.html?theme=uplift&variant=light&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/101755742-32a32400-3b10-11eb-8250-057ab56f6aa1.png)
