### ISSUE TITLE
Datagrid: Still not highlighting the text when using server side paging

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4488]
**Describe the bug**
We noticed https://github.com/infor-design/enterprise/issues/3977 isnt entirely fixed. As noted on the QA remarks the issue is "though not highlighting"

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-keyword-search-serverside.html
2. Click on search in the toolbar
3. Type 212 and hit enter
4. Notice the text is not highlighting in bold

**Expected behavior**
Should be bold on keyword search

**Version**
- ids-enterprise: [e.g. v4.34

**Additional context**
Missed on QA remarks on https://github.com/infor-design/enterprise/pull/4142#issue-448381227

**Comment by janahintal** [comment]
This issue is now resolved. 
https://master-enterprise.demo.design.infor.com/components/datagrid/test-keyword-search-serverside.html
![image](https://user-images.githubusercontent.com/45757016/97409969-6b5cb480-1939-11eb-8c01-4c8bbe309c12.png)
