### ISSUE TITLE
Datagrid - Change resize handle element draggable attribute to true when a datagrid column is resizable

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#4490]
This feature is requested for the use of automated script: currently, value of "draggable" attribute for columns is set to "false". In order for automation script to drag / expand the column, we need the value to be set to "true".

**Comment by vonnyw** [comment]
![Capture](https://user-images.githubusercontent.com/39130590/95894513-d3fb3d00-0d4e-11eb-891b-56cd1e7f88d0.PNG)

**Comment by tmcconechy** [comment]
QA Notes: Just test things that are draggable on datagrid and other places that have drag/drop in general. Should be no effect from my testing

**Comment by tmcconechy** [comment]
The site https://master-enterprise.demo.design.infor.com/components/datagrid/example-index now shows draggable true for testing.

**Comment by jbrcna** [comment]
**QA Passed**
Nothing off is observed
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-index
![image](https://user-images.githubusercontent.com/56722184/95978779-38042b00-0e4d-11eb-9726-13f8f2f49f30.png)
