### ISSUE TITLE
DataGrid: Personalize Columns search does not work

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#4495]
**Describe the bug**
When trying to search column in Personalize Columns dialog, it throws an error in console (Cannot read property 'toLowerCase' of undefined) and not working

**To Reproduce**
1. Go to demo app /ids-enterprise-ng-demo/datagrid-breadcrumb
2. Click on ellipsis menu - personalize column
3. Try searchbox
4. See error in the console

**Expected behavior**
Search should normally work

**Version**
- ids-enterprise-ng: 7.5.5 (8.0.1 also tested)

**Screenshots**
![image](https://user-images.githubusercontent.com/11279863/95602533-59cc6f00-0a55-11eb-89a4-fff967580834.png)

**Comment by tmcconechy** [comment]
FYI Found this problem occurs when you have a checkbox column with no "name" field in the column. So this can be workedaround by adding a name="something" on every column in the grid.

Could also be seen here https://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html

**Comment by hohnzy** [comment]
Workaround works! Even with empty string `{...column, name: ''}`.

**Comment by jbrcna** [comment]
**QA Passed**
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
![image](https://user-images.githubusercontent.com/56722184/96559283-6a9ba100-12ef-11eb-8df9-07f72c88d330.png)
