### ISSUE TITLE
SOHO-6276: Chart localization

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#450]
Soho Chart.js does not format values based locale selected. It needs to set d3.locale for ensuring values on chart are localized per language.
For example for de-de - values indicated on chart should be 1.000.000 instead of 1,000,000

**Comment by tmcconechy** [comment]
Descoping this issue for now

**Comment by tmcconechy** [comment]
for anyone watching this i was able to fix it on https://github.com/infor-design/enterprise-ng/issues/910 see this issue for details
