### ISSUE TITLE
BreadCrumb: Unintentional Breakage on css only version

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4501]
**Describe the bug**
If you leave the bread-crumb-list class off then dont invoke the breadcrumb, this doesnt work anymore. It just shows it as a list. Will adjust to make it more backwards compatible

**To Reproduce**
1. Make a test page with
```
<div class="row">
  <div class="twelve columns">
    <nav class="breadcrumb" data-init="false">
      <ol aria-label="breadcrumb">
        <li>
          <a href="#" id="home" class="hyperlink hide-focus">Home</a>
        </li>
        <li>
          <a href="#" id="second-item" class="hyperlink hide-focus">Second Item</a>
        </li>
        <li>
          <a href="#" id="third-item" class="hyperlink hide-focus">Third Item</a>
        </li>
        <li class="current">Fourth Item <span class="audible">Current</span></li>
      </ol>
    </nav>
  </div>
</div>
```
2. load it up in the browser
4. See error -> does not look like a bread crumb

**Expected behavior**
Still works as before with css only

**Version**
- ids-enterprise: [e.g. v4.33]

**Additional context**
May require a patch to 8.0.0

**Comment by jbrcna** [comment]
**QA Passed**
v4.34.0-dev
https://master-enterprise.demo.design.infor.com/components/breadcrumb/test-just-css.html
https://master-enterprise.demo.design.infor.com/components/breadcrumb
![image](https://user-images.githubusercontent.com/56722184/96998203-a0e25600-1565-11eb-93f7-ea37f6403c02.png)
