### ISSUE TITLE
Fileupload: Previously selected file gets cleared on cancel

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#4504]
**Describe the bug**
A previously selected file gets cleared if cancelling a new selection. Minor/trivial issue.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/fileupload/example-index.html
2. Click the folder icon of the first field
3. Select a file and click open
4. Click the folder icon again
5. Click Cancel
Result: The field is emptied. Is this by design? Or should the previously selected file be persisted?

**Version**
- ids-enterprise: v4.33.0

**Screenshots**
![file](https://user-images.githubusercontent.com/1101770/96464345-fa761800-1227-11eb-89aa-2d14135a8788.gif)

**Comment by tmcconechy** [comment]
Yes, This is "by design" in a way. Since this component as a UI over the normal html input type="file". We just do what the browser does for this case as can be seen here https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_file when cancelling adding.

**Comment by volante007** [comment]
Oh, right, it's identical to standard input behavior. Feel free to close this one!

**Comment by tmcconechy** [comment]
No problem, got this question before actually so good to post it
