### ISSUE TITLE
I18n issue: "All: { id: 'All'" should not be glued / concatenated with any other strings

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4505]
**Please do not glue / concatenate All: { id: 'All' with any other strings.** 

All: { id: 'All', value: 'All', comment: 'All items in the context of a filter' } belongs to the IDS project. This string is combined / glued with other Landmark strings (e.g. Status, Bank Sign, etc.). This is not a good approach.

Gluing strings creates translation issues as the translation for All is determined by the second part of the string. As this string combination is used in different contexts, it doesn’t work in languages.
 
Using a self-contained / generic string (e.g. All Results, All Selection) will be ok. 

![All](https://user-images.githubusercontent.com/66057969/96466966-b9cbce00-122a-11eb-885c-f0f396b204a8.png)

**Comment by cpinatel7** [comment]
Similar issue with "Selected" (Screenshot: Selected.png)

'Selected' shouldn't be glued / concatenated with any other words. The combination - 'Selected' + 'Another string' - doesn't work in languages.

Urgent fix required for 'All' and 'Selected'.

Thank you

**Comment by cpinatel7** [comment]
![Selected](https://user-images.githubusercontent.com/66057969/103925874-72adf480-5118-11eb-9941-4916375b55cf.png)

**Comment by tmcconechy** [comment]
i'll take a look next sprint

**Comment by tmcconechy** [comment]
My suggest is to use a generic (non appended string for each case). And that those will be:

`All Results`
and
`Selected or All`

See https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html as it is working now for the latter.

cc @EdwardCoyle ?

**Comment by cpinatel7** [comment]
![image](https://user-images.githubusercontent.com/66057969/105862809-7e425c00-5ff0-11eb-8627-c24b8aea18c2.png)

The priority is NOT to append / glue different strings so the suggested solution is much better. However, 'All' and 'Selected' are a bit difficult to translate. 'All' and 'Selected' will be translated differently depending on the context.

'All' -> Difficult to translate
vs
'All Items'
'All Results'

'Selected' -> Difficult to translate
vs
'Selected Items'
'Selected Results'
'Selection'

Thanks

**Comment by tmcconechy** [comment]
Ok then maybe:

Select/All Results -> for search
Select/All Items -> for listed results

plus maybe we need to keep it setable so we dont break anybody so they can set these to anything manual

**Comment by cpinatel7** [comment]
Thanks

**Comment by janahintal** [comment]
QA Passed. Working as expected. 

Issue #4505

go to http://localhost:4000/components/multiselect/example-index.html
open the first list
this should say selected and all in the bold fields and not say "states"

![image](https://user-images.githubusercontent.com/45757016/107936701-e962cb00-6fbd-11eb-9ae1-b4d4e48efa6d.png)
