### ISSUE TITLE
Modal/Message: No control of Focus on return from MessageDialog

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#4507]
The introduction of the "noRefocus" setting on the Modal component broke our UI. Upon return from display of message dialog, we no longer have control of where the focus is placed.

The noRefocus setting should be added to the Message component also and passed on to the Modal component.
i.e. 
    noRefocus: false,

added to MESSAGE_DEFAULTS

and 
    noRefocus: this.settings.noRefocus,

added to 
    this.message.modal({

**Comment by tmcconechy** [comment]
Whil efixing this i found a not worthy thing. There is actually two settings `returnFocus` ad `noRefocus`. `returnFocus did work so if you want to focus something specific and dont want to upgrade you can put that in your app.

https://github.com/infor-design/enterprise/blob/17dd5427089fb51be6c8aeb3f0fcc90b8d740a4b/app/views/components/message/example-index.html#L41

These are bit redundant but i wont break the API right now. And note that if you provide `returnFocus` it will use that and ignore `noRefocus` even after this fix. So its sort of use one or the other and the `returnFocus` could work as a workaround.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.
![image](https://user-images.githubusercontent.com/45757016/96993579-164a2880-155e-11eb-89b5-cbad19aee45a.png)

![image](https://user-images.githubusercontent.com/45757016/96993568-121e0b00-155e-11eb-880b-00648a86956d.png)
