### ISSUE TITLE
SOHO-6187: Allow option for SOHO charts to not have padding

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#451]
By default, most of SOHO's SVG charts add their own "padding", thereby not taking up the entire space they are given.  Here's what SOHO's default padding is like:

!soho-chart-padding.png|thumbnail!

And here's what the chart would look like if it was able to take up the entire space allotted:

!soho-chart-padding-removed.png|thumbnail!

Note that the chart renders as 20% larger.  This example may not prove the importance so much, but when charts are smaller, denser (imagine the same chart with 5x as many data points), or being used in a layout that doesn't use padding (e.g. not inside a card), the extra 20% can make-or-break the chart.

Hard to work around because the padding is built into the SVG.  Related (possibly a separate bug): there is some inconsistency with how line charts pad their legend.

Another related bug: Pie/donut charts seem to emit 100% width and height, which is not consistent with how other charts are sized.

**Comment by tmcconechy** [comment]
Closing this for now but will make it this way in the new component in the Web Components project without padding
