### ISSUE TITLE
Tree: Character entity references render differently at top / child levels when using source

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#4512]
**Describe the bug**
For a Tree that uses `source`, item texts that contain character entity references render differently at top / child levels, e.g. `&lt;` shows as < at top level, but as `&lt;` at child level.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/tree/example-ajax?theme=uplift&variant=light
2. Open Dev console
3. Execute the following to re-initialize the tree with texts that have a character entity reference
```
$('#json-tree').tree({dataset: [{
          "text": "I have a less than sign: &lt;",
          "extra": "test 1"
        }, {
          "text": "Node Two",
          "open": false,
          "children": [],
          "extra": "test 2"
        }, {
          "text": "Node Three",
          "open": false,
          "children": null,
          "extra": "test 3"
        }], source: function (req, response) {
          setTimeout(function () {

            var nodes = [{
              "id": "node2.1",
              "text": "I also have a less than sign: &lt;"
            },{
              "id": "node2.2",
              "text": "Node 2.2",
              "children": []
            }];

            response(nodes);
          }, 2000);

        }})
```
4. Expand Node Two
Result: See screenshot

**Expected behavior**
The text is rendered in the same way at top level and child level. 

**Version**
- ids-enterprise: v4.33.0

**Screenshots**
![image](https://user-images.githubusercontent.com/1101770/96560011-057b8780-12be-11eb-9c6b-a0b9222c3013.png)

**Comment by jbrcna** [comment]
**QA Passed**
v4.35.0-dev
https://master-enterprise.demo.design.infor.com/components/tree/example-ajax.html
![image](https://user-images.githubusercontent.com/56722184/99626229-b8c9ce80-2a6c-11eb-81f5-eb08608e8c7b.png)
