### ISSUE TITLE
SOHO-6131: Closing module tab from More button does not select previous tab

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#452]
Open enough dismissible module tabs so the More button appears. From the More button, select the last tab. Close that same tab from the More button menu. No tab will be selected, and the content will be blank.

You can see this at http://master-enterprise.demo.design.infor.com/components/tabs-module/example-index.html if you shrink the width enough that the More button appears.

If you close a tab from the More button that is not the last one, everything works as expected, and the previous tab will be selected.

**Steps to Reproduce**

1. Open http://master-enterprise.demo.design.infor.com/components/tabs-module/example-index.html
1. Shrink width until you see “New Tab Builder | 2 More”
1. From More button select “Order #123456”
1. See the Order #123456 is now the active tab.
1. From the More button, click the X next to “Order #123456”
1. The tab bar now shows “New Tab Builder | 1 More…” but the content below is entirely blank.

**Comment by tmcconechy** [comment]
Descoping this issue for now.
