### ISSUE TITLE
Tabs: Reorder Tabs via drag and drop

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4520]
**Is your feature request related to a problem or use case? Please describe.**
Our team is currently migrating the classic program to Angular. One of the feature that is being asked now for our User certification is the tab reordering via drag and drop, but currently soho-tabs doesn't support it. Please see below for sample behavior:

![expected_tab_reorder](https://user-images.githubusercontent.com/50192038/96696126-00513200-13bd-11eb-8268-6f05d21defa5.gif)

**Describe the solution you'd like**
Enable users to reorder tabs via drag and drop
Targeting Module tabs only and visual tabs

**Additional context**
And what application do you work on? M3 User Productivity

This has been reported before -> https://github.com/infor-design/enterprise/issues/1366 
We don't have any alternatives for the tab reordering and this is a must feature for the users.

**Comment by tmcconechy** [comment]
Adding to sprint board for discussion

**Comment by tmcconechy** [comment]
Lets start with initially only allowing drag (by option) on the visible tabs (not the overflowed tabs)

**Comment by janahintal** [comment]
Tabs are not sorting using drag and drop at https://main-enterprise.demo.design.infor.com/components/tabs-module/example-sortable.html as expected. 

![image](https://user-images.githubusercontent.com/45757016/116687169-54ca0f80-a9e7-11eb-980d-e32d6a40fa2f.png)
