### ISSUE TITLE
EmptyMesage: Calling setEmptyMessage(null) throws javascript error causing Empty message not to clear.

### ISSUE THREAD

**Issue by drinkaj** [infor-design/enterprise#4522]
**Describe the bug**
Calling setEmptyMessage(null) throws javascript error causing Empty message not to clear.

**To Reproduce**
1. Go to https://usspvwvader.infor.com/uitest/PatternTest/list/Manufacturer.ManufacturerDetailSections?csk.ng=true
2. Contact me for user name and password
3. Click on Back Order Codes tab
4. Click Refresh icon in Banner Tool Bar
5. Empty Message does not clear due to Javascript Error. 
See console javascript error. 
```
core.js:6210 ERROR TypeError: Cannot read property 'height' of null
    at Ea.setEmptyMessage (scripts-11.0.x.5061.js:1)
    at ids-enterprise-ng.js:10533
    at u.invoke (zone-evergreen.js:364)
    at s.run (zone-evergreen.js:123)
    at Kc.runOutsideAngular (core.js:41618)
    at cT.set emptyMessage [as emptyMessage] (ids-enterprise-ng.js:10532)
    at yo (core.js:13715)
    at js (core.js:12526)
    at Ur (core.js:21147)
    at zY (lm-list-grid.component.html:19)
```

**Expected behavior**
Empty message should clear.

**Version**

- ids-enterprise: 4.33

**Screenshots**
![image](https://user-images.githubusercontent.com/6230418/96743332-80f63b00-1389-11eb-836f-fbba7d822931.png)

**Platform**
 - Landmark
 - PC
 - windows 10
 - Chrome
 - latest

**Additional context**

**Comment by tmcconechy** [comment]
Try `setEmptyMessage('')` or `setEmptyMessage({})` instead of null. This seems to work but we can fix null as well.

**Comment by tmcconechy** [comment]
Pushed a fix so null works https://github.com/infor-design/enterprise/commit/e7711ff04538e6f9a02427dfedaf688b00923f2b
