### ISSUE TITLE
TabModule: Misaligned Text

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4538]
**Describe the bug**
Noticed the tabs module has issues (minor) in uplift theme. With alignment

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tabs-module/example-index.html?theme=uplift&variant=light&colors=0066D4
4. See that the text is not centered in the tab and header underneath

**Expected behavior**
Better alignment

**Version**
- ids-enterprise: [4.33]

**Additional context**
Ms teams

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
