### ISSUE TITLE
Lookup: Unable to unselect previously selected values (server side paging)

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#4539]
**Describe the bug**
Precondition: Values have been selected on the first page in a server side paged lookup. It's not possible to unselect these values when reopening the lookup, if you also navigate to another page when reopened.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/example-multiselect-paging-serverside?theme=uplift&variant=light
2. Open lookup
3. Select at least one item on page 1
4. Click Apply
5. Reopen the lookup
6. Unselect one / all of the previously selected items
7. Go to page 2 / other page
8. Go back to page 1
Result: The items are no longer unselected. The only way to unselect the items is to click Apply directly after unselecting them, without navigating anywhere else. 

**Expected behavior**
Items should be kept unselected on page 1.

**Version**
- ids-enterprise: v4.33.0

**Screenshots**
![lookup](https://user-images.githubusercontent.com/1101770/97156636-46b8df00-1777-11eb-86ed-e6318f26e4a8.gif)

**Platform**
 - Infor Application/Team Name: Homepages

**Additional context**
This is only an issue when values have been applied, e.g. saved to the input value (step 1-4)
This might be a bit related to https://github.com/infor-design/enterprise/issues/4503

**Comment by tmcconechy** [comment]
Thought this might be fixed but still seeing this issue. Leaving this open for anyone this sprint

**Comment by ericangeles** [comment]
@tmcconechy will try to figure this out

**Comment by tmcconechy** [comment]
@ericangeles did you get anywhere with this one?

**Comment by ericangeles** [comment]
@tmcconechy I was not able to check it out again. You may look at it if you want.

**Comment by tmcconechy** [comment]
ok i think i know what it might be - looking

**Comment by janahintal** [comment]
The issue is now resolved. 
Verified in https://master-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside
