### ISSUE TITLE
SOHO-5971: fixed column widths won't fill horizontally when screen starts out narrow

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#454]
To Dup:
1. Size your browser so it's more narrow than the datagrid in the sample.
2. run this sample http://localhost:4000/components/datagrid/datagrid-columns-fixed.html
3. make browser wider and see unfilled space in the datagrid

If you start out wider than the sample then it all works as expected.

**Comment by tmcconechy** [comment]
This can be solved by adding:
https://github.com/infor-design/enterprise/issues/459

So really a dup...
