### ISSUE TITLE
Translation - Japanese - "Records per page" translation needs to be amended

### ISSUE THREAD

**Issue by sachiko-infor** [infor-design/enterprise#4540]
The issue was originally logged as SunSystems JIRA <(SS5-122163) SS5-121940 - 6.4.0 PS15 - Translation issue with 'Records per page' and value 'Default'>. According to the SunSystems Dev team, this is an IDS issue.

The current Japanese translation of "Records per page" (1 ページのレコード数) doesn’t work well with the form design, as it contains a number "1" where another record-count number will be added. Please change the translation to “ページあたりのレコード数”.
![SunSystems_record per page_screenshot](https://user-images.githubusercontent.com/73469765/97162280-5578b380-17c2-11eb-9221-fb3d69df5468.png)

Also, please amend a similar translation of Groups per page  "1 ページのグループ数" to "ページあたりのグループ数".

Screenshot attached.

**Comment by tmcconechy** [comment]
cc @hwondergem - could we please get this corrected in the translation files?

**Comment by tmcconechy** [comment]
FYI - Added a comment in the strings to help for next time translating to locate

**Comment by cpinatel7** [comment]
Thanks. Linguists need to verify translations in context / at run-time

**Comment by hwondergem** [comment]
Solved in December-2020 delivery: 
  GroupsPerPage: { id: 'GroupsPerPage', value: 'ページあたりのグループ数 {0}', comment: 'Dropdown allows the user to select how many visible Groups the {} placeholder shows value. NOTE: Please change japanese to ページあたりのグループ数 for next time' },
    RecordsPerPage: { id: 'RecordsPerPage', value: 'ページあたりのレコード数 {0}', comment: 'Shows an actual number of pages in the pager. Note: Please change japanese to ページあたりのレコード数' },

**Comment by tmcconechy** [comment]
Ok thanks @hwondergem closing this then.
