### ISSUE TITLE
Column/Bar Grouped Chart: Custom Tooltip function not getting all group data

### ISSUE THREAD

**Issue by harishinfor** [infor-design/enterprise#4548]
**Description:**
When hovered on any dataset first, shows the same tooltip in another dataset. In below case consider 2019, 2020 as datasets.

**Issue1:** This issue arises when tooltip is given to each data point in the dataset of 2019 and 2020 respectively.
![image](https://user-images.githubusercontent.com/25452976/97311244-288fd380-188a-11eb-9fb0-642cd18d0499.png)
![image](https://user-images.githubusercontent.com/25452976/97311261-2cbbf100-188a-11eb-8c10-29b35dba9c91.png)

2019 chart dataset has tooltips 25, 60, 70 80, 90 and 2020 chart dataset has tooltips 35, 55, 65, 45, 75.
Initially when hovered on 2019 columns, show correct tooltips, the same tooltips seen when hovered on 2020 columns.
In the same way, Initially when hovered on 2020 columns, show correct tooltips the same tooltips seen when hovered on 2019 columns.
The issue is recorded in small video. Please find the ppt- Issue1 and open, play the video in it.

**Issue2:**  This issue arises when tooltip is given at html level.
When tooltip is given like [tooltip] = “tooltip” in html and assigned custom tooltip to it, will get only one tooltip for entire chart.
Then same tooltip seen for 2019 and 2020 datasets.
![image](https://user-images.githubusercontent.com/25452976/97312394-72c58480-188b-11eb-9825-3ae6d2dd53d3.png)

Please the attachment ppt-Issue2.

The same issue was seen in Bar Grouped chart.
[Issue1.pptx](https://github.com/infor-design/enterprise/files/5445799/Issue1.pptx)
[Issue 2.pptx](https://github.com/infor-design/enterprise/files/5445800/Issue.2.pptx)

**Conclusion:**
When hovered on any dataset first, shows the same tooltip in another dataset in Column/Bar Grouped charts.

**Comment by tmcconechy** [comment]
Should be noted that we designed this so that when you hover the group you get a tooltip. Can you base your design around that so the data in the tooltip is for that group?

**Comment by tmcconechy** [comment]
Additionally can you add (as text not screen shot).

a) the settings your passing to the chart
b) the data your passing to the chart
c) any custom css your using?

So basically we need to be able to run the example to try it as opposed to looking at videos/power points and that should do it.

**Comment by harishinfor** [comment]
HTML:
<div class="lm-height-full lm-scroll-auto">
        <div soho-column  [dataset]="columnGroupedData" [type]="'column-grouped'" [tooltip]="tooltip">
	</div>
</div>

TS file:
ngAfterViewInit(): void { 
		this.tooltip = (req: any, args: any) => {
			console.log("Args", args);
			const data = args.data || {};
			let content = "Name: " + data.name;
			content += "<br>Value: " + data.value;
			req(content);
		};
	}
const previousData = [{name:”Overall”, value:25},
                                     {name:”Quality”, value:35},
                                     {name:”Price”, value:45},
                                     {name:”Quantity”, value:55},
                                     {name:”Delivery”, value:65}] 
const currentData =  [{name:”Overall”, value:20},
                                   {name:”Quality”, value:30},
                                   {name:”Price”, value:40},
                                   {name:”Quantity”, value:50},
                                   {name:”Delivery”, value:60}]  

this.columnGroupedData = [{ data: previousData, name: “2019”},
			{ data: currentData, name: “2020” }];

**Comment by tmcconechy** [comment]
**New Summary from looking into this**

Looked into this and it seems like the column grouped is NOT passing all the data into the function.

1) Load this example i pushed column-grouped/example-custom-tooltip
2) hover each group
3) Note that its showing each value and the data in the tooltip function is for the bar.

For this type of chart the tooltip is over the whole group. So we need to fix the tooltip function to get all the data in that group so a custom tooltip can be constructed with all the data.

**Comment by jbrcna** [comment]
the issue is now resolved. 
v4.37.0-beta0
https://4370-beta0-enterprise.demo.design.infor.com/components/bar-grouped/test-custom-tooltip.html
https://4370-beta0-enterprise.demo.design.infor.com/components/column-grouped/example-custom-tooltip.html
