### ISSUE TITLE
SOHO-5858: QA for WCAG AA and AAA Contrast

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#455]
h3. Details

Test all main pages on http://usmvvwdev53:425/controls using code sniffer http://squizlabs.github.io/HTML_CodeSniffer/

For each page test all three themes.
Make sure to toggle all states, for example on the dropdown page, test with the list open and closed.
On the expandable row, test with it expanded ect
Test focus states and active and hover states (may have to plugin colors into http://webaim.org/resources/contrastchecker/)

h3. Goal
Light Theme - AA  but also test for gaps in AAA
Dark Theme - AA  but also test for gaps in AAA
High Contrast - AAA

h3. Results

*Light Theme*
Example Component Name -  http://usmvvwdev53:425/controls/link - The focus state does not pass AA and AAA
Example Component Name -  http://usmvvwdev53:425/controls/link - The focus state does not pass AA and AAA

*Dark Theme*
Example Component Name -  http://usmvvwdev53:425/controls/link - The focus state does not pass AA and AAA
Example Component Name -  http://usmvvwdev53:425/controls/link - The focus state does not pass AA and AAA

*High Contrast Theme*
Example Component Name -  http://usmvvwdev53:425/controls/link - The focus state does not pass AA and AAA
Example Component Name -  http://usmvvwdev53:425/controls/link - The focus state does not pass AA and AAA

**Comment by tmcconechy** [comment]
This will be handled with more future testing
