### ISSUE TITLE
DataGrid: Click event is not triggered when using key search

### ISSUE THREAD

**Issue by ablomq** [infor-design/enterprise#4550]
**Describe the bug**
We have columns marked as hyperlinks that relies on the click event to perform different actions. 

A SohoDataGridColumn:
```
            {
                id: column.name,
                name: column.description,
                field: column.name,
                sortable: true,
                hidden: false,
                formatter: this.getOrderNumberFormatter(m3DialogParams.h5Url),
                click: this.orderNumberCallback(m3DialogParams),           // The callback is not triggered when using key search
            };
```
But when using key search and the field is marked as found by key search the attached callback function is never called.

**Expected behavior**
A click event should be triggered so the callback function is called when clicking on a field even when using key search.

**Version**
- ids-enterprise-ng: 7.6.0

**Screenshots**
With no key search the hyperlinks works fine and the click event is triggered when clicking on the order no:
![image](https://user-images.githubusercontent.com/42343009/97285049-0b371700-1842-11eb-9682-e00970cb33c3.png)

But when using key search and the field is marked as found by key search the callback which is attacked to the click event is not triggered when clicking on the order no:
![image](https://user-images.githubusercontent.com/42343009/97285478-8c8ea980-1842-11eb-9106-aac709c430ee.png)

**Comment by tmcconechy** [comment]
Ok, great. I see it now. For some reason some are not working consistently.

**Comment by janahintal** [comment]
QA Failed. There's no console log 'clicked' . Please refer on the images below. 

After Clicking the Product Name Column (outside the link) itself. No console log.
![image](https://user-images.githubusercontent.com/45757016/100073402-72171280-2e78-11eb-8c56-d761e9c02516.png)

After Clicking the link itself.
![image](https://user-images.githubusercontent.com/45757016/100073504-8d821d80-2e78-11eb-98ea-301deec88508.png)

**Comment by janahintal** [comment]
QA Passed. 
https://master-enterprise.demo.design.infor.com/components/datagrid/example-keyword-search.html
![image](https://user-images.githubusercontent.com/45757016/100226539-dd391580-2f5a-11eb-98f5-bab8e7209f22.png)
