### ISSUE TITLE
Circle Pager: is not working as expected example tabs when in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4555]
**Describe the bug**
Circle Pager: is not working as expected example tabs when in responsive view 

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/circlepager/example-tabs.html
2. Minimize the screen until the circle pager is seen

**Expected behavior**
Circle pager is seen. No scroll bar should be seen. 

**Version**
4.33 ids - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/97432817-88a07b80-1957-11eb-8ba9-c09acb3c9d7c.png)

**Platform**
All Major Browsers. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping this one for now
