### ISSUE TITLE
Hierarchy: Broken Line when 6 or more child is expanded

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4559]
**Describe the bug**
When you expand  at least 6 child/sub child the connecting line gets broken

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/hierarchy/example-lazy-load.html
2. Expand child until possible
3. See error
4. Notice that the connecting line gets detached.

**Expected behavior**
should not be detached

**Version**
- ids-enterprise: [4.34.0-dev]

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/97571183-aedf1d80-1a22-11eb-8958-8130c27ba9fd.png)

**Platform**
All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
I did also notice this but since we dont generally use it with more that 3 levels it shouldnt be an issue for anyone. 
May descope in the future

**Comment by jbrcna** [comment]
Yeah that makes sense. Thank you @tmcconechy

**Comment by tmcconechy** [comment]
Descoping for now
