### ISSUE TITLE
SOHO-5590: hierarchy-chart not printing well

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#456]
Try printing http://master-enterprise.demo.design.infor.com/components/hierarchy/example-index.html

We should probably go after a design of:

1. print exactly what I see
2. let me print from a select node down, or a select and print type thing

**Comment by tmcconechy** [comment]
Note landmark uses paging http://localhost:4000/components/hierarchy/example-paging.html mode hierarchy so that page would be the one that would be the one to focus on for best results to impact landmark specifically

**Comment by janahintal** [comment]
Hi @tmcconechy, for clarification, on which requirements should I look into? As per my testing when I try to Print http://master-enterprise.demo.design.infor.com/components/hierarchy/example-index.html
I get this page below: 

<img width="1012" alt="screen shot 2019-02-14 at 7 24 59 pm" src="https://user-images.githubusercontent.com/45757016/52783878-44d7e680-308e-11e9-9e9a-212de034fceb.png">

Im only getting a blank page

**Comment by tmcconechy** [comment]
Looks like you have it in landscape mode. Try portrait mode and also make sure the "Background Graphics" setting is turned on. Because this uses images that setting is needed.

![screen shot 2019-02-14 at 8 16 00 am](https://user-images.githubusercontent.com/814283/52789059-d9abf700-3030-11e9-8c7c-d5ff35d0fc69.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

<img width="580" alt="print doc" src="https://user-images.githubusercontent.com/39101346/52815939-fc103580-306d-11e9-80af-15439a502d59.png">
