### ISSUE TITLE
Rating: Add ability to toggle current rating off

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#4571]
**Is your feature request related to a problem or use case? Please describe.**
Would like to be able to clear the current rating control to be zero stars.

**Describe the solution you'd like**
Allow the highest rated start star to be toggled off.

**Describe alternatives you've considered**
considered adding a "clear" button next to the rating but it adds more clutter.

**Additional context**
https://inforonline-my.sharepoint.com/personal/konstantin_lazarev_infor_com/Documents/Microsoft%20Teams%20Chat%20Files/rating%20(1).gif

![clear-rating](https://user-images.githubusercontent.com/4737815/97904601-5b145300-1d06-11eb-8683-b8aa221c951a.gif)

And what application do you work on? Landmark

**Comment by janahintal** [comment]
QA Passed. 
![image](https://user-images.githubusercontent.com/45757016/105804039-bdb17e00-5fd9-11eb-99b0-13dbd6015fe0.png)
