### ISSUE TITLE
Modal: Clicking the close button icon doesn't remove the overlay when a context menu is open 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4573]
Describe the bug
Clicking on the close button icon (ShowCloseBtn) of a modal dialog, isn't clearing the overlay when showing the context menu of a datagrid row.

Probably have to get together to show/resolve.  Attempted to duplicate the behavior using the following example but was unsuccessful.

1. Using the attached test-modal-close-btn.html
2. Click on the Open Modal button
3. Open the context menu from the grid
4. Click on the Close icon

Expected behavior
Clicking on the close icon will remove the overlay.

Version
Needed in Enterprise 4.35.x

**Comment by tmcconechy** [comment]
So i cant try these steps? If you need it in 4.35 its got to be quick. Setup a meeting with me later this week and we can look

**Comment by claudenbach** [comment]
![Git-4573](https://user-images.githubusercontent.com/39804038/98055415-04407380-1e03-11eb-8cb0-741d85b4d45d.gif)

**Comment by claudenbach** [comment]
Only see the issue when a context menu is open from the datagrid.  If the popupmenu for the more button is open and the close icon button is clicked it works fine (meaning the overlay is removed).

**Comment by claudenbach** [comment]
Here's how I attempted to dup with an example.  This however does close the popup context menu.

[Git-4573.zip](https://github.com/infor-design/enterprise/files/5484866/Git-4573.zip)
