### ISSUE TITLE
Datagrid: Changing the selectable value does not take effect

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4575]
**Describe the bug**
Changing a datagrid's selectable option doesn't take effect.  After changing the selectable value, when the user clicks on a cell in the datagrid, the incorrect event is being fired.  The selectable value has not been updated.    

**Steps to reproduce the behavior**
Attempt to change a datagrid's selectable value using either of the following did not work:
 
`this.sohoDataGridComponent.selectable = selectionMode;`
or
`this.sohoDataGridComponent.selectable(selectionMode);`

Looking at the coding for setting  the selectable value....

```
  @Input() set selectable(selectable: any) {
      this._gridOptions.selectable = selectable;
      if (this.jQueryElement) {
        // Just changing the datagrid.settings.selectable updates the datagrid view.
        this.datagrid.settings.selectable = selectable;
        this.markForRefresh('selectable', RefreshHintFlags.RenderRows);
      }
    } 
```

Probably need to get together to show/resolve.  

**Expected behavior**
The selectable value is changed from 'single' to 'mixed'. When a cell in the datagrid is clicked, its firing a row selection event, but it should be firing a row activation event.  

**Version**
Needed in Enterprise 4.35.x

Is related to Git #4573.

**Comment by claudenbach** [comment]
![Git-4575](https://user-images.githubusercontent.com/39804038/98059452-ccd6c480-1e0c-11eb-998b-1f10a1e5afb7.gif)

**Comment by tmcconechy** [comment]
I can reproduce (and ultimately fix this in EP). It looks like this variable https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L8421 is only set on startup. We could check this every time before firing the event.

Also probably could work by changing `RefreshHintFlags` to reload

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.
