### ISSUE TITLE
Badges: Text alignment is not consistent

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4578]
**Describe the bug**
Badges: Text alignment is not consistent

**To Reproduce**
1. Go to https://4340-beta0-enterprise.demo.design.infor.com/?theme=uplift&variant=contrast&colors=0066D4
2. Go to Badges Section
3. Notice the test is not in the center

**Expected behavior**
Text should be consistently aligned center

**Version**
4.340 IDS - Beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/98225781-1f8cb980-1f90-11eb-9920-13b176273c20.png)

**Platform**
All major browser and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Can also see this here https://4340-beta0-enterprise.demo.design.infor.com/components/badges/example-index.html?theme=uplift&variant=contrast&colors=0066D4 seems to be just high contrast node

**Comment by CindyMercadoReyes** [comment]
This ticket failed on high contrast across all browser. The number "15, and 912" are not centered. Please see screen shot attached. 
![bs_win10_Edge_86 0-1](https://user-images.githubusercontent.com/39101346/98738178-50486680-2375-11eb-8396-46a98283da7e.jpg)

**Comment by tmcconechy** [comment]
Will just mark this done. Its pretty close to centered in IE edge and works in other browsers. Cant see any better way to do this...
