### ISSUE TITLE
SOHO-4523: [All Browsers] Popover Control: Can't use keyboard for Popover window.

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#458]
1. http://usmvvwdev53:421/controls/popover#

2. Can't use keyboard to tab into ABC Information Popover or XYZ Engine Company. As a user you are able to open the pop ups for both but the user has no way of being able to get into the actual pop up. There is not way to click on the "X", Apply, or View More fields using keyboard.

**Comment by EdwardCoyle** [comment]
I just retested this on http://master-enterprise.demo.design.infor.com/components/popover/example-index.html, and I'm not sure this is an issue anymore.  If you do the following...

- Press `Tab` until focus is on the popover trigger button
- Press `Enter` to open
- Press `Tab` to focus the first item in the Popover (X button)

...that all works as expected.  I think we can probably close this one.

**Comment by tmcconechy** [comment]
Yeah i see it working as well. Looks fine (except minor issue with no focus on link).
Lets close and bring that one up.
