### ISSUE TITLE
Application Menu: Indentation is not dramatic enough

### ISSUE THREAD

**Issue by lipetzan** [infor-design/enterprise#4580]
**Describe the bug**
Differentiation of menu path is difficult to see (indention is not dramatic enough)

Can something more be done to help the eye follow the various levels

**Comment by tmcconechy** [comment]
Do you have a screen shot or anything? Not sure as to what your referring to?

**Comment by lipetzan** [comment]
![image](https://user-images.githubusercontent.com/42155063/98278967-f142b600-1f5e-11eb-87b4-ccb81ef6e00b.png)

**Comment by lipetzan** [comment]
Koch Ind feedback from FSM users trying out 4x.

**Comment by tmcconechy** [comment]
I think we noticed this before on your system and discussed it with @pwpatton your using the second level menu items as the first level and we have it in the design like this:

https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html

So normally if you configure it that way it will look a little different here https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html?theme=uplift&variant=light&colors=0066D4

**Comment by tmcconechy** [comment]
Descoping this for now (see previous reply). I think your using it wrong as it does what you want in the normal configuration we have
