### ISSUE TITLE
Autocomplete: Search results not showing when using source function

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#4584]
**Describe the bug**
Results are not showing when using the source function.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/4.34.0-beta.0/demo/components/autocomplete/example-templates
2. Begin searching for Alex 
3. Go to https://design.infor.com/code/ids-enterprise/4.34.0-beta.0/demo/components/autocomplete/test-ajax-as-function
4. Begin searching for a state

**Expected behavior**
"Alex Mills" option should show up. 

**Version**
- ids-enterprise: v4.34.0-beta.0

**Screenshots**
![autocomplete](https://user-images.githubusercontent.com/1101770/98529395-d6818180-227d-11eb-91d4-db5aee202221.gif)

**Additional context**
If using an endpoint url as source, it works fine, such as https://design.infor.com/code/ids-enterprise/4.34.0-beta.0/demo/components/autocomplete/example-index

Both failing samples work fine on 4.33.0:
https://design.infor.com/code/ids-enterprise/latest/demo/components/autocomplete/example-templates
https://design.infor.com/code/ids-enterprise/latest/demo/components/autocomplete/test-ajax-as-function

The only change I can see related to autocomplete in 4.34.x is https://github.com/infor-design/enterprise/issues/4387

**Comment by tmcconechy** [comment]
I noticed this as well the end of last week and put a fix in 4.34 and master branch https://github.com/infor-design/enterprise/commit/9f85b89fb4a6694d392648123ca98b2b94ac7801

It will be ok in the final 4.34.
