### ISSUE TITLE
Datepicker: Stops working with iOS 14.1+

### ISSUE THREAD

**Issue by ahnpnl** [infor-design/enterprise#4585]
**Describe the bug**

When tapping on datepicker input field, it no longer opens datepicker pop-up after upgrading iOS to 14.1+

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-index?theme=uplift&variant=light on an iPhone with iOS 14.1+
2. Tap on the datepicker input field
3. Observe that the datepicker pop-up doesn’t open

**Expected behavior**

Should open datepicker pop-up 

**Version**

- ids-enterprise: 4.32.0

**Screenshots**

**N.A.**

**Platform**
 - Infor Application/Team Name: **N.A.**
 - Device: iPhone 8
 - OS Version: iOS 14.1/14.2
 - Browser Name: chrome/safari
 - Browser Version: latest

**Additional context**
**N.A.**

**Comment by tmcconechy** [comment]
I tried this on an xcode simulator running Iphone Pro 14.1 and did not see any problems. But to clarify the functionality:

- if you click on the input it will focus the field
- if you click the button it seems to be opening the picker just fine

https://drive.google.com/file/d/1r3IBadrRis_EIFYyBXfw5WGiufSybgcN/view

**Comment by ahnpnl** [comment]
oh ya, you were right. I remember the wrong detail about that component. Thank you !. There is no issue indeed if tapping on the icon.
