### ISSUE TITLE
SOHO-3459: Datagrid - Responsive to Card - Column Sets

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#459]
Implement ability to specify a card template. On mobile breakpoints or tablet the datagrid design uses the card template instead.

Add a sub tasks to implement the Formatter for the qualifications column.

Feature Specs:
- Add is-card style that lays out the grid in configurable card form.
- Add three sets of columns at each break point the column set can be defined.

This would allow different column sets per breakpoint as well as optional card at each breakpoint.

Design:

[Responsive Date Grid.pdf](https://github.com/infor-design/enterprise/files/2205600/Responsive.Date.Grid.pdf)

**Comment by clepore** [comment]
A workaround for this can be by putting both a card view and datagrid on a page, and then hiding/showing the specific one based on different breakpoints.

**Comment by sminforlms** [comment]
Hey folks, is "wont fix" latest and greatest status for overall enhancement?

**Comment by clepore** [comment]
@sminforlms Yes it is 👍 

(since the requested goal can be already be achieved with the current components)

**Comment by sminforlms** [comment]
Ok thanks, is there any sample code/example that we could share with devs? or documentation? just want to make sure they know what to do :)

**Comment by clepore** [comment]
While we don't have anything specific to this instance, it should be fairly basic if they are familiar with building responsive apps/websites. The main gist is that you would have both components on the page, but hide/show each section as you wished.

For instance, on a normal desktop they could show the datagrid, but when you go to the url on your phone, they could hide the datagrid, and show the card section.
