### ISSUE TITLE
AppMenu: Not able to set module tabs appMenuTriggerText to empty string

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise#4590]
**Describe the bug**
For the module tabs you can provide options to have and set the application menu trigger text:
```typescript
const TABS_DEFAULT = {
  ...otherStuff,
  appMenuTrigger: false,
  appMenuTriggerText: undefined,
  ...moreStuff,
};
```
If `appMenuTrigger` is true but `appMenuTriggerText` is not set, it will default to `Locale.translate('AppMenuTriggerText')`. We would like to be able to not have a title text i.e. "" (blank). Currently, if we provide empty string it defaults to 'Menu' due to the following on line 543 in tabs.js:
```html
<span>${this.settings.appMenuTriggerText || Locale.translate('AppMenuTriggerText')}</span>
```
So we currently specify `" "` a space which won't evaluate false, but has the side effect of the icon becomes misplaced.

**To Reproduce**
1. Set appMenuTrigger to true and appMenuTriggerText to "" (empty)
2. You will have 'Menu' as the trigger text

**Expected behavior**
When provide empty string i.e. `""` there shouldn't be a default.

**Version**
- ids-enterprise: 4.35.0-dev

**Screenshots**
The menu icon becomes misplaced by adding the space:
<img width="347" alt="Screenshot 2020-11-09 at 20 15 14" src="https://user-images.githubusercontent.com/73601152/98585943-4ae11280-22c8-11eb-87e7-d72e95516688.png">

**Platform**
 - All

**Additional context**
Using the nullish coalescing operator (??) ([CanIuse](https://caniuse.com/mdn-javascript_operators_nullish_coalescing)) instead of the logical or (||) would let empty string through, but at the same time set the default text appMenuTriggerText 
 is null or undefined.
```html
<span>${this.settings.appMenuTriggerText ?? Locale.translate('AppMenuTriggerText')}</span>
```

**Comment by tmcconechy** [comment]
As an alternate workaround does setting it to `&nbsp;` work?

**Comment by whernebrink** [comment]
@tmcconechy Forgot to mention I've already tested that too, with the same result as `" "`.

**Comment by whernebrink** [comment]
Also, I forgot to mention: in our code we have to unset the min-width for the application-menu-trigger in order to get the trigger not look huge:

This is how it looks by default if one set the trigger text to `" "`:
![Screenshot 2020-11-10 at 22 34 01](https://user-images.githubusercontent.com/73601152/98736243-d9c35d00-23a4-11eb-8a74-a3f11a3d69dd.png)

We have to add the following style:
```scss
:host::ng-deep {
    [soho-tab-list] {
      .tab.application-menu-trigger {
        min-width: unset;
      }
    }
  }
```
Ouput:
![Screenshot 2020-11-10 at 22 31 29](https://user-images.githubusercontent.com/73601152/98735966-7c2f1080-23a4-11eb-95fe-98e8f1439dd0.png)

When also removing the previously mentioned margin, we get the desired output (which I do think should be default if you were to add set `" "` as value for the `appMenuTriggerText`:

With removal of margins:
```scss
:host::ng-deep {
    [soho-tab-list] {
      .tab.application-menu-trigger {
        min-width: unset;

        span:not(.icon) {
          margin: 0;
        }
      }
    }
  }
```
![Screenshot 2020-11-10 at 22 37 21](https://user-images.githubusercontent.com/73601152/98736603-50605a80-23a5-11eb-8ad3-7687ab0e1ba4.png)

**Comment by tmcconechy** [comment]
Is this using this example https://master-enterprise.demo.design.infor.com/components/tabs-module/example-app-menu-button.html but just without the Menu text? Or maybe you werent aware of this configuration?

The more i look at this it looks like that example

**Comment by whernebrink** [comment]
Correct, I'm using that appMenuTrigger with appMenuTriggerText set to `" "`. Yep, without the menu text is what we want and also, when the button only consist of the bars, that the width of that trigger button is no bigger than the actual icon.

**Comment by janahintal** [comment]
QA Passed. 
Verified in https://master-enterprise.demo.design.infor.com/components/tabs-module/example-app-menu-button-audible.html?layout=nofrills. Used Chrome Reader Extension for verification.
