### ISSUE TITLE
Splitter: Right splitter is not working as expected (too much space in the splitter)

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4591]
**Describe the bug**
Splitter: Right splitter is not working as expected (too much space in the splitter)

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/splitter/example-splitter-right.html
2. Move the splitter to the left side
3. Move the splitter to the right side (fast)

**Expected behavior**
Splitter should look fine and not have too much space like in actual

**Version**
4.350 ids - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/98674058-387fdb00-2393-11eb-8e27-03bffdce2df6.png)

**Platform**
All major browsers. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Could be a tricky one to fix , i think what's happening when you drag fast is the drag ends before the element moves across the page.

**Comment by tmcconechy** [comment]
Descoping for now
