### ISSUE TITLE
Application Menu: If search finds children then the parent is not expanded

### ISSUE THREAD

**Issue by Milan1983** [infor-design/enterprise#4592]
**Describe the bug**
In some search conditions the results is not expanding.

**To Reproduce**
- Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/applicationmenu/example-filterable?theme=uplift&variant=light
 -Search for "Task #3"
- Results is collpased

**Expected behavior**
Results should be expanded

**Version**
V 4.34.0

**Platform**
- Chrome Version 86.0.4240.183

I think the problem it is in done method.

**Comment by tmcconechy** [comment]
Any other specifics you have on it being in the done method would be helpful to speed up a fix?

**Comment by Milan1983** [comment]
Unfortunately not @tmcconechy .
Also I realized when you search non-existed items,show all results,and I think is wrong.

**Comment by tmcconechy** [comment]
ok we will have a look

**Comment by Milan1983** [comment]
Thank you @tmcconechy

**Comment by Milan1983** [comment]
Is it possible to investigate this situation, please.

https://design.infor.com/code/ids-enterprise/latest/demo/components/applicationmenu/example-filterable?theme=uplift&variant=light

 

1- search for 'zzzz'
Results : Everything and is possible expand
   step 1)
           My Account
           Bookmarks
           History
           Homepages
          My Roles
step 2) if you clicked for example on My Account,it is possible to expand
            My Account
                    Notifications
                    Administrator
                    User Settings
                    Help
           Bookmarks
           History
           Homepages
          My Roles
      
           
         
Expected: 
      step 1)
           My Account
           Bookmarks
           History
           Homepages
          My Roles
   step 2) Not possible to expand

I think shows everything and works in an 'unfiltered' mode basically.

**Comment by tmcconechy** [comment]
think simpler put - searching for zzzz is returning all results and not filtering to nothing as i would expect. I think this should be fixed as well on this issue

**Comment by jbrcna** [comment]
**QA Passed**
v4.36.0-dev
In the app menu searchfield, type `"#3"`. After filtering completes, the results should include: `"Role #1 Task #3", "Role #2 Task #3", and "Role #3".`
![image](https://user-images.githubusercontent.com/56722184/103198699-edf6f580-4923-11eb-84f2-8831eac412e9.png)

Clear the searchfield and type "`zzzzz`". After filtering completes, `no items should be present` in the filter results.
![image](https://user-images.githubusercontent.com/56722184/103198714-00712f00-4924-11eb-8fa5-cb7959506556.png)
