### ISSUE TITLE
DataGrid: Possibillity to show data type in the header

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#4596]
**Is your feature request related to a problem or use case? Please describe.**
We are filling the datagrid with data comming from SQL and because we need values to be displayed as strings as they come from backend (no localization, no datetime transformations, number formatting, etc) we somehow need to show users what data type it is like float, int8, int16, double, long, string, date, datetime, boolean, etc.

**Describe the solution you'd like**
some kind of icons which could be set for the header like:
![image](https://user-images.githubusercontent.com/11279863/98699322-4de70c00-2377-11eb-9de6-e197af8aa30c.png)

or maybe something like _subheader_?

**Describe alternatives you've considered**
Tooltip is not a solution for us, because its already showing possible ellipsified column names.

**Comment by tmcconechy** [comment]
Wondering if you know which other grid features you plan to use? Filter, Sort, Arrange?

**Comment by hohnzy** [comment]
We have only search filtering. Column filtering is not user friendly when all the values are just _string_. Also sorting is not really applicable.
Our product is basically SQL editor, so sorting and filtering can be done in a query
![image](https://user-images.githubusercontent.com/11279863/98706241-ec2aa000-237e-11eb-9cc8-0d2417a8f68e.png)

**Comment by tmcconechy** [comment]
cc @inforandy what do you think about making these database icons?

**Comment by kevinwhitedesign** [comment]
@hohnzy I don't think using icons would be a wise choice because I could see the communication breaking down very easily considering the very specific ones like " int8, int16, string". From my icon creator pov these would visually be hard to create metaphors for. 

I think there's some weight with what was said about an 'eyebrow' text or maybe something such as a parenthesis after the col name example:

firstname (String)

Only problem there is losing the information to truncation, although the name would be available on hover or resize of the col headers.

Worth exploring @katieinfor maybe we can get a ticket for this assigned to me

**Comment by hohnzy** [comment]
![image](https://user-images.githubusercontent.com/11279863/114554685-48178e80-9c67-11eb-81ea-8b631e6f1a12.png)
These were used for the file types, I can imagine similar style... Or what about some kind of subheaders? I would rather have taller header row than forcing users to resize the columns (+ the column resizing is kinda buggy when all the columns fit into the screen width)

**Comment by tmcconechy** [comment]
My biggest concern is how to fit it in with all the other "icons" on the header here:

![image](https://user-images.githubusercontent.com/814283/114561314-77b0a180-9c3b-11eb-8f07-c90dfd7ddb65.png)

If we add this we'd need to make sure it all works/fits. Not certain there is a big advantage to adding this from a UX standpoint vs the complication.

**Comment by katieinfor** [comment]
@kevinwhitedesign created a ticket for this in Jira! https://jira.infor.com/browse/UXD-2370 thanks.

**Comment by inforandy** [comment]
@tmcconechy let me know if there is any further feedback required here, otherwise looks like we are set

**Comment by tmcconechy** [comment]
@hohnzy after https://github.com/infor-design/enterprise/issues/6490 is done this should be possible FYI

**Comment by CindyMercadoReyes** [comment]
This task has been completed

**Comment by tmcconechy** [comment]
Closing as this was implemented https://main-enterprise.demo.design.infor.com/components/datagrid/example-header-icon-with-tooltip.html
