### ISSUE TITLE
Charts: Ability to make a combined column chart and line chart

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4598]
**Is your feature request related to a problem or use case? 
Use case to enable user to generate column chart with combination of line graph.
Please see below for example:
![image](https://user-images.githubusercontent.com/50192038/98805361-69731500-2452-11eb-8ac7-598b8513d686.png)

**Describe alternatives you've considered**
No alternatives yet

**Additional context**
And what application do you work on? M3 H5 UI Team
Tagging @lucacolumbu

**Comment by janahintal** [comment]
QA Passed. Thanks! 👍 
![image](https://user-images.githubusercontent.com/45:757016/141084257-155faf0d-2a6b-43da-8401-dc17a84acb3b.png)
![image](https://user-images.githubusercontent.com/45757016/141085155-dc0fe547-7fe9-497b-bd88-36d8e89bbadb.png)

**Comment by CindyMercadoReyes** [comment]
BDD attached.
[BDDStory_github4598.docx](https://github.com/infor-design/enterprise/files/7618850/BDDStory_github4598.docx)
