### ISSUE TITLE
Dropdown: Press caps lock or backspace in a collapsed dropdown list - unknown character appears

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4599]
**Describe the bug**
Press caps lock or backspace in a collapsed dropdown list - unknown character appears

**To Reproduce**
go to https://latest-enterprise.demo.design.infor.com/components/dropdown/example-index.html
1. search any item on dropdown
2. select matching searched item
3. on select the dropdown will collapsed
4. press caps lock or backspace

**Expected behavior**
No unknown character should show when pressing caps lock or backspace

**Version**
ids-enterprise-ng: 7.2.4 or here https://latest-enterprise.demo.design.infor.com/components/dropdown/example-index.html

**Screenshots**
![unknown character on soho dropdown when collapsed](https://user-images.githubusercontent.com/50192038/98806632-6f69f580-2454-11eb-8416-4c1f7f05c864.gif)

**Platform**
 - Infor Application/Team Name: M3 H5 UI Team
 - Device: N/A
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Browser Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
What's that onscreen keyboard your using? I tried this on Mac and could not reproduce but its possibly a windows only thing?
Is this maybe https://github.com/infor-design/enterprise/issues/4020 ? But that was fixed a while ago.

Will investigate further next sprint

**Comment by marclouisgenedeguzman** [comment]
yup its Windows on screen keyboard. I think the back space was fixed on that ticket, but we can still produce unknown character for caps lock.

**Comment by CindyMercadoReyes** [comment]
Hi @tmcconechy I was unable to reproduce this issue on my Window's base PC.  Kind regards, Cindy

**Comment by tmcconechy** [comment]
We cant seem to reproduce this on a normal PC. It must be something with that on screen keyboard which we dont have perhaps?

Since we cant do anything much about this , will close
