### ISSUE TITLE
Split program when a user drops a tab on another tab

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4600]
**Is your feature request related to a problem or use case? Please describe.**
Use case: Our classic program have the ability for split screen when a user drops a tab on another tab

**Describe the solution you'd like**
Ability for users to split 2 programs when they drop a tab on another tab.

**Describe alternatives you've considered**
Currently we have styling in place to make it look like the programs are split.
Below is an example of the feature from our classic UI:
![split program when a user drops a tab on another tab](https://user-images.githubusercontent.com/50192038/98809831-2cf6e780-2459-11eb-95c3-415a3a6299c1.gif)

**Additional context**
And what application do you work on? M3 H5 UI Team

Tagging @lucacolumbu

**Comment by tmcconechy** [comment]
We have some of feature called multi tabs. https://master-enterprise.demo.design.infor.com/components/tabs-multi/example-index.html

In this example you can move tabs via the right click menu. I think maybe the drag option to split is missing but thats also not that discoverable. 

For dragging we need https://github.com/infor-design/enterprise/issues/4520 first

**Comment by katieinfor** [comment]
We need to investigate the behavior before moving forward. Thanks!

**Comment by tmcconechy** [comment]
@ericangeles @tjamesallen15 - can you guys add a PR with types for the NG. Thanks!

**Comment by ericangeles** [comment]
@tjamesallen15 please proceed to this.
