### ISSUE TITLE
Environment: EDGE is not detected

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4603]
**Describe the bug**
When using Microsoft Edge Browser, `currentBrowser` & `browserVersion` is not displayed as EDGE

**To Reproduce**
1. Open Edge browser
2. Navigate to https://master-enterprise.demo.design.infor.com/components/environment/example-browser-specs.html
3. See error

**Expected behavior**
Should display Microsoft Edge specs

**Version**
- ids-enterprise: v4.35.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/98941703-e7edb680-2527-11eb-89a5-a005176ffb8a.png)

`About` component has the right browser name. However, the version is different
![image](https://user-images.githubusercontent.com/56722184/98941883-21bebd00-2528-11eb-9199-7770d327ebac.png)

**Platform**
EDGE 

**Additional context**
Also in` iPhone 11 Pro  - Chrome`
**Safari** is displayed as currentBrowser
![image](https://user-images.githubusercontent.com/56722184/98941777-fd62e080-2527-11eb-9d9a-4507b8e6f48a.png)

**Comment by tmcconechy** [comment]
@danielortiz1982 for consideration

- isEdge > is actually for IE Edge 11
- Maybe we add an isEdgeChrome() 
- Check the wrong version number issue
- Check why on iPhone 11 Pro - it ssaying chrome is true

All these is in about.js or environment.js

**Comment by jbrcna** [comment]
QA Failed. 
v4.39.0-dev
https://master-enterprise.demo.design.infor.com/components/environment/example-browser-specs.html
The issue on ` MS Edge` is now resolved. However, when using `chrome `browser with `iOS devices`, Safari is displayed as current browser. Failing this ticket for now.
![image](https://user-images.githubusercontent.com/56722184/112431209-2dde4500-8d7a-11eb-99b5-9a3b921ffe90.png)

**Comment by tmcconechy** [comment]
@danielortiz1982 can you please have another look at this case? Its probably easily fixable

**Comment by danielortiz1982** [comment]
@tmcconechy I will have a looks this morning.

**Comment by tmcconechy** [comment]
For the last part lets table it for now. Its "close enough"
