### ISSUE TITLE
Datepicker: Incorrect placement within vertically short area

### ISSUE THREAD

**Issue by kvaldillez** [infor-design/enterprise#4605]
**Describe the bug**
Datepicker/calendar has incorrect placement in relation to its field when it has vertically less room to display.

**To Reproduce**
1. Go here: https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat?theme=uplift&variant=light
2. Make browser window half the height of your screen (or more if you have a larger monitor)
3. Click on any of the calendar icons
4. Observe offset placement to the field in which it relates to

**Expected behavior**
I would expect the datepicker to be offset to the left or right of the field if there is not enough space above or below the field to show it.

**Version**
4.34.0

**Screenshots**
![clicked-top-field](https://user-images.githubusercontent.com/13121777/98984244-cb755e00-24d6-11eb-82a0-c44671c2d4f2.png)
![clicked-bottom-field](https://user-images.githubusercontent.com/13121777/98984245-cc0df480-24d6-11eb-9a9d-51cdfcbf25f5.png)

**Platform**
 - Infor Application/Team Name: Infor Front-end-framework
 - OS Version: macOS Catalina 10.15.6
 - Browser Name: Chrome
 - Browser Version: 85.0.4183.121

**Comment by tmcconechy** [comment]
We'll take a look when we get to updating the place logic

**Comment by tmcconechy** [comment]
While we didnt actually fix this in the new version https://main.wc.design.infor.com/ids-date-picker/example.html the space is a little less with the optional buttons removed.
