### ISSUE TITLE
Locale: setLanguage is throwing Maximum call stack size exceeded error in console for "en-GB"

### ISSUE THREAD

**Issue by VINAYREDDY59** [infor-design/enterprise#4607]
**Describe the bug**
While setting the language using Soho.Locale.setLanguage, it is throwing error in console for "en-GB".

**To Reproduce**
1. Download the attached project.
2. Goto project Location.
3. Run "yarn" or "npm install" to install all the dependencies.
4. After Installing the dependencies , Run "Yarn start" or "ng serve" or "npm start"
5. After the application ran, open localhost:4200 in your browser.
6. And observe a console error saying "  Maximum call stack size exceeded".
( Please find the attached screenshot to see the full error).

**Expected behavior**
Soho.Locale.setLanguage shouldn't throw error in console.

**Version**
- ids-enterprise: 4.31.2
-ids-enterprise-ng : 7.5.3. 
Note: ids-enterprise-ng: 8.0.3 and 8.1.0 also have the same issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/31958563/99043628-81fb4080-25b4-11eb-9968-7e548c333028.png)

**Platform**
 - Infor Application/Team Name: Inbox/ ION
 - OS Version: Windows 10.
 - Browser Name: chrome.
 - Browser Version:Version 86.0.4240.193 (Official Build) (64-bit)

**Additional context**
Please find the attached Project.
[Soho-bug-repo-copy.zip](https://github.com/infor-design/enterprise/files/5535518/Soho-bug-repo-copy.zip)

**Comment by tmcconechy** [comment]
Duplicates #3455

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by janahintal** [comment]
QA Passed. Thanks.
Will now move to Done.
