### ISSUE TITLE
General: When was support for IE11 withdrawn?

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#4608]
Hi,

Is IE11 still supported in IDS or has it been withdrawn?

I've just upgraded from IDS 4.26 to 4.34 and due to an issue with drop-down boxes appearing in the wrong place and no longer responding, I can't even sign on to our system via the standard sign on screen... 

![image](https://user-images.githubusercontent.com/44396995/99058607-5b79dd00-2595-11eb-8044-26f234c3d7ad.png)

Looks like an exception is being thrown in JQuery when I click the drop down button...

![image](https://user-images.githubusercontent.com/44396995/99058674-73516100-2595-11eb-93bd-3d379eaa28ec.png)

![image](https://user-images.githubusercontent.com/44396995/99058814-9aa82e00-2595-11eb-9272-fc3d58512f5c.png)

I tried to look at the standard examples for the IDS Enterprise site in IE11 and they do not work either. I can see fixes in the release notes for IE11 issues up to 4.31, so is that the last version to support IE11?

Dropping support for IE11 is a show-stopper for our Infor application as we still have to support it for some legacy functionality.

**Comment by tmcconechy** [comment]
Yes as of October we do not support IE 11 anymore. This was planned out on https://github.com/infor-design/enterprise/issues/3756

The last version 4.34 was the first one that we no longer tested for IE11. Before that for the last 6 months we only fixed critical issues. This decision is inline with several other major groups. And with the Infor Policy docs (support R-1 browsers).

We don't want to reverse this decision so we can free up resources for other things.

However, This issue would be easy to fix. It is something we added recently and probably just needs an if `!ie 11` check. So i can fix it for this version now. We plan on keeping the IE11 code in for one more year at least (the 5.0 version definitely won't support IE 11).

So i'll put in a fix for this to get you buy why you adjust your support matrix in the future?

**Comment by sanx72** [comment]
That's a bit of a unexpected blow to us as we have a legacy part of our user interface that still requires IE11 (for an ActiveX plugin). We are re-writing the functionality in HTML/web technology, but as we are a very small dev team, I'm essentially having to fit it in between other development, support and day-to-day tasks so unlikely we will be able to stop supporting IE11 until the middle of 2021, if not longer. 

Thanks for accepting the issue itself; as I really need this in the 4.34 release to go into our Q4 2020 build, I guess I'll need to bespoke fix the sohoxi.js file myself and re-minify. Presume this is just IE11 not accepting an object as the third parameter to addEventListener?

**Comment by tmcconechy** [comment]
Yeah i guess the time is about right then. So let's say we don't support IE 11 but if you have issues we can assess them. Will fix this one for you in 4.34 no problem. I think it just needs a check as this code doesnt need to run at all in IE 11

**Comment by sanx72** [comment]
Much appreciated Tim, if I hit any IE11 specific issues in future, I'll only flag them up if I can't resolve them in our code.

**Comment by sanx72** [comment]
Downloaded 4.34.2 and dropdown issue in IE11 is resolved and didn't come across any others during unit testing. Many thanks for the quick turnaround on this issue.
