### ISSUE TITLE
Popdown: Seems off when in Vibrant High Contrast or Dark Mode

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4609]
Popdown: Seems off when in Vibrant High Contrast or Dark Mode

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/popdown/example-index.html?theme=uplift&variant=contrast&colors=003876
2. Open the popdown 
3. Also try in Dark mode

**Expected behavior**
Popdown header should look consistent. 

**Version**
4.350 dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/99071070-66139100-25ec-11eb-801b-d6f278cc45ff.png)

**Platform**
All Major Browsers

N/a

**Comment by tmcconechy** [comment]
Descoping for now
