### ISSUE TITLE
SOHO-3146: Relative date/time format

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#461]
The GT Nexus Front End team has gotten a request for relative date/time formats, something akin to what [Moment.js|http://momentjs.com] has.

A few examples
11/9/2015 => 2 days ago
11/11/2015 2:30 PM => in about 1 hour

Something that also should be considered is a) whether to update date/times if formatted in this way as time passes, and b) if so, how often/during what event. I'm not sure whether it makes sense for the control to handle this or not, but should be part of the discussion.

**Comment by tmcconechy** [comment]
Since we are pulling this data out of the CLDR we can support these configurations...
http://www.unicode.org/repos/cldr-aux/json/22.1/main/en.json

**Comment by theakatz** [comment]
related to #592

**Comment by tmcconechy** [comment]
Descoping this issue for now.
