### ISSUE TITLE
Form: Read Only vs Disabled element

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4611]
**Describe the bug**
The Read-only element looks like a Disabled field ( vice versa )

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/form/example-readonly-inputs.html
2. Notice that `Searchfield (Readonly)` doesn't seem to appear like the rest of the form elements
_The placeholder of the search field is greyed out while the rest of the form elements looks darker_
3. Go to https://master-enterprise.demo.design.infor.com/components/form/example-disabled-field.html
4. Click the button `Click to Disable`
4. Notice that `Searchfield` doesn't seem to appear like the rest of the form elements

**Expected behavior**
For disabled element, it adds some style (grayed-out)
![image](https://user-images.githubusercontent.com/56722184/99253792-572b1980-284c-11eb-90e6-dd5ef45bf94e.png)

**Version**
- ids-enterprise: v4.35.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/99253752-44184980-284c-11eb-9c67-8a336357e08a.png)

**Platform**
Mac OS Safari

**Additional context**
I'm not really sure about this but when I think of a `read-only` element The browser doesn't add any visual style for "read-only" elements. whereas the `disabled` element it adds some style (grayed-out) to disabled elements. please see the screenshot below.
![image](https://user-images.githubusercontent.com/56722184/99253724-39f64b00-284c-11eb-99c1-33dc4ac98a0b.png)

**Comment by tmcconechy** [comment]
Yes it looks like a css bug in safari. It looks ok in Chrome. Good catch

**Comment by jbrcna** [comment]
working as expected. it looks disabled now
v4.39.0-dev
https://master-enterprise.demo.design.infor.com/components/form/example-disabled-field.html
![image](https://user-images.githubusercontent.com/56722184/112590587-0a7cce00-8e3e-11eb-85a7-9f28b9648a5c.png)
