### ISSUE TITLE
Datepicker: shows placeholder and error for non-required fields in some languages

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#4613]
**Describe the bug**
Datepickers that are not required shows errors in some languages when emptied.
This issue only happens in some languages; The following which we've found so far: Swedish, Afrikaans (South Africa), Danish (Denmark), Dutch (Netherlands), French (Canada), Hindi (India), Korean (Korea), Lithuanian (Lithuania)
The issue is that if you have an input value in the datepicker and then remove it some formatted error is shown (Even when no date is allowed)

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-timeformat?locale=sv-SE 
2. Click on the first datepicker
3. Pick a date so that the input field shows a value
4. Mark the text
5. Delete it
=> Notice that some form of format placeholder is shown
6. Click outside the datepicket
=> Notice that there are errors showing in the input
7. Do the same steps for en-US => No placeholder or errors are showing

**Expected behavior**
There should not be any errors when removing the value from a datepicker that allows no value. Also I haven't seen this error placeholder before.

**Version**

- ids-enterprise: 4.34.1

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/99380643-87190200-28ca-11eb-821b-a03d231ea4a5.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 1
 - Browser Name: Chrome
 - Browser Version: Version 86.0.4240.183 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
The mask pattern is a configuration you can do to make it have a placeholder. Its an option and not commonly used. My guess is this is just a problem with this examples configuration but will take a look into it if we can next sprint

**Comment by SofiK** [comment]
Hi Tim! 
Yes please take a look at it. We discovered this issue in Homepages after the latest IDS update. And it only happen for some languages. We are not using the mask pattern.

**Comment by tmcconechy** [comment]
Seems like something changed between 4.32 and 4.33 where masks with `-` in the date pattern fail like this

https://4320-enterprise.demo.design.infor.com/components/datepicker/example-timeformat?locale=sv-SE

Moving this up

**Comment by janahintal** [comment]
This issue is now resolved. 
![image](https://user-images.githubusercontent.com/45757016/100199501-3d6a9000-2f38-11eb-853f-7f29ab3a4c95.png)
