### ISSUE TITLE
Datagrid: Cant open context menu with the keyboard and close with escape (in NG)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4614]
**Describe the bug**
Two issues with grid context menu keyboard. One is the shortcut key isnt working. The other is that in angualr the reset focus isnt working

**To Reproduce**
**Issue One**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-contextmenu.html
2. Click any cell
3. Hit Shift+F10
4. See error - > context menu should open (this works on https://master-enterprise.demo.design.infor.com/components/contextmenu/example-index.html d)

**Issue Two**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/datagrid-dynamic
2. click a cell (second one)
3. right click
4. hit escape -> should focus back the cell -> this works on https://master-enterprise.demo.design.infor.com/components/datagrid/test-contextmenu.html

**Version**
- ids-enterprise: [e.g. v4.34]

**Platform**
 - Chrome

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-31984

**Comment by ceszilla** [comment]
hi Tim. this is one of the identified High Priority VPAT items. thanks.

**Comment by tmcconechy** [comment]
NOTE: To @pwpatton and LM the way the datagrid-dynamic was setup the issue on  infor-design/enterprise#4873 will never work. I had to change the example to not use immediate and then do the menu loading in onContextMenu but use the menuID linkage so the datagrid knows what to do know. You will need to make the same changes to make this work. See the changes on 

https://github.com/infor-design/enterprise-ng/pull/999/files#diff-b763524007616a39303afc6afc4afe9c56777ae3e9ca8051ab00440f305981eaL33
and
https://github.com/infor-design/enterprise-ng/pull/999/files?file-filters%5B%5D=.js&file-filters%5B%5D=.md&file-filters%5B%5D=.ts#diff-861d7ccd6b8be10cb86b93958856e36922dd58509db1220ffc186db3642ca72aR39

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-contextmenu.html
![image](https://user-images.githubusercontent.com/45757016/109461758-98fb6b00-7a9d-11eb-978c-721ff83ac762.png)
