### ISSUE TITLE
Datagrid: Option to display tooltips by column

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#4616]
**Is your feature request related to a problem or use case? Please describe.**
Relates to a Landmark ticket. Some of our lists have large tooltips, depending on the column content. It would be nice if there was a way to have more control over the tooltips created while using the datagrid. .

**Describe the solution you'd like**
For example, card cells create really large tooltips while also including content that is not pertinent. And example of this can be seen here http://localhost:4000/components/datagrid/test-card-cell.html. Tooltips are also being created for some cells where they aren't really needed, hyperlinks for example.  (see screenshot)

**Describe alternatives you've considered**
A possible workaround is to disable the `enableTooltips` option. But this is not ideal.

**Additional context**
<img width="648" alt="ids-enterprise-card-tooltip" src="https://user-images.githubusercontent.com/1056684/99442660-4f688500-28df-11eb-8062-c63f4d326d0f.png">
<img width="99" alt="tooltip-on-hyperlink" src="https://user-images.githubusercontent.com/1056684/99442669-5099b200-28df-11eb-93a4-b1dbc35b77bd.png">

**Comment by tmcconechy** [comment]
So you mean that the enableTooltips option can be applied by column instead of the whole thing?

**Comment by krishollenbeck** [comment]
@tmcconechy Yes Also wondering if maybe there is a way to prevent cards from having all content included in the tooltip? I am not sure how that part is designed from an ids standpoint? As far as I know, we  just pass an HTML string in via formatter for cards. But maybe the logic that applies the tooltip can omit collecting text from certain elements? Like buttons and links for example. Not sure exactly.

**Comment by pwpatton** [comment]
I think a first cut would be just to enable tooltips per column. That way we can disable them for cardview columns. 

A future ask would be more control over what is display in an tooltip, for landmark that'd probably mean an async callback.

**Comment by tmcconechy** [comment]
A lot of this is a bit old so maybe needs some future restructuring but for now i would say maybe..

- beforeTooltipShow -> a hook where you can scrub content
- enableTooltips per column as well as per table

**Comment by tmcconechy** [comment]
One thought on this is the I noticed the callback does already work. For example https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-tooltips.html#L29

So you can attach a function to the column for the tooltip https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-tooltips.html#L34 and then do what you like for the column by returning the markup as you wish.

Will that satisfy this enough? Its already by column so i think we dont need to change anything.

**Comment by krishollenbeck** [comment]
@tmcconechy  Does that callback create the same tooltip for every cell in that column? Or is the tooltip unique per cell?

**Comment by tmcconechy** [comment]
The tooltip is unique per cell (providing you return something unique each time). It’s called for each and every time you hover a cell

**Comment by krishollenbeck** [comment]
@tmcconechy  I was able to get a unique tooltip with HTML for process indicator. I believe I can do the same thing for this one. I am going to close this and create an LMCLIENT ticket.

**Comment by krishollenbeck** [comment]
@tmcconechy Might potentially need another ticket though. To support tooltips on individual fields somehow? Like each specific field in the card? Not 100% sure what the plan is yet on that.

**Comment by tmcconechy** [comment]
ok yeah, maybe we can pass the targeted element on hover to the function and you can use that if needed. Make an issue as required
