### ISSUE TITLE
Header: Searchfield is also triggered when you open the Appmenu

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4617]
**Describe the bug**
when the Appmenu is triggered the search field also opens up

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/header/example-long-title-with-button.html
2. Click on the hamburger button
3. Notice that the search field expands
4. See error.

**Expected behavior**
![Large GIF (1128x526)](https://user-images.githubusercontent.com/56722184/99522881-3b04b500-29d1-11eb-88ed-bcd508ed9588.gif)

**Version**
- ids-enterprise: v4.35.0-dev

**Screenshots**
![Large GIF (1128x526)](https://user-images.githubusercontent.com/56722184/99523071-7a330600-29d1-11eb-9eda-8300b5bcf3d9.gif)

**Platform**
all major browsers

**Additional context**

**Comment by tmcconechy** [comment]
This must have started in 4.33 as it works in https://4320-enterprise.demo.design.infor.com/components/header/example-long-title-with-button.html

I think we should try and fix this asap

**Comment by jbrcna** [comment]
**QA Passed**
v4.35.0-dev
https://master-enterprise.demo.design.infor.com/components/header/example-long-title-with-button.html
notice that when you open that app menu the `Hamburger` icon turns to `X`. Is this working as expected?
![image](https://user-images.githubusercontent.com/56722184/100838622-bbd1af80-34ad-11eb-9640-2d1853c9a9f2.png)

**Comment by tmcconechy** [comment]
@EdwardCoyle I noticed that as well but i didnt say anything. You changed the icon right to a clone? Think that works just fine but just checking...

**Comment by EdwardCoyle** [comment]
@tmcconechy Yeah that was changed in a separate PR: #4646.  The (X) behavior is something that's been there but was no longer working

**Comment by tmcconechy** [comment]
Sure - i think it works better anyways. But as noted it is a change.

**Comment by jbrcna** [comment]
Thank you @tmcconechy and @EdwardCoyle  for clarifying.
