### ISSUE TITLE
ListView: Select on Focus not working correctly

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#4621]
If a ListView is set up with the selectOnFocus option set, the row is automatically selected which is correct, However, the first click on a different row has no effect. Second and subsequent clicks work okay and all is fine when using the keyboard.

**To Reproduce**

1. Set up a ListView with selectOnFocus option set.
1. Add 3 items to it the list.
1.  Show the listview 
<img width="113" alt="SessionScreen1png" src="https://user-images.githubusercontent.com/49482971/99668788-1575bb00-2a66-11eb-8d88-cf747dfd771b.png">
1. click once on a row other than the selected row -> Address row had been clicked once
<img width="97" alt="SessionScreen2" src="https://user-images.githubusercontent.com/49482971/99668901-3b9b5b00-2a66-11eb-8233-2d69f64aaa0f.png">
1. Click again on that row
<img width="96" alt="SessionScreen3" src="https://user-images.githubusercontent.com/49482971/99668933-4524c300-2a66-11eb-9dc2-fab348d1c4e7.png">
1. Row now selected okay.

**Expected behavior**
Should only need to click once to select a different row

**Version**
v4.31.2

**Platform**
 - Sunsystems
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - Windows 10
 - Chrome
 - Browser Version: 86.0.4240.198 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
So let me clarify these steps we are using `selectOnFocus: true`

1. Go to https://master-enterprise.demo.design.infor.com/components/listview/example-singleselect.html
2. Tab into the listview - item is selected on focus as expected
3. "Attempt" to click row 2 to select (this only works the first time)

**Comment by nbeare-infor** [comment]
My screenshots only have 2 items on them (first row is the heading), whereas my reproduce steps mention 3 items. sorry for the confusion. 

Re your clarification 
Agreed, except that its the opposite result to what you have said in step 3. i.e. click row 2 DOES NOT work first time but DOES work second and subsequent times.

**Comment by tmcconechy** [comment]
Fixed on this commit https://github.com/infor-design/enterprise/commit/ead1f86be60211ebf013d5d860f785203e0dca02

**Comment by janahintal** [comment]
QA Passed. Now working as expected. 
![image](https://user-images.githubusercontent.com/45757016/108057593-cd2e5f00-708d-11eb-9080-d76a713dfb3f.png)
