### ISSUE TITLE
Column Chart : Icon is cut off in Subtle mode

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4622]
**Describe the bug**
Column Chart : Icon is cut off in Subtle mode

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/completion-chart/example-colors.html?theme=soho&variant=light&colors=2578a9
2. Notice the Required icon is cut off

**Expected behavior**
Icons should not be cut off

**Version**
4.350 ids dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/99677073-454baf80-2ab4-11eb-8506-9ea94dacc89b.png)

**Platform**
All major browsers

**Additional context**
N/a

**Comment by tmcconechy** [comment]
descoping for now
