### ISSUE TITLE
Editor: Dirty indicator sticks around (won't reset) when a new line "<br>" is introduced to the editor

### ISSUE THREAD

**Issue by gilbugauisan** [infor-design/enterprise#4624]
**Describe the bug**
Dirty indicator sticks around (won't reset) when a new line "\<br\>" is introduced to the editor (after save)

**To Reproduce**
https://master-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking-reset.html
1. go in the editor and put cursor at the end and press enter a 3/4 times
2. click "reset dirty"
3. dirty indicator sticks around

**Expected behavior**
dirty indicator should reset even with new lines introduced in the editor (use case: after saving the form)

**Version**
- ids-enterprise: 4.35.0-dev (dev), 4.31.4 (prod)

**Screenshots**
N/A

**Platform**
 - Infor Application/Team Name: Infor GHR/FSM
 - Device: Web/PC
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 86.0.4240.198 (Official Build) (64-bit)

**Additional context**
The developer also observed that the dirty indicator is present on load when the content or payload of the editor has new lines "\<br\>" in it.

**Comment by pwpatton** [comment]
Related Landmark Jira ticket
https://jira.lawson.com/browse/LMCLIENT-31908 - 'Save' action not available on Description after more than two updates

**Comment by tmcconechy** [comment]
Please fix in 4.36 and I will patch in 4.35 once merged

**Comment by jbrcna** [comment]
**QA Passed**
this is now working as expected. thank you
v4.36.0-dev
https://master-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking-reset.html
