### ISSUE TITLE
Tabs Module: Toolbar with spillover '+' button is still enabled even after clicking disable all button

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4626]
**Describe the bug**
Tabs Module: Toolbar with spillover add button is still enabled even after clicking disable all button

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html
2. Click Disable All 
3. Click '+' button in the tab

**Expected behavior**
All buttons and tabs should be disabled

**Version**
4.350 ids dev 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/99763480-ecbcf680-2b35-11eb-8b0b-713ac5498995.png)

**Platform**
All major browsers and devices. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
We made the choice to keep the + enabled. So will close this for now
