### ISSUE TITLE
Tabs Module: Buttons are misaligned 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4627]
**Describe the bug**
Tabs Module: Buttons are misaligned 

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html
2. Minimize the screen to responsive view. 
3. Notice that the '+' and 'x' buttons are not aligned 
4. Also try in Vibrant mode

**Expected behavior**
Should be aligned properly. 
'+' - center 
'x' - left corner

**Version**
IDS 4.350 dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/99764989-23484080-2b39-11eb-8a0c-4b62f79d83b9.png)

**Platform**
 All major browser and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping for now
