### ISSUE TITLE
WC: Add menu ids-menu component

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4628]
**Describe the Enhancement/Task**
Add a new popupmenu replacement to the WC project. Perhaps `ids-menu` this roughly replaces popupmenu and all its features and settings.

**Expected behavior**
- roughly all these settings https://github.com/infor-design/enterprise/blob/master/src/components/popupmenu/popupmenu.js#L48 but see if there is any that can be simplified/not brought over
- show an example on a menu button and right click (trigger click and rightClick)
- invoke a menu manually
- css only menu
- tests / docs
- current uplift light styles

**Comment by EdwardCoyle** [comment]
For reference:  Following this guide for some good info on making the menu accessibility-friendly:  https://www.smashingmagazine.com/2017/11/building-accessible-menu-systems/
