### ISSUE TITLE
SOHO-2957: Datepicker - Setting Locale

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#463]
1. Setting the local with $('body').initialize('nl-NL'); works first time you select in the calendar. After that, its changing the locale back tio US.

2. Should be able to set a local with data-options (or settings)

3. Should be able to change the locale with Locale.set('nl-NL');

4. Should be able to change the locale with a change to data options or settings and the trigger updated.

**Comment by karinpb** [comment]
We have the requirement to separate the language and the location, for all controls. To get the formatting without having to load all the translations for example.

**Comment by tmcconechy** [comment]
This issue was fixed
