### ISSUE TITLE
Dropdown: Opens on mouse up (drag/highlight from other field and release the mouse click on dropdown)

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4638]
**Describe the bug**
The dropdown opens when you release the mouse up from dragging or highlighting any items in the view.

**To Reproduce**
Steps to reproduce the behavior (application implementation):
1. Go to https://master-enterprise.demo.design.infor.com/components/dropdown/example-no-search.html
2. highlight the label above the dropdown
3. release the mouse click inside the dropdown div

![dropdown opens on mouseup](https://user-images.githubusercontent.com/50192038/100043104-afaf7780-2e47-11eb-989e-d07bc9d95c96.gif)

**Expected behavior**
Dropdown should only open on click not from mouse up

**Version**
- ids-enterprise-ng 7.2.4

**Screenshots**

**Platform**
 - Infor Application/Team Name: M3 H5 UI Team
 - Device: N/A
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Browser Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
I think we can probably change from mouseup to click. However this seems pretty minor. In general we might be using mouseup in other places where click might be better.

Task Here: Try and see if everything works changing the mouseup handler to a click handler.

**Comment by jbrcna** [comment]
**QA Passed**
This is working as expected. just to calrify, is this also applicable when closing the list/dropdown menu?
v4.36.0-dev
https://master-enterprise.demo.design.infor.com/components/dropdown/example-no-search.html
https://master-enterprise.demo.design.infor.com/components/dropdown/example-index
