### ISSUE TITLE
Checkbox: Better support for automated testing

### ISSUE THREAD

**Issue by desireenacorda** [infor-design/enterprise#4639]
**Is your feature request related to a problem or use case? Please describe.**
Problem is stated on https://jira.infor.com/browse/M3UX2-4002 - Test Automation: Verifying Elements in Angular is longer than in H5 Classic

We're seeing significant longer response time on H5-Angular compared with H5-Classic when doing our automation scripts. The WebDriver takes longer time to verify elements in H5-Angular compared to H5-Classic. Please see details below:

**H5 Classic:** https://krypton.infor.com/management/ui/reports/test-plan-result.html?tp_id=551f6036-2a03-11eb-9e11-0aeb5f683fbc--job&resultid=e4faf54e-4940-45e9-b14e-055e6f559bba
_Execution Time:_ 46m
![image](https://user-images.githubusercontent.com/74954524/100064299-4c384080-2e6d-11eb-97c4-6778f0e8ab66.png)
_Green highlight:_ Took only 5 seconds to open the vertical menu panel
_Yellow highlight:_ Took only 20 seconds to navigate to IPW
 
**H5 Angular:** https://krypton.infor.com/management/ui/reports/test-plan-result.html?tp_id=57b9c579-2a1e-11eb-ae59-0ae8b8910824--job&resultid=e2f7eb8a-8ff2-4043-8363-6bdcd05324d4
_Execution Time:_ 1hr
![image](https://user-images.githubusercontent.com/74954524/100064682-cd8fd300-2e6d-11eb-863e-17aa13f2391a.png)
_Green highlight:_ Took 2 minutes and 36 seconds to open the vertical menu panel
_Yellow highlight:_ Took 3 minutes and 15 seconds to navigate to IPW

It was also observed in automation that checkbox interaction has become significantly slower in H5 Angular than in classic. We've noticed that checked class attribute from classic (see Screenshot 1. H5C Checkbox) was no longer applicable in H5 Angular (see Screenshot 2. H5A Checkbox). The use of such attribute value helps the WebDriver to quickly get the status of the checkbox in just a few seconds. However, without it, it would get the status from the properties which takes around 5 minutes for each checkbox. With this, if a test scenario involves, say, 10 checkboxes to create a data, it would take 50 minutes just to tick the checkboxes. 

**H5 Classic:**
![image](https://user-images.githubusercontent.com/74954524/100065409-b69db080-2e6e-11eb-91a6-1c69fccbf30b.png)

**H5 Angular:**
![image](https://user-images.githubusercontent.com/74954524/100065453-c4533600-2e6e-11eb-8a56-6eab4a244e19.png)

**Describe the solution you'd like**
The availability of various element attributes for automation helps to reduce the execution time of hundreds, if not thousands, of test executions just for data setup. What could have been the reason to omit this attribute value? Is it possible to re-introduce the use of status indicators especially for checkbox elements for automation tools to quickly determine whether the element is checked/active or not (e.g. <span class='checked'></span>)?

**Comment by tmcconechy** [comment]
It seems like the issue must be mainly the way you are scripting these. This isnt easy to change on our end right now. So i suggest you look at other ways of doing your scripts.

As of now we use css to style the checkbox and this is a common trick. We put the input in behind and add css to the adjacent label to show it on screen styles or else we cant change the checkbox look. 

![Screen Shot 2020-11-24 at 9 26 23 AM](https://user-images.githubusercontent.com/814283/100107022-37d95100-2e37-11eb-8c38-dde804181099.png)

You should try to target the input element and get the checked property to see if its checked and not try and rely on the label css in evaluating. Evaluating the attribute should be faster than a class or css evaluation.

We do have the ability to change this in a future (year + from now version) so will consider a different approach but for now i suggest looking at your scripts

**Comment by desireenacorda** [comment]
Hi @tmcconechy. That's what we are already doing on our current implementation. We are getting the 'checked' property to get the status of the checkbox and it takes 5 minutes just to verify if one checkbox is already checked on our execution.

**Comment by tmcconechy** [comment]
Hi. Ok, But then i cant see why the script should take 5 minutes. So i would guess the problem would be on the scripting side if it takes that long. Perhaps this issue should go with the team that made that script.

We cant reasonably change this implementation at the moment but we can consider a change for next years version. What exactly would make it "faster"? I still think this isnt a bug.

**Comment by jrubillar** [comment]
Hi Tim,

I tried to toggle the checkbox in the IDS samples but it seems that the "checked" attribute does not get updated.

In the screenshot below, I "unchecked" the checkbox labeled "Checked" but the attribute is still checked="true" in the DOM.

-Jack

![image](https://user-images.githubusercontent.com/75055810/100304427-b0781300-2fd9-11eb-9a40-a04c6edea873.png)

**Comment by tmcconechy** [comment]
I think that the check property is set on checkboxes “internally”. So if you query with scripts you will get access to it.  But you may not see it in the dom.

Is there some way to map the checkbox to that? These should be pretty close to standard checkboxes except the css

**Comment by tmcconechy** [comment]
We changed this implementation so that a class is exposed externally but this will only be available on 5.0 version sometime next year
