### ISSUE TITLE
SOHO-1564: Datagrid Frozen Columns

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#464]
The inforDataGrid allows you to specify a "frozenColumn" option, which causes some columns to become fixed so that when the grid is too wide to fit on the page, the scroll bar that appears only applies to the unfrozen columns.  Under the frozen columns, there is a scrollbar, but it is always disabled.
  It would be nice if there was some way to reduce the width of the region containing the frozen columns, and then using the scroll bar under the frozen columns to see them.

Landmark: Needs ability to freeze/lock the at least first column of a datagrid, which may be a possible workaround.

Sales Hub: Needs to freeze/lock the last column (which is an action button) that should always stay in view.

**Comment by brianjuan** [comment]
Noticed some issues that might be related to this enhancement.
**Issue 1: There is alignment issue on Button Column Header**
<img width="1671" alt="screen shot 2019-02-26 at 11 56 42 am" src="https://user-images.githubusercontent.com/39508864/53386994-aae23900-39bf-11e9-9017-033a510bd6da.png">

**Issue 2: Alignment issues occur on the Column Headers and rows after you scroll to the rightmost of the grid**
<img width="1214" alt="screen shot 2019-02-26 at 12 01 37 pm" src="https://user-images.githubusercontent.com/39508864/53387078-217f3680-39c0-11e9-9694-2e0cb99063fc.png">

**Issue 3: Sorting a column makes the page longer**
Steps:
1. Sort the Product Name column several times
2. Noticed that the page is now longer, vertical scrollbar will be displayed on the right of the page
![frozengrid1](https://user-images.githubusercontent.com/39508864/53387361-8ab37980-39c1-11e9-9951-bbd7f3473b9d.gif)

Please advise if we need to create separate tickets for these issues, thanks.

**Comment by tmcconechy** [comment]
@brianjuan I think these are worth looking at. Are these windows? I suggest making one ticket with all three points as they are somewhat related and I’ll investigate further.

**Comment by brianjuan** [comment]
@tmcconechy The first two issues on column alignment only happen on Mac Chrome, Issue 3 happens on all browsers both in Mac and Windows. I will just create a ticket for issue 1 and 2, and a separate ticket for issue 3. Thanks!

**Comment by brianjuan** [comment]
Moving to Done since issue 1 and 2 are intermittent, can't replicate it now. And we already have a separate ticket for issue 3.

**Comment by tmcconechy** [comment]
@Moonsez you can use the ms teams channel for questions. But this is shown in the example:
https://teams.microsoft.com/l/team/19%3a2b0c9ce520b0481a9ce115f0ca4a326f%40thread.skype/conversations?groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&tenantId=457d5685-0467-4d05-b23b-8f817adda47c

http://master-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html
Source: https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-frozen-columns.html

And if you dont need it frozen use the Button formatter: https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-form-buttons.html#L42

Also inforDataGrid is maybe the 3.x version? This version is no longer supported. But there is also a BUttonCellFormatter there see the example ⁨inforDataGrid⁩ / ButtonFormatter - DO NOT USE UNDER REVIEW.html

Frozen columns i dont think was supported on 3.x.
