### ISSUE TITLE
Homepage (Editable): Widget border color issue in uplift dark theme

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#4640]
**Describe the bug**
The border color for widgets on an editable homepage behaves different in uplift dark theme compared to other themes / colors. After hovering, the border does not change back correctly. Also, if items have been hovered and then edit mode is exited, the border is not reverted.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/homepage/example-editable.html?theme=uplift&variant=dark&colors=0066D4
2. Notice the correct border around the widgets
2. Hover a widget, see the blue border (correct, or should perhaps be white?)
3. Hover out of the widget, see the border become white (incorrect)
4. Click "Toggle Edit Mode" button to make the Homepage non-editable, see the white border remains (incorrect)

**Expected behavior**
The hover border color is removed when hovering out of the widget / exiting edit mode. 

**Version**
- ids-enterprise: v4.34.2

**Additional context**
Other variants in uplift + all variants in subtle theme seem to look fine. This isn't major, just looks a bit glitchy in dark theme

**Comment by jbrcna** [comment]
The issue is now resolved. Thank you
