### ISSUE TITLE
Icons: New SVG Icons for Mongoose / CSI

### ISSUE THREAD

**Issue by brianpettit** [infor-design/enterprise#4642]
With the design uplift, we have lost some icons in Mongoose

You have distribute horizontally on the icons page, but not distribute vertically.  Also, we need icons for "make same width", "same height" and "same size",  The old icons look like this:

![image](https://user-images.githubusercontent.com/74990136/100150187-46daf600-2e6d-11eb-9cf5-a7a499c7aa44.png)

So we need the following icons please

- [ ] distribute vertically
- [ ] make same width
- [ ] make same height
- [ ] make same size

**Comment by tmcconechy** [comment]
cc @inforandy - Do we have someone that can add new icons at this time or add this to the design backlog?

**Comment by brianpettit** [comment]
![image](https://user-images.githubusercontent.com/74990136/101095989-dd559880-358c-11eb-9af1-442f160b1c96.png)
We also have two other icons as seen above.   These are "arrange in a row" and "arrange in a column".

**Comment by katieinfor** [comment]
Created a ticket for this in Jira: https://jira.infor.com/browse/UXD-2369 Thanks!

**Comment by tmcconechy** [comment]
this are now available according to https://jira.infor.com/browse/UXD-2369
