### ISSUE TITLE
Locale: Incorrect Norwegian translation: "First page pagination tooltip is Først side, should be Første side"

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4643]
Incorrect Norwegian translation: "First page pagination tooltip is Først side, should be Første side"

Screenshot attached

![FirstPage](https://user-images.githubusercontent.com/66057969/100205604-3f632d80-2efd-11eb-98b0-156174c7e149.png)

**Comment by tmcconechy** [comment]
These are out for translation now if you can get someone to get in there and check / fix it?

**Comment by hwondergem** [comment]
OK, will be corrected in current translation cycle.

**Comment by jbrcna** [comment]
The issue is now resolved. Thank you
![image](https://user-images.githubusercontent.com/56722184/102201070-95c1fb80-3f00-11eb-8110-757d7e81e1f0.png)
