### ISSUE TITLE
Grouped column: Chart columns do not center properly in some cases (more obvious w/chart not in widget)

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#4645]
**Describe the bug**
Depending on the chart size and data the column charts at time have mis-aligned x axis labels. The problem is better experienced when the chart is not contained within a widget. Taking a single data item chart out of a widget also exaggerates the issue like for chart /components/column/test-custom-tooltips.html

**To Reproduce**
1. Use the chart examples chart /components/column-grouped/test-axis-y-format-integer.html
2. replace the data for the chart with the data listed below
3. Load the chart
4. You have to remove the chart from a widget as that seems to make things work better
5. Depend on window/screen size you might need to change size to see the issue.

**Expected behavior**
Label to be displayed the same way on each column. It appears they should be centered but that is not always the case

**Version**
Soho XI Controls v4.3.4

**Screenshots**

**Platform**
Version 87.0.4280.66 (Official Build) (64-bit)

**Additional context**
```
[
   {
      "data":[
         {
            "name":"Quantity",
            "value":10
         },
         {
            "name":"Future Orders",
            "value":12
         }
      ],
      "name":"Apples"
   },
   {
      "data":[
         {
            "name":"Quantity",
            "value":12
         },
         {
            "name":"Future Orders",
            "value":0
         }
      ],
      "name":"Snozberry"
   },
   {
      "data":[
         {
            "name":"Quantity",
            "value":11
         },
         {
            "name":"Future Orders",
            "value":8
         }
      ],
      "name":"Oranges"
   },
   {
      "data":[
         {
            "name":"Quantity",
            "value":8
         },
         {
            "name":"Future Orders",
            "value":7
         }
      ],
      "name":"Bananas"
   },
   {
      "data":[
         {
            "name":"Quantity",
            "value":11
         },
         {
            "name":"Future Orders",
            "value":18
         }
      ],
      "name":"Pears"
   },
   {
      "data":[
         {
            "name":"Quantity",
            "value":19
         },
         {
            "name":"Future Orders",
            "value":7
         }
      ],
      "name":"Grapes"
   },
   {
      "data":[
         {
            "name":"Quantity",
            "value":1
         },
         {
            "name":"Future Orders",
            "value":0
         }
      ],
      "name":"dfdfg"
   }
]
```

**Comment by krahs1** [comment]
![Screenshot 2020-11-25 11 21 46](https://user-images.githubusercontent.com/19823048/100262622-05e8ed00-2f12-11eb-8dd1-a9ab8c1cd89e.png)

**Comment by krahs1** [comment]
Tied to https://github.com/infor-design/enterprise/issues/4460

**Comment by tmcconechy** [comment]
@jmacaluso711 since you looked at this last time can you look again when you have the chance. I think we need a fix that either 

a) fixes the problem if the data has one element
b) of changes the data as it comes in before rendering like the single chart

It can be easier if the data changes that the groups go from n items to 1 so they cant just always reformat the data

**Comment by jbrcna** [comment]
**QA Passed**
v4.36.0-dev
https://master-enterprise.demo.design.infor.com/components/column-grouped/test-axis-y-format-integer-2-column.html
![image](https://user-images.githubusercontent.com/56722184/101761070-af390100-3b16-11eb-8cfb-c8bc39eb9b42.png)
other EPs were also tested
https://master-enterprise.demo.design.infor.com/components/column-grouped
