### ISSUE TITLE
Form: Lookup field required function is not working

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4647]
**Describe the bug**
Form: Lookup field required function is not working

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/form/example-compact-mode.html?theme=uplift&variant=light&colors=0066D4
2. Tab on all fields to show the required icon
3. Notice the the lookup required field doesn't work

**Expected behavior**
Lookup field should look required after tabbing on the field

**Version**
IDS dev 4.350

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/100425205-bcdb9900-30c9-11eb-970d-673522f77c57.png)

**Platform**
All major browser and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
I just removed the required form that example. Its not functional/important
