### ISSUE TITLE
Lookup: Overlapping modal issue

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4648]
**Describe the bug**
Lookup: Overlapping modal issue

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/lookup/example-minwidth.html
2. Click the Paging and Paging Small field very quickly 

**Expected behavior**
There should only be one modal opened. And 2 modal should not overlap.

**Version**
ids 4.350 dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/100428834-6d986700-30cf-11eb-92f5-d328468bb405.png)

**Platform**
All major Bowser and device. 

**Additional context**
N./a

**Comment by tmcconechy** [comment]
I'm not able to reproduce this. What are you clicking fast on exactly?

**Comment by tmcconechy** [comment]
Skipping this issue for now
