### ISSUE TITLE
Toolbar Searchfield: Calculation is broken when favorButtonset is set to false

### ISSUE THREAD

**Issue by kvaldillez** [infor-design/enterprise#4650]
**Describe the bug**
When using a toolbar searchfield that has the favorButtonset property set to false, it incorrectly calculates the buttonset width upon expanding the searchfield which then pushes the content outside of the container causing an unnecessary scroll.

**To Reproduce**
1. Go to the toolbar searchfield example in IDS here: https://design.infor.com/code/ids-enterprise/latest/demo/components/toolbarsearchfield/example-alternate-style?theme=uplift&variant=light
2. Change the favorButtonset property to false (currently defaults to true) either in the source code or via breakpoint.
3. Click into the searchfield and have it expand.
4. Observe searchfield now offscreen and a scroll is now present.

**Expected behavior**
Expanding the searchfield should not widen the toolbar and should behave similarly to when favorButtonset is set to true and the title length is not an issue or competing for space.

**Version**
- ids-enterprise: 4.31.5

**Screenshots**
See video screencast here: https://screencast-o-matic.com/u/6JnE/ids-toolbar-searchfield-issue

**Platform**
 - Infor Application/Team Name: Infor Nexus (Front-end Framework)
 - OS Version: macOS Catalina 10.15.6
 - Browser Name: Chrome
 - Browser Version: 86.0.4240.198

**Comment by tmcconechy** [comment]
To solve this issue i suggest moving to the toolbarFlex component. The toolbar component is deprecated in favor of this new one but it is an opt in situation. So we probably arent making any more changes to toolbar at this time

https://master-enterprise.demo.design.infor.com/components/toolbar-flex/list

It doesnt have or need this option and the search + buttons should work better and more efficient with this component.

**Comment by kvaldillez** [comment]
Thanks for the suggestion, since it is near the end of our QA cycle, we will likely implement a workaround until we can implement this new toolbar in a future development cycle.

**Comment by tmcconechy** [comment]
Sure or perhaps you can use it in one screen / case if it helps

**Comment by tmcconechy** [comment]
Descoping for now
