### ISSUE TITLE
Modal: Required icon is not working in modal form

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4651]
**Describe the bug**
Modal: Required icon is not working in modal form

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/modal/example-full-content.html
2. Open the Modal 
3. Tab on all fields inside the Modal form to show the required icon

**Expected behavior**
Required icon and fields should show

**Version**
IDS 4.350

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/100726324-c7669d00-33ff-11eb-93dd-ef5c43950dad.png)

**Platform**
All major browser and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This was a small demo app issue. Pushed a fix and removed the required indicators that were not functional as they arent needed here for this example.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. The mandatory fields are no longer mandatory.
