### ISSUE TITLE
Switch: is working when the disabled switch is ticked

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4652]
**Describe the bug**
Switch: is working when the disabled switch is ticked

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/switch/example-two-columns.html
2. Tick the disabled Switch "Require personal information to reset my password"
3. Notice that the above switch is being ticked. 

**Expected behavior**
Other switch should not work when disabled switch is ticked. 

**Version**
ids dev 4.350 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/100729063-44dfdc80-3403-11eb-8832-099951b4b05d.png)

**Platform**
All major browsers and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This was a small demo app issue. Pushed a fix and changed the ids (there was duplicates on the two).

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
