### ISSUE TITLE
Slider: NaN value is displayed in tooltip when you adjust the slider

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4653]
**Describe the bug**

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/slider/example-vertical.html
2. Click on and Play around with `Range` slider
3. Notice that it displays `NaN`

**Expected behavior**
![Large GIF (1128x524)](https://user-images.githubusercontent.com/56722184/100744946-867b8200-3419-11eb-89b3-41c75957ce28.gif)

**Version**
- ids-enterprise: v4.35.0-dev

**Screenshots**
![Large GIF (1128x524)](https://user-images.githubusercontent.com/56722184/100744742-3c929c00-3419-11eb-9c03-06606b750b3b.gif)

**Platform**
All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
This issue was a duplicate and solved on https://github.com/infor-design/enterprise/pull/5380
