### ISSUE TITLE
ListView: Context menu doesn't open on iphone11

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#4655]
**Describe the bug**
Long press doesn't open the context menu on list view.

**To Reproduce**
This can only be reproduced using browserstack or an actual IOS device.

1. Go to localhost:4000/components/listview/example-contextmenu.html
2. Long press on a list row
3. Context menu should open, context menu doesn't open.

**Expected behavior**
Context menu should open.

**Version**
4.36.0-dev

**Screenshots**
![list-view-context-menu-not-working-iphone11](https://user-images.githubusercontent.com/1056684/100924433-38609000-34a6-11eb-9b3b-732f1489fb5a.gif)

**Platform**
 - iPhone11
 - iOS, v13
 - Safari

**Comment by janahintal** [comment]
Passed - 
Tested in Browserstack
Working in iPhone 12 ios14
![image](https://user-images.githubusercontent.com/45757016/103207916-7385a000-493a-11eb-94c0-1b4c6b273e15.png)

Tested on real device & Browserstack:
Iphone 11 ios14
![image](https://user-images.githubusercontent.com/45757016/103211379-00ccf280-4943-11eb-824d-48e67a1698ec.png)


**Failing in:**
Browserstack iPhone 11 **ios 13**
![image](https://user-images.githubusercontent.com/45757016/103211441-2d810a00-4943-11eb-806f-30cea4a195a5.png)

**Comment by tmcconechy** [comment]
We partly fixed this issue by changing the selection. However. I think Browserstack is not working for this feature but real devices do. So not much we can do about that.

**Comment by CindyMercadoReyes** [comment]
This issue failed. I tested this issue on iPhone X and the menu does pop up when you do long press. However, The work "Task" gets highlighted at the same time every time you do a long press.  Please see screen shot attached.
![image](https://user-images.githubusercontent.com/39101346/103670085-219ad680-4f47-11eb-9c03-628b2cbd489a.png)

**Comment by tmcconechy** [comment]
@CindyMercadoReyes lets ignore this issue - we dont have any viable solution thats worth the time
