### ISSUE TITLE
Locale: A large negative number losing a digit

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#4656]
**Describe the bug**
A large negative number is losing a 0 digit when .formatNumber is called. This is causing the number -922,589,489,099.38 to become -92,258,948,999.38

**To Reproduce**
1. Unzip [test-format-big-negative.zip](https://github.com/infor-design/enterprise/files/5631703/test-format-big-negative.zip) into the codebase, then navigate to it.
2. Enter -922589489099.38 into the Numeric Input field
3. Click the Format button (this will call .formatNumber, and the formatted value to be put in the Formatted Value field.
4. See error, that the Formatted Value field's value is -92258948999.38

**Expected behavior**
We shouldn't lose a digit when formatting a negative big decimal.

**Version**

- ids-enterprise: v4.36.0-dev

**Screenshots**
![FormatNumberBigDecimalIssue](https://user-images.githubusercontent.com/22107636/100924261-fc2d2f80-34a5-11eb-9be8-fa69ffe0fb85.gif)

**Platform**
 - All

**Comment by jbrcna** [comment]
**QA Passed**
v4.37.0-dev
https://master-enterprise.demo.design.infor.com/components/locale/test-format-big-negative.html
