### ISSUE TITLE
File Upload Advance: uploads simultaneously on both fields

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4657]
**Describe the bug**
File Upload Advance: uploads simultaneously on both fields

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html
2. Drag a file on the first File Upload field
Notice the second fields got populated as well
Also noticed that the 'x' cancel button don't work on the first field. 

**Expected behavior**
1. First field should only be populated
2. Upload should be canceled after clicking 'x'

**Version**
4.350 ids dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/100989373-c2365900-358b-11eb-8b87-8bf0bcf68b3f.png)

**Platform**
All Major browser and devices

**Additional context**
N/a

**Comment by janahintal** [comment]
Hi @tmcconechy, I can't fully verify the fix as the page is only showing 1 file upload field instead of 2. 
https://master-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html

Now: Only 1 field is visible
![image](https://user-images.githubusercontent.com/45757016/101737949-7db53b00-3b00-11eb-8fc4-a2f0c677eb2c.png)

Before: There is 2 file upload field
![image](https://user-images.githubusercontent.com/45757016/101738123-ab9a7f80-3b00-11eb-8909-9d43592dfb02.png)

**Comment by tmcconechy** [comment]
@janahintal this is correct it should only be one on this page. It was a bug that it showed two and in doing so that caused the behavior as before since they were duplicated. So the fact it has one IS the fix

**Comment by CindyMercadoReyes** [comment]
This issue passed QA. This issue is now resolved.
