### ISSUE TITLE
Pressing tab to navigate away from a Dropdown causes its list to open

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#466]
**Describe the bug**
Trying to use the `Tab` or `Shift + Tab` keyboard commands when focused on a dropdown's pseudo element will unexpectedly cause its list of options to open.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/dropdown/example-index.html
2. Click on the Dropdown's label, or use the keyboard to focus the dropdown
3. Press the `Tab` key
4. after a brief delay, the list opens.

**Expected behavior**
The list shouldn't open, and the next or previous focusable element on the page should have focus.

**Screenshots**
<img width="605" alt="screen shot 2018-07-18 at 3 58 33 pm" src="https://user-images.githubusercontent.com/3249601/42904579-7a1c7ad6-8aa3-11e8-87fc-b62d13ca61c8.png">

**Additional context**
- Related to the dropdown changes in #267 
- as reported by @tmcconechy

**Comment by brianjuan** [comment]
Bug fix is working as expected across all browsers and passed QA testing.
Environment: http://490-beta0-sohoxi.demo.design.infor.com/components/dropdown/example-index
<img width="827" alt="screen shot 2018-07-19 at 3 48 49 pm" src="https://user-images.githubusercontent.com/39508864/42928943-4217e346-8b6b-11e8-9d94-133392c7c62e.png">
