### ISSUE TITLE
Date picker: is not updating in Sink Page in Windows Chrome Browser

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4664]
**Describe the bug**
Date picker: is not updating in Sink Page in Windows Chrome Browser

**To Reproduce**
1. Go to https://4350-rc0-enterprise.demo.design.infor.com/?theme=uplift&variant=light&colors=0066D4
2. Scroll down to Datepicker and Populate to Date today
3. Open the first Date Field 
4. Select January 2016
5. Click Apply
Notice that the field did not update and Still December, 2020

**Expected behavior**
Month should change to January 2016

**Version**
IDS RC0 4.350

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/101134492-69c39200-3645-11eb-97b7-9ad24aab2134.png)

**Platform**
Windows Chrome

**Additional context**
N/a

**Comment by tmcconechy** [comment]
I dont think i can reproduce anything wrong here. Just to clarify when you select Jan 2016 you open the picker and then hit apply?

But not that you need to hit apply twice. The first time you select the month and year and then that closes, then you pick the day and close it.

Are you seeing this?

**Comment by tmcconechy** [comment]
Skipping this issue for now
