### ISSUE TITLE
Datagrid: Icon gets blank in High Contrast mode when focused

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4665]
**Describe the bug**
Datagrid: Icon gets blank in High Contrast mode

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-alternate-row-shading.html?theme=soho&variant=contrast&colors=133c59
2. Hover and focus on each rows

**Expected behavior**
Icons should not look block or bank when focused

**Version**
4.350 rc0 ids

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/101331668-49970b80-38af-11eb-84a1-03a7de493f05.png)
![image](https://user-images.githubusercontent.com/45757016/101332171-e8236c80-38af-11eb-9bc4-774040daafa3.png)

**Platform**
All major browser and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping for now
