### ISSUE TITLE
Dropdown: Tooltip performance issue

### ISSUE THREAD

**Issue by pukhrajbal** [infor-design/enterprise#4672]
**Describe the bug**
It seems tooltips are causing a bottleneck to rendering the control when a large dataset is presented to it.
**Secondary issue**: Notice the long time it takes for the pop up to render when the control is clicked. 

**To Reproduce**
1. If you open attached index.html - you will notice it takes a long time to render the page
2. Removing `title` attribute from line 812 makes the page load immediately.
3. Open the list and see how long it takes

**Expected behavior**
Further speed improvement

**Version**
- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Platform**
 - Test in chrome

**Additional context**
[index.zip](https://github.com/infor-design/enterprise/files/5674874/index.zip)

**Comment by tmcconechy** [comment]
Yes, i see the issue. I think that the tooltip plugin is currently invoked for every item. Maybe we can change it to use delagates.

For opening the list it does need to append 8000 items which is a lot but we can look what further can be done. Previously it was decided working with teams on this that around 2000 is the most you would have in a dropdown to make it somewhat usable for the end user (even thats a lot to look at).

https://master-enterprise.demo.design.infor.com/components/dropdown/test-2000-items.html

**Comment by pukhrajbal** [comment]
Probably it should render a tooltip only when a single item is hovered - instead of prerendering tooltip for all items which might never be hovered over.

**Comment by tmcconechy** [comment]
Yeah ideally but its not simple since the title has to be removed or the browser tooltip will just show on hover.

**Comment by jbrcna** [comment]
**QA Passed**
loading/reloading the page is instant, it takes about 2000ms to open the list.
v4.36.0-dev
https://master-enterprise.demo.design.infor.com/components/dropdown/test-8000-items.html

**Comment by tmcconechy** [comment]
see also #4708
