### ISSUE TITLE
Datagrid: Not enough space in the bottom of the page to see the pager in mobile devices

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4675]
**Describe the bug**
Datagrid: Not enough space in the bottom of the page to see the pager in mobile devices

**To Reproduce**
1. Open mobile device iOS or Android and Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
2. Remove compact mode
Notice that there is not enough space at the bottom to see the entire paging button

**Expected behavior**
There should be enough space in the bottom

**Version**
IDS 4.360 dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/101878404-78242780-3bca-11eb-8535-90908c3e387a.png)
![image](https://user-images.githubusercontent.com/45757016/101878444-8c682480-3bca-11eb-9b9d-6955fa013dd6.png)

**Platform**
All major browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping this one for now
