### ISSUE TITLE
Datagrid: Apply filter is automatically occurring when the user enter a value into a lookup filter column and tabs out 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4678]
Describe the bug
Apply filter is automatically occurring when the user enters a value directly into a lookup filter field and tabs out.  The gridOption of filterWhenTyping is set to false. 

1. Using the attached test-lookup-automatically-filtering.html
2. Enter a value into the filter row of the Product Id column 
3. Hit the tab key
4. Method applyFilter() is called on a change

Expected behavior
Similar to other filter columns, applyFilter is not automatically invoked.

Version
v4.36.0-dev

Landmark will need this fixed in v4.35.x.

**Comment by claudenbach** [comment]
[Git-4678.zip](https://github.com/infor-design/enterprise/files/5680538/Git-4678.zip)

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/101932589-9ecd6880-3ba0-11eb-8a37-616490221ed2.png)

**Comment by tmcconechy** [comment]
Please fix in 4.36 and I will patch in 4.35 once merged (Tim 👍🏻 )

**Comment by tmcconechy** [comment]
Looks like the filterWhenTyping setting is not being applied for the lookup filter only

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.
