### ISSUE TITLE
Searchfield: Search bar is showing an extra outline when focused

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4682]
**Describe the bug**
For the component "Example Category Searchfield Go Button Home" under tab-module, when the searchfield is focused an outline of the searchfield wrapper is shown. It looks like the width of the searchfield itself might be getting shrunk and this leaves behind an extra outline of the size that the searchfield would have been. Note, in Portal this is also happening but more exaggerated. Please refer to the screenshots below for comparison.

**To Reproduce**
1. Go to 'Example Category Searchfield Go Button Home' component under tabs-module at https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html
2. Click on the searchfield
3. Notice that the outline to the left of the searchfield is visible. (It is most visible with a lighter theme color)

**Expected behavior**
When the page is loaded, I expected the search bar to be its full length so when it is focused, no extra outline would be shown.

**Version**
- ids-enterprise: 4.36.0-dev

**Screenshots**
![Controls Sample Search Bar](https://user-images.githubusercontent.com/76002134/102110466-cddf1680-3dfa-11eb-9202-07f8013b9398.PNG)
![Portal Search Bar](https://user-images.githubusercontent.com/76002134/102110492-d8011500-3dfa-11eb-8012-94c9eea332c3.PNG)

**Platform**
 - Infor Application/Team Name: Infor Portal
 - Device: (if applicable) N/A
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 87.0.4280.88 (official build) (64-bit)

**Additional context**
N/A

**Comment by janahintal** [comment]
QA Passed. 
Verified in https://master-enterprise.demo.design.infor.com//components/tabs-module/example-category-searchfield-go-button-home.html?theme=uplift&variant=light&colors=8D0B0E
![image](https://user-images.githubusercontent.com/45757016/104308563-d87cf080-550b-11eb-8949-f2e1295cc3ea.png)
