### ISSUE TITLE
Searchfield: Search bar is not focused when tabbing through the page

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4683]
**Describe the bug**
After loading the page, if the search bar is not manually focused by clicking first, when you tab through the page the search bar does not get focused.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html - 'Example Category Searchfield Go Button Home' under tabs-module 
2. Tab through the page to show each element getting focused.
3. Notice that the searchfield does not get focused. Focus goes from the category dropdown to the go button.

**Expected behavior**
When tabbing through the page, the searchfield would be in focus after pressing 'tab' on a category dropdown focus.

**Version**
- ids-enterprise: 4.36.0-dev

**Screenshots**
N/A

**Platform**
 - Infor Application/Team Name: Infor Portal
 - Device: (if applicable) N/A
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
Note that if you click on the search bar first and then tab through the page, the search bar is now included in being focused.

**Comment by tmcconechy** [comment]
Sorry the PR fixes #4693 and this was closed by mistake

**Comment by janahintal** [comment]
QA Passed. 
Verified in https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html
![Uploading image.png…]()
