### ISSUE TITLE
HomePages: Animation and refresh doesnt work the first time

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4686]
**Describe the bug**
We noticed the first time the animation doesnt work. 

**To Reproduce**
1. Go to https://stackblitz.com/edit/soho-homepage-remove-widget-bug
2. Click on open on full page
3. Click the button -> notice it doesnt animate the first time
4. Click again and its working as expected

**Expected behavior**
Expect this to work the same way the first time as the second time

**Version**
- ids-enterprise: [e.g. 4.35.1 / NG 8.2 ++]

**Platform**
 - Chrome

**Additional Context**
Fix with https://github.com/infor-design/enterprise/issues/4663

**Comment by tmcconechy** [comment]
see anything obvious / easy @deep7102

**Comment by deep7102** [comment]
Looks like timing issue there, soon it remove from the DOM.
```
removeWidget() {
  this.widgets.splice(0, 1);
  setTimeout(() => {
    this.sohoHomepage.refresh();
  }, 1);
}
```

**Comment by janahintal** [comment]
Hi @tmcconechy, upon testing in 
https://master-enterprise.demo.design.infor.com/components/homepage/test-add-remove-widget.html?theme=uplift&variant=light&colors=0066D4 the page still fails to load smoothly in Windows Chrome.

**Comment by tmcconechy** [comment]
@janahintal i dont see any issue? Can you elaborate?

**Comment by janahintal** [comment]
Working as expected. 
https://master-enterprise.demo.design.infor.com/components/homepage/test-add-remove-widget.html?theme=uplift&variant=contrast&colors=0066D4

Having trouble last time loading the page due to bad internet connection. :)
