### ISSUE TITLE
Modal: Drag a modal dialog so that it's position can be changed, dragging the header only

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#4687]
IDS: 4.34.2
Browser: all supported browsers (Windows/Apple OS)

In our application, we sometimes have single or multiple modal dialogs open, and we would like to allow the user to drag the top-most modal around so they can see the content beneath.

I can do this using the IDS Drag API using the following code after creating each modal dialog...

`

			var modal = $('#' + id).closest(".modal"); 
			modal.css("position", "absolute");
			modal.css("bottom", "auto");
			modal.drag({containment: 'parent'});

`
...where "id" is the element ID of the object we supply to the "content" option of the Modal API.

This works reasonably well except that the user can click anywhere in the dialog to drag it, which doesn't conform to common UI standards that users may be used to.

What I would like to do is limit the drag initialisation to just the modal header DIV (i.e. the user can only drag the entire modal dalog when they press the mouse down on the heading/title area).

Without re-writing the drag functionality, is there any way to do this using the existing Modal or Drag APIs?

**Comment by tmcconechy** [comment]
This dragging enhancment was previously rejected on https://github.com/infor-design/enterprise/issues/1140

- makes modals to complicated
- multiple modals is not accessible ect
- not mobile friendly

Has had enough requests we can reconsider i suppose
