### ISSUE TITLE
Arrange: Handles alignment in Uplift

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4690]
**Describe the bug**
 the handles icon is not properly centered. 

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/arrange/example-index.html?
2. Switch to Uplift
3. Scroll down to `Sortable List with Handles`
4. See error. Notice that the three dots were not properly centered

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/102348183-78faf600-3fdc-11eb-947e-c1b0efa51871.png)

**Version**
- ids-enterprise: 4.36.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/102348193-7d271380-3fdc-11eb-964f-808abe9192af.png)

**Platform**
All major browser

**Additional context**
this might be trivial and minor issue

**Comment by tmcconechy** [comment]
Yes trivial because this is just a subcomponent and not used exactly like that. Looks a little low in the real place its used however https://master-enterprise.demo.design.infor.com/components/swaplist/example-index.html?theme=uplift&variant=light&colors=0066D4

**Comment by tmcconechy** [comment]
Descoping this issue for now
