### ISSUE TITLE
DataGrid: It is possible to insert column between 2 not reorderable or inside frozen columns area

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#4691]
**Describe the bug**
It is possible to have 2 columns next to each other with property `reorderable: false` and insert `reorderable: true` in between. That way we are reordering not reorderable. Also it is possible to insert column from not frozen ones into frozen ones. When you are trying that you can observe strange behavior like in the attached video

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-frozen-columns-with-grouped-headers.html
2. try to play with column reordering

**Expected behavior**
I think the component should not allow me to move not frozen column between frozen ones (in the zipped video they have reorderable: false). I think to have for example checkbox and action button columns frozen, while the rest is customizable by the users is valid use case. The same behavior imo should be applied when you are not using frozen, but only reorderable and you try to move column in between two with reorderable false, because with current behavior you are actually reordering those with reorderable false.

**Screenshots**
![Peek 2020-12-16 17-06](https://user-images.githubusercontent.com/11279863/102374045-28c26a80-3fc1-11eb-94e4-e9239a96d58e.gif)

another mp4 video (zip - not supported to upload directly)
[frozen-columns-2020-12-16_16.15.35.zip](https://github.com/infor-design/enterprise/files/5703930/frozen-columns-2020-12-16_16.15.35.zip)

**Comment by tmcconechy** [comment]
Descoping some older issues. But will try and get this working in the new web component.
Also the Landmark team actually asked to be able to drag the columns over

**Comment by hohnzy** [comment]
Why are these closed as they are still valid? This way we are loosing track of it. Or when should I recreate the ticket??

**Comment by tmcconechy** [comment]
ok fine can keep it open however its not easily fixable anytime soon. I think in the new component we can make it work
