### ISSUE TITLE
Pager: attributes not being propagated to attach-to-body popup menus

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#4692]
**Describe the bug**
If not using attach-to-body the data automation attributes work fine on the page-size-chooser menu. If using attach-to-body they aren't being set on the popup menu.

**To Reproduce**
1. Go to http://localhost:4000/components/pager/example-standalone.html
2. Make sure `Attach Page Size Menu To Body` checkbox is checked
3. Open the page size chooser menu and inspect menu items.

**Expected behavior**
expected id=standalone-pager-pagesize-opt-X to be set on menu items.

**Version**
- ids-enterprise: 4.35.2

**Screenshots**
not attaching to body works fine
![image](https://user-images.githubusercontent.com/4737815/102530327-c0c65f80-4066-11eb-92c3-c9a2e69467a5.png)

Attach-to-body and ids for popup menu aren't being set.
![image](https://user-images.githubusercontent.com/4737815/102530645-e3f10f00-4066-11eb-9b83-2ad2c7a8b6c8.png)

**Platform**
 - Team Name: Landmark
 - Device: PC
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**

**Comment by jbrcna** [comment]
**QA Passed**
v4.36.0-dev
https://master-enterprise.demo.design.infor.com/components/pager/example-standalone.html
![image](https://user-images.githubusercontent.com/56722184/102977520-0d65db00-453e-11eb-8917-bc17ad595923.png)
