### ISSUE TITLE
Datagrid: Need to be notified when clearable filter icon is clicked

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4693]
Describe the bug
Not notified when the clearable filter icon is clicked.  Issue exists when the grid options has filterWhenTyping set to false.

1. Using 'test-lookup-filter.html'
2. Add the property of filterWhenTyping: false to the grid options
3. Go to 'test-lookup-filter.html'
4. Perform a lookup on the filter row for Product Id column
5. Select a value
6. Click on the clear icon on the filter row for Product Id column 

Landmark will need to notified to react to the filter value being cleared.

Version
Landmark is on v4.35.2

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/102542392-5cf86280-4077-11eb-99e1-a22c8b67d102.png)

**Comment by claudenbach** [comment]
Will need to event to be exposed for angular development.

**Comment by claudenbach** [comment]
Also noticed that the clear icon isn't visible until the user clicks into the filter cell even when a value has been selected when testing in Landmark using Angular.  Not seeing this issue in enterprise.

**Comment by tmcconechy** [comment]
I think what the fix will be is just making the filter fire like it does on enter when you press the X so it wont be a seperate event

**Comment by claudenbach** [comment]
We already have a function defined for the lookup click, so hookup a function for the clear click?

Here's how its currently coded...
```
      if (displayField.compactFormatByForm) {
        displayField.id = column.id;
        column.filterConditions = this.codeBlockFilterConditions;
        column.filterType = 'lookup';
        column.editorOptions = {
          editable: false,
          icon: 'icon-launch',
          clearable: true,
          click:    this.LMFilterClickFunction,
          clickArguments: {
            column: {
              displayField: displayField
            }
          }
        };
        return;
      }
```

**Comment by claudenbach** [comment]
Here's the visibility issue with the clear icon.  The clear icon isn't visible with a filter value until the user attempts to edit the value directly.  Attempting to rep in enterprise-ng.

![Visibility-Clear-Icon](https://user-images.githubusercontent.com/39804038/102545812-620be080-407c-11eb-8d85-93584fbeb48f.gif)

**Comment by tmcconechy** [comment]
How do you currentlly run the filter logic when selecting a lookup item? What i see is you have to select the item in the lookup and then go in the field and hit "enter" to get the filter events to fire.

In your screen shot you some how do that. I think the issue with the clear button must be somehow related to how you populate the lookup from the dialog.

I can fix it so that the clear button runs the filter events tho. But im not sure how the filter runs to test it....

**Comment by claudenbach** [comment]
Figured out the issue with the clear icon.  Last concern is when making the column width smaller, this is what I'm seeing...

![Clear-Icon](https://user-images.githubusercontent.com/39804038/102663228-fc842680-4145-11eb-8dfa-ddb8b4cc5a92.gif)

**Comment by tmcconechy** [comment]
OK maybe thats something for a future time? What i did here: https://master-enterprise.demo.design.infor.com/components/datagrid/test-lookup-filter.html was set a min width but yours is a LOT longer

**Comment by claudenbach** [comment]
When using setFilterConditions() to set filter values into the filter row, the clear icon is not shown as appropriate.  If a filter element is clearable, the clear icon should be shown when a value is entered via setFilterConditions().

**Comment by claudenbach** [comment]
Should a call to applyFilter() be performed after calling setFilterConditions() in order to refresh the clear icon?

**Comment by tmcconechy** [comment]
applyFilter calls setFilterConditions i think. So shouldnt need to call both?

**Comment by claudenbach** [comment]
Okay.  Let me know whenever a package is built with the changes.

**Comment by tmcconechy** [comment]
Ok, To be sure I did a test and in this example http://localhost:4000/components/datagrid/test-lookup-filter if you call setFilterConditions instead of applyFilter it in both cases will now refresh the x.

Building the package now

**Comment by claudenbach** [comment]
For the clearArguments, need to also pass the grid object as it's being done for clickArguments...

        if (lookupEl.length && typeof $().lookup === 'function') {
          if (col.editorOptions) {
            if (col.editorOptions.clickArguments) {
              col.editorOptions.clickArguments.grid = self;
            } else {
              col.editorOptions.clickArguments = {
                grid: self
              };
            }
            if (col.editorOptions.clearArguments) {
              col.editorOptions.clearArguments.grid = self;
            } else {
              col.editorOptions.clearArguments = {
                grid: self
              };
            }
          }

**Comment by jbrcna** [comment]
**QA Failed**
it works fine but in Safari there's a UI issue.
v4.36.0-dev
https://master-enterprise.demo.design.infor.com/components/datagrid/test-lookup-filter-click-clear
https://master-enterprise.demo.design.infor.com/components/datagrid/test-lookup-filter
![image](https://user-images.githubusercontent.com/56722184/102976912-3b96eb00-453d-11eb-87d1-70c34f7f387b.png)
`**Mac Safari**`

Also in mobile view
![image](https://user-images.githubusercontent.com/56722184/102979797-89aded80-4541-11eb-9335-b9926ce4441f.png)

**Comment by tmcconechy** [comment]
Added a pending fix for safari https://github.com/infor-design/enterprise/pull/4712 however we only support R-1 so not fixing for iphone 5/6

**Comment by jbrcna** [comment]
Hi @tmcconechy . does the fix also apply to [test-lookup-filter](https://master-enterprise.demo.design.infor.com/components/datagrid/test-lookup-filter)? . mobile view?
In Safari `Subtle` theme is fine but fails on `Vibrant` Theme. please see screenshot below
![image](https://user-images.githubusercontent.com/56722184/103188310-e115da00-4902-11eb-92e2-e608d18ae156.png)
https://master-enterprise.demo.design.infor.com/components/datagrid/test-lookup-filter-click-clear?theme=uplift&variant=light&colors=0066D4
_Mac/ Safari Vibrant Theme_

Also in mobile view
![image](https://user-images.githubusercontent.com/56722184/103189001-b11c0600-4905-11eb-8a40-3a87e0d9e0a3.png)
_Mac/ Safari Vibrant Theme mobile view_

kindly try other row heights
![image](https://user-images.githubusercontent.com/56722184/103189071-fc361900-4905-11eb-94ff-386f2b1da793.png)
https://master-enterprise.demo.design.infor.com/components/datagrid/test-lookup-filter-click-clear?theme=soho&variant=light&colors=2578a9
_Mac/ Safari Soho Theme mobile view Extra small Row height_

**Comment by tmcconechy** [comment]
@jbrcna i forgot to test uplift theme, so that required an additional fix. Which is pending now....

**Comment by jbrcna** [comment]
Thank you @tmcconechy
