### ISSUE TITLE
Tree: characters being stripped on addNode but not updateNode

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#4694]
**Describe the bug**
We're upgrading from 4.11. Customers are allowed to enter certain characters that end up in the tree, or is auto generated. An example would be the text `<online job>`. In the current controls, on an addNode, that is being stripped out and left blank. updateNode does still work though.

**To Reproduce**
Check out this gist: https://gist.github.com/awbuboltz/aac0971938b7082cc21ccc0420937e59

**Expected behavior**
Both addNode and updateNode should behave the same and should properly render the text passed, not strip it out

**Version**

- ids-enterprise: 4.35.x

**Platform**
 - Infor Application/Team Name: Lawson

**Comment by jbrcna** [comment]
**QA Passed**
v4.37.0-dev
https://master-enterprise.demo.design.infor.com/components/tree/test-escape-node.html
https://master-enterprise.demo.design.infor.com/components/tree/example-ajax.html
