### ISSUE TITLE
Datagrid: Overlapping icons 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4695]
**Describe the bug**
Datagrid: Overlapping icons 

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-lookup-click-function.html
2. Tab on the first row on Product Ids column to see icons
See required and lookup icons are overlapping. 

**Expected behavior**
Icons should not overlap. 

**Version**
4.360 ids dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/102583448-b1671500-413f-11eb-9f4e-b833a30c84c6.png)

**Platform**
All browser, OS and devices. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
@janahintal I don't quite understand the issue. I don't see anything wrong in the screen shot or on the page Can you clarify?

**Comment by ericangeles** [comment]
@tmcconechy I see what she implied here. The link is incorrect in the issue.

It should https://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-lookup-click-function.html

Then,
- Click on the first item in the Column Id to trigger the error icon
- Hover the error icon
- Error icon overlapped to the search list icon

<img width="549" alt="err-icon" src="https://user-images.githubusercontent.com/8839327/102795848-560b8000-43e8-11eb-8d63-d741f01100f0.png">

**Comment by janahintal** [comment]
Hi @tmcconechy & @ericangeles, yes correct I attached a wrong link. Should be https://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-lookup-click-function.html

1. Tab on the first row in Product Id column to see error. 
![image](https://user-images.githubusercontent.com/45757016/102860435-d5409880-4468-11eb-93b0-5c5140c9953b.png)

**Comment by tmcconechy** [comment]
Descoping this issue for now
