### ISSUE TITLE
Splitter: Search Field is not hidden by the split

### ISSUE THREAD

**Issue by Milan1983** [infor-design/enterprise#4696]
**Describe the bug**
When you split does not hidden search field . I am adding this markup to see the problem.

```
<div class="page-container two-column fixed splitter-container">
  <section class="main">
    <div class="content scrollable">
      <div class="field">
        <label for="searchfield">Search</label>
        <input id="searchfield" name="searchfield" class="searchfield autocomplete" data-options= '{"clearable": "true", "showAllResults": false, "source": "//latest-enterprise.demo.design.infor.com/api/states?term="}' placeholder="Type a search term"/>
      </div>
    </div>
  </section>
  <nav class="sidebar scrollable">
    <div class="content">
      <div id="splitter" class="splitter"></div>
    </div>
  </nav>
</div>
<script>
$('#splitter').splitter({
  attributes: [
    { name: 'id', value: 'splitter-id-1' },
    { name: 'data-automation-id', value: 'splitter-automation-id-1' }
  ]
});
</script>
```

**To Reproduce**
1. split to left
2. will see search icon

**Expected behavior**
Can not see search icon

**Version**
4.35.2

**Screenshots**

![image](https://user-images.githubusercontent.com/17885045/102627688-744f5280-4140-11eb-9b8c-8e7135661172.png)

**Platform**
 - Infor Application/Team Name: Subsystems
 - OS Version:  Windows 10 
 - Browser Name: Chrome
 - Browser Version:  87.0.4280.88 

Thank you Tim for sent me this markup

**Comment by tmcconechy** [comment]
From what i saw i think its because the splitter uses flex and so does the search field container. I think the workaround might be to contain the search field in something else that negates the css flex.

Do not what i see is that the searchfield "stops" the splitter from moving and then it has extra scrolling this size of the searchfield on the right of the splitter

**Comment by ericangeles** [comment]
@tmcconechy it looks like this issue has been fixed already?

https://main-enterprise.demo.design.infor.com/components/splitter/example-searchfield.html

**Comment by ericangeles** [comment]
@tmcconechy it looks like this issue has been resolved already.

https://main-enterprise.demo.design.infor.com/components/splitter/example-searchfield.html

**Comment by tmcconechy** [comment]
@ericangeles i pushed an example for this. But notice that you cant "push" the search field around. It just stops at the search field. I think maybe it should resize the search field

**Comment by nganotice** [comment]
Splitter isn't overlapping w/ the Search Field anymore. I just wanted to confirm if the Search Field wont go back to it's old state when the splitter is already on the leftmost part of the screen. 

![Video 18](https://user-images.githubusercontent.com/84306838/140436098-a717e3c3-9c89-42c5-bf60-d07554984346.gif)

If that's the responsiveness we're achieving, I'll move this ticket to Done. 

CC @yohannahbautista @ericangeles @tmcconechy 

Thanks!
