### ISSUE TITLE
css home page has a visual bug

### ISSUE THREAD

**Issue by swetteinfor** [infor-design/enterprise#470]
weird bug i came across. see image

seems like a jmac thing 

t.com/20357266/42913226-be1302dc-8ac1-11e8-83ec-7c0fdeabdd19.png)

**Comment by tmcconechy** [comment]
Is this an issue for the website ? If so should be logged here: https://github.com/infor-design/website
Also that image did not seem to attach correctly.

**Comment by tmcconechy** [comment]
@jmacaluso711 Does this make any sense to you?

**Comment by jmacaluso711** [comment]
@swetteinfor what is this in regards to?

**Comment by tmcconechy** [comment]
Couldnt reproduce this...
