### ISSUE TITLE
Colorpicker: Custom label selects a color even without selection

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4700]
**Describe the bug**
when you open the custom picker and just tab out it automatically selects a certain color. in this case 

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/colorpicker/example-custom-labels.html
2. Click on `Color Picker (custom label)` dropdown
3. Tab out or double click the page body to lose focus

**Expected behavior**
should not select a color. should remain default/ what is currently selected

**Version**
- ids-enterprise:v4.36.0-dev

**Screenshots**
![Large GIF (606x552)](https://user-images.githubusercontent.com/56722184/102764667-74f11e80-43b6-11eb-990b-0fedc3b52109.gif)

**Platform**
all major browsers

**Additional context**

**Comment by tmcconechy** [comment]
Descoping this one for now
