### ISSUE TITLE
Geo Charts: add ability for map overlay component

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#4701]
**Is your feature request related to a problem or use case? Please describe.**
No problem or use case at the moment.

**Describe the solution you'd like**
In Bubble chart to have the ability to change the white background to an image and use Axis as coordinates that don't start with 0.

**Describe alternatives you've considered**
An alternative is using Google [GeoCharts](https://developers.google.com/chart/interactive/docs/gallery/geochart#marker-geocharts)

**Additional context**
An ilustration:
![bubble-chart](https://user-images.githubusercontent.com/34129313/102783736-102cc880-43a4-11eb-9917-12cf16f006d6.png)

Thanks!

**Comment by tmcconechy** [comment]
https://leafletjs.com/ is another one here. If we add something i think it would be Geo based maybe not the bubble chart as that could be harder to map.

I think we had a very old design we never got to so taking a look.
