### ISSUE TITLE
Dropdown: Add virtual scrolling

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4708]
**Describe the bug**
Need to further speed up http://localhost:4000/components/dropdown/test-8000-items.html in particular opening and closing is too slow. Will make the following work

- virtual scroll from 5.0 (WC)
- opening/closing is fast
- rendering page is fast
- tooltips work
- filter style search works

**To Reproduce**
1. Go to http://localhost:4000/components/dropdown/test-8000-items.html
2. Click on dropdown to open

**Expected behavior**
Fast as possible. We think virtual scrolling will help

**Version**
- ids-enterprise: [e.g. v4.35

*Platform**
- CRM
- Chrome

**Comment by tmcconechy** [comment]
Marking as 4.37 for now as it is an enhancement -> will patch if necessary when complete

**Comment by jbrcna** [comment]
**QA Passed** with observation
v4.37.0-beta0
https://4370-beta0-enterprise.demo.design.infor.com/components/dropdown/example-virtual-scroll.html

**Chrome**
this is what a toast looks like in Mac/Chrome. I guess this might be some cache issue as this works fine using incognito mode
![image](https://user-images.githubusercontent.com/56722184/106569720-e0124100-656f-11eb-9321-e9f84e388be5.png)

**Safari**
the dropdown resizes when you search
![Large GIF (586x414)](https://user-images.githubusercontent.com/56722184/106570111-6af33b80-6570-11eb-8a50-053e52295733.gif)
