### ISSUE TITLE
EDITOR component should have configuration for Visual and HTML mode

### ISSUE THREAD

**Issue by allanalvarez** [infor-design/enterprise#471]
**Is your feature request related to a problem? Please describe.**
http://master-enterprise.demo.design.infor.com/components/editor/example-index.html
Currently editor default settings is in HTML mode.  We should have an options that will identify what is the default mode of the controls. Either (HTML mode or Visual mode)

**Describe the solution you'd like**
We should have a settings that would identify what would be the default mode of the editor.

**Comment by tmcconechy** [comment]
This setting would be rather simple, just add the option and then call 

```
api.toggleSource()
```

This can also be considered a solid workaround.
