### ISSUE TITLE
Tabs: If info icon is used rather than error icon , it then overlaps

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#4711]
**Describe the bug**
The test given for the bug #2695 was not valid as http://master-enterprise.demo.design.infor.com/components/tabs/test-modal-error.html should have been altered so that it had an info validation rule.

The difference is that when the rule runs it apply the is-info and not the is-error class on the tab. Another issue is that the inline message on the field does not display.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/tabs/test-modal-error.html'
2. Run the custom Rule code to add in info rule to the field
3. Enter the 'Test' value
4. See overlap

**Expected behavior**
The icons and message should display in the same way as an error

**Version**

- ids-enterprise: master

**Screenshots**
class on tab
![image](https://user-images.githubusercontent.com/39749678/102943546-51d68400-4508-11eb-85f8-6562c6ff6ad1.png)
overlap
![image](https://user-images.githubusercontent.com/39749678/102944733-8f88dc00-450b-11eb-8c44-fb3fa1ce95be.png)

**Platform**
 - Infor Application/Team Name: Pathway
 - OS Version: Windows 10
 - Browser Name: chrome

**Additional context**

Script to add custom rule
```
// Custom Rule
$.fn.validation.rules.customRule = {
	check: function (value, field) {
		var pass = false;
        if (value !== 'Test') {
			pass = true;
		}
        return pass;
    },
    message: 'Information message',
    type: 'info',
    id: 'customDynamicRule'
};

// Change the validation attribute on the field
$('#last-name').attr('data-validate', 'required customRule');
```

**Comment by marknolaninfor** [comment]
only the info icon was corrected, but there are other validation types, such as alert, success.

**Comment by tmcconechy** [comment]
@ericangeles can you add the other types please? Thanks!

**Comment by janahintal** [comment]
This issue is now resolved.  Thank you. 
![image](https://user-images.githubusercontent.com/45757016/105696391-36fb9300-5f3e-11eb-8f00-564a2960d171.png)
