### ISSUE TITLE
RTL:Wizard tick circle offset

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#4714]
**Describe the bug**
Hi, in Wizard component in RTL mode, the tick circle is off by a few pixels

**To Reproduce**
1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/wizard/example-index.html?locale=he-IL#](https://design.infor.com/code/ids-enterprise/latest/demo/components/wizard/example-index.html?locale=he-IL#)
2. See the circle

**Expected behavior**
As LTR.
When I change `html[dir='rtl'] .wizard-header .tick::before` value of `right: 7px;` to -3px it looks ok.

**Version**

- ids-enterprise:v4.35

**Screenshots**
![image](https://user-images.githubusercontent.com/34129313/103017980-1f9b4580-454d-11eb-8786-00408912518a.png)

After changing CSS property:
![image](https://user-images.githubusercontent.com/34129313/103018332-bd8f1000-454d-11eb-8c98-186fa4da9f83.png)
it looks OK:
![image](https://user-images.githubusercontent.com/34129313/103018187-7a34a180-454d-11eb-9198-4e6de5a8da70.png)

**Platform**
 - OS Version: Windows 10 
 - Browser Name: Chrome
 - Browser Version:  87.0.4280.88 (Official Build) (64-bit)]

**Additional context**
Thanks!

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
