### ISSUE TITLE
Input: Right-aligned lookup fields have cursor overlapping the icon

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4718]
**Describe the bug**
A right-aligned text field with a lookup icon has the cursor overlapped with the icon when selecting the field.

**To Reproduce**
1. Go to 'components--> input --> Test Short Fields Right Aligned '
2. Click on any field in the 'Lookup Field' section
4. See that the cursor overlaps with the lookup icon

**Expected behavior**
A right-aligned field with a lookup icon should not have the cursor overlapping with the icon when the field is selected.

**Version**
v4.36.0-dev

**Screenshots**
From the controls example page:
![Controls Sample Lookup Field](https://user-images.githubusercontent.com/76002134/103238464-7075ba00-4910-11eb-8985-aa91d350672c.PNG)

From the product with the updated controls:
![Lawson Lookup Field Example](https://user-images.githubusercontent.com/76002134/103238522-9dc26800-4910-11eb-90f8-767586c61a2e.PNG)

From the product without the updated controls:
![Working Example Lookup Field](https://user-images.githubusercontent.com/76002134/103238583-c9dde900-4910-11eb-9a67-ceeaaa2362c8.PNG)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by janahintal** [comment]
Issue still exist in Lookup field and Dropdown field. 

![image](https://user-images.githubusercontent.com/45757016/107611014-f5792080-6c7d-11eb-8689-74660318f01e.png)
![image](https://user-images.githubusercontent.com/45757016/107611108-33764480-6c7e-11eb-8df6-7ed0386fe335.png)

**Comment by ericangeles** [comment]
@tmcconechy looks like some of the CSS rules were not able to merge properly that's why it failed.

**Comment by tmcconechy** [comment]
Ok that could be my fault I had been testing your or and I had them on my branch I created and took them out. Can you just or them again? Sorry

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
