### ISSUE TITLE
Breadcrumb: Add/Update docs for truncation/JS component

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#4720]
**Describe the bug**
Our documentation still says that Breadcrumbs are entirely comprised of HTML/CSS only, which is no longer true as of v4.32.0.  The API details are present, but there are some conflicting notes. We need to update the docs here and remove any trace of:

> This component is entirely HTML and CSS, to update contents you will need to implement the logic to replace the link elements in the hierarchy.

**To Reproduce**
Take a look here: https://design.infor.com/code/ids-enterprise/latest/breadcrumb

**Expected behavior**
Correct the docs to account for the JS component.

**Version**
- ids-enterprise: v4.32.x+

**Additional context**
[Relevant MS Teams Convo](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1609867373396?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1609867373396&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=General&createdTime=1609867373396)

@PilotBob

**Comment by CindyMercadoReyes** [comment]
There is not way to test this bug in QA. Moving this ticket to Done column.
