### ISSUE TITLE
File upload: allow drag and drop file path from File explorer.

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#4723]
**Describe the bug**
Allow drag and drop a file path from File Explorer into the file upload value.

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/fileupload
2. Click on file upload folder icon
3. Drag a file into the file upload input 
4. File path is not pasted into the file upload value

**Expected behavior**
File path is pasted into the file upload value

**Version**

- ids-enterprise: 4.35

**Screenshots**
![image](https://user-images.githubusercontent.com/39130590/103793023-874f9700-5009-11eb-897c-918279f8e57a.png)

**Platform**
 - Infor Application/Team Name: Infor Landmark
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@vonnyw i noticed that in 3.x the drag and drop only works if you drag it on to the icon. I could make it work if you drag anywhere on the field but it will make it so you cant select the text anymore so thats rather clunky and will probably get complaints.

Think we should just let you drop on the icon only like before?

**Comment by vonnyw** [comment]
@tmcconechy We definitely want to still be able the select the text. I was able to drag it outside of the folder icon in 3.x

**Comment by tmcconechy** [comment]
In 3.5 you cant (maybe just a little buffer). But its only possible to drag to the icon, try dragging to the start of the field and it will just open the file. So i think this was accidentally a feature.

Not seeing a great way to do both unless we just let you drag on the icon again

**Comment by jbrcna** [comment]
**QA Passed**
v4.37.0-dev
https://master-enterprise.demo.design.infor.com/components/fileupload/example-index.html
