### ISSUE TITLE
Datagrid: filter cell border is not rendered when editable is false with a theme of subtle and variant of high contrast

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4724]
Describe the bug
No border is displayed for a filter cell that is rendered with editable false when using a theme of subtle with a variant of high contrast.

1. Go to test-lookup-filter.html
2. Change the theme to subtle
3. Change the variant to high contrast
4. Notice that the border for the Product Id filter cell is not displayed

Expected behavior
Border around the input element of the filter cell is visible

Version
- ids-enterprise: v4.37.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/39804038/103812270-e6baa080-5023-11eb-83f4-61cff15817a5.png)

**Comment by janahintal** [comment]
QA Passed. Verified in https://master-enterprise.demo.design.infor.com/components/datagrid/test-lookup-filter?theme=soho&variant=contrast&colors=133c59
![image](https://user-images.githubusercontent.com/45757016/105843347-890de880-6012-11eb-87fd-34ab9c6a79b9.png)
