### ISSUE TITLE
Process Indicator:  Labels overlap fields

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#4725]
**Describe the bug**
Process indicator overlaps fields when there are more fields placed below it. This appears to be caused by "details" element using absolute positioning.

**To Reproduce**
1. Edit example-labels.html in ids project. Add and extra field below
2. Go to http://localhost:4000/components/processindicator/example-labels.html
3. Notice process indicator overlaps field.

**Expected behavior**
Process indicator should not overlap other fields.

**Version**
4.37.0-dev

**Screenshots**
<img width="704" alt="overlapping" src="https://user-images.githubusercontent.com/1056684/103820796-91d25680-5032-11eb-9547-8432bb69bb6b.PNG">
<img width="425" alt="code-example" src="https://user-images.githubusercontent.com/1056684/103820800-93038380-5032-11eb-8993-db446ff3ca4a.PNG">

**Platform**
 - Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Do you really want this in 4.36 or is 4.37 ok?

**Comment by krishollenbeck** [comment]
@tmcconechy  I have some CSS overrides in place for Landmark at the moment. So I can get buy without it for now. @pwpatton  What do you think?

**Comment by jbrcna** [comment]
**QA Passed**
v4.37.0-dev
https://master-enterprise.demo.design.infor.com/components/processindicator/example-labels.html#
![image](https://user-images.githubusercontent.com/56722184/104315609-2eef2c80-5516-11eb-8aaf-a16308c44de3.png)
![image](https://user-images.githubusercontent.com/56722184/104315687-49c1a100-5516-11eb-98d2-7d9b6be6d8ac.png)
