### ISSUE TITLE
Editor: Add Clear Formatting Button to

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#473]
**Is your feature request related to a problem? Please describe.**

There currently is no easy way to reset all formatting in the editor component.

**Describe the solution you'd like**

Extending on https://jira.infor.com/browse/UXD-24 we will add a new button to the editor component. Which will add "Clear formatting" feature in the Editor, clearing all applied formatting (such as hyperlinks, font weight, italics, underline etc.).

**Describe alternatives you've considered**

You could manual edit the html in the html view. But this is a pain if a lot of formatting.

**Additional context**

Decide on icon 3 in the attached set [Archive.zip](https://github.com/infor-design/enterprise/files/2209917/Archive.zip)

See old issue for previous context https://jira.infor.com/browse/UXD-24

**Comment by brianjuan** [comment]
http://localhost:4000/components/editor/test-clear-formatting.html
Encountered an issue in **Windows Edge**, **IE** and **Firefox**, alignment is not clearing when done with Select All

Steps:
      1. Apply Right Align on the first paragraph
      2. Press Command+A or Ctrl+A to select all
      3. Click Clear Formatting icon, formatting will be cleared except for Right Align

**Comment by brianjuan** [comment]
Passed QA testing, fix is now working on all browsers.

**Comment by brianjuan** [comment]
Passed QA testing, fix is now working on all browsers.
