### ISSUE TITLE
Calendar: Add ability to drag across calendar dates to create a range 

### ISSUE THREAD

**Issue by jamie-norman** [infor-design/enterprise#4734]
**Is your feature request related to a problem or use case? Please describe.**
It would be a nice UX feature to allow a user to drag across, say, an entire week when making a time off request using the IDS calendar. Currently, user would click on a date (within the desired range) and have to enter a start and end date in the appropriate fields. Extra data entry. 

**Describe the solution you'd like**
Standard click and drag behavior

**Describe alternatives you've considered**

**Additional context**
The openCalendar that is used in HCM supports the drag behavior, so it could be considered a regression if the IDS calendar were implemented without that feature. Google Calendar also allows this in desktop.
![calendar drag](https://user-images.githubusercontent.com/44705854/104365088-2af2e880-54dd-11eb-9ed0-2fba06dfbdd2.gif)

**Comment by tmcconechy** [comment]
Descoping this one for now
