### ISSUE TITLE
App Menu: Searchfield issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4737]
**Describe the bug**
In example-personalized, the elements of the search field are overlapping

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized.html
2. Ensure that the App Menu is Open
3. See error
4. Notice that the search field elements in the upper left are over lapping

**Expected behavior**
should be placed properly

**Version**
- ids-enterprise: v4.34.0 - v4.37.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/104445758-763bf280-55d4-11eb-9539-327c25945ea6.png)

**Platform**
All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
If possible can you fix https://github.com/infor-design/enterprise/issues/4756 as well with this at the same time? Should be easy enough.

**Comment by jbrcna** [comment]
this issue is now resolved.
v4.37.0-dev
![image](https://user-images.githubusercontent.com/56722184/105838219-c66e7800-600a-11eb-9fab-bfe903efead2.png)
