### ISSUE TITLE
Dropdown stays in the page when closing CAP with keyboard

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#474]
**Describe the bug**

Dropdown is sticking around on closing CAP

**To Reproduce**
1. Go to and CAP page with a search field like:
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-trigger.html
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-centered.html
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-markup.html
http://490-beta0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-index.html
2. open cap
3. hit escape
4. See the dropdown stay at the bottom of the page.

**Expected behavior**
Dropdown should not focus and stay

**Platform**
All

**Additional context**
Similar to tab issue found two days ago.

**Comment by EdwardCoyle** [comment]
Just noting this is similar to the fix we made in #466, just need to manage the escape key

**Comment by brianjuan** [comment]
Bug is still encountered in Windows 10 IE 11
Steps to replicate:
1. Open IE 11 in Windows 10 (browserstack)
2. Go to http://490-rc0-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-index.html
3. Open the CAP
3. Type "Infor" in the Company Name dropdown, then click the Notes text area. Notice that the focus is still on the Company Name dropdown
4. Hit Escape key, CAP will close and a dropdown field will stick in the page
<img width="734" alt="screen shot 2018-07-31 at 7 05 03 pm" src="https://user-images.githubusercontent.com/39508864/43456284-743bed3e-94f5-11e8-852c-098a0c219277.png">

**Comment by tmcconechy** [comment]
Im not seeing this are you @EdwardCoyle ? One thing i do see is if i you hit ESC when on the dropdown it just goes into filter mode.

**Comment by brianjuan** [comment]
Passed QA testing on All Browsers.
Environment: http://490-rc1-sohoxi.demo.design.infor.com/components/contextualactionpanel/example-index.html
