### ISSUE TITLE
Dropdown/Multiselect: Automation attributes aren't being propagate to sub element in a dropdown

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#4742]
**Describe the bug**
- automation attributes `[{ name: 'id', value: 'my_dropdown_id }]' aren't being propagated to some sub elements
- no settings.attributes exists for the dropdown.js or multiselect.js component

**To Reproduce**

Steps to reproduce the behavior in multiselect.js
1. edit multiselect/example-search-under-selected.html
2. add to the options: attributes: [{ 'name': 'id', value: 'My_Dropdown1_Id' }]
3. run example and inspect dom to see elements with missing ids
> - dropdown                     
>    selector: select + div.dropdown-wrapper > div.dropdown
>    expected: id="My_Dropdown1_Id-dropdown"
> - dropdown list
>    selector:  #dropdown-list > ul
> - dropdown list search label
>    selector:  #dropdown-list > label
>     expected: id="My_Dropdown1_Id-search-label"
> - dropdown list search    
>    selector: #dropdown-list > input.dropdown-search
>    expected: id="My_Dropdown1_Id-dropdown-search"
> - dropdown list li anchor 
>    selector: #dropdown-list > ul > li.dropdown-option > a
>    expected: id="My_Dropdown1_Id-list-option-${index}"
4. For non search field under selected
> - trigger 
>    selector: #dropdown-list > span.trigger
>    expected: id="My_Dropdown1_Id-trigger"

Steps to reproduce the behavior in dropdown.js
1. edit dropdown/example-index.html
2. add to the data-options="{ attributes: [{ 'name': 'id', value: 'My_Dropdown1_Id' }] ") to the select element html
3. run example and inspect dom to see elements with missing ids
> - dropdown                     
>    selector: select + div.dropdown-wrapper > div.dropdown
>    expected: id="My_Dropdown1_Id-dropdown"
> - dropdown list search    
>    selector: #dropdown-list > input.dropdown-search
>    expected: id="My_Dropdown1_Id-dropdown-search"
> - dropdown list li anchor 
>    selector: #dropdown-list > ul > li.dropdown-option > a
>    expected: id="My_Dropdown1_Id-list-option-${index}"

**Version**

- ids-enterprise: 4.36.x

**Screenshots**

**Platform**
Windows 10
Latest Chrome Browser

**Additional context**

**Comment by tmcconechy** [comment]
See also https://github.com/infor-design/enterprise/issues/4741

**Comment by janahintal** [comment]
QA Passed. Verified in https://master-enterprise.demo.design.infor.com/components/dropdown/example-index.html?colors=0066D4. Working as expected will now move this ticket to Done.
