### ISSUE TITLE
Popover: Add automation identifiers to the popover close button and title

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#4743]
**Is your feature request related to a problem or use case? Please describe.**
Since all popovers uses the id="tooltip" and I guess that is reasonable I think it would be good to add an id to the Close button as well so that it's easier to find in automated testing. I also think it would be good to add an id to the title of the popover as well. Maybe it works without it, I am not sure, but if this is not too hard to implement I think it would be good.

**Describe the solution you'd like**
I would like the close button of a popover to have an id, for example id="tooltip-close" or tooltip-close-button or id="popover-close" or id="popover-close-button" and for the title id="popover-title" or id="tooltip-title"

**Describe alternatives you've considered**
-

**Additional context**
And what application do you work on? [e.g. {Infor XYZ}]3
![image](https://user-images.githubusercontent.com/8664975/104647687-8d511200-56b2-11eb-9f47-308f0cbaaed6.png)

**Comment by jbrcna** [comment]
**QA Passed**
v4.38.0-dev
https://master-enterprise.demo.design.infor.com/components/popover/example-index.html
![image](https://user-images.githubusercontent.com/56722184/107936362-85d89d80-6fbd-11eb-8d0a-eec7676561e6.png)
