### ISSUE TITLE
Button: Not enough color contrast between disabled and enabled 

### ISSUE THREAD

**Issue by kaeleding** [infor-design/enterprise#4744]
**Describe the bug**
Lawson team here, we're upgrading from 4.11 to 4.37.0-dev and I noticed that the button elements that have the disabled attribute which are children of an element that have the classes toolbar and standalone don't provide enough contrast to their text from enabled ones. Also happening to all theme variants except vibrant dark (provides enough contrast).

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/personalize/example-index?theme=uplift&variant=light

2. Edit the div with the classes "twelve columns" and add the classes toolbar and standalone. The div should now have the classes "twelve columns toolbar standalone".

3. Observe and compare the text color of the Date with the disabled attribute, with the one that doesn't.

**Expected behavior**
The disabled button should provide enough contrast to differentiate it from the enabled one.

**Version**
v4.37.0-dev

**Screenshots**
![theme_no_standalone_toolbar](https://user-images.githubusercontent.com/18295372/104700376-04d47f00-574f-11eb-85fe-cd4e0c3e159a.png)
![theme_with_standalone_toolbar](https://user-images.githubusercontent.com/18295372/104700381-0736d900-574f-11eb-8a55-ebdf09df502c.png)

**Platform**
- Infor Application/Team Name: lawson
- Device: (if applicable) N/A
- OS Version: Windows 10
- Browser Name: Chromium Edge
- Browser Version: Version 87.0.664.75 (Official build) (64-bit)

**Comment by kaeleding** [comment]
Hi @tmcconechy, would like to follow-up on the timeline of this. Thank you

**Comment by tmcconechy** [comment]
Is it urgent? Seemed minor so did not schedule it. I will put it in next sprint as it is a small fix. But note we are rather full with limited resources

**Comment by kaeleding** [comment]
It's not really urgent but we wanted our soho backlog tickets to be moving along since we're doing an incremental update and we would like to resolve those issues before doing so. Thanks for understanding and I apologize for the inconvenience.

**Comment by tmcconechy** [comment]
@kaeleding looking at this. Is it just the text part that isnt enough contrast and the icon is ok when its disabled? Or think we should lower the icon too?

**Comment by tmcconechy** [comment]
Added on https://github.com/infor-design/enterprise/commit/895c1935dd931cea196976c85b4aed1c35c3eed4 to master by mistake

Steps to test:

1) http://localhost:4000/components/toolbar/example-standalone-style.html (or master or beta branch when built)
2) cycle through the themes and the disabled button icons and text should have a difference to the toolbar

**Comment by janahintal** [comment]
Working as expected. 
![image](https://user-images.githubusercontent.com/45757016/106588310-96ccec00-6585-11eb-9719-49278e391b2d.png)
![image](https://user-images.githubusercontent.com/45757016/106588346-a2b8ae00-6585-11eb-9d0b-05f5dfc506a6.png)
![image](https://user-images.githubusercontent.com/45757016/106588369-ac421600-6585-11eb-9bee-29f1efb964c2.png)
![image](https://user-images.githubusercontent.com/45757016/106588411-b5cb7e00-6585-11eb-9248-007464459053.png)
![Uploading image.png…]()
