### ISSUE TITLE
Datagrid: Allow Shift + Click to select a range of rows from the selection checkboxes when selectable is 'mixed'

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4748]
Describe the bug:
Allow the Shift + Click behavior on the selection checkboxes to select a range of rows when the selectable mode is 'mixed'. Currently this behavior is only provided when a user performs a range selection from list cells other than the selection checkbox.

1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection.html
2. Click on selection checkbox on first row
3. With Shift + Click on the third row
4. Only the third row is selected
 
Expected behavior
Range of rows within the selection should be selected. Want the same behavior that currently already exists for range selection from when its not the selection checkbox.  So row selection events are emitted and a single row activation event is emitted for the last row within the selection.

Version
- ids-enterprise: v4.37.0-dev

**Comment by claudenbach** [comment]
![Git-4748](https://user-images.githubusercontent.com/39804038/104752047-c96c8d00-571b-11eb-927d-40d24c69412b.gif)

**Comment by janahintal** [comment]
QA Passed. Working as expected. 
![image](https://user-images.githubusercontent.com/45757016/107620138-33cb0b80-6c8f-11eb-9bb0-75de5275e0a0.png)
![image](https://user-images.githubusercontent.com/45757016/107620190-4a716280-6c8f-11eb-8a24-6318071898ff.png)
