### ISSUE TITLE
Dropdown: Options which has the same data-val but different name will make the other one unselectable

### ISSUE THREAD

**Issue by kaeleding** [infor-design/enterprise#4750]
**Describe the bug**
A very minor bug caught by the Lawson QA, basically there are options that have the same data-val value but with a different name, this makes the other option unselectable. 

**To Reproduce**
1. Create a dropdown which has the same data-val value (both have AL as the value). 
	Ex. 

		<li class="dropdown-option is-focused" data-val="AL" tabindex="0" role="option">
        <a id="custom-dropdown-id-1-option-0" href="#" role="option" data-automation-id="custom-automation-dropdown-id-option-0">Alabama</a></li>
        
        
    	<li class="dropdown-option is-selected" aria-selected="true" data-val="AL" tabindex="-1" role="option">
        <a id="custom-dropdown-id-1-option-1" href="#" role="option" data-automation-id="custom-automation-dropdown-id-option-1">Alaska</a></li>

2. Click the second option.
3. The dropdown value will not change to the option you selected.

**Expected behavior**
The dropdown value should change with the option selected.

**Version**
v4.37.0-dev

**Platform**
Infor Application/Team Name: lawson
Device: (if applicable) N/A
OS Version: Windows 10
Browser Name: Chromium Edge
Browser Version: Version 87.0.664.75 (Official build) (64-bit)

**Comment by tmcconechy** [comment]
I will log this as an accepted issue but we might not be able to fix it or will want to fix it. As far as i recall the code relies on the value to select the element so having duplicate values will cause this sort of issue. Workaround is make them unique.

**Comment by kaeleding** [comment]
Sure that sounds fine, no worries. We just have it on our backlog and we wanted our soho issues moving along since we're doing an incremental update. I'll be closing the ticket now. Thanks!
