### ISSUE TITLE
Tabs Module: Switching to Vibrant theme is not working in category searchfield

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4752]
**Describe the bug**
Tabs Module: Switching to Vibrant theme is not working in category searchfield

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html
2. Switch to Vibrant theme

**Expected behavior**
Notice that the theme didn't change

**Version**
4.370-dev

**Screenshots**
https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html

**Platform**
All browser, OS and devices. 

**Additional context**

**Comment by tmcconechy** [comment]
Descoping this one for now
