### ISSUE TITLE
Tabs Module: Overlapping close button in the search field 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4753]
**Describe the bug**
Tabs Module: Overlapping close button in the search field 

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html
2. Populate the search field 
3. Minimize the the screen 

**Expected behavior**
No overlapping buttons or icons

**Version**
4.370 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/105172105-0f7d8280-5b5a-11eb-96a2-c7e3ebe7df3f.png)
![image](https://user-images.githubusercontent.com/45757016/105172218-3b990380-5b5a-11eb-8901-16c286a40101.png)

**Platform**
All browser, OS and devices. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping for now
