### ISSUE TITLE
App Menu: Change icon when closed back to hamburger

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4756]
**Describe the bug**
Decided to revert the recent change that made the hamburger into an X on open back to a hamburger due to complaints by customers. I.E. its always a hamburger and doesnt morph into an x like previous versions

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized.html
2. Click on hamburger
4. See it morph to an x

**Expected behavior**
Works like https://4340-enterprise.demo.design.infor.com/components/applicationmenu where it is not an X when open.

**Version**
- ids-enterprise: [e.g. v4.36]

**Additional context**
Seems this can be fixed by not adding the close class to `class="icon app-header close"`

**Comment by tmcconechy** [comment]
We might patch this to 4.36 but keep it in master for now.

**Comment by jbrcna** [comment]
**QA Passed**
v4.3.7.0-dev
https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized.html
