### ISSUE TITLE
Dropdown: Typing an uppercase letter for a single-letter dropdown menu does not highlight the corresponding option

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4757]
**Describe the bug**
For a dropdown menu that has single-letter options, typing a lowercase letter will highlight the corresponding menu item but typing an uppercase letter will not.

**To Reproduce**
1. Go to 'Example No Search Lsf' under the dropdown component
2. Click on the 'No-Search Dropdown'
3. Type a lowercase 'm' and notice how it highlights the item 'M - Mantis'
4. Type an uppercase 'M' and notice that there is no menu item highlighted

**Expected behavior**
A dropdown item should be highlighted if a lowercase or uppercase letter corresponding to that item is typed in the dropdown field.

**Version**
- ids-enterprise: 4.37.0-dev

**Screenshots**
Example using a lowercase search:
![Lowercase Dropdown Search](https://user-images.githubusercontent.com/76002134/105222732-7ed68080-5b20-11eb-8557-80149cf5e1ec.PNG)

Example using an uppercase search:
![Uppercase Dropdown Search](https://user-images.githubusercontent.com/76002134/105222788-94e44100-5b20-11eb-8527-808d105e9023.PNG)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 87.0.4280.141 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Noticing this only happens when open.

**Comment by s-werking** [comment]
This issue seems to be fixed by another ticket. This can be closed now, thanks!

**Comment by tmcconechy** [comment]
Great thanks!
