### ISSUE TITLE
Spinbox: A stepped interval spinbox doesn't work properly for double digits

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4762]
**Describe the bug**
When using a stepped interval spinbox there are two issues that occur:
1. When using the spin up button until the value is in the double digits, if you click/tab off of the spinbox only the ten's digit is shown
2. When trying to type multiple digits in the spinbox, it only allows one digit to be entered

**To Reproduce**
1. Go to 'example-stepped-intervals' under the spinbox component at https://master-enterprise.demo.design.infor.com/components/spinbox/example-stepped-intervals.html
2. Click on the spin up button until the number is in the double digits
3. Click or tab out of the spinbox
4. Notice that only one digit remains in the spinbox
5. Try typing multiple digits into the spinbox
6. Notice that only one digit is allowed

**Expected behavior**
When clicking the spin up button on a stepped interval spinbox and clicking outside of the box, the value should be unchanged. When typing a value into a stepped interval spinbox, it should allow any number within the accepted range.

**Version**
- ids-enterprise: 4.37.0-dev

**Platform**
 - Infor Application/Team Name: lawson
 - Device: N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: Version 88.0.4324.96 (Official Build) (64-bit)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
