### ISSUE TITLE
Tabs Module: Cannot close tabs on iPad

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#4763]
**Describe the bug**
The X button to close module tabs does not work when using an iOS device (iPad/iPhone). There seems to be a problem with the tap/click getting registered on the X. When I test with an Android device, things work ok. The issue only seems to exist on iOS devices.

The X's on the tab overflow menu work ok. It's the normal X's on the tabs that don't work. If you zoom in very close, then sometimes a tap on the X will close the tab (but we can't expect users to do that).

**Note:** I tried simply increasing the size of the X's with a CSS hack, but that didn't help.

**To Reproduce**
1. Launch Safari or Chrome on an iPad or iPhone
2. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs-module/example-index
3. Click the X on a tab to close it
4. Observe that it does not close (occasionally it may close if you are lucky)

**Expected behavior**
The tabs should be easy to close the first time you tap the X button. Without being able to close module tabs, it makes our app very difficult to use on iPads.

**Version**
4.36.1 (and older)

**Platform**
 - Infor Application/Team Name: CSD
 - Device: iPad and iPhone 6s (both using iOS 14.3)
 - OS Version: iOS 14.3
 - Browser Name: Safari and Chrome
 - Browser Version: ?

**Comment by janahintal** [comment]
QA Passed. Issue is now resolved. 
Verified in https://master-enterprise.demo.design.infor.com/components/tabs/example-dismissible-tabs.html?theme=uplift&variant=light&colors=0066D4 & https://master-enterprise.demo.design.infor.com/components/tabs/example-dismissible-tabs.html?colors=0066D4
