### ISSUE TITLE
Typography: Add "Coordinating conjunctions (and, but, for, not, or, so,yet)" to "Title Case vs. Sentence Case" section 

### ISSUE THREAD

**Issue by clazarev** [infor-design/enterprise#4765]
I was looking for a rule in the subject and found out that the guide was missing important statement below for "string except for"

> Coordinating conjunctions (and, but, for, not, or, so,yet)

I think it is important to mention because most of the menus, buttons, and titles might include conjunctions quite often.

**Comment by tmcconechy** [comment]
@clazarev what would you propose we say about these? Open to suggestions as i see it while they may be used there isn't really too much special about them. However i dont see some of them being used much? Like "not, so, yet" especially for applications.

Perhaps and and or but thats really just using proper descriptions. So really not sure that there is too much to add.

**Comment by clazarev** [comment]
@tmcconechy so the conjunctions should not be capitalized, and I think  "coordinating conjunctions(and, or, nor, for)" should be clear for most of the cases. I noticed people forgetting about those and applied Title case so the result looked awkward in UI.

**Comment by tmcconechy** [comment]
Ah - i see what you mean now. How is this addition look: https://github.com/infor-design/enterprise/commit/fe05d168e3b6fd29f484175e4f934f6778a88b9f

**Comment by clazarev** [comment]
> Ah - i see what you mean now. How does this addition look: [fe05d16](https://github.com/infor-design/enterprise/commit/fe05d168e3b6fd29f484175e4f934f6778a88b9f)

Looks good!

**Comment by tmcconechy** [comment]
Lets go with that then 👍🏻
