### ISSUE TITLE
Datagrid: Dropdown filter remains open when focusing the input

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4766]
**Describe the bug**
Datagrid: Popdown filter is stuck opened after using.

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
2. Open the dropdown filter in Order Date 
3. Type anything inside the test field 
4. Switch to different Filter e.g Product Name

**Expected behavior**
Dropdown filter should close.

**Version**
4.370-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/105486253-2a323180-5ce9-11eb-80df-08c1edac9ad4.png)

**Platform**
All browser, OS and devices

**Additional context**
N/a

**Comment by janahintal** [comment]
The issue still exists. Issue is intermittent. 

Try to play with the filter and focus on any field after opening the filter to reproduce the issue. 
https://master-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
![image](https://user-images.githubusercontent.com/45757016/111425301-f0503b00-872d-11eb-94c6-dcb697844189.png)
![image](https://user-images.githubusercontent.com/45757016/111426186-3bb71900-872f-11eb-8abc-44aa1ffabcc8.png)

**Comment by tmcconechy** [comment]
@janahintal  im unabe to reproduce this. can you elaborate on the steps?

**Comment by janahintal** [comment]
> @janahintal im unabe to reproduce this. can you elaborate on the steps?

Hi Tim, I'm testing it in Windows Chrome & the issue is intermittent. 

Steps to reproduce: 
1. Click **order date input field** 
2. **Open** Order date filter
3. Change the focus to **price input field** very fast 
4. Repeat the steps 1-3 until reproduced

![image](https://user-images.githubusercontent.com/45757016/111473708-4a6cf280-8766-11eb-9655-64f9ad2a1d71.png)

**Comment by janahintal** [comment]
Hi @tmcconechy, the issue still exist in https://master-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html

Steps:
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html 
2. Open the 'Quantity' dropdown
3. Focus on other field

![image](https://user-images.githubusercontent.com/45757016/112451938-02b32000-8d91-11eb-8cdb-31b402145f5c.png)

**Comment by tmcconechy** [comment]
Lets try to test this again as im not seeing it. If the issue persists lets make a new one?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
