### ISSUE TITLE
Icon: Need circle x icons for process indicator an "approvers" rejected state

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#4770]
**Is your feature request related to a problem or use case? Please describe.**
Need circle x icons for process indicator an "approvers" rejected state

**Describe the solution you'd like**
red x equivalent to the check mark

![image](https://user-images.githubusercontent.com/4737815/105530615-a27b0180-5cad-11eb-8a0b-65610125a797.png)

![image](https://user-images.githubusercontent.com/4737815/105530685-b9b9ef00-5cad-11eb-9cbc-5a45e555a364.png)

**Comment by jamie-norman** [comment]
[Uploading sketch.zip…]()

**Comment by jbrcna** [comment]
**QA Passed**
v4.37.0-dev
just a minor observation. In Firefox responsive and mobile view
![image](https://user-images.githubusercontent.com/56722184/105837359-91adf100-6009-11eb-97d0-d490e603db9c.png)
