### ISSUE TITLE
Can no longer change the text of the Editor component via the html source

### ISSUE THREAD

**Issue by btburg** [infor-design/enterprise#478]
**Describe the bug**
Can no longer change the text of the Editor component via the html source. The html text is jumping back to the original html.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/editor/example-index?font=source-sans
2. Click on the html button
3. Try to change the html

This no longer works.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the "Done" folder

**Comment by tmcconechy** [comment]
This should have been closed
