### ISSUE TITLE
Calendar menuSelected setting is defined as the incorrect type

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#4781]
**Describe the bug**
The calendar has a setting called menuSelected that will call the defined function, but it is typed as a string meaning that it can not be used with the generated typing files.

**To Reproduce**
Install the "ids-enterprise-typings" npm package and use it as a type within typescript

**Expected behavior**
This should be defined as a Function

**Platform**
 - Infor Application/Team Name: Pathway

**Additional context**

 * @param {string} [settings.menuSelected=null] Callback for the  right click context menu

**Comment by tmcconechy** [comment]
Add on pending PR...

**Comment by tmcconechy** [comment]
Also fixed the comment types https://github.com/infor-design/enterprise/commit/74d3552e3883c25ef97d1393c6b1f84de4a1808f
