### ISSUE TITLE
Locale: Turkish has Incorrect "Starts with" translation

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4788]
Two options in drop-down menu have same translations meaning "Ends with". However the second marked one should be "Starts with"

Screenshot attached

![Turkish](https://user-images.githubusercontent.com/66057969/106256775-ffca0200-621b-11eb-8d20-22080e63b17a.png)

**Comment by tmcconechy** [comment]
OK the file is presently waiting for an update on smb://nlbavwmemoq2.infor.com/cc/FromDev/SohoUX/ from the translation team.

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
Corrected to: 
    StartsWith: { id: 'StartsWith', value: 'Şununla Başlar', comment: 'for condition filtering' },

in \\nlbavwmemoq2\cc\ToDev\SohoUX\tr-TR.js	45,806	02/09/2021 09:46

**Comment by janahintal** [comment]
QA Passed. Working as expected. 
![image](https://user-images.githubusercontent.com/45757016/107934527-24afca80-6fbb-11eb-8669-aaf8ace40a96.png)
