### ISSUE TITLE
Datagrid: Inconsistent selected data when in compact mode

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4789]
**Describe the bug**
Datagrid: Inconsistent selected data when in compact mode

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
2. Select the id 0
3. Tick the sort filter in id
4. Notice that other row is being selected

**Expected behavior**
Selected row should be consistent 

**Version**
4.370 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/106263247-180f4080-625f-11eb-89ca-68c70101c7cf.png)

**Platform**
 All major browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping this issue for now
