### ISSUE TITLE
Locale: Incorrect Greek translations for "[variable] records per page", "Clear Filter" and "Characters Left"

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4791]
1. For the Greek phrase "[number] records per page", the first letter of "records" needs to be lowercase. Please replace "Εγγραφές" with "εγγραφές

![Greek](https://user-images.githubusercontent.com/66057969/106299337-53a50d00-6255-11eb-961d-3492dfaf63cb.png)

2. Clear Filter translation needs to be amended

For consistency with memoQ (Clear Filter = Εκκαθάριση φίλτρου) and term consistency for "Clear", please update:
Απαλοιφή φίλτρου
with
Εκκαθάριση φίλτρου

![Greek2](https://user-images.githubusercontent.com/66057969/106299914-18570e00-6256-11eb-9b9a-ce3fd389149b.png)

3. Out-of-context translation of "Characters left" (left has been translated as in left/right, not as "remaining"). Please replace "Χαρακτήρες αριστερά [number]" with "[number] χαρακτήρας(ες) ακόμη

![Greek3](https://user-images.githubusercontent.com/66057969/106302540-6588af00-6259-11eb-9a7b-c671b4ed07cd.png)

**Comment by tmcconechy** [comment]
I think this needs to be replaced in the translation product so we dont keep getting the strings coming back. Im still not sure on what a good process is to make that happen.

**Comment by cpinatel7** [comment]
This needs to be assigned to Henry Wondergem. Thanks

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
These will be updated in the February translation update.

**Comment by hwondergem** [comment]
Corrected in 
\\nlbavwmemoq2\cc\ToDev\SohoUX\el-GR.js	52,763	02/11/2021 13:59

**Comment by janahintal** [comment]
QA Passed. Working as expected. Thanks!

![image](https://user-images.githubusercontent.com/45757016/107932499-9a666700-6fb8-11eb-90e1-683666c2b780.png)
![image](https://user-images.githubusercontent.com/45757016/107932608-b7029f00-6fb8-11eb-9bdd-7400fdebaf9b.png)
![image](https://user-images.githubusercontent.com/45757016/107932833-f630f000-6fb8-11eb-8f63-2c307b167fd0.png)
