### ISSUE TITLE
Timepicker - Translation -  Greek Language issue - Truncated AM/PM translation in Set Time control

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#4793]
**Describe the bug**
In Time picker when we set Greek language it not showing full test for AM/PM. It is showing only first letter. Please refer below screenshots. 

**To Reproduce**

1. Go to 'Enterprise-ng project - locale-initializer and set the language to "el-GR" '
2. Go to Time picker Example and click on "Standard Time (h:mm:ss a)" and set the AM/PM and apply.
3. Again click on that control and check the AM/PM values.
 

**Expected behavior**
It should show full test for AM/PM.
**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
If applicable, add screenshots to hel
![TP1](https://user-images.githubusercontent.com/42198413/106460024-b8ac6d00-64b8-11eb-8c6f-aa6ef4a5e1d1.jpg)
![TP2](https://user-images.githubusercontent.com/42198413/106460036-bcd88a80-64b8-11eb-8540-43ac7f4f8c90.jpg)

p explain your problem.

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
We would have to make the dropdown a bit wider on the dialogs

**Comment by cpinatel7** [comment]
It's for GRC. Issue raised by my Greek tester. Thanks

**Comment by tmcconechy** [comment]
Trying to reproduce this in the component https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=el-GR and im not sure that i can. I see enough room for the last column (last input)

**Comment by cpinatel7** [comment]
One character is missing by default. Example:

![Clarification](https://user-images.githubusercontent.com/66057969/107481608-c4fe8d00-6b7e-11eb-99ad-bd9b5c13ba08.png)

Thanks

**Comment by prasannapatil91infor** [comment]
Hello @tmcconechy ,
we are faceing one more issue related to this, We are trying to parse date as bellow, it is giving same result for AM and PM.
Soho.Locale.parseDate("25/2/2021 7:59 μ.μ.","d/M/yyyy h.mm. a");
Thu Feb 25 2021 07:59:00 GMT+0530 (India standerd Time)
Soho.Locale.parseDate("25/2/2021 7:59 π.μ.","d/M/yyyy h.mm. a");
Thu Feb 25 2021 07:59:00 GMT+0530 (India standerd Time)

Also we try as bellow but getting same result

Soho.Locale.parseDate("25/2/2021 7:59 π.μ.".replace('π.μ.', 'AM').replace('μ.μ.', 'PM'),"d/M/yyyy h:mm a");
Thu Feb 25 2021 07:59:00 GMT+0530 (India standerd Time)
Soho.Locale.parseDate("25/2/2021 7:59 μ.μ.".replace('π.μ.', 'AM').replace('μ.μ.', 'PM'),"d/M/yyyy h:mm a");
Thu Feb 25 2021 07:59:00 GMT+0530 (India standerd Time)

we are expecting result as bellow for PM
Soho.Locale.parseDate("25/2/2021 7:59 π.μ.","d/M/yyyy h.mm. a");
Thu Feb 25 2021 19:59:00 GMT-0500 (Eastern Standard Time)

could you resolved this issue with this ticket or should we create new ticket for this issue ?

**Comment by tmcconechy** [comment]
yes i think we can do it with this.
