### ISSUE TITLE
Homepage: Resize / reorder events send faulty information for Editable Homepage (Regression)

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#4798]
**Describe the bug**
When resizing/reordering widgets in an editable Homepage, the events that fire do not send correct metadata. The events are sending the size / position the widget had _before_ the event, not the resulting size / position.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/homepage/example-editable.html
2. Open Dev console
3. Move Widget A (top left) to position of Widget B (top right)
4. Inspect the event metadata being sent in the reorder event

**Expected behavior**
Widget A should be at index 1 in metadata blocks array. Its x value should be 2.

**Actual behavior**
Widget A is at index 0 in metadata blocks array. Its x value is 0.

See similar fault in the metadata blocks when resizing a widget.

**Version**
- ids-enterprise: latest / 4.36.1

**Screenshots**
![image](https://user-images.githubusercontent.com/1101770/106625187-bad50100-6576-11eb-9741-ce4e49e231a7.png)

**Additional context**
Works fine on 4.35.0, https://design.infor.com/code/ids-enterprise/4.35.0/demo/components/homepage/example-editable.html
![image](https://user-images.githubusercontent.com/1101770/106625330-dcce8380-6576-11eb-9642-d5864dceb5c8.png)

**Comment by tmcconechy** [comment]
@deep7102 can you take a look at this (on master) if needed i can patch to 4.36 - assume its due to some recent changes.

**Comment by volante007** [comment]
I'm pretty sure it's due to this change
https://github.com/infor-design/enterprise/commit/761f3c02a8a03677918e96faa5493212f392d894#diff-0a05b3a653c698030f13b241516312e126a853dd3e8f6fab78ee26aa6dd4dc41R771
Adding a timeout in refresh()

refresh() is called before dispatching the resize/reorder events. Due to the timeout, the blocks are out of date (they are updated in refresh())

**Comment by jbrcna** [comment]
The issue is now resolved.
v4.37.0-rc0
https://4370-rc0-enterprise.demo.design.infor.com/components/homepage/example-editable.html
![image](https://user-images.githubusercontent.com/56722184/106856545-95bccb80-66f9-11eb-8395-77fc69f78a70.png)

**Comment by jbrcna** [comment]
QA Passed
v4.52.0-dev
https://main-enterprise.demo.design.infor.com/components/homepage/example-editable.html
![image](https://user-images.githubusercontent.com/56722184/119146468-3baffe00-ba7d-11eb-9d41-70f86706947d.png)
