### ISSUE TITLE
Typography: Add Meiryo font to Japanese font family

### ISSUE THREAD

**Issue by PaulEvansInfor** [infor-design/enterprise#4801]
**Is your feature request related to a problem or use case? Please describe.**
We recently had a suggestion raised by a Japanese customer of ours to improve the font that our application is rendered with.  I think the current font in use (by IDS) is MS PGothic which doesn't scale so well as it is rendered from bitmaps.  The customer have suggested we switch to using the "Meiryo" font which is a lot smoother and scales nicely to different sizes.

**Describe the solution you'd like**
Add Meiryo as the first font in the Japanese font family in relevant stylesheets.

**Describe alternatives you've considered**
We can override the font-family with a local stylesheet for now, but it would be nice to include this as standard in the IDS components.

**Additional context**
I've attached a couple of screenshots showing what the application looks like with PS M Gothic and Meiryo fonts.  To test with the Meiryo font on an English version of windows you will need to install the Japanese language pack.  I'm not sure what you would need to do for Macs etc.

MS PGothic
![scp-psgothic](https://user-images.githubusercontent.com/69893048/106725340-2bc0fb00-6601-11eb-99c5-7b33bfe8d304.PNG)

Meiryo
![scp-meiryo](https://user-images.githubusercontent.com/69893048/106725379-38ddea00-6601-11eb-88c8-ea30eff95bb7.PNG)

**Comment by tmcconechy** [comment]
@PaulEvansInfor We had selected https://fonts.google.com/specimen/Noto+Sans+JP?preview.text_type=custom in the new theme (Uplift/Vibrant/New). So thats already in place:

https://github.com/infor-design/enterprise/blob/master/src/components/typography/_typography-uplift.scss#L11

We had decided to leave the old theme as is. But i suppose we could change to the same.

It looks like Meiryo is a pay as you can font https://www.fonts.com/font/microsoft-corporation/meiryo/licenses so i think thats probably a non starter. 

Could you :
- Check if they are ok with Noto Sans JP? Or any open source alternative
- Should we change the "old" theme too or will you adopt the new theme?

**Comment by PaulEvansInfor** [comment]
Thanks for looking into that Tim.  I think the Noto Sans JP would be acceptable, I think the customer would prefer to have something that renders better than MS PGothic.

Regarding the part where you say Meiryo is a paid for font.  The font is included as part of the Windows platform and should be free to use.  I think fonts.com may supply those fonts on a paid for basis, but the one included in Windows should be free.  For reference here are the pages I checked on the Microsoft site.
https://docs.microsoft.com/en-us/typography/font-list/meiryo#licensing-and-redistribution-info
https://docs.microsoft.com/en-us/typography/fonts/font-faq (Check the web section) I think as we use font-family as a hint it would be okay to include it.
https://docs.microsoft.com/en-us/typography/fonts/font-faq

We don't need anything backporting to old themes as we will provide an override in our own stylesheets until any changes are made.

Our application is Supply Chain Planning.

**Comment by tmcconechy** [comment]
I was concerned about the "WEB FONT LICENSE" section as with cloud i guess we'd be there. And im not sure that its on Mac or Linux (there are increasing numbers of users there).

Ok, Lets go with Noto Sans JP for the new theme and leave the old theme. one reason we picked it is to be close to Source Sans the normal font in that theme (without Language support).

 If you agree i guess nothing to do here?

**Comment by PaulEvansInfor** [comment]
Yes, I guess it is preferable to go open source for font used in the IDS components.  We can always override locally for our customer, so it is not such a big issue.

I guess we can close the issue.

Thanks for you help/advice.

**Comment by tmcconechy** [comment]
Sure ! Another thing that is kind of a flag is its not available on directly on
https://fonts.google.com/?preview.text_type=custom&query=Meiryo
