### ISSUE TITLE
Datagrid: TargetedAchievement percentage value is showing x.000001% or x.999999%

### ISSUE THREAD

**Issue by rdugenia** [infor-design/enterprise#4802]
**Describe the bug**
Datagrid: TargetedAchievement percentage value is showing x.000001% or x.999999%

**To Reproduce**

Unable to provide a direct link but used this a reference and changed the values
https://master-enterprise.demo.design.infor.com/components/datagrid/test-targeted-achievement.html

**Expected behavior**
Percentage value should be an integer or up to 2 decimal places.

**Version**

- ids-enterprise: v4.36.0

**Screenshots**
![image](https://user-images.githubusercontent.com/78482539/106748481-3f4f7e80-6660-11eb-9da2-f55f37f1c37a.png)

**Platform**
 - Browser Name: Chrome, Edge
 - Browser Version: Chrome 88.0.4324.104, Edge 88.0.705.56

**Comment by janahintal** [comment]
QA Passed. 
Verified in https://4370-rc0-enterprise.demo.design.infor.com/components/datagrid/test-targeted-achievement.html?theme=uplift&variant=dark&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/106870112-b3932c00-670b-11eb-8b67-2499ef6d9f5f.png)
