### ISSUE TITLE
Translation: Incorrect Estonian translation for XX Results

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#4805]
Incorrect Estonian translation for XX Results

![Results](https://user-images.githubusercontent.com/66057969/106778462-49fd1a00-6646-11eb-8f50-102048709699.png)

(Translation owner: Henry Wondergem)

**Comment by tmcconechy** [comment]
cc @henrywondergem

**Comment by hwondergem** [comment]
Corrected to the following,
Results: { id: 'Results', value: '({0} tulemust)', comment: 'As in showing N Results (plural) in a List' },
    in \\nlbavwmemoq2\cc\ToDev\SohoUX\et-EE.js	45,306	02/09/2021 09:46

**Comment by janahintal** [comment]
QA Passed. Working as expected. 
![image](https://user-images.githubusercontent.com/45757016/107939834-43658f80-6fc2-11eb-85e8-b15d80ec51c5.png)
