### ISSUE TITLE
Datagrid: Setting the numberFormat for group and decimal

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4806]
**Describe the bug**

If a developer sets the group and decimal for a Decimal formatter/editor that is different then the current format. This will cause issues causing the decimal and group to alter the number.

**To Reproduce**
1. Go to datagrid/test-custom-number-formats.html
2. Add a column like
```
columns.push({ id: 'quantity', name: 'Change Group', field: 'quantityStr', formatter: Formatters.Decimal, numberFormat: { decimal: ',', group: '.'}, mask: '#.###,00' , editor: Editors.Input});
```
3. See that the formatter is right when you run it
4. Click in the cell and then click out -> notice the number is changing

**Expected behavior**
Should be able to set the number to decimal or groupas it can be done via an app setting and out of the current locale

**Version**
- ids-enterprise: [e.g. v4.36]

**Platform**
 - Infor Application/Team Name: M3
 - Browser Name:  Chrome

**Additional context**
Ms Teams

**Comment by janahintal** [comment]
This issue is now resolved. 
Verified in:
https://4370-rc0-enterprise.demo.design.infor.com/components/datagrid/test-custom-number-formats.html?theme=uplift&variant=light&colors=0066D4
