### ISSUE TITLE
Checkboxes: When placed in tables that have a relative position checking first box effects the last

### ISSUE THREAD

**Issue by 100Jason** [infor-design/enterprise#4808]
**Describe the bug**
Checkboxes inside of a table inside of a div with a style position:relative (such as class="field") prevents clicking on the top checkbox (the box, not the label).

**To Reproduce**

1. Go to https://stackblitz.com/edit/ids-enterprise-jkmtk6?file=index.js
2. Click on the box (not the label) for the First checkbox
3. It will check the Third checkbox.

**Expected behavior**
I expect it to check the first checkbox.

**Version**

- ids-enterprise: 4.35.4 to latest

**Screenshots**
N/A

**Platform**
 - Infor Application/Team Name: Infor Property Management
 - Device: (N/A)
 - OS Version: Windows 10
 - Browser Name: Chrome, Edge
 - Browser Version: Version 88.0.4324.104 (Official Build) (64-bit)

**Additional context**
We use the checkboxes inside of a table for marking multiple rows within the table.

**Comment by tmcconechy** [comment]
Caused by https://github.com/infor-design/enterprise/pull/3764

**Comment by jbrcna** [comment]
**QA Passed**
v4.37.0-rc0
https://4370-rc0-enterprise.demo.design.infor.com/components/checkboxes/test-tables.html
https://4370-rc0-enterprise.demo.design.infor.com/components/checkboxes/example-index.html
was able to scroll into view but there's no blurred blue border.
