### ISSUE TITLE
Modal: Inconsistent modal placement upon using key up & down with the dropdown field. 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4812]
**Describe the bug**
Modal: Inconsistent modal placement upon using key up & down with the dropdown field. 

**To Reproduce**

1. Go to  https://4370-rc0-enterprise.demo.design.infor.com/?theme=soho&variant=contrast&colors=133c59
2. Go to Modal section
3. Click show modal
4. Tab to focus in the Location dropdown field
5. Use key up and down to select in the dropdown

**Expected behavior**
Modal position should be fixed and won't move as I click the key up & down to select in the dropdown field. 

**Version**
IDS 4.370 RC0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/107005027-18ad5700-67ca-11eb-9f84-9c9139eb814b.png)

**Platform**
All major browsers. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
@janahintal Im not seeing the issue when following your steps but am wondering if this was caused be a recent change. Is there anything you can add to reproduce?

**Comment by tmcconechy** [comment]
Descoping for now
