### ISSUE TITLE
Timepicker: Intermittent issue. Misaligned popup in timepicker field

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4813]
**Describe the bug**
Timepicker: Intermittent issue on popup in timepicker field

**To Reproduce**

1. Go to https://4370-rc0-enterprise.demo.design.infor.com/?theme=uplift&variant=contrast&colors=003876
2. Go to timepicker section
3. Play with the timepicker field open and close the popup, scroll up & down until the error shows. 

**Expected behavior**
Timepicker popup should not me misaligned. 

**Version**
4370 IDS - RC0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/107030215-3fc85080-67eb-11eb-8923-b402025085a1.png)
![image](https://user-images.githubusercontent.com/45757016/107030463-a8afc880-67eb-11eb-99e5-795342620b35.png)

**Platform**
iOS 13-14 
iPhone 11 & iPhone 12

**Additional context**
N/a

**Comment by tmcconechy** [comment]
@janahintal i think this is similar to the other one you raised but i also cannot reproduce this one. Since it is intermittent i'm calling this minor

**Comment by tmcconechy** [comment]
descoping this one for now
