### ISSUE TITLE
Tabs: Animated bar of selected tab gets longer when inline validation takes place.

### ISSUE THREAD

**Issue by ktfields** [infor-design/enterprise#4818]
**Describe the bug**
Tabs: Animated bar of selected tab gets longer when inline validation takes place.

**To Reproduce**
Issue occurs on nested tabs, where outer tab is a module tab and inner tab has inline validation. I created a sample to replicate the issue using codes from the webpage (IDS).
[tabAnimatedBar-updated.zip](https://github.com/infor-design/enterprise/files/5950956/tabAnimatedBar-updated.zip)
![tabAnimatedBarIssue](https://user-images.githubusercontent.com/39935379/107356398-baef7680-6b0b-11eb-8607-b829dcf96988.gif)

The html file I created includes the following components:
1. https://design.infor.com/code/ids-enterprise/latest/demo/components/header/example-tabs?theme=uplift&variant=light (Changed the type of tab to module tab)
2. https://design.infor.com/code/ids-enterprise/latest/demo/components/validation/example-index?theme=uplift&variant=light (Added field validation to the first module tab, "Header Tabs Example")

1. From the "Header Tabs Example", delete the value of the textbox.
2. Required icon will appear
3. Input any value again in the textbox
4. Observe the animated bar of selected tab ("Header Tabs Example")

**Expected behavior**
Width of animated bar of selected tab should not increase after performing the steps above.

**Version**
- ids-enterprise: v4.36.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39935379/107171011-c1db9380-69fc-11eb-8934-ef6a3f58f6b4.png)

**Platform**
Browser Name: Chrome, Edge
Browser Version: Chrome 88.0.4324.150, Edge 88.0.705.63

**Comment by tmcconechy** [comment]
@ktfields i couldn't seem to get that example to run but if i put a required field on http://localhost:4000/components/tabs-module/example-index.html#module-tabs-controls thnei see some slightly different behavior.

Can you update the example so it runs?

**Comment by ktfields** [comment]
> @ktfields i couldn't seem to get that example to run but if i put a required field on http://localhost:4000/components/tabs-module/example-index.html#module-tabs-controls thnei see some slightly different behavior.
> 
> Can you update the example so it runs?

Hi @tmcconechy, I uploaded the updated sample codes (tabAnimatedBar-updated.zip). Thanks!

**Comment by ktfields** [comment]
Hi @tmcconechy, just checking in to see if there's an update here. 
Have you had the chance to look into the issue again? Thank you.

**Comment by tmcconechy** [comment]
I was able to verify the issue but we did not have a chance to work on this. The backlog is rather big right now.

We are looking at https://github.com/infor-design/enterprise/issues/4877 which is similar. So i'll mention who picks up that to take a quick look if this can be solved along that as well.

**Comment by ktfields** [comment]
hi @tmcconechy, just checking in again for updates on the status of this issue. Thanks!

**Comment by tmcconechy** [comment]
I tested this against the latest version (4.50.1) and its not fixed by the related issue. We will have to take a look further so put it in the next available (June) sprint

**Comment by tmcconechy** [comment]
For who picks this up. The idea is to remove the animation and way of doing things and do it with just a css for focus and selection state

**Comment by EdwardCoyle** [comment]
This will also fix #5094

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.54.0-dev.

https://main-enterprise.demo.design.infor.com/components/tabs/test-no-animation-tabs.html
![Animation Tabs Fix](https://user-images.githubusercontent.com/84306838/127614002-e111b41b-5479-4984-951c-bbef63c00a95.gif)

Moving this ticket to Done.

Thanks!
