### ISSUE TITLE
Splitter: Inconsistent splitter width

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4819]
**Describe the bug**
Splitter: Inconsistent splitter width

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/splitter/example-splitter-right-custom-width.html
2. Hold and swipe the splitter to the left very fast

**Expected behavior**
Splitter width should be consistent

**Version**
4.370 ids rc0 / 4.380 ids - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/107214405-d3e12480-6a44-11eb-82ef-d1c2245d7038.png)

**Platform**
All major browsers

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping this - we will fix it when we recreate this component
