### ISSUE TITLE
Donut Chart Does Not show tooltip if only 2 slices

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#482]
**Describe the bug**
A specific pie chart config causes tooltips to not work.

**To Reproduce**
1. Go to components/pie/example-tooltip.html
2. Change data to
```
public donutData = [{
        data: [{
            name: 'Component A',
            value: 10
        }, {
            name: 'Component B',
            value: 30
        }],
        centerLabel: 'Donut Chart'
    }];
```
3. Run
4. Hover the sliced

**Expected behavior**
Should see a tooltip on hover (it does work with the default example just not this specific case for some reason).

**Platform**
All

**Additional context**
From Ms Teams Divya Parepally...

**Comment by ericangeles** [comment]
Hi @tmcconechy . I made a lot of testing and bug fixing but it seems that there's just a particular/specific value that cause the bug, which is value: 10 and value: 30. Am not sure if this bug is in the d3 library? Just wanted to know your thoughts about it. Thanks.

**Comment by tmcconechy** [comment]
Yes, looks like when its exactly in quarters. Fx .25, .5, .75, 1

From what i can see looks like a problem here… https://github.com/infor-design/enterprise/blob/master/src/components/pie/pie.js#L421 because all for “directions” are false.

Maybe just change these to <= as its exact equal when in quarters.. Fx here
https://github.com/infor-design/enterprise/blob/master/src/components/pie/pie.js#L407
`rads <= (7 * Math.PI / 4) && rads >= (5 * Math.PI / 4)`
But try to test all 4 quarters as it might be wrong when its exact in any direction… See what i mean?
