### ISSUE TITLE
ApplicationMenu: Accordion sub parent icon issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4821]
**Describe the bug**
the icon of the subparent in accordion had changed

1. Go to https://4370-rc0-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html
2. Expand "`My Roles`"
3. Notice that the icon of `Role #1` is different from `Role #2` 

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/107223532-40622080-6a51-11eb-8d8a-90ba01f7df73.png)

**Version**
- ids-enterprise: v4.37.0-rc0 - master v4.38.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/107223597-566fe100-6a51-11eb-864e-67fcf5e78668.png)

**Platform**
All major browser

**Additional context**

**Comment by tmcconechy** [comment]
We did this on purpose to test both options so closing
