### ISSUE TITLE
ToolbarFlex: Migrate contextual-toolbar to toolbar-flex

### ISSUE THREAD

**Issue by tfavorite** [infor-design/enterprise#4823]
**Is your feature request related to a problem or use case? Please describe.**
While migrating toolbars in our system to toolbar-flex we noticed that the contextual-toolbar flavor did not have styles implemented for it. the example is on https://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html if you select a row

**Describe the solution you'd like**
Migrate contextual-toolbar to toolbar-flex

**Describe alternatives you've considered**
Not migrating in this case, or adding styles to work around it.

And what application do you work on? Infor Nexus

**Comment by tmcconechy** [comment]
Think this was fixed on another issue...
