### ISSUE TITLE
Datagrid: Cells with a leading space have a dirty indicator on second blur without changes

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4825]
**Describe the bug**
When a cell has a purposeful leading space, the space is replaced with '&nbsp', triggering a dirty indicator after the cell is clicked twice without changing the value.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-editable.html
2. Add the "showDirty: true" setting to the datagrid and set the quantity of the first row to "  1".
3. Click on that cell and blur it, and repeat this step.
4. Notice that the dirty indicator appears without ever changing the cell value.

**Expected behavior**
Since our use of the datagrid allows the use of leading spaces, it is expected that these spaces are preserved and that without changing the value of the cell the dirty indicator should not appear.

**Version**

- ids-enterprise: v4.37.0-dev

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 88.0.4324.146 (Official Build) (64-bit)

**Comment by janahintal** [comment]
This is now working as expected.
Verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-cell-with-leading-space-dirty-indicator.html
