### ISSUE TITLE
Tooltip: Icon issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4827]
**Describe the bug**
there's no icon in tooltip.

1. Go to https://master-enterprise.demo.design.infor.com/components/tooltip/example-icon-in-tooltip.html
2. Hover over the button
3. Notice that the icon is missing in tooltip

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/107361502-71565a00-6b12-11eb-8426-7a1b4edd1738.png)

**Version**
- ids-enterprise: v4.38.0-dev master

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/107361460-60a5e400-6b12-11eb-952e-848182970513.png)

**Platform**
all major browsers

**Additional context**

**Comment by tmcconechy** [comment]
Lets take a look at this. It definitely regressed

**Comment by jbrcna** [comment]
This issue is now resolved. thank you
v4.39.0-dev
https://master-enterprise.demo.design.infor.com/components/tooltip/example-icon-in-tooltip.html
![image](https://user-images.githubusercontent.com/56722184/111586011-27405280-87fb-11eb-98c2-3d7f7e5b5199.png)
