### ISSUE TITLE
Input: Cant clear search field using tab key

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4828]
**Describe the bug**
Input: Cant clear search field using tab key

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/input/example-clearable.html?theme=uplift&variant=dark&colors=0066D4
2. Type anything on the first field 
3. Tab to focus on the 'x' or clear button
4. Populate the search field
5. Tab to focus on the clear button

**Expected behavior**
Same behavior with the first field

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/107368803-f5f9a600-6b1b-11eb-9fea-e1a1b0e4aeaa.png)

**Platform**
All major browsers

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Coincidentally i fixed this on this PR https://github.com/infor-design/enterprise/pull/4824 so will be in shortly.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
