### ISSUE TITLE
Soho Pie Component: Controls to highlight pie chart sections do not have descriptive name, role, or state information.

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#4831]
**Describe the bug**
[VPAT] Controls to highlight pie chart sections do not have descriptive name, role, or state information.
**To Reproduce**

Reproducible on the following pages: 
* https://master-enterprise.demo.design.infor.com/components/pie/example-donut.html
* https://master-enterprise.demo.design.infor.com/components/pie/example-contextmenu.html

**Expected behavior**
Ensure the following information is conveyed for each group of pie chart buttons:
1. A meaningful label describe the function/purpose of the control (ex: Highlight Griffin, Pam (10%)).
2. A role to inform users of how the control functions (ex: role="button")
3. A state to inform users when the button is pressed/not pressed. This can be done using the aria-pressed property. 

**Version**

- ids-enterprise: 4.36.2

**Platform**
 - Infor Application/Team Name: Landmark Client
 - Device: (if applicable) NA
 - OS Version: Windows 10
 - Browser Name: Firefox
 - Browser Version: 85.0 (64-bit)

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-34284
One of the High Priority Koch Items.

**Comment by tmcconechy** [comment]
Not sure i fully understand the proposal here. Are we talking about a role or make the legend items be a button (might be easy). Are adding them to the pie slices? Might be a challenge.

**Comment by JBismonte** [comment]
Hi @tmcconechy, looks like we just need to add roles and meaningful labels in only the legends and not the slices.

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/113093891-57d4b300-9223-11eb-93ef-40a853b9572a.png)
![image](https://user-images.githubusercontent.com/45757016/113093947-73d85480-9223-11eb-837d-415cdbefb0d9.png)
