### ISSUE TITLE
Datagrid - French accents are not matching when using alert ranges

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#4832]
**Describe the bug**
Datagrid - Status column showing blank in French language.

**To Reproduce**
Please replace bellow attached file in the enterprise-ng project and go to link http://localhost:4200/ids-enterprise-ng-demo/datagrid-dynamic
you will see the value "En file d\'attente" is not getting display in datagrid view with icon.
[datagrid-demo.service.ts.zip](https://github.com/infor-design/enterprise-ng/files/5958542/datagrid-demo.service.ts.zip)

**Expected behavior**

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by dhumalkishor** [comment]
Hi Tim,

Any update on this?

Regards,
Kishor

**Comment by tmcconechy** [comment]
No not at this time but will put it in for next sprint

**Comment by davidcarlsonberg** [comment]
Hey @tmcconechy , any clues as to where to start with this issue?

**Comment by tmcconechy** [comment]
We took a look at this @dhumalkishor and one solution is to escape your quotes

https://github.com/infor-design/enterprise/pull/5529/files#diff-d305d6ee255d64e6b8aea5a79ee2f7a5d61152801c94d0a95e6b47cfd64321eeR29 

And it works. Did you try that?

**Comment by JangleShubham** [comment]
Hello @tmcconechy ,

In which version of this fix is available? We tried it with 4.54.0 but we are still getting issue, we have added escape character in options, ranges as well as in data.
Please see below image:
![Github-4832](https://user-images.githubusercontent.com/50510865/130577014-f91ee3a1-c034-4689-90b6-0f710920d532.png)

Thanks,
Shubham Jangle

**Comment by tmcconechy** [comment]
This fix is going to be in 4.55.0 which is not released until early Sept sometime. But you can use this dev release if you want to test it `4.55.0-dev.20210823`

**Comment by jbrcna** [comment]
this issue is now resolved. moving this ticket to done. Thanks
 v4.55.0-dev
verified in 
https://main-enterprise.demo.design.infor.com/components/datagrid/test-alerts-escaped-html.html
https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
![image](https://user-images.githubusercontent.com/56722184/130788474-9cf046b3-37cc-4501-8e04-a260ce8f2e5f.png)
