### ISSUE TITLE
Accordion: On a collapse the open state of the header does not change

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4838]
**Describe the bug**
When you collapse an accordion option, the open state remains unchanged at "true".

**To Reproduce**
1. Add the below code to the bottom of 'example-accordion-panels.html'
2. Click on any of the accordion options to expand
3. Look at the console and note the open states of the accordion
4. Click on that same accordion option to collapse
5. Look at the console and note that the open state of that option is unchanged

**Code Segment to Add**
```
<script>
  const $accordions = $('div.accordion ');
  function listOpenHeaders() {
    const states = $(this).children('.accordion-header').map((i, header) => {
      return {
        text: $(header).text().trim(),
        expanded: $(this).data('accordion').isExpanded(header)
      }
    }).toArray();
    console.log(states);
  }
  $accordions.on({
    afterexpand: listOpenHeaders,
    aftercollapse: listOpenHeaders
  });
</script>
```

**Expected behavior**
It is expected that on a collapse for an accordion header, the open state would be false.

**Version**
- ids-enterprise: v4.38.0-dev

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 88.0.4324.150 (Official Build) (64-bit)

**Comment by s-werking** [comment]
Hi @tmcconechy, this bug fix is our team's highest priority. Could we get an ETA for it?

**Comment by tmcconechy** [comment]
hi @s-werking took a quick look and found a solution. WIll add to 4.38
Seems like the events afterexpand and aftercollapse fire just before setting the expanded state.

Workaround might be looking for the is-expanded class instead but i didnt test that. Anyways have a fix.

**Comment by s-werking** [comment]
Thanks Tim! I appreciate it

**Comment by jbrcna** [comment]
QA Passed
v4.38.0-dev
![image](https://user-images.githubusercontent.com/56722184/109443609-ecf25980-7a75-11eb-9e42-65c161496b92.png)
