### ISSUE TITLE
Breadcrumb: Small scrollbar besides the breadcrumb in Safari

### ISSUE THREAD

**Issue by NicholTamayo** [infor-design/enterprise#4839]
**Describe the bug**
A small scrollbar is displayed besides the breadcrumb in Safari browser.

**To Reproduce**
1. Go to 'https://master-enterprise.demo.design.infor.com/components/breadcrumb/test-flex-toolbar.html' using Safari browser.

**Expected behavior**
There's no scrollbar besides the breadcrumb.

**Version**
- ids-enterprise: 4.35.0/4.37.0

**Screenshots**
![IDS Text Flex Toolbar](https://user-images.githubusercontent.com/79066908/107896665-de824900-6f71-11eb-9210-167a39116fe5.PNG)

**Platform**
 - Infor Application/Team Name: Homepages
 - Device: Macbook
 - OS Version: Catalina
 - Browser Name: Safari
 - Browser Version: Version 14.0 (15610.1.28.1.9, 15610)

**Additional context**
Homepages issue: https://jira.infor.com/browse/LIME-6719

**Comment by jbrcna** [comment]
the issue is now resolved. v4.38.0-dev tried with both themes and other major browsers
https://master-enterprise.demo.design.infor.com/components/breadcrumb/test-flex-toolbar.html
![image](https://user-images.githubusercontent.com/56722184/108459242-3e019100-72b1-11eb-8e11-00e4015a272b.png)
