### ISSUE TITLE
Application Menu: Trigger styling not correct

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise#4842]
**Describe the bug**
When using the options below for soho-tabs (moduleTabs = true), the icon does not appear centered in the  `application-menu-trigger` list item:

**To Reproduce**
Enable appMenuTrigger for soho-tabs (moduleTabs) and set appMenuTriggerTextAudible to true.
``` json
{
  appMenuTrigger: true,
  appMenuTriggerTextAudible: true
}
```

1. Clone repo https://github.com/whernebrink/module-tabs-issue
2. Install deps and npm start

**Expected behavior**
Menu icon should be centered in the application-menu-trigger list item.

**Version**
- ids-enterprise:  v4.37.0  (enterprise-ng v9.1.5)

**Screenshots**
![Screenshot 2021-02-15 at 15 00 38](https://user-images.githubusercontent.com/73601152/107957129-7139dc80-6fa0-11eb-9889-acf690baeb10.png)

**Platform**
 - Infor Application/Team Name: M3
 - OS Version: OSX Catalina
 - Browser Name: chrome
 - Browser Version: 88.0.4324.96 (Official Build) (x86_64)

**Comment by janahintal** [comment]
QA Passed. Thank you!
![image](https://user-images.githubusercontent.com/45757016/108500704-28a95880-72eb-11eb-9111-1fca539840ff.png)
![Uploading image.png…]()
