### ISSUE TITLE
Tabs Module: Home button focus border is not visible

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4850]
**Describe the bug**
When focusing the home button on a header, the shadow box color is the same as the theme so the focus border is not visible. 

**To Reproduce**
1. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?colors=DE7223&theme=soho&variant=light
2. Click the menu button to put the home button in focus.
3. Notice that the focus outline is white
4. Open the debugger and select the home button to inspect
5. Look at the "Styles" of this element when it is focused
6. Note that the white shadow box has an "!important" flag

This example is the expected behavior, however in our application the white shadow-box does not have an "!important" flag so the shadow-box used is the same color as the selected theme and is not visible then.

**Expected behavior**
It is expected that when the home button is in focus, the border of the button is white.

**Version**
- ids-enterprise: v4.38.0-dev

**Screenshots**
Example's Behavior:
![image](https://user-images.githubusercontent.com/76002134/108257528-8b042c80-7124-11eb-9a1a-f4aa8a4ac76b.png)
![image](https://user-images.githubusercontent.com/76002134/108258588-ceab6600-7125-11eb-8e7b-8ff72df1842d.png)

Application's Behavior:
![image](https://user-images.githubusercontent.com/76002134/108258245-6ceafc00-7125-11eb-8ff2-865135b40a6b.png)
![image](https://user-images.githubusercontent.com/76002134/108258306-7a07eb00-7125-11eb-8825-9ade69099e56.png)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 88.0.4324.150 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I also thought the problem on https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home was that if you tab into the page it skips everything in the header except the search field.

Does tabs-module use tab instead of arrows?

**Comment by s-werking** [comment]
Yes, that was an issue. You can use both tabs and arrows, but the arrows in the header just focuses between the menu, searchfield, and home button.

**Comment by ericangeles** [comment]
@tmcconechy was checking it last time, it seems that the big changes (the new and classic) affect its UI behavior. The focus state does not seem to work anymore.

**Comment by tmcconechy** [comment]
ok feel free to have a look. If you solve we can add to the sprint

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/109481090-4e86e800-7ab7-11eb-87dc-d3fcfbec55a9.png)
Tested in both theme and all colors.
