### ISSUE TITLE
Rating - unselecting back to the no stars selected leaves first star outline as yellow

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#4853]
**Describe the bug**
The outline of the first star remains yellow, even after being unselected. This only happens when you go from some stars being selected down to none.

**To Reproduce**
1. Go to '/components/rating/example-index.html'
2. Click on the first star twice (once to select just one star, and then to unselect all stars)
3. See error

**Expected behavior**
The color of the outline should match the other stars when all are unselected.

**Version**

- ids-enterprise: v4.38.0-dev

**Screenshots**
![RatingYellowOutline](https://user-images.githubusercontent.com/22107636/108274359-64e98700-713a-11eb-8400-ab1b4730ec0f.gif)

**Platform**
 - All

**Comment by jbrcna** [comment]
the issue is now resolved. v4.39.0-dev. thank you
https://master-enterprise.demo.design.infor.com/components/rating/example-index.html
