### ISSUE TITLE
Tabs: Can't click the 'x' or close button in  Toast when in responsive view. The background is also not that readable when not focused in Windows Chrome

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4854]
**Describe the bug**
Tabs: Can't click the 'x' or close button in  Toast when in responsive view. The background is also not that readable when not focused. 

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/tabs/example-url-hash-change.html?theme=uplift&variant=dark&colors=0066D4#tab-number-one
2. Minimize the screen and go to responsive view
3. Click tabs 'til the toast appear
4. Notice that the toast background makes the text not that visible and the 'x' button is cut off. 

**Expected behavior**
'x' should not e cut off in responsive view and texts should be clearer. 

**Version**
4.380 ids - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/108353595-4c08d080-7223-11eb-990f-2baaf2aa3be4.png)

**Platform**
Windows Chrome

**Additional context**
N/a

**Comment by tmcconechy** [comment]
I tried this but im not seeing whats in the screen shot (Mac Chrome page sized smaller). Anyone else see this?
