### ISSUE TITLE
Environment: Fix feature detection for Ipad

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4855]
**Describe the bug**
in ipad ios 13 the feature detection changed:

> I opened Settings -> Safari -> Request Desktop Website -> All websites. That option is enabled by default. I disabled it and the proper User Agent is now displayed.
> 
> 
> Mozilla/5.0 (iPad; CPU OS 13_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Mobile/15E148 Safari/604.1
> 
> IMO it should be disabled by default and if a user enables it a modal window should be displaying indicating not all web sites will be supported properly. Or maybe you may consider to add the iPad word to the first user agent to allow us to detect if it is an ipad emulating safari desktop or enable mouse event emulation, because I think when it is released several websites will fail.

**To Reproduce**

1. Go to http://localhost:4000/components/environment/example-browser-specs.html
2. Compare this page on ipad 11, 12, 13, 14 -> 13 and 14 are wrong

**Expected behavior**
Correct detection on ios 13 and 14 

**Platform**
 - Device: ipad
 - OS Version: 13/14
 - Browser Name: safari

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
