### ISSUE TITLE
Tabs Module: Resizing browser moves home button to "More" menu

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4857]
**Describe the bug**
This occurs when the toolbarsearchfield setting 'showCategoryText' is set to false. When you contract and expand the browser, the home button is sent into the 'More' menu.

**To Reproduce**
1. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
2. Set the 'showCategoryText' setting to false
3. Contract/Expand the browser
4. See that the home button remains in the 'More' menu

**Expected behavior**
It is expected that the home button will appear on its own when resizing.

**Version**
- ids-enterprise: v4.38.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/76002134/108402447-2a87f480-71e3-11eb-87a5-88d5c7b495bd.png)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 88.0.4324.182 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
This may be hard to fix as this is the behavior of the toolbar.

**Comment by awbuboltz** [comment]
Hey Tim, not sure if it's clear on this ticket, but the reason we're reporting is because after you maximize a window, the home button still doesn't expand. Once it's collapsed, it's collapsed until a browser refresh.

**Comment by janahintal** [comment]
QA Passed. Verified in https://4510-beta0-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html?layout=nofrills
![image](https://user-images.githubusercontent.com/45757016/116985373-f363b280-acfe-11eb-9da3-53993f43559f.png)
