### ISSUE TITLE
ApplicationMenu: unable to collapse/expand after search

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4861]
**Describe the bug**
when you search to filter the accordion becomes uncollapsible

1. Go to https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html
2. Type and search "Role"
3. Try to Collapse the accordion

**Expected behavior**
should be able to collapse/expand the list (accordion) after search

**Version**
- ids-enterprise: v4.37.0 - v4.38.0-dev

**Screenshots**
![Large GIF (530x452)](https://user-images.githubusercontent.com/56722184/108504614-26e29380-72f1-11eb-9bc6-1147e8104d78.gif)

**Platform**
All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
hi @EdwardCoyle assuming this must have broke on that recent patch of fixes...

**Comment by tmcconechy** [comment]
Lowering priority as its only not expanding the searched items. We think it should be fixed for usability but its not broken. We made this decision. So lower priority

**Comment by EdwardCoyle** [comment]
To clarify: Since the children of `Role #1` and `Role #2` include items that have the word `Role`, they match the filter, and the filtered mode doesn't currently let you collapse.  We're thinking it probably should though (technically an enhancment)
