### ISSUE TITLE
Application Menu Component: After clearing the search field it doesn't revert back to the default.

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#4863]
**Describe the bug**
Application Menu Component: After clearing the search field it doesn't revert back to the default..

**To Reproduce**

1. Go to url: https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized.html
2. Click inside the search field box and type in "zzzzzz" 
3. Remove the word "zzzz" and clear the search.
4. See error: when you search an item that is not on the list, the list doesn't revert back to default after you clear the search field

**Expected behavior**
The list should default back after you clear the search field box.

**Version**

- ids-enterprise: [e.g. v4.38 ]

**Screenshots**
![image](https://user-images.githubusercontent.com/39101346/108530099-3affa400-72a3-11eb-864c-53ff9603604c.png)

**Platform**
 - Infor Application/Team Name: [IDS]
 - Browser Name: [All Browsers and Devices]

**Additional context**
None

**Comment by tmcconechy** [comment]
Might want to fix this with https://github.com/infor-design/enterprise/issues/4861

**Comment by nganotice** [comment]
Hi @tmcconechy! This issue is still active, and I encountered it on https://4520-beta0-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html - didn't raise a new issue since it's just the same.

CC: @CindyMercadoReyes 

Thanks!

**Comment by tmcconechy** [comment]
thanks @nganotice - we will be looking to fix this, this sprint

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
