### ISSUE TITLE
Datagrid: More noticeable new row when adding inline

### ISSUE THREAD

**Issue by clazarev** [infor-design/enterprise#4865]
When a new row is added in a data grid with inline editing, it is hard for users to notice what happens when they click the "+" button(we've got few complaints already).
In comparison, when you dbl click in a cell, it gets highlighted with "is-editing" 
![datagrid_add_new_row](https://user-images.githubusercontent.com/11888130/108732341-14d04300-74f3-11eb-908b-744ded584a92.gif)

**Describe the solution you'd like**
May be applying "is-editing" class to all cells with "has-editor" right after the row is added makes more sense because when I add a new row, I have not started editing a specific cell, but instead, I see this new row and all of its cell are ready for editing.
![image](https://user-images.githubusercontent.com/11888130/108732177-ec484900-74f2-11eb-8d2a-995a7ccef43c.png)

**Describe alternatives you've considered**
none

**Additional context**
Infor GHR

**Comment by tmcconechy** [comment]
We can only have one cell in edit mode at once. So the proposed design i dont think works.

- just to clarify you dont have to use the + in that location - this was an example
- you could try to setActiveCell to some other cell perhaps.
- also you could pass data in to the new row that might give a hint like "New Row" or something. See here https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L490 where you can pass an object in for defaults on the row.

Some ideas...

**Comment by clazarev** [comment]
@tmcconechy , Thanks!
I will suggest to LM team to add "rowstatus-row-new" and "#icon-dirty"
![image](https://user-images.githubusercontent.com/11888130/108861059-71476700-75b4-11eb-821c-56a55cc88d75.png)
you can close it,
