### ISSUE TITLE
TabsVertical: Hover state is black

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4867]
**Describe the bug**

**To Reproduce**
1. Go to http://localhost:4000/components/tabs-vertical/example-index.html?theme=uplift&variant=contrast
2. Hover the vertical tabs
4. See how osme are black and unreadable

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Additional context**
Ms Teams

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by janahintal** [comment]
This issue is now resolved. 
![image](https://user-images.githubusercontent.com/45757016/109278901-0a47dd80-7854-11eb-949c-103ef86f1b75.png)
