### ISSUE TITLE
Editor: Text Formatting issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4870]
**Describe the bug**
there's an instance when you format a text with some combination it does not apply the all the format you selected

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html?theme=uplift&variant=light&colors=0066D4
2. Type a text to editor field
3. Format the text by selecting it then change `font color to red`
4. Select the text again then change to `Bold`
5. Notice that it change the font color to red and font `Bold`
6. Click Enter and Input a text again in editor
7. Format the text by selecting it then add `italic` and `underline`
8. Format the text by selecting it then change `font color to blue`
9. Notice that the font color changes to blue but the `Bold`, `Italic`, and `Underlined` was removed
10. Try to play around by changing the header then bold (vice versa) - the vice versa has the issue
11. Format to `Bold`
12. Change to` Header 1`
13. Notice that the `Bold` was removed

**Expected behavior**
should be able to format the text accordingly regardless of the format combination used

**Version**
- ids-enterprise: v4.38.0-dev

**Screenshots**
![Large GIF (608x588)](https://user-images.githubusercontent.com/56722184/108846307-64109380-7619-11eb-9717-48d79bf32dc4.gif)

**Platform**
All major browsers

**Additional context**
ensure that you paste the URL above. if you start from Soho theme and you switch to Uplift you have to refresh the browser so you can replicate the issue

**Comment by tmcconechy** [comment]
Tricky issue - also a bit hard to reproduce so making it minor

**Comment by tmcconechy** [comment]
Descoping this for now
