### ISSUE TITLE
Message: data-automation-id not added to root of the dialog

### ISSUE THREAD

**Issue by PaulLad77** [infor-design/enterprise#4871]
**Describe the bug**
When using the message dialog and passing attributes for automated testing (data-automation-id) these are not applied to the main div for the message dialog.

**To Reproduce**
Create simple message dialog and pass attributes for automated test/ids.

**Expected behavior**
Attributes added to Message dialog.  The test attributes are added to other parts of the dialog such as title, but it would be useful if the attribute is applied to the main div (without any further text appended) for the modal so it can easily be picked up by automated testing tools.

**Version**
- ids-enterprise: v4.36.2

**Additional context**

** Workaround **
A workaround would be to use the Modal dialog directly for messages, however this approach is not ideal and will need to be changed when the Message dialog supports automated testing attributes.

I have check the latest version 3.7.x of the code and it still looks to be an issue.

**Comment by tmcconechy** [comment]
@PaulLad77 im not sure if i can reproduce this issue. Perhaps this is working now or i misunderstand where you want the ID.

1. Go to https://master-enterprise.demo.design.infor.com/components/message/example-index.html
2. click "alert example"
3.  see that there is an id on the message text area

Will this work or do you want it on the root too (which is technically the modal)?

![Screen Shot 2021-03-09 at 9 28 24 AM](https://user-images.githubusercontent.com/814283/110485628-d8d3db00-80b9-11eb-803e-7eaa884f02fa.png)

**Comment by PaulLad77** [comment]
Hi Tim,

Our automated test engineer requested that the id also be set on the root/modal if that's okay?

Paul.

**Comment by tmcconechy** [comment]
Added it to the div with `.modal` class

**Comment by PaulLad77** [comment]
Cheers Tim.  Thanks!

________________________________

**Comment by jbrcna** [comment]
the issue is now resolved. v4.39.0-dev. thank you
https://master-enterprise.demo.design.infor.com/components/message/example-index.html
![image](https://user-images.githubusercontent.com/56722184/111414832-ac543a80-871b-11eb-8fe1-79bd15fbc941.png)
