### ISSUE TITLE
FileUpLoad Advanced : Disabled/Enabled not working

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#4872]
[disabled] is not working, When variables are set with the values to disabled it, the fileUpload stays enabled.

**To Reproduce**
Use the fileupload-advanced example in the IDS master

Steps to reproduce:
1. Click Disabled button on top 
2. nothing is disabled
![image](https://user-images.githubusercontent.com/17933529/108870616-449c4b00-75c6-11eb-8100-2c314c0fbb2b.png)

**Expected behavior**
Disabled and enabled when the variables are set.

**Version**
"ids-enterprise-ng": "^9.1.5",
 "ids-identity": "^3.0.5",

**Comment by janahintal** [comment]
Hi @tmcconechy. Just need to verify if this is also expected - when a file is attached & I click disabled button, the attachment is not disabled & only the file upload is disabled. 
![image](https://user-images.githubusercontent.com/45757016/110897026-a505e900-8337-11eb-8a53-a88a5d518043.png)

Verified in https://master-enterprise.demo.design.infor.com/components/fileupload-advanced/example-enabled-disabled.html?theme=classic&mode=light&colors=2578a9

**Comment by tmcconechy** [comment]
Yeah i think thats ok for now its kind of a strange case to disable it while your using it. So i think either thing would be acceptable. I.E. it finishes and lets you work with the files

**Comment by janahintal** [comment]
Thanks for this. Will now move the ticket to Done.
