### ISSUE TITLE
ApplicationMenu : Subtle high-contrast theme - submenu expander icon is same color as background

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4874]
**Describe the bug**
When the subtle high-contrast theme is selected, the plus-minus icon that expands a submenu in an application menu with an "is-personalizable" class is the same color as the background so it is not visible.

**To Reproduce**
1. Go to http://localhost:4000/components/applicationmenu/example-personalized-roles.html?theme=soho&variant=contrast&colors=de7223
2. Notice that the 'Level 2' submenu icon is not visible since it is the same color as the background
3. Open http://localhost:4000/components/applicationmenu/example-personalized-roles.html?theme=soho&variant=contrast in a new tab
4. Notice for this theme color, it is not an issue.

**Expected behavior**
It is expected that the plus-minus icon is visible when an application menu header has a submenu.

**Version**
- ids-enterprise: v4.38.0-dev

**Screenshots**
Theme dark enough to make icon light:
![image](https://user-images.githubusercontent.com/76002134/108883571-37358f80-75cb-11eb-9c96-68d6c5ac4b2e.png)

Theme selected is "bright" so icon is black:
![image](https://user-images.githubusercontent.com/76002134/108883691-61874d00-75cb-11eb-9ae6-c7bc7489542a.png)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable)N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 88.0.4324.182 (Official Build) (64-bit)

**Comment by jbrcna** [comment]
QA Passed
v4.38.0-dev
![image](https://user-images.githubusercontent.com/56722184/109443242-05ae3f80-7a75-11eb-95d8-3d40e641c91c.png)
