### ISSUE TITLE
Tabs Module: Overlapping Search field close button when in responsive view in Windows Edge

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4878]
**Describe the bug**
Text is overlapping on the search field.

**To Reproduce**
1. Go to Tabs Module: Overlapping Search field close button when in responsive view in Windows Edge ON https://master-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html
1. Type with the search field and enter a long text to see the error. 
1. Minimize the screen to responsive view

**Expected behavior**
Buttons / icons should not overlap with the text. 

**Version**
4.380 dev 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/108996381-430f7780-76d9-11eb-9788-fbddef46f98e.png)

**Platform**
Windows 10 
Edge Browser

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping for now
