### ISSUE TITLE
Blockgrid Control: Records per Page dropdown and Update button disappear on smaller(mobile) screen

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#488]
**Describe the bug**
Records per Page dropdown and Update button disappear when resizing to smaller(mobile) screen.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/blockgrid/example-paging.html and http://master-enterprise.demo.design.infor.com/components/blockgrid/test-update.html
2. Resize the screen to smaller (mobile) view
3. Notice that the Update button and Records per Page dropdown will disappear

**Expected behavior**
Update button and Records per Page dropdown should still be displayed on smaller view.

**Screenshots**
<img width="406" alt="screen shot 2018-07-24 at 4 13 33 pm" src="https://user-images.githubusercontent.com/39508864/43125475-bc420a6c-8f5c-11e8-95d2-9316bfb7a349.png">

**Platform**
 - Windows and Mac
 - All browsers

**Additional context**
On mobile (Android and iOS), Records per Page dropdown and Update button are not displayed

**Comment by tmcconechy** [comment]
Actually this is correct, we decided to hide the records per page at the lowest breakpoint because there is not enough room for it if there is a lot of pages.

**Comment by brianjuan** [comment]
Noted @tmcconechy, thanks!
