### ISSUE TITLE
Datagrid: Textarea formatter does not support singleline

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#4882]
**Describe the bug**
The list column definition is set to single line. The Textarea formatter renders long text spanning multiple lines.

**To Reproduce**

1. Go to datagrid tests, test-long-text.html
2. Change the following column definition to set singleline: 
columns.push({ id: 'activity', name: 'Activity', field: 'activity', width: 360, formatter: Formatters.Textarea, singleline:true });
3. Bring up the test html (https://master-enterprise.demo.design.infor.com/components/datagrid/test-long-text.html)

**Expected behavior**
The activity column in the first row displays in singleline.

**Version**

- ids-enterprise: [IDS Enterprise Components - v4.36.2

**Screenshots**

**Platform**
 - Infor Application/Team Name: Landmark
  - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by aaralikar** [comment]
![image](https://user-images.githubusercontent.com/22720894/109076335-0c793300-76c0-11eb-9e43-0fa06cbad784.png)

**Comment by tmcconechy** [comment]
We have a couple examples with single line 
https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-editor-singleline.html
https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-editor-singleline-rowheight.html

Everything seems to be working on there. Note that the single line option works with the editor formatter and editor not the textarea formatter. Are you asking for a feature to make the textarea have single line? Or can you use it like that

**Comment by aaralikar** [comment]
The editor formatter unescapes the content. Landmark has a requirement to display xml as Text. It will display in single line in the datagrid with a tooltip. Both the cell and tooltip content will be escaped html like &gt;xmlText&lt;

**Comment by tmcconechy** [comment]
Ok, As a workaround i think you can use a regular `Text` formatter to get single line. But i can see supporting the textarea rows option perhaps someday.
