### ISSUE TITLE
Calendar: mobile listview issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4886]
**Describe the bug**
the label of the event duration overlaps the icon in mobile listview

1. Using BrowserStack or browser dev tools
2. Go to https://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
3. Create events
4. Then click on any of the event in the calendar
5. After clicking the event, a listview component will appear with the information about the event at the bottom, there could be several depending whats on the day
6. Scroll down and Notice that the icon overlaps the label/text of event duration
7. Test also with long title and play around with the duration (i.e. uncheck all day

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/109299382-f9a56080-786f-11eb-8e71-3ad50d87ba66.png)

**Version**
- ids-enterprise: v4.38.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/109299341-e7c3bd80-786f-11eb-97ed-40ae8e39b514.png)

![image](https://user-images.githubusercontent.com/56722184/109299350-eabeae00-786f-11eb-98a7-64f8acb2afef.png)

**Platform**
mobile device/view

**Additional context**

**Comment by tmcconechy** [comment]
@jbrcna the bug is missing info? thanks

**Comment by jbrcna** [comment]
I pressed the enter key by mistake. info is updated now @tmcconechy

**Comment by jbrcna** [comment]
This issue is now resolved. thank you.
v4.39.0-dev
https://master-enterprise.demo.design.infor.com/components/calendar/example-index
![image](https://user-images.githubusercontent.com/56722184/110908414-be179580-8349-11eb-8be2-d52da6120fbf.png)
