### ISSUE TITLE
Calendar: Cancel & Submit button missing in iOS mobile

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4887]
**Describe the bug**
 The Cancel & Submit button were missing in iOS mobile. Android devices works fine

1. Using BrowserStack
2. Go to https://master-enterprise.demo.design.infor.com/components/calendar/example-index.html
3. Open modal to create an event
5. Notice that Cancel and Submit button were missing/hidden.
6. However, you can still hit Cancel button by clicking on the bottom left corner (by which cancel button is located). Same goes with Submit button by clicking on the bottom right corner.

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/109300264-42a9e480-7871-11eb-8106-112dd62b30c3.png)

**Version**
- ids-enterprise: v4.38.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/109300309-4e95a680-7871-11eb-96c5-1e8c84ad2051.png)

**Platform**
iOS mobile

**Additional context**

**Comment by tmcconechy** [comment]
Descoping this for now
