### ISSUE TITLE
Lookup: Empty page is occurring before getting into the landing page

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4893]
**Describe the bug**
Lookup: Empty page is occurring before getting into the landing page

**To Reproduce**

1. In a windows browser, Go to  https://master-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside
2. Open the lookup filter
3. Notice that Empty Page is showing very quickly before getting in the landing page

**Expected behavior**
Empty message should not show up. 

**Version**
4.380 dev ids

**Screenshots**

**Platform**
Windows Browsers - Chrome, Edge, FF

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Im seeing the empty message permanently show up. This is some sort of a demo app issue but not sure about it.

**Comment by tmcconechy** [comment]
Descoping this for now
