### ISSUE TITLE
Tooltip: Tooltip not on top of header

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4896]
**Describe the bug**
Something changed and now the tooltip is not on top of the header.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/input/test-tooltips.html?theme=classic&mode=light&colors=2578a9
1. Hover on '....'
1. See that the tooltip top is cut off

This is in all themes and works ok on https://latest-enterprise.demo.design.infor.com/components/input/example-index.html

**Expected behavior**
Not cut off

**Version**
- ids-enterprise: [e.g. v4.38-dev]

**Platform**
- only tested chrome

**Comment by tmcconechy** [comment]
I think this caused by this https://github.com/infor-design/enterprise/commit/76c57c9655b7078164a7f9413ae60507253a1e93#diff-446d916c9de0d2d43b8cb0b65d6829191dd631e3f6f8c6aaed6dad565ccad9ebR855 @EdwardCoyle

**Comment by EdwardCoyle** [comment]
I fixed this one on #4899

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
