### ISSUE TITLE
Tabs Module: Close icon for a clearable searchfield overlaps with 'Go' button

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4898]
**Describe the bug**
When you type in a clearable searchfield that has a Go button, it looks like the close icon is not visible, and it overlaps with the Go button.

**To Reproduce**
1. Go to 'http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html'
2. Add "clearable": true to the searchfield settings
3. Type in the searchfield
4. Notice that the 'x' icon is not inside the searchfield

**Expected behavior**
It is expected that when something is typed into the searchfield and it is clearable, the 'x' icon is seen inside the searchfield.

**Version**
- ids-enterprise: v4.38.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/76002134/109536084-e74f4080-7a82-11eb-91e5-3b26f1c46561.png)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: 88.0.4324.190 (Official Build) (64-bit)

**Comment by awbuboltz** [comment]
Hey Tim, could this get looked at for 4.39? We're nearing release and would like this fixed.

**Comment by janahintal** [comment]
QA Passed. Thanks!
![image](https://user-images.githubusercontent.com/45757016/111424100-3dcba880-872c-11eb-9287-41f6b2e7cf5a.png)
![image](https://user-images.githubusercontent.com/45757016/111424890-56888e00-872d-11eb-8fcf-fc9cac98fabc.png)
