### ISSUE TITLE
Datagrid: Resizing drilldown columns has erratic behavior

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4900]
**Describe the bug**
When resizing a drilldown column (particularly when you make it smaller than the original column size) the column will move erratically.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-drilldown.html
2. Resize the second column to be a smaller width
3. See that while resizing, the column glitches to different widths

**Expected behavior**
It is expected that while resizing, the columns of a datagrid will smoothly change size.

**Version**
- ids-enterprise: v4.38.0-dev

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: 88.0.4324.190 (Official Build) (64-bit)

**Additional context**
This is also seen in http://localhost:4000/components/datagrid/example-multiselect.html

**Comment by tmcconechy** [comment]
FYI - we probably wont be able to fix this until we do 5.0 where the grid is no longer a table. So its a huge change.
The reason this happens is the grid needs to size everything so it goes to 100% and by default it will adjust the neighbouring columns to stretch.

Ways you might be able to handle?
- add a fixed width on drill down columns (not sure about this)
- hold shift on resize -> this will just reduce the column in question and not effect other columns (separate resize mode)

**Comment by tmcconechy** [comment]
Going to descope this as i don't have any way to fix it until we refactor the grid some.
