### ISSUE TITLE
Radio: Selecting a radio button in a fieldset causes the legend to blink on the next fieldset

### ISSUE THREAD

**Issue by jvang01** [infor-design/enterprise#4901]
**Describe the bug**
Selecting a radio input causes the legend in a following fieldset to flicker.  This seems to happen when fieldsets are arranged vertically.

**To Reproduce**
Paste the attached html into any test page:
[radio-inputs-with-legend.txt](https://github.com/infor-design/enterprise/files/6065026/radio-inputs-with-legend.txt)

1. Paste the code above into any test page and open in a browser.
2. Select a radio input that is not in the last fieldset.
3. Note that the legend in the fieldset below blinks.

**Expected behavior**
Legend should not blink

**Version**
ids-enterprise: v4.38.0-dev

**Screenshots**
![radio-button-legend-blink](https://user-images.githubusercontent.com/64548726/109570770-3cee1200-7ab0-11eb-973a-a90eb806318e.gif)

**Platform**
Infor Application/Team Name: lawson
Device: (if applicable) N/A
OS Version: Windows 10
Browser Name: chrome
Browser Version: 88.0.4324.190 (Official Build) (64-bit)

**Comment by awbuboltz** [comment]
Hey Tim, this issue is super minor but also kind of an eyesore, can you schedule it for a future release?
