### ISSUE TITLE
Context Menu:  double focus on menu

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4903]
**Describe the bug**
Context Menu:  double focus on menu

**To Reproduce**

1. Go to https://4380-beta0-enterprise.demo.design.infor.com/
2. In Context Menu section, hover in Paste Special
3. Click Up & Down arrow keys 
See error

**Expected behavior**
There should only be one menu focused

**Version**
4.380 beta0 ids

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/109651294-4b642880-7b99-11eb-8deb-482ed4c2736d.png)

**Platform**
All major browsers 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Looks like its been this way a while. Seems roughly minor.

**Comment by tmcconechy** [comment]
Descoping this for now
