### ISSUE TITLE
Sink Page: Multiselect unable to search

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4904]
**Describe the bug**
search function of multiselect dropdown is not working in this version

1. Go to https://4380-beta0-enterprise.demo.design.infor.com
2. Scroll into multiselect dropdown
3. Click the field or press enter to open
4. Type to search
5. See error

**Expected behavior**
should be able to search

**Version**
- ids-enterprise: v4.38.0-beta0

**Screenshots**
![Large GIF (1124x564)](https://user-images.githubusercontent.com/56722184/109653642-39d05000-7b9c-11eb-9125-ebc506fede6b.gif)

**Platform**
all major browser

**Additional context**
if you don't open the dropdown (by clicking or by pressing enter).  The search function is working when you Use tab to focus then type to search
![Large GIF (1124x564)](https://user-images.githubusercontent.com/56722184/109653993-a21f3180-7b9c-11eb-81d3-c4823883f6c4.gif)

**Comment by tmcconechy** [comment]
Seems to only happen during scrolling

**Comment by jbrcna** [comment]
QA Failed.
v4.38.0-rc0 
the issue persists in Mac OS Safari. Chrome, Edge, Firefox works fine
https://4380-rc0-enterprise.demo.design.infor.com

**Comment by tmcconechy** [comment]
@jbrcna I see this as fixed..

1. go to https://4380-rc0-enterprise.demo.design.infor.com/ in chrome (mac)
2. scroll down to the multiselect
3. click to open
4. type a to search

@EdwardCoyle @deep7102 can you confirm?

**Comment by jbrcna** [comment]
@tmcconechy Chrome, Edge, Firefox browsers were fine. I was able to search in both multi select standard and with tags
only in Safari browser that I wasn't able to search. After I type some text the list closes. 
![Large GIF (936x668)](https://user-images.githubusercontent.com/56722184/110333268-5e28a280-805c-11eb-8a1f-b1bdbbfea6cf.gif)

**Comment by jbrcna** [comment]
This issue is now resolved. Thank you.
v4.38.0-rc1
![image](https://user-images.githubusercontent.com/56722184/110628508-0ca82100-81de-11eb-98e5-334b21945fe6.png)
