### ISSUE TITLE
Sink Page: Multiselect Unable to select/deselect multiple items consecutively

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4907]
**Describe the bug**
when you select an item in `Multiselct with tags` the list closes after just one selection.

1. Using BrowserStack
2. Go to https://4380-beta0-enterprise.demo.design.infor.com
3. Scroll down to Multiselect
4. Click to open `Mutliselect (Standard)`
5. Select multiple items
6. Working as expected
7.  Click to open `Mutliselect (with tags)`
8. Select multiple items
9. See error
10. Notice that each time you select an item the list closes

**Expected behavior**
should be able to select multiple items consecutively

**Version**
- ids-enterprise:v4.38.0-beta0

**Screenshots**
![Large GIF (596x564)](https://user-images.githubusercontent.com/56722184/109810477-88e1b800-7c64-11eb-819f-3ebee24429fe.gif)

**Platform**
iOS 14 on iPad Pro 12.9 2020
Safari

**Additional context**

**Comment by tmcconechy** [comment]
This is the same problem as https://github.com/infor-design/enterprise/issues/4904 so closing.. Will provide a fix

**Comment by jbrcna** [comment]
QA Failed. 
The issue still persists in v4.38.0-rc0
iOS 14 on iPad Pro 12.9 2020
https://4380-rc0-enterprise.demo.design.infor.com

**Comment by tmcconechy** [comment]
So just safari on this one too? Its the same issue as https://github.com/infor-design/enterprise/issues/4904#issuecomment-792789434

**Comment by jbrcna** [comment]
for this one, it fails in both Chrome and Safari on iOS 14 of  iPad Pro 12.9 2020.
it also fails in iPhone Chrome and Safari but it works fine on Android device.

**Comment by tmcconechy** [comment]
i dont see it failing in chrome - just safari..

**Comment by jbrcna** [comment]
Hi @tmcconechy this seems to be happening in [multiselect/example-compact](https://master-enterprise.demo.design.infor.com/components/multiselect/example-compact.html) v4.39.0-dev .when using` mobile devices iOS & android `the tag-display Multiselect doesn't stay open when selecting items from the list (by default it's supposed to): 
Kindly let me know if I need to file a separate ticket.

**Comment by tmcconechy** [comment]
I thought we fixed that. But i think yes - lets make a new issue with details since this is closed.

**Comment by jbrcna** [comment]
yes it's working fine on https://4380-rc0-enterprise.demo.design.infor.com. but the issue also exist in [multiselect/example-compact ](https://master-enterprise.demo.design.infor.com/components/multiselect/example-compact.html). 
Here's the new issue https://github.com/infor-design/enterprise/issues/5021. thank you
