### ISSUE TITLE
Sink Page: CAP unable to change the value of the dropdown

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4908]
**Describe the bug**
when you try to change the default value of the dropdown the dropdown list just closes and it doesn't change the value

1. Using BrowserStack
2. Go to https://4380-beta0-enterprise.demo.design.infor.com
3. Scroll down to `Contextual Action Panel`
4. Try to change the value of each dropdown
5. See error
6. Notice that you can't change the value of the dropdown
7. Also, Click to open `Template` dropdown
8. Working as expected
9. Click to open  `Ship Terms` dropdown
10. See error
11. Notice that the dropdown list opens below the other component

**Expected behavior**
should be able to change the value of the dropdown 

**Version**
- ids-enterprise: v4.38.0-beta0

**Screenshots**
![Large GIF (596x564)](https://user-images.githubusercontent.com/56722184/109811747-31444c00-7c66-11eb-9cbd-e65921d056d7.gif)

**Platform**
iOS 14 on iPad Pro 12.9 2020
Safari

**Additional context**
please see also this minor issue
![image](https://user-images.githubusercontent.com/56722184/109811208-7a47d080-7c65-11eb-8501-fb042c95ad7c.png)

_Expected result_
![image](https://user-images.githubusercontent.com/56722184/109811232-80d64800-7c65-11eb-8efb-ccdc508e5257.png)

**Comment by tmcconechy** [comment]
Might also be caused by https://github.com/infor-design/enterprise/issues/4904 will update once thats fixed

**Comment by jbrcna** [comment]
All the issues noted above were now resolved. 
![image](https://user-images.githubusercontent.com/56722184/110324540-15b7b780-8051-11eb-939d-04467b390264.png)

**Clarification**
when using `iOS 13 or 14 on iPad Pro 12.9 2020 Chrome` the dropdown won't open
![Large GIF (596x564)](https://user-images.githubusercontent.com/56722184/110324984-b3ab8200-8051-11eb-8bb9-46e5a9047acf.gif)
