### ISSUE TITLE
Tab: UI issues

### ISSUE THREAD

**Issue by arumnie93** [infor-design/enterprise#4910]
**Describe the bug**
The tab behavior is not ideal. 
1) The tabs that are showing are also displayed in the overflow dropdown. I think the overflow dropdown should on display the tabs that are not displayed.
2) The first and last tab have too much of a fading effect

**To Reproduce**
Tabs with overflow 

**Expected behavior**

**Version**
- ids-enterprise: 4.36.1

**Screenshots**
![Tabs issue](https://user-images.githubusercontent.com/79988555/109824133-8781a280-7c06-11eb-8d3a-cc0dbcf0d577.gif)

![image](https://user-images.githubusercontent.com/79988555/109823887-530de680-7c06-11eb-8cb1-bb19d1f1ecf1.png)

**Platform**
 - Browser Name: Chrome
 - Browser Version: Version 88.0.4324.192
 - 
**Additional context**

**Comment by tmcconechy** [comment]
So you suggest we just lower the "fade" a bit? Perhaps that's reasonable but labeling this minor.
Any particular justification or is it just a singular opinion?

**Comment by tmcconechy** [comment]
Closing this for now. Its pretty hard to change the design at this point and im not sure the justification as mentioned in the previous comment
