### ISSUE TITLE
Datagrid: When have frozen columns, unable to display the vertical scrollbar 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4912]
Describe the bug
For a list with frozen columns, want to be able to show the column headers when the contents is scrolled.
The following .css is preventing from showing the scrollbar on the right size of the datagrid (only when have frozen columns).

  &.left + &.center.scrollable-x,
  &.left {
    overflow-y: hidden;
  }

Expected behavior
The vertical scrollbars should not be hidden.

Version
- ids-enterprise: v4.38.0-dev

Screenshots
![image](https://user-images.githubusercontent.com/39804038/109994162-a77e9800-7cd2-11eb-8d9e-0e77fe3d3f9a.png)

**Comment by tmcconechy** [comment]
Have a fix for this - i investigated with @claudenbach

**Comment by claudenbach** [comment]
Landmark use case is for a tree list, as the user expands tree nodes the headers stay at the top of the screen.

**Comment by janahintal** [comment]
Not yet deployed in RC0. Working as expected in Master. 

![image](https://user-images.githubusercontent.com/45757016/110285656-8691ac00-801e-11eb-8fc2-bdaf11a63841.png)
https://4380-rc0-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-flex

**Comment by tmcconechy** [comment]
this should be deployed now on https://4380-rc1-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-flex

**Comment by janahintal** [comment]
QA Passed. 
Verified in https://4380-rc1-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-flex?theme=new&mode=dark&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/110607592-5127c280-81c6-11eb-85b3-a09dac48ea91.png)
