### ISSUE TITLE
Datagrid: "last" option does not stretch last column width

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4913]
**Describe the bug**
When setting the datagrid option stretchColumn to "last", the last column width remains the original calculated value, and does not stretch to the end of the grid.

**To Reproduce**
1. Go to the attached html page
2. Notice that the last column does not stretch to the edge of the datagrid. The other columns have instead stretched larger than their calculated widths.

[example-drilldown.zip](https://github.com/infor-design/enterprise/files/6085132/example-drilldown.zip)

**Expected behavior**
When stretchColumn is set to "last" it is expected that all columns except the last column are not stretched and the last column is stretched to the end of the grid.

**Version**
- ids-enterprise: v4.38.0-dev

**Screenshots**
What the datagrid looks like:
![image](https://user-images.githubusercontent.com/76002134/109994627-1b20a500-7cd3-11eb-9a69-8e5a0b33a22f.png)

What the datagrid would look like with a stretched last column:
![image](https://user-images.githubusercontent.com/76002134/109994772-40151800-7cd3-11eb-9e70-a3af7b8195c7.png)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 89.0.4389.72 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Can you also post that code change you think might fix? Note that a workaround for this we found investigating is to set `stretchColumn: 'lastColumnId'` instead of `'last'`

**Comment by s-werking** [comment]
A possible solution for this would be adding something like this inside the 'if' that checks for lastColumn on line 4784 of datagrid.js. It might be an adjusted value from this based on padding and edges :
 if (this.settings.stretchColumn === 'last') {
        colWidth = diff;
      }

**Comment by tmcconechy** [comment]
Another idea could be if last is set then set it to the last columns ID (which works).

**Comment by s-werking** [comment]
One issue we have noticed with using stretchColumn on the last column, is when resizing the last column past the edge of the datagrid the column is lost and the scrollbar only scrolls to the end of the second-to-last column.

**Comment by janahintal** [comment]
QA Passed. Thank you
Verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-stretch-last-column.html?theme=new&mode=light&colors=0066D4
