### ISSUE TITLE
Datagrid: Client side paging does not retain checked rows on Records per page change

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#4915]
**Describe the bug**
When selecting rows on the datagrid, then changing the records per page dropdown to a new value, the selected rows are not retained. Paging does work though.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-paging-client-side?theme=uplift&variant=light
2. Select a few rows
3. Change the records per page
4. Rows are unchecked 

**Expected behavior**
Selected rows should be retained

**Screenshots**
![issue](https://user-images.githubusercontent.com/2107139/109998210-9d5e9880-7cd6-11eb-8772-9f588e33056b.gif)

**Version**

- ids-enterprise: 4.38

**Platform**
 - Infor Application/Team Name: Lawson
 - Device: (if applicable) Browser
 - 
**Additional context**
I have verified that this regressed at some point after 4.15 but am unable to run an npm install after that version to verify when it broke.

**Comment by awbuboltz** [comment]
I see this is scheduled for 4.40, any chance of sliding it into 4.39 for our release?

**Comment by tmcconechy** [comment]
ok, i think thats all we can do in 4.39 right now.

**Comment by awbuboltz** [comment]
Hey Tim, any update on this? Is it going to make 4.39?

**Comment by tmcconechy** [comment]
yeah either me or @deep7102 will pick it up shortly. should make it

**Comment by awbuboltz** [comment]
Cool, thanks!

**Comment by janahintal** [comment]
QA Passed.
Verified in components/datagrid/test-loaddata-selected-rows.html
![image](https://user-images.githubusercontent.com/45757016/113570488-05dac580-9647-11eb-9c7d-d1bee2c4925c.png)
