### ISSUE TITLE
Grid option SelectAllCurrentPage does not work with deselect all event

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise#4916]
**Describe the bug**
If the datagrid has the option SelectAllCurrentPage set to true and you then select all rows and then deselect all rows the deselect all event wont trigger and wont empty the selected data

**Expected behavior**
Deselect event should trigger

**Version**
- ids-enterprise-ng: 9.2.0

**Comment by janahintal** [comment]
QA Passed. Verified in https://4380-rc0-enterprise.demo.design.infor.com/components/datagrid/test-paging-select-clientside-multiple-current-page.html
![image](https://user-images.githubusercontent.com/45757016/110310095-18a8ad00-803d-11eb-8d0e-bf1ed1dcbd2d.png)
