### ISSUE TITLE
Datagrid: List with frozen columns when vertical scrollbar is displayed rows become misaligned horizontally

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4922]
Describe the bug
For a tree list with frozen column, when the vertical scrollbar is displayed the rows become misaligned horizontally.

Testing with the fix provided as a patch to 4.37 for issue #4912.

1. Go to 'https://master-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-flex.html
2. Reduce the browser's window size until the list rows become misaligned

Expected behavior
Vertical scrollbars are visible when necessary and the list rows maintain horizontal alignment.

Version
- ids-enterprise: v4.37.1

Screenshots
![image](https://user-images.githubusercontent.com/39804038/110382738-ef7a2380-8020-11eb-8eed-43ccf1dee453.png)

**Comment by tmcconechy** [comment]
Note to self:
- this can be seen on both https://master-enterprise.demo.design.infor.com/components/datagrid/test-tree-frozen-columns.html and https://4371-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-flex.html
- make the page really wide so there is no horizontal scroll bar
- then resize width so there is a horizontal scroll bar
- scroll down and notice the last bar is cut off
- same with the inverse

**Comment by janahintal** [comment]
QA Passed. Verified in https://4380-rc1-enterprise.demo.design.infor.com/components//datagrid/test-frozen-columns-flex.html
![image](https://user-images.githubusercontent.com/45757016/110613879-b7174880-81cc-11eb-8742-bffe847df560.png)
