### ISSUE TITLE
Pie/Donut charts don't fill entire space when browser resizes

### ISSUE THREAD

**Issue by tfavorite** [infor-design/enterprise#4925]
**Describe the bug**
When resizing the browser window small enough so that the donut or pie goes into small view, then making the browser window bigger again, the donut or pie does not resize itself bigger again.

**To Reproduce**
This is a little tricky to reproduce, but:

1. go to https://design.infor.com/code/ids-enterprise/latest/donut 
2. make the window smaller _very slowly_. The donut goes into small view. 
3. Then, make it wider again.

**Expected behavior**
The donut/pie should get bigger again.

**Version**
4.37.1

**Platform**
 - Infor Application/Team Name: Infor Nexus
 - OS Version: MacBook Pro
 - Browser Name: Chrome
 - Browser Version: 88

**Additional context**
I think this can be fixed in pie.js's build by tacking an else to the if statement where the height:auto is added, to reset it to the normal size:
`else if (this.element[0].style.height === 'auto') { // unset height from auto if previously set so chart can fill space again
      this.element.css({ height: '' });
    }`
Happy to add a pull request if that's helpful.

**Comment by tmcconechy** [comment]
@tfavorite - pull request would be terrific. Please feel free

**Comment by jbrcna** [comment]
this is now working as expected. v4.39.0-dev
https://master-enterprise.demo.design.infor.com/components/donut/example-index.html
https://master-enterprise.demo.design.infor.com/components/pie/example-index.html
