### ISSUE TITLE
Data Grid column with time picker editor doesn't keep the HHmm format

### ISSUE THREAD

**Issue by AsafMeirBarziv** [infor-design/enterprise#4926]
The time editor is popping up with wrong values when using 

**Describe the bug**

**To Reproduce**
Use this column in order to reproduce

    columns.push({id: 'Start Time', name: 'Start Time', field: 'Start Time', editor: Editors.Time, formatter: Soho.Formatters.Time, timeFormat: 'HHmm', editorOptions: { timeFormat: 'HH:mm' }});

1. Select a time - 23:00
2. Click on the editor's time icon in order to pop up the time picker
3. See the wrong value in the time picker

**Expected behavior**
The 23:00 value should be in the time picker

**Version**
 *  IDS Enterprise Components - v4.35.4
 *  Date: 2020-12-22T17:48:41.860Z
 *  Revision: ece8d37ab06167cbad2811be6e657c293e2fdaf2

**Comment by tmcconechy** [comment]
i dont seem to be able to reproduce this. Please see example working example: (this is 4.38)

1. https://master-enterprise.demo.design.infor.com/components/datagrid/test-editable-time
2. the column time 24 is set to 
```
columns.push({ id: 'time3', name: 'Time 24', field: 'value', formatter: Formatters.Time, editor: Editors.Time, editorOptions: {'timeFormat': 'HH:mm'}, timeFormat: 'HH:mm', filterType: 'time' });
```
3. click any cell in that column and select 23:00
4. reopen that cell again by clicking again and 23:00 is shown

**Comment by AsafMeirBarziv** [comment]
Please use the HHmm time format in order to reproduce the issue.

Thanks

Cheers

//Asaf

**Comment by tmcconechy** [comment]
ok my mistake missed the missing `:` again. the way the API is built most formats we use have a seperator. So workaround is to use a separator of some type in the format.

**Comment by AsafMeirBarziv** [comment]
Got it - thanks, but as you probably know the original M3 formats do not
contain separators
its YYYYMMDD for date & HHMMSS for time

בברכה,

אסף מאיר ברזיו
asaf.meir.barziv@gmail.com
קיבוץ עין המפרץ
0524-281-872

**Comment by tmcconechy** [comment]
Yeah got it - it should work but in the past we had issues with no seperator because its not like that in any supported locales so we added it after. Seems like its not workin in certain places still so just saying the workaround

**Comment by jbrcna** [comment]
this issue is now resolved. 
v4.51.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-time
![image](https://user-images.githubusercontent.com/56722184/116039519-689b0c00-a69d-11eb-944d-80ada4ad72d9.png)
