### ISSUE TITLE
Sink Page: MultiSelect States Component Alignment Issue and Dropdown list box opens in different area of UI

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#4934]
**Describe the bug**
Sink Page: Multi Select States Component Alignment Issue and Dropdown list box opens in different area of UI

**To Reproduce**

1. Go to url: https://4380-rc1-enterprise.demo.design.infor.com/#
2. Scroll down to Multi select Standard
3. Click on the drop down list box and select a state on Win 10 Edge the "x" next to the state is not aligned correctly 
4. Second issues is across all browsers the drop at times opens on different areas of the Multi select section of the page, like under fruits section for no reason. It's an intermittent issue but I was able to get a screen shot of it o MAC FF 
4. See error. Please view both screen shots attached below

**Expected behavior**
Aligned needs to be corrected and the drop down list box should open under the states

**Version**

- ids-enterprise: [e.g. v4.38]

**Screenshots**
<img width="974" alt="Multiselect States IDS" src="https://user-images.githubusercontent.com/39101346/110698466-b0cca080-81bb-11eb-8678-61614f9f84c5.png">
![bs_win10_Edge_89 0](https://user-images.githubusercontent.com/39101346/110698781-16b92800-81bc-11eb-91dc-22dec656d6d2.jpg)

**Platform**
 - OS Version: [e.g. Windows 10 and iOS 8]
 - Browser Name: [Win 10 Edge and MAC FF]

**Additional context**
None

**Comment by tmcconechy** [comment]
Descoping this one for now
