### ISSUE TITLE
Busy Indicator start trigger

### ISSUE THREAD

**Issue by AsafMeirBarziv** [infor-design/enterprise#4935]
When I use the $('#BusyIndicator').trigger('start') it shows up only after done executing the code that follows this trigger - and that's not I intend to achieve.

I want to show immediately.

I couldn't find in the docs an example on how to start and stop the Busy Indicator manually and explicitly.

Something like BusyIndicator.start() & BusyIndicator.compltete();

**To Reproduce**
Steps to see the question or problem:
1. Write a function that call this trigger at the beginning
2. Add some extra code
3. Add the call to the complete trigger
3. Run
4. See that the indicator shows and disappear immediately and not right at the start of execution.

**Version**
 *  IDS Enterprise Components - v4.35.4
 *  Date: 2020-12-22T17:48:41.860Z
 *  Revision: ece8d37ab06167cbad2811be6e657c293e2fdaf2

**Comment by tmcconechy** [comment]
There is a new thread created but you can change the delay setting https://github.com/infor-design/enterprise/blob/master/src/components/busyindicator/busyindicator.js#L26 just change it to for example 0 or 1

In the angular project examples we do have an example of using this on a button click https://github.com/infor-design/enterprise-ng/tree/master/src/app/busyindicator

Does this answer your question?

**Comment by tmcconechy** [comment]
I assume this answers your question?
