### ISSUE TITLE
Data Grid selection-sum on columns

### ISSUE THREAD

**Issue by AsafMeirBarziv** [infor-design/enterprise#4936]
Is there a way of have a 'selection-sum' on a specific numeric column just like the selection-count functionality?

**Describe the Issue**
I wish the get automatic summary of a specific column

**Comment by tmcconechy** [comment]
@AsafMeirBarziv This example is showing a sum on a column:

https://master-enterprise.demo.design.infor.com/components/datagrid/example-summary-row.html
Its done via this column setup https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/example-summary-row.html#L29

**Comment by AsafMeirBarziv** [comment]
Thanks,

I know about the summary row, but I need to sum only selected lines' values
...
בברכה,

אסף מאיר ברזיו
***@***.***
קיבוץ עין המפרץ
0524-281-872

**Comment by tmcconechy** [comment]
Hmm ok i havent tried that or made any example. But what you can maybe try is making the formatter a custom one: Then perhaps you can look at the data given in the formatter and change the values you return to only the selected ones

```
summaryRowFormatter: function(row, cell, fieldValue, columnDef, rowData, api) { return 'value'; }
```

Also so your aware you can put the selection counts (not totalls tho) on the contextual toolbar like this example https://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html

**Comment by AsafMeirBarziv** [comment]
Thanks - Great
בברכה,

אסף מאיר ברזיו
***@***.***
קיבוץ עין המפרץ
0524-281-872

**Comment by tmcconechy** [comment]
I assume this answers your question?
