### ISSUE TITLE
Icons: Uplift theme has two classes for .icon

### ISSUE THREAD

**Issue by karinpb** [infor-design/enterprise#4938]
**Describe the bug**
When I use icons next to one another, the last one is cropped. This is caused by two css rules for icon, one with width 18 and one with width 20.

**To Reproduce**
Open the icon sample and check the icon classes that are applied in the uplift theme.

**Expected behavior**
I expect only one icon class with the width 22px.

**Version**

- ids-enterprise: 4.36.1

**Screenshots**
See screenshots of the issue and how it compares to subtle theme.
![uplift](https://user-images.githubusercontent.com/7961438/110770106-36eaf480-8259-11eb-893b-5515a378f932.png)
![subtle](https://user-images.githubusercontent.com/7961438/110770109-37838b00-8259-11eb-94c2-da9e8b0144f8.png)

**Platform**
 - Infor Application/Team Name: Infor Homepages
 - Device: -
 - OS Version: Windows 10
 - Browser Name: Chrome

**Additional context**

**Comment by tmcconechy** [comment]
@karinpb i think its going to be tricky to change that without risk of things being misaligned all over. Can you post the example situation where you need this changed? Maybe we can fix it another way thats a bit safer

**Comment by karinpb** [comment]
But you cannot have two classes with the same name in two different files? It's used for this: A list of icons for a widget so show information about the widget.
![image](https://user-images.githubusercontent.com/7961438/110806455-606c4600-8282-11eb-97dc-8a456a3ba376.png)
`<div *ngFor="let badge of badges" soho-tooltip
				[popover]="true"
				[title]="badge.title"
				extraClass="lm-badges-popover"
				[content]="badge.description">
			<svg *ngIf="badge.isCustom" class="icon"
					aria-hidden="true"
					focusable="false">
				<use [attr.xlink:href]="badge.badgeIcon" />
 			</svg>
			<svg *ngIf="!badge.isCustom"
					soho-icon
					[icon]="badge.badgeIcon">
			</svg>
		</div>`

**Comment by tmcconechy** [comment]
The reason its in two files is the first one is for the old theme and then the uplift one overrides it. To solve the issue your showing we usually put the elements in a toolbar... Or might be easiest to just a add a bit of css on your end for the placement. I think this changed could be risky since it effects every component. In the 5.0 this wont be an issue as we redid the icons in a component.

**Comment by karinpb** [comment]
Ok, yes I can override it, no problem.

**Comment by tmcconechy** [comment]
great sounds - good - then i will just close this knowing the next version will clean this problem out
