### ISSUE TITLE
Dropdown: Scroll bar creates dropdown option overflow in Classic themes

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#4940]
**Describe the bug**
For a dropdown that allows two digits (width of 54px) and in a classic theme, when there are enough dropdown options to have a scroll bar the options will have one digit and the start of an ellipsis as overflow. This issue does not occur with a new theme and the same dropdown sizing.

**To Reproduce**
1. Go to the attached html page
2. Select a new theme
3. Select the dropdown
4. Note that the two digit numbers appear
5. Select a classic theme
6. Select the dropdown
7. Note that the two digit numbers now have an overflow

[example-widths.zip](https://github.com/infor-design/enterprise/files/6125952/example-widths.zip)

**Expected behavior**
For a dropdown with a width large enough for two digits, that the options will appear without overflow in both the new and classic themes.

**Version**
- ids-enterprise: v4.38.0

**Screenshots**
Dropdown with a classic theme:
![Dropdown Classic Theme](https://user-images.githubusercontent.com/76002134/110855297-c6090400-827b-11eb-97af-bac7bafc1c27.PNG)

Dropdown with a new theme:
![Dropdown New Theme](https://user-images.githubusercontent.com/76002134/110855432-f486df00-827b-11eb-8ab2-3a48575411d8.PNG)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 89.0.4389.82 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
The problem is the uplift dropdown has a bigger font. So i think it will need to be wider to fit two characters.Maybe you can try not left aligning the text and seeing if you can use the "compact mode" one as it does have the smaller font size in that case. Also since the width is custom is supported you could try to adjust the width with css.

**Comment by s-werking** [comment]
Hi @tmcconechy,
I attached a new html to look at. The dropdowns that are this smaller size seem to adjust the sizing on opening the list if there is an overflow. This doesn't happen until there are at least 5 characters in an option. Could there be a change in adjusting the dropdown-list size for the cases that the dropdown-list has an overflow (2-4 characters)?
We need to keep the text left-aligned from a previous ticket we had. I tried adjusting the width with css, but since we have so many different cases of these right-aligned dropdowns, it broke cases where the width is much larger.
[test-short-field-with-scrollbar.zip](https://github.com/infor-design/enterprise/files/6131781/test-short-field-with-scrollbar.zip)

**Comment by tmcconechy** [comment]
We can probably do something to tweak the margins. So what do you want? 

a) make the top one align better and not change the width when open ? (these are options width and maxWidth that can control this) or...
b) make the top one open.

As i see it the left aligned padding is a little bit off....

**Comment by s-werking** [comment]
Yeah I think that making that left-aligned padding smaller or removing it would work well

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
