### ISSUE TITLE
range with no max

### ISSUE THREAD

**Issue by AsafMeirBarziv** [infor-design/enterprise#4945]
Can I use the range with no max?
e.g. ranges: [{'min': 0, 'classes': 'good'}]
Or perhaps there is another way of doing 'greater than'

**Comment by tmcconechy** [comment]
We dont have a way to do no max. But perhaps you can set min/max to very very high numbers to acheive this.

It might be easier to ask questions here:

https://teams.microsoft.com/l/team/19%3a2b0c9ce520b0481a9ce115f0ca4a326f%40thread.skype/conversations?groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&tenantId=457d5685-0467-4d05-b23b-8f817adda47c the issue tracker is mainly for bugs with reproductions and enhancement requests.

Also when raising issues please use the templates and fill out all information https://github.com/infor-design/enterprise/issues/new/choose

**Comment by tmcconechy** [comment]
Closing as the support question is answered (its not possible so just use a large number). You could also make a custom formatter if you rewally wantd

**Comment by AsafMeirBarziv** [comment]
OK - How can i join the teams? what login shall |I use?
בברכה,

אסף מאיר ברזיו
***@***.***
קיבוץ עין המפרץ
0524-281-872

**Comment by tmcconechy** [comment]
Are you in the Infor MS Teams? If so ping me directly your infor email address and i'll add you. (you use your infor email to login and can invite yourself as well)

**Comment by AsafMeirBarziv** [comment]
***@***.***
בברכה,

אסף מאיר ברזיו
***@***.***
קיבוץ עין המפרץ
0524-281-872

**Comment by tmcconechy** [comment]
hmm your email is unreadable as all stars. Are you an Infor employee ? If so reach out to me on email or ms teams.
if not try and email me at tim.mcconechy@infor.com

**Comment by tmcconechy** [comment]
ok i sent an inivite
