### ISSUE TITLE
Set default filter values on data grid

### ISSUE THREAD

**Issue by AsafMeirBarziv** [infor-design/enterprise#4946]
its not clear how to apply filter conditions on init - can you elaborate on that please?

e.g set Qty column filter to be greater than 0

**Comment by tmcconechy** [comment]
I'm afraid i dont understand this question. What do you want to do exactly? What did you try?

It might be easier to ask questions here:

https://teams.microsoft.com/l/team/19%3a2b0c9ce520b0481a9ce115f0ca4a326f%40thread.skype/conversations?groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&tenantId=457d5685-0467-4d05-b23b-8f817adda47c the issue tracker is mainly for bugs with reproductions and enhancement requests

**Comment by tmcconechy** [comment]
Actually rereading this i think i see what your looking for now. You want to use the applyFilter function and pass in the same data you would get in the event for example

https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-filter-applyfilter.html#L111

Or say if you wanted to set a qty filter greater than zero it would be
```
grid.applyFilter([{ columnId: 'productId', operator: 'greater-than', value: 0 }]);
```

**Comment by AsafMeirBarziv** [comment]
Yes great - it works - thanks.

BTW - why can't we have a complete reference with all of the properties ,
parameters, etc....
בברכה,

אסף מאיר ברזיו
***@***.***
קיבוץ עין המפרץ
0524-281-872

**Comment by tmcconechy** [comment]
@AsafMeirBarziv we do have this information on the design / docs site for example this is the docs for datagrid https://design.infor.com/code/ids-enterprise/latest/datagrid

We show settings, methods and events that are public. This is generated from jsdoc in the code

**Comment by AsafMeirBarziv** [comment]
I know this kind of doc - but it is very partial
for instance it never describe what is the format of parameters in the
applyFilter function
it was you that explained me how to use above mentioned function - why cant
we have a complete reference?


אסף מאיר ברזיו
***@***.***
קיבוץ עין המפרץ
0524-281-872

**Comment by tmcconechy** [comment]
Yes your right its missing some things we could add like the operators see here https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L2210 in the code.

Some of this is very dependant on your column data however. but maybe that helps. Will work to revamp this on a future version
