### ISSUE TITLE
Splitter: Inconsistent height for lower pane when zooming in and out.

### ISSUE THREAD

**Issue by SAIPRANAY-GANGULA** [infor-design/enterprise#4949]
**Describe the bug**
Splitter: Inconsistent height for lower pane when zooming in and out.

**To Reproduce**

1. Go to :  https://stackblitz.com/edit/splitter-issue
2. Set the zoom level of browser to 100%.
3. Refresh Browser.
4. Set the zoom level of browser to 50%.
5. Move splitter down and observe the issue.

**Expected behavior**
Lower pane height should be consistent.

**Version**

- ids-enterprise-ng :  9.0.0

**Screenshots**

![Screenshot (207)](https://user-images.githubusercontent.com/56952302/111258912-ee11b200-8643-11eb-9979-c85db32cd4fd.png)

**Comment by tmcconechy** [comment]
Descoping this work for now but we will rebuild the splitter then i think this will work ok. As of now its too difficult to justify a fix.
