### ISSUE TITLE
Datagrid: Issue when resizing first left column

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#4956]
**Describe the bug**
When resizing the left most column to exceed the viewport, when resizing it back the column resize to a certain width.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html
2. Resize the first left column up to the point that it exceeds the list viewport
3. Resize the column from step 2 to a smaller size, it gets resized automatically to a certain width which could confuse users. 

**Expected behavior**
The column resized should only be resize by the user.

**Version**
https://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html

**Screenshots**

![Column resize bug](https://user-images.githubusercontent.com/50192038/111447123-14207a80-8748-11eb-82dc-8378f6dee778.gif)

**Platform**
 - Infor Application/Team Name: M3 H5 UI Team
 - Device: Desktop
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Browser Version: Version 88.0.4324.190 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Slightly similar to https://github.com/infor-design/enterprise/issues/4900 but this may ve very challenging to fix with out the re-architecting the datagrid (i.e. should may be fixed in 5.0 web components)

**Comment by tmcconechy** [comment]
We will fix this in the web component version by rewriting the logic but will close this to the archive for now
