### ISSUE TITLE
Dropdown: When you use search to filter, arrows keys are not working properly

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#4958]
**Describe the bug**
When you use search to filter, arrows keys are not working properly.

**To Reproduce**

1. Go to url: https://master-enterprise.demo.design.infor.com/components/dropdown/example-virtual-scroll.html
2. Click on the drop down
3. Type to search, Input MON
4. Press up/down arrow keys
5. when you use search to filter, arrows keys are not working properly.

**Expected behavior**
The arrow up and arrow down key should work

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.39.0]

**Screenshots**
None

**Platform**
 - All Browser 
**Additional context**
None

**Comment by tmcconechy** [comment]
Descoping some older issues
