### ISSUE TITLE
Additional Functional, E2E Test For Block Grid 

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#496]
**Is your feature request related to a problem? Please describe.**
Additional E2E Test For Block Grid to cover accessibility and block gird paging component. 

**Describe the solution you'd like**
A MS Word document is attached to this GutHub ticket covering all the E2E functionality that is needed  

**Describe alternatives you've considered**
MS Word document attached. 

**Additional context**
[Block Grid Test Case.docx](https://github.com/infor-design/enterprise/files/2228549/Block.Grid.Test.Case.docx)

**Block Grid Test Case**
blockgrid/example-mixed-selection
- [ ] Tab in
- [ ] Space will active that box (not select)
- [ ] Tab again to checkbox
- [ ] Space (this will select)
- [x] The box is activated, and the checkbox is selected
- [x] Verify that a user can navigate from page one to page two using your keyboard
- [x] Verify that the user checks of one grid on the first page then navigates to the second page then navigates back to the first page and that the grid that was checked off is still checked off
- [x] Verify that the user is able to navigate using the “Click” action using a mouse
- [x] Verify that the grid appears correctly on “Responsive” view
- [ ] Verify the user is able to make check marker box selection on responsive view

**Hard to Automate**
- [ ] Verify that a scroll bar appears when the grid is in responsive view
- [ ] Verify track sizing and minmax and also ensure they expand to fit any content this is added

**Functional**
- [x] Various parts of the Blockgrid are not covered as well. Cover those as well. https://design.infor.com/code/ids-enterprise/latest/blockgrid

**?**
Spacebar doesn't seem to work
- [ ] Verify that all Block grids e2e test cover Tab, Spacebar, or Enter key for selection of any grid

**Comment by tmcconechy** [comment]
For when you have time (sprint items take precedence so that might be next sprint if you dont get to it until after)

**Comment by tmcconechy** [comment]
This was addressed by PR's
