### ISSUE TITLE
Datagrid: Bottom scroll bar is cut off in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4961]
**Describe the bug**
Datagrid: Bottom scroll bar is cut off in responsive view

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-index.html
2. Minimize the screen to see the scroll bar

**Expected behavior**
Bottom scroll bar should not be cut off

**Version**
4.390-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/111625787-38ec1f00-8828-11eb-9a2a-eae6cc56350f.png)

**Platform**
All major OS & browsers. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Going to go ahead and descope this right away. There really isn't anything we can do about this as the example has a fixed height some other examples will resize with the page like https://master-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html
