### ISSUE TITLE
Datagrid: Expand button animation is cut off

### ISSUE THREAD

**Issue by arturchilangwa-infor** [infor-design/enterprise#4962]
**Description**
An animation cut off when clicking on the "expand-button" (plus or minus sign) on a SohoDataGrid that is multiselectable. This happens only if the row is selected.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-expandable-row-multiselect.html
  
2. Select/check a row first so it has a blue background
  
3. Press on the button that expands row (the animation cut off will appear here)
  

**Expected behavior**
The animation for "expand-button" should be a whole circle with no oddity to the animtaion

**Version**
- ids-enterprise-ng: v4.38.0

**Screenshots**
*Animation cut off* 
![animation-cut-off2](https://user-images.githubusercontent.com/80833325/111480474-5939b200-8732-11eb-9e2c-f8d2d2e20a2c.gif)

*Animation cut off close up* 
![animation-cutoff_closeup](https://user-images.githubusercontent.com/80833325/111481425-3eb40880-8733-11eb-8945-213012141b91.gif)

Potential element that produces the error

**Platform**
- Device: Desktop
- OS Version: Windows 10
- Browser Name: Chrome
- Browser Version: 88.0.4324.190 (Official Build) (64-bit)

**Additional context**
*The potential element that makes bug.*
![animation-cut-off-with-inspector](https://user-images.githubusercontent.com/80833325/111480496-5e96fc80-8732-11eb-8c62-7952b879d9e0.png)

The element is the `<span class="icon plus-minus"></span>` inside of the button-element.  
```html
<div class="datagrid-cell-wrapper">
    <button type="button" aria-label="Expand / Collapse" class="btn-icon datagrid-expand-btn hide-focus" tabindex="-1">
        <span class="icon plus-minus"></span>
    </button>
    <span> 2142201</span>
</div> 
```

**Comment by jbrcna** [comment]
QA Passed
The animation for "expand-button" is now  a whole circle with no oddity to the animtaion (both selected/unselected)
v4.52.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-expandable-row-multiselect.html
