### ISSUE TITLE
Circle: Circle pager not working correctly on Android

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#4966]
**Describe the bug**
Report two issues in one ticket. 
https://master-enterprise.demo.design.infor.com/components/circlepager/example-index.html – on first load, try navigating by clicking the circles. it's not moving to the next item. Clicking Next or Prev button is working as expected. 

https://master-enterprise.demo.design.infor.com/components/circlepager/example-tabs.html – this one is broken in uplift. Soho is fine

**To Reproduce**

Report two issues in one ticket. 
https://master-enterprise.demo.design.infor.com/components/circlepager/example-index.html – on first load, try navigating by clicking the circles. it's not moving to the next item. Clicking Next or Prev button is working as expected. 

https://master-enterprise.demo.design.infor.com/components/circlepager/example-tabs.html – this one is broken in uplift. Soho is fine

**Expected behavior**
The circle pager should be working as expected. 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
None

**Platform**
 - Devices: [e.g. Android]

**Additional context**
None

**Comment by ericangeles** [comment]
Hi @CindyMercadoReyes what was the specific issue in https://master-enterprise.demo.design.infor.com/components/circlepager/example-tabs.html?

What I am seeing are the issues on dropdown caret icon

<img width="386" alt="Screen Shot 2021-03-29 at 6 02 53 PM" src="https://user-images.githubusercontent.com/8839327/112821242-07d9dd00-90b9-11eb-8592-0c21e229f4b8.png">
<img width="168" alt="Screen Shot 2021-03-29 at 6 02 36 PM" src="https://user-images.githubusercontent.com/8839327/112821256-0a3c3700-90b9-11eb-877b-2cb35d2f4f8a.png">

**Comment by ericangeles** [comment]
> @eric i fixed the popup issue here (separate issue) #5008
> Are you not able to reproduce the steps here?

Haven't seen your PR. Let me look at it. Thanks, @tmcconechy 👍🏼

**Comment by jbrcna** [comment]
**QA Passed** 
this is working as expected using a `real device`. just noting some observations when using Browserstack. kindly see screenshot for reference

https://main-enterprise.demo.design.infor.com/components/circlepager/example-index.html - No circle buttons
_Samsung Galaxy S21 Browserstack_
![image](https://user-images.githubusercontent.com/56722184/114670762-f12cba80-9d35-11eb-91b9-21a01fc5707a.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
