### ISSUE TITLE
Pie: Custom chart legend

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#4968]
**Is your feature request related to a problem or use case? Please describe.**
A customizable function that can be used to generate a chart legend. This is so a total can be added to both a pie, column, bar (non-stacked). There looks like there was a function but it no longer works. 

https://master-enterprise.demo.design.infor.com/components/pie/test-legend-formatter.html

**Describe the solution you'd like**
a way to override the charts.addLegend function via a setting on the chart. I believe that is what the legendFormatter was intended.

**Describe alternatives you've considered**
Looked at using legendFormatter, but is does not work, for a pie chart add an additional data row with 0 value, but this would not work for a bar.

**Additional context**
The total item is also there, so that the user can drill through to all of the records in the chart instead. The other legend items are user to drill through to a filtered list.

![image](https://user-images.githubusercontent.com/39749678/111723576-aee99800-88b3-11eb-9f43-56add8b60ac0.png)

**Comment by tmcconechy** [comment]
Yes i think legendFormatter should be running. It was the idea here. Im  not against a new setting but in the example mentined its not firing. So i think we should fix that.

Will that work?

**Comment by marknolaninfor** [comment]
@tmcconechy, Yes if legendFormatter work as in the example, so one process to generate the whole legend and not one per series, as it looks like it has been modified from the original example.

legendFormatter may have changed how it works from the example page, as it is used to format a legend item's name.

line 286 of pie.js          name = `${d.name} (${d3.format(s.legendFormatter)(d.value)})`;

**Comment by tmcconechy** [comment]
Ok thanks. I didn't dig far into this. I think we might have done that to just format the text so maybe we do need a second option for full legend configuration.
