### ISSUE TITLE
DataGrid: Documention for saving pagesize is wrong

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#4969]
IDS version: 4.37.2

In the web site documentation, it says the following is required to save the datagrid page size value into local storage...

![image](https://user-images.githubusercontent.com/44396995/111757575-61f5c980-8893-11eb-9e38-6ee20a75cd20.png)

...but this does not work, and looking in the code, the settings value being checked is "pagesize" not "pageSize"...

![image](https://user-images.githubusercontent.com/44396995/111757852-af723680-8893-11eb-8c6b-f7549aeae9ac.png)

Either code or documentation needs to be changed to be consistent.

**Comment by tmcconechy** [comment]
Note that this is working on https://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings-serverside.html
- change the page size in the bottom dropdown
- reload the page

So just went ahead and updated the docs
