### ISSUE TITLE
Datagrid: Issue with entering decimal number with Editors.Input using maskOptions

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#4974]
Describe the bug
Attempting to enter a decimal value into a cell with Editors.Input and with maskOptions noticed...
- if the cell is empty, entering '.25' will work
- if the cell already has a value, entering '.25', you need to either enter the decimal point twice '..25' or enter '0.25'. 

1. Using the attached 'test-decimal-maskoptions.html'
2. Set focus in Price cell of Row Id: 0 (has a value of 210.99)
3. Enter '.25' => need to enter the decimal point '.' twice or enter '0.25'
4. Set focus in the Price cell of Row Id: 3 (has no value)
5. Enter '.25' => takes the value has entered (don't need enter the decimal point '.' twice of enter the leading zero

Expected Behavior
Entering a decimal value shouldn't need to enter the decimal point twice or enter leading 0.25

Version
v4.39.0-dev

**Comment by tmcconechy** [comment]
Probably an issue with mask. Css @EdwardCoyle

**Comment by claudenbach** [comment]
[Git-4974.zip](https://github.com/infor-design/enterprise/files/6173573/Git-4974.zip)

**Comment by claudenbach** [comment]
Has this been planned for a sprint?  The client associated with the LMCLIENT ticket is asking for updates.

**Comment by tmcconechy** [comment]
Put in June sprint for now..

**Comment by tmcconechy** [comment]
@EdwardCoyle we will need to prioritize this one for landmark. Maybe it's easy (i hope). Probably have to make sure it works in the new code brought over.

**Comment by claudenbach** [comment]
Seeing this same behavior on a numeric field that resides on a form.

- if the field is empty, entering '.25' will work
- however, if the field already has a value, entering '.25', you need to either enter the decimal point twice '..25' or enter '0.25'.

![Form-Example](https://user-images.githubusercontent.com/39804038/116900092-f88d0880-abfd-11eb-93e2-df430ed5d9af.gif)

**Comment by tmcconechy** [comment]
Yes that makes sense as i would expect this to be an issue in any mask...

**Comment by jbrcna** [comment]
the issue is now resolved. moving this ticket to Done.
v4.52.0-dev
https://main-enterprise.demo.design.infor.com/components/mask/test-number-leading-zeroes.html

**Comment by CindyMercadoReyes** [comment]
The BDD and accessibility test case has been created for this ticket. This component will be part of our regression test suite. 
[BDDStory_github4974.docx](https://github.com/infor-design/enterprise/files/6585330/BDDStory_github4974.docx)
[TCs_Mask_LeadingZeroesinNumberMasks_V01.xlsx](https://github.com/infor-design/enterprise/files/6585331/TCs_Mask_LeadingZeroesinNumberMasks_V01.xlsx)
