### ISSUE TITLE
TextArea: Autogrow doesn't work inside an accordion panel

### ISSUE THREAD

**Issue by StaciGreen** [infor-design/enterprise#4977]
**Describe the bug**
When using a soho-textarea inside a soho-accordian-pane, autogrow is ignored. It does not grow and it does not show scrollbar depending on the if max is set.
[textarea.zip](https://github.com/infor-design/enterprise-ng/files/4961002/textarea.zip)

**To Reproduce**
1. Add attached example files to demo app.
2. Scroll down to T menu item.
3. Click T.
4. Scroll Down and select Textarea Forms demo.
5. Open Warehouse Location panel.

**Expected behavior**
The grow (Infiinite) in panel should be the same size as the grow (infinite) farther down the page.
The grow (finite) in panel should have vertical scroll bar same as grow (finite) farther down the page.

**Version**
- ids-enterprise-ng: 7.4.1

**Screenshots**

![image](https://user-images.githubusercontent.com/50175666/88199019-583b9980-cc12-11ea-9103-ee36df2c212d.png)

**Platform**
 - Device (if applicable) Windows PC
 - OS Version:  Windows 10 
 - Browser Name Chrome
 - Browser Version Version 84.0.4147.89 (Official Build) (64-bit)

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
v4.39.0-dev
https://master-enterprise.demo.design.infor.com/components/accordion/test-textarea-inside-of-accordion.html
