### ISSUE TITLE
Datagrid: TreeGrid Data is duplicated and checkbox dont work

### ISSUE THREAD

**Issue by Varalaxmi26** [infor-design/enterprise#4979]
**Describe the bug**
Data was duplicated while updating the row in Tree SohoDataGridComponent using updateRow(). While updating the child rows with index, instead of updating the corresponding row/children new row is adding to the data set. 

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-910-xtnbq9
1. Issue 1: Select the checkbox column in the first/parent row and try to click the children. Again try to unselect the checkbox. Not able to unselect that check box. 
2. Issue 2: Change the row height from actions menu. Observe that some data was duplicated. New updated data was displaying at the end of the tree grid.

**Expected behavior**
Data should not be duplicated. Correct child row data should be updated instead of adding new one to the data set. Checkbox should be selectable in the first row.

**Version**
See on on current version 9.3, 9.1.1 and any version later than 7.5.3

**Screenshots**
![image](https://user-images.githubusercontent.com/59650265/112112229-4401cf00-8bdb-11eb-814e-9aad0c887017.png)

**Comment by Varalaxmi26** [comment]
is there any update on this bug?

**Comment by Varalaxmi26** [comment]
This issue is reproducing with the latest version also. 

With the older versions 7.5.3 it is working fine.  We didn't made any specific changes after this version also. This was worked fine in older version.
Not performing any operations while changing the row height.

We are updating the data when we click on check box cell by making a call for onCellChange(). In this cell change event calling treeGridComponent.updateRow() method. The grid data was duplicated when ever called the datagrid.updaterow() method.  Due to this the grid data indexes got changed, so can't able to select the parent check box. 

The updateRow() method internal implementation got changed in the later versions. May be there is some issue in updaterow() of SohoDataGrid.

Thanks

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by aparimalla** [comment]
Please let us know on which version this issue got fixed.

**Comment by ericangeles** [comment]
@aparimalla it's in `4.66.0`

**Comment by aparimalla** [comment]
Thank you @ericangeles
