### ISSUE TITLE
Datagrid: Search field looks cut off after switching to responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4980]
**Describe the bug**
Datagrid: Search field looks cut off after switching to responsive view

**To Reproduce**

1. https://master-enterprise.demo.design.infor.com/components/datagrid/example-singleselect.html?theme=new&mode=light&colors=0066D4
2. Open & focus on the search field 
3. Switch to responsive view & minimize the screen
4. See error search fields looks cut off

**Expected behavior**
Search field should be responsive and not look cut off

**Version**
4.390 - dev

**Screenshots**

![image](https://user-images.githubusercontent.com/45757016/112139264-880dc780-8c0d-11eb-8a26-4ee2c3444db7.png)

**Platform**
All major browsers and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
@janahintal not clear on this step "Switch to responsive view & minimize the screen" - i tried what i think you mean but wasnt able to replicate. Can you provide more details?

**Comment by tmcconechy** [comment]
Descoping for now
