### ISSUE TITLE
Field Filter: short is off in Uplift

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#4982]
**Describe the bug**

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/field-filter/example-short.html
2. See error
4. Notice that UI  is a bit off

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/112152831-aaa7dc80-8c1d-11eb-9ed2-74d83ea26e0b.png)

**Version**
- ids-enterprise: v4.29.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/112152778-9d8aed80-8c1d-11eb-96a6-b265827e0aa6.png)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Yes looks like the uplift theme is a little bit off.
1. Missing a border
2. And the focus state is only partly working covering the center
3. When you open the list it is too long for the field.

**Comment by jbrcna** [comment]
issue is now resolved. v4.39.0-dev
https://master-enterprise.demo.design.infor.com/components/field-filter/example-short.html
![image](https://user-images.githubusercontent.com/56722184/113104355-02080700-9233-11eb-8137-881d9061bac5.png)
