### ISSUE TITLE
Datepicker: Time picker portion not working properly in Danish language

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#4987]
**Describe the bug**
Showing incorrect time in Time and date picker control.

**To Reproduce**

1. go to https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=da-DK
2. select date in "Date Time Picker in Locale (Time to Current)" and set time as "11.25" and click ok
3. now click anywhere on the page
4. the time in datetime control changes to "23.25"

**Expected behavior**
It should show time user have selected. 

**Version**

- https://master-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=da-DK

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Some related issues:
https://github.com/infor-design/enterprise/issues/4964
https://github.com/infor-design/enterprise/issues/4926

**Comment by jbrcna** [comment]
The issue is now resolved. v4.51.0-dev
https://main-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html?locale=da-DK
![image](https://user-images.githubusercontent.com/56722184/115840893-c38af400-a44e-11eb-93e6-a8a899e7bcf4.png)
