### ISSUE TITLE
WC-PopupMenu: Submenus do not open to the left when on the far right

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#4990]
**Describe the bug**
Still need some updates to the new popupmenu so it can be used on the right aligned toolbars/theme switcher

**To Reproduce**
1. Go to http://localhost:4300/ids-toolbar
2. Open the .. menu
3. Open the sub menu

**Expected behavior**
Should in this case open the menus towards the left.

**Screenshots**
![image](https://user-images.githubusercontent.com/814283/112322235-1d00d700-8c87-11eb-8ce3-df6d3d0fd01e.png)

**Additional context**
https://github.com/infor-design/enterprise-wc/pull/52

**Comment by tmcconechy** [comment]
Duplicate of https://github.com/infor-design/enterprise/issues/5038 ?

**Comment by katieinfor** [comment]
Closed issue (April Sprint Meeting)
