### ISSUE TITLE
W10: certain npm commands which reference directories in quotes cannot be run

### ISSUE THREAD

**Issue by rob2d** [infor-design/enterprise#4993]
**Describe the bug**
Cannot currently run commands such as `npm run stylelint` on a Windows PC. This is a very simple issue to fix as there are no spaces in our globs, but as it was mentioned that one goal was to make it easier for Windows users in the org to spin things up, figured to post this while it is top of mind before heading out today.

**To Reproduce**

1. Open repo
2. Run `npm run stylelint`
3. Output will be as follows
```
${MYDIR}\enterprise>npm run stylelint

> ids-enterprise@4.39.0-dev stylelint
> npm run stylelint:demo && npm run stylelint:src

> ids-enterprise@4.39.0-dev stylelint:demo
> npx stylelint app/src/**/*.scss --config src/.stylelintrc

> ids-enterprise@4.39.0-dev stylelint:src
> npx stylelint './src/**/*.scss --config src/.stylelintrc

Error: No files matching the pattern "'./src/**/*.scss" were found.
    at ${MYDIR}\enterprise\node_modules\stylelint\lib\standalone.js:212:12
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Expected behavior**
Running `npm run stylelint` should simply run the command specified with no errors to perform linting.

**Version**

- ids-enterprise: 4.39.0-dev

**Platform**
 - Infor Application/Team Name: Infor IDS
 - Device: PC
 - OS Version: Windows 10 Pro v10.0.18362
 - Browser Name: N/A
 - Browser Version: N/A

**Additional context**
It's possible to get around this by simply using WSL2 or Cygwin, but purposely not running those initially today to test scenarios for users of repo as WSL2 requires several steps by IT department for installation, and Cygwin is external dep. Dogfooding to vet issues.

**Comment by tmcconechy** [comment]
thanks @rob2d feel free to push a fix
