### ISSUE TITLE
Datagrid: Overlapping popdown modal

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#4994]
**Describe the bug**
Datagrid: Overlapping popdown modal

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
2. Open the calendar button in Order Date
3. Open the filter in Order date very quickly 
4.  Repeat steps 2-1 until issue is reproduce

**Expected behavior**
Popdown should not overlap

**Version**
4.390 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/112452444-984eaf80-8d91-11eb-8fca-ec915f39dbfe.png)

**Platform**
All major browsers & devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Maybe caused by a timeout. Possibly fix with https://github.com/infor-design/enterprise/issues/4995

**Comment by tmcconechy** [comment]
Descoping for now
