### ISSUE TITLE
Listview: Lacking listview heading hierarchy for theme-new

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise#4996]
**Describe the bug**
Listview headings font-sizes are all the same (1.6rem) in theme-new compared to theme-classic which has `.listview-micro` and `.listview-subheading` font-size 1.2rem (whereas the `.listview-heading` has 1.4rem).

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/listview/example-index.html
2. Compare Theme Classic to Theme New

**Expected behavior**
There should be a hierarchy for heading, subheading and micro.

**Version**
- ids-enterprise: v4.38.1

**Screenshots**
Theme Classic
![Screenshot 2021-03-25 at 14 25 39](https://user-images.githubusercontent.com/73601152/112480119-fbcae400-8d75-11eb-8fb5-b70a15e04f50.png)

Theme New
![Screenshot 2021-03-25 at 14 26 12](https://user-images.githubusercontent.com/73601152/112480194-100ee100-8d76-11eb-8b7c-e15448c73c6a.png)

**Platform**
 - n/a

**Comment by katieinfor** [comment]
Will send to Design for input

**Comment by katieinfor** [comment]
Ticket created for Design: https://jira.infor.com/browse/UXD-2348

**Comment by tmcconechy** [comment]
Proposal from the design ticket is 

![image](https://user-images.githubusercontent.com/814283/134060240-f2a0d260-4026-4061-b099-e1a6ae9edef1.png)

```
Title: 24pt Slate 10

Task: 16pt Slate 10

Subtext: 16pt Slate 6
```

**Comment by GlenlieMaye** [comment]
QA tested and passed. Moving this ticket to done.

_New Version_
![image](https://user-images.githubusercontent.com/102151352/163765769-e65b059e-b9a3-4f05-8ff8-d4bf9d17121b.png)

_Classic Version_
![image](https://user-images.githubusercontent.com/102151352/163765867-4b8d859b-ab99-4e21-84fd-9c639d7c0b4b.png)
