### ISSUE TITLE
Autocomplete doesn't have "Show More" in the bottom result list

### ISSUE THREAD

**Issue by allanalvarez** [infor-design/enterprise#500]
**Is your feature request related to a problem? Please describe.**
http://usalvlhlpool1.infor.com/4.3.4/components/autocomplete
- I think in older version autocomplete have "Show More" in the bottom of the results list.

**Describe the solution you'd like**
It would be nice if we have configuration something switch on/off of the Show more link in the bottom of the results

**Describe alternatives you've considered**

**Additional context**

**Comment by tmcconechy** [comment]
I dont think we ever had a "Show More" Link. But we have a no more results text...

http://master-enterprise.demo.design.infor.com/components/searchfield/example-no-all-results-link.html

Is that what you mean?

**Comment by tmcconechy** [comment]
Ok i see what i think your looking for its on searchfield not autocomplete.

- see http://master-enterprise.demo.design.infor.com/components/searchfield/example-index.html
- type i
- there is a showAllResults link.
- this is controlled by setting showAllResults on searchfield

**Comment by allanalvarez** [comment]
Hi @tmcconechy 

Thanks for the recommendation.  As far as I remember the search field we had in old version is containing "Show More" (See image below).   Is that something we remove already or something customizable? 

![image](https://user-images.githubusercontent.com/41406875/43298857-79cd48ce-918a-11e8-9ca1-89b0f673bf7f.png)

![image](https://user-images.githubusercontent.com/41406875/43298839-585d687c-918a-11e8-8a5c-244e2c922bec.png)

**Comment by tmcconechy** [comment]
I think we just had the example http://master-enterprise.demo.design.infor.com/components/searchfield/example-index.html

Maybe your team implemented something with it by making the last item as "Show More". But i dont see any history about this feature.
