### ISSUE TITLE
Editor: Creating clickable links doesn’t give you a clickable link instead it shows a non-clickable link.

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#5001]
**Describe the bug**
 In Mac OS Safari, creating clickable links doesn’t give you a clickable link instead it shows a non-clickable link. Both "New Window" and "Same Window" doesn’t work. Try also in Mac Big Sur.

**To Reproduce**

1. Go to editor/example-clickable-links.html
2. In Mac OS Safari, creating clickable links doesn’t give you a clickable link instead it shows a non-clickable link. Both "New Window" and "Same Window" doesn’t work. Try also in Mac Big Sur.

**Expected behavior**
Creating clickable links should give you the clickable links

**Version**

- ids-enterprise: [v4.39.0]

**Screenshots**
![Picture1](https://user-images.githubusercontent.com/39101346/112525911-c1fadd00-8d77-11eb-8df6-6b1421349f4f.png)
![Picture1](https://user-images.githubusercontent.com/39101346/112525997-d6d77080-8d77-11eb-9e6c-b8605130499a.png)

**Platform**
 - OS Version: [iOS 8]
 - Browser Name: [Safari]
 - Browser Version: [14]

**Additional context**
none

**Comment by davidcarlsonberg** [comment]
Unable to reproduce in latest Safari on Mac Monterey
<img width="1120" alt="Screen Shot 2022-04-27 at 8 31 11 PM" src="https://user-images.githubusercontent.com/7952168/165652899-d0553ad5-68dd-40a0-a6a9-a7e60a59af95.png">
.

**Comment by tmcconechy** [comment]
ok lets kick this over to QA to confirm

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
