### ISSUE TITLE
Popdown: Modal grid is cut off on first page load

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5007]
**Describe the bug**
Popdown: Modal grid is cut off on first page load

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/popdown/example-index.html
2. Click My Cart right ayaw
3. Notice that the popdown grid is cut off
4. Close & open the popdown again, notice that the popdown is now okay 

**Expected behavior**

**Version**
4.390 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/112629532-69a70680-8e6f-11eb-9337-5705acf3ad72.png)
![image](https://user-images.githubusercontent.com/45757016/112629857-c4d8f900-8e6f-11eb-915f-4a69bd15ece6.png)

![image](https://user-images.githubusercontent.com/45757016/112629902-d91cf600-8e6f-11eb-8739-0c420c74515a.png)
![image](https://user-images.githubusercontent.com/45757016/112629912-dcb07d00-8e6f-11eb-8fc8-6bff82808771.png)

**Platform**
All major browsers

**Additional context**
N/a

**Comment by tmcconechy** [comment]
@janahintal - im not seeing this on my end...

![Screen Shot 2021-03-26 at 8 50 54 AM](https://user-images.githubusercontent.com/814283/112633999-6df00700-8e10-11eb-975d-fc3cd7071165.png)

**Comment by tmcconechy** [comment]
Descoping for now
