### ISSUE TITLE
Lookup: clientside paging filter issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5010]
**Describe the bug**
the filter menu have extra arrows and  unable to change filter type after you select a certain filter

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/lookup/example-clientside-paging-with-filtering.html
2. Open Lookup
3. Open any filter
5. Notice the extra arrow
6. Enter 1 on Quantity to search
7. Change filter to any (e.g., does not equal)
8. Change filter again
9. See error
10. Filter won't open. unable to change filter type
11. Try to play around with column filters

**Expected behavior**
should be able to filter without any issues

**Version**
- ids-enterprise: v4.39.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/112799778-67c48980-90a1-11eb-974a-4268cf4ec3ea.png)

**Platform**
all browser

**Additional context**
see also https://master-enterprise.demo.design.infor.com/components/lookup/example-custom-toolbar.html
![image](https://user-images.githubusercontent.com/56722184/112801479-875cb180-90a3-11eb-86c6-9416917bfa1b.png)

**Comment by tmcconechy** [comment]
Noticed this as well and fixed it on this PR https://github.com/infor-design/enterprise/pull/5008

**Comment by jbrcna** [comment]
QA Passed
v4.39.0-dev
[lookup/example-clientside-paging-with-filtering](https://master-enterprise.demo.design.infor.com/components/lookup/example-clientside-paging-with-filtering.html)
![image](https://user-images.githubusercontent.com/56722184/113105236-f49f4c80-9233-11eb-889f-23ba882c6065.png)

[lookup/example-custom-toolbar](https://master-enterprise.demo.design.infor.com/components/lookup/example-custom-toolbar.html)
![image](https://user-images.githubusercontent.com/56722184/113104897-9a05f080-9233-11eb-8c93-600196d21dfe.png)
