### ISSUE TITLE
IDS App Menu — Component should have a close icon

### ISSUE THREAD

**Issue by katieinfor** [infor-design/enterprise#5013]
**Is your feature request related to a problem or use case? Please describe.**
Makes sense to have the 'close X' icon as the active state at least as an option, if not the only way the menu works.

**Describe the solution you'd like**
Makes sense to have the 'close X' icon as the active state. 

**Describe alternatives you've considered**
 If not available, the way the menu works now could be a fallback. 
**Additional context**
https://user-images.githubusercontent.com/81309537/112889019-1917ef00-90a3-11eb-832b-3322be9a62a1.mov

**Comment by tmcconechy** [comment]
hi @katieinfor - what do you mean by "active state". But what i can tell you there is some history here so now its not an X at all anymore. 

https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html

The HR system has a version where we release it with an X... And it got very bad feedback/ was confusing / customers didnt like the change so it was changed back on newer versions:

History:
- we had an older design that might have had an x for close state
- for a very long time 20+ it was just the same icon
- we changed it to an X
- no one liked the x so we reverted it https://github.com/infor-design/enterprise/issues/4756

HR will take a while to reflect this though. Given that its no longer an X at all I think this is a non issue?

**Comment by katieinfor** [comment]
Thanks for the context! Can you please put this in response in Jira as well? Here's the ticket: https://jira.infor.com/browse/UXD-2272

**Comment by tmcconechy** [comment]
Done. Will close this. I think we "cant" change this. It was very unpopular.
