### ISSUE TITLE
Data Grid Component: Alignment not correctly aligned for BOD sorting button

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#502]
**Describe the bug**
[All browsers] Data Grid Component: Alignment not correctly aligned for BOD sorting button

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/test-rtl-text.html?locale=ar-SA'
2. Click on the "BOD sorting button
3. Across all browsers and devices the button is misaligned 
4. Please see screen shot attached

**Expected behavior**
All sort buttons on the data grid should be aligned correctly

**Screenshots**
![bs_win10_ie_11 0 1](https://user-images.githubusercontent.com/39101346/43274705-e87b6070-90cd-11e8-9d07-a0b0ed0a1c6e.jpg)

**Platform**
 - All Browsers

**Additional context**
This issue is related to jira: https://jira.infor.com/browse/SOHO-6410

**Comment by tmcconechy** [comment]
Seems to be loading for me. No problems on any of those.. Can you try again?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. However, a new issue was created while conducting testing on this issue. GitHib ticket https://github.com/infor-design/enterprise/issues/814 has been created. Thanks, Cindy
