### ISSUE TITLE
WC: Add ids-wizard component

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5026]
**Describe the bug**

Bring over the current "wizard" component.  See if we can simplify and improve the code and improve as we go. Current wizard component https://master-enterprise.demo.design.infor.com/components/wizard

Rough idea for an API

```
<ids-wizard >
 <ids-wizard-step completed="true" id="step-one" data-automation-id="d1">Step One</ids-wizard-step>
 <ids-wizard-step completed="true" id="step-two">Step Two</ids-wizard-step>
 <ids-wizard-step current="true"  id="step-three">Step Three</ids-wizard-step>
 <ids-wizard-step clickable="false">Step Five</ids-wizard-step>
 <ids-wizard-step>Step Four</ids-wizard-step>
</ids-wizard>
```

- I think the steps should be ids-hyperlinks in the shadow root (if clickable true which should be the default) else its a span
- should flow to 100% parent
- try and use css grid or flex to align
- api to set the step no making all previous completed (we had been using `value(index)`

**Functionality to bring over**
- clickable option
- add short labels option https://master-enterprise.demo.design.infor.com/components/wizard/test-shortlabels.html for responsive sizes to make the labels smaller
- add events for clicking the steps (selected and clicked event)
- scour over the wizard code for anything i missed such as public methods and events or settings
- left off the ellipsis feature - will do this as a separate component (maybe in ids-text_ so its more automatic
- one gap is we have no containers under that change when changing step and showing contents - for version 2 we could try to do that but maybe not first draft

**Additional context**
- 100% test coverage
- DOCS, CHANGE log ect. 
- https://github.com/infor-design/enterprise-wc/blob/master/doc/CHECKLIST.MD
- themes 

See components like card, tag, badge, hyperlink  as reference and it it similar ways.

**Comment by rob2d** [comment]
Was just roughly iterating on the API and for simplification of the API seems it could be:

```html
<ids-wizard step=3 id="my-wizard">
  <ids-wizard-step>Step One</ids-wizard-step>
  <ids-wizard-step>Step Two</ids-wizard-step>
  <ids-wizard-step>Step Three</ids-wizard-step>
  <ids-wizard-step clickable="false">Step Four</ids-wizard-step>
  <ids-wizard-step>Step Five</ids-wizard-step>
</ids-wizard>
```

This way there's no programmatic need for the user to inject the current step; the only thing they are focused on is inner content of an `ids-wizard-step` and whether they are clickable or not. 

Internally the component could just store an array for refs -- but if it was expressed for the sake of being able to query or grabbing that specific element's `innerHTML`, they could always query the element with standard `nth-child` i.e. `$('#my-wizard ids-wizard-step:nth-child(3)')`?

**Comment by tmcconechy** [comment]
Sure that works. I like it step is fine for a name but could also be value=“3” as some overs use that

**Comment by rob2d** [comment]
@tmcconechy that's also a good suggestion. 

I am subjectively leaning towards `step` just initially, because: 
- it seems `value` can be 0-based or 1-based, or strings as well.
- currently `step` just infers the step # from our components and we don't allow a user to specify arbitrary `value` in the spec. But this could also be cool? e.g.

```
<ids-wizard step="tally" id="my-wizard">
  <ids-wizard-step value="voting">Voting Occurring</ids-wizard-step>
  <ids-wizard-step value="tally">Tallying Results</ids-wizard-step>
  <ids-wizard-step value="decision">Decision Made</ids-wizard-step>
</ids-wizard>
```

The above would be similar to tabs or dropdown in some libraries. 

But with the step number inferring the position in current behavior/being simple, it seems `step` models that behavior a little bit more unambiguously. Any input on whether that logic seems ok or not appreciated.

**Comment by tmcconechy** [comment]
Step sounds good. I was 50/50 on that suggestion.

**Comment by rob2d** [comment]
Just a heads up/update that the WIP branch was/is being rebased onto infor-design/enterprise-wc#56 which it depends on for `ids-text` attribs, so no need to merge while WIP (e.g. would increase likelihood of merge problems and should already be in sync w master otherwise as things are going).

**Comment by rob2d** [comment]
![ids-wizard-wc-example](https://user-images.githubusercontent.com/1799905/113947316-664d3c80-97d8-11eb-9311-1ef76373c85d.gif)

So far have the general component attribs/reflecting the component and markup (testing with ids-text changes); without any js measurement/pure CSS-flexbox was a little tricky but I think it looks ok now.

@tmcconechy can address your feedback tomorrow on the  infor-design/enterprise-wc#56 PR and then will be able to continue on this, thanks on that.

**Comment by tmcconechy** [comment]
Ok thanks - if flex or css grid doesn’t work out here that’s no so important so just do what you have to to make it work properly

**Comment by rob2d** [comment]
The component is about ready for initial PR/iteration, outside of one thing which is a documentation md.

Tried to rebase to update before writing a PR, but really messy to keep branches in decent state with, and it's honestly impossible to avoid unknown changes with this much branching/ad-hoc merge in two directions. Spent a lot of time to sort this out and I think that could be avoidable on day-to-day from past experiences... but in the meantime will just start again by creating a new branch w diffs for PR tomorrow.

**Comment by tmcconechy** [comment]
Ok if it’s easier to not rebase, just don’t. We don’t have that requirement in our system of working right now. The last merge had a months work in it.
