### ISSUE TITLE
Datagrid: resizing a window that has a datagrid with a stretched Column setting does not keep a stretched column

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#5045]
**Describe the bug**
When a datagrid column has a stretchColumn setting for a certain column id and the browser window is resized, the stretched column state is not kept.

**To Reproduce**
1. Go to the attached html site
2. Note that the last column is stretched
3. Resize the browser window
4. Note that the last column is no longer stretched

[example-drilldown.zip](https://github.com/infor-design/enterprise/files/6246076/example-drilldown.zip)

**Expected behavior**
It is expected that the stretchedColumn setting for a particular datagrid column will remain stretched when the window is resized.

**Version**
- ids-enterprise: v4.38.0-dev

**Screenshots**
![stretchColumn_window_resize](https://user-images.githubusercontent.com/76002134/113345168-b4a19d80-92f7-11eb-9123-a11aa2330c59.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: 89.0.4389.114 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Assigned to you as you communicated you might try a PR https://github.com/infor-design/enterprise/blob/master/docs/CONTRIBUTING.md

Thanks if you do !

**Comment by janahintal** [comment]
The issue still exist in https://main-enterprise.demo.design.infor.com/components/datagrid/test-stretch-last-column.html?theme=new&mode=light&colors=0066D4

![image](https://user-images.githubusercontent.com/45757016/115866173-e546a400-a46b-11eb-8891-e18b7b268b56.png)
![image](https://user-images.githubusercontent.com/45757016/115865873-7c5f2c00-a46b-11eb-9e36-51666af3b5cb.png)

**Comment by tmcconechy** [comment]
@s-werking i think this is in fact working the best it can. If you resize it does get shorter but if you keep going you get a scrollbar. Its still stretching to the end even though the end is shorter...

**Comment by s-werking** [comment]
Yes, that is the intended behavior. The column width will be the calculated/assigned width of the column if there is not enough room to stretch longer to the edge of the datagrid.

**Comment by janahintal** [comment]
This is noted. Thank you! Will now move this ticket to Done. :)
