### ISSUE TITLE
Modal: Dialog doesn't close when a tooltip is visible

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5047]
**Describe the bug**
A modal dialog that is closed via a keyboard action (like an enter key) does not close when a tooltip is visible. When working in this issue will need to work with @tmcconechy to come up with a sample

**To Reproduce**
- Open a modal dialog
- Configure a keyboard action to close the dialog
- Have a tooltip visible
- Attempt to close the dialog via the keyboard

Or possibly for an example
- have a modal with a grid and paging
- hover the pager buttons so the tooltip shows
- while showing call closeDialog
- problem is here https://github.com/infor-design/enterprise/blob/master/src/components/modal/modal.js#L1179 (why is tooltips stopping from closing)

**Expected behavior**
Modal dialog should close whether or not a tooltip is visible. 

Version
- ids-enterprise: v4.37.3

**Comment by claudenbach** [comment]
[Git-5047.zip](https://github.com/infor-design/enterprise/files/6250042/Git-5047.zip)

**Comment by tmcconechy** [comment]
Speaking to @EdwardCoyle the code https://github.com/infor-design/enterprise/blob/master/src/components/modal/modal.js#L1179 is mainly for popovers (which are a subclass of tooltips) so the fix is probably to change this logic to detect isPopover for tooltips and ignore regular tooltips

**Comment by jbrcna** [comment]
QA Passed
v4.51.0-beta0
https://4510-beta0-enterprise.demo.design.infor.com/components/modal/test-close-tooltip.html
