### ISSUE TITLE
ListView: Changing selectable from 'mixed' to 'single' does not remove checkboxes 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5048]
**Describe the bug**
Changing the selectable input on a listview from 'mixed' to 'single' is not removing the checkboxes.  It works from when changing the selectable input from 'single' to 'mixed'. 

**To Reproduce**
- Render a listview with selectable set to 'mixed'
- Change the selectable to 'single' (using the updated(newSettings) method)
- Notice that the checkboxes are still rendered

**Expected behavior**
When setting the selectable to 'single', checkboxes should not be rendered

**Version**
- ids-enterprise: v4.37.3

**Comment by claudenbach** [comment]
![Git-5048](https://user-images.githubusercontent.com/39804038/113427534-d0aa4b00-939a-11eb-9b3c-bca800c53bee.gif)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
