### ISSUE TITLE
Dropdown/Multiselect : Typeahead dropdown/multiselect list doesn't contain attributes id when searching

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#5053]
**Describe the bug**
The id attribute prefix is missing from a dropdown list when searching through a call back (i.e. when reload === 'typeahead')

**To Reproduce**

1. Put attached examples in place
2. Open example and click dropdown, notice the items in the list to have the id prefix applied
3. type in a search term, notice the items in the list to do not have the id prefix applied

**Expected behavior**
id prefix should applied in dropdown list when returning results through the source callback

**Version**

- ids-enterprise: [4.38

**Screenshots**

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: 89.0.4389.90 (Official Build) (64-bit)

**Additional context**

For dropdown/example-ajax.html change options to this:
```
<script>
  $('body').on('initialized', function() {

    $('#ajax-test').dropdown({
      source: function (response, term) {
        var apiRoute = '{{basepath}}api/states';
        if (term && typeof term === 'string' && term.length) {
          apiRoute += '?term=' + term;
        }

        $.getJSON(apiRoute, function(data) {
          response(data);
        });
      },
      attributes: [{'name': 'id', 'value': 'SomeIdPrefix'}],
      showSearchUnderSelected: true,
      reload: 'typeahead'
    });

  });
</script>
```

For multiselect/example-ajax.html change options to this:
```
    $('#ajax-test').multiselect({
      source: callExternalSource,
      attributes: [{'name': 'id', 'value': 'SomeIdPrefix'}],
      showSearchUnderSelected: true,
      reload: 'typeahead'
    });
```

**Comment by janahintal** [comment]
QA Passed. Thank you.
![image](https://user-images.githubusercontent.com/45757016/119645285-75538100-be50-11eb-8240-04330506d9fd.png)
![image](https://user-images.githubusercontent.com/45757016/119645484-a5028900-be50-11eb-9112-5d45b2c0ebd7.png)
