### ISSUE TITLE
Accordion - collapseAll on panel with datepicker throws deprecated method warning

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise#5054]
**Describe the bug**
When the collapseAll method is called on an accordion that includes a datepicker in one of the panels, a deprecated method warning is thrown.

The warning message is: _"IDS Enterprise: "close()" is deprecated. Please use "closeCalendar()" instead."_

**To Reproduce**
Put a datepicker component on a accordion panel and call the collapseAll() method on that accordion. You'll see the warning message on the console.

1. In the NG demo app, replace the \app\accordion\accordion.demo.html file with the one attached to this issue.
2. Start the demo app and navigate to A\Accordion
3. Click 'Expand All' then 'Collapse All'.
4. Note the deprecated method warning in the console.

[accordion.demo.html.txt](https://github.com/infor-design/enterprise/files/6260302/accordion.demo.html.txt)

**Expected behavior**
It should not throw the warning message.

**Version**
IDS NG Version: 9.3.1
IDS Version : 4.38.1

**Screenshots**

**Platform**
 - Infor Application/Team Name: GLT
 - Device: PC
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: 89.0.4389.114
 
**Additional context**
Been seeing this one for quite a few versions back, just got around to reporting it.

**Comment by tmcconechy** [comment]
I forget at what point i fixed this. But i did. Confirmed in 4.51
