### ISSUE TITLE
Dropdown: The list of matching hits gets detached from field

### ISSUE THREAD

**Issue by jcotaco** [infor-design/enterprise#5056]
**Describe the bug**
When searching in a dropdown field, the retrieved list with matching hits gets detached.
**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/dropdown/example-ajax-managed.html
2. Make the browser window small by resizing it or opening the console.
3. Search for "California"

**Expected behavior**
The list with matching hits should be displayed near the dropdown field. 

**Version**
IDS Version: 4.38.1

**Screenshots**
![image](https://user-images.githubusercontent.com/72491690/113699248-e22b8400-9707-11eb-8607-97652befb58a.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - Device: Windows Laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 89.0.4389.114 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Im not able to reproduce this on the link mentioned. Does the page have to be some exact size? If so what size is the page. You can see this by inspecting the html tag...

![Screen Shot 2021-04-06 at 9 32 16 AM](https://user-images.githubusercontent.com/814283/113718819-057c1200-96bb-11eb-8736-6d01daa3bfdc.png)

**Comment by jcotaco** [comment]
Hi,

Please see attached. You can also resize the window in such a way that when you click on the field, the dropdown list will not be fully shown. 
![image](https://user-images.githubusercontent.com/72491690/113722638-31cb7900-9723-11eb-986f-eebff670da23.png)

**Comment by tmcconechy** [comment]
thanks - this is much shorter than i was trying

**Comment by SofiK** [comment]
I think it often happens when the dropdowns opens above the dropdown and you search. It doesn't look so good when it's sometimes very far from the source :(

For exampel here when in the last dropdown and you search for 40:
https://master-enterprise.demo.design.infor.com/components/dropdown/test-sizes.html
![image](https://user-images.githubusercontent.com/8664975/114547918-582b7000-9c5f-11eb-88b1-031f556b2a43.png)

**Comment by jbrcna** [comment]
QA Passed. v4.51.0-dev
https://main-enterprise.demo.design.infor.com/components/dropdown/example-ajax-managed.html
![image](https://user-images.githubusercontent.com/56722184/115838025-d3ed9f80-a44b-11eb-9c03-4b91f45e4a7e.png)

https://main-enterprise.demo.design.infor.com/components/dropdown/test-sizes.html
![image](https://user-images.githubusercontent.com/56722184/115838182-fc759980-a44b-11eb-823f-5235c7932e2b.png)
