### ISSUE TITLE
Bar Chart (stacked): Y-axis label overlaps with each other

### ISSUE THREAD

**Issue by rdugenia** [infor-design/enterprise#5057]
**Describe the bug**
Bar Chart (stacked): Y-axis label overlaps with each other

**To Reproduce**
Steps to reproduce the behavior: See attached sample.
[y-axisOverlap.zip](https://github.com/infor-design/enterprise/files/6264505/y-axisOverlap.zip)

**Version**
ids-enterprise: v4.38.0

**Screenshots**
![image](https://user-images.githubusercontent.com/78482539/113708153-75b68200-9713-11eb-8403-25efa52ad49a.png)

**Platform**
 - Browser Name: Chrome, Edge

**Comment by tmcconechy** [comment]
I checked this out and i dont think there is really too much we can do about it. If you put that many items in to that small of an area thats the way its going to fit.

Suggestions:
- show less items
- make the parent width / hero area width bigger
- could also add a css rule like this to reduce the axis font size but it makes it pretty hard to read

```
.bar-chart .tick text {
  font-size: 8px;
}
```

**Comment by katieinfor** [comment]
Will build an epic for design in Jira.

**Comment by katieinfor** [comment]
Jira Ticket: https://jira.infor.com/browse/UXD-2943

**Comment by tmcconechy** [comment]
I dont think this has a solution other than to rethink how you present the data.
