### ISSUE TITLE
Modal: Unnecessary scroll bar

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5059]
**Describe the bug**
Modal: Unnecessary scroll bar

**To Reproduce**

1. Go to  https://main-enterprise.demo.design.infor.com/components/modal/example-index.html
2. Click show modal 
3. See unnecessary scroll bar

**Expected behavior**
No unnecessary scroll bars should show

**Version**
4.50 - ids

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/113840277-1adc6380-97c3-11eb-9369-b150d963f205.png)

**Platform**
Windows 10 Chrome and all major browsers

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Seems like just an issue when its a specific size. But i think this can be improved in terms of reducing the padding on the bottom

**Comment by tmcconechy** [comment]
Descoping for now...
