### ISSUE TITLE
Popupmenu Control settings.showArrow not recognised when 'true'

### ISSUE THREAD

**Issue by mliet** [infor-design/enterprise#5061]
DESCRIPTION
The settings.showArrow value is not recognised when set to 'true'.
I am using the popupmenu control and want to force the arrow to be shown on a btn-icon class trigger.  I see that it will happen by default if there is a specific icon used, but I am using a different icon and therefore want to override the default.

TO REPRODUCE
Create a popup menu from a control which will not default to the arrow displaying by default.  
Eg. "btn-icon" class where icon is not #icon-more.
Eg.
`<button class="btn-icon triggerPopup" type="button"><img src="Images/myIcon.png" alt="Actions" /></button>`
`<ul id="popupActionMenu" class="popupmenu">`
`   <li><a href="#" id="menu-option-1">Menu Option #1</a></li>`
`   <li><a href="#" id="menu-option-2">Menu Option #2</a></li>`
`</ul>`
`<script type="text/javascript">`
`        $('.triggerPopup').popupmenu({ menu: 'popupActionMenu', trigger: 'click', showArrow: true });`
`</script>`

1. Run Html above on IDS page
2. Click on the Icon
3. Note that the popup has no arrow on it despite showArrow being set to true.

EXPECTED BEHAVIOUR
Expect to see arrow on popup menu pointing to originating icon.

Can be fixed by altering the following code in addMarkup function:

      var doSetArrow = false;
      var containerClass = this.element.parent().attr('class'); // `true` setting takes precedent over all else

      if (this.settings.showArrow === true) {
        doSetArrow = true;              //  <<<<< This line is changed.  Was incorrectly setting to false

VERSION
IDS Enterprise Components - v4.38.0

PLATFORMS
All

**Comment by tmcconechy** [comment]
@mliet sounds good. If you would like to do a pull request feel free to. Thanks
