### ISSUE TITLE
Lookup: "editable: false" (readonly) lookups do not allow clicking of the lookup button

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#5062]
**Describe the bug**
Using `editable: false` has always made the input field readonly, it suddenly makes the button disabled.

**To Reproduce**

Create a lookup with `editable: false` and noticed it is not clickable. Here is an example: https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/example-not-tabbable.html

**Expected behavior**
The input should not be editable, but the lookup should be actionable.

**Version**

- ids-enterprise: 4.51

**Additional context**
This was broken with this commit: #https://github.com/infor-design/enterprise/commit/b90bb8e8406baac8c842932af039991cfcbb8339

**Platform**
Infor Application/Team Name: lawson
Device: (if applicable) N/A
OS Version: Windows10
Browser Name: chrome
Browser Version: 89.0.4389.114 (Official Build) (64-bit)

**Comment by awbuboltz** [comment]
Note: this need the lawson team label.

**Comment by EdwardCoyle** [comment]
@awbuboltz confirmed this was a change from #5030, where we changed some trigger field icons to become represented by actual HTML buttons (accessibility needs from the Landmark team being the driver for the change).  I had originally thought this wasn't working correctly -- you're expecting to still be able to open a Lookup field when `editable: false` is set, and the input becomes readonly?

**Comment by awbuboltz** [comment]
Using the buttons makes sense to us, although we are seeing a lot of _blurry_ SVGs now for some reason.

But yes, readonly lookups have always been actionable via the button since the early 3.6 days with only the input itself being readonly.

**Comment by EdwardCoyle** [comment]
Marked as a regression :thumbs:

Can you pass along a screenshot, and let us know the browser/OS where you're seeing the icon blurriness?  We can address that too but I haven't seen that one.

**Comment by awbuboltz** [comment]
Yeah, we're working on it gathering samples on the other issue.

**Comment by jbrcna** [comment]
this issue is now resolved. thank you
https://main-enterprise.demo.design.infor.com/components/lookup/example-not-tabbable.html
