### ISSUE TITLE
Datagrid: Icon misalignment on a filter field for a datagrid with small rowheight

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#5063]
**Describe the bug**
For a datagrid with the class "small-rowheight", the lookup, datepicker, and timepicker icons are misaligned with the fields.

This seems to be caused by this commit from issue #5030:
https://github.com/infor-design/enterprise/commit/3a22ee7af6bec545454bb185ab904fb4624ccc09

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-filter.html
2. Add the class "small-rowheight" to the datagrid
3. Note that the datagrid filter fields with icons overlap

**Expected behavior**
It is expected that the icon is inside of the datagrid filter field.

**Version**
- ids-enterprise: v.4.51.0-dev

**Screenshots**
Misalignment seen in this sample:
![Filter Icon Misalignment](https://user-images.githubusercontent.com/76002134/114091297-204ab400-987e-11eb-9c4e-16b6ccb9c649.PNG)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 89.0.4389.114 (Official Build) (64-bit)

**Comment by EdwardCoyle** [comment]
I think this one probably also started around the same time as #5030.  Minor tweaks needed on Small and Extra-small row heights.

**Comment by tmcconechy** [comment]
Yeah i agree we should probably fix this sooner than later.

**Comment by tmcconechy** [comment]
In addition can you fix this issue

https://master-enterprise.demo.design.infor.com/components/lookup/example-index.html
- open lookup
- type in search
- notice the X

**Comment by s-werking** [comment]
I just found another issue having to do with those icons. Using the same html on this ticket if you click to edit the cell with a timepicker icon inside it, the icon shifts in the cell. This happens with the other icons too and with/without the "small-rowheight" class assignment.

**Comment by awbuboltz** [comment]
Also, on those tables with editable cells, the popups lose their position.

**Comment by EdwardCoyle** [comment]
http://localhost:4000/components/datagrid/example-editable.html

- Use the editable Timepicker cell.  The trigger button appears in the wrong location
- Activate the Timepicker.  It opens in the wrong location

**Comment by jbrcna** [comment]
the issue is now resolved.
https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
![image](https://user-images.githubusercontent.com/56722184/115189006-5eff2a80-a118-11eb-9e54-ce2e18731d05.png)
