### ISSUE TITLE
Calendar: Today becomes selected day on calendar in current month instead of provided day

### ISSUE THREAD

**Issue by jalalhobbs** [infor-design/enterprise#5064]
**Describe the bug**
Calendar initialized with day in current month will select today instead of provided day.

**To Reproduce**

**Steps to reproduce the behavior:**
_example-only-calendar.html:_
`        $('.calendar').calendar({
          day: 21,
          month: 3,
          year: 2021, ... });`
(Today being any day in April 2021 besides the 21st)

Create calendar using object containing year, month, day in current month where day isn't today's date.

This will be shown on April 9, 2021:
![image](https://user-images.githubusercontent.com/4069347/114109929-7dde0f80-9915-11eb-8bae-571abd325ebd.png)

**Expected behavior**
The day provided to calendar should be highlighted/selected.
![image](https://user-images.githubusercontent.com/4069347/114109949-89c9d180-9915-11eb-85e8-6c98244b0c2f.png)

**Version**
Tested in ids-enterprise v4.38.x and v4.50.x.

**Platform**
 - Infor Application/Team Name: Infor Pathway
 - Browser Name: chrome
 - Browser Version: Version 89.0.4389.114 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
To reproduce go to https://master-enterprise.demo.design.infor.com/components/calendar/test-specific-month.html and notice it has todays day selected.

**Comment by nganotice** [comment]
The issue is now resolved.

Tested on: https://main-enterprise.demo.design.infor.com/components/calendar/test-provided-date.html

<img width="1680" alt="Screen Shot 2021-06-03 at 4 04 04 PM" src="https://user-images.githubusercontent.com/84306838/120610132-735b7480-c485-11eb-86df-2277d5551f18.png">

Moving this ticket to Done. Thanks!
