### ISSUE TITLE
Calendar: Week and Day view is-selected

### ISSUE THREAD

**Issue by jalalhobbs** [infor-design/enterprise#5065]
**Is your feature request related to a problem or use case? Please describe.**
When a day is selected in month view, when changing to Week or Day view, there is no visual cue to show which date is selected.

**Describe the solution you'd like**
The user would be able to visualize what date they are working on by showing the a visual cue on the selected day when changing from Month view to Week or Day view.

**Describe alternatives you've considered**
An additional CSS class outside of is-today, possibly is-selected that functions in Month view, Week view, Day view to keep with the selected themes used while showing a slightly different visual cue than is-today.

**Additional context**
Infor Pathway

**Design**
See https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=346-11814&mode=design&t=DYjJiuYxPZouEwaF-0

We want to update the states (hover/focus/selection/today).

**Comment by tmcconechy** [comment]
I dont think i follow what your asking for here. If i look at monthview https://master-enterprise.demo.design.infor.com/components/calendar/test-specific-month.html

It has a selected day shown and when i change month it stays on that day in the next month.

If changing to week view - perhaps we could use some colaration there? But in day view it doesn't really make sense does it?

**Comment by jalalhobbs** [comment]
Yes, the change from month view to week/day view with coloration is what I mean, sorry to not be clear.
As for the day view, I understand that it seems useless as you're staring at it, but is-today does show coloration for the day view.
Our QA has requested that we have it for week and day view.

**Comment by tmcconechy** [comment]
ok, thank you. I think this makes sense.

**Comment by tmcconechy** [comment]
Closing stale issues

**Comment by timothyholton** [comment]
Hi. I am reviewing some older tickets. This one is still required by Pathway users, but it was closed for some reason. Is it possible to re-open this one so it can be actioned at some point? Thanks.

**Comment by tmcconechy** [comment]
Closed by stale bot. We can look when we have the bandwidth

**Comment by hey-yall** [comment]
Design resources requested: https://jira.infor.com/browse/IDS-1819

**Comment by tmcconechy** [comment]
Ready from design please see https://jira.infor.com/browse/IDS-1819 https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=346-11814&mode=design&t=bLwOgSaJJvNm5Jfd-4

**Comment by tmcconechy** [comment]
@tjamesallen15 to clarify please see https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=346-11814&mode=design&t=DYjJiuYxPZouEwaF-0

We want to update the states (hover/focus/selection/today).
