### ISSUE TITLE
Datagrid: Issue changing selectable when have frozen columns

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5067]
Describe the bug
We are changing the selection mode between 'single' and 'mixed' on a datagrid with frozen columns.  When in 'single' mode the checkbox is not displayed.  When in 'mixed' mode the checkbox is displayed.  This all works great when frozenColumns do not exist.  Meaning in 'single', no checkbox is rendered and the selection model is single and when in 'mixed' mode the checkbox is rendered and the selection model behaves in 'mixed' mode.

With frozenColumns, when changing the selectable from 'single' to 'mixed', the selection model stays in 'single' mode.

1. Using the attached 'test-change-selectable-with-frozen-columns.html'
2. Click on 'Switch Select Mode' button
3. Datagrid is not rendered correctly and the selection mode has not changed

Expected behavior
When switching to mixed, the columns array includes the selectionCheckbox so checkbox should be displayed and multiple rows are able to be selected

Version
- ids-enterprise: v4.39.0

**Comment by claudenbach** [comment]
[Git-5067.zip](https://github.com/infor-design/enterprise/files/6288056/Git-5067.zip)

**Comment by claudenbach** [comment]
[Git-5067-Landmark-Example.zip](https://github.com/infor-design/enterprise/files/6288164/Git-5067-Landmark-Example.zip)

**Comment by jbrcna** [comment]
QA Failed
Try to change Datagrid size then click Switch select mode.
v4.52.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-change-selectable-with-frozen-columns.html
![image](https://user-images.githubusercontent.com/56722184/119067326-644fdd80-ba14-11eb-97e8-f95ce0b492ca.png)

**Comment by tmcconechy** [comment]
Can you clarify these steps @jbrcna Im not seeing it unless @ericangeles has an idea how to reproduce?

**Comment by jbrcna** [comment]
@tmcconechy I just changed the Row height and switch select modes.
Steps to replicate
1. Click `...` then change row height to Extra small
2. Toggle `Switch Select Mode` on/off
3.  Click `...` then change row height to small
4. Toggle `Switch Select Mode` on/off
5. Repeat steps 1-4 in all Row Height
6. Play around with sizes and toggle `Switch Select Mode` on/off
7. 
![image](https://user-images.githubusercontent.com/56722184/119145940-b9273e80-ba7c-11eb-846c-a2be1b93a43d.png)

**Comment by ericangeles** [comment]
@tmcconechy I can verify this one. Will fix this issue. Good catch btw, @jbrcna.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
