### ISSUE TITLE
About: IDS Version on About page is not set

### ISSUE THREAD

**Issue by rdugenia** [infor-design/enterprise#5069]
**Describe the bug**
IDS Version on About page is not set

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/about/example-index.html
2. Click on 'Show About Screen'
3. Scroll down to view the IDS Version

**Expected behavior**
Should show the IDS version but instead "[object Object]" is displayed

**Version**
- ids-enterprise 4.50

**Screenshots**
![image](https://user-images.githubusercontent.com/78482539/114373574-50af8c80-9bb5-11eb-8964-97ab1357e3e5.png)

**Platform**
 - Browser Name: Chrome

**Comment by tmcconechy** [comment]
Noticed this as well in the html in the header

**Comment by jbrcna** [comment]
the issue is now resolved. 
v4.51.0-dev
![image](https://user-images.githubusercontent.com/56722184/115326537-01beb400-a1c0-11eb-932e-f4365183875e.png)
