### ISSUE TITLE
[All Browsers] Popupmenu: Page doesn't have contents

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#507]
**Describe the bug**
[All Browsers] Popupmenu: Page doesn't have contents.

**To Reproduce**
1. Go to http://490-beta0-sohoxi.demo.design.infor.com/components/popupmenu/example-context-menu-behavior.html
2. No contents are displayed

**Expected behavior**
popupmenu/example-context-menu-behavior page should have contents.

**Screenshots**
<img width="721" alt="screen shot 2018-07-27 at 7 17 00 pm" src="https://user-images.githubusercontent.com/39508864/43317999-b9add188-91d1-11e8-8fbb-df27c8b341a4.png">

**Platform**
 - All browsers

**Additional context**
No additional context.

**Comment by EdwardCoyle** [comment]
I'll fix this one... caused by me in #504 -- I moved the page in the `app/views/components/contextmenu` folder that this particular popupmenu test references.
