### ISSUE TITLE
Datagrid: Filter options not opening anymore after doing a sort

### ISSUE THREAD

**Issue by rdugenia** [infor-design/enterprise#5073]
**Describe the bug**
Filter options not opening anymore after doing a sort on server-side paging

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-paging-server-side.html
2. Click on any filter options dropdown (keep it open)
3. Do a sort (on any of the columns)
4. Close the filter options dropdown
5. Try to open it again

**Expected behavior**
Filter options should be opened

**Version**
- ids-enterprise: 4.50

**Screenshots**
![filterOptions](https://user-images.githubusercontent.com/78482539/114548681-ab6ae600-9c92-11eb-8783-e060a0445de0.gif)

**Platform**
 - Browser Name: Chrome

**Additional context**
Issue is not occurring on client-side paging
https://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html

**Comment by janahintal** [comment]
QA Passed. 
Verified in: https://main-enterprise.demo.design.infor.com/components/datagrid/test-filter-paging-server-side.html
