### ISSUE TITLE
DatePicker: Add Mobility enhancements

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5075]
**Is your feature request related to a problem or use case? Please describe.**
We need to add a few improvements to the datepicker so that it can be used standalone and in a smaller version.

**Describe the solution you'd like**
- card popover background is removed to do this https://master-enterprise.demo.design.infor.com/components/monthview can be used already but we need to make the monthview that is in https://master-enterprise.demo.design.infor.com/components/datepicker/example-index avaialble "in page". There is an option now for it being in a datepicker but need one so the smaller one there is shown in page. Would add an example to components/monthview/example-inpage . And the example should look like the design
- Clear and Apply actions are removed to do this just dont include buttons in the example-inpage version
- Tapping a date can trigger and event that changes the list below  (application team’s responsibility but we add the event)
~- Add swiping in our Angular web component (and HTML??)~ this will be done on https://github.com/infor-design/enterprise/issues/5002
- Change “Today” action to 16px bold
- Spacing between dates and chevrons has been improved to have enough space for a 40 to 44px hitbox (for in page version only if this is easier / breaking too much / this is optional)
- Change date hitbox to 40 or 44px for better mobile touch points (if space allows) (for in page version only if this is easier / breaking too much / this is optional)
- Included a legend view from the datepicker component, can we align it to the left by default? Centered is ok for the popover examples. Suggest we do this based on number of items. If they can fit in one row do it left aligned otherwise centered
- If clicked/tapped, the toolbar title & calendar icon will pulse & expand the month view downwards... pushing other content down the page. To do this we do it in the in page example
- Change text color for current month’s dates to slate 8 (can change all)
- azure and slate circles are 2 instead of 1. To do this - its just part of the example in the legend colors
- Add ‘pulse’ animation back in for buttons/dates on mobile at least?
- Noticed that on https://main-enterprise.demo.design.infor.com/components/monthview/example-index when you click the calendar it changes the month this may be related to https://github.com/infor-design/enterprise/issues/5064
- Adjust the month and year picker

**Describe alternatives you've considered**
Leaving this go for now

**Additional context**
See designs - we are just implementing page one (High Priority) https://www.figma.com/file/ri2Knf3KchdfdzRAeds0Ab/IDS-Mobility-v4.6?node-id=1%3A5739

**Comment by jbrcna** [comment]
The issue is now resolved.
v4.52.0-beta0
