### ISSUE TITLE
Tabs Vertical: with outbound links cannot be selected using tab & keys up & down function. 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5085]
**Describe the bug**
Tabs Vertical: with outbound links cannot be selected using tab & keys up & down function. 

**To Reproduce**

1.	Go to https://main-enterprise.demo.design.infor.com/components/tabs-vertical/example-outbound-links-page1
2.	Use tab key to focus on Page 2
3.	Hit Enter

**Expected behavior**
The page will refresh to Page 2

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/114864902-257ea480-9e24-11eb-93da-be8976e404ee.png)

**Platform**
All major browsers. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
There does seem to be something strange here. However it is working on https://main-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html

**Comment by tmcconechy** [comment]
Descoping this
