### ISSUE TITLE
Lookup: editable strict cannot open lookup

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5087]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/lookup/example-editable-strict.html
2. Click on Lookup icon
3. Notice that the look up is not shown

**Expected behavior**
should be able to open lookup

**Version**

- ids-enterprise: 4.50.0-main

**Screenshots**

**Platform**
all major browsers

**Additional context**

**Comment by tmcconechy** [comment]
cc @EdwardCoyle - maybe due to button tabbing change?

**Comment by EdwardCoyle** [comment]
Seems like it's related, but not sure exactly why (maybe something related to the `tabbable`/`editable` settings conflicting)

**Comment by tmcconechy** [comment]
Could it be the same as https://github.com/infor-design/enterprise/issues/5062

**Comment by EdwardCoyle** [comment]
Good call, tested against the branch on #5066 and it does fix the problem 👍

**Comment by jbrcna** [comment]
this is now working as expected. thank you
https://main-enterprise.demo.design.infor.com/components/lookup/example-editable-strict.html
