### ISSUE TITLE
LookUp: x icon in was misaligned in uplift

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5088]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/lookup/example-clearable.html
2. Input some text
3. See error

**Expected behavior**
x icon should be aligned

**Version**

- ids-enterprise: 4.50-main

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/114872809-3e3f8800-9e2d-11eb-9f05-6c1332ac3326.png)

**Platform**
Allmajor browsers

**Additional context**
see also
https://main-enterprise.demo.design.infor.com/components/lookup/example-filter-lookup.html
![image](https://user-images.githubusercontent.com/56722184/114875044-7d6ed880-9e2f-11eb-97a2-03fed04db840.png)

https://main-enterprise.demo.design.infor.com/components/lookup/example-icon.html
![image](https://user-images.githubusercontent.com/56722184/114875281-b9a23900-9e2f-11eb-9708-00998b4064d8.png)

https://main-enterprise.demo.design.infor.com/components/lookup/example-index.html
![image](https://user-images.githubusercontent.com/56722184/114875485-e7877d80-9e2f-11eb-9bcb-5a06e895af5c.png)

https://main-enterprise.demo.design.infor.com/components/lookup/example-minwidth.html

**Comment by tmcconechy** [comment]
This seems to be another case @rob2d align with

https://github.com/infor-design/enterprise/issues/5074
and
https://github.com/infor-design/enterprise/issues/5080

Should maybe fix all 3 together.

**Comment by rob2d** [comment]
@tmcconechy haven't looked at this one quite yet but will do so next. 

Submitted several related fixes; trying to be small/targeted so we can see on review that the CSS is extremely specific with clear PR test cases, since one-size-fits-multiple isn't going very smoothly on these search-field cases in terms of regressions.

**Comment by jbrcna** [comment]
this issue is now resolved. v4.51.0-dev
https://main-enterprise.demo.design.infor.com/components/lookup/example-clearable.html
https://main-enterprise.demo.design.infor.com/components/lookup/example-clearable.html?theme=new&mode=light&colors=2578a9&locale=ar-EG
