### ISSUE TITLE
Tabs Module: Tabbing inside clearable searchfield makes the "X" icon disappear

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#5090]
**Describe the bug**
When the focus is set to the "X" icon for a clearable searchfield, only the focus border appears around where the "X" icon should be.

**To Reproduce**
1. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
2. Begin typing in the searchfield
3. Tab to access the close button
4. Note that the close button is no longer visible

**Expected behavior**
It is expected that the "X" icon is visible while focused.

**Version**
- ids-enterprise: v.4.51.0-dev

**Screenshots**
Issue seen in the sample:
![Searchfield Close Icon Lost](https://user-images.githubusercontent.com/76002134/114896840-49b39480-9dd6-11eb-94e7-325bb8114a37.PNG)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: 89.0.4389.114 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Similar to https://github.com/infor-design/enterprise/issues/5096

**Comment by janahintal** [comment]
QA Passed. Verified in https://4510-beta0-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html
![image](https://user-images.githubusercontent.com/45757016/116987037-2313ba00-ad01-11eb-8abc-63d160b54a19.png)
