### ISSUE TITLE
Dropdown: When an option with <option value=""> is entered, dropdown does not close

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#5095]
**Describe the bug**
When selecting an option that is blank, dropdown is not closing on enter key press

**To Reproduce**
https://master-enterprise.demo.design.infor.com/components/dropdown/test-blank-option.html

1. Go to https://master-enterprise.demo.design.infor.com/components/dropdown/test-blank-option.html
2. Change selection to blank via click
3. Press Enter again, dropdown should open 
4. Press Enter again
    - Expected: Dropdown will close
    - Actual: Dropdown does not close
(Added on screen keyboard on recording to Enter key press)

![blank dropdown issue](https://user-images.githubusercontent.com/50192038/114967841-c3678300-9ea7-11eb-8d8d-f048aa5aa917.gif)

**Platform**
 - Infor Application/Team Name: M3 H5 UI Team
 - Device: N/A
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Browser Version: Version 88.0.4324.190 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
It looks like when it opens its not selecting the blank item. It will work if you down arrow first. But this indeed seems to be a bug

**Comment by janahintal** [comment]
Issue is now resolved in https://main-enterprise.demo.design.infor.com/components/dropdown/test-blank-option.html?theme=new&mode=light&colors=0066D4

However, the issue still exists in master - https://master-enterprise.demo.design.infor.com/components/dropdown/test-blank-option.html

**Comment by tmcconechy** [comment]
Lets make a new issue for that @janahintal its not really the same issue (and not so important)
