### ISSUE TITLE
Password: Reveal text feature forces autocomplete on

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5099]
**Describe the bug**
Because the way chrome works you can't ignore autocomplete for type="password". This is an issue flagged by the security team for the recently added reveal feature. To fix this we can use `-webkit-text-security: disc;` instead of password type then autocomplete can be ignores

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-hidereveal-tsgm2h?file=index.html
2. Type 1 and hit enter
3. Reload 
4. Type 1 again -> see problem the security team doesnt want this

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="398" alt="Screen Shot 2021-04-16 at 11 00 05 AM" src="https://user-images.githubusercontent.com/814283/115043901-fb1ffc00-9ea2-11eb-8a74-d6bbe55dfc43.png">

**Platform**
 - Chrome
 
**Additional context**
MS Teams

**Comment by tmcconechy** [comment]
Can test the fix here https://stackblitz.com/edit/ids-hidereveal-xvhqlq?file=index.html

**Comment by jbrcna** [comment]
the issue is now resolved.
v4.51.0-dev

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
