### ISSUE TITLE
Tabs Module: Rename tab title API not working

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#5105]
**Describe the bug**
When using the rename API for a tab title change, the tab title does not change.

**To Reproduce**
1. Go to the attached html page below (similar to http://localhost:4000/components/tabs-module/test-lsf-addtabs-scenario.html but with a focus change on clicking the add tab button and renaming tabs)
2. Click on the 'Rename' button
3. Note that the tab name does not change
4. Click on the add tab button until a More menu appears
5. Note that every new tab in the menu does not get renamed properly

[test-lsf-addtabs-scenario.zip](https://github.com/infor-design/enterprise/files/6337776/test-lsf-addtabs-scenario.zip)

**Expected behavior**
It is expected that when the rename tab API is called, the tab will have the new title after it has finished.

**Version**
- ids-enterprise: v.4.51.0-dev

**Screenshots**
The original tab name persists in the more menu for every new tab:
![Original tab name persists](https://user-images.githubusercontent.com/76002134/115275627-a92be000-a107-11eb-9c10-a949e0914100.PNG)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: 90.0.4430.72 (Official Build) (64-bit)

**Comment by janahintal** [comment]
QA Passed. Verified in https://4510-beta0-enterprise.demo.design.infor.com/components/tabs-module/test-lsf-addtabs-scenario-2
![Uploading image.png…]()

**Comment by s-werking** [comment]
Hi! I noticed that when the new tab is added to the popupmenu in the test-lsf-addtabs-scenario-2 html page, the tab doesn't have the "X" button to close it even though it is dismissable. Is there a way to add this to the ticket? 
I verified that it is possible to close a new tab in the popupmenu if it is not renamed.

I was also wondering if the href selector on line 3075 of tabs.js could include the "#" so we could just send the tab id without "#" into the rename API. I'm not sure what is standard for that. Otherwise the rename API works great! Thanks.

**Comment by EdwardCoyle** [comment]
@s-werking I'm seeing an "X" button present in the menu against the new items, as expected.  The "X" button doesn't appear unless the item in the menu is hovered though (this has always been the behavior):

![Untitled_-May-5-2021-1_24-PM](https://user-images.githubusercontent.com/3249601/117183250-51e36c00-ada5-11eb-9a16-4d2bd9a76e1d.gif)

**Comment by EdwardCoyle** [comment]
@s-werking I raised #5181 to enable the `rename()` method to work with/without a hash in the ID string.

**Comment by s-werking** [comment]
Thanks Ed, So in the test-lsf-addtabs-scenario-2.html, if the '#' is removed on line 44 to accommodate the most recent change then it should rename the new tab in the popupmenu correctly and you should be able to see that "X" missing.

**Comment by s-werking** [comment]
This is what I see: 
![Missing X button](https://user-images.githubusercontent.com/76002134/117186527-8b65a880-ada0-11eb-8cc8-4f2259b0f7c3.gif)

**Comment by EdwardCoyle** [comment]
@s-werking, I see the issue now (dismissible not being accounted for when resetting the text in the overflowed item).  I've made changes to #5181 to fix that
