### ISSUE TITLE
Builder: Change icon for hiding/showing the sidebar.

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#5106]
**Is your feature request related to a problem or use case? Please describe.**
The hiding/showing the sidebar uses a back and hamburger as its icons, but the use of a collapse-app-tray, and expand-app-tray is more intuitive.

Go to https://master-enterprise.demo.design.infor.com/components/builder/example-builder-subtitle-test.html and notice there is a back button to collapse the side menu.

**Describe the solution you'd like**
Make it clear to the user that this button will collapse or expand the sidebar.

**Additional context**
Was initially added in #4394 using the icons used for the responsiveness of this control.

**Comment by tmcconechy** [comment]
I agree that the back button doesnt really make sense https://master-enterprise.demo.design.infor.com/components/builder/example-builder-subtitle-test.html

Which icon is the  collapse-app-tray, and expand-app-tray ? I cant seem to see it. So not 100% sure which one you are proposing. If you mean the hamburger. Im not sure that would work as it is used for the app menu and they could both be on the page.

**Comment by tmcconechy** [comment]
cc @katieinfor -> this is a question for design.

**Comment by marknolaninfor** [comment]
The circled icons.
![image](https://user-images.githubusercontent.com/39749678/115645191-12596080-a35f-11eb-9c42-cf57d99fc686.png)

The design for the smaller devices (phones) may also be considered, as a separate button is also displayed with a back icon.

**Comment by tmcconechy** [comment]
OK, yeah i think that does probably work better.

**Comment by katieinfor** [comment]
@kevinwhitedesign I will add this ticket in Jira. Thanks!

**Comment by katieinfor** [comment]
Jira: https://jira.infor.com/browse/UXD-2494

**Comment by tmcconechy** [comment]
Closing as stale issue ~ we wont be updating builder anymore ~ look for new patterns in the future
