### ISSUE TITLE
Dropdown: Readonly dropdown doesnt have aria states

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5107]
**Describe the bug**
Found this issue conversing with the TAAS team on issues LMCLIENT-33120 / TAAS-8281. They pointed out that the readonly dropdown only has a class and no actually DOM indication of a readonly state.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/dropdown/example-readonly.html
2. Right Click on the readonly dropdown div
3. See that it doesn't have any readonly property or aria

**Expected behavior**
Can add aria-reaoonly for this state.

**Version**
- ids-enterprise: [e.g. v4.50.0]

**Platform**
 - Mac/Chrome

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-33120

**Comment by jbrcna** [comment]
This issue is now resolved. v4.51.0-dev
https://main-enterprise.demo.design.infor.com/components/dropdown/example-readonly.html
![image](https://user-images.githubusercontent.com/56722184/115842119-1913d080-a450-11eb-9b3d-15a49937a7f0.png)
