### ISSUE TITLE
New window and Same window in RichtextEditor anchor is not translated to other language

### ISSUE THREAD

**Issue by allanalvarez** [infor-design/enterprise#511]
**Describe the bug**
We have this issue in the sohoxi Richtext Editor > anchor, the New Window and Same Window is not being translated to other language (please see image below)

**Expected behavior**
New Window and Same Window should be translated

**Screenshots**
![image](https://user-images.githubusercontent.com/41406875/43375294-ba519ebe-93e6-11e8-9987-8c45d0783262.png)

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Note, As a workaround you can pass in a string for it...

```
* @param {string} [settings.anchor = { url: 'http://www.example.com', class: 'hyperlink', target: 'New window', isClickable: false, showIsClickable: false }] An object with settings related to controlling link behavior when inserted example: `{url: 'http://www.example.com', class: 'hyperlink', target: 'New window', isClickable: false, showIsClickable: false},` the url is the default url to display. Class should normally stay hyperlink and represents the styling class. target can be 'New window' or 'Same window', isClickable make the links appear clickable in the editor, showIsClickable will show a checkbox to allow the user to make clickable links in the link popup.
```

**Comment by brianjuan** [comment]
Please provide steps for QA testing, thank you.

**Comment by allanalvarez** [comment]
Hi @brianjuan 

Steps to reproduce:
1) Access this url: http://master-enterprise.demo.design.infor.com/components/editor/test-paste-as-plain-text.html

2) Click **Insert Anchor** button

3) Notice **Target** column will not change to different language.
![image](https://user-images.githubusercontent.com/41406875/44697892-688f7c00-aab0-11e8-9c72-f3599f1cfd12.png)

**Comment by brianjuan** [comment]
Thanks @allanalvarez 
Moving to Failed QA, Target dropdown values are still not translated to different language.
http://4100-beta0-enterprise.demo.design.infor.com/components/editor/test-paste-as-plain-text.html?locale=zh-Hans
<img width="937" alt="screen shot 2018-08-28 at 6 25 42 pm" src="https://user-images.githubusercontent.com/39508864/44717584-f76fb900-aaef-11e8-89fb-611c1cdcc3fc.png">

**Comment by tmcconechy** [comment]
@brianjuan the strings are not all translated from the translation team. At the moment only es-ES and en-US are supported

http://4100-beta0-enterprise.demo.design.infor.com/components/editor/test-paste-as-plain-text.html?locale=es-ES

Once https://github.com/infor-design/enterprise/issues/557 is done all languages will be supported.

**Comment by brianjuan** [comment]
This is noted @tmcconechy thanks.
http://4100-beta1-enterprise.demo.design.infor.com/components/editor/test-paste-as-plain-text.html?locale=es-ES
Passed QA testing
<img width="846" alt="screen shot 2018-08-29 at 1 41 30 pm" src="https://user-images.githubusercontent.com/39508864/44767636-491c5000-ab91-11e8-8db1-0616efe7e63a.png">

**Comment by mgatus** [comment]
Hi @tmcconechy we tried your suggestion, but it created a new option instead of replacing the options on the Selectbox, please see screenshots below.

![screenshot_1](https://user-images.githubusercontent.com/1150099/45474481-77db1e80-b76c-11e8-8ddf-43b71c6afff8.png)
![screenshot_3](https://user-images.githubusercontent.com/1150099/45474483-77db1e80-b76c-11e8-8583-4784c3c88122.png)

is there any other workaround options that We can do to replace the language?

cheers,
Marvi

**Comment by tmcconechy** [comment]
OK, seems like the workaround wont work. But this bug is fixed (although we are awaiting translations for next version)

**Comment by mgatus** [comment]
hi @tmcconechy ,
I just want to follow up you on this? :) when can we get the new update
cheers

**Comment by tmcconechy** [comment]
We did not yet get translations back from the translation team for 4.11.0. Expect possibly next month (End Oct release) but they work on their own schedule.

**Comment by mgatus** [comment]
Hi @tmcconechy 

any updates for the translation? :)

thank you,
Marvi
