### ISSUE TITLE
Translations: Incorrect Russian translation for "Show Filter Row"

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5110]
Incorrect Russian translation for "Show Filter Row". It should be "Показать строку фильтра". Screenshot attached

Please assign this issue to Henry Wondergem (Henry.Wondergem@infor.com)

![ShowFilterRow](https://user-images.githubusercontent.com/66057969/115438867-348f9900-a20e-11eb-9295-c84ce952954c.png)

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
Corrected in the June 2021 translation delivery.
