### ISSUE TITLE
Translations: Incorrect Russian translation for "xx Results"

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5111]
Translations: Incorrect Russian translation for "xx Results"

![XXResults](https://user-images.githubusercontent.com/66057969/115439728-327a0a00-a20f-11eb-8f1d-dc9786003893.png)

The word “results” has a wrong ending due complicated Russian rules for nouns after numbers. Possible solution: (результаты: NUMBER) => (results: NUMBER). This refers to ALL strings like “(31 results)”, “(63 results)” etc. in ALL following dialogues where this structure occurs.

Please assign this issue to Henry Wondergem (Henry.Wondergem@infor.com)

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
Corrected in the June 2021 translation delivery.
