### ISSUE TITLE
Dropdown: Backspace key not setting a noSearch dropdown to "blank" value

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#5113]
**Describe the bug**
In previous versions, the backspace key could be used on a dropdown (with it closed), to set the value to blank when using a noSearch dropdown. The delete key still works to do this, but backspace is limited to only OSX. 

**To Reproduce**

1. Go to http://localhost:4000/components/dropdown/example-no-search-lsf.html
2. Tab to the first dropdown, type "5" to select 5, then hit backspace.
3. Note that it does not set the dropdown to blank.
4. Press "Delete" key and note that it does set the dropdown to blank.

**Expected behavior**
A noSearch dropdown that contains a blank value should clear out when using backspace. A customer reported this change in behavior to us.

**Version**

- ids-enterprise: 4.51-dev

**Platform**
 - Infor Application/Team Name: Infor Lawson
 - Device: Browser
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 90

**Additional context**
Talked about this one with @EdwardCoyle. In dropdown.js -> handlePseudoElemKeydown, I think this line ` if ((!isOSX && key === 'Delete') || (isOSX && key === 'Backspace')) {` could be changed to `if ((!isOSX && key === 'Delete') || (isOSX && key === 'Backspace') || key === 'Backspace' && this.settings.noSearch) {`.

**Comment by awbuboltz** [comment]
Hey all, any timeline on this one? We've got a customer looking for the fix.

**Comment by tmcconechy** [comment]
I'll put in for next sprint planning - will probably be able to add it. Then it will be done end of July for Aug release.

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://main-enterprise.demo.design.infor.com/components/dropdown/example-no-search-lsf.html
![image](https://user-images.githubusercontent.com/45757016/125402167-abd86180-e3e6-11eb-9660-8aecde385e62.png)
