### ISSUE TITLE
Tooltip: Misplaced tooltip when hovering on bar-stacked chart label

### ISSUE THREAD

**Issue by rdugenia** [infor-design/enterprise#5114]
**Describe the bug**
When the text on the Y-axis label is long, ellipsis will be in place and turn to gray color. When hovered on the ellipsis label, a tooltip will show the complete text value but the tooltip is appearing on the far left of the screen.
![misplacedTooltip](https://user-images.githubusercontent.com/78482539/115492259-0ce31400-a294-11eb-8c62-ce1cb4aaba90.gif)

**To Reproduce**
1. Check out the html file on the attached zip file
2. Hover mouse on the label with long text
[misplacedTooltip.zip](https://github.com/infor-design/enterprise/files/6347800/misplacedTooltip.zip)

**Expected behavior**
Tooltip should be displayed within the hovered label and text should be readable

**Version**
- ids-enterprise: 4.38

**Screenshots**
<img width="952" alt="misplacedTooltip" src="https://user-images.githubusercontent.com/78482539/115491926-6d258600-a293-11eb-9cca-fc77488d1acf.png">
<img width="952" alt="textNotReadable" src="https://user-images.githubusercontent.com/78482539/115491933-70b90d00-a293-11eb-82d8-65027f1a1443.png">

**Platform**
 - Browser Name: Chrome, Edge

**Additional context**
Misplaced tooltip is not occurring on Area chart type

**Comment by tmcconechy** [comment]
Closing stale issues
