### ISSUE TITLE
Tabs: Close() deprecation message when clicking through tabs

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#5116]
**Describe the bug**
When moving from one tab that contains a datepicker to another tab, a close() deprecation message pops up in the debugger console.

**To Reproduce**
1. Go to the attached html page
2. Note that the focused tab has a datepicker field 
3. Click on a different tab
4. See deprecation message in console

**This occurs both when the calendar is open and closed upon clicking another tab

[test-bordered-tabs-lsf.zip](https://github.com/infor-design/enterprise/files/6353426/test-bordered-tabs-lsf.zip)
**Expected behavior**
It is expected that no errors would occur.

**Version**
- ids-enterprise: v.4.51.0-dev

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: 90.0.4430.72 (Official Build) (64-bit)

**Comment by jbrcna** [comment]
working as expected. moving ticket to Done
v4.51.0-dev
https://main-enterprise.demo.design.infor.com/components/tabs/test-bordered-tabs-lsf.html
