### ISSUE TITLE
Locale: Exclamation mark should be displayed on the right-hand side in all languages

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5119]
Exclamation mark should be displayed on the right-hand side in all languages

- English: Exclamation mark is displayed on the right-hand side
- Languages: Exclamation mark is displayed on the left-hand side

Example: English vs Russian

![ExclamationMark](https://user-images.githubusercontent.com/66057969/115693822-2cdc0b80-a358-11eb-9597-5930aee51dc5.png)

From GRC dev:

We have reproduced the issue in below fork code:

https://github.com/JangleShubham/enterprise-ng.git 

Please go to http://localhost:4200/ids-enterprise-ng-demo/tabs-vertical after running this project and go into Contract tab, create validation error, it will show exclamation error icon at left side.

Please see attachment for more detail.

![image-2021-04-22-14-24-01-867](https://user-images.githubusercontent.com/66057969/115693837-2fd6fc00-a358-11eb-9974-b8e8a5ff0e46.png)

Please ask enterprise team to follow above steps to reproduce the issue.

**Comment by tmcconechy** [comment]
As a note i can't reproduce this on the example we have:

https://main-enterprise.demo.design.infor.com/components/validation/test-error-on-tab-vertical.html?locale=ru-RU
and
https://main-enterprise.demo.design.infor.com/components/validation/test-error-on-tab-vertical.html?locale=en-US

I cant seem to run your project its giving a ton of errors.... Perhaps you can put it in https://stackblitz.com/edit/ids-quick-start-940 (make a fork and add the code). Or perhaps you can try a newer version?

**Comment by cpinatel7** [comment]
From: Shubham Jangle <shubham.jangle@infor.com> 
Sent: vendredi 23 avril 2021 05:49
To: Christophe Louis Pinatel <Christophe.Pinatel@infor.com>
Subject: RE: [infor-design/enterprise] Locale: Exclamation mark should be displayed on the right-hand side in all languages (#5119)

Hello Christophe,

I guess issue is there in provided links by Tim
https://main-enterprise.demo.design.infor.com/components/validation/test-error-on-tab-vertical.html?locale=ru-RU
and
https://main-enterprise.demo.design.infor.com/components/validation/test-error-on-tab-vertical.html?locale=en-US
For all languages including en-US exclamation error icon is appearing at left side in above examples and also in GRC as well.

Can you please check? Or the issue is something different(I might be thinking of something else) 

Thanks,
Shubham Jangle

**Comment by tmcconechy** [comment]
Yes the icon seems to appear on the left side? Is there anything wrong with that? For example anything from a translation point of view?

**Comment by cpinatel7** [comment]
It's a minor issue but there is no justification / requirement to display ! on the right in English and on the left in languages. It should be on the right-hand side. Thanks

**Comment by tmcconechy** [comment]
Ok agreed it probably makes sense on the right

**Comment by cpinatel7** [comment]
Still valid. Thanks

**Comment by tmcconechy** [comment]
@cpinatel7 i think we need to know what languages in our set should be on the right and which should be on the left?
Is this a true statement: Its on the left in English and EVERY other language its on the right?

**Comment by cpinatel7** [comment]
I think we need to understand the logic first. Example: In English? Why one ! on the left and one ! on the right? What's the logic? Thanks

![image](https://github.com/infor-design/enterprise/assets/66057969/0a9446b6-233c-498e-870e-f35b125c8e19)

**Comment by tmcconechy** [comment]
@cpinatel7 there really isnt any logic to these. But for the input field i think its common to put the error at the front of the text unless its Right To Left. But for the tab error we could put it on either side (design desicion).

So i think for both cases we should just have the error on the left unless its a RTL language? Unless there are language concerns with either?

One other factor is there needs to be room for it on the left so thats why in some cases we stick it on the right. 

From your side can you see any translation recommendations on this as im not really sure we have logic and its well thought out so we can do it how makes sense

**Comment by cpinatel7** [comment]
My recommendation is to be consistent. **Same approach in all languages including English.** In short, I agree with your statement "i think for both cases we should just have the error on the left unless its a RTL language".

I think an exclamation point sign in red triangle would be better than the current icon:
![image](https://github.com/infor-design/enterprise/assets/66057969/4466e204-4c08-4bd3-8305-9a0c5c441820)

**Comment by ericangeles** [comment]
@tmcconechy, do you think we should ask for design feedback here?

**Comment by tmcconechy** [comment]
For the icon change i dont think we want to change the icon. I think its as expected. But we can check with @talkaboutdesign what do you think about making the tab errors on the left?
