### ISSUE TITLE
Input:  Field is not working in a Toolbar 

### ISSUE THREAD

**Issue by jvang01** [infor-design/enterprise#5122]
**Describe the bug**
Input field in the toolbar is being hidden in the New theme.

**To Reproduce**

1. Go to http://localhost:4000/components/toolbar/example-toolbar-input.html
2. inspect the html
3. there is a input field there, but it's being hidden via css class .is-overflow

**Expected behavior**
The input field should be visible:
![a](https://user-images.githubusercontent.com/64548726/115747744-2733f500-a35b-11eb-9131-1819576618dc.jpg)

Actual:
![b](https://user-images.githubusercontent.com/64548726/115747770-2dc26c80-a35b-11eb-9510-121f2842ee9f.jpg)

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor Lawson (Portal)
 - Device: Browser
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version:  89.0.4389.128 

**Additional context**

**Comment by tmcconechy** [comment]
This is not 100% a regression but marking it as such. Its more like it works in classic theme and not new theme.
But the fix is simple...

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
