### ISSUE TITLE
Hierarchy: Changes to getActionMenuItems() is breaking JSON.stringify of the data object

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5124]
Describe the bug
Changes to the method getActionMenuItems is breaking the JSON.stringify of the data object.

1. Go to 'example-context-menu-with-details.html'
2. Open the browser's debugger
3. For Kaylee Edwards record, click on '...' to open the menu items
4. Click on 'Profile' menu item
5. In the console the displayed value for eventInfo.actionReference is just "{"

Expected behavior
The entire value for the actionReference is displayed

Version
- ids-enterprise: v4.39.0-dev

Screenshots

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/115768660-370a0400-a370-11eb-89ab-f14e7749c4ad.png)

**Comment by janahintal** [comment]
QA Passed. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/116687729-36184880-a9e8-11eb-93a0-5eb670ceadfa.png)
