### ISSUE TITLE
Field Filter short: text is not displayed in dropdown

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5126]
**Describe the bug**
after selecting a item in the dropdown, the text is not displayed in the field

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-filter/example-short.html
2. Click on dropdown and select an item
3. Notice that the selected text is not displayed in the field
5. Click on dropdown again and you will see the item you selected highlighted in blue

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/115719881-1a40f100-a3af-11eb-9961-744148f0c59e.png)

**Version**
- ids-enterprise: v4.51.0-dev

**Screenshots**
![Large GIF (536x508)](https://user-images.githubusercontent.com/56722184/115720801-fa5dfd00-a3af-11eb-8865-43b4fbf97852.gif)

**Platform**
All major browsers

**Additional context**
also please try in EDGE in both themes. when you open the dropdown, The arrow icon is misaligned
https://main-enterprise.demo.design.infor.com/components/field-filter/example-short.html
![image](https://user-images.githubusercontent.com/56722184/115721089-44df7980-a3b0-11eb-9fa1-b79db5f40226.png)

**Comment by jbrcna** [comment]
the issue is now fixed. However, when you switch to classic theme the label/text appears on the left side (dropdown-wrapper)
v4.63.0-dev
<img width="403" alt="image" src="https://user-images.githubusercontent.com/56722184/165674165-377ba603-2fde-4c7f-bfde-d8006f5e3a92.png">

`label issue on firefox - classic theme`
<img width="380" alt="image" src="https://user-images.githubusercontent.com/56722184/165674588-26d7b4a3-7267-4c71-8958-80115c71d914.png">

**Comment by ericangeles** [comment]
@sesbrenosienna can you take a look at this one? Thanks!

**Comment by jbrcna** [comment]
this is now working as expected. thank you
https://4630-beta0-enterprise.demo.design.infor.com/components/field-filter/example-short.html?theme=classic&mode=light&colors=2578a9
<img width="619" alt="image" src="https://user-images.githubusercontent.com/56722184/166196103-d2952e32-a3d6-4f07-a758-67d463764b7e.png">
