### ISSUE TITLE
 Soho.Locale.parseDate() unable to parse some datetime locale correctly

### ISSUE THREAD

**Issue by aalbaAtInfor** [infor-design/enterprise#5129]
**Describe the bug**
When parsing locale with 12 hour format that have their own AM/PM like Chinese / zh-CN 上午 / 下午. it's not parsing the time portion correctly. 

**To Reproduce**

Load locale that you want to parse with.
`<script src="scripts/lime/resources/zh-CN.js"></script>`  

**Expected behavior**  
```
Soho.Locale.parseDate('2021/4/21 下午7:47', { dateFormat: 'yyyy/M/d ah:mm', locale: 'zh-CN' })
Result: Wed Apr 21 2021 07:47:00 GMT+0800 (Singapore Standard Time)
```

It's not parsing the time part correctly.  this should be 19:45:00

 
When parsing other dates like en-US format, it parses correctly

```
Soho.Locale.parseDate('4/21/2021 07:45 PM', { dateFormat: 'M/d/yyyy h:mm a', locale: 'en-US' })
Result: Wed Apr 21 2021 19:45:00 GMT+0800 (Singapore Standard Time)
```  

EU(Germany) Datetime format parses correctly  
```
Soho.Locale.parseDate('21.04.2021 19:45', { dateFormat: 'dd.MM.yyyy HH:mm', locale: 'de-DE' })
Result: Wed Apr 21 2021 19:45:00 GMT+0800 (Singapore Standard Time)
```

**Version**

```
IDS Enterprise Components - v4.38.1
Date: 2021-03-18T14:53:13.017Z
```

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor CRM Cloud Edition
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 90.0.4430.85 (Official Build) (64-bit)

**Additional context**
This function will be used with soho datepicker in CRM CE Reminders Widget, since the datepicker will return the datetime in the current locale, like in the Chinese Locale example, it needs to be formatted back to a valid javascript date object.

**Comment by tmcconechy** [comment]
This can be reproduced by 
1. go to https://master-enterprise.demo.design.infor.com/components/locale/test-translations.html?locale=zh-CN
2. type` Soho.Locale.parseDate('2021/4/21 下午7:47', { dateFormat: 'yyyy/M/d ah:mm', locale: 'zh-CN' })` in the console. 

As noted its not working with chinese AM/PM...Should also add a locale test for this.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
