### ISSUE TITLE
Error messages duplicate

### ISSUE THREAD

**Issue by darrenosena** [infor-design/enterprise#513]
**Describe the bug**
Error messages are being duplicated

**Expected behavior**
Error messages should be appended only if it's not existing in the current data

**Screenshots**
![image](https://user-images.githubusercontent.com/41884285/43376815-668c45e6-93ef-11e8-943c-44f9bd683300.png)

![image](https://user-images.githubusercontent.com/41884285/43381754-3d33a9f0-9408-11e8-9173-5885ef33c1fa.png)

**Additional context**
All control specific error message are being stored in control.data('errormessage'), also error messages are being formatted with a break and bullet and then get appended.

The added line of code fails to do the correct checking.

 **if (dataMsg === appendedMsg) {
        // No need to add new message
        return;
 }**

For example 
 *** var dataMsg = loc.data(type + 'message'); is locdata('errormessage')

![image](https://user-images.githubusercontent.com/41884285/43376865-abf35fde-93ef-11e8-92b8-e8ad615e2640.png)

![image](https://user-images.githubusercontent.com/41884285/43376878-b9ed374a-93ef-11e8-90c4-385c74b67324.png)

![image](https://user-images.githubusercontent.com/41884285/43376881-c00f8f1a-93ef-11e8-817e-2c175eca4b25.png)

Supposedly, the appendedMsg should not be appended as it's already existing in the dataMsg.

**Comment by tmcconechy** [comment]
This is a duplicate issue should be fixed by the pending PR https://github.com/infor-design/enterprise/pull/503
