### ISSUE TITLE
"Toast" component usage discrepancy in Product vs Components 

### ISSUE THREAD

**Issue by clazarev** [infor-design/enterprise#5133]
There is a discrepancy in how "Toast" component is intended to be used in "Product" vs "Component".
In Product is says 
> Toasts are used to display confirmations of success, failure, or other statuses of system processes related to a user’s workflow. If a user submits a form, a toast will confirm the successful or unsuccessful completion of that submission. Toasts are dismissible via the “close” icon or the escape key. If not dismissed, the toast will hide after a configurable amount of time.

so seems to be for the **current view/page**, however when I open "Toast" in "Components"
it says different
> Best for showing feedback about a system process that is not related to the current view.

**Comment by tmcconechy** [comment]
Ok good catch, I think we should just go with the product section text as it’s more complete, so will make that change soon

**Comment by tmcconechy** [comment]
For this lets edit the https://github.com/infor-design/enterprise/blob/main/src/components/toast/readme.md to have the same contents as https://design.infor.com/product/components/toast so its not a discrepancy

**Comment by tmcconechy** [comment]
This was done here https://github.com/infor-design/enterprise/commit/a073ce4480e14f53cf1ea43d2ae48365ab5652e4 so closing
