### ISSUE TITLE
Modal forms are too jumpy 

### ISSUE THREAD

**Issue by jamie-norman** [infor-design/enterprise#5134]
**Is your feature request related to a problem or use case? Please describe.**
Modals forms adjust width when text is entered/rendered on the fly. There isn't really a minimum width rule. Single column select/lookups seem too narrow. Forms with select/lookups that display a description next to them after selection, or fields that appear upon progressive disclosure also cause the form to change size. It makes the form "jumpy," a poor user experience.  
**Describe the solution you'd like**
Likely we need to have a fixed width on the desktop, given that it could be difficult to know how wide to build the form before it renders. Maybe the form stays rendered at the initial size, but with a minimum width. 
**Describe alternatives you've considered**
Landmark could handle the coding for this, but concerns with code conflicts.
**Additional context**
And what application do you work on? [e.g. {Infor XYZ}]
Landmark applications. 
Landmark ticket that will depend on this feature: https://jira.lawson.com/browse/LMCLIENT-33613

**Comment by tmcconechy** [comment]
Not really sure what we would do here. However we made it in a way that the modal width can be whatever you want.
Also we suggest that there is one row of fields in the form and they are 100%. Other than that this is a bit vague.

Maybe we need an example to fix?

**Comment by jamie-norman** [comment]
![modal size changes](https://user-images.githubusercontent.com/44705854/116092531-7f286f80-a66b-11eb-9763-5a0d6e99d960.gif)

**Comment by jamie-norman** [comment]
Quick example where you can see the width change based on the manufacturer description coming in. MANY Landmark forms work this way.  App developers have coded lots of variations to this, outside of your suggestion. Normal technical debt.Not sure what the best approach would be, Tim, but I think we need to start with IDS.

**Comment by tmcconechy** [comment]
Is it just "jumpy" because you use 3 different modals in the pattern? If so maybe the pattern needs to be changed somehow. Maybe thats the problem but still finding this issue to need more action points.
So still not seeing what we could do about it. We just present a modal and you use it how you want.

Whats the suggestion? @EdwardCoyle isnt there a way to have the modals not "shut" when another opens?

**Comment by pwpatton** [comment]
@tmcconechy is there a method where the dialogue can choose an initial size and not change once content is set except for browser resizing of width and height. Sorta like Jira  does?

One issue we have is when we place tabs on a modal the modal form changes width and height when switching between tabs with varying content.

**Comment by tmcconechy** [comment]
Yes, if you make the main modal div have a fixed css height and width it will do that. Otherwise it sizes based on content.
But still not sure i understand the issue here...

**Comment by pwpatton** [comment]
if I have a fixed css height will it still be responsive? 

Perhaps something like this would give me both?
```
landmark-modal {
   height: 200px;
   min-height: 100px;
   max-height: 300px;
}
```

**Comment by pwpatton** [comment]
I suppose we could accomplish something like this by listening to a resize event and adjusting the height and width then?

**Comment by tmcconechy** [comment]
Actually responsive you would probably need a whole new set of css rules (for every case)....You could use the resizeObserver? A whole bunch of options come into play here https://github.com/infor-design/enterprise/blob/main/src/components/modal/modal.js#L47-L49

I think the use case seems a little unclear.. At first i thought it was different modals poping up on eachother and closing the other one? I've never said this before but maybe use nested modals that open on top of each other? Or popups? (just an idea without fully understanding the entire use case but seems like something wrong more in the pattern not the form size itself...)

**Comment by EdwardCoyle** [comment]
I'm not sure the nesting of modals is the problem.  From what I can tell the modal's size is shifting as its content loads, so whatever size is determined initially is changing after the fact, causing the "jumpiness".

I agree with the assessment that fixed widths/heights on the modal can help, but it's tricky.  You guys are on the right track with listening for a resize event and adjusting based on the breakpoint (desktop/tablet/mobile/etc).  This might be the best fix for the components we currently ship.

Offhand I'm not sure what's occurring first (grid render, or modal render), so it may even be a problem with the integration of those two components. Overall (future) what could help is if we can get a handle on the true size of columns/rows in the Datagrid and set them before the modal has a chance to calculate, but I suspect that's a deeper problem in the lifecycle somewhere and won't be easy to fix.

**Comment by tmcconechy** [comment]
Closing this for now as i dont have a solution for the components, seems like an application pattern problem. But if you think of something we can add feel free to mention and i will reopen
