### ISSUE TITLE
FieldOptions: wrong placement of x icon in searchfield

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5138]
**Describe the bug**
the x icon in clearable Searchfield is outside the field.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-options/example-index.html
2. Scroll Into Clearable Searchfield
3. Enter some text
5. Try also in compact mode

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/116201221-db72b880-a76b-11eb-9738-f379117d8edf.png)

**Version**

- ids-enterprise: v4.51.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/116200907-7fa82f80-a76b-11eb-9acd-7f031be8227d.png)

**Platform**
All

**Additional context**

**Comment by jbrcna** [comment]
Thanks @ericangeles

**Comment by jbrcna** [comment]
**Test Failed**
The issue on the placement of x icon in searchfield is now resolved.
![image](https://user-images.githubusercontent.com/56722184/120486968-1eb5ec00-c3e8-11eb-8cad-fba7c00b4e63.png)
However, the test failed on the ff steps
`Test this on Compact Mode, then follow above steps`
`Additional: Test all the components to make sure field options are align correctly`
v4.52.0-beta0
https://4520-beta0-enterprise.demo.design.infor.com/components/field-options/example-index
![image](https://user-images.githubusercontent.com/56722184/120486171-5c664500-c3e7-11eb-8f81-70c13d99a102.png)
_screenshot (Mac/Chrome)_

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
