### ISSUE TITLE
FieldOptions: no init misaligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5139]
**Describe the bug**
The fieldoptions in color picker is not properly aligned

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-options/example-no-init.html
2. Examine field options on each field
3. Scroll down to Color picker then open field options

**Expected behavior**
field options should be properly aligned
![image](https://user-images.githubusercontent.com/56722184/116200381-d9f4c080-a76a-11eb-85d7-b0f3324ab8c0.png)

**Version**

- ids-enterprise: v4.51.0-dev

**Screenshots**
_snap on Mac/Safari_
![image](https://user-images.githubusercontent.com/56722184/116196022-8c298980-a765-11eb-8460-b0c6d3c169e9.png)

**Platform**
All major browsers

**Additional context**
_snap on EDGE_
![image](https://user-images.githubusercontent.com/56722184/116196189-c09d4580-a765-11eb-8963-51fa64dd317b.png)

**Comment by jbrcna** [comment]
QA Failed.
This works fine in chrome but **failed** in `Mac/Safari`
v4.52.0-dev
https://main-enterprise.demo.design.infor.com/components/field-options/example-no-init.html
![image](https://user-images.githubusercontent.com/56722184/119589790-254fcc80-be06-11eb-9cab-7de40059d977.png)

**Comment by jbrcna** [comment]
**QA Failed**
The issue still persists on Firefox browser. moving this to failed column
`Click the field option, it should perfectly align with the component`
v4.52.0-beta0
https://4520-beta0-enterprise.demo.design.infor.com/components/field-options/example-no-init.html
`Firefox`
![image](https://user-images.githubusercontent.com/56722184/120488696-9afcff00-c3e9-11eb-81c4-725bc2a35ab1.png)
![image](https://user-images.githubusercontent.com/56722184/120488712-9d5f5900-c3e9-11eb-90e0-0978e0bb24c3.png)

**Comment by ericangeles** [comment]
@jbrcna what version of firefox and OS by the way?

**Comment by jbrcna** [comment]
@ericangeles Browserstack Windows 10, 88 Latest Firefox.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
