### ISSUE TITLE
[Date Picker]: Unnecessary dates are marked on hover

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#514]
**Describe the bug**
On the Date Picker with legends, hovering on certain dates even without clicking marks them with the colored legend.

**To Reproduce**
1. Go to http://490-beta0-sohoxi.demo.design.infor.com/components/datepicker/example-legend.html
2. Open the DatePicker
![image](https://user-images.githubusercontent.com/41028784/43378122-4e7d5046-93f7-11e8-93fe-4b0d24f7f081.png)
3. As seen above, the dates January 12, 18, 19, 24 & 25 are already marked with colored legends.
4. Move to the next month which is February.
![image](https://user-images.githubusercontent.com/41028784/43378153-80a5150e-93f7-11e8-86be-ea1a03d54438.png)
5. No dates are marked in the weekdays. Now, hover your mouse in the dates that are in the same place previously as the marked dates in January.
![image](https://user-images.githubusercontent.com/41028784/43378176-a660ec50-93f7-11e8-885e-e7746f8c694a.png)
6. Those dates will now be marked even if user just hovered the mouse.

**Expected behavior**
No dates should be marked by just hovering the mouse.

**Platform**
 - All Browsers

**Comment by NathanLouisBarcial** [comment]
Hi @EdwardCoyle, issue still occurs in http://490-rc1-sohoxi.demo.design.infor.com/components/datepicker/example-legend.html , not sure if I could re-open this ticket.

**Comment by tmcconechy** [comment]
This didnt make it into rc1 due to code freeze. It will be in 4.10 and you can test it out here instead http://master-enterprise.demo.design.infor.com/components/datepicker/example-legend.html

**Comment by NathanLouisBarcial** [comment]
Alright, thanks for the clarification.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datepicker/example-legend.html
Passed QA testing
