### ISSUE TITLE
Icons: New Icon Requests

### ISSUE THREAD

**Issue by afredrick-ba** [infor-design/enterprise#5143]
Request for icons dealing with mail merge and templates:

- Manage Templates
- Template Properties
- Save as New Template
- Convert Template
- Start Mail Merge

We need to be able to differentiate the Save as Template from the standard Save button as these are embedded in the standard Microsoft Word toolbar.

For context, here are screenshots using placeholder (non-Infor) icons
![image](https://user-images.githubusercontent.com/83303613/116285561-157b9480-a743-11eb-92b6-57396113c864.png)
![image](https://user-images.githubusercontent.com/83303613/116285282-d77e7080-a742-11eb-9cf0-cabb3f227dec.png)
![image](https://user-images.githubusercontent.com/83303613/116285507-0399f180-a743-11eb-9d61-10fb36aae9fa.png)

**Comment by tmcconechy** [comment]
You mean you want some icons for those things to be created? some of those seem a little specific or wierd for making an icon for.
Did you check all existing ones. I know we have one that looks like a templatie thing (columns maybe) and a mail one and some for processing (in-progress)

https://design.infor.com/product/identity/icons

**Comment by afredrick-ba** [comment]
Yes, please. I did look at existing icon set, but we have already used that icon elsewhere in the client and my stakeholders are looking for something more specific to templates and mail merge. Perhaps a base template icon with smaller sub components to indicate ***@***.***D73B53.4E8396D0], properties ***@***.***D73B53.4E8396D0] , manage ***@***.***D73B53.4E8396D0]
 ***@***.***D73B53.4E8396D0]
For Start Mail Merge we are looking for something to show “merging”. I also tried reversing the process.png ***@***.***D73B53.4E8396D0] . The in-process.png is under consideration for Convert Template.

Thank you!
Angie Fredrick

**Comment by tmcconechy** [comment]
Ok we can review these. It takes a while...

**Comment by afredrick-ba** [comment]
Thank you. Also are there upscaled sizes of the standard icons? We are looking for 24x24, 32x32 and 48x48 versions of some icons.

**Comment by tmcconechy** [comment]
We dont use those sizes however, you can perhaps use css to style the svg icons.

**Comment by katieinfor** [comment]
@kevinwhitedesign I'll create a Jira ticket and add to Design backlog. Thanks!

**Comment by katieinfor** [comment]
Jira ticket: https://jira.infor.com/browse/UXD-2493

**Comment by tmcconechy** [comment]
closing this issue until https://jira.infor.com/browse/IDS-99 has it covered
