### ISSUE TITLE
Personalization: Hyperlinks are not visible using Dark theme and non default color

### ISSUE THREAD

**Issue by drinkaj** [infor-design/enterprise#5144]
Hyperlinks are not visible using Dark theme and non default color

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/personalize/example-classes.html
2. Note there are two hyperlinks visible. Incidents and More Info. See light_default_color.png attachment
2. Click on overflow menu in the toolbar and change the Mode to Dark and the Colors to Amber.
3. Note the two hyperlinks disappear. See dar_amber_color_nolinks.png attachment
4. If you hover the mouse over to were the hyperlinks were when visible then they appear until you move the mouse away. See dark_amber_color_hoveroverlinks.png attachment.
![dark_amber_color_noLinks](https://user-images.githubusercontent.com/6230418/116315060-9bb0ce80-a775-11eb-8ced-566b680aac7f.png)
![dark_amber_color_hoveroverlinks](https://user-images.githubusercontent.com/6230418/116315061-9c496500-a775-11eb-95e9-d7732eb9f330.png)
![light_default_color](https://user-images.githubusercontent.com/6230418/116315062-9c496500-a775-11eb-9aa7-afc5b26a2396.png)

**Expected behavior**
Hyperlinks should be visible no matter what mode or color is being used. 

**Version**

- ids-enterprise: 4.51.0-dev

**Screenshots**

**Platform**
 - Browser Name: Chrome
 - Browser Version: 90.0.4430.93 (Official Build) (64-bit)]

**Additional context**

**Comment by janahintal** [comment]
QA Passed. Thank you.
Verified on all Theme and Modes

![image](https://user-images.githubusercontent.com/45757016/122751786-c9704a80-d2c2-11eb-9839-0e01b29768d7.png)
![image](https://user-images.githubusercontent.com/45757016/122751846-dab95700-d2c2-11eb-9503-973421912936.png)
