### ISSUE TITLE
Editor: Word wrap is missing after changing to a Hyperlink

### ISSUE THREAD

**Issue by NicholTamayo** [infor-design/enterprise#5145]
**Describe the bug**
Observed that there's no word wrap after changing a paragraph (or any 2 line sentence) into hyperlink.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-clickable-links.html
2. Highlight the second paragraph (or for the 1st paragraph please removed the link first before selecting it)
3. Click "Insert Anchor" icon.
4. Click "Insert" button.

**Expected behavior**
The paragraph/sentence became a hyperlink while retaining its word wrap.

**Version**
- ids-enterprise: 4.37.0/4.38.1/4.50.2

**Screenshots**
![Word wrap is missing after changing to a Hyperlink](https://user-images.githubusercontent.com/79066908/116368668-2a3b5380-a83b-11eb-87aa-c01ab7677d73.gif)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Window 10
 - Browser Name: Chrome, Safari
 - Chrome/Version Version 90.0.4430.72 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Fix for this also fixes one part of https://github.com/infor-design/enterprise/issues/5117

**Comment by jbrcna** [comment]
QA Passed
v4.51.0-dev
https://main-enterprise.demo.design.infor.com/components/editor/example-index.html
![image](https://user-images.githubusercontent.com/56722184/116639563-64bc0200-a99b-11eb-83a8-b8650ffc3b9d.png)
