### ISSUE TITLE
Forms: spinbox looks off in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5146]
**Describe the bug**
Forms: spinbox looks off in responsive view

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/form/example-inputs.html
2. Open developer console
3. Make it responsive to 1577 x 836 50% or 75%

**Expected behavior**
The spinbox buttons should not look cut off

**Version**
4.51 - ids

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/116401781-371d6e80-a85e-11eb-8e41-9ccbd4b2befa.png)
![image](https://user-images.githubusercontent.com/45757016/116401833-469cb780-a85e-11eb-8a97-92cac1ed7b41.png)

**Platform**
All major browsers and devices

**Additional context**
N/a

**Comment by janahintal** [comment]
The issue still exists in https://4520-beta0-enterprise.demo.design.infor.com/components/form/example-inputs.html?theme=new&mode=light&colors=0066D4

Screenshot below
![image](https://user-images.githubusercontent.com/45757016/120464639-bb1fc480-c3cf-11eb-981d-0558250e534b.png)

**Comment by tmcconechy** [comment]
@janahintal we noticed this as well but its a "cross pixel effect" try different zoom levels and try different monitors. You cant always see it and we cant really actually fix it that easily

**Comment by janahintal** [comment]
Hi @tmcconechy. Please note that I'm experiencing the issue in Windows Chrome Browser. 

This screenshot was provided to me by James. 
![image](https://user-images.githubusercontent.com/45757016/120789413-28fcf500-c564-11eb-9292-9eba2db8a462.png)
![image](https://user-images.githubusercontent.com/45757016/120789640-71b4ae00-c564-11eb-9249-a2f6a4ddc332.png)

Seems working fine on his end, using macOS but not in Windows. 
Let me know if this should be fix as well. If it's not required, then I can move this to Done Thank you.

**Comment by tmcconechy** [comment]
I think its not a big deal, unless a customer/team notices it so i would skip for nw
