### ISSUE TITLE
Locale: In zh-CN, the first day of the week should be Monday (and not Sunday)

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5147]
In zh-CN, the first day of the week should be Monday (and not Sunday)

In CRM CE, Monday is the first day of the week but the IDS date picker shows Sunday as the first day

![zh-CN](https://user-images.githubusercontent.com/66057969/116406806-f6efc900-a828-11eb-8298-37d46911ce83.png)

cc: stella.huang@infor.com

**Comment by tmcconechy** [comment]
@cpinatel7 what about :

zh-TW and zh-Hant and zh-Hans

**Comment by cpinatel7** [comment]
CRM CE is only available in zh-CN / zh-Hans but it should be Monday for zh-CN / zh-Hans and zh-TW / zh-Hant. Thanks

**Comment by tmcconechy** [comment]
@cpinatel7 are you sure its monday for zh-TW/zh-Hant. Stella mentioned she checked on a Chinese Traditional Operating System it ist was sunday for that. So just confirming

**Comment by jbrcna** [comment]
this issue is now resolved. moving this ticket to Done. thank you
v4.51.0-dev
https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=zh-CN
![image](https://user-images.githubusercontent.com/56722184/116640261-1576d100-a99d-11eb-9f6f-1b4931d14baf.png)
