### ISSUE TITLE
Forms: read only Look up field issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5149]
**Describe the bug**
you can open the lookup even if it's a read-only element

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/form/example-readonly-inputs.html
2. Click on the Lookup icon to open Lookup
5. Try to  select and change the value
6. See error
7.  A read-only element should not be editable

**Expected behavior**
should not be able to open lookup
![image](https://user-images.githubusercontent.com/56722184/116412274-19093b80-a869-11eb-9502-841e153635c0.png)

**Version**

- ids-enterprise: v4.51.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/116412202-08f15c00-a869-11eb-932e-109f0af37836.png)

**Platform**
all

**Additional context**

**Comment by tmcconechy** [comment]
Regressed from https://4380-beta0-enterprise.demo.design.infor.com/components/lookup/test-states.html so fixing

**Comment by jbrcna** [comment]
this issue is now resolved. thank you
v4.51.0-dev
https://main-enterprise.demo.design.infor.com/components/lookup/test-states.html
https://main-enterprise.demo.design.infor.com/components/form/example-readonly-inputs.html
![image](https://user-images.githubusercontent.com/56722184/116638946-f9256500-a999-11eb-9e5f-2f7c2d4c9067.png)
