### ISSUE TITLE
Translations: Latvian translation for "Required" should be "Obligātais lauks"

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5152]
Translations: Latvian translation for "Required" should be "Obligātais lauks"

![Latvian-Required](https://user-images.githubusercontent.com/66057969/116420176-a7fc6080-a835-11eb-8b4c-0017f7201380.png)

Could you please assign this issue to Henry Wondergem (Henry.Wondergem@infor.com)?

Thanks

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
Corrected in the 2021-05 translation delivery.

**Comment by tmcconechy** [comment]
Is the delivery complete? Or should i wait for an email? Thanks!

**Comment by hwondergem** [comment]
Yes, delivery 2021-06 is complete today!
