### ISSUE TITLE
Mask: Decimal mask doesn't allow a under 1 decimal on second edit

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#5154]
**Describe the bug**
When using a mask with a decimal pattern, if the user attempts to enter a value a second time in the field, the leading decimal point is ignored.

If using the allow leading zero option, you can enter 0.7 and the decimal point is maintained

**To Reproduce**
1. Copy [test-decimal.zip](https://github.com/infor-design/enterprise/files/6393060/test-decimal.zip) into /app/views/components/mask
2. Navigate to /components/mask/test-decimal.html
3. Enter the value .8
4. Blur out of the field, see that the value in it is 0.8
5. Highlight the value and try and enter the value .7
6. See that the . is ignored and that the value is 7 when it should be .7

**Expected behavior**
After highlighting and entering the second value, the value should be .7

**Version**
- ids-enterprise: 4.51.0-dev

**Screenshots**
![BrokenDemicalOnSecondEdit](https://user-images.githubusercontent.com/22107636/116431501-766f9f00-a80d-11eb-9e91-272a340dfafe.gif)
I am attempting to type ".7" in this gif, but the "." isn't appearing.

**Platform**
 - All

**Comment by lipetzan** [comment]
Aging customer issue.

**Comment by tmcconechy** [comment]
Adding to next sprint

**Comment by Sovia** [comment]
I believe this was fixed with https://github.com/infor-design/enterprise/issues/4974, in 4.51.4

**Comment by tmcconechy** [comment]
Yes it seems to be fixed by https://github.com/infor-design/enterprise/issues/4974 in 4.51.4 and 4.52
I will move this to done

**Comment by jbrcna** [comment]
confirming the issue has been resolved. Thanks
v4.53.0-dev
![Large GIF (710x356)](https://user-images.githubusercontent.com/56722184/122864528-6250a580-d357-11eb-826b-206b4cdca1a4.gif)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
