### ISSUE TITLE
Datagrid: Hover on an editable lookup datagrid has flawed styling.

### ISSUE THREAD

**Issue by arturchilangwa-infor** [infor-design/enterprise#5157]
**Describe the bug**

The icon in an editable Iookup cell in SohoDataGrid has flawed hover styling.  

**To Reproduce**

1. Use SohoDataGrid with an editable lookup cell
2. Hover over the editable cell
3. The flaw in the hover should now be showed

**Expected behavior**
Only show the icon while hovering.

**Version**
- ids-enterprise: v4.50.2 
- ids-enterprise-ng: v9.4.4

**Screenshots**
![Hover-editable-lookup-cell](https://user-images.githubusercontent.com/80833325/116511115-3e786280-a8c6-11eb-893d-d022e4914975.gif)

**Platform**

- Infor Application/Team Name: Infor Mongoose
- OS Version: Windows 10
- Browser Name: Chrome
- Browser Version: 90.0.4430.93 (Official Build) (64-bit)

**Additional context**
* Here is the code used that generates our datagrid: 

```typescript
ngOnInit(): void {
        this.datagridOptions = this.initDatagridOptions();
}

private initDatagridOptions(): void {
	const lookupColumns = this.initLookupGridOptions();
	const lookupDataset: IStrings[] = this.service.getStrings();
	const columns: SohoDataGridColumn[] = [];
	columns.push({
           /* ... */ 
	});
	columns.push({
            /* ... */ 
	});
	columns.push({
		id: "name",
		name: "Column name",
		field: "name",
		width: "34%",
		sortable: true,
		editor: Soho.Editors.Lookup,
		formatter: Soho.Formatters.Lookup,
		editorOptions: {
			options: {
				columns: lookupColumns,
				dataset: lookupDataset,
				selectable: "single",
				paging: true,
				pagesize: 25,
				toolbar: {
					title: "Toolbar title",
					results: true,
					keywordFilter: true,
				},
			},
			field: (row: IMap<string>) => {
				const match = row.name;
				if (!match) {
					console.warn("Warning: No current match to dataset.");
				}
				setTimeout(() => {
					this.grid.commitCellEdit();
				});
				return match;
			},
		},
	});

	this.datagridOptions = {
		columns,
		dataset: [],
		paging: true,
		pagesize: 25,
		enableTooltips: true,
		isList: true,
		editable: true,
		toolbar: {
			keywordFilter: true,
		},
	};
	this.buildDataset();
}
```

```html
<div
	soho-datagrid
	id="editable-lookup-datagrid"
	[gridOptions]="datagridOptions"
	(cellchange)="onCellChange($event)"
></div>
```

* Issue might be related to https://github.com/infor-design/enterprise/issues/4963

**Comment by tmcconechy** [comment]
If your using editable / editors you should probably not be using the isList: true styling. So my suggestion is you take that off. That's the correct style for when a grid has editors.

Nonetheless this is a bug we can try and fix at some point.

**Comment by EdwardCoyle** [comment]
Note for Q/A: Fixed a similar issue that should have targeted this same problem on #5180

**Comment by tmcconechy** [comment]
@janahintal not sure i follow this comment? at least the screen shot looks ok. @EdwardCoyle ?

**Comment by EdwardCoyle** [comment]
I see in the screenshot that the popup doesn't have an arrow, but I'm not sure that's related?

**Comment by tmcconechy** [comment]
I saw that too. We do have a seperate issue for that though https://github.com/infor-design/enterprise/issues/5084

**Comment by janahintal** [comment]
Hi @tmcconechy, please see screenshot below I created new scenario. 

Steps:

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Open the date picker and click the action dropdown beside it very quickly

![image](https://user-images.githubusercontent.com/45757016/117770594-b0a65b00-b267-11eb-8c94-3ac9d91a3364.png)

**Comment by janahintal** [comment]
Ohh, I see it now. I will file new minor issue for the above and will move this ticket to done as the icon are now working as expected.. Thanks @tmcconechy :)

**Comment by arturchilangwa-infor** [comment]
Hi, @tmcconechy & @EdwardCoyle 

This issue still exists. 
Could we reopen this issue?
![iCzFP0DAAh](https://user-images.githubusercontent.com/80833325/122902230-9d021000-d34e-11eb-973d-03956b6a00ce.gif)
Versions: 
* ids-enterprise: 4.52.0
* ids-enterprise-ng: 10.1.0

**Comment by tmcconechy** [comment]
OK, it looks like we fixed something else here on the "normal" grid not the islist grid. Will have a look.

**Comment by janahintal** [comment]
QA Passed. Thankyou!
Verified in http://localhost:4000/components/datagrid/example-list-lookup across all browser, theme and modes.
