### ISSUE TITLE
Header: non-collapsible/expanded searchfield x icon is misaligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5158]
**Describe the bug**
the issue exist on Safari browser. looks good in chrome & edge 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-non-collapsible-searchfield.html
2. Enter text in searchfield
3. See error
4. X icon is not properly aligned
5. Go to https://main-enterprise.demo.design.infor.com/components/header/example-searchfield-expanded.html
6. Enter text in searchfield
7. See error
8. X icon is not properly aligned

**Expected behavior**
the x icon should be center aligned vertically and close to the right most edge

**Version**

- ids-enterprise: v4.51.0-dev

**Screenshots**
https://main-enterprise.demo.design.infor.com/components/header/example-non-collapsible-searchfield.html
![image](https://user-images.githubusercontent.com/56722184/116517048-f6c2fc80-a900-11eb-8ccc-d370aed8d3da.png)

https://main-enterprise.demo.design.infor.com/components/header/example-searchfield-expanded.html
![image](https://user-images.githubusercontent.com/56722184/116517610-cb8cdd00-a901-11eb-808a-909d34451654.png)

**Platform**
Mac/Safari

**Additional context**
please see also 
the issue exist on Safari browser. looks good in chrome & edge
https://main-enterprise.demo.design.infor.com/components/header/example-buttons-larger-search.html
![image](https://user-images.githubusercontent.com/56722184/116516207-e78f7f00-a8ff-11eb-9af4-f2c49217e515.png)

**Comment by jbrcna** [comment]
This issue is now resolved. v4.51.0-beta0
https://4510-beta0-enterprise.demo.design.infor.com/components/header/example-searchfield-expanded.html
![image](https://user-images.githubusercontent.com/56722184/116970553-ca392700-acea-11eb-9196-fed8ecdf2934.png)
https://4510-beta0-enterprise.demo.design.infor.com/components/header/example-non-collapsible-searchfield.html
![image](https://user-images.githubusercontent.com/56722184/116970698-066c8780-aceb-11eb-98a2-1ea8c3037c02.png)
https://4510-beta0-enterprise.demo.design.infor.com/components/header/example-buttons-larger-search.html
![image](https://user-images.githubusercontent.com/56722184/116971223-d1ad0000-aceb-11eb-85c0-03b538a78869.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
