### ISSUE TITLE
Accordion Functional and E2e Tests

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#516]
Add some tests for Accordion

See existing tests for example textarea, dropdown, treemap, menubutton, lookup ect for reference. Also see docs/TESTING.MD for commands. Ask for help on sohoxi-dev if needed.

Functional Tests
- Test events that get triggered
- Test events that are listened to
- Test all API methods, most importantly the public ones first and the rest for coverage. (fx enable/disable)
- Test lifecycle methods (init, teardown, destroy, invoke)
- Test setting and that some states are applied

E2e Tests
- Load each test page in the components/<name>/list and test the main ideas of the page, if unsure of the main idea ask on the channel.
- Keyboard

Accordion Specific Test Considerations 
- Special Accordion Public api tests
- App menu Tests
- Example Accordion Click Event
- Example Accordion Lazy Loading
- Example Accordion Panels
- Example Ajax
- Example Disabled
- Example Index
- Test Accordion Inner Pane Icon
- Test Angular No Reroute On Link Click
- Test Close Children On Collapse
- Test Common
- Test Different Header Types
-  Test Expand All
-  Test Expand Collapse All Apis
-  Test Expand On Init
-  Test Landmark Many Nodes
-  Test No Reroute On Link Click
-  Test Six Levels Deep
-  Test Top Level Expanders
-  Test Update Specific Part
-  Test With Contextmenu
-  Test With Expandablearea

Other Tests
- Accessibility tests https://github.com/dequelabs/axe-core
- Other Specific Test Cases from Cindy
- Protractor Image Comparison Tests

**Comment by CindyMercadoReyes** [comment]
This script captures everything needed for the Accordion component. Moving this ticket to the Done folder.
