### ISSUE TITLE
Toolbar: text button alignment issue when in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5160]
**Describe the bug**
Toolbar: text button alignment issue when in responsive view

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
2. Minimize the screen to responsive view
3. Notice the text button alignment

**Expected behavior**
Text button should be aligned

**Version**
4.51 - ids

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/116549550-34874b80-a928-11eb-951e-4090d0eb8f30.png)

**Platform**
All major browser & devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This is just the overflow behavior. Its not possible to fix it
