### ISSUE TITLE
Pager: disappear pager tooltip on 2nd page

### ISSUE THREAD

**Issue by deep7102** [infor-design/enterprise#5161]
**Describe the bug**
First and previous button tooltip disappear after clicking next from the first page.

**To Reproduce**
- Pull and build NG branch ([main](https://github.com/infor-design/enterprise-ng.git))
- Navigate to http://localhost:4200/ids-enterprise-ng-demo/datagrid-standalone-pager
- After clicking next in pager button, the first and previous buttons are gets enable, but the tooltip doesn't show up any more.

**Expected behavior**
Tooltip should work on all pager button and all pages.

**Version**
- ids-enterprise-ng: v9.4.4

**Platform**
- All Browsers

**Additional context**
Related: https://github.com/infor-design/enterprise/issues/4862

**Comment by tmcconechy** [comment]
Closing this as we have it covered on this ticket https://github.com/infor-design/enterprise-ng/issues/1047
