### ISSUE TITLE
Tabs: Go button overlaps x icon in mobile view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5178]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button.html
2. Switch to mobile view

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/117109635-86f8ba00-adb7-11eb-84ac-319f331eaca1.png)

**Version**

- ids-enterprise: v4.52.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/117109699-a263c500-adb7-11eb-9ad1-ea7ecfe9b176.png)

**Platform**
mobile view

**Additional context**
Browserstack Android
![image](https://user-images.githubusercontent.com/56722184/117109926-fbcbf400-adb7-11eb-8807-6fe334791877.png)
Galaxy S21

**Comment by tmcconechy** [comment]
This is very similar to https://github.com/infor-design/enterprise/issues/5173 and i think they should be fixed together

**Comment by jbrcna** [comment]
this is now working as expected. however, this is failing on a specific browser size 767. 
if you test this on browser size `< 767 `or `> 767` this works fine.see below screenshot.
<img width="636" alt="image" src="https://user-images.githubusercontent.com/56722184/169477447-6fdca8a7-f466-4679-a97a-01d74ec1474b.png">

<img width="690" alt="image" src="https://user-images.githubusercontent.com/56722184/169477537-5d220057-e5da-4c31-b3d7-feecd524e9ff.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/56722184/169477560-8fc4db25-ee6e-4db2-86b2-7aa541d0db35.png">

**Comment by davidcarlsonberg** [comment]
I can get to this for Monday.

**Comment by jbrcna** [comment]
QA Failed. v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button.html
<img width="638" alt="image" src="https://user-images.githubusercontent.com/56722184/170486330-886be621-e4f1-4939-993b-5fa1d0fa4aca.png">

Responsive view 767
<img width="862" alt="image" src="https://user-images.githubusercontent.com/56722184/170486505-a112f9fb-6a41-4b96-b4f7-46e8095116c9.png">

**Comment by tmcconechy** [comment]
Yes but it will take a while.

**Comment by iamjamesreyracho** [comment]
QA Passed. Moving this ticket to done.
Android
![image](https://user-images.githubusercontent.com/98729565/171761456-5a4f5ea5-5d19-43a3-b50a-926272db50d0.png)

IPhone
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/98729565/171761472-1d58bfec-968a-4081-88db-89f9111b9191.png)
