### ISSUE TITLE
Home and End Key behavior when in edit mode in editable cell

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#5179]
https://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html

When a user focuses on the editable cell, and press Home key or End Key this is what happens:
Press Home key - editable field cell focus is removed and focus will be placed on the first column of the row
Press End key - editable field cell focus is removed and focus will be placed on the last column of the row

Add a behavior in editable cell under edit mode:
Press Home key - the text cursor will only be placed in front of the text value
Press End key - place the text cursor at the end of the text value

**Comment by tmcconechy** [comment]
To elaborate. The Current home/end key functionality is correct. But if in edit mode it should be ignored so it works in the field to use home/end.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
