### ISSUE TITLE
Tabs: Disabled tab content looks enabled when in different dropdown page

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5183]
**Describe the bug**
Tabs: Disabled tab content looks enabled

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/example-enable-disable.html?theme=classic&mode=light&colors=2578a9
2. Click Dropdown Page 3
3. Click Disable button

**Expected behavior**
All content must be disabled

**Version**
4.520 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/117277620-9ef13c00-ae92-11eb-9bb5-c29469770ae8.png)

**Platform**
All major os and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping this for now
