### ISSUE TITLE
Application Menu is unexpectedly closing when clicking headers in the mobile breakpoint

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#519]
Originally reported by @vonnyw

**Describe the bug**
When an application menu is open below the mobile breakpoint threshold, and one of its accordion headers is clicked, the menu is closing unexpectedly -- even if the `dismissOnClickMobile` setting is set to `false`.

**To Reproduce**
- Go to http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-container.html
- Resize the browser viewport to fit beneath the Mobile breakpoint (767px or less)
- Open the Application Menu using the hamburger
- Click/Tap on any of the accordion headers
- Also clicking plus and minus icons should not close the menu

The Application menu is unexpectedly closing.

**Expected behavior**
The Application menu should remain open.

**Videos**
See the `webm` file here for a video displaying the issue:  
[application-menu-close-premature.webm.zip](https://github.com/infor-design/enterprise/files/2242462/application-menu-close-premature.webm.zip)

**Platform(s)** n/a

**Additional context**
After some troubleshooting we discovered that the first condition on [this line] (https://github.com/infor-design/enterprise/blob/master/src/components/applicationmenu/applicationmenu.js#L430) in the App Menu is showing `e.target` being the body tag.  This value should be represented as an `a` or `.accordion-header` element, and should not the body tag.  Possible things to check:
- `pointer-events: none;` CSS rule on something inside the app menu where it shouldn't be?

**Comment by CindyMercadoReyes** [comment]
I'm also running into this same issue while conducting smoke testing.

**Comment by EdwardCoyle** [comment]
@clepore @theakatz should we add this one to the July sprint for fixing?  I might be able to track it down and get it fixed today.

**Comment by theakatz** [comment]
Yes we think so

**Comment by EdwardCoyle** [comment]
Caused by https://github.com/infor-design/enterprise/commit/9e624892bdf20db81c369072406337952677bc4a#diff-75bb29fcad7b97e804de3fd00e8252d6R1393

**Comment by brianjuan** [comment]
Passed QA testing on all browsers.
Environment: http://490-rc1-sohoxi.demo.design.infor.com/components/list

**Comment by EdwardCoyle** [comment]
Closing this, it's landed in `4.9.0`
