### ISSUE TITLE
AppMenu: Ability to for end user to resize

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#5193]
**Is your feature request related to a problem or use case? Please describe.**
Ability for users to resize Application Menu. In both 4.x and 5.x

**Describe the solution you'd like**
Please see attached for sample behavior
![application_menu_resizable](https://user-images.githubusercontent.com/50192038/97297549-2713da80-188d-11eb-9869-3f94a4c03e77.gif)

**Describe alternatives you've considered**
No alternatives found

**Additional context**
Sample on -> https://master-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html
And what application do you work on? M3 User Productivity

**Comment by tmcconechy** [comment]
@marclouisgenedeguzman 

From https://jira.infor.com/browse/UXD-2301

The product team should probably consider:

- Better naming for page names (shorter, more effective communication to the users)
- Are there significant user complaints about not being able to see the full page name when they have tooltips that show the full name on hover?
- IDS Responsive could have a menu that navigates (drills in) > to avoid lots of truncation, although this could get users lost very quickly 
- Product teams should limit the use of nested app menu navigation and focus on secondary navigation throughout the app via tabs, etc where possible. 
- Maybe IDS can add a splitter, although this might enable bad menu practices
- Wrapping text for menu items in cases where navigation is deep and names are long.

So passing that along but we will add this even though it might encourage bad practice.

**Comment by katieinfor** [comment]
Peter's comment on the Jira ticket: https://jira.infor.com/browse/UXD-2301 
"Following-up on this from a UXW and content strat recommendations for this issue:

- Clear character limitations when the label is created/input.

- In-line help and hint text and /or cautionary messaging if labels are too long or unwieldy, delivered via modal, toaster or hover text.

- Use of beginning or middle truncation.

- Full text on hover."

**Comment by tmcconechy** [comment]
Ok i guess what we can do with that info is add it to the app menu docs as guidellines? But not sure what the beginning or middle truncation means.

We do have tooltips now on hover https://main-enterprise.demo.design.infor.com/components/applicationmenu/test-tooltips.html

I think M3 still wants the resize no matter what guidance give though.

**Comment by ericangeles** [comment]
@tmcconechy should we wait for the design to finalize?

**Comment by tmcconechy** [comment]
Yes, please work on it @ericangeles they keep requesting it this way so even if we give the recommendations for design they still want it

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.55.0-dev.

Also tried closing the browser and opening again w/ this link https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-resizable-menu.html and the last size of the Application Menu was saved.

![Video 4](https://user-images.githubusercontent.com/84306838/130226418-f4824faf-141e-4ba6-a35b-c66b890b7cb9.gif)

Moving this ticket to Done.

Thanks!

**Comment by CindyMercadoReyes** [comment]
BDD attached. 
[BDDStory_github5193.docx](https://github.com/infor-design/enterprise/files/7022633/BDDStory_github5193.docx)
