### ISSUE TITLE
Popup/Tooltip: Using Popover with a tooltip on the same object (button) causes conflicts

### ISSUE THREAD

**Issue by edgarinfor** [infor-design/enterprise#5197]
**Describe the bug**
When replacing the deprecated **soho-popdown** with a **soho-tooltip [popover]="true"**, the opening element's "**title**" attribute becomes the header of the **popover** and it no longer shows on hovering that element as a _tool-tip_.

This means that an element cannot have a tool-tip independent from its popover; which could be done before.

![soho_popdown_vs_popover](https://user-images.githubusercontent.com/39097500/76876098-d0024d80-6847-11ea-96ef-60e1cd273fc1.png)

**To Reproduce**
This can be reproduced in the demo by simply trying to use a **soho-tooltip** as a popover, for example:
```html
<button soho-button="icon" title="This is the button title..." soho-tooltip [popover]="true" ...>
```

**Expected behavior**
For popovers, you may want to have a different "tool-tip" for the opening button explaining what it does ("hint") and display a different popover header or **no header at all**.

We can reproduce the desired results if we do something like this:
```html
<button soho-button="icon" [attr.title]="'This is the button title...'" title="xxx" soho-tooltip [popover]="true" ...>
```
![soho_tooltip_popover](https://user-images.githubusercontent.com/39097500/76877980-8830f580-684a-11ea-9f27-1e98670a9fcd.png)

However, this might be _hacky_, and it doesn't allow you to have a soho formatted tooltip (in case you want it).

**Version**
- ids-enterprise-ng: 7.0.0-dev.20200219

**Platform**
 - OS Version: Windows 
 - Browser Name: Chrome
 - Browser Version: Latest

**Comment by jbrcna** [comment]
@EdwardCoyle , this is now working as expected. However, In one of the EP 
when using [classic theme ](https://main-enterprise.demo.design.infor.com/components/popover/test-popover-with-nested-tooltip?theme=classic&mode=light&colors=2578a9), the tooltip doesn't appear. Kindly let me know if I need to file a separate issue for this.
Upon investigating, I noticed that I have to refresh the page after switching themes for the tooltip to appear.
![image](https://user-images.githubusercontent.com/56722184/122867543-44d20a80-d35c-11eb-96ae-8cfefc5c648f.png)



`Popover/Tooltip don't close each other:`
https://main-enterprise.demo.design.infor.com/components/popover/test-popover-tooltip.html
![image](https://user-images.githubusercontent.com/56722184/122866926-5830a600-d35b-11eb-8f1d-e8b98550f496.png)


`Popovers with Nested Tooltips:`
https://main-enterprise.demo.design.infor.com/components/popover/test-popover-with-nested-tooltip
![image](https://user-images.githubusercontent.com/56722184/122867074-8e6e2580-d35b-11eb-9fed-3dae478206fa.png)

`Popovers and Tooltips sharing the same trigger element:`
https://main-enterprise.demo.design.infor.com/components/popover/test-popover-tooltip-same-button.html
![image](https://user-images.githubusercontent.com/56722184/122867923-d8a3d680-d35c-11eb-8ba8-f00c8cd478d2.png)

**Comment by tmcconechy** [comment]
@jbrcna I think this is working as expected. Tooltips and popups can now be open at the same time.
Also there is one example where the tooltip isnt used.

I think we wont work anymore on these.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by jbrcna** [comment]
@tmcconechy Thanks for clarifying.
