### ISSUE TITLE
Modal: Enter key does not trigger the Primary Button

### ISSUE THREAD

**Issue by brianpettit** [infor-design/enterprise#5198]
**Describe the bug**

When using modal its expected that enter will submit the form. Some code ttps://github.com/infor-design/enterprise/blob/main/src/components/modal/modal.js#L976 is trying to do it but seems a bit off.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/modal/example-index.html
2. Fill in the problem field (now all fields are valid)
3. Hit enter

**Expected behavior**
Enter should submit the modal when in an input

**Version**
- ids-enterprise: v4.51.0

**Platform**
 - Chrome/ Any
 
**Additional context**
There is code thats "trying" to do it https://github.com/infor-design/enterprise/blob/main/src/components/modal/modal.js#L976 but in my tests its not working when you are in input elements and im not sure why that's the case

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to Done
v4.54.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/modal/example-index.html
