### ISSUE TITLE
Locale: In Thai, the first day of the week should be Monday (and not Sunday)

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5199]
Locale: In Thai, the first day of the week should be Monday (and not Sunday)

CRM CE -> The first day of the week is Monday
Microsoft ->  The first day of the week is Monday

IDS Time Picker ->  The first day of the week is Sunday. It should be Monday 

Screenshot attached

![Thai-Monday](https://user-images.githubusercontent.com/66057969/118505255-29079300-b724-11eb-86e5-8a2e7b717508.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
