### ISSUE TITLE
Target to Achievement Control: Dropdown list stays open after making a selection

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#520]
**Describe the bug**

**To Reproduce**
1. Go to 'http://490-rc0-sohoxi.demo.design.infor.com/components/targeted-achievement/example-percent-text.html#'
2. Click on"Update" drop down list box
3. Select Label B
4. The dropdown list box doesn't close

**Expected behavior**
The dropdown list box should close once a label has been selected. Please see screen shot attached, 

**Screenshots**
![target achievement error](https://user-images.githubusercontent.com/39101346/43416991-d6393864-9407-11e8-9cca-455feab80d3f.png)

**Platform**

 - All Browsers

**Additional context**
None

**Comment by tmcconechy** [comment]
This issue was solved on #1136 - The example was removed and done as a test
