### ISSUE TITLE
Lookup: attributes are not added to Save and Cancel button

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#5202]
**Describe the bug**
when I add attributes to a lookup it is added to the input, trigger, modal title and searchfield. But not to the Cancel and Save buttons. They still only have id="modal-button-1". It would be useful if they to got the added attributes!

**To Reproduce**

1. Go to  https://main-enterprise.demo.design.infor.com/components/lookup/example-index.html
2. Click on the first lookup so the dialog is opened
3. Open dev tools
4. Inspect the cancel button

**Expected behavior**
The cancel button has the attribute data-automation-id with value "my-lookup-modal-cancel"
and the save button has the attribute data-automation-id with value "my-lookup-modal-save"

**Version**

- ids-enterprise: 4.51

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/118662123-0e025500-b7f0-11eb-87e8-8a16c401dae0.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 90.0.4430.212 (Official Build) (64-bit)

**Additional context**
-

**Comment by janahintal** [comment]
QA Passed. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/122028944-1190f800-cdff-11eb-86e7-1cfb3698e7ca.png)
