### ISSUE TITLE
Translations: Incorrect Italian translation for "Selected"

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5205]
Translations: Incorrect Italian translation for "Selected"

![Selected](https://user-images.githubusercontent.com/66057969/118796428-840bc800-b893-11eb-8bca-27151b2b22d1.png)

“Selezionato” should be “Selezionati” or even better “Selezionato/i” (one or more items), however the comment in the string below reads “'text describing **a** selected object'"

Selected: { id: 'Selected', value: 'Selected', comment: 'text describing a selected object' },

Correct string that needs amending? Incorrect comment?

Please assign it to: Henry Wondergem

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
Corrected in the June 2021 delivery. 
The comment should be changed to “text describing selected object(s)”.
