### ISSUE TITLE
About: Spilling scroll bar when in responsive view 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5206]
**Describe the bug**
About: Spilling scroll bar when in responsive view 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/?theme=classic&mode=contrast&colors=133c59
2. Scroll to About section
3. Click the about button 
4. Minimize the screen to see in responsive view

**Expected behavior**
Modal should be in responsive view

**Version**
4.52 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/118803197-a6bed080-b8d5-11eb-9485-ca177de225d7.png)

**Platform**
All major browser

**Additional context**
N/a

**Comment by tjamesallen15** [comment]
Hello, FYI. This issue isn't reproducible on Mac. It can only be reproduced on Windows.

**Comment by janahintal** [comment]
This issue is now resolved. 
Verified in https://main-enterprise.demo.design.infor.com/components/about/example-index.html?theme=classic&mode=light&colors=2578a9 

![image](https://user-images.githubusercontent.com/45757016/119603467-d44cd200-be1f-11eb-8ec4-fa49d8dcb7db.png)
