### ISSUE TITLE
Circlepager: Improvement on controls

### ISSUE THREAD

**Issue by Carlfjord** [infor-design/enterprise#5207]
**Is your feature request related to a problem or use case? Please describe.**
Component: Circlepager
https://master-enterprise.demo.design.infor.com/components/circlepager/list
The problem is that when using this to display images that does not have a white background the controls will be above the image and thus making them hard to see in some scenarios.
This is forcing slide content to respect the controls. Which is very hard to manage in a scenario like the one we are trying to accomplish where slide content is determined by user uploaded images of various ratios/colors and sizes.

**Describe the solution you'd like**
It would be easier to manage if the controls were positioned outside of the slide container.
```
____________________
|                  |
|   slide content  |
|                  |
____________________
|      controls    |
____________________

```
 In this case if an image were to ocupy 100% height it would not affect the controls visuallty maintaining usability.

**Describe alternatives you've considered**
Perhaps the controls can be added on a separate element instead of the slider so one can manage were to keep the controls more easily just by structuring the html according to your own requirements.

**Additional context**
![image](https://user-images.githubusercontent.com/9215760/118830105-fa71ef80-b8be-11eb-9838-834e90d33fb8.png)

Infor PIM

**Comment by tmcconechy** [comment]
We planned on redoing this component and i think thats what it would take to address this. (Including adding swipe)

**Comment by Carlfjord** [comment]
@tmcconechy No specific code change in mind. I think remaking it sounds like a good idea, this component feels quite different compared to other components in terms of how it is structured and used and configs. So a fresh start would benefit the components usability. I can take this oportunity to highlight another consern we noticed tho.

So there are the button controls and when it get too many slides it changes to the arrow controls. I think it would be helpful to have a way of easily configuring what layout should be used. For example we would like to be able to use arrows even for low amount of slides. Also it would be nice to be able hide certain things through config option. Like in this example it would be nice to be able to configure it not to show the "Slide 3 out of 20" once it switched to arrow layout since we are already keeping track of "3 of 20" even in button controls layout.
![image](https://user-images.githubusercontent.com/9215760/118969787-c6a1d300-b96d-11eb-9097-07032b2222bf.png)

We will be on the lookout for a potential rework of this component then and make any critical fixes in overrides on our end. 👍

**Comment by tmcconechy** [comment]
Yeah sounds good. Im think of more of a scroll container but the ability to configure the arrows and make it be more of a "carousel" will be the goal as your saying.

I may open a more specific issue for this soon.

**Comment by tmcconechy** [comment]
In the new version the circle pager is now "scroll view" https://main.wc.design.infor.com/ids-scroll-view/example.html should do most of this
