### ISSUE TITLE
[Application Menu]  Learner dropdown list box check maker overlapping onto text

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#521]
**Describe the bug**
[Application Menu]  Learner dropdown list box check maker overlapping onto text

**To Reproduce**
1. Go to 'http://490-rc0-sohoxi.demo.design.infor.com/components/applicationmenu/example-top-level-buttons.html
2. Click on "learner"
3. The check marker is overlapping onto the word "Author"
4. Please see screen shot attached. 

**Expected behavior**
The check marker should not overlap

**Screenshots**
![application menu learner error](https://user-images.githubusercontent.com/39101346/43419451-eb7a1782-940e-11e8-9b46-61788f87a44b.png)

**Platform**
 - MAC- Chrome 67

**Additional context**
None

**Comment by tmcconechy** [comment]
Just need to change the config in this example to selectable.
