### ISSUE TITLE
Datagrid: Unable to select records in sticky headers

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5212]
**Describe the bug**
Datagrid: Unable to select records in sticky headers

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-sticky-headers.html
2. Tick select all and the first grid 
Notice that the select all is checked but none of the records were selected 

**Expected behavior**
All records should be selected

**Version**
4.52 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/118966183-097a9f80-b99c-11eb-8006-8259205069c9.png)

**Platform**
All major browsers

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping for now
