### ISSUE TITLE
Header: default color makes make it impossible to highlight the selected a text in the header

### ISSUE THREAD

**Issue by clazarev** [infor-design/enterprise#5219]
It looks like the default color of the light-new theme is identical to the browser text selection color (I tried Edge and Chrome).
It makes it look like the text is non-selectable and very confusing; please see the gif
![header_selection_default_color](https://user-images.githubusercontent.com/11888130/119425689-760fda00-bccd-11eb-9446-7938f12e64e9.gif)
I think it is the only header that is affected

Expected: for this particular default color, apply custom text selection color for _.header_

**Comment by tmcconechy** [comment]
I agree.. Lets fix this by making the selection color a lot lighter..

**Comment by tmcconechy** [comment]
For a fix we just need to change the selection css color `::selection` to a better value https://github.com/infor-design/enterprise/blob/main/src/components/personalize/personalize.styles.js#L10 maybe use some opacity?

**Comment by jbrcna** [comment]
**QA Passed**
v4.53.0-dev
https://main-enterprise.demo.design.infor.com/components/personalize
![image](https://user-images.githubusercontent.com/56722184/122866520-aabd9280-d35a-11eb-8767-7bfc04cb33ef.png)


`Azure`
![image](https://user-images.githubusercontent.com/56722184/122866552-bb6e0880-d35a-11eb-9d62-05c8491f7c5f.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
