### ISSUE TITLE
Dropdown: Example Setvalue - dropdown also updates when clicking "more actions" button

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5222]
**Describe the bug**
Dropdown: Example Setvalue - dropdown also updates when clicking "more actions" button

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/dropdown/example-setvalue.html 
2. Click on 'more actions' button
3. Check the dropdown as it changed from 'Option One' to 'Option Three' without clicking the 'Update' button

**Expected behavior**
Options in dropdown should be updated only when 'Update' button is clicked

**Version**
v4.52.0-dev

**Screenshots**
<img width="1680" alt="Screen Shot 2021-05-25 at 6 21 58 PM" src="https://user-images.githubusercontent.com/84306838/119482189-28a37380-bd86-11eb-87a5-b233dc7cdc0c.png">

**Platform**
 - All browsers and mobile

**Additional context**
N/A

**Comment by tmcconechy** [comment]
This one should be easy to fix i think just change this https://github.com/infor-design/enterprise/blob/main/app/views/components/dropdown/example-setvalue.html#L18 to use the ID of the button.

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.53.0-dev.

Moving this ticket to Done.

Thanks!
