### ISSUE TITLE
Datagrid: Columns are not get resized in some cases 

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#5227]
**Describe the bug**
We observed issue with datatgrid columns in model popup some not get resized. 
Please refer below example for the same. 

**To Reproduce**

1. Go to 'https://ids-quick-start-model-popup-issue.stackblitz.io/model-popup-example'
2. Click on 'Show Model' button
3. In Popup try to resize any column
4. See columns re not get resized.

**Expected behavior**
Datagrid columns should get resize by using resizer 
**Version**

- ids-enterprise: v4.51.1

**Screenshots**
Please check below example - https://ids-quick-start-model-popup-issue.stackblitz.io/model-popup-example 

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
How do i see the code in stack blitz (whats the link to the code part)? I'm thinking that all you need to do to make this work is set a width on the modal so the content is constrained.

That being said in our code:

- Here is an example that works https://main-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-tooltips.html 
- This one doesnt https://main-enterprise.demo.design.infor.com/components/datagrid/example-modal-datagrid.html

But try putting a css width on the modals main div.

**Comment by dhumalkishor** [comment]
For code refer below link - 
https://stackblitz.com/edit/ids-quick-start-model-popup-issue

**Comment by dhumalkishor** [comment]
We tried with width in "px" but it's not working.

**Comment by cpinatel7** [comment]
Still not fixed

**Comment by tmcconechy** [comment]
Yes, still not fixed. I took a look and its not going to be an easy fix i think due to the way the modal and datagrid is sized. It works here:

https://main-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-tooltips.html

Try comparing https://main-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-tooltips.html to and https://main-enterprise.demo.design.infor.com/components/modal/test-modal-close-btn.html to what your your doing?

On https://main-enterprise.demo.design.infor.com/components/modal/test-modal-close-btn.html i was able to fix it by removing the modal maxWidth setting. So you could try playing around with that and looking at those examples.

**Comment by dhumalkishor** [comment]
Hi Tim,

Can you please update when we can expect fix for this JT.

Regards,
Kishor

**Comment by tmcconechy** [comment]
I 'll put this in the next sprint plan - to look at but i cant guarantee a fix on this one. We may we need to work this into a future 5.0 and change some grid fundamentals to fix it...

**Comment by tmcconechy** [comment]
note to the developer: I think this can be fixed by finding a proper column configuration/sizes ect.. and settings so give it try

**Comment by tmcconechy** [comment]
@ericangeles - did you guys see any easy fixes? If not thats fine we might have to slide this

**Comment by tmcconechy** [comment]
ok, look forward to seeing it 👍🏻

**Comment by jbrcna** [comment]
QA Passed. v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-column-size?width=500
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/56722184/177077174-4848a2f4-71e3-4243-9bd3-ed4848051819.png">
