### ISSUE TITLE
Datagrid: Investigate Combining Reordering and Grouping

### ISSUE THREAD

**Issue by katieinfor** [infor-design/enterprise#5233]
**Is your feature request related to a problem or use case? Please describe.**
For specific UI applications in M3 app builder we need data grid component which combines:

- row reordering 

https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-row-reorder?theme=uplift&variant=light 

- row grouping

https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-grouping?theme=uplift&variant=light

- group reordering

- adding new groups

**Additional context**

Figma prototype:
https://www.figma.com/proto/hxbpgjNregW5SR0IvC29ol/M3?page-id=1616%3A9080&node-id=1633%3A10659&viewport=222%2C376%2C0.09557423740625381&scaling=min-zoom 

JIRA ticket: 
https://jira.infor.com/browse/UXD-2557

**Comment by jbrcna** [comment]
QA Passed
this is now working as expected.
v4.54.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/example-grouping-row-reorder.html
Hi @tmcconechy , just wanted to clarify if this is part of the requirement. when using `small` and `extra small` row height the parent  drag handle is not aligned to child  drag handles. thank you.
![image](https://user-images.githubusercontent.com/56722184/126602379-d897cea5-53b2-42ff-b59d-16c4b455490e.png)

**Comment by jbrcna** [comment]
the issue  is now resolved. thank you
v4.54.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/example-grouping-row-reorder.html
![image](https://user-images.githubusercontent.com/56722184/127450677-367e29dc-4aaa-4fcb-8bcc-55ec888e5c64.png)
