### ISSUE TITLE
ContextualActionPanel: Add example with left side menu navigation 

### ISSUE THREAD

**Issue by katieinfor** [infor-design/enterprise#5234]
**Is your feature request related to a problem or use case? Please describe.**
Bringing over ticket from JIRA, 
Requirements:
1. Content will be displayed inside CAP but we need navigation in CAP
2. Navigation is realized using left-hand side vertical menu
3. Menu position can have: title, subtitle, icon, badge, etc.
4. Menu items separator is needed to group menu positions.

**Additional context**
https://www.figma.com/file/hN1MJ3HuJqEKF4QJd4wD1I/M3-App-Builder-IDS-Components?node-id=1%3A995 

JIRA Ticket: 
https://jira.infor.com/browse/UXD-2431

**Comment by tmcconechy** [comment]
@ericangeles for this one i think it just needs to have an example with vertical tabs on the contextual action panel. so use vertical tabs design not the one in the design so we keep it consistent. So just making an example and any tweaks to combine those.

**Comment by jbrcna** [comment]
this is now working as expected. However, when using `iPhone 12 Pro Max 14` ,` iPhone 11 13`,` iPhone 11 14`,  ` iPhone 11 Pro Max 14`, `Phone 11 Pro Max 13`, `iPhone XS Max` Landscape mode the left side menu is missing. test is done in BS and actual real device
v4.53.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-cap-tabs-vertical.html
![image](https://user-images.githubusercontent.com/56722184/123749318-e078f300-d8e7-11eb-8575-c54c5e4e300a.png)

_recording from a real device `iPhone 12 Pro Max`_
https://user-images.githubusercontent.com/56722184/123751941-df959080-d8ea-11eb-9854-579f0da7671e.mov

**Comment by CindyMercadoReyes** [comment]
Adding BDD document for this ticket. 
[story_github5234.docx](https://github.com/infor-design/enterprise/files/6741522/story_github5234.docx)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
