### ISSUE TITLE
Translation - in Estonian, "Required" should be translated as “Nõutud”

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5235]
Translation - in Estonian, "Required" should be translated as “Nõutud”

Owner: Henry.Wondergem@infor.com

![Estonian](https://user-images.githubusercontent.com/66057969/119690159-58638180-be41-11eb-9831-305db455bf1b.png)

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
Fixed in translation delivery of 2021-06.
