### ISSUE TITLE
Calendar: Duplicate events

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5236]
**Describe the bug**
when creating a time-specific event `(All day is unchecked)`, it duplicates all other events created after it by switching to weekview/dayview

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Create an event `Add Event API`
3. Click to Edit the newly created event
4. Unchecked All day option to edit the time
5. Change the time to 7am - 12pm
6. Create another event `Add Event Modal` (same day or other day)
7. Switch to WeekView or DayView
8. See error. Notice that the newly created event is duplicated.

**Expected behavior**
Event should not be duplicated

**Version**

- ids-enterprise: v4.52.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/119749495-c6538b80-bec9-11eb-83e9-37adaffc2991.png)

**Platform**
All browsers

**Additional context**

**Comment by tjamesallen15** [comment]
@tmcconechy I'll pick this up and check it. :)

**Comment by jbrcna** [comment]
this is now working as expected. thank you
v4.53.0-dev
https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html
