### ISSUE TITLE
Dropdown: Expanded dropdown menu/list is not responsive on mobile

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5237]
**Describe the bug**
Dropdown: Expanded dropdown menu/list is not responsive on mobile(ios)

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/dropdown/example-virtual-scroll.html
2. Click on the dropdown
3. The dropdown menu/list expands and a whitespace shows

**Expected behavior**
The page should be responsive and there shouldn't be a whitespace on the rightmost side.

**Version**
v4.52.0-dev

**Screenshots**
![image0](https://user-images.githubusercontent.com/84306838/119822229-fcbef400-bf25-11eb-839e-952f6571af0a.png)

**Platform**
 - iPhone 12 Pro Max - Safari/Chrome (actual)
 - Tested on other iPhone devices as well

**Additional context**
N/A

**Comment by tmcconechy** [comment]
descoping this due to new component
