### ISSUE TITLE
FieldOption: Overlapping focus / highlight in compact mode

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5244]
**Describe the bug**
FieldOption: Overlapping focus / highlight in compact mode

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-options/example-index.html
2. Switch to compact mode
3. Use tab key to focus and see the vertical '...'

**Expected behavior**
Focus / highlight should not overlap

**Version**
Ids 4.52 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/120191112-17f27200-c24c-11eb-9230-761e8119dd8a.png)

**Platform**
All major browser & devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Might this be fixed on https://github.com/infor-design/enterprise/pull/5238 @ericangeles  ?

**Comment by ericangeles** [comment]
@tmcconechy yes, that's correct.

**Comment by tmcconechy** [comment]
Fixed by https://github.com/infor-design/enterprise/pull/5238

**Comment by janahintal** [comment]
This issue is now resolved. Thank you.
![image](https://user-images.githubusercontent.com/45757016/120465418-89f3c400-c3d0-11eb-98be-b5c6157c043a.png)
