### ISSUE TITLE
Monthview: Datepicker's placement isn't aligned with month&year and not responsive on Firefox

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5245]
**Describe the bug**
Datepicker's placement isn't aligned with month and year and not responsive on Firefox

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/monthview/example-index.html 
2. Click on datepicker
3. Resize the browser

**Expected behavior**
Datepicker should be responsive

**Version**
v4.52.0-dev

**Screenshots**
The placement of the Datepicker is not aligned to the Month & Year
<img width="1680" alt="Screen Shot 2021-05-31 at 8 37 25 PM" src="https://user-images.githubusercontent.com/84306838/120194679-7de0f880-c250-11eb-8c82-4a4acdac1969.png">

Tried resizing the browser then the datepicker moved down
<img width="474" alt="Screen Shot 2021-05-31 at 8 37 37 PM" src="https://user-images.githubusercontent.com/84306838/120194813-ad900080-c250-11eb-9dfa-12eb25075df7.png">

After clicking the datepicker, it moved back up
<img width="476" alt="Screen Shot 2021-05-31 at 8 37 59 PM" src="https://user-images.githubusercontent.com/84306838/120194829-b385e180-c250-11eb-8ad3-a3972829b73c.png">

**Platform**
 Firefox

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Maybe we can test this against https://github.com/infor-design/enterprise/pull/5226

**Comment by nganotice** [comment]
Hi @tmcconechy this issue is active on https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html (Firefox) as well. Guessing that the fix will be for all that's related to calendar, right? Thanks!

**Comment by tmcconechy** [comment]
Yes @nganotice this issue will cover both cases, we'll just note to test that example as well when fixing.

**Comment by tmcconechy** [comment]
I think this issue should be closed
