### ISSUE TITLE
Images: Searchbar overlaps with "Websites" Header

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5248]
**Describe the bug**
Searchbar overlaps with "Websites" Header

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/images/example-image-list.html 
2. Click on Searchbar (resize the browser and use any mobile device)
3. See error

**Expected behavior**
It shouldn't overlap with the "Websites" Header/It should be responsive

**Version**
v4.52.0-dev

**Screenshots**
Resized Browser
<img width="492" alt="Screen Shot 2021-06-01 at 9 20 25 PM" src="https://user-images.githubusercontent.com/84306838/120330500-75a3be80-c31f-11eb-9d9f-963da013f0c2.png">

iPhone
<img width="219" alt="Screen Shot 2021-06-01 at 9 20 59 PM" src="https://user-images.githubusercontent.com/84306838/120330530-7a687280-c31f-11eb-8762-0cd0164b4ead.png">

**Platform**
 - All Resized Browsers & Major devices

**Additional context**
N/A

**Comment by tmcconechy** [comment]
This is probably so minor we will never fix this but will leave it open for now

**Comment by ericangeles** [comment]
@tmcconechy assigning this to @yohannahbautista

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.53.0-dev.

Responsive view:
<img width="367" alt="Screen Shot 2021-06-15 at 4 43 33 PM" src="https://user-images.githubusercontent.com/84306838/122022254-01761a00-cdf9-11eb-872f-c929e36fd536.png">

iPhone 12 mini:
<img width="395" alt="Screen Shot 2021-06-15 at 4 43 07 PM" src="https://user-images.githubusercontent.com/84306838/122022204-f6bb8500-cdf8-11eb-8820-18cdb7353387.png">

Moving this ticket to Done.

Thanks!
