### ISSUE TITLE
Destroy Tabs API randomly failing

### ISSUE THREAD

**Issue by d-g-h** [infor-design/enterprise#525]
**Describe the bug**
Tabs destroy method tests are randomly failing. Perhaps the timeout length should be increased, as the underlying teardown methods are taking longer than expected.

```sh
FAILED TESTS:
  Tabs API
    ✖ Should destroy tabs
      HeadlessChrome 0.0.0 (Linux 0.0.0)
    Expected 1 to equal 0.
        at <Jasmine>
        at test/components/tabs/tabs-api.func-spec.js:3802:74
    ✖ Should teardown tabs
      HeadlessChrome 0.0.0 (Linux 0.0.0)
    Expected 1 to equal 0.
        at <Jasmine>
        at test/components/tabs/tabs-api.func-spec.js:3789:74
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Closing this out as this test has been passing ok.
