### ISSUE TITLE
Circle Pager: Size interactions and changes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5251]
**Is your feature request related to a problem or use case? Please describe.**

Need to make some changes too circle pager for WFM demos.

**Describe the solution you'd like**

- [ ] Increase size from 10px to 16px (can be done for all circle pagers  if easier)
- [ ] Add 44p hitbox for tapping (can be done for all circle pagers if easier)
- [ ] At mobile circles change size to smaller
- [ ] If more than 6 pages the pager changes to an input style pager

To make it simple some of the pagers could be static if needed

**Design**
These sections:
![Screen Shot 2021-06-01 at 11 42 56 AM](https://user-images.githubusercontent.com/814283/120352402-bc1cfd00-c2ce-11eb-8afa-72ac5f851bd7.png)

**Additional context**
See sections on https://www.figma.com/file/ri2Knf3KchdfdzRAeds0Ab/IDS-Mobility-v4.6?node-id=285%3A0 if needed

**Comment by jbrcna** [comment]
**QA Passed**
v4.53.0-dev
https://main-enterprise.demo.design.infor.com/components/circlepager/example-mobile.html
![image](https://user-images.githubusercontent.com/56722184/122008950-2912b580-cdec-11eb-9d2a-38091b835382.png)
https://main-enterprise.demo.design.infor.com/components/pager/example-standalone.html

**Comment by CindyMercadoReyes** [comment]
BDD added for this enhancement. 
[BDDStory_github5251.docx](https://github.com/infor-design/enterprise/files/6677501/BDDStory_github5251.docx)
