### ISSUE TITLE
Cards: Add improved Expandable Card Example

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5252]
**Is your feature request related to a problem or use case? Please describe.**
Adding some improvements to the expandable card examples

**Describe the solution you'd like**

- [x]  FIx or archive the old example https://main-enterprise.demo.design.infor.com/components/cards/example-expandable.html
- [ ] Make sure this one has an angular example
- [ ] Make a working example like the design
- [ ] Later on add this example to WC 
- [ ] Make sure we can do it in NG as they use NG see https://github.com/infor-design/enterprise-ng/issues/1036

**Describe alternatives you've considered**
![Screen Shot 2021-06-01 at 1 30 15 PM](https://user-images.githubusercontent.com/814283/120366333-86cbdb80-c2dd-11eb-90a1-77e193814802.png)

**Additional context**
See expandable card section of https://www.figma.com/file/ri2Knf3KchdfdzRAeds0Ab/IDS-Mobility-v4.6?node-id=1%3A5740

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
