### ISSUE TITLE
Cards: Add selection state

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5253]
**Is your feature request related to a problem or use case? Please describe.**
Working on features for the WFM demo. This one adds selection to cards similar to https://main-enterprise.demo.design.infor.com/components/blockgrid/example-multiselect.html

**Describe the solution you'd like**
- [x] Add selectable option to cards like listview or datagrid or block grid has
- [x] Add an example
- [ ] Add NG example and types 
- [ ] Add to WC (eventually)

**Design**
![Screen Shot 2021-06-01 at 1 32 17 PM](https://user-images.githubusercontent.com/814283/120366670-f0e48080-c2dd-11eb-8f44-f518f6b33bd6.png)

**Additional context**
See Single Select / Multi-select section in:
https://www.figma.com/file/ri2Knf3KchdfdzRAeds0Ab/IDS-Mobility-v4.6?node-id=1%3A5740

**Comment by janahintal** [comment]
This is working as expected in https://main-enterprise.demo.design.infor.com/components/cards/example-multi-select.html
& https://main-enterprise.demo.design.infor.com/components/cards/example-single-select.html

![image](https://user-images.githubusercontent.com/45757016/127640157-9f6e9b4b-14a3-47b9-a8d5-ce3952236e65.png)
![image](https://user-images.githubusercontent.com/45757016/127640173-fb7f607b-9602-488a-a39f-28bdc5f7581c.png)
