### ISSUE TITLE
Mobile: Add swipe container component

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5254]
**Describe the bug**
Add the newly coming swip-container component to EP.

**To Resolve**
- Add an example to web components
- Port example code to old code

**Design**
![Screen Shot 2021-06-01 at 1 34 49 PM](https://user-images.githubusercontent.com/814283/120366969-491b8280-c2de-11eb-9307-e114d901a8f2.png)

**Comment by janahintal** [comment]
This is now working as expected. 
Both tested on Android and iOS device in https://4530-beta0-enterprise.demo.design.infor.com/components/swipe-action/example-index.html

![image](https://user-images.githubusercontent.com/45757016/124474363-03694280-ddd3-11eb-99d9-7e382147a8ab.png)
![image](https://user-images.githubusercontent.com/45757016/124474858-a15d0d00-ddd3-11eb-85bb-cfddabb82943.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by CindyMercadoReyes** [comment]
Adding BDD.
[BDDStory_github5254.docx](https://github.com/infor-design/enterprise/files/6777669/BDDStory_github5254.docx)
