### ISSUE TITLE
Datepicker: Some texts in date picker not showing in correct language.

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise#5255]
**Describe the bug**
In the case where the Soho locale and language are set to 2 different things, for example locale = es-ES and language = en, the top of the date picker shows based on the locale and not the language.

**To Reproduce**

1. Modify datepicker/test-two-locales-same-page.html - for the 3rd date picker field ('Swedish Language / De locale') use the following language and locale setting:

"{ locale: 'es-ES', language: 'en' }"

2. Execute the component.
3. Click the date picker icon in the 3rd field. 
4. Note the top portion of the date picker (name of month, abbreviations for day names) show in Spanish, bottom half shows in  English.

**Expected behavior**
At step 4 the component should appear entirely in English which is the language setting.

**Version**
Enterprise 4.51, Enterprise NG 9.5.0

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/39279254/120366990-50429080-c2de-11eb-9f7b-799074adf6a5.gif)

**Platform**
 - Infor Application/Team Name: GLT
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 90.0.4430.212
 - 
**Additional context**

**Comment by tmcconechy** [comment]
Will try and work this into the new locale code im working on.
