### ISSUE TITLE
Tabs Counts: Design doesn't comply with translation requirements

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5258]
KPI issue: Design doesn't comply with translation requirements

![Widget](https://user-images.githubusercontent.com/66057969/120480074-906d4600-c3a6-11eb-9289-58e6c0c6ceef.png)

Screenshot attached

**Scenario:**

- KPIs can be displayed vertically and / or horizontally
- Two sets of labels are required for translation, one set for the ones that are displayed vertically and one set for the horizontal view

Example:

Label used for Vertical KPI display
e.g.
"id": "XXX",
"string": "Past Due",

Label used for Horizontal KPI display with floatable variables
e.g.
"id": "YYY",
"string": "{0} Past Due",

- This approach is not supported. Result: Grammatically incorrect translations are displayed in most languages

CRM MT developer:
"Upon checking the soho component configuration used to display both horizontal and vertical(pop up) navigation don't support 2 label versions. The current setup *automatically *converts the original horizontal KPI items to Vertical view when the max display length is reached. Note that the component also automatically hides the remaining pass the max display length, and the vertical navigation is the only way to view all items."

**Comment by tmcconechy** [comment]
I can easily see what your saying on https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html if you resize the page so the overflow shows.

What would be grammatically correct? Maybe it would be better if we dropped the counts from the overflow menu entirely? Or what do you think we should do about it from a translation point of view?

**Comment by cpinatel7** [comment]
Thanks Tim. I see what you mean. Dropping the counts from the overflow menu entirely is the easiest / quickest solution

From a translation point of view, we need 2 sets of strings i.e. one set of strings for the vertical view and one set of strings for the horizontal (overflow) view. Currently, the same set is used in both cases. **Overall your solution is the best option.** 

Another question, not mentioned in my initial ticket:
The following layout (i.e. Number on the first row and Text/label on the second row) is problematic:
![image](https://user-images.githubusercontent.com/66057969/120487773-28226280-c3ae-11eb-9543-cb2ef4f6d8a0.png)

It looks ok in English but for some languages, it's more logical to display the Text/label on the first row and the Number on the second row. Do you think that we could add some configuration settings e.g. for en (US), display Number on the first row and Text/label on the second row. For language XXX, display Text/label on the first row, for language YYY, display...., etc. I'll create a separate issue for this. Thanks for your help

**Comment by tmcconechy** [comment]
I think this issue should cover the cases of the order on the tabs and the order in the overflow menu so no need for a separate issue. I guess we could:

- add a way to make the count on top or bottom
- reflect that order in the menu as well? Or should we drop them out of the menu part?

**Comment by cpinatel7** [comment]
- For "add a way to make the count on top or bottom", I guess we (translation team) will have to give you a list of languages and whether counts should be on top or bottom
- Drop it please as it's the easiest / best option
Thanks again

**Comment by tmcconechy** [comment]
Ok if you want to give a list we can do that.

**Comment by cpinatel7** [comment]
I'll compile a list (will take at least a week as several languages are translated externally)

**Comment by cpinatel7** [comment]
re: list of languages and whether counts should be on top or bottom

**Counts should be on top:**
English locales
Chinese Simplified
Chinese Traditional
German
Japanese

**Counts should be on bottom:**
Other languages

Thanks

**Comment by tmcconechy** [comment]
In addition i would add we should do this on Tabs Counts and actual counts as well.

https://main-enterprise.demo.design.infor.com/components/counts/example-index

And in WC and EP.

**Comment by cpinatel7** [comment]
Would it be possible to target / prioritise this issue? Thanks

**Comment by tmcconechy** [comment]
I Can put it up for next sprint.. Thanks

**Comment by cpinatel7** [comment]
Thanks Tim. Much appreciated

**Comment by tmcconechy** [comment]
Please make this change in web components as well?

**Comment by cpinatel7** [comment]
Sorry but is "Please make this change in web components as well?" intended for your team or do I need to talk to the CRM MT team about this?
Thanks

**Comment by tmcconechy** [comment]
This is for my team @cpinatel7 -> want to make sure the change is also done in the future version we are making so it doesnt get lost there...

**Comment by cpinatel7** [comment]
Thanks

**Comment by tmcconechy** [comment]
To clarify this fix to the developer that does this:

a. Remove the count from the overflow menu
b. Counts position depends on locale:

These should be on top:
English locales
Chinese Simplified
Chinese Traditional
German
Japanese

These counts should be on bottom:
Other languages

**Comment by cpinatel7** [comment]
Thank you

**Comment by jbrcna** [comment]
this is now working as expected. counts are now displayed accordingly and is not visible in spillover
v4.59.0-dev
verified in
https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html?locale=de-DE
https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html?locale=zh-CN
https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html?locale=zh-Hans
https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html?locale=zh-TW
https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html?locale=zh-HANT
https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html?locale=ja-JP

https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html?locale=pt-PT
https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html?locale=ar-EG
https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html?locale=no-NO
