### ISSUE TITLE
Lookup: Values became unselected when reopened/not loaded

### ISSUE THREAD

**Issue by NicholTamayo** [infor-design/enterprise#5261]
**Describe the bug**
Observed that when reopening the lookup, the page that is not loaded became unselected. Another observation is, unselecting an item in page 1, unselect the item in succeeding pages.

**To Reproduce**
Scenario 1
1. Go to https://master-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside
2. Open the lookup.
3. Select all the item from page 1 to 3
4. Click "Apply".
5. Open the lookup again. (observed that the selection-count is only in 5)
6. Click "Apply".
7. Reopen the lookup.
8. Go to page 2 and 3.
Result: Items in page 2 and 3 became unselected. 

Scenario 2
1. Go to https://master-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside
2. Open the lookup.
3. Select all the item from page 1 to 3
4. Click "Apply".
5. Open the lookup again. (observed that the selection-count is only in 5)
6. Unselect an item in page 1.
7. Go to page 2 and 3
Result: Items in page 2 and 3 became unselected. 

**Expected behavior**
The selected items in page 2 and 3 remained selected.

**Version**
- ids-enterprise: 4.38.1/4.51.1

**Screenshots**
Scenario 1
![Values became unselected when reopened/not loaded - Scenario 1](https://user-images.githubusercontent.com/79066908/120569604-d0850500-c448-11eb-8fdb-04f15bbd2177.gif)

Scenario 2
![Values became unselected when reopened/not loaded  - Scenario 2](https://user-images.githubusercontent.com/79066908/120569703-0aeea200-c449-11eb-9e1a-756f87165477.gif)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Window 10
 - Browser Name: Chrome
 - Browser Version: Chrome/Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by nganotice** [comment]
This has been QA tested and passed in v4.53.0-dev.

**1st Scenario**
![1st Scenario](https://user-images.githubusercontent.com/84306838/123587153-704f6c00-d818-11eb-80cb-fda6761239de.gif)

**2nd Scenario**
![2nd Scenario](https://user-images.githubusercontent.com/84306838/123587164-73e2f300-d818-11eb-84a0-1128c730dba4.gif)

Moving this ticket to Done.

Thanks!
