### ISSUE TITLE
Applicationmenu: When changing colors from more actions, Application Menu changes color as well

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5266]
**Describe the bug**
After clicking More Actions>Color>'Any color', Application Menu also updates to that color

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html (**All Examples of this component are affected as well**)
2. Click on More Actions Button
3. Click on Colors then pick any color
4. See error that the Application Menu updates to the color as well

**Expected behavior**
Application Menu's color shouldn't be changed when updating a new color from More Actions

**Version**
v4.52.0-dev

**Screenshots**
Color Emerald
<img width="1680" alt="Screen Shot 2021-06-03 at 6 42 57 PM" src="https://user-images.githubusercontent.com/84306838/120632490-9abd3c00-c49b-11eb-8660-8b41cee23eb4.png">

**Platform**
 -All Major Browsers

**Additional context**
N/A

**Comment by EdwardCoyle** [comment]
@nganotice This is not a bug.  The personalization of the background color in the application menu is configurable depending on the application's needs.  Also see [this example](https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable?colors=1F9254), which does not change the background color.

**Comment by tmcconechy** [comment]
Agreed - changing the color is called personalization and its a setting. So it will change in some examples...Like this one

**Comment by nganotice** [comment]
Got it! Thanks @EdwardCoyle & @tmcconechy
