### ISSUE TITLE
Datagrid: Column headers disappear and column data moves to other column after Personalizing Columns

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5267]
**Describe the bug**
Datagrid: Column headers disappear and column data moves to other column after Personalizing Columns

**To Reproduce**

1. Go to https://4520-beta0-enterprise.demo.design.infor.com/components/datagrid/example-index.html?theme=new&mode=contrast&colors=003876
2. Remove Product Name and Activity Column 
3. Click Close
**Notice the Phone column moved to Order date & the Activity Column not removed.** 
![image](https://user-images.githubusercontent.com/45757016/120636724-8d568080-c4a0-11eb-8507-640f70ed6c39.png)

4. Add the Product Name & Activity Column again & play with the checklist again
![image](https://user-images.githubusercontent.com/45757016/120636837-b9720180-c4a0-11eb-8a92-adedd381e1e1.png)

**Expected behavior**

**Version**
IDS Beta 4.52

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/120636724-8d568080-c4a0-11eb-8507-640f70ed6c39.png)
![image](https://user-images.githubusercontent.com/45757016/120636837-b9720180-c4a0-11eb-8a92-adedd381e1e1.png)
![image](https://user-images.githubusercontent.com/45757016/120636533-53857a00-c4a0-11eb-940a-f207c77e1294.png)

**Platform**
All browser, OS, and devices. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Probably should look at this one. Adding for next sprint

**Comment by tmcconechy** [comment]
This has been fixed on another issue. Please QA on main.
