### ISSUE TITLE
Datagrid: Tree filter not working for options is Empty and is not Empty

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#5273]
When using a Datagrid-tree the filter options of is Empty and is not Empty are not working. 

I modified the datagrid-treegrid-service.demo.ts and added multiple rows that had the comments column as empty (null and space values) .

1. Go to DataGRid - TreeGrid
2. Click [R] for the Comments column
3. Select option is Empty

Scenario #2
Repeat steps but select is not empty, same results.

**Expected behavior**
Only rows with empty in comments should be displayed

Actual:
 All rows are displayed. 

**Version**
"ids-enterprise-ng": "^9.3.1",
 "ids-identity": "^3.0.5",
    
**Screenshots**
![image](https://user-images.githubusercontent.com/17933529/120815831-32fc0500-c51e-11eb-91c2-5de48c89c33b.png)

![image](https://user-images.githubusercontent.com/17933529/120816262-95ed9c00-c51e-11eb-9868-80380736757f.png)

Chrome

**Comment by AnaLauraMartinez** [comment]
I tested with IDS 13.0.3 and still the same issue.

**Comment by jbrcna** [comment]
this is now working in localhost. will retest once fix is available in main
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/56722184/198202502-7adb1fb5-db49-4672-8b92-e871f87b755e.png">

**Comment by jbrcna** [comment]
this is now working in main. thanks
https://main-enterprise.demo.design.infor.com/components/datagrid/test-tree-filter.html
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/56722184/199494073-80b1ac38-8d99-468f-bd31-202560f0afa9.png">
