### ISSUE TITLE
Datepicker: Not responsive on iPhone 5S/SE

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5277]
**Describe the bug**
Datepicker not responsive on iPhone 5s/se(320X568 or below mobile devices)

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datepicker/example-legend.html or any examples on datepicker component
2. Click on Datepicker
3. See error

**Expected behavior**
Datepicker should be responsive on iPhone 5s/se(320X568 or below mobile devices)

**Version**
v4.53.0-dev

**Screenshots**
Example legend
<img width="343" alt="Screen Shot 2021-06-07 at 7 02 42 PM" src="https://user-images.githubusercontent.com/84306838/121006210-3663ea80-c7c3-11eb-89d0-f1606c555fe2.png">
Example range
<img width="341" alt="Screen Shot 2021-06-07 at 7 03 33 PM" src="https://user-images.githubusercontent.com/84306838/121006224-39f77180-c7c3-11eb-9c25-0314cf0f1a62.png">

**And other Examples.**

**Platform**
 - iPhone 5s/se(320X568 or below mobile devices) - all browsers

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Calling this minor. For testing really just need to test R-2 mobile devices iphone 5 is quite old

**Comment by tmcconechy** [comment]
Descoping as we dont support this device
