### ISSUE TITLE
Arrange: Line spacing of text and handles not displayed properly

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5281]
**Describe the bug**
Arrange: Line spacing of text and handles not displayed properly

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/arrange/example-index.html
2. Click on any "Items" (notice that the line spacing isn't properly displayed)
3. See error

**Expected behavior**
Line spacing of the text and handles should be displayed properly(check actual and expected result on screenshots)

**Version**
v4.53.0-dev

**Screenshots**
Actual Result
<img width="633" alt="Screen Shot 2021-06-08 at 7 02 53 PM" src="https://user-images.githubusercontent.com/84306838/121175611-d5edaf80-c88d-11eb-9c97-95cf6bd9ff68.png">
Expected Result
<img width="701" alt="Screen Shot 2021-06-08 at 7 12 38 PM" src="https://user-images.githubusercontent.com/84306838/121175635-e00fae00-c88d-11eb-9215-8bd0188df36f.png">

**Platform**
-All browsers/mobile devices

**Additional context**
N/A

**Comment by jbrcna** [comment]
this issue is now resolved.
 v4.62.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/arrange/example-index.html
