### ISSUE TITLE
Spinbox: misaligned spinbox outline & focus in short example

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5282]
**Describe the bug**
Spinbox: misaligned spinbox outline & focus in short example

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/spinbox/example-short.html
2. Tab & focus on the spinbox
Notice the focus is not aligned as well as the outline of the field. 

**Expected behavior**
Focus & field outline should be aligned

**Version**
ids - 4.53 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/121189665-e35e6600-c89c-11eb-9397-7715f59332f2.png)

**Platform**
All major browser & devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
We can no longer reproduce this issue. It must have been fixed.

**Comment by janahintal** [comment]
This issue is now resolved. 

![image](https://user-images.githubusercontent.com/45757016/122911988-72ce4380-d38a-11eb-9caf-aafd86c4e939.png)
![image](https://user-images.githubusercontent.com/45757016/122912135-95605c80-d38a-11eb-97d1-d18ee289f85e.png)
