### ISSUE TITLE
Label: Required * not being shown for file upload input

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise#5285]
Go to https://main-enterprise.demo.design.infor.com/components/fileupload/test-required.html
"Upload a File" should have required asterisk like "Last Name" text input field

![image](https://user-images.githubusercontent.com/1594815/121223283-a76cd600-c887-11eb-92e4-26c87d88882b.png)

**Comment by davidcarlsonberg** [comment]
Is the purpose of all of the fields on this page to be `required`?

**Comment by hemantg05** [comment]
Is it a just a matter of adding required class to input field in test file?

The bug was discovered at the level on enterprise-ng. 

When we add required=true on label or when we add data-validate="required" on file upload input field, it should automatically show asterisk. It is not showing asterisk. 

```
<div class="field">

  <label
    soho-label
    for="file-upload"
    required="true">
    {{ label }}
  </label>

  <input
    id="file-upload"
    soho-alert
    data-validate="required"
    soho-fileupload
    soho-trackdirty
    (change)="onFileSelected($event)"
    (changeEvent)="onSelectedFileRemoved($event)"
    accept="{{ supportedFileTypes }}"/>

</div>
```

So, does this change on test file by adding a required class manually work there?

Please verify.
cc @tmcconechy, @davidcarlsonberg

**Comment by tmcconechy** [comment]
@tmcconechy yeah the fix doesnt seem to address that. Will request changes for the label class but this does work

```
          <label soho-label for={{name1}} class="required">Normal Input (Required)</label>
          <input
            soho-fileupload [attributes]="fileUploadOptions.attributes" [disabled]="fileUploadDisabled" [readonly]="fileUploadReadOnly"
            id="{{name1}}" name={{name1}} accept="true" class="required" (change)="onChange($event)" data-validate="required"
          />
```

**Comment by tmcconechy** [comment]
@davidcarlsonberg just saw your question. it really doesnt matter we just need one example file input that confirms its working can be in any of the example pages are whats there now is fine. Except maybe we should get the class on the label to work.

**Comment by davidcarlsonberg** [comment]
https://github.com/infor-design/enterprise/pull/5451#issuecomment-886206421

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.54.0-dev.

https://main-enterprise.demo.design.infor.com/components/fileupload/test-required.html
![Screen Shot 2021-07-29 at 12 43 05 PM](https://user-images.githubusercontent.com/84306838/127432923-678095ca-07af-48e3-bc0b-aea37d4cebbd.png)

Moving this ticket to Done.

Thanks!
