### ISSUE TITLE
Datagrid: Unable to reopen filter options after doing pagination and clicking other filter options

### ISSUE THREAD

**Issue by ktfields** [infor-design/enterprise#5286]
**Describe the bug**
Unable to open filter option again after doing pagination and clicking other filter options. Issue occurs on both server-side and client-side paging.

**To Reproduce**

Case 1:
1. Go to 
[client-side] https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-filter-paging-client-side.html 
[server-side] https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-filter-paging-server-side.html
2. Click on any filter options dropdown (keep it open)
3. Click on "Next Page" or "Last Page" button
4. Close the filter options dropdown
5. Try to open it again

Case 2:
1. Go to 
[client-side] https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-filter-paging-client-side.html 
[server-side] https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-filter-paging-server-side.html
2. Click on any filter options dropdown (Open at least 3)
3. Reopen the previous filter option

See attached gif files for reference.

**Expected behavior**
Filter options should be opened

**Version**
ids-enterprise: 4.52

**Screenshots**
Case 1:
![fileterOption_pagination_issue](https://user-images.githubusercontent.com/39935379/121300148-08001f80-c929-11eb-8034-350a6bb868b7.gif)

Case 2:
![fileterOption_randomClicks_issue](https://user-images.githubusercontent.com/39935379/121301795-4dbde780-c92b-11eb-950e-7ff71698da21.gif)

**Platform**
 - Browser Name: Google Chrome, Microsoft Edge
 - Browser Version: Google Chrome version 91.0.4472.77, Microsoft Edge version 91.0.864.41

**Additional context**
N/A

**Comment by tmcconechy** [comment]
When fixing the first one i think it should close the filter when going to another page

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.55.0-dev.

https://main-enterprise.demo.design.infor.com/components/datagrid/test-filter-paging-client-side.html & https://main-enterprise.demo.design.infor.com/components/datagrid/test-filter-paging-server-side.html

Case 1:
**Client side**
![Client1](https://user-images.githubusercontent.com/84306838/129310491-60de500d-6eab-4729-b96e-65b4521e9b90.GIF)

**Server side**
![Server1 2](https://user-images.githubusercontent.com/84306838/129311107-6c0dcd8a-808a-41e5-9fb8-fd921a5929e1.GIF)

Case 2:
**Client side**
![Client2](https://user-images.githubusercontent.com/84306838/129310584-55bdee50-2e5a-48a2-9a1e-455f5c822b87.GIF)

**Server side**
![Server2 2](https://user-images.githubusercontent.com/84306838/129311113-ea38eed7-5ec2-4b9e-889e-4d802e7a4937.GIF)

Moving this ticket to Done. 

Thanks!
