### ISSUE TITLE
Datagrid: Spacer column removed after hiding a different column

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5287]
**Describe the bug**
Datagrid: Spacer column removed after hiding a different column

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-spacer-column.html
2. Personalize Column - Hide Product Name & Activity Column 
Notice the spacer column is removed & Activity column is not hidden.

**Expected behavior**
Activity Column should be hidden & spacer column should not get removed

**Version**
IDS 4.53 - dev 

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/121330673-ce3f1100-c948-11eb-90ca-81fca02e9785.png)

**Platform**
All major browser & devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
I think its working ok enough as this is a bit of an  odd case.

**Comment by tmcconechy** [comment]
Descoping for now
