### ISSUE TITLE
Datagrid: Overlapping text after expanding search field

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5288]
**Describe the bug**
Datagrid: Overlapping text after expanding search field

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar.html
2. Type 2015 in the search field 
3. Minimize to responsive view
4. Hover & click to search field to expand 
5. Click outside to minimize the search field 
6. Expand & minimize the browser
7. Repeat step 4 to reproduce

**Expected behavior**
Text should not overlap

**Version**
5.43 - ids - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/121336588-40662480-c94e-11eb-9d8f-a0aac5a391ca.png)

**Platform**
All major browsers. 
Screenshot provided from windows  10 chrome browser

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Think this has been like this a very long time. So may just descope this going forward

**Comment by tmcconechy** [comment]
Descoping this ue to complexity/value
