### ISSUE TITLE
Autocomplete errors when selecting an item

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#529]
**Describe the bug**
When selecting an item from the autocomplete list an error is shown in the console. This is also causing the selection events not work.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/autocomplete/example-index.html
2. Click into the field and type a
3. Select any item
4. Look at the console

**Expected behavior**
No error

**Context**
Bug seems to have been introduced in 4.8 and not spotted

**Comment by brianjuan** [comment]
Passed QA testing on all browsers.
Environment: http://490-rc1-sohoxi.demo.design.infor.com/components/autocomplete/example-index.html
