### ISSUE TITLE
Toolbar-flex: Collapsible searchfield button not displayed properly on Firefox

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5290]
**Describe the bug**
searchfield button not displayed properly and not in line with other buttons

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-searchfield-collapsible.html 
2. Click on searchfield button
3. See error(searchfield button not in line with other buttons)

**Expected behavior**
<img width="464" alt="Screen Shot 2021-06-09 at 8 02 28 PM" src="https://user-images.githubusercontent.com/84306838/121350822-b0c87200-c95d-11eb-8931-df2d405b0195.png">

**Version**
v4.53.0-dev

**Screenshots**
Actual Result
<img width="443" alt="Screen Shot 2021-06-09 at 8 00 54 PM" src="https://user-images.githubusercontent.com/84306838/121351123-ff760c00-c95d-11eb-9e94-2aabf46f1f36.png">

Expected Result
<img width="464" alt="Screen Shot 2021-06-09 at 8 02 28 PM" src="https://user-images.githubusercontent.com/84306838/121350822-b0c87200-c95d-11eb-8931-df2d405b0195.png">

**Platform**
-Firefox

**Additional context**
N/A

**Comment by tmcconechy** [comment]
@tjamesallen15 maybe check this as you are working on something very closely related

**Comment by tjamesallen15** [comment]
> @tjamesallen15 maybe check this as you are working on something very closely related

Sure!

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.53.0-dev.

Searchfield icon is now displayed properly on Firefox.
<img width="461" alt="Screen Shot 2021-06-15 at 4 50 21 PM" src="https://user-images.githubusercontent.com/84306838/122023497-320a8380-cdfa-11eb-8feb-8099407257d3.png">

Moving this ticket to Done.

Thanks!
