### ISSUE TITLE
Datagrid: Grid Header is misaligned in list mode with isEllipsis

### ISSUE THREAD

**Issue by brianpettit** [infor-design/enterprise#5291]
When using the "isList" option for a grid with the "new" theme and an ellipsis formatter, the text in the column using ellipsis is pushed up.

![image](https://user-images.githubusercontent.com/74990136/121360631-9614df80-c902-11eb-957f-b640de70a628.png)

**To Reproduce**
Using the demo locally - http://localhost:4200/ids-enterprise-ng-demo/datagrid-fixedheader

Change this - 

datagrid-fixedheader.demo.ts
buildGridOptions - 
remove       
rowHeight: 'small', filterable: true,
add       
isList: true,

datagrid-paging-data.ts
Add formatter: Soho.Formatters.Ellipsis, to a couple columns.

Make sure you're using "Versions - New"

**Expected behavior**
The "ellipses" formatted column headers should not be higher than the rest.

**Version**
- ids-enterprise-ng: 9.4

**Comment by tmcconechy** [comment]
Please note when making issues we have a template https://github.com/infor-design/enterprise/issues/new/choose

This may be a bug but just want to mention that generally the IsList option is for very simple lists that are readonly and dont have many features. It was made as a "simple list" design. So you might be better off not using that option.

But we can eventually have a look

**Comment by dersgniw** [comment]
Our designers want to use the light header color and lack of cell borders.  Is there a simple way to get that format without using isList?

**Comment by dersgniw** [comment]
And I used the template.

**Comment by tmcconechy** [comment]
No that is the isList format. But this has been a bit confusing part of the design to explain. The isList is not a personal choice. Its for use cases where the grid is more like a "simple table" like ball pack maybe 5 fields and not many grid features used (maybe sorting and paging is ok). Editing doesnt work well in isList mode.

It sort of expanded and people expect they can use just either one that they want but it wasn't the intention. The intention was it was for more simple list use cases. For editing and advanced grid features should use the "standard" one.

That being said i dont mind fixing this issue but there are other limitations we wont be able to fix in that mode.

**Comment by tmcconechy** [comment]
Side note (to self) in web components we should make a SimpleList component that has the isList style so its not combined with other DataGrid features.

**Comment by brianpettit** [comment]
Thanks Tim.
