### ISSUE TITLE
Charts: Update legends to have a setting

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5292]
**Is your feature request related to a problem or use case? Please describe.**
Implement a change to the charts so that the design will show a popup for legends when it doesnt fit. See https://jira.infor.com/browse/UXD-2682

**Describe the solution you'd like**
- Implement this design
- Decide if it goes in the old and current code

**Describe alternatives you've considered**
Maybe we do this just in the new charts.

**Additional context**
See design https://jira.infor.com/browse/UXD-2682
Relates closely to https://github.com/infor-design/enterprise/issues/5275

**Comment by janahintal** [comment]
The list is working as expected. But the Response Late focus is not aligned in Classic Theme. 
![image](https://user-images.githubusercontent.com/45757016/125431250-d3d35e74-f208-45ca-b390-28f9c59f5b16.png)

**Comment by tmcconechy** [comment]
Thanks @janahintal. Would you be able to have a second look @yohannahbautista  ?

**Comment by tmcconechy** [comment]
@yohannahbautista the only small problem with this is it seems to be "moving" when you focus it. In this video

https://drive.google.com/file/d/1IGVnEGRzNyFlIx_RTc-lWTAjdEnEsHDH/view

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.54.0-dev.

Response Late focus is now aligned in Classic Theme
<img width="648" alt="Screen Shot 2021-07-22 at 4 18 33 PM" src="https://user-images.githubusercontent.com/84306838/126609164-ea309185-3c65-4fca-aa1d-bb6d07a52b05.png">

Moving this ticket to Done.

Thanks!
