### ISSUE TITLE
Lookup: Readonly not properly working 

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5298]
**Describe the bug**
Readonly not properly working 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/lookup/example-not-tabbable.html
2. Click on Lookup from "Products (readonly)"
3. See error (it shouldn't be clickable since it's readonly)

**Expected behavior**
![expected1](https://user-images.githubusercontent.com/84306838/121522926-357fc280-ca28-11eb-80ce-868b105f50dc.gif)

**Version**
v4.53.0-dev

**Screenshots**
Actual Result
![actual1](https://user-images.githubusercontent.com/84306838/121522900-2f89e180-ca28-11eb-8716-7eac475538a0.gif)

Expected Result
![expected1](https://user-images.githubusercontent.com/84306838/121522926-357fc280-ca28-11eb-80ce-868b105f50dc.gif)

**Platform**
All browsers/mobile devices

**Additional context**
N/A

**Comment by tmcconechy** [comment]
@nganotice i just changed the label to "not editable" this is not a bug as this example is showing a "non editable" lookup not readonly state

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
