### ISSUE TITLE
Lookup: Clear icon not properly placed at the end of the textbox on mobile

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5299]
**Describe the bug**
Clear icon not properly placed at the end of the textbox on mobile

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/lookup/example-paging.html (all that has products and keywords are searchable)
2. Click on lookup icon
3. Enter anything then the clear icon isn't placed at the end of the textbox

**Expected behavior**
It should be placed at the end of the textbox
<img width="231" alt="Screen Shot 2021-06-10 at 8 31 21 PM" src="https://user-images.githubusercontent.com/84306838/121525519-06b71b80-ca2b-11eb-8d01-a0065f4035f0.png">

**Version**
v4.53.0-dev

**Screenshots**
Actual Result
<img width="236" alt="Screen Shot 2021-06-10 at 8 32 03 PM" src="https://user-images.githubusercontent.com/84306838/121525549-0e76c000-ca2b-11eb-8b1d-e26ce9532ec3.png">

Expected Result
<img width="231" alt="Screen Shot 2021-06-10 at 8 31 21 PM" src="https://user-images.githubusercontent.com/84306838/121525519-06b71b80-ca2b-11eb-8d01-a0065f4035f0.png">

**Platform**
All mobile devices

**Additional context**
N/A

**Comment by tmcconechy** [comment]
@rob2d do you recall fixing this? i think it regressed

**Comment by ericangeles** [comment]
I can pick this one up @tmcconechy

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.53.0-dev.

**iPhone 12 Pro Max** - actual device
<img width="396" alt="Screen Shot 2021-06-22 at 4 52 56 PM" src="https://user-images.githubusercontent.com/84306838/122895116-62ae6800-d37a-11eb-9f9d-3a3335e9d466.png">

**Samsung Galaxy S20** - browserstack
<img width="383" alt="Screen Shot 2021-06-22 at 4 49 28 PM" src="https://user-images.githubusercontent.com/84306838/122894892-309d0600-d37a-11eb-93cc-fd21d0ca8716.png">

Moving this ticket to Done.

Thanks!
