### ISSUE TITLE
Bar/BarGrouped/BarStacked: Vertical Gridlines missing when changing colors in new&classic/high contrast

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5301]
**Describe the bug**
Vertical Gridlines missing when changing colors in high contrast

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/bar/example-contextmenu.html (this issue applies to all examples)
2. Click on More actions then Versions>New/Classic then Modes>High Contrast then Colors>Any color besides default
3. See error
4. Also test bubble https://github.com/infor-design/enterprise/issues/5309

**Expected behavior**
Vertical Gridlines should still show when changing colors in new&classic/high contrast

**Version**
v4.53.0-dev

**Screenshots**
Version: New/Classic - Modes: High Contrast - Colors: Default -- Vertical Gridlines are showing
<img width="1680" alt="Screen Shot 2021-06-10 at 8 59 37 PM" src="https://user-images.githubusercontent.com/84306838/121529458-002aa300-ca2f-11eb-8ca5-f0e4768b981a.png">

Version: New/Classic - Modes: High Contrast - Colors: Amber -- Vertical Gridlines are missing
<img width="1680" alt="Screen Shot 2021-06-10 at 9 00 03 PM" src="https://user-images.githubusercontent.com/84306838/121529492-0882de00-ca2f-11eb-998b-561899ba2326.png">

**Platform**
All browsers/mobile devices

**Additional context**
N/A

**Comment by nganotice** [comment]
Hi @tmcconechy - I've updated the ticket coz I also encountered the same issue with both Bar Grouped & Stacked. Is this already fine with you or you want me to create a separate ticket for both? Thanks!

**Comment by tmcconechy** [comment]
Perfectly fine. I think its going to be the same fix.

**Comment by nganotice** [comment]
Hi @tmcconechy encountered the same issue in Column/Column Grouped/Column Stacked - horizontal gridlines are missing when changing colors in new&classic/high contrast.

**Column** - https://main-enterprise.demo.design.infor.com/components/column/example-balance.html (this issue applies to all examples)
<img width="375" alt="Screen Shot 2021-06-17 at 7 56 35 PM" src="https://user-images.githubusercontent.com/84306838/122392475-7aff3b00-cfa6-11eb-816d-cc8c6fecc6dd.png">

**Column Grouped** - https://main-enterprise.demo.design.infor.com/components/column-grouped/example-contextmenu.html (this issue applies to all examples)
<img width="834" alt="Screen Shot 2021-06-17 at 7 58 42 PM" src="https://user-images.githubusercontent.com/84306838/122392512-83577600-cfa6-11eb-8ee6-dba39b6ca896.png">

**Column Stacked** - https://main-enterprise.demo.design.infor.com/components/column-stacked/example-contextmenu.html (this issue applies to all examples)
<img width="832" alt="Screen Shot 2021-06-17 at 7 57 44 PM" src="https://user-images.githubusercontent.com/84306838/122392542-8a7e8400-cfa6-11eb-87a1-bb93e102030a.png">

Thanks!

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
