### ISSUE TITLE
Donut: Would like a tooltip on centerLabel of donut chart

### ISSUE THREAD

**Issue by guptaruchi-github** [infor-design/enterprise#5302]
**Describe the bug**
soho-tooltip in centerLabel of donut chart is not getting added.

**To Reproduce**

Add soho-tooltip to centerLabel of Donut.
Use code below
centerLabel: 

```
<tspan  x="0" dy="-0.4em" style="font-size:${fontSize}">${this.lang.get("total")}${centerLabel}</tspan> <tspan x="0" dy="1.4em" style="font-weight:bold;font-size:${fontSize}" 

soho-tooltip [title]="donutTooltip">${centerValue}</tspan>`
```

**Expected behavior**
Tooltip should appear in the center of the donut chart.

Version

ids-enterprise-ng : 9.1.1

Screenshots
![image](https://user-images.githubusercontent.com/85481652/121529860-707af980-ca1a-11eb-8f81-3501b0a24c0f.png)

Platform
OS Version: Windows 10 or iOS 8
Browser Name: Chrome
Browser Version: 91.0.4472.77

**Comment by tmcconechy** [comment]
@guptaruchi-github what team are you on.

We can add this (eventually) but we would add it as a setting to the chart, just to clarify

**Comment by guptaruchi-github** [comment]
I am from LN Homepage Widgets team. Then I would be expecting this as a part of SohoChartOptions interface.

**Comment by janahintal** [comment]
Failing in Mobile iOS and Android Devices.

Still not centered in mobile devices. 
![image](https://user-images.githubusercontent.com/45757016/127637106-9f97c5ed-335e-4974-bd09-15ed993d7b25.png)
![image](https://user-images.githubusercontent.com/45757016/127637372-8e38adf4-10af-461c-acea-cb047fe12058.png)
