### ISSUE TITLE
Personalize: form3 issue in mobile/responsive view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5303]
**Describe the bug**
there's some gradient color in tabs when in mobile/responsive view

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/personalize/example-form3-short.html
    or https://main-enterprise.demo.design.infor.com/components/personalize/example-form3.html
2. Resize to moible view or open in Browserstack
3. See error
4. Play around with tabs

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/121481800-13257f00-c9ff-11eb-8fa3-c38fb1d718a5.png)

**Version**

- ids-enterprise: v4.53.-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/121481767-0e60cb00-c9ff-11eb-8070-91994a406f64.png)

**Platform**
mobile/responsive view

**Additional context**

**Comment by jbrcna** [comment]
QA Failed
When I switch to `Classic` theme & `Dark` mode the header becomes black so I refresh the page to see if it's the default color on `classic dark` but after refresh the header becomes azure and a gradient color appears in tabs.
v4.54.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/personalize/example-form3-short.html
![Large GIF (416x434)](https://user-images.githubusercontent.com/56722184/126729775-6877634d-f707-476f-814c-2b31d38fd295.gif)
_iPhone 12 Pro Max browserstack_

![image](https://user-images.githubusercontent.com/56722184/126730350-9c126a7e-8e97-42b8-aab2-60ff1fc9d35f.png)
_chrome devtools_

**Comment by jbrcna** [comment]
the issue is now resolved. moving this ticket Done. thank you.
v4.54.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/personalize/example-form3.html
![image](https://user-images.githubusercontent.com/56722184/127620469-8c7f9ca4-4ec1-4b82-8cbe-cbff53e3b2ca.png)

**Comment by tmcconechy** [comment]
Should be closed
