### ISSUE TITLE
Icons: The color should be slate6

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5307]
**Describe the bug**
Got from design that the color in uplift light of the icons is incorrect everywhere. And in particular on cards.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/button/example-index.html
2. here the icon and text icons should be slate6 not slate 7 in default state
3. Go to https://main-enterprise.demo.design.infor.com/components/cards/example-index.html
4. Here the icon in default slate should be slate6 but its slate 8 or 9?

**Expected behavior**
All icons slate 6 in default state. ALSO check the web components

**Version**
- ids-enterprise: [e.g. v4.52]

**Additional context**
https://jira.infor.com/browse/UXD-2514

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.54.0-dev.

Button - All icons and text icons are in the correct color (#606066)
![Screen Shot 2021-07-22 at 4 45 46 PM](https://user-images.githubusercontent.com/84306838/126612370-d1b1496b-0648-4b00-a44c-90b9fe3465d0.png)

Cards - All icons are in the correct color (#606066)
![Screen Shot 2021-07-22 at 4 45 16 PM](https://user-images.githubusercontent.com/84306838/126612325-0762900b-ca60-45dc-984f-0e46cffaf136.png)

Moving this ticket to Done.

Thanks!
