### ISSUE TITLE
Locale: Mask incorrectly applied on large negative number.

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#5308]
**Describe the bug**
The mask is adding a 0 to large negative numbers.

**To Reproduce**
1. Navigate to https://master-enterprise.demo.design.infor.com/components/locale/test-format-big-negative.html
2. Enter the value -1,482,409,800.81
3. Hit the format button
4. See that the read only field now has an additional 0 inserted into it: -14824098000.81

**Expected behavior**
Extra zeros should not be inserted into the number

**Version**

- ids-enterprise: v4.51.0-dev

**Screenshots**
![MaskOnNegativeBigNumber](https://user-images.githubusercontent.com/22107636/121714320-55080100-caa3-11eb-9146-04c2487d75fe.gif)

**Platform**
 - Infor Application/Team Name: Infor Landmark
 - Device: All
 - OS Version: All
 - Browser Name: All
 - Browser Version: All

**Additional context**
If you hit format on the value that initially there, it seems to work. Maybe an issue having a zero before the decimal point?

**Comment by lipetzan** [comment]
Multiple customers (three FSM thus far) reporting this. Raised priority from my perspective.

**Comment by Sovia** [comment]
Only seems to happen for a number with 10 digits before the decimal point

**Comment by tmcconechy** [comment]
And only with the minus. What kind of numbers are minus billions? (curious)

**Comment by Sovia** [comment]
Certainly something in financials!

**Comment by lipetzan** [comment]
See more on https://jira.lawson.com/browse/LMCLIENT-36032 @tmcconechy

**Comment by tmcconechy** [comment]
@EdwardCoyle can you maybe please see about this one and if it has any easy fix?

**Comment by vonnyw** [comment]
@tmcconechy  and @EdwardCoyle We need a patch for 4.51 and potentially 4.50 if it's low risk.

**Comment by tmcconechy** [comment]
Have to see about 4.50 we don't usually patch that far back and i think it might have a problem building. But i will try..

Also i know there was another issue you wanted a patch for but i dont know which one? Can you remind me of that other issue and i can add that too to 4.51

**Comment by tmcconechy** [comment]
@Sovia do you guys use the "round" option on purpose as far as you know? Or is it just our code doing that by default? 

bug is here...
```
this.truncateDecimals(-1482409800.81, 2, 2, { round: true})
"-14824098000.81"
this.truncateDecimals(-1482409800.81, 2, 2, { round: false})
"-14824098000.81"
```

**Comment by tmcconechy** [comment]
OK this issue and #4974 are now patched in 4.51.3 -> Did an angular build and its ids-enterprise-ng@9.5.1

**Comment by janahintal** [comment]
Working as expected in https://main-enterprise.demo.design.infor.com/components/locale/test-format-big-negative.html?theme=new&mode=light&colors=0066D4

Verified in https://main-enterprise.demo.design.infor.com/components/locale/test-format-big-negative.html?
![image](https://user-images.githubusercontent.com/45757016/122022270-0509a100-cdf9-11eb-964e-e5ce7270504b.png)
![image](https://user-images.githubusercontent.com/45757016/122022337-12269000-cdf9-11eb-8bd1-6c89f8b8d961.png)


Will now move this ticket to done. 

Observation: Unable to input negative sign directly from the field.

**Comment by vonnyw** [comment]
@tmcconechy Can we get a patch for 4.50? THanks

**Comment by tmcconechy** [comment]
Should we include https://github.com/infor-design/enterprise/issues/5318 as well?

**Comment by Sovia** [comment]
Only this one in the 4.50 patch please!
