### ISSUE TITLE
Bubble: Horizontal and Vertical lines missing when changing colors in new&classic/high contrast 

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5309]
**Describe the bug**
Horizontal and Vertical lines missing when changing colors in new&classic/high contrast 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/bubble/example-contextmenu.html (this issue applies to both examples)
2. Click on More actions then Versions>New/Classic then Modes>High Contrast then Colors>Any color besides default
3. See error

**Expected behavior**
Horizontal and Vertical lines should still show when changing colors in new&classic/high contrast 

**Version**
v.4.53.0-dev

**Screenshots**
Version: New/Classic - Modes: High Contrast - Colors: Default -- Horizontal and Vertical lines are showing
<img width="1680" alt="Screen Shot 2021-06-14 at 8 47 57 PM" src="https://user-images.githubusercontent.com/84306838/121894617-eac8b800-cd51-11eb-848c-c179d9337ff5.png">

Version: New/Classic - Modes: High Contrast - Colors: Emerald -- Horizontal and Vertical lines are missing
<img width="1680" alt="Screen Shot 2021-06-14 at 8 48 22 PM" src="https://user-images.githubusercontent.com/84306838/121894641-f320f300-cd51-11eb-89a9-b261007140f3.png">

**Platform**
All browsers/mobile devices

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Going to consolidate with https://github.com/infor-design/enterprise/issues/5301 as this is surely the same issue
