### ISSUE TITLE
Fieldfilter: Unable to select in the dropdown filter

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5310]
**Describe the bug**
Fieldfilter: Unable to select in the dropdown filter

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-filter/example-index.html
2. Tab to the dropdown field and try to select a record using keyboard function or hover and select a record.

**Expected behavior**
Data should be selected

**Version**
IDS - 4.53 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/121897437-f7024480-cd54-11eb-83bd-bf95f3731c40.png)

**Platform**
All major browsers, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping all filter field issues for now
