### ISSUE TITLE
Builder: Back to order overlaps with wizard/progress bar in responsive/mobile(402x767 below)

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5312]
**Describe the bug**
Back to order overlaps with wizard/progress bar in responsive/mobile(402x767 below)

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/builder/example-builder-nosidebar.html (this issue applies to examples builder nosidebar, subtitle test, wizard)
2. View on responsive/any mobile(402x767 below)
3. See error

**Expected behavior**
Back to order should be responsive and shouldn't overlap with wizard/progress bar in responsive/mobile(402X767 below)

**Version**
v4.53.0-dev

**Screenshots**
Responsive view(402x767)
<img width="423" alt="Screen Shot 2021-06-14 at 9 33 12 PM" src="https://user-images.githubusercontent.com/84306838/121900600-2cf4f800-cd58-11eb-9c15-d52e00f758d4.png">

iPhone 12 Pro
<img width="389" alt="Screen Shot 2021-06-14 at 9 22 44 PM" src="https://user-images.githubusercontent.com/84306838/121900155-b0621980-cd57-11eb-82a5-f4050ef38176.png">

Samsung Galaxy s20
<img width="382" alt="Screen Shot 2021-06-14 at 9 30 40 PM" src="https://user-images.githubusercontent.com/84306838/121900344-e7d0c600-cd57-11eb-8136-83c94ad857a5.png">

**Platform**
All browsers - Responsive view/mobile devices(402x767 below)

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Descoping this for now
