### ISSUE TITLE
Datagrid: Column with a filter type of integer has console error when using inRange filtering

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#5313]
**Describe the bug**
After selecting "in range" as the filter for a column with an integer filter type and typing in a value in the column header, an error appears in the console.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-filter.html
2. Click on the filter dropdown in the "Qty" column
3. Select the "In Range" filter option
4. Type a value into the filter input
5. Go to the console and see that an error appears

**Expected behavior**
I would expect for the In Range option for an integer filter type to operate similar to other filter types that have the In Range option.

**Version**
- ids-enterprise: v4.51.1

**Screenshots**
![image](https://user-images.githubusercontent.com/76002134/121921329-8597a700-ccfe-11eb-9f15-3a4025c655f1.png)

![image](https://user-images.githubusercontent.com/76002134/121921166-5da84380-ccfe-11eb-8e94-d15e6b3a7a05.png)

**Platform**
 - Infor Application/Team Name: lawson
 - Device: (if applicable) N/A
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: 91.0.4472.77 (Official Build) (64-bit)

**Additional context**
Could the solution to this be put into the 4.51.1 release as well?

**Comment by tmcconechy** [comment]
This fature isnt a priority right now due to the comments on https://github.com/infor-design/enterprise/issues/4438

So this may take a while to be fixed. Suggest not using range with integer for now

**Comment by s-werking** [comment]
Oh I see, thank you. We will plan on excluding range from the filter conditions. This ticket can be closed

**Comment by tmcconechy** [comment]
OK we do plan on fixing the other one someday.... So maybe watch that for later :)
