### ISSUE TITLE
Searchfield input height not the same as searchfield-wrapper when having searchfield with categories, Firefox

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise#5314]
When using soho-searchfield with categories the button (34px - inherited from searchfield-wrapper) for selecting the category does not have the same height as the searchfield input (3.8rem).

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/searchfield/example-categories-full.html?theme=new&mode=light&colors=0066D4
2. Make sure theme new is selected
3. View difference in height

**Expected behavior**
Should be same height (appear aligned).

**Version**

- ids-enterprise: v.4.52

**Screenshots**
<img width="695" alt="Screenshot 2021-06-14 at 20 09 58" src="https://user-images.githubusercontent.com/73601152/121938762-822b0c80-cd4c-11eb-90c8-df2b13b953c4.png">
2.0

**Platform**
 - Infor Application/Team Name: Infor M3
 - OS Version: Mac OSX
 - Browser Name: Firefox
 - Browser Version: 89.0 (64-bit)

**Comment by tmcconechy** [comment]
next issue for you please @RiyaTayal20

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.53.0-dev.

**Firefox**
<img width="1212" alt="Screen Shot 2021-06-22 at 4 27 31 PM" src="https://user-images.githubusercontent.com/84306838/122891075-cf276800-d376-11eb-860c-bd88ad372ed5.png">

Also tested on other browsers. Moving this ticket to Done.

Thanks!
