### ISSUE TITLE
Datagrid: Updating/refreshing (loadData) the datagrid with a column filter value doesn't clear that value

### ISSUE THREAD

**Issue by kaeleding** [infor-design/enterprise#5321]
**Describe the bug**
From the version we're upgrading from, 4.11, there was code in loadData where when pagerInfo was undefined, default values were set to it, especially pagerInfo.type to 'initial'. This would make it so it will go through renderHeader(), which clears the value of the column header.

In the latest version, this was removed, based from https://github.com/infor-design/enterprise/pull/2404.

It looks like weird since the column filter is still there after update/refresh which makes it look like the result rows should be filtered, but its not.

Also noting that the value for this.settings.toolbar is null (we don't have toolbar on our use case), so the columns do not get cleared in updateDataset()'s clearFilter().

**To Reproduce**
I wasn't able to find a good page to test this on, so I just tried a hacky way.

Prerequisite: Save the value of the current dataset to a variable, let's just call it currentDataset.

1. Go to http://localhost:4000/components/datagrid/test-filter-load-data-update-columns.html
2. On the Action column, set any filter value
4. Set the value of this.settings.toolbar to null 
3. Call $('#datagrid').data('datagrid').updateDataset(currentDataset, null)

**Expected behavior** : The column filter should be cleared. (If not, the current column filter should be applied after update/refresh, which does not currently.)

**Version**
ids-enterprise: v4.51.1

**Screenshots**
![controls](https://user-images.githubusercontent.com/18295372/122184713-12895e80-cebf-11eb-9d26-87e855b00afb.gif)

**Platform**
  - Infor Application/Team Name: lawson
  - Device: (if applicable) N/A
  - OS Version: Windows 10
  - Browser Name: Chrome
  - Browser Version: 91.0.4472.77 (Official Build) (64-bit)

**Additional context**
Not sure if we should just manually clear the column headers ourselves. Would like to know more about this change choice. Thanks.

**Comment by tmcconechy** [comment]
The details for the changes are on https://github.com/infor-design/enterprise/issues/2383 but im not able to see what you are seeing in the steps.

1. Not sure what `this.settings.toolbar` means (or why that would matter)
2. Don't have currentDataset.. 

So what i did try is:

1. go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-filter-load-data-update-columns.html
1. select a value and filter the lookup
1. in the console type `$('#datagrid').data('datagrid').updateDataset([], null)`

Then i do see the grid update to no rows and the filter reset.

**Comment by kaeleding** [comment]
Hi @tmcconechy, the `this.settings.toolbar` having a value is what actually makes it so that the filters get reset, inside the `updateDataset`  function, it goes through the line `this.clearFilter()`

In the case where `this.settings.toolbar` is undefined, which is in our case, it doesn't undergo `this.clearFilter()` which is why the filter doesn't get cleared. 

On https://main-enterprise.demo.design.infor.com/components/datagrid/test-filter-load-data-update-columns.html, it looks like the value for `this.settings.toolbar` is set, that's why running `$('#datagrid').data('datagrid').updateDataset([], null)` will reset the filter.

**Comment by tmcconechy** [comment]
OK, Still not getting this? How can i reproduce this exactly? Could try a  stack blitz? https://stackblitz.com/edit/ids-enterprise-4520

I "almost" get what your saying but having a problem working out how to do the steps. Maybe you can just call clearFilter then for your scenario and we shelf this?

**Comment by kaeleding** [comment]
[test-filter-load-data-update-columns.zip](https://github.com/infor-design/enterprise/files/6674977/test-filter-load-data-update-columns.zip)

I'm having trouble loading the datagrid with stackblitz and even jsfiddle.  I'll just give you the modified test-filter-load-data-update-columns.html file with the `toolbar` attribute commented out and with a button added to call `updateDataset()`

As you can see, setting a filter to Action, then clicking the button Update Dataset will refresh the datagrid with the filter still intact. While un-commenting out the `toolbar` attribute will clear the filter.

I think there's no harm in just manually calling clearFilter on our end, and will proceeding with that solution instead. Still I just think that this is a valid bug to report..

Thanks!

**Comment by tmcconechy** [comment]
OK, i see the issue in the code you have. Does look like a bug in that scenario.

**Comment by tmcconechy** [comment]
Steps in the console to repro on http://localhost:4000/components/datagrid/test-filter-load-data-update-columns.html

```
var x = $('#datagrid').data('datagrid')
x.settings.toolbar = null
x.updateDataset(x.settings.dataset, null)
```

but if you just do this it works

```
var x = $('#datagrid').data('datagrid')
x.updateDataset(x.settings.dataset, null)
```

But , since it has a workaround will look at other priorities first
