### ISSUE TITLE
Hierarchy: Context menu Delete and Move actions keeps on adding whenever the '...' is clicked

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5322]
**Describe the bug**
Hierarchy: Context menu Delete and Move actions keeps on adding whenever the '...' is clicked

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html
2. Search for  Kaylee Edwards and click '...'
3. Click '...' again for 3 times
Notice the Delete and Move actions adds up

**Expected behavior**
Context menu actions should stay as is even after clicking the '...' again

**Version**
4.53 ids - dev

**Screenshots** 
![image](https://user-images.githubusercontent.com/45757016/122215004-51c6a800-cedd-11eb-9767-3dcc0b0fafce.png)

**Platform**
All major browsers, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Descoping this for now
