### ISSUE TITLE
Design QA on Calendar Complete 

### ISSUE THREAD

**Issue by katieinfor** [infor-design/enterprise#5323]
**Is your feature request related to a problem or use case? Please describe.**
QA is done. Reviewed by Kev as well. Can be seen [here](https://inforonline-my.sharepoint.com/:w:/g/personal/lauren_steigerwald_infor_com/EbnTsvLd5d1Aj7PEViTHcRIBchY7O5nxdkVu8qAksuJ6vg?e=LwslFN).

**Describe the solution you'd like**
QA on calendar and cards.

[Inpage Calendar
](https://main-enterprise.demo.design.infor.com/components/monthview/test-inpage-variations.html)

[Cards/Toolbars 
](https://main-enterprise.demo.design.infor.com/components/monthview/example-inpage.html)

[Word Doc](https://inforonline-my.sharepoint.com/:w:/g/personal/lauren_steigerwald_infor_com/EbnTsvLd5d1Aj7PEViTHcRIBchY7O5nxdkVu8qAksuJ6vg?e=9RiJg4)

**Additional context**
New Workflow for Design QA:
Design>Development>DesignQA(Test)>Feedback to Dev>Back to Design

**Comment by tmcconechy** [comment]
@deep7102 can you work through the design QA on the card/calendar work you did. Skip the swipe for now we would add that later and any extra features lets discuss (like not sure what the popup example is being referred too). But the rest seem pretty clear and to be small tweaks to work through

**Comment by janahintal** [comment]
This is now working as expected in https://main-enterprise.demo.design.infor.com/components/monthview/test-inpage-variations.html & https://main-enterprise.demo.design.infor.com/components/monthview/example-inpage.html Thank you.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving it over to Done.
