### ISSUE TITLE
Datagrid: Unable to export frozen columns to Excel

### ISSUE THREAD

**Issue by amjathkhan-leanswift** [infor-design/enterprise#5328]
**Describe the bug**
When I tried to export datagrid table as a excel file, All datas with column label exported except frozen columns label. Any solutions for this

**To Reproduce**
Steps to reproduce the behavior: (this steps do not reproduce the issue)
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html
3. Click Export to excel
4. Open the file

**Expected behavior**

**Version**
- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Platform**
 - Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Again please use the template https://github.com/infor-design/enterprise/issues/new/choose so we have enough info to see your issue. I updated it for you but please go through and add the necessary info.

We have an example at https://main-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html and i see it exporting the frozen columns. So i cant reproduce this issue. Try a newer version?

**Comment by tmcconechy** [comment]
Duplicate of https://github.com/infor-design/enterprise/issues/5332
