### ISSUE TITLE
Datagrid: Unable to export frozen column labels in Excel File

### ISSUE THREAD

**Issue by amjathkhan-leanswift** [infor-design/enterprise#5332]
**Describe the bug**
When I export to Excel File, Frozen columns label missing in the excel File

**To Reproduce**

1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-frozen-columns'
2. Click on '... Export To Excel'
3. File Download 
4. See the difference between datagrid column name with excel column label. Frozen column missing missing in the excel file and also column datas mismatched

**Expected behavior**
When I export to excel, all columns labels including forzen columns labels will be there in the excel file

**Version**

- ids-enterprise: latest v 4.52.0

**Screenshots**
![image](https://user-images.githubusercontent.com/81161360/122507192-66aa5500-d01d-11eb-97c7-f65b9b14f63c.png)
![image](https://user-images.githubusercontent.com/81161360/122507219-7164ea00-d01d-11eb-8630-7184246ee3fa.png)

**Platform**
 - OS Version: [e.g. Windows 10 ]
 - Browser Name: [e.g. chrome]

**Additional context**

**Comment by janahintal** [comment]
QA Failed. 
The 'Weight' column displays the button column and not the weight data.
![image](https://user-images.githubusercontent.com/45757016/127455454-c53e4098-6ce0-486b-9d58-032d589d2271.png)

**Comment by tmcconechy** [comment]
@RiyaTayal20 yes i see what @janahintal is saying. Actually thats the right side which is also frozen? I.E. we have 3 panes. I think its getting mixed up on the other side too.
