### ISSUE TITLE
Tree: addNode() returns parent node instead of added node

### ISSUE THREAD

**Issue by kvsieminfor** [infor-design/enterprise#5334]
**Describe the bug**
`tree.addNode()` returns the parent `<li>` instead of the added `<li>` when using setting `nodeData.parent` in the addNode() call.

**To Reproduce**

Steps to reproduce the behavior using attached example:
1. Unzip [ids-tree-addnode-returns-incorrect-li.zip](https://github.com/infor-design/enterprise/files/6675601/ids-tree-addnode-returns-incorrect-li.zip)
2. Open `IDS Enterprise.html`
3. Open console
4. Note that the same `<a>` (node) element is logged twice, i.e. both `addNode()` calls return the same `<li>`.

Steps to reproduce the behavior using existing online example:
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/tree/test-add-node
2. Open console
3. Enter the following:
```javascript
    var api = $('#addnode-tree').tree().data('tree');
    let node1 = api.addNode({text: 'New Item 1', id: 'new1'});
    let node2 = api.addNode({text: 'New Item 2', id: 'new2', parent: 'new1'});
    console.log("child <a> returned when adding 'new1': ", node1.children('a').get(0))
    console.log("child <a> returned when adding 'new2': ", node2.children('a').get(0))
    console.log("<li> returned adding 'new1' equal to <li> returned adding 'new2'?", node1.get(0) === node2.get(0));
```
4. Note that the same `<a>` (node) element is logged twice, i.e. both `addNode()` calls return the same `<li>`.

**Expected behavior**
`addNode()` should return the `<li>` of the new node regardless of where in the tree it was added.

**Version**
- ids-enterprise: v4.52.0 (Note that while "latest" is said to be 4.52.0 in the docs, it appears to resolve to 4.51.4 in the examples(!)) 

**Screenshots**
Screenshot from attached example:
![ids-tree-addnode-returns-incorrect-li](https://user-images.githubusercontent.com/86047787/122528655-dcfa8780-d01c-11eb-82d9-34a25d744f01.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: 91.0.4472.106 (Official Build) (64-bit) (cohort: Stable)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
