### ISSUE TITLE
Contextmenu: Fieldoptions not properly rendered on Firefox and not properly aligned on Edge/responsive/mobile view

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5335]
**Describe the bug**
Fieldoptions not properly rendered on Firefox and not properly aligned on Edge/responsive/mobile view

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/contextmenu/example-field-options.html
2. Click on Fieldoptions
3. See error

**Expected behavior**
Fieldoptions should be properly rendered on Firefox and properly aligned on Edge/responsive/mobile view

**Version**
v4.53.0-dev

**Screenshots**
Firefox - All Fieldoptions are missing the line below
![Firefox issue](https://user-images.githubusercontent.com/84306838/122552908-7c456c00-d069-11eb-96f5-f8d2697da842.gif)

Edge - Only input LG Fieldoption is misaligned
<img width="907" alt="Screen Shot 2021-06-18 at 7 07 42 PM" src="https://user-images.githubusercontent.com/84306838/122552928-85363d80-d069-11eb-8c39-121b63fed144.png">

Responsive view (476x988 below)
<img width="366" alt="Screen Shot 2021-06-18 at 6 59 45 PM" src="https://user-images.githubusercontent.com/84306838/122551369-75b5f500-d067-11eb-894f-b6216b9a0535.png">

iPhone 12 Pro Max (actual device) - All Fieldoptions are misaligned (just click the gif if it isn't moving)
![Fieldoptions issue](https://user-images.githubusercontent.com/84306838/122551436-8fefd300-d067-11eb-9113-a48154e12d18.gif)

Samsung Galaxy S21 Ultra (browserstack) - Only input LG Fieldoption is misaligned
<img width="359" alt="Screen Shot 2021-06-18 at 6 38 01 PM" src="https://user-images.githubusercontent.com/84306838/122548811-66817800-d064-11eb-9d68-2896be45e107.png">

**Platform**
-All browsers/mobile devices

**Additional context**
N/A

**Comment by nganotice** [comment]
Hi @tmcconechy - just merged all the issues related to Fieldoptions in this ticket. Thanks!

**Comment by tjamesallen15** [comment]
Hello @ericangeles  and @tmcconechy ,

I can't reproduce this issue anymore on both edge and firefox. Note that I am testing this one on mac.

See below pictures

![12EA0039-3600-45C2-91D4-5C98774209F9_1_105_c](https://user-images.githubusercontent.com/34049950/127597785-4c732f5c-1726-4c66-b1c8-ce7f1c5dcbf6.jpeg)
![7AE296E9-8499-43E9-9EB9-0E2D560E05DC](https://user-images.githubusercontent.com/34049950/127597789-6b5392cd-04c6-48d3-9cc9-44a72c940cdd.jpeg)

**Comment by ericangeles** [comment]
@tjamesallen15 yeah, not seeing it either. Perhaps @nganotice can verify this?

**Comment by nganotice** [comment]
Hi @ericangeles @tjamesallen15 - confirming that the issues w/ Firefox/Edge's already fixed. But the issue w/ mobile's still active. Thanks!

**Comment by nganotice** [comment]
HI @tjamesallen15 - fieldoptions are still misaligned on mobile(iPhone)

![Fieldoptions issue](https://user-images.githubusercontent.com/84306838/128130915-7bb9e666-e453-4193-8ee6-3f30e5009b32.png)

Thanks!

**Comment by tjamesallen15** [comment]
Hello @nganotice ,

![2A3CF2A2-DBC4-4899-B32C-8B0B3FCAF47A](https://user-images.githubusercontent.com/34049950/128140816-f725ee5a-baf3-4433-8e76-1d7103ab0483.jpeg)

Looks fine on my end.

Thanks!

**Comment by nganotice** [comment]
Hi @tjamesallen15 - it's already aligned

![MicrosoftTeams-image](https://user-images.githubusercontent.com/84306838/128165543-27e12730-4f13-4038-a297-e3331d6d8a1d.png)

Moving this ticket to Done.

Thanks!
