### ISSUE TITLE
Homepage: No circle pager current page indicator when in High Contrast mode

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5337]
**Describe the bug**
Homepage: No circle pager current page indicator when in High Contrast mode

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html?theme=classic&mode=contrast&colors=133c59
2. Minimize to see circle pager
3. Play with the circle pager and go to different pages
4. Try for both New and Classic Version

**Expected behavior**
There should be a circle pager current page indicator 

**Version**
IDS-4.53-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/122558150-52dc0e80-d070-11eb-97cd-85300dadb721.png)

**Platform**
 All major browser OS, devices

**Additional context**
N/a

**Comment by janahintal** [comment]
QA Passed. 
Thank you. 
![image](https://user-images.githubusercontent.com/45757016/125608795-e21e4548-e209-46fc-96ac-a02385333ac8.png)
![image](https://user-images.githubusercontent.com/45757016/125608848-496bf2b6-7013-4a2c-9d45-7345f0f17d31.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
