### ISSUE TITLE
Datagrid: Column Filter Menu closes prematurely for Grids on tab panels

### ISSUE THREAD

**Issue by nbeare-infor** [infor-design/enterprise#5340]
We are experiencing some odd behaviour with grid column filtering whereby when the first item in the list is deselected, the dropdown closes immediately (shots1 and 2 below). This is only the case for the first item in the list. This makes it necessary to reopen in order to deselect other items. Subsequent items can be selected without the dropdown closing prematurely. This is only the case when the grid is on a tab panel.
Open up filter dropdown with first 3 items selected

To reproduce:-
1. On a tab panel, open up a grid column filter dropdown and some items including the fist in the list. See shot 1.
![SS5-124326-1](https://user-images.githubusercontent.com/49482971/122594075-739b6880-d05e-11eb-8e56-5e0ee501fd37.png)
2. Deselect first item (dropdown immediately closes) see shot 2.
![SS5-124326-2](https://user-images.githubusercontent.com/49482971/122594372-d68cff80-d05e-11eb-90a5-d8dbc820cb22.png)
3. Reopen the filter dropdown. shot 3
![SS5-124326-3](https://user-images.githubusercontent.com/49482971/122594505-ffad9000-d05e-11eb-892e-04402716c2b8.png)
4. Deselect next item and this time the dropdown DOES NOT close (i.e. correct behaviour). Shot 4
![SS5124326-4](https://user-images.githubusercontent.com/49482971/122594748-5adf8280-d05f-11eb-85d5-0182dfd09331.png)

**Expected behavior**
The dropdown should remain open to allow further deselections and only close when click elsewhere on the grid or press TAB key

**Version**
4.51.1, but also got the same result with latest (v4.52.0)

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Platform**
 - Infor SunSystems
 - OS Version: Windows 10
 - Chrome
 - Browser Version: 91.0.4472.106 (Official Build) (64-bit)

**Additional context**
On investigation, it looks to have appeared when Resize Observer was introduced on 5 Aug 2020 ‘Add ResizeObserver to Tabs list/panels for resize handling detection’, revision 5188d4b (components/tabs/tabs.js)
Your example https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html works fine but only because it is not on a tabs panel.
When the first item in the list is deselected, the resize observe for element[0] causes/highlights the issue. commenting it out, all works fine.

**Comment by tmcconechy** [comment]
@nbeare-infor - which example can i reproduce this on?

**Comment by nbeare-infor** [comment]
Hi @tmcconechy There isn't one ATM (to my knowledge).

**Comment by tmcconechy** [comment]
Ok we can try.. If that doesnt reproduce it when we look at this will get back to you.

**Comment by nbeare-infor** [comment]
Thanks @tmcconechy . Much appreciated.

**Comment by yohannahbautista** [comment]
Hello, I edited the example-filter page to have the datagrid in a tab in this branch: [5340-datagrid-dropdown-tab](https://github.com/infor-design/enterprise/tree/5340-datagrid-dropdown-tab)
And I can't replicate the bug. I use both the Activity columns to test the dropdown and it doesn't close when I deselect the first item. Could I ask for more details on how the datagrid and tabs were setup?

**Comment by yohannahbautista** [comment]
> @nbeare-infor @tmcconechy @ericangeles Hello, I edited the [example-filter page](http://localhost:4000/components/datagrid/example-filter.html) to have the datagrid in a tab in this branch: [5340-datagrid-dropdown-tab](https://github.com/infor-design/enterprise/tree/5340-datagrid-dropdown-tab) And I can't replicate the bug. I use both the Activity columns to test the dropdown and it doesn't close when I deselect the first item. Could I ask for more details on how the datagrid and tabs were setup?

I also tried it on NG and the dropdown doesn't close either.

**Comment by ericangeles** [comment]
@nbeare-infor can you test the latest version of IDS (both NG and EP version) with this issue?

**Comment by yohannahbautista** [comment]
@nbeare-infor @tmcconechy  @ericangeles Hello, is the bug still present in the latest version?

**Comment by nbeare-infor** [comment]
Hi @yohannahbautista , not had the opportunity to try yet.

**Comment by tmcconechy** [comment]
Yeah i dont see a way to test this. @nbeare-infor can you put together an example in stackblitz? Im not really certain from these steps exactly how to reproduce. You can use this as a starting point https://stackblitz.com/edit/ids-enterprise-4570

**Comment by yohannahbautista** [comment]
@tmcconechy @ericangeles @nbeare-infor 
Hello, I checked this again using this branch (already updated with the latest in main): [5340-datagrid-dropdown-tab](https://github.com/infor-design/enterprise/tree/5340-datagrid-dropdown-tab) and going here: http://localhost:4000/components/datagrid/example-filter.html
And I still can't replicate the bug. Is the bug still there in your end? If so, is there another example I can use?

**Comment by tmcconechy** [comment]
Ok lets table this then. Im not sure how to reproduce either @nbeare-infor if you would still like this addressed can you make an example in a stackblitz like https://stackblitz.com/edit/ids-enterprise-4590 as a starting point.

Then update steps for that example?

**Comment by tmcconechy** [comment]
Closing as was never able to reproduce correctly
