### ISSUE TITLE
Month view: Misaligned collapse focus

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5345]
**Describe the bug**
Month view: Misaligned collapse focus

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/monthview/test-inpage-variations.html
2. Go to collapse example section
3. Hover and click on January - 2020

**Expected behavior**
Focus should not look misaligned

**Version**
ids-4.53-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/122917224-5df4ae80-d390-11eb-855f-f2d274513b30.png)

**Platform**
All Major OS. Browser & Devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
cc @deep7102 - think we should fix this as this is new?

**Comment by janahintal** [comment]
QA Passed. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/123611554-4c9a1f00-d834-11eb-95a0-72312334581c.png)
![image](https://user-images.githubusercontent.com/45757016/123611581-53c12d00-d834-11eb-9a59-4978fc1ecb55.png)
