### ISSUE TITLE
TargetedAchievement: Requesting tooltip feature

### ISSUE THREAD

**Issue by bveerabathini** [infor-design/enterprise#5346]
**Is your feature request related to a problem or use case? Please describe.**
Tooltip on 'targeted-achievement' chart is not working. See https://stackblitz.com/edit/ids-quick-start-940-dlsyjf

**Describe the solution you'd like**
 We need tooltip on this 'targeted-achievement' chart .

**Describe alternatives you've considered**
No.

**Additional context**
We work on Infor LN Homepage Widgets.

**Comment by tmcconechy** [comment]
@bveerabathini what did you want the tooltip to show? Some custom text or the percent value?

**Comment by bveerabathini** [comment]
@tmcconechy ,
 to show custom text
