### ISSUE TITLE
Datepicker: keyboard +/- doesn't change the date

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#5353]
**Describe the bug**
Previously, pressing the + or - key on the keyboard would increment or decrement the date. This was missed in the move to 4.0.

**To Reproduce**
1. Go to /components/datepicker/example-index.html
2. In the first date field, press t to enter todays date
3. While in the date field, press the + key
4. The date should be incremented
5. While in the date field, press the - key
6. The date should be decremented

**Expected behavior**
The date should be incremented when + is pressed, or decremented when - is pressed

**Version**

- ids-enterprise: v4.51.0-dev

**Platform**
 - Infor Application/Team Name: Infor Landmark
 - All

**Comment by katieinfor** [comment]
Just to note- "-" does work, shift and "+" works, make sure to check on top keys and number pad. Thanks!

**Comment by jbrcna** [comment]
QA Passed
v4.54.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html
![Large GIF (612x440)](https://user-images.githubusercontent.com/56722184/125406704-b3e6d000-e3eb-11eb-9b77-f0aaca6b7f89.gif)
