### ISSUE TITLE
Popupmenu/Datagrid: Support for conditional programming on action menu item on datagrid rows. 

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise#5354]
**Is your feature request related to a problem? Please describe.**
Support for conditional programming on action menu item on datagrid rows. 

**Describe the solution you'd like**
<img width="1092" alt="Screenshot 2021-06-23 at 5 06 07 PM" src="https://user-images.githubusercontent.com/1594815/123122501-5db6ea80-d446-11eb-9329-0162f3135a91.png">

**Comment by tmcconechy** [comment]
In order to do this i think we just need to expose some of the eventing for popupmenu through the grid api.
For example beforeOpen ect
