### ISSUE TITLE
Pie Charts: alternative colors/patterns to make it more accessible.

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#5357]
**Is your feature request related to a problem or use case? Please describe.**
Color is used to indicate information on the pie chart legend. That is, the content on the right-hand side indicating which section of the pie chart it refers to is indicated only in color. 
This causes users with low color vision or users who are color blind will not be able to distinguish between the colors and will cause loss of information. See below screenshot
<img width="558" alt="LMCLIENT-34214" src="https://user-images.githubusercontent.com/29673378/123222574-a7fda180-d502-11eb-868a-a6ddbeab8260.png">

**Describe the solution you'd like**
Developers must ensure that other forms of indication, in addition to color, is used to indicate information. That is, stripes, lines and different shapes on the pie charts can be used. Alternatively, other labels can be used to indicate the pie chart association to the legend. 

**Describe alternatives you've considered**
NA

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-34214
And what application do you work on? Landmark Client

**Comment by tmcconechy** [comment]
cc @elizabethhartley

**Comment by tmcconechy** [comment]
Patterns Designs: https://www.figma.com/file/K9vE65VIsm97PHTkTBhpML/IDS-Chart-Patterns-Accessibility

**Comment by tmcconechy** [comment]
Descoping this issue ~ but this was done in the new charts https://main.wc.design.infor.com/ids-pie-chart/patterns.html
