### ISSUE TITLE
Datagrid: Personalize Columns - Headers not rendering properly

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5361]
**Describe the bug**
All Examples that has Personalize Columns - Headers aren't rendering properly

**To Reproduce**

1. Go to http://localhost:4000/components/datagrid/example-colspan.html or http://localhost:4000/components/datagrid/example-books.html (this issue applies to all examples that has Personalize Columns)
2. Click on the actions button on the upper right of the datagrid
3. Click on Personalize Columns then just click on the checkboxes

**Expected behavior**
Headers should be rendered properly

**Version**
v4.53.0-dev

**Screenshots**
Here are just a few GIFs of the issue:
Example Colspan
![Colspan](https://user-images.githubusercontent.com/84306838/123250040-37fc1500-d51c-11eb-8872-3863015f7e10.GIF)

Example Books
![Books](https://user-images.githubusercontent.com/84306838/123250065-3cc0c900-d51c-11eb-9368-b5803d339b60.GIF)

**Platform**
-All browsers/mobile devices

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Something regressed in 4.52.0 here as this works in 4.51.0 we should fix this. Must be something in the recent may history
https://github.com/infor-design/enterprise/commits/main/src/components/datagrid/datagrid.js

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.53.0-dev.

https://main-enterprise.demo.design.infor.com/components/datagrid/example-colspan.html

Also checked the other examples and so far I'm not encountering the issue.

Moving this ticket to Done.

Thanks!
