### ISSUE TITLE
Treemap: New theme makes the text bigger

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5365]
**Describe the bug**
New theme makes the text bigger

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/treemap/example-stats.html
2. See error

**Expected behavior**
Text should be responsive and rendered properly

**Version**
v4.53.0-dev

**Screenshots**
<img width="852" alt="Screen Shot 2021-06-28 at 7 36 00 PM" src="https://user-images.githubusercontent.com/84306838/123630493-2e3e1e80-d848-11eb-9205-3a798545b4d4.png">

**Platform**
-All browsers/mobile devices

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Seems to be an issue only in "new theme" since the text is much bigger.

**Comment by nganotice** [comment]
Updated the issue @tmcconechy. Thanks!

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.57.0-beta.

**New Theme**
<img width="834" alt="Screen Shot 2021-11-04 at 1 53 33 PM" src="https://user-images.githubusercontent.com/84306838/140418448-a8d79669-3113-43ab-ac7d-fcae5832c867.png">

**Classic Theme**
<img width="832" alt="Screen Shot 2021-11-04 at 1 53 55 PM" src="https://user-images.githubusercontent.com/84306838/140418426-6f5d5abb-bd02-4808-85e4-a1cfaf1d6f91.png">

Moving this ticket to Done.

Thanks!
