### ISSUE TITLE
Datepicker/Monthview: Design Enhancements

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5373]
**Is your feature request related to a problem or use case? Please describe.**
Design flagged some things they would like changed..

**Describe the solution you'd like**

- [ ]  Field filter on left side is removed. (equals, in range, etc.)
- [ ] Clear and Apply actions are removed. The user can clear the field manually and teams include an X icon inside the field if that functionality is needed. (not sure that we can do this)
- [ ] Add swiping to change months
- [ ] Popover by default is flush left with field but can be changed.
- [ ] azure and slate circles are 2 instead of 1. One did not pass any form of accessibility

 In month/year switcher: 
- [ ]  ‘Apply’ is available in cases users might not think to use the  dropdown again.
- [ ]   Top right action toolbar goes away
- [ ]  Vertical chevrons added to 
- [ ]  Change “Today” action to 16px bold
- [ ]   Hover is azure 2

**Describe alternatives you've considered**
Do the above, except think about the button change

**Additional context**
See designs - complete the medium ones as per https://www.figma.com/file/y1oT4NPGJA78EzUNssZYsG/IDS-Calendar?node-id=1%3A2269&viewport=-288%2C2528%2C0.32999536395072937

**Comment by anton-kurilov** [comment]
Will these enhancements be for:
https://main-enterprise.demo.design.infor.com/components/monthview 
or 
https://main-enterprise.demo.design.infor.com/components/datepicker

or Both?

**Comment by tmcconechy** [comment]
Some would flow threw on both (like the colors). Some would just be on datepicker
