### ISSUE TITLE
Component Rename — Process to Progress

### ISSUE THREAD

**Issue by katieinfor** [infor-design/enterprise#5376]
**Is your feature request related to a problem or use case? Please describe.**
Original Component Name
Process Indicator [[Link](https://design.infor.com/product/components/process-indicator)]
 
New Component Name
Progress Indicator

**Describe the solution you'd like**
We will have to update:

product & component pages on design.infor.com 
component pages on the demo site
references in the code

**Describe alternatives you've considered**
N/A
**Additional context**
Jira Ticket: https://jira.infor.com/browse/UXD-2805

**Comment by tmcconechy** [comment]
This would be a breaking change so would need to do this on a major release or revist or versioning rules.
Might need a call for this

**Comment by tmcconechy** [comment]
Not sure if this will work as we have similar names

https://main-enterprise.demo.design.infor.com/components/progress/list
https://main-enterprise.demo.design.infor.com/components/processindicator/list

So we already have conflicting names. So maybe 

- process chart?
- progress indicator?

**Comment by tmcconechy** [comment]
Closing for now - as it has the proper name / descoping
