### ISSUE TITLE
BlockGrid: Selection State improvements

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5379]
**Describe the bug**
Design would like to add a more consistent selection treatment to the block grid. See https://www.figma.com/file/aYCxzzldd3MvFsvQ4l563E/Multiselect?version-id=950414926&node-id=0%3A1&viewport=-495%2C564%2C0.522594690322876

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/blockgrid/example-multiselect.html

**Expected behavior**
Should update the mutiselect design to the new specs.

**Additional context**
Also update the Web component version with the same design

**Comment by jbrcna** [comment]
QA Passed
v4.54.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/blockgrid/example-multiselect-text.html
![image](https://user-images.githubusercontent.com/56722184/126605422-14ab4893-9d47-4305-a751-f69ca019b08f.png)
