### ISSUE TITLE
Datagrid: With showDirty displaying row dirty when dropdown value hasn't changed

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#538]
A row's status is showing the dirty flag, when a cell has a dropdown and the user selects the same value from the dropdown.  Landmark issue, since the column.field property will be set to something like "fields.ReasonType.value".  So within the updateCellNode function, the code for getting the oldVal needs to be changed.

**Expected behavior**
Dirty flag is not set when the user opens the dropdown and selects the current value from the drop-down list.
![withfix](https://user-images.githubusercontent.com/39804038/43530913-451eaa80-9574-11e8-8b96-1102acecf0ae.gif)
![withoutfix](https://user-images.githubusercontent.com/39804038/43530914-452ab2bc-9574-11e8-9d53-bc99c71d31e3.gif)

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
Made the following change to the method updateCellNode() within datagrid.js
```
    // const oldVal = (col.field ? rowData[col.field] : '');
    let oldVal = '';
    if (col.field) {
      if (col.field.indexOf('.') > -1) {
        var parts = col.field.split('.');
        if (parts.length === 2) {
          oldVal = rowData[parts[0]][parts[1]];
        }

        if (parts.length === 3) {
          oldVal = rowData[parts[0]][parts[1]][parts[2]];
        }
      } else {
        oldVal = rowData[col.field];
      }
    }

```

**Comment by tmcconechy** [comment]
This relates to https://github.com/infor-design/enterprise/issues/477
