### ISSUE TITLE
Icons: Requesting New icon for Basket

### ISSUE THREAD

**Issue by GRAMIK0** [infor-design/enterprise#5381]
Background
It is important to visualize a shopping basket in a sales application with the right icon. A basket is a basket and a cart is a cart.
Right now there is an icon for a Cart (Shopping Cart) in IDS. See "Screenshot 1" below.
In application Infor Sales Hub we are using the wording MY BASKET together with existing icon for a cart (See "Screenshot-3" below). We want to continue calling is a basket (Shopping basket). The word "Basket" doesn't match the cart icon and that's why we want an icon for a basket. 

Requirement
There is no icon available for a Basket (Shopping Basket). 
The requirement is to also have an icon for a basket. See "Screenshot 2" for an example of an Shopping Basket. 

Screenshot 1 from IDS - Cart:
![image](https://user-images.githubusercontent.com/86775671/124104905-037be200-da63-11eb-9dc2-7e28a9fb935e.png)

Screenshot 2 - Basket:
![image](https://user-images.githubusercontent.com/86775671/124105188-46d65080-da63-11eb-8fb0-a2365f69287f.png)

Screenshot-3 - From application Infor Sales Hub:
![image](https://user-images.githubusercontent.com/86775671/124139027-81ea7b00-da87-11eb-99f1-c58b45d8d038.png)

**Comment by tmcconechy** [comment]
@GRAMIK0 Can you explain the use case? Why can't a cart be used?

**Comment by tmcconechy** [comment]
Descoping this for now

**Comment by tmcconechy** [comment]
@GRAMIK0 We can add this but for design they use Jira so please make a jira https://jira.infor.com/browse/UXD and when its done we can use this ticket to add to the code.

This one didnt make this release due to that. Sorry

**Comment by tmcconechy** [comment]
Please add the request on https://jira.infor.com/browse/UXD for the basket icon. Once made by design we will add it.

**Comment by tmcconechy** [comment]
Related Jira https://jira.infor.com/browse/UXD-3682
