### ISSUE TITLE
Bar Chart: Add axis labels for bar chart

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#5382]
**Describe the bug**
We are using in bar chart in widget and we want to add axis labels for it but there is no provision to add it. We need to have this feature for bar chart that exists in line chart https://main-enterprise.demo.design.infor.com/components/line/example-axis-labels.html

**Expected behavior**
We need to add axis labels for bar chart. 

**Version**
- ids-enterprise: [e.g. v.4.52.0]

**Screenshots**
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/42198413/124132980-fed51f00-da9e-11eb-9d4c-bf7e47e89ae0.png)

**Platform**
 - Infor Application/Team Name: Infor GRC
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
I know you want this feature but just putting this out that while waiting you could use the line chart as well as maybe manually adding a text label to the DOM as a workaround

**Comment by dhumalkishor** [comment]
Hi Tim,

Looking at the data which we are showing in this chart (Bar Chart), We can't use line chart.

Regards,
Kishor

**Comment by tmcconechy** [comment]
Yes, But just mentioning it does work there if you need a quick solution. I find the line and bar chart to be relatively interchangeable for data

**Comment by dhumalkishor** [comment]
Hi Tim,

Can you please update when we can expect fix for this JT.

Regards,
Kishor

**Comment by tmcconechy** [comment]
Put this in for next sprint planning

**Comment by tmcconechy** [comment]
cc @kevinwhitedesign

**Comment by jbrcna** [comment]
QA Passed. v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/bar/example-axis-labels.html
<img width="930" alt="image" src="https://user-images.githubusercontent.com/56722184/170617984-39de1145-d836-4fb8-a3c8-030c8e4d5b94.png">
https://main-enterprise.demo.design.infor.com/components/bar/example-axis-labels.html?theme=new&mode=light&locale=ar-EG
<img width="966" alt="image" src="https://user-images.githubusercontent.com/56722184/170618533-59bc60c2-4af7-4896-91a9-4b35204b3ba6.png">
