### ISSUE TITLE
Datagrid: Request for radio button support in Datagrid

### ISSUE THREAD

**Issue by bveerabathini** [infor-design/enterprise#5384]
Infor Design team asked us to implement Radio buttons in place of selectionCheckbox in datagrid.

**Describe the solution you'd like**
For single selection we have checkboxes instead of that we require Radio buttons.

**Additional context**
![image](https://user-images.githubusercontent.com/85981034/124134748-c59dae80-daa0-11eb-8d9f-5b176f8f9edb.png)
Infor LN

**Comment by tmcconechy** [comment]
For single select we simply do not show checkboxes. https://main-enterprise.demo.design.infor.com/components/datagrid/example-singleselect.html

This is the design and i dont see any reason for adding radio buttons...

**Comment by bveerabathini** [comment]
Hi Tim,
Our Datagrid has Soho.Formatters.SelectionCheckbox formatter with single selection, so the expectation is to see the Radio button. Same was even recommended by Rogel Ragadio from IDT team.

**Comment by tmcconechy** [comment]
As of now the selected state for single select is

![Screen Shot 2021-07-02 at 9 14 56 AM](https://user-images.githubusercontent.com/814283/124280301-8742d680-db16-11eb-8b6e-d88e27036e89.png)

Can see it in this example https://main-enterprise.demo.design.infor.com/components/datagrid/example-singleselect.html

When you come back just call the selectRow() api and set the state of selected rows from before. We could try to add a radio column formatter at some point but this may take a long while and could be a bit of work when the use case is actually already covered.

**Comment by janahintal** [comment]
This is now working as expected. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/130228453-ee793880-7c0b-4f1f-af60-ce3ec3527e46.png)
![image](https://user-images.githubusercontent.com/45757016/130228470-ae4595a1-150d-40fb-b715-79c047a39f22.png)
