### ISSUE TITLE
Datagrid: Retaining rows even though keyword search is empty

### ISSUE THREAD

**Issue by bveerabathini** [infor-design/enterprise#5385]
**Describe the bug**
We have a listview with 2 list items. On click of each list item we need to show data according the listview item in datagrid.
Here we have single datagrid but dataset changes according to listview item click.
When searched with some text in keyword search it filters the rows when clicked on other listview item and then back to the previous listview item , the datagrid retains filtered rows with empty keyword search.
If we goto keyword search and just hit enter it will load whole dataset.

**To Reproduce**
Please find below url for the code in stackblitz  ,
https://stackblitz.com/edit/ids-quick-start-940-jbvjaf 

1. Click on Lookup button --> opens Dialog(WIth Financial Company listview item selected with datagrid)
2. give 170 in keyword search--> it filters the rows
3.Click on Sales Office listview item --> then click back to  Financial Company listview item
4. Now you can see the datagrid having row with data related to 170(Financial Company) but Keyword search is empty.
5. If we goto keyword search and just hit enter it will load whole dataset.

**Expected behavior**
In this case , as keyword search is empty, Datagrid should show full dataset. 

**Version**
IDS Enterprise 4.36.1

**Screenshots**
![image](https://user-images.githubusercontent.com/85981034/124137582-7147fe00-daa3-11eb-9512-063bd50dcf74.png)
![image](https://user-images.githubusercontent.com/85981034/124137636-7efd8380-daa3-11eb-98f8-8a57570b4f17.png)

**Platform**
 - Infor Application/Team Name: Infor LN
 - OS Version:Windows 10
 - Browser Name:  chrome
 - Browser Version: Version 91.0.4472.124 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
I think we talked about this before. The problem is that when the grid is filtered. It marks the data with _isFilteredOut
And you are not reseting the grid array so its the same one as before. What you could do is apply the original array or you could clear out the `_isFilteredOut` fields.

See This example for a fix:
https://stackblitz.com/edit/ids-quick-start-940-qebddg?file=src%2Fapp%2Flocation.dialog.ts

I added this...
```
  populateDataset(dataset: any[], field: string): void {
    this.columns = [
      {
        id: 'selectionCheckbox',
        sortable: false,
        resizable: true,
        width: 20,
        formatter: Soho.Formatters.SelectionCheckbox,
        align: 'center'
      },
      {
        name: 'code',
        id: field,
        field: field
      },
      {
        name: 'description',
        id: 'description',
        field: 'description'
      }
    ];
    delete dataset[0]._isFilteredOut;
    delete dataset[1]._isFilteredOut;
    delete dataset[2]._isFilteredOut;

    this.gridOptions = {
      columns: this.columns,
      dataset: dataset,
      selectable: 'single'
    };
```

this was just a quick hacky way but you could use a loop and do it or reset your array to the original.
