### ISSUE TITLE
Datagrid: Request for Custom text in Keyword Search placeholder of Datagrid

### ISSUE THREAD

**Issue by bveerabathini** [infor-design/enterprise#5386]
**Is your feature request related to a problem or use case? Please describe.**
Infor Design recommended this custom text in  Keywordsearch placeholder of Datagrid

**Describe the solution you'd like**
Need to give custom text in place of keyword(placeholder) of Keywordsearch of datagrid.

**Additional context**
![image](https://user-images.githubusercontent.com/85981034/124139464-42328c00-daa5-11eb-976d-2febef58be47.png)
Infor LN

**Comment by tmcconechy** [comment]
How do we reproduce this? I think what you need to do is make your own toolbar. See this example:
https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar.html

Basically by putting in your own markup you can add the placeholder.

**Comment by tmcconechy** [comment]
Descopint this as im not able to reproduce

**Comment by bveerabathini** [comment]
Hi Tim,
Basically I am giving custom toolbar like this to Datagrid,
this.toolbar = { collapsibleFilter:  false , keywordFilter: true, actions: false, filterRow: { clearFilter: true } }
and toolbar is of type **SohoToolbarOptions**.
I couldn't find any option/attribute to set custom text in placeholder of toolbar.
Could you please suggest any option to set custom text in this toolbar.
