### ISSUE TITLE
Modal: Add setting for modal's close button to set tooltip content and be able to add new attributes

### ISSUE THREAD

**Issue by ssaniel** [infor-design/enterprise#5391]
**Is your feature request related to a problem or use case? Please describe.**
We're making changes to the modal to improve the user experience. This is related to https://github.com/infor-design/enterprise/issues/5358. For this particular ticket, we'd like to request to add settings for modal's close button. 
We'd like to set the tooltip content and add new attributes like tabIndex = -1. 

**Describe the solution you'd like**
Currently, we make the closeButton visible by setting it in the SohoModalOptions like this..

.modal(LMCompactFormDialogComponent, placeholder, {fullsize: 'responsive', showCloseBtn: true})

is it possible to add something like this so we can set the tooltip content and add new attributes?

closeBtnOptions: {
  tooltipContent: 'Close Modal. Esc key can also be used.'
  attributes: [ { name: 'tabIndex', value: -1 } ]  \\OR tabIndex: -1
}

**Describe alternatives you've considered**
was able to add new attributes in the closeButton on LMClient side but I cannot change the tooltip content.

**Additional context**
![image](https://user-images.githubusercontent.com/78124324/124451458-fbe87000-ddb7-11eb-9cf7-429d22761d5c.png)

And what application do you work on? LMCLIENT

**Comment by tmcconechy** [comment]
Can you explain why you would not want the x to be available to the keyboard. This seems incorrect as it means keyboard users cant use the modal to close.

Suggest we dont add this and you find a way to do this manually if you really need it as it doesnt seem like something we would want. Maybe you can use the modal beforeOpen/Open lifecycle events to do this.

**Comment by CindyMercadoReyes** [comment]
BDD attached. 
[story_github5391.docx](https://github.com/infor-design/enterprise/files/6969095/story_github5391.docx)

**Comment by jbrcna** [comment]
working as expected. moving this ticket to Done
v4.55.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/modal/test-custom-tooltip-close-btn.html
![image](https://user-images.githubusercontent.com/56722184/129293620-85e009e3-5b0a-4d34-9b4c-80e9aee32ac8.png)
