### ISSUE TITLE
Datagrid: Cannot resize after expanding the tree with long values

### ISSUE THREAD

**Issue by bempedragosa** [infor-design/enterprise#5392]
**Describe the bug**
Cannot resize the datagrid column after expanding the tree with long values

**Expected behavior**
Column should be resizable

**Version**
ids-enterprise: 4.52.1

**Screenshots**
![Tree_List_Expand_Issue](https://user-images.githubusercontent.com/58026209/124518874-3f73c600-de1a-11eb-8290-df61ba7530d4.gif)

**Platform**
Chrome

**Comment by tmcconechy** [comment]
Can you correct the bug so we can reproduce the issue? Also it seems like you mean datagrid not tree?

From the screen shot i think i've seen this before and its very difficult to solve (might require partial rewrite of datagrid). One thing you can try is taking the column widths off or setting then to numbers as opposed to percent.

**Comment by bemariepedragosa** [comment]
I tried your suggestion but still didn't work. I still can't resize the datagrid columns

**Comment by tmcconechy** [comment]
Ok we are still not able to reproduce this, as you just have a video and no way to run the code see the problem. So let’s start there

**Comment by bemariepedragosa** [comment]
Hi @tmcconechy 

Here are the steps to reproduce the issue:
1. Add this file to app > data 
[app_data.zip](https://github.com/infor-design/enterprise/files/6794796/app_data.zip)
2. Add this file to app > views > components > modal
[app_views_components_modal.zip](https://github.com/infor-design/enterprise/files/6794798/app_views_components_modal.zip)
3. http://localhost:4000/components/modal/example-modal-with-tree-list.html
4. Check the column if resizable
5. Expand the first tree node
6. Check the column again if resizable
