### ISSUE TITLE
Datagrid: grid misalignment in action item column 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5394]
**Describe the bug**
Datagrid: grid misalignment in action item column 

**To Reproduce**

1. Go to https://4530-beta0-enterprise.demo.design.infor.com/components/datagrid/example-list-frozen-columns.html?
2. Edit row height to Extra Small 
3. Hover and click new order button to see the blue focus 
4. Check all row height sizes
5. Also check in classic theme

**Expected behavior**
Focus and grids should be aligned properly

**Version**
Beta 4.530 - IDS

**Screenshots**
XS
![image](https://user-images.githubusercontent.com/45757016/124572863-93fb5d80-de7b-11eb-879f-d105d94cdb00.png)
SMALL 
![image](https://user-images.githubusercontent.com/45757016/124572895-9b226b80-de7b-11eb-894f-9f69a605b760.png)
MEDIUM
![image](https://user-images.githubusercontent.com/45757016/124572798-8514ab00-de7b-11eb-8c10-bc19dd1259e4.png)

**Platform**
All major browsers & devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
One more issue similar to the targeted achievement one

**Comment by vivz753** [comment]
Currently viewing on my branch that fixes #5366

It fixed Medium, but Small and Extra Small still need to be corrected
<img width="1433" alt="Screen Shot 2021-07-14 at 5 44 00 PM" src="https://user-images.githubusercontent.com/22609861/125710513-923145d5-92ce-42a3-b108-af18230e1cc9.png">

On main branch
<img width="1431" alt="Screen Shot 2021-07-14 at 5 43 53 PM" src="https://user-images.githubusercontent.com/22609861/125710507-6f70a1fe-489b-48cc-84b6-dafb0ff018c5.png">
