### ISSUE TITLE
Multiselect: Clear icon in Multiselect (with Tags) not aligned with the states/towns when in compact mode

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5396]
**Describe the bug**
Multiselect: Clear icon in Multiselect (with Tags) not aligned with the states/towns when in compact mode

**To Reproduce**

1. Go to https://4530-beta0-enterprise.demo.design.infor.com/components/multiselect/example-compact.html
2. Click on compact mode
3. See error(clear icon not aligned with the states/towns)

**Expected behavior**
Clear icon should be aligned with the states/towns when in compact mode

**Version**
v4.53.0-beta

**Screenshots**
Chrome/Safari/Edge -same issue w/ mobile devices as well
![3 browsers compact issue](https://user-images.githubusercontent.com/84306838/124582997-294f1f80-de85-11eb-899f-25da1504e0a5.GIF)

Firefox -not aligned even if not in compact mode
![Firefox compact issue](https://user-images.githubusercontent.com/84306838/124583048-34a24b00-de85-11eb-97e4-b4048aa65bb3.GIF)

Additional issue: Clear icon not aligned as well in Firefox - https://4530-beta0-enterprise.demo.design.infor.com/components/multiselect/example-index.html & https://4530-beta0-enterprise.demo.design.infor.com/components/multiselect/example-tags.html
<img width="1514" alt="Screen Shot 2021-07-06 at 6 14 28 PM" src="https://user-images.githubusercontent.com/84306838/124583778-0709d180-de86-11eb-94b7-57e7b722086e.png">

Mobile - iPhone 12 Pro Max
![Screen Shot 2021-07-06 at 5 57 27 PM](https://user-images.githubusercontent.com/84306838/124582268-767ec180-de84-11eb-8f9d-5ac0c6e57579.png)

**Platform**
All browsers/mobile devices

**Additional context**
N/A

**Comment by nganotice** [comment]
Hi @ericangeles,

Just found 1 issue. It's still not centered on Firefox when in compact mode.
![Screen Shot 2021-07-13 at 1 58 56 PM](https://user-images.githubusercontent.com/84306838/125398898-7893d380-e3e2-11eb-9f57-79f4db3b4e9a.png)

Thanks!

**Comment by ericangeles** [comment]
@nganotice are you on mac or windows?

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.54.0-dev.

Chrome/Safari/Edge/Mobile
![Screen Shot 2021-07-13 at 2 30 18 PM](https://user-images.githubusercontent.com/84306838/125402320-da563c80-e3e6-11eb-964e-46b595131db6.png)
![Screen Shot 2021-07-13 at 2 30 46 PM](https://user-images.githubusercontent.com/84306838/125402370-eb9f4900-e3e6-11eb-8b9f-38849b172e6f.png)

Firefox
<img width="651" alt="Screen Shot 2021-07-13 at 2 31 25 PM" src="https://user-images.githubusercontent.com/84306838/125402455-0376cd00-e3e7-11eb-85de-a2dcd781b211.png">
<img width="1510" alt="Screen Shot 2021-07-13 at 2 33 39 PM" src="https://user-images.githubusercontent.com/84306838/125402732-5486c100-e3e7-11eb-89c1-01919bb7c899.png">

**The issue earlier was encountered on my extended monitor**
![Screen Shot 2021-07-13 at 1 58 56 PM](https://user-images.githubusercontent.com/84306838/125398898-7893d380-e3e2-11eb-9f57-79f4db3b4e9a.png)

Moving this ticket to Done.

Thanks!
