### ISSUE TITLE
Modal: No focused element in modal if first field is disabled and has a trigger button

### ISSUE THREAD

**Issue by ssaniel** [infor-design/enterprise#5400]
**Describe the bug**
There is no focused element in the modal if first field is disabled and has a button like lookup, timepicker and datepicker.
I think we also need to set the tabindex of trigger button to -1, current value is 0 even if the input is disabled.

    var focusableElemSelector = ['button:not([disabled]):not([tabindex="-1"])', ...

**To Reproduce**
https://stackblitz.com/edit/ids-enterprise-pbmw8c?file=index.html

Pre-req: First field in the modal should be disabled and has a button like lookup, timepicker and datepicker
1. Open up the modal

**Expected behavior**
First editable field (name) should be focused.

**Actual Behavior**
First editable field  (name)  is not focused.

**Version**
- ids-enterprise: v4.52.1

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 91.0.4472.124

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.54.0-dev.

https://main-enterprise.demo.design.infor.com/components/modal/test-focusable-elements.html
![Modal Focus Fix](https://user-images.githubusercontent.com/84306838/127466446-a0101ab6-d372-4e29-a4f1-9e8bf49433b1.gif)

Moving this ticket to Done.

Thanks!
