### ISSUE TITLE
Datagrid: Delete key on dropdown filter columns only clears the value, but not apply the cleared filter

### ISSUE THREAD

**Issue by kaeleding** [infor-design/enterprise#5402]
**Describe the bug**
Pressing the delete key on filters that are dropdowns only clear the value, but not actually apply the cleared filter. On text filters, you can select all the text then press the delete key and it clears the value and applies the new filter.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-books.html
2. On the Book Currency dropdown, select Test, the grid will update
3. Press the delete key, which should clear the Test value

**Expected behavior**
The grid should update and reflect the cleared filter dropdown value.

**Version**
- ids-enterprise: v.4.54.0-edv

**Additional context**
Discussed with an email with Tim.

**Comment by janahintal** [comment]
Issue still exists in http://localhost:4000/components/datagrid/example-books.html. 

1. Tab to Book Currency
2. Select Test using arrow key 
3. Press Delete 
4. Press Enter 
The dropdown still has the Test value even after deleting.
![image](https://user-images.githubusercontent.com/45757016/129339168-1756da5a-8add-403e-a56c-2ab36b3f28e1.png)

**Comment by yohannahbautista** [comment]
> Issue still exists in http://localhost:4000/components/datagrid/example-books.html.
> 
> 1. Tab to Book Currency
> 2. Select Test using arrow key
> 3. Press Delete
> 4. Press Enter
>    The dropdown still has the Test value even after deleting.
>    ![image](https://user-images.githubusercontent.com/45757016/129339168-1756da5a-8add-403e-a56c-2ab36b3f28e1.png)

@janahintal Hi, can you show a video or gif of how you did it? I can't replicate the bug on my end

**Comment by tmcconechy** [comment]
I also cant reproduce this anymore. Perhaps your looking at an old branch? or try https://main-enterprise.demo.design.infor.com/components/datagrid/example-books.html

**Comment by janahintal** [comment]
Hello, I just recorded a video. I can still reproduce the issue even on https://main-enterprise.demo.design.infor.com/components/datagrid/example-books.html. Thank you. 
https://user-images.githubusercontent.com/45757016/129873894-20857b54-5c2f-49e8-b786-dda567f8939d.mp4

**Comment by janahintal** [comment]
Hello, @tmcconechy @yohannahbautista 
- On the Book Currency dropdown, select Test, the grid will update
- Press the delete key, which should clear the Test value
**Is working as expected. It cleared the value after clicking "delete" key.** 

**Although I've tried other scenario that failed on my end. _Can you confirm if this is an invalid scenario,_ if so, I can now move this to Done. Thank you.**

**Comment by janahintal** [comment]
Hello, @tmcconechy @yohannahbautista 
- On the Book Currency dropdown, select Test, the grid will update
- Press the delete key, which should clear the Test value
**Is now working as expected on my end. It cleared the value after clicking "delete" key.** 

Observation:
_I've tried other scenario that can be for enhancement if valid._
https://user-images.githubusercontent.com/45757016/129879289-7091ec61-b530-48fe-b2f5-e0a8767f6d4d.mp4

**Comment by tmcconechy** [comment]
Ok i see from the case, this isnt really a valid test case because when the dropdown closes Test is selected. Your just clearing the dropdown's filter. So as long as whats in the field matches the grid filter when its the dropdown is closed. I dont think there is anything more to do
