### ISSUE TITLE
Buttons: Mobile Enhancements

### ISSUE THREAD

**Issue by katieinfor** [infor-design/enterprise#5409]
**Is your feature request related to a problem or use case? Please describe.**
Design made improvements for mobile see file for adjustments. Make this changes in both Web Components and Enterprise (or just web components?)

**Additional context**
Jira: https://jira.infor.com/browse/UXD-2770 
Individual Component Link: https://www.figma.com/file/VcRDGPFqlp3MJ46mEWkGPf/Buttons?node-id=0%3A1

**Comment by tmcconechy** [comment]
We will have to test the impact of this on as its possibly going to cause UI regressions or move things around. See if we can add the hitboxes in a way that doesnt effect positioning and size and doesnt overlap.

**Comment by tmcconechy** [comment]
duplicate of https://github.com/infor-design/enterprise/issues/5568
