### ISSUE TITLE
LoadingIndicator: Mobile Loading / Progress Indication

### ISSUE THREAD

**Issue by ghost** [infor-design/enterprise#5411]
**Is your feature request related to a problem or use case? Please describe.**
Design, we should explore how our loaders/progress indicators work on mobile. When a user swipes down to refresh, what is the appropriate loading component to show them?

Changes for Dev
- Adjust sizes on mobile
- Add swipe down animation/example

**Describe the solution you'd like**
Implement the proposed designs

**Describe alternatives you've considered**
N/A 

**Additional context**
Link to figma component: https://www.figma.com/file/PwwLkUtTxpxLzRJzm5kACM/IDS-Loader?node-id=823%3A3143&viewport=1015%2C454%2C0.12414686381816864
Jira Ticket: https://jira.infor.com/browse/UXD-2653

**Comment by tmcconechy** [comment]
@katieinfor i think this is the wrong design or this needs hand off. As i dont see any mobile specific changes and this is showing the design thats already implemented in progress

**Comment by tmcconechy** [comment]
Closing this as not sure what to do at this time.
