### ISSUE TITLE
Dropdown: Setting the property noSearch to true does not disable the input field

### ISSUE THREAD

**Issue by kaeleding** [infor-design/enterprise#5419]
**Describe the bug**
In 4.11, dropdowns that have the property noSearch set to true adds the disabled attribute to input fields.

In the latest version however, this is now gone.

Would like to know if this was an intentional change or not.

You can check the demo (and see the steps to reproduce) for 4.11 here: https://jsfiddle.net/n3voc764

Notice it disabled the input field and you can't type on it.

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/dropdown/example-no-search.html
2. Click on the dropdown
3. Try to type on the input field

**Expected behavior**
Based from the version we're upgrading from, 4.11, it _should_ be disabled

**Version**
- ids-enterprise: 4.51-dev

**Platform**
 - Infor Application/Team Name: Lawson
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 91.0.4472.124 (Official Build) (64-bit)

**Additional context**
The code that adds the disabled attribute to input fields can be found in the function `handleSearchEvents()`

Looks like it was removed in 4.34.

**Comment by tmcconechy** [comment]
By request we added the ability to filter in the no-search dropdown. However, in 4.53.0 we added a setting around this see https://github.com/infor-design/enterprise/issues/5159

For an example see https://4530-beta0-enterprise.demo.design.infor.com/components/dropdown/example-no-search-lsf.html

See instructions for testing this on https://github.com/infor-design/enterprise/pull/5369

**Comment by tmcconechy** [comment]
cc @EdwardCoyle in case he has anything to add on what i put
