### ISSUE TITLE
Homepages: Charts looks off in Mobile Devices

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5425]
**Describe the bug**
Homepages: Charts looks off in Mobile Devices

**To Reproduce**

1. Open Mobile Browser
2. Go to https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html?theme=classic&mode=contrast&colors=133c59

**Expected behavior**
Charts should not look cut off and should fit the screen. 

**Version**
IDS - 4.54 - dev

**Screenshots**
Iphone 12 Pro Max
![image](https://user-images.githubusercontent.com/45757016/125610365-1e1d8518-efcd-43c9-a756-9bbec4ca64ef.png)

Iphone 12 Mini
![image](https://user-images.githubusercontent.com/45757016/125610469-f65a6322-4c19-434f-bd2a-1380cc858eb9.png)

**Platform**
iOS & Android Devices 
Latest OS 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Probably just some specific size. I think we have spent enough time on this page for now

**Comment by janahintal** [comment]
Working well in chome mobile simulator. 
Verified in http://localhost:4000/components/homepage/example-hero-widget.html?theme=classic&mode=dark&colors=133c59
![image](https://user-images.githubusercontent.com/45757016/128168846-699cae72-d9d8-4df7-a285-dfa62e789307.png)
![image](https://user-images.githubusercontent.com/45757016/128168921-6d15d378-c87b-42c0-bfa4-14aad75bdf64.png)

Will move to done once the changes reflects to https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html?theme=classic&mode=contrast&colors=133c59
![image](https://user-images.githubusercontent.com/45757016/128169206-3c2f1dcf-0797-48c1-8449-5c9df572407f.png)

Thank you

**Comment by janahintal** [comment]
The issue still exist in lower model of iPhone devices & in Android devices. 
iPhone XR:
![image](https://user-images.githubusercontent.com/45757016/128340410-e4fb63ae-02a7-43c8-80a3-d87fb44a4927.png)

Samsung s20:
![image](https://user-images.githubusercontent.com/45757016/128340509-a37b25a3-3b0f-46d7-b440-52b52aba4ab9.png)

Samsung S21:
![image](https://user-images.githubusercontent.com/45757016/128340857-c4103b23-46a8-4881-ab8f-2e80e396cc0f.png)
