### ISSUE TITLE
update cells value on datagrid rows

### ISSUE THREAD

**Issue by AsafMeirBarziv** [infor-design/enterprise#5426]
How can I iterate on the rows and update cell values based on some other cell values?
Can't find any getAllRows() method.....

**Comment by tmcconechy** [comment]
Remember to use Ms Teams for general questions 

https://teams.microsoft.com/l/team/19%3a2b0c9ce520b0481a9ce115f0ca4a326f%40thread.skype/conversations?groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&tenantId=457d5685-0467-4d05-b23b-8f817adda47c

I think for this use case what you want to do is just loop the dataset.. `grid.settings.dataset` it wall have all the cell values
