### ISSUE TITLE
Datagrid title vulnerability to xss

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise#5428]
**Describe the bug**
When column definition of datagrid contains code, datagrid will execute such code.

**To Reproduce**

1. Change column definition in any datagrid to have name such as `<img src=x onerror=alert('kocicka')>test`
2. Open editted datagrid in the browser
2. See error

**Expected behavior**
Any malicious code should be sanitized and not executed

**Version**

- ids-enterprise: 9.5.x

**Comment by tmcconechy** [comment]
Try and use the xssUtils on this.

**Comment by Fruko** [comment]
Hi @tmcconechy  that's what we did actually, but I think it should be something that grid does automatically like it does for cells

**Comment by tmcconechy** [comment]
Hi @Fruko yes sorry, that comment was for @davidcarlsonberg when he looks at addressing this

**Comment by jbrcna** [comment]
this issue is now resolved. moving this ticket to done
 v4.55.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-xss-prevention.html
