### ISSUE TITLE
Popupmenu assume all sections are the same

### ISSUE THREAD

**Issue by AnaLauraMartinez** [infor-design/enterprise#5432]
**Describe the bug**
When you use a popup-menu you can indicate if it is single or multiple selection as well as if it is check or not. IF you have 3 sections one multiple selection, one single selection and one without checkbox you can't do that. The moment you specify is-check in one section, this applies to all the sections regardless.

**To Reproduce**

1. have 3 separators in a popup-menu. Each section will have items.
2. try to make one multi-selection, another one single selection with is-check and the third to not have is-check

When isMultiSelectable all the sections are multi selection. 
 
![image](https://user-images.githubusercontent.com/17933529/125955205-32024834-7bd6-4bb8-b576-2ca804f829bf.png)

```
`button soho-menu-button icon="pie-chart" [disabled]="isDisabled" pie-chart="" menu="charts-menu"
            (selected)="onSelected($event)"
            (beforeopen)="onBeforeOpen($event)"
            (close)="onClose($event)"
            (open)="onOpen($event)"></button>
    <ul soho-popupmenu id="charts-menu" [isMultiselectable]="true">
      <li class= "heading">Section 1</li>
      <li soho-popupmenu-item ><a soho-popupmenu-label>Pie Chart</a></li>
      <li soho-popupmenu-item ><a soho-popupmenu-label>Line Chart</a></li>
      <li soho-popupmenu-item ><a soho-popupmenu-label>Bubble Chart</a></li>
      <li soho-popupmenu-item *ngIf="showLastOption"><a soho-popupmenu-label (click)="showLastOption = !showLastOption">Click this to remove myself</a></li>
      <li soho-popupmenu-separator singleSelectableSection></li>
      <li class= "heading">Section 2</li>
      <li soho-popupmenu-item [isChecked]="true"><a>A 1</a></li>
      <li soho-popupmenu-item ><a>A 2</a></li>
      <li soho-popupmenu-item ><a>A 3</a></li>
      <li soho-popupmenu-separator></li>
      <li class= "heading">Section 3</li>
      <li soho-popupmenu-item><a>Reset Filter</a></li>
    </ul>
```

If multiSelectableSection is used this is ignored completely and the section is the same as the one above. Also If a is-check is used in one of the items all the items in all sections are assumed the same.

![image](https://user-images.githubusercontent.com/17933529/125954814-f2332e6e-3dcb-4ae3-aa6c-17587fa18582.png)

```
<button soho-menu-button icon="pie-chart" [disabled]="isDisabled" pie-chart="" menu="charts-menu"
            (selected)="onSelected($event)"
            (beforeopen)="onBeforeOpen($event)"
            (close)="onClose($event)"
            (open)="onOpen($event)"></button>
    <ul soho-popupmenu id="charts-menu">
      <li soho-popupmenu-separator singleSelectableSection></li>
      <li class= "heading">Section 1</li>
      <li soho-popupmenu-item ><a soho-popupmenu-label>Pie Chart</a></li>
      <li soho-popupmenu-item ><a soho-popupmenu-label>Line Chart</a></li>
      <li soho-popupmenu-item ><a soho-popupmenu-label>Bubble Chart</a></li>
      <li soho-popupmenu-item *ngIf="showLastOption"><a soho-popupmenu-label (click)="showLastOption = !showLastOption">Click this to remove myself</a></li>
      <li soho-popupmenu-separator multiSelectableSection></li>
      <li class= "heading">Section 2</li>
      <li soho-popupmenu-item [isChecked]="true"><a>A 1</a></li>
      <li soho-popupmenu-item ><a>A 2</a></li>
      <li soho-popupmenu-item ><a>A 3</a></li>
      <li soho-popupmenu-separator></li>
      <li class= "heading">Section 3</li>
      <li soho-popupmenu-item><a>Reset Filter</a></li>
    </ul>
```    

**Expected behavior**
Each section will follow the attributes set, the first will allow multi-selection, the second section will have checkboxes but only select one and the third section will not have a checkbox.

![image](https://user-images.githubusercontent.com/17933529/125953523-2a6219ff-a186-466d-be39-a3e92a060458.png)

**Version**
v9.3.1

**Comment by tmcconechy** [comment]
I dont think we can look at this given the information. Can you please add a reduced test case? Also can you specify what you actually want to achieve as your showing several cases and we probably dont have the bandwidth  to look at them all

**Comment by tmcconechy** [comment]
We have more examples like this..

https://main-enterprise.demo.design.infor.com/components/popupmenu/example-partially-selectable
Source:    https://github.com/infor-design/enterprise/blob/main/app/views/components/popupmenu/example-partially-selectable.html

Does that make this a non-issue?

**Comment by AnaLauraMartinez** [comment]
I modified the menu-button.demo.html in the ids demo source as follow
``

**Comment by AnaLauraMartinez** [comment]
Updated the issue with code examples and screen shots.

**Comment by tmcconechy** [comment]
So those examples dont work i just posted?

https://main-enterprise.demo.design.infor.com/components/popupmenu/example-partially-selectable
Source: https://github.com/infor-design/enterprise/blob/main/app/views/components/popupmenu/example-partially-selectable.html

Seems like if you follow that you should be able to do this.

**Comment by tmcconechy** [comment]
Just so this is easier for me to follow.

1. They want a menu this way but cant seem to make this order work

```
Multi Select Section
  Option a
  Option b
  Option c
Single Select Section
  Option a
  Option b
  Option c
Single Item
```

2. Would like to see this in Angular

**Comment by tmcconechy** [comment]
Closing this in fvaor of https://github.com/infor-design/enterprise-ng/issues/1082
