### ISSUE TITLE
Calendar: Month” dropdown is overlapping with “Today” on mobile 

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#5438]
**Describe the bug**
Month” dropdown is overlapping with “Today” on mobile 

**To Reproduce**

1. Go to 'url: https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Noticed that “Month” dropdown is overlapping with “Today” on mobile & responsive view below 385x780
4. Please see screen shots attached. 
5. Please reference ticket: https://github.com/infor-design/enterprise/issues/5245

**Expected behavior**
The Month” dropdown  should not be overlapping with “Today” on mobile & responsive view below 385x780

**Version**

- ids-enterprise: [v4.54]

**Screenshots**
![Iphone Image 2](https://user-images.githubusercontent.com/39101346/126187361-33ce9d0c-3955-46fa-9e94-0880ebea7d54.png)
![Iphone Image 1](https://user-images.githubusercontent.com/39101346/126187362-568bcf9a-246d-4459-80a6-7e6dfa21762e.png)

**Platform**
 - Device: (if applicable) [e.g. iPhone 12 and all older versions]

**Additional context**
None

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.55.0-dev.

https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html

**Responsive View:** 320x568(same size w/ iphone 5)
<img width="356" alt="Screen Shot 2021-08-25 at 3 45 40 PM" src="https://user-images.githubusercontent.com/84306838/130748801-d4fa5594-4ac0-4bda-a148-a6899da2929a.png">

**iPhone 12:** browserstack
<img width="436" alt="Screen Shot 2021-08-25 at 3 46 23 PM" src="https://user-images.githubusercontent.com/84306838/130748908-9af193f6-619f-4dcb-933b-19591f0b397b.png">

Moving this ticket to Done.

Thanks!
