### ISSUE TITLE
Charts: Missing automation id entry points

### ISSUE THREAD

**Issue by tfavorite** [infor-design/enterprise#5441]
**Describe the bug**
There is no way of adding in automation IDs for chart labels or legend labels when using the charting components, which makes them more challenging to test.

**Expected behavior**
The presence for automation ids for any testable surfaces in a component.

**Version**
4.53.2

**Platform**
 - Infor Application/Team Name: Nexus

**Additional context**
Per @tmcconechy, it's possible to work around the missing entry points by using something like `#root-id .chart-donut-text`.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
