### ISSUE TITLE
Datagrid: Fallback Image when image can not be loaded

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise#5442]
We would like to show a fallback image in case the image url provided to the datagrid image column doesn't load successfully.

**Describe alternatives you've considered**
```
(Soho.Formatters as any).ImageUnavailableFallbackCustomFormatter = (
      row: number,
      cell: any,
      value: any,
      column: SohoDataGridColumn,
      item: any,
      api: SohoDataGridStatic
    ) => {
     return `<img src="`+
      'http://stackoverflow.com/does-not-exist.png' +
      `" onerror="console.log('errror'); this.src='https://cdn.sstatic.net/Img/unified/sprites.svg?v=e5e58ae7df45'"
       alt="" width="35" height="35">`
    };
    
```

 But onerror is removed by IDS for Security concerns (related to XSS attacks).

I referred to this answer for fallback image solution. https://stackoverflow.com/a/7995298

**Additional context**
Infor PIM

**Comment by bbmuni** [comment]
@tmcconechy   Please prioritize this ticket as we have  issue reported by customer related to this functionality

**Comment by tmcconechy** [comment]
@ericangeles for the design we should use the placeholder images / icons here similar to this https://main-enterprise.demo.design.infor.com/components/images/example-index.html

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.57.0-beta.

https://4570-beta0-enterprise.demo.design.infor.com/components/treemap/example-stats.html?theme=new&mode=light
<img width="1261" alt="Screen Shot 2021-11-04 at 2 16 22 PM" src="https://user-images.githubusercontent.com/84306838/140421362-8b1b7afb-c4eb-4ea3-b4bc-a2e4a9e37a52.png">

Moving this ticket to Done.

Thanks!

**Comment by tmcconechy** [comment]
Testing with @hemantg05 if you use add row or re-render then this fails to work. Pushing a new easy fix

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.61.0-beta.
https://4610-beta0-enterprise.demo.design.infor.com/components/datagrid/test-images-error.html
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/56722184/157383686-e2b73c9a-2bc2-40a8-ba69-b1271cb025ac.png">
