### ISSUE TITLE
Message: Increasing the maximum width of the text message is not effective in the Messages

### ISSUE THREAD

**Issue by ramya-renjarla** [infor-design/enterprise#5443]
**Describe the bug**
The text message of ids card component does not expand with respect to the title length for 'Message'.

**To Reproduce**
1. Go to 'Message' component
2. Increase the 'title' length
3. Verify the text message is not adjusted w.r.t title length

**Expected behavior**
When the length of title is increased, the text message in the modal should be responsive w.r.t the modal at a minimum threshold.

**Version**
- ids-enterprise-ng: [v4.53.2]

**Screenshots**
![image](https://user-images.githubusercontent.com/87714971/126361751-e92cfb61-0afe-4e20-bb87-5963c4b12817.png)

**Platform**
 - Device : iPad Air 4
 - OS Version : v14.1
 - Browser : chrome, safari, stock browser]
 - Browser Version : Version 91.0.4472.77 (Official Build) (64-bit)

**Additional context**
unable to increase the width of text message.
https://github.com/infor-design/enterprise/blob/main/app/views/components/message/example-index.html

**Comment by tmcconechy** [comment]
@ramya-renjarla the message is a fixed size but if you want to make the width bigger you can set this option https://github.com/infor-design/enterprise/blob/main/src/components/message/message.js#L20

**Comment by ptomanek-infor** [comment]
@tmcconechy  Is it still not a bug? The default width is set to auto you could assume it will either keep growing or have max width. However it should be the same for both content and title. Its really weird when long title cause increase in dialog width but content will remain stuck at original size. Thats not something you would imagine under "auto" setting.

**Comment by tmcconechy** [comment]
Yeah i guess we could try to adjust that text area as a bug. But if that helps please use the workaround i gave

**Comment by davidcarlsonberg** [comment]
I've put up a fix but wondering what should be the default behavior here. Should the modal always expand to it's max-width, letting the message or title determine how wide up until that point?

**Comment by davidcarlsonberg** [comment]
I agree, I don't think there's actually a use case for this bug. If the title is truncated anyway, there would never be an occurrence where the text would force the modal to go too wide. It seems maybe this was tested in the browser and not in as an actual code test case?

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to done. thanks
v4.55.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/message/test-long-title.html
![image](https://user-images.githubusercontent.com/56722184/130229355-31c8907d-576f-4381-a6f3-abb645fbeca8.png)
