### ISSUE TITLE
Locale: Date and timestamp format issues

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#5447]
**Describe the bug**
When using Soho.Locale.calendar().dateFormat the date format string returned has some issues with some languages:
~~- The Date format for SK(Slovak), SL(Slovenian), and HU(Hungarian) locale has spaces between them,~~
~~-- for ex. "21. 1. 2019" (d. M. yyyy) should have no spaces "21.1.2019" (d.M.yyyy)~~
~~- the timestamp format in DA(Danish) Locale uses period (.) instead of colon (:) as a separator~~ 
~~-- for ex. 09.51.51(HH.mm.ss), should be 09:51:51 (HH:mm:ss);~~
- the FI(Finnish) Locale where the timestamp uses period (.) and as a separator for hours and mins and should be using colons(:).
-- for ex. 09.00.03 (H.mm:ss) and should be 09:00:03 (H:mm:ss)

**Expected behavior**
provided the expected behavior in the Describe the bug section

**Version**

- ids-enterprise: 4.52.2

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor Landmark UI
 - Device: (if applicable) NA
 - OS Version: Windows 10
 - Browser Name: Firefox
 - Browser Version: 90.0

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-36368
https://jira.lawson.com/browse/LMCLIENT-36370
https://jira.lawson.com/browse/LMCLIENT-36371

**Comment by tmcconechy** [comment]
Is a native speaker saying these are wrong? Because i got these from the CLDR so they should be correct. For example i know for a fact Slovakia has spaces in the date format https://en.wikipedia.org/wiki/Date_format_by_country

Danish is also showing as dots https://github.com/unicode-org/cldr/blob/master/common/main/da.xml#L1461

Not sure we should change any of these unless 100% justified.

**Comment by JBismonte** [comment]
Ok, Ill clarify with them about the first two issues.

but I can confirm that with Finnish, the timestamp format should be (h.mm.ss) instead of (h.mm:ss).
https://github.com/unicode-org/cldr/blob/3dc49cc0bc72a80e573bc90385feec05af10fc47/common/main/fi.xml#L1633

**Comment by tmcconechy** [comment]
ok yeah that one does seem like a mistake

**Comment by tmcconechy** [comment]
cc @cpinatel7 what do you think about this discrepancy? Is what we have correct?

**Comment by cpinatel7** [comment]
Hi Tim

I'm on PTO today. I'll review these changes tomorrow. 

For example:

https://jira.lawson.com/browse/LMCLIENT-36371 i.e.
The Date format for HU(Hungarian) locale has spaces between them,
-- for ex. "21. 1. 2019" (d. M. yyyy) should have no spaces "21.1.2019" (d.M.yyyy)

LMCLIENT-36371 is not valid. The current format i.e. "yyyy. mm. dd." is correct and should not be changed

**Comment by tmcconechy** [comment]
Yeah that's what i thought. Thanks for confirming when you have the time. Have a nice pto @cpinatel7

**Comment by JBismonte** [comment]
Hi Tim, I confirmed with the reporter that these two issues are no longer valid:
The Date format for SK(Slovak), SL(Slovenian), and HU(Hungarian) locale has spaces between them,
-- for ex. "21. 1. 2019" (d. M. yyyy) should have no spaces "21.1.2019" (d.M.yyyy)
the timestamp format in DA(Danish) Locale uses period (.) instead of colon (:) as a separator
-- for ex. 09.51.51(HH.mm.ss), should be 09:51:51 (HH:mm:ss);

Just need to fix the finnish locale timestamp on this issue

**Comment by cpinatel7** [comment]
![DanishTime](https://user-images.githubusercontent.com/66057969/128314176-64d9c04a-9937-4114-999b-ab6b08535e26.png)
![FinnishTime](https://user-images.githubusercontent.com/66057969/128314179-39699dbc-148f-42a1-b872-3497e8a2fe94.png)

For Danish: Microsoft -> Default time separator is colon. No customization. Danish train timetable also shows colons
For Finnish: Microsoft -> Default time separator is colon. Customization (.) is possible as per the attached screenshot. Finnish train timetable shows colons

**Comment by tmcconechy** [comment]
Ok, the finish locale was previously correct. Thanks @JBismonte @cpinatel7
