### ISSUE TITLE
Gantt Chart - Request for a New IDS Component

### ISSUE THREAD

**Issue by ranga90** [infor-design/enterprise#5452]
**Request for a new component - Gantt Chart**

We do not have a readily available component for UI Development, and this request is to have a component newly developed for the request - and the Jira reference is below:
1. Jira # T2V-1835 - For Gantt Chart dependency.
2. Jira # T2V-1091 - Design Recommendation from Infor Design team.
3. Jira # T2V-1087 - Business requirement (Epic - containing all the sub Jiras)

Attached the Design Recommendation as received from Infor Design Team:
![image](https://user-images.githubusercontent.com/87777400/126738235-33e375f7-0734-4099-8209-69d5f23399f8.png)

Figma link of proposed designs:
https://www.figma.com/file/YZadVbj3bByqT9pFWdJxhi/Gantt-Chart?node-id=1%3A3612
 
 Alternate Design:
 https://www.figma.com/file/YZadVbj3bByqT9pFWdJxhi/Gantt-Chart?node-id=1%3A348
 
Brief about Business requirement:

Expectation is to have a Dock Door Scheduling where User will have visibility of the Warehouse and the related master, and the list of documents that need scheduling onto appropriate Docks.

- Requirement is to have a timeline chart for the user to understand the assignments / documents in place, and also expectation is such that user manually drag-and-drop from the "waiting assignment / documents" to the Gannt Chart. 
- The user would want to be able to drop several assignments together - to do a "what if" scenario" before saving the changes.
-  There should be a warning by validation of Transport Equipment and other special Unloading Equipment required for the Assignment do not match the Dock that is being used for the Assignment; or the date overlaps with another Assignment.

**Functionality to bring over**
- To have a Gantt Chart component to Achieve Time line chart / details.
- To Support Drag and Drop functionality of assignments / documents on to Gantt chart.
- Supports the what-if scenario to be able to help user to understand the possible scheduling options.
- Placement in M3 application to used for relevant industries.

**Comment by ranga90** [comment]
High Level Spec document is attached for reference, please.
[Dock Loading Spec V1.0.pptx](https://github.com/infor-design/enterprise/files/6868552/Dock.Loading.Spec.V1.0.pptx)

**Comment by tmcconechy** [comment]
cc @inforandy

**Comment by ranga90** [comment]
Hi @tmcconechy and @lucacolumbu , 
please find attached the latest email conversation on this which may be useful for reference, and Latest Figma design is as below:

Idea design for Gantt chart for dock door scheduler:
https://www.figma.com/file/YZadVbj3bByqT9pFWdJxhi/Gantt-Chart?node-id=1%3A3612

Alternative design:
https://www.figma.com/file/YZadVbj3bByqT9pFWdJxhi/Gantt-Chart?node-id=1%3A348

**Comment by ranga90** [comment]
[Re Inquiry on the possible ETA of new IDS Component request.zip](https://github.com/infor-design/enterprise/files/7556688/Re.Inquiry.on.the.possible.ETA.of.new.IDS.Component.request.zip)

**Comment by tmcconechy** [comment]
Posting a link to a more generic gantt chart design https://www.figma.com/file/YZadVbj3bByqT9pFWdJxhi/Gantt-Chart?node-id=207%3A41728 for future ref..

**Comment by tmcconechy** [comment]
Closing this in favor of https://github.com/infor-design/enterprise-wc/issues/889 more details coming soon there.
