### ISSUE TITLE
Field Options: Field set focus / hitboxes looks off and misaligned

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5456]
**Describe the bug**
Field Options: Field set focus / hitboxes looks off and misaligned

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-options/example-fieldset.html?theme=new&mode=dark&colors=0066D4
2. Hover  & click  "4209 Industrial Avenue Los Angeles, California 90001 USA"

**Expected behavior**
Hitbox / focus should not overlap other components & should be aligned

**Version**
ids ver. 4.54 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/126963238-1501595a-bbfb-40c4-85cc-8f8a439f8100.png)

**Platform**
All major browsers & devices

**Additional context**
N/a

**Comment by nganotice** [comment]
Also experienced this on Safari - https://main-enterprise.demo.design.infor.com/components/field-options/example-no-init.html 
<img width="324" alt="Screen Shot 2021-10-12 at 4 57 11 PM" src="https://user-images.githubusercontent.com/84306838/137044431-0e732ec0-4498-4c75-83f2-d7a3385c5cde.png">

And Microsoft Edge - https://main-enterprise.demo.design.infor.com/components/field-options/example-no-init.html
<img width="326" alt="Screen Shot 2021-10-12 at 4 58 57 PM" src="https://user-images.githubusercontent.com/84306838/137044586-d43f2a32-1b44-468a-bf54-05a0d7d3328c.png">

**Comment by tmcconechy** [comment]
Descoping this issue as field options are not important right now
