### ISSUE TITLE
Fieldset: Submit button error

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5457]
**Describe the bug**
Fieldset: Submit button error

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/fieldset/example-fields.html
2. Populate the fields
3. Click Submit

**Expected behavior**
Should have no error

**Version**
IDS 4.54 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/126979334-84fad1ea-0516-41ad-af7d-6ae9649bc67d.png)

![image](https://user-images.githubusercontent.com/45757016/126979367-3a36d230-c184-44f0-b218-df0eeeefc6e1.png)

**Platform**
All major browser & devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Pushed a quick fix for this demo app issue

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://main-enterprise.demo.design.infor.com/components/fieldset/example-fields.html 
![image](https://user-images.githubusercontent.com/45757016/127140827-b5018037-d9ee-48d0-b0f6-31dc6a9846b0.png)
