### ISSUE TITLE
Message: Add informational status

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise#5459]
**Is your feature request related to a problem or use case? Please describe.**
Message component currently has only 3 statuses available: error, alert, success.

**Describe the solution you'd like**
We would like to be able to set an informational status. It would have a blue 'info' icon like on the screenshot.
![image](https://user-images.githubusercontent.com/86295640/127114911-75263d4c-afbe-42bf-8f37-66bcb3ae8c85.png)

**Describe alternatives you've considered**
Temporary we do not include any status for those messages, but we would like to

**Additional context**
Used in angular app
Infor application: WFM

**Comment by tmcconechy** [comment]
You can just use the one with no icon for informational dialogs. 

https://main-enterprise.demo.design.infor.com/components/message/example-index.html

- complete example
- or confirmation example

However judging by the delete text this should probably be an alert or error type. I dont mind eventually one day adding the info icon too but the idea was for those to use no icon.

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.55.0-dev.

https://main-enterprise.demo.design.infor.com/components/message/example-index.html
![Screen Shot 2021-08-25 at 4 36 48 PM](https://user-images.githubusercontent.com/84306838/130757418-e8c47b11-d06b-407c-8aae-7488c73cc841.png)

Moving this ticket to Done.

Thanks!

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.55.0-dev.

https://main-enterprise.demo.design.infor.com/components/message/example-index.html
![Screen Shot 2021-08-25 at 4 56 13 PM](https://user-images.githubusercontent.com/84306838/130760780-56de1257-a290-4c7d-8e81-85cad37d1f1a.png)

Moving this ticket to Done.

Thanks!
