### ISSUE TITLE
Header: Looks cut off in responsive view after expanding the search field

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5460]
**Describe the bug**
Header: Looks cut off in responsive view after expanding the search field

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-long-title-with-button.html
2. Minimize the screen to responsive view 
3. Open the Search field and type 'test'
4. Click outside to collapse the search field 

**Expected behavior**
Title should not look cut off

**Version**
ids 4.54 - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/127146630-b6d0c476-edb7-490c-8e08-c33190af9915.png)

**Platform**
All major browser, OS & devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
The text should ideally be restored to the previous state. Also its not quite centered

**Comment by EdwardCoyle** [comment]
This example is using a regular Toolbar.  I suspect we could fix it quickly by swapping for a similarly-structured Flex Toolbar

**Comment by tmcconechy** [comment]
Descoping for now
