### ISSUE TITLE
Rich Text Editor not understanding some HTML used in field.

### ISSUE THREAD

**Issue by jdrinka1** [infor-design/enterprise#5462]
**Describe the bug**
Modified HTML tags are not displaying in WebUI text boxes that allow you to view the HTML. Starting this in Hook and Loop since I see the same issue on the components examples pages.

**To Reproduce**
1. Go to https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
2. Replace the current text in the Comments box with the following text.
```
<p>As an employee of the Company, you will be required to:</p><ol><li>devote the whole of your time, efforts, attention and skills during the hours of work and such other times as may be reasonably necessary to the performance of your duties;</li><li>use your best endeavours to promote the interests and business of the Infor Group; and</li><li>faithfully and diligently perform your duties a may be assigned from time to time</li></ol>
```
3. Click the HTML in the editor box.
4. insert type="a" into the first ordered list element.
![updatedhtmlText](https://user-images.githubusercontent.com/86791155/127154144-e86dec40-402f-4906-8588-0f5b95546079.png)

5. Click the VISUAL in the editor box
6. Note the list items still displays as numbers. Adding the type="a" into the ordered element should change it to display a. b. c. 
7. If you click the HTML in the editor box again.. The type="a" is no longer there. 

**Expected behavior**
The list items should display as a. b. c.

**Version**
- ids-enterprise: 4.52.2

**Screenshots**

**Platform**
 - Chrome - Version 92.0.4515.107 (Official Build) (64-bit)
![displayingAsNumbers](https://user-images.githubusercontent.com/86791155/127151562-7b30edc3-2ab0-43ac-b46b-b69653044fea.png)

**Additional context**

**Comment by jdrinka1** [comment]
Here is the related customer reported jira ticket. https://jira.lawson.com/browse/LMCLIENT-36198

Here is a screen shot of the html text used. 

![htmlText](https://user-images.githubusercontent.com/86791155/127151865-cb8bd4ab-d9cf-4c53-baf5-cfdf1dd5e3d3.png)

**Comment by jdrinka1** [comment]
![updatedhtmlText](https://user-images.githubusercontent.com/86791155/127154144-e86dec40-402f-4906-8588-0f5b95546079.png)

**Comment by tmcconechy** [comment]
To avoid xss intrusion we are stripping some attributes. We could either not strip type on OL (if possible). Or maybe add a button that lets numbers be a. b. c.

Also copied the text out instead of screen shots.

**Comment by janahintal** [comment]
Failing on my end. It did not show roman numbers and went alphabetically ordered in lowercase again after trying all combinations. Kindly check video below.
https://user-images.githubusercontent.com/45757016/130738829-eeebc3eb-e0c9-4c74-a83b-fefbcd68c314.mp4

**Comment by ericangeles** [comment]
@janahintal I see what you mean here. I'll provide another PR for an additional fix.

**Comment by janahintal** [comment]
This is now working as expected in https://main-enterprise.demo.design.infor.com/components/editor/example-index.html. Will now move this to Done. Thanks!
