### ISSUE TITLE
Message: Add close button option

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise#5464]
**Is your feature request related to a problem or use case? Please describe.**
Message component does not have an option to add close button as X (compared to Modal dialog or CAP).

**Describe the solution you'd like**
Message component should have the option to add close button (X) at the top. It could work as a third option in confirmation dialogs leaving some space for other buttons (important especially for localized text).
![image](https://user-images.githubusercontent.com/86295640/127112834-dcb2ab3a-442f-4900-b0e0-932e802cf98e.png)

**Describe alternatives you've considered**
As a temporary solution we have added a third button, but there is not much space left for longer localizations
![image](https://user-images.githubusercontent.com/86295640/127113538-b0132245-d95d-42b5-b59c-f98c30706992.png)

**Additional context**
Infor application: WFM

**Comment by tmcconechy** [comment]
I think this makes sense. Since the modal has a close button option we could just add one to message and pass it through. Then check the styling.

But note this dialog is like a alert() dialog which does not have an X so your workaround seems like the actual correct UX.

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to done. thanks
v4.55.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/message/test-close-btn.html
![image](https://user-images.githubusercontent.com/56722184/130230353-a7b911cc-53f1-4fa9-adc1-1e112926ec19.png)
