### ISSUE TITLE
PieChart: Small pieces are displayed on top of each other

### ISSUE THREAD

**Issue by krahs1** [infor-design/enterprise#5465]
**Describe the bug**
The labels on a pie chart with small pieces near the top or bottom of the chart cause the labels to not be readable since they are displayed on top of each other 

**To Reproduce**
To reproduce this issue run the components/pie/example-index.html example but the change the data to the following data set.
```
  [{
            data: [{
                name: 'Item A',
                value: 98.1,
                id: 'item-a',
                attributes: [
                  { name: 'id', value: 'item-a' },
                  { name: 'data-automation-id', value: 'item-a-automation-id' }
                ],
                tooltip: 'Item A <b>{{percent}}</b>'
            }, {
                name: 'Item B',
                value: .7,
                id: 'item-b',
                attributes: [
                  { name: 'id', value: 'item-b' },
                  { name: 'data-automation-id', value: 'item-b-automation-id' }
                ],
                tooltip: 'Item B <b>{{percent}}</b>'
            }, {
                name: 'Item C',
                value: .3,
                id: 'item-c',
                attributes: [
                  { name: 'id', value: 'item-c' },
                  { name: 'data-automation-id', value: 'item-c-automation-id' }
                ],
                tooltip: 'Item C <b>{{percent}}</b>'
            }, {
                name: 'Item D',
                value: .3,
                id: 'item-d',
                attributes: [
                  { name: 'id', value: 'item-d' },
                  { name: 'data-automation-id', value: 'item-d-automation-id' }
                ],
                tooltip: 'Item D <b>{{percent}}</b>'
            }, {
                name: 'Item E',
                value: .4,
                id: 'item-e',
                attributes: [
                  { name: 'id', value: 'item-c' },
                  { name: 'data-automation-id', value: 'item-e-automation-id' }
                ],
                tooltip: 'Item E <b>{{percent}}</b>'
            }, {
                name: 'Item F',
                value: .2,
                id: 'item-f',
                id: 'item-f',
                attributes: [
                  { name: 'id', value: 'item-f' },
                  { name: 'data-automation-id', value: 'item-f-automation-id' }
                ],
                tooltip: 'Item F <b>{{percent}}</b>'
            }]
          }];  
```

1. Run the example demo "components/pie/example-index.html"
2. replace the data with the above data.
3. Display the chart
4. See the label displayed on top of each other.

**Expected behavior**

**Version**

 IDS Enterprise Components - v4.52.2

**Screenshots**
![image](https://user-images.githubusercontent.com/19823048/127172165-80b19af1-4b9f-4cba-8b45-5d4da8e63e8e.png)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

Landmark
Windows 10
Chrome 
Version 91.0.4472.164 (Official Build) (64-bit)

**Additional context**

This is a pretty common chart display when displaying the completion of some process. When the process is mostly complete the small categories of incomplete categories will be at the end and so at the top of the display.

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise/issues/3712 reported

**Comment by tmcconechy** [comment]
Descoping this for now. Please use a legend and no lines

**Comment by pwpatton** [comment]
@tmcconechy It looks like this is doable. 

Check out these examples and pages.
- https://jsfiddle.net/thudfactor/HdwTH/
- http://jsfiddle.net/rocky1616/oLzsrd4o/

- https://stackoverflow.com/questions/19792552/d3-put-arc-labels-in-a-pie-chart-if-there-is-enough-space/19801529#19801529
- https://stackoverflow.com/questions/14802600/preventing-text-clipping-in-d3-javascript-charting/14803104#14803104
- https://stackoverflow.com/questions/19681724/how-to-avoid-labels-overlapping-in-a-d3-js-pie-chart
