### ISSUE TITLE
Lookup: Single select lookup not working properly

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#5466]
**Describe the bug**
We are not able to navigate to next page in single select lookup popup.

**To Reproduce**
1. Go to "ids-enterprise-ng-demo/lookup" page
2. In that page, open "Products (Async Results)" single select lookup.
3. Select any value from page 1. Popup get auto close.
4. Again open the same lookup popup and click on   pagination "Next" button.
5. See popup got auto closed.  

**Expected behavior**
User should be able to navigate to next page and popup should not get close. 

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
On workaround is to disable autoApply with the setting. This will make it work but you will have to click apply after you select.

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.54.0-dev.

https://main-enterprise.demo.design.infor.com/components/lookup/test-single-select-serverside.html
![Lookup Fix](https://user-images.githubusercontent.com/84306838/127444793-14ebada6-44b0-49a6-9831-67a747b8e03f.gif)

Going to the next page doesn't close the modal anymore but there's an issue with the response time of the results - as you can see in the GIF the loading's a bit slow. @tmcconechy 

Thanks!
