### ISSUE TITLE
Editor: the dropdown on the toolbar doesnt have a tooltip 

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#5472]
**Describe the bug**
the dropdown for the font style in the toolbar doesn't have any tooltip when it is hovered or focused by the keyboard.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-customize-buttons?theme=uplift&variant=light
2. hover your mouse on the dropdown or focus to it via keyboard, there should be a tooltip

**Expected behavior**
There should be a tooltip when the dropdown is focused/hovered over.

**Version**

- ids-enterprise: 4.53.5

**Screenshots**
![image](https://user-images.githubusercontent.com/29673378/127439571-6790a1a1-2508-494a-9a62-36f5e6401677.png)

**Platform**
 - Infor Application/Team Name: Landmark Client
 - Device: (if applicable) :NA
 - OS Version: Windows 10
 - Browser Name: Firefox
 - Browser Version: Firefox 90.0.2

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-15370

**Comment by tmcconechy** [comment]
Yeah i guess it should say "Choose Font / Heading Type" or something like that

**Comment by jbrcna** [comment]
working as expected. moving this ticket to Done
v4.55.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/editor/example-customize-buttons
![image](https://user-images.githubusercontent.com/56722184/129294358-a6348d56-e183-4a07-a121-a95a48d07afe.png)
