### ISSUE TITLE
Calendar: Add date range to calendar component

### ISSUE THREAD

**Issue by edinfor** [infor-design/enterprise#5474]
**Is your feature request related to a problem or use case? Please describe.**

We would like to enhance the calendar at https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html to show a certain number of weeks for example 6 or 8.

Can the calendar take a date range parameter and render the full calendar using the given range?
e.g. pass in July 5 to August 25, calendar will start from July 5 to August 25 on the same calendar.

Usecase:

 As an employee, when I access available shifts plotted for a given date range on a calendar, I can see all the available dates on the same calendar.

https://hcmjira.infor.com:8443/browse/WFM-32589

**Describe the solution you'd like**
Add a new parameter called range in the core component and add typing on angular to the monthview.

**Describe alternatives you've considered**
Add a scheduling component #2563 

**Additional context**
Product team at WFM really needs this to push product design forward and it is what the customers truly want.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
