### ISSUE TITLE
Empty Messages example page on the site uses the same icon for three different classes

### ISSUE THREAD

**Issue by clazarev** [infor-design/enterprise#5475]
![image](https://user-images.githubusercontent.com/11888130/127589266-129f511b-0ac8-41ab-b7ae-7f7d69ed3790.png)
I was baffled when used "icon-empty-generic" as an empty message icon for a list. It looked like a question mark, while on this site it was a folder with a magnifier.
I realized that in the code of the example page svg name was copy-pasted. Please see the screenshot

**Comment by tmcconechy** [comment]
thanks @clazarev i fixed this on https://github.com/infor-design/enterprise/commit/afa25deb8bcb04b5fe3efb7e4ae3abc5a7ee840a

Good Catch
