### ISSUE TITLE
Editor does not support pasting of plain text

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise#548]
**Describe the bug**
Rich Text Editor does not support pasting of plain text
used version: 4.8.0
**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/editor/example-index?font=source-sans
2. Copy url from Chrome url bar
3. Try to paste into Editor
4. See paste ignored

**Expected behavior**
Editor supports paste of plain text

**Comment by tmcconechy** [comment]
Some related issues:
https://github.com/infor-design/enterprise/issues/401 - Related to paste
https://github.com/infor-design/enterprise/issues/335 - Part of this is mentioned indirectly

**Comment by tmcconechy** [comment]
Pushed a fix for this in https://github.com/infor-design/enterprise/pull/635

**Comment by CindyMercadoReyes** [comment]
On Win 10 IE 11 I'm unable to copy and paste any url into the Editor for the Editor Customize Button component.  
http://4100-beta0-enterprise.demo.design.infor.com/components/editor/example-customize-buttons.html

**Comment by tmcconechy** [comment]
Please retest now that i fixed the errors on https://github.com/infor-design/enterprise/pull/679
Was a general error. I am able to paste with ctrl-c after the change.

**Comment by brianjuan** [comment]
Win 10 IE
http://4100-beta0-enterprise.demo.design.infor.com/components/editor/example-customize-buttons.html

Can't interact with the Editor, it seems like the Editor is not being loaded correctly (no toolbar). I waited and tried several times but still no good.

<img width="1303" alt="screen shot 2018-08-28 at 12 52 52 pm" src="https://user-images.githubusercontent.com/39508864/44701537-c1b3db80-aac1-11e8-8aad-ebf466515e09.png">

**Comment by tmcconechy** [comment]
This is because of the error on IE i mentioned we pushed a fix and this can be retested on the new URL now http://4100-beta1-enterprise.demo.design.infor.com/components/editor/example-customize-buttons.html

**Comment by brianjuan** [comment]
Pasting of plain text is working on IE but it's removing texts with "ng-some other characters" from other paragraph.

http://4100-beta1-enterprise.demo.design.infor.com/components/editor/example-customize-buttons.html
http://4100-beta1-enterprise.demo.design.infor.com/components/editor/example-index
**Before pasting**
<img width="1026" alt="screen shot 2018-08-29 at 2 46 26 pm" src="https://user-images.githubusercontent.com/39508864/44770397-8507e300-ab9a-11e8-8a31-dec3a9208af0.png">
**After pasting a url or any other plain text**
"ng-edge" was removed from the word "cutting-edge"
<img width="1023" alt="screen shot 2018-08-29 at 2 49 06 pm" src="https://user-images.githubusercontent.com/39508864/44770489-cef0c900-ab9a-11e8-8d79-5c359026b61b.png">

Another scenario:
-Clear contents of the editor, then type "testing-anything secondword"
-Paste anything for example: "Lorem Ipsum, giving information on its origins"
-"ng-anything" will be removed from the word "testing-anything"
<img width="987" alt="screen shot 2018-08-29 at 2 57 32 pm" src="https://user-images.githubusercontent.com/39508864/44770880-014ef600-ab9c-11e8-96c3-93c944adac3c.png">

**Comment by tmcconechy** [comment]
Added a PR to fix the pasting of `ng` it was getting removed from the paste string. Will be ready for the next round of QA

**Comment by brianjuan** [comment]
http://4100-rc0-enterprise.demo.design.infor.com/components/editor/example-customize-buttons.html
QA verified, bug fix is now working on all browsers.
