### ISSUE TITLE
Datagrid: Issue changing cellNavigation when switching the selectable

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5482]
Describe the bug
We are changing the selection mode between 'single' and 'mixed' on a datagrid.  
When in 'single' mode, set the option cellNavigation to false to enable moving through the datagrid rows with the hand pointer. When in 'mixed' mode, set the option cellNavigation to true to enable moving through the datagrid cells with the pointer cursor.

Issue is that the cursor and navigation are not changing when updated.

1. Using the attached 'test-change-selectable-and-cellnavigation.html'
2. Notice that datagrid navigation is row navigation and the cursor is a hand
3. Click on the 'Switch to Mixed Mode' button
4. Notice that datagrid navigation is still row and the cursor is still a hand

Expected behavior
Changing selection and cellNavigation take affect when switching.

Version
- ids-enterprise: v4.51.4

**Comment by claudenbach** [comment]
[Git-5482.zip](https://github.com/infor-design/enterprise/files/6919199/Git-5482.zip)

**Comment by vonnyw** [comment]
@tmcconechy Please let us know which release this will be scheduled for. 4.53 patch would be ideal if it's a minor one. Thanks.

**Comment by tmcconechy** [comment]
Its scheduled as of now for Sep 4.56 sprint once we do triage. But could move it to 4.55 if needed. We can access the patch based on the fix. Seems like it wouldn't be too bad of a one.

**Comment by vonnyw** [comment]
Sounds good Tim, yeah 4.55 and a patch would be great! Thanks.

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.55.0-dev.

https://main-enterprise.demo.design.infor.com/components/datagrid/test-change-selectable-and-cellnavigation.html
![5482 2](https://user-images.githubusercontent.com/84306838/129311124-00b19220-0127-4a87-9026-e2cd21c66332.GIF)

Moving this ticket to Done. 

Thanks!
