### ISSUE TITLE
Search Field in Toolbar "X" alignment when collapsed: false

### ISSUE THREAD

**Issue by matt-sciaretta-infor** [infor-design/enterprise#5486]
![IDS-X](https://user-images.githubusercontent.com/78383494/128029149-1e571c18-29be-4be1-839b-81632da1304a.jpg)
![IDS-code](https://user-images.githubusercontent.com/78383494/128029179-5dbc99b1-4ea7-4757-9e72-c97762864680.jpg)
**Describe the bug**
I am working on the Infor Stratus project. We are using a search field inside of a toolbar and setting it to collapsed: false. When the field is focused and text is entered, an X appears that allows clearing the value. In this case, the X is not vertically aligned in the middle. 

**To Reproduce**
Create a toolbar search field, set data-options="{collapsible: false}". Click into the field and add text. Notice the X is pushed toward the top. 

**Expected behavior**
Expecting to see the X vertically aligned in the middle.

**Version**
"ids-enterprise-ng": "10.2.0"

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor Stratus
 - Device: Dell Lattitude
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 92.0.4515.131 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
We had a lot of fixes to this https://github.com/infor-design/enterprise/issues?q=is%3Aissue+close+search+is%3Aclosed i would say lets try this on 10.3.0 which will be out soon.

For other suggestions:
- do you see this in any of our examples? at https://main-enterprise.demo.design.infor.com/components/searchfield to verify?
- make sure to use the newer flex-toolbar not toolbar and this could help with this issue

**Comment by yohannahbautista** [comment]
Hi, I pulled the main branch and checked http://localhost:4200/ids-enterprise-ng-demo/searchfield-clear and added `data-options="{ collapsible: false }"` in the html and the button seems aligned
<img width="551" alt="Screen Shot 2021-09-27 at 7 05 14 PM" src="https://user-images.githubusercontent.com/85279127/134896862-477105ff-f96c-4635-82e8-e50a59bc3725.png">
I also checked http://localhost:4000/components/searchfield/test-clearable.html and added the collapsible option too
<img width="771" alt="Screen Shot 2021-09-27 at 7 12 11 PM" src="https://user-images.githubusercontent.com/85279127/134897751-9732284d-cd86-444d-bafd-6c2e3535344f.png">

**Comment by ericangeles** [comment]
@tmcconechy @yohannahbautista we can assume that this one is already fixed.

**Comment by tmcconechy** [comment]
yeah fix has been merged lets just put this again in ready to QA to go through this process.
