### ISSUE TITLE
Datagrid: Tree list indentation is not left aligned when row has no children and datagrid row height is extra small

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#5487]
**Describe the bug**
Tree list indentation is off when row has no children and datagrid row height is extra small.

**To Reproduce**

1. Modify test-post-renderer-tree.html and add the following option. `rowHeight: 'extra-small'`
2. Go to test-post-renderer-tree.html
3. Notice the left alignment is off when a row has no children. It makes it appear as if they are children of the previous row when they aren't.

**Expected behavior**
Row values should left align properly.

**Version**
4.38.0-dev,  4.52.2

**Screenshots**
<img width="366" alt="extra-small-row-height-tree-indent-issue" src="https://user-images.githubusercontent.com/1056684/128082699-89949674-9eaf-4461-bd85-9cb0ef10e899.PNG">
<img width="1078" alt="extra-small-row-height-tree-indent-issue-1" src="https://user-images.githubusercontent.com/1056684/128082705-a2b599dc-a01d-47d4-bc01-69159f69123a.PNG">

**Platform**
 - Landmark
 - Windows 10 
 - Chrome
 - 92.0.4515.131

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.55.0-dev.

https://main-enterprise.demo.design.infor.com/components/datagrid/example-tree.html
https://main-enterprise.demo.design.infor.com/components/datagrid/test-tree-editable.html
https://main-enterprise.demo.design.infor.com/components/datagrid/test-tree-export.html
https://main-enterprise.demo.design.infor.com/components/datagrid/test-post-renderer-tree.html
<img width="733" alt="Screen Shot 2021-08-20 at 5 18 54 PM" src="https://user-images.githubusercontent.com/84306838/130211375-56114646-c370-4061-9c30-a9c36eeb0218.png">

Moving this ticket to Done.

Thanks!
