### ISSUE TITLE
Datagrid: Exception column not properly rendered on responsive/mobile view(968x820 below)

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5495]
**Describe the bug**
Exception column not properly rendered on responsive/mobile view

**To Reproduce**

1. Go to https://4540-beta0-enterprise.demo.design.infor.com/components/datagrid/example-colspan.html
2. Scroll to the left to see "Exception" column
3. See error

**Expected behavior**
Exception column should be properly rendered on responsive/mobile view(968x820 below)

**Version**
v4.54.0-beta

**Screenshots**
**Responsive view(968x820 below)**
![Screen Shot 2021-08-06 at 5 25 40 PM](https://user-images.githubusercontent.com/84306838/128489159-3740829c-646a-4f34-8569-8ed45b517c1c.png)

**iPhone X**
![Screen Shot 2021-08-06 at 5 19 56 PM](https://user-images.githubusercontent.com/84306838/128488372-5286af81-ce72-4d34-9e5f-def38a93e95e.png)

**Platform**
All browsers - Responsive view/mobile devices(968x820 below)

**Additional context**
N/A

**Comment by tmcconechy** [comment]
I think this can be fixed in the demo app by setting the column width of that column so it doesnt "flex". But this is just an issue with this demo

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.62.0-dev.
https://main-enterprise.demo.design.infor.com/components/datagrid/example-colspan.html
<img width="509" alt="image" src="https://user-images.githubusercontent.com/56722184/160050768-07a90eb4-f856-42b7-bf61-1757c2637b01.png">
