### ISSUE TITLE
Datagrid: Some filter is not opening in the column header

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5496]
**Describe the bug**
Datagrid: Some filter is not opening in the column header

**To Reproduce**

1. Go to https://4540-beta0-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
2. In Product Name column, open the filter

**Expected behavior**
Filter should be opened

**Version**
ids-4540-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/128492427-dd0425b8-4e70-4258-ace0-ace33e5e0e3d.png)

**Platform**
All major browser, OS & Devices 

**Additional context**

**Comment by tmcconechy** [comment]
@janahintal do i need any extra steps, with these its opening for me and i cant reproduce

**Comment by tmcconechy** [comment]
Closing as unable to reproduce
