### ISSUE TITLE
Datagrid: Equals filter not working properly

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5497]
**Describe the bug**
Equals filter not working properly

**To Reproduce**

1. Go to https://4540-beta0-enterprise.demo.design.infor.com/components/datagrid/example-books.html (all examples that requires filtering - equals)
2. Go to "Ledger" column
3. Click on the filter button
4. Then pick equals then click on the textbox then type in "CORE" 
5. See error

**Expected behavior**
Equals filter should work properly - when typing the same part of the column it, results shouldn't be blank

**Version**
v4.54.0-beta

**Screenshots**
https://4540-beta0-enterprise.demo.design.infor.com/components/datagrid/example-books.html
![Filter issue](https://user-images.githubusercontent.com/84306838/128493770-e23cbe96-e18e-438b-9293-bb0e5eccf3e7.gif)

https://4540-beta0-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
![Filter issue 2](https://user-images.githubusercontent.com/84306838/128495721-d66e494b-868e-4fe0-b8fa-e7b35e9efb60.GIF)

https://4540-beta0-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html
- "Compressor" was shown but when I added "s" it didn't return any results
![Filter issue 3](https://user-images.githubusercontent.com/84306838/128495738-14c56314-94e7-44ab-9b9a-7b405d1c5228.GIF)

**Platform**
-All browsers & mobile devices

**Additional context**
N/A

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
