### ISSUE TITLE
Datagrid: Comments column disappears on responsive/mobile view(464x667 below)

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5498]
**Describe the bug**
Comments column disappears on responsive/mobile view(464x667 below)

**To Reproduce**

1. Go to https://4540-beta0-enterprise.demo.design.infor.com/components/datagrid/example-expandable-cells.html
2. Click on Personalize Columns
3. Tick "Product Id"
3. Scroll to the left

**Expected behavior**
Comments column should be responsive and still show even if a new column is added

**Version**
v4.54.0-beta

**Screenshots**
**Responsive view(464X667 below)**
![Comments 1 (1)](https://user-images.githubusercontent.com/84306838/128499471-caf450d8-006a-43a3-98a9-8fb24a70e40f.gif)

**iPhone 12 Pro Max**
![Comments 2](https://user-images.githubusercontent.com/84306838/128498973-48f1106a-b8c2-42e8-b68a-ab277273ae45.GIF)

**Platform**
All browsers - Responsive view/mobile devices(464X667 below)

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Descoping some older issues
