### ISSUE TITLE
Tree control : tree text is obscured in nested tree nodes

### ISSUE THREAD

**Issue by jp-infor** [infor-design/enterprise#5499]
**Description**
When adding lengthy text strings to nodes in a Tree control, the text becomes obscured or lost, the greater the number of nested nodes are added to the tree. Text is likely to be obscured the more deeply a node is nested.

**To Reproduce**
The issue can be reproduced by adapting the existing Tree control in the IDS demonstration suite (https://design.infor.com/code/ids-enterprise/latest/demo/components/tree/example-plus-minus-folders.html). Please find attached (as a text file) the adapted HTML element which can be inserted into the demonstration web page. The <div> that needs to be replaced with the attached code has the class name "page-container".

1. Navigate to the IDS Tree component demo.
2. Launch the browser tools console (F12). Open the elements section in the browser debugging tools.
3. Replace the existing <div class="page-container"...</div> with the adapted HTML code attached to the issue.
4. Open the nested nodes in the tree to display the text.

**Expected behavior**
All the displayed text in each node should wrap correctly and be fully visible.

**Version**
- ids-enterprise: 4.53.5

**Screenshots**
Added screenshot demonstrating the issue
[tree_demo-page-container-element.txt](https://github.com/infor-design/enterprise/files/6945178/tree_demo-page-container-element.txt)
![NestedText](https://user-images.githubusercontent.com/88488184/128503309-48adb139-704f-4ea8-b08b-10f216bb0358.PNG)
.

**Platform**
 - original error found by Infor SunSystems
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 92.0.4515.131 (Official Build) (64-bit)

**Additional context**

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to done. thanks
v4.55.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/tree/example-long-node-text.html
![image](https://user-images.githubusercontent.com/56722184/130228765-dfe5e316-bdf1-4112-a07a-3c2680d9a5bf.png)
