### ISSUE TITLE
Export to Excel: The excel exported from DataGrid doesn’t work on EDGE

### ISSUE THREAD

**Issue by afarn** [infor-design/enterprise#5507]
**Describe the bug**
No excel file generated when exporting to excel from datagrid on EDGE but it works on Chrome.

**To Reproduce**
1. Go to 'ids enterprise ng demo'
2. Click on 'D→DataGrid – Test Settings' on the left menu, and the page shows a table with data.
3. Click on the link 'Export to Excel'
4. No excel file generated.

**Expected behavior**
The excel file must be generated when exporting to Excel from Datagrid on Edge like Chrome.

**Version**
- ids-enterprise-ng: [v4.10.0]

**Screenshots**

![image](https://user-images.githubusercontent.com/40360119/128991371-2ec82742-6e82-4d21-9d79-79afffb5467e.png)

**Platform**
 - Device (if applicable) []
 - OS Version: [Windows 10]
 - Browser Name [Edge]
 - Browser Version [92.0.902.67 (Official Build) (64-bit)]

**Additional context**

**Comment by afarn** [comment]
Excuse me, maybe I misspoke.
Under Chrome, I have the Excel file but under Edge I don't have it.
![image](https://user-images.githubusercontent.com/40360119/129686032-e69e6395-2330-4f1f-8650-e556595a8bc2.png)

**Comment by tmcconechy** [comment]
Think is see the issue.. Pushing a fix

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.55.0-dev.

We can now generate the excel file from Microsoft Edge - https://main-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row.html

![Video 2](https://user-images.githubusercontent.com/84306838/130208503-0a5a3908-4161-45b8-99fc-7edd8172ccaf.gif)

Moving this ticket to Done.

Thanks!
