### ISSUE TITLE
ActionSheet: Add "tray" feature

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5509]
**Is your feature request related to a problem or use case? Please describe.**
Design came up with a new feature for action-sheet where the top https://www.figma.com/file/KMCdcFsKVDZjdPFClAS5OF/WFM-Mobile-Components-(Internal)?node-id=1172%3A6097

There are three additions from this design

1. The ability to have it "stuck" on the bottom as a "tray" (call it tray) and when you click it pulls up (call it a header shows)
<img width="861" alt="Screen Shot 2021-08-11 at 1 52 10 PM" src="https://user-images.githubusercontent.com/814283/129079084-6cc0f39e-c22b-40f8-b6ad-6dd8b0d34258.png">

3. The ability to drill into submenus
<img width="683" alt="Screen Shot 2021-08-11 at 1 52 20 PM" src="https://user-images.githubusercontent.com/814283/129079030-f572169b-08c1-4247-850b-1b889ece6c2c.png">

4. The ability to change the color of the tray for status
<img width="773" alt="Screen Shot 2021-08-11 at 1 52 28 PM" src="https://user-images.githubusercontent.com/814283/129079010-e040f718-20b2-4572-86f5-b148c1241958.png">

5. May need swipe up to open... (start with click)

**Describe the solution you'd like**
Add tray, header and submenus to the action-sheet

**Additional context**
https://jira.infor.com/browse/UXD-2120

**Comment by EdwardCoyle** [comment]
@tmcconechy @lucacolumbu Did we ever come to a consensus on the submenus part of this issue?  I vaguely remember discussing the submenus portion of the design and thinking we shouldn't address that immediately?

**Comment by tmcconechy** [comment]
Basically what we said is these arent 100% submenus. They are more of hiding and showing buttons. So the way i would code it in the example is

- Add ALL the links as in the second + third images
- But some are set to hidden
- When you click more... -> it just shows the hidden ones
- If the menu is so big as it takes up the whole view then it gets the X on the top and scrolls

I can demo together if thats easier to explain

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by CindyMercadoReyes** [comment]
A BDD was created for this ticket. Thanks, Cind
[BDDStory_github5509.docx](https://github.com/infor-design/enterprise/files/7670528/BDDStory_github5509.docx)
y
