### ISSUE TITLE
Datagrid: Allow a mask to be applied to a column's cell but no mask or a different mask to the filter cell 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5519]
Issue:
Currently mask options are applied to a column meaning the same mask will be applied when editing a column cell and the same mask will be used in the column's filter row cell.

Request:
Would like the ability to provide a mask for a column's cell and a different mask or no mask to the column's filter cell. 

Alternatives considered:
There are no viable alternates to pursue.

Additional context:
Working on a Landmark feature to allow the user to select or enter multiple lookup select values in the filter row cell for filtering the list.  When the list allows editing a column's cell value the mask applied will hamper the user's ability to enter multiple search values in the filter cell.

**Comment by tmcconechy** [comment]
For the one that takes this. My suggestion would be to add a `filterMaskOptions` setting. That when applied on the column lets the filter field take those mask settings instead of `maskOptions` as it does now. If not set it still uses `maskOptions`

**Comment by vonnyw** [comment]
@tmcconechy @ericangeles We need this to complete the multi select feature and therefore requesting it to be included in 4.54 patch.

**Comment by tmcconechy** [comment]
This is an enhancement not a bug. So i don't believe it should be critical. But we had planned to complete it this sprint.
So we can see if the fix looks safe to patch back when it's done, i dont believe it should be too bad tho.

**Comment by tmcconechy** [comment]
@vonnyw patched this fix into NG 10.3.1 (containing EP 4.54.1)
