### ISSUE TITLE
EmptyMessage: Empty chart inside of auto height card displays outside of card container

### ISSUE THREAD

**Issue by kvaldillez** [infor-design/enterprise#5527]
**Describe the bug**
When an empty chart (i.e. bar or pie) is rendered within an auto height card container, the empty chart will display outside of the card. This is due to a transform styling for the empty chart within a "height: auto" container.

**To Reproduce**
1. Go here and copy the HTML for the chart container: https://design.infor.com/code/ids-enterprise/latest/demo/components/bar/test-empty?theme=uplift&variant=light
2. Then go here and paste that HTML inside of one of the cards, replacing the text currently there: https://design.infor.com/code/ids-enterprise/latest/demo/components/cards/example-auto-size
3. Observe that the empty chart is outside of the card container

Code should look something like this:
```
<div class="row">
   <div class="two-thirds column">
      <div class="card auto-height" id="expandable-card-1">
         <div id="bar-example" class="chart-container bar-chart bar-chart-stacked">
            <svg width="774" height="313">...</svg>
            <div class="chart-legend"></div>
         </div>
      </div>
   </div>
   <div class="one-third column">
      <div class="card auto-height" id="expandable-card-2">
         <div id="bar-example" class="chart-container bar-chart bar-chart-stacked empty-message">
            <div class="empty-icon">
               <svg class="icon-empty-state is-azure" focusable="false" aria-hidden="true" role="presentation">
                  <use href="#icon-empty-no-data"></use>
               </svg>
            </div>
            <div class="empty-title">Nothing To See</div>
         </div>
      </div>
   </div>
</div>
```

**Expected behavior**
The empty chart should display within the auto height card container.

**Version**
- ids-enterprise: 4.54.0

**Screenshots**
![empty-chart-display-issue](https://user-images.githubusercontent.com/13121777/129754451-dac0402d-16b9-45ea-8830-6556aab68c87.png)

**Platform**
 - Infor Application/Team Name: Front-end Framework
 - Device: Macbook Pro
 - OS Version: MacOS Catalina 10.15.7
 - Browser Name: Chrome
 - Browser Version: Version 91.0.4472.164

**Comment by tmcconechy** [comment]
I see this as working pretty well when i tried. Result:

![Screen Shot 2021-08-17 at 12 59 30 PM](https://user-images.githubusercontent.com/814283/129769121-2198c47a-0f26-48ac-afa2-b82a650d7d0a.png)

Markup:

```
<div class="one-third column">
  <div class="card auto-height" <div="" id="bar-example">
    <div class="empty-icon">
       <svg class="icon-empty-state is-azure" focusable="false" aria-hidden="true" role="presentation">
         <use href="#icon-empty-no-data"></use>
        </svg>
     </div>
     <div class="empty-title">Nothing To See</div></div>
</div>
```

Maybe you just put it in the wrong place?

**Comment by kvaldillez** [comment]
You need to put the chart-container inside of the card with the empty-message class. The icon itself is fine but it's always wrapped in a chart container when it is rendered as part of a chart. See my code example above, specifically this part:
```
<div class="card auto-height" id="expandable-card-2">
    <div id="bar-example" class="chart-container bar-chart bar-chart-stacked empty-message">
        <div class="empty-icon">
            <svg class="icon-empty-state is-azure" focusable="false" aria-hidden="true" role="presentation">
                <use href="#icon-empty-no-data"></use>
            </svg>
        </div>
        <div class="empty-title">Nothing To See</div>
    </div>
</div>
```

**Comment by jbrcna** [comment]
this issue is now resolved.
 v4.55.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/emptymessage/example-chart-with-auto-height.html?theme=classic&mode=light&colors=2578a9
![image](https://user-images.githubusercontent.com/56722184/132252570-22f7d908-74b5-4cad-a5f2-75376458643d.png)
