### ISSUE TITLE
Enable mobile-specific e2e testing on Browserstack

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#553]
**Is your feature request related to a problem? Please describe.**

Some recent issues we've addressed like #245 and #400 require features that are only present on mobile browsers, like Android Chrome and iOS Safari.  It would be nice to be able to test things with the `TouchActions` API in Protractor, limit these tests to mobile environments, and test actual mobile devices in Browserstack as part of our E2E testing.

**Additional context**

- [TouchActions API description](https://www.protractortest.org/#/api?view=webdriver.WebDriver.prototype.touchActions) in the protractor docs
- [Selenium HQ's explanation](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/touch/TouchActions.html) of the TouchActions API

**Comment by EdwardCoyle** [comment]
@d-g-h, @tmcconechy, @clepore what do you guys think?

**Comment by tmcconechy** [comment]
I think its a good idea. We might have to spend some time to harden the tests for it thought.
It does seem to support it with our free license

**Comment by d-g-h** [comment]
Ask @CindyMercadoReyes also. I believe I mentioned this to her, but I can't remember her answer. Yes, we can have some tests devoted to these experiences. I have no real opinions about organization. Currently, mobile or smaller screens tests are within the component. Yeah, Tim has good point about the license. I think device testing requires an another license. Not sure about emulation either, meaning that we test a smaller screen, and use the touchActions methods you pointed out... better than nothing, and I feel like it's a decent smoke test.

**Comment by tmcconechy** [comment]
I checked and seems the automate part (which we have) should support all these: https://www.browserstack.com/list-of-browsers-and-platforms?product=automate

**Comment by d-g-h** [comment]
Select NodeJS, https://www.browserstack.com/automate/capabilities

**Comment by EdwardCoyle** [comment]
@CindyMercadoReyes, do you have anything to add?  As Dave said, would probably just be more smoke testing on our end and not affect you as much.

**Comment by CindyMercadoReyes** [comment]
@EdwardCoyle , I can write up some general mobile test cases, that the team can reference for the automation scripts.

**Comment by tmcconechy** [comment]
Also somewhat related is #1229

**Comment by tmcconechy** [comment]
Closing for now. If doing e2e testing then using puppeteer this wont be possible.
