### ISSUE TITLE
Datagrid: linkable tag icon in datagrid cell has incorrect background color

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#5533]
**Describe the bug**
Background color of linkable tag icon ( a right arrow icon '>') in a datagrid cell is showing the selection color as the background instead of the allowing the tabs background color to show through.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-alerts.html
2. Select a row
3. Notice in the tag (clickable column) the icon background is showing the selection color.

**Expected behavior**
No background or border color should be set on a linkable tag in a datagrid cell

**Version**
4.52

**Screenshots**
![image](https://user-images.githubusercontent.com/4737815/129967676-432e310b-359e-41bb-b028-3d3b6d23840d.png)

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: latest

**Additional context**

**Comment by janahintal** [comment]
This issue is now resolved. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/130225134-f2d1616f-ea60-4f36-905f-b3e48e254cd1.png)
![image](https://user-images.githubusercontent.com/45757016/130227417-78781e64-c11f-418e-aa72-070ae236c675.png)
