### ISSUE TITLE
Toolbarflex: Responsiveness(375x662 below)/Size(753x662 below) issues

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5535]
**Describe the bug**
Toolbarflex: Size/Responsiveness issues(375x662 below)

**To Reproduce**
**1st issue:** 
1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-index.html
2. View on responsive/any mobile(375x662 below)
3. Check "Incredibly Long Toolbar (Favor's Title)"
4. See error that the more actions button is not responsive

**2nd issue:** 
1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-searchfield-collapsible.html
2. View on responsive/any mobile(753x662 below)
3. Click on Search button
4. See error that the collapsible button is not in it's right size

**Expected behavior**
Toolbar input should be responsive and the collapsible button should be in it's correct size

**Version**
v4.55.0-dev

**Screenshots**
**1st issue:** All browsers (Responsive & Mobile view - 375x662 below)
<img width="307" alt="Screen Shot 2021-08-19 at 4 45 02 PM" src="https://user-images.githubusercontent.com/84306838/130038314-fd8f7bc0-8bf8-4fb4-8fcf-2f557c7d7367.png">

**2nd issue:** Only w/ Chrome/Edge/Safari (Responsive & Mobile view - 753x662 below)
<img width="262" alt="Screen Shot 2021-08-19 at 4 45 39 PM" src="https://user-images.githubusercontent.com/84306838/130038331-d6122f4a-3e95-48cf-8c41-9f501824bed8.png">

**Platform**
All browsers - Responsive view/mobile devices(375x662 below)

**Additional context**
N/A

**Comment by davidcarlsonberg** [comment]
It seems like Issue #1 is designed this way on purpose; to favor the title and not truncate it with `text-overflow: ellipsis;`.
I am unable to reproduce #2 on MacOS using Chrome, Firefox, or Safari.

**Comment by tmcconechy** [comment]
Yeah i think we can descope do this then.
