### ISSUE TITLE
Tooltip: Lookup button & Focus tooltip not working/rendered properly

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5536]
**Describe the bug**
Tooltip: Lookup button & Focus tooltip not working/rendered properly

**To Reproduce**
**1st issue:**
1. Go to https://main-enterprise.demo.design.infor.com/components/tooltip/example-tooltips-on-elements.html using Safari
2. Click on Lookup button on Tooltip tests>Code
3. See error that the button doesn't stay inside the textbox

**2nd issue:**
1. Go to https://main-enterprise.demo.design.infor.com/components/tooltip/example-tooltips-on-elements.html using Firefox
2. Click on Lookup button on Tooltip tests>Code
3. See error that the button isn't centered

**3rd issue:**
1. Go to https://main-enterprise.demo.design.infor.com/components/tooltip/example-trigger-focus.html using Safari
2. Click on Show Focus Tooltip
3. See error that tooltip isn't showing

**Expected behavior**
Lookup button should stay inside the textbox and be centered while the focus tooltip, when clicked, the tooltip should show

**Version**
v4.55.0-dev

**Screenshots**
**1st issue:**
![Lookup button issue](https://user-images.githubusercontent.com/84306838/130045577-54cf52af-1b91-4302-bf78-4a21d033d2d0.GIF)

**2nd issue:**
<img width="508" alt="Screen Shot 2021-08-19 at 5 24 10 PM" src="https://user-images.githubusercontent.com/84306838/130044810-390b5411-cfa6-409a-958c-9b3b47ce0c06.png">

**3rd issue:**
![Focus tooltip issue](https://user-images.githubusercontent.com/84306838/130045595-04b7561f-c9b6-4934-b0b9-ed108f3ba4cd.GIF)

**Platform**
Safari & Firefox(Responsive/mobile devices)

**Additional context**
N/A

**Comment by nganotice** [comment]
Found a new issue w/ an icon using Safari in Component - Calendar(All examples):

When clicking the datepicker, it doesn't stay where it's supposed to stay - https://4550-beta0-enterprise.demo.design.infor.com/components/calendar/example-calendar-toolbar.html

![Video 6](https://user-images.githubusercontent.com/84306838/132661063-f44c96a5-08e2-42e3-9f58-2c546897406a.gif)

**Comment by tmcconechy** [comment]
@nganotice i am not seeing this on safari https://4550-beta0-enterprise.demo.design.infor.com/components/calendar/example-index (also the link you gave me looks different than the screen shots).

**Comment by nganotice** [comment]
@tmcconechy - I can still encounter the issue on all the examples - will attach the screenshot of the console as well:

https://4550-beta0-enterprise.demo.design.infor.com/components/calendar/example-only-calendar-legend.html
<img width="535" alt="Screen Shot 2021-09-10 at 4 04 28 PM" src="https://user-images.githubusercontent.com/84306838/132821273-d4a2aacb-6d34-4f88-afed-ae753c98e921.png">

Just commented a diff link but I encountered that issue on all examples. Also maybe there's a factor w/ my safari version - Version 14.1 (16611.1.21.161.6) that's why I encountered that issue?

**Comment by tmcconechy** [comment]
I see the error in the console. But thats not effecting anything. I dont see the icon issue. I am on Safari 14.2 however.

CC @ericangeles

**Comment by tmcconechy** [comment]
@nganotice can you check this and let us know if anything is still off. if it is lets make a new issue

**Comment by nganotice** [comment]
Hi @tmcconechy - it's already working fine on my end. I'll just inform you once I've experienced the same issue again. Will move this ticket to Done. Thanks!

**Comment by nganotice** [comment]
Raised a new ticket for the remaining issue #5693.

Moving this ticket to Done.

Thanks!
