### ISSUE TITLE
Validation: Example Short Fields icons not displayed/rendered properly

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5541]
**Describe the bug**
Example Short Fields icons not displayed/rendered properly

**To Reproduce**Steps to reproduce the behavior:
**1st issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/validation/example-short-fields.html using all your browsers
2. Click on spinbox-sm
3. See error that there's an extra space after "+"

**2nd issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/validation/example-short-fields.html & https://main-enterprise.demo.design.infor.com/components/validation/example-multiple-errors.html using Safari
2. Click on lookup icon on example multiple errors & lookup and timepicker icons on example short fields
3. See error that the icons doesn't stay inside the textbox

**3rd issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/validation/example-short-fields.html using Firefox
2. Click on Lookup & Datepicker button
3. See error that the icons aren't centered

**Version**
v4.55.0-dev

**Screenshots**
**1st issue:** - issue on all browsers
![Screen Shot 2021-08-23 at 7 04 24 PM](https://user-images.githubusercontent.com/84306838/130437905-7422c6f9-325f-4103-8a37-1b615b2c7caa.png)

**2nd issue:** issue w/ Safari only
**Example Short Fields**
Lookup
![Screen Shot 2021-08-23 at 7 05 57 PM](https://user-images.githubusercontent.com/84306838/130438415-5d7c7e2e-f026-4197-9e71-84fc0d698f35.png)

Timepicker
![Screen Shot 2021-08-23 at 7 06 57 PM](https://user-images.githubusercontent.com/84306838/130438436-985828a3-997e-4475-8594-4a0f609aad25.png)

**Example Multiple Errors**
![Screen Shot 2021-08-23 at 7 05 16 PM](https://user-images.githubusercontent.com/84306838/130438591-cce94e10-9f3b-41a7-932e-65b6511ef4aa.png)

**3rd issue:** issue w/ Firefox only
![Screen Shot 2021-08-23 at 7 07 35 PM](https://user-images.githubusercontent.com/84306838/130438659-d198bf81-ae84-4566-90ea-e19f3ca009ea.png)

**Platform**
 All browsers/mobile devices

**Additional context**
N/A

**Comment by nganotice** [comment]
**(2nd issue)** -- Also experienced this issue on: https://main-enterprise.demo.design.infor.com/components/form/example-compact-mode.html

All Lookup icons in Safari as well.

**Comment by tmcconechy** [comment]
I think this issue covers all safari icons placement issues. It seems to be a general issue and we'll solve it here. No need to fail or raise anymore issues about that for now until this is solved.

**Comment by nganotice** [comment]
**1st issue** - Passed
The extra space is already removed
https://main-enterprise.demo.design.infor.com/components/validation/example-short-fields.html
<img width="257" alt="Screen Shot 2021-09-10 at 5 36 16 PM" src="https://user-images.githubusercontent.com/84306838/132833723-3bb64f4a-a798-47ab-9d94-a9134fbc1af2.png">

**2nd issue** 
Lookup - Passed
https://main-enterprise.demo.design.infor.com/components/validation/example-short-fields.html
<img width="258" alt="Screen Shot 2021-09-10 at 5 39 27 PM" src="https://user-images.githubusercontent.com/84306838/132834328-d3a2ee05-158f-4698-afd7-7d5dd006ef0d.png">

Timepicker - Passed
https://main-enterprise.demo.design.infor.com/components/validation/example-short-fields.html
<img width="348" alt="Screen Shot 2021-09-10 at 5 40 53 PM" src="https://user-images.githubusercontent.com/84306838/132834378-6ef8ae9e-b712-475c-8b07-a3ae895fdb88.png">

Example Multiple Errors - Passed
https://main-enterprise.demo.design.infor.com/components/validation/example-multiple-errors.html
<img width="336" alt="Screen Shot 2021-09-10 at 5 41 58 PM" src="https://user-images.githubusercontent.com/84306838/132834498-9d158228-b726-4cbc-b4a5-0f3c119feac6.png">

Example Compact Mode - 1 observation
The Time Picker & Lookup icons here are not centered
https://main-enterprise.demo.design.infor.com/components/form/example-compact-mode.html
![Screen Shot 2021-09-10 at 5 57 00 PM](https://user-images.githubusercontent.com/84306838/132836441-20942e5d-7d41-454f-99ca-d636c4af10e7.png)

**3rd issue** Passed w/ observations
I've noticed that the animation blue circle isn't centered
https://main-enterprise.demo.design.infor.com/components/validation/example-short-fields.html
<img width="335" alt="Screen Shot 2021-09-10 at 5 34 29 PM" src="https://user-images.githubusercontent.com/84306838/132833475-ca8312bf-e933-42cf-8567-8734752bc355.png">

Hi @tjamesallen15 - can you please check Example Compact Mode & the 3rd issue? Thanks!

**Comment by tmcconechy** [comment]
Thanks @nganotice I agree we should try to fix those small remaining issues. cc @tjamesallen15

**Comment by tjamesallen15** [comment]
> Thanks @nganotice I agree we should try to fix those small remaining issues. cc @tjamesallen15

Sure @tmcconechy

**Comment by nganotice** [comment]
All issues are now fixed from Issue 1-3 but I found a new one w/ https://main-enterprise.demo.design.infor.com/components/form/example-compact-mode.html (all other examples w/ Date Picker as well using Safari)
![Video 7](https://user-images.githubusercontent.com/84306838/133603348-83b1fb06-7590-4ab7-a9cd-29141430b9a5.gif)

cc @tjamesallen15 @tmcconechy

**Comment by tmcconechy** [comment]
@tjamesallen15 @nganotice 

The issue where it popups up hidden is https://github.com/infor-design/enterprise/issues/5550 
So can you look at just why the icon is moving around @tjamesallen15  ?

**Comment by ericangeles** [comment]
Adding @yohannahbautista on the loop as she's currently working on #5550.

**Comment by tjamesallen15** [comment]
> @tjamesallen15 @nganotice
> 
> The issue where it popups up hidden is #5550
> So can you look at just why the icon is moving around @tjamesallen15 ?

Hello will look on this.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
