### ISSUE TITLE
Heirarchy: expand and collapse buttons are missing on rtl

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#5544]
**Describe the bug**

**To Reproduce**

1. Go to https://master-enterprise.demo.design.infor.com/components/hierarchy/example-single.html?locale=ar-sa
2. expand and collapse button are missing and lines are not laid out correctlly

**Expected behavior**
Expand and collapse button should be visible

**Version**

- ids-enterprise: 4.51

**Screenshots**
LTR:
![image](https://user-images.githubusercontent.com/29673378/130551777-26855ffc-e89c-41c2-a4fd-bcb6d5bb576a.png)

RTL:
![image](https://user-images.githubusercontent.com/29673378/130551709-91f5c7ef-7ceb-4858-8312-cb180f5cac99.png)

**Platform**
 - Infor Application/Team Name: Landmark Client
 - Device: (if applicable): NA
 - OS Version: Windows 10
 - Browser Name: Firefox
 - Browser Version: 91.0.1

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-36710

**Comment by janahintal** [comment]
QA Passed. Working as expected in https://main-enterprise.demo.design.infor.com/components/hierarchy/example-single.html?locale=ar-sa. Thank you. 
https://main-enterprise.demo.design.infor.com/components/hierarchy/example-single.html?locale=ar-sa
