### ISSUE TITLE
Enable permanently-displayed field options button in touch environments

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#555]
**Is your feature request related to a problem? Please describe.**
The user experience surrounding the field options button on input fields doesn't currently work all that well (as of `v4.9.0`) in iOS environments, and doesn't work at all in Android environments.

To test, open http://master-enterprise.demo.design.infor.com/components/field-options/example-index.html in a mobile browser.

_In iOS Safari:_
- Field Options are not accessible unless the field is previously focused, and the button doesn't always stay in-tact when navigating away from the input field.

_In Android Chrome:_
- Field options are completely inaccessible on dropdown/multiselect components
- On most input fields, field options are visible once the input becomes focused, but immediately disappear and close their menus when the button is tapped.
- On checks/radios, interestingly enough everything works fine.

**Describe the solution you'd like**
- Field Options attached to other components should always be visible on the page and ready for interactions when a touch environment is detected (the Environment core component has a check for this as of `v4.10.x` that can be used)

**Additional context**
For an example of why we might want this, see the discussion about touch-enabled context menus on input fields in #245

**Comment by EdwardCoyle** [comment]
@deep7102, your thoughts?

**Comment by EdwardCoyle** [comment]
Per some in-person conversation with @deep7102:

- Everything works off of `mouseenter/mouseleave` events right now
- Need to disable the event system in touch environments and always display the field options via CSS class on the `.field` element, or other wrapper element.

**Comment by CindyMercadoReyes** [comment]
Hi Ed,  Per our conversation, There are multiple issues appearing for the Field Option component on iOS Phone X. I'm attaching multiple screen shots for your review.  Thanks, Cindy

![img_3404](https://user-images.githubusercontent.com/39101346/44351652-5ee29480-a470-11e8-9f2b-82d3bc1618eb.PNG)
![img_3403](https://user-images.githubusercontent.com/39101346/44351653-5ee29480-a470-11e8-8ffe-6bb171a199d2.PNG)
![img_3402](https://user-images.githubusercontent.com/39101346/44351654-5ee29480-a470-11e8-9ff5-7dbb9e71ebb2.PNG)
![img_3401](https://user-images.githubusercontent.com/39101346/44351655-5ee29480-a470-11e8-9fc2-3924c2632d80.PNG)
![img_3399](https://user-images.githubusercontent.com/39101346/44351656-5ee29480-a470-11e8-99b1-cc59b4a6c2eb.PNG)
![img_3398](https://user-images.githubusercontent.com/39101346/44351657-5ee29480-a470-11e8-9ffa-116fe3e9ae58.PNG)
![img_3397](https://user-images.githubusercontent.com/39101346/44351658-5ee29480-a470-11e8-8519-985e98f761e2.PNG)
![img_3396](https://user-images.githubusercontent.com/39101346/44351659-5ee29480-a470-11e8-937f-3efaf0c54c0e.PNG)
![img_3395](https://user-images.githubusercontent.com/39101346/44351660-5ee29480-a470-11e8-9707-19646442a175.PNG)

**Comment by EdwardCoyle** [comment]
@CindyMercadoReyes I made a few adjustments to the Popupmenu and Field Options components in #646 that should address:

- the input fields' and buttons' active states (blue border).  These should all appear/disappear at the correct timings.
- the placement of the popupmenu being off when a software keyboard is present.  The menu is now on a delay, and should open after the software keyboard disappears.

Please retest these issues against `master`.  Also note that @brianjuan had reported issues with popupmenu scrolling in iOS that is related to this issue, but was pre-existing and requires a bigger fix.  I've opened #645 for those scrolling related issues.

**Comment by CindyMercadoReyes** [comment]
Hi Ed,  Sending this ticket back over to you. There are still issue with "Hover" when the user clicks on the three button eclipse. Please see screen shot attached. 

![hover error](https://user-images.githubusercontent.com/39101346/44672419-5f41d900-a9f6-11e8-8298-1c21e32955a3.png)

**Comment by EdwardCoyle** [comment]
@CindyMercadoReyes, this one will be ready for the next Q/A round - [this PR](https://github.com/infor-design/enterprise/pull/694) fixes the issue

**Comment by brianjuan** [comment]
Passed QA testing, enhancement is working on all mobile browsers.
http://4100-rc0-enterprise.demo.design.infor.com/components/field-options/example-index
