### ISSUE TITLE
In Model popup date picker's year and month get hide

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#5550]
**Describe the bug**
In Model popup Date picker's header get hide. 

**To Reproduce**

1. Go to 'https://main-enterprise.demo.design.infor.com/components/datepicker/test-modal.html'
2. Click on 'Date Control'
3. See date picker's header get hide.

**Expected behavior**
It should show date picker properly.

**Version**

- ids-enterprise: V4.51.1

**Screenshots**
<img width="582" alt="MicrosoftTeams-image (8)" src="https://user-images.githubusercontent.com/42198413/130801763-25bdbd4f-4ce7-4e13-a759-e7661d19d7da.png">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by yohannahbautista** [comment]
Hello, I checked the link and the page looks different from the screenshot shown, is it the right one? I can't find any "Date Control".
Here's how mine looks
<img width="1344" alt="Screen Shot 2021-09-15 at 9 52 33 AM" src="https://user-images.githubusercontent.com/85279127/133357702-77cbf8cf-11d2-4ccd-abb1-48c071595d21.png">

**Comment by ericangeles** [comment]
@yohannahbautista as we discussed a while ago, you can test it by making the browser's height a little bit smaller around `660px` and the datepicker position should be on top. Or better, use the toolbar device on chrome and test it on mobile device landscape mode.

**Comment by tmcconechy** [comment]
Yeah the key is to make it so that there is more space for the datepicker to open on the top than there is on the bottom for it

**Comment by jbrcna** [comment]
working as expected. moving this to Done. thank you.
verified in https://main-enterprise.demo.design.infor.com/components/datepicker/test-modal.html
![image](https://user-images.githubusercontent.com/56722184/135200055-956ea6a2-7bbc-4221-a7b9-827af451b3a6.png)
