### ISSUE TITLE
Datepicker: The calendar pane of a date picker pops up behind the navigation bar in recent version   

### ISSUE THREAD

**Issue by drirem0** [infor-design/enterprise#5553]
Bug
In previous version of IDS this was not a problem. Now that we upgraded to the latest ng-enterprise, we noticed that the monthly view of the calendar pane of date picker pops up behind the navigation bar as soon as you click on the datepicker.
<img width="1247" alt="calendar pane behind navigation bar" src="https://user-images.githubusercontent.com/34474688/130880537-2e04f440-2d11-4f17-9b8b-97e9d3d7490f.PNG">

HTML Code
Here you see the HTML code of the left hand navigation bar containing the start date component (date from /to). 
<img width="750" alt="navigation bar htmlcode" src="https://user-images.githubusercontent.com/34474688/130880990-c32e7894-fe04-4061-8ce9-1949a75be98c.PNG">

Then this is the html code of the nested date components that are placed on the navigation bar.  The actual calendar component sits in the correct place. The issue arises when you click on the calendar icon to bring up the monthly view., is when this drops BEHIND the navigation bar.
<img width="842" alt="workcenter component" src="https://user-images.githubusercontent.com/34474688/130881037-8fa8e150-82c8-43c3-acbb-4aa06aa16386.PNG">

I did try to see if I was able to manipulate the z-index value of the calendar pane, but not successful in doing so. 
Also, this wasn't an issue in a previous version, whereby the datepicker monthly calendar pane simply pops up on top. 

Please advise. 

Kind Regards

Remco

**Comment by tmcconechy** [comment]
Closing this due to no response and not being able to reproduce
