### ISSUE TITLE
Soho tabs: Tab outline isn't aligned on RTL

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#5554]
**Describe the bug**
When navigating between soho tabs on the following example(https://main-enterprise.demo.design.infor.com/components/tabs/example-composite-form-on-side.html?locale=ar-sa), the focused tab outline doesnt align to the tab. the issue only occurs on rtl.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/example-composite-form-on-side.html?locale=ar-sa
2. Click on any tab
3. navigate to any tabs via keyboard or mouse
4. the nout

**Expected behavior**
outlines should be aligned.

**Version**

- ids-enterprise: v4.51

**Screenshots**
![image](https://user-images.githubusercontent.com/29673378/130907478-038ba987-6556-487a-8c84-d3a1d1af87e3.png)

**Platform**
 - Infor Application/Team Name: Landmark Client
 - Device: (if applicable): NA
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 92.0.4515.159 (Official Build) (64-bit)

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-36225

**Comment by cpinatel7** [comment]
When can we expect a resolution for this generic issue? Thanks

**Comment by tmcconechy** [comment]
Start of Oct release

**Comment by cpinatel7** [comment]
Thanks Tim

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to Done. thank you.
v4.56.0-dev
https://main-enterprise.demo.design.infor.com/components/tabs/example-composite-form-on-side.html?locale=ar-sa#composite-form-messages
![image](https://user-images.githubusercontent.com/56722184/135380286-ed0d8086-a3b5-4e97-98a1-3e97c7e27f8b.png)

**Comment by tmcconechy** [comment]
@JBismonte please make a new issue for this case...
