### ISSUE TITLE
Calendar: Events cross multiple dates not rendering on the same line

### ISSUE THREAD

**Issue by edinfor** [infor-design/enterprise#5556]
**Describe the bug**

events label are not aligned when when crossing multiple dates.

**To Reproduce**

1. events.json
2. go to line 21, change "ends" to `2018-08-23T18:00:00.999`
3. events don't align when crossing multiple dates

**Expected behavior**

**Version**

- ids-enterprise: 4.5.3

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.56.0-dev.
![image](https://user-images.githubusercontent.com/56722184/134485506-30bee815-0c00-4ff4-8df9-dae9278483a9.png)
