### ISSUE TITLE
Timepicker: Timepicker icon not rendered properly on Safari

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5558]
**Describe the bug**
Timepicker icon not rendered properly on Safari

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-Hans (CN/Hant/TW)
2. Click on Timepicker icon
3. See error that the icon doesn't stay inside the textbox

**Expected behavior**
Timepicker icon should stay inside the textbox

**Version**
v4.55.0-dev

**Screenshots**
![Timepicker issue](https://user-images.githubusercontent.com/84306838/131100354-a71a4881-6746-45c3-82bb-9b1df8208ebc.GIF)

**Platform**
Safari

**Additional context**
N/A

**Comment by nganotice** [comment]
Also experienced this issue on: https://main-enterprise.demo.design.infor.com/components/form/example-compact-mode.html

All Timepicker icons in Safari as well.

**Comment by tmcconechy** [comment]
This is a second issue about the same problem. We'll fix it. I think no need to fail or raise anymore issues about icons moving in safari for now until this is solved.

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.56.0-dev.

https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-TW (Hans/Hant/CN)
<img width="337" alt="Screen Shot 2021-09-10 at 4 59 44 PM" src="https://user-images.githubusercontent.com/84306838/132828849-1288dec6-de7a-44f9-a747-c5a94b53f544.png">

Moving this ticket to Done.

Thanks!

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.56.0-dev.

https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-TW (Hans/Hant/CN)

Moving this ticket to Done.

Thanks!
