### ISSUE TITLE
Datagrid - When using groupable row index is incorrect for expand and collapse row events

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise#5559]
**Describe the bug**

Some change has effected the "row" that is omited when the "expandrow" / "collapserow" fires. 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-grouping
1. edit the console log to 
```
        $('#datagrid').on('expandrow', function (e, args) {
         console.log('expandrow', args.row);
        });
```
1. Click on a row and expand/collapse
1. Notice the events fire twice (once with NaN)
1. Ensure the row number is the first row in the group

Also when fixing add `detail` and the new `firstRowIndex` to the NG the types (detail is missing)

**Expected behavior**
Need a way to get the first row index in a group

**Additional context**
TIM: I think what changed is that the aria-rowindex was starting at zero and we changed it to 1 to be correct.

**Comment by tmcconechy** [comment]
Closing stale issues that should be autoclosed
