### ISSUE TITLE
Better demo app examples for the Mask component

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#556]
**Is your feature request related to a problem? Please describe.**
The Demoapp's Mask examples don't distinguish well enough between the Legacy mask samples (which are defined with a `data-pattern` attribute) and the "New" mask samples (which are defined with `patternOptions` inside of the `data-options` attribute).

**Describe the solution you'd like**
We should:

- Do a general upkeep of the Mask component example folder
- Update all "example" pages to use examples of the newer, `data-options` based method, or use JS object settings directly.
- Rename files to clearly label the "legacy" examples as legacy
- Ensure there are clear Number mask tests for both the new and legacy masks.  Ensure that the JS-based option examples on the new tests show a complete representation of the settings object:

```
settings: {
   process: 'number',
   patternOptions: {
      allowDecimals: false,
      integerLimit: 4,
      useThousandsSeparator: true
   }
}
```

**Comment by tmcconechy** [comment]
Also suggest merging the two MD files since they dont show up on design.infor.com.
masked-input.md should go into readme.md

**Comment by tmcconechy** [comment]
Lets finish this up next sprint. At the moment the docs are missing on the design site and it gets the odd question. Not sure how much of the rest of this is done

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
