### ISSUE TITLE
Add new Language Translations for Summer 2018

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#557]
**Is your feature request related to a problem? Please describe.**

Aug 3 i sent strings to the translation team. Once these are sent back this should be added to the sprint to update all the translations.

This will include an updated total of 38 languages. Including new Slovak needed for talent management.

**Comment by tmcconechy** [comment]
Closed via #1299

**Comment by brianjuan** [comment]
https://4130-rc0-enterprise.demo.design.infor.com/components/datepicker/example-index.html?locale=sk-SK
Passed QA testing on all browsers, also tested using other locales. Moving to Done.
