### ISSUE TITLE
Modal: Email required validation is not working

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5571]
**Describe the bug**
Modal: Email required validation is not working

**To Reproduce**

1. Go to http://localhost:4000/components/modal/example-validation
2. Open Modal 
3. Click Type 
4. Click Email 
5. Click Description 
Notice that the email didn't throw the required validation

**Expected behavior**
Email should have a Required Validation 

**Version**
4.55 - ids - dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/131649822-560eeefb-b5a8-4eab-a936-f12ff2dc703e.png)

**Platform**
All major browsers, OS and devices 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
I think it needs

```
{'required': 'keydown change blur', 'email': 'change blur'}
```

**Comment by janahintal** [comment]
QA Passed. Thanks! 
![image](https://user-images.githubusercontent.com/45757016/160120853-ce022b6a-c963-4b3e-82bc-9d03f49192dd.png)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
