### ISSUE TITLE
Calendar: Event label click is captured by date cell first

### ISSUE THREAD

**Issue by edinfor** [infor-design/enterprise#5579]
**Describe the bug**

Cell click event is capturing event label click event.
This replaces the data created for event label click with cell click data.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/calendar/example-index?theme=uplift&variant=light
2. Click on any event
3. Cell click event is triggered before the event click

**Expected behavior**

When clicking on event label, date cell should not capture an event to avoid event override. 

e.g. when clicking on calendar, a popover shows, when clicking on events, I expect to see event details modal, however, since date cell also captured the click, it showed  popover instead of modal.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]
4.55.0-dev

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Think this is the one you fixed

**Comment by edinfor** [comment]
@tmcconechy I didn't fix this one, this one is difficult to fix, I can give a better example later when I finish my current sprint tasks. I fixed https://github.com/infor-design/enterprise/issues/5581

**Comment by tmcconechy** [comment]
Any updates on how to reproduce this @edinfor or should we just close?
