### ISSUE TITLE
Editor: Bullet/Numbered list is cleared when using Clear Formatting, even though its not selected

### ISSUE THREAD

**Issue by eeriksson429** [infor-design/enterprise#5592]
**Describe the bug**
Bulleted and numbered lists are removed when using the Clear Formatting feature in the Editor, even if the lists are not selected. 

**To Reproduce**

1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/test-clear-formatting.html'
2. Make a bullet list and a numbered list below the existing text.
3. Select "Embrace e-commerce action-items, reintermediate, ecologies"
3. Click the Clear Formatting icon. 

**Result**
The formatting of the lists is removed.

**Expected behavior**
The formatting on "Embrace e-commerce action-items, reintermediate, ecologies" is removed. 
The formatting of the unselected text (including the lists) remain.

**Version**
- ids-enterprise: 4.55.0

**Platform**
 - Infor Application/Team Name: Infor Homepages
 - Device: Desktop
 - OS Version: macOS Catalina
 - Browser Name: Chrome
 - Browser Version: 93.0.4577.63 

**Demo**
![demo](https://user-images.githubusercontent.com/69903685/132840972-cbec9138-d69e-467e-8e34-ba3d1f4148ab.gif)

**Comment by tmcconechy** [comment]
Agreed. It should only remove the formatting for what is selected. However, the bullet/number list will be removed from the formatting if it is selected.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
