### ISSUE TITLE
NotificationBadge: Make notification badge applicable to soho buttons (especially menu burger button)

### ISSUE THREAD

**Issue by pgrochowski-infor** [infor-design/enterprise#5594]
**Is your feature request related to a problem or use case? Please describe.**
Notification badge in current form is not applicable to soho buttons.
Also current jQuery wrapper does not provide a way to update badge parameters (position, color, etc).
In other words, the component only extends OnInit and not OnChange and even not OnDestroy (!).
Another very important feature that is missing is an ability to enable/disable badge visibility.

**Describe the solution you'd like**
I'd like the badge to:
- be applicable to soho buttons (especially 'soho-toolbar-flex-nav-button'),
- be applicable to menu items ('accordion-header'),
- to be triggerable (enable/disable visibility),
- have updatable parameters (like position, color)

Actual usecase from WFM can be seen at (bottom slide):
https://www.figma.com/file/v4k6FYW7RokctgnU9MrZuK/IDS-Notification-Badge?version-id=929134509&node-id=0%3A1&viewport=318%2C455%2C0.061992693692445755

**Additional context**
Application: Infor WFM
Used in Angular app.

**Comment by tmcconechy** [comment]
I think what we could do here is make soho-button get some of the settings so it can "add" a notification badge in it.
Also should make the current EP version show it on buttons and hamburger button ect.

**Comment by ericangeles** [comment]
@tjamesallen15 we can discuss more of the fix offline.

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.57.0-beta.

https://4570-beta0-enterprise.demo.design.infor.com//components/button/example-badge.html?theme=new&mode=light
<img width="199" alt="Screen Shot 2021-11-04 at 2 26 40 PM" src="https://user-images.githubusercontent.com/84306838/140423134-80e86222-0d1f-4248-820d-38cfb2662c8e.png">

https://4570-beta0-enterprise.demo.design.infor.com/components/applicationmenu/example-menu-notification.html?theme=new&mode=light
<img width="160" alt="Screen Shot 2021-11-04 at 2 26 48 PM" src="https://user-images.githubusercontent.com/84306838/140423150-653e200f-dc55-440c-862b-954133a6fce5.png">

https://4570-beta0-enterprise.demo.design.infor.com/components/notification-badge/example-enable-disable.html
![3BFFEACC-4A8E-47BE-A353-91E8CBC4A596](https://user-images.githubusercontent.com/84306838/140423176-134991fa-4c1f-4d0f-bd5c-0eb6475386e0.gif)

Moving this ticket to Done.

Thanks!
