### ISSUE TITLE
Icons: Change Launch Icon

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5595]
**Describe the bug**
Updating the launch icon https://jira.infor.com/browse/UXD-2892 to make it less bulky.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/icons/example-index.html
2.Review visuals of launch icon

**Expected behavior**
New icon

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
