### ISSUE TITLE
Mask: large number is incorrectly transposing the number

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#5605]
**Describe the bug**
When entering a large integer number into a list cell, the entered value is being incorrectly transformed with the applied mask. An 11 digit integer number is being transformed from 12345678910 into 123456789100.

**Steps to reproduce the behavior:**

Using the attached 'test-integer-maskoptions.html'
Click on a Batch Number cell
Enter the value of 12345678910 into the cell and tab out
Notice that the number has been transposed to 123456789100
Expected behavior
Mask is correctly applied to the integer number

**Version**

ids-enterprise: v4.54.1-dev

**Additional context**
This is a critical issue for Landmark since the user is unable to enter say a Batch Number correctly or to filter on an 18 digit Batch Number.

Issue was previously reported on #5318.

Is an issue for both List and Form. For the form example could use the following...
Goto https://main-enterprise.demo.design.infor.com/components/locale/test-format-big-negative.html
Enter the value of 12345678910
Click on the Format button

**Comment by tmcconechy** [comment]
FYI if pasting 12345678910 and transforming it was an issue after the original fix https://4541-enterprise.demo.design.infor.com/components//locale/test-format-big-negative.html so its not a regression its an untested/unfixed case.

Will fix and patch in 4.54

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.56.0-dev.

https://main-enterprise.demo.design.infor.com/components/locale/test-format-big-negative.html
![Video 8](https://user-images.githubusercontent.com/84306838/133605414-f49e64dd-f757-4088-94b6-55aac8ba34aa.gif)

Moving this ticket to Done.

Thanks!
