### ISSUE TITLE
Badges: Mobile Enhancements and style changes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5608]
**Describe the bug**
Make some style changes to badges and make it work better on mobile. Based on Demo
https://main-enterprise.demo.design.infor.com/components/badges/example-index.html

**Fixes**
https://www.figma.com/file/v4k6FYW7RokctgnU9MrZuK/IDS-Badge?node-id=203%3A1094

- [x] Badges are not perfect circles (make it 22x22) for circle ones
- [ ] Fix this in web components too if needed

**Additional context**
https://jira.infor.com/browse/UXD-2772

**Comment by davidcarlsonberg** [comment]
@tmcconechy Should changes here be made in Uplift (`*-new.scss`) or the original file?

**Comment by davidcarlsonberg** [comment]
Do web components inherit enterprise in some way or is it a stand alone repo?

**Comment by ericangeles** [comment]
@davidcarlsonberg, it uses the assets of ids-identity (design system) such as design tokens, font files, and icons.

**Comment by tmcconechy** [comment]
It is a standalone repo but as @ericangeles says both do use some colors/tokens from https://github.com/infor-design/design-system

I think the fix would go in the `new.scss` files. The uplift is the old name for `new` and you shouldn't really see it anywhere?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
