### ISSUE TITLE
Cards: Mobile Enhancements and style changes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5609]
**Describe the bug**
Make some style changes to card exampes and make it work better on mobile. Based on Demo

https://main-enterprise.demo.design.infor.com/components/cards/example-variations-hitboxes.html
- 16px spacing on sides

**Fixes**
https://www.figma.com/file/2pHthwwOhchvnpFXp69O7H/IDS-Card?node-id=229%3A10946

- [ ] 16px spacing on sides on the card examples
- [ ] for the main card example it should look close to this:
- [ ] Change this in Web components too

<img width="576" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/814283/135909627-a10177a3-5ed7-42a1-9785-07a7010c8133.png">
**Additional context**

https://jira.infor.com/browse/UXD-2773

**Comment by janahintal** [comment]
Hi @ericangeles, I'm getting different side spaces for scenario 1 & 2. Can you confirm if it is the margin left & right is the one I should be testing for the spaces? I got different spaces on each size for scenario 1 & 2. Thanks!


1.) Test the basic card

Go to http://localhost:4000/components/cards/example-index
Check the .card-header
It should have 16px spaces on both sides


Result: 
Margin Left = 16px 
Margin Right = 2px

![image](https://user-images.githubusercontent.com/45757016/147251996-4df69f3c-1b0b-49e1-8bc5-677584ca5b28.png)

2.) Test the card variations

Go to http://localhost:4000/components/cards/example-variations-hitboxes.html
Card variations should have 16px space on both sides

Result: 0px Margin left and Right
![image](https://user-images.githubusercontent.com/45757016/147252279-2b8ccf72-b60e-44c4-82e9-33677e45ec19.png)



3.) Test the swipe action - **Passed**

Go to http://localhost:4000/components/swipe-action/example-index.html
Toggle the device toolbar in the chrome dev tool
swipe action right button should have 5px border-radius (top right, bottom right) see the Figma design
swipe action left button should have 5px border-radius (top left, bottom left) see the Figma design
Swipe action (left and right) should be wider than before. See the Figma design
Swipe action icon should be 16px x 16px
The contents of it should always be centered
The second line should be truncated

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
