### ISSUE TITLE
Accordion: Mobile Enhancements and style changes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5611]
**Describe the bug**
Make some style changes to accordion examples and make it work better on mobile. Based on Demo
https://main-enterprise.demo.design.infor.com/components/accordion/example-accordion-panels.html

**Fixes**
https://www.figma.com/file/36JA2H9Z6zRnVuj5A6BfdO/Accordion?node-id=0%3A1

- [ ] 44px hitboxes (non visible/size changing)
- [ ] 16px spacing

**Additional context**
https://jira.infor.com/browse/UXD-2767

**Comment by tjamesallen15** [comment]
Hello @tmcconechy ,

I don't have an access for this one. I'm using my infor email
![image](https://user-images.githubusercontent.com/34049950/146871364-fb33a4ec-e671-4fdf-8abc-006d8fe07451.png)

**Comment by tmcconechy** [comment]
I Requested on https://jira.infor.com/browse/IDS-136 @tjamesallen15

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
