### ISSUE TITLE
Swipe Container: Mobile Enhancements and style changes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5615]
**Describe the bug**
Make some style changes to swipe container examples and make it work better on mobile. Based on Demo
https://main-enterprise.demo.design.infor.com/components/swipe-action/example-index.html

Also make these changes in the web component version on a seperate PR.

**Fixes**
https://www.figma.com/file/2pHthwwOhchvnpFXp69O7H/IDS-Card?node-id=229%3A10946

- [ ] 16px spacing on sides
- [ ] show a new variant without icon
- [ ] text box 87px width, overflows into a second  line when it reaches the width max
- [ ] No radius on the button when swiped
- [ ] Make changes in WC too

**Additional context**
https://jira.infor.com/browse/UXD-3375

**Comment by ericangeles** [comment]
@tmcconechy I believe some of these changes have been made, but I see an issue when the button left shouldn't have edges when swiped.

**Comment by CindyMercadoReyes** [comment]
BDD attached.
[BDDStory_github5615.docx](https://github.com/infor-design/enterprise/files/7996034/BDDStory_github5615.docx)
