### ISSUE TITLE
HomePages: More Widget Examples to match docs

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5616]
**Describe the Task**

Total: 28 story points

Should also make an area were all these examples are listable. Perhaps under cards
For example cards/example-widget-status-indicators cards/example-widget-group-action-bar and move the others. And update Docs

This will be broken down later into a few issues.

See https://wiki.infor.com/confluence/pages/viewpage.action?spaceKey=IMH&title=New+Widget+Samples numbers match:

1. Status Indicators
- Fix the fixed width on tags
- Make the Text match the design (the design is correct here?)
- Estimate: 1 pt

2. Group Action Bar
- Design: To be updated to the built one?
- Make the example show a dropdown
- Estimate: 1 pt

3. Data Visualization
- Make an example of a widget with process indicators on it
- Estimate: 2 pt

4. Pagination
- Everything is ok, they are showing the classic theme

5. Load More
- Design: Decide which design to use, suggest using the one with a smaller footer and azure text. So make these changes if agreed on. (seems like the current size)
- See if its possible to hide the footer when not fetching for more speed
- Make a new example showing the text with qty on the right. See if "form-responsive row" can be used with a better way to float left and right text. Also see swipe-container rules.
- Estimate: 3 pt

6. Lazy Loading
- Adjust footer if 5 is agreed on
- Make the example show the indicator by being slowed down (set timeout)
- Estimate: 2 pt

7. Single Line, Text Only
- Add this new example using the new form layout classes we decide on (5)
- Estimate: 2 pt

8. Single Line with Icons
- Add this new example using the new form layout classes we decide on (5)
- Design: Decide on the colors for the icons. I think should be azure?
- Estimate: 1 pt (similar to 7 done at same time)

9. Single Line with Avatar and action icon
- Add this new example using the new form layout classes we decide on (5)
- Design: Icons look too big
- Estimate: 1 pt (similar to 7 done at same time)

10.	Single Line with Numeric Column
- Add this new example using the new form layout classes we decide on (5)
- Show the image placeholder image
- Design: Icons look too big
- Estimate: 2 pt

11.	Single Line with Avatar, Numeric and "More" icon
- Add this new example using the new form layout classes we decide on (5)
- Design: Percent text has bad color contrast
- Estimate: 2 pt (similar to 10 done at same time)

12.	Single Line with Time and Description
- Add this new example using the new form layout classes we decide on (5)
- Estimate: 1 pt (similar to 7 done at same time)

13.	Single Line with Checkbox, Description, Input Field and Numeric
- Add this new example using the new table layout class for widgets
- Estimate: 3 pt

14.	Single Line with Numerical Value
- Add this new example using the new form layout classes we decide on (5)
- We could skip this one as its pretty similar
- Estimate: 1 pt (similar to 7 done at same time)

15.	Double Line with Numeric Column
- Adjust the text styles
- Design: To confirm
- Estimate: 1 pt (similar to 7 done at same time)

16. Double Line with File Type 
- Add example similar to 8
- Estimate: 1 pt (similar to 8 done at same time)

17. Double Line with Avatar, description, hyperlink and action icon
- Add example similar to 11
- Estimate: 1 pt (similar to 11 done at same time)

18. Responsive widget sample 1/2
19. Responsive widget sample 1/2
- Design: Does this need a design/use case/example. For now i would skip
- Estimate: ? pt

20. Charts
- Nothing to do

21. Alerts
- Update the example to match
- Design: Confirm correct styles
- Estimate: 1 pt

22. Kudos
- Make an example to match
- Design: Confirm correct styles (wrong text color on azure)
- Estimate: 2 pt

**Comment by kevinwhitedesign** [comment]
@tmcconechy here's my edits on your list

1. status indicators
Design has the text, and height of list items wrong, needs to add pagination.
Dev needs to match the tags we have.
<img width="1309" alt="Screen Shot 2021-09-17 at 3 41 06 PM" src="https://user-images.githubusercontent.com/6478704/133844759-c7dcb53d-c7be-419c-a8b4-76416cfb6da6.png">

2. group action bar
Design needs to update to match list item height, action bar height, content?, and typography.
Dev could make the example show a popover.
<img width="1318" alt="Screen Shot 2021-09-17 at 3 42 18 PM" src="https://user-images.githubusercontent.com/6478704/133844804-a706ed70-34cf-4026-ad73-051eaa400e3b.png">

3. data vis
Dev to match our 16px "7 of 7 Steps completed" and our 14px "5 Days Remaining" label.
Dev to make a process indicator widget to match ours? Or does design just remove the example?
<img width="1308" alt="Screen Shot 2021-09-17 at 3 42 45 PM" src="https://user-images.githubusercontent.com/6478704/133844849-0a399c22-0b4b-4905-86ec-da7069423605.png">

5. load more
Design to get rid of action bar, Qty 21, make load more a slate value, enlarge list item height.
Dev to change "Compressor 0" to 16px and "Induction" to 14px.
<img width="1295" alt="Screen Shot 2021-09-17 at 3 47 12 PM" src="https://user-images.githubusercontent.com/6478704/133845309-a4e0ad86-ec3f-49a9-8846-efa77889873d.png">

6. lazy loading
No action required by either

7. single line, text only
Design to evaluate value, dev to add example?
<img width="1022" alt="Screen Shot 2021-09-17 at 3 49 47 PM" src="https://user-images.githubusercontent.com/6478704/133845553-0ba1c287-5589-4892-bbc7-a8cbc7a3076c.png">

8. single line, with icons
Design to evaluate value, dev to add example?
<img width="1010" alt="Screen Shot 2021-09-17 at 3 50 24 PM" src="https://user-images.githubusercontent.com/6478704/133845633-b1ae504f-eb7b-4047-b108-925597ae83bb.png">

9. single Line with avatar and action icon
Design to evaluate value, dev to add example?
<img width="1010" alt="Screen Shot 2021-09-17 at 3 51 28 PM" src="https://user-images.githubusercontent.com/6478704/133845749-fe1ad531-1f3a-4d7a-a556-d4dc3f1b6b7f.png">

10. Single Line with Numeric Column
Design to evaluate value, dev to add example?
<img width="1013" alt="Screen Shot 2021-09-17 at 3 52 19 PM" src="https://user-images.githubusercontent.com/6478704/133845854-3a200ad1-ceb0-4819-a4db-39783a8266ea.png">

11. Single Line with Avatar, Numeric and "More" icon
Design to evaluate value, dev to add example?
<img width="1014" alt="Screen Shot 2021-09-17 at 3 53 15 PM" src="https://user-images.githubusercontent.com/6478704/133845971-24a4366d-d4f2-475e-92db-9008fe95de4c.png">

12. Single Line with Time and Description
Design to evaluate value, dev to add example?
<img width="1012" alt="Screen Shot 2021-09-17 at 3 53 50 PM" src="https://user-images.githubusercontent.com/6478704/133846043-8b10a8bf-75b7-4bd1-bf37-77375b7f8523.png">

13. Single Line with Checkbox, Description, Input Field and Numeric
Design to evaluate value, dev to add example?
<img width="1015" alt="Screen Shot 2021-09-17 at 3 54 22 PM" src="https://user-images.githubusercontent.com/6478704/133846093-17f25a53-e85b-47e3-8543-f2d1fc044235.png">

14. Single Line with Numerical Value
Design to evaluate value, dev to add example?
<img width="1009" alt="Screen Shot 2021-09-17 at 3 54 59 PM" src="https://user-images.githubusercontent.com/6478704/133846163-a7ae4dd7-70da-4cc2-bdb9-f64fcc83b2d0.png">

15. Double Line with Numeric Column
Design to address spacing mistakes, make list item height same as dev, and add pagination
Dev to update "8 MILE RESURFACING" to 16px and "City of Detroit" to 14px
<img width="1285" alt="Screen Shot 2021-09-17 at 3 58 44 PM" src="https://user-images.githubusercontent.com/6478704/133846577-66c1ce3e-a080-445b-90a0-ae3f5789dcb6.png">

16. Double Line with File Type
Design to evaluate value, dev to add example?
<img width="1010" alt="Screen Shot 2021-09-17 at 3 58 27 PM" src="https://user-images.githubusercontent.com/6478704/133846545-255f64d7-3dfe-4675-9108-594edca48454.png">

17. Double Line with Avatar, description, hyperlink and action icon
Design to evaluate value, dev to add example?
<img width="1024" alt="Screen Shot 2021-09-17 at 3 59 39 PM" src="https://user-images.githubusercontent.com/6478704/133846687-b854bbeb-d1c9-49e3-a57b-bfe484290a3d.png">

18 - 19 Responsive widget sampleS
No Action Required?
<img width="1325" alt="Screen Shot 2021-09-17 at 4 03 26 PM" src="https://user-images.githubusercontent.com/6478704/133847039-95067495-3716-4277-9cb7-877745a3999b.png">

21. Alerts 
Design to match dev's circle & type styles. Remove the "Latest Alerts" message thing? Unless we have this?
<img width="1307" alt="Screen Shot 2021-09-17 at 4 03 41 PM" src="https://user-images.githubusercontent.com/6478704/133847067-3c500017-09d8-4392-bfbf-63b6201f86c2.png">

22. Kudos
Weird design asset, dev doesn't have this? Do we just remove this or show something else? Anything we want to propose to dev?
<img width="1309" alt="Screen Shot 2021-09-17 at 4 04 06 PM" src="https://user-images.githubusercontent.com/6478704/133847110-c3cbe9d7-11c2-4bce-86d5-1066e4251623.png">

Alright this is just my latest analysis on the gap Emma did with Tim's review combined / edited. I think next steps are for design to meet next week and start making decisions on what makes sense to work on, make tickets, etc. cc @benfenton @danirosefishinfor @lucacolumbu @inforandy @laurensteiger
