### ISSUE TITLE
Datagrid: Current filterMaskOptions are inadequate to control input for filtering numeric and date columns

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5618]
Problem:
Landmark is developing a feature to allow columns to be filtered by more than one filter term.  We are presently using the comma character as the delimiter between filter terms.  So for example on an alpha column the user would be able to enter Apples, Grapes.

If the term itself contains the comma character, the user would need to enclose the filter term with double quotes.  So for example on a numeric column the user would have to enter "1,000.00", "99,999".

We are currently implementing the feature using the filterMaskOptions. However when using the pattern function it only allows control over the individual characters being entered.  If an entered character matches the mask its accepted regardless of whether the input makes sense.

For example, for a date column the user can enter the following and because it matches the mask it is accepted:
' ///// 2015'

For example, for a decimal column the user can enter the following and because it matches the mask it is accepted:
'12-------,,,,,,5959595'

Describe the solution you'd like:
The current column.maskOptions works great for editing a column cell.  Able to expand on it for filterMaskOptions to indicate multiples are allowed with a specified delimiter and whether a space between filter term values is accepted?

Today the only way that I know to allow the user to type in multiples were the delimiter is a comma, is to change the filterType to 'text'.  This is problematic for a date column since changing the filterType from 'date' to 'text' will remove the date icon within the filter cell.

Attached the sample test-filter-mask-options.html to illustrate what I'm currently doing.  Open to other suggestions to resolve.

**Comment by claudenbach** [comment]
[FilterMaskOptions.zip](https://github.com/infor-design/enterprise/files/7173213/FilterMaskOptions.zip)

**Comment by tmcconechy** [comment]
@EdwardCoyle Do you have any ideas how we could do this with maybe some customizations to the existing code so this isnt something we would have to support? I.E. Adding the custom regex/functions

I think this is going be tricky and seems like it would make things a bit complicated to type. What abut just using the multiselect filter instead. This seems better UX to me.

https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html and elimnates the need for this.

<img width="254" alt="Screen Shot 2021-09-16 at 9 32 40 AM" src="https://user-images.githubusercontent.com/814283/133621461-667ae220-66bb-4503-a4fb-2ee13cbcaec6.png">

**Comment by lipetzan** [comment]
Any target sprint or dates on this @tmcconechy ?

**Comment by tmcconechy** [comment]
No, i was waiting for feedback on my proposal of doing it another way using the multiselect to pick multiples. As i think this adds a lot of complexity for one use case. Also wondering of @EdwardCoyle has any suggestions to make this simpler/saner?

**Comment by tmcconechy** [comment]
Discussing this it seems like a really heavy ask. Especially having commas inside values of different types inside values?
Maybe we can come up with a design that doesnt put this all on a mask as this is pretty complex (and probably hard for a user to use).

Lets see if we can come up with a design like maybe a modal with separate inputs? Current mask code is not setup to handle this in any way.
