### ISSUE TITLE
Locale: calling formatNumber with maximumfraction 15 and rounding returns strange number

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#5622]
**Describe the bug**
Calling formatNumber with a maxiumFraction/minimumFraction of 15 and round: true is returning an incorrect value.

**To Reproduce**

1. Copy [test-format-number-15-decimal.zip](https://github.com/infor-design/enterprise/files/7180774/test-format-number-15-decimal.zip) into the codebase
2. Navigate to /components/locale/test-format-number-15-decimal.html
3. Enter the value "123.54"

**Expected behavior**
The value in after calling formatNumber should be "123.540000000000000", not "123.540000000000006"

**Version**

- ids-enterprise: v4.56.0-dev

**Screenshots**
![FormatNumberIssue](https://user-images.githubusercontent.com/22107636/133681257-0f45aa83-f8d5-400e-98c4-a0da3804e3d9.gif)

**Platform**
 - Infor Application/Team Name: LMClient
 - All

**Comment by Sovia** [comment]
This issue happens starting with 14 fraction digits

**Comment by vonnyw** [comment]
![image](https://user-images.githubusercontent.com/39130590/133694257-e027816b-a5ed-4032-a1a4-3e9266986361.png)
 Actually it happens on numbers with high number of precision. It starts breaking when entering more digit before the decimal.

**Comment by tmcconechy** [comment]
Putting this note on:

```
10 digits precision, the maximum digits before the decimal is 7, 
11 digits precision, the maximum digits before the decimal is 5,
12 digits precision, the maximum digits before the decimal is 4,
13 digits precision, the maximum digits before the decimal is 3,
14 digits precision, the maximum digits before the decimal is 2,
15 digits precision, the maximum digits before the decimal is 1,
```

Whats the priority here?

**Comment by tmcconechy** [comment]
Need one more fix which is not working

31.15
- 16 digits on left, 77 decimal should not round to 80
1234567890123456.77 -> 1234567890123456.770000000000000

**Comment by tmcconechy** [comment]
Ok Two more test cases

- go to https://main-enterprise.demo.design.infor.com/components/dropdown/example-validation.html?locale=el-GR
- try:
```
Soho.Locale.formatNumber("1234567890123456.77000000000000000", {style: 'decimal', round: true, minimumFractionDigits: 15, maximumFractionDigits: 15})

Get: '1.234.567.890.NaN.000.000.000.000.000'
Expect: '1.234.567.890.123.456,770000000000000'
```
- try:
```
Soho.Locale.formatNumber('1234567890123456.77', { decimal: '.', group: '', maximumFractionDigits: 15, minimumFractionDigits: 15, round: false, style: 'decimal'})
```
Get: "123456789012345677.000000000000000"
Expectin: "1234567890123456.77000000000000000"
```

**Comment by janahintal** [comment]
QA Passed. Working as expected on my end. 
Verified in https://main-enterprise.demo.design.infor.com/components/dropdown/example-validation.html?locale=el-GR
https://main-enterprise.demo.design.infor.com/components/locale/test-big-number.html

![image](https://user-images.githubusercontent.com/45757016/134511843-e553bc1a-e428-4e8e-96b0-c721e5923a87.png)
![image](https://user-images.githubusercontent.com/45757016/134511880-5c88e2a8-f2eb-4065-9f77-157d951eeb1a.png)
