### ISSUE TITLE
Icons: Some look very different/strange in 4.55.0 (Classic)

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#5624]
**Describe the bug**
Some icons turned very bulky / large when updating to v4.55.0. Not sure if this is intentional? Some of them really stand out. They seem to look OK in the new theme, but not in classic which we are using.

**To Reproduce**
Compare these two
https://design.infor.com/code/ids-enterprise/latest/demo/components/icons/example-index?theme=classic&mode=light&colors=2578a9

https://design.infor.com/code/ids-enterprise/4.54.0/demo/components/icons/example-index?theme=classic&mode=light&colors=2578a9

First link is v4.55.0, second link is v4.54.0. The `svg` tag is the same, but the `use` tag within is a lot larger in v4.55.0. I see no change related to icons in the changelog.

**Version**
- ids-enterprise: v4.55.0

**Screenshots**
Just some of the most noticeable changes highlighted below, but as you can see the size/thickness is very different across all of them.
![image](https://user-images.githubusercontent.com/1101770/133746863-2cca8e53-40a8-4fad-862e-a9085de76570.png)

**Comment by tmcconechy** [comment]
Compare https://main-enterprise.demo.design.infor.com/components/icons/example-index.html?theme=classic&mode=light&colors=2578a9
To https://4540-enterprise.demo.design.infor.com/components/icons/example-index.html?theme=classic&mode=light&colors=2578a9

CC @elizabethhartley @kevinwhitedesign

FYI the change was https://github.com/infor-design/design-system/blob/main/docs/CHANGELOG.md#v460-fixes 
I added an entry to the enterprise change log as well

**Comment by tmcconechy** [comment]
We have identified the issue and are testing the fix. Expect a patch Monday

**Comment by tmcconechy** [comment]
![Screen Shot 2021-09-20 at 9 55 09 AM](https://user-images.githubusercontent.com/814283/134014618-f29a6251-d0b4-4d73-871b-e8878ee15084.png)

Ok this is the result with the new updates. I think its good now. The problem was a change to the view boxes.

Just posting for another set of eyes

**Comment by tmcconechy** [comment]
@volante007 This issue is now patched in NG 10.6.2 -> which contains EP 4.55.2 -> which contains ids-identity 4.7.5 with fixed icons.

The issue was that when we changed from sketch to figma the old icons had the wrong viewBox sizes

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.56.0-dev.

https://main-enterprise.demo.design.infor.com/components/icons/example-index.html?theme=classic&mode=light&colors=2578a9
<img width="1578" alt="Screen Shot 2021-09-23 at 6 58 34 PM" src="https://user-images.githubusercontent.com/84306838/134496290-20765344-40ed-48df-8112-11482a72584e.png">

Moving this ticket to Done.

Thanks!

**Comment by volante007** [comment]
Hi,

All standard icons look good now, thanks!

We noticed that all tree icons are smaller than before, and some icons from the extended icons set. Not sure if those changes are intentional, or if accidental viewBox changes there as well? Not critical for us, but perhaps needs to be fixed as well?

Difference can be seen in my two links in OP.

**Comment by tmcconechy** [comment]
Pushing a fix to the tree css. The icons are correct but the css doesnt match anymore. Good catch

**Comment by nganotice** [comment]
This has been QA tested on v4.56.0-dev.

Compared https://main-enterprise.demo.design.infor.com/components/tree/example-index.html to https://4350-enterprise.demo.design.infor.com/components/tree/example-index.html

**1st - New & Vibrant**
![Screen Shot 2021-10-01 at 5 56 40 PM](https://user-images.githubusercontent.com/84306838/135601856-dec62780-456b-4358-88bd-26d2b91986d4.png)

**2nd - Classic & Subtle**
![Screen Shot 2021-10-01 at 5 56 40 PM](https://user-images.githubusercontent.com/84306838/135601875-a1098fc7-26f4-4a30-9e69-cb9580efb640.png)
