### ISSUE TITLE
Dropdown: Incorrect border color for required & disabled dropdown fields

### ISSUE THREAD

**Issue by eeriksson429** [infor-design/enterprise#5630]
**Describe the bug**
Dropdown fields that are required & disabled gets gray border instead of red. 

**To Reproduce**
1. Create a required dropdown field.
2. Disable it.

OR

Open https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/example-index?theme=classic&mode=light&colors=2578a9 and add the following classes to the div.dropdown element: "error is-disabled". 

**Expected behavior**
The dropdown field gets a red border.

**Actual result** 
The border is gray. 

There seems to be a rule for disabled required dropdown fields to get the red border color, but it is overwritten by the styling for the disabled state. See attached screenshot. Please advise if this is by design or not. 

**Version**
- ids-enterprise: 4.55.2

**Screenshots**
<img width="447" alt="Screenshot 2021-09-21 at 13 55 32" src="https://user-images.githubusercontent.com/69903685/134167278-bf5ad78a-c628-4072-b145-b34b6381cfe0.png">

**Platform**
 - Infor Application/Team Name: Infor Homepages
 - OS Version: macOS Catalina
 - Browser Name: Chrome
 - Browser Version: Version 93.0.4577.82 (Official Build) (x86_64)

**Comment by tmcconechy** [comment]
I think the example you want to https://main-enterprise.demo.design.infor.com/components/dropdown/example-validation.html if you select blank and tab out then it is red.

I tested this for disabled fields and i see the issue. I just dont think we ever considered this a plausable use case. Any reason to show an error they cant fix on a field that is disabled?

**Comment by eeriksson429** [comment]
We don't really have a specific use case for this, it's only part of one of our test widgets used to verify Homepages when we upgrade the components to the latest version. So nothing major on our end. Just wanted to clarify if this was by design or not.

**Comment by tmcconechy** [comment]
No not on purpose i guess if it had an error and then became disabled it should show in a disabled red color? But we would have to add this as a "feature".

**Comment by eeriksson429** [comment]
From our side it's not needed to add that feature/make the change. We can close this!

**Comment by tmcconechy** [comment]
I'll make it minor for now. See if it comes up again. Its a bug but with a weird use case i guess.
May descope later.

**Comment by eeriksson429** [comment]
Sounds good! Thanks Tim.

**Comment by tmcconechy** [comment]
Closing for now :)
