### ISSUE TITLE
TreeGrid: selectedRows is reporting incorrect indexes, occurs after updating tree data with rows selected

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5631]
Describe the bug
A tree grid with select of 'mixed' is reporting incorrect selected row indexes.  Occurs when row(s) are selected and then the tree is updated following an expand action that inserts additional rows into the tree.  

1. Using the attached test-tree-selected-rows-idx.html
2. Click on the checkbox for 'Z' row
3. Click on the expand icon for 'A' row
4. Click on the checkbox for 'AA' row
5. Click on the expand icon for 'AA' row
6. Click on the checkbox for 'BBB' row
7. Click on Selected Rows Idx button on the toolbar and notice the reported indexes

Refresh the browser
1. Click on the expand icon for 'A' row
2. Click on the expand icon for 'AA' row
3. Click on the checkbox for 'AA' row, 'BBB' row, 'Z' row
4. Click on Selected Rows Idx button on the toolbar and notice the reported indexes

Expected behavior:
The method selectedRows() returns the valid idx for the selected rows.

Seems like the internal global variable _selectedRows needs to be updated when rows are added to the treeGrid following an expand row to accurately reflect the actual row index.

Version
- ids-enterprise: v4.55.0-dev

**Comment by claudenbach** [comment]
[Git-5631.zip](https://github.com/infor-design/enterprise/files/7204269/Git-5631.zip)

**Comment by tmcconechy** [comment]
The selected rows do behave a bit different in the tree because the data is changed. But we will have a look at this when we can.

**Comment by claudenbach** [comment]
Thanks!  I do have a customer ticket tied to this issue.  The only workaround I could come up with is to make the selections after the tree has been expanded to include the necessary rows.

**Comment by tmcconechy** [comment]
@deep7102 can take a look and see how complicated this is

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.56.0-dev.

https://main-enterprise.demo.design.infor.com/components/datagrid/test-tree-selected-rows-idx.html
![Screen Recording 2021-09-23 at 5 58 06 PM](https://user-images.githubusercontent.com/84306838/134498276-37a09006-420f-49db-9044-b12520e679c4.GIF)

Moving this ticket to Done.

Thanks!
