### ISSUE TITLE
Dropdown: noSearch dropdowns do not clear searchMatches when selecting a different value with mouse or JS

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#5632]
**Describe the bug**
When a noSearch dropdown has values that start with the same character, and the dropdown changes the value by not using the keyboard, the previously typed key is still remembered. That is confusing, but @EdwardCoyle knows what I'm talking about! The steps to reproduce will explain better.

**To Reproduce**

1. Go to /components/dropdown/example-no-search.html
2. Type "t" to select "Two"
3. Use the mouse to select "Five" or use $('#nosearch-dropdown').val('15').trigger('updated') to do it programatically
4. Type "t"
5.  Note that "Three" was selected in the dropdown

**Expected behavior**
"Two" should have been selected

**Version**

- ids-enterprise: 4.51.1

**Platform**
 - Infor Application/Team Name: Lawson

**Additional context**
We have customers hitting this. They had to modify their absence forms to include COVID 19, which they did by prepending C19 to all of their dropdown options. They end up having something like this
* Absence
* C19 - absence
* C19 - extended
* C19 - something else
* Extended
* Something else

After they submit a form, we clear all values to prepare for the next. When a user then goes to that field, and types "C" to selected "C19 - absence", it is actually selecting the next one in the list, causing them to enter a bunch of incorrect data.

The function firstOptionStartingWith in dropdown never clears out searchMatches when selecting other values if not using the keyboard.

**Comment by awbuboltz** [comment]
Hey Ed, any update on this?

**Comment by tmcconechy** [comment]
Its planned for this Nov sprint to be released early Dec

**Comment by awbuboltz** [comment]
Thanks Tim.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by s-werking** [comment]
Hi @tmcconechy,

This fix works well for dropdown options that have letters, but this issue also exists for dropdowns that have multiple digits.
[example-no-search-lsf.zip](https://github.com/infor-design/enterprise/files/7671654/example-no-search-lsf.zip)

Steps to reproduce in the given sample:
1. Open the top dropdown
2. Type '0'
Expected Result: 01 will be focused
3. Select any value to close the dropdown
4. Open the dropdown
5. Type '0'
Expected Result: 01 should be focused
Actual Result: 02 is focused

Thanks!

**Comment by tmcconechy** [comment]
@yohannahbautista can you take another look at the extra case added by @s-werking ?

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.59.0-dev.

https://main-enterprise.demo.design.infor.com/components/dropdown/example-no-search.html

![Video 22](https://user-images.githubusercontent.com/84306838/145938075-3664f756-ea3c-43cf-928d-7b0421cff150.gif)

Moving this ticket to Done.

Thanks!
