### ISSUE TITLE
Line: If all data points are zero the line is centered

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5640]
**Describe the bug**
 If all data points are zero the line is centered. This regressed between 4.51 and 4.55 so should dig into it from that direction.
 
**To Reproduce**
1. Edit https://github.com/infor-design/enterprise/blob/main/app/views/components/line/example-zero-millions.html#L22-L26 so that all the data is zero i.e.
```
    var dataset = [{
      "data":[
        {"name":"08/30/17","value": 0},
        {"name":"09/29/17","value": 0},
        {"name":"10/30/17","value": 0},
        {"name":"11/30/17","value": 0},
        {"name":"12/28/17","value": 0}],
      name: 'Component C'
    }];
```
3. Run page

**Expected behavior**
Should work as in 4.51 version where line is at the bottom

**Version**
- ids-enterprise: [4.51 to 4.55]

**Screenshots**

![Screen Shot 2021-09-22 at 11 57 06 AM](https://user-images.githubusercontent.com/814283/134379057-181d903e-460a-437a-be9c-877a6124c7c1.png)

**Additional context**
https://jira.infor.com/browse/LIME-7092

**Comment by tmcconechy** [comment]
Looking at the history maybe either this was a change by @deep7102 or @ericangeles 
https://github.com/infor-design/enterprise/commits/main/src/components/line/line.js

Any ideas?

**Comment by ericangeles** [comment]
@tmcconechy I am not sure about this issue before but I can take look at it.

**Comment by tmcconechy** [comment]
Yes please. I would check the history a bit https://github.com/infor-design/enterprise/commits/main/src/components/line/line.js

Deepak told me he doesnt think it was his change? Maybe when we added the combined line / bar chart?

**Comment by ericangeles** [comment]
@tmcconechy I haven't PR yet the combine line and column chart.

**Comment by tmcconechy** [comment]
oh my mistake still might be something in the recent history https://github.com/infor-design/enterprise/commits/main/src/components/line/line.js

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
