### ISSUE TITLE
Header: Wizard focus is not centered or aligned

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5646]
**Describe the bug**
Header: Wizard focus is not centered or aligned

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-wizard-alternate.html?theme=new&mode=light&colors=0066D4
2. Click the wizard to focus
3. Notice the focus is not centered
4. Try to minimize the screen and check alignment

**Expected behavior**
Focus should be centered

**Version**
4.56-ids-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/134508875-e07fe8db-6719-4d9a-b183-10cdd5a5d909.png)

**Platform**
Windows 10 
Chrome
& all major browsers and devices.

**Additional context**
N/a

**Comment by tmcconechy** [comment]
<img width="216" alt="Screen Shot 2021-09-23 at 9 11 44 AM" src="https://user-images.githubusercontent.com/814283/134513034-f7646007-61fe-46d9-8d91-e6adcabcb209.png">

You mean this focus right?

**Comment by tmcconechy** [comment]
closing this as not 100% able to reproduce anymore. also too minor as we are redoing this component
