### ISSUE TITLE
Checkboxes: Checkboxes are disabled after changing Versions/Modes/Colors

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5648]
**Describe the bug**
Checkboxes are disabled after changing Versions/Modes/Colors

**To Reproduce**Steps to reproduce the behavior:
1. Go to https://main-enterprise.demo.design.infor.com/components/checkboxes/example-checkbox-groups.html (All examples)
2. Click on more actions
3. Pick any Versions/Modes/Colors
4. See error that the checkboxes disables

**Expected behavior**
After picking the Versions/Modes/Colors the checkboxes shouldn't be disabled

**Version**
v4.56.0-dev

**Screenshots**
**Versions:**
![Screen Recording 2021-09-24 at 7 11 52 PM](https://user-images.githubusercontent.com/84306838/134666587-1912bdc0-1546-4a53-bafd-c2a11e55e0f3.GIF)

**Modes:**
![Screen Recording 2021-09-24 at 7 12 35 PM](https://user-images.githubusercontent.com/84306838/134666604-bf6a31a7-009c-4511-a185-140756a7b8f4.GIF)

**Colors:**
![Screen Recording 2021-09-24 at 7 13 00 PM](https://user-images.githubusercontent.com/84306838/134666623-a3d4b258-54bb-44e7-80a8-43a11a8d3aaa.GIF)

**Platform**
-All browsers/mobile devices

**Additional context**
N/A

**Comment by nganotice** [comment]
Found the same issue w/ CAP - Checkbox is disabled after changing Versions/Modes/Colors (https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html)

![Video 9](https://user-images.githubusercontent.com/84306838/134888939-3576b279-7334-4177-8ad8-ad7b47a47142.gif)

**Comment by tmcconechy** [comment]
this should be fixed by PR https://github.com/infor-design/enterprise/pull/5652 (it is the same issue as you noted 👍🏻  )

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.56.0-dev.

**Checkboxes** - https://main-enterprise.demo.design.infor.com/components/checkboxes/example-horizontal.html
![Video 12](https://user-images.githubusercontent.com/84306838/135399838-66255360-9a1c-49f9-b19a-0abc11a6194d.GIF)

**Contextualactionpanel** - https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html
![Video 11](https://user-images.githubusercontent.com/84306838/135399897-6faaaa7c-5723-40c9-992a-dea9454fd462.GIF)
 
Moving this ticket to Done!

Thanks!
