### ISSUE TITLE
Hierarchy support for context menu and detail fields

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#565]
**Describe the solution you'd like**
Hierarchy control needs ability to display actions related to a specific node. (IE context menu). Need ability to display detail fields for some applications. In 3.5 this was achieved via the popupmenu. This has been designed as a context/detail fields combo for 4.0.

[Detail Fields - Org Chart with Paging.pdf](https://github.com/infor-design/enterprise/files/2263667/Detail.Fields.-.Org.Chart.with.Paging.pdf)

**Comment by tmcconechy** [comment]
This fix was merged
