### ISSUE TITLE
Homepage: Charts are misaligned in mobile mode

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5650]
**Describe the bug**
Homepage: Charts not rendered properly inside circle pager

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html
2. Minimize the screen 
3. Click the next page in circle pager

**Expected behavior**
Chart should b rendered properly

**Version**
4.56-ids-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/134668104-a7913ef9-a6ae-40b3-8ad5-54441ad752ec.png)

**Platform**
Windows 10
Chrome & all major browsers & OS

**Additional context**
N/a.

**Comment by janahintal** [comment]
The issue still exists. Kindly see screenshots below.
![image](https://user-images.githubusercontent.com/45757016/135455081-23c2796b-9a96-430b-adf6-b8b0d52d7291.png)
![image](https://user-images.githubusercontent.com/45757016/135455103-7f9a9dd3-ed6d-49df-a2ee-30d3ac5b9726.png)

**Comment by yohannahbautista** [comment]
> The issue still exists. Kindly see screenshots below. ![image](https://user-images.githubusercontent.com/45757016/135455081-23c2796b-9a96-430b-adf6-b8b0d52d7291.png) ![image](https://user-images.githubusercontent.com/45757016/135455103-7f9a9dd3-ed6d-49df-a2ee-30d3ac5b9726.png)

@janahintal Hello, the new changes should reflect on the page now, can you try again? Thanks

**Comment by janahintal** [comment]
Hi @yohannahbautista, this is now working on my end. Will now move this to Done. Thank you! 👍 

https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html?theme=classic&mode=light&colors=2578a9
![image](https://user-images.githubusercontent.com/45757016/135625353-53b38dfc-5011-49db-be7c-445a6e16fea5.png)
![image](https://user-images.githubusercontent.com/45757016/135625381-e8054a7f-6a3b-4520-9072-812804c2a8fe.png)
![image](https://user-images.githubusercontent.com/45757016/135625400-710dfa2d-0e17-421d-bc41-7a6533047c37.png)
