### ISSUE TITLE
Adjust location of input + .busy-indicator-container .busy-indicator in compact mode.

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#5655]
**Describe the bug**
Busy indicator is displaying outside field boundary when in compact mode

**To Reproduce**
1. Go to /busyindicator/example-inputs.html and add `form-layout-compact` class to `div.page-container`
2. Click the load button under each field
3. See input busy indicator display too low in the field
The top margin is 6px. Making it 3px seems to solve it. 

**Expected behavior**
Adding a rule like this seems to fix the issue. 
```
.form-layout-compact input + .busy-indicator-container,
.form-layout-compact .dropdown-wrapper > .busy-indicator-container {
  position: absolute;

  .busy-indicator {
    height: 18px;
    margin-top: 5px;

    .bar {
      height: 18px;
    }
  }
}
```

**Version**
4.55

**Screenshots**

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: latest 64  bit

**Additional context**

**Comment by tmcconechy** [comment]
Sounds fine to me. Feel free to PR, or we will add it next sprint

**Comment by pwpatton** [comment]
@tmcconechy I have a branch for the changes. Are these changes ok by themselves are do you need examples?

**Comment by tmcconechy** [comment]
Maybe a quick test page would be good. So we could add a test plan for it

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.56.0-dev.

Busyindicator's now centered - https://main-enterprise.demo.design.infor.com/components/busyindicator/example-inputs-compact.html
![Video 15](https://user-images.githubusercontent.com/84306838/135995054-09fe5b34-b9ab-4e49-9cb5-c8e33f6e78ac.gif)

Moving this ticket to Done.

Thanks!
