### ISSUE TITLE
Contextualactionpanel: CAP not rendered properly

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5658]
**Describe the bug**
CAP not rendered properly

**To Reproduce**Steps to reproduce the behavior:
1. Go to https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html
2. Click on Open Markup-Based Contextual Action Panel button
3. See error that the CAP isn't rendered properly

**Expected behavior**
CAP should be rendered properly

**Version**
v4.56.0-dev

**Screenshots**
![Video 10](https://user-images.githubusercontent.com/84306838/134892605-90d63a2a-cdbe-4e0a-976c-31ce07735462.gif)

**Mobile**
<img width="304" alt="Screen Shot 2021-09-27 at 6 29 47 PM" src="https://user-images.githubusercontent.com/84306838/134892147-dd0e6e1d-3265-4299-b347-eecb8fd6f9dd.png">

**Platform**
-All browsers/mobile devices

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Seems like its been doing this for a while. We may just need to set the widths on this dialog

**Comment by davidcarlsonberg** [comment]
Cannot reproduce. Most likely solved by the PRs addressed within this issue: https://github.com/infor-design/enterprise/issues/6065

**Comment by tmcconechy** [comment]
yes i remember we fixed this.. thanks @davidcarlsonberg

**Comment by janahintal** [comment]
QA Passed. Thanks! Verified in https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html 
![image](https://user-images.githubusercontent.com/45757016/161002895-b245b52f-fd17-4ab7-91f0-8cafc3067c6f.png)
