### ISSUE TITLE
Datagrid: Add option to excel export to use the current locale

### ISSUE THREAD

**Issue by NewCoffee1** [infor-design/enterprise#5663]
**Is your feature request related to a problem or use case? Please describe.**
Hi IDS-Team,

While i'm working with the AppBuilder and the AppHub, i mentioned that the app doesn't take the locale from my browser (as every other application from the CloudSuite does). This is a bigger problem for the export function (to excel). Some formattings are not available (e.g. the Decimal separator (,) and 1000 separator (.) As usual in Germany) and have to be done after the excel export. When i set up different apps, i don't want the user to format the data after export.

Therefore i request you to improve your export functionality to take locale into consideration, so that after that the AppBuilder Team can implement a way for users to change the locale in app builder. 
Right now the export function just takes the data from the grid with no formatting.

The best way would be that the application takes the locale from the browser or i can set it in the app configurations.
I explained the problem in ticket 15714463 on the Infor Concierge Portal.

Please work on this issue because it will increases the attractiveness of the app. Otherwise it becomes unusable in many cases.

Thanks

**Describe the solution you'd like**
Add an option so that the export to excel uses the current locale when exporting dates/numbers.

**Describe alternatives you've considered**
End user has to do it everytime which is a pain.

**Additional context**
AppBuilder and the AppHub

**Comment by tmcconechy** [comment]
When filing issues please use the issue template https://github.com/infor-design/enterprise/issues/new/choose you could edit this issue to form into the markdown template for enhancements?

We do not automatically take the browsers locale as not everyone wants this. But you can easily read the browser locale and call `Soho.Locale.set(navigator.language)`.

I'm also not sure its a very good idea to change the export to use the locale. I would have to be convinced as this is a breaking change. And what we would be doing is formatting dates and numbers to strings. So it would make it difficult to use excel functions on the columns.

I suggest that you just use the excel features to format the numbers and dates.

Will keep this open for now tho for further discussion.

**Comment by NewCoffee1** [comment]
Can i use Soho.Locale.set(navigator.language) i a MultiTenant environment?

It's not possible to format the numbers to a german format in the App. So it's necessary to format it in excel. I think this isn't the way we should work with an CloudSuite. The enduser has to format it every time he uses the export function.

**Comment by tmcconechy** [comment]
The problem is that it takes the unformatted data now. So would have to add an option that takes the data out of the table UI view instead.

**Comment by jbrcna** [comment]
this is now working as expected.
v4.58.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/example-export-format.html

I'd just like to clarify if this is the correct behavior.
`observation 1: the Extra column 5th row doesn't have 'ية (مصر' when export as excel`
![image](https://user-images.githubusercontent.com/56722184/144382962-a15a3513-281f-4aa9-9dd5-4559409579bc.png)

`observation 2: using de-DE locale, 2345 is formatted as '2.345'`
![image](https://user-images.githubusercontent.com/56722184/144383281-206768c2-12cf-497d-b2b2-bebef72518e5.png)


`observation 3: using ar-SA, 500 is aligned right. should be left?` 
_(assumption: all numbers including 2345 is aligned left)_
![image](https://user-images.githubusercontent.com/56722184/144383843-24a49a08-e9ef-4a06-aca9-6364c8a61a44.png)

**Comment by nganotice** [comment]
I've also noticed that after picking any locale from the dropdown - the link lands on http://localhost:4000/components/datagrid/example-export-format.html?locale=en-US 

![Video 21](https://user-images.githubusercontent.com/84306838/144514414-5b30be8c-4d32-45a7-895f-57de9bf979dd.gif)

CC @tmcconechy @ericangeles

**Comment by ericangeles** [comment]
It looks like the base URL sets statically. To fix this, you can use `window.location.host` to get the base URL of the page.

**Comment by tmcconechy** [comment]
Also you can change the locale without reloading the page. I think you would just call
```
Locale.set()
```
And then rerender() on the datagrid?

Maybe thats better for a follow up fix?

**Comment by jbrcna** [comment]
**QA Failed**. v4.59.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/example-export-format.html
![Large GIF (946x544)](https://user-images.githubusercontent.com/56722184/145949108-1c6322d0-931a-47d6-8ecd-da5e86fe3904.gif)

**Comment by tmcconechy** [comment]
This should be fixed on next deploy....

**Comment by jbrcna** [comment]
We'll do a retest again on this on next deploy. thanks @tmcconechy

**Comment by tmcconechy** [comment]
Its there now https://main-enterprise.demo.design.infor.com/components/datagrid/example-export-format.html and seems working @jbrcna

**Comment by jbrcna** [comment]
Thanks @tmcconechy . this is what I see on my end. I might be missing something. there's no error in console
![Large GIF (1084x568)](https://user-images.githubusercontent.com/56722184/146301081-29a1f2a6-189e-4dda-93f6-044f9ac731e7.gif)

the export functionality is working. however, there's a bit of a delay when changing locale using dropdown. Also the url/link is not changing. I assume that it should also change as well, but if it is by design, will mark this ticket Pass
![image](https://user-images.githubusercontent.com/56722184/146302620-56614523-a7d4-4f55-8238-d88317a352ba.png)

![image](https://user-images.githubusercontent.com/56722184/146305043-2ca7ebb3-7894-47bf-9678-f5df610c2e94.png)

**Comment by tmcconechy** [comment]
@yohannahbautista @jbrcna Yes i see something wierd in the example. If you change the locale say 3 times it always shows the previous locale not the one you just changed it to? A bit confusing so maybe we should fix that in the example too 👍🏻

**Comment by CindyMercadoReyes** [comment]
BDD Attached.
[BDDStory_github5663.docx](https://github.com/infor-design/enterprise/files/7728592/BDDStory_github5663.docx)

**Comment by jbrcna** [comment]
this is now working as expected. thank you! v4.59.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/example-export-format.html

**Comment by NewCoffee1** [comment]
What means Enterprise 4.59.x (Dec 2021) Sprint? When will this function be available?

**Comment by EdwardCoyle** [comment]
@NewCoffee1 this one is available in the current release: https://github.com/infor-design/enterprise/releases/tag/4.59.3

**Comment by NewCoffee1** [comment]
This means for MT customers it will be available after the february update?

**Comment by tmcconechy** [comment]
Sorry @NewCoffee1 i dont know what that means about Mt customers and Feb update.... All i can say is the fix was already released in Jan and should still be fixed in the upcoming monthly release
