### ISSUE TITLE
datagrid indeterminate paging - previous page fails if initially loaded data is in the middle of the set of records

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#567]
**Describe the bug**
There is an case where the source(req.type === prev) doesn't get called.  If you load a page of records that isn't the first page (req.firstPage/lastPage both equal false) and click previous the source function is never called. 

**To Reproduce**
1. save example on next comment as example-previssue.html to your project.
2. open example-previssue.html in your browser
3. notice a page of recs is displayed (to illustrate loading a page of recs from the middle of a dataset).
4. click previous page and notice request type is never called on the datagrid source function.

**Expected behavior**
The source(req.type === 'prev') should be called in this case.

**Platform**
 - OS Version: Windows 10
 - Browser Name: chrome
 - Latest build

**Additional context**
This is only an issue with indeterminate paging AFAIK

**Comment by pwpatton** [comment]
`

<div class="row">
  <div class="twelve columns">
    <div id="datagrid">
    </div>
  </div>
</div>

<script>
  $('body').one('initialized', function () {
    var data, columns;

    //Init and get the api for the grid
    $('#datagrid').datagrid({
      columns: getColumns(),
      paging: true,
      pagesize: 5,
      indeterminate: true,
      source: dataSource
    });

    function dataSource(request, response) {
      if (request.type === 'initial') {
        // set activePage to -1 so only pagingRequest.firstPage and pagingRequest.lastPage
        // are solely used to determine whether paging bar button should be enabled/disabled
        request.activePage = -1;
        request.firstPage = false;
        request.lastPage = false;
        response(getData(), request);
      } else if (request.type === 'prev') {
        // click previous button, notice this function is never reached.
        alert('someone clicked previous');
      }
    }

    function getColumns() {
      if (!columns) {
        columns = [
          { id: 'selectionCheckbox', sortable: false, resizable: false, width: 50, formatter: Formatters.SelectionCheckbox, align: 'center' },
          { id: 'productId',   name: 'Product Id',   field: 'productId',   sortable: false, filterType: 'integer', width: 140, formatter: Formatters.Readonly                     },
          { id: 'productName', name: 'Product Name', field: 'productName', sortable: false, filterType: 'text',    width: 150, formatter: Formatters.Hyperlink                    },
          { id: 'activity',    name: 'Activity',     field: 'activity',    sortable: false, filterType: 'text',    width: 125,                                      hidden: true  },
          { id: 'quantity',    name: 'Quantity',     field: 'quantity',    sortable: false,                        width: 125                                                     },
          { id: 'price',       name: 'Price',        field: 'price',       sortable: false, filterType: 'decimal', width: 125, formatter: Formatters.Decimal                      },
          { id: 'orderDate',   name: 'Order Date',   field: 'orderDate',   sortable: false, filterType: 'date',                formatter: Formatters.Date, dateFormat: 'M/d/yyyy' }
        ];
      }

      return columns;
    }

    function getData() {
      if (!data) {
        data = [
          { id: 0,  productId: 214220, productName: 'Compressor 1',  activity: 'Assemble Paint', quantity: 1,    price: 210.99,             status: 'Active',   orderDate: '2015-01-01T06:00:00.000Z', action: 'Action', rated: .32  },
          { id: 1,  productId: 214221, productName: 'Compressor 2',  activity: 'Assemble Paint', quantity: 1.5,  price: 209.99,             status: 'Late',     orderDate: '2015-01-02T06:00:00.000Z', action: 'Action', rated: .76  },
          { id: 2,  productId: 214222, productName: 'Compressor 3',  activity: 'Assemble Paint', quantity: 2,    price: 208.99,             status: 'Active',   orderDate: '2015-01-03T06:00:00.000Z', action: 'Action', rated: .32  },
          { id: 3,  productId: 214223, productName: 'Compressor 4',  activity: 'Assemble Paint', quantity: 2.5,  price: 207.99,             status: 'Inactive', orderDate: '2015-01-04T06:00:00.000Z', action: 'Action', rated: .53  },
          { id: 4,  productId: 214224, productName: 'Compressor 5',  activity: 'Assemble Paint', quantity: 3,    price: 206.99,             status: 'Inactive', orderDate: '2015-01-05T06:00:00.000Z', action: 'Action', rated: .42  },
          { id: 5,  productId: 214225, productName: 'Compressor 6',  activity: 'Assemble Paint', quantity: 3.5,  price: 205.99,             status: 'Inactive', orderDate: '2015-01-06T06:00:00.000Z', action: 'Action', rated: .88  },
        ];
      }

      return data;
    }
  });
</script>

`

**Comment by pwpatton** [comment]
```

<div class="row">
  <div class="twelve columns">
    <div id="datagrid">
    </div>
  </div>
</div>

<script>
  $('body').one('initialized', function () {
    var data, columns;

    //Init and get the api for the grid
    $('#datagrid').datagrid({
      columns: getColumns(),
      paging: true,
      pagesize: 5,
      indeterminate: true,
      source: dataSource
    });

    function dataSource(request, response) {
      if (request.type === 'initial') {
        // set activePage to -1 so only pagingRequest.firstPage and pagingRequest.lastPage
        // are solely used to determine whether paging bar button should be enabled/disabled
        request.activePage = -1;
        request.firstPage = false;
        request.lastPage = false;
        response(getData(), request);
      } else if (request.type === 'prev') {
        // click previous button, notice this function is never reached.
        alert('someone clicked previous');
      }
    }

    function getColumns() {
      if (!columns) {
        columns = [
          { id: 'selectionCheckbox', sortable: false, resizable: false, width: 50, formatter: Formatters.SelectionCheckbox, align: 'center' },
          { id: 'productId',   name: 'Product Id',   field: 'productId',   sortable: false, filterType: 'integer', width: 140, formatter: Formatters.Readonly                     },
          { id: 'productName', name: 'Product Name', field: 'productName', sortable: false, filterType: 'text',    width: 150, formatter: Formatters.Hyperlink                    },
          { id: 'activity',    name: 'Activity',     field: 'activity',    sortable: false, filterType: 'text',    width: 125,                                      hidden: true  },
          { id: 'quantity',    name: 'Quantity',     field: 'quantity',    sortable: false,                        width: 125                                                     },
          { id: 'price',       name: 'Price',        field: 'price',       sortable: false, filterType: 'decimal', width: 125, formatter: Formatters.Decimal                      },
          { id: 'orderDate',   name: 'Order Date',   field: 'orderDate',   sortable: false, filterType: 'date',                formatter: Formatters.Date, dateFormat: 'M/d/yyyy' }
        ];
      }

      return columns;
    }

    function getData() {
      if (!data) {
        data = [
          { id: 0,  productId: 214220, productName: 'Compressor 1',  activity: 'Assemble Paint', quantity: 1,    price: 210.99,             status: 'Active',   orderDate: '2015-01-01T06:00:00.000Z', action: 'Action', rated: .32  },
          { id: 1,  productId: 214221, productName: 'Compressor 2',  activity: 'Assemble Paint', quantity: 1.5,  price: 209.99,             status: 'Late',     orderDate: '2015-01-02T06:00:00.000Z', action: 'Action', rated: .76  },
          { id: 2,  productId: 214222, productName: 'Compressor 3',  activity: 'Assemble Paint', quantity: 2,    price: 208.99,             status: 'Active',   orderDate: '2015-01-03T06:00:00.000Z', action: 'Action', rated: .32  },
          { id: 3,  productId: 214223, productName: 'Compressor 4',  activity: 'Assemble Paint', quantity: 2.5,  price: 207.99,             status: 'Inactive', orderDate: '2015-01-04T06:00:00.000Z', action: 'Action', rated: .53  },
          { id: 4,  productId: 214224, productName: 'Compressor 5',  activity: 'Assemble Paint', quantity: 3,    price: 206.99,             status: 'Inactive', orderDate: '2015-01-05T06:00:00.000Z', action: 'Action', rated: .42  },
          { id: 5,  productId: 214225, productName: 'Compressor 6',  activity: 'Assemble Paint', quantity: 3.5,  price: 205.99,             status: 'Inactive', orderDate: '2015-01-06T06:00:00.000Z', action: 'Action', rated: .88  },
        ];
      }

      return data;
    }
  });
</script>
```

**Comment by tmcconechy** [comment]
Did you want to do a PR for this if you have a fix?

**Comment by pwpatton** [comment]
sure, let me look into it and see what I can find out.
