### ISSUE TITLE
Advanced File Upload: No way to set a file upload as failed and to display error message

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise#5671]
In the advanced file upload component, there is no way to set an upload as failed and to display the error message received from backend.

Only following API are provided with the component:
```
interface SohoFileUploadAdvancedStatus {
  /** The file being uploaded. */
  file: File;

  setCompleted(data?: any): void;

  setProgress(percent: number): void;

  setAbort(xhr?: any): void; // xml http request object
}
```

**Expected Behavior**: Provide an API to set status as failed and to provide an error message as input.

**Actual Behavior**: No way to set an upload as failed and to display an error message

Product: Infor PIM

**Comment by tmcconechy** [comment]
In addition need to add the fix/ability to the new web component

**Comment by NarraVivek** [comment]
Hello @tmcconechy , 

I was wondering to check in here to know when this fix going to be added? also came across some requirements which needed addition of user-made custom error messages(unlike maxFiles and maxFileSize). Is it possible to integrate something like the alert component into individual files upload. 

Thank you.

**Comment by tmcconechy** [comment]
Added it to grooming to discuss further. i dont think we wont to combine the alert component. As it would mean having two UIs for the same thing. But if you need a workaround you could try to use it temporarily.

For this fix, add an api to hide/show a manual message in a fileupload.

@deep7102 is this possible in the web component version?

**Comment by deep7102** [comment]
No, currently web component version not implemented for api to hide/show a manual message only you can do custom error strings.

**Comment by jbrcna** [comment]
this is now working as expected. thank you .
v4.62.0-dev
https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-failed.html
<img width="564" alt="image" src="https://user-images.githubusercontent.com/56722184/159850465-27fe7de8-7fa1-42a0-9f06-4ac0a81fbe6a.png">

**Comment by NarraVivek** [comment]
@tmcconechy is this available in enterprise-ng? or could please share any ref on how we can make use of this on our end.

**Comment by tmcconechy** [comment]
Not yet @NarraVivek - we need to add the `setFailed` method to angular. Can you do that @yohannahbautista ? cc @ericangeles 

Thanks!
