### ISSUE TITLE
Lookup: Range filter is not working as expected

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5677]
**Describe the bug**
Lookup: Range filter is not working as expected
**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/lookup/example-filter-row.html
2. In Product Id - Filter Range 2142201-2142205

**Expected behavior**
Product IDs in range should be listed

**Version**
4.56-ids-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/135244344-fcd86a43-b712-42ee-bca8-a4fbfdb77593.png)

**Platform**
Windows 10 Chrome 
& all major browsers & OS

**Additional context**
N/a

**Comment by tmcconechy** [comment]
There shouldn't be a range filter here. So suggest just updating the example to remove it.

**Comment by janahintal** [comment]
QA Passed, Verified in https://main-enterprise.demo.design.infor.com/components/lookup/example-filter-row.html
![image](https://user-images.githubusercontent.com/45757016/161253080-1227e129-6980-451e-a1ac-b8176caeb4a0.png)
