### ISSUE TITLE
CAP: Make background slate 01

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5685]
**Describe the bug**
For better contrast need to change the cap header to Slate 01.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html
2. Click on button
4. See toolbar header 

Should now be:
Light
Slate 02 -> Slate 01
Dark
Slate 06 -> Slate08
High-Contrast
Slate 03 -> Slate 01

**Additional context**
https://jira.infor.com/browse/UXD-2505

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
