### ISSUE TITLE
Locale: Add Filipino / Tagalog Translations

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5695]
**Describe the Task**
Add new translation files for the month from the translation team. This includes Filipino / Tagalog support. Locale is `tl-PH`

**Task**
- Add translations for this month to EP/WC

**Comment by cpinatel7** [comment]
tl-PH locale? Could you please advise. Thanks

**Comment by tmcconechy** [comment]
Yes @cpinatel7  its `tl-PH` and this will be in 4.56.0 (see attached PR which you can double check if you like)

**Comment by cpinatel7** [comment]
Thanks

**Comment by janahintal** [comment]
Hi @tmcconechy, kindly see below for the test result. 

Notes for enhancement. 
1. Currency should be placed before the number 
![image](https://user-images.githubusercontent.com/45757016/135965776-3104f30a-ee04-4835-b159-4c2a69a17779.png)
2. May change Extra Small to "Pinaka Maliit"

Blocker
1. Unable to scroll down in Datagrid Tab

**Comment by tmcconechy** [comment]
@nganotice Can you make a new issue for those because we have to route this to the translation team
