### ISSUE TITLE
Pie: Item 4 id is incorrect

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5703]
**Describe the bug**
I happen to discover this issue while running my automation scripts. the ID of the `4th slice` and `4th Legend` seems to be incorrect following the naming of other id's. I'm not sure if this is an issue but will file this for reference.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/pie/example-index.html
2. Inspect element on `orange slice` (4th slice)
3. See error. Notice that it's` id="item-c-slice-4"`
4.  Inspect element on `Item E (19%)` Legend (4th Legend)
5. See error. Notice that it's` id="item-c-legend-4"`

**Expected behavior**
should be id="item-e-slice-4" and id="item-e-legend-4"

**Version**

- ids-enterprise: v4.56.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/135746438-26f44bc7-787b-49b7-8d40-149242df34d2.png)
![image](https://user-images.githubusercontent.com/56722184/135746466-9459460b-fe7a-4011-8085-2686c9c046a5.png)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
`data-automation-id` are fine

**Comment by tmcconechy** [comment]
This wasnt a bug it was just labelled wrong in the example so i updated it here https://github.com/infor-design/enterprise/commit/e036d280ece9feaff786041e6405c97a4678cd12 

Should be ok now going forward

**Comment by jbrcna** [comment]
Thanks @tmcconechy .
