### ISSUE TITLE
Datagrid:Row selection using keyboard up and down arrows

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#5713]
**Is your feature request related to a problem or use case? Please describe.**
I couldn't find this feature in Data Grid

**Describe the solution you'd like**
In Single select mode we want to be able to select the next row by clicking the Down arrow on the keyboard, and the previous row by clicking the Up arrow.
(We had this feature in Infor M3 IBrix table)

**Describe alternatives you've considered**
I've made a workaround using `activecellchange` event that will select the new row - but I must check that it was a different row, otherwise it will be infinite loop.

**Additional context**
[https://jsfiddle.net/sebulbajoe/taxy5hs6/4/show](https://jsfiddle.net/sebulbajoe/taxy5hs6/4/show)
![datagrid-keyboard-selection](https://user-images.githubusercontent.com/34129313/136228917-10633d3f-cb90-4b47-91a5-23e0dcfbc81f.gif)

Thanks!

**Comment by tmcconechy** [comment]
Maybe you could also use the https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.js#L238 callback and on up or down arrow get the selected row and call the prev/next one.

I'm not seeing any issue in what you did though? Are you basically asking for a setting for this?

**Comment by CindyMercadoReyes** [comment]
BDD attached.
[BDDStory_github5713.docx](https://github.com/infor-design/enterprise/files/7728596/BDDStory_github5713.docx)

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.59.0-dev.

https://main-enterprise.demo.design.infor.com/components/datagrid/example-key-row-select.html

![Video 24](https://user-images.githubusercontent.com/84306838/146717614-c5e0590f-c6ab-44d3-a402-782623057e8c.gif)

Moving this ticket to Done.

Thanks!
