### ISSUE TITLE
Card Swipe Action to Reveal Multiple Actions (up to 4)

### ISSUE THREAD

**Issue by anton-kurilov** [infor-design/enterprise#5715]
**Is your feature request related to a problem or use case? Please describe.**
As an extension of: https://github.com/infor-design/enterprise/issues/5254 it would be helpful to be able to configure the number of items we show after a swipe action.

**Describe the solution you'd like**
Be able to pass 0 to 4 different swipe actions to the component.

**Describe alternatives you've considered**
Needed actions are currently available outside of a swipe context, otherwise we could need a custom swipe solution on our cards.

**Additional context**
WFM Employee Portal Requirement, as per mockups, something like:
![image](https://user-images.githubusercontent.com/14839675/136262625-278f98d7-b7bd-49e5-af91-c060090d2bbe.png)

**Comment by tmcconechy** [comment]
cc @kevinwhitedesign has pushed back on this...

`We only want to show one action on left swipe, one action on right swipe... and then what we suggest to teams is that they can have their users pick which actions they want on swipe via settings... so If a user wants a save action on right swipe instead of delete, they can do that also teams have the ability for more actions with the ellipsis that will always be there`

So we should hold on this for now or close....

**Comment by kevinwhitedesign** [comment]
https://main-enterprise.demo.design.infor.com/components/swipe-action/example-index.html
Current card swipe example^

As you can see multiple actions are available in the ellipsis icon in this example (you can fit 4). On mobile, tapping the ellipsis will show an action sheet on the bottom with the available actions. This supports many actions. It is advised to have the most frequently used actions on swipe, and then to take it a step forward: a user settings experience can be designed in your app to allow the user to configure which actions they'd like on swipe (config left and right swipe actions). 
cc @danirosefishinfor @laurensteiger @anton-kurilov

**Comment by anton-kurilov** [comment]
@tmcconechy @kevinwhitedesign that makes sense to me, I had a similar discussion with our team as well that our many actions should be handled in the ellipsis. Let me close this and bring this back to WFM :) for now. I will reopen if we have a convincing counter-point. Thanks!

**Comment by kevinwhitedesign** [comment]
@anton-kurilov awesome! Yeah I discussed with Calvin and Chloe as well I think in the past
