### ISSUE TITLE
Toolbar: Actions search misaligned 'x' button

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5716]
**Describe the bug**
Toolbar: Actions search misaligned 'x' button

**To Reproduce**

1. Go to Open iOS mobile
2. Go to https://4560-beta0-enterprise.demo.design.infor.com/
3. Scroll down to Toolbar Action
4. Type in search field

**Expected behavior**
'x' button should be aligned

**Version**
IDS-4560-BETA0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/136362010-8dbbab28-5bec-4dba-ab3d-15c7c42cbe0f.png)

**Platform**
iOS - iPhone 12 mini & android

**Additional context**
N/A

**Comment by ericangeles** [comment]
Looks like it is now fixed in 4.57.0 version.

Tested on iOS mobile iPhone XS Max (BrowserStack)

<img width="397" alt="toolbar-ss" src="https://user-images.githubusercontent.com/8839327/140514535-ca029924-80fa-479d-8735-9b6bd805cbf2.png">

**Comment by tmcconechy** [comment]
Agreed it looks fix now!

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to Done. thanks!
https://main-enterprise.demo.design.infor.com
`iPhone 12 Mini (browserstack)`
![image](https://user-images.githubusercontent.com/56722184/140733479-d424897b-3cf1-478f-8515-657817ca66cd.png)


`Samsung Galaxy S21+ (browserstack)`
![image](https://user-images.githubusercontent.com/56722184/140732702-4402bb97-a65d-4975-b0b7-f07a33abc313.png)
