### ISSUE TITLE
SpinBox: Shows ripple effect when disabled

### ISSUE THREAD

**Issue by aviralg26892** [infor-design/enterprise#5719]
**Describe the issue **
Soho Spin Box when we reach to min or max value, disabled buttons stil show the ripple effect making at appear as if its enabled

**Steps to reproduce the behavior:**
1. Go to https://github.com/infor-design/enterprise/blob/4.55.3/app/views/components/spinbox/example-range-limits.html
 https://design.infor.com/code/ids-enterprise/latest/demo/components/spinbox/example-range-limits?theme=uplift&variant=light
2. Click on - or + tabs to reach minimum or maximum value.
3. As we reach min or max value, - or + sections are disabled.
4. Now if we click on disabled area it is showing ripple effect, that eventually leads to click event when applied in project.

**Expected behavior**
On reaching maximum or minimum value, disabled area should not give any response when clicked.

**Version**
- "ids-enterprise-ng": "10.2.1"

**Screenshots**
NA

**Platform**
 - Device (if applicable) NA
 - OS Version: Windows 10 
 - Browser Name :chrome
 - Browser Version: 94.0.4606.71

**Additional context**
Due to this problem when we implement soho spin box in project , even clicking on disabled section triggers to a click event which ultimately leads to enable save feature, even though no changes are done in the component it is used in.

**Comment by aviralg26892** [comment]
Hi @EdwardCoyle , I don't think we have a team here. I am working for Infor and my work id didn't had access to Git earlier. SO I raised issue from my personal Id.

**Comment by tmcconechy** [comment]
@aviralg26892 we just mean whats the name of the app you work on.

**Comment by aviralg26892** [comment]
@tmcconechy  I am working on ION desk application.

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.59.0-dev.

https://main-enterprise.demo.design.infor.com/components/spinbox/example-range-limits

![image0 (1)](https://user-images.githubusercontent.com/84306838/145312695-42bfe8c1-5f86-49c0-962a-40da8c1340d6.gif)

Moving this ticket to Done.

Thanks!

**Comment by aviralg26892** [comment]
Hi @nganotice / @tmcconechy ,

How can I upgrade this in my project? What are the steps and  prerequisites and which angular version is supported in this upgrade?

**Comment by tmcconechy** [comment]
Hi!

If you using NG 12 and dont want to upgrade take ids-enterprise-ng take [10.12.1](https://www.npmjs.com/package/ids-enterprise-ng/v/10.12.1 ) 

If you want to upgrade to Ng 13 take [13.0.2](https://www.npmjs.com/package/ids-enterprise-ng/v/13.0.3)

See notes on updating here: https://github.com/infor-design/enterprise-ng/blob/main/docs/UPGRADING.md

**Comment by aviralg26892** [comment]
Hi @tmcconechy ,

We are using "ids-enterprise-ng": "10.9.0". What is the next version where we can upgrade to, to fix this issue.

**Comment by tmcconechy** [comment]
Those are the only two choices. We didn’t have an NG 10/11 anymore so either:

NG 12 - https://www.npmjs.com/package/ids-enterprise-ng/v/10.12.1
NG13 - https://www.npmjs.com/package/ids-enterprise-ng/v/13.0.3

**Comment by aviralg26892** [comment]
Hi @tmcconechy 
We have upgraded our system to ids-enterprise-ng/v/13.0.3 but it looks like issue is not fixed. Even though the -/+ tabs are disabled while reaching min/max limit but if we click on it ripple effect/propagation is not stopping. It is leading to triggering of some event which should not be the case.
