### ISSUE TITLE
Column Chart: Add axis labels for column chart

### ISSUE THREAD

**Issue by ryanChrstn** [infor-design/enterprise#5721]
**Is your feature request related to a problem or use case? Please describe.**
[Column Chart](https://design.infor.com/code/ids-enterprise/latest/column) ([Grouped](https://design.infor.com/code/ids-enterprise/latest/column-grouped)): Currently the Column Charts only displays the name of items per bar as the label.
Though, the user might not have an idea what those labels are being represented.

**Describe the solution you'd like**
We think having axis labels in the Column Chart would be beneficial to make the charts more descriptive of the data displayed.
The idea of axis labels we're expecting is the same as the labels in [Line Chart](https://main-enterprise.demo.design.infor.com/components/line/example-axis-labels.html)

**Describe alternatives you've considered**
Or maybe to add a way that'll give a description for the bars on the graph.

**Additional context**
Here's an example of a Column Chart having axis labels.
![image](https://user-images.githubusercontent.com/14357059/136501864-0d62ab0f-f88d-4919-b456-bea7c0eebc60.png)

Application: {lawson}

**Comment by tmcconechy** [comment]
Need to add the same code that makes axis labels in line chart to column chart

**Comment by ryanChrstn** [comment]
Hi @tmcconechy, I wasn't able to find a way to add a label for this ticket.

Could you please add a label, the label would be "team: lawson".
Thank you!

**Comment by jbrcna** [comment]
**QA Failed.**
v4.58.0-dev
this is now working https://main-enterprise.demo.design.infor.com/components/column-grouped/example-axis-labels?theme=classic&mode=light&colors=2578a9.
 but failed on this one https://main-enterprise.demo.design.infor.com/components/column-grouped/example-axis-labels?locale=ar-EG in `Safari`

`expected result: should have bottom axis label and right axis label`
![image](https://user-images.githubusercontent.com/56722184/144193926-bbf288ce-cb1b-4e57-90bf-556fffa86b10.png)
`Safari browser`

**Comment by ericangeles** [comment]
@jbrcna what version of Safari did you use? Am not seeing the issue on my end. 

This is Safari Version 15.1

<img width="1333" alt="Screen Shot 2021-12-01 at 4 19 44 PM" src="https://user-images.githubusercontent.com/8839327/144197680-84818631-1cff-4175-b2f8-8013b9cd212c.png">

**Comment by jbrcna** [comment]
I'm using 15.1
![image](https://user-images.githubusercontent.com/56722184/144229514-85fa6bce-4374-46c4-b7c0-a5019713c450.png)

**Comment by jbrcna** [comment]
@ericangeles , I've check this on Browserstack Safari Big Sur, Monterey, Catalina and works fine. will move this ticket to Done now. thanks
![image](https://user-images.githubusercontent.com/56722184/144230073-0eba28c5-92d2-47e5-9671-f3b5062b2b37.png)

**Comment by CindyMercadoReyes** [comment]
A BDD has been created for this ticket. Thanks, Cind
[BDDStory_github5721.docx](https://github.com/infor-design/enterprise/files/7661649/BDDStory_github5721.docx)
y
