### ISSUE TITLE
Modal: Enter key closes dialog unexpectedly

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#5728]
**Describe the bug**
When in a dialog, pressing the "Enter" key when focusing a field that doesn't handle the event (keydown enter) will cause the dialog to be closed.

I'm not sure if this is a bug or feature, but it's a new (undocumented?) behavior since 4.54.0.

**To Reproduce**

1. Go to 'https://design.infor.com/code/ids-enterprise/4.54.0/demo/components/modal/example-index' or any later versions
2. Click on 'Show Modal', optionally write something in the first input field
3. Press Enter
4. The dialog closes

**Expected behavior**
When repeating the above, but on [4.53.5](https://design.infor.com/code/ids-enterprise/4.53.5/demo/components/modal/example-index) the dialog is not closed.

**Version**

- ids-enterprise: 4,54,0 to current latest

**Platform**
 - Browser Name: Chrome

**Additional context**
Causing some issues in multiple projects and dialogs, especially where "Enter" is handled in an unexpected way, for example an Autocomplete field where no value has been selected:

https://jira.infor.com/browse/LIME-7118
https://jira.infor.com/browse/MINGLEDEV-32468

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.58.0-dev.

https://main-enterprise.demo.design.infor.com/components/modal/example-index.html

Moving this ticket to Done.

Thanks!
