### ISSUE TITLE
Datagrid: With cell navigation set to false, tabbing traverses all the rows before setting focus on the pager bar

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5734]
Describe the bug
With the datagrid option of cellNavigation set to false and focus on a grid row, tabbing will set focus on each of the grid rows before tabbing sets the focus on the pager bar.  

1. Using the attached 'example-modal-datagrid-tabbing.html'
2. Click on 'Open Modal'
3. Notice that focus is on the first row of the datagrid
4. Hitting the tab key twice (assuming this is because two columns) moves to the next row 
5. Continue to hit the tab key to set focus in the pager bar

Expected behavior
Expectation is that a list without cell navigation, a tab from a grid row should go to the pager bar and not traverse all the rows first.

Version
- ids-enterprise: v4.57.0-dev

**Comment by claudenbach** [comment]
[Git-5734.zip](https://github.com/infor-design/enterprise/files/7331898/Git-5734.zip)

**Comment by janahintal** [comment]
QA Passed. Verified in http://localhost:4000/components/datagrid/test-editable-paging-validation.html and is now working as expected.
