### ISSUE TITLE
Datagrid: Modal containing a datagrid unable to tab through the fields of the filter row

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5735]
Describe the bug:
When tabbing through a modal dialog containing a datagrid, unable to tab through the fields of the filter row.

1. Using the attached 'example-modal-datagrid-tabbing.html'
2. Click on 'Open Modal'
3. Notice that focus is on the first row of the datagrid
4. Perform a shift-tab (or tab) until focus is on a field in the filter row
5. Continue to hit shift-tab (or tab) and notice that focus does not move across the filter row fields

Expected behavior:
Able to tab across the fields that make up the filter row.  Tab to the operands dropdown and filter input elements.  When the datagrid is not in a modal dialog, user is able to tab across the elements of the filter row.

Version:
- ids-enterprise: v4.57.0-dev

Screenshots:
See attached zip file.

Additional context:
Is related to Git #5734

**Comment by claudenbach** [comment]
The tabbing eventually get stuck going between a filter field and a toolbar button when hitting the tab key or shift-tab key.

**Comment by janahintal** [comment]
QA Passed. Verified in http://localhost:4000/components/datagrid/example-modal-datagrid-tabbing.html thanks!
![image](https://user-images.githubusercontent.com/45757016/151345501-70c82703-5766-49e0-b26e-f71e668c3d6d.png)
![image](https://user-images.githubusercontent.com/45757016/151345562-3e0f06ba-c951-4ac9-afe9-a2a39cd8b5d2.png)
