### ISSUE TITLE
Calendar event colors should accept color keywords

### ISSUE THREAD

**Issue by lbursey-infor** [infor-design/enterprise#5743]
**Is your feature request related to a problem? Please describe.**
Calendar events currently only accept a hex value color (eg "#00FF00") when overriding the color of an event. Currently we get custom colors for calendar events both by hex and by keyword (eg "papayawhip").

**Describe the solution you'd like**
Calendar event should accept color keywords as well, instead of just accepting hex values.

**Describe alternatives you've considered**
WFM is having to maintain an array of color keywords and convert them to hexes, but this is not ideal.

**Comment by lbursey-infor** [comment]
Hi Tim,

Current workaround is to maintain a map of all color keywords and their hex values (ie this list https://www.w3.org/wiki/CSS/Properties/color/keywords).

Regarding the color palette, our customers have custom colors already set up for certain events (eg vacation/PTO/sick day) and they need to be consistent across the app. That might mean some inconsistency in branding but it's required for some use cases.

**Comment by jbrcna** [comment]
The colors on the event types displayed in the calendar is also reflected in the legend. However, if you create a new event it will not match the legend color of event.
 v4.60.0-dev
Steps 

1. Go to https://main-enterprise.demo.design.infor.com/components/calendar/test-event-custom-colors.html
2. Create a new event (Add event Modal)
3. See error.
4. Try all event types
5. Noticet that the color is always `background-color: powderblue; border-left-color: royalblue;`

**Comment by CindyMercadoReyes** [comment]
BDD attached
[BDDStory_github5743.docx](https://github.com/infor-design/enterprise/files/7927352/BDDStory_github5743.docx)
.

**Comment by ericangeles** [comment]
@tjamesallen15 where are we on this?

**Comment by jbrcna** [comment]
this is now working as expected. v4.60.0-beta1 . thank you
https://4600-beta1-enterprise.demo.design.infor.com/components/calendar/test-event-custom-colors.html
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/56722184/153340520-2b7badb1-bec3-4c0b-82ca-2c20fd2260de.png">
