### ISSUE TITLE
ColorPicker: Red diagonal line goes beyond its border when field-short class is used

### ISSUE THREAD

**Issue by marclouisgenedeguzman** [infor-design/enterprise#5744]
**Describe the bug**
When the color picker have field-short class, the red diagonal line goes beyond its border:

![image](https://user-images.githubusercontent.com/50192038/137460781-ff2e5e92-2e69-41ac-b0ca-58c991ce7771.png)

**To Reproduce**
Sample code reproduced here: https://stackblitz.com/edit/ids-quick-start-940-pg8ssj

1. Go to https://stackblitz.com/edit/ids-quick-start-940-pg8ssj
2. Select None color option
3. Observe diagonal line

**Expected behavior**
Diagonal line should not go beyond the border

**Version**
ids-enterprise-ng 9.4.0 or higher

**Comment by tmcconechy** [comment]
This can easily be seen on https://main-enterprise.demo.design.infor.com/components/form/example-compact-mode.html and is only happening in compact mode.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
