### ISSUE TITLE
Area: Display text ellipsis for long legend items

### ISSUE THREAD

**Issue by javenturina** [infor-design/enterprise#5749]
**Describe the bug**
Area chart type is encountering an issue when legends have long text. Legends overlapped resulting to them becoming undegradable.

**To Reproduce**

1) Use Soho component with the following configuration:
```
<ng-container [ngSwitch]="chartType">
      <div soho-line [isArea]="true" [dataset]="chartData" *ngSwitchCase="'area'"></div>
      <div soho-bar type="bar" [dataset]="chartData" *ngSwitchCase="'bar'"></div>
      <div soho-column type="column" [dataset]="chartData" *ngSwitchCase="'column'"></div>
      <div soho-pie [isDonut]="true" [dataset]="chartData" *ngSwitchCase="'donut'"></div>
    </ng-container>
```

**Expected behavior**

Long text legends should convert to text with ellipsis. Similar to the behavior of the Column type chart.

**Version**

- ids-enterprise: 4.3.3
- October 18,2021 

**Screenshots**
Area chart type widget:

![image](https://user-images.githubusercontent.com/91868168/137720089-1b4f41b6-4549-4945-bdc9-746c2c65a349.png)

Column chart type widget:

![image](https://user-images.githubusercontent.com/91868168/137720148-7623bd4e-6781-464f-97ee-1fb54f91eb13.png)

**Platform**
Infor Application/Team Name: Infor CRM Cloud Edition
OS Version: Windows 10
Browser Name: Chrome
Browser Version: Version 90.0.4430.85 (Official Build) (64-bit)

**Additional context**
Component is used in our Mingle homepage widgets, please note of the size constraint.

**Comment by javenturina** [comment]
Yes, the column chart does the ellipsis conversion of long text label.
Sorry i missed to add that our widgets are using a translatable strings for the chart labels, here is the English labels:

Donut chart:
![image](https://user-images.githubusercontent.com/91868168/137829240-ab795f18-a8cb-43de-94e5-5270599c080c.png)


Column chart:

![image](https://user-images.githubusercontent.com/91868168/137828858-2553ced3-d8b8-47e6-865b-020d97d161ff.png)

Area Chart:
 Works in english, but in other languages with longer text they don't get truncated(with ellipsis) 
![image](https://user-images.githubusercontent.com/91868168/137828751-6a9257c3-45df-493e-848a-ef70e63ada7a.png)

Here is the default settings:

```
selector: "chart",
  template: `
    <ng-container [ngSwitch]="chartType">
      <div soho-line [isArea]="true" [dataset]="chartData" *ngSwitchCase="'area'"></div>
      <div soho-bar type="bar" [dataset]="chartData" *ngSwitchCase="'bar'"></div>
      <div soho-column type="column" [dataset]="chartData" *ngSwitchCase="'column'"></div>
      <div soho-pie [isDonut]="true" [dataset]="chartData" *ngSwitchCase="'donut'"></div>
    </ng-container>
  `,
  styles: [
    `
      :host {
        display: inline-block;
        height: 100%;
        width: 100%;
      }
    `
  ]

Usage:
providers: [InvoicesService, ChartComponent],
  template: `
    <chart [chartData]="agingDetails" [chartType]="chartType"> </chart>
    <!-- <div soho-emptymessage icon="icon-empty-no-data" class="empty-title" *ngIf="!showNoData" [title] ="language.noDataMessage"></div> -->
  `
```

I see the alternatives and they look promising, I'll present them to the client and see which they prefer. Thank you for this.

**Comment by tmcconechy** [comment]
Yes i tested and it works (even tho the axis type is typed to an object).

- in src/app/area/area.demo.ts add
```
  axisSettings = { rotate: '-65' };
```
- in src/app/area/area.demo.html add
```
[xAxis]="axisSettings"
```

**Comment by javenturina** [comment]
Thanks Tim, I already presented this workaround with our client/user. I'll keep you posted on the result.
