### ISSUE TITLE
Form: Datepicker icon not centered on Safari

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5751]
**Describe the bug**
Datepicker icon not centered on Safari

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/form/example-compact-mode.html
2. Scroll down to Datepicker (not in compact mode)
3. See error that the Datepicker isn't centered

**Expected behavior**
Datepicker should be centered

**Version**
v4.57.0-dev

**Screenshots**
<img width="813" alt="Screen Shot 2021-10-18 at 2 44 56 PM" src="https://user-images.githubusercontent.com/84306838/137811122-a37b52c6-73c7-4916-b7d2-7456bb3159c4.png">

**Platform**
-Safari

**Additional context**
N/A

**Comment by tmcconechy** [comment]
This appears to be fixed now. Closing

**Comment by janahintal** [comment]
QA Passed. Thanks! 👍 
![image](https://user-images.githubusercontent.com/45757016/139833227-38705e58-6e78-4bd6-838e-d898150dbb12.png)

**Comment by ericangeles** [comment]
@janahintal what test page is this?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
