### ISSUE TITLE
Message: Create Puppeteer Script on Informational Status

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#5754]
**Describe the Issue**
Create a unit testing for a message informational status.

See attached BDD for more information.
[BDDStory_github5459.docx](https://github.com/infor-design/enterprise/files/7372205/BDDStory_github5459.docx)

**Related github issue**
https://github.com/infor-design/enterprise/issues/5459

**Comment by ericangeles** [comment]
cc @CindyMercadoReyes

**Comment by jbrcna** [comment]
this is now merged into main enterprise. moving this ticket to Done. Thank you  @ericangeles

**Comment by jbrcna** [comment]
cc @maezcruz , @CindyMercadoReyes
