### ISSUE TITLE
Application Menu: Create a Puppeteer Script on Resizable App Menu

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#5755]
**Describe the Issue**
Create a unit testing for a resizable app menu.

See attached BDD for more information.
[BDDStory_github5193.docx](https://github.com/infor-design/enterprise/files/7372277/BDDStory_github5193.docx)

**Related github issue**
https://github.com/infor-design/enterprise/issues/5193

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
