### ISSUE TITLE
Datepicker/Calendar: Mobile and Usability Improvements

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5763]
**Describe the bug**
Checking through https://www.figma.com/file/y1oT4NPGJA78EzUNssZYsG/?node-id=0%3A1 it seems we have not everything implemented.

- [ ] ‘Clear’ and ‘Apply’ actions are removed where not needed. ‘Clear’ is available as an option and ‘Apply’ is available where users have to make multiple selections.
- [ ] A visual ‘today’ state was added to mark the current date for reference while users navigate.
- [ ] Border at the top was removed for consistency.
- [ ] Hitboxes for horizontal chevrons ‘< >’ and dates have been increased to 44px size
- [ ] Change “Today” action to 16px bold, to be consistent with other tertiary buttons.
- [ ] Popovers stay open & receive an ‘Apply’ action when users have to make multiple selections. (ex. range + time picker)
- [ ] Add desktop variant where the month/year selection is attached to date selection.
- [ ] Add desktop variant where ‘Clear’ action is retained for potential usecases when ‘Clear’ is critical to a user’s flow. (although we think this will be uncommon)
- [ ] Add another way for users to ‘Clear’ by deselecting (clicking or tapping) a selected date.
- [ ] Add swiping in our Angular web component (and HTML??) for mobile action sheet options.
- [ ] Horizontal swiping for calendar view navigation
- [ ] Vertical swiping for month / year navigation
- [ ] For mobile action sheet, add a variant that includes a ‘Cancel’ action in case it is not apparent that users can tap away to ‘Cancel’.

In month/year switcher:
- [ ] Disabled horizontal chevrons ‘< >’ were removed due to not being applicable.
- [ ] ‘Cancel’ action is removed because it is duplicate functionality with the month/year switcher itself.
- [ ] Vertical chevrons ‘^v’ added to navigate through months
- [ ] Month chevron cycles through the entire rest of the months, so if it can display 6, clicking on the bottom chevron will show the next 6
- [ ] Similarly, the year switcher will cycle through to the next amount of years that can be displayed.
- [ ] Add and use default hover state for months / years.
- [ ] Instead of tag styling, use rectangular styling consistent with other list selection components.

**Additional context**
https://www.figma.com/file/y1oT4NPGJA78EzUNssZYsG/?node-id=0%3A1

Some of these changes will apply to monthview/calendar.

**Comment by kevinwhitedesign** [comment]
Just set a review 👍

**Comment by tmcconechy** [comment]
May need to further divide these changes up

**Comment by laurensteiger** [comment]
Kevin worked on some variants for this component. Here are the variations. https://www.figma.com/file/DnguXUS7T4J5Rce92MuoCY/?node-id=892%3A348

**Comment by kevinwhitedesign** [comment]
Let us know if y'all have any questions

**Comment by tmcconechy** [comment]
Will do - I'm thinking about targeting this for the new version, since it is a LOT of work.

**Comment by tmcconechy** [comment]
This was added in the web component version..
