### ISSUE TITLE
Actionable Button Card

### ISSUE THREAD

**Issue by anton-kurilov** [infor-design/enterprise#5768]
**Is your feature request related to a problem or use case? Please describe.**
We want the same button effects (hover, focus, press, etc..) for card like buttons

**Describe the solution you'd like**
Would like Actionable Button Card component that gives us this type of style and behaves like a button

**Describe alternatives you've considered**
full width outline button styles such as: https://getbootstrap.com/docs/5.1/components/buttons/#outline-buttons 

**Additional context**
Here is an example mockup from our design team:
![image](https://user-images.githubusercontent.com/14839675/138355317-e105be82-86a7-46f2-b032-daf423f83274.png)

**Comment by anton-kurilov** [comment]
Any update on this one? Thanks!

**Comment by tmcconechy** [comment]
Not yet we have it in for planning so it should get in the Dec sprint.

**Comment by tmcconechy** [comment]
@anton-kurilov do you think https://main-enterprise.demo.design.infor.com/components/button/test-secondary-border.html would work?

But i think we should have actionable cards. To who picks this up lets make a `<a>` or `<button>` work with a card class so it looks like a card. And add the focus and cursor change

**Comment by anton-kurilov** [comment]
@tmcconechy I think the secondary buttons are definitely a better than the current solid grey ones, can will these outline style of buttons support theme color as well? Or are they always grey?

But it's definitely better than the current secondart grey color :) Just to show what we currently have to get all the ids button effects for free:

![image](https://user-images.githubusercontent.com/14839675/148411212-fe935ca4-5861-4586-b395-58b76221b7a1.png)

It's a little monotone, so product isn't a huge fan

**Comment by tmcconechy** [comment]
ok cool. well it is an option and one thats more like bootstrap outline buttons.
But we decided we should also add the button/actionable cards as they are used in design more and more

**Comment by ericangeles** [comment]
@tmcconechy is this gonna be a new component?

**Comment by tmcconechy** [comment]
@ericangeles sort of but i would call it a new feature of the card. the way i would think about it maybe is:

- add an example to the card examples (example-actionable.html)
- add a button element and a element with class `card`
- add styles to card.scss like fx `button.card {}. a.card{}` 
- change the initializer so that it initializes it as a button so you get the ripple effect (maybe)

**Comment by anton-kurilov** [comment]
Will this be in the angular build as well? Thanks!

**Comment by tmcconechy** [comment]
Yes we should add the types for next release @ericangeles

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.60.0-dev. moving this ticket to done.
https://main-enterprise.demo.design.infor.com/components/cards/example-actionable
![image](https://user-images.githubusercontent.com/56722184/150458286-4a1e4771-e122-4c9b-b392-29d2d1264307.png)

**Comment by CindyMercadoReyes** [comment]
BDD attached
[BDDStory_github5768.docx](https://github.com/infor-design/enterprise/files/7914716/BDDStory_github5768.docx)
.
