### ISSUE TITLE
ColumnChart: Request to add rotate option

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise#5773]
**Is your feature request related to a problem? Please describe.**
When there are many items in the column chart, the labels are concatenated. Stakeholders still want the labels to be readable .
![image](https://user-images.githubusercontent.com/53523076/138425780-c0d719fc-d202-4136-b723-29be9dbcdd45.png)

**Describe the solution you'd like**
The soho-chart/line/column component should have an option to display the complete label rotated at 45 degrees.
![image](https://user-images.githubusercontent.com/53523076/138429195-949f4060-3895-452d-8f4a-116263d16d94.png)

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.58.0-dev. moving this ticket to done. Thanks
https://main-enterprise.demo.design.infor.com/components/column/example-rotate.html
![image](https://user-images.githubusercontent.com/56722184/141723204-5170de9a-24d0-4b8a-92c9-6f3311c869ce.png)
