### ISSUE TITLE
Icons: Add new icons from design

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#5774]
**Describe the change**

Made some changes to icons and added some new ones.

**Icon Changes:**
Updated ‘launch’ icon for visual clarity
Updated ‘translate’ icon for visual clarity

**Icon Additions:**
“make-same-width”
“make-same-height”
“make-same-size”
“distribute-vertically”
“number”
“dropdown-indicator”
“team”
“calendar-user”
“calendar-check”
“calendar-cancel”
“calendar-team”
“billboard”
“billboard-pending”
“tag”

**Updated Log0s**
Now have a trademark and come in 4 colors

icon-logo
icon-logo-dark
icon-logo-white-trademark
icon-logo-white

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.57.0-beta. moving this ticket to Done. thanks

**Comment by jbrcna** [comment]
https://main-enterprise.demo.design.infor.com/components/icons/example-index.html
![image](https://user-images.githubusercontent.com/56722184/141736127-311bb71d-b55a-4bf4-8bce-0275bbf20db1.png)

https://main-enterprise.demo.design.infor.com/components/datagrid/test-images-error.html
![image](https://user-images.githubusercontent.com/56722184/141736269-1f518c77-3a5f-4ca2-be9b-e6ef6f9a84d8.png)

https://main-enterprise.demo.design.infor.com/components/icons/example-logos.html
![image](https://user-images.githubusercontent.com/56722184/141736310-bed64caf-5427-47a5-b98e-45a09c7ed989.png)
