### ISSUE TITLE
[iOS Safari] Checkboxes misaligned inside Multiselect

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#578]
**Describe the bug**
When viewing the Multiselect component on an iOS Device, the checkbox graphics on the left side are not vertically centered against the text contents of each list item.

**To Reproduce**
- Go to http://master-enterprise.demo.design.infor.com/components/multiselect/example-index
- Open any multiselect list

Notice that all the checkboxes are not correctly aligned.

**Expected behavior**
The checkboxes should be correctly aligned.

**Screenshots**
<img width="256" alt="screen shot 2018-08-08 at 12 57 23 pm" src="https://user-images.githubusercontent.com/3249601/43852272-cda82e08-9b0a-11e8-91fc-c8e4de90d774.png">

**Platform**
 - Device: iPhone/iPad
 - OS Version: iOS 11
 - Browser Name: Safari

**Additional context**
Not an issue on Desktop Safari

**Comment by tmcconechy** [comment]
This issue seems to have been fixed along the way, no longer seeing any layout issues
