### ISSUE TITLE
Editor: The fontpicker tooltip is not translated in some locale

### ISSUE THREAD

**Issue by NicholTamayo** [infor-design/enterprise#5784]
**Describe the bug**
Observed that the frontpicker tooltip is not translated in the following locale:
- Afrikaans (South Africa)
- Bulgarian (Bulgaria)
- Czech (Czech Republic)
- Danish (Denmark)
- Estonian (Estonia)
- Finnish (Finland)
- Greek (Greece)
- Hebrew (Israel)
- Hungarian (Hungary)
- Italian (Italy)
- Korean (Korea)
- Latvian (Latvia)
- Lithuanian (Lithuania)
- Norwegian (Norway)
- Portuguese (Brazil)
- Portuguese (Portugal)
- Romanian (Romania)
- Slovakian (Slovakia)
- Slovenian (Slovenia)
- Thai (Thailand)
- Turkish (Turkey)
- Vietnamese (Vietnam)

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index?locale=fi-FI' or in any locale mention in the description.
2. Hover to the fontpicker dropdown.
3. Observed that the tooltip is in English instead of Finnish (Finland), other buttons are translated correctly.

**Expected behavior**
The tooltip in fontpicker dropdown is translated correctly.

**Version**
- ids-enterprise: 4.56.0

**Screenshots**
![The fontpicker tooltip is not translated in some locale](https://user-images.githubusercontent.com/79066908/138782806-321b3b28-5d20-4a03-9a17-43f1a374b7a2.gif)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Window 10
 - Browser Name: Chrome
 - Browser Version: Chrome/Version 95.0.4638.54 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
We do have the translation strings but they seem not to be applied https://main-enterprise.demo.design.infor.com/components/editor/example-index.html?locale=da-DK

**Comment by yohannahbautista** [comment]
@tmcconechy @ericangeles @NicholTamayo 
Hello, I checked the tooltip and I think this is because several of the locale files don't have a value for ChooseFont, so it defaults to English. If I go to http://localhost:4000/components/editor/example-index?locale=es-ES the font tooltip has a translation, and when I check the es-ES.js file it has ChooseFont. fi-FI.js doesn't have ChooseFont. There may be missing translations in the locale files.

**Comment by tmcconechy** [comment]
cc @hwondergem
Can you have a look at ChooseFont? I see its english in IT and missing in some locales. I updated the file at nlbavwmemoq2/cc/ToDev/SohoUX/ to be current.

Thanks @yohannahbautista we will have to wait for these. i saw some were there so i thought we had all of them.

**Comment by hwondergem** [comment]
Hi @tmcconechy , strange, as I find the following (all translated): 
  \\nlbavwmemoq2\cc\ToDev\SohoUX\af-ZA-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Kies fontstyl', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\ar-EG-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'اختيار نمط الخط', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\ar-SA-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'اختيار نمط الخط', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\bg-BG-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Избор на стил на шрифт', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\cs-CZ-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Vyberte styl písma', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\da-DK-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Vælg typografi', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\de-DE-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Schriftschnitt auswählen', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\el-GR-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Επιλογή στυλ γραμματοσειράς', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\es-ES-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Escoger estilo de fuente', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\et-EE-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Vali fondi laad', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\fi-FI-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Valitse kirjasintyyppi', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\fr-CA-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Choisir un style de police', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\fr-FR-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Choisir un style de police', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\he-IL-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'בחר סגנון גופן', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\hi-IN-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'फ़ॉन्ट शैली चुनें', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\hr-HR-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Odaberi stil fonta', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\hu-HU-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Betűtípus kiválasztása', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\id-ID-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Pilih Gaya Font', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\it-IT-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Scegli stile carattere', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\ja-JP-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'フォントスタイルの選択', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\ko-KR-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: '글꼴 스타일 선택', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\lt-LT-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Pasirinkti šrifto stilių', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\lv-LV-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Izvēlieties fonta stilu', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\ms-MY-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Pilih Gaya Fon', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\nb-NO-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Velg skriftstil', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\nl-NL-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Lettertypestijl kiezen', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\nn-NO-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Velg skriftstil', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\pl-PL-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Wybierz styl czcionki', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\pt-BR-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Escolher estilo da fonte', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\pt-PT-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Selecionar estilo de tipo de letra', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\ro-RO-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Selectare stil font', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\ru-RU-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Выберите стиль шрифта', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\sk-SK-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Výber štýlu písma', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\sl-SI-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Izberite slog pisave.', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\sv-SE-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Välj teckenstil', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\th-TH-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'เลือกรูปแบบตัวอักษร', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\tl-PH-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Pumili ng Estilo ng Font', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\tr-TR-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Yazı Tipi Stili Seç', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\uk-UA-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Виберіть стиль шрифту', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\vi-VN-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: 'Chọn kiểu phông', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\zh-CN-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: '选择字形', comment: 'Choose a font style' },
  \\nlbavwmemoq2\cc\ToDev\SohoUX\zh-TW-messages.js (1 hit)
	Line 47:   ChooseFont: { id: 'ChooseFont', value: '選擇字型樣式', comment: 'Choose a font style' },

**Comment by tmcconechy** [comment]
Ok thanks. I Presume it will work when i pull the next drop of the translations and merge them.

**Comment by jbrcna** [comment]
this is working as expected. v4.59.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/editor/example-index.html?locale=fi-FI
![image](https://user-images.githubusercontent.com/56722184/147622944-ac3b2b0a-9eef-4935-8f23-4f767d0501a8.png)

**Comment by xqses** [comment]
Hi,
Should this be fixed in 4.59.4? We are still having this problem in Homepages.

**Comment by tmcconechy** [comment]
It is verified as fixed on our end. Should be in 4.59.4 - but you could also try

- 4.60.0 just in case...
- and making sure your locale files have been updated depending how you bring them in
- making sure you set the locale ahead of initializing the editor

Can see it translated here:
https://main-enterprise.demo.design.infor.com/components/editor/example-index.html?locale=fi-FI
