### ISSUE TITLE
Calendar: Week number required on views/date-time selection.

### ISSUE THREAD

**Issue by pbal** [infor-design/enterprise#5785]
**Is your feature request related to a problem or use case? Please describe.**
Week number required on Calendar views/date-time selection.

**Describe the solution you'd like**
Week number selection here 
![image](https://user-images.githubusercontent.com/1594975/138790520-b49e1829-445c-4728-92ce-aa76bdf0e092.png)

**Describe alternatives you've considered**
None

**Additional context**
Customer request here https://jira.infor.com/browse/MCRM-15310
Also raised https://jira.infor.com/browse/MGD-3520 for adding feature to Mongoose Platform

**Comment by tmcconechy** [comment]
How does this look in mongoose? Is it just the week number? As having a hard time understanding what you would select and what you would show in the field after?

**Comment by pbal** [comment]
It is not implemented in Mongoose as of now. Linked jira in description is still in MGD dev queue.

**Comment by tmcconechy** [comment]
cc @kevinwhitedesign any thoughts on how this should look?

**Comment by kevinwhitedesign** [comment]
I'd like to understand the usecase a bit more @pbal why would someone need this?

**Comment by tmcconechy** [comment]
FYI @kevinwhitedesign week numbers are used a lot in Europe and logistics.

> Week numbers are used around the world, mostly by companies. It is most often used in international logistics and international project management where it is often not possible to specify a specific date due to date and time differences in various countries. In this case “time buckets” may defined in weeks.

Just my two cents

**Comment by tmcconechy** [comment]
> Calendar week is the main language when talking with FMCG customers. Any promotion will be aligned based on the calendar week. 

Similar to what i know about using week numbers for weeks vs a date range

**Comment by elizabethhartley** [comment]
hi @pbal, are you proposing to add a third week number (1-4) column on the month and year picker or a separate 1-52 week picker?

**Comment by pbal** [comment]
either month+year or week.

**Comment by tmcconechy** [comment]
Just to confirm would it suffice to show the week number on the calendar on the left side (right side in right to left). On the datepicker popup and monthview.

If so we just need design feedback on placement and color of it. For the single week picker i think we can use dropdowns.

**Comment by inforrpunay** [comment]
> Just to confirm would it suffice to show the week number on the calendar on the left side (right side in right to left). On the datepicker popup and monthview.
> 
> If so we just need design feedback on placement and color of it. For the single week picker i think we can use dropdowns.

Hi @tmcconechy,

For the M3 requirement, yes it would suffice. We had this in the old infor controls and some customers are looking for it.
![image](https://user-images.githubusercontent.com/55830499/195289357-8192aa4e-3580-4d3f-a194-dd54ed340581.png)

**Comment by tmcconechy** [comment]
@inforandy just need a quick design for font size and color (dark and light mode and classsic) for the new text for the week number

**Comment by inforandy** [comment]
@tmcconechy got it, we are going to bundle this work in progress here https://www.figma.com/file/DnguXUS7T4J5Rce92MuoCY/Datepicker?node-id=1674%3A455&t=5oeVCrQ7TK0F37O2-0 

This is the design for selecting the week, we just want to make sure we are aligned for displaying the week number in the datepicker as well

**Comment by tmcconechy** [comment]
<img width="510" alt="Screenshot 2022-12-20 at 2 40 55 PM" src="https://user-images.githubusercontent.com/814283/208752595-d8f162ae-be5d-45d3-98fc-2e1f60ea9634.png">

**Comment by inforandy** [comment]
adjusted the permissions, should be good now

**Comment by tmcconechy** [comment]
Can the developer that adds this also do a PR for WC?

**Comment by tmcconechy** [comment]
@ericangeles this is ready -> just add a setting to datepicker and show this:
<img width="343" alt="Screenshot 2023-01-18 at 9 23 53 AM" src="https://user-images.githubusercontent.com/814283/213196335-8aa84268-9ef3-4067-96cb-9e5d7c20ae10.png">

Rest can be used later if required

**Comment by glenlieorillo** [comment]
Tested and passed.

Verified in https://main-enterprise.demo.design.infor.com/components/datepicker/test-show-week-number.html

https://user-images.githubusercontent.com/102151352/218915284-dcabfc9a-7e44-489f-8bc8-d61b71e07c94.mov

**Comment by ericangeles** [comment]
@tjamesallen15 please add this feature to NG wrapper.
