### ISSUE TITLE
Tooltip: disappeared after moving mouse up in keep open example

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5787]
**Describe the bug**
Tooltip: disappeared after moving mouse up in keep open example

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tooltip/example-keep-open.html?theme=classic&mode=light&colors=2578a9
2. Hover to the link
3. Move mouse up 

**Expected behavior**
Tooltip should stay opened

**Version**
4.57 - ids - dev 

**Screenshots**
N/a

**Platform**
Windows 10 Chrome and other major OS and browsers. 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
This is a known bug with the fact that header has a tooltip in it and it will hide. Could be tough to resolve so might wait for the new version to close this
