### ISSUE TITLE
Inputs: Create generic wrapping element for input-field-based components

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#579]
**Is your feature request related to a problem? Please describe.**
Some use cases have come up that would benefit from having a top-level wrapper element (f.x.: `<div class="input-wrapper">` surrounding `<input type="text" />`).  Some of our more complex components already have a wrapping element for the purpose of containing multiple trigger elements:

- Spinbox needs a wrapper element to contain its two buttons and the number input
- Dropdown/Multiselect contain a text span, and one or several icons (always a dropdown arrow, sometimes a custom icon)
- Complex Searchfields can have a popupmenu trigger, input field, and go button
- Any form input can have Field Options and Validation icons attached

Each of these components implements a custom wrapper that has its own set of CSS rules for structure.

Some use cases for permanent Field Options attachment (#555) and needing a non-disabled base element to fire events (f.x.: displaying a tooltip on disabled items -- #453) have come up that show a benefit for having a generic element surrounding all input fields, that could have common structure that all these components could use.

Structure might look like:
![example](https://user-images.githubusercontent.com/3249601/43861189-11bdea74-9b24-11e8-9d5d-b47631eff90e.jpg)

**Describe the solution you'd like**

To make this work we'd need to:

- [ ] create a generic wrapping element that can be used on any input field:
  - removes the rounded border and related focus/hover states from the input field itself and places it on this wrapper element, when the wrapper is used.
  - flexbox-based to take advantage of fluid fill rules?  If done correctly could potentially allow as many icons or trigger buttons as necessary next to each input field, while making them all appear to sit inside the wrapper.
  - could use `white-space: nowrap` inside the wrapper element to ensure all the various items within the wrapper don't attempt to wrap to a second line (could be a better longterm fix for [misaligned field-options buttons](https://github.com/infor-design/enterprise/pull/573#issuecomment-411393437)  on regular text input fields).
- [ ] remove the custom wrapping elements from many of these components, and replace them with the generic one
- [ ] Retest on each field type: 
  - validation icons
  - dirty tracking
  - hover/focus/enabled/disabled/readonly states

**Comment by tmcconechy** [comment]
I agree with the 13 ranking entirely... Also should make sure each of these has a few basic tests first.

**Comment by tmcconechy** [comment]
Closing this in favor of https://github.com/infor-design/enterprise/issues/4244
