### ISSUE TITLE
Toolbar Search: close button 'x' is not centered

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5791]
**Describe the bug**
Toolbar Search: close button 'x' is not centered when in responsive view then maximized

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-index.html
and https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html and https://main-enterprise.demo.design.infor.com/components/toolbar/example-selected-event.html
2. Minimize the screen 
3. Then maximize the screen again

**Expected behavior**
'x' button should still be aligned center

**Version**
ids-4.57-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/139046389-a23860f1-2a04-4e37-ad62-32c9cc1c0125.png)
![image](https://user-images.githubusercontent.com/45757016/139047838-cc3caae8-ebb6-41cb-a768-d7109840ec5b.png)

**Platform**
Windows 10 Chrome and all major browsers and OS. 

**Additional context**
N/a

**Comment by ericangeles** [comment]
The only issue that I am seeing is the height of the collapse button on the smaller viewport.

**Comment by janahintal** [comment]
QA Passed. Thanks! 👍 
![image](https://user-images.githubusercontent.com/45757016/141077117-1eaa5211-691b-4a01-9b35-c1da15e9b82a.png)
