### ISSUE TITLE
Dropdown: Tab does not commit a changed value

### ISSUE THREAD

**Issue by johnvang** [infor-design/enterprise#5793]
**Describe the bug**
Clicking on a dropdown, typing a single letter and quickly hitting Tab does not commit the typed letter/option

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/dropdown/test-scenarios.html
2. Click on the 'Set Width Small' dropdown
3. type '7' and quickly follow by pressing TAB

Result:  value in the dropdown is unchanged

**Expected behavior**
Typing a valid value immediately followed by Tab ought to commit the typed value

**Version**

- ids-enterprise: 4.51.1

**Screenshots**

![dropdown-quick-tab](https://user-images.githubusercontent.com/10240604/139109395-9bee5d17-99b7-474c-a066-291bb4ab1d35.gif)

**Platform**
 - Infor Application/Team Name: Lawson

**Additional context**

**Comment by tmcconechy** [comment]
Could be a little tricky as we do a type delay. Maybe have to check if one character or somehow solve.

**Comment by awbuboltz** [comment]
Hey Tim, this is another customer issue for us. ETA?

**Comment by tmcconechy** [comment]
We have this for next sprint planning to review feasibility. (Probably fixable somehow). So expect fix during Dec for Jan release.

**Comment by tmcconechy** [comment]
@awbuboltz are you still seeing this on https://main-enterprise.demo.design.infor.com/components/dropdown/test-scenarios.html i know we fixed some related stuff? and now i dont

**Comment by awbuboltz** [comment]
Yeah I'm still seeing it, although now the cursor actually jumps back to the dropdown after tabbing.

**Comment by tmcconechy** [comment]
Yeah your right have to do it faster than the delay...

**Comment by jbrcna** [comment]
this is now working as expected. thank you. 
the value pressed is now being selected and the focus is on the next field after quickly pressing tab
v4.59.0-dev
https://main-enterprise.demo.design.infor.com/components/dropdown/test-scenarios.html
