### ISSUE TITLE
Busy Indicator: Add event to know when the indicator ends / hides

### ISSUE THREAD

**Issue by edgarinfor** [infor-design/enterprise#5794]
**Is your feature request related to a problem or use case? Please describe.**

The current busy indicator have a "start" event but, there is no counterpart for it...

Even though in most cases setting the "activated" property to "false" is enough, the fact that the UI takes a little bit of time to actually fade-out/hide and remove the DOM elements, there are instances where it's convenient to have an "end" event that tells you exactly when the indicator is gone.

**Describe the solution you'd like**

An Output/Event, it could be "end" or "ended" or any other name that fires when the indicator ends / hides.

**Describe alternatives you've considered**

Using timeouts or delays or checking for the presence of elements in DOM helps but, this should avoided.

**Additional context**

This is a small enhancement and, it could be considered as part of #5593.

Team: WFM

**Comment by tmcconechy** [comment]
There are two events https://github.com/infor-design/enterprise/blob/main/src/components/busyindicator/busyindicator.js#L282-L283 

Can you use these? Also wouldnt you know when you called it to hide it?

**Comment by edgarinfor** [comment]
Based on the documentation here: https://design.infor.com/code/ids-enterprise/latest/busyindicator

The "complete" event seems to be used for something else (or the description is confusing) and, the "aftercomplete" one is not on the list.

We know when we "call to hide it" but, the busy indicator and it's DOM elements DO NOT disappear immediately from the UI as there is a transition that happens. So, in some occasions, trying to perform an action immediately after "calling to hide it" can conflict. 

The idea here, is to have a event that let's you know when the hiding transition has ended and the DOM elements are removed (everything goes back to normal).

The name "aftercomplete" sounds like it could be what we need, if it does what I just described above, otherwise, we need a different event.

By the way, we are using this in Angular so, maybe this ticket was meant for the "ng" project.

**Comment by tmcconechy** [comment]
We probably need the event in both sides so this is a fine place. To start lets get @EdwardCoyle  to review your comments when he can and see if he has a suggestion on the previous comment.

Can you explain the use case as well?

**Comment by edgarinfor** [comment]
The use case is essentially to resolve a "timing" issue caused by the gap between "calling to hide" and "hidden" due to the transition changes.

For example, we've seen instabilities in our Automation (Cucumber, Selenium) where an ASYNC action has been completed and the test tries to perform the next step but, the Busy Indicator elements are still on the way.

Similarly, in some occasions, when we try to display or update the content after "calling to hide" but, the elements are momentarily on the way as well.

It's a subtle situation and it can be tricky but, having the option to tell when the busy indicator is completely gone would definitely help keeping things tidy.

**Comment by tmcconechy** [comment]
Lets try to make the aftercomplete event fire "later" so that it fires after its gone. If possible rather than adding a new event

**Comment by jbrcna** [comment]
QA Passed
v4.59.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/busyindicator/example-stop-event.html
![image](https://user-images.githubusercontent.com/56722184/147024316-c36defd4-ce3a-404f-9ab1-853d20b53e61.png)
