### ISSUE TITLE
Modal: Dialog containing a datagrid the title is overlapping the close button

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5795]
**Describe the bug:**
The modal title is overlapping with the close button.

**Steps to reproduce the behavior:**
1. Using the attached 'test-modal-datagrid-title-overlap.html'
2. Click on 'Open Modal'
3. Notice that the modal title, Select 'Finance Dimension 6' is overlapping with the X (close button) 

**Expected behavior:**
The X (close button) should not overlap the modal title.

**Version**
- ids-enterprise: v4.57.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/39804038/139140937-42cc84f6-cd5a-4000-874a-93a98e6839e7.png)

**Additional context**
Note:  The pager is absent because landmark would use the soho-standalone-pager.

**Comment by jbrcna** [comment]
QA Passed. v4.59.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/modal/test-modal-datagrid-title-overlap.html
![image](https://user-images.githubusercontent.com/56722184/146748527-d2e25105-1a34-4d14-b16d-a26e46139eef.png)
