### ISSUE TITLE
Modal: Dialog does not always close with escape key

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5796]
**Describe the bug**
A modal dialog that contains a datagrid, when focus is on a filter row input element, the escape key is not closing the dialog. 

1. Using the attached 'test-modal-datagrid-escape-closing.html'
2. Click on 'Open Modal'
3. Using the shift+tab key or using mouse set focus on a filter row input element
4. Hit the escape key

**Expected behavior**
Escape key will close the modal regardless of which element has the focus.

**Version**

- ids-enterprise: v4.57.0-dev

**Additional context**
Many Landmark clients are keyboard users, so they expect consistent behavior for hotkeys.

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.59.0-dev.

https://main-enterprise.demo.design.infor.com/components/modal/test-modal-datagrid-escape-closing.html

Moving this ticket to Done.

Thanks!
