### ISSUE TITLE
Search: 'X'(close) button is overlapping with search icon in rtl case

### ISSUE THREAD

**Issue by bveerabathini** [infor-design/enterprise#5807]
**Describe the bug**
Search 'X'(close) button is overlapping with search icon in rtl (right to left)case.

**To Reproduce**
We can reproduce on IDS Enterprise with locale=ar-SA ,
https://main-enterprise.demo.design.infor.com/components/searchfield/example-clear-api.html?locale=ar-SA

1. Type something on search input field.
2. you can see the 'X' button overlapping with search icon.

**Expected behavior**
Search icon and 'X' button should have some distance between them.

**Version**

- ids-enterprise: 4.55.2

**Screenshots**
![image](https://user-images.githubusercontent.com/85981034/139791011-7f18ca10-a52f-446f-bede-11e92a0ff60c.png)

**Platform**
 - Infor Application/Team Name: Infor LN
 - OS Version: Windows 10 
 - Browser Name: chrome
 - Browser Version: Version 95.0.4638.69 (Official Build) (64-bit)

**Additional context**

**Comment by nganotice** [comment]
This has been QA tested and passed on v4.59.0-dev.

https://main-enterprise.demo.design.infor.com/components/searchfield/example-clear-api.html?locale=ar-EG

![image0](https://user-images.githubusercontent.com/84306838/145312719-74770df7-afb1-4e37-b1ca-d33fc935c53b.gif)

Moving this ticket to Done.

Thanks!
