### ISSUE TITLE
Datagrid: Need options for fast data entry

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#5810]
**Is your feature request related to a problem or use case? Please describe.** 
For financial users we need to be able to tab from fitler bar input field to input field skipping the filter options menu and trigger button. 

**Describe the solution you'd like**
We'd like to have an option in the datagrid to skip tabbing to the filter options menu and filter field trigger button. While the trigger button can be executed with a downarrow key we need a short cut key to bring up the filter options menu.

**Describe alternatives you've considered**
Going directly into the dom ourselves to set tabIndex="-1" but we are not clear on how to force a keyboard shortcut from the fitler bar field for the filter options menu.

**Additional context**
Add any other context or screenshots about the feature request here. And what application do you work on? Landmark Client

**Comment by tmcconechy** [comment]
What about filter fields like dropdown and datepicker that already use down arrow for the picker?

**Comment by tmcconechy** [comment]
A little like https://main-enterprise.demo.design.infor.com/components/searchfield/example-categories-short.html but we need the down arrow functionality added.

Add option to tabindex="-1" and add the down arrow functionality.

**Comment by tmcconechy** [comment]
We are thinking about this again. We think this will create problems for accessibility and for your VPAT. We think we should hold off on this.

**Comment by pwpatton** [comment]
Hadn't seen this in a while... landmark has a flag for users to enable or disable "accessibility" mode. The idea is that for the datagrid we'd need a flag that switched between these 2 modes as well.
