### ISSUE TITLE
About: Incorrectly shows operating system as Windows 10 instead of Windows 11

### ISSUE THREAD

**Issue by xqses** [infor-design/enterprise#5813]
**Describe the bug**
When tenant is accessed in Windows 11 instance; About is displaying OS as Windows 10 instead of Windows 11

**To Reproduce**

0. Run a Windows 11 instance.
1. Goto https://design.infor.com/code/ids-enterprise/latest/about
2. Click the Show About Screen button
3. Scroll down to the device specs information
4. See wrong operating system for the browser. 

**Expected behavior**
About should display the OS as Windows 11, as this is performed in Windows 11 instance.

**Version**

- ids-enterprise:  4.56.0

**Platform**
 - Infor Application/Team Name: Portal V2 Development
 - OS Version: Windows 11
 - Browser Name: Edge Chromium
 - Browser Version: 95.0.1020.40

**Additional context**
Observed and reported in PortalV2 testing.

**Comment by tmcconechy** [comment]
Please fix this on EP and WC projects. This can be tested on browser stack as it now has Windows 11.

@CindyMercadoReyes maybe you can use Windows 11 as the primary windows device for QA now as its new and we can see if we find anything else.

**Comment by tmcconechy** [comment]
@ericangeles when working on this please adjust the web component version as well?

**Comment by tmcconechy** [comment]
In addition the about isnt correct for Mac Monterey. I have this so i can help out with this.

**Comment by tmcconechy** [comment]
Note: Because using the userAgent is deprecated the last few browser/os versions do not update this information. So the version can no longer be obtained. For this reason the version now removed from the OS field on the about dialog

**Comment by janahintal** [comment]
QA Passed.  OS version is now removed in About https://main-enterprise.demo.design.infor.com/components/about/example-index.html

Windows 11
![image](https://user-images.githubusercontent.com/45757016/147631596-eb69f973-5738-41f5-a22f-1778b5438d6b.png)
![image](https://user-images.githubusercontent.com/45757016/147631535-335579f6-c652-4ac7-946d-0f17de03bfb2.png)

BrowserStack MacOS
![image](https://user-images.githubusercontent.com/45757016/147631633-c73d4d14-cfb9-4b29-80c6-f6a878df6096.png)
![image](https://user-images.githubusercontent.com/45757016/147627305-53666a22-f389-4565-b8b4-0257dc95da4e.png)
