### ISSUE TITLE
No space needed before colon (this applies to all languages including English. Exception: French locales)

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5817]
**GENERIC RULE:
No space needed before colon. This applies to all languages including English
Exception: A non-breaking space is required before : in French locales (e.g. French (France) and French (Canada))**

Example:
- Homepages > About.
- Swedish and English -> No space needed

Incorrect:

![image](https://user-images.githubusercontent.com/66057969/140296149-37a5f53c-d18e-4222-bba3-25b1f8bd8241.png)

This issue belongs to IDS:
Homepages team: "Most of the About dialog content in Homepages is set from IDS (The copyright and below) https://design.infor.com/code/ids-enterprise/latest/about"

**Comment by tmcconechy** [comment]
So to clarify..

1) French is: `Operating System:MacOS` (no spaces at all?)
2) All other languages is `Operating System : MacOS`

?

**Comment by cpinatel7** [comment]
Not really. In short, there are 2 sets of **generic rules**: Rules for French locales and rules for all other locales including English. Currently, IDS is only correct for French locales.

1. No space needed **before** colon. This applies to all languages including English
Operating System : MacOS -> Current display. Incorrect
Operating System: MacOS -> Correct

2. A **non-breaking space** is required before : in French locales (e.g. French (France) and French (Canada))
Operating System : MacOS -> Correct

**Comment by cpinatel7** [comment]
If colons are included in the strings provided for translation, colon requirements are handled by linguists during the translation process. However, in the present case, colons are appended at run-time therefore colon rules need to be implemented / followed by Dev. Thanks

**Comment by cpinatel7** [comment]
If the same label is used on 2 different pages e.g. page 1 (no colon) > Operating System and page 2 (with colon) > Operating System:, appending : at run-time will save time / reduce translation cost as only 1 label needs translating. In this scenario, developers need to implement the proper colon rules in their code.
I think including it in the strings provided for translation is cleaner. However, I don't know if it's a generic issue in IDS and how many strings will be impacted. Maybe it's too late as we don't want to re-translate everything and have different labels - with and without colons - in IDS. In this case, the logic needs to be changed with an IF in the code. Thanks

**Comment by tmcconechy** [comment]
We'll double check but i think these are just for that about page so should be ok.

**Comment by cpinatel7** [comment]
Also incorrect on this page. Does it belong to IDS?
![image](https://user-images.githubusercontent.com/66057969/140348452-7bfa5ca2-c2e7-48a3-91e3-4c416b24fe68.png)

**Comment by tmcconechy** [comment]
No not that last screen shot this is just a text input for the Dev team (we dont even have that at all in the example https://main-enterprise.demo.design.infor.com/components/about/example-index.html )

**Comment by tmcconechy** [comment]
One option for a fix is to use Bold Text and then regular text (no semi colon).

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
