### ISSUE TITLE
Context menu: Shared menu breaks if a datagrid is present on the page

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#5818]
**Describe the bug**
When a context menu (e.g. popupmenu control) is shared among multiple triggers, the menu breaks if one of the triggers is removed **when there is a datagrid present on the page**. This is a regression issue.

**To Reproduce**
I'm actually unable to reproduce this in the core controls, but we see this when using the ng components, so it should be reproducible there (I'm reporting it here rather than enterprise-ng since the cause is in the core control)

1. Edit the context-menu/context-menu-shared.demo.html in enterprise-ng samples to simply include a datagrid (doesn't need any data or anything, just created)
`<div soho-datagrid></div>`
2. Click the "Destroy Input Popup" button
3. Right click the text area
**Result**: Popup not shown / popup not positioned correctly (we see both in certain scenarios)

**Expected behavior**
The shared menu should not be destroyed, since there are triggers left for it. A datagrid present on the page should not affect & destroy a completely different menu. This code in `popupmenu.teardown()` is what's causing the issue:

```
const otherTriggers = $(`[aria-controls="${menuId}"]`).not(this.element);
 // Needs to check to unwrap and wrap the menu in datagrid
const datagridFilterWrapper = $('.datagrid-filter-wrapper');

if (!otherTriggers.length || datagridFilterWrapper.length > 0) {
      // Destroy, teardown etc. happens here
     ...
}
```
https://github.com/infor-design/enterprise/commit/3c7ec2007254b27f7238c1c08e78f12283400e9e#diff-b06106137d1a69bd28f432d8c8b19dddc9714fea7df3462dbf570c09983197c0

So even if there are other triggers, destroy happens due to $('.datagrid-filter-wrapper') present.

**Version**
- ids-enterprise: 4.56.0

**Additional context**
https://github.com/infor-design/enterprise-ng/issues/987
We've previously reported a similar issue, where the shared menu got broken when removing a trigger, no matter what. The `otherTriggers` code was added to fix that, but now we see it again due to the added datagrid check.

**Comment by tmcconechy** [comment]
@ericangeles had to prioritize this one as well for T2V

**Comment by janahintal** [comment]
QA Passed. Thanks! Will now move this to Done.
