### ISSUE TITLE
Homepage: Convert Protractor Tests to Puppeteer

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#5831]
**Is your feature request related to a problem or use case? Please describe.**
Convert homepage component tests to puppeteer.

**Describe the solution you'd like**
Convert all tests scenarios in protractor to puppeteer. For the naming can be, `{component}.puppeteer-spec.js`

**Describe alternatives you've considered**
N/A

**Comment by janahintal** [comment]
Working as expected. Will now move this to done. 
![image](https://user-images.githubusercontent.com/45757016/156550439-38c8684a-32dc-463b-8038-a5ed8ce802bb.png)
