### ISSUE TITLE
Area: Convert Protractor Tests to Puppeteer

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#5834]
**Is your feature request related to a problem or use case? Please describe.**
Convert area component tests to puppeteer.

**Describe the solution you'd like**
Convert all tests scenarios in protractor to puppeteer. For the naming can be, `{component}.puppeteer-spec.js`

**Describe alternatives you've considered**
N/A

**Additional context**
For the visual regression tests, no need to convert and leave it as is for the meantime.

**Comment by CindyMercadoReyes** [comment]
This is now resolved.
