### ISSUE TITLE
Header Tabs: Border styling not aligned when zoomed

### ISSUE THREAD

**Issue by Annfo637** [infor-design/enterprise#5837]
**Describe the bug**
We are using header tabs in our project and discovered that the border styling isn't aligned correctly when selecting a tab. The same behavior is seen in the Header Tabs Test: Spillover Example. The border for a selected tab doesn't align with the text and border-bottom for the tab. It is not visible on all tabs, but it seems that the text/border-bottom increases overflowing to the right the higher the tab number you click on (the more to the right the tab is placed). See screenshots for tab 6 and 9.

Also, for Header Tabs 4 the overflow occurs every other time to the left and every other time to the right when you click to zoom in/out the browser. Overall, the overflow is more or less prominent/existing and also changes between the tabs in a pattern that is not clear to me.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs-header/example-index.html
2. Click on the tabs mentioned in description above
3. When tab 4 is selected, open browser settings and zoom in/out to see changes in the overflow.
4. See error/errors

**Expected behavior**
The border around the selected tab should always be aligned with the text and border-bottom for all tabs and regardless of browser zoom level.

**Version**

- ids-enterprise: v4.56.0

**Screenshots**
![image](https://user-images.githubusercontent.com/54262041/141107113-20df21ab-2dc2-4ce0-8b5f-7070fab6b38a.png)

![image](https://user-images.githubusercontent.com/54262041/141107139-66ec5b51-3b1a-4a70-8ce8-7c311d38afba.png)

**Platform**
 - Infor Application/Team Name: Portal V2
 - OS Version: Windows 10
 - Browser Name: Chrome and Edge
 - Browser Version: Version 95.0.4638.69 (Official Build) (64-bit) and Version 95.0.1020.40 (Official build) (64-bit)

**Comment by tmcconechy** [comment]
We had corrected this somewhat, but think this is a follow up issue. We need to correct the css.

**Comment by jbrcna** [comment]
**QA Passed**
v4.58.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html
Header 6
![image](https://user-images.githubusercontent.com/56722184/144190277-991a8718-c34b-4d42-9d5b-e00baae0ca87.png)

Header 9
![image](https://user-images.githubusercontent.com/56722184/144190300-ac2a545c-55cc-4abf-8034-7a444683cfa7.png)

Header 4 zoom 150%
![image](https://user-images.githubusercontent.com/56722184/144190334-5b33f377-97b8-4293-a411-c1d8bf283293.png)
