### ISSUE TITLE
Bar Grouped: Convert Protractor Tests to Puppeteer

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#5839]
**Is your feature request related to a problem or use case? Please describe.**
Convert bar grouped component tests to puppeteer.

**Describe the solution you'd like**
Convert all tests scenarios in protractor to puppeteer. For the naming can be, `{component}.puppeteer-spec.js`

**Describe alternatives you've considered**
N/A

**Comment by CindyMercadoReyes** [comment]
This task is completed
