### ISSUE TITLE
DatePicker: Create a Puppeteer Script for the ability to set first day of week in date picker configuration

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#5841]
Describe the Issue
Create a unit testing for the ability to set first day of week in date picker configuration.

See attached BDD for more information.
[story_github#1179.docx](https://github.com/infor-design/enterprise/files/7512771/story_github.1179.docx)

Related github issue
#1179

**Comment by maezcruz** [comment]
cc: @CindyMercadoReyes

**Comment by ericangeles** [comment]
@maezcruz it looks like it has unit testing (protractor) already. This will be under the dev work to convert to puppeteer. Will now close the ticket. Thanks!
