### ISSUE TITLE
Dropdown: Create a Puppeteer Script for Enter key opens dropdown list, when it should only be used to select items within an open list

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#5842]
Describe the Issue
Create a unit testing for Enter key opens dropdown list, when it should only be used to select items within an open list.

See attached BDD for more information.
[story_github#1239.docx](https://github.com/infor-design/enterprise/files/7512787/story_github.1239.docx)

Related github issue
#1239

**Comment by maezcruz** [comment]
cc: @CindyMercadoReyes

**Comment by janahintal** [comment]
Test covered in #6000. This ticket can now be closed. Thank you.
