### ISSUE TITLE
Datagrid: Create a Puppeteer Script for keeping the last column stretched

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#5844]
Describe the Issue
Create a unit testing for keeping the last column stretched.

See attached BDD for more information.
[BDD_github#2130.docx](https://github.com/infor-design/enterprise/files/7512861/BDD_github.2130.docx)

Related github issue
#2130

**Comment by maezcruz** [comment]
cc: @CindyMercadoReyes

**Comment by CindyMercadoReyes** [comment]
This task is now completed.
