### ISSUE TITLE
Datagrid: a column's maskOptions function is never called when grid has filtering

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5847]
**Describe the bug**
A column's maskOptions function is never called when the datagrid also has a filter row.  Within the method filterRowHtml() in datagrid.js for a column filter type of 'integer', 'decimal', or 'percent' if a function is defined it will be overwritten with the default mask options.

Believe the code should be something like...

```
      if (col.filterMaskOptions && typeof col.filterMaskOptions !== 'function') {
        col.filterMaskOptions = utils.extend(true, {}, decimalDefaults, col.filterMaskOptions);
      }

      if (col.maskOptions && typeof col.maskOptions != 'function') {
        col.maskOptions = utils.extend(true, {}, decimalDefaults, col.maskOptions);
      }
```

**To Reproduce**
1. Using the attached 'test-dynamic-mask-with-filter.html'
2. Edit the Quantity for the Phone product 
3. Notice that decimal values can be entered
4. Alert statement within the maskOptions function is never reached

**Expected behavior**
Support maskOptions function and a filterMaskOptions function to dynamically change a mask.

**Version**
- ids-enterprise: v4.58.0-dev

**Additional context**
Several Landmark clients are requesting this functionality including custInfor.

**Comment by claudenbach** [comment]
[Git-5847.zip](https://github.com/infor-design/enterprise/files/7515742/Git-5847.zip)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
