### ISSUE TITLE
Counts: Create a Puppeteer Script for Counts' Mobile Enhancements and style changes

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#5850]
Describe the Issue
Create a unit testing for Counts' Mobile Enhancements and style changes.

See attached BDD for more information.
[BDDStory_github5588.docx](https://github.com/infor-design/enterprise/files/7520766/BDDStory_github5588.docx)

Related github issue
#5588

**Comment by maezcruz** [comment]
cc: @CindyMercadoReyes

**Comment by ericangeles** [comment]
This ticket has been resolved on this PR https://github.com/infor-design/enterprise/pull/5771
