### ISSUE TITLE
Datagrid: Create a Puppeteer Script for Allowing a selected filter condition

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#5853]
Describe the Issue
Create a unit testing for for allowing a selected filter condition.

See attached BDD for more information.
[BDDStory_github5750.docx](https://github.com/infor-design/enterprise/files/7520797/BDDStory_github5750.docx)

Related github issue
#5750

**Comment by maezcruz** [comment]
cc: @CindyMercadoReyes

**Comment by janahintal** [comment]
This one is Done. Covered in previous deployment. 
![image](https://user-images.githubusercontent.com/45757016/148364187-4e272695-bbf3-4119-bce5-4a187c762595.png)
