### ISSUE TITLE
Message: Create a Puppeteer Script for Mobile Enhancements and style changes

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#5856]
Describe the Issue
Create a unit testing for Message Mobile Enhancements and style changes.

See attached BDD for more information.
[BDDStory_github5567.docx](https://github.com/infor-design/enterprise/files/7520875/BDDStory_github5567.docx)

Related github issue
#5567

**Comment by maezcruz** [comment]
cc: @CindyMercadoReyes

**Comment by tmcconechy** [comment]
@maezcruz can you make an estimate on the issues (label 1, 2, 3, 5 depending on relative complexity)

**Comment by maezcruz** [comment]
@tmcconechy Hi Tim, yep for now we can add high-level estimates. Going forward, we will refine a process wherein the team can provide initial estimates before I add the for Unit Test tickets. Thank you. :)
