### ISSUE TITLE
Create a Puppeteer Script for Split program when a user drops a tab on another tab

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#5857]
Describe the Issue
Create a unit testing for Split program when a user drops a tab on another tab.

See attached BDD for more information.
[BDDStory_github4600.docx](https://github.com/infor-design/enterprise/files/7520998/BDDStory_github4600.docx)

Related github issue
#4600

**Comment by maezcruz** [comment]
cc: @CindyMercadoReyes

**Comment by tmcconechy** [comment]
@maezcruz and @CindyMercadoReyes Im wondering if we need to create EVERY issue and if we will actually do all these as this effecting our bug and backlog count a lot.

Maybe you just make all the ones for one just the sprint that you will definitely do first. Not sure if you do plan to do all these pretty soon but it seems like a lot.

**Comment by ericangeles** [comment]
Assigning to the devs as this one is difficult for the QAs, and we also need to create util for drag and drop functionality for automation.

**Comment by tmcconechy** [comment]
descoping this as may change test framework
