### ISSUE TITLE
Datagrid: Issue with personalizing columns when multiple datagrids

### ISSUE THREAD

**Issue by jayblack-infor** [infor-design/enterprise#5859]
**Describe the bug**
Using datagrid method personalizeColumns() is not working correctly when multiple datagrids on the page.

**To Reproduce**
Go to the sample  to reproduce: https://main-enterprise.demo.design.infor.com/components/datagrid/test-multiple-grids.html 

On 1st datagrid select personalize columns from the menu and select the hidden column activity date.   If you click on the menu for the 2nd grid activity date shows as being selected but it doesn’t appear in the 2nd grid.   

**Expected behavior**
When you have multiple datagrids on a page you should be able to personalize each datagrid by hiding/showing columns and it only affects that datagrid.

**Version**

- ids-enterprise: v4.56

**Comment by tmcconechy** [comment]
one thing to check is that is the data the same? i.e. need two different array instances

**Comment by jbrcna** [comment]
QA Passed. v4.59.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-multiple-grids.html
![image](https://user-images.githubusercontent.com/56722184/147623526-6965f219-2c59-4852-badf-4b2da6f4e47c.png)
