### ISSUE TITLE
Role attribute value is misspelled on kitchen sink page

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#586]
**Describe the bug**
- `role="presentation"` is misspelled as `role="presenatation"` on kitchen-sink.html in buttons section.

**To Reproduce**
Pull down and run the app and browse to localhost:4000/kitchen-sink. Open developer tools and view the `role` attribute on the buttons in the Button section.

**Expected behavior**
role="presenatation" should change to proper spelling of role="presentation"

**Screenshots**
![screen shot 2018-08-09 at 3 30 39 pm](https://user-images.githubusercontent.com/7952168/43921274-3a30f5f8-9be9-11e8-93c1-fbba7c6cb07c.png)

**Platform**
All platorms.

**Comment by tmcconechy** [comment]
19 Places in 6 files - good call.

**Comment by davidcarlsonberg** [comment]
@theakatz  Please add to current sprint.
