### ISSUE TITLE
SearchField: White toolbar search field background

### ISSUE THREAD

**Issue by ryan-bailey-infor** [infor-design/enterprise#5865]
**Is your feature request related to a problem or use case? Please describe.**
When using the search field component (normally white background) inside of a toolbar, the background is overwritten to a gray background that looks inconsistent with the rest of the UI elements within the toolbar. 

**Describe the solution you'd like**
Either a user-definable flag or a default behavior (white background) that mirrors the stock search field component.

**Describe alternatives you've considered**
We have overwritten the styles in css which will lead to more custom rewrites as we attempt to stay on the current IDS version.

**Additional context**
This is currently being used on Infor App Designer (IAD).

We'd like this as the default (or flagged) behavior:
![noToolbar](https://user-images.githubusercontent.com/94412718/141869777-73a59f28-4629-4e0c-8c85-8e14705ef71a.jpg)

And not this:
![withToolbar](https://user-images.githubusercontent.com/94412718/141869776-d212fe50-30e9-4d14-9982-76ffe284e127.jpg)

**Comment by tmcconechy** [comment]
@kevinwhitedesign what do you think about making this change (or something else). I tend to agree that the dark grey is a bit strange on the toolbar

**Comment by kevinwhitedesign** [comment]
Yeah @tmcconechy I'm not sure why it's not white.

**Comment by kevinwhitedesign** [comment]
Yeah @tmcconechy remember these designs? We fixed this and a few other issues that are open right now in this figma file https://www.figma.com/file/gS5jIE14am8hYEvmtIAXLv/?node-id=10%3A449

**Comment by ericangeles** [comment]
Picking this up as I am also working on a related issue https://github.com/infor-design/enterprise/issues/6047
