### ISSUE TITLE
Field Filter: Field & filter icon issues

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5866]
**Describe the bug**
Filter icons misaligned & text fields not rendered properly

**To Reproduce**
**1st issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/field-filter/example-short.html on Firefox
2. Click on the dropdown
3. See error that the filter icons are misaligned

**2nd issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/field-filter/example-short.html on Safari
2. See error that the field for Datepicker/Timepicker/Lookup are not rendered properly

**Expected behavior**
Filter icons should be properly aligned & fields should be rendered properly

**Version**
v4.58.0-dev

**Screenshots**
**1st issue:** the filter icons are misaligned on Firefox
<img width="359" alt="Screen Shot 2021-10-27 at 11 46 06 AM" src="https://user-images.githubusercontent.com/84306838/139127707-a8ccfd59-133b-4e08-a6aa-c7b492768343.png">

**2nd issue:** the field for Datepicker/Timepicker/Lookup are not rendered properly on Safari
<img width="348" alt="Screen Shot 2021-10-27 at 11 44 32 AM" src="https://user-images.githubusercontent.com/84306838/139127475-52aeec78-7498-4fc2-bae9-f006eca2bfb3.png">

**Platform**
Firefox & Safari browser/mobile

**Additional context**
N/A

**Comment by GlenlieMaye** [comment]
_1st Issue (Firefox)_ **PASSED**
<img width="603" alt="image" src="https://user-images.githubusercontent.com/102151352/165200598-a63dcaca-b292-49f2-b491-398ff65c5a3e.png">

_2nd Issue (Safari)_ **PASSED**
<img width="603" alt="image" src="https://user-images.githubusercontent.com/102151352/165201166-e97dd7d2-6279-47a7-87e9-c5ec40863121.png">

However, the dropdown field looks different with the other field.
![image](https://user-images.githubusercontent.com/102151352/165202915-2d1e1e60-0ade-4197-9045-a53ae122cce0.png)

**Comment by ericangeles** [comment]
@GlenlieMaye what do you mean by different look? I don't see much of a difference.

**Comment by ericangeles** [comment]
@sesbrenosienna can you take a look at this again. Thanks!

**Comment by GlenlieMaye** [comment]
Yes, @tmcconechy. Thanks!

**Comment by GlenlieMaye** [comment]
QA tested and passed. Moving this ticket to Done. Thanks, @sesbrenosienna!

![image](https://user-images.githubusercontent.com/102151352/165712443-425646b7-7182-4531-a20c-842a5890bf99.png)
