### ISSUE TITLE
Tabs: No longer works in modals

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#5867]
**Describe the bug**
Tabs inside a modal no longer works.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs/test-modal-error.html
2. Open dev console and see the error
3. Click "Add Comment" button 
4. See error again when modal opens
5. Select the other tab in the modal

**Result**
Tab can not be selected.

**Expected behavior**
No errors. Tab can be selected. 

**Version**
- ids-enterprise: 4.57.0

**Screenshots**
![image](https://user-images.githubusercontent.com/1101770/141949334-24b238e9-55e3-42c6-bcb7-bd748bb7b35a.png)

**Platform**
 - Infor Application/Team Name: Homepages

**Comment by tmcconechy** [comment]
Hi @ericangeles can you or someone in manilla prioritize the regression? I'll patch it once its PR'd
Thanks 👍🏻

**Comment by janahintal** [comment]
QA Passed. Verified in http://localhost:4000/components/tabs/test-modal-error.html & http://localhost:4000/components/contextualactionpanel/example-cap-tabs-vertical-scroll.html
![image](https://user-images.githubusercontent.com/45757016/144208687-ebe9fdfd-f32b-433d-b7a4-7609d1b47f18.png)
![image](https://user-images.githubusercontent.com/45757016/144208494-f5003246-1277-4d93-831a-206e63209d46.png)
