### ISSUE TITLE
Broken example page 

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#5868]
**Describe the bug**

Following URL is broken
https://design.infor.com/code/ids-enterprise/latest/demo/components/icons/example-extended?theme=uplift&variant=light

- When I'm on the following page https://design.infor.com/code/ids-enterprise/latest/icons
- Then I click on `Extended Icon Set` from the Usage Examples

Page is broken

**Comment by tmcconechy** [comment]
Fixed this here https://github.com/infor-design/enterprise/commit/b3922eccaf4c01ebe01faf2ba724e980d8f16987
But note all these icons are now on sections on https://main-enterprise.demo.design.infor.com/components/icons/example-index.html and no longer on a separate page
