### ISSUE TITLE
Toast: allow different progress bar color

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#5869]
**Is your feature request related to a problem or use case? Please describe.**
Hi, sometimes we want an error message to behave as a toast message with no user interaction.
But we still want that the user will notice it.

Similar to Notification component, but we want it to disappear like toast.

**Describe the solution you'd like**
Add message type parameter similar to Notification with 'error', 'alert', 'info' and 'success'

**Describe alternatives you've considered**
Changing `toast-progress ` background-color

**Additional context**
![image](https://user-images.githubusercontent.com/34129313/141983586-e2fff0b8-7c3f-43a2-9c42-17d02e8590d1.png)

Thanks!

**Comment by tmcconechy** [comment]
I dont mind changing this and adding colors but i think that errors should be messages that are non dismissible https://main-enterprise.demo.design.infor.com/components/message/example-index.html

**Comment by jonathanamiran** [comment]
yes, but we want the error message to "pop" and not to wait for the user to click on a button to dismiss it. thanks

**Comment by tmcconechy** [comment]
Not sure if we will get to this any time soon and if its an error or warning it shouldn't be dismissed. I.E. a user should aknowledge the more important message types. So i think you could use:

https://main-enterprise.demo.design.infor.com/components/notification/example-index.html 
https://main-enterprise.demo.design.infor.com/components/message/example-index.html

**Comment by tmcconechy** [comment]
Ok, So we agree. If an error or alert should use a message https://main-enterprise.demo.design.infor.com/components/message/example-index.html
Any error thats non important should can be timed out https://main-enterprise.demo.design.infor.com/components/notification/example-index.html

If you still need a notification, we would like to understand the use case where it can dismiss on a timeout when its an error.
