### ISSUE TITLE
Icon: Wrong color on #icon-translate

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#5870]
**Describe the bug**

Look in the following image
![image](https://user-images.githubusercontent.com/542598/142008667-a74796bb-b972-4e6a-ba39-2122ede1fa58.png)

I have set inline style to the icons and even added !important to make it explicit
![image](https://user-images.githubusercontent.com/542598/142008768-7f280c8c-3661-48a1-a735-288650a685bb.png)

Even so the #icon-translate doesn't get the color I want. This is an issue since without the above styling the default color should be white, but it isn't for the translate icon now.

This issue happens in version 10.10.0 of enterprise-ng, and was not an issue 10.9.0

Ref
https://main-enterprise.demo.design.infor.com/components/icons/example-index.html

**Version**
- ids-enterprise-ng: 10.10.0

**Additional context**

**Comment by tmcconechy** [comment]
cc @kevinwhitedesign can you check this new icon. It seems to have a hard coded fill/stroke unlike the others so it can not be colorized.

We can fix it with the next round of icons?

**Comment by tmcconechy** [comment]
@kevinwhitedesign any chance of getting this fixed?

**Comment by jbrcna** [comment]
QA Passed
v4.60.0-dev
https://main-enterprise.demo.design.infor.com/components/icons/example-index.html
![image](https://user-images.githubusercontent.com/56722184/151134081-24bd20e1-ccd5-4404-b6d4-476c38af364a.png)

![image](https://user-images.githubusercontent.com/56722184/151134117-c3d4a2da-8806-4d64-8e4c-1b6152678773.png)
