### ISSUE TITLE
Pie: Legend is not aligned in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5871]
**Describe the bug**
Pie: Legend is not aligned in responsive view

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/pie/example-tooltip.html
2. Switch to Mobile / Responsive view
3. Open the legend 

**Expected behavior**
Legend should be aligned.

**Version**
4.58-ids-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/142199762-2a1deb07-7061-4b81-a7cc-0b892b48b5ea.png)

**Platform**
All major browser and devices. (Responsive View)

**Additional context**
N/a

**Comment by tmcconechy** [comment]
closing as slate
