### ISSUE TITLE
Popover: Overlapping text and icon

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5872]
**Describe the bug**
Popover: Overlapping text and icon

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/popover/example-attached-to-textbox.html#
2. Minimize the screen to responsive view
3. Type a long text

**Expected behavior**
Text and icon should not overlap

**Version**
4.58-dev-ids

**Screenshots**
![Uploading image.png…]()

**Platform**
All major browser, OS and devices

**Additional context**
N/a

**Comment by tmcconechy** [comment]
Can you try to upload the image again i cant see it? But i think we should remove/deprecate this example.

**Comment by tmcconechy** [comment]
descoping this for now
