### ISSUE TITLE
Modal: Focus issues with fields with inline style of display:none.

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#5875]
**Describe the bug**
A modal dialog with auto focus is not ignoring input fields are hidden by the inline style display:none. also the mutation observer only recognize the change in focusable elements only when there is something added or removed to the dom, it doesnt update when you change the input elements attributes (tabindex, style etc.) dynamically.

**To Reproduce**

1. replace the example-fullsize-modal.component.html file from here. [example-fullsize-modal.component.zip](https://github.com/infor-design/enterprise/files/7560934/example-fullsize-modal.component.zip)
2. Go to http://localhost:4200/ids-enterprise-ng-demo/modal-dialog
3. Click on full on tablet button
4. it should be focused on the name field upon open of the focus modal.

**Expected behavior**
update/add the following selector when updating the focusable element in DOM.focusableElems() to not include inputs hidden by the inline style display:none, need to also account if there is space between the display:none.
```
'input:not([tabindex="-1"]):not([disabled]):not([style*="display:none;"]):not([style*="display: none;"])'
```

also can we modify the MutationObserver inside the modal.js to include attribute changes like tabindex or inline style?

```
      // When changes happen within the subtree on the Modal, rebuilds the internal hash of
      // tabbable elements used for retaining focus.
      self.changeObserver = new MutationObserver(() => {
        self.setFocusableElems();
      });
      self.changeObserver.observe(self.element[0], 
        { childList: true,
          subtree: true,
          attributes: true // add this argument to trigger the rebuild of internal hash when elements have attribute changes.
```

**Version**

- ids-enterprise: 4.55.3

**Screenshots**
https://user-images.githubusercontent.com/29673378/142371592-95f52681-2900-49cb-8199-3ac6aad74eb4.mp4

**Platform**
 - Infor Application/Team Name: Landmark
 - Device: (if applicable) : NA
 - OS Version: [e.g. Windows 10 or iOS 8]: Windows 10
 - Browser Name: [e.g. chrome, safari, stock browser]: Chrome
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]: Version 95.0.4638.69 (Official Build) (64-bit)

**Additional context**
https://jira.lawson.com/browse/LMCLIENT-38382

**Comment by janahintal** [comment]
QA Passed. Thanks. 
Verified in https://4590-beta0-enterprise.demo.design.infor.com/components/modal/example-hidden-field.html?theme=classic&mode=light&colors=2578a9
