### ISSUE TITLE
Listbuilder: Will not enable on call to enable() after disable() twice

### ISSUE THREAD

**Issue by jp-infor** [infor-design/enterprise#5885]
**Describe the bug**
The Listbuilder control does not become enabled (when calling the enable() method), if the control has had the disable() method called on it twice in succession. When this event occurs, the control can only be re-enabled if the enable() method is also called twice in succession.

**To Reproduce**
Please find attached a demonstration html (listBuilderTest.html in text format
[listBuilderTest.html.txt](https://github.com/infor-design/enterprise/files/7580729/listBuilderTest.html.txt)
hh) page that illustrates the issue.

1. Open [the attached webpage.](https://stackblitz.com/edit/ids-enterprise-4560-zvl9kb?file=index.html). The Listbuilder should show as enabled.
2. Click on "Disable" button twice (confirmation output shown in console) to call disable() method on control. Listbuilder shows as disabled.
3. Click on "Enable" button once only (calling enable() method on control).
4. Listbuilder remains disabled.

**Expected behavior**
Listbuilder should become enabled when the first call to enable() is made.

**Version**
- ids-enterprise: [v 4.57.1]

**Screenshots**
n/a

**Platform**
 - Infor Application/Team Name: [Infor Sunsystems]
 - Device: (if applicable) [n/a]
 - OS Version: [Windows 10 ]
 - Browser Name: [Chrome, Edge]
 - Browser Version: [Chrome Version 96.0.4664.45 (Official Build) (64-bit) , Edge Version 96.0.1054.29 (Official build) (64-bit)]

**Additional context**
n/a

**Comment by tmcconechy** [comment]
Would it be possible to put this in stackblitz? https://stackblitz.com/edit/ids-enterprise-4560 on a fork as i'm getting an error running this about missing JS files...

Not necessary but would help..

**Comment by jp-infor** [comment]
Hi, here is a link to the version I have got working in Stackblitz. Please let me know if you require more.
https://stackblitz.com/edit/ids-enterprise-4560-zvl9kb?file=index.html

**Comment by jbrcna** [comment]
this issue is now resolved.
 v4.60.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/listbuilder/test-disable.html
![image](https://user-images.githubusercontent.com/56722184/149727205-c99d9262-fe57-4b3f-bffc-fc9c186e57ac.png)
