### ISSUE TITLE
Lookup: English string "Selected" is prone to errors in the translated versions. Can it be changed to "Selection"?

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5886]
English string "Selected" is prone to errors in the translated versions. Can it be changed to "Selection"?

Example: 
Incorrect translation for "Selected" in fr-FR and Fr-CA. "Selected" (one word in English) can be translated as Sélectionné, Sélectionnée, Sélectionnés and Sélectionnées

Solution: Change "Selected" to "Selection" in English US

![image](https://user-images.githubusercontent.com/66057969/142873965-148ec99a-fdfd-475d-a050-83f6ec4a1fca.png)

**Comment by tmcconechy** [comment]
Do we have any other options here? In my mind "Selection": does that make sense in english? I think before we had this as "Selected XXX" but that was also too hard to translate so was changed to just "Selected"

**Comment by tmcconechy** [comment]
We can go with selection of we think thats the best. But i think i prefer "selected options"? But doesnt that bring us back to where we were?

**Comment by cpinatel7** [comment]
The string - "Selected Options" - is good. Thanks.
Before it was different as we used to concatenate / glue 2 strings (i.e. one string from IDS and one string from Landmark): https://github.com/infor-design/enterprise/issues/4505

**Comment by tmcconechy** [comment]
Added a new string for this for next translation round Jan

**Comment by tmcconechy** [comment]
Can this be just translated in french as "selection" and we leave the english?

**Comment by cpinatel7** [comment]
This issue is not specific to French. French is just an example. The word "selected" (one word in English) has multiple translations depending on the context
