### ISSUE TITLE
MultiSelect: Use of localized commas is required in comma delimited lists

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5887]
Use of localized commas is required in comma delimited lists e.g.

![image](https://user-images.githubusercontent.com/66057969/142875162-ae92cc5e-c0a2-4373-b3e8-c117d1020d13.png)

Example:
Japanese linguist: "Displayed options are divided by English comma, not a localized one (、)"
Arabic linguist: ".... you will the Arabic separated with English Comma, Arabic Comma should be used!"
Etc.

**Comment by tmcconechy** [comment]
As a workaround the develop could use the delimiter option and set it per local. But i agree this is something we should add at some point.

**Comment by cpinatel7** [comment]
Still required. Thanks
