### ISSUE TITLE
Locale: The Finnish translation of “Seconds” should be capitalized

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5894]
Locale: The Finnish translation of “Seconds” should be capitalized

![image](https://user-images.githubusercontent.com/66057969/143277314-2b1b0e33-838a-4552-aad3-69040cb74a6d.png)

Please assign this issue to: Henry Wondergem

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
Corrected today in: fi-FI-messages.js	50,062	11/30/2021 15:00

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
