### ISSUE TITLE
Locale: The Latvian translation for Select All should be Atlasīt visus > with an additional “s” in the end

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5895]
Locale: The Latvian translation for Select All should be Atlasīt visus > with an additional “s” in the end

![image](https://user-images.githubusercontent.com/66057969/143280824-0bb8c43a-d760-4bb8-916b-1aee4cd64a55.png)

Please assign this issue to: Henry Wondergem

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
Corrected today in: lv-LV-messages.js	50,378	11/30/2021 16:59

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
