### ISSUE TITLE
Datagrid: A new event that will be triggered when filter operator is changed

### ISSUE THREAD

**Issue by sjasaniel** [infor-design/enterprise#5899]
**Is your feature request related to a problem or use case? Please describe.**
If we select an operator in a filter row (except isEmpty and isNotEmpty) and the value is empty, filterConditions ignore the value of the operator  and not added in the filterExpr array. This becomes an issue in LMCLIENT because reapply that condition, the value of filter operator is reset to its default value. Please see gif below.

**Describe the solution you'd like**
An event that we can listen to when filter operator is changed. Something like:
this.element.triggerHandler('filterOperatorChanged', { operator: 'greaterThan', defaultOperator: 'equals', value: 'test', columnId: 'field1'});

**Describe alternatives you've considered**

**Additional context**
![soho](https://user-images.githubusercontent.com/9715303/143557700-69d4316a-0b37-4825-8468-3ae057ef3454.gif)

And what application do you work on? LMCLIENT

**Comment by sjasaniel** [comment]
Tagging @pwpatton 
Hi @tmcconechy , not sure why but there's no option to  assign this to you.

**Comment by tmcconechy** [comment]
Sounds like a reasonable event to fire. To clarify this should fire when a dropdown filter value is selected?

**Comment by sjasaniel** [comment]
Hi @tmcconechy, yes. Thank you!

**Comment by tmcconechy** [comment]
@tjamesallen15 can you pick this one up next

**Comment by jbrcna** [comment]
QA Passed
v4.59.0-dev
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
![image](https://user-images.githubusercontent.com/56722184/147025370-9088fc36-539a-4b06-b502-a3963aad14a1.png)
