### ISSUE TITLE
Dropdown highlights different options upon hitting Delete/Backspace

### ISSUE THREAD

**Issue by rdugenia** [infor-design/enterprise#5900]
**Describe the bug**
Dropdown highlights different options upon hitting Delete/Backspace

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/4.51.1/demo/components/dropdown/example-no-search-lsf.html
2. Click on any option on No Search Dropdown
3. Click again the dropdown
4. Hit Delete or Backspace to clear the dropdown field
5. Repeat steps 3 and 4 multiple times

**Expected behavior**
Hitting Delete or Backspace should highlight the blank option

**Version**
- 4.51.1

**Screenshots**
![dropdownHighlightsDifferentOptionsUponClear](https://user-images.githubusercontent.com/78482539/143568509-8baa5b0c-1ac8-41d3-9444-8e0cbe9b59a8.gif)

**Platform**
 - Browser Name: Chrome, Edge

**Comment by awbuboltz** [comment]
To clarify, when backspace or delete is pressed, the "blank" option should be selected. Tabbing from there should "commit" that blank option.

**Comment by tmcconechy** [comment]
Thanks, thats the impression I got as well backspace/delete should highlight the blank item for selection

**Comment by s-werking** [comment]
Hi @tmcconechy,

I think this one can be closed now. It looks like this issue was fixed by https://github.com/infor-design/enterprise/issues/5113. Thanks!
