### ISSUE TITLE
Line Chart: Unreadable Column Labels

### ISSUE THREAD

**Issue by GMInf** [infor-design/enterprise#5906]
**Describe the bug**
Column labels are unreadable when the labels are long. Also tried xaxis rotate be labels are cut.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-940-ebhm6s?file=src%2Fapp%2Fline%2Fline.demo.html
2. See labels for both normal and rotated column labels

**Expected behavior**
Columns labels should be readable.

**Version**
- ids-enterprise-ng: latest

**Screenshots**
![image](https://user-images.githubusercontent.com/53523076/142980244-d837be98-5ead-4fd3-8c95-e60d6fbba1d9.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome
 - Browser Version  96.0.4664.45 Official

**Comment by tmcconechy** [comment]
Im not 100% sure what we would be able to do here. I dont think the text is as important as the chart so i dont think it should take over the whole page with text in the axis. So my suggestion(s) would be.

1) Apply a shorter label (abbreviate it ect)
2) Apply the two line customization and tweak the `tspan` like https://main-enterprise.demo.design.infor.com/components/line/example-two-lines.html could try and combine this with the rotated option.  but i never have tried this

This chart works better with super long labels https://main-enterprise.demo.design.infor.com/components/bar/example-long-text.html

**Comment by GMInf** [comment]
The column chart has handling for the display labels based on the available size. It would be great if this is also implemented on the line/area chart. See column chart below.
The Column chart data has entries for normal, short and abbreviated labels. It would also be great in rotated labels and a property for choosing the which names/labels to display if it cannot be done automatically. 
![image](https://user-images.githubusercontent.com/53523076/144229764-b97b369e-de2b-4e37-80b3-aa00beadcf58.png)

**Comment by tmcconechy** [comment]
Ok thats a good idea if that can solve it for you.
