### ISSUE TITLE
Datagrid: Add Option to Have Totals in Expandable Section

### ISSUE THREAD

**Issue by clausvaever** [infor-design/enterprise#5909]
In the Datagrid component, I would like to have the option of showing grouping totals in the expandable line itself, instead of in the bottom of each group. 

I am developing a M3 application, IPW, which is based on ui-grid (AngularJS) that I would like to upgrade to the new infor-design.
In the current solution we are displaying a grid with items (lines) with information about that item. Equally important we are displaying some aggregated (totals) information of several items grouped together in groups. When the groups are collapsed, the aggregated information is still visible which gives a nice overview when displaying e.g. 500 items in 10 groups. 

View of the datagrid version (the groups needs to be expanded in order to see the totals):
![Datagrid](https://user-images.githubusercontent.com/29476583/144019111-11c56f3a-f2e4-49f1-b1a4-79c3fa73f449.png)
(I am using groupFooterRowFormatter for the totals)

Expanded view of the ui-grid version (totals and non-totals is visible):
![UIGrid-Expanded](https://user-images.githubusercontent.com/29476583/144019116-4b443753-dd77-4827-b7b0-4db6a54f9190.png)

Collapsed view of the ui-grid version (only the totals are visible):
![UIGrid-Collapsed](https://user-images.githubusercontent.com/29476583/144019115-bbef01f9-1abf-4981-83b9-71bc93883c24.png)

**Comment by tmcconechy** [comment]
Closing stale issues
