### ISSUE TITLE
Sink Page: Editor Image not shown

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5915]
**Describe the bug**
when you insert an image in the editor field. it doesn't show

**To Reproduce**

1. Go to https://4580-beta0-enterprise.demo.design.infor.com or https://4580-beta0-enterprise.demo.design.infor.com/components/editor/example-index.html
2. scroll into `Editor`
3. insert image
4. See error;  placeholder image is not shown
5. switch to html view
6. notice that there's an image tag

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/144413692-4077f950-8b9f-49a4-adc7-d72e88b2648b.png)

**Version**

- ids-enterprise: v4.58.0-beta0

**Screenshots**
![Large GIF (1050x384)](https://user-images.githubusercontent.com/56722184/144414620-81f0fa3b-2826-4200-ba34-bdbf84b2b105.gif)

**Platform**
all major browsers

**Additional context**

**Comment by davidcarlsonberg** [comment]
This issue is not reproducible on latest `master`:
https://master-enterprise.demo.design.infor.com/
https://master-enterprise.demo.design.infor.com/components/editor/example-index.html

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.60.0-dev.
https://main-enterprise.demo.design.infor.com/components/editor/example-index.html
![image](https://user-images.githubusercontent.com/56722184/149859348-4d63c198-10a4-4f20-bdf4-6c1af22ab304.png)
