### ISSUE TITLE
Timezone in Timestamp fields

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#592]
**Is your feature request related to a problem? Please describe.**
There are requirements in Landmark application to display timezone for time stamp fields. 

**Describe the solution you'd like**
The ability to format the timestamp fields to display timezone name short (for eg. CST) or long  (for eg. Central Standard Time) in 4.0 version of Infor controls.

**Describe alternatives you've considered**
None

**Additional context**
None

**Work Needed**

- [x] Handling for timezone in formatDate
- [x] Add all translations from CLDR for https://www.timeanddate.com/time/current-number-time-zones.html
- [x] Example in a label on a form
- [x] Handling for timezone in parseDate
- [x] Tests for translations in short and long form for parseDate
- [x] Tests for translations in short and long form for formatDate
- [x] Function that takes a UTC date and shows it in any timezone
- [x] Formatters examples in datagrid
- [x] Add timezone default formats to all locales
- [ ] Docs
- [x] Browser Test (IE 11 has a fallback)
- [x] ~~Editor examples in datagrid (Skipping as not possible)~~

**Comment by tmcconechy** [comment]
What do you consider "timestamp fields". We do not have that concept or any component with that name.

**Comment by aaralikar** [comment]
Timestamp fields basically have date and time parts.  The requirement is to render timezone when a time stamp field is displayed as text in a form.  
In the culture files, for en-US, we have:
    dateFormat: {
      separator: '/', 
      timeSeparator: ':',
      short: 'M/d/yyyy', // use four digit year
      medium: 'MMM d, yyyy',
      long: 'MMMM d, yyyy',
      full: 'EEEE, MMMM d, y',
      month: 'MMMM d',
      year: 'MMMM yyyy',
      timestamp: 'h:mm:ss a',
      datetime: 'M/d/yyyy h:mm a'
    }

We require additional properties to display timestamp with timezone. The parsers and formatters will make use of this property.

**Comment by tmcconechy** [comment]
For me: This is a good article explaining everything: https://www.timeanddate.com/time/current-number-time-zones.html the translations are in the CLDR so would just need to make formatDate with with fx +UTC timezone option and do a lot of copy pasting so that we have all 38 timezones for each UTC in the locales.

**Comment by Fruko** [comment]
Another requirement coming from Inbox is to adjust date/datetime according to timezone. Currently a system default is used however Mingle offers a timezone in this format 
inforTimeZone=(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna&inforStdTimeZone=Europe/Berlin

We would like Soho date/datetime formatters to be able to accept a TimeZone format to adjust formatted date

**Comment by tmcconechy** [comment]
@Fruko Can you elaborate on that. I.E. You have data coming in as a string `"(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna&inforStdTimeZone=Europe/Berlin"` and you want to convert that to a date object on a form?

I.E. Whats an example of a starting and ending data

**Comment by Fruko** [comment]
@tmcconechy we get a date as an UTC date e.g. "2018-12-03T15:18:39.727Z" that we then show in either datepicker/datetimepicker or as a label. Normally we use Soho Formatters for it that convert it to localised date in proper format. 

However in our usecase we get a query parameter when our applications are loaded (see the timezone strng in my comment above) and we are supposed to adjust the date based on that Time zone parameter

**Comment by Fruko** [comment]
I believe that we need both translated string and date object

**Comment by tmcconechy** [comment]
OK, you lost me again? So you just mean `parseDate` and `formatDate` should work with translated timezones?

**Comment by Fruko** [comment]
oh I see now, I think what we need is a method that would accept a date object and timezone and return a date object adjusted according to that timezone.

then we could re-use the rest of the formatters as it is no matter whether we want date string or date object.

**Comment by brianjuan** [comment]
Passed QA testing on all browsers, moving to Done.
