### ISSUE TITLE
Dropdown: Special charecter "&" issue on drop-down list

### ISSUE THREAD

**Issue by YosraHammami** [infor-design/enterprise#5920]
**Describe the bug**
The issue is that the drop down list do not support a special character like "&" specilally on data grid.

Please see the example in this link on stackblitz : [https://stackblitz.com/edit/ids-quick-start-930-prfjyg?file=src%2Fapp%2Fdatagrid-dirty-indication-data.ts]
1.Click on cell that has a value "F&B" . When the drop-down is displayed there is no blue color highlighting the value  "F&b" in the drop-down list( as it's the value of the cell)==> wrong behavior
If you select the 3rd cell "Action" the drop-down list is displayed and the blue color is on "Action" ==> correct behavior
 
Second scenario :

When you click on a cell "F&B" then  click out side the drop-down, the cell become red it should keep the value "F&B". ==> wrong behavior.

Click on the cell "Action "or "On Hold" the list is displayed . Without selecting anything ,leave the cell it's keeping the same value "Action" ==>the correct behavior
Please see my video for these steps.

**Screenshots**
![Ids Quick Start 930 (forked) - StackBlitz - Google Chrome 2021-12-03 15-04-06](https://user-images.githubusercontent.com/32633586/144630207-92d413c6-0ad8-4b89-99bf-d52e6e269b18.gif)

**Additional context**
Add any other context about the problem here.add screenshots to help explain your problem.

**Platform**
version used: "ids-enterprise-ng": "10.6.1"

**Comment by tmcconechy** [comment]
Closing stale issues
