### ISSUE TITLE
Datagrid: leading spaces not triggering dirty indicator in editable data cell

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#5927]
**Describe the bug**
Leading spaces are not being seen as a change in an editable data grid cell.

**To Reproduce**

1. Go to /components/datagrid/test-cell-with-leading-space-dirty-indicator.html
2. Click on add leading spaces to Compressor in the first cell under the Product Name column
3. Tab out of the cell
4. See that no dirty indicator appears on the cell.

**Expected behavior**
A dirty indicator should be seen when adding leading spaces to an editable data grid cell, just like adding characters does.

**Version**

- ids-enterprise: v4.59.0-dev

**Screenshots**
![LeadingSpaceNoDirty](https://user-images.githubusercontent.com/22107636/144899937-4af3a1e6-f63c-421a-9628-b9037cbc293a.gif)

**Platform**
 - All

**Additional context**
I believe the issue is this .trim() call on this line: https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.js#L10940

**Comment by ericangeles** [comment]
It has something to do also with the issue before https://github.com/infor-design/enterprise/issues/4825

**Comment by tmcconechy** [comment]
Should change dirty code to not compare with trimmed strings maybe?

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-cell-with-leading-space-dirty-indicator.html?theme=classic&mode=light&colors=2578a9
![image](https://user-images.githubusercontent.com/45757016/150779833-fcb28f46-058d-444f-8ba5-c4da403016bc.png)
