### ISSUE TITLE
Button: not possible to set disabled state more than once

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise#5928]
No able to update the disable state of button in flex toolbar in CAP dialog more than once.

1. Go to https://stackblitz.com/edit/ids-enterprise-10110-lbtbab
2. Click on Open Cap button
3. Add text in the form input
4. Delete everything in the form input
5. See Save button now disabled (the form is invalid)
6. Now, add text to the form input (making the form valid)
7. Save button is still disabled, i.e. `myButton.updated({ disabled: !isValid })` did not do anything.

**Expected behavior**
When calling `button.updated({ disabled: true/false })` the updated setting should be reflected in the UI.

**Version**
- ids-enterprise: v4.58.0
- ids-enterprise-ng: v10.11.0

**Screenshots**
<img width="556" alt="image" src="https://user-images.githubusercontent.com/73601152/144911612-2a16a3f1-fa29-423c-a6b4-7db6c5ba9223.png">

How i'm calling the updated():
<img width="510" alt="image" src="https://user-images.githubusercontent.com/73601152/144911403-bf5b82df-b5cc-4f32-a686-3c17b5572784.png">

**Platform**
 - Infor Application/Team Name: Infor M3
 - OS Version: Big Sur
 - Browser Name: Firefox (but shouldn't matter)

**Additional context**
I think it has to do with the code starting on [line 315 in Button.js](https://github.com/infor-design/enterprise/blob/91ab2466123b102eb20c830f33968a51795d9ab3/src/components/button/button.js#L315):
```ts
// Handle a one-time `disabled` setting, if defined.
if (this.settings.disabled) {
  this.disabled = this.settings.disabled === true;
  delete this.settings.disabled;
}
```
If i've called the update with `disabled: true` and then want to remove that disabled, the setting will have to be false, but will never enter the codeblock to actually set `this.disabled = false`, so it will keep being disabled.

**Comment by tmcconechy** [comment]
@whernebrink seems like when i type in the example that it is giving an error now? Any ideas...

**Comment by whernebrink** [comment]
@tmcconechy that's weird. Can's recall I've seen that before. 

This is the error when entering in the input in the component in the CAP:
![image](https://user-images.githubusercontent.com/73601152/148511077-a1266521-deb3-433c-9178-70eacc0c0bc7.png)

And since I havn't added anything to the example stackblitz more than the CAP component and the code for opening the CAP, the only accordionAPI there can be is in regards to the application-menu. So entered something in the application menu searchfield input and got the same error.

Setting `[filterable]="false"` on the `<nav  soho-application-menu>` in app.html will not yield any errors. 

No idea why the accordionAPI is undefined or why that error would appear when entering in then input field in the CAP dialog? Must be some event bubbling?

**Comment by tmcconechy** [comment]
ok thanks - lets see if we can make a local example @tjamesallen15

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/test-close-button-updated.html
![image](https://user-images.githubusercontent.com/45757016/150265497-4e9f113e-a45e-4bf1-b1fd-3ee16ca7a338.png)
