### ISSUE TITLE
Menu search icon not reacting to High Contrast theme

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#593]
**Describe the bug**
Menu search icon not reacting to High Contrast theme

**To Reproduce**
Change theme to High Contrast and observe the application menu search icon is not visible

1. go to http://localhost:4000/components/applicationmenu/example-filterable.html
2. switch to high contrast theme in the ... menu.

Notice the search icon goes away...

**Expected behavior**
Menu search icon should show up in light color in Hight Contrast theme

**Platform**
 - Browser Name: Chrome
 - Browser Version: Version 68.0.3440.84 (Official Build) (64-bit)

**Comment by ericangeles** [comment]
Hi @vonnyw, can you attach a screenshot of the issue? Thank you.

**Comment by vonnyw** [comment]
Here it is:
![high contrast-filter icon](https://user-images.githubusercontent.com/39130590/44100079-c1497c9a-9fa9-11e8-8256-f2c285ceeedb.PNG)
