### ISSUE TITLE
Model: Dialog containing a rich text editor has a row height issue

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5937]
**Describe the bug:**
When rapidly typing into the rich text editor that is in a modal dialog, the line height of the rows is being changed when the user pauses from typing.

**Steps to reproduce the behavior:**
1. Using https://main-enterprise.demo.design.infor.com/components/editor/test-modal.html
2. Click on Show Modal
3. Clear the existing content with the rich text component
4. Rapidly type into the text editor several characters then the enter key (repeat for a couple of lines) then stop

Notice that the height of the rows within the editor are changed when the user pauses from typing.

I've only noticed this behavior happening when the editor is contained in a modal dialog.

**Version**
 ids 4.59.0-dev
 
 **Additional Context:**
 Have a customer reporting this issue.  The user is doing heads-down data entry, rapidly typing into the editor.

**Comment by claudenbach** [comment]
Example from components/editor/test-modal.html:

![RichTextIssue](https://user-images.githubusercontent.com/39804038/145632645-5c74dfe7-131e-4912-9b8b-49549bf494ca.gif)

**Comment by claudenbach** [comment]
Landmark example:
![LMCLIENT-38399](https://user-images.githubusercontent.com/39804038/145632862-9c4ac537-ddf8-4036-b0a2-844ff350730f.gif)

**Comment by tmcconechy** [comment]
Tips to someone that picks this up:

To clarify we added a setting so it will always wrap in P tags so each time you hit enter it makes a new <p> tag which has space between each one. If you dont want a P tag you can do shift+enter.

But it seems in this one case the container isnt yet wrapped possibly the modal is prevent this from happening https://github.com/infor-design/enterprise/blob/main/src/components/editor/editor.js#L650

**Comment by tjamesallen15** [comment]
@tmcconechy  I tried this at http://localhost:4000/components/editor/example-index.html and it seems behaving exactly with the one inside the modal.

**Comment by tmcconechy** [comment]
@tjamesallen15 i did see this issue - sounds like from our teams chat you were eventually able to reproduce?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 i did see this issue - sounds like from our teams chat you were eventually able to reproduce?

yes. still looking at it.

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to Done. thanks
v4.56.0-dev
https://main-enterprise.demo.design.infor.com/components/editor/example-index.html
https://main-enterprise.demo.design.infor.com/components/editor/test-modal.html
