### ISSUE TITLE
Allow abbreviation for month label in calendar view

### ISSUE THREAD

**Issue by edinfor** [infor-design/enterprise#5941]
**Is your feature request related to a problem or use case? Please describe.**
A clear and concise description of what the problem is. [e.g. {Component Name} has a problem when {...}]
When browser width is smaller, some month labels will push date number to second line in date cell, which becomes unreadable when there are events for that specific day.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/82842191/145860049-725dd3cd-354d-4de3-93c9-6269f0e4f03a.png)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/82842191/145860060-fcee06d2-097a-48c3-b3c0-2dd0a5d92844.png)

**Describe the solution you'd like**
A clear and concise description of what you want to happen. [e.g. {Component Name} would work better if {...}]

Provide the option for displaying the month labels in abbreviation for both desktop and mobile view:

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/82842191/145860119-001d320c-d464-4bc7-af9a-34fbe78dc4b2.png)

**Describe alternatives you've considered**

Add an option to configure month label to show abbreviation.

**Additional context**
And what application do you work on? [e.g. {Infor XYZ}]

**Comment by janahintal** [comment]
QA Passed. Working as expected. Thanks!
![image](https://user-images.githubusercontent.com/45757016/146766503-f2edc33b-d057-443c-a8ac-a2d2a1c8b00a.png)

**Comment by CindyMercadoReyes** [comment]
BDD attached.
[BDDStory_github5941.docx](https://github.com/infor-design/enterprise/files/7780804/BDDStory_github5941.docx)
