### ISSUE TITLE
Datagrid: Alternate row tag color issue 

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5945]
**Describe the bug**
when using `New` theme and `High Contrast` , tag color blends with the background color

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-alternate-row-shading.html?theme=new&mode=contrast&colors=003876
2. See error

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/145979645-4c8fc8a1-ed75-4af2-b945-87ff8b830a5a.png)

**Version**

- ids-enterprise: v4.54.0 - v4.59.0-0dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/145979492-47dc8776-47d2-4375-a386-4f817397a0ca.png)

**Platform**
all major browsers

**Additional context**
when you hover over the 6th row it's working as expected. the issue is when you not hover
![image](https://user-images.githubusercontent.com/56722184/145979915-daa0ddef-3d1c-49af-a86c-0dab7e0441c6.png)

**Comment by tmcconechy** [comment]
Would use a darker color for that tag.. As a fix. The next one down or up

**Comment by jbrcna** [comment]
Thank you @tmcconechy

**Comment by tmcconechy** [comment]
Descoping
