### ISSUE TITLE
Datagrid: example-compact-mode  searchfield x icon misaligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5946]
**Describe the bug**
when using New theme, searchfield x icon misaligned in mobile view

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
2. Type in search field
3. See error
4. Notice the x icon is misaligned

**Expected behavior**
x icon should be aligned

**Version**

- ids-enterprise:v4.59.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/145989904-515f07d9-eb54-43ba-ba3a-e0c5c2282b74.png)

**Platform**
android & iOS

**Additional context**

**Comment by ericangeles** [comment]
@tmcconechy tested this issue and it looks like fixed now.

**Comment by jbrcna** [comment]
@tmcconechy , @ericangeles I tested in Browserstack and this is now working in chrome Android and Safari iOS mobile. However, It is failed on Firefox 

Steps to reproduce the behavior:

1. Using Firefox in mobile
2. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
3. Type in search field
4. See error
5. Notice the x icon is misaligned

<img width="151" alt="image" src="https://user-images.githubusercontent.com/56722184/149456899-0b4d6a8f-55b9-4e03-9194-918d45623e20.png">

**Comment by ericangeles** [comment]
What mobile are you using here?

**Comment by jbrcna** [comment]
thank you @ericangeles , I've tried Samsung S21 and S21 Ultra Firefox in Browserstack.

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to done. thanks
https://main-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
![image](https://user-images.githubusercontent.com/56722184/150483235-054d681e-b524-4741-b119-126dd79a94e7.png)
![image](https://user-images.githubusercontent.com/56722184/150483361-088d0388-f2f5-4923-8b53-b89460bed11c.png)
