### ISSUE TITLE
Slider: Textbox function is not working in Windows 10 IE (chromium)

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5948]
**Describe the bug**
Slider: Textbox function is not working in Windows 10 IE (chrome)

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/slider/example-tooltip-onload-and-textbox.html)
2. Change the slider value using the text box 
3. Hit Enter

**Expected behavior**
Slider value should change

**Version**
ids dev - 4.59

**Screenshots**
N/A

**Platform**
Windows 10 IE

**Additional context**
N/A

**Comment by ericangeles** [comment]
@janahintal I believe we do not support IE anymore except for Edge. Tested it in Edge 97 (latest) Windows 10 and it's working as expected.

**Comment by yohannahbautista** [comment]
@janahintal @tmcconechy @ericangeles 
Hello, I checked this on Edge in mac and the textbox seems to be working

**Comment by tmcconechy** [comment]
Im assuming he means edge chromium that we support but i tested this again and it seems ok. I thought i saw it not working before. So lets just get QA to look again.

**Comment by janahintal** [comment]
Retested this again in https://main-enterprise.demo.design.infor.com/components/slider/example-tooltip-onload-and-textbox.html?theme=classic&mode=light&colors=2578a9 for both classic and new theme and seems to be working as expected now. Will now move this to Done. Thank you. :)
