### ISSUE TITLE
Donut: There is an extra line on top of the chart when clicking a legend with zero value

### ISSUE THREAD

**Issue by ktfields** [infor-design/enterprise#5953]
**Describe the bug**
Donut: There is an extra line on top of the chart when clicking a legend with zero value

**To Reproduce**

1. Go to https://jsfiddle.net/ktfields117/v7se6hnk/3/
2. Double click "Pre-tax Deductions" legend
Actual Result: 
"Company Deductions" legend is highlighted with extra line

**Expected behavior**
The chart should only display "Company Deductions" arc without the extra line on top

**Version**

- ids-enterprise: 4.59.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/39935379/146172658-00faa2a0-117c-41b2-a6bf-3e16b3a39fb5.png)

**Platform**
 - Infor Application/Team Name: Lawson System Foundation (LSF)
 - Browser Name: Chrome
 - Browser Version: Version 96.0.4664.110

**Comment by tmcconechy** [comment]
At the time of making this component i made the zeros have 0.01 so you can see there is some value there. But perhaps this is confusing. Maybe we should change this...
