### ISSUE TITLE
SearchField: example-custom-toolbar x icon misaligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5954]
**Describe the bug**
the x icon in searchfield is misaligned

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar.html
2. Click on search icon 
3. Type to search
5. x icon misaligned

**Expected behavior**
x icon should be aligned

**Version**

- ids-enterprise: v4.59.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/146177365-01a01e89-c42e-4648-b955-f10050b9ee51.png)

**Platform**
Android & iOS

**Additional context**
Classic theme not affected

**Comment by tmcconechy** [comment]
This is similar if not the same bug as:
https://github.com/infor-design/enterprise/issues/5947
and
https://github.com/infor-design/enterprise/issues/5946

So i would fix all three of these at once when picking this up 👍🏻

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.60-dev.
https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar.html
![image](https://user-images.githubusercontent.com/56722184/149726123-86fc05f1-639e-454c-943c-55bbe750fe15.png)
