### ISSUE TITLE
Datagrid: example-disabled-rows calendar icon issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5955]
**Describe the bug**
when using medium height the calendar icon is not aligned when you edit that date in order date column.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-disabled-rows.html
2. Change row height to medium
3. Click to edit the order date column
5. Notice that the calendar icon kind of moves away

**Expected behavior**
calendar icon should be properly aligned

**Version**

- ids-enterprise: v4.54.0 - v4.59.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/146179495-cc74d4dd-eef9-4e9a-9e40-1fc4628adc84.png)

_mobile_
![image](https://user-images.githubusercontent.com/56722184/146181491-28111f57-93be-4dc4-ba5f-021fc31a8867.png)

**Platform**
all

**Additional context**
Classic theme not affected
![image](https://user-images.githubusercontent.com/56722184/146179879-888a095e-2b5e-4a58-850c-20b3e574c80b.png)

**Comment by tmcconechy** [comment]
Also it doesn't look perfect in any of the row heights. In the others it moves around going in edit mode. So please check all 4 themes.

**Comment by jbrcna** [comment]
QA failed. v4.60.0-dev
All row heights were affected with both new and classic theme
https://main-enterprise.demo.design.infor.com/components/datagrid/example-disabled-rows.html
![image](https://user-images.githubusercontent.com/56722184/150273069-85c861fc-dd9a-4efc-8524-8f7a92f1e20b.png)

**Comment by ericangeles** [comment]
@tjamesallen15 can you take a look at this?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 can you take a look at this?

Will take a look

**Comment by jbrcna** [comment]
working as expected. moving this ticket to Done. thanks
