### ISSUE TITLE
Modal: Dialog containing a datagrid with a codeblock column generates JSE 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5957]
**Describe the bug**
A modal dialog using the options of noRefocus: false generates a JSE when the dialog contains a datagrid with a code block column.

**To Reproduce**
1. Create a modal dialog with the option of noRefocus = false
2. Dialog contains a datagrid
3. Datagrid contains a codeblock colum
4. Select a row 
5. Notice the JSE in the console

**Expected behavior**
When selecting an item from a datagrid with a code block a JSE is not generated.

**Suggested Fix**
In the method isFocused() within lookup.js, change the following line:
const wrapperHasActive = this.element.parent('.lookup-wrapper')[0].contains(active);

Change to:
const wrapperHasActive = this.element.parent('.lookup-wrapper')[0]?.contains(active);

**Version**
- ids-enterprise: 4.58

**Screenshots**
![image](https://user-images.githubusercontent.com/39804038/146401204-0256a416-02b8-4bf2-ac5a-ba1973f13760.png)

**Comment by claudenbach** [comment]
Shows the issue before using the suggested fix:

![ReFocus-Issue-Before](https://user-images.githubusercontent.com/39804038/146403143-e9900eac-39a5-45dd-99b3-ee0754e6ea9f.gif)

**Comment by claudenbach** [comment]
Shows the issue after using the suggested fix:

![ReFocus-Issue-After](https://user-images.githubusercontent.com/39804038/146403275-16695981-f8b2-4076-907e-eda1da731b44.gif)

**Comment by claudenbach** [comment]
Asking nicely if this could be included into IDS 4.59.  Thanks.

**Comment by tmcconechy** [comment]
I added the change. Thanks @claudenbach !
But i did not do a pull request since we dont have the codeblock column on our end. But since the fix is super simple i just pushed it in https://github.com/infor-design/enterprise/commit/bdd56e5457b8637873dff27f83157fd79183a0d3
