### ISSUE TITLE
Masthead: Changing of color/s from more actions not working

### ISSUE THREAD

**Issue by nganotice** [infor-design/enterprise#5959]
**Describe the bug**
Changing of color/s from more actions not working

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/masthead/example-banner-detail.html
2. Click on more actions
3. Click on Colors and pick a color
4. See error that the changing of color/s isn't working

**Expected behavior**
After picking a color it should change to that specific color

**Version**
v4.59.0-dev

**Screenshots**
![Video 23](https://user-images.githubusercontent.com/84306838/146491155-1e484e38-b0cc-4b15-9162-8b6375cad595.gif)

**Platform**
-All browsers & mobile devices

**Additional context**
N/A

**Comment by tmcconechy** [comment]
We did not wire up the color change in that example. Its not really too important. We can either make this work or remove the items from the menu to not imply its work...

**Comment by janahintal** [comment]
Issue still exists in https://main-enterprise.demo.design.infor.com/components/masthead/example-banner-detail.html?colors=8D0B0E

Expected: Notice action button no longer exists on far right of header
![image](https://user-images.githubusercontent.com/45757016/158113322-292d773e-1e8a-474f-b2d5-3da119b4cbe4.png)

**Comment by tmcconechy** [comment]
cc @davidcarlsonberg

**Comment by davidcarlsonberg** [comment]
When I visit that page in MacOS Chrome I do not see the actions menu...? So, maybe QA is visiting a cached version? Strange...

**Comment by tmcconechy** [comment]
ok lets get them to test again...

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
