### ISSUE TITLE
Color picker field without clearable option is missing a color

### ISSUE THREAD

**Issue by jake-harrington** [infor-design/enterprise#596]
**Describe the bug**
Two issues:
1. A color picker without the clearable option just has an empty space where the clearable option usually is and Azure01 used to be.
2. Azure03 is strangely green.

**To Reproduce**
1. Go to http://localhost:4000/components/colorpicker/test-clearable.html
2. Open the second input, the "Clearable (false)" input
3. Observe that there are only 69 colors because one is missing where Azure01 would have been. Also Azure03 is greenish.

**Expected behavior**
There should be 70 colors and the blues should be blue.

**Screenshots**
![image](https://user-images.githubusercontent.com/39064853/44036121-ae7e0726-9ed6-11e8-89ab-49b952d8f3d3.png)

**Comment by tmcconechy** [comment]
The color is mistyped 8DC9A6 should be-> 8DC9E6

**Comment by clepore** [comment]
Is the mistyped hex in EP or the design tokens?

**Comment by ericangeles** [comment]
Can anyone discuss the behavior of the clearable (true & false)?
