### ISSUE TITLE
Locale: Incorrect Lithuanian translations

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5960]
Lithuanian contractor:
1.“Equals” is translated as “Lygus”, which is more applicable to numbers. In this context, it should be “Atitinka”. (This is a global issue)
2. Another problem is when, for example, I enter a search string that shows 12 results, the heading says “12 rezultatai”, which is incorrect (in Lithuanian, it should be 12 rezultatų (wrong inflection (the same would happen with other numbers like 0). The best solution is to abbreviate the word “rezultatai” to “rezult.” To avoid the inflection. (This is a global issue)
3. The “Move to left” tooltip is translated as “Pereiti į kairę”, which is incorrect. It should be “Perkelti į kairę”

I think 1. needs to be assessed as it's probably used in different contexts

![LT](https://user-images.githubusercontent.com/66057969/146592518-7b4fb03d-f4b6-4bc6-8b77-16365c7e066c.png)

Please assign this ticket to Henry.Wondergem@infor.com

**Comment by tmcconechy** [comment]
cc @hwondergem - BTW when is the next translation drop? (or when was the last one?)

**Comment by hwondergem** [comment]
All fixed in \\nlbavwmemoq2\cc\ToDev\SohoUX\lt-LT-messages.js	51,525	02/08/2022 16:50

**Comment by tmcconechy** [comment]
Yes it would have been included in the March Release (but i would take [4.64.2](https://github.com/infor-design/enterprise/releases/tag/4.64.2) which is the very latest)
