### ISSUE TITLE
Notification: displaying multiple messages using SohoNotificationService

### ISSUE THREAD

**Issue by adityathumma119898** [infor-design/enterprise#5964]
**Describe the bug**
we see multiple notification bars opening up using SohoNotificationService for  getting that notification in our Homepages Widget development using Widget SDK.
Development Ticket for reference: https://jira.infor.com/browse/T2V-1281

**To Reproduce**
The steps to reproduce is available in the JIRA https://jira.infor.com/browse/M3HOME-393

1. Search buyer
2. Search item
3. Select order line
4. On date selector, select current date
5. Leave Order quantity blank/null
6. Click Create multiple times

**Expected behavior**
Able to close the notification automatically/programmatically  when there is a new notification message.

**Version**
https://github.com/infor-design/enterprise/blob/main/src/components/notification/notification.js#L153

**Screenshots**
![image-2021-12-20-13-31-20-393](https://user-images.githubusercontent.com/96410340/146727170-d32c5064-f746-4f93-80d8-c7da1e566a3f.png)

**Platform**
 - Infor Application/Team Name: Homepages Widget
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 96.0.4664.93 (Official Build) (64-bit)

**Additional context**
We were unable to achieve this programmatically by using the "SohoNotificationService" in angular, also posted the issue in the IDS Enterprise Development Teams channel, Since we could not get the solution. we are logging this ticket.

**Comment by tmcconechy** [comment]
We usually require a reduced test case for this sort of bug. We cant fix bugs in your application code as the steps might indicate.

Are you just asking how to close/hide a notification?

**Comment by tmcconechy** [comment]
The example shows how to hide the last and hide all ect https://github.com/infor-design/enterprise-ng/tree/main/src/app/notification

But i might change this to close FYI

**Comment by tmcconechy** [comment]
Closing this issue as i think from what i can tell it will be solved in 4.59 meaning we adjusted the method names and the types are there in NG. https://github.com/infor-design/enterprise-ng/pull/1203/files#diff-b45bee13f10573531fa82f4d2050d0b08987d6420cf84a2cc06328cbbfbe9f26L48

So if you get that release when its done and follow that example you should be able to close them
