### ISSUE TITLE
Locale: Please refine Latvian translation for "Records per page”

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#5969]
GRC contractor:
“Records per page” would be better: “[number] ieraksti vienā lapā” (for consistency, otherwise two different words are used > “lapa” and “lappuse”. This is a general issue.

LV screenshot
![LV](https://user-images.githubusercontent.com/66057969/147015228-de1cfd7c-5595-485c-9389-fda6eaebc7f7.png)

Please assign this issue to Henry.Wondergem@infor.com

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by janahintal** [comment]
Hi @tmcconechy @cpinatel7, please see test result below.
“Records per page” should be “[number] ieraksti vienā lapā”
![image](https://user-images.githubusercontent.com/45757016/147626801-e098c06b-7d1d-487a-a182-5d884bf00f77.png)

Result:
[number] ieraksti vienā lappusē

**Comment by tmcconechy** [comment]
@cpinatel7 is what was provided by the translation team correct? as there is two variants:

```
RecordsPerPage: { id: 'RecordsPerPage', value: '{0} ieraksti vienā lappusē', comment: 'Shows an actual number of pages in the pager' },
    RecordsPerPageNoToken: { id: 'RecordsPerPageNoToken', value: 'Ieraksti vienā lapā', comment: 'Shows as a title list of values for page number (without the slot/token value)' },
```

**Comment by cpinatel7** [comment]
I think this issue needs to be reassigned to Henry and his team. They need to review RecordsPerPage & RecordsPerPageNoToken and decide what should be done. Thanks

**Comment by hwondergem** [comment]
Yes, will be reviewed and corrected during January translation update.

**Comment by tmcconechy** [comment]
Pushing this to next as wasnt fixed yet

**Comment by hwondergem** [comment]
All fixed in \\nlbavwmemoq2\cc\ToDev\SohoUX\lv-LV-messages.js	51,349	02/08/2022 16:50

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/datagrid/example-paging?locale=lv-LV
![image](https://user-images.githubusercontent.com/45757016/153846081-f9c620f1-7d6c-4c40-af83-65280e53a297.png)
