### ISSUE TITLE
Must now click twice to close menus

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#597]
**Describe the bug**
After some changes this sprint it takes two clicks to close a menu now.

**To Reproduce**
1. Go to http://localhost:4000/components/contextmenu/example-index.html
2. Right click
3. Click out to close the menu

**Expected behavior**
Should close on click out, now requires one more click.

Pushing a fix to follow

**Comment by brianjuan** [comment]
Moving to Failed QA. In Mac Safari, contextmenu is automatically closing when you open it for the second time.
1. Right-click to open contextmenu
2. Click outside to close the contextmenu
3. Right-click again, notice that the contextmenu will automatically close.

**Comment by tmcconechy** [comment]
@brianjuan I'm not seeing this it seems to be working ok? Do you see it @EdwardCoyle @deep7102 @CindyMercadoReyes ?

**Comment by EdwardCoyle** [comment]
@brianjuan agreed with Tim, I'm not seeing that result on the latest `master`:

![aug-20-2018-10_07-am](https://user-images.githubusercontent.com/3249601/44345407-47e87600-a461-11e8-9787-1c5278486da7.gif)

**Comment by brianjuan** [comment]
I found out why, the issue happens when you're on iMac and do the right-click by pressing control + click (I believe this is the default). But if you set Secondary click on System Preferences > Mouse, then do the normal right clicking, the issue will not be encountered.

**Comment by tmcconechy** [comment]
@brianjuan 
Ok, great tracking it down. Then i think this is a new and separate problem. Lets make a new issue for it not working with control +click

**Comment by brianjuan** [comment]
I agree, thanks @tmcconechy . I will now move this to Done and will create a separate issue for the control + click
