### ISSUE TITLE
Datagrid: TargetedAchievement formatter displays incorrect color when using a locale

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5972]
**Describe the bug**
When using a locale of 'fr-FR', the TargetedAchievement formatter always displays the primary color of blue, even when col.ranges are provided.  Works correctly when the locale is 'en-EN'.

**To Reproduce**

1. Using the attached 'test-targeted-achievement-with-locale-html
2. Notice in the With Alert Colors column that all cells are rendered with the primary color of ble
3. Using https://main-enterprise.demo.design.infor.com/components/datagrid/test-targeted-achievement.html
4. Notice the correct colors are rendered in the cells of the With Alert Colors column 

**Expected behavior**
Regardless of locale, the correct colors are displayed.

**Version**
- ids-enterprise: v4.58.0-dev

**Screenshots**
With a locale of 'fr-FR':

![image](https://user-images.githubusercontent.com/39804038/147266355-d5f4092c-5c5f-468d-84a6-0b0a94597d8b.png)

With the default locale of 'en-EN':

![image](https://user-images.githubusercontent.com/39804038/147266430-5580b0ae-b329-4668-9190-3d727891121b.png)

**Comment by claudenbach** [comment]
[TargetedAchievement.zip](https://github.com/infor-design/enterprise/files/7770385/TargetedAchievement.zip)

**Comment by claudenbach** [comment]
This issue isn't specific to just a locale of 'fr-FR'.  Other locales also do not work. for example 'de-DE'.

**Comment by tmcconechy** [comment]
Can also simply reproduce by going to https://main-enterprise.demo.design.infor.com/components/datagrid/test-targeted-achievement.html?locale=de-DE 

A bit wierd 👍🏻

**Comment by claudenbach** [comment]
Thanks for the much simpler way to test.  Wasn't aware of the parameter string setting.

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.60.0-dev.
https://main-enterprise.demo.design.infor.com/components/datagrid/test-targeted-achievement.html?locale=de-DE
![image](https://user-images.githubusercontent.com/56722184/152086374-ed3a9bbd-d4aa-47c3-8832-994888fc567a.png)
