### ISSUE TITLE
Datagrid: example-export-format RTL issue on Safari

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5978]
**Describe the bug**
when using RTL in Safari the parenthesis is different.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-export-format.html
2. Select `he-IL` from the dropdown. or any RTL 
3. Wait to Load

**Expected behavior**
parenthesis should look normal

**Version**

- ids-enterprise: v4.59.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/147538892-07df61e9-6ce4-47a7-ae6d-953976a3332e.png)

**Platform**
Safari

**Additional context**
i think it's the same as https://github.com/infor-design/enterprise/issues/5827#issuecomment-989486867

**Comment by tmcconechy** [comment]
@jbrcna we cant do anything about this. Its a by product of using English text where Right to Left (arabic or hebrew characters would ultimately be used). The browser just treats it different in chrome / and safari. So there isnt any way to change this behavior and it would be fine if they use the right real language characters.

**Comment by jbrcna** [comment]
thanks for clarifying @tmcconechy
