### ISSUE TITLE
Soho.excel.exportToCsv XSS vunlerability

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise#5982]
**Describe the bug**
Soho utility function `Soho.excel.exportToCsv` is vulnerable to XSS

**To Reproduce**
Have a datagrid with a row that includes malicious javascript and see it gets executed upon exporting datagrid content to csv

1. create datagrid that has e.g. this in a cell `<img src=x onerror=prompt()>`
2. use utility function `Soho.excel.exportToCsv`
3. See code being executed

**Expected behavior**
export to csv will never execute any script within the csv text

**Version**
Soho.version
'4.57.0'

**Comment by tmcconechy** [comment]
We should run the xss utils over the css export data.

**Comment by janahintal** [comment]
QA Passed. 
![image](https://user-images.githubusercontent.com/45757016/149768019-35776140-8bd1-4ef5-8eda-36e40457bade.png)
