### ISSUE TITLE
Field Options: misaligned x icon in searchfield

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#5983]
**Describe the bug**
when using compact mode in` classic theme` the x icon in `clearable searchfield` is not aligned

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-options/example-index.html?theme=classic&mode=light&colors=2578a9
2. Enter text in `clearable search field`
3. Click `Compact Mode` button

**Expected behavior**
x icon should be properly aligned

**Version**
v4.59.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/147810793-8892c8fd-6658-42e3-883a-2566ae909d44.png)

**Platform**
All major browsers.

**Additional context**

**Comment by tmcconechy** [comment]
Are all the steps right here? As i don't see a compact mode button on this page? Also the example screen shot doesn't show compact mode. So something isn't quite right.

**Comment by jbrcna** [comment]
Hi @tmcconechy , I entered a wrong link. should be example-index of field-options.  the link above is now updated.

**Comment by jbrcna** [comment]
this issue is now resolved.
 v4.60.0-dev
https://main-enterprise.demo.design.infor.com/components/field-options/example-index?theme=classic&mode=light&colors=2578a9
![image](https://user-images.githubusercontent.com/56722184/149726499-a30e1de1-3ebd-4dd4-a640-b779cc669772.png)

Firefox
https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar.html
![image](https://user-images.githubusercontent.com/56722184/149726338-afc2d7cd-a898-48c7-b714-85816de68528.png)
