### ISSUE TITLE
Date Picker - Ability to update legend when visible month changes

### ISSUE THREAD

**Issue by LilBiggs** [infor-design/enterprise#5988]
**Is your feature request related to a problem or use case? Please describe.**
The IDS Date Picker will show a green circle for each day of which you have a shift. Which day you have a shift is fetched via an API. Because of performance reasons of phones / network usage, we wouldn't want to fetch the Shift information until actually needed. 
Currently with the Date Picker, there is no way of knowing when the visible month changes. (Either via the Previous/Next buttons or via the month/year selector.). There is also an issue of when the Legend is updated and the Date Picker is open, the Date Picker is closed because the entire control is destroyed and rebuilt on an update. (Angular)

**Describe the solution you'd like**
* Date Picker would work better if there was a beforemonthrender + aftermonthrender event. This event would be used to fetch Shift information to populate the Legend.dates array.
* Ability to update the legend dynamically as well when the Shifts are fetched from the API.
* Know when the Date Picker is Visible / Not Visible. (This may only be a Angular issue as the listopened / listclosed events are not listened for)

**Describe alternatives you've considered**
Load Shifts when first coming to the page. This works to populate the first month. However when changing months the Shifts can't be loaded.

**Additional context**
![image](https://user-images.githubusercontent.com/6730716/148089296-389d1018-5fb7-49cc-94d9-ca4bef035da1.png)
Infor WFM

**Comment by tmcconechy** [comment]
i'd suggest two changes
- adding a beforemonthrendered a aftermonthrendered in addition to the current monthrendered (with ng typings)
- adding a legendLoaded call back in the settings that lets you return a new set of data for the legend setting that will apply dynamically as the calendar is reloaded/changed page

**Comment by jbrcna** [comment]
v4.60.0-dev
https://main-enterprise.demo.design.infor.com/components/monthview/test-legend-loaded.html
<img width="764" alt="image" src="https://user-images.githubusercontent.com/56722184/152912257-f994156c-06a2-4d8d-a29b-3d597cc83e1e.png">

then change to feb.
<img width="666" alt="image" src="https://user-images.githubusercontent.com/56722184/152912311-29a25b45-b144-4ea9-8b31-48eb6de74a27.png">
