### ISSUE TITLE
Sink Page: Context Menu not working in Windows Chrome

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#5992]
**Describe the bug**
Sink Page: Context Menu not working in Windows Chrome

**To Reproduce**

1. Go to https://4590-beta0-enterprise.demo.design.infor.com/?theme=new&mode=light&colors=0066D4
2. Go to Context Menu section
3. Right Click each fields

**Expected behavior**
Context menu should open

**Version**
4.59 ids - beta

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/148215541-c456c3af-8308-4710-99b5-90431a5a0ff7.png)

**Platform**
Windows Chrome 

**Additional context**
N/a

**Comment by tmcconechy** [comment]
I tried this on Browser Stack using Chrome 96 and both windows 10 and 11 and could not reproduce?
Any other info that would help? I can see somehow you have the field focused... Maybe you clicked outside the field on the label?

**Comment by janahintal** [comment]
Hi @tmcconechy, I'm using Windows 10 Chrome 95 but when I tried it in Browser Stack and it worked even on lower OS and Chrome version. Maybe it's my device that's having problem. Will close this issue then since its working in BS. Also tried it in my personal laptop and it worked. I will now close this issue. Thanks! :)
