### ISSUE TITLE
Process indicator separator has a double line.

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#5997]
**Describe the bug**
The border CSS for separators in process indicator appears to be creating a double line.

**To Reproduce**

1. Go to http://localhost:4000/components/processindicator/example-index.html
2. Observe separator. Notice white in middle. (see screenshot)

**Expected behavior**
Should be a solid line

**Version**

- 4.57.1

**Screenshots**
<img width="655" alt="double-line" src="https://user-images.githubusercontent.com/1056684/148430776-a5f136d5-5497-4982-9415-8ebab3bcd8a4.PNG">

**Platform**
 - Windows 10
 - Chrome
 - Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by krishollenbeck** [comment]
I can temporarily override this in our SCSS by doing the following..

```
.process-indicator {
    .lines {
      .separator {
        border-color: transparent !important;
        border-bottom-color: #B7B7BA !important;
        &.darker {
          border-color: transparent !important;
          border-bottom-color: #0066D4 !important;
        }
      }
    }
}
```

**Comment by jbrcna** [comment]
this is working as expected. moving this ticket to done. thanks
https://main-enterprise.demo.design.infor.com/components/processindicator/example-index.html
`BS Win10 Chrome 98 latest`
<img width="1576" alt="image" src="https://user-images.githubusercontent.com/56722184/156710016-01f481c2-54f9-4ce2-8767-c85ff70bd0f4.png">
`BS Win10 Chrome 96`
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/56722184/156710284-7b0fd332-9dd3-402b-a426-88de26e0546f.png">
