### ISSUE TITLE
Datagrid: Column that is filterable with maskOptions is ignoring an align 'left'  

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#5999]
**Describe the bug**
A column that is filterable and uses the maskOptions property, then the property to align 'left' is ignored.  The input cursor is displayed on the right-hand side of the filter cell.  Noticed that if the column uses the mask property versus the maskOptions property, the input cursor is displayed in the left-hand side of the cell as intended.

Side note: should padding be added since the input cursor and the lookup trigger icon have no spacing between? 

**To Reproduce**
1. Using the attached 'test-filter-align.html'
2. Click on the filter cell for the Product Id column
3. Notice that the input cursor is in the right-hand side of the filter cell
4. Also see that the input cursor is too close to the lookup trigger icon

**Expected behavior**
Filter cell honors an align of 'left'.

**Version**
- ids-enterprise: v4.60.0-dev

**Comment by claudenbach** [comment]
[Test-Filter_Align.zip](https://github.com/infor-design/enterprise/files/7825021/Test-Filter_Align.zip)

**Comment by claudenbach** [comment]
![image](https://user-images.githubusercontent.com/39804038/148459472-a68bc4a3-dc2a-4619-9de7-aa85c4e27e04.png)

**Comment by jbrcna** [comment]
this issue is now resolved.
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-filter-align.html
<img width="900" alt="image" src="https://user-images.githubusercontent.com/56722184/155918957-a2a95ca1-29ca-4cbd-93b9-3670ad3c1878.png">
