### ISSUE TITLE
List Lookup is not returning data in Safari browser

### ISSUE THREAD

**Issue by jdrinka1** [infor-design/enterprise#6003]
**Describe the bug**
In a datagrid list when performing a lookup it does not always return a value. It appears that the cell the lookup icon is in no longer appears to editable. 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-list-lookup.html (in safari mac)
2. Click on Product Id field.
3. Click the Lookup icon.
4. Select a record.
5. The Select dialog goes away, but the value is never returned to Product Id field. 

**Expected behavior**
The value selected should return to the datagrid cell it was selected from

**Version**

- ids-enterprise: v4.58.1

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor Landmark 
 - OS Version: Mac OS Big Sur 11.6
 - Browser Name: Safari
 - Browser Version: 14.1.2

**Additional context**

https://user-images.githubusercontent.com/86791155/148575772-4a0440d4-f220-4860-ba37-6624f8908672.mov

**Comment by tmcconechy** [comment]
The problem seems to be around this area.. https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.js#L7142-L7154 either the timeout is not enough for safair or an additional test is needed here to make it properly work
