### ISSUE TITLE
Multiselect: missing event when closing tags

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#6004]
**Describe the Issue**
Hi, I couldn't find an event that is triggered when Tag inside multiselect is closed/dismissed

**To Reproduce**
Steps to see the question or problem:

1. Go To [https://design.infor.com/code/ids-enterprise/latest/demo/components/multiselect/example-tags.html](https://design.infor.com/code/ids-enterprise/latest/demo/components/multiselect/example-tags.html)
2. Select an item
3. Close it (clicking on the X)

**What are you trying to do**
I'm currently using `.on('selected',` and `.on('updated'` to find out when a user selected items in order to update a query.
But when the user clears one of the tags by clicking on the 'x' on the tag, my query is not updated.

**What did you try so far**
Tries `click.tag` and `aftertagremove `event, but with no success

**Version**

- ids-enterprise: v4.59.0

**Screenshots**

**Platform**
 - Device: Windows
 - OS Version: 10
 - Browser Name Chrome
 - Browser Version 97

**Additional  Context**
Thanks

**Comment by tmcconechy** [comment]
It was intended that the change event would work. On this example: https://design.infor.com/code/ids-enterprise/latest/demo/components/multiselect/example-tags.html

If you add this to the console:

```
$('#multi-tagged').on('change', function () {
  console.log($(this).val());
});
```

It works but only if you deselect them from the open list with the checkmarks. It seems like clicking tags is not triggering it so this is actually a bug.

**Comment by jbrcna** [comment]
this issue is now resolved.
verified in https://main-enterprise.demo.design.infor.com/components/multiselect/example-tags.html
<img width="951" alt="image" src="https://user-images.githubusercontent.com/56722184/156335777-70d486fb-eb99-4e2f-b5c5-6a74f9b6a73a.png">
