### ISSUE TITLE
SearchField: Request for enhanced Widget Search component with "Filter" and "Sort' control

### ISSUE THREAD

**Issue by jvedua** [infor-design/enterprise#6007]
One of the important elements of a widget is the _**effective placement of components to maximize the limited amount of space**_. But some current widget components are not effectively utilizing the limited space by displaying separately when they can be combined.

Currently the **"Search"** and the **"Filter/Sort"** components are displayed in separate panels even if both can be considered as _"Navigation Controls"_ that can be combined not only for aesthetic reasons but also to maximize the limited space of the widget. 

<img width="277" alt="image" src="https://user-images.githubusercontent.com/49638020/148765243-00069a3e-fc0f-49aa-8fe0-f37d258a99b0.png">

<img width="767" alt="image" src="https://user-images.githubusercontent.com/49638020/148765272-96fc8ddb-ee61-4132-bc15-fec2453807dc.png">

As the requirement to place more information in the widget level arise the need to maximize the available space in the 1x1 widget size becomes relevant. the **product developers thus resorted to "custom styling"** to achieve the combination of the Search and Filter/Sort components which is placed below the widget header.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/49638020/148765389-45f81b5b-f41e-42a4-a2f4-1801f11e2ac4.png">

This is effective as of the moment as application developers on different products can do custom styles but since the Search and Filter/Sort components are "common" and not a _"unique"_ component thus we must standardize them in the IDS to minimize custom styling across all products that will use the Homepage Widgets. This will shorten turnover time and we can also restrict custom styling efforts on components that is **_"unique"_ only to a particular product.**

**Comment by tmcconechy** [comment]
Hey @jvedua is this from t2v. FYI we will look at what we can do to fix this stuff. Maybe there is a bit too much functionality on this small space.

cc @inforandy

**Comment by jvedua** [comment]
Thank you @tmcconechy!

**Comment by kevinwhitedesign** [comment]
Hey @tmcconechy @jvedua 

After reviewing this, it seems that the height size of the search header is too small. It should be at least 44px to be appropriate for mobile hitbox/touch areas. That goes for the space between icons as well. Looks a bit tight especially up in the widget toolbar. Can filter and sort be in the widget's header? That might make sense as well? But I do agree, 3 headers is 1 too many, and I think we should try to move to 1 header in the future. 

cc @danirosefishinfor

**Comment by tmcconechy** [comment]
FYI i dont think we actually have this yet but if we do this is 44px https://main-enterprise.demo.design.infor.com/components/cards/example-group-action.html so we would just stick a search in there.

Then we have a question about the buttons hanging over it...(placement/size ect)

**Comment by jvedua** [comment]
@kevinwhitedesign, Yes I agree if we can increase the vertical height of the search panel to 44px which @tmcconechy  said above we already have. Also I think we should keep the Filter and Sort in the Search Panel as it controls the "Widget Content" whereas the widget header elements controls the "widget itself".

As for the tight space, we can have the Filter and Sort control disappear when the search control is in "focus" and let the user do a search query and display the Filter and Sort control again after the search results are displayed.

**Comment by kevinwhitedesign** [comment]
@jvedua it is a bit confusing that there are multiple versions of design comps up there with varying specifications. Do you also have a figma link to inspect.

**Comment by kevinwhitedesign** [comment]
@jvedua but then does that remove the ability to further filter, sort when a user has searched a criteria?

**Comment by tmcconechy** [comment]
Could just put the x next to the filter icon and not hide them. I think it makes it a little safer for usability and accessibility and they could click the filter if they wanted to while typing...

**Comment by kevinwhitedesign** [comment]
@jvedua can sort / filter be combined into the same UI? Such as this example in ebay? https://capture.dropbox.com/NpiVYb84w9c40L9t?src=ss

**Comment by jvedua** [comment]
Hi @tmcconechy , @kevinwhitedesign  just an update, I discussed with my team recently our exchanges on this matter and we unanimously agreed to still have the filter and sort control on the search panel to simplify the widget and keep the current pattern consistent:

<img width="861" alt="image" src="https://user-images.githubusercontent.com/49638020/153988267-55d5bf00-5f7f-46a0-8b31-d3160a5185f5.png">

We also decided to have the filter and sort display immediately regardless if the there is initial list content or not to reduce complexity.. or maybe have them disabled if they are not needed? 

As for the recommendation to have an EDIT MODE for the widget so the user will have access to widget configuration rather than putting them in the spillover outright we also did a unanimous decision to KEEP the current approach.. so this will still have ONE content-related trigger in the widget header which is the "add" ("+") trigger only and the rest will be widget-related (inside the spillover).

Joseph

**Comment by tmcconechy** [comment]
I agree with this but the field would be 44px height and the buttons would be the standard icon size (18) with a 44px hit point to follow our guidelines.

What do you think @kevinwhitedesign ?

**Comment by jvedua** [comment]
Yes @tmcconechy let's use the standard sizes

**Comment by kevinwhitedesign** [comment]
@tmcconechy yeah, it should end up looking a bit larger than Joseph's latest images

**Comment by tmcconechy** [comment]
Maybe just for clarification / prevent errors can get a final design with the sizes and focus states. Fx i think the focus state should be on the search field or the buttons as normal and not wrapped around

**Comment by kevinwhitedesign** [comment]
@jvedua you can run this design through @danirosefishinfor or I

**Comment by jvedua** [comment]
@tmcconechy something like this one? (I made the hit point 44px square as well):

<img width="889" alt="image" src="https://user-images.githubusercontent.com/49638020/155661740-f2c2b6f2-0a78-4aaa-9f61-fb8bff7767e0.png">


@kevinwhitedesign, @danirosefishinfor

**Comment by tmcconechy** [comment]
Looks good - except for two things.. 

1. think we should make the search field focus the same as it is now (rounded?)
2. should use 16 px margins not 20px for the 8px grid system we are using

**Comment by kevinwhitedesign** [comment]
@jvedua sending some feedback via teams so we can wrap up the design before sending to dev 🤠

**Comment by jvedua** [comment]
@tmcconechy , @kevinwhitedesign , @danirosefishinfor 

Here's an updated one based on Kevin's recommendation:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/49638020/156185048-f05f72f8-1b4c-44e7-a47d-325defd51db9.png">

wuddya think guys?

**Comment by kevinwhitedesign** [comment]
@tmcconechy we were talking about this, might appear odd visually to round the corners since it's within a box. The buttons you mean the icons? @elizabethhartley you worked on focus states, does this make sense? Not to round the corners of focus?

**Comment by tmcconechy** [comment]
Yeah but its just a wierd second variation. Im thinking of this like a normal toolbar...

**Comment by jvedua** [comment]
@tmcconechy I have discussed some changes with @kevinwhitedesign (see below)
<img width="964" alt="image" src="https://user-images.githubusercontent.com/49638020/156273478-ebaa163a-df01-4c46-9d97-5f8c355a8030.png">

I have not applied the rounded corners yet on the focused state as @elizabethhartley has yet to comment on it.

**Comment by elizabethhartley** [comment]
@tmcconechy @kevinwhitedesign I'm team rounded corners

**Comment by kevinwhitedesign** [comment]
@tmcconechy @jvedua @elizabethhartley so it is settled! 👨‍⚖️

**Comment by jvedua** [comment]
Settled is indeed! rounded corners 

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/49638020/156588604-eee6d583-3123-42c3-bce5-ef8382c64017.png">

any thoughts?

**Comment by tmcconechy** [comment]
The filter and sort buttons.. I mean. But its going to be the same as a normal button so i guess its pretty clear.

**Comment by jvedua** [comment]
I think so too.. we will not focus the area right? it will just behave the same way pop down component works?

https://latest-enterprise.demo.design.infor.com/components/popdown/example-index.html

**Comment by tmcconechy** [comment]
If the user tabbed / use the keyboard it would be focused - in one case. But its ok i think i get the point here on this so ready to code

**Comment by jbrcna** [comment]
QA passed on v4.62.0-dev. moving this ticket to Done. thank you
https://main-enterprise.demo.design.infor.com/components/listview/example-filters.html
<img width="984" alt="image" src="https://user-images.githubusercontent.com/56722184/160342919-103709d0-a1a1-4b1e-88ff-2f57fac7c1d2.png">

**Comment by jbrcna** [comment]
Hello @tjamesallen15 @ericangeles @tmcconechy, this is working as expected. However, I noticed something in safari but am unsure if this is valid. 
`Monterey Safari`
steps
1. using Safari Go to https://main-enterprise.demo.design.infor.com/components/listview/example-filters.html?theme=new&mode=light&colors=0066D4
2. notice that the border at the bottom looks cut off 
3. and the search field is somewhat have a space or not horizontally aligned?

<img width="533" alt="image" src="https://user-images.githubusercontent.com/56722184/160347818-db383113-fa77-4ece-8f21-517d56c5c0ae.png">

**Comment by ericangeles** [comment]
@tjamesallen15 can you take another look?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 can you take another look?

Will do.

**Comment by jbrcna** [comment]
the issue is now fixed. thank you.
v4.62.0-beta0
https://4620-beta0-enterprise.demo.design.infor.com/components/listview/example-filters.html
<img width="530" alt="image" src="https://user-images.githubusercontent.com/56722184/161889305-8babb91e-054c-4653-b56a-4955eac92c92.png">

**Comment by kevinwhitedesign** [comment]
Looks like there's not enough spacing/padding between the end of the search field and the filter icon. Looks like it needs 8 more pixels. Also, can we change the default hint text from "Search My Alerts" to something more generic like "Search" 

cc @jvedua @tmcconechy

**Comment by tmcconechy** [comment]
@tjamesallen15 @ericangeles -> can you make these fixes on a new PR?

**Comment by jvedua** [comment]
I have already mentioned the space between the left edge and the search icon, and the right edge to the plus icon. It should be aligned with widget label above and the ellipsis. or 16px as per our last discussion.

**Comment by jvedua** [comment]
and each of the icons (filter, sort, add) will be 44px square

**Comment by tjamesallen15** [comment]
> @tjamesallen15 @ericangeles -> can you make these fixes on a new PR?

Will do.

**Comment by jbrcna** [comment]
the issue is now resolved. moving this ticket to done.
<img width="661" alt="image" src="https://user-images.githubusercontent.com/56722184/163805148-a5dcb6a4-5d07-4bd5-9ac7-cb7a3f7c5210.png">
