### ISSUE TITLE
Datagrid range filtering bug

### ISSUE THREAD

**Issue by hohnzy** [infor-design/enterprise#6008]
Reproduce steps
1. Open demo page https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-filter?theme=uplift&variant=light
2. set any date for any date column with operator equals
3. change the operator to range
4. open the date picker
5. try to select the range dates - observe error in console

https://user-images.githubusercontent.com/11279863/148767520-1d1704c1-6749-479d-9360-6db0473e165c.mp4

**Comment by jbrcna** [comment]
this is failing in safari. there's no calendar icon and the scroll bar is missing so i need to change the height to extra small to see the date column.
https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
_Browserstack - Monterey 15.1_ 
![Large GIF (1364x708)](https://user-images.githubusercontent.com/56722184/155920546-6e437158-25a1-423e-8a79-cba5df4587de.gif)
