### ISSUE TITLE
Editor: Opening the add hyperlink modal via CTRL-H is bugged

### ISSUE THREAD

**Issue by xqses** [infor-design/enterprise#6015]
**Describe the bug**
The Soho editor allows a user to enter the Add Hyperlink modal via pressing CTRL-H on the keyboard. If the add hyperlink option in the toolbar is not visible for some reason, this will cause an error in the modal close event. 

**To Reproduce**
1. Go to 'https://main-enterprise.demo.design.infor.com/components/editor/example-index.html'
2. Resize the browser window such that the add hyperlink option is not visible
3. Press ctrl-H to open the add hyperlink modal
4. Attempt to add the hyperlink (press 'insert' button)
5. The interface will break and the user has to refresh the page.

**Expected behavior**
The new hyperlink would be added to the textarea.

**Version**

- ids-enterprise: v4.60.0

**Screenshots**
Console error: https://imgur.com/a/25t9gxJ
Line numbers in the editor.js file: https://imgur.com/a/K80ndjk

**Platform**
 - Infor Application/Team Name: Infor Homepages
 - OS Version: Windows 10
 - Browser Name: edge
 - Browser Version: Version 97.0.1072.55 (Official build) (64-bit)

**Comment by jbrcna** [comment]
this issue is now resolved.
verified in https://main-enterprise.demo.design.infor.com/components/editor/example-index.html
