### ISSUE TITLE
Datagrid: row reorder issue in safari

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6019]
**Describe the bug**
 using safari, when you drag/swipre to the left/right the row seems to be off

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-row-reorder.html
2. Hold and drag/ swipe a row to the left or right
3. See error
4. Notice that the design of row is off 

**Expected behavior**
![Large GIF (1356x542)](https://user-images.githubusercontent.com/56722184/149289646-cca88c3e-8d97-4573-aa32-8714b61d459c.gif)

**Version**

- ids-enterprise: v4.60.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/149289917-4929057d-502e-4dd0-9e02-933975e2b5db.png)

![Large GIF (1356x542)](https://user-images.githubusercontent.com/56722184/149289531-a78c7e80-25a9-466b-911e-10618739367b.gif)

**Platform**
Safari

**Additional context**

**Comment by tmcconechy** [comment]
Im doubting there is any way to fix this and it seems minor. So just backlogging for now

**Comment by jbrcna** [comment]
thank you  @tmcconechy
