### ISSUE TITLE
Datagrid: Date focus on selected date is not centered

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6022]
**Describe the bug**
Datagrid: Date focus on selected date is not centered

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html
2. Open the Datepicker
3. Select a date 
4. Open the date picker again to see the focus

**Expected behavior**
Focus should be aligned center

**Version**
4.60-ids-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/149296732-8288f9be-1fbd-4f33-8fa5-eef7da2f646e.png)
![image](https://user-images.githubusercontent.com/45757016/149296877-37e351ea-16ec-490e-9885-9e7742e73088.png)

**Platform**
Windows 11 Chrome

**Additional context**
N/A

**Comment by tmcconechy** [comment]
@janahintal im not 100% sure i see what isnt centered? Can you point it out? Everything looks pretty good to me.

**Comment by tmcconechy** [comment]
Descoping this for now
