### ISSUE TITLE
Datagrid: example paging client-side x icon misaligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6023]
**Describe the bug**
the searchfield x icon is not aligned with mobile viewport

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side.html
2. Type any text in search field
3. See error

**Expected behavior**
x icon should be aligned

**Version**

- ids-enterprise:v4.60.0-dev

**Screenshots**
`iOS`
![image](https://user-images.githubusercontent.com/56722184/149298297-8334b3c7-9ad8-4514-aea0-a45f064e877f.png)

`Android`
![image](https://user-images.githubusercontent.com/56722184/149298438-e9a9c791-533f-4ea9-9811-03a68b146897.png)

**Platform**
Mobile Android & iOS

**Additional context**

**Comment by tmcconechy** [comment]
@ericangeles here is another case. as far as i can tell it doesnt seem to be fixed by https://github.com/infor-design/enterprise/pull/6018 or https://github.com/infor-design/enterprise/pull/6025

sorry :(

**Comment by ericangeles** [comment]
@tmcconechy picking this up!

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.60.0-dev. thank you
https://main-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side.html
![image](https://user-images.githubusercontent.com/56722184/150060637-7e83307e-34e9-4e3b-af71-2a7390ce2f9a.png)
