### ISSUE TITLE
Modal: Dialog content does not fill the space inside modal dialog properly (extra space on the right side) when window size is under 481px

### ISSUE THREAD

**Issue by palof** [infor-design/enterprise#6024]
**Describe the bug**

Elements inside a modal dialog that are set to use the full available width inside the modal dialog (i.e. full width of div.modal-body-wrapper minus paddings) suddenly get an extra space on the right side once the window width is shrunk under 481px (i.e. 480px and lower). 

This happens because max-width of div.modal-body-wrapper is set to (window width - 46px) while the parent element div.modal-content width is (window width - 34px), so there is a 12px gap on the right. Thus div.modal-body-wrapper does not use all the available width it's supposed to use.

The underlying cause is that there is a style for .modal (for context: div.modal > div.modal-content > div.modal-body-wrapper) applied when window width is above 480px (@media screen and (min-width: 481px)) that sets max-width of the div.modal to 90%. 

Once the window width goes under 481px, this style is no more applied, but rather the default style for .modal is applied where max-width is set to 100%

The max-width of div.modal-body-wrapper is calculated in the Modal.resize() function. In the case of div.modal having max-width set to 100%, the calculation goes wrong and sets the max-width of div.modal-body-wrapper to a lower value than actually needed.

**To Reproduce**

1. In Chrome, go to 'Modal', e.g. https://design.infor.com/code/ids-enterprise/latest/modal
2. Click on 'View Example' blue icon on the right above the Modal Example area, which takes you to https://design.infor.com/code/ids-enterprise/latest/demo/components/modal/example-index?theme=uplift&variant=light
3. Click on the 'Show Modal' button
4. Open DevTools via F12 and click on the 'Toggle device toolbar' button in the top left
5. Set Dimensions to Responsive and set 481px for width
6. Tweak the size of the 'Problem' input in DevTools so it occupies the whole available width (i.e. width: 100%;). Observe that the input is centered symmetrically inside the modal
7. Change the width to 480px. Observe that the gap on the right is larger than the gap on the left. Hover over div.modal-body-wrapper in DevTools -> Elements and observe 12px extra "margin" highlighted on the right. This is because of the max-width of div.modal-body-wrapper set to a lower value than the parent div.modal-content can accomodate

**Expected behavior**

The content set to fill all the available width inside modal should be centered correctly, regardless of the window width being 481px+ or less.

**Version**

- ids-enterprise: 4.59.0 (initially found on 4.57.0)

**Screenshots**

![modal480px](https://user-images.githubusercontent.com/10611180/149311551-480561e7-662e-42e1-8528-5ad98b2a890f.png)

**Platform**

 - Infor Application/Team Name: Infor Workforce Management
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: 97.0.4692.71 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I think this isnt a bug. Because the inputs by default are 300px wide this is correct. This can be "fixed" by adding the `form-responsive` class to the responsive grid container holding the fields. this will make them 100%. See https://main-enterprise.demo.design.infor.com/components/form/example-inputs.html

**Comment by palof** [comment]
Please note the step 6 - change the width of the Problem input field to 100% manually in DevTools and then observe the behavior (does not really matter if the 100% width is set manually in DevTools or is applied via a stylesheet, just wanted to make the reproduction as simple as possible using IDS default examples which don't have width 100% by default)

**Comment by tmcconechy** [comment]
Ok i see. To anyone that picks this up try to make a form-responsive new modal example and test this.

**Comment by tmcconechy** [comment]
Example fixed on https://main-enterprise.demo.design.infor.com/components/modal/example-index?theme=uplift&variant=light (once deployed)

**Comment by janahintal** [comment]
Passed QA. Re-tested this issue on https://main-enterprise.demo.design.infor.com/components/modal/example-index?theme=uplift&variant=light will now move this to Done. Thanks!

![image](https://user-images.githubusercontent.com/45757016/157850834-def50e5d-4bf4-4d47-ba3b-b750903eeaf6.png)
