### ISSUE TITLE
Horizontal splitter, with tabs in the header has its tabs and tabs content hidden

### ISSUE THREAD

**Issue by debuis** [infor-design/enterprise#6030]
**Describe the bug**
If you use the horizontal splitter, and inside the header section multiple tabs. 
The tabs and the tabs content are hidden.

**To Reproduce**
https://stackblitz.com/edit/ids-quick-start-1301-p2xf9h

1. Take the getting started code
2. Copy the horizontal splitter demo code into app.component.html
3. Copy the first the best tab demo code into the  splitter header section
4. After loading there is no tab content visible

**Expected behavior**
The target is to have content in these tabs clickable and the action is to show its details in the splitter footer part.

**Version**
Latest

**Platform**
 - Infor Application/Team Name: Infor Documentation and Translation
 - Device: Chrome on windows desktop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Assume it would be ok to change the markup if we can get this to work another way? Should also make an example of this and a test.
