### ISSUE TITLE
File Upload (Advanced): slow uploading

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#6031]
**Describe the bug**
Hi, when uploading a file using File Upload Advanced it seems to take 1 second for each KB uploaded (I know it sounds strange)
For example, uploading 31KB file took around 31 seconds, a 200KB took around 200 seconds.

However, using [https://design.infor.com/code/ids-enterprise/latest/demo/components/fileupload-advanced/example-send.html](https://design.infor.com/code/ids-enterprise/latest/demo/components/fileupload-advanced/example-send.html) it works fast as expected (1.2MB file took less than 2 seconds to upload).

I'm not sure if I'm doing something wrong - that's my first time using it.
 

**To Reproduce**

1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/fileupload-advanced/example-index.html](https://design.infor.com/code/ids-enterprise/latest/demo/components/fileupload-advanced/example-index.html)
2. Upload a file
3. Notice how much time it takes to upload
4. Go to  [https://design.infor.com/code/ids-enterprise/latest/demo/components/fileupload-advanced/example-send.html](https://design.infor.com/code/ids-enterprise/latest/demo/components/fileupload-advanced/example-send.html) 
5. Upload the same file

**Expected behavior**
Should be fast like `example-send.html`

**Version**

- ids-enterprise: v4.73 and above

**Screenshots**

https://user-images.githubusercontent.com/34129313/149660966-3e5448a0-81f6-44be-85f5-a44cb8c13e31.mp4

**Platform**
-- seen both in Chrome and Firefox

**Additional context**
Thanks!

**Comment by tmcconechy** [comment]
@jonathanamiran we did this on purpose in the example so you can see the status. Its not really uploading anything and is completely a simulation.

In the next gen 5.0 version we did change this so you have to set the speed in the network tab of dev tools. So given this is just an example im going to close.
