### ISSUE TITLE
The dirty indicator intermittently sticks when there's a lot of page break (return) on the RTE. Happens on EDGE browser only.

### ISSUE THREAD

**Issue by gilbugauisan** [infor-design/enterprise#6032]
**Describe the bug**
The dirty indicator intermittently sticks when there's a lot of page break (return) on the RTE. Happens on EDGE browser only.

**To Reproduce**
1. Go to 'https://master-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking-reset.html' using EDGE browser.
2. Edit the text on the RTE and use multiple page breaks (return) as much as possible. (see screenshots)
    - put the mouse cursor at the end of the first word of the first line and press enter
    - put the mouse cursor at the end of the first word of the second line and press enter
    - put the mouse cursor at the end of the first word of the third line and press enter
    - repeat on each line with at least 10 page breaks (enter key) 
3. Click the 'Reset Dirty' button.

**Expected behavior**
Dirty indicator should be cleared.

**Version**
- ids-enterprise@4.57.2

**Screenshots**
![Reset Dirty Intermittent Not Working on EDGE Browser](https://user-images.githubusercontent.com/74726741/149704771-1c17d5e4-a9cd-48f5-8e18-5ead1e197494.gif)
![Reset Dirty Intermittent Not Working on EDGE Browser 2](https://user-images.githubusercontent.com/74726741/151480944-34101156-2c8c-4383-9675-70755851d536.gif)

**Platform**
 - Infor Landmark
 - Device: Laptop
 - OS Version: Windows 10
 - Browser Name: Microsoft EDGE
 - Browser Version: Version 97.0.1072.55 (Official build) (64-bit)

**Comment by tmcconechy** [comment]
I wasn't easily able to reproduce this. So made it minor.

**Comment by rvilleno** [comment]
Hi @tmcconechy will there be a plan to include this to your upcoming sprint? This particular git ticket is linked to a JT of a customer which is already out of compliance in SLO.

**Comment by tmcconechy** [comment]
Is there anyways you make these steps more concrete. Its very difficult to reproduce and i only saw it happen once.

**Comment by tmcconechy** [comment]
There might be a chance its this issue : https://github.com/infor-design/enterprise/issues/5937
Which has a pull request now https://github.com/infor-design/enterprise/pull/6050 you can test?

**Comment by gilbugauisan** [comment]
Still was able to reproduce with latest pull.

**Comment by tmcconechy** [comment]
@gilbugauisan the fixes are here now https://main-enterprise.demo.design.infor.com/components/editor/example-index.html so you can test there.

But i tried your steps and they are pretty vague, can you update the steps so i can see what your seeing? (the video doesnt really help)

**Comment by gilbugauisan** [comment]
Hi @CindyMercadoReyes, please refer to the screenshot in the description to replicate. If you still can't reproduce, let's have a quick call for me to assist you.

**Comment by tmcconechy** [comment]
@gilbugauisan is there any way you can write out the steps to reproduce so they are more clear "use multiple page breaks (return) as much as possible" is pretty unclear to me and multiple people will need to be able to read the issue to solve it

**Comment by gilbugauisan** [comment]
Updated the description and attached another screenshot. Please let me know if it is still unclear.

**Comment by tmcconechy** [comment]
ok that helps. i do see it now.

**Comment by tmcconechy** [comment]
Was fixed early so can be included in 4.61 -> thanks @tjamesallen15

**Comment by jbrcna** [comment]
**QA Failed.** test run on Edge Mac & Win10 Edge 97
https://4610-beta0-enterprise.demo.design.infor.com/components/editor/test-dirty-tracking-reset.html
`MAc EDge`
![Large GIF (940x586)](https://user-images.githubusercontent.com/56722184/157398239-2eb6e9a1-7818-43e6-a259-bf0a1192e233.gif)

`Win10 Edge 97`
![Large GIF (940x586)](https://user-images.githubusercontent.com/56722184/157398271-6b620bfe-e5e8-4f6b-91b6-f8203582b1b2.gif)

**Comment by tmcconechy** [comment]
@tjamesallen15 can you take another look at this case? We would want this in 4.61.x so need a fix by end of week..

Thanks!
