### ISSUE TITLE
Datagrid: Row Status on Tree List Not Clearing on a Single Row

### ISSUE THREAD

**Issue by gilbugauisan** [infor-design/enterprise#6033]
**Describe the bug**
Calling clearRowError to clear row status of a single row not working on tree list

**To Reproduce**
1. On dev mode, edit _'ids\enterprise\app\views\components\datagrid\test-tree-rowstatus.html'_
2. Change this block of code (line 70-93) to use clearRowError api (see image below)
![image](https://user-images.githubusercontent.com/74726741/149764245-6ac66f9d-ad3a-4ed8-975e-19bbc9c4c641.png)
3. Save
4. Open the component and test

**Expected behavior**
Should clear row status on a single row.

**Version**
- ids-enterprise: 4.60.0-dev

**Screenshots**
![Datagrid - Row Status on Tree List Not Clearing Single Row 2](https://user-images.githubusercontent.com/74726741/149764635-78ff5795-74f8-49b0-be6b-b1fba38e7080.gif)

**Platform**
 - Infor Landmark
 - Laptop/Desktop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 96.0.4664.110 (Official Build) (64-bit)

**Additional context**
The API clearRowError is working fine on standard list but not on tree list.

**Comment by gilbugauisan** [comment]
Hello, do we have updates on this issue?

**Comment by tmcconechy** [comment]
No, It got marked as stake. But will add it to the next sprint backlog.

**Comment by yohannahbautista** [comment]
Hello, the current fix I have for clear makes it that both the parent and children node statuses are cleared. Should there be a method for clearing only specific child nodes?
