### ISSUE TITLE
Modal: Spinbox not limited when clicking Enter

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#6036]
**Describe the bug**
Hi, when there is a Spinbox inside Modal that is limited, if the user is typing higher number and clicking Enter (to close the Modal) the higher number is set.

**To Reproduce**

1. Go to [https://jsfiddle.net/sebulbajoe/g286qxdp/11/show](https://jsfiddle.net/sebulbajoe/g286qxdp/11/show)
2. Click on Show Modal
3. The limit is 10
4. Type higher number, for instance 55
5. click Enter on the keyboard
6. see that the quantity changed to 55
7. However, when clicking with the mouse on the submit button that quantity will change to the Max quantity
8

**Expected behavior**
Should behave the same as when clicking the submit button with the mouse.
The event to update Spinbox should occur before modal close event.

**Version**

- ids-enterprise: v4.59.0

**Screenshots**

https://user-images.githubusercontent.com/34129313/149911625-ed5c9b25-3cba-41cb-9eed-3d70b29d5714.mp4

**Platform**

 - OS Version :Windows 10
 - Browser Name: Chrome

**Additional context**
Thanks!

**Comment by jonathanamiran** [comment]
a workaround is using suppressEnterKey:true in the Modal settings

**Comment by jbrcna** [comment]
this is working as expected. moving this ticket to done
https://main-enterprise.demo.design.infor.com/components/modal/example-spinbox
![Large GIF (1072x666)](https://user-images.githubusercontent.com/56722184/155469402-25a5cb5c-e182-4f8c-b12c-5923c0b9d220.gif)
