### ISSUE TITLE
Contextual Action Panel: Toolbars inside the body of the panel are being displaced

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#6041]
**Describe the bug**
All toolbars that exist in the body of the CAP are being moved to the CAP's header. This behavior is unwanted and it is corrupting the display of the CAP by giving it multiple header toolbars. Only the first toolbar in the CAP should be treated as the CAP's header toolbar. Any other toolbars in the CAP should be left in their place. There can be many good reasons for having toolbars in a CAP's body (i.e. one or more grids with their toolbars in the CAP).

**To Reproduce**
The only IDS example I could find of a CAP with a toolbar in the body is https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-contextualactionpanel.html  This seems to intentionally move the toolbar for this specific use case of a grid CAP. But there can be many use cases where we have a grid toolbar inside a CAP and we don't want the grid's toolbar moved up into the header. The below solution will fix the problem and still allow for this particular use case of moving the grid's toolbar up into the header (if no other header toolbar exists).

**Solution**
The coding fix for this bug is simple and safe. Only 2 lines of code need tweaked. Please change contextualactionpanel.js so that it only looks for the **first** toolbar and buttonset instead of finding multiple of them...

**line 265:**
`let buttonset = this.panel.find('.toolbar .buttonset, .flex-toolbar .buttonset').first();`

**line 269:**
`this.toolbar = this.panel.find('.toolbar, .flex-toolbar').first();`

**Expected behavior**
The CAP should only have one header toolbar, and all other toolbars should be left where they are.

**Version**
- ids-enterprise: v4.59.1 and earlier

**Platform**
 - Infor Application/Team Name: CSD
 - Device: laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 97.0.4692.71 (Official Build) (64-bit)

Thank you!

**Comment by tmcconechy** [comment]
@aaronpikkarainen i think the change makes sense but i tried to reproduce it and your lines didnt actually fix it.. This is the change i made to test-contextualactionpanel.html

```

<div class="row">
  <div class="six columns">

    <button type="button" id="js-contextual-panel" class="btn-secondary contextual-action-panel-trigger no-init">
      Open Panel with Grid
    </button>
    <div class="contextual-action-panel" style="display:none">
      <div class="full-width">
        <div class="flex-toolbar" role="toolbar">
          <div class="title">
            Custom Grid Toolbar
            <span class="datagrid-result-count">(N Results)</span>
          </div>
          <div class="buttonset">
            <label class="audible" for="common-toolbar-searchfield">Keyword Search</label>
            <input id="common-toolbar-searchfield" name="common-toolbar-searchfield" class="searchfield" />

            <button type="button" class="btn">
              <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
                <use href="#icon-filter"></use>
              </svg>
              <span>Category</span>
            </button>
          </div>

          <div class="more">
            <button class="btn-actions" type="button">
              <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
                <use href="#icon-more"></use>
              </svg>
              <span class="audible">More Actions</span>
            </button>
            <ul class="popupmenu">
              <li><a href="#">Option One</a></li>
              <li><a href="#">Option Two</a></li>
              <li><a href="#">Option Three</a></li>
              <li class="separator single-selectable-section"></li>
              <li class="heading">Row Height</li>
              <li class="is-selectable"><a data-option="row-extra-small" href="#" data-translate="text">ExtraSmall</a></li>
              <li class="is-selectable"><a data-option="row-small" href="#" data-translate="text">Small</a></li>
              <li class="is-selectable"><a data-option="row-medium" href="#" data-translate="text">Medium</a></li>
              <li class="is-selectable is-checked"><a data-option="row-large" href="#" data-translate="text">Large</a></li>
            </ul>

          </div>
        </div>
      </div>
      <div class="full-width">
        <div class="flex-toolbar" role="toolbar">
          <div class="toolbar-section title">
            <h2>Compressors <span class="datagrid-result-count">(N Results)</span></h2>
          </div>
        </div>
        <div class="datagrid"></div>
      </div>
    </div>
    </div>
</div>
```

This errors and does weird things still.. So i think we need to make sure we have the right markup to test.

As a "workaround" you could use the buttons setting https://github.com/infor-design/enterprise/blob/main/app/views/components/contextualactionpanel/example-centered.html#L57 maybe?

**Comment by aaronpikkarainen** [comment]
@tmcconechy, I took your markup and expanded it into a nice test case (see attached zip file). Please add this to the suite.

[test-toolbar-in-body.zip](https://github.com/infor-design/enterprise/files/7900545/test-toolbar-in-body.zip)

I tested the 2 changed lines of code in contextualactionpanel.js, and things seem to work well (see screenshots below). However, it looks like you guys have some css that is making the grid toolbar title too big. It would be nice to get that cleaned up if possible.

**Before (problem)**

![image](https://user-images.githubusercontent.com/14128010/150213861-523b9d72-edc2-4b16-ac68-d0f3a5bdb78b.png)


**After (fix in cap js)**

![image](https://user-images.githubusercontent.com/14128010/150213920-2e584379-9fd5-4c2e-bb9d-a80d1c98691d.png)

**Comment by jbrcna** [comment]
this is working as expected. moving this ticket to done
https://main-enterprise.demo.design.infor.com/components/datagrid/test-cap-with-toolbar-inside-of-the-body-panel.html
<img width="970" alt="image" src="https://user-images.githubusercontent.com/56722184/155470428-39454be2-146b-475a-8b12-cf2ddfb2c4c1.png">

**Comment by aaronpikkarainen** [comment]
Thank you all for getting this fixed.
