### ISSUE TITLE
2 Calendars in different widgets will both show up in the first widget

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#6042]
**Describe the bug**
Some widget developers noticed that when they added 2 widgets with a calendar in Homepages, both calendars often ended up in the same widget. I was able to reproduce this by altering the homepage.demo file in the IDS component samples. I am not sure if the issue is in enterprise or enterprise-ng.

**To Reproduce**
1. Replace the Demo sample with (or create a new Homepage sample):
```
<div soho-homepage
  (resize)="onResize($event)">
    <div soho-widget widgetWidth="triple">
      <div soho-widget-header>
        <div soho-widget-title tabIndex="0"><h2>Chart Title</h2></div>
        <button soho-button="icon" icon="more" soho-context-menu menu="action-popupmenu" trigger="click" class="btn-actions"></button>
      </div>
      <div soho-widget-content>
        <div class="chart-container" style="height:100%">
          <div soho-chart
            [dataSet]="getBarChartData()"
            type="bar"
            showLegend="true">
          </div>
        </div>
      </div>
    </div>
    <div soho-widget>
      <div soho-widget-header>
        <div soho-widget-title tabIndex="1"><h2>Calendar 1</h2></div>
        <button soho-button="icon" icon="more" soho-context-menu menu="action-popupmenu" trigger="click" class="btn-actions"></button>
      </div>
      <div soho-widget-content>
        <div id="jobstorelease-1">
			  <div class="calendar-class" soho-calendar
				 [showViewChanger]="false"
				 [showToday]="true">
					<div class="month-content" soho-calendar-monthview></div>
			  </div>
		</div>
      </div>
    </div>

    <div soho-widget>
      <div soho-widget-header>
        <div soho-widget-title tabIndex="2"><h2>Calendar 2</h2></div>
        <button soho-button="icon" icon="more" soho-context-menu menu="action-popupmenu" trigger="click" class="btn-actions"></button>
      </div>
      <div soho-widget-content>
			 <div id="jobstorelease-2">
			  <div class="calendar-class" soho-calendar
				 [showViewChanger]="false"
				 [showToday]="true">
					<div class="month-content" soho-calendar-monthview></div>
			  </div>
		</div>
      </div>
    </div>

  <ul soho-popupmenu id="action-popupmenu"
    (selected)="onSelected($event)"
    (beforeopen)="onBeforeOpen($event)"
    (close)="onClose($event)"
    (open)="onOpen($event)">
    <li soho-popupmenu-item><a soho-popupmenu-label>Action One</a></li>
    <li soho-popupmenu-item><a soho-popupmenu-label>Action Two</a></li>
  </ul>
</div>
```

2. Build & run and open the sample
3. Notice that the 2 calendars ends up in the same widget

**Expected behavior**
There should be one calendar in each of the 2 calendar widgets

**Version**
- ids-enterprise-ng: 10.10

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/149118066-ee7ba51d-c3fc-46f6-a5e2-53cc54361b72.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name Chrome
 - Browser Version: Version 97.0.4692.71 (Official Build) (64-bit)

**Additional context**
-

**Comment by tmcconechy** [comment]
I pushed a fix for this issue. But wanted to mention it IS possible to use monthviews by themself in the widget. I think this are more appropriate in size for widgets so just mentioning this does work if done the same way on a previous version.

https://main-enterprise.demo.design.infor.com/components/homepage/example-monthviews.html

**Comment by SofiK** [comment]
I tried with both monthview and calendar before and the monthview was working but not the calendar.

**Comment by tmcconechy** [comment]
@SofiK yes that was my point - i think it looks better in a small widget (less scrolling ect). So that could be used depending the use case without any updating.
