### ISSUE TITLE
Datagrid: Icons are not aligned in file upload column

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6044]
**Describe the bug**
Datagrid: Icons are not aligned in file upload column

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-fileupload.html
2. Upload a file

**Expected behavior**
Icons should be aligned

**Version**
4.60-ids-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/150266057-34c7cd68-bc75-4ab0-96e1-05e9e9e63605.png)

**Platform**
All major browser, OS and devices. 

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Seems like an extra fix to https://github.com/infor-design/enterprise/pull/6006 - so treating this as failed.
