### ISSUE TITLE
Timepicker: Selecting the hour and AM/PM dropdowns automatically selects hour 1

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6049]
**Describe the bug**
When only selecting from the hour dropdown and AM/PM dropdown, the hour 1 automatically gets selected.

**To Reproduce**
1. Go to ['...'](http://localhost:4000/components/timepicker/example-index.html)
2. Click on the timepicker button
3. Select an hour from the dropdown (ex. 3)
4. Select PM on the AM/PM dropdown
Result: The hour dropdown value changes to 1.

**Expected behavior**
The dropdown options on a timepicker should reflect what the user has selected.

**Version**
- ids-enterprise: v4.60.0-dev

**Screenshots**
![Automatic hour change](https://user-images.githubusercontent.com/76002134/150423168-c4857a30-d1c5-478a-a53a-f194f14c7af5.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by jbrcna** [comment]
this issue is now resolved.
verified in https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html
![Large GIF (908x510)](https://user-images.githubusercontent.com/56722184/153811634-22a4a637-e46b-49c0-82d3-59ef245e593b.gif)
