### ISSUE TITLE
Datagrid - fit last column during resize

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#605]
**Is your feature request related to a problem? Please describe.**

Discussed with landmark and on chat several times. 
**Describe the solution you'd like**

Teams would like an option similar to "fit" on this example:

https://www.jqueryscript.net/demo/jQuery-Plugin-For-Draggable-Resizable-Table-Columns-colResizable/
See also 
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ColumnResizing/jQuery/Light/

Keep the existing method (similar to flex in the example)
**Additional context**

- landmark
- teams (marek and victor)

**Comment by tmcconechy** [comment]
All these 3 are closely related
https://github.com/infor-design/enterprise/issues/2130
https://github.com/infor-design/enterprise/issues/1671
https://github.com/infor-design/enterprise/issues/605

**Comment by tmcconechy** [comment]
Maybe be fixed by #2825

**Comment by tmcconechy** [comment]
Also if this is fixed https://github.com/infor-design/enterprise/issues/1671 will be fixed

**Comment by tmcconechy** [comment]
Fixed this when implementing #2825 
As can be seen in the Video https://drive.google.com/file/d/1pzerRP5uPP11WHRWCVYaZchpXZnCKswp/view

**Comment by jbrcna** [comment]
QA **FAILED**
the columns with an option similar to "fit" function work fine. However, In `Safari` Browser after you use the sort in Datagrid, the columns become frozen. you can't resize anymore

Verified in http://4240-beta0-enterprise.demo.design.infor.com/components/datagrid/example-index.html

**Comment by tmcconechy** [comment]
This is already mentioned on https://github.com/infor-design/enterprise/issues/1818#issuecomment-564950660 so working on it there on just one issue. Moving this to done.
