### ISSUE TITLE
Modal: Content in a new panel is disabled

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6056]
**Describe the bug**
Content that is originally hidden when a modal is initialized is disabled once the content is no longer hidden.

**To Reproduce**
1. Go to [modal-wizard-content.zip](https://github.com/infor-design/enterprise/files/7927912/modal-wizard-content.zip)
2. Click on Show Modal
3. Click Next
Result: The switch and input field are disabled

**Expected behavior**
Panels that were previously hidden should have enabled fields once the panel is shown.

**Version**
- ids-enterprise: v4.60.0-dev

**Screenshots**
![Uploading Elements in second panel are disabled.gif…]()

**Platform**
 - Infor Application/Team Name: lawson
 - Device: N/A
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 97.0.4692.99 (Official Build) (64-bit)

**Additional context**
This issue seems to be caused by the changes in this ticket: 
https://github.com/infor-design/enterprise/issues/5875

**Comment by s-werking** [comment]
![Elements in second panel are disabled](https://user-images.githubusercontent.com/76002134/150842491-6ebb368e-05fa-4e48-8097-d77e1d7dced0.gif)

Apologies, here is the gif

**Comment by tmcconechy** [comment]
@s-werking this was reported on https://github.com/infor-design/enterprise-ng/issues/1210 and I think we patched it already should be fixed in 4.59.2 and on main branch. Did you test this on main as i saw that you mentioned 4.60? But should be fixed now...

**Comment by tmcconechy** [comment]
yeah dropped this into main and it works - so is the same issue. also made a 4.60.0-dev.20220123 dev version but for you , i'd take 4.59.2 and verify.

**Comment by s-werking** [comment]
I took the latest on main and verified it is fixed, thanks! Must not have pulled the latest version before testing.
