### ISSUE TITLE
Tooltip: <p> is translated into characters in tooltip text

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6059]
**Describe the bug**
Tooltip content that includes <p> will have an output of $('.tooltip').text() that includes <p> as \n characters.

**To Reproduce**
1. go to https://main-enterprise.demo.design.infor.com/components/tooltip/example-index.html
2. hover the button
3. type $('.tooltip').text() in the console and see all the /n stuff

**Expected behavior**
Only the text shown should be included in $('.tooltip').text(), the <p> should not be included in characters.

**Version**
- ids-enterprise: v4.60.0-dev

**Screenshots**

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: Version 97.0.4692.99 (Official Build) (64-bit)

**Additional context**
This changed in v4.53

**Comment by tmcconechy** [comment]
@ericangeles whats your assessment of this? i think its a recent change: https://github.com/infor-design/enterprise/commits/main/src/utils/xss.js

**Comment by ericangeles** [comment]
@tmcconechy I can take a look again.

**Comment by janahintal** [comment]
QA Passed. Thanks! Verified in https://main-enterprise.demo.design.infor.com/components/tooltip/example-index.html
![image](https://user-images.githubusercontent.com/45757016/152764729-6eca5929-8670-4a88-bab4-fe6ffd92d5ce.png)
