### ISSUE TITLE
Editor: ReadOnly Editor + Preview and HTML mode should work together

### ISSUE THREAD

**Issue by hemantg05** [infor-design/enterprise#6060]
Currently soho editor removes all buttons in read only mode. So, user is not able to see HTML markup in HTML mode.

### Expected Behaviour
User should be able to view HTML markup in HTML mode and should be able to toggle between Preview and HTML mode

### Actual Behaviour
 User is not able to view HTML markup in HTML mode as there is no button to change to HTML mode. User is forced to stay on preview mode.

**Additional context**
Infor PIM

**Comment by tmcconechy** [comment]
Closing stale issues
