### ISSUE TITLE
Testing: Create a Puppeteer Script for Actionable Button Card

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#6062]
Describe the Issue
Create a unit testing for Actionable Button Card.

See attached BDD for more information.
[BDDStory_github5768.docx](https://github.com/infor-design/enterprise/files/7941584/BDDStory_github5768.docx)

Related github issue
#5768

**Comment by maezcruz** [comment]
cc: @CindyMercadoReyes

**Comment by CindyMercadoReyes** [comment]
This task is now completed.
