### ISSUE TITLE
Datagrid: Setting stretchColumn to "last" does not stretch the last column

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6063]
**Describe the bug**
The last column does not get stretched when the datagrid setting stretchColumn is set to "last".

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/test-stretch-last-column.html
2. Note that the last column is not stretched
3. Remove the stretchColumn setting in test-stretch-last-column.html
4. Go to http://localhost:4000/components/datagrid/test-stretch-last-column.html
5. Note that the table looks the same without the stretchColumn setting

**Expected behavior**
When the stretchColumn setting is set to "last", the columns should all be their set pixel widths and the last column should fill the rest of the table if there is any width left. If the total column widths are over the table width, then all of the columns including the last should be their set pixel width.

**Version**
- ids-enterprise: v4.60.0-dev

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows10
 - Browser Name: chrome
 - Browser Version: Version 97.0.4692.99 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
As a workaround what seems to work is setting it to the name.

```
stretchColumn: 'orderDate', // or columns[columns.length -1].id
```

Maybe we phase `last` out for simplicity. Would suggest doing this...

**Comment by s-werking** [comment]
The only issue with that solution is that when you resize the last column to be close to the end of the table and resize the next column over, the last column disappears. Gif for reference:
![Disappearing last column](https://user-images.githubusercontent.com/76002134/151219770-0710ad8b-2655-4c9b-965b-49c97605b5fe.gif)

**Comment by tmcconechy** [comment]
I think the stretch column should be used for readonly views (no resize). Its a bit limited. Would probably be better off without it.

This is probably fixable but i might have to rework how the columns are done. I will consider this for the v5

**Comment by tmcconechy** [comment]
Maybe https://github.com/infor-design/enterprise/commit/46306482340716a7b8cd9467078388e453329f9e#diff-13c32b0c73b40992aa6d376fb22d6746845a3b7d6d2545e19bd30687bcabb5a5

**Comment by jbrcna** [comment]
this is now working in Chrome but Failed in Safari browser
v4.60.0-dev
`Browserstack SAfari Browser`
https://main-enterprise.demo.design.infor.com/components/datagrid/test-stretch-last-column.html
![Large GIF (1206x632)](https://user-images.githubusercontent.com/56722184/152085533-6158c93d-a512-4b9d-908d-46617d900732.gif)

Also, try resizing the row height after you resize the column. it will look like this
Steps
1. resize the last column to the right -> make sure you can still see it and scroll to it
2. resize the next column to it to the left -> make sure you can still scroll right and see it
3. Change row height to small or any
![image](https://user-images.githubusercontent.com/56722184/152085303-df84019e-aaf1-40e9-acf4-6b25392b5c08.png)

**Comment by jbrcna** [comment]
Thanks for clarification @tmcconechy , here's the ticket for the new issue. https://github.com/infor-design/enterprise/issues/6087
