### ISSUE TITLE
CAP: example markup issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6065]
**Describe the bug**
there are some fields that are missing in this example page

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html
2. Click the button
3. See error
4. 

**Expected behavior**
![image](https://user-images.githubusercontent.com/56722184/151310201-cda565b1-4db4-4e8f-9a04-08be3e912a27.png)

**Version**

- ids-enterprise:4.60.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/151310238-3c6c9f4c-987c-4303-ab33-6d7034a03586.png)

**Platform**
all browsers

**Additional context**

**Comment by tmcconechy** [comment]
Seems like just a bad example hasnt worked in a while https://4550-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html

So marking minor

**Comment by jbrcna** [comment]
this now looks as expected. However, the fields arent working. 
v4.62.0-dev
https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html
![Large GIF (784x554)](https://user-images.githubusercontent.com/56722184/158135060-a39cd0ac-8125-4ce4-84be-dd5693b16320.gif)

**Comment by tmcconechy** [comment]
this seems like they should work... @ericangeles any ideas?

**Comment by ericangeles** [comment]
@tmcconechy hmm can't recall but we can take a look at this one.

**Comment by davidcarlsonberg** [comment]
https://github.com/infor-design/enterprise/pull/6224 should fix the dropdown issue. They were not initialized.

**Comment by jbrcna** [comment]
this is now working in New Theme. However, when using classic theme it creates elements after clicking the` #trigger-1 `button
https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html?theme=classic&mode=light&colors=2578a9
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/56722184/160972034-c2f87327-0083-43a0-a212-4c44e07d4c6d.png">
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/56722184/160972193-01d63293-4f08-4da2-bd14-ef3aaec92c05.png">

**Comment by davidcarlsonberg** [comment]
I'm not sure why that was even originally originally in the example. Could we just remove the `insertAfter` @tmcconechy or is this meant to demonstrate something?

**Comment by tmcconechy** [comment]
Its basically trying to show you can have markup to construct the contextual action panel so as long as there is markup in the page and it works and shows that in the CAP, i think that should be fine

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
