### ISSUE TITLE
Tabs: Additional Overflow Issue

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#6068]
**Describe the bug**
This is similar to the following issue #5554

- take this attached file [example-desktop-breakpoint.zip](https://github.com/infor-design/enterprise/files/7949115/example-desktop-breakpoint.zip) and put it in where we have a composite form, and there are tabs in a header.
- go to http://localhost:4000/components/tabs/example-desktop-breakpoint.html?locale=ar-SA
- tab to the tabs
- arrow left/right and you will see the issue

See the following
![image](https://user-images.githubusercontent.com/29673378/151328072-6b605981-5721-43c6-a47b-7aee7646e504.png)

**Expected behavior**
outlines should be aligned.

**Version**
ids-enterprise: v4.60.0

**Platform**

    Infor Application/Team Name: Landmark Client
    Device: (if applicable): NA
    OS Version: Windows 10
    Browser Name: Chrome
    Browser Version: 92.0.4515.159 (Official Build) (64-bit)

Additional context
https://jira.lawson.com/browse/LMCLIENT-36225

**Comment by tmcconechy** [comment]
cc @tjamesallen15 did you look at these before?

**Comment by tmcconechy** [comment]
ok looks like a new case - have another look this sprint, please

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.62.0-dev.
https://main-enterprise.demo.design.infor.com/components/tabs/example-desktop-breakpoint.html?theme=classic&mode=light&colors=2578a9&locale=ar-SA
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/56722184/159623381-a24c8c04-99d3-4cab-bbf1-d32052e5fe33.png">
