### ISSUE TITLE
[Mobile] Contextual Action Panel Component-Focus on previous element does not disappear 

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#607]
**Describe the bug**
[Mobile] Focus on previous element does not disappear 

**To Reproduce**
1. Open any browser on Android and iOS devices
2. Go to http://master-enterprise.demo.design.infor.com/components/contextualactionpanel/example-index.html
3. Open Contextual Action Panel
4. Select Infor from Company Name dropdown
5. Select 3569 from Purchase Form dropdown
6. Notice that the focus on Company Name dropdown doesn't disappear

**Expected behavior**
Company Name dropdown should disappear

**Screenshots**

![image](https://user-images.githubusercontent.com/39101346/44105186-e05b4342-9fbe-11e8-9d54-705d65084b87.png)

**Platform**
 - [All Mobile Devices

**Additional context**
None

**Comment by tmcconechy** [comment]
Descoping this for now
