### ISSUE TITLE
DataGrid: Typing "12:00" automatically selects "00:00" in the 24H time picker

### ISSUE THREAD

**Issue by ktfields** [infor-design/enterprise#6076]
**Describe the bug**
TimePicker: Typing "12:00" automatically selects "00:00" in 24H time format

**To Reproduce**

1. Go to https://jsfiddle.net/ktfields117/cx9Lm8to/
2. Type 12:00, then press enter or use the time picker to modify any cell under "Time 24" column
3. Observe the value in the cell
Actual Result: The cell value becomes "00:00" automatically

**Expected behavior**
The cell value should be "12:00"

**Version**

- ids-enterprise: 4.60.0-dev

**Platform**
 - Infor Application/Team Name: Lawson System Foundation (Portal)
 - Browser Name: Google Chrome
 - Browser Version: 97.0.4692.99

**Additional context**

**Comment by tmcconechy** [comment]
Is the description of this issue correct? I tried the steps but do not see any issue. I.E. When i type 12:00 and hit enter it stays as 12:00

**Comment by s-werking** [comment]
Hi @tmcconechy,

Please see the gif as a reference:
![24hr timepicker cell](https://user-images.githubusercontent.com/76002134/151808723-fb81a732-55f1-45d4-b27a-4f269e29784a.gif)

Do you still see 12:00 in the cell when you follow the steps in the gif?

**Comment by tmcconechy** [comment]
Ok i see. Is there any difference between this stack blitz and https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-time.html as i do see it more simply there.

My guess is something with the locale/settings not beeing. Set. Should also look at that layout issue

**Comment by awbuboltz** [comment]
Hey Tim, we're hoping to get this in for 4.61, customer issue.

**Comment by tmcconechy** [comment]
I'll see what we can do...

**Comment by s-werking** [comment]
Hi @tmcconechy ,

There are a couple more issues related to entering 12PM in datagrid cells which can be seen at https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-time.html:
1. Typing 1200 in a 12HR timepicker cell will result in a 12:00 AM entry
2. Selecting 12:00 manually on a 24HR timepicker cell will result in a 00:00 entry

Here's a gif to show these scenarios:
![Additional 12PM issues](https://user-images.githubusercontent.com/76002134/152060834-aeb33152-ac8f-4723-80e3-1a5bde8c5307.gif)

**Comment by janahintal** [comment]
QA Passed. Verified in http://localhost:4000/components/datagrid/test-timepicker-24.html
![image](https://user-images.githubusercontent.com/45757016/156349388-b6c4b012-24a4-43bf-b4e8-33377af77b52.png)

**Comment by s-werking** [comment]
Hi, after testing this a bit further I noticed an alignment issue in classic theme. Here's a gif for reference:
![Timepicker alignment](https://user-images.githubusercontent.com/76002134/156417275-74d9de59-ae31-4ba9-9348-f311c16e9f56.gif)

**Comment by janahintal** [comment]
> Hi, after testing this a bit further I noticed an alignment issue in classic theme. Here's a gif for reference: ![Timepicker alignment](https://user-images.githubusercontent.com/76002134/156417275-74d9de59-ae31-4ba9-9348-f311c16e9f56.gif)

Yeah, I noticed it too. I thought I should open another issue since it's UI issue but I'll have it fixed along with this ticket. Thanks! :)

**Comment by tmcconechy** [comment]
@tjamesallen15 can you address the very last alignment issue? Thanks

**Comment by tmcconechy** [comment]
@s-werking fixed the layout issue on this branch https://github.com/infor-design/enterprise/pull/6180

**Comment by s-werking** [comment]
Thanks @tmcconechy !

**Comment by janahintal** [comment]
QA Passed. Now working as expected. Verified in https://4610-beta0-enterprise.demo.design.infor.com/components/datagrid/test-timepicker-24.html
