### ISSUE TITLE
Datepicker: allow the removal of masking via a new option

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#6080]
**Is your feature request related to a problem or use case? Please describe.**
In the past (pre-4.51), we were able to use `$elem.data('mask').destroy();` to effectively remove the masking from datepickers. That was an acceptable solution, but now that it's broken, we'd like to have something more permanently supported.

**Describe the solution you'd like**
A new datpicker option called something like `{ "useMask": false }` that forgoes the addition of masking to the input field, allowing users to customize their own formatting.

**Describe alternatives you've considered**
One temporary solution I found with @EdwardCoyle  was to add `this.$elem.data('mask', null);` after the destroy() call, which comes after initializing a datepicker. The reason this works is because https://github.com/infor-design/enterprise/blob/7be62f518fe0322c39b73d54de9b0dae39ae808b/src/components/datepicker/datepicker.js#L552 checks specifically for `undefined`, allowing null to pass though. For some reason, the entire mask is being set back up on blur, which seems wrong altogether, that gets called here: https://github.com/infor-design/enterprise/blob/ed3870cddaa18092f179c698e7899891273bd01b/src/components/datepicker/datepicker.js#L287 which is called by `setCurrentCalendar()` after the blur.

**Additional context**
And what application do you work on? [e.g. {Infor XYZ}]
Team: Lawson
Needed by: 4.61
@EdwardCoyle  and I spent a good amount of time figuring this all out, so he's probably the guy for the job ;).

**Comment by tmcconechy** [comment]
Feel free @EdwardCoyle - but I think just a setting to not invoke the mask seems entirely appropriate

**Comment by awbuboltz** [comment]
Note, this is team: lawson

**Comment by EdwardCoyle** [comment]
@tjamesallen15 two notes:
- We should forego the temporary solution described above because...
- `this.mask();` probably shouldn't be called in `setCurrentCalendar()`, considering how often it can be called.  You might also want to look into removing that as part of the PR for this issue, but it's unclear to me what the impact of that will be on any usage of Datepicker and Monthview components.

**Comment by kaeleding** [comment]
Hi @tmcconechy, would like to ask an estimate for the 4.61 release date, since we are contemplating on applying the workaround on our end in line with our own release date.

Thanks!

**Comment by tmcconechy** [comment]
Would be march 5-10 (start of march)

**Comment by tmcconechy** [comment]
Once completed will patch in 4.60.1

**Comment by jbrcna** [comment]
this issue is now resolved.
verified in https://main-enterprise.demo.design.infor.com/components/datepicker/test-disable-mask.html
<img width="930" alt="image" src="https://user-images.githubusercontent.com/56722184/156335231-c4a15380-1dc9-46b9-82b5-3c3dcb3e7292.png">

**Comment by hsubtain** [comment]
Hi @jbrcna I would like to ask if we can include the fix in soho changes?
