### ISSUE TITLE
Tabs: 'x' icon is not aligned in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6083]
**Describe the bug**
Tabs: 'x' icon is not aligned in responsive view

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/example-enable-disable.html?theme=classic&mode=light&colors=2578a9
2. Minimize the screen to responsive view

**Expected behavior**
'x' button / icon should be aligned

**Version**
ids-4.60-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/152144181-e8508ccc-d007-4c29-ba72-2d8c178b631c.png)

**Platform**
All major browsers, OS and devices.

**Additional context**
N/A

**Comment by janahintal** [comment]
QA Failed. Tested in https://main-enterprise.demo.design.infor.com/components/tabs/example-enable-disable.html?theme=classic&mode=light&colors=2578a9
![image](https://user-images.githubusercontent.com/45757016/153198200-b7a1c3c5-8b24-4d28-828a-6b27a50f61ad.png)

**Comment by tmcconechy** [comment]
We had some issues with tests so this wasnt deployed. Please try again

**Comment by janahintal** [comment]
QA Passed. Will now move this ticket to Done. Thanks!
![image](https://user-images.githubusercontent.com/45757016/153392857-6ff38dab-c00c-49f5-b051-bc203ff3fba0.png)
