### ISSUE TITLE
Datagrid: Setting stretchColumn issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6087]
**Describe the bug**
The last column does not get stretched when the datagrid setting stretchColumn is set to "last" when using a different row height and/or safari browser

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-stretch-last-column.html
2. resize the last column to the right -> make sure you can still see it and scroll to it
3. resize the next column to it to the left -> make sure you can still scroll right and see it
4. Change row height to small or any.'

**Expected behavior**
When the stretchColumn setting is set to "last", the columns should all be their set pixel widths and the last column should fill the rest of the table if there is any width left. If the total column widths are over the table width, then all of the columns including the last should be their set pixel width.

**Version**

- ids-enterprise: v4.60.0-dev

**Screenshots**
![Large GIF (1206x632)](https://user-images.githubusercontent.com/56722184/152271611-819a494c-6717-4bd2-8f93-50d6cc16e914.gif)

**Platform**
SAfari. 

**Additional context**
the row height issue occurs in all browsers
![image](https://user-images.githubusercontent.com/56722184/152271735-e066bb61-bee4-453b-b09b-cc8c6c4c94eb.png)

**Comment by awbuboltz** [comment]
We're not seeing any issues on our side on Safari, at least not in relation to our original bug (https://github.com/infor-design/enterprise/issues/6063).

**Comment by tmcconechy** [comment]
Cant seem to reproduce this either. Will descope as i dont want to mess around more with this setting.
