### ISSUE TITLE
[iOS] Line Chart Component- Legend for Component C is not displayed

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#609]
**Describe the bug**
[iOS] Line Chart Component- Legend for Component C is not displayed

**To Reproduce**
1. Open Safari on iPhone X
2. Go to http://master-enterprise.demo.design.infor.com/components/line/example-index.html
3. Notice that the Component C is not displayed

**Expected behavior**
Component C legend should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/39101346/44110262-4343082e-9fcd-11e8-8359-304b7e32f32c.png)

**Platform**
 - iOS Mobile Devices

**Additional context**
None

**Comment by tmcconechy** [comment]
This can be fixed by updating the line chart like the column chart is so it supports different labels.

```
{
                name: 'Automotive',
                shortName: 'Auto',
                abbrName: 'A',
                value: 7,
                tooltip: 'Custom Tooltip - {{value}}'
}
```

Copy that logic in to line chart and update the example

**Comment by tmcconechy** [comment]
Added this to the sprint because it was picked up by @ericangeles.

**Comment by janahintal** [comment]
QA Passed. Moving to Done. 
Tested in: http://master-enterprise.demo.design.infor.com/components/line/example-index.html in all Devices and Browsers
