### ISSUE TITLE
Icons: Remove icon-field icons

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6091]
**Describe the bug**
Design identified some old icons (5+ years) that are redundent and shouldnt be used on https://main-enterprise.demo.design.infor.com/components/alerts/example-index.html

The ones with `icon-field` should be 

**To Reproduce**
1. Go to  https://main-enterprise.demo.design.infor.com/components/alerts/example-index.html
2. Inspect page
3. Remove ones with `field`
4. update https://main-enterprise.demo.design.infor.com/components/input/example-info.html to use `icon-info` 

**Expected behavior**
Remove `icon-field`

**Comment by tmcconechy** [comment]
"info-field" -> should use #icon-info
"info-field-solid"-> should use #icon-info-alert
"info-field-alert" -> should use #icon-info-alert

**Comment by kevinwhitedesign** [comment]
@tmcconechy anything we have to do here?

**Comment by tmcconechy** [comment]
Did you publish a fix in the icons? If so then i have to release it and all that so on me if done and published?

**Comment by kevinwhitedesign** [comment]
@tmcconechy published

**Comment by jbrcna** [comment]
This has been QA tested and passed on 
https://main-enterprise.demo.design.infor.com/components/icons/example-index.html
