### ISSUE TITLE
Tag names not rendered inside a tooltip component

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#6092]
**Describe the bug**
https://teams.microsoft.com/l/message/19:6d4c9079385840c0bc61e55bcdd16a33@thread.skype/1643907555524?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1643907555524&teamName=IDS%20Enterprise%20Development&channelName=Problems&createdTime=1643907555524

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-enterprise-4590?file=index.html

**Expected behavior**
Tag content should be visible

**Version**
- ids-enterprise-ng: 13.0.3

Issue is probably following line
https://github.com/infor-design/enterprise/blob/main/src/components/tooltip/tooltip.js#L575

**Comment by janahintal** [comment]
QA Passed.
