### ISSUE TITLE
Dropdown: Misaligned input in classic theme on Firefox

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6096]
**Describe the bug**
This misalignment is seen for this circumstance:
- In Firefox browser
- Short field
- Classic theme is used
- Dropdown is right-aligned

**To Reproduce**
1. Go to [misaligned-right-align-dropdown.zip](https://github.com/infor-design/enterprise/files/8005986/misaligned-right-align-dropdown.zip)
See that the text in the dropdown is not aligned correctly.

**Expected behavior**
It is expected that the input text is shown on the left of the dropdown trigger button.

**Version**
- ids-enterprise: v.4.60.0-dev

**Screenshots**
![Misaligned dropdown text](https://user-images.githubusercontent.com/76002134/152597343-0c4a4f46-c958-4da7-9da8-5b8b1775b608.PNG)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows10
 - Browser Name: firefox
 - Browser Version: Version 97.0
Related Lawson JIRA Ticket: [LSF-50815](https://jira.lawson.com/browse/LSF-50815)

**Comment by tmcconechy** [comment]
Lets add a visual test for this as well please.

**Comment by tmcconechy** [comment]
Once we figure this out will patch in a 4.60.1

**Comment by davidcarlsonberg** [comment]
I am unable to reproduce this with Browserstack:
<img width="1203" alt="Screen Shot 2022-03-01 at 7 38 08 PM" src="https://user-images.githubusercontent.com/7952168/156272518-7cbf854c-536e-4083-8b39-76029d2c3a99.png">

**Comment by s-werking** [comment]
Hi @davidcarlsonberg, it looks like you are in the new theme in the screenshot. This issue only happens in the classic theme.

**Comment by s-werking** [comment]
Hi @tmcconechy,

So you don't see the misalignment of the input when you select an option?
![image](https://user-images.githubusercontent.com/76002134/156379016-93bcc0db-1a69-4590-bec3-21acedb4ba6c.png)

**Comment by tmcconechy** [comment]
No also your screen shot is "new theme"

After Selecting (Closed)
![Screen Shot 2022-03-02 at 9 23 41 AM](https://user-images.githubusercontent.com/814283/156380163-2dffb532-e307-4d8e-bc88-8c166d8c58d3.png)
![Screen Shot 2022-03-02 at 9 23 34 AM](https://user-images.githubusercontent.com/814283/156380165-a4c7db9f-83e9-4194-9456-07d739c0443f.png)

Open
![Screen Shot 2022-03-02 at 9 24 42 AM](https://user-images.githubusercontent.com/814283/156380310-0b8c5a10-b085-4dbe-8378-e6a9fcf321fe.png)
![Screen Shot 2022-03-02 at 9 24 34 AM](https://user-images.githubusercontent.com/814283/156380313-c4ffff59-814a-4db1-a115-2b7368721980.png)

@davidcarlsonberg can fix this up tho but we need to be careful not to move it too far to the left or it will mean you can select less digits

**Comment by tmcconechy** [comment]
Sorry i was in chrome 👎🏻  Well i guess we should adjust both cases @davidcarlsonberg .. clean it up

**Comment by jbrcna** [comment]
this is working as expected. moving this ticket to done. thanks
https://main-enterprise.demo.design.infor.com/components/dropdown/test-field-short.html?theme=classic&mode=light
