### ISSUE TITLE
Font size for empty UI is too big in the uplift theme

### ISSUE THREAD

**Issue by evikstrom** [infor-design/enterprise#6099]
**Describe the bug**
The font size for the empty UI in widgets differ between the classic and the new uplift theme. The size of the font is too big in the uplift theme.

**To Reproduce**

1. Add "Menu" widget to a page
2. The css class empty-title is bigger and more bold in the new uplift theme. Adding screenshots below to showcase the difference between the two themes.

**Expected behavior**
In the uplift theme, the empty-title easily becomes a bit messy and overcrowded due to changes in font size. It should be comparable to the size of the title in the classic theme. 

**Version**

- ids-enterprise: v4.59.2

**Screenshots**
"Item Creation" widget in classic theme vs new uplift theme
![item-creation-portalv1](https://user-images.githubusercontent.com/79518918/152833630-1e3a107a-c8c7-464f-beee-f54ba96d6de6.png)
![item-creation-portalv2](https://user-images.githubusercontent.com/79518918/152833659-0796b1ba-0c39-4e22-8400-5c3a08e1e34d.png)

"Menu" widget in classic theme vs new uplift theme
![image](https://user-images.githubusercontent.com/79518918/152833946-27747b9c-f8d3-470b-8a98-d67536b41fb9.png)
![image](https://user-images.githubusercontent.com/79518918/152833990-cb83bb8b-c389-486d-ab01-d164e62b7d97.png)

**Platform**
 - Infor Application/Team Name: Infor Homepages
 - OS Version: Windows 10
 - Browser Name: Google Chrome
 - Browser Version: 97.0.4692.99 (Official Build) (64-bit)

**Additional context**
Since we do not want any custom styling, we would appriciate if this could be handled by the IDS design team. Note: this is only regarding the font size of the empty UI.

**Comment by kevinwhitedesign** [comment]
@evikstrom You need a title here for what's happening for the user's quick awareness. For example "No Items Yet" might work as a title, and then description could be underneath that. Looping in our UX writer for some additional recommendations here.

**Comment by tmcconechy** [comment]
@kevinwhitedesign since the beginning of coding this one i also sort of felt it was too big. What about lowering the emphasis of it maybe making the icon a bit smaller and both texts 2px smaller?

**Comment by tmcconechy** [comment]
@evikstrom still discussing the change here but one thing we noticed is your fonts dont seem the same as the example. https://main-enterprise.demo.design.infor.com/components/emptymessage/example-widgets.html

I wonder if maybe your missing the new font and falling back to Arial. To get this then add

```
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600&amp;display=swap" rel="stylesheet">
```

to the head tag

<img width="783" alt="Screen Shot 2022-02-14 at 9 10 00 AM" src="https://user-images.githubusercontent.com/814283/153879948-1e2e0c35-30bf-461b-841e-5aca075945f3.png">

**Comment by evikstrom** [comment]
Hi @tmcconechy. Perhaps that is the issue. I will check this with the team and I will get back to you as soon as possible. Thank you for letting me know.

Kind regards,
Emma Vikström

**Comment by tmcconechy** [comment]
It will definitely help 👍🏻 But i think we may reduce the padding/margin and icon size as well

**Comment by evikstrom** [comment]
Okay, thanks for letting me know. I have forwarded this to the team :)

**Comment by kevinwhitedesign** [comment]
@evikstrom also here's an example I made showing the two overlapping. Our code example versus the screenshots you sent. A few things about the examples looked larger than what we have in code

- empty state graphic looks a bit larger on your end
- title style text
- body style text
- the button & text looked larger

![overlapping-widgets](https://user-images.githubusercontent.com/6478704/154549646-97e3489e-20a4-47a0-91b8-c777322601fc.png)

**Comment by evikstrom** [comment]
Hi @kevinwhitedesign,
I'm sorry for a late response. I did forward this feedback to the team february 18th. It looked like we had some custom styling and when it were removed it looked better.

Kind regards,
Emma Vikström

**Comment by kevinwhitedesign** [comment]
@evikstrom thank you! I'll update my team too

**Comment by kevinwhitedesign** [comment]
@tmcconechy design can take a look, backlog and get back I think there's opportunity for fine tuning spacing.

**Comment by tmcconechy** [comment]
great once we have that just a note we should adjust both the new: https://main.wc.design.infor.com/ids-empty-message/ and old ones to the spec.

**Comment by tmcconechy** [comment]
closing i think we solved this with the fonts
