### ISSUE TITLE
[iOS] Radar Component- Some labels are cropped on mobile devices

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#610]
**Describe the bug**
[iOS] Radar Component- Some labels are cropped on mobile devices

**To Reproduce**
1. Open Safari/Google Chrome on iPhone X or iPhone 8
2. Go to http://master-enterprise.demo.design.infor.com/components/radar/example-index.html
3. Notice that some labels are cropped

**Expected behavior**
Labels should not be cropped out

**Screenshots**

![image](https://user-images.githubusercontent.com/39101346/44110441-afb66ffa-9fcd-11e8-8cb3-7acdb463d018.png)
**Platform**
 - iOS Mobile Devices 

**Additional context**
None

**Comment by tmcconechy** [comment]
This was a duplicate issue of https://github.com/infor-design/enterprise/pull/1849
