### ISSUE TITLE
Tooltip: maxWidth setting has no effect.

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#6100]
**Describe the bug**
https://teams.microsoft.com/l/message/19:6d4c9079385840c0bc61e55bcdd16a33@thread.skype/1644251833655?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1644251833655&teamName=IDS%20Enterprise%20Development&channelName=Problems&createdTime=1644251833655

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-enterprise-4590-buhs89?file=index.html

**Expected behavior**
Tooltip popover should be 100px wide

**Version**
- ids-enterprise-ng: main

**Comment by tmcconechy** [comment]
I see the setting in tooltip.js but its not being applied in any way

**Comment by guoliang** [comment]
> I see the setting in tooltip.js but its not being applied in any way

Thought I saved the changes. It should be saved now.

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/popover/example-using-max-width-setting
![image](https://user-images.githubusercontent.com/45757016/159239056-b59a8ebe-690d-48f3-8206-b1c9c17c0bb5.png)
