### ISSUE TITLE
Donut: Misplaced center tooltip on multiple donut charts

### ISSUE THREAD

**Issue by ktfields** [infor-design/enterprise#6103]
**Describe the bug**
Donut: Misplaced center tooltip on multiple donut charts

**To Reproduce**

1. Go to https://jsfiddle.net/ktfields117/Lgbpy3qv/2/
2. Hover over the center label of the first donut chart
3. Observe the tooltip
Actual result: Tooltip appears on the 2nd donut chart

**Expected behavior**
The tooltip should appear on the 1st donut chart

**Version**

- ids-enterprise: 4.60.0-dev

**Screenshots**
![misplaced_centerTooltip1](https://user-images.githubusercontent.com/39935379/152967881-1c7984f3-a566-4eb4-9d2a-121a989f4164.gif)

**Platform**
- Infor Application/Team Name: Lawson System Foundation (Portal)
- Browser Name: Google Chrome
- Browser Version: 98.0.4758.81

**Comment by awbuboltz** [comment]
Hey Tim, this is the Lawson team.
