### ISSUE TITLE
Time picker: value changes after changing the period to AM/PM via tab. 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6104]
**Describe the bug**
Time picker: value changes after changing the period to AM/PM via tab. 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html
2. Open the datepicker
3. Using keyboard, choose 12 for hours
4. Tab and choose 30 for minutes via keyboard
5. Tab and choose PM 
6. Tick set time

**Expected behavior**
The time should not change to 12:30 PM

**Version**
4.60-IDS-DEV

**Screenshots**
N/A

**Platform**
Windows 10 Chrome

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Did you mean it turns to 1:30? Thats what i see and i think this is a duplicate of https://github.com/infor-design/enterprise/issues/6049

**Comment by janahintal** [comment]
QA Passed. Now working as expected in https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html. Thanks!
