### ISSUE TITLE
Unit Testing: Research on visual regression tests for Puppeteer

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#6105]
**Describe the Issue**

Research on visual regression tests that will replace the protractor and eventually it will be our way of testing visuals.

**What are you trying to do**

Transitioning to puppeteer tests to eliminate the use of the protractor (deprecated) for visual testing which includes docker for generating and updating the baseline images.

**What did you try so far**

Still using the protractor in the meantime.

**Additional  Context**

- Considering Percy but need to sort out the costs/licenses
- Looking at the puppeteer jest image snapshots

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to Done column.
