### ISSUE TITLE
Column Chart: Grouped-bars float having axis labels

### ISSUE THREAD

**Issue by ryanChrstn** [infor-design/enterprise#6109]
**Describe the bug**
Having axis labels on a column-grouped chart that has a large value makes the bars float.

**To Reproduce**

Create a column-group chart, enable the axis labels.
The data should have a large value.

**Expected behavior**
All bars should stay on the line. The same bars without the axis labels.
<img width="349" alt="image" src="https://user-images.githubusercontent.com/14357059/153178453-3e46b7e4-89b1-483d-ba7b-cb6f560236b8.png">

**Version**

- ids-enterprise: 4.60-dev

**Screenshots**
Bars below million are floating.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/14357059/153177995-d354e227-9d79-4960-aeda-197cba9c72bd.png">

**Platform**
 - Infor Application/Team Name: Lawson System Foundation (LSF)
 - OS Version: [e.g. Windows 10 ]
 - Browser Name: Chrome, Firefox, Edge
 - Browser Version: Version 97.0.4692.99 (Official Build) (64-bit), 97.0 (64-bit), Version 98.0.1108.43 (Official build) (64-bit)

**Additional context**
Sample code replicating the issue.
https://jsfiddle.net/pn4swk6a/

Left axis labels also overlap with the Y-axis label.

**Comment by tmcconechy** [comment]
Maybe related to https://github.com/infor-design/enterprise/issues/5911

**Comment by ryanChrstn** [comment]
Thanks for the update. The issue in https://github.com/infor-design/enterprise/issues/5911 has been resolved on our end.
Just to add, the issue seems to happen only when the axis labels were added.

**Comment by tmcconechy** [comment]
ok, thanks for clarifying we will take a look when we can

**Comment by s-werking** [comment]
Hey @tmcconechy, since this is finished earlier than expected, could this ticket also be included in our 4.60.1 patch? I believe including this one would make it 9 tickets now.

**Comment by janahintal** [comment]
Passed QA. Verified in https://4610-beta0-enterprise.demo.design.infor.com/components/column-grouped/test-column-grouped.html?theme=classic&mode=contrast&colors=133c59
![image](https://user-images.githubusercontent.com/45757016/157431656-bc96e255-cf96-4bf8-a853-49cfa4d48780.png)
