### ISSUE TITLE
[iOS] Sign in Component-Misalignment on "Required" Error messages

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#611]
**Describe the bug**
[iOS] Sign in Component-Misalignment on "Required" Error messages

**To Reproduce**
1. Open any browser on iOS devices including iPad
2. Go to http://master-enterprise.demo.design.infor.com/components/signin/example-index.html
3. Leave all the input fields blank
4. Click Sign in Button
5. Notice the misalignment on the "Required" error messages

**Expected behavior**
The error icons should be properly aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/39101346/44114111-33ea08fe-9fd8-11e8-9e66-3f84469c4266.png)

**Platform**
 - All Mobile Devices 
 

**Additional context**
None

**Comment by tmcconechy** [comment]
This one would be a good one to look into @ericangeles ... Seems like it did it in 4.9.0.
Have a look at this one next when you can.
