### ISSUE TITLE
Tabs: Pressing tab to move focus onto tabs causes blank space to be focused (Firefox)

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6110]
**Describe the bug**
Pressing tab to focus the active tab focuses blank space on the right side of the tabs instead. This only happens when in Firefox browser.

**To Reproduce**
1. Go to (https://main-enterprise.demo.design.infor.com/components/tabs/example-index.html)
2. Press tab to focus the tabs
3. See that the blank space at the end of the tabs receives focus

**Expected behavior**
It is expected that the active tab receives focus upon tabbing to the tabs.

**Version**
- ids-enterprise: v4.60.0-dev

**Screenshots**
Tabbing sequence in Chrome:
![Chrome tabbing to focus tabs](https://user-images.githubusercontent.com/76002134/153219604-b7047d69-265b-4429-9e33-63b689ae0405.gif)

Tabbing sequence in Firefox:
![Firefox tabbing to focus tabs](https://user-images.githubusercontent.com/76002134/153219670-00545acd-8e34-4d35-ba0b-7f7f710f78b1.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 10
 - Browser Name: firefox
 - Browser Version: 97.0 (32-bit)
Related Lawson JIRA Ticket: [LSF-50915](https://jira.lawson.com/browse/LSF-50915)

**Comment by tmcconechy** [comment]
What hmm. Wierd one

**Comment by tmcconechy** [comment]
Once done will patch this in 4.60.1

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
