### ISSUE TITLE
Editor: Retains red color border when Soho-Alert status/message is changed. 

### ISSUE THREAD

**Issue by NarraVivek** [infor-design/enterprise#6111]
**Describe the bug**
The Rich text Editor(soho-editor) retains the red color border even if the soho-alert status/message is changed back to success or removed entirely. 

**To Reproduce**

Using the soho-alert component, `addInlineMessage('Error Message', 'error')` to the editor component(soho-editor) and `removeAllMessages()`.

**Good to have before reproducing this issue:**

1. Having the enterprise-ng repository from IDS cloned in your local system.
2. Running the application locally to add new elements in the Alert component of enterprise-ng .

**Steps to reproduce the behavior:**
1. Go to 'http://localhost:4200/ids-enterprise-ng-demo/alert' (Running the enterprise-ng on your local environment) or open something similar like https://main-enterprise.demo.design.infor.com/components/validation/test-all-field-types.html
![image](https://user-images.githubusercontent.com/49568511/153254165-376060d6-d587-4128-a8e7-ffa36dd03709.png)

2. Add the below code which should add a Rich text editor in the enterprise-ng\src\app\alert\alert.demo.html
`<div class="field">
        <div
          soho-editor
          soho-alert
          id="Test-editor"
          role="textbox"
          aria-multiline="true"
          [innerHtml]=""
        >
        </div>`
3. Adding the soho-alert to the soho-editor component should look something like from the above.
![image](https://user-images.githubusercontent.com/49568511/153254454-d3ef7cb3-7b22-4249-8145-0a3773fcc3fc.png)
4. Now, try to click on "Add Inline Message" of type "Error"
![image](https://user-images.githubusercontent.com/49568511/153257806-0154f75b-203d-4ca9-8ffb-f1b926586b2e.png)
5. Observe how the red border is added to the Editor in both HTML mode and VISUAL mode. 

 In HTML mode: Observe how the red border is only applied to the toolbar.
![image](https://user-images.githubusercontent.com/49568511/153258072-1991b386-5fcf-4f0a-8df7-56750f5abbbc.png)

 In VISUAL mode: Observe how the red border is applied to the whole editor. 
![image](https://user-images.githubusercontent.com/49568511/153258184-d5a4f051-5ca0-483b-bf1d-59f4058da799.png)

6. Now click on "Remove Message" or "Clear All Messages". 
7. Observe how the red border is still retained after the inline message disappears. 
![image](https://user-images.githubusercontent.com/49568511/153258362-38be93d4-9388-496a-979e-b187985345d3.png)

**Expected behavior**
The Red border should be removed/disappear when the alert is removed programmatically. This is also apply for any other border color. (Green-border for Success alert, Red-border for Error alert).

**Version**

- ids-enterprise: v4.60.0
- ids-enterprise-ng: v10.1.0

**Screenshots**
Reproducing the issue in Video:
![HTML Editor persists REd border](https://user-images.githubusercontent.com/49568511/153258474-417e00af-ffb5-403a-9626-7565302a6dde.gif)

**Platform**
 - Infor Application/Team Name: Infor PIM
- OS Version: Windows 10
- Browser Name: chrome

**Comment by tmcconechy** [comment]
I think the issue is that we never supported editor for this example. We will have to add it. But calling it a bug vs a feature

**Comment by tmcconechy** [comment]
Closing stale issues
