### ISSUE TITLE
Legends of Donut chart are overlapping with Legend color when legends placed at bottom.

### ISSUE THREAD

**Issue by bveerabathini** [infor-design/enterprise#6113]
**Describe the bug**
Legends of Donut chart are overlapping with Legend color when legends placed at bottom. This issue is reproduced when window is resized/responsive.

**To Reproduce**
Kept code in stackblitz ,here is the url.
https://stackblitz.com/edit/ids-quick-start-1301-dn2uzm?file=src%2Fapp%2Fapp.component.html

**Expected behavior**
Legends should not overlap with legend color.

**Version**

- ids-enterprise: v4.58.3

**Screenshots**
<img width="374" alt="image" src="https://user-images.githubusercontent.com/85981034/153347008-56d8f609-e738-4aaa-82d4-ecefb78cf136.png">

**Platform**
 - Infor LN
 - OS Version: Windows 10
 - Browser Name: chrome
 - Browser Version: Version 98.0.4758.82 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Test this in both new and classic theme

**Comment by tmcconechy** [comment]
<img width="391" alt="Screen Shot 2022-02-23 at 12 30 41 PM" src="https://user-images.githubusercontent.com/814283/155374146-8997df36-f2b8-4f0b-8e99-2d6fd7f0b48d.png">

Should wrap like this (uses flex)

**Comment by davidcarlsonberg** [comment]
Can we just change the display on the parent item to `inline-flex`?

**Comment by tmcconechy** [comment]
Yes possibly - that could be the solution.. (might need a bit more)
