### ISSUE TITLE
Sink Page: Multiselect font issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6114]
**Describe the bug**
The fonts in multiselect looks bold

**To Reproduce**
1. Go to https://4600-beta1-enterprise.demo.design.infor.com/components/multiselect
2. Look at the tags
3. See error

**Expected behavior**
font should not be bold

**Version**

- ids-enterprise: v4.60.0-beta1

**Screenshots**
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/56722184/153352094-feb835ab-9d81-42be-ac31-ff105a774c49.png">

**Platform**
all

**Additional context**

**Comment by kevinwhitedesign** [comment]
The bold style was done to be able to pass AA contrast correct me if I'm wrong @elizabethhartley
