### ISSUE TITLE
Locale: Incorrect / incomplete date format for Latvian. A dot is required at the end

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#6123]
Locale: Incorrect / incomplete date format for Latvian. A dot is required at the end

![image](https://user-images.githubusercontent.com/66057969/153901277-0d23a5a9-cc1a-4f1f-8018-e9dfcda7589e.png)

**Comment by tmcconechy** [comment]
Missing here https://github.com/infor-design/enterprise/blob/main/src/components/locale/cultures/lv-LV.js#L16 but need to confirm it works in formatDate and that we have a unit test

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/locale/test-format-date.html
![image](https://user-images.githubusercontent.com/45757016/168794914-395e9e1e-daf4-4305-85da-45ec2c4188a3.png)
