### ISSUE TITLE
Enhance Navigation Menu API Breakpoint Setting to Control Menu Overlay vs Push

### ISSUE THREAD

**Issue by anton-kurilov** [infor-design/enterprise#6127]
**Is your feature request related to a problem or use case? Please describe.**
Goal is to have the overlapping menu on devices larger than 768, specifically tablets (tablet-to-desktop breakpoint)

![image](https://user-images.githubusercontent.com/14839675/154337891-38694e67-9e8a-41f9-9150-32184a80c2b2.png)
This ^ Instead of:
![image](https://user-images.githubusercontent.com/14839675/154337939-aa6c0abe-67b6-4ccc-82b1-18e1ea65e0c9.png)

Images from:  https://stackblitz.com/edit/ids-quick-start-1311-yvuujo?file=src%2Fapp%2Fapp.component.html 

**Describe the solution you'd like**
Remove the hardcoded media query which is at phone-to-tablet https://github.com/infor-design/enterprise/blob/main/src/components/applicationmenu/_applicationmenu.scss#L658 and have it respect the breakpoint passed to settings via the api.

**Describe alternatives you've considered**
None really available the decision comes down to if we allow custom breakpoints via the api or if we have use the hardcoded one linked in the scss above.

**Additional context**
Had a Teams chat with Ed and Tim, can provide a link as needed for more context. Thanks!

**Comment by anton-kurilov** [comment]
@tmcconechy, another stale issue, maybe this one if not as relevant with the new styling in 4.8? We can probably close this one, although not sure @LilBiggs if wfm still has a want for this?

**Comment by tmcconechy** [comment]
Ok, yeah i have a Robot closing out issues older than a year. So will close. This but if anyone needs it let me know.

I think ultimately the menu will be replaced with https://github.com/infor-design/enterprise-wc/issues/916 if you cant see the design its a side bar. That opens up in three stages. So it can open bigger or smaller. Probably replaces the entire idea here.

**Comment by LilBiggs** [comment]
I'll follow up with our BA, we still have an open ticket on our side for this.
