### ISSUE TITLE
Datagrid: Enable tooltips for disabled rows

### ISSUE THREAD

**Issue by lynzleb** [infor-design/enterprise#6128]
**Is your feature request related to a problem or use case? Please describe.**
The tooltip is not appearing for a disabled row even when the related settings have been set.

**Describe the solution you'd like**
Tooltips to appear on disabled rows. Please see screenshot.
![image](https://user-images.githubusercontent.com/83392536/154407378-e1c5832f-8dee-41d9-8104-055145a8c6f1.png)

**Describe alternatives you've considered**
Was thinking if it will work if I disabled on cell level but it doesn't seem possible. 

**Additional context**
Infor SalesHub

**Comment by tmcconechy** [comment]
@lynzleb Can you elaborate on the code you added to put this in place? Also curious about it because in the screen shot i do see the tooltip. So maybe need the steps/code to set this up so we see what you are seeing?

**Comment by tmcconechy** [comment]
@lynzleb can you add the code to reproduce this? Thanks

**Comment by lynzleb** [comment]
Hi Tim, sorry I missed the earlier comment. The screenshot was provided by our BA as desired output so it's not a working code. 

Code is here https://stackblitz.com/edit/ids-quick-start-nhzdc3

I've added enableTooltips = true in datagrid and tooltip with callback and regular string for each column. Neither works for disabled rows, ideally we will use the one with the callback.

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-tooltip-disabled-rows.html
