### ISSUE TITLE
Text Inputs:  'is-disabled' class is being added to field labels

### ISSUE THREAD

**Issue by jvang01** [infor-design/enterprise#6131]
**Describe the bug**
The function below in components/form/form.js is disabling our text input labels when it shouldn't be.  
```
// Adds css class 'is-disabled' to field if input has disabled attribute
// Gray color should apply to label if input is disabled
$(() => {
  const elements = $('input[type="text"]');

  if (elements.length) {
    elements.each(function () {
      if ($(this).is(':disabled')) {
        $(this)
          .closest('.field')
          .addClass('is-disabled');
      }
    });
  }
});
```

**Screenshots**
![image](https://user-images.githubusercontent.com/64548726/154543695-30174dec-63a5-4833-8568-44b66ba6504f.png)

**Platform**
 - Infor Application/Team Name: LAWSON

**Additional context**
Per our conversation on 2/17/22 - we agreed that it should be removed.

**Comment by tmcconechy** [comment]
Once we figure this out will patch in a 4.60.1

**Comment by jbrcna** [comment]
Hello @tmcconechy , upon testing the steps on the PR it is working as expected. However, the label fields are still disabled. I'd like to clarify if that is the desired output or am I missing something? 
https://main-enterprise.demo.design.infor.com/components/modal/test-focusable-elements.html
<img width="454" alt="image" src="https://user-images.githubusercontent.com/56722184/155081295-8d7ddaa3-61bc-480d-8824-d99735cc6ce0.png">

**Comment by tmcconechy** [comment]
@jbrcna yeah i pushed a minor fix that the first field isnt disable so the label shouldnt be. It just has no tab order. Otherwise the rest is correct..

**Comment by jbrcna** [comment]
thank you @tmcconechy , this is now working as expected. will move this ticket to done.
<img width="485" alt="image" src="https://user-images.githubusercontent.com/56722184/155468534-980eebe8-0a4c-4a46-ad3a-3acc1d999b6a.png">
