### ISSUE TITLE
Hierarchy - Need a way to dynamically update actions in leaf action menu

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#614]
**Describe the solution you'd like**
Hierarchy control needs a way to allow actions in action menu to be updated dynamically. Some actions may not be available until a certain leaf is selected.

![menu](https://user-images.githubusercontent.com/1056684/44151116-3018ee68-a067-11e8-975b-5b990b865c1d.png)

**Comment by tmcconechy** [comment]
This fix was merged
