### ISSUE TITLE
Icons: Add new mobile icon

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6144]
**Describe the bug**
Add new design system release with a new icon for mobile.

**Task**
- new mobile icon (phone)

**Additional context**
https://jira.infor.com/browse/UXD-3976

**Comment by tmcconechy** [comment]
waiting on @corpulent to see why the release build isnt working

**Comment by jbrcna** [comment]
This has been QA tested and passed on v4.61.0-beta.
https://4610-beta0-enterprise.demo.design.infor.com/components/listview/example-footer-navigation.html
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/56722184/157389021-68825747-d457-494a-b390-1ae6d3a2dd72.png">

https://4610-beta0-enterprise.demo.design.infor.com/components/icons/example-index.html
<img width="79" alt="image" src="https://user-images.githubusercontent.com/56722184/157387732-1fa3ed58-5f06-4ca2-a709-f4582f9da4ae.png">
<img width="112" alt="image" src="https://user-images.githubusercontent.com/56722184/157388410-473fca0a-651b-4a13-bf86-9fa525a63253.png">
