### ISSUE TITLE
Lookup: Input label stays disabled when enable API is called on Lookup.

### ISSUE THREAD

**Issue by LilBiggs** [infor-design/enterprise#6145]
``**Describe the bug**
Utilizing as soho-label with a soho-lookup when inside of a `<div class="field">` does not enable the soho-label correctly after disabling, then re-enabling the soho-lookup. This happens when the .field is not the first parent of the soho-lookup. 

```
<div class="field">
  <field-chooser>
    <label soho-label>Test</label>
    <input soho-lookup>
 </field-chooser>
</div>
```

**To Reproduce**
https://stackblitz.com/edit/ids-quick-start-1311-ipgosj?file=src/app/app.component.html

1. Navigate to url above.
2. Notice the Label and Lookup are disabled.
3. After 3 seconds the Lookup will become enabled. However the label will stay disabled.

**Expected behavior**
The Label and Lookup should stay in sync with disabling then re-enabling.

**Version**
4.60.0

**Screenshots**
![image](https://user-images.githubusercontent.com/6730716/155585310-43278c35-6dd2-4ea2-a09c-3f9c9a209550.png)

**Platform**
 - Infor Application/Team Name: Infor WFM

**Additional context**
There is a small inconsistency in lookup.js enable(). enable is using .parent() instead of .closest('.field') like disable is using. I will produce a Pull Request shortly.

**Comment by tmcconechy** [comment]
This might be because of https://github.com/infor-design/enterprise/pull/6132 ? Maybe not tho..

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
