### ISSUE TITLE
RenderLoop: Memory Leak / Gradual Increase

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#6153]
We have discovered what looks like a memory leak in IDS. 

Our production version is 4.56.0 but even after upgrading to 4.60.0, we see the same issue. We are reproducing using Chrome at latest version. The videos below were created using IDS 4.60.0.

In most cases, it doesn't cause a problem, but this has been reported to us by ICS on behalf of a Infor customer that has a large data set which is then crashing one of our interfaces.

Here is a recording of the issue https://watch.screencastify.com/v/XcCdqunYNUUe2SYr6pzz - the interface loads an XML file, converts it to HTML elements, then applies the IDS "tree" control to the elements (around 1min 36secs into the video), then you can see in task manager that after rendering the tree there is a constant CPU use and memory goes up and down, dependant on Garbage Collector, but eventually runs out around 4GB and crashes. Once the XML has been converted to HTML elements by our UI code, no more activity is performed.

However I do not believe it is this tree that is the problem as using the browser performance monitor on a smaller data set I could see that code in the RenderLoop API was being called over and over and consuming at least CPU and JS Heap memory.

To test my theory, I added the following to disable the RenderLoop from running before loading sohoxi.js...

`<script>window.SohoConfig = { renderLoop: { noAutoStart: true}};</script>`

...and no other change, and then made a recording of loading the same data set https://watch.screencastify.com/v/PfYRhescTbKeWyv0n28q as you can see, the same memory increase does not occur and at no point does the browser crash.

I'm not 100% ruling out the issue isn't related to our application code, but as we don't intentionally initiate or access this RenderLoop object, I wanted your input as to why disabling it appears to resolve the issue.

Can someone investigate this area of IDS to see why being enabled causes the memory to go up so rapidly when there are a large number of interactive elements on the page?

Also, as a short term fix, if we were to apply the SohoConfig override above to the entire product, what impact would it have on other IDS pages within our product (e.g. would certain elements or controls stop working)?

**Comment by tmcconechy** [comment]
@EdwardCoyle what do you think initially? It might be nice to be able to provide some test for this but not sure how that would even look.

**Comment by tmcconechy** [comment]
I took a look at the example provided offline but im seeing sort of different findings..

- if the `window.SohoConfig = { renderLoop: { noAutoStart: true}};` is on a cant get a heap snap shot at all without it crashing
- if the `// window.SohoConfig = { renderLoop: { noAutoStart: true}};` I do get a heap measurement and its using a lot of memory. 

It has to be the tree - the renderloop is always running but it needs to (its the requestAnimationFrame) - i don't see many components that use the renderLoop timeouts in it.

Maybe a solution is to add a pager at the bottom of the tree and only show "page-number" of items and reload the tree each time.. https://main-enterprise.demo.design.infor.com/components/pager/example-standalone.html

Or could try something like this https://main-enterprise.demo.design.infor.com/components/listview/example-footer-navigation.html

Im not really sure...But some initial thoughts

**Comment by tmcconechy** [comment]
Took a deeper look. Its hard to reproduce the same way on mac but it does happen for me after 10 minutes or so.
To understand what we are doing its basically this https://javascript.plainenglish.io/better-understanding-of-timers-in-javascript-settimeout-vs-requestanimationframe-bf7f99b9ff9b

If you disable that line it turns off all the places that might use this in replacement of a setTimeout. The loop is doing very little really but i think in this case the sheer number of DOM elements combined with it causes the issue.

Will work with @EdwardCoyle and see if either
a) we just go back to setTimeout
b) maybe we can stop and start the loop in register and unregister as in this case the loop is running but nothing uses

But if you do turn it off the following will be lacking/stop working

<img width="470" alt="Screen Shot 2022-03-04 at 11 56 26 AM" src="https://user-images.githubusercontent.com/814283/156806145-59b87320-4ae1-4f9d-b740-5aac401bee94.png">

- any long press
- breadcrumb (truncation)
- dropdown (keyboard typeahead)
- modal (some events in opening/closing)
- popdown (some events in opening/closing)
- search (some events in expanding/resize)
- tabs (afteractivated event)
- toast (open/close)
- tooltip (probably wont show at all)

I think from a UX standpoint its pretty slow loading so you might want to do this https://main-enterprise.demo.design.infor.com/components/tree/example-ajax.html

This could solve the issue but we might want to re-evaluate the use of this...

**Comment by tmcconechy** [comment]
Closing stale issues - maybe for this one go to the web component version which has no more renderloop
