### ISSUE TITLE
Cards - Memory leak with resize.card event

### ISSUE THREAD

**Issue by LilBiggs** [infor-design/enterprise#6155]
**Describe the bug**
When destroying the soho-card, the body.resize.card event is not being removed. This is causing the soho-card to stay in memory and increase both the JS heap size and JS Event Listener Count.

**To Reproduce**
https://stackblitz.com/edit/ids-quick-start-1311-de8hmk?file=src%2Fapp%2Fapp.component.html

1. Navigate to stackblitz link above.
2. Open Chrome Dev Tools
3. Show performance monitor
4. Click on the Reload Button a couple times. Notice JS Heap Size and JS Event Listeners goes up drastically with each click.
5. Navigate to Elements Tab in Dev Tools
6. Click on `<body>` and navigate to Event Listeners in Dev Tools.
7. Expand Resize, notice the thousands of event listeners hanging around.
This can also be seen via a Heap Snapshot.

**Expected behavior**
No memory leak while utilizing soho-cards

**Version**
- ids-enterprise: v4.60.0

**Screenshots**
First Load
![image](https://user-images.githubusercontent.com/6730716/156211531-dbe570f7-f516-4987-8e80-275ad2a4fc7b.png)

Tenth Load.
![image](https://user-images.githubusercontent.com/6730716/156211639-6f06d9d0-d056-47a6-b32b-27b3e9bc5c5b.png)

**Platform**
 - Infor Application/Team Name: WFM

JS Heap size depends greatly on what is inside of the card. The stackblitz above doesn't have alot of content so Heap is not as bad.

**Comment by tmcconechy** [comment]
Think i see the problem.. Will PR shortly

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
