### ISSUE TITLE
Icons: Inconsistency between solid and outlined icons

### ISSUE THREAD

**Issue by ReniVarghese** [infor-design/enterprise#6165]
**Describe the bug**
SohoMessageService displays the hollow icons for error and alert. Can't modify these icons.

**To Reproduce**

1. Make use of the method SohoMessageService.error() or sohoMessageService.alert()
2. We can see a hollow error and alert icons getting displayed with outline colors of red and orange

**Expected behavior**
Need to change these icons to display the error-solid and alert-solid icons instead with filled red and orange colors

**Version**

- ids-enterprise-ng: 13.0.3

**Screenshots**
Currently SohoMessageService.error() is showing a hollow error as below:
![image](https://user-images.githubusercontent.com/88399113/156785645-d8c24623-a27b-47f7-8fb4-4a62618ec30c.png)
SohoMessageService.alert() is showing a hollow alert as below:
![image](https://user-images.githubusercontent.com/88399113/156788142-58295dd9-edd5-42bf-acce-be990dd2c6a8.png)

Would need to modify these to solid ones as below:
![image](https://user-images.githubusercontent.com/88399113/156787576-08a41f37-0b2b-4613-ae86-a4abf7db8cd5.png)
![image](https://user-images.githubusercontent.com/88399113/156787720-b98e8723-1784-49ad-a373-fe132ffdf12a.png)

**Additional context**
In order to be in sync with the other icons used in project

Some places found:
- datagrid formatters
- field validation
- search code for icon names and change
-

**Comment by kevinwhitedesign** [comment]
@tmcconechy yeah I remember. Outline is the current style, so it makes sense to stick with that throughout the design system. I'm not sure why we have solid versions in our library. We can discuss deprecating those potentially?

**Comment by tmcconechy** [comment]
Ok yeah make them all outlined it is - i think by making those changes we will deprecate them. Then after some time can maybe remove.

I think perhaps they are there because in the classic theme thats the ones that were used so the names needed to be the same. So we will have to figure that out in the code. Classic = solid New = outline

**Comment by tmcconechy** [comment]
We should check this in the web components too.

**Comment by GlenlieMaye** [comment]
QA tested and passed. Moving this ticket to Done.

https://main-enterprise.demo.design.infor.com/components/validation/test-alert-types.html
<img width="129" alt="image" src="https://user-images.githubusercontent.com/102151352/168236106-4c725f60-c8f3-4316-8df3-cc893aa1a7e6.png">

https://main-enterprise.demo.design.infor.com/components/datagrid/test-alerts.html
<img width="557" alt="image" src="https://user-images.githubusercontent.com/102151352/168236998-d684df62-37ec-4884-a14f-a4e324a9321b.png">

https://main-enterprise.demo.design.infor.com/components/tree/example-long-node-text.html
<img width="617" alt="image" src="https://user-images.githubusercontent.com/102151352/168237107-5563acb5-c896-424a-84e8-40ad46132433.png">

https://main-enterprise.demo.design.infor.com/components/tree/example-plus-minus-folders.html
<img width="111" alt="image" src="https://user-images.githubusercontent.com/102151352/168236338-a2966855-8286-4919-9c91-0c9775dfe047.png">

https://main-enterprise.demo.design.infor.com//components/calendar/example-only-calendar
<img width="689" alt="image" src="https://user-images.githubusercontent.com/102151352/168236829-3dd72576-616f-422b-aa1b-edbf77049e78.png">

https://main-enterprise.demo.design.infor.com/components/week-view/example-two-weeks
<img width="691" alt="image" src="https://user-images.githubusercontent.com/102151352/168236734-c7310a03-bc9b-4da4-9df5-85fa11519cb0.png">

https://main-enterprise.demo.design.infor.com/components/validation/example-index
<img width="236" alt="image" src="https://user-images.githubusercontent.com/102151352/168236655-9e6296a1-3a0e-4ad3-bfa5-3bf9c708646b.png">
