### ISSUE TITLE
DatePicker: Cannot clear the value of range date/timestamp

### ISSUE THREAD

**Issue by sjasaniel** [infor-design/enterprise#6168]
**Describe the bug**
Cannot clear the value of range date/timestamp.
Also, if the date passed is an Invalid Date, the value in the field becomes NaN/NaN/NaN - NaN/NaN/NaN. Not sure of this is working as designed.

**To Reproduce**
Please see sample below. Please input 02/01/2022 - 02/15/2022 then press 'Clear Field'.
https://ids-enterprise-ege91h.stackblitz.io (https://stackblitz.com/edit/ids-enterprise-ege91h?file=index.html)
Actual result: Date field is not cleared and it was replaced with the current date in range format. 
>> Input: 02/01/2022 - 02/15/2022
>> becomes: 03/05/2022 - 03/05/2022 (date at the time this report was logged)

**Expected behavior**
Date field is cleared.

**Version**
Version used in stackblitz is v4.51.0-dev.
The latest version is v4.60.0, the result is different from v4.51.0-dev but still incorrect (3/5/2022 - NaN/NaN/NaN)

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows10
 - Browser Name: Chrome 99.0.4844.51
 - Browser Version: 99.0.4844.51 (Official Build) (64-bit)

**Comment by jbrcna** [comment]
date field can now be cleared using the button. moving this ticket to done.
v4.63.0-dev
https://main-enterprise.demo.design.infor.com/components/datepicker/test-input-datefield-clear.html
