### ISSUE TITLE
Mask - Support option to force decimal portion of mask to pad right

### ISSUE THREAD

**Issue by PilotBob** [infor-design/enterprise#617]
When using new-mask we would like an option for the mask to force right fill the decimal portion with zeros. 

For example.... if the mask pattern is #,###,###.00 

User types: 123
Result on blur: 123.00

User types: 123.1
Result on blur: 123.10

**Is your feature request related to a problem? Please describe.**
No.  Per our product manager, this functionality is required for our application which is mostly a financials app.

**Describe the solution you'd like**
A pattern option perhaps forceTrailingZeros, forceDecimalTrailingZeros or fillTrailingZeros or something.

Maybe also, if using old mask pattern a character that indicates it will fill.  "0" currently means decimal place perhaps "#" (or "9") after the decimal place could mean it will be filled with a zero if not provided by input.

**Describe alternatives you've considered**
Create a blur event on .new-mask, read the mask options, right fill with zeros based on the decimalLimit.

**Comment by tmcconechy** [comment]
@EdwardCoyle Just making sure there is no way to do this yet? Seems like forceDecimal would do it by name but it only forces there to be a decimal.

**Comment by tmcconechy** [comment]
There is an example that is doing this. https://github.com/infor-design/enterprise/blob/master/app/views/components/mask/test-number-mask-auto-format.html#L24

Outside the mask component.. Which can be used as a workaround until this is sorted out

**Comment by EdwardCoyle** [comment]
`requireDecimal` doesn't currently pad zeroes at the end.  It forces the decimal to be present and that's about it.

For context, the Mask component specifically isn't meant to do any sort of automatic formatting of numbers beyond inserting the decimal and special characters in the correct places.  The example @tmcconechy linked to above demonstrates how to combine the Mask with the Locale component to do the formatting the way you're expecting.

**Comment by tmcconechy** [comment]
I going to close this as it seems we have an example that shows how to do what you are expecting.

**Comment by PilotBob** [comment]
Did we add this because the control doesn't do this inheriently?

**Comment by tmcconechy** [comment]
Yes, thats why. We basically only mask things that you "dont type in" or "optionally type in or it fills. 
As such i think this is something thats not necessarily out of scope but hasnt got a lot of asks. If you disagree and need it i can see coming back later on it.

**Comment by PilotBob** [comment]
I think our product owner wants this behavior. So we do need it. But, it's easy enough to implement ourselves that if you don't support it, we'll be fine.
