### ISSUE TITLE
HomePage: Fix Tests

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6179]
**Describe the bug**

The home page puppetteer tests are a bit unstable. @ericangeles will try to fix...
If thats not working we can make a page wth no animations and try on that

Will skip these for now in the code.

**To Reproduce**
https://github.com/infor-design/enterprise/runs/5462032106?check_suite_focus=true#step:10:99

**Expected behavior**
All home page pass on the PR...

**Comment by janahintal** [comment]
QA Passed. 
https://main-enterprise.demo.design.infor.com/components/datagrid/test-timepicker-24.html?theme=new&mode=light&colors=2578a9
![image](https://user-images.githubusercontent.com/45757016/158578928-c0b7c056-ed1a-44b6-9d24-87e8cb0e25e7.png)
