### ISSUE TITLE
Tree Sortable

### ISSUE THREAD

**Issue by MilanInfor** [infor-design/enterprise#618]
[Tree_Sortable.zip](https://github.com/infor-design/enterprise/files/2290777/Tree_Sortable.zip)
**Describe the bug**
Sortable on the Tree does not works correctly If I add items by button as example attached . 

**To Reproduce**
1. click Add button3. 
2. try do drag and drop  new items

**Expected behavior**
Drag and drop new item

Version

Soho : 4.8.0

**Comment by tmcconechy** [comment]
Can you add the sample again in a zip. I was not able to reproduce this on http://master-enterprise.demo.design.infor.com/components/tree/example-sortable.html

This example does add node and they all work when added that way. Should not be effected but i test on 4.9 and 4.1.0-dev

**Comment by tmcconechy** [comment]
Ok, the problem seems to be when you use updateNode it no longer works after that.

**Comment by Milan1983** [comment]
My project will end at the end of the month. Is there any chance this Issue will be solved before that?
Thank you

**Comment by tmcconechy** [comment]
This is scheduled for this sprint. It should be released and tested in 4.11 on Oct 4.

**Comment by tmcconechy** [comment]
@deep7102 When you look at this i suggest also fixing #718 which seems related.

**Comment by brianjuan** [comment]
http://4110-beta0-enterprise.demo.design.infor.com/components/tree/test-sortable-update-node.html
Passed QA testing across all browsers
