### ISSUE TITLE
[iOS] Tabs Component- Spillover dropdown is not clickable

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#619]
**Describe the bug**
[iOS] Tabs Component- Spillover dropdown is not clickable

**To Reproduce**
1. Open any browser on Android and iOS devices including iPad
2. Go to http://master-enterprise.demo.design.infor.com/components/tabs-multi/example-index.html
3. Click the Spillover dropdown to access other tabs
4. Dropdown won't open

**Expected behavior**
Drop downs should open

**Screenshots**
![image](https://user-images.githubusercontent.com/39101346/44159186-a807a280-a084-11e8-94a8-1af25e8459e6.png)

**Platform**
 - All iOS Device 

**Additional context**
None

**Comment by brianjuan** [comment]
http://localhost:4000/components/tabs-multi/example-index.html
http://master-enterprise.demo.design.infor.com/components/tabs-multi/example-index.html
Passed QA testing on all mobile browsers
