### ISSUE TITLE
Calendar - use 3 letters to display day of the week label

### ISSUE THREAD

**Issue by edinfor** [infor-design/enterprise#6193]
**Is your feature request related to a problem or use case? Please describe.**
A clear and concise description of what the problem is. [e.g. {Component Name} has a problem when {...}]

Range calendar is using single letter to display day of the week as default, this needs to be changed to use three letter instead.
![image](https://user-images.githubusercontent.com/82842191/157895444-b5c91d1c-ac54-4b33-bb51-300978cf7053.png)

It seems like single letter is only used on popup or smaller views, all in page calendars should display three letter
![image](https://user-images.githubusercontent.com/82842191/157895574-567bbe61-4fbb-43cb-a729-334dd40d6a8f.png)

I will submit a PR for this fix

**Describe the solution you'd like**
A clear and concise description of what you want to happen. [e.g. {Component Name} would work better if {...}]
should display three letter as default
![image](https://user-images.githubusercontent.com/82842191/157895574-567bbe61-4fbb-43cb-a729-334dd40d6a8f.png)

**Describe alternatives you've considered**

**Additional context**
And what application do you work on? [e.g. {Infor XYZ}]

**Comment by tmcconechy** [comment]
Yes i agree - probably could use 3 letters here (short vs abbreviated)
