### ISSUE TITLE
DataGrid: Misaligned datepicker icon button and time value upon click

### ISSUE THREAD

**Issue by ktfields** [infor-design/enterprise#6198]
**Describe the bug**
DataGrid: Misaligned datepicker icon button and time value upon click

**To Reproduce**

Scenario 1: Misaligned datepicker icon button. Persistent on Chrome, MS Edge and Firefox
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-datetime.html
2. Click on any Date cells or datepicker icons
3. Observe the icons
Actual Result: datepicker icon button is misaligned

**Expected behavior**
No alignment issues

Scenario 2: Misaligned time value on Firefox
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-datetime.html
2. Click on any Time cells or timepicker icons
3. Observe the values
Actual Result: time value is misaligned

**Expected behavior**
No alignment issues

**Version**

- ids-enterprise: 4.62.0-dev

**Screenshots**
Scenario 1: Misaligned datepicker icon button
![datepicker_misalignment](https://user-images.githubusercontent.com/39935379/158351430-d5e027a1-4ef8-4806-a2df-f73180600e4c.gif)

Scenario 2: Misaligned time value on Firefox
![timevalues_misalignment](https://user-images.githubusercontent.com/39935379/158351469-49c45863-fb03-4b57-b10b-261650d31ddf.gif)

**Platform**
 - Infor Application/Team Name: Lawson System Foundation (Portal Team)
 - Browser Name: Chrome, MS Edge and Firefox
 - Browser Version: Chrome 99.0.4844.51, MS Edge 99.0.1150.39, Firefox 99.0b3

**Comment by tmcconechy** [comment]
- make sure to check both versions and all row heights
- make sure timepicker doesnt regress https://main-enterprise.demo.design.infor.com/components/datagrid/test-timepicker-24.html

**Comment by awbuboltz** [comment]
Noticed today that the new high contrast theme looks wrong as well.

![high contrast](https://user-images.githubusercontent.com/2107139/158615004-5353977d-732f-4f97-9922-58f569f8b825.png)

**Comment by awbuboltz** [comment]
Hey Tim, what are your timeline thoughts on this? We're in our final testing and are hoping for a quick turnaround if possible.

**Comment by tmcconechy** [comment]
Im not sure who can pick this up? @tjamesallen15 can you pick this up? @ericangeles you on vacation yet?

**Comment by ericangeles** [comment]
@tmcconechy I can take a look

**Comment by awbuboltz** [comment]
Hey @tmcconechy  or @ericangeles , could this be merged to 4.60.1? That is our "release" branch and where our QAs found the bug.

**Comment by tmcconechy** [comment]
Yes, will do when merged. Did you have a chance to test this?

**Comment by s-werking** [comment]
Hi @tmcconechy, I tested and all looks good. Thanks!

**Comment by tmcconechy** [comment]
ok will make the patch today.. cc @awbuboltz

**Comment by tmcconechy** [comment]
@awbuboltz @s-werking -> 4.61.1 with this patches is done now.

**Comment by tmcconechy** [comment]
Opps sorry - added this to `4.60.2` as well.

**Comment by jbrcna** [comment]
QA Passed. moving this ticket to done
v4.62.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-datetime.html
https://main-enterprise.demo.design.infor.com/components/datagrid/test-timepicker-24.html
