### ISSUE TITLE
[Mobile] Toolbar Flex Component- Display issues on Toolbar Flex

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#620]
**Describe the bug**
[Mobile] Toolbar Flex Component- Display issues on Toolbar Flex

**To Reproduce**
1. Open any browser on Android and iOS devices
2. Go to http://master-enterprise.demo.design.infor.com/components/toolbar-flex/example-index.html
3. Notice the gray shadings on Incredibly Long Text label

**Expected behavior**
Gray shading should not appear

**Screenshots**
![image](https://user-images.githubusercontent.com/39101346/44159393-3c720500-a085-11e8-95d1-afa292e2e6a1.png)

**Platform**
 - All Mobile Device 

**Additional context**
None

**Comment by tmcconechy** [comment]
This issue appears to have been corrected on the latest version http://master-enterprise.demo.design.infor.com/components/toolbar-flex/example-index.html
