### ISSUE TITLE
Website: 404 Errors on the github links

### ISSUE THREAD

**Issue by walaareafaee** [infor-design/enterprise#6204]
**Describe the Issue**
we need code samples  for all components in github, all links take redirect me to github 404 not found resource

**Comment by tmcconechy** [comment]
Hi @walaareafaee please use the templates when filing issues https://github.com/infor-design/enterprise/issues/new/choose

The code samples are all here in the repo https://github.com/infor-design/enterprise/tree/main/app/views/components

Which links and where are you refering to? I assume the ones here https://design.infor.com/code/ids-enterprise/latest/accordion if so yes i can confirm they 404.

@jmacaluso711 - can you check this out again when you have a chance?

**Comment by tmcconechy** [comment]
links should be good now - try a hard refresh

**Comment by walaareafaee** [comment]
i got access to all components thank you so much
