### ISSUE TITLE
SwapList: Clicking x button (clear) on search field from swaplist resets search term

### ISSUE THREAD

**Issue by kenneth-acejo** [infor-design/enterprise#6206]
**Describe the bug**
Initial click on x button in a search field from swaplist resets the search term.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/swaplist/example-search.html
2. Click on Selected search field
3. Type "Option"
4. Click any item on Available card (e.g. Option B, Selected search field now loses focus)
5. Click on Selected search field again
6. Hit backspace (Search term should now be "Optio")
7. Click x on Selected search field to clear.

**Expected behavior**
Search field should be cleared.

**Actual behavior**
Search field value resets back to "Option"

**Version**
- ids-enterprise-ng: 10.11.x

**Comment by tmcconechy** [comment]
Closing stale issues
