### ISSUE TITLE
Tabs Module: 'x' button is not centered in new version

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6207]
**Describe the bug**
Tabs Module: 'x' button is not centered in new version

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html?theme=new&mode=light&colors=0066D4
2. Type in the search field 
3. Click Tab to focus in 'x' button

**Expected behavior**
Blue circle / focus should be centered

**Version**
4.62-ids-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/158817616-c984a75a-9e8d-458a-bec0-f75c24cab170.png)

**Platform**
Windows Chrome 10 & other major browsers & OS

**Additional context**
N/A.

**Comment by tmcconechy** [comment]
<img width="313" alt="Screen Shot 2022-03-17 at 9 26 29 AM" src="https://user-images.githubusercontent.com/814283/158818321-12e0178c-a20a-46e9-97e8-0fc65c4a5b1e.png">

My search icon looks wierd also

**Comment by davidcarlsonberg** [comment]
Looks like that search icon fill is negotiated by this line...
`.module-tabs.is-personalizable .toolbar-searchfield-wrapper > svg {
    fill: #ffffff !important;
}`
...which is coming from `<style id="soho-personalization"></style>`.

Any idea why this is injected? I removed the `.is-personalizable` class and it fixes the issue but I assume we should correct the underlying style issue there?

**Comment by tmcconechy** [comment]
@davidcarlsonberg yeah i think maybe you could exclude that icon specifically with a rule. It probably needs stroke instead of fill where the rest can use fill.

The idea was to support changing personalization colors on this page https://main-enterprise.demo.design.infor.com/components/tabs-module/example-index.html?colors=7928E1

**Comment by janahintal** [comment]
QA Failed  in https://main-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html?theme=new&mode=light&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/164016845-e0a41531-bdcd-48cf-9885-ded34f9cd6ee.png)

**Comment by tmcconechy** [comment]
I think this wasnt properly deployed. Once i merge some PR's today it should be ok. So check back tomorrow?

**Comment by janahintal** [comment]
Hi @tmcconechy, it does still looks off in https://main-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html?theme=new&mode=light&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/164149885-9348b345-d8dc-4033-8b2b-97f978c8d28b.png)

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html?theme=new&mode=light&colors=0066D4
![image](https://user-images.githubusercontent.com/45757016/165931300-8512ef9b-812f-4952-9a0a-f433c310d95e.png)
