### ISSUE TITLE
Slider: Bar is not visible on a modal

### ISSUE THREAD

**Issue by amittapally** [infor-design/enterprise#6211]
**Describe the bug**
Hi Team, I use Soho Slider component in IDM Document Monitor Widget inside Modal. It works fine in Portal V1(all themes) and Portal V2 except in the Dark theme. Slider wrapper is not visible in Portal V2 Dark theme. Please find the below screenshot of widget in Portal V1 and Portal V2. The background color is different in V1 and V2. This is happening in dialog box. I suspect background color of .modal-content and slider wrapper are the same. That's why it is not shown.. Can anyone help us to fix in issue

**To Reproduce**
Add the Soho Slider inside modal and test in Portal V2 Dark theme. The slide wrapper background and modal background color looks same and wrapper is not shown.  

**Expected behavior**
Slider wrapper should be shown like Portal V1.

**Screenshots**
![image](https://user-images.githubusercontent.com/89181007/159204301-e41bcdb9-d19e-4ca0-9e27-93843ac99179.png)
![image](https://user-images.githubusercontent.com/89181007/159204358-6039bb2e-e7a3-4f22-afe4-b866866760fd.png)

**Comment by tmcconechy** [comment]
cc @kevinwhitedesign

**Comment by kevinwhitedesign** [comment]
Explored this one a bit, we can discuss if this works or if any other considerations should be made. https://www.figma.com/file/oAQxLvHH5Pk1bL7ibbCpmj/Slider-Dark-UI?node-id=0%3A1

**Comment by tmcconechy** [comment]
@kevinwhitedesign can you give us access to the file?

**Comment by jbrcna** [comment]
hi @tmcconechy @davidcarlsonberg , this is now working as expected. however, i noticed **unecessary scroll bar** in `EDGE` using `New theme`
https://main-enterprise.demo.design.infor.com/components/modal/example-slider.html?theme=new&mode=dark&colors=db7726
<img width="918" alt="image" src="https://user-images.githubusercontent.com/56722184/164150040-2f22e3f6-2ded-4e37-8a73-376ace3c1e7a.png">

`Edge new theme`
<img width="413" alt="image" src="https://user-images.githubusercontent.com/56722184/164150850-fd346c32-18de-408d-9d79-dec19174d6b5.png">
