### ISSUE TITLE
Unit Testing: Create a Puppeteer Script for "Badge/Tag - Update colors for better accessibility contrast"

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#6213]
Describe the Issue
Create a unit testing for "Badge/Tag - Update colors for better accessibility contrast".

See attached BDD for more information.
[BDDStory_github#5673.docx](https://github.com/infor-design/enterprise/files/8315886/BDDStory_github.5673.docx)

Related github issue
#5673

**Comment by maezcruz** [comment]
Cc: @CindyMercadoReyes

**Comment by CindyMercadoReyes** [comment]
This task is now completed.
