### ISSUE TITLE
Modal/Lookup: Closing a modal before an async lookup that's in it is loaded breaks the UI

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#6218]
**Describe the bug**
When there's an async lookup inside a modal and you close the modal while waiting for the lookup to load, the modal backdrop doesn't disappear which prevents you from interacting with the page and you need to reload the page to fix it.

**To Reproduce**
The following code can be used to reproduce this:

```
// Button to open the modal
@Component({
	selector: "demo-button",
	template: `<button soho-button="primary" (click)="openDialog()">Open Dialog</button>`
})
export class DemoButtonComponent {
	constructor(private readonly dialogService: SohoModalDialogService) { }

	openDialog(): void {
		const dialog = this.dialogService.modal(DemoModalComponent);
		dialog.buttons([{ text: "Close", click: () => dialog.close() }]).open();
	}
}

// Modal
@Component({
	selector: "demo-modal",
	template: `<input soho-lookup [beforeShow]="beforeShow"/>`
})
export class DemoModalComponent {
	beforeShow = (_: SohoLookupStatic, response: SohoLookupBeforeShowResponse) => {
		setTimeout(() => response(), 2000);
	}
}
```

1. Click the button to open the modal.
2. Click the lookup button.
3. Close the modal either by clicking the "Close" button or the "Esc" key BEFORE the lookup has been loaded. Have to be quick before the modal opens
4. The lookup doesn't open and the modal closes, but the modal backdrop is still there which prevents you from interacting with the page.

**Expected behavior**
The lookup shouldn't open and the modal should close, but the backdrop should also disappear.

**Version**
- Observed and reported in ids-enterprise@4.60.0 / ids-enterprise-ng@13.1.1

**Screenshots**
![dialog_lookup](https://user-images.githubusercontent.com/63045013/159665086-6ac3fbc4-f71e-4193-8e2c-4883d55b7ab0.gif)

**Platform**
 - Infor Application/Team Name: Homepages
 - Device: All
 - OS Version: All
 - Browser Name: All
 - Browser Version: All

**Additional context**
Tested the same scenario with a second modal instead of a lookup but didn't observe the issue in that case.

**Comment by tmcconechy** [comment]
@radovaniljic can you be more specific about where to put this code? Maybe you can plop it in a stackblitz so we can see it running if you fork this https://stackblitz.com/edit/ids-quick-start-1321

**Comment by tmcconechy** [comment]
Maybe i could but i wasnt sure and would have to spend time figuring out where to put them. I tried to follow the above steps on your stackblitz and im not seeing the same thing as the video?

**Comment by radovaniljic** [comment]
Yeah I should've just put it in a stackblitz :) It requires some timing to make it happen, so if you try a few times you should get it
![dialog_lookup2](https://user-images.githubusercontent.com/63045013/159731215-99fca62c-dfd8-42f2-b3f0-9ae1ec7e4133.gif)
.

**Comment by jbrcna** [comment]
QA Passed . v4.64.0-dev . moving this ticket to done
https://main-enterprise.demo.design.infor.com/components/modal/test-async
