### ISSUE TITLE
Tooltip add support for escaping tags

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise#622]
**Is your feature request related to a problem? Please describe.**
We are using inputs where user are allowed to write html code. however this code is interpreted by tooltip as html and not as text

**Describe the solution you'd like**
We would like to have an option to make tooltip treat html content as string text rather than html (escape tags)

**Describe alternatives you've considered**
We could manually escape content for every tooltip used in our application

**Additional Context**
From an email conversation, the example should an input with ”<p><span><test>html rendered” in it.
Expect the tooltip to show that whole string.
We probably should add an escapeContent option that turns these into printable characters and inserts that in the tooltip

**Comment by tmcconechy** [comment]
This issue was addressed so closing.
