### ISSUE TITLE
SwapList: Search results in swaplist or listview contains mismatched items when filtering

### ISSUE THREAD

**Issue by kenneth-acejo** [infor-design/enterprise#6222]
**Describe the bug**
Search results in swaplist or listview contains mismatched items when filtering

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/swaplist-search
2. Click on any of the two search bar.
3. Type any one from these letters: f, a, l, s, e (or the word "false" itself)

**Expected behavior**
Should only contain items with the search term

**Version**
- ids-enterprise-ng: 10.11.x

**Screenshots**

<img width="797" alt="search_bug" src="https://user-images.githubusercontent.com/17284784/159202684-0593444f-74ea-47fc-98d4-32e66a83504a.png">

**Comment by kenneth-acejo** [comment]
<img width="941" alt="search_mismatch" src="https://user-images.githubusercontent.com/17284784/159766201-ea860379-9291-4977-8af9-e2fc629a94c2.png">

Here is a screenshot from https://main-enterprise.demo.design.infor.com/components/swaplist/example-search.html
I don't know why it is different for you but everytime I type "f", items that does not contain the search term still shows.

**Comment by tmcconechy** [comment]
Ok i see yes it should have hidden them. I think we have the same problem just a different way. It doesnt filter with one letter only starts working with two (and also seems like "fal" is wrong).

Something definitely off here

**Comment by GlenlieMaye** [comment]
QA tested and passed. Moving this ticket to Done. Thanks!

![image](https://user-images.githubusercontent.com/102151352/165876564-75b7de9c-84df-4290-b28e-9ce51d4088e4.png)

![image](https://user-images.githubusercontent.com/102151352/165876607-7333a794-b325-49e9-b42b-3e3af6db32e3.png)

![image](https://user-images.githubusercontent.com/102151352/165876667-c4990893-aac0-4360-bfa4-4dd5013d6fde.png)

![image](https://user-images.githubusercontent.com/102151352/165876719-7d98d6e9-56eb-4324-837a-d2ae73e46bd6.png)
