### ISSUE TITLE
Datagrid: Context menu left alignment issue with checked items and submenus 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#6223]
**Describe the bug**
When opening the context menu for a datagrid row, the left alignment of menu items is incorrect when a menu item is checked and a submenu exists (and no icons exist).

**To Reproduce**
1. Using the attached 'test-contextmenu-alignment.html'
2. Open the context menu for a datagrid row
3. Notice that the submenu items are not properly aligned

**Expected behavior**
Submenu items have the proper left alignment.

**Version**
- ids-enterprise: v4.63.0-dev

**Additional context**
Able to see the issue only the first time the context menu is opened since its only built once.  In Landmark, we build the context menu each time the context menu is opened.

**Comment by claudenbach** [comment]
[contextmenu-alignment.zip](https://github.com/infor-design/enterprise/files/8333665/contextmenu-alignment.zip)

**Comment by tmcconechy** [comment]
This is somewhat correct in that the selectable items are indented and the unselectable ones are not. I dont think it looks terrible. Will review with design...

**Comment by tmcconechy** [comment]
![ContextMenuAlignment](https://user-images.githubusercontent.com/814283/159726733-23ea342d-8629-4920-b3e8-6ca2e18edbb3.gif)

What do you think @kevinwhitedesign think we should always indent more? Or make equal indenting when one ore more is selectable?

**Comment by kevinwhitedesign** [comment]
@tmcconechy on our end, the component looks like it is always indenting. This is ok https://main-enterprise.demo.design.infor.com/components/contextmenu/example-index.html

**Comment by tmcconechy** [comment]
yeah right i see - must be a bug in this one scenario

**Comment by GlenlieMaye** [comment]
QA tested and passed.
https://main-enterprise.demo.design.infor.com/components/datagrid/test-contextmenu-alignment.html

![image](https://user-images.githubusercontent.com/102151352/169431150-1788e6bb-4921-45d7-b5cd-c17e7c9fb8d1.png)
