### ISSUE TITLE
FileUploadAdvanced component french language issue

### ISSUE THREAD

**Issue by ShashidharGutha** [infor-design/enterprise#6226]
**Describe the bug**
We are using fileupload advanced component to upload files using browse and drag drop files option. We are unable to view select files to browse in french language below are the sample links of the component in english (working correct) and french (not working properly) language.

English language with select files option correct example:
https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html?locale=en-US
French language without select files option:
https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html?locale=fr-FR

1. Click on 'https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html?locale=fr-FR'
2. We are unable to view select files to browse in french language.
3. See error

**Expected behavior**
Expecting select files option in french language like in other language. Below is the english language example link of the component.
https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html?locale=en-US
**Version**

- ids-enterprise: v4.3 and latest versions too.

**Screenshots**
<img width="782" alt="image" src="https://user-images.githubusercontent.com/102306888/159945997-2263d4fe-ae80-48ab-805a-f761b20aedaa.png">

**Platform**
 - Infor Application/Team Name: Infor Concierge.
 - OS Version: Windows 11
 - Browser Name: All

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to done. thank you
https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html?locale=fr-FR
<img width="471" alt="image" src="https://user-images.githubusercontent.com/56722184/160529908-4d6efd2f-6822-4197-81d8-756ea0f75c6f.png">
