### ISSUE TITLE
Datagrid: After clearing the filter row, a column's selected filter condition is not restored

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#6227]
**Describe the bug**
After clearing the filter row, a column's default filter operand is not maintained.  The column has filterConditions with a condition that specifies its to be selected. 

**To Reproduce**
1. Using the attached 'test-selected-filter-condition.html'
2. For Product Name in the filter row, open the operand drop-down (notice that Starts With is selected)
3. Change the operand to Equals and enter Compressor into the input cell
4. Click on the More (...) button, click on Clear Filter menu item
5. For Product Name in filter row, open the operands drop-down
6. Notice that the first operand is selected

**Expected behavior**
After a filter row is cleared, the selected operand should reflect the selected operand provided by the filterConditions property on the column.

**Version**
- ids-enterprise: v4.63.0-dev

**Comment by claudenbach** [comment]
[SelectedFilterCondition.zip](https://github.com/infor-design/enterprise/files/8345128/SelectedFilterCondition.zip)

**Comment by tmcconechy** [comment]
So you think the selected condition should stay? As of now we reset the condition and the selection in the list.
I'm not even really sure if this should be considered a bug as it seems minor?

**Comment by tmcconechy** [comment]
because the operator will filter the clear function should also clear that back to the default so the filter is reset

**Comment by claudenbach** [comment]
That is correct.  Is additional clarification required?

**Comment by tmcconechy** [comment]
The idea was that when you clear the filter it resets the filter value and the filter condition. Changing it to keep the filter condition would be a behavior change not everyone would want (and an extra setting to maintain if we did it that way). Is it really worth changing?

**Comment by claudenbach** [comment]
Now have a customer attached to the Landmark ticket regarding this issue.

**Comment by tmcconechy** [comment]
I'm not sure we want to keep the conditions when you clear it as it clears both the . So maybe they dont clear and just change the text in the field to something else? I.E. Clearing filter clears values and conditions.

Or you could add maybe a new option?

**Comment by tmcconechy** [comment]
What you could do is either:

A) implement your own clear filter menu item and not use the default one in the datagrid. This one would do what you want and only clear the conditions. If we need a supporting API for that operation we could help with that.
B) You implement two menu items – one that clears it “normally” and one that clears just the operations.
C) You could implement a saved filter feature where the use can save a “default” filter then use the api to restore it. That way they could save any filter exactly how they want it and restore to these saved ones. This should be doable with the current applyFilter / saveFilter code.

**Comment by tmcconechy** [comment]
Closing stale issues
