### ISSUE TITLE
Data Visualization: Legend requiring scrollbar to be visible

### ISSUE THREAD

**Issue by jvedua** [infor-design/enterprise#6231]
T2V teams are reporting that they need to use a scrollbar so that the chart legend can be visible, Would like to request a fix for this that we can recommend?

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/49638020/160326134-6c5fe7f9-7df7-44f7-9521-cb01400406cd.png">

Reference document:
https://inforonline-my.sharepoint.com/:w:/r/personal/crisellestephanie_ong_infor_com/_layouts/15/Doc.aspx?sourcedoc=%7B1f76a04a-8c9d-4767-8ad6-2ecb996992aa%7D&action=edit&wdPid=18ef7a4f

**Comment by tmcconechy** [comment]
Please check the bug reporting guidelines and follow the template when reporting issues. https://github.com/infor-design/enterprise/issues/new/choose and https://github.com/infor-design/enterprise/blob/main/docs/CONTRIBUTING.md#bug-reports as we would need run-able reproductions to solve bugs

But trying on the popup example:
https://main-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-popup.html

I dont see there how it would be possible to scroll. So must be a specific case/example needed. Or maybe you need to use the popup version of the chart?

**Comment by jvedua** [comment]
Hi @tmcconechy thanks for reminding me on the guide, will check it and follow it, my apologies.

About the chart legend, T2V Teams would like it to be displayed immediately without additional clicks, will the pop down be the only workaround for the legend not to be hidden under the fold?

They also required the data visualizations to be displayed immediately in the widget so I don't know if using a popup version will be suitable.

**Comment by tmcconechy** [comment]
Well i think those are the options and all i can think of

1) allow it to scroll on bottom
2) use the popup Ok try to implement it like this example then https://main-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-popup.html
3) put it on the right

**Comment by jvedua** [comment]
Ok Tim, will discuss this with the team.. also can you check our enhancement backlog request document in the link below? I dont know if some of the issue here already has alternatives that you might know?

https://inforonline-my.sharepoint.com/:w:/r/personal/crisellestephanie_ong_infor_com/_layouts/15/Doc.aspx?sourcedoc=%7B1f76a04a-8c9d-4767-8ad6-2ecb996992aa%7D&action=edit&wdPid=18ef7a4f

As I will be creating enhancement tickets for all of this.. let me know your thoughts.

**Comment by tmcconechy** [comment]
Sure, I don't have access to this doc right now. Yes, I think let's review before make a lot of enhancement tickets. To make sure they might seem like something we would actually want to / or could feasibly do.

Maybe we need to figure out a way to handle these things or setup some parameters around it before having a lot of things in the backlog we cant really do.

cc @inforandy

**Comment by tmcconechy** [comment]
@jvedua i took a look brief look at the document. A lot there but seems not all for us. But Definitely not all these should just be created as issues ( i maybe see one or two as an enhancement). Im seeing things like:

- bugs on there side (one i already talked to someone about)
- specific details they might need to code themselves
- maybe not knowing you can already do it
- some issues with general comments for the M3 team
- things you probably don't want to do (like an input in a dropdown list) for usability reasons

Maybe the best next course of action is to setup a call with all parties and go through this list. cc @inforandy and @lucacolumbu

**Comment by jvedua** [comment]
@tmcconechy.

Can you comment that on the document? which is which? so we can discuss that once I setup a meeting?

Just comment on each of the issues so we can track

thanks!

**Comment by tmcconechy** [comment]
Sure I can.. but i don't seem to have the ability to do that. Do you need to setup permissions? @jvedua ?

**Comment by jvedua** [comment]
@tmcconechy I gave you edit privileges

**Comment by tmcconechy** [comment]
ok i went through it - made comments. Actually not seeing anything we would action on in that list in Ids

**Comment by jvedua** [comment]
Thank you @tmcconechy ill discuss it with the team

**Comment by jvedua** [comment]
Hi @tmcconechy  I think we are already good with this issue, we will just recommend what is currently in the IDS thanks!

**Comment by tmcconechy** [comment]
Got it thanks for following up
