### ISSUE TITLE
DataGrid: Misaligned lookup icon button upon click

### ISSUE THREAD

**Issue by hsubtain** [infor-design/enterprise#6233]
**Describe the bug**
DataGrid: Misaligned lookup icon button upon click

**To Reproduce**
NOTE: This is browser specific, I can only reproduce this in FireFox browser. Tested on FireFox 98.0.2 (64-bit)
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-list-lookup.html?theme=classic&mode=light&colors=7928E1
2. Click on any Product ID cells 
3. Observe the lookup icon is misaligned 
     Actual Result: Lookup icon is misaligned

**Expected behavior**
No Alignment issues 

**Version**
- ids-enterprise: 4.63.0-dev

**Screenshots**
![Lookup icon misalign](https://user-images.githubusercontent.com/100820299/160378885-dd5b65eb-0684-43aa-8b81-78303f761849.gif)

**Platform**
 - Infor Application/Team Name: Lawson System Foundation (Portal Team)
 - FireFox 
 - Browser Version: FireFox 98.0.2 (64-bit)

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to done.
v4.63.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/example-list-lookup.html
<img width="1654" alt="image" src="https://user-images.githubusercontent.com/56722184/165072517-cb601b91-adb0-4e73-9854-5e62ebda8731.png">

Hello @tmcconechy , @ericangeles , I noticed some off edges when using `firefox` with `High Contrast `- `Classic` -` Extra Small`. try to zoom in to see the edges. I'd like to clarify if this could be a bug? thank you.
<img width="432" alt="image" src="https://user-images.githubusercontent.com/56722184/165072820-d9e22d0c-a28c-477c-a07e-3741d03f4731.png">
https://main-enterprise.demo.design.infor.com/components/datagrid/example-list-lookup.html?theme=classic&mode=contrast&colors=133c59

**Comment by ericangeles** [comment]
@jbrcna it looks okay on my end whether zooming in or just a normal view. What version of firefox are you on?

**Comment by jbrcna** [comment]
`Monterey 12.3.1`
`Firefox 99.0.1 (64bit)`

**Comment by ericangeles** [comment]
@jbrcna I see it now. Good catch! I'll provide a PR for this issue. Thanks!

**Comment by jbrcna** [comment]
this is what it looks like in Browserstack
<img width="928" alt="image" src="https://user-images.githubusercontent.com/56722184/165075308-a286eaab-506d-40cb-80aa-fdc3e6552ecd.png">

**Comment by jbrcna** [comment]
thank you @ericangeles

**Comment by jbrcna** [comment]
the off edge/border issue ( when you click the field to edit) is now fixed on firefox. however the issue still persist on other browsers. see below snapshot from edge
<img width="638" alt="image" src="https://user-images.githubusercontent.com/56722184/165673871-3ff0e935-812f-46a7-8d94-c2a312cad47e.png">



Also, when you click on the field and hover over the next element there's a circle shape with grey background on search icon. try to zoom in to see it clearly
<img width="300" alt="image" src="https://user-images.githubusercontent.com/56722184/165672579-b2902dfd-e0dd-42a6-86c9-2d9c5edc6052.png">
