### ISSUE TITLE
Card: Reduce cards, card-content padding from 16px to 8px

### ISSUE THREAD

**Issue by anton-kurilov** [infor-design/enterprise#6235]
**Is your feature request related to a problem or use case? Please describe.**
When using the .cards class the .card-content gets 16px padding. For mobile devices this takes up too much space.

**Describe the solution you'd like**
Reduce the padding to 8px to avoid breaking existing cards, but make it a little tighter for mobile devices.

**Describe alternatives you've considered**
Autosized cards, don't use cards container since single cards don't have this class, mobile-cards container class alternative, custom in house card class (i.e maybe wraps .card, but not .cards, but we like the multi-select feature out of the box we get)

**Additional context**
Ask for link to Teams chat as needed.
Should update card demos to use .cards wrapper or apply the padding directly in card-content to avoid depending on .cards for this default padding.
Label WFM

**Comment by tmcconechy** [comment]
@kevinwhitedesign do you want to review this one? Im sort of afraid of the impact.
We could make a compact setting that makes it 8px but also not a fan of all the variance.

**Comment by kevinwhitedesign** [comment]
@anton-kurilov can you break this down a bit further for us? 

"Describe alternatives you've considered
Autosized cards, don't use cards container since single cards don't have this class, mobile-cards container class alternative, custom in house card class (i.e maybe wraps .card, but not .cards, but we like the multi-select feature out of the box we get)"

**Comment by anton-kurilov** [comment]
@kevinwhitedesign sure!

- Autosized cards: https://main-enterprise.demo.design.infor.com/components/cards/example-auto-size.html, when talking to @tmcconechy this seemed like a possibility but when I applied .cards and .card-conent I get the same result, so maybe the demo just needs to updated with all the proper classes?
![image](https://user-images.githubusercontent.com/14839675/160422027-12e255bb-8c97-4695-ad6d-b2381409fae4.png)

- mobile-cards container class alternative, this is similar to @tmcconechy idea of a compact setting, but I actually agree that all the variance will just cause more confusion, so not really a fan of this choice.

- Custom in house card class (i.e maybe wraps .card, but not .cards, but we like the multi-select feature out of the box we get): This is just from WFM's point of view, if our designers want tighter cards maybe we just have to build our own in-house wfm card. However I really like the out of the box behavior we get from ids like multi-select https://main-enterprise.demo.design.infor.com/components/cards/example-multi-select.html which I think will be very useful for future mass edit operations.

Hope this helps, after all these investigations I thought it reasonable to just ask for a reduction of padding from 16 to 8 in the ids card-conent. Please feel free to reach out on teams if you have any other questions as well! Thanks!

**Comment by anton-kurilov** [comment]
Just one note interesting note from this article: https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62 

Seems like this section is very relevant to this card-content padding issue?
![image](https://user-images.githubusercontent.com/14839675/160461278-dd866607-a822-46fd-a9e6-fea582a1ddc6.png)

Maybe this is ticket is just a result of a design/code smell due to the lack of space-inset variables?

**Comment by kevinwhitedesign** [comment]
@anton-kurilov Thank you! Still getting confused about the different card classes & variants. Is it that autosize cards are one variant, multi-select another, and your custom cards would be potentially one more? I honestly think that's something we could organize a bit better but I don't understand the complete dev pov on that.

- 16 is the standard spacing or "margins" surrounding the card content in IDS. I have done extensive mobile card testing with this and it has been ideal. I'm open to the design team demonstrating the issue a bit more to highlight the need for 8 if there is. 
- @tmcconechy maybe for the autosize cards we should introduce this padding by default?
- @anton-kurilov an alternative is to switch to a list on mobile, instead of a card list, which should give you more space. 
- Appreciate that Nathan Curtis article, I met him in person once and we're philosophically in agreement there. We have mostly integrated an 4px, 8px, 16px, 24px, 32px, etc spatial system into the current components, and the new components will completely be based on this.

**Comment by anton-kurilov** [comment]
@kevinwhitedesign no problem!

_Is it that autosize cards are one variant, multi-select another, and your custom cards would be potentially one more?_
The autosize and multi-select are ones are just different variants of the ids card from what I understand (@tmcconechy). The custom cards would be a wfm only venture which **I would rather not go down this route given how useful and comprehensive the ids card already is**. The custom cards is more of a last resort if we can't make things such as padding more flexible with inset value modifiers like or something.

_an alternative is to switch to a list on mobile, instead of a card list, which should give you more space._
I was thinking of that too but I was wrong about the mobile only use case. We might use cards in smaller views in desktop as well. 
i.e:
![image](https://user-images.githubusercontent.com/14839675/160468997-059b29e0-9ef5-4e77-956f-3c640f83739a.png)

_Appreciate that Nathan Curtis article, I met him in person once and we're philosophically in agreement there._
Oh nice :), good to hear.

**Comment by tmcconechy** [comment]
Yeah i think im starting to agree with this comment: "I would rather not go down this route given how useful and comprehensive the ids card already is"

There is too much going in a card and its getting hard to maintain the code given how this should be a simple thing. I think for these ones, couldn't you just use the autosize card and then use the css to make your special card designs?

Changing things seems to add too much problems to me

**Comment by anton-kurilov** [comment]
> Yeah i think im starting to agree with this comment: "I would rather not go down this route given how useful and comprehensive the ids card already is"
> 
> There is too much going in a card and its getting hard to maintain the code given how this should be a simple thing. I think for these ones, couldn't you just use the autosize card and then use the css to make your special card designs?
> 
> Changing things seems to add too much problems to me

I don't see how autosize solves the issue if the same thing happens when I use the .cards and .card-content classes that ids provides? @tmcconechy Please See my screenshot in: https://github.com/infor-design/enterprise/issues/6235#issuecomment-1080740730 and without those classes I don't get all the ids card features, unless I am missing something?

I don't think adding inset padding variables that maybe we can apply with a class (similar to font size classes) is adding much complexity for container component, but rather giving the the flexibility to avoid needing to create different variations of the same card which is when maintainability becomes a concern.

**Comment by edgarinfor** [comment]
@kevinwhitedesign , this is related to the overall IDS padding/spacing situation that's been posing challenges for new WFM designs.

The intention is to gain back some real estate to display more data or components on the screen by reducing the space taken by the components.

I don't know if this would qualify as a "variant" of the card since, it wouldn't add or change anything in terms of form, functionality or usage, I would say it's maybe more of a "mode", something like a "compact mode", so, essentially, the same cards, with simply less padding.

**Comment by kevinwhitedesign** [comment]
@anton-kurilov @edgarinfor reviewing internally thanks folks.

**Comment by tmcconechy** [comment]
Also I may have misunderstood the scope here. So if its just adding a compact class that has less padding i agree that wouldn't be such a big deal and is somewhat consistent.

**Comment by tmcconechy** [comment]
If we do this can it go in the web components @anton-kurilov ?

**Comment by edgarinfor** [comment]
We are currently using the Angular components so, we would still need it for NG...

**Comment by tmcconechy** [comment]
Got it. Although you could try the card web component in angular and use it along side other ones. But let me see what i can do.

**Comment by talkaboutdesign** [comment]
The title of this ticket is tricky. Plus don't we already offer cards with no padding? 

In this example: https://design.infor.com/code/ids-enterprise/latest/demo/components/cards/example-auto-size.html

What's the problem we are trying to solve?

**Comment by tmcconechy** [comment]
Yeah the card current has no padding, and you add it. We are adding an option for 16px added. Should we add options for 8px, 4px? Or dev teams just add it?

**Comment by anton-kurilov** [comment]
Hey @tmcconechy, @talkaboutdesign, I actually already talked about the difference between the auto-size demo and the .card-content class adding the 16px on our behalf.

This issue is specifically about the .card-content class, which adds the 16px. Please reference my previous response for screenshots referencing the autosize demo: https://github.com/infor-design/enterprise/issues/6235#issuecomment-1080740730 

For my recommendation on how to proceed please reference: https://github.com/infor-design/enterprise/issues/6235#issuecomment-1081876124

If we do not think this is necessary that's fine. But to clarify the only ask here is to create more flexibility when applying the .card-content class.

Thanks!

**Comment by tmcconechy** [comment]
Oh i see. The reason this came up is the "card content" has zero padding so we plan on adding a 16px class. Could add more. But as of now in https://main-enterprise.demo.design.infor.com/components/cards/example-auto-size.html it is zero. So you could build up with that version.

In the screen https://main-enterprise.demo.design.infor.com/components/cards/example-index card-content is zero but the header is 16px.

Still not sure the answer, so bring this up around this work #7379 which adds a 16px padding to the body. This setting makes a lot of sense in web components but in this code its a css class.
