### ISSUE TITLE
The space bar key is ignored when editing a data grid cell

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#624]
**Describe the bug**
The space bar key is ignored when editing a data grid cell

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Click on the Activity column edit a value and replace it with 'This is a Test'
3. See error as the Spaces are ignored 'ThisisaTest'

**Expected behavior**
The user is able to enter a value with spaces.

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome
 - Browser Version 67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
Passed QA testing
