### ISSUE TITLE
Updates on Soho-Tabs with counts

### ISSUE THREAD

**Issue by javenturina** [infor-design/enterprise#6242]
As per the IDS enterprise 4.59.4 version and this PR: https://github.com/infor-design/enterprise/pull/5970

Counts should now be displayed on the bottom for the TABS components if current locale is not on the exempted list (e.g.'en-US', 'de-DE', 'ja-JP', 'zh-CN', 'zh-Hans', 'zh-TW', 'zh-Hant).

I manually set my locale to "pt-BR" , However the expected count positioned of bottom is not working correctly,

![image](https://user-images.githubusercontent.com/91868168/160822271-48418eb2-7fe9-4aeb-bf4e-57acef6c6f01.png)

Here is a snippet of our angular template using the soho tabs component: 
![image](https://user-images.githubusercontent.com/91868168/160821391-cc38669a-5ed5-42f4-b6c3-c64c72946b8a.png)

Here is the html code generated:
![image](https://user-images.githubusercontent.com/91868168/160822814-67cda8b8-bc7e-4a2d-ac62-cf5b488d1b4c.png)

![image](https://user-images.githubusercontent.com/91868168/160823610-433915ae-aa8f-4034-bde1-25694b41e9d0.png)

And the locale value:
![image](https://user-images.githubusercontent.com/91868168/160822562-882e4b54-7bf1-49da-b980-777dd8491396.png)

Did we missed a configuration?

**Comment by tmcconechy** [comment]
Hi, It appears to be working on https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html?locale=pt-BR

One thought is that its a timing issue - i.e. you set the locale after the tabs was already drawn/initialized? Or maybe you dont have the fix and could try 4.61.0

**Comment by javenturina** [comment]
Hi,

Our widget is already using the updated IDS, since iam already seeing the other fix related to removing the counts on spillovers:
![image](https://user-images.githubusercontent.com/91868168/161008832-a8433043-ab2d-40ee-8316-3eb005d33e57.png)


Regarding the timing, Locale is set on before the initialization of the component:

![image](https://user-images.githubusercontent.com/91868168/161010232-7d4f9b96-dcd8-43e0-a0a8-d2c07501c95f.png)

And i tried manually setting the count position using the countsPositionoption:

![image](https://user-images.githubusercontent.com/91868168/161010068-2bd72484-ec1a-455b-8524-58596327a8b9.png)

**Comment by tmcconechy** [comment]
ok @javenturina - then im not able to reproduce. So not 100% sure what we can do. Some suggestions

- does pt-PT or any other locales that should flip it work?
- can you check the html tag for the `data-sohoxi-version` to make sure you really have the right version?
- anything else you can think of so we can reproduce on our end?

I just added the type for next version https://github.com/infor-design/enterprise-ng/commit/e4af2e2a1aef937964f79572a35b36fd327325d1

**Comment by javenturina** [comment]
@tmcconechy  Closing this ticket.
 We updated our code based on the documentation samples, Instead of using templates for the count, we inject the counts after the component is initialized. Thank you.
