### ISSUE TITLE
Datagrid: Leading spaces are visible upon blur

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6244]
**Describe the bug**
When editing a text cell that has leading spaces, the leading spaces are visible after a blur. Currently for cells with leading spaces, they are formatted as left-aligned and once clicked to edit, the spaces will be visible. Is there a way to preserve the leading spaces in memory and trim the leading spaces visually once editing is finished?

**To Reproduce**

1. Go to this zipped html file: [editable-datagrid-leading-spaces.zip](https://github.com/infor-design/enterprise/files/8382483/editable-datagrid-leading-spaces.zip)
2. Note that when first loaded, the "Assemble Paint" cell with leading spaces is still aligned with the rest of the text in that column.
3. Click on the "Assemble Paint" cell
4. Note that this cell has leading spaces
5. Click away from the cell
6. Note that the leading spaces are shown in the cell

**Expected behavior**
After editing a cell with leading spaces, we would like the spaces to be visually trimmed but preserved in memory. This would keep the cell text left-aligned with the rest of the cells.

**Version**
- ids-enterprise: v4.60.2

**Screenshots**
![Leading spaces preserved visually](https://user-images.githubusercontent.com/76002134/160890065-6748a2a9-fc54-4963-b529-c08603e4325b.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows11
 - Browser Name: chrome
 - Browser Version: 100.0.4896.60 (Official Build) (64-bit)

**Additional context**
This looks to be related to this ticket: https://github.com/infor-design/enterprise/issues/4380

If the m3 team is wanting to preserve leading spaces visually, could a datagrid option be added to give us the option to trim leading spaces after blurring?

**Comment by tmcconechy** [comment]
Ok lets make an option 'trimSpaces' with default of off.

**Comment by jbrcna** [comment]
QA Passed. v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/56722184/167773825-cb49eb01-7421-4c01-8ff2-9336313ba625.png">

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/56722184/167773845-af3355ea-e346-493f-bb5a-44d61c6816dd.png">
