### ISSUE TITLE
Calendar: Thick border line on right and bottom 

### ISSUE THREAD

**Issue by ogalcik** [infor-design/enterprise#6246]
**Describe the bug**
The rightmost and bottommost TDs' border in a calendar don't collapse properly and create a double border with the .monthview.is-fullsize.monthview div

**To Reproduce**
- go to https://main-enterprise.demo.design.infor.com/components/monthview/example-index.html

**Expected behavior**
Expecting the right and bottom border to be the same thickness as top and left (1px solid #B7B7BA)

**Version**
-ids-enterprise-ng: v13.1.0

**Screenshots**
![image](https://user-images.githubusercontent.com/102692449/160913699-d5fca754-c570-44cb-acf0-b4c3e37086bb.png)

**Platform**
 - OS Version: Win 11
 - Chrome
 - Version 99.0.4844.82 (Official Build) (64-bit)

**Additional context**
Infor Team: WFM

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/monthview/example-index.html, thanks!
![image](https://user-images.githubusercontent.com/45757016/167561537-dc16809d-b556-4ba6-a162-2d79364cf209.png)

**Comment by tmcconechy** [comment]
@sesbrenosienna could you maybe take a second look at this? I noticed now the bottom border is missing when its bigger.
I.E.

<img width="1354" alt="Screen Shot 2022-05-13 at 10 45 25 AM" src="https://user-images.githubusercontent.com/814283/168308627-524152fc-eb62-4e75-88e5-7df34d173847.png">

So its sort of like we need it? Maybe unless you can find a solution?

**Comment by tmcconechy** [comment]
FYI we dont support IE anymore.

**Comment by janahintal** [comment]
This issue is now resolved. Verified in Edge, Safari, Chrome and FF. Thanks!
