### ISSUE TITLE
Spinbox: Example-autocorrect-on-blur alignment error

### ISSUE THREAD

**Issue by GlenlieMaye** [infor-design/enterprise#6250]
**Describe the bug**
Negative spinbox is not aligned when in Classic Version in Safari browser

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/spinbox/example-autocorrect-on-blur.html?theme=classic&mode=light&colors=2578a9
2. Notice the negative spinbox
3. Zoom in and zoom out the page 

**Expected behavior**
Negative spinbox should be aligned

**Version**

- ids-enterprise: v4.63.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/102151352/161057036-b08f580c-2766-42e4-b47d-abb370291a93.png)

**Platform**
 - Browser Name: Safari
 - Browser Version: Version 14.1 (16611.1.21.161.6)

**Comment by GlenlieMaye** [comment]
Hello @tmcconechy It seems that I'm still using the older version of Safari Browser. I'll gonna update the browser and re-test this ticket.

Regarding with the "negative spinbox", I was referring to the negative icon on left side of the spinbox. Sorry for the confusion.

![image](https://user-images.githubusercontent.com/102151352/161181613-b5c519f5-6d90-4ac7-91fa-443fcdde7cb7.png)

**Comment by tmcconechy** [comment]
Ok Got it. I was able to test this on Safari 15 and compare it to Safari 14 using [browserstack.com](https://www.browserstack.com/)

And i can confirm it is fixed. So i'll close this for now as its minor and somewhat out of our control
