### ISSUE TITLE
Datagrid: Header doesn't align when using Soho.Formatters.Ellipsis

### ISSUE THREAD

**Issue by IdaAspen** [infor-design/enterprise#6251]
**Describe the bug**
When using `Soho.Formatters.Ellipsis`  header in data grid doesn't align.

We are using that on columns "Name", "Description" and "Type" in screenshot  below, and as you can see the header text on these columns are not vertically aligned. When changing to `Soho.Formatters.Text`  for example it looks as it should. Is it something we are missing?

Header colors and styling are similar to this example (we are using @slate01: #efeff0 as background clr): https://master-enterprise.demo.design.infor.com/components/datagrid/test--actions-reload-list.html

**Version**
- ids-enterprise-ng: 13.2.1

**Screenshots**
![image](https://user-images.githubusercontent.com/80949028/161067511-b995b896-029a-44d8-a738-57c376a708f3.png)

**Code snippets**

*Data grid columns in .ts*

		columns.push({
			id: "displayName",
			name: this.translatePipe.transform("name"),
			field: "displayName",
			width: "25%",
			sortable: true,
			resizable: true,
			formatter: Soho.Formatters.Ellipsis,
		});
		columns.push({
			id: "author",
			name: this.translatePipe.transform("author"),
			field: "author",
			width: "10%",
			sortable: true,
			resizable: true,
		});
		columns.push({
			id: "Description",
			name: this.translatePipe.transform("description"),
			field: "description",
			width: "30%",
			sortable: false,
			resizable: true,
			formatter: Soho.Formatters.Ellipsis,
			),
		});
		columns.push({
			id: "date",
			name: this.translatePipe.transform("createdOn"),
			field: "creationDate",
			width: "10%",
			sortable: false,
			resizable: true,
			formatter: Soho.Formatters.Date,
			dateFormat: "M/d/yyyy",
		});
		columns.push({
			id: "suite",
			name: this.translatePipe.transform("type"),
			field: "suite",
			width: "10%",
			sortable: true,
			resizable: true,
			formatter: Soho.Formatters.Ellipsis,
			),
		});
			this.datagridOptions = {
			columns,
			clickToSelect: false,
			dataset: [],
			selectable: SelectableEnum.Multiple,
			paging: true,
			pagesize: 25,
			enableTooltips: true,
			isList: true,
			toolbar: {
				keywordFilter: true,
			},
		};
		`

*Data grid settings in .html*

```
<div
	soho-datagrid="auto"
	[id]="'datagridId'"
	[gridOptions]="datagridOptions"
	(selected)="onItemSelected($event)"
	></div>
```

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Windows 11
 - Browser Name : Chrome
 - Browser Version: Version 99.0.4844.84 (Official Build) (64-bit)

**Comment by jbrcna** [comment]
QA Passed. v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-text-ellipsis-header
