### ISSUE TITLE
Validator: Error message on toolbar button still appears after error is removed

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6253]
**Describe the bug**
When calling removeMessage() on a toolbar button with an error and error message on it, the error is removed but the message remains visible.

**To Reproduce**
1. Please use the zipped html file: 
[test-error-on-toolbar-with-addmessage (2).zip](https://github.com/infor-design/enterprise/files/8399566/test-error-on-toolbar-with-addmessage.2.zip)
2. Click on "Show Error" button
3. Note that an error icon appears on the toolbar and the toolbar button with the error is red and has an error tooltip
4. Click on "Hide Error" button
5. Note that the error icon is removed and the toolbar button is no longer red, but the error tooltip is still visible.

**Expected behavior**
The error message should be removed once Hide Error is pressed.

**Version**
- ids-enterprise: v4.60.3

**Screenshots**
![Visible error message on remove message](https://user-images.githubusercontent.com/76002134/161307997-56ed2a10-a76f-4a46-8bf9-84ba2c3b8b14.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows11
 - Browser Name: chrome
 - Browser Version: 100.0.4896.60 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I didnt know the icon got onto the toolbars. Is thats something you implemented?

**Comment by s-werking** [comment]
I think it's only when inline is set to false for addMessage()

**Comment by tmcconechy** [comment]
Would it be better if it didn't put it on the toolbar at all? I thought it was just for tabs where the tab could be hiding the message on another page

**Comment by s-werking** [comment]
Yeah maybe removing the icon would be best

**Comment by tmcconechy** [comment]
Will do i think in this pattern its a mistake

**Comment by jbrcna** [comment]
QA Passed. v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/toolbar/test-error-on-toolbar-with-addmessage.html
https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-paging-validation.html
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/56722184/170418243-95cb790e-ba2a-419b-84cc-8fc23ee17dd3.png">

**Comment by iamjamesreyracho** [comment]
QA Passed. v4.64.0-dev. But I noticed that the show/hide error button was moved.
https://main-enterprise.demo.design.infor.com/components/toolbar/test-error-on-toolbar-with-addmessage.html

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/98729565/171101132-3bbc66ec-b214-4bd5-927e-e7baea473395.png)

**Comment by iamjamesreyracho** [comment]
QA Passed. Moving this ticket to done. Thanks.
https://nimb.ws/X3D9ux
