### ISSUE TITLE
Tooltip: showing again after clicking another surface 

### ISSUE THREAD

**Issue by Annfo637** [infor-design/enterprise#6257]
**Describe the bug**
The tooltip shows as expected. But after clicking somewhere else or choosing something from a popup/modal and then close, the tooltip appears again. Is this because the latest click is still in focus?

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs-header
2. Hover on the ellipse "..." You'll se the tooltip "More"
3. With or without selecting anything from the menu, a click outside renders the tooltip to show again. Since the button is still in focus. The tooltip showing up again is perhaps not to prefer? Sometimes it is used for buttons that are not visible for the user? 

**Expected behavior**
The tooltip should be visible and pop up when the user hovers over the area that is tooltipped :) After clicking and/or another action is taking place, when clicking elsewhere (in this case just clicking on another surface instead of the popup menu), the tooltip should not show again as it isn't clicked/or hovered on. It's very much about which elements are in focus, perhaps? :)  

**Version**

- ids-enterprise: [v4.59.2]

**Screenshots**
![IDS example with tooltip](https://user-images.githubusercontent.com/54262041/161638304-2a4be4ee-84b5-41b6-abac-06545c8386c6.gif)

**Platform**
 - Infor Application/Team Name: [User Productivity]
**Additional context**

**Comment by tmcconechy** [comment]
Hi @Annfo637 for accessibility reasons we allow the tooltip to show on focus so that keyboard only users can see the tooltip.
However, you can try to turn it off with this setting https://github.com/infor-design/enterprise/blob/main/src/components/tooltip/tooltip.js#L31

**Comment by Annfo637** [comment]
Hi @tmcconechy , I understand. Setting the showOnKeyboardFocus to false solved the issue for one use of the tooltip in our project. It didn't solve another use we have of a button with tooptip, but I suspect that that might have to do with our own settings, so I'll investigate further with my team. Thanks for the quick reply!

**Comment by Annfo637** [comment]
Hi again @tmcconechy, Still having issues with this and a colleague found another scenario with tooltip popping up. It seems that for these scenarios it's not when using the tooltip component as such, but when the class "has-tooltip" is being automatically generated. Is there a workaround for these cases similar to disabling showOnKeyboardFocus?
![image](https://user-images.githubusercontent.com/54262041/163338185-78755ce3-1404-49c1-81ff-ac12ffdf0457.png)

**Comment by tmcconechy** [comment]
So do you mean you cant set `showOnKeyboardFocus` because its generated "through" a component? Not sure i understand the additional case yet and if it needs a new issue or not?

 BTW its probably better to allow `showOnKeyboardFocus` so that the keyboard only user can benefit from the tooltip as well.

**Comment by Annfo637** [comment]
Hi @tmcconechy, sorry for not responding for a while. After some discussion, we decided to keep the standard tooltip behavior and adjust our project's UI to better correspond with this. Thanks for all help!
