### ISSUE TITLE
Sink Page: Message unnecessary scroll bar

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6262]
**Describe the bug**
Sink Page: Message unnecessary scroll bar

**To Reproduce**

1. Go to https://4620-beta0-enterprise.demo.design.infor.com/
2. Scroll to Message section
3. Open 'Success Example'

**Expected behavior**
There should be no scroll bar

**Version**
6.20-ids-beta0

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/161722730-abe44e92-b3f5-4fbf-a77d-e95a38502102.png)

**Platform**
Windows 10 Chrome

**Additional context**
N/A

**Comment by tmcconechy** [comment]
This issue is solved on main https://main-enterprise.demo.design.infor.com/ as it was an example issue only

**Comment by janahintal** [comment]
QA Passed. Thanks!
![image](https://user-images.githubusercontent.com/45757016/162142950-904df99a-04c1-4b44-8e9f-1d3f87cf634e.png)
