### ISSUE TITLE
Message: Spacing Issue

### ISSUE THREAD

**Issue by GlenlieMaye** [infor-design/enterprise#6263]
**Describe the bug**
Space between line and text is missing

**To Reproduce**

1. Go tohttps://4620-beta0-enterprise.demo.design.infor.com/components/message/example-index.html
2. Scroll down to 'Message' component
3. Click 'Error Example' button

**Expected behavior**
Text should be placed at the center of the alert message box

**Version**

- ids-enterprise: v4.62.0-beta.0

**Screenshots**
![image](https://user-images.githubusercontent.com/102151352/161745170-8a701a4e-44c6-4d93-b5e1-75cfd0c09b20.png)

https://user-images.githubusercontent.com/102151352/161744626-165962ec-648b-4e8a-bf88-23b7c0dd0374.mov

https://user-images.githubusercontent.com/102151352/161744820-e241ce7b-8349-4e87-8259-cfab05e1e580.mov

**Platform**
Device: iPhone 13, Samsung S22 and S22 Ultra
OS Version: IOS 15, 15.3 and Android Version 12
Browser Name: Safari, Chrome, Firefox and Samsung Internet Browser

**Comment by tmcconechy** [comment]
I tried to reproduce this in chrome with variations on the dev tools but cant seem to reproduce it? Can you reproduce there?

<img width="565" alt="Screen Shot 2022-04-05 at 9 13 22 AM" src="https://user-images.githubusercontent.com/814283/161761783-e2043920-5df1-4d89-8714-1dfc1d94acc1.png">

**Comment by GlenlieMaye** [comment]
QA tested and passed

Thank you, @tmcconechy!

iPhone 13 v15
![image](https://user-images.githubusercontent.com/102151352/162211829-c5047427-64b3-4020-be85-b15c341609fb.png)

Samsung Galaxy S22 Ultra v12
![image](https://user-images.githubusercontent.com/102151352/162212592-91a91dba-dfa1-47bd-9963-8aed6f4e893b.png)
