### ISSUE TITLE
CAP: Not able to show a notification badge on a CAP

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6264]
**Describe the bug**
It seems its not possible to show a notification on a CAP. Need more css for this in notification code.

**To Reproduce**
1. Unzip the attached into notification or cap examples and run
1. See error
2. start the browser at mobile size or smaller size -> text is missing

[example-notification.html.zip](https://github.com/infor-design/enterprise/files/8418345/example-notification.html.zip)

**Expected behavior**
Notification should be flush at the top.

**Version**
- ids-enterprise: [e.g. v4.62]

**Screenshots**

![Screen Shot 2022-04-05 at 9 08 16 AM](https://user-images.githubusercontent.com/814283/161760840-c0882f0f-a08c-41fb-a523-e85f12bcd513.png)

![Screen Shot 2022-04-05 at 9 09 02 AM](https://user-images.githubusercontent.com/814283/161760924-8784baf7-4a0f-4b29-a785-ed022b42e802.png)

**Comment by davidcarlsonberg** [comment]
Looks like this is more than just a CSS issue. The text inside the notification is attempting to adhere to multiple changing widths as the modal opens.

**Comment by tmcconechy** [comment]
OK, i think we need to make it work somehow... One way or the other

**Comment by GlenlieMaye** [comment]
QA tested and passed. Moving this ticket to Done.

![image](https://user-images.githubusercontent.com/102151352/166208744-0e39d51e-9c95-41ec-bafd-27bf1b37d560.png)
![image](https://user-images.githubusercontent.com/102151352/166208898-6b40bbf9-62ee-409a-918f-614e15ba87d3.png)

https://user-images.githubusercontent.com/102151352/166216967-861dbb4c-1479-4db0-abb1-c19dd533ee24.mov
