### ISSUE TITLE
SinkPage: Single select lookup size issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6265]
**Describe the bug**
Customers (small) does not have the right size

**To Reproduce**

1. Go to https://4620-beta0-enterprise.demo.design.infor.com/
2. Scroll into lookup element
3. See error

**Expected behavior**
<img width="429" alt="image" src="https://user-images.githubusercontent.com/56722184/161759995-27915538-2bf6-49a8-b0b1-f6cf84cd6390.png">

**Version**

- ids-enterprise: v4.62.0-beta0

**Screenshots**
<img width="539" alt="image" src="https://user-images.githubusercontent.com/56722184/161760047-a922807b-aea3-4219-a872-dbf9889c4d6a.png">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@jbrcna I'm not following this issue:

a) I dont see anything wrong with the screen shots
b) not sure what you mean by scroll in the lookup
c) Also do you see it here https://4620-beta0-enterprise.demo.design.infor.com/components/lookup/example-index.html

**Comment by tmcconechy** [comment]
Oh i see - you just mean on the kitchen sink its not small..

**Comment by jbrcna** [comment]
> @jbrcna I'm not following this issue:
> 
> a) I dont see anything wrong with the screen shots 
b) not sure what you mean by scroll in the lookup 
c) Also do you see it here https://4620-beta0-enterprise.demo.design.infor.com/components/lookup/example-index.html

a. it's the size of costumer small lookup 

b. sorry i meant move to or scroll down to locate lookup

c. no I don't see it in the example page.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/56722184/161879391-7642ef17-2c9d-4c58-bd2c-3160e372b5c1.png">

**Comment by tmcconechy** [comment]
Got it @jbrcna -> i fixed it on main now should be ok https://github.com/infor-design/enterprise/pull/6269

**Comment by tmcconechy** [comment]
This issue is solved on main https://main-enterprise.demo.design.infor.com/ as it was an example issue only

**Comment by jbrcna** [comment]
Thanks @tmcconechy . this is now working as expected.
https://main-enterprise.demo.design.infor.com/
<img width="857" alt="image" src="https://user-images.githubusercontent.com/56722184/162141240-61072e8d-8311-4c81-ac92-c65da0fd2a8a.png">
