### ISSUE TITLE
SinkPage: colorpicker alignment issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6266]
**Describe the bug**
when you choose a color. the color was misaligned

**To Reproduce**

1. Go to https://4620-beta0-enterprise.demo.design.infor.com/
2. Scroll to color picker
3. Change color

**Expected behavior**
should be able to change color with no issue

**Version**

- ids-enterprise: v4.62.0-beta0

**Screenshots**
<img width="295" alt="image" src="https://user-images.githubusercontent.com/56722184/161761311-65cf1ff8-85fd-4b91-b4f9-317a02909ff9.png">

**Platform**
Chrome Mac

**Additional context**

**Comment by tmcconechy** [comment]
Note that this only happens on the kitchen sink and not the color picker page

**Comment by jbrcna** [comment]
Thanks @tmcconechy . this is now working as expected.
https://main-enterprise.demo.design.infor.com/
<img width="328" alt="image" src="https://user-images.githubusercontent.com/56722184/162140455-9db9ded7-d7c5-4e64-8d5f-4a5d11a39bec.png">
