### ISSUE TITLE
SinkPage: accordion animation issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6268]
**Describe the bug**
the animation of accordion is much faster now.

**To Reproduce**

1. Go to https://4620-beta0-enterprise.demo.design.infor.com/
2. Scroll to Accordion
3. Click to see animation

**Expected behavior**
![Large GIF (738x414)](https://user-images.githubusercontent.com/56722184/161764117-b760c85b-aace-4cdc-9798-be02ca9c9c33.gif)

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![Large GIF (738x414)](https://user-images.githubusercontent.com/56722184/161764268-96eaba11-de6c-4a5d-b208-4559363ccc37.gif)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
This last worked on https://4580-enterprise.demo.design.infor.com/components/accordion/example-index.html
