### ISSUE TITLE
Column charts: Add "yAxis" option setting

### ISSUE THREAD

**Issue by cshirole** [infor-design/enterprise#627]
The column and column grouped charts do not include the yAxis setting that the line chart has.

Use Case:
I wanted to display only whole numbers in yAxis of my column chart e,g. "1, 2, 3, 4 ...", but sometimes I see decimals e,g. 0.1, 0.2, 0.3 - would like to format these out.

- [ ] Add the yAxis setting and example formatting yAxis to the enterprise components

**Comment by brianjuan** [comment]
http://4110-beta0-enterprise.demo.design.infor.com/components/column/test-axis-y-format-integer.html
http://4110-beta0-enterprise.demo.design.infor.com/components/column-grouped/test-axis-y-format-integer.html
http://4110-beta0-enterprise.demo.design.infor.com/components/column-stacked/test-axis-y-format-integer.html
Passed QA testing across all browsers.
