### ISSUE TITLE
Datepicker: Arabic locale time issues

### ISSUE THREAD

**Issue by xqses** [infor-design/enterprise#6270]
**Describe the bug**
Two scenarios fail when using the datepicker + timepicker component in an islamic locale. When picking a new time without picking a new date, the new date will be incorrect on the input field change event. (This event triggers things like updating [(ngModel)] bindings, which is a situation where the bug appears in practice). The issue does not seem to be happening if we pick a date before picking a time, and it seems to be resolved by itself when the date is saved and the timepicker is closed. 

**To Reproduce**
Pre-condition:
1. Set locale to Arabic (Saudi Arabia)
or
Set both language and locale to Arabic (Saudi Arabia)

**Scenario 1**
1. Go to [the reproducible example](https://stackblitz.com/edit/ids-enterprise-4610-ftsgpq?file=index.js).
2. Make sure the input field is cleared.
3. Open the datepicker - when opening the datepicker the date should be correct.
4. Do not select any date.
5. Pick a new time.
6. The value of the datepicker element will be incorrect when the change event emits. 
7. Using the input field date array in the umalquraToGregorian method will return null (because a date like 2022-04-05 does not exist in umalqura) 

**Scenario 2**
1. Open the datepicker
2. Pick any date and save it
3. Open the datepicker
4. Do not pick any date, pick only a new time
5. See steps 6 and 7 above.

**Expected behavior**
Both scenarios: When the change event emits, the input field value should be the current date but with the new time picked.

**Version**
- ids-enterprise: v4.61.0 (also appears in previous versions)

**Screenshots**
[Reproducible code for scenario 1.](https://stackblitz.com/edit/ids-enterprise-4610-ftsgpq?file=index.js)
[Imgur GIF for scenario 1](https://imgur.com/a/0IpmL8Z)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10/11

**Additional context**
First reported in Feb 2021, so it's been around a while.

**Comment by jbrcna** [comment]
QA Passed.  v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/datepicker/test-datepicker-arabic.html
<img width="767" alt="image" src="https://user-images.githubusercontent.com/56722184/170316288-6139f957-518c-4ef1-bb2d-c3297f7f6290.png">
