### ISSUE TITLE
Search/Header: Fix responsive behavior

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6271]
**Describe the bug**
The category search in the header in responsive mode needs to be corrected.

**To Reproduce**

1. Go to https://4620-beta0-enterprise.demo.design.infor.com/components/header/example-toolbar-flex-with-categories.html
2. Resize the page until the search field looks responsive.
3. See error
4. Focus the search 
5. See error

**Expected behavior**
Should look like this in both cases https://www.figma.com/file/gS5jIE14am8hYEvmtIAXLv/Search_Enhancements?node-id=66%3A1935#175458056

![Screen Shot 2022-04-05 at 3 39 12 PM](https://user-images.githubusercontent.com/814283/161836069-6c22f034-87a4-4f44-9bb7-21a6d2d2a3db.png)

**Screenshots**
![Screen Shot 2022-04-05 at 3 38 07 PM](https://user-images.githubusercontent.com/814283/161835937-8e3477ce-6fa5-4741-a309-ef7a171eed61.png)
![Screen Shot 2022-04-05 at 3 38 01 PM](https://user-images.githubusercontent.com/814283/161835939-d4df462d-5642-4847-a2a8-c3dd81f8d6ea.png)

**Additional context**
[Add any other context about the problem here.
](https://github.com/infor-design/enterprise/issues/6047)

**Comment by tmcconechy** [comment]
@kevinwhitedesign should we "get rid" of the expand/collapse design on https://4620-beta0-enterprise.demo.design.infor.com/components/header/example-toolbar-flex-with-categories.html 

It does give the ability to use the buttons.. So this might need more thinking?
![Screen Shot 2022-04-05 at 3 40 51 PM](https://user-images.githubusercontent.com/814283/161836400-75fda045-7357-4ddf-bc76-fb8774f1c727.png)

**Comment by janahintal** [comment]
QA Passed, Verified in https://main-enterprise.demo.design.infor.com/components/header/example-header-with-multiple-buttons-and-searchfield.html?theme=classic&mode=dark&colors=2578a9 
https://main-enterprise.demo.design.infor.com/components/header/example-toolbar-flex-with-categories.html

![image](https://user-images.githubusercontent.com/45757016/177525268-a31b0d72-3292-45bb-a88c-e1b16c925848.png)
![image](https://user-images.githubusercontent.com/45757016/177525303-8b3a743f-4a05-4509-a14d-2fa2bd6ab8a4.png)
![image](https://user-images.githubusercontent.com/45757016/177526114-b8855220-059a-4a74-b99a-ca8db67568be.png)
![image](https://user-images.githubusercontent.com/45757016/177526444-7e0ec9e9-c698-409c-9721-3e4a369fe081.png)
