### ISSUE TITLE
CAP: Close button not working

### ISSUE THREAD

**Issue by GlenlieMaye** [infor-design/enterprise#6274]
**Describe the bug**
Close button in example-trigger not working

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-trigger.html
2. Click on 'Contextual Action Panel - Manual Trigger' button
3. Click 'Close' button

**Expected behavior**
Pop-up window should be closed when the user click the close button

**Version**

- ids-enterprise: v4.63.0-dev

**Screenshots**

https://user-images.githubusercontent.com/102151352/161880780-70fc550a-6aae-400d-8740-a17cd1a77e7f.mov

**Platform**
Device: iPhone 13 v15 and v15.3
OS Version: Windows 11
Browser Name: chrome, safari, firefox and edge

**Comment by tmcconechy** [comment]
Just an issue with that example - no big deal

**Comment by GlenlieMaye** [comment]
QA tested and passed. Moving this ticket to done.

https://user-images.githubusercontent.com/102151352/163977492-fa654659-374e-44db-beff-73801a097df7.mov
