### ISSUE TITLE
Sink Page: Toolbar doesn't rendered properly in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6277]
**Describe the bug**
Sink Page: Toolbar doesn't rendered properly in responsive view

**To Reproduce**

1. Go to https://4620-beta0-enterprise.demo.design.infor.com/?theme=new&mode=dark&colors=0066D4
2. Scroll to Toolbar section
3. Minimize the screen to responsive view

**Expected behavior**
Toolbar should render properly

**Version**
4.63-ids-beta

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/161947915-6b8d1128-094f-43e7-bb32-78bcf9a4bea2.png)

**Platform**
Windows 10 
Firefox 
Chrome 

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Closing stale issues
