### ISSUE TITLE
Refactor all inline styles out.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#628]
**Describe the bug**

One problem is that our current CSP policy uses insafe inline for styles. We still need to do this because of the following reasons.. #256 Fixed many inline styles but the remaining issues exist as a continuation. We need to:

- [ ] need to remove any inline styles from all samples (fx display: none -> class hidden)
- [ ] need to remove any other inline styles from all samples (move to a script tag which has a nonce or use class)
- [ ] datagrid column widths use inline style for width. this needs to be refactored to use CSSDOM (and may make it slower)
- [ ] editor pasting html needs to somehow use CSSDOM (may be tricky)
- [ ] dragging/dropping code needs to be refactored to use CSSDOM (and may make it slower)
- [ ] search for `style=` in all .js files and fix those components (completion-chart, column, editor, tree should be simple to use CSSDOM)
- [ ] search for `style=` in all .html files 
- [ ] Consider a "bypassSecurity" setting for things like editor to avoid stripping.

**To Reproduce**
1. Go to csp-handler.js
2. Change it to `style-src': [ 'self', `nonce-${res.opts.nonce}`]`
3. Restart server
4. Go to any page fx kitchen sink, datagrid or 

**Expected behavior**
All pages should run with no csp errors without unsafe-inline styles.

**Workaround**
For now, running with this limitation of needing unsafe-inline.

**Comment by EdwardCoyle** [comment]
two things:

> need to remove any inline styles from all samples (fx display: none -> class hidden)

Some of the demos have inline styles that are specific to said demo.  The demoapp has SASS files inside of `app/src/sass` that are built and served whenever the app's run.  All important inline styles should probably make their way into this folder, with the following guidelines:
   - Try to generalize styles if possible, for reuse between tests.
   - If styles can't be generalized, make some CSS comments above these specific styles to point out where they are used by the app (use the URL of the demo/test to label it)

> need to remove any other inline styles from all samples (move to a script tag which has a nonce or use class)

Can `<style>` tags also contain a nonce?  Is that valid?  If so, maybe we should try that?

**Comment by tmcconechy** [comment]
Yes, i made style tags have a nonce in the Veracode PR. I started down this path but found it was much bigger than expected so its about 50% done on that PR. But general idea is if styles are needed in the demo they should go in style tag in that page or replaced with a class if we have one that will do it.

**Comment by karinpb** [comment]
Can we use nonce with IDS? Or do we need to wait for this ticket?

**Comment by tmcconechy** [comment]
You can use a nonce on the style sheet but the code is still adding inline css so it won’t help. The only solution is to use an exception for inline css for now. Our 5.0 will have this covered (will be a little while though)

**Comment by tmcconechy** [comment]
Closing this issue. We have setup version 50 (Web components) to not have any inline styles and it and we are fixing it in there but it will be awhile before all components are ported over and released
