### ISSUE TITLE
Unit Testing: Create a Puppeteer Script for "SearchField: White toolbar search field background"

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#6282]
Describe the Issue
Create a unit testing for "SearchField: White toolbar search field background".

See attached BDD for more information.
[BDD_github#5865.docx](https://github.com/infor-design/enterprise/files/8512560/BDD_github.5865.docx)

Related github issue
#5865

**Comment by maezcruz** [comment]
Cc: @CindyMercadoReyes

**Comment by ericangeles** [comment]
@maezcruz I was wondering, how do we come up with the BDD on #5865? That issue is not yet been fixed. As far as I know, BDDs were only created once an enhancement has been done.

**Comment by maezcruz** [comment]
@ericangeles Ill check with the team. Will make necessary changes to the ticket once confirmed. Thanks.
