### ISSUE TITLE
Spinbox defects

### ISSUE THREAD

**Issue by pbal** [infor-design/enterprise#6291]
**Describe the bug**
Found some issues with step and min/max in datepicker

**To Reproduce**
Bug One
1. Go to app/views/components/spinbox/example-index.html
2. Change to `$(element).spinbox({min: 0, max: 10, step: 2})`
3. Run and click +
4. See error -> not doing step 2

Bug Two
1. Go to app/views/components/spinbox/example-index.html
2. Change to `$(element).spinbox({min: 20, max: 30})`
3. Run and click +
4. See error -> not starting at 20

**Expected behavior**
Follows the settings..

**Version**
- ids-enterprise: [e.g. v4.60.2]

**Screenshots**
![image](https://user-images.githubusercontent.com/1594975/162612503-21b4c2de-d91c-4775-8b8f-6331869f9fed.png)

**Platform**
- Chrome/Any

**Comment by tmcconechy** [comment]
@pbal are these things you would actually use or just minor bugs? Asking in terms of prioritization. Also please follow the templates for issues. I had to sort of guess in the steps if but i can see these cases dont work.

**Comment by pbal** [comment]
Will do template going forward.

Not an emergency, but I hope these defects would be solved soon as they affect core functionality of the component.

**Comment by tmcconechy** [comment]
Closing stale issues
