### ISSUE TITLE
Datagrid: Unable to scroll in mobile in frozen columns example

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6293]
**Describe the bug**
Datagrid: Unable to scroll in mobile in frozen columns example

**To Reproduce**

1. Open mobile browser
2. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-frozen-columns.html
3. Scroll right to see other columns

**Expected behavior**
Should be able to scroll left and right 

**Version**
4.63-ids-dev

**Screenshots**
N/A

**Platform**
Mobile Devices Apple and Android 

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Closing stale issues
