### ISSUE TITLE
Datagrid: Incomplete columns on exported files

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6294]
**Describe the bug**
Datagrid: Incomplete columns on exported files

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-export-from-button.html
2. Remove Product name column
3. Export file on both CSV and Excel file

**Expected behavior**
Downloaded file should have the same column as displayed in IDS

**Version**
4.63-dev-ids

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/162724026-76cb5511-45f5-4be7-b8b8-196123429bcf.png)

**Platform**
All major browsers, OS and devices

**Additional context**
N/A

**Comment by tmcconechy** [comment]
@janahintal this isnt a bug it is possible to set some columns to not exportable. And the code shows which ones are not going to appear in the export https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/example-export-from-button.html#L87

So its correct
