### ISSUE TITLE
Validation: Validate on submit is not working as expected

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6296]
**Describe the bug**
Validation: Validate on submit is not working as expected

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/validation/example-validate-on-submit.html 
2. Type invalid email
3. Empty other fields
4. Click Submit

**Expected behavior**
Validation should show upon submit

**Version**
4.63-ids-dev

**Screenshots**

**Platform**
All major Browser, OS and Devices. 

**Additional context**
N/A

**Comment by janahintal** [comment]
Hi @davidcarlsonberg, the issue still exists for 'Code' field. 

![image](https://user-images.githubusercontent.com/45757016/163801205-721a2b00-a8e2-4e5e-98f5-8ffd999b95ee.png)

**Comment by davidcarlsonberg** [comment]
Looks like that first 'Code' field is not required so I would say this example is working as expected. Happy to address this though if that's an incorrect assumption.

**Comment by tmcconechy** [comment]
Yeah I think we are trying to show one field in between thats not validated to mix it up. So i think this is fine as is
