### ISSUE TITLE
Donut Chart: Legend selected highlight issue

### ISSUE THREAD

**Issue by GlenlieMaye** [infor-design/enterprise#6301]
**Describe the bug**
Highlight for selected legend is overlapping with the legend and legend color

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-single-widget.html
2. Click on any legend

**Expected behavior**
Highlight for legends should be placed accordingly as expected

**Version**

- ids-enterprise: v4.63.0-dev

**Screenshots**
<img width="835" alt="image" src="https://user-images.githubusercontent.com/102151352/163181571-e3b72335-8286-4a9d-9460-182c809abb77.png">

https://user-images.githubusercontent.com/102151352/163180888-17b6e17d-aa48-44b8-9b70-2df6e3f0ead8.mov

**Platform**
 - Device: iPhone 13 v15 and v15.3
 - OS Version: Windows 11
 - Browser Name: Chrome, Safari, Stock Browser

**Additional context**
N/A

**Comment by tmcconechy** [comment]
@davidcarlsonberg maybe can you take another look at this it was fixed on https://github.com/infor-design/enterprise/issues/6113 but still seeing a similar issue as noted

**Comment by GlenlieMaye** [comment]
QA tested and passed. Moving this ticket to Done.

https://user-images.githubusercontent.com/102151352/166182909-57d733ac-0073-4401-bfc4-43b5cf1ae700.mov
