### ISSUE TITLE
Datagrid: checkbox column header changes color

### ISSUE THREAD

**Issue by Annfo637** [infor-design/enterprise#6303]
**Describe the bug**
When selecting a checkbox in the datagrid, the column header changes color. The color also stays changed when unselecting the checkbox again. See attached screenshot with example from https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-multiselect?theme=new&mode=dark&colors=0066D4 running IDS version 4.62.0. 

The change in color is even more obvious in our own project in all themes, attaching screenshots for this. Our project is running IDS version 4.59.2.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-multiselect?theme=new&mode=dark&colors=0066D4.
2. Select a row in the data grid.
3. See the column header color change.
4. Unselect the checkbox.
5. Column header color is still changed (i.e. not the same as the rest of the header).

**Expected behavior**
The checkbox column header should be the same as the rest of the header.

**Version**

- ids-enterprise: 4.59.2 and 4.62.0

**Screenshots**
![image](https://user-images.githubusercontent.com/54262041/163344341-9d52413a-f286-43fa-9438-08928d1a6aa7.png)
![image](https://user-images.githubusercontent.com/54262041/163344770-c31134eb-71e0-4b82-a551-83ebb4e07d0a.png)

**Platform**
 - Infor Application/Team Name: User Productivity
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 99.0.4844.82 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
This is as designed. The idea is that its showing you the active column that your in. But we did decide to remove this in the upcoming future web component version https://main.wc.design.infor.com/ids-data-grid/

Will park this for now

**Comment by Annfo637** [comment]
Thanks Tim, I get the concept and that's great, but it's not **looking** great though...sorry for being honest.

**Comment by tmcconechy** [comment]
I don't disagree which is why we removed it in the new version. Also it is an extra expensive DOM query so slows it down a bit having it. I think we can easily just remove so adding it to grooming

**Comment by Annfo637** [comment]
Great :) Does this mean it will be removed in the 4.63.x version?

**Comment by tmcconechy** [comment]
No possibly 4.64 however. Add to review/discuss in the next sprint planning but i dont see why anyone would argue about it

**Comment by Annfo637** [comment]
Ok, thanks Tim!

**Comment by tmcconechy** [comment]
Ok - Can we make this an option @ericangeles - default to off

**Comment by ericangeles** [comment]
@tmcconechy sure

**Comment by GlenlieMaye** [comment]
QA tested and passed. Moving this ticket to Done.
https://main-enterprise.demo.design.infor.com/components/datagrid/example-multiselect?theme=new&mode=dark&colors=0066D4

https://user-images.githubusercontent.com/102151352/169430044-99c19f1d-930b-43a5-96fc-10729e223e59.mov
