### ISSUE TITLE
TargetedAchievement: Add Support for Tooltip on icon

### ISSUE THREAD

**Issue by bveerabathini** [infor-design/enterprise#6308]
**Is your feature request related to a problem or use case? Please describe.**
Feature request suggested by  UX Design team to have tooltip on icon on 'targeted-achievement' chart.

**Describe the solution you'd like**
tooltip to be shown when hover on icon on 'targeted-achievement' chart.

**Describe alternatives you've considered**
None
**Additional context**
<img width="367" alt="image" src="https://user-images.githubusercontent.com/85981034/163763978-c2c5fbb3-140e-4425-adbb-4f6867052798.png">

**Comment by tmcconechy** [comment]
I would add:

- a tooltip option for a string tooltip
- tooltipSettings options to pass through for more configuration

**Comment by jbrcna** [comment]
QA Passed. v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/targeted-achievement/example-index.html
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/56722184/167771699-fcd3c53d-2a6b-485e-8019-3d8b57b2eb01.png">

**Observation:**
the icon is cut off when using `firefox` browser` classic theme`. let me know if I should file a new issue. @tmcconechy , @ericangeles 
<img width="939" alt="image" src="https://user-images.githubusercontent.com/56722184/167771827-48f6cecf-7323-49a6-9be9-1267cee9431a.png">

**Comment by ericangeles** [comment]
@jbrcna yeah we can file it as a minor bug.

**Comment by jbrcna** [comment]
thank you @ericangeles

**Comment by CindyMercadoReyes** [comment]
BDD attached.
[BDDStory_github#6308.docx](https://github.com/infor-design/enterprise/files/8680358/BDDStory_github.6308.docx)
