### ISSUE TITLE
Datagrid: Modal mouse scrolling not available after clicking Dropdown

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#6311]
**Describe the bug**
Hi, when running Datagrid inside Modal and one of the fields is Dropdown, after clicking it, the mouse scroll event on Datagrid is not scrolling.

**To Reproduce**

1. Run a Datagrid with many items on Modal causing it to have a scrollbar.
2. Add a `Formatters.Dropdown` field
3. Open the modal, see that mouse scroll is working
4. Click on one of the Drop down fields focus back to the grid
5. Try scrolling again with the mouse

Please see an example: [https://jsfiddle.net/sebulbajoe/hx1z0kat/9/show](https://jsfiddle.net/sebulbajoe/hx1z0kat/9/show)

**Expected behavior**
Mouse scroll event should scroll on datagrid even when dropdown was clicked

**Version**

- ids-enterprise: v4.61.1

**Screenshots**
Code when loading the modal:
![image](https://user-images.githubusercontent.com/34129313/163800028-dd39eb13-b9fa-4baa-8000-1206dcd09c45.png)
After clicking on Dropdown this style (surrounded yellow) is added:
![image](https://user-images.githubusercontent.com/34129313/163800228-ca4aeb87-7bea-414e-bf13-d94f40a8a922.png)

**Platform**
 - Browser Name: Chrome/Firefox 
 - Browser Version: Latest

**Additional context**
Thanks

**Comment by tmcconechy** [comment]
Not sure i understand this one. Im not having any problems scrolling the modal with the dropdown open or closed after using it.

However, if you made the scrolling happen on the datagrid (by setting a height) the dropdown would actually close when you scroll the datagrid? Is that the issue?

**Comment by jonathanamiran** [comment]
The datagrid is not set by any height. After opening dropdown (and closing it), I cannot scroll with mouse wheel, same Chrome/Firefox/Edge same behavior. If the mouse pointer is hovering over the scrollbar then the mouse wheel scrolls.
Hope this clarifies, thanks.

**Comment by tmcconechy** [comment]
Ok maybe we need to test it on a PC... I would think you would want to try to scroll in side the grid not the modal, perhaps that would help..

But its not even scrolling in this example:
https://main-enterprise.demo.design.infor.com/components/datagrid/example-modal-datagrid.html

General idea https://main-enterprise.demo.design.infor.com/components/datagrid/example-fixed-header.html

**Comment by jonathanamiran** [comment]
If I run `$(".datagrid-wrapper").css("overscroll-behavior","")` it "fixes" it until I click once more on the dropdown, then I need to run this code again.
Indeed I've tested it in two PCs, unfortunately I don't have a Mac :) 

My JSFiddle example was based on "example-modal-datagrid.html" in which I added more data to make it scroll.

Thanks!

**Comment by tmcconechy** [comment]
ok i see - yeah not sure if that class is needed or not. But it should go away when you close and it doesnt.

**Comment by tmcconechy** [comment]
Sure the advantage is that the header stays fixed

**Comment by Sovia** [comment]
Hi @tmcconechy This is also an issue for a datagrid not in a modal, where the overscroll-behavior rule stays and the mouse wheel isn't working when hovering over the datagrid. Since this doesn't happen for other filter types, it's being reported as a bug, This is happening on PC. It doesn't look like the css class gets cleaned up when the dropdown is closed?
