### ISSUE TITLE
Swipe Action: Scroll bar issue

### ISSUE THREAD

**Issue by Henriko24** [infor-design/enterprise#6312]
**Describe the bug**
 - There is a scroll bar that appears on Mozilla Firefox that other browser doesn't have.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/swipe-action/example-index.html
2. And then you can see the error 

**Expected behavior**
 - Should have no scroll bar or doesn't appear scroll bar

**Version**

- ids-enterprise:  v4.63.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/102222379/163975389-8e2ba3e6-ce61-4a42-93dc-3cedae8b45a5.png)

**Platform**
 - Browser Name: Mozilla Firefox
 - Browser Version: 99.0.1 (64-bit)

**Additional context**
NA

**Comment by tmcconechy** [comment]
There is an easy fix for this. Pushed on the linked Pull Request

**Comment by Henriko24** [comment]
QA passed on v4.63.0-dev. moving this ticket to Done. Thank you.
https://main-enterprise.demo.design.infor.com/components/swipe-action/example-index.html
![image](https://user-images.githubusercontent.com/102222379/165432012-429d5f26-bb97-4546-99dc-a0b3be786718.png)
Mozilla Firefox
