### ISSUE TITLE
DataGrid: Focus lost in cell after selecting date in calendar

### ISSUE THREAD

**Issue by hsubtain** [infor-design/enterprise#6317]
**Describe the bug**
Focus is lost on data grid cell when selecting a date from the date picker cell via the calendar 

**To Reproduce**
I was able to reproduce the behavior in Edge and google chrome only, it was working as expected in Mozilla FF 98.0.2 (64-bit).

Steps to replicate
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-datetime.html
2. Click on product id cell 
3. Navigate to order date 2 cell by pressing right arrow key
4. Click enter on order date 2 cell
5. Press arrow down 
6. Select date in calendar by pressing enter

Actual Result: Focus is lost on cell date picker after selecting a date in calendar

**Expected behavior**
Focus is retained on cell after selecting date from calendar

**Version**

- ids-enterprise: 4.63.0-dev

**Screenshots**
![LSF-42418 focust lost on date field](https://user-images.githubusercontent.com/100820299/164180978-4cd26d00-8220-47b6-98a6-804267814fc4.gif)

**Platform**
 - Infor Application/Team Name: Lawson System Foundation (Portal Team)
 - MS Edge - Version 100.0.1185.44 (Official build) (64-bit)
 - Google Chrome - Version 100.0.4896.88 (Official Build) (64-bit)

**Comment by GlenlieMaye** [comment]
QA tested and passed. Moving this ticket to Done.
https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-datetime.html

https://user-images.githubusercontent.com/102151352/168723958-35bda9f3-d1ed-41f7-b776-ee429bc28062.mov
