### ISSUE TITLE
Tabs Module: Search menu looks off in responsive view 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6320]
**Describe the bug**
Tabs Module: Search menu looks off in responsive view 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html and https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html and https://main-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html
2. Minimize the screen 
3. Type in search 
4. Click the search button

**Expected behavior**
Search button should look fine

**Version**
4.63-ids-dev

**Screenshots**
https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html
![image](https://user-images.githubusercontent.com/45757016/164411731-de64598b-9c4b-4fc2-b776-2e8e240109d2.png)

https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html
![image](https://user-images.githubusercontent.com/45757016/164422212-92d4e70a-bead-4808-ab1e-46893e0ab0dc.png)

https://main-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html
![image](https://user-images.githubusercontent.com/45757016/164422437-72a51bf8-a73f-4ebc-9316-870df89e39c5.png)

**Platform**
Windows Chrome and all other major browser and devices. 

**Additional context**
N/A

**Comment by GlenlieMaye** [comment]
_Failed_ -- Search field still looks off in Mozilla Firefox
https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html
![image](https://user-images.githubusercontent.com/102151352/166219952-f7e8e894-7414-4146-8cfa-6a0b4ef1bd38.png)
![image](https://user-images.githubusercontent.com/102151352/166220338-2a6bc2ba-2d52-4fd0-9ee1-993dbaabe369.png)


https://user-images.githubusercontent.com/102151352/166219403-41c88705-3194-447b-b053-be8cca0c419a.mov



_Failed_ -- Misaligned close button
https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html
![image](https://user-images.githubusercontent.com/102151352/166217648-6a97884a-e3b2-42ce-a7ce-8551796bf33a.png)

_Failed_ -- Misaligned close button
https://main-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html
![image](https://user-images.githubusercontent.com/102151352/166218281-513cfedb-508d-4ea5-a78f-b16a5c24f8d4.png)
