### ISSUE TITLE
Field Filter: Filter icon dropdown box issue

### ISSUE THREAD

**Issue by GlenlieMaye** [infor-design/enterprise#6321]
**Describe the bug**
Filter icon dropdown box is not rendering consistently upon changing mode from 'Light' to 'High Contrast' (_applicable to all examples_)

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-filter/example-index.html?theme=new&mode=light&colors=0066D4
2. Change from 'Light' to 'High Contrast' Mode
3. Notice the filter icon dropdown box

**Expected behavior**
Filter icon dropdown box should be consistently rendered upon changing from 'Light' to 'High Contrast' Mode

**Version**

- ids-enterprise: 4.63.0-dev

**Screenshots**

_Light Mode_
![image](https://user-images.githubusercontent.com/102151352/164434479-2ba418f4-27ed-4b14-8da9-c901ea608e66.png)

_Dark Mode_
![image](https://user-images.githubusercontent.com/102151352/164434599-3c82580e-adf7-4fa4-ac8a-2a32b84a8b3b.png)

_High Contrast Mode_
![image](https://user-images.githubusercontent.com/102151352/164434725-e368310c-1b4d-466c-90ab-6379f29f549b.png)

**Platform**
 - Browser Name: Chrome, Safari, Firefox, Edge

**Comment by tmcconechy** [comment]
Going to descope this because we are spending too much time on field filter when its actually not that commonly used if at all and was deprecated in the new version
