### ISSUE TITLE
Field Options: Misaligned magnifying icon

### ISSUE THREAD

**Issue by GlenlieMaye** [infor-design/enterprise#6323]
**Describe the bug**
Magnifying icon is misaligned when in compact mode

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-options/example-index.html#
2. Switch to 'Compact Mode'
3. Scroll down to 'Clearable Searchfield'

**Expected behavior**
Magnifying icon should be aligned accordingly

**Version**

- ids-enterprise: 4.63.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/102151352/164444393-62517814-7359-4da5-9584-c966122c220e.png)

**Platform**
Browser Name: Chrome, Safari, Firefox, Edge

**Comment by ericangeles** [comment]
I believe it's already been fixed here https://github.com/infor-design/enterprise/pull/6316

**Comment by GlenlieMaye** [comment]
QA tested and passed. Moving this ticket to Done.

![image](https://user-images.githubusercontent.com/102151352/165429036-e3f2593a-1b3f-4789-bc33-d61c3773db9c.png)
