### ISSUE TITLE
Blockgrid: Convert Protractor Tests to Puppeteer 

### ISSUE THREAD

**Issue by tjamesallen15** [infor-design/enterprise#6327]
**Is your feature request related to a problem or use case? Please describe.**
Convert blockgrid component tests to puppeteer.

**Describe the solution you'd like**
Convert all tests scenarios in protractor to puppeteer. For the naming can be, `{component}.puppeteer-spec.js`

**Describe alternatives you've considered**
N/A

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
