### ISSUE TITLE
Page Patterns: Header Issue

### ISSUE THREAD

**Issue by Henriko24** [infor-design/enterprise#6328]
**Describe the bug**
When I click the last part of the list item in the left side and go back to the top the header will be missing.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/page-patterns/example-list-detail.html
2. Click the last part of the list item and go back to the first item of the list
3. And then you can see the error.

**Expected behavior**
The header will be stay

**Version**

- ids-enterprise: 4.63.0-dev

**Screenshots**
![Normal Pic(Chrome)](https://user-images.githubusercontent.com/102222379/164680651-f4a22759-7b1a-4426-9aba-d3585cce2491.JPG) 
Chrome normal pic

![Error pic(Chrome)](https://user-images.githubusercontent.com/102222379/164680831-169c8294-07bc-4188-89cc-8019ce9467e2.JPG)
Error Chrome

![Normal Pic(Edge)](https://user-images.githubusercontent.com/102222379/164681018-8429147c-f5eb-41f2-b11c-cbba28103bc4.JPG)
Normal pic Edge

![Error pic(Edge)](https://user-images.githubusercontent.com/102222379/164680889-bdbd7eb9-5c1b-4cff-a119-f4f5479d348d.JPG)
Error pic Edge

https://user-images.githubusercontent.com/102222379/164681813-a672f936-5516-41a9-b8e4-041faefe965b.Mp4
Chrome and Edge 

**Platform**
 - Browser Name: Google Chrome, Edge
 - Browser Version: 100.0.4896.127 (Official Build) (64-bit), 100.0.1185.44 (Official build) (64-bit)

**Additional context**
- When I use VDI browser that is the result but when I use my browser it's work good

**Comment by tmcconechy** [comment]
I also cant reproduce in chrome. I see you mentioned VDI browser - first i heard of it we don't support it.
What can you tell me about it? Is it something you need or just testing it out?

**Comment by Henriko24** [comment]
> I also cant reproduce in chrome. I see you mentioned VDI browser - first i heard of it we don't support it. What can you tell me about it? Is it something you need or just testing it out?

@tmcconechy This is provided by infor, as an intern this is what I use because they did not provide the mac that I would use as an intern so they give me access to VDI.

**Comment by tmcconechy** [comment]
Ok, And its actually just a chrome browser in a VM? How might we get access to one for testing?
What chrome version is it (we only support R-2)?

We dont support VDI browsers - but if its just chrome im not sure why it wouldn't work unless its something like a lag/delay issue or an older version of chrome.

**Comment by ericangeles** [comment]
@tmcconechy I was able to replicate it. Try to make the browser smaller around `700px`? Then click the last item that you can see on the listview (since it doesn't have a scrollbar).

**Comment by iamjamesreyracho** [comment]
QA Passed. Moving this ticket to done. Thanks.
https://www.screencast.com/t/NiEUyNzS
