### ISSUE TITLE
Page Patterns: Color not function Issue

### ISSUE THREAD

**Issue by Henriko24** [infor-design/enterprise#6329]
**Describe the bug**
- When you click the 3 dots in the header and choose the color then click any color he does not work.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/page-patterns/example-toolbar-datagrid.html?
2. Click the 3 dots in the header 
3. And then click any color that you choose
4. And you can see that he doesn't work

**Expected behavior**
- The color that is chosen will appear in the header.

**Version**

- ids-enterprise: 4.63.0-dev

**Screenshots**
![Console](https://user-images.githubusercontent.com/102222379/164700177-bdd578c3-f94c-45ed-8400-59de3cc02381.JPG)
Console

https://user-images.githubusercontent.com/102222379/164700952-4f29e98b-ae38-4791-b6d7-2af194eafc7f.mp4

**Platform**
 - Browser Name: Google Chrome, Edge, Mozilla Firefox
 - Browser Version: 100.0.4896.127 (Official Build) (64-bit), 100.0.1185.44 (Official build) (64-bit), 99.0.1 (64-bit)

**Additional context**
- When I choose color and pick a color and pick again any color, you can see the 3 dots that appear the color that you choose previously before you pick again another color.

**Comment by tmcconechy** [comment]
@Henriko24 something doesn't match up here i tried the link on https://main-enterprise.demo.design.infor.com/components/page-patterns/example-list-detail.html and the feature works fine. No errors in the console. I tried both mac and pc chrome?

**Comment by tmcconechy** [comment]
Is this also VDI browser?

**Comment by Henriko24** [comment]
> Is this also VDI browser?

@tmcconechy  yes
