### ISSUE TITLE
SearchField: Additional fix from design changes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6331]
**Describe the bug**
Found some issues from the fall out of https://github.com/infor-design/enterprise/pull/6234

**To Reproduce**
1. Go to http://localhost:4000/components/header/example-searchfield-expanded.html
2. Notice the placeholder setting is set but that text is not visible - should be visible also in dark mode its cut off. Does the design have this focus state in it?
3. Focus the field - notice the border "shrinks" - should stay same size
4. Type so that the X appears - hover the X -> it disappears but should be darker

**Platform**
 - Chrome
 
**Additional context**
@ericangeles whats https://github.com/infor-design/enterprise/pull/6324/files about ? Do you think you can incorporate these fixes in that PR?

**Comment by ericangeles** [comment]
@tmcconechy yeah, I found some of these issues including the hovering the close button. I will add the solution to my current draft PR.

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to Done. However there were issues found with the alignment for https://4630-beta0-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html?theme=new&mode=light&colors=2578a9. Spoke to Tim about it and he will add the
![Seachfield Alinment is off](https://user-images.githubusercontent.com/39101346/166467054-b7dc8be9-1afa-4cc4-a6ba-91670070a089.png)
 fixes to it and then advise me when we can retest this ticket. Adding screen shot:
