### ISSUE TITLE
Form: Misaligned textbox

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6335]
**Describe the bug**
'Task Banner Image URL' textbox is misaligned with the other textboxes when in 'Compact Mode'.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/form/example-align-field-bottoms.html?theme=new&mode=light&colors=0066D4
2. Switch to 'Compact Mode'
4. Notice the 'Task Banner Image URL' textbox

**Expected behavior**
'Task Banner Image URL' should be aligned with the other textboxes when in 'Compact Mode'.

**Version**

- ids-enterprise: 4.63.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/102151352/165015058-7466fe97-32fb-4d02-80cd-659bd5765c27.png)

**Platform**
Browser Name: Chrome, Safari, Firefox, Edge

**Comment by tmcconechy** [comment]
Closing stale issues
