### ISSUE TITLE
Datagrid: Need a method that we can call to make cell editable

### ISSUE THREAD

**Issue by sjasaniel** [infor-design/enterprise#6338]
**Is your feature request related to a problem or use case? Please describe.**
When adding a new row, we'd like to request that the first cell in the datagrid (not the checkbox) to be editable. 

**Describe the solution you'd like**
A method that we can call to make the cell editable in the datagrid

**Additional context** 
(https://stackblitz.com/edit/ids-enterprise-qzzw8i?file=index.html)
![not_focused](https://user-images.githubusercontent.com/9715303/165051825-57705e00-9077-46c3-ab86-562b950836ab.gif)

As shown, we are setting column: 1 (not column 0), row: 0 as the active cell when adding a new row,  but we'd also like it to be editable without clicking / pressing enter / tabbing into the cell.

And what application do you work on? Landmark

**Comment by tmcconechy** [comment]
Did you try calling https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.js#L9793 ?
It should be the right one but it isnt presently public, so i think we might need to add the method to NG and make a public method `editCell` that doesnt need an event as an argument (just row, cell)

**Comment by tmcconechy** [comment]
Should it focus the cell when you go into edit mode?

So i think we might need to add the method to NG and make a public method called `editCell` that doesn't need an event as an argument (just row, cell).

**Comment by jbrcna** [comment]
QA Passed . v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-addrow-selected.html
![Large GIF (1376x516)](https://user-images.githubusercontent.com/56722184/170314779-7f3cd527-a131-4a67-ba98-159e854b0347.gif)

**Comment by GlenlieMaye** [comment]
QA tested and passed. Moving this ticket to Done.
https://main-enterprise.demo.design.infor.com/components/datagrid/test-addrow-selected.html

https://user-images.githubusercontent.com/102151352/170402414-28c07a8c-8604-443e-a749-2cde94b66f05.mov
