### ISSUE TITLE
Tabs Module: Searchfield with categories has some visual issues

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6348]
**Describe the bug**
Here's a list of the issues I am seeing on a searchfield with categories:
1. When assigning a theme color to the page, the new and light themes cause the Category button's icon to disappear
2. When typing in the searchfield in classic themes, the searchfield expands its height
3. When typing in the searchfield, the "X" button is overlapping the Go button

**To Reproduce**
1. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?theme=classic&mode=light&colors=2578a9
2. Note that the Category button's icon is not visible
3. Change the theme and mode in the URL to other options
4. Note that for the light and contrast modes, the Category button's icon is not visible
5. Start typing in the searchfield when in a classic theme
6. Note that the searchfield's height has expanded and the "X" button is hidden behind the Go button

**Expected behavior**
It is expected that the Category button's icon stays visible, the searchfield height wouldn't change, and that the "X" button is aligned inside of the searchfield while typing.

**Version**
- ids-enterprise: v4.63.0-dev

**Screenshots**
![Searchfield with category button](https://user-images.githubusercontent.com/76002134/165306682-82d8f308-7d52-484e-9057-b146f7917f8e.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows11
 - Browser Name: chrome
 - Browser Version: 100.0.4896.127 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
cc @ericangeles -> added this issue as we should probably straighten this out from the fallout of the changes / related issues

**Comment by CindyMercadoReyes** [comment]
Moving this ticket to Done. However there were issues found with the alignment for https://4630-beta0-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html?theme=new&mode=light&colors=2578a9.  Spoke to Tim about it and he will add the fixes to it and then advise me when we can retest this ticket.  Adding screen shot:
![Seachfield Alinment is off](https://user-images.githubusercontent.com/39101346/166466465-7a608a3c-c003-4cda-8959-43936402345b.png)
