### ISSUE TITLE
Datagrid - Header tooltip is center aligned 

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#6361]
**Describe the bug**
We observed that in datagrid header if we added tooltip for header by using "" attribute, it get center aligned. 
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/42198413/165755311-b899f6fa-a7e9-4163-adf1-2e08abd4960a.png)

**To Reproduce**

**Expected behavior**
Tooltip should be left align. 

**Version**
- ids-enterprise-ng: [v 4.60.0]

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@dhumalkishor 

Can you attach the code snippet where you added the tooltip? Im not clear on if its the cell or the header? I do see a problem on the header tooltips on https://main-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html I think it would be better on top.

Also we can add an option`tooltipSettings` to the grid column that can pass additional config settings to the tooltip so you could have it on the left? 

Concerning it being on the left can you make a screen shot of where you think it should be?

**Comment by dhumalkishor** [comment]
Please refer attached screenshot of code. 
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/42198413/165759810-76a1942b-2e18-4fb7-95db-c462ac08074f.png)

**Comment by tmcconechy** [comment]
Ok - what we will do is:

a) Fix the position of default header tooltiips to be on top and centered
b) add an `tooltipOptions` setting to the column so you can pass any setting to the tooltips on the column and do what you want with positioning and offsets
