### ISSUE TITLE
Datagrid: "Select all" checkbox doesn't reflect the current state correctly

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#6362]
**Describe the bug**
In a multiselect datagrid, the "select all" checkbox doesn't reflect the current state correctly.

**To Reproduce**

**First scenario:**
1. Go to https://ids-quick-start-1331-y8kmbt.stackblitz.io
2. Click on the "select all" checkbox.
3. Click on the "Add row" button (make sure that there are no rows in the grid before adding a new one, click on the "Clear" button to remove all rows).
4. Notice that the added row isn't selected but the "select all" checkbox is still selected.

**Expected behavior**
When adding the first row to a datagrid, the "Select all" checkbox should be de-selected.

**Second scenario:**
1. Go to https://ids-quick-start-1331-y8kmbt.stackblitz.io
2. Add at least 2 new rows (click on the "Add row" button).
3. Click the "select all" checkbox.
4. Click on the "Clear" button.
5. Notice that the "select all" checkbox is only partly de-selected (changes icon from check to "-").
6. Click on "Add row" again.
7. Notice that the "select all" checkbox changes to the check icon again.

**Expected behavior**
The "select all" checkbox should get entirely de-selected when removing all rows (at step 5) and then stay de-selected when adding a new row again (at step 7).

**Version**
- Observed and reported in ids-enterprise-ng@13.0.3 / ids-enterprise@4.59.2

**Platform**
 - Infor Application/Team Name: Portal V2 Development
 - OS Version: Any OS
 - Browser Name: Any browser

**Additional context**
Observed and reported during PortalV2 testing.

**Comment by tmcconechy** [comment]
The select all button acts on whats there at the time you press it its not changing dynamically as you add and remove rows. But i suppose these could be considered correct so will backlog this.

**Comment by tmcconechy** [comment]
Closing stale issues
