### ISSUE TITLE
Sinkpage: toolbar searchfield x icon misaligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6369]
**Describe the bug**
x icon is center aligned

**To Reproduce**

1. Go to https://4630-beta0-enterprise.demo.design.infor.com
2. Scroll down to toolbar element

**Expected behavior**
should be aligned

**Version**

- ids-enterprise: v4.63.0-dev

**Screenshots**
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/56722184/166226108-c87d9d4f-c612-4e42-bfd5-9e08d75fa663.png">

**Platform**
Safari, Chrome, Edge

**Additional context**
firefox not affected
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/56722184/166226055-32606fb3-1656-4477-ac56-ef0b47ae69f6.png">

**Comment by tmcconechy** [comment]
@ericangeles if you fixing this https://github.com/infor-design/enterprise/issues/6320#issuecomment-1114703657 one maybe can include a fix for this too?

**Comment by tmcconechy** [comment]
ok once approved i think we should put this in back in 4.64
