### ISSUE TITLE
Sinkpage: Datagrid Personalized Columns Search the X icon is a bit off

### ISSUE THREAD

**Issue by iamjamesreyracho** [infor-design/enterprise#6375]
**Describe the bug**
The X icon in the search field is a bit off in both new and classic version.

**To Reproduce**

1. Go to https://4630-beta0-enterprise.demo.design.infor.com/#
2. Scroll down to Datagrid
3. Click the triple dot (...), then click Personalized Columns
4. Input a text
5. See error

**Expected behavior**
X icon should looks fine.

**Version**

- ids-enterprise: v4.63.0-beta.0

**Screenshots**
![image](https://user-images.githubusercontent.com/98729565/166635354-6dd11adc-9da1-4857-a71d-2295ad4cb3f6.png)
New
![image](https://user-images.githubusercontent.com/98729565/166650388-6c78e69e-4f9d-4a7b-ae3c-50172fd024ab.png)
Classic

**Platform**
 - Browser Name: Chrome (Version 101.0.4951.54 (Official Build) (64-bit))

**Additional context**
NA

**Comment by tmcconechy** [comment]
Lets test this again after merging... https://github.com/infor-design/enterprise/pull/6371 
I didnt test but might be fixed @ericangeles ?

**Comment by ericangeles** [comment]
@tmcconechy I reproduced it on my searchfield branch.

**Comment by ericangeles** [comment]
The only thing here is the padding on the right side of the close icon.

**Comment by iamjamesreyracho** [comment]
Still need to fix the x button in Classic Version, kindly see test evidences below:
New - Passed
![image](https://user-images.githubusercontent.com/98729565/167978571-962afd87-f2bc-469b-8444-465a8cfcceaf.png)

Classic -Failed
![image](https://user-images.githubusercontent.com/98729565/167978514-3ad0fb67-fe9b-4780-b15c-561216343ef2.png)

**Comment by iamjamesreyracho** [comment]
QA Passed. Moving this ticket to done. Thanks.
Classic
![image](https://user-images.githubusercontent.com/98729565/168956017-03692b39-65c1-4827-8691-d2eb3fc10871.png)
