### ISSUE TITLE
Sinkpage: Misaligned toolbar ‘x’ button in iOS mobile / responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6380]
**Describe the bug**

Sinkpage: Misaligned toolbar ‘x’ button in iOS mobile / responsive view

**To Reproduce**

1. Go to https://4630-beta0-enterprise.demo.design.infor.com/#
2. Scroll down to Toolbar
3. Type in Search 

**Expected behavior**
Components should render properly.

**Version**

- ids-enterprise: v4.630

**Screenshots**
![5C82C13E-A016-42F3-8821-9EBE5ECDABC5](https://user-images.githubusercontent.com/45757016/166675740-16d10988-c583-41cb-8073-a220b73db628.png)

**Platform**
 iOS - Mobile 

**Additional context**
N/A

**Comment by ericangeles** [comment]
@tmcconechy yes it fixes the issue.

**Comment by janahintal** [comment]
QA Passed. Thanks!
![image](https://user-images.githubusercontent.com/45757016/167557355-2e48617b-aaa0-4fac-ac93-f06d1712df04.png)

**Comment by tmcconechy** [comment]
Closing stale issues
