### ISSUE TITLE
Circlepager: Items are off and text is misaligned in responsive view

### ISSUE THREAD

**Issue by iamjamesreyracho** [infor-design/enterprise#6383]
**Describe the bug**
Items are off and text is misaligned in responsive view in Circlepager component

**To Reproduce**

1st issue:
1. Go to https://main-enterprise.demo.design.infor.com/components/circlepager/example-form.html# 
2. In responsive view, the issue appears 365 width(Mozilla Firefox), and make it smaller.
3. See error that the text move from right to left.

2nd issue:
1. Go to https://main-enterprise.demo.design.infor.com/components/circlepager/example-index.html 
2. In responsive view, The issue appears in 355 width (Google Chrome, Microsoft Edge) and 341 width (Mozilla Firefox), and make it smaller.
3. See error that the items stick together.

3rd issue:
1. Go to https://main-enterprise.demo.design.infor.com/components/circlepager/example-tabs.html#
2. In responsive view, The issue appears in 624 width (Google Chrome, Microsoft Edge) and the item text is misaligned
3. See error that the items stick together and text is misaligned.

**Expected behavior**
Items and text should be look fine.

**Version**

- ids-enterprise: 4.64.0-dev

**Screenshots**
1st issue:
https://www.screencast.com/t/PEEF4Pcv

2nd issue:
https://www.screencast.com/t/d7vppVJww

3rd issue:
https://www.screencast.com/t/S6nNckxrf
![image](https://user-images.githubusercontent.com/98729565/166907966-e0e12c9a-2e5d-4295-95f6-14f151b18191.png)

**Platform**
 - Browser Name: Chrome, Edge, Firefox (Windows)

**Additional context**
NA

**Comment by ericangeles** [comment]
The first two were not that kind of a big deal. The third issue is more noticeable. Making it as a minor.

**Comment by tmcconechy** [comment]
Agreed minor - also partly an example issue
