### ISSUE TITLE
Images: image-list icons misaligned in mobile view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6385]
**Describe the bug**

**To Reproduce**

1. Go to https://4630-beta0-enterprise.demo.design.infor.com/components/images/example-image-list.html
2. Click to edit searchfield
3. Type test

**Expected behavior**
icons should be aligned and in-line with each other

**Version**

- ids-enterprise: v4.63.0-beta0

**Screenshots**
<img width="417" alt="image" src="https://user-images.githubusercontent.com/56722184/166914876-d861b45d-f75c-4465-b7e2-43c5023c51f1.png">

**Platform**
Mobile / mobile viewport

**Additional context**

**Comment by ericangeles** [comment]
This has been fixed in the main repo already. https://main-enterprise.demo.design.infor.com/components/images/example-image-list.html

**Comment by jbrcna** [comment]
could this be considered as a bug? 
<img width="265" alt="image" src="https://user-images.githubusercontent.com/56722184/166916715-94f54b24-3a8e-44e0-a7d9-16aa614b2393.png">

this is what it looks like in prev version
`4550`
<img width="343" alt="image" src="https://user-images.githubusercontent.com/56722184/166916801-b3267c68-a402-4f39-9775-a9f5550d3fde.png">

**Comment by ericangeles** [comment]
Yeah, we can consider it as a minor bug. I think there was a change in the height of the buttonset that causes the icons to move.

**Comment by jbrcna** [comment]
thank you. @ericangeles

**Comment by jbrcna** [comment]
this is now fixed.
<img width="419" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/3ec047c3-3432-40e2-87fd-bbc75823ed5e">
