### ISSUE TITLE
Column Grouped: Overlapping axis label & legend highlight

### ISSUE THREAD

**Issue by GlenlieMaye** [infor-design/enterprise#6388]
**Describe the bug**
Bottom Axis Label and legend highlight are overlapping

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/column-grouped/example-axis-labels.html?theme=new&mode=contrast&colors=003876
2. Click on 'May' or 'June' legend
3. See error

**Expected behavior**
Bottom Axis Label and legend highlight should not overlap upon clicking the legend

**Version**

- ids-enterprise: 4.64.0-dev

**Screenshots**
<img width="865" alt="image" src="https://user-images.githubusercontent.com/102151352/167065224-01cc0e42-b4cd-4d8a-a784-2fa4f431a3ca.png">

**Platform**
 - All major browsers

**Comment by ericangeles** [comment]
This is a duplicate https://github.com/infor-design/enterprise/issues/6384

**Comment by GlenlieMaye** [comment]
Thanks, Sir @ericangeles

**Comment by tmcconechy** [comment]
Yeah same issue - lets just have one issue 👍🏻
