### ISSUE TITLE
Tabs Module - Resizing the window makes Home button disappear and changes font in searchfield

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6394]
**Describe the bug**
When resizing a window smaller with the tabs module component and a home button, the home button either disappears or is hidden in a menu depending on the theme mode. The text in the searchfield also gets small and bolded when the window is smaller.

**To Reproduce**
1. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
2. Type something into the searchfield
3. Resize the window smaller
4. Note that at some point the home button is no longer visible and the text in the searchfield becomes bold.
5. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?theme=classic&mode=light&colors=2578a9
6. Type something into the searchfield
7. Resize the window smaller
8. Note that at some point the home button is hidden in a menu and the text in the searchfield becomes smaller and bold.

**Expected behavior**
When the window is resized it is expected that all components in the header are visible and the text in the searchfield does not change.

**Version**
- ids-enterprise: v4.64.0-dev

**Screenshots**
New Theme:
![Resizing tabs module - new theme](https://user-images.githubusercontent.com/76002134/167461192-de2c3641-31da-44fb-a3f4-13feaf42f9f4.gif)

Classic Theme:
![Resize tabs module - classic theme](https://user-images.githubusercontent.com/76002134/167461259-2f4a72d1-1064-4cde-8c1a-db134bdfd51d.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 101.0.4951.54 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
This didnt actually work did it? I think we never had a decent design for the mobile look of this.

**Comment by s-werking** [comment]
I know that for our current version (4.60.2), the home button stays visible when resizing the window. On that version the new theme searchfield text does get bolded but not in the classic theme.

**Comment by tmcconechy** [comment]
Closing stale issues
