### ISSUE TITLE
Calendar and Datagrid: Implement long press to fires the context menu event in datagrid and calendar on mobile phone.

### ISSUE THREAD

**Issue by jdrinka1** [infor-design/enterprise#6395]
**Is your feature request related to a problem or use case? Please describe.**
Would like a long press on a calendar event to display context menu on a mobile phone.
https://jira.lawson.com/browse/LMCLIENT-35799

**Describe the solution you'd like**
Would like a long press on a calendar event to display context menu on a mobile phone.

**Additional context**
After talking with Phillip he responded with 
"it looks to me like the long press is in the soho listview.js control. I think we should write up a ticket for IDS to implement so that long press fires the context menu event in datagrid and calendar"

Kris did some work on Card View List on a mobile phone.
"The card view long press was built into the card view control via (IDS)"

Would also like to see an example of a long press that displays the context form on the Calendar components page. 
https://master-enterprise.demo.design.infor.com/components/calendar/list

**Comment by tmcconechy** [comment]
Closing stale issues
