### ISSUE TITLE
Dynamic validation messages do not update the displayed value

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#640]
**Describe the bug**
If a validation rule has a dynamic message and has an id define the message displayed to the user will not update if two, or more subsequent invalid values are entered.

If a validation rule has a dynamic message and has NO id define the message displayed to the user will duplicate if two, or more subsequent invalid values are entered.

To capture the rule correctly for a dynamic message rule the id should be set, so that the rule can be identified.

**To Reproduce**
1. Go to a form with a dynamic message
2. Set the field so that the message displays (The correct message is displayed)
3. Change the value so that the rule fails, but the message should change.
4. The original message is being displayed as the addMessage function discards the updated message based on the rule id.

**Expected behavior**
The rule displays the one message on the control and it is the current message.

**Platform**
All

**Additional context**
Section of code causing the issue
```
    if (dataMsg &&
      dataMsg.filter(rules =>
        (rules.id || rules.message) === (rule.id || rule.message)).length > 0) {
      // No need to add new message
      return;
    }
```

Example rule
```
$.fn.validation.rules['lifotin-tfklifoftp-fine-records-effective-for-offence-date-single-rule'] = {
    id: 'lifotin-tfklifoftp-fine-records-effective-for-offence-date-single-rule',
    check: function(value, field, gridInfo) {
              var pass = false;
              if (validateAvailableFeeRecords(field,value)) {
                 pass = true;
              }
              $.fn.validation.rules['lifotin-tfklifoftp-fine-records-effective-for-offence-date-single-rule'].message = 'The Offence Type, \u0027{0}\u0027, has no Fine record effective for the Offence Date.'.format(value);
              return pass;
           },
    message: 'The Offence Type, \u0027{0}\u0027, has no Fine record effective for the Offence Date.'.format(),
    type: 'error'
};
```

**Comment by tmcconechy** [comment]
OK, i think we want to make the id required. So i think the only part is that it wont update if its already there. We added some of this so the events wont fire more than once.

So i think a fix would be to see if the message id is there and the text matches. If the text is changed do another update.

**Comment by marknolaninfor** [comment]
Change to check if the message has changed

      if (dataMsg && dataMsg.filter(function (rules) {
          return (rules.id || rules.message) === (rule.id || rule.message) && rules.message === rule.message;
      }).length > 0) {
        // No need to add new message
        return;
      }

      var appendedMsg = rule.message;

      if (dataMsg) {
        for (var i = 0; i < dataMsg.length; i++) {
          appendedMsg = '\u2022 ' + dataMsg[i].message;
        }
        appendedMsg += '<br>\u2022 ' + rule.message;
      }

      if (!dataMsg) {
        dataMsg = [];
      }
      // Find the message by id and remove
      field.closest('.field, .field-short').find('[data-rule-id="' + (rule.id || rule.message) + '"]').remove();

      if (field.hasClass('dropdown') || field.hasClass('multiselect')) {
        field.parent().find('.dropdown-wrapper > [data-rule-id="' + (rule.id || rule.message) + '"]').off('click.validate').remove();
      }

      dataMsg = dataMsg.filter(function (rules) {
        return rules.id !== rule.id;
      });

      dataMsg.push({ id: rule.id, message: rule.message, type: rule.type });
      loc.data(validationType.type + 'message', dataMsg);

**Comment by tmcconechy** [comment]
@marknolaninfor did you want to try to push this on a PR, with a test?

**Comment by marknolaninfor** [comment]
Test
http://localhost:4000/components/validation/test-dynamic-message.html
Change the dropdown to any value other than Hawaii and focus out of the control to trigger the validation.
The validation then contains the dynamic message including the current value.

**Comment by marknolaninfor** [comment]
The same issue is found on the standard field test for the dropdown control, so this would be a separate issue to displaying a dynamic validation message.

1. http://master-enterprise.demo.design.infor.com/components/validation/test-all-field-types.html
2. select a value 
3. remove the value to trigger the required rule

**Comment by tmcconechy** [comment]
The problem on touch devices is you cannot click out of the field. The best way to reproduce it on mobile is to click the ... to leave/blur the field.

Dont think there is anything further we can do about that, normally it wont be an issue because there would be more objects on the page to interact with. So i say ignore that mobile issue
