### ISSUE TITLE
Datagrid: Ability to add multiple rows at once

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise#6404]
**Is your feature request related to a problem? Please describe.**
Currently it is possible to add single row using `sohoDataGridComponent.addRow`. We have a use case where a new batch of rows needs to be added at once. We also have reported an [issue](https://github.com/infor-design/enterprise/issues/6491) where the grid is being rebuilt with each add of row. To avoid adding all the rows of the new batch to be added one at a time, we would like to request a method that will allow us to add multiple additional rows at once.

**Describe the solution you'd like**
Availability of `sohoDataGridComponent.addRows`. Similar to `addRow` but accepts multiple items.

**Comment by tmcconechy** [comment]
Should'nt be too bad to add. OnNe advantage would be it could render after and partly help with https://github.com/infor-design/enterprise-ng/issues/1291

Which team are you on @inforrpunay ?

**Comment by tmcconechy** [comment]
Consider also the paging - might need to add to new pages.
