### ISSUE TITLE
Locale: Incorrect German translation for id: 'InRange'

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#6413]
Locale: Incorrect German translation for id: 'InRange'

InRange: { id: 'InRange', value: 'In Bereich', comment: 'In Range in icons for filtering' }

The dropdown option “In Range” displays as “In Bereich” for German, but should be “Im Bereich”

![image](https://user-images.githubusercontent.com/66057969/168253852-0cdbfdb1-5afc-477f-8751-b7cecd3c59b1.png)

Owner: Henry.Wondergem@infor.com

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by cfieger** [comment]
Okay, I agree.
Change in memoQ project Infor CommonUX all inh 2021, string will be available after export of target file.

**Comment by cpinatel7** [comment]
@tmcconechy - Issue is still valid. Thanks

**Comment by tmcconechy** [comment]
Actually this seems fixed just not closed. the translation has been changed to Im Bereich ~ you can see it here:
https://main-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?locale=de-DE

**Comment by tmcconechy** [comment]
This would have already been in the latest version 4.82.0 ~ not sure when we got this back for sure so could be in older versions. But safest is to say 4.82.0
