### ISSUE TITLE
Datagrid: Extra space column disappear in responsive view

### ISSUE THREAD

**Issue by iamjamesreyracho** [infor-design/enterprise#6419]
**Describe the bug**
In responsive view, the extra space column disappeared.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-spacer-column.html
2. Check the extra column in the right most part of the table.
3. In responsive view, check the extra column disappeared in the right most part of the table. 

**Expected behavior**
The  extra space column should be shown in responsive view.

**Version**

- ids-enterprise: v4.64.0-dev

**Screenshots**
https://www.screencast.com/t/DY8WauyJwJL

**Platform**
 - Browser Name: All major browsers 

**Additional context**
NA

**Comment by tmcconechy** [comment]
This is as designed. The space column only fills the space at the end if its needed to fill to the width of thegrid. In that case its not needed

**Comment by iamjamesreyracho** [comment]
Okay, Sir Tim. This is noted. Thank you.
