### ISSUE TITLE
Circlepager: Border missing

### ISSUE THREAD

**Issue by iamjamesreyracho** [infor-design/enterprise#6427]
**Describe the bug**
A border is missing inside the circle pager example card in Classic version.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/circlepager/example-mobile.html
2. Click the ellipses, then click version-classic.
3. See error

**Expected behavior**
It should have a border.

New 
![image](https://user-images.githubusercontent.com/98729565/168762277-268a9628-f9fe-4868-86de-926e90358634.png)

**Version**

- ids-enterprise: v4.64.0-dev

**Screenshots**
Classic
![image](https://user-images.githubusercontent.com/98729565/168762359-374caf34-fbe7-41a8-ad04-cab3744297a9.png)

**Platform**
 - Browser Name: All major browsers

**Additional context**
NA

**Comment by tmcconechy** [comment]
I dont think we can change this. The design of cards has no border on the top. Pretty minor

**Comment by tmcconechy** [comment]
Closing as we are not updating classic anymore
