### ISSUE TITLE
Dropdown: dropdown menu changes position

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6429]
**Describe the bug**
Dropdown changes position upon clicking in FF, Edge and Safari. 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/dropdown/example-ajax-managed.html?theme=new&mode=light&colors=2578a9 (_affecting all other examples_)
2. Click on dropdown menu
3. Notice the upper part of the dropdown

**Expected behavior**

https://user-images.githubusercontent.com/102151352/168766489-6b831061-0712-4e4b-af78-3fad025ae94f.mov

**Version**

- ids-enterprise: 4.64.0-dev

**Screenshots**

https://user-images.githubusercontent.com/102151352/168766562-2b5968d8-e7e2-4d1b-8cbb-bc88a28dab1a.mov

**Platform**
 - Safari, FF and Edge

**Comment by tmcconechy** [comment]
Possibly not worth worrying about here

**Comment by tmcconechy** [comment]
Skiping this for now
