### ISSUE TITLE
Editor: The space between a copied underlined text and a hyperlinked text is removed when pasting them.

### ISSUE THREAD

**Issue by jcotaco** [infor-design/enterprise#6436]
**Describe the bug**
The space is removed when pasting a copied underlined text followed by a hyperlinked text with space between them.

**To Reproduce**

1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index'
2. Add a text with underline style.
3. Press space and add another text. 
4. Select the second word and click on the "Insert Link" button.
5. In the "Insert Link" dialog, enter URL and click on "Insert" button.
6. Verify that the second word has become a hyperlink.
7. Copy the first text and the hyperlinked text by pressing CTRL+C.
8. Paste it on a new line by pressing CTRL+V.

**Expected Behavior**
The first text and hyperlinked text should be pasted as it was copied (i.e with space in between texts).
**Actual Result:**
The space between the texts was lost on paste.

https://user-images.githubusercontent.com/72491690/168932049-3a4d988c-c8da-44ed-a586-f470a58b0c02.mp4

**Version**
ids-enterprise: 4.63.0

**Platform**
Infor Application/Team Name: Homepages
OS Version: Windows 11
Browser Name: Chrome
Browser Version: Version 101.0.4951.67 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Marking this minor as the use case is rare. Also dont think its easy to fix
