### ISSUE TITLE
Tooltip validation messages overlap text in narrow fields

### ISSUE THREAD

**Issue by jake-harrington** [infor-design/enterprise#644]
**Describe the bug**
The tooltip style of validation messages have icons in the field that overlap text in the field, especially apparent in narrow fields (particularly lookups) and fields with right text alignment. Many of our fields only have room for 2-4 characters and all are absolutely positioned (sorry but this is not able to be changed as it's not under our control). So we need to use the 'legacy' tooltip style but the (!) icon in the field will overlap the text. One scenario is a form is filled out submitted, a validation message pops up alerting the user that a field was auto populated but you can't see the auto-populated value with the icon in the way.

**To Reproduce**
1. Go to [test-legacy-tooltip-narrow-field.zip](https://github.com/infor-design/enterprise/files/2311466/test-legacy-tooltip-narrow-field.zip)
2. Focus and blur the email address field
3. See the icon overlaps the text

**Expected behavior**
Text should still be visible and not overlapped.

**Screenshots**
![image](https://user-images.githubusercontent.com/39064853/44480976-43ab8c80-a60a-11e8-8f7b-d648e9fdee0a.png)

**Platform**
 - Enterprise 4.9.x
 - All browsers

**Comment by tmcconechy** [comment]
What do you propose here? Putting the icon outside the field to the left when its that small?

**Comment by jake-harrington** [comment]
Maybe something in the background?

**Comment by tmcconechy** [comment]
Like make it behind the text?

**Comment by jake-harrington** [comment]
Yeah maybe? Or perhaps also lower opacity and tile it in the background? How do you think that'd look?

**Comment by tmcconechy** [comment]
Something like this....

![screen shot 2018-08-22 at 3 56 39 pm](https://user-images.githubusercontent.com/814283/44487325-0653f880-a624-11e8-9054-b79886e66a69.png)

Maybe it could just hide on focus? If thats the main problem?

**Comment by jake-harrington** [comment]
Yeah, I think it might look pretty nice if the icon went into the background and opacity was lowered if there was text in the field.

**Comment by tmcconechy** [comment]
Just on focus or always? And all fields or just super tiny ones... Just thinking this through

**Comment by jake-harrington** [comment]
I'm thinking always, but maybe have it do some measurements to leave it full opacity if the field is significantly wider than the amount of text in the field? If it would overlap the icon then dial the opacity down, otherwise leave it full opacity. Otherwise it might look a little wonky.

**Comment by jake-harrington** [comment]
Is this planned to be worked on eventually?

**Comment by tmcconechy** [comment]
Yes, lets put it up for Jan consideration.

**Comment by theakatz** [comment]
@kayiuho can you please take a look at Tim's suggested solve before dev takes this over?

**Comment by tmcconechy** [comment]
As discussed on chat the design on https://github.com/infor-design/enterprise/issues/644#issuecomment-415159494 should be good to go.

It works like this now:
- if you edit the field it shows the tooltip - only one at a time on most recent error
- on other fields if it has the icon and you need to see the tooltip again you click it to see it (edited) 

Fix would:
- would add something (code) to dim the icon if you focus and the text is cut off like that so you can see the whole value (edited)

**Comment by janahintal** [comment]
QA Passed. 
Tested in: https://4150-beta0-enterprise.demo.design.infor.com/components/validation/test-legacy-tooltip-narrow-field.html
