### ISSUE TITLE
Theme: Dark theme's brand.primary.base hex color is wrong

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#6446]
**Describe the bug**
The theme service's personalization color's has the wrong hex value for it's brand.primary.base option, which leads a dropdown allowing the choice of color to show the wrong default preview color.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html?theme=new&mode=dark
4. See that the "default" option is selected in the second dropdown, with a blue preview color next to the label. This is incorrect, since the actual default is a slate color. The preview color should match what the default color for the header is.

**Expected behavior**
The correct default color should be seen

**Version**

- ids-enterprise: v4.62.0

**Screenshots**
<img width="385" alt="image" src="https://user-images.githubusercontent.com/22107636/169150215-69fad7f5-1509-438b-a343-6e509d6bad80.png">

**Platform**
 - All

**Additional context**
Just need to update theme-classic-dark-colors.json and theme-new-dark-colors.json to have the correct hex values for their brand.primary.base objects.

**Comment by tmcconechy** [comment]
@ericangeles - can one of you guys take a look here. I'll patch it to 4.62 once complete

**Comment by ericangeles** [comment]
@tmcconechy so the fix on this will be on identity tokens?

**Comment by ericangeles** [comment]
PR for this issue https://github.com/infor-design/design-system/pull/491

**Comment by tmcconechy** [comment]
@ericangeles - did you test my fix? If so i can help finish this one up if you give me the go?

**Comment by ericangeles** [comment]
Yes I did, Tim. It works.

**Comment by jbrcna** [comment]
QA Passed. v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/personalize/example-color-theme-api.html?theme=new&mode=dark

<img width="386" alt="image" src="https://user-images.githubusercontent.com/56722184/170312617-6105474d-28db-4314-80df-3bf7ea671887.png">
<img width="249" alt="image" src="https://user-images.githubusercontent.com/56722184/170312754-a74e0e82-4150-48c7-8c4a-90584aafae66.png">
