### ISSUE TITLE
Unit Testing: Create a Puppeteer Script for "Button NotificationBadge – Doesn’t support changing"

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#6449]
Describe the Issue
Create a unit testing for Button NotificationBadge – Doesn’t support changing.
See attached BDD for more information.
[BDDStory_github#1241.docx](https://github.com/infor-design/enterprise/files/8696887/BDDStory_github.1241.docx)

Related github issue
[#1241](https://github.com/infor-design/enterprise-ng/issues/1241)

**Comment by jbrcna** [comment]
moving this to Done. the PR has already been merged. thanks
