### ISSUE TITLE
Typography: Overlapping Text

### ISSUE THREAD

**Issue by Henriko24** [infor-design/enterprise#6450]
**Describe the bug**
- The text is Overlapping

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/typography/example-index.html
2. See error

**Expected behavior**
- The text should not be overlapped

**Version**

- ids-enterprise: v4.64.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/102222379/169242921-38a0b889-205a-41b4-bf34-4e1ac4201cdf.png)

**Platform**
 - Browser Name: Mozilla Firefox
 - Browser Version: 100.0.1 (64-bit)

**Additional context**
NA

**Comment by ericangeles** [comment]
@sesbrenosienna can you take a look at this?

**Comment by sesbrenosienna** [comment]
Okay, sir! :)

**Comment by Henriko24** [comment]
QA tested and passed. Moving this ticket to Done. v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/typography/example-index.html

![image](https://user-images.githubusercontent.com/102222379/170415917-66bc7039-d7c8-47d8-866e-983ce729fad7.png)
