### ISSUE TITLE
Toolbar-flex: Search Icon misaligned

### ISSUE THREAD

**Issue by Henriko24** [infor-design/enterprise#6451]
**Describe the bug**
 - The search icon are misaligned

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-searchfield-collapsible.html
2. See error

**Expected behavior**
 - It should be aligned

**Version**

- ids-enterprise: v4.64.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/102222379/169265480-d541a159-ee47-421f-a49b-397220407383.png)

**Platform**
 - Browser Name: Mozilla Firefox
 - Browser Version: 100.0.1 (64-bit)

**Additional context**
NA

**Comment by sesbrenosienna** [comment]
Hello! I've fixed this issue in https://github.com/infor-design/enterprise/issues/6405. Thanks! 😄

**Comment by Henriko24** [comment]
> Hello! I've fixed this issue in #6405. Thanks! 😄

Okay. Thanks. :)

**Comment by Henriko24** [comment]
QA Passed. v4.64.0-dev
https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-searchfield-collapsible.html
![image](https://user-images.githubusercontent.com/102222379/169728792-87436009-a408-4501-97cd-9b8b3e7aeca8.png)
