### ISSUE TITLE
Searchfield: Layout issues with flex toolbar

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#6452]
**Describe the bug**
There are various layout issues with searchfield in a flex toolbar.

-- collapsible: true -- 
- icon is misaligned when searching. 
- icon is the wrong color when collapsed.
- white background color disapears when focusing out of search when still open.

-- collapsible false --
- search icon has white square behind it when collapsed

-- mobile view --
- close icon is not visible

-- other --
- Icons in toolbar shift slightly when using `collapseSize: calculateSize` function. 

For example.. 
```
<script id="test-script">
  function calculateSize() {
      return 200;
  }

  var regularSearchElem = $('#common-toolbar-searchfield');
  regularSearchElem.searchfield({
    clearable: true,
    collapsible: true,
    collapseSize: calculateSize
  });
</script>
```

**To Reproduce**

1. Edit components/header/index.html with the following

```
<header class="header is-personalizable is-personalizable">
  <div class="flex-toolbar" data-options="{maxVisibleButtons: 5}">
    <div class="toolbar-section title">
      {{> includes/header-appmenu-trigger}}
      <h1>Page Title</h1>
    </div>


    <div class="toolbar-section search">
      <div class="searchfield-wrapper">
        <label class="audible" for="common-toolbar-searchfield">Keyword Search</label>
        <input id="common-toolbar-searchfield" name="common-toolbar-searchfield" class="searchfield" placeholder="Search"/>
      </div>
    </div>

    <div class="toolbar-section buttonset">
      <button class="btn-icon" type="button">
        <svg class="icon is-expanded" focusable="false" aria-hidden="true" role="presentation">
          <use href="#icon-star-filled"></use>
        </svg>
        <span>Row</span>
      </button>

      <button class="btn" type="button">
        <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
          <use href="#icon-edit"></use>
        </svg>
        <span>Update Details</span>
      </button>

      <button id="trash-btn" class="btn">
        <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
          <use href="#icon-delete"></use>
        </svg>
        <span>Trash</span>
      </button>

      <button type="button" id="category-button" class="btn">
        <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
          <use href="#icon-filter"></use>
        </svg>
        <span>Category</span>
      </button>
    </div>

    {{> includes/header-actionbutton}}

  </div>
</header>

<script id="test-script">
  function calculateSize() {
      return 200;
  }

  var regularSearchElem = $('#common-toolbar-searchfield');
  regularSearchElem.searchfield({
    clearable: true,
    collapsible: true,
    collapseSize: calculateSize
  });
</script>
```

2. Go to http://localhost:4000/components/header/example-index.html
3. Observe various issues reported in ticket

**Expected behavior**
Issues should not occur

**Version**

- 4.63.0

**Screenshots**
<img width="590" alt="classic-search-issue" src="https://user-images.githubusercontent.com/1056684/169373927-b2e9ed39-dfbf-43b8-b9c7-42d3523b014e.png">
<img width="592" alt="icon-wrong-color-classic" src="https://user-images.githubusercontent.com/1056684/169373934-87a3b0ea-57aa-4b06-8356-1954e70b7ee8.png">
<img width="593" alt="background-color-is-lost-when-focus-removed" src="https://user-images.githubusercontent.com/1056684/169373941-623f6bfa-c359-41f6-ba77-293e0ab3d5a8.png">
<img width="233" alt="missing-close-icon" src="https://user-images.githubusercontent.com/1056684/169373972-a7bcde6c-c390-49f2-8fde-7b1a480fbe5d.png">
<img width="441" alt="white-background-on-search-icon" src="https://user-images.githubusercontent.com/1056684/169375935-c053d01b-6f4d-4415-ae22-e5b0824e322c.png">
![shifting](https://user-images.githubusercontent.com/1056684/169609666-2b2b654c-7e47-4471-bc20-57aad72e2de8.gif)

**Platform**
 - Windows 11
 - Chrome 101.0.4951.67

**Comment by tmcconechy** [comment]
cc @ericangeles
