### ISSUE TITLE
Searchfield: Ability to add additional icon into searchfield and be able to run functions when clicked.

### ISSUE THREAD

**Issue by jdrinka1** [infor-design/enterprise#6453]
**Is your feature request related to a problem or use case? Please describe.**
Have a simple LPL List definition on with with a keyword search field on it. The field also happens to be scannable so on a mobile device using Infor Go it needs to pop up a barcode scanner and return a value. 

In portrait mode the search field is always collapsed.

**Describe the solution you'd like**
When clicking on the search icon it expands the field 100%. Would like to be able to display the barcode icon and when clicked it would run functions in our code. The additional icon should display next to the to the X and Collapse button.  See screen shot. 

**Additional context**
Here is a sample screen shot. 
![barcode_searchField_example](https://user-images.githubusercontent.com/86791155/169384415-cbe42036-b0ed-423c-bda0-167c22ae7263.png)

Here is a sample video of how the barcode scanning works in general. This is on a CardView type list. The request above is not using a cardview type list. 

https://inforonline-my.sharepoint.com/personal/jerry_drinka_infor_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fjerry%5Fdrinka%5Finfor%5Fcom%2FDocuments%2FFiles%20to%20big%20for%20mail%20or%20Jira%2FkeywordSprintDemo%2EMOV&parent=%2Fpersonal%2Fjerry%5Fdrinka%5Finfor%5Fcom%2FDocuments%2FFiles%20to%20big%20for%20mail%20or%20Jira&ga=1

**Comment by tmcconechy** [comment]
cc @inforandy

**Comment by inforandy** [comment]
Hi @jdrinka1. Looking at example, our recommendation would be to isolate this scan-to-search functionality to another tab, the way you have already done with Keyword search and Text search, and not extend the standard searchfield in this manner. 

If I am misunderstanding something about the use case, please let me know. 

Thanks!

**Comment by tmcconechy** [comment]
idea for coding:
- in full screen the button is on the toolbar
- button appears only in expanded mode
- show attaching click event to each with a console log
- cant be any button

**Comment by tmcconechy** [comment]
@jdrinka1 maybe wont solve it but i noticed this example is similar https://main-enterprise.demo.design.infor.com/components/listview/example-filters.html with custom buttons.

@yohannahbautista can we make the example look like this one like the screen shots to make sure the extra button works on the collapsible example http://localhost:4000/components/searchfield/test-conflicting-collapsible-settings.html (on mobile size).

If that works its good. Maybe call the setting extraButton? Also will need an NG type

**Comment by jbrcna** [comment]
QA PAssed
v4.66.0-beta0
https://4660-beta0-enterprise.demo.design.infor.com/components/searchfield/example-buttons
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/56722184/183001609-9a02bfac-a875-44f0-a9db-987164a1ab06.png">
