### ISSUE TITLE
Busyindicator: The busy indicator is a bit off

### ISSUE THREAD

**Issue by iamjamesreyracho** [infor-design/enterprise#6457]
**Describe the bug**
Busy indicator is a bit off in Classic version in Win-FF.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/busyindicator/example-inputs-compact.html?theme=classic&mode=light&colors=2578a9
2. Click on the Load button
3. See error

**Expected behavior**
Busy indicator should look fine.

Win-Chrome (Classic)
https://www.screencast.com/t/KkXo0DRYN

**Version**

- ids-enterprise: v4.64.0-dev

**Screenshots**
Win-FF (Classic)
https://www.screencast.com/t/JbR3v9D1tq8 

**Platform**
 - Browser Name: Mozilla Firefox (Windows)

**Additional context**
NA

**Comment by tmcconechy** [comment]
I think this issue is too minor. I would'nt work on it and we should probably descope issues this minor.
