### ISSUE TITLE
FileuploadAdvanced: Failed Icon Issue

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6459]
**Describe the bug**
Failed Icon is not rendered properly when in Classic Version

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-failed.html?theme=classic&mode=light&colors=2578a9 (_affecting all other examples_)
2. Click on the 'Select Files' link
3. Select a file
4. Then click the 'Set Failed' button
5. Notice the Failed Icon

**Expected behavior**
Failed button should be rendered properly

**Version**

- ids-enterprise: 4.64.0-dev

**Screenshots**

https://user-images.githubusercontent.com/102151352/169512364-1d9926aa-6fa9-4a2c-8b7d-335e0f3d400d.mov

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
Looks like something on TOP of the icon. Can probably remove that and just use the icono

**Comment by ericangeles** [comment]
To add that, the icon's width should be 18x18 once the background color has been removed (classic).

**Comment by tmcconechy** [comment]
No longer appears to be an issue
