### ISSUE TITLE
Tabs: regression from#6068

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#6464]
**Describe the bug**
with the fix from https://github.com/infor-design/enterprise/issues/6068, the issue from https://github.com/infor-design/enterprise/issues/5554 came back.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/example-composite-form-on-side.html?locale=ar-sa
2. focus on the tabs, the outline isn't aligned.

**Expected behavior**
Check with these two patterns, and check if the outline is aligned on the focused tab.
https://main-enterprise.demo.design.infor.com/components/tabs/example-composite-form-on-side.html?locale=ar-sa
https://main-enterprise.demo.design.infor.com/components/tabs/example-desktop-breakpoint.html?theme=classic&mode=light&colors=2578a9&locale=ar-SA

**Version**

- ids-enterprise: 4.62

**Screenshots**
![image](https://user-images.githubusercontent.com/29673378/169744211-a3924fe0-769f-4893-afe8-00369fa590eb.png)

**Platform**
 - Infor Application/Team Name: Landmark Client
 - Device: (if applicable): NA
 - OS Version: Windows 10
 - Browser Name: Chrome

**Additional context**
[Jira Ticket](https://jira.lawson.com/browse/LMCLIENT-36225)

**Comment by tmcconechy** [comment]
@tjamesallen15 yeah looks like it wasnt addressed for classic. I will release the beta today but we will add a fix to this on top of it when thats done 👍🏻

**Comment by tmcconechy** [comment]
@tjamesallen15  CC @ericangeles 
Looks like this failed QA and we didnt address it last sprint. Can you take another look for classic theme?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 CC @ericangeles Looks like this failed QA and we didnt address it last sprint. Can you take another look for classic theme? i.e.
> 
> https://main-enterprise.demo.design.infor.com/components/tabs/example-desktop-breakpoint.html?theme=classic&mode=light&colors=2578a9&locale=ar-SA

wil ldo

**Comment by GlenlieMaye** [comment]
QA tested and passed. Moving this ticket to Done.
https://main-enterprise.demo.design.infor.com/components/tabs/example-composite-form-on-side.html?theme=classic&mode=light&colors=2578a9&locale=ar-sa

https://user-images.githubusercontent.com/102151352/176570737-7163cdb7-2bd7-44ee-b21d-4e217d1d21ca.mov
