### ISSUE TITLE
Icons: Misaligned and overlapping icon upon clicking

### ISSUE THREAD

**Issue by iamjamesreyracho** [infor-design/enterprise#6469]
**Describe the bug**
In New version, the plus-minus icon is misaligned. And after 2 times clicking the app-header icon, it overlaps the plus-minus icon in both New and Classic Version.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/icons/example-pseudo-elements.html
2. Click on app-header icon 2 times
3. See error

**Expected behavior**
Classic Version
![image](https://user-images.githubusercontent.com/98729565/169786779-6e34fb95-2d04-46ab-8176-97e28b3beb63.png)

**Version**

- ids-enterprise: v4.64.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/98729565/169786847-aadb7c89-a8d8-4c7b-ad70-d408bc88aeaa.png)

New
https://www.screencast.com/t/VfDVT8P3q

Classic
https://www.screencast.com/t/QtEqB5zW

**Platform**
 - Browser Name: Chrome, Edge, Firefox (Windows)

**Additional context**
NA

**Comment by tmcconechy** [comment]
I dont think that these are used anymore.
