### ISSUE TITLE
[Mac Safari] ContextMenu: Contextmenu closing automatically when opened again using control+click

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#647]
**Describe the bug**
[Mac Safari] ContextMenu: Contextmenu is closing automatically when opened again using Control+click

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/contextmenu/example-index.html in Mac Safari
2. Right-click or press Control+click to open the contextmenu
3. Click outside the contextmenu to close it
4. Now open the contextmenu by pressing Control+click, the contextmenu will automatically close

**Expected behavior**
Contextmenu should stay open when opened again using Control+click

**Screenshots**
![safari_controlclick_1](https://user-images.githubusercontent.com/39508864/44504261-78cce300-a6cd-11e8-9585-2df49f0da520.gif)

**Platform**
 - Mac OS
 - Safari

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Maybe im not clear on how this is working but if i hold down ctrl and click on the track pad. It seems to be working. Can someone explain what different config we need to reproduce this?

**Comment by EdwardCoyle** [comment]
@tmcconechy I tested with Mac Safari and can confirm it doesn't work.  The mouseup events that close the menu aren't checking for a pressed CTRL key, so we'll need to fix that.

**Comment by EdwardCoyle** [comment]
originally reported [here](https://github.com/infor-design/enterprise/issues/597#issuecomment-414249699) in #597

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/contextmenu/example-index.html
Passed QA testing
