### ISSUE TITLE
Norwegian bokmål does not work with datagrids

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#6472]
**Describe the bug**
We are seeing issues with datagrids when using "Norwegian bokmål" as locale (nb-NO) 

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-index.html?locale=nb-NO 
**Expected result**: The datagrid is correctly displayed
**Actual result**: The datagrid is not displayed (or in some of our cases looks weird) and there is a format issue in console. 

**Expected behavior**
The datagrid should be displayed correctly (similar to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-index.html )

**Version**

- ids-enterprise: 4.61.0, but also reproducible in 4.63.0 (latest)

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/169835125-3d9472cc-4699-44a4-8bf6-cea89f6bca7e.png)

**Platform**
 - Infor Application/Team Name: Infor Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 101.0.4951.67 (Official Build) (64-bit)

**Additional context**
-

**Comment by anhallbe** [comment]
@ericangeles @tmcconechy would it be possible to provide a patch for this for 4.62?

We are using `ids-enterprise-ng@13.3.2` which depends on `ids-enterprise@4.62.1`

Would it be possible with a `ids-enterprise-ng@13.3.3` patch that depends on `ids-enterprise@4.62.2` with a fix for this issue? I guess we could techically override the NG dependency, but it would be cleaner if there was a patch for both

**Comment by tmcconechy** [comment]
ok done its ids-enterprise-ng@13.3.3 with ids-enterprise@4.62.2

**Comment by janahintal** [comment]
QA Passed. Verified in 

- http://localhost:4000/components/datagrid/example-index.html?locale=nn-NO
- http://localhost:4000/components/datagrid/example-index.html?locale=nb-NO
- http://localhost:4000/components/datagrid/example-index.html?locale=ms-MY
Thanks!
