### ISSUE TITLE
Pie: Right side legend setting is being overflowed under the pie chart

### ISSUE THREAD

**Issue by satishsetti** [infor-design/enterprise#6474]
Earlier version 9.6.1, by default legend text is showing at right side like below
 
 
![IDS-NG-9 4 0](https://user-images.githubusercontent.com/1482174/169844525-92c0d2d0-221b-4871-871d-ad7f0c07b83c.jpg)

 Now We are using Newer Version 13.4.0: unable setting the prop for right side of legend text.
![IDS-NG-13 4 0](https://user-images.githubusercontent.com/1482174/169844604-6614e09e-af16-401c-9c04-59298b356808.jpg)

  
Please let me know if any other prop to show the Legend text at right side.

**Comment by tmcconechy** [comment]
To reproduce this issue go to https://stackblitz.com/edit/ids-quick-start-1331-micebt?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.css

I think we should:
a) put this feature behind a setting. So you can disable it. 
b) also I think it shouldn’t take the text from the right side and move it below.

**Comment by jbrcna** [comment]
QA Passed.
https://main-enterprise.demo.design.infor.com/components/donut/example-legend-bottom
<img width="400" alt="image" src="https://user-images.githubusercontent.com/56722184/173725489-feb45e87-6a89-43ae-8286-56f36578654f.png">
<img width="363" alt="image" src="https://user-images.githubusercontent.com/56722184/173725521-5a6171f0-4a4a-411b-8efa-e9461a92faee.png">
