### ISSUE TITLE
Datagrid: When removing data at page 2 it jump to page 1

### ISSUE THREAD

**Issue by AmilaWelikalaInfor** [infor-design/enterprise#6475]
Assume that there are 9 data rows in grid and page size of that grid is 5. Then there must be 2 pages there and first 5 data rows are in 1st page and next 4 is on 2nd page. Now user navigate to second page and remove the last data row.

**Describe the bug**
 Data grid should not navigate to page 1 and keep it on page 2. Because user remove last data row at page 2 and even he removed that total data rows are 8 and for page 1 still with 5 data records and page 2 it will have 3 data record. But before he delete record he is on 2nd page and even though he delete it he should be in 2nd page. But right now it moves to 1st page

**Steps to reproduce the behavior:**

- create a data grid with 9 data records. 
- Set data grid page size as 5
- go to 2nd page
- remove that record
- see the behaviour
use this [example](https://master-enterprise.demo.design.infor.com/components/datagrid/test-dirty-indication-after-remove-row.html)

**Expected behavior**
User should in his current page after remove data. In here it will be page two

**Version**
- ids-enterprise: [e.g. v13.4.0]

**Screenshots**
[Refer this video](https://user-images.githubusercontent.com/86338168/169850447-bc58ba28-41b3-4025-8715-ca6a797bc4f0.mp4)

**Platform**
 - Infor Application/IAD
 - Device: Laptop - Dell
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 101.0.4951.67 (Official Build) (64-bit)

**Additional context**

**Comment by GlenlieMaye** [comment]
QA tested and passed.
https://main-enterprise.demo.design.infor.com/components/datagrid/test-dirty-indication-after-remove-row.html

https://user-images.githubusercontent.com/102151352/173963039-aa5ef7e3-2ceb-48b3-970d-65a71d9c4eb3.mov
