### ISSUE TITLE
Datagrid: Issue changing the grid's showSelectAllCheckBox property

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#6476]
**Describe the bug**
We are changing the grid's showSelectAllCheckBox property for a datagrid.  

For the lookup select modal dialog, when the user can select multiple values across the pages do not want to show the select all checkbox.  When the user switches the select datagrid into edit mode to perform transactions, then want to show the select all checkbox. 

Issue is the select all checkbox is not changing when the property is updated. 

1. Using the attached 'test-change-show-select-all-checkbox.html'
2. Initially the grid is built without the select all checkbox being rendered
3. Click on the 'Toggle Select All' button
4. Notice that the show select all checkbox is not displayed

**Expected behavior**
Changing the showSelectAllCheckBox property will take affect.

**Version**
- ids-enterprise: v4.64.0-dev

**Comment by claudenbach** [comment]
[showSelectAllCheckBox.zip](https://github.com/infor-design/enterprise/files/8755979/showSelectAllCheckBox.zip)

**Comment by tmcconechy** [comment]
Could you do a rerender()? - Although we could make it take effect right away - probably have to hide / show it.

**Comment by claudenbach** [comment]
Yes, I'm able to work around this issue.
