### ISSUE TITLE
Lookup: Misalignment and overlapped issue in responsive view

### ISSUE THREAD

**Issue by iamjamesreyracho** [infor-design/enterprise#6487]
**Describe the bug**
**1st Issue**
In responsive view, the search-list icon and launch icon are misaligned. It appears on 339px in Win-Chrome and Win-Edge. Both in New and Classic version.

**2nd Issue**
The ellipses icon is not centered in focus. Both in New and Classic version.  In all browsers

**3rd Issue**
In responsive view, the table overlaps the title text In New version. In all browsers. It appears on 610px.

**To Reproduce**

**1st Issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/lookup/example-clearable.html and https://main-enterprise.demo.design.infor.com/components/lookup/example-icon.html 
2. In responsive view, set the view px on 339px
3. See error

**2nd Issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/lookup/example-clientside-paging-with-filtering.html and https://main-enterprise.demo.design.infor.com/components/lookup/example-custom-toolbar.html and https://main-enterprise.demo.design.infor.com/components/lookup/example-filter-row.html 
2. Click on search-list icon
3. see the ellipses' focus

**3rd Issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html
2. In responsive view, set the view px on 610px
3. See error

**Expected behavior**
It should be look fine.

**Version**

- ids-enterprise: v4.64.0-dev

**Screenshots**
**1st Issue**
![image](https://user-images.githubusercontent.com/98729565/170187911-cd8796bf-0269-4afa-9f0d-def7cbfcbabb.png)
![image](https://user-images.githubusercontent.com/98729565/170187922-999dabd5-2165-4e70-a47a-322395626b10.png)

**2nd Issue**
![image](https://user-images.githubusercontent.com/98729565/170188097-13206ca6-afa9-4357-a40b-2be718d2c426.png)

**3rd Issue**
![image](https://user-images.githubusercontent.com/98729565/170188132-0ceb7a4f-5ac5-49b5-92db-71e3aa5e2be8.png)

**Platform**
 - Browser Name: Chrome, Edge, Firefox (Windows)

**Additional context**
NA

**Comment by jbrcna** [comment]
QA Passed


**1st issue**
https://main-enterprise.demo.design.infor.com/components/lookup/example-clearable.html
<img width="597" alt="image" src="https://user-images.githubusercontent.com/56722184/174970357-be54cd71-e0bc-465c-b833-a24c142d916b.png">
https://main-enterprise.demo.design.infor.com/components/lookup/example-icon.html
<img width="525" alt="image" src="https://user-images.githubusercontent.com/56722184/174970496-08a5139c-7538-49ac-bdf1-3e9202904d66.png">

**2nd issue**
https://main-enterprise.demo.design.infor.com/components/lookup/example-clientside-paging-with-filtering.html
<img width="848" alt="image" src="https://user-images.githubusercontent.com/56722184/174971313-87dce989-977b-4576-abef-61fc5880d5af.png">
https://main-enterprise.demo.design.infor.com/components/lookup/example-custom-toolbar.html
<img width="657" alt="image" src="https://user-images.githubusercontent.com/56722184/174972160-5faebea7-0034-41b0-aac1-22d1a859a13f.png">
https://main-enterprise.demo.design.infor.com/components/lookup/example-filter-row.html
<img width="812" alt="image" src="https://user-images.githubusercontent.com/56722184/174972312-1404e3cf-0bc6-406f-b25e-4dfc91fb571c.png">

**3rd issue**
https://main-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside.html
<img width="706" alt="image" src="https://user-images.githubusercontent.com/56722184/174972835-29f6ebec-a87e-4364-9b6e-7d2dd4cad987.png">
