### ISSUE TITLE
General: Remove sourcemaps from Minified assets

### ISSUE THREAD

**Issue by pbal** [infor-design/enterprise#6489]
**Describe the bug**
Minified assets like sohoxi.min.js and other css `min` assets should not include sourcemaps

* It reveals the source code in production mode
* It forces browser to make an inquiry for sourcemap

Source maps can remain in non-minified assets.
 
1. Check bottom of sohoxi.min.js file - you will find reference of sourcemaps.

**Expected behavior**
Source maps should only be in non-minified version of code.

**Additional Information**
See https://css-tricks.com/should-i-use-source-maps-in-production/

**Version**
4.63.0

**Comment by tmcconechy** [comment]
Agreed (see also IGS-1842)
- you cant just not include it without a change
- We don't want in in prod for performance / and obfuscation

**Comment by pbal** [comment]
This here needs to be `false`
https://github.com/infor-design/enterprise/blob/main/scripts/configs/terser.js#L29-L31

**Comment by tmcconechy** [comment]
@pbal Thinking about backing this idea out as now we have no way of debugging production issues.
Did this come from Infor Security or anything?

If we do might be for https://github.com/infor-design/enterprise-wc only?

**Comment by pbal** [comment]
No, it was not a request from Infor Security.
