### ISSUE TITLE
Browser Stack Errors on Datepicker Tests

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#649]
**Describe the bug**

Nightly builds have been failing for the past few nights due to https://travis-ci.com/infor-design/enterprise/jobs/141486991#L2616

Errors like: Expected '8/22/2018' to equal '8/23/2018'.

List of failures
```
 Datepicker example-index tests Should set todays date from popup to field
- Expected '8/22/2018' to equal '8/23/2018'.
 Datepicker example-index tests Should be able to select with arrows and enter
- Expected '8/22/2018' to equal '8/23/2018'.
 Datepicker Anniversay tests Should populate month day
- Expected 'August 22' to equal 'August 23'.
 Datepicker Anniversay tests Should populate month/day/year
- Expected '8/22/2018' to equal '8/23/2018'.
 Datepicker custom format tests Should use Locale
- Expected '8/22/2018' to equal '8/23/2018'.
 Datepicker custom format tests Should format ISO Date
- Expected '2018-22-08' to equal '2018-23-08'.
 Datepicker custom format tests Should format Full Date
- Expected '22 Aug 2018' to equal '23 Aug 2018'.
 Datepicker custom format tests Should format Custom Date
- Expected '22/08/2018' to equal '23/08/2018'.
 Datepicker Timeformat Tests Should set custom pattern time when selected
- Expected '2018/8/22 00:00' to equal '2018/8/23 00:00'.
 Datepicker Timeformat Tests Should set locale time when selected 
- Expected '8/22/2018 12:00 AM' to equal '8/23/2018 12:00 AM'.
 Datepicker 12hr Time Tests Should render 12hr time
- Expected '22 Aug 2018 12:00 AM' to equal '23 Aug 2018 12:00 AM'.
 Datepicker Gregorian SA Tests Should render gregorian on as-SA time
- Expected '22/08/2018' to equal '23/08/2018'.
```

**To Reproduce**
1. Wait for the nightly to run.

**Expected behavior**
No more errors in nightly

**Additional context**
It appears the server is running in a different time zone than the browser.

**Comment by clepore** [comment]
One idea mentioned, is to change [this code](https://github.com/infor-design/enterprise/blob/master/test/protractor.ci.bs.conf.js#L43) to be UTC.

Also @d-g-h noticed that these are setting the times to 0 in the tests [here](https://github.com/infor-design/enterprise/commit/ef03e2026b11acb3053d817306e0ad357b9c16a9#diff-787049c6175156e8cc0221db3acbab14)

**Comment by tmcconechy** [comment]
I set the times to zero because the today function does that.. https://github.com/infor-design/enterprise/blob/master/src/components/datepicker/datepicker.js#L2075 I thought it would help but it made no difference.

**Comment by tmcconechy** [comment]
I think these have been fixed.
