### ISSUE TITLE
Datagrid: Adding row re-renders the entire rows

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise#6491]
**Describe the bug**
We observed that the datagrid re-renders all the row element when you add a new row.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/4.60.0/demo/components/datagrid/test-hide-pager-if-one-page.html
2. Click on the 'Add' button to add rows
3. Manually modify the text of the Order Date cells using the developer tools
4. Click on the 'Add' button to add another row

**Expected behavior**
Modified text of the cells should be retained

**Version**
- ids-enterprise-ng: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 101.0.4951.54 (Official Build) (64-bit)

**Additional context**
Could it be possible that newly added row element will just be appended instead of destroying all elements and creating new one?

**Comment by tjamesallen15** [comment]
Hello @tmcconechy ,

I just wanna ask for clarification because I'm not much sure if this is a bug because clearly when you edit a cell node in the developer's tool it won't saved/persist in the datagrid. As far as I remember, we used dataset inside the settings for the datagrid,

I can give the reported an editable test page similar for this one but in editable true.

**Comment by GlenlieMaye** [comment]
QA tested and passed.

**_Before fix:_**
https://4610-enterprise.demo.design.infor.com/components/datagrid/test-hide-pager-if-one-page.html

https://user-images.githubusercontent.com/102151352/176820481-5652a5f8-9d2d-4945-b1ac-d688185a6e5e.mov


**_After fix:_**
http://localhost:4000/components/datagrid/test-hide-pager-if-one-page.html

https://user-images.githubusercontent.com/102151352/176820542-8de8c3fe-41bd-4546-bffd-22108adb3a3d.mov

**Comment by CindyMercadoReyes** [comment]
Attaching the BBD for this ticket.
[BDD_github6491.docx](https://github.com/infor-design/enterprise/files/9031155/BDD_github6491.docx)
