### ISSUE TITLE
Datepicker: '+' and '-' key is not working to increment/decrement the day in calendar 

### ISSUE THREAD

**Issue by iamjamesreyracho** [infor-design/enterprise#6493]
**Describe the bug**
'+' and '-' key is not working to increment/decrement the day in calendar in Win-FF.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html 
2. Click on calendar icon and pick any date
3. Press '+' or '-' key

**Expected behavior**
'+' is used to increment the day in the calendar.
'-' is used to decrement the day in the calendar.

**Version**

- ids-enterprise: v4.64.0-dev

**Screenshots**
Win-FF on the left and Win-Chrome on the right.
https://www.screencast.com/t/c9v3WQ76NMuj 

**Platform**
 - Browser Name: Mozilla Firefox (Windows)

**Additional context**
Affected links:
https://main-enterprise.demo.design.infor.com/components/datepicker/example-index.html 
https://main-enterprise.demo.design.infor.com/components/datepicker/example-anniversary-format.html 
https://main-enterprise.demo.design.infor.com/components/datepicker/example-custom-format.html 
https://main-enterprise.demo.design.infor.com/components/datepicker/example-disabled-dates.html 
https://main-enterprise.demo.design.infor.com/components/datepicker/example-not-tabbable.html 
https://main-enterprise.demo.design.infor.com/components/datepicker/example-range.html 
https://main-enterprise.demo.design.infor.com/components/datepicker/example-sizes.html 
https://main-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html 
https://main-enterprise.demo.design.infor.com/components/datepicker/example-umalqura.html 
https://main-enterprise.demo.design.infor.com/components/datepicker/example-validation.html

**Comment by tmcconechy** [comment]
Seems like a bug but this is "old fashioned" behavior. Idea was it only worked in the field. When its open you can use arrow keys.

That being said i think it could also work when open

**Comment by iamjamesreyracho** [comment]
Noted, Sir @tmcconechy. Thank you!
