### ISSUE TITLE
DatePicker: The currently selected date in the Datepicker is not being 'unhighlighted' when one navigates away from the selected month

### ISSUE THREAD

**Issue by madebyannalam** [infor-design/enterprise#6495]
**Describe the bug**
When we have a selected date in the Datepicker and we navigate to a month that is not the one belonging to our selected date, the day of the month remains highlighted in blue.

**To Reproduce**
1. Select any date in the datepicker.
2. Reopen the date picker. Note that the previously selected date is highlighted in blue and has the focus on it.
3. Navigate to the next month.
4. Use the month & year selector at the top left of the datepicker to jump to another month, ideally one that is not directly before or after our selected date.

**Expected behavior**
When we navigate away from the selected month, the selected day (in the example 26) should be 'unhighlighted' in the other months' views.

**Version**
- ids-enterprise-ng: 13.0.3

**Screenshots**
![Soho Datepickers 1](https://user-images.githubusercontent.com/93908047/170393860-8cf36cf4-ba0a-43c3-8ab5-30bc74562c7d.png)

**Platform**
 - Device (if applicable) 
 - OS Version: Windows
 - Browser Name: Chrome
 - Browser Version: Version 102.0.5005.63 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
This was a behavior choice. When navigating to the new month we highlight the same day on the next month. Partly this is to have something focused for using the keyboard. Probably wont be able to easily change this.
