### ISSUE TITLE
Locale: Inconsistent / incorrect filter translations in 15 languages

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#6501]
Locale: Inconsistent / incorrect filter translations in:
Bulgarian
Danish
French (Canada)
Hebrew
Hungarian
Indonesian
Lithuanian
Latvian
Malay
Norwegian
Romanian
Slovak
Slovenian
Thai
Vietnamese

Attachment: Filters.docx ([Filters.docx](https://github.com/infor-design/enterprise/files/8799113/Filters.docx)). List of changes are in yellow highlight

Please assign to Henry.Wondergem@infor.com for review

**Comment by jonathanamiran** [comment]
Hi, the current Hebrew translation is better than proposed in the document.

**Comment by tmcconechy** [comment]
cc @hwondergem - thank you!

**Comment by tmcconechy** [comment]
@hwondergem -> has this been translated yet?

**Comment by hwondergem** [comment]
Some changed have been implemented, others haven't. Will check them again with the next translation update.

**Comment by tmcconechy** [comment]
@hwondergem can you update this? in the last drop was this all resolved? Thanks!

**Comment by hwondergem** [comment]
@tmcconechy Not all resolved yet as several languages only get updated during June 2023.

**Comment by hwondergem** [comment]
All translations updated where required, in ..\cc\ToDev\SohoUX\xx-YY-messages.ts	69,254	07/19/2023 06:46
