### ISSUE TITLE
Datagrid: getModifiedRows in Grouping not showing all modified rows

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#6503]
**Describe the bug**
When using `groupable` in Datagrid, `getModifiedRows ` and `dirtyRows` returns data in a different format than without the `groupable` setting and also returns rows that haven't been changed.

**To Reproduce**

1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-grouping-editable.html](https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-grouping-editable.html)
2. in the console type `$("#datagrid").data('datagrid').getModifiedRows(true)`
3. See that it's empty (this is OK)
4. Make some changes
5. Run command again
6. See the returned data

**Expected behavior**
Should behave like [https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-dirty-indication.html](https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-dirty-indication.html)
The returned array size should be the number of changed rows, and the array data should be the changed rows.

**Version**

- ids-enterprise: v4.63.0

**Screenshots**

![image](https://user-images.githubusercontent.com/34129313/171021506-2fb1cef3-788a-4a4d-8819-7b04b35550c4.png)

**Platform**

 - OS Version: Windows 10 
 - Browser Name: Chrome / Firefox
 - Browser Version: Latest

**Additional context**
Thanks

**Comment by clausvaever** [comment]
Besides the problem as described above with the return of modified rows, it also seems like the returned selected rows are wrong. So both getModifiedRows() and selectedRows() returns the wrong rows if grouping is used.

Steps to recreate the problem with selectedRows():
1.Open [https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-grouping-editable.html](https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-grouping-editable.html%20) in Chrome
2.Open Developer tool (Ctrl+Shift+i)
3.In Watch add $("#datagrid").data('datagrid').selectedRows()
4.Select the row with "customer Id"=3 as in the screenshot
5.Refresh the watched expressions
6.See that in fact "customer Id"=6 seems to be selected

In my opinion this are quite fundamental to the datagrid. If you e.g. have a master grid on top and a detail view below displaying detail information about the selected row in the grid, the information would be all wrong!
