### ISSUE TITLE
Tabs Module: Alignment and overlapping issues

### ISSUE THREAD

**Issue by iamjamesreyracho** [infor-design/enterprise#6526]
**Describe the bug**
**1st Issue**
The searchfield-category button is a bit misaligned in Classic version. In all browsers.

**2nd Issue**
In responsive view, the tabs module overlaps to accordion panel in both New and Classic version. It appears on 766px. In all browsers.

**3rd Issue**
In responsive view, the tabs module overlaps to title toolbar  in both New and Classic version. It appears on 767px. In all browsers.

**To Reproduce**

**1st Issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html
2. Click on ellipses and change the version to classic
3. See error

**2nd Issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-sortable.html
2. Click on application menu
3. In responsive view, set the view px to 766px

**3rd Issue**
1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html 
2. In responsive view, set the view px to 767px
3. See error

**Expected behavior**
It should look fine.

**Version**

- ids-enterprise: v4.64.0-dev

**Screenshots**
**1st Issue**
![image](https://user-images.githubusercontent.com/98729565/171323552-d506d643-7502-45fd-8558-c0676eb1d08a.png)

**2nd Issue**
![image](https://user-images.githubusercontent.com/98729565/171323588-66625dbc-c28d-4304-ab99-c5e6897f5f4e.png)

**3rd Issue**
![image](https://user-images.githubusercontent.com/98729565/171323629-75305720-e2c6-43fb-b680-995aa74259c0.png)

**Platform**
 - Browser Name: Chrome, Edge, Firefox (Windows)

**Additional context**
NA

**Comment by GlenlieMaye** [comment]
**1st Issue** _Bug is already fixed. However, the focus on ellipses is overlapping within the border._
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/177691614-b3835e8c-5922-402e-be64-091a73fa6cb1.png">

**2nd Issue** Pass
<img width="864" alt="image" src="https://user-images.githubusercontent.com/102151352/177692166-7499d642-5a73-4165-88df-4d007ec0ce04.png">

<img width="864" alt="image" src="https://user-images.githubusercontent.com/102151352/177692307-693d6824-58ea-4d36-aa3a-dc7aafb2d1ec.png">

**3rd Issue** Pass
<img width="864" alt="image" src="https://user-images.githubusercontent.com/102151352/177692477-3264d876-e338-47ca-b164-dceb2b1b343e.png">

<img width="864" alt="image" src="https://user-images.githubusercontent.com/102151352/177693349-80ac2978-e309-4e2e-bd6f-833d52df228d.png">
