### ISSUE TITLE
Homepage: When dragging widgets, they are almost invisible

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#6529]
**Describe the bug**
When dragging widgets in a Homepage we need the border (or all content) to be visible. But currently when the widget is larger than small-widget size the border is not visible when using Windows (on MAC it seems to be OK)

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/homepage/test-small-editable.html?theme=classic&mode=light&colors=0066D4
2. Drag the small widget
3. Notice that the whole border is visible
4. Drag the large widget
5. See the error: the widget is barely visible. 

**Expected behavior**
The border should be visible for all widgets when dragging it.

**Version**

- ids-enterprise: 4.63.0
**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/171597519-4b23dc7a-afab-4b05-bbe8-c4d6d579ced7.png)

![image](https://user-images.githubusercontent.com/8664975/171597637-2067858d-9928-4712-b314-5140912417fb.png)

**Platform**
 - Infor Application/Team Name: Infor OS
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 102.0.5005.63 (Official Build) (64-bit)

**Additional context**
-

**Comment by ericangeles** [comment]
@SofiK, does this issue only occur on the Windows platform?

**Comment by SofiK** [comment]
Hi @ericangeles , yes this is only an issue on Windows (as far as I know)

**Comment by tjamesallen15** [comment]
Hello Team,

I did a research about the draggable fade and it is built-in limitation on Windows 10. In Mac, it is fine as it is and there is no fade between large draggable items.
https://stackoverflow.com/questions/18841228/draggable-item-faded-and-ugly

As stated in the link above, I checked the google image and it creates a small version of the draggable image for it not to fade.
![Untitled](https://user-images.githubusercontent.com/34049950/193711907-5ec8b4cb-602e-4a99-9164-a2c60b2ef796.png)

**Comment by tmcconechy** [comment]
@andriivarhanov did you solve this recently for tabs in the WC project? Just trying to connect the two issues.

**Comment by tmcconechy** [comment]
@tjamesallen15 have a look at https://github.com/infor-design/enterprise-wc/pull/933 but i dont know if it will solve the issue.

Lets research if we can get rid of the window effect?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 have a look at [infor-design/enterprise-wc#933](https://github.com/infor-design/enterprise-wc/pull/933) but i dont know if it will solve the issue.
> 
> Lets research if we can get rid of the window effect?

Will research about this, but I think this won't make in Oct Sprint.
