### ISSUE TITLE
Lost support for Lookup filter type in datagrid

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#653]
**Describe the bug**
In the 3.x controls, we could specify a lookup filter type. This is missing in 4.0.

**Expected behavior**
Should be able to specify a lookup filter type for datagrid.

**Screenshots**
In 3.x, this is what we passed in as the column definition:
![image](https://user-images.githubusercontent.com/22107636/44537278-f7bd1e00-a6c3-11e8-816b-a3afdafc1da7.png)

and the lookup filter looked like this:
![image](https://user-images.githubusercontent.com/22107636/44537347-2935e980-a6c4-11e8-8940-e947b60500ca.png)

**Platform**
 - All

**Additional context**

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done folder.
