### ISSUE TITLE
Calendar: Request for exposing a boolean to show/hide the legend.

### ISSUE THREAD

**Issue by LinweiW** [infor-design/enterprise#6533]
**Is your feature request related to a problem or use case? Please describe.**
There is no flag for us to change show/hide of legend in the calendar.  We need this as a type in the NG project as well please.

**Describe the solution you'd like**
Exposing a boolean to change the state(show/hide) of legend. 

**Describe alternatives you've considered**
We currently hide the legend with css but this means that we are dependent on the component's CSS structure

**Comment by lbursey-infor** [comment]
Hey Tim, just wanted to add that this is for WFM, so we'd need it to be available in the Angular project. Can create a ticket there as well

**Comment by tmcconechy** [comment]
I think the note on here is fine. With that reminder we'll remember

**Comment by tmcconechy** [comment]
Lets add a setting to both EP and Ng so that the legend can be toggled visually

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/calendar/test-hide-legend.html
![image](https://user-images.githubusercontent.com/45757016/186157495-4cced2fb-b33a-42df-898a-4839bcef2dc6.png)
![image](https://user-images.githubusercontent.com/45757016/186157578-a6289178-1ec9-4032-acac-7ad8ccd3f8d5.png)

**Comment by CindyMercadoReyes** [comment]
BDD attached. 
[BDDStory_github_6533.docx](https://github.com/infor-design/enterprise/files/9454249/BDDStory_github_6533.docx)

**Comment by tjamesallen15** [comment]
> QA Passed for Responsive view. Verified in https://main-enterprise.demo.design.infor.com/components/calendar/test-hide-legend.html
> 
> For Clarification: When in max view, the toggle is still visible but the legends are hidden. Is this as expected? @tjamesallen15 @tmcconechy ![image](https://user-images.githubusercontent.com/45757016/186157495-4cced2fb-b33a-42df-898a-4839bcef2dc6.png) ![image](https://user-images.githubusercontent.com/45757016/186157578-a6289178-1ec9-4032-acac-7ad8ccd3f8d5.png)

Yes
