### ISSUE TITLE
Chart: The property tooltip is inconsistent for the different types of charts

### ISSUE THREAD

**Issue by kkoscielski** [infor-design/enterprise#6534]
There is some inconsistency when we are creating the dataset for the different types of charts. The mock data for a pie chart contains the property called tooltip (e.g. tooltip: 'Item D <b>{{percent}}</b>') which allows to display the percentage share of the ‘Item D’ (see the 1st pic). The mock data for a column chart also contains the property called tooltip, but it differs from the previous example. The word “percent” that we have seen between double curly braces is now replaced by the word “value” (e.g. tooltip: 'Custom Tooltip: {{value}}'). If we use the word “percent” instead of “value” and then hover over column in the chart, we will see a message “Custom Tooltip: undefined” (see the 2nd pic).

1. Go to https://stackblitz.com/edit/ids-quick-start-1341-tw2vzo?file=src%2Fapp%2Fchart-column%2Fchart-column.component.ts,src%2Fapp%2Fchart-column%2Fchart-column.component.html,src%2Fapp%2Fchart-pie%2Fchart-pie.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fchart-pie%2Fchart-pie.component.html,src%2Findex.html,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
2. Hover over the first two columns.
3. See the results that will be displayed and compare them with the dataset for the column chart component.
4. The first column will present the name Automotive and its value (see the 3rd pic). The second column will display the name Distribution, but its percentage share will be undefined (see the 2nd pic). The documentation proves that in the case of some types of charts we can use the word “percent” in the tooltip property (e.g. examine the pie chart component and the 1st pic). However, in the case of some other types of charts (e.g. column chart) it is not possible since the displayed percentage share will be undefined.

**Expected behavior**
It is not clarified in the documentation how to set up the property called tooltip for the different types of charts and this inconsistency is very confusing.

**Version**
•	ids-enterprise-ng: ^13.1.1,

**Screenshots**
![image](https://user-images.githubusercontent.com/105841567/171726487-20aec32e-55bb-4cfe-9fa7-3f2225011d2e.png)
![image](https://user-images.githubusercontent.com/105841567/171726579-62a21320-6bd0-4bbe-a4de-64b3e2636b88.png)
![image](https://user-images.githubusercontent.com/105841567/171726634-6a4f5ee4-e017-4d9d-86be-67987951e215.png)

**Comment by tmcconechy** [comment]
It works with these options https://github.com/infor-design/enterprise/blob/main/src/components/pie/pie.js#L580-L584

However, the problem seems to be this is only in the pie chart and no other charts. So this is a good bug. I think we need to:

- make sure this works in all charts
- add the docs

Can probably try to add it here https://github.com/infor-design/enterprise/blob/main/src/components/charts/charts.js#L78

(BTW - note to self i think this will work fine in the future web component version already)
