### ISSUE TITLE
Sinkpage: Toolbar Actions - Scroll bar appears in Search Icon

### ISSUE THREAD

**Issue by iamjamesreyracho** [infor-design/enterprise#6537]
**Describe the bug**
In responsive view, there is a scroll bar appeared below the search icon. It appears on 767px.

**To Reproduce**

1. Go to https://4640-beta0-enterprise.demo.design.infor.com/
2. Scroll down to Toolbar Actions
3. In responsive view, set the px view to 767px.

**Expected behavior**
It shouldn't have scroll bar below..

**Version**

- ids-enterprise: v4.64.0-beta.0

**Screenshots**
Win-FF
![image](https://user-images.githubusercontent.com/98729565/171788011-98e9ce3f-dae4-4161-9ea5-590ae8faeb59.png)

Win-Edge
![image](https://user-images.githubusercontent.com/98729565/171788037-28c97d2d-ece1-4ac1-8ff1-d5ee3838ad3a.png)

Win-Chrome
![image](https://user-images.githubusercontent.com/98729565/171788052-498996d9-17be-4b26-96bf-41739e2c1e7b.png)

**Platform**
 - Browser Name: Chrome, Firefox, Edge (Windows)

**Additional context**
NA

**Comment by tmcconechy** [comment]
I believe this is a duplicate but cant find the other issue

**Comment by ericangeles** [comment]
@tmcconechy yeah, I believe it's been fixed.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
