### ISSUE TITLE
Icon in search field has incorrect alignment when used in a toolbar flex component.

### ISSUE THREAD

**Issue by evikstrom** [infor-design/enterprise#6539]
**Describe the bug**
The magnifying glass icon in the search field is not properly aligned when keyboard focus is in the field. This occurs when the search field is in a toolbar-flex component.

**To Reproduce**

1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/toolbar-flex/example-searchfield-collapsible.html'
2. Click on 'Magnifying glass (search icon)' up to the right
3. See error that the magnifying glass icon is not aligned properly.

**Expected behavior**
The magnifying glass icon should vertically align in the middle when focus is on the search field and the field gets expanded.

**Version**

- ids-enterprise: 4.63.0

**Screenshots**
![image](https://user-images.githubusercontent.com/79518918/171798431-ca6aaa0b-db24-4ef2-98c5-848ee48ee8b4.png)

**Platform**
 - Infor Application/Team Name: Infor OS
 - OS Version: Windows 11
 - Browser Name: Google Chrome
 - Browser Version: 102.0.5005.63 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@evikstrom this has already been fixed in 4.64 (which is now beta). You can see that its fixed here: https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-searchfield-collapsible.html

**Comment by jbrcna** [comment]
this is working as expected. moving this ticket to done. 
https://4640-beta0-enterprise.demo.design.infor.com/components/toolbar-flex/example-searchfield-collapsible.html
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/56722184/172085711-806196ac-cb4c-4ebb-b224-87460a89eee8.png">
Icon in search field has incorrect alignment when used in a toolbar flex component.
