### ISSUE TITLE
Hierarchy control selection event firing multiple times when paging.

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#654]
**Describe the bug**
The selection event fires multiple times (stacks up) when paging back and forth.

**To Reproduce**
1. Go to http://localhost:4000/components/hierarchy/example-paging.html
2. Expand a leaf
3. Go back
4. Expand again
5. In the network observe the request is fetch multiple times after expanded a second time

**Expected behavior**
Should only make one Network request

**Comment by tmcconechy** [comment]
This should have been closed when merged
