### ISSUE TITLE
Toolbar: Up/Down/Left/Right arrow not working with voice over

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6541]
**Describe the bug**
Cant use voice overs nav key on our toolbar. I "think" this is an issue

**To Reproduce**

1. Go to http://localhost:4000/components/bar/example-index.html (or any page)
2. Turn on voice over
3. use `caps lock + left/right arrow` to move through the page
4. once you hit the .. button you cant move

**Expected behavior**
Ignore left right arrow with caps lock down?

**Additional context**
Found testing https://github.com/infor-design/enterprise/pull/6531

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
