### ISSUE TITLE
Typography: Title typography is not consistent

### ISSUE THREAD

**Issue by pbal** [infor-design/enterprise#6542]
**Describe the bug**
Title typography in IDS is not consistent.

h1 is 2.8rem
Rest all h2, h3, h4, are all 1.6rem which is same as body text size.

Verify title font sizes in ids library.

**Expected behavior**
Font sizes should gradually decrease to body size. Probably this setting would work
h1 2.5 rem  
h2 2 rem  
h3 1.8 rem  
h4 1.6rem

**Version**
4.63.0

**Screenshots**
![image](https://user-images.githubusercontent.com/1594975/171909735-42c25fc8-5d22-42af-8127-624e35421802.png)

**Comment by tmcconechy** [comment]
Yeah weird. What file are these in? I think these might be for some place where you can change from h3, h4 ect logically for the right semantic markup but the style doesn't actually change (header subtext for example)

You could try to use these classes as well.
https://main-enterprise.demo.design.infor.com/components/typography/example-index.html

**Comment by pbal** [comment]
h1....h6 should define their size without a class.

Screenshot I took above is from theme-new-dark.min.css from version 4.63.2. Those styles are defined at root.

**Comment by tmcconechy** [comment]
@pbal Can you give us an idea of where these might be placed in the page? Is it like documentation or text or something?

**Comment by tmcconechy** [comment]
cc @danirosefishinfor

**Comment by danirosefishinfor** [comment]
@pbal - would it be possible to share screenshots of the usage for reference? Thanks!
