### ISSUE TITLE
Lookup: Apply with mouse DblClick

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#6546]
**Is your feature request related to a problem or use case? Please describe.**
When setting `autoApply: false` and double clicking on a row nothing happens.

**Describe the solution you'd like**
A new settings for instance `DblClickApply` that will apply the selected row when `dblclick` event is fired.

**Describe alternatives you've considered**
I've tried adding `dblclick` event to Lookup but it doesn't exist. maybe I'm missing something.

**Additional context**
This ability is a standard behavior of Infor M3's browse window (which is similar to Lookup).

Thanks!

**Comment by jonathanamiran** [comment]
The default behavior (`autoApply: true`) might be "too responsive" for the user, mainly when there is large data with filters, if the user accidently clicks on the row it applies, also if the user wants to select text to copy to clipboard it automatically applies.

Also, M3 users are used to this behavior:
https://user-images.githubusercontent.com/34129313/172171529-b1cc9ead-b17f-42fa-ab59-6b1d3e0d892b.mp4

Thanks

**Comment by tmcconechy** [comment]
cc @inforandy

**Comment by jbrcna** [comment]
QA Passed. v4.68.0-dev
