### ISSUE TITLE
TreeGrid: unselectRow is providing incorrect rowData when triggering a deselect

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#6548]
**Describe the bug**
A tree grid with selectable of 'mixed' is providing incorrect rowData for the row being unselected.  Occurs after rows in the tree are collapsed. 

**To Reproduce**

1. Using the attached 'test-tree-multiselect.html'
2. Collapse the task label 'Follow up action with Residential Baltimore'
3. Select the row for the task labeled, 'Follow up action with Residental Housing'
4. Unselect the same row (the one with the task labeled, 'Follow up action with Residental Housing'
5. In the debugger console, notice that the rowData for the unselected row is incorrect
    
    rowData indicates that the task unselected was 'Follow up action with Residental Mexico'
    rowData should be the task unselected of 'Follow up action with Residental Housing'

**Expected behavior**
Passed argument on the deselect event provides the rowData for the row that was unselected.

**Version**
- ids-enterprise: v4.64.0-dev

**Additional context**
Necessary for a new feature being developed in Landmark.  The data in the tree grid is updated as the user expands / collapses tree rows.

**Comment by claudenbach** [comment]
[TreeGridUnselect.zip](https://github.com/infor-design/enterprise/files/8848211/TreeGridUnselect.zip)

**Comment by jbrcna** [comment]
QA Passed
v4.66.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-tree-mixed.html
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/56722184/180351976-6c40595e-e230-431c-a633-fcea4e40a023.png">
