### ISSUE TITLE
Notification: RTL close button position

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#6555]
**Describe the bug**
1. Notification banner's close button position is not pulled to the left side of the screen in RTL mode.
2. There isn't space between `linkText` and `message` when Hebrew or Arabic fonts are used.

**To Reproduce**

1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/notification/example-index.html?locale=he-IL#](https://design.infor.com/code/ids-enterprise/latest/demo/components/notification/example-index.html?locale=he-IL#)
2. See screen
3. Go to [https://jsfiddle.net/sebulbajoe/pq7Lzjsk/9/show](https://jsfiddle.net/sebulbajoe/pq7Lzjsk/9/show)
4. See lack of space

**Expected behavior**
Should be displayed like LTR but "reversed"

**Version**

- ids-enterprise: v4.63.0

**Screenshots**
![image](https://user-images.githubusercontent.com/34129313/172637097-f37de55d-d9bd-4967-a4cf-2daebc1e89c0.png)

**Platform**

 - OS Version: Windows
 - Browser Name: Chrome/Firefox
 - Browser Version: latest

**Additional context**

Thanks

**Comment by tmcconechy** [comment]
Can you check the web component version as well? (to developer)

**Comment by jbrcna** [comment]
this is now working as expected but i notice that the ... is much close to the x icon in` locale=ar-EG`. kindly let me know if i need to file an issue. thanks
https://main-enterprise.demo.design.infor.com/components/notification/example-index.html?locale=he-IL
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56722184/180349712-9757b74f-fe31-4e92-888c-3ef9a5697c87.png">

https://main-enterprise.demo.design.infor.com/components/notification/example-index.html?locale=ar-EG
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/56722184/180350440-0cc35d2c-e29e-4925-9dd9-42f1d59113eb.png">

**Comment by tmcconechy** [comment]
I think thats marginally worth fixing, could add maybe 4px margin, just make a new issue and i'll mark it minor

**Comment by jbrcna** [comment]
thank you for clarifying, Tim. here's the ticket for the new issue https://github.com/infor-design/enterprise/issues/6683
