### ISSUE TITLE
[Mobile] Dropdown Component: Dropdown is closing when scrolling through the items

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#656]
**Describe the bug**
[Mobile] Dropdown is closing when scrolling through the items

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/dropdown/example-index.html on any mobile device
2. Open the dropdown
3. Try to scroll through the items, dropdown will close

**Expected behavior**
User should be able to scroll and view items in the drop down list

**Screenshots**
None

**Platform**
 - iOS, Android Device 
 - Browser Name [FireFox

**Additional context**
None

**Comment by tmcconechy** [comment]
Do you know if this worked on http://490-enterprise.demo.design.infor.com/components/dropdown/example-index.html

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/list
Passed QA testing, bug fix is verified working in all browsers on mobile.
