### ISSUE TITLE
Calendar: Day Shading and Day Legend required in Week and Day view (already present in Month view)

### ISSUE THREAD

**Issue by timothyholton** [infor-design/enterprise#6568]
Currently, the Calendar component caters for:
- The background shading of days (using settings.dayLegend), and
- The display of an associated "day legend" at the bottom of the calendar which shows the meaning of the shading colours (e.g. weekend, public holiday, etc).  However, the above is only available for the **Month** view.  Our (Infor Pathway) customers require the background shading of days and the "day legend" to also be applied to the **Week** and **Day** views.

For example, the following screenshot shows the Calendar in Month view:
- Saturdays and Sundays are shaded grey because they are weekends,
- 7th and 8th July are shaded light green because they are Public Holidays
- 22nd and 23rd July are shaded light grey because they are "Other" days.
- A "day legend" at the bottom showing what the different shades signify.
![image](https://user-images.githubusercontent.com/107448146/173476576-95dd4547-68fe-4072-9ca0-fffa070b173c.png)

However, when viewing the same Calender in Week view and Day view, there is no shading and no "day legend".  The request is for the Calendar component to be enhanced so that these views also shade days and display the "day legend".
![image](https://user-images.githubusercontent.com/107448146/173476754-12235eb1-30d0-4452-b54e-629f83426790.png)
![image](https://user-images.githubusercontent.com/107448146/173476794-4c39ae02-35b0-4b07-8ce6-752f4586a870.png)

For reference only, the following is a screenshot from one form that uses the Calendar component (in Month View) in the Infor Pathway product.
![image](https://user-images.githubusercontent.com/107448146/173477598-53084449-3b23-48a3-b7e7-d546d0a9565a.png)

**Comment by jbrcna** [comment]
QA Passed
https://main-enterprise.demo.design.infor.com/components/calendar/test-legend-day-week-shading.html
<img width="537" alt="image" src="https://user-images.githubusercontent.com/56722184/187606461-81adaa90-1952-4291-a5fc-70634f74cdc2.png">
<img width="535" alt="image" src="https://user-images.githubusercontent.com/56722184/187606476-f2726918-fc38-429a-bb46-8d3b62c38920.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/56722184/187606594-da608f3b-d45d-4db4-ad11-b3ea760dc252.png">
