### ISSUE TITLE
[iOS, Firefox Android] Dropdown Component: Icon and arrow down are not vertically centered

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#657]
**Describe the bug**
[iOS, Firefox Android] Icon and arrow down are not vertically centered

**To Reproduce**
1. Open any browser on iOS and Firefox on Android
2. Go to http://master-enterprise.demo.design.infor.com/components/dropdown/example-icons.html
3. Open the dropdown
4. Select any item
5. Icon and arrow down are not vertically centered

**Expected behavior**
Alignment needed

**Screenshots**
![image](https://user-images.githubusercontent.com/39101346/44544320-d9651b80-a6df-11e8-8313-aa6de311e395.png)

**Platform**
 - iOS, Android (firefox only)

**Additional context**
None

**Comment by ericangeles** [comment]
Seems to work on my iPhone 7 Plus. Test it on Firefox (v.13.2).

**Comment by tmcconechy** [comment]
@CindyMercadoReyes Can you retest this one your end again?

**Comment by ericangeles** [comment]
Was able to replicate on Samsung S8+ Firefox (61.0.2).

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/dropdown/example-icons.html
There is still alignment issue on Android Firefox
![image](https://user-images.githubusercontent.com/39508864/45538172-d8379200-b838-11e8-9b47-3d1b0a680084.png)

**Comment by tmcconechy** [comment]
@ericangeles can you also fix up this layout issue? Thanks

**Comment by ericangeles** [comment]
For sure.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this GitHub ticket to the Done folder.
