### ISSUE TITLE
[Mobile] Dropdown Component: Layout issue on Example States page

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#658]
**Describe the bug**
[Mobile] Layout issue on Example States page

**To Reproduce**
1. Open any browser on any mobile device
2. Go to http://master-enterprise.demo.design.infor.com/components/dropdown/example-states.html
3. Notice the layout issue

**Expected behavior**
Should not have layout issues

**Screenshots**
![image](https://user-images.githubusercontent.com/39101346/44544409-1f21e400-a6e0-11e8-99f4-2f371044d183.png)

**Platform**
 - All Mobile

**Additional context**
None

**Comment by tmcconechy** [comment]
This issue will be closed via a PR on #1136 since this page is being moved to a test page/unit test.
