### ISSUE TITLE
Locale: Different strings required for "Less Than" / "Less Than Or Equals" / "Greater Than" / "Greater Than Or Equals" filtering options

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#6587]
Locale: Multiple strings required for "Less Than" / "Less Than Or Equals" / "Greater Than" / "Greater Than Or Equals" filtering options

- Less Than
- Less Than Or Equals
- Greater Than
- Greater Than Or Equals

are used in different contexts

LessThan: { id: 'LessThan', value: 'Less Than', comment: 'Less Than in icons for filtering' }
LessOrEquals: { id: 'LessOrEquals', value: 'Less Than Or Equals', comment: 'Less Than Or Equals in icons for filtering' }
GreaterThan: { id: 'GreaterThan', value: 'Greater Than', comment: 'Greater Than in icons for filtering' }
GreaterOrEquals: { id: 'GreaterOrEquals', value: 'Greater Than Or Equals', comment: 'Greater Than Or Equals in icons for filtering' }

Examples:
![image](https://user-images.githubusercontent.com/66057969/174332284-37410aa1-c4e3-4172-81a9-24576320f26c.png)

In some languages, for example, the translation of "Less Than" is not valid / appropriate when used with a date.

For dates, would it be possible to create / use new strings e.g.
- Earlier Than
- Earlier Than Or Equals
- Later Than
- Later Than Or Equals

**Comment by tmcconechy** [comment]
Should be fixed in the web in components as well

**Comment by cpinatel7** [comment]
Either way but "equals" options are probably more standard:

Microsoft:
![image](https://user-images.githubusercontent.com/66057969/178781721-5f4e65ae-f611-4d6c-8806-d585c4aeb39d.png)

Thanks for your help

**Comment by GlenlieMaye** [comment]
QA tested and passed.

_**Before Fix:**_
https://4500-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/102151352/179945803-e8f0c996-6eb2-4ae8-b9ba-5bb7c60af721.png">


**_After Fix:_**
https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/102151352/179945676-7d9ee5df-3e48-4d26-ab96-e69518188109.png">

**Comment by tmcconechy** [comment]
@cpinatel7 should we try and make these "standard" in the filter menu? I see we only added them in a custom example https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html

Plus the translations need to be checked...

**Comment by cpinatel7** [comment]
re: make these "standard" in the filter menu
I'm not sure what you mean by standard but these filter entries are used for dates (periods) only.

We've noticed that this fix has been released but translations are not available e.g.

![image](https://user-images.githubusercontent.com/66057969/222193266-47b09bcd-e436-4ae4-b918-65dee8b3f65f.png)

**Comment by tmcconechy** [comment]
They should be in this months translation package. What i mean is should we make all date filters show these items by default? Or is it ok to make this something custom (vs the previous labels)

**Comment by cpinatel7** [comment]
Ok, I see what you mean. All **date filters** should use these items by default. I thought this was already like this. Thanks

**Comment by tmcconechy** [comment]
Ok this needs some corrections when we get this strings back. I also missed a translation drop with some of these.... So will take care of finalizing this next version

**Comment by yohannahbautista** [comment]
Hello, the date filters should use the strings by default. I checked this example and all date and time pickers have it: https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html

**Comment by tmcconechy** [comment]
Oh my mistake. It does seem fixed https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?locale=de-DE 

May need a few more languages I'll drop them in next time

**Comment by cpinatel7** [comment]
@tmcconechy 

These new strings are untranslated in several Infor products e.g.
![image](https://github.com/infor-design/enterprise/assets/66057969/31025146-3124-46d1-9b69-0b483725be66)

Can you let me know the EP version that includes these translations in all languages?

Thanks

**Comment by tmcconechy** [comment]
They are definitely translated on the latest version [4.84.2](https://www.npmjs.com/package/ids-enterprise/v/4.84.2)
If using angular NG 15 its in -> [15.4.4](https://www.npmjs.com/package/ids-enterprise-ng/v/15.4.4)
If using angular NG 16 its in  -> https://www.npmjs.com/package/ids-enterprise-ng/v/16.4.1

**Comment by cpinatel7** [comment]
Thanks

**Comment by cpinatel7** [comment]
Not fixed / regression. Version: 4.92.0

![image](https://github.com/infor-design/enterprise/assets/66057969/87b3bfed-8478-4460-b056-d80ef4062d51)

Earlier / Later strings do not seem to be used anywhere in Landmark. These strings (and translations) should be used for all date filtering controls.

**Comment by tmcconechy** [comment]
@cpinatel7 the earlier then does work in our examples https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html

<img width="577" alt="Screenshot 2024-05-09 at 9 43 39 AM" src="https://github.com/infor-design/enterprise/assets/814283/778bc644-f518-4e49-8a97-6c08298813b2">

I think they may need to either adjust any customized strings they are using for filters or use a date type filter like our example on the landmark end.
