### ISSUE TITLE
Datagrid: Editor does not outline the cell when a text area cell has multiple lines

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6588]
**Describe the bug**
The editor of a cell will not outline the full cell when in the same row as a text area cell with multiple lines. It keeps the defined row height as an outline of the cell.

**To Reproduce**
1. Please use this zipped html file: 
[test-text-area-with-editor.zip](https://github.com/infor-design/enterprise/files/8930899/test-text-area-with-editor.zip)
2. Click on the cell that says "Assemble Paint" to edit
Result: The editor keeps the defined row height and does not outline the entire cell.

**Expected behavior**
It is expected that when editing a cell, the editor outlines the cell.

**Version**
- ids-enterprise: v4.64.0-dev

**Screenshots**
![Text Area Editor Outline](https://user-images.githubusercontent.com/76002134/174390159-ecc2fb62-286a-42d5-9528-c8a6ac6f9a93.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 102.0.5005.115 (Official Build) (64-bit)

**Comment by janahintal** [comment]
QA Passed. 
![image](https://user-images.githubusercontent.com/45757016/181433531-bad8b002-23a3-440a-a7be-3ad1b89eebf3.png)
![image](https://user-images.githubusercontent.com/45757016/181433700-38b6e388-a984-432e-b8cc-b229a5227e7c.png)
