### ISSUE TITLE
[iOS] Dropdown Component:Validation is not triggering

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#659]
**Describe the bug**
[iOS] Validation is not triggering

**To Reproduce**
1. Open any browser on any iOS device
2. Got to http://master-enterprise.demo.design.infor.com/components/dropdown/example-validation.html
3. Open the dropdown
4. Leave the dropdown blank
5. Required error message won't be displayed

**Expected behavior**
Validation should be triggering

**Screenshots**
None

**Platform**
 - iOSDevice

**Additional context**
None

**Comment by tmcconechy** [comment]
Its only going to show when you tab out on blur on this example. So you can make it show by clicking some with element (like the ... menu). Maybe there is a better way for this for mobile but its not incorrect per say just mobile friendly.

**Comment by EdwardCoyle** [comment]
May want to address this on any mobile setting by checking for [`env.features.touch`](https://github.com/infor-design/enterprise/blob/master/src/utils/environment.js#L18).  In the Dropdown component code that handles closing lists, we should fire a `blur` event in touch environments only to ensure that validation occurs.  We might also want to check this against the Multiselect component too, check for differences in the selected list items, and also fire a `change` event here.
