### ISSUE TITLE
ListView: Any toolbar-flex gets a "selection title" if it is wrapped under widget class with soho-listview as a sibling

### ISSUE THREAD

**Issue by arturchilangwa-infor** [infor-design/enterprise#6591]
**Describe the bug**

`SohoListViewComponent` adds a "Selected  1" text on any flexbox component sibling to list-view which is wrapped under `widget` class . 

```html
<div class="widget">
  <soho-toolbar-flex>
    <h2>
      {{ 'My Title ' }}
    </h2>
  </soho-toolbar-flex>

  <!-- New title is inserted here -->

  <soho-listview [dataset]="listData">
    <li soho-listview-item *ngFor="let contextItem of listData">
      <h2>{{ contextItem.name }}</h2>
    </li>
  </soho-listview>
</div>
```

![u8mdFGiKhM](https://user-images.githubusercontent.com/80833325/174816358-4188a682-8840-491a-8046-d9f20bb24aca.gif)

I reproduced the issue in this [Stackblitz](https://stackblitz.com/edit/ids-quick-start-1401-newcgl?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts) app.

This change is related to these two: 
* PR: https://github.com/infor-design/enterprise/commit/4534c103adf801fc1be128179fafbf00ab1348aa 
* Issue: https://github.com/infor-design/enterprise-ng/issues/1249 

**To Reproduce**
1. Select a element on a list

**Expected behavior**
Nothing should happen with the flex-toolbar, no text should be added 

**Version**
- ids-enterprise-ng: v14.0.1 (Forked my Stackblitz from here [this one](https://stackblitz.com/edit/ids-quick-start-1401?file=src%2Fapp%2Fapp.component.ts))

**Platform**
 - OS Version: Windows 10
 - Browser Name Chrome,
 - Browser Version: 102.0.5005.115 (Official Build) (64-bit)

**Additional context**
I think a solution would be to add a new class for the multiselect which is then chosen when adding the "Selected text".

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/listview/test-multiselect-flex.html

<img width="1678" alt="Screen Shot 2022-06-30 at 1 37 37 PM" src="https://user-images.githubusercontent.com/45757016/176600932-b0307420-cdb0-490d-a273-365c4f8a421b.png">
