### ISSUE TITLE
AppMenu: Unflilter error when typing in any input field

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6592]
**Describe the bug**
Clicking in any input will trigger an error if an app menu is invoked (only seen in the NG projects).

**To Reproduce**

1.  Clone https://github.com/infor-design/enterprise-ng-quickstart
2. `npm i`
3. `npm run start`
4. go to http://localhost:4200/ and open app menu
5. type anything in the filter
6. See error

Also if you were to put an input in the page it would also error.

**Expected behavior**
No errors

**Additional context**
Ms Teams

**Comment by janahintal** [comment]
Working as expected in http://localhost:4000/components/applicationmenu/example-filterable.html http://localhost:4000/components/applicationmenu.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
