### ISSUE TITLE
Rating: Readonly mode issue

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6595]
**Describe the bug**
Upon clicking the "Example Readonly", the stars are clickable while it is in the "Make Enabled" button/Readonly mode.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/rating/example-readonly.html
2. Click on stars
3. See error

**Expected behavior**
The stars should not be clickable when in Readonly mode.

**Version**

- ids-enterprise: 4.64.0-dev

**Screenshots**

https://user-images.githubusercontent.com/102151352/174931571-04cd2977-6261-4f65-832f-6658d2c1f7b2.mov

**Platform**
- All major browsers

**Comment by ericangeles** [comment]
Need to improve the test page.
