### ISSUE TITLE
Build - Incorrect scss file in Chrome when debugging

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#6596]
**Describe the Issue**

When debugging CSS issues using dev tools, it shows incorrect file/s in Chrome but it looks okay in other browsers like Firefox. It's not a show-stopper but it's something that needs to fix as we use Chrome as the default browser.

**To Reproduce**
Steps to see the question or problem:

- Go to any of the components test pages https://main-enterprise.demo.design.infor.com/components/list e.g., [Header](https://main-enterprise.demo.design.infor.com/components/header/example-index.html)
- Inspect the search icon
- Check the stylesheets in dev tools
- It shows incorrect file

![err](https://user-images.githubusercontent.com/8839327/174975665-491e4d0b-d55d-4bfc-9623-2541363a7c68.png)

**Comment by tmcconechy** [comment]
Weird? Is it possibly an issue in chrome?

**Comment by tmcconechy** [comment]
I guess i would try to update some of the dependencies in package.json (related to sass/rollup). Do you remember seeing this @EdwardCoyle
