### ISSUE TITLE
CAP: example-notification btn-actions misaligned mobile view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6602]
**Describe the bug**
... or btn-actions is not visible in iOS and misaligned in android

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-notification.html
2. Open CAP
3. See error

**Expected behavior**
should be visible and properly aligned

<img width="264" alt="image" src="https://user-images.githubusercontent.com/56722184/175316975-5b78b493-a139-4ba9-82b5-ca8179a6a9f9.png">

**Version**

- ids-enterprise: v4.64.0-dev / main

**Screenshots**
<img width="634" alt="image" src="https://user-images.githubusercontent.com/56722184/175317256-a02905b8-699e-4915-b4dc-8d31e6c5bee1.png">

**Platform**
Android & iOS mobile

**Additional context**

**Comment by jbrcna** [comment]
this is now working as expected.
v4.84.0-dev
<img width="395" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/cfd1721c-0860-4f75-bf17-c58d617553dd">

**Comment by tmcconechy** [comment]
Closing stale issues
