### ISSUE TITLE
Tabs Module: responsive issue

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6606]
**Describe the bug**
Tabs Module: Sortable responsive issue

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-sortable.html & https://main-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html#module-tabs-controls
2. Minimize the screen 

**Expected behavior**
All fields should render properly without any alignment issue

**Version**
IDS 4.65 - DEV

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/175942445-f9c08e86-2457-423b-a430-451ef2391d52.png)
![image](https://user-images.githubusercontent.com/45757016/175942521-a34be85c-96b7-4cee-894a-fe31313313c0.png)

**Platform**
All major browser, OS and devices

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Not that worried about the modal fields as its just an example and you can scroll. But i think we need to fix the button zindex issue.

**Comment by tmcconechy** [comment]
I think this is fixed. Lets recheck/QA it please

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
