### ISSUE TITLE
Datagrid: Add filter type options for Is Zero and Is Not Zero

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#6612]
**Is your feature request related to a problem or use case? Please describe.**
We have some special search functionality, and consider 0 to be an empty value for number fields. For clarity, it would be nice to have  Is Zero/Is Not Zero options in the filter type dropdown on datagrid. 

Either adding entirely new options or allowing us to pass in a label for the current Is Empty/Is Not Empty options would work.

And what application do you work on? Landmark

**Comment by tmcconechy** [comment]
@inforandy

**Comment by tmcconechy** [comment]
After discussing this - this seem redundant with "equals zero" and "does not equals zero" so seems redundant so we decided it wouldn't add much value to add.
