### ISSUE TITLE
Tooltip event handlers created on show not cleaning up properly on hide

### ISSUE THREAD

**Issue by tfavorite** [infor-design/enterprise#6613]
**Describe the bug**
In tooltip.js, detachOpenEvents doesn't have the following line like some other members of tooltip:
`const self = this;`
meaning that the event handlers created in show, ie:
`keydown.${COMPONENT_NAME}-${self.uniqueId}`

are not torn down in detachOpenEvents (called by hide).
This could be fixed by either adding `const self = this` to that method, or changing self to this.

**Version**

- ids-enterprise: 4.64.0-dev

**Platform**
 - Infor Application/Team Name: Nexus

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
