### ISSUE TITLE
Toolbar search field looks cut off 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6615]
**Describe the bug**
Toolbar search field looks cut off 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-alternate-style-with-categories.html
2.  Notice the search field looks cut off on one side and still looks cut off after expanding

**Expected behavior**
Search bar / field should not look cut off

**Version**
4.65 - dev

**Screenshots**
<img width="360" alt="Screen Shot 2022-06-30 at 4 24 36 PM" src="https://user-images.githubusercontent.com/45757016/176629756-5571c923-6e23-4f67-a790-5017a0eba31b.png">
<img width="434" alt="Screen Shot 2022-06-30 at 4 25 36 PM" src="https://user-images.githubusercontent.com/45757016/176629946-1849c980-ad9f-4c9d-b9fb-7a3092c4d619.png">

**Platform**
All major browser & OS. 

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Possible regression here with the search fixes @ericangeles ?

**Comment by ericangeles** [comment]
@tmcconechy probably. Am just not sure what will be the ideal design/look in the example page.

**Comment by tmcconechy** [comment]
actually maybe this one isnt that important is it was messed up before https://4530-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-alternate-style-with-categories.html

we can do it later. but i think would i would do is it shows as just the icon:
<img width="59" alt="Screen Shot 2022-06-30 at 9 05 18 AM" src="https://user-images.githubusercontent.com/814283/176684448-02db3180-4850-42c2-bf88-b7897d8c42a5.png">

then when you expand it it shows will all the borders in place.
<img width="282" alt="Screen Shot 2022-06-30 at 9 06 26 AM" src="https://user-images.githubusercontent.com/814283/176684682-225f3546-e223-48e1-b6b3-a7b1b44b4397.png">

**Comment by ericangeles** [comment]
@tmcconechy gotcha!

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
