### ISSUE TITLE
Tabs Module: Missing category border when focusing searchfield

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6618]
**Describe the bug**
When the searchfield or category dropdown is focused, the searchfield shifts and the category dropdown's border is hidden.

**To Reproduce**
1. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button.html
2. Click on the searchfield
Note that the searchfield is slightly larger and the category dropdown's border is hidden.
4. Click anywhere on the page to cause the searchfield to go back to normal
5. Click on the category dropdown
Note that the searchfield is slightly larger and the category dropdown's border is hidden again.

**Expected behavior**
When clicking on the category button or searchfield, the category dropdown border should still be visible and the searchfield should remain the same size.

**Version**
- ids-enterprise: 4.64.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/76002134/176905929-afc348fb-ba3f-445b-8422-ec020367ae2d.png)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 103.0.5060.66 (Official Build) (64-bit)

**Additional context**
On initial load of our home page we focus the searchfield which shows the issue, so this issue is a higher priority for us. Thanks!

**Comment by tmcconechy** [comment]
cc @ericangeles 
@s-werking yes i see the issue (doesn't look that great). Will fix it next sprint. We can patch this just remind me if i forget and i can patch it where you need.

**Comment by s-werking** [comment]
Sounds good, thanks @tmcconechy

**Comment by GlenlieMaye** [comment]
QA tested and the bug is already fixed. However, the width of the search text box shrinks upon typing.

https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button.html



https://user-images.githubusercontent.com/102151352/181701762-51ef7787-3727-4382-a6c3-547dc3098466.mov

**Comment by awbuboltz** [comment]
Would it be possible to fix this and https://github.com/infor-design/enterprise/issues/6686? The seachfield is the main source of navigation for our product and the first thing we focus when people log in. These visual issues in the search leave a bad impression and although considered minor, they give the product a bad look and feel from the start.

**Comment by tmcconechy** [comment]
We do have this fixed (minus one failed issue) but the other issue came in after so will be fixed this coming new sprint.
But once they are all fixed we can put together a patch

**Comment by awbuboltz** [comment]
Cool, thanks Tim. I didn't actually see that you moved #6686 right before my comment.
