### ISSUE TITLE
[All Browsers] Modal: X button is out of position

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#662]
**Describe the bug**
[All Browsers] Modal: X button is out of position (bottom-right of the modal)

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/modal/example-close-btn.html
2. Click on Show Modal button
3. Notice that the X button is in the bottom-right of the modal

**Expected behavior**
X button should be on the top-right of the modal

**Screenshots**
<img width="339" alt="screen shot 2018-08-24 at 3 49 14 pm" src="https://user-images.githubusercontent.com/39508864/44572115-734ac800-a7b5-11e8-8a1b-2f92f1d3f66d.png">

**Platform**
 - All OS and Browsers

**Additional context**
No additional context

**Comment by tmcconechy** [comment]
@ericangeles can you look at this please. i think this was introduced because of the fix you made on https://github.com/infor-design/enterprise/pull/602 so we need another fix so both cases work...

**Comment by brianjuan** [comment]
Issue is still occurring on http://4100-rc0-enterprise.demo.design.infor.com/components/modal/example-close-btn.html
but not on http://master-enterprise.demo.design.infor.com/components/modal/example-close-btn.html

**Comment by clepore** [comment]
@ericangeles Did a pull request for the fix into the master branch, rather than the release branch where this failed. I will cherry-pick the fix over.
