### ISSUE TITLE
FileUploadAdvance: Issue with maximum file in components

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#6625]
**Describe the bug**
Cannot add more files after removing previously added files.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/test-max-files.html
2. Add two files
3. Remove one file
4. Add another file (it will error)

**Expected Behavior**
Should always guard against exactly two.

**Version**
- ids-enterprise-ng: 14.0.3

**Comment by jbrcna** [comment]
this is now working as expected.  moving this ticket to done. 
**Observation**
on my first couple of tries i was able to upload 3 files after removing one file  (one after the other). 
<img width="515" alt="image" src="https://user-images.githubusercontent.com/56722184/178172882-ac24c7f2-bcd9-4d0e-82f0-ddd34a02e56e.png">

However, when i try it again after about an hour it was working as expected. 
<img width="731" alt="image" src="https://user-images.githubusercontent.com/56722184/178175254-d4cbf768-d373-4acb-aab0-a616ca4428af.png">
