### ISSUE TITLE
Textarea: Convert Protractor tests to Puppeteer

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#6629]
**Is your feature request related to a problem or use case? Please describe.**
Convert Textarea component protractor tests to puppeteer.

**Describe the solution you'd like**
Convert all test scenarios in protractor to puppeteer. The naming can be, `{component}.puppeteer-spec.js`

**Comment by CindyMercadoReyes** [comment]
This ticket is now resolved.
