### ISSUE TITLE
Dropdown with Icon: There's an extra Search icon at the bottom when searching

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#663]
**Describe the bug**
[All Browsers] Dropdown with Icon: There's an extra Search icon at the bottom when searching

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/dropdown/example-icons.html
2. Click on the Dropdown field, then clear the content
3. Type "Icon with" in the Search field
4. Notice the extra Search icon at the bottom of the Dropdown

**Expected behavior**
Extra Search icon should not be displayed

**Screenshots**
<img width="492" alt="screen shot 2018-08-24 at 5 31 30 pm" src="https://user-images.githubusercontent.com/39508864/44577434-abf19e00-a7c3-11e8-8669-6d81d4047867.png">

**Platform**
 - All browsers in Mac and Windows

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Seeing this on all the way back to 460.

**Comment by EdwardCoyle** [comment]
@tjamesallen15 regarding the changes for this in #713... The fact that the icon gets swapped out during dropdown filtering isn't an accident.  Under normal circumstances, the icon will change from the "arrow" to the "magnifying glass" when filtering is occurring, and will switch back to the arrow when filtering is cleared or reset.  See the GIF below running against http://master-enterprise.demo.design.infor.com/components/dropdown/example-index.html:

![aug-30-2018-12_51-pm](https://user-images.githubusercontent.com/3249601/44867058-da082f80-ac54-11e8-8a59-1d84ec79c31c.gif)

The issue being reported here is specific to Dropdown components that (optionally) have an icon associated with each list item.  I suspect that the code that normally targets the Dropdown's arrow is mistakenly targeting a different icon (there is sometimes a second icon in the Dropdown's list, if the currently-selected item has one).  Notice in the GIF below that both the actual arrow and the mistaken one are both changing to a magnifying glass during filtering, AND that the icon associated with the selected item disappears on the first attempt at filtering:

![aug-30-2018-12_53-pm](https://user-images.githubusercontent.com/3249601/44867238-471bc500-ac55-11e8-84bb-86232950ce6b.gif)

So, I think the true fix here is to make sure that the icon representing the dropdown arrow and magnifying glass is correctly targeted for replacement, and that the optional icon for selected dropdown items is not targeted.

**Comment by brianjuan** [comment]
http://localhost:4000/components/dropdown/example-icons.html
http://master-enterprise.demo.design.infor.com/components/dropdown/example-icons.html
Passed QA testing across all browsers in Mac and Windows
