### ISSUE TITLE
Searchfield: Difficult/Impossible to clear contents by clicking the "X" button

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#6631]
**Describe the bug**
In Mac OSX Safari, it's currently difficult/impossible to clear the contents of the Searchfield by using the mouse.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-toolbar-flex-with-basic-searchfield.html 
2. Enter some text into the Header searchfield to display the "X" button
3. Try to click around the X button.  On the first click, it may clear the contents.  On subsequent clicks, it no longer clears the Searchfield contents

![Untitled_-Jul-6-2022-11_51-AM](https://user-images.githubusercontent.com/3249601/177592249-1da950da-94e4-4328-a808-0cda372813a8.gif)

**Expected behavior**
It should be possible to click the "X" button to easily clear searchfield contents

**Version**
- ids-enterprise: Latest

**Platform**
 - Browser Name: Safari

**Additional context**
Reported from the M3 team by @inforrpunay

**Comment by tmcconechy** [comment]
@ericangeles maybe combine with the other search issues in this sprint?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
