### ISSUE TITLE
Node 16: Update all Dependencies and Use Node LTS

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6634]
**Describe the bug**

- [x] check ncu ~ check each dependency
- [x] use the LTS node in .nvmrc
- [x] update d3?
- [x] update jquery 

Note: https://github.com/infor-design/enterprise/issues/6912

**Comment by tmcconechy** [comment]
For soon but later... TBD

**Comment by tmcconechy** [comment]
We wanted to stay on LTS just to avoid problems with dependencies (not everyone seems to have every dependency upgraded and working we use for builds/sass ect). We could possibly try 18 but think i'd rather just stay on whatever is LTS and do that in a year.

**Comment by ericangeles** [comment]
@tmcconechy I will definitely do! Thanks!

**Comment by danielortiz1982** [comment]
@tmcconechy @ericangeles Thanks for getting ahead of this issue.
