### ISSUE TITLE
Error in console when click on rating component

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#664]
**Describe the bug**
Console error when clicking on the rating component

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/rating/example-index?font=source-sans
2. Click on rating component
3. Go to console to see error

**Expected behavior**
No error should be in console

**Screenshots**
https://i.imgur.com/I4oWFVw.png

**Comment by tmcconechy** [comment]
This issue appears to have been fixed already in 4.10 you can see its working here http://master-enterprise.demo.design.infor.com/components/rating/example-index.html

**Comment by guoliang** [comment]
Is there a patch for this fix on 4.9.0, or can be patched to 4.9.0?

**Comment by tmcconechy** [comment]
We are freezing 4.10 today and a beta will be available today to test. Releasing 4.10 in one week.
The problem is QA is working on 4.10 so we dont have resources for QAing a patch release as well.
