### ISSUE TITLE
Listview: bind 0 to template

### ISSUE THREAD

**Issue by pbal** [infor-design/enterprise#6640]
In listview component, any property in dataset that has 0 is not bound to component. If dataset is updated to "0", it works.

**To Reproduce**
Pass this dataset to listview with following template
```
[{
  "someProperty": 0
}]
```

Template property on listview
```
<ul>{{#dataset}}<p class="listview-heading">Task #{{someProperty}}</p></li>{{/dataset}}</ul>
```
In this case 0 is not rendered on template.

However if 0 is passed on as a string within dataset, template refects 0 in DOM.

**Expected behavior**
int 0 and string 0 should both render when applied from template.

**Version**
4.63.2

**Comment by tmcconechy** [comment]
@pbal what app is this for? just wondering

**Comment by jbrcna** [comment]
QA Passed
v4.67.0-dev
https://main-enterprise.demo.design.infor.com/components/listview/test-listview-zero.html
<img width="778" alt="image" src="https://user-images.githubusercontent.com/56722184/185913807-1d7f4628-173b-461d-aecd-297ab1f13a34.png">
