### ISSUE TITLE
Datagrid: example-paging-client-side overlapping search icon in mobile view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6650]
**Describe the bug**
 overlapping search icon in mobile view

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-paging-client-side.html
2. Click on searchfield
3. Input some text
4. Click anywhere on the page to lose focus
5. See error

**Expected behavior**
<img width="175" alt="image" src="https://user-images.githubusercontent.com/56722184/178402732-a3d2d48b-fc5f-4947-8ddb-19521b41e392.png">

**Version**

- ids-enterprise: v4.66.0-dev

**Screenshots**
<img width="179" alt="image" src="https://user-images.githubusercontent.com/56722184/178402770-9f63b65e-8b38-4ef1-a20d-1d22f35a0d75.png">
<img width="201" alt="image" src="https://user-images.githubusercontent.com/56722184/178402779-73326ecd-b440-490f-a411-93369cfa6f48.png">

**Platform**
iOS and Android

**Additional context**

**Comment by ericangeles** [comment]
For the dev who will pick up, follow the styling of the searchfield here https://main-enterprise.demo.design.infor.com/components/searchfield/example-index
