### ISSUE TITLE
Disable 't' for Today Input In DatePicker

### ISSUE THREAD

**Issue by anton-kurilov** [infor-design/enterprise#6653]
**Is your feature request related to a problem or use case? Please describe.**
For Date Formats that use letters we want to avoid 't' to be a shortcut to 'Today' and instead continue typing in the month name such as 'Sep**t**ember'

**Describe the solution you'd like**
Add a new setting to the Datepicker API that lets you disable the 'Today' shortcut

**Describe alternatives you've considered**
Use number only date formats. Not a good solution for international clients, and localization in general.

**Additional context**
Add the setting here: https://github.com/infor-design/enterprise/blob/main/src/components/datepicker/datepicker.js#L376

**Comment by tmcconechy** [comment]
@anton-kurilov very similar issue being fixed here: https://github.com/infor-design/enterprise/pull/6648
Maybe you can review and we can fix it along side

**Comment by anton-kurilov** [comment]
@tmcconechy I think I was going to do something similar so I agree with you that it would make sense to fix it along the way with a todayWithKeyboard setting being introduced as part of #6648

**Comment by ericangeles** [comment]
@tjamesallen15 FYI

**Comment by tjamesallen15** [comment]
> @tjamesallen15 can you do a PR for the new settings https://github.com/infor-design/enterprise/pull/6648/files#diff-1ad6f4ace935f015f962a1f530e78f06bd6372a230b7759d02a9f783ef842309R152-R153 they would need to be added to NG as well. Thanks!!

okay will do!

**Comment by anton-kurilov** [comment]
@tjamesallen15 how will I know when this is the in the angular project? Just given that this issue is closed, is there another issue I should track? Thanks!

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/datepicker/test-datepicker-today-increment-key.html

**Comment by ericangeles** [comment]
@tjamesallen15 can you add this fix to the NG project?

**Comment by ericangeles** [comment]
@anton-kurilov we'll add this to the next release.

**Comment by tjamesallen15** [comment]
https://github.com/infor-design/enterprise-ng/pull/1344

it was already added 7 days ago @ericangeles , @anton-kurilov
