### ISSUE TITLE
Datagrid: Render issue with editable alerts

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#6663]
**Describe the bug**
A render issue with a column that contains an alert and whose editor has a trigger icon .

**To Reproduce**
1. Using the attached 'test-editable-alerts.html'
2. Look at the Action column - notice the alert icon is not visible
3. Mouse over a value in the Action column - notice the hover action

**Expected behavior**
Expect the alert icon to be visible and not having a hover (or mouse over) change occurring.
Seeing this same behavior on any column editor that has a trigger icon with an alert.

**Version**
- ids-enterprise: v4.66.0-dev

**Additional context**
Have a Landmark regression ticket attached to this issue.  Apparently this was last working in v10.14.0 (v4.61).

**Comment by claudenbach** [comment]
[EditableAlerts.zip](https://github.com/infor-design/enterprise/files/9132813/EditableAlerts.zip)

**Comment by claudenbach** [comment]
Landmark example were is was working...

![Alert-Icon-Trigger-Not-Working](https://user-images.githubusercontent.com/39804038/179551684-193c5764-5310-4017-a38a-58a13d6f7405.gif)

**Comment by tmcconechy** [comment]
@ericangeles where you able to determine which issue this is on? Or have a suggestion? I can look but when i tried i really wasnt sure which issue might have caused this.
@tmcconechy Note to self: patch with https://github.com/infor-design/enterprise/pull/6655 into 4.65.x

**Comment by ericangeles** [comment]
@tmcconechy not yet but am looking now.

**Comment by claudenbach** [comment]
Noticed when using the attached sample, if I change the row height to Extra Small or Small (which is what Landmark uses), then the error icon's margin-left property becomes a margin-left: -26px.  This doesn't seem correct?  

![Icon-Error-Margin-Left](https://user-images.githubusercontent.com/39804038/179825407-5211d220-59e2-47ad-84e3-4852ade8e6a2.gif)

**Comment by claudenbach** [comment]
I've updated the test to be more realistic...

[EditableAlertsUpdate.zip](https://github.com/infor-design/enterprise/files/9151756/EditableAlertsUpdate.zip)

**Comment by tmcconechy** [comment]
Closing but working through patches

**Comment by tmcconechy** [comment]
Can you help to fix this on all branches? For some reason this doesn't work on 4.62.x and maybe others.

This tomorrow Enrico Angeles ? I think we need to put test-editable-alerts.html in each branch 4.62.x - 4.63.x - 4.64.x 4.65.x and see if you can push a fix for each one on the branch?

I think the tests are:
- check each row height that the icon
- select one dropdown
- check each row height that the icon is still ok

I did it on 4.62.x the code is pushed but its not working....

**Comment by claudenbach** [comment]
I've updated the test to match more closely to Landmark.

[Test-Editable-Alerts.zip](https://github.com/infor-design/enterprise/files/9154663/Test-Editable-Alerts.zip)

**Comment by jbrcna** [comment]
QA Passed
v4.66.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-alerts
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56722184/180115907-567c9c40-3e98-4efe-bb0d-6e37865015f5.png">

**Comment by claudenbach** [comment]
Here's my last change to the test for completeness (added another trigger test for a date icon)...

[Test-Editable-Alerts-Improved.zip](https://github.com/infor-design/enterprise/files/9155898/Test-Editable-Alerts-Improved.zip)
