### ISSUE TITLE
Icons: Add new icons

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6666]
**Describe the Feature**
Task is to add new icons to the code:
'interaction' and the other one with left pointing arrow is 'interaction-reply'

**Expected behavior**
Two new icons

**Additional context**
NA

**Comment by GlenlieMaye** [comment]
QA Passed.
https://main-enterprise.demo.design.infor.com/components/icons/example-index.html

https://user-images.githubusercontent.com/102151352/180767421-5fea4217-3e1a-4e89-9b2b-2f21b0316f79.mov
