### ISSUE TITLE
Page Patterns: Row Height resizing issue

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6672]
**Describe the bug**
Resizing of row height is not working.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/page-patterns/example-master-detail.html
2. Click on ellipses on the "My Assets" table
3. Click any row height size (Extra Small, Small, Medium or Large)

**Expected behavior**
Row height should be changed upon choosing any row height.

**Version**

- ids-enterprise: 4.66.0-dev

**Screenshots**

https://user-images.githubusercontent.com/102151352/179971740-7fa0ca88-a908-46c1-a37c-8a41dcb31409.mov

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
The problem is probably only that its not wired up right in the settings (see toolbar options)
