### ISSUE TITLE
ModuleTabs: Active tab and toolbar color mismatch

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise#6673]
**Describe the bug**
Previously, we reported [this issue](https://github.com/infor-design/enterprise-ng/issues/1245) where the background color for active and inactive tabs are the same when you use a color other than the default. This has been resolved but we noticed that there is now a difference in the background color of the active tab and the background color of the header inside that tab.

**To Reproduce**

1. Go to 'https://design.infor.com/code/ids-enterprise/4.63.0/demo/components/tabs-module/example-index.html?colors=0066D4'
2. Observe that the active tab "New Tab Builder" is now brighter compared to the other tabs that are inactive.
3. Observe also that "Module Tabs" matches the background color of the inactive tabs instead of the active tab which is not what we expect.

**Expected behavior**
We are expecting the same color scheme [as this sample from 4.52.0](https://design.infor.com/code/ids-enterprise/4.52.0/demo/components/tabs-module/example-index.html?colors=0066D4) where the background color of that active tab and header inside that tab are the same.

**Version**

- ids-enterprise: 4.63.0

**Screenshots**

**Platform**
- OS Version: Windows 10
- Browser Name: Chrome
- Browser Version: 98.0.4758.102 (Official Build) (64-bit)

**Additional context**

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/tabs-module/example-index.html#order-entry thanks!
![image](https://user-images.githubusercontent.com/45757016/201662168-850dfab9-913f-4ee2-a314-70205bd0f05e.png)
