### ISSUE TITLE
Dropdown: styling issue

### ISSUE THREAD

**Issue by pbal** [infor-design/enterprise#6677]
**Describe the bug**
Styling issue when dropdown is opened.

**To Reproduce**
Visit below link and click on dropdown
https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/example-index?theme=new&mode=light&colors=0066D4

Notice the options popup does not line up with dropdown base outline.
![image](https://user-images.githubusercontent.com/1594975/180209679-208788e0-9531-4411-ad90-3f7209151e16.png)

**Comment by tmcconechy** [comment]
It looks pretty good one my end (chrome latest / mac)

![Screen Shot 2022-07-21 at 9 15 17 AM](https://user-images.githubusercontent.com/814283/180222589-9b98f0f7-80b4-4d85-b10a-40d984f37c24.png)

Any other details we should know?

**Comment by pbal** [comment]
110% zoom on chrome and edge show this behaviour.
