### ISSUE TITLE
Datagrid: Incorrect background color of trigger icon when hovering

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#6679]
**Describe the bug**

The background color of the trigger icon is incorrect when you hover the Datagrid row.

**To Reproduce**

1. Go to http://localhost:4000/components/datagrid/test-landmark
2. Click any cell in `Manufacturer (Ed, Ell)` column to toggle the editing mode
3. Then hover to the next cell column
4. Seach icon background color is incorrect

**Expected behavior**
Background color of the trigger icon should be the same as the row when hovered

**Version**

- ids-enterprise: v4.62.0

**Comment by tmcconechy** [comment]
once done we will patch this in 4.65

**Comment by jbrcna** [comment]
QA Passed
v4.66.0-dev
Datagrid: Incorrect background color of trigger icon when hovering 
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/56722184/181185584-c0b542a5-1784-4405-bf8f-13fc93f27c88.png">
