### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'tooltipOptions')

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#6684]
**Describe the bug**
Remove rows to fast in a Data Grid throw tooltip is undefined error

**To Reproduce**

1. Go to https://stackblitz.com/edit/ids-quick-start-1411-ivewxa?file=src/app/app.component.ts
2. Open browser developer tools
3. Delete rows rapidly

**Expected behavior**
No errors should throw

**Version**

- enterprise-ng: 14.1.1

**Comment by yohannahbautista** [comment]
@guoliang @tmcconechy @ericangeles 
Hello, I checked the code in IDS and there looks to be a fix already there for the undefined exception: https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.js#L12881
If I inspect the stackblitz, the check is missing
<img width="461" alt="image" src="https://user-images.githubusercontent.com/85279127/195519651-647151a2-4e43-4a53-9475-097a991ddb2d.png">

I've been trying several cases to reproduce the error and it doesn't work in my end, so I think updating to the latest IDS version will fix the issue

**Comment by tmcconechy** [comment]
@yohannahbautista sounds like the answer to me.

**Comment by ericangeles** [comment]
Closing now this issue.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
