### ISSUE TITLE
Rich Text Editor - Font background color control doesn't work properly

### ISSUE THREAD

**Issue by mlick27** [infor-design/enterprise#6685]
In the Editor component example with a title of "Example with backcolor", if I try to highlight text and then change the backcolor, the color is not saved correctly in the HTML.  I always end up with white:  <font style="background-color: rgb(255, 255, 255);">.  Seems like this is a problem with the control rather than the example.

/latest/demo/components/editor/example-with-backcolor?theme=uplift&variant=light

**Comment by tmcconechy** [comment]
- Go to https://main-enterprise.demo.design.infor.com/components/editor/example-with-backcolor.html
- select some text and hit backcolor and pick a color
- deselect text and notice its not set (its setting it to rgb(256, 256, 256))

**Comment by tmcconechy** [comment]
Lets also test this in the Web Component Versions

**Comment by glenlieorillo** [comment]
QA tested and passed.

**_Before fix:_**
https://4550-enterprise.demo.design.infor.com/components/editor/example-with-backcolor.html

https://user-images.githubusercontent.com/102151352/187915694-678bdc05-aa5f-4980-8aae-84be0511b67d.mov

**_After fix:_**
https://main-enterprise.demo.design.infor.com/components/editor/example-with-backcolor.html

https://user-images.githubusercontent.com/102151352/187915717-8f2c41d4-8656-43d1-aed0-75bd593a5886.mov
