### ISSUE TITLE
Tabs Module: Searchfield visual issues

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6686]
**Describe the bug**
1. When the searchfield isn't focused, the height of the searchfield is smaller than the categories and go buttons.
2. When the window is resized smaller and then expanded, the Go button is cut off

**To Reproduce**
1. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
3. Click on the searchfield to focus it
4. Click anywhere else on the page
5. Notice that the searchfield height is now smaller than the categories and go buttons
6. Resize the window small enough where the searchfield collapses
7. Expand the window with the maximize button
8. Notice that the Go button is cut off

**Expected behavior**
It is expected that the searchfield height remains the same height regardless of its focus, and the Go button should be fully visible when resizing the window.

**Version**
- ids-enterprise: v4.66.0-dev

**Screenshots**
![searchfield visual issues](https://user-images.githubusercontent.com/76002134/180518174-5bff4884-f1d5-459e-b4a6-4a7fadd8820b.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 103.0.5060.134 (Official Build) (64-bit)

**Comment by glenlieorillo** [comment]
QA tested and the bug still exists. 
Validated in: http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html

1. _When the searchfield isn't focused, the height of the searchfield is smaller than the categories
and go buttons._  **FAILED**

3. _When the window is resized smaller and then expanded, the Go button is cut off._  **PASSED**

https://user-images.githubusercontent.com/102151352/193711669-758bd383-fac1-4ac3-a803-9a4249850238.mov

**Comment by ericangeles** [comment]
@yohannahbautista can you take a look again?

**Comment by yohannahbautista** [comment]
> @yohannahbautista can you take a look again?
Hello, it's working for me in local, not sure what to do with main-enterprise
<img width="1012" alt="Screen Shot 2022-10-04 at 10 42 12 AM" src="https://user-images.githubusercontent.com/85279127/193723140-5f324ec9-5f1d-41bd-994f-ce8c582ea2a2.png">

**Comment by glenlieorillo** [comment]
Thanks, @yohannahbautista 😊

It's working now in local.
http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html

https://user-images.githubusercontent.com/102151352/193725448-d8076207-7ed4-4a1a-b834-c05cf03f000f.mov

**Comment by ericangeles** [comment]
@glenlieorillo can you test it again on main-enterprise?

**Comment by glenlieorillo** [comment]
Working as expected in main-enterprise.


https://user-images.githubusercontent.com/102151352/194809907-b04a2ac9-ef06-438c-a85e-d5361e847f0a.mov

**Comment by glenlieorillo** [comment]
This is working now as expected in main-enterprise. Thanks! 😊


https://user-images.githubusercontent.com/102151352/194814685-fa1d3c37-8c2d-4672-a521-d35269c6f221.mov

**Comment by s-werking** [comment]
Hi, we have encountered an issue related to this ticket after implementing this fix. This is only an issue with classic theming.

Steps to reproduce:
1. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html?theme=classic&mode=light&colors=2578a9
2. Note that the searchfield height doesn't quite match the categories button height

Screenshot for reference:
![image](https://user-images.githubusercontent.com/76002134/196763471-fa11ef9f-cfd4-46c6-9817-c9803da329d6.png)

**Comment by ericangeles** [comment]
@yohannahbautista can you take a look at this

**Comment by glenlieorillo** [comment]
It is now working as expected.

Windows 11 - Chrome (BrowserStack)

https://user-images.githubusercontent.com/102151352/198158186-a28d2eeb-382e-43c3-a051-3b7c00df5cdd.mov

Mac Chrome

https://user-images.githubusercontent.com/102151352/198158196-1b63a755-2070-477a-99fc-e7a32c612f2a.mov

https://user-images.githubusercontent.com/102151352/198158273-62b4f55f-7531-451a-b4c9-e7b471084856.mov
