### ISSUE TITLE
Toolbar: responsive and overlapping issue

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6689]
**Describe the bug**
Toolbar: responsive and overlapping issue

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar/example-non-collapsible-searchfield.html
2. Minimize the screen to responsive view and Mobile

**Expected behavior**
Fields should not overlap other field/text. 

**Version**
4.66-ids-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/180786414-6d5bee21-5d79-4005-b453-0e401217d78a.png)

**Platform**
All major OS, Browsers and devices. 

**Additional context**
N/A

**Comment by ericangeles** [comment]
For the dev who will fix this, use the new design of searchfield. https://main-enterprise.demo.design.infor.com/components/searchfield/example-index. If you have any questions, ping me.
