### ISSUE TITLE
Editor: flex-toolbar unable to insert image

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6693]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/editor/example-flex-toolbar.html
2. Insert Image
3. See error

**Expected behavior**
should be able to insert an image
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/56722184/180963876-0d6ade90-924f-490e-bbd5-09c6f6315ac3.png">
**Version**

- ids-enterprise: v4.66.0-dev

**Screenshots**
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56722184/180964239-b3585087-ca47-42a5-8199-5f3211c4729d.png">

**Platform**
All

**Additional context**
affected links
https://main-enterprise.demo.design.infor.com/components/editor/example-short.html

**Comment by ericangeles** [comment]
Looks like it has something to do with this fix https://github.com/infor-design/enterprise/pull/5968

**Comment by jbrcna** [comment]
this is now working as expected. 
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/56722184/232012684-a75fdaa6-92b9-474e-9950-d47397c452a9.png">
