### ISSUE TITLE
Searchfield: 'Go' button height issue

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6695]
**Describe the bug**
The 'Go' button height does not match the height of the search textbox in the Classic Version.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/searchfield/example-go-button.html?theme=classic&mode=light&colors=2578a9 and https://main-enterprise.demo.design.infor.com/components/searchfield/example-categories-and-go-button.html?theme=classic&mode=light&colors=2578a9
2. See error

**Expected behavior**
'Go' button height should match the height of the search textbox.

**Version**

- ids-enterprise: 4.66.0-dev

**Screenshots**
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/102151352/181234934-d40d51b5-6dbd-43fb-a13c-8a7842afb5ac.png">

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/102151352/181235001-26ecd86f-b23c-49fd-b616-ebeeb0b3d446.png">

**Platform**
 - All major browsers

**Comment by jbrcna** [comment]
this now working in local but not in main
`main`
<img width="430" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/23526e6f-5e67-4512-81fd-4cca37b6ecb4">
`local`
<img width="463" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/cb6f8132-7ecb-4d8c-bf66-d0d24ad0dd51">
