### ISSUE TITLE
Trackdirty: Element removed from dom will cause error

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#6696]
**Describe the bug**
In the situation where an element is removed from the dom before the event listener functions can finish will throw an error. In combination with angular 13, this is causing pages to get reloaded.

**Expected behavior**
It would be nice if there could be a safety check at https://github.com/infor-design/enterprise/blob/main/src/components/trackdirty/trackdirty.js#L209 to make sure that el[0] exists.

**Version**

- ids-enterprise: 4.64.3

**Platform**
 - Infor Application/Team Name: Infor Landmark, all devices and browers

**Comment by ericangeles** [comment]
@Sovia, can you provide an example of this issue?

**Comment by Sovia** [comment]
It's an error that is occurring deep in the bowels of lmclient code, and I can't easily recreate it in ids code. Since it's a safety check, do you need an example?

**Comment by tmcconechy** [comment]
Maybe this change would just solve it `if (!d.icon.is('.icon-dirty')) {` -> `if (!d?.icon?.is('.icon-dirty')) {` @ericangeles ?

**Comment by glenlieorillo** [comment]
QA validated and passed.

![image](https://user-images.githubusercontent.com/102151352/189636007-c6b68e57-63ec-4bba-b7c2-b30dc9be05a7.png)

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/102151352/189636377-4c89cdcc-d991-488c-a633-47c18b69360e.png">
