### ISSUE TITLE
Datagrid: Render issue with frozenColumns and a column with textOverflow of 'ellipsis' in height of 'extra-small' 

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#6697]
**Describe the bug**
A render issue when using frozenColumns and a column has a property of textOverlow: 'ellipsis' when using a row height of 'extra-small'.

**To Reproduce**
1. Using the attached 'example-frozen-columns.html'
2. Notice that the height of the header is incorrect for the columns that are scrollable

**Expected behavior**
Expect the grid header has a consistent height.

**Version**
- ids-enterprise: v4.64.4

**Screenshots**
![image](https://user-images.githubusercontent.com/39804038/181339934-1c0f881f-b00f-4d22-afe4-22f32166bb45.png)

**Additional context**
Have a Landmark regression ticket attached to this issue.  Problem started in v4.64.x.

**Comment by claudenbach** [comment]
[Git-6697.zip](https://github.com/infor-design/enterprise/files/9202423/Git-6697.zip)

**Comment by vonnyw** [comment]
@tmcconechy @EdwardCoyle this is a regression in IDS 4.64 and we would like to request a patch for the fix when that is available, thanks

**Comment by yohannahbautista** [comment]
@claudenbach @tmcconechy @ericangeles 
Hello, I'm not seeing it in extra-small but I am seeing it in medium, so will start on that. Is the bug using the example file showing in extra-small if it's using the latest version?

On extra-small
<img width="930" alt="Screen Shot 2022-08-11 at 11 28 55 AM" src="https://user-images.githubusercontent.com/85279127/184061485-efda3836-0fb7-4257-b062-9213911c0aa0.png">

On medium
<img width="917" alt="image" src="https://user-images.githubusercontent.com/85279127/184061525-7a765fed-5119-497c-9dce-46aa93bb836c.png">

**Comment by tmcconechy** [comment]
@claudenbach i discovered you can only see this in 4.65 or 4.64 not 4.66 or main. So we will need more than one fix unless 4.66 works....

**Comment by claudenbach** [comment]
Agree.  I've pulled the latest on main and now can no longer see it on main.  Thanks.

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-frozen-columns-text-overflow.html?
![image](https://user-images.githubusercontent.com/45757016/184833395-9f680b95-bd11-4115-96f8-dd6f6bf1c69d.png)
