### ISSUE TITLE
Searchfield icon has overflow underneath when collapsed.

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#6705]
**Describe the bug**
Toolbar searchfield icon has scrollbar underneath the icon when toolbar is sized down to a smaller resolution.

**To Reproduce**
1. Checkout 4.64.x
2. Navigate to http://localhost:4000/components/toolbar-flex/test-gauntlet.html
3. Resize browser to smaller resolution.
4. Notice scrollbar underneath the search icon

**Expected behavior**
There should be no scrollbar on search icon

**Version**
4.64.3

**Screenshots**
<img width="539" alt="search-overflowed" src="https://user-images.githubusercontent.com/1056684/182462753-6aaf2262-8f32-4576-97e3-be89f6ec0128.png">

**Platform**
- Chrome
- Windows 11

**Additional context**
This has been fixed in 4.65.x. Using this ticket to track a patch for this in 4.64.4

**Comment by GlenlieMaye** [comment]
QA tested and passed.

https://main-enterprise.demo.design.infor.com/components/toolbar-flex/test-gauntlet.html
<img width="483" alt="image" src="https://user-images.githubusercontent.com/102151352/183555033-0d3d6d9b-0494-4daf-baaf-d5bc5558fc1d.png">

https://4640-enterprise.demo.design.infor.com/components/toolbar-flex/test-gauntlet.html
<img width="483" alt="image" src="https://user-images.githubusercontent.com/102151352/183555270-2022ee80-84ff-43d1-b550-4369496ab067.png">
