### ISSUE TITLE
Sink page: about incorrect version

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6710]
**Describe the bug**

**To Reproduce**

1. Go to https://4660-beta0-enterprise.demo.design.infor.com/
2. scroll down to about component
3. click to open modal

**Expected behavior**
should be IDS Version: 4.66.0-beta.0

**Version**

- ids-enterprise: v4.66.0-beta0

**Screenshots**
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/56722184/182841244-73116908-2637-4690-8a4c-ab47e22d101c.png">

**Platform**
all

**Additional context**

**Comment by tmcconechy** [comment]
Had a slight issue in the deploy but its just cosmetic with the number. Rest is ok https://github.com/infor-design/enterprise/compare/4.66.0-beta.0...4.66.x so nothing we can fix/change
