### ISSUE TITLE
Datagrid: in-range filter input issue

### ISSUE THREAD

**Issue by nickanello** [infor-design/enterprise#6719]
**Describe the bug**
After doing an in-range date filter on a column, changing the filter condition, and then changing back to in-range, the in-range filter input becomes unchangeable.

**To Reproduce**
1. Use this zipped html file: 
[test-filter-in-range-input.zip](https://github.com/infor-design/enterprise/files/9293933/test-filter-in-range-input.zip)
2. On the "Date" column, change the filter condition to "In Range"
3. Type or use the date picker to input two dates
4. Change the filter condition to "Equals" (or any condition that requires one date as input)
5. Change the filter condition back to "In Range"
6. Edit the second date of the in-range filter input (do not use the date picker)
7. Blur the filter input field by clicking elsewhere
8. Notice that the edit made in step 6 was reverted.

**Expected behavior**
The edit made to the filter input field in step 6 was applied.

**Version**
ids-enterprise: v4.67.0-dev

**Screenshots**
Showing the steps to reproduce.
![Presentation1](https://user-images.githubusercontent.com/71667221/183741002-f7325eed-7c87-4b94-a7a1-aeb54302c33a.gif)
**Platform**
- Infor Application/Team Name: lawson
- OS Version: Windows 11
- Browser Name: Chrome
- Browser Version: 104.0.5112.81 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Closing out older issues
