### ISSUE TITLE
About: The information of 'Platform' in About component is not right

### ISSUE THREAD

**Issue by SunnyIris** [infor-design/enterprise#6727]
**Describe the bug**
The information of 'Platform' in About component is not right.

**To Reproduce**

1. Go to 'https://design.infor.com/code/ids-enterprise/latest/about'
2. Click on 'Show About Screen' button on the left side page
3. Scroll down the opened dialog to 'Platform: Win32'
4. See the value for Platform is match the real one which should be Win11

**Expected behavior**
Remove the unmatched platform information, can only show "Windows" for Operating System or Platform.

**Version**

- ids-enterprise: v4.67.0 dev

**Screenshots**

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/111033862/184061562-9cccdc30-c9b4-4089-8e96-b9c00c2303a0.png)

**Platform**
 - Infor Application/Team Name: Infor IDS Enterprise
 - Device: 
 - OS Version: Windows 11
 - Browser Name: Edge
 - Browser Version: 103.0.1264.77

**Additional context**

**Comment by tmcconechy** [comment]
Lets remove this field from 4.x and WC

**Comment by SunnyIris** [comment]
> Lets remove this field from 4.x and WC

Sounds great
