### ISSUE TITLE
Validation Component: Selected item from dropdown list box not appearing when the list box is closed

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#673]
**Describe the bug**
Selected item from dropdown list box not appearing when the list box is closed

**To Reproduce**
1. http://4100-beta0-enterprise.demo.design.infor.com/components/validation/example-short-fields.html
2. Scroll down to "Dropdown" and Select "W" from the "Custom" dropdown list
3. The value is not appearing. The letter "W" should appear when the dropdown lit box is closed. 
4. Please see screen shot attached. 

**Expected behavior**
 The letter "W" should appear when the dropdown lit box is closed. 

**Screenshots**
![bs_win10_ie_11 0 3](https://user-images.githubusercontent.com/39101346/44676377-10e60780-aa01-11e8-903b-d81bf87228c2.jpg)

**Platform**
  - All Browsers

**Additional context**
None

**Comment by tmcconechy** [comment]
To whoever picks this up. We can just change the css on the dropdown so that the width is enough to show one character of data. Isolate the fix to just the short height and narrow version of the dropdown (ie. try not to effect all dropdowns)

**Comment by davidcarlsonberg** [comment]
Assigned to self and will move to Ready for QA upon completion.
