### ISSUE TITLE
Datagrid: New row added to the top in data grid cannot be selected

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#6730]
**Describe the bug**
New row added to the top isn't located at top.

**To Reproduce**
Go to this stackblitz
https://stackblitz.com/edit/ids-quick-start-1421-m8kuzg?file=src/app/odd-data-grid/odd-data-grid.component.ts

1. Add few rows
3. Look in console

**Expected behavior**
New row added to the top should be correct selected

**Version**
- ids-enterprise-ng: 14.2.1

**Screenshots**
![image](https://user-images.githubusercontent.com/542598/184116183-668096d9-025b-4e69-b784-920ec18f36d5.png)

**Comment by tmcconechy** [comment]
I see the problem but i dont get how the item.id in this line has any connection to the datagrid.

```
<a soho-popupmenu-label (click)="onMenuItemSelected(item.id)">
```

Maybe you can do something like:

```
  onMenuItemSelected(action: any): void {
    switch (action) {
      case 'delete':
        console.info(grid.dataset[grid.activeCell.row].id);
        break;
    }
  }
```

**Comment by tmcconechy** [comment]
What do you think about this one @ericangeles am i off base?

**Comment by guoliang** [comment]
I have another stackblitz where I have removed the popupmenu.
https://stackblitz.com/edit/ids-quick-start-1421-hqbupu?file=src/app/app.component.ts

And the issue is present there as well.

**Comment by tmcconechy** [comment]
Yeah that lasts case is showing an issue... That we should fix

**Comment by guoliang** [comment]
btw, I found a similar issue. might be related to same part of code. If I add toolbar with search filter, and then search on some item on the row, and select the item in it. the selected item is not the actual item which got selected.

I can create another stackblitz for it to re-produce the error if needed.

**Comment by tjamesallen15** [comment]
Hello @tmcconechy and @guoliang ,

I cannot reproduce this issue anymore in both EP and NG. I made an example page directly with the project. I used your data and structure in the example page. Please see it in the Pull Request.

**Comment by ericangeles** [comment]
@tjamesallen15 can you reference that PR in here?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 can you reference that PR in here?

https://github.com/infor-design/enterprise-ng/pull/1393

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
