### ISSUE TITLE
Datagrid: Layout issue with frozen columns after updating the datagrid

### ISSUE THREAD

**Issue by ablomq** [infor-design/enterprise#6739]
**Describe the bug**
If the datagrid has frozen columns they are misaligned after updating the datagrid. The header above the frozen columns disappear etc. This was not an issue in version 4.64.2. Think it was introduced from version 4.65.1 or possibly version 4.65.3. Maybe the issue is caused by this fix: [6290 - datagrid toolbar visible after fixing error/validation](https://github.com/infor-design/enterprise/tree/6290-datagrid-toolbar-visible-after-no-error)

**Expected behavior**
The frozen columns should not be misaligned after updating the datagrid.

**Version**
4.66.0

**Screenshots**
The two columns to the left are frozen columns:

![image](https://user-images.githubusercontent.com/42343009/184848784-0bcee286-0a83-4004-a1b7-509da72dac2c.png)

After update of the datagrid:
![image](https://user-images.githubusercontent.com/42343009/184849059-aab36d50-3439-4057-8489-3dd81b44fa49.png)

**Comment by tmcconechy** [comment]
@ablomq i think this is the same issue as https://github.com/infor-design/enterprise/issues/6697
And its been patched if you want to try:

[4.64.5](https://www.npmjs.com/package/ids-enterprise/v/4.64.5) 

Also in
[4.65.4](https://www.npmjs.com/package/ids-enterprise/v/4.65.4) or 4.66 (latest)

**Comment by ablomq** [comment]
@tmcconechy Dont think it's the same issue. We are running the latest release, version 4.66.0 and the issue remains. It happens when some data used by the grid is changed.

**Comment by tmcconechy** [comment]
ok @ablomq it seemed related. how can this be reproduced in the examples exactly?

**Comment by ablomq** [comment]
Is there an example available with frozen columns and a refresh button which reload the data? Something similar to this:

![image](https://user-images.githubusercontent.com/42343009/184924452-e5af6c5c-8eba-44af-8736-a1c27a514e63.png)

**Comment by tmcconechy** [comment]
I made a similar example https://github.com/infor-design/enterprise/commit/6187a58301f8b2ddb659d28ccbb60471da0196f8 but i could not see the issue 

Url is http://localhost:4000/components/datagrid/test-list-update.html if local

**Comment by ablomq** [comment]
Maybe this is an angular issue? I'll try to setup an example in Stackblitz.

**Comment by tmcconechy** [comment]
Sure, https://github.com/infor-design/enterprise/issues/6697 does seem a little like it, so just in case i just updated main so you can try against main branch..

Or latest stack blitz is https://stackblitz.com/edit/ids-quick-start-1411

Another idea is could it be if the names of the frozen columns or missing or anything wierd like that?
