### ISSUE TITLE
[Win 10 IE 11] Validation Component: Error validation not appearing when fields are left empty

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#674]
**Describe the bug**
[Win 10 IE 11] Validation Component: Error validation not appearing when fields are left empty

**To Reproduce**
1. Go to http://4100-beta0-enterprise.demo.design.infor.com/components/validation/example-short-fields.html
2.  Scroll to "Normal Input Fields" and click inside of "Custom" 
3. Tab into the "input-xs" and tab out of the field box again
4. The error validation is not appearing once you tab out of each

**Expected behavior**
The error validation should appear once you leave a field box empty and tab into the next field box. 

**Screenshots**
None

**Platform**
 - Browser Name [Win 10 IE11]

**Additional context**
None

**Comment by tjamesallen15** [comment]
Hi Team,

I tried doing initial testing and it seems working fine.

Thanks.

**Comment by tmcconechy** [comment]
Ok, lets just put this to retest then. I think that it might have been when we had a general IE problem on all pages.

**Comment by tmcconechy** [comment]
@CindyMercadoReyes can you retsted this when you have a chance.
