### ISSUE TITLE
Modal: readonly field should not be focused.

### ISSUE THREAD

**Issue by sjasaniel** [infor-design/enterprise#6740]
**Describe the bug**
Readonly field in a modal should not be focused.

**To Reproduce**

Using example from https://github.com/infor-design/enterprise/issues/5400..
Please update https://main-enterprise.demo.design.infor.com/components/modal/test-focusable-elements.html and add this field on top of an editable field
`	<div class="field">
              <label for="test-lookup-readonly" class="label is-readonly">Test Lookup Readonly</label>
              <input id="test-lookup-readonly" class="lookup" readonly
			  name="test-lookup-readonly" type="text"/>
       </div>`

**Expected behavior**
Readonly field should not be focused.

**Version**

- enterprise: v4.64.3

**Screenshots**
<img width="310" alt="image" src="https://user-images.githubusercontent.com/9715303/184859407-0cf6c264-4dcb-4a02-96fe-0203e454d390.png">

**Platform**
 - Infor Application/Team Name: Landmark
 - Device: (if applicable) Desktop
 - OS Version: Windows 10
 - Browser Name: Microsoft Edge
 - Browser Version: Version 104.0.1293.54 (Official build) (64-bit)

**Additional context**

**Comment by sjasaniel** [comment]
Hi @tmcconechy , kindly disregard this issue for now. Currently, I'm clarifying some rules for accessibility. Thank you!

**Comment by tmcconechy** [comment]
ok, feel free to reopen... Thanks!
