### ISSUE TITLE
Circle Pager: Text labels are overlapping on the border

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6741]
**Describe the bug**
Text labels are overlapping on the border.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/circlepager/example-tabs.html
2. See error

**Expected behavior**
Text labels should not be overlapping on the border.

**Version**

- ids-enterprise: 4.67.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/102151352/184866791-d2c4082f-923a-4130-9ead-fcd4adb804d5.png)

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
Descoping this issue for now
