### ISSUE TITLE
Process indicator last separator shouldn't be visible.

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#6744]
**Describe the bug**
There is a line extending beyond the last step in some use cases. This should be hidden.

**To Reproduce**

1. Checkout main branch (4.66.0-dev)
2. Go to http://localhost:4000/components/processindicator/example-index.html
3. See last indicator chart on page. Notice separator extending beyond step.

**Expected behavior**
Line should be hidden.

**Version**
4.66.0-dev

**Screenshots**

This appears to be caused by https://github.com/infor-design/enterprise/pull/6133

**Issue:**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1056684/184942835-6cd198b8-6571-4568-a21c-09458fd92dbd.png)

**How it looks if I revert change from:** 6133
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/1056684/184942251-0522a406-ea36-4360-bfee-4e06f9c46b28.png">

**Platform**
- Chrome
- Windows 11

**Additional context**

**Comment by glenlieorillo** [comment]
QA Failed. The bug still exists.

Windows 11 Chrome (BrowserStack)

![image](https://user-images.githubusercontent.com/102151352/201098116-ace5fd48-b31f-41eb-8420-02c2f865d7ca.png)


Mac Chrome - main-enterprise
![image](https://user-images.githubusercontent.com/102151352/201098489-479cd8f9-bfda-43e1-bb80-e54c62d77dd0.png)

Mac Chrome - localhost
![image](https://user-images.githubusercontent.com/102151352/201098824-cbd26d4d-974b-4778-bc3a-118fe442a1f4.png)

**Comment by tmcconechy** [comment]
@corpulent can you see why main isnt deploying this bug also failed.

**Comment by tmcconechy** [comment]
It's updated on main now. We are having issues deploying. I think in general if you dont see it on main and try running local  and if it works you can trust it works.

**Comment by glenlieorillo** [comment]
QA tested and passed.

Mac Chrome
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/201590425-44de3102-f180-48fb-9e7e-0e9f94dc6ecb.png">


Windows 11 - Chrome (BrowserStack)
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/201590206-22a85189-e2da-4375-bb42-9e38cc9c845e.png">
