### ISSUE TITLE
Datagrid: isEditable is passed incorrect argument values when an addRow has been performed

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#6746]
**Describe the bug**
The arguments being passed to the function isEditable are incorrect when a row has been added to the top of the datagrid.

**To Reproduce**
1. Using the attached 'test-addrow-with-is-editable.html'
2. Click on 'Add Row'
3. Open the browser's debugger console
4. Click on Product Id cell for the newly added row
5. Notice that the arguments passed to the the function customIsEditable are incorrect
6. Click on Product Id cell for the row with Portable Compressor
7. Look in the console, notice that the arguments passed to customIsEditable are incorrect

**Expected behavior**
Correct arguments are passed to the isEditable function.

**Version**
- ids-enterprise: v4.67.0-dev

**Additional context**
Have a Landmark regression ticket attached to this issue.  Need to confirm when this started, but seeing it in v4.65.2.

**Comment by claudenbach** [comment]
[Git-6746.zip](https://github.com/infor-design/enterprise/files/9354225/Git-6746.zip)

**Comment by tmcconechy** [comment]
Something similar was reported here https://github.com/infor-design/enterprise/issues/6730 but on an older version

**Comment by tmcconechy** [comment]
Most likely related to this changes:

https://github.com/infor-design/enterprise/issues/6491
https://github.com/infor-design/enterprise/issues/6491

**Comment by jbrcna** [comment]
QA Passed
https://main-enterprise.demo.design.infor.com/components/datagrid/test-addrow-with-is-editable.html
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/56722184/187825068-b1e7b946-260c-4e64-a25a-8a1b3c584162.png">
