### ISSUE TITLE
Bar Charts Grouped: Identical aria labels for bar chart

### ISSUE THREAD

**Issue by JBismonte** [infor-design/enterprise#6748]
**Describe the bug**
the aria labels for bar chart grouped is the same, the label for the first bar is the same for all bars.

**To Reproduce**

1. Go to http://localhost:4000/components/bar-grouped/example-formatter.html
2. Inspect element for each of the bars.
3. See that they have identical aria labels.

**Expected behavior**
aria label should be different for each bar.

**Version**

- ids-enterprise: 4.67

**Screenshots**
See screen recording 

https://user-images.githubusercontent.com/29673378/185085568-0a7dee15-d64d-48e1-bc6e-69b1ca39f507.mp4

**Platform**
 - Infor Application/Team Name: Landmark UI
 - Device: (if applicable: NA
 - OS Version: Windows 11
 - Browser Name: Firefox
 - Browser Version: 103.0.2 (64-bit)

**Additional context**
Infor Jira Link
https://jira.infor.com/browse/LMWEB-1972

**Comment by glenlieorillo** [comment]
QA tested and passed.
http://localhost:4000/components/bar-grouped/example-formatter.html

https://user-images.githubusercontent.com/102151352/193491666-869c4146-c483-4813-94ae-a5200219b69a.mov
