### ISSUE TITLE
Chore: Build/Dev Pipeline Improvements

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6749]
**Describe the bug**
Did a bit of a div and made a list of some project changes we should make. These can be broken into smaller issues if needed. Treat this like an Epic.

Ranked in priority:

- [x] #6750
- [x] Get rid of grunt dependency
- [ ] Package up the server.js in webpack deploy
- [x] Remove Chalk.js dependency
- [ ] use sass https://github.com/infor-design/enterprise-wc/blob/main/package.json#L87 not node-sass dependency
- [x] Get rid of moment.js
- [ ] Change Rollup and convert to Web Pack (using webpack and rollup and grunt and yargs)
- [x] Fully remove protractor (EOL 2023)
- [x] Put package lock back in place
- [x] Replace karma with jest (maybe)
- [ ] Remove fs events hack

**Version**
- ids-enterprise: [e.g. v4.67.0]

**Platform**
 - Node 16

**Additional context**
#6634 is required first

**Comment by danielortiz1982** [comment]
@ericangeles This issue is next on the priority list after your done with #6634

**Comment by tmcconechy** [comment]
Mostly done by 6634 for what we can. There are some things remaining on https://github.com/infor-design/enterprise/issues/7064 that require future collaboration
