### ISSUE TITLE
Remaining Calendar Features (Part One)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#675]
Added more features to calendar for Sept sprint:

- ajax load events for a month
- events for changing months
- tooltip on ellipsis of event name
- status (fx.. pending) on the event
- a notification banner
- allow calendar items to span multiple dates
- selecting events (with an event when selecting a day)
- show readonly events details on a template - when days are clicked

**Comment by tmcconechy** [comment]
Noted to test (as per the PR)


- ajax load events for a month
http://localhost:4000/components/calendar/example-ajax-events.html
After a moment, and after changing each page the events will be loaded on an ajax call

- events for changing months
Covered by unit tests (renderedmonth)

- tooltip on ellipsis of event name
http://localhost:4000/components/calendar/example-index.html
go to oct
resize page so ellipsis is shown on events
hover the events

- status (fx.. pending) on the event
http://localhost:4000/components/calendar/example-index.html
go to oct
resize page so ellipsis is shown on events
hover the event with an icon (note that an icon is shown)
click that day (note that the icon is shown in the day details)

- a notification banner
http://localhost:4000/components/notification/example-index.html
page should render
clicking x will dismiss (this will be used on calendar examples later)

- allow calendar items to span multiple dates
http://localhost:4000/components/calendar/example-index.html
go to oct (or nov)
notice events spanning more than one day

- selecting events (with an event when selecting a day)
http://localhost:4000/components/monthview/example-selectable-days.html
click any day to select
click today to select today again
also covered by unit tests but evident when clicking a day that it shows

- show readonly events details on a template - when days are clicked
http://localhost:4000/components/calendar/example-index.html
any month (aug - nov)
click days with events
events should be shown (multiple in a day not yet supported)

**Comment by brianjuan** [comment]
http://localhost:4000/components/notification/example-index.html
X button is not clickable

**Comment by tmcconechy** [comment]
Some styles where missing on a merge. Fixed this for the second redeploy

**Comment by brianjuan** [comment]
http://localhost:4000/components/notification/example-index.html
http://master-enterprise.demo.design.infor.com/components/notification/example-index.html
Hi tim, X button is still not clickable.

**Comment by tmcconechy** [comment]
Hi @brianjuan 

We pushed this on 4.11.x branch and the fix is not yet merged to master. So you can only see it working on http://4110-beta1-enterprise.demo.design.infor.com/components/notification/example-index.html (or 4.11.x branch if running local)

**Comment by brianjuan** [comment]
http://4110-beta1-enterprise.demo.design.infor.com/components/notification/example-index.html
Thanks @tmcconechy , working as expected on that url. This ticket now passed QA, moving this to Done.
I found one issue (#892) related to this, but I think it should be in a separate ticket.
