### ISSUE TITLE
Locale: Incorrect "Previous" translation in Slovenian

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#6752]
Locale: Incorrect "Previous" translation in Slovenian

![image](https://user-images.githubusercontent.com/66057969/185189780-7197bcac-41f6-441b-a360-653d79bf086b.png)

![image](https://user-images.githubusercontent.com/66057969/185189942-b114195f-fb32-4c6c-8a0e-92d0720cc960.png)

Please assign to [Henry.Wondergem@infor.com](mailto:Henry.Wondergem@infor.com) for review

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
Hi, feedback from the translator: 
"The standard way of translation for “Previous” in these kind of contexts is “Nazaj” (i.e., as it is already). This is both gender and number neutral, since it is often not known what the subject will be (i.e., previous what?). So, unless it is known what the previous thing is and that this particular instance of “previous” will only be used here (where the gender and number is known), then I would suggest the translations remains as it is. Also, the translation of “previous” depends on how “next” is translated in this context, so I would need to know that, before any change can be made."

**Comment by tmcconechy** [comment]
Ok @hwondergem i think for purposed of the component library we should translate this as "Database Records" but not anything specific.

However, for the team in this case (since its on a header and not the datagrid or a list of records) they could request a specific translation for the type of object for the app?

Does the current translation match to something generic like "Database Records"?

**Comment by cpinatel7** [comment]
Additional screenshot - to be reviewed by SL linguist:
![image](https://user-images.githubusercontent.com/66057969/188665411-03e7d948-03bb-48ac-b5c8-13b5da61e889.png)

Are your Previous and Next strings always used in the same context?

**Comment by tmcconechy** [comment]
yeah i guess so they are just previous and next from the context of a generic pager https://main-enterprise.demo.design.infor.com/components/pager/example-datagrid.html where we dont really know what data is in the pager.

These look like your moving through records on on a header but same idea. I guess you could translate it for what your moving through but we would never know so need to keep it generic as it could be any data....

**Comment by cpinatel7** [comment]
I don't speak SL but in this case, translations should be neutral (i.e. not gender specific).
Ideally, Next should be Next Record and Previous should be Previous Record. This will avoid future translation issues.
Thanks

**Comment by tmcconechy** [comment]
Sounds like it is that way from @hwondergem 's comment: 

`This is both gender and number neutral, since it is often not known what the subject will be (i.e., previous what?)`

**Comment by cpinatel7** [comment]
Would it be possible to change the English strings at some point?
i.e.
Next -> Next Record
and
Previous -> Previous Record

**Comment by tmcconechy** [comment]
Yes, @cpinatel7 if you think that makes sense for "any pager next/previous no matter what the data"? I can do that, think here as one example https://main-enterprise.demo.design.infor.com/components/pager/example-datagrid.html but also on that header as that team has done

**Comment by cpinatel7** [comment]
No changes required for:
(context is clear)
![image](https://user-images.githubusercontent.com/66057969/188672507-9277996f-4dab-4c3d-bec0-b4087585960c.png)

I cannot see Previous and Next on https://main-enterprise.demo.design.infor.com/components/pager/example-datagrid.html

I think there are 2 options:
1. Source text changes: Next -> Next Record and Previous -> Previous Record
2. If 1. is too risky, the string comments should indicate that Next and Previous can be used in different contexts

Option 1 is definitely much better.

Thanks

**Comment by cpinatel7** [comment]
Thanks

**Comment by tmcconechy** [comment]
After discussing this we would like to keep this text is shorter. Can just translate it as if it actually said "page" for the gender?

**Comment by cpinatel7** [comment]
Next and Previous are not related to Page. They are related to Record i.e. Next -> Next Record and Previous -> Previous Record. I'm not sure why tooltips have to be short:
![image](https://user-images.githubusercontent.com/66057969/192802019-a7b54060-5cff-4a08-8287-cef39dfeb7ba.png)

**Comment by tmcconechy** [comment]
@cpinatel7 will this work?

- use "next page", "previous page" for the pager (where it already says page)
- make an example with arrows on the header (tooltip custom that says next record/previous record)
- add strings if not there for next / previous record

**Comment by cpinatel7** [comment]
Overall, "Next" and "Previous" should be avoided:
- Page context, "Next Page" and "Previous Page" should be used instead
- Record context, "Next Record" and "Previous Record" should be used instead

If "Next" and "Previous" strings cannot be removed, could you please add comments stating that these strings can be used in DIFFERENT contexts. Next = A navigation control used to go to the next page / record / item, etc. Previous = A navigation control used to go to the previous page / record / item, etc. 

Thanks

**Comment by cpinatel7** [comment]
Thanks

re: Kept next/previous but not sure we will use it for anything going forward

Is it possible to add comments for these strings stating that they are used in DIFFERENT contexts. Next = A navigation control used to go to the next page / record / item, etc. Previous = A navigation control used to go to the previous page / record / item, etc.

**Comment by tmcconechy** [comment]
I did add some comments here https://github.com/infor-design/enterprise-wc/pull/1219/files#diff-4a4e435ae780de2644009d72d9521f252dbd50337dc0102788a7510164f08e1dL347

Maybe you can edit the PR with the comments you want? Click in the gutter on the left and make suggestion?

<img width="910" alt="Screenshot 2023-04-04 at 10 58 48 AM" src="https://user-images.githubusercontent.com/814283/229833857-c62ed964-084e-4789-b9f4-bb137936376c.png">

**Comment by hwondergem** [comment]
Translations updated in 
..cc\ToDev\SohoUX\sl-SI-messages.ts	61,621	07/19/2023 06:46
Like: 
Next: { id: 'Next', value: 'Naslednji', comment: 'Generic Next for a tooltip, see Next Record and Next Page for more specific' },
  NextMonth: { id: 'NextMonth', value: 'Naslednji mesec', comment: 'the label for the button that moves calendar to next/prev' },
  NextPage: { id: 'NextPage', value: 'Naslednja stran', comment: 'Move to next item on Pager component' },
  NextRecord: { id: 'NextRecord', value: 'Naslednji zapis', comment: 'Can be used as a tooltip for arrow navigation on a form moving between records' },
