### ISSUE TITLE
Datagrid - Grouped header with tooltips throws undefined errors

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#6753]
**Describe the bug**
When the datagrid has grouped headers, hovering on a column with tooltip throws columnSettings undefined error.

**To Reproduce**

To reproduce, added tooltip to a column in components/datagrid/test-tree-grouped-headers.html

Hover over a column that has tooltip and check console errors.

**Expected behavior**
Tooltip is displayed.

**Version**

- ids-enterprise: v4.65.2
 
**Additional context**
This issue is caused by https://github.com/infor-design/enterprise/issues/6361

**Comment by aaralikar** [comment]
To test-tree-group-headers.html, I added:

    columns.push({ id: 'taskName', name: 'Task', field: 'taskName', expanded: 'expanded', **tooltip: 'This is a Task',** formatter: Formatters.Tree});

and

      $('#datagrid').datagrid({
        columns: columns,
        dataset: data,
        treeGrid: true,
        toolbar: {title: 'Tasks (Hierarchical)', results: true, personalize: true},
        columnGroups: [{colspan: 2, id: 'group1', name: 'Column Group One'}, {colspan: 3, id: 'group2', name: 'Column Group Two'}], //Numeric Column Span Groups
        **enableTooltips: true**
      });

**Comment by tmcconechy** [comment]
Did you try on main to see if it still happens on the latest?

**Comment by aaralikar** [comment]
Yes, Landmark is on ids-enterprise-ng 14.1.6 and can reproduce the issue

**Comment by claudenbach** [comment]
When the column has an editor, this issue prevents the selection of the value when the cell is made editable.

**Comment by janahintal** [comment]
This issue is now resolved. Verified in https://main-enterprise.demo.design.infor.com/components/datagrid/example-tooltips.html?theme=classic&mode=dark&colors=2578a9
![image](https://user-images.githubusercontent.com/45757016/185886551-1c003b1b-5edd-4f67-87f7-ee84f90a08d4.png)
