### ISSUE TITLE
Badge/Tag: The Info Icon Changed Color

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6763]
**Describe the bug**

When using “badge Info”, “tag info” and “icon info” we expect blue color on component and  in previous IDS versions we used to get Blue(Azure) color. But in IDS Version: 4.62.3 these components have gray color.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tag/example-index.html?theme=new&mode=dark&colors=0066D4 or https://main-enterprise.demo.design.infor.com/components/badges/example-index.html?theme=new&mode=dark&colors=0066D4
1. See that the info tag is not azure

**Expected behavior**
Info icon, badge and tag should be azure again.

**Additional context**
Need example for icon...

**Comment by tmcconechy** [comment]
Caused by https://github.com/infor-design/enterprise/issues/6446

**Comment by glenlieorillo** [comment]
QA tested and passed.

https://main-enterprise.demo.design.infor.com/components/tag/example-index.html?theme=new&mode=dark&colors=0066D4
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/102151352/185893105-a6c92c6b-42e0-4762-8511-4b98fe06725d.png">



https://main-enterprise.demo.design.infor.com/components/badges/example-index.html?theme=new&mode=dark&colors=0066D4
<img width="772" alt="image" src="https://user-images.githubusercontent.com/102151352/185892890-60fc0768-91d0-4413-b0bb-bdba0f4cbd05.png">
