### ISSUE TITLE
Validation/Textarea: Validation breaks when disabling and enabling a Textarea

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#6773]
**Describe the bug**
In a textarea, if you trigger a validation error (e.g. by leaving a required field empty) and then disabling and enabling it again, the validation breaks and the error doesn't disappear even when the field is valid.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1411-6q3is3?file=src/app/app.component.html
2. Focus the textarea and then click anywhere outside it to remove the focus. The validation error should now should up.
3. Click the "Toggle" button and confirm the textarea is disabled.
4. Click the "Toggle" button again to enable the textarea.
5. Start typing in the textarea and notice that the validation error doesn't disappear.

**Expected behavior**
The validation error should disappear.

**Version**
- ids-enterprise-ng: 14.1.1
- ids-enterprise: 4.65.1

**Screenshots**
![textarea_validation](https://user-images.githubusercontent.com/63045013/186365212-47e765fd-6537-42fa-a290-1bb67d8b3561.gif)

**Comment by jbrcna** [comment]
QA Passed. v4.68.0-dev
