### ISSUE TITLE
DataGrid expanded row cannot be edited after two editing scenarios on the parent row

### ISSUE THREAD

**Issue by guymid** [infor-design/enterprise#6781]
**Describe the bug**
When the parent row of an expanded row contains editable fields they interfere with the editability of inputs in the expanded row. This is a defect with the state handling where the exit states from fields in the parent row are incorrect. If line 107486 of sohoxi.js is commented out the editability of the input in the expanded row is correct, but the input in the parent row is still in edit mode. The line is in commitCellEdit() and contains this code:

cellNode.removeClass('is-editing is-editing-inline has-singlecolumn'); // Editor.destroy

**To Reproduce**
This Stackblitz shows both scenarios (with steps) where editability is broken by the parent row. https://stackblitz.com/edit/ids-quick-start-1411-6rgabz?file=src/app/app.component.html

**Expected behavior**
Editable fields in the parent row should not break the editability of inputs in the expanded row.

**Version**

v4.59.2

**Platform**
 - Infor Application/Team Name: Orchestrator

**Comment by tmcconechy** [comment]
Nice bug report. I think we can fix this. But there was'nt the general idea that editing would take place in the expandable row.
Might be better to put that editor in a column (not knowing the full use case)

**Comment by guymid** [comment]
In this case the expandable row is for viewing and editing the description of an item. As the description can be quite long it doesn't fit in the main grid.

**Comment by jbrcna** [comment]
QA Passed.v4.70.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/example-expandable-row-editable.html
