### ISSUE TITLE
Restrict accordion default behavior

### ISSUE THREAD

**Issue by AnjaniSravyaInfor** [infor-design/enterprise#6785]
I am using soho-accordion in a sidebar menu and When I am navigating between the panes in soho accordion I need to restrict the accordion to expand because I am using canDeactivate route guard in angular to confirm whether the user wanted to navigate out of the current page or not. I am able to restrict the user navigation with canDeactivate route guard where as unable to restrict the accordion default behavior of expansion / collapse

Is there any way that I can restrict the default behavior of expanding soho-accordion pane until user confirms the modal we are showing using can canDeactivate route guard. 
 
Please find the screenshot attached.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/112463347/187359554-bc2dc53d-1e11-4a21-bdfb-9f4256544a45.png)

**Comment by tmcconechy** [comment]
Can you use the template for the issue https://github.com/infor-design/enterprise/issues/new/choose (filling in the sections as mentioned). You can edit this one and use the same markdown.

Just to clarify what would work here? A callback before the expand and collapse on the accordion that can be vetoed? If you try this event it should work: https://github.com/infor-design/enterprise/blob/main/src/components/accordion/accordion.js#L382

Or maybe we just need an example showing this in angular?
