### ISSUE TITLE
General: IDS throwing error in console

### ISSUE THREAD

**Issue by jayblack-infor** [infor-design/enterprise#6789]
**Describe the bug**
Kind of hard to explain but I’ll give it a try.  We have run into an issue where IDS is throwing an error that only appears in the console.   We open our angular application (it’s in a js file) and close it.    Reopen that application or another of our angular applications and when the user types in a text field an error is thrown.
 
The application where the occurs occurs (the one that was closed) has an accordion pane and there seems to be an event that is listening for a keydown event and because the js file is still in the browser memory a function gets called and throws an error because the object doesn’t exist.   I was able to add a check to make sure the object exists ( this.headers  in the unfilter function - see code below) and the error went away.    

**To Reproduce**
Will be difficult to reproduce.

**Expected behavior**
Do a safety check to prevent throwing errors when object no longer exists

**Version**
4.56

**Screenshots**
The IDS code is compiled into supportcenter-app.js
![image](https://user-images.githubusercontent.com/45010485/187519969-642d7cd7-3a28-475b-a2e5-ea5a9a6b116e.png)

** Sample code fix **
/**
     * @param {jQuery[]} [headers] element references representing accordion headers.
     *  If provided, will cause only specific items to become unfiltered.  If not
     *  provided, removes all filtering from the accordion.
     * @param {boolean} [isReset] if true, sets a flag to force unfilter the filtered accordions. This will be useful
     * if there are no headers filtered when typing a character that is not available on the accordion list.
     */
    unfilter: function unfilter(headers, isReset) {
      var _this4 = this;
 
      if (!this.currentlyFiltered.length && !isReset) {
       return;
      }
 
      if (!headers || !headers.length) {
        headers = this.currentlyFiltered;
      } // Store a list of all modified parent headers
 
 
      var allParentHeaders = $(); // Reset all the things
 
     **_if (this.headers !== undefined) {_**
      this.headers.removeClass('filtered has-filtered-children hide-focus');
      this.panes.removeClass('all-children-filtered no-transition');
      this.contentAreas.removeClass('filtered');
      headers.each(function (i, header) {
        var parentPanes = $(header).parents('.accordion-pane');
 
        if (parentPanes.length) {
          var parentHeaders = parentPanes.prev('.accordion-header').filter(function (j, item) {
            return allParentHeaders.index(item) === -1;
          });
          allParentHeaders = allParentHeaders.add(parentHeaders);
        }
      });
      allParentHeaders.removeClass('has-filtered-children');
      var collapseDfds = [this.collapse(headers), this.collapse(allParentHeaders)];
      $.when(collapseDfds).done(function () {
        _this4.currentlyFiltered = _this4.currentlyFiltered.not(headers);
      });
     **_}_**
    },

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
