### ISSUE TITLE
Suppress Enter = true do not work  on SohoModal

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise#6793]
**Describe the bug**
Using the suppressEnterKey setting for modal does not work on the succeeding use of enter key for the modal. This happens if you opened and closed another modal with suppressEnterKey=false.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/4.64.0/demo/components/modal/example-index.html.
2. Click on the Show Modal (Suppressed Enter) button to show the modal with suppressEnterKey=true.
3. Press Enter key. The modal will not close as expected.
4. Close the modal by clicking the Cancel button
5. Click on the Show Modal button to show the modal with suppressEnterKey=false.
6. Press Enter key. The modal will close as expected.
7. Click again on the Show Modal (Suppressed Enter) button to show the modal with suppressEnterKey=true.
8. Press Enter key. The modal will close but it should not.

**Expected behavior**
Modal window should not close on press of Enter key if suppressEnterKey=true is set.

**Version**

- ids-enterprise: v4.64.0

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 104.0.5112.82 (Official Build) (64-bit)

**Comment by glenlieorillo** [comment]
QA failed. The bug still exists.
http://localhost:4000/components/modal/example-index.html

https://user-images.githubusercontent.com/102151352/192680361-2c1a7fc5-43e2-432d-b994-78c951c69489.mov

**Comment by tmcconechy** [comment]
@glenlieorillo I tested on https://main-enterprise.demo.design.infor.com//components/modal/example-index.html and it seems ok for me.. Can you test there?

**Comment by glenlieorillo** [comment]
Retested and passed. Moving this ticket to Done.
https://main-enterprise.demo.design.infor.com//components/modal/example-index.html

https://user-images.githubusercontent.com/102151352/193015766-5a4e5f32-227f-497a-a196-8944085b93dc.mov

Thanks, @tmcconechy 😊
