### ISSUE TITLE
Editor: Block quote format not entered in the next line after pressing <Enter>

### ISSUE THREAD

**Issue by NicholTamayo** [infor-design/enterprise#6794]
**Describe the bug**
Observed that the block quote format is not displayed in the next after pressing <Enter>. 
Not encountered in Homepages version 2022.04.00 with IDS version 4.59.4.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/editor/example-index?theme=uplift&variant=light.
2. Enter text.
3. Select the text.
4. Click "Block quote" format.
5. Unselect the text.
6. Press <Enter>.

**Expected behavior**
The block quote format is entered in the next line.

**Version**
- ids-enterprise: 4.66.0

**Screenshots**
![block quote observation](https://user-images.githubusercontent.com/79066908/187857784-0de22453-5bd9-480a-9cd6-5cc23750d949.gif)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Window 11
 - Browser Name: Chrome
 - Browser Version: Chrome/Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by jbrcna** [comment]
QA Passed. v4.68.0-dev
<img width="570" alt="image" src="https://user-images.githubusercontent.com/56722184/191637055-ea16e44f-5ef7-4861-bcae-fb45e2942187.png">
