### ISSUE TITLE
Datagrid: Colorpicker parts are misaligned

### ISSUE THREAD

**Issue by jvang01** [infor-design/enterprise#6799]
**Describe the bug**
Colorpicker parts are not properly aligned for datagrids with default sized rows and datagrids with class 'small-rowheight'.
1.  the dropdown icon overlaps with the color swatch (screenshots 1 & 2)
2.  for standard sized rows, clicking on the colorpicker causes the swatch, value and dropdown icon to all move down and to the right For small-height rows, colorpicker parts move up and to the right (screenshots 3 & 4)
3.  for colopickers in datagrids with class 'small-rowheight', the value is not aligned with the color swatch (screenshot 5)

**To Reproduce**

See example: http://localhost:4000/components/datagrid/test-editable-colorpicker.html
or open attached .zip for html file. 
Add class='small-rowheight' to the datagrid (<table class="datagrid small-rowheight" role="grid">) to test for small height rows.

**Expected behavior**
the dropdown icon should not overlap the color swatch
the colorpicker should not move when the colorpicker is opened
for datagrids with class 'small-rowheight' the colorpicker swatch and text should be aligned

**Version**

- ids-enterprise: v.4.61.x

**Screenshots**
1.
![image](https://user-images.githubusercontent.com/64548726/188727059-5dd6bf49-ff68-4054-ab4e-8d9bcafae103.png)
2.
![image](https://user-images.githubusercontent.com/64548726/188727294-52abb11c-5665-4932-a8ef-7fb4bc3a13a4.png)
3.
![image](https://user-images.githubusercontent.com/64548726/188727426-831abade-3602-4e86-9569-8099c5dcd7b3.png)
4.
![image](https://user-images.githubusercontent.com/64548726/188727505-a71d90bf-a89c-4508-991e-20a4942a2ca2.png)
5.
![image](https://user-images.githubusercontent.com/64548726/188727578-51b9b2ce-693c-4d4d-9d49-0e5a66276c68.png)

**Platform**
 - Infor Application/Team Name: Lawson
 - OS Version: Windows 10
 - Browser Name: Chrome

**Additional context**
[test-editable-colorpicker.zip](https://github.com/infor-design/enterprise/files/9500412/test-editable-colorpicker.zip)

**Comment by ericangeles** [comment]
It looks like this issue has been for a while now. I think to fix it, the caret/trigger icon should be on the right portion of the row and not over the color picker.

**Comment by ericangeles** [comment]
Tagging it as `3` because there are a lot of areas that should be considered to fix it. (Row heights for intance)

**Comment by tmcconechy** [comment]
I think this will be fixed by https://github.com/infor-design/enterprise/pull/6755 but this didnt make the current release.

**Comment by jvang01** [comment]
@tmcconechy, @ericangeles, @yohannahbautista, the behavior of the colorpicker in the datagrid seems broken.  It will not allow you to click on the input and type in a value.  However, it will allow you to type in a value if you tab to the cell from an adjcent cell.  But even then the value will not register a change to the colorpicker.
![colorpicker-issues-in-datagrid](https://user-images.githubusercontent.com/64548726/188962044-ff57cb92-6d5e-46dd-a8d2-8f468cea2084.gif)

**Comment by tmcconechy** [comment]
understood @jvang01 it should be fixed soon when https://github.com/infor-design/enterprise/pull/6755 is done. Its all messed up right now

**Comment by glenlieorillo** [comment]
QA tested and passed.
http://localhost:4000/components/datagrid/test-editable-colorpicker.html

https://user-images.githubusercontent.com/102151352/192420420-e1503641-d207-4f56-af1c-de8a27212dd9.mov
