### ISSUE TITLE
Datepicker: Add ability to add new custom buttons in date picker

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#6800]
**Describe the Enhancement**
Provide the ability to add new custom buttons in date picker monthview model popup. We need to add buttons like "Clear" and "Never Expire".  We currently do this by overriding the sohoxi.js but this is not sustainable.

<img width="576" alt="Never_Expires" src="https://user-images.githubusercontent.com/42198413/188897282-ec22fb52-f8f5-4075-9196-920fb1958fa0.png">

**Expected behavior**
Suggested by @tmcconechy is we could customize the buttons where clear/apply are and add a custom button (never expires). This would work similar to the buttons option in modal.js

**Additional context**
MS Teams - ask @tmcconechy

**Comment by ericangeles** [comment]
@tmcconechy, do we need to align this with the designers?

**Comment by tmcconechy** [comment]
I dont think so but will put it in grooming. All it is changing the button text/operations, no visual changes. But i consider it low priority due to being a workaround

**Comment by ericangeles** [comment]
Agree

**Comment by tmcconechy** [comment]
After discussing we dont think this hyperlink should be there. Suggest using a checkbox next to the field. Thanks
