### ISSUE TITLE
Datagrid: Need extra class setting for adding a class to the new datagrid icon tooltip

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#6802]
This is releated to: Datagrid: Add ability to have an icon on the datagrid header with a tooltip #6490

**Is your feature request related to a problem or use case? Please describe.**
For the new icon tooltip (#6490) we need an "extraClass" setting that is added to the .tooltip element so we modify the css for the tooltip to make it more readable for longer sections of text. 

**Describe the solution you'd like**
Add a headerIconTooltipExtraClass to the datagrid column definition. Apply that class to the .tooltip displayed on hover.
```
{
  id: 'productName',
  headerIconTooltip: headerIconTooltipContent,
  headerIconTooltipExtraClass: 'lm-custom-tooltip-style'  <---
}
```
**Describe alternatives you've considered**
I cannot find another specific enough way to change the css for that tooltip.

**Additional context**

![image](https://user-images.githubusercontent.com/4737815/189170159-1a55bfee-d2b7-4fd3-8087-f7db56238f46.png)

And what application do you work on? Infor Landmark

**Comment by tmcconechy** [comment]
We only had added `headerCssClass` so that i guess would not work in this situation. Maybe `headerTooltipCssClass` would match for names to this.

**Comment by pwpatton** [comment]
I wouldn't want to regular tooltip to take on our styling for this icon tooltip tho.

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to done. thanks
