### ISSUE TITLE
Sink Page: Popover - incorrect placement of the 'Apply' button

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6804]
**Describe the bug**
'Apply' button in the popover was placed incorrectly. 

**To Reproduce**

1. Go to https://4671-beta0-enterprise.demo.design.infor.com/#
2. Go to Popover
3. Click on 'Click To Show Popover' button

**Expected behavior**
'Apply' button should be in the correct placement.

**Version**

- ids-enterprise: 4671-beta0

**Screenshots**
<img width="935" alt="image" src="https://user-images.githubusercontent.com/102151352/189338363-0c99dbf6-b85f-47f6-8899-1599fe959192.png">

**Platform**
 - Browser Name: Mac-Firefox and Mac-Edge

**Comment by ericangeles** [comment]
Looks like the `.demo-popover` CSS rules were missing.
