### ISSUE TITLE
About: minor issue with mobile and cookie values are not translated

### ISSUE THREAD

**Issue by SofiK** [infor-design/enterprise#6805]
**Describe the bug**
A minor issue with the mobile and cookie values are always shown as true or false. I assume these should perhaps be changed to yes and no and also be translated to other languages. Or if true/false then it should be "sant"/"falskt" in Swedish

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/about/example-index.html?locale=sv-SE
2. Click on 'Show about'
3. scroll down to the bottom.
4. notice that "Mobil" and "Cookies aktiverade" values are false respective true. They are not translated

**Expected behavior**
I was expecting the value false to be "nej" (no in English) or "falskt" (false in English) and true to be "ja" (yes in English) or "sant" (true in English)

**Version**

- ids-enterprise: 4.65.6 (but reproducible in  4.67.0-dev)

**Screenshots**
![image](https://user-images.githubusercontent.com/8664975/189360396-427d26da-4c35-4b5a-ba65-9df1837e3054.png)

**Platform**
 - Infor Application/Team Name: Homepages
 - OS Version: Windows 10
 - Browser Name: Chrome

**Additional context**
-

**Comment by tmcconechy** [comment]
Do we think these informations are even valuable? I have to already remove the OS information as chrome is no longer going to provide it at some point could also trim some of this other stuff out.

**Comment by SofiK** [comment]
I am not sure maybe they are not needed. I will check with the team and see what they say.

**Comment by SofiK** [comment]
Hi Tim, From our side it seems there are no issue to remove that information.
