### ISSUE TITLE
Typography: Text link color is incorrect in Dark mode

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#6807]
**Describe the bug**

With the recent color/token changes particularly in dark mode, the `.text-link` color is incorrect in dark mode.

**To Reproduce**

1. Go to http://localhost:4000/components/typography/example-index.html?theme=new&mode=dark&colors=0066D4
2. Under `Typographic Characteristics (class)` find `Link Text (text-link)`
3. The `.text-link` class color should be `#0072ED` and not `#606066`

**Expected behavior**
 The `.text-link` class color should be `#0072ED` and not `#606066`

**Version**

- ids-enterprise: [v4.67.0]

**Comment by jbrcna** [comment]
QA Passed. v4.68.0-dev
<img width="785" alt="image" src="https://user-images.githubusercontent.com/56722184/191636637-8492b307-024c-4de1-8096-33994fb29e37.png">
