### ISSUE TITLE
Unit Testing: Create a Puppeteer Script for "Calendar: Day Shading and Day Legend required in Week and Day view (already present in Month view)"

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#6809]
Describe the Issue
Create a unit testing for "Calendar: Day Shading and Day Legend required in Week and Day view (already present in Month view)".

See attached BDD for more information.
[BDDStory_github6568.docx](https://github.com/infor-design/enterprise/files/9544252/BDDStory_github6568.docx)

Related github issue
#6568

**Comment by maezcruz** [comment]
Cc: @CindyMercadoReyes

**Comment by ericangeles** [comment]
Closing as this one is already created.
