### ISSUE TITLE
Datagrid: date-icon does not show in datagrid columns. 

### ISSUE THREAD

**Issue by martinabdulghni** [infor-design/enterprise#6812]
Hi,

My date columns does not show the datepicker-icon. It works fine on other icons, such as 'time'.

date column: (does not show date-icon)
`{ id: 'startDate', name: '', field: 'startDate', sortable: false, filterType: 'date', formatter: Soho.Formatters.Date, dateFormat: 'yyyyMMdd' }` 
<img width="153" alt="image" src="https://user-images.githubusercontent.com/95101987/189603125-ce062631-fc79-4339-a495-02d55020b17a.png">

And if I change filterType to 'time':
time column: (does show time-icon)
` { id: 'startDate', name: '', field: 'startDate',  sortable: false, filterType: 'time', formatter: Soho.Formatters.Time }`

<img width="227" alt="image" src="https://user-images.githubusercontent.com/95101987/189602610-8e017c97-0948-4548-a2eb-71b119cad8f6.png">

I have tried to expand the column and use other methods to insert the columns into the datagrid, but nothing worked. 

**Version**
- ids-enterprise: [v4.64]

**Comment by ericangeles** [comment]
I don't see any problem with this example that has `filterType: 'date'` in this example https://4640-enterprise.demo.design.infor.com/components/datagrid/test-editable-datetime.html

**Comment by tmcconechy** [comment]
I cant reproduce it either @martinabdulghni

**Comment by martinabdulghni** [comment]
My bad, I am using enterprise-ng and not enterprise.
