### ISSUE TITLE
Datagrid: Request to put a null guard on specific line of code (see screenshot) to avoid undefined error

### ISSUE THREAD

**Issue by gilbugauisan** [infor-design/enterprise#6816]
**Describe the bug**
When the tree list is not yet loaded into the grid, soho is returning an undefined error caused by accessing an undefined element from the grid.

**To Reproduce**
Can't reproduce in ids local build since it's an application specific scenario where asynchronous operations are involved. See screenshots.

**Expected behavior**

**Version**
- ids-enterprise: 4.64.6

**Screenshots**
![image](https://user-images.githubusercontent.com/74726741/189902920-e5cb400c-d859-498e-bb1b-aba6112867b7.png)

![image](https://user-images.githubusercontent.com/74726741/189903015-d3e380ec-aa0a-4ee0-a773-510296baab6d.png)

**Platform**
 - Infor Application/Team Name: Infor Landmark
 - Device: Browser
 - OS Version: Windows 11
 - Browser Name: Edge
 - Browser Version: Version 104.0.1293.63 (Official build) (64-bit)

**Additional context**
Request to put a null guard on specific line of code (see screenshot) to avoid undefined error

**Comment by tmcconechy** [comment]
@ericangeles lets just add the guard even tho we cant reproduce

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to Done.
