### ISSUE TITLE
Demo App: Example page icons are in blue

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6817]
**Describe the bug**
All the icons of the example page are in blue.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/list
2. Click on any component with an example page
3. See error

**Expected behavior**
Example page icons are in blue, it should be red.

**Version**

- ids-enterprise: 4.68.0-dev

**Screenshots**

**Main:**
![image](https://user-images.githubusercontent.com/102151352/190058998-b3cd9fb5-8a73-4c9a-a891-f20a7ceb9358.png)

**Older version:**
![image](https://user-images.githubusercontent.com/102151352/190059111-f60995ac-c693-4cd0-a492-5bd4158ef797.png)

**Comment by tmcconechy** [comment]
You can see there is a 404 error and thats why it does this. 
```
GET https://main-enterprise.demo.design.infor.com/css/demo.css net::ERR_ABORTED 404
```

This comes from https://github.com/infor-design/enterprise/blob/main/package.json#L38 so maybe either this is not running or this file is not being copied when deployed. Either way probably need @corpulent to check it out

**Comment by tmcconechy** [comment]
This was fixed on the dev ops side (deployment issue)

**Comment by glenlieorillo** [comment]
QA tested and passed.
Version: 4.68.0-dev

https://user-images.githubusercontent.com/102151352/192210099-46de1825-2aff-4546-af36-be324d1dc34f.mov

**Comment by jbrcna** [comment]
Hello, the issue reoccured.
<img width="460" alt="image" src="https://user-images.githubusercontent.com/56722184/216274281-8bbe75c9-0fcd-47a7-9465-3e52e36c103b.png">
