### ISSUE TITLE
Splitter: Not working fine when we dynamically change the container height

### ISSUE THREAD

**Issue by mikolajmazurek3** [infor-design/enterprise#6819]
**Describe the bug**
The layout that I am trying to implement is very similar to this stackblitz that I created: https://stackblitz.com/edit/ids-quick-start-1421-vhs139?file=src%2Fapp%2Fapp.component.ts
Splitter component is not working fine when I dynamically change the height of container where the splitter is (by hiding blue **div** in javascript code). It somehow keep the original height and if I try to hide bottom area using splitter the bug appears.

**To Reproduce**
1. Go to stackblitz: https://stackblitz.com/edit/ids-quick-start-1421-vhs139?file=src%2Fapp%2Fapp.component.ts
2. Try to resize yellow and gray area using the splitter. Everything is working fine, we are able to hide entirely yellow area and gray area
3. Click on "close" text - blue area will disappear. Now we have only two areas and the splitter between 
4. Try to resize yellow and gray area using the splitter again 
5. Try to hide whole gray area - it's impossible (check the screenshot below)

**Expected behavior**
Splitter component should work for each position and resolution (the bug appears also when user first time render the application with not maximized browser and then he will maximize the browser, bug will appear)

**Version**
ids-enterprise-ng: 14.2.1

**Screenshots**
With visible blue area:
![image](https://user-images.githubusercontent.com/113527688/190169787-ffb278ed-27f7-44cb-b059-1eab88f27260.png)

With invisible blue area: (bug)
![image](https://user-images.githubusercontent.com/113527688/190165062-7b37b356-a54c-4779-aea1-a6539a35f6f0.png)

**Platform**
 - Device: Dell Precision
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 105.0.5195.102 (Official Build) (64-bit)

**Comment by jbrcna** [comment]
this is now working in localhost. will retest once fix is available in main
<img width="993" alt="image" src="https://user-images.githubusercontent.com/56722184/197145157-c3b5f4c0-0b47-4f58-832e-7e64d1e3ea38.png">

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
