### ISSUE TITLE
Accordion and Card component: Expanding/collapsing accordion is closing all cards on the UI

### ISSUE THREAD

**Issue by mikolajmazurek3** [infor-design/enterprise#6820]
**Describe the bug**
When I use accordion and card component on the same page I am facing strange issue. Opening or closing accordion component triggers collapsing all cards that are present on the UI. I prepared very simple stackblitz(https://stackblitz.com/edit/ids-quick-start-1421-4f29vv?file=src%2Fapp%2Fapp.component.html) where I have accordion with four items and two cards that are expandable. I tried to find something in documentation but I was unable to find property that could prevent it. So it looks like a bug to me.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1421-4f29vv?file=src%2Fapp%2Fapp.component.html
2. All accordion panes are collapsed by the default and two cards on the right are expanded by default
3. Try to expand accordion pane by clicking on header (no matter which one)
4. Selected accordion pane is expanding but in the same time both of cards on the right are collapsing (this is incorrect behavior)
5. Open one or both cards on the right
6. Try to collapse accordion pane by clicking on header
7. Cards are also collapsing - each interaction with this accordion collapse/expand is closing card component

**Expected behavior**
Interacting with accordion by clicking on headers should not affect other components. Opening accordion pane should not close card component.

**Version**
ids-enterprise-ng: 14.2.1

**Screenshots**
Default state:
![image](https://user-images.githubusercontent.com/113527688/190181566-0126a843-3a28-430b-9f1a-d0719521f27a.png)

After click on "Test 2" header:
![image](https://user-images.githubusercontent.com/113527688/190181708-831c0740-8862-4665-86e1-ba03fe71c9fc.png)

**Platform**
Device: Dell Precision
OS Version: Windows 11
Browser Name: Chrome
Browser Version: 105.0.5195.102 (Official Build) (64-bit)

**Comment by jbrcna** [comment]
QA PAssed . v4.70.0-dev
https://main-enterprise.demo.design.infor.com/components/applicationmenu/test-accordion-card.html
<img width="1563" alt="image" src="https://user-images.githubusercontent.com/56722184/204448153-7d4b2cbf-b2c7-4eaf-9ce6-890a95cf94de.png">

**Comment by yohannahbautista** [comment]
> Once applying the fix to this example https://stackblitz.com/edit/ids-quick-start-1480-h8du6h?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts you can still see the issue so repoening.
> 
> 1. go to https://stackblitz.com/edit/ids-quick-start-1480-h8du6h?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts
> 2. expand the Test 1 card
> 3. click on the header 2 accordion
> 
> It looks as if everything is updated ~ can you take another look @yohannahbautista ?

@tmcconechy @ericangeles 
Hello, I checked by copy-pasting the stackblitz in local and it works fine. There's another example page for NG to test this bug as well and it looks okay: http://localhost:4200/ids-enterprise-ng-demo/accordion/card

**Comment by tmcconechy** [comment]
@yohannahbautista can you do a pull request with a new example based on the code in that new stack blitz? So we can see its working...

**Comment by yohannahbautista** [comment]
> @yohannahbautista can you do a pull request with a new example based on the code in that new stack blitz? So we can see its working...
> 
> I looked at that stackblitz and it has the new enterprise version it seems? Any idea why the stack blitz doesnt work?

@tmcconechy 
Hello, looking into it more and the bug appears if I add the nofrills layout: https://main-enterprise.demo.design.infor.com/components/applicationmenu/test-accordion-card.html?layout=nofrills
Will start on fix based on that

**Comment by janahintal** [comment]
This is now working as expected in https://main-enterprise.demo.design.infor.com/components/applicationmenu/test-accordion-card.html?theme=classic&mode=light&colors=2578a9&layout=nofrills
Tested on both Classic and New theme and when in responsive view as well. Thanks!

**Comment by tmcconechy** [comment]
FYI this is patched in https://www.npmjs.com/package/ids-enterprise-ng/v/14.8.2?activeTab=versions i believe. @mikolajmazurek3
