### ISSUE TITLE
Checkbox: Label not wrapping at end of column with both page-container and form-responsive classes included on page

### ISSUE THREAD

**Issue by danders17** [infor-design/enterprise#6826]
**Describe the bug**
Checkbox label is not wrapping if the column size is smaller than length if both page-container and form-responsive classes are used on the page

**To Reproduce**
Got to sample at https://main-enterprise.demo.design.infor.com/components/checkboxes/example-index.html and change column to one-column and add form-responsive tag to the row.  The checkbox labels do not wrap.  If remove form-responsive from the row tag, it then wraps at end of the one column as shown in screen shots below

**Expected behavior**
The checkbox labels should wrap when hit the end of the column rather than running into the next column which potentially could have other information in it.

**Version**

- ids-enterprise: v4.51.1

**Screenshots**
Without form-responsive
![image](https://user-images.githubusercontent.com/3855683/190426778-f88d2b7f-9abe-434f-bcdc-ae98a33a375a.png)
With form-responsive, labels do not wrap at end of column
![image](https://user-images.githubusercontent.com/3855683/190427103-311b82d0-7e95-44b0-9ea0-ea5d7f1bd906.png)

**Platform**
 - Infor Application/Team Name: Infor Property Management and Construction/IPM
  - Windows 10
 - Edge
 - Version 105.0.1343.27 (Official build) (64-bit)

**Comment by tmcconechy** [comment]
Is this still an issue. I think we solved this over chat maybe?

**Comment by danders17** [comment]
Yes, it is still an issue as far as I know.  We did not resolve over chat with your suggestions so you said add the issue.

Thanks,
Dave

**Comment by janahintal** [comment]
QA Passed. Now working as expected in https://main-enterprise.demo.design.infor.com/components/checkboxes/test-checkboxes-with-form-responsive?theme=classic&mode=light&colors=2578a9 on both classis and new version
