### ISSUE TITLE
Monthly Veracode Rescan (possible automation?)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#683]
**Describe the Task**

This issue is a reminder to scan 4.11 on veracode for static scan https://login.infor.com/Veracode
This is a requirement from the ISO team.

Scan Requirements
-	Monthly Static Scans
-	Quarterly Dynamic Scans
Note: We are still working with Veracode on resolving the issue with scanning apps within Ming.le
 
Grace Period
-	Remediation’s for findings are to be completed within the grace period per Policy. See FAQ below
 
https://wiki.infor.com/confluence/display/ISO/Security+Scanning+FAQ#SecurityScanningFAQ-13.Q.WhatistheApplicationCompliancerequirementforVeracodeScan

**Comment by clepore** [comment]
@tmcconechy has suggested possibly automating this, which would be nice. He said the tool has a (jenkins plugin)[https://help.veracode.com/reader/PgbNZUD7j8aY7iG~hQZWxQ/_4G8gT1rhWMgVVtCI1C57A] that can automate submitting a static or dynamic scan. For development we could use @tmcconechy 's api key, but preferably request one specifically for our "bot" so we can keep things silo'd.

**Comment by nickwynja** [comment]
I looked into this a bit more. I was able to get the Veracode plugin installed but we need to work out where this fits into the development process.

* "Monthly" seems kind of arbitrary, but luckily for us, I think we should fit this into our monthly release cadence
* It makes sense to do it as the code for a release stabilizes but not too late where we can't fix critical vulnerabilities
* Which leads me to believe we should do the scan around the time we're making a `beta` cut of a release

The Jenkins plugin seems to not have any conditionals, so I think we'd have to create a unique job just for uploading the scan. We can then trigger that scan from the command line. We'd add this task as part of the beta release playbook.

**Comment by tmcconechy** [comment]
We could also scan nightly as an idea. That way you do get pretty immediate feedback on what you worked on. Just one idea here. But im also fine with starting out monthly for the time being.

**Comment by clepore** [comment]
Approximately how long does a scan take?

**Comment by tmcconechy** [comment]
Varies on system load but usually between 1-4 hrs from my experience

**Comment by clepore** [comment]
Since its not automated yet, @tmcconechy will manually fun on `4.11.0-beta.0` on Friday 9/29/18.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the Done bucket.
