### ISSUE TITLE
Monthview: Restricted month selection is not working as expected

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#6832]
**Describe the bug**
Monthview: Restricted month selection is not working as expected

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/monthview/test-restrict-month-selection.html
2. Click the <> button 
3. And try to select using the calendar button 

**Expected behavior**
Should restrict month selection

**Version**
4.68-ids-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/191017988-74cbd224-afb1-40f9-bac8-610ae8b62bd9.png)

**Platform**
Windows 10 and all major browser and devices. 

**Additional context**
N/A

**Comment by tmcconechy** [comment]
FYI this example is set to:

```
minDate: '04/01/2018',
maxDate: '06/30/2018'
```

Seems like it's working to me? Can you clarify the steps?
