### ISSUE TITLE
Breadcrumb: flex-toolbar icon cut off

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6836]
**Describe the bug**
btn-icon is cut off in mobile when using `new theme`

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/breadcrumb/test-flex-toolbar.html
2. See error

**Expected behavior**
should not be cut off

**Version**

- ids-enterprise: v4.68.0-dev

**Screenshots**
<img width="627" alt="image" src="https://user-images.githubusercontent.com/56722184/191231653-1cf0146e-09ce-4569-9b6d-ebb2d120ee43.png">

**Platform**
mobile device android and iOS

**Additional context**

**Comment by tmcconechy** [comment]
Issue cant be fixed the way flex toolbar works
