### ISSUE TITLE
Week View: Calendar icon alignment issue

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6839]
**Describe the bug**
Misaligned calendar icon and text in Firefox.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/week-view/example-index.html, https://main-enterprise.demo.design.infor.com/components/week-view/example-one-day.html, https://main-enterprise.demo.design.infor.com/components/week-view/example-two-day.html and https://main-enterprise.demo.design.infor.com/components/week-view/example-two-weeks.html
2. Notice the calendar icon
3. See error

**Expected behavior**
Calendar icon and text should be aligned in Firefox.

**Version**

- ids-enterprise: 4.68.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/102151352/191409311-35d059cc-5e25-4739-a845-0b3b88ea40f6.png)

https://user-images.githubusercontent.com/102151352/191409064-8344b041-cdd0-4302-8521-bcb58c11f7ec.mov

**Platform**
 - Firefox

**Comment by tmcconechy** [comment]
No longer seems to be an issue
