### ISSUE TITLE
Show Mobile Device and Version on About page component

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#684]
**Is your feature request related to a problem? Please describe.**
Show Mobile Device and Version on About page component

**Describe the solution you'd like**
Currently on the About page for mobile the information being displayed is being pulled from the browser. It would be great if the About page displays the device and version.

I'm attaching a screen shot of what is currently being displayed on the About page for mobile.

**Describe alternatives you've considered**
Reference below:
https://stackoverflow.com/questions/11381673/detecting-a-mobile-browser

**Additional context**

![bs_realdroid_mobile_samsung galaxy s9 plus-8 0-1440x2960](https://user-images.githubusercontent.com/39101346/44729812-94f5c900-aaad-11e8-86b3-0dced1550b48.jpg)

**Comment by EdwardCoyle** [comment]
Would need to extend the `Environment` core component to announce the device type.  Also note that what gets reported through the user agent string will not always 100% match the device type provided, using the method suggested.  Doing this correctly (or close to it) would need some research.

**Comment by tmcconechy** [comment]
yeah ok, was thinking about using Environment as well , i not sure if we can get a version or not yet but we can definitely get the device name. Lets make it a 5 then.

**Comment by EdwardCoyle** [comment]
@CindyMercadoReyes when you say "version", which do you mean?

- Device's hardware version (like Samsung Galaxy S8)
- Device's software version (like Android 8.1.0, or iOS 11.2)
- IDS version

Not sure if we could do the first one based on User Agent string... the other two we could make happen via the `Environment` core component the same way

**Comment by ericangeles** [comment]
@tmcconechy definitely.
