### ISSUE TITLE
Toolbar Flex: Incorrect destroy function for 'toolbarflexitem' component

### ISSUE THREAD

**Issue by InforBG** [infor-design/enterprise#6844]
**Describe the bug**
The change in <https://github.com/infor-design/enterprise/pull/6439> fixed a memory leak problem, but create new issue.
The 'toolbarflexitem' component is not destroyed correctly.
Line 22 in https://github.com/infor-design/enterprise/blob/4.67.x/src/components/toolbar-flex/toolbar-flex.item.jquery.js, it should be corrected from
```js
$.removeData(this, COMPONENT_NAME);
```
to
```js
if (this.element) $.removeData(this.element, COMPONENT_NAME);
```
It is because the data value is set in toolbar button object, not in 'instance' object. The original code `$.removeData(this, COMPONENT_NAME);` will always do nothing.

Because the component is not destroyed correctly, the toolbarflexitem cannot be re-initialised again. See line 10 in <https://github.com/infor-design/enterprise/blob/4.67.x/src/components/toolbar-flex/toolbar-flex.item.jquery.js#L10>, the instance variable will always have value. The expected result is the instance variable should be undefined after being destroyed.

After I correct the line 22 in toolbar-flex.item.jquery.js, there are other issues at line 728 and 731 in <https://github.com/infor-design/enterprise/blob/4.67.x/src/components/toolbar-flex/toolbar-flex.item.js#L728>. The 'originalButtonAPI' variable could be undefined after being successfully destroyed. When destroying the 'More' button, it will try to unlink those predefinedItems that has already been done before. Need some null point check on the two lines like below:
```
line 728:   if (originalButtonAPI) originalButtonAPI.actionButtonLink = null;
line 731:   if (originalButtonAPI && originalButtonAPI.type === 'menubutton') {
```

**To Reproduce**

Sorry that I cannot use the pure html page to reproduce the problem. I can only reproduce the issue in our GWT projects.

**Expected behavior**
The 'toolbarflexitem' component should be destroyed correctly.

**Version**

- ids-enterprise: [v4.67.1]

**Screenshots**
N/A

**Platform**
 - Infor Application/Team Name: [Infor SunSystems]
 - Device: (if applicable) [N/A]
 - OS Version: [Windows 11]
 - Browser Name: [chrome]
 - Browser Version: [105.0.5195.127 (Official Build) (64-bit) (cohort: Stable)]

**Additional context**
N/A

**Comment by InforBG** [comment]
Except the problems above, there is another problem about the focusedItem/trueFocusedItem in toolbar-flex.js.  
When destroying the toolbar-flex, the focusedItem/trueFocusedItem object is not deleted in toolbar-flex. But the element within the focusedItem/trueFocusedItem are destroyed. So line 168 in toolbar-flex.item.js, `this.element.tabIndex = 0;` in set focused(boolean) function, the `this.element` is undefined. Error occurs.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
