### ISSUE TITLE
Count: Misalignment when a user has two count-components when one of the labels are two rows 

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise#6845]
**Describe the bug**
Misalignment when a user has two count-components when one of the labels are two rows 

**To Reproduce**
Go to this website: https://master-enterprise.demo.design.infor.com/components/counts/example-widget-count.html

Open dev-tools and give one count a long label.

It will then look something like this:
![image](https://user-images.githubusercontent.com/4634476/191765311-f9e33acc-93ef-4872-8d81-1dfcb19f86a3.png)

**Expected behavior**
The label would either be truncated or the alignment should only be focusing on the circle and not the labels.

**Version**
Enterprise 4.67.0

**Comment by tmcconechy** [comment]
Might be able to do something with the flex alignment classes here https://main-enterprise.demo.design.infor.com/components/form/example-align-field-bottoms.html (or flex box in general)

**Comment by ericangeles** [comment]
Yeah, my initial fix here is to use flex and add a class for truncation.

**Comment by glenlieorillo** [comment]
QA Failed. Bug still exists.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/201243396-5e39aed0-a3c3-4df6-8cfb-a230db1dedfe.png">

**Comment by jbrcna** [comment]
the issue still exist on firefox browser
https://main-enterprise.demo.design.infor.com/components/counts/test-widget-long-title.html
<img width="811" alt="image" src="https://user-images.githubusercontent.com/56722184/201551434-1f7d8d93-b0e1-47d4-8463-c6a17a3e2fed.png">
http://localhost:4000/components/counts/test-widget-long-title.html
<img width="601" alt="image" src="https://user-images.githubusercontent.com/56722184/201551514-2fa99249-9814-4705-b078-6081713c45e8.png">

**Comment by ericangeles** [comment]
Please check @tjamesallen15

**Comment by jbrcna** [comment]
QA Passed. v4.70.0-dev
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/56722184/205268072-a659703d-7ace-481d-8301-135b861eaa25.png">
