### ISSUE TITLE
Datagrid: Error with multiselect filter on datagrid

### ISSUE THREAD

**Issue by jayblack-infor** [infor-design/enterprise#6846]
**Describe the bug**
When trying to filter a datagrid using a multiselect ddlb and you click the dropdown you can't select a value because of an error being thrown.   

**To Reproduce**
The error only occurs in angular environment where using shadowdom encapsulation.    

**Version**
4.67/14.3.1

**Screenshots**
![image](https://user-images.githubusercontent.com/45010485/191820481-f85cdccf-21b7-4da9-bdeb-caf3db0daf84.png)

![image](https://user-images.githubusercontent.com/45010485/191820534-e1c20bc4-3244-4a58-b61a-3ce65d11f23b.png)

**Fix Proposal**

```
if (this.list.hasClass('datagrid-filter-dropdown')) {
                **if (document.querySelector('.datagrid-container') !== null) {**
               const gridContainerPos = document.querySelector('.datagrid-container').getBoundingClientRect().right;
               const gridFilterDropdownPos = document.querySelector('.datagrid-filter-dropdown').getBoundingClientRect().right;
               const pageContainerPos = document.querySelector('.page-container').getBoundingClientRect().right;
                               const adjustedPosition = pageContainerPos - gridContainerPos;
               if (gridContainerPos.right < gridFilterDropdownPos.right) {
                               this.list[0].style.right = "".concat(adjustedPosition, "px");
                               this.list[0].style.left = '';
               }
 
               if (Locale.isRTL() && gridFilterDropdownPos.left < 0) {
                               this.list[0].style.left = "".concat(gridContainerPos.left, "px");
               }
                }
      }
```

**Comment by tjamesallen15** [comment]
Can you provide more input regarding this issue like test page or can you update the description? I tried testing it in our environment and I can't reproduce the issue. @jayblack-infor  Thanks!

**Comment by jayblack-infor** [comment]
Hi James.   You could only duplicate if using using shadowdom encapsulation.   If you could just provide a safety check similar to what I suggested above that should handle it.

**Comment by tmcconechy** [comment]
@tjamesallen15 I think its fine to just add the code above as an extra check...  Thanks!

**Comment by jbrcna** [comment]
QA Passed. moving this ticket to done.
https://main-enterprise.demo.design.infor.com/components/datagrid/test-filter-zero-as-text.html
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/56722184/197157907-7b92a156-4bf4-4aec-bf67-5c9d4c2e16e8.png">

**Comment by jayblack-infor** [comment]
What release will this be included in?   Looks like it's 4.69.x.   Can you update to let me know when it's included and what release?   Thanks

**Comment by tmcconechy** [comment]
It will be in 4.69. Correct. Will be sometime in early Nov. Watch the announcements in MS Teams for that 👍🏻

**Comment by jayblack-infor** [comment]
Thanks

**Comment by jayblack-infor** [comment]
Is there an ETA for 4.69?   Just trying to plan.  Thanks

**Comment by tmcconechy** [comment]
Its a bit late - going to beta today. So about a week

**Comment by jayblack-infor** [comment]
Ok.   Thanks
