### ISSUE TITLE
Locale: addCulture function only adds the first locale entry of the language

### ISSUE THREAD

**Issue by bempedragosa** [infor-design/enterprise#6847]
**Describe the bug**
addCulture function only adds the first locale entry of the language and ignores the rest.
Example: 3 locales loaded for zh_TW (en_US, zh_CN, zh_TW)
note: we also load the parent locale which is the zh_CN
- zh_CN locale entry will be added to this.language as zh and zh_CN
- When it's zh-TW turn to be added, it is ignored since it's already present on the this.languages.

**To Reproduce**

1. https://main-enterprise.demo.design.infor.com/components/locale/test-translated-strings.html?locale=zh-TW
2. Add breakpoint on locale.js > addCulture function

![Screenshot 2022-09-23 092633](https://user-images.githubusercontent.com/58026209/191877705-b6d3ff89-3148-4782-b7f1-8c31212de211.png)

**Comment by ericangeles** [comment]
What's your use case here @bempedragosa ?

**Comment by tmcconechy** [comment]
Generally the locals will load if you call `Locale.set('en-US')` and they are setup correctly. Shouldn't be any need to call this internal method directly..

**Comment by bempedragosa** [comment]
Yes @tmcconechy . That's right. When Locale.set('zh-TW') loads the locale, there are 3 locale javascript files being loaded. The en-US, zh-TW and zh-CN. The locale js file call the addCulture function which adds the locale data to _**this.languages**_ (see pic below). In this case,  the parent locale which is the **zh-CN** is added first to language list. It will be added as, zh and zh-CN (see the selected code). So when it's zh-TW turn to be added,  it is ignored since it's already present on the language list.

![addCulture](https://user-images.githubusercontent.com/58026209/193960270-6fc3b48c-9ba4-4cf1-82ae-58480036ac81.png)

**Comment by bempedragosa** [comment]
Yes @tmcconechy . Just add some breakpoint to addCulture function and you'll see that the next language occurence with different region will be ignored since the language is already on the list.
