### ISSUE TITLE
datagrid-filter-dropdown: Cannot read properties of null (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by InforBG** [infor-design/enterprise#6859]
**Describe the bug**
The change in <https://github.com/infor-design/enterprise/commit/98779802f69d6e555280232eded723bf53e03a11>, line 2046, 
```js
const pageContainerPos = document.querySelector('[role="main"]').getBoundingClientRect().right;
```
requires the page container must have attribute 'role' and value 'main'.  
I wonder if it is mandatory for all web pages? Or can it be change back to original code as below?
```js
const pageContainerPos = document.querySelector('.page-container').getBoundingClientRect().right;
```
Our web applications doesn't have such attribute value and there will be following error when using filter dropdown in datagrid:
```
Exception: java.lang.JsException: TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
ConsoleLogger.java:33 TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at Dropdown.openList (dropdown.js:2046:32)
    at completeOpen (dropdown.js:1924:12)
    at Dropdown.open (dropdown.js:1932:7)
    at Dropdown.toggle (dropdown.js:2761:10)
    at HTMLDivElement.<anonymous> (dropdown.js:3777:14)
    at HTMLDivElement.dispatch (jquery-3.6.0.min.js:2:43064)
    at v.handle (jquery-3.6.0.min.js:2:41048)
```

**To Reproduce**

I can reproduce this issue with test-filter-dropdown-overflows.html. Just put the codes from this file into a html like this:
```hmtl
<section id="maincontent" class="page-container scrollable" role="main-why">
<!-- insert codes from test-filter-dropdown-overflows.html -->
</section>
```
Please note I change the role attribute value from `main` to `main-why`. Then the error in title can be seen after select the dropdown in grid filter. If I change the value back to 'main', the dropdown in grid filter works fine.

**Expected behavior**
There should be no `Cannot read properties of null (reading 'getBoundingClientRect')` error when use the filter dropdown in datagrid.

**Version**

- ids-enterprise: [4.67.1]

**Screenshots**
N/A

**Platform**
 - Infor Application/Team Name: [Infor SunSystems]
 - Browser Name: [chrome ]
 - Browser Version: [105.0.5195.127 (Official Build) (64-bit)]

**Additional context**
N/A

**Comment by ericangeles** [comment]
@InforBG `.page-container` is also being used in other sections of the page/s as well so we targeted the role=main attribute.

**Comment by ericangeles** [comment]
We can probably use `#maincontent` over `role="main"`.

**Comment by InforBG** [comment]
> @InforBG `.page-container` is also being used in other sections of the page/s as well so we targeted the role=main attribute as its main container.

@ericangeles , I think it is fine to for other sections to use `.page-container`.  
According to <https://www.w3schools.com/jsref/met_document_queryselector.asp>, `The querySelector() method returns the first element that matches a CSS selector`. So it will always get the web element in outmost. It will ignore the rest web elements within it. This is expected, right?

> We can probably use `#maincontent` over `role="main"`.

Unfortunately, our web applications don't have the `#maincontent` too.  
The outmost web element with `.page-container` is:
```html
<div class="page-container no-scroll sunsystemsPageContainer" id="application-container">
... ...
</div>
```

**Comment by tmcconechy** [comment]
Actually i would argue we should keep it as `role="main"` the reason this is selected is this is actually a required element. So i would suggest you add it for better accessibility https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/main_role and it should fix the issue...

In the past any teams with this issue just added the role. But perhaps we could do an order check:

- check for `role="main"`
- if none then `<main>`
- if none then `.page-container`
- if none then `body`

But might be overkill with the checking...

**Comment by InforBG** [comment]
I agree with you that adding the `role="main"` is a good option after reading the main_role page. No need to add more checking.  
I was just surprised that it still works in v4.61.2 and has issue in v4.67.1. And thought it's a new issue.  
This issue can be closed.  
Many thanks for your time.
