### ISSUE TITLE
[Mac Chrome 68] Arrange Component: Sortable List with Handles not working correctly

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#686]
**Describe the bug**
[Mac Chrome 68] Arrange Component: Sortable List with Handles not working correctly. It currently displays styling issues.  

**To Reproduce**
1. Go to http://4100-beta1-enterprise.demo.design.infor.com/components/arrange/example-index.html
2. Scroll down to "Sortable List with Handles" and try to drag "Item 1" above "Item 4"
3. The user is unable to move any of the items in the list

**Expected behavior**
User should be able to move items around either to the top, middle, or bottom of the list

**Screenshots**
![arrange component error](https://user-images.githubusercontent.com/39101346/44730991-33832980-aab0-11e8-9f98-38009c964008.png)

**Platform**
- MAC Chrome[e.g. chrome, safari, stock browser]
 - Browser Version [68]

**Additional context**
None

**Comment by tmcconechy** [comment]
The styling for this lives inside the components at the moment for example on listbuilder or swaplist. So its more important those work. This is like the underlying code for that.

Suggest we eventually style this page better and make sure everything on it is used or remove it (and that it works)

**Comment by tmcconechy** [comment]
Going to close and descope this as we labelled this a test page http://localhost:4000/components/arrange/test-scenarios.html

The visuals on this page are just "skeletons" they need to be used on a component like Swaplist to see the styling correctly. So test Swaplist and just ignore this page for visual QA
