### ISSUE TITLE
Popupmenu: Submenus and submenu items are sometimes incorrectly indented

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#6860]
**Describe the bug**
Submenus in the popupmenu are sometimes incorrectly indented. It seems to be caused by adding the classes
`has-selectable-submenu` and `is-selectable` (which is done [here](https://github.com/infor-design/enterprise/blob/a619f3c6d6116086a44b03fef07419c30c7abd54/src/components/popupmenu/popupmenu.js#L749) , which was a fix for [this bug](https://github.com/infor-design/enterprise/issues/6223)).

![bild](https://user-images.githubusercontent.com/63045013/192701507-b72930dd-801c-4a50-bbf5-967baa60e592.png)
![bild](https://user-images.githubusercontent.com/63045013/192701575-3abc5346-77d6-4576-a3ad-14681837d383.png)

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/popupmenu/test-handling-predefined-wrappers.html
2. Click on the popupmenu button

**Expected behavior**
The submenus and the submenu items shouldn't be indented in this scenario.

**Version**
- ids-enterprise: 4.68.0-dev

**Platform**
 - Infor Application/Team Name: Infor OS

**Comment by volante007** [comment]
Yes, it's adding the selectable classes if the menu contains `.separator` elements which is very strange. Separators in the main menu have nothing to do with whether the submenu contains selectable options.

**Comment by janahintal** [comment]
QA Passed. Verified working as expected in https://main-enterprise.demo.design.infor.com/components/popupmenu/test-handling-predefined-wrappers.html
Thanks!
