### ISSUE TITLE
Editor: Insert Image doesn't work when adding attributes

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#6864]
**Describe the bug**
Insert Image doesn't work when adding extra attributes to the editor.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1431-ykiuma?file=src/app/app.component.ts
2. Click on "Insert Image" in the editor toolbar.
3. Enter a valid url to an image, e.g. https://www.infor.com/img/logo-infor.png
4. Click "Insert"

**Expected behavior**
The image should be inserted into the editor.

**Version**
- ids-enterprise: 4.67.1

**Screenshots**
![bild](https://user-images.githubusercontent.com/63045013/192993608-e0c21e15-def1-4bc1-9d0f-ad1853d5b144.png)

**Platform**
 - Infor Application/Team Name: Infor OS

**Comment by tmcconechy** [comment]
Hmm they shouldnt have anything to do with each other. I do see an image is inserted but its just `<img>`. Do you think it could be a cross site issue?

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/editor/test-image-attribute.html. Thanks!
![image](https://user-images.githubusercontent.com/45757016/201108116-59178127-9972-4750-ba49-9c56a81c60cf.png)
