### ISSUE TITLE
Datagrid: Icon button is cut off with small rowheight

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6866]
**Describe the bug**
When using a new theme and a datagrid with a small rowheight, the top of the icon buttons are cut off.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/test-icon-buttons.html
2. Select Small row height from the toolbar menu
3. See that the top of the icon buttons are cut off
Note: If you cannot reproduce, change the scale on your display settings to 125%. I was not able to reproduce on my monitor at first because the scale was at 100% while the scale on my laptop was at 125% to reproduce the bug.

**Expected behavior**
It is expected that icon buttons are fully visible for each theme and row height in a datagrid.

**Version**
- ids-enterprise: v4.68.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/76002134/193083780-9f691dde-dd84-4ad8-add4-c78c91844aaf.png)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 106.0.5249.62 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Yeah looks like they could be pushed down a little

**Comment by glenlieorillo** [comment]
QA tested and passed.

http://localhost:4000/components/datagrid/test-icon-buttons.html
<img width="1792" alt="Screen Shot 2022-10-11 at 7 25 33 PM" src="https://user-images.githubusercontent.com/102151352/195082952-4bc74def-04bc-4ef1-89c7-82e83c85890d.png">

https://main-enterprise.demo.design.infor.com/components/datagrid/test-icon-buttons.html
<img width="1792" alt="Screen Shot 2022-10-11 at 7 23 28 PM" src="https://user-images.githubusercontent.com/102151352/195082991-0166eee4-91b1-4054-a7fe-7eded18d042c.png">

**Comment by s-werking** [comment]
Hi, just a note that this one may not be deployed to main. I'm seeing the issue still on 
https://main-enterprise.demo.design.infor.com/components/datagrid/test-icon-buttons.html but not on http://localhost:4000/components/datagrid/test-icon-buttons.html. Thanks

**Comment by ericangeles** [comment]
@s-werking it may have something to do with the build, but it will definitely added once it we merged other fixes in the main.

**Comment by tmcconechy** [comment]
yeah i think it was broken for a while and fixed on https://github.com/infor-design/enterprise/pull/6903
should update next time we merge a PR

**Comment by glenlieorillo** [comment]
It is now working as expected in main-enterprise.

Mac - Chrome
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/198159106-3c9927f4-da39-45c8-8f09-6acf48482d50.png">

Windows 11 - Chrome (BrowserStack)
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/198159282-942242ef-2689-4aeb-97ab-c493f28baff6.png">
