### ISSUE TITLE
Datagrid: Dirty indicator does not follow changed cell on column reorder

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6867]
**Describe the bug**
This bug is found on an editable table with reorderable columns and dirty indicators. When a change is made on a cell and the column order changes, the dirty indicator does not follow the changed cell to the new column.

**To Reproduce**
1. Add datagrid settings columnReorder: true and showDirty: true to http://localhost:4000/components/datagrid/example-editable.html
2. Go to http://localhost:4000/components/datagrid/example-editable.html
3. Make a cell change to show a dirty indicator on that cell
4. Reorder the changed column
5. See that the dirty indicator remains on the original cell that the change occurred

**Expected behavior**
It is expected that the dirty indicator follows the changed cell's column and row index changes.

**Version**
- ids-enterprise: v4.68.0-dev

**Screenshots**
![Dirty indicator row reorder](https://user-images.githubusercontent.com/76002134/193113958-67d4f1fd-824c-46d1-9168-02105c8b1ef0.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 106.0.5249.62 (Official Build) (64-bit)

**Comment by glenlieorillo** [comment]
QA tested and passed.
https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html

**Windows 11 - Chrome (BrowserStack)**

https://user-images.githubusercontent.com/102151352/195085326-824ca35e-be0b-44ac-ac5e-82f985c46ca7.mov

**Mac - Chrome**

https://user-images.githubusercontent.com/102151352/195085387-fbfa1dec-66c0-45f2-90d1-52457d0bef0e.mov

**Comment by s-werking** [comment]
Hi, we have encountered an issue related to this ticket after implementing this fix.

Steps to reproduce:
1. Go to http://localhost:4000/components/datagrid/example-editable.html
2. Make a cell change to show a dirty indicator on that cell
3. Reorder a different column over the dirty column
4. See that a dirty indicator appears on a cell that has not been changed

See this gif for reference:
![Dirty indicator on an unchanged cell](https://user-images.githubusercontent.com/76002134/196761309-390a0822-7188-4981-a687-9ae7c750d780.gif)

**Comment by ericangeles** [comment]
@yohannahbautista can you verify this?

**Comment by glenlieorillo** [comment]
It is now working as expected.

localhost

https://user-images.githubusercontent.com/102151352/198514434-4c012af4-f6bc-4941-b40d-504d4b73b42e.mov



main-enterprise

https://user-images.githubusercontent.com/102151352/198514449-dd6079f0-cbfa-4d1a-adf3-bbc351166a67.mov
