### ISSUE TITLE
Icons: Add new icons, filled icons and change the internal padding

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6868]
**Describe the bug**
This ticket is associated with https://jira.infor.com/browse/IDS-509 and will be used for the change log and Pull request to add changed and new icons from design. The current changes will include

- [ ] A new ids-identity version
- [ ] New icons
- [ ] New "fiilled" icons
- [ ] Changes to icon padding (2px on top and bottom)

**Tests/Tasks**
- [ ] Include new ids-identity version
- [ ] List New icons
- [ ] Mention New "fiilled" icons
- [ ] Test Changes to icon padding (2px on top and bottom)
- [ ] Check the take color in css and can be resized with css

**Comment by jbrcna** [comment]
Hello, see below my test findings :bug:
https://main-enterprise.demo.design.infor.com/components/validation/test-legacy-tooltip.html
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/56722184/200745984-c9403ddd-cf60-44c9-b145-ba4713d84127.png">

**_Observations_**:
https://main-enterprise.demo.design.infor.com/components/validation/test-error-on-tab.html?theme=classic&mode=light&colors=2578a9&locale=ar-SA – the icon beside 'Opportunites' (subtle difference, the icon is a little bit more on top)
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/56722184/200755960-d6f52095-f832-4f70-9f34-847f94857217.png">

https://main-enterprise.demo.design.infor.com/components/validation/test-error-on-tab.html?locale=ar-SA – Notice that the “Opportunities” label has moved up
<img width="703" alt="image" src="https://user-images.githubusercontent.com/56722184/200756057-3b4b29a4-a2bf-4e94-9a51-e7361023de7d.png">

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Tim did fix the additional issue just in case - but it was minor. I think i will add it to the final once the beta is approved

**Comment by jbrcna** [comment]
Thank you @CindyMercadoReyes
