### ISSUE TITLE
Datagrid: Scrollbar disappears on Safari browser

### ISSUE THREAD

**Issue by rdugenia** [infor-design/enterprise#6871]
**Describe the bug**
Scrollbar on datagrid disappears on Safari browser.

**To Reproduce**

1. Go to [datragrid example](https://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html)
2. Observe the horizontal scrollbar

Scrollbar seems to disappear and cannot scroll.

**Expected behavior**
Scrollbar on datagrid should show and able to scroll

**Version**

- ids-enterprise: 4.51.0-dev, 4.65.3

**Screenshots**
![Safari_missingScrollbar](https://user-images.githubusercontent.com/78482539/193774810-f96ccbf8-b4ac-4cbf-b7f5-0bf9b82c5945.gif)

**Platform**
 - OS Version: macOS Monterey
 - Browser Name: Safari
 - Browser Version: 15.3, 16.0

**Comment by tmcconechy** [comment]
i dont think this is fixable actually. I think it relates to this mac setting. (Show scroll bars in general). If you set this to "automatically based on mouse or trackpad" or "when scrolling" then it only shows when you "flick" or scroll with the magic mouse. You might want to set it to always on.

<img width="674" alt="Screen Shot 2022-10-04 at 10 24 30 AM" src="https://user-images.githubusercontent.com/814283/193845586-a71ec963-d715-49b1-a13d-793a6cca8eef.png">

**Comment by rdugenia** [comment]
I see, my bad :sweat_smile: Show scroll bars not set to Always. This is working on my end now, thanks Tim!

**Comment by tmcconechy** [comment]
Cool 👍🏻
