### ISSUE TITLE
Datepicker: Increment/Decrement date hotkeys do not work in Firefox

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6877]
**Describe the bug**
When using hotkeys to change the date in a field or cell in Firefox, the "+" and "-" keys do not increment/decrement the date. 
Note: The "+" and "-" keys in the number keypad successfully increment/decrement the date, but the "+" and "-" keys in the QWERTY keyboard do not.

**To Reproduce**
1. Add the settings 'incrementWithKeyboard: true' and 'todayWithKeyboard: true' to the editorOptions on the date column in http://localhost:4000/components/datagrid/example-editable.html
2. Go to http://localhost:4000/components/datagrid/example-editable.html in Firefox
3. Select a date cell to edit
4. Press the "+" and "-" keys on the QWERTY keyboard to increment/decrement the date
5. See that the date does not change

1. Go to http://localhost:4000/components/datepicker/test-datepicker-today-increment-key.html
2. Select the field to edit
3. Press the "+" and "-" keys on the QWERTY keyboard to increment/decrement the date
4. See that the date does not change

**Expected behavior**
The date should be incremented/decremented upon pressing the "+" and "-" keys on the QWERTY keyboard.

**Version**
- ids-enterprise: v4.68.0-dev

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: firefox
 - Browser Version: 106.0b8 (32-bit)

**Comment by s-werking** [comment]
Just a note: It looks like the keycodes for the +/- keys on a QWERTY keyboard differ between chrome and firefox.

chrome: "+" = 187
               "-" = 189

firefox: "+" = 61
             "-" = 173

**Comment by jbrcna** [comment]
QA PAssed. v4.70.0-dev
https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
https://main-enterprise.demo.design.infor.com/components/datepicker/test-datepicker-today-increment-key.html
![Large GIF (1506x560)](https://user-images.githubusercontent.com/56722184/201827688-089a42b4-7d3c-4fce-b603-ccd64a4055ff.gif)
