### ISSUE TITLE
File Upload Label Text

### ISSUE THREAD

**Issue by narrow89** [infor-design/enterprise#688]
There is a way to change the label text for file upload component?
Im trying localize the component.

**Comment by tmcconechy** [comment]
You should just be able to set the text in the label in the starting markup...
https://github.com/infor-design/enterprise/blob/master/app/views/components/fileupload/example-index.html#L6

**Comment by narrow89** [comment]
Yes, but i want to set the text from an angular scope variable. When i put:
`<div class="field">
      <label for="fileupload">{{myVariable}}</label>
      <input type="file" class="fileupload" id="fileupload" name="fileupload"/>
    </div>`
The generated new label contain literally text "{{myVariable}}".

**Comment by tmcconechy** [comment]
Try using a soho-label we have this in the examples which works..

```
        <div class="field">
          <label soho-label for={{name4}}>Limit File Types - {{limitLabel}}</label>
          <input soho-fileupload id={{name4}} name={{name4}} accept="{{fileLimits}}"/>
        </div>
```

**Comment by tmcconechy** [comment]
Assuming this worked, closing out this issue.
