### ISSUE TITLE
Weekview: month is formatted differently when 'Today' is clicked using mobile device

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6889]
**Describe the bug**
month is formatted differently when 'Today' is clicked using mobile device

**To Reproduce**

1. Go to 'https://main-enterprise.demo.design.infor.com/components/week-view/example-index.html'
2. Click on '`Today`'
3. See error
4. Notice the month is in different format. (displaying three letter month)

**Expected behavior**
should not change format

**Version**

- ids-enterprise: v4.69.0-dev

**Screenshots**
<img width="275" alt="image" src="https://user-images.githubusercontent.com/56722184/195239850-71e96784-61f6-49ab-87c0-fe12ccf8db65.png">

**Platform**
Android & iOS

**Additional context**

**Comment by ericangeles** [comment]
For clarification @tmcconechy

**Comment by tmcconechy** [comment]
@jbrcna this is by design, in smaller views the whole month wont fit so we show the smaller date format

**Comment by jbrcna** [comment]
thank for clarifying @tmcconechy , @ericangeles
