### ISSUE TITLE
Datagrid: Changing a colorpicker from none to a color does not make the cell dirty

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6893]
**Describe the bug**
On an editable datagrid that has dirty indicators, when changing a colorpicker with no color specified to a different color there is no dirty indicator added to the cell.

**To Reproduce**
1. Add datagrid setting showDirty: true and change the color of a colorpicker to an empty string on http://localhost:4000/components/datagrid/test-editable-colorpicker.html
2. Go to http://localhost:4000/components/datagrid/test-editable-colorpicker.html
3. Change the colorpicker from none to a color
4. See that there is no dirty indicator on the cell

**Expected behavior**
It is expected that when changing a colorpicker's color, the dirty indicator is added to the cell.

**Version**
- ids-enterprise: v4.68.0-dev

**Screenshots**
![none to color colorpicker no dirty indicator](https://user-images.githubusercontent.com/76002134/195696068-a355216b-a816-4973-beea-0f08031c0cfc.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 106.0.5249.119 (Official Build) (64-bit)

**Comment by glenlieorillo** [comment]
Tested and passed. Moving this ticket to Done.

https://user-images.githubusercontent.com/102151352/210507736-415d8206-ca43-4361-afd2-26554a32b504.mov
