### ISSUE TITLE
Toolbarsearchfield: inside CAP x icon misaligned in mobile view

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6894]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-inside-contextual-panel.html
2. swtich to mobile view or open min mobile device
3. click button to open cap
4. click searchfield icon
5. See error

**Expected behavior**
should be properly aligned

**Version**

- ids-enterprise: v4.69.0-dev

**Screenshots**
<img width="234" alt="image" src="https://user-images.githubusercontent.com/56722184/195767392-878987b2-3616-465a-bedd-b89fab7aadd9.png">

**Platform**
mobile

**Additional context**

**Comment by ericangeles** [comment]
Duplicate issue https://github.com/infor-design/enterprise/issues/6857 closing this one now.
