### ISSUE TITLE
Gantt Charts

### ISSUE THREAD

**Issue by kimanderssonm3cs** [infor-design/enterprise#6895]
**Is your feature request related to a problem or use case? Please describe.**
Production planning in M3 is a vital process for alot of customers, currently you'd have to work in a bit of a "messy" M3 environment to achieve your goals.

**Describe the solution you'd like**
Implement a Gantt Chart component 

**Describe alternatives you've considered**
I have looked into https://dhtmlx.com/docs/products/dhtmlxGantt/ which both looks good and works good, but I would obviously appreciate a native component in IDS

**Additional context**
Grouping, Coloring, Events for drag-n-drop and other features that might be applicable for this type of component.

**Comment by ericangeles** [comment]
@kimanderssonm3cs I believe we have plan for the gantt chart component request. Any additional information @tmcconechy @danielortiz1982 @inforandy?

**Comment by tmcconechy** [comment]
yes this is the design and issue: https://github.com/infor-design/enterprise-wc/issues/889 we are currently finalizing the design. Watch that issue for updates and contribute there please. Sounds like what you would want
