### ISSUE TITLE
Datagrid: Time filter doesn't take effect when clicking 'Set Time' button

### ISSUE THREAD

**Issue by ccai2021** [infor-design/enterprise#6896]
**Describe the bug**
The filter does not take effect until I type 'enter'. It can't take effect immediately after I click the 'Set Time' button

**To Reproduce**

https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-time.html.
1. Click on the clock icon on the time filter `Time 24`, set the time to 0400, then click 'Set Time' button
2. The data in the Datagrid is not changed.

**Expected behavior**
The result is changed after clicking  'Set Time' button.

**Version**
- ids-enterprise: 7.7.1

**Screenshots**
Set the time to 0400, click 'Set Time' button
![image](https://user-images.githubusercontent.com/93892306/195861180-d810a33e-2b35-4d49-ad2c-470fd417268f.png)
The filter does not take effect
![image](https://user-images.githubusercontent.com/93892306/195861271-b5f9acb7-c641-4bc0-abcf-8118e43afef2.png)
The filter takes effect after I type enter
![image](https://user-images.githubusercontent.com/93892306/195861399-ea0bd3f6-e66d-460c-89a2-e1e6e80d9079.png)

**Platform**
 - Infor Application/Team Name: Cloverleaf SICB/Healthcare
 - Device: 
 - OS Version: Windows 11
 - Browser Name: Chrome, Edge
 - Browser Version:  106.0.5249.103

**Additional context**

**Comment by janahintal** [comment]
Seems working in https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-time.html after I set a time and then click 'Enter' after. But it's not filtering right after I set a time and didn't hit Enter key. 

![image](https://user-images.githubusercontent.com/45757016/201105290-4bb4e714-aaa5-4816-a622-44310c9b9717.png)
![image](https://user-images.githubusercontent.com/45757016/201107639-d174df12-118c-43b4-82e5-9310f8467c36.png)

**Comment by tmcconechy** [comment]
@corpulent can you see why this didnt deploy? It is working locally but not present on the deploy site
