### ISSUE TITLE
Field Filter: dropdown filter looks off in Firefox

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6897]
**Describe the bug**
Dropdown filter looks off in Firefox.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-filter/example-datepicker.html, https://main-enterprise.demo.design.infor.com/components/field-filter/example-filtertype.html, https://main-enterprise.demo.design.infor.com/components/field-filter/example-index.html in Firefox
2. Click on dropdown filter
3. See error

**Expected behavior**
Dropdown filter should be rendered properly in Firefox.

**Version**

- ids-enterprise: 4.68.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/102151352/196085323-0af3e60b-8be6-4223-9ca9-34ae610dd94f.png)

**Platform**
 - Mozilla Firefox

**Comment by tmcconechy** [comment]
Closing out older issues / field filter isnt getting much fixes
