### ISSUE TITLE
Toolbar: missing input field

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6899]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar/example-toolbar-input.html?theme=classic&mode=light
2. See error
3. Notice that the input field is missing

**Expected behavior**
input field should be displayed

**Version**

- ids-enterprise: v4.69.0-dev

**Screenshots**
<img width="183" alt="image" src="https://user-images.githubusercontent.com/56722184/196126734-239e39ff-33c0-4483-ba20-e6c729c74ede.png">

**Platform**
android & iOS

**Additional context**

**Comment by tmcconechy** [comment]
Descoping this. Issue has been raised in other ways and this has changed since
