### ISSUE TITLE
Update theme switching to use ids-identity as a source

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#690]
**Is your feature request related to a problem? Please describe.**
We already have an existing theme switcher in Enterprise, we just need to switch the source to pull the themes from `ids-identity`

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
Once all is linked properly, you might not see much change and this is expected. The original 3 themes (light/dark/high-contrast) should look identical to the previous setup and the uplift theme is at most, 10% done/implemented.

**Comment by tmcconechy** [comment]
PRing this but noting some problems that will need addressing.

- the color changes are not represented in charts or the color palette page unless we do something
- token $button-height is not used
- ep variable $menubutton-height is not used
- token $button-line-height is not used
- token $button-font-weight is not used

Changes so far
- input background color
- checkbox/radio color
- button height (not mapped)
- color palette (not mapped)

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/input/example-index.html
http://master-enterprise.demo.design.infor.com/components/checkboxes/example-index.html
Passed QA testing, input and checkboxes look good on Uplift theme.
