### ISSUE TITLE
Keyboard shortcut 't' is not working in Date fields

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#6901]
**Describe the bug**
Keyboard shortcut 't' is not working in Date fields

**To Reproduce**

https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
2. Put focus on Order Date Column
3. Type 't' on Order Date filter
4. Nothing happens, we used to be able to type "t" and the field is populated with today's date, noticed once the date picker is displayed, typing "t" selects today's date. 

**Expected behavior**
Being able to type "t" in a date field and field value is populated with today's date.

**Version**

- ids-enterprise: 4,67.2

**Screenshots**

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: Version 106.0.5249.61 (Official Build) (64-bit)

**Additional context**
Last working version: 4.64.6

**Comment by tmcconechy** [comment]
Remember this is now a setting that defaults to false because its non-standard. See: https://github.com/infor-design/enterprise/blob/main/docs/CHANGELOG.md#v4670-important-notes so maybe you need to add this t get it to work:

```
editorOptions: { todayWithKeyboard: true }
```

**Comment by vonnyw** [comment]
Thanks Tim, so this is a breaking change in IDS 4.67. Let us try setting the option to true.

**Comment by tmcconechy** [comment]
Yeah it must be the same breaking change - give it a try

**Comment by vonnyw** [comment]
Please close this ticket, setting the "todayWithKeyboard" setting to true resolved the issue. Thanks!
