### ISSUE TITLE
Tabs:  Ability to add title in New Tab

### ISSUE THREAD

**Issue by ryanChrstn** [infor-design/enterprise#6902]
**Is your feature request related to a problem or use case? Please describe.**
Tabs: Add an option in the New Tab button to add a title.

**Describe the solution you'd like**
New Tab in the Tab component would be better if there's also a title being displayed on the button. Same with the other tabs.

**Describe alternatives you've considered**
If the title can be modified or supplied for translation; the display can be uniformly the same as other titles or the browser's title option.

**Additional context**
![image](https://user-images.githubusercontent.com/14357059/196324142-56af4d74-d964-4a61-ac2b-c2ead00741f9.png)

And what application do you work on? [e.g. {Infor XYZ}]
Infor Lawson (LSF)

**Comment by jbrcna** [comment]
QA Passed. v4.70.0-dev
https://main-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/56722184/201828386-6e207e10-4861-4604-acf8-61b027ff82c8.png">
