### ISSUE TITLE
 Edit column cell value with conditional validation on DataGrid component   

### ISSUE THREAD

**Issue by ahivare** [infor-design/enterprise#6911]
Edit column cell values with conditional validation on every line of the DataGrid component  

The DataGrid component should provide editing of every row's column cell values with conditional validation. Here, first we have to capture the column cell value and then do conditional validation by using this captured value while editing. If this is true, we should succeed; otherwise, we should make an error.

e.g. We've used the "DataGrid component" in one of our widget developments, where we've made the quantity column editable. But the business requirement is such that the quantity column be editable and should be validated with a condition while editing the value. The condition is not to accept more quantity than the existing value in ordered quantity. Here we can catch/understand the existing value on each line and compare the value for data validation.

**Comment by ahivare** [comment]
Hi @tmcconechy ,yes it is an enhancement request.
Example:
so as per below image we have datagrid and the quantity column is editable, so every line there is having default ordered qty, here user can edit the ordered qty but condition while editing ordered qty is  user can not exceed/edit  value more than the default value. e.g. 1. (if qantity is 8 ,user can exceed/edit value only less than 8 not more), e.g. 2. condition (value<=8).

so for every row when we  are editing the value we have to first catch default value for comparing with editing value, and according to compared result we have to show success or fail  error on edit row column.

![image](https://user-images.githubusercontent.com/102961873/197678673-8e808cfb-96b7-48d7-807d-b3c4b3d6d876.png)

**Comment by tmcconechy** [comment]
This isnt the type of enhancement we would do as its app specific. But i think what you want to do as add validation to that cell. This example shows custom validation:

https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-validation.html
- Edit the product id cell.

You would just want to add the logic for the use case in a custom validation function https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/test-editable-validation.html#L29 

then add it to validate no the column https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/test-editable-validation.html#L63

**Comment by ahivare** [comment]
Okay @tmcconechy ,I already given try on this but will check on you pasted example.

Thanks.
