### ISSUE TITLE
d3-color vulnerable to ReDoS

### ISSUE THREAD

**Issue by swuendri** [infor-design/enterprise#6912]
**Describe the bug**
The project uses version 5.16.0 of package d3. D3 has a dependency to d3-color which has a reported security issue since several weeks. This breaks the audit of our M3 H5 application.

**To Reproduce**
Run npm audit.

1. git clone https://github.com/infor-design/enterprise.git
2. cd enterprise
3. npm audit --production
4. Output: 
```
found 4 high severity vulnerabilities in 39 scanned packages
  4 vulnerabilities require semver-major dependency updates.
```

**Expected behavior**
npm returns with exit code 0, means no important vulnerabilities were found.

**Version**
- ids-enterprise: 4.58.3 and higher (but I haven't checked earlier versions)

**Screenshots**
not necessary

**Platform**
not platform specific 

**Additional context**
I couldn't find a way to add something to the https://github.com/infor-design/enterprise/security/advisories.

**Comment by tmcconechy** [comment]
This is being worked on https://github.com/infor-design/enterprise/pull/6731 we will update all dependencies to their latest there. But its a big task.

**Comment by swuendri** [comment]
I'm not sure how, but if you see a possibility that I can help @tmcconechy , please let me know.

**Comment by tmcconechy** [comment]
No we should be able to handle this. Just not sure which version it will be in
