### ISSUE TITLE
Dropdown: Cannot read properties of null (reading 'find') using virtual keyboard

### ISSUE THREAD

**Issue by AT-Infor** [infor-design/enterprise#6916]
**Describe the bug**
If you use a virtual keyboard when entering characters into a dropdown box it causes the following error:
"dropdown.js:1795 Uncaught TypeError: Cannot read properties of null (reading 'find')  at dropdown.js:1795:21"

**To Reproduce**

Step up:
Add the Chines language pack to your PC.

![image](https://user-images.githubusercontent.com/88100277/197785994-9c839731-7ed0-4c1a-8d55-35d011436191.png)

Please see [here for more details](https://support.microsoft.com/en-us/windows/manage-the-input-and-display-language-settings-in-windows-12a10cb4-8626-9b77-0ccb-5013e0c7c7a2#:~:text=if%20it%27s%20available)

1. Go to https://design.infor.com/code/ids-enterprise/latest/dropdown
2. Open DevTools (F12)
3. Change the keyboard layout to be Chines.
4. In the dropdown box type in the first letter of the item you're searching for and select it.
5. Check the console log for the error.

Please see the zip file for action for click by click action steps taken:
[Replicate Steps.zip](https://github.com/infor-design/enterprise/files/9860603/Replicate.Steps.zip)

**Expected behavior**
This should work for all languages. 

**Version**
- ids-enterprise: 4.68 (Latest)

**Platform**
 - Infor Application/Team Name: Infor SunSysyems
 - OS Version: Windows 11 Enterprise
 - Browser Name: Chrome,
 - Browser Version: Version 106.0.5249.119 (Official Build) (64-bit)

**Additional context**
Consoles Log:
[design.infor.com-Dropdown-Box.log](https://github.com/infor-design/enterprise/files/9860333/design.infor.com-Dropdown-Box.log)

**Comment by tmcconechy** [comment]
I tried this on mac as thats what i have and could not reproduce. Any idea which of these it would be using?

![Screen Shot 2022-10-25 at 10 02 34 AM](https://user-images.githubusercontent.com/814283/197795049-2fda8363-5feb-450b-96fa-bda50289888e.png)

Also do you know if its a virtual keyboard issue or actually reported by chinese users?

**Comment by AT-Infor** [comment]
Originally it was reported by a Chinese user but I'm able to replicate this issue on my machine (Windows 11). It's set to Pinyin.
I don't have access to a Mac for testing.

**Comment by tmcconechy** [comment]
@jdilag90 would you be able give this a test on a pc?

**Comment by AT-Infor** [comment]
Please see attached video:

https://user-images.githubusercontent.com/88100277/198081640-937504c8-1d6b-4767-bdc7-4ce512007085.mp4

**Comment by AT-Infor** [comment]
Hello @tmcconechy , were you able to follow those steps, if you need anything else please say?

**Comment by tmcconechy** [comment]
I wasn't because i dont use a PC. But passing to the team which can test on PC. We'll look and i dont think we need anything as of now.
