### ISSUE TITLE
Datagrid: Datepicker is not shown on datagrid filter in Safari

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6917]
**Describe the bug**
Datepicker icons are not shown in date column filters when in a Safari browser.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/test-editable-datetime.html
2. See that the date column filters are missing datepicker icons

**Expected behavior**
It is expected that datepicker icons appear in the date column filters.

**Version**
- ids-enterprise: v4.68.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/76002134/197831301-159932f9-8c90-428d-8a12-6b8aebae5709.png)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: macOS Big Sur
 - Browser Name: safari
 - Browser Version: Version 14.1.2

**Additional context**
This broke in v4.56.0

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-datetime.html. Thanks!
![image](https://user-images.githubusercontent.com/45757016/201658761-af45aaf8-fdf2-4da7-b2c8-3a78d7eb0624.png)
