### ISSUE TITLE
Checkbox Component. Dirty tracker not appearing on high contrast

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#692]
**Describe the bug**
[All Browsers] Checkbox Component. Dirty tracker not appearing on high contrast on "Option 3".

**To Reproduce**
1. Go to url: http://4100-beta1-enterprise.demo.design.infor.com/components/checkboxes/example-horizontal.html
2. Click on the menu and select "High Contrast'
3. Click on "Option 3"
4. The dirty tracker is not appearing. 

**Expected behavior**
The dirty tracker should appear on all three themes

**Screenshots**

![checkbox tracker_2](https://user-images.githubusercontent.com/39101346/44743783-6db0f300-aad1-11e8-964e-482f2073d178.png)

![checkbox _1](https://user-images.githubusercontent.com/39101346/44743839-920ccf80-aad1-11e8-9b13-1893d0edfb6b.png)

**Platform**
- All Browsers

**Additional context**
None

**Comment by tmcconechy** [comment]
Looks like this needs zindex and a but of adjustment on top/left as well.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/checkboxes/example-horizontal.html
Passed QA testing, bug fix is verified working across all browsers.
