### ISSUE TITLE
Datagrid: Undefined tooltip when headerIconTooltip setting is not defined

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6929]
**Describe the bug**
When the column setting headerIconTooltip is not included on a column with a header icon and the icon is hovered, the tooltip is shown as undefined.

If I want a header icon to not have a tooltip I need to include the column's headerIconTooltip setting and set it to an empty string. Instead, could it be possible to only use the headerIconTooltip setting if a tooltip is needed?

**To Reproduce**
1. Remove the headerIconTooltip setting from the 'productName' column in http://localhost:4000/components/datagrid/example-header-icon-with-tooltip.html
2. Go to http://localhost:4000/components/datagrid/example-header-icon-with-tooltip.html
3. Hover over the icon on the Product Name column header
4. See that the tooltip is shown as undefined

**Expected behavior**
If the headerIconTooltip setting is not included on a column with a header icon, upon hovering over the icon there should not be a tooltip.

**Version**
- ids-enterprise: v4.68.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/76002134/198306723-f21e4556-f34f-4cbb-b229-e4ea7dd1130a.png)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 107.0.5304.63 (Official Build) (64-bit)

**Comment by jbrcna** [comment]
QA Passed.
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/56722184/228431636-74d07281-c0b7-4889-872d-7df4ae60c880.png">
