### ISSUE TITLE
Datepicker: Range display in RTL (regression)

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#6933]
**Describe the bug**
Datepicker Range display in RTL is malformed since version 4.6x.x (was OK in 4.60.0)

**To Reproduce**

1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-range.html?locale=he-IL](https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-range.html?locale=he-IL)
2. Click on one of the calendar icons
3. Select a range
4. Click again on the calendar icon and see display
5. Go to version 4.60.0 [https://design.infor.com/code/ids-enterprise/4.60.0/demo/components/datepicker/example-range.html?locale=he-IL](https://design.infor.com/code/ids-enterprise/4.60.0/demo/components/datepicker/example-range.html?locale=he-IL)
6. repeat step 2

**Expected behavior**
Should behave as LTR or version 4.60.0

**Version**

- ids-enterprise: v.4.68.0

**Screenshots**
### Latest:
![image](https://user-images.githubusercontent.com/34129313/198965653-e84bb8ce-d939-4257-9e12-e6647006e3eb.png)

### Version 4.60.0:
![image](https://user-images.githubusercontent.com/34129313/198965459-cfb2581c-06c5-4d4c-a640-765f01c77264.png)

**Platform**

 - OS Version: Windows 10
 - Browser Name: Chrome/Firefox
 - Browser Version: Latest

**Additional context**
Thanks!

**Comment by jbrcna** [comment]
QA Passed
https://main-enterprise.demo.design.infor.com/components/datepicker/example-range.html?locale=he-IL
<img width="515" alt="image" src="https://user-images.githubusercontent.com/56722184/210480798-05df52a2-411d-4576-88a7-0c4d74f3a281.png">

https://main-enterprise.demo.design.infor.com/components/datepicker/example-range.html
<img width="431" alt="image" src="https://user-images.githubusercontent.com/56722184/210480916-1c664433-34ef-4401-80cd-23a10342e424.png">
