### ISSUE TITLE
Datagrid: dirty cell indicator is not being cleared with frozen columns when using clearDirtyRow

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#6952]
**Describe the bug**
The dirty cell indicator is not being removed from all cells of a datagrid row when using frozen columns.  The dirty cell indicator is only being cleared from the frozen columns and not the remaining columns on the row.  This is working fine when frozen columns are not in play.  

**To Reproduce**

1. Go to 'test-addrow-with-frozen-columns.html'
2. Click on 'Add Row'
3. Enter new values for each of the columns in the new row
4. Notice the dirty indicator on each cell
5. Click on 'Save and New'
6. Notice the dirty cell indicator is only cleared from the frozen column

**Expected behavior**
Dirty cell indicator is cleared from all cells on the row and not just the frozen columns.

**Version**

- ids-enterprise: v4.70.0-dev

**Additional context**
Landmark is currently on v4.68

**Comment by claudenbach** [comment]
![Git-6952](https://user-images.githubusercontent.com/39804038/200684038-83573501-9927-4ba5-a86d-6f1309c6ee6b.gif)

**Comment by tmcconechy** [comment]
@ericangeles can you guys take a look. This regressed and is needed by Landmark on 4.67.x when done

**Comment by claudenbach** [comment]
I've also noticed that the method clearRowError() is not removing the corner black hash on the selectCheckbox cell.  Using the example 'test-addrow-with-frozen-columns.html', this was last working correctly in v4.64.6.

**Comment by claudenbach** [comment]
Illustration of the issue in v4.70.0...

![ClearingRowError-4 70 0](https://user-images.githubusercontent.com/39804038/201220862-f8917b59-7087-4d07-82fa-693040ac6e72.gif)

**Comment by claudenbach** [comment]
Illustration of it last working in v4.64.6...

![ClearingRowError-4 64 6](https://user-images.githubusercontent.com/39804038/201220994-5a9f87c7-4430-40d9-8bbf-7127db11072e.gif)

**Comment by janahintal** [comment]
QA Passed. Verified working in 
![image](https://user-images.githubusercohttps://main-enterprise.demo.design.infor.com/components/datagrid/test-addrow-with-frozen-columns.html?theme=classic&mode=light&colors=2578a9 
ntent.com/45757016/201329653-e5eb15f1-d486-4b42-a3b4-18d4edc9ea1c.png)

**Comment by ericangeles** [comment]
@tjamesallen15 can you check the `clearRowError()`?

**Comment by tmcconechy** [comment]
@tjamesallen15 looks like we missed the bug mentioned on the comment added later https://github.com/infor-design/enterprise/issues/6952#issuecomment-1310989491

Can you take a look and make an additional fix? Higher priority as it needs a patch. Thanks!

**Comment by tjamesallen15** [comment]
> @tjamesallen15 looks like we missed the bug mentioned on the comment added later [#6952 (comment)](https://github.com/infor-design/enterprise/issues/6952#issuecomment-1310989491)
> 
> Can you take a look and make an additional fix? Higher priority as it needs a patch. Thanks!

will do

**Comment by tjamesallen15** [comment]
Hello @tmcconechy  @ericangeles ,

Please a take look at this video below. I cant reproduce it. I followed the steps from the comment.
https://user-images.githubusercontent.com/34049950/202593410-e0b5c275-92fa-4f10-88fe-bac62d4b2a1d.mp4

**Comment by tmcconechy** [comment]
@claudenbach ?

**Comment by claudenbach** [comment]
I'm only seeing that this is still an issue in v4.68.x.  When testing with v4.70.0 it was working fine.

**Comment by claudenbach** [comment]
Testing using v4.68.1...

![Testing-v4 68 1](https://user-images.githubusercontent.com/39804038/202743651-b2e97fb9-23d9-406d-b40f-f2176a6854d4.gif)

**Comment by claudenbach** [comment]
Testing using v4.70.0...

![Testing-v4 70 0](https://user-images.githubusercontent.com/39804038/202743805-d4ea271a-f274-4dad-be02-c40eecead0aa.gif)

**Comment by tmcconechy** [comment]
@tjamesallen15 can you check 4.68.x and push a fix to that branch? thanks!

**Comment by janahintal** [comment]
This is now working as expected in https://main-enterprise.demo.design.infor.com/components/datagrid/test-addrow-with-frozen-columns.html. Thanks
![image](https://user-images.githubusercontent.com/45757016/205099265-5ac9aefd-a176-4007-b829-4426ccb45c5b.png)
