### ISSUE TITLE
Sinkpage: Process Indicator - Icons: line overlaps with the icons

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#6953]
**Describe the bug**
The line overlaps with the icons in Classic Version.

**To Reproduce**

1. Go to https://4690-beta0-enterprise.demo.design.infor.com/?theme=classic&mode=light&colors=2578a9
2. Scroll down to Process Indicator - Icons

**Expected behavior**
Line should not overlap with the icons.

**Version**

- ids-enterprise: 4.69.0-beta.0

**Screenshots**
_Current:_
![image](https://user-images.githubusercontent.com/102151352/200824090-d6be27d9-bf15-4a08-99cb-64fe0fcc3b36.png)

![image](https://user-images.githubusercontent.com/102151352/200825994-64c7a073-b1a7-48e6-8fd9-a5da1cf493f4.png)

_Older Version:_ 
https://4680-beta0-enterprise.demo.design.infor.com/?theme=classic&mode=light&colors=2578a9
![image](https://user-images.githubusercontent.com/102151352/200824488-0b18c0f6-b0e6-418b-829b-f163c2e494c1.png)

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
No longer seems valid on https://main-enterprise.demo.design.infor.com/?theme=classic&mode=light&colors=default
