### ISSUE TITLE
Modal: Whitespace on the right side of a datagrid on Firefox

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#6956]
**Describe the bug**
In the Firefox browser, when a modal with a datagrid is opened there is some whitespace next to the last column in the datagrid.

**To Reproduce**
1. Go to http://localhost:4000/components/modal/test-modal-datagrid-title-overlap.html in Firefox
2. Click on Open Modal button
3. See that there is whitespace on the right side of the datagrid

**Expected behavior**
The columns should fill the entire datagrid.

**Version**
- ids-enterprise: v4.67.4

**Screenshots**
![image](https://user-images.githubusercontent.com/76002134/200921002-9436a878-c845-41a7-84ff-17fa247fdbd6.png)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: firefox
 - Browser Version: 107.0b9 (32-bit)

**Comment by tmcconechy** [comment]
Can you set the column widths?

**Comment by s-werking** [comment]
Yes, we have been extending the length of columns to temporarily fix the issue but the modal looks better when columns are sized automatically according to the size of the text in the columns.
