### ISSUE TITLE
Need to remove the go-back arrow in a SPA context

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#696]
**Describe the solution you'd like**
Back button does not go away when navigating to a new page in a single page application. Need a way to manually dismiss this and go back to the hamburger menu button.

**Additional context**
![go-back](https://user-images.githubusercontent.com/1056684/44747753-87533a00-aad3-11e8-9ddf-5f0db67e6619.png)

**Comment by tmcconechy** [comment]
Fix was added thanks for that.
