### ISSUE TITLE
Sinkpage: Searchfield x icon is not centered when focused/highlighted

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#6961]
**Describe the bug**
when using `chrome` and/or `edge`, Searchfield x icon is not centered when focused/highlighted

**To Reproduce**

1. Go to https://4690-beta0-enterprise.demo.design.infor.com
2. Find Searchfield
3. Type a text
4. Press tab key to focus on x icon
5.  See error

**Expected behavior**
should be centered
<img width="415" alt="image" src="https://user-images.githubusercontent.com/56722184/201012993-221757ef-d209-4e43-a549-55e35199d2a3.png">

**Version**

- ids-enterprise: v4.69.0-beta0

**Screenshots**
<img width="415" alt="image" src="https://user-images.githubusercontent.com/56722184/201012925-efa8aa3d-4c92-47df-a1d4-6d00e0fb103f.png">

**Platform**
EDGE & Chrome

**Additional context**

**Comment by jbrcna** [comment]
x icon is now centered. highlight is also now a rounded square.
verified in https://main-enterprise.demo.design.infor.com
<img width="388" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/d2d90587-4ee4-4fc2-a0b1-2359256b2beb">

**Comment by tmcconechy** [comment]
OK lets close as it seems ok?
