### ISSUE TITLE
Date cell is still in edit state even after selecting a date from date picker calendar 

### ISSUE THREAD

**Issue by hsubtain** [infor-design/enterprise#6963]
**Describe the bug**
[SAFARI] Date cell is still in edit state even after selecting a date from date picker calendar, need to click Enter again to exit edit state of cell.

**To Reproduce**
 I was able to reproduce the behavior in Safari only, it was working as expected in Mozilla, Google Chrome, and Edge where after selecting a date from calendar edit state is exited.

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-datetime.html
2. Click on product id cell
3. Navigate to order date 2 cell by pressing right arrow key
4. Click enter on order date 2 cell
5. Press arrow down
6. Select date in calendar by pressing enter

Actual Result: Cell date is still in edit Mode.

**Expected behavior**
Cell date shouldn't be in edit state after selecting from calendar.

**Version**
ids-enterprise: 4.70.0-dev

**Screenshots**
![date_cell_still_in_edit_state_after_selecting_from_calendar](https://user-images.githubusercontent.com/100820299/201017109-6d844e74-a0cc-42c7-a9ae-32c5eb553393.gif)

**Platform**
- Infor Application/Team Name: Lawson System Foundation (Portal Team)
- Safari 15.6.1 (17613.3.9.1.15)

**Comment by hsubtain** [comment]
Hi @tmcconechy, I would just like to ask a possible delivery date for the fix? Thank you!

**Comment by tjamesallen15** [comment]
Hello, correct me if I'm wrong but this is not reproducible on my end. Video below. 
cc @tmcconechy  @ericangeles  @hsubtain 

https://user-images.githubusercontent.com/34049950/208367222-7138293c-92fb-4abb-ab40-1f14d0eff9d4.mp4

**Comment by hsubtain** [comment]
Hi @tjamesallen15 Have you tried replicating it in Safari? We were able to replicate the issue in Safari 15.6.1

**Comment by hsubtain** [comment]
> Hello, correct me if I'm wrong but this is not reproducible on my end. Video below. cc @tmcconechy @ericangeles @hsubtain
> 
>  6963.mp4


Hi @tjamesallen15 Have you tried replicating it in Safari? We were able to replicate the issue in Safari 15.6.1

**Comment by glenlieorillo** [comment]
QA tested and passed.

**Safari**

https://user-images.githubusercontent.com/102151352/209893540-775c65e7-b2c8-4306-91f4-226c33eb0cec.mov




**Chrome**

https://user-images.githubusercontent.com/102151352/209893498-f84073b6-7c48-40dc-a049-0a6801fd5ba8.mov
