### ISSUE TITLE
fileupload-advanced: HTML rendered from file name

### ISSUE THREAD

**Issue by darinw** [infor-design/enterprise#6970]
**Describe the bug**
If a file is added to the fileupload-advanced component with something like `<img scr=z onerror=alert(2);>.py` it will append the image to the DOM. 

[fileupload-advanced L361](https://github.com/infor-design/enterprise/blob/1a0dc8e3614324c03cc46c1c7daddc0b413c98c5/src/components/fileupload-advanced/fileupload-advanced.js#L361)

Related Jira: https://jira.infor.com/browse/IONDEV-62076

**Expected behavior**
the file name should be present in the not the element

![image](https://user-images.githubusercontent.com/92472/201991473-eed5bb6f-3484-41ea-bc93-fae047c1d6f6.png)

**Additional context**
There are a few other areas where similar issues exist. 
[emptymessage L75](https://github.com/infor-design/enterprise/blob/1a0dc8e3614324c03cc46c1c7daddc0b413c98c5/src/components/emptymessage/emptymessage.js#L75)
[emptymessage L79](https://github.com/infor-design/enterprise/blob/1a0dc8e3614324c03cc46c1c7daddc0b413c98c5/src/components/emptymessage/emptymessage.js#L79)

**Comment by tmcconechy** [comment]
@ericangeles can you fit this one in?

**Comment by ericangeles** [comment]
@tmcconechy for sure

**Comment by marnix** [comment]
Asking for a colleague: Is there any way to work around this issue on the adopting side, without having to wait for a release that contains this fix?  Thanks!

**Comment by tmcconechy** [comment]
i cant seem to reproduce it to try for a workaround. When i go to https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html and upload a file of that name. It is all good.

It really looks like from the screen shot its just a missing image? Do you use CSP? (this could be an option or maybe its a CSP error)

Also i dont have access to the Jira to see further details

**Comment by tjamesallen15** [comment]
I'm using Windows PC and Mac to test this and I cannot reproduce it.
![image](https://user-images.githubusercontent.com/34049950/202975373-dee672e7-c49a-420d-9279-7b4817354ec2.png)
![image](https://user-images.githubusercontent.com/34049950/202975420-ccb628b7-0415-4f0c-96b5-affe26e8ffb3.png)

cc @tmcconechy @ericangeles

**Comment by tmcconechy** [comment]
@darinw / @marnix ? No one can reproduce this. Did you try the latest version? Or maybe the issue is on your end?

**Comment by darinw** [comment]
I will reach out to see how they were able to create a file with `<img scr=z onerror=alert(2);>.py` it seems to remove the < and >

**Comment by tmcconechy** [comment]
No one seems to be able to reproduce.
