### ISSUE TITLE
Secondary Button: Change from Slate to Solid with Border

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6977]
**Describe the bug**
Based on feedback would like to change the secondary button to a blue border to a slate button.

- Classic Leave it
- Dark =- TBD
- Contrast - darker azure like the primary

**Expected behavior**

**Screenshots**
See Designs link https://www.figma.com/file/VcRDGPFqlp3MJ46mEWkGPf/Buttons?node-id=701%3A1222&t=2eRdbDDXoBLYCBwt-1

**Implementation Details**

- all button styles change to this new style
- updates can seen no https://main-enterprise.demo.design.infor.com/components/button/example-index.html?colors=7928E1 go across the examples
- personalization color changes the border
- use a class for destructive action button and show it and show it on https://main-enterprise.demo.design.infor.com/components/button/example-index.html?colors=7928E1

**Comment by jbrcna** [comment]
QA failed.
`disabled primary button` text is hard to read in `Amethyst`, `Azure`, `Grapihite` using high contrast. observe in light and dark mode. 
<img width="326" alt="image" src="https://user-images.githubusercontent.com/56722184/209770190-a1d17e6c-2c61-460f-b49a-9f83bcd1ff35.png">
<img width="307" alt="image" src="https://user-images.githubusercontent.com/56722184/209770226-f35e6aa9-2191-4bda-bf93-30a73a0bb85b.png">
<img width="268" alt="image" src="https://user-images.githubusercontent.com/56722184/209770276-6b027310-2d8e-4de5-a1d5-ee7bfad83073.png">

**Comment by tmcconechy** [comment]
@tjamesallen15 @ericangeles I see this as well. I think we just need to adjust the css in personalize-styles.js for the new buttons it should get the colors and look readable.

**Comment by ericangeles** [comment]
@tjamesallen15 please check at this too.

**Comment by janahintal** [comment]
Hi Team, some buttons still not that visible/readable in Dark mode. 

Dark mode amethyst 
![image](https://user-images.githubusercontent.com/45757016/211303619-21ef129e-6ae2-4a54-a0f4-b1bcdbbdf802.png)

Dark mode Graphite 
![image](https://user-images.githubusercontent.com/45757016/211303788-a4b8e43d-e88b-417f-83ca-64943b7abf5a.png)

Thanks, 
Janah

**Comment by ericangeles** [comment]
@tmcconechy yes please

**Comment by tmcconechy** [comment]
@janahintal can you make a new issue for that? @ericangeles we might want to try to include it asap

**Comment by janahintal** [comment]
Hi Tim, created another issue for Dark Mode visibility. Will move this to done as the buttons are now visible in Light and High contrast mode. Thanks!
