### ISSUE TITLE
Tabs: Add White Background (as Default)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6979]
**Is your feature request related to a problem or use case? Please describe.**
Make the tabs header white like #6978 

**Describe the solution you'd like**
- change https://main-enterprise.demo.design.infor.com/components/tabs-header/example-alternate.html to the default
- will be some changes like hover state 
- https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html is still possible but white is recommend.
- dark stays same - applied on high contrast and light (new theme only)

**Additional context**
Will be needed on web components as well - To be discussed

Design: Tabs: https://www.figma.com/file/0VaVCeINhJjxvISUQrHq2D/Tabs?node-id=1504%3A725&t=DX2f4VPERUDc8AN6-1 

**Implementation**
- Working on Example For Changes https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html
- example should get a theme switch https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html
- default is now this new design
- all other colors work as is
- other tab ideas like alternate: stays as is no matter the setting
- current tabs https://main-enterprise.demo.design.infor.com/components/tabs/example-index.html will get new styling to match (lower priority can do later)
~- Idea for setting: `backgroundColor: light/dark` (default stays as is) `appearance` - if needed (dont think it will be)~

**Comment by glenlieorillo** [comment]
Changes already applied. However, if the user changes the color header, the tabs are unreadable.

https://user-images.githubusercontent.com/102151352/209741443-1451129c-3fd1-4778-b388-369abab36b18.mov

![image](https://user-images.githubusercontent.com/102151352/209741531-f7c00c5d-e35c-4374-96b0-8438c630a7e8.png)

**Comment by tmcconechy** [comment]
@glenlieorillo we also found this and fixed it on another PR thats not yet merged https://github.com/infor-design/enterprise/pull/7050

**Comment by glenlieorillo** [comment]
Passed. Moving this ticket to Done.

![image](https://user-images.githubusercontent.com/102151352/211461912-45c52a1c-4db5-4d2a-9a2f-b0c7cd7e57cd.png)
