### ISSUE TITLE
Searchfield: Searchfield styling issues in RTL

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#6982]
**Describe the bug**

Searchfield UI looks off in RTL.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/searchfield/example-buttons.html?locale=ar-EG
2. Looking at the Searchfield, there's a bunch of issues in terms of the UI including
    - searchfield input doesn't have borders
    - search icon position
    - when search is active the border is incorrect
    - close icon overlaps in the search icon when typing
    - custom icon (bar code) is in the edge of the input field
3. Check it also in Classic. Looks terrible there. Should fix that too.

**Expected behavior**
It should fix all the issues mentioned above.

**Version**
-  IDS-Enterprise: [v4.66.0]

**Comment by ericangeles** [comment]
A couple of UI issues in here. Let's put this back in the backlog.

**Comment by tmcconechy** [comment]
Closing stale issues
