### ISSUE TITLE
Tabs: regression from#6068 #6464

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#6992]
Please refer to: https://github.com/infor-design/enterprise/issues/6464

Failed retest (test environment: Landmark MT. Testing in ar).

Focus on the tabs, the outline isn't aligned for **long** tab names.

Screenshots attached.

![Fixed](https://user-images.githubusercontent.com/66057969/203518039-cbddced4-c57a-4252-92aa-a7bdb596c0c6.png)

![NOT Fixed -Administration Console-Analytics-Data Access Cube Management](https://user-images.githubusercontent.com/66057969/203518041-7d3ce922-40c1-46cc-97fa-3fc4ca98b270.png)

![NOT Fixed -Configuration Console-Change Management-LPL Version Analysis-All Versions](https://user-images.githubusercontent.com/66057969/203518042-059d0f19-65c3-436c-abcb-2318732c3d19.png)

**Comment by tmcconechy** [comment]
Any way to get a landmark dev to add an example that shows the issue? Can you reproduce in any examples...

**Comment by cpinatel7** [comment]
3 screenshots are already attached (1 showing that the fix works for short tab names and 2 Landmark screenshots showing that long tab names are not displayed correctly). What else do you need? Thanks

**Comment by tmcconechy** [comment]
Since we dont run landmark itself usually they provide a minimal example. But we can try to put one together with the example data (but wouldn't know how to type the arabic). If possible take the relavent example from the repo and put your data in it and see it shows the issue. Then attach.

**Comment by cpinatel7** [comment]
You don't need to type anything in Arabic.

Example (already included in the provided screenshots):

![image](https://user-images.githubusercontent.com/66057969/203592876-e139c381-7b9c-443d-9e08-5c515ec2ba7e.png)

**Comment by tmcconechy** [comment]
Right but we have no way to run that. I can only run these pages https://main-enterprise.demo.design.infor.com/components/tabs-module (we dont work on the Landmark team directly).

cc @claudenbach ?

**Comment by cpinatel7** [comment]
This focus issue for ar was initially raised as part of https://github.com/infor-design/enterprise/issues/6464. Issue partially fixed so new GitHub (6992) for long tab names

**Comment by tmcconechy** [comment]
ok we can try and make just a longer name - if its just that should be enough to still see it. Will let you know.

**Comment by claudenbach** [comment]
I was going to suggest trying a longer name, perhaps without spaces?

**Comment by janahintal** [comment]
QA Passed. Verified in 

- https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?theme=new&mode=light&colors=default&locale=ar-SA
- https://main-enterprise.demo.design.infor.com/components/compositeform/test-with-tab-headers-horizontal.html?locale=ar-SA
- https://main-enterprise.demo.design.infor.com/components/header/example-tabs-alternate.html?locale=ar-SA
- https://main-enterprise.demo.design.infor.com/components/header/example-tabs-alternate.html?theme=classic&mode=dark&colors=0066D4&locale=ar-SA
- https://main-enterprise.demo.design.infor.com/components/page-patterns/test-landmark-requisitions-screen.html?locale=ar-SA

Thanks!

**Comment by cpinatel7** [comment]
Thanks @janahintal 

Are you sure this issue has been fixed?

Example:
![image](https://user-images.githubusercontent.com/66057969/222440756-2ff94ca8-af40-4de5-95db-9769f2f5a94b.png)

Thank you

**Comment by tmcconechy** [comment]
@tjamesallen15 i also see it on https://main-enterprise.demo.design.infor.com/components/header/example-tabs-alternate.html?locale=ar-SA still? Just load the page and the initial focus is wrong.

**Comment by janahintal** [comment]
I can still replicate the issue on https://main-enterprise.demo.design.infor.com/components/header/example-tabs-alternate.html?locale=ar-SA upon initial load
![image](https://user-images.githubusercontent.com/45757016/223974396-5bcf727f-cc5e-4eee-919d-bba8c9ad6873.png)

**Comment by tmcconechy** [comment]
was an additional fix here https://github.com/infor-design/enterprise/pull/7295 i just merged lets retest after it uploads in a short while

**Comment by janahintal** [comment]
Hi Team, alignment is now fixed but some pages fails as the tab is not visible when in classic mode.


Classic Mode: 

- https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?theme=classic&mode=light&colors=default&locale=ar-SA 
![image](https://user-images.githubusercontent.com/45757016/224242479-2d2b34c5-db55-4057-84a3-adb1997adad4.png)

- https://main-enterprise.demo.design.infor.com/components/personalize/example-form-landmark2-horizontal.html?theme=classic&mode=light&colors=default&locale=ar-SA
![image](https://user-images.githubusercontent.com/45757016/224245017-f28f75ce-d067-401b-8917-c6c4aab4f207.png)


- https://main-enterprise.demo.design.infor.com/components/personalize/example-form-landmark.html?theme=classic&mode=light&colors=default&locale=ar-SA
![image](https://user-images.githubusercontent.com/45757016/224245142-225a786e-6492-4bb9-b1b6-c161522d350c.png)


- https://main-enterprise.demo.design.infor.com/components/personalize/example-form-landmark2.html?theme=classic&mode=light&colors=default&locale=ar-SA
![image](https://user-images.githubusercontent.com/45757016/224245241-0d5c281a-2749-430c-a3bb-25f912e2ef2d.png)

**Comment by tmcconechy** [comment]
cc @tjamesallen15 -> also when we merge please add to 4.81.x @ericangeles
