### ISSUE TITLE
Update IDS Status Colors; Green,Orange

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise#6993]
We need to update a few of our status colors

Green
OLD - #1F9254 
NEW - #2AC371

Orange
OLD.- #CD6200
NEW - #F98300

figma link for reference - https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/IDS-(SoHo)-Component-Library-v4.5?node-id=19558%3A13628&t=LJhLqVEWUDVWHzdn-0

**Comment by inforandy** [comment]
@tmcconechy let me know if we can do this in conjunction with re-adding the yellow status color for 4.71, happy to provide any further details

**Comment by tmcconechy** [comment]
Linking issue https://github.com/infor-design/enterprise/issues/6922

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
