### ISSUE TITLE
Icons: Two new icons

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#6999]
**Describe the bug**
Design added two new icons `empty-no-search-result` and `advance-settings`. Requires a new design system bump.

**Expected behavior**

**Comment by glenlieorillo** [comment]
QA tested and passed in main-enterprise however, its not reflecting in localhost.

_**main-enterprise**_
https://main-enterprise.demo.design.infor.com/components/icons/example-empty-widgets.html
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/102151352/205231328-3d386c36-5537-49a5-b441-36a5b1134acd.png">

https://main-enterprise.demo.design.infor.com/components/icons/example-index.html
![image](https://user-images.githubusercontent.com/102151352/205232056-c95490cd-1d08-4cfa-8210-bd6fa302d735.png)

**_localhost_**

http://localhost:4000/components/icons/example-index.html
<img width="703" alt="image" src="https://user-images.githubusercontent.com/102151352/205232226-a16faa22-e663-44c6-80cd-217db344bbf3.png">

http://localhost:4000/components/icons/example-empty-widgets.html
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/102151352/205232358-2f3b4d46-067a-41fb-9600-2590a6d7d733.png">

**Comment by tmcconechy** [comment]
thanks @glenlieorillo - but just a note for it to relect on local you may need too npm i again...

```
cd local-folder
rm -rf node_modules
nvm use
npm i
npm run start
```
