### ISSUE TITLE
Datagrid Paging Indeterminate: Paging controls doesn't work after initial interaction

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#700]
**Describe the bug**
[All Browsers] Datagrid Paging Indeterminate: Paging controls doesn't work after initial interaction
http://4100-beta1-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html
http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html

**To Reproduce**
1. Go to URLs above
2. Click Next Page icon or any icons in the paging control
3. Datagrid will update but the paging controls no longer work, First Page and Previous Page are disabled and nothing happens when you click Next Page and Last Page

**Expected behavior**
Paging control should work

**Screenshots**
No applicable screenshots.

**Platform**
 - All devices and browsers

**Additional context**
No additional context.

**Comment by brianjuan** [comment]
http://4100-rc0-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate.html
QA verified, bug fix is working on all browsers.

**Comment by tmcconechy** [comment]
This issue should have been closed by the PR
