### ISSUE TITLE
Icon in card formatter causes clipping issues

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#7000]
**Describe the bug**
Icons in card formatters causes clipping with adjacent text.

1. Add HTML to **_test-card-cell.html_**

```
var customFormatter = function (row, cell, value, col) {
      return `<div class="custom-card">
          <h3>${value.title}</h3>
          <dl>
            <div><dt>Location</dt><dd>${value.location}</dd></div>
            <div><dt>Phone</dt><dd>${value.phone}</dd></div>
            <div><dt>Quantity</dt><dd>${value.quantity}</dd></div>
            <div>
                <dt>
                    <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
                      <use href="#icon-alert"></use>
                    </svg>
                    Price
                </dt>
                <dd>${value.price}</dd>
            </div>
          </dl>
          <div class="toolbar card-toolbar has-more-button">
            <div class="buttonset">
              <button class="btn"><span>Order</span></button>
              <button class="btn"><span>Save</span></button>
              <button class="btn"><span>Delete</span></button>
              <button class="btn"><span>Update</span></button>
            </div>
          </div>
        </div>`;
    };
```

2. Go to http://localhost:4000/components/datagrid/test-card-cell.html
3. Select row
4. See clipping issue

**Expected behavior**

**Version**
4.70.0-dev

**Screenshots**
<img width="610" alt="image" src="https://user-images.githubusercontent.com/1056684/204633299-9cb4af34-a5f4-4e3a-b8ba-35e3c85ef6a5.png">

**Platform**
- Chrome (latest)
- Windows 11

**Additional context**
Noticed this after upgrading to 4.67
Appears to have been caused by this change 
https://github.com/infor-design/enterprise/pull/6680/commits/9e310a0cda8c83eac8897f3d06a4ed6d81b54d52

**Comment by glenlieorillo** [comment]
Icon and text (_Price_:) are misaligned.

![image](https://user-images.githubusercontent.com/102151352/209742236-45522832-2d87-4159-accb-04c57efcc4ee.png)

**Comment by ericangeles** [comment]
@tjamesallen15 can you take a look at this?

**Comment by glenlieorillo** [comment]
Passed. Moving this ticket to Done.

![image](https://user-images.githubusercontent.com/102151352/211462616-30c765ab-c52c-4f50-9f83-9dde5abb03a5.png)
