### ISSUE TITLE
field filter in modal design-glitch

### ISSUE THREAD

**Issue by rusteninfor** [infor-design/enterprise#7001]
**Describe the bug**
using a field fielfilter-wrapper component inside a modal makes for weird design-glitch

**To Reproduce**
Reproduced for you here:
https://ids-enterprise-4690-stxrtu.stackblitz.io/

Click link above, look at first field.

**Expected behavior**
First field should look like all the other fields.

**Version**
- ids-enterprise 4.69.0 

**Screenshots**
(This is from a different application, in a different setting, but same problem as in example above)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/119403809/204821853-3d3fa51d-0106-4d63-9e17-c6d15716fd62.png)

**Platform**
 - Infor Application/Team Name: M3 Portals
 - Device: PC
 - OS Version: Linux / Mac / Windows
 - Browser Name: Chrome ++
 - Browser Version: several

**Additional context**
CSS rule that causes it:
`.modal .field:first-child .audible ~ input:not(.spinbox):not(.colorpicker),`
Which sets `margin-top: 4px;`
Affects first input in a modal (Obviously, from the CSS context)

**Comment by jbrcna** [comment]
QA Passed.
https://main-enterprise.demo.design.infor.com/components/field-filter/example-index.html
<img width="500" alt="image" src="https://user-images.githubusercontent.com/56722184/223046092-3704a1db-1cd9-4594-ba3d-a57ff1eab22a.png">
