### ISSUE TITLE
Datagrid: dropdown opened from filter row is not visible / displayed

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#7006]
**Describe the bug**
When clicking on a dropdown from the filter row the dropdown is not visible.  Issue occurs when the datagrid containing the dropdown is found within a tab that is not initially selected. 

**To Reproduce**

1. Using the attached 'test-multiple-grids-in-tab-with-dropdown.html'
2. From the 'Single' tab, click on the dropdown for the Multiple Selection column
3. Notice that the dropdown is displayed
4. Click on the 'Top Bottom' tab
5. From the bottom grid, click on Filter icon from the toolbar
6. Click the dropdown for the Multiple Selection column
7. Notice that the dropdown is not displayed

**Expected behavior**
Dropdown is positioned correctly and is visible when clicking on the dropdown.

**Version**

- ids-enterprise: v4.70.0-dev and v4.68.2

**Additional context**
Maybe related to https://github.com/infor-design/enterprise/issues/6834

**Comment by claudenbach** [comment]
[Git-7006.zip](https://github.com/infor-design/enterprise/files/10155506/Git-7006.zip)

**Comment by claudenbach** [comment]
If the dropdown is not the last displayed column, opening the dropdown seems to be working correctly within the Bottom grid.

Also tested whether it matters if the filter row is already opened, it does not (meaning dropdown is not displayed).
Also tested whether it matters if a cell contains the value of 'No longer meets eligibility requirements', it does not.
Also tested whether it matters if the 'Top Bottom' tab is the selected tab, it does not.

**Comment by jbrcna** [comment]
QA Passed. moving this ticket to done
https://main-enterprise.demo.design.infor.com/components/datagrid/test-multiple-grids-in-tab-with-dropdown.html?
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/56722184/206613684-c41779db-1013-4e01-ad47-01ef0c94ef93.png">
