### ISSUE TITLE
Add click handler support for Soho image formatter in legacy Angular components.

### ISSUE THREAD

**Issue by kkulick** [infor-design/enterprise#7007]
This feature request is related to a use case.  The use case is, we have a grid with a column that displays an image (a part thumbnail image) on each line.  In our existing system built with bootstrap, the user can click on the part picture (thumbnail) on the line item, and it will open a modal popup with a larger version of the image.  Currently this does not appear possible using the existing Soho grid.

Requirements:
1. Click handler support for the image formatter.
2. The click handler should support the same parameters as the button formatter click handler supports.  This will provide the row/column clicked and the model data which we can use to determine how to open and populate the modal.

** Please note, this is required for the angular version of the components.  We are currently using version 14x.  This feature will also be needed in the newer Web Components which we will eventually migrate to in the coming years.

**Comment by tmcconechy** [comment]
Whats the use case for clicking on images (and even putting them in grid cells)?

**Comment by kkulick** [comment]
Use Case:
Our current Shop Floor application written in Angular using Bootstrap has grids which support the display of an image in a cell.  This feature is used to display a picture associated with the part id on the grid row.  When the user clicks or taps on the part picture, a modal opens which displays a larger/full size image.  So, the row displays a “Thumbnail” which can be clicked to display full size.

I offered an alternative of having the user select the row and click a button at the top to display the full size picture but it was rejected by product/development manager.  They want it to open in a single click like it does currently.

Currently using the Soho controls, I can use a custom formatter function to display the image, however there does not appear to be a way to catch the click even and have the grid row’s item information available so a modal with the larger picture can be displayed.

All I need is the ability to catch the click on the picture/cell and have the rows data object available in the click handler method for me to use for displaying the full image.  I suspect this could be useful for other things as well.  Maybe the grid row/cell indexes or configuration information would be useful also, but I don’t think I need them to do what I described.

***@***.***

Modal popup to display larger picture.
***@***.***

**Comment by tmcconechy** [comment]
Ok as a workaround you might try the click event on the grid level and look at the target/currentTarget in the event data. But i think we could have an event like the hyperlink click on the column.

The designers i was in sprint plan with had concerns about the discoverability/usability of it. But i think perhaps thumbnails might fit.

**Comment by kkulick** [comment]
It would be even better if the grid supported custom angular template contents which had access to the row/column and item data too.  Then I wouldn’t need a custom formatter.

For example, in our existing bootstrap angular app, we have an angular picture component which is injected into the column using an ng-template.  The template has access to the grid rows data item and passes it into the picture component.  The component itself supports opening the modal with the larger picture so, it’s very reusable throughout the application.  We use this on every grid which has a part id column which is probably 80% of the grids.  For practical use, I would hide the column to improve performance, but product management likes it for the sales value it provides.  A.K.A “Sizzle”.  Along with status icons on the rows.

  <ng-template #partPictureTemplate let-item="item">
    <app-visual-picture *ngIf="item && item.PartPicture"
      [model]="getPartPicData(item)"
      [showLabel]="false"
      [cssClassOverride]="'float-left'"
      [styleOverride]="{'max-height': '5rem'}"
      [enablePopup]="true"
      [showPopupImageLabel]="true"
      [popupImageLabelPosition]="'ABOVE'">
    </app-visual-picture>
  </ng-template>

Apparently, sales and prospective customers go gaga over status icons and images which give them quick reference to the information they are looking for.

One other reason I was given for the use of the part picture is that the manufacturing is being done by people who might struggle with text which may be due to English not being their first language.  So having a picture allows them to identify parts correctly by view.

***@***.***

**Comment by tmcconechy** [comment]
Using a custom NG component is more feasible in our newer web component grid https://main.wc.design.infor.com/ids-data-grid/ but not available yet.

I do get the case for clickable thumbnails now. I think we can add a click to the image column formatter. But for now i do that the grid level click or dblclick event will also work - if you need a faster delivery/workaround.

**Comment by kkulick** [comment]
In order to use a grid/row level click I would need to determine if the user clicked over the cell having the picture.  I think I looked into that, but there didn’t seem to be a good way of obtaining the item information.  I don’t recall exactly, but I think I could get the row index and maybe the column index but matching that up with the cell data item or identifying if the cell clicked is for the picture seemed problematic.

**Comment by kkulick** [comment]
Actually, I should clarify something.  When the click occurs, I would need access to the “row” data object and also know which column/cell was clicked so I can get the key data from the row’s data object (part id etc.) to use for requesting the data to display for the image in the modal.


From: Karl Kulickowski
Sent: Friday, February 3, 2023 10:56 AM
To: infor-design/enterprise ***@***.***>; infor-design/enterprise ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [infor-design/enterprise] Add click handler support for Soho image formatter in legacy Angular components. (Issue #7007)

In order to use a grid/row level click I would need to determine if the user clicked over the cell having the picture.  I think I looked into that, but there didn’t seem to be a good way of obtaining the item information.  I don’t recall exactly, but I think I could get the row index and maybe the column index but matching that up with the cell data item or identifying if the cell clicked is for the picture seemed problematic.

**Comment by tmcconechy** [comment]
Idea for this fix:

- add a class like "actionable" that changes the css cursor to pointer
- show a click handler in plain js in the EP example
- make sure the click handler works in angular (if not already a wrapper might need a wrapper for image comp).
