### ISSUE TITLE
Applicatiionmenu: menubutton popupmenu is displayed at the back

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7013]
**Describe the bug**

**To Reproduce**

1. Open browser mobile
2. Go to https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-menubutton.html
3. Click hamburger menu
4. Click menu button
5. See issue

**Expected behavior**
should be in front (visible and selectable)

**Version**

- ids-enterprise: v4.70.0-dev

**Screenshots**
<img width="158" alt="image" src="https://user-images.githubusercontent.com/56722184/205827026-3dad1624-037c-41c5-8e39-92772d2b68d8.png">

**Platform**
android & iOS

**Additional context**

**Comment by tmcconechy** [comment]
This is actually correct - on mobile the menu will "hang over" not the same as desktop
