### ISSUE TITLE
Listview: Incorrect height calculation for list with searchfield

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise#7015]
**Describe the bug**
When listview is used with search field, there is an issue with height calculation inconsistency:
![image](https://user-images.githubusercontent.com/86295640/205935737-4042fefc-eda0-4687-bcb9-4a4c5e9c8072.png)
This can cause double scroll bar like: 
![image](https://user-images.githubusercontent.com/86295640/205936241-51beaba0-5697-48af-9812-9add6e97ef58.png)

**To Reproduce**

1. Go to 'https://stackblitz.com/edit/list-view-search-scrollbar?file=src%2Fapp%2Flist%2Flist.component.html'
2. Observe that there is a double scroll on the list

**Expected behavior**
Height calculation for the listview with search should used the same value as height of searchfield. 
**Version**

- ids-enterprise: v4.69.0

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor WFM

**Comment by glenlieorillo** [comment]
Working now as expected.


https://user-images.githubusercontent.com/102151352/220531320-d908cc49-de4b-4102-a0ff-5ed556a3e3fe.mov

**Comment by kwolentarski** [comment]
It looks like this does not really fix the issue. Although there is no second scrollbar now, the content of the list is still overflowing the card. Instead of additional scrollbar the bottom border is now hidden under the overflowing content:
![image](https://user-images.githubusercontent.com/86295640/220597933-4aea2277-7b99-4f66-a393-c79111a6bc21.png)

**Comment by tmcconechy** [comment]
@kwolentarski do you mean just push it up a couple pixels so that you see the bottom border? if so i agree. See attached... cc @tjamesallen15 ? Can you add this revision?

![image](https://user-images.githubusercontent.com/814283/220646198-0a08736d-17e8-4355-9118-e01346215b30.png)

**Comment by tjamesallen15** [comment]
Will check on this one.

**Comment by glenlieorillo** [comment]
Tested and passed.

![image](https://user-images.githubusercontent.com/102151352/222617200-8af753a2-6115-4bf2-a828-adab662e0109.png)


https://user-images.githubusercontent.com/102151352/222617210-23baed7f-d418-4f2d-8ab9-06b6d99a4a38.mov
