### ISSUE TITLE
Reordering: Dragging columns after a failed / cancelled drop moves more than one column

### ISSUE THREAD

**Issue by edisonferrer** [infor-design/enterprise#7017]
**Describe the bug**
Encountered on version 4.68.0. Data grid component -> Reordering of columns samples.

When dragging a column and was dropped on the not-droppable area in between columns (area where the cursor changes back to a pointer and the drag icon on the upper left of the dragged column dims), list does not reorder, which is expected. But subsequent drag-and-drop of a column after this was done moves more than one column.

**Describe the bug**

**To Reproduce**

1. Go to data grid samples -> column reordering
2. Drag the last column somewhere between the second and third column. 
3. While holding the drag, drop it in between the columns where the icon changes back to a pointer and the drag indicator on the upper left of the column you are dragging dims.
4. Reordering doesn't happen, which is expected.
5. Drag the last column again, but this time, make sure to drop it correctly.
6. Notice that the dragged column isn't the only one that moved position. 

In the recording attached, only Order Date column is being dragged but was able to reposition Price column as well.

**Expected behavior**
Only the dragged column should change position.

**Version**

- ids-enterprise: 4.68 & 4.69

**Screenshots**
![reorder](https://user-images.githubusercontent.com/47999751/206131690-a48f8e71-238d-43ff-96a0-7117b1b08d33.gif)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by glenlieorillo** [comment]
Working now as expected. Moving this ticket to Done.

Validated in: https://main-enterprise.demo.design.infor.com/components/datagrid/example-reorder.html and http://localhost:4000/components/datagrid/example-reorder.html

https://user-images.githubusercontent.com/102151352/221567990-41519e7d-692d-429d-9c1f-82677ee9f6fe.mov


https://user-images.githubusercontent.com/102151352/221568031-c3f0d961-d53e-4433-9ac4-e901ec042ad5.mov
