### ISSUE TITLE
Application Menu: Clearing search filter doesn't return complete list 

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#702]
**Describe the bug**
[All Browsers] Application Menu: Clearing search filter doesn't return complete list 
http://4100-beta1-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html
http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html

**To Reproduce**
1. Go to URLs above
2. Type "history" in the search field inside Application menu
3. Menu will return with just the History
4. Clear the search field by clicking X icon
5. Menu will not return with the complete list of items

**Expected behavior**
Menu should return with complete list when the search is cleared

**Screenshots**
<img width="644" alt="screen shot 2018-08-29 at 7 06 05 pm" src="https://user-images.githubusercontent.com/39508864/44783980-9f53b800-abbe-11e8-8a9f-d23889fc0ca8.png">

**Platform**
 - All Devices and browsers except IE

**Additional context**
No additional context

**Comment by tmcconechy** [comment]
This regressed on 4.8.0 as it works ok here http://470-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/applicationmenu/example-filterable.html#
Passed QA testing across all browsers.
