### ISSUE TITLE
Modal: spinbox field looks broken when in classic mode. 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#7026]
**Describe the bug**
Modal: splitter field looks broken when in classic mode. 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/modal/example-spinbox.html?theme=classic&mode=light&colors=2578a9
2. Switch to classic 
3. Open the Modal

**Expected behavior**
All fields should render with no error

**Version**
IDS-4.71-DEV

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/207061485-ecefa6f8-75f4-453d-b05e-451739eab1c1.png)

**Platform**
Windows 10 Chrome & all major browsers and devices. 

**Additional context**
N/A

**Comment by tmcconechy** [comment]
Descoping (classic theme has less support now)
