### ISSUE TITLE
Slider: Sliding and dropping the handle outside of the component doesn't trigger the change event

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#7028]
**Describe the bug**
When you slide and drop the handle outside of the component, the change event isn't fired.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/slider/example-stepping?theme=new&mode=dark&colors=0066D4
2. Change the value by either clicking somewhere on the slider or manually sliding using the handle.
3. Notice the toast that appears when the value is changed.
4. Grab the handle and slide it all the way to the left or right and then beyond the component container.
5. Drop the handle.
6. Notice that no toast appears.

**Expected behavior**
The change event should fire even if you drop the handle outside of the component container.

**Version**
- ids-enterprise: 4.69.0

**Platform**
 - Infor OS Portal

**Comment by jbrcna** [comment]
QA Passed.
verified in https://main-enterprise.demo.design.infor.com/components/slider/example-stepping.html
