### ISSUE TITLE
Slider: Add support for fully custom tooltips

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#7029]
We have a requirement to implement a slider that looks like this:

<img width="346" alt="Skärmavbild 2022-12-13 kl  18 56 22" src="https://user-images.githubusercontent.com/63045013/207417599-0cf24a26-a9ea-4ddc-bc4a-1f51caf7a915.png">

In this case we want the tooltip for the max value to say "All", instead of the tick value.

There's currently support for adding a prefix or suffix to the tooltips, but it would be nice to be able to set a fully custom tooltip as well.

**Team: Infor OS Portal**

**Comment by tmcconechy** [comment]
Im not picturing how this would be possible. Because the range is math based so each tick means a mathematical distance to the end... So the end needs to be "some value".

Maybe you can put a max there and add a checkbox next to it for "All". Unless all really means a value and you want to change the label?

**Comment by radovaniljic** [comment]
We don't need to change the value of the tick itself, just the tooltip.

<img width="346" alt="Skärmavbild 2022-12-13 kl  18 56 22" src="https://user-images.githubusercontent.com/63045013/207409129-e27af793-0294-4586-92ad-d2e61d4470d9.png">

The value of the last tick is in this case 11 which is fine, but the way it currently works is that the tick value is used in the tooltip and then you can only add a prefix/suffix to it by defining `tooltipContent` in the slider options, e.g.:

<img width="356" alt="Skärmavbild 2022-12-13 kl  18 59 38" src="https://user-images.githubusercontent.com/63045013/207410531-3dc6128d-927a-47e3-a78c-032bc42b9cd6.png">

What we want to be able to do is to tell the slider to not use the tick value at all in the tooltip, but rather some other text. I think this should be pretty easy to implement. A tick can currently have a value, a description and a color... what you could do is to just add add another property `tooltip` to the tick definition where you can define the text that should be used in the tooltip for each tick. Then, the slider component can either use `tooltip` if it's defined, or `value`  by default if `tooltip` isn't defined.

I hope that makes sense :)

**Comment by tmcconechy** [comment]
OK, So maybe a feature to customize the tooltips as well as. Ability to customize the labels to text (not the) value...
