### ISSUE TITLE
Warning, Success, Error on messages/modals

### ISSUE THREAD

**Issue by kels0** [infor-design/enterprise#703]
**Is your feature request related to a problem? Please describe.**
I want to use a YesOrNo message dialog with a warning similar to https://github.com/infor-design/enterprise/blob/master/app/views/components/message/example-index.html but with a warning icon. Ability to add an errors exists here but no warning.

**Describe the solution you'd like**
I would like to have an enum property to establish.
```
1-success/confirm
2-warning/alert
3-error (exist)
4-info
```

**Describe alternatives you've considered**
I have solved the issue by setting a custom class to the modal that changes the color of the modal-title.

**Comment by tmcconechy** [comment]
You should be able to code this just establish 3 buttons and name them as you would like: https://github.com/infor-design/enterprise/blob/master/app/views/components/modal/test-full-content-buttons.html#L55

In the click code for each you can create the enum. I dont think this is something we need to add to the component directly as you can easily do it that way

**Comment by kels0** [comment]
I'm sorry for not being more clear, I want the modal-title to have different colors.
For example, yellow for warning and red for error.
it does exist for errors but not warnings.

It has nothing to do with buttons.

**Comment by kels0** [comment]
it's a message:

Currently looking like this;
`const options: IMessageDialogOptions = {`
`title: title,`
`message: message,`
`standardButtons: StandardDialogButtons.YesNo,`
`cssClass: cssClass};`

`this.showMessage(options);`

Here i would like to have a `isWarning: true` that give the modal title a yellow-ish color.
Same as isError does, but with red and icon.

**Comment by tmcconechy** [comment]
Yes i think some more icons are a good idea.

**Comment by brianjuan** [comment]
http://localhost:4000/components/message/example-index
http://4120-beta0-enterprise.demo.design.infor.com/components/message/example-index
Passed QA testing on all browsers. Warning, Success, Error messages look good and working correctly.
