### ISSUE TITLE
Builder: icon overlap header text 

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7031]
**Describe the bug**

**To Reproduce**

1. Open mobile device
2. Go to https://main-enterprise.demo.design.infor.com/components/builder/example-builder-subtitle-test.html
3. Select an item

**Expected behavior**
<img width="391" alt="image" src="https://user-images.githubusercontent.com/56722184/207359927-4d8cf818-bcb4-419c-8a90-a35cff33231e.png">

**Version**

- ids-enterprise: v4.71.0-dev

**Screenshots**
<img width="414" alt="image" src="https://user-images.githubusercontent.com/56722184/207359386-ed6656c6-9048-44d8-b0d1-4aa379315649.png">

**Platform**
android & iOS device

**Additional context**

**Comment by tmcconechy** [comment]
Closing builder is somewhat deprecated
