### ISSUE TITLE
EmptyStates: Color Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7033]
**Describe the bug**
1. https://main-enterprise.demo.design.infor.com/components/icons/example-empty-widgets.html shows the azure stroke. should be slate06
2. this page is missing empty-search-data-new
3. https://main-enterprise.demo.design.infor.com/components/icons/example-empty-widgets.html also has some aspects with azure stroke
4. https://main-enterprise.demo.design.infor.com/components/emptymessage/example-widgets.html also has a few

Consider https://github.com/infor-design/enterprise-ng/issues/1418 as well

**Additional context**
Design review

**Comment by jbrcna** [comment]
QA Passed
<img width="365" alt="image" src="https://user-images.githubusercontent.com/56722184/222405977-8876870e-db8f-429e-8359-e5cd0412dbaf.png">

<img width="477" alt="image" src="https://user-images.githubusercontent.com/56722184/222406492-6bd3f2fc-e317-465a-abe0-a3feae436b8e.png">
