### ISSUE TITLE
Datagrid: unable to resize columns when a cell contains table markup

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#7038]
**Describe the bug**
When the cell value for a rich text column contains html table markup the user is unable to adjust column widths.  If the cell value for a rich text column contains other html markup the user is able to adjust column widths.

**To Reproduce**

1. Using the attached 'test-cell-containing-table.html'
2. Attempt to resize any of the columns
3. Notice that none of the column's widths are resizable
4. Update the sample data provided in 'test-cell-containing-table.html'
5. Comment out the data whose product name is 'With Table'
6. Notice that the columns's widths are resizable

**Expected behavior**
Should be able to resize column widths

**Version**

- ids-enterprise: v4.70.0-dev

**Additional context**
Landmark has a customer ticket attached to this issue.

**Comment by claudenbach** [comment]
[Git #7038.zip](https://github.com/infor-design/enterprise/files/10263159/Git.7038.zip)

**Comment by tmcconechy** [comment]
This might be difficult to fix but we can try. Want to note that we dont actually currently support table layout in the editor (although you can paste it in).

**Comment by claudenbach** [comment]
This issue can be closed.  Provided a suggestion to replace the html table markup by using divs with css styling to the team that was creating the html markup.
