### ISSUE TITLE
Status icons in Avatar examples have transparent pixels on the inner icon instead of white fill.

### ISSUE THREAD

**Issue by talkaboutdesign** [infor-design/enterprise#7040]
**Describe the bug**
Some of the status icons next to avatar images show transparent fill on the inner icon instead of a white fill. This causes legibility issues.

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/images/example-photos.html

**Expected behavior**
Icons in the middle of the circles should have white fill. 

**Version**
Latest

**Screenshots**
<img width="514" alt="Screenshot 2022-12-20 at 6 59 45 AM" src="https://user-images.githubusercontent.com/2926534/208662492-b26329fe-9d51-4781-9b44-b5b88306adcc.png">

**Platform**
All Platforms

**Additional context**
This seems to be an issue with the icon itself. It might need to be fixed by the design team.

**Comment by tmcconechy** [comment]
We can fix it with css. I think these are used in different cases where you sometimes need white, sometimes some other background fill.

**Comment by talkaboutdesign** [comment]
@tmcconechy Looking at this file from how it is setup in Figma it looks like icons are always filled white. I also notice that the icons are different. Prob need to check with design team on this. Just flagging this as not consistent with our design file. And the fact that status icons are not really legible because of transparency issue.

**Comment by tmcconechy** [comment]
@inforandy do you have a designer that can check these icons. I think @talkaboutdesign is right because i cant fix it with a stroke. But i can "put something behind it". The gap around the icon idea looks good. I think we can do that as well easily.

**Comment by nownunz** [comment]
I am saying it has to be behind and a stroke. We need it all @tmcconechy!

**Comment by lucacolumbu** [comment]
@inforandy this needs to be reviewed with Danielle.

**Comment by ericangeles** [comment]
On a developers perspective, having behind a stroke is much easier to do than adding fill color in the middle.
