### ISSUE TITLE
Bar-stacked: displays undefined value after clicking legend

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7043]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/bar-stacked/example-index.html
2. Hover over the bars
3. Click series 1 legend
4. Hover over the first bar
5. See undefined value in tooltip
6. Click series 2 legend
7. Hover over the first bar
8. See error

**Expected behavior**
should not display undefined value

**Version**

- ids-enterprise: v4.64.0- v4.71.0-dev

**Screenshots**
<img width="958" alt="image" src="https://user-images.githubusercontent.com/56722184/207083784-52b9a060-ce98-4bd5-9cd1-db15388bd056.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/56722184/207083841-05d930ad-94e3-4ed0-a825-6414a51a81df.png">

**Platform**
All

**Additional context**
see also https://main-enterprise.demo.design.infor.com/components/bar-stacked/example-stacked-100.html
<img width="908" alt="image" src="https://user-images.githubusercontent.com/56722184/207084179-6eeb30e3-476b-4dda-97e2-785e3f992c99.png">
and https://main-enterprise.demo.design.infor.com/components/bar-stacked/example-stacked-colors.html
<img width="888" alt="image" src="https://user-images.githubusercontent.com/56722184/207084505-e3f7ff75-06d7-43ed-81be-4affd2d66e00.png">

**Comment by tmcconechy** [comment]
May be fixed after https://github.com/infor-design/enterprise/pull/6731

**Comment by jbrcna** [comment]
this is now working as expected
v4.90-dev
<img width="968" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/cc9f987a-77c1-476c-be92-de96081690be">
<img width="899" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/5232e9a3-e786-4b17-8448-e61444668e58">
