### ISSUE TITLE
Each instance of splitter component leaves an entry in local storage even when settings.save is false

### ISSUE THREAD

**Issue by edisonferrer** [infor-design/enterprise#7045]
**Describe the bug**
Each instance of splitter component leaves an entry in local storage even when settings.save is false.
Some background:
We're using many instances of the splitter in our application and noticed that it has a lot of entries in local storage (1 per splitter instance). Striving for optimal conditions, we thought that this might be a bug that splitter is still keeping its position value even though settings.save is false.

**To Reproduce**

1. Create a splitter similar to https://design.infor.com/code/ids-enterprise/latest/splitter
2. Set the settings.save to false.
3. Notice in developer tools -> local storage that it still has an entry.

**Expected behavior**
No entry on local storage when settings.save is false

**Version**

- ids-enterprise: 4.68 - 4.70

**Screenshots**
GIF is just to show the local storage entry. We assumed that the sample defaults to settings.save is true but we've tried this to false and same thing happens.
![splitter_local_storage](https://user-images.githubusercontent.com/47999751/208906750-cec7ab26-02b8-4c96-a3b9-51c89fbae2ce.gif)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
