### ISSUE TITLE
Donut Chart colors are coming different hashcode for legend and donut chart 

### ISSUE THREAD

**Issue by spendker** [infor-design/enterprise#7048]
**Describe the Issue**
In donut chart object we will pass the color property.previously we used to give # colorcodes,but later SDK team asked to give lime color classes only so we started replace the hardcoded color codes with lime colors(success,info).
Problem:Now the problem we facing is that when I replace the color code with lime colors then the color codes appear different fo r legends and donut chart   
**To Reproduce**
Steps to see the question or problem:
1. Unzip attached example to '...'
2. Go To ''
3. Click on '....'

**What are you trying to do**
I want to both legend,donut chart colors should be same 

**What did you try so far**
I created donut chart data in stackblitz but it is showing correct codes,but in my local widget environment it is not working

**Version**

data-ids-enterprise-ng-version="14.3.1"

**Screenshots**
If applicable, add screenshots to help explain your question or problem.

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]
![imgpsh_mobile_save](https://user-images.githubusercontent.com/121223526/209104290-4b6d47e1-2ea5-4df5-a6d9-9ce2086f1db8.jpg)
![92ec7ce7-c93e-44ee-986f-a8cf85ec274d](https://user-images.githubusercontent.com/121223526/209104322-d9e83473-28f4-4b99-86c4-8a80d2436818.jpg)

stackblitz url: https://stackblitz.com/edit/ids-quick-start-1421-knjnex?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts
**Additional  Context**
Add any other context about the question or problem here, including the use case if relevant.

**Comment by tmcconechy** [comment]
The stackblitz is giving me errors. But you said it is working... So if its working I'm not sure what we can do. Maybe revert back to the hex value if you have to. Or did you try compare your local code to the working one?

Valid colors are:

```
 'error'
 'alert'
'alertYellow'
 'good'
 'neutral'
 // or hex value
```

We would need to see a stackblitz that shows it not working (as you say it isnt in the local). So i would do more comparing.. But dont see why it wouldnt work https://main-enterprise.demo.design.infor.com/components/donut/example-alerts.html

Check your data perhaps
