### ISSUE TITLE
Toolbar: Search bar/icon and text are overlapping

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7049]
**Describe the bug**
Search bar/icon and text are overlapping.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar/example-non-collapsible-searchfield.html
https://main-enterprise.demo.design.infor.com/components/toolbar/example-selected-event.html
3. Adjust to smaller window

**Expected behavior**
Search bar/icon and text should not overlap.

**Version**

- ids-enterprise: 4.71.0-dev

**Screenshots**

https://main-enterprise.demo.design.infor.com/components/toolbar/example-non-collapsible-searchfield.html

https://user-images.githubusercontent.com/102151352/209111300-40ca451e-c740-4ea0-9cef-6184891e34ad.mov

https://main-enterprise.demo.design.infor.com/components/toolbar/example-selected-event.html
![image](https://user-images.githubusercontent.com/102151352/209111154-591c23dd-732e-41bd-812e-213f295e85e5.png)

**Platform**
 - All major browsers

**Comment by marknolaninfor** [comment]
#7113 causes this issue as getTargetTitleWidth is using the window's width to determine the width, but this can be greater than the width of the toolbar.
