### ISSUE TITLE
Icons: Some icons are blurry for some users in Classic theme

### ISSUE THREAD

**Issue by etegstrom** [infor-design/enterprise#7052]
**Describe the bug**
Some icons (such as the "#icon-tree-ppt" and "#icon-tree-xls" icons) in Classic theme are blurry for some users. 

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/icons/example-index?theme=classic&mode=light&colors=2578a9.

The "#icon-tree-ppt" and "#icon-tree-xls" are blurry for some people in the team. I'm not able to reproduce this, but some other people in the team are encountering this. 

If changing the browser zoom, the icons becomes clear. But if you zoom back to 100%, they become blurry again.

**Version**
- ids-enterprise: v4.69.0

**Platform**
 - Infor Application/Team Name: Infor Homepages
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 108.0.5359.125 (Official Build) (64-bit)

**Additional context**
As mentioned, this is a very strange issue that only occur for some of use even though we use the same device, OS version and browser version. I cannot wrap my head around the cause for this. Perhaps screen resolution plays a part in this maybe?

**Comment by tmcconechy** [comment]
Its probably a cross pixel effect. This is one reason we redid all the new icons. I don't think we will be updating all the classic icons again as they are semi-deprecated. We recommend the new theme. Just for expectations, i think this would involve re doing all the icons with a px size reduction.

**Comment by etegstrom** [comment]
Thanks for clarifying Tim! I'll add a not about this in our ticket. Makes sense to close this then, since it works as expected in the new theme.

**Comment by tmcconechy** [comment]
Sounds good - i dont see us making changes to the old icons. So will just close.
