### ISSUE TITLE
Datagrid: datefield hover issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7053]
**Describe the bug**
when you hover over the date icon, there is  highlight

**To Reproduce**

1. Go to EP that has a datefield 
( e.g., [example-custom-filter-conditions-and-defaults.](https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions-and-defaults.html), [example-custom-filter-conditions](https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-filter-conditions.html), [example-compact-mode](https://main-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html) )
2. Select the date field
3. Hover over the date icon

**Expected behavior**
should have no highlight in icon when hovered
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/56722184/209346317-c43ac182-128f-4ed1-92a4-b96588536fbd.png">

**Version**

- ids-enterprise: v4.71.0-dev

**Screenshots**
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/56722184/209346166-74c8b307-85e3-4244-9855-ee23f2d273e0.png">

**Platform**
All 

**Additional context**

**Comment by tmcconechy** [comment]
This was part fixed by https://github.com/infor-design/enterprise/pull/7042 but not the trigger buttons here

**Comment by jbrcna** [comment]
this is now working as expected. However, when using classic theme in  [example-compact-mode](https://main-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html) the date icon is not displayed
<img width="349" alt="image" src="https://user-images.githubusercontent.com/56722184/211473695-1499d735-0387-47de-861e-959a0dd0b0d5.png">

**Comment by tmcconechy** [comment]
@ericangeles lets try and include this in main and 4.71.x ?

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to done. tahnk you.
https://main-enterprise.demo.design.infor.com/components/datagrid/example-compact-mode.html
<img width="375" alt="image" src="https://user-images.githubusercontent.com/56722184/212609810-5fb90664-3b8a-4d7e-a96f-476703268d09.png">
