### ISSUE TITLE
Lookup: Custom Modal script error after close

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#7057]
**Describe the bug**
(Minor bug)
When using Custom Modal in Lookup and closing the dialog in the second time there is a script error - seems to be related to the resize function.

```
modal.js:1218 Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at Modal.resize (modal.js:1218:18)
    at HTMLBodyElement.<anonymous> (modal.js:1003:12)
    at HTMLBodyElement.dispatch (jquery-3.6.0.js:5430:27)
    at elemData.handle (jquery-3.6.0.js:5234:28)
    at Object.trigger (jquery-3.6.0.js:8719:12)
    at jQuery.fn.init.triggerHandler (jquery-3.6.0.js:8803:24)
    at ResizeObserver.<anonymous> (tabs.js:478:19)
```

**To Reproduce**

1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/test-custom-modal.html](https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/test-custom-modal.html)
2. Click on Lookup icon
3. Close modal by clicking Cancel or Apply
4. Repeat steps 2 and 3.
5. See error in browser console

**Expected behavior**
Shouldn't see console errors

**Version**

- ids-enterprise: . v4.70.0 

**Screenshots**
![image](https://user-images.githubusercontent.com/34129313/209664215-c514ccad-268d-4529-856c-e53f9bde5b4c.png)

**Platform**
 - Device: Windows
 - OS Version: 10
 - Browser Name: Chrome/Edge/Firefox
 - Browser Version: latest

**Additional context**
Thanks!

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
