### ISSUE TITLE
Dependencies: Vulnerability issues and deprecation warnings

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#7064]
**Describe the Issue**

Need to fix all deprecation warnings and vulnerability issues dependencies upon installation of package.

**To Reproduce**
1. You should be using the latest node version `18.x`
2. Run `npm i` (remove node_modules if you have existing IDS project `rm -rf node_modules`)
3. Watch the warnings upon installation
3. After installation, check all the vulnerabilities. As of now `26 vulnerabilities (16 low, 5 moderate, 5 high)`
4. Run `npm audit` for details

**Version**

- ids-enterprise: 4.71

**Additional  Context**
Vulnerability issues are related to
1. glob-parent
2. json5
3. mout
5. postcss

**Comment by tmcconechy** [comment]
One thing we have to do to fix this is get rid of release-it and change the release scripts to manual. This will need help with @corpulent or request fixes from those dependencies.

Plan on seeing if more can be fixed but the first 3 or 4 i looked at are all inside release-it.

**Comment by tmcconechy** [comment]
A further study we need to remove 3 things

- node-sass -> dart-sass = level of effort hard / possibly breaking change
- handlebars-wax / handlebars =  level of effort hard / possible change to doc site
- glob = level of effort not too bad
- release-it = level of effort medium

**Comment by tmcconechy** [comment]
These are updated long ago
