### ISSUE TITLE
Column chart is not taking full width after loading the data.It is shrinking the chart component

### ISSUE THREAD

**Issue by spendker** [infor-design/enterprise#7065]
**Describe the bug**
This issue is regarding the column chart is not taking the full width and it is shrinking the chart component because of this user unable to see the data.

**To Reproduce**

**Expected behavior**
When I load the chart component it should be load in full width.

**Version**

- ids-enterprise: data-ids-enterprise-ng-version="14.3.1"

**Screenshots**
.![Screenshot 2023-01-04 170353](https://user-images.githubusercontent.com/121223526/210548159-4d9eec04-4d6a-4660-8fd2-7fddb1349fca.jpeg)

**Platform**
 - Infor Application/Team Name: LN-widgets
 - Device: Laptop
 - OS Version: windows 11
 - Browser Name: Chrome
 - Browser Version:   Version 108.0.5359.125 (Official Build) (64-bit)

**Additional context**
I am attaching the stackblitz code for the issue
https://stackblitz.com/edit/ids-quick-start-1421-vzhksm?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.css

**Comment by tmcconechy** [comment]
The chart takes the width and size of the parent that it is in. In this example it seems like you can fix it by assigning a height and width to..

```
<div class="lm-height-full lm-margin-md-b">
   <div soho-column="" ng-reflect-dataset="[object Object]" ng-reflect-type="column" class="chart-container empty-message column-chart">
</div>
```

That should fix it. But also the steps here are part of the template. But dont consider this a bug as you have zero height and width on the parent div.

**Comment by tmcconechy** [comment]
Above should solve your issue
