### ISSUE TITLE
Tabs: Drag operation on a tab can switch to that tab and make it active.

### ISSUE THREAD

**Issue by edisonferrer** [infor-design/enterprise#7066]
**Is your feature request related to a problem or use case? Please describe.**
There are times that our users need to copy information from another open tab. This can be achieved though by switching through tabs and using copy/paste, however some users prefer dragging the text they want to copy to the tab they want to place it. The tab then activates and they're able to drop them on the needed area.

**Describe the solution you'd like**
When dragging items/text to an inactive tab, we hope to activate that tab and show its contents so we can drop the dragged item/text.

**Describe alternatives you've considered**
We currently have a working alternative wherein we set the tab active manually when a drag operation is placed on it.

**Additional context**
And what application do you work on? [e.g. {Infor XYZ}]

**Comment by tmcconechy** [comment]
Is this a duplicate of https://github.com/infor-design/enterprise/issues/6445 ? We had previous considered this but felt it was a bit of an old school/desktop way of interacting with the application.
