### ISSUE TITLE
About: Browser version and what appears in the About page doesn't match up

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#7067]
**Describe the bug**
About: Broswer version and what appears in the About page doesn't match up

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/about/example-index.html
2. Click on Show About Screen
3. compare the browser version that appears on the About page and check the browser version from CHROME or any other browser.
4. The browser versions don't match. Please see screen shot attached. 

**Expected behavior**
The browser version on the About component and any web browser should match.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/39101346/210595630-6e5121fc-3ab7-4ad0-a98e-d412dd4b2056.png)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/39101346/210595670-c2d3e83e-2a7f-4d7d-85bb-47528fd058ee.png)

**Platform**
 - All Browsers Name: [e.g. chrome, safari, stock browser]

**Additional context**
Add any other context about the problem here. NONE

**Comment by tmcconechy** [comment]
the version chrome gives no longer contains this info https://www.whatismybrowser.com/guides/the-latest-user-agent/chrome

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
