### ISSUE TITLE
Header/Tabs: Changes Effect Classic/Subtle theme 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7069]
**Describe the bug**
The tab and header changes for landmark should have had no effect on classic/subtle theme but they did. This should be addressed ASAP

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-index.html?theme=classic&mode=light
2. Go to https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?theme=classic&mode=light
3. Test both pages in Classic - Dark/Light/Contrast

**Expected behavior**
In both examples all pages for classic -  Dark/Light/Contrast should be the same as https://4680-enterprise.demo.design.infor.com/components/header/example-index.html

But new theme should have all these changes,

Tests For this issue:
- Both "Versions" - subtle is as before
- All "Modes:
- All "Colors"

**Additional context**
cc @pwpatton

**Comment by pwpatton** [comment]
![image](https://user-images.githubusercontent.com/4737815/210621535-d3d582a8-feb2-4f41-8c06-220169d778f0.png)

![image](https://user-images.githubusercontent.com/4737815/210621556-dcbfeda8-3a44-4c17-9ed5-bc6f45db80a6.png)

![image](https://user-images.githubusercontent.com/4737815/210621581-b6fb8129-1aa4-43b9-86f9-f5227af0f74b.png)

**Comment by glenlieorillo** [comment]
Tested and passed.

**https://main-enterprise.demo.design.infor.com/components/header/example-index.html?theme=classic&mode=contrast&colors=2578a9**

https://user-images.githubusercontent.com/102151352/212584622-c850f661-2e4c-478f-a0c7-d5b10283fb55.mov


**https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?theme=classic&mode=contrast&colors=2578a9**

https://user-images.githubusercontent.com/102151352/212584604-736f3423-c44f-4968-8d3e-e3997fb71b78.mov
