### ISSUE TITLE
Set personalization color via named color from Infor OS V2

### ISSUE THREAD

**Issue by awbuboltz** [infor-design/enterprise#7073]
**Is your feature request related to a problem or use case? Please describe.**
All applications that run within Infor OS V2 are required to display the theme that is passed in from Infor OS as a URL parameter. See this link for details https://wiki.infor.com/confluence/display/companyon/Infor+OS+Portal+-+Theme+and+Personalization.

The query string from OS passes a named color, for example `azure`, not a hex value. The problem is that to use the personalize API, a hex value must be given. For example `$html.personalize({ colors:  '#a13030;' });`

**Describe the solution you'd like**
The request is for the setting of colors via personalize using a named color.

A secondary component to this is the usage of `default`. When default is used, if varies from blue to gray based on the theme being used. That would need to be taken into account.

**Describe alternatives you've considered**
An alternative here would be for Infor OS V2 to pass a hex value to the applications running inside.

**Additional context**
Product: Lawson
I spoke with @EdwardCoyle about this and we decided creating a ticket is a good first step.

**Comment by awbuboltz** [comment]
Update: We were able to use Soho.theme.personalizationColors() to get the map of named colors. That object contains the hex values as the value key. It also takes into account the current theme. `Soho.theme.personalizationColors()['default'].value`  returns `#0072ED` when in dark theme, and `#004A99` in high-contrast.

**Comment by janahintal** [comment]
Hi team, done testing in main. The color changes to amber but there is a console error. Kindly see screenshot below. 
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/45757016/222088716-d39f0c03-635d-4782-b6a6-b541c7da9414.png">

**Comment by ericangeles** [comment]
@janahintal the error has something to do with the deployment and not in the main issue.

**Comment by tmcconechy** [comment]
Im not seeing this anymore https://main-enterprise.demo.design.infor.com/components/personalize/example-classes.html?colors=BB5500 seems ok in the console now. Maybe a redeploy helped
