### ISSUE TITLE
Replace color palette sass vars with more contextual tokens (first pass)

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#708]
**Is your feature request related to a problem? Please describe.**
Currently we use a color palette in Enterprise that isn't dynamic per theme like the ids-identity package we are slowly moving to.

**Describe the solution you'd like**
As a first pass, we want to go through the sass files and replace as many `$color##` (i.e. `$azure06`) variables from the internal Enterprise color palette as we can with more contextual token variables from ids-identity.

**Describe alternatives you've considered**
n/a

**Additional context**

As described this will be a first pass (probably out of a few), so we want to:
- try to replace as many as possible
- note ones that we can't replace just yet
- open a single issue (in the design-system repo) to add any tokens we may need

On completion, follow up with someone to get https://github.com/infor-design/design-system/issues/194 started.

**Comment by tmcconechy** [comment]
Reminder that for the charts, treemap and personalization the colors are a part of the Javascript. So that needs to be addressed.

It might be possible / better to add classes for these that change the fill property ect. (Grep : 2578A9, azure07 ect)

**Comment by clepore** [comment]
@nickwynja pointed out that there are classes for each color in the color palette that will need to be removed and the code updated to not break for that. This is probably a fairly large, breaking change as it might affect customers using those classes.

**Comment by tmcconechy** [comment]
If there are replacements thats probably OK. I doubt color classes aren't all that much used externally since they arent documented/advertised except for the actual palette page (for that code) and a few places internally. We'll just have to document it.

**Comment by nickwynja** [comment]
@tmcconechy Have you heard of anyone using these? It would be nice to remove if possible. I feel OK removing them since they're undocumented and not really "supported".

**Comment by tmcconechy** [comment]
I cant be sure. But i don't remember anyone asking any questions about them if that helps.
But i do use the class as i said in our code. So as long as its just a name change i think it should be fine. With a note that they are calls "$color##" now in the change log seems would cover it all to me.
