### ISSUE TITLE
Buttons: some buttons aren't that readable or visible in dark mode on both Classic and New theme

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#7083]
**Describe the bug**
Buttons: some buttons aren't that readable or visible in dark mode on both classic and new theme

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/button/example-index.html
2. Switch to Dark mode 
3. Switch to all colors to check visibility
4. Try to hover buttons to check visibility
5. Also check in Classic mode

**Expected behavior**
All buttons should not have visibility issue

**Version**
4.71.0-ids-main

**Screenshots**
Dark mode amethyst 
![image](https://user-images.githubusercontent.com/45757016/211303619-21ef129e-6ae2-4a54-a0f4-b1bcdbbdf802.png)

Dark mode Graphite 
![image](https://user-images.githubusercontent.com/45757016/211303788-a4b8e43d-e88b-417f-83ca-64943b7abf5a.png)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
N/A

**Comment by ericangeles** [comment]
@janahintal I already created a ticket for this issue. Will close this now.
