### ISSUE TITLE
Charts: Add support for "info" and palette values as chart data color

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#7084]
**Is your feature request related to a problem or use case? Please describe.**
It's possible to use standard IDS status keywords to color chart segments. The currently supported ones, as far as I know, are:
```
"good"
"error"
"neutral"
"alert"
"alertYellow"
```
https://design.infor.com/code/ids-enterprise/latest/demo/components/donut/example-alerts?theme=uplift&variant=light
![image](https://user-images.githubusercontent.com/1101770/211560152-e6776538-1184-41f8-b010-e1a87b99cc2b.png)

**Describe the solution you'd like**
I think it would make sense to allow "info" as well, to get an info azure color. To support all status colors. It would also be nice to be able to provide palette values, e.g. `azure07`, `ruby03` (same name as existing CSS background-color classes). Because as of now, it's a bit cumbersome to achieve sequential chart types.

We are frequently asked about chart colors by widget developers, who get designs where status colors are used in the charts. Those design comps often include info colors, but info color is not currently supported (without hardcoding a hex value instead).

**Comment by tmcconechy** [comment]
When picking this up. Please add some docs to each of the charts as support is added. One reason we perhaps didnt add this is i think the "info" or no info is just the default and not really sure what the difference in status between info blue and normal grey would be... But no problem adding an option

**Comment by tmcconechy** [comment]
Also this should be checked on the WC charts but this works differently so may not be an issue

**Comment by volante007** [comment]
Updated original post with palette values support

**Comment by jbrcna** [comment]
QA Passed.
https://main-enterprise.demo.design.infor.com/components/donut/example-alerts
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/56722184/213078721-056e2cd8-ba08-41ed-9ea1-d2832848a19f.png">
https://main-enterprise.demo.design.infor.com/components/donut/example-colors
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/56722184/213079119-dae9cf63-03ce-42b6-8ef1-3dfc3dc3d704.png">
