### ISSUE TITLE
Tabs: White theme issues

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#7085]
**Describe the bug**
2nd round of LM design changes are being tested and this is a running list of TODO's. (beta.1)

**To Reproduce**
**1. Disabled Tab foreground color**
![image](https://user-images.githubusercontent.com/4737815/211603414-fcdb1bf1-f71c-468f-9d05-3591da1da051.png)

This example doesn't have the tabs in the header but specifies the tabset as being a header-tab in the classlist. Unable to reproduce in header tabs that are in the header.  

```
<soho-header>
    header content
</soho-header>
<div class=content>
    <div class="tab-container is-personalizable horizontal sticky-tabs header-tabs ng-star-inserted">
        tabset content
    </div>
</div>
```
1. make an example like above
2. run and hopefully we'll see the issue

---

**Tabs focus ring is being cropped**

![image](https://user-images.githubusercontent.com/4737815/211606142-1fd2b3b9-b485-4f02-bf6e-171ad86c5bae.png)

Notice the focus around the focused tab is being cropped.

1. go to https://4710-beta1-enterprise.demo.design.infor.com/components/tabs-header/example-index.html
3. put a tab into focus and see focus ring is cropped at the top

---

**Tabs focus ring is being cropped**

- Fade out doesn't seem quite right
- dropdown icon color seems to be blue when theme color is not white
![image](https://user-images.githubusercontent.com/4737815/211618580-616606fa-53ed-43dc-a5e4-88e6d1ae3cf9.png)

This example is also one where the tabs are set as class='header-tabs' but the tabset is not in the header.
Might only happen with the markup in the **Disabled Tab foreground** example 

```
<soho-header>
    header content
</soho-header>
<div class=content>
    <div class="tab-container is-personalizable horizontal sticky-tabs header-tabs ng-star-inserted">
        tabset content
    </div>
</div>
```
---

**Subtle theme default color**
subtle theme seems to no longer allow the white color. The default is azure.
But now the foreground color is incorrect when using the default color with an is-personalizable form.

![image](https://user-images.githubusercontent.com/4737815/211619904-e1ad3698-6d41-4d23-b97a-9c7c6de3d597.png)

Happens in dark mode too
![image](https://user-images.githubusercontent.com/4737815/211639646-7f3cebf5-23bc-4092-afe2-d6414fb0fec2.png)

The other colors seem to work fine.
![image](https://user-images.githubusercontent.com/4737815/211620701-5e950b69-452f-4e4c-8304-9e567b2bcbb0.png)

---
Tabs in list-detail aren't showing correctly.

<img width="967" alt="image" src="https://user-images.githubusercontent.com/4737815/211917188-a2fc3ecc-64de-4e47-b0dd-990b73993a18.png">

When embedded into a larger form
<img width="870" alt="image" src="https://user-images.githubusercontent.com/4737815/211917563-f352537b-c2ac-4d36-ae2c-8a357d42cf09.png">

**Version**
ids-enterprise: 4.71.0-beta.1

**Comment by tmcconechy** [comment]
cc @ericangeles also i think the color of the tabs is wrong on https://4710-beta1-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?colors=0066D4 and that it should be the same two colors? You can also see the focus state being cropped

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
