### ISSUE TITLE
Listview: searchfield is width issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7089]
**Describe the bug**
searchfield looks short

**To Reproduce**

1. Go to 'https://main-enterprise.demo.design.infor.com/components/listview/example-filters.html
2. See error

**Expected behavior**
<img width="489" alt="image" src="https://user-images.githubusercontent.com/56722184/211736227-d5911cfa-8bcf-4a00-b93e-bdc5cbd78064.png">
<img width="499" alt="image" src="https://user-images.githubusercontent.com/56722184/211736354-16a36570-a450-4f97-8e64-2954e4a7a561.png">

**Version**

- ids-enterprise: v4.70.0-dev

**Screenshots**
<img width="564" alt="image" src="https://user-images.githubusercontent.com/56722184/211736140-7bf95296-f316-41ef-bdda-0f47894a19b3.png">

<img width="516" alt="image" src="https://user-images.githubusercontent.com/56722184/211736190-afcf1dab-8a3e-44e2-9277-5f488f847e19.png">

**Platform**
All

**Additional context**
Affected EPs
[example-filters.html](https://main-enterprise.demo.design.infor.com/components/listview/example-filters.html)
[example-search.html](https://main-enterprise.demo.design.infor.com/components/listview/example-search.html)

**Comment by yohannahbautista** [comment]
Searchfield width fix is included in this PR: https://github.com/infor-design/enterprise/pull/7087

**Comment by jbrcna** [comment]
this is now working as expected. thanks
