### ISSUE TITLE
Listview: button text not readable in light & high contrast

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7090]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/listview/example-multiselect.html
2. Click on item
3. Hover over the buttons

**Expected behavior**

**Version**

- ids-enterprise: v4.70.0-dev

**Screenshots**
https://main-enterprise.demo.design.infor.com/components/listview/example-multiselect.html?theme=new&mode=light&colors=0066D4
<img width="712" alt="image" src="https://user-images.githubusercontent.com/56722184/211735175-a0a8a8a9-cf46-4ed6-9951-35ae12c64a9a.png">

https://main-enterprise.demo.design.infor.com/components/listview/example-multiselect.html?theme=new&mode=contrast&colors=003876
<img width="744" alt="image" src="https://user-images.githubusercontent.com/56722184/211735100-7eaf8773-f581-4b7f-a779-3cd8e3053272.png">

**Platform**
All

**Additional context**
affected EP
[example-multiselect.html](https://main-enterprise.demo.design.infor.com/components/listview/example-multiselect.html)
[example-singleselect-no-deselect.html](https://main-enterprise.demo.design.infor.com/components/listview/example-singleselect-no-deselect.html)

**Comment by tmcconechy** [comment]
one more from QA @ericangeles

**Comment by jbrcna** [comment]
this is now working as expected. thank you
https://main-enterprise.demo.design.infor.com/components/listview/example-multiselect.html?theme=new&mode=contrast&colors=003876
<img width="515" alt="image" src="https://user-images.githubusercontent.com/56722184/212609005-6490e98f-2646-46d4-9cfe-9bb23e394124.png">
