### ISSUE TITLE
design.infor.com requires login

### ISSUE THREAD

**Issue by kimanderssonm3cs** [infor-design/enterprise#7091]
Hi!
I cannot remember that I've ever had to login in order for me to read the documentation on https://design.infor.com/code/ids-enterprise/latest
Why is everything suddenly locked?

**Comment by tmcconechy** [comment]
Hi! Sorry ~ some of the design content was being used by competitor so they locked it down. 

We can give you login access to it if you email: 
Andy Kopas <andrew.kopas@infor.com>; Gaetano Pollice <gaetano.pollice@infor.com>

I do see this as a barrier to adoption, so not personally a fan of this decision.
cc @inforandy @lucacolumbu @danielortiz1982 

It may not always be this way - i hope it should be temporary. Also keep in mind all the component docs are still available in the repo in the readme.md files (this is generated into the site). And the docs and examples are still open source and can be used locally by cloning the repo https://github.com/infor-design/enterprise

Thanks! And sorry for the inconvenience.

**Comment by kimanderssonm3cs** [comment]
Thanks for the reply, I will email them!
