### ISSUE TITLE
Hyperlinks: Text color on hover in dark theme

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#7095]
**Describe the bug**
I'm not sure if this is a bug or by design, but the hyperlink text color gets a grey color on hover in dark theme which looks quite weird going from the default blue color. In light theme the color only changes to a slightly different shade of blue on hover, which I guess should probably be the behavior in dark theme as well.

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/hyperlinks/example-index?colors=606066&theme=new&mode=dark
2. Hover over any of the hyperlinks (except the disabled one)
3. Notice the text color

**Expected behavior**
As mentioned, the text color should probably only just change to a slightly different shade of blue, i.e. the same behavior as in light theme.

**Version**
- ids-enterprise: 4.70.0

**Platform**
 - Infor Application/Team Name: Homepages

**Comment by tmcconechy** [comment]
Its by design but it doesn't look right? I think we should change it to an azure color on hover

**Comment by tmcconechy** [comment]
Lets make it #1C86EF on hover... For now

**Comment by janahintal** [comment]
QA Passed. Now working as expected in https://main-enterprise.demo.design.infor.com/components/hyperlinks/example-index?theme=new&mode=dark#
![image](https://user-images.githubusercontent.com/45757016/217257911-23281573-00a2-4e2f-bd98-c715756a4622.png)
