### ISSUE TITLE
Tabs: Selected tab is barely visible in classic dark theme

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#7097]
**Describe the bug**
Selected tab is barely visible in classic dark theme

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs/example-index?theme=classic&mode=dark&colors=2578a9
2. Notice the color of the selected tab

**Expected behavior**
The selected tab should probably be a different color

**Version**
- ids-enterprise: 4.70.0

**Screenshots**

**NEW THEME**
![tabs_new](https://user-images.githubusercontent.com/63045013/212690131-6874b1c5-2e05-4fb7-bc95-a97860e92089.png)

**CLASSIC THEME**
![tabs_classic](https://user-images.githubusercontent.com/63045013/212690273-48805cb7-da82-4bbc-87e5-8bb127bcc1fd.png)

**Platform**
 - Team: Homepages

**Comment by tmcconechy** [comment]
@radovaniljic this was already fixed in 4.71.x with some tab design work https://main-enterprise.demo.design.infor.com/components/tabs/example-index.html?theme=new&mode=dark

**Comment by tmcconechy** [comment]
ok yeah ~ lets review https://github.com/infor-design/enterprise/pull/7099 and add this comment to it if that is still an issue on that supplemental PR

**Comment by glenlieorillo** [comment]
Failed. Tabs are still unreadable.

![image](https://user-images.githubusercontent.com/102151352/213085143-e4ba9b42-6823-4cc1-9147-095b0c1e29a5.png)

**Comment by ericangeles** [comment]
Reopening this issue

**Comment by glenlieorillo** [comment]
Working as expected. Moving this ticket to Done.


https://user-images.githubusercontent.com/102151352/214988765-6b5dc886-d51b-42d5-a6a2-929b27141ae3.mov
