### ISSUE TITLE
Busyindicator/Modal: Busyindicator is barely visible in modals in dark theme

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#7098]
**Describe the bug**
Busyindicator is barely visible in modals in dark theme.

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/busyindicator/test-inside-modal.html?colors=50535A&theme=classic&mode=dark
2. Click on the "Show Modal" button
3. Click on the "Show Busy Indicator" button
4. Notice that the busyindicator is barely visible

**Expected behavior**
The busyindicator should be more visible

**Version**
- ids-enterprise: 4.70.0

**Screenshots**

The busyindicator is quite difficult to see even when there's no text overlapping with it:

**NEW THEME**
![busyindicator_new](https://user-images.githubusercontent.com/63045013/212693789-4799a050-613c-4bbe-8a9c-ad771dad69d7.png)

**CLASSIC THEME**
![busyindicator_classic](https://user-images.githubusercontent.com/63045013/212693817-a3fab41f-3e69-4028-8c29-26b69a827efa.png)

**Platform**
 - Team: Homepages

**Additional context**
As you can see in the screenshots, this is an issue in both new and classic theme, but it's not as difficult to see in new theme

**Comment by tmcconechy** [comment]
Also an issue on https://design.infor.com/code/ids-enterprise/latest/demo/components/busyindicator/example-body.html?theme=new&mode=dark&colors=0066D4 i think we should make it 2 lighter/darker
