### ISSUE TITLE
IDS tertiary button enhancement

### ISSUE THREAD

**Issue by jvedua** [infor-design/enterprise#7101]
Request to enhance the I**DS Button's** **_tertiary_** variant (link below) affordance.
https://latest-enterprise.demo.design.infor.com/components/button/example-index.html

<img width="149" alt="image" src="https://user-images.githubusercontent.com/49638020/212881052-66b0dc69-7260-462c-b9e2-7ddd8a12ee29.png">

During one of the presentation of a widget design proposal for HRT, their PM Parker Erikson commented on how he was not able to identify a tertiary button as a "clickable" button as it doesn't show any clear affordance, it cannot even be identified as a link as it doesn't display any underline nor blue color.

The **"Request Time Off"** button is _primary_ while the **"View requested"** is _tertiary_, as per feedback it looks more of a label than a clickable button.
<img width="568" alt="image" src="https://user-images.githubusercontent.com/49638020/212881850-c4ada343-d63a-499f-bacf-7640918dc157.png">

A recommendation to enhance this variant to display affordance just like the sample below:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/49638020/212890422-e62da487-8b18-4fd2-a89d-42bb6d1de7e8.png">

**Comment by tmcconechy** [comment]
I don't really think we should change the tertiary button as its used for toolbars mainly and would look wierd with a border. 

I think what you want here is a secondary button. On the current version its https://latest-enterprise.demo.design.infor.com/components/button/example-index.html (its grey) but...

on the upcomming version its already been changed to something that would look more like you proposed. https://main-enterprise.demo.design.infor.com/components/button/example-index.html

**Comment by jvedua** [comment]
Thank you @tmcconechy! will communicate this with the team
