### ISSUE TITLE
Header: misaligned border

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7102]
**Describe the bug**

**To Reproduce**

1. Go to https://4710-beta2-enterprise.demo.design.infor.com/components/header/example-tabs-alternate.html
2. Click on tabs
3. Press arrow keys

**Expected behavior**
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/56722184/212923483-4af8f3f7-0eab-4e71-a83b-9abb630f20bc.png">

**Version**

- ids-enterprise: v4.71.0-beta2

**Screenshots**
<img width="877" alt="image" src="https://user-images.githubusercontent.com/56722184/212923963-1df62eaa-7b42-46d5-bc9d-ca8df7f8243e.png">

**Platform**
All
**Additional context**

**Comment by tmcconechy** [comment]
@tjamesallen15 / @ericangeles this should be fixed on the supplemental fixes if not already. ?

**Comment by ericangeles** [comment]
@tmcconechy I believe @EdwardCoyle noticed that issue on this PR https://github.com/infor-design/enterprise/pull/7099

**Comment by jbrcna** [comment]
this is now working a expected. thanks
https://main-enterprise.demo.design.infor.com/components/header/example-tabs-alternate.html
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/56722184/214556371-9b841ee8-f0d5-4935-9521-73475e3f32eb.png">
