### ISSUE TITLE
Header: tab labels hard to read when hovered

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7103]
**Describe the bug**
when you changed the color, the tab labels were hard to read when hovered

**To Reproduce**

1. Go to https://4710-beta2-enterprise.demo.design.infor.com/components/header/example-tabs-alternate.html?theme=new&mode=contrast&colors=0066D4
2. Hover over on each tabs
3. See error
4. try also with different colors
5. play around with different modes

**Expected behavior**
should be readable

**Version**

- ids-enterprise: v4.71.0-beta23

**Screenshots**
<img width="903" alt="image" src="https://user-images.githubusercontent.com/56722184/212924863-a90faea5-a361-4e91-bfa4-e23472ad52e5.png">

**Platform**
all

**Additional context**

**Comment by tmcconechy** [comment]
@ericangeles / @tjamesallen15 ~ same with this one.

**Comment by ericangeles** [comment]
@tjamesallen15 please include this issue

**Comment by jbrcna** [comment]
this is now working as expected. thanks
https://main-enterprise.demo.design.infor.com/components/header/example-tabs-alternate.html?theme=new&mode=contrast&colors=0066D4
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/56722184/214555087-56b2b7ea-5fc1-485c-bf1b-6d4b685950d6.png">
