### ISSUE TITLE
White theme issues

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#7105]
**Describe the bug**
More white theme issues

**Tabs in list-detail aren't showing correctly.**

<img width="967" alt="image" src="https://user-images.githubusercontent.com/4737815/211917188-a2fc3ecc-64de-4e47-b0dd-990b73993a18.png">

When embedded into a larger form
<img width="870" alt="image" src="https://user-images.githubusercontent.com/4737815/211917563-f352537b-c2ac-4d36-ae2c-8a357d42cf09.png">

---

**Vertical tabs focus state is incorrectly placed**

1. goto https://main-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html
2. select a tab (click on it) and see incorrect placement of focus 

![image](https://user-images.githubusercontent.com/4737815/212982714-5fb57303-4670-4aa6-832c-3172b0630c1a.png)

---

Foreground color is incorrect in subtle light theme with is-personalization set. But only in the default theme color

![image](https://user-images.githubusercontent.com/4737815/212962891-a4babe8d-b0aa-4cec-a1e2-0f10d40a8ccb.png)

---

Toolbar has wrong hover and click color.

![image](https://user-images.githubusercontent.com/4737815/213005724-5fc6c316-24ce-45de-ba7a-d8cdd761a38a.png)

---

When a color is set disabled tabs foreground color is wrong

![image](https://user-images.githubusercontent.com/4737815/213006180-77e2665f-7566-4189-be11-be1ef7f5b189.png)

---
- ids-enterprise: 4.71.0-beta.2

**Comment by tmcconechy** [comment]
@ericangeles ?

**Comment by janahintal** [comment]
Hi team, still failing on these sample pages for New and Classic Theme. 

https://main-enterprise.demo.design.infor.com/components/compositeform/test-with-tab-headers-vertical.html & https://main-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html?theme=classic&mode=light&colors=2578a9

![image](https://user-images.githubusercontent.com/45757016/214853617-dc09d771-217a-46c1-8af9-bb6cf36f6857.png)
![image](https://user-images.githubusercontent.com/45757016/214853775-b7d28970-c8d7-425f-a91e-ec8f2b2fc639.png)
![image](https://user-images.githubusercontent.com/45757016/214854043-7284b0ae-9fb4-4654-9274-5b6a8ad6a3ba.png)
![image](https://user-images.githubusercontent.com/45757016/214854138-f5e6ff69-862f-4a0f-9bd6-c8198184ec04.png)



Passed - https://main-enterprise.demo.design.infor.com/components/page-patterns/test-landmark-requisitions-screen.html?theme=classic&mode=light&colors=2578a9
https://main-enterprise.demo.design.infor.com/components/page-patterns/test-landmark-requisitions-screen.html?theme=classic&mode=light&colors=2578a9
![image](https://user-images.githubusercontent.com/45757016/214852983-42b6a7d8-f151-42c7-b0ed-f74e5e66666c.png)
![image](https://user-images.githubusercontent.com/45757016/214853216-b9f9159f-3a0d-4755-a909-da6eccc36038.png)

**Comment by ericangeles** [comment]
@tjamesallen15 can you take a look again?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 can you take a look again?
Hello @ericangeles 
I checked it again in main and its okay now. It was fixed here https://github.com/infor-design/enterprise/pull/7135, it was merged yesterday
![image](https://user-images.githubusercontent.com/34049950/215004542-9cca6113-022c-4f88-8931-20a9962eae10.png)
![image](https://user-images.githubusercontent.com/34049950/215004576-3dafd356-5f52-4c9e-9975-639eded7c268.png)

**Comment by janahintal** [comment]
Tabs focus are now working as expected in https://main-enterprise.demo.design.infor.com/components/compositeform/test-with-tab-headers-vertical.html?theme=classic&mode=contrast&colors=BB5500 & https://main-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html?theme=classic&mode=contrast&colors=2578a9
