### ISSUE TITLE
Searchfield: Focus look off in buttons

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#7106]
**Describe the bug**
Searchfield: Focus look off in buttons

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-searchfield-full, https://main-enterprise.demo.design.infor.com/components/header/example-searchfield-large
2. Type something in the search field 
3. Click tab to focus on the button

**Expected behavior**
There should not be any alignment issues in focus for the button

**Version**
IDS-4.710-BETA2

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/212959804-75ace586-b3bd-4716-96c6-4de997bc408a.png)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
N/A

**Comment by tmcconechy** [comment]
one more to fix @ericangeles / @yohannahbautista

**Comment by janahintal** [comment]
QA Passed. Verified on both classic and new theme. Thanks!
![image](https://user-images.githubusercontent.com/45757016/214845688-d9d74169-9104-4209-b90b-b8dee817e1b5.png)
![image](https://user-images.githubusercontent.com/45757016/214848886-b6d8981b-e911-41ce-9fd6-da437b22cf75.png)
