### ISSUE TITLE
Tabs: Unreadable tab title in Classic Version, Dark Mode

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7109]
**Describe the bug**
Unreadable tab title in Classic Version, Dark Mode

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/example-index.html?theme=classic&mode=dark&colors=2578a9
2. See error

**Expected behavior**
Tab title should be readable.

**Version**

- ids-enterprise: 4.71.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/102151352/213070798-41b7a840-d512-4041-b039-38956a665ccf.png)

**Platform**
 - All major browsers

**Comment by glenlieorillo** [comment]
Duplicate ticket to #7097

**Comment by ericangeles** [comment]
Duplicate issue. Closing this one now.
