### ISSUE TITLE
Searchfield: button looks off when field is collapsed

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7110]
**Describe the bug**

**To Reproduce**

1. Go to https://4710-beta2-enterprise.demo.design.infor.com/components/header/example-toolbar-flex-with-categories.html
2. Click on searchfield
3. input some text
4. Click anywhere on the page
5. hover over the button
6. see error

**Expected behavior**

**Version**

- ids-enterprise: v4.71.0-beta2

**Screenshots**
<img width="1561" alt="image" src="https://user-images.githubusercontent.com/56722184/213095355-7afc326b-a1b8-49a4-9915-fa336ef963bb.png">

**Platform**
All

**Additional context**

**Comment by yohannahbautista** [comment]
May be fixed with this PR: https://github.com/infor-design/enterprise/pull/7120 (WIP)

**Comment by tmcconechy** [comment]
This looks fixed @yohannahbautista but in white mode the search field needs a border see https://main-enterprise.demo.design.infor.com/components/header/example-toolbar-flex-with-categories.html 

Also maybe change the ... menu to the theme/color menu so all the states can be tested.

This can probably wait until next version if you cant get to it right away

**Comment by jbrcna** [comment]
this is now working in local. will retest again once available in main thanks.
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/56722184/215983387-d08931d9-e67b-47bb-939e-134fe8b2e2f7.png">

**Comment by jbrcna** [comment]
Retest passed in main.
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/56722184/216270510-1662d9c5-0120-463a-a3a2-1da43fcf16d5.png">
