### ISSUE TITLE
EmptyMessages: Offer difference sizes of icons

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7115]
**Describe the bug**
We want to offer designs that are bigger (smaller) than the standard sizes. As per https://www.figma.com/file/82eiVHRCZzCpqukPL2pLe8/Empty-states?node-id=405%3A3471&t=BKkXme79EC214QZx-0

**Tasks**

- will get a new figma with different sizes / icons
- need to implement a way to show each new icon in its correct size
- update the examples
- update design system to have size meta data

**Additional context**
Assets for first round are https://www.figma.com/file/82eiVHRCZzCpqukPL2pLe8/Empty-states?node-id=626%3A5279&t=PpRGHZ3mSJolZ1G5-1 (these will come in the identity package)

Original jira ask https://jira.infor.com/browse/IDS-850

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/icons/example-empty-states.html
