### ISSUE TITLE
Timepicker with Korean locale gives an invalid value

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise#7116]
**Describe the bug**
When using the timepicker component with a Korean locale (ko-KR), the value that the user selects is invalid.

**To Reproduce**
1. Open the URL: https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=ko-KR
2. Click the clock icon to open the value selector.
3. Select a time, any time, and press the 'Set Time' button.
4. Note the field validation immediately shows an error.

**Expected behavior**
The value entered using the selector should be a valid value.

**Version**
Ent: 4.70.0
NG: 14.7.0
**Screenshots**
![image](https://user-images.githubusercontent.com/39279254/213536466-42f395d1-4282-47dc-9b49-d4025b65e931.png)
Note in the screenshot above, the value returned from the selector puts the day period value (오전) after the time value (1:00).

If you manually enter the day period value BEFORE the time value, the value is valid. For example:
![image](https://user-images.githubusercontent.com/39279254/213537124-53da836f-2b6d-4352-b37e-d13fea419b76.png)

If you look at the IDS ko-KR locale file, you'll see that the timeFormat is 'a h:mm'.
 
**Platform**
 - Infor Application/Team Name: GLT
 - Device: 
 - OS Version: Win 11
 - Browser Name: Chrome
 - Browser Version: 109.0.5414.75 

**Additional context**

**Comment by janahintal** [comment]
Issue still exists in https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-CN

Steps:
1. Select 12:00 PM 
2. Click Set Time 

<img width="2047" alt="image" src="https://user-images.githubusercontent.com/45757016/219294542-b233982b-6836-47f4-8c86-605b3ee515ae.png">

**Comment by tmcconechy** [comment]
Hmm wierd @andriivarhanov i tried this on main and not seeing the fix. Do you know where it is? i remember it worked fine on the PR...

**Comment by andriivarhanov** [comment]
@andriivarhanov it works for ko-KR, but not for zh-CN since it's `ah:mm`. I've fixed it, PR should be ready in a few minutes

**Comment by janahintal** [comment]
QA Passed.  Verified on both https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=ko-KR & https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html?locale=zh-CN. Thanks!
