### ISSUE TITLE
Searchfield: unable to type a text in field on mobile

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7117]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/searchfield/example-buttons.html
2. Click on searchfield
3. Type a text

**Expected behavior**
should be able to input a text

**Version**

- ids-enterprise: v4.71.0-beta2/main

**Screenshots**
<img width="473" alt="image" src="https://user-images.githubusercontent.com/56722184/213632419-12efa6e2-943d-403f-8c60-e9cc575dcd50.png">

**Platform**
mobile

**Additional context**
searchfield is also small. icons were outside.

**Comment by tmcconechy** [comment]
Close to some of the other issues in this sprint. Should make sure its fixed for mobile

**Comment by yohannahbautista** [comment]
May be fixed with this PR: https://github.com/infor-design/enterprise/pull/7087

**Comment by tmcconechy** [comment]
Looks fixed now. I can confirm

**Comment by jbrcna** [comment]
QA Passed.
