### ISSUE TITLE
Searchfield: advance search label not visible in light & high contrast

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7118]
**Describe the bug**

**To Reproduce**

1. Go to https://4710-beta2-enterprise.demo.design.infor.com/components/header/example-searchfield-large
3. See error
4. switch to high contrast
5. See error

**Expected behavior**
advance search label should be visible

**Version**

- ids-enterprise: v4.71.0-beta2/main

**Screenshots**
<img width="956" alt="image" src="https://user-images.githubusercontent.com/56722184/213654250-bef93b62-fbac-4da7-af18-f26ab222d0c9.png">

**Platform**
All

**Additional context**

**Comment by jbrcna** [comment]
issue still exists in https://main-enterprise.demo.design.infor.com/components/header/example-searchfield-large?theme=new&mode=light&colors=default
v.4.91.0-dev.0
<img width="1693" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/9c299f39-8a07-48d9-bc37-aab86e0c6052">

**Comment by tmcconechy** [comment]
Descoping this, old pattern no one cares about
