### ISSUE TITLE
search field width is incorrect

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#7123]
**Describe the bug**
the input for a searchfield is too narrow for the container it's in.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/listview/example-search.html
2. Notice the search field is too narrow for it's container

There appears to be some strange width inline style that wasn't there in 4.70
![image](https://user-images.githubusercontent.com/4737815/214093201-6644e2ae-5c1c-42a8-af4b-448b4c5153eb.png)

**Expected behavior**
That the search field width is 100% of it's container

**Version**
- ids-enterprise: 4.71.0-beta.2

**Screenshots**
What my screen looks like in ids-enterprise: 4.71.0-beta.2
![image](https://user-images.githubusercontent.com/4737815/214094137-49788515-1567-49db-bbb3-c0535b6c2cc0.png)

In 4.70 it was working. Notice there is no calc() inline style.
![image](https://user-images.githubusercontent.com/4737815/214094429-dc15ee66-2225-4b40-8c02-069c3e06868f.png)

**Comment by tmcconechy** [comment]
@yohannahbautista can you check this too? we can wait for the search field PR to merge and see

**Comment by yohannahbautista** [comment]
Hello, it looks to be fixed now
<img width="827" alt="Screen Shot 2023-01-24 at 12 20 36 PM" src="https://user-images.githubusercontent.com/85279127/214212408-006252dc-e3f5-4fe6-b16e-b4e02057159e.png">

**Comment by tmcconechy** [comment]
Cool, looks good now

**Comment by glenlieorillo** [comment]
Tested and passed. Moving this ticket to Done.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/214468389-70c72046-c0d2-4262-af5d-2499a54fce75.png">
