### ISSUE TITLE
Modal: Tooltip validation on an input field has misaligned error icon

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#7125]
**Describe the bug**
When tooltip validation is used on an input field inside of a modal, the error icon and tooltip message are not aligned with the input field.

**To Reproduce**

1. Add the attribute data-error-type="tooltip" onto the Type dropdown and Email input at http://localhost:4000/components/modal/example-validation.html
2. Go to http://localhost:4000/components/modal/example-validation.html
3. Click the Add Context button
4. Trigger the validation by clicking in and out of the fields.
5. See that the tooltip validation on the dropdown is aligned with the field, but the tooltip validation on the input field is not.

**Expected behavior**
It is expected that the error icon is found inside the input field with the tooltip validation directly underneath the error icon.

**Version**
- ids-enterprise: 4.71.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/76002134/214416586-5754d86c-d096-4ae1-9502-c54759565b9a.png)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 109.0.5414.75 (Official Build) (64-bit)

**Comment by glenlieorillo** [comment]
Working as expected.

https://main-enterprise.demo.design.infor.com/components/modal/example-validation.html
![image](https://user-images.githubusercontent.com/102151352/220523897-08d092d4-934a-4974-bdfe-127aa86ed059.png)

![image](https://user-images.githubusercontent.com/102151352/220524140-28d67a8c-d3c5-4cdf-96ae-b0c5b571a432.png)
