### ISSUE TITLE
Tabs: Focus looks off when selected & hovered 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#7126]
**Describe the bug**
Tabs: Focus looks off when selected & hovered 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/example-index.html
2. Click any Tab
3. Hover and focus on the selected tab
4. Also check in Classic 

Also check the following Tab Links with focus issues: 

- https://main-enterprise.demo.design.infor.com/components/tabs-header/example-add-tab-button.html
- https://main-enterprise.demo.design.infor.com/components/tabs-module/example-index.html?theme=classic&mode=light&colors=2578a9#order-entry
- https://main-enterprise.demo.design.infor.com/components/tabs-multi/example-index.html
- https://main-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html

**Expected behavior**
There should be no alignment issues after selecting and hovering a tab

**Version**
ids-4.71

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/214495639-1923d7d5-662c-495a-9c5b-607a1f0c79df.png)

Classic 
![image](https://user-images.githubusercontent.com/45757016/214496169-56263982-5619-49f9-b206-18b48a88c241.png)

Tabs Header: Main Menu 
![image](https://user-images.githubusercontent.com/45757016/214498698-59c9429e-74c0-430e-828b-85d308bbcc15.png)

Tabs Module: 
![image](https://user-images.githubusercontent.com/45757016/214499002-fabafe34-f6b2-4dc6-a618-7b15827ac12a.png)
![image](https://user-images.githubusercontent.com/45757016/214499075-3b51c7bc-5419-478a-a691-35c850d0885b.png)

Tabs Multi: 
![image](https://user-images.githubusercontent.com/45757016/214499345-dcc5b045-7aa0-4d74-b091-18f6cb735a01.png)

Tabs Vertical: 
![image](https://user-images.githubusercontent.com/45757016/214499484-ba64addc-da2e-4bf0-a511-97fc106e9ded.png)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
N/A

**Comment by tmcconechy** [comment]
@ericangeles @tjamesallen15 - we probably need to address this too for the release.

**Comment by tjamesallen15** [comment]
Hello Team,

 This was fixed on https://github.com/infor-design/enterprise/pull/7135. For testers, please check again the main. The PR was merged yesterday.

Thanks!

**Comment by ericangeles** [comment]
Can you test it again @janahintal ? Thanks!

**Comment by janahintal** [comment]
Hi team, done retesting the ticket it it seems to be fixed now. Thanks!
