### ISSUE TITLE
Summary will be selected

### ISSUE THREAD

**Issue by swuendri** [infor-design/enterprise#7128]
**Describe the bug**
When having a data grid with summary row and enabled option to select a row, then the summary row will also be selected, when you select the first row in data grid. 

**To Reproduce**
1. git clone https://github.com/infor-design/enterprise.git
2. cd enterprise
3. change the file `app/views/components/datagrid/example-summary-row.html` and add selectable option
```
@@ -35,6 +35,7 @@
         columnReorder: true,
         dataset: data,
         summaryRow: true,
+        selectable: 'single',
         toolbar: {title: 'Compressors', actions: true, rowHeight: true, results: true }
       });
     });
```
4. npm ci
5. npm run start
6. When IDS server is running open a browser with the shown URL and append `components/datagrid/example-summary-row.html`to open the changed HTML file.
7. Select and unselect the first row and maybe other rows

**Expected behavior**
The summary should never be selected.

**Version**
- ids-enterprise: v4.70.0

**Screenshots**
![image](https://user-images.githubusercontent.com/35500068/214566909-1b6da4f1-942b-458a-8186-42637622e2f1.png)

**Additional context**
This bug was introduced by solving #6746.

**Comment by jbrcna** [comment]
QA Passed.
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/56722184/215006302-8819369c-206e-4a2f-a575-1e8a1ae3efd8.png">
