### ISSUE TITLE
Icons: Incorrect color of new empty state icons

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7131]
**Describe the bug**
The new empty state icon colors isn't correct as in the Figma design file. The exclamation, question mark icon, and outline of the icons should not blue.

In Figma (The correct one)
![image](https://user-images.githubusercontent.com/102151352/214750732-e909dda9-8fb7-4707-ad64-e886cfb98a27.png)

In the IDS
![image](https://user-images.githubusercontent.com/102151352/214750754-12d0a4f6-1897-4337-bd64-1ce82d819e26.png)

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/icons/example-empty-widgets.html
2. Compare the new empty state icon colors above
3. See discrepancies

**Expected behavior**
Should match the design in Figma

**Version**

- ids-enterprise: 4.71.0-dev

**Comment by ericangeles** [comment]
The correct one here is the second image above, @glenlieorillo and it's correct in the main. https://main-enterprise.demo.design.infor.com/components/icons/example-empty-widgets.html

Will close the ticket now. Thanks!
