### ISSUE TITLE
Lookup: Default values not selected when opening the lookup (source, multiselect)

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#7133]
**Describe the bug**
For a lookup with default values that uses `source` to provide the dataset, the default values are not always selected when opening the lookup. If they get selected or not depends on the time it takes to fetch the data in `source` before providing the results in `response`. 

**To Reproduce**
Can be reproduced by modifying existing sample slightly.

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/example-multiselect-paging-serverside?theme=classic&mode=light&colors=2578a9
2. Open dev. console
3. Paste the modified initialization code below in console and hit enter to execute it
4. Open the second lookup
Result: Values not selected

```
$('#product-lookup-2').lookup({
           field: 'productId',
           options: {
              columns: columns,
              dataset: [],
              paging: true,
              pagesize: 5,
              pagesizes: [5, 10, 25],
              selectable: 'multiple',
              allowSelectAcrossPages: true,
              toolbar: {
                results: true,
                keywordFilter: false,
                actions: true,
                rowHeight: false,
                collapsibleFilter: false,
                fullWidth: true,
                contextualToolbar: true
              },
              source: function (req, response) {
                var url = '//4690-enterprise.demo.design.infor.com/api/compressors?pageNum='+ req.activePage +'&pageSize='+ req.pagesize;

                if (req.sortField) {
                  url += '&sortField=' + req.sortField + '&sortAsc=' + req.sortAsc;
                }

                if (req.filterExpr && req.filterExpr[0]) {
                  url += '&filterValue=' + req.filterExpr[0].value;
                  url += '&filterOp=' + req.filterExpr[0].operator;
                  url += '&filterColumn=' + req.filterExpr[0].columnId;
                }

                // Get Page Based on info in Req, return results into response;
                $.getJSON(url, function(res) {
                  // This is the total going into the grid so the pager works (filtered total or total)
                  req.total = res.total;

                  if ((req.filterExpr && req.filterExpr[0])) {
                    req.total = res.total;
                    req.grandTotal = res.grandTotal; // This is the total amount on the server
                  }
                  setTimeout(function() { response(res.data, req) }, 500);  
                });
              }
           }
        });
```
I just added a timeout of 500ms before calling the `response` function (it would rarely be called instantly when using source). I'm not sure how fast it needs to be to work, a delay of 200ms seems to work fine. I.e., if request to fetch data is very fast, it might work, otherwise it won't.

**Expected behavior**
The default values should be selected when opening the lookup even when loading of data takes some time.

**Version**
- ids-enterprise: v4.69.0/latest

**Screenshots**
![lookup](https://user-images.githubusercontent.com/1101770/214794768-4250d6d8-af88-430b-ab44-49edef182b30.gif)

**Comment by yohannahbautista** [comment]
Hello, checking on local and main and it looks to have already been fixed:

Main: Do all the steps mentioned except using this link https://main-enterprise.demo.design.infor.com/components/lookup/example-multiselect-paging-serverside?theme=classic&mode=light&colors=2578a9

Local: Copy-pasted the code snippet in the html file and the lookup selects the items
