### ISSUE TITLE
Searchfield: x icon placed outside the field 

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7134]
**Describe the bug**
 x icon placed outside the field in `classic theme`

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/searchfield/example-buttons.html?theme=classic&mode=light&colors=2578a9
2. Type a text 
3. See error

**Expected behavior**
<img width="351" alt="image" src="https://user-images.githubusercontent.com/56722184/214772896-9ab2e3be-8043-4482-9697-62e0acb67534.png">

**Version**

- ids-enterprise: v4.71.0-dev/main

**Screenshots**
<img width="348" alt="image" src="https://user-images.githubusercontent.com/56722184/214773173-5a712bed-e13d-4cc3-82e3-3a40bba841ef.png">

**Platform**
All

**Additional context**

**Comment by jbrcna** [comment]
this is now working as expected. However it looks off in mobile view. 
<img width="443" alt="image" src="https://user-images.githubusercontent.com/56722184/215673235-eaa1080c-5716-4a17-86dd-9b51d1ab952f.png">

<img width="416" alt="image" src="https://user-images.githubusercontent.com/56722184/215673282-28224f82-6615-42c2-be66-8a774939394b.png">

**Comment by janahintal** [comment]
QA Passed. Verified in https://main-enterprise.demo.design.infor.com/components/searchfield/example-buttons.html?theme=new&mode=light&colors=2578a9 for both responsive and classic & new themes. 
<img width="2047" alt="image" src="https://user-images.githubusercontent.com/45757016/219302951-e0e69efa-7c78-4e9f-b704-c4c942bd9f6b.png">
