### ISSUE TITLE
Hero: Needs color adjustments and fixes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7136]
**Describe the bug**
Some of the colors and states on https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html are behaving odd now.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html
2. Notice the tab colors are hard to read and states are strange
3. Click the button in top left in the header (states are weird)
4. Change colors
5. In some colors the circle pager should change

**Expected behavior**
Better color coordination - use the new design colors https://www.figma.com/file/epOdvMMse6clzIL52ymsrF/Portal-V2%3A-Component-Library?node-id=43%3A3462&t=CIXC15jacU8BGooK-0

The new design attached will change the secondary color. Also this will apply on examples like https://main-enterprise.demo.design.infor.com/components/page-patterns/test-saleshub-builder.html?colors=BB5500 with the subheader color changing there as well. Note this example isn't working https://main-enterprise.demo.design.infor.com/components/page-patterns/test-saleshub-builder.html?colors=BB5500 with color change (header stays white).

**Priorities**

- [ ] On desktop fix the tab states -> make them just use https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html?colors=1F9254
- [ ] on mobile make the circle page white in some colors 
- [ ] fix the hover state on the button -> can use tertiary button as used on header
- [ ] tabs should not disappear on mobile?
- [ ] add header + subheader example to header page
- [ ] Same issue on this page https://main-enterprise.demo.design.infor.com/components/personalize/example-form.html?colors=BB5500 ?

**Screen shots**
![Screenshot 2023-01-26 at 1 29 41 PM](https://user-images.githubusercontent.com/814283/214919775-8d3ea558-d403-451e-91ae-e1347dc34862.png)
![Screenshot 2023-01-26 at 1 29 44 PM](https://user-images.githubusercontent.com/814283/214919777-37402112-fe59-43ef-961d-e8791e6a0575.png)
![Screenshot 2023-01-26 at 1 29 50 PM](https://user-images.githubusercontent.com/814283/214919779-46d8c2d1-c67e-46a0-815a-d4476a2f9a86.png)

**Comment by glenlieorillo** [comment]
QA failed. Texts are unreadable in Classic Version.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/222712304-6750a5b0-9a4c-4c10-a6d0-504f11efd5f0.png">

https://user-images.githubusercontent.com/102151352/222712246-209e1acd-c090-4392-ba4a-670079209903.mov

**Comment by glenlieorillo** [comment]
Working as expected. Moving this ticket to Done.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/223302534-d08f4024-c418-4d9e-8fc9-9b65f0fd341d.png">


https://user-images.githubusercontent.com/102151352/223302650-01aeaeb7-dd06-44dd-8d1b-a40923a9fdbc.mov
