### ISSUE TITLE
Tooltip: Show overlapping data in the tooltip

### ISSUE THREAD

**Issue by SacroVennis** [infor-design/enterprise#7139]
Line chart has a problem in displaying the data through tooltip when the dots have same values. Hence, when the dots are overlapping, only one value is visible, and there is no indicator from which dot the value belongs to.

The line chart would work better if the tooltip can display 2 values (like how the grouped/stacked bar chart works) when the dots are overlapping, and one value when it is not. Please see ideal tooltip layout for line chart:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/112992009/215027095-0b56bda7-b377-46aa-ab67-cdfa64c57098.png">

As a workaround, the developer used the same tooltip layout from the stacked bar chart, and it works with the overlapping dots. However, for the non-overlapping dots, it's confusing because it also shows the value from the other dot that is plotted on the same column.

We are currently using the chart for a T2V homepage.

**Comment by tmcconechy** [comment]
If possible can you attach test data and settings so we can replicate this issue? Also please if you can edit the issue and use the markup template with all the info in it? https://github.com/infor-design/enterprise/issues/new/choose

**Comment by SacroVennis** [comment]
I have updated the ticket

**Comment by tmcconechy** [comment]
I guess we can just use any data as long as they have the exact same value?

**Comment by SacroVennis** [comment]
Hi Srinithya- You can use the data you have shown to me before. 

Hi Tim - How should we give the code to you here?

**Comment by tmcconechy** [comment]
Can you attach it here and add to the steps? Thinking about it i think if you just take the current sample and edit the values to be the same it will reproduce it in https://github.com/infor-design/enterprise/blob/main/app/views/components/line/example-index.html#L22... So no big need for anything special im also hoping everyone follows the issue template when making issues...

https://github.com/infor-design/enterprise/issues/new?assignees=&labels=&template=bug_report.md

**Comment by pulavarthy** [comment]
Hi @tmcconechy , @SacroVennis 

 var dataset = [{
    data: [{
        name: 'Jan',
        value: 3211,
        depth: 4,
        attributes: [
         { name: 'id', value: 'line-a-jan' },
         { name: 'data-automation-id', value: 'automation-id-line-a-jan' }
       ]
    }, {
        name: 'Feb',
        value: 3110,
        attributes: [
         { name: 'id', value: 'line-a-feb' },
         { name: 'data-automation-id', value: 'automation-id-line-a-feb' }
       ]
    }, {
        name: 'Mar',
        value: 3411,
        attributes: [
         { name: 'id', value: 'line-a-mar' },
         { name: 'data-automation-id', value: 'automation-id-line-a-mar' }
       ]
    }, {
        name: 'Apr',
        value: 3011,
        attributes: [
         { name: 'id', value: 'line-a-apr' },
         { name: 'data-automation-id', value: 'automation-id-line-a-apr' }
       ]
    }, {
        name: 'May',
        value: 3411,
        attributes: [
         { name: 'id', value: 'line-a-may' },
         { name: 'data-automation-id', value: 'automation-id-line-a-may' }
       ]
    }, {
        name: 'Jun',
        value: 3111,
        attributes: [
         { name: 'id', value: 'line-a-jun' },
         { name: 'data-automation-id', value: 'automation-id-line-a-jun' }
       ]
    }],
    name: 'Component A',
    legendShortName: 'Comp A',
    legendAbbrName: 'A',
    attributes: [
     { name: 'id', value: 'line-comp-a' },
     { name: 'data-automation-id', value: 'automation-id-line-comp-a' }
   ]
  }, {
    data: [{
        name: 'Jan',
        value: 3211,
        attributes: [
         { name: 'id', value: 'line-b-jan' },
         { name: 'data-automation-id', value: 'automation-id-line-b-jan' }
       ]
    }, {
        name: 'Feb',
        value: 3111,
        attributes: [
         { name: 'id', value: 'line-b-feb' },
         { name: 'data-automation-id', value: 'automation-id-line-b-feb' }
       ]
    }, {
        name: 'Mar',
        value: 2411,
        attributes: [
         { name: 'id', value: 'line-b-mar' },
         { name: 'data-automation-id', value: 'automation-id-line-b-mar' }
       ]
    }, {
        name: 'Apr',
        value: 2011,
        attributes: [
         { name: 'id', value: 'line-b-apr' },
         { name: 'data-automation-id', value: 'automation-id-line-b-apr' }
       ]
    }, {
        name: 'May',
        value: 2411,
        attributes: [
         { name: 'id', value: 'line-b-may' },
         { name: 'data-automation-id', value: 'automation-id-line-b-may' }
       ]
    }, {
        name: 'Jun',
        value: 2811,
        attributes: [
         { name: 'id', value: 'line-b-jun' },
         { name: 'data-automation-id', value: 'automation-id-line-b-jun' }
       ]
    }],
    name: 'Component B',
    legendShortName: 'Comp B',
    legendAbbrName: 'B',
    attributes: [
     { name: 'id', value: 'line-comp-b' },
     { name: 'data-automation-id', value: 'automation-id-line-comp-b' }
   ]
  }, {
    data: [{
        name: 'Jan',
        value: 1211,
        attributes: [
         { name: 'id', value: 'line-c-jan' },
         { name: 'data-automation-id', value: 'automation-id-line-c-jan' }
       ]
    }, {
        name: 'Feb',
        value: 3112,
        attributes: [
         { name: 'id', value: 'line-c-feb' },
         { name: 'data-automation-id', value: 'automation-id-line-c-feb' }
       ]
    }, {
        name: 'Mar',
        value: 3411,
        attributes: [
         { name: 'id', value: 'line-c-mar' },
         { name: 'data-automation-id', value: 'automation-id-line-c-mar' }
       ]
    }, {
        name: 'Apr',
        value: 1011,
        attributes: [
         { name: 'id', value: 'line-c-apr' },
         { name: 'data-automation-id', value: 'automation-id-line-c-apr' }
       ]
    }, {
        name: 'May',
        value: 1411,
        attributes: [
         { name: 'id', value: 'line-c-may' },
         { name: 'data-automation-id', value: 'automation-id-line-c-may' }
       ]
    }, {
        name: 'Jun',
        value: 1811,
        attributes: [
         { name: 'id', value: 'line-c-jun' },
         { name: 'data-automation-id', value: 'automation-id-line-c-jun' }
       ]
    }],
    name: 'Component C',
    legendShortName: 'Comp C',
    legendAbbrName: 'C',
    attributes: [
     { name: 'id', value: 'line-comp-c' },
     { name: 'data-automation-id', value: 'automation-id-line-comp-c' }
   ]
  }];

Can you please try with this dataset...

**Comment by tmcconechy** [comment]
@SacroVennis this still needed? Closing this as trying to descope old issues but if needed let me know
