### ISSUE TITLE
Icons: New System Icons

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7142]
**Is your feature request related to a problem or use case? Please describe.**
New icons are added:

up-down-chevron
approve-all
import-spreadsheet
microphone

**Describe the solution you'd like**
Post a PR with new icons/new ids identity.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by glenlieorillo** [comment]
QA tested ad passed.

**up-down chevron**
<img width="443" alt="image" src="https://user-images.githubusercontent.com/102151352/215666780-ec18bde9-ca8b-4edc-85bd-bbd86f561fe2.png">

**approve-all**
<img width="443" alt="image" src="https://user-images.githubusercontent.com/102151352/215666977-84816636-556e-44ff-bf8d-43a119c47a2d.png">

**import-spreadsheet**
<img width="443" alt="image" src="https://user-images.githubusercontent.com/102151352/215666588-8fa68a30-04d7-48ac-8999-c20006e2c6a6.png">

**microphone**
<img width="443" alt="image" src="https://user-images.githubusercontent.com/102151352/215667107-1fd38b20-78b1-4eab-b81f-406875d0887b.png">
