### ISSUE TITLE
Tabs: counts focus issue mobile

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7145]
**Describe the bug**
there seems to be a white box in tabs when using mobile

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html
2. Click a tab to focus
3. Swipe right to see the blur/fade
5. Notice a white box in right side

**Expected behavior**
should be clear

**Version**

- ids-enterprise: v4.71.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/56722184/215395299-eebdef69-bcb3-41b9-89d9-4b6ec894b32d.png)

**Platform**
Android & iOS

**Additional context**
you can also try in mobile view in devtools. click to focus a tab then swipe right or left.
<img width="457" alt="image" src="https://user-images.githubusercontent.com/56722184/215395552-a769c284-7764-4efe-8414-6cbf85cae4a2.png">

**Comment by tmcconechy** [comment]
Descoping this one
