### ISSUE TITLE
Dropdown and Multiselect: Disabled options not disabled when using ajax and not templateManaged

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#7150]
**Describe the bug**
When using the ajax callback for a dropdown or multiselect, a disabled option is not displaying as disabled.

**To Reproduce**

1. Modify states-all.json to disable option Alaska:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/22107636/215829623-f4df51f7-610d-47d9-ad94-daf6e95cb4ba.png">

2. Go to /components/dropdown/example-ajax.html
3. Click on the dropdown
4. See that no options are disabled
 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/22107636/215831300-cfbfe8d2-73e4-419d-b56b-f5882e73c45e.png">

**Expected behavior**
Disabled options should be disabled correctly.

**Version**

- ids-enterprise: v4.71.0-dev

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor Landmark
 - Device: All
 - OS Version: All
 - Browser Name: All
 - Browser Version: All

**Additional context**
It looks like [buildOption in dropdown.js](https://github.com/infor-design/enterprise/blob/main/src/components/dropdown/dropdown.js#L3380) doesn't check for disabled flags at all. Changing it to check for disabled like this fixes the issue for both dropdown and multiselect:

```
function buildOption(option) {
        if (option === null || option === undefined) {
          return;
        }

        const isString = typeof option === 'string';
        const stringContent = option;
        let id = '';
        let selected = '';
        let textContent = '';
        let disabled = '';

        if (isString) {
          option = {
            value: stringContent
          };
        }

        if (option.value !== undefined) {
          option.value = replaceDoubleQuotes(option.value);
        }

        if (option.id !== undefined) {
          if (!isNaN(option.id)) {  //eslint-disable-line
            option.id = `${option.id}`;
          }
          option.id = replaceDoubleQuotes(option.id);
          id = ` id="${option.id}"`;
        }

        if (option.label !== undefined && option.label.length) {
          option.label = replaceDoubleQuotes(option.label);
          textContent = option.label;
        }

        // Detect whether or not the `<option>` should be selected
        const selectedValues = self.selectedValues;
        const hasSelectedValues = selectedValues.indexOf(val) > -1;
        if (self.settings.multiple) {
          val.forEach((value) => {
            if (value === option.value) {
              option.selected = true;
            }
          });
        } else if (option.value === val || hasSelectedValues) {
          option.selected = true;
        }
        if (option.selected) {
          selected = ' selected';
        }

        if (option.disabled) {
          disabled = ' disabled';
        }

        // Make sure that text content is populated.
        // If all else fails, just use the value.
        if (!textContent.length && textContent !== option.value) {
          textContent += option.value;
        }

        // Render the option element
        list += `<option${id} value="${option.value}"${selected}${disabled}>
          ${textContent}
        </option>`;
      }


```

**Comment by janahintal** [comment]
QA Passed. Verified in 
https://main-enterprise.demo.design.infor.com/components/dropdown/example-ajax.html?theme=classic&mode=contrast&colors=2578a9
https://main-enterprise.demo.design.infor.com/components/multiselect/example-ajax.html?theme=new&mode=contrast&colors=003876
