### ISSUE TITLE
Personalization: When using .is-personalizable class on a form links are styled in white causing them to appear not to display when the color is set to white

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#7153]
**Describe the bug**
when using .is-personalizable class on a form links are styled in white causing them to appear not to display when the color is set to white

**To Reproduce**
Notice on the form here that the hyperlink test is white. This works fine for colors other than white
![image](https://user-images.githubusercontent.com/4737815/216066308-fe75ef76-37cd-4483-ab75-0ccbd1b6c80e.png)

Notice on the white color the hyperlink seems to disappear, it's there but it's foreground color is still white making it seem like it's disappeared.
![image](https://user-images.githubusercontent.com/4737815/216066898-c90f21e5-0bfe-48f2-9570-e92eb332ac28.png)

1. Got to a composisteForm and make the context form (summary) have the is-personalizable 
2. add a link to the composite form "summary"
3. Notice in white color the hyper link is white

**Expected behavior**
The hyperlink should return to the standard blue hyper link color in the white color.

**Version**
- ids-enterprise: 4.71.0-beta.2

**Comment by jbrcna** [comment]
QA PAssed
verified in https://main-enterprise.demo.design.infor.com/components/personalize/example-form-landmark2.html?theme=new&mode=contrast&colors=003876
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/56722184/220321520-5a96649c-0582-40e7-9eaa-e28f880ace5c.png">
