### ISSUE TITLE
DataGrid: items hidden by keyword search are selected when selectAllCurrentPage 

### ISSUE THREAD

**Issue by darinw** [infor-design/enterprise#7154]
When a keyword filter is applied and selection is set to selectAllCurrentPage, it will select everything from the beginning to the last visible item on the page.

1. Go to https://stackblitz.com/edit/ids-quick-start-1421-4vdkke?file=src/app/app.component.html
2. type 1 in the keyword filter(leaving 1, 10-19) and hit enter
3. Click the select all checkbox
4. See that 18 are selected from 1 to 18 (including the hidden items from 2-9)

**Comment by darinw** [comment]
Also Toggling it will only deselect the visible ones. So code for deselect appears correct.

**Comment by tmcconechy** [comment]
@darinw  still needed? If so let me know. Closing old issues marked stale
