### ISSUE TITLE
Soho icon/"info": too dark in dark mode when 'alert' attribute is set

### ISSUE THREAD

**Issue by gustavpollak** [infor-design/enterprise#7158]
**Describe the bug**
The 'info' icon color is too dark when 'alert' attribute is set to 'true' while in Dark mode in PortalV2.

Currently in PortalV2: 
![image](https://user-images.githubusercontent.com/49652924/216299379-f37e9fc2-eece-49eb-b9b7-06a1acd3ca5b.png)
![image](https://user-images.githubusercontent.com/49652924/216299786-d641d869-3872-4532-b091-a70974dd30a6.png)

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/icons/example-index?theme=new&mode=dark&colors=0066D4
2. See 'info' icon
3. Open dev tool and choose the info-icon
4. Set css color setting for the icon to #606006.

![infodarkmode](https://user-images.githubusercontent.com/49652924/216569511-d662a4c8-b847-4df6-98a0-7c546542074a.gif)

**Expected behavior**
Not sure, but maybe a slightly lighter shade of gray so the icon does not look like it's disabled?

**Version**

- data-sohoxi-version: 4.70.0
- ids-enterprisie-ng-version: 14.5.0

**Platform**
Team: Portal V2

**Comment by volante007** [comment]
Can be seen directly in the alert icons demo page as well

https://design.infor.com/code/ids-enterprise/latest/demo/components/alerts/example-index?theme=new&mode=dark&colors=0066D4

**Comment by jbrcna** [comment]
QA Passed.
verified in 
https://main-enterprise.demo.design.infor.com/components/alerts/example-index?theme=new&mode=dark&colors=0066D4
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/56722184/220324901-85b1a128-2463-4637-8c35-70228ac4bf44.png">
