### ISSUE TITLE
Color Picker Component: The work None is not appearing when selecting "None" from the palette

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#716]
**Describe the bug**
Color Picker Component: The work None is not appearing when selecting "None" color picker option

**To Reproduce**
1. Go to URL: http://4100-beta1-enterprise.demo.design.infor.com/components/colorpicker/example-index.html
2. Option the color picker and select "None" from the palette 
3.The word "None" is not appearing in the color picker field box

**Expected behavior**
The word "None" should appear in the Color Picker field-box when the user selects "None" from the color picker Palette. Please see screen shot attached. 

**Screenshots**
![color picker example page](https://user-images.githubusercontent.com/39101346/44860558-7a098d00-ac44-11e8-8cc7-7e62882f79b8.png)

**Platform**
 - All Browsers and Devices 

**Additional context**
None

**Comment by tmcconechy** [comment]
I don't think this is an issue as that is not the functionality. It just clears the value from the field.
It doesn't enter the word none. This was working this way all the while.. Fx on last version

http://490-enterprise.demo.design.infor.com/components/colorpicker/example-index.html
