### ISSUE TITLE
Buttons: Correct Compact Buttons

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7161]
**Describe the bug**
Implement this design https://www.figma.com/file/VcRDGPFqlp3MJ46mEWkGPf/Buttons?node-id=1333%3A7327&t=MRKvhIAXxk2W4Xa0-0

**To Reproduce**

1. [Go to '...'](https://main-enterprise.demo.design.infor.com/components/form/example-compact-mode.html)
2. Add a secondary button
3. Ensure design is like this
4. Test dark/classic and contrast

**Additional context**
Grooming

**Comment by janahintal** [comment]
QA Passed. Verified https://main-enterprise.demo.design.infor.com/components/form/example-compact-mode.html thanks!
