### ISSUE TITLE
Header: Change from Pseudo Elements to actual icon / Header Cleanup

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7163]
**Describe the bug**
Change header hamburger to use the icon and change header text size.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-index.html
2. Notice the icon is not a real icon in the design system
3. See text size

**Expected behavior**
- Change all hamburger examples to use the actual SVG icon
- Change header size to 24px
- What about double text (two sizes) https://main-enterprise.demo.design.infor.com/components/header/example-eyebrow.html

**Additional context**
The icon was using https://main-enterprise.demo.design.infor.com/components/icons/example-pseudo-elements.html / keep the page for now. But no longer need to use it on header

https://jira.infor.com/browse/IDS-887 

**Conform To Design**
https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/IDS-(SoHo)-Component-Library-v4.5?node-id=26118%3A55002&t=0KTc3uMUCKmOZ3a0-1

**Comment by jbrcna** [comment]
https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-index
<img width="252" alt="image" src="https://user-images.githubusercontent.com/56722184/223392443-ad318478-3216-4f4e-8ebb-095403ee7699.png">
https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-performance
<img width="251" alt="image" src="https://user-images.githubusercontent.com/56722184/223392823-44f09508-fabf-44bd-9f43-762c627c5361.png">
https://main-enterprise.demo.design.infor.com/components/builder/example-builder-nosidebar#
<img width="198" alt="image" src="https://user-images.githubusercontent.com/56722184/223393363-f1966163-88c7-4ada-b3b3-100ddd1938ad.png">
https://main-enterprise.demo.design.infor.com/components/builder/example-builder-subtitle-test
<img width="265" alt="image" src="https://user-images.githubusercontent.com/56722184/223393564-0ffa9cea-ea83-4447-9949-ab613198a471.png">
https://main-enterprise.demo.design.infor.com/components/builder/example-builder
<img width="220" alt="image" src="https://user-images.githubusercontent.com/56722184/223394011-52fa70cb-9be2-460b-b914-f9cc492289a7.png">
https://main-enterprise.demo.design.infor.com/components/builder/example-builder-wizard
<img width="216" alt="image" src="https://user-images.githubusercontent.com/56722184/223394143-da459d85-456c-465c-8d7e-d0aa351c2378.png">
https://main-enterprise.demo.design.infor.com/components/button/example-badge
<img width="205" alt="image" src="https://user-images.githubusercontent.com/56722184/223394503-4e6cc1cc-5616-4da6-a651-5bc84dd3426d.png">
https://main-enterprise.demo.design.infor.com/components/form-compact/example-list-detail.html
<img width="185" alt="image" src="https://user-images.githubusercontent.com/56722184/223394673-f791f8bf-38c8-4e39-8041-de5d4d719585.png">
https://main-enterprise.demo.design.infor.com/components/header/example-emphasize-id
<img width="281" alt="image" src="https://user-images.githubusercontent.com/56722184/223395264-9e1723c9-727b-4883-8bc0-2098fd6cf667.png">
