### ISSUE TITLE
Lookup: Keyword search not working with single quote(')

### ISSUE THREAD

**Issue by MohanKumarPalanisamy** [infor-design/enterprise#7165]
**Describe the bug**
Lookup keyword search not working with single quote(')

**To Reproduce**

Find the attached screen shot for more info.
Code: https://stackblitz.com/edit/ids-enterprise-4800-18nghf?file=index.html,index.js

**Expected behavior**
Search needs to work with single quote(') also.

**Version**
- ids-enterprise: latest

**Screenshots**
![image](https://user-images.githubusercontent.com/124390327/216673485-8eb0d367-f455-4a46-bea0-e5e325f2062d.png)
![image](https://user-images.githubusercontent.com/124390327/216673369-cc4169da-3e27-444c-8ffb-21516ffbe7a3.png)

**Platform**
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 109.0.5414.120 (Official Build) (64-bit)

**Additional context**

**Comment by jbrcna** [comment]
QA Passed.
https://main-enterprise.demo.design.infor.com/components/lookup/example-index.html
<img width="751" alt="image" src="https://user-images.githubusercontent.com/56722184/226308935-1fabdd26-a438-47f9-a3d4-7611aed397ad.png">
