### ISSUE TITLE
Circle Page Component: The page view is different on MAC and Windows

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#717]
**Describe the bug**

**To Reproduce**
1. Go to URL: http://4100-beta1-enterprise.demo.design.infor.com/components/circlepager/example-index.html
2. Expand the window on both MAC Chrome and Window's 10 IE 11
3. On MAC Chrome when you expand the window you see all three slides 
4. On Window's 10 IE 11 you only see one slide when the window is expanded. Please see screen shots attached.

**Expected behavior**
Both operating system should match

**Screenshots**
![circle page _2](https://user-images.githubusercontent.com/39101346/44862404-9c050e80-ac48-11e8-9f45-8c7416f361d9.png)
![circle page _3](https://user-images.githubusercontent.com/39101346/44862405-9c050e80-ac48-11e8-83c6-fb65ef2fb19d.png)
![circle page_1](https://user-images.githubusercontent.com/39101346/44862406-9c050e80-ac48-11e8-98a3-39e276f09e87.png)

**Platform**
 - Window 10 IE 11 and MAC Chrome

**Additional context**
None

**Comment by tmcconechy** [comment]
Descoping this issue for now
