### ISSUE TITLE
Personalize: Color font is not changing upon selecting version/mode until you refresh the page

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7171]
**Describe the bug**
Color font is not changing upon selecting version/mode until you refresh the page.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/personalize/example-classes.html (_all examples_)
2. Change version/mode
3. See error
4. Refresh the page

**Expected behavior**
Color font should change instantly upon changing the version/mode.

**Version**

- ids-enterprise: 4.81.0-dev

**Screenshots**

https://user-images.githubusercontent.com/102151352/217144967-5004ac85-8aa6-4b59-aed0-00468fd2871e.mov

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
@ericangeles -> one more...

**Comment by ericangeles** [comment]
Adding @andriivarhanov to this issue as this PR https://github.com/infor-design/enterprise/pull/7223 

@tjamesallen15 can you test the PR and check it again?

**Comment by glenlieorillo** [comment]
Working as expected. Moving this ticket to Done.


https://user-images.githubusercontent.com/102151352/221552959-fefea768-84f4-4ee3-8f30-feddcd8b4586.mov
