### ISSUE TITLE
Personalize: Subheader background color is blue/azure by default

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#7173]
**Describe the bug**
When the personalisation color is set to "default", e.g through `PersonalizeDirective.colors = ""` or `Soho.personalization.setColors("")`, headers (`.is-personalizable .personalize-header`) are white. However subheaders (`.is-personalizable .personalize-subheader`) is blue `#0054b1`.

**To Reproduce**

**Expected behavior**
The personalizable subheader should also be white, or perhaps some variation of white for it to be different from the header?

**Version**

- ids-enterprise: 4.80.0

**Screenshots**
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/4991954/217210640-58bdb48d-754d-4486-aaf7-b29205835b98.png">
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/4991954/217212764-46d51bf3-7df3-4580-afb8-f53a441f1083.png">

**Additional context**
Related: #7167

**Comment by tmcconechy** [comment]
One more @ericangeles ~ @anhallbe is the markup available for this?

**Comment by anhallbe** [comment]
This is with the Angular directives, but it shouldn't make much of a difference?:

```html
<section class="is-personalizable">
  <soho-header>
    <soho-toolbar-flex>
      <soho-toolbar-flex-section [isTitle]="true">
        <h1 soho-toolbar-flex-section-title>Header with correct color</h1>
      </soho-toolbar-flex-section>
    </soho-toolbar-flex>
  </soho-header>

  <section class="personalize-subheader">
    <p>
      Text inside subheader that probably has the incorrect color for both
      background and text.
    </p>
  </section>
</section>
```

Repro here: https://anhallbe.github.io/ids-repro/header-personalization

Code here: https://github.com/anhallbe/ids-repro/blob/master/src/app/header-personalization/header-personalization.component.html

Light Default:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/4991954/217278496-72e8b1d9-9d0f-4905-941e-a5c9960bcaf8.png">

Light Azure:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/4991954/217278598-9d4bd278-0e83-43b8-9335-d5d559fef0b2.png">


Dark Default:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/4991954/217278706-3d0978cb-1215-4ac9-b15d-3b81b41ac1e9.png">

Dark Azure:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/4991954/217278784-05e6a920-26bf-4cda-a927-e7595066165f.png">

High Contrast Default:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/4991954/217278877-5dc81c76-d4d7-4fd2-b091-f7cf5bcc2a75.png">

**Comment by tmcconechy** [comment]
FYI issue will be patched in 4.80.2 / NG 14.8.2 ~ running shortly

**Comment by anhallbe** [comment]
@tmcconechy @tjamesallen15 the issue appears to be fixed in 4.80.2 light theme, but in dark theme the subheader doesn't have any background color (with the default color):

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/4991954/218041914-ecb02bc6-3552-4a6c-96f3-1586d2149dc7.png">

**Comment by tmcconechy** [comment]
@tjamesallen15 can you pick up the remaining issue here?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 can you pick up the remaining issue here?

![image](https://user-images.githubusercontent.com/34049950/220028364-52b4b97a-76c8-49d8-adff-2d679ce97365.png)
Hello @tmcconechy @anhallbe . I checked the dark new theme mode and it seems okay in my end, running the latest in the main branch

**Comment by tmcconechy** [comment]
ok seems ok on https://main-enterprise.demo.design.infor.com/components/header/example-subheader.html?colors=0066D4&theme=new&mode=dark there are a lot of different issues so maybe this got fixed along the way

**Comment by glenlieorillo** [comment]
Working as expected.

Tested in: http://localhost:4000/components/header/example-subheader.html?colors=606066&theme=new&mode=dark and https://main-enterprise.demo.design.infor.com/components/header/example-subheader.html?colors=default&theme=new&mode=dark

**Default**
![image](https://user-images.githubusercontent.com/102151352/222621135-ee865c2d-e7e3-4ef5-aa24-8decef376623.png)

**Slate**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/222621798-a2d50367-2fd4-4b0e-a66f-1050364eb251.png">

**Turquoise**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/222621843-76cc4df2-0e47-4443-982d-a2f64cd92460.png">
