### ISSUE TITLE
Tree - Does not update model when sorting in some situations

### ISSUE THREAD

**Issue by Milan1983** [infor-design/enterprise#718]
Replication steps:
Step 1:
Drag "New Item 2" and drop "Public Folders"
Step 2:
 Drag "New Item 2" and drop at same level "Public Folder"
Step 3:
 Drag "New Item 2" and drop "New Item 1"
Step 4:
 Drag "New Item 2" and drop at same level "Public Folder"

Looking the page,looks fine,but I don't think it is realistic model.
I tried to call on console $('#addnode-tree').data('tree').settings.dataset
[Tree_Sortable.zip](https://github.com/infor-design/enterprise/files/2336995/Tree_Sortable.zip)
And now shows realistic model,and it is wrong,because are not cleaning step 1 and step 3

 
Actual Result ( It does not matter the order):
 Public Folders
     - New Item 2
 New Item 2
 New Item1 
     -New Item 2

Expected Result(It does not matter the order):
   Public Folders
   New Item 1
   New Item 2

The page appears as expected, but dataset does not.
Can confirm calling $('#addnode-tree').data('tree').settings.dataset on console

**Comment by Milan1983** [comment]
My project will end at the end of the month. Is there any chance this Issue will be solved before that?
Thank you

**Comment by tmcconechy** [comment]
This issue relates to #618 and should probably be fixed at the same time.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/tree/test-sortable-update-dataset.html
Passed QA testing across all browsers.
