### ISSUE TITLE
Bar: Left axis label is missing

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7181]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/bar/example-axis-labels.html
2. See error

**Expected behavior**
should be visible

**Version**

- ids-enterprise v4.81.0-dev

**Screenshots**
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/56722184/217408641-81a2d97a-6c4f-48f2-b604-89cb40be4cd4.png">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Also due to d3 changes ~ same issue as https://github.com/infor-design/enterprise/issues/7181 ?
