### ISSUE TITLE
Bar: cannot select/deselect category A & C

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7182]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/bar/example-contextmenu.html
2. Click on Categroy A
3. Category B is selected
4. Click on Categroy C
5. Nothing happen

**Expected behavior**
should work properly.

**Version**

- ids-enterprise: v4.81.0-dev

**Screenshots**

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Also due to d3 changes...
