### ISSUE TITLE
Bar: Long text not visible/cut off

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7183]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/bar/example-long-text.html
2.  See error

**Expected behavior**

**Version**

- ids-enterprise: v4.81.0-dev

**Screenshots**
<img width="918" alt="image" src="https://user-images.githubusercontent.com/56722184/217550258-a77c6cfa-4b54-4adf-a672-24a3c95c38e7.png">

**Platform**
 All

**Additional context**
https://main-enterprise.demo.design.infor.com/components/bar/example-negative-value.html
'Category' text is missing
<img width="943" alt="image" src="https://user-images.githubusercontent.com/56722184/217550906-72561099-c278-4a60-8e31-541ed557e182.png">

**Comment by tmcconechy** [comment]
Regression from my d3 changes. But we/I can try to get this later unless noticed by a team. Because we have a lot in this sprint.

cc @ericangeles

**Comment by tmcconechy** [comment]
@deep7102 this is related to me updating d3.. from 5 to 7 would you recall what the code was that did this? Looked for a fix but not 100% seeing it

http://localhost:4000/components/bar/example-long-text.html
vs
https://4800-enterprise.demo.design.infor.com/components/bar/example-long-text.html

**Comment by deep7102** [comment]
@tmcconechy 
It caused by statement `if (!this.canvas) return 0;` in `charts.js`
because this it looks it never going to pass thru to calculate. I guess we no need it.
https://github.com/infor-design/enterprise/blob/c18041e1f5671684dc0adf250c8b9efeaef97eb5/src/components/charts/charts.js#L1105
