### ISSUE TITLE
Typography: Usage guidance inconsistent 

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise#7187]
**Describe the bug**
Guidance for typography [capitalization](https://design.infor.com/code/ids-enterprise/latest/typography#title-case-vs-sentence-case) is different from what is in UX writing style guide. The inconsistent sections should be removed and instead point readers to the [existing guidance](https://design.infor.com/product/ux-writing/capitalization). 

**Expected behavior**
- [**Title case vs sentence case**](https://design.infor.com/code/ids-enterprise/latest/typography#title-case-vs-sentence-case) documentation removed
- [**Be concise**](https://design.infor.com/code/ids-enterprise/latest/typography#be-concise) documentation removed
- Replace broken link in [**Usage**](https://design.infor.com/code/ids-enterprise/latest/typography#usage) with link to [UXW page](https://design.infor.com/product/ux-writing/introduction).  

**Additional context**
[IDS-654](https://jira.infor.com/browse/IDS-654)

**Comment by tmcconechy** [comment]
Yeah they changed this guidance ... thanks for pointing this out
