### ISSUE TITLE
Locale parseDate function accepts and modifies invalid time values 

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise#7191]
**Describe the bug**
The Locale parseDate function will accept certain invalid time values and return an incorrect result. Results in incorrect data.

**To Reproduce**
1. Open the enterprise demo.
2. Open the developer tools, go to the console and execute:

_Soho.Locale.parseDate('9:69 A', 'hh:mm a')_

3. Note in step 2 the invalid time value being inputted - 9:99.
4. Note that the result is not undefined as expected but _'... 09:00:00 GMT-0500 (Eastern Standard Time)'_

**Expected behavior**
The result should be 'undefined', not an incorrect value.

**Version**
 4.70.0

**Screenshots**
![image](https://user-images.githubusercontent.com/39279254/217660183-b367a60e-f646-4d63-8b25-f8579a2de22f.png)

**Platform**
 - M3 GLT
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 109.0.5414.120 (64-bit)

**Additional context**
This issue prevents me from coding a workaround for https://github.com/infor-design/enterprise/issues/7188

**Comment by tmcconechy** [comment]
@dmcodrum this is an option. by default it adds values to the date similar to how a date works. but there is a strict option...

```js
new Date(2023, 11, 19, 9, 69)
Tue Dec 19 2023 10:09:00 GMT-0500 (Eastern Standard Time)
```

```js
Soho.Locale.parseDate('9:69 A', 'hh:mm a')
// Wed Feb 01 2023 09:00:00 GMT-0500 (Eastern Standard Time)
Soho.Locale.parseDate('9:69 A', 'hh:mm a', true) // isStrict true
// undefined
```

**Comment by dmcodrum** [comment]
I swear I tried that and it only worked for dates. I just now tested it and it does indeed work. Thanks Tim.

**Comment by tmcconechy** [comment]
Cool closing then ~ wasnt sure if you were going to say it was being called inside some of our code in a wierd way but if this works for you will close
