### ISSUE TITLE
Personalize: All H1 are white in light theme for non-default color

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#7193]
**Describe the bug**
When the personalization color is set to anything but "default", ALL `<h1>` elements are white.

**To Reproduce**

1. Go to an example page that uses `<h1>` that is not inside a header, e.g https://design.infor.com/code/ids-enterprise/latest/demo/components/slider/example-tooltip-position.html?colors=0066D4
2. Notice that the heading is invisible
3. Change color to Default
4. See heading is now visible

**Expected behavior**
`<h1>` elements should be visible

**Version**

- ids-enterprise: 4.80.1 (issue was not present in 4.80.0)

**Screenshots**
Azure color:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/4991954/217786923-dc1d46b8-9d04-40dd-a71b-182339ec537d.png">

Default color:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/4991954/217786974-3664d3f1-2173-48e7-8f1c-4f8e588517d3.png">

Azure color (dark):
<img width="851" alt="image" src="https://user-images.githubusercontent.com/4991954/217787098-645b5895-229a-4806-8073-54d3602b3e85.png">

**Additional context**
Looks like a typo in the personalization styles?:

<img width="255" alt="image" src="https://user-images.githubusercontent.com/4991954/217787301-9a55e1df-4e41-4656-90a9-ab7576a18647.png">

**Comment by tmcconechy** [comment]
Yeah i was trying to include some of https://github.com/infor-design/enterprise/pull/7179/files the `h1` part is offf

**Comment by tmcconechy** [comment]
Fixed with [enterprise](https://github.com/infor-design/enterprise/issues/7173) making patches

**Comment by tmcconechy** [comment]
FYI issue will be patched in 4.80.2 / NG 14.8.2 ~ running shortly

**Comment by jbrcna** [comment]
QA Passed. verified in https://main-enterprise.demo.design.infor.com/components/slider/example-tooltip-position.html?colors=0066D4. tested in all themes and modes
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/56722184/217987051-fae96717-22b0-4955-8489-b7e2de7de63f.png">
