### ISSUE TITLE
Toolbar: Narrowing the browser, none of the other toolbar bar button go into overflow

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#7194]
**Describe the bug**
When a toolbar has a search field in it the other toolbar button won't go into the ... overflow/more menu. When there is not a search field things seem to work fine

**To Reproduce**
1. Go to /components/datagrid/example-custom-toolbar-flex.html
2. Narrow the browser
3. See issue where export icon does not go into the ... more menu and instead gets truncated with ellipsis

NOTE: in landmark we favor the title in the flex toolbar. That and adding more icons to the example might help see the issue better.

**Expected behavior**
While the search button should not ever go into overflow, the other toolbar button should go into overflow when the browser is narrowed.

**Version**
- ids-enterprise: 4.80.0

**Screenshots**
notice icons don't go into overflow when there is search field in the toolbar
![image](https://user-images.githubusercontent.com/4737815/217847657-44464de0-c422-4c51-b9f1-7ca15f247f7c.png)

notice w/o the search field in the toolbar icons do go into overflow
![image](https://user-images.githubusercontent.com/4737815/217848106-ed6df1b0-a4b2-4130-8249-b34a11883a68.png)

**Comment by pwpatton** [comment]
@tim I think we'll need a patch for this on 4.80

**Comment by tmcconechy** [comment]
I noticed this as well @yohannahbautista and @ericangeles ~ i think this regressed with the search field changes...

**Comment by tmcconechy** [comment]
Since this happened in 4.70 will not call this a regression. Most of the examples seem ok under https://main-enterprise.demo.design.infor.com/components/toolbar-flex

So possible edge case. If a full markup example can be provided we can add this in next sprint.

**Comment by pwpatton** [comment]
looks like this has been happening for quite a while At least since IDS 4.64.3 / IDS NG 13.5.3

[toolbar-markup.txt](https://github.com/infor-design/enterprise/files/10711098/toolbar-markup.txt)

To see this is action:

- To see this in action go to https://wiki.lawson.com/display/LMRK/Landmark+Server+LMQA1 to get password for admin1 user.
- open the link here to Recruiter https://gen-usspvwlmqa1.infor.com/hcm/RecruiterSelfService/page/XiLRCRequisitions?csk.showusingxi=true&menu=LRCRecruiter.XiRequisitions
- click the "workflow tab"
- narrow the browser so that the toolbar buttons look squished together

![image](https://user-images.githubusercontent.com/4737815/218196376-7f93bb59-0a7e-4744-9c1f-e64ba92aa95a.png)

If you remove the search field `<soho-toolbar-flex-section class="toolbar-section search">` in the dom then overflow starts working

![image](https://user-images.githubusercontent.com/4737815/218196849-3a7b54b6-481c-43f3-815e-18a2b2dd9ac2.png)

**Comment by tmcconechy** [comment]
Yeah the key to this might be that its different size buttons? Are you also sure its all toolbar flex everywhere? No "old toolbar"

**Comment by pwpatton** [comment]
I'm not sure since we only use flex boolbar.

**Comment by tmcconechy** [comment]
[sample.html.zip](https://github.com/infor-design/enterprise/files/10711309/sample.html.zip)

ok attaching the sample ~ this might reproduce the issue

**Comment by janahintal** [comment]
QA Passed. Now working fine in https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-search-before-buttonset.html?theme=classic&mode=light&colors=default 
https://www.screencast.com/t/Kd0XMXFRUQv
