### ISSUE TITLE
Column Stacked: Data chart and legend doesn't match up

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7199]
**Describe the bug**
Data chart doesn't match the legend.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/column-stacked/example-singular-get-selected.html?
2. Click on legends
3. See error

**Expected behavior**
Legend and data chart should match up.

**Version**

- ids-enterprise: 4.81.0-dev

**Screenshots**

https://user-images.githubusercontent.com/102151352/218076748-2c20ee49-00b3-4f38-a07f-2e90b77b785e.mov

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
@andriivarhanov can you see if https://github.com/infor-design/enterprise/pull/7389 fixed this. If not please take a look

**Comment by andriivarhanov** [comment]
@tmcconechy it looks like #7389 didn't fix it, I will take a look

**Comment by glenlieorillo** [comment]
Tested and passed.

Validated in: https://main-enterprise.demo.design.infor.com/components/column-stacked/example-singular-get-selected.html

https://user-images.githubusercontent.com/102151352/231130126-87f8e385-624e-4156-b80a-3d518ac6098d.mov
