### ISSUE TITLE
Export to Excel with Frozen columns enabled in Data Grid

### ISSUE THREAD

**Issue by sudhakaran-samadurai** [infor-design/enterprise#7200]
**Describe the bug**
If frozen column option is enabled in data grid the export to excel functionality is not exporting the Headers section of the frozen columns.

**To Reproduce**

create a data grid with frozen columns, select options in data grid and chose export to excel, the downloaded sheet will not have the header part of the frozen columns and the data part is aligned incorrectly.

**Expected behavior**
All the header column and data part should be exported correctly.

**Version**

- ids-enterprise: 10.1.0

**Comment by tmcconechy** [comment]
This is already fixed https://github.com/infor-design/enterprise/issues/5332 please try the latest version (your version is very old)

**Comment by sudhakaran-samadurai** [comment]
Thank you Tim i will use the latest version.
