### ISSUE TITLE
Button: Small Design Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7201]
**Describe the bug**
Some design QA issues as noted on https://jira.infor.com/browse/IDS-905

**To Reproduce**

1. Go to http://localhost:4000/components/button/example-index.html
2. Inspect the icons buttons

**Additional context**
https://jira.infor.com/browse/IDS-905

**Comment by glenlieorillo** [comment]
Tested and passed.

Verified in: https://main-enterprise.demo.design.infor.com/components/button/example-index.html

<img width="319" alt="image" src="https://user-images.githubusercontent.com/102151352/218916081-630811fa-4aa5-4d6e-8f5f-fd8dfee96df2.png">

<img width="319" alt="image" src="https://user-images.githubusercontent.com/102151352/218916126-0884d470-b8ad-42fb-96b3-7e01e22eb400.png">
