### ISSUE TITLE
Personalize: Secondary button in header is different from all others

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#7204]
**Describe the bug**
When a `.btn-secondary` or `soho-button="secondary"` button is inside a header (toolbar), it looks different from all other button types. Especially so in Light / HighContrast theme.

**To Reproduce**

1. Go to https://anhallbe.github.io/ids-repro/header-buttons
2. Notice the buttons in the header
3. Change the color theme to anything but "Default"
4. *See how the "Secondary Button" text is almost invisible.*
5. Hover the buttons
6.* See how "Secondary Button" behaves differently from the others* (not necessarily incorrect, but it appears like a bug.

**Expected behavior**
I guess it's fine that "secondary" buttons look different from the others. But the text should always be visible.

**Version**

- ids-enterprise: 4.80.2

**Screenshots**
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/4991954/218257678-33378c38-fdab-415e-80b2-aa5115fef811.png">

**Additional context**
https://jira.infor.com/browse/SCRMPORTALV2-5678

Repro code: https://github.com/anhallbe/ids-repro/blob/master/src/app/header-buttons/header-buttons.component.html

```html
<soho-header>
  <soho-toolbar-flex>
    <soho-toolbar-flex-section [isButtonSet]="true">
      <button soho-button="primary">Primary Button</button>
      <button soho-button="secondary">Secondary Button</button>
      <button soho-button="tertiary">Tertiary Button</button>
      <button soho-button="icon" icon="component" title="Icon Button"></button>
      <button soho-menu-button>Menu Button</button>
      <ul soho-popupmenu>
        <li soho-popupmenu-item>
          <a soho-popupmenu-label>Item 1</a>
        </li>
        <li soho-popupmenu-item>
          <a soho-popupmenu-label>Item 2</a>
        </li>
        <li soho-popupmenu-item>
          <a soho-popupmenu-label>Item 3</a>
        </li>
      </ul>
    </soho-toolbar-flex-section>
  </soho-toolbar-flex>
</soho-header>
```

**Comment by ericangeles** [comment]
@andriivarhanov can you take a look at this one?

**Comment by andriivarhanov** [comment]
@ericangeles sure, on it

**Comment by jbrcna** [comment]
working as expected. moving this ticket to done. thanks
https://main-enterprise.demo.design.infor.com/components/personalize/example-header-buttons.html?colors=1F9254#
<img width="991" alt="image" src="https://user-images.githubusercontent.com/56722184/222663744-54350dcf-e8a2-413b-b40b-10ab30f819d2.png">
