### ISSUE TITLE
Lookup: Width is not constrained by grid system

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#7205]
**Describe the bug**
Lookup inputs inside a grid (`.row`, `.three.columns` etc), are overflowing, and their width is not constrained by the surrounding column.

**To Reproduce**

1. Go to https://anhallbe.github.io/ids-repro/lookup-overflow
2. Resize the window
3. Notice how the Lookup inputs are overflowing

**Expected behavior**
Lookups should never be wider than their containing element.

**Version**

- ids-enterprise: 4.80.2
- ids-enterprise-ng 15.0.4

Seems like the bug was introduced by this PR (4.80): https://github.com/infor-design/enterprise/pull/7047

**Screenshots**
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/4991954/218419764-b7e57915-a031-485b-a5dc-b1d192414cc1.png">

**Platform**
 - Infor Application/Team Name: Infor OS & Homepages
 - OS Version: Windows, MacOS
 - Browser Name: Chrome, Safari

**Additional context**
Critical bug (see link for more screenshots/context): https://jira.infor.com/browse/SCRMPORTALV2-5706

PR that (probably) introduced the issue: https://github.com/infor-design/enterprise/pull/7047

Link to repro: https://github.com/anhallbe/ids-repro/blob/master/src/app/lookup-overflow/lookup-overflow.component.html

Minimal Repro code:
```html
<div class="row">
  <div class="three columns">
    <div class="field">
      <label soho-label>Lookup 1</label>
      <input soho-lookup />
    </div>
  </div>
  <div class="three columns">
    <div class="field">
      <label soho-label>Lookup 2</label>
      <input soho-lookup />
    </div>
  </div>
  <div class="three columns">
    <div class="field">
      <label soho-label>Lookup 3</label>
      <input soho-lookup />
    </div>
  </div>
  <div class="three columns">
    <div class="field">
      <label soho-label>Lookup 4</label>
      <input soho-lookup />
    </div>
  </div>
</div>
```

**Comment by tmcconechy** [comment]
For historical reasons the inputs are by default fixed width 300px however if you add the `form-responsive` class it should make all the inputs responsive. See example https://main-enterprise.demo.design.infor.com/components/form/example-inputs.html

I think that should solve the issue...

**Comment by anhallbe** [comment]
Although `input` and `textarea` both have `max-width: 100%` ( [input-style mixin](https://github.com/infor-design/enterprise/blob/0ac67c50ab8c4b5183b4a7d30392203e51c27a0e/src/components/input/_input-mixins.scss#L17) ) which prevents them from overflowing in this scenario. The `.lookup-wrapper` used to have this, but not anymore since it was removed in #7047.

**Comment by marknolaninfor** [comment]
If .lookup-wrapper had a width set to 100% does it work for all cases?

**Comment by tmcconechy** [comment]
we will look deeper but wanted to note there is a way to include inputs in the responsive grid that requires different classes https://main-enterprise.demo.design.infor.com/components/form/example-inputs.html

we should see if we broke something as mentioned tho
