### ISSUE TITLE
Builder: subtitle text not visible/readable

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7207]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/builder/example-builder-subtitle-test.html
2.  See error
3. Notice that the panel title & subhead is not visible

**Expected behavior**
panel title and subhead text should be visible/readable

**Version**

- ids-enterprise: v4.81.0-dev

**Screenshots**
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/56722184/218415739-a808de37-0f4f-433d-89bd-8cfb7e8aa040.png">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
I think should be fixed by showing long text as an ellipsis (with tooltip added in the example)

**Comment by tjamesallen15** [comment]
Can we test this again? @jbrcna 

Seems okay on my end. I can see the title and subtitle.
http://localhost:4000/components/builder/example-builder-subtitle-test.html

cc @ericangeles @tmcconechy

**Comment by jbrcna** [comment]
sure will do @tjamesallen15

**Comment by jbrcna** [comment]
https://main-enterprise.demo.design.infor.com/components/builder/example-builder-subtitle-test.html
moving this ticket to Done.
<img width="1642" alt="image" src="https://user-images.githubusercontent.com/56722184/232277092-fdb45762-f14b-4206-a49e-5bb2f374a7e8.png">
