### ISSUE TITLE
Header: Wizard texts are not visible in classic mode and misaligned 'x' button on search field

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#7209]
Header: Wizard texts are not visible in classic mode

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-wizard.html?theme=classic&mode=light&colors=2578a9#
2. Notice the texts are not visible 
3. Also test the search field in classic and responsive mode 
https://main-enterprise.demo.design.infor.com/components/header/example-header-with-multiple-buttons-and-searchfield.html?theme=classic&mode=light&colors=2578a9

**Expected behavior**
Wizard should be readable regardless of the mode

**Version**
IDS-4.81-DEV

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/218481354-78299939-4f29-4827-91f5-cbb7bdf6309d.png)
![image](https://user-images.githubusercontent.com/45757016/218474341-13a4623a-aa75-49d9-a0eb-6d046b95a7f6.png)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
N/A

**Comment by tmcconechy** [comment]
May be improved after recent fixes. Can you retest and confirm and fix if needed

**Comment by tjamesallen15** [comment]
Can we test this again? @janahintal. Seems okay on my end

http://localhost:4000/components/header/example-wizard.html?colors=2578a9&theme=classic&mode=light
http://localhost:4000//components/header/example-header-with-multiple-buttons-and-searchfield.html?colors=2578a9&theme=classic&mode=light

CC @ericangeles  @tmcconechy

**Comment by ericangeles** [comment]
I see another issue in here http://localhost:4000/components/header/example-header-with-multiple-buttons-and-searchfield.html

- Test it on smaller viewport
- Collapse button icon isn't visible

![Screen Shot 2023-04-12 at 9 08 03 PM](https://user-images.githubusercontent.com/8839327/231467492-07a5d119-ed35-4277-8948-9615f8762718.png)
