### ISSUE TITLE
Document how to include and use Enterprise

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#721]
**Is your feature request related to a problem? Please describe.**
In the course of the migration to github, we lost some documentation on how to use/apply Enterprise into a system.

**Describe the solution you'd like**

1. Relocate the development information
    - [ ] Clean up [docs/DEVELOPER.md](https://github.com/infor-design/enterprise/blob/master/docs/DEVELOPER.md)
    - [ ] Move any developer instructions from [./README](https://github.com/infor-design/enterprise/blob/master/README.md) into [docs/DEVELOPER.md](https://github.com/infor-design/enterprise/blob/master/docs/DEVELOPER.md)

1. Add implementation instructions
    - [ ] Clean up [./README](https://github.com/infor-design/enterprise/blob/master/README.md)
    - [ ] Add instructions on how to include/use the controls into [./README](https://github.com/infor-design/enterprise/blob/master/README.md)
    - [ ] Maybe somehow add a link to the `docs/` folder "for more info" or something

1. Update [docs/index.md](https://github.com/infor-design/enterprise/blob/master/docs/index.md) (@clepore)
    - [ ] Link back to [./README](https://github.com/infor-design/enterprise/blob/master/README.md)
    - [ ] Make it more of a general introduction to EP (as this is what's shown on the website)

1. Make sure the changes pass `npm run mdlint:docs`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tmcconechy** [comment]
Some thoughts...

1) point out the links if using angular
2) go through the process of 
- npm install
- what to include in the page
- adding a component
- point to the example

**Comment by tmcconechy** [comment]
Seems like this should have been closed.
