### ISSUE TITLE
Hyperlink: Color on personalize-actionable is incorrect for white color in new-contrast theme and new-light theme

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#7212]
**Describe the bug**
Hyperlinks seems fine for all colors except white when in new theme/contrast mode and light mode

**To Reproduce**
1. Put attached example in place in component/personalize
2. run http://localhost:4000/components/personalize/example-form-landmark2.html?theme=new&mode=contrast
3. notice hyperlinkg color is too dark

**Expected behavior**
Hyperlinks color should use contrast-mode hyper link color
Notice it's using some dark color in a rule from personalize.scss

**Version**

- ids-enterprise: 4.80.2

**Example**
[example-form-landmark2.html.txt](https://github.com/infor-design/enterprise/files/10726335/example-form-landmark2.html.txt)

**Screenshots**
new-contrast
![image](https://user-images.githubusercontent.com/4737815/218574188-85271405-2b6e-414a-8b9f-d08f2d160f92.png)

new-light
![image](https://user-images.githubusercontent.com/4737815/218784403-a249480b-35b2-4987-a10a-ac18f51cabd4.png)

**Comment by tmcconechy** [comment]
This issue should be fixed with https://github.com/infor-design/enterprise/issues/7211
Since its the same example. The links and text and tabs are all not respecting the color...

Can you pick this one up @andriivarhanov ?

**Comment by tmcconechy** [comment]
FYI ~ i pushed the example app/views/components/personalize/example-form-landmark2.html while checking this out

**Comment by andriivarhanov** [comment]
@tmcconechy on it

**Comment by glenlieorillo** [comment]
Working as expected.

**New - High Contrast**
![image](https://user-images.githubusercontent.com/102151352/220228173-c422c459-82ce-4481-8cbb-b2ceb5b77068.png)

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/220228888-3e70cddf-7939-4bba-8dcc-e135c12a7fcf.png">


**New - Light**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/220228688-7590548f-423c-4d07-b319-5fa57338806c.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/220228829-6ec1940e-2a51-41b8-9564-90c7d4bfb1af.png">
