### ISSUE TITLE
Appmenu: x icon is too bright when hovered

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7214]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-resizable-menu.html?
2. Type a text in searchfield
3. Hover over the 'x' icon

**Expected behavior**

**Version**

- ids-enterprise: v4.81.0-dev

**Screenshots**
<img width="527" alt="image" src="https://user-images.githubusercontent.com/56722184/218698999-15c1ddad-927b-409f-bc71-a2c5b835be53.png">

**Platform**
All

**Additional context**

**Comment by yohannahbautista** [comment]
Hello, the bright hover looks to be removed now
<img width="531" alt="Screen Shot 2023-03-08 at 9 54 43 AM" src="https://user-images.githubusercontent.com/85279127/223599341-986bb5fc-1acc-4466-85e6-7144d4356cea.png">

**Comment by jbrcna** [comment]
thanks @yohannahbautista . moving this to done.

**Comment by tmcconechy** [comment]
Now fixed https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-resizable-menu.html
