### ISSUE TITLE
Button: Design QA ~ Header icon buttons are not azure

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7215]
**Describe the bug**
Noticed that the icon buttons on the header do not turn azure on hover like the other icon buttons do. This is inconsistent. Also on safari there is a minor color change issue...

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/button/example-index.html
2. Hover the .. button -> see its not azure
3. Hover the other icons buttons -> see it is azure
4. Open safari and hover the action icon button and then "dehover" it on https://main-enterprise.demo.design.infor.com/components/button/example-index.html?theme=new&mode=dark&colors=0066D4 notice it looks like this:

<img width="117" alt="bug" src="https://user-images.githubusercontent.com/814283/218772489-e79953a5-b253-445b-8429-a796d87cfc22.png">

**Expected behavior**
- As per https://www.figma.com/file/VcRDGPFqlp3MJ46mEWkGPf/Buttons?node-id=701%3A1222&t=atylm2Dn1R7mq64U-0 the icons buttons should be azure in the header as well on hover
- check all 3 themes again on both pages above
- **make sure changing colors still works as is now and classic is not broken**

**Additional context**
Maks - MS Teams

**Comment by tmcconechy** [comment]
no longer 100% relevant ~ so closing

**Comment by jbrcna** [comment]
QA Failed.
when using `dark mode` buttons are off in `all colors but default`
when using `light | high contrast` buttons are off in `all colors but default & alabaster`

**Comment by tmcconechy** [comment]
@jbrcna can we make a new issue for that? It could be the example. Thanks!

**Comment by jbrcna** [comment]
sure @tmcconechy  here's the new issue. https://github.com/infor-design/enterprise/issues/7406

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.  @jbrcna open new issue. https://github.com/infor-design/enterprise/issues/7406.
