### ISSUE TITLE
Tabs: Color changes allowing screen to be displayed behind sticky tabs

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#7217]
**Describe the bug**
personlized tabset in new-dark theme default color - background color is transparent allowing screen to be displayed behind sticky tabs.

This happens only when the tabset has .is-personalizable.header-tabs classes set.

**To Reproduce**
1. Put attached example in place in component/personalize
2. run http://localhost:4000/components/personalize/example-form-landmark2.html?theme=new&mode=dark&color=default
3. scroll the browser so that the tab content scrolls under the sticky tabs
4. notice tab content is displaying behind the sticky tabs

**Expected behavior**
Tab content should not display behind sticky tabs.

**Version**

- ids-enterprise: 4.80.2

**Example**
[example-form-landmark2.html.txt](https://github.com/infor-design/enterprise/files/10734308/example-form-landmark2.html.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/4737815/218790086-2748e296-310b-4317-a745-bb8ff57cd31f.png)

**Comment by glenlieorillo** [comment]
Working as expected. Moving this ticket to Done.



https://user-images.githubusercontent.com/102151352/220229942-dffe23cc-778a-4f48-a97d-0b116a8995e8.mov
