### ISSUE TITLE
Personlized: Form in new-dark theme default color - foreground color is too dark

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#7218]
**Describe the bug**
personlized form in new-dark theme default color - foreground color is too dark

**To Reproduce**
1. Put attached example in place in component/personalize
2. run http://localhost:4000/components/personalize/example-form-landmark2.html?theme=new&mode=dark&color=default
3. Notice the dark foreground color

**Expected behavior**
foreground color when personalized should look like the form when it's not personlized.

**Version**

- ids-enterprise: 4.80.2

**Example**
[example-form-landmark2.html.txt](https://github.com/infor-design/enterprise/files/10734597/example-form-landmark2.html.txt)

**Screenshots**
From example
![image](https://user-images.githubusercontent.com/4737815/218797346-c6e20b8b-86d1-4c08-9f87-7e53aa1c0af2.png)

**Comment by tmcconechy** [comment]
is this the same issue as https://github.com/infor-design/enterprise/issues/7211 ?

**Comment by pwpatton** [comment]
@andriivarhanov @tmcconechy this also happens in the subtle theme in dark mode

**Comment by glenlieorillo** [comment]
Working as expected.

**New - Dark**
![image](https://user-images.githubusercontent.com/102151352/220230307-45089627-646d-471f-861a-e64a4adaefa5.png)

**Classic - Dark**
![image](https://user-images.githubusercontent.com/102151352/220230502-216506f2-54df-47f5-a098-33505d9cac12.png)
