### ISSUE TITLE
is-personalize disabled tabs do not look disabled in dark mode default color

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#7219]
**Describe the bug**
personalized form in new-dark theme default color - disabled tabs do not look disabled 

**To Reproduce**
1. Put attached example in place in component/personalize
2. run http://localhost:4000/components/personalize/example-form-landmark2.html?theme=new&mode=dark&color=default
3. Notice 2nd and 4th tabs should be disabled 

**Expected behavior**
disabled tabs should look disabled

**Version**
- ids-enterprise: 4.80.2

**Example**
[example-form-landmark2.html.txt](https://github.com/infor-design/enterprise/files/10735153/example-form-landmark2.html.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/4737815/218812581-341f9905-85cb-4bd0-90ff-d47b3a8c4602.png)

**Comment by tmcconechy** [comment]
is this the same example as the other 4 issues?

**Comment by pwpatton** [comment]
@andriivarhanov @tmcconechy this also happens in the classes theme

![image](https://user-images.githubusercontent.com/4737815/219106333-fa69bf74-e8d2-428f-bdf7-48c50609af72.png)

**Comment by jbrcna** [comment]
QA Passed
verified in https://main-enterprise.demo.design.infor.com/components/personalize/example-form-landmark2.html?theme=new&mode=dark&colors=0066D4
<img width="1645" alt="image" src="https://user-images.githubusercontent.com/56722184/220319221-2e8769b0-7eea-4b34-9ee8-745bc5d0c31e.png">
