### ISSUE TITLE
Button: secondary menu text is not readable

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7221]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/button/example-as-link.html
2. Switch to High contrast / dark mode
3.  See error

**Expected behavior**

**Version**

- ids-enterprise: v4.81.0-dev

**Screenshots**
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/56722184/218941491-51ba1dd4-6461-4dc1-b2e4-7880c6e9eae9.png">
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/56722184/218941529-88cda35d-48a2-4cd4-8440-74c274765d75.png">

**Platform**
All

**Additional context**
this EP is also affected . https://main-enterprise.demo.design.infor.com/components/button/example-with-icons.html?theme=new&mode=contrast&colors=8D0B0E

**Comment by tmcconechy** [comment]
May be a demo app issue. Looks like we need to apply the same style for `a` tags styled like buttons. That we have on https://main-enterprise.demo.design.infor.com/components/button/example-index.html?theme=new&mode=contrast&colors=003876 (third button row)

**Comment by jbrcna** [comment]
working as expected. moving this ticket to done
https://main-enterprise.demo.design.infor.com/components/button/example-as-link.html
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/56722184/223312622-e84902dc-8553-4a82-ae1c-2c5de8046478.png">

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/56722184/223312741-21dae8ef-78a6-4466-9a19-113c63157a43.png">
