### ISSUE TITLE
Image: Allow resizing avatars (user images), make their sizes consistent

### ISSUE THREAD

**Issue by bartlomiej-k** [infor-design/enterprise#7222]
**Is your feature request related to a problem or use case? Please describe.**
IDS Enterprise library contains Image component which allows creating user avatars using images or initials by applying CSS classes only. Both avatar types are fixed-size, they also differ in their size with image avatars being fixed to 50x50px and initial avatars having a size of 4.8x4.8rem. The latter means that when user changes their browser font size, initials avatar can grow and misalign with image avatars, so both types cannot be used at the same time. Even with default settings (which sets 1rem to 10px in my case), there is a difference between these two (48x48px vs 50x50px). Also, user status positioning is fixed using px unit, so status icons shouldn't be used with initials as they do not respect initials size.

Because of the fixed status icon positioning and using font-size and line-height properties to center text in initials avatar, it's difficult to resize any avatar component - it requires a lot of calculations to preserve relative sizes and positions of avatar and status icon. An example of such calculations can be found in additional context section. 

All of that means that usage of IDS avatars is very limited.

**Describe the solution you'd like**
- Avatars should not use fixed numbers to position elements that are relative to them, so they can be easily resizable by applying another CSS class or setting a CSS variable to a desired size. For example, setting avatar's width and height to 30px would not only change size of the image/initials, but also preserve position of the icon and scale it down. Similarly, setting a dedicated CSS variable (let's say `--ids-size-avatar`) would recalculate all of these sizes.
- Both image and initials avatars should use the same size unit, so they can be used together in the same component, making initials a placeholder/substitution in case user does not choose any image as their avatar.
- If avatars become a separate jQuery component, we would need it to be wrapped in Angular component as we use Enterprise-ng library in our project.

**Describe alternatives you've considered**
There are two alternatives we've considered:
- Applying a class to the avatar component that would set width, height, font-size, line-height of the avatar and margins of the status icon according to calculated ratios and desired avatar size (example below)
- Creating a custom component that would be used internally - basically reimplementing what the IDS Enterprise library provides, but adding it more flexibility

**Additional context**
JSFiddle with example of current workaround: https://jsfiddle.net/4wx832oj/32/
Infor Application/Team Name: Infor WFM

**Comment by tmcconechy** [comment]
So maybe just 3 sizes of https://main-enterprise.demo.design.infor.com/components/images/example-photos.html by class?
Think we could do that. This could also be a good contribution 👍🏻 Something like no-class, "small", "medium", "large" ect

BTW We have the sizes on the new component but not for the avatar

**Comment by talkaboutdesign** [comment]
This is also something we told Olga and IDS team about. I think Olga had done some work on identifying what default sizes might be.
