### ISSUE TITLE
Build: Cannot Run the Build on Windows

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7228]
**Describe the bug**
Since making changes on #6634 the build system wont work on windows. The problem seems to be the 

```
npm run clean
```

Which errors with "Error: Illegal characters in path."

**To Reproduce**

1. On a windows machine 
2. Clone the repo
3. Cd to the cloned project
4. `npm run start` or more isolated `npm run clean`

**Expected behavior**
Should work

**Additional context**
Seems to be https://github.com/isaacs/rimraf/issues/249

**Comment by tmcconechy** [comment]
cc @danielortiz1982 / @EdwardCoyle

**Comment by awbuboltz** [comment]
Could the docs dirs be removed instead of targeting just the html files: `"clean:docs": "rimraf app/docs && rimraf docs"`? What is being preserved that needs to stay in those directories?

**Comment by tmcconechy** [comment]
@awbuboltz try and checkout the PR basically

a) the app/docs is whats cleaning and thats an old old rarely used thing
b) app/docs is empty / seems to have nothing to keep and is only added if `npm run documentation` is run. I think it had something at one point but doesnt seem to now
