### ISSUE TITLE
Ids ActionSheet - Add documentation to site map

### ISSUE THREAD

**Issue by LilBiggs** [infor-design/enterprise#7230]
The IDS Action Sheet is not currently part of the component documentation on design.infor.com.

1. Go to design.infor.com
2. Click on Components
3. Notice in the Components section, Action Sheet does not exist

**Expected behavior**
See Action Sheet documentation and examples

**Version**
- ids-enterprise: v4.80

**Comment by tmcconechy** [comment]
Should be ok when we deploy 4.81.0 in a few weeks
