### ISSUE TITLE
Widget Counts: Make an example showing it in a colored banner

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7234]
**Describe the Feature**

We want to ensure that the newer counts work in a banner widget. So take the example
and implement a copy of this page https://main-enterprise.demo.design.infor.com/components/personalize/test-classes-short.html?colors=BB5500 but replace the counts with these ones https://design.infor.com/code/ids-enterprise/latest/demo/components/counts/example-widget-count.html?colors=BB5500

We may need some design feedback on color schemes.

**Expected behavior**
A new example where you can change colors that looks good with widget counts.

**Additional context**
Email / HomePages

Example should look similar to this one. But make sure the counts are centered and the text is centered and everything looks as good as ours  https://design.infor.com/code/ids-enterprise/latest/demo/components/counts/example-widget-count.html?colors=BB5500

![image](https://user-images.githubusercontent.com/814283/219681080-ee67981a-0d18-46d5-ba59-88153de4d30c.png)

**Comment by tmcconechy** [comment]
Reopen for design feedback..

**Comment by hey-yall** [comment]
Created partner Jira ticket in Infor Design System (IDS) project -- [IDS-959](https://jira.infor.com/browse/IDS-959)

**Comment by tmcconechy** [comment]
as mentioned in the call after the solution to this for now is to make the counts appear in an example like this https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html

So they appear only in the hero image. On that darker color. Can you please change http://localhost:4000/components/counts/example-header.html so that it shows that hero widget with counts in instead?

Thanks @yohannahbautista

**Comment by jbrcna** [comment]
QA Failed. 
https://main-enterprise.demo.design.infor.com/components/counts/example-hero.html?theme=classic&mode=light&colors=ffffff
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/56722184/233496193-5961ff21-f3f7-430c-b338-699abf450329.png">

https://main-enterprise.demo.design.infor.com/components/counts/example-hero.html?theme=classic&mode=contrast&colors=ffffff
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/56722184/233496277-aa810293-5c0e-4e21-93dc-564d4656de84.png">
