### ISSUE TITLE
DataGrid: Frozen column with Column Group option has bug while exporting to excel

### ISSUE THREAD

**Issue by sudhakaran-samadurai** [infor-design/enterprise#7236]
**Describe the bug**
While trying to export to excel the data grid with Frozen column enabled and data grid has column group, provides wrong data in the header section, attached the screenshot for reference. And this happens only when we enable both column group and frozen column.

**To Reproduce**
1. Create a Data grid with column group and frozen column 
2. Export the data to excel
3. The column and column group exported to excel will same data with wrong alignments.

**Expected behavior**
The column group and columns should have the same value in the exported excel as in the data grid.

**Version**
- ids-enterprise-ng: 15.0.4

**Screenshots**

Data grid:
<img width="930" alt="image" src="https://user-images.githubusercontent.com/35565173/219552987-f016d0b8-d26c-4fc7-a775-584adb41e1be.png">

Excel:
<img width="940" alt="image" src="https://user-images.githubusercontent.com/35565173/219553083-aad7bad2-7891-421e-8fd3-db9c7d88095f.png">

**Platform**
 - Device : Laptop computer
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 110.0.5481.96 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
This enhancement is slightly more feasible than #7235 - I think that frozen columns does already work but we do not include the grouped headers. We would have to figure out how thats possible in excel.

Keep in mind the current export uses CSV / simple table. So would need to first work with the full excel API to achieve it https://github.com/infor-design/enterprise-wc/issues/153

No promises possible on this one.
