### ISSUE TITLE
Autocomplete search term that contains a value not Alphanumeric does not work

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#724]
We are using the autocomplete to select a UNC path on a remote server, \\Server\Share, and the service is returning the filtered values, but then the control excludes them.

**To Reproduce**
1. http://master-enterprise.demo.design.infor.com/components/autocomplete/test-xss-security.html
2. Type in "\\"
3. Check the term that is passed to the openList function 

**Expected behavior**
The term "\\" is passed to the openList function.

**Platform**
All

**Additional context**
The xss security on the searchTerm is stripping the double backslash.
return dfd.resolve(xssUtils.ensureAlphaNumeric(searchTerm), response);

xssUtils.ensureAlphaNumeric('\\') returns an empty string.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.

**Comment by tmcconechy** [comment]
This issue should have been marked fixed/closed
