### ISSUE TITLE
Editor: Dirty tracking doesn't trigger when you go to HTML view first before editing 

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#725]
**Describe the bug**
In Editor component, dirty tracking doesn't trigger when you go to HTML view first before editing.

**To Reproduce**
1. Go to http://4100-beta1-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html
2. Click the HTML view in the toolbar
3. Go back to Visual view
4. Type "test dirty tracker" in the Editor
5. Dirty tracker will not be displayed

**Expected behavior**
Dirty tracker should be displayed 

**Screenshots**
![editor_nodirty2](https://user-images.githubusercontent.com/39508864/44903496-49f2e480-ad3f-11e8-9b25-978f67ec8b5c.gif)

**Platform**
 - All devices, OS and browsers

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
Can no longer reproduce this issue following the steps on https://master-enterprise.demo.design.infor.com/components/editor/example-index.html
