### ISSUE TITLE
Datagrid: Strange behaviour when sorting groupable datagrid

### ISSUE THREAD

**Issue by albinpettersson** [infor-design/enterprise#7253]
**Describe the bug**
When filtering a groupable data grid with multiple pages the groups remain on their original pages rather than being moved to the front. Pressing enter a second time after applying the filter temporarily shows the current page correctly, but does not fix the page counter. Paging after pressing enter a second time results in the results being displayed incorrectly again.

**To Reproduce**
See https://github.com/albinpettersson/grid-tests (private)

1. Create a paging, groupable and filterable datagrid
2. Make sure the datagrid has enough data to have multiple pages
3. Run the web application and apply a filter to your data grid.
4. Watch the grid not move the groups that remain after filtering to the front.

**Expected behavior**
The data grid should behave more like an ungroupable data grid, where any remaining lines are moved to the front rather than remaining on their original pages. The behaviour after pressing enter a second time is more in line with the expected behaviour, although the page display at the bottom should also update, and the result should persist when paging.

**Version**
- ids-enterprise-ng: v14.4.3

**Screenshots**
Unfiltered:
<img width="346" alt="2023-02-22 14_35_39-" src="https://user-images.githubusercontent.com/94176389/220635794-bc9ad14b-1f96-4aec-afdf-78a692857005.png">
<img width="347" alt="2023-02-22 14_35_45-" src="https://user-images.githubusercontent.com/94176389/220635821-3b99b7e3-1804-42e8-8684-f4cb942b3d53.png">

Filtered:
<img width="347" alt="2023-02-22 14_35_54-" src="https://user-images.githubusercontent.com/94176389/220635847-9b2b5c56-1150-4978-8fb3-be363da3dcdd.png">
<img width="347" alt="2023-02-22 14_36_20-" src="https://user-images.githubusercontent.com/94176389/220635865-804f45cb-c2ec-47ff-8604-243d9b158b5e.png">

After pressing enter again (The second page is empty because only 5 groups remain after filtering):
<img width="348" alt="2023-02-22 14_43_22-" src="https://user-images.githubusercontent.com/94176389/220637560-434a0d49-819b-404a-8d59-f689279e7162.png">
<img width="347" alt="2023-02-22 14_44_12-" src="https://user-images.githubusercontent.com/94176389/220637584-a644579e-b80b-4ffe-ae2d-f5b781064110.png">

**Platform**
 - Device: PC
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Version 110.0.5481.104 (Official Build) (64-bit)

**Additional context**
I'm using the package inside of an app created with https://github.com/infor-cloud/m3-h5-sdk

**Comment by tmcconechy** [comment]
@albinpettersson can you make this example refered too. It seems a bit specific and not sure we would get it right

**Comment by albinpettersson** [comment]
Created a private repo that shows the issue and invited you as a collaborator as I'm not quite sure sure to which extent I am allowed to publically share projects created using the H5 SDK.
