### ISSUE TITLE
Color: Status Colour in different modes

### ISSUE THREAD

**Issue by angelajyc** [infor-design/enterprise#7254]
**Describe the bug**
The status colours stay the same in the different modes: Light, Dark and High Contrast. However, in the notification banner, the icon transparency/colour changes. 

If the status colours are meant to stay the same, I would like to find out the difference between the regular colours and the status colour. 
![Screen Shot 2023-02-22 at 2 00 14 PM](https://user-images.githubusercontent.com/96130460/220732039-fbec6d5e-a648-4b3a-bdad-9900299d53d0.png)
![Screen Shot 2023-02-22 at 2 01 16 PM](https://user-images.githubusercontent.com/96130460/220732168-4866566f-666a-4df6-a1a0-88b923c20f56.png)

**To See the Issue**
https://design.infor.com/code/ids-enterprise/latest/demo/components/colors/example-index?theme=new&mode=dark&colors=0066D4
vs
https://design.infor.com/code/ids-enterprise/latest/demo/components/notification/example-index?theme=new&mode=dark&colors=0066D4

**Comment by tmcconechy** [comment]
Thanks. I would use the ones on https://design.infor.com/code/ids-enterprise/latest/demo/components/colors/example-index?theme=new&mode=dark&colors=0066D4 for now. But need to confirm. And fix the inconsistencies in the components

**Comment by tmcconechy** [comment]
Late but stale bot was about to close this and i saw it 🤖 

This may be more answerable by looking at the new tokens here:
https://github.com/infor-design/enterprise-wc/blob/main/src/themes/default/ids-theme-default-colors.scss#L99-L105

Many of the alert colors has a range of colors. We cant use just one color across all themes so it would correspond to these as an example: 
https://github.com/infor-design/enterprise-wc/blob/main/src/themes/default/ids-theme-default-colors.scss#L99-L105

https://main.wc.design.infor.com/ids-color/palette.html

This may need a design update but for now it is how it is
