### ISSUE TITLE
Datagrid: Columns disappear when resizing them and then refreshing the datagrid

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#7259]
**Describe the bug**
This is a little difficult to describe in text, but the steps to reproduce and the gif below should hopefully make it understandable. Anyway, the general issue is that columns disappear when resizing them to very large and small sizes and then refreshing the datagrid.

**To Reproduce**
This can be reproduced in several ways, but the below steps are for one specific scenario to avoid making the steps too complex.

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/test-paging-trigger
2. Grab the leftmost resizing handle and then keep dragging to the right until the horizontal scrollbar appears and all columns except "Product Id" are dragged out of view.
3. Scroll to the right and then grab one of the other resizing handles (**not** the leftmost one) and start dragging to the left until it stops.
4. **Optional:** Repeat step 3 as many times as you want.
5. Click "Trigger Refresh".
6. Notice that one or more columns (depending on which ones you resized) completely disappear.

**Note:** this can be repeated until there's only one column left.

**Expected behavior**
Refreshing the datagrid shouldn't make any columns disappear.

**Version**
- ids-enterprise: 4.80.1

**Screenshots**
![resize_columns](https://user-images.githubusercontent.com/63045013/221135767-3a870385-f23c-41f5-bf71-e40758717c5a.gif)

**Platform**
 - Infor Application/Team Name: OS Portal / Homepages

**Comment by tmcconechy** [comment]
To avoid the situation, you might be able to try to set a maxWidth for the column. Just an idea for a workaround. It shouldnt loose the column. My guess is one column is getting set to zero.

Another idea is to add the resetColumns to grid button if needed. These resizing issues can be pretty hard to fix.
