### ISSUE TITLE
Lookup: Cannot scroll the list when the modal is fullsize

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#7260]
**Describe the bug**
It's not possible to scroll the list when a lookup is opened in small enough browser window widths (e.g. on mobile) to make the modal open in fullsize.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/lookup/example-index
2. Click on one of the lookups
3. Decrease the browser window width until the modal becomes fullsize.
4. Decrease the browser window height until not all items are visible in the list.
5. Notice that no vertical scrollbar appears.

**Expected behavior**
It should be possible to scroll the list when the modal is in fullsize.

**Version**
- ids-enterprise: 4.80.1

**Screenshots**
![image](https://user-images.githubusercontent.com/63045013/221147407-27faa8b9-6af5-47b7-aee3-c27dac991856.png)

**Platform**
 - Infor Application/Team Name: OS Portal / Homepages

**Comment by tmcconechy** [comment]
This might be a example bug. I think the only way to fix it is to make the datagrid have a height or min and max height with css.
