### ISSUE TITLE
Themes: Contrast Mode Background Color Changed

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7261]
**Describe the bug**
Possibly as a result of header color changes #7022 the contrast mode background color is white now. Not slight grey like it used to be. Need to check if this is OK or Better to keep it how it was.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-index.html?theme=new&mode=contrast&colors=default
2. Compare to https://4660-enterprise.demo.design.infor.com/components/header/example-index.html?theme=new&mode=contrast

**Expected behavior**
Header color should be slate 01, background color should be slate 01 in contrast theme..

**Additional context**
Could argue this is ok but it is a UI change that could be noticed. In Web components i made it slate 01 for now

**Comment by jbrcna** [comment]
QA Passed.
https://main-enterprise.demo.design.infor.com/components/header/example-index.html?theme=new&mode=contrast&colors=default
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/56722184/223952020-bd3e66ca-d0e3-4fbb-a191-3cad1cb9b021.png">
