### ISSUE TITLE
Field filter: short icon not centered

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7264]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-filter/example-short.html
2. hover over the timepicker icon
3. See error

**Expected behavior**
<img width="322" alt="image" src="https://user-images.githubusercontent.com/56722184/221463954-757f9a8f-546f-484e-97ac-c6da2c6219b4.png">

**Version**

- ids-enterprise: v4.81.0-dev

**Screenshots**
<img width="365" alt="image" src="https://user-images.githubusercontent.com/56722184/221464094-a410196c-5e8d-4d60-bf7c-92212494ce8f.png">

**Platform**
Mac chrome & Edge

**Additional context**

**Comment by yohannahbautista** [comment]
Hello, checking the example and it may have been fixed
<img width="766" alt="image" src="https://user-images.githubusercontent.com/85279127/222056751-64975ad2-0e48-4345-8f03-501b49f1c763.png">

**Comment by jbrcna** [comment]
edge and chrome now looks okay. However, in safari icon is not centered. let me know if I need to file a separate ticket. thank you
`safari`
<img width="340" alt="image" src="https://user-images.githubusercontent.com/56722184/222385566-91b94362-f4a5-43d8-93c0-5bb9ae4e0aee.png">

**Comment by ericangeles** [comment]
@yohannahbautista can you take a quick look? Am also seeing the issue in Safari.

**Comment by jbrcna** [comment]
hello, the hover is gone now. see below screenshot. thanks
<img width="510" alt="image" src="https://user-images.githubusercontent.com/56722184/222662894-b50106f4-c8c7-4910-ab24-524587cc5a98.png">

**Comment by jbrcna** [comment]
hover highlight is now displayed in safari.
<img width="478" alt="image" src="https://user-images.githubusercontent.com/56722184/223952933-5a7dc58b-3b94-4194-b3e5-5d8e6ca6ca4c.png">
