### ISSUE TITLE
Question to scroll action in datagrid

### ISSUE THREAD

**Issue by sobirkma** [infor-design/enterprise#7267]
I developed a datagrid with about 12 rows.
Once I click a row (e.g. in the middle of the datagrid), the row should be moved to the top (first position) of the datagrid.
That means a scroll action should be done.

How can I develop this?

<img width="445" alt="Picture1" src="https://user-images.githubusercontent.com/102984723/221569402-c9874c33-f925-4949-8955-644de62f422f.png">
<img width="332" alt="Picture2" src="https://user-images.githubusercontent.com/102984723/221569407-fe53291a-525c-4f09-a738-71e16bb43688.png">

**Comment by sobirkma** [comment]
Dear tmcconechy, thank you for your answer.

The order of the rows should the same as before.
What I want is to move the whole data so, that the selected row (which is marked blue in the first picture) is on the first position of datagrid afterwards. 
All rows which are above of the select row  -> should disappear.
All rows which are below of the selected row  -> will go upward.

It is the same as if I use the mouse to scroll a little bit down.

**Comment by tmcconechy** [comment]
ok sounds a little strange but sounds like you can do this by just changing the data in the dataset (JS array coding). Then set the new array on the datagrid and it will refresh

There is also api commands like `addRow` and `removeRow` that could be used

**Comment by sobirkma** [comment]
Dear Tim,
I am sorry, but there ist still a misunderstanding. I don't want to change the dataset.

I want to click to a row in the middle of the datagrid. Then the whole "data block" should be moved (scrolled) upwards, until the selected row is on the first position in the datagrid. The rows which are above of the selected row, will be scrolled out of the visible part of datagrid and will be not visible afterwards.
From bottom up new rows will be scrolled into the visible part of datagrid.

I found a page in the web which describes the behaviour which we want to have. Perhaps this helps to understand my question.

https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridview.firstdisplayedscrollingrowindex?redirectedfrom=MSDN&view=windowsdesktop-7.0#System_Windows_Forms_DataGridView_FirstDisplayedScrollingRowIndex

Thank you in advance and best regards!

**Comment by tmcconechy** [comment]
Ok, Why would you need to do that? I think you could hack it up by calling scrollTop on the correct HTML element. But it doesn't seem like a great idea to just change the scroll position for the user. Could be confusing or look jumpy.

Maybe with this?
```
$('#datagrid').data('datagrid').setActiveCell(0, 0, true)
```

i.e. setting active cell and focusing it

**Comment by sobirkma** [comment]
Dear Tim,
thank you for your answer.
The reason behind this: once a line in the datagrid is clicked, a card with detailed information in lower part is opened and (maybe) the selected line disappears behind this card. 
The why we want to move this line to first viewable position in datagrid.

I tested setActiveCell(). It focus the line, but doesn't move it within datagrid.
Perhaps scrollTop is the right one. Can your please give me an example, how to use it?

Thank you in advance!

**Comment by tmcconechy** [comment]
Sorry, I have no example of that. I still dont get the use case. Can you make an example that shows the use case very clearly?
Perhaps i can update it https://stackblitz.com/edit/ids-quick-start-1480?file=src%2Fapp%2Fapp.component.ts

Something like this https://main-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection.html ? Except a card on the bottom?

I think what your trying to do sounds odd. So i would try and avoid it

**Comment by sobirkma** [comment]
Dear Tim,
thank you for your answer. I will prepare a video to show our user case. Because tomorrow is no working day for me, I will come back to you next week.

**Comment by tmcconechy** [comment]
Ok, this is probably a better question for the support channel. Will close this for now.
