### ISSUE TITLE
Tabs Header: focus not properly placed, close button color issue

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7273]
**Describe the bug**
_Issue 1_: Focus on the Add button is not properly placed.
_Issue 2_: Close button in the added tab is not visible

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-header/example-add-tab-button.html
2. Click on Add button
3. Notice the focus on Add button (_Issue 1_)
4. Hover the added tab, notice the close button (_Issue 2_)

**Expected behavior**
Focus on the Add button should be correctly placed. The close button should be visible.

**Version**

- ids-enterprise: 4.81.0-dev

**Screenshots**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/221834234-8509cb91-4a9d-4a6b-85fc-a5a0004f8661.png">

https://user-images.githubusercontent.com/102151352/221835187-15976d09-ad3d-49b5-912f-986bdb0e4cd2.mov

**Platform**
 - All major browsers

**Comment by tjamesallen15** [comment]
I'll work on this @tmcconechy  and @ericangeles

**Comment by glenlieorillo** [comment]
Tested and passed.

https://main-enterprise.demo.design.infor.com/components/tabs-header/example-add-tab-button.html

https://user-images.githubusercontent.com/102151352/226296860-e23fc640-b873-4dd0-86f4-f201e5a8a304.mov
