### ISSUE TITLE
Notification Banner throw errors when close. 

### ISSUE THREAD

**Issue by LinweiW** [infor-design/enterprise#7276]
**Describe the bug**
Notification Banner close function will cause error when try to close an already closed notification. 

**To Reproduce**
https://stackblitz.com/edit/ids-quick-start-1501-zpv7qo?file=src%2Fapp%2Fapp.component.ts
1. Click on Close All Notification (Error in console)

**Expected behavior**
No Error in console. The function should handle closing notifications which are already closed. 

**Additional context**
All close method seems have same issue which cannot handle closing a not existing notification.

**Comment by tmcconechy** [comment]
@LinweiW i tried your steps but did not see any error. Can you correct the steps or example..

1. went to https://stackblitz.com/edit/ids-quick-start-1501-zpv7qo?file=src%2Fapp%2Fapp.component.ts
2. clicked add notifcation a few times
3. then click close all notifications

Looked in the console and saw no errors

**Comment by LinweiW** [comment]
@tmcconechy Try to click close all notifications several times. the error will show.

**Comment by tmcconechy** [comment]
Ok i see. Error only happens if there are none open.

**Comment by LinweiW** [comment]
@tmcconechy I saw the fix add checks to closeLatest and closeAll but not close(id). close(id) throws same error when
1. create a notification with an id
2. click x to close it
3. call close(id)

**Comment by tmcconechy** [comment]
@andriivarhanov ?

**Comment by andriivarhanov** [comment]
@tmcconechy added the check to `close` in https://github.com/infor-design/enterprise-ng/pull/1451
