### ISSUE TITLE
File Upload: Issue with uploading a big file. Icon while uploading is invisible

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#7277]
1. Go to https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html
2. Upload a bigger file
3. Hover the icon while uploading and the style is "invisible"
4. Screen shot attached. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/39101346/221942911-bdf194ef-ebc8-49f3-be8c-adeb6030d4ed.png)

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise/issues/7265 is similar just noting

**Comment by jbrcna** [comment]
QA Passed.
https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html
<img width="445" alt="image" src="https://user-images.githubusercontent.com/56722184/223046843-ec943c42-48a5-4e99-9fd8-7041c2a1c154.png">
