### ISSUE TITLE
Timeline: Broken when placed inside a 1x1 Card

### ISSUE THREAD

**Issue by glennreyesss** [infor-design/enterprise#7278]
**Describe the bug**
The timeline component is not properly styled/responsive when placed inside a 1x1 card component.

**To Reproduce**
Place the Timeline Component Raw code inside the Card Component card-content class.

Timeline Component (Raw)
https://raw.githubusercontent.com/infor-design/enterprise/4.80.3/app/views/components/timeline/example-index.html

Card Component (Raw)
https://raw.githubusercontent.com/infor-design/enterprise/4.80.3/app/views/components/cards/example-index.html

Please see the screenshot below.
![image](https://user-images.githubusercontent.com/126537236/222027911-7dfa9536-a6d6-4c0f-8411-e593e7b2bb4b.png)

**Comment by tmcconechy** [comment]
@glennreyesss can you attach the new markup for the example so we can try it?

**Comment by glennreyesss** [comment]
@tmcconechy, here is the example https://main-enterprise.demo.design.infor.com/components/timeline/test-on-card.html

**Comment by glennreyesss** [comment]
Hello @tmcconechy, when is the ETA for this fix?

**Comment by glennreyesss** [comment]
Ok, thank you @tmcconechy.

**Comment by glenlieorillo** [comment]
Tested and passed.

https://main-enterprise.demo.design.infor.com/components/timeline/test-on-card.html

https://user-images.githubusercontent.com/102151352/226300991-a03219b2-aff9-49ec-9350-c24a87666b8f.mov

**Comment by glennreyesss** [comment]
Hello @tmcconechy, I am still encountering the issue after I updated my Widget SDK to version 3.22 which includes IDS version 4.80.3. Please see the screenshot.
![image](https://user-images.githubusercontent.com/126537236/236983956-d56c7475-2a11-4743-a4cc-84ea193fe60f.png)
