### ISSUE TITLE
Aug31 Specific Date Bug

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#728]
**Describe the bug**
Down and up key is not selecting the right thing in datepicker.

**To Reproduce**
1. Go to http://localhost:4000/components/datepicker/example-index.html
2. Hit down arrow to open
3. Hit down again to go to sept 7th
4. Hit up..

At this point month should be august. And be highlighted. This failed a build.
Also this is focus trap as you can no longer use the keyboard which makes it more serious.

**Expected behavior**

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by brianjuan** [comment]
http://4100-rc0-enterprise.demo.design.infor.com/components/datepicker/example-index.html
Passed QA testing, bug fix is working on all browsers.

**Comment by tmcconechy** [comment]
This should have been closed.
