### ISSUE TITLE
Datagrid: filtering with disableClientFilter set true is re-rendering the grid

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#7282]
**Is your feature request related to a problem or use case? Please describe.**
Have a client ticket that is indicating slow performance when filtering with a page size of 200 records.  Additionally, when examining the console log (need to have verbose checked) they are seeing several of the following messages stemming from the datagrid:

[Violation] xxx took xxx ms
[Violation] Forced reflow messages.

**Describe the solution you'd like**
Noticed that the list is being re-rendered when handling the filter request initiated via pressing the enter key within a filter row cell. Even when the setting of disableClientFilter is set to true.  When we receive the filter event, we make a call to the server for the 200 filtered records and load the data into the grid.  This also causes the list to be re-rendered. Seems like the list should not be re-rendered when handling the filter request when disableClientFilter is set to true.  The re-rendering of the datagrid is causing some of the [Violation] messages.  Should also reduce processing time since the datagrid is not rendered twice.

Suggest the following code change within the applyFilter() method of datagrid.js...

**Existing:**
```
    if (!this.settings.source) {
      this.clearCache();
      this.renderRows();
    }
```

Suggestion:
```
    if (!this.settings.source && !this.settings.disableClientFilter) {
      this.clearCache();
      this.renderRows();
    }
```

1. Using the attached 'test-filtering-violations.html'
2. Open the browser's debugger
3. Open Console tab, and ensure that the Custom levels has Verbose checked
4. Click on 'Load Data' button
5. Open multi-select drop down for Activity column in the filter row & select 'Assemble Paint'
6. Initiate filter request by pressing enter key from the List Price filter row cell
7. Notice the violation messages in the console log for each step

**Comment by claudenbach** [comment]
[ExampleOfViolations.zip](https://github.com/infor-design/enterprise/files/10864953/ExampleOfViolations.zip)

**Comment by claudenbach** [comment]
Landmark customer ticket: https://jira.infor.com/browse/LMWEB-16652

**Comment by tmcconechy** [comment]
@ericangeles can you check this one out. might be easy. we could include in 4.81.x if it is but i think it will require smoke testing the majority of the data grid pages after adding it...

**Comment by tmcconechy** [comment]
Added this fix to be in 4.81.x as well.

**Comment by glenlieorillo** [comment]
Tested and passed

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/224596816-0a4d05e6-e4ef-4623-9949-089d5a7e8eed.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/224597854-08a82087-f7e1-49d0-b94f-01c5054ec3ff.png">

**Comment by glenlieorillo** [comment]
Tested and passed

**main-enterprise**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/224596816-0a4d05e6-e4ef-4623-9949-089d5a7e8eed.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/224597854-08a82087-f7e1-49d0-b94f-01c5054ec3ff.png">

**localhost**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/224599394-7162c4b6-ee0f-4165-b554-f7c66b4c9346.png">
