### ISSUE TITLE
ids-enterprise-ng 14.8.3 uses a vulnerable d3-color 

### ISSUE THREAD

**Issue by btburg** [infor-design/enterprise#7284]
**Describe the bug**
ids-enterprise-ng 14.8.3 uses a vulnerable d3-color.

**To Reproduce**
When I use ids-enterprise-ng in my project and type "npm audit" it shows the following:

  High            d3-color vulnerable to ReDoS

  Package         d3-color

  Patched in      >=3.1.0

  Dependency of   ids-enterprise-ng

  Path            ids-enterprise-ng > d3 > d3-color

  More info       https://github.com/advisories/GHSA-36jr-mh4h-2g58

**Expected behavior**
"npm audit" will not mention any vulnerabilities

**Version**
- ids-enterprise-ng: 14.8.3

**Comment by tmcconechy** [comment]
Aiming to have this fixed in the next version in a week or so. Have the fixes in place.
