### ISSUE TITLE
Typeface styling consistency and implementation method

### ISSUE THREAD

**Issue by Infor-Calvin** [infor-design/enterprise#7287]
For the current IDS text styling, there are discrepancies between:
Product / Design -
https://design.infor.com/product/foundations/typography
Component / Dev -
https://design.infor.com/code/ids-enterprise/latest/typography
(And Figma / Design Component Library)
Web Component Dev
https://main.wc.design.infor.com/ids-text/typography.html

Also, there are some questions regarding how the styling can be communicated between design and dev easily -- what and how should the styling attributes (i.e. text size, line-height, case, etc.) be tokenized and labeled (and work within the limitation in Figma - our main tool for design and used in dev handoff). Would this be taken on by IDS or product teams?
Furthermore, if it's intended that some flexibilities are given to the product teams (i.e. product team can make their own styling CSS classes based on guidelines and IDS variables/classes; and occasionally create their own styling variations based on needs and unique use-cases).

**Comment by talkaboutdesign** [comment]
@tmcconechy lets discuss this internally. Some good questions here.

**Comment by tmcconechy** [comment]
Just realized we also have this revision https://main.wc.design.infor.com/ids-text/typography.html to add to the list of making consistent (in the web components).

**Comment by hey-yall** [comment]
Brought to designers under Jira ticket IDS-1069 https://jira.infor.com/browse/IDS-1069

**Comment by hey-yall** [comment]
Hi Calvin! We are addressing this under https://jira.infor.com/browse/IDS-1069 . Please follow the Jira ticket for progress updates here. We plan to address this in Web Components as part of a typography overhaul. Thanks!

**Comment by hey-yall** [comment]
Closing :)

**Comment by inforandy** [comment]
closed, ping me if these gaps remain but they have been broadly closed
