### ISSUE TITLE
Icons: Missing icons and name mismatches in classic vs new theme

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#7289]
**Describe the bug**
Not all icons exist in both classic and new theme and some (possibly quite many) that do exist in both don't have the same name in both themes. One consistent mismatch is for filled icons, where many(?) are called `x` in classic and `x-filled` in new, which is mainly what widget developers have reported to us. There are more inconsistencies than that though.

This is a quite serious issue for widgets that run in Homepages and Portal V2, since we use classic in Homepages and new in Portal. Luckily, widgets can check where they're currently running and use the correct icon name based on that, but it would be preferable if those mismatches didn't exist in the first place.

Would it be possible to somehow solve this without affecting other teams?

**Version**
- ids-enterprise: 4.80.1

**Platform**
 - Infor Application/Team Name: Homepages / OS Portal

**Comment by tmcconechy** [comment]
This might be rather difficult or take a long time. The intention is to use the new ones not the old ones.

Quite a bit of icons out of sync overlap.

```
system icons 4.5: 735 icons
empty state icons 4.5: 35 icons 

system icons 3.5: 424 icons
empty states icons 3.5: 13 icons
```

Regarding the filled ones. For the new icons we dont want the filled ones we want the new ones (unfilled). So maybe you can just fix the filled ones by removing`filled`

**Comment by radovaniljic** [comment]
@tmcconechy Noted regarding not using the filled ones! Removing `linear` from the unfilled ones would solve the issues that have been reported to us so that would be great.

**Comment by tmcconechy** [comment]
Adding one thing as this will likely get fixed soon. `empty-circle` has a hard coded stroke.
