### ISSUE TITLE
Tabs Module: Border between dropdown and textbox looks off

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7297]
**Describe the bug**
Border between dropdown and textbox looks off.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html?theme=new&mode=light&colors=BB5500
2. Notice the border between dropdown and textbox

**Version**

- ids-enterprise: 4.81.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/102151352/223322492-2b6f1fc8-ac00-44d6-a7c7-f17b432fb7a9.png)

**Platform**
 - All major browsers

**Comment by tjamesallen15** [comment]
@tmcconechy  do we want this remove except on default color?

**Comment by tmcconechy** [comment]
I think i would make the entire component have a white background. So make the buttons on each side white background, check the states and classic looks decent and see how that looks.

Its a bit of an odd design. Also see this was reported here as well https://github.com/infor-design/enterprise/issues/7304 perhaps this closes that issue too?

**Comment by tmcconechy** [comment]
See https://github.com/infor-design/enterprise/issues/7297#issuecomment-1462201273

**Comment by tjamesallen15** [comment]
> I think i would make the entire component have a white background. So make the buttons on each side white background, check the states and classic looks decent and see how that looks.
> 
> Its a bit of an odd design. Also see this was reported here as well #7304 perhaps this closes that issue too?

Thanks @tmcconechy

**Comment by glenlieorillo** [comment]
The bug has been fixed. However, I noticed the focus on the ellipses is rectangular.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/102151352/227839571-d44b7ad6-5ac5-44eb-94c4-7aceb6a17e99.png">

Unlike in the other example, it is square.

https://main-enterprise.demo.design.infor.com/components/tabs-module/example-add-tab-button.html

<img width="523" alt="image" src="https://user-images.githubusercontent.com/102151352/227839729-37d0ba34-79e1-48b2-af27-140f335f69ab.png">

**Comment by ericangeles** [comment]
@tjamesallen15 can you take a look at this?

**Comment by glenlieorillo** [comment]
Tested and passed.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/102151352/228788285-4977b476-b79c-4619-a8dc-d33541a8b808.png">
