### ISSUE TITLE
Timeline: Line doesn't reach the last timeline-block element

### ISSUE THREAD

**Issue by glennreyesss** [infor-design/enterprise#7298]
**Describe the bug**
The line doesn't reach the last timeline-block element.

**To Reproduce**
Create multiple timeline-block elements that don't contain the sub-heading and date class under the content class. 

You may see the code below. Git doesn't allow uploading an HTML file.
[timeline.txt](https://github.com/infor-design/enterprise/files/10907736/timeline.txt)

Here is the screenshot of the issue:
![image](https://user-images.githubusercontent.com/126537236/223390489-6c875245-8774-43b4-a3cf-4315594e221c.png)

**Comment by tmcconechy** [comment]
Fix with https://github.com/infor-design/enterprise/issues/7278

**Comment by jbrcna** [comment]
QA Passed
https://main-enterprise.demo.design.infor.com/components/timeline/test-empty-dates.html
<img width="456" alt="image" src="https://user-images.githubusercontent.com/56722184/229168972-c23bac55-a112-4d00-acd8-92a3fbf65312.png">
