### ISSUE TITLE
Timeline: Line exceeds the last indicator when there is a line break in the sub-heading

### ISSUE THREAD

**Issue by glennreyesss** [infor-design/enterprise#7299]
**Describe the bug**
The line exceeds the last indicator when there is a line break in the sub-heading class of the last timeline-block.

**To Reproduce**
Create multiple timeline-block elements. The last timeline-block element should contain a sub-heading with a line break in its content.

You may see the code below. Git doesn't allow uploading an HTML file.
[timeline-sub-heading.txt](https://github.com/infor-design/enterprise/files/10908166/timeline-sub-heading.txt)

Here is the screenshot of the issue:
![image](https://user-images.githubusercontent.com/126537236/223389435-31e87927-5a5f-4415-b6cf-05b3c60347b0.png)

**Comment by tmcconechy** [comment]
Fix with https://github.com/infor-design/enterprise/issues/7278
