### ISSUE TITLE
SOHO-8027: Datagrid E2E Tests

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#730]
**Is your feature request related to a problem? Please describe.**
Datagrid needs tests.

**Describe the solution you'd like**

Write e2e tests:
- Load each test page in the components/<name>/list and test the main ideas of the page, if unsure of the main idea ask on the channel.
- Keyboard
**Describe alternatives you've considered**
n/a

**Additional context**
See existing tests for example dropdown, treemap, menubutton, timepicker, spinbox for reference. Also see docs/TESTING.MD for commands

**Comment by tmcconechy** [comment]
Closing this for now as we do have most of the tests done and gradually adding more.
