### ISSUE TITLE
Application Menu: is-personalizable class turns app menu the current theme color

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#7302]
**Describe the bug**
I wanted to check if this is a bug or if this is working as designed.

When the app menu has the "is-personalizable" class and the page is loaded without any customizations to the theme, the menu is the standard color. Then when a theme is applied the app menu becomes the selected theme color.

**To Reproduce**
1. Go to http://localhost:4000/components/applicationmenu/test-six-levels.html
2. Note that the app menu is the standard menu color
3. Select a color from the theme menu
4. See that the app menu has changed to the selected color
5. Change to the classic theme
6. Note that the app menu is back to the standard color even with a color applied to the theme.

**Expected behavior**
If this is not working as designed, it is expected that the app menu stays the standard menu color when different colors are selected for the theme.

**Version**
- ids-enterprise: v4.81.0-dev

**Screenshots**
New theme:
![image](https://user-images.githubusercontent.com/76002134/223839992-9ff25791-71cb-4edc-8d28-1096bcfc792c.png)

Classic theme:
![image](https://user-images.githubusercontent.com/76002134/223840291-2ba48326-c0cf-44c4-87eb-24bf7c5c9ae1.png)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version:  110.0.5481.178 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Yeah i think this is a bug in classic mode, it should probably not even use the color in classic and stay always azure?

But not sure if we would fix it at this point. Given that we plan on changing the menu to white. And removing the colors from it. Sometime in the future. Idea is to remove color blocking from the UI like this.

Will review with the team.
