### ISSUE TITLE
Field filter: icon hover highlight is off in high contrast

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7307]
**Describe the bug**
related to #7264 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-filter/example-short.html?theme=new&mode=contrast&colors=default
2. hover over the icon
3. See error

**Expected behavior**
<img width="373" alt="image" src="https://user-images.githubusercontent.com/56722184/223956049-9809f937-9aab-4c3b-8c20-c6a44d468439.png">

**Version**

- ids-enterprise: v4.82.0-dev/main

**Screenshots**
<img width="585" alt="image" src="https://user-images.githubusercontent.com/56722184/223956139-f73392ed-f098-43af-a149-deb70ecbe559.png">

**Platform**
safari
**Additional context**

**Comment by tmcconechy** [comment]
Closing out older issues / field filter isnt getting much fixes
