### ISSUE TITLE
User cannot expand two parent folders in the menu at the same time

### ISSUE THREAD

**Issue by michalnowak-infor** [infor-design/enterprise#7309]
**To Reproduce**

1. Open this IDS component: https://main-enterprise.demo.design.infor.com/components/applicationmenu/test-six-levels.html
2. Try to expand 2 parent folders at the same time.
3. Observe that when user expands the second parent folder, the first one gets collapsed.

**Expected behavior**
Users should be able to expand as many parent folders as they want to see the whole tree structure of the menu items at the same time.

This is coming from WFM.

**Comment by ericangeles** [comment]
@michalnowak-infor, I don't think that this is a bug. By default, the accordion only allow one pane to open. For your use case to work, you need to set the `allowOnePane` to `false` in accordion component.

Check this example https://main-enterprise.demo.design.infor.com/components/accordion/test-expand-collapse-by-id.html

**Comment by tmcconechy** [comment]
Was going to add that as well see https://main-enterprise.demo.design.infor.com/components/applicationmenu/test-all-chevrons.html
