### ISSUE TITLE
SOHO-8027: Datagrid "Other" Tests (Accessibility, Security...)

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#731]
**Is your feature request related to a problem? Please describe.**
Datagrid needs tests.

**Describe the solution you'd like**

Write "Other" Tests
- Accessibility tests https://github.com/dequelabs/axe-core
- Security Tests
- Specific Test Cases from Cindy
- Protractor Image Comparison Tests

**Describe alternatives you've considered**
n/a

**Additional context**
See existing tests for example dropdown, treemap, menubutton, timepicker, spinbox for reference. Also see docs/TESTING.MD for commands

**Comment by tmcconechy** [comment]
Closing this as done, we have datagrid tests.
