### ISSUE TITLE
Lookup: Lookup icon hover highlight is slightly cut off in safari

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7314]
**Describe the bug**

**To Reproduce**

1. Go to https://4810-beta-0-enterprise.demo.design.infor.com/
2. Find lookup field
3. Hover over the icon

**Expected behavior**
<img width="392" alt="image" src="https://user-images.githubusercontent.com/56722184/224258174-6d9fa499-a6ea-40eb-a0a8-2928a1703521.png">

**Version**

- ids-enterprise: v4.81.0-beta-0

**Screenshots**
<img width="427" alt="image" src="https://user-images.githubusercontent.com/56722184/224258339-35203e85-f14b-4eed-8131-1bf2768e7396.png">

**Platform**
Safari

**Additional context**

**Comment by tmcconechy** [comment]
no longer seems valid on https://main-enterprise.demo.design.infor.com/components/lookup/example-index.html
<img width="376" alt="Screenshot 2023-08-17 at 3 40 16 PM" src="https://github.com/infor-design/enterprise/assets/814283/a6851198-a2d7-449a-a85a-a7e25010b617">

**Comment by jbrcna** [comment]
working as expected. thank you
https://main-enterprise.demo.design.infor.com/components/lookup/example-index.html
<img width="682" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/7f87b2c6-1be3-4ae7-8601-4e919c3517c5">
