### ISSUE TITLE
Sink page: modal button double border

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7316]
**Describe the bug**

**To Reproduce**

1. Go to https://4810-beta-0-enterprise.demo.design.infor.com/
2. Find modal
3. click to focus the button
4. close the modal
5. See error

**Expected behavior**
should have no double border in button

**Version**

- ids-enterprise: v4.81.0-beta0

**Screenshots**
<img width="341" alt="image" src="https://user-images.githubusercontent.com/56722184/224264854-b9b2a62c-a59a-4f6b-840f-bb7f55138bb5.png">

**Platform**
All
**Additional context**

**Comment by tmcconechy** [comment]
Dont think this is a bug at this stage in the steps. The button is focused and this is the focus state
