### ISSUE TITLE
Personalization: Make Azure the Default

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7320]
**Describe the bug**
Was decided we arent quite ready to make white/alabaster the default. So will need to make azure the default again and make alabaster a personalization option. This as of now needs to go in 4.80.x as a patch and be changed delaying the 4.81.x release. So this is high priority.

Sorry about this @ericangeles ! Maybe it can be PR'd to main, then copied back to 4.81.x and 4.80.x with one general fix and testing?

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-index.html
2. Header should be azure
3. Open the .. menu and select colors -> should be an alabaster option
4. Open the .. menu and select default -> should go back to azure 
5. Open the .. menu and select azure -> should also go back to azure 

**Expected behavior**
 - test https://main-enterprise.demo.design.infor.com/components/personalize all should be azure by default
 - test https://main-enterprise.demo.design.infor.com/components/header all should be azure by default
 - in any page the colors should have a new alabaster option
 
**Version**
- ids-enterprise: [e.g. v4.80 / v4.81.0]

**Additional context**
Fix is probably changing all variables in https://github.com/infor-design/enterprise/blob/main/src/themes/theme-new-light.scss back to azure as a default
https://github.com/infor-design/enterprise/tree/main/src/components/personalize needs alabaster added to the list and code to make it happen.

**Comment by jbrcna** [comment]
QA Failed.
[homepage/example-hero-widget.html?colors=BB5500](https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html?colors=BB5500)
`#icon-dropdown icon` - when hovered, color is off with all colors (except default & alabaster)
<img width="351" alt="image" src="https://user-images.githubusercontent.com/56722184/228293119-eff43530-d98e-46ff-a9cc-4ae102c7b5ab.png">

[homepage/example-hero-widget.html?theme=new&mode=light&colors=ffffff](https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html?theme=new&mode=light&colors=ffffff) - with alabaster , button disappears when hoevered.
high contast & light - button disappears
dark - color is off
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/56722184/228293959-46f30a3c-8eaa-4092-a777-eef04f88d5f4.png">

**Comment by tmcconechy** [comment]
@jbrcna its getting hard to fix everything all at once with the color/themes. So i fixed this last comment on this PR https://github.com/infor-design/enterprise/pull/7363

Please QA that PR and include a test for this.
