### ISSUE TITLE
Splitter: The right sidebar can not be displayed in splitter page

### ISSUE THREAD

**Issue by zzhblh** [infor-design/enterprise#7322]
**Describe the bug**
The width of the right sidebar is always 0 when the side param is “right”

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/splitter/example-splitter-right.html or https://design.infor.com/code/ids-enterprise/latest/demo/components/splitter/test-collapse-button-right.html .
![image](https://user-images.githubusercontent.com/8154831/225185162-93e527cd-f135-4343-a77c-9131cff5d2d6.png)

`<div id="splitter" class="splitter" data-options="{'side':'right', 'save':false}"></div>`  when the side param is “right” the width of the right sidebar is always 0 and the content of right sidebar the content of right sidebar is not displayed.

2. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/splitter/test-tabs.html
![image](https://user-images.githubusercontent.com/8154831/225187059-42e39172-f9a9-4de6-9dd4-9529eef4833a.png)

`<div id="splitter" class="splitter"></div>` No side parameter defined (default side value is ‘left’ in soho), the content of right sidebar can be displayed.

3. There is something wrong with the code near line 28215 `if (this.isSplitterRightSide){}else{}` in soho.js.

**Expected behavior**
The parameter of right sidebar should be right.
The right sidebar can be displayed.

**Version**

v4.80.3 

**Screenshots**
See above.

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
not sure i follow this issue as all the examples mentioned look good. @zzhblh but if you do see a solution feel free to do a pull request and contribute to this open source and we can check it out?
