### ISSUE TITLE
Datepicker: Component with type “range” saves a start date without validation when an end date was not selected in the picker

### ISSUE THREAD

**Issue by maltsevy** [infor-design/enterprise#7332]
**Describe the bug:**

When a user clicks on a “datepicker” component ([source](https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-ng/src/lib/datepicker/soho-datepicker.component.ts)) and selects only the start date and clicks outside the datepicker and closes it in this way - the selected start date value will be saved in the modal. However, if we select a start date and click the “Apply” button - it will set the start and end date as the same date. It introduces inconsistency in the component behavior and doesn’t have or allow adding some “live” validation on a frontend side.

**To Reproduce**

Create a datepicker component
```jsx
<input type="text"
       soho-datepicker
       id="=daterange"
       [formControlName]="dateRange"
       [mode]="'range'"
       [range]="{useRange: true,maxDays: 20, separator: '-'}"
/>
```
Click on the button to open a datepicker and select a start date
![image](https://user-images.githubusercontent.com/44119194/225893542-bba1d041-f05f-4335-8c73-01cb4cda8052.png)
Click outside the datepicker and see that only the start date was entered.
If the user repeats the same steps but instead of clicking outside the datepicker he clicks the “Apply” button - he will see both the start and end date entered:
![image](https://user-images.githubusercontent.com/44119194/225893622-fecc19d0-25a6-4f88-b059-3b6c671d3a1d.png)

**Expected result:**

As having only the start date is an invalid format for the date range after closing the datepicker user should see either both start and end dates as the same day, OR the validation message informing him that he needs to enter end date as well

**Version**
ids-enterprise-ng: 13.6.2

**Platform**
    Infor Application/Team Name: Infor WFM

**Comment by tmcconechy** [comment]
This can easily be reproduced on https://main-enterprise.demo.design.infor.com/components/datepicker/example-range.html

I guess clicking out should do the same thing as hitting clear when only one end of the date is selected. I dont consider this a major issue as its been like this for ages
