### ISSUE TITLE
Tabs: Alabaster Cleanup 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7333]
**Describe the bug**
Need to finish up alabaster theme. on the tab component.

- Module tabs -> https://main-enterprise.demo.design.infor.com/components/tabs-module/example-index.html
- Header -> https://main-enterprise.demo.design.infor.com/components/header/example-index.html
- Multi Tabs -> https://main-enterprise.demo.design.infor.com/components/tabs-multi/example-index.html
- Header Tabs -> https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html
- Vertical Tabs -> https://main-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html

https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=127-38900&t=bYNV1tThUhGQXib7-0

**Expected behavior**
Add design changes, adapt personalization colors and add deprecated label to multi tabs page

**Comment by hey-yall** [comment]
Addressed to designers through this Jira ticket: https://jira.infor.com/browse/IDS-1010

**Comment by hey-yall** [comment]
Hi @tmcconechy -- Lauren is working on this now, but we dropped the Datagrid and Editor portions you asked for above. The header/toolbar color is consistent across accent themes and we plan to keep this the same in Alabaster. However, the designers will be providing updated Alabaster guidance for headers and tabs soon under the same Jira ticket -- https://jira.infor.com/browse/IDS-1010
