### ISSUE TITLE
Builder: sidebar popup not readable in safari 

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7338]
**Describe the bug**
 using safari  browser, sidebar popup button is not readable in safari when default color is used/selected

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/builder/example-builder-wizard.html
2. Resize the browser to see sidebar popup
3. Switch color to default
4. Hover over sidebar popup button
5. See error. Notice that the color of button is off

**Expected behavior**
should be readable

**Version**

- ids-enterprise: v4.82.0-dev

**Screenshots**
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/56722184/226248290-54ff0dcb-ebea-4b0b-b017-29d3be789032.png">

**Platform**
Safari

**Additional context**
affected EPs
https://main-enterprise.demo.design.infor.com/components/builder/example-builder-subtitle-test.html?colors=default
https://main-enterprise.demo.design.infor.com/components/builder/example-builder.html?colors=default

**Comment by tmcconechy** [comment]
@jbrcna im not seeing a button on this page? Perhaps this was recently fixed?

**Comment by tmcconechy** [comment]
Ok i see it now. I think this was fixed later on friday i dont see the hover problem anymore

**Comment by jbrcna** [comment]
Thanks @tmcconechy

**Comment by ericangeles** [comment]
@tmcconechy am seeing the issue here. You need to shift to different colors then go back to the default one.

**Comment by jbrcna** [comment]
this is now working as expected. thank you. all themes modes and colors are tested as well.
<img width="782" alt="image" src="https://user-images.githubusercontent.com/56722184/228430400-c8eb8d2f-8981-4538-9b3c-e12070980faa.png">

**Comment by jbrcna** [comment]
this is now working as expected.
https://main-enterprise.demo.design.infor.com/components/builder/example-builder-wizard.html
<img width="350" alt="image" src="https://user-images.githubusercontent.com/56722184/229464594-ce9bb503-cf50-4208-864a-2a99ba25abfa.png">
