### ISSUE TITLE
Column charts: alabaster not working in dark mode

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7350]
**Describe the bug**

**To Reproduce**

1. Go to any column chart page 
e.g., https://main-enterprise.demo.design.infor.com/components/column/example-index.html
2. Switch to dark mode
3. Change color to alabaster

**Expected behavior**
header color should change to alabaster 

**Version**

- ids-enterprise: v4.82.0-dev

**Screenshots**
<img width="796" alt="image" src="https://user-images.githubusercontent.com/56722184/226837728-b1cb0431-dceb-41d0-a0d8-3d656a3b11da.png">

**Platform**
All

**Additional context**
see also
https://main-enterprise.demo.design.infor.com/components/column-grouped/example-index.html?theme=classic&mode=dark&colors=ffffff
https://main-enterprise.demo.design.infor.com/components/column-stacked/example-index.html?theme=classic&mode=dark&colors=ffffff

**Comment by ericangeles** [comment]
@jbrcna the color of Alabaster in Dark Mode will be dark as well. Closing the ticket.
