### ISSUE TITLE
Pager: Underline Looks Rounded

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7352]
**Describe the bug**
The pager has a box shadow o the active state. Should turn it off so it doesnt look partly rounded.

**To Reproduce**
See https://jira.infor.com/browse/IDS-437

**Screenshots**
![image](https://user-images.githubusercontent.com/814283/226964358-e8c1008e-db66-44c6-9f38-928d528c6f46.png)

**Comment by ericangeles** [comment]
Looks like the border-radius should remove as well.

**Comment by glenlieorillo** [comment]
Tested and passed.

https://main-enterprise.demo.design.infor.com/components/pager/example-index.html

https://user-images.githubusercontent.com/102151352/227840641-ba64f762-18dc-404b-861f-84d834ce69d5.mov
