### ISSUE TITLE
Bug "field filter in modal design-glitch #7001" still not fixed

### ISSUE THREAD

**Issue by rusteninfor** [infor-design/enterprise#7358]
**Describe the bug**

See https://github.com/infor-design/enterprise/issues/7001 for details. This issue isnt 100% fixed.
The QA page does not display the error, unless you add the classes : modal is-visible to the `<div class="row top-padding">`. 

So instead of
`<div class="row top-padding">`
it should be 
`<div class="row modal is-visible top-padding"> `
to provoke the error

**To Reproduce**
See above

**Additional context**
#7001

**Comment by tmcconechy** [comment]
@tjamesallen15 can you take another look at this and #7001?

**Comment by tjamesallen15** [comment]
> @tjamesallen15 can you take another look at this and #7001?

sure sure

**Comment by jbrcna** [comment]
QA Passed
https://main-enterprise.demo.design.infor.com/components/modal/test-modal-field-filter.html
<img width="493" alt="image" src="https://user-images.githubusercontent.com/56722184/229463120-dc8ce17a-9245-491b-a86c-25a2281ad208.png">
