### ISSUE TITLE
EmptyMessage: Is Not Centered on Different Size Widgets

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7360]
**Describe the bug**
The empty message should be centered when used in a widget.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/emptymessage/example-widgets.html
2. Add class "card double-height" to one card
3. See that its not centered

**Expected behavior**
Should always center itself.

Possible Solution:
- add a sass mixin for centered (double check if we have one but from my checks we dont)
- sass mixin adds something like
- also add a flex-center utility class
- but make sure empty message auto centers without the class by using the mixn

```
.flex-center {    
 display: flex;
 align-items: center;
 justify-content: center;
 flex-wrap: wrap;
 align-content: center;
 flex-direction: column;
}
```

**Version**
- ids-enterprise 4.82

**Additional context**
[Add any other context about the problem here.
](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1679032110130?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1679032110130&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1679032110130&allowXTenantAccess=false)

**Comment by CindyMercadoReyes** [comment]
Hi @tmcconechy and @danielortiz1982  BDD attached. Thanks, Cindy
[BDD_github7360.docx](https://github.com/infor-design/enterprise/files/11355928/BDD_github7360.docx)

**Comment by danielortiz1982** [comment]
Thanks @CindyMercadoReyes
