### ISSUE TITLE
Datagrid: Hover Color Changed

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7369]
**Describe the bug**
While testing PRs i noticed the hover color changed.

**To Reproduce**

1. Go to https://4800-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Hover a row a click a row. Notice the colors
3. Compare this to https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html

**Expected behavior**
Should be two different colors on hover and select

**Screenshots**
![Screenshot 2023-03-27 at 11 06 10 AM](https://user-images.githubusercontent.com/814283/227981676-687e41e5-3177-4ad9-9486-af8a364721b0.png)

**Comment by tmcconechy** [comment]
@ericangeles do you know/how when this changes?

**Comment by ericangeles** [comment]
@tmcconechy has something to do with this PR https://github.com/infor-design/enterprise/pull/7341

**Comment by janahintal** [comment]
This is now working as expected in http://localhost:4000/components/datagrid/test-selected-rows-addnew.html?theme=new&mode=contrast&colors=default and main. Also tested in all Theme, Modes and Colors. 
![image](https://user-images.githubusercontent.com/45757016/229511798-ab4ac72c-6a27-4c6e-ae60-b38875cc9270.png)
![image](https://user-images.githubusercontent.com/45757016/229512048-9cde4d74-e842-47c0-8434-ab53ea48cff6.png)
