### ISSUE TITLE
Tabs Vertical: In mobile devices, dropdown inside the tab is cropped

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#737]
**Describe the bug**
In Tabs Vertical control, dropdown inside the tab is cropped.

**To Reproduce**
1. Go to http://4100-beta1-enterprise.demo.design.infor.com/components/tabs-vertical/test-extra-sidebar-content.html using Android or iOS devices
2. Click the "Product Level" tab
3. Dropdown inside the tab is cropped

**Expected behavior**
Dropdown inside the tab should not be cropped.

**Screenshots**
<img width="522" alt="screen shot 2018-09-03 at 5 42 59 pm" src="https://user-images.githubusercontent.com/39508864/44979887-e9fb7880-afa0-11e8-82a3-7f8f7a8a5639.png">

**Platform**
 - All browsers in Android and iOS devices

**Additional context**
No additional context

**Comment by tmcconechy** [comment]
To solve this, just rename the tests to have "responsive" or "not-responsive" in the tests. Because this is a setting you can enable thats not enabled on all tests. See:

http://4100-beta1-enterprise.demo.design.infor.com/components/tabs-vertical/example-responsive.html

**Comment by tmcconechy** [comment]
Duplicate #3542
