### ISSUE TITLE
IDSWeekview: Agenda variant

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise#7373]
**Is your feature request related to a problem or use case? Please describe.**
This is a request for a variant of the IDS Weekview, which we will call the "Agenda View". It's a request from the WFM team for use in their homepage widget. 

**Describe the solution you'd like**
Scoped out here: https://inforonline.sharepoint.com/:w:/s/InforDesign/EdzNr6a9ZwdBtdAOPxeQcOAB6-xIpCzZHdWOd4PjulUvbg 
"A week-long calendar view that shows events for each day"
Design and more here: https://www.figma.com/file/0S0CmLnhegSnAOBulgvSD3/Nurse-Homepage-Designs?node-id=3977%3A112302&t=3iHxvWEXjG7oP7r1-0 

**Additional context**
Reach out to Andy for any additional information or context!

**Comment by inforandy** [comment]
@tmcconechy alright, we are going to move this one ahead with the original design provided in the issue here. Let's break it down at the next planning

**Comment by danielortiz1982** [comment]
@inforandy Do we need to scope this for both 4x and wc?

**Comment by tmcconechy** [comment]
i think WFM is on the new components new.

**Comment by CindyMercadoReyes** [comment]
BDD Attached.  Kind regards, Cindy
[BDD_github7373.docx](https://github.com/infor-design/enterprise/files/11454601/BDD_github7373.docx)
