### ISSUE TITLE
Add CSS utility classes to the project

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#7377]
**Is your feature request related to a problem or use case? Please describe.**
We frequently find ourselves writing repetitive CSS code for commonly used styles such as margins, paddings, and typography. This not only slows down development time but also increases the size of the CSS file.

To improve front-end development efficiency, I suggest adding a set of CSS utility classes to the project. These classes could include commonly used styles such as positioning, padding, margin, font-size, font-weight, text-alignment, and more.

By using these utility classes, developers could save time and reduce the amount of repetitive code they write. Additionally, it would help keep the CSS file size smaller by reducing the number of rules written for specific elements.

**Describe the solution you'd like**
Suggesting that we create a CSS file and add these utility classes including the current ones we have and integrate them into the existing codebase. This would benefit not only the current development team but also future contributors to the project.

Will also need to add this to the doc site as a reference for everyone.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by CindyMercadoReyes** [comment]
Hi @tmcconechy  and @danielortiz1982 BDD attached.  Thanks Cindy 
[BDD_github7377.docx](https://github.com/infor-design/enterprise/files/11355916/BDD_github7377.docx)
