### ISSUE TITLE
Popupmenu/CAP: Popupmenu button isn't visible when the menu is open and is in a CAP header in classic theme dark mode

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#7383]
**Describe the bug**
**In classic theme dark mode** - when there's a popupmenu in a contextual action panel header, the popupmenu button has the same color as the header when the menu is open, resulting in it not being visible.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/contextualactionpanel/test-complex-toolbar.html?colors=50535A&theme=classic&mode=dark
2. Click on "Contextual Action Panel" to open the CAP
3. Click on "..." to open the popupmenu
4. Notice that the color of the popupmenu button is changed and no longer visible

**Expected behavior**
The button should be a different color.

**Version**
- ids-enterprise: 4.80.1

**Platform**
 - Infor Application/Team Name: Homepages

**Additional context**
In New theme, the button color is set to `#606066` and looks like this:
![image](https://user-images.githubusercontent.com/63045013/228744126-c2542854-7504-43c0-8e93-98b226c89213.png)

**Comment by ericangeles** [comment]
@yohannahbautista can you take a look at this?

**Comment by radovaniljic** [comment]
@tmcconechy the fix for this doesn't cover the scenario where the popupmenu button has an icon + text, see https://design.infor.com/code/ids-enterprise/latest/demo/components/contextualactionpanel/test-complex-toolbar-flex.html?theme=classic&mode=dark&colors=default

**Comment by tmcconechy** [comment]
@yohannahbautista this does indeed seem not fixed in one case. could you have a second look.

1. go to https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/test-complex-toolbar-flex.html?theme=classic&mode=dark&colors=default
2. click the filter button and see it disappears
3. try all 6 themese
