### ISSUE TITLE
Tooltip: Validation message in SohoDataGrid disappears after modal with another grid is opened and closed

### ISSUE THREAD

**Issue by leysanS** [infor-design/enterprise#7393]
Tooltip validation message in SohoDataGrid disappears from grid validation after model with another Grid inside is opened and closed.

**Steps to reproduce**
1. There's a grid with some validations (custom and default required one) and tooltip messages which are shown when user hovers over the cell on grid.
2. Some modal window which also includes grid inside is opened and closed.
3. After this invalid grid cells are still represented in proper styling, but tooltip message never appears (also DOM element which should contain tooltip message is empty when checking via sources in dev tools).

**Expected behavior**
Tooltip message should be present after modal window is closed.

**Version**
- iids-enterprise@4.65.1

**Platform**
 - Infor Team Name: Data Orchestrator
 - Browser Name: Chrome
 - Browser Version: Version 111.0.5563.147 (Official Build) (64-bit)

**Additional context**
SlackBlitz example which reproduces the issue:
https://stackblitz.com/edit/ids-quick-start-1411-yecsq4?file=src%2Fapp%2Fapp.module.ts,src%2Findex.html

**Comment by tmcconechy** [comment]
Perhaps just check if the issue still occurs on the latest version https://www.npmjs.com/package/ids-enterprise-ng?activeTab=versions in the meantime.

**Comment by yohannahbautista** [comment]
@leysanS  @tmcconechy  @ericangeles 
Hello, the tooltip isn't working in the stackblitz regardless of what's done, so I'm a bit confused on what the scenario for the bug is. Should tooltip appear when hovered and doesn't appear after you open modal? Or does tooltip not appear at all?

**Comment by leysanS** [comment]
@yohannahbautista
Hi! As it's written in description the scenario is following:
- grid1 has validation with tooltips - works ok and tooltips are shown
- modal window (which has other grid2 inside)  is opened and closed
- grid1 is not displaying tooltips any more. Expected: grid1 displays tooltips.

Could be observed also in SlackBlitz example: https://stackblitz.com/edit/ids-quick-start-1411-yecsq4?file=src%2Fapp%2Fapp.module.ts,src%2Findex.html

**Comment by tmcconechy** [comment]
seems like maybe the tooltip is getting destroyed via the grid on the modal. But do indeed test the latest version before we proceed with a fx @leysanS
