### ISSUE TITLE
Builder: incorrect icon color in alabaster

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7396]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/builder/example-builder-wizard.html?colors=ffffff&theme=new&mode=light
2. shrink the browser so `Sidebar Popup` is visible
3. change color to alabaster 
4. hover over`Sidebar Popup` 
5. see icon is white

**Expected behavior**
should have the correct color

**Version**

- ids-enterprise: v4.82.0-dev

**Screenshots**
<img width="190" alt="image" src="https://user-images.githubusercontent.com/56722184/229465795-79e2ffd8-c351-46c4-b189-e4a2972a5a18.png">

**Platform**
all

**Additional context**

**Comment by ericangeles** [comment]
This looks okay now when testing it. Moving it to Ready for QA.

**Comment by jbrcna** [comment]
can confirm. thanks. moving this ticket to Done.
<img width="696" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ea0396cd-be24-44a2-89ad-2ee522ac565c">
