### ISSUE TITLE
Lookup: Add clear button to the field

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#740]
Is your feature request related to a problem? Please describe.
In Lookup control when we add some data or object from lookup popup to the lookup field, currently there is no provision to remove specific object or data.
Please refer below image for more details.

![lookupwithdata](https://user-images.githubusercontent.com/42198413/45032579-b15fab80-b041-11e8-9b8b-221913be16f1.jpg)

It would be great if we provide "X" (remove) button for every object in the lookup field.
Please refer below image for more details.

![removebutton](https://user-images.githubusercontent.com/42198413/45032590-b6245f80-b041-11e8-94e8-6165c06d4b23.jpg)

**Comment by CindyMercadoReyes** [comment]
This new enhancement is working as expected. Tested it across browsers.

**Comment by CindyMercadoReyes** [comment]
BDD added to this ticket. Thanks, Cindy
[BDDStory_github#740.docx](https://github.com/infor-design/enterprise/files/4662659/BDDStory_github.740.docx)
