### ISSUE TITLE
Toolbar: Error toolbarAPI undefined

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#7402]
**Describe the bug**
check for toolbarAPI in toolbarFlexItem is undefined thus throwing exception.

**To Reproduce**

1. Go to https://stackblitz.com/edit/ids-quick-start-1512-3g3432?file=src/app/header/header.component.html
2. Click to show console
3. Write something in search field
4. Check console
5. Click hide button, and click it again to show search field
6. Write something in search field
7. Check console and see error

**Expected behavior**
No errors should be thrown in console

**Comment by tmcconechy** [comment]
When i run the stackblitz i get another error.

<img width="635" alt="Screenshot 2023-04-04 at 9 16 41 AM" src="https://user-images.githubusercontent.com/814283/229803883-d45c8cdd-f033-4875-a3f5-4073cbf45e73.png">

Any other way to reproduce? Can you suggest a fix / PR for it?

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
