### ISSUE TITLE
Datagrid: Error - Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#7403]
**Describe the bug**
While using datagrid lookup we are getting error - Cannot read properties of undefined (reading 'toString') when we open lookup popup multiple times. 

**To Reproduce**

1.after opening stackblitz you can see name and value column
2.click on value column lookup editor.
3.then select and unselect value from lookup 
4.click on apply button
5.now you can see value is changed in value column for respective row
6. now again click on value column lookup editor.
7. then again select and unselect value from lookup 

**Expected behavior**
User should be able to select multiple values in lookup whenever they open lookup popup.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0] v4.81.0

**Screenshots**
We have reproduce this issue in below StackBlitz link. 
[Ids Quick Start 1443 App (forked) - StackBlitz.](https://stackblitz.com/edit/ids-quick-start-1443-app-bgnvxw?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fdatagrid-paging-data.ts,tsconfig.json,src%2Fapp%2Fapp.component.css)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
When When i run the stackblitz it just hangs. Any other way to reproduce?
Can you suggest a fix / PR for it?

**Comment by ojadhav1** [comment]
Hi,
The Stackblitz link is working for me. Please refresh the link if you are facing any issues while loading StackBlitz.
