### ISSUE TITLE
Button: colors issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7406]
**Describe the bug**
when using dark mode buttons are off in all colors but default
when using light | high contrast buttons are off in all colors but default & alabaster

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/button/example-index.html
2. Switch to dark mode
4. Observe button colors 
5. hover over the buttons
6. Notice that buttons are off in all colors but default
7. Switch to Light | High contrast mode
8. Observe button colors 
9. Notice that buttons are off in all colors but default & alabaster

**Expected behavior**

**Version**

- ids-enterprise: v4.82.0-dev

**Screenshots**
<img width="1592" alt="image" src="https://user-images.githubusercontent.com/56722184/229969852-3f1e3114-c73c-4555-91ea-9da8861e8f7b.png">

**Platform**
All
**Additional context**
related to https://github.com/infor-design/enterprise/issues/7215

**Comment by tmcconechy** [comment]
For next issue @andriivarhanov 
I think you worked on this recently? but due to all the changes we made on buttons its not looking great at the moment again.

**Comment by andriivarhanov** [comment]
sure, I will check
