### ISSUE TITLE
File Upload Component: Can't exit the CAP window

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#741]
**Describe the bug**
File Upload Component: Can't exit the CAP window

**To Reproduce**
1. Go to url: http://4100-beta1-enterprise.demo.design.infor.com/components/fileupload/test-cap.html
2. Click on "Contextual Action Panel" 
3. The "Company Information" panel window appears
4. Click on the file icon and select a file
5. The file is successfully uploaded 
6. There is no way for the user to get out of the CAP window. An "X" or a "Close" button is needed in order to exit the CAP

**Expected behavior**
The user should be able to exit the CAP

**Screenshots**
![file upload](https://user-images.githubusercontent.com/39101346/45041292-ea921e80-b035-11e8-8e35-7c36f45e859b.png)

**Platform**
- All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
Might just be an example issue. The idea would be to ensure an X is shown like the other modal examples, so compare to the modal code samples
