### ISSUE TITLE
ListBuilder Component: None of the features on the toolbar are working correctly

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#742]
**Describe the bug**
On Mac Chrome version 68, the Add, Move Up, Move Down, Edit, and Delete feature is not working

**To Reproduce**
1. Go to URL: http://4100-beta1-enterprise.demo.design.infor.com/components/listbuilder/example-index.html
2. Click on any of the features on the toolbar, or click on the "+" to add a new item to the list box
3. Nothing happens. None of the features on the toolbar are working

**Expected behavior**
When the user clicks on the "+" button it should put a place hold in the list box to add a new item to the list box.

**Screenshots**
![listbuilder](https://user-images.githubusercontent.com/39101346/45042600-14991000-b039-11e8-98f0-4fd38c30dccc.png)

**Platform**
- MAC 
 - Browser Chrome[e.g. chrome, safari, stock browser]
 - Browser Version [68]

**Additional context**
None

**Comment by clepore** [comment]
> @EdwardCoyle that component isn’t invoking, it’s not getting to the point where the toolbar gets setup.

**Comment by clepore** [comment]
Console error:

<img width="564" alt="screen shot 2018-09-04 at 12 41 50 pm" src="https://user-images.githubusercontent.com/742319/45045071-ee2aa300-b03f-11e8-9ff5-7619efc9aa2e.png">

**Comment by clepore** [comment]
This seems to have been broken by the fix for https://github.com/infor-design/enterprise/issues/742 with [this commit](https://github.com/infor-design/enterprise/commit/68a1c913fc81f54205619c4910066a19fe0f57da#diff-86b5f0bcf06e1b0cb84479f9590cd538R154) in PR https://github.com/infor-design/enterprise/pull/669

**Comment by brianjuan** [comment]
http://4100-rc0-enterprise.demo.design.infor.com/components/listbuilder/example-index.html
QA verified, bug fix is working on all browsers.

**Comment by tmcconechy** [comment]
This should be closed i assume...
