### ISSUE TITLE
Icons: Missing icon when using version "classic"

### ISSUE THREAD

**Issue by ablomq** [infor-design/enterprise#7420]
**Describe the bug**
The shopping-basket icon is missing when running version "Classic". It works when running version "New". 

**To Reproduce**

Version New:
![image](https://user-images.githubusercontent.com/42343009/231197397-5747a87c-5f49-45f0-b473-22e7070fb87d.png)

Version Classic:
![image](https://user-images.githubusercontent.com/42343009/231197537-30ae986a-6035-4b68-97e8-ee4d7a9da830.png)

**Expected behavior**
Add missing icon.

**Version**
- ids-enterprise: [v4.82.0]

**Comment by tmcconechy** [comment]
If you need portability between classic and new please use the cart icon its close enough. (even if the text says basket).

cc @inforandy
