### ISSUE TITLE
Listview: Dataset does not update after removal

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#7423]
**Describe the bug**
After removing a node from a listview, the listview's `settings.dataset` does not change. Can this setting be updated after a node is removed or is there another place I can find the updated list after a remove?

**To Reproduce**

1. Go to http://localhost:4000/components/listview/test-remove-clear.html
2. Check `$('#multiselect-listview').data('listview')` in the dev console and see `settings.dataset`
3. Click on a checkbox to select a node
4. Select Remove
5. Check `$('#multiselect-listview').data('listview')` in the dev console and see that `settings.dataset` is the same as before the removal

**Expected behavior**
I would like some way for the updated list to be accessible or the `settings.dataset` to update after a node is removed.

**Version**
- ids-enterprise: v4.82.0-dev

**Screenshots**
![remove-update-listview](https://user-images.githubusercontent.com/76002134/231543597-c36df273-bb16-4e3e-8dd5-4daf3e50d203.gif)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 112.0.5615.50 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
You might want to look a the list builder https://main-enterprise.demo.design.infor.com/components/listbuilder/example-index.html because listview doesnt really store the dataset and maintain it like that one does.

That being said i guess it wouldnt be too much to remove the selected rows from the dataset and clear them if thats the only functions.

Aside from that a workaround would be to manually set the dataset at the same time you call the listview API

**Comment by s-werking** [comment]
Hi @tmcconechy, we are currently implementing your suggested workaround. It just seemed like something the controls component would keep track of instead of us. It would be nice if down the road we could get rid of some code that manually rebuilds the list with the updated dataset.

We looked into using other components for this but the layout of a listview fits best for our use case, specifically the card's header:
![image](https://user-images.githubusercontent.com/76002134/231553127-98b3cf9a-5d92-4d9d-88c6-0be2cb8e7a5f.png)

**Comment by tmcconechy** [comment]
Got it - seems like something we could add
