### ISSUE TITLE
Builder: subheader issue

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7430]
**Describe the bug**
Subheader is not fit within the border/background in all examples

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/builder/example-builder-nosidebar.html
https://main-enterprise.demo.design.infor.com/components/builder/example-builder-subtitle-test.html
https://main-enterprise.demo.design.infor.com/components/builder/example-builder-subtitle-test.html
https://main-enterprise.demo.design.infor.com/components/builder/example-builder.html
2. See error

**Expected behavior**
Subheader should fit within the border/background

**Version**

- ids-enterprise: 4.82.0-dev

**Screenshots**
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/102151352/231760925-d7492a36-43b4-4731-974c-37020db6688a.png">

**Platform**
 - All major browsers

**Comment by yohannahbautista** [comment]
Hello, checking main and local and it looks to already be fixed
<img width="408" alt="image" src="https://user-images.githubusercontent.com/85279127/235845501-4c00684e-c48e-4ff4-933d-e8787cb03833.png">
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/85279127/235845550-fe6496f3-ea45-4d8f-8a07-560128c783f5.png">

**Comment by tmcconechy** [comment]
Yeah i think this is a duplicate. Looks fixed.

QA: Can you verify as a duplicate issue on the links on main

**Comment by glenlieorillo** [comment]
Tested and passed.

Tested in: https://main-enterprise.demo.design.infor.com/components/builder/example-builder-nosidebar.html
https://main-enterprise.demo.design.infor.com/components/builder/example-builder-subtitle-test.html
https://main-enterprise.demo.design.infor.com/components/builder/example-builder-subtitle-test.html
https://main-enterprise.demo.design.infor.com/components/builder/example-builder.html

https://user-images.githubusercontent.com/102151352/235937440-f2c6f1ae-3f26-4d41-8446-04ff714ad446.mov
