### ISSUE TITLE
Masthead: Button hover state is inconsistent

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7433]
**Describe the bug**
Need to "correct" masthead button state as due to button change its a bit off.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/masthead/example-index.html
2. Hover each button
3. Some just change color (old style), some have a wrong azure background

**Expected behavior**
background-color:  #47474C
color: (icon): white

As a suggestion so its like other places but will review with design

**Comment by hey-yall** [comment]
Jira ticket created for designer feedback -- https://jira.infor.com/browse/IDS-1068

**Comment by tmcconechy** [comment]
should be solved by #7481
