### ISSUE TITLE
Counts(component): Inherit background color when widget is on banner

### ISSUE THREAD

**Issue by MadhuKiran4247** [infor-design/enterprise#7434]
We have discussed this issue on below IDS teams channel.

https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1677496796882?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1677496796882&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1677496796882&allowXTenantAccess=false

**Comment by yohannahbautista** [comment]
> @MadhuKiran4247 can you edit the bug and put it in the bug reporting template https://github.com/infor-design/enterprise/issues/new?assignees=&labels=&template=bug_report.md this is pretty hard to do anything with. We need to take the discussion and turn it into a bug or feature? based on what we are seeing https://github.com/infor-design/enterprise/issues/new/choose
> 
> Do note we did make this work on #7234 so maybe that issue is enough. But we are finding the counts dont work very well with all the colors. So maybe consider an alternate placement where its not in a color background.
> 
> Have a look at that issue and see if it covers it. If not can you reformat this issue into a bug or feature request thats more concrete?

Hello, we already have an example page with card/widget inheriting the header color here: https://main-enterprise.demo.design.infor.com/components/counts/example-header.html
If that isn't the scenario you expected, would it be possible to give a sample implementation and more details? The thread in the support channel doesn't really explain how you want to use counts. There isn't any code to base this on, so most of what's done is from assumptions.

**Comment by tmcconechy** [comment]
Was not able to reproduce this.
