### ISSUE TITLE
toolbar-flex throws exception when action-link-button does not have data

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#7438]
**Describe the bug**
In `renderButtonSet()` there's two different for-loop, which add/remove className hidden. In some cases `action-link-button` does not have any data stored, and will therefore throw an exception since there are no additional check before  `parent()` is called.

**Expected behavior**
No exception thrown

**Version**
- ids-enterprise: 4.82.0

**Comment by tmcconechy** [comment]
@guoliang do you plan on PRing this

**Comment by danielortiz1982** [comment]
PR on 4/17/2023
