### ISSUE TITLE
Display alignment of the empty state is not consistent among widgets

### ISSUE THREAD

**Issue by hey-yall** [infor-design/enterprise#7440]
**Describe the bug**
Received a bug ticket in the IDS Jira about empty state images not aligning properly in the widgets. Can we check the padding/alignment across our widgets? Thanks! 

![image](https://user-images.githubusercontent.com/122995837/232526447-7d21d27e-80d8-4f94-9525-d088963248d1.png)

Component: Empty State 

Product: LN: Contract Manager

Contact Person: Sudha Addala, Srinithya Pulavarthy 

**Originally submitted as Jira ticket [IDS-968](https://jira.infor.com/browse/IDS-968)**

**Comment by tmcconechy** [comment]
Should be fixed by https://github.com/infor-design/enterprise/pull/7415 (this was already reported)

**Comment by hey-yall** [comment]
Fixed by 7415. Closing issue.
