### ISSUE TITLE
PORTAL V2_4.80.0 -- IDS Button content not centered when button features an icon

### ISSUE THREAD

**Issue by hey-yall** [infor-design/enterprise#7443]
**Describe the bug**
Originally submitted as Jira bug ticket [IDS-913](https://jira.infor.com/browse/IDS-913). In Portal V2, the alignment for buttons with icons is off. Can we check on this?

> New buttons that have icons in them don't center content. One side has more space than the other. 

![image](https://user-images.githubusercontent.com/122995837/232551587-34dc682f-ebbe-4b71-96a9-0bf2c29ef5ad.png)

Thanks, dev team!

**Comment by tmcconechy** [comment]
cc @talkaboutdesign

**Comment by tmcconechy** [comment]
Could not reproduce
