### ISSUE TITLE
Homepage/Widgets: Change the sizes/gutter and banner sizes

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7445]
**Is your feature request related to a problem or use case? Please describe.**
Change the gutter, banner and home page widget sizes. The changes would be in homepage.js and homepage.scss

**Describe the solution you'd like**
Test all example scenarios https://main-enterprise.demo.design.infor.com/components/homepage and see that it all works out.

**Additional context**
https://jira.infor.com/browse/IDS-989

**Comment by CindyMercadoReyes** [comment]
BDD attached. Kind regards, Cindy
[BDD_github7445.docx](https://github.com/infor-design/enterprise/files/11407956/BDD_github7445.docx)
