### ISSUE TITLE
When I gave the legend placement to bottom in donut chart the legends are not visisble

### ISSUE THREAD

**Issue by spendker** [infor-design/enterprise#7449]
**Describe the bug**
Hi team,I am facing an issue where legends are not visible when I put the legendplacement to bottom.

**To Reproduce**
Please refer this below stackblitz to reproduce the issue
https://stackblitz.com/edit/ids-quick-start-1421-v4c3jq?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.css

**Expected behavior**
The legends has to show when I give the legendplacement to bottom

**Version**

- ids-enterprise: 4.80.3

**Screenshots**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/121223526/233007071-31387c69-0263-4b0b-94ba-2e8535029ada.png">
<img width="958" alt="image" src="https://user-images.githubusercontent.com/121223526/233007202-abf9518e-5b5a-4f00-a37b-c1b53632fb12.png">

**Platform**
 - Infor Application/Team Name: LN-Widgets
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Windows 11
 - Browser Name: google chrome
 - Browser Version: 112.0.5615.121

**Additional context**

**Comment by ericangeles** [comment]
@spendker, I identified and resolved all of the issues in this thread 

https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1681886036237?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1681886036237&teamName=IDS%20Enterprise%20Development&channelName=Angular%20Components&createdTime=1681886036237&allowXTenantAccess=false

**Comment by tmcconechy** [comment]
Thanks @ericangeles
