### ISSUE TITLE
Homepage: Circle pager is not visible in Alabaster 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#7450]
**Describe the bug**
Homepage: Circle pager is not visible in Alabaster 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/homepage/example-widget-two-column.html?colors=ffffff
2. Switch to other color
3. Notice the circle pager appears on all colors but not in Alabaster

**Expected behavior**
Circle pager should be visible in Alabaster. 

**Version**

4.83-ids-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/45757016/233077348-8306bebe-119b-4009-b889-923f7e964704.png)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by andriivarhanov** [comment]
@janahintal the issue might be fixed already, I don't see it on https://main-enterprise.demo.design.infor.com/components/homepage/example-widget-two-column.html?colors=ffffff , could you please check on your end?

**Comment by ericangeles** [comment]
Looks okay as well. Moving to Ready for QA.

**Comment by janahintal** [comment]
Passed. Verified in https://main-enterprise.demo.design.infor.com/components/homepage/example-widget-two-column.html 
on all modes, colors and theme. Thanks!
