### ISSUE TITLE
Donut: Improve legend labels position

### ISSUE THREAD

**Issue by spendker** [infor-design/enterprise#7452]
**Describe the bug**
In the Donut chart when the legend placement is bottom the the legend text overflowing because of this donut chart is taking less space.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-single-widget.html
2. Open dev console to change dataset and re-render chart (with "Regulars", see issue, if "Regular" shows fine). Paste below and Enter

```
var pieData = [{
       centerLabel: '<tspan x="0.15em" dy="-0.1em" style="font-size:1.6rem">Total Hours</tspan> <tspan x="0" dy="1.4em" style="font-size:1.6rem">265</tspan>',
       data: [{
           name: 'Regulars',
           value: 192,
           tooltip: 'Regular 192'
         }, {
           name: 'Unpaid',
           value: 24,
           tooltip: 'Unpaid 24'
         }]
       }];

       $('#pie-chart-example').chart({
         type: 'donut',
         dataset: pieData,
         showLegend: true,
         legendPlacement: 'bottom'
       });
```

**Expected behavior**
Legends should be properly aligned regardless of the texts length

**Version**

- ids-enterprise: 4.80.3

**Screenshots**
<img width="323" alt="image" src="https://user-images.githubusercontent.com/121223526/233340080-44d16b65-8703-44e3-89e9-fc161cd24041.png">
<img width="226" alt="image" src="https://user-images.githubusercontent.com/121223526/233340357-a772b6c6-7e61-4c65-9238-859a405e1d3c.png">
.

**Platform**
 - Infor Application/Team Name: LN-Widgets
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 112.0.5615.138 (Official Build) (64-bit)
**Additional context**
.

**Comment by tmcconechy** [comment]
How would you expect it to look? Could you use shorter labels or change position?

**Comment by ericangeles** [comment]
@tmcconechy, I recommended that too, but they didn't want to change the text that is coming from the data and confuse the current user, according to them.

**Comment by spendker** [comment]
@ericangeles,If the chart text has more characters then what if we do overflow elipsis and when we hover on it we can show full text,
Or everytime we show popover if the legends are multiple

**Comment by spendker** [comment]
Hi @ericangeles, @tmcconechy This issue is still not resolved in the homepage widgets if the label having more characters.
<img width="406" alt="image" src="https://github.com/infor-design/enterprise/assets/121223526/e2aaf982-32d5-483c-9c6a-b6924a7ba3ff">
This is issue got escalated for me,Can you please check this.

**Comment by tmcconechy** [comment]
@spendker maybe thats a new issue? Or is it exactly like above? Also the version in the screen shot is somewhat old. Do we need an example?

**Comment by spendker** [comment]
@tmcconechy, In which version this issue gets resolved.

**Comment by tmcconechy** [comment]
This was fixed in 4.84 but i would take the latest 4.90.0

**Comment by spendker** [comment]
Hi @tmcconechy,I have seen in the example code that bottom-legend popover is not visible untill we open the devTools
https://latest-enterprise.demo.design.infor.com/components/donut/example-legend-bottom?theme=uplift&variant=light&layout=embedded

**Comment by spendker** [comment]
FYR,
![image](https://github.com/infor-design/enterprise/assets/121223526/f3ac977f-0004-4461-9034-b39a0e6a31ed)
