### ISSUE TITLE
Charts: Force overflowing popupmenu legends

### ISSUE THREAD

**Issue by spendker** [infor-design/enterprise#7453]
**Is your feature request related to a problem or use case? Please describe.**
We are facing Design issue for donut which have the less character length. [e.g. {Component Name} has a problem when {...}]

**Describe the solution you'd like**
Implement a feature that will force the popup menu legends to display regardless of the length of the text. 

If the donut chart legends have the feature of popover which is having for longer text legends if it is also apply for less characters it will be looks good. [e.g. {Component Name} would work better if {...}]

**Describe alternatives you've considered**

**Additional context**
<img width="298" alt="image" src="https://user-images.githubusercontent.com/121223526/233343326-649996be-cc06-4a87-8c8c-831ee21a36c6.png">
In the above pic if we get the popover design it will be really looks great.
And what application do you work on? [e.g. {Infor XYZ}]

**Comment by ericangeles** [comment]
@tmcconechy @danielortiz1982 @inforandy  I have spoken with both the homepages team and the content developers regarding this issue. This can help them resolving any issues that arise from data that cannot be handled within the component (UI per se). We can consider adding this task to the next sprint.

Also this one https://github.com/infor-design/enterprise/issues/7452

**Comment by tmcconechy** [comment]
@spendker I don't understand whats wanted here? You want an example that looks exactly like that design? 

https://main-enterprise.demo.design.infor.com/components/pie/test-legend-below.html is similar but a pie instead of a donut.

Also bar charts can be just as clear and easy to position.

**Comment by ericangeles** [comment]
@SofiK can also give more information about this

**Comment by spendker** [comment]
@tmcconechy, the major problem I am facing in the widget is if more no.of  legends in the bottom is occupying the more space because of this Actual donut chart is fit in less space.
Ex:https://design.infor.com/code/ids-enterprise/latest/demo/components/donut/example-legend-bottom-single-widget.html

instead of this If I get the popover evrytime if the legends are more than one then the chart will looks better. 
Ex:https://design.infor.com/code/ids-enterprise/latest/demo/components/donut/example-legend-bottom-popup.html

**Comment by tmcconechy** [comment]
yes it sounds like you want https://design.infor.com/code/ids-enterprise/latest/demo/components/donut/example-legend-bottom-popup.html

Can you just implement that example on your end? Another thing you can do is change the size of the pie chart part to reduce space. To do that make a div where you put it and set height and width and the pie will size to that chunk.

**Comment by tmcconechy** [comment]
ok i can see fixing the legend layout and the popup becoming automatic. Lets discuss when we groom

**Comment by danielortiz1982** [comment]
@tmcconechy and @ericangeles when you have a moment can you please update this issue with the designs. Ty.

**Comment by tmcconechy** [comment]
Should look like this https://main-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-popup.html but forced via a setting.
