### ISSUE TITLE
Editor: uses non-unique IDs for image insertion

### ISSUE THREAD

**Issue by gushanson** [infor-design/enterprise#746]
**Describe the bug**
The input field of the modal used to insert an image has id="image". This can cause an issue when using multiple editors since the id is used to target the input and get the image URL.

**To Reproduce**
1. Go to http://usalvlhlpool1.infor.com/4.6.0-rc/components/editor/example-index
2. Click on the Insert Image button
3. Inspect the input field and observe that the id is "image".

**Expected behavior**
The id is unique.

**Comment by tmcconechy** [comment]
@gushanson what browser / os are you testing this on. Tried Mac os chrome and safari, and the image is just `<img src="https://imgplaceholder.com/250x250/368AC0/ffffff/fa-image">` with no ide. Also guessing you mean img not input?

Testing on http://master-enterprise.demo.design.infor.com/components/editor/example-index loads an image the 4.6.0 link doesnt work anymore.

**Comment by gushanson** [comment]
![screen_image](https://user-images.githubusercontent.com/4129417/45404047-ac13e980-b65d-11e8-8f28-e2fea4e2e897.PNG)
No I actually do mean input :) I hope the screenshot makes things clear. Notice how the input has id="image". Since this (non unique) id is used to fetch the input value, we've noticed issues when using multiple editors on a page.

**Comment by tmcconechy** [comment]
Got it, this can be reproduced on http://master-enterprise.demo.design.infor.com/components/editor/test-several-on-page.html

We need to change editor.js around line 912 to...
```
    <label for="image-${this.id}">${Locale.translate('Url')}</label>
    <input id="image-${this.id}" name="image-${this.id}" type="text" value="${this.settings.image.url}">
```

And make sure that the insert image still works after...

**Comment by tmcconechy** [comment]
In addition to that you probably also need to update this line to also use the ID.
https://github.com/infor-design/enterprise/blob/master/src/components/editor/editor.js#L826

**Comment by tmcconechy** [comment]
This change seems to work on my end...
![screen shot 2018-09-14 at 9 33 22 am](https://user-images.githubusercontent.com/814283/45553214-452f3580-b801-11e8-96b7-0a14ff5127e1.png)

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/editor/example-index.html
Passed QA testing, working across all browsers.
