### ISSUE TITLE
Editor: Table border not rendering when created using HTML and switching to VISUAL

### ISSUE THREAD

**Issue by gilbugauisan** [infor-design/enterprise#7463]
**Describe the bug**
When pasting an html string that has a table in it to the HTML editor, and switching it back to VISUAL editor, table border is not being rendered.

**To Reproduce**
1. Go to 'https://main-enterprise.demo.design.infor.com/components/editor/example-dirty-tracking.html'
2. Click HTML from the toolbar
3. Paste the html string from this file ([table-border-not-rendering.txt](https://github.com/infor-design/enterprise/files/11329042/table-border-not-rendering.txt))
4. Click VISUAL from the toolbar
5. See result

**Expected behavior**
Table border should be displayed

**Version**
- ids-enterprise: 4.82.0-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/74726741/234471932-cb61ce01-99e7-449a-9c67-7fdd540342c4.png)

**Platform**
 - Infor Application/Team Name: Infor Landmark
 - Device: (if applicable): Laptop
 - OS Version: Windows 11
 - Browser Name: edge
 - Browser Version: 112.0.1722.58 (Official build) (64-bit)

**Comment by tmcconechy** [comment]
I think you need another css property? But will have to dedicate sprint time to this. I couldn't figure it out on quick glance.

**Comment by gilbugauisan** [comment]
The customer's complaint is when they paste it on random online html editor, they can see the borders.

**Comment by ericangeles** [comment]
@gilbugauisan, looking at the HTML provided above, I don't see any custom CSS that will add a border color to the table.
