### ISSUE TITLE
Header: text look disabled in dark mode

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7465]
**Describe the bug**
when using dark mode with  default color the  text look disabled.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-tabs-alternate.html?colors=default&theme=new&mode=dark
2. See error

**Expected behavior**
with other color, the text is white.

**Version**

- ids-enterprise: v4.83.0-dev

**Screenshots**
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/56722184/234566393-cd7ee0d2-279f-4fc8-ad7b-b61328deef4b.png">

**Platform**
All

**Additional context**

**LINKED JIRA TICKET**: https://jira.infor.com/browse/IDS-1351

**Comment by tmcconechy** [comment]
Think this can go up one or two colors in the range

**Comment by hey-yall** [comment]
Jira design QA ticket created: https://jira.infor.com/browse/IDS-1351

**Comment by tmcconechy** [comment]
Note: Use Slate 05 for disabled state

**Comment by jbrcna** [comment]
QA Passed.
<img width="827" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/eb6f9188-f04a-47e8-9e51-29ee70eae8a1">

<img width="849" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1342a0a7-e45d-465d-8777-8177a2e87bac">
