### ISSUE TITLE
Modal closes on accordion click

### ISSUE THREAD

**Issue by nbcp** [infor-design/enterprise#747]
**Describe the bug**
If you click on an accordion inside the modal, it closes the modal. This issue just happened recently.

**To Reproduce**
Here is a fiddle to replicate the issue: https://jsfiddle.net/xpvt214o/747881/

**Expected behavior**
The modal should remain open and clicking the accordion should just expand its pane.

**Screenshots**
![accordion-closes-modal](https://user-images.githubusercontent.com/11013464/45083863-6c19a780-b12f-11e8-92da-ba5ee5d3ff3c.gif)

**Platform**
Any

**Comment by ericangeles** [comment]
Hi @clepore , where can I replicate this issue?

**Comment by nbcp** [comment]
@ericangeles I just fixed that bad jsfiddle link. You should be able to replicate from there now.

**Comment by tmcconechy** [comment]
I just tested this and its still a bug in 4.10.0 https://jsfiddle.net/6p72nbvr/1/

**Comment by ericangeles** [comment]
Seems that ```$('body').children().not('.application-menu').closeChildren();``` in `accordion.js` causes the modal to close upon clicking the accordion.

**Comment by tmcconechy** [comment]
I wouldnt remove it, its there to close any open menus. But perhaps you can add .modal to it..

```
$('body').children().not('.application-menu, .modal').closeChildren();
```

See if that works?

**Comment by ericangeles** [comment]
Unfortunately, it didn't work.

**Comment by ericangeles** [comment]
I change the selector to `.modal-page-container' and it works.
