### ISSUE TITLE
Popupmenu item not entirely highlighted when item is longer than viewport.

### ISSUE THREAD

**Issue by yousef-elkaisi** [infor-design/enterprise#7476]
**Describe the bug**
When a popupmenu item is longer than the viewport and the menu needs to be scrolled, only part of the item gets highlighted. As you scroll to the right, the rest of the item is not highlighted.

**To Reproduce**

Create a popupmenu with at least one item. Make the item text is very long so that it stretches beyond the viewport. When you open the menu and hover over the item and scroll to the right you will see some of the item is not highlighted.

**Expected behavior**
Entire item should be highlighted.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://user-images.githubusercontent.com/132393590/235756150-adf5747c-7e80-4406-8972-00d65e5846b3.png)
![image](https://user-images.githubusercontent.com/132393590/235756288-96da8a29-4d37-4af5-adcb-380336524d4f.png)

**Platform**
 - Infor Application/Team Name: WFM/ Team Supernovas
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 110

**Additional context**

**Comment by tmcconechy** [comment]
Can this be avoided?
