### ISSUE TITLE
Header: missing/utilize flex

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7479]
**Describe the bug**
 in examples to use flex toolbar by default. Replaces toolbar with flex toolbar in all header examples. some pages have no `flex-toolbar`

**To Reproduce**

1. Go to http://localhost:4000/components/header/example-long-title-with-button.html
http://localhost:4000/components/header/example-no-title-button.html
http://localhost:4000/components/header/example-searchfield-large.html
2. See error

**Expected behavior**
all EPs in header should utilize flex

**Version**

- ids-enterprise: v4.83.0-dev

**Screenshots**
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/56722184/235849749-4aeec398-0199-44d3-a7a2-c5be34e88f38.png">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
related to https://github.com/infor-design/enterprise/pull/7470

**Comment by tmcconechy** [comment]
This can be very low priority. Maybe even do it later with all the other stuff

**Comment by tmcconechy** [comment]
Push this back to 4.87 for now. We have a lot

**Comment by jbrcna** [comment]
QA Passed
<img width="1646" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/acab91bd-d0b1-434d-97a0-1978818e4796">

<img width="1680" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/c99fe5a6-4469-4969-bd21-574307561774">

<img width="1671" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/17e00bfc-9878-4de5-a520-716e1f2edf92">
