### ISSUE TITLE
Add Tree disable() method

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#748]
**Is your feature request related to a problem? Please describe.**
A feature method to disable the entire Tree.

**Describe the solution you'd like**
The assumed solution is the ability to disable the entire Tree by disabling each node.

**Describe alternatives you've considered**
An alternative solution could be disabling the parent element in Tree and styling the nodes as disabled based on a parent class.
An additional method could be to disable a single node.

**Additional context**
Parent issue: #561 .

**Comment by CindyMercadoReyes** [comment]
This ticket is now resolved. Moving it to the Done folder.
