### ISSUE TITLE
Masthead update -- new design

### ISSUE THREAD

**Issue by danielortiz1982** [infor-design/enterprise#7481]
Maks Petriv is updating the masthead; it will move away from black which we had used in the past. This will need to be added into IDS as an update.

Definition of Done: The new finalized masthead will reflect on both the demo site and on design.infor.com for customer consumption. 

More details:  TBD...

Jira Number `IDS-931` depends on `SCRMPORTALV2-5865`

Example URL:
https://design.infor.com/product/components/masthead

**Comment by tmcconechy** [comment]
I have questions if we can fit this in the this sprint with the current bandwidth and tasks

**Comment by inforandy** [comment]
final designs for the masthead updates here. these were in the jira ticket since march, but I am posting here as well https://www.figma.com/file/WYGbzemcaZzgNY6N0qeyo0/Portal-Masthead-Enhancement?node-id=0%3A1&t=TVKPN99A7cBQ0nFe-0

**Comment by danielortiz1982** [comment]
JIRA ticket is closed, closing this issue for now.
