### ISSUE TITLE
Editor: Track dirty's reset dirty incorrect when a &nbsp; is only value inside a tag

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#7483]
**Describe the bug**
A dirty indicator is being incorrectly applied when afterDirty is being called on an editor with a value that has a &nbsp; as the only content inside a tag:

`

        <p class="MsoNormal">‘smart quote’</p>

        <p class="MsoNormal">&nbsp;</p>

        <p class="MsoNormal">“double smart quote”</p>

        <p class="MsoNormal">&nbsp;</p>

        <p class="MsoNormal">nothing</p><p class="MsoNormal"><br>
      </p><p class="MsoNormal">'regular single'</p><p class="MsoNormal"><br>
      </p><p class="MsoNormal">"regular double quote"</p><p class="MsoNormal"><br>
      </p><p class="MsoNormal">nothing</p>`

**To Reproduce**

1. Copy [test-reset-dirty-with-nbsp.html.txt](https://github.com/infor-design/enterprise/files/11391224/test-reset-dirty-with-nbsp.html.txt) into /app/views/components/editor. Ensure to rename it to just an html file
2. Navigate to '/components/editor/test-reset-dirty-with-nbsp.html' in your app
3. Make no changes, and just press the Reset Dirty button
4. See error, the dirty indicator now appears incorrectly

**Expected behavior**
Reset Dirty should not display an indicator, since no changes were made.

**Version**

- ids-enterprise: v4.80.3

**Screenshots**
![DirtyIndicatorEditor](https://user-images.githubusercontent.com/22107636/236051615-41f2e2fa-063b-4de2-a51a-10aa54ab3a0e.gif)

**Platform**
 - Infor Application/Team Name: Infor Landmark Web
 - All

**Comment by Sovia** [comment]
I did some debugging, and the issue in this block of code in trackdirty.js: https://github.com/infor-design/enterprise/blob/main/src/components/trackdirty/trackdirty.js#L247

`

          const textArea = field.find('textarea');
          original = this.trimEditorText(textArea.data('original'));
          current = field.find('.editor-source').is(':visible') ? textArea.val() : textArea.text();
          current = this.trimEditorText(current);
`

the value set on textArea.original already has trimEditorText called on it in https://github.com/infor-design/enterprise/blob/main/src/components/trackdirty/trackdirty.js#L167 's valMethod https://github.com/infor-design/enterprise/blob/main/src/components/trackdirty/trackdirty.js#L62 .

So the first call to trimEditorText changes the &nbsp; into ' ', and the second call trims it off. So since original and current don't match, we get a dirty icon.

**Comment by Sovia** [comment]
This is also happening on test-dirty-tracking-reset.html, when the initial value of the editor is set to:

`
      <div class="editor" id="editor1" role="textbox" aria-multiline="true" aria-label="Comments" data-trackdirty="true">
        Company Welcome Text...        Competencies and skills:<br />Essential:<br />* Customer Relations<br />* Flexibility<br /> Credentials:<br />Essential:<br />* Law Basics<br /> Education:<br />Essential:<br />* Associate of Arts<br />   EOE M/F/V/D
      </div>
`

This is causing editors to not behave correctly, and causing multiple issues in landmark web code.

**Comment by tmcconechy** [comment]
Would you consider not using the dirty indicator on complex components like Editor? i think we probably want to just get rid of this based on all the issues

**Comment by Sovia** [comment]
I think that just removing the trimEditorText() call in the valMethod() method would fix these issues. The trouble is that trimEditorText() is being called twice on the original string but only once for the current string. If it's only called once, then the strings match and it's not incorrectly seen as dirty.
