### ISSUE TITLE
Grid: Resizing the browser causes the grid components to adjust and move inside an accordion

### ISSUE THREAD

**Issue by glennreyesss** [infor-design/enterprise#7484]
**Describe the bug**
Resizing the browser causes the grid components inside an accordion to break the layout of the grid. 

**To Reproduce**
Place a grid component inside an accordion-content and resize the browser.
The row is allocated to two divs that have five and seven columns respectively. 

https://stackblitz.com/edit/ids-enterprise-4811-pdfvqn?file=index.html
[web.txt](https://github.com/infor-design/enterprise/files/11392377/web.txt)

**Screenshot**
![image](https://user-images.githubusercontent.com/126537236/236093431-2c23fc71-5af9-47e3-ac2f-bb660bfddbe1.png)

**Recording**
https://user-images.githubusercontent.com/126537236/236092213-00b8ae4f-7a8b-44fd-b511-bd4ff86749a8.mp4

**Comment by tmcconechy** [comment]
Maybe you can use the 2 up on mobile for this https://main-enterprise.demo.design.infor.com/components/grid/example-simplified.html it looks like its going to the responsive grid single row. (or try something like an li)

**Comment by glennreyesss** [comment]
Thanks for the recommendation. I used "one-half-mobile" class and it did fix my issue. 
https://github.com/infor-design/enterprise/assets/126537236/d154ffcc-74c7-48eb-a755-2f2089a62fd3

You may proceed in closing this. Thanks again!

**Comment by tmcconechy** [comment]
Thanks!
