### ISSUE TITLE
Input/Icons: "icon-info-field" no longer exists

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#7485]
**Describe the bug**
`icon-info-field` seems to have been removed or possibly renamed.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/input/example-info
2. Notice that no icons are visible

**Expected behavior**
Not sure what's expected here... was the icon removed completely or maybe renamed? So either the icon should be brought back or the example should be updated.

**Version**
- ids-enterprise: 4.82.0

**Platform**
 - Infor Application/Team Name: Homepages / OS Portal

**Comment by radovaniljic** [comment]
@tmcconechy Yeah I just used `icon-info` instead. We were using `icon-info-field` and recently noticed that it had disappeared, but we couldn't remember what it actually looked like, so I thought I'd report it. But yeah, if they're identical there's no reason to have both.

**Comment by tmcconechy** [comment]
Sounds good. Lets close then. No need for extra dup icons if we can avoid it
