### ISSUE TITLE
Add Tree enable() method

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#749]
**Is your feature request related to a problem? Please describe.**
A feature method to enable the entire Tree.

**Describe the solution you'd like**
The assumed solution is the ability to enable the entire Tree by enabling each node.

**Describe alternatives you've considered**
An alternative solution could be enabling the parent element in Tree and styling the nodes as enabled based on a parent class.
An additional method could be to enable a single node.

**Additional context**
Parent issue: #561 .

**Comment by CindyMercadoReyes** [comment]
This request is now resolved. Closing out this GitHub ticket.
