### ISSUE TITLE
Toolbar: more than 3 buttons overlapping text

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7496]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar/example-more-than-three-buttons.html
2. Switch to mobile view
3. See error

**Expected behavior**
buttons should not overlap

**Version**

- ids-enterprise: v4.82.0-dev

**Screenshots**
<img width="414" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/367c6a9d-df31-4f3e-91a1-6cfd907a4119">

**Platform**
mobile

**Additional context**

**Comment by tmcconechy** [comment]
Will fix on https://github.com/infor-design/enterprise/issues/7733

**Comment by tmcconechy** [comment]
Was resolved when https://github.com/infor-design/enterprise/issues/7733 was addressed

**Comment by jbrcna** [comment]
EP not available in main
https://main-enterprise.demo.design.infor.com/components/toolbar/example-more-than-three-buttons.html
<img width="1204" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/7feca638-d827-4281-862b-90b8f18253e5">

but this is now working in local
<img width="392" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/60c46c26-f9b6-46eb-85b2-a8435b8c4263">
