### ISSUE TITLE
New typography "text-wrap"

### ISSUE THREAD

**Issue by lawinPatrick** [infor-design/enterprise#7497]
**Is your feature request related to a problem or use case? Please describe.**
Use case for word wrapping a long text 

**Describe the solution you'd like**
A new typography that will allow users to wrap a word using 'word-break: break-all'

**Describe alternatives you've considered**
Currently added a css rule to word wrap
![image](https://github.com/infor-design/enterprise/assets/131942709/31e9d6d0-d345-4d84-ad68-2bf137bfdc24)

**Comment by tmcconechy** [comment]
@lawinPatrick this would be a good one to contribute https://github.com/infor-design/enterprise/blob/main/docs/CONTRIBUTING.md#pull-requests

1. add class `text-wrap` to this file https://github.com/infor-design/enterprise/blob/main/src/core/_css-utilities.scss
2. add a change log entry for it

Maybe show it on https://github.com/infor-design/enterprise/blob/main/app/views/components/css-utilities/example-index.html or https://github.com/infor-design/enterprise/blob/main/app/views/components/typography/example-index.html

PR ....
