### ISSUE TITLE
Add Tree readonly() method

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#750]
**Is your feature request related to a problem? Please describe.**
A feature method to readonly the entire Tree.

**Describe the solution you'd like**
The assumed solution is the ability to readonly the entire Tree by readonlyifying each node.

**Describe alternatives you've considered**
An alternative solution could be readonlyifying the parent element in Tree and styling the nodes as readonly based on a parent class.
An additional method could be to readonlyify a single node.

**Additional context**
Parent issue: #561 .

**Comment by davidcarlsonberg** [comment]
Barring any disagreement, I'm closing this ticket as Tree is not editable by the user and therefore anything accomplished by a `readonly` state is accomplished by a `disabled` state. If, at some point, a user is able to edit nodes, perhaps then we can revisit to distinguish between `readonly` and `disabled` in the context of Tree.

**Comment by EdwardCoyle** [comment]
No argument here!
