### ISSUE TITLE
Card/Widget: "More Actions" button needs open state

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#7501]
**Describe the bug**
The new button styles implemented as part of the Card/Widget style enhancements (See #7480) are missing the menu button "open" state for when the menu is open

![Screen Shot 2023-05-12 at 9 07 25 AM](https://github.com/infor-design/enterprise/assets/3249601/2aae6196-7992-4a0b-826c-6d7302be965a)

**To Reproduce**
1. Go to http://localhost:4000/components/cards/example-borderless.html
2. Open any of the cards' "More Actions" buttons
3. See the button has no visible active state while the menu is open

**Expected behavior**
- The button's text color should be Azure 60 (text color is inherited by the icon's `fill` prop using `currentColor`)
- The background should be Azure 20
- These should be applied to the More Action button's `.btn-actions.is-open` class

**Comment by tmcconechy** [comment]
This is the correct open state from @talkaboutdesign and the designs. They made it this way and i questioned it as well because it is inconsistent but they wanted it this way and to be special.

**Comment by talkaboutdesign** [comment]
This is by design. Ignore.
