### ISSUE TITLE
Homepage: Make hero alabaster not personalization color

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7505]
**Describe the bug**

The hero image should no longer be able to take a personalization color. Remove the code in personalization that makes the color change.

Example: https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html 

https://jira.infor.com/browse/IDS-1066

cc @talkaboutdesign 

**To Reproduce**

- go to https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html
- in the ... menu change color
- should no longer have any effect on the hero. should stay white background.

Note: Dark and high contrast use page background.

**Expected behavior**
 should no longer have any effect on the hero. should stay white background.

**Comment by danielortiz1982** [comment]
Waiting on design to confirm colors for changes requested.

**Comment by talkaboutdesign** [comment]
@tmcconechy let me know what the hold up on this one is?

**Comment by tmcconechy** [comment]
No hold up just had to cycle it into a sprint based on everyones availability. Please check the PR now. I opened it up for QA..

https://github.com/infor-design/enterprise/pull/7781

@talkaboutdesign will be in 4.87

**Comment by jbrcna** [comment]
this is now working as expected. just an observation, the caret color is off when hovered.
<img width="1680" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/9fe36f57-60e7-4177-ba26-8121895994b2">

**Comment by volante007** [comment]
> this is now working as expected. just an observation, the caret color is off when hovered. <img alt="image" width="1680" src="https://user-images.githubusercontent.com/56722184/261331034-9fe36f57-60e7-4177-ba26-8121895994b2.png">

I think this is because the `.hero-widget` element still has class `.is-personalizable` in the sample. Should it really use that class now that it is white? Just wondering if we can safely remove it 

cc @tmcconechy

**Comment by jbrcna** [comment]
thanks for clarifying @volante007
