### ISSUE TITLE
Stats: New Component Similar to Counts

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7506]
**Describe the bug**

Needs to go in both component libraries (eventually). In the enterprise repo first. Designs are https://www.figma.com/file/vFSHOqtgm9ypxOtOTHoBjF/List-View-Cards?type=design&node-id=0-1&t=Op6UQdJJNZyGldN1-0

Replaces: https://main-enterprise.demo.design.infor.com/components/counts/example-widget-count.html

**Additional context**
May want to deprecate counts https://main-enterprise.demo.design.infor.com/components/counts/example-widget-count.html

**Comment by CindyMercadoReyes** [comment]
BDD attached. Kind regards, Cindy
[BDD_github7506.docx](https://github.com/infor-design/enterprise/files/11707855/BDD_github7506.docx)
