### ISSUE TITLE
Add Tree restoreOriginalState() method

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#751]
**Is your feature request related to a problem? Please describe.**
A feature method to restore the original state of the entire Tree prior to any disabling/enabling/readonlyifying.

**Describe the solution you'd like**
The assumed solution is the ability to restore the original state of the entire Tree by preserving the initial state of the Tree before any actions are done to any node.

**Describe alternatives you've considered**

**Additional context**
Parent issue: #561 .

**Comment by tmcconechy** [comment]
In other components we just used enable to make either readOnly or disabled enabled again, whats the difference between enable and restoreOriginalState ?

**Comment by davidcarlsonberg** [comment]
This method preserves any state disabled or enabled on any node from creation of the DOM and allows you to restore each node to that state incase any node's state was changed. See this comment: https://github.com/infor-design/enterprise/issues/561#issuecomment-410749803

**Comment by EdwardCoyle** [comment]
@davidcarlsonberg I'm re-reading my comment there and realizing that I wasn't totally clear.  What I was trying to convey was:

- It should be possible to enable/disable each individual node on its own.
- It should be possible to enable/disable the entire tree component as a whole.  When re-enabling the tree component, any individual nodes that were previously (individually) set to disabled/readonly should be put back in that state.

I think those requirements are actually met by the work you did here though.  If anything, it's more robust.

@tmcconechy for reference, the functionality I described above is present in Tabs, and has been asked for in Accordion before.  Tree seemed like a good candidate for this as well.

**Comment by davidcarlsonberg** [comment]
I'm happy to create another ticket for enabling/disabling individual nodes by ID if that's a desired functionality. Or can refactor existing to accept an argument of a single node and when not present, just do all.

**Comment by tmcconechy** [comment]
You can currently disable nodes with the api so i think thats covered. http://master-enterprise.demo.design.infor.com/components/tree/example-disabled.html enough. I dont think we need to spend much more time than whats requested on the original ticket.

**Comment by davidcarlsonberg** [comment]
Just needs a second review then.

**Comment by CindyMercadoReyes** [comment]
This ticket is now resolved. Closing out this GitHub ticket.
