### ISSUE TITLE
Tabs Module: Active tab is not a different color than inactive tabs

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#7516]
**Describe the bug**
The active tab is the same color as the rest of the tabs, making it difficult for users to tell which tab is active.

**To Reproduce**
1. Go to http://localhost:4000/components/tabs-module/example-category-searchfield-go-button-home.html
2. Select any color from the theme menu
3. Click on a tab to be active
4. See that the background color does not change

**Expected behavior**
The active tab's background color should be different from the rest of the tabs.

**Version**
- ids-enterprise: v4.83.0-beta.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/76002134/a886fcc9-8505-4e3c-bf0a-1772dfd68b3a)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 113.0.5672.93 (Official Build) (64-bit)

**Additional context**
Note this is a regression. Here is a past ticket:
- [#6236](https://github.com/infor-design/enterprise/issues/6236)

**Comment by tmcconechy** [comment]
see also https://github.com/infor-design/enterprise/issues/7293

**Comment by s-werking** [comment]
Hi @tmcconechy, since this is a regression from a previous fix could this be scheduled for an upcoming release?
