### ISSUE TITLE
Add Tree method tests

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#752]
**Is your feature request related to a problem? Please describe.**
Functional and e2e tests on disable(), enable(), preserveEnablementState(), restoreEnablementState()

**Describe the solution you'd like**
Write functional and e2e tests for new Tree methods mentioned above.

**Additional context**
Came from #561 .

**Comment by CindyMercadoReyes** [comment]
This ticket is now resolved. Moving it to the Done folder.
