### ISSUE TITLE
Treemap: Treemap doesn't fit within the border

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7538]
**Describe the bug**
Treemap doesn't fit within the border.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/treemap/example-nested.html
2. See error

**Expected behavior**
Treemap should fit within the border.

**Version**

- ids-enterprise: 4.83.0-beta.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/3bd5f874-0da2-4b00-b219-f451de6149b5)

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
This might be ok now as `auto-height`.

**Comment by tmcconechy** [comment]
yes looks good. i think we fixed it on an other card issue

**Comment by CindyMercadoReyes** [comment]
This issue is resolved.
