### ISSUE TITLE
Lookup: custom toolbar more actions btn not centered when focused

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7543]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/lookup/example-custom-toolbar.html
2. Open modal
3. See error

**Expected behavior**
<img width="544" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/f6655013-e0e7-4c20-aca7-329228e290f0">

**Version**

- ids-enterprise: v4.83.0-dev

**Screenshots**
<img width="573" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/b0da2e35-8bc3-4f43-b2c9-82fa058374a6">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
@jbrcna this was fixed on another PR and is ok now on https://main-enterprise.demo.design.infor.com/components/lookup/example-custom-toolbar.html have a look.

**Comment by jbrcna** [comment]
thanks @tmcconechy . this is also working now on my end
<img width="286" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/c646019f-666a-4eeb-99af-f48707522c38">
