### ISSUE TITLE
Listview: border highlight issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7545]
**Describe the bug**
the top border is missing on the first item

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/listview/example-index.html
2. Click on the first item
3. See error

**Expected behavior**
<img width="517" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ad7f66e2-1631-4a29-9a06-d9a55dee23b2">

**Version**

- ids-enterprise: v4.83.0-dev

**Screenshots**
<img width="321" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/efe7ab73-0709-4ba1-b667-0459cf4958ce">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Should look like the list on https://main-enterprise.demo.design.infor.com/components/cards/example-workspace-widgets.html

Maybe example needs to be updated

**Comment by jbrcna** [comment]
QA Passed.
