### ISSUE TITLE
Listview: filters misaligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7546]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/listview/example-filters.html
2. See error

**Expected behavior**
the filters should be properly aligned

**Version**

- ids-enterprise: v4.83.0-dev

**Screenshots**
<img width="490" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1b6e6e5a-470a-4aed-a0b9-36deed84c530">

**Platform**
All

**Additional context**

**Comment by talkaboutdesign** [comment]
> Should fix this to look more like the search on https://main-enterprise.demo.design.infor.com/components/cards/example-workspace-widgets.html - might be just partially a markup issue.

@tmcconechy It should match that search with two filters next to it on clear background. 

<img width="836" alt="CleanShot 2023-06-01 at 14 20 31@2x" src="https://github.com/infor-design/enterprise/assets/2926534/7e8ba3aa-8aab-4203-844f-2b20a8db5b3b">


https://www.figma.com/file/DxLvQRUlFFEf5cTuEICEEM/Widget-Enhancements-(documentation)?type=design&node-id=1239%3A9549&t=ckYTEeiNEKnHMAdy-1

**Comment by ericangeles** [comment]
Adding this to the `4.85.x` board.
