### ISSUE TITLE
Modal: Table inside popup modal does not show records

### ISSUE THREAD

**Issue by n-anello** [infor-design/enterprise#7548]
**Describe the bug**
The table inside a popup modal does not display records in Firefox. This issue does not occur in Chrome. I've identified that the issue occurs on line 1242 of reports-joblist.controls.js. I've attached two screenshots, one of the improper behavior in Firefox and one of the correct behavior in Chrome. Notice the difference in data in the console. We need a fix for 4.82.

![firefox](https://github.com/infor-design/enterprise/assets/134652550/963ebae9-765b-4494-9611-55b8be3c8f31)

![chrome](https://github.com/infor-design/enterprise/assets/134652550/536c297b-f7d9-421f-8aeb-1bbcd4a44c58)

**To Reproduce**

In Firefox, initialize a modal and a table inside the modal.

After initialization, add records to the table with updateDatagrid. 

**Expected behavior**
The table should contain records. 

**Version**
ids-enterprise: v4.68.0-dev

**Platform**
Infor Application/Team Name: lawson
OS Version: Windows 11
Browser Name: Firefox
Browser Version: 113.0.2 (64-bit)

Infor Application/Team Name: lawson
OS Version: Windows 11
Browser Name: Chrome
Browser Version: 113.0.5672.127 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@n-anello can you explain better how to reproduce this issue. Perhaps you can use the stack blitz https://stackblitz.com/edit/ids-enterprise-4830?file=index.js

- Not sure what you mean exactly by a table (a datagrid?)
- not sure if you mean popup or modal
- the code file mentioned does not appear to be one we own, so you might want to check with that codes owner whoever it is

I think if you made a proper code reproduction it should clarify this.

**Comment by tmcconechy** [comment]
Closed as per Andy B.
