### ISSUE TITLE
Datagrid: Date column filter does not match locale setting

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#7554]
**Describe the bug**
When using a date format that is different than (MM/dd/yyyy) on a column, the table's data is in the right format but when attempting to filter on the column, the format is in the MM/dd/yyyy format.

**To Reproduce**
1. Change the orderDate's dateFormat setting to 'yy/MM/dd' in http://localhost:4000/components/datagrid/example-filter.html
2. Go to http://localhost:4000/components/datagrid/example-filter.html
3. See that the data under the Order Date column is all the correct date format
4. Select the Order Date datepicker and select a date to filter on
5. See that the column filter field shows the selected date in the wrong date format (MM/dd/yyyy instead of yy/MM/dd)

**Expected behavior**
It is expected that the filter field shows the correct date format when entering a date to filter via the datepicker or manually.

**Version**
- ids-enterprise: 4.83.0-beta.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/76002134/79786bb5-fcc7-41a9-b71c-065d0b4a27b6)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 113.0.5672.127 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Does this work with 4 digit year and just not 2 digit year. Because we are trying to only support 4 digit year.
