### ISSUE TITLE
Locale: Italian. Refresh (tooltip) should be translated as "Aggiorna visualizzazione" (instead of "Aggiorna vista")

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#7559]
Locale: Italian. Refresh (tooltip) should be translated as "Aggiorna visualizzazione" (instead of "Aggiorna vista")

Issue raised by GRC tester:

![image](https://github.com/infor-design/enterprise/assets/66057969/6c7284b0-11b5-48f7-89ba-a9666c01c3b9)

**Comment by tmcconechy** [comment]
I checked our translations and cant find "Aggiorna vista" or "Aggiorna visualizzazione". So i presume this is an application translation they need to fix in GRC

**Comment by cpinatel7** [comment]
It's not from GRC as I cannot find it in our translation repository. It must be: Infor Ming.le Homepages (LIME). You can close this GitHub issue. Thanks

**Comment by tmcconechy** [comment]
ok maybe ~ can just say not in ours either. FYI this is the source file for us for future reference https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-locale/data/en-messages.ts
