### ISSUE TITLE
Page patterns: table edges are cut off

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7560]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/page-patterns/example-landing-page.html
2. See error

**Expected behavior**

**Version**

- ids-enterprise: v4.83.0-dev

**Screenshots**
<img width="1122" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/b657e1be-6b89-41b5-acc2-716feec6cab9">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Will fix this on https://github.com/infor-design/enterprise/issues/7733
