### ISSUE TITLE
Page patterns: searchfield not in full width

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7561]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/page-patterns/example-list-detail-search-paging.html
2. Click on searchfield
3. See error

**Expected behavior**
<img width="436" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1818bceb-49eb-4c56-bc5d-750dbd49f84c">

**Version**

- ids-enterprise: v4.83.0-dev

**Screenshots**
<img width="302" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/c44c0d89-a386-4c2b-9964-d82d6fd5ed7a">

**Platform**
all

**Additional context**

**Comment by tmcconechy** [comment]
I think it should be made to look like the search on https://main-enterprise.demo.design.infor.com/components/cards/example-workspace-widgets.html

**Comment by jbrcna** [comment]
QA Passed. moving this ticket to Done.
