### ISSUE TITLE
Wrong border color in soho-accordion-header

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#7565]
**Describe the bug**
Style issue with the `soho-accordion-header`

![image](https://github.com/infor-design/enterprise-ng/assets/542598/3584ca2a-bace-4348-9d35-6c7c1af53f88)

**To Reproduce**
1. Build and run enterprise-ng
2. Go to the first page

**Expected behavior**
Expect border-bottom-color to be correct

**Version**
- ids-enterprise-ng: 15.3.2

**Comment by tmcconechy** [comment]
Can easier be reproduced on https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-roles.html

Also BTW working on a new version of the app menu https://7386-add-nav-menu-enterprise.demo.design.infor.com/components/module-nav/example-index.html

**Comment by tmcconechy** [comment]
Lets see if we can fix this earlier

**Comment by tmcconechy** [comment]
cc @ericangeles
