### ISSUE TITLE
Sink Page: fileupload x icon hover state is not in full circle

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7570]
**Describe the bug**

**To Reproduce**

1. Go to https://4840-beta0-enterprise.demo.design.infor.com
2. Click on 'fileupload
3. upload a file
4. hover x icon
5. See error

**Expected behavior**

**Version**

- ids-enterprise: v4.84.0-beta0

**Screenshots**
<img width="900" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/14d90b25-87df-46e1-af9a-f5e5548b056f">

**Platform**
all

**Additional context**

**Comment by tmcconechy** [comment]
@tjamesallen15 can you aslo add a bit more space between the X and upload icon and make them have the same hover state?
