### ISSUE TITLE
Sink Page: editor text color button is off in shades of green

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7571]
**Describe the bug**

**To Reproduce**

1. Go to https://4840-beta0-enterprise.demo.design.infor.com/
2. Find the editor component
3. click text color button and select emerald (choose the 2nd emerald)
5. play around with other color to see difference
6. try also the hover state of button

**Expected behavior**

**Version**

- ids-enterprise:v4.84.0-beta0

**Screenshots**
<img width="978" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/3453493f-1704-47ef-86f8-cdb39317bf52">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Not really sure what to do here since it is the correct color. Will park this for now

**Comment by tmcconechy** [comment]
https://inforonline-my.sharepoint.com/:i:/g/personal/andrew_kopas_infor_com/EbBxZlUABl9LuADXzHLQ-6wBusgx5VMFGGo029QKByTgfg?e=Df2age

**Comment by jbrcna** [comment]
QA Passed
<img width="1359" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/dd0d958b-9947-418f-b678-81c128f84202">
