### ISSUE TITLE
Sink Page: toolbar x icon misaligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7572]
**Describe the bug**

**To Reproduce**

1. Go to https://4840-beta0-enterprise.demo.design.infor.com/
2. Find toolbar component
3. type a text in searchfield

**Expected behavior**
x icon should be properly aligned

**Version**

- ids-enterprise: v4.84.0-beta0

**Screenshots**
<img width="1108" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/6681e825-832d-4117-ba0a-18c651a47331">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Pushed to main by mistake. Also pushed to 4.84
