### ISSUE TITLE
Sink Page: breadcrumb 4th item is not aligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7573]
**Describe the bug**

**To Reproduce**

1. Go to https://4840-beta0-enterprise.demo.design.infor.com/
2. Find breadcrumb component

**Expected behavior**

**Version**

- ids-enterprise: v4.84.0-beta0

**Screenshots**
<img width="513" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ea77284b-188d-4689-a990-f470dd2c3fbb">

**Platform**
Safari

**Additional context**

**Comment by yohannahbautista** [comment]
Hello, I'm checking https://main-enterprise.demo.design.infor.com/ and local in Chrome, Safari, Edge, and Firefox and it looks to be fixed
<img width="565" alt="image" src="https://github.com/infor-design/enterprise/assets/85279127/ed9efd4f-43ed-4d60-86be-7ba2100ddc44">

**Comment by jbrcna** [comment]
can confirm on my end
`4.85.0-beta`
<img width="439" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/0f787d0d-57bf-49ad-a665-4bd56314da9e">

`main `
<img width="439" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/9a586bff-a587-4ae0-b2ba-382e4f9d36df">

**Comment by tmcconechy** [comment]
Ok i think this was fixed along side another issue. Closing
