### ISSUE TITLE
Datagrid: No scrollbar for table width overflow in safari

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#7582]
**Describe the bug**
When the width of the columns exceeds the table width, the table does not get a scrollbar in a Safari browser.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/example-filter.html in a Safari browser
2. See that the table columns get cut off at the table width and there is no scrollbar.

**Expected behavior**
There should be a scrollbar to view every table column when the column widths exceed the table width.

**Version**
- ids-enterprise: v4.82.1

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/76002134/f119165d-6dff-49f2-a7a4-35cd115ab89e)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Mac Ventura
 - Browser Name: safari
 - Browser Version: 16.3

**Comment by tmcconechy** [comment]
im getting a scroll bar in safari (trying https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html )

![Screenshot 2023-06-07 at 4 34 27 PM](https://github.com/infor-design/enterprise/assets/814283/d3f1f45b-ff11-4598-b259-b7cba6c98105)

One thing tho is there is a setting in mac.

![Screenshot 2023-06-07 at 4 35 09 PM](https://github.com/infor-design/enterprise/assets/814283/f05af07d-187d-48ac-a34c-8652529f4c1a)

Perhaps you have the setting on that hides the scrollbar?

**Comment by s-werking** [comment]
Hi @tmcconechy, I am testing on BrowserStack and I'm unable to view or edit my Mac settings. Would you have an idea of what the default setting would be for the scrollbar?

**Comment by tmcconechy** [comment]
it would be off. but you should be able to use the magic mouse and swipe if its off. but you might not have the track pad. try what you would normally do with your mouse to scroll left? i think it will still scroll even tho it hides the scrollbar from you

**Comment by s-werking** [comment]
Thanks for the video. I was able to replicate the scrolling with the arrow keys. This can be closed now, thanks!
