### ISSUE TITLE
Sinkpage: CAP - labels and textboxes doesn't fit in the panel

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7585]
**Describe the bug**
labels and textboxes doesn't fit in the panel.

**To Reproduce**

1. Go to https://4840-beta0-enterprise.demo.design.infor.com/
2. Scroll down to Contextual Action Panel
3. Click 'Contextual Action Panel' button

**Expected behavior**
labels and textboxes should fit in the panel.

**Version**

- ids-enterprise: 4.84.0-beta.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/5dcbfce1-996f-452d-bba3-64eacf2ed7fa)

**Platform**
 - BrowserStack (iOS - iPhone 14)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
