### ISSUE TITLE
Page: Sort out page background colors

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7586]
**Describe the bug**
Need to sort out background colors

- [x] what is contrast mode background color (answer: slate 10 but this is a new lighter color)
- [x] what is the light mode background color?  (answer: white for normal pages, slate 10 for homepages/widget pages)
- [x] what is slate 05's value? (answer: #fafafa) 
- [x] the module nav should start slate 10 (answer: yes its slate 10 in light mode
- [ ] fix dark mode (see attached PR)
- [x] fix bottom color in issue below

**To Reproduce**

1. Go to  http://localhost:4000/components/homepage/example-scenario-b
2. Scroll down see error on color at the bottom
3. Go to  http://localhost:4000/components/button/example-index.html?theme=new&mode=dark&colors=default
4. See hard to see buttons and hover states

**Additional context**
[Jira](https://jira.infor.com/browse/IDS-1333)

**Comment by hey-yall** [comment]
Asking design input in Jira ticket [IDS-1333](https://jira.infor.com/browse/IDS-1333)

**Comment by tmcconechy** [comment]
Status as of now

- contrast -> (new slate 10)
- light -> white
- widget pages light >  (new slate 10)
- dark mode -> maybe needs a tweak as its very dark now
