### ISSUE TITLE
Widget: Minor alignment inconsistencies/issues (workspace widgets)

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#7589]
**Describe the bug**
There seems to be a few inconsistencies for the alignment of icons/buttons in the widget header. A few redundant CSS values?

**To Reproduce**
Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/cards/example-workspace-widgets?theme=new&mode=light&colors=default

1. See svgs for icon buttons, for example "Bordered with actions", or more notably "Back button" . The svg has `top: -1px` due to 
```
.card-header:not(.has-toolbar) .icon, .widget-header:not(.has-toolbar) .icon {
   top: -1px;
}
```
svg is slightly off within its button:
![image](https://github.com/infor-design/enterprise/assets/1101770/90d8d0b8-a471-40dd-9d64-797c9a511baf)

Removing that CSS makes svg centered within the button. 

2. The actions button svg gets `top: -1px` from below as well, so to match it also needs to go.
```
.btn-actions > .icon {
   top: -1;
}
```

3. `widget-header-section custom-action` has `margin-top: 1px` which seems to counteract the svg positioning. It's the only section with that margin. So, if correcting the svg placement within the icon buttons instead, this margin is not needed and should be removed as well.
```
.widget-header-section.title + .widget-header-section.custom-action {
   margin-top: 1px;
}
```

4. Text next to back button when navigated is not aligned with the rest of the header content
![image](https://github.com/infor-design/enterprise/assets/1101770/b303c56b-7313-473d-85a5-b3c36fa255ae)

5. RTL support. Looks OK, except the `.custom-action` element would need `text-align: left` instead of `right`.

Below is a screenshot where I've removed all of above pixel shifts (1 to 3):
![image](https://github.com/infor-design/enterprise/assets/1101770/18048494-2391-4dd9-9c7b-3f69d8a1bede)

**Version**
- ids-enterprise: v4.83.1

**Platform**
 - Infor Application/Team Name: OS Portal

**Additional context**
Issues are minor and probably difficult to spot, but since this will be a new feature & concept for the workspace widgets, pixel perfection would be nice :) 

Maybe there's a reason for the 1px shift of icons within the buttons, does it align better with the title like that? Or looks better/more correct for some icons but not others?

Even if shift is by design, some changes would be required to make example page look correct (e.g. back navigation text, buttons when there's a subtitle)

**Comment by tmcconechy** [comment]
@volante007 some of this may be fixed in 4.84.x we can check through this and note what we still see.
