### ISSUE TITLE
Widget: Alignment issue in chart legend (workspace widgets)

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise#7599]
**Describe the bug**
There's a minor alignment issue in the donut chart legend when using inside of a workspace widget. 

**To Reproduce**

Create a widget with the following configuration:

```
    <div class="widget no-shadow auto-height double-width" id="progress-monitor">
      <div class="widget-header">
        <div class="widget-header-section title">
          <h2 class="widget-title">Progress Monitor</h2>
        </div>
        <div class="widget-header-section">
        </div>
        <div class="widget-header-section more">
          <button class="btn-actions">
            <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
              <use href="#icon-vertical-ellipsis"></use>
            </svg>
            <span class="audible">More Actions</span>
          </button>
          <ul class="popupmenu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Action</a></li>
            <li><a href="#">Action</a></li>
          </ul>
        </div>
      </div>
      <div class="widget-content">
        <div class="d-flex">
          <div id="pie-chart-progress" class="chart-container"></div>
          <div id="period-end" class="listview" data-options="{template: 'period-end-tmpl', selectable: 'single', source: '{{basepath}}api/periods' }"></div>
        </div>
      </div>
    </div>

  <script>
      const progressData = [{
        data: [{
          name: 'Off-contract',
          value: 75,
          tooltip: 'Off-contract 75%'
        }, {
          name: 'Unpaid',
          value: 25,
          tooltip: 'Unpaid 24'
        }]
      }];
  
      const progressApi = $('#pie-chart-progress').chart({
        type: 'donut',
        dataset: progressData,
        showLegend: true,
        legendPlacement: 'bottom'
      }).data('pie');
  </script>
```

Notice the chart legend misalignment.
![Screenshot 2023-06-13 at 3 02 23 PM](https://github.com/infor-design/enterprise/assets/1084735/143c1ee8-2eec-4d0f-b8ad-6f586f249050)

This is a screenshot from the workspaces dev environment using enterprise-ng:
![Screenshot 2023-06-13 at 2 49 34 PM](https://github.com/infor-design/enterprise/assets/1084735/6dfe51c3-ebac-41dd-a454-7a442dc9257e)

**Expected behavior**
Chart legend text labels should be properly aligned:
![Screenshot 2023-06-13 at 3 03 54 PM](https://github.com/infor-design/enterprise/assets/1084735/f600d8da-fb33-4734-afc7-ceb42eb29eb0)

Possible solution is to use the following css, but would need to test other scenarios:

```
  .chart-legend {
    display: flex;
    align-items: center;
    padding: 12px 0 !important;
  }

  .chart-legend .chart-legend-item.is-two-column {
    align-items: center;
    display: flex;
    float: none;
    margin: 0;
    padding: 0 15px;
    width: 50%;
  }
```

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Hey @jmacaluso711 is this tested against main? Because we had a similar bug that was fixed. Checking https://main-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-single-widget.html it looks better

**Comment by jmacaluso711** [comment]
@tmcconechy Just merged main into my branch and it does look better.

**Comment by jmacaluso711** [comment]
@tmcconechy Yeah sorry, meant to close with my last comment
