### ISSUE TITLE
Field Filter: Dropdown border disappears upon hovering

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7600]
**Describe the bug**
Dropdown border disappears upon hovering.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/field-filter/example-short.html
2. Hover over dropdown
3. See error

**Expected behavior**

**Version**

- ids-enterprise: 4.83.0-beta.0

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/67a99de2-07ba-4beb-8391-86f93b572b64

**Platform**
 - All major browsers

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to done. 
https://main-enterprise.demo.design.infor.com/components/field-filter/example-short.html
