### ISSUE TITLE
DatePicker: Date Range highlighted on iOS devices is not displayed correctly

### ISSUE THREAD

**Issue by michalnowak-infor** [infor-design/enterprise#7603]
**Describe the bug**
When a user opens the Date Range Picker (https://design.infor.com/code/ids-enterprise/latest/demo/components/datepicker/example-range.html) on the iOS device and selects the Date Range in the DatePicker the dates are highlighted in a different way that normally:
![image](https://github.com/infor-design/enterprise/assets/127401885/53af85f4-e3cb-438d-84c3-6c515299852e).

Expected behavior - dates are highlighted in the following way:
![image](https://github.com/infor-design/enterprise/assets/127401885/ba326976-211a-4780-b1bc-723dd6d24ea6)

**Comment by tmcconechy** [comment]
@michalnowak-infor was not able to reproduce this on IOS (iphone 14) also tried safari. We once had a similar issue in an older version? I see you checked on the latest link tho. But in case, just mentioning.

Will need additional info to reproduce. Not seeing it

**Comment by michalnowak-infor** [comment]
Hi @tmcconechy. To reproduce this issue the date range picker needs to be placed within the modal. Sorry for not mentioning that.

**Comment by tjamesallen15** [comment]
I need an access I think in browserstack to further fix this. Unfortunately, I don't have an IOS Phone

**Comment by tmcconechy** [comment]
@CindyMercadoReyes sent an invite for browser stack. Also note that on Mac you can use xcode app and the simulator there.

https://developer.apple.com/documentation/xcode/running-your-app-in-simulator-or-on-a-device
