### ISSUE TITLE
Fileupload Advanced: 'x' icon looks off

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7604]
**Describe the bug**
'x' icon looks off.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-allowed-types.html
2. Click on 'Select Files' link
3. Select a file
4. Notice the 'x' icon while loading

**Expected behavior**
'x' icon should be rendered properly.
**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/3c03c41f-ed30-4397-969a-c45eebe6201d)

**Platform**
 - All major browsers

**Comment by jbrcna** [comment]
this is now working as expected. moving this ticket to done. 
https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-allowed-types.html
