### ISSUE TITLE
Editor: Design Cleanup for Alabaster

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7606]
**Describe the bug**
Need to finish up alabaster theme fixes for the Editor component

- Editor -> https://main-enterprise.demo.design.infor.com/components/editor/example-index.html

**Expected behavior**

Editor: https://www.figma.com/file/8ekRxSWEbFxDzmvzraB1LH/Rich-Text-Editor?type=design&node-id=518-314&mode=design&t=aaj0rcFpsCQHH7lJ-0

See: https://jira.infor.com/browse/IDS-1335

**Comment by inforandy** [comment]
Alright, design here is ready for dev

**Comment by jbrcna** [comment]
QA Failed
dropdown label not centered in firefox
<img width="977" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/b1dd75a1-a1d3-49fa-991d-3e07563b1005">

hyperlinks and dropdown label were not slate in dark mode
<img width="945" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/d3cec4a8-e586-4fac-9bea-a01a84dd6abe">

**Comment by tmcconechy** [comment]
@jbrcna i didnt have a chance to fix. Can you make a new issue for whats left?

**Comment by jbrcna** [comment]
sure thing @tmcconechy . which one ? the Firefox alignment issue?

**Comment by tmcconechy** [comment]
yes, the FF one. The other part i didnt quite understand. But if that is an issue. Do add that as well...But from a design side.
