### ISSUE TITLE
Menu items cannot be seen in Alabaster theme

### ISSUE THREAD

**Issue by edinfor** [infor-design/enterprise#7609]
**Describe the bug**

Font color is similar to the background, title for the selected menu item is hard to see

same goes for Angular version, I know they are two different repos, maybe you can fix them together.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/applicationmenu/example-index?colors=ffffff&theme=uplift&variant=light
2. Click on theme switcher
3. Scroll down to colors
4. select Alabaster

**Expected behavior**

Text should be clearly visible

this should be fixed for both Enterprise and Angular

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

![image](https://github.com/infor-design/enterprise/assets/82842191/1a44f596-ac44-4290-918e-1a9e6a0bc331)
![image](https://github.com/infor-design/enterprise/assets/82842191/41201896-b4cf-400f-92e4-888848e711ae)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Its probably only a bug in the enterprise repo. We took away that it takes color at all but somehow alabaster is having an effect.

Will fix but also keep in mind we are slowly rolling out a new menu https://main-enterprise.demo.design.infor.com/components/module-nav/example-index.html

**Comment by edinfor** [comment]
please let me know whenever you release a new angular version that includes this fix, thanks so much @tmcconechy

**Comment by tmcconechy** [comment]
Will be 4.85 in the first few weeks of July. Please watch the announcements in teams. Will be hard to remember to follow up here with another message

**Comment by edinfor** [comment]
thanks for the update!
