### ISSUE TITLE
Editor Component: Typing in a hyperlink in body of the Editor doesn't work 

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#761]
**Describe the bug**
Editor Component: Typing in a hyperlink in body of the Editor doesn't work 

**To Reproduce**
1. Go to URL: http://4100-beta1-enterprise.demo.design.infor.com/components/listbuilder/example-index.html
2. Scroll down to the Editor section of the page
3. In the body of the Editor type in www.happy.com and click the enter key
4. www.happy.com should turn into a hyperlink but it's not doing that for MAC Chrome. Please see screen shot attached

**Expected behavior**
www.happy.com should turn into a hyperlink

**Screenshots**
![editor url](https://user-images.githubusercontent.com/39101346/45169940-b13fe700-b1cc-11e8-989f-ac76ae9a92b2.png)

**Platform**
- MAC Chrome

**Additional context**
None

**Comment by tmcconechy** [comment]
Just noting that this never did that. You need to use the hyperlink dialog to insert links. I think this would be tricky and probably not worthwhile

**Comment by CindyMercadoReyes** [comment]
Hi @tmcconechy On Win 10 IE 11 it works. It why I opened the ticket.  Here's a screen shot.  Thanks, Cindy
![editor hyperlink](https://user-images.githubusercontent.com/39101346/45175969-ab520200-b1dc-11e8-95da-0c80489cf35e.png)

**Comment by tmcconechy** [comment]
Ok, i think that IE treats the links this way and the other browsers dont. I would probably go the other way and see if we can make IE not do this.

**Comment by tmcconechy** [comment]
Descoping this IE 11 issue for now
