### ISSUE TITLE
Images: Search icon is not aligned properly in Classic Version

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7615]
**Describe the bug**
Search icon is not aligned properly in Classic Version

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/images/example-image-list.html?theme=classic&mode=light&colors=default
2. Type in any in the search bar
3. Notice the search icon

**Expected behavior**
Search icon should be aligned properly in Classic Version

**Version**

- ids-enterprise: 4.83.0-beta.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/a1ff9c36-1534-4fac-a649-196f118f80e1)

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
Looks ok now on https://main-enterprise.demo.design.infor.com/components/images/example-image-list.html?theme=classic&mode=light&colors=default

**Comment by jbrcna** [comment]
QA Passed
<img width="1393" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/28c92a17-eeb5-44ae-abb0-afd6548edaf4">
