### ISSUE TITLE
Bar stacked: unnecessary scroll bar

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7617]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/bar-stacked/example-contextmenu.html
2. See error

**Expected behavior**
<img width="880" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/f7865222-2d7d-42f8-8d33-df8bc532f77d">

**Version**

- ids-enterprise: v4.84.0-dev

**Screenshots**
<img width="984" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/903d702f-d6f7-44ac-8370-0107bbde7671">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
May be related to https://github.com/infor-design/enterprise/issues/7612

**Comment by tmcconechy** [comment]
We fixed this already on https://main-enterprise.demo.design.infor.com/components/bar-stacked/example-contextmenu.html

**Comment by jbrcna** [comment]
this is now working as expected. thanks
<img width="888" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/2207bb31-1cc4-464a-b108-edcd5d70a2fe">
