### ISSUE TITLE
Breadcrumb: Misaligned disabled item/breadcrumb

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7618]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/breadcrumb/example-disabled.html
2. See error

**Expected behavior**
<img width="343" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/a79af10a-bd3c-4f24-bbbb-1190c04f8b99">

**Version**

- ids-enterprise: v4.83.0-dev

**Screenshots**
<img width="378" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/107a51e5-6970-4e2c-8f14-04d097455fb6">

**Platform**
Safari

**Additional context**
see also https://main-enterprise.demo.design.infor.com/components/breadcrumb/example-index.html
https://main-enterprise.demo.design.infor.com/components/breadcrumb/example-with-hitbox.html
the last item is not properly aligned

**Comment by tjamesallen15** [comment]
This one too. Screenshot below @jbrcna 
Chrome (Upper Part)
Safari (Bottom One)
![10A94133-D8D3-484A-946F-5B29CD91744E](https://github.com/infor-design/enterprise/assets/34049950/16858615-2442-4f95-ad34-df7988d4ffe5)

**Comment by jbrcna** [comment]
can confirm on my end. thank you @tjamesallen15
<img width="632" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/b865eb83-3067-4826-94b3-68678c179aac">

**Comment by tmcconechy** [comment]
Thanks I think i spotted this and fixed it along with something else. Closing
