### ISSUE TITLE
Tabs vertical looks off on alabaster

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#7619]
**Describe the bug**
Tabs vertical looks off on alabaster

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html?theme=classic&mode=contrast&colors=ffffff & https://main-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html?theme=new&mode=contrast&colors=ffffff
2. Notice the tab not visible 

**Expected behavior**
Tabs should be visible / readable on alabaster 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/45757016/13a4714e-47c9-404d-97df-fa51af5506c0)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Will be fixed on https://github.com/infor-design/enterprise/issues/7333 so duplicate
