### ISSUE TITLE
Lookup Editable Strict Component: The color of the text is appearing in gray when it should be in black

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#762]
**Describe the bug**
Lookup Editable Strict Component: The color of the text is appearing in gray when it should be in black

**To Reproduce**
1. Go to url: http://4100-rc0-enterprise.demo.design.infor.com/components/lookup/example-editable-strict.html
2. Click on the lookup icon. The "Lookup that can only be edited by selection in modal" window will appear
3. Select 2142201, 2241202, 2342203 and click the "Apply"
4. In the "Lookup that can only be edited by selection in modal" The color of the text is appearing in a light gray.

**Expected behavior**
The color of the text should be in the color black 

**Screenshots**
![lookup_1](https://user-images.githubusercontent.com/39101346/45170594-3aa3e900-b1ce-11e8-8126-545685f0b74f.png)

**Platform**
- MAC Chrome

**Additional context**
None

**Comment by EdwardCoyle** [comment]
@CindyMercadoReyes maybe @tmcconechy can confirm, but I think the gray text here is on purpose because the input field itself is technically "read only".  It can only be changed by selecting items in the  lookup.

**Comment by CindyMercadoReyes** [comment]
Hi @EdwardCoyle Here's a screen shot of how it looks on Win 10 IE11
![lookup_2](https://user-images.githubusercontent.com/39101346/45182821-56b88200-b1f0-11e8-8602-60d9bc7c07b4.png)

**Comment by EdwardCoyle** [comment]
Upon further inspection, it's definitely a bug... only present in Chrome:

![screen shot 2018-09-06 at 4 55 56 pm](https://user-images.githubusercontent.com/3249601/45184737-dd239280-b1f5-11e8-9366-1bbc70868fc3.png)

due to a rogue `-webkit-text-fill-color` prop

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/lookup/example-editable-strict.html
Passed QA testing
