### ISSUE TITLE
Widgets: Message in widgets have wrong colors when in banner

### ISSUE THREAD

**Issue by gustavpollak** [infor-design/enterprise#7623]
**Describe the bug**
Message in widget has wrong colors in PV2 **when in a banner.**
This is for all accent colors but Alabaster.
This concerns the css classes `.is-personalizable` and `.personalize-subheader` as far as I can tell.

**To Reproduce**
Precondition:
1. There's a published workspace added.
2. The theme setting is set to Light UI/High Contrast UI
3. The Accent Color is set to any color except Alabaster.

Steps to Reproduce:
1. Login to PV2.
2. Click the Navigation Menu.
3. Hover and click the "..." (more) of the published workspace in precondition 1.
4. Click "Edit Published Workspace".
5. Click "Edit Layout".
6. Add a standard widget in Banner area. (e.g. Image widget)
7. Click "Save" and "Republish".

**Expected behavior**
1. The inline message in banner widget is readable. (same text color as the one in main area?)

**Actual Result:**
1. The inline message in banner area is difficult to read in light UI and high contrast UI.
2. This is not encountered in Dark UI.
3. This is not encountered using accent color "Alabaster".

**Version**
data-sohoxi-version="4.80.2"

**Screenshots**

![image](https://github.com/infor-design/enterprise/assets/49652924/5da7f153-2579-4d68-93f0-5194947d6f6a)

![image](https://github.com/infor-design/enterprise/assets/49652924/27702844-5db4-4b9f-aec4-a791324c0c96)

**Platform**
 - Infor Application/Team Name: Portal V2
 - Device: (if applicable) PC 
 - OS Version: W11
 - Browser Name: Chrome & Chrome debug
 - Browser Version: Version 114.0.5735.134 (Official Build) (64-bit)

**Comment by gustavpollak** [comment]
> @gustavpollak not sure how to login to PV2? Can this be reproduced in an example https://main-enterprise.demo.design.infor.com/components/notification/example-widget.html
> 
> Tried to reproduce it here https://main-enterprise.demo.design.infor.com/components/notification/example-index.html?colors=ffffff

Couldn't find a way to recreate a banner widget, how do I go about doing that? In normal widgets of any size it works well. Just banner widgets that behaves differently.

**Comment by tmcconechy** [comment]
@gustavpollak 
What do you mean by banner? Do you mean the "hero" on https://main-enterprise.demo.design.infor.com/components/homepage/example-hero-widget.html for example?

In that case would this go under the header instead? Perhaps thats worth a second issue with more details?
