### ISSUE TITLE
Links: New Component

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7628]
**Describe the bug**
Add new designs for a new type of link component.

- examples page a home page (under home pages or cards) showing example
- link cards (with text and icon) name TBD (class link-card)
- list of links with icon (class link-list) 
- list of links with color
- icons should be purple by default but can set to any palette color ~ various icons
- we will need action/accent icons

Designs: https://www.figma.com/file/azKGRkreBePCaeafbFknU4/Links?type=design&node-id=216-13291

**Additional context**
Original design ticket: https://jira.infor.com/browse/IDS-1032
Design QA ticket: https://jira.infor.com/browse/IDS-1379

See also https://www.figma.com/file/VRKxAUsadnteWIzz6i2WoU/Accent-Icons-exploration?type=design&node-id=253-13260&t=E9BnIlJiRb7y4fz7-0

**Comment by hey-yall** [comment]
Jira ticket for dev work: https://jira.infor.com/browse/IDS-1352 (clone of original ticket IDS-1032)

**Comment by hey-yall** [comment]
Design QA ticket: https://jira.infor.com/browse/IDS-1379

**Comment by talkaboutdesign** [comment]
Can we prioritize this one: 

<img width="360" alt="Group 41" src="https://github.com/infor-design/enterprise/assets/2926534/b8544b81-09e6-445b-a526-d251a39a5267">

@tmcconechy @yohannahbautista this is 1 to 1 same cards, layout and states as the new Stats KPIs. The only difference is in the content inside of it, and how thats arranged.

**Comment by tmcconechy** [comment]
@talkaboutdesign this is now in the current sprint. But how do we get these icons? They need to go in the icon set..

**Comment by talkaboutdesign** [comment]
We can give you some, but they are manually going to be added into the code by dev. We are not going to maintain these in our library yet. We want this only in a specific use case in workspaces in October. Not to be used by anyone else.

**Comment by tmcconechy** [comment]
ok how can we include them manually? We dont have a way to do that....I would have to figure that out...
Maybe if you just give the compressed SVG for it?

**Comment by talkaboutdesign** [comment]
> ok how can we include them manually? We dont have a way to do that....I would have to figure that out... Maybe if you just give the compressed SVG for it?

Do we have a way to just place SVG in code? Or it needs to be linked to an asset hosted somewhere?

**Comment by tmcconechy** [comment]
I think if we got an SVG file(s) with it all contained in it. We make it work with some added css.

**Comment by talkaboutdesign** [comment]
> Yes, I think if we got an SVG file(s) with it each icon all contained in it and drop it in the HTML. We make it work with some added css.

Let's talk this though in a meeting maybe.

**Comment by tmcconechy** [comment]
ok @yohannahbautista i'll get you more details after we chat
