### ISSUE TITLE
 Cross-Site Scripting (XSS) when setting up tree node

### ISSUE THREAD

**Issue by AT-Infor** [infor-design/enterprise#7631]
**Describe the bug**
When creating a tree you can use cross-site scripting to bypass any protection (escaping).

**To Reproduce**

Steps to reproduce the behaviour:
Create a tree using the SOHO controls. Within the text field add in your attack. EG:

```
 <ul role="tree" id="addnode-tree" aria-label="Asset Types" class="tree" data-init="false">
          <li>
              <a href="#" id="home">'\"><img src=x onerror=alert(1)>'</a>
          </li>
</ul>
```
Please see:

https://stackblitz.com/edit/ids-enterprise-4jn25k?file=index.html

Based off https://design.infor.com/code/ids-enterprise/latest/demo/components/tree/test-add-node?theme=uplift&variant=light

**Expected behaviour**
The code should protect you against it. The reason why this is important is that we create trees based on user input (a workaround has been implemented).

**Version**
v4.50.2

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/88100277/9e615642-429f-46d9-a0d7-f37539c2020b)

**Platform**
 - Infor Application/Team Name:  SunSystems
 - Device: N/A
 - OS Version: N/A
 - Browser Name:  All
 - Browser Version: 114.0.5735.134 (Official Build) (64-bit)

**Comment by ericangeles** [comment]
@AT-Infor is `src=x` intentional?

**Comment by tmcconechy** [comment]
@ericangeles the problem is probably the `onerror` part that "runs". Script x might just be to trick it as that really shouldnt have an effect
