### ISSUE TITLE
Module nav and application menu component accessibility support

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#7632]
**Describe the bug**
Current audible with screen reader for + and - is "button".

**To Reproduce**

Use a screen reader and tab through menu items, put focus on the +/- button and the menu item text.

1. Go to 'https://main-enterprise.demo.design.infor.com/components/applicationmenu/test-all-plusminus.html'
2. Turn on screen reader
3. Tab on +
4. Tab on "Resources"

**Expected behavior**
Requesting more descriptive audible which denotes users are traversing a menu hierarchy including announcing the text of the menu item being expanded/collapsed.

**Version**

- ids-enterprise: v 4.84.1

**Screenshots**

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version:Windows 11
 - Browser Name: Chrome
 - Browser Version: Version 114.0.5735.134 (Official Build) (64-bit)

**Additional context**
https://jira.infor.com/browse/LMWEB-17584 (point 3)

**Comment by tmcconechy** [comment]
Given that the new module nav is the eventual replacement. Shouldn't we just fix up the module nav instead and leave this?

**Comment by tmcconechy** [comment]
Ok you mean the + and - button? Fixing these for screen reader is very complex and time consuming so might as well just do it once. What if we just don't tab onto the + and - button and you just tab into the main element?

**Comment by tmcconechy** [comment]
Needs to be done for both module nav and application nav. Check the aria (maybe like a tree). Something like this example 
https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/

**Comment by tmcconechy** [comment]
One new wrinkle on this is now because of #7654 and #7719 the + and - is no longer focusable. Only the parent header is. 
This probably helps with accessibility because its less tab stops. But we need to check the screen reader with this in mind.

The module nav is more solid with this change that application nav. Will have to spend time on this and upping the estimate.

See what you can do @tjamesallen15 cc @ericangeles

**Comment by vonnyw** [comment]
Tim, actually the client came back with the feedback and their ask was exactly that, which is not to put focus on the + and - buttons. We have added the aria-hidden="true" attribute in our application menu implementation to achieve this behavior.

**Comment by vonnyw** [comment]
Feel free to close this issue.

**Comment by tmcconechy** [comment]
Ok that’s great. Sounds good all around then
