### ISSUE TITLE
Tabs: Dropdown tabs focus looks off in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#7638]
**Describe the bug**
Tabs: Dropdown tabs focus looks off in responsive view

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/example-dropdown-tabs.html
2. Minimize the screen to responsive view 

**Expected behavior**
Focus should be aligned correctly in responsive view

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/45757016/a54336ff-cf38-4a85-8880-8c5fce95c5e2)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Cant seem to reproduce this. Anything more you can add?
