### ISSUE TITLE
Multiselect Component: Dropdown list not working correctly on iOS IPhone X

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#764]
**Describe the bug**
iOS IPhone X for the Multi select component the drop-down list is not working correctly on iOS

**To Reproduce**
1. Go to url: http://4100-rc0-enterprise.demo.design.infor.com/
2. Scroll down to Multi-Select Drop-down 
3. Click on the "States" (Max 10) drop-down at time you see the correct dropdown list items within the drop down or the user will see the following: Cut, Copy, Paste list.  Please see screen shot attached.

**Expected behavior**
When the user clicks on the drop down the list of states should appear.

**Screenshots**
![img_3598](https://user-images.githubusercontent.com/39101346/45181432-7352bb00-b1ec-11e8-93d6-e9607bd76901.PNG)

**Platform**
 - iOS IPhone X
**Additional context**
None

**Comment by EdwardCoyle** [comment]
This one's my bad -- the kitchen sink page is linking out to the wrong example for context menus.  I'd renamed some examples in #563 and didn't re-link to the proper sample from the Kitchen Sink page.
