### ISSUE TITLE
Column-stacked: example-singular-set-selected not working

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7644]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/column-stacked/example-singular-set-selected.html
2. Click the buttons
3. See error
4. Nothing happens

**Expected behavior**
<img width="1572" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/3c43ae41-6c1e-4007-9fc0-74ed7319795e">

**Version**

- ids-enterprise: v4.84.0-dev

**Screenshots**
<img width="1623" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/2e713646-bdfa-4fea-a792-c645d66d5bce">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
Unsure if its a bug or just a bad demo. But we should probably research this.

**Comment by jbrcna** [comment]
working as expected. moving this ticket to Done.
<img width="1657" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1c7c216b-6c11-485d-8b49-a57a4256b7b5">
