### ISSUE TITLE
File Upload: Validation isn't triggered on "clear"

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#7645]
**Describe the bug**
The validation isn't triggered when clearing the input.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/fileupload/test-required.html
2. Upload a file to one of the required file uploads
3. Clear the input (click "X")
4. Notice that the validation error doesn't appear.

**Expected behavior**
The validation should be triggered when clearing the input.

**Version**
- ids-enterprise: 4.84.0

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by tmcconechy** [comment]
If you tab out after it will work. So maybe just need to trigger a change event on the X click. Maybe could be some workarounds with that info.
