### ISSUE TITLE
Notification Badge: Missing Icon

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7650]
**Describe the bug**
Phone Icon is not visible.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/notification-badge/example-badge-placement.html and https://main-enterprise.demo.design.infor.com/components/notification-badge/example-index.html
2. Notice the second icon on the list
3. Change to Classic Version then go back to New Version

**Expected behavior**
Phone Icon should be also visible in New Version.

**Version**

- ids-enterprise: 4.84.0-dev

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/30111b85-d304-40f2-b849-46732b883a21)

**_Classic Version_**
![image](https://github.com/infor-design/enterprise/assets/102151352/9f386ddd-d853-4d03-a1be-3d8136c9ac99)

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
We arent adding new icons to classic mode. This icon doesnt exist there. So no way to fix this
