### ISSUE TITLE
Page layouts: Column border is cut-off

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7652]
**Describe the bug**
Column border is cut-off.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/page-layouts/example-scrolling-two-column-left.html
2. Scroll down to the bottom

**Version**

- ids-enterprise: 4.84.0-dev

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/5c7c41b6-ff7f-4783-8c8d-10dc8df4e944)

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
FYI we will remove this example https://github.com/infor-design/enterprise/issues/7733
