### ISSUE TITLE
Rework the way base tags are used with icons

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#766]
**Describe the bug**
There are currently issues with the way base tags work with icons.  In single-page app environments, it's been reported in infor-design/enterprise-ng#144 that the logic used to reset URLs on icons is not being appended correctly to icon, causing it to disappear.

Most likely the issue is in how the Base Tag is prepended, which happens in [`/src/utils/base.js`](https://github.com/infor-design/enterprise/blob/master/src/utils/base.js#L41):

```js
  if (hash) {
      // absolute links
      if (hash.indexOf('/') === 0) {
        return window.location.origin + hash;
      }

      hash = (hash.indexOf('#') === -1 ? '#' : '') + hash;
      return this.url + hash;
    }
```

In situations where the base URL is `/`, it might not be necessary to prepend the entire location.

**To Reproduce**
See the discussion thread on MS Teams for specifics, and the NG Github Issue for some screenshots.  The IDS demo app doesn't have any good samples where we can recreate this problem (which should be part of the solution for this ticket).

**Expected behavior**
Icons should be properly reloaded, and base-tag-prepended URLs should be correct.

**Screenshots**
n/a

**Platform**
n/a

**Additional context**
- [Discussion thread on MS Teams](https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1536137934297?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1536137934297&teamName=IDS%20Enterprise%20Development%20(SoHo%20Xi)&channelName=Angular%20Components&createdTime=1536137934297) (requires an Infor email address to login)
- Related NG Issue: infor-design/enterprise-ng#144

**Comment by EdwardCoyle** [comment]
The actual fix is pretty simple, but rating this as `[3]` because we should also check out the testbed we have for this in the demoapp and make sure we can faithfully reproduce the problem on the EP side, before we retest with Angular.

**Comment by brianjuan** [comment]
Hi @tmcconechy , can we test this on enterprise?

**Comment by tmcconechy** [comment]
No This one can only be tested on Angular apps.
