### ISSUE TITLE
ModuleNav: Role switcher empty menu with invalid search

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#7662]
**Describe the bug**
Role switcher leaves empty menu with invalid search

**To Reproduce**
1. Go to http://localhost:4200/ids-enterprise-ng-demo/
2. Search "abc"
3. See issue

**Expected behavior**
Should display some kind of no results message? Or nothing at all...

**Version**
- ids-enterprise-ng: 15.4.x

**Screenshots**
<img width="554" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/1056684/3c5c98e5-d190-46b8-8066-f9d9b9f0cce3">

**Platform**
 - Windows
 - Chrome

**Additional context**

**Comment by tmcconechy** [comment]
Part of this is design issue https://jira.infor.com/browse/IDS-1427 for now use "no search" in dropdown https://main-enterprise.demo.design.infor.com/components/searchfield/example-index.html
