### ISSUE TITLE
Positive-Negative: Legend alignment

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7666]
**Describe the bug**
Legends and Legend colors are not properly aligned.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/positive-negative/example-contextmenu.html
2. Notice the Legend
3. Change to Classic Version
4. Notice again the Legend

**Expected behavior**
Legends and Legend colors should be properly aligned.

**Version**

- ids-enterprise: [4.84.0-dev](https://main-enterprise.demo.design.infor.com/components/list)

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/4c9a2ff8-dc26-4197-a03b-878c8aa3aaf0)

![image](https://github.com/infor-design/enterprise/assets/102151352/d640e8aa-2598-412c-99b3-aa74cb77f15b)

**Platform**
 - All major browsers

**Comment by ericangeles** [comment]
@glenlieorillo please test this again. I believe it's been fixed in here https://github.com/infor-design/enterprise/issues/7722

**Comment by glenlieorillo** [comment]
Working now as expected. Thanks!

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/c7973172-0537-4f6f-90bf-060637c0964b">
