### ISSUE TITLE
Re-implement SASS Linter

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#767]
**Describe the bug**
At some point in the recent past, we lost our SASS linter scripts in `package.json`.  We used to have the following:

- a standalone SASS linting script
- call to the above script inside the `lint:ci` task (which makes SASS linting required to pass builds on the CI)

We previously used [scss-lint](https://github.com/brigade/scss-lint), and the rules for this are still present in IDS's [scss-lint.yml](https://github.com/infor-design/enterprise/blob/master/.scss-lint.yml).  However, as long as the rules are met, it probably doesn't need to be that package if there are others to choose from.

**Comment by clepore** [comment]
I'm going to remove these two oddities (`:hidden { }`) as they aren't real psuedo-class selectors and shouldn't be doing anything, but in case something breaks we have a record.
- [src/layouts/_scrollable-flex.scss#L61](https://github.com/infor-design/enterprise/blob/59695bfc7eff0e55fabdf0f985b50ee16e895c36/src/layouts/_scrollable-flex.scss#L61)
- [src/components/header/_header.scss#L455](https://github.com/infor-design/enterprise/blob/59695bfc7eff0e55fabdf0f985b50ee16e895c36/src/components/header/_header.scss#L455)

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Closing out this jira ticket.
