### ISSUE TITLE
Popover: Title section has different font size for plain popover

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise#7676]
**Describe the bug**
Title section of popover component has a different font styling that in design files: https://design.infor.com/product/components/popover

![image](https://github.com/infor-design/enterprise/assets/86295640/f5d5ef0e-82f0-4079-b178-d347e207d355)

It looks fine for alternate class and custom header color classes, but there is no way to have this styling with white header and white background.

**To Reproduce**

1. Go to any popover demo and remove alternate class
2. The title is smaller and close button is not centered

**Expected behavior**
Title section for plain popover should be similar to the one with alternate or custom header color classes.
Alternatively there could be additional class to make it the same as with alternate, without changing the background and adding padding for button.

**Version**

- ids-enterprise: 4.84

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor WFM

**Comment by tmcconechy** [comment]
Do you really want a modal here? I think we are getting rid of the blue color. But i do see why should update the title to just...

```
font-family: Source Sans Pro;
font-size: 20px;
font-weight: 400;
line-height: 25px;
letter-spacing: 0px;
text-align: left;
```

Is that enough for this?

**Comment by kwolentarski** [comment]
Sorry for using the same example for multiple issues, but here the content is quite irrelevant. I guess as long as the default and alternate title styling are similar I'm fine
