### ISSUE TITLE
Popover: Event handlers of other components are removed when reopening the popover

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise#7677]
**Describe the bug**
When using different IDS components inside popover contents, they are working fine the first time, but after closing and reopening the popover they are not working properly.
The issue is with probably with seting content using innerHtml which is known for removing event handlers.

**To Reproduce**

Textarea;
1. Go to https://stackblitz.com/edit/ids-popover-issues?file=src%2Fapp%2Fapp.module.ts
2. Click on 'Popover 1'
3. Write something in text area and see that counter is working fine.
4. Close and reopen 'Popover 1'
5. There are now two counters, one working fine and another frozen.

Expandable data grid:
1. Click on 'Popover 2'
2. Expand datagrid row - should work fine
3. Close and reopen 'Popover 2'
4. Try to expand datagrid row - it will not work anymore

**Expected behavior**
Other components should work just fine when used inside popover.

**Version**

- ids-enterprise: 4.84

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/86295640/6b6be430-c84c-47f9-812c-28e6ee0403ba)

**Platform**
 - Infor Application/Team Name: Infor WFM

**Comment by kwolentarski** [comment]
Hi @tmcconechy, I had some time to think about this issue and the fix provided. The example provided fixes the problem, but not the root cause. I have found the solution that looks to be working without need to destroy/recreate each time the popover is opened/closed. I can provide the PR, but should it be under this ticket or should I create a copy?

**Comment by tmcconechy** [comment]
@kwolentarski you can use the same issue. Look forward to the PR 👍🏻
