### ISSUE TITLE
Popover: Add ability to make popover content scrollable

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise#7678]
**Is your feature request related to a problem or use case? Please describe.**
Popover component currently does not restrict content (tooltip-content) height in any way. This can be problematic as either the content will overflow the popover (in case the popover container restricts height due to positioning) or it will grow infinitely (in case popover has expandable sections). In the second case it also causes the arrow to change position not showing trigger anymore.

Example:
1.  Go to https://stackblitz.com/edit/ids-popover-issues?file=src%2Fapp%2Fapp.module.ts
2. Click on 'Popover 2'
3. Extend few data grid rows
4. Notice that the popover is now overflowing the viewport and also the arrow is misplaced
![image](https://github.com/infor-design/enterprise/assets/86295640/908e3b4e-48ff-4a8a-b755-dfd6595caabc)

Second example:
1.  Go to https://stackblitz.com/edit/ids-popover-issues?file=src%2Fapp%2Fapp.module.ts
2. Resize the window to make it small enough.
3. Click on 'Popover 2'
4. Notice that the popover content is overflowing the popover 
![image](https://github.com/infor-design/enterprise/assets/86295640/e8e6e9e3-5739-410c-a80b-876b571bb9ff)

**Describe the solution you'd like**
There should be a way to make the popover to keep initial height and make the content scrollable (maybe some extra css class?).

**Describe alternatives you've considered**
We considered setting the height on the custom  but because it could be dynamic we would need to either set it up after rendering or popover would have whitespace if there is not enough content to show. 

**Additional context**
Infor Application/Team Name: Infor WFM

**Comment by talkaboutdesign** [comment]
@kwolentarski Popovers are not suitable for presenting such complex UI. Utilize modals windows for this.

**Comment by kwolentarski** [comment]
Yeah, maybe the example is a bit over the top, but it actually does not have to be this complex:
https://stackblitz.com/edit/ids-popover-issues-zedyoz?file=src%2Fapp%2Fapp.component.html
Here you have expandable area inside the popover. Once you expand it, it will grow popover and move the arrow to different position then it was losing context.
![image](https://github.com/infor-design/enterprise/assets/86295640/6cd64855-f5d5-472d-9873-96a3d5d0e778)

**Comment by talkaboutdesign** [comment]
> Yeah, maybe the example is a bit over the top, but it actually does not have to be this complex: https://stackblitz.com/edit/ids-popover-issues-zedyoz?file=src%2Fapp%2Fapp.component.html Here you have expandable area inside the popover. Once you expand it, it will grow popover and move the arrow to different position then it was losing context. ![image](https://user-images.githubusercontent.com/86295640/251506114-6cd64855-f5d5-472d-9873-96a3d5d0e778.png)

This is still complex. Why do you have a popover with so much content? Not convinced that popovers are suitable for this type of data. What is your use case?

**Comment by kwolentarski** [comment]
I have just added more text for it to be more visually clear. Are you saying that we should not use e.g. expandable areas inside popovers? We have two use cases for now, one is employee details, which allow users to quickly glance through the data related to employee to make scheduling decisions. Second one is for the shift details, which is a bit more complex.
The main reason for using popover vs. modal is that popover allows us to show more details without losing the context of the trigger element.
This is not possible with modal itself as it will hide the context.

**Comment by tmcconechy** [comment]
I agree with @talkaboutdesign in both the https://github.com/infor-design/enterprise and https://github.com/infor-design/enterprise-wc components we coded it as

popup - simple not much text and not any inputs -> no scrolling but should position to fit in the page
modal - should also be simpler like 4/5 fields -> will scroll but cover the page
contextual action panel - can be more complex its like a page in a page over top -> will scroll but cover the page

We did have the question before of showing content under but it remains unanswered #7019 is related

**Comment by Infor-Calvin** [comment]
In general and in most use cases I agree with @talkaboutdesign as well. 
Our use cases in WFM are more akin to calendar and Excel, where the entire screen is full of entry points and the positional context is vital / critical / must have. 

In this case, we need a conditional and positional container that is capable of a range of tasks and information display. We can name it something else if we want to reserve the "popup" to simpler usecase.

Or alternatively we can enhance contextual action panel instead -- it was considered but it is lacking the vital positional context. We basically need a hybrid!

Example of our use cases in a common product (Calendar - both Apple and Google has similar behaviour) that we might all be familiar with:

https://github.com/infor-design/enterprise/assets/93406677/f99b0e55-04b2-4949-a3ff-e61ede9837cf

**Comment by inforandy** [comment]
Thanks @Infor-Calvin, your point makes a lot of sense here. I am going to set up some time to meet and discuss what this hybrid popover/modal might be and see where we can go from there.

**Comment by tmcconechy** [comment]
@jbrcna sorry i have @corpulent looking at the updating problem. Just check main for now or the issue specific branch and we will have it fixed soon enough. Thanks!

**Comment by glenlieorillo** [comment]
This is now working as expected in main-enterprise.


https://github.com/infor-design/enterprise/assets/102151352/9886d52b-a866-47e8-9a3b-fa78324b58bb

**Comment by jbrcna** [comment]
test passed
<img width="1336" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ed2b07dc-1ee6-4f18-94df-ed638bfe001d">
