### ISSUE TITLE
Datagrid: Allow to configure expandable rows to be expanded 

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise#7680]
**Is your feature request related to a problem or use case? Please describe.**
Datagrid Expander formatter based on the documentation should allow to be exanded by default:
![image](https://github.com/infor-design/enterprise/assets/86295640/70df4be1-3f61-4fb8-b65b-aeb1b146e162)
This is not implemented right now, but could be done similarly to how it is done in Group formatter.

**Describe the solution you'd like**
Passing expanded to the Expander formatter should allow to make expandable rows expanded by default.

**Additional context**
Infor Application/Team Name: Infor WFM

**Comment by tmcconechy** [comment]
I checked the code and this is only current for grouped rows not expandable rows. But i think we can reuse the setting there.

This might already work on the new web component datagrid https://github.com/infor-design/enterprise-wc
