### ISSUE TITLE
Agenda Weekview: Last day of previous week displayed as first date in subsequent week

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise#7684]
Submitted by Mahesh Thimanayakapalium (mahesh.thimanayakapalium@infor.com)

**Describe the bug**
We have identified a date rolling issue. Specifically, the last day of the week displayed in the component is being repeated in the subsequent week, leading to an incorrect representation of the dates.

![image](https://github.com/infor-design/enterprise/assets/57144784/54897fd5-0c30-4abe-920d-8b56eca1933d)
![image](https://github.com/infor-design/enterprise/assets/57144784/fa153461-f4c4-45d1-8265-d9d04223146a)

**Comment by tmcconechy** [comment]
@inforandy do you understand the issue or do we have to reach out. Trying these steps:

https://main-enterprise.demo.design.infor.com/components/week-view/example-stacked.html
1. open the picker and go today
2. click next week several times and make sure the dates are in the right order

I see somehow it went from 7-12 and then 12-18 instead of 13 but not sure how.

**Comment by inforandy** [comment]
No, I don't have any more replication details right now, we'll need Mahesh to swing by here and drop in any additional information he may have

**Comment by info-mahesh** [comment]
Hi all,
To replicate the issue, follow these steps: set the date range starting from the current date and extending to six days ahead, ensuring that a complete week is included. When rendering this date range and clicking on the "next week" button, the last day of the current week gets repeated. However, if you click on "today," the date range adjusts accordingly, showing the upcoming week without any repetition.

**Comment by tmcconechy** [comment]
Yes i see it. To clarify

- update example to change these to today and today + 6
```
        startDate: new Date(2023, 6, 10),
        endDate: new Date(2023, 6, 16),
```
- open page and click next
- today does in fact work, can only reproduce this if you adjust these and click next

**Comment by infor-mahesh** [comment]
yes, it works when we click "Today" then "next", but when we give date range and click "next" then it doesn't work.

**Comment by yohannahbautista** [comment]
Hello,
Maybe as a temporary fix, I found that weekview works as intended if you add additional parameters in the Date object on endDate:
https://github.com/infor-design/enterprise/blob/main/app/views/components/week-view/example-stacked.html#L24

**Comment by jbrcna** [comment]
QA Passed

**Comment by infor-mahesh** [comment]
Hi Is it fixed? when it is available in which release?

**Comment by tmcconechy** [comment]
4.88. See top right corner.
