### ISSUE TITLE
ModuleNav: allowOnePane setting not current working

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7687]
**Describe the bug**
The module nav does not respect the allowOnePane setting. 

However, from design feedback we may not want this.
Say for example i want two menus open and only work in those menu items.
Also the new portal does not close the open items.

**To Reproduce**

2. Change this line to true `<div class="module-nav-accordion accordion panel" data-options="{'allowOnePane': true}">` or remove it because it should be the default as true (for accordion but not module nav)
3. Re-Open http://localhost:4000/components/module-nav/example-index.html

**Expected behavior**
If the option is set could respect it. But is it worth to add? Example from Portal with two open...

![Screenshot 2023-07-10 at 3 06 26 PM](https://github.com/infor-design/enterprise/assets/814283/d5c92d29-48fc-438e-8e2b-a086a0a38b6e)

**Additional context**
LM Discussion

**Comment by jbrcna** [comment]
QA Passed.
