### ISSUE TITLE
ModuleNav: Ability to add an external image with a link

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7694]
**Is your feature request related to a problem or use case? Please describe.**

In the module nav and the dropdown need a way to create an `<img>` tag.

**Describe the solution you'd like**
Instead of the svg replace it with in `img` 

**Additional context**
New high priority item

**Comment by talkaboutdesign** [comment]
Can you elaborate why this is needed?

**Comment by tmcconechy** [comment]
@talkaboutdesign they want to show customer/landmark specific icons and they are inside of a "CDN" where they pull images from.

**Comment by talkaboutdesign** [comment]
> @talkaboutdesign they want to show customer/landmark specific icons and they are inside of a "CDN" where they pull images from. Basically any `svg` icons could come from an CDN instead `<image src="url">`

Is there a related ticket to this anywhere? Just curious about the type of images. Icons for modules? Icons for apps/sections?

**Comment by tmcconechy** [comment]
cc @lucacolumbu -> i think it was a request from Landmark based on requirements. Part of it was from a call with landmark based on the past need in module nav.

**Comment by talkaboutdesign** [comment]
Who can I talk to to get more clarity here. @tmcconechy
