### ISSUE TITLE
Homepage Example Workspace: The background is rendered in visible viewport, white if you scroll past it. 

### ISSUE THREAD

**Issue by talkaboutdesign** [infor-design/enterprise#7696]
![CleanShot 2023-07-11 at 14 18 03@2x](https://github.com/infor-design/enterprise/assets/2926534/dc82ebea-e6cc-4e9b-8155-99e0bb6f5802)

**Describe the bug**

**To Reproduce**
See this example: https://localhost:4000/components/homepage/example-workspace.html

**Comment by talkaboutdesign** [comment]
@tmcconechy can we take a look at this and try to fix for 4.85. This is high priority.

**Comment by tmcconechy** [comment]
Are you sure its not just the example @talkaboutdesign part of this was around that question i had of "does the page" background have the slate or just the home page.

Or do they also have this issue?

**Comment by talkaboutdesign** [comment]
> Are you sure its not just the example @talkaboutdesign part of this was around that question i had of "does the page" background have the slate or just the home page.
> 
> Or do they also have this issue?

Homepage should be slate01. Regular background white.

**Comment by tmcconechy** [comment]
Fixed this for both 4.85 and 4.86 https://github.com/infor-design/enterprise/commit/bc78175118eca7b34e1430f4a45f62a4fc5f3993
