### ISSUE TITLE
Agenda Weekview: Add setting to hide full day event row

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise#7700]
We want to port over the setting that we have in the standard weekview to optionally hide the row that displays full day events in the weekview.

<img width="1470" alt="Screenshot 2023-07-11 at 5 11 32 PM" src="https://github.com/infor-design/enterprise/assets/57144784/803a98d5-c560-47f5-a67e-1b0ee2314e1c">

**Comment by infor-mahesh** [comment]
Hi @tmcconechy ,
what is the status of this ticket, when it will be available to use

**Comment by tmcconechy** [comment]
@infor-mahesh it was added on the PR above on June 14. So means any release after that. Suggest the latest 4.87.0
