### ISSUE TITLE
Arrange: Does not use connectWith attribute provided via settings

### ISSUE THREAD

**Issue by tfavorite** [infor-design/enterprise#7708]
**Describe the bug**
Arrange does not use connectWith attribute provided via settings as documented [here](https://design.infor.com/code/ids-enterprise/latest/arrange) - it only seems to look at data-arrange-connectWith attribute on the element.

See line 182 or so of arrange.js:
    ```this.connectWith = this.element.attr('data-arrange-connectWith');```

**Expected behavior**
I would expect to see something like:
    ```this.connectWith = s.connectWith || this.element.attr('data-arrange-connectWith');```

**Version**

Is an issue as of the latest codebase (4.84.2)

**Platform**
 - Infor Application/Team Name: Nexus

**Comment by tmcconechy** [comment]
Can do a pull request if you would like @tfavorite ? 🚀

**Comment by tfavorite** [comment]
Sure, I can likely do that. Let me see if I can get it working correctly as it seems like there is a little more to it than what I mentioned.
