### ISSUE TITLE
WeekView: Time Formatting and Display Order

### ISSUE THREAD

**Issue by infor-mahesh** [infor-design/enterprise#7739]
**Is your feature request related to a problem or use case? Please describe.**

My problem is a use case for a specific requirement, so to match that i need this enhancement.

[Week view] component has by default:
*Time Format Display*: Currently, the default schedule displays time ranges in different formats depending on the duration of the event. For instance, if an event spans from AM to PM, it shows as "2am-5pm." However, for events within a single time period, it displays as "2-5am" or "2-5pm." so, I want to achieve "2am - 5am" or "2pm - 5pm".

*Time-Sorting Order*: Additionally, we would like to change the sorting order of the schedule entries. The default behavior is to display entries in the order of subject first and then time. However, we need the schedule to display entries in the order of time first and then subject to match the design requirements. By order i mean the order of the inner contents

*Time format change*: Need to change the Time display from 12 hours format to 24hours format

This is what default week view looks
<img width="559" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/43953f81-1ffe-4adf-83a0-3c418909e4cc">

This is the requirement which needs to be matched
<img width="379" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/71896e2d-d3d9-48b6-9607-841997be43dd">

**Describe the solution you'd like**
I am seeking a flag that allows me to modify the format of time ranges in the schedule. Currently, the format is displayed as "2-5AM," and I would like the flexibility to change it to "2AM-5AM."

Additionally, I have a requirement to change the order of display data in the schedule. The default order is subject first, followed by time. However, I need the schedule to show the time first and then the subject for better alignment with the design.

need an attribulte to make the week view 24/12 hours format.
provide me a solution/enhancement accordingly.

**Comment by tmcconechy** [comment]
@infor-mahesh just one question for now. is your team going to be adopting the web component version https://github.com/infor-design/enterprise-wc if so we can check this there and add it if there is no way (or else might have to be done twice)

**Comment by hey-yall** [comment]
Needs design resources first to determine date standards. Assigned to Peter Messina under IDS-1519.

https://jira.infor.com/browse/IDS-1519

**Comment by PeterMessina** [comment]
Hi @infor-mahesh, 

I'm a UX writer for Infor Design and this issue has been assigned to me at the JIRA ticket @hey-yall (Laken) references above. 

I heartily approve of the change you'd like to make in that calendar. Although it doesn't specifically address a hourly time range within the same day, the UXW standard for hourly time formats is to always show the minutes integers in a specific hour (or hours) regardless of it's at the top of the hour (i.e., 10:00AM) or not (i.e., 10:15AM, 10:23AM etc). AS well as always state whether AM or PM EXCEPT if it is in 24 hour clock in which case AM/PM is unnecessary. You can reference that here (Scroll to Date Format with a Timestamp): 

[https://design.infor.com/resources/ux-writing/dates-and-times](url)

We will update the UXW style guide to contain a standard for formatting hours ranges within a single 24 hour period.

Question: Could you clarify what you mean by "I am seeking a flag that allows me to modify the format of time ranges in the schedule." If you mean a sort of toggle that formats the date ranges. I think if the standard is being followed at all time a "flag" shouldn't be necessary.

Let me know your thoughts.

Thanks,

Peter M

Team Lead - UX Writer

**Comment by tmcconechy** [comment]
ok thanks @PeterMessina i think he means a setting so they can pick the format. that being said the following are valid?

`2 AM-5 AM` - if time is not relevant
`2:45 AM-5:15 AM` - if time is relevant
`17:00-19:00` - if 24 hr

And 2-4PM should not be used (always show am or pm on one side?) Is that what im picking up? Keep in mind we can switch the locale and it should be default use 24hr or time format for that locale depending what the country uses. So that would be our "default"

**Comment by PeterMessina** [comment]
Hi @tmcconechy!, 

Great about the 'default setting". :)

These are closest to the current UXW standards:

> 2:45 AM-5:15 AM - if time is relevant
> 17:00-19:00 - if 24 hr
> 

Right now recommending: 2:45AM - 5:15AM

As saving that pixel space is usually pretty appreciated by the visual designers working with columns, I find. :)

But hours shouldn't appear without minutes like this:

> 2 AM-5 AM - if time is not relevant

And this should never happen as you stated:

>  2-4PM


Thanks Tim!!

**Comment by tmcconechy** [comment]
I can add something to the locale page for this when its done.

**Comment by PeterMessina** [comment]
> @PeterMessina assuming you will update guidelines to reflect it?

@talkaboutdesign Yep absolutely, it's in the backlog for next IDS UXW styleguide update.

**Comment by PeterMessina** [comment]
Yep, Thanks and will do! This will be in the next update/revision  to the UXW writing Style Guide forthcoming soon.


Peter M


[Infor]<http://www.infor.com/>
Peter Messina (he/him) | Team Lead UX Writer | Infor Design
646 812 8420 | ***@***.*** ***@***.*** > | design.infor.com<https://design.infor.com/>



From: Maksim Petriv ***@***.***>
Date: Monday, August 21, 2023 at 8:24 AM
To: infor-design/enterprise ***@***.***>
Cc: Peter Messina ***@***.***>, Mention ***@***.***>
Subject: Re: [infor-design/enterprise] WeekView: Time Formatting and Display Order (Issue #7739)
Sent by an external sender.  Please be cautious about clicking on links and opening attachments.
--------------------------------------------------------------------------------------------------------------------------------


@PeterMessina<https://github.com/PeterMessina> assuming you will update guidelines to reflect it?

**Comment by infor-mahesh** [comment]
Hi Is it fixed? when it is available in which release?

**Comment by ericangeles** [comment]
Most probably this week.

**Comment by tmcconechy** [comment]
@infor-mahesh its in 4.88 -> i think would be either Fri, Mon or Tues

**Comment by tmcconechy** [comment]
@infor-mahesh also you can always see this on the "projects" tab on the issue...

![Screenshot 2023-10-03 at 10 08 00 AM](https://github.com/infor-design/enterprise/assets/814283/8a44e4aa-b9c7-4cf9-8d8e-b5e3abfdd025)
