### ISSUE TITLE
ModuleNav: Remove default icon from the module nav switcher

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#7740]
**Is your feature request related to a problem? Please describe.**
Would like to have the default set to nothing.  Currently it is set to "EM" icon. Having a default is causing some flash of content issues when swapping the image on initial load.

**Describe the solution you'd like**
Remove the default. Or make it optional

**Additional context**
Example of FOC when switching from default to a different icon. (this happens on initial page load)
![foc](https://github.com/infor-design/enterprise-ng/assets/1056684/f8fdc8c1-424b-440f-8818-a68e01108891)

**Comment by glenlieorillo** [comment]
Tested and passed.

https://7740-no-icon-enterprise.demo.design.infor.com/components/module-nav/example-no-icon.html

![image](https://github.com/infor-design/enterprise/assets/102151352/c00f555c-2751-4253-bc8e-3517fd19a683)

https://7740-no-icon-enterprise.demo.design.infor.com/components/module-nav/example-icon.html

![image](https://github.com/infor-design/enterprise/assets/102151352/22ade1b0-9f23-4623-9350-01ba53d7d43d)
