### ISSUE TITLE
Tabs Module: Close button is not properly aligned in mobile view

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7742]
**Describe the bug**
Close button is not properly aligned in mobile view.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html
2. Type in any text in search bar
3. See error

**Expected behavior**
Close button should be rendered properly in mobile view.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="448" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/a487db6f-a91b-4193-bc42-b788c9580474">

**Platform**
 - Browserstack
 - iOS

**Additional context**

**Comment by tmcconechy** [comment]
Similar to https://github.com/infor-design/enterprise/issues/7743 https://github.com/infor-design/enterprise/issues/7746 and https://github.com/infor-design/enterprise/issues/7744

Not sure if its easy to solve it, maybe hide the search on mobile?
