### ISSUE TITLE
Tabs Module: 'Menu' label is not spelled out in mobile view

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7743]
**Describe the bug**
'Menu' label is not spelled out in mobile view.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield-go-button-home.html
2. Notice the 'Menu' label

**Expected behavior**
'Menu' label should be fully spelled out in mobile view.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="448" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/8e4c730f-6ca0-4818-9541-410614235061">

<img width="894" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/524a0e6e-c4e4-4b8c-8a29-559d006d2a90">

**Platform**
 - BrowserStack
 - iOS

**Additional context**

**Comment by tmcconechy** [comment]
Seems a little like https://github.com/infor-design/enterprise/issues/7744 ~ where not exactly sure how to solve it if we can at all.
