### ISSUE TITLE
Tabs Module: Close button looks off in mobile view

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7744]
**Describe the bug**
Close button looks off in mobile view.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html
2. Notice the close icon in search bar

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="444" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/69e7f8af-7e1b-4350-a646-9fae80d59453">

**Platform**
 - BrowserStack
 - iOS

**Additional context**

**Comment by tmcconechy** [comment]
May need some design feedback. Pretty small here. Maybe we hide the search entirely at this viewport
