### ISSUE TITLE
Tabs Module: Warning icon is not properly aligned in modal

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7746]
**Describe the bug**
Warning icon is not properly aligned.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-sortable.html
2. Click 'Open Modal Dialog' button
3. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="444" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/ece6e1ad-fa14-4888-bbf4-a76ae80c65b0">

![image](https://github.com/infor-design/enterprise/assets/102151352/fe9313f5-d6f6-43f9-9706-d266a8588384)

**Platform**
 - BrowserStack
 - iOS
 - All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
Happens on https://main-enterprise.demo.design.infor.com/components/message/example-index.html too.
