### ISSUE TITLE
Datagrid export to CSV using customDS doesn't work correctly

### ISSUE THREAD

**Issue by dmcodrum** [infor-design/enterprise#775]
**Describe the bug**
When executing exportToCsv on a datagrid and using a custom DS:
1. The custom DS is ignored and the data from the grid is exported.
2. The heading row is not exported.

**To Reproduce**
1. Setup a datagrid to exportToCsv using a custom DS. For example, the custom DS  that contains less data rows than the displayed grid.
2. Execute the export.
3. Note the exported CSV file does not contain the header row and the data rows do not match the custom DS data.

**Expected behavior**
The exported CSV file should have a header row and contain the data from the custom DS

**Screenshots**

**Platform**
- OS and browser irrelevant.

**Additional context**
Possibly found the problem code:

**In datagrid.js:**
```
  _/**
  * Export the grid contents to csv
  * Consider Deprecated use excel.exportToCsv
  *
  * @param {string} fileName The desired export filename in the download.
  * @param {string} customDs An optional customized version of the data to use.
  */
  exportToCsv(fileName, customDs) {
    excel.exportToCsv(fileName, customDs, this); **<< Note 'this' is always set**
  },_
```
In **excel.js**:
```
_/**
* Export the grid contents to csv
* @param {string} fileName The desired export filename in the download.
* @param {string} customDs An optional customized version of the data to use.
* @param {string} self The grid api to use (if customDs is not used)
*/
excel.exportToCsv = function (fileName, customDs, self) { **<< Note 'self' is always set**_
...
  _if (!self && customDs) { **<< Self is always set!**
    table = this.datasetToHtml(customDs); **<< This line is never executed, customDs is ignored**
  } else {
    table = this.appendRows(self.settings.dataset, self.table.clone(), self); **<< customDs is ignored**
  }

  if (!customDs && !table.find('thead').length) {
    self.headerRow.clone().insertBefore(table.find('tbody')); **<< Never gets executed if custom Ds**
  }_
```

**Comment by tmcconechy** [comment]
@dmcodrum I made the export function externally available without the grid. This is the example and code. 

https://github.com/infor-design/enterprise/blob/master/app/views/components/datagrid/test-export-without-datagrid.html#L57

Its not presently exposed in Ng but if you did a PR for that i think it would work.

**Comment by dmcodrum** [comment]
That sounds ok to me but shouldn't we then deprecate the functionality from the datagrid?

**Comment by tmcconechy** [comment]
Yeah, just the ability to pass a different dataset in. Its still useful as a grid function to export whats there.

**Comment by tmcconechy** [comment]
Since this is an ng issue i moved the issue over there for the wrapper. See/watch https://github.com/infor-design/enterprise-ng/issues/203

**Comment by brianjuan** [comment]
Hi @tmcconechy can this be tested in enterprise?

**Comment by tmcconechy** [comment]
You can retest out page http://master-enterprise.demo.design.infor.com/components/datagrid/test-export-without-datagrid.html but there isnt much to it. It was primarily an Angular issue

**Comment by brianjuan** [comment]
Thanks @tmcconechy , http://master-enterprise.demo.design.infor.com/components/datagrid/test-export-without-datagrid.html passed QA testing. Will now move this to Done.
