### ISSUE TITLE
Label: provide new CSS class to allow text wrapping

### ISSUE THREAD

**Issue by s-gasior** [infor-design/enterprise#7764]
**Is your feature request related to a problem or use case? Please describe.**
We need an ability to make labels wrappable inside form-responsive context. Currently all labels that are under form-responsive parent have ellipsis applied. We also would like to use the same approach for checkbox label without using field class.

**Describe the solution you'd like**
New CSS class that allows text wrapping for labels inside form-responsive parent

**Describe alternatives you've considered**
We thought of using field class for checkbox label but there is a great number of rules applied with the .field selector which we don't have a control of. We want to use it in crucial part of application where we need to be cautious when applying CSS rules because it could cause regression in the whole application when upgrading the IDS library.

**Additional context**
Application Infor WFM

**Comment by tmcconechy** [comment]
Not 100% sure what you mean here but is this example what you want https://main-enterprise.demo.design.infor.com/components/form/test-wrapped-labels.html

**Comment by s-gasior** [comment]
The example looks fine but flex-align-bottom changes display of the row. In our case the label is next to the input so they are misaligned after adding this class.
We would like a simple class that won't be adding additional CSS properties other than white-space. 
![image](https://github.com/infor-design/enterprise/assets/125876056/998db74e-b1a2-4c48-86f0-6e1e99285f6c)

**Comment by tmcconechy** [comment]
Why not have the labels on the top of the inputs like everyone else? I guess this issue is unclear then.
I think we need a mockup of how you think it should look. I can see if you have a left label you might want it on two lines but on clear on the rest of the details for this enhancement

**Comment by s-gasior** [comment]
The use case is a questionnaire type form, where labels will be quite long.

Here is an example:
- first row: label above the input
- second row: label and input in separate columns
- third row: label and input in separate columns with no flex-align-bottom (
![image](https://github.com/infor-design/enterprise/assets/125876056/b16314c5-8d34-4ef4-b40f-54766001484e)

Expected behavior:
- third row: label wraps without using flex-align-bottom
![image](https://github.com/infor-design/enterprise/assets/125876056/25719161-3e7c-43bd-b42b-15f3c520593a)

**Comment by tmcconechy** [comment]
This looks a little odd to me with a huge dropdown and hard to scan label. I'll review with our design team for ideas.

**Comment by ericangeles** [comment]
@s-gasior how does this look on mobile/smaller viewport?
