### ISSUE TITLE
Accordion: Header text is not visible when expanded

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7769]
**Describe the bug**
Header text is not visible when expanded.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/accordion/example-disabled.html
2. Click on 'Notes'
3. Click on 'Skills'
4. Click on 'Compliance Training'
6. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/6d276970-8755-41f4-b492-511f79315fd6

**Platform**
 - All major browsers

**Additional context**

**Comment by glenlieorillo** [comment]
The bug still exists in Light Mode.

Tested in https://main-enterprise.demo.design.infor.com/components/accordion/example-disabled.html

![image](https://github.com/infor-design/enterprise/assets/102151352/70a50b21-9c0f-47cb-bcc4-345793e81135)

![image](https://github.com/infor-design/enterprise/assets/102151352/7e39a20b-f137-4841-8a78-37474a209a11)

Dark Mode:

![image](https://github.com/infor-design/enterprise/assets/102151352/75f95f5e-41ac-45ad-bd0b-a9db55f3a079)

High Contrast Mode:

![image](https://github.com/infor-design/enterprise/assets/102151352/f8e0b5d6-5e4f-4b18-9348-5660ba8d4843)

https://github.com/infor-design/enterprise/assets/102151352/83930729-386d-4c42-af45-a15e0503be92

**Comment by jbrcna** [comment]
QA Failed.
issue still exist

<img width="807" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/d28b9665-bd26-4cf7-9cea-2722974726ef">

see also classic light
<img width="756" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/cf96e82b-9b6f-485e-8a78-1a9af13135bc">

**Comment by jbrcna** [comment]
thanks for clarifying @tmcconechy

**Comment by jbrcna** [comment]
this is now working as expected. 
<img width="1316" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ec74b2b5-e2fb-466d-a372-1cfb5eaa144e">
<img width="1356" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1ccad299-c004-40ce-a8cb-8fa63009911e">
