### ISSUE TITLE
Module Nav: Revisit spacing for icons in collapsed state 

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise#7770]
Looking at what we are seeing in Landmark environments, we want to revisit some of the margins around the global options at the bottom of the menu and see if we can normalize those to allow for a little more space for the application specific icons. 

Typical screen size for landmark users is 1920x1080 @100% scale

Goal is more icons showing before scrolling occurs.

Status: Waiting for design feedback

![MicrosoftTeams-image (11)](https://github.com/infor-design/enterprise/assets/57144784/7dc464a9-f5a8-4c91-a76b-d1fa9ffce0e0)

**Comment by tmcconechy** [comment]
cc @EdwardCoyle if needed this would need to patched into branch https://github.com/infor-design/enterprise/tree/4.84.6 after released to main first

**Comment by hey-yall** [comment]
Design input ticket created here: https://jira.infor.com/browse/IDS-1488 
Put into IDS Design sprint for August Sprint 2 (Aug 10 - Aug 24)
