### ISSUE TITLE
Tabs module: border not properly aligned in RTL

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#7772]
**Describe the bug**
Tab borders are not properly aligned in RTL mode.
It was OK in the past.

**To Reproduce**

1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs/example-index?theme=uplift&variant=light&locale=he-IL](https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs/example-index?theme=uplift&variant=light&locale=he-IL)
2. Click on any tab
3. See problem

**Expected behavior**
In v4.70.0 it was OK
[https://design.infor.com/code/ids-enterprise/4.70.0/demo/components/tabs/example-index?theme=uplift&variant=light&locale=he-IL](https://design.infor.com/code/ids-enterprise/4.70.0/demo/components/tabs/example-index?theme=uplift&variant=light&locale=he-IL)

**Version**

- ids-enterprise: v4.85.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/34129313/b31d4eff-2cb6-4de6-a12a-39c8a0e59fcd)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome/Firefox
 - Browser Version: latest

**Additional context**
Thanks

**Comment by glenlieorillo** [comment]
Tested and passed.

https://main-enterprise.demo.design.infor.com/components/tabs/example-index?theme=uplift&variant=light&locale=he-IL

https://github.com/infor-design/enterprise/assets/102151352/9bad54ca-70f8-45c1-ad70-68835a24b746
