### ISSUE TITLE
Doc site readme file: remove paragraph 

### ISSUE THREAD

**Issue by hey-yall** [infor-design/enterprise#7777]
On the documentation site (specifically at  https://design.infor.com/code/ids-enterprise/latest/typography ), we need to remove the following paragraph from the readme file: 

![image](https://github.com/infor-design/enterprise/assets/122995837/05fa95d3-9834-4fc2-8336-9625f86ffde1)

Please reach out with any questions or concerns. Thanks, developers! 

Linked Jira ticket: https://jira.infor.com/browse/IDS-1447

**Comment by tmcconechy** [comment]
ok done. did it inline here https://github.com/infor-design/enterprise/blob/main/src/components/typography/readme.md

**Comment by hey-yall** [comment]
@tmcconechy You are the GOAT 🐐 ! Thanks so much for the quick work.
