### ISSUE TITLE
Datagrid search is failing when special characters like &, %, # etc with space entered in the seach toolbar

### ISSUE THREAD

**Issue by SasiPalanati** [infor-design/enterprise#778]
**Describe the bug**
Searching in datagrid does not work when using & with spaces.

**To Reproduce**
0. Edit the data on example-keyword-search to include a & in the data in the activity column fix activity:  'Assemble & Paint'
1. Go to http://localhost:4000/components/datagrid/example-keyword-search.html
2. Click on search icon
3. Type "Assemble & Paint"
4. note that no results are found.

**Expected behavior**
If a data grid data has columns with the specified text with the special characters should show those rows.

**Screenshots**
<img width="876" alt="datgrid_search_bug" src="https://user-images.githubusercontent.com/43148169/45313829-736df600-b51f-11e8-8c80-e7213785f25c.PNG">

**Platform**
All

**Additional context**
Seems to work with just "Assemble &" but not with a trailing space after.

**Comment by ericangeles** [comment]
I made some testing for #, &, and % (with a trailing space), and it seems that the really issue is the &.

See attached.

<img width="1039" alt="img-data" src="https://user-images.githubusercontent.com/8839327/45823642-b3ec2180-bd20-11e8-9800-8d502339434d.png">
<img width="1025" alt="img1-" src="https://user-images.githubusercontent.com/8839327/45823643-b484b800-bd20-11e8-9f18-ed6cea2acf16.png">
<img width="1030" alt="img2-" src="https://user-images.githubusercontent.com/8839327/45823645-b484b800-bd20-11e8-805e-91c9cdd470db.png">
<img width="1022" alt="img3-" src="https://user-images.githubusercontent.com/8839327/45823646-b51d4e80-bd20-11e8-9bde-512665bf487f.png">

**Comment by ericangeles** [comment]
And also noticed that the `highlightSearcRows` isn't working on `&`.

**Comment by tmcconechy** [comment]
@deep7102 noticed that it may be this regex... https://github.com/infor-design/enterprise/blob/cfc6030a90c9d02bdbbe1c277f444089d62026a2/src/components/datagrid/datagrid.js#L5277
