### ISSUE TITLE
AppMenu: 'Employee' dropdown menu is too bright when hovered

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7782]
**Describe the bug**
'Employee' dropdown menu is too bright when hovered.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-menu-notification.html
https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-personalized-role-switcher.html
https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-resizable-menu.html
2. Hover over 'Employee' dropdown menu
3. See error

**Expected behavior**

**Version**

- ids-enterprise: 4.86.0-beta.0

**Screenshots**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/8fd11ddc-a591-4cf0-b47c-dfd2d0f7fcbd">

**Platform**
 - All major browsers

**Comment by jbrcna** [comment]
this is now fixed and working in local
<img width="526" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/fcc95ea0-3833-4318-9062-6d660ce47f5d">
<img width="417" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/f4b0c749-3d29-4890-9292-fafb57be7b88">
<img width="693" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/598f44a7-f8c4-4778-96ce-e7ef82fe009f">
