### ISSUE TITLE
Unable to see the button text when Secondary + menu buttons combination is used

### ISSUE THREAD

**Issue by snelanti** [infor-design/enterprise#7783]
**Description**:
Unable to see the button text on **clicking** menu button. Combination of Secondary button + menu- button is creating the issue here. This issue is observed after IDS upgrade to 15.2.1

**To Reproduce**:
1. Apply btn-secondary and btn-menu classes to a button tag
2. Click on the button to see the menu
3. Remove the mouse focus from the button then the button text is invisible.

**Expected behavior**
A clear button text should be visible without hover on the button too.

**Version**
ids-enterprise-ng: 15.2.1
ids-identity: 4.10.0

**Screenshots**
<img width="960" alt="MicrosoftTeams-image" src="https://github.com/infor-design/enterprise/assets/141207120/f414770e-0e5b-4d6c-be05-a1bde2274434">

**Platform**
https://design.infor.com/code/ids-enterprise/latest/demo/components/button/example-menubutton?theme=new&mode=dark
Latest(4.86.0)

**Comment by max-hizon** [comment]
Not sure if the bug being asked to fix is for the mouse hover highlight to remain after moving it or just to make the text visible

Assuming that the button should be highlighted while the dropdown menu is open, the fix doesn't work on classic mode
![image](https://github.com/infor-design/enterprise/assets/79514236/c127603c-1b87-41a1-a85a-6ad6d30465bf)

Above, I have my mouse hovered over the button but when I remove my mouse 
![image](https://github.com/infor-design/enterprise/assets/79514236/65eac9a8-a516-44ec-a135-a5bed51adbc4)

the highlight goes away

Just wanted to check if this is the issue or not

**Comment by snelanti** [comment]
Yes, once the menu button is clicked and menu related to the button is in opened state the menu button should be highlighted (even if mouse is away from button). Yes, This is the issue
