### ISSUE TITLE
Module Nav: Close menu on successful selection or click outside of the menu space

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise#7786]
**Observed behavior**: On mobile, when the module nav menu is set to overlay content on the page, the user is unable to close the menu. The menu only responds to clicks on the the hamburger icon, so when that is hidden by an overlay, users cannot do anything to close the menu.

**Desired behavior**: On mobile, the menu should close when
1. the user clicks on a navigation option 
2. the user clicks outside of the menu entirely 

Happy to elaborate further here, let me know if more details are needed.

**Comment by hey-yall** [comment]
Design resources needed: https://jira.infor.com/browse/IDS-1517
