### ISSUE TITLE
Week view: When we select "Today" in the week view, our customized start and end days are reset or overwritten.

### ISSUE THREAD

**Issue by infor-mahesh** [infor-design/enterprise#7792]
**Describe the bug**
When we are initiating the week with custom start date and end date, when we click on today it is getting overridden.

**To Reproduce**

1. create a custom start date end date, such that it is 7 or more than a week
<img width="584" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/b77233c2-d59d-41ef-910f-1f22cd315d4b">

2. click on today, now by default it shows 6 days
<img width="572" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/b5d7d5ff-cabe-4041-ba2b-b865f819501f">

**Expected behavior**
even if today is clicked the days we initiated should not be gone, example if i am initiating it with current date + 7 days so which completes a week, even when clicked on today the 7 days behaviour should not go

**Comment by tmcconechy** [comment]
@infor-mahesh im not following this issue (screen shots do not show 6 days and steps are confusing). Maybe it would help if you put an example based on https://main-enterprise.demo.design.infor.com/components/week-view in stackblitz

https://stackblitz.com/edit/ids-enterprise-4860?file=index.js

**Comment by infor-mahesh** [comment]
Hi @tmcconechy,
<img width="581" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/9bd2b5db-05da-4b7d-9ead-d68170758e14">
i have taken start date and end date of week view such that start date is current date and end date is next 7 days,


but when i click on today it gives me 6 days 
<img width="584" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/d15e0d6a-5364-45c4-899d-8199a57801d9">

here is the reference.


and more over i checked on design.infor.com on week view- 2weeks example
in two weeks 14 days are displayed, 
<img width="925" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/31c03ae2-86c4-4e0a-b480-5464a4e950d8">

but when clicked on today
it shows only 13 
<img width="935" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/d6c975d3-452c-455e-a156-41c8c73f5fd9">


here is the reference link for two weeks example https://design.infor.com/code/ids-enterprise/latest/demo/components/week-view/test-ajax-events?theme=uplift&variant=light

similar action is being happening for my week for 1 week initially if i load with 7 days and when i click on today it shows 6 days

**Comment by tmcconechy** [comment]
Ok i think that makes sense. Will have a developer try to fix. Especially since we can see it on https://design.infor.com/code/ids-enterprise/latest/demo/components/week-view/test-ajax-events?theme=uplift&variant=light that makes it much easier to reproduce

**Comment by glenlieorillo** [comment]
Passed.

<img width="1791" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/ced57aa4-fb42-4f3f-b92f-4fd190b9f07b">

**Comment by infor-mahesh** [comment]
Hi @tmcconechy ,
is it available now, i tried but it is still not reflecting in the latest version. Any attribute should be added to get this results?
