### ISSUE TITLE
Bar: Cropped bottom axis label; chart title not displayed completely

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7795]
**Describe the bug**
Issue 1: Cropped bottom axis label
Issue 2: Chart title should be displayed completely

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/bar/example-axis-labels.html
2. Notice the chart title and bottom axis label

**Expected behavior**

**Version**

- ids-enterprise: 4.87.0-beta.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/f5265069-1168-48eb-94a7-fa3aa33e3ee6)

https://github.com/infor-design/enterprise/assets/102151352/f0a8a4e1-899b-4d19-a30b-b8af5b03bcbd

**Platform**
 - All major browsers

**Additional context**

**Comment by ericangeles** [comment]
This issue regarding widget title should be fixed in this PR https://github.com/infor-design/enterprise/pull/7920, but there's something wrong with the main environment not applying the recently merged fixes.

**Comment by jbrcna** [comment]
QA Passed
<img width="1037" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/7321761e-c278-4879-9a55-f27486255863">
