### ISSUE TITLE
Editor: unable to change the heading using keyboard keys

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7796]
**Describe the bug**
 in Firefox when you select all using keyboard `cmd + A (ctrl +A)` then change the heading, it doesn't work. selecting all by mouse click is working fine.

**To Reproduce**

1. Go to https://beta-bugs-enterprise.demo.design.infor.com//components/editor/example-index.html
2. try selecting all text using mouse (click and hold)
4. change heading style
5. works fine
6. try selecting all text using keyboard (cmd + A / ctrl + A)
7. change heading style
8. see error

**Expected behavior**
should be able to change styles using mouse and keyboard keys. 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![Large GIF (1358x462)](https://github.com/infor-design/enterprise/assets/56722184/530fc645-4d7e-43fe-afb3-5f29a37f9cd4)

**Platform**
Firefox

**Additional context**
found when testing https://github.com/infor-design/enterprise/pull/7765

**Comment by tjamesallen15** [comment]
@jbrcna Hello, can we retest this one? I've been following your instruction and can't reproduce it. Thanks.

**Comment by jbrcna** [comment]
@tjamesallen15 Hi, please try using Firefox 
try selecting all text using keyboard (cmd + A / ctrl + A)
change heading style
![Large GIF (1286x572)](https://github.com/infor-design/enterprise/assets/56722184/31747661-90e7-443e-bc3b-954ecbbd73c1)

**Comment by tjamesallen15** [comment]
Thanks for clarification @jbrcna

**Comment by jbrcna** [comment]
this is now working in local
![Large GIF (1346x484)](https://github.com/infor-design/enterprise/assets/56722184/20acd69e-2312-49da-9c09-4c4a21677b23)
