### ISSUE TITLE
Calendar: Day legend shading applied in Month view but not Week/Day views

### ISSUE THREAD

**Issue by timothyholton** [infor-design/enterprise#7800]
When Calendar has a Day Legend it is applying background shading to "Weekend" days in Month view but not in Week view or Day view.  Note that background shading is being applied correctly to other types of days ("Public Holiday" days and "Other" days) in all views correctly.

1. Open a calendar that has a Day legend.
2. In "Month" view, observe that "Weekend" days are shaded correctly.
3. Switch to "Week" or "Day" view.
4. Observe that the "Weekend" days are not shaded.

**Expected behavior**
The "Weekend" days should also be shaded when in "Week" and "Day" views, just like they are in "Month" view.

**Version**
v4.80.0

**Screenshots**
Refer to attached file.
[Calendar day background.docx](https://github.com/infor-design/enterprise/files/12331626/Calendar.day.background.docx)

**Platform**
 - Infor Application/Team Name: Infor Pathway
 - Device: Laptop
 - OS Version: Windows 11
 - Browser Name: Chrome

 - Browser Version: 115.0.5790.171 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Was this the same issue https://github.com/infor-design/enterprise/issues/6568 seems like it and resolved?

**Comment by timothyholton** [comment]
No, this ticket is for what appears to be an omission in the implementation of 6568, in that the Week and Day views do not seem to apply a Day Legend background colour to Weekend days.  Please refer to the file attached to this request which has some screen shots to illustrate this.
I have done a little more investigation, and it seems like the Week and Day views are not recognising the Calendar dayLegend "Weekend" dayOfWeek setting, highlighted below.

![image](https://github.com/infor-design/enterprise/assets/107448146/2283c892-d856-4524-9fe1-21301755fef4)
