### ISSUE TITLE
ModuleNav: Mobile Follow up Issues

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7804]
**Describe the bug**
As of now these aren't blocking but need workarounds. As follow up to https://github.com/infor-design/enterprise/issues/7786 around mobile behavior of module nav

**Questions/Issues**

- [x] Go to a new design for some sort of "hang over it" like a box shadow. Design would be similarish to https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html when it is on mobile size
- [x]  If enableOutsideClick is on "offset the page container" should be off
- [x] Zindex is too low to hang over (see below)
- [x] Should the setting `enableOutsideClick` by on by default?
- [x] Should it collapse on mobile or go to "hang over" mode
- [x] mobileCollapse setting - would either collapse on mobile break point or stay expanded and hang over the content
- [x] Animation (decided to skip)
- [x] https://github.com/infor-design/enterprise/issues/7934
- [x] has-module-nav-offset -> will change width of page container not set margin-inline-start (page patterns get wrong width)
- [x] https://github.com/infor-design/enterprise/issues/7823
- [x] Angular issue with page clicks
- [x] Angular types for new settings

**Expected behavior**
Above issues addressed

**Comment by tmcconechy** [comment]
<img width="839" alt="image" src="https://github.com/infor-design/enterprise/assets/814283/11604dc0-4a1e-44ff-9bd4-3fb25c6c6b13">

**Comment by inforandy** [comment]
design is ready on this one https://www.figma.com/file/bL4EBYtWjgfBsvTVI9seXU/branch/cq48fPCCQ1RatdOLOtshpe/Module-Nav-%7C-Application-Menu?type=design&node-id=6269-15955&mode=design&t=uvAqniela7CDJ0y8-0
