### ISSUE TITLE
Classic Theme missing `empty-no-data` icon for Datagrid

### ISSUE THREAD

**Issue by SumitK27** [infor-design/enterprise#7808]
**Description**
We have recently upgraded from IDS Enterprise **v4.54.0** to **v4.83.1** and has noticed that the `soho-datagrid` is lacking the no data icon after switching to the classic light theme and enabling the old icons.

![v4.54.0](https://github.com/infor-design/enterprise/assets/40501698/ea1557a9-428c-49f1-9ad0-fe5c88be615a)

![v4.83.1](https://github.com/infor-design/enterprise/assets/40501698/995fa99f-6a9f-48fb-8a71-da446c635d76)

The icon was available until version **4.80**, but not since version **4.81**.

**Describe the solution you'd like**
We'd like the old icon `icon-empty-no-data` to be displayed by default.

**Describe alternatives you've considered**
We have tried adding the `emptyMessage` property to the datagrid
```ts
this.sohoDataGridComponent.emptyMessage = { title: 'No_Data', info: '', icon: 'icon-empty-no-data', color: 'graphite' };
```
but regardless of the `color`, the icon is displayed as shown below.

![v4.83.1 with empty message](https://github.com/infor-design/enterprise/assets/40501698/c71a7ea4-cb9f-4224-85fb-9737b421aa6a)

**Additional context**
We are currently working on Infor GRC with the intention of allowing users to select their preferred theme.

**Comment by tmcconechy** [comment]
on testing on https://main-enterprise.demo.design.infor.com/components/emptymessage/example-index.html?theme=classic&mode=light&colors=default i noticed that the page is trying to change to the new icon.

So for classic just use `#icon-empty-no-data` instead of `#icon-empty-no-data-new` unless your finding its automatically changing it like that page? If so we can fix that.

But do note. We are no longer updating classic and adding new icons. And its deprecated. In the new web component version its not available. And new features are not being added to classic.

**Comment by SumitK27** [comment]
The SVG icon used in the grid contains a `use` tag with `href="#icon-empty-no-data-new"` and even after changing it to `#icon-empty-no-data` from dev tools [this](https://user-images.githubusercontent.com/40501698/260653650-c71a7ea4-cb9f-4224-85fb-9737b421aa6a.png) icon is being displayed and not the one provided in the `ids-enterprise\dist\svg\theme-classic-svg-empty.html`

If the icon change behavior from `#icon-empty-no-data` to `#icon-empty-no-data-new` can be fixed and if the grid uses the SVG provided in `theme-classic-svg-empty.html` (after replacing with old icon from our side) then we may get a work-around fix for this.

Please suggest a solution for using the icon in above manner.

**Comment by tmcconechy** [comment]
Sorry not sure i follow the last comment. But i tested this out. Here is an example that works.

```
<div class="row">
  <div class="four columns">

    <!-- Data (None Available) -->
    <div class="card is-empty">
      <div class="card-header">
        <h2 class="widget-title">Data</h2>
        <button class="btn-actions" type="button">
          <span class="audible">Actions</span>
          <svg class="icon" focusable="false" aria-hidden="true" role="presentation">
            <use href="#icon-vertical-ellipsis"></use>
          </svg>
        </button>
        <ul class="popupmenu actions top">
          <li><a href="#">Action One</a></li>
          <li><a href="#">Action Two</a></li>
        </ul>
      </div>
      <div class="card-content">
        <div class="card-empty-icon">
          <svg class="icon-empty-state is-slate" focusable="false" aria-hidden="true" role="presentation">
            <use href="#icon-empty-no-data"></use>
          </svg>
        </div>
        <div class="card-empty-title">
          No data available
        </div>
        <div class="card-empty-info">
          Description of empty message that explains why and possibly contains a hyperlink.
        </div>
        <div class="card-empty-actions">
          <button type="button" class="btn-primary">
            <span>Action</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
```

Just make sure to use `<use href="#icon-empty-no-data"></use>` and not the one with 'new' in it. Again we wont be adding all the new icons to classic mode. Just the old ones will work.
