### ISSUE TITLE
soho-toolbar-flex-more-button not working as intended in PortalV2

### ISSUE THREAD

**Issue by gustavpollak** [infor-design/enterprise#7810]
**Describe the bug**
soho-toolbar-flex-more-button not working as intended in PortalV2

**To Reproduce**
Create a scenario where the width of the toolbar forces the actions into the "more" button.

In either mobile view in browser, or just a really small width browser window.

1. Go to [PortalV2 ](https://mingle-ci-portal.mingle.inforos.dev.inforcloudsuite.com/v2/PORTALV2_PP6)
2. Set window width to 400px (or mobile mode)
3. Click on 'Menu' button
4. Click on "Test Application (OS Portal)"
5. Verify that right side panel is extended.
6. Click on "Add widget"
7. Click '+' icon to add any random widget.
8. Click "X" to exit catalog
9. Click "..." more options to view the "Save" button
10. Click "Save"

**Expected behavior**
Clicking "Save" button in the "..." menu should save the Insight group 

**Version**
data-ids-enterprise-ng-version="16.5.0"
data-sohoxi-version="4.85.0"

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://github.com/infor-design/enterprise/assets/49652924/4d6b2370-5b97-4e63-9268-c416e3b7c998)

**Platform**
 - Infor OS Portal v2
 - Device: PC
 - OS Version: W11
 - Browser Name: chrome
 - Browser Version: Version 115.0.5790.171 (Official Build) (64-bit)

**Additional context**
I'll gladly provide credentials to login to provided tenant for you to see the issue, please reach out to me in Teams/mail at gustav.pollak@infor.com and I'll respond as fast as I can.

I was not able to reproduce the issue in your samples from the IDS website.

**Comment by tmcconechy** [comment]
@gustavpollak i took a quick look just to see and i wonder if you need to hide the left side white space or right bar on mobile (was told the bar isnt supposed to be there on mobile)

But i suspect the issue is that extra space on the left that is white.

![Screenshot 2023-08-15 at 8 56 25 AM](https://github.com/infor-design/enterprise/assets/814283/b718a92a-915d-4cb6-a64f-41d9bcf5f0f1)

**Comment by alixrosales** [comment]
@gustavpollak I don't think you would ever get to this point. We don't have the Smart Panel in Infor Go and when you resize it in a desktop setting it doesn't have the bug. The issue seems to be that the hit area in mobile doesn't match the button so it doesn't hit.

**Comment by tmcconechy** [comment]
@gustavpollak did you try to fix the left panel to make this work? I.E. is it a non-component issue really? Thanks

**Comment by gustavpollak** [comment]
@alixrosales I just recreated the issue, it's still there even in desktop mode, as long as the browser width is small enough to trigger the "..." menu, then those options in the menu won't work.

@tmcconechy I'm not sure which left panel to fix. It's in the step when you've added a widget and then want to save it, not when it's empty. 

I'll attach another gif:

 
![small-width-menu-options-not-working](https://github.com/infor-design/enterprise/assets/49652924/fa01619d-122e-4619-8136-73e72c60935f)

**Comment by gustavpollak** [comment]
We found a solution to the issue and solved it in the client code, I'll close this ticket as solved, thanks for the help 😊
