### ISSUE TITLE
Slate: Personalization Color is wrong

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7811]
**Describe the bug**
Slate color has the wrong colors. With poor contrast. Make the colors the same as graphite.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/module-nav/header/example-index.html?colors=6F6F76
2. See error
3. Been like this a long time https://4610-enterprise.demo.design.infor.com/components/header/example-index.html?colors=6F6F76 as far as i can tell

**Additional context**
Better colors for slate. Make the colors the same as graphite (white ish buttons). Probably in the personalization color code.

**Comment by talkaboutdesign** [comment]
Would like design team to weight in here on exact values. Both for the bar itself and the text/active items. @tmcconechy can we create a JIRA ticket for this with high priority.

**Comment by tmcconechy** [comment]
@talkaboutdesign what is there to design here? Its just fixing the color on the header? https://github.com/infor-design/enterprise/pull/7825

https://7811-slate-personalization-color-enterprise.demo.design.infor.com/components/header/example-index.html?colors=6F6F76

BTW think a wrong link so updated... Maybe some confusion?

**Comment by talkaboutdesign** [comment]
I think I got confused by your comment on white ish buttons. What was the final resolution?

**Comment by tmcconechy** [comment]
We just changed it https://7811-slate-personalization-color-enterprise.demo.design.infor.com/components/header/example-index.html?colors=6F6F76

So its the same as other colors like https://7811-slate-personalization-color-enterprise.demo.design.infor.com/components/header/example-index.html?colors=0066D4
