### ISSUE TITLE
Dropdown: empty icon not cleared

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#7813]
**Describe the bug**
When using **dropdown** that has options with icons and options with no icons, when selecting the option with no icon, the previous icon is not cleared

**To Reproduce**

1. Go to [https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/test-icons-color.html](https://design.infor.com/code/ids-enterprise/latest/demo/components/dropdown/test-icons-color.html)
2. Select the last option (No Icon) - you can select either one of the four last options
3. See that the icon is not cleared from dropdown

**Expected behavior**
Option with `data-icon=""` or `data-icon="{}"` or `data-icon="{icon:''}"` should clear the last icon selected

**Version**

- ids-enterprise: v4.86.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/34129313/5208ecd9-7e4a-4ac0-92fb-5b31c9333070)

RTL example first option is set with `data-icon="{}"` , we see the last selected icon:
![image](https://github.com/infor-design/enterprise/assets/34129313/c6fb42c8-3ed1-4f62-bf5a-534f8045fd17)

**Platform**

 - OS Version:  Windows 10 
 - Browser Name: Chrome/Firefox
 - Browser Version: latest

**Additional context**
Thanks

**Comment by glenlieorillo** [comment]
This is now working as expected in main.

<img width="1791" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/af974357-5ad0-465e-b9c7-8788edefc838">

**Comment by glenlieorillo** [comment]
This is now working as expected in main-enterprise.

<img width="1791" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/e85bf4c3-fe9e-404f-a896-739626a79362">
