### ISSUE TITLE
Datagrid: Design Cleanup for Alabaster

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7814]
**Describe the bug**
Need to finish up alabaster theme fixes for the Datagrid component

Datagrid -> https://main-enterprise.demo.design.infor.com/components/datagrid/example-index.html

**Expected behavior**

Datagrid: https://www.figma.com/file/4CtBGz8dwvSa6JsBcdtVZQ/Data-Grid?type=design&node-id=2388-30705&mode=design&t=npya2cBC5ZmD3wcz-0

See: https://jira.infor.com/browse/IDS-1334

**Comment by sanx72** [comment]
@tmcconechy am I missing something on this one? Downloaded 4.87.0 and all the data grid headers have gone white, regardless of the colour used, but the text for this feature says _"Has a new design with a soft grey header. The white header background option is removed and this is now the default."_ so I was expecting some sort of grey background. The link above shows the same but the example still point to 4.86.0 so still use the old shading (dark grey/blank).

**Comment by tmcconechy** [comment]
@sanx72 no your not missing anything. The new style is https://main-enterprise.demo.design.infor.com/components/datagrid/example-index.html

Debatable if you want to call it "white" but its slate 01 in the color pallette https://main-enterprise.demo.design.infor.com/components/colors/example-index.html I would call it soft grey...

This was request by design to remove the dark colors

**Comment by sanx72** [comment]
@tmcconechy on my DELL monitor #FAFAFA vs #FFFFFF is barely indistinguishable in either Chrome or FireFox; e.g.

![image](https://github.com/infor-design/enterprise/assets/44396995/6eba277f-cae0-4123-9a36-9496216c0867)
![image](https://github.com/infor-design/enterprise/assets/44396995/f1e5e7ff-cc87-4417-bb99-4650107b0986)

**Comment by tmcconechy** [comment]
i was aware that on some monitors with less colors some of the lower end colors are harder to see. I wonder if @talkaboutdesign that means we want to bring it up one? How does slate 02 look @sanx72 ?

**Comment by sanx72** [comment]
@tmcconechy slate02 (#e0e0e1) definitely gives a better contrast in practice IMO...

![image](https://github.com/infor-design/enterprise/assets/44396995/77d2c1b8-473d-404a-a0b3-ff11457c40d9)

![image](https://github.com/infor-design/enterprise/assets/44396995/dd4c40ee-7d19-431b-8cac-7c891ecc2083)
