### ISSUE TITLE
Uncaught error when clicking on more in Calendar (Month view)

### ISSUE THREAD

**Issue by kingstonkoa** [infor-design/enterprise#7818]
**Describe the bug**
Clicking the +n more in `Calendar` throws an error in the console when `showViewChanger` is set to `false`

**To Reproduce**

1. Make sure `showViewChanger` setting is set to `false`
2. Create an event of 4 or more in a day to trigger the more option in the day
3. Go to Calendar with month view shown
4. Click + x more
![image](https://github.com/infor-design/enterprise/assets/10598258/64805ab9-72b0-4fb8-862b-d3aaf6a32505)
5. View error thrown in the console

**Expected behavior**
No error thrown when more is clicked, and it redirects to the day view

**Version**

- ids-enterprise: v4.85.0

**Screenshots**
- Error thrown
![image](https://github.com/infor-design/enterprise/assets/10598258/ce66953e-5263-43b8-92af-b2842cba2bd7)

Error occurs in calendar-toolbar.js
![image](https://github.com/infor-design/enterprise/assets/10598258/1965f0a3-6697-4fe2-9dff-9a9b6fbfe3f7)

**Platform**
 - Infor Application/Team Name: Infor MFS (Cordova application)
 - OS Version: Windows 10
 
Cordova cannot handle js errors, which causes the application to crash

**Comment by tmcconechy** [comment]
@kingstonkoa I made a branch with edits to try to reproduce this but could not https://github.com/infor-design/enterprise/pull/new/7818-calendar-bug

Could you check this out and tell me what i need to add to reproduce? After running the branch then go to http://localhost:4000/components/calendar/test-specific-month.html and try clicking the + More and im not seeing any issue?

**Comment by kingstonkoa** [comment]
Hi Tim, I ran the branch provided. Functionality-wise, the issue would not manifest in the UI, however looking at the console, an uncaught `TypeError` was thrown
![image](https://github.com/infor-design/enterprise/assets/10598258/84ee950f-dbc1-42ae-a31f-3a4df03a9489)

the error occurs at calendar-toolbar.js line 362.

The error thrown would result into a crash in a react cordova built platform

Thank you

**Comment by tmcconechy** [comment]
ok @kingstonkoa check out https://github.com/infor-design/enterprise/pull/7835
I cant confirm this fixes it but assume it would...

If you can please test / review the fix

**Comment by kingstonkoa** [comment]
Hi @tmcconechy tested and checked the fix, uncaught error no longer occurs in the console.

thank you.
