### ISSUE TITLE
ModuleNav: Images when loaded are the wrong/non constrained size

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7820]
**Describe the bug**
When loading external images the size is not enforced

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/module-nav/example-icon.html
2. Click on 'Use Url' in the dropdown
3. Inspect the image size (lego man)

**Expected behavior**
Should be 32x32 not any other size

**Comment by jbrcna** [comment]
QA Passed.
https://main-enterprise.demo.design.infor.com/components/module-nav/example-icon.html
<img width="779" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/b0219609-73c5-42d3-8c0e-a694af0f6118">
