### ISSUE TITLE
ModuleNav: Need to expose context menu event

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7822]
**Describe the bug**
LM needs to be able to right click the dropdown menu. Then open a URL on a new link.

**To Reproduce**
1. Go to  https://main-enterprise.demo.design.infor.com/components/module-nav/example-index.html?colors=fff
2. Click on module switcher drop down
3. right click a menu item and open in new window

**Expected behavior**
- could have either a (contextmenu) on the module nav switcher
- or a onContextMenu call back
- in the test page the URL gets inserted so it can be followed but it should only stay for right click not normal click

**Comment by jbrcna** [comment]
QA Passed.
https://main-enterprise.demo.design.infor.com/components/module-nav/example-index.html?colors=fff
<img width="1149" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/95f65b8f-8496-43b1-9a7e-693faa8f76ab">
