### ISSUE TITLE
Calendar: Override the color of one event within an event type

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#7826]
**Describe the bug**
Override the color of one event within an event type

**To Reproduce**

1. Go to '[...](https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html)'
2. Double Click on today's date and add a new event.
3. Open the browser's console and change the new event color "$('.calendar').data('calendar').settings.events[78].color = 'emerald'"
4. Change the view of the month so that the new event is rendered

**Expected behavior**
The event should be emerald instead of the event type so that it can be identified by its data.

**Version**
- ids-enterprise: 

**Design**
 https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=346-11814&mode=design&t=DYjJiuYxPZouEwaF-0

But really means. Improve the API to work and use the 01 range of colors for the day when its custom

**Platform**
 - Infor Application/Team Name: Pathway

**Additional context**
Being able to identify one event can help the user find an event that relates to navigation. The alternative is to make a special event type, but this could lose some functionality if it is actually one of the listed event types. 

An example for the test form would be to highlight the leave that you are approving, and that leave type in "Administrative leave".

**Comment by marknolaninfor** [comment]
The requirement is that event on the 27th, "Today is the day", has a different color so that it can be identified. Without the requirement of adding an additional event type on the legend.
![image](https://github.com/infor-design/enterprise/assets/39749678/5a49e4b1-4011-4841-93cd-dfa4f14af938)

**Comment by tmcconechy** [comment]
Ok i'll see if we can do that. Should be possible

**Comment by hey-yall** [comment]
Design resources ticket: https://jira.infor.com/browse/IDS-1820

**Comment by tmcconechy** [comment]
Ready for Dev. See to clarify  https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=346-11814&mode=design&t=DYjJiuYxPZouEwaF-0

But really means. Improve the API to work and use the 01 range of colors for the day when its custom

**Comment by marknolaninfor** [comment]
> @marknolaninfor can you look at https://jira.infor.com/browse/IDS-1820 I think from what i read you only want the API to set the day color. You dont need the user to pick a color? Or do you see:
> 
> https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=918-19058&mode=design&t=3sS3LJrsRI23LOqV-0

@tmcconechy 

Can not log on to Figma to confirm

Infor Figma SSO
Sorry, but we’re having trouble signing you in.

AADSTS50105: Your administrator has configured the application Infor Figma SSO ('2bd14efb-efe9-463c-a9af-5f6efedae06d') to block users unless they are specifically granted ('assigned') access to the application. The signed in user 'mark.nolan@infor.com' is blocked because they are not a direct member of a group with access, nor had access directly assigned by an administrator. Please contact your administrator to assign access to this application.

**Comment by tmcconechy** [comment]
<img width="938" alt="Screenshot 2024-01-18 at 4 25 22 PM" src="https://github.com/infor-design/enterprise/assets/814283/d853ac48-e6b3-4cb3-8e12-eeb881db9d75">

Looks Like that:

I think may be irrelvent because we took the picker out. I think in summary you just want the days to be custom colors but the API isnt working. The user never picks the colors?

For future you can get access to and infor-issued Figma license via the Infor IT Help Desk ithelpdesk@infor.com

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise/pull/8368 is sort of related but

a) the API may not be working and
b) not sure we have an example showing the color of a day changing on the API

**Comment by marknolaninfor** [comment]
@tmcconechy 

I do not think the example shows any event that has a different colour from the legend.

I would have expected that maybe the TEST EVENT B on the 28th would be a different colour.

**Comment by tmcconechy** [comment]
ok maybe we are way off base here and combining something else @marknolaninfor so you just want to be able to:

- set the event color of any individual event to one thats not the currently assigned legend color?

the rest can be considered other calendar changes

**Comment by marknolaninfor** [comment]
@tmcconechy 

Yes, as you can specify a colour for the event but currently if it is part of an event type then the colour for the event type is used. 

The use case is to schedule a booking event, so the user is loading the calendar from another page and the event needs to be highlighted so that they can identify the event.

**Comment by talkaboutdesign** [comment]
> @tmcconechy
> 
> Yes, as you can specify a colour for the event but currently if it is part of an event type then the colour for the event type is used.
> 
> The use case is to schedule a booking event, so the user is loading the calendar from another page and the event needs to be highlighted so that they can identify the event.

Can you more clearly explain the use case. This is a little confusing. If such functionality exists in calendars like outlook I am not aware of it, or not really understanding your need.

**Comment by talkaboutdesign** [comment]
> @tmcconechy
> 
> I do not think the example shows any event that has a different colour from the legend.
> 
> I would have expected that maybe the TEST EVENT B on the 28th would be a different colour.

Why would Test event B be different color, if all events of that type are labeled in that color?

**Comment by inforandy** [comment]
@talkaboutdesign It's a conditional state applied to a dynamic group of events based on user selection criteria. imagine the following


1. an employee of yours requested off like, 3 random days next month
2. you want to look at them all in one glance following a link that the ERP sent you "Your employee has new DTO reqs"
3. Then you want to go to a calendar that already has other employee requests on it, but these three should be a unique color

**Comment by marknolaninfor** [comment]
@talkaboutdesign 

For @inforandy example you would be loading the calendar to approve a single DTO request, so to correctly approve the leave the calendar will show all the leave events for your team.

The purpose of highlighting one event differently is to show that this is the event that you are going to approve. You can not highlight the day as it is possible to have more than one event on a day.

The event needs to be highlighted to the end user, so a different colour, a border, or any other method that allows the rest of the data to remain the same.

**Comment by tmcconechy** [comment]
See new design https://inforwiki.atlassian.net/browse/IDS-1820 for the color
