### ISSUE TITLE
Datagrid: multiselect banner is not personalized

### ISSUE THREAD

**Issue by GabrielaRy** [infor-design/enterprise#7828]
**Describe the bug**
datagrid banner on multiselect is staying azure even when is the accent color different

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-multiselect?colors=8D0B0E&theme=uplift&variant=light
2. select any row
3. observe the issue

**Expected behavior**
banner should be personalized 

**Version**
latest

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/60609323/9dffbc6c-451a-46dd-9478-ab99bc37b834)

**Comment by tmcconechy** [comment]
Previous discussion this is not personalizable. See https://github.com/infor-design/enterprise-wc/issues/1029 
https://jira.infor.com/browse/IDS-970

But will bring up once more.

**Comment by tmcconechy** [comment]
Working as designed. Closing
