### ISSUE TITLE
Searchfield: icon hover color have different size

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7832]
**Describe the bug**
x icon hover color size is different from custom icon

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/searchfield/example-buttons.html
2. Type a text in searchfield
3. hover on each icon

**Expected behavior**

**Version**

- ids-enterprise: v4.87.0-dev
- 

**Screenshots**
<img width="322" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/4b75ec7d-4987-4634-869f-9c305fef8c40">
vs
<img width="272" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/0e09bfa4-bb89-4959-9ae3-bd221ec7076d">

**Platform**
All major browsers

**Additional context**

**Comment by jbrcna** [comment]
this seems to be fixed. v4.99
https://main-enterprise.demo.design.infor.com/components/searchfield/example-buttons.html
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/bacce911-9c01-4392-ba96-94f8df6d5f2c">
<img width="1294" alt="image" src="https://github.com/user-attachments/assets/5e729618-e841-45a2-8a7b-9337420b0339">

but not in classic view
<img width="1144" alt="image" src="https://github.com/user-attachments/assets/f16df004-5391-4f03-8e6c-45cde4bebff6">

**Comment by tmcconechy** [comment]
Lets descope classic mode here.
