### ISSUE TITLE
Bubble: Labels are not aligned in legend

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7834]
**Describe the bug**
Labels are not aligned in legend.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/bubble/example-contextmenu.html, https://main-enterprise.demo.design.infor.com/components/bubble/example-disable-selection-state.html, https://main-enterprise.demo.design.infor.com/components/bubble/example-index.html
2. Notice the legend

**Expected behavior**
Legend should be rendered properly.

**Version**

- ids-enterprise: 4.86.0-beta.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/ffe92a2a-7572-4b52-8e4f-de0d6bbb9c5f)

**Platform**
 - All major browsers

**Comment by jbrcna** [comment]
QA Passed

https://main-enterprise.demo.design.infor.com/components/bubble/example-contextmenu.html
<img width="891" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/682cac3d-4673-4d7d-9883-e34ea5fac9cd">

https://main-enterprise.demo.design.infor.com/components/bubble/example-disable-selection-state.html
<img width="879" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/0f92e3e3-4fe8-4cca-9ef5-211e5dc5f134">

https://main-enterprise.demo.design.infor.com/components/bubble/example-index.html
<img width="878" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/fa40372c-62e3-4ec0-b6ab-3d9b55d5e3d4">
