### ISSUE TITLE
Image: Some icons are 50x50

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7836]
**Describe the bug**
Some icons on https://main-enterprise.demo.design.infor.com/components/images/example-photos.html are 50x50 should be 48x48.

**To Reproduce**
1. Go to  https://main-enterprise.demo.design.infor.com/components/images/example-photos.html
2. Inspect each icon and ensure they are 48x48 not 50

**Additional context**
https://jira.infor.com/browse/IDS-478

**Comment by jbrcna** [comment]
QA Passed
<img width="770" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/00de79f1-1ea3-4f3f-a8cd-26965ab0cd7c">
