### ISSUE TITLE
Links: Some links are missing underline

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7838]
**Describe the bug**
The link on https://main-enterprise.demo.design.infor.com/components/listview/example-list-view-classes.html is missing the underline

**Expected behavior**
Should haver one like https://main-enterprise.demo.design.infor.com/components/hyperlinks/example-index.html

**Additional context**
https://jira.infor.com/browse/IDS-479

**Comment by jbrcna** [comment]
QA Passed
https://7838-link-underline-enterprise.demo.design.infor.com/components/listview/example-list-view-classes.html?theme=classic&mode=light&colors=default
<img width="443" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/c87b56b6-85e4-4046-8622-49f97788ee72">
