### ISSUE TITLE
Week view: show time in over night shift

### ISSUE THREAD

**Issue by infor-mahesh** [infor-design/enterprise#7840]
**Is your feature request related to a problem or use case? Please describe.**
Use case: if we are showing an over night shift in week view component it is not showing the time.
example: if the shedule is starting from 21-08-2023 11pm to 22-08-2023 1am then it directly shows its an over night shift which is fine but the duration is not shown

**Describe the solution you'd like**
Required time duration on over night shifts displayed on week view and if the name is big it is limiting characters

**Additional context**
<img width="206" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/5c59f7d4-7f88-4b15-9055-77e8b1766c3a">
<img width="412" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/814dc840-543f-42ee-b376-ed665eead98e">

**Comment by tmcconechy** [comment]
@infor-mahesh how do we reproduce this?

**Comment by tmcconechy** [comment]
To fix.

a) add a date that spans over two days like
```
  {
    "id": "1",
    "subject": "Discretionary Time Off",
    "shortSubject": "DTOssss",
    "comments": "Short getaway",
    "location": "Us Office",
    "status": "Draft",
    "starts": "2018-08-22T00:00:00.000",
    "ends": "2018-08-23T23:59:59.999",
    "type": "dto",
    "isAllDay": "false"
  },
```
2. Note that it goes to isAllDay when it should not. It should stay in the timed section below and span two days
3. Also can we update all examples to 2023 instead of 2019

**Comment by glenlieorillo** [comment]
Working now as expected in web browsers.

<img width="1791" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/151bd795-dd66-4e73-b0c8-8d50ec3c3deb">

However, overnight event is not present (23rd date).

![image](https://github.com/infor-design/enterprise/assets/102151352/03c1862f-e674-4128-9620-f6e0dbc53809)

**Comment by infor-mahesh** [comment]
hello @tmcconechy ,
can you please specify how to use this? like what fields to be added to use this feature and steps
 or example

**Comment by tmcconechy** [comment]
@infor-mahesh nothing special it is automatic based on the time. So when your times end up overnight https://github.com/infor-design/enterprise/pull/8026/files#diff-3f57d2dbe7113ebb18ccddcc6a23eb122ce410587dc9d15b8ac9a9cd0e2cce03R777-R780

It will show as overnight https://main-enterprise.demo.design.infor.com/components/week-view/example-stacked.html

This is example data for that page https://github.com/infor-design/enterprise/blob/9b1e463a1322ba568e63f1f0be173c0d7ed801ff/app/data/events.json

**Comment by infor-mahesh** [comment]
then how to disable this separation
<img width="650" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/f9743597-385e-43f8-9ce6-2cc75800432a">

**Comment by tmcconechy** [comment]
We did not add a way to disable that all day section, i didnt see it mentioned or discussed. We could add a setting if you need it? New issue please

**Comment by infor-mahesh** [comment]
so how the overnight shift is differentiated? 
<img width="367" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/dbff1fcc-36ce-43e0-84d1-8f7e9cc16bb5">
both conference and overnight spans 2 days?

**Comment by tmcconechy** [comment]
If you need it to span more than one day you could still put it in the top section. The use case bind the overnight shift was "overnight" we thought so it goes over the night within the same date. Would be no way to show it stacked and on multiple days since its unsorted.

I guess if you wanted to show it in both days you could but this also wasnt mentioned.

**Comment by infor-mahesh** [comment]
what we actually wanted is if there is an overnight shift it should display on 2 days which i guess you already provided but what i am talking is linked to this https://github.com/infor-design/enterprise/issues/7700

**Comment by infor-mahesh** [comment]
so what it is currently implemented if it is spaning 2 days show with time? and if it is more then 2 then show it on overall? is that correct?

**Comment by tmcconechy** [comment]
OK as i see it

1) we missed https://github.com/infor-design/enterprise/issues/7700 in that we interpretted it differently. So can repopen that and add a setting
2) We did not consider it spanning 2 days with that setting and that area is hidden there is no way to do it. I actually have no idea what we could do. The thing we cant do is line it up when its stacked. So maybe if its 2 or more days we put it up top in that case?  Have to discuss with design. 

I would suggest we make a new issue so its very clear whats missing. I can do it just clarify with me if thats all thats missing here? May help to add some sample data that represents all the cases.

**Comment by infor-mahesh** [comment]
ha almost there, this is our design 
<img width="440" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/2c6e88b4-7013-475a-8192-9f280b00862c">
 so what basically we require is we don't need. over all row(the row which is specifing conference on all day), so if we have any shift spanning more then one day it should display with time(same as you implemented overnight shift) and you can see in this example if its an holiday(which is an all day event) it should display in the shedule like this ex: veteran day

**Comment by tmcconechy** [comment]
ok, not totally following that. this is all new stuff that we didnt consider. Maybe you can make a new clean issue with the design and carefully list the missing things? You lost me on Veterans day and "pill" ect?

**Comment by infor-mahesh** [comment]
ha yes veterans' day is a single day no issues in that, we need a setting to hide the all day thing and along with over night shift if there is a range longer than 2 days also it should show in each schedule with time because we would be hiding the all day row?

**Comment by infor-mahesh** [comment]
example which you showed conference if we hide it then conference will be not shown? so we need that in the schedule but not on all day row but as a pill with time everyday(the days which is specified). so when we created to hide the all day row event we thought it would be shifted in schedule

**Comment by tmcconechy** [comment]
@infor-mahesh actually we have a setting to hide that area https://github.com/infor-design/enterprise/blob/main/src/components/week-view/week-view.js#L63 i forgot.

So maybe try that and then maybe. Try if that day spans more than one day, then manually split the data in two so it shows in both time stacks?

**Comment by infor-mahesh** [comment]
Tell me the steps to hide the all day row(it was recently added)

And after hiding the the data in that also hides

But spliting it via logic is not that preferable to maintain consistency we prefer compinent to do that so we need something like if the row is hidden it should show over pill

**Comment by tmcconechy** [comment]
Just set the setting https://github.com/infor-design/enterprise/blob/main/src/components/week-view/week-view.js#L63 to false. Not really any "steps" i can share there.

If you cant split the dates like i said we can consider a design. Just make a new issue for that new thing? Not sure what you mean about show over pill but i can talk to our designers...

**Comment by infor-mahesh** [comment]
Show over pill I refer to show along with other schedules

**Comment by infor-mahesh** [comment]
As your showing over night shift not on all day but with other schedules right? So in the same way even if it more than 2 days it should show same as over night shift you designed and it should be when the all day row is hidden

**Comment by tmcconechy** [comment]
Sorry not following the remaining issue? Do you have a design of how you think it should look?

**Comment by infor-mahesh** [comment]
ok will create new issue in detail

**Comment by kuldeepsingh1905** [comment]
In the latest IDS changes, overnight event records are divided into two parts and label as 'overnight.' However, in the WFM schedule calendar, overnight shifts are displayed with a '+1.' Please refer to the My WFM Calendar screenshots
The end user might get confused when encountering two different types of overnight shifts, one in the My Week widget and the other in the WFM application calendar window. It would be better to maintain consistency in the design of overnight shifts, preferably using the '+1' notation for both

<img width="606" alt="image" src="https://github.com/infor-design/enterprise/assets/157625099/dff05191-d3f6-4af2-9e8f-4a82737ee057">

**Comment by tmcconechy** [comment]
@kuldeepsingh1905 can you make a new issue as we will have to discuss this. I think that the word is more clear. But maybe we can turn this into a setting.

Will need to schedule more work so probably better to make a new issue if this is truely needed.
