### ISSUE TITLE
Pie/Donut: Changing the popup items should change visible text

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7845]
**Describe the bug**
When selecting a slice in "popup" mode for the legend. It should change the text that is visible

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-popup.html
2. Click on the dropdown then select "open" or any item
3. Expect the text "Response Late (62%)" to change to "Open (26%)"

**Expected behavior**
Should change visible text.

**Additional context**
https://jira.infor.com/browse/IDS-701

**Comment by jbrcna** [comment]
this is now working as expected. moving to done.
verified in https://main-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-popup.html
<img width="788" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/9db0df99-0e20-4111-bdb3-fd845ad30096">
