### ISSUE TITLE
Datagrid: Allow new line in Comments Editor

### ISSUE THREAD

**Issue by manjaripalavancha** [infor-design/enterprise#7848]
**Is your feature request related to a problem or use case? Please describe.**
Soho-datagrid has a problem when one of the cell has data with new line and it has expandable option along with ellipsis and tooltip. If the cell has huge data along with new line the cell first show the ellipsis and when click on the cell, it will expand and shows the entire data. But in the entire data doesn't displaying the new line.

In the example https://main-enterprise.demo.design.infor.com/components/datagrid/example-comments.html show a way of adding a two paragraph piece of text with line feed. May also need https://github.com/infor-design/enterprise/issues/7849

**Describe the solution you'd like**
Soho-datagrid cell expandable option along with tooltip and ellipsis would work better if the cell has an ability show the new line if the data has.

**Describe alternatives you've considered**
As of now we kept the things as it is. Because for huge data ellipsis should be there,  to see the entire data cell should expand then we can see the entire cell data.

**Additional context**
Refer below screenshot to check how the data is displaying in the cell and in the tooltip.
![64275e9b-11bb-4e43-8d67-b6210d2cce89](https://github.com/infor-design/enterprise/assets/104565263/e7605284-6430-4b17-bd8c-fb90cda7ef2b)

Would like to expect that data would show like this if it has new line.
![14023ec5-55bc-4bca-bb42-a85eb6b1248b](https://github.com/infor-design/enterprise/assets/104565263/fe328fca-a59e-4c15-a64c-132c9fdca154)

You can also check the below stackblitz expample that the data set up and how the tooltip looks, how the data with ellipsis and after cell expansion how the data looks.
https://stackblitz.com/edit/ids-quick-start-1651-gozlwx?file=src%2Fapp%2Fdatagrid%2Fdatagrid.component.html,src%2Fapp%2Fdatagrid%2Fdatagrid.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fdatagrid%2Fdatagrid.component.css

**Example data to check:**
Transform yourself and help the company and others to do the same. Develop the visions, strategies,capabilities, products and services that will enable us to satisfy unmet needs and create superior value.

Be humble, intellectually honest and deal with reality constructively. Develop an accurate sense of self-worth based on your strengths, limitations and contributions. Hold yourself and others accountable to these standards.

**Comment by glenlieorillo** [comment]
This is now working as expected in main-enterprise except for the second row (_World-class robust peer-to-peer_) which moves upward upon clicking the cell.


https://github.com/infor-design/enterprise/assets/102151352/76c4b688-af38-42d8-88c7-3d66d50621d0
