### ISSUE TITLE
Donut: Legend highlight issue

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7850]
**Describe the bug**
Legend highlight looks off.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-single-widget.html
2. Click on legend
3. See error

**Expected behavior**
Legend highlights should be rendered properly.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/3d4bb880-cde7-4263-a3d5-60fa2c3c7ea7

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/2b0068f7-02e9-4c98-a597-c527c41f97ac">

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
Also try resizing the page and note the legend jumps out of the widget https://main-enterprise.demo.design.infor.com/components/donut/example-legend-bottom-single-widget.html

![Screenshot 2023-08-23 at 10 12 32 AM](https://github.com/infor-design/enterprise/assets/814283/975b1f8e-7c08-4727-914e-12a8aa5f6824)
