### ISSUE TITLE
ModalButton: cssClass Property Not Prefixing With Space When Adding Class

### ISSUE THREAD

**Issue by yousef-elkaisi** [infor-design/enterprise#7852]
**Describe the bug**
When adding buttons to a modal, we have the option to set a 'cssClass' property on the button which should append a css class to the button's class list. However this is appending the class without prefixing a space, so it is not getting added properly.

![image](https://github.com/infor-design/enterprise/assets/132393590/1243f6df-3818-4010-b4c0-ef8aa5c0e3eb)
![image](https://github.com/infor-design/enterprise/assets/132393590/05696986-e192-4aa8-8e28-8525b958ff1c)

Prefixing the 'cssClass' property with a space fixes the problem:

![image](https://github.com/infor-design/enterprise/assets/132393590/766ac5f9-198b-4220-98d6-d7d5d4656911)
![image](https://github.com/infor-design/enterprise/assets/132393590/6f1de0f5-5111-4665-8399-046b3a3e7147)

**To Reproduce**
Create a modal component and add a button to it. Set the cssClass property on the button to any class (ex: 'hidden'). Observe that the class will not have any effect and that the class name gets appended on to the previous class name.

**Expected behavior**
We should not have to prepend a class name with a space.

**Version**
4.83.0-beta.0

**Platform**
 - Infor Application/Team Name: WFM Supernovas
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 116

**Comment by tmcconechy** [comment]
@ericangeles could be a good one for interns
