### ISSUE TITLE
Soho-datagrid Empty message alignment issue without icon

### ISSUE THREAD

**Issue by manjaripalavancha** [infor-design/enterprise#7854]
**Describe the bug**
Soho-datagrid empty message alignment got disturbed when there is no icon. 

**Steps to reproduce the behavior:**
1. Create Soho-datagrid with no data
3. Give some empty message along with empty message settings height: 'small'/ icon: 'null'
4. Observe the empty message alignment
5. Padding is not set properly for top and bottom

**Expected behavior**
Empty message should align center with/without icon.

**Version**

- ids-enterprise: 15.2 Onwards (Found)

**Screenshots**
![e688ac30-df42-4ad1-93be-4966f2bd490e](https://github.com/infor-design/enterprise/assets/104565263/4277bbf0-22f2-4689-be7e-373a61490c33)
<img width="914" alt="c091210c-4eb9-4176-80ee-dd5e3077ca32" src="https://github.com/infor-design/enterprise/assets/104565263/d577255e-e052-482d-a612-363825dd4937">

**Additional Information:**
Here is the stackblitz link to refer.
https://stackblitz.com/edit/ids-quick-start-1651-9suguu?file=src%2Fapp%2Fdatagrid%2Fdatagrid.component.ts,src%2Fapp%2Fdatagrid%2Fdatagrid.component.html,src%2Fapp%2Fdatagrid%2Fdatagrid.component.css,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html

**Comment by tmcconechy** [comment]
@manjaripalavancha the stackblitz url doesnt work.

I do have some examples that seem to be working ok https://main-enterprise.demo.design.infor.com/components/datagrid/test-empty-message-small.html

Have a look through all the examples with "empty message" in the name https://main-enterprise.demo.design.infor.com/components/datagrid maybe we can reproduce it in an example? If not it may give some ideas

**Comment by manjaripalavancha** [comment]
@tmcconechy , can you please copy the stackblitz link and try to paste it in the browser directly. It might work rather than direct navigation.

The above example which you have provided, It contains frozen columns. So we might not observed the issue.

You can also refere to the below link regarding the issue discussion.

[https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1692770683472?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1692770683472&teamName=IDS%20Enterprise%20Development&channelName=Angular%20Components&createdTime=1692770683472](url)

**Comment by glenlieorillo** [comment]
This is now working as expected in main-enterprise.

![image](https://github.com/infor-design/enterprise/assets/102151352/0fd1593b-f5c1-407b-a815-3a1c49549d8a)
