### ISSUE TITLE
Dropdowns and popupmenues sets wrong height

### ISSUE THREAD

**Issue by Macke105** [infor-design/enterprise#786]
**Describe the bug**
Currently all small type dropdowns and popupmenues (normal)  will get a calculated height applied to the "ul" element with inline styling from a soho script. The height is always to small, resulting in a scrollbar (even if the dropdown/popupmenu only contains one element).

**To Reproduce**
1. Go to http://490-enterprise.demo.design.infor.com/components/dropdown/test-extra-padding-short-fields.html
2. Expand the dropdown
3. Notice the scrollbar

**Expected behavior**
I expect the dropdown/popupmenu to open and NOT contain a scrollbar unless it needs to.

**Screenshots**
![scroll](https://user-images.githubusercontent.com/1390994/45410666-9a890c80-b672-11e8-8fc0-c23b148a05b5.png)

![dropdown](https://user-images.githubusercontent.com/1390994/45410694-abd21900-b672-11e8-8177-15d8042d398e.png)

![popupmenu](https://user-images.githubusercontent.com/1390994/45410682-a4127480-b672-11e8-8926-435a0677eec8.png)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 68.0.3440.106 (Official Build) (64-bit)

**Additional context**
Problem first occurred when upgrading from soho 4.6 to 4.8. Problem is still reproducible in 4.10.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/components/dropdown/test-extra-padding-short-fields.html
I encountered an issue where the dropdown won't open again when you change theme while the dropdown remained open. But I think it's just a minor one.

**Comment by tmcconechy** [comment]
Yes, i would just raise a new issue for that we can label as minor. Seems unrelated but is a good find.

**Comment by brianjuan** [comment]
Thanks @tmcconechy , I will now move this Done, passed QA testing.
