### ISSUE TITLE
Datagrid: Dropdown icon on filter row misaligned

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7860]
**Describe the bug**
The Dropdown icon on filter row misaligned

**To Reproduce**
1. Go to https://4846-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
2. See error on filter row
3. Same on main https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html

**Expected behavior**
Was fixed on https://github.com/infor-design/enterprise/pull/7846

**Additional context**
Needs patch. Just logging this issue for future need.

**Comment by jbrcna** [comment]
working in https://7814-datagrid-design-updates-enterprise.demo.design.infor.com/components/datagrid/example-filter.html?theme=new&mode=light&colors=default. will retest again in main once merged.
<img width="1342" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/15201cb2-8201-41c8-bdb1-d19c079a4c10">

**Comment by jbrcna** [comment]
passed in main
<img width="1484" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/b62ed30f-0323-4f96-a72c-1dcbba7ded6a">
