### ISSUE TITLE
CAP: Text field and 'Action' button are too close

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7863]
**Describe the bug**
Text field and 'Action' button are too close.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-cap-tabs-vertical-scroll.html
2. Click on 'CAP - Tabs Vertical' button
3. Click on 'Test Information'
4. Notice the text field and 'Action' button

**Expected behavior**
Text field and 'Action' button should have space in between.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/63498581-47f1-4772-ba71-9dae602a99e2">

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
I just removed this from the example it serves no purpose there
