### ISSUE TITLE
CAP: Dropdown menu issues

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7865]
**Describe the bug**

**To Reproduce**

**Issue 1: Dropdown icon is moving upon clicking the dropdown menu**
1. Go to https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html
2. Click on 'Open Markup-Based Contextual Action Panel' button
3. Click on any dropdown menu

**Issue 2: Unnecessary dropdown icon**
1. Go to https://main-enterprise.demo.design.infor.com/components/contextualactionpanel/example-markup.html
2. Click on 'Open Markup-Based Contextual Action Panel' button
3. Notice the unnecessary dropdown icon below dropdown menu

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/a6914481-009a-473a-9f21-1bb529a9d5eb

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/e1bad145-ca25-4fb8-a573-11c436f9e482">

**Platform**
 - All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
I had fixed this on a patch branch. The fix didnt seem to make it in to main. So fixed again. Should be ok after all the builds run now
