### ISSUE TITLE
ModuleNav: Update documentation

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise#7869]
Update ModuleNav .readme so that there is full design usage and a unified page structure when component is released. 

[Draft documentation](https://inforwiki.atlassian.net/wiki/spaces/IDX/pages/597609513/Module+nav) to be finalized this week through Jira [IDS-1580](https://jira.infor.com/browse/IDS-1580).

**Comment by tmcconechy** [comment]
@infor-jake is this something we put in the docs when its done? Or do you plan a pull request. Just let me know when its done if you need help adding. (Same with the other issue)
