### ISSUE TITLE
Datagrid exportable: false not working in certain column positions.

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#787]
**Describe the bug**

**To Reproduce**
1. Edit app/views/components/datagrid/example-export-from-button.html so that the columns have several exportable: false for example paste this in the "Define Columns for the Grid." section..
```
      columns.push({ id: 'productId', name: 'Product Id', field: 'productId', formatter: Formatters.Readonly});
      columns.push({ id: 'productName', name: 'Product Name', field: 'productName', formatter: Formatters.Hyperlink});
      columns.push({ id: 'activity', name: 'Activity', field: 'activity', formatter: Formatters.Hyperlink, exportable: false});
      columns.push({ id: 'quantity', name: 'Quantity', field: 'quantity'});
      columns.push({ id: 'price', name: 'Price', field: 'price', formatter: Formatters.Decimal});
      columns.push({ id: 'orderDate', name: 'Order Date', field: 'orderDate', formatter: Formatters.Date, dateFormat: 'M/d/yyyy', exportable: false});
      columns.push({ id: 'status', name: 'Status', field: 'status', formatter: Formatters.Text, exportable: true});
      columns.push({ id: 'action', name: 'Action Item', field: 'action', exportable: false});
      columns.push({ id: 'ex', name: 'Extra', field: 'ex', exportable: true});
```
2. Go to http://localhost:4000/components/datagrid/example-export-from-button.html
3. Click on export
4. Check the excel file and some columns are missing

**Expected behavior**
All columns with exportable: true (or no exportable value) should be exported. All columns with exportable: false should be excluded. No missing data in between 

**Platform**
All

**Additional context**
@dmcodrum

**Comment by dmcodrum** [comment]
Another thing we're seeing - if the first column in a grid is non-exportable, drill down icon for example, the column is still exported and the heading-to-column alignment winds up being one column off in the xls. Works ok in CSV export.

**Comment by brianjuan** [comment]
Does the drilldown column supposed to be exported too in the excel file? 
Right now, the drilldown column is exported in both .xls and .csv files.

**Comment by tmcconechy** [comment]
I would say this is fine, because the user could put "exportable: false" on that column if they dont want it in the export. We cant control this because its part of the column definition.

**Comment by brianjuan** [comment]
Thanks @tmcconechy , now moving this to Done, passed QA across all browsers.
