### ISSUE TITLE
ModuleNav: Update example .index

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise#7870]
Update the documentation copy within the [main Module Nav demo](https://main-enterprise.demo.design.infor.com/components/module-nav/example-index.html) to reflect the design intent.

![image](https://github.com/infor-design/enterprise/assets/117312557/c822eb06-cd42-4869-adaa-3f8ec278241c)

**Comment by tmcconechy** [comment]
Is this ready? Should i do it? Or you?

**Comment by infor-jake** [comment]
I can do a PR when ready!
