### ISSUE TITLE
BarStacked: Uneven legend space

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7874]
**Describe the bug**
Legend could have equal space between the top and bottom of the legend and could use space more effeciently

1. Go to https://main-enterprise.demo.design.infor.com/components/bar-stacked/example-stacked-100.html
2. Compare to https://4800-enterprise.demo.design.infor.com/components/bar-stacked/example-stacked-100.html
4. See Legend spacing top and bottom

**Additional context**
https://github.com/infor-design/enterprise/pull/7844#pullrequestreview-1602721534

**Comment by tjamesallen15** [comment]
@tmcconechy the 2nd link is not accessible anymore.

**Comment by tmcconechy** [comment]
updated now

**Comment by glenlieorillo** [comment]
Passed.

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/dcef146e-b14d-450b-9996-16a36191f249">
