### ISSUE TITLE
Datagrid: Vertical scroll event is not triggered when list styling is enabled

### ISSUE THREAD

**Issue by informanisha** [infor-design/enterprise#7879]
**Describe the bug**
Vertical scroll event is not getting triggered when we enable list styling on datagrid (isList = true)

**To Reproduce**
On a datagrid component create gridOptions with isList=true and declare the event (verticalScroll)

For example: use the below example code but declare and use gridOptions with isList = true
 https://github.com/infor-design/enterprise-ng/blob/main/src/app/datagrid/datagrid-vertical-scroll-to-end.demo.html
 https://github.com/infor-design/enterprise-ng/blob/main/src/app/datagrid/datagrid-vertical-scroll-to-end.demo.ts 

	<div #target
		soho-datagrid
		[columns]="this.EDITORS_COLUMNS"
		[data]="this.data"
		*ngIf="gridOptions"
		[gridOptions]="gridOptions"
		(verticalScroll)="onVerticalScroll($event)"></div>

                this.gridOptions = {
			columns: this.EDITORS_COLUMNS,
			selectable: "single",
			clickToSelect: false,
			idProperty: "date",
			stretchColumn: "last",
			editable: false,
			isList: true,
			filterable: false,
			searchable: true,
			paging: false,
			showDirty: false,
			emptyMessage: this.emptyMessage,
		};

1. Create a datagrid component
2. Declare gridOptions with isList = true
3. Declare a verticalScroll event
4. Debug the component on the browser 
5. See that the verticalScroll event is not triggered

**Expected behavior**
Vertical scroll event should trigger when list styling is enabled.

**Version**

- ids-enterprise: v4.80.3

**Screenshots**
The event is triggered when list styling is not enabled (isList:false)
<img width="437" alt="image" src="https://github.com/infor-design/enterprise/assets/143688935/0412886f-28b5-4e1b-a981-b4b0fe9ddc83">
The event is not triggered when list styling is enabled (isList:true)
<img width="559" alt="image" src="https://github.com/infor-design/enterprise/assets/143688935/c83ee919-60bd-4e9c-93a0-3a4ad9d3b802">

**Platform**
 - Browser Name: All browsers

**Comment by tmcconechy** [comment]
FYI this does work on the enterprise side on testing. Possibly some lifecycle issue?

**Comment by yohannahbautista** [comment]
@tmcconechy @ericangeles 
Hello, I've followed the steps on this issue and it looks like vertical scroll does work. The only scenario where it doesn't is if i don't use the gridOptions and try `[isList]="true"` on the div instead, so will look into that. But using gridOptions and adding `isList: true` like its mentioned works on my end.

**Comment by ericangeles** [comment]
Great! Thanks, @yohannahbautista 👍🏼

**Comment by yohannahbautista** [comment]
Here is an example stackblitz for reference: https://stackblitz.com/edit/ids-quick-start-1681-yhm8db?file=src%2Fapp%2Fapp.component.ts
