### ISSUE TITLE
Accordion is inheriting CSS styles from module nav

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#7884]
**Describe the bug**
Accordion width is set to 40px when menu is in collapsed state. There are also some margins being changed. 

**To Reproduce**

1. Checkout  ids-ng 15.4.11
2. Go to http://localhost:4200/ids-enterprise-ng-demo/accordion
3. Collapse menu
4. See issue

**Expected behavior**
Module nav styles should not get inherited by accordion control

**Version**
4.84.6

**Screenshots**
<img width="536" alt="image" src="https://github.com/infor-design/enterprise/assets/1056684/b1871a78-aa8b-4b3b-a3aa-75da87bac826">

**Platform**
- Windows
- Chrome

**Comment by glenlieorillo** [comment]
This is now working as expected in main-enterprise.


https://github.com/infor-design/enterprise/assets/102151352/5e7d21ed-d261-4da2-9c66-7f7039746b20
