### ISSUE TITLE
TimePicker: control does not enable correctly after being disable

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#7887]
**Describe the bug**
If you disable the control and then enable it again the icon fails to open the timepicker.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to '[...](https://main-enterprise.demo.design.infor.com/components/timepicker/example-index.html)'
2. Disable via code '$('#timepicker-id-1').disable()'
3. Enable via code '$('#timepicker-id-1').enable()
4. Click on the icon to open the time picker 

**Expected behaviour**
time picker works once it has been re-enabled.

**Version**
- ids-enterprise: [e.g. 4.86.0]

**Platform**
 - Infor Application/Team Name: Pathway
 - OS Version: Windows 10
 - Browser Name: chrome, edge

**Additional context**
Also enabled and disabled the time picker using the API and the same result

'$('#timepicker-id-1').data('timepicker').disable()'
'$('#timepicker-id-1').data('timepicker').enable()'

**Comment by marknolaninfor** [comment]
https://github.com/infor-design/enterprise/commit/b88c6076305bade5cb8e66873debc11801dfe11d#diff-bc4d59504a1e1d5f9f041aab0387cfe796e74e0ca4da9b2fa55c721eef38fb0d

the disable method adds a property to the trigger, but the enable method does not remove it.

this.trigger.prop('disabled', true);

**Comment by marknolaninfor** [comment]
@tmcconechy 

Can this be corrected ASAP, as we can no longer conditionally enable and disable time pickers as #7569 broke the control?

**Comment by tmcconechy** [comment]
Ok @marknolaninfor i think i fixed it on the attached PR. I can include this in 4.87 after testing happens on the PR next week.
Note you could do a workaround where you find the `.trigger' button and remove the disabled attr if you need to https://github.com/infor-design/enterprise/pull/7914/files#diff-69b5cc6d5460562add956bff04934d17d5c1f0d2fbd00ab63671fde098d886b9R53
