### ISSUE TITLE
Column: Chart title is not in full text

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7889]
**Describe the bug**
Chart title is not in full text.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/column/example-rotate.html
2. Notice the chart title, it should be in full text

**Also here:**

- https://main-enterprise.demo.design.infor.com/components/column-grouped/example-axis-labels.html
- https://main-enterprise.demo.design.infor.com/components/column-grouped/example-column-grouped-with-line-combined-hide-dots.html
- https://main-enterprise.demo.design.infor.com/components/column-grouped/example-column-grouped-with-line-combined.html

**Expected behavior**
Chart title should be in full text.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/dd813e4b-bc4f-4e2e-bff9-333311e1a83e">

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/7a9a2e7b-b52c-46c1-bd6d-5111825495dd">

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
Lets just change this to "Column Chart"
