### ISSUE TITLE
TargetedAchievement: Issue showing yellow component color

### ISSUE THREAD

**Issue by paripireddymanikrishna** [infor-design/enterprise#7891]
Describe the bug
Instead for showing yellow color it showing different color
<img width="293" alt="image" src="https://github.com/infor-design/enterprise/assets/144098110/2bc6afa6-c0d0-4ec4-ad15-aa010a1e4af6">

and if try to apply alert class for this component then it showing like below image and count is visible on top of bar but not inside the bar and count is also having same color of bar color

To Reproduce
use color class is "warning"

<img width="305" alt="image" src="https://github.com/infor-design/enterprise/assets/144098110/110d348e-3f4a-4649-9f49-0782757d199b">

**Comment by tmcconechy** [comment]
We have an alert color one here:
https://main-enterprise.demo.design.infor.com/components/targeted-achievement/example-links-icons.html

DO you want both a yellow and orange alert? I think the orange can work but we did have a bug with alert colors and reverted the orange one to have both orange and yellow. https://main-enterprise.demo.design.infor.com/components/colors/example-index.html

So want to clarify you want an alert thats yellow?
