### ISSUE TITLE
FileUploadAdvanced: Ability to resize responsively

### ISSUE THREAD

**Issue by paripireddymanikrishna** [infor-design/enterprise#7892]
**Describe the bug**
unable to resize the attachment component for both multi attachment and attachment component and dropdown component also

**To Reproduce**
<img width="296" alt="image" src="https://github.com/infor-design/enterprise/assets/144098110/9f8aaba2-3145-4692-8c8a-9f5f7e99167f"> 

<img width="298" alt="image" src="https://github.com/infor-design/enterprise/assets/144098110/4ed5f7c6-16f4-4893-9418-509961a4e516">

**Possible Specs (TJM)**

- by default has 300px width like an input field
- in responsive forms will take the save of the responsive column
- other fixed sizes?
- may have issues with very small sized and text wrapping so may need a changing height as well

**Comment by tmcconechy** [comment]
@paripireddymanikrishna do you mean you want it to be responsive to the same size of fields? or want to resize it as a user or something else? the issue is a bit unclear. Also i changed it to file upload which is the name of the component

**Comment by tmcconechy** [comment]
@paripireddymanikrishna tested this on https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html and it seems to be now the size of the page. Does that work for you?

**Comment by paripireddymanikrishna** [comment]
@tmcconechy when we are using this component in widgets then size is different with another components like input field and it is taking more time to upload file

**Comment by tmcconechy** [comment]
@paripireddymanikrishna not sure whats special about your case when it works on https://main-enterprise.demo.design.infor.com/components/fileupload-advanced/example-index.html

Can you try to do it the same way and see if it fixes it? Or provide a reduced test case / stackblitz (Template: https://stackblitz.com/edit/ids-quick-start-1651?file=src%2Fapp%2Fapp.component.ts)

As for it being slow. We dont have control over how you upload it but do note you probably want to use the send method like this example https://github.com/infor-design/enterprise/blob/main/app/views/components/fileupload-advanced/example-send.html our default `sendFileToServer` has a timer in it to slow it down for demo app. So maybe you didnt implement send properly

**Comment by paripireddymanikrishna** [comment]
@tmcconechy I tried same as example given in IDS site and not added any custom CSS also. I tried in different versions as well but issue is same and I will send you credentials and details if you want

**Comment by tmcconechy** [comment]
We usually insist on a reduced test case for looking at issues https://www.browserstack.com/guide/test-case-reduction-and-techniques

So could you make a small example that just shows the issue. You can either put the relevent code in a zip.
Or use our stackblitz templates:

NG: https://stackblitz.com/edit/ids-quick-start-1711?file=src%2Fapp%2Fapp.component.ts
Enterprise: https://stackblitz.com/edit/ids-enterprise-4991?file=index.js

Try perhaps to focus on what your passing in settings, any custom css or special placement or any special angular tags or something?

**Comment by paripireddymanikrishna** [comment]
here is runnable example for above issue and still issue is reproducing here that is while uploading files using this component is taking more time.

https://stackblitz.com/edit/ids-quick-start-1711-1pyfgr?file=src%2Fapp%2Fapp.component.html

**Comment by tmcconechy** [comment]
@paripireddymanikrishna I cant find the code in this example but there is a thing about the component...

By default if you dont implement the send function it will slow the upload down and just do a fake upload for demonstration purposes. All you need to do is implement this function and do your own logic and it will bypass this logic.

https://github.com/infor-design/enterprise/blob/main/app/views/components/fileupload-advanced/example-send.html#L15

I dont get what you mean about the resize part of the issue but from what i see doing that should solve the issue

**Comment by tmcconechy** [comment]
@paripireddymanikrishna does adding the method fix the slowness problem?
Can you elaborate on the steps to reproduce the resize issue please? Should this be closed?

**Comment by paripireddymanikrishna** [comment]
Hi @tmcconechy , No it is still slow.
I am adding here example https://stackblitz.com/edit/ids-quick-start-1711-qezkdj?file=src%2Fapp%2Fapp.component.html

**Comment by paripireddymanikrishna** [comment]
when we select any large size file it is taking time and in above just mentioned sample component and it same in widget as well

**Comment by tmcconechy** [comment]
@paripireddymanikrishna where in that example did you implement the send function https://github.com/infor-design/enterprise/blob/main/app/views/components/fileupload-advanced/example-send.html#L15

Once you implement that you bypass the default "slow it down for visual" behavior and actually implement your logic to send it to the backend.

**Comment by paripireddymanikrishna** [comment]
Hi @tmcconechy the soho-fileupload-advanced component itself taking more time while selecting file for reference I am attaching the video link

https://inforonline-my.sharepoint.com/:v:/g/personal/manikrishna_paripireddy_infor_com/EbPOIonQoCZOtev9UdEJzF8Brik0oqyiSiqv_pEFWtMU7A?e=WLgsSD 

and this is stackblitz link ]
https://stackblitz.com/edit/ids-quick-start-1711-qezkdj?file=src%2Fapp%2Fapp.component.html

**Comment by tmcconechy** [comment]
Will fix the responsive behaviour if we have time. But for the slow issue i think if you implement the send function it will work.
Also could try the new web component version. It doesnt have the send issue

**Comment by paripireddymanikrishna** [comment]
@tmcconechy any idea in which fix version this available so that I will update in Jira ticket accordingly

**Comment by tmcconechy** [comment]
@paripireddymanikrishna i can try and add this to release 4.96.0 which would be early June.
