### ISSUE TITLE
TextArea: NaN issue

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7893]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/textarea/example-autogrow.html
2. Type any text
3. See error
4. Notice that the number is NaN

**Expected behavior**
should be a number/digit

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="815" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1dbac1c0-e465-47a7-a829-9f8e03ab934a">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
@yohannahbautista can you take a look? might be due to latest fixes

**Comment by glenlieorillo** [comment]
Hello @tmcconechy

This bug also exists in CAP. Thanks!

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/a0d732ec-f086-48b2-bf60-6300e3cadf56">

**Comment by tmcconechy** [comment]
Note: Fix added to 4.87.0 (Beta and Final)

**Comment by jbrcna** [comment]
fix applied in main and beta. thank you
<img width="827" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/4fa48010-8d68-450c-b3de-a2c9a27204f7">

<img width="857" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/541b6e64-5d17-42f9-a7c2-ee808caec84a">

CAP is fixed as well
<img width="1083" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1a5b5207-91ee-477b-af94-cb87de3438a9">
