### ISSUE TITLE
Soho Circlepager glitch

### ISSUE THREAD

**Issue by ajayponnapati** [infor-design/enterprise#7894]
**Describe the bug**
I am using soho-circlepager component with the following attribute `[slidesToShow]="slides.length"`.  I want to show as many slides as I can on one page but I am noticing a glitch.

**To Reproduce**
You can reproduce it on the html page link attached below by dragging inspection tools to increase/decrease width for soho-circlepager (slowly).

1. Go to https://main-enterprise.demo.design.infor.com/components/circlepager/example-index.html
2. Open inspection tools.
3.Resize the inspection tools by dragging so as to change the available width for circlepager.
4. You ccan see flickering on resize

**Expected behavior**
There should be no glitch or smoother resize

**Version**
- ids-enterprise: v15.1.2

**Comment by tmcconechy** [comment]
Ideas to try maybe on resize https://github.com/infor-design/enterprise/blob/main/src/components/circlepager/circlepager.js#L771

1. Hide the elements and show them again during resize 
2. Add animation
3. Debounce the resize
