### ISSUE TITLE
Card/Widget: Height greater than header + content heights combined

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#7896]
**Describe the bug**
The height of a widget is greater than its header and content elements combined. This doesn't seem right, as it leads to a noticeable gap with full content.  

**To Reproduce**
1. https://design.infor.com/code/ids-enterprise/latest/demo/components/cards/example-workspace-widgets?theme=uplift&variant=light
2. Inspect the widget element, and its header and content elements
3. Widget height is 373px. Header is 48px, content 318px (366px combined). Means there is 7px of dead space, see screenshot below. 
4. For a double height widget, it's the other way around, header + content heights exceed widget height

**Expected behavior**
Height of a widget should be header + content.

**Version**
- ids-enterprise: latest (4.86.0)

**Screenshots**
`.widget-content` colored red
![image](https://github.com/infor-design/enterprise/assets/1101770/a9630977-e0df-42fc-af4e-385f3be9ba47)

**Platform**
 - Infor Application/Team Name: OS Portal

**Additional context**
We're currently using v4.85.0, where same issue can be seen (but widget is 368px tall, so only 2px dead space). I think the new widget height is supposed to be 368px, so content should be 320px?

**Comment by tmcconechy** [comment]
Fixed on https://github.com/infor-design/enterprise/pull/7902 but will like to run this through full round of QA. Do have a look tho. Thanks @volante007

**Comment by volante007** [comment]
Thanks Tim!

I think some change is required for double-height as well

”For a double height widget, it's the other way around, header + content heights exceed widget height”

**Comment by tmcconechy** [comment]
@volante007 i added a fix and noted it on the PR it needed a small adjustment
