### ISSUE TITLE
Radio: Selected radio button dot is not 100% centered

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#7899]
**Describe the bug**
We have one observation regarding the selected radio button: the white circle is not centered.

**To Reproduce**

1. Go to radio button's example.
2. select any radio button and check the white circle placement. It is not center aligned.

**Expected behavior**
In selected radio button, white circle should be center aligned. 

**Version**

- ids-enterprise: latest ID version.

**Screenshots**
![R1](https://github.com/infor-design/enterprise/assets/42198413/b5bb777c-8c62-4252-9a1a-81b6088fed11)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
verified in https://main-enterprise.demo.design.infor.com/components/radios/example-index.html
<img width="954" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/eb105327-431e-4c8a-879d-bfbe372dbbd1">
