### ISSUE TITLE
Lookup: Results not inline with Header title

### ISSUE THREAD

**Issue by charantejpola** [infor-design/enterprise#7905]
**Describe the bug**
After upgrading to the latest version [ids-enterprise-ng@16.6.1](mailto:ids-enterprise-ng@16.6.1) I observed this issue in soho-lookup
where the results are not inline with the header. The same can be seen in the enterprise design page example as well.
[IDS Enterprise (infor.com)](https://latest-enterprise.demo.design.infor.com/components/lookup/example-custom-toolbar.html).

**To Reproduce**
1. Create a lookup with proper dataset.
2. Open the lookup and observe the results value beside header title.
3. Alignment got disturbed in comparison with previous version (15.0.2) to latest (16.6.1 observed in this version) 

**Expected behavior**
The results should align with header title

**Version**
- ids-enterprise: 16.6.1 onwards
**Screenshots**
![0490b0fa-c174-42f9-903f-4dad1246356a](https://github.com/infor-design/enterprise/assets/144307117/b44815a7-b59a-46b0-8044-6eabe38919e1)

**Additional context**
Can refer to below link to check.
https://latest-enterprise.demo.design.infor.com/components/lookup/example-custom-toolbar.html

**Comment by tmcconechy** [comment]
Noting patch included in 4.87
