### ISSUE TITLE
WeekView: Date format of the component over tenant is not consistent

### ISSUE THREAD

**Issue by infor-mahesh** [infor-design/enterprise#7906]
**Describe the bug**
when we validate on local week view shows like this
<img width="588" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/dedf410d-8c71-45c6-af3f-5e2aae45c640">
with name of the weeks,

but if we deploy on tenant and see 
<img width="650" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/720fcc79-1629-46cd-a98f-db24f787d7b9">
then the name of the week are not available

**To Reproduce**

1. Go to tenant and try to add week view 
2. it shows the week with no week day names

**Expected behavior**
It should show how the component looks in design.infor.com but its different then that, and for reference it is working in local but not on tenant

**Comment by tmcconechy** [comment]
We require a reduced test case for info on that see https://www.browserstack.com/guide/test-case-reduction-and-techniques#:~:text=Test%20Case%20Reduction%2C%20as%20the,suites%20for%20the%20Development%20team.

We dont have a way to "log in to tenant" for issues and fix them. 

But I would assume they would be on different versions. So check the versions they are on (by checking on the html tag in the markup). And make sure they are the same. If the one that does not work is newer then we may have a bug. Which you can try to reproduce in the examples in this repo.

**Comment by infor-mahesh** [comment]
Hi @tmcconechy , we can give tenant information over teams for validation to check whats the issue, will it be fine?

**Comment by tmcconechy** [comment]
@infor-mahesh we need you to do the work as well, help use help you. Did you try any of my suggestions in the last comment?The most probable causes i can think of are either:

1. this server is in a different timezone
2. its a different version of code(s) -> see this on the <html> tag and compare
3. see if you can make a reduced test case

 If you tried all this and still cant reproduce the issue with a simplified example. I can go in and take a look and see. But it will be very unlikely i could solve the issue. But maybe i see something. So please try all the above first and let me know.

**Comment by infor-mahesh** [comment]
Hi @tmcconechy ,
the days are working fine on locale setup and no issue and errors in console, even on deployment no errors on console, working fine as expected in locale but not in tenant.

**Comment by tmcconechy** [comment]
ok what about?

1. is the server that is not working in a different timezone?
2. did you check the versions? its a different version of code(s) -> see this on the tag and compare
3. did you see if you can make a reduced test case
4. did you verify the the locale set is set `Soho.Locale.currentLocale`.
~5. Did you check for any errors in the console?~ No
5. Did you note what difference the tenant is?
