### ISSUE TITLE
Validation: Add setting to not wrap the validation message

### ISSUE THREAD

**Issue by charantejpola** [infor-design/enterprise#7909]
**Describe the bug**
The alert message shown for soho-lookup validation gets overlapped with other fields if the alert message has width greater than the input.

**To Reproduce**
1. Add a custom validation which has an alert message like "Value is not found in the list" for a lookup.
2. Click on the lookup and select a value.
3. Make changes to the value selected in the input such that the value does not exist in the list of values.
4. Then we trigger a custom validation message saying, "Value is not found in the list".

**Expected behavior**
The expected behavior would be if the alert message exceeds the length of the soho-lookup field it should a ellipsis to the end of the text and adjust the validation message in the given width and add a soho-tooltip, on which if we hover it should show the complete text.

**Version**

- ids-enterprise-15.2.8

**Screenshots**
Observed behavior:

![92c03836-8cf0-4c72-8dbe-3e729721aef7](https://github.com/infor-design/enterprise/assets/144307117/ac14d42d-f548-465f-83b6-f43b60144298)

Expected:

![6a8ebe59-73e8-411e-b4fb-819f8bf0d938](https://github.com/infor-design/enterprise/assets/144307117/f69309d3-0ac9-4a9d-8558-6920dce1a678)

**Additional context**
Also, for accordion labels the soho-tooltip is being handled effectively we can see if the content exceeds the given width it automatically adjusts adds the ellipsis and tool-tip

**Comment by tmcconechy** [comment]
For clarification this would be a non default setting to not wrap the label we "could" add if accepted. It is reccomended to let the fields move down like https://main-enterprise.demo.design.infor.com/components/validation/example-index.html

@charantejpola 
Can you add a simple form example to this issue that mimics the use case? not sure how you make the forms work the way your doing it. Our example forms do not work this way. This will speed up the issue

**Comment by charantejpola** [comment]
Sorry for my delayed response. Here is the stackblitz link for the issue to be checked.
[https://stackblitz.com/edit/ids-quick-start-1759-vgpl9p?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.css](url)
Actually according to the requirement the fields below should not move down. 
Steps to do in the above stackblitz.
1.Open the stackblitz in a new window(or drag the preview such) where we can see four fields in a row.
<img width="641" alt="image" src="https://github.com/infor-design/enterprise/assets/144307117/87822b65-6bd1-4d4f-9b90-93ceb9265fc0">
2. Now enter any random value in first lookup "Business type" then we can see the custom alert and also the fields getting moved down which doesnt provide a good user experience. As it disturbs the whole layout
3. The expectation would be something like in the screenshots attached in the description where the alert should be in a single line with ellipsis.

**Comment by tmcconechy** [comment]
@charantejpola that link doesnt work to stackblitz
