### ISSUE TITLE
Toolbar-flex: overlapping icons in mobile

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7911]
**Describe the bug**
when using mobile view,  icons were overlapping in searchfield

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-search-before-buttonset.html?
2. Switch to mobile view or open in mobile browser
3. Click and type on searchfield

**Expected behavior**
icons should be properly aligned

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="252" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ef829f66-73e9-4a16-adb5-cfb7d88c4f45">

**Platform**
mobile

**Additional context**
check also in 
https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-searchfield-collapsible.html
https://main-enterprise.demo.design.infor.com/components/toolbar-flex/example-toolbar-flex-with-searchfield-in-center.html

**Comment by tmcconechy** [comment]
@yohannahbautista did you fix this already?

**Comment by yohannahbautista** [comment]
> @yohannahbautista did you fix this already?

@tmcconechy Hello, yes, it should be fixed in this PR: https://github.com/infor-design/enterprise/pull/7895
