### ISSUE TITLE
Datepicker: Selecting a date with time closes the picker

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#7916]
**Describe the bug**
In our application, we are using a date picker with time. When a user clicks on the calendar icon to change the date and time, a popup opens. However, when the user selects a date, it automatically closes without allowing them to select a time. To select a time, the user needs to click on the calendar icon again. Ideally, after selecting both date and time, the user should click on the 'apply' button, and then we should close the popup.

**To Reproduce**

1. Go to (https://latest-enterprise.demo.design.infor.com/components/datepicker/example-timeformat.html).
2. Click on Calendar icon to change the date.
3. Select date, calendar popup got closed automatically without selecting time.

**Expected behavior**
Ideally, after selecting both date and time, the user should click on the 'apply' button, and then we should close the popup.

**Version**

- ids-enterprise: latest IDS version

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
As noted (on ms teams). This was a decision we made but maybe not the best one. Perhaps we require the "apply" when time is turned on so you can select in any order.

**Comment by tmcconechy** [comment]
Make a setting `enforceApplyButton` for this. (Suggestion)
