### ISSUE TITLE
Tabs: Design QA Round 4

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#7922]
**Describe the bug**

One more round of QA to fix https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=1029-1967&mode=design&t=YeLzMP16lxrXwxKu-0

**To Reproduce**

See issues on https://www.figma.com/file/gRpli2TgQ3scLE6GF4e2Hz/Alabaster-Clean-up?type=design&node-id=1029-1967&mode=design&t=YeLzMP16lxrXwxKu-0

**Additional context**
https://jira.infor.com/browse/IDS-1415

**Comment by tjamesallen15** [comment]
Give me this one on next sprint @tmcconechy. 😄

**Comment by tmcconechy** [comment]
Assigning ahead of next sprint
