### ISSUE TITLE
Datagrid: Issue while fixing the width of a grid's column in a modal

### ISSUE THREAD

**Issue by venugopal1993** [infor-design/enterprise#7923]
**Describe the bug**
Unable to set a fixed width to a grid's column inside a modal screen. As there is a huge text in a column, we would like set fixed width and show ellipsis instead of a horizontal scrollbar on the grid.

**To Reproduce**
Create a modal screen through contextual action panel and in the modal component, place a datagrid. Add one of the columns as below. Ensure that there is one record in the grid with large data for below column.
![image](https://github.com/infor-design/enterprise/assets/16607906/ca36e14f-aaad-443e-8865-2115098766b1)

1. Open the 'modal screen'
2. Check the width of the column

**Expected behavior**
The width of the column is fixed to 50px.

**Version**
v4.85.0

**Screenshots**

<img width="344" alt="Screenshot 2023-09-08 200126" src="https://github.com/infor-design/enterprise/assets/16607906/94e55b06-5252-4499-8125-a05a30cf38de">

<img width="453" alt="image" src="https://github.com/infor-design/enterprise/assets/16607906/90b543eb-43e2-4974-8343-feef92664565">

**Platform**
 - Infor Application/Team Name: Infor Homepages
 - Device: PC
 - OS Version: Windows 11
 - Browser Name: All
 - Browser Version: -

**Additional context**

**Comment by misaelmv1995** [comment]
Hi, additional to this ticket, we are unsure if the textOverflow: 'ellipsis' is working while in a modal since the columns are not resizing to less than the label width.

**Comment by tmcconechy** [comment]
@misaelmv1995 modals are tricky for datagrids (probably should be avoided from a complexity standpoint). You might have to set the width on datagrid parent in the modal to get it to get a fixed size.
