### ISSUE TITLE
Weekview: footer-cell not centered in classic

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7926]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/week-view/example-stacked.html?theme=classic&mode=dark&colors=default
2. Ensure you are in classic theme
3. See error
4. Notice that the footer cell is not centered

**Expected behavior**
should be centered

**Version**

- ids-enterprise: v4.87.0-beta0

**Screenshots**

<img width="1636" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ad760a02-2745-44f7-9a20-6574416530f1">

<img width="1672" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/3a2713fa-3ff7-4cb8-beee-3698431907df">

<img width="152" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/b861ff58-79b3-4ff9-a0cb-ec51a56123b2">

**Platform**
Web & Mobile browser

**Additional context**

**Comment by tmcconechy** [comment]
@ericangeles maybe good new one for interns
