### ISSUE TITLE
Custom hotkeys not firing when focus is on dropdowns or popups

### ISSUE THREAD

**Issue by jake-harrington** [infor-design/enterprise#793]
**Describe the bug**
We have several hotkeys 

**To Reproduce**
1. Go to the attached page 
[example-groups.zip](https://github.com/infor-design/enterprise/files/2376665/example-groups.zip)

2. Tab to the dropdown
3. Try to press Ctrl + Shift + O (one of the hotkeys we're trying to use)
4. Notice no keydown event was logged and the paragraph text wasn't updated with the current keycode

**Expected behavior**
We have lots of hotkeys, some general and some that show specific information about the focused field for helpful information for a separate wysiwyg designer product for customers to customize our forms. Ctrl+Shift+O is one hotkey, but we have many where some combination of modifier keys are used but it looks like if Ctrl is held at all the dropdown will ignore the key press, which means our key handlers never get called. Our expected behavior that all fields shouldn't interfere with key strokes that aren't directly handled by the control. We also are expecting the popup menu to behave similarly but it seems Ctrl hotkeys are also canceled there if you try to use Ctrl+Shift+O with the dropdown open.

**Platform**
-Enterprise 4.10.x - built from source

**Additional context**
Our hotkeys can be set by the users too so we don't have full control over what hotkeys are used either.

**Comment by tmcconechy** [comment]
We added a setting for you to do this since we cant change this easily. The idea is you listen to this call back and do your keystroke there. No strokes will be ignored.

So just wire up this call back rather than using the key events?

https://github.com/infor-design/enterprise/blob/master/app/views/components/dropdown/test-allow-custom-keystroke.html#L33

**Comment by jake-harrington** [comment]
Ok I tried that out but I'm still seeing the same issue where it doesn't fire if Ctrl is held.

**Comment by tmcconechy** [comment]
OK, will have to take a look, maybe its filtered out or the call is in the wrong place.

**Comment by brianjuan** [comment]
http://4110-beta0-enterprise.demo.design.infor.com/components/dropdown/test-onkeydown-ctrlkey.html
Passed QA testing across all browsers.
