### ISSUE TITLE
Homepage: Pie chart overlaps the bar chart

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7932]
**Describe the bug**
The pie chart overlaps the bar chart.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/homepage/example-add-widget.html
2. Click on 'Remove Business Insight' button
3. Click on 'Append Business Insight' button
4. Try to click the button multiple times to see the error
5. Notice the pie chart is appearing/overlapping the bar chart

**Expected behavior**
Pie chart should render properly upon clicking the 'Remove/Append Business Insight' button

**Version**

- ids-enterprise: 4.87.0-beta.0

**Screenshots**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/ca2bcd2a-dd38-4d73-8426-89ecc79557d3">

https://github.com/infor-design/enterprise/assets/102151352/0cf30c97-abaa-4ac2-a25b-7b0d771116f6

**Platform**
 - All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
@glenlieorillo i cant seem to reproduce this. Can you look at the steps again? Does the size of the window matter?

**Comment by glenlieorillo** [comment]
@tmcconechy try to click the button multiple times faster and focus on the bar chart. I recorded the screen again in slo-mo so you can notice the bug:


https://github.com/infor-design/enterprise/assets/102151352/d9bfa304-bb47-4b85-9c83-404f3537b750

I also tried in responsive view and the bug exists:


https://github.com/infor-design/enterprise/assets/102151352/8af9a3a1-0e77-4da5-8946-dec05e63aab9
