### ISSUE TITLE
Donut chart: Require a title over Legends

### ISSUE THREAD

**Issue by infor-mahesh** [infor-design/enterprise#7933]
**Is your feature request related to a problem or use case? Please describe.**
Design need to acheive
<img width="365" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/2e1af4da-fa3b-42f0-b1a8-c561610c4a3d">

What we are getting:
<img width="431" alt="image" src="https://github.com/infor-design/enterprise/assets/139130328/c51a16de-2b55-4bd8-8290-e1cb41a6831b">

**Describe the solution you'd like**
Require something so that we can add title for the legends

Reference component:
https://design.infor.com/code/ids-enterprise/latest/demo/components/donut/example-index?theme=uplift&variant=light

**Comment by tmcconechy** [comment]
Could you just put a label on top of the chart? Why does it need to be on the legend exactly? Also consider other charts donut is not always the best fit

**Comment by infor-mahesh** [comment]
Hi @tmcconechy ,
Requirements specify to use donut chart

**Comment by tmcconechy** [comment]
@infor-mahesh we think the label should be on the widget title area. Would that not work?

**Comment by infor-mahesh** [comment]
Hi @tmcconechy , as per the requirements we need title above legends, so it is design specific requirement. can i know the status of this? any update

**Comment by tmcconechy** [comment]
Last grooming call we discussed with design and that was the suggestion. So no action being done right now. Can explain why that would be important to put it in that specific location when the widget can have a label/title?

**Comment by tmcconechy** [comment]
This now has a design i thought it was closed. So ready to implement now: https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/branch/QIgqnGnfDIBj5v06zEAqMy/IDS-(SoHo)-Component-Library-v4.8?type=design&node-id=44454-35748&mode=design&t=WxKizgMw6X7sYdn9-0

**Comment by infor-mahesh** [comment]
ok, is it available now? if so what attribute/field need to be added to acheive this

**Comment by tmcconechy** [comment]
It is not yet available, only now approved and with a new design to be implemented.

**Comment by infor-mahesh** [comment]
Hello @tmcconechy , is this issue resolved and at which sdk release we can expect this?

**Comment by tmcconechy** [comment]
Hi @infor-mahesh 

This fix is in 4.93.0 (NG 17.5.9) of the components but you will have to ask the SDK team which version this would be in there. I don't know that.

**Comment by informanisha** [comment]
Hi @tmcconechy ,

What is the fix provided for this issue. How do we add the legends title?
