### ISSUE TITLE
Form: File Upload/short size field icons focus state looks off

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7937]
**Describe the bug**
File Upload/short size field icons focus state looks off.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/form/example-compact-mode.html
2. Hover over folder icon under File Upload (Compact Mode)/Short Size
3. See error

**Expected behavior**
Icons focus state should not look to overlap with the field

**Version**

- ids-enterprise: 4.87.0-beta.0

**Screenshots**

_File Upload_
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/ba16e46e-d45e-4ce2-8e78-af619e64a2b0">

_Short Size_
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/cd936797-3855-4d53-a605-93e00238aa31">

**Platform**
 - All major browsers

**Additional context**

**Comment by tmcconechy** [comment]
@ericangeles maybe a good one for interns
