### ISSUE TITLE
Dropdown: Revise component lifecycle to be less dependent on "setTimeout()"

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#794]
**Is your feature request related to a problem? Please describe.**
The Dropdown component has some issues related to the use of `setTimeout` that sometimes prevents reliable e2e testing from occurring.

**Describe the solution you'd like**
Replace the usage of some of these timeouts with:
* callbacks stored for a specific duration against the renderLoop system (for situations like [this one](https://github.com/infor-design/enterprise/blob/master/src/components/dropdown/dropdown.js#L340) where we are waiting to set event handlers for the purposes of preventing the menu to not close as soon as it’s opened).
* promise-based?

Also, will need to double check the commented out portions of [these Dropdown e2e tests](https://github.com/infor-design/enterprise/blob/4.10.x/test/components/dropdown/dropdown.e2e-spec.js#L165,L208) and ensure that the above changes allow for better detection of a Dropdown's open/closed state.

**Additional context**
_TODO:_ List all timeouts with reasons for existence / possible modern solutions

**Comment by EdwardCoyle** [comment]
See [this comment](https://github.com/infor-design/enterprise/issues/570#issuecomment-420784156) on #570 for an example of a test that wasn't reliable due to this issue

**Comment by tmcconechy** [comment]
Going to descope this. The future refactor version will aim to ultimately be free of setTimeouts but i dont think we need to keep an open issue for this
