### ISSUE TITLE
Column: column-stacked errors

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#7941]
**Describe the bug**
TypeErrors when using the column-stacked chart type. 

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/column-stacked/example-index?theme=uplift&variant=light
2. Open dev console
3. See error
4. Hover a chart segment
5. See error

**Version**
- ids-enterprise: 4.87.0
- OS: Windows 11 only, Chrome: latest (116) - beta (117)

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/1101770/773fd06f-b755-4bf7-8eb1-e3beab72104c)

**Additional context**
The stacked column chart is used in multiple homepage/OS Portal widgets by different teams. For some, these type errors cause subsequent issues, such as not being able to open any modal.

**Comment by SofiK** [comment]
Hi @tmcconechy just wanted to ping you about this issue, since it has quite big side affects in Homepages.

**Comment by volante007** [comment]
@tmcconechy I see the errors those two as well (latest/main), 4.86/4.87. 

Maybe browser matters? I'm on Win 11, Chrome

**Comment by ericangeles** [comment]
@volante007 are you on Windows?

**Comment by volante007** [comment]
Yes, Windows 11, Chrome v117

**Comment by ericangeles** [comment]
I saw it on the Windows OS. We don't see it because we're on a Mac.

**Comment by ericangeles** [comment]
Adding it to the sprint, @tmcconechy. We'll look into it, @volante007.
