### ISSUE TITLE
Actionsheet: no hover highlight in dark mode

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#7942]
**Describe the bug**
when hovering on the list, the highlight is not visible in dark mode.
Note: when using a real device. you need to click an item to reveal the highlight. the hover works in devtools

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/actionsheet/example-index.html?theme=new&mode=dark&colors=default
2. switch to mobile view or open in mobile device
3. Open action sheet by clicking the button
4. Hover over the list
5. See error
6. Notice that there's no highlight.

**Expected behavior**
<img width="394" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ca01b79d-99aa-4df6-ab09-6c239767f969">
<img width="168" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/2e1ca94a-b7cc-4880-bc48-4451d7eb378d">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="419" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/77592f44-a1b1-4625-be27-e8b1f42d4fa1">

**Platform**
mobile view

**Additional context**

**Comment by tmcconechy** [comment]
Its not possible to do a hover state on mobile devices. So thats why this wont work. Imagine a phone and you have your finger in the air over the phone button. It cant know where in the air the finger is pointing.

So on mobile you never see hover states.

**Comment by jbrcna** [comment]
thanks for clarifying @tmcconechy. I am referring to the highlight that appears when clicked or click & hold in a real mobile device. the hover is only for dev tools. thank you, noted on this.
