### ISSUE TITLE
Header: Icons are not in the proper place

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7947]
**Describe the bug**
Icons are not in the proper place.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/header/example-toolbar-flex-with-categories.html
2. Notice the magnifying and down arrow icon above 'Product:1' 

**Expected behavior**
Icons should be placed properly.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/d6d1a2b3-a926-4674-8328-d7ef638fe44e)

**Platform**
 - All major browsers

**Comment by yohannahbautista** [comment]
Hello, I'm checking main and it looks like the alignment has been fixed. Though I found in classic that the icon colors are off, should I fix that instead for this issue?

**Comment by tmcconechy** [comment]
@yohannahbautista yes please. Its sort of bad that you cant see the icons there 👍🏻
