### ISSUE TITLE
Module Tab: "Missing" Top/Bottom Border in Alabaster

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#7954]
IDS 4.87.0 - Windows 11, Chrome/Edge, DELL Monitor with default factory display settings

The top and bottom border for Module Tabs in Alabaster in the Uplift Theme is set to #FFFFFF but for all other colours is set to a value that shows a contrasting bordered area.

![image](https://github.com/infor-design/enterprise/assets/44396995/65ee0b48-b80b-4f8f-a54b-788f6252cc3f)

This issue can be reproduced in your own example code...

https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs-module/example-index?colors=ffffff&theme=uplift&variant=light

https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs-module/example-index?theme=new&mode=dark&colors=ffffff

https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs-module/example-index?colors=ffffff&theme=new&mode=contrast

Change the colour to anything but Alabaster to see the border appear at the top and bottom of the module tab.

**Comment by tmcconechy** [comment]
@sanx72 so are you just suggesting we add a border? Does it matter for any reason?

**Comment by sanx72** [comment]
@tmcconechy for consistency. All the other colours have a distinct border that is a different colour to the background, both top and bottom (in the CSS), except for Alabaster.

Here is the module tabs in Alabaster (no border)...

![image](https://github.com/infor-design/enterprise/assets/44396995/35c45469-f69d-4935-b5f8-318e591f5a78)

Here is the same in Azure...

![image](https://github.com/infor-design/enterprise/assets/44396995/be8eae40-37bf-43bd-84e4-eb0c12dec38f)

There's definitely a line between the module tab section and the module header in the other colours except in Alabaster.

**Comment by tmcconechy** [comment]
thanks @sanx72 we'll take this into consideration but it was by design.

**Comment by tmcconechy** [comment]
This should be ok anyways. Because we redid the styles on a new design.
