### ISSUE TITLE
Tabs: Focus state of button/radio button/switch is cut

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#7955]
**Describe the bug**
The focus state of buttons/radio buttons/switches is cut when inside a `.tab-panel-container`.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs/example-enable-disable-individual-tabs.html
2. Focus the "Primary Button" button
4. See cut focus state
5. Focus a radio button at the bottom
6. See cut focus state (very subtle)
7. Use Dev tools to add a switch element to the example, e.g. after the `<fieldset>` containing the radios
```
<div class="switch hide-focus" id="switch-id-1" data-automation-id="switch-automation-id-1">
   <input type="checkbox" checked="true" id="allow-notifications" name="allow-notifications" class="switch">
   <label for="allow-notifications">Allow notifications</label>
</div>
```
8. Focus the switch when "off"
9. See cut focus state

Maybe this is the same for other focus states too.

**Expected behavior**
Focus state completely shown

**Version**
- ids-enterprise: v4.87.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/1101770/51184135-660a-453b-9a15-269b57028d40)
![image](https://github.com/infor-design/enterprise/assets/1101770/d6d89a38-0716-47e4-bcd2-cc0770fb2abb)
![image](https://github.com/infor-design/enterprise/assets/1101770/709b307d-5593-4c75-850c-ea6aaba901be)

**Platform**
 - Infor Application/Team Name: OS Portal

**Additional context**
Works fine on v4.85.0.

**Comment by volante007** [comment]
Caused by this overflow change

```
.tab-panel-container {
  .tab-panel {
    overflow-y: auto;
    margin-top: -5px;
  }
}
```

**Comment by tmcconechy** [comment]
I wonder if changing the overflow will cause another issue to regress. Maybe if we did some padding for the form field it would give enough room to show the whole focus state?

BUt we can check if that rule can be reverted

**Comment by volante007** [comment]
Yeah, not sure. Maybe it can’t be assumed that the controls are inside a form field, nor would look aligned with other tab content such as text/headers.

Ours are just in .field elements, combined with other various content

**Comment by tmcconechy** [comment]
Ok maybe we can use the `.field` class to move it a bit (as long as it all stays aligned)

**Comment by volante007** [comment]
Could the whole tab-panel get some padding maybe?

**Comment by tmcconechy** [comment]
Maybe.. But maybe as an option / class. We'll figure out something

**Comment by hey-yall** [comment]
Asked Maksim Petriv to provide input on this issue in the following Jira ticket: https://jira.infor.com/browse/IDS-1698

**Comment by volante007** [comment]
It seems a fix was only made for the radio buttons? The switch is a bigger problem as seen in description.

**Comment by tmcconechy** [comment]
@tjamesallen15 woops we missed the switch here. Can you make a new PR? I'll mark this as failed.

**Comment by volante007** [comment]
I see this general padding added, so maybe that solved it? 

https://github.com/infor-design/enterprise/pull/8079/files#diff-92dcf78247157c92c1bfb22474704ab9536d7c78aff92d19fb440378719bd9feR285

**Comment by tmcconechy** [comment]
Maybe. There is no switch on https://main-enterprise.demo.design.infor.com/components/tabs/example-enable-disable-individual-tabs.html to verify.

@tjamesallen15 can you add a switch on the example and see if its ok? If not fix, if it is just push a PR with the example.

**Comment by volante007** [comment]
I'm sorry, I got confused since I thought no padding was going to be changed for this (according to JIRA), and just noted the specific fix/change for radios at first.

**Comment by tmcconechy** [comment]
Yes, i thought we needed to fix it that way but @tjamesallen15 came up with a fix on the component which is better to me. Lets add the switch to confirm as i totally missed verifying it as part of this issue
