### ISSUE TITLE
Calendar: Today button overlaps Month/Week/Day view drop down

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise#7966]
**Describe the bug**
Today button overlaps dropdown button when width dimension is short enough

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html
2. Switch to responsive mobile view
3. Shorten width dimension to 403

**Expected behavior**
Today button does not overlap drop down menu

**Version**
- ids-enterprise: v4.88.0-beta.0

**Screenshots**
<img width="317" alt="Untitled" src="https://github.com/infor-design/enterprise/assets/79514236/307362ca-e5be-4546-be45-312fe666fe93">

**Platform**
-mobile view

**Additional context**

**Comment by jbrcna** [comment]
this is now working in local.
<img width="613" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/a83774ba-30a0-4aa6-8e2e-4901e822370d">
