### ISSUE TITLE
Tabs: Error Icon not aligned in dropdown menu

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise#7970]
**Describe the bug**
Using a smaller window, 'Can Have Error Icon' tab in dropdown menu is not aligned

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/example-enable-disable.html
2. Click 'Can Have Error Icon'
3. Type anything into text box and remove text to trigger Error Icon
4. Adjust window size small enough to allow tabs to be selected from a dropdown menu
5. Click dropdown menu for tab selection
6. See error

**Expected behavior**
Error Icon should be aligned with text

**Version**
4.88.0-beta.0

**Screenshots**
<img width="339" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/d8815280-5593-4a0e-9c9d-82fbb572036e">

**Platform**
All browsers

**Additional context**

**Comment by tmcconechy** [comment]
Thanks for a very clear bug report 👍🏻

**Comment by jbrcna** [comment]
this is now working in local
https://7970-tabs-error-icon-dropdown-enterprise.demo.design.infor.com/components/tabs/example-enable-disable.html
<img width="776" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/c2da74b7-eb43-4965-a0a8-5ea9a125aeac">
