### ISSUE TITLE
Bar chart: x-axis ticks not visible for dataset with one group

### ISSUE THREAD

**Issue by DavidMoerman** [infor-design/enterprise#7976]
**Describe the bug**
The top chart is showing three groups, the bottom one a single one. For the bottom example, the tick values are no longer visible.
Please see the attached file index.zip for the code. 

**To Reproduce**
Unpack the attached index.zip file, change the imports to the relevant locations.

**Expected behavior**
I would expect the tick numbers to appear in both cases. It looks like the size of the SVG image generated is not correct; enlarging the height with around 30 pixels solves the problem.

**Version**
4.87.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/145779154/d7de7f77-ec37-427e-affe-d8a203816d24)

**Additional context**
[index.zip](https://github.com/infor-design/enterprise/files/12701297/index.zip)

**Comment by tmcconechy** [comment]
@DavidMoerman if you just have one group you want to use the normal bar chart.

```
        $('#bar-grouped-example2').chart({
            type: 'bar',
            dataset: dataset2,
            tooltip: 'Tooltip by attribute',
            animate: false
        });
```

See corrected attached. one could argue the chart could figure that out but this seems correct to me.

[index.html.zip](https://github.com/infor-design/enterprise/files/12701794/index.html.zip)

![Screenshot 2023-09-22 at 10 28 00 AM](https://github.com/infor-design/enterprise/assets/814283/deeac2fd-288b-4a8f-ae02-236259f38159)

**Comment by DavidMoerman** [comment]
The number of groups in our case is flexible and can range from 1 to 4; and we would like to have the same 'look' in all scenarios.

**Comment by tmcconechy** [comment]
Ok, I guess one group is technically "valid". We can check it later.

Curious if this works in https://github.com/infor-design/enterprise-wc
Which is the new chart https://main.wc.design.infor.com/ids-bar-chart/horizontal-grouped.html getting the bulk of the new features.

**Comment by tmcconechy** [comment]
Might be fixed by adjusting the legend space on https://github.com/infor-design/enterprise/issues/7874 so i would group these issues together.
