### ISSUE TITLE
Button: Styling issue for Toolbar Primary button hover

### ISSUE THREAD

**Issue by SumitK27** [infor-design/enterprise#7977]
**Describe the bug**
Primary button if used with soho-toolbar is hovered the styling looks like the secondary button and the text of the button stays to it's default color present before hovering.

**To Reproduce**

1. Go to [Stackblitz example](https://stackblitz.com/edit/ids-quick-start-1671-yjx4pz)
2. Hover on the primary button added in the datagrid toolbar
3. See error

**Expected behavior**
The button color should get a bit darker and the text color should change (if needed) accordingly

**Version**

- ids-enterprise: v4.87.0

**Screenshots**
Currently on Hover:
![image](https://github.com/infor-design/enterprise/assets/40501698/2c274234-61fa-42de-8538-270639a9125f)

Expected behavior:
![image](https://github.com/infor-design/enterprise/assets/40501698/94f22cd1-2704-41e2-951e-3fbe4060f7e6)
 

**Platform**
 - Infor Application/Team Name: Infor GRC
 - Device: Dell Latitude 5400
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: Chrome and Firefox
 - Browser Version: 117.0.5938.89 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Also you might want to try `soho-toolbar-flex` instead as `soho-toolbar` is deprecated? If it works there that could be the answer.

**Comment by glenlieorillo** [comment]
Passed.

https://github.com/infor-design/enterprise/assets/102151352/2b9509fc-78d0-4329-97a2-caaf2d4af6cc


https://github.com/infor-design/enterprise/assets/102151352/17c8d485-0be3-45a1-95c5-dc26692e32f0


https://github.com/infor-design/enterprise/assets/102151352/bcc9cf18-2638-49b5-bee0-864bbc46534c
