### ISSUE TITLE
Accordion: Selection border color is not consistant

### ISSUE THREAD

**Issue by manjaripalavancha** [infor-design/enterprise#7978]
**Describe the bug**
soho accordion border top color change while expand and collapse.

**To Reproduce**

1. go to [https://design.infor.com/code/ids-enterprise/latest/accordion](url)
2. Click on first one and then open second accordion
3. Observe the extra blue line on the second open accordion top

**Expected behavior**
It should be consistant for all the open and closed accordions.

**Version**

- ids-enterprise: 16.6.1(found)

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/104565263/ed1a71a7-a796-4cd4-8b0f-2e284ae70130)

**Comment by tmcconechy** [comment]
@ericangeles maybe another good one for @RJ-Csc

**Comment by glenlieorillo** [comment]
This is now working as expected in main-enterprise.


https://github.com/infor-design/enterprise/assets/102151352/75c07a7a-12d5-4e82-bbb0-8d5419aa3396
