### ISSUE TITLE
Datagrid: Grid tree issue - items selected incorrectly

### ISSUE THREAD

**Issue by jayshindeinfor** [infor-design/enterprise#7979]
**Describe the bug**
In grid tree multiple pages are selected(showing blue background), attaching screenshot for reference.

**To Reproduce**
Link to reproduce
https://main-enterprise.demo.design.infor.com/components/datagrid/test-tree-multiselect.html

This issue is seen after updating soho to 4.87.0 version.
https://main-enterprise.demo.design.infor.com/components/datagrid/test-tree-multiselect.html

**Expected behavior**
The multiple pages should not be selected by default.

**Version**

- ids-enterprise: 4.87.0
**Screenshots**
<img width="958" alt="image" src="https://github.com/infor-design/enterprise/assets/145977410/63401fe5-008e-4076-9289-cb659743019b">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
https://main-enterprise.demo.design.infor.com/components/datagrid/test-tree-multiselect.html
<img width="1219" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/09b300fb-0fac-49a2-bb49-0c64a3cba5e3">
<img width="1407" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/bdbddbf8-4405-4cf7-873b-3bf3e5237a21">
