### ISSUE TITLE
Rows of a given page number doesn't appear in datagrid with save settings after reload page

### ISSUE THREAD

**Issue by CristianCosta** [infor-design/enterprise#798]
**Describe the bug**
Rows of a given page number doesn't appear in datagrid with save settings after reload page.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html
2. Set on pagination text field a page number like 2.
3. Refresh the page (F5).
4. You wont see the rows in the datagrid related to that page number.

**Expected behavior**
The expected is to see the rows of that selected page established in the pagination component.

**Platform**
 - Browser Name: chrome, firefox

**Comment by tmcconechy** [comment]
Is this also an issue on your end? I'm just wondering if its just an example problem as our backend for this test is not very sophisticated.

**Comment by tmcconechy** [comment]
Gotcha, ok cool. We probably should fix the example to avoid confusion.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-save-settings.html
http://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html
Passed QA testing on all browsers, moving to Done.
