### ISSUE TITLE
ProcessIndicator: Icons the wrong size

### ISSUE THREAD

**Issue by MadhaviDasika** [infor-design/enterprise#7982]
**Describe the bug**
Process indicator with icons shows gaps between the indicator icon and lines.

**To Reproduce**
1. Create a simple process indicator with icons.
2. Gaps are visible between the icons and the lines.

Even IDS sample showcases the issue.

**Expected behavior**
Show the process indicator with icons without gaps.

**Version**
- ids-enterprise-ng: 16.6.1

**Screenshots**
<img width="758" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/24714335/61484f7c-43a9-4bb6-b0d9-547c94b735fb">
<img width="797" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/24714335/479c2d25-edc6-4acf-8349-5c5554a93b3a">

**Platform**
 - Browser Name - any browser

**Additional context**
Business needs a neat view without gaps. Conversation reported in below channel.

https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1695369158757?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1695369158757&teamName=IDS%20Enterprise%20Development&channelName=Angular%20Components&createdTime=1695369158757

**Comment by talkaboutdesign** [comment]
@tmcconechy are you sure this is not by design?

**Comment by tmcconechy** [comment]
![Screenshot 2023-09-26 at 2 15 29 PM](https://github.com/infor-design/enterprise/assets/814283/48389a9b-097b-4151-985f-4614dd06eb97)

Perhaps a point @talkaboutdesign for me the gaps might be ok if thats the design but they should be the same size

- so same size ~ i think yes
- slight gap between dots ~  debatable

Presently in figma there is no gap https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/IDS-(SoHo)-Component-Library-v4.8?type=design&node-id=29451-61726&mode=design&t=9HH61VopchWO1V7W-0 but we could change if you think?

**Comment by talkaboutdesign** [comment]
> ![Screenshot 2023-09-26 at 2 15 29 PM](https://user-images.githubusercontent.com/814283/270755542-48389a9b-097b-4151-985f-4614dd06eb97.png)
> 
> Perhaps a point @talkaboutdesign for me the gaps might be ok if thats the design but they should be the same size
> 
> * so same size ~ i think yes
> * slight gap between dots ~  debatable
> 
> Presently in figma there is no gap https://www.figma.com/file/yaJ8mJrqRRej8oTsd6iT8P/IDS-(SoHo)-Component-Library-v4.8?type=design&node-id=29451-61726&mode=design&t=9HH61VopchWO1V7W-0 but we could change if you think?

Let's just align with whats in Figma. This is a great catch.

**Comment by glenlieorillo** [comment]
Passed.

<img width="1791" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/77af1260-8635-4890-80e5-c98dda66387f">
