### ISSUE TITLE
Modal: '+' button shows below '-' instead of to the right of the spinbox in Classic version

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise#7988]
**Describe the bug**
The '+' button that increments the spinbox shows below the '-' button instead of to the right of the spinbox text where it should be. This is probably due to the allocated space given to the spinbox in the modal being too small so the '+' button occupies the space below it.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/modal/example-spinbox.html
2. Switch version to Classic
3. Click 'Show Modal'

**Expected behavior**
The '+' button should appear next to the spinbox text

**Version**
- ids-enterprise: v4.88.0-beta.0

**Screenshots**
Expected as seen using New version
<img width="178" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/1784b057-a06d-4c25-8875-5e7778118701">

Using the Classic version, the '+' button tries to compensate and occupies the vertical space allocated for it under the '-' button'
<img width="166" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/05eb9009-ce96-48e2-a847-653e58aa87d2">

**Platform**
 - Device: Laptop
 - OS Version: Windows 11
 - Browser: All browsers

**Additional context**

**Comment by glenlieorillo** [comment]
Passed.

<img width="1791" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/daea5a7e-d9cf-4b8f-a187-e393f1744ad6">
