### ISSUE TITLE
Checkbox: Style issue when checked, in modal in dark mode

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#7991]
**Describe the bug**
The background of a selected checkbox is the same as the modal background color in dark mode.

**To Reproduce**
1. https://design.infor.com/code/ids-enterprise/latest/demo/components/modal/test-checkbox.html?theme=new&mode=dark&colors=default
2. Open modal
3. Check one of the checkboxes

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/1101770/8540aba0-8c47-40f4-a78a-83ddb1cb0865)

**Version**
- ids-enterprise: v4.87.0

**Platform**
 - Infor Application/Team Name: OS Portal 
 
**Additional context**
Looks OK on 4.86.0

**Comment by tmcconechy** [comment]
Design: Is to change to slate 01 https://www.figma.com/file/nHRdY5ARKI8HPr2pQs3vWk/Themes?type=design&node-id=1839-19559&mode=design&t=eAZSRJjNae10IGxI-0
