### ISSUE TITLE
Datagrid: addRow() problem / creating a new array

### ISSUE THREAD

**Issue by dsinfor** [infor-design/enterprise#7995]
**Describe the bug**
In our wrapper of SohoDataGridComponent, calls to addRow() add to the dataset property but do not add always add rows to the array. Updates to existing rows seem to work fine but addRow only works after the initial load, after reload of data addRow fails.

**To Reproduce**
1 - Load the sample 
https://stackblitz.com/edit/ids-quick-start-1671-b25ibn?file=src%2Fapp%2Fvisual-table%2Fvisual-table.component.ts

The dropdown has 2 options
Timeoff list and Status list, defaulted to Timeoff list 
Selecting each option loads the appropriate list

2 - Press Add
On ititial load, when the Add button is pressed, a new row is added to the grid and array from the selected list

console.log output in the AppComponent.AddRow() and VisualTableComponent.AddRow() compare the length of the SohoDataGridComponent.dataset with the data array

After the initial load, the Add works fine
  visualtable.addRow success
  AppComponent.onAddClicked success

3 - Press Add 2 times and so 3 rows are added, no problem

4 - Now change the active list to Status list 

5 - press Add
Note the output from console.log 
  visualtable.addRow fail 4!=3
  AppComponent.onAddClicked fail 4!=3
indicating that the row added to the SohoDataGridComponent was not added to the data array

6 - Switch back to Timeoff list and notice that the 3 new rows added are still there

7 - but press Add and notice the fail messages from console.log

From this point on, adds to SohoDataGridComponent.dataset will not be reflected in the related arrays.

**Expected behavior**
We have multiple places where this causes a problem.
Our expectation is that we be able to add grid rows, even after the attached data array has been changed from the original array.

**Version**
- ids-enterprise: 16.7.1

**Platform**
 - Infor Application/Team Name: Infor VISUAL CRM
 - OS Version: Windows 11
 - Browser Name: Edge

**Comment by tmcconechy** [comment]
The issue could be this https://github.com/infor-design/enterprise/blob/main/src/components/datagrid/datagrid.js#L828 is creating a new array
