### ISSUE TITLE
Cards: Border below the tabs is missing in Classic-Dark Version

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#7999]
**Describe the bug**
Border below the tabs is missing in Classic-Dark Version

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/cards/test-tabs-card.html?theme=classic&mode=dark&colors=default
2. Notice the border below tabs is missing

**Expected behavior**
There should be a border below the tabs

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

![image](https://github.com/infor-design/enterprise/assets/102151352/4ccb94aa-7e92-4488-a3a1-7fe2f4ff2209)

![image](https://github.com/infor-design/enterprise/assets/102151352/d6a3da7f-351f-4dc0-a7fa-a1e7cb4cbc78)

_Reference:_
![image](https://github.com/infor-design/enterprise/assets/102151352/35369ee5-1f22-4a0a-b2cb-e0308db24491)

**Platform**
 - All major browsers

**Additional context**

**Comment by ericangeles** [comment]
@glenlieorillo, the issue has been addressed in this pull request: https://github.com/infor-design/enterprise/pull/7994. I will now close this. Thank you.

**Comment by jbrcna** [comment]
QA Passed
<img width="976" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/571c2a75-d1a3-4810-ba0e-acd7a554b382">
