### ISSUE TITLE
Dropdown: Dropdown menu looks off in responsive view

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8000]
**Describe the bug**
Dropdown menu looks off in responsive view

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/dropdown/example-index.html
2. Change to responsive view
3. Adjust the screen to a smaller view
4. Notice the dropdown menu

**Expected behavior**
Dropdown menu should render properly even in a smaller view.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

![image](https://github.com/infor-design/enterprise/assets/102151352/3fde2871-4157-47b9-a07b-0e9d4fe02b6e)

![image](https://github.com/infor-design/enterprise/assets/102151352/104db61e-87f3-482a-8f5a-119b8cc1444c)

![image](https://github.com/infor-design/enterprise/assets/102151352/cf0fd4ac-05b5-4c44-b141-2bb34d3944be)

**Platform**
 - Mobile
 - BrowserStack

**Comment by ericangeles** [comment]
Keep in mind that the minimum width that we support is `320px`.

**Comment by tmcconechy** [comment]
We can maybe hide the text better / make the icon not flow over on super small dropdown width
