### ISSUE TITLE
Splitter: list-detail with splitter in modal isn't working correctly

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#8005]
**Describe the bug**
When bringing up a modal with a list-detail and splitter:
- modal header is being covered
- list-detail seems slightly outside of modal on the left side. note the splitter 
- side bar vertical scrolling isn't working, no scrollbar
- side bar horizontal scrollbar shows event when it isn't needed
- when narrowing list-detail so that only the side bar displays clicking on side bar item does not slide the main content into place.     Would need to add affordance for back button to the right side content. Probably something we'd need to do.
- tree node wrap, I'd like then to not wrap but cause the horizontal scrollbar to display when there is not enough width.

**To Reproduce**

1. put attached example into place
2. run http://localhost:4000/components/splitter/test-splitter-in-modal.html

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/4737815/164b129f-94f2-459b-bcc0-ebf4d7b34b04)
![image](https://github.com/infor-design/enterprise/assets/4737815/1137d58d-c70a-451a-ad06-f6338123cab4)
![image](https://github.com/infor-design/enterprise/assets/4737815/00c16c5c-a3a2-4bc0-b7f5-6e5185dd6da7)
![image](https://github.com/infor-design/enterprise/assets/4737815/46cc000e-47f1-4a4f-8a65-c446c3c6b0a2)

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: latest

**Example**

[test-splitter-in-modal.zip](https://github.com/infor-design/enterprise/files/12751048/test-splitter-in-modal.zip)

**Additional context**

**Comment by tmcconechy** [comment]
@pwpatton do we still need this or is this needed just web components? So we do this only one time.
