### ISSUE TITLE
Checkbox: Focus State Not Discernible 

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#8015]
**Describe the bug**

The focus state on checkboxes needs improvement its not very discernible.

**To Reproduce**
1.  See https://main-enterprise.demo.design.infor.com/components/radios/example-index.html and focus
2. Tab in the page through the checkboxes

**Expected behavior**
Maybe something more like https://main-enterprise.demo.design.infor.com/components/radios/example-index.html

**Screenshots**

Not too bad here but could be better:
![Screenshot 2023-10-02 at 1 28 32 PM](https://github.com/infor-design/enterprise/assets/814283/f4f54793-73ee-4834-91c0-f8056033cb95)

More so here:
![Screenshot 2023-10-02 at 1 28 27 PM](https://github.com/infor-design/enterprise/assets/814283/507e5b55-7cb1-45d4-bfa1-e394108502b2)

**Comment by tmcconechy** [comment]
Also not that this applies to web components as well

**Comment by hey-yall** [comment]
Jira ticket for design resources: https://jira.infor.com/browse/IDS-1739

**Comment by tmcconechy** [comment]
Ready to go.

**Comment by tmcconechy** [comment]
Note: We need to do this on WC as well. If you want to do a PR and fix there that would be great if not lets make an issue for it when this is complete
