### ISSUE TITLE
Tabs: Reorder/Drag tabs coming from More button 

### ISSUE THREAD

**Issue by edisonferrer** [infor-design/enterprise#8016]
**Is your feature request related to a problem? Please describe.**
In line with this ticket https://github.com/infor-design/enterprise/pull/7728

Possibility to be able to do the same reordering and dragging when tabs are coming from the more button:
<img width="960" alt="image" src="https://github.com/infor-design/enterprise-ng/assets/47999751/1dafdb5a-4b99-49d2-af36-96ef95bb5afe">

**Additional context**
In addition need an event that fires when the sort changes and for each of the drag events

**Comment by tmcconechy** [comment]
Any particular justification for doing this?

**Comment by edisonferrer** [comment]
Hi Tim, actually this came up together with our https://github.com/infor-design/enterprise/issues/8017 request. 
Since the customer was seeing only a few interactable tab and the rest were on the More button, customer wanted to be able to control what tabs are outside the more button.

For reference, the common setup for maximum tabs a user can open at a given time are 10 tabs.

**Comment by tmcconechy** [comment]
![Screenshot 2023-10-17 at 8 38 40 AM](https://github.com/infor-design/enterprise/assets/814283/8048f87b-4084-4b62-97a0-2c6a558a6d98)

We were looking in what browsers do and it does the same thing. Just noting its not doing it this way. Also it would be too difficult to drag in and out of the menu.

**Comment by tmcconechy** [comment]
Design added on https://inforwiki.atlassian.net/browse/IDS-1740

**Comment by inforandy** [comment]
@edisonferrer We adjusted the behavior on this component so that the selected tab in the overflow menu swaps with the last active and can be dragged/rearranged. Can you review the behavior and let us know if this improves the customer scenario? 

Thank you

**Comment by inforrpunay** [comment]
Hi @inforandy,

The adjusted behavior sounds good to me. That would require the user to select the tab first from the overflow before it can be rearranged but to me that is already an improvement as compared to not being able to rearrange the tabs. May we know when the improvement will be available? The number of customers asking for this feature is already increasing.

Kind regards,
Raymond

**Comment by tmcconechy** [comment]
@inforrpunay if this is the decided dirction (its a two step process). Then i think we can pull this in next sprint (June)

**Comment by inforrpunay** [comment]
Thanks, @tmcconechy! Can you also confirm if the planned changes here will also address the raised issue in https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1712047954537?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1712047954537&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1712047954537 where there are preventDefault() calls which break our other feature of pairing tabs?

**Comment by inforrpunay** [comment]
Hi @tmcconechy, we need those low level events to determine if the user dragged and dropped a tab over another tab. That is our way to determine if we are going to pair the two tabs. Having an event that fires when the tab sort changed is also a good thing to have.
