### ISSUE TITLE
Modal: Dialog has an offset issue

### ISSUE THREAD

**Issue by bdahlen** [infor-design/enterprise#8018]
**Describe the bug**
A modal dialog with dynamic content can get incorrectly positioned off the viewport.

Consider the example where the dialog contains switch components. Enabling or disabling a switch will expand or collapse a section, so the overall height of the content inside the modal dialog dynamically changes.

The entire body of the page gets offset. The offset seems to match the scroll height inside the modal dialog. If the "no-scroll" CSS class is removed from the body, you can scroll up to see the rest of the body and the entire modal dialog.

**To Reproduce**

See the following stackblitz to reproduce the issue.
https://stackblitz.com/edit/ids-quick-start-1671-mpucu2?file=src%2Fapp%2Fapp.component.ts

1. Click the "Show Modal" button to launch the modial dialog.
2. Scroll down on the modal and disable one of the switches closer to the bottom, such as Position, JobApplication, or EmployeeAppraisal.
3. A vertical offset gets applied to the body and the dialog will either be partially clipped at the top or not visible at all.

**Expected behavior**
The body should never get offset and the modal dialog should always remain completely visible on the page without any clipping. It's expected that the user may need to scroll the contents of the modal dialog if there is a lot of content inside the modal.

**Version**

- ids-enterprise: v4.87.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/146859868/abe15e18-de78-40fc-bde8-01517ab352c2)

**Platform**
 - Infor Application/Team Name: Infor HR Talent
 - Device: Not Applicable
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 117.0.5938.132 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Hmm maybe its a bug in the switch? Wierd one.

**Comment by glenlieorillo** [comment]
This is now working as expected.


https://github.com/infor-design/enterprise/assets/102151352/d375c335-d9cd-43ba-92d0-8fbdd38dd6aa
