### ISSUE TITLE
MobileNav: Additional Issues (close on mobile / resize)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#8019]
**Describe the bug**

The mobile nav is missing 2 things which need to be patched in 4.84 and 4.88. Namely:

- on mobile when you click an item it should close
- when you resize the page it should activate the breakpoint change

**To Reproduce**

1. Go to  https://main-enterprise.demo.design.infor.com/components/module-nav/example-index.html?colors=fff
2. Expand
3. Resize To mobile
4. Should fold to mobile mode
5. Click a menu item -> should close

**Expected behavior**
- `autoCloseOnMobile` - will be set to true and will close the menu when clicked

**Additional context**
MS Teams "Module Nav..." Channel

**Comment by jbrcna** [comment]
QA Passed
https://main-enterprise.demo.design.infor.com/components/module-nav/example-index.html?colors=fff
