### ISSUE TITLE
Datagrid: Date alignment

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8021]
**Describe the bug**
Text/Date alignment upon clicking the cell.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html or https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?theme=new&mode=light&colors=default&locale=ar-SA
3. Click on cell with data under Order Date column
4. Notice that the date is moving left/right or a space is appearing before/after the date

**Expected behavior**
The date should stay at the center upon clicking the cell.

**Version**

- ids-enterprise: 4.88.0-beta.0

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/42138231-7fb4-4b32-a4f2-0ef11ee5b46c

**_RTL_**

https://github.com/infor-design/enterprise/assets/102151352/c7d277ef-b552-47b6-9578-39f8b1eb2794

**Platform**
 - All major browsers

**Comment by jbrcna** [comment]
this is working as expected.
<img width="1590" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/d76ca850-65f9-467d-921d-d70e4f721bad">
<img width="1603" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/5f3f1e69-d9c1-48ff-a415-1dd12d19d145">

However, in RTL classic the text is cut off
<img width="1309" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/f4895fa0-79ca-4b5d-ad89-2c5d604a31a2">
