### ISSUE TITLE
Datagrid: Some cells are uneditable

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8023]
**Describe the bug**
Some cells are uneditable.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html or https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?theme=new&mode=light&colors=default&locale=ar-SA
2. Click the cells under Action column
3. Notice that the other cells are uneditable

**Version**

- ids-enterprise: 4.88.0-beta.0

**Screenshots**

https://github.com/infor-design/enterprise/assets/102151352/78dc08f5-6c82-4e0c-964b-464e801b0e55

**_RTL_**

https://github.com/infor-design/enterprise/assets/102151352/52b8a9ce-1591-4d53-9185-d2b932ba935c

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
@glenlieorillo this is "by design" the example is showing some cells that are not editable in a darker slate color. This is a common use case and its just showing it in the example here.
