### ISSUE TITLE
File Upload: Able to remove the file from Read Only field 

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#8024]
**Describe the bug**
File Upload: Able to remove the file from Read Only field 

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/fileupload/example-index.html
2. Tab to the readonly field
3. Hit backspace 
4. Notice that the file name is removed 

**Expected behavior**
Should not happen on readonly fields

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/45757016/793c41ee-0c25-4a5e-ba29-b2a41dec5cc3)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
![Large GIF (880x434)](https://github.com/infor-design/enterprise/assets/56722184/c4236b7b-9291-4a04-a7e7-7c7674a1a14a)
