### ISSUE TITLE
Widget/Card: Title width too small

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#8027]
**Describe the bug**
The widget title is only allowed to be `230px` wide, which seems too little even for a single width widget.

**To Reproduce**
1. https://design.infor.com/code/ids-enterprise/latest/demo/components/cards/example-index?theme=uplift&variant=light
2. Use dev tools to change the double width widget title to something longer
4. It's truncated at 230px, even though there's plenty of available width

**Expected behavior**
Similar to how it looked in v4.85.0

**Version**
- ids-enterprise: v4.87.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/1101770/17e7c1df-cd1a-4f08-a9f3-598aaeae1d4e)

In v4.85.0, it looks like
![image](https://github.com/infor-design/enterprise/assets/1101770/952a5ba3-f9d4-4350-93e1-f0f7d1f787e9)

**Platform**
 - Infor Application/Team Name: OS Portal

**Additional context**
Most noticeable when widget is double width or more, but even for single width it could be longer

**Comment by tmcconechy** [comment]
@ericangeles can we change this back?

**Comment by ericangeles** [comment]
Looks okay now in main https://main-enterprise.demo.design.infor.com/components/cards/example-index

@tmcconechy @volante007

**Comment by tmcconechy** [comment]
yes your right, maybe the rules changed> @volante007 does it look ok now on main?

![Screenshot 2023-10-05 at 9 33 08 AM](https://github.com/infor-design/enterprise/assets/814283/77d1cf0d-3345-407d-a74f-1f099047901d)

**Comment by volante007** [comment]
Nice, yes looks ok on main now :)

**Comment by glenlieorillo** [comment]
This is now working as expected.

https://main-enterprise.demo.design.infor.com/components/cards/example-index
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/29b37995-530c-4460-a07a-32938ad0108e">
