### ISSUE TITLE
Donut: donut chart rounding is cut off

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8028]
**Describe the bug**

**To Reproduce**
1. Go to https://4880-enterprise.demo.design.infor.com/components/donut/example-index.html
2. go to donut chart
3. click each component (slice)

**Expected behavior**
<img width="943" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/b5a7fc59-74f8-45ed-b5af-417f195808ec">

**Version**
- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="790" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/46fca273-5643-4982-947a-cc395b667eee">

**Platform**
Safari

**Additional context**

**Comment by tjamesallen15** [comment]
![image](https://github.com/infor-design/enterprise/assets/34049950/f89cc144-ecc6-463d-864b-85de82d7b8c5)

I think this is now fixed from previous bug fixes, I can't see any cut off. @jbrcna 

cc @ericangeles @tmcconechy

**Comment by ericangeles** [comment]
@tjamesallen15 great thanks!

**Comment by jbrcna** [comment]
this is what I can see in my end @tjamesallen15 . click component B
browser: Safari
<img width="1289" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/0f69db44-6065-4c38-afdf-00c16e1a9311">

**Comment by ericangeles** [comment]
Could you check it again, @tjamesallen15 ?

**Comment by ericangeles** [comment]
@tmcconechy, I believe what he meant was cutting the donut on the left side. @jbrcna, I've checked it on my end using Safari, and I no longer see the issue.

**Comment by tmcconechy** [comment]
ok can you verify its fixed@jbrcna

**Comment by jbrcna** [comment]
perhaps because of safari version?

Version 17.1 (19616.2.9.11.7)
<img width="587" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/5d5693f6-5d78-44ac-9b03-891e24b2d368">



Version 15.6.1 (17613.3.9.1.16)
not quite obvious on this version
<img width="773" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/26138702-6f6c-408e-bfd7-2164bba73123">
