### ISSUE TITLE
Editor: editor font color issue safari

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8029]
**Describe the bug**
when chaging font color in safari. you have to click twice to select

**To Reproduce**
1. Go to https://4880-enterprise.demo.design.infor.com/components/editor/example-index.html
2. go to Edtitor component
3. change font color
4. See error (it pops up twice)

**Expected behavior**

**Version**
- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

https://github.com/infor-design/enterprise/assets/56722184/dce0f91d-b1a2-4555-b1f0-bc13d2255d29

**Platform**
Safari

**Additional context**

**Comment by tjamesallen15** [comment]
Can you try testing this again @jbrcna, its not reproducible in main. Thanks

**Comment by jbrcna** [comment]
this is now working as expected. thank you @tjamesallen15 
verified in https://main-enterprise.demo.design.infor.com/components/editor/example-index.html
![Large GIF (1314x494)](https://github.com/infor-design/enterprise/assets/56722184/fcf8b937-a619-4389-af5d-ccee73ee701d)
