### ISSUE TITLE
Message: Info icon in info example message is slightly cropped in Classic

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise#8031]
**Describe the bug**
Left side of the info icon is cropped when using Classic mode

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/message/example-index.html
2. Change Version to Classic
3. Click 'Info Example' button

**Expected behavior**
Info icon should show in full

**Version**
- ids-enterprise: 4.88.0-beta.0

**Screenshots**
<img width="313" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/9c94517f-f1f4-473c-b4d7-8a1a6f97af33">

**Platform**
 All browsers

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
verified in https://main-enterprise.demo.design.infor.com/components/message/example-index.html?theme=classic&mode=light&colors=default
<img width="1063" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/52c3751d-5b08-44a8-b70b-5f8e5f42232b">
