### ISSUE TITLE
Multiselect: disabled multiselect x icon color contrast is off

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8036]
**Describe the bug**
x icon color contrast does not match its sibling

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/multiselect/example-index.html?theme=new&mode=contrast&colors=default
2. Switch to high Contrast
3. go to multiselect component (disabled)
5. Notice that the x icon color does not match the font color of text beside it
6. See also dark mode

**Expected behavior**
the color of x icon and text should match
<img width="399" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/703d5c63-a1ec-4c7e-a377-8d796f1f97e4">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
**high contrast**
<img width="374" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ffa756a3-dfc5-4599-b5aa-6d65cc4d2eb1">
 
**dark**
<img width="406" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/3d7bb5a6-0dbc-41ab-8150-050c3e1e10b4">

**Platform**

**Additional context**

**Comment by tmcconechy** [comment]
Solution: Make the x one or two colors down in the slate scale https://main-enterprise.demo.design.infor.com/components/colors/example-index.html?theme=new&mode=contrast&colors=default
