### ISSUE TITLE
Context menu stopped working in Safari

### ISSUE THREAD

**Issue by Fruko** [infor-design/enterprise#8037]
**Describe the bug**
Context menu stopped working in Safari

**To Reproduce**

1. Go to [context menu example](https://design.infor.com/code/ids-enterprise/latest/demo/components/contextmenu/example-index?theme=uplift&variant=light)
2. Right-Click on button
3. See error

**Expected behavior**
Popup menu opens

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]
latest (4.87.0)
**Screenshots**

**Platform**
- MacOS
- Safari v17.0

**Additional context**

**Comment by glenlieorillo** [comment]
Safari
<img width="1791" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/d107f7d0-fa6f-44ba-8780-cee67b10a048">

Chrome
<img width="1791" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/2cb54fa5-eee8-4b11-b558-394eea2a0bbc">
 
FF
<img width="1791" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/4d0431d9-90d2-40ce-bfc8-e163efd11b58">

Edge
<img width="1791" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/e52fe4d9-faab-4b64-9e7e-7328b819afb4">

iOS
![image](https://github.com/infor-design/enterprise/assets/102151352/ff8322db-10d3-4857-9cb2-cabd0acd2937)

Android
![image](https://github.com/infor-design/enterprise/assets/102151352/4999a88b-1aca-4e34-87b0-67fba49c0c0d)
