### ISSUE TITLE
Notification banner: inaccurate docs

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise#8038]
**Describe the bug**
The overview documentation for [Notification banner](https://design.infor.com/code/ids-enterprise/latest/notification) say that the component is not dismissible. 

**Expected behavior**
Update `The notification banner is a non-dismissible banner that sits at the top of the page.` to `The notification banner is a dismissible alert that sits at the top of the page.`

**Screenshots**
<img width="533" alt="image" src="https://github.com/infor-design/enterprise/assets/117312557/42a27431-d317-4d8d-8244-875e81767a00">

**Comment by hey-yall** [comment]
Linked to Jira issue https://jira.infor.com/browse/IDS-1719

**Comment by tmcconechy** [comment]
https://github.com/infor-design/enterprise/blob/main/src/components/notification/readme.md ~ updated now but will take a while.
