### ISSUE TITLE
Autocomplete doesn't fire change event when a value is selected

### ISSUE THREAD

**Issue by PilotBob** [infor-design/enterprise#804]
**Describe the bug**
When binding to the change event of an autocomplete the change is not fired if the user selects a value from the dropdown list.

**To Reproduce**
1. Go to http://localhost:4000/components/autocomplete/example-index
2. Set up a change handler `$("#autocomplete-default").on('change', function() { alert($(this).val())})`
3. Type in a partial match to the value 'a'
3. Arrow down to select, notice change fires with the typed in value
4. Select a value from the list

**Expected behavior**
change event fires

**Platform**
 - Windows 7
 - All Browsers

**Comment by tmcconechy** [comment]
Having @deep7102 take a quick look at this one today. Hope thats ok @ericangeles we just wanted this one in

**Comment by tmcconechy** [comment]
I think deepak was working on this my mistake.

**Comment by ericangeles** [comment]
@tmcconechy for sure. Not a problem. :)

**Comment by janahintal** [comment]
QA Passed. Will now move to Done. Thank you. 
Verified in https://4280-beta1-enterprise.demo.design.infor.com/components/autocomplete/test-on-change.html?theme=uplift&variant=light across all platforms.
