### ISSUE TITLE
PopupMenu: Highlight showing for two elements at a time in case of mixings and submenu is not closing.

### ISSUE THREAD

**Issue by manjaripalavancha** [infor-design/enterprise#8043]
**Describe the bug**
When we are working on popup menu along with submenu we have observed one issue which is related to popup menu highlight with two elements same time.
When I hover on submenu item and immediately moved to another list item which doesn't have submenu, the submenu is not closing and the non-submenu list item and submenu both the elements showing background color as highlighted.

**To Reproduce**

1. Go to Popupmenu mixing selectables https://main-enterprise.demo.design.infor.com/components/popupmenu/example-mixing-selectables.html
2. Hover on list item which has submenu and slowly hover on non-submenu list item
3. Hover element background color is showing for both the elements and submenu is not collasing.

**Expected behavior**
Submenu will collapse when we hover on other menu item and submenu highlight should be there only for hoved item.

**Version**

- ids-enterprise: 16.7.1 (Observed)

**Screenshots**
You can refer below screenshot and the recording.
<img width="620" alt="MicrosoftTeams-image (14)" src="https://github.com/infor-design/enterprise/assets/104565263/f2b72031-c697-46fe-89f5-365195b3553d">

https://github.com/infor-design/enterprise/assets/104565263/9c5e6ab3-6417-4c2d-a182-765077dbf546

**Additional context**
You can also refer the below conversion reported in the channel.
[https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1696562164895?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1696562164895&teamName=IDS%20Enterprise%20Development&channelName=Angular%20Components&createdTime=1696562164895](url)

**Comment by tmcconechy** [comment]
Tough one to fix. To clarify just move at a diagonlal from the submenu bottom item up to the Non Selectable Item #4

**Comment by jbrcna** [comment]
QA Passed
https://main-enterprise.demo.design.infor.com/components/popupmenu/example-mixing-selectables.html
<img width="1570" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/315c4921-373a-460c-92d9-d92ef32cf789">
