### ISSUE TITLE
Accordion: Using mobile shows ellipsis before header

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise#8044]
**Describe the bug**
Using mobile, accordion with multi-level expansions has periods before the header

**To Reproduce**

1. Using mobile, go to https://main-enterprise.demo.design.infor.com/components/accordion/test-all-plus-minus.html
2. See error

**Expected behavior**
Only header text should be showing

**Version**

- ids-enterprise: v.4.88.0-beta.0

**Screenshots**
Current version shows ellipsis before header
<img width="193" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/70be1501-d058-4315-ae72-badda4c555b5">

Expected behavior
<img width="146" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/9a43be23-c16c-444d-9235-8f8457b5c831">

**Platform**
 - All browsers

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
verified in https://main-enterprise.demo.design.infor.com/components/accordion/test-all-plus-minus.html
<img width="844" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/9a22f024-9245-4ebd-9e4e-e61e51d476ef">
