### ISSUE TITLE
Unable to close TimePicker after setting the value then opening again

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#805]
**Describe the bug**
The TimePicker is not closing after second load

**To Reproduce**
1. Click on the TimePicker icon on one of the TimePickers.
2. Select time then click on "Set Time"
3. Close the TimePicker.
4. Open again using the icon.
5. Change the time then "Set Time" again.
6. The TimePicker doesn't close.

**Platform**
 - OS Version: Windows 10
 - Browser Name: Microsoft Edge

**Additional context**
```
<div class="field">
      <label for="timepicker-blur-test" class="label required">Time Field Required only on blur</label>
      <input id="timepicker-blur-test" class="timepicker" type="text" data-trackdirty="true" data-validate="required" data-validation-events="{ 'required': 'blur' }">
    </div>
<div class="field">
      <label for="timepicker-main" class="label">Timepicker</label>
      <input id="timepicker-main" class="timepicker" type="text">
</div>

```

**Comment by tmcconechy** [comment]
Confirmed this bug, seems to only happen in edge (tried chrome and did not occur)

**Comment by marknolaninfor** [comment]
This issue requires more than one timepicker on the page, and only happens in the Edge browser. All the current examples have only a single control on the page.

**Comment by tmcconechy** [comment]
Really wierd, i tried you example and could see it happen only one time. Every time after works fine.
Are you able to reproduce it consistently.. If you have a fix feel free...

**Comment by marknolaninfor** [comment]
I have been able to reproduce this consistently, by opening and setting the timepicker with the validation, and then opening the same control very quickly, over and over again.

**Comment by tmcconechy** [comment]
Maybe i dont have the sequence correct then? Can you update the steps? Im trying on windows 10 edge 17 with your exact code.

**Comment by tmcconechy** [comment]
Unfortunately we were not able to reproduce this with the given info. Feel free to reraise if you can add another test case, i'm just not seeing this.

**Comment by johnbarcena** [comment]
Hello, Issue found on 4210-enterprise. 
![Timepicker-4210](https://user-images.githubusercontent.com/52902639/66742653-b92b8980-eeaa-11e9-806f-5604b1e69c91.gif)
