### ISSUE TITLE
BarChart: Incorrect size widget for horizontal bar chart on initial load 

### ISSUE THREAD

**Issue by hey-yall** [infor-design/enterprise#8053]
**Describe the bug**
Bug originally reported in Jira under https://jira.infor.com/browse/IDS-1606 .

In FSM PBWS, the horizontal bar chart component initially loads in a 1x1 widget. Upon refresh, the chart loads normally. See the videos attached to the Jira ticket for more information. 

**To Reproduce**
In FSM PBWS, initial load of horizontal bar chart displays a 1 x 1 widget. This is incorrect. 

**Expected behavior**
FSM PBWS horizontal bar chart should have a larger widget container. 

**Version**
4.87.0

**Screenshots**
See Jira ticket https://jira.infor.com/browse/IDS-1606

**Comment by tmcconechy** [comment]
Note our bug reporting guidelines https://github.com/infor-design/enterprise/blob/main/docs/CONTRIBUTING.md#bug-reports 

And example bug https://github.com/infor-design/enterprise-ng/issues/1565 

I.E. We need a simple example showing the issue not in the app so we can debug and try solutions.

**Comment by tmcconechy** [comment]
Closing this in favor of https://github.com/infor-design/enterprise/issues/8410 as it does not have a way to reproduce but that issue does and we can see after if any futher issues that can be reproduced
