### ISSUE TITLE
Widget/Card: Four column wide widget has incorrect width

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#8056]
**Describe the bug**
A four column wide card/widget, i.e. uses `.quad-width` class, has incorrect width. It's greater than four single width widgets + gutter.

**To Reproduce**
1. https://design.infor.com/code/ids-enterprise/latest/demo/components/homepage/example-scenario-l.html
4. See incorrect width of top widget 

**Version**
- ids-enterprise: v4.87.0 / latest

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/1101770/ebe028af-24e4-45cb-81db-433b76c6247a)

**Platform**
 - Infor Application/Team Name: OS Portal
 
**Additional context**
Triple & double widths are correct.

**Comment by talkaboutdesign** [comment]
Should be **1488**. Thats the full width of the grid. 
8 columns 172px wide with 16px gaps = 1488
or you can count as 360px wide widget with 16 gaps 4 across = 1488

**Comment by tmcconechy** [comment]
@talkaboutdesign yep thats what it came out to https://github.com/infor-design/enterprise/pull/8057/files#diff-c64ff7d754d29ef30af42ea450255f1267a66c58eb2ae9b4fef121797c7779d1R280

**Comment by glenlieorillo** [comment]
Passed.

https://github.com/infor-design/enterprise/assets/102151352/1266aed1-a5ea-4dfd-b102-7e32665eb0e2
