### ISSUE TITLE
ExpandableRow: Component getting empty after cell change in soho-datagrid

### ISSUE THREAD

**Issue by SudarshanDivakarla** [infor-design/enterprise#8058]
**Is your feature request related to a problem or use case? Please describe.**

While working with soho-datagrid where have a requirement of Expandable Row. On the Expanded section, I have a component for displaying data in it. So, when the row is expanded, i can see the data in the expanded section but when i change a cell of the expanded row, the data is disappearing, and I can only see empty expanded section.

I am using **rowTemplateComponent** in grid options and providing a component (**ExpandableAreaComponent**) which has data in it.

On Cell change updating that row and reassigning the dataset to data grid for updating the summary row which is causing an issue with expandable section.

**Describe the solution you'd like**

**Requirement**:

-> User can expand particular row 
-> expandable section should be expanded and the data in the expanded section should be visible.
-> He can make changes on cell1, then cell 2 and cell3 of that row need to be updated with the values from the backend and simultaneously the summary row also needs to update.

**In this feature Request we need below Methods:**
-> Api to update summary row,
-> Expandable section to be expanded after updateRow() and the component which is given in rowTemplateComponent should be triggered and the data in the component should be visible.

**Please find the below stack blitz example for more information:**
https://stackblitz.com/edit/ids-quick-start-1671-q3e7sw?file=src%2Fapp%2Fdatagrid%2Fdatagrid.component.ts

**Steps to Reproduce:**
-> Expand particular row,
-> You can see some labels available in the expanded section.
-> change Cumulative Period Progress cell of the expanded row.
-> on tab the expanded section is expanded but the data in the expanded section is getting disappear, which shouldn't happen.

**Additional context**
<img width="712" alt="image" src="https://github.com/infor-design/enterprise/assets/94103218/11c554fc-5b21-4944-8b97-a5c39ba31034">

And what application do you work on?  **LN Enterprise Collaboration Portal**

**Comment by ericangeles** [comment]
Sure thing, @tmcconechy
