### ISSUE TITLE
ModuleTabs demo: page-container padding causing issue in website demo

### ISSUE THREAD

**Issue by jmacaluso711** [infor-design/enterprise#8060]
**Describe the bug**
An issue has been identified in the ModuleTabs demo, specifically related to the padding of the `page-container`, impacting the rendering of the website demo. There is `padding: 20px 0;` set on the `page-container` which affects the ModuleTab specifically, does not affect any other demos.

**To Reproduce**

1. Go to https://design.infor.com/code/ids-enterprise/latest/tabs-module
2. See error in the demo at the top of the page

**Expected behavior**
Module tab demo should render properly on the website

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![Screenshot 2023-09-28 at 4 53 09 PM](https://github.com/infor-design/enterprise/assets/1084735/c132be4b-42a4-4ee3-9ab8-7ec38c7c175b)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
n/a

**Comment by tmcconechy** [comment]
Strangely i cant see the issue on the actual page https://design.infor.com/code/ids-enterprise/latest/demo/components/tabs-module/example-index?theme=uplift&variant=light even if resizing the page
