### ISSUE TITLE
Datagrid: Error icon on hover inside a grid cell doesn't display error message on tooltip

### ISSUE THREAD

**Issue by hsubtain** [infor-design/enterprise#8071]
**Describe the bug**
In a grid when I add a new row and perform some validation and that validation returns an error and triggers a showCellError, the cell is populated with a error icon and a tooltip indicating error message, however when hovering over the error icon it doesn't display the error message unlike in other grid cell.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-index?theme=uplift&variant=light
2. Check `$('#datagrid').data().datagrid` in the dev console and and trigger a `$('#datagrid').data().datagrid.addRow({})`
-new row should be added to the grid with the first cell having the grey flag (i believe this is used for new rows)
3. In the dev console trigger a showCellError `$('#datagrid').data().datagrid.showCellError(0, 0, "TOOLTIP ERROR MESSAGE", "error");` and `$('#datagrid').data().datagrid.showCellError(0, 1, "TOOLTIP ERROR MESSAGE", "error");`
5. Hover over the error icons
-When hovering over the error icon of the first cell (where the grey flag is) error message is not shown, but when hovering over the error icon on the last cell error message is shown

**Expected behavior**
The error message should be displayed via tooltip when hovered over the error icon

**Version**
ids-enterprise: v4.82.1

**Screenshots**
Here is a GIF of the scenario for reference:

![tooltip_message_not_showing](https://github.com/infor-design/enterprise/assets/100820299/5d1388d4-6f9a-4f10-af9b-b40ea0001100)

**Platform**
Infor Application/Team Name: lawson
OS Version: Windows 11
Browser Name: Chrome
Browser Version: Version 117.0.5938.150 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@hsubtain would be helpful to create the example so it speeds this up and we get it right

**Comment by hsubtain** [comment]
> @hsubtain would be helpful to create the example so it speeds this up and we get it right

This is Noted @tmcconechy I'm working on this and will get back to you, on the meantime I've updated the steps to replicate. Thank you!
