### ISSUE TITLE
SearchField: Collapsible Search Has Strange Animation

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#8076]
**Describe the bug**
Would like to improve the animation.

**To Reproduce**
1. Go to  https://main-enterprise.demo.design.infor.com/components/datagrid/example-custom-toolbar-flex.html
2. Click on the search 
3. See error

**Expected behavior**
Would like to see it animate all in one direction out to the left all parts at one time. When it closes it animates right.
In RTL it does the inverse.

**Additional context**
Also add a collapsible search example to the searchfield pages for easier testing

**Comment by tjamesallen15** [comment]
I'll get this one @tmcconechy, if this becomes available since I'm familiar already with it. I might get it early if I finished my task as soon as possible.

cc @ericangeles

**Comment by tjamesallen15** [comment]
Thanks @ericangeles
