### ISSUE TITLE
Cards: Menu button on the upper left instead of the upper right on Classic version

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise#8081]
**Describe the bug**
The card's menu button is on the upper left using Classic version

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/cards/example-no-header.html?theme=classic&mode=light&colors=default
2. See error

**Expected behavior**
Menu button should be on the upper right

**Version**
- ids-enterprise: v4.88.0-beta.0

**Screenshots**
<img width="808" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/21304ff7-d162-49f2-9ac5-c3842b66ca3a">

Expected behavior (using example-index)
<img width="443" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/c1f9abfe-8fcf-4a85-8c0f-fb8dc4cbd087">

(using New version)
<img width="786" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/9bcc5cfe-94ae-47e9-827a-65094890f047">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@ericangeles maybe one for @RJ-Csc next time

**Comment by glenlieorillo** [comment]
Passed.

<img width="1791" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/2880b1d0-c0ea-4269-9194-82bfb7d97782">
