### ISSUE TITLE
Radios: The selected indicator (the "dot") is misaligned for a disabled radio

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#8082]
**Describe the bug**
When a selected radio button is disabled, the "dot" that indicates that the radio is selected is misaligned.

**FYI**: A related issue [(7899)](https://github.com/infor-design/enterprise/issues/7899) was fixed a while back but introduced this issue instead.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/radios/example-index
2. Open the browser dev tools
3. Locate the "Option four" element in the HTML tree
4. Add `checked="true"` to that element.

**Expected behavior**
The selected indicator should be correctly aligned for a disabled radio button.

**Version**

- ids-enterprise: `4.88`

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/63045013/3001f30f-af29-4e28-9f53-c2b5deaeaccd)

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by jbrcna** [comment]
this is now working in main. moving ticket to done
https://main-enterprise.demo.design.infor.com/components/radios/example-index
<img width="771" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/d496c747-b580-4f8d-a6c8-0b0b23f93ef3">
