### ISSUE TITLE
Datagrid: xss issue with datagrid lookup 

### ISSUE THREAD

**Issue by charantejpola** [infor-design/enterprise#8083]
**Describe the bug**
On selection of value in lookup inside a datagrid which has script values. The datagrid executes the script on selection.

**To Reproduce**
 1. Create a datagrid with a lookup column
 2. The lookup values has one of the option as follows "<script>alert("Hello World!")</script>".
 3. Select the lookup value option "<script>alert("Hello World!")</script>"
 4. Press any key/enter or do a mouse click
 5. You can see that script got executed and see a alert on the screen as in below screenshot

**Expected behavior**
As in the normal lookup the script value is sanitized and does not execute where as that doesnt happen in the lookup inside a datagrid.

**Version**
- ids-enterprise-ng: 16.8.1

**Screenshots**

![f3e3f700-4746-428a-9769-8274c4209424](https://github.com/infor-design/enterprise/assets/144307117/d8fd04fd-00cd-4428-bb9c-9de886569cca)

**Additional context**
Can refer to below stackblitz to get a better understanding.
https://stackblitz.com/edit/ids-quick-start-1681-m5wtu6?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

**Comment by jbrcna** [comment]
QA Passed
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-lookup-mask.html
<img width="1201" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/f312948e-abed-4bfc-9179-a024544937e1">
![Large GIF (1292x758)](https://github.com/infor-design/enterprise/assets/56722184/ed258f45-30c7-4068-9fc7-2939e1aca1de)
