### ISSUE TITLE
Toolbar: "More" menu in contextual toolbar has incorrect icon alignment and hover state

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#8084]
**Describe the bug**
The "..." icon in "more" menu buttons is misaligned when they're in a contextual toolbar. Additionally, in Light Theme, the hover state is also incorrect.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-editable.html
2. Select an item in the data grid
3. Hover the "more" menu.
4. Notice the hover state and the icon alignment.

**Expected behavior**
I assume the background color on hover should be the same as the 2 buttons in the contextual toolbar. The menu button icon should also be centered.

**Version**
- ids-enterprise: `4.88`

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/63045013/cae127f6-91b7-4f97-beb3-4a0758553ea1)

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by jbrcna** [comment]
QA Passed
<img width="1492" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/b7152ee5-3d39-42e5-9056-1f4fd88e7c34">
