### ISSUE TITLE
Toolbar Searchfield: Unable to expand a collapsible searchfield using the search button

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#8085]
**Describe the bug**
It's a bit difficult to expand (open) a collapsible toolbar searchfield which isn't empty.

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
2. Hover the search button on top example (notice it seems wide)
3. Click the search button to open the searchfield 
4. Type something
5. Click outside to collapse the searchfield
6. Try to open the searchfield again by clicking the search button
**Result**: It cannot be opened using the button. Instead, you need to click to the left of the button (in that "extra" space?)

**Version**
- ids-enterprise: v4.88.0

**Screenshots**
![toolbarsearchfield](https://github.com/infor-design/enterprise/assets/1101770/73971cc5-f089-45bf-ba89-b770747022c7)

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by tmcconechy** [comment]
Lets see on this after 4.89 as we did some work here on related search issues

**Comment by ericangeles** [comment]
It looks like the search icon should be on the left, and the text should be visible.

Correct one -> https://4850-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html

**Comment by yohannahbautista** [comment]
Hello, checking on https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html and it looks like it works now, though the focus border is off so I'll fix that one

**Comment by ericangeles** [comment]
Thanks, @yohannahbautista

**Comment by glenlieorillo** [comment]
Searchfield border is cut-off.
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/27668fb9-175b-4153-abde-5b1379e038ea">

X icon is not centered within the hover state.
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/b299f223-68af-47b9-ab04-4de2922f164a">

That should be look like this:
<img width="304" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/9aaa95e7-8baa-48c0-a568-67c4d403e1df">

**Comment by yohannahbautista** [comment]
This hasn't been merged yet though?

**Comment by jbrcna** [comment]
QA Passed
https://main-enterprise.demo.design.infor.com/components/toolbarsearchfield/example-flex-toolbar-align-with-searchfield.html
![Large GIF (1314x494)](https://github.com/infor-design/enterprise/assets/56722184/3b95ddd1-6fd5-4665-b4a1-a309312f23cb)
<img width="427" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/473fa0f8-8842-43c3-b1e1-6c2b2f5297f8">

**observation**
the issue of  x icon as seen [here](https://github.com/infor-design/enterprise/issues/8085#issuecomment-1820936993) still exists

<img width="407" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/a92aec4c-bf5c-4f33-8829-93f1b3b551db">
