### ISSUE TITLE
Page pattern: button color is off in dark mode

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8087]
**Describe the bug**

**To Reproduce**

1. Go to page-patterns/example-toolbar-datagrid.html?theme=new&mode=dark&colors=ffffff
2. Hover on Deployment button
3.  See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="821" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/628ae56b-a094-4ca1-92a2-96570963224d">

**Platform**
All major browser

**Additional context**
see also the color of header tabs in https://main-enterprise.demo.design.infor.com/components/page-patterns/example-toolbar-datagrid.html?theme=classic&mode=contrast&colors=ffffff
<img width="1628" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/114e1234-f14d-4750-869c-6831d99ea290">

**Comment by tjamesallen15** [comment]
Can you test this again @jbrcna, it seems okay to me. Thanks!

**Comment by jbrcna** [comment]
can confirm. thanks @jbrcna 
<img width="1707" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/be9c7db6-7453-48e2-8c61-d4a5ef6e3282">
However, when you change colors, the font of deployment label changes color as well. is this also expected?
<img width="1410" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/09e5bc67-54e7-407a-867f-ded56cbdf5f2">

**Comment by tjamesallen15** [comment]
Closing this ticket then.
