### ISSUE TITLE
Datagrid: Overlapping text/button

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8093]
**Describe the bug**
Overlapping text/button.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Notice the header

**Expected behavior**
Text and button should be rendered properly on mobile.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/89dc99fe-ece4-41b3-b7f6-2d548c1f3b43)

![image](https://github.com/infor-design/enterprise/assets/102151352/7582da48-9272-451f-8a75-7ba0157a522e)

![image](https://github.com/infor-design/enterprise/assets/102151352/2d296571-d063-4ed1-a283-62079e9507db)

**Platform**
 - Mobile devices: iOS and Android (tested in BrowserStack)

**Comment by tmcconechy** [comment]
This is basically a demo app bug. It would be fixed by replacing the toolbar with a flex toolbar in the example. Not very important.
