### ISSUE TITLE
Pager: Double pager showing when toggling the pager options in the grid

### ISSUE THREAD

**Issue by johnlouieserrano** [infor-design/enterprise#8094]
**Describe the Issue**
Currently on OAD, we have a wizard that previews possible options on the data grid. we have a switch that shows/hides the pager but has an issue when we toggle it.

**To Reproduce**
Steps to see the question or problem:
1. was able to replicate on this on stackblitz with our code: [STS-3748 - Double pagination options are showing for Records Page Widget (forked) - StackBlitz](https://stackblitz.com/edit/ids-quick-start-1671-4cztav?file=src%2Fapp%2Ftest%2Ftest.component.ts)

**What are you trying to do**
Jira Link : [STS-3748](https://jira.infor.com/browse/STS-3748) - Double pagination options are showing for Records Page Widget

**What did you try so far**
Current workaround was to hide it with css but it should not add another pager when the options is already true

**Version**

- ids-enterprise: v4.8.7

**Screenshots**
If applicable, add screenshots to help explain your question or problem.

**Platform**
 - Device : Browser
 - OS Version:  Windows 11
 - Browser Name only tested on edge
 - Browser Version : 118

**Comment by tmcconechy** [comment]
Maybe we add a hide/show pager method to resolve.
