### ISSUE TITLE
Calendar: Provide an Option to Use Mobile Legend in Both Views

### ISSUE THREAD

**Issue by JunyiZhao720** [infor-design/enterprise#8104]
**Is your feature request related to a problem or use case? Please describe.**
The mobile legend for the soho-calendar component is restricted to mobile views. We would like it to be accessible from desktop views as well.

**Describe the solution you'd like**
Consider adding an option to soho-calendar to enable the use of the mobile legend in both desktop and mobile views.

**Comment by tmcconechy** [comment]
Any reason why? Just making things inconsistent....

**Comment by JunyiZhao720** [comment]
> Any reason why? Just making things inconsistent....

We can agree to use the provided legend, but the existing legend styles differ too much between desktop and mobile views. We can accept using the mobile legend on both screens, but using the desktop version is definitely not an option. The main reason is that our design only supports a legend positioned at the bottom. If, for desktop, it appears as a sidebar on the left, that would break the existing design as far as I know.

**Comment by hey-yall** [comment]
Design resource ticket: https://jira.infor.com/browse/IDS-1822

**Comment by hey-yall** [comment]
Design has rejected this request and the corresponding Jira ticket is now closed. Please use existing desktop legend as designed.
