### ISSUE TITLE
Enhancement: 'Back' arrow button for Contextual Action Panel and Modal window

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#8112]
Contextual Action Panel and Modal window to have an option to have a 'Back' arrow button to go back to the previous page on the modal.

**Additional context**
https://jira.infor.com/browse/IDS-1317

**Task**

- make a CAP example like here https://main-enterprise.demo.design.infor.com/components/cards/example-workspace-widgets.html
- where it animates and shows a back button

**Comment by hey-yall** [comment]
Need more information from Maezelle and the original requestor. Waiting on a response.

**Comment by tmcconechy** [comment]
Ready to make an example for, all we want is an example like this:

![Screenshot 2024-01-23 at 9 06 32 AM](https://github.com/infor-design/enterprise/assets/814283/dda38878-dea6-452a-a8a8-3082c1b4e3d7)

For @maezcruz you could try to do it in your dev steam
