### ISSUE TITLE
Enhancement: KPI and Slim cards combined variant

### ISSUE THREAD

**Issue by maezcruz** [infor-design/enterprise#8113]
KPI and Slimcards are related thus them displaying side by side is important, the current challenge is that the slim cards are not aligning properly with the on your radar widget horizontally. 

We recommend an enhancement for the slim cards to have a default vertical size to compensate, this will display 3 slim cards by default and will be at the same size as the KPI widget, to achieve this we recommend using the vertical size of the slim cards when its displaying "3-line content".

Current behavior of the slim cards is that it automatically resize vertical height depending on the number of lines its content has, right now we recommend to only have 2-line content for simplicity but it means that the vertical height will be shorter which results to the alignment issue.

IDS Ticket for reference:
https://jira.infor.com/browse/IDS-1684

**Comment by tmcconechy** [comment]
I actually dont understand this one. Can you clarify? What are slim cards? As i see it you have two widget types that are totally different and look ok.

**Comment by ericangeles** [comment]
@tmcconechy, i think its the card list? https://main-enterprise.demo.design.infor.com/components/listview/example-card.html

**Comment by ericangeles** [comment]
@tmcconechy, I spoke with @maezcruz about this ticket. The two issues here are as follows:

1.) KPI tiles and slim cards (card list) should be on the same level position, meaning it should align horizontally. This is a side by side components so it is not combined (which I assume as well at first). Here's the screenshot

![issue](https://github.com/infor-design/enterprise/assets/8839327/71918f01-3503-4e3e-81f2-c96795aef173)

2.) Slim card contents – their use case is that they contain only two lines of content, and the goal is to make the cards the same height as a three-liner. To achieve this, I believe we need to set a minimum height of 94px. I also noticed a Figma design where both two and three-liner contents had the same height of 94px. https://www.figma.com/file/DxLvQRUlFFEf5cTuEICEEM/Widget-Enhancements-(documentation)?node-id=384%3A9328&mode=dev
