### ISSUE TITLE
Counts: Number and label text overlapping

### ISSUE THREAD

**Issue by max-hizon** [infor-design/enterprise#8121]
**Describe the bug**
Number and label text overlaps each other

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/counts/example-index.html
2. See error

**Expected behavior**
Texts should not overlap

**Version**
- ids-enterprise: v4.88.0-beta.0

**Screenshots**
<img width="778" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/4e34828c-c5bc-4441-9785-4b95ee206bb6">

Works properly on previous version: https://4870-enterprise.demo.design.infor.com/components/counts/example-index.html
<img width="838" alt="image" src="https://github.com/infor-design/enterprise/assets/79514236/36e8d35b-0eec-4a73-ba7f-df384f970f39">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by jbrcna** [comment]
this is now working as expected
verified in https://main-enterprise.demo.design.infor.com//components/counts/example-index.html
<img width="1554" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/87d4ea9f-c72b-453a-a95d-ecb1b7517b83">
