### ISSUE TITLE
Modal: Textarea width is too large on small windows

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#8125]
**Describe the bug**
The width of textareas is too large when they're in a modal and the browser window width is less than (but still close to) or equal to 400px ~as well as in Safari regardless of window size~.

**To Reproduce**

~**Scenario 1**~
~1. Open Safari and go to https://design.infor.com/code/ids-enterprise/latest/demo/components/modal/test-validation-error-tooltip.html~
~2. Click on "Add Context"~
~3. Notice the textarea width~

Scenario 1 has been fixed

**Scenario 2**
1. Open any browser and go to https://design.infor.com/code/ids-enterprise/latest/demo/components/modal/test-validation-error-tooltip.html
2. Decrease the window width to 400px or less (but still close to 400px)
3. Click on "Add Context"
3. Notice the textarea width

**Expected behavior**
The textarea width should be the same as the other inputs.

**Version**
- ids-enterprise: `4.88`

**Platform**
 - Infor Application/Team Name: Homepages
 - Browser Name: ~Safari or~ any browser when the browser window width is <=400px

**Additional context**
~Caused by [this rule](https://github.com/infor-design/enterprise/blob/0c1cc7062c60cd1135cb5ea11226062c7272fb23/src/components/modal/_modal.scss#L707-L714) in the Safari scenario~ and [this rule](https://github.com/infor-design/enterprise/blob/0c1cc7062c60cd1135cb5ea11226062c7272fb23/src/components/modal/_modal.scss#L123-L124) in the other scenario.

**Comment by lucacolumbu** [comment]
@radovaniljic we are not able to reproduce this

**Comment by radovaniljic** [comment]
@lucacolumbu the issue on Safari seems to have been fixed, but I can still reproduce this in the other scenario. I'll update my description, the window width needs to be less than <= 400px but still close to it.

![image](https://github.com/infor-design/enterprise/assets/63045013/c845a2f5-969a-41b1-a370-1f63305f7f9f)
