### ISSUE TITLE
Personalization: Read only has dark background color in personalized headers.

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#8130]
**Describe the bug**
Read only has dark background color in personalized headers. The background color doesn't match well with the corresponding color. Label color also seems off for inputs.

**To Reproduce**

1. Go to http://localhost:4000/components/personalize/example-form-landmark2.html?theme=new&mode=dark&colors=8D0B0E
2. Add readonly input to context form
3. Change colors in dark theme. See issue.
4. See issue

![image](https://github.com/infor-design/enterprise/assets/1056684/14db2a7e-a732-4511-be23-889810ec84a8)

**Expected behavior**
Should maybe look more like this?
![image](https://github.com/infor-design/enterprise/assets/1056684/39c362e4-40ec-48c2-988c-d12f550aa48f)

**Version**
4.88.0-beta.0

**Platform**
 - Chrome
 - Windows 11

**Comment by tmcconechy** [comment]
@krishollenbeck for what its worth we no longer recommend this pattern https://github.com/infor-design/enterprise/issues/7861 - basically for all the problems it can cause like this.

But will review with design as we do support it

**Comment by lucacolumbu** [comment]
This pattern is deprecated. We'll be closing this issue.
