### ISSUE TITLE
Datagrid: Add ability to personalize column groups

### ISSUE THREAD

**Issue by bveerabathini** [infor-design/enterprise#8138]
**Describe the bug**
Personalization for column groups in datagrid is not present. Need the personalization for the column groups.

**To Reproduce**
Applied this columnGroups for SohoDataGridOptions.

```
 columnGroups: [{ colspan: 1, id: '', name: ''},{ colspan: 1, id: '', name: 'Claim (Line) Number'},
        {colspan: 1, id: '', name: 'Cost Type'},{colspan: 2, id: '', name: 'Costs'},
        {colspan: 2, id: '', name: 'Item'}, { colspan: 1, id: '', name: 'Serial Number'},
        {colspan: 1, id: '', name: 'Status'}, { colspan: 1, id: '', name: 'Creation Date'},
        {colspan: 2, id: '', name: 'Breakdown Date'}],
      toolbar: {title: '', actions: true, results: true, personalize: true },
      saveUserSettings: {
       columns: true,
       rowHeight: true,
       sortOrder: true,
       filter: true
     },
```

**Steps to reproduce the behavior**
Personalization is not present for column groups in toolbar.

**Expected behavior**
Personalization should present for column groups in toolbar.

**Version**

- ids-enterprise: v4.87.0

**Screenshots**
<img width="689" alt="image" src="https://github.com/infor-design/enterprise/assets/85981034/b6e3c3ec-7303-4167-ad69-596228266105">
<img width="679" alt="image" src="https://github.com/infor-design/enterprise/assets/85981034/d4cb2041-4672-4df2-adf1-26e38a6a7fba">

**Platform**
 - Infor Application/Team Name: Infor LN 
 - Device: PC
 - OS Version: Windows 11 Enterprise
 - Browser Name: Chrome, Edge
 - Browser Version: Version 118.0.5993.118 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
This might be quite time consuming to add. We plan on enhancing the personalization dialog in the new Web Component version. Would it work if we only add this on the new version in the future?

**Comment by tmcconechy** [comment]
See https://jira.infor.com/browse/IDS-1616

**Comment by inforandy** [comment]
design here: https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=660-14205&mode=design&t=dTVyX0BpID4jDA6Y-0

**Comment by yohannahbautista** [comment]
Hello, checking on IDS and IDS NG and it looks to be working at present:
For IDS: https://main-enterprise.demo.design.infor.com/components/datagrid/example-grouped-headers.html

For NG: added the toolbar settings for this demo page http://localhost:4200/ids-enterprise-ng-demo/datagrid-groupedheader
<img width="697" alt="image" src="https://github.com/infor-design/enterprise/assets/85279127/9bc19900-21bd-43b7-b50c-d434ddb165f1">

**Comment by tmcconechy** [comment]
@ericangeles the design is here https://www.figma.com/design/JZdeun4ht1IsqZpV9xAW8Y/Colors?node-id=660-14205&t=Gr6LgNoMB2NC3EOC-0

Regarding grouped parents: I think they are not ever draggable when in the grid. But may be a case for refining it in the dialog. So might be best to use the `draggable` setting to determine if the column should show the drag indicator.
