### ISSUE TITLE
Datagrid: Tab Key Navigation issue

### ISSUE THREAD

**Issue by sathishchittimi** [infor-design/enterprise#8141]
**Describe the bug**
Tab navigation in the soho-datagrid is not working as expected.

**To Reproduce**

1. Download the attached Zip file. Extract and add this folder into Visual studio code. 
2. Open terminal for this folder.
3. Type "cd src" and press Enter.
4. Type "npm install --force" press Enter and later type "ng serve" press Enter.
5. Once it is compiled successfully. Open browser and type localhost:4200
6. Click on "Add Row" Button on the Top Right Side Corner. New Empty row will be inserted in the datagrid.
7. Type any text, lets say "1" on the "SourceValueTitle" column and press Tab
     Issue 1: After pressing the Tab instead of navigating to Next column, value "1" on the SourceValueTitle column gets highlighted. 
                  And again we need to Press Tab (Second Time) to navigate to Next Column, which is TargetValueTitle.

8. Type any text, lets say "1" on the "TargetValueTitle" column and press Tab
     Issue 2: After pressing the Tab instead of navigating to Next column, value "1" on the TargetValueTitle column gets removed. 
                  And if we press Downward arrow mark Key, Values of the AssignmentTypeTitle column DropDown values appears, which 
                  is not correct. again we need to Press Tab (Second Time) to navigate to Next Column, which is AssignmentTypeTitle.

9. Select any value using dropdown keys, for the "AssignmentTypeTitle" column and press Tab
     Issue 3: After pressing the Tab instead of navigating to Next column, value gets stored on the AssignmentTypeTitle column, but 
                  "SkipToMain" Header will appear on the Top Left side Corner.
      

**Expected behavior**
Follow the same steps mentioned on the "Steps to reproduce the behavior" with below changes and Tab navigation is working as expected.
1. In the Package.json file change "ids-enterprise-ng", "ids-enterprise-typings" versions like below
2. "ids-enterprise-ng": "13.4.4",
    "ids-enterprise-typings": "13.4.4",
3. In the terminal Run "npm install --force" command and "ng serve" command.

**Version**
Issue is appearing after
"ids-enterprise-ng": "13.5.*",
"ids-enterprise-typings": "13.5.*",

Tab Navigation is working successfully till
"ids-enterprise-ng": "13.4.4",
"ids-enterprise-typings": "13.4.4",

Node Version: 18.16.1 for both
Angular Version: latest

**Screenshots**
PFA Video
[tab-key-navigation-issue-MP4.zip](https://github.com/infor-design/enterprise/files/13263554/tab-key-navigation-issue-MP4.zip)

**Platform**
All

**Source Code**

[tab-key-navigation.zip](https://github.com/infor-design/enterprise/files/13263549/tab-key-navigation.zip)

**Comment by tmcconechy** [comment]
Keep in mind (for anyone that picks this up). That for tab navigation you need to hit f2 or set actionable mode on.
