### ISSUE TITLE
Preview - Accent colors - Default shows azure in color selector, and should alabaster be kept as an option?

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#8151]
**Describe the bug**
This is related to the preview/dev build, using alabaster as default. These are the colors returned from `Soho.theme.personalizationColors()` in Light mode, which we use to build the color selector (dropdown is-swatch)

```
{
    "default": {
        "id": "default",
        "name": "Default",
        "backgroundColorClass": "primary-bg-color", <--- This seems to have wrong value
        "value": "#0066D4" <--- Should this be white?
    },
    "alabaster": {
        "id": "alabaster",
        "name": "Alabaster",
        "backgroundColorClass": "alabaster",
        "value": "#ffffff"
    },
  // ... rest of accent colors
}
```

![image](https://github.com/infor-design/enterprise/assets/1101770/0943551a-2a04-432b-9dc9-01d1d44f3496)

`primary-bg-color` in effect on the option
![image](https://github.com/infor-design/enterprise/assets/1101770/ec020088-65b3-4217-9cf2-62fe3b739980)

**To Reproduce**
I couldn't find the dev build deployed, but should be reproducible in an example that uses the swatch dropdown.

**Expected behavior**
`primary-bg-color` should be white. And will alabaster still be kept as a personalization color? We could filter it out if we want to avoid duplicates (Default & Alabaster), with a fallback to default if alabaster has previously been selected, so more of a question.

**Additional context**
The default value itself works fine, i.e. headers/subheaders/tabs get alabaster. It's just the representation of it in the swatch.

**Version**
- ids-enterprise: v4.89.0-dev.0
 
**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by tmcconechy** [comment]
FYI a deployed version is here https://preview-enterprise.demo.design.infor.com/components 
Will add a fix now for this
