### ISSUE TITLE
Breadcrumb overflow menu doesn't fire any event or call the callback function.

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#8154]
**Describe the bug**
unable to get a callback message when a breadcrumb in overflow is clicked

**To Reproduce**
1. Go to http://localhost:4000/components/breadcrumb/example-add-remove.html
2. Click on the Add button to create enough crumbs that there is an overflow
3. Open the overflow and click one
4. Notice when clicking an overflow item that the callback is not executed.

If you click on a crumb not in overflow notice the change in Last-Clicked Breadcrumb is updated.

**Expected behavior**
callback function should get messaged when click on a breadcrumb in overflow.

**Version**
- ids-enterprise: 4.87.0, 4.88.0

**Platform**
 - Infor Application/Team Name: Landmark
 - OS Version: Windows 11
 - Browser Name: latest chrome

**Comment by glenlieorillo** [comment]
This has been tested and passed.


https://github.com/infor-design/enterprise/assets/102151352/047f8556-ed16-475e-931f-8a3fb6a5b43e
