### ISSUE TITLE
Datagrid: Increasing number of spaces when clicking in and out of cell

### ISSUE THREAD

**Issue by jvang01** [infor-design/enterprise#8155]
**Describe the bug**
In a grid, when I enter a space into an editable cell, click out of the cell, and then click back into the cell, the number of spaces multiply.

**To Reproduce**

1.  Go to https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-editable.html
2.  Click on the blank cell in Row 2, under Product Name
3.  Type a space
4.  Click in and out of the cell multiple times

**Expected behavior**
The single space should persist.  Instead, the space increases with each click into the cell.

**Version**

- ids-enterprise: 4.82.1

**Screenshots**
![datagrid-multiplying-spaces](https://github.com/infor-design/enterprise/assets/64548726/9d4631da-3f6e-415e-9a52-c865f8d3edf4)

**Platform**
 - Infor Application/Team Name: Lawson
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 119.0.6045.106 (Official Build) (64-bit)

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
<img width="1288" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ff217dae-6cd1-4aa4-9ca6-3b4c3f96556d">
