### ISSUE TITLE
Datagrid: Server side pagination, manual page navigation calls API twice

### ISSUE THREAD

**Issue by wreighsantos** [infor-design/enterprise#8156]
**Describe the bug**
Manually changing pages in Datagrid results to duplicate API calls.

**To Reproduce**

This behavior can be observed in https://design.infor.com/code/ids-enterprise/latest/demo/components/datagrid/example-paging?theme=uplift&variant=light

Monitor the network activity and then try manually jumping from page to page (e.g., enter a number in the active page field and then hit enter)
 
Notice that there will be 2 identical network calls. This does not happen when moving from page to page with previous and next.

**Expected behavior**
There should only be 1 API call per page navigation

**Version**

- IDS Enterprise Components - v4.88.2

**Platform**
 - OS Version: Windows 11
 - Browser Name: Microsoft Edge for Business
 - Browser Version: Version 119.0.2151.44 (Official build) (64-bit)

**Comment by jbrcna** [comment]
QA Passed
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/example-paging
<img width="1713" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/782fd25c-796a-483d-9c7d-c7cda6b889c7">
