### ISSUE TITLE
Sinkpage: Charts - Legend color positioning issue

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8159]
**Describe the bug**
Focus state overlaps with legend color (Classic).

**To Reproduce**

1. Go to https://4890-beta0-enterprise.demo.design.infor.com/?theme=classic&mode=light&colors=default
2. Scroll down to Charts: Vertical Bar Chart, Stacked Bar - Vertical, Stacked Bar - Vertical 100%, Grouped Bar Chart, Line Chart, and Area Chart
3. Click on legends

**Expected behavior**
Focus state and legend color should not overlap.

**Version**

- ids-enterprise: 4890-beta0

**Screenshots**
<img width="796" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/6d1d5bcb-7f74-426e-9327-c3aa9d8e627f">

<img width="796" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/4569afab-7200-4226-b7e7-58bc7da6382e">

**Platform**
 - All major browsers

**Comment by jbrcna** [comment]
QA Passed
verified in https://main-enterprise.demo.design.infor.com/?theme=classic&mode=light&colors=default
<img width="1073" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/a2d5d764-e672-4b0f-b33b-2f5da62ea55b">
<img width="1067" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/4f2d2f2a-9106-4fab-9953-fef9dafd11a2">
