### ISSUE TITLE
Breadcrumb: Misaligned item in RTL on safari

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8167]
**Describe the bug**

**To Reproduce**

1. Go to https://preview-enterprise.demo.design.infor.com
or https://4890-beta0-enterprise.demo.design.infor.com in safari
2. switch to RTL
3. Scroll down to  breadcrumb component

**Expected behavior**

**Version**

- ids-enterprise: v4.89.0-beta0 & preview version

**Screenshots**
<img width="496" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/60405b13-b52e-4082-a5a1-268ccf9371a9">

**Platform**
Safari

**Additional context**
maybe related to https://github.com/infor-design/enterprise/issues/7573

**Comment by tmcconechy** [comment]
Hmm this one im not seeing https://4890-beta0-enterprise.demo.design.infor.com/components/breadcrumb/example-index.html?locale=ar-SA

**Comment by jbrcna** [comment]
please try to use a safari browser. no extra steps needed. I have updated the ticket. 
https://4890-beta0-enterprise.demo.design.infor.com/components/breadcrumb/example-index.html?locale=ar-SA
<img width="1607" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ac37dd48-0cd8-4658-987c-3bad02e85ded">

**Comment by jbrcna** [comment]
QA Passed
verified in https://main-enterprise.demo.design.infor.com/components/breadcrumb/example-index.html?locale=ar-SA
<img width="1138" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/2414f6bd-cc27-4584-805e-371063bf5a2f">
