### ISSUE TITLE
Datagrid: Different options based on each lines in a dropdown in a Grid ? 

### ISSUE THREAD

**Issue by ismail-spoon** [infor-design/enterprise#8187]
**Describe the Issue**
Is it possible to add different options values based on the value from a column in each rows in a Dropdown column in a Datagrid? 

**What are you trying to do**
I have an editable datagrid with different columns, one of the column is a dropdown. 
An array of object (label, value) is assigned to this column. What I want is to filter the values of this array based on the value of another column in the same row. 

e.g
Array: [{label: "A", value: "A"},{label: "B", value: "B"}]

If column Item in a row is "ITEM01", only option {label: "A", value: "A"} should be displayed in the dropdown column. 
If column Item in a row is "ITEM02", both options should be displayed in the dropdown column. 

**What did you try so far**
I tried modifying the options of the dropdown when the row is clicked but the update function updates the entire grid which is not optimal.
`
          COLUMNS[contractIndex] = this.initColumn({
              field: 'POOURR',
              name: 'poourr',
              filterType: 'text',
              editor: Soho.Editors.Dropdown,
              maxLength: 10,
              options: AGNBArray,
            });

            columns = COLUMNS.map((column: SohoDataGridColumn) =>
              this.initColumn(column)
            );

            this.columns = columns;

            this.datagridOptions.columns = this.columns;
            this.datagrid.updated(this.datagridOptions);
`

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/95227711/9d465e0d-417f-4f0e-a323-6e00aae74afc)

**Version**

 -  "ids-enterprise-ng": "^14.7.1",

**Comment by tmcconechy** [comment]
Yes you can do that. We called it cascacing dropdowns. But basically you just provide a function that has the logic for each line.

https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/test-cascading-dropdowns.html#L53

Then implement it. In the example https://main-enterprise.demo.design.infor.com/components/datagrid/test-cascading-dropdowns.html the dropdown is different for each cell based on the status.

HTH

**Comment by ismail-spoon** [comment]
Indeed it was the solution is was searching for. 
Thank you so much for your help.
