### ISSUE TITLE
Busy Indicator Update Issues with Apostrophes

### ISSUE THREAD

**Issue by rvaja-infor** [infor-design/enterprise#8189]
**Describe the bug**
An issue has been observed where the text of a running busy indicator when updated displays as the same as what is set on the 'text' property of the the options, e.g. escaped characters are not unescaped when displayed. The escaping is done from the calling application

**To Reproduce**
Navigate to https://stackblitz.com/edit/ids-enterprise-4880-h6ottf?file=index.html and click the 'Start Busy Indicator' button

**Expected behavior**
The expected behaviour is after calling the #updated on a busy indicator the value should render as 
"VÃ©rification du statut de l'utilisateur"

**Version**
- ids-enterprise: [e.g. v4.88.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/45232365/f491f4d2-c89b-4b85-9dea-f86522dfdd92)

**Platform**
 - Infor Application/Team Name: Infor SunSystems
 - Device: Laptop
 - OS Version: Windows 11
 - Browser Name: Chrome/Edge
 - Browser Version: Latest

**Additional context**

**Comment by rvaja-infor** [comment]
Quick note, not sure if after calling #updated you need to perform a trigger for triggering 'updated.busyindicator'. I tried this as well but seemed to completely remove the indicator. May not be working as intended.

**Comment by glenlieorillo** [comment]
QA Passed.

![image](https://github.com/infor-design/enterprise/assets/102151352/0f50f638-375c-4b31-84d0-06a52eb3b7aa)

**Comment by rvaja-infor** [comment]
@ericangeles / @glenlieorillo is there an update to the original StackBlitz page I provided where any additional calls need to be made or will the page I provided work out the box with latest fix out the box.

**Comment by ericangeles** [comment]
@rvaja-infor, once we publish version 4.90 in early December, you will need to use 4.90 instead of the version you provided. You won't need to change anything in your code; simply update it to 4.90 once we have published it.
