### ISSUE TITLE
Scatterplot: legend items not centered

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8194]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/scatterplot/example-index.html
2. Click on Legend items
3. See error

**Expected behavior**
should be centered 
<img width="420" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/4d90bd1a-3e0b-4938-8cb8-e4160662920b">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="349" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/e9cc1b42-b86f-4be0-ad87-a71976a71163">

**Platform**
all maor browser

**Additional context**

**Comment by glenlieorillo** [comment]
This is now working as expected.

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/ce02af2d-4c0e-433b-9fa1-3cbda0b8c68c">
