### ISSUE TITLE
Translation:  "NoResultsFound" is not translated

### ISSUE THREAD

**Issue by adamzhang1932** [infor-design/enterprise#8196]
I am an employee in Infor company, our product is SunSystems and we are now using IDS.

I found that "NoResultsFound" is only existed in "/src/components/locale/cultures/en-US.js", could you please translate this key to other culture files(such as af-ZA,js, ar-EG.js and so on)?

<img width="553" alt="NoResultsFound_need_translation" src="https://github.com/infor-design/enterprise/assets/151612185/9f2ef4a7-20e7-4042-a4df-80d0916ebe34">

<img width="851" alt="NoResultsFound_need_translation_en-US" src="https://github.com/infor-design/enterprise/assets/151612185/700c35f2-bf0f-41df-b487-256a3069e4e1">

**Comment by tmcconechy** [comment]
@hwondergem can you check `NoResultsFound` im not sure how new that is but i thought it was translated. Thanks!
@adamzhang1932 note that now we have separate locale and translation files

**Comment by hwondergem** [comment]
@tmcconechy, yes, these are translated in our latest delivery, like:
\\nlbavwmemoq2\cc\ToDev\SohoUX\zh-CN-messages.ts	61,389	11/16/2023 16:34

de:   NoResultsFound: { id: 'NoResultsFound', value: 'Keine Ergebnisse gefunden', comment: 'Search Results Text' },
zh:   NoResultsFound: { id: 'NoResultsFound', value: '找不到结果', comment: 'Search Results Text' },

**Comment by hwondergem** [comment]
Yes, it's complete now @tmcconechy

**Comment by adamzhang1932** [comment]
Many thanks to your help.
