### ISSUE TITLE
Datagrid: Frozen columns when dragged get out of sync

### ISSUE THREAD

**Issue by spendker** [infor-design/enterprise#8198]
**Describe the bug**
Bug is seen in Soho-Datagrid frozen column. If you drag a frozen column, it will not be dragged in the table but in Personalize Column section it position gets changed. The grid malfunctions when non-frozen columns is show/hide.

**To Reproduce**
[Project Code.zip](https://github.com/infor-design/enterprise/files/13435470/Project.Code.zip)

[Issue Steps.docx](https://github.com/infor-design/enterprise/files/13435463/Issue.Steps.docx)

**Expected behavior**
Frozen column position should not be changed in Personalize Column section.
When non-frozen column is either show/hide the grid should show/hide the particular column.

**Version**
- ids-enterprise: 16.7.1

**Screenshots**
[Issue Steps.docx](https://github.com/infor-design/enterprise/files/13435463/Issue.Steps.docx)

**Platform**
 - OS Version: Windows 11
 - Browser Name: Google Chrome
 - Browser Version: 119.0.6045.160

**Additional context**

**Comment by tmcconechy** [comment]
My suggestion is to not allow frozen columns to be draggable by setting `reorderable: false` that should solve the issue i think. But the steps are pretty long 11 pages 🤯 

Can it be simplified to say if you reorder the frozen column then the personalization dialog is incorrect?

**Comment by spendker** [comment]
Hi @tmcconechy ,

I followed your suggested step i.e not allow frozen columns to be draggable by setting "reorderable: false". The problem is if I am dragging non frozen column in place of frozen column then also personalization dialog changing it's order.

**Comment by tmcconechy** [comment]
@spendker what do you mean re dragging a non frozen column?

**Comment by glenlieorillo** [comment]
This is now working as expected.


https://github.com/infor-design/enterprise/assets/102151352/93cb7d68-3575-4655-b8cd-0a5320c61504
