### ISSUE TITLE
Widget/Card: Flickering hover effect after homepage layout refresh

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#8201]
**Describe the bug**
This is a strange one, a bit difficult to describe. But it seems that, for "bordered" widgets, its hover effect changes after the homepage layout has been updated/refreshed. It should have a subtle hover effect, but the hover effect flickers from darker/thicker border to the "correct" one. 

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/cards/example-workspace-widgets.html
2. Hover any of the bordered widgets
3. See that hover effect looks OK
4. Resize the window to trigger a homepage layout refresh/recalculation
5. Hover any of the bordered widgets
**Result**: The hover effect is now different and flickering.

**Expected behavior**
No flickering hover effect, i.e. same hover effect as when homepage first rendered. We trigger a homepage layout refresh upon load, so we always get this strange hover effect on workspaces in Portal.

**Version**
- ids-enterprise: v4.89.0

**Screenshots**
Before homepage layout refresh
![widget-hover-ok](https://github.com/infor-design/enterprise/assets/1101770/fbd4f21b-510d-4c2b-99d0-9f0d2c116715)

After layout refresh
![widget-hover](https://github.com/infor-design/enterprise/assets/1101770/e923b12d-746d-46d9-8b38-5fc565160a65)

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by tmcconechy** [comment]
I couldnt get the animation css quite right. I know what you mean. I will get someone else to try it if not we may have to remove the animation. I think it cant correctly transition what it needs to over multiple rules.

**Comment by volante007** [comment]
Looks OK though unless triggering a homepage layout update, so also curious what might differ after that has happened?

**Comment by tmcconechy** [comment]
Ok i see. Seems like adding box-shadow  / vs all to  none to the inline dynamic rule works

```
element.style {
    cursor: auto;
    transition: box-shadow 0.3s cubic-bezier(0.09, 0.11, 0.24, 0.91) 0s; */
    left: 376px;
    top: 0px;
}
```

**Comment by volante007** [comment]
That was quick, thanks a lot!

**Comment by jbrcna** [comment]
QA Passed
verified in https://main-enterprise.demo.design.infor.com/components/cards/example-workspace-widgets.html
![Large GIF (1148x544)](https://github.com/infor-design/enterprise/assets/56722184/dfeb5b01-d5ac-4883-bf8c-54aef00fc31f)
