### ISSUE TITLE
BarChart: Issues with duplicate dataset elements

### ISSUE THREAD

**Issue by AmilaViduranga** [infor-design/enterprise#8209]
**Describe the bug**
When the user tries to display a duplicate key-contained dataset as a bar chart it gives an error

![MicrosoftTeams-image (8)](https://github.com/infor-design/enterprise/assets/13863481/2df70030-736d-420d-8e6b-9fe7c5572a51)

**To Reproduce**

1. Create a dataset with duplicate keys.
2. Assign that created dataset property, give type as "bar" under options of chart
3. observe the result

**Expected behavior**
It gives an error

**Version**

- ids-enterprise-ng: 16.8.1

**Screenshots**

**Platform**
 - Infor Application/Team Name: IAD
 - Device: Dell Laptop
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: Version 119.0.6045.160 (Official Build) (64-bit)

**Additional context**
Go through this MS team chat for more details
https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1700742211443?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1700742211443&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1700742211443

**Comment by glenlieorillo** [comment]
This is now working as expected.


https://github.com/infor-design/enterprise/assets/102151352/20b2d00b-2594-45a3-ab50-a70dd930d44a
