### ISSUE TITLE
Homepage control does not allow 3 or 4 rows

### ISSUE THREAD

**Issue by karinpb** [infor-design/enterprise#8211]
**Describe the bug**
We have received a bug ticket for portal that the Homepages control can only add widgets that are two columns high. There are scenarios when you want to use the Related Information viewer widget to view a full document and you need to read the document and even if you have more space in your insight group there is no way to get a widget span 3 rows and 2 columns and then add more widgets next to it. The hight is really important when reading documents.

Note: It has nothing to do with columns. The issue is the limit of the ROWS.
**To Reproduce**
Check the API for the Homepages control, there is no option to set 3 or 4 rows which is what we need. 

**Expected behavior**
I expect that it is possible to add a widget with height 3 rows and then have the algoritm try and fill all the available space with widgets. If there are empy spaces when widgets does not fit, then that is OK, You would have to build the workspace in a way that fits your most common screen size.

**Version**
- ids-enterprise: 4.88.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/7961438/0f390d57-b78d-4217-b3a8-cb272035fd45)

**Platform**
 - Infor Application/Team Name: OS Portal
 - Device: (if applicable) -
 - OS Version: Windows 11
 - Browser Name: All browsers
 - Browser Version:: '

**Additional context**
This is a blocker for one of our customers but we are also dicussing other options, like adding an icon to the smart panel and have the Information viewer in full screen, in which case we don't need this change. But I still wanted to add the ticket for the feedback, as it could be usable to be able to set more rows for others.

**Comment by talkaboutdesign** [comment]
We should explore this. But this alone might not be enough to satisfy the use cases. @karinpb we could make a default behavior in the smart panel that resizes the widget automatically take up full height or in case of detached panel and a single widget we might need that widget to take up full width and height of the window. It gets complicated when you have multiple widgets. I think before we jump into code, we should explore this on design side, come up with a solid solution, and then divide the responsibilities. There are other related design asks for smart panel, that can impact this.

**Comment by hey-yall** [comment]
Design ticket here: https://jira.infor.com/browse/IDS-1863

**Comment by tmcconechy** [comment]
Ok this is good to go!
