### ISSUE TITLE
Widget: Border and Borderless widget title alignment

### ISSUE THREAD

**Issue by Rajashekharkurva24** [infor-design/enterprise#8212]
Seems to be a vertical difference in those samples as well, albeit small (1-2 pixels?), for the title in borderless vs. bordered.

https://main-enterprise.demo.design.infor.com/components/cards/example-workspace-widgets.html

**Comment by Rajashekharkurva24** [comment]
Post:
https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1700643284249?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1700643284249&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1700643284249

**Comment by tjamesallen15** [comment]
It seems all of the widgets are correctly sized 360x368. Can we retest this one @infor-design/qa ? Thanks

**Comment by jbrcna** [comment]
<img width="485" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/04782334-3362-4c58-a751-3924f91d8907">
<img width="405" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/145a8e54-82f9-44b4-b3ce-e2a58a7d3bba">

**Comment by jbrcna** [comment]
the widget itself is the same see below
<img width="875" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/aaaf1be9-f13b-43ce-a33d-c18aeaa3b8de">

**Comment by tmcconechy** [comment]
@jbrcna does that mean it passes or fails ?

**Comment by jbrcna** [comment]
@tmcconechy , I am uncertain. but if the size in question is the widget content and widget header (https://github.com/infor-design/enterprise/issues/8212#issuecomment-1886351684) then it's failed. they are not the same exact size. if it is the widget itself, it is passed (https://github.com/infor-design/enterprise/issues/8212#issuecomment-1886360452)

**Comment by tmcconechy** [comment]
Oh i see. yes i think its still there @jbrcna @tjamesallen15 its really really subtle just a pixel between border and borderless for the title alignment maybe?

On https://main-enterprise.demo.design.infor.com/components/cards/example-workspace-widgets.html You can sort of see it here:

<img width="776" alt="Screenshot 2024-01-11 at 9 30 15 AM" src="https://github.com/infor-design/enterprise/assets/814283/48fffa10-5cee-4ff5-a973-71b5ce8eacf2">

Try making an example like the post with the same text and it may be more obvious:

![Screenshot 2024-01-11 at 9 30 50 AM](https://github.com/infor-design/enterprise/assets/814283/ecbe4162-332a-46c3-947b-f84685b3f735)

**Comment by jbrcna** [comment]
this is now working as expected.
<img width="574" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/7fa34e07-5257-4549-bf36-28ba9aaf1af3">
<img width="483" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/f3fec7fc-cadc-405b-b9d7-7bfc981ceba6">
