### ISSUE TITLE
Readme Updates: Broken Links 

### ISSUE THREAD

**Issue by hey-yall** [infor-design/enterprise#8217]
Hi dev team! 

On 30 Nov 2023, the design.infor.com scrum group is completing a migration of website content from Wagtail to Wordpress. Some of the new pages pull code documentation from the readme files, and I noticed during content QA that we have some broken links. 

We would love to have these broken links addressed before 30 January 2024. The comprehensive list is below. Please reach out to me, Laken Renick (@hey-yall) with any questions. 

**ALL PAGES**
- [ ] Testability section - Application Testability Checklist link is broken

**Components>Action Sheet**
- [ ] 	Code section, Popupmenus link is broken 
- [ ] 	Changing Breakpoints section, IDS Breakpoint link broken

**Component> Alert**
- [ ] 	Status and alert icons, See icons component link must be updated 
- [ ] 	Code example section, Badges link is broken

**Breadcrumb**
- [ ] 	Breadcrumb Positioning section, In Header and Below Header links are broken

**Button**
- [ ] 	Code Example section, popmenu link is broken
- [ ] 	Keyboard Shortcuts section, popupmenu link is broken 

**Context Menu**
- [ ] 	Code Example section, popmenu link is broken
- [ ] 	Coding Tips section, popup menu link is broken 

**Data Grid**
- [ ] 	Formatters table, RowReorder row, Example link broken
- [ ] 	Formatters table, Editor row, Example link broken
- [ ] 	Formatters table, Expander row, Example link broken
- [ ] 	Formatters table, GroupRow row, Example link broken
- [ ] 	Formatters table, GroupFooterRow row, Example link broken
- [ ] 	Formatters table, SummaryRow row, Example link broken
- [ ] 	Formatters table, Tree row, Example link broken
- [ ] 	Formatters table, TargetedAchievement row, Example link broken
- [ ] 	Formatters table, RowNumber row, Example link broken
- [ ] 	Other Features section, alternate row shading link broken
- [ ] 	Other Features section, Column Span Example link broken

	
**Datepicker**
- [ ] Accessibility section, example link leads to sketchy Indonesian gambling site 

**Dropdown**
- [ ] 	Accessibility section - aria best practices link is broken

**Empty Messages**
- [ ] 	Invoking with HTML/CSS section, example page for widgets link broken 
- [ ] 	API Details table, settings.icon row, the link to the latest icon set is broken

**Error Page**
- [ ] 	Code Example section, empty message component link is broken 

**Field Set**
- [ ] 	Code section, the expandable area link is broken. 

**Home Page**
- [ ] 	Code Example section, Cards link is broken

**Icon**
- [ ] Status and Alert Icons section, See alerts component link broken 

**Image**
- [ ] Code Tips, example image list pattern link is broken 

**Listview**
- [ ] 	Keyboard Shortcuts section, checkboxes link is broken 
- [ ] 	Responsive Guidelines section, homepages link is broken 

**Month View**
- [ ] 	Accessibility section - Example link leads to sketchy Indonesian gambling site 

	
**Pager**
- [ ] Code Example section, datagrid link is broken 

**Popup Menu**
- [ ] 	Basic popup menu on a button section, menu button link is broken
- [ ] 	Initialization as a context menu, contextmenu example link is broken 

**Search Field**
- [ ] Usage Examples section, toolbar searchfield link is broken

**Swaplist**
- [ ] Code Example section, listview component link is broken

**Switch**
- [ ] Code Example section, checkbox element link is broken 

**Text Input**
- [ ] Responsive Guidelines section, both "View example" links are broken 

**Timepicker**
- [ ] Default Example section, 24 hour/Military time, seconds picker, and another configuration links are all broken 

**Toolbar (Flex)**
- Testability section - 
- [ ] 		Popupmenu API link broken
- [ ] 		Searchfield link broken
- [ ] 		Application Testability Checklist link is broken
- [ ] 	States and Variations section, text input field link broken 
- [ ] 	Responsive Guidelines section, action button link broken 

**Toolbar Search Field**
- [ ] 	Important Notes section, this page link is broken 
- [ ] 	Implementation Tips, searchfield link broken
- Contextual Colors section
- [ ] 		Alternate in-page style link broken
- [ ] 		Inside contextual action panels link broken 

**Tooltip**
- Simple Tooltips section
- [ ] 		initializer link is broken
- [ ] 		Common tooltip example link broken
- Custom HTML Tooltips
- [ ] 		HTML tooltip example link broken
- [ ] 		Icons in tooltips example link broken 

**Wizard**
- [ ] 	Code Example section, header wizard example link is broken 

**Components>Utilities>Personalize**
- [ ] 	Themes section, theme api link is broken
- Supported Personalization Components section
- [ ] 		Hyperlinks link broken
- [ ] 		Hero Widget link broken 

**Components>Patterns>Application Menu**
- [ ] 		Accordion component link broken
- [ ] 		Searchfield component link broken
- [ ] 		Button component link broken
- [ ] 		Flex Toolbar link broken
- [ ] 		App Test Checklist link broken

**Components>Charts>Overview**
- Chart Types section
- [ ] 	Bar Grouped link broken
- [ ] 		Bar Stacked link broken
- [ ] 		Column Grouped link broken

**Comment by ericangeles** [comment]
Sure, @tmcconechy @hey-yall. 👍🏼

**Comment by tmcconechy** [comment]
Noting: For "Application Testability Checklist links that can definitely be removed. Otherwise try to correct the link or remove it. Again questions ping me.

**Comment by yohannahbautista** [comment]
@tmcconechy @hey-yall @ericangeles 
Hello, I have a few questions:
- Accessibility link (now leads to a gambling site): http://oaa-accessibility.org/example/15/
   - Is there a site you would recommend that would replace this?
- Link to checkboxes (in listview readme): http://access.aol.com/dhtml-style-guide-working-group/#checkbox
   - Should I just link this to the readme already existing for checkbox instead?

**Comment by tmcconechy** [comment]
http://oaa-accessibility.org/example/15/ -> we could use https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/ instead (was supposed to link to an aria example)

For the second one lets make line 12 make more sense

```md
- <kbd>Space</kbd> toggles the selection state if single or multiple selection is enabled
```
