### ISSUE TITLE
Memory leak in modal

### ISSUE THREAD

**Issue by prkarlsson** [infor-design/enterprise#822]
**Describe the bug**
The modal component (modal.js) causes memory leaks by attaching key event handlers to the document that are never detached. This causes leaks of detached DOM elements when opening and closing modal dialogs. The keepFocus function in modal.js is called one or more time for each modal and each call attaches a key handler to the document object. After the modal dialogs are closed parts of the DOM elements are kept alive from the key event handlers.

The leaked DOM elements can be found by using the Chrome Memory profiler. They show up as "Detached HTMLDivElement" etc.

**To Reproduce**
1. Open and close modal dialogs a couple of times
2. Take a heap snapshot in the Chrome Memory profiler
3. There are several detached DOM elements kept alive through the key event handlers.

**Expected behavior**
Opening and closing modal dialogs should not cause leaks of detached DOM elements.

**Platform**
- Device: N/A
- OS Version: Windows
- Browser Name: Chrome
- Browser Version: 69.0.3497.92 (Official Build) (64-bit)

**Additional context**
The issue was found when using the enterprise components in Infor Homepages. The modals were used through the Angular SohoModalDialogService but the issue seems to be in the jQuery modal implementation.

**Comment by ericangeles** [comment]
I've noticed and it appears to be that the `keepFocus` function tends to call even though the key events does not applied (e.g. escape key). and I agree with you @EdwardCoyle with regards to separating the keyboard handling in modals.

**Comment by brianjuan** [comment]
http://4120-beta0-enterprise.demo.design.infor.com/components/modal/example-index.html
Passed QA testing, moving to Done.
