### ISSUE TITLE
Searchfield: x icon is placed outside the field in classic

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8222]
**Describe the bug**
the x icon is placed outside the seaarchfield in classic view

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/searchfield/example-buttons.html?theme=classic&mode=light&colors=default
2. Ensure classic mode
3. Type a text

**Expected behavior**
<img width="407" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/b8353bf5-130a-49ca-894c-da960a4e8cf4">

**Version**

- ids-enterprise: v4.89.0-dev

**Screenshots**
<img width="328" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/d6de7491-c80f-4caa-80eb-12063605558c">

**Platform**
all major browser

**Additional context**
bar code icon is also missing

**Comment by yohannahbautista** [comment]
Hello, checking on main and it looks to already have been fixed
New
<img width="673" alt="image" src="https://github.com/infor-design/enterprise/assets/85279127/960177e9-5839-426f-8220-631b0d9ba4ef">
Classic
<img width="666" alt="image" src="https://github.com/infor-design/enterprise/assets/85279127/33d9de24-16e6-4e82-9c19-580a3ee4b442">

**Comment by jbrcna** [comment]
can confirm. thanks @yohannahbautista 
<img width="1010" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/14dcfbb0-d6ff-4e6f-98f8-b5cd7ee66ca7">
