### ISSUE TITLE
Link: Has a wrong selected state

### ISSUE THREAD

**Issue by talkaboutdesign** [infor-design/enterprise#8225]
It should mirror what we have in KPIs.

https://main-enterprise.demo.design.infor.com/components/link/example-index.html

**Should be identical in the way cards look like:**
https://main-enterprise.demo.design.infor.com/components/stats/example-index.html

**Comment by tmcconechy** [comment]
To Reproduce: Wrong color to be clear when clicking.

Also when picking this up please check web components as well https://main.wc.design.infor.com/ids-hyperlink/box.html and fix https://main.wc.design.infor.com/ids-stats/example.html

**Comment by jbrcna** [comment]
QA Passed
https://main-enterprise.demo.design.infor.com/components/link/example-index.html
<img width="1348" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/bed39a27-2ebf-429b-9cc9-5fbc3b2e7396">
<img width="1506" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/52ca102b-d958-4496-8b16-22226d531f37">
