### ISSUE TITLE
Swipeaction: truncated text is not displayed

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8227]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/swipe-action/example-index.html
2. switch to mobile view or open dev tools
3. Under `Swipe Action (Reveal / One Action / Text Truncated)` swipe left

**Expected behavior**
`Example Action` text should be visible
<img width="545" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/78f7929e-922c-4b23-af83-e4a1a04c5e79">

**Version**

- ids-enterprise: v4.89.0-dev

**Screenshots**
<img width="453" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/750880f9-14b7-4387-b678-20ccec4f3e77">

**Platform**
all

**Additional context**

**Comment by hey-yall** [comment]
Design ticket here: https://jira.infor.com/browse/IDS-1864

**Comment by tmcconechy** [comment]
Going to descope this is as not much we can do and its working within the overflow scenario
