### ISSUE TITLE
Documentation: Fix `attributes` property documentation on all component pages

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#8228]
**Describe the bug**
It was brought to my attention that our documentation for the `attributes` property on most (if not all) of our component pages is incorrectly saying it takes a string argument, when it's actually an object array with several properties.

**To Reproduce**

This can be seen where the property is defined on the documentation pages:

- https://design.infor.com/code/ids-enterprise/latest/modal
- https://design.infor.com/code/ids-enterprise/latest/contextualactionpanel
- https://design.infor.com/code/ids-enterprise/latest/about

The types for the documentation come from JSDoc comments at the top of each file, like this one:  https://github.com/infor-design/enterprise/blob/main/src/components/modal/modal.js#L57

**Expected behavior**
We should fix all these so the documentation reports the types correctly.  For reference, our Angular component library's type definitions seem to report these correctly: https://github.com/infor-design/enterprise-ng/blob/main/projects/ids-enterprise-typings/lib/modal-dialog/soho-modal-dialog.d.ts#L111

**Version**
- 4.89.0
- Also present in many back versions

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/3249601/570bc693-5118-4647-ac52-3d0f6edf4e73)

**Additional context**
Pointed out in an [MS Teams conversation](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1701431162433?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1701431162433&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1701431162433)

**Comment by tmcconechy** [comment]
@yohannahbautista I guess since the data is usually an array?

```
  attributes: [
     { name: 'id', value: 'cap' },
     { name: 'data-automation-id', value: 'cap-automation-id' }
  ]
```

The type would be `@param {array}` unless its someplace you see its a object?
