### ISSUE TITLE
Question: Regarding previous and next icons

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise#8234]
**Describe the Issue**
We are using previous-page and next-page icons. Previously they have the same size but we noticed in version 4.88.0 that the previous-page icon is now smaller. Kindly advise if this is intended and may we know the reason?

**To Reproduce**
Steps to see the question or problem:
1. Visit https://design.infor.com/components/components/icon/
2. Inspect the size of previous-page and next-page icons

**What are you trying to do**
We expect them to have the same size as before.

**Version**

- ids-enterprise: sohoxi-version 4.88.0

**Screenshots**
previous-page icon
![image](https://github.com/infor-design/enterprise/assets/55830499/22844c84-e602-432a-a684-6d8e00e05d9a)

next-page icon
![image](https://github.com/infor-design/enterprise/assets/55830499/11b36bb7-4d45-4590-8f4c-baa99a231778)

**Platform**
 - Infor Application/Team Name: Infor M3
 - OS Version: Windows 10
 - Browser Name Google Chrome
 - Browser Version Version 119.0.6045.200 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I cant seem to verify that it changed i compared https://4644-enterprise.demo.design.infor.com/components/icons/example-index.html with https://main-enterprise.demo.design.infor.com/components/icons/example-index.html

And in both cases it was 18x18. Maybe from a really older version it was different but we have been fixing bugs where the icons are not 18x18 via css and making sure they are consistent.

So answer is should be 18x18 or its wrong. If you really wont smaller ones you can use css to change it but 18x18 should be the right default size.
