### ISSUE TITLE
Card: Incorrect vertical alignment of the detail title

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#8235]
**Describe the bug**
For the new card, the detail title alignment is incorrect if the widget isn't using a subtitle.

![image](https://github.com/infor-design/enterprise/assets/1101770/6d78c052-fac3-4cc6-ab0f-a121a8d9e0b9)

**To Reproduce**
1. Go to https://latest-enterprise.demo.design.infor.com/components/cards/example-workspace-widgets?theme=uplift&variant=light
2. Click on 'Click to open the detail view' button on the navigation example
3. See that the detail title alignment is **correct**
4. Modify the example to not use the subtitle concept. I.e, remove class `has-subtitle` from `.widget-header` and remove the subtitle element (`<p>` inside `widget-header-section title`)
5. Click on 'Click to open the detail view' button again
**Result:** Detail title alignment is not correct.

**Version**
- ids-enterprise: v4.89.0

**Platform**
 - Infor Application/Team Name: OS Portal

**Additional context**
I think `top: 2px` should only be used when the widget is using a subtitle. So our workaround will be `.widget-header:not(.has-subtitle) { top: unset; }`

**Comment by tmcconechy** [comment]
@ericangeles maybe we can fit this in this sprint?

**Comment by ericangeles** [comment]
It appears that the `top: 2px;` isn't necessary. We'll remove it.
