### ISSUE TITLE
Lookup: Single select lookup error

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#8238]
**Describe the bug**
Single select lookup error

**To Reproduce**

1. Go to https://4900-beta0-enterprise.demo.design.infor.com/components/lookup/example-index.html
2. Open the Products field in the single select lookup section

**Expected behavior**
Should not have errors

**Version**
4900-beta0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/45757016/9f08103f-4f45-42b3-8be5-e9a313083df2)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by jbrcna** [comment]
QA Passed
verified in https://main-enterprise.demo.design.infor.com/components/lookup/example-index.html
<img width="1455" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/106e75ad-ae9c-4b87-b826-350b4346da4b">
https://main-enterprise.demo.design.infor.com/components/splitter/test-splitter-in-modal.html
<img width="1420" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/63d32fbc-e01d-4116-8ef9-05cd6f9605d0">
