### ISSUE TITLE
JSdoc formatting issue with Wizard

### ISSUE THREAD

**Issue by nickwynja** [infor-design/enterprise#824]
**Describe the bug**
The code specs/API details for [Wizard](https://design.infor.com/code/ids-enterprise/latest/wizard) are incorrect. `beforeactivate` and `activated` are listed as separate entities rather than being part of "Instance Members".

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/wizard

![image](https://user-images.githubusercontent.com/1012017/45832110-08ff4780-bccf-11e8-9fcd-0444039bccdb.png)

**Expected behavior**
For all Instance Members to be grouped together.

**Comment by clepore** [comment]
@tmcconechy pointed out that the `memberof` is incorrect for this jsdoc comment
