### ISSUE TITLE
Calendar: Swipe/Gesture to select multiple days in the Calendar

### ISSUE THREAD

**Issue by bdahlen** [infor-design/enterprise#8243]
**Is your feature request related to a problem or use case? Please describe.**
We would like the Calendar component to support swiping multiple days use as input when creating an event. Similar to the way double clicking a day can open a modal with that day pre-selected, we'd like to be able to swipe a week of days and have those dates pre-selected in the event creation modal.

Swiping to select mutiple days is an intuitive way for casual users to add a new event to a calendar, and is supported in other third-party solutions like [FullCalendar](https://fullcalendar.io/)

**Describe the solution you'd like**
We'd like a new event that could be fired when the user selects a day on the calendar. It could either be a single day or a set of contiguous days. Something like the code shown below.

`$(".calendar").calendar(calOptions).on("selected", function(e, data) {
	data = {
		eventData: {
			startKey: "20231218",
			endKey: "20231222"
		}
	};
});`

**Describe alternatives you've considered**
The alternative is to add a "dblclick" event that opens a modal. The user needs to manually select the desired begin and end dates using the date range fields on the modal. This interaction is not as user friendly for casual users who want to create a new event that spans multiple days.

**Additional context**
And what application do you work on? [e.g. {Infor XYZ}]

This is needed to support more robust event creation for HR Talent and Landmark.
![IDSCalendarSwipe](https://github.com/infor-design/enterprise/assets/146859868/35728d46-444b-407f-9050-6167b66c1231)

**Comment by AAlviar** [comment]
Design Figma: https://www.figma.com/file/JZdeun4ht1IsqZpV9xAW8Y/Colors?type=design&node-id=346-11814&mode=design&t=aLWixVSyEFJRgRfq-0
