### ISSUE TITLE
DataGrid: Using formatter from next column when the grid is defined with actionableMode: true

### ISSUE THREAD

**Issue by danders17** [infor-design/enterprise#8245]
**Describe the bug**
I'm seeing an issue with the data-grid where the preceding column is taking on the formatter for the next column when the grid is defined with actionableMode: true since we want the tab key to function when entering data in the grid.  I was able to use a workaround by setting showDirty: true although we really don't want the dirty indicators so I am just removing them on cellchange.  See the screen shots of the definitions of the grid and then how the description gets the date icon and then uom gets NaN when enter text and tab through the field.
See this thread in teams https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1701879561411?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1701879561411&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1701879561411

**To Reproduce**
- go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-actionable-mode.html
- type a number in the quantity field and click tab
- note it It changes to true which the next column (the checkbox)

**Expected behavior**
Expect the value to stay as it was entered and not format based on next column

**Version**
4.90.0-beta.0

**Comment by tmcconechy** [comment]
@ericangeles can we look?
