### ISSUE TITLE
BarChart: X axis not display when wrap it with a fixed sized wrapper

### ISSUE THREAD

**Issue by AmilaViduranga** [infor-design/enterprise#8247]
**Describe the bug**
X axis will not display for bar-grouped typed chart. Bellow condition needed to satisfy to reproduce this issue.

- Dataset should be single, not multiple (for multiple it works as expect)
- Chart should wrap with another parent tag.
- Parent tag should have fixed width and height

**To Reproduce**

1. Create a chart with type "bar-grouped"
2. Assign single data set, no multiples
3. Wrap it with a parent element (parent div tag)
4. Give fixed width and height to the parent wrapper.

Stackblitz link:- https://stackblitz.com/edit/ids-quick-start-1641-kt7byw?file=src%2Fapp%2Fapp.component.html

**Expected behavior**
X -axis should visible. 

**Version**

- ids-enterprise: 16.8.1

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/13863481/884718f0-b198-4972-a95e-d02a8ea2b706)

**Platform**
 - Infor Application/Team Name: IAD
 - Device: (if applicable) Dell Laptop
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 119.0.6045.200 (Official Build) (64-bit)

**Additional context**
MS team chat link:-  https://teams.microsoft.com/l/message/19:6d4c9079385840c0bc61e55bcdd16a33@thread.skype/1701955604490?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1701955604490&teamName=IDS%20Enterprise%20Development&channelName=Problems&createdTime=1701955604490

**Comment by tmcconechy** [comment]
Thinking of something here:

- If you make it bigger will it work? 
- I think we have some logic that shows different labels when its smaller. You could try and put text in https://github.com/infor-design/enterprise/blob/main/app/views/components/bar/example-long-text.html#L22-L25 `shortName` and `abbrName` and see if that works?

**Comment by AmilaViduranga** [comment]
@tmcconechy I tried above solutions that you requested. But those solutions are not give expected result to me. I am not 100% sure, but I feel there may be a relations between data sets count and x-axis alignment. If you go through my stackbitz example then you can get what I mean.

**Comment by tmcconechy** [comment]
ok, we will take a look. @AmilaViduranga

**Comment by yohannahbautista** [comment]
Hello, I tested it on the latest and it looks to have been fixed at one point: https://stackblitz.com/edit/ids-quick-start-1730-cwk7e3?file=src%2Fapp%2Fapp.component.ts

**Comment by tmcconechy** [comment]
@AmilaViduranga we can reproduce can you try on 17.30.0 or update this stackblitz with anything it might need?

https://stackblitz.com/edit/ids-quick-start-1730-cwk7e3?file=src%2Fapp%2Fapp.component.ts

**Comment by jbrcna** [comment]
working as expected.
verified in https://stackblitz.com/edit/ids-quick-start-1730-cwk7e3?file=src%2Fapp%2Fapp.component.ts
<img width="975" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1bac3ea2-d927-4885-bcf3-59b14bd66142">
