### ISSUE TITLE
Calendar: Dynamically update disabled dates or day legend settings in

### ISSUE THREAD

**Issue by bdahlen** [infor-design/enterprise#8248]
**Is your feature request related to a problem or use case? Please describe.**
The current version of the Calendar component requires passing in an array of disabled dates when the component is initialized. Retrieving all this data up front could be slow. One use case in HR Talent is the Employee Time Off Calendar. Specific dates or date ranges could be disabled depending on whether the corresponding pay period is open or the rules set up on the absence plan. Pay period date could span multiple years so could be a lot of records to retrieve.

**Describe the solution you'd like**
We'd like to be able to dynamically look up and set disabled dates or other date legend settings each time the calendar is rendered for a given month. As a general approaach, having a "beforeRender" event where we could pass back disabled or updated settings would meet our needs. 

**Describe alternatives you've considered**
I tried dynamically updating the calendar settings in the onRenderMonth, but it didn't work.

```
var api = $(".calendar").data("calendar");
if (api) {
	api.settings.disable = settings.disable;
	api.settings.dayLegend = settings.dayLegend;
	api.updated(settings);	
}
```

**Additional context**
And what application do you work on? [e.g. {Infor XYZ}]
This is needed for the Employee Time Off Calendar in HR Talent.

**Comment by tmcconechy** [comment]
@tjamesallen15 it looks a bit funny on the bottom because the new items are in a section with the bottom cut off and then there is an empty section. I think it should show the lines under the table bottom row

<img width="803" alt="Screenshot 2024-01-22 at 10 51 22 AM" src="https://github.com/infor-design/enterprise/assets/814283/88bb10d0-9cbd-4efe-8c79-b3f500be95dc">
