### ISSUE TITLE
Lookup: With keyword search enabled and server side pagination

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#8258]
**Describe the bug**
When we search any value and press enter the data is being filtered but after pressing the clear button the text from the input is cleared and still shows the old recorder (result of filter).

**To Reproduce**

https://latest-enterprise.demo.design.infor.com/components/lookup/test-paging-server-side-keyword-search.html 
1. Click on Lookup icon.
2. Enter any text in keyword search and press enter
3. Click on clear button.

Lookup grid doesn't refresh on clear until we press enter.

**Expected behavior**
Tt should trigger the source once clear is pressed as it does on DataGrid keyword search.

**Version**

- ids-enterprise: [4.90.0 ids-enterprise-ng@17.1.1]

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
I suggest:

- we filter when we stop typing rather than on enter
- also filter/clear on clicking the X

**Comment by SumitK27** [comment]
@tmcconechy if I may suggest, keep the filter when stop typing optional and let user add this through lookup options the same way we have for datagrid (`filterWhenTyping` in SohoDataGridOptions in enterprise-ng)
