### ISSUE TITLE
Datagrid filtering - Provide filter type 

### ISSUE THREAD

**Issue by dhumalkishor** [infor-design/enterprise#826]
**Is your feature request related to a problem? Please describe.**

We observed that when filtering from Soho Grid, it is not providing filter type whether it is integer, text, select, date. In column definition, filterType is specified for column. 

**Describe the solution you'd like**
If we get filterType from data Grid, it is easy to write appropriate server side filtering code according to filterType for date or integer fields in grid.

**Describe alternatives you've considered**

**Additional context**
This is column definition:
```
[{
  id: 'RuleSeverity', name: this._localize.getLocalizedString('ChartViolatingRules_XAxis'), sortable: false,
  field: 'ruleSeverity', filterType: 'integer'
}
{
  id: 'createdby', name: this._localize.getLocalizedString('Global_Owners'),
  field: 'createdBy', sortable: false, filterType: 'text'
},
{
  id: 'createdon', name: this._localize.getLocalizedString('VBL3_CreatedOn'), field: 'createdOn',
  filterType: 'date', formatter: this.getDateForGrid.bind(this), sortable: false
}]
```

![code](https://user-images.githubusercontent.com/42198413/45861497-69889600-bd5c-11e8-8902-569a9f6e3800.jpg)

**Comment by tmcconechy** [comment]
Im actually not clear 100% on what you mean here. Do you mean you just want the filterType to be sent in the event arguments (source) when paging?

**Comment by dhumalkishor** [comment]
Yes, When we filter data in server side pagination grid we want to send filterType.

**Comment by tmcconechy** [comment]
You can do this by looking up the columnId in the columns array to get the column type.
To add this we would need to add a data-filter-type property to the UI and pick it up here https://github.com/infor-design/enterprise/blob/master/src/components/datagrid/datagrid.js#L1928

Or also pick it up out of the columns array from the data-column-id

**Comment by tmcconechy** [comment]
Added the type in 4.26
