### ISSUE TITLE
Soho-datagrid column required icon is not visible

### ISSUE THREAD

**Issue by manjaripalavancha** [infor-design/enterprise#8260]
**Describe the bug**
When we add required for the Soho-datagrid column, it is not visible properly.

**Steps to reproduce the behavior:**
1. Create one Soho-datagrid
2. Add an column property to required (required: true)
3. Observe the datagrid column which required has been added
4. The required icon is not visible.(The icon color is overlapping with the column header color)

**Expected behavior**
The required icon should be visible

**Version**

- ids-enterprise: 17.1.1

**Screenshots**
<img width="944" alt="datagrid-required" src="https://github.com/infor-design/enterprise/assets/104565263/3d692ee2-53d0-4a29-875e-40644fd5c711">

**Additional context**
You can refere below link to check the issue.
[https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html](url)

**Comment by jbrcna** [comment]
QA Passed
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
<img width="1415" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/6c3f01a1-c4e0-4e29-a6d2-07c3eda5af26">

<img width="1415" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/6c3f01a1-c4e0-4e29-a6d2-07c3eda5af26">

<img width="1399" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/d569e150-3177-4d33-9582-f48211c5de47">

<img width="1363" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/693b552a-4b2e-4b39-bc08-5860e47352e2">



<img width="1363" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/693b552a-4b2e-4b39-bc08-5860e47352e2">


<img width="1336" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/a5b66d23-20eb-41c4-a691-4fecc4095d5f">
