### ISSUE TITLE
Tabs Header: Unable to recognize active tab on High Contrast mode

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#8265]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-header/example-alternate.html?theme=classic&mode=contrast&colors=ffffff 
2. Play around with tabs, notice that the active state is not visible. 

**Expected behavior**
Should be able to see active state as with Dark and Light mode

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/45757016/0544cafa-8d01-47bc-80b5-7d00fc2c6989)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by glenlieorillo** [comment]
This is now working as expected.

<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/cb157e46-ad63-4025-bd58-d70edbfb71b2">
