### ISSUE TITLE
Busy Indicator is pushed way down when in a modal dialog

### ISSUE THREAD

**Issue by aaralikar** [infor-design/enterprise#827]
**Describe the bug**
When using a busy indicator on a modal it can be pushed far down out of view

**To Reproduce**
[soho-busyindicator-in-modal-dialog.zip](https://github.com/infor-design/enterprise/files/2426153/soho-busyindicator-in-modal-dialog.zip)
1. Unzip the sample
1. Bring up a modal dialog.
1. Click on a dialog button to activate the busy indicator.
1. The busy indicator bars are behind the dialog.  However, if the overlay is not transparent, it displays over the dialog.

**Expected behavior**
Busy indicator in the middle and visible.

**Screenshots**
![busyindicator](https://user-images.githubusercontent.com/22720894/45889877-242d8e00-bd87-11e8-9be4-dfa60552a2c4.png)

**Platform**
- All

**Comment by tmcconechy** [comment]
Are you referencing a specific example or do we need to come up with a test case of a busyindicator on a modal?

**Comment by aaralikar** [comment]
![busyindicator](https://user-images.githubusercontent.com/22720894/45889877-242d8e00-bd87-11e8-9be4-dfa60552a2c4.png)

**Comment by aaralikar** [comment]
I am able to reproduce the issue using Angular demo. Added 'WAIT' button to 'Dialog Result'. And on click activate the busy indicator. 

`
  @ViewChild(SohoBusyIndicatorDirective) sohoBusyIndicator: SohoBusyIndicatorDirective;
............ 
 openDialogResult() {
    const dialogRef = this.modalService
      .message('<span class="longer-message">Are you sure you want to delete this page?</span>')
      .buttons(
      [{ text: 'YES', click: () => { dialogRef.close('YES'); } },
        { text: 'WAIT', click: () => { this.sohoBusyIndicator.open(); } },
      { text: 'NO', click: () => { dialogRef.close('NO'); }, isDefault: true }])
      .title(this.title)
      .open()
      .afterClose(result => {
        alert(`You selected ${result}`);
        this.closeResult = result;
      });
  }
`

**Comment by aaralikar** [comment]
Please ignore my earlier comment and code snippet. Digging deeper, I found it is not a zIndex issue. The top calculation for busy indicator is:

```
  .busy-indicator-container.blocked-ui {
    bottom: 0;
    display: block;
    left: 0;
    position: absolute;
    right: 0;
    top: calc(50% - 58px); }
```

And when the component displayed within the modal is more than 600px high, the top of the indicator is pushed way down.  I was not able to override the top on the div that has the soho-busyindeicator directive and get the result I expected.

**Comment by tmcconechy** [comment]
Does this mean you have solved this issue? Maybe if not you can provide an example.

**Comment by aaralikar** [comment]
[soho-busyindicator-in-modal-dialog.zip](https://github.com/infor-design/enterprise/files/2426153/soho-busyindicator-in-modal-dialog.zip)

**Comment by aaralikar** [comment]
Copy the files over to enterprise-ng\src\app\modal-dialog.  I have added a big paragraph to an existing test for nested dialog.  With that, the busy indicator is pushed way down. When the big paragraph is removed from the template, the busy indicator is visible.

**Comment by tmcconechy** [comment]
@aaralikar Does this still need investigating and fixing or have you addressed it to how you need it?

**Comment by aaralikar** [comment]
@tmcconechy This is still an issue. I have set the transparentOverlay to false, so I have a gray overlay displayed when an action is taken in a modal dialog since the bars are pushed way down.

**Comment by tmcconechy** [comment]
Ok thanks i wasnt 100% clear.
