### ISSUE TITLE
Datagrid: Backslash in edited cell is replaced with "&bsol;"

### ISSUE THREAD

**Issue by jonathanamiran** [infor-design/enterprise#8285]
**Describe the bug**
In Datagrid, when typing Backslash in editable cell it replace with `&bsol;`

**To Reproduce**

1. Go to [https://latest-enterprise.demo.design.infor.com/components/datagrid/example-editable.html](https://latest-enterprise.demo.design.infor.com/components/datagrid/example-editable.html)
2. Click on of the cells
3. Type or paste a text with backslash, for instance `c:\windows\temp`
4. See that it changed into `c:&bsol;windows&bsol;temp`

**Expected behavior**
backslash should remain backslash.

It worked fine in v4.82.0 - but I don't know now how to reproduce it because design.infor.com was changed

**Version**

- ids-enterprise: v4.90.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/34129313/a6c37efe-9f36-4747-894f-42af5f631751)

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: Latest

**Additional context**
Thanks!

**Comment by tmcconechy** [comment]
Note: Check all characters like: `&, '  " ` as its doing it for all

**Comment by claudenbach** [comment]
Landmark is also seeing this issue with '<', '>', and '&' characters.
