### ISSUE TITLE
AppMenu: Incorrect text color of selected accordion header in Classic Light/Contrast theme

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#8290]
**Describe the bug**
Selected accordion headers in an application menu have an incorrect text color in Classic Light/Contrast theme

**To Reproduce**
1. Go to https://latest-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html?theme=classic&mode=light&colors=default
2. Open the application menu
3. Notice the text color of the selected accordion header

**Expected behavior**
The text color should be changed (to white?)

**Version**
- ids-enterprise: `4.90.0`

**Platform**
 - Infor Application/Team Name: Homepages

**Comment by tmcconechy** [comment]
@radovaniljic by coincidence we noted this on a PR test and fixed it. So its been fixed in 4.91 to be released ealy this month.
You can see it working here now: https://main-enterprise.demo.design.infor.com/components/applicationmenu/example-index.html?theme=classic&mode=light&colors=default
