### ISSUE TITLE
Tabs: focus highlight is off

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8294]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/example-add-tab-button.html
2. Click on '+' icon
3. See error
4. Notice the focus highlight

**Expected behavior**
<img width="180" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ce557682-ec74-48da-b4e6-f2a7305a58e1">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="185" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/74ce6e2b-03ff-4112-b332-3cdbe61e6130">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
To dev that takes this: Can you just make the button same shape and states as the ... button on the page? (regular icon button)
