### ISSUE TITLE
TabsModule: x icon is not properly aligned

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8296]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html
2. Type a text on searchfield
3. See error

**Expected behavior**
x icon should be properly aligned. 
<img width="284" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/e6e054d5-7f85-4edf-84aa-65e8d605d1f5">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1726" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/58dbd120-3a17-4af5-9e7c-eedf75bee8e2">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@jbrcna also this one seems fixed now. Can you confirm as well? Thanks!

**Comment by jbrcna** [comment]
thanks @tmcconechy . 
test passed. verified in https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html
<img width="568" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/86dfdbd0-2a3b-4587-9fd2-618826e6f664">
