### ISSUE TITLE
TabsModule: search icon is off

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8297]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html?theme=new&mode=light&colors=default
2. Click on searchfield
3. Click outside

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1703" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/1ea95e93-7f83-407c-b07b-15cac7761cad">

**Platform**
All  major browsers

**Additional context**

**Comment by tmcconechy** [comment]
@jbrcna seems like this is fixed now can you confirm on main branch?

**Comment by jbrcna** [comment]
can confirm. working as expected. thanks @tmcconechy 
verified in https://main-enterprise.demo.design.infor.com/components/tabs-module/example-category-searchfield.html?theme=new&mode=light&colors=default
<img width="1717" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/20be0c16-dad1-4225-959c-81121be258f0">
