### ISSUE TITLE
TabsModule: more actions menu color is off

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8298]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover.html
2. Hover over more actions buttons
3. See error
4. Change color to alabaster
5. Hover over more actions buttons
6. See error

**Expected behavior**
<img width="531" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/58f363db-2add-4a40-b034-82ee320ba5ad">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]
- 
**Screenshots**
<img width="1720" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/e1ad60be-c4ce-47ad-a307-ce0e672e13aa">
<img width="415" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/2dc4de66-9866-4250-a208-bc0eb7801846">

**Platform**
all major browsers

**Additional context**

**Comment by lucacolumbu** [comment]
Check this issue as well https://github.com/infor-design/enterprise/issues/8404

**Comment by tmcconechy** [comment]
- Fix with #8404
- ... (and all buttons) are not centered - see figma on #8404 
- Button focus state is cut off
- In Focus state button should not be round should be same as normal icon buttons for rounding
