### ISSUE TITLE
Modal: Opening a lookup from a modal breaks vertical resizing

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#8301]
**Describe the bug**
Opening a lookup that's inside a modal breaks the vertical resizing of the modal.

**To Reproduce**
1. Go to https://latest-enterprise.demo.design.infor.com/components/modal/test-modal-field-filter.html
2. Decrease and increase the height of the browser window and notice how the modal height adjusts and the scrollbar appears/disappears.
3. Open and then close the lookup
4. Repeat step 2
5. Notice that the modal resizing no longer works

**Note:** Can also be reproduced with the browser devtools docked to the bottom and increasing/decreasing the height of it, see the recording below for reference.

**Expected behavior**
The modal resizing should continue working after opening a lookup.

**Version**
- ids-enterprise: `4.90.0`

**Screenshots**
![modal_resize](https://github.com/infor-design/enterprise/assets/63045013/8c747000-83f3-42f5-bb92-7a15e5e53773)

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by ericangeles** [comment]
I don't see it this issue on my end. Are you using windows?

**Comment by radovaniljic** [comment]
@ericangeles yes but I can't reproduce it either anymore, so I guess some other change fixed this issue. Can close this one then 👍

**Comment by ericangeles** [comment]
Closing this now. Thanks.
