### ISSUE TITLE
Text Editor: Add AI Icon Button Variant

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise#8311]
This is related to https://github.com/infor-design/enterprise/issues/8310 

As part of the efforts to implement AI across Infor, we need to create a variant of our Rich Text Editor that includes the icon version of the AI button being created as part of #8310.

This button should fire an event upon click, which the OS/AI team will eventually pick up and attach to their generation endpoint.

The payload from the AI API call will also likely need some type of styling applied to it, whether that is what is in the example below (a vertical purple bar to the left of the text), or something more basic as a first step, like changing text color or weight to help distinguish.

Full Figma board here: https://www.figma.com/file/de80AF4En3uS3uNToJg5at/Infor-Copilot%3A-Identity?type=design&node-id=96-2867&mode=design&t=JQW6ErVc6Elzwlnn-0

Rich text editor mock here
<img width="623" alt="Screenshot 2024-01-05 at 3 01 30 PM" src="https://github.com/infor-design/enterprise/assets/57144784/dc395e3f-0882-4066-aeb8-68c3c6900fef">

Let me know if there are any questions, thanks!

**Comment by tmcconechy** [comment]
- only need to add the new button https://github.com/infor-design/enterprise/issues/8312
- as a new button on the toolbar
- add a new event that fires when clicked `aiButtonClicked` perhaps
- button can be disabled
