### ISSUE TITLE
Loading Indicator: AI Action Variant

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise#8312]
This is related to #8310

We want to create a new animation to indicated an AI action taking place, which I _think_ could be done as a type of loading indicator, but am open to alternative options! 

Animation prototype is here: https://codepen.io/talkaboutdesign/pen/KKEMpjP

We want to get a sense of effort here, and then if the animation needs to be framed out, we can do so. 

Let me know if there are any questions, thanks!

**Comment by tmcconechy** [comment]
That animation looks relatively simple. Shouldnt be too bad. Might need more docs on usage ect. Slightly similar to a loading indicator but may want to have its own name.

Maybe in Enterprise a simple class like "ai-action-animation". In Web components we could maybe make an animation component that has this and any future animations with some settings/start/stop ect.

**Comment by tmcconechy** [comment]
Notes:

- add similar to destructive button
- new `btn-ai` perhaps (best name?)
- add to button page like the others
