### ISSUE TITLE
Sinkpage: checkbox dirty tracker is not fully aligned in firefox

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8319]
**Describe the bug**

**To Reproduce**

1. Go to https://4910-beta0-enterprise.demo.design.infor.com/components/checkboxes/example-index.html
2. Find checkbox component
3. Click dirty tracking  checkbox

**Expected behavior**
<img width="419" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/97d7c06e-562f-413b-97c3-09b3f325ee49">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="689" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/e8fbdfa0-c145-4c22-8e22-b06f24515f02">

**Platform**
Firefox

**Additional context**

**Comment by tmcconechy** [comment]
Looks ok on my end @jbrcna ?

<img width="424" alt="Screenshot 2024-01-08 at 9 40 11 AM" src="https://github.com/infor-design/enterprise/assets/814283/280a9898-984b-4334-96b1-dba6bdc0abd0">

**Comment by jbrcna** [comment]
this is odd. looks okay on my end as well now. thanks for checking @tmcconechy 
<img width="1007" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/605e6a20-2e1c-454a-b92b-647993b15064">

**Comment by tmcconechy** [comment]
No problem, just glad it works good.
