### ISSUE TITLE
Placeholder text not appearing within multiselect dropdown control 

### ISSUE THREAD

**Issue by picitelli** [infor-design/enterprise#832]
**Describe the bug**
For the multiselect dropdown control, the placeholder text is not appearing within the control. The previous versions of the controls, any placeholder attribute value assigned to the SELECT element would be populated as a "placeholder" text within the control (assuming no option is selected). From what I am seeing in the v4.10 build of the SOHO XI controls, the placeholder attribute value is not being passed off to the SPAN within the pseudoElem element.

**To Reproduce**
Using the multiselect examples on the SoHo XI web site
https://design.infor.com/code/ids-enterprise/4.10.0/demo/multiselect/example-index?font=source-sans

1. Add a PLACEHOLDER attribute and value to a SELECT element on the page
2. Initialize control manually $('.multiselect').multiselect(); 
2. On document load, after initialization of control, the placeholder attribute value is not appearing within the dropdown

**Expected behavior**
Any PLACEHOLDER attribute value set to a SELECT element that is intialized as a mutliselect control should be assigned within the SPAN of the pseudoElem (dropdown) element.

**Screenshots**
N/A

**Platform**
 - Device: MacBook Pro (15-inch, 2016)
 - OS Version: Mac OS Sierra v10.12.6
 - Browser Name: Chrome (not working in any browser)
 - Browser Version: Version 69.0.3497.100

**Additional context**
Using Soho XI Controls v4.10.0

**Comment by picitelli** [comment]
@nickwynja what is the review process for determining priority of tickets?

**Comment by picitelli** [comment]
Potential workaround, update the following:

In the `setInitial` method of the `Dropdown` plugin:

```
if (this.element.attr('placeholder')) {
  this.pseudoElem.attr('placeholder', this.element.attr('placeholder'));
  // COMMENT OUT LINE BELOW: Why is the placeholder attribute being removed?
  // this.element.removeAttr('placeholder');
}
```

In the `setDisplayedValues` method of the `Dropdown` plugin, in the following conditional where there is a check for settings or if there are no options:

```
if (this.settings.empty && opts.length === 0) {
  // COMMENT OUT LINE BELOW: Why would we clear out the span?
  // this.pseudoElem.find('span').text('');
  // ADDING LINE BELOW: Taking placeholder attribute value assigned to SELECT (this.element) and placing it within SPAN
  this.pseudoElem.find('span').text(this.element.attr('placeholder'));
  // console.log(this.pseudoElem.attr('placeholder'));
  return;
}
```

This assigns the placeholder to the pseudoElem's SPAN element, but also assigns the placeholder value to the INPUT within the dropdown itself. Looking at ways to resolve this.

**Comment by tmcconechy** [comment]
We don't actually currently have any tests that show support for putting a placeholder on the multiselect/dropdown, but as you pointed out there is a code path for it. So this needs a test.

This probably did break when we changed to use span as the pseudo element. At one point it was an input. I'm not 100% sure if spans can do placeholder text, and changing the implementation considerable might be tricky, so starting out at an 8 estimate here.

Whats the case for doing that (what text do you put there)? Asking because generally just adding "Pick something from the list" type of text is considered redundant.

**Comment by picitelli** [comment]
@tmcconechy , appreciate your response. We having 4 multiselect controls being used as filtering options for a GPC Mongoose application. These controls do not have labels (as part of the design), so we relied on using the placeholder text for a user know what they were for. As you mentioned, older version of these controls were using the INPUT element within the dropdown el, so placeholder worked and client was happy. We ran into performance issues with older set of controls and after upgrading, newer controls perform much better in IE (as well as other browsers). Trying to find a workaround that allows us to use the placeholder as it was originally. Code examples I noted above work but the text value from the placeholder is carried over to the dropdown search when the dropdown is open. Trying to follow path of how that is generated in the plugin to add tweak for that.

**Comment by tmcconechy** [comment]
Ok, that makes sense for a case. Yeah, i think your on the right track. But we might have issues like you said with it being selected and have to toggle a class on the span that styles a span like the placeholder styles. Or add a new element.

If you dont figure it out we can put it up for next sprint..

**Comment by picitelli** [comment]
@tmcconechy, I found a solution that works and uses CSS to display the placeholder text.

In the `setInitial` method of the `Dropdown` plugin, I am adding a `data-placeholder-text` attribute to the pseudoElem's SPAN and setting it with the placeholder value from the SELECT element.

```
if (this.element.attr('placeholder')) {
  this.pseudoElem.attr('placeholder', this.element.attr('placeholder'));
  // set placeholder text on pseudoElem SPAN el
  this.pseudoElem.find('span').attr('data-placeholder-text', this.element.attr('placeholder'));
  this.element.removeAttr('placeholder');
}
```
Using just CSS, we can show the placeholder text within the SPAN only when the SPAN is empty.

```
.dropdown-wrapper .dropdown > span:empty:before {
  content:attr(data-placeholder-text);
}
```

**Comment by tmcconechy** [comment]
This seems like a good solution. Would you like to try to do a pull request? We have details here that you can follow: https://github.com/infor-design/enterprise/blob/master/docs/CONTRIBUTING.md#pull-requests

**Comment by picitelli** [comment]
@tmcconechy, just created pull request for this.
