### ISSUE TITLE
Header: Variant with Menu + Back Button

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise#8327]
We need to create a variant of our header that includes both the menu toggle and the option to display a back button on the page header. 

We already have variants of the header that include one of these two items, but not both, so we should not need anything major to change.

Header with back button: https://main-enterprise.demo.design.infor.com/components/header/example-drilldown.html?colors=ffffff
Header with menu toggle: https://main-enterprise.demo.design.infor.com/components/header/example-index.html?colors=ffffff 

The back button should be located to the right of the menu toggle in this combined variant. Design will follow up with a mock here and add this variant to our Figma library, but since this is coming in as spike work we'll want to start scoping the dev work out while the mock is completed.

Let me know if there are any questions here.

**Comment by tmcconechy** [comment]
@inforandy please see https://github.com/infor-design/enterprise/pull/8329#issuecomment-1885626547 for testing
