### ISSUE TITLE
Modal: Closing a timepicker in a modal with "esc" causes a crash

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#8344]
**Describe the bug**
When a timepicker that's inside a modal is closed using `esc`, a console error is encountered and the entire page becomes uninteractable.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/modal/test-modal-field-filter.html
2. Click "Show Modal"
3. Open the timepicker
4. Close the timepicker with `esc`
5. Notice how the modal is closed and the timepicker is still open, and the page becomes uninteractable. Open the devtools and notice the console error.

**Expected behavior**
The timepicker should close with no errors.

**Version**

- ids-enterprise: `4.91.0-dev.0`

**Screenshots**
![modal_timepicker](https://github.com/infor-design/enterprise/assets/63045013/70d8496e-ae98-4a96-84e4-40d1e13bff2e)

**Platform**
 - Infor Application/Team Name: OS Portal / Homepages

**Comment by glenlieorillo** [comment]
This is now working as expected in main-enterprise.


https://github.com/infor-design/enterprise/assets/102151352/1f6ce34d-cb7d-468a-b784-c47a9e34ad34
