### ISSUE TITLE
Empty Value Option not shown on Datagrid Filter

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#835]
**Describe the bug**
Occurs in Filtering of Datagrids for Options with an empty string option or "". The value is not shown/rendered as one of the filterable values.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html'
2. Click on the "Activity" column's filter.
3. "Select All", "Assemble Paint", and "Inspect and Repair" options are shown.

**Expected behavior**
The "Default Activity" option should also be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/41028784/45993749-d71d2500-c0c2-11e8-8325-57c19292b9aa.png)

**Additional context**
The "Default Activity" option has an id and value of an empty string ("")
![image](https://user-images.githubusercontent.com/41028784/45993798-12b7ef00-c0c3-11e8-8b87-6f9b2b036a16.png)

**Comment by tmcconechy** [comment]
I think at one point i made a change here in this example that removed this. Its problematic to make blank items have a label. Is this something impacting your app? Or you just noticed in the example, as the solution is probably to blank the label for empty items

**Comment by NathanLouisBarcial** [comment]
Hi Tim, yes this has impact for us as we have some datagrid values that has this exact scenario.

**Comment by marknolaninfor** [comment]
I have created a fix, so that the empty valued options will display and work correctly with the multiselect filtertype, as the value does not work when filtering using the select, as this used the empty string as empty filter option.

I am just waiting for the #1009 pull request to be approved and signed off so that I can create a new pull request
