### ISSUE TITLE
[Preview] Widget: Header does not cover the whole width

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#8351]
**Describe the bug**
The widget header has a fixed 360px width, which is smaller than a 2-, 3- or 4- column widget (and half width?). Because of this, the toolbar buttons are no longer aligned to the right side of the widget.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/homepage/example-index
2. Notice how the widget header does not cover the width of the widget

**Expected behavior**
The widget header should cover the whole width, and the buttons should be aligned to the right.

**Version**

- ids-enterprise: 4.92.0-dev.1

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/4991954/39b36f93-b8f0-4d35-b50b-4f27acd9bec9)

**Platform**
 - Infor Application/Team Name: Portal

**Additional context**
Caused by: https://github.com/infor-design/enterprise/pull/8331

**Comment by tmcconechy** [comment]
@tjamesallen15 sorry one more based on previous work. Let me know if you need any help.
cc @ericangeles
