### ISSUE TITLE
[Preview] Dropdown: Crashes when used with ids-enterprise-ng

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#8353]
**Describe the bug**
Given the following template:

```html
<select soho-dropdown [(ngModel)]="colorId">
  <option *ngFor="let item of colors"
    [attr.data-icon]="toIcon(item)"
    [attr.data-hex]="item.value"
    [ngValue]="item.id">{{item.name}}</option>
</select>
```

An error is thrown, and the dropdown doesn't work at all.

**Version**

- ids-enterprise: 4.92.0-dev.1

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/4991954/533a3886-34fd-4f73-853c-1ba346240837)
![image](https://github.com/infor-design/enterprise/assets/4991954/34102173-f3e3-47df-a0d8-4223db65bef4)

**Platform**
 - Infor Application/Team Name: Portal

**Additional context**
Caused by: https://github.com/infor-design/enterprise/pull/8236

**Comment by tmcconechy** [comment]
@tjamesallen15 could you please look and prioritize this new issue based on the one you worked on https://github.com/infor-design/enterprise/pull/8236 ? Thanks

**Comment by tmcconechy** [comment]
@tjamesallen15 looks like from the screen shot its coming from this function here in our code https://github.com/infor-design/enterprise/blob/main/src/components/dropdown/dropdown.js#L787

But i did not try to reproduce

**Comment by anhallbe** [comment]
I don't know the origin of this, but the code looks like this (can be reproduced in an otherwise empty app):

```ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { SohoComponentsModule } from 'ids-enterprise-ng';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [SohoComponentsModule, FormsModule],
  template: `
    <label soho-label for="dropdown">Color</label>
    <select id="dropdown" soho-dropdown [(ngModel)]="color">
      @for (color of colors; track color.id) {
      <option [ngValue]="color.value" [attr.data-icon]="toIcon(color)" [attr.data-hex]="color.value">
        {{color.name}}
      </option>
      }
    </select>
  `,
})
export class AppComponent {
  colors = Object.values(Soho.theme.personalizationColors());
  color = this.colors[0].value;

  toIcon(color: SohoPersonalizationColor): string {
    return JSON.stringify({
      icon: "swatch",
      class: `${color.backgroundColorClass} swatch}`,
    })
  }
}

```

**Comment by anhallbe** [comment]
Code here: https://github.com/anhallbe/ids-repro-dropdown
