### ISSUE TITLE
Column: Stacked Column Not Rendering Using SoHo Column Module

### ISSUE THREAD

**Issue by santosh-sy** [infor-design/enterprise#8361]
**Describe the Issue**
When implementing the column chart by modifying the type to "column-stacked" and importing the SohoColumnModule, the stacked column chart does not render as expected. The issue seems to be related to the rendering of the stacked column chart using SoHo Modules.

**To Reproduce**
Steps to see the question or problem:
1. Import the SohoColumnModule.
2. Implement the column chart with the type set to "column-stacked."
3. Attempt to render the stacked column chart.

**What are you trying to do**
I expected the stacked column chart to render correctly when using the "column-stacked" type with the SohoColumnModule. The use case is to display a stacked column chart in the application.

**What did you try so far**
I followed the implementation details provided in the code snippet. I imported the SohoColumnModule and set the type to "column-stacked" for the column chart.
<div soho-column type='column-stacked' [dataset]="chartData" (selected)="onSelected($event)"></div>

**Version**
- ids-enterprise: v13.3.3
- soho-xi: v4.62.3

**Screenshots**
![Screenshot 2024-01-22 at 8 44 14 AM](https://github.com/infor-design/enterprise/assets/91912744/c52f234d-d648-468a-bc49-54af9a4f69af)

**Platform**
 - Device: Desktop, Laptop
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version: 120.0.6099.225 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@santosh-sy can you post an example or it NOT working? I tried to run it in the demo app and it looks correct.

http://localhost:4200/ids-enterprise-ng-demo/column-stacked

<img width="606" alt="Screenshot 2024-01-22 at 9 44 02 AM" src="https://github.com/infor-design/enterprise/assets/814283/9c57978e-a78e-457f-b6d0-33583e0eed2b">

Suggestion: Try upgrading to the latest version, the one you posted is extremely old https://github.com/infor-design/enterprise-ng/tree/main/src/app/column-stacked

**Comment by santosh-sy** [comment]
@tmcconechy 
This is the output I am able to see (it just doesn't render at all):
![image](https://github.com/infor-design/enterprise/assets/91912744/9e066e3b-2f11-48f6-85fe-9d4b8aa4a6d4)

![image](https://github.com/infor-design/enterprise/assets/91912744/9c6d9675-cb47-4dc4-b0f4-0d47331234d7)

As per the version, could you please guide through how I can upgrade as these widgets will be hosted on LN homepages?

Thanks

**Comment by tmcconechy** [comment]
OK it "works on our end". So not sure, i can only show you our working example and you can compare. https://github.com/infor-design/enterprise-ng/tree/main/src/app/column-stacked

Are you talking about upgrading IOS / Widget framework? If so you may need to talk about it with that time as I dont know why your version would be so old? Or with the LN team?

In general you should just need to update the Angular version to 17 and the version in package.json to [17.2.1](https://www.npmjs.com/package/ids-enterprise-ng/v/17.2.1)

See also: https://github.com/infor-design/enterprise-ng/blob/main/docs/UPGRADING.md
https://update.angular.io/

This project may also help https://github.com/infor-design/enterprise-ng-quickstart

 But again, not sure specifically if there is anything on YOUR project special for updating.
