### ISSUE TITLE
Homepage: No bottom margin in layout?

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#8362]
This is more of a question if this is by design or not. It's been like this for a long time, but I'm pretty sure there was a margin at some time (a long time back)?

**Describe the Issue**
The homepage does not have any bottom margin, causing widgets to look a bit cut. Their bottom border/box shadow isn't shown. Might look better with some kind of margin/gap between last row of widgets and the end of the page?

**To Reproduce**
1. https://main-enterprise.demo.design.infor.com/components/homepage/example-four-column.html
2. Scroll to bottom

- ids-enterprise: 4.91.0-dev.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/1101770/318d8aad-7077-482b-9a49-787f4a576d34)

**Platform**
 - Team: OS Portal

**Comment by tmcconechy** [comment]
I think it was 16px gutter on top and bottom (same as between widgets left and right). Seems like too much space on top too.
I'll take a look

**Comment by tmcconechy** [comment]
@volante007  had to change this. For now padding is 16px on top but the bottom can vary depending on widgets in use and screen size. Its just not possible to get it to 16px always as it requires nasty JS due to the positioned elements.

Can possibly circle back on this later for bottom padding
