### ISSUE TITLE
Demo links not working

### ISSUE THREAD

**Issue by infor-jake** [infor-design/enterprise#8364]
_Associated with: [IDS-1902](https://jira.infor.com/browse/IDS-1902) in Jira_

**Describe the bug**
The [example demo links](https://design.infor.com/components/components/accordion/#usage-examples) for components don't work. They reload the current doc page.

**To Reproduce**
Click a link within any Usage Example section on a component page. 
e.g. https://design.infor.com/components/components/accordion/#usage-examples

**Expected behavior**
The links to demo pages should be removed from readme's (keeping the "embedded" demos as is). Usage demos are planned to be reintroduced within the doc site, keeping it as the source of truth.  

![Screen Shot 2024-01-22 at 11 46 51 AM](https://github.com/infor-design/enterprise/assets/117312557/99a8cad9-5290-477f-9e10-52b14e4c3bbb)

**Comment by tmcconechy** [comment]
We did a bunch of fixes in this area but its not deployed yet. Might want to check this again when its deployed.

**Comment by tmcconechy** [comment]
Looks fixed now please have a look @infor-jake
