### ISSUE TITLE
Graph: An error is encountered when there's more than 20 records

### ISSUE THREAD

**Issue by NicholTamayo** [infor-design/enterprise#8367]
**Describe the bug**
When the Pie, Stacked Bar, Donut and Stacked Column Graph has more than 20 records, a console error is encountered: TypeError: Cannot read properties of undefined (reading 'substr'), related to https://github.com/infor-design/enterprise/issues/7941

**To Reproduce**
1. Go to 'https://stackblitz.com/edit/ids-enterprise-4880-dd4cvn?file=index.js,index.html'.
2. In Index.js, add another record.
3. Save and run.

**Expected behavior**
No console error is encountered and the graph's legend remain displayed.

**Version**
- ids-enterprise: 4.88.0 and above.

**Screenshots**
![A error is encountered when there's more than 20 records](https://github.com/infor-design/enterprise/assets/79066908/b76a0067-9ea1-4715-af4f-734d825e86b1)

**Platform**
 - Infor Application/Team Name: Homepages/PortalV2
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 120.0.6099.225 (Official Build) (64-bit)

**Additional context**
The modals in Homepages and PortalV2 became broken after the issue is encountered.

**Comment by tmcconechy** [comment]
You may want to consider a different chart type. With 20 slices i think a) we dont have enough colors and b) it seems invalid for a pie chart making it wholly unreadable. If you cant at least disable the lines.

Maybe a bar or line is better or some reduction of data. But we can look at the error, but i think that the stackblitz doesnt show an error? Can you check the stackblitz is reporting the error in the console?

**Comment by NicholTamayo** [comment]
Hi @tmcconechy, I have leave the stackblitz with 20 records, I added another one so it should be have the console error upon access now. This also seems to be only encountered using Pie and Donut chart.

Screenshot of the console error:
![image](https://github.com/infor-design/enterprise/assets/79066908/baba503d-a344-49a1-99dd-ead6401d684f)
![image](https://github.com/infor-design/enterprise/assets/79066908/1a8ab4da-32b1-42e6-8484-cc9f681146e6)

**Comment by tmcconechy** [comment]
Ok, thanks. Again this seems like a strange pattern. But i think as a fix we can loop back over the colors again since there is a limit of 20 colors right now.

So just start looping back over the color area (for dev)

**Comment by NicholTamayo** [comment]
Hi @tmcconechy, I noticed that the color on the graph doesn't seem to be looping back? May I kindly ask if the fixed includes this? or we fixing that on a different ticket? Many thanks in advance!
![image](https://github.com/infor-design/enterprise/assets/79066908/e468df1e-1ec9-4771-9400-00cd5425fd82)

**Comment by tmcconechy** [comment]
@NicholTamayo no we didnt fix any errors. Im looking at the example https://main-enterprise.demo.design.infor.com/components/pie/test-many-records.html and i dont get any errors.

Do you think the error is related to it? If so how can i reproduce that? Or can you see a simple fix? Also noting on https://main-enterprise.demo.design.infor.com/components/pie/test-many-records.html the legend doesnt look very good.

But i think we need to focus on the error here and how to reproduce and make a new issue or reopen this and fix the legend.

Did you consider just using a different chart (maybe a line chart) as the amount of items makes it pretty useless as a chart and very hard to read (side note)

**Comment by NicholTamayo** [comment]
Hi @tmcconechy, I no longer encountered the console error when using pie, donut and bar-stacked (but weirdly I still encountered the issue when using bar-stacked in widget but not in stackblitz), but I can still reproduce the issue when using column-stacked (https://stackblitz.com/edit/ids-enterprise-4940-kb5xlb?file=index.js,index.html) in stackblitz.
![image](https://github.com/infor-design/enterprise/assets/79066908/fbc79444-1fcf-4200-8aa4-3b34629ac8ef)

unfortunately the error breaks the modals in Homepages and PortalV2 so we need to fix this particular chart type. 
![image](https://github.com/infor-design/enterprise/assets/79066908/9e7dd83b-f123-45ec-a362-76c4233dd623)

**Comment by ericangeles** [comment]
@tmcconechy yes. @NicholTamayo please create another ticket issue thanks.

**Comment by NicholTamayo** [comment]
Thank you @tmcconechy and @ericangeles, the bar-stacked and column-stacked issue is reported in https://github.com/infor-design/enterprise-ng/issues/1675
