### ISSUE TITLE
Announcement Widget/Hungarian/Date Picker

### ISSUE THREAD

**Issue by sgcrandall** [infor-design/enterprise#837]
**Describe the bug**
Cannot able to post an announcement in hungarian language

**To Reproduce**
InforOS 12.0.27
1. Language: Hungarian
2. Post an announcement using the announcement widget
3. When you hit post, a placeholder is appended to the date, which creates an invalid input and prevents the announcement from being posted.

**Expected behavior**
Placeholder doesn't return upon hitting post and the announcement is posted.

**Screenshots**
https://jira.infor.com/browse/TECHSTACK-6748

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
What makes you certain this is an issue in the Enterprise components? We have no way to debug your app for you, so we will need you to make a reduced test case such as a jsfiddle, which we can run. Or make steps to reproduce it on our samples.

Without that we will be unable to solve this issue in any way.

Also i suggest just not using a placeholder... Its not required, that may solve the issue

**Comment by tmcconechy** [comment]
Unfortunately we were not able to reproduce this. Feel free to reraise if you can add a reduced test case.
