### ISSUE TITLE
IE Specific - Select Announcement type is displaying Blank.

### ISSUE THREAD

**Issue by sgcrandall** [infor-design/enterprise#838]
**Describe the bug**
MNGCLD/MNGOP - 12.0.25 - IE Specific - Select Announcement type is displaying Blank.

**To Reproduce**
1. Login into Mingle application.
2. Navigate to Home pages screen.
3. Add Announcement widget .
4. Try to add Announcement.
5. Enter Title and Description
6. Click on select Announcement Type.

**Actual Result:**

Select Announcement Type is displaying Blank.

**Expected Result:**

List of Announcement Types should be displayed.

**Observations in previous build:**

Issue exists in previous build also but it will disappear after refreshing the URL.Now it is reproducing continuously.

**Screenshots**
https://jira.infor.com/browse/TECHSTACK-6190

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: 
 - Browser Name **IE only**
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
We have no way to debug your app for you, so we will need you to make a reduced test case such as a jsfiddle, which we can run. Or make steps to reproduce it on our samples.

Without that we will be unable to solve this issue, since we have no way to test or run or verify anything.

**Comment by tmcconechy** [comment]
Unfortunately we were not able to reproduce this with the given info. Feel free to reraise if you can add a reduced test case.
