### ISSUE TITLE
ModuleNav: Disable Module Nav Switcher

### ISSUE THREAD

**Issue by Abrai7** [infor-design/enterprise#8381]
**Is your feature request related to a problem? Please describe.**
There's no option to disable the module-nav-switcher so that the user can't interact with it. 

**Describe the solution you'd like**
Being able to see an icon and a text instead of a dropdown

**Describe alternatives you've considered**
Hiding the whole section, however, this may cause confusion.

**Additional context**
N/A

**Comment by tmcconechy** [comment]
If the dropdown has one item, may want to disable it. Effectively just showing text in the module switcher. Or just remove the chevron and disable clicking to open. Depending on how design feels

**Comment by tmcconechy** [comment]
@Abrai7 Just as one more thing for clarification. What are you wanting to show in the top with the icon and text? Whats the use case? Does the dropdown eventually become enabled?

**Comment by Abrai7** [comment]
@tmcconechy Sorry for the delay, didn't see this question. Instead of the chevron icon at the far left side just show the switcher icon along with the default text. Like this:
<img width="199" alt="image" src="https://github.com/infor-design/enterprise/assets/9669865/17dadf4c-ed20-4b53-9364-d2eaf98ec396">

This would prevent unauthorized users to being able to interact with the switcher. 
Does the dropdown eventually become enabled?
-> No, the whole idea is to load the switcher at the beginning and based on the user's security permissions disable it.

**Comment by tmcconechy** [comment]
Ok i think if its unchangable it should just show as text like a title? Dont you think?

**Comment by Abrai7** [comment]
Yes, makes sense

**Comment by hey-yall** [comment]
Flagged for design review under this Jira ticket: https://inforwiki.atlassian.net/browse/IDS-2135
