### ISSUE TITLE
ModuleNav: Use Custom Icon/avatars in Switcher/Top bar

### ISSUE THREAD

**Issue by Abrai7** [infor-design/enterprise#8382]
**Is your feature request related to a problem? Please describe.**
Currently we can only set up an icon inside IDS repository: https://design.infor.com/foundations/icons/ for the module-nav-switcher.

**Describe the solution you'd like**
Being able to set up an icon with the user initials. Something similar to this: https://github.com/infor-design/enterprise/issues/8374 but instead of setting up the icon on the bottom, being able to configure it on the module-nav-switcher

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by inforandy** [comment]
Hi @Abrai7, this functionality is not currently planned for the module nav. Global design guidance is to place user avatar in the bottom left corner, please reach out if there are any questions or concerns here.
