### ISSUE TITLE
Tabs: count labels were missing

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8385]
**Describe the bug**
the label for counts is not displayed. therefore, there's too much space at the bottom

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/example-counts.html
2. Click on tabs
3. See error

**Expected behavior**
<img width="1278" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/adc02336-f704-4e64-9360-a6e9482b6b53">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1223" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/362b333b-aa6a-497a-9d88-9e870dc647cf">

**Platform**
all major browser

**Additional context**
the focus highlight is not in proper place as well. perhaps due to the missing label

**Comment by jbrcna** [comment]
issue still exists in beta
<img width="1135" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/dafeb887-e7ea-4702-b7bb-8727611fbdf6">
 but fixed in main

**Comment by tmcconechy** [comment]
@jbrcna try this url https://4921-beta0-enterprise.demo.design.infor.com/components/tabs/example-counts.html to confirm
I reposted the branch as the version was wrong, old one was out of date a bit

**Comment by jbrcna** [comment]
thanks @tmcconechy . this is now working as expected.
<img width="1421" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/7276e668-bb65-4ea3-a0af-d3cf1c2d688c">
