### ISSUE TITLE
Generative AI: some icons looks off on classic mode

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#8389]
**Describe the bug**
Generative AI: Looks off on classic mode

**To Reproduce**

1. Go to https://4920-beta1-enterprise.demo.design.infor.com/?theme=classic&mode=light&colors=default 
2. Scroll to GEN AI section 
3. Notice some icons looks off

**Expected behavior**
Should look like something like the ff:
![image](https://github.com/infor-design/enterprise/assets/45757016/56aa6824-ce4c-46ed-be6f-dae3952424a4)

**Version**
4920-beta1-enterprise

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/45757016/ff096c25-cf20-4eb1-9a7f-f33a9e46c202)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@janahintal This new button will never work in classic mode. Its not supported for it. To make it easier i hide it when in classic mode

https://main-enterprise.demo.design.infor.com/components/button/example-index.html?theme=classic&mode=light&colors=default

vs

https://main-enterprise.demo.design.infor.com/components/button/example-index.html

Just for the demo site 👍🏻
