### ISSUE TITLE
Masthead: Button hover color is incorrect?

### ISSUE THREAD

**Issue by volante007** [infor-design/enterprise#8391]
**Describe the bug**
Putting a question mark in the title, as I'm not sure if this is by design. I see no mention of it in the 4.91.0 changelog. Hover color of buttons in the masthead is now azure, used to be white.

**To Reproduce**
1. https://main-enterprise.demo.design.infor.com/components/masthead/example-index.html
2. Hover the buttons in the masthead
Result: Hover color is azure

**Expected behavior**
Would expect it to be white as in previous versions, see 
https://4900-enterprise.demo.design.infor.com/components/masthead/example-index.html

**Version**
- ids-enterprise: v4.91.0 / 4.92.1-beta.2

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/1101770/a6eac1e5-2932-4b33-8019-543b4c86be0a)

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by tmcconechy** [comment]
Yes should go to white like https://4644-enterprise.demo.design.infor.com/components/masthead/example-index.html (or the site you noted). I will push a fix for inclusion in the final.

**Comment by volante007** [comment]
The issue was not fixed for menu buttons
![azure-hover](https://github.com/infor-design/enterprise/assets/1101770/380ee976-8508-408a-a398-6ae8f8005441)
