### ISSUE TITLE
Icon: Incorrect icon exporting for change-department-alt icon

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise#8393]
We need to look into a sync issue between our icon board and what is currently available in the IDS enterprise icon library. 

Icon in question: change-department-alt

Currently serves: 
<img width="32" alt="Screenshot 2024-01-26 at 10 59 42 AM" src="https://github.com/infor-design/enterprise/assets/57144784/96c06802-57e4-4363-b2aa-876d975f542f">

Expected outcome, based on the icon file:
<img width="86" alt="Screenshot 2024-01-26 at 11 00 46 AM" src="https://github.com/infor-design/enterprise/assets/57144784/a423a6ff-369f-407e-937f-6f35c2188255">

Let me know if there are any additional questions!

**Comment by tmcconechy** [comment]
Yes the previous one was:
![Screenshot 2024-01-26 at 11 57 04 AM](https://github.com/infor-design/enterprise/assets/814283/0f5ac79b-05d5-41d5-b383-734aeb23aaf2)

But in the newest icons its:
![Screenshot 2024-01-26 at 11 56 25 AM](https://github.com/infor-design/enterprise/assets/814283/dcee91dd-9f47-4ebe-8cd4-5966eb417c74)

Which is correct? I guess changing departments would be the arrows? CC @talkaboutdesign

**Comment by talkaboutdesign** [comment]
The change is by design. All icons that communicate change were updates to this style. Some examples below: 

Change Project, change job, change department, etc. 

![CleanShot 2024-01-26 at 13 08 49@2x](https://github.com/infor-design/enterprise/assets/2926534/028814fb-7b94-4aa2-8026-0cb1abdb19a0)

**Comment by talkaboutdesign** [comment]
The change from v4 to v5 icons is not exclusive to just bump up in stroke weight. They have some new metaphors, and other changes.

**Comment by inforandy** [comment]
Got it. So then the workspace team has the wrong icon in their, and the icon they should be using is what is currently live?

**Comment by tmcconechy** [comment]
@inforandy the just adopted the new beta with the new icons so i assume they would have the old one for now and would get the new one soon?

But may need to check with them on that? Does that mean we can close?

**Comment by tmcconechy** [comment]
We have two figma files:

**Old One**
https://www.figma.com/file/XWg7HKWXuEa4O4pEoAGmYi/IDS-(SoHo)-Assets-Library-v4.5?node-id=14119%3A239&mode=dev

**New One**
https://www.figma.com/file/NYzUbtJYc4aFh9f4LKjiUN/IDS-System-Icons%3A-5.0?type=design&node-id=0%3A1&mode=design&t=XJDJg5PmET5OSUDV-1

Since design changed it to a circle arrow now for all "Switching/Changing" actions. Its now correct as of 4.92.0
