### ISSUE TITLE
Slider: Milestone ticks not displaying correctly in dark mode

### ISSUE THREAD

**Issue by inforandy** [infor-design/enterprise#8397]
**Issue**
Filing on behalf of workspaces so they can drop additional info

Observed Behavior: Slider ticks not displaying correctly in dark mode
<img width="221" alt="noticksslide" src="https://github.com/infor-design/enterprise/assets/57144784/dff519c1-0e49-434f-94c5-706a01beb593">

**Steps To Reproduce**
- go to new example added by Tim http://localhost:4000/components/modal/example-slider.html?theme=new&mode=dark&colors=default
- switch to dark mode
- open modal and observe slider

<img width="432" alt="Screenshot 2024-01-29 at 9 17 34 AM" src="https://github.com/infor-design/enterprise/assets/814283/ddaabc74-edff-4501-ab71-5d91d5bdfe49">

**Suggested Fix**
- change back color to other slate colors to make this work

**Comment by inforandy** [comment]
I cannot replicate this currently, we need more info

**Comment by tmcconechy** [comment]
Could even be an app problem and not a bug in the component library for all we know.

**Comment by bveerabathini** [comment]
Hi,
In SohoModalDialog the slider is available, so dialog background color is same as the slider ticks color in Dark theme of New Mode.

**Comment by tmcconechy** [comment]
@bveerabathini i was able to reproduce this one, added it to the notes.
