### ISSUE TITLE
Swaplist: Overlapping/Misaligned Text and Swap Button

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8398]
**Describe the bug**
Overlapping/Misaligned Text and Swap Button.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/swaplist/list
2. Click on all examples
3. Notice the text and the swap button

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/38cb16e0-8a41-4fa8-ade6-c77fa9066abc)

**Platform**
 - All major browsers

**Additional context**

**Comment by ericangeles** [comment]
It has something to do with the recent fix where the width in the card/widget header is set to inherit.

**Comment by tmcconechy** [comment]
Fixed this issue on main https://github.com/infor-design/enterprise/commit/f24b2db6ad4dcb6496a4e3e9d1bc351a7cd7b893

Please confirm on https://main-enterprise.demo.design.infor.com/components/swaplist/example-index.html
(Wait at least an hour from this post for it to update please).

**Comment by glenlieorillo** [comment]
This is now working as expected in main-enterprise.

https://main-enterprise.demo.design.infor.com/components/swaplist/example-disable-dragging.html
![image](https://github.com/infor-design/enterprise/assets/102151352/e6a69547-6c65-4445-983a-6b29079fdb47)

https://main-enterprise.demo.design.infor.com/components/swaplist/example-enable-keep-in-list.html
![image](https://github.com/infor-design/enterprise/assets/102151352/299cfdb1-2865-4b1c-9cbd-7a15719d3f8a)

https://main-enterprise.demo.design.infor.com/components/swaplist/example-index.html
![image](https://github.com/infor-design/enterprise/assets/102151352/c12d03a8-c033-409a-84b3-55290a652fbd)

https://main-enterprise.demo.design.infor.com/components/swaplist/example-search.html
![image](https://github.com/infor-design/enterprise/assets/102151352/3d754d0d-98f4-4c0e-8dbc-38c301e7600c)

https://main-enterprise.demo.design.infor.com/components/swaplist/example-selected.html
![image](https://github.com/infor-design/enterprise/assets/102151352/293efabf-d744-40c8-aa71-967aeac0050d)
