### ISSUE TITLE
Searchfield: x icon focus is not centered

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8399]
**Describe the bug**

**To Reproduce**

1. Go to https://4921-beta0-enterprise.demo.design.infor.com/components/searchfield/example-index
2. Type a text
3. Press tab to focus in x icon

**Expected behavior**
focus should be properly aligned

**Version**

- ids-enterprise: beta

**Screenshots**
<img width="441" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/94339d52-780c-4e4e-990d-56dba23e05b6">

**Platform**
all major browser

**Additional context**

**Comment by ericangeles** [comment]
For more context, this is noticeable in Firefox.

**Comment by tmcconechy** [comment]
@ericangeles think it needs to be fixed in this 4.92 release about to release? was thinking no...

**Comment by ericangeles** [comment]
No, we can fix that anytime. Not too important.
