### ISSUE TITLE
Datagrid: Getting a JSE when editing a column with an editorComponent

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#8401]
**Describe the bug**
For a datagrid column using a custom editor via editorComponent, getting a JSE when attempting to edit the column.

**To Reproduce**

1. Create a column with a custom editor
2. Attempt to edit the column
3. See JSE in the console

**Expected behavior**
Able to edit a column with a custom editor.

**Version**

- ids-enterprise: v4.91.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/39804038/a8edef4e-92a8-4a66-8bc2-219db9833211)

![image](https://github.com/infor-design/enterprise/assets/39804038/6ce27269-d82d-4ee3-9751-11ab470cf650)

**Comment by tmcconechy** [comment]
Hopefully fixed by https://github.com/infor-design/enterprise/commit/4115efc0fd234fc1d2f233324d1084171f08e2f8
