### ISSUE TITLE
Syntax Error in icon-user-status-unknown definition

### ISSUE THREAD

**Issue by sanx72** [infor-design/enterprise#8402]
IDS 4.92.0

File: theme-new-default-svg.html

Icon: icon-user-status-unknown

`<symbol id="icon-user-status-unknown" viewBox="0 0 18 18"><circle cx="9" cy="9" r="7.5"fill="currentColor" ></circle></symbol>`

There should be a space between the **r="7.5"** attribute and the **fill="currentColor"** attribute. This is currently invalid HTML, and if used in an XML context, breaks icon access to the entire file.

**Comment by tmcconechy** [comment]
Will be in patch 4.92.1
