### ISSUE TITLE
Border on tabs in Alabaster color

### ISSUE THREAD

**Issue by edisonferrer** [infor-design/enterprise#8404]
**Describe the bug**
Top and bottom border of module tabs aren't visible when switching to Alabaster color. 

**To Reproduce**
1. Load the module tab demo on this link: https://latest-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover?colors=default&theme=uplift&variant=light&layout=embedded
2. Switch to Alabaster color
3. Notice that top and bottom borders of the tabs aren't visible, specially the active tab

<img width="958" alt="image" src="https://github.com/infor-design/enterprise/assets/47999751/b7f54132-48d5-450e-a17d-79a200fa2d90">

Might also want to check out the add more tabs button:
<img width="248" alt="image" src="https://github.com/infor-design/enterprise/assets/47999751/9dbb0a22-0911-4457-97e3-6c7cf01a9d6a">

**Expected behavior**
A border something similar to other colors:

<img width="959" alt="image" src="https://github.com/infor-design/enterprise/assets/47999751/c9a26993-e6ea-4af7-ab72-0bb0a4a84255">

**Version**
- ids-enterprise: v.4.92

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Seeing a few other issues on this page:

1. alabster is the default https://main-enterprise.demo.design.infor.com/components/tabs-module/example-toolbar-with-spillover
2. Button icons are misaligned
3. Plus button icon color is invisible

**Comment by talkaboutdesign** [comment]
Border being gone is by design.

**Comment by tmcconechy** [comment]
@tjamesallen15 just have a look at my points here for this issue https://github.com/infor-design/enterprise/issues/8404#issuecomment-1919198605 the design is correct but we need to fix other problems with the pattern page
