### ISSUE TITLE
Datepicker: Month year date pickers are incrementing their manually typed months when blurred out of the input field

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#8406]
**Describe the bug**
A date picker with the month year format will increment their manually typed in months when clicking out of the field.

**To Reproduce**

1. Go to /components/datepicker/example-month-year-format.html
2. Type in '04/2021' into the first field
3. Click into next field
4. See error, the value in the first field has changed to '05/2021'

This also happens in the other fields on the page.

**Expected behavior**
The entered date should stay when the field is blurred.

**Version**

- ids-enterprise: 4.91.0

**Screenshots**
![JanIDSDateIssue](https://github.com/infor-design/enterprise/assets/22107636/c2ae7c2d-af35-462e-8337-e1a87515c8f7)

**Platform**
 - Infor Application/Team Name: Landmark
 - All

**Comment by tmcconechy** [comment]
@ericangeles can you look at this one first and I'll patch with some others when done?

**Comment by tjamesallen15** [comment]
can you guys retest this one? Tried checking it and its not reproducible on my end. @infor-design/qa

**Comment by jbrcna** [comment]
this is what i see on my end. 
verified in https://main-enterprise.demo.design.infor.com/components/datepicker/example-month-year-format.html
![Large GIF (628x700)](https://github.com/infor-design/enterprise/assets/56722184/e8692938-7666-4486-81a5-4e1844c5786b)

**Comment by tmcconechy** [comment]
hmm wierd @Sovia i cant reproduce it today either on 4.92.1 https://4921-enterprise.demo.design.infor.com/components/datepicker/example-month-year-format.html

Or on main https://main-enterprise.demo.design.infor.com/components/datepicker/example-month-year-format.html

**Comment by Sovia** [comment]
Well, I could recreate it on the demo controls yesterday, but can't today. I'm ok with this getting closed for now, if it comes back I can re-open. Thanks @tmcconechy !

**Comment by tmcconechy** [comment]
yeah wierd 👍🏻
