### ISSUE TITLE
Remaining Calendar Features (Part Three)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#841]
**Remaining Current Design (Future Sprint)**
- [ ] adding events - on add button
- [ ] adding events - on double click
- [ ] editing events - on selecting
- [ ] showing more than one event in a day in the details
- [ ] mobile / responsive design
- [ ] drag times to extend / reduce them across days, Drag events to other days
- [ ] week view
- [ ] more docs and tests
- [ ] code sniffer scan
- [ ] in ar-SA locale the events are not showing, should map todays date when passed in the events.
- [ ] confirm keyboard on ar-SA - including the secondary picker.

**Added Nov/Oct Sprint**
- [x] upcoming events view
- [x] when no icon, the event should be left aligned
- [x] when selecting a day from the month switcher datepicker it doesn't go to that direct day..
- [x]  Right to left cleanup/retest
- [x] refactor showTodaysMonth to selectDay
- [x] comment back in the xit tests
- [x] keyboarding around on the calendar days
- [x] veracode scan

**Added Sept Sprint**
- [x] Ajax load events for a month
- [x] events for changing months
- [x] tooltip on ellipsis of event name
- [x] status (fx.. pending) on the event
- [x] notification banner
- [x] allow calendar items to span multiple dates
- [x] selecting events (with an event when selecting a day)
- [x] show readonly events details - when days are clicked

**Landmark Requirements:**
- [ ]   Keyboard navigation
- [ ]   notify by an event for show, add, update, delete 
- [x]  Allow display of calendar items to span dates and times.
- [x]  Allow a legend with a checkbox control to display/hide matching items
- [ ]   Allow click events on open areas and on calendar items: double click, right click (to open and show right click menu)
- [x]  Date navigator to go to the next/prev week, month, day.
- [ ]  Drag times to extend / reduce them, Drag events to other days
- [ ]   Need a way to tell calendar whether item is draggable or not.
- [ ]  Need an event on drop with "done" and "cancel" responses.
need to be able to cancel the drop from completing after drop event.
- [x]  Need an onSelection event
- [x]  Right to left compliant
- [x]  Other calendar support: Hijri, other?

**Optiva Requirements**
- [x]   Shared calendars
- [x]  Support for adding site level holidays
- [x]   UTC support
- [x]   We need support for importing and exporting calendar event data using a standard format (Wont do - should be implemented server side)
- [x]   The standard iCalendar (.ICS) format is supported by Outlook and Google Calendar for import from outlook. (Wont do - should be implemented server side)
- [ ]   Support for defining working days and working hours for groups of employees
    i.e. Monday through Friday. 7AM to 3PM

**ePathway Requirements**

- [ ]  View which days of the month are fully booked (i.e. all available times booked)
- [ ]  View which times in a day are booked
- [ ]  Ability to configure blocks/intervals of time (e.g. 15 minute blocks, 2 hour blocks etc.)
- [x]  Ability to configure starting (availability) date and final (availability) date. For example, a facility is available from the 1st of next month up until the end of the calendar year.
- [ ] Nice to have: If booking a facility (e.g. tennis courts), Google Maps integration to display/view the facility and other nearby facilities

**Other info**
This used to be SOHO-2182
Sprint Two Work was done on ticket https://github.com/infor-design/enterprise/issues/675

**Design**
[SoHo Calendar-UI-v1_050418_JN.pdf](https://github.com/infor-design/enterprise/files/2176670/SoHo.Calendar-UI-v1_050418_JN.pdf)

**Comment by clepore** [comment]
We need to split this ticket into smaller parts.
