### ISSUE TITLE
Datagrid: Escape key closes modal and opens colorpicker after the modal is closed

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#8411]
**Describe the bug**
When a colorpicker cell is focused on a table within a modal and the user presses the Escape key, the modal is closed and the colorpicker is opened after.

**To Reproduce**

1. Please use this zipped html file: [test-editable-colorpicker-on-modal.zip](https://github.com/infor-design/enterprise/files/14127309/test-editable-colorpicker-on-modal.zip)
2. Click on Show Modal button
3. Click on a colorpicker cell
4. Select a color
5. Press the Escape key

**Expected behavior**
After comparing this to other datagrid cells, it is expected that the modal is closed and the colorpicker does not open.

**Version**
- ids-enterprise: 4.88.0-beta.0

**Screenshots**
![editable colorpicker escape key on modal](https://github.com/infor-design/enterprise/assets/76002134/ff565e49-4205-40d9-99b8-10e1ebbe3364)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 121.0.6167.87 (Official Build) (64-bit)

**Comment by s-werking** [comment]
Hi @tmcconechy, I'm not encountering the console error in #8344 and I can still interact with the page after pressing the Escape key. I think the modal and colorpicker key down events are both triggered in this case.

**Comment by tmcconechy** [comment]
ok @yohannahbautista can you look at this when you address https://github.com/infor-design/enterprise/issues/8344 seems very closely related 👍🏻

**Comment by awbuboltz** [comment]
@tmcconechy, will tickets that we create for 4.x be addressed in 5.0? We're not actually planning to take another 4.x update as we work towards the 5.0 migration.

**Comment by tmcconechy** [comment]
@awbuboltz 
 You mean the web components right https://github.com/infor-design/enterprise-wc

If so i assume this issue wont happen there. But if it does we can fix it there https://github.com/infor-design/enterprise-wc/issues

If we have a quick chance i'll setup a test page and see but the code is 100% different

This particular issue i will fix here because it was reported multiple times

**Comment by awbuboltz** [comment]
Yes, I was talking about the web components. Thanks for the update!

**Comment by ericangeles** [comment]
Had time to investigate it, and it looks like that the timepicker doesn't trigger any events when `esc` key pressed. I compared it to the datepicker, which does have this functionality. I also traced back to this, and it has been there since 4.83.

**Comment by glenlieorillo** [comment]
This is now working as expected in main-enterprise.


https://github.com/infor-design/enterprise/assets/102151352/2ff7529e-d1b2-40c7-bfac-5fcd285134d1


https://github.com/infor-design/enterprise/assets/102151352/affc5468-ce3c-41a3-9223-8d6aee6921de
