### ISSUE TITLE
CopyToClipboard: Need a new component for genAI

### ISSUE THREAD

**Issue by bveerabathini** [infor-design/enterprise#8414]
**Is your feature request related to a problem or use case? Please describe.**
As per Design team request for GenAI widget need Copy component/functionality.

**Describe the solution you'd like**
Need CopyToClipboard functionality like ctrl+c and then we can paste it anywhere.

**Describe alternatives you've considered**
There is a copyToClipboard on lime's DialogService , but unable to paste using ctrl+v.
It is just the content is shown in dialog.

**Additional context**
Please see the Figma design(rounded/ticked in yellow) here for the Copy provided by Design team.
<img width="364" alt="image" src="https://github.com/infor-design/enterprise/assets/85981034/520759d7-014d-47b4-82b8-e24b9b5ae5c4">
Infor LN Widget Team

**Comment by tmcconechy** [comment]
@bveerabathini where did this design come from? Do you have the design contacts and figma file for a better explanation of it all?

For the actual problem you could try https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript (not sure if this is anything more than a button)

**Comment by bveerabathini** [comment]
@tmcconechy ,
Alicia An from Design team suggested this . Here is the Figma link,
https://www.figma.com/file/KYl8ZGq5gnzZZtkRkTl0o2/GenAI?type=design&node-id=1142-11466&mode=design&t=Olnzeq48xGIMFLPz-0

**Comment by tmcconechy** [comment]
Thanks @bveerabathini can you point me at the section in this doc? Not seeing the description of the copy button? If you right click you can copy a link

![Screenshot 2024-02-06 at 9 57 02 AM](https://github.com/infor-design/enterprise/assets/814283/ddd472ef-fe42-4fc7-82b6-7ac26aaf63c8)

**Comment by bveerabathini** [comment]
@tmcconechy ,
Here is the link
https://www.figma.com/file/KYl8ZGq5gnzZZtkRkTl0o2/GenAI?type=design&node-id=1928-46198&mode=design&t=W9Y9ZjDWhE3wpxN3-4
<img width="161" alt="image" src="https://github.com/infor-design/enterprise/assets/85981034/26198117-2dc3-4a9d-8061-b1ac06a25022">

**Comment by lucacolumbu** [comment]
We are closing this ticket, please go ahead and implement it in your code, thanks.
