### ISSUE TITLE
DataGrid column header doesn't show ellipsis and tooltip shows filter information

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#842]
When a column's formatter is set to Formatters.Ellipsis and the datagrid has the option of enableTooltips, a column's header does not show the '...' when the column's width is to small to display the full column name.

Additionally, if the column has a filter, the tooltip contains filter information.  The tooltip should just display the column's name.

1. Go to datagrid/example-filter.html
2. Add the datagrid option of 'enableTooltips: true'
3. Change the formatter of the 'activity' a/o 'productName' column to use the formatter of Formatters.Ellipsis
4. Make the width of the column smaller so the '...' should be shown on cells within the column and header
5. Mouse over the column header

**Expected behavior**
Mouse over the column header when full name is not shown the value should have an '...' and the tooltip should only show the header name (and not filter information)

See attached file.
![soho-header-tooltips](https://user-images.githubusercontent.com/39804038/46037469-cc1bc200-c0cd-11e8-84b8-19b85f3acb5d.gif)

**Comment by tmcconechy** [comment]
The header wasnt part of the formatter. So calling this an enhancement.

**Comment by lipetzan** [comment]
No, but will do.

**Comment by lipetzan** [comment]
This appears to still be an issue on our mainline stuff

**Comment by tmcconechy** [comment]
Ok, that part we did fix here https://github.com/infor-design/enterprise/issues/955
Showing as passed tests on the example http://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-with-tooltip.html

**Comment by tmcconechy** [comment]
The only issue we can see left on this issue is:
- edit http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
- make enableTooltips: true
- resize a header so the text wont show
- hover - the tooltip will show.

The only issue with this case is the text is not in ellipsis

**Comment by janahintal** [comment]
QA Passed. Will Move to Done.
Tested in: https://4170-beta0-enterprise.demo.design.infor.com/components/datagrid/test-ellipsis.html across all browsers.
