### ISSUE TITLE
Cross-Site Scripting (XSS) when updating a tree node

### ISSUE THREAD

**Issue by SB-Infor** [infor-design/enterprise#8427]
This is related to: https://github.com/infor-design/enterprise/issues/7631

**Describe the bug**
When updating a tree, users can use cross-site scripting to bypass any protection (escaping).  This was fixed in 7631 for adding a tree node.  We need the same fix applied to 'updating' a tree node.

**Expected behavior**
The code should protect against XSS.  We create and update trees based on user input.

**Version**
v4.91.0

**Screenshots**

**Platform**
 - Infor Application/Team Name: SunSystems
 - Device: N/A
 - OS Version: N/A
 - Browser Name: All
 - Browser Version: 121.0.6167.140 (Official Build) (64-bit)

**Additional context**

**Comment by yohannahbautista** [comment]
@SB-Infor  @tmcconechy @ericangeles 
Hello, is the scenario similar to this example? https://main-enterprise.demo.design.infor.com/components/tree/test-escape-node.html
I've checked by changing the update text to `<a href="#" id="home">'\"><img src=x onerror="errorMessage()">'</a>` and no error message pops up

**Comment by ericangeles** [comment]
@SB-Infor, can you check it on your end?

**Comment by SB-Infor** [comment]
It would be updating nodes so they contain text such as the above. Or if a node name contains escaped characters such as single quotes. We're having issues where escaped characters aren't unescaped (eg single quote appearing as &#39).  In 'addNode()', this is handled with the call to xssUtils.unescapeXML(). There is no check/call to this method in updateNode().

**Comment by ericangeles** [comment]
Perhaps, could you please create a StackBlitz with an XSS issue in the `updateNode`? That would be helpful.

https://stackblitz.com/edit/ids-quick-start-1730

**Comment by SB-Infor** [comment]
This will take some time as I need to get up to speed on using stackblitz.

The issue we have is that we pass through a new node name containing escaped characters: Eg Updated 'Node' would be escaped and passed in as: Updated &#39;Node&#39;.  

If this is passed into the 'addNode()' method, it's displayed as: Updated 'Node' as expected, as there is a check to unescape escaped characters.

If this is passed into the 'updateNode()' method, it's displayed as: Updated &#39;Node&#39; as there is no such check.  Hard coding the check into our sohoxi.js file solved this issue.

**Comment by SB-Infor** [comment]
[test-escape-update-node.zip](https://github.com/infor-design/enterprise/files/14446823/test-escape-update-node.zip)

I've attached an updated version of test-escape-node, showing how updateNode() doesn't unescape the node name.
