### ISSUE TITLE
Bar: Axis label visibility

### ISSUE THREAD

**Issue by ericangeles** [infor-design/enterprise#8431]
**Describe the bug**

There are some cases where the axis label is not visible because it uses the `em` unit. Given that `em` is dependent on the parent's font-size, it becomes essential to explicitly include the font-size property within the `axis-label` element. This ensures that the axis label does not rely on other parent elements for its font size, mitigating the possibility of encountering situations where the parent elements lack a specified font size.

**Expected behavior**
We need to explicitly add font-size in the `<g class="axis-labels">`

```csss
.axis-labels {
  font-size: 1.6rem; // based in the .row font-size but open for discussion
}
```

**Version**

- ids-enterprise: 4.88.0

**Additional context**
Reported here https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1706860686874?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1706860686874&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1706860686874

**Comment by tmcconechy** [comment]
So is the fix just using `px` instead @ericangeles ? If so thats fine by me.
