### ISSUE TITLE
Header Tabs: Tabs titles always have max-width

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#8434]
**Describe the bug**
_new-tab-header.scss sets a max-width to 215px for everything. Update this use the setting adding in https://github.com/infor-design/enterprise/pull/7674/files#diff-92dcf78247157c92c1bfb22474704ab9536d7c78aff92d19fb440378719bd9fe to be checked, and not always set the max-width.

Also, it would be nice if truncated tabs had a tooltip that displays the complete title.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html
2. See that the first tab is truncated.
3. Hover over the truncated tab and see that there is no tooltip.

**Expected behavior**
Header tabs should take advantage of the setting introduced for module tabs.

**Version**

- ids-enterprise: 4.92.x

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/22107636/311e7706-0314-4aab-941b-fc6b6ab069e3)

**Platform**
 - Infor Application/Team Name: Landmark
 - All

**Comment by tmcconechy** [comment]
@tjamesallen15 (cc @ericangeles)

Can you check this one. Since you did https://github.com/infor-design/enterprise/pull/8418 the way i would fix it is

a) Make sure that header tabs also uses the maxWidth like module tabs and add an example
b) and remove that css and make sure by default neither makes the maxWidth unless specified (default is no maxWidth on both)

**Comment by vonnyw** [comment]
@tmcconechy requesting this to be patched in 4.92 please

**Comment by tmcconechy** [comment]
@vonnyw if we do we have to include https://github.com/infor-design/enterprise/pull/8418 (dont think it should be a problem) just mentioning in case that changes the calculation.

Will patch with https://github.com/infor-design/enterprise/pull/8425 when they are fixed (holiday in manilla)

**Comment by vonnyw** [comment]
Yeah, not a problem with including #8418, thanks Tim!

**Comment by tjamesallen15** [comment]
what's the default tab size for normal tabs?

for module tabs it is 120px. is it the same for normal tabs too? it might be different, just want to clarify.

@tmcconechy @ericangeles

thanks!

**Comment by tmcconechy** [comment]
Can we try to remove the newer “hard coded” width so it worked like before we added the new max width setting and only if max width if the setting is applied? Thanks @tjamesallen15

**Comment by tjamesallen15** [comment]
> Can we try to remove the newer “hard coded” width so it worked like before we added the new max width setting and only if the setting is applied? Thanks @tjamesallen15

Wait, this one?
![image](https://github.com/infor-design/enterprise/assets/34049950/d7f7b49d-6dd4-45e7-86a1-2a8559764978)

**Comment by tmcconechy** [comment]
This one https://github.com/infor-design/enterprise/pull/7674/files#diff-92dcf78247157c92c1bfb22474704ab9536d7c78aff92d19fb440378719bd9fe

Should only have a maxWidth if it’s set, so it works as before this change

**Comment by tjamesallen15** [comment]
> This one https://github.com/infor-design/enterprise/pull/7674/files#diff-92dcf78247157c92c1bfb22474704ab9536d7c78aff92d19fb440378719bd9fe
> 
> Should only have a maxWidth if it’s set, so it works as before this change

got it @tmcconechy , thanks!
