### ISSUE TITLE
About: Copying content enhancement 

### ISSUE THREAD

**Issue by hey-yall** [infor-design/enterprise#8438]
**Is your feature request related to a problem or use case? Please describe.**
This was requested during the workshop

Please fix the copy behavior in the About dialog. Currently functionality copies all background information. Users need a way to easily copy the About info to paste into other applications. 

**Describe the solution you'd like**
Please provide a solution so that Ctrl + A and copying only pulls the content within the About feature and not the background info

**Describe alternatives you've considered**
We discussed having a Copy button placed in the component, but decided that updating the Ctrl + C functionality would be best for consumers. 

**Additional context**
Tracked under Jira ticket https://inforwiki.atlassian.net/browse/IDS-1591

**Comment by hey-yall** [comment]
@tmcconechy Hi Tim! Please help me understand if this issue has been solved. I see https://github.com/infor-design/enterprise/issues/8414 is closed, but does that mean the Ctrl + C functionality in the About modal has also been updated?

**Comment by karinpb** [comment]
@tmcconechy  If you read the ticket again support get screenshots of the about dialog and would like a better way to copy the information. A button or link to copy might at least get some users to not just printscreen and then not everything is visible. Or should you increase the size of the dialog? Important information is in the bottom and selecting HTML does not seem like a viable solution that people would use. I also don't think that a user would just ctrl+c and expect text to be copied on the dialog. I would printscreen it unless there was some link or button to click to copy the information that I would see. 

So when you always get this:
![image](https://github.com/infor-design/enterprise/assets/7961438/e404fd72-ff01-408c-93f3-980ba4eb6a39)
But you are interested in all the information at the buttom and you need to ask them again becuase they didn't scroll then that would be my interpretation of the ask. Perhaps making the dialog bigger would be the best approach, but I hope that gives more context.

**Comment by hey-yall** [comment]
Hi @karinpb, thank you for the additional information! The product team will address adding buttons to the About modal in a future iteration of the design system. Right now, the quickest fix is to rewrite the Copy/Paste functionality to only capture relevant data. 

@tmcconechy -- Currently, when the user copies all About modal info via Ctrl + A and Ctrl + C, it also copies background information outside the modal. See this pic for explanation: 

![Screenshot 2024-04-04 at 7 52 50 AM](https://github.com/infor-design/enterprise/assets/122995837/ff821887-fb71-45d0-a370-9d7b84a6b680)

For the current iteration, can we fix the Ctrl + A and Ctrl + C functionality so it selects/copies only the info set in the scrollable textarea? This would be a quick win for users copying the About info. Thanks!

**Comment by tmcconechy** [comment]
@hey-yall you need to click in and select it. Its a bit awkward. But we cant really control what the user selects.

<img width="682" alt="Screenshot 2024-04-04 at 10 13 21 AM" src="https://github.com/infor-design/enterprise/assets/814283/92f655d9-6ecb-4426-8ff2-40b2d853b102">

I think we could do the following

- make it taller (remove any uneeded info)
- add a copy button (easy just need placement and a icon selection)
- could try and make it select all the text when you click on it to make it easier (possible "quick win")

So i suggest we go ahead with the design changes and expediate them if this is a big issue.

**Comment by hey-yall** [comment]
@tmcconechy and @karinpb -- Discussed with the design team and will add a button. Designating as high priority. Tracking design work in associated Jira ticket.

**Comment by hey-yall** [comment]
Hi @tmcconechy ! Please move forward with this issue! 

We decided to add a Copy icon button below the textarea on the right side of the About modal.

Please let me know if you have any questions. Thanks!

**Comment by tmcconechy** [comment]
@hey-yall where should we show it ? Here:

<img width="514" alt="Screenshot 2024-04-04 at 2 40 15 PM" src="https://github.com/infor-design/enterprise/assets/814283/7c6b3108-73b0-43c1-99df-35ab9de5e997">

**Comment by tmcconechy** [comment]
@hey-yall for mobile reasons might work better around here:
<img width="624" alt="Screenshot 2024-04-04 at 2 52 08 PM" src="https://github.com/infor-design/enterprise/assets/814283/bcbb2453-de16-4092-a2a1-ab2320f1a28c">

**Comment by hey-yall** [comment]
@tmcconechy Designers want it below the textarea on the right side. Like this:

<img width="624" alt="319735862-bcbb2453-de16-4092-a2a1-ab2320f1a28c" src="https://github.com/infor-design/enterprise/assets/122995837/c4a1dbcb-57bc-4295-bdb0-a3018e85aa9b">

**Comment by tmcconechy** [comment]
ok @hey-yall please check it out at https://about-copy-enterprise.demo.design.infor.com/components/about/example-index.html for approvals

**Comment by hey-yall** [comment]
Approved. Great work!

**Comment by glenlieorillo** [comment]
This has been tested and passed.

https://github.com/infor-design/enterprise/assets/102151352/286a4079-ea4d-48ae-b30a-1654b3083dfd
