### ISSUE TITLE
Datagrid: edited cell showing encoded value when setting rowStatus

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#8444]
**Describe the bug**
In datagrid, after editing a cell with a special character the cellChange event listener makes a call to update rowStatus.  The encoded value is displayed in the cell.

**To Reproduce**

1. Using the attached example, 'http://localhost:4000/components/datagrid/example-editable-with-row-status.html'
2. Click on Activity cell for row 3.
3. Type in a special character (for example, '<', '>', '&')
4. Exit the cell
5. Notice the value is encoded

**Expected behavior**
Display value is not encoded.

**Version**

- ids-enterprise: v4.92

**Additional context**
Landmark will need a patch to v4.92

**Comment by claudenbach** [comment]
[Git-8444.zip](https://github.com/infor-design/enterprise/files/14289234/Git-8444.zip)

**Comment by tmcconechy** [comment]
Maybe the way to approach this is to revert https://github.com/infor-design/enterprise/pull/8425 and find the real cause.

So far I found:

https://4901-enterprise.demo.design.infor.com/components/datagrid/example-editable.html -> works
https://4910-enterprise.demo.design.infor.com/components/datagrid/example-editable.html -> does not
 
https://github.com/infor-design/enterprise/compare/4.90.1...4.91.0 -> seems like the diff but not sure so i dont see anything

Was thinking it was this https://github.com/infor-design/enterprise/compare/4.90.1...4.91.0#diff-13c32b0c73b40992aa6d376fb22d6746845a3b7d6d2545e19bd30687bcabb5a5R10381 but it did not solve so something along these lines
