### ISSUE TITLE
Icons: not displayed in classic

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8450]
**Describe the bug**

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/icons/example-logos.html
2. Switch to Classic view'
3. See error

**Expected behavior**
icons should be properly displayed and visible

**Version**

- ids-enterprise: v4.93.0-dev

**Screenshots**
<img width="890" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/191346d9-bc46-48f5-bbb6-3342b13e1784">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
@jbrcna we are'nt fixing Classic anymore. So will close this. Especially with icons, not getting any design support on the old icons
