### ISSUE TITLE
Calendar: Turquoise border color is blue

### ISSUE THREAD

**Issue by allanalvarez** [infor-design/enterprise#8452]
**Describe the bug**
In the Month view, the color: turquoise have blue border color, while in the Week and Day views, the border color remains turquoise

**To Reproduce**
set color: "turquoise". Notice the border color is blue. Other colors have same border color.

**Expected behavior**
If color set to turquoise the border color should also be turquoise

**Version**
IDS Enterprise Components - v4.90.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/41406875/74596d51-1a12-463f-b217-17fb15d9187a)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Im seeing it as not showing the right color but showing it as white. So agree there is a bug here. To dev that picks this up. Please make an example with all colors showing
