### ISSUE TITLE
Calendar: Display starts and ends in the tooltip/title

### ISSUE THREAD

**Issue by allanalvarez** [infor-design/enterprise#8453]
**Is your feature request related to a problem or use case? Please describe.**
In the calendar, when hovering over an event, a tooltip/title displays the subject of the selected event. It would be beneficial to additionally include the schedule of date and time within the tooltip/title, providing users with a quick overview of the event's schedule.

**Describe the solution you'd like**
The solution will apply across all views - Month, Week, and Day. This feature is particularly useful for all-day events, as users should be able to view the schedule simply by hovering over the event.

By default configuration is true and user have an option to enable or disable it.  Can display the value of starts and ends
![image](https://github.com/infor-design/enterprise/assets/41406875/69dbd6a7-2800-4129-b9ed-3af4873f1888)

**Additional context**
Current Tooltip of an calendar. Only display the subject
Month
![image](https://github.com/infor-design/enterprise/assets/41406875/b82a3c71-9557-4a23-b79d-4e6fe7b9d009)
Week
![image](https://github.com/infor-design/enterprise/assets/41406875/0a63a299-89a0-4a01-aa40-6e2c7812323b)
Day
![image](https://github.com/infor-design/enterprise/assets/41406875/3d53d913-988b-4808-9dd5-8823a2219203)

Expected output is to try to mimic the outlook behavior when you hover an event
![image](https://github.com/infor-design/enterprise/assets/41406875/034f23ad-87f7-4553-9df7-77d272b730df)

**Comment by tmcconechy** [comment]
@allanalvarez 

1. How did you get the tooltip to show up? I dont see it in any examples?
2. What exact fields in the data do you think it should show? Im not seeing how to show it in outlook i just get a popup there. Which is similar to what we do already

![Screenshot 2024-02-19 at 10 14 44 AM](https://github.com/infor-design/enterprise/assets/814283/91a16265-ac97-4173-9f39-0dee4073a18d)

**Comment by allanalvarez** [comment]
Hello @tmcconechy ,

1) Just point the mouse to the event. Tooltip will just show automatically.
2) In the outlook just point the mouse to the event and will show the tooltip.  I'm thinking it will show the fields from **starts** and **ends**. It will beneficial for the user to see the event schedule without clicking any event

![image](https://github.com/infor-design/enterprise/assets/41406875/117e0169-a8f9-4acb-afa6-80aec31e84e7)

**Comment by tmcconechy** [comment]
Not seeing our tooltip on the calendar examples. But i think this is valid

**Comment by lucacolumbu** [comment]
@allanalvarez can you provide an example of how you are getting the tooltips in the IDS Calendar component?

**Comment by tmcconechy** [comment]
@allanalvarez i found the tooltip on https://main-enterprise.demo.design.infor.com/components/calendar/test-ajax-events.html I knew it was there 👍🏻 

Right now it's taking `"comments": "Short getaway",` field. Would it be possible to just fill in that with the text you want?

**Comment by allanalvarez** [comment]
> @allanalvarez i found the tooltip on https://main-enterprise.demo.design.infor.com/components/calendar/test-ajax-events.html I knew it was there 👍🏻
> 
> Right now it's taking `"comments": "Short getaway",` field. Would it be possible to just fill in that with the text you want?

I'm thinking to mimic the behavior of outlook. Not only display the event subject or a specific field but it will show also the starts and ends schedule.  This will beneficial especially when there's an multiple data in a day.

**Comment by allanalvarez** [comment]
Maybe this would also help. In week view we show the subject and the starts-ends time. It would be nice if we also show that in tooltip

![image](https://github.com/infor-design/enterprise/assets/41406875/938ec4d9-d4a8-4ca7-91c4-b8b5907250a1)

**Comment by tmcconechy** [comment]
Isnt i a bit redundant to show the date so many places? Just my opinion. I will review with Design

**Comment by allanalvarez** [comment]
> Isnt i a bit redundant to show the date so many places? Just my opinion. I will review with Design

This would be helpful in user experience on month view since in month view if an event is in multiple days it only display the Date in the event details. It would be nice if they can also see the specific date and time of an events if they hover the event

**Comment by tmcconechy** [comment]
ok will review with our design in grooming and see what they want to do.

**Comment by tmcconechy** [comment]
@allanalvarez what team are you on?

**Comment by tmcconechy** [comment]
@allanalvarez would this work if we let you put other fields in the existing settings. Also, can you prioritize all the issues? so we can select one or two.

```
comments: "{startDate} is in <br>  the comment"
subject: "{starts} = {ends} is in the comment {status}"
```

**Comment by allanalvarez** [comment]
Hi @tmcconechy , I have listed the tickets I filed related to Calendar and arranged them in priority order

1. https://github.com/infor-design/enterprise/issues/8490
2. https://github.com/infor-design/enterprise/issues/8514
3. https://github.com/infor-design/enterprise/issues/8469
4. https://github.com/infor-design/enterprise/issues/8453
