### ISSUE TITLE
Datagrid Editable Cell Color Issue in Dark Theme

### ISSUE THREAD

**Issue by clausvaever** [infor-design/enterprise#8459]
**Describe the bug**
It is not possible to see which cells are editable in the Datagrid when having dark theme.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Select Dark Theme
3. Notice the indifference between editable and non-editable cells. (at least on my monitor)

**Expected behavior**
It should be possible to see the difference between editable and non-editable cells for dark theme in the Datagrid exactly as it is in Light and Contrast themes.

**Version**
- ids-enterprise v.4.9.2
- ids-enterprise-ng v.17.4.3

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/29476583/fe0165c0-9c44-4be4-9fde-fe158fd5690c)
![image](https://github.com/infor-design/enterprise/assets/29476583/3d0f4359-ed9e-4e44-8244-6f3a03e98bb4)
![image](https://github.com/infor-design/enterprise/assets/29476583/006eb0b7-af11-4d4b-a15a-84c77d16c544)

**Comment by tmcconechy** [comment]
@ericangeles can we fit this in?
