### ISSUE TITLE
IdsDatagrid: Selected lines not intuitive when using dark mode

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise#8467]
**Describe the bug**
It is hard to understand which line is selected in the new dark mode. Which line is highlighted/selected? By experience you learn, but (for some users) it is counter-intuitive. The black lines are the ones being selected. Some users would have it the other way around.

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html?theme=new&mode=dark&colors=default
2. Click on any line
3. Selected line is same as the background which can be confusing to other users

**Expected behavior**
Selected lines should not have the same color as the background or at least have a more distinguishable identifier.

**Version**

- ids-enterprise: v4.92.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/55830499/6940b472-5ded-40a0-8569-f1fea37a3286)

**Platform**
 - Infor Application/Team Name: Infor M3
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
In the samples, there is a checkbox to indicate which lines are selected. This is not the case in our application as we do not display the checkbox as seen in the attached screenshot.

**Comment by inforandy** [comment]
tracking here for design https://inforwiki.atlassian.net/browse/IDS-1968

**Comment by ericangeles** [comment]
@inforandy can't access the jira link.

**Comment by tmcconechy** [comment]
New jira link: https://inforwiki.atlassian.net/browse/IDS-1968
