### ISSUE TITLE
Calendar: calendar.api.monthView.currentDate execute twice on week view and day view

### ISSUE THREAD

**Issue by allanalvarez** [infor-design/enterprise#8469]
**Describe the bug**
I'm utilizing the onRenderMonth.  I notice that calendar.api.monthView.currentDate is executed twice when user move into next month using the week or day view.

1) Load the page (IDSCalenderOnRender.html) 
2) Navigate to the month until April
3) Switch the view to the week view
4) In the "Upcoming Events" section and select either the May 1-2 or May 3 event.

**Actual Result**
Notice that the alert will execute twice. It will alert May 1 and followed by April 28.  

**Expected behavior**
The alert should only execute once. Should only display the May 1

**Version**

- ids-enterprise: v4.90

**Screenshots**
Use this file in IDS to load the calendar
[IDSCalendarOnRender.zip](https://github.com/infor-design/enterprise/files/14354487/IDSCalendarOnRender.zip)

https://github.com/infor-design/enterprise/assets/41406875/92d98138-5394-464e-83dd-693cb71a4b0c

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
I think that code may need to fire twice. But we may be able to fire the event just once. Assuming this is very important?

**Comment by allanalvarez** [comment]
Yes, it is important wherein duplicate data arises from both weekly and daily views, triggered by the code executing twice
