### ISSUE TITLE
Datagrid - Reset to default is not reseting the filter

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#847]
**Describe the bug**
Reset to default is not reseting the filter completely.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html
2. type any condition that filters
3. reload the page
4. under the ... menu - select reset to default

**Expected behavior**
Expect this to reset the filter to show all items. But it is keeping the filter.

**Additional context**
Found when testing https://github.com/infor-design/enterprise/pull/846
Also should add a unit test for this.

**Comment by davidcarlsonberg** [comment]
Trigger reload of page on "Reset to Default"?

**Comment by tmcconechy** [comment]
Yeah i see it does work, but i wouldnt solve the issue that way. Should be able to just call render again in the grid code when rest to default is called.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-save-settings.html
http://master-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html
Passed QA testing across all browsers, Reset to Default is now clearing the applied filters.
