### ISSUE TITLE
Datagrid: Text moves upward upon clicking the cell

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8472]
**Describe the bug**
The text moves upward upon clicking the cell.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-books.html
2. Click any cell from `Book Currency` to `Deprecation History`
3. Notice the text in the cell moves upward upon clicking the cell

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1792" alt="image" src="https://github.com/infor-design/enterprise/assets/102151352/63bba061-ae04-4951-a0c3-33d52255e7a6">

**Platform**
 - All major browsers

**Comment by tmcconechy** [comment]
@ericangeles lets try to fix this
