### ISSUE TITLE
BlockGrid: Block grids alignment are shifted to the right in RTL

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise#8482]
**Describe the bug**
In the 1st page of the paging example for the Block Grid, the blocks are shifted to the right in RTL.

**To Reproduce**
1. Go to [https://main-enterprise.demo.design.infor.com/components/blockgrid/example-paging.html](https://main-enterprise.demo.design.infor.com/components/blockgrid/example-paging.html)
2. Then go to [https://main-enterprise.demo.design.infor.com/components/blockgrid/example-paging.html?locale=ar-EG](https://main-enterprise.demo.design.infor.com/components/blockgrid/example-paging.html?locale=ar-EG)
3. Compare the two sites, the blocks are shifted as well to the right in the 1st page for the RTL version

**Expected behavior**
Blocks are still centered in the 1st page

**Version**
- ids-enterprise: 4.93.0-dev.0

**Screenshots**
**RTL**
![image](https://github.com/infor-design/enterprise/assets/156752175/c9449785-18a0-45db-b553-50f195592e52)

**LTR**
![image](https://github.com/infor-design/enterprise/assets/156752175/e116262e-84a4-418e-95f8-cb354a9d7dfd)

**Platform**
 All major browsers

**Comment by tmcconechy** [comment]
Fixed as per https://oxford.awsdev.infor.com/infor-design/enterprise/-/merge_requests/37#7ee86a895998ce25791f58b2989084fcb5a83623
