### ISSUE TITLE
DataGrid: updateRow - Apostrophes is escaped to &apos; for French language

### ISSUE THREAD

**Issue by InforBG** [infor-design/enterprise#8483]
**Describe the bug**
In DataGrid, when update row with French language, the Apostrophes is escaped to `&apos;`.

**To Reproduce**

1. Go to 'test-dirty-change-cell-externally.html'
2. Edit the code the line have gridApi.updateRow to below. It has the "l'unité de gestion".
```js
      gridApi.updateRow(0, { id: 0, productId: 2142201, productName: 'Compressor', activity:  "l'unité de gestion", quantity: 50, price: 210.99, status: 'OK', orderDate:  '', portable: false, action: 1 });
```
4. Click on 'Change Cell' button
5. Check the first row
6. See the problem: "l'unité de gestion" is changed to "l&apos;unité de gestion".

**Expected behavior**
The French  words "l'unité de gestion" should not be changed.

**Version**

- ids-enterprise: [v4.91.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/114138479/ea0f7c73-68e7-4cfa-b5eb-5f70129420a1)

**Additional context**
ids-enterprise: [v4.86.0] doesn't have the problem.
It seems to be a regression issue caused by https://github.com/infor-design/enterprise/pull/8180/files#diff-13c32b0c73b40992aa6d376fb22d6746845a3b7d6d2545e19bd30687bcabb5a5.

**Comment by tmcconechy** [comment]
@InforBG This was already fixed on https://github.com/infor-design/enterprise/issues/8285 so I think this is a duplicate. If you want the fix take 4.92.4 which is the latest and you should be good.

**Comment by tmcconechy** [comment]
@InforBG  @rvaja-infor

Ok done. I made a patch with https://github.com/infor-design/enterprise/issues/8285 and https://github.com/infor-design/enterprise/issues/8479

Its: https://www.npmjs.com/package/ids-enterprise/v/4.91.1

**Comment by InforBG** [comment]
Thank you so much.
