### ISSUE TITLE
Tabs: Cannot read properties of undefined (reading 'prop')

### ISSUE THREAD

**Issue by adamzhang1932** [infor-design/enterprise#8488]
**Describe the bug**
If I want to create a 'vertical' tabs without initial tabs, there will be an error:
tabs.js:3959 Uncaught TypeError: Cannot read properties of undefined (reading 'prop')
    at Tabs.positionFocusState (tabs.js:3959:50)
    at Tabs.add (tabs.js:2701:12)

**To Reproduce**

1. Download the zip file and unzip it.
[test-no-initial-vertical-tabs.zip](https://github.com/infor-design/enterprise/files/14383873/test-no-initial-vertical-tabs.zip)

2. Put the 'test-no-initial-vertical-tabs' file to IDS source code pages: app/views/components/tabs.
![image](https://github.com/infor-design/enterprise/assets/151612185/50823e29-06a3-44ec-b43c-fbb5e2853e95)

3. Run it and test it in your local machine.
http://localhost:4000/components/tabs/test-no-initial-vertical-tabs.html

4.Then click 'Add Tabs' button at the first time, you will get the error.
![image](https://github.com/infor-design/enterprise/assets/151612185/b05d6cb5-1b51-43b9-8599-2e55e6dca2da)

**Expected behavior**

**Version**

- ids-enterprise: v4.92.4, and this problem might from v4.92.0

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor SunSystems
 - Device: 
 - OS Version: 
 - Browser Name: 
 - Browser Version: 

**Additional context**
The condition to reproduce this issue is that:
1.The tabs is 'vertical'.
![image](https://github.com/infor-design/enterprise/assets/151612185/976af4c8-d474-4107-be1d-78ace6231ec7)

2.The tabs has zero tab after initializing.

**Comment by tmcconechy** [comment]
@ericangeles lets see if we can add this one? Seems important to keeping tabs working

**Comment by adamzhang1932** [comment]
Just a friendly reminder, if it is a 'vertical' table, the variable 'tablistContainer' might be undefined, and this variable is called in many places in 'tabs.js' file, so it might better to check it carefully.
![image](https://github.com/infor-design/enterprise/assets/151612185/93826608-13f6-4178-a87b-c4591f0d5ac7)

**Comment by tmcconechy** [comment]
@adamzhang1932 can you test the PR and see if it fixes it for you. Just add a comment on https://github.com/infor-design/enterprise/pull/8495 

There is a link for testing it https://8488-tabs-undefined-prop-enterprise.demo.design.infor.com/components/tabs-vertical/test-no-initial-vertical-tabs.html but if you need to build it and copy it with `npm run build:release`

**Comment by adamzhang1932** [comment]
@tmcconechy I tested it today, and the current problem in this issue was fixed, thank you very much.
