### ISSUE TITLE
HTML character code special characters prevent search highlighting

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#849]
**Describe the bug**
Words are not highlighted upon search when a HTML character code special character exists in same cell as word that is searched for.

**To Reproduce**
Browse to http://localhost:4000/components/datagrid/example-keyword-search.html and search in filter for keyword. Type in a word that exists in a cell with a special character. Notice the word doesn't get highlighted upon search.
I've noticed % and # get highlighted but this may be because it appears at the end of the character string or because it isn't part of HTML character code formatting such as are $ and &.

**Expected behavior**
When searching for a word that exists in a cell with a special character ($, &) the word should be highlighted (bolded) upon execution of search.

**Platform**
Seemingly all browsers but noticed on macOS Chrome most recent version.

**Comment by davidcarlsonberg** [comment]
Also noticing that parentheses in search throw a RexExp error.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/example-keyword-search.html
Passed QA testing across all browsers, special characters are highlighted upon searching.
