### ISSUE TITLE
Calendar: When the start and end dates differ, and "Day" view is chosen, the calendar won't show full session hours.

### ISSUE THREAD

**Issue by allanalvarez** [infor-design/enterprise#8490]
**Describe the bug**
When session start date and end date are set to different dates and calendar view selected is "Day" view, calendar will not be able to display the full session hours. (Not encountered in Month and Week view)

**To Reproduce**
When session start date and end date are set to different dates and calendar view selected is "Day" view, calendar will not be able to display the full session hours. (Not encountered in Month and Week view)

1. Go to Calendar Day view
2. Un check the All Day
3. Create an event
    *Starts: Feb 26, 2024 11PM
    *Ends: Feb 27, 2024 4AM
5. Submit

For clear example:
1) Load the IDSCalendarOnRender.zip and used the IDSCalendarOnRender.html in IDS enterprise builder
[IDSCalendarOnRender.zip](https://github.com/infor-design/enterprise/files/14489804/IDSCalendarOnRender.zip)

2) Focus on data below. Notice that the starts and ends time is different day but the time difference is less than 24hours

```
    {
      "id": "21",
      "subject": "Quick bite",
      "comments": "Chick-fil-a Lancaster",
      "starts": "2024-03-05T23:00:00.000",
      "ends": "2024-03-06T05:00:00.000",
      "type": "admin",
      "isAllDay": "false"
    },
```
    
3) Switch the calendar view to Week or Day view
4) The quick bite doesn't show in the calendar either of Week or Day view.

**Actual Behavior**
Created event won't show in the Day view of calendar

**Expected behavior**
Event will map the schedule in day view

**Version**
- ids-enterprise: [ v4.90]

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@allanalvarez im not clear on this? Are you talking about this page? https://main-enterprise.demo.design.infor.com/components/calendar/example-index.html

I think the steps need to be clarified a bit more.. Especially because all day events cant have times.

**Comment by allanalvarez** [comment]
Hi @tmcconechy , I attached IDSCalendarOnRender.zip and updated the ticket description so that we can see the actual behavior.

**Comment by tjamesallen15** [comment]
I just want to clarify something on this one. @tmcconechy  @allanalvarez 

The available hours on the week view and day view are just from 7am - 7pm.

The test case was, May 5 - 11 PM to May 6 - 5AM. I can't display since its not on the available hours?

cc @ericangeles

**Comment by tjamesallen15** [comment]
I just want to clarify something for this ticket. 

The available hours on the week view and day view are just from 7am - 7pm.

The test case was May 5 - 11 PM to May 6 - 5 AM. From my point of view, I cannot display it since its not on the available hours displayed on the UI or there is another configuration to make the day and weekview show 00:00 AM to 11:59 PM?

Thanks in advance.

cc @ericangeles @tmcconechy  @allanalvarez
