### ISSUE TITLE
Dropdown, lookup: Inconsistent styling

### ISSUE THREAD

**Issue by bartlomiej-k** [infor-design/enterprise#8492]
**Describe the bug**
I'm not sure wether it's a bug or feature considering the git blame messages from about 10 years ago, but it's inconsistent with other input components. Dropdown is displayed within `div.dropdown-wrapper` element that is styled by default using `margin-bottom: 20px`. When it's placed inside a `.field` wrapper, this margin is being removed, because the wrapping element `.field` already contains this margin, so otherwise the field would be misaligned when placed next to other fields. However, because this margin is removed only when the dropdown is wrapped with `.field`, it's misaligned when this class is not needed/not wanted (it has about 400 rules that we have no control of and it often causes side effects). The same happens for lookups, which are placed inside `span.lookup-wrapper`.

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-quick-start-1730-czp8pg
2. Observe that in 'Without field class' section dropdown and lookup are not aligned with date/time pickers, because they have `margin-bottom: 20px`.
3. Observe that in 'With field class' section all fields are aligned, because they have the same margin applied using `field` class to each field's wrapper and internal margin-bottom removed.

**Expected behavior**
To avoid breaking all existing usages of the dropdown and lookup, new classes should be added (like `dropdown-no-margin` and `lookup-no-margin`) that would remove the unwanted `margin-bottom: 20px` from the dropdown-wrapper and lookup-wrapper elements.

**Version**
- ids-enterprise: v4.92.0
- ids-enterprise-ng: v17.2.0

**Screenshots**
This is how it looks like in our application. Note that we already override the styling for lookups, what we should not be doing. 
![image](https://github.com/infor-design/enterprise/assets/49535453/27242bc7-27cb-4e4d-a6ba-5a50c2d74bbd)

**Platform**
 - Infor Application/Team Name: WFM

**Additional context**
Workaround exists - it can be overriden by custom styling, but I think it should be fixed at a library level.

**Comment by tmcconechy** [comment]
Bottom padding should be 20px when using the field class. Probably none when not loosing the field class but need to check all components there.

Also i know of inconsistencies on bottom padding on text area and file upload advanced
