### ISSUE TITLE
Pager: Is moved from datagrid class to widget-footer class on Infor Workspace refresh and hides itself

### ISSUE THREAD

**Issue by nipunbhanot** [infor-design/enterprise#8496]
**Description**
I am developing a widget containing soho-datagrid to be used on an Infor tenant. The widget contains only a button and the datagrid. The datagrid is populated from a Compass API call to Data Fabric. The pager is a part of the datagrid class when I deploy the widget. However, after a webpage (Workspace) refresh, it disappears entirely from the widget and on further inspecting, is found to be moved to the widget-footer class.

**To Reproduce**
Here is a reduced code snippet for styles and template:
export const styles = [`
    .widget-container {
        height: 500px;
    }
    .datagrid-container {
        height: 500px;
    }
    `];

export const template = `
    <div class="widget-container">
        <div class="datagrid">
            <div class="has-vertical-scroll">
                <div soho-datagrid paging="true" *ngIf="gridOptions" [gridOptions]="gridOptions"></div>
            </div>
        </div>
    </div>
`;

N/A as it includes creating a widget?

**Expected behavior**
The pager must always be visible and not move around depending on webpage refresh.

**Version**
IDS Enterprise NG 7.1.0. (InforWidgetSDK 3.0.0)
However, the Infor environment dictates the version in Homepages. Which I understand is one of the newer ones.

**Screenshots**
Pager as part of datagrid:
![pager-in-datagrid](https://github.com/infor-design/enterprise/assets/38666982/06e2675c-f983-40cd-97f7-de7db69fb35e)

After webpage refresh, becomes a part of widget-footer and is not visible in the widget:
![pager-in-widgetfooter](https://github.com/infor-design/enterprise/assets/38666982/fc4bc039-9bef-47ab-af50-f9e94e15de24)

**Platform**
 - Infor Workspaces
 - Device: Macbook Pro (N/A)
 - OS Version: macOS 14.3.1
 - Browser Name: Chrome
 - Browser Version: Version 121.0.6167.184 (Official Build) (x86_64)

**Comment by tmcconechy** [comment]
@nipunbhanot I just noticed there is a setting for this https://github.com/infor-design/enterprise/blob/main/src/components/pager/pager.js#L377

Try setting that on the pager? To disable the behavior

**Comment by nipunbhanot** [comment]
@tmcconechy this workaround definitely helped in a local setting. But for it to work on widget-SDK and Homepages, as discussed internally and recommended by you, the issue will be worked on as planned by you and the team. (adding this statement here for greater visibility w.r.t to the issue)

Thanks a lot for the help!

**Comment by tmcconechy** [comment]
@nipunbhanot if you can test the pull request. on https://github.com/infor-design/enterprise/pull/8506 against your solution that would prevent future going back and forth.

Made a fix for it

**Comment by nipunbhanot** [comment]
@tmcconechy  Thanks a lot! I will collaborate with Gustav on this as he might need to ensure that the change is reflected in widget-sdk.

**Comment by tmcconechy** [comment]
BTW if you really needed a backup plan i do believe the css could be changed so that the widget was in the correct position having looked at this issue i came that conclusion. Look at the card/widget class card-content/widget-content and footer.

But this should help
