### ISSUE TITLE
Datagrid: Clicking a hyperlink shouldn't also trigger select/deselect

### ISSUE THREAD

**Issue by eaenriquez** [infor-design/enterprise#8498]
**Describe the Issue**
In the datagrid, clicking on a row selects/deselects the whole row. But when clicking on a hyperlink in a cell, we don't want it to trigger the select/deselect. Would there be other ways to prevent it?

**To Reproduce**
1. Just render a datagrid
2. use a hyperlink formatter on a column
3. click on a hyperlink

**What did you try so far**
Tried to use the event's `stopPropagation` and `preventDefault` on the enterprise's datagrid code base locally

**Version**

- ids-enterprise: 4.91.0-dev.0

**Comment by tmcconechy** [comment]
@eaenriquez we have an option data grid for this `clickToSelect` you can set to false then only the checkboxes will select? Is this enough or do you think we need to change for when this is off and just not select on buttons/hyperlinks?

**Comment by eaenriquez** [comment]
@tmcconechy I wish the clickToSelect property would be enough, but the use case in our application (M3 ExD) is to click a row to select, ever since.

If there was a property like `shouldSelectOnHyperlinkCellClick` as a boolean (setting it to false would not trigger select/deselect) on gridOptions, that would be nice.
