### ISSUE TITLE
About: Mobile is displaying "true" for Safari 17 in Mac

### ISSUE THREAD

**Issue by NicholTamayo** [infor-design/enterprise#8502]
**Describe the bug**
Related to https://github.com/infor-design/enterprise/issues/8118, observed that the Mobile in About is displaying "true" instead of "false" for Safari 17 in Mac.

**To Reproduce**
1. Go to 'https://design.infor.com/code/ids-enterprise/latest/demo/components/about/example-index?theme=uplift&variant=light' using Safari browser in Mac.
2. Click "Show About Screen".
3. Scroll down.

**Expected behavior**
1. The Mobile should display the correct value, in this case it should be "false". or
2. We should remove this information since userAgent is deprecated.

**Version**
- ids-enterprise: 4.92

**Screenshots**
![Mac Safari 17 About](https://github.com/infor-design/enterprise/assets/79066908/5f5a10b4-d5e8-4a45-a9e2-e610c51f9085)

**Platform**
- Infor Application/Team Name: Homepages
- OS Version: Ventura 13.6.4/Safari 17
- Browser Name: Safari
- Browser Version: Version 17.3.1 (18617.2.4.11.12, 18617)

**Comment by tmcconechy** [comment]
Lets just remove it as its not that useful and unreliable
