### ISSUE TITLE
Datagrid: Searchlist icon is missing in Safari and misaligned in Firefox

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8504]
**Describe the bug**
The searchlist icon under `Product Id` column is misaligned in Mac Firefox and it is missing in Safari.

**To Reproduce**

1. Go to https://8363-datagrid-datefilter-enterprise.demo.design.infor.com/components/datagrid/test-filter-date-hide-days.html
2. Hover over the searchfield under Product ID column (Safari)
3. Notice the searchlist icon under Product ID column (Mac Firefox)

**Expected behavior**
Searchlist Icon should be present in Safari and aligned properly in Mac Firefox.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
Mac Firefox

![image](https://github.com/infor-design/enterprise/assets/102151352/21441dbf-dfe7-40ca-901c-84aeaff8ff71)

Safari

![image](https://github.com/infor-design/enterprise/assets/102151352/a1b1b427-a756-47ff-9d0f-ecc562d21fc4)

**Platform**
 - Safari and Mac Firefox

**Additional context**

**Comment by tmcconechy** [comment]
@ericangeles lets see if we can fit this in.
