### ISSUE TITLE
Timeline: Missing connecting/broken line between Items in Progress and Closed in RTL

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8510]
**Describe the bug**
Missing connecting/broken line between Items in Progress and Closed.

**To Reproduce**

1. Go to https://4930-beta0-enterprise.demo.design.infor.com/components/timeline/example-index.html?locale=ar-SA
2. Notice the connecting/broken line between `Items in Progress` and `Closed`

**Expected behavior**

**Version**

- ids-enterprise: 4.93.0-beta.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/e6ecd103-0d49-4527-a620-6dc2962da5fd)

**Platform**
 - All major browsers

**Additional context**

**Comment by glennreyesss** [comment]
Just a quick note, this also happens in our widget even if all indicators are complete.
![image](https://github.com/infor-design/enterprise/assets/126537236/ca9ea3f3-2a6e-4b58-8948-90b9b7b8b0b2)
