### ISSUE TITLE
Calendar: Data Disappearance Issue on Week or Day view when user clicked on a blank event in Week or Day view

### ISSUE THREAD

**Issue by allanalvarez** [infor-design/enterprise#8514]
**Describe the bug**
Data Disappearance Issue: Calendar Week/Day View

**To Reproduce**
Switch to week view of the calendar. Click on a blank event 

1). Refer to calendar - month view and switch to week view
2). Go to specific date where session was scheduled
3). Double click (or multiple times) any date from the calendar with no data/session 

**Expected behavior**
Data will still retain even if user double click or clicked on a blank event.

**Version**
- ids-enterprise: [v4.90]

**Screenshots**

https://github.com/infor-design/enterprise/assets/41406875/a36d7b34-b811-4563-94c5-e01ae00b6d79

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
This error occurs when double-clicking a blank event in the week view. Note that data remains on some weeks but disappears on others.
![image](https://github.com/infor-design/enterprise/assets/41406875/257450aa-1a08-4802-a673-995aef7907fb)

**Comment by tjamesallen15** [comment]
Can we retest this issue, can't seem to reproduced it on my end @infor-design/qa thanks

**Comment by tmcconechy** [comment]
@allanalvarez can you test this on the latest we do too seems resolved now, passing to QA
