### ISSUE TITLE
Dropdown: Search icon is not aligned in the datagrid's cell

### ISSUE THREAD

**Issue by kkoscielski** [infor-design/enterprise#8515]
**Describe the bug**
When I have a datagrid and type something I can see that the "search" icon is not aligned when the row height is set to small or extra small.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html
2. Change the row height to small (or extra small).
3. See the cell with the value "Shipped" on the column named "Action". When you hover it you can see that it is a dropdown.
4. Click on the cell and type a letter "o" or "s".
5. You can see that the search icon is not aligned.

**Expected behavior**
The search icon is aligned when the row height is small or extra small.

**Version**
- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="650" alt="image" src="https://github.com/infor-design/enterprise/assets/105841567/0f50958a-1219-43b9-a40b-135ad430adbb">

**Platform**
 - Infor Application/Team Name: M3
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by kkoscielski** [comment]
Team Name:  M3

**Comment by whernebrink** [comment]
I noticed, when one types something that is not in the list, the dropdown is not constrained within the datagrid:
![image](https://github.com/infor-design/enterprise/assets/73601152/60c51acf-84ea-4f45-a675-0fc2c939b21b)
