### ISSUE TITLE
Datagrid: escapes special chars in the cellchange event

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise#8516]
**Describe the bug**
In prior [issue](https://github.com/infor-design/enterprise/issues/8285) it was fixed so that when entering special chars into editable fields wasn't escaped, however, the event object for `cellchange` event still have it

**To Reproduce**

1. Go to [example-editable](https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html?theme=new&mode=light)
2. Open console
3. Enter `related[BALMAS1("TX60:\{IndexList_Items.TX60}")]` into  e.g. an activity column
4. See logged event object which has an additional `\` for the `value` prop, `rowData.activity` prop, as well as oldValue prop still escapes special chars `related[BALMAS1(&quot;TX60:&bsol;{IndexList_Items.TX60}&quot;)]`

**Expected behavior**
All mentioned props should be exactly the same as the inputted string, `related[BALMAS1("TX60:\{IndexList_Items.TX60}")]`.

**Version**
- ids-enterprise: 4.90.1 (here the values are still being escaped on the event object), but also latest.
- ids-enterprise-ng: 17.1.3 (we're currently on this one and need a patch with only the change from this version)

**Platform**
 - Infor Application/Team Name: M3

**Comment by tmcconechy** [comment]
@ericangeles can you or @yohannahbautista take a look? maybe it is as simple as calling the unescape on the variables in the events?

**Comment by whernebrink** [comment]
Due to the time frame we have, I've tried the following workaround on our side which we will have to go with for the April release:
```ts
const value = Soho.xss.unescapeHTML(rowData.initialValue);
```
Would be great if the fix can be included in next ids-enterprise-ng version (and we'll try to update for June release), but you don't have to do any other patch for now @tmcconechy. 

Thanks everyone!

**Comment by tmcconechy** [comment]
ok thanks @whernebrink  we will just include in the regular release cycle.I was going to say at one point you could run it on the event data this way 👍🏻
