### ISSUE TITLE
Toolbar: Incorrect effect shape on hover 

### ISSUE THREAD

**Issue by hey-yall** [infor-design/enterprise#8523]
In Enterprise demo site in the "[All icon buttons](https://main-enterprise.demo.design.infor.com/components/toolbar/example-all-icon-buttons.html)" demo, the hover state effect on all icons should be a square instead of a rectangle. 

Example: When hovering over the More icon on the demo site toolbar, the hover effect is square. When you hover over the Edit icon or Check icon in the toolbar, the hover effect is incorrect and displays a rectangle. 

Please correct in the demo and check if this is a more widespread issue or only affects the demo example. 

Contact @hey-yall for more questions. Thanks so much!

**Comment by tmcconechy** [comment]
@ericangeles can we see if we can squeeze this in. I noticed this too but forgot to raise an issue
