### ISSUE TITLE
Timeline: Broken when viewed in a 1x1 card

### ISSUE THREAD

**Issue by glennreyesss** [infor-design/enterprise#8524]
**Describe the bug**
The timeline component when displayed inside a 1x1 card is broken.

**To Reproduce**
Create a timeline widget and deploy using Widget SDK or OS Portal.

Here is the sample code.
[timeline.txt](https://github.com/infor-design/enterprise/files/14532222/timeline.txt)

**Expected behavior**
The timeline component should not be broken when viewed in 1x1 size.

**Version**
- ids-enterprise: v4.88.2 (Widget SDK 3.32) and v4.92.3 (OS Portal 2024.04)

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/126537236/b3f91658-0783-48b6-80d6-6e4048b08037)
![image](https://github.com/infor-design/enterprise/assets/126537236/0dc3c52b-e4fa-44be-bffa-439528801ee9)

**Platform**
 - Infor Application/Team Name: FSM Context Widgets
 - Device:
 - OS Version: Windows 11
 - Browser Name: Edge
 - Browser Version: 122.0.2365.66 (Official build) (64-bit)

**Additional context**
This has already been raised before and was already fixed and closed. https://github.com/infor-design/enterprise/issues/7278

There aren't any special patterns that were used to create the timeline component. 
Another thing to note is that the timeline component works when viewed in 2x1 size.
![image](https://github.com/infor-design/enterprise/assets/126537236/bf08812c-fb08-4f8e-9037-de47d101550e)
![image](https://github.com/infor-design/enterprise/assets/126537236/508fb3f8-a7ab-4acb-802c-b1bbf7c603fc)

**Comment by glennreyesss** [comment]
Hello @tmcconechy, what is the target date for it to be fixed? Also asking the same question for https://github.com/infor-design/enterprise/issues/8510.

**Comment by tmcconechy** [comment]
Should be able to add it in the April sprint for early May release @glennreyesss

**Comment by glennreyesss** [comment]
Hello @tmcconechy, is it possible for the fix to be included in 2024.04 (April Release) instead? The question applies to https://github.com/infor-design/enterprise/issues/8510 as well.

**Comment by ericangeles** [comment]
@tmcconechy, sure, we can add it to the April sprint board.

**Comment by anhallbe** [comment]
@tmcconechy @ericangeles @tjamesallen15  would it be possible to patch this for 4.93?

I know it's a lot to ask, but if possible we'd need it for our June release which is supposed to be locked by tomorrow. Or at the very latest end-of-week

**Comment by tmcconechy** [comment]
@anhallbe added a patch version `ids-enterprise-ng@17.5.10` with time line fixes. Will do the 4.94 one next.
