### ISSUE TITLE
Modal: {0} appeared on the character count

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8532]
**Describe the bug**
`{0}` appeared on the character count.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/modal/test-draggable.html or https://7019-modal-draggable-enterprise.demo.design.infor.com/components/modal/test-draggable.html
2. Click on the Show Modal button
3. Enter any text on Notes up to the maximum text length
4. Notice the character count

**Expected behavior**
`{0}` should not be included in the displayed text. 

**Version**

- ids-enterprise: 4.93.0-dev.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/a0cd95e0-96a9-4f20-9bba-c04e6ccbc0ee)

**Platform**
 - All major browsers

**Additional context**

**Comment by ericangeles** [comment]
Duplicate https://github.com/infor-design/enterprise/issues/8449
