### ISSUE TITLE
Changing tab from popup menu won't trigger window location change

### ISSUE THREAD

**Issue by lskonieczka** [infor-design/enterprise#8536]
**Describe the bug**
When you have defined tab-id with slashes and configure changeTabOnHashChange to true, clicking on tab triggers url change as well. It doesn't work with popup menu (extra menu which appears when all tabs can't fit on a screen).

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs/test-forward-slashes.html#/home/attachments
2. Click on any tab, observe that url changes along with a tab.
3. Change size of web browser so popup menu appears.
4. Click any tab from popup menu and observe that tab changes but url remains the same

**Expected behavior**
The behavior should be consistent when clicking on tab and popup menu item. Both should trigger url change. Please make sure it is fixed with enterprise-ng as well. 

**Version**

- ids-enterprise: v4.93.0
- ids-enterprise-ng v17.5.9

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/163156055/31d0a18c-12ad-44a4-83ab-817c61da5d9b)

**Platform**
 - Infor Application/Team Name: WFM
 - Device: PC
 - OS Version: Win11
 - Browser Name: chrome
 - Browser Version: Version 122.0.6261.70 (Official Build) (64-bit)

**Additional context**
Original fix that made it work with tabs (but not popup menu):
https://github.com/infor-design/enterprise/pull/5135

**Comment by tjamesallen15** [comment]
Hello team, can we retest this. The url is changing on my end. Video below. @infor-design/qa 

https://github.com/infor-design/enterprise/assets/34049950/5b6f0941-d33f-4358-9672-cbe5d7ae7faf

**Comment by lskonieczka** [comment]
> * Change size of web browser so popup menu appears.
> * Click any tab from popup menu and observe that tab changes but url remains the same

please try as described in initial report:
...
3. Change size of web browser so popup menu appears.
4. **Click any tab from popup menu and observe that tab changes but url remains the same**

**Comment by jbrcna** [comment]
the url is changing on my end as well.
Win 11 Chrome
<img width="671" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/4a12754d-c07e-4243-997a-8108b5ee7b5f">


Safari
<img width="761" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/87d2889c-7f4a-4d28-a639-7353bc39bef8">

**Comment by lskonieczka** [comment]
> the url is changing on my end as well. Win 11 Chrome <img alt="image" width="671" src="https://private-user-images.githubusercontent.com/56722184/325583987-4a12754d-c07e-4243-997a-8108b5ee7b5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDgyNzYsIm5iZiI6MTcxNDA0Nzk3NiwicGF0aCI6Ii81NjcyMjE4NC8zMjU1ODM5ODctNGExMjc1NGQtYzA3ZS00MjQzLTk5N2EtODEwOGI1ZWU3YjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEyMjYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYzk0NWRkNTJiZWEyYzAxNmI5NzczMmQwNWMwZjdkZjJlZTkwZmQwYzZiYTE0MGQ2YzIwZDk1MmRjMDBlNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tBxYWMQxO5BtoG3fYKGE8tuQ-fSziIWpsDQMaDx8OjY">
> 
> Safari <img alt="image" width="761" src="https://private-user-images.githubusercontent.com/56722184/325583626-87d2889c-7f4a-4d28-a639-7353bc39bef8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwNDgyNzYsIm5iZiI6MTcxNDA0Nzk3NiwicGF0aCI6Ii81NjcyMjE4NC8zMjU1ODM2MjYtODdkMjg4OWMtN2Y0YS00ZDI4LWE2MzktNzM1M2JjMzliZWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDEyMjYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YmMwNzhiMmExZmQwODNjZTM3NGY4YWYyZjdjYWY3Yzk0ZmJkNGM4MTBkM2JhOGM2NWE1MjhiZTIzZTVlODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z4k58uMIt6mNMdwn7CoQqGB3dm1vatHdoIPOhajOH9E">

I cannot tell how you are doing it from a screenshot, but on attached recording it is clearly visible that popup menu was not used, but instead tab is clicked directly. I am not sure what more I can do to describe the issue, but will try in below screenshot:

![image](https://github.com/infor-design/enterprise/assets/163156055/7212cc25-f449-42ae-919b-823584e7be93)

**Comment by jbrcna** [comment]
thanks for clarifying @lskonieczka. I see it now. 
you have to change the tab in/using `tab-container-popupmenu ` @tjamesallen15 
<img width="845" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/26422273-c4d6-4673-a425-40613951c661">

**Comment by tmcconechy** [comment]
@tjamesallen15 can you look at everything
