### ISSUE TITLE
GenAiButton: Change API to start/stop / Also add to NG (soho-button)

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#8541]
**Describe the bug**

The recently added api to start the button animation will not work in practice because we dont know how long the animation will take.

See: https://github.com/infor-design/enterprise/blob/main/app/views/components/button/example-index.html#L205
It just uses a timeout. 

Also we need to add this to the NG project:

- the button type (icon is static and cant be changed
- and the new animation API

```js
<button soho-button="generative-ai" title="Love It">Generate</button>
```

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/button/example-index.html
2. Click on gen ai buttons

**Expected behavior**
In addition of passing a timeout to the button on https://github.com/infor-design/enterprise/blob/main/app/views/components/button/example-index.html#L205

Lets make two new methods. `startGenerativeActionAnimation/stopGenerativeActionAnimation` so it can be started and stoped on demand (or maybe `start/stopAnimation`.

**Additional context**
Sorry missed this on initial review.

**Comment by tmcconechy** [comment]
@ericangeles can you try this suggestion we found with Landmark

**Comment by vonnyw** [comment]
I picked up this change and still seeing the animation being terminated prematurely. Looking at the code, there is a default of 5000 delay which sets the timeout versus letting the stopAnimation call to handle it.
