### ISSUE TITLE
Datagrid: source is called twice when the datagrid has a pager

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#8551]
**Describe the bug**
`source` is called twice when the datagrid has a pager, which means the API is called twice.

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-filter-paging-server-side.html (or any other server side paging example)
2. Open the network tab in the devtools
3. Reload the page
4. Notice that `https://main-enterprise.demo.design.infor.com/api/compressors?pageNum=1&pageSize=10` is called twice

**Expected behavior**
The API should only be called once.

**Version**
- ids-enterprise: `4.93.0-dev`

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by karinpb** [comment]
This is kind of critical to have our service called duplicate times, so when can we expect to have this corrected? I would like to fix this for our 2024.08 release and I was not aware of this issue until I spotted the duplicate calls myself.
@tmcconechy

**Comment by tjamesallen15** [comment]
This was fixed on my previous ticket #8748

**Comment by tmcconechy** [comment]
Ok lets move to QA, thanks @tjamesallen15
