### ISSUE TITLE
ContextualActionPanel: unexpected padding added

### ISSUE THREAD

**Issue by whernebrink** [infor-design/enterprise#8553]
**Describe the bug**
We're currently on 17.1.3 on (4.90.1) and testing 17.5.9 I saw some added x-padding (`padding-x-16` class) to the modal (see screenshot below).
Caused by [this line](https://github.com/infor-design/enterprise/blob/e9456584ab4426ba1ee4e42923500f26b254ddb0/src/components/contextualactionpanel/contextualactionpanel.js#L258C1-L258C17)

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/
2. Click the Contextual Action Panel button to trigger one
3. Inspect DOM
4. See added `padding-x-16` class.

**Expected behavior**
Don't add any padding to the modal body, it should be the responsibility of the app teams.

**Version**
- ids-enterprise: v4.93.0

**Screenshots**
Experience Designer - looks cropped/broken.
![image](https://github.com/infor-design/enterprise/assets/73601152/e4195718-25b3-4f3e-bc22-511a2caf2fd3)
![image](https://github.com/infor-design/enterprise/assets/73601152/94c9d75b-5881-4a12-8d3c-e346e3320544)

Main enterprise:
![image](https://github.com/infor-design/enterprise/assets/73601152/c22746b8-bd73-4265-807f-5663f4caf4f5)

**Platform**
 - Infor Application/Team Name: m3
 - OS Version: Mac
 - Browser Name: Firefox/Chrome

**Comment by whernebrink** [comment]
Also that `has-back-button` was added (we don't even have any back button). This is how it is for us in production:
![image](https://github.com/infor-design/enterprise/assets/73601152/76137f4a-cfd2-4e05-8d4b-dc4f360662c9)

**Comment by tmcconechy** [comment]
@ericangeles can you guys take a look at this one as well?
