### ISSUE TITLE
ModuleNav: Should be overlayed by model when it is in open

### ISSUE THREAD

**Issue by manjaripalavancha** [infor-design/enterprise#8558]
**Describe the bug**
Soho-module-nav is not overlayed, when is there any model open.

**Steps to reproduce the behavior:**
1. Create a Soho-module-nav
2. Add a button to outside of the module-nav
3. Implement a model and open it when button click
4. Observe the module-nav is not overlayed back to the model

**Expected behavior**
Soho-module-nav should overlayed by model popup.

**Version**

- ids-enterprise: 17.5.4

**Screenshots**

![3a9600c9-6357-4cd5-b837-905fbfa107f0](https://github.com/infor-design/enterprise/assets/104565263/7de55be2-ca6e-44a9-9223-4b0ba59ef1e0)

**Additional Context:**
You can also refer the below communication channel link for the reference.
[https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1710323051491?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1710323051491&teamName=IDS%20Enterprise%20Development&channelName=Angular%20Components&createdTime=1710323051491](url)

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4114
