### ISSUE TITLE
Datagrid: xss issue with datagrid lookup

### ISSUE THREAD

**Issue by charantejpola** [infor-design/enterprise#8561]
**Describe the bug**
On selection of value in lookup inside a datagrid which has iframe values. The datagrid executes the iframe on selection.

**To Reproduce**

1. Create a DataGrid with a lookup column
2. The lookup values has one of the option as follows "<iframe src="javascript:alert(1)"></iframe>".
3. Select the lookup value option "<iframe src="javascript:alert(1)"></iframe>"
4. Press any key/enter or do a mouse click.
5. You can see that script got executed and see a alert on the screen.
**Expected behavior**
As in the normal lookup the script values/iframe values are sanitized and does not execute whereas that doesn't happen in the lookup inside a DataGrid.

**Version**
ids-enterprise-ng : 17.5.9

**Screenshots**

**Additional context**
Can refer to below stackblitz to get a better understanding.
https://stackblitz.com/edit/ids-quick-start-1759-artwhr?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

The same issue is fixed in ids-enterprise-ng:17.2.1(Here you can check the iframe doesnt get executed)
https://stackblitz.com/edit/ids-quick-start-1721?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,package.json

Please make sure all such other xss issues related to datagrid are fixed .

**Comment by tmcconechy** [comment]
@ericangeles we should look at this one please
