### ISSUE TITLE
design.infor website broken link

### ISSUE THREAD

**Issue by JoelWilke** [infor-design/enterprise#8562]
**Describe the bug**
A number of text links on the Popup component page lead to a 404.

**To Reproduce**

1. Go to ['(https://design.infor.com/components/components/popup/web-components/)'](https://design.infor.com/components/components/popup/web-components/)
2. Click on '[Popup Menu](https://design.infor.com/code/wc-beta/latest/ids-popup-menu)' and [Modal](https://design.infor.com/code/wc-beta/latest/ids-modal)
3. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![Screenshot 2024-03-20 at 4 55 39 PM](https://github.com/infor-design/enterprise/assets/164258730/7954d6ff-d7b3-4f42-b4f0-5f0613f21d03)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
I didn't check them all, but at least four text links were broken.

**Comment by inforandy** [comment]
Got this one in Jira here https://inforwiki.atlassian.net/browse/IDS-2067, closing out this ticket and will track the fix in Jira
