### ISSUE TITLE
Checkbox: the checkbox has an outer ring.

### ISSUE THREAD

**Issue by adamzhang1932** [infor-design/enterprise#8567]
**Describe the bug**
The checkbox has an outer ring.

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/checkboxes/example-checkbox-groups?theme=uplift&variant=light&layout=embedded
2. Unselect Option 2
3. Switch to any chrome tab and then switch back to current page.
4. See there is an outer ring on Option 2.

**Expected behavior**

**Version**

- ids-enterprise: v4.93.0

**Screenshots**
https://github.com/infor-design/enterprise/assets/151612185/6d391184-dfa0-4ee2-a197-9e7f3859e42f

**Platform**
 - Infor Application/Team Name: Infro SunSystems
 - Device: (if applicable) 
 - OS Version: 
 - Browser Name: chrome
 - Browser Version: 123.0.6312.59 (Official Build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
The ring is the focus state. Is this really an issue? Not sure what we can do about it?

**Comment by adamzhang1932** [comment]
Sorry, I am not sure if it is an issue before.
If it is a new feature for the Checkbox, then you can close this issue now.
Thanks a lot.
