### ISSUE TITLE
Application Menu: Mobile - Popup menu is behind the application menu - BETA 4.94

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise#8582]
**Describe the bug**
In mobile version, a pop up menu appears behind the application menu

**To Reproduce**

1. Go to https://4940-beta0-enterprise.demo.design.infor.com/components/applicationmenu/example-menubutton.html
2. Open the application menu
3. Click the **Add Item** button
4. The pop up menu is behind the application menu

**Expected behavior**
Pop up menu is in front of the application menu

**Version**

- ids-enterprise: beta 4.94

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/156752175/c90d5785-da6a-4ac0-9584-c7e749a435af)

![Animation](https://github.com/infor-design/enterprise/assets/156752175/deb7d147-0ee5-40af-b325-82b2535aff0b)

**Platform**
 - Device: Android 13 Galaxy S23
 - Browser Name: Chrome
 - Browser Version: 120.0.6099.144

**Comment by n-ace-ancog** [comment]
Duplicate of #7013. @tmcconechy - as per the other issue this is expected behavior. Just reconfirming, as it seems in the mobile there's no way to access menu behind.

**Comment by tmcconechy** [comment]
@ericangeles lets add this. dont think it needs to be fixed in 4.94 but seems important. Also the hover state is a wierd color should not get a background color there.

**Comment by tmcconechy** [comment]
@n-ace-ancog i misunderstood https://github.com/infor-design/enterprise/issues/7013.
This issue should be fixed but not the highest urgency
