### ISSUE TITLE
Sinkpage: Timeline - Misaligned connecting line - BETA 4.94

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8583]
**Describe the bug**
Misaligned connecting line.

**To Reproduce**

1. Go to https://4940-beta0-enterprise.demo.design.infor.com/
2. Scroll down to `Time Line` component

**Expected behavior**
Connecting line should be aligned accordingly.

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/2e1a8b79-67c4-49d6-ada8-4b490922b978)

**Platform**
 Tested in Mac Chrome, Safari, and Mac Edge.

**Additional context**

**Comment by tmcconechy** [comment]
Duplicate of https://github.com/infor-design/enterprise/issues/8586
