### ISSUE TITLE
Sinkpage: timeline not properly algined - BETA 4.94 

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8586]
**Describe the bug**

**To Reproduce**

1. Go to https://4940-beta0-enterprise.demo.design.infor.com/components/timeline/example-index.html
2.  See error

**Expected behavior**
should be properly aligned. 
<img width="656" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/5f9db5c0-d1e0-4ca4-8ca5-0a8dfe011e60">

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="611" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/cd406d46-90f5-4381-9894-c2274038b607">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
@ericangeles can we fix this for the 4.94 (QA issue). Can push to main and then i'll merge it when it when complete.

**Comment by ericangeles** [comment]
Agree.
