### ISSUE TITLE
Tabs Vertical: Mobile - Clicking the dropdown produces error - BETA 4.94

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise#8596]
**Describe the bug**
Upon clicking the dropdown in the `tabs vertical` in a mobile view an error is returned and nothing happens.

**To Reproduce**

1. Go to https://4940-beta0-enterprise.demo.design.infor.com/components/tabs-vertical/example-index.html
2. Open developer's console
3. Toggle device toolbar
4. Click the dropdown
5. See error

**Expected behavior**
No error is displayed and other tabs shown

**Version**
- ids-enterprise: v4.94 Beta

**Screenshots**
![Animation](https://github.com/infor-design/enterprise/assets/156752175/e1080979-7a5b-4dbc-9f13-d6c0902cb0a8)

![image](https://github.com/infor-design/enterprise/assets/156752175/5717768b-d92c-46cb-ad2f-b829a729dd2f)

**Comment by tmcconechy** [comment]
@ericangeles i think we should fix this one too for 4.84. I will pick one of these up and assign myself.
