### ISSUE TITLE
"$" is not highlighting in datagrid search

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#860]
**Describe the bug**

**To Reproduce**
1. Run app
2. Go to http://localhost:4000/components/datagrid/example-keyword-search.html
3. Search for $
4. Notice $ is not highlighted

**Expected behavior**
$ should be highlighted when searching for it.

**Platform**
All

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/example-keyword-search.html
http://master-enterprise.demo.design.infor.com/components/datagrid/example-keyword-search.html
Passed QA testing across all browsers
