### ISSUE TITLE
HomePages: Add Background image functionality

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#8600]
**Describe the bug**

1. Add the ability to show a background image on home pages. This is optional via a setting.
1. Also when resizing to mobile the chart size (width) isnt correct...This might be a regression.

**Task**
Add this to both EP and WC.

**Screenshots**

<img width="579" alt="Screenshot 2024-04-05 at 7 30 29 AM" src="https://github.com/infor-design/enterprise/assets/814283/add484fc-f427-42ac-b6ab-54ff6f057e8b">

**Additional context**
https://inforwiki.atlassian.net/browse/IDS-2068
https://inforwiki.atlassian.net/browse/IDS-2143

**Comment by tmcconechy** [comment]
@ericangeles FYI will need to add this enhancement. The design is being refined but needs to be added this month so flagging for now.

**Comment by tmcconechy** [comment]
@ericangeles this is ready please see designs and decide who should take it?

**Comment by tmcconechy** [comment]
@yohannahbautista can you review the design https://inforwiki.atlassian.net/browse/IDS-2068 (password there) in the Jira
The file is https://www.figma.com/file/3NBGQJthD3eY6l9cjI9UQn/Workspace%3A-October-24-Release?type=design&node-id=0-1&mode=design&t=CxvOOKom0Gxxc7MG-0

1. The background is only on the top section
2. There are some other backgrounds that look like they would have better contrast. Maybe for the example we could show toggling between the four there or add four examples. But we should use these specific examples. We dont need the rest of the content in this example (for now im not sure) but definitely use those backgrounds and designs.

**Comment by inforandy** [comment]
https://inforonline-my.sharepoint.com/:v:/g/personal/maksim_petriv_infor_com/EYdkVBxzAQlLhAGn4GDrdG0BJEgoLJPDlmGik71RhSmeCQ?e=ocwFaX video of design feedback from maks here
