### ISSUE TITLE
Sinkpage: listview vertical ellipsis not in proper position - 4.94-beta0

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8602]
**Describe the bug**

**To Reproduce**

1. Go to https://4940-beta0-enterprise.demo.design.infor.com
2. Scroll into listview
3. Hover over 

**Expected behavior**
<img width="519" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/ac041c82-43ed-497b-bc8b-265247917fe2">

**Version**

- ids-enterprise: v4.94.0-beta0

**Screenshots**
<img width="603" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/440cec1a-674f-4b04-bfef-7d448e538727">

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
@ericangeles i think we should take a look at this one. Will break homepages, not sure what happened?
