### ISSUE TITLE
Homepage: Crashes after 4.94 update

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#8611]
**Describe the bug**
After updating to 4.94, the Homepage (Angular `soho-homepage`) crashes with an error:

> Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Fs.resize (global:scripts.js:216:1158595)
    at HTMLBodyElement.<anonymous> (global:scripts.js:216:1159609)
    at HTMLBodyElement.dispatch (global:scripts.js:2:40035)
    at v2.handle (global:scripts.js:2:38006)
    at Object.trigger (global:scripts.js:2:70124)
    at ce.fn.init.triggerHandler (global:scripts.js:2:70811)
    at global:scripts.js:216:16756
    at global:scripts.js:216:10715
    at timer (zone.js:2402:41)
    at _ZoneDelegate.invokeTask (zone.js:403:31)

After this, the Homepage no longer re-calculates the position/size of widgets when resized.

**To Reproduce**

Cannot reproduce exact issue in samples. Could be that the Homepage is initially empty? I.e no widgets.

A similar issue can be reproduced by:

1. Go to https://4940-beta0-enterprise.demo.design.infor.com/components/homepage/test-add-remove-widget.html
2. Click "Remove Widget" until the last one is removed
3. See error in console

The difference might be that in our app, the Homepage is _initially_ empty, which causes more issues.

**Version**

- ids-enterprise: 4.94.0

**Screenshots**
<img width="1728" alt="image" src="https://github.com/infor-design/enterprise/assets/4991954/7e8ae6b6-605f-419a-8f4d-a76ff6dd2300">

**Platform**
 - Infor Application/Team Name: Portal / Homepages

**Additional context**
This line crashes (possibly because there are no Widgets when the Homepage is created?):
https://github.com/infor-design/enterprise/blob/4edb56906c0a88a62455212096b0de9636c02afd/src/components/homepage/homepage.js#L744

Possibly caused by this commit: https://github.com/infor-design/enterprise/commit/8dfa48a5e974bd257666922024b3491eee886c73

**Comment by tmcconechy** [comment]
@anhallbe does this need patching? See: https://github.com/infor-design/enterprise/pull/8612

**Comment by anhallbe** [comment]
@tmcconechy  Yes, a 4.94.x patch would be great since we're hoping to go with 4.94 which fixes #8524

**Comment by tmcconechy** [comment]
@anhallbe ok its ids-enterprise@4.94.2 and ids-enterprise-ng@17.6.2
