### ISSUE TITLE
Datagrid: Visibility Issue with columns after update

### ISSUE THREAD

**Issue by Vishal-2021** [infor-design/enterprise#8617]
**Describe the bug**
After updating to IDS version 4.94.2, we noticed an issue with the soho-datagrid component in conjunction with the soho-splitter. Specifically, only the first column of the soho-datagrid is visible, while the rest are hidden. This problem does not occur when using IDS version 4.93.1. Interestingly, if the soho-datagrid is not within a soho-splitter, it displays correctly.
Attached are screenshots showing the difference between the soho-datagrid with three columns (IDS 4.93.1) and the one with only one column (IDS 4.94.2).
We need urgent attention to resolve this issue.

**To Reproduce**

1. use splitter 
2. use soho data grid inside the soho splitter mention in step 1

**Expected behavior**
All the grid column should visible (as they are visible in version 4.93.0).

**Version**

- ids-enterprise:  v4.94.1

**Screenshots**

<img width="483" alt="image" src="https://github.com/infor-design/enterprise/assets/85800874/fdae14ee-4439-4dfd-af30-5d7615c48526">

![image](https://github.com/infor-design/enterprise/assets/85800874/feefd483-34dc-409e-8af2-402392e3c2ff)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@ericangeles any ideas what may have caused this? I dont see any splitter or datagrid changes. I think we should look at this this sprint if possible

**Comment by ericangeles** [comment]
@tmcconechy no idea as well. I don't think we touched anything in splitter with datagrid. @Vishal-2021, can you put it in a stackblitz, perhaps? Or environment that we can check the issue.

**Comment by tmcconechy** [comment]
@ericangeles the stackblitz is:

https://anhallbe.github.io/ids-repro/datagrid-splitter
Code:
https://github.com/anhallbe/ids-repro/tree/master/src/app/datagrid-splitter

You can see the grid width is very very larg

**Comment by Vishal-2021** [comment]
> @tmcconechy no idea as well. I don't think we touched anything in splitter with datagrid. @Vishal-2021, can you put it in a stackblitz, perhaps? Or environment that we can check the issue.

These are two code and repository links - 

https://anhallbe.github.io/ids-repro/datagrid-splitter
 
Code: https://github.com/anhallbe/ids-repro/tree/master/src/app/datagrid-splitter

**Comment by tmcconechy** [comment]
@ericangeles @yohannahbautista 

1. I created a branch with a "fix" and example  https://github.com/infor-design/enterprise/pull/new/fix-datagrid-regression and some other minor formatting was fixed BUT
2. https://github.com/infor-design/enterprise/pull/8560 is not fixed notice https://latest-enterprise.demo.design.infor.com/components/datagrid/test-frozen-only.html is not working
3. This change https://github.com/infor-design/enterprise/pull/8560/files#diff-cc804a8d1fdaf0bfaf6aa91dbfdf7be69520510ac7133f1dc0b3d916460eae58R1127 is what caused it

Can we look at another fix for https://latest-enterprise.demo.design.infor.com/components/datagrid/test-frozen-only.html 

http://localhost:4000/components/datagrid/test-frozen-only.html -> should show headers
http://localhost:4000/components/datagrid/example-splitter.html -> should show two cols
