### ISSUE TITLE
Autocomplete: Arrow navigation malfunctions after typing, waiting, and typing again

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#8618]
**Describe the bug**
When using the Autocomplete control, if you navigate with the arrow down/up after typing multiple times, the control gets into a weird state and doesn't work properly.

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/autocomplete/example-index.html
2. In the input field, type "ne" and wait for the results to appear.
3. Hit the down arrow to nav down the list (notice the highlighted record is BLUE and FOCUS remains in the input field, which is correct behavior)
4. Start over (clear the field or refresh the page)
5. In the input field, type "ne" and WAIT for the results to appear (don't nav down).
6. Now type another character "w" (for "new") and wait for the results to update.
7. Hit the down arrow to nav down the list (notice the highlighted record is GRAY and the input field LOSES FOCUS, which is wrong behavior)

**Expected behavior**
The highlighted record should be BLUE and FOCUS should remain in the input field, no matter if you type in once or multiple times.

**Version**
ids-enterprise: v4.94.2

**Screenshots**
Correct
![image](https://github.com/infor-design/enterprise/assets/14128010/551facc8-a6d7-4798-8c1d-53b63ec67530)

Incorrect
![image](https://github.com/infor-design/enterprise/assets/14128010/df6167d8-af09-4e81-bf42-2e2f523cf891)

**Platform**
 - Infor Application/Team Name: CSD
 - Device: Dell laptop
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 123.0.6312.123 (Official Build) (64-bit)

Thank you!

**Comment by aaronpikkarainen** [comment]
Hello, I tested the coding changes, and I found this issue is partially fixed. The highlighted row is now blue, which is good.

However, the focus cursor is not remaining in the input field in this scenario. The expected behavior is that the focus cursor stays in the input field (as it does when typing just once) so that the user can keep refining their search if needed.

If you test the reproduce steps exactly as described, you will see this issue. I tested here: https://main-enterprise.demo.design.infor.com/components/autocomplete/example-index.html

Can you please review again? Thank you.

**Comment by tmcconechy** [comment]
@tjamesallen15 can you take a look?

**Comment by aaronpikkarainen** [comment]
Thank you everyone. I brought in the changes locally and tested it. The autocomplete is working well now.
