### ISSUE TITLE
Remove customValidation setting to better support custom validation in time and datepicker

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#862]
**Describe the bug**
The timepicker and date picker in angular will only work with the default date validation. You cannot add custom or required validation.

**To Reproduce**
1. Make a date and time picker example with data-validation ="date required"
2. Tab out
3. Nothing is shown for errors

**Proposed Fix**
- remove customValidation setting (in both timepicker, datepicker)
- remove all logic related to customValidation
- add a path that checks if the input has data-validation attributes. If it does dont do anything and let the validation plugin run. If it doesnt exist add default date validation.

**Additional context**
https://github.com/infor-design/enterprise-ng/issues/198

**Comment by tmcconechy** [comment]
Steps necessary to review this issue

http://localhost:4000/components/timepicker/example-validation.html

first field - type a bad time like 1: and hit enter or tab
second field - type anything (everything is gonna be wrong here)
last field - tab out without a value, then type a bad date like 1: and hit enter or tab
http://localhost:4000/components/datepicker/example-validation.html

first field - type a bad date like 1/2 and hit enter or tab
second field - type an unavailable date like 10/6/2018 and hit enter or tab
third field - type anything (everything is gonna be wrong here)
last field - tab out without a value, then type a bad date like 1/2 and hit enter or tab

**Comment by brianjuan** [comment]
http://localhost:4000/components/datepicker/example-validation.html
http://localhost:4000/components/timepicker/example-validation.html
Passed QA testing on all browsers, validations are working as expected.
