### ISSUE TITLE
Popupmenu: Submenu and multiselect items doesn't work

### ISSUE THREAD

**Issue by vjramos** [infor-design/enterprise#8623]
**Describe the bug**
Soho popupmenu with submenu and multiselectable items doesn't retain isChecked property when another item from the submenu is selected. It basically behaves like a single select menu but with the appearance of a multiselect menu. This can be replicated using ids-enterprise-ng 17.2.x on a locally built environment. See attached video clip on how to replicate.

**To Reproduce**
- Using enterprise-ng v17.2.x cloned from here - https://github.com/infor-design/enterprise-ng/tree/17.2.x
1. On home page, search 'Popup Menu Options'
2. On 'Label' w/ 'Right Click Me', right click on element to open popupmenu, select 'Multiselectable' item and choose any item check it
3. Go back to same menu and click any other item

**Expected behavior**
Selected items on submenu w/ multiselect items should have retained its check

**Actual behavior**
Only last selected item retain its check, other items that was previously checked has lot its check

See attached video for actual replication

**Version**
- ids-enterprise-ng: 17.2.x

**Video**
https://github.com/infor-design/enterprise/assets/34755536/559032a3-4d4e-46d0-a772-87c67804eff0

**Additional context**
Issue occurs up to the latest version of ids-enterprise-ng

**Comment by vjramos** [comment]
Hi @tmcconechy, do we have an estimate on when can this be fixed? We need an estimate because we're planning ahead for a release. if this issue can't be fixed in time, we will have to find a workaround for it. Please advise. Thanks!

**Comment by tmcconechy** [comment]
Might be able to get this in a sprint May timeframe. To workaround it i guess you could exclude the extra information from the menus or maybe use groups instead of submenus in the main menu.

**Comment by vjramos** [comment]
I think that timeline fits perfectly on our schedule. Yeah, we have the same ideas for a workaround. Thanks a lot, Tim!
