### ISSUE TITLE
WeekView: Enhancement request on overnight shift for week view component 

### ISSUE THREAD

**Issue by AlineAbraham** [infor-design/enterprise#8630]
Overnight shifts display in My week widget.

**Jira ticket no**.- [[T2V-18138] Observation: Overnight shift is not displayed as a pill over the week widget, Start time and end time are not displayed - Infor JIRA](https://jira.infor.com/browse/T2V-18138)
**Current scenario**: In the latest IDS changes, overnight shift records are divided into two parts and labeled as 'overnight.' However, in the WFM schedule calendar, overnight shifts are displayed with a '+1.' Please refer to the My Week widget and WFM Calendar screenshots. 

![Screenshot 2024-04-19 180511](https://github.com/infor-design/enterprise/assets/167535167/7db84dee-386c-4f89-934a-7e1c761bdc67)

 **Requirement:** Can we have a setting to define that overnight shift only be display on the date it happened
![Screenshot 2024-04-19 180548](https://github.com/infor-design/enterprise/assets/167535167/5f14235a-d632-43c2-bd75-470d697f141a)

**Comment by tmcconechy** [comment]
@AlineAbraham I think it may help if you add some example times and how you think they should

7AM - 7PM -> it goes to one day
11PM - 4AM -> Is overnight shift (should it go 

Is basically this issue just adding the overnight shift, to the calendar as well since its only on the week view? Any further explanation would be great as I'm not 100% sure how to act on this.

**Comment by AlineAbraham** [comment]
Hi @tmcconechy,
I will setup a call with Alice, so we can have detailed understand of the issue.

**Comment by AlineAbraham** [comment]
Hi @tmcconechy, I have scheduled a call with Alice tomorrow. So that we can thoroughly understand the issue

**Comment by tmcconechy** [comment]
Tasks for this issue while working with @AlineAbraham 

See https://main-enterprise.demo.design.infor.com/components/week-view/example-stacked.html that the overnight shift is on both days

1) Add a setting: `showOvernightBothDays` if this is false show it only on the firstDay when it starts
2) Make the text `Overnight` label a setting (and blank would be hidden). Let the setting pass HTML (sanitized). Possibly `customEventHeader`

**Comment by infor-mahesh** [comment]
Hi @tmcconechy ,

**If there is an overnight shift and showOvernightBothDays is false, then the shift will be assigned to firstDay + 1?**

![image](https://github.com/user-attachments/assets/11e0e892-d908-436e-8027-184a86ede28c)
we need as per application design? is that what it got implemented? 

**which release it is available?**

**can you please provide the sample.**

thanks

**Comment by tmcconechy** [comment]
@infor-mahesh this is in 4.97.0 or later 

See Example: https://main-enterprise.demo.design.infor.com/components/week-view/example-stacked.html
