### ISSUE TITLE
Datagrid: Misaligned frozen columns cells when virtualized

### ISSUE THREAD

**Issue by meechtsm-infor** [infor-design/enterprise#8638]
**Describe the bug**
When the datagrid is set to use virtualized and has frozen left columns; after scrolling, the grid rows in the frozen columns do not align with the other columns cells.

**To Reproduce**
The issue can be reproduced using the existing test-virtualization.html example and adding frozenColumns to the datagrid settings. 

1. Update the test-virtualization.html file to include the frozenColumns setting. E,,g frozenColumns: {left:['column0', 'column1']},
2. Navigate to the test-virtualization.html test.
3. Scroll down until the virtualized setting causes redraw (about 10 rows)
4. See that the frozen columns cells are no longer aligned with the remaining row cells

**Expected behavior**
When scrolling the grid all row cells should remain aligned.

**Version**
- ids-enterprise@4.95.0-dev.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/53617793/2acaec8b-e6c5-4bf6-b8be-f630591d92ca)

**Platform**
- Platform: Win32
- Mobile: false
- Locale: en-US
- Language: en
- Browser: Chrome (124)
- Browser language: en-US
- Cookies enabled: true
- IDS version: 4.95.0-dev.0

**Comment by tmcconechy** [comment]
This combination is not supported. We do have better support for virtualization in the web components https://github.com/infor-design/enterprise-wc and i think this might work there in the new version.

But for this version we are not working on virtualization any further than it is working right now as its too difficult. Also it has a lot of issues and is considered experimental.

But for https://github.com/infor-design/enterprise-wc we are supporting everything.

**Comment by tmcconechy** [comment]
@meechtsm-infor what team are you on BTW? 

As far as virtual scrolling goes we recommend using https://github.com/infor-design/enterprise-wc as it works. So if you need it please try that component. We wont be able to fix this version without the rewrite we did.

**Comment by meechtsm-infor** [comment]
> @meechtsm-infor what team are you on BTW?
> 
> As far as virtual scrolling goes we recommend using https://github.com/infor-design/enterprise-wc as it works. So if you need it please try that component. We wont be able to fix this version without the rewrite we did.

Thanks, we will look in to using the datagrid web component.

I'm in the SCP UI team. We have a very customized datagrid that can contain many rows and columns with custom formatters. When there are a significant number of columns, with a number of left frozen columns there seems to be an issue with grid responsiveness. To alleviate the issue the virtualized settings was enabled, which is when misalignment was noticed.
