### ISSUE TITLE
Personalize: tabs focus looks off in responsive view

### ISSUE THREAD

**Issue by janahintal** [infor-design/enterprise#8644]
**Describe the bug**

**To Reproduce**

Personalize: tabs focus looks off in responsive view

1. Go to https://main-enterprise.demo.design.infor.com/components/personalize/example-form-landmark.html?theme=new&mode=light&colors=default
2. Switch to Responsive View
3. Navigate the Tabs

**Expected behavior**
Selected Tabs should render properly 

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="1743" alt="Screenshot 2024-04-24 at 4 01 30 PM" src="https://github.com/infor-design/enterprise/assets/45757016/eeac0c93-b68d-4f52-ab83-cbc8fe29b298">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by ericangeles** [comment]
@infor-design/qa, please re-test this as I don't see the issue.

**Comment by jbrcna** [comment]
the test passed on my end.
<img width="772" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/c234b4de-0597-4a08-9363-fe5c0c72c67b">
<img width="773" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/911b8270-c796-4f66-b4df-52ee6bdc7f7c">
<img width="865" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/00d370d4-bdb6-4d83-bec6-a4ecfaeb158a">

**Comment by tmcconechy** [comment]
@ericangeles the focus state used to float like this one https://4910-enterprise.demo.design.infor.com/components/personalize/example-form-landmark.html?theme=new&mode=light&colors=default

Does it look better?

**Comment by ericangeles** [comment]
@tmcconechy, it looks like there's a cut-off at the bottom. I'll adjust it.
