### ISSUE TITLE
Datagrid: Autosizing not working correctly with tree grid

### ISSUE THREAD

**Issue by kwolentarski** [infor-design/enterprise#8646]
**Describe the bug**
When using column auto-sizing in tree grid there are two issues occurring:
 1. Children content is not taken into consideration when column width is calculated
 2. Audible description of expand/collapse button is used as part of text when calculating the width, making the column wider than it needs to be.

**To Reproduce**

1. Go to 'https://stackblitz.com/edit/ids-enterprise-4940-qethhi?file=index.js'
2. Notice in first datagrid that the second row's (first child of first row) content is clipped.
3. Notice in second datagrid that the first column is a lot wider than it needs to be.

**Expected behavior**
1. Children of tree grid should be taken into consideration when calculating column width.
2. Hidden text of expand/collapse button should not be taken into account when calculating column width.

**Version**

- ids-enterprise: v4.94

**Platform**
 - Infor Application/Team Name: Infor WFM

**Comment by tmcconechy** [comment]
@kwolentarski valid bug I guess but the auto column sizing is not very performant so maybe consider static widths? Additional checks might make it a bit slower

**Comment by tmcconechy** [comment]
@yohannahbautista thinking about this one... maybe

1) use existing calculateTextWidth which is used already for auto column width
2) For tree columns navigate all the children and find the max adding all the textWidths together
3) add some padding for the indenting ect
