### ISSUE TITLE
Norwegian, Bokmål (Norway) nb-NO locale is not accessible to applications

### ISSUE THREAD

**Issue by denmacalinao** [infor-design/enterprise#8647]
**Describe the bug**
We identified Dutch translations in the following Norwegian locale files:
no-NO: https://github.com/infor-design/enterprise/blob/main/src/components/locale/cultures/no-NO.js
nn-NO: https://github.com/infor-design/enterprise/blob/main/src/components/locale/cultures/nn-NO.js

**To Reproduce**

1. Inspect the content of the following files:
nb-NO: https://github.com/infor-design/enterprise/blob/main/src/components/locale/cultures/nb-NO.js
nn-NO: https://github.com/infor-design/enterprise/blob/main/src/components/locale/cultures/nn-NO.js
no-NO: https://github.com/infor-design/enterprise/blob/main/src/components/locale/cultures/no-NO.js
nl-NL: https://github.com/infor-design/enterprise/blob/main/src/components/locale/cultures/nl-NL.js

2.  Verify actual contents 
nb-NO - contains Norwegian Bokmål  translations - Correct
nn-NO - contains Dutch translations - Wrong!
no-NO - contains Dutch translations - Wrong!
nl-NL - contains Dutch translations - Correct

**Expected behavior**
nb-NO - contains Norwegian, Bokmål translations
nn-NO - contains Norwegian, Nynorsk translations
no-NO - contains Norwegian translations
nl-NL - contains Dutch translations

**Version**

- ids-enterprise: v4.93

**Screenshots**
Dutch translations shows in Date picker instead of Norwegian, Bokmål (Norway) nb-NO locale
![Wrong Norwegian Translation in Date field](https://github.com/infor-design/enterprise/assets/167986021/a5a8506e-b3b2-47ad-b1d7-642aec021ecb)

**Platform**
 - Infor Application/Team Name: Infor M3 H5

**Additional context**
MUST: Kindly read through the discussion in Teams
[IDS Enterprise Development Teams](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1713843840682?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1713843840682&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1713843840682)

**Comment by tmcconechy** [comment]
@denmacalinao I misunderstood you.

I fixed the problem with Dutch being in there by accident. I noticed it too when i updated the translations here https://github.com/infor-design/enterprise/pull/8614 a few weeks ago.
 
This fix will be in 4.95.0

As a workaround if needed you could manually update them since they may be external or:
https://github.com/infor-design/enterprise/tree/main/src/components/locale/cultures
 
We could also include it in a patch if really badly needed.

**Comment by tmcconechy** [comment]
Update: Testing again it was still wrong. Fixed on this PR https://github.com/infor-design/enterprise/pull/8648
If a patch is needed just let me know which version. See PR for testing details

**Comment by denmacalinao** [comment]
I've discussed this with our team and we would like to request a patch for ids-enterprise v.4.90.1
 @tmcconechy is it possible for a patch for version 4.90.1?

**Comment by tmcconechy** [comment]
@denmacalinao i patched this into https://www.npmjs.com/package/ids-enterprise/v/4.90.4
If you need an Angular wrapper version of this just let me know what version it was I should patch there as well.

**Comment by denmacalinao** [comment]
@tmcconechy Yes we need a patch for the angular wrapper version, ids-enterprise-ng. We are currently using the 17.1.4 version.

**Comment by tmcconechy** [comment]
@denmacalinao you got it. Its `ids-enterprise-ng@17.1.5`
