### ISSUE TITLE
Datagrid: Not spanning the entire width in modals

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#8658]
**Describe the bug**
Data grids don't span the entire width in modals

**To Reproduce**
1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-tooltips.html (or any other example where there's a data grid inside a modal)
2. Open the modal
3. Open the devtools and edit the modal title (make it long enough so that the modal increases in width), or set a `width` on one of the elements in the modal.
4. Notice that the data grid doesn't span the entire modal width. 

**Expected behavior**
The data grid should span the entire modal width.

**Version**
ids-enterprise: `4.95.0-dev.0`

**Screenshots**
![grid_width_modal](https://github.com/infor-design/enterprise/assets/63045013/55ec9f6e-b1ac-4743-a518-b6300619d334)

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by tmcconechy** [comment]
Some ideas you could try:

1) remove any custom widths so its using auto layout: https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/test-modal-datagrid-tooltips.html#L31
2) use percent column widths
3) Use fixed widths and stretchColumn on one column.

**Comment by ericangeles** [comment]
@tmcconechy, looks like it's now fixed.

**Comment by ericangeles** [comment]
Could you, @n-ace-ancog, re-test this?

**Comment by jbrcna** [comment]
this is now working as expected. 
verified in https://main-enterprise.demo.design.infor.com/components/datagrid/test-modal-datagrid-tooltips.html
<img width="1219" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/7f7161e3-bd6c-44dd-bd4d-a949562093ae">
