### ISSUE TITLE
BusyIndicator: Add new indicator

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#8662]
**Describe the bug**
In a mixed use (old and new components). The loading indicators are different.

**Expected behavior**
https://main.wc.design.infor.com/ids-loading-indicator/example.html be changed in this repo from the line busy indicator to circular one.

- Make an option `type="bar"` to show the old one (circular / bar / square)
- By default should show the bar indicator
- Add an option to show the square one 
- Add option to the examples to switch between the two types (small button on top right or similar)
- Linear option would be in limited examples

**Additional context**
Came up with M3

**Comment by MadhaviDasika** [comment]
For LN Portal (Angular application) as well have a requirement to show the latest busy indicator (circular). So, please try to make this available at the earliest.

**Comment by yohannahbautista** [comment]
@tmcconechy 
Hello, I'm a bit unsure on my interpretation of the ticket so to elaborate:
- In WC, add the busy indicator version from IDS https://main-enterprise.demo.design.infor.com/components/busyindicator/example-index.html
- In IDS, add circle indicator seen in WC https://main.wc.design.infor.com/ids-loading-indicator/example.html
- In NG, add circle indicator

**Comment by tmcconechy** [comment]
@inforandy check me if it is not correct but 

- WC - just have the circle one leave as is
- NG - add the circle one as well keep the current indicator as an option but circle can be the new default?
