### ISSUE TITLE
(IDS) Translation issues for Role-based Workspace KPI tiles

### ISSUE THREAD

**Issue by juanfrancoyu** [infor-design/enterprise#8666]
On Your Radar KPI tiles (screenshots below) encounter layout issues when they’re translated.

Two things happen:

- When KPI labels reach a certain number of characters, the text overflows, messing the styling/formatting
- If a translated language overflows to three lines, a scrollbar appears

There were also suggestions on Truncating three-line texts and revealing the truncated text via tooltip on mouse hover but it wasn’t received well.

The devs from Hyderabad brought up translation rules that were becoming complicated, as requested by the localization teams, which is making the process hard to track.

The rules went something like:

If language is English, then the number goes first before the status

For Spanish, words come first then followed by numbers (see En su radar)

<img width="960" alt="ES workspace (translated)" src="https://github.com/infor-design/enterprise/assets/168730518/7eab2c68-8cb8-4495-9d83-664299747ada">

<img width="960" alt="Local host translation issues" src="https://github.com/infor-design/enterprise/assets/168730518/bce92e53-d9bf-4692-835b-c7645f5a48c3">

Would relish to hear your thoughts on this one.

**Comment by tmcconechy** [comment]
@juanfrancoyu we already raised this one based on your feedback here: https://github.com/infor-design/enterprise/issues/8636#issuecomment-2090338955

So will close this one. I think making it move to the other side is something we could/should do if that makes sense. But not sure how to handle the longer text yet. If you notice on #8636 there is a design request on it for this and we'll settle on an approach
