### ISSUE TITLE
Header: Primary Buttons on a toolbar in a header not styling correctly

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#8669]
**Describe the bug**
The "btn-primary" is not styling a button in a toolbar in a header. For just a btn-primary in a flex toolbar, the buttons appear as filled in blue buttons:
![image](https://github.com/infor-design/enterprise/assets/22107636/16946a11-6894-4de6-b2b8-2e68b8a46c42)

However, if this toolbar is inside of a header, then the styling is not added to the buttons:
![image](https://github.com/infor-design/enterprise/assets/22107636/22f81735-cf38-4826-865e-312963f7c399)

It would be nice if there was primary stylings on the buttons in the header toolbar, and that they would work nicely when the color is personalized on the header as well.

Also, the icon only button icon seems to be a gray icon instead of a white icon.

1. Copy [test-toolbar-primary-buttons.zip](https://github.com/infor-design/enterprise/files/15189500/test-toolbar-primary-buttons.zip) into the codebase /app/views/components/header
2. Navigate to /components/header/test-toolbar-primary-buttons.html in the web browser
3. See error

![image](https://github.com/infor-design/enterprise/assets/22107636/752697ea-f76d-41f4-8cb7-5239d6a8b775)

**Use Case**

- up to developer but for actions to stand out such as approve or reject

**Questions**
 
- what do with colors (could make it white instead or opposite contrast color
- fix all primary button types

**Expected behavior**
There is correct primary button styling on the buttons with btn-primary.

**Version**

- ids-enterprise: 4.95.0

**Platform**
 - Infor Application/Team Name: Landmark UI
 - All devices and platforms

**Comment by tmcconechy** [comment]
I dont believe we ever supported primary buttons in the toolbar. Especially multiple does not make sense. But will review with design.

**Comment by Sovia** [comment]
The multiple was for testing, our use case will only have one per toolbar.

**Comment by tmcconechy** [comment]
@tjamesallen15 or @yohannahbautista For this one:

a) make primary possible on a flex toolbar
b) remove any button specific code for button styles out of the toolbar and let buttons all just use from buttoon. css

**Comment by tmcconechy** [comment]
@Sovia initially we will add support for this but not when there is a personalization color set (this requires more design / tokens work for future)
