### ISSUE TITLE
Enterprise "uniqueId" conflicts with jQueryUI "uniqueId" function

### ISSUE THREAD

**Issue by PilotBob** [infor-design/enterprise#868]
**Describe the bug**
When attempting to add some Enterprise controls to our legacy pages during our Mingle/SOHO adoption we are running into a conflict trying to use the jQueryUI dialog with Enterprise loaded. 

**To Reproduce**
1. Add jQueryUI to a page prior to soho.js
1. Call
    ```$("#element").dialog()```
1. See error:
    ```
    personalize.hooks.js:19 Uncaught TypeError: Cannot convert undefined or null to object
        at Function.from (<anonymous>)
        at Object.g.uniqueId (personalize.hooks.js:19)
        at jQuery.fn.init.$.fn.uniqueId (personalize.hooks.js:19)
    ```
1. Modify code to load jQueryUI after Enterprise, the jQueryUI dialog works however Enterprise controls like datepicker and dropdown don't get initialized when calling `datepicker()` or `dropdown()`

**Expected behavior**
No conflict. Perhaps Enterprise can namespace `uniqueId` to `soho.uniqueId` or not globally expose `uniqueId` to jQuery.

**Additional context**
It appears that both jQueryUI and Enterprise add a `uniqueId` function globally to jQuery `$.fn.uniqueId` and of course which ever library is loaded last wins. 

If this remains as is it will be a huge impact on our project timeline, due to needing to fully replace all usage of jQueryUI, which wasn't in the scope of this initial Mingle/SOHO adoption release.

**Comment by tmcconechy** [comment]
Fix appears to be to remove our `$.fn.uniqueId` in favor of Soho.utils.uniqueId and any references that call it as a jquery plugin.
I dont think it is a breaking change as i doubt anyone knows this exists. If someone happens to they can change to Soho.utils.uniqueId

**Comment by EdwardCoyle** [comment]
@tmcconechy agree with your assessment.  I don't think this will affect any consumers of IDS.  Our `uniqueId` stuff is pretty well setup for internal use only

**Comment by CindyMercadoReyes** [comment]
There is no way to QA test this GitHub ticket. However, I spoke to Tim and the user gave us the Ok to move this ticket to the Done folder. Thanks, Cindy
