### ISSUE TITLE
Button: Click Indicator is missing - BETA 4.95

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise#8686]
**Describe the bug**
When clicking buttons, no visual indicator that it was clicked

**To Reproduce**

1. Go to https://4950-beta0-enterprise.demo.design.infor.com/components/button/example-index.html
2. Click on any button
3. No visual indicator is present

**Expected behavior**
Visual indicator is present

**Version**

- ids-enterprise: 4.95.0-beta.0

**Screenshots**
https://4950-beta0-enterprise.demo.design.infor.com/components/button/example-index.html

https://github.com/infor-design/enterprise/assets/156752175/88fb5013-1c31-44c1-ac22-67f2e0755513

https://4940-beta0-enterprise.demo.design.infor.com/components/button/example-index.html

https://github.com/infor-design/enterprise/assets/156752175/b3695b03-4db5-4a2e-8bcd-31e6f9dc3134

**Comment by n-ace-ancog** [comment]
I think this might be connected to #8652 regarding new button styles with the removal of the ripple state @tmcconechy. We can close this if this is as intended.

**Comment by tmcconechy** [comment]
@n-ace-ancog Yes we removed this by design request. And actually if you see a place that still HAS the ripple effect please raise an issue for that. Shouldnt be anymore ripples.
