### ISSUE TITLE
SinkPage: Readonly icon hovering issue - BETA 4.95

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8696]
**Describe the bug**
Readonly icon should look slate when hovering (refer to version 4.94).

**To Reproduce**

1. Go to https://4950-beta0-enterprise.demo.design.infor.com/
2. Scroll down to `Datepicker` component
3. Hover over the button under `Date Field (Readonly)`

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

![image](https://github.com/infor-design/enterprise/assets/102151352/bc663d59-8505-4dd3-9c0c-abb10cbb926a)

_version 4.94_
![image](https://github.com/infor-design/enterprise/assets/102151352/51c51da5-875b-487c-a850-7abea2b4444b)

**Platform**
 - All major browsers

**Additional context**

**Comment by glenlieorillo** [comment]
This has been tested and passed.

https://github.com/infor-design/enterprise/assets/102151352/9d43d8a9-c832-4874-be33-ec1900b7d147


https://github.com/infor-design/enterprise/assets/102151352/7afab5c4-c5be-4d6d-b288-8cc729e7ce65

**Comment by tmcconechy** [comment]
I saw this one as well and fixed it on https://github.com/infor-design/enterprise/pull/8694
