### ISSUE TITLE
Veracode scan results 9/28/18

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#870]
**Describe the issue**
Veracode scan results 9/28/18

**Results**
39 New Flaws of 67 total
Score 81
 
![screen shot 2018-09-28 at 4 27 37 pm](https://user-images.githubusercontent.com/814283/46231886-849a6d80-c33b-11e8-87c5-12b98b99fc17.png)

**Actions**
- Several appear to be mitagations / a few fixes to the js/samples needed
- pr with a fix for the flaws that can be
- mitigate the others
- we need to mark the mitagtated flaws as we passed the grace period so the app is showing us as failing now. @EdwardCoyle 

**Additional context**
https://analysiscenter.veracode.com/auth/index.jsp#ReviewResultsAllFlaws:47220:435900:2904750:2684360:2906621:2700110:653798

**Comment by CindyMercadoReyes** [comment]
This ticket is now resolved. Closing out this GitHub ticket.
