### ISSUE TITLE
DataGrid: Failed to set the 'innerHTML' property on 'Element'

### ISSUE THREAD

**Issue by adamzhang1932** [infor-design/enterprise#8709]
**Describe the bug**
When I call the 'updateRow' method in datagrid.js, an error occured:
```
Failed to set the 'innerHTML' property on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
```

**To Reproduce**

Sorry for that it is not easy to reproduce, the error just occurred after we upgrading IDS from v4.91.0 to v4.91.1.
And in v4.91.0, our codes worked well.

**Expected behavior**

**Version**

- ids-enterprise: v4.91.1

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor SunSystems
 - Device: 
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 124.0.6367.119 (Official Build) (64-bit)

**Additional context**
1.In firefox, it works well, the error occurred when I use the chrome browser.
2.For the codes in `updateCellNode` method in `datagrid.js` file:
`wrapper[0].innerHTML = formatted; `,
I am wondering if the above codes in IDS can be changed through some solutions:
**Solution 1:**
Define a new method which can avoid the xss attack, for example ```escapeHtml``` and then:
```wrapper.html(escapeHtml(formatted));```
**Solution 2:**
// If using innerHTML throws an exception, then use the fallback method.
```
try {
  wrapper[0].innerHTML = formatted;
} catch (e) {
  wrapper.empty().append(formatted);
}
```

**Comment by tmcconechy** [comment]
@adamzhang1932 So this only happens in your app not in the examples? I think maybe we need to see why wrapper is empty?

The latest code has a check here..

```
    const wrapper = cellNode.find('.datagrid-cell-wrapper');
    if (!isInline && wrapper[0]) {
      wrapper[0].innerHTML = formatted;
```

So does the diff https://github.com/infor-design/enterprise/compare/4.91.0...4.91.1#diff-13c32b0c73b40992aa6d376fb22d6746845a3b7d6d2545e19bd30687bcabb5a5R11481

Can you test against the latest version? Even if you cant upgrade this would help us know. I personally dont like the `try` approach if we dont know why its happening or cant reproduce but willing to look at other solutions.

**Comment by adamzhang1932** [comment]
@tmcconechy I tried the IDS v4.95.0 just now, the error is still here.

**Comment by adamzhang1932** [comment]
Some things need to know is:
1.The error happened in my app indicated that it is caused by the code:
`wrapper[0].innerHTML = formatted;`
2.And only when I use Chrome browser, the error will occur, and when I use Firefox, everything is fine.
3.When I change the code to `wrapper.html(formatted);`, everything will be fine in Chrome browser and Firefox browser.

**Comment by InforBG** [comment]
This issue can be reproduced starting from 4.91.1. The change is https://github.com/infor-design/enterprise/pull/8447.

**Comment by tmcconechy** [comment]
ok @adamzhang1932 @InforBG I tried the suggestion please review https://github.com/infor-design/enterprise/pull/8718
But still not sure why the existing check wouldnt work. But seems equal and didnt break anything so far.

**Comment by adamzhang1932** [comment]
@tmcconechy Thanks a lot. 
And I left one comment for that.
