### ISSUE TITLE
Datepicker: Misalignment on the datepicker content

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#871]
**Describe the bug**
Datepicker: Misalignment on the datepicker content

**To Reproduce**
1. Go to http://4110-beta0-enterprise.demo.design.infor.com/components/datepicker/example-index.html
2. Open the datepicker on the Date Field
4. Notice the misalignment issue

**Expected behavior**
Datepicker content should be in the correct position/layout

**Screenshots**
<img width="698" alt="screen shot 2018-10-01 at 3 17 31 pm" src="https://user-images.githubusercontent.com/39508864/46275077-4f398e00-c58e-11e8-9300-fd9dd51ebdc7.png">

**Platform**
 - All Devices, OS and Browsers

**Additional context**
No additional context.

**Comment by brianjuan** [comment]
@tmcconechy Where can we test the fix? Issue still exist on http://4110-beta1-enterprise.demo.design.infor.com/components/datepicker/example-index.html and http://localhost:4000/components/datepicker/example-index.html

**Comment by tmcconechy** [comment]
My mistake, we did not deploy this yet it will be on http://4110-beta2-enterprise.demo.design.infor.com/components/datepicker/example-index.html when we make that. Im dragging these back for now to inprogress until its deployed.

**Comment by brianjuan** [comment]
http://4110-rc0-enterprise.demo.design.infor.com/components/datepicker/example-index.html
Passed QA testing across all browsers
