### ISSUE TITLE
Open Requisitions widget: Raised Status Indicators

### ISSUE THREAD

**Issue by ankitsharmaInfor** [infor-design/enterprise#8711]
**User Story**
As a recruiter, I want to know what the status indicator are depicting so that I can determine what action I need to take upon for that particular requisition or candidate.
Jira Ticket: https://jira.infor.com/browse/T2V-20018

**BEHAVIOR CHANGE/IMPACT**
Enhancement on existing functionality

**Dependency**
IDS dependency -
While hovering on indicators, it needs to display the name of the alert for indicators:

**Aging requisition**
Featured requisition
Aging candidate

**Scope**
To show as a tool tip while hovering on the icons to show what it means on the record level if it is aging or featured.

![image](https://github.com/infor-design/enterprise/assets/169445560/8c0e8880-64c6-4710-8fbd-41df756f8541)
![image](https://github.com/infor-design/enterprise/assets/169445560/8b17396b-6643-4211-a4cb-5952f80f9a57)

**Comment by tmcconechy** [comment]
@ankitsharmaInfor 

I think you can easily do this. Just apply the tooltip component on the alert:

Examples:
https://main-enterprise.demo.design.infor.com/components/alerts/example-index.html
https://main-enterprise.demo.design.infor.com/components/tooltip/example-index.html

Source: 
https://github.com/infor-design/enterprise/tree/main/app/views/components/tooltip
https://github.com/infor-design/enterprise/blob/main/app/views/components/alerts/example-index.html

So maybe just need to pass to a developer on that team.

Also the new web component makes it really simpler... So if you adopt that for it might make it even simpler to add 

https://github.com/infor-design/enterprise-wc/blob/main/src/components/ids-alert/demos/example.html#L16
Demo: https://main.wc.design.infor.com/ids-alert/example.html

**Comment by ankitsharmaInfor** [comment]
@tmcconechy Thanks for your inputs, we will check this with the team and get back if there are any queries on this.

**Comment by tmcconechy** [comment]
Cool will close this for now since we have no actions we can do. But any questions let me know
