### ISSUE TITLE
PDFViewer: New Component Enhancement to View PDF Candidate Resumes

### ISSUE THREAD

**Issue by ankitsharmaInfor** [infor-design/enterprise#8729]
This is a new requirement as part of Recruiter Enhancements 2024 release. Below mentioned is the Jira for which we have the below dependecy.
Jira: https://jira.infor.com/browse/T2V-20023

**User Story**
As a recruiter, I want to view candidate resumes within the context of the system so that I am not inundated with multiple windows and tabs in my browser.

**BEHAVIOR CHANGE/IMPACT**
Enhancement on existing functionality

Current: Upon clicking the 'view resume' button the resume file(pdf) opens in another tab on the same browser.

**Dependency**
We have an IDS dependency on the component level to view the file as document viewer over the widget.
Widget: Open Requisition
Component: Data Grid
Check screenshots below for reference.

**Scope**
As a Recruiter, I should be able to view resume file(pdf) over the widget itself or being on the workspace.

Note: This usecase is only applicable if the resume file is in pdf format.

![image](https://github.com/infor-design/enterprise/assets/169445560/29ba6853-2777-46d7-a8c9-c44f80470b30)
![image](https://github.com/infor-design/enterprise/assets/169445560/821b588b-2cd3-4a2a-b383-4c4e7f509dc8)

**Comment by tmcconechy** [comment]
So you want to have a PDF viewer component? 

My first initial impression thoughts on this:

1) Tell them to use a plugin like PDF reader https://www.adobe.com/acrobat/pdf-viewer-extension.html
2) Use a third party dependency like https://mozilla.github.io/pdf.js/ and style our own
3) Use another third party dependency
4) Build our own parser (multi year effort likely)

Will discuss internally

**Comment by inforandy** [comment]
Hi @ankitsharmaInfor 

I believe this enhancement should be requested from the HRT application or perhaps the workspace SDK team, not the IDS team. I'll be closing this issue out. Please contact me if you have any additional questions
