### ISSUE TITLE
Module nav switcher text is not vertically centered

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#8736]
**Describe the bug**
Module nav switcher text is not vertically centered. 
Text is also shifting up and down slightly

**To Reproduce**

1. Go to http://localhost:4000/components/module-nav/example-index.html?colors=fff
2. See misalignment issue

**Expected behavior**
Text should be vertically centered with switcher icon

**Version**
4.95

**Screenshots**
<img width="238" alt="image" src="https://github.com/infor-design/enterprise/assets/1056684/aa43685f-13df-4d31-a32e-7a5bd290990d">

![shifting](https://github.com/infor-design/enterprise/assets/1056684/33e2199c-7c3c-46b0-aef9-0b60876e7154)

**Platform**
 - Chrome
 - Windows 11

**Comment by tmcconechy** [comment]
@ericangeles if we have time
