### ISSUE TITLE
Datagrid: Custom formatter using Soho.Locale.FormatNumber displayed number is incorrect

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#8737]
**Describe the bug**
A custom formatter is using Soho.Locale.formatNumber and seeing that the formatted number is sometimes incorrect.  Seeing this more often when the number has 17 or 18 digits.

**To Reproduce**

1. Using the attached example 'http://localhost:4000/components/datagrid/test-format-number.html'
2. Looking at the values for the Batch Number cells
3. Row 1, the displayed value is 12345678901234568, but the value in the data is 12345678901234567
4. Row 2, the displayed value is 19030114370254880, but the value in the data is 19030114370254879
5. Row 5, the displayed value is 190301143702548800, but the value in the data is 190301143702548792

**Expected behavior**
Soho.Locale.formatNumber does not roundup the last digit. 

**Version**

- ids-enterprise: v4.95.0-dev.0

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
Landmark is currently on ids-enterprise: v4.95.  Landmark has a customer attached to this issue.

**Comment by claudenbach** [comment]
[Git-8737.zip](https://github.com/infor-design/enterprise/files/15381334/Git-8737.zip)

**Comment by tmcconechy** [comment]
@claudenbach i think i can make this work but only if you pass it as a string since the number is too big for JS.

```
Number(12345678901234567)
12345678901234568
Number('12345678901234567')
12345678901234568
```

So should i go ahead with a fix assuming `12345678901234567` as an input to 

```
// Actual test case
Soho.Locale.parseNumber('12345678901234567', { style: 'integer', group: '' })
```

**Comment by claudenbach** [comment]
What about this suggestion, in the method parseNumber change the return statement to be...

return numString.length >= 17 ? BigInt(numString) : parseFloat(numString);

**Comment by claudenbach** [comment]
Maybe a better solution would be to use the following in the method parseNumber...

const isMaxInteger = numString > Number.MAX_SAFE_INTEGER;
return isMaxInteger ? BigInt(numString) : parseFloat(numString);
