### ISSUE TITLE
Datagrid: Pager not updating after new data is pushed and filter is applied.

### ISSUE THREAD

**Issue by AT-Infor** [infor-design/enterprise#8744]
**Describe the bug**

We've got a grid that we push new data to via a timer. On our side we update the data, then we reapply the filter to this grid. However, within your control, you're not correctly changing the filterChanged flag. If I override filterChanged it works fine.

Also the text is not aligned between the input and page selector.

**To Reproduce**
This issue is difficult to reproduce, as you don't have any example pages with this set-up. The screenshots detail this issue well and you can see this issue. It would appear you're looking for a change in the filter when you apply it rather than just applying it as is.

For the alignment issue see below.

**Expected behaviour**
Any time a filter is applied I expect it to still be applied when I add/refresh/remove data from the grid.

**Version**
4.93.0 - I checked out the version and reviewed the change logs this issue has not occurred before.

**Screenshots**

Please see the highlighted area, this showcases the error.
![image](https://github.com/infor-design/enterprise/assets/88100277/778f5467-7466-4946-b704-5284758b0f70)

The error is caused by filterchange not being set correctly. 
![image](https://github.com/infor-design/enterprise/assets/88100277/843ab59b-4df8-418b-bd44-15e583d3ddcf)

**Platform**
 - Infor Application/Team Name: Infor SunSystems
 - Device: (if applicable) N/A
 - OS Version: Window 10
 - Browser Name: Chrome & Edge
 - Browser Version: 124.0.6367.210 (Official Build) (64-bit) & Version 125.0.2535.51 (Official build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
Might need an example here because i think if we remove that line then the pager may rerun more times than its supposed to. But we could see what removing it does in our examples...

**Comment by AT-Infor** [comment]
As requested i've created this issue.  https://stackblitz.com/edit/ids-enterprise-vh4kte?file=index.html
