### ISSUE TITLE
Datagrid: Dropdown on the filter row is not properly handling keyboard commands

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#8745]
**Describe the bug**
A dropdown on the filter row is not properly handling keyboard commands.  

A dropdown on a form is properly handling keyboard commands...
https://main-enterprise.demo.design.infor.com/components/dropdown/test-1000-instances.html

**To Reproduce**

1. Go to 'https://main-enterprise.demo.design.infor.com/components/datagrid/example-filter.html'
2. Place focus in Product Name cell on the filter row
3. Hit the Tab key to tab into Activity cell on the filter row
4. Hit the Enter or Space Bar key to open the dropdown
5. Hit the Up/Down keys to navigate the options in the dropdown
6. Notice that nothing happens
7. Hit the Tab key to tab into Activity (Multi) cell on the filter row
8. Hit the Enter or Space Bar key to open the dropdown
9. Hit the Up/Down keys to navigate the options in the dropdown
10. Notice that nothing happens
11. Notice that two dropdowns are now visible
12. Click on any cell in the datagrid and the dropdowns are not closing
13. Click any where outside of the datagrid and the dropdowns are not closing

**Expected behavior**
Should be able to use the arrow keys to navigate the options in an open dropdown.
When tabbing out of a filter cell with the dropdown open the dropdown should close or when clicking off the open dropdown.

**Version**

- ids-enterprise: v4.95.0-dev.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/39804038/c85cabe9-a258-43cd-ae32-f996cdbf5113)

**Additional context**
Landmark will require a patch to v4.95

**Comment by tmcconechy** [comment]
@ericangeles can you look? @claudenbach did this work before ever?

**Comment by claudenbach** [comment]
I'll need to verify.  But an open dropdown used to close when clicking  or navigating using the keyboard somewhere else in the datagrid or clicking outside of the datagrid.

**Comment by claudenbach** [comment]
Dropdowns in a cell (not found on the filter row) are working correctly.  And there are no errors in the console. I'm using the Tab / Shift Tab / Up and Down Arrow keys / Space bar in the example below.

![Dropdown-In-Cell](https://github.com/infor-design/enterprise/assets/39804038/1b067f9e-8732-4b35-9d05-5a7102bb4570)

**Comment by claudenbach** [comment]
Checking with a QA and they stated this used to work.
