### ISSUE TITLE
Donut: Chart cut off

### ISSUE THREAD

**Issue by aishanyagupta** [infor-design/enterprise#8755]
The donut is behaving inconsistently, it is being cut off in some cases and cannot see legends that are placed in bottom for banner widgets, 
Here is the stackblitz link for the reproduced issue, 
[Donuts cut off](https://stackblitz.com/edit/ids-quick-start-1771-y2n5tj?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html)

Issues found:

- Donut is cutting in middle in some cases, few of those cases are while opening and closing inspect tab,
[screen-capture (5).webm](https://github.com/infor-design/enterprise/assets/167510255/c7d21ba2-d007-4969-9e28-619421f60ca6)
- The donut should be displayed in whole and we should also see legends that are not being shown initially

We are using ids version: 4.92.2 and beta SDK 8.
We can also see another issue that busy indicator can only be seen at the end of the completion of loading this behavior is only seen in donuts with bottom legend placements.

Please note that these issues are only found in donuts placed in banner

For full details refer to teams post:
[Teams Post](https://teams.microsoft.com/l/message/19:2b0c9ce520b0481a9ce115f0ca4a326f@thread.skype/1716367241073?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1716367241073&teamName=IDS%20Enterprise%20Development&channelName=General&createdTime=1716367241073)

**Comment by tmcconechy** [comment]
@aishanyagupta can you write out the steps? When i load the page it looks fine. When i pick from the dropdown its slow but it eventually works?

**Comment by aishanyagupta** [comment]
@tmcconechy 
The steps to reproduce are, going to widget and right clicking and scrolling to the bottom, and select inspect
<img width="291" alt="image" src="https://github.com/infor-design/enterprise/assets/167510255/db62e140-49b8-42db-a5a2-ea571be6c3ee">
try resizing the inspect tab and then close, then we can see the donut is being cut off
[screen-capture (5).webm](https://github.com/infor-design/enterprise/assets/167510255/c7d21ba2-d007-4969-9e28-619421f60ca6)
Here is a screen recorded video of it
