### ISSUE TITLE
Calendar: When clicking +1 more in the calendar. it will double fire the selectDay().

### ISSUE THREAD

**Issue by LinweiW** [infor-design/enterprise#8769]
**Describe the bug**
If the calendar have over 3 events, when clicking the +1 more pill there will be double fired the selectDay() method. First one is from appendEvent which the jquery cannot find the ".calendar-event-more" so its getting into the !(moreSpan) trigger it. Then second one is from handleEvents which seems normal. 

**To Reproduce**
1. having three more events in the calendar cell to get the +1 more pill. 
2. clicking the cell trigger a modal etc.
3. the result of single click acts like double click. 

**Expected behavior**
single click the +1more pill should not triggering double click effect

**Version**
IDS Enterprise Components - v4.86.0

**Screenshots**

**Platform**
chrome

**Additional context**

**Comment by LinweiW** [comment]
is there a workaround we can use while waiting for the fix

**Comment by tmcconechy** [comment]
Maybe you can watch all the related events `click`, `dblclick` and `select` and figure out whats correct for your case?

It wasn't intended to be able to click the +1 either actually. So really this is partly an enhancement. We will need some time to get to it.
