### ISSUE TITLE
Can't Open The Application Menu For Filterable Many Items Component

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#877]
**Describe the bug**
On all browser the user can't open the application menu for filterable many items component

**To Reproduce**
1. Go to URL: http://4110-beta1-enterprise.demo.design.infor.com/components/applicationmenu/test-filterable-many-items.html
2. Click on the three line eclipse button
3. Nothing happens. When the user clicks on the button the application menu should open.
4. See screen shot attached. 

**Expected behavior**
When the user clicks on the button the application menu should open.

**Screenshots**
![bs_win10_edge_17 0](https://user-images.githubusercontent.com/39101346/46301447-5ce21a00-c574-11e8-8b9b-1e42997821e1.jpg)

**Platform**
 - All browsers 

**Additional context**
None

**Comment by EdwardCoyle** [comment]
Looks like the included partial template for the "Many Items" application menu was removed at some point:  https://github.com/infor-design/enterprise/blame/master/app/views/components/applicationmenu/test-filterable-many-items.html#L6
