### ISSUE TITLE
Icon: Icon "spreadsheet" is not showing in safari

### ISSUE THREAD

**Issue by LinweiW** [infor-design/enterprise#8772]
**Describe the bug**
icon "spreadsheet" is not showing in safari

**To Reproduce**
open the safari with a button 
<button soho-button="icon" icon="spreadsheet"></button>

**Expected behavior**
The icon should be displayed

**Version**

data-sohoxi-version="4.86.0"
data-ids-enterprise-ng-version="15.6.0"

**Platform**
safari

**Additional context**

**Comment by tmcconechy** [comment]
Looks ok on my end. 

<img width="709" alt="Screenshot 2024-06-03 at 11 14 59 AM" src="https://github.com/infor-design/enterprise/assets/814283/77f752ad-e61e-408b-9e84-e7119db26918">

a) Does it work OK on chrome and not safari for you? 
b) That version is older but the icon appears as well as per https://4860-enterprise.demo.design.infor.com/components/icons/example-index.html

Anything else you can add? maybe something you are doing?

**Comment by LinweiW** [comment]
the icon was wrapped by a <soho-toolbar-button-set>. button has a extraIconClass="azure07-color". works ok for Chrome but not Safari.

**Comment by tmcconechy** [comment]
@LinweiW Ok, Might be an issue with that class not the icon? What do you mean it was wrapped? Could you provide an example html or stackblitz?

**Comment by LinweiW** [comment]
@tmcconechy What do you mean it was wrapped? typo here. accidently cut the sentence. 
this is how its setup. 
https://stackblitz.com/edit/ids-quick-start-1761-jg45eq?file=src%2Fapp%2Fapp.component.html

**Comment by tmcconechy** [comment]
@LinweiW I couldnt get that to run in safari but http://localhost:4200/ids-enterprise-ng-demo/icon (https://github.com/infor-design/enterprise-ng/blob/main/src/app/icon/icon.demo.html) has an example.

It seems like it works ok. But wondering if it needs `-webkit-text-fill-color` or `-webkit-text-fill-color` or `-webkit-text-stroke-color` too?

But cant seem to test. Maybe an old version of safari?

**Comment by tmcconechy** [comment]
<img width="1106" alt="Screenshot 2024-06-03 at 2 26 33 PM" src="https://github.com/infor-design/enterprise/assets/814283/a1bffc63-6a63-4d04-a845-b43e8dd89ee8">

If so can test if one of these works and we could add.

**Comment by LinweiW** [comment]
i couldnt test it. but the we have another button with icon="add" and exact same setup it can show. and i tested with icon="check" its showing fine also.

**Comment by LinweiW** [comment]
Issue solved. Issue can be closed. Thanks
