### ISSUE TITLE
Datagrid: Tooltip for a column's displayed filter operator is incorrect

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#8773]
**Describe the bug**
The displayed tooltip for a column's filter operator is incorrect.  The tooltip is showing 'Contains', when it should be 'Starts With'.

**To Reproduce**

Have been unable to create a test example that demonstrates this issue.  But have provided ,gif file containing console logs as to what Landmark is experiencing.  Seems tied to a column having a defaultFilterOperator that is not the first filterConditions option.

Perhaps tied to the grid-tooltip div created for the data-automation-id.

Will include an updated test-filter-with-default-operator.html that I've been testing with, but can't seem to show the issue.

**Expected behavior**
Expect the displayed tooltip to match the column's filter operator being shown.

**Version**

- ids-enterprise: v4.95.2

**Additional context**
Let me know if you want me to demonstrate the issue Landmark is experiencing.

**Comment by claudenbach** [comment]
![Tooltip-Filter-Operator](https://github.com/infor-design/enterprise/assets/39804038/abe3588f-0a9d-4ade-86a4-8b472e79419f)

**Comment by claudenbach** [comment]
Including example in enterprise that I'm using, but unable to duplicate the issue.

[Git-8773.zip](https://github.com/user-attachments/files/15536635/Git-8773.zip)

**Comment by tmcconechy** [comment]
cc @ericangeles any thoughts initially?

**Comment by tmcconechy** [comment]
@claudenbach looking into this one but cant reproduce either. Also having a bit of an issue following the video but i get that the tooltip is the wrong one.

One idea is maybe could be maybe we can change the logic to update the tooltip again just before its being displayed? Think that could work?

**Comment by claudenbach** [comment]
I moved to 4.95.2 and was still able to duplicate.

I think updating the tooltip again before its being displayed should work.

Thanks.

**Comment by tmcconechy** [comment]
ok cool. Give me PR a try on your end and let me know. Note that i made one update.

**Comment by claudenbach** [comment]
I've been testing with your changes and it looks good.

Thanks.

**Comment by claudenbach** [comment]
Here's an example that illustrates the issue.  Landmark makes use of the datagrid's method setFilterConditions().  This method properly sets the column's operator and value.  However the displayed tooltip is incorrect.

[Tooltip-Issue.zip](https://github.com/user-attachments/files/15994858/Tooltip-Issue.zip)
