### ISSUE TITLE
Locale: Incorrect "Available" translations in Italian and Thai

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#8786]
Locale: Incorrect "Available" translations in Italian and Thai

**Italian**
![image](https://github.com/infor-design/enterprise/assets/66057969/92b709f0-e2f8-4f23-91d6-cd63fa61d463)

**Thai**
![image](https://github.com/infor-design/enterprise/assets/66057969/cb0ef411-61c1-4aa3-8cac-bdc37407fa62)

en-messages.json
 "Available": { "id": "Available", "value": "Available", "comment": "Button tooltip used in a list of movable items" },
 "Selected": { "id": "Selected", "value": "Selected", "comment": "Text describing a selected object" },

"Available" and "Selected" are unclear strings. Result = Mistranslations. For example, in French, there are 4 translations for "Selected". The provided comments are not consistent.

"Available" and "Selected" = Poor strings
"Available Items" and "Selected Items" = Clear strings + add comments indicating string context/usage including the fact that Item is NOT a product/an article. Item = Part of a list, collection, or set

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
Hi @tmcconechy, 
These have been corrected in the latest translation files, 
\\nlbavwmemoq2\cc\ToDev\SohoUX\it-IT-messages.json	68,501	08/16/2024 09:09	-a--
\\nlbavwmemoq2\cc\ToDev\SohoUX\th-TH-messages.json	79,537	08/16/2024 11:50	-a--
