### ISSUE TITLE
Locale: Truncated "Apply" button translations (e.g. Dutch, Spanish, French (France+Canada), German, Italian, Thai, etc.)

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#8787]
Locale: Truncated "Apply" button translations (e.g. Dutch, Spanish, French (France+Canada), German, Italian, Thai, etc.)

**English**
![image](https://github.com/infor-design/enterprise/assets/66057969/02259163-2153-45c7-b940-c51d799105cf)

"Apply" translations come from SohoUX > en-messages.json
"Apply": { "id": "Apply", "value": "Apply", "comment": "Text in a button to apply an action" },

**Truncated "Apply" translations**
Below are some examples in Dutch, French and German:
![image](https://github.com/infor-design/enterprise/assets/66057969/f91f33fa-1864-4c34-b2cb-8dfbf9c28123)
![image](https://github.com/infor-design/enterprise/assets/66057969/e65596aa-5eb8-4d20-b5aa-6f103c1c9327)
![image](https://github.com/infor-design/enterprise/assets/66057969/b9eae5dd-43ec-4d42-91e2-38e71c83d866)

**Comment by tmcconechy** [comment]
@cpinatel7 I see two bugs here:

1) https://main-enterprise.demo.design.infor.com/components/datepicker/example-month-year-format.html the layout is messed up (extra space on one side)
2) in german its cut off https://main-enterprise.demo.design.infor.com/components/datepicker/example-month-year-format.html?locale=de-DE
2) https://github.com/infor-design/enterprise/issues/8639 -> may help fix this

**Comment by cpinatel7** [comment]
Thanks. Hopefully #8639 (that I initially reported in Landmark a while ago - Fix not yet deployed in Landmark) will help.

If the translation for "Clear" (left-hand side button) is long, it's also truncated.

Example in Landmark dummy/pseudo-language:
![image](https://github.com/infor-design/enterprise/assets/66057969/bab0a907-f5ce-4a14-9eee-8defc4656670)
