### ISSUE TITLE
Busy Indicator Ajax Component: The dropdown and Lookup can be opened at the same time

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#879]
**Describe the bug**
All Browser: Busy Indicator Ajax Component: The dropdown and Lookup can be opened at the same time

**To Reproduce**
1. Go to url: http://4110-beta1-enterprise.demo.design.infor.com/components/busyindicator/test-ajax-calls.html
2. Click on the drop down icon and the drop down list box pops up
3. Click on the Lookup button and the lookup results pop will appear
4. Both the drop down list box and the lookup results pop up are appearing at the same time. 
5. Please see screen shot attached. 
![busy indicator](https://user-images.githubusercontent.com/39101346/46303600-49d24880-c57a-11e8-9022-ecaf9c7c220b.png)

**Expected behavior**
Two pop up windows should not appear at the same time for the Busy Indicator component.

**Screenshots**

![busy indicator](https://user-images.githubusercontent.com/39101346/46303626-53f44700-c57a-11e8-80ee-942e9b9ca7a1.png)

**Platform**
 - All Browsers 

**Additional context**
None

**Comment by tmcconechy** [comment]
Descoping this issue for now
