### ISSUE TITLE
Remove the uplift theme for 4.11.0 release

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#880]
**Is your feature request related to a problem? Please describe.**
We need to remove the uplift for the 4.11.0 release.

**Describe the solution you'd like**

- [x] Change examples to not have mock data be similar to true data (thus removing theme references):
  - `app/views/components/personalize/example-modal.html`
  - `app/views/components/menubutton/test-selected-item.html`
  - `app/views/components/personalize/example-settings-page.html` (prob move this to patterns as well)
  - `app/views/includes/header-actionbutton.html`
- [x] Disable references to "uplift" in `docs/CHANGELOG.md`
- [x]  Disable references in build flow:
  - `scripts/build.js`
  - `scripts/configs/cssmin.js`
  - `scripts/configs/sass.js`
- [x]   Remove "uplift" from `src/components/personalize/personalize.js`
- [x]  Verify there are no more functioning references to `src/themes/uplift-theme.scss`

**Describe alternatives you've considered**
In the future we will come up with more generic ways to reference these files. Due to the coming release, we have minimal time now.

**Additional context**
n/a

**Comment by brianjuan** [comment]
http://4110-rc0-enterprise.demo.design.infor.com/components/list
I've checked the example pages of all of the components and Uplift theme were already removed. I guess this passed QA testing.
