### ISSUE TITLE
Toolbar: looks different in RTL - BETA 4.96

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8811]
**Describe the bug**

**To Reproduce**

1. Go to https://4960-beta0-enterprise.demo.design.infor.com/?locale=ar-SA
2. Ensure RTL is on
3. Scroll down to '.Toolbar Actions'

**Expected behavior**
<img width="1350" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/bc066085-7d11-42d7-a79e-55b80e5c9cc2">

**Version**

- ids-enterprise: v4.96.0-beta0

**Screenshots**
<img width="1355" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/bfee1347-43ed-4086-8675-47af82f15642">

**Platform**
All

**Additional context**
in general, sink page is broken in RTL. a lot of components is not working properly
error in console
<img width="807" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/7665b00b-6a0b-4c19-8ff6-19452f4ce1dd">

**Comment by tmcconechy** [comment]
Just a smallbug effecting the page will fix. Works ok on https://4960-beta0-enterprise.demo.design.infor.com/components/toolbar/example-index.html?locale=ar-SA

**Comment by jbrcna** [comment]
QA Passed
<img width="1281" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/3deb0fa4-a398-44d1-8137-1199e4757b84">
