### ISSUE TITLE
NotificationBadge: Badge disappears on buttons under toolbar in mobile mode

### ISSUE THREAD

**Issue by lskonieczka** [infor-design/enterprise#8812]
**Describe the bug**
1. When button with notification badge is used within toolbar it works just fine in desktop mode but the notification container gets hidden in mobile mode
2. Notification badge is completely ignored (both in desktop and mobile) when button is displayed under "more" button in toolbar

**To Reproduce**

1. Add button with notification badge under enterprise QuickStart project in "Toolbar Actions" section both inside and outside "more" button
2. Verify if you can see notification both in mobile and desktop view

By mobile view I mean all devices matching the query:
@media (max-width: ($breakpoint-phone-to-tablet - 1))

**Expected behavior**
1. for buttons outside "more" - Notification badge is visible both in desktop and mobile mode
2. for buttons inside "more" - notification badge should be visible on each individual buttons but also some way of displaying notification on "more" button itself should be considered in my opinion. 

**Version**

- ids-enterprise: 4.95

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/163156055/a7d8dd3b-5b05-4e35-ba94-b53220cb95f2)

![image](https://github.com/infor-design/enterprise/assets/163156055/192bdfbb-aacd-4a21-b02d-7632097e4e7f)

**Platform**
 - Infor Application/Team Name: WFM
 - Device: x86 PC
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 125.0.6422.142

**Additional context**
CSS responsible for the issue:
\ids\enterprise\src\components\toolbar\_toolbar.scss@426

**Comment by tmcconechy** [comment]
@lskonieczka can you include an example for this. We may not put it together the way you did and be able to reproduce?

**Comment by lskonieczka** [comment]
Hi,

please have a look:

https://stackblitz.com/edit/ids-enterprise-4960-z4ebwm?file=index.html

Calendar icon has a badge only when width is greater than 766px, as soon as it gets smaller, badge disappears. 
Please also note that I could not make badge working with "more" menu.

**Comment by tmcconechy** [comment]
@lskonieczka ok it should not hide on lower break point. Not sure how it looks in the menu though. We havent had that feature but can discuss.

**Comment by ericangeles** [comment]
@tmcconechy, we haven't had many use cases previously with notification badge, so this one is good to look at.

**Comment by tmcconechy** [comment]
@ericangeles yep definately should not hide when you resize the page. Just need to define how it looks in the menu...(if at all)

**Comment by tmcconechy** [comment]
Ok on the same page there @lskonieczka I 💯 agree
