### ISSUE TITLE
DataGrid: add "searched" trigger event

### ISSUE THREAD

**Issue by aldsdelram** [infor-design/enterprise#8814]
**Is your feature request related to a problem or use case? Please describe.**
we have this use case that empty message for the data grid changes depends on the following conditions:
- when the data grid has no records
  -  empty message is to instruct the user to create a new record
- when filtering/keyword searching has no records
  -  empty message is to instruct the user to refine the search 

Problem is DataGrid only fires event when filtering of rows coming from Column filters but not when keyword search is triggered.
![image](https://github.com/infor-design/enterprise/assets/9246064/147960a2-c35e-40d2-90ef-8ce5bd0141f0)

**Describe the solution you'd like**
to add a new trigger event "searched", same with "filtered", emit the filter expression
![image](https://github.com/infor-design/enterprise/assets/9246064/ff12a51f-3133-4b8d-b076-1643630a0fb7)

**Describe alternatives you've considered**

**Additional context**
And what application do you work on? Infor M3 CLM

In addition, if in case this gets implemented, implementation of the "searched" event emitter to enterprise-ng is much appreciated.

**Comment by tmcconechy** [comment]
Possible workaround are `change` or `keydown` or `rendered`
