### ISSUE TITLE
Locale: Date Formatter Issue with different languages/locale

### ISSUE THREAD

**Issue by VadoodS** [infor-design/enterprise#8820]
**Describe the bug**
Soho Locale Formatter Issue with different languages/locale.

**To Reproduce**
Issue 1 :
1).I am using soho locale formatter to format date to display on widget.
2). Use below code to format date Soho.Locale.formatDate(new Date(), {
			pattern: 'MMM dd',
		});
3). Use language and locale as spanish(es-ES).

**Expected behavior**
Soho locale formatter should format date to Junio 13 but it is formatting to Jun 13

**Screenshots**
![image](https://github.com/infor-design/enterprise-wc/assets/172265383/0300dbcc-4ed9-4264-90f8-fcd005f2e9ec)

**Comment by VadoodS** [comment]
@tmcconechy , I gone through your example. For "'es-ES" locale the expected output is "Junio 14" but we are getting output as "Jun 14".

**Comment by VadoodS** [comment]
@tmcconechy , 
Issue 1 :
With MMMM date getting translated properly for Spanish. Thanks for clarification.

For Issue2 do I need to use different format to format below date in German.
Soho.Locale.formatDate(
new Date(06/14/2024 12:03 vorm.),
{ pattern: "yyyyMMdd HH:mm:ss" },
);

**Comment by tmcconechy** [comment]
@VadoodS yes you can use:

``` 
Soho.Locale.formatDate(new Date(), { pattern: 'yyyyMMdd hh:mm:ss a' })
```

But you cannot pass `Date(06/14/2024 12:03 vorm.)` to it thats not a valid date expression

**Comment by VadoodS** [comment]
@tmcconechy ,
The date picker is providing me date in the mention format "06/14/2024 12:03 vorm." for German.
Is it something that soho locale formatDate function should be enhanced in future to support this format as well. Please confirm.

**Comment by tmcconechy** [comment]
@VadoodS 

We cant change `Date()` so that works because that JS. We do have a parseDate that can take a date and convert it to a Date object. But i think that one case doesnt work, so if you need we could do it

```
Locale.parseDate('2019-01-01', 'yyyy-MM-dd'));
Locale.parseDate('2019-01-01', { dateFormat: 'yyyy-MM-dd', locale: 'es-ES' } )
Locale.parseDate('20/10/2019 20:12', { date: 'datetime', locale: 'es-ES' });
Locale.parseDate('Noviembre de 2019', { date: 'year', locale: 'es-ES' });
```
