### ISSUE TITLE
Datagrid: Using maskOptions function with textEllipsis showing visual artifact

### ISSUE THREAD

**Issue by claudenbach** [infor-design/enterprise#8821]
**Describe the bug**
There is a visual artifact (looks like a partial ellipsis) that appears when editing a numeric cell that has the properties of align: 'right', textOverflow: 'ellipsis', and is using a maskOptions function.  Seeing this with a rowHeight: 'extra-small'.  See the comment below.

Also seeing this visual artifact on a column that contains a tag.  When narrowing the column width, narrow the width to the point were just a single ellipsis is being displayed.

**To Reproduce**

1. Using the attached example, 'http://localhost:4000/components/datagrid/test-mask-options-with-text-overflow.html'
2. Click on a Quantity cell to edit
3. Notice that there is a visual artifact being displayed on the righthand side of the cell

**Expected behavior**
Visual artifact should not be shown.

**Version**

- ids-enterprise: v4.95.0-dev.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/39804038/6cb988c9-8f0d-4a72-b3ac-0752303e121d)

**Additional context**
Landmark will need a patch to v4.95.

**Comment by claudenbach** [comment]
[Git-8821.zip](https://github.com/user-attachments/files/15825430/Git-8821.zip)

**Comment by tmcconechy** [comment]
@claudenbach this seems pretty minor to me?

**Comment by claudenbach** [comment]
Acknowledging, since it doesn't affect the behavior of editing the cell's vaule.

**Comment by tmcconechy** [comment]
Will fix with medium priority here

**Comment by claudenbach** [comment]
Also able to see the partial ellipsis on cells of a column with tags.

![Tag-With-Ellipsis](https://github.com/infor-design/enterprise/assets/39804038/9678b8a0-154e-4557-b870-eab145e4395d)

**Comment by claudenbach** [comment]
Providing zip file containing the changes made to test-alerts.html...

[Tag-With-Ellipsis.zip](https://github.com/user-attachments/files/15874592/Tag-With-Ellipsis.zip)

**Comment by tmcconechy** [comment]
@claudenbach added a fix to that PR as well. I made the fix more specific so as not to break anything else so do check if you see any more issues like it on your end

**Comment by claudenbach** [comment]
Attaching another example showing the ellipsis issue with a column containing a tag.  In this example, I've updated the test-mask-options-with-text-overflow.html.

[Tag-With-Ellipsis.zip](https://github.com/user-attachments/files/15992864/Tag-With-Ellipsis.zip)
