### ISSUE TITLE
Module Tabs: Active and inactive program tab color contrast to be more noticeable

### ISSUE THREAD

**Issue by edisonferrer** [infor-design/enterprise#8831]
**Is your feature request related to a problem or use case? Please describe.**
Customers have complained about the colors are too close so it is hard to see active program. We have discussed with IDS and gotten "approval" of new colors to use.

**Describe the solution you'd like**
New color specifications can be found in this Figma file:
https://www.figma.com/design/Y041RDg72qE0vWPhpqSk2j/Module-Tab-Colors?m=dev&node-id=0-1&t=oep0xe0pbdM3dFC8-1

Also discussed in https://inforwiki.atlassian.net/browse/MUA-14190

**Describe alternatives you've considered**

**Additional context**
And what application do you work on? Infor M3

**Comment by tmcconechy** [comment]
Was having no colors considered? Just wondering if there is another way to help this problem.

**Comment by denmacalinao** [comment]
Hi @tmcconechy,

Erik Backlund provided a link to the color specifications for the module tabs:

https://www.figma.com/design/Y041RDg72qE0vWPhpqSk2j/Module-Tab-Colors?m=dev&node-id=0-1&t=oep0xe0pbdM3dFC8-1

I don't have access to the Figma file yet. I've also tried reaching out to Erik, but haven't been able to connect.
