### ISSUE TITLE
Datagrid: Memory leak issue in soho datagrid

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise#8832]
**Describe the bug**
We are addressing memory leak in our app and identified code implementations in soho datagrid that is contributing to the issue. We have made modifications in sohoxi.js and noticed improvements in memory consumption. Please see attach [sohoxi.txt](https://github.com/user-attachments/files/15894121/sohoxi.txt). This is also related to this pull request: https://github.com/infor-design/enterprise/pull/8833.

**To Reproduce**

1. Continuously add rows to the list with different formatters by updating the dataset
2. Observe the memory consumption

**Expected behavior**
Memory consumption should not increase a lot and there should be no memory leak

**Version**

- ids-enterprise: [4.90.4]
- ids-enterprise-ng: [17.1.4]

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor M3]

**Additional context**

**Comment by tmcconechy** [comment]
@inforrpunay is https://github.com/infor-design/enterprise/pull/8833 for this?

**Comment by inforrpunay** [comment]
> @inforrpunay is #8833 for this?

Hi @tmcconechy, yes.
