### ISSUE TITLE
Calendar: Custom Sorting method for each event being rendered in in MonthView

### ISSUE THREAD

**Issue by InforOttoLing** [infor-design/enterprise#8836]
**Is your feature request related to a problem or use case? Please describe.**
Use case: 
Currently, all the events in Calendar(Month View) are sorted by start time. We'd like to be able to display the events sorted based on some custom logic.

https://github.com/infor-design/enterprise/blob/main/src/components/calendar/calendar.js#L779

**Describe the solution you'd like**
Add a parameter in the Calendar component to allow users to provide a custom sorting method that determines the sorting order of the events being displayed on each day in the month view.

**Describe alternatives you've considered**
The current solution we are using, involves sorting the events before adding them into the calendar, then overriding the actual start time, so that the events will display in a specific order.

**Additional context**
And what application do you work on? 
Infor WFM

**Comment by tmcconechy** [comment]
For solution: Could add a setting that allows you to change `starts` into other fields in the calendar data `sortField` perhaps

https://github.com/infor-design/enterprise/blob/main/src/components/calendar/calendar.js#L779

**Comment by InforOttoLing** [comment]
The logic we are using to sort the events involves reading data from multiple fields, so I don't think updating the field being used for sorting is sufficient for my use case.

**Comment by tmcconechy** [comment]
ok we can look at a sort function callback as well for the setting.
