### ISSUE TITLE
Modal: Text in message dialog is truncated

### ISSUE THREAD

**Issue by rvaja-infor** [infor-design/enterprise#8839]
**Describe the bug**
The message dialog sometimes truncates the message text. In the attached screenshot you can observe that message text has been truncated. The text should read 

> The file does not exist in the system: 'file://C/Application/Administration/Data/ABC/ABC/ABC_PYMT_A_XYZAB_PARAMS.txt'

1. Go to 'https://ids-enterprise-4930-amgax7.stackblitz.io'
2. Click on 'Error Example' button
3. Text in message dialog is truncated, see screenshot

**Expected behavior**
The message in the dialog should not be truncated and clearly visible.

**Version**
- ids-enterprise: v4.93.0

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/45232365/858a961d-0963-48ea-9a84-99bf3b21355c)

**Platform**
 - Infor Application/Team Name: Infor SunSystems
 - Device: Windows Desktop
 - OS Version: Windows 11
 - Browser Name: Edge/Chrome
 - Browser Version: latest 64bt

**Comment by tmcconechy** [comment]
Maybe we can do something with css `word-wrap` here.

**Comment by rvaja-infor** [comment]
> Maybe we can do something with css `word-wrap` here.

I did look at this initially but it just don't look right. The only value that seem to have any effect was 'break-word', which produced the below.
![image](https://github.com/infor-design/enterprise/assets/45232365/b9b198c4-4444-4ffa-b5c6-f91449db6a2b)

Considering the string in single quotes is a path it does not feel right to word wrap it unless it looks meaningful. I did not propose to our analysts but can see what they think, but maybe rejected.

**Comment by tmcconechy** [comment]
@rvaja-infor maybe you can change the maxWidth here? https://github.com/infor-design/enterprise/blob/main/src/components/message/message.js#L21

**Comment by rvaja-infor** [comment]
Thought did cross my mind. Also a scrollbar for this. What I am trying to do here is effect other message dialogs and was looking for a more generic solution.

I may ask about the scrollbar as these paths can be any size which means I would need to find a sensible max-width, but that is not always going to be reasonable for some cases so the scrollbar may be the way forward.

**Comment by tmcconechy** [comment]
I'll talk to our team as well for ideas

**Comment by rvaja-infor** [comment]
@tmcconechy , had a closer look and see the issue.
The message div has a max-width of 369px. If this is removed then the message dialog expands to the content. Any reason for this max-width?

**Comment by tmcconechy** [comment]
@rvaja-infor this max width was an attempt to get a reasonable sized message (what the designs originally showed). Maybe we can look at a way to unset max width.

**Comment by yohannahbautista** [comment]
@rvaja-infor  @tmcconechy 
Hello, would setting maxWidth to 'fit-content' be a possible solution? https://stackblitz.com/edit/ids-enterprise-4930-vdasqa?file=index.html
It would avoid needing to specify a value for width.

**Comment by tmcconechy** [comment]
Looks like a good solution to me... @yohannahbautista what do you think @rvaja-infor ?

**Comment by rvaja-infor** [comment]
@tmcconechy , seems okay to me. Just so I have got the right end of the stick here, basically a new option is being added into the settings for message dialogs to specify max-width, is that correct?

**Comment by tmcconechy** [comment]
@rvaja-infor that option already works i believe cc @yohannahbautista ?

**Comment by rvaja-infor** [comment]
I just seen the option in the Enterprise controls we are currently on. Just not been exposed on our GWT wrapper, so not hard to sort out.

The documentation at https://design.infor.com/components/components/message/enterprise/, is not very clear how this setting can be used.
> settings.maxWidth | string=null | Pass a specific string or defaults to null

We will however give this a try.

**Comment by tmcconechy** [comment]
@yohannahbautista can you update the docs? Mention you can use `fit-conent` (or any valid css width)
