### ISSUE TITLE
Datagrid: Incorrect updates in commitCellEditUtil

### ISSUE THREAD

**Issue by crisjoshua-inf** [infor-design/enterprise#8850]
**Describe the bug**
When using setActiveCell and click to refocus from one editable cell to another. A unique bug occurs where the value of the initially entered/clicked value is placed in the next focused value. This is only achieved with a specific scenario of code

Things to note: 
datagrid.settings.source always has a value with an placeholder function much like this
() => {
/* placeholder empty */
};.
when enter is done, a different focus is simulated and setActiveCell or element.click is used by the application to focus on the editable cell

**To Reproduce**
1. Use attached html file and replace the existing test-editable-inline-editor.html (https://github.com/user-attachments/files/15966129/test-editable-inline-editor.zip)
2. Press enter on 3 editable field or as show on gif below
![SimulatedEnterKeyIssue](https://github.com/infor-design/enterprise/assets/115533426/e78d0cd5-fd11-4100-8ce6-121869c1fe1a)

**Expected behavior**
Value of the 3rd editable row does not duplicate in the first editable row

**Version**
v4.97.0

**Platform**
 - Infor M3 H5A Application
 - Browser Name: Chrome/Edge
 - Browser Version: Version 126.0.6478.115 (Official Build) (64-bit) / Version 126.0.2592.68 (Official build) (64-bit)

**Additional context**

**Comment by tmcconechy** [comment]
This one is https://github.com/infor-design/enterprise/pull/8838 correct?

**Comment by crisjoshua-inf** [comment]
Yes this is the one.
