### ISSUE TITLE
ColumnChart: Data with only negative values has misplaced bars

### ISSUE THREAD

**Issue by DavidMoerman** [infor-design/enterprise#8854]
**Describe the bug**
I have modified the example-negative-value.html file from the demo, to a dataset with just two negative values:

```
    var negativedataset = [{
            data: [{
                name: 'Automotive',
                shortName: 'Auto',
                abbrName: 'A',
                value: -7
            }, {
                name: 'Distribution',
                shortName: 'Dist',
                abbrName: 'D',
                value: -5
            }
          ]
          }];
 
    $('#column-bar-example').chart({type: 'column', dataset: negativedataset});
```
    
![image](https://github.com/infor-design/enterprise/assets/145779154/6b9621a9-a316-4ea0-8a94-958cadd2fffa)
 
If I alter the dataset slightly by adding a third bar that has a zero value, the chart looks like this:

![image](https://github.com/infor-design/enterprise/assets/145779154/c2ca3705-8aff-4593-a95b-afa534ddb624)

This last chart is how I would expect the first one to look like as well (but then just with two bars, of course).

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4051
