### ISSUE TITLE
Datagird editor - Datepicker isn't opening correctly, or exiting edit mode

### ISSUE THREAD

**Issue by mlick27** [infor-design/enterprise#8860]
We are using ids-enterprise-ng: 17.1.5 for Angular. I have an editable datagrid with a date column in it. We're seeing 3 problems.  

**To Reproduce**

PROBLEM 1 - CALENDAR DOESNT OPEN UNLESS CELL IS ACTIVE FIRST
1. If I hover over the cell, the calendar icon appears as expected.
2. If I click on the calendar icon, the cell just becomes active, and the calendar does not open - it should open.
3. If I click on the calendar icon again, it opens as expected, but it should do it on the first click, and not require 2.

PROBLEM 2 - AFTER PICKING A DATE, FIELD IS LEFT IN EDIT MODE
1. Pick a date, calendar closes as expected.
2. Text representation of date is populated into cell as expected.
3. Cursor is active in cell, leaving it in edit mode - this is not correct. After selecting a date, it should end editing for the cell.

PROBLEM 3 - cellChange event doesn't fire
1. Because the cell is still in edit mode, cellChange isn't firing until the cell loses focus by the user either hitting enter or clicking elsewhere.

I cannot reproduce this behavior with the samples.  Those are working as expected.  I suspect we have a problem that's not directly related to IDS, but we have no idea what it might be.  For #2 and #3, it's like the code is failing somewhere during the update of the value, but instead of throwing an error, just quitting before emitting the cellChange event.

**Expected behavior**
Single click to open the calendar.
Value populated the cell without requiring using to hit enter or make the cell inactive
cellChange event should fire.

**Version**

- ids-enterprise-ng: 17.1.5 for Angular.

**Screenshots**
Before clicking anything - no active field - correct
![image](https://github.com/infor-design/enterprise/assets/45044406/0179dda9-99b9-4860-b7fa-63ebf5d1f6ed)

Hover over field, and click the calendar icon ONCE, calendar doesn’t popup, but cell does become active - incorrect. Calendar should open here.
![image](https://github.com/infor-design/enterprise/assets/45044406/616561bf-3543-438a-a1f2-7621af5a5fe0)

Click calendar button TWICE, calendar appears - correct, but should've opened on the first click
![image](https://github.com/infor-design/enterprise/assets/45044406/b95e4f88-3cde-4291-b893-5a06775db6d4)

Click a date, calendar closes, but box is left in edit mode (cursor not shown, but it's there) - incorrect. Should have exited edit mode here.  cellChange event is not fired, which is not correct.
![image](https://github.com/infor-design/enterprise/assets/45044406/30384fe0-34e3-4113-a4c7-475c9c14472c)

**Platform**
 - Infor CSD / Concierge Team
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: Version 126.0.6478.63 (Official Build) (64-bit)

**Additional context**
HTML
```
<div class="full-width">
      <div id="testGrid" name="testGrid" soho-datagrid *ngIf="gridOptions" [gridOptions]="gridOptions" [dataset]="maintenanceCalendarData" 
      (cellchange)="onCellChange($event)"
      class="datagrid"></div>
  </div>

```
Columns
```
    this.maintenanceCalendarColumns = [
      {
        id: 'monthMinus1Date',
        name: 'Hello world',
        field: '',
        editor: Soho.Editors.Date,
        formatter: Soho.Formatters.Date,
      },
    ];

```

Options
  ```
  this.gridOptions = {
      columns: this.maintenanceCalendarColumns,
      dataset: this.maintenanceCalendarData,
      stretchColumnOnChange: false,
      paging: true,
      pagesize: 10,
      showPageSizeSelector: true,
      idProperty: 'productId',
      editable: true,
      rowHeight: 'small',
      filterable: true,
      filterWhenTyping: true,
      toolbar: {title: 'Product Maintenance Calendar', filterRow: true, results: true, dateFilter: false ,keywordFilter: false, actions: true, views: false, rowHeight: true, collapsibleFilter: false},
    };

```
The only event handler
```
onCellChange(e: any) {
    console.log("onCellChange", e);
}
```

**Comment by tmcconechy** [comment]
Testing on https://main-enterprise.demo.design.infor.com/components/datagrid/example-editable.html

1. I dont see it i can click the order date column and go straight in  to edit mode
2. I do see this when you click the calendar the cursor stays in the field. This is what you mean right?
![Screenshot 2024-06-27 at 4 49 47 PM](https://github.com/infor-design/enterprise/assets/814283/56fef437-39b1-48d4-ab4e-b0fa7618c3b4)

3. I dont see it editing the date cell shows cellchange in the console

**Comment by mlick27** [comment]
Upgrading to 17.8.0 fixed the issue. None of these problems exist anymore. Closing the issue.
