### ISSUE TITLE
TabsModule: Menu icon is not visible

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8863]
**Describe the bug**
Menu icon is not visible in New - Light Mode.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-module/example-sortable.html?
2. Notice the `Menu` icon on the left side of the tabs

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/102151352/19f4f902-9c7d-4a89-b7ba-aabd0bb27e20)

![image](https://github.com/infor-design/enterprise/assets/102151352/7be69ec0-dff6-43f4-ba98-21c839e96724)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
This has been fixed on a previous PR. Please test it out?

**Comment by jbrcna** [comment]
can confirm
<img width="765" alt="image" src="https://github.com/infor-design/enterprise/assets/56722184/94c06879-9423-40ee-b8ff-534ae8999cc9">
