### ISSUE TITLE
Datagrid: Add selectOnEdit setting for inline editor

### ISSUE THREAD

**Issue by rcoseng** [infor-design/enterprise#8870]
**Describe the bug**
On 1st click in the inline editor, the text is highlighted (expected)
On succeeding clicks in between characters, the cursor moves and then is highlighted.
When trying to drag to select only a set of characters, the whole text is highlighted on release of mouse.

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/datagrid/test-editable-with-inline-editor.html
2. Click on inline editor "Repair"
3. Click in between "R" and "e" (cursor should be in between)
4. Click in between "a" and "i"
5. See text highlight behavior
6. Click in between "R" and "e" (cursor should be in between)
7. Drag to select "epai" only
8. Notice the whole text is selected

**Expected behavior**
On clicks after the first, the cursor is moved in between characters. 
When dragging to select a set of characters, the whole text is not highlighted on release.

**Version**

- ids-enterprise: 4.95

**Screenshots**

https://github.com/infor-design/enterprise/assets/120151603/f7b1c4e2-8d5c-43d7-9929-e67ac1204577

**Additional context**
see linked comment for `selectOnEdit` suggestion:
https://github.com/infor-design/enterprise/issues/8763#issuecomment-2195120378

**Comment by tmcconechy** [comment]
Seems to still be a bug on https://main-enterprise.demo.design.infor.com/components/datagrid/test-editable-with-inline-editor.html
