### ISSUE TITLE
Drag Component: X Only and Left drag example overlaps the title of the example

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#888]
**Describe the bug**
MAC Chrome: Drag Component: X Only and Left drag example overlaps the title of the example

**To Reproduce**
1. Go to url: http://4110-beta1-enterprise.demo.design.infor.com/components/drag/example-index.html
2. Move "X Only" to the right and then back to the left
3. Move "Left" to the right and then back to the left
4. Both drag's features overlaps the title text of the example
5. Please see screens shot attached

**Expected behavior**
Should not overlap the text from the title

**Screenshots**
![drag component](https://user-images.githubusercontent.com/39101346/46311685-ffa89180-c590-11e8-965b-e7266d0670c7.png)

**Platform**
- MAC- Chrome Browser 

**Additional context**
None

**Comment by tmcconechy** [comment]
This example could use a bit of cleanup.
