### ISSUE TITLE
Datepicker: when configured to also show time does not display current time

### ISSUE THREAD

**Issue by fitzorama** [infor-design/enterprise#889]
**Describe the bug**
When the Datepicker is configured to also show time, the time picker does not display the current time. This is also evident when the 't' shortcut is used to display the current day.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html
2. For the Time and Date field, click on the Datepicker icon to display the calendar
3. The time picker parts display 12:00:00 AM instead of the current time
4. Dismiss the calendar
5. Enter a t into the Time and Date field to display the current date
6. The time parts display as 12:00:00 AM

**Expected behavior**
Expect the time parts to display the current time.

**Screenshots**
![datepicker with show time](https://user-images.githubusercontent.com/20212079/46312211-07186c80-c58a-11e8-8ac2-a43e01591f7e.gif)

**Platform**
All

**Additional context**

**Comment by tmcconechy** [comment]
I suggest should maybe make this a setting. setTimeToNoon or something.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datepicker/example-timeformat.html
Encountered an issue. Clicking "Today" after you changed the values on the time picker doesn't set the time to current time, instead, it applies the values on the time picker.

Steps:
1. Open the date picker on the "Date-Time Picker in Locale (Time to Current)"
2. Select 1:00 AM on the time picker
3. Click "Today" button
4. Issue will happen, values on the time picker (1:00 AM) will be applied, not the current time.

**Comment by tmcconechy** [comment]
Actually thats the way i made it work on purpose. It was kind of a funny case, but this way you can pick a different time on today and apply it to the field. I think it is ok? Do you think it's really wrong?

**Comment by brianjuan** [comment]
I think the "Today" button can be confusing to set both the date and time to current when clicked. 

And if ever we change the functionality to always set the time to current when Today button was clicked, we still have way to pick different time since the values in the field are dynamically changing as you select time in the time picker. Just my opinion.

**Comment by tmcconechy** [comment]
OK, lets make a new minor enhancement for that. I guess it is a bit strange, we can just change the behavior to always insert currentTime or midnight on click of the today button.

**Comment by brianjuan** [comment]
Thanks @tmcconechy , will now move this to Done, then test #1087 once fixed.
