### ISSUE TITLE
Dropdown: The class value "dropdown-wrapper " has an extra blank space in the end

### ISSUE THREAD

**Issue by InforBG** [infor-design/enterprise#8894]
**Describe the bug**
In IDS 4.95.x, the class value "dropdown-wrapper " has an extra blank space in the end. IDS 4.93.0 doesn't have this problem.
We are using XPATH to locate the web element for Automation tests. For example, the XPATH is `"./following-sibling::div
[./@class='dropdown-wrapper']/div[not(contains(./@style, 'display: none;'))][1]"`.
In IDS 4.95.x or 4.96.0, the XPATH becomes invalid.
Is it a design change or bug to have the extra blank space in the end?

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/dropdown/example-clearable?theme=uplift&variant=light&layout=embedded
2. Look at the HTML elements
3. See the class value as the screenshot below

**Expected behavior**
The class value don't have the useless space in the end. It should be just `"dropdown-wrapper"`.

**Version**

- ids-enterprise: [e.g. v4.95.0 or v4.96.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/114138479/cc1e95e1-c012-40bd-9429-f74787cb580a)

**Platform**
 - Infor Application/Team Name: [Infor SunSystems]
 - OS Version: [Windows 11]
 - Browser Name: [chrome]
 - Browser Version: [126.0.6478.127 (Official Build) (64-bit)]

**Comment by tmcconechy** [comment]
@InforBG we can get rid of the space. But that being said i never recommend xpath

**Comment by InforBG** [comment]
Thanks, @tmcconechy .
We are using Selenium for the automation tests.
Which technology will you recommend to locate the element?
For example, to use the xpath `"./following-sibling::div [./@class='dropdown-wrapper']/div[not(contains(./@style, 'display: none;'))][1]"`,
1. we get the 'select' element by ID;
2. get the next sibling which has the class value 'dropdown-wrapper'; then get the visible child element.

If we don't use the xpath, what will you recommend? Thanks for any advices.

**Comment by tmcconechy** [comment]
@InforBG we will update this for you as the space isnt needed but i usually suggest css selectors in whatever tool im using.

Maybe https://www.browserstack.com/guide/css-selectors-in-selenium#:~:text=CSS%20(Cascading%20Style%20Sheets)%20Selectors,faster%20as%20compared%20to%20XPath. 

So then select by class instead and it could ignore the space?

**Comment by InforBG** [comment]
Thanks for update this.

The CSS locator in Selenium seems to have limitations. It is better than the other locators when locate web elements based on their id, class, name, attributes.
While the XPath locator can handle more complicated scenarios. For example, we have one known element. Use xpath to get the next sibling's first visible child. Or get a grid's parent element and some elements within it. CSS couldn't do it easily in my understanding.

**Comment by tmcconechy** [comment]
OK @InforBG i dont use selenium directly we use Playwright so cant 100% help but i know that xPaths have in the past caused issues. Will get a fix for the extra space
