### ISSUE TITLE
Switch: Click label doesn't change value.

### ISSUE THREAD

**Issue by InforBG** [infor-design/enterprise#8896]
**Describe the bug**
The behavior of Switch component is changed in IDS 4.96.x+. Click label doesn't change value. Is it a design change or bug ?
In IDS 4.95.x, click label does change the value.

**To Reproduce**

1. Go to IDS 4.95.0 example, https://latest-enterprise.demo.design.infor.com/components/switch/example-alignment.html, click label works.
2. Go to IDS 4.97.0 exmaple, https://main-enterprise.demo.design.infor.com/components/switch/example-alignment.html, click label doesn't work.

**Expected behavior**
For the switch component, click label should change the value.

**Version**

- ids-enterprise: [v4.96.0 or v4.97.0]

**Screenshots**
![image](https://github.com/infor-design/enterprise/assets/114138479/a025ef3d-f8b3-475f-beb5-2d5d5ac9325e)
In IDS 4.95.0 example, when hover on the label, the mouse is a 'hand' icon, not an 'arrow'.

**Platform**
 - Infor Application/Team Name: [Infor SunSystems]
 - OS Version: [Windows 11]
 - Browser Name: [chrome]
 - Browser Version: [Version 126.0.6478.127 (Official Build) (64-bit)]

**Comment by tmcconechy** [comment]
@jdilag90 can you take a look?

**Comment by InforBG** [comment]
Can the fix be included in IDS 4.97.x patch, if it is solvable? Thanks.

**Comment by tmcconechy** [comment]
@InforBG I patched this fix in:

https://github.com/infor-design/enterprise/releases/tag/4.97.3

**Comment by InforBG** [comment]
Thanks, @tmcconechy .
