### ISSUE TITLE
DataGrid: Selection (Single) Example - Checkbox selects not working to select row

### ISSUE THREAD

**Issue by JoelWilke** [infor-design/enterprise#8903]
**Describe the bug**
The example of the [Single Selection DataGrid](https://latest-enterprise.demo.design.infor.com/components/datagrid/example-singleselect?theme=uplift&variant=light&layout=embedded) does not allow a user to select/check the checkboxes when the user selects the row itself, or the checkbox by clicking on it/them.

**To Reproduce**

1. Go to ['example-singleselect'](https://latest-enterprise.demo.design.infor.com/components/datagrid/example-singleselect?theme=uplift&variant=light&layout=embedded)
2. Select/click on any checkbox in the right column or click on any row
3. See that the checkboxes are unable to be checked/selected nor does the cursor display correctly as a selectable option

**Expected behavior**
I expect the checkboxes to display a checkmark when the row is clicked and when the checkbox itself is clicked. In both cases the row should display as selected.
When another row or checkbox is selected, the first will display as unselected/lose focus, and the new, current row will display as selected as well as the checkbox.

**Version**

- ids-enterprise: data-sohoxi-version="4.95.0"

**Screenshots**
![Screenshot 2024-07-16 at 12 14 35 PM](https://github.com/user-attachments/assets/faa4ede5-c38a-4136-b9f4-d6630f4072b0)

**Platform**
 - OS Version: Mac OS 14.5 Sonoma
 - Browser Name: Chrome and Safari

**Additional context**

I am using this data-grid version as the basis for bug tickets for the Landmark version to use as an example of how the single select should function.

**Comment by tmcconechy** [comment]
@JoelWilke This example is misleading as that checkbox is a normal checkbox not a selection checkbox.

If you wanted a checkbox for single select use the radio selection checkbox as per this example 

https://latest-enterprise.demo.design.infor.com/components/datagrid/test-selection-radio-button.html

Source: https://github.com/infor-design/enterprise/blob/main/app/views/components/datagrid/test-selection-radio-button.html#L32

I think we should remove the checkbox from this example to avoid confusion so did so here: https://github.com/infor-design/enterprise/commit/5cd5704409f5824daec01f76bffc35947e8a1c9a
