### ISSUE TITLE
Datagrid: "NaN.NaN.NaN" date format in using dot separator instead of default value (i.e: 'N/A').

### ISSUE THREAD

**Issue by CristianCosta** [infor-design/enterprise#891]
**Describe the bug**
On datagrids, the date fields shows NaN.NaN.NaN value when the dot separator ('.') is establish instead of slash separator ('/'). In the following JsFiddle you can see the commented behavior https://jsfiddle.net/ccosta/31Lqa29r/

**To Reproduce**
1. Establish a default value such as 'N/A' to denote a missing date. 
2. Change the browser language in order to have a dot notation for date formatting (i.e: de-DE).
3. See error on datagrid date field.

**Expected behavior**
Instead of show NaN.NaN.NaN value, the date field must show the default value established previously (N/A).

**Platform**
 - Browser Name: Chrome, Firefox

**Additional context**
 - **Soho XI version: Soho XI Controls v4.3.2 - Date: 19/09/2017 3:05:43 PM - Revision: fea06c42e1f23e7b5ef6e088b093e76578822c3d**
- The issue happens on _Date_ function inside _sohoxi.js_ (line number ~15000). After execute the method _Locale.formatDate_, the result is 'NaN.NaN.NaN'. Immediately, there is a condition who ask if the returned format value is equals to 'NaN/NaN/NaN'. The condition evaluates false so, under that condition it won't never assign the default value ('N/A').

**Comment by CristianCosta** [comment]
Hi Tim! How are you? That fix related to #249 was applied over **Integer** and **Decimal** formatters. The issue that I'm reporting is related to **Date** formatter. So when I test it again the error still happening.

I've take a look into master code into **Date** formatter and I see this:

`if (formatted === 'NaN/NaN/NaN') { // show invalid dates not NA/NA/NA`
`formatted = value;`
`}`

It doesn't take care about the formatted value were equals to 'NaN.NaN.NaN'.
If you need something else, just tell me.

**Comment by tmcconechy** [comment]
I see, ok thanks. Changing this to an active bug

**Comment by CristianCosta** [comment]
Thanks Tim. Regards.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-accept-default-date-value.html
http://master-enterprise.demo.design.infor.com/components/datagrid/test-accept-default-date-value.html
Passed QA testing across all browsers, datagrid shows default N/A value in date column.
