### ISSUE TITLE
Tabs: Uncaught TypeError: this.focusState is undefined

### ISSUE THREAD

**Issue by adamzhang1932** [infor-design/enterprise#8910]
**Describe the bug**
![image](https://github.com/user-attachments/assets/7cdb0b2e-9c1d-4648-ba48-66c204b264ac)

**To Reproduce**
[blockgrid-index.zip](https://github.com/user-attachments/files/16331156/blockgrid-index.zip)
Download this zip file and unzip it, put the file to `app/views/components/tabs/blockgrid-index.html`

1.npm run start
2.Visit:
http://localhost:4000/components/tabs/blockgrid-index.html
3.Click the 'Application1' grid and you can see the error on the console.

**Expected behavior**

**Version**

- ids-enterprise: v4.97.3

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor SunSystems
 - Device: 
 - OS Version:Windows 11
 - Browser Name: firefox/chrome
 - Browser Version: 

**Additional context**
Similar to https://github.com/infor-design/enterprise/issues/8419

**Comment by adamzhang1932** [comment]
Hi @tmcconechy 
We are trying to upgrade IDS to v4.97.3, is it possible to provide one patch like v4.97.4 to fix this issue?

Regards,
Adam

**Comment by tmcconechy** [comment]
@adamzhang1932 yes once its fixed we can do a patch. We have this is high priority but may not get to it until next sprint. If you see the issue is fixed and the patch takes a short while, just remind me and i'll make it

**Comment by adamzhang1932** [comment]
Hi @tmcconechy, this issue had been closed several days ago, is it possible to add patch for it to 4.97.x and 4.98.x?

**Comment by tmcconechy** [comment]
Hi @adamzhang1932 I made the patches:

[v4.98.1](https://github.com/infor-design/enterprise/releases/tag/4.98.1)
[v4.97.4](https://github.com/infor-design/enterprise/releases/tag/4.97.4)

Unclear if you need the angular side of them. If so can you let me know the versions you last used? (if not i can find them but...)

**Comment by adamzhang1932** [comment]
@tmcconechy Many thanks to you!
We are using java GWT and we don't use AngularJS.
