### ISSUE TITLE
ColumnChart: Selected event issue in column grouped chart

### ISSUE THREAD

**Issue by aishanyagupta** [infor-design/enterprise#8916]
In column grouped chart while clicking on bar of the chart and printing event value.
two different values are coming alternatively.

Steps to reproduce
1. Go to [Link](https://main-enterprise.demo.design.infor.com/components/column-grouped/example-selected.html)
2. Right click on the on the widget and scroll down to inspect and click on it.
<img width="899" alt="image" src="https://github.com/user-attachments/assets/0bd05593-f89c-4ead-8577-4a7a0a273c5d">
3. Navigate to console tab, and click on various bars of the chart as well as the bottom legends.

Here is a screen recorded video for easy understanding.
[screen-capture (9).webm](https://github.com/user-attachments/assets/5fa58972-dbd6-4c47-8dff-91219f44ef76)

The expected behavior is to get the same value every time we click on the bar.

ids-enterprise-ng: 4.95.0-dev.0

**Comment by ericangeles** [comment]
@tmcconechy, have you confirmed this one? I still don't quite understand it.

**Comment by tmcconechy** [comment]
@ericangeles yeah i dont get it, it looked like from the video that some of the data was obviously wrong in the console.
Not when clicking a group you select the whole group not the bar. And i dont get the part about right clicking? But trying it i dont see any issues

![Screenshot 2024-08-19 at 10 26 18 AM](https://github.com/user-attachments/assets/842f0998-c811-4174-9bab-224029014226)

 @aishanyagupta can you update the steps? the data looks ok to me. maybe your looking at a wrong place in the event data?

**Comment by aishanyagupta** [comment]
Hi @tmcconechy,

This data is when we click first and a group is selected then
![image](https://github.com/user-attachments/assets/91c0d274-f564-4aa5-ad6d-dba3f525ad37)
next time when we click we are getting console is showing this value
![image](https://github.com/user-attachments/assets/c3a303d1-28d4-493f-916c-b09f6753c1b7)
overall on multiple clicks of a single bar, this is how response is
![image](https://github.com/user-attachments/assets/fd3d0d65-26d6-4cab-8a33-c34ddcf1feee)
Two different values are coming alternatively.


but, the case I am looking for is when we click on a bar in column grouped chart, I want to find which group it belongs to and also which bar in that group.

here is a screen recorded video
[screen-capture (11).webm](https://github.com/user-attachments/assets/9b0ef988-b3ff-4822-a56c-5bd6619d14a2)

Please let me know if any further queries required.

Thanks

**Comment by yohannahbautista** [comment]
Hello, here's my observations on the 'selected' events happening:

### On selecting Component B (first)
- Selected element is the Component B group itself
- The data sent is the array of bar elements and its data 
<img width="1281" alt="image" src="https://github.com/user-attachments/assets/28e6c585-b49a-4754-b76a-c4f288e773ad">
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/fd849026-ff60-4159-bfea-b58c7412b136">

On selecting Component B again

**Comment by aishanyagupta** [comment]
Hi @yohannahbautista,
The requirement is when we click anywhere on chart we need to know which group it belongs to as well as which bar in that group.
I need bar data in the group.

**Comment by yohannahbautista** [comment]
> Hi @yohannahbautista, The requirement is when we click anywhere on chart we need to know which group it belongs to as well as which bar in that group. I need to know which bar is selected in that group.

@aishanyagupta Would having the index in the data be enough? Maybe something called the childIndex?

**Comment by aishanyagupta** [comment]
> > Hi @yohannahbautista, The requirement is when we click anywhere on chart we need to know which group it belongs to as well as which bar in that group. I need to know which bar is selected in that group.
> 
> @aishanyagupta Would having the index in the data be enough? Maybe something called the childIndex?

@yohannahbautista yes, that will be enough, Thanks

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4045
