### ISSUE TITLE
Notification Banner: Cannot interact with the Page Header unless all notifications were dismissed

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#892]
**Describe the bug**
Notification Banner: Cannot interact with the Page Header unless all notifications were dismissed.

**To Reproduce**
1. Go to http://4110-beta1-enterprise.demo.design.infor.com/components/notification/example-index.html
2. Click the Search icon or ... Menu icon, nothing happens
3. Dismiss all the notifications by clicking their X button on the right side
4. Click the Search icon or ... Menu icon again, they should work this time

**Expected behavior**
Page header controls should work whether the notifications were dismissed or not

**Screenshots**
![notifbanner1](https://user-images.githubusercontent.com/39508864/46332021-14e2f600-c64d-11e8-86ed-567336eff1f3.gif)

**Platform**
 - All devices, OS and browsers.

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This issue should have been closed
