### ISSUE TITLE
Datagrid: Drag icon is not working

### ISSUE THREAD

**Issue by glenlieorillo** [infor-design/enterprise#8920]
**Describe the bug**
The drag icon is not working.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/datagrid/example-index.html
2. Click on ellipses (...) above the table
3. Try to drag the items by click and hold the drag icon

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
![image](https://github.com/user-attachments/assets/937c40a5-c90a-4ad0-b5a5-733c5dd1b9d6)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@yohannahbautista i think this used to work recently. Could you check?

**Comment by tmcconechy** [comment]
Found this was just an example issue as it was not turned on. Fixed for that example now on attached PR
