### ISSUE TITLE
MenuButton: Button is cut off intermittently in Safari (4.98 beta)

### ISSUE THREAD

**Issue by n-ace-ancog** [infor-design/enterprise#8925]
**Describe the bug**
When loading the menu button in Safari, it may be cut off.

**To Reproduce**

1. Open Safari
2. Go to https://4980-enterprise.demo.design.infor.com/components/button/example-menubutton.html
3. If the button is not cut off, reload
4. See issue

**Expected behavior**

**Version**

- ids-enterprise: 4.98 Beta

**Screenshots**

https://github.com/user-attachments/assets/aa626a3e-dcd8-4b26-8081-eb3dcc6af766

**Platform**
 - OS Version: Mac OS Sonoma Version 14.5
 - Browser Name: Safari
 - Browser Version: Version 17.5 (19618.2.12.11.6)

**Comment by tmcconechy** [comment]
Seems like just that example. Not so sure why but it was there before. Tried looking and could not see why.
Will fix later.
