### ISSUE TITLE
Date: error validation not working - BETA 4.98

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8930]
**Describe the bug**

**To Reproduce**

1. Go to 'https://4980-enterprise.demo.design.infor.com/
2. Move to Date Input - Error Handling
3. Type 12/31/23

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="433" alt="image" src="https://github.com/user-attachments/assets/fee819d4-88af-44f9-add5-232b5fc6ebc0">

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**
the error only appear when you input 3 digit in year

**Comment by tmcconechy** [comment]
@jbrcna actually that date is valid because we allow two digit years. Try `12/31/2` for the test

**Comment by jbrcna** [comment]
noted @tmcconechy . thanks for clarifying
