### ISSUE TITLE
Tabs: Extra line shown (4.98 beta)

### ISSUE THREAD

**Issue by jbrcna** [infor-design/enterprise#8932]
**Describe the bug**
 extra line is shown when the last item is selected then you click the tab more button

**To Reproduce**

1. Go to https://4980-enterprise.demo.design.infor.com/
2. Move to tabs
3. Select the last item 
4. Click icon-more (down arrow)
5. See error

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**
<img width="464" alt="image" src="https://github.com/user-attachments/assets/3229807f-5a24-474d-a2cd-26945d2d04b0">

**Platform**
mobile

**Additional context**

**Comment by tmcconechy** [comment]
https://inforwiki.atlassian.net/browse/IDS-4863

**Comment by roiangeloseminiano** [comment]
Hi @tmcconechy, seems this issue was already fixed by this PR [9012](https://github.com/infor-design/enterprise/pull/9012). This was an issue maybe because that the branch being used in the given link (https://4980-enterprise.demo.design.infor.com/) was outdated.

**Comment by tmcconechy** [comment]
Issue was fixed previously and can no longer see this on  https://main-enterprise.demo.design.infor.com/

**Comment by jbrcna** [comment]
can confirm. v4.99.0
https://main-enterprise.demo.design.infor.com
<img width="471" alt="image" src="https://github.com/user-attachments/assets/ef62564f-3dce-43ad-8a9f-8ce5812016ed">
