### ISSUE TITLE
Datagrid: Column filter allows non-numeric input for filterType integer 

### ISSUE THREAD

**Issue by s-werking** [infor-design/enterprise#8934]
**Describe the bug**
Users can enter non-numeric values in a column filter for a column with filterType: 'integer'.

**To Reproduce**
1. Go to http://localhost:4000/components/datagrid/test-ellipsis.html
2. Click inside the Qty column filter
3. Type a non-numeric value

**Expected behavior**
Column filters with the filterType: 'integer' should not allow non-numeric entries.

**Version**

- ids-enterprise: v4.95.0-dev.0

**Screenshots**
![image](https://github.com/user-attachments/assets/b3d54abf-d47e-4a67-9afd-e873fb52e83c)

**Platform**
 - Infor Application/Team Name: lawson
 - OS Version: Windows 11
 - Browser Name: chrome
 - Browser Version: 127.0.6533.73 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
@s-werking try adding a mask to the column config for that column for example `mask: '###'` i think it picks it up for the filter row?

**Comment by tmcconechy** [comment]
@s-werking going to close this issue as long as you say it works with the mask. I can't seem to do it automatically as we dont know how big of an integer to user is unless you specify it

**Comment by s-werking** [comment]
That works for me. Thanks for looking into this @tmcconechy
