### ISSUE TITLE
Date picker is picking the next month after focusing out of field

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#8937]
**Describe the bug**
If I type "April" into date picker. It will switch to "May" after focusing off of the field.

**To Reproduce**

1. Go to http://localhost:4000/components/datepicker/example-month-year-format.html
2. Type "April" into the Month Picker (Long) field.
3. Click out of field
4. Value changes to "May"

**Expected behavior**
Value should not change

**Version**

4.95.5

**Screenshots**
![date-picker-bug](https://github.com/user-attachments/assets/bc83449e-39ee-40be-a657-bbbd12f644cc)

**Platform**
 - Windows 11
 - Chrome (latest) 127.0.6533.88

**Comment by yohannahbautista** [comment]
Hello, checking on the issue, the bug doesn't seem to appear anymore: https://main-enterprise.demo.design.infor.com/components/datepicker/example-month-year-format.html
