### ISSUE TITLE
Datagrid: Date picker in range selected issue in data grid filter.

### ISSUE THREAD

**Issue by manonshen** [infor-design/enterprise#8940]
**Describe the bug**
My work project ids ng version is 18.0.2 and demo case ids version is 18.1.3,  in my data grid, I have a date picker filter. 
the filter condition includes in-range, less than, greater than, and I set it to first position.
when switching to less than or greater than from in range. note it is still selecting range?

I have a demo for it.  [demo issue.zip](https://github.com/user-attachments/files/16458080/demo.issue.zip)

Note:
To solve the issue, I adjusted in range to the last position, which can solve most problems, but also had another problem.
1. When I selected in range operator and selected a time range(the time range was saved to local storage), 
2. Then I switched to other functions, 
3. But when I switched back to the before page, the previous time range could be filled correctly, but clicked the date picker, and discovered that both times can not be selected.
I think it is the same issue as before mentioned, right? time range selected issue?

**To Reproduce**

1. Open datagrid page, check the time filter,  in range is selected
2. Open the date picker and select a range.
3. Switch to less than or greater than
4. Open the date picker and note it is still selecting range?
```
this.columns.push({
      id: 'orderDate',
      name: 'Order Date',
      field: 'orderDate',
      formatter: Soho.Formatters.Date,
      dateFormat: 'M/d/yyyy',
      filterType: 'date',
      filterConditions: [
        'in-range',
        'less-than',
        'less-equals',
        'greater-than',
        'greater-equals',
      ],
    });
  }
```
**Expected behavior**
Switch different time operator, time picker can work normally. 

**Version**

- ids-enterprise: 18.0.2-18.1.3

**Screenshots**

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-5174
