### ISSUE TITLE
Autocomplete: List is not scrolling when using up/down arrows to navigate

### ISSUE THREAD

**Issue by aaronpikkarainen** [infor-design/enterprise#8943]
**Describe the bug**
The Autocomplete list is not scrolling when you use the up/down arrow keys to browse a long list. It should scroll automatically so the highlighted item is visible.

**To Reproduce**
1. Go to https://latest-enterprise.demo.design.infor.com/components/autocomplete/example-contains.html
2. Type 'a' into the field and see a long scrollable list appear.
3. Use the down arrow to navigate down the list.
4. Notice that the highlighted item is not visible once you get too far down a scrollable list.

**Expected behavior**
The list should scroll automatically in this scenario so the user can see which item is highlighted. This used to work properly in older versions. Compare to the dropdown control, which scrolls automatically so the highlighted item is always visible.

**Important**
When fixing this issue, please make sure the change does not break the recent fix for https://github.com/infor-design/enterprise/issues/8618

**Version**
- ids-enterprise: v4.98.0

**Screenshots**
![image](https://github.com/user-attachments/assets/b7f8ec3f-d8c9-4f4e-8e4f-90883ff3cecb)

**Platform**
 - Infor Application/Team Name: CSD
 - Device: Dell laptop
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 127.0.6533.89 (Official Build) (64-bit)

**Comment by aaronpikkarainen** [comment]
Thank you all. I found that it is partially working, but there is a negative side effect with the fix. In certain cases, the up/down arrows stop moving the highlighted selection properly. You can see it at the below example with the following steps:

1. Go to https://main-enterprise.demo.design.infor.com/components/autocomplete/example-contains.html
2. Type 'a' into the autocomplete field.
3. WAIT for the results to display.
4. Then type 'r' into the field (so you now have 'ar').
5. Arrow down several times and notice that it gets stuck after 3 down arrows. You can no longer move the selection down. If you try to arrow up at this point it jumps to the first item in the list and won't go farther.

Can you take a look? @tjamesallen15 @tmcconechy

**Comment by tmcconechy** [comment]
@AAlviar Can we add this issue as well to Jira it was reponed
