### ISSUE TITLE
ListView: Compact 

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#8959]
**Is your feature request related to a problem or use case? Please describe.**
There is some padding around the list item that could be reduced if the control was within the class 'form-layout-compact'. If this was reduced then more items could be displayed within the list.

**Describe the solution you'd like**
Use the "form-layout-compact" class to display a more compact version of the listview.

**Describe alternatives you've considered**
Creating custom CSS to target these controls.

**Additional context**
And what application do you work on? [Infor Pathway]

**Comment by ericangeles** [comment]
Could you provide an example page for this issue? (perhaps your use case or in our example page?)

**Comment by tmcconechy** [comment]
@ericangeles i see this similar to https://github.com/infor-design/enterprise/pull/8961 but in this case we reduce the padding based on `form-compact` classes.

I.E. add list view to https://main-enterprise.demo.design.infor.com/components/form/example-compact-mode.html
