### ISSUE TITLE
Locale: Incorrect "Small" and "Extra Small" translations in Spanish 

### ISSUE THREAD

**Issue by cpinatel7** [infor-design/enterprise#8962]
Locale: Incorrect "Small" and "Extra Small" translations in Spanish

![image](https://github.com/user-attachments/assets/3d61093b-a2c4-4eba-aee3-b83f7d4ed7ac)

**Comment by cpinatel7** [comment]
Please assign this bug to Henry. Thanks

**Comment by tmcconechy** [comment]
cc @hwondergem

**Comment by hwondergem** [comment]
Hi @tmcconechy, 
Corrections available in the updated resource file,
\\nlbavwmemoq2\cc\ToDev\SohoUX\es-ES-messages.json	68,610	08/19/2024 11:57
