### ISSUE TITLE
Homepage: Incorrect height when empty

### ISSUE THREAD

**Issue by radovaniljic** [infor-design/enterprise#8972]
**Describe the bug**
In browser windows that have a `height` of max `1250px`, the `Homepage` component pretty much takes up 100% of the window height. This becomes a problem when there's content above or below the homepage (a hero widget on the page is probably the most common), because it causes the page to unnecessarily overflow.

Caused by [this CSS rule](https://github.com/infor-design/enterprise/blob/b96b952763220be77fc6e751063bf813441ea44a/src/components/homepage/_homepage.scss#L562-L566) which was added [in this commit](https://github.com/infor-design/enterprise/commit/fd3c6a44ab5cc023843236f64c2eefb8d733ce68#diff-c64ff7d754d29ef30af42ea450255f1267a66c58eb2ae9b4fef121797c7779d1R481-R486)

**To Reproduce**
1. Go to https://stackblitz.com/edit/ids-enterprise-4980-f2ajcn?file=index.js,index.html
2. Reduce the height of the browser window if it's greater than `1250px`, 
3. Notice the scrollbar

**Expected behavior**
Shouldn't unnecessarily cause overflow. I think an empty `Homepage` used to not have a height at all. 

**Version**
- ids-enterprise: Introduced in `4.94`

**Platform**
 - Infor Application/Team Name: OS Portal

**Comment by tmcconechy** [comment]
I think the height was added so the new color background covers it

**Comment by tmcconechy** [comment]
https://inforwiki.atlassian.net/browse/IDS-4867

**Comment by roiangeloseminiano** [comment]
Hi @tmcconechy and @radovaniljic,

Upon investigation, the height of the homepage is determined as stated below

First is the line 564 where height is being calculated when page height is **< 1250** 
<img width="504" alt="image" src="https://github.com/user-attachments/assets/b87477fa-de50-4a0d-b50a-059f37f3de86">

If the line 564 is temporarily removed the line 13 will take effect 
<img width="480" alt="image" src="https://github.com/user-attachments/assets/40b4ebd5-3738-412f-b3a9-1748b648ca16">

It will inherit the parent height from the page-content class css thus having height of 100% 

Can please advise on how we will fix this issue?

**Comment by tmcconechy** [comment]
@tjamesallen15 seems you added it here https://github.com/infor-design/enterprise/pull/8544
Is there either a way you can revert that and still have the fix.

cc @roiangeloseminiano -> check with @tjamesallen15 either we revert that or make a rule that will set the height to auto if empty? maybe the empty rule? https://developer.mozilla.org/en-US/docs/Web/CSS/:empty

We will need to confirm https://github.com/infor-design/enterprise/pull/8544 is still fixed.

**Comment by tmcconechy** [comment]
Fixed as per https://oxford.awsdev.infor.com/infor-design/enterprise/-/merge_requests/29
