### ISSUE TITLE
Datagrid, lookupfield doesn't span width of column

### ISSUE THREAD

**Issue by krishollenbeck** [infor-design/enterprise#8974]
**Describe the bug**
Lookupfield doesn't span width of column. This use to work prior to this change.
https://github.com/infor-design/enterprise/commit/8f359c934c476f4a35aba0c2daae4815fc9cc149

**To Reproduce**

1. Go to http://localhost:4000/components/datagrid/test-filter-align.html
2. See issue "product id" column

**Expected behavior**

**Version**

- ids-enterprise: 4.96.0

**Screenshots**

**Before**
<img width="688" alt="before" src="https://github.com/user-attachments/assets/69f6b70b-96e4-4195-881a-824933000238">

**After**
<img width="685" alt="after" src="https://github.com/user-attachments/assets/de9d2f3c-280f-4834-bcc6-ab9f20e7f307">

**Platform**
 - Chrome
 - Windows 11

**Comment by tmcconechy** [comment]
@krishollenbeck this is fixed recently it was already raised https://github.com/infor-design/enterprise/issues/8900

**Comment by krishollenbeck** [comment]
@tmcconechy Thanks for letting me know. I was not aware of the other ticket.
