### ISSUE TITLE
Calendar: 'Upcoming' events in the Calendar show sessions with class dates that are not within the selected calendar date

### ISSUE THREAD

**Issue by allanalvarez** [infor-design/enterprise#8975]
**Describe the bug**
'Upcoming' events in the Calendar show sessions with class dates that are not within the selected calendar date

**To Reproduce**

1. Go to advance Month (November 25, 2024)
2. Create a data that is less than the month of November
3. Notice the newly created data will display in the Upcoming event

**Expected behavior**
The date is not within the date range of the selected calendar month. The data should display within the range of selected calendar month.

**Version**

IDS Enterprise Components - v4.90.0

**Screenshots**
See attached video

https://github.com/user-attachments/assets/1e7fba00-b346-4e77-8f2f-e3b5523e2ce4

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
@allanalvarez can we

a) test the latest version
b) simplify the steps to reproduce down from a 2 minute video  in written form?
c) make a reduced test case so its not just in the app and / or reproduce it in our examples?

**Comment by tmcconechy** [comment]
Closed as per https://inforwiki.atlassian.net/browse/IDS-4865
