### ISSUE TITLE
Datagrid: Contextual Toolbar button colors

### ISSUE THREAD

**Issue by anhallbe** [infor-design/enterprise#8980]
**Describe the bug**
Buttons in the `.contextual-toolbar` that are **not primary** gets the wrong colors when hovered and disabled.

**To Reproduce**

1. Serve the ids-enterprise-ng samples
2. Go to http://localhost:4200/ids-enterprise-ng-demo/listview or http://localhost:4200/ids-enterprise-ng-demo/datagrid-mixed-selection
3. Select an item in the list/datagrid
4. Hover the buttons
5. Notice that they are white with black text

<img width="372" alt="image" src="https://github.com/user-attachments/assets/de493e7e-4799-4084-8c1b-24081da07510">

**Expected behavior**
The button text should be white and the background should be a darker semi-transparent color:
<img width="372" alt="image" src="https://github.com/user-attachments/assets/36882700-6094-408a-a40e-489b882f021a">

**Version**

- ids-enterprise: 4.98.0

**Platform**
 - Infor Application/Team Name: Portal

**Additional context**
Possibly caused by https://github.com/infor-design/enterprise/pull/8901

...although it might not be, since the last version where this works as intended is in 4.96.0

**Comment by tmcconechy** [comment]
Yes it probably was @tjamesallen15 can you take a look. You can reproduce it also on:

https://main-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection.html
- select any row
- hover the buttons

This type of button should be treated like a tertiary button on a blue background. i.e. see https://4900-enterprise.demo.design.infor.com/components/datagrid/example-mixed-selection.html

**Comment by tjamesallen15** [comment]
Will do @tmcconechy , sry for the delay we got long weekend.

**Comment by anhallbe** [comment]
Update: It looks like there are similar issues for other buttons (tertiary only?) when inside a header, and **using the classic theme**. See:

https://inforwiki.atlassian.net/browse/LIME-10119

![image](https://github.com/user-attachments/assets/98270e28-c838-4c34-a6ba-21f846b5d8b7)
![image](https://github.com/user-attachments/assets/b8025b9d-3e2a-4455-87b1-359d918fa13c)
![image](https://github.com/user-attachments/assets/23758799-648b-4ea6-80e0-299571a0f042)
![image](https://github.com/user-attachments/assets/510daf88-0555-4227-87d5-8aa6d6d04a78)
![image](https://github.com/user-attachments/assets/bae8eba6-5405-49f8-89a8-2eda82df4779)

**Comment by tmcconechy** [comment]
@tjamesallen15 can you check the new cases proposed by @anhallbe ? Or can you test if this resolved them all @anhallbe ?
