### ISSUE TITLE
Validation: Settings undefined on load in angular

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#8981]
**Describe the bug**
Landmark has a use case where we are using the validation required, but there is a timing issue causing the settings to not be defined when checking truncated. Would it be possible to add a safety to these calls of this.settings.truncated:

https://github.com/infor-design/enterprise/blob/main/src/components/validation/validator.js#L928
https://github.com/infor-design/enterprise/blob/main/src/components/validation/validator.js#L937
https://github.com/infor-design/enterprise/blob/main/src/components/validation/validator.js#L999

Just changing them to this.settings?.truncated should work.

**To Reproduce**
Angular timing issue makes this hard to create a simple example.

**Expected behavior**
The safety is in the code so that we don't get the undefined error message.

**Version**

- ids-enterprise: 4.98.0

**Platform**
 - Infor Application/Team Name: Infor Landmark UI
 - All

**Comment by tmcconechy** [comment]
@Sovia Patch is made its in 4.98.2 ( ids-enterprise-ng (18.2.3))
