### ISSUE TITLE
Color Picker Short Field Component: Tooltip inconsistency when selecting from the color palette

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#899]
**Describe the bug**
Color Picker Short Field Component: Tool-tip inconsistency when selecting from the color palette

**To Reproduce**
1. Go to URL: http://4110-beta1-enterprise.demo.design.infor.com/components/colorpicker/example-short-field.html
2.  Open the color palette for Validation
3. Click on the color #8DC9E6 of any color on the last row of the color palette 
4. When a color is selected the tool-tip is appearing in different areas of the page.  I can't produce a screen shot but @tmcconechy is aware of the issue.

**Expected behavior**
The tool-tip should appear in the correct location of the UI

**Screenshots**
None

**Platform**
All Browsers
 
**Additional context**
None

**Comment by tmcconechy** [comment]
This issue can no longer be reproduced on http://master-enterprise.demo.design.infor.com/components/colorpicker/example-short-field.html suspect it was fixed along the way.
