### ISSUE TITLE
Active tab text color is hard to read

### ISSUE THREAD

**Issue by inforrpunay** [infor-design/enterprise#8991]
**Describe the bug**
Active tab text color is hard to read when using Azure color

**To Reproduce**

1. Go to https://latest-enterprise.demo.design.infor.com/components/tabs-module/example-index.html?colors=0066D4
2. Use Azure color
3. Active tab text color is hard to read (color is blue)

**Expected behavior**
Active tab text color should be readable (white just like in https://4880-enterprise.demo.design.infor.com/components/tabs-module/example-index.html?colors=0066D4)

**Version**

- ids-enterprise: v4.98.0

**Screenshots**
![image](https://github.com/user-attachments/assets/f294e594-fb5a-40c8-9e35-0c2e1792bfd6)

**Platform**
 - Infor Application/Team Name: Infor M3
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by ericangeles** [comment]
We need to check all the personalization colors. Alabaster is the only correct active tab color.

**Comment by tmcconechy** [comment]
@ericangeles @inforrpunay 

We fixed this recently on https://github.com/infor-design/enterprise/issues/8831 implementing designs from m3 designers.
The active color is now visible on main https://main-enterprise.demo.design.infor.com/components/tabs-module/example-index.html?colors=0066D4#order-entry

This will be in next release I think this is fixed / duplicate
