### ISSUE TITLE
Dropdown: Memory Leak when opened and closed

### ISSUE THREAD

**Issue by crisjoshua-inf** [infor-design/enterprise#8992]
**Describe the bug**
When attempting to find leaks in our code, we found a scenario where soho-dropdowns would have detached elements.

**To Reproduce**

1. Go to http://localhost:4000/components/dropdown/example-no-search.html
2. Open and Close dropdown
3. Edge has an option in devtools to see detached elements. Get Detached Elements before Open dropdown list, and Get Detached Elements after closing dropdown list and Click Collect Garbage
4. Repeat Step 3
5. See Detached Elements leak

Developer Tools in Edge were used here:
![image](https://github.com/user-attachments/assets/6a129943-2808-473f-a904-57fffa888ea5)

Another scenario: 
Although unable to reproduce in demo code, we have had scenarios where when reinitializing the dropdown without properly destroying the instance would have issues with detached elements as well regarding a listener.
Code Suggestion: Add .off here in dropdown.js. Thanks!
![image](https://github.com/user-attachments/assets/1c4b566c-dcb4-4e9d-bfce-4f6c371ebe6d)

**Expected behavior**

**Version**

- ids-enterprise: [e.g. v4.9.0 or v4.10.0]

**Screenshots**

**Platform**
 - Infor Application/Team Name: Infor M3
 - Device: (if applicable) Laptop/Edge
 - OS Version: Windows 10
 - Browser Name: Microsoft Edge 
 - Browser Version: 

**Additional context**

**Comment by tmcconechy** [comment]
@crisjoshua-inf does the code suggestion fully solve  the issue?

**Comment by crisjoshua-inf** [comment]
No, the code suggestion solves the issue on our side regarding reinitialization of our dropdowns in M3. But I've found adding this particular code in the closeList function improves the leak to only 1 detached element after garbage collection when opening and closing:
![image](https://github.com/user-attachments/assets/78d2b96c-4591-44e6-92c9-1eeb587fbd62)

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4504
