### ISSUE TITLE
Tabs: Header tabs in overflow get inserted into tab order, instead of scrolling the tab container

### ISSUE THREAD

**Issue by Sovia** [infor-design/enterprise#9004]
**Describe the bug**
A header tab in the overflow menu is inserted into the tab order, instead of scrolling. This is causing indexing issues when used in landmark UI, but it also easily seen in the controls.

**To Reproduce**

1. Go to https://main-enterprise.demo.design.infor.com/components/tabs-header/example-index.html
2. Click on the tab overflow dropdown, and select Header Tabs 18
3. See error. Header tab 18 gets inserted earlier in the tab order.
![HeaderTabsIssue](https://github.com/user-attachments/assets/535e22d9-1f2b-4cb8-a72a-d0a7a4b0bafa)

**Expected behavior**
The tab contained should "scroll" over to the correct tab position. This was the behavior in version 4.95.5
![HeaderTabsIssuePrevious](https://github.com/user-attachments/assets/1ff2fb15-264c-4223-8cb9-7652e25d16ac)

**Version**

- ids-enterprise: 4.99.0

**Platform**
 - Infor Application/Team Name: Landmark Web UI
 - All

**Comment by vonnyw** [comment]
@tmcconechy requesting this issue to be prioritized in 4.98 or 4.99 please.

**Comment by yohannahbautista** [comment]
@Sovia @tmcconechy @ericangeles 
Hello, the behavior looks to be because of a previous request (moving the tab to the next viewable space): https://github.com/infor-design/enterprise/issues/8016#issuecomment-2100521615

**Comment by Sovia** [comment]
Hi @yohannahbautista can you make a flag that controls that behavior? Landmark UI doesn't want it, and it breaks out indexing when displaying many tabs. This flag would have to be exposed in the angular wrappers as well.

**Comment by tmcconechy** [comment]
@Sovia @yohannahbautista @ericangeles I dont think we want a setting for this. I think the behavior is incorrect. 

If you follow the steps. If you select Tab 18 why is it putting it between Tab 9 and 10 ten. It shouldnt change the order of the tabs. When you select Tab 18 it should still scroll to it but it should come after Tab 17.

Thats my take on this.

**Comment by Sovia** [comment]
@tmcconechy I am also happy with it to revert to it's previous behavior! I thought 8016 was saying it was a deliberate design change.
