### ISSUE TITLE
Context Menu Right Click Mobile Component: Long press not working properly on horizontal view

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#901]
**Describe the bug**
iOS iPhone X: Context Menu Right Click Mobile Component: Long press not working properly on horizontal view

**To Reproduce**
1. Go to URl: http://4110-beta1-enterprise.demo.design.infor.com/components/contextmenu/example-page-rightclick.html
2. Turn phone to horizontal view 
3. Long-press on your mobile device
4. the context menu opens but you can't view the full list.  Please see screen shot attached

**Expected behavior**
The full list should be displayed. 

**Screenshots**
![img_0138](https://user-images.githubusercontent.com/39101346/46361385-77cb9180-c63b-11e8-845a-2609835d4aa3.PNG)

**Platform**
 - Device [iPhone X ]

**Additional context**
None

**Comment by tmcconechy** [comment]
This issue is probably fixed since we set the attachToBody on.
