### ISSUE TITLE
Modal: Seeing console errors after closing modal using close icon

### ISSUE THREAD

**Issue by aniltalari22** [infor-design/enterprise#9013]
**Describe the bug**
Observed an issue with SohoModal Service after opening a modal and if we close it using the close icon button then we could see
the following error in the console.
 
Blocked aria-hidden on a <button> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.

**To Reproduce**

1. open the link  [IDS-Example](https://latest-enterprise.demo.design.infor.com/components/modal/example-close-btn.html)
2.Click on show Modal button.
3.Right click and inspect the page.
4.Now click on close icon button.
5.You can see the error in the console.

**Expected behavior**
Such console errors should not be there.

**Version**
18.2.1

**Screenshots**
![image](https://github.com/user-attachments/assets/b73b5bde-6226-4a2d-b45d-4119878ad35b)

**Platform**
 - Infor Application/Team Name: [e.g. Infor XYZ, Infor ABC]
 - Device: (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name: [e.g. chrome, safari, stock browser]
 - Browser Version: [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

**Comment by tmcconechy** [comment]
Fixed as per https://inforwiki.atlassian.net/browse/IDS-4807
