### ISSUE TITLE
SohoDatagrid: Throwing error on cell change (Error: Cannot read properties of undefined (reading 'async'))

### ISSUE THREAD

**Issue by manjaripalavancha** [infor-design/enterprise#9015]
**Describe the bug**
Soho datagrid with lookup, When focus on to the lookup and immediately trying to focus on the other cell It's throwing an error of" Error: Cannot read properties of undefined (reading 'async')".

**Steps to reproduce the behavior:**
1. Create a datagrid with lookup and one more input/dropdown any type of cell
2. Focus on the lookup/Select any value from the lookup 
3. If any value selected from lookup options don't click outside or don't press tab/enter
4. Immediately focus on other cell to provide any value
5. The screen is loaded with the above error and not able to proceed further

**Expected behavior**
The error should be clear and other cell should be focused.

**Version**
- ids-enterprise: 18.2.1

**Screenshots**
Stackblitz example: [https://stackblitz.com/edit/ids-quick-start-1821?file=src%2Fapp%2Fapp.component.ts](url)

**Additional context**
issue communication channel link: [https://teams.microsoft.com/l/message/19:83173693057f4991b7a84f030975c06d@thread.skype/1725422413765?tenantId=457d5685-0467-4d05-b23b-8f817adda47c&groupId=4f50ef7d-e88d-4ccb-98ca-65f26e57fe35&parentMessageId=1725422413765&teamName=Infor%20Design%20System&channelName=Angular%20Components&createdTime=1725422413765](url)

**Comment by tmcconechy** [comment]
Fixed as per https://oxford.awsdev.infor.com/infor-design/enterprise-ng/-/merge_requests/4
