### ISSUE TITLE
Pie Chart Component: Legends get cut off on Mobile

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#902]
**Describe the bug**
Pie Chart Component: Legends get cut off on Mobile

**To Reproduce**
1. Go to url: http://4110-beta1-enterprise.demo.design.infor.com/components/donut/example-index.html
2. The word "Component is getting cut off
4. Please See screen shot attached

**Expected behavior**
The text in the legends should appear correctly

**Screenshots**
![img_0139](https://user-images.githubusercontent.com/39101346/46362105-65525780-c63d-11e8-97c6-c408664dd996.PNG)

**Platform**
iPhone X

**Additional context**
None

**Comment by johnbarcena** [comment]
tested on http://master-enterprise.demo.design.infor.com/components/donut/example-index.html
Test PASSED
