### ISSUE TITLE
Datagrid's settingschanged event is called multiple times as it's being invoked by drag event.

### ISSUE THREAD

**Issue by vonnyw** [infor-design/enterprise#903]
**Describe the bug**
Datagrid's settingschanged event is called multiple times as it's being invoked by drag event.

**To Reproduce**
Drag a column on a data grid and observe how many times it calls settingschanged event.

**Expected behavior**
Datagrid's settingsChanged event should be called once from dragend event.

**Platform**
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
To reproduce this in our samples...

1. go to http://localhost:4000/components/datagrid/example-reorder.html (or any page with settingschange event wired up)
2. drag in between the first and second column and drag it to make it wider
3. watch the console

We probably can move this from firing during the dgr event and do it in the dragend. But need to make sure...
1. still has same info in the event
2. first less
3. columns still save correctly for example on:
http://localhost:4000/components/datagrid/test-save-settings-manual.html 
http://localhost:4000/components/datagrid/test-save-settings-serverside.html
http://localhost:4000/components/datagrid/test-save-settings.html

(test here is to resize the column and then reload the page, should be the same size)

**Comment by brianjuan** [comment]
http://4120-beta0-enterprise.demo.design.infor.com/components/datagrid/example-reorder.html
http://4120-beta0-enterprise.demo.design.infor.com/components/datagrid/test-save-settings-manual.html
http://4120-beta0-enterprise.demo.design.infor.com/components/datagrid/test-save-settings-serverside.html
http://4120-beta0-enterprise.demo.design.infor.com/components/datagrid/test-save-settings.html
Passed QA testing on all browsers, moving to Done,
