### ISSUE TITLE
Datepicker: calendar outside of popup

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#906]
http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html

**Describe the bug**
The calendar popover has padding that is forcing the calendar outside of the popover.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datepicker/example-index.html'
2. Click on 'the date picker'

**Screenshots**
![image](https://user-images.githubusercontent.com/39749678/46381075-e82ded80-c6e3-11e8-815e-7cb969f9f991.png)

**Platform**

 - OS Version: Windows 10
 - Browser Name chrome, IE11

**Comment by tmcconechy** [comment]
We fixed this on https://github.com/infor-design/enterprise/issues/871
Its only on the 4.11.x branch at the moment for 4.11 release. Will get merged back to master on release.

**Comment by marknolaninfor** [comment]
Thanks @tmcconechy
