### ISSUE TITLE
Datagrid DropDown - last option is cropped when there are several options

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#909]
**Describe the bug**
When there are several values to choose from in an Editable Datagrid with a DropDown datatype, the last value is actually cropped.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/datagrid/example-editable.html'
2. Add More values for the options in the "Action" column.
`$('#datagrid').data('datagrid').settings.columns[8].options`
3. See screenshot below, as seen the last option is cropped.

**Screenshots**
![image](https://user-images.githubusercontent.com/41028784/46399088-62349580-c729-11e8-8fd8-7ed98af9bd0b.png)

**Platform**
 - Windows 10
 - Google Chrome, Microsoft Edge

**Comment by tmcconechy** [comment]
This can also be reproduced by datagrid/editable/changing editable.html to add

```
        var selectOptions = [
          {id: '', label: '', value: -1},
          {id: 'oh1', label: 'On Hold', value: 1},
          {id: 'sh1', label: 'Shipped', value: 2},
          {id: 'ac1', label: 'Action 1', value: 4},
          {id: 'ac2', label: 'Action 2', value: 5},
          {id: 'ac3', label: 'Action 3', value: 6},
          {id: 'ac4', label: 'Action 4', value: 7},
          {id: 'ac5', label: 'Action 5', value: 8},
        ];
```

...
```
columns.push({ id: 'action', name: 'Action', field: 'action', formatter: Formatters.Dropdown, editor: Editors.Dropdown, validate: 'required', options: selectOptions});
```

**Comment by tmcconechy** [comment]
Posted a PR, but it wont build until the problem is resolved.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/example-editable.html
Passed QA testing on all browsers.
