### ISSUE TITLE
Editor: Changing background color is not working on iOS Safari and Firefox

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#911]
**Describe the bug**
Editor: Changing background color is not working on iOS Safari and Firefox.

**To Reproduce**
1. Go to http://4110-beta1-enterprise.demo.design.infor.com/components/editor/example-with-backcolor.html in iPhone X Safari or Firefox
2. Highlight any word/s
3. Try to change the background color, the colorpicker will not close when you try to select any color,
and the selected color will not also be applied.

**Expected behavior**
Changing of background color inside the editor should work properly on iOS Safari and Firefox.

**Screenshots**
No applicable screenshots.

**Platform**
 - iPhone Safari and Firefox

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This issue appears fixed when i retry on http://latest-enterprise.demo.design.infor.com/components/editor/example-with-backcolor.html on safari. Moving to QA so we can have it retested and confirmed.

**Comment by brianjuan** [comment]
http://4150-beta0-enterprise.demo.design.infor.com/components/editor/example-with-backcolor.html
Issue still happens on iOS browsers

**Comment by tmcconechy** [comment]
OK i read this wrong. I tested safari not IOS. We are still going to have issues on mobile with this functionality. Not sure how we could fix. Pulling this back into the backlog for later

**Comment by tmcconechy** [comment]
Descoping this for now
