### ISSUE TITLE
Make typescript typings for each component

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#914]
**Is your feature request related to a problem? Please describe.**

The issue of maintaining types for ids-enterprise came up on the angular call and on issues like https://jira.infor.com/browse/SOHO-7477

Advantages Are:
- users using typescript only could use it
- easier to maintain because its close to our code
- easier to see at a glance what our api is and test it

**Describe the solution you'd like**
- add a component-name.d.ts file to each src/components folder
- build process takes them all and makes a ids-enterprise.d.ts which is shipped
- or this file should have its on npm import

**Additional context**
https://jira.infor.com/browse/SOHO-7477
https://github.com/infor-design/enterprise-ng/issues/203
https://github.com/Microsoft/dts-gen

@bthharper 
Toby Wicks

**Comment by EdwardCoyle** [comment]
We might be able to borrow some of this from the NG project

**Comment by tmcconechy** [comment]
yeah i think we will have to manually maintain them but should see that they jive with whats there as well. be a bit of work but once we have it in place it will also help make sure or settings/methods are typesafe.

**Comment by bthharper** [comment]
@tmcconechy @EdwardCoyle probably only want to define the typings once, in facts it has always been a bit of an issue that the typing were defined within the NG library - so having them defined in a separate @types package would be perfect.

**Comment by tmcconechy** [comment]
That would be ideal but probably have to check that they "are" i sync is all as well.

**Comment by tmcconechy** [comment]
Closing this issue as a duplicate (sort of). We are doing this for the eventual 5.0 and each component will have its own type.
For now we have enterprise-ng-typings for angular.

See Also #4631
