### ISSUE TITLE
ContextualActionPanel: Search field is taking the entire Complex Toolbar on mobile

### ISSUE THREAD

**Issue by brianjuan** [infor-design/enterprise#918]
**Describe the bug**
ContextualActionPanel: Search field is taking the entire Complex Toolbar on mobile

**To Reproduce**
1. Go to http://4110-beta1-enterprise.demo.design.infor.com/components/contextualactionpanel/test-complex-toolbar.html on any mobile device
2. Open the Contextual Action Panel
3. Notice the search field in the complex toolbar

**Expected behavior**
Complex toolbar inside Contextual Action Panel should be displayed properly on mobile

**Screenshots**
<img width="502" alt="screen shot 2018-10-04 at 6 40 05 pm" src="https://user-images.githubusercontent.com/39508864/46469947-8797d100-c807-11e8-8ddf-203d0b0a8222.png">

**Platform**
 - All mobile devices

**Additional context**
No additional context.

**Comment by tmcconechy** [comment]
This is still an issue in 4.14 but it actually looks worse now. We may need flex toolbar to be completed first.

**Comment by ericangeles** [comment]
Hi @tmcconechy, it looks like it has been fixed now. 

<img width="459" alt="screen shot 2019-02-12 at 5 31 11 pm" src="https://user-images.githubusercontent.com/8839327/52625534-2c2fcb00-2eec-11e9-8f95-d227bafe0743.png">

**Comment by tmcconechy** [comment]
Yeah looks better but not perfect :) I think we could tweak this a bit to make it look better.

**Comment by ericangeles** [comment]
Awesome! Let me know what are your proposals, so I can fix it. :)

**Comment by tmcconechy** [comment]
@EdwardCoyle What do you think? Maybe we can just not expand this and have the search on the right that you have to tab to expand. That way you can see the title and all?

**Comment by tmcconechy** [comment]
Yeah tested this again and it doesnt look right to me. I think it should revert to  icon only then expands when clicked. On mobile.

**Comment by janahintal** [comment]
QA Passed. Thank you. 
Verified in https://master-enterprise.demo.design.infor.com/components/contextualactionpanel/test-complex-toolbar.html
![image](https://user-images.githubusercontent.com/45757016/84257763-752b7a00-ab48-11ea-9ef5-ce19ebfa9e89.png)
