### ISSUE TITLE
List View: Improve paging performance on larger datasets

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#922]
**Describe the bug**
Extending on #430 we want to improve the performance on paging.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/listview/test-listview-performance.html from the PR on #430 once merged
2. Notice on render that initially all nodes are added to the page, then they are paged
3. Change page size to 100 so many pages are added (numbers are in a weird sequence)

**Expected behavior**
Only the first page is ever added to the DOM and the numbers are in a better sequence.

**Platform**
 - Worst on IE11

**Additional context**
#430 
#250

**Comment by CindyMercadoReyes** [comment]
This issue is now resolve.
