### ISSUE TITLE
Calendar Component: responsive view

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#925]
**Describe the bug**
Calendar Specific Month Component: Can't view Legend or Time off on responsive view

**To Reproduce**
1. Go to URL: http://4110-beta1-enterprise.demo.design.infor.com/components/calendar/example-specific-month.html#
2.Make the page responsive
3. The legend and Upcoming Time off is not appearing on responsive view
4. Please see screen shot attached. 

**Expected behavior**
The Legend and Time off should be visible on responsive view

**Screenshots**

<img width="400" alt="calendar legends not appearing" src="https://user-images.githubusercontent.com/39101346/46485705-36b5b780-c7ca-11e8-8dc3-5154b3cbe634.png">

**Platform**
- MAC Chrome

**Additional context**
Design:
[SoHo Calendar-Phone_View-102318_JN.pdf](https://github.com/infor-design/enterprise/files/3179268/SoHo.Calendar-Phone_View-102318_JN.pdf)

**Comment by tmcconechy** [comment]
There is no design for this at the moment so it is disabled on mobile.

**Comment by tmcconechy** [comment]
Will do this after day view is added.

**Comment by janahintal** [comment]
This issue is now resolved. Will now move to Done. Thank you. 
![image](https://user-images.githubusercontent.com/45757016/80576560-fff06380-8a37-11ea-8eb9-9ba5e37c9706.png)
