### ISSUE TITLE
Lookup Modal Component: Alignment issue with the scroll bar

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#927]
**Describe the bug**
Win 10 IE 11: Lookup Modal Component: Alignment issue with the scroll bar

**To Reproduce**
1. Go to URL: http://4110-beta1-enterprise.demo.design.infor.com/components/lookup/test-custom-modal.html
2. Click on the Lookup button
3. The Scroll bar is not aligned properly  
4. Please see screen shot attached. 

**Expected behavior**
The scroll bar should be aligned properly within the lookup window

**Screenshots**
![bs_win10_ie_11 0](https://user-images.githubusercontent.com/39101346/46487718-b9407600-c7ce-11e8-9bbe-b40a390f1338.jpg)

**Platform**

 -Windows 10 IE 11

**Additional context**
None

**Comment by tmcconechy** [comment]
Again, this example seems to have inconsistency issues. I think we can just adjust the example so the duplicate scrollbar does not occur.

**Comment by tmcconechy** [comment]
Decided to just close this issue and not fix as its only a test page
