### ISSUE TITLE
Lookup Contextual Action Panel Conponent missing title, button, and label

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#930]
**Describe the bug**
Lookup Contextual Action Panel Conponent missing title, button, and label

**To Reproduce**
1. Go to URL:http://4110-beta1-enterprise.demo.design.infor.com/components/lookup/test-on-contextual-action-panel.html
2. Click on CAP button
3. The CAP pop up window appears. However, it's missing the following: Title, Save button and the label for the Close button
4. Please see screen shot attached. 

**Expected behavior**
The CAP window should have the Title, Save button, and the label for the Close button.

**Screenshots**
<img width="1236" alt="lookup cap" src="https://user-images.githubusercontent.com/39101346/46494196-46d89180-c7e0-11e8-8ce3-a310d343f920.png">

**Platform**
-MAC Chrome

**Additional context**
None

**Comment by tmcconechy** [comment]
To resolve this issue, we should just update the contextual action panel.
The only purpose is to prove that a lookup can execute from the CAP. So this may also be covered by a e2e test.
