### ISSUE TITLE
Hierarchy Context Menu With Details Component: Profile text is cut off

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#931]
**Describe the bug**
Windows 10 IE 11: Hierarchy Context Menu With Details Component: Profile text is cut off

**To Reproduce**
1. Go to URL: http://4110-beta1-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html
2. Click on the three dot eclipse button for Kaylee Edwards on WIn 10 IE 11
3. Her profile text is cut off.
4. Please see screen shot attached. 

**Expected behavior**
The text for her profile should not be cut off

**Screenshots**
![hierarchy component](https://user-images.githubusercontent.com/39101346/46495471-7fc63580-c7e3-11e8-9c2b-44ad76b2666f.png)

**Platform**
Windows 10 IE 11
**Additional context**
None

**Comment by tmcconechy** [comment]
@krishollenbeck

**Comment by tmcconechy** [comment]
Added to this sprint so it can be QA'd. This was pulled out of up for grabs while we change sprints.

**Comment by CindyMercadoReyes** [comment]
This issue is still occurring on Mac FF 63.

**Comment by tmcconechy** [comment]
@CindyMercadoReyes The issue was for windows. What do you see wrong in Mac FF?
The only thing i can see if is if you make the page shorter the menu wont fit, but you can scroll it. Thats all we can do.

**Comment by ericangeles** [comment]
Yeah I see it also in Mac FF. It seems when the scrollbar appears, it tends to overlap the detail fields same as in IE11. We can handle this one @tmcconechy. This would be a quick fix, then I'll create a new PR.

**Comment by janahintal** [comment]
QA Passed.  Moving to Done. 
Tested in: http://4140-rc0-enterprise.demo.design.infor.com/components/hierarchy/example-context-menu-with-details.html for Windows 10 IE 11
