### ISSUE TITLE
Hierarchy Many Children Component: Left Edge Color Issue

### ISSUE THREAD

**Issue by CindyMercadoReyes** [infor-design/enterprise#932]
**Describe the bug**
Hierarchy Many Children Component: Left Edge Color Issue

**To Reproduce**
1. Go to URL: http://4110-beta1-enterprise.demo.design.infor.com/components/hierarchy/example-many-children.html
2. Click on the arrow button for Mary Butler
3. Scroll down to the "Open" position
4. The color is left edge. Please see screen shot attached. 

**Expected behavior**
The color should not be left edge

**Screenshots**
<img width="480" alt="hierarchy error" src="https://user-images.githubusercontent.com/39101346/46496646-8e621c00-c7e6-11e8-86d3-5bdf5c0640cf.png">

**Platform**
- MAC Chrome

**Additional context**
None

**Comment by tmcconechy** [comment]
Ideally we can style the circle to have the same color as the left edge.

**Comment by tmcconechy** [comment]
Added to this sprint so it can be QA'd. This was pulled out of up for grabs while we change sprints.

**Comment by brianjuan** [comment]
https://4140-beta0-enterprise.demo.design.infor.com/components/hierarchy/example-many-children.html
Passed QA testing on all browsers.
