### ISSUE TITLE
Dropdown popup - the previously selected item in the list has low contrast in high contrast mode

### ISSUE THREAD

**Issue by jake-harrington** [infor-design/enterprise#945]
**Describe the bug**
When you click open a dropdown it shows the previously selected item at the top of the list. On high contrast it's black text on dark gray background, the rest of the popup is black text on white so it doesn't look intended.

![image](https://user-images.githubusercontent.com/39064853/46554997-9df56980-c8a7-11e8-9524-94b83e3f4af7.png)

**To Reproduce**
1. Go to https://design.infor.com/code/ids-enterprise/latest/demo/dropdown/example-index?font=source-sans&theme=high-contrast
2. Click open the dropdown
3. Look at the top text

**Platform**
 - Enterprise 4.10.x

**Comment by tmcconechy** [comment]
In this theme and at this state, the background on the field should probably be white like the closed state. May need a new sass variable for all themes

**Comment by brianjuan** [comment]
Does this also apply to mobile? Currently, the previously selected item has gray background on all themes for both iOS and Android.
<img width="543" alt="screen shot 2018-10-19 at 3 00 22 pm" src="https://user-images.githubusercontent.com/39508864/47202491-d620a000-d3af-11e8-9611-d0222f0319c2.png">

**Comment by tmcconechy** [comment]
Yes, it should. Moving to failed QA. Can you another have a look @tjamesallen15 on ios and android?

**Comment by tjamesallen15** [comment]
Hi @tmcconechy, I'll check on this.

**Comment by brianjuan** [comment]
http://4120-rc1-enterprise.demo.design.infor.com/components/dropdown/example-index.html
Passed QA testing on all browsers including mobile.
