### ISSUE TITLE
Calling rating method val() with input parameter '0' does not work

### ISSUE THREAD

**Issue by guoliang** [infor-design/enterprise#946]
**Describe the bug**
Calling Rating component's API method "val()" with input 0 does not set the component to zero stars

**To Reproduce**
Call rating's val() method with input parameter 0

**Expected behavior**
Should set zero stars filled

Does not work in 4.9.0, or 4.10.0

**Comment by tmcconechy** [comment]
1. go to http://localhost:4000/components/rating/example-index.html
2. type `$('.rating').data('rating').val(0)` (should show zero stars)

Make test for this..
