### ISSUE TITLE
activateRow and deactivateRow toggle state incorrectly

### ISSUE THREAD

**Issue by pwpatton** [infor-design/enterprise#948]
**Describe the bug**
For indeterminate paging toggleRowActivation changes activated index across pages.

Per Tim:
- move logic from toggleRow to either activateRow or deactivateRow
- change toggleRow to check state and call either activateRow or deactivateRow

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate-landmark.html
2. Click on 2nd row (but not the checkbox) to show it activated in light blue
3. Click next page paging bar button
4. 2nd row index on 2nd page isn't activated. Also, Trying to click on it to activate it is failing as well. Have to click on a nother row and then back to get 2nd row index to activate.

**Expected behavior**
For indeterminate paging 2nd row index on 2nd page and any subsequent page should be activated.

**Platform**
 - Device: PC
 - OS Version: Windows 10
 - Browser Name: Chrome
 - Browser Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
I'll take this as we discussed this a lot, once we get it into a sprint.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/example-paging-indeterminate-landmark.html
http://master-enterprise.demo.design.infor.com/components/datagrid/example-paging-indeterminate-landmark.html
Passed QA testing on all browsers, activateRow and deactivateRow now toggle correctly.
