### ISSUE TITLE
Upgrade to Babel 5 and Rollup - And related dependencies

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#950]
**Is your feature request related to a problem? Please describe.**

https://babeljs.io/ has a version 5. Which is apparently much faster. We should upgrade to it.
We are also several releases behind on rollup (now a 1.0 as well with source map fixes)

**Describe the solution you'd like**

Update babel/rollup and any related dependencies like rollup-plugin-babel. Check for any other minor dependencies which can be upgraded.

Test builds, Tests , Custom Builds, Docs and compile work on kitchen sink without errors.
Compare outputted files for major differences.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this ticket to the done bucket.

**Comment by tmcconechy** [comment]
I think this is now fixed as we are on 6.0 and sourcemaps have been working so closing
