### ISSUE TITLE
Send token theme JSON with documentation publish

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#951]
**Is your feature request related to a problem? Please describe.**
This is so we can specifically pair the exact token version with the enterprise version to display accurate documentation (include all 3 themes).

**Describe the solution you'd like**
See the CSS repo for an example on how to send the JSON files, but note `.raw.json` is deprecated if https://github.com/infor-design/css/issues/176 hasn't been completed yet.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved. Moving this GitHub ticket to the Done  bucket.
