### ISSUE TITLE
Lookup: selectRowByValue fails when the field is a function

### ISSUE THREAD

**Issue by marknolaninfor** [infor-design/enterprise#953]
**Describe the bug**
The field property of a lookup can either be a field name as a string or a function. When it is defined as a function it will error and you are unable to change the lookups value.

**To Reproduce**
1. Go to 'http://master-enterprise.demo.design.infor.com/components/lookup/test-custom-matching.html'
2. Click on 'the Products lookup and select a value'
3. Click on 'the Products lookup and attempt to change the value'

**Expected behavior**
It should not fail.

**Platform**
 - OS Version: Windows 10
 - Browser Name chrome

**Additional context**
```
let rowValue = '';

if (typeof field === 'function') {
  rowValue = field(data);
} else {
  rowValue = data[i][field];
}

if (rowValue.toString() === value.toString()) {
    isMatch = true;
}
```

**Comment by brianjuan** [comment]
Passed QA testing using the steps provided in #958

**Comment by tmcconechy** [comment]
@jonathanamiran Yes, please make a new bug report following the template. I'll route it.
Easier that way.
