### ISSUE TITLE
Datagrid Filter Tooltip - Formatting of the Tooltip Message

### ISSUE THREAD

**Issue by NathanLouisBarcial** [infor-design/enterprise#955]
**Describe the bug**
When the enableTooltips setting for a Datagrid w/ Filter is on, hovering on the Filter Box will show a tooltip of the filter. The formatting of the tooltip message looks odd. Just a minor issue though.

**To Reproduce**
1. Go to http://master-enterprise.demo.design.infor.com/components/datagrid/example-filter.html
2. Set the enableTooltips of the datagrid to true. 
```
$('#datagrid').data('datagrid').settings.enableTooltips = true
$('#datagrid').data('datagrid').render()
```
3. Hover on any of the Filters.

**Screenshots**
As seen below, the formatting of the tooltip for the filter looks odd.
![image](https://user-images.githubusercontent.com/41028784/46647982-719e5d80-cbc5-11e8-82f2-d618e65d320a.png)

**Platform**
 - All Platforms.

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/test-filter-with-tooltip.html
http://master-enterprise.demo.design.infor.com/components/datagrid/test-filter-with-tooltip.html
Passed QA testing on all browsers, tooltips are displayed correctly.
