### ISSUE TITLE
Remove identifying response headers from Demoapp

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#959]
**Is your feature request related to a problem? Please describe.**
One of the items discovered by Veracode Dynamic Scanning (#256) is that the demoapp should not be passing along HTTP headers that identify the operating system and application platform.  Despite the demoapp being non-customer-facing, this is a trivial fix that we can easily make.

**Describe the solution you'd like**
We should remove the `X-Powered-By` and `Server` headers from the server response.  Headers are trivial to remove via ExpressJS middleware:  https://stackoverflow.com/questions/44966462/how-to-remove-a-header-from-express-req-object

**Comment by EdwardCoyle** [comment]
Just noting here that while testing things, I confirmed that @tmcconechy's change for disabling x-powered-by was in fact working.  I moved it to the new middleware object for cleanup.

**Comment by CindyMercadoReyes** [comment]
There is no way for this issue to be tested via QA. Moving this ticket to the Done bucket.
