### ISSUE TITLE
Incorrect scss mapping

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#962]
**Describe the bug**
Application is incorrectly mapping modal styles to `_pager.scss` file as shown in Chrome Dev Tools.

**To Reproduce**
- Run app.
- Browse to http://localhost:4000/components/message/example-index
- Click Error Example button
- Open Dev Tools and/or Inspect `modal-content`, `modal-header`, `modal-title`, or `svg` inside modal.
- All these styles map to `_pager.scss` per Chrome Dev Tools though the styles actually exist inside `_modal.scss`

**Expected behavior**
I would expect to see these styles map correctly to `_modal.scss`

**Screenshots**
<img width="1911" alt="screen shot 2018-10-09 at 1 23 15 pm" src="https://user-images.githubusercontent.com/7952168/46686827-52a0cb00-cbc7-11e8-89f1-a147834a003e.png">

**Platform**
 - Mac laptop
 - macOS High Sierra 10.13.6
 - Chrome
 - 69.0.3497.100 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Interestingly on my version of chrome here 69.0.3497.100  that same modal-content class is said to be in http://localhost:4000/node_modules/ids-identity/dist/tokens/web/theme-soho.sass as opposed to _pager.scss

**Comment by ericangeles** [comment]
I tested all the ideas that @tmcconechy listed but unfortunately it didn't work.

**Comment by brianjuan** [comment]
Passed QA testing, tested using the steps in #1319
