### ISSUE TITLE
Change 'confirm' to 'success'

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#963]
**Is your feature request related to a problem? Please describe.**
`confirm` is used across icons and messages to indicate a successful status (similar to other statuses: `alert`, `info`, `error`).

**Describe the solution you'd like**
Change `confirm` to `success` as a more semantically correct convention. This is used in `datagrid`, `dropdown`, `field-filter`, `icons`, `input`, `listview`, `message`, `modal`, `notification`, `signin`, `stepchart`, `validator`, `validation`, and possibly elsewhere.

**Comment by tmcconechy** [comment]
We didnt actually change this yet, so repopening.

**Comment by davidcarlsonberg** [comment]
Should this be considered a breaking change and made for 5.0? Happy to address now...

**Comment by tmcconechy** [comment]
Is there maybe a way to deprecate "confirm" so it still works. i.e. copy confirm icon so there is both an icon-confirm and icon-success in the icons/svg.html file. Then rename everywhere in else so its using the new one.

That should be a little bit safer.

**Comment by tmcconechy** [comment]
- [ ] Also we could make message accept both confirm and success as options that do the same thing (but add the is-success icon in case of confirm. 
- [ ] Same with "notification.js"
- [ ] For step chart make it take icon-confirm, confirm, success or icon-success
- [ ] For validation.js make the type: 'confirm' or success work but default to success.
- [ ] Update tests

**Comment by brianjuan** [comment]
http://localhost:4000/components/alerts/example-index.html
http://localhost:4000/components/form/test-wrapped-labels.html
http://localhost:4000/components/icons/example-index.html
http://localhost:4000/components/icons/example-with-labels.html
http://localhost:4000/components/input/test-short-fields-validated.html
http://localhost:4000/components/stepchart/test-markup.html
http://localhost:4000/components/tabs/example-enable-disable-individual-tabs.html
http://localhost:4000/components/tabs/example-enable-disable.html
http://localhost:4000/components/validation/test-message-types.html
Passed QA testing on the URLs above, moving to Done.
