### ISSUE TITLE
Datagrid - non functional "Personalize Columns" when previously closed with using ESC on keyboard

### ISSUE THREAD

**Issue by vladimir-marko** [infor-design/enterprise#968]
**Describe the bug**
When modal window for personalize columns is closed be ESC button on keyboard then the next opening of the modal window for personalize columns is not functional.

**To Reproduce**
1) Open link in incognito window
https://design.infor.com/code/ids-enterprise/latest/demo/datagrid/example-multiselect.html?font=source-sans
2) Try to personalize the columns for datagrid
![image](https://user-images.githubusercontent.com/44021524/46727325-999ec700-cc80-11e8-92b9-e7d792bf1d8b.png)
3) Close the modal window by ESC on keyboard
4) Try to personalize the columns
5) Now nothing in the modal window can be checked/unchecked
6) The checking and unchecking of the columns is enabled again after pressing the ESC button and clicking the ‘Personalize Columns’
7) The mentioned steps 2-3 are switching on/off the ability to check/uncheck the defined columns in modal window for personalization.

 **Expected behavior**
Closing the modal window by pressing the ESC on keyboard should not disable the functionality in the next opening of the modal window.

**Platform**
  - OS Version:  Windows 7 Enterprise 64-bit
 - Browser Name  chrome
 - Browser Version Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by brianjuan** [comment]
http://localhost:4000/components/datagrid/example-multiselect.html
http://4120-beta0-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html
Passed QA testing, bug fix is working on all browsers.
