### ISSUE TITLE
Datagrid - filter in modal window for "Personalize columns" is temporarily disabling the check/uncheck functionality

### ISSUE THREAD

**Issue by vladimir-marko** [infor-design/enterprise#969]
**Describe the bug**
The using of the filter in modal window for "Personalize columns" is temporarily disabling the check/uncheck functionality in case that two separate words are used in filter. The second click is working without problem.

**To Reproduce**
1. Open link in incognito window
https://design.infor.com/code/ids-enterprise/latest/demo/datagrid/example-multiselect.html?font=source-sans
2. Try to personalize the columns
![image](https://user-images.githubusercontent.com/44021524/46729936-0917b500-cc87-11e8-95c0-79b66f0c0b05.png)

3. Write 2 whole words to filter some options
![image](https://user-images.githubusercontent.com/44021524/46729927-04530100-cc87-11e8-8fe3-626547ded56b.png)

4. Try to check/uncheck the selected option – the first click is ignored, the second is processed properly
5. This bug is not always replicable. The easiest way is to open the incognito window and then write the full name of two words item.
6. The bug doesn’t appear when the part of word is used in filter and item is clicked.

**Expected behavior**
Even filtering which consist from 2 words should not disable the first click on filtered options.

**Platform**
 - OS Version:  Windows 7 Enterprise 64-bit
 - Browser Name: chrome
 - Browser Version: Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by tmcconechy** [comment]
Like you said, i wasnt able to reproduce this at all. Can you reproduce this on http://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html?font=source-sans by any chance?

**Comment by vladimir-marko** [comment]
Actually I don't have success to demonstrate mentioned bug on [http://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html?font=source-sans ](http://master-enterprise.demo.design.infor.com/components/datagrid/example-multiselect.html?font=source-sans) . I was able to simulate just [#968](https://github.com/infor-design/enterprise/issues/968)
