### ISSUE TITLE
Tab content cut off in mobile 

### ISSUE THREAD

**Issue by davidcarlsonberg** [infor-design/enterprise#971]
**Describe the bug**
The content of the tab is cut off in smaller screens and also doesn't display in dropdown menu of tab options.

**To Reproduce**
- http://localhost:4000/components/tabs-multi/example-index
- Open mobile Dev Tools in Chrome
- Notice Tab content is cut off on smaller device screens such as iPhone 5
- Notice content of first Tab also does not appear in dropdown of Tab options

**Expected behavior**
As a user I would expect to be able to read the content of the first tab either as a tab or as an option in the dropdown of tab options.

**Screenshots**
<img width="418" alt="screenshot" src="https://user-images.githubusercontent.com/7952168/46739989-bda5dc80-cc6f-11e8-894a-fc6bf4542b8e.png">

**Platform**
 - Mobile, specifically iPhone 5 (or Dev Tools Mobile view for iPhone 5 in Chrome for macOS)
 - Most recent iOS or most recent macOS
 - Chrome
 - Version 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
Spawned from PR #619 and corresponding Issue #960

**Comment by tmcconechy** [comment]
Im not sure how we could fix this, its not totally incorrect. So may be one we just leave as an awkward edge case.

**Comment by davidcarlsonberg** [comment]
Happy to take your lead on it. We can consider this issue documentation of the edge case.

**Comment by tmcconechy** [comment]
One thought is maybe on this very low break point can hide the "4 More items" text so its just an arrow and there is a bit more room. Still a long title wont show, but perhaps better.

Further, im not sure a side by side pattern like this is going to be of much benefit on a smaller devices as you are comparing two things side by side.

**Comment by janahintal** [comment]
QA Failed. Issue still exist in iOS Mobile for both Safari and Chrome browser. 
Tested in: https://4150-beta0-enterprise.demo.design.infor.com/components/tabs-multi/example-index

Steps to replicate:
1. in portrait mode, open safari or chrome 
2. goto > https://4150-beta0-enterprise.demo.design.infor.com/components/tabs-multi/example-index
3. notice that there is no ellipsis for the 1st and 3rd column
4. turn the phone to Landscape mode
5. notice that the ellipsis is already visible
6. turn the phone again to Portrait mode
7.  refer to the image below

Using iphone XS: doesn't have ellipsis and tab is cut off
<img width="469" alt="screen shot 2019-01-24 at 4 03 16 pm" src="https://user-images.githubusercontent.com/45757016/51663456-d0130e80-1ff1-11e9-9fe0-84c022bcf705.png">

Using iPhone 8: doesn't have ellipsis and tab is cut off
<img width="466" alt="screen shot 2019-01-24 at 4 27 35 pm" src="https://user-images.githubusercontent.com/45757016/51664709-fc7c5a00-1ff4-11e9-985f-ca8a6d8c301f.png">

iPhone 5s: doesn't have ellipsis
![image from ios 3](https://user-images.githubusercontent.com/45757016/51665150-0fdbf500-1ff6-11e9-8564-ecde7fc94b51.png)

**Comment by ericangeles** [comment]
@tmcconechy there's an error when the dropdown is missing.

<img width="1645" alt="screen shot 2019-01-24 at 6 09 15 pm" src="https://user-images.githubusercontent.com/8839327/51671173-4c621d80-2003-11e9-8436-98b33a0ca4df.png">

**Comment by janahintal** [comment]
QA Failed. 
Tested in: http://4150-rc0-enterprise.demo.design.infor.com/components/tabs-multi/example-index issue still existing. 

Tested in iPhone XS Max and XR  still no ellipsis after page load.

<img width="624" alt="screen shot 2019-02-04 at 4 37 12 pm" src="https://user-images.githubusercontent.com/45757016/52197639-2fe3a200-289b-11e9-8b8c-2b16533f5a76.png">

**Comment by tmcconechy** [comment]
Pushed a fix for this for rc1.

**Comment by CindyMercadoReyes** [comment]
This issue is now resolved.
