### ISSUE TITLE
Toolbar Searchfield - Now has wrong background color

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#972]
**Describe the bug**
Searchfield on forms, toolbars is now a darker color than before. Should fix as a regression for 4.11

**To Reproduce**
1. Go to <http://4110-rc0-enterprise.demo.design.infor.com/components/datagrid/test-click-event-on-rows.html>
1. Notice that the searchfield is darker now.
1. Compare to last version <http://4100-enterprise.demo.design.infor.com/components/datagrid/test-click-event-on-rows.html>

**Expected behavior**
Should be same background as 4.10

**Comment by clepore** [comment]
It seems like the ordering of the CSS has changed:
<img width="803" alt="screen shot 2018-10-10 at 12 44 35 pm" src="https://user-images.githubusercontent.com/742319/46752195-9ad4f180-cc8a-11e8-8eec-3a7f8dedfee6.png">
