### ISSUE TITLE
Button text/icon alignment is not centered

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#973]
**Describe the bug**
Button text and icon alignment is not vertically aligned in the center of the button.

**To Reproduce**
1. Go to <http://master-enterprise.demo.design.infor.com/>
2. View the button alignment

**Expected behavior**
Both should be evenly spaced vertically.

**Screenshots**
<img width="898" alt="screen shot 2018-10-10 at 10 29 19 am" src="https://user-images.githubusercontent.com/742319/46743892-02ce0c80-cc78-11e8-8c52-db1b862b3c40.png">

**Platform**
 - all

**Additional context**
Removing [this style property](https://github.com/infor-design/enterprise/blob/b8892dc91b464292ba1e1619e552a84c497eb65b/src/components/button/_button.scss#L46) seems to fix it, but we should investigate how this ripples through other button/icon/text interactions.

**Comment by brianjuan** [comment]
http://master-enterprise.demo.design.infor.com/
http://localhost:4000/
Passed QA testing on all browsers.
