### ISSUE TITLE
Complete Visual Regression Tests

### ISSUE THREAD

**Issue by tmcconechy** [infor-design/enterprise#978]
**Describe the solution you'd like**
Add a visual regression test for example components example-index page. And main component states if not covered on the example-index page

**Additional context**
Need to make these on a travis VM.

https://github.com/infor-design/enterprise/blob/master/docs/TESTING.md#creating-baseline-screenshots

**Comment by EdwardCoyle** [comment]
@infor-design/development would anyone oppose to making all visual regression tests use the demoapp's "no-frills" layout to inspect all visuals, unless the test specifically needs a certain layout to work correctly?

My thinking:  Ran into [this test](https://github.com/infor-design/enterprise/blob/master/test/components/tabs/tabs.e2e-spec.js#L163) while working on #852.  Before each of those tests run, the test page depends on using the keyboard to focus on an unrelated component.  Considering the fragility of the tests, I feel like we should avoid including unrelated components in tests, unless you are specifically testing integrations between those two specific components.  We should also test with as little "distraction" from the tested implementation as possible (don't include headers/searchfields/popupmenus on test pages that don't specifically test those things).  

To keep our demoapp's regular browsing experience in-tact, we should continue using the regular layout by default, but have the [e2e tests' `setPage()` helper utility](https://github.com/infor-design/enterprise/blob/master/test/helpers/e2e-utils.js#L12) hard-set the layout to "no-frills" unless specifically set to something else.

**Comment by clepore** [comment]
For a refactor period, I think it would be good to simplify all of the pages to have a default state of the bare minimum.

**Comment by clepore** [comment]
Yeah i'm thinking we could still do some sort of header + dropdown, but not use the controls for that, therefore they should never change.

**Comment by CindyMercadoReyes** [comment]
This visual regression test is completed. Moving this ticket to the Done folder.
