### ISSUE TITLE
Make demo.design.infor.com into a directory of all live demo urls

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#981]
**Is your feature request related to a problem? Please describe.**
It would be nice to see all currently available live demo urls/versions.

**Describe the solution you'd like**
Make <http://demo.design.infor.com> as a TOC of all available deployed demo urls/versions.

**Describe alternatives you've considered**
None currently, but open to other similar ideas on this issue.

**Additional context**
n/a

**Comment by nickwynja** [comment]
Currently, we have to log into the docker host and run `docker ps` to see all of the images that are running.

**Comment by tmcconechy** [comment]
Descoping this issue for now as Artem is working on a kubernetes solution so this isnt likely to be needed.
