### ISSUE TITLE
popup-menu: li.is-disabled has highlighted background when with .is-selected

### ISSUE THREAD

**Issue by dubde** [infor-design/enterprise#982]
**Describe the bug**
In the popup menu, when I have some entries disabled, after I move the mouse over them and take it away they get the .is-selected background color, giving the feel that they are selectable.

**To Reproduce**
1. Have a dropdown menu with disabled options
2. Move the mouse over the option
3. Slide the cursor of the mouse "horizontally" till it is out of the menu
4. The entry get "selected" even if it's not enabled or with the mouse over it.

**Expected behavior**
The class .is-disabled should prevent .is-selected from changing the background of the item. It is curious that .is-disabled:hover behaves correctly, but when the :hover is off then get the highlight.

A solution could be to add "background-color: transparent" to .is-disabled.is-selected 

**Screenshots**
![image](https://user-images.githubusercontent.com/2682846/46787958-4c326080-cd39-11e8-8f2e-6a0981252791.png)

**Platform**
 - OS Version: Windows 10
 - Browser: Chrome

**Additional context**

**Comment by dubde** [comment]
For the moment, I solved it locally by putting in global styles.css  

```
.popupmenu li.is-focused.is-disabled,
 .popupmenu li.is-focused.disabled {
  background-color: transparent;
}
```

**Comment by brianjuan** [comment]
Hi @tmcconechy , where can we test the fix? /components/menubutton/test-disabled.html is not found on localhost and https://4140-beta0-enterprise.demo.design.infor.com/components/list

**Comment by dubde** [comment]
Hi @brianjuan you can check it here:

not working: https://4110-enterprise.demo.design.infor.com/components/popupmenu/example-disabled-submenus.html

working: https://4140-beta0-enterprise.demo.design.infor.com/components/popupmenu/example-disabled-submenus.html
