### ISSUE TITLE
Cleanup file matching on Demoapp directory list view

### ISSUE THREAD

**Issue by EdwardCoyle** [infor-design/enterprise#985]
**Is your feature request related to a problem? Please describe.**
We discovered that certain visual test file names wouldn't show up in the Demoapp's directory listing view (f.x., the page you see when going to http://master-enterprise.demo.design.infor.com/components/dropdown/).  This is because there were exclusions being made by the demoapp to avoid showing source code files, JS-based tests, and documentation MD files in this listing before we separated the source code from the demoapp views.  These exclusions need to be removed.

**Describe the solution you'd like**
There's an array of regex matches in [this file](https://github.com/infor-design/enterprise/blob/master/app/src/js/routes/directory-list.js#L10) that should be cleaned up to remove:
- anything that matches test file names (functional, api, etc)
- anything that matches file types that are not HTML

After we remove the unnecessary exclusions, we should view several directory views to make sure nothing is getting into the list that shouldn't be there.

**Comment by brianjuan** [comment]
http://localhost:4000/tests/listing/list
Both Api and Functional are displayed, moving to Done.
