### ISSUE TITLE
Forms: Two-column form input field alignment issue with static text

### ISSUE THREAD

**Issue by clepore** [infor-design/enterprise#987]
**Describe the bug**
When using a 2-column form, the input fields across from static text do not share the same spacing or alignment.

**To Reproduce**
1. See screenshot

**Expected behavior**
they should lineup with similar spacing to keep the columns even in height.

**Screenshots**
<img width="673" alt="screen shot 2018-10-11 at 9 16 55 am" src="https://user-images.githubusercontent.com/742319/46816217-7b050280-cd4a-11e8-849f-fd30419facf5.png">

**Platform**
- Web

**Additional context**
n/a

**Comment by tmcconechy** [comment]
We will need to make a forms example for this to fix in http://master-enterprise.demo.design.infor.com/components/form

Taking the "Data Labels" and laying them out like this screen shot http://master-enterprise.demo.design.infor.com/components/form/example-labels.html

Also the font size of Data Label should be changed to be the same font size as the field, so it will layout right and look consistent.

**Comment by janahintal** [comment]
Hello, Issue still exists in http://master-enterprise.demo.design.infor.com/components/form/test-long-labels.html
![image](https://user-images.githubusercontent.com/45757016/73822549-4ebfa000-4831-11ea-80fc-a5b519ce567a.png) whenever there is a field validation.

**Comment by tmcconechy** [comment]
No need to fail both issues. Will fix that point on https://github.com/infor-design/enterprise/issues/3115 if its possible. Might not be. Marking this as done
